### ISSUE TITLE
Build fails on Jetson Orin AGX

### ISSUE THREAD

**Issue by GiorgosBetsos** [PaddlePaddle/Paddle#45701]
### 问题描述 Issue Description

I have issued cmake like so:

cmake ..     -DWITH_CONTRIB=OFF     -DWITH_MKL=OFF     -DWITH_AVX=OFF     -DWITH_MKLDNN=OFF     -DWITH_TESTING=OFF     -DCMAKE_BUILD_TYPE=Release     -DON_INFER=ON     -DWITH_PYTHON=ON     -DWITH_XBYAK=OFF     -DWITH_NV_JETSON=ON     -DWITH_TENSORRT=ON     -DWITH_NCCL=OFF     -DPY_VERSION=3.8 -DWITH_GPU=ON -DPYTHON_LIBRARY:FILEPATH=/usr/lib/python3.8/config-3.8-aarch64-linux-gnu/libpython3.8.so -DPYTHON_INCLUDE_DIR:PATH=/usr/include/python3.8:/usr/include/python3.8 -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc

then I try to:

sudo cmake -j8

I get error:

make[1]: *** [CMakeFiles/Makefile2:10487: paddle/phi/kernels/funcs/CMakeFiles/segment_pooling.dir/all] Error 2
[ 19%] Linking CXX static library libcollective_helper.a
[ 19%] Built target collective_helper
[ 19%] Linking CXX static library libbackward_infermeta.a
[ 19%] Built target backward_infermeta
1 error detected in the compilation of "/home/nvidia/third-party-repos/Paddle/paddle/phi/kernels/funcs/matrix_reduce.cu".
make[2]: *** [paddle/phi/kernels/funcs/CMakeFiles/matrix_reduce.dir/build.make:76: paddle/phi/kernels/funcs/CMakeFiles/matrix_reduce.dir/matrix_reduce.cu.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:10259: paddle/phi/kernels/funcs/CMakeFiles/matrix_reduce.dir/all] Error 2
-- Using src='https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz'
-- Using src='https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz'
-- Retry after 15 seconds (attempt #4) ...
-- Retry after 15 seconds (attempt #4) ...
-- Using src='https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz'
-- Using src='https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz'
-- Retry after 60 seconds (attempt #5) ...
-- Retry after 60 seconds (attempt #5) ...
-- Using src='https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz'
-- Using src='https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz'
CMake Error at src/download_externalError-stamp/download-download_externalError.cmake:159 (message):
  Each download failed!

    error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---

CMake Error at extern_lapack-stamp/download-extern_lapack.cmake:159 (message):
  Each download failed!

    error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---
         error: downloading 'https://paddlepaddledeps.bj.bcebos.com/lapack_lnx_v3.10.0.20210628.tar.gz' failed
         status_code: 35
         status_string: "SSL connect error"
         log:
         --- LOG BEGIN ---
           Trying 103.235.46.61:443...

  TCP_NODELAY set

  Connected to paddlepaddledeps.bj.bcebos.com (103.235.46.61) port 443 (#0)

  ALPN, offering h2

  ALPN, offering http/1.1

  successfully set certificate verify locations:

    CAfile: /etc/ssl/certs/ca-certificates.crt
    CApath: /etc/ssl/certs

  [5 bytes data]

  TLSv1.3 (OUT), TLS handshake, Client hello (1):

  [512 bytes data]

  [5 bytes data]

  error:1408F10B:SSL routines:ssl3_get_record:wrong version number

  Closing connection 0

         --- LOG END ---

make[2]: *** [CMakeFiles/download_externalError.dir/build.make:91: third_party/externalError/src/download_externalError-stamp/download_externalError-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:5058: CMakeFiles/download_externalError.dir/all] Error 2
make[2]: *** [CMakeFiles/extern_lapack.dir/build.make:91: third_party/lapack/src/extern_lapack-stamp/extern_lapack-download] Error 1
make[1]: *** [CMakeFiles/Makefile2:4593: CMakeFiles/extern_lapack.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

### 版本&环境信息 Version & Environment Information

The supplied script doesn't work on Jetson Orin AGX Dev kit. Using another utility I got

NVIDIA Jetson AGX Orin
 L4T 35.1.0 [ JetPack 5.0.2 ]
   Ubuntu 20.04.4 LTS
   Kernel Version: 5.10.104-tegra
 CUDA 11.4.239
   CUDA Architecture: NONE
 OpenCV version: 4.5.4
   OpenCV Cuda: NO
 CUDNN: 8.4.1.50
 TensorRT: 8.4.1.5
 Vision Works: NOT_INSTALLED
 VPI: 2.1.6
 Vulcan: 1.3.203

**Comment by pangyoki** [comment]
It's a network problem, can you download this installation package using `wget` locally?

**Comment by jiguanglu** [comment]
mark
