### ISSUE TITLE
paddle.uniform api生成数值超过指定范围

### ISSUE THREAD

**Issue by TUDelftHao** [PaddlePaddle/Paddle#45713]
### bug描述 Describe the Bug
paddle版本：2.3.2
系统：MacOS， M1芯片

在使用paddle.uniform生成(-1，1)区间随机数时，会有一定概率出现返回值为-1或1的情况，导致后续计算log1p出现异常值。因为是随机生成，复现该bug可能需多次重复执行代码。

```python
import paddle
import numpy as np

eps = 0
shape = (30000, 2)
for i in range(10000):
    uniform = paddle.uniform(shape=shape,
                    min=float(np.nextafter(-1, 1)) + eps / 2,
                    max=1. - eps / 2,
                    dtype='float32')
    res = paddle.log1p(-uniform.abs())
    if paddle.any(paddle.isinf(res)):
        position = paddle.where(paddle.isinf(res))
        print("inf occurs: ", [position[0][0], position[1][0]])
        print("badcase: ", uniform[[position[0][0], position[1][0]]])
```

某次复现出的结果：
![image](https://user-images.githubusercontent.com/46449831/188273977-d9bb4c84-4392-428f-9ddb-3d8d95a265f3.png)

辛苦看下是我使用的问题还是uniform 算子实现存在bug。

**Comment by TUDelftHao** [comment]
It's my fault. Ignore it, please.

**Comment by zhiqiu** [comment]
hi，我本地跑出了-1，但是没有出现1。uniform是产生[min, max)的随机数， 建议设置 min > -1 试试。

**Comment by TUDelftHao** [comment]
> ```python
> np.nextafter(-1, 1)
> ```

hi，我使用了np.nextafter(-1, 1)这个函数生成的数就是趋近于-1但是不等于-1的值，所以-1这个数字应当也是不在uniform范围内的吧？
另外我重新跑了代码确实存在结果为1的情况
![image](https://user-images.githubusercontent.com/46449831/188386836-d9986527-97c6-44de-b658-bc168d3eb41d.png)


> hi，我本地跑出了-1，但是没有出现1。uniform是产生[min, max)的随机数， 建议设置 min > -1 试试。

**Comment by yuwoyizhan** [comment]
楼主说uniform是产生(min, max)的随机数,下面的zhiqiu说uniform是产生[min, max)的随机数,请问2位,这个结论是谁告诉你们的?
我听说飞桨底层都是C++实现的,上面采用python封装.据我了解,C++的uniform是产生[min,max],只不过由于min到max有无穷多个浮点数,导致了生成min和max都需要不少时间,有可能需要几小时才能复现.但是我很明确告诉你们,C++的uniform肯定可以产生min和max这两个值的,至少visual studio2022可以做到.我测试过很多次.

**Comment by zhiqiu** [comment]
> 楼主说uniform是产生(min, max)的随机数,下面的zhiqiu说uniform是产生[min, max)的随机数,请问2位,这个结论是谁告诉你们的? 我听说飞桨底层都是C++实现的,上面采用python封装.据我了解,C++的uniform是产生[min,max],只不过由于min到max有无穷多个浮点数,导致了生成min和max都需要不少时间,有可能需要几小时才能复现.但是我很明确告诉你们,C++的uniform肯定可以产生min和max这两个值的,至少visual studio2022可以做到.我测试过很多次.

是的，uniform的c++ kernel用的是std::uniform_real_distribution实现，c++文档说是[min, max)。参考：[cppreference](https://en.cppreference.com/w/cpp/numeric/random/uniform_real_distribution)
<img width="791" alt="image" src="https://user-images.githubusercontent.com/6888866/188560490-5b1fd172-b0cf-4593-bce7-dfee05a6c5be.png">

**Comment by zhiqiu** [comment]
> > ```python
> > np.nextafter(-1, 1)
> > ```
> 
> hi，我使用了np.nextafter(-1, 1)这个函数生成的数就是趋近于-1但是不等于-1的值，所以-1这个数字应当也是不在uniform范围内的吧？ 另外我重新跑了代码确实存在结果为1的情况 ![image](https://user-images.githubusercontent.com/46449831/188386836-d9986527-97c6-44de-b658-bc168d3eb41d.png)
> 
> > hi，我本地跑出了-1，但是没有出现1。uniform是产生[min, max)的随机数， 建议设置 min > -1 试试。

我推测你能得到-1和1还有一种可能，就是 你用的float32，精度不够，你可以使用float64再试试。

**Comment by TUDelftHao** [comment]
> > > ```python
> > > np.nextafter(-1, 1)
> > > ```
> > 
> > 
> > hi，我使用了np.nextafter(-1, 1)这个函数生成的数就是趋近于-1但是不等于-1的值，所以-1这个数字应当也是不在uniform范围内的吧？ 另外我重新跑了代码确实存在结果为1的情况 ![image](https://user-images.githubusercontent.com/46449831/188386836-d9986527-97c6-44de-b658-bc168d3eb41d.png)
> > > hi，我本地跑出了-1，但是没有出现1。uniform是产生[min, max)的随机数， 建议设置 min > -1 试试。
> 
> 我推测你能得到-1和1还有一种可能，就是 你用的float32，精度不够，你可以使用float64再试试。

hi, 用了float64的话确实没有出现这个情况，但是float32是paddle默认数据类型，这个是不是考虑严格支持一下？paddle.uniform默认也是float32。

**Comment by zhiqiu** [comment]
好的，我们会讨论下怎么修复哈。
