### ISSUE TITLE
Init OP

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#4575]
We need to implement init OP.

Discussed with @Canpio and @dzhwinter , the init OP should have the Variable to be inited as the output.

But it should **not** have the Variable to be inited as the input: the init OP is the start of the Var's read / write instructions, and uninitialized Variables should be be read. Thus the init OP should not have the Variable to be inited as the input.

**Comment by reyoung** [comment]
I think the initialize operator has been done by random operators, such as `uniform_random`.

**Comment by helinwang** [comment]
Sorry, thanks! I did not realize that.

**Comment by dzhwinter** [comment]
we discussed face to face and decided to solve the init process through `run_once` at present.
