### ISSUE TITLE
自定义logger，import paddle后，出现重复或多余的log打印

### ISSUE THREAD

**Issue by snow77** [PaddlePaddle/Paddle#45756]
### bug描述 Describe the Bug

如下列代码，自定义了一个log对象，log只打印到log.log文件，不会在控制流打印。如果不加载paddle包，效果是对的，加载paddle包以后，在命令行出现了打印（这个打印按照代码只应该打印到文件）。说明paddle内部的log机制导致了此问题

import logging
from logging.handlers import RotatingFileHandler

import paddle

fileName = 'test.log'
fileLevel = logging.DEBUG

logger = logging.getLogger(fileName)
logging.Logger.manager.loggerDict.pop(fileName)
logger.handlers = []
logger.removeHandler(logger.handlers)
formatter = logging.Formatter("[%(asctime)s] [%(levelname)s] %(message)s")
logger.setLevel(logging.DEBUG)
fileHandler = RotatingFileHandler(filename = fileName, 
                                  maxBytes = 4 * 1024 * 1024, backupCount = 400)
fileHandler.setFormatter(formatter)
fileHandler.setLevel(fileLevel)
logger.addHandler(fileHandler)

logger.warning('这一行log只打印到log.log，控制流不应该打印')

### 其他补充信息 Additional Supplementary Information

如果可能，paddle是否可以提供一个log开关，很多时候需要关闭多余的打印

**Comment by wangna11BD** [comment]
我在V100，python3.8， develop版本paddle，cuda10.2环境下跑了一下，加或不加paddle打印出的log是一样的，都是只生成了test.log文件，文件内容为 [2022-09-05 10:58:27,783] [WARNING] 这一行log只打印到log.log，控制流不应该打印

**Comment by snow77** [comment]
我这边是一直会多打印一行，是不是环境或者版本哪儿不一致？我也是百度员工，可以如流联系我liubingxing



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月5日(周一) 晚上7:02
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 自定义logger，import paddle后，出现重复或多余的log打印 (Issue #45756)




 
我在V100，python3.8， develop版本paddle，cuda10.2环境下跑了一下，加或不加paddle打印出的log是一样的，都是只生成了test.log文件，文件内容为 [2022-09-05 10:58:27,783] [WARNING] 这一行log只打印到log.log，控制流不应该打印
