### ISSUE TITLE
【论文复现赛第七期】静态图预测输出结果为Nan

### ISSUE THREAD

**Issue by kongdebug** [PaddlePaddle/Paddle#45767]
### 请提出你的问题 Please ask your question

图像去噪任务，使用动态图预测结果正常，但是转为静态图（没有报错）之后，使用paddleinference预测，结果为nan，对照了预处理部分，输入静态图与动态图的数据是一致的，不知道这个错误该如何解决呢？

**Comment by kongdebug** [comment]
改为用cpu的静态图推理则没问题，gpu的推理输出为nan，真的很疑惑

**Comment by Aurelius84** [comment]
请问是使用paddleinference 在CPU下推理结果没有问题，但切换到GPU设备上跑，会出现结果为NaN的情况么？

**Comment by kongdebug** [comment]
> 请问是使用paddleinference 在CPU下推理结果没有问题，但切换到GPU设备上跑，会出现结果为NaN的情况么？

是的，我测试了2.1.2到2.3.2，GPU/CPU不同推理模式，发现就2.1.2和2.2.2的CPU推理正常，其他均为NAN的情况，不知道发生什么问题了

**Comment by kongdebug** [comment]
> 请问是使用paddleinference 在CPU下推理结果没有问题，但切换到GPU设备上跑，会出现结果为NaN的情况么？

您好，请问有没有解决的呢
