### ISSUE TITLE
【论文复现】反向对齐验证时梯度无法对齐

### ISSUE THREAD

**Issue by dorren002** [PaddlePaddle/Paddle#45780]
### 请提出你的问题 Please ask your question

我们在反向对齐时发现第一轮的loss是对齐的，但是第二轮无法对齐，因此按照复现文档向前排查，发现从倒数第四个线性层开始梯度无法对齐。也就是后面三层是对齐的，第四层开始无法对齐，请问有什么新的排查思路吗？优化器使用Momentum和Adam结果都对不齐。

**Comment by Lllllolita** [comment]
同时，我们在测试过程中，输出前向对齐的结果，发现Tensor在经过一层线性层之后的diff，是经过线性层之前的diff的三倍。请问这个级别的差异是正常的吗？是否存在某些问题，导致线性层前向、反向运算出现diff，使得最终结果无法对齐？

**Comment by LemonNoel** [comment]
可以检查下参数初始化是否一致，如果diff较小，可以看下Layer中的其他默认参数配置是否一致。

**Comment by LemonNoel** [comment]
反向可以打印grad验证，优化器需要按原有实现对齐。

**Comment by Lllllolita** [comment]
加载同样的模型，使用model.eval()和FLAGS_cudnn_deterministic = True，还固定了随机种子。前向输出、前向loss和最后一层的grad还是能对齐的，但反向倒数第二层的grad开始出现diff。请问这种情况，只能检查模型参数了吗？

**Comment by LemonNoel** [comment]
优化器部分默认设计上会有所区别，如果不考虑单步的差异，现在整体训练下来能够复现结果吗？

**Comment by Lllllolita** [comment]
正在整体训练，如果结果能达到精度指标，可以验收吗？

**Comment by LemonNoel** [comment]
整体训练精度按照要求达标应该是可以的，如果不能的话就需要排查下是否中间还有其他问题。
