### ISSUE TITLE
怎样在notebooks上使用多gpu训练？

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#45791]
### bug描述 Describe the Bug

您好，官方文档都是针对python脚本进行多gpu训练，请问怎么在notebook上进行多gpu训练。李沐老师的《动手学习深度学习》的代码由于不支持多gpu训练，相比pytorch，训练效率比较低

https://github.com/d2l-ai/d2l-zh/pull/1198

**Comment by LemonNoel** [comment]
您好，在notebook上同样可以将代码放在文件中，使用python脚本进行多GPU训练。如果需要notebook block默认多GPU训练，建议到AIStudio交流群提问哈，官方QQ: 580959619

**Comment by sljlp** [comment]
可以开启多个Notebook，每个Notebook占用一个GPU，配置环境稍微比较麻烦
可以首先使用launch按照脚本的方式启动一下，获取启动后每个进程的环境变量，然后相应地配置到对应notebook里
这样就可以使用分布式环境了
