### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1: invalid continuation byte

### ISSUE THREAD

**Issue by Hoonly** [PaddlePaddle/Paddle#45801]
### bug描述 Describe the Bug

paddle源码编译安装
分支：develop
commit id：a119686ce108c4e1880182e423bf0a6f26db759a
编译安装后执行以下命令验证
`paddle.utils.run_check()`
在程序执行到
`program.desc.cached_hash_str()`时
出现解码错误
```*** UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 1: invalid continuation byte```
将python/paddle/fluid/executor.py中 `_run_impl`函数
`key = _get_strong_program_cache_key_for_new_exe(
                    inner_program, feed, fetch_list)`
回退版本到
`key = _get_strong_program_cache_key(
                    inner_program, feed, fetch_list)`
解决了这个问题
具体原因需要进一步查找

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。

**Comment by zhiqiu** [comment]
你的编译选项是什么？

**Comment by Hoonly** [comment]
> 你的编译选项是什么？

![图片](https://user-images.githubusercontent.com/20243833/188804636-121a8967-32ac-412e-a6b2-4f28ab4e352c.png)

**Comment by zhiqiu** [comment]
你把crypto编译打开试试

**Comment by Hoonly** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，您的邮件我已收到，谢谢。
