### ISSUE TITLE
confusing usage of  "std::make_shared<phi::DenseTensorMeta>(phi::DenseTensorMeta)"

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45818]
### 请提出你的问题 Please ask your question

paddle\fluid\eager\grad_node_info.h
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31559413/188772311-5044ab90-d03a-4c7f-942e-d99ab86803a6.png">

I'm confused about the usage of  `std::make_shared<phi::DenseTensorMeta>(meta);`
It seems to use  `std::make_shared<phi::DenseTensorMeta>(phi::DenseTensorMeta),` which doesn't make sense to me.     
If the original code is meant to use move constructor,  there is no definition of move constructor of `phi::DenseTensorMeta`    
I am referring to the following material:   

https://en.cppreference.com/w/cpp/memory/shared_ptr/make_shared   
```C++
template< class T, class... Args >
shared_ptr<T> make_shared( Args&&... args );
```

**Comment by OccupyMars2025** [comment]
It's ok NOT to answer this question. It's not urgent.  I just take down my confusion here for  my future reference.

**Comment by DesmonDay** [comment]
``` C++
template< class T, class... Args >
shared_ptr<T> make_shared( Args&&... args );
```

Actually this kind of usage still match this template, where we have T and Args are both phi::DenseTensorMeta. Then we can have ``shared_ptr<phi::DenseTensorMeta> a = make_shared<phi::DenseTensorMeta>(meta)``. You can find many other examples, like ``shared_ptr<int> a = make_shared(42), shared_ptr<string> b = make_shared<string>(10, '9')``.
