### ISSUE TITLE
《论文复现》现在没有cuda11.3对应的paddle-gpu版本吗？

### ISSUE THREAD

**Issue by Lllllolita** [PaddlePaddle/Paddle#45827]
### 请提出你的问题 Please ask your question

是否可以向下兼容，使用cuda11.6对应的paddle-gpu版本，在cuda11.3的环境中运行？

**Comment by DesmonDay** [comment]
https://github.com/PaddlePaddle/Paddle/issues/44980 可以看看这个issue哈，可以使用飞桨官网提供的pip cuda11.2 的安装包，是可以cuda11.3 环境中使用的。

**Comment by Lllllolita** [comment]
好的，已解决。感谢您的回复
