### ISSUE TITLE
where算子在compiled_with_xpu情况下出错

### ISSUE THREAD

**Issue by Hoonly** [PaddlePaddle/Paddle#45830]
### bug描述 Describe the Bug

`python/paddle/tensor/search.py`

当where算子中的X==inf时，走到如下分支时会出现inf*0=nan的情况，由于xpu上实现了where op，是否考虑将这个条件分支删除

<img width="659" alt="图片" src="https://user-images.githubusercontent.com/20243833/188796656-ed8a0634-e8f5-4ee6-88ce-37e44c6bf324.png">

**Comment by DesmonDay** [comment]
想问问，有测试过去掉这个条件分支之后，xpu环境下能正常运行吗？

**Comment by Hoonly** [comment]
> 想问问，有测试过去掉这个条件分支之后，xpu环境下能正常运行吗？

可以正常运行，结果没有问题

**Comment by DesmonDay** [comment]
ok，那你这边是否方便提个PR呢？然后可以的话再贴一下正常运行的截图之类的，不方便的话我就自己来修改了。

**Comment by Hoonly** [comment]
> ok，那你这边是否方便提个PR呢？然后可以的话再贴一下正常运行的截图之类的，不方便的话我就自己来修改了。

您那边修改吧 感谢

**Comment by DesmonDay** [comment]
嗯嗯，ok

**Comment by DesmonDay** [comment]
hello，能否简单贴一个测试代码呢？

**Comment by Hoonly** [comment]
> hello，能否简单贴一个测试代码呢？

我这边之前是测的一个模型，我简单整理下贴过来吧，需要点时间

**Comment by DesmonDay** [comment]
好的，谢谢

**Comment by DesmonDay** [comment]
已修复：https://github.com/PaddlePaddle/Paddle/pull/45832
