### ISSUE TITLE
deformable_conv算子的im2col_step参数问题

### ISSUE THREAD

**Issue by Rayman96** [PaddlePaddle/Paddle#45847]
### 请提出你的问题 Please ask your question

在paddle中deformable_conv有两个入口：
1. paddle.vision.ops.deform_conv2d[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/vision/ops/deform_conv2d_cn.html#deform-conv2d]
2. paddle.static.nn.deform_conv2d[https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/deform_conv2d_cn.html#deform-conv2d]

在benchmark和单测中都使用的vision.ops的入口，然而这个入口取消了im2col_step这个参数，在执行过程中将次参数默认设置成为1。这个参数我的理解只是增大单次计算的图片数量，如果我手动在代码中增大im2col_step的取值，理论上应该是可以正常运行获得正确结果的，但是真实的计算结果却会和im2col_step=1时不一致。

想请问下：vision.ops.deform_conv2d取消im2col_step参数的原因以及增大im2col_step得到的结果错误是否是已知情况。

**Comment by Ligoml** [comment]
@ZzSean

**Comment by Rayman96** [comment]
deformable_conv作者实现的代码中提到
https://github.com/msracver/Deformable-ConvNets/tree/master/DCNv2_op
![image](https://user-images.githubusercontent.com/35597076/188851733-c665e195-2e53-4ccc-adce-56d49c7083c6.png)

从代码上看，不同的im2col_step只是并行速度上变化，应该不会影响最终结果才对。 我是在做hackathon的38题时发现的，我设想的一条优化思路落实下来就是合理增大im2col_step，但增大了发现结果不一致了😂

**Comment by Rayman96** [comment]
找到原因了，目前deformable实现中的output_4d的维度是
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/35597076/190604836-ee327298-9d7f-4cf5-8720-84827df50ea7.png">
在最终计算完output_3d后需要swap axis[1]和axis[2]才正确。
