### ISSUE TITLE
snprintf -Werror=format-security error on GCC9

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#45871]
### bug描述 Describe the Bug

cmake .. 
make

[  9%] Building CXX object paddle/fluid/platform/profiler/CMakeFiles/profiler_logger.dir/chrometracing_logger.cc.o
In file included from /home/wjl/github/Paddle/paddle/fluid/platform/profiler/chrometracing_logger.cc:26:
/home/wjl/github/Paddle/paddle/fluid/platform/profiler/utils.h: In instantiation of ‘std::string paddle::platform::string_format(const string&, Args ...) [with Args = {}; std::string = std::__cxx11::basic_string<char>]’:
/home/wjl/github/Paddle/paddle/fluid/platform/profiler/chrometracing_logger.cc:552:36:   required from here
/home/wjl/github/Paddle/paddle/fluid/platform/profiler/utils.h:32:29: error: format not a string literal and no format arguments [-Werror=format-security]
   32 |   int size_s = std::snprintf(nullptr, 0, format.c_str(), args...) +
      |                ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/wjl/github/Paddle/paddle/fluid/platform/profiler/utils.h:40:16: error: format not a string literal and no format arguments [-Werror=format-security]
   40 |   std::snprintf(buf.get(), size, format.c_str(), args...);
      |   ~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors

Compiler : GCC 9.4.0

**Comment by rainyfly** [comment]
你好，该warning已经提pr修复了，https://github.com/PaddlePaddle/Paddle/pull/45870 ， 等合入后重新拉一下

**Comment by engineer1109** [comment]
Fix confirmed
