### ISSUE TITLE
Operator multiclass_nms3 has not been registered 

### ISSUE THREAD

**Issue by luowenhong01** [PaddlePaddle/Paddle#45884]
### 请提出你的问题 Please ask your question

使用paddle2.0版本出现Operator multiclass_nms3 has not been registered问题，更新paddle2.2版本后可以解决。请问在不更版本的情况下如何解决这个问题。如果不行替换成paddle2.2版本的是否能与原版本兼容？

**Comment by haoyuying** [comment]
您好，请问您使用2.2版本会有什么问题呢，如果有，请提供具体的问题，如果没有，建议您使用新版paddle，2.2相对于2.0更新内容较多。

**Comment by luowenhong01** [comment]
> 
请问2.2版本和2.0版本是完全兼容的吗？

**Comment by haoyuying** [comment]
2.2在2.0的基础上肯定会有很多bug修复及其他功能的阔充，建议使用2.2版本的paddle
