### ISSUE TITLE
Build error after "Update protobuf output format for profiler"

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#45885]
### 问题描述 Issue Description

Commit 23bc0e3cf9c948fc65baacc436bb8b0786417ee1 causes build error, reproduced on several machines (SKX, CLX, CPX, SPR)

![image](https://user-images.githubusercontent.com/10847947/189078744-9f9cded3-b2fe-482a-9e0c-e00feb91bbcd.png)
(…)
![image](https://user-images.githubusercontent.com/10847947/189078888-1c7ac8d9-da96-4991-a345-e6e65302ac3b.png)

### PaddlePaddle branch: 
develop

### CMAKE Flags:
``
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/data/PaddlePaddle/pp_models -DPY_VERSION=3.6
``
### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.10.2
      Compiler: GCC 8.4
```

**Comment by haoyuying** [comment]
Hi, this warning has been fixed in https://github.com/PaddlePaddle/Paddle/pull/45870, you may pull the new code after this pr merged.

**Comment by haoyuying** [comment]
由于用户没有继续更新，该问题先暂时关闭，若后续更新，用户可自行打开。
