### ISSUE TITLE
Compile Error: name followed by "::" must be a class or namespace name

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#45881]
### 问题描述 Issue Description

[ 35%] Building CUDA object paddle/phi/kernels/CMakeFiles/phi_gpu.dir/gpu/group_norm_grad_kernel.cu.o
/home/wjl/github/Paddle/paddle/phi/kernels/gpu/group_norm_grad_kernel.cu(74): error: name followed by "::" must be a class or namespace name
          detected during instantiation of "void phi::GroupNormGradKernel<T,Context>(const Context &, const phi::DenseTensor &, const paddle::optional<phi::DenseTensor> &, const paddle::optional<phi::DenseTensor> &, const phi::DenseTensor &, const phi::DenseTensor &, const phi::DenseTensor &, const phi::DenseTensor &, float, int, const std::string &, phi::DenseTensor *, phi::DenseTensor *, phi::DenseTensor *) [with T=float, Context=phi::GPUContext]" 
(464): here

/home/wjl/github/Paddle/paddle/phi/kernels/gpu/group_norm_grad_kernel.cu(81): error: name followed by "::" must be a class or namespace name
          detected during instantiation of "void phi::GroupNormGradKernel<T,Context>(const Context &, const phi::DenseTensor &, const paddle::optional<phi::DenseTensor> &, const paddle::optional<phi::DenseTensor> &, const phi::DenseTensor &, const phi::DenseTensor &, const phi::DenseTensor &, const phi::DenseTensor &, float, int, const std::string &, phi::DenseTensor *, phi::DenseTensor *, phi::DenseTensor *) [with T=float, Context=phi::GPUContext]" 
(464): here

### 版本&环境信息 Version & Environment Information

Paddle Version: Develop
With_CUDA
CPU I7 12700  
Ubuntu 20.04 GCC 9.4.0

**Comment by engineer1109** [comment]
use CudaAtomicAddWithWarp to replace to solve platform::CudaAtomicAdd.

for #Line 72

```
  if (flags & kHasScale) {
#if CUDA_VERSION >= 11070
    CudaAtomicAddWithWarp(&(d_scale[ccid]), d_scale_data);
#else
    CudaAtomicAddWithWarp(&(d_scale[ccid]), d_scale_data);
#endif
  }
  if (flags & kHasBias) {
#if CUDA_VERSION >= 11070
    CudaAtomicAddWithWarp(&(d_bias[ccid]), d_bias_data);
#else
    CudaAtomicAddWithWarp(&(d_bias[ccid]), d_bias_data);
#endif
  }
```

**Comment by engineer1109** [comment]
老的写法明明对的，为啥要给CUDA 11.7开分支宏

**Comment by LielinJiang** [comment]
11.7 老的写法有问题

**Comment by haoyuying** [comment]
您好，该问题已经修复，请拉取新代码尝试：https://github.com/PaddlePaddle/Paddle/pull/45738/files

**Comment by engineer1109** [comment]
@haoyuying Fix Still error.
platform::CudaAtomicAdd  is wrong.
Should be
```
#if CUDA_VERSION >= 11070
    paddle::platform::CudaAtomicAdd(&(d_scale[ccid]), d_scale_data);
#else
```
lack namespace.

**Comment by engineer1109** [comment]
Addtional Fix #45904
合并时 注意下命名空间要写全，不然还是错
@haoyuying

**Comment by haoyuying** [comment]
收到，感谢您的反馈。

**Comment by engineer1109** [comment]
@haoyuying   问题已经找到
[group_norm_grad_kernel.cu](https://github.com/PaddlePaddle/Paddle/pull/45904/commits/4c0b03ade817106af5d4b776fa02aeab689aa36d)
是在namspace phi里
所以platform::CudaAtomicAdd是错误的
必须要paddle::platform::CudaAtomicAdd
[group_norm_op.cu](https://github.com/PaddlePaddle/Paddle/pull/45904/files/aeb29016d6ceccf8970812b133656190e5df1118#diff-2224a64cd516dcdf44b0804e6978e475660f86f0fa3d02cb983209412e8d560e)
已经在namespace paddle里，所以platform::CudaAtomicAdd可以使用。

为了代码安全，尽量写全命名空间为好。

**Comment by luotao1** [comment]
close due to #45925
