### ISSUE TITLE
want to put  "PyObject_HEAD" at a single line in the PaddlePaddle source code

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#45880]
### 请提出你的问题 Please ask your question

I want to put  "PyObject_HEAD" at a single line in the PaddlePaddle source code,  but  this will fail  
PR-CI-Codestyle-Check like the following:  
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31559413/189070463-5c76878a-5ed2-4213-a10c-1bdf15fa6b9c.png">
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/6568249/job/18261672

According to the definition of  PyObject_HEAD,  it's better to put it at  a single line :
![e81d31e00e3c1fe636224d80f4b50f2](https://user-images.githubusercontent.com/31559413/189070701-ed84df59-4e75-4124-a3e9-4dbd6aecd487.jpg)

Is there  any  possible solution to this problem ?

**Comment by haoyuying** [comment]
sorry， it is the ci code style requirements, you must follow code style requirements.
