### ISSUE TITLE
CRF demo Core 了，什么问题？

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#459]
I1114 14:26:55.183913 25598 Util.cpp:138] commandline: /home/work/sunkai/paddle2nd/baidu/idl/install_dir/bin/../opt/paddle/bin/paddle_trainer --config rnn_crf.py --parallel_nn=1 --use_gpu=1 --dot_period=10 --log_period=1000 --test_period=0 --num_passes=10 
I1114 14:26:55.184221 25598 Util.cpp:113] Calling runInitFunctions
I1114 14:26:55.184581 25598 Util.cpp:126] Call runInitFunctions done.
Traceback (most recent call last):
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3130, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py", line 3106, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "rnn_crf.py", line 32, in <module>
    learning_rate_decay_b = 0.5,
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
  File "/home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
    return func(*args, **kwargs)
TypeError: settings() got an unexpected keyword argument 'learning_rate_decay_a'
F1114 14:26:55.435573 25598 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type 'exceptions.TypeError'> : settings() got an unexpected keyword argument 'learning_rate_decay_a'
Python Callstack: 
            /home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py : 3130
            /home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer/config_parser.py : 3106
            rnn_crf.py : 32
            /home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/default_decorators.py : 45
            /home/work/.jumbo/lib/python2.7/site-packages/paddle-0.8.0b0-py2.7.egg/paddle/trainer_config_helpers/default_decorators.py : 45
Call Object failed.
*** Check failure stack trace: ***
    @     0x7fc1fdfc26ed  google::LogMessage::Fail()
    @     0x7fc1fdfc6e50  google::LogMessage::SendToLog()
    @     0x7fc1fdfc3217  google::LogMessage::Flush()
    @     0x7fc1fdfc3476  google::LogMessageFatal::~LogMessageFatal()
    @           0x7bd9c7  paddle::callPythonFuncRetPyObj()
    @           0x7bdd2c  paddle::callPythonFunc()
    @           0x6f0f93  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x6f15d4  paddle::TrainerConfigHelper::createFromFlags()
    @           0x5405b3  main
    @     0x7fc1fc6dabd5  __libc_start_main
    @           0x54bf15  (unknown)
/home/work/sunkai/paddle2nd/baidu/idl/install_dir/bin/paddle: line 81: 25598 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer

**Comment by hedaoyuan** [comment]
把配置文件贴一下。
> TypeError: settings() got an unexpected keyword argument 'learning_rate_decay_a'
> F1114 14:26:55.435573 25598 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type

**Comment by VamWolf** [comment]
demo 里面的配置.

**Comment by qingqing01** [comment]
@VamWolf 
```
TypeError: settings() got an unexpected keyword argument 'learning_rate_decay_a'
```
看着是你的paddle安装较老。 ```pip uninstall paddle``` 再试试。
