### ISSUE TITLE
【论文复现】CvT: Introducing Convolutions to Vision Transformers

### ISSUE THREAD

**Issue by caikw0602** [PaddlePaddle/Paddle#45908]
### 数据集解压问题

百度团队你好：
        我队目前正在参加论文复现赛，选择的是CvT图像分类任务，现在需要采用了单机4卡进行ImageNet数据集的训练，目前有以下问题。
       通过查看日志（如下图所示），验证数据集并没有解压，就已经开始训练，导致执行验证代码时找不到图像样本。我是采用与行run.py方式进行脚本提交的，具体写法如下，请问我应该怎样修改代码，可以保证训练和验证数据集都解压以后，才开始运行train的程序呢？第一次复现，小白一名，还请见谅。
       
<img width="881" alt="解压后训练" src="https://user-images.githubusercontent.com/45365909/189266626-3b7c2fdc-f907-4f24-9eac-55eb109dcb33.png">

<img width="885" alt="2" src="https://user-images.githubusercontent.com/45365909/189266659-9c17c16f-767f-412e-a99c-d2ddee84dee2.png">

具体使用的run.py为：

<img width="729" alt="image" src="https://user-images.githubusercontent.com/45365909/189267275-7cdb3b93-bf71-4cea-8c3f-d3e40499087d.png">

**Comment by juncaipeng** [comment]
你可以通过termial查看解压数据是否完成，可能也是数据路径没有存放正确。
os.system命令是阻塞的，应该是按照顺序执行，不过还是建议换成shell脚本执行解压和训练的命令。

**Comment by caikw0602** [comment]
感谢回复，请问在脚本运行的情况下，哪里找terminal呢？

**Comment by juncaipeng** [comment]
如果是ai studio，是可以开启terminal的。

**Comment by caikw0602** [comment]
感谢您的回复。我是新建立的脚本任务，没有看到开启terminal的按钮？
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/45365909/189349568-90fde858-9da1-4e4c-b681-fa50b8a215a6.png">

**Comment by caikw0602** [comment]
百度团队你好：
       针对这个问题我找到原因了，我解压出来的val数据集保存路径和val_list.txt中的路径不一致，从而导致找不到val数据，解压出来的路径没有类别文件夹。请问我应该怎么解决呢？我采用的是./data114746/Light_ILSVRC2012_part_1.tar数据集。
<img width="644" alt="image" src="https://user-images.githubusercontent.com/45365909/189490133-fdd02e83-577e-4770-b50c-138ea7d9ec4f.png">

**Comment by juncaipeng** [comment]
你这是两类不同的数据集整理方式。 
你可以在ai studio上找找还有没有符合你要求的数据集格式，或者参考paddleclas的文档看看，或者问问论文复现赛的答疑同学。
