### ISSUE TITLE
dataloader 加载问题

### ISSUE THREAD

**Issue by r0103** [PaddlePaddle/Paddle#45905]
### 请提出你的问题 Please ask your question

dataloader 加载数据，1024个数据一个batch，120000000数据，按理说应该11万个batch 就用完所有数据了，该下一epoch了。可是我发现一直加载到第30多万都还在继续加载。

1. 这种dataloader 加载方式，是会不停重复数据吗？
2. 如果是，那我设置每50000次break，开始下一epoch，每一个epoch 加载的数据相同吗？能充分利用上所有数据吗？

**Comment by juncaipeng** [comment]
1、dataloader是会不断循环读取data，不会终止。 
2、可以充分利用，会继续读取后续的数据。
