### ISSUE TITLE
您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢

### ISSUE THREAD

**Issue by PMPBinZhang** [PaddlePaddle/Paddle#45914]
### 请提出你的问题 Please ask your question

![Uploading 1662704415313(1).jpg…]()

**Comment by engineer1109** [comment]
友情提示： 图片无法显示

**Comment by juncaipeng** [comment]
你可以把log信息贴出来

**Comment by PMPBinZhang** [comment]
D:\Anaconda\envs\ai_platform\python.exe D:/work/vin/20220902_ocr_flask_server_kafka/extro_op/graphic_memory_text.py
2022-09-09 14:09:25,643-WARNING: type object 'QuantizationTransformPass' has no attribute '_supported_quantizable_op_type'
2022-09-09 14:09:25,643-WARNING: If you want to use training-aware and post-training quantization, please use Paddle >= 1.8.4 or develop version
D:\Anaconda\envs\ai_platform\lib\site-packages\paddlex\ppcls\data\preprocess\ops\timm_autoaugment.py:38: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
 _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
D:\Anaconda\envs\ai_platform\lib\site-packages\paddlex\ppcls\data\preprocess\ops\timm_autoaugment.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
 _RANDOM_INTERPOLATION = (Image.BILINEAR, Image.BICUBIC)
2022-09-09 14:09:27 [INFO] Model[YOLOv3] loaded.
Traceback (most recent call last):
 File "D:/work/vin/20220902_ocr_flask_server_kafka/extro_op/graphic_memory_text.py", line 18, in
   res = model.predict(imgs)
 File "D:\Anaconda\envs\ai_platform\lib\site-packages\paddlex\deploy.py", line 256, in predict
   images=images, topk=topk, transforms=transforms)
 File "D:\Anaconda\envs\ai_platform\lib\site-packages\paddlex\deploy.py", line 211, in _run
   net_outputs = self.raw_predict(preprocessed_input)
 File "D:\Anaconda\envs\ai_platform\lib\site-packages\paddlex\deploy.py", line 196, in raw_predict
   self.predictor.run()
RuntimeError: ResourceExhaustedError:

Out of memory error on GPU 0. Cannot allocate 2.441406GB memory on GPU 0, 5.063965GB memory has been allocated and available memory is only 18.935547GB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.

(at ..\paddle\fluid\memory\allocation\cuda_allocator.cc:87)


| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 15:03 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

你可以把log信息贴出来

**Comment by yeyupiaoling** [comment]
@PMPBinZhang 这的确是显存不足，减少batch size试试

**Comment by PMPBinZhang** [comment]
avaliable明显大于需要的啊，而且我观察我的显卡占用状态，连一半都不到。您仔细看了log了吗？另外，咱们这个paddlex的安装，在python3.9版本安装不了吗？提示的0.23.2版本的scikit-learn无法安装。


| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 16:09 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

@PMPBinZhang 这的确是显存不足，减少batch size试试

**Comment by yeyupiaoling** [comment]
这个日志就是显存不足，

**Comment by PMPBinZhang** [comment]
我能看明白英文翻译是显存不足，我不懂为什么会显存不足，我显卡剩余的空间明显大于需要的空间。
| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 16:14 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

这个日志就是显存不足，

**Comment by yeyupiaoling** [comment]
可能是初始化需要这些内存，但是后面训练时会变化的

**Comment by PMPBinZhang** [comment]
另外，3090的显卡，batch_size给4都跑不动，是不是有点奇怪呢，另外，您这边知道paddlex相关的知识吗？有一些问题需要咨询


| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 16:17 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

可能是初始化需要这些内存，但是后面训练时会变化的

**Comment by juncaipeng** [comment]
paddlex的问题，建议在paddlex repo下提issue，估计是设置了可以使用的显存大小。

**Comment by PMPBinZhang** [comment]
您好，我是用conda安装的11.6版本的paddlepaddle，报cudnn的错误。   
File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
     outputs = self.forward(*inputs, **kwargs)
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddlex\ppdet\modeling\backbones\darknet.py", line 76, in forward
     out = self.conv(inputs)
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
     return self._dygraph_call_func(*inputs, **kwargs)
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
     outputs = self.forward(*inputs, **kwargs)
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\nn\layer\conv.py", line 666, in forward
     out = F.conv._conv_nd(
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\nn\functional\conv.py", line 168, in _conv_nd
     helper.append_op(
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\layer_helper.py", line 44, in append_op
     return self.main_program.current_block().append_op(*args, **kwargs)
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\framework.py", line 3615, in append_op
     op = Operator(
   File "D:\Anaconda3\envs\mm\lib\site-packages\paddle\fluid\framework.py", line 2635, in __init__
     for frame in traceback.extract_stack():

   ExternalError: CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
     [Hint: 'CUDNN_STATUS_EXECUTION_FAILED'.  The GPU program failed to execute. This is usually caused by a failure to launch some cuDNN kernel on the GPU, which can occur for multiple reasons.  To correct, check that the hardware, an appropriate version of the driver, and the cuDNN library are correctly installed.  Otherwise, this may indicate an internal error/bug in the library.  ] (at C:\home\workspace\Paddle\paddle\fluid\operators\fused\conv_fusion_op.cu:373)
     [operator  error]


| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 16:54 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

paddlex的问题，建议在paddlex repo下提issue，估计是设置了可以使用的显存大小。

**Comment by yeyupiaoling** [comment]
windows 好像只有CUDA 10.2版本才是正常的

**Comment by PMPBinZhang** [comment]
我之前用过11.2，可以用。但是gpu使用利用率不全，现在我寻思改为11.6版本的，看一下效果。


| |
Wenwu Zhang
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月9日 17:03 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 您好，我这显存空间剩余明显大于需要的，为什么还是会报显存空间不足呢 (Issue #45914) |

windows 好像只有CUDA 10.2版本才是正常的

**Comment by juncaipeng** [comment]
通常最新的CUDA版本，支持的完善度没有稳定版本高。

**Comment by FlyingQianMM** [comment]
日志显示显存不足，麻烦贴一下运行的代码，看下是否是API使用上的问题。
