### ISSUE TITLE
IndexError: (OutOfRange) 索引超出范围报错

### ISSUE THREAD

**Issue by Beichen-Ma** [PaddlePaddle/Paddle#45948]
### 请提出你的问题 Please ask your question

我的代码是：
layer_weight = paddle.zeros([nearon_nums]) # nearon_nums = 64
for i in range(nearon_nums):
    layer_weight[i] = paddle.sum(paddle.abs(paddle.t(layer.weight)[i])) \
                              + paddle.sum(paddle.abs(model.prunable_layers[layer_index+1].weight), axis=0)[i]

创建的 layer_weight.shape=[64]， 但是遇到报错：IndexError: (OutOfRange) The starting index 10 of slice is out of bounds in tensor 0-th axis, it shound be in the range of [-10, 10). (at /home/Paddle/paddle/fluid/pybind/slice_utils.h:197)。为什么会有索引超出范围的报错？显示索引的范围只能是在[-10， 10）

**Comment by Bingoang** [comment]
@Beichen-Ma 兄弟你好，我也遇到同样的问题，请问你是怎么解决的？

**Comment by impactcolor** [comment]
Same here, any word on a fix?
