### ISSUE TITLE
paddle.Generator

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#45945]
### 需求描述 Feature Description

复现diffusers代码，发现这个仓库使用了generator
```python
generator=torch.Generator().manul_seed(42)
tensor1＝torch.randn(1,2,generator=generator)
tensor2＝torch.randn(10,20,generator=generator)
```
这一个generator给两个生成随机数的算子使用了，我的理解是generator相当于生成一串随机数（打个比方），第一次的时候tensor1消耗了1个，然后tensor2在上一个基础上继续消耗1个。
Paddle目前只有全局设置随机种子，不确定是否一致。

### 替代实现 Alternatives

无

**Comment by juncaipeng** [comment]
对的，目前paddle只有通过`paddle.seed(102)`设置全局默认generator的随机种子。 
如果从随机性考虑，应该是一致的。但是如果从paddle和torch对齐的角度来看，由于paddle只有一个全局的generator，可能无法生成顺序一致的随机数。

**Comment by JunnYu** [comment]
明白了，谢谢，建议以后添加一个这个generator。
