### ISSUE TITLE
训练后期显存突增了10G

### ISSUE THREAD

**Issue by Lllllolita** [PaddlePaddle/Paddle#45972]
### 请提出你的问题 Please ask your question

设置总共训练240epoch，每个epoch训练结束后进行验证。前期显存占用大概是24G，到了220epoch突然增加了10G，然后CUDA报错OOM。请问有可能是什么原因造成的？

**Comment by zyfncg** [comment]
这个问题确实比较奇怪，是偶发的现象还是可以稳定复现的？

**Comment by zyfncg** [comment]
能否提供下使用的Paddle版本，GPU配置，以及训练用的模型和数据集这些信息？

**Comment by Lllllolita** [comment]
这是论文复现赛的一个模型，不好意思忘记加tag了。本地服务器是CUDA-11.3，3090GPU，Paddle版本为2.3.2-post112，Paddle复现的代码逻辑（训练、验证、变量命名等）与Torch相同，Torch占用显存大概24G，并未出现显存爆炸现象。本地训练Paddle模型的时候，固定了随机数种子，共训练了3次，每次都在220epoch突然显存爆炸，前期显存稳定在24G。在aistudio上训练了1次，也出现了显存爆炸的情况，但不是在220epoch，过一段时间会恢复稳定，显存占用同为24G左右。已检查部分：loss累加使用了.item()，验证时用了model.eval()和with paddle.no_grad()，与显存相关的环境变量均采用缺省值。

**Comment by Lllllolita** [comment]
我把optimizer.clear_grad()写在了每个epoch循环的最开始，之后再进行loss计算和反向等，因为torch项目就是这样写的。也许会和这个有关系吗？现在观察nvidia-smi发现，稳定状态的显存也会浮动几百MB左右。

**Comment by zyfncg** [comment]
正常情况下如果有显存问题一般是显存稳定增加或者周期性变化，这种后期显存突然增加的情况比较少见，感觉像是在这个场景下刚好成为了一个极端case。
不知道有没有条件用最新develop代码编的Paddle包测试下？我们develop中的代码使用了新的动态图架构，也许可以解决这个显存问题。
<img width="1289" alt="image" src="https://user-images.githubusercontent.com/13048366/190057050-d5c5cf36-5c56-4a80-8d63-73f6490d7adb.png">
