### ISSUE TITLE
文档中部分示例代码存在错误

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#45977]
### 文档链接&描述 Document Links & Description

在进行 flake8 引入的过程中（#45937），在 CI 流水线中发现有大量的示例代码是无法跑通的，大多数示例代码有明显的错误，这些错误需要逐一进行修正

CI 流水线 log：[build.log](https://github.com/PaddlePaddle/Paddle/files/9554294/build.log)（来源于 https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/6580153/job/18299804 ）

### 请提出你的建议 Please give your suggestion

根据 log 中报错信息进行修复，有很多有明显的错误，比如 `paddle.distributed.InMemoryDataset.get_shuffle_data_size_example.py` 中使用了 print 语句（Python2 遗留代码）

https://github.com/PaddlePaddle/Paddle/blob/9f5b0831d215dd02e5151b69cc56f466347670b2/python/paddle/distributed/fleet/dataset/dataset.py#L1166

整体存在错误的 API 有将近 100 个，但大多数是 fluid 下的 API，非 fluid 大概在 10 个左右，fluid 下一些确定要废弃的 API 可以不改或者优先级低一些。其余的 API 需要根据情况进行修改。

**Comment by Ligoml** [comment]
fluid API会逐渐退场，所以这部分API文档的示例代码可以先不处理，非fluid的API示例代码需要修正

**Comment by luotao1** [comment]
close due to related PR is merged:
- https://github.com/PaddlePaddle/Paddle/pull/45937
