### ISSUE TITLE
paddleOcr 

### ISSUE THREAD

**Issue by dennis88888** [PaddlePaddle/Paddle#45987]
### 请提出你的问题 Please ask your question

请问,我需要在ocr代码里要访问paddleocr.bj.bcebos.com
 但这个网址在公网上没法访问，请问这个网址是做什么用的？是否是必须的？

**Comment by zyfncg** [comment]
paddleocr.bj.bcebos.com提供了一些预训练的模型，有些场景的代码会用到

**Comment by dennis88888** [comment]
那您的意思是 这个网址的作用是做预训练的模型的？
我在公网上访问这个网址是被拒绝的，请问是什么原因？

**Comment by dennis88888** [comment]
我在应用程序中，引入这个paddleocr.py 这个文件里有需要访问这个网址，

**Comment by dennis88888** [comment]
我在应用程序中，引入这个paddleocr.py 这个文件里有需要访问这个网址，

**Comment by an1018** [comment]
使用paddleocr.py会默认下载预训练，先用浏览器或者wget下载模型试试吧：https://paddleocr.bj.bcebos.com/PP-OCRv3/english/en_PP-OCRv3_det_infer.tar
