### ISSUE TITLE
使用RTX30系列多卡训练问题

### ISSUE THREAD

**Issue by DLPerf** [PaddlePaddle/Paddle#46019]
### 请提出你的问题 Please ask your question

多卡训练要求有NCCL，官方文档中写明当前ubuntu系统下，paddle只支持CUDA10.1下的NCCL版本。
但是我的机器是四张RTX 3090显卡，只能使用CUDA11（CUDA10调用显卡会一直卡住），是不是这样就不能进行单机多卡训练了？

**Comment by limin2021** [comment]
请问一下，『官方文档中写明当前ubuntu系统下，paddle只支持CUDA10.1下的NCCL版本。』可否贴一下链接？

**Comment by limin2021** [comment]
参考一下这里：[Linux下的安装文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/linux-conda.html#gpupaddlepaddle)

**Comment by DLPerf** [comment]
[5. PaddlePaddle对NCCL的支持](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html)，我还没有训练，而且是直接使用cuda11.2版本的docker环境，我弄个模型跑一下吧。
