### ISSUE TITLE
关于third party的一点小建议

### ISSUE THREAD

**Issue by opentld** [PaddlePaddle/Paddle#46017]
### 问题描述 Issue Description

首先感谢敬爱的北邮方教授，还有可爱的网络运营商，让我等屁民还有机会上网；
其次感谢paddle团队的great works，paddle确实很好用（真心话）；
最后，关于编译paddle，我有一个不成熟的小建议：
是否可以将third_party专门提供一个下载，就像opencv contrib一样？
另外，在我手动下载之后，咱的cmake能不能不给我删掉，然后执着的非要自己重新下载（或者非要逼我改cmake）？
大量的时间，消耗在这样的Time Out上，真的心情非常不美丽。
授人玫瑰，手有余香，举手之劳，方便广大学子，善莫大焉。：）

### 版本&环境信息 Version & Environment Information

paddle 2.3.2
CUDA 11.6
GPU Nvidia RTX3060
Windows 10
No Python

**Comment by limin2021** [comment]
你好，非常感谢你的建议，需求已收到，我们会内部评估该功能的可行性和开发优先级。
