### ISSUE TITLE
设定随机种子仍无法复现相同的结果

### ISSUE THREAD

**Issue by thgpddl** [PaddlePaddle/Paddle#46012]
### bug描述 Describe the Bug

我尝试设定随机种子，然后运行程序两次，然而两次的结果并不一致。

我将随机种子的代码写在utils.py中，代码如下：
```python
def random_seed(seed):
    random.seed(seed)   # random包
    np.random.seed(seed)    # numpy包
    paddle.seed(seed)   # paddle包
    os.environ['FLAGS_cudnn_deterministic'] = "True"
```

然后我在train.py中导入上述函数，然后在train.py中开启训练，我不改变任何环境和代码，当第一次训练完成后，开启第二次训练，两者结果不一致，下图中红色和蓝色分别表示第一次训练和第二次训练：
![image](https://user-images.githubusercontent.com/48787805/189941027-af10acf7-4b66-46de-a9c1-325b4a9629f4.png)
![image](https://user-images.githubusercontent.com/48787805/189941093-515c8650-0c3d-4359-a5ee-4c6f11fa2f0e.png)

而且在其他模型和配置下也出现无法复现的情况。

请问如何保证可复现性，如果不能我将无法进行网络改进前后的对比

**Comment by limin2021** [comment]
多次运行，保证模型复现需注意：
1.使用同样的随机种子或者手动固定要读取的文件为同一个；
2.关掉读取数据集时的shuffle行为（因为若训练使用的是不同数据或者数据读取顺序不一样，最终结果可能存在一些差异）；
3.需保证模型中所有算子的计算是可复现性的，对于使用cudnn实现的算子，可以通过FLAGS_cudnn_deterministic为true保证他们的确定性；
然而对于一些使用原子指令实现的算子，在rerun时结果可能存在差异，比如embedding的反向，index_select和index_add算子的前向等。
当前index_select算子可通过控制FLAGS_cudnn_deterministic为true控制确定性，#46040 对index_add和embedding增加了FLAGS_cudnn_deterministic控制；
目前paddle框架中可能有一些算子可能有不确定性行为。建议排查下模型中的全部算子，看是否有原子操作等影响确定性的行为。
4.如果上述都没有找到原因，建议手动设置输入为同一个文件，关闭shuffle后，逐层打印输出，详细找出问题的位置后再分析。

感谢你的提问，也欢迎将解决该问题中遇到的问题和经验反馈和分享给我们！

**Comment by thgpddl** [comment]
> 多次运行，保证模型复现需注意： 1.使用同样的随机种子或者手动固定要读取的文件为同一个； 2.关掉读取数据集时的shuffle行为（因为若训练使用的是不同数据或者数据读取顺序不一样，最终结果可能存在一些差异）； 3.需保证模型中所有算子的计算是可复现性的，对于使用cudnn实现的算子，可以通过FLAGS_cudnn_deterministic为true保证他们的确定性； 然而对于一些使用原子指令实现的算子，在rerun时结果可能存在差异，比如embedding的反向，index_select和index_add算子的前向等。 当前index_select算子可通过控制FLAGS_cudnn_deterministic为true控制确定性，#46040 对index_add和embedding增加了FLAGS_cudnn_deterministic控制； 目前paddle框架中可能有一些算子可能有不确定性行为。建议排查下模型中的全部算子，看是否有原子操作等影响确定性的行为。 4.如果上述都没有找到原因，建议手动设置输入为同一个文件，关闭shuffle后，逐层打印输出，详细找出问题的位置后再分析。
> 
> 感谢你的提问，也欢迎将解决该问题中遇到的问题和经验反馈和分享给我们！

感谢您的回答，但是在训练时关闭数据集shuffle会影响最终效果，那么我就无法使用paddle进行研究。其次我认为shuffle本身也是随机控制， 那么当我设定随机种子后，这种随机性也应当被固定下来，这应该如何解释？谢谢

**Comment by limin2021** [comment]
1.你的理解是对的哈。dataloader中，随机种子固定，shuffle后的结果应该是一样的。我第一个回复其实是想排除掉这种随机性，来查真正的问题出在哪里。你可以看看随机种子固定后，dataloader出来的数据，不同rerun是否相同，这样也能排除这个因素。

2.如果你多次rerun正确性出现很大的偏差，那可能是你写的模型代码或者paddle框架中有潜在的bug，或者是某个算子存在不确定性行为，这时候就可以固定输入来调试一下，看问题具体出在哪里；也有可能是不同rerun使用了来自不同文件的数据集（这种情况，训练结果很可能本身就是不同的）。

**Comment by limin2021** [comment]
1.shuffle应该是会影响rerun的结果的，这个应该跟框架无关，属于算法本身的问题。如果你多次rerun正确性出现很大的偏差，那可能是你写的模型代码或者paddle框架中有潜在的bug，这时候就可以固定输入来调试一下，看问题具体出在哪里；也有可能是不同rerun使用了来自不同文件的数据集（这种情况，训练结果很可能本身就是不同的）。2. 你的理解是对的哈。dataloader中，随机种子固定，shuffle后的结果应该是一样的。我第一个回复其实是想排除掉这种随机性，来查真正的问题出在哪里。你可以看看随机种子固定后，dataloader出来的数据，不同rerun是否相同，这样也能排除这个因素。

**Comment by thgpddl** [comment]
感谢您的回复，谢谢(ง •_•)ง

**Comment by GuoxiaWang** [comment]
@thgpddl 请问你是在训练什么模型？上面的 PR 通过添加 FLAG 控制 embedding 反向确定性后，是否还有随机性？
