### ISSUE TITLE
paddle支持对比学习InfoNCE Loss吗

### ISSUE THREAD

**Issue by spantarXP** [PaddlePaddle/Paddle#46043]
### 请提出你的问题 Please ask your question

paddle支持对比学习InfoNCE Loss吗

**Comment by limin2021** [comment]
你好，paddle目前不支持Info NCE Loss。感谢你提的需求，内部开发人员会评估调研该API的需求程度，根据优先级进行决定与排期。

**Comment by Ligoml** [comment]
建议自己组合Python算子实现~
如果你有兴趣，可以给paddle贡献这个API
