### ISSUE TITLE
paddleDetection内置算法训练报错

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/Paddle#46057]
### 请提出你的问题 Please ask your question

使用内置的ppyoloe_crn_l_300e_coco算法训练时报错，如何解决？
![1401663169240_ pic](https://user-images.githubusercontent.com/55121158/190199679-44d4daa0-0457-4ccf-9b04-46d29a2d6823.jpg)

**Comment by XYZ-916** [comment]
请问您的数据集类别数和配置是否一致？请确认。另外标签label index是从0开始的，请注意。

**Comment by ionescofung** [comment]
我就调用模型去训练，只有一个label的 就是篮球。如下图，哪里出现错误吗？
![WechatIMG142](https://user-images.githubusercontent.com/55121158/190451248-170092db-664b-479a-8cda-d697036bce16.png)

**Comment by ionescofung** [comment]
我使用原配置文件也出现错误
![1451663319629_ pic](https://user-images.githubusercontent.com/55121158/190604485-410e7eda-c5cc-4533-b3c3-1a8a8e62985e.jpg)

**Comment by nemonameless** [comment]
https://github.com/PaddlePaddle/PaddleDetection/search?q=out+of+bound&type=issues 
win上paddle请暂时安装paddle2.2.2版本去使用
