### ISSUE TITLE
paddle.autograd.PyLayer多卡训练

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#46062]
### 请提出你的问题 Please ask your question

我现在要实现一个功能，同一个loss对不同层的参数回传梯度不一样。用的是这个 paddle.autograd.PyLayer。问题是单卡可以调试通过，但多机多卡不行，请问有啥办法解决这个问题吗？
多机多卡报错显示为：Thu Sep 15 00:34:04 2022[1,3]<stdout>:  File "/root/paddlejob/workspace/env_run/envs/py38_pd230_cuda111_a100/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
Thu Sep 15 00:34:04 2022[1,3]<stdout>:    outputs = self.forward(*inputs, **kwargs)
Thu Sep 15 00:34:04 2022[1,3]<stdout>:  File "/root/paddlejob/workspace/env_run/envs/py38_pd230_cuda111_a100/lib/python3.8/site-packages/paddle/fluid/dygraph/parallel.py", line 755, in forward
Thu Sep 15 00:34:04 2022[1,3]<stdout>:    self._reducer.prepare_for_backward(
Thu Sep 15 00:34:04 2022[1,3]<stdout>:RuntimeError: (PreconditionNotMet) Note: Currently PyLayer is not supported in DataParallel. For using PyLayer in a DataParallel model, you can skip gradient synchronization among multiple cards by 'no_sync', and manually implement 'all_reduce' before model optimization

**Comment by zoooo0820** [comment]
你好，根据报错信息，请参考下：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/DataParallel_cn.html#dataparallel 看是否有帮助呢

**Comment by bixiaopeng0** [comment]
“推荐先使用no_sync接口暂停多卡通信，然后在优化器前手动实现梯度同步”，这种手动梯度同步方式会有什么影响，比如对网络训练的速度和效果上？

**Comment by ForFishes** [comment]
您好，这个改动对精度/效果没有影响，性能上会有一点影响，大概2%不到的性能损失。
