### ISSUE TITLE
飞桨框架v2.4的发布计划(Paddle framework v2.4 release plan)

### ISSUE THREAD

**Issue by jzhang533** [PaddlePaddle/Paddle#46069]
### 问题描述 Please describe your issue

我们已经于9月9日创建了[v2.4.0 release 分支](https://github.com/PaddlePaddle/Paddle/tree/release/2.4)，并基于该分支启动了集成测试、稳定性测试、性能测试。我们会逐步的从develop分支中通过cherry-pick PRs的方式让该分支稳定。该过程可能会持续1~2个月的时间，这期间我们会发布一到多个的v2.4.0 release candidate版本。待该分支稳定后，我们会发布v2.4.0正式版本。

We have created a release branch for [the v2.4.0 release](https://github.com/PaddlePaddle/Paddle/tree/release/2.4) on 9/9, and have started performing integration test, stability test and performance test based on this branch. To stabilize the release branch , we will cherry-pick PRs from develop branch progressively, this process may take 1~2 months, and we will create one or more v2.4.0 release candidates during this process. We will release v2.4.0 version after this branch is stabilized.

update at 2022-11-17: We have created [v2.4.0 tag](https://github.com/PaddlePaddle/Paddle/releases/tag/v2.4.0), release note is on the way.

update at 2022-11-28: release note published: https://github.com/PaddlePaddle/Paddle/releases/tag/v2.4.0

**Comment by yuwoyizhan** [comment]
@jzhang533  @Ligoml 飞桨2.4,gpu版本,python3.10.8,cuda10.2,windows10 64位,使用pip uninstall paddleclas报错,跟fassi_cpu有关

see discussion in #48414

**Comment by jzhang533** [comment]
[v2.4.0](https://github.com/PaddlePaddle/Paddle/releases/tag/v2.4.0) is released, I will close this issue.
