### ISSUE TITLE
如何动态调整预训练参数

### ISSUE THREAD

**Issue by 15554710621** [PaddlePaddle/Paddle#46063]
如何根据epoch调整动态调整预训练参数

**Comment by 15554710621** [comment]
是使用callback吗，不太懂paddle 的dataloader机制，网上没找到教程

**Comment by zoooo0820** [comment]
你好，辛苦能再具体描述下具体场景吗，看描述是指除了启动训练时载入预训练模型的参数，后续会有继续载入其他参数的需求吗。如果有对应的模型代码可以一并提供下帮助理解

**Comment by 15554710621** [comment]
就是前面训练的时候
使用一个transforms = Compose([transforms.Resize(int(224*1.143)),
                                transforms.CenterCrop(224),
                                transforms.ToTensor(),
                                transforms.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])])
训练到一定epoch后改为使用一个new_transforms继续训练

**Comment by 15554710621** [comment]
其他没有什么特别的，DatasetFolder实例化Dataset，然后用DataLoader加载

**Comment by zoooo0820** [comment]
看下[检测模型](https://github.com/PaddlePaddle/PaddleDetection/blob/50d9662c20dae25b1faebd1ccfaccddd26c563d5/ppdet/data/source/dataset.py#L84-L96)里的做法是否符合描述的场景需求呢，通过`_epoch`参数控制返回不同的`transform`

**Comment by 15554710621** [comment]
但是怎么获得当下的epoch呢

**Comment by zoooo0820** [comment]
关于如何获取epoch，在上面的类中定义了`set_epoch(epoch_id)` 方法用于传入epoch。同样以检测模型为例，在train函数的循环中传入，参考[这里](https://github.com/PaddlePaddle/PaddleDetection/blob/ede22043927a944bb4cbea0e9455dd9c91b295f0/ppdet/engine/trainer.py#L444-L448) .
