### ISSUE TITLE
linux 下用c++推理PP-TSM出错

### ISSUE THREAD

**Issue by 923629877** [PaddlePaddle/Paddle#46076]
### bug描述 Describe the Bug

在Linux下按照官方教程（https://github.com/PaddlePaddle/PaddleVideo/blob/develop/deploy/cpp_infer/readme.md）用c++部署PP-TSM抛出如下错误：
(paddle) rex@rex:~/PaddleVideo-develop/deploy/cpp_infer$ sudo ./build/ppvideo rec --rec_model_dir=/home/rex/PaddleVideo-develop/inference/ppTSM --inference_model_name=TSM --video_dir=/home/rex/PaddleVideo-develop/deploy/cpp_infer/example_video_dir --num_seg=8 --seg_len=1
[sudo] rex 的密码： 
mode: rec
[/home/rex/PaddleVideo-develop/inference/ppTSM]
[/home/rex/PaddleVideo-develop/deploy/cpp_infer/example_video_dir]
total videos num: 1
terminate called after throwing an instance of 'char const*'
已放弃

### 其他补充信息 Additional Supplementary Information

配置文件如下（build.sh）：
OPENCV_DIR=/home/rex/PaddleVideo-develop/deploy/cpp_infer/opencv-3.4.7/opencv3
LIB_DIR=/home/rex/PaddleVideo-develop/deploy/cpp_infer/paddle_inference
CUDA_LIB_DIR=/usr/local/cuda/lib64
CUDNN_LIB_DIR=/usr/lib/x86_64-linux-gnu/
TENSORRT_DIR=your_tensorRT_dir

BUILD_DIR=build
rm -rf ${BUILD_DIR}
mkdir ${BUILD_DIR}
cd ${BUILD_DIR}
cmake .. \
    -DPADDLE_LIB=${LIB_DIR} \
    -DWITH_MKL=ON \
    -DWITH_GPU=OFF \
    -DWITH_STATIC_LIB=OFF \
    -DWITH_TENSORRT=OFF \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DCUDNN_LIB=${CUDNN_LIB_DIR} \
    -DCUDA_LIB=${CUDA_LIB_DIR} \
    -DTENSORRT_DIR=${TENSORRT_DIR} \

make -j4

**Comment by huangjun12** [comment]
pls refer to https://github.com/PaddlePaddle/PaddleVideo/issues/530

**Comment by 923629877** [comment]
> pls refer to [PaddlePaddle/PaddleVideo#530](https://github.com/PaddlePaddle/PaddleVideo/issues/530)

谢谢，您给的参考链接也是同样的问题，但那边似乎也并没有给出解决方案

**Comment by ccslience** [comment]
遇到了同样的问题

**Comment by ccslience** [comment]
邮件已收到，谢谢~                    张静
