### ISSUE TITLE
nn.functional.interpolate convert Tensor on CPU to GPU

### ISSUE THREAD

**Issue by Dawn-bin** [PaddlePaddle/Paddle#46096]
### 请提出你的问题 Please ask your question

Why **nn.functional.interpolate** always convert Tensor on CPU to GPU???

my code here:
```python
logit = paddle.to_tensor(logit, place=paddle.CPUPlace())
print(logit.place)
print(logit.shape)
logit = F.interpolate(logit, (h_input, w_input), mode='bilinear')
print(logit.place)
print(logit.shape)
```

```shell
Place(cpu)
[1, 2, 6205, 5968]
Place(gpu:0)
[1, 2, 12410, 11936]
```

Can we  interpolate only use cpu? since gpu is not adequate.

**Comment by zoooo0820** [comment]
For now, Paddle will automatically use the default device (here is GPU). 
To temporarily solve this problem, you can use:
```python
paddle.set_device('cpu')
# {your code here, executed on cpu}
# ...
paddle.set_device('gpu')
```
The default device scheduling policy is for user-friendly purposes, we will further consider the design.

**Comment by Dawn-bin** [comment]
Thank u for reply! It works well.
