### ISSUE TITLE
手动下载数据集

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/Paddle#46103]
### 请提出你的问题 Please ask your question

请问手动下载的数据集如何给到paddleDetection使用??
![image](https://user-images.githubusercontent.com/55121158/190534745-6b96ec3e-9a87-4d51-8974-4ce20891f0a2.png)

**Comment by wjj19950828** [comment]
@ionescofung ppyoloe训练可以参考这个文档:[PPYOLOE](https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/configs/ppyoloe),若还有问题，建议去[PaddleDetection issues](https://github.com/PaddlePaddle/PaddleDetection/issues)提问～
