### ISSUE TITLE
执行 tools/train.py训练提示错误

### ISSUE THREAD

**Issue by ionescofung** [PaddlePaddle/Paddle#46134]
### 请提出你的问题 Please ask your question

已经下载了coco的数据集
执行tools/train.py训练提示错误。请问什么原因？
我的电脑gpu是3070显卡 cuda 11.6
![1451663319629_ pic](https://user-images.githubusercontent.com/55121158/190602978-fcd127e9-5527-4f33-b43f-ce1e3c98dc0c.jpg)

**Comment by wjj19950828** [comment]
@ionescofung 看起来像是有label越界了，建议去[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection) Issue下提问
