### ISSUE TITLE
arm编译报错：error: namespace "paddle::platform::dynload" has no member "cusparseDestroy"

### ISSUE THREAD

**Issue by SunGoodIn** [PaddlePaddle/Paddle#46149]
版本、环境信息：
   1）PaddlePaddle版本：2.2
   4）系统环境：arm、ubuntu 20.04、Python 3.8
![image](https://user-images.githubusercontent.com/37318301/190640337-da420cb8-94ac-4648-9a84-f4a6aa5c9bfd.png)

**Comment by wjj19950828** [comment]
@SunGoodIn arm编译可以参考这个文档：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/729dbea675c1923282a31ea581093d588211c883/docs-official/guides/install/compile/compile_ARM.md

**Comment by SunGoodIn** [comment]
gcc版本过高导致，原版本gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0；
将为gcc (Ubuntu/Linaro 8.4.0-3ubuntu2) 8.4.0后编译通过

**Comment by Ligoml** [comment]
你好，我们会在2.4版本支持gcc9，欢迎关注
