### ISSUE TITLE
YOLOv5 Paddle export error == 1 OPs are not supported yet `aten::clone` ==

### ISSUE THREAD

**Issue by glenn-jocher** [PaddlePaddle/Paddle#46146]
### bug描述 Describe the Bug

YOLOv5 export fails due to unsupported torch Tensor `.clone()` operation. Error first reported in https://github.com/ultralytics/yolov5/issues/9439

```bash
PaddlePaddle: starting export with X2Paddle 1.3.8...
[WARNING] PyTorch==1.6.0 is recommended
Now translating model from PyTorch to Paddle.

========= 1 OPs are not supported yet ===========
========== aten::clone ============
PaddlePaddle: export failure ❌ 3.6s: Model is not supported yet.
```

<img width="1154" alt="Screenshot 2022-09-16 at 13 36 39" src="https://user-images.githubusercontent.com/26833433/190630368-5a3723ed-74cf-4483-ac12-15a632ae25e3.png">

### Code to reproduce
```python
!git clone https://github.com/ultralytics/yolov5  # clone
%cd yolov5
%pip install -qr requirements.txt x2paddle paddlepaddle # install

!python export.py --weights yolov5s.pt --include paddle  # export
```

### 其他补充信息 Additional Supplementary Information

YOLOv5 uses a torch tensor .clone() operation here that is causing the bug I think:
https://github.com/ultralytics/yolov5/blob/a1e5f9a97de2a3ace012315208c686744ced2782/models/yolo.py#L67-L68

**Comment by wjj19950828** [comment]
@glenn-jocher hi，glenn-jocher，I reopened an issue on [X2Paddle](https://github.com/PaddlePaddle/X2Paddle/issues/896), I will follow up and schedule support

**Comment by glenn-jocher** [comment]
@wjj19950828 ah thank you, wasn't sure which repo to post to.
