### ISSUE TITLE
如何使用VisualDL可视化模型的梯度？

### ISSUE THREAD

**Issue by marcuswang6** [PaddlePaddle/Paddle#46167]
### 请提出你的问题 Please ask your question

百度得到pytorch中可视化梯度：[x.grad for x in self.optimizer.param_groups[0]['params']]

官方文档中VisualDL直方图：Histogram组件以直方图形式展示Tensor（weight、bias、gradient等）数据在训练过程中的变化趋势。深入了解模型各层效果，帮助开发者精准调整模型结构。

官方例子：
from visualdl import LogWriter
import numpy as np

if __name__ == '__main__':
    values = np.arange(0, 1000)
    with LogWriter(logdir="./log/histogram_test/train") as writer:
        for index in range(1, 101):
            interval_start = 1 + 2 * index / 100.0
            interval_end = 6 - 2 * index / 100.0
            data = np.random.uniform(interval_start, interval_end, size=(10000))
            writer.add_histogram(tag='default tag',
                                 values=data,
                                 step=index,
                                 buckets=10)

搜索了以上结果后还是没有解答如何可视化梯度的问题，小白不了解Paddle中梯度应该怎么调用以及这里add_histogram如何用来可视化梯度，请问有大神知道具体实现的吗？

**Comment by ZhangHandi** [comment]
在Paddle中，可以通过x.grad.numpy()的方式获得tensor x的numpy梯度值。可视化方法请参考：[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/advanced/visualdl_usage_cn.html#histogram](url)
。运行程序后，执行visualdl --logdir ./log --port 8080 命令，在浏览器输入[http://127.0.0.1:8080](url)，即可查看训练参数直方图。

**Comment by marcuswang6** [comment]
> 

好的，谢谢！
