### ISSUE TITLE
pytorch中的API转为paddle

### ISSUE THREAD

**Issue by shanqiu24** [PaddlePaddle/Paddle#46161]
### 需求描述 Feature Description

torch.optim.lr_scheduler, torch.optim.lr_scheduler.LambdaLR, torch.optim.lr_scheduler._LRScheduler这几个API对应的paddle中的API是啥呀

**Comment by linjieccc** [comment]
您好，
1. torch.optim.lr_scheduler._LRScheduler 对应 paddle.optimizer.lr.LRScheduler
2. torch.optim.lr_scheduler.LambdaLR 对应 paddle.optimizer.lr.LambdaDecay

**Comment by Ligoml** [comment]
映射关系可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/pytorch_api_mapping_cn.html
