### ISSUE TITLE
项目从pytroch转为paddle框架时遇到的报错

### ISSUE THREAD

**Issue by shanqiu24** [PaddlePaddle/Paddle#46171]
### 请提出你的问题 Please ask your question

ValueError: (InvalidArgument) Leaf Tensor (conv2d_transpose_0.w_0) that doesn't stop gradient can't use inplace strategy.
  [Hint: Expected self->IsLeaf() && !self->OverridedStopGradient() == false, but received self->IsLeaf() && !self->OverridedStopGradient():1 != false:0.] (at ..\paddle\fluid\pybind\imperative.cc:994)
本人在历史issue中看到过类似的问题，还还是无法得到满意的解决，所以想请相关技术支持的帮助~

**Comment by ZhangHandi** [comment]
可以参考issue [42190](https://github.com/PaddlePaddle/Paddle/issues/42190)将参数设置为不需要梯度: p.stop_gradient = True， 并在 with no_grad 上下文里对参数值做修改。如果该方法不能解决此问题，请提供一段可复现该问题的最小代码，我们来排查一下问题。

**Comment by shanqiu24** [comment]
> 可以参考issue [42190](https://github.com/PaddlePaddle/Paddle/issues/42190)将参数设置为不需要梯度: p.stop_gradient = True， 并在 with no_grad 上下文里对参数值做修改。如果该方法不能解决此问题，请提供一段可复现该问题的最小代码，我们来排查一下问题。

之前并未接触过贵公司的paddle框架，依然无法定位问题发生位置，无法提供准确的代码片段，望帮助~

**Comment by ZhangHandi** [comment]
> 
pytorch转paddle是怎么转的呢，用x2paddle工具么，还是参考论文复现指南手动复现的呢？

**Comment by shanqiu24** [comment]
> > 
> 
> pytorch转paddle是怎么转的呢，用x2paddle工具么，还是参考论文复现指南手动复现的呢？

是使用的X2Paddle转的

**Comment by ZhangHandi** [comment]
> 是使用的X2Paddle转的

训练代码转换目前暂时不成熟哈，只支持转换推理模型。 训练代码复现建议参照paddle文档进行复现，可以参考：[论文复现指南](https://github.com/PaddlePaddle/models/blob/develop/docs/ThesisReproduction_CV.md#3.8)
