### ISSUE TITLE
根据FE/UI/UX设计师要求，整理中英文文档

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#462]
整体要求：
1. 中英文目录结构统一及规范
2. 中英文文档内容质量的提高

目录方面的工作：

- [ ] 中英文一级二级目录的确定（优先级最高）。@wangkuiyi @reyoung 
    - [ ] 目录确定后，是否需要将doc_cn和doc下面的文档和子目录重新归类？重新归类的话，会导致已有很多链接的失效。
     - [ ] 目前存在多个目录节点指向同一个页面，最好只保留一份。
     - [ ] 中英文顶部导航的问题。（英文已完成 #478）
- [ ] 中英文目录和文档对应问题。
     - [ ] doc_cn下面的目录结构修改成和doc完全一样的。中文缺少的目录，采用软连接到英文目录？
- [x]  页面锚点作为目录节点出现了，但是到了页面中这些锚点又没有了。（优先级高）
     - [x] Model Config Interface（已完成 #463 ）
     - [x] Source Code Document （已完成 #519 ）
- [ ] 删去所有的内部文档和链接。（优先级高）
- [ ] 生成Source Code注释过程中，存在大量重复的目标链接提示以及warning。（优先级低）
- [ ] 其他小问题：锚点链接与页面链接一样，链接指向错误，标题名称错误等情况。（碰到即解决）

内容方面的工作：
- 中英文md文档转成rst文档：中文进行中
- 中英文质量提升：中文进行中

请大家补充

**Comment by llxxxll** [comment]
补充
文档语言切换（中/英文）方案：现在实现方式是重写，未来是否可以统一文件名，通过路径名（doc/doc_cn）判断切换。

**Comment by Shi-Liang** [comment]
部分目录中的标题与具体文档的标题存在不一致的情况，期望保持一致

**Comment by lizhaoch** [comment]
先发布出来，边写边发布吧
