### ISSUE TITLE
paddle想限制cpu核心数，新API在老版本中报模块不存在

### ISSUE THREAD

**Issue by weiyang-1** [PaddlePaddle/Paddle#46220]
### bug描述 Describe the Bug

[root@ef474a0f7a05 APP_AI]# pip list |grep paddle
paddlepaddle                  1.2.0    
[root@ef474a0f7a05 APP_AI]# python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle.v2 as paddle
>>> paddle.inference.Config.cpu_math_library_num_threads()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Config'
>>> 

### 其他补充信息 Additional Supplementary Information

目前使用的paddle版本为1.2.0cpu版本，默认运行时会跑满cpu的全部核心，因此想通过paddle.inference.Config.set_cpu_math_library_num_threads()来设置，结果此API老版本不生效

**Comment by an1018** [comment]
推荐安装PaddlePaddle2.3
