### ISSUE TITLE
导包问题

### ISSUE THREAD

**Issue by dasenCoding** [PaddlePaddle/Paddle#46228]
### 问题描述 Please describe your issue

测试api时，报错 “ModuleNotFoundError: No module named 'python.paddle.fluid.proto'” 。

但是运行其他测试类可以正常运行 (比如：Paddle\python\paddle\fluid\tests\unittests\distribution\test_distribution_gumbel.py)

在 Paddle\python\paddle\fluid\framework.py 中，使用到了前面报错的包：“ from .proto import framework_pb2 ”，同时这条导包语句在  framework.py  中同样也报错。

**Comment by Ligoml** [comment]
@cxxly 辛苦帮忙看下

**Comment by cxxly** [comment]
麻烦贴个具体PR或者可复现代码

**Comment by dasenCoding** [comment]
测试类：[https://github.com/PureNatural/Paddle/blob/gumbel_api/python/paddle/fluid/tests/unittests/distribution/test_distribution_gumbel.py](url)

api:
[https://github.com/PureNatural/Paddle/blob/gumbel_api/python/paddle/distribution/gumbel.py](url)

__init__:
[https://github.com/PureNatural/Paddle/blob/gumbel_api/python/paddle/distribution/__init__.py](url)

这样可以吗？其他地方没有变动。

**Comment by cxxly** [comment]
你是私有仓库吗，我打不开你发的链接

**Comment by dasenCoding** [comment]
**测试类：**

`import unittest

import numpy as np
import paddle
import scipy.stats
import config
import parameterize
from python.paddle.distribution import Gumbel

SEED=2022

@parameterize.place(config.DEVICES)
@parameterize.parameterize_cls(
    (parameterize.TEST_CASE_NAME, 'loc', 'scale'), [
    ('one-dim', parameterize.xrand((2, )),\
             parameterize.xrand((2, ))),
    ('multi-dim', parameterize.xrand((5, 5)),\
             parameterize.xrand((5, 5))),
    ])
class TestGumbel(unittest.TestCase):

    def setUp(self):
        self._dist = Gumbel(loc=paddle.to_tensor(self.loc),
                                                 scale=paddle.to_tensor(\
                                                     self.scale))

    def test_mean(self):
        mean = self._dist.mean
        self.assertEqual(mean.numpy().dtype, self.scale.dtype)
        np.testing.assert_allclose(mean,
                                   self.np_mean(),
                                   rtol=config.RTOL.get(str(self.scale.dtype)),
                                   atol=config.ATOL.get(str(self.scale.dtype)))

    def test_variance(self):
        var = self._dist.variance
        self.assertEqual(var.numpy().dtype, self.scale.dtype)
        np.testing.assert_allclose(var,
                                   self.np_variance(),
                                   rtol=config.RTOL.get(str(self.scale.dtype)),
                                   atol=config.ATOL.get(str(self.scale.dtype)))

    def test_stddev(self):
        stddev = self._dist.stddev
        self.assertEqual(stddev.numpy().dtype, self.scale.dtype)
        np.testing.assert_allclose(stddev,
                                   self.np_stddev(),
                                   rtol=config.RTOL.get(str(self.scale.dtype)),
                                   atol=config.ATOL.get(str(self.scale.dtype)))

    def test_entropy(self):
        entropy = self._dist.entropy()
        self.assertEqual(entropy.numpy().dtype, self.scale.dtype)

    def test_sample(self):

        sample_shape = (30000, )
        samples = self._dist.sample(sample_shape, seed=SEED)
        sample_values = samples.numpy()

        self.assertEqual(samples.numpy().dtype, self.scale.dtype)
        self.assertEqual(tuple(samples.shape),
                         tuple(self._dist._extend_shape(sample_shape)))

        self.assertEqual(samples.shape, list(sample_shape + self.loc.shape))
        self.assertEqual(sample_values.shape, sample_shape + self.loc.shape)

        np.testing.assert_allclose(sample_values.mean(axis=0),
                                   scipy.stats.gumbel.mean(self.loc,
                                                            scale=self.scale),
                                   rtol=0.1,
                                   atol=0.)
        np.testing.assert_allclose(sample_values.var(axis=0),
                                   scipy.stats.gumbel.var(self.loc,
                                                           scale=self.scale),
                                   rtol=0.1,
                                   atol=0.)

        tmp_loc = 4.0
        tmp_scale = 3.0
        tmp_dist = Gumbel(loc=tmp_loc, scale=tmp_scale)
        samples = tmp_dist.sample(sample_shape, seed=SEED)
        sample_values = samples.numpy()
        self.assertTrue(self.kstest(tmp_loc, tmp_scale, sample_values))

    def np_mean(self):
        return self.loc

    def np_stddev(self):
        return (2 ** 0.5) * self.scale

    def np_variance(self):
        stddev = (2 ** 0.5) * self.scale
        return np.power(stddev, 2)

    def np_entropy(self):
        return scipy.stats.gumbel.entropy(loc=self.loc, scale=self.scale)

    def kstest(self, loc, scale, samples):
        # Uses the Kolmogorov-Smirnov test for goodness of fit.
        ks, p_value = scipy.stats.kstest(
            samples,
            scipy.stats.gumbel(loc, scale=scale).cdf)
        return p_value < 0.05

if __name__ == '__main__':
    unittest.main()
`

---------------------------------------------------------------------
**api：**
`
import math
import warnings
import paddle
import numbers
import scipy

import numpy as np
from paddle.distribution import distribution
from paddle.distribution.uniform import Uniform
from paddle.distribution.transformed_distribution import TransformedDistribution
from paddle.distribution.transform import AffineTransform, ExpTransform
from paddle.fluid import framework as framework


class Gumbel(TransformedDistribution):
    r"""The Gumbel distribution with location `loc` and `scale` parameters.

    Mathematical details

    The probability density function (pdf) is

    .. math::

        pdf(x; mu, sigma) = exp(-(x - mu) / sigma - exp(-(x - mu) / sigma)) / sigma


    In the above equation:

    * :math:`loc = \mu`: is the mean.
    * :math:`scale = \sigma`: is the std.

    Args:
        loc(int|float): The mean of normal distribution.The data type is int, float.
        scale(int|float): The std of normal distribution.The data type is int, float.

    Examples:
        .. code-block:: python

          import paddle
          from paddle.distribution import Gumbel

          # Define a single scalar Gumbel distribution.
          dist = Gumbel(loc=0., scale=1.)
    """

    def __init__(self, loc, scale):
        if not isinstance(loc, (numbers.Real, framework.Variable)):
            raise TypeError(
                f"Expected type of loc is Real|Variable, but got {type(loc)}")

        if not isinstance(scale, (numbers.Real, framework.Variable)):
            raise TypeError(
                f"Expected type of scale is Real|Variable, but got {type(scale)}"
            )
        self.loc, self.scale = paddle.broadcast_tensors([loc, scale])
        finfo = np.finfo(self.loc.dtype)
        if isinstance(loc, numbers.Number) and isinstance(scale, numbers.Number):
            base_dist = Uniform(finfo.tiny, 1 - finfo.eps)
        else:
            base_dist = Uniform(paddle.full_like(self.loc, finfo.tiny),
                                paddle.full_like(self.loc, 1 - finfo.eps))
        transforms = [ExpTransform().inverse(self), AffineTransform(loc=0, scale=-paddle.ones_like(self.scale)),
                      ExpTransform().inverse(self), AffineTransform(loc=loc, scale=-self.scale)]
        super(Gumbel, self).__init__(base_dist, transforms)

    @property
    def mean(self):
        """Mean of distribution

        The variance is

        .. math::

            mean = \mu + \sigma * γ

        In the above equation:

        * :math:`loc = \mu`: is the location parameter.
        * :math:`scale = \sigma`: is the scale parameter.
        * :math:`γ`: is the euler's constant.

        Returns:
            Tensor: mean value.

        """
        return self.loc + self.scale * np.euler_gamma

    @property
    def variance(self):
        """Variance of distribution.

        The variance is

        .. math::

            variance = \sigma^2 * \pi^2 / 6

        In the above equation:

        * :math:`scale = \sigma`: is the scale parameter.

        Returns:
            Tensor: The variance value.

        """
        return self.scale.pow(2) * math.pi.pow(2) / 6

    @property
    def stddev(self):
        """Standard deviation of distribution

        The standard deviation is

        .. math::

            stddev = \sqrt(\sigma^2 * \pi^2 / 6)

        In the above equation:

        * :math:`scale = \sigma`: is the scale parameter.

        Returns:
            Tensor: std value.

        """
        return math.sqrt(self.variance)

    def prob(self, value):
        """Probability density/mass function.

        The probability density is

        .. math::

            prob(value) = e^({y} - e^{y}) / \sigma

        .. math::

            y = (\mu - value) / \sigma

        In the above equation:

        * :math:`loc = \mu`: is the location parameter.
        * :math:`scale = \sigma`: is the scale parameter.

        Args:
          value (Tensor): The input tensor.

        Returns:
          Tensor: probability.The data type is same with value.

        """
        y = (self.loc - value) / self.scale
        return math.exp(y - math.exp(y)) / self.scale

    def log_prob(self, value):
        """Log probability density/mass function.

        Args:
          value (Tensor): The input tensor.

        Returns:
          Tensor: log probability.The data type is same with value.

        """
        return math.log(self.prob(value))

    def entropy(self):
        r"""Shannon entropy in nats.

        The entropy is

        .. math::

            entropy(\sigma) = \\log(\sigma) + 1 + γ

        In the above equation:

        * :math:`scale = \sigma`: is the scale parameter.
        * :math:`γ`: is the euler's constant.

        Returns:
          Tensor: Shannon entropy of gumbel distribution.

        """
        return math.log(self.scale) + 1 + np.euler_gamma
`

---------------------------------------------
__init__:
`from paddle.distribution import transform
from paddle.distribution.beta import Beta
from paddle.distribution.categorical import Categorical
from paddle.distribution.dirichlet import Dirichlet
from paddle.distribution.distribution import Distribution
from paddle.distribution.exponential_family import ExponentialFamily
from paddle.distribution.independent import Independent
from paddle.distribution.kl import kl_divergence, register_kl
from paddle.distribution.multinomial import Multinomial
from paddle.distribution.normal import Normal
from paddle.distribution.transform import *  # noqa: F403
from paddle.distribution.transformed_distribution import \
    TransformedDistribution
from paddle.distribution.uniform import Uniform
from paddle.distribution.gumbel import Gumbel

__all__ = [  # noqa
    'Beta', 'Categorical', 'Dirichlet', 'Distribution', 'ExponentialFamily',
    'Multinomial', 'Normal', 'Uniform', 'kl_divergence', 'register_kl',
    'Independent', 'TransformedDistribution','Gumbel'
]



__all__.extend(transform.__all__)`

**Comment by cxxly** [comment]
你好，你的测试用例是怎么运行的，是用ctest，还是直接运行python文件

**Comment by dasenCoding** [comment]
我直接运行的python文件。

**Comment by cxxly** [comment]
错误的原因应该是你在build目录下运行了测试用例, build目录下每个用例会编译乘独立单元，要找到依赖关系，需要通过PYTHONPATH自己配置，有些麻烦。建议：
1）编译安装，直接运行${PADDLEROOT}/python/paddle/...下的单测试文件
2）cmake选项 -DWITH_TESTING=ON，编译，build目录下通过ctest运行

**Comment by cxxly** [comment]
另外，你贴的代码中出现许多错误，不过这个和上述报错原因无关，优先能运行，然后自己逐步debug

**Comment by dasenCoding** [comment]
谢谢，问题已解决！
