### ISSUE TITLE
'module' object has no attribute 'square_error_cost'

### ISSUE THREAD

**Issue by zxskylc** [PaddlePaddle/Paddle#4623]
在运行线性回归例子的时候，系统提示
'module' object has no attribute 'square_error_cost' 报错……

“”“
Traceback (most recent call last):
  File "yihuo.py", line 105, in <module>
    main()
  File "yihuo.py", line 55, in main
    cost = paddle.layer.square_error_cost(input=y_predict, label=y)
“”“
是因为版本的问题么？似乎我用的是挺老的版本了……

**Comment by NHZlX** [comment]
嗯， 请确保你的paddle的版本是否是最新的
