### ISSUE TITLE
Need to flush `vars_` in `BlockDescBind::Sync()`

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#4624]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/block_desc.cc#L69

This issue will be fixed in #4537.

**Comment by tonyyang-svail** [comment]
@jacquesqiao @Canpio  Please confirm this issue.

**Comment by Canpio** [comment]
Yes, we should flush `vars_`. I'm going to fix it.
