### ISSUE TITLE
关于paddle C++ infer的内存占用异常增加问题

### ISSUE THREAD

**Issue by jjrCN** [PaddlePaddle/Paddle#46252]
### 请提出你的问题 Please ask your question

我们业务中出现了一个问题，我们的backbone为r34的检测模型仅仅增加了一个1*1卷积时，在通过trt的int8量化后，C++ infer时的内存占用从2G增加到了3G。
想请教下paddle同学有关paddle C++ infer时的内存申请机制，有可能是什么原因导致的这个问题？
谢谢

**Comment by jjrCN** [comment]
有人吗

**Comment by an1018** [comment]
请问解决了吗

**Comment by jjrCN** [comment]
解决了
