### ISSUE TITLE
How to use capi to input "integer_value"?

### ISSUE THREAD

**Issue by zds9204** [PaddlePaddle/Paddle#4626]
您好，我在使用capi调用训练的网络，网络的输入层如下：
`
month = paddle.layer.data(name="month", type=paddle.data_type.integer_value(12))
week  = paddle.layer.data(name="week",  type=paddle.data_type.integer_value(7))
hour  = paddle.layer.data(name="hour",  type=paddle.data_type.integer_value(24))
    city  = paddle.layer.data(name="city",  type=paddle.data_type.integer_value(3240))
    phoneos    = paddle.layer.data(name="os",         type=paddle.data_type.integer_value(3))
    homedist   = paddle.layer.data(name="homedist",   type=paddle.data_type.integer_value(10))
    compdist   = paddle.layer.data(name="compdist",   type=paddle.data_type.integer_value(10))
    homecity   = paddle.layer.data(name="homecity",   type=paddle.data_type.integer_value(3))
    newcity    = paddle.layer.data(name="newcity",    type=paddle.data_type.integer_value(3))
    gender     = paddle.layer.data(name="gender",     type=paddle.data_type.integer_value(3))
    age        = paddle.layer.data(name="age",        type=paddle.data_type.integer_value(8))
    life_stage = paddle.layer.data(name="life_stage", type=paddle.data_type.integer_value(22))
    status     = paddle.layer.data(name="status",     type=paddle.data_type.integer_value(3))
    trade      = paddle.layer.data(name="trade",      type=paddle.data_type.integer_value(24))
    education  = paddle.layer.data(name="education",  type=paddle.data_type.integer_value(4))
    job        = paddle.layer.data(name="job",        type=paddle.data_type.integer_value(7))
    consumption = paddle.layer.data(name="consumption", type=paddle.data_type.integer_value(37))
    catering_expense_level = paddle.layer.data(name="catering_expense_level", type=paddle.data_type.integer_value(4))
`
`
    travelpref = paddle.layer.data(name="travelpref", type=paddle.data_type.dense_vector(4))
    carowner   = paddle.layer.data(name="carowner",   type=paddle.data_type.dense_vector(1))
    privatedriver = paddle.layer.data(name="privatedriver", type=paddle.data_type.dense_vector(1))
    drive      = paddle.layer.data(name="drive",    type=paddle.data_type.dense_vector(3))
    carserve   = paddle.layer.data(name="carserve", type=paddle.data_type.dense_vector(3))
    gas        = paddle.layer.data(name="gas",      type=paddle.data_type.dense_vector(3))
    poi4s      = paddle.layer.data(name="poi4s",    type=paddle.data_type.dense_vector(3))
    park       = paddle.layer.data(name="park",     type=paddle.data_type.dense_vector(3))
    drive_weekday = paddle.layer.data(name="drive_weekday", type=paddle.data_type.dense_vector(3))
    drive_weekend = paddle.layer.data(name="drive_weekend", type=paddle.data_type.dense_vector(3))
    consumption_will = paddle.layer.data(name="consumption_will", type=paddle.data_type.dense_vector(36))
`
`
    taghistyear = paddle.layer.data(name="taghistyear", type=paddle.data_type.dense_vector(802))
    taghisthour = paddle.layer.data(name="taghisthour", type=paddle.data_type.dense_vector(802 * 24))
    taghistweek = paddle.layer.data(name="taghistweek", type=paddle.data_type.dense_vector(802 * 2))
`
现问题如下：
1. 模型中的data layer非常多，capi中，也需要这么多slot来对应这些data layer吗？这样在代码中维护起来非常困难，有更简便的方法吗？
2. integer_value这种类型，我的网络后面接了embedding层，我在capi的样例程序中没有看到合适的输入样例：[https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference)请问这种输入类型如何输入？使用样例中sequence的输入方式，把长度改为1，能够满足这种需求吗？

**Comment by luotao1** [comment]
> 模型中的data layer非常多，capi中，也需要这么多slot来对应这些data layer吗？

是的，c-api中需要slot和data layer一一对应。不过您调用的是训练时的网络，capi应该调用预测时的网络，改成预测时的网络，data layer会减少一点么？

> integer_value这种类型

使用`paddle_arguments_set_ids`函数来设置即可。

**Comment by zds9204** [comment]
> 改成预测时的网络，data layer会减少一点么？  

我们目前的预测网络和训练网络结构是一样的，以后可以看看能不能化简一些
> 使用paddle_arguments_set_ids函数来设置即可。   

是按照sequence长度为1的方式，来进行设置吗？

**Comment by luotao1** [comment]
> 是按照sequence长度为1的方式，来进行设置吗

不用。直接设置即可。可参考单测[test_Arguments.cpp](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/tests/test_Arguments.cpp#L71)中的写法：
```
  paddle_ivector ivec;
  int array[3] = {1, 2, 3};
  ivec = paddle_ivector_create(array, 3, true, false);
  paddle_arguments_set_ids(args, 0, ivec);
```

**Comment by zds9204** [comment]
多谢，按照上面的方法，问题可以解决。
建议paddle的同学补充一下capi的例子以及api说明文档，现在很多api都得查源码才能稍微了解。
