### ISSUE TITLE
There should be a fill_one_like_op as an starting point of backward pass

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#4627]
Notice the file_one_op at the beginning of the backward.

![Backward Pass](https://media.licdn.com/mpr/mpr/AAEAAQAAAAAAAAvwAAAAJDEwYjMyOTJiLTkyMTUtNGRkZS04NDExLTc3MDdiMTc3NTg0YQ.png)

**Comment by Canpio** [comment]
How about rename the current `fill_zeros_like_op` to `fill_op`, and make the constant to be filled as an attribute?

**Comment by Canpio** [comment]
I checked the TensorFlow, and found they have two ops: `zeros_like` and `ones_like`.
https://www.tensorflow.org/api_guides/python/constant_op

And these two commands also exist in numpy. So I think my previous comment is not correct and we do need `ones_like_op`.

**Comment by tonyyang-svail** [comment]
According to @Canpio @jacquesqiao, this has already been fixed.
