### ISSUE TITLE
Add the Factorization Machine Layer / Operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#4628]
Factorization machines can be compared to support vector machines (SVMs) with a polynomial kernel, which is highly used in recommendation problem to estimate more complex interactions (2-order or even higher).

FM helps to make learning interactions among large-scale categorical features tractable.

**Comment by typhoonzero** [comment]
Shall we add as a `Layer` or an `Operator`?

**Comment by lcy-seso** [comment]
I prefer to add a layer first, so we can use it under the current framework. And then port it to an operator under the new framework.
