### ISSUE TITLE
Limit Python version >= 3.7

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#46314]
### 问题描述 Please describe your issue

Python supports type hint from version 3.5 https://docs.python.org/3/library/typing.html. And we can write codes like this
```
def greeting(name: str) -> str:
    return 'Hello ' + name
```
which is more readable and easier to use than we use now. And Python 3.6 has an [surprisingly bug](https://stackoverflow.com/questions/56394350/how-to-resolve-this-import-error-in-python-3-6)
So will we limit the Python version to greater than 3.7?

**Comment by jzhang533** [comment]
Python 3.6 has reached end-of-life, I second this proposal.

**Comment by luotao1** [comment]
close due to https://github.com/PaddlePaddle/Paddle/pull/46477 merged
