### ISSUE TITLE
使用softmax计算大矩阵报错

### ISSUE THREAD

**Issue by Wenze7** [PaddlePaddle/Paddle#46330]
### 请提出你的问题 Please ask your question

我的矩阵是256*384*50000的，在最后一维使用softmax进行降维，报了下面的错
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/55132749/191305501-808d56a3-01c1-4214-bed4-fe12b93b4f03.png">
怎么能让我计算这个大矩阵呢，设备是A100 80G

**Comment by yt605155624** [comment]
可以先在 issue 区搜下 `CUDNN_STATUS_NOT_SUPPORTED` 尝试可能的解决办法

**Comment by w5688414** [comment]
可以尝试切分数据分片进行softmax
