### ISSUE TITLE
切片赋值不能传播梯度

### ISSUE THREAD

**Issue by luochenghonggithub** [PaddlePaddle/Paddle#46338]
### 请提出你的问题 Please ask your question

你好，我将一个能传播梯度的tensor赋值给另一个tensor，如何保持stop_gradient=False呢？
代码如下：
`mat = paddle.zeros((n, n))`
`mat[index1, index2] = probs`
probs的stop_gradient=False，我该如何让赋值后的mat也是False呢？
如果使用pytorch，赋值后的mat的grad_fn=<IndexPutBackward0>是能传播梯度的。
谢谢！

**Comment by w5688414** [comment]
请问您的paddle版本是哪个。

以下是我复现的环境：

+ paddlepaddle                       2.3.0  
+ macos

```
import paddle
n=10
mat = paddle.zeros((n, n))
probs = 1
index1=1 
index2 =2
mat[index1, index2] = probs
mat.stop_gradient=False
print(mat)
```

我的输出：

```
Tensor(shape=[10, 10], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
```

**Comment by luochenghonggithub** [comment]
谢谢，你这个不会造成mat的stop_gradient = True。
我发现是index的问题，当index是numpy或者tensor的时候就会造成stop_gradient=True，此时即使将stop_gradient设置为False也没用，backward后grad是None.
我将index设置为python的list就好了。

代码如下：
```
import paddle
from paddle import nn

import numpy as np

n = 9

index1 = np.array([0])
index2 = np.array([0])

x = paddle.rand((1, ))

net1 = nn.Linear(1, 1)
y1 = net1(x)
mat1 = paddle.zeros((n, n + 1))
mat1[index1, index2] = y1
loss1 = paddle.sum(mat1)
print(loss1.stop_gradient)
loss1.stop_gradient = False
print(loss1.stop_gradient)
loss1.backward()
print(net1.weight.grad)

net2 = nn.Linear(1, 1)
y2 = net2(x)
mat2 = paddle.zeros((n, n + 1))
mat2[index1.tolist(), index2.tolist()] = y2
loss2 = paddle.sum(mat2)
print(loss2.stop_gradient)
loss2.backward()
print(net2.weight.grad)
```

相应的输出是：
```
True
False
None
False
Tensor(shape=[1, 1], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[0.93701142]])
```

**Comment by luochenghonggithub** [comment]
> 请问您的paddle版本是哪个。
> 
> 以下是我复现的环境：
> 
> * paddlepaddle                       2.3.0
> * macos
> 
> ```
> import paddle
> n=10
> mat = paddle.zeros((n, n))
> probs = 1
> index1=1 
> index2 =2
> mat[index1, index2] = probs
> mat.stop_gradient=False
> print(mat)
> ```
> 
> 我的输出：
> 
> ```
> Tensor(shape=[10, 10], dtype=float32, place=Place(cpu), stop_gradient=False,
>        [[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
>         [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])
> ```
