### ISSUE TITLE
如何实现W*H*C按照channel转置为 H* W * C 顺序

### ISSUE THREAD

**Issue by Yipeng-Sun** [PaddlePaddle/Paddle#4634]
输入为`W*H*C`的feature_map，希望实现对每个channel进行转置操作，得到输出为`H*W*C`的feature map。

是否需要单独写layer来实现？根据文档说明，现有trans_layer, rotate_layer并不能直接使用

**Comment by Yipeng-Sun** [comment]
如题：输入为W*H*C的feature_map，希望实现对每个channel进行转置操作，得到输出为H*W*C的feature map, 根据文档说明，现有trans_layer, rotate_layer并不能直接使用，是否需要单独写layer来实现？非常感谢！

**Comment by chengduoZH** [comment]
可以尝试使用[switch_order_layer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L6479)

**Comment by Yipeng-Sun** [comment]
`swith_order_layer`不能解决该问题.

**Comment by Yipeng-Sun** [comment]
一种较简单的解决办法：在`BlockExpandLayer`中输出矩阵的存储形式由`N*C*H*W` -> 改为`N*C*W*H`，由行优先改为列优先，可以通过新增BlockExpandTransLayer实现，修改完成.cpp/.h代码后，在python中新增layer接口，重新编译安装paddle即可。注：使用版本paddle-0.9.0
