### ISSUE TITLE
gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.2, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#46381]
`python -m pip install paddlepaddle-gpu==2.3.2.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
`

C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6
覆盖了
cudnn-windows-x86_64-8.4.0.27_cuda11.6-archive

还是提示
`gpu_resources.cc:201] WARNING: device: . The installed Paddle is compiled with CUDNN 8.4, but CUDNN version in your machine is 8.2, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.`

**Comment by 1649759610** [comment]
可以确认下当前环境默认运行的cudnn版本是否已经是8.4版本，Cuddnn环境变量是否配置好。

**Comment by fishisnow** [comment]
这个问题解决了吗，遇到同样的报错，检查了虚拟环境和本机的 cuddnn 版本都是没有8.2, 但是就是是报这个错。
