### ISSUE TITLE
龙芯uos源码编译安装v2.3.2报错

### ISSUE THREAD

**Issue by PeterWesley** [PaddlePaddle/Paddle#46392]
### 龙芯uos源码编译安装v2.3.2报错

**龙芯平台不支持v0.3.13的openblas源码编译**
[  1%] Built target extern_zlib
[  2%] Built target extern_protobuf
[  2%] Built target extern_gflags
[  2%] copy_if_different /home/jywang/software/image/Paddle/build/paddle/fluid/operators/jit/kernels.h
[  2%] Built target copy_kernels_command
[  2%] copy_if_different /home/jywang/software/image/Paddle/build/paddle/phi/kernels/declarations.h
[  2%] Built target copy_declarations_command
[  2%] copy_if_different /home/jywang/software/image/Paddle/build/paddle/phi/ops/compat/signatures.h
[  2%] Built target copy_signatures_command
[  2%] copy_if_different /home/jywang/software/image/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  2%] Built target copy_paddle_inference_pass_command
[  2%] copy_if_different /home/jywang/software/image/Paddle/build/paddle/fluid/pybind/pybind.h
[  2%] Built target copy_pybind_command
[  2%] Built target extern_glog
Consolidate compiler generated dependencies of target framework_proto
[  2%] Built target framework_proto
[  2%] Built target extern_boost
Consolidate compiler generated dependencies of target flags
[  2%] Built target flags
Consolidate compiler generated dependencies of target errors
[  2%] Built target errors
Consolidate compiler generated dependencies of target phi_enforce
[  2%] Built target phi_enforce
Consolidate compiler generated dependencies of target enforce
[  2%] Built target enforce
Consolidate compiler generated dependencies of target workqueue_utils
[  2%] Built target workqueue_utils
[  3%] Built target extern_eigen3
[  3%] Built target extern_threadpool
[  3%] Built target extern_dlpack
Consolidate compiler generated dependencies of target shape_range_info_proto
[  3%] Built target shape_range_info_proto
Consolidate compiler generated dependencies of target profiler_proto
[  4%] Built target profiler_proto
Consolidate compiler generated dependencies of target nodetreeproto
[  4%] Built target nodetreeproto
Consolidate compiler generated dependencies of target interceptor_message_proto
[  5%] Built target interceptor_message_proto
Consolidate compiler generated dependencies of target fleet_executor_desc_proto
[  5%] Built target fleet_executor_desc_proto
Consolidate compiler generated dependencies of target data_feed_proto
[  5%] Built target data_feed_proto
Consolidate compiler generated dependencies of target trainer_desc_proto
[  6%] Built target trainer_desc_proto
Consolidate compiler generated dependencies of target op_def_proto
[  6%] Built target op_def_proto
Consolidate compiler generated dependencies of target pass_desc_proto
[  6%] Built target pass_desc_proto
Consolidate compiler generated dependencies of target heter_service_proto
[  6%] Built target heter_service_proto
[  6%] Built target extern_xxhash
[  6%] Performing build step for 'extern_openblas'
getarch.c:1392:2: error: #error "This arch/CPU is not supported by OpenBLAS."
 #error "This arch/CPU is not supported by OpenBLAS."
  ^~~~~
getarch.c: In function ‘main’:
getarch.c:1459:5: warning: implicit declaration of function ‘get_libname’; did you mean ‘gethostname’? [-Wimplicit-function-declaration]
     get_libname();
     ^~~~~~~~~~~
     gethostname
getarch.c:1592:5: warning: implicit declaration of function ‘get_cpuconfig’ [-Wimplicit-function-declaration]
     get_cpuconfig();
     ^~~~~~~~~~~~~
make[3]: *** [Makefile.prebuild:70：getarch] 错误 1
Makefile.system:1319: Makefile.: 没有那个文件或目录
make[3]: *** 没有规则可制作目标“Makefile.”。 停止。
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:86：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4698：CMakeFiles/extern_openblas.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

**而我的机器上已经有v0.3.5的openblas库文件了，同时也有libz等一些库文件，但是cmake完之后还是会去抓取源码并安装，请问如何避免这种情况**
jywang@uos-PC:/usr/lib/loongarch64-linux-gnu$ ls -al libopenblas*
lrwxrwxrwx 1 root root       33 6月  14 11:24 libopenblas.a -> libopenblas_loongson3r5p-r0.3.5.a
-rw-r--r-- 1 root root 48129530 6月  14 11:24 libopenblas_loongson3r5p-r0.3.5.a
-rw-r--r-- 1 root root  8791368 6月  14 11:24 libopenblas_loongson3r5p-r0.3.5.so
lrwxrwxrwx 1 root root       34 6月  14 11:24 libopenblas.so -> libopenblas_loongson3r5p-r0.3.5.so
lrwxrwxrwx 1 root root       34 6月  14 11:24 libopenblas.so.0 -> libopenblas_loongson3r5p-r0.3.5.so

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

**OS: UnionTech OS Server 20 Military 20**
**Python version: 3.7.3**

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None

**Architecture:        loongarch64**
Byte Order:          Little Endian
CPU family:          Loongson-64bit
Model name:          Loongson-3C5000L
BogoMIPS:            4400.00
Flags:               cpucfg lam ual fpu lsx lasx complex crypto lvz lbt_x86 lbt_arm lbt_mips
****************************************

**cmake选项**
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MIPS=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_MKL=OFF

**Comment by jzhang533** [comment]
这样试试：`export OPENBLAS_ROOT=<PATH_TO_OPENBLAS>`

**Comment by qili93** [comment]
这里的问题是飞桨编译的时候 cmake 没有找到系统安装的 blas，所以自己又下载 openblas 源码编译导致的。建议可以参考这个修复PR，加点 cmake 的 message 代码，保证飞桨编译走的是系统安装的 blas 就可以避免这个问题。

https://github.com/PaddlePaddle/Paddle/pull/42953/files

龙芯 CPU 的安装说明可以参考这个文档 
https://www.paddlepaddle.org.cn/inference/master/guides/hardware_support/cpu_loongson_cn.html

主要的寻找 cblas 的逻辑从这里的代码开始 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L50 保证64-71行能找到对应的系统文件，否则就会走到 143行通过extern_openblas 编译了。

因为非镜像环境下系统的 cbals 和 lapacke 的地址路径可能都有差异，所以很容易导致 64-71行找不到对应的文件。建议先手动在系统的/usr/目录下搜索到对应的 cblas.h lapacke.h openblas_config.h 以及 libopenblas.so 这四个文件之后，再尝试修改 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L61 这里的代码保证这4个文件能被正确找到。

**Comment by PeterWesley** [comment]
> 这里的问题是飞桨编译的时候 cmake 没有找到系统安装的 blas，所以自己又下载 openblas 源码编译导致的。建议可以参考这个修复PR，加点 cmake 的 message 代码，保证飞桨编译走的是系统安装的 blas 就可以避免这个问题。
> 
> https://github.com/PaddlePaddle/Paddle/pull/42953/files
> 
> 龙芯 CPU 的安装说明可以参考这个文档 https://www.paddlepaddle.org.cn/inference/master/guides/hardware_support/cpu_loongson_cn.html
> 
> 主要的寻找 cblas 的逻辑从这里的代码开始 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L50 保证64-71行能找到对应的系统文件，否则就会走到 143行通过extern_openblas 编译了。
> 
> 因为非镜像环境下系统的 cbals 和 lapacke 的地址路径可能都有差异，所以很容易导致 64-71行找不到对应的文件。建议先手动在系统的/usr/目录下搜索到对应的 cblas.h lapacke.h openblas_config.h 以及 libopenblas.so 这四个文件之后，再尝试修改 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cblas.cmake#L61 这里的代码保证这4个文件能被正确找到。

感谢，通过修改已成功完成编译

**Comment by moosewoler** [comment]
> 

我已经编译通过了v2.3.2和develop分支，你看我的文章。
https://zhuanlan.zhihu.com/p/589311248?
