### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#46404]
## I'm participating  in  PaddlePaddle Hackathon 3rd,  this is  my  PR : https://github.com/PaddlePaddle/Paddle/pull/46333,  I'm confused about this error. [failed  CI](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/6689890/job/18678001)
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31559413/191705519-3f5892b6-6a32-4050-9b31-c4caab2a4c26.png">

## I find  other similar errors  reported by other people, but none of them is related to my problem   
https://github.com/PaddlePaddle/PaddleOCR/issues/4333    
https://github.com/PaddlePaddle/Paddle/issues/28253   
https://pythontechworld.com/issue/paddlepaddle/paddleocr/6338

**Comment by OccupyMars2030** [comment]
# typo
<img width="960" alt="image" src="https://user-images.githubusercontent.com/31559413/191873939-e2975191-2610-4db1-b9a9-28c776b26b26.png">

**Comment by 1649759610** [comment]
You can try manually rebuilding the CI task several times.  And  we will solve these problems above as soon as possible.

**Comment by OccupyMars2030** [comment]
I find that my newly added code is probably the cause of error. The error has nothing to do with the PaddlePaddle itself.
I have been modifying my PR, and I find that  the cpu forward coo kernel can work in a right way,  and all other kernels seem to cause all kinds of errors.  I will try to fix it by myself. Thank you.
