### ISSUE TITLE
From paddle import inference No inference in paddle when running on jetson nano

### ISSUE THREAD

**Issue by Mu23rad** [PaddlePaddle/Paddle#46414]
### bug描述 Describe the Bug

import paddle 
from paddleocr import PaddleOCR

### 其他补充信息 Additional Supplementary Information

![paddle](https://user-images.githubusercontent.com/90346796/191738190-3d3b5142-25db-43b1-8877-b2e7fb4bfb1d.PNG)
this is the output i get on jetson nano

**Comment by 1649759610** [comment]
可以尝试升级一下paddle，或者提供一下padlde和paddleocr的版本。
