### ISSUE TITLE
多卡训练报错

### ISSUE THREAD

**Issue by wangna11BD** [PaddlePaddle/Paddle#46425]
### bug描述 Describe the Bug

单卡可正常训练，多卡报错如下，find_unused_parameters=True已设置
<img width="1014" alt="fdbed07a6cc101664b06ee47e" src="https://user-images.githubusercontent.com/79366697/191774290-f8111538-b48a-468f-a244-5aabcc09485a.png">

**Comment by 1649759610** [comment]
你这边是训练的哪个模型呢，方便提供下复现代码吗？
