### ISSUE TITLE
Custom Device使用文档和接口实现

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#46440]
### 需求描述 Feature Description

任务目标 针对Custom_Device自定义设备的在Paddle上实现; <br /> 
自制GPU计算 运行在Paddle上;  <br /> 
使用OpenCL运行PHI

我想用OpenCL实现PHI（或者别的图形API）
我该如何去使用custom_device 实现哪些接口，补充什么代码？
有没有文档介绍，或者告诉我大致的头文件位置

**Comment by qili93** [comment]
您好，关于 custom device 的相关文档可以参考这里：

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/custom_device_docs/index_cn.html

Custom device 接入的设备可以参考如下代码：
昇腾 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
Custom CPU (就是用 CPU 代码模拟一个硬件设备实现 custom device 功能) https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/custom_cpu/README_cn.md

OpenCL 通过 custom device 接入飞桨主要需要分为2个步骤：

1. custom runtime 实现，具体实现代码可以参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/custom_cpu/runtime/runtime.cc 
2. custom kernel 实现，这里根据实际需要运行的模型开发模型所需的相应算子 Kernel 即可 参考 https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/custom_cpu/kernels

如果需要支持分布式训练，则还需要开发
3. custom ccl 实现，即 custom runtime 中的 ccl 接口来接入硬件的集合通信库
