### ISSUE TITLE
Typo in auto_tune_base.h

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#46453]
### 问题描述 Please describe your issue

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/autotune/auto_tune_base.h#L25

Maybe there is ReturnType not RetureType? Just a small typo

**Comment by wangzhen38** [comment]
Thank you for your attention, we will fix it as soon as possible.

**Comment by JamesLim-sy** [comment]
Has been delt with in [PR30834](https://github.com/PaddlePaddle/Paddle/pull/41878)
