### ISSUE TITLE
Paddle论文复现

### ISSUE THREAD

**Issue by liuhongen1234567** [PaddlePaddle/Paddle#46465]
### 问题描述 Please describe your issue

@once_differentiable在paddle中应该用什么函数替换
`
import torch
from torch import nn
from torch.autograd import Function
from torch.autograd.function import once_differentiable
from torch.nn.modules.utils import _pair

from csrc import _C

class _RROIAlign(Function):
    @staticmethod
    def forward(ctx, input, roi, output_size, spatial_scale):

        ctx.output_size = _pair(output_size)
        ctx.spatial_scale = spatial_scale
        ctx.input_shape = input.size()
        total_output = _C.rroi_align_forward(
            input, roi, spatial_scale, output_size[0], output_size[1]
        )

        output, con_idx_x, con_idx_y = total_output
        ctx.save_for_backward(roi, con_idx_x, con_idx_y)

        return output

    @staticmethod
    @once_differentiable
    def backward(ctx, grad_output):
        rois, con_idx_x, con_idx_y = ctx.saved_tensors
        output_size = ctx.output_size
        spatial_scale = ctx.spatial_scale
        bs, ch, h, w = ctx.input_shape
        grad_input = _C.rroi_align_backward(
            grad_output,
            rois,
            con_idx_x,
            con_idx_y,
            spatial_scale,
            output_size[0],
            output_size[1],
            bs,
            ch,
            h,
            w
        )
        return grad_input, None, None, None

rroi_align = _RROIAlign.apply`

**Comment by wangzhen38** [comment]
你参考下这个接口，看能不能满足需求，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/autograd/PyLayerContext_cn.html#mark-non-differentiable-self-tensors
