### ISSUE TITLE
无法在kaggle上使用GPU版本的paddle

### ISSUE THREAD

**Issue by yinpub** [PaddlePaddle/Paddle#46474]
### 问题描述 Issue Description

我正在打一场kaggle的比赛，并用paddle写了一个baseline。问题是，我想用GPU跑模型，GPU的占用率一直0% CPU的占用率已经到了200%. (可显存确依然有占据)。现在我的code只跑了一个CPU版本。
我也尝试了很多其他版本的paddle 包括2.2.2、2.1.2，无一幸免。希望这个问题能尽快得到处理！我还想用paddle做其他几场的方案，但paddle的安装是个基础。

这是我的baseline地址：
https://www.kaggle.com/code/yinhaojie/baseline-with-resnet-by-paddle

### 版本&环境信息 Version & Environment Information

 paddle2.3.2以及2.2.2

**Comment by haohongxiang** [comment]
@YinHaojie Hi，辛苦先check下paddlepaddle-gpu是否成功安装，具体指令是：
```
import paddle
paddle.utils.run_check()
```

如果出现下述结果，则已成功安装：
```
PaddlePaddle works well on 8 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
```

**Comment by haohongxiang** [comment]
@YinHaojie paddlepaddle-gpu安装方法详见[官网教程](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)

**Comment by yinpub** [comment]
> @YinHaojie paddlepaddle-gpu安装方法详见[官网教程](https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html)
![1% 5_SN$IRIH20O4}O0@CFC](https://user-images.githubusercontent.com/62241597/192284453-84697408-aec0-48d3-b9ff-bf5a8e1c1ca5.png)



![Uploading H`AQC}KT5C(}4]IWNBAF}JY.png…]()

**Comment by yinpub** [comment]
![H`AQC}KT5C(}4 IWNBAF}JY](https://user-images.githubusercontent.com/62241597/192285062-567d85f8-5711-469b-8da4-fb708c088f7e.png)

**Comment by parap1uie-s** [comment]
看一下features和predicts的place是cuda还是cpu。如果是cuda，说明GPU是用上了，可能是数据加载太慢导致GPU等CPU准备数据，体现出来也是GPU没占用而CPU打满
