### ISSUE TITLE
请问如果需要使用paddle模型部署在Windows上用于其它程序调用，需要使用什么，看哪篇文档

### ISSUE THREAD

**Issue by kslz** [PaddlePaddle/Paddle#46476]
### 请提出你的问题 Please ask your question

不依赖其它环境可以直接运行的形式，包括可调用CPU和GPU的形式

**Comment by XYZ-916** [comment]
请参考：
推理部署: https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/infer/index_cn.html
X86 Windows上预测部署示例：https://paddleinference.paddlepaddle.org.cn/master/demo_tutorial/x86_windows_demo.html

**Comment by kslz** [comment]
> 请参考： 推理部署: https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/infer/index_cn.html X86 Windows上预测部署示例：https://paddleinference.paddlepaddle.org.cn/master/demo_tutorial/x86_windows_demo.html

感谢
