### ISSUE TITLE
Will Paddle support C++17 in the future?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#46479]
### 请提出你的问题 Please ask your question

hi, is there a plan to update the C++ standard to cpp17 for paddle?

**Comment by XYZ-916** [comment]
Thanks for you question. We'll consider supporting C++ 17 standard in the future.

**Comment by gglin001** [comment]
> Thanks for you question. We'll consider supporting C++ 17 standard in the future.

is there a timeline or roadmap for it?

**Comment by XYZ-916** [comment]
> 

There is no timeline yet.
