### ISSUE TITLE
百度飞桨环境问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/Paddle#46488]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/114384977/192211318-7d82fd5e-f838-428b-a0ba-9930a80ab98f.png)
我在使用咱们的百度飞桨测试一个人像分割项目，点击的时是在线运行教程，该项目地址：
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.5/contrib/PP-HumanSeg/README_cn.md
能否尽快回复一下

**Comment by jingmingtao** [comment]
上述问题，我跟着教程一步步的走，不能复现，希望尽快回复一下我可以吗

**Comment by XYZ-916** [comment]
你好，请问你用的哪个分支？我这边看教程和代码对应不上。

**Comment by jingmingtao** [comment]
什么分支是啥意思，我是运行的上边项目地址，点击在线运行教程，想看看效果
![image](https://user-images.githubusercontent.com/114384977/192216702-4280d19f-329e-4c8c-921e-4e8cd29b6eb6.png)

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/192216881-cf6ff88f-89da-4d86-8747-a65b953668b7.png)

**Comment by jingmingtao** [comment]
在线运行的

**Comment by jingmingtao** [comment]
![image](https://user-images.githubusercontent.com/114384977/192217164-62eccaa6-0c39-49bd-97c0-866fb546cf07.png)
点击在线运行按钮
然后再点击如下按钮
![image](https://user-images.githubusercontent.com/114384977/192217340-c9df10a6-10d7-4fd5-8b99-b6454f76d937.png)
然后运行一下
![image](https://user-images.githubusercontent.com/114384977/192217415-904bc133-db4f-46bc-ac84-df4fc46f2dc0.png)

**Comment by jingmingtao** [comment]
我初步判断是环境问题，你可以试一试，是不是这个问题

**Comment by jingmingtao** [comment]
您说的代码跟教程对应不上指的是什么，可以截图一下吗

**Comment by XYZ-916** [comment]
我跑了一下AI Studio教程，确实有问题，建议你给教程的作者提一下你的问题。

我看项目评论里有：
“
paddle-seg在7月20日更新了2.6版本后，运行此项目会出现错误'numpy.ndarray' object has no attribute 'keys'。需要将此项目中第一行改为!pip install paddleseg==2.5
”
请参考。

**Comment by jingmingtao** [comment]
好的谢谢

**Comment by jingmingtao** [comment]
已经解决了，就是这个问题，谢谢
