### ISSUE TITLE
gpu测试机上安装whl包后，无法使用gpu

### ISSUE THREAD

**Issue by spantarXP** [PaddlePaddle/Paddle#46492]
### 问题描述 Issue Description

import paddle后，报warning: "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."

### 版本&环境信息 Version & Environment Information

Python 2.7.15
cuda11.4
nviddia Tesla V100卡

**Comment by XYZ-916** [comment]
请问您安装的Paddle版本是？

确保CUDA环境配置是否正确：
nvcc -V 查看一下显示什么 ， echo %PATH% 看看显示什么？
查看显卡驱动版本。
