### ISSUE TITLE
训练代码hang住

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#46523]
### 请提出你的问题 Please ask your question

具体现象是使用paddledetection训练1~3epoch过程会卡住，显卡利用率是100%，没有报错信息。

请问这种问题一般怎么调试呀？有可能是什么原因造成的？

**Comment by zhaoyinglia** [comment]
可以把 GLOG 打开，确认一下具体是 hang 在哪个操作上了。
