### ISSUE TITLE
RepVGG_B3预训练模型下载失败

### ISSUE THREAD

**Issue by 15554710621** [PaddlePaddle/Paddle#46524]
### 请提出你的问题 Please ask your question

https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/RepVGG_B3_pretrained.pdparams

**Comment by zhaoyinglia** [comment]
你好，麻烦请提供一下是在哪里的下载链接。

**Comment by zhaoyinglia** [comment]
你好，可以麻烦提供一下这个链接是哪个repo的吗？

**Comment by 15554710621** [comment]
![image](https://user-images.githubusercontent.com/108608277/192434402-8203cffe-e9fd-4f03-9511-9f4323bfa5f5.png)

**Comment by TingquanGao** [comment]
你好，我们目前并未提供B3的预训练模型。请问该下载链接是在哪里看到的呢？

**Comment by 15554710621** [comment]
不好意思，看错了

**Comment by 15554710621** [comment]
![image](https://user-images.githubusercontent.com/108608277/192489673-0969690c-89c8-4d0a-b4a9-fa5a3d6b2e87.png)

**Comment by 15554710621** [comment]
那个，我想另外问个问题，为什么最后一行的的警告不会被过滤掉呢
