### ISSUE TITLE
StyleGAN3算子复现问题

### ISSUE THREAD

**Issue by ouyangshixiong** [PaddlePaddle/Paddle#46563]
### 请提出你的问题 Please ask your question

飞桨开发团队，你们好。我尝试用飞桨复现论文StyleGAN3，遇到一个问题。https://github.com/NVlabs/stylegan3/blob/main/torch_utils/ops/conv2d_gradfix.py 这个算子里176-178行
![image](https://user-images.githubusercontent.com/2086862/192516233-972dded3-30c8-4029-a7f3-194661ba7242.png)
pytorch这种写法，在paddlepaddle中对应的代码应该怎么写呢？

**Comment by zhaoyinglia** [comment]
你好，可以尝试自定义算子来实现相关功能，但是需要重新编译paddle。参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html

**Comment by ouyangshixiong** [comment]
收到，我看看
