### ISSUE TITLE
分布式训练相关

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/Paddle#46564]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/108966996/192523633-39133285-bbbc-414f-a462-f468eb69bb33.png)
请问这个有ps架构的例子，那Ring AllReduce的例子有吗？或者说Ring AllReduce的例子就是‘’Collective 训练快速开始‘’这个

**Comment by zhaoyinglia** [comment]
你好，这个是否符合你的需要呢？https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/all_reduce_cn.html#all-reduce。
更详细的分布式训练的文档可以参考这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/distributed_overview.html

**Comment by AlphaMind123** [comment]
请问Collective 训练快速开始里面的那个resnet50的例子为什么没有设置gpu的操作呀


| |
hfqemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月27日 20:26 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 分布式训练相关 (Issue #46564) |

你好，这个是否符合你的需要呢？https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/all_reduce_cn.html#all-reduce。
更详细的分布式训练的文档可以参考这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/distributed_overview.html

**Comment by zhaoyinglia** [comment]
> 请问Collective 训练快速开始里面的那个resnet50的例子为什么没有设置gpu的操作呀 | | hfqemail | | ***@***.*** | ---- 回复的原

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/cluster_quick_start_collective_cn.html
你好，可以直接参考这个最新的教程。

**Comment by AlphaMind123** [comment]
thank you very much


| |
hfqemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月27日 20:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 分布式训练相关 (Issue #46564) |

请问Collective 训练快速开始里面的那个resnet50的例子为什么没有设置gpu的操作呀 | | hfqemail | | @.*** | ---- 回复的原

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/cluster_quick_start_collective_cn.html
你好，可以直接参考这个最新的教程。

**Comment by AlphaMind123** [comment]
你好，请问您发的这个网址怎么跟我在paddle官网的看到的内容不一样呢，那么是否也存在其他板块的内容也存在这个问题呢


| |
hfqemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年9月27日 20:40 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 分布式训练相关 (Issue #46564) |

请问Collective 训练快速开始里面的那个resnet50的例子为什么没有设置gpu的操作呀 | | hfqemail | | @.*** | ---- 回复的原

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/cluster_quick_start_collective_cn.html
你好，可以直接参考这个最新的教程。
