### ISSUE TITLE
paddle.utils.run_check() coredump

### ISSUE THREAD

**Issue by hnlslyp** [PaddlePaddle/Paddle#46570]
### bug描述 Describe the Bug

Centos 6.3
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 440.33.01    CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |

./python38/bin/python3.8 -c "import paddle;paddle.utils.run_check()"
/ssd1/lyp/python38/lib/python3.8/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Running verify PaddlePaddle program ...
W0927 21:21:29.765214 408282 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0927 21:21:29.798705 408282 gpu_resources.cc:91] device: 0, cuDNN Version: 7.0.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1664284894 (unix time) try "date -d @1664284894" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 408282 (TID 0x7f440115c740) from PID 0 ***]

Segmentation fault
You have new mail in /var/spool/mail/root

**Comment by zhaoyinglia** [comment]
你好，麻烦请提供一下安装的paddle版本和相关环境信息，谢谢。
