### ISSUE TITLE
[BUG] 请求Embedding OP支持越界检查

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#46578]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/16911935/192680287-828e6f3c-3e42-4a90-8fe1-68c181b1c45f.png)

embedding op 对于非法输入没有报错拦截，基本上是 出来 embedding只后 tensor 报 illegal memory access的错误。
对用户十分不友好，难以追查！！！

**Comment by seemingwang** [comment]
已经修复

**Comment by ZHUI** [comment]
Add embedding range check https://github.com/PaddlePaddle/Paddle/pull/46991
