### ISSUE TITLE
paddle.io库导入问题

### ISSUE THREAD

**Issue by utopiagamming** [PaddlePaddle/Paddle#46581]
### 请提出你的问题 Please ask your question

当我使用paddlepaddle1.8.0版本时，无法导入这个库，报错；
当我把paddlepaddle更新到最新版本时，仍然报错，无法使用。

**Comment by yeliang2258** [comment]
你好，具体的报错信息是？看起来paddle没有正确安装

**Comment by utopiagamming** [comment]
使用1.8.0时：
<img width="506" alt="image" src="https://user-images.githubusercontent.com/87075301/192700930-08d7f139-1fed-466a-8854-75c71cabc643.png">
<img width="862" alt="image" src="https://user-images.githubusercontent.com/87075301/192700976-5db4697e-1d4e-49ee-be4b-675f06c8803f.png">
使用最新版即2.3.2版时：
<img width="560" alt="image" src="https://user-images.githubusercontent.com/87075301/192701383-897fd173-4e3b-47db-b25f-d395a0a71d2b.png">
<img width="1215" alt="image" src="https://user-images.githubusercontent.com/87075301/192701388-01a5c784-da37-4838-b756-e000d0ed1cea.png">
（我不确定这样图片能不能正常显示。。）

**Comment by yeliang2258** [comment]
你的paddle是怎么安装的呢？可以用这个API验证一下：paddle.utils.run_check()

**Comment by yeliang2258** [comment]
安装可以参考这个文档：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

**Comment by utopiagamming** [comment]
使用这个API的时候好像也报错了，无论是第一次使用还是我uninstall在用你发的安装文档里的指令再装一次。
不过我不确定这个的用法，是不是先导入 import paddle 然后直接运行这条指令？
<img width="1240" alt="image" src="https://user-images.githubusercontent.com/87075301/192706642-6fe2f984-3b71-44a2-a890-96c8ec4c304c.png">

**Comment by utopiagamming** [comment]
我现在是在飞桨的平台环境中进行整个流程的，终端无法import所以直接在notebook里尝试了

**Comment by yeliang2258** [comment]
那就是你的paddle没有正确安装

**Comment by yeliang2258** [comment]
![image](https://user-images.githubusercontent.com/30516196/192710550-d9fc03a7-40d1-4442-8b53-1e4ed021a990.png)

**Comment by utopiagamming** [comment]
不，应该说我一开始不知道要先进入python环境，所以说了我不确定用的对不对。。。
然后我刚刚又尝试重装了一次，
刚刚重装那么多次都没行，这次很奇怪地就可以了...
无论如何暂时算是解决了，虽然我也不知道一样的命令为啥前面几次不行这次行。

**Comment by yeliang2258** [comment]
好的，估计是之前某个操作没有弄对吧。问题解决了就好

**Comment by utopiagamming** [comment]
是嘞，反正解决了，我先把它做完再说。非常感谢前辈啦，前辈辛苦。
