### ISSUE TITLE
训练集图片尺寸

### ISSUE THREAD

**Issue by pwy1327347084** [PaddlePaddle/Paddle#46584]
### 请提出你的问题 Please ask your question

在paddleseg和paddledetection训练中，训练集的图片尺寸一般都是640×640的吗，我一直用的是1080p和720p的图片在一块训练，会对训练结果有影响吗。如果有影响需要更改什么参数能够匹配高分辨率的图片呢。

**Comment by yeliang2258** [comment]
这个要对具体网络而言：
1. 如果不支持可变输入，网络训练之前都会有前处理保证输入数据的shape，你可以看看你训练的网络的前处理，如果是固定输入大小，则一般都会有resize的操作。
2. 如果网络的输入是可以支持随意shape的，那么你不同大小的输入并不会影响到训练结果。
