### ISSUE TITLE
自定义设备内存有时不会创建 Alloc失效

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#46597]
### bug描述 Describe the Bug

使用OpenCL多次创建内存后，dev_ctx.template Alloc<T>(out); 不起作用，没有创建内存，返回了一个奇怪的地址。

```
template <typename T>
void AbsKernel(const phi::Context &dev_ctx,
               const phi::DenseTensor &x,
               phi::DenseTensor *out)
{
    std::cout << "Abs" << std::endl;
    // 使用dev_ctx的Alloc API为输出参数out分配模板参数T数据类型的内存空间
    dev_ctx.template Alloc<T>(out);
    // 使用DenseTensor的numel API获取Tensor元素数量
    auto numel = x.numel();
    // // 使用DenseTensor的data API获取输入参数x的模板参数T类型的数据指针
    auto x_data = x.data<T>();
    // // 使用DenseTensor的data API获取输入参数y的模板参数T类型的数据指针

    // // 使用DenseTensor的data API获取输出参数out的模板参数T类型的数据指针
    auto out_data = out->data<T>();
    // // 完成计算逻辑
    // // for (auto i = 0; i < numel; ++i)
    // // {
    // //     out_data[i] = abs(x_data[i]);
    // // }
    x.dims();
    
    xdx::XDXOpenCLContext::getInstance()->runKernel(0, "abs_kernel", {x_data}, out_data, {numel});
}
```

```
allocate OpenCL0x1/8
memory_copy_h2d0x1/0x5555576f8840
allocate OpenCL0x2/2076672
memory_copy_h2d0x2/0x5555578c5a00
allocate OpenCL0x3/8
memory_copy_h2d0x3/0x555555f8d6a0
[       OK ] PaddleInferTest.inputData (6 ms)
[ RUN      ] PaddleInferTest.run
memory_copy_d2h0x7fff6ef7d040/0x2
allocate OpenCL0x4/2768896
memory_copy_h2d0x4/0x7fff6f6c3040
allocate OpenCL0x5/2768896
memory_copy_h2d0x5/0x7fff70beb040
Add
allocate OpenCL0x6/2768896
memory_copy_d2h0x7fff70e90040/0x6
memory_copy_h2d0x1a6804/0x7fff73632040
Create New Buffer0x1a6804
memory_copy_h2d0xa9004/0x7fff74a04040
Create New Buffer0xa9004
```

我设置驱动每次创建新内存的地址加一，
例如第一个创建的内存是0x1, 第二次创建是0x2
但是Alloc 会返回0x1a6804，从来没有创建过的OpenCL内存。

Paddle的内存Alloc是啥规律？

### 其他补充信息 Additional Supplementary Information

Ubuntu 20.04 GCC9.4.0
develop 22fe4f03f611fd6be5dd3cb291814546a6cec389

**Comment by engineer1109** [comment]
allocate OpenCL0x5/2768896
是allocate OpenCL 新地址/ 内存大小

memory_copy_d2h0x7fff6ef7d040/0x2 是 设备内存0x2 拷贝到 主机内存 0x7fff6ef7d040

Create New Buffer0x1a6804 是 BUG提示，
发现没有被驱动标记的内存地址 0x1a6804

**Comment by engineer1109** [comment]
改了下LOG
```
memory_copy_d2h Device0x7fff6ef7d040/ Host0x2
allocate OpenCL addr 0x4/ size 2768896
memory_copy_h2d Device0x4/ Host0x7fff6f6c3040
allocate OpenCL addr 0x5/ size 2768896
memory_copy_h2d Device0x5/ Host0x7fff70beb040
Add
allocate OpenCL addr 0x6/ size 2768896
memory_copy_d2h Device0x7fff70e90040/ Host0x6
memory_copy_h2d Device0x1a6804/ Host0x7fff73632040
Bad Device Memory0x1a6804
Fix to Create Device Memory
memory_copy_h2d Device0xa9004/ Host0x7fff74a04040
```

**Comment by engineer1109** [comment]
研究了一下，
自定义设备必须支持虚拟内存地址 (例如0x7ff00000)。
Paddle里面有FitAllocator不支持句柄类型地址（例如0x1 0x2 0x3)，所以不支持clCreateBuffer

使用clSVMAlloc 可以进行虚拟地址的内存分配, SVM的内存指针支持偏移量的访问

目前的内存分配器估计对opencl compute vulkan compute是很不友好的
需要在驱动补充虚拟地址的访问实现。

**Comment by qili93** [comment]
hi, @engineer1109 

请问您能提供一下自定义 runtime.cc 的具体实现代码吗？

Paddle 目前的自定义设备接入对于设备端内存的申请走的是 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/memory/allocation/custom_allocator.cc 的实现，这里通过 DeviceManager 类调用到了自定义 runtime 里面注册的 device_memory_allocate 接口。当前 custom_allocator.cc 的实现与 cuda_allocator.cc 的实现类似，不会限制必须使用虚拟地址，是可以直接申请设备上的显存地址的，比如可以调用 cudaMalloc，当前除非打开 FLAGS_use_cuda_managed_memory 才会调用到 cudaMallocManaged。

clCreateBuffer 的功能与 cudaMalloc 类似，区别在于 cudaMalloc 传入的是 **ptr，返回的是状态码； 而 clCreateBuffer 这是返回  cl_mem 类型的对象。因此这里需要对 clCreateBuffer 等内存操作功能进行一定的封装，使其能够返回指针地址不被释放即可（这里需要对 cl_mem 类型进行类型转换）。

您可以提供一下您实现的 runtime.cc 代码，这里协助分析一下问题的原因。

另外您这里提到“Paddle里面有FitAllocator不支持句柄类型地址”具体是指？

Thanks 
Qi
