### ISSUE TITLE
Numpy seed in DataLoader with multiprocessing

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/Paddle#46603]
### 请提出你的问题 Please ask your question

在Dataloader中，如果num_worker大于0，dataloader起的线程中的numpy的random seed不满足我自己设置的。
我的网络在评估的时候需要固定np.random.seed，我期望的是每个worker的numpy seed是一致的，这样对每个样本以同样的随机性进行预处理，然而paddle的dataloader在起线程的时候传了一个随机的_base_seed，这就不是我自己预期的seed了，请问这部分有什么比较好的处理办法能让seed保持我自己设置的？

**Comment by yeliang2258** [comment]
请问具体是什么问题？没有看懂你的问题

**Comment by Birdylx** [comment]
> 请问具体是什么问题？没有看懂你的问题

sorry，更新了下问题。

**Comment by Birdylx** [comment]
> > 请问具体是什么问题？没有看懂你的问题
> 
> sorry，更新了下问题。

简而言之，我需要每个worker的numpy seed保持一致，保证每个样本预处理的随机性一致。

**Comment by parap1uie-s** [comment]
用worker_init_fn参数指定一个func，在func内部设定固定seed

**Comment by heavengate** [comment]
可以用`worker_init_fn`指定

**Comment by Birdylx** [comment]
Thanks~
