### ISSUE TITLE
Paddle库后续开发是否能支持更多版本的boost库，或者有更好方案，兼容其他更多C++库？

### ISSUE THREAD

**Issue by DIPTE** [PaddlePaddle/Paddle#46600]
### 需求描述 Feature Description

<br />**任务目标**：正在做的项目是结合Paddle以及PCL库做算法应用。
<br />**需求场景**：需要Paddle库支持更多版本的boost库，以方便可以编译使用PCL库。**为什么需要用此功能**：需要在代码中加入并使用PCL库做点云处理以及可视化等功能，然而直接将二者放在一起编译会报boost依赖冲突的问题（其中Paddle库为2.3版本，其依赖boost1.41.0版本；而点云处理库PCL库为1.8.1版本，其依赖的boost1.40.0版本；故而联合编译时，在编译编译阶段报错为："-- Could NOT find Boost (missing: chrono) (found suitable version "1.41.0", minimum required is "1.40.0")）"。
<br />**功能描述**：Paddle库支持更多版本的boost库，或者有更好方案（替换boost库？减少一些类似的依赖冲突），兼容其他更多C++库。

**Comment by yeliang2258** [comment]
这个你可以在你的工程里面自己包括一份boost吗？paddle应该是没有支持多个boost版本的计划

**Comment by jzhang533** [comment]
试试用develop的paddle，已经去掉了对boost的依赖。

**Comment by DIPTE** [comment]
> 
尝试了，结果python环境那又报错了
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /home/xx/anaconda3/envs/test/lib/python3.7/site-packages/paddle/fluid/libpaddle.so
......
ImportError: libpython3.7m.so.1.0: cannot open shared object file: No such file or directory

**Comment by yeliang2258** [comment]
先看看libpython3.7m.so.1.0这个库在哪里，然后将路径加入到LD_LIBRARY_PATH中
