### ISSUE TITLE
spectral_norm的 dim参数，文档说明和代码实现是不是矛盾了？

### ISSUE THREAD

**Issue by O-O1024** [PaddlePaddle/Paddle#46602]
from paddle.nn.utils import spectral_norm

文档说对于全连接层必须是dim=0
```it should be set as 0 if Input(Weight) is the weight of fc layer, and should be set as 1 if Input(Weight) is the weight of conv layer.```

但是代码处理 dim=None 时，对于Linear，dim=1
```
if dim is None:
    if isinstance(layer, (Conv1DTranspose, Conv2DTranspose, Conv3DTranspose,
                              Linear)):
            dim = 1
        else:
            dim = 0
```

**Comment by yeliang2258** [comment]
您好，已经反馈给相关同学处理。

**Comment by aizain** [comment]
我明天尝试处理一下~

**Comment by luotao1** [comment]
@jkla139 @aizain 欢迎提一个PR进行修复！
