### ISSUE TITLE
机器翻译如何进行单条推理

### ISSUE THREAD

**Issue by wangpin000** [PaddlePaddle/Paddle#46604]
### 请提出你的问题 Please ask your question

你好，请问如何把paddle训练好的transformer机器翻译模型进行部署？我正在做一个小翻译系统，需要对单条文本进行推理。因为咱们官方提供的inference实际上是批量推理，先把批量的文本存在文件中，然后对该文件进行分词和bpe处理，再把得到的bpe文件加载成data_loader，最后对data_loader进行批量翻译。所以我想问下如何用训练好的paddle翻译模型直接对未经任何处理的单条文本进行翻译？

**Comment by FrostML** [comment]
切词比如使用 [mosesdecoder tokenize](https://github.com/PaddlePaddle/PaddleNLP/pull/3269/files#diff-c91f0429e90e70378520f329c296dd6435f3f236ee44cb0da0f2350ba38bf0a7R30)。Python 对应的 whl 可以参考 `mosestokenizer`。
bpe 可以参考 [fasterBPE](https://github.com/PaddlePaddle/PaddleNLP/pull/3269/files#diff-bf9334fe4d0477f5dbf202d56b054e5afb0d17b0b2e9db70a5b9e8c2e2ff6ac3R264) 代码。
再输入模型即可。
