### ISSUE TITLE
着急着急：控制占卡比例失败

### ISSUE THREAD

**Issue by susu-ai** [PaddlePaddle/Paddle#46609]
### 请提出你的问题 Please ask your question

想起一个服务，为了防止跑一半被其他程序挤掉，想要通过export FLAGS_fraction_of_gpu_memory_to_use=0.7 强制占70%的卡，但是发现最终起的服务并没有占到这么多的卡，不管我如何调至这个参数，最终服务所占的显存都是不变的，请教一下怎么控制我的服务强制占一定比例的卡呀~
如流@董苏慧

**Comment by AndPuQing** [comment]
尝试使用 [FLAGS_initial_gpu_memory_in_mb](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-initial-gpu-memory-in-mb) ?
