### ISSUE TITLE
安装软硬件环境部分 - 关于docker GPU运行的命令更新

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#46614]
## 文档中英文链接

[Linux下的Docker安装](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/docker/linux-docker.html#linux-docker)

[Install on Linux via Docker](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/install/docker/linux-docker_en.html#install-on-linux-via-docker)

新版的docker已经支持直接使用``--gpus all``不再需要额外安装[nvidia-docker](https://github.com/NVIDIA/nvidia-docker)支持

具体方法可以参考[docker官方文档](https://docs.docker.com/engine/reference/commandline/run/#access-an-nvidia-gpu)

### 替代实现 Alternatives

docker run --gpus all --name [Name of container] -it -v $PWD:/paddle <imagename> /bin/bash

需要验证是否兼容才能完成文档修改

**Comment by dingjiaweiww** [comment]
你的反馈我们已收到，待验证后再答复此issue

**Comment by gouzil** [comment]
https://github.com/PaddlePaddle/community/pull/240

**Comment by gouzil** [comment]
#https://github.com/PaddlePaddle/community/pull/240

**Comment by gouzil** [comment]
已添加[pr](https://github.com/PaddlePaddle/community/pull/240), 待验证

**Comment by dingjiaweiww** [comment]
你的方案我们已收到，会尽快回复

**Comment by gouzil** [comment]
docs文档添加[pr](https://github.com/PaddlePaddle/docs/pull/5340)

**Comment by dingjiaweiww** [comment]
pr 已合入，故将此issue 关闭
