### ISSUE TITLE
paddle模型正向和反向的op list 

### ISSUE THREAD

**Issue by duwenzhao** [PaddlePaddle/Paddle#46625]
### 请提出你的问题 Please ask your question

对于paddle模型，有什么方法可以获得模型正向和反向的op list 吗？

**Comment by Caozhou1995** [comment]
静态图方式：print(your_program.ops)

**Comment by Caozhou1995** [comment]
动态图下：export GLOG_vmodule=dygraph_functions=3,nodes=3,tracer=1，跑模型时会打印运行OP的日志。

**Comment by duwenzhao** [comment]
> 使用paddle.enable_static()  动态图转静态图，静态图方式：print(your_program.ops)中的your_program 是什么？

**Comment by Caozhou1995** [comment]
是你转换后的program，可以参考这个链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/static/Program_cn.html#program
