### ISSUE TITLE
OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR

### ISSUE THREAD

**Issue by HarryYuan007** [PaddlePaddle/Paddle#46630]
### 请提出你的问题 Please ask your question

OSError: (External) CUDNN error(4), CUDNN_STATUS_INTERNAL_ERROR. 
  [Hint: 'CUDNN_STATUS_INTERNAL_ERROR'.  An internal cuDNN operation failed.  ] (at /paddle/paddle/fluid/platform/device_context.h:407)

在V100的机器上使用cuda 10.2，cudnn7.6.5和paddle-gpu 2.2.1使用模型预测的时候，发现2个月前能跑起来的模型，现在跑不起来，在本机上尝试了多个这样的环境，均会报错这个问题。代码无改动，模型无改动
在谷歌上检索这个问题，多数认为是cuda和cudnn的版本不对导致的，check后发现均匹配。请帮忙看下

**Comment by Caozhou1995** [comment]
建议尝试使用下官方的docker镜像，https://hub.docker.com/r/paddlepaddle/paddle/tags/?page=1
