### ISSUE TITLE
vs2019 win10 paddle-develop 编译 bug

### ISSUE THREAD

**Issue by perfyperfect** [PaddlePaddle/Paddle#46648]
### bug描述 Describe the Bug

cmake好之后 vs2019打开project，单独编译print_pten_kernels这个项目，失败！error：严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1248	映像大小(902A2000)超过允许的最大大小(80000000)	print_pten_kernels	

### 其他补充信息 Additional Supplementary Information

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1248	映像大小(902A2000)超过允许的最大大小(80000000)	print_pten_kernels

**Comment by zhwesky2010** [comment]
你好，可以在编译时加一个选项：cmake .. -DNEW_RELEASE_PYPI=ON，这样编译的体积可以减小些

**Comment by perfyperfect** [comment]
> 你好，可以在编译时加一个选项：cmake .. -DNEW_RELEASE_PYPI=ON，这样编译的体积可以减小些

开启了这个选项，问题解决了，但是出现而来一个新的问题： 严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1000	Internal error during IMAGE::Pass2	print_pten_kernels 
 \paddle\phi\tools\libphi_static_1.lib(reduce_min_grad_kernel.obj)	1

**Comment by zhwesky2010** [comment]
清理了之前编译的内容吗，重新build试下，如果还不行建议使用ninja编译，`cmake ..  -GNinja -DNEW_RELEASE_PYPI=ON` ，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/install/compile/windows-compile.html#windows
