### ISSUE TITLE
[Bug ] the numpy() method of a sparse coo cuda tensor reports  an error "Segmentation fault (core dumped)"

### ISSUE THREAD

**Issue by OccupyMars2030** [PaddlePaddle/Paddle#46642]
### bug描述 Describe the Bug

You can refer to my [PR](https://github.com/PaddlePaddle/Paddle/pull/46333#issuecomment-1261816827)

我使用了ai studio上的飞桨框架开发功能，编译了develop分支上的代码，安装编译后的wheel包，自己手动试验发现了上述bug。目前我认为是这个bug导致了我的cuda coo forward kernel 的CI测试失败，而我的cpu coo forward kernel 能够通过单测。麻烦请飞桨专家确认这个bug是否存在，谢谢

**Comment by zhwesky2010** [comment]
这个不是bug，SparseTensor本身无法使用.numpy()方式，你需要使用crows、cols、indices先取出其内部的DenseTensor，再调Tensor.numpy()。
这个与你这个kernel的实现是没什么关系的，最多只可能涉及单测的写法。

**Comment by OccupyMars2030** [comment]
收到，谢谢。
