### ISSUE TITLE
dataloader workers exit unexpectedly

### ISSUE THREAD

**Issue by xywlpo** [PaddlePaddle/Paddle#46646]
### 请提出你的问题 Please ask your question

您好，我使用paddle自己写的分类代码，然后由于使用了多个dataloader，因此数据迭代采用下面的方式实现的：
<img width="418" alt="image" src="https://user-images.githubusercontent.com/728405/192982054-1c8bccbd-43af-4d13-b512-d7c5e0b83adc.png">
其中train_loader是多个dataloader的迭代器构成的列表，然后因为每个dataloader对应的数据量都不一样，然后为了保持统一的处理，这里使用.next拿数据，当此次迭代某个迭代器没有数据了，就通过try...Exception，重新初始化该迭代器。
目前程序可以正常运行，但是在都训练好后，会报以下的错误，目前这个是用的单卡训练，num_worker=1，shared_memory=false，训练模型的容器在启动时候加入了共享内存。
![image](https://user-images.githubusercontent.com/728405/192982593-fe7a7988-7b5d-45c6-bf48-3cc99caeafcb.png)
请问这个问题是什么原因？应该怎么修改？非常感谢

**Comment by Caozhou1995** [comment]
麻烦再贴一下train_dataloader的代码逻辑，提供更多的信息帮助定位。
一般来说是封装成一个dataloader，dataloader的接口可以参考官网链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html#dataloader
