### ISSUE TITLE
Weights & Biases Callback for supporting logging to Weights & Biases

### ISSUE THREAD

**Issue by manangoel99** [PaddlePaddle/Paddle#46647]
### 需求描述 Feature Description

In this issue, I am proposing creating a new callback for logging metrics to Weights & Biases. This will be added [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/hapi/callbacks.py) with the rest of the callbacks. I would love to implement this as well!

The added functionality would include logging metrics to a W&B dashboard along with saving model checkpoints as W&B artifacts with only 2 extra lines of code for the users. 

This will give users the ability to track their model training with plots like this

<img width="1427" alt="Screenshot 2022-09-29 at 2 30 13 PM" src="https://user-images.githubusercontent.com/32260633/192988900-fa5f3dc6-d471-41f1-83cf-73e149c70af2.png">

This will be accompanied by being able to track and version saved checkpoints

<img width="1232" alt="Screenshot 2022-09-29 at 2 30 59 PM" src="https://user-images.githubusercontent.com/32260633/192989105-307b6c27-30f5-4f4c-a0dc-fb2351250ba8.png">

W&B also automatically tracks all system metrics during training along with model config for reproducibility.

<img width="1371" alt="Screenshot 2022-09-29 at 2 32 50 PM" src="https://user-images.githubusercontent.com/32260633/192989546-a1da2525-76dd-4b2b-8abd-31d238af04c9.png">

<img width="1358" alt="Screenshot 2022-09-29 at 2 32 28 PM" src="https://user-images.githubusercontent.com/32260633/192989457-fc9ec88b-55f7-4613-8d20-c7cbcf097279.png">

A W&B integration already exists in other libraries supported by PaddlePaddle like [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/utils/loggers/wandb_logger.py) and [PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/ppdet/engine/callbacks.py#L291) along with other popular libraries like MMEngine, MMDetection and more.

Adding this callback will require adding any addition requirements to the paddlepaddle python package either! I would love to hear the mantainers' thoughts on this.

**Comment by Caozhou1995** [comment]
Thank u for your suggestion ! We will reply after discussion！

**Comment by manangoel99** [comment]
Hi @Caozhou1995 ! Any updates?

**Comment by Caozhou1995** [comment]
Hi, sorry to reply u slowly, it was the National Day holiday in 10.1 - 10.7. We will discuss as soon as possible.

**Comment by jzhang533** [comment]
@manangoel99 Please go ahead on adding this new feature to paddlepaddle, and assign @heavengate and @jzhang533 for review when your PR is ready.

Thanks a lot!

**Comment by manangoel99** [comment]
Hi @jzhang533 ! Thanks for giving the thumbs up for this contribution. Could you also guide me to where I can find a guide about how to build the library so that I can test it locally.
I looked through the [docs](https://github.com/PaddlePaddle/docs/tree/develop/docs) here but I can't seem to find the relevant instructions.

**Comment by jzhang533** [comment]
It should be this doc: https://github.com/PaddlePaddle/docs/blob/develop/docs/install/compile/linux-compile_en.md

and if you are using Mac M1 silicon, there is a simple script might be helpful:
https://github.com/jzhang533/Paddle/blob/instructions-on-build-paddle-on-mac-m1/tools/instructions_build_paddle_on_mac.sh
