### ISSUE TITLE
跨层网络配置

### ISSUE THREAD

**Issue by RuijieHou** [PaddlePaddle/Paddle#4665]
跨层网络如何配置，如下，x4跨层连x3,x2,x1
x1 = paddle.layer.fc(input=x, size=1024, act=paddle.activation.Relu())
x2 = paddle.layer.fc(input=x1, size=512, act=paddle.activation.Relu())
x3 = paddle.layer.fc(input=x2, size=256, act=paddle.activation.Relu())
x4 =？

**Comment by hedaoyuan** [comment]
> x4 =？

这个取决于你想实现什么样的计算。从上面配置看起来x1,x2,x3的输出size都是不一样的，所以你本意x4是想获得什么样的计算结果？

**Comment by RuijieHou** [comment]
@hedaoyuan 本意是想x4层除了和x3层全相连外，和x1、x2层也全相连，达到梯度跨层传播的效果

**Comment by hedaoyuan** [comment]
明白你的意思了。首先你要定义x4的输出是多少，然后考虑x3到x4用什么连（直接相连或者也过一个fc），同样，x1，x2也可以通过fc或别的计算再连到x4的输出上。

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
