### ISSUE TITLE
rsample 采样精度

### ISSUE THREAD

**Issue by dasenCoding** [PaddlePaddle/Paddle#46673]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/100328659/193210607-36f99875-d7eb-49e1-9765-26297449f643.png)

请教一下该如何降低 rsample 的误差，现在 rsample 的误差最多在 1.0 左右，太大了。

**Comment by veyron95** [comment]
@dasenCoding 请提供最小复现代码片段，方便复现问题

**Comment by dasenCoding** [comment]
Gumbel ：


    class Gumbel(TransformedDistribution):

          def __init__(self, loc, scale):
              self.batch_size_unknown = False
              self.all_arg_is_float = False
              self.loc = paddle.to_tensor(loc, dtype='float32')
              self.scale = paddle.to_tensor(scale, dtype='float32')
      
              finfo = np.finfo(dtype='float32')
              if isinstance(loc, numbers.Number) and isinstance(scale, numbers.Number):
                  base_dist = Uniform(float(finfo.tiny), float(1 - finfo.eps))
              else:
                  base_dist = Uniform(paddle.full_like(self.loc, float(finfo.tiny)),
                                      paddle.full_like(self.loc, float(1 - finfo.eps)))
      
              super(Uniform, base_dist).__init__(self.loc.shape)
              self.transforms = [ExpTransform(),
                                 AffineTransform(loc=paddle.to_tensor(0,dtype='float32'), scale=-paddle.ones_like(self.scale)),
                                 ExpTransform(),
                                 AffineTransform(loc=self.loc, scale=-self.scale)]
              super(Gumbel, self).__init__(base_dist, self.transforms)

          def sample(self, shape=[]):
              x = self._base.sample(shape)
              for t in self._transforms:
                  x = t.forward(x)
              return x



test 类：


    @parameterize.place(config.DEVICES)
    @parameterize.parameterize_cls(
        (parameterize.TEST_CASE_NAME, 'loc', 'scale'), [
        ('one-dim', parameterize.xrand((4, )),parameterize.xrand((4, ))),
        ('multi-dim', parameterize.xrand((5, 3)),parameterize.xrand((5, 3))),
        ])
    class TestGumbel(unittest.TestCase):
    
        def setUp(self):
            self._dist = Gumbel(loc=paddle.to_tensor(self.loc,dtype='float32'),
                                                     scale=paddle.to_tensor(\
                                                         self.scale,dtype='float32'))



        def test_sample(self):
  
          sample_shape = [10000]
          samples = self._dist.sample(sample_shape)
          samples = np.array(samples.numpy(),dtype=np.float64)
          sample_values = samples
          self.assertEqual(samples.dtype, self.scale.dtype)
  
          # There is a loss of accuracy in this conversion.
          tolerance = 1e-3
  
          np.testing.assert_allclose(sample_values.mean(axis=0),
                                     scipy.stats.gumbel_r.mean(self.loc,scale=self.scale),
                                     rtol=tolerance,
                                     atol=tolerance)
          np.testing.assert_allclose(sample_values.var(axis=0),
                                     scipy.stats.gumbel_r.var(self.loc,scale=self.scale),
                                     rtol=tolerance,
                                     atol=tolerance)



麻烦您给看下， @veyron95

**Comment by cxxly** [comment]
这个PR #46255 遇到问题吧

**Comment by cxxly** [comment]
这个issue先close，我们在 #46255 讨论

**Comment by dasenCoding** [comment]
好的。
