### ISSUE TITLE
模型在mpi集群上训练后回传到hdfs上的问题

### ISSUE THREAD

**Issue by zjgtan** [PaddlePaddle/Paddle#4670]
背景
模型训练完成后，需要将每个pass保存的结果返回。

问题
训练五轮后，从workspace的目录看，./output/model_params路径下有五个模型，但是最终HDFS上只有dssm_pass_00004.tar，下面是截图
![image](https://user-images.githubusercontent.com/4132906/31372218-54ad658e-ad5a-11e7-9cee-fe887c848218.png)

**Comment by luotao1** [comment]
第一轮是00000.tar，00004.tar是第五轮。

**Comment by zjgtan** [comment]
移目录的代码
![image](https://user-images.githubusercontent.com/4132906/31372260-83d23eb6-ad5a-11e7-8967-8f96d79a89a9.png)

**Comment by zjgtan** [comment]
恩恩，我理解应该会全部返回到hdfs上才对

**Comment by luotao1** [comment]
从代码上看，是从model_params移到output/model_params？output/model_params下不是已经有5个了么？

**Comment by hedaoyuan** [comment]
@zjgtan ./output/model_params下面有5个文件，所以看起来你贴的那段代码是正确执行了？

**Comment by zjgtan** [comment]
对的，但奇怪的是hdfs上只有一个哈，我也很纳闷啊****

**Comment by hedaoyuan** [comment]
hdfs上是什么样子的？看一下模型上传hdfs的逻辑？

**Comment by zjgtan** [comment]
![image](https://user-images.githubusercontent.com/4132906/31372692-a07d99dc-ad5c-11e7-9e9b-0df68e6aa5ec.png)

**Comment by zjgtan** [comment]
上传hdfs用啥参数控制？

**Comment by hedaoyuan** [comment]
可能传的是./model_params下面的内容，你把那个mv语句去掉试试？

**Comment by zjgtan** [comment]
好滴

**Comment by zjgtan** [comment]
实验了，去掉mv语句，hdfs的output下就没有数据了
