### ISSUE TITLE
PaddlePaddle Nvidia NGC容器支持Arm架构CPU

### ISSUE THREAD

**Issue by niconical** [PaddlePaddle/Paddle#46749]
### 需求描述 Feature Description

感谢PaddlePaddle提供NGC容器化安装的方式，其极大的简化了异构设备的安装工作。但是，目前PaddlePaddle的NGC容器只支持x86架构的CPU，而Pytorch和Tensorflow同时支持x86, Arm SBSA。希望PaddlePaddle NGC 镜像可以同时支持ARM和X86架构CPU，感谢。

Ref
- https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html

**Comment by From00** [comment]
你好，你的需求我们已经收到，会在国庆假期结束后安排NGC相关负责同学进行讨论和评估。

**Comment by niconical** [comment]
> 你好，你的需求我们已经收到，会在国庆假期结束后安排NGC相关负责同学进行讨论和评估。

非常感谢，请问有相关SIG或者社区吗，我对PaddlePaddle NGC相关工作也非常感兴趣，希望可以给社区做一点贡献。

**Comment by dingjiaweiww** [comment]
@niconical 请问你用的哪个版本NGC 容器呢

**Comment by niconical** [comment]
> @niconical 请问你用的哪个版本NGC 容器呢

我使用的这个镜像 nvcr.io/nvidia/paddlepaddle:22.09-py3，以下是两张官网截图。我不太清楚如何查看NGC容器版本，因为这里显示nvcr.io/nvidia/paddlepaddle:xx.xx-py3都是只支持amd64架构的。

![image](https://user-images.githubusercontent.com/23325508/194710654-f4e74d4a-67b3-4ea1-b7c7-51731109133e.png)
![image](https://user-images.githubusercontent.com/23325508/194710673-445314cd-cc4b-4474-be0f-b56de12ef0a6.png)

Ref
1. https://docs.nvidia.com/deeplearning/frameworks/support-matrix/index.html#framework-matrix-2020
2. https://catalog.ngc.nvidia.com/orgs/nvidia/containers/paddlepaddle

**Comment by onecatcn** [comment]
@niconical 感谢对NGC飞桨容器的支持。目前，NGC飞桨容器确实还不支持SBSA，诉求已经收到，我们会努力推进。
我们有一个NGC用户微信群，里面有飞桨和NV的工程师与用户沟通，欢迎加入：
![image](https://user-images.githubusercontent.com/28726337/194739422-913c1906-b6d5-4e3e-954d-787b2a6c1484.png)
