### ISSUE TITLE
PR-CI-Coverage: Makefile:140: recipe for target 'all' failed

### ISSUE THREAD

**Issue by PureNatural** [PaddlePaddle/Paddle#46750]
您好，我不太清楚是什么样的原因会导致下面的错误，导致CI无法通过
![image](https://user-images.githubusercontent.com/29674550/194028000-131fc8e0-8e00-4086-8180-0acf51b094f5.png)

**Comment by From00** [comment]
你好，这个错误为Paddle编译失败，但从你提供的截图无法分析出编译失败的具体原因。建议尝试重新执行失败的CI，若仍无法通过，请提供具体的PR或CI任务链接，我们帮助排查和解决。

**Comment by PureNatural** [comment]
> 你好，这个错误为Paddle编译失败，但从你提供的截图无法分析出编译失败的具体原因。建议尝试重新执行失败的CI，若仍无法通过，请提供具体的PR或CI任务链接，我们帮助排查和解决。

感谢您的回复，我多尝试了几次后编译通过了。
