### ISSUE TITLE
PR-CI-Windows-Inference和PR-CI-Windows这两项CI一直处于排队中

### ISSUE THREAD

**Issue by PureNatural** [PaddlePaddle/Paddle#46764]
### 请提出你的问题 Please ask your question

您好，我提交了一个PR，在CI检查中PR-CI-Windows-Inference和PR-CI-Windows这两项一直处于排队中，我发现排队的项目也有很多，请问有解决的方式吗
https://github.com/PaddlePaddle/Paddle/pull/46255

**Comment by Aganlengzi** [comment]
你好，CI是自动排队运行的，需要等待前序执行完成，如果CI流水线本身有问题会有相关维护同学解决；另外我看PR中有未通过的Required的CI，如果可以的话建议先解决。

**Comment by PureNatural** [comment]
感谢您的回复。
