### ISSUE TITLE
paddle安装后无法import

### ISSUE THREAD

**Issue by blingblingxxy** [PaddlePaddle/Paddle#46778]
### 问题描述 Issue Description

pip显示安装成功但import后报错，但机器上显示文件存在。
<img width="842" alt="截屏2022-10-08 下午5 12 02" src="https://user-images.githubusercontent.com/57892938/194699856-06bb3ad0-01de-4d5e-b4c3-0f03e0d05f07.png">
<img width="504" alt="截屏2022-10-08 下午5 13 25" src="https://user-images.githubusercontent.com/57892938/194699902-c73ff94f-2f75-44fa-b081-8a9d973cc316.png">

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: CentOS Linux 7
Python version: 3.7.6

CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by dingjiaweiww** [comment]
你安装的是什么哪个版本的paddle 呀，或者你的安装命令是什么？
