### ISSUE TITLE
关于 paddle.distributed.spwan

### ISSUE THREAD

**Issue by zsy0828** [PaddlePaddle/Paddle#46788]
### 请提出你的问题 Please ask your question

在使用spwan进行分布式训练时，如何像torch的multiprocessing中，使用自定义类，如torch-quiver中会增加reductions中的ForkingPickler.register来实现进程的通信。因为我在尝试使用paddle的使用的时候，它会自动的帮助我实现进程通信，但这并不是我需要的，我应该如何处理呢，同时，我还发现，在ubuntu1804，双1080ti，nvcc10.2的服务器上，使用paddle的dist时候，显卡的占用率会很低，基本在25~30，而torch是几乎吃满，这个是paddle自身的原因么 ，因为我处理的部分使用的是cupy，pd只是后续使用from_dlpack，在不使用from_dlpack时，也会很慢

**Comment by seemingwang** [comment]
目前paddle没有提供自定义通信的接口，不过可以通过
以下链接上面的方法来自己实现多卡间的通信。
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/distributed/all_reduce_cn.html#all-reduce

**Comment by zsy0828** [comment]
> 目前paddle没有提供自定义通信的接口，不过可以通过 以下链接上面的方法来自己实现多卡间的通信。 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/distributed/all_reduce_cn.html#all-reduce

你好，我大概看了一下，paddle的，好像spwan直接用的是torch的.......

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/incubate/multiprocessing

paddle也实现了  multiprocessing 在多进程之间传输 tensor

spawn 分布式训练的话，也是nccl通信
