### ISSUE TITLE
基于 华为昇腾 NPU 的推理部署

### ISSUE THREAD

**Issue by trefoil0219** [PaddlePaddle/Paddle#46807]
### 请提出你的问题 Please ask your question

![5c1d9d8c392b93e79e30a1abd928de6](https://user-images.githubusercontent.com/55016894/194744151-56c6a56b-e04a-4259-b2d8-52da028ea8bc.png)
在编译的时候，下载第三方依赖有没有替代从github上下载的方法，或者另外解决的办法

**Comment by hong19860320** [comment]
如果没有训练的需求，只进行推理部署的话，可以尝试使用 Paddle Lite https://www.paddlepaddle.org.cn/lite/develop/demo_guides/huawei_ascend_npu.html
