### ISSUE TITLE
将paddle2的模型转换成paddle1

### ISSUE THREAD

**Issue by ggbond3** [PaddlePaddle/Paddle#46809]
### 请提出你的问题 Please ask your question

在使用K210部署paddle时，AIstudio案例是paddle1.8的模型转化成kdmodel。现已经使用paddle2.3和paddleslim生成模型，但无法转换成kdmodel，现在想要将其转化成1.8下fluid.io生成的模型再转换成kdmodel,应该怎么转。

**Comment by ceci3** [comment]
可以直接使用paddle.static.load_inference_model 把模型加载进来，然后在使用 paddle.fluid.io.save_inference_model  （https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_inference_model_cn.html#save-inference-model）接口保存成paddle1.8下的模型，再按照正常转kdmodel的流程就可以了

**Comment by ggbond3** [comment]
> paddle.static.load_inference_model

  也就说可以使用paddle1.8 的paddle.static.load_inference_model 可以加载paddle2版本生成的静态图文件

**Comment by ggbond3** [comment]
看了一下官方文档，1.8的paddle不能读2.3的模型啊

**Comment by zkh2016** [comment]
试下用2.3的load_inference_model把模型加载进来，然后使用1.8的save_inference_model接口保存下来？

**Comment by ceci3** [comment]
> 试下用2.3的load_inference_model把模型加载进来，然后使用1.8的save_inference_model接口保存下来？

是的

**Comment by ggbond3** [comment]
> > 试下用2.3的load_inference_model把模型加载进来，然后使用1.8的save_inference_model接口保存下来？
> 
> 是的

这怎么做到在一个环境里装两个paddle版本？

**Comment by zkh2016** [comment]
> > > 试下用2.3的load_inference_model把模型加载进来，然后使用1.8的save_inference_model接口保存下来？
> > 
> > 
> > 是的
> 
> 这怎么做到在一个环境里装两个paddle版本？

哈喽，确认下你2.3使用的是哪个save接口不能转成kdmodel的。 @ceci3 的意思是使用2.3的paddle就行，这个[save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_inference_model_cn.html#save-inference-model) 接口是保留1.8版本的，可以用这个接口来保存模型。

**Comment by ggbond3** [comment]
> > > > 试下用2.3的load_inference_model把模型加载进来，然后使用1.8的save_inference_model接口保存下来？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 这怎么做到在一个环境里装两个paddle版本？
> 
> 哈喽，确认下你2.3使用的是哪个save接口不能转成kdmodel的。 @ceci3 的意思是使用2.3的paddle就行，这个[save_inference_model](https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_inference_model_cn.html#save-inference-model) 接口是保留1.8版本的，可以用这个接口来保存模型。

谢谢，已经保存成功了

**Comment by zkh2016** [comment]
好的
