### ISSUE TITLE
Batch Matrix Mul Operator.

### ISSUE THREAD

**Issue by mkliegl** [PaddlePaddle/Paddle#4683]
```txt
Input X: [C, M, K]
Input Y: [C, K, N]
Output Z: [C, M, N] 
```

**Comment by hedaoyuan** [comment]
Will this Batch Matrix Mul Operator implement the CPU version?

**Comment by mkliegl** [comment]
Good question. From some initial searches:
- For GPU, cuBLAS has gemmBatched: https://devblogs.nvidia.com/parallelforall/cublas-strided-batched-matrix-multiply/
- Intel MKL has {s,d}gemm_batch: https://software.intel.com/en-us/mkl-developer-reference-c-cblas-gemm-batch

So I think I will just wrap those. For the general CPU case (with no Intel MKL), maybe for now we can just loop over the batch dimension. What do you think, @hedaoyuan ?

**Comment by hedaoyuan** [comment]
That is great.

**Comment by zhouxiao-coder** [comment]
I think both operations (the 3-d * 3-d version and 3-d * 2-d version) can be implemented as a special case of a general `matmul` operator. 
Quote from `numpy` document：
'''
The behavior depends on the arguments in the following way.

If both arguments are 2-D they are multiplied like conventional matrices.
If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.
'''

**Comment by mkliegl** [comment]
Good idea - numpy.matmul is a nice design. I'll try to implement the same cases (or at least some subset for now).

**Comment by mkliegl** [comment]
@zhouxiao-coder @hedaoyuan Please see initial PR #4856 .
