### ISSUE TITLE
[CodeStyle] Legacy python code cleanup tracking issue

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#46837]
## 项目说明

用于跟踪 Call-for-Contributions: [Python 2.7 相关代码退场](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style/legacy_python2.md) 及 [Python 3.5/3.6 相关代码退场
](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style/legacy_python36minus.md) 各个任务的计划和进度

### ✅ Python 2.7 退场（8/8）

| 子任务 | 具体内容和完成时间|相关 PR | 修复行数  | 作者 |
|-|-|-|-|-|
| ✅ 1. 删除python2子包| ✅ 1.1 移除 `__future__` import（2022/09/28）| #46411, #46463, #46466, #46736 | 3613  | [SigureMo](https://github.com/SigureMo), [Yulv-git](https://github.com/Yulv-git)|
|| ✅ 1.2 移除`six`（2022/11/01）| #46965, #47334 | 906 | [SigureMo](https://github.com/SigureMo) |
| ✅ 2. 删除没有其它功能的 Python 2 模块 | ✅ 2.1 移除 类中不必要的显式 `object` 继承（2022/11/08）| #47642 #47730 | 524 | [SigureMo](https://github.com/SigureMo) |
|| ✅ 2.2 移除 `super()` 函数中不必要的参数（2022/11/22）| #47549, #47643 | 1900 | [SigureMo](https://github.com/SigureMo) |
|| ✅ 2.3 移除 `compat.py` 文件（2022/10/25）| #46686, #46923, #47035, #47036, #47097, #47269 | 836 | [SigureMo](https://github.com/SigureMo) |
| ✅ 3. 清理 Python2 相关逻辑分支 | ✅ 3. 清理 Python2 相关逻辑分支（2022/10/11）| #46696 | 92 | [caolonghao](https://github.com/caolonghao) |
| ✅ 4. 删除非必要的环境依赖（Python2）| ✅ 4. 删除非必要的环境依赖（Python2）(2023/01/03）| #48685 | 51 | [SigureMo](https://github.com/SigureMo) |
| ✅ 5. 清理文档中涉及 Python 2 的内容 | ✅ 5. 清理文档中涉及 Python 2 的内容（2022/12/01）|  [docs#5466](https://github.com/PaddlePaddle/docs/pull/5466)  | 125 | [caolonghao](https://github.com/caolonghao) |

### Python 3.5/3.6 退场（3/3）

| 子任务和完成时间 |  相关PR | 修复行数  | 作者 |
|-|-|-|-|
| ✅ 1. 清理低于 Python 3.7 相关逻辑分支（2022/11/29）| #48426, #48540 | 78 | [gsq7474741](https://github.com/gsq7474741) |
| ✅ 2. 删除非必要的环境依赖（Python 3.5/3.6）（2023/2/6）| #49558 | 125 | [gsq7474741](https://github.com/gsq7474741) |
| ✅ 3. 清理文档中涉及 Python 3.5/3.6 的内容（2022/12/01）| [docs#5460](https://github.com/PaddlePaddle/docs/pull/5460) | 65 | [gsq7474741](https://github.com/gsq7474741) | 

## 其他成果总结

| 子任务和完成时间|相关 PR | 修复行数  | 作者 |
|-|-|-|-|
| ✅ 1. 使用 `open` 替换 `io.open`（2022/10/11）| #46751 | 18  | [SigureMo](https://github.com/SigureMo) |
| ✅ 2. 清理为兼容 Python2 而增加的 `next` 方法（2022/11/08）| #47728 | 17  | [SigureMo](https://github.com/SigureMo) |
| ✅ 3. 替换 metaclass 旧的声明语法（2022/11/09）| #47730 | 6  | [SigureMo](https://github.com/SigureMo) |
| ✅ 4. 移除字符串字面量无用的 u 前缀（2022/11/09）| #47727 | 64  | [SigureMo](https://github.com/SigureMo) |
| ✅ 5. 使用 `inspect.getfullargspec` 替换 `inspect.getargspec`（2022/11/22）| #48218 | 43  | [SigureMo](https://github.com/SigureMo) |
| ✅ 6. 移除 DeprecationWarning filter（2022/12/05）| #48639 | 8  | [gsq7474741](https://github.com/gsq7474741) |
| ✅ 7. 更新 PyPI README 文档 （2022/12/28）| #48640 | 42 | [gsq7474741](https://github.com/gsq7474741) |
| ✅ 8. 清理弃用的 `typing.Text`（2023/01/04）| #49506 | 6 | [SigureMo](https://github.com/SigureMo) |
| ✅ 9. 清理低于 Python 3.7 的依赖项、更新 `setup.py` classifiers 字段（2023/01/04）| #49516 | 10 | [gsq7474741](https://github.com/gsq7474741) |

> **Note**
>
> 这里仅统计已经完成的项目，部分正在进行/将要进行的见下面 Comment，如有遗漏，可在下面直接回复或者在该 PR 里 @SigureMo 一下～

**Comment by SigureMo** [comment]
## Python2、Python3.5、Python3.6 遗留代码退场计划各个子任务的计划和进度

### ✅ remove future imports <sup>[py2]</sup>

- 存量修复
   - 全部 Python 代码（除 test_error.py）：#46411
   - test_error.py、test_origin_info.py（含 yapf 格式化、remove-future-import）：#46463
   - `spawn.py` 的 docstring 里：#46890
- 增量阻止
   - CI：#46466
- 增量修复
   - #46736

### ✅ Python2 条件分支 <sup>[py2]</sup>

- 存量修复：#46696

### ✅ 使用 `open` 替换 `io.open` <sup>[py2]</sup>

- 存量修复：#46751

### ✅ 移除 `paddle.compat` 模块 <sup>[py2]</sup>

- 存量修复
   - long_type, int_type, get_exception_message, floor_division: #46686
   - round: #46923
   - to_bytes: #47035
   - to_text: #47036
   - 问题修复: #47097
   - 模块文件清理: #47269

### ✅ 删除第三方包 `six` 的使用及依赖 <sup>[py2]</sup>

- 存量修复
    - #46965
    - #47334

### ✅ 清理显式继承 object <sup>[py2]</sup>

- 存量修复 #47642
- 增量修复
    - TODO
- 增量控制方案（待确定）

### ✅ 清理 `super()` 继承时不必要的参数 <sup>[py2]</sup>

- 存量修复
    - #47549
    - 部分示例代码中的：#47643
- 增量修复
    - TODO
- 增量控制方案（同上）

### ✅ 替换 `__metaclass__` 的元类声明方式 <sup>[py2]</sup>

- 存量修复 #47730

### ✅ 清理 u 前缀的字符串 <sup>[py2]</sup>

- 存量修复 #47727

### ✅ 清理 Python2 next 方法 <sup>[py2]</sup>

- 存量修复 #47728

### ✅ 使用 `inspect.getfullargspec` 替换 `inspect.getargspec` <sup>[py2]</sup>

- 存量修复 #48218

### ✅ 低于 Python 3.7 条件分支清理 <sup>[py36-]</sup>

- 存量修复
    - #48426
    - #48540

### ✅ 移除 DeprecationWarning filter <sup>[py36-]</sup>

- 存量修复 #48218

### ✅ 移除为 Python 3.2-3.6 做的 DeprecationWarning 兼容性处理 <sup>[py36-]</sup>

- 存量修复 #48639

### ✅ 清理不必要的 Python2 相关注释 <sup>[py2]</sup>

- #49135

### ✅ 更新 PyPI README 文档 <sup>[py36-]</sup>

- #48640

### ✅ 清理 Docker 镜像中不必要的 python2 安装 <sup>[py2]</sup>

- #48685

### ✅ 清理低于 Python 3.7 的依赖项、更新 `setup.py` classifiers 字段 <sup>[py36-]</sup>

- #49516 

### ✅ 清理弃用的 `typing.Text` <sup>[py36-]</sup>

- #49506

### ✅ 清理弃用的 unittest 的 aliases <sup>[py36-]</sup>

- #49522

### ✅ 清理 Docker 镜像中不必要的 python 3.5/3.6 安装 <sup>[py36-]</sup>

- #49558
- #48490

### 清理文档中的相关使用

- python2: PaddlePaddle/docs#5466
- python 3.5、3.6: PaddlePaddle/docs#5460
- `six`, `__future__` imports: https://github.com/PaddlePaddle/docs/pull/5352
- `paddle.compat` 模块文档清理: https://github.com/PaddlePaddle/docs/pull/5376
- 清理显式继承 object 和清理 `super()` 继承时不必要的参数：PaddlePaddle/docs#5410
- TODO...

### 其他...

TODO...

**Comment by YvoCup** [comment]
@SigureMo 您好，我想做任务2.2移除super()函数中不必要的参数

**Comment by SigureMo** [comment]
> @SigureMo 您好，我想做任务2.2移除super()函数中不必要的参数

emmm，这个的话其实已经基本上做完了，上面的 comment 记录了详情（不是最上面那个），剩下几个在示例代码中的在 #47643 修改了还没合入，此外就只有几个增量了～

感兴趣可以移除下增量，以及 Markdown 里还有一些没有移除的，「清理显式继承 object」也有一些可以一起完成（剩余的很少，总计估计也就 10～20 个吧）

**Comment by YvoCup** [comment]
哦好的，那我看看其他合适些的代码
