### ISSUE TITLE
如何在一台机器上运行俩个分布式训练任务？

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#46875]
### 请提出你的问题 Please ask your question

现在有四机32卡，想要跑2个paddledetection任务，但是当运行第二个任务的时候，第一个任务会卡住，log信息如下，并且第二个任务也启动不起来。

请问该怎么解决呢？

<img width="1144" alt="image" src="https://user-images.githubusercontent.com/31760851/194978979-16ebeda9-e53e-41c1-87ed-1576c39ad4f3.png">

**Comment by jerrywgz** [comment]
请问在单机下运行两个ppdet任务是否正常呢
