### ISSUE TITLE
A100上在cuda11.1环境下pip安装的paddlepaddle-gpu==2.3.2使用推理tools/infer.py，加载数据到Tensor像素值异常

### ISSUE THREAD

**Issue by qianhang1994** [PaddlePaddle/Paddle#46882]
### 环境
ubuntu18.04, A100，anaconda python3.8，cuda11.1(自行安装)，paddlepaddle-gpu==2.3.2（pip安装）

### 问题
运行下面脚本，没有检测结果，debug看到图片加载dataset+transform正常（numpy），加载完毕loader转batch到Tensor上之后所有像素值都为固定值0.461，这个Tensor再转回numpy还是正常的（均值95.+）
![ba9d2aff7b33faf6850ead3cc](https://user-images.githubusercontent.com/31030676/194990062-c3941c2c-49fe-4528-94d7-bc71beee6b73.png)

### 其他
换环境自带paddlepaddle-gpu==2.3.0.post110是可以正常的，但是上面这个有点奇怪

**Comment by wuyefeilin** [comment]
self.inputs["image"].astype('float32').mean()看看是否正常哈

**Comment by qianhang1994** [comment]
> self.inputs["image"].astype('float32').mean()看看是否正常哈
@wuyefeilin 抱歉处理些事情没及时看回复

这样输入仍然是错误的
![infoflow 2022-10-17 17-31-33](https://user-images.githubusercontent.com/31030676/196143071-fa04e5d8-5aba-4f62-935a-81a6f296bb68.png)
并且如果不是print，直接在debug console多次执行这句话，结果每次都不一样：
![infoflow 2022-10-17 17-33-26](https://user-images.githubusercontent.com/31030676/196143314-6c9f83f9-a0f3-4d9f-8262-64be7e0f353c.png)

应该是pip自动安装的paddle版本问题吧？
paddlepaddle_gpu-2.3.2-cp37-cp37m-manylinux1_x86_64.whl
Name: paddlepaddle-gpu
Version: 2.3.2
Summary: Parallel Distributed Deep Learning

最后我去官网直接下载了post111的paddle就正常了
paddlepaddle_gpu-2.2.2.post111-cp38-cp38-linux_x86_64.whl
