### ISSUE TITLE
使用paddle进行半监督训练，遇到问题

### ISSUE THREAD

**Issue by wjm202** [PaddlePaddle/Paddle#46903]
### 请提出你的问题 Please ask your question

在使用paddledetection复现半监督论文Denseteacher中使用多卡训练报错，截图如下：
![816873e5d60cf19ef4afe2109794b1a2](https://user-images.githubusercontent.com/97875990/195045179-2df6f11e-b7ab-450d-9c5d-bd1e15fddb5f.png)
所建立的半监督模型里面内容如下：建立model，model中存在student，teacher两种基础模型，类似知识蒸馏（我使用的是fcos）
teacher模型不进行反向传播，student进行反向传播，teacher设置为eval（），student设置为train（）以下是我的多卡设置代码截图：
![92bf27ba17dba5e252236b69ce27d8ac](https://user-images.githubusercontent.com/97875990/195045973-e1b4455c-aa70-4693-8880-8879847da5c6.png)
![55576ccd5a1b3ebb9f3fde4a0518d066](https://user-images.githubusercontent.com/97875990/195046071-2255eef4-5733-4a55-a3c3-dcfe150a1d78.png)

**Comment by wuyefeilin** [comment]
请问一下，单卡条件下正常吗

**Comment by wjm202** [comment]
正常的

**Comment by wjm202** [comment]
补充信息
![653ae67ac7fd672d8aeab07ad622a44f](https://user-images.githubusercontent.com/97875990/195050958-727fc269-5123-4e2c-bd4d-9429f0028bdb.png)
cuda版本10.1
python 3.8.8

**Comment by wjm202** [comment]
单卡能训练，不过单卡训练时epoch输出是乱的，不知道问题出在哪

![1efa29fc271e4c7fc2a69b0bf4f6b033](https://user-images.githubusercontent.com/97875990/195051915-44ddad73-47ac-48cf-a4b3-75ceb5dee101.png)
