### ISSUE TITLE
使用Docker安装后，jupyter的用户名是什么？

### ISSUE THREAD

**Issue by Z-fly** [PaddlePaddle/Paddle#46931]
使用命令 docker run -p 80:80 --rm --env USER_PASSWD="password you set" -v $PWD:/home/paddle registry.baidubce.com/paddlepaddle/paddle:2.3.2-jupyter

**Comment by Z-fly** [comment]
默认用户名是jovyan，建议在这里注明
![image](https://user-images.githubusercontent.com/10470892/195265597-94c74a2d-e257-4beb-9944-690ccaf254b3.png)

**Comment by seemingwang** [comment]
使用paddle用户名也可以，挂载到容器目录 /home/paddle
