### ISSUE TITLE
Rename graph.py into framework.py ?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4693]
It seems that Python classes defined in https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/graph.py, namely,

- Variable
- Operator
- Block
- Program 

generally corresponds to protobuf messages defined in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/framework.proto.

Should we rename graph.py into framework.py?

**Comment by reyoung** [comment]
Cool! We will change it after merging a PR of @Canpio
