### ISSUE TITLE
请求PP-HumanSeg用大数据集+连通性loss实现视频会议下的高效人像分割的公开数据集14117数据集

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/Paddle#46930]
### 问题描述 Please describe your issue

您好，我怀着崇敬的心态，阅读了一篇咱们公司的论文，论文为PP-HumanSeg: Connectivity-Aware Portrait Segmentation with a Large-Scale Teleconferencing Video Dataset
想要学习复现该网络，看到有公开数据集，但是需要请求，所以特地来请求一下，能够将数据集发我一下，下载链接也可以。我的邮箱是2927786428@qq.com，万分感谢

**Comment by juncaipeng** [comment]
感谢你的关注，我会发送下载链接到你的邮箱。 更多信息，可以参考：https://github.com/PaddlePaddle/PaddleSeg/tree/release/2.6/contrib/PP-HumanSeg
