### ISSUE TITLE
Paddle Inference 网站链接失效

### ISSUE THREAD

**Issue by felixhao28** [PaddlePaddle/Paddle#46936]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/infer/inference/inference_cn.html

这个页面的两个链接

点此 [安装与编译Linux预测库](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html)

点此 [安装与编译Windows预测库](https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html#windows)

![image](https://user-images.githubusercontent.com/2417391/195271920-a5ee75f5-620c-4d4a-acc7-8b8b8a107077.png)

失效了

**Comment by jiweibo** [comment]
感谢您的反馈，您可以先通过该入口访问Inference文档，我们后续pr修复下失效链接。
https://www.paddlepaddle.org.cn/inference/v2.4/guides/introduction/index_intro.html
