### ISSUE TITLE
官网的使用指南-参数服务器-纯GPU参数服务器：给出的示例代码运行报错

### ISSUE THREAD

**Issue by Eddie-zhg** [PaddlePaddle/Paddle#46945]
### 问题描述 Please describe your issue

[纯GPU参数服务器给出的示例链接](https://github.com/PaddlePaddle/PaddleFleetX/tree/old_develop/examples/wide_and_deep_gpups)
**train.py里面会出现下图所示的问题：**
![微信图片_20221012194235](https://user-images.githubusercontent.com/82798516/195333958-4a69c550-4267-46b9-9e2d-1240d24c898f.jpg)

-  Paddle是PaddlePaddle develop GPU版本 cuda11.2

**Comment by seemingwang** [comment]
使用gpups的时候，cmake编译需要开启 -DWITH_HETERPS=ON 选项

**Comment by Eddie-zhg** [comment]
> 使用gpups的时候，cmake编译需要开启 -DWITH_HETERPS=ON 选项

您好，我不太明白如何开启 -DWITH_HETERPS=ON 选项。我应该怎么找到这个地方并开启它呢？

**Comment by seemingwang** [comment]
> > 使用gpups的时候，cmake编译需要开启 -DWITH_HETERPS=ON 选项
> 
> 您好，我不太明白如何开启 -DWITH_HETERPS=ON 选项。我应该怎么找到这个地方并开启它呢？

是这样的，官方提供的whl包，是不支持GPU参数服务器训练的。需要自己进行cmake编译，然后再安装whl包

https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
可以参考这里，
到第9步时候，在cmake后面加上 -DWITH_HETERPS=ON 这个参数

**Comment by seemingwang** [comment]
cmake ..  -DWITH_DISTRIBUTE=ON -DPY_VERSION=3.7 -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_HETERPS=ON -DWITH_GLOO=ON -DWITH_FLUID_ONLY=ON
可以参考这个例子，把python版本换成自己的
