### ISSUE TITLE
使用tensor做为tensor索引出现问题

### ISSUE THREAD

**Issue by xiehuanyi** [PaddlePaddle/Paddle#46954]
### bug描述 Describe the Bug

我在复现Informer模型的时候遇到tensor索引问题，代码如下：
```python
    b, h, l_q, d = q.shape
    _, _, l_k, _ = k.shape

    # calculate the sampled Q_K
    k_expand = k.unsqueeze(-3).expand((b, h, l_q, l_k, d))  # shape [1, 1, 32, 34, 2]
    index_sample = paddle.to_tensor(np.random.choice(l_k, size=(l_q, sample_k)), dtype='int64')  # [32, 20]
    axis2 = paddle.arange(l_q).unsqueeze(1)  # [32, 1]

    k_sample = k_expand[:, :, axis2, index_sample, :]
```
出现如下报错：
```shell
Traceback (most recent call last):
  File "/Users/xiehuanyi/PycharmProjects/DL/src/Transformer/informer.py", line 22, in <module>
    main()
  File "/Users/xiehuanyi/PycharmProjects/DL/src/Transformer/informer.py", line 18, in main
    print(feat1[index, :, :, :, :])
  File "/Users/xiehuanyi/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 736, in __getitem__
    return _getitem_impl_(self, item)
  File "/Users/xiehuanyi/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/variable_index.py", line 455, in _getitem_impl_
    raise IndexError(
IndexError: Valid index accept int or slice or ellipsis or list, but received [Tensor(shape=[4], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1, 0, 0, 1]), slice(None, None, None), slice(None, None, None), slice(None, None, None), slice(None, None, None)].
Tensor(shape=[2, 2, 2, 2, 4], dtype=int64, place=Place(cpu), stop_gradient=True,
       [[[[[1, 0, 0, 2],
           [2, 1, 0, 2]],

          [[0, 1, 2, 2],
           [0, 2, 2, 2]]],


         [[[1, 0, 0, 0],
           [1, 0, 1, 1]],

          [[0, 1, 2, 2],
           [1, 2, 1, 1]]]],



        [[[[0, 2, 1, 2],
           [2, 1, 2, 0]],

          [[1, 2, 1, 2],
           [2, 0, 2, 2]]],


         [[[1, 0, 1, 0],
           [1, 0, 2, 1]],

          [[1, 0, 0, 0],
           [1, 0, 0, 0]]]]])
Tensor(shape=[4], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1, 0, 0, 1])

进程已结束,退出代码1
```
相同的用法在pytorch中是可以使用的，如果想在paddle中实现相同效果，应该如何操作？

**Comment by seemingwang** [comment]
您好，可否提供一段简单的可运行的代码帮忙我们复现问题呢。 看出错提示，报错的语句并没有提供出来

**Comment by xiehuanyi** [comment]
可以的 不过现在问题已经解决了



| |
***@***.***
|
|
***@***.***
|




---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年10月13日 14:11 |
| 收件人 | ***@***.***> |
| 抄送至 | Huanyi ***@***.******@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 使用tensor做为tensor索引出现问题 (Issue #46954) |

您好，可否提供一段简单的可运行的代码帮忙我们复现问题呢。 看出错提示，报错的语句并没有提供出来

**Comment by xiehuanyi** [comment]
> ### bug描述 Describe the Bug
> 我在复现Informer模型的时候遇到tensor索引问题，代码如下：
> 
> ```python
>     b, h, l_q, d = q.shape
>     _, _, l_k, _ = k.shape
> 
>     # calculate the sampled Q_K
>     k_expand = k.unsqueeze(-3).expand((b, h, l_q, l_k, d))  # shape [1, 1, 32, 34, 2]
>     index_sample = paddle.to_tensor(np.random.choice(l_k, size=(l_q, sample_k)), dtype='int64')  # [32, 20]
>     axis2 = paddle.arange(l_q).unsqueeze(1)  # [32, 1]
> 
>     k_sample = k_expand[:, :, axis2, index_sample, :]
> ```
> 
> 出现如下报错：
> 
> ```shell
> Traceback (most recent call last):
>   File "/Users/xiehuanyi/PycharmProjects/DL/src/Transformer/informer.py", line 22, in <module>
>     main()
>   File "/Users/xiehuanyi/PycharmProjects/DL/src/Transformer/informer.py", line 18, in main
>     print(feat1[index, :, :, :, :])
>   File "/Users/xiehuanyi/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 736, in __getitem__
>     return _getitem_impl_(self, item)
>   File "/Users/xiehuanyi/opt/anaconda3/lib/python3.9/site-packages/paddle/fluid/variable_index.py", line 455, in _getitem_impl_
>     raise IndexError(
> IndexError: Valid index accept int or slice or ellipsis or list, but received [Tensor(shape=[4], dtype=int64, place=Place(cpu), stop_gradient=True,
>        [1, 0, 0, 1]), slice(None, None, None), slice(None, None, None), slice(None, None, None), slice(None, None, None)].
> Tensor(shape=[2, 2, 2, 2, 4], dtype=int64, place=Place(cpu), stop_gradient=True,
>        [[[[[1, 0, 0, 2],
>            [2, 1, 0, 2]],
> 
>           [[0, 1, 2, 2],
>            [0, 2, 2, 2]]],
> 
> 
>          [[[1, 0, 0, 0],
>            [1, 0, 1, 1]],
> 
>           [[0, 1, 2, 2],
>            [1, 2, 1, 1]]]],
> 
> 
> 
>         [[[[0, 2, 1, 2],
>            [2, 1, 2, 0]],
> 
>           [[1, 2, 1, 2],
>            [2, 0, 2, 2]]],
> 
> 
>          [[[1, 0, 1, 0],
>            [1, 0, 2, 1]],
> 
>           [[1, 0, 0, 0],
>            [1, 0, 0, 0]]]]])
> Tensor(shape=[4], dtype=int64, place=Place(cpu), stop_gradient=True,
>        [1, 0, 0, 1])
> 
> 进程已结束,退出代码1
> ```
> 
> 相同的用法在pytorch中是可以使用的，如果想在paddle中实现相同效果，应该如何操作？
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

**Comment by xiehuanyi** [comment]
我通过这样的索引达到了预期的效果
```
    index_sample = paddle.to_tensor(np.random.choice(l_k, size=(l_q, sample_k)), dtype='int64')  # [32, 20]
    axis0 = paddle.arange(b)[:, None, None, None, None]
    axis1 = paddle.arange(h)[None, :, None, None, None]
    axis2 = paddle.arange(l_q)[None, None, :, None, None]
    axis3 = index_sample[None, None, :, :, None]
    axis4 = paddle.arange(d)[None, None, None, None, :]
    k_sample = k_expand[axis0, axis1, axis2, axis3, axis4]
    q_k_sample = paddle.matmul(q.unsqueeze(-2), k_sample, transpose_y=True).unsqueeze(-2)
```
貌似paddle使用tensor做索引的时候，不支持缺省。每个dimension都要写出来。
