### ISSUE TITLE
Check area under the losses to replace value comparison in each step for test_mnist_pure_fp16.

### ISSUE THREAD

**Issue by mingxu1067** [PaddlePaddle/Paddle#46973]
### 需求描述 Feature Description

We found `test_mnist_pure_fp16` fails on Hopper architecture GPUs.
```
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/python/paddle/fluid/tests/unittests/dygraph_to_static/test_mnist_pure_fp16.py", line 40, in test_mnist_to_static
    self.assertTrue(
AssertionError: False is not true : dygraph is [2.305, 2.248, 2.287, 1.997, 1.978, 1.836, 1.702, 1.677, 1.481, 1.4795, 1.309]
 static_res is 
[2.305, 2.252, 2.287, 1.997, 1.978, 1.836, 1.702, 1.678, 1.482, 1.48, 1.31]
```

The value difference in some step is larger than torrence (1e-3), like 2.248 vs 2.252 (4e-3). However, the convergence property is almost the same from the view of curve of loss. Then, we further compare ops between Dy and St mode and find that the number and order of kernels are not exactly the same (Dy got 193 kernels, St got 198). The mis-match might come from
1. Rounding errors from the different number and order of kernels.
2. Rounding errors from the different kernel implementation of CUDA library, like cuDNN, across GPU architecture.

### 替代实现 Alternatives

Therefore, we proposed to apply checking overlap area under the losses as criteria to stablize UTs.
In above tests, dygraph's area under loss is 18.4925, and static_graph is 18.4995. The absolute mis-match is 0.007, about 0.04% over dygraph's area (baseline), which is not much differnet.

The fomula of area under the loss:
$$\sum_{i=0}^{n-1} = \frac{(loss_i + loss_{i+1})}{2}, n = total\ steps$$

**Comment by mingxu1067** [comment]
CC: @0x45f

**Comment by 0x45f** [comment]
After discussion, we thought that the original method of checking losses was better, so I submitted PR to increase atol：https://github.com/PaddlePaddle/Paddle/pull/46984

**Comment by mingxu1067** [comment]
This issue is also fixed by [issues-46974](https://github.com/PaddlePaddle/Paddle/issues/46974). Probably, [PR46984](https://github.com/PaddlePaddle/Paddle/pull/46984) no need at this moment.

**Comment by onecatcn** [comment]
I closed the issue since the discussion showed it has been resolved. Thanks for the contributions.
