### ISSUE TITLE
Merge topdiffs before backward

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#4697]
首先，此issue描述的是针对网络结构中有branch分支的情况，比如GoogLeNet和ResNet。

与VGG相比，主要区别在于分之处的grad需要先收集起来，再做backward。

所以才有了这个issue。

关于实现有两种方式：
1. 类似IntelCaffe的做法，在初始化net的时候，自动[插入split layer](https://github.com/intel/caffe/blob/master/src/caffe/net.cpp#L137)。 
如果按照这个方式，就需要在PaddlePaddle的`NeuralNetwork::init`中通过`#if PADDLE_USE_MKLDNN`的方式加入对应的方法。

2. 使用Layer.h中定义的`std::map<std::string, Argument*> outputMap_`， 在`MKLDNNLayer::init`中把inputLayer的这个变量初始化好，等待整个net初始化完了之后，每个layer的map信息就齐全了。然后在backward的时候，先把outputMap里面的grad merge下，就可以了。

@luotao1 不知道更prefer的是哪一种？

**Comment by luotao1** [comment]
补充下背景：
- Paddle针对网络结构中有branch分支的情况，由于目前梯度是累加的，不需要merge diffs。
- MKLDNN的梯度是直接覆盖，非累加，所以需要merge diffs。

**Comment by luotao1** [comment]
请问MKLDNN的layer为什么不做成梯度直接累加的那种呢？

**Comment by tensor-tang** [comment]
因为如果每层的backward的grad输出都用累加，那么相比于现在的code，会多2样东西：
1. 多一个加法操作。现在MKLDNN的结果是直接覆盖的，如果用加法就还需要再开一块buffer暂存。
2. 每个layer 自己的grad，还需要在每个iteration的时候都清零grad，调用类似`reserveOutput`或`resetOutput`，都会清grad。现在的做法是可以不清零。

这样，每个layer可以省掉很多时间，并且当层数多的时候，省下的更多。

**Comment by qingqing01** [comment]
1. MKLDNN的接口是否有类似cuDNN接口的系数，比如类似`cudnnConvolutionBackwardData`接口，有针对dst的beta系数：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/cuda/src/hl_cuda_cudnn.cc#L864

如果有，不需要额外的buffer暂存，更改这个系数为1.0即可

2. 对grad的清零，PaddlePaddle框架已做，[`MultiGradientMachine.cpp`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/MultiGradientMachine.cpp#L558) 以及`ParameterUpdater`每个mini-batch都会对grad清零，不需要每个Layer各自对grad清零，这个只要用到了PaddlePaddle的`GradientMachine`和`ParameterUpdater`都始终做了清零操作，这块时间并没有省掉。

**Comment by tensor-tang** [comment]
1. MKLDNN 并没有这样的参数：
https://github.com/01org/mkl-dnn/blob/master/include/mkldnn.hpp#L1140

2. 那我是不是可以这样理解：
a. 首先，对于MultiGradientMachine.cpp在code里面写死的清零，这仅仅针对multi的时候，非multi的时候并没有看到，并且你这里的例子是parameter的grad，并不包含input和output的grad。
b. 其次，如果既然PaddlePaddle框架已经做了grad清零，那么我们看到现有的layer，比如[conv的resetOutput](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ExpandConvLayer.cpp#L156)中对于grad的清零是多余的？

如果有不对的地方请指出。

**Comment by qingqing01** [comment]
你的理解是对的。

针对1：没有系数的话，确实需要额外处理，你上述提到的两种解决方式，我理解都需要额外的内存。

加入连接方式如下，a连到b, a连到c:

```txt
      b   
   / 
a
    \
       c
```


方式1:  插入`自动插入split layer`，会变成：

```txt
                              b
                          / 
a -> split_layer
                          \
                              c
```

从[`split_layer`](https://github.com/intel/caffe/blob/master/src/caffe/layers/split_layer.cpp#L71)的backward实现来看，`split_layer`有2个`top_diff`，也是多出来的buffer。

方式2：使用`std::map<std::string, Argument*> outputMap_`

首先，当前PaddlePaddle中每个layer都只有一个输出，`outputMap_`是layer有多个输出时用(比如输出有2个Arguments)，而不是连接到多个layer时用, 可以参考解释：

```cpp
  /// If there are several outputs, map them by each name.
  std::map<std::string, Argument*> outputMap_;
```
即使做一些tric使用这个`outputMap_`，其实也是需要额外的内存吧，虽然相比在每个mkldnn-layer里面使用buffer暂存来说，是一个统一的实现。

**Comment by qingqing01** [comment]
针对2：

你说的是对的，`MultiGradientMachine`和`ParameterUpdater`(可以在`paddle/trainer/`目录下搜索`zeroMem()`，发现参数update之后，有对grad清零)是只对weight的grad清零，output的grad清零确实是在每个layer里做的。

**Comment by luotao1** [comment]
方法1，需要改paddle的`NeuralNetwork::init`这块；那方法2，除了改`MKLDNNLayer::init`这块外，也要改paddle原来的框架么？

**Comment by tensor-tang** [comment]
@qingqing01 针对1， 是的，不管采用哪种方式都是需要额外buffer的，毕竟MKLDNN求和还是需要的，但是新增的buffer应该不会多。

同时， 我觉得现在方法2从操作上应该会方便点，因为我看到目前只有[LstmStepLayer](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/LstmStepLayer.cpp#L101)这里修改了`outputMap_`，并且名字只用“state”。
如果我使用这个变量，与Paddle现有的框架也没有什么冲突，相比方法一，不需要修改现有框架@luotao1 。

> outputMap_是layer有多个输出时用(比如输出有2个Arguments)，而不是连接到多个layer时用, 可以参考解释

这一点，我觉得我应该可以多加一个备注，说明在MKLDNN里面也使用了这个变量。

**Comment by tensor-tang** [comment]
备注@luotao1 ，  方法一确实还需要先实现一个split layer才能办到。

**Comment by luotao1** [comment]
那就采用方法2吧。
