### ISSUE TITLE
hAPI与模型的forward_hook不兼容

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/Paddle#47000]
### bug描述 Describe the Bug

目前hAPI在动态图模式下，调用模型前向运算时，直接调用了nn.Layer对象的forward方法，而绕过了__call__方法，因而绕过了hooks执行逻辑：

模型的__call__方法：

https://github.com/PaddlePaddle/Paddle/blob/a5875319fe3bdd359895f1f6a11faf21df886f88/python/paddle/fluid/dygraph/layers.py#L924-L930

hAPI Model训练实现：
https://github.com/PaddlePaddle/Paddle/blob/910e1b6a9a302dba089fe63550a10287fdb58fee/python/paddle/hapi/model.py#L714-L722

hAPI Model eval实现：
https://github.com/PaddlePaddle/Paddle/blob/910e1b6a9a302dba089fe63550a10287fdb58fee/python/paddle/hapi/model.py#L749-L757

hAPI Model predict实现：
https://github.com/PaddlePaddle/Paddle/blob/910e1b6a9a302dba089fe63550a10287fdb58fee/python/paddle/hapi/model.py#L807-L815

可见均直接绕过了nn.Layer的hook逻辑

**Comment by luotao1** [comment]
close due to #47001
