### ISSUE TITLE
模型save后load加载的模型 无法获取sublayer和中间输出

### ISSUE THREAD

**Issue by Asucan** [PaddlePaddle/Paddle#47010]
### 请提出你的问题 Please ask your question

模型save后重新load sublayers是空的 无法获取中间层 只有一个TranslatedLayer
怎么才能获取中间层tensor的输出呢
<img width="563" alt="9b84d413f14f7daed4005ef3c52b7a06" src="https://user-images.githubusercontent.com/37799383/195749301-c6620f9d-8add-4e48-84a9-b7e50b6de9c3.png">

**Comment by sljlp** [comment]
请问这是paddle的模型套件还是你们自己构建的模型呢？

**Comment by Asucan** [comment]
> 请问这是paddle的模型套件还是你们自己构建的模型呢？

是自己搭的模型, 非框架自带模型, train模型的时候可以正常输出模型结构, 但是save再load之后就只剩下一个TranslatedLayer,
train时的结构(参数量不同是因为修改了一点点内部结构 但是整体结构未变化):
<img width="601" alt="image" src="https://user-images.githubusercontent.com/37799383/195756732-69f43f59-c4e0-4045-b68f-8b9493ef08c5.png">
save之后重新加载:
![image](https://user-images.githubusercontent.com/37799383/195756825-b25f1b90-6a26-4ebb-86fb-76a56b20574f.png)

**Comment by Asucan** [comment]
> > 请问这是paddle的模型套件还是你们自己构建的模型呢？
> 
> 是自己搭的模型, 非框架自带模型, train模型的时候可以正常输出模型结构, 但是save再load之后就只剩下一个TranslatedLayer, train时的结构(参数量不同是因为修改了一点点内部结构 但是整体结构未变化): <img alt="image" width="601" src="https://user-images.githubusercontent.com/37799383/195756732-69f43f59-c4e0-4045-b68f-8b9493ef08c5.png"> save之后重新加载: ![image](https://user-images.githubusercontent.com/37799383/195756825-b25f1b90-6a26-4ebb-86fb-76a56b20574f.png)

是用的是jit.save / jit.load 
paddle2.2版本

**Comment by sljlp** [comment]
请@chenwhql 看下

**Comment by chenwhql** [comment]
jit.save是将用paddle api搭建的动态图模型转换为静态图推理用的格式之后保存下来的，这个转换和保存的过程是不可逆的，转换后无法再恢复成动态图模式，而jit.load是提供了一种加载转换后的静态图的模型并运行的方式，但并不意味着能将已经Translated的Layer恢复为正常Layer

所以如果您的需求是仍然要通过print(Layer)查看网络接口，建议您使用paddle.save(layer.state_dict())的方式仅保存参数，用paddle.load加载之后继续使用，这个过程不会对Layer本身进行translated

**Comment by Asucan** [comment]
> 

paddle.save(layer.state_dict())中的layer是指最后output的layer么? 会保留sublayer么? 还有就是能访问子层的输出么?

**Comment by Asucan** [comment]
> jit.save是将用paddle api搭建的动态图模型转换为静态图推理用的格式之后保存下来的，这个转换和保存的过程是不可逆的，转换后无法再恢复成动态图模式，而jit.load是提供了一种加载转换后的静态图的模型并运行的方式，但并不意味着能将已经Translated的Layer恢复为正常Layer
> 
> 所以如果您的需求是仍然要通过print(Layer)查看网络接口，建议您使用paddle.save(layer.state_dict())的方式仅保存参数，用paddle.load加载之后继续使用，这个过程不会对Layer本身进行translated

paddle.save(layer.state_dict())中的layer是指最后output的layer么? 
会保留sublayer么? 
还有就是能访问子层的输出么?

**Comment by Asucan** [comment]
> jit.save是将用paddle api搭建的动态图模型转换为静态图推理用的格式之后保存下来的，这个转换和保存的过程是不可逆的，转换后无法再恢复成动态图模式，而jit.load是提供了一种加载转换后的静态图的模型并运行的方式，但并不意味着能将已经Translated的Layer恢复为正常Layer
> 
> 所以如果您的需求是仍然要通过print(Layer)查看网络接口，建议您使用paddle.save(layer.state_dict())的方式仅保存参数，用paddle.load加载之后继续使用，这个过程不会对Layer本身进行translated

按此方法尝试, 不能正常使用预测功能, 辛苦提供下demo

**Comment by chenwhql** [comment]
您是要存下来，在不依赖源码的前提下进行预测吗？paddle.save(layer.state_dict())是需要依赖源码的

**Comment by chenwhql** [comment]
经过沟通已解决当前的使用问题，先close
