### ISSUE TITLE
Paddle2.2.2 expand算子

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#47058]
### 请提出你的问题 Please ask your question

请问paddle2.2.2版本支持expand算子吗？
注意到直接通过paddle.expand接口调用的是expand_v2算子，在2.2.2中也没有找到layerhelper注册expand算子的代码，请问2.2.2是否已经不支持expand算子了。

**Comment by wuhuachaocoding** [comment]
您好，2.x的几个版本中，paddle.expand接口内部调用的一直是expand_v2算子。请问您在使用paddle.expand API时，存在什么问题吗？如果有，辛苦把复现代码或需求写一下。

**Comment by peiwenYe** [comment]
您好～我暂时没有在应用中遇到问题。只是注意到expand和expand_v2实现存在差别，expand的参数shape和expand_v2的参数expand_times表示的意义是不同的，我是想确认paddle2.2.2中是否已经不支持expand算子了。

**Comment by wuhuachaocoding** [comment]
您好，2.2.2版本中，对外API是expand_v2,  expand op还在，具体参考https://github.com/PaddlePaddle/Paddle/blob/v2.2.2/paddle/fluid/operators/expand_op.cc
