### ISSUE TITLE
切片慢

### ISSUE THREAD

**Issue by luochenghonggithub** [PaddlePaddle/Paddle#47052]
### 请提出你的问题 Please ask your question

你好，我有一个复杂的切片操作使用paddle会很慢，而使用pytorch和numpy却很快。由于右值存在梯度所以不能使用numpy进行操作，有什么好的办法让速度快点吗？
代码如下：
```
import paddle

import time

n = 1024
mat = paddle.zeros((n, n + 1))

index1 = paddle.arange(n).reshape((n, 1)).tolist()
index2 = paddle.randint(0, n + 1, shape=(n, 11)).tolist()
values = paddle.rand((n, 11))

start = time.time()
mat[index1, index2] = values
print(time.time() - start)

```

**Comment by wuhuachaocoding** [comment]
您好，已经收到您的需求，确实存在一定问题，我们已经安排人员在跟进这个问题。

**Comment by zoooo0820** [comment]
你好，复杂索引及赋值功能目前确实是存在性能问题，关于这部分优化的相关工作我们目前正在进行中

**Comment by GlennLoveZhen0124** [comment]
> 你好，复杂索引及赋值功能目前确实是存在性能问题，关于这部分优化的相关工作我们目前正在进行中

请问复杂索引性能问题现在解决了吗？我们现在训练也遇到了这个问题
