### ISSUE TITLE
[Call for Contribution] Tutorials for PaddlePaddle  ——— issue 链接

### ISSUE THREAD

**Issue by momozi1996** [PaddlePaddle/Paddle#47064]
### 问题描述 Please describe your issue

# [Call for Contribution] Tutorials for PaddlePaddle 
### 第一期任务 🎺

负责人：莫琰 [momozi1996](https://github.com/momozi1996) 

# 【参与者-选题方式】
- <u>**方式一**</u>：**列表选题**，见招募列表（提供了选题方向、题目、优秀的对标项目、文章和代码，以供学习）。
- <u>**方式二**</u>：**自选题目**，对于非参考列表内的题目，可自主命题，需要与负责人 [momozi1996](https://github.com/momozi1996) 讨论后决定题目。

# 【题目认领】
为避免重复选题、知晓任务状态、方便统计管理，请根据如下操作认领您的题目。
* 1）方式一（招募列表）：在“招募列表”中选择题目，并在本 Issue 中，回复下列信息：
```
【列表选题】
编号：XX
题目：XXXX
认领人：XX

```

* 2）方式二（自选题目）：自主命题，直接在本 Issue 中，回复下列信息：
```
【自选题目】
题目：XXXX
认领人：XX

```

# 【应用实践的编写模板：基于Notebook格式（.ipynb）】

```
# 题目

作者信息：Github ID (github个人主页URL)
更新日期：** 年 ** 月 ** 日
--

## 1. 简要介绍
简单的一段文字介绍本案例场景和用到的一些知识点，不用太复杂的讲述知识细节，

## 2. 环境设置
导入包，运行一些初始化方法

## 3. 数据集
讲述数据集的一些基础信息，描述数据集组成等。进行数据集的下载、抽样查看、数据集定义等。

## 4. 模型组网
基于Layer定义模型网络结构，模型的可视化展示。可以概要讲述一些网络结构代码设计的原因。

## 5. 模型训练
使用模型网络结构和数据集进行模型训练。需要讲述一些实践中的知识点。

## 6. 模型评估
使用评估数据评估训练好的模型。

## 7. 模型预测
对模型进行预测，展示效果。

```

## 招募列表（10月20日公开）

| 序号  | 领域  | 题目 | 新增点  | 参考范例  | 认领人  |
|:----| :----- |  :----- |  :----- |  :-----| :-----|
| 01  | CV (image)| cifar100数据集上基于Vision Transformer 实现图片分类|Vision Transformer (ViT)|https://keras.io/examples/vision/image_classification_with_vision_transformer/| jsdbzcm（kjf4096） | 
| 02  |CV (image)|Crowd Instance-level Human Parsing Dataset 数据集上使用DeepLabV3+实现多分类语义分割 |DeepLabV3|https://keras.io/examples/vision/deeplabv3_plus/| 木头熊（WangXi2016）   |
| 03  |CV (image)|Caltech 101 数据集上基于Vision Transformer 实现飞机目标识别|Vision Transformer (ViT)|https://keras.io/examples/vision/object_detection_using_vision_transformer/| 李长安（lwbmowgli ） |
| 04  |CV (image)|MosMedData: 新冠肺炎胸部 CT扫描数据集上基于3D-CNN实现二分类任务。|3D-CNN（医学图像）|https://keras.io/examples/vision/3D_image_classification/| 木头熊（WangXi2016） |
| 05  |CV (Point)|PASCAL 3D+数据集上使用 PointNet 实现5类点云的分割|PointNet （点云数据）|https://keras.io/examples/vision/pointnet_segmentation/| lzzzzzm |
| 06  |Video （视频）|UCF101数据集上实现基于TimeSformer模型的视频分类|transformer|https://aistudio.baidu.com/aistudio/projectdetail/2162025?channelType=0&channel=0| ---- |
| 07  |Video （视频）|COCO数据集上实现基于Mask-RCNN的视频分割|Mask-RCNN|https://github.com/facebookresearch/maskrcnn-benchmark| javaroom |
| 08  |Video （视频）|Moving MNIST 数据集上基于卷积LSTMs的下一帧视频预测|卷积LSTMs|https://keras.io/examples/vision/conv_lstm/| javaroom |
| 09  |Video （视频）|UCF101数据集上基于TSM的视频理解|TSM|https://aistudio.baidu.com/aistudio/projectdetail/4114499?channelType=0&channel=0| 木头熊 |
| 10  |Video （视频）|MedMNIST数据集上基于Video Vision Transformer的医学轻量视频分类任务。|Video ViT（医学视频）|https://keras.io/examples/vision/vivit/| 木头熊 |
| 11  |可解释性（神经网络性能的可解释性）|使用Grad-CAM 类激活可视化深度学习网络性能的可解释性|Grad-CAM|https://keras.io/examples/vision/grad_cam/| 李长安（lwbmowgli ） |
| 12  |时间序列|PeMSD7 真实交通速度数据集上利用 图神经网络 和 LSTM 进行交通预测|GNN & LSTM|https://keras.io/examples/timeseries/timeseries_traffic_forecasting/| ---- |
| 13  |时间序列|Jena Climate时间序列数据集上使用LSTM进行温度的预报|LSTM|https://keras.io/examples/timeseries/timeseries_weather_forecasting/| 深渊上的坑（edencfc） |
| 14  |时间序列|FordA噪声测量数据集上使用FCN进行发动机噪声分类|FCN|https://keras.io/examples/timeseries/timeseries_classification_from_scratch/| javaroom |
| 15  |时间序列|baostock 证券数据集下使用LSTM 模型预测 A 股走势|LSTM|https://colab.research.google.com/github/invisprints/blog/blob/master/_notebooks/2020-04-17-LSTM-stock.ipynb| 深渊上的坑（edencfc） |
| 16  |图数据|Cora数据集上使用图关注网络GAT进行科学论文的预测|GAT|https://keras.io/examples/graph/gat_node_classification/| Rayman96 |
| 17  |图数据|BBBP分子药数据集上使用MPNN模型进行分子的性质预测|药物性质预测|https://keras.io/examples/graph/mpnn-molecular-graphs/| ---- |
| 18  |NLP|IMDB数据集上基于双边 LSTM的文本分类任务|双边 LSTM|https://keras.io/examples/nlp/bidirectional_lstm_imdb/| 唐竹笑 |
| 19  |NLP|English-to-Spani数据集下基于sequence-to-sequence Transformer的机器翻译任务|Transformer|https://keras.io/examples/nlp/neural_machine_translation_with_transformer/| 月光下的独孤亮（2017040264 ）  |
| 20  |NLP|文献检索数据集下基于Pair-wise模型的语义检索系统|Pair-wise|https://aistudio.baidu.com/aistudio/projectdetail/3351784?channelType=0&channel=0| --   |
| 21  |NLP|RSC15数据集下构造序列语义检索SSR模型|SSR模型|https://aistudio.baidu.com/aistudio/projectdetail/205028?channelType=0&channel=0| --   |
| 22  |NLP|NLPCC2018数据集下基于word2vec构造知识库问答系统系统|word2vec|https://aistudio.baidu.com/aistudio/projectdetail/3206157?channelType=0&channel=0| RedContritio  |
| 23  |NLP|NLPCC14-SC和ChnSentiCorp数据集下基于SKEP构造句子级的文本情感分析|SKEP|https://aistudio.baidu.com/aistudio/projectdetail/2097355?channelType=0&channel=0| --   |
| 24  |Audio （语音）|LJSpeech 数据集下使用CTC进行自动语音识别|CTC|https://keras.io/examples/audio/ctc_asr/|  javaroom |
| 25  |Audio （语音）|LJSpeech 数据集下使用Transformer进行音频语音片段的自动语音识别(ASR)|Transformer|https://keras.io/examples/audio/transformer_asr/| --   |
| 26  |推荐|Goodbooks-10k数据集下基于隐式推荐算法模型完成图书推荐系统|隐式推荐算法|https://aistudio.baidu.com/aistudio/projectdetail/2556840?channelType=0&channel=0| --   |
| 27  |推荐|基于PaddlePaddle的SR-GNN推荐算法解决Session-based 会话推荐模型|SR-GNN推荐|https://aistudio.baidu.com/aistudio/projectdetail/124382?channelType=0&channel=0| --   |
| 28  |强化学习|用DQN强化学习算法玩“合成大西瓜”！|DQN|https://aistudio.baidu.com/aistudio/projectdetail/1556392?channelType=0&channel=0| RedContritio  |
| 29  |强化学习|用飞桨框架基于AlphaZero算法造一个会下五子棋的AI模型|AlphaZero算法|https://aistudio.baidu.com/aistudio/projectdetail/1403398| yangguohao  |
| 30  |GAN|selfie2anime数据集下基于CycleGAN的将照片变为二次元卡通风格|CycleGAN|https://aistudio.baidu.com/aistudio/projectdetail/1153303?channelType=0&channel=0| RedContritio |
| 31  |GAN|MNIST数据集下用Paddle框架的动态图模式玩耍经典对抗生成网络（GAN）|GAN|https://aistudio.baidu.com/aistudio/projectdetail/551962?channelType=0&channel=0| --   |
| 32  |GAN|cifar10数据集上复现大规模的生成对抗网络模型BigGAN|BigGAN|https://aistudio.baidu.com/aistudio/projectdetail/860925?channelType=0&channel=0| --   |
| 33  |GAN|城市街景分割数据集下使用对抗网络Pix2Pix生成分割掩码，并使用掩码生成街景|对抗网络Pix2Pix|https://aistudio.baidu.com/aistudio/projectdetail/1119048?channelType=0&channel=0| --   |
| 34  |多模态|基于UGC用户制作的真实短视频业务数据，融合文本、视频图像、音频三种模态进行视频多模标签分类|多模融合|https://aistudio.baidu.com/aistudio/projectdetail/3469740?channelType=0&channel=0| --   |
| 35  |多模态|XFUND数据集下基于多模态(OCR+文档视觉问答)技术实现金融表单识别|(OCR+文档视觉问答)|https://aistudio.baidu.com/aistudio/projectdetail/3884375?channelType=0&channel=0| --   |
| 36  |多模态|GAMMA比赛多模态眼底图像数据集下基于EfficientNet和resnet构造fundus_img和oct_img的分类模型|EfficientNetB3+resnet34|https://aistudio.baidu.com/aistudio/projectdetail/2334029?channelType=0&channel=0| --   |

 <mark>【注意】招募列表外的，欢迎开发者主动贡献👏 <mark>

**Comment by Rayman96** [comment]
【列表选题】
编号：16
题目：Cora数据集上使用图关注网络GAT进行科学论文的预测
认领人：Rayman96

**Comment by momozi1996** [comment]
> 
感谢，你的选题已被飞桨框架团队收到，将在3个工作日内邀请你进入任务群，并指导完成任务，请留意信息。

**Comment by yangguohao** [comment]
【列表选题】
编号：29
题目：用飞桨框架基于AlphaZero算法造一个会下五子棋的AI模型
认领人：yangguohao

**Comment by kjf4096** [comment]
【列表选题】
编号：1
题目：cifar100数据集上基于Vision Transformer 实现图片分类
认领人：jsdbzcm

**Comment by edencfc** [comment]
【列表选题】
编号：13
题目：Jena Climate时间序列数据集上使用LSTM进行温度的预报
认领人：深渊上的坑

**Comment by edencfc** [comment]
【列表选题】
编号：15
题目：baostock 证券数据集下使用LSTM 模型预测 A 股走势
认领人：深渊上的坑

**Comment by lwbmowgli** [comment]
【列表选题】
编号：11
题目：使用Grad-CAM 类激活可视化深度学习网络性能的可解释性
认领人：李长安

**Comment by lwbmowgli** [comment]
【列表选题】
编号：03
题目：Caltech 101 数据集上基于Vision Transformer 实现飞机目标识别
认领人：李长安

**Comment by momozi1996** [comment]
感谢，选题已被飞桨框架团队收到，将在3个工作日内邀请你进入任务微信群。并指导完成任务，请留意信息。

**Comment by WangXi2016** [comment]
【列表选题】
编号：04
题目：MosMedData: 新冠肺炎胸部 CT扫描数据集上基于3D-CNN实现二分类任务。
认领人：木头熊

**Comment by WangXi2016** [comment]
【列表选题】
编号：02
题目：Crowd Instance-level Human Parsing Dataset 数据集上使用DeepLabV3+实现多分类语义分割
认领人：木头熊

**Comment by RedContritio** [comment]
【列表选题】
编号：28
题目：用DQN强化学习算法玩“合成大西瓜”！
认领人：RedContritio

**Comment by 2017040264** [comment]
【列表选题】
编号：19
题目：English-to-Spani数据集下基于sequence-to-sequence Transformer的机器翻译任务
认领人：月光下的独孤亮

**Comment by momozi1996** [comment]
您认领任务了后，请扫码加入微信群，我们实时回答问题～






&nbsp;


BIT莫琰
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月26日(星期三) 下午2:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] [Call for Contribution] Tutorials for PaddlePaddle  ——— issue 链接 (Issue #47064)





 
【列表选题】
 编号：19
 题目：English-to-Spani数据集下基于sequence-to-sequence Transformer的机器翻译任务
 认领人：月光下的独孤亮
 
&mdash;

**Comment by RedContritio** [comment]
【列表选题】
编号：30
题目：selfie2anime数据集下基于CycleGAN的将照片变为二次元卡通风格
认领人：RedContritio

**Comment by lzzzzzm** [comment]
【列表选题】
编号：05
题目：PASCAL 3D+数据集上使用 PointNet 实现5类点云的分割
认领人：lzzzzzm

**Comment by npuyzr** [comment]
【列表选题】
编号：26
题目：Goodbooks-10k数据集下基于隐式推荐算法模型完成图书推荐系统
认领人：npuyzr

**Comment by npuyzr** [comment]
【列表选题】
编号：26
题目：Goodbooks-10k数据集下基于隐式推荐算法模型完成图书推荐系统
认领人：npuyzr

**Comment by lzzzzzm** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by RedContritio** [comment]
【列表选题】
编号：22
题目：NLPCC2018数据集下基于word2vec构造知识库问答系统系统
认领人：RedContritio

**Comment by 2017040264** [comment]
【列表选题】
编号：25
题目：LJSpeech 数据集下使用Transformer进行音频语音片段的自动语音识别(ASR)
认领人：月光下的独孤亮

**Comment by edencfc** [comment]
> 【列表选题】 编号：13 题目：Jena Climate时间序列数据集上使用LSTM进行温度的预报 认领人：深渊上的坑

在Jena Climate时间序列数据集上使用LSTM进行气温预报：https://aistudio.baidu.com/aistudio/projectdetail/4904531

**Comment by WangXi2016** [comment]
【列表选题】
编号：10
题目：MedMNIST数据集上基于Video Vision Transformer的医学轻量视频分类任务。
认领人：木头熊

**Comment by WangXi2016** [comment]
【列表选题】
编号：9
题目：UCF101数据集上基于TSM的视频理解。
认领人：木头熊

**Comment by momozi1996** [comment]
### 11/4日 活动进展⏰
- 任务认领——认领率：22份/36份
- 任务完成&提交AIstudio ——完成/认领率：4份/22份
- 任务完成&提交PR ——完成/认领率：4份/22份

### github-参与人：（11位）
@RedContritio、@lwbmowgli、@WangXi2016、@Rayman96、@edencfc、@kjf4096、@npuyzr、@2017040264、@lzzzzzm、@yangguohao、@wuhuachaocoding

### github-contributor 进展：（4位）
@WangXi2016、@lzzzzzm、@edencfc、@2017040264

### 已提交的4个PR：
- [5381](https://github.com/PaddlePaddle/docs/pull/5381)
- [5384](https://github.com/PaddlePaddle/docs/pull/5384)
- [5390](https://github.com/PaddlePaddle/docs/pull/5390)
- [5391](https://github.com/PaddlePaddle/docs/pull/5391)

**Comment by dasenCoding** [comment]
【列表选题】
编号：26
题目：Goodbooks-10k数据集下基于隐式推荐算法模型完成图书推荐系统
认领人：dasenCoding

**Comment by Liyulingyue** [comment]
【列表选题】
编号：31
题目：MNIST数据集下用Paddle框架的动态图模式玩耍经典对抗生成网络（GAN）
认领人：笠雨聆月

**Comment by RuthlessMan** [comment]
【列表选题】
编号：12
题目：PeMSD7 真实交通速度数据集上利用 图神经网络 和 LSTM 进行交通预测。
认领人：无情道人

**Comment by momozi1996** [comment]
## 11/18日 活动进展⏰
- 任务认领——认领率：25份/36份
- 任务完成&提交AIstudio ——完成/认领率：6份/22份
- 任务完成&提交PR ——完成/认领率：6份/22份

## github-参与人：（14位）
@RedContritio、@lwbmowgli、@WangXi2016、@Rayman96、@edencfc、@kjf4096、@npuyzr、@2017040264、@lzzzzzm、@yangguohao、@wuhuachaocoding、@dasenCoding 、@Liyulingyue 、@RuthlessMan

## github-PR提交人-进展：（4位）
@WangXi2016、@lzzzzzm、@edencfc、@2017040264

### 已提交的6个PR：
https://github.com/PaddlePaddle/docs/pull/5381
https://github.com/PaddlePaddle/docs/pull/5384
https://github.com/PaddlePaddle/docs/pull/5390
https://github.com/PaddlePaddle/docs/pull/5391
https://github.com/PaddlePaddle/docs/pull/5419 【AIstudio-加精】
https://github.com/PaddlePaddle/docs/pull/5411  【AIstudio-加精】

**Comment by Liyulingyue** [comment]
【列表选题】
编号：33
题目：城市街景分割数据集下使用对抗网络Pix2Pix生成分割掩码，并使用掩码生成街景
认领人：笠雨聆月

**Comment by tianxingxia-cn** [comment]
【列表选题】
编号：35
题目：XFUND数据集下基于多模态(OCR+文档视觉问答)技术实现金融表单识别
认领人：tianxingxia

**Comment by momozi1996** [comment]
## 11/25日 活动进展⏰
- 任务认领——认领率：26份/36份
- 任务完成&提交AIstudio ——完成/认领率：8份/26份
- 任务完成&提交PR ——完成/认领率：8份/26份

## github-参与人：（14位）
@RedContritio、@lwbmowgli、@WangXi2016、@Rayman96、@edencfc、@kjf4096、@npuyzr、@2017040264、@lzzzzzm、@yangguohao、@wuhuachaocoding、@dasenCoding 、@Liyulingyue 、@RuthlessMan、@tianxingxia-cn

## github-PR提交人-进展：（5位）
@WangXi2016、@lzzzzzm、@edencfc、@2017040264、@Liyulingyue 

### 已提交的8个PR：
https://github.com/PaddlePaddle/docs/pull/5381 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5384 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5390  【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5391  【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5419 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5411  【RD审核意见，待回复和修改】

https://github.com/PaddlePaddle/docs/pull/5426   【RD通过，待merge】
https://github.com/PaddlePaddle/docs/pull/5439  【RD通过，待merge】

**Comment by Fancy-hjyp** [comment]
【列表选题】
编号：36
题目：GAMMA比赛多模态眼底图像数据集下基于EfficientNet和resnet构造fundus_img和oct_img的分类模型
认领人：Tomoko-hjf

**Comment by momozi1996** [comment]
## 12/2日  活动进展⏰
- 任务认领——认领率：27份/36份
- 任务完成&提交 AIstudio ——完成/认领率：9份/27份
- 任务完成&提交 PR ——完成/认领率：9份/27份

## github-参与人：（14位）
@RedContritio、@lwbmowgli、@WangXi2016、@Rayman96、@edencfc、@kjf4096、@npuyzr、@2017040264、@lzzzzzm、@yangguohao、@wuhuachaocoding、@dasenCoding 、@Liyulingyue 、@RuthlessMan、@tianxingxia-cn、@Tomoko-hjf

## github-PR提交人-进展：（6位）
@WangXi2016、@lzzzzzm、@edencfc、@2017040264、@Liyulingyue 、@RedContritio

### 已提交的8个PR：
https://github.com/PaddlePaddle/docs/pull/5381 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5384 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5390  【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5391  【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5419 【RD审核意见，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5411  【RD审核意见，待回复和修改】

https://github.com/PaddlePaddle/docs/pull/5426   【RD通过，待merge】
https://github.com/PaddlePaddle/docs/pull/5439  【RD通过，待merge】

 https://github.com/PaddlePaddle/docs/pull/5454【RD review中】

**Comment by momozi1996** [comment]
> 【列表选题】 编号：36 题目：GAMMA比赛多模态眼底图像数据集下基于EfficientNet和resnet构造fundus_img和oct_img的分类模型 认领人：Tomoko-hjf

hi , @Tomoko-hjf  请联系我，加入技术指导微信群。

**Comment by momozi1996** [comment]
## 12/9日  活动进展⏰
- 任务认领——认领率：27份/36份
- 任务完成&提交 AIstudio ——完成/认领率：10份/27份
- 任务完成&提交 PR ——完成/认领率：10份/27份

## github-参与人：（14位）
@RedContritio、@lwbmowgli、@WangXi2016、@Rayman96、@edencfc、@kjf4096、@npuyzr、@2017040264、@lzzzzzm、@yangguohao、@wuhuachaocoding、@dasenCoding 、@Liyulingyue 、@RuthlessMan、@tianxingxia-cn、@Tomoko-hjf

## github-PR提交人-进展：（7位）
@WangXi2016、@lzzzzzm、@edencfc、@2017040264、@Liyulingyue 、@RedContritio、@Tomoko-hjf

### 已提交的 10 个PR：
https://github.com/PaddlePaddle/docs/pull/5381 【merged】
https://github.com/PaddlePaddle/docs/pull/5384 【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5390  【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5391  【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5419 【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5411  【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5426   【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5439  【RD审核，待回复和修改】
https://github.com/PaddlePaddle/docs/pull/5454  【RD 审核中】
https://github.com/PaddlePaddle/docs/pull/5490 【RD 审核中】

**Comment by Fleming-Sung** [comment]
【列表选题】
编号：12
题目：PeMSD7 真实交通速度数据集上利用 图神经网络 和 LSTM 进行交通预测。
认领人：Ming Sung

**Comment by lzzzzzm** [comment]
你发过来的邮件怎么都是乱码啊，什么都看不到，再发一次吧。

**Comment by ShiYue-oo** [comment]
【列表选题】
编号：32
题目：cifar10数据集上复现大规模的生成对抗网络模型BigGAN
认领人：wq-go
