### ISSUE TITLE
关于环境支持的展示

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#47078]
### 需求描述 Feature Description

在官网的安装指南和paddle的readme中添加受支持的表格以供维护和参考, 实现方法类似于下面的示例
|    System    | CPU (32bit) | CPU (64bit) | GPU (32bit) | GPU (64bit) |
|:------------:|:-----------:|:-----------:|:-----------:|:-----------:|
| Linux (GCC7) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - |![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|
| Linux (GCC8) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - |![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|
| Linux (Clang) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - |![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|
| Linux (ARM) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - | - |
| Windows (VS2017) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat) |
| Windows (VS2019) | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)|![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - | ![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat) |
| Windows (VS2020) | ![](https://img.shields.io/badge/build-failing-red.svg?style=flat)|![](https://img.shields.io/badge/build-failing-red.svg?style=flat)| - | ![](https://img.shields.io/badge/build-failing-red.svg?style=flat) |
| MacOS | - |![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - | - |
| MacOS (ARM) | - |![](https://img.shields.io/badge/build-passing-brightgreen.svg?style=flat)| - | - |

**Comment by gouzil** [comment]
#47079

**Comment by ddgetget** [comment]
有没有多好的对应的docker运行环境呀？

**Comment by gouzil** [comment]
> 有没有多好的对应的docker运行环境呀？

可以去hub看镜像
