### ISSUE TITLE
线上libpaddle_capi_shared.so耗时问题

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#4708]
我们用的libpaddle_capi_shared.so有3个版本，  [下载链接](https://paddleci.ngrok.io/overview.html）  
1. 版本1，支持avx, libpaddle_capi_shared.so有248M。(8月份，paddle的同学提供的下载链接得到的)
2. 版本2，支持avx, libpaddle_capi_shared.so只有5.8M, 同时有其他的so库。（9月29日paddle同学编译的）
3. 版本3，不支持avx, libpaddle_capi_shared.so只有5.8M, 同时有其他的so库。（9月29日paddle同学编译的）

现在的问题是耗时问题，版本1平均耗时120ms左右。 版本2测试的耗时是400多ms。

是不是编译版本2、3的时候没有加一些编译优化？辛苦paddle的同学了。

**Comment by Jarlonyan** [comment]
@gongweibao 同学加上了CMAKE_BUILD_TYPE=Release参数，再测试版本2、3的耗时情况是：
版本2平均耗时258ms
版本3平均耗时283ms

**Comment by zds9204** [comment]
同遇到这个问题，请教paddle组的同学！我最近在链接 https://paddleci.ngrok.io/overview.html 上下到的libpaddle_capi_shared.so（6M左右，但是还有libmklml_intel.so等其它依赖），与内网上找到的的一份文件（http://icode.baidu.com/repo/baidu%2Fthird-party%2Fpaddle-capi/files/master/tree/ ， 136M，只有单独一个文件）相比，模型耗时增加了10倍。

**Comment by gongweibao** [comment]
基本上已经找到问题了，
1. 要加CMAKE_BUILD_TYPE=Release编译
2. 链接的mkl不能链接开源版本，而要链接公司买的商业版本。

**Comment by luotao1** [comment]
请问为什么不能链接mkl开源版本，公司买的商业版本是哪个版呢？

**Comment by gongweibao** [comment]
`mklml` sometime is much lower than `mkl`。
