### ISSUE TITLE
paddledetection里如何注册一个新的dataset

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#47085]
### 请提出你的问题 Please ask your question

我没有用官方默认的TrainDataset，参考官方的TrainDataset config文件新建了一个XXXTrainDataset，但是运行的时候提示
“AssertionError: the module XXXTrainDataset is not registered”，请问该怎么改呢？

**Comment by firestonelib** [comment]
一般步骤：
1.在 ppdet/data/source 下创建自定义 dataset python 文件
2.为自定义的 Dataset 类添加register注册，可参考：https://github.com/PaddlePaddle/PaddleDetection/blob/7fb2318a4f272a78ec1e4344abd1758735fce8d3/ppdet/data/source/coco.py#L24
3.在 ppdet/data/source/__init__.py 中导入自定义 Dataset 即可
