### ISSUE TITLE
因PR：https://github.com/PaddlePaddle/Paddle/pull/47036 导致PaddleSlim单测test_merge.py failed

### ISSUE THREAD

**Issue by iamWHTWD** [PaddlePaddle/Paddle#47096]
### bug描述 Describe the Bug

AttributeError: 'str' object has no attribute 'decode'
![image](https://user-images.githubusercontent.com/28421344/196357673-a9f7eaf4-fe05-4a9e-9cc7-d71fc4ee6038.png)

复现步骤：
git clone https://github.com/PaddlePaddle/PaddleSlim.git
cd PaddleSlim/tests
python test_merge.py

### 其他补充信息 Additional Supplementary Information

related https://github.com/PaddlePaddle/Paddle/pull/47036
<img width="1421" alt="bb2fd0a0910e90b4b34205cba735d77b" src="https://user-images.githubusercontent.com/6836917/196358516-687ff3cb-ec77-4ca6-b061-5ceca45b41a9.png">

**Comment by SigureMo** [comment]
抱歉这里当时这一个是没有单测没有覆盖到的，因此是根据框架内上下文修改的（仅仅传递 bytes），未考虑到依赖于主框架的套件的用法（传递了 str），这里已经做出了兼容性处理，和原有行为保持一致

目前已经在 #47097 做了修复
