### ISSUE TITLE
||条件前后一样

### ISSUE THREAD

**Issue by zhangxin81** [PaddlePaddle/Paddle#47094]
https://github.com/PaddlePaddle/Paddle/blob/940d8f253239a74e0812faf9a80f60d5c39ebedd/paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc#L127

**Comment by firestonelib** [comment]
感谢反馈，我们已确定问题，稍后贴出pr

**Comment by luotao1** [comment]
@firestonelib 目前develop分支的该文件，还有3处没有修改
https://github.com/PaddlePaddle/Paddle/blob/9bd20aa0d24aa1c459cb2775879754fdd05a8456/paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc#L66

https://github.com/PaddlePaddle/Paddle/blob/9bd20aa0d24aa1c459cb2775879754fdd05a8456/paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc#L142

https://github.com/PaddlePaddle/Paddle/blob/9bd20aa0d24aa1c459cb2775879754fdd05a8456/paddle/fluid/inference/analysis/passes/ir_params_sync_among_devices_pass.cc#L200

**Comment by luotao1** [comment]
close due to #49624 merged
