### ISSUE TITLE
当网络使用DataParallel后，如何调用模型里的方法？

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#47109]
### 请提出你的问题 Please ask your question

例如
model = DataParallel(model)
a = model.backbone ()
会提示报错“AttributeError: 'DataParallel' object has no attribute backbone”

**Comment by firestonelib** [comment]
model = DataParallel(model)
model_s = model._layers
a = model_s.backbone ()

**Comment by bixiaopeng0** [comment]
thanks
