### ISSUE TITLE
Inference Lite模式 添加OpenCL启用接口

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#47113]
### 需求描述 Feature Description

**任务目标:**
在WITH_LITE=ON 的编译选项下，开启OpenCL模式，原本只有CPU模式。
**需求场景:**
企业合作内容
**功能描述:**
Inference Lite模式 添加OpenCL启用接口， 在WITH_LITE=ON 的编译选项下，开启OpenCL模式，原本只有CPU模式。

添加接口 AnalysisConfig::EnableLiteOpenCLEngine()
以及其他若干结构体变量

**实现Code （请求Merge)**
https://github.com/PaddlePaddle/Paddle/pull/47112

**Comment by luotao1** [comment]
请 @qingqing01 @leiqing1 帮忙看下

**Comment by engineer1109** [comment]
Code Merged
