### ISSUE TITLE
paddle对于CUPTI的调用

### ISSUE THREAD

**Issue by zyx2095** [PaddlePaddle/Paddle#47129]
### 请提出你的问题 Please ask your question

paddle中调用的CUPTI的接口是否都在cupti.h，还有用到其他的接口吗？
 __macro(cuptiActivityEnable);               \
  __macro(cuptiActivityDisable);              \
  __macro(cuptiActivityRegisterCallbacks);    \
  __macro(cuptiActivityGetAttribute);         \
  __macro(cuptiActivitySetAttribute);         \
  __macro(cuptiGetTimestamp);                 \
  __macro(cuptiActivityGetNextRecord);        \
  __macro(cuptiGetResultString);              \
  __macro(cuptiActivityGetNumDroppedRecords); \
  __macro(cuptiActivityFlushAll);             \
  __macro(cuptiSubscribe);                    \
  __macro(cuptiUnsubscribe);                  \
  __macro(cuptiEnableCallback);               \
  __macro(cuptiEnableDomain);                 \
  __macro(cudaOccMaxActiveBlocksPerMultiprocessor)

**Comment by chenwhql** [comment]
应该是的，paddle中使用cupti的接口是通过这种动态加载的方式去使用的，如果需要使用其他接口，应该需要在这里声明加载
