### ISSUE TITLE
[CodeStyle] Compiler Warning tracking issue

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#47143]
# 项目说明
用于跟踪 [Call-for-Contributions: 编译 warning 消除计划](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style/code_style_compiler_warning.md) 并记录该计划下各个子任务的计划和进度。

# 项目初始状态
目前 Paddle 在 Linux, Mac, Windows 上存在许多 warning，其中大部分是有第三方库引入。去除掉第三方库的影响，在 Linux, Mac, Windows 上分别存在 40, 743, 8 条 warning 记录。

* 推进方案：对现有的 warning 进行分类修复，然后修复隐藏的 warning, 修复完一类 warning 后将该类 warning 改为 error 避免 warning 重复出现。

# Warning 消除阶段性目标
### 1.1 Linux 明面 Warning（进展 5/6）
| 序号 | Warning |  个数 | 存量修复 |  增量拦截 |作者 |
| :-----------: | :----------- | :-----------: | :-----------: | :-----------: |  :-----------: |
|   1  |✅ [-Wsign-compare] （2022/10/22）|  25  |  #46644 (25) #47252 (11)  | #47163  |  [Li-fAngyU](https://github.com/Li-fAngyU)   |
|   2  |✅ [-Wunused-local-typedefs]  (2022/11/1)| 4  | #47513 (4)   |  #47513  |   [GreatV](https://github.com/GreatV)  |
|   3  | ✅[-Wunused-variable] (2022/11/3)|  4  | #47558 (4)  #47706 |  #47558 #47706  |   [GreatV](https://github.com/GreatV)  |
|   4  | ✅[-Wterminate] (2023/3/31)|  9  |  #52307  |  #52564  |  @Galaxy1458  |
|   5  | ✅[-Wmaybe-uninitialized]  (2023/3/9)|  3  | #51336 (3)   | #51336   | @GreatV   |
|   6  | ✅ [-Wunknown-pragmas] (2023/3/6) |  2  |  #51203 (2)  | #51203   | @GreatV   |

更新：以2023/02/13某成功PR的流水线 [PR-CI-Build](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/7770445/job/21695308) 为例。

### 1.2 Mac 明面 Warning（进展 8/10）
| 序号 | Warning |  个数 | 存量修复 |  增量拦截 | 作者 |
| :-----------: | :----------- | :-----------: | :-----------: | :-----------: | :-----------: |
|  1   | ✅ [-Winconsistent-missing-override]（2022/10/22） | 743 |  #47264 (743) | #47264  |   [GreatV](https://github.com/GreatV)    | 
|  2   |✅  [-Wformat] （2022/10/19） | 31 | #47137 (31) | #47216   | [GreatV](https://github.com/GreatV)   | 
|  3   | ✅ [-Wbraced-scalar-init] （2022/10/24） | 13 | #47309 (13)  |  #47309 |  [GreatV](https://github.com/GreatV)  | 
|  4-6 |✅  [-Wliteral-conversion]  [-Wuninitialized]  [-Wtautological-constant-out-of-range-compare]  （2022/10/26） | 3 |  #47341 (3) | #47341   |   [GreatV](https://github.com/GreatV)  | 
|  7 | ✅[-Wpragma-pack] (2022/10/28) | 1 | #47399 (1)  | #47399  |   [GreatV](https://github.com/GreatV)   | 
|  8   |✅ [-Wc++17-extensions]（2022/12/14） | 4 | #49017 (4)  | #49017  | @AndPuQing   | 
|  9   | ✅[-Wexceptions] (2023/3/31)| 2 | #52307  |  #52564 |  @Galaxy1458  | 
|  10   | [-Wreturn-type-c-linkage] | 1 |   |   |   | 

更新：以2023/02/13某成功PR的流水线 [PR-CI-Mac-Python3](https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/7770363/job/21695160) 为例。

### 1.3 Windows 明面 Warning 
TBE

### 2.1 Linux 未打开的 Warning
TBE
### 2.2 macOS 未打开的 Warning
TBE

## 3 其他成果总结
|子任务和完成时间|相关 PR|作者 |
|-|-|-|
|✅去掉 boost 库引入的 warning （2022/10/29）| #47468 |[GreatV](https://github.com/GreatV) 
|✅修复 GCC9.4 下的 maybe-uninitialized 编译错误 |#51605 #51633| @engineer1109 @jinyouzhi |

**Comment by luotao1** [comment]
编译warning消除（明面）已全部完成！
- 感谢参与的小伙伴们：@Li-fAngyU、@GreatV、@AndPuQing、@engineer1109、 @jinyouzhi
- 结项小结见：[code_style_compiler_warning_milestone_summary.md](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style/code_style_compiler_warning_milestone_summary.md)

欢迎继续参与 [快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/48019)！
