### ISSUE TITLE
推理模型文件中的存储格式NCHW改为NHWC

### ISSUE THREAD

**Issue by Rokcy-Lucky** [PaddlePaddle/Paddle#47158]
### 请提出你的问题 Please ask your question

如何将paddle推理模型文件中的存储格式NCHW改为NHWC

**Comment by JZZ-NOTE** [comment]
你好呀，请问转化的需求是什么呢？如果转换了没有相应的kernel支持，也是没办法运行的。

**Comment by Rokcy-Lucky** [comment]
你好！我也是本集团员工，将数据转化为NHWC格式可以提高运行效率，该项目对fps要求较高。请问paddle这边是否有对应的工具或者接口将推理模型文件中的存储格式NCHW改为NHWC？谢谢！

**Comment by JZZ-NOTE** [comment]
那可以在如流上沟通，jingzhuangzhuang。现在应该没有这样的工具，因为转换完之后，没法推理。

**Comment by zjliu-cs** [comment]
paddle.vision.transforms.Transpose
