### ISSUE TITLE
undefined reference to `paddle::experimental::add(paddle::experimental::Tensor const&, paddle::experimental::Tensor const&)

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#47162]
### bug描述 Describe the Bug

对于 #include "paddle/phi/api/include/api.h" 里面的函数
例如paddle::experimental::add
在libpaddle.so 有符号  但是在libpaddle_inference.so 没有符号

gcc有一个规定，链接静态库，如果不使用静态库中的符号，则不会导出

于是会 undefined reference to `paddle::experimental::add(paddle::experimental::Tensor const&, paddle::experimental::Tensor const&)

我不知道libpaddle.so 哪里做了什么导出了这些符号，
我如果想在paddle_inference导出 这些符号，应该做什么（以前是能导出的）

**Comment by engineer1109** [comment]
都在libphi_function_api.a 里面

**Comment by chenwhql** [comment]
是以前能用，现在不能用了吗？

**Comment by engineer1109** [comment]
@chenwhql 是的，以前有ABI导出来的，现在的没有了

**Comment by engineer1109** [comment]
nm libpaddle_inference.so | grep N6paddle12experimental3add  无结果
nm libpaddle_inference.a | grep N6paddle12experimental3add  有结果

**Comment by chenwhql** [comment]
用的哪个版本的paddle，求发个demo我试试

**Comment by engineer1109** [comment]
@chenwhql 
```
if(LINUX)
  SET(AR_LINK_FLAGS "-Wl,--whole-archive")
  SET(AR_UNDO_FLAGS "-Wl,--no-whole-archive")
  target_link_libraries(paddle_inference_shared "${AR_LINK_FLAGS} phi_function_api ${AR_UNDO_FLAGS}")
endif()
```
可以让phi_function_api 导出

**Comment by chenwhql** [comment]
或者你可以直接提个PR，我找inference的同学看看？

**Comment by engineer1109** [comment]
@chenwhql https://github.com/PaddlePaddle/Paddle/pull/47208 PR提了
用一行代码解决

**Comment by qingqing01** [comment]
@engineer1109 想问下您是在做什么工作、怎么写程序时触发的问题？

**Comment by engineer1109** [comment]
@qingqing01 
我在写自定义插件，链接libpaddle_inference.so 
调用auto out = paddle::experimental::add(x, y);发现ABI符号不存在。
nm libpaddle_inference.so | grep N6paddle12experimental3add 无结果
但是libphi_function_api.a  确实链接在libpaddle_inference.so ，但是符号被丢弃

**Comment by jiweibo** [comment]
您好，请问下您使用的是哪个版本呢？我在develop分支上测试是导出符号了的。
![image](https://user-images.githubusercontent.com/26377421/197097189-a065516d-b431-46fc-ad5b-3aa6b63cbf47.png)

**Comment by engineer1109** [comment]
@jiweibo 1c8ef38e56f0b864c323efaeacc817e31e2b8ecd 我拉了最新的编译 依然没有Symbol
编译参数
```
cmake .. -DWITH_GPU=OFF -DWITH_LITE=OFF -DWITH_CUSTOM_DEVICE=ON -DWITH_DISTRIBUTE=OFF 
```

**Comment by engineer1109** [comment]
@jiweibo 链接: https://pan.baidu.com/s/19gzMskad7Ye5q6JzqV8V9g?pwd=kech 提取码: kech
我编译的libpaddle_inference.so

**Comment by engineer1109** [comment]
@jiweibo 以前的版本我编译出来 确实是有的，最近的commit消失了

**Comment by engineer1109** [comment]
@jiweibo 其实 __attribute__((visibility("default"))) 不能保证 静态库导出的，对于链接的静态库 不使用ABI是不会导出，静态库要放在目标文件的位置才能导出

**Comment by jiweibo** [comment]
> @jiweibo 以前的版本我编译出来 确实是有的，最近的commit消失了

我本地清空build，重测下哈，看看是不是最近的改动导致的

**Comment by jiweibo** [comment]
> @jiweibo 链接: https://pan.baidu.com/s/19gzMskad7Ye5q6JzqV8V9g?pwd=kech 提取码: kech
> 我编译的libpaddle_inference.so


我从网盘这里下载的so中有`experimental::add`的符号呀。

我再确认一下哈，您需要的是动态库中有这个符号吧，静态库目前没有导出这些符号（需要通过`"-Wl,--whole-archive"`导出）。

**Comment by engineer1109** [comment]
@jiweibo 网盘那个应该传错了，没符号的应该是这个  
链接: https://pan.baidu.com/s/1PNYsdMdefU0S4fi3_lcugA?pwd=dabs 提取码: dabs

我是需要这个符号，我提交的PR https://github.com/PaddlePaddle/Paddle/pull/47208 就是保证静态库符号导出的。

**Comment by jiweibo** [comment]
> nm libpaddle_inference.so | grep N6paddle12experimental3add 无结果
> nm libpaddle_inference.a | grep N6paddle12experimental3add 有结果

我本地的测试结果和这个刚好相反。我拉下pr看下是否修复了静态库的符号问题吧

**Comment by jiweibo** [comment]
> > nm libpaddle_inference.so | grep N6paddle12experimental3add 无结果
> > nm libpaddle_inference.a | grep N6paddle12experimental3add 有结果
> 
> 我本地的测试结果和这个刚好相反。我拉下pr看下是否修复了静态库的符号问题吧

@engineer1109  我是在这个镜像内测试的`docker pull paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82`，拉取pr后仍未修复静态库的符号问题；
![image](https://user-images.githubusercontent.com/26377421/197469756-c326f810-1e41-4870-a3eb-9f444251eac9.png)


后面会修复静态库的符号问题，动态库目前测试没有发现符号问题

**Comment by engineer1109** [comment]
@jiweibo 你这个grep 结果 不是 so有符号吗？

**Comment by jiweibo** [comment]
> @jiweibo 你这个grep 结果 不是 so有符号吗？

@engineer1109  .so有符号，.a中符号缺失

**Comment by engineer1109** [comment]
@jiweibo   libpaddle_inference.a 不是保留完整符号吗？你这个图有什么问题？

**Comment by jiweibo** [comment]
> @jiweibo libpaddle_inference.a 不是保留完整符号吗？你这个图有什么问题？
@engineer1109  这里是符号缺失吧
![image](https://user-images.githubusercontent.com/26377421/197667757-1f9cb23b-a688-4906-8ad4-4f736d7e7aee.png)

**Comment by engineer1109** [comment]
@jiweibo 这个大写U少了是不影响使用的。在ELF里表示Undefined为定义的符号。一定要有T
引起的原因是本身Paddle CMake链接库的顺序和关系很混乱引起的。
引起libpaddle_inference.a 有两个相同的符号，已经定义的T 和 没有定义的 U。
在生成so或执行文件的时候，U都是要去掉的变成T，没有去掉反而会BUG了，导致没有Symbol编译不过。

**Comment by engineer1109** [comment]
@jiweibo 静态库本身是一堆.o的压缩包集合，实际上静态库没有导出的概念，也不是运行时，允许有未定义的U函数。
同时因为链接的问题（A链接B，C没有链接B但是用了B的函数, 然后再用D一起链接A和C)，可能会引入同名符号的T，和U一起共存。
简单来说，对于静态库只要有.o 和 .a 进去了，就一定能保留下来。

如果链接成so是另一回事了，gcc编译属性visibility并不能控制静态库符号的保留，必须通过$<TARGET_OBJECTS:phi_function_api> 选择性保留静态库的符号，或者调用静态库的函数。
链接的时候，通常不容许存在U，发现有同名的T，就会指向T

**Comment by jiweibo** [comment]
> @jiweibo 静态库本身是一堆.o的压缩包集合，实际上静态库没有导出的概念，也不是运行时，允许有未定义的U函数。 同时因为链接的问题（A链接B，C没有链接B但是用了B的函数, 然后再用D一起链接A和C)，可能会引入同名符号的T，和U一起共存。 简单来说，对于静态库只要有.o 和 .a 进去了，就一定能保留下来。


@engineer1109 
ok，.a中T和U共存不影响使用；.so中本地测试正常，但你的环境编出的.so有问题，我微信加下你问下具体的复现环境吧。

**Comment by jiweibo** [comment]
经验证`WITH_GPU=OFF`情况下so符号未导出，https://github.com/PaddlePaddle/Paddle/pull/47208 修复此问题

**Comment by engineer1109** [comment]
https://github.com/PaddlePaddle/Paddle/pull/47208 merged   可能还有其他未导出接口
