### ISSUE TITLE
关于from_dlpack

### ISSUE THREAD

**Issue by zsy0828** [PaddlePaddle/Paddle#47171]
### bug描述 Describe the Bug

将dlpack的数据循环传入paddle的Tensor，不会释放内存， torch，tensorflow均不会出现该问题

```python
import cupy as cp

def test1():
    print("using paddle")
    from paddle.utils.dlpack import from_dlpack
    for i in range(100):
        a = cp.random.random((1024*128, 1024), dtype=cp.float32)
        b = from_dlpack(a.toDlpack())
        print(i)
def test0():
    for i in range(100):
        a = cp.random.random((1024*128, 1024), dtype=cp.float32)
def test2():
    from torch import from_dlpack
    print("using torch")
    for i in range(100):
        a = cp.random.random((1024*128, 1024), dtype=cp.float32)
        b = from_dlpack(a.toDlpack())

```

### 其他补充信息 Additional Supplementary Information

paddle-gpu == 2.3.2
cupy == 11.2
torch == 1.10.0 / 1.12.0
cuda 11.2 / 11.6
GPU ： 3090/ 1080Ti
Ubuntu 1804

**Comment by GuoxiaWang** [comment]
问题已收到，相关同学会跟进

**Comment by zsy0828** [comment]
> 问题已收到，相关同学会跟进
你好，请问近期能够解决该bug么

**Comment by zsy0828** [comment]
你好，请问近期能够解决该问题么 @GuoxiaWang

**Comment by DesmonDay** [comment]
问题已定位了，预计明天提PR到Paddle哈。

**Comment by zsy0828** [comment]
你好，我今天安装了nightly和stable两个版本，但这个bug均未能解决，还是相同的代码 @GuoxiaWang ， 我应该怎样测试最新的paddle呢

**Comment by DesmonDay** [comment]
嗯嗯，你现在可以重新安装nightly的版本了，测试过是ok的。之前之所以不行可能是代码合进去没多久，whl包还没来得及更新。
