### ISSUE TITLE
[MKLDNN] Will squeeze, reshape, and flatten mkldnn kernels be enabled in fluid in the near future?

### ISSUE THREAD

**Issue by jiahy0825** [PaddlePaddle/Paddle#47173]
### 请提出你的问题 Please ask your question

`Squeeze`, `reshape`, and `flatten` mkldnn kernels are registered in `fluid` (See `fluid/operators/mkldnn/reshape_mkldnn_op.cc line 427-522`). But they can never be called because `GetExpectedKernelType` lost corresponding kernel selection codes.

Will `squeeze`, `reshape`, and `flatten` mkldnn kernels be enabled in fluid in the near future? Or can they be deleted directly?

**Comment by sfraczek** [comment]
@jakpiase

**Comment by jakpiase** [comment]
Hi @jiahy0825. These kernel were disabled due to some bugs, but we are going to fix and re-enable them in the near future, so please don't delete them.
