### ISSUE TITLE
DataLoader的速度问题

### ISSUE THREAD

**Issue by zsy0828** [PaddlePaddle/Paddle#47185]
### 请提出你的问题 Please ask your question

相较于tensorflow，和torch，为什么paddle的dataloader速度会满这么多，比如20w个，batch_size为1024，需要至少5s的时间，而tf与th则仅需要不到1s的时间，是因为，内部由np实现的问题么？如果是的话，能否在后续的版本对其加速呢

**Comment by GuoxiaWang** [comment]
请问你这个速度对比，有最小复现代码吗？

**Comment by zsy0828** [comment]
> 请问你这个速度对比，有最小复现代码吗？

你好，后续看了一下，貌似需要使用numpy作为dataset，不能直接使用pd.Tensor作为输入，对不起，没太仔细看文档
