### ISSUE TITLE
Record warning and other level log message in Op

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#4718]
For now, there is only `PADDLE_ENFORCE` to check invalid inputs. But sometimes I just want to record some warning message...

**Comment by lcy-seso** [comment]
Support.

In some cases, some not significant problem can be automatically corrected by the operator itself, but if this happens, it is better to throw a warning information to the users to remind them.

**Comment by Yancey1989** [comment]
We can use GLOG to print the logs message as the specified level, such as:
```bash
VLOG(3) << "This is a log message."
```

And I'll close this issue.
