### ISSUE TITLE
Are `paddle.gather` and `paddle.index_select` functionally the same?

### ISSUE THREAD

**Issue by Bobholamovic** [PaddlePaddle/Paddle#47188]
### 请提出你的问题 Please ask your question

I've found that `paddle.gather` and `paddle.index_select` seem to behave very similarly, as they both take an input tensor and a 1-D index tensor and performs a look-up based on the input and the index (which is much like `torch.index_select`). My question is, are these two APIs essentially the same? p.s. I know there are notable differences between `paddle.gather` and `torch.gather`.

**Comment by GuoxiaWang** [comment]
torch.gather -> paddle.take_along_axis

torch. index_select  -> paddle. index_select

**Comment by Bobholamovic** [comment]
Thanks for your answer. But my question is, what is the difference between `paddle.gather` and `paddle.index_select`？

**Comment by GuoxiaWang** [comment]
The difference is the data dtype:

`index_select` supports `['float32', 'float64', 'int32', 'int64']`
`gather` supports `'float16', 'float32', 'float64', 'int16', 'int32', 'int64', 'uint8'`

**Comment by Bobholamovic** [comment]
Thank you!
