### ISSUE TITLE
random_walk

### ISSUE THREAD

**Issue by qqxze** [PaddlePaddle/Paddle#47195]
### bug描述 Describe the Bug

复现https://github.com/PaddlePaddle/PGL/tree/main/legacy/examples/GATNE Dataset.py代码时 
报 type object 'Graph' has no attribute 'random_walk' 
paddlepaddle        2.1.2
pgl                 2.2.2

**Comment by zhangbo9674** [comment]
您好，这个是legacy的，要用PGL 1.x版本 配 PaddlePaddle 1.8.5。
