### ISSUE TITLE
Paddle Quick Start预处理亚马逊数据报错 

### ISSUE THREAD

**Issue by DrakeNi** [PaddlePaddle/Paddle#472]
基于一键打包工具安装的paddle，在运行idl/paddle/Paddle/demo/quick_start/preprocess.sh时报python import 包错误，如 下图：
![image](https://cloud.githubusercontent.com/assets/3113944/20294204/661ce752-ab37-11e6-8a8a-d5a07f07f7e9.png)
感觉是打包的这个python没有依赖的库， 基于jumbo的python处理过没有问题， 但是在做predict时，jumbo的python 也无法工作

**Comment by reyoung** [comment]
这其实是Python的问题。你的机器shared memory不能被这个用户读写，所以python的multiprocessing.Queue用不了。而quick start的样例中，数据预处理使用了这个包。

解法是，用root将这台机器的shared memory变成可读的。

```bash
chmod a+rwx /dev/shm/
```

**Comment by DrakeNi** [comment]
但是过去基于jumbo的python预处理，没有这个问题，如果机器没有root权限，有其它解决方案么？

**Comment by reyoung** [comment]
@DrakeNi 请调用一下`ls -l /dev/shm`，看看是不是有读写权限。

如果是有读写权限的，那么再看一下python问题。

**Comment by DrakeNi** [comment]
执行了，是空的， 
total 0

**Comment by DrakeNi** [comment]
并且刚权限已经加过了

**Comment by backyes** [comment]
@DrakeNi 初步定位可能是python解释器的问题，后续 @reyoung 会提供一个新的python解释替换一键安装里的python解释器。

**Comment by HugoLian** [comment]
我也遇到了同样的问题，希望解决之后可以有通知，非常感谢。

**Comment by backyes** [comment]
@HugoLian @DrakeNi 
在正式fix这个bug的方法出来前，你们可以通过以下方法先临时解决你的问题

*  注释掉~/.bashrc  中最后几行Paddle的环境变量，然后relogin ssh
* 再执行sh preprocess,

上述动作本质上在跳过Paddle自带的python解释器，使用系统默认的python解释器。待预处理结束后，重新使能~/.bashrc 中环境变量，并source ~/.bashrc， 然后再运行后续流程。

BTW：文档里描述了一键安装的卸载过程，https://github.com/baidu/Paddle/issues/475 也提到了。

**Comment by wen-bo-yang** [comment]
@DrakeNi 我遇到过3770关于multiprocessing错我，一下是我在自己机器上linux centos4.3机器上的解决方案

如果你在使用时看到如下提示:
ImportError: This platform lacks a functioning sem_open implementation, therefore, the required synchronization primitives needed will not function, see issue 3770.
这个是因为机器上的 /dev/shm 未挂载或权限不足, 而 Linux 下 sem_open 是需要往 /dev/shm 下写入内容的.
mount | grep shm
none on /dev/shm type tmpfs (rw)
如果没有挂在需要重新挂载
用 root 权限修改 /etc/fstab 查看是否下方的内容在你的文件中备注是，如果是请打开
none                    /dev/shm                tmpfs   defaults        0 0
用 root 权限 chmod 777 /dev/shm
重新安装python
如果是自己编译安装的话需要确认HAVE_SEM_OPEN这项等于0
https://bugs.python.org/issue3770

**Comment by wen-bo-yang** [comment]
@DrakeNi 
我在linux centos 6.3系统上遇到过此类问题3770(python  multiprocessing)，以下是解决问题的过程，希望能帮到你

这个是因为机器上的 /dev/shm 未挂载或权限不足, 而 Linux 下 sem_open 是需要往 /dev/shm 下写入内容的.
mount | grep shm
会产看到你是否挂在了下方的设备
none on /dev/shm type tmpfs (rw)
如果没有挂在需要重新挂载
用 root 权限修改 /etc/fstab 查看是否下方的内容在你的文件中被注释掉，如果是请打开
none                    /dev/shm                tmpfs   defaults        0 0
用 root 权限 chmod 777 /dev/shm
重新安装python
如果是自己编译安装的话需要确认HAVE_SEM_OPEN这项等于0
https://bugs.python.org/issue3770

希望对你有帮助

**Comment by hohdiy** [comment]
绕过去的方案亲测有效。

**Comment by George-Huang** [comment]
@backyes 
尝试了你的先注释掉~/.bashrc的方案。
但又出现了如下错误：
Traceback (most recent call last):
  File "preprocess.py", line 40, in <module>
    parse_queue = Queue(maxsize=max_queue_size + num_tokenize)
  File "/home/vis/anaconda/lib/python2.7/multiprocessing/__init__.py", line 218, in Queue
    return Queue(maxsize)
  File "/home/vis/anaconda/lib/python2.7/multiprocessing/queues.py", line 63, in __init__
    self._rlock = Lock()
  File "/home/vis/anaconda/lib/python2.7/multiprocessing/synchronize.py", line 147, in __init__
    SemLock.__init__(self, SEMAPHORE, 1, 1)
  File "/home/vis/anaconda/lib/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 13] Permission denied

请问有办法解决吗？

P.S.
我在服务器上运行程序，没有root权限。
谢谢～

**Comment by backyes** [comment]
@George-Huang 

这应该是一个python general的问题，跟paddle关系不大。不过具体解决方法参考下 @reyoung 在前面给出的解决方法。

> 这其实是Python的问题。你的机器shared memory不能被这个用户读写，所以python的multiprocessing.Queue用不了。而quick start的样例中，数据预处理使用了这个包。

> 解法是，用root将这台机器的shared memory变成可读的。

> ```bash
chmod a+rwx /dev/shm/
```

**Comment by George-Huang** [comment]
@backyes 
主要是我没有root权限，所以
chmod a+rwx /dev/shm/
这条命令无法执行呀。

**Comment by donote** [comment]
已经验证 通过chmod无效，jumbo自动的python没有问题

**Comment by donote** [comment]
用root权限执行预处理脚本OK

**Comment by donote** [comment]
使用这种方法ok了，一定要relogin ssh
--------------
@HugoLian @DrakeNi
在正式fix这个bug的方法出来前，你们可以通过以下方法先临时解决你的问题

注释掉~/.bashrc 中最后几行Paddle的环境变量，然后relogin ssh
再执行sh preprocess,
上述动作本质上在跳过Paddle自带的python解释器，使用系统默认的python解释器。待预处理结束后，重新使能~/.bashrc 中环境变量，并source ~/.bashrc， 然后再运行后续流程。

BTW：文档里描述了一键安装的卸载过程，#475 也提到了。
