### ISSUE TITLE
分布式在多机部署时，进行分布式环境验证时出错

### ISSUE THREAD

**Issue by Eddie-zhg** [PaddlePaddle/Paddle#47215]
### 请提出你的问题 Please ask your question

在第一台机子输入指令：
![2022-10-20 15-44-49屏幕截图](https://user-images.githubusercontent.com/82798516/196888497-2c991ad6-2b9e-4e12-81e5-360d7f98b975.png)
在第二台机子输入指令后，第一台机子显示如下：
![2022-10-20 15-45-06屏幕截图](https://user-images.githubusercontent.com/82798516/196888636-01af1bf9-d46f-46f1-b31f-55eb56b255b7.png)
已经检查了网络连接，都是正常的。
希望得到解答！

**Comment by wuhuachaocoding** [comment]
您好，报错提示没有run_check这个file， 这样用的话，请先确定run_check是个运行脚本。
单机可以这样检测：
```
import paddle
paddle.utils.run_check()
```
您可以把这个函数抽出一个脚本出来， 然后用launch启动这个脚本在多机上执行，前提是launch后面跟的是一个运行脚本。

**Comment by Eddie-zhg** [comment]
> 您好，报错提示没有run_check这个file， 这样用的话，请先确定run_check是个运行脚本。 单机可以这样检测：
> 
> ```
> import paddle
> paddle.utils.run_check()
> ```
> 
> 您可以把这个函数抽出一个脚本出来， 然后用launch启动这个脚本在多机上执行，前提是launch后面跟的是一个运行脚本。

![2022-10-20 16-30-50屏幕截图](https://user-images.githubusercontent.com/82798516/196898187-0434d2c4-8035-41e4-863b-37c22a85fa68.png)
单机检测的没问题。
“把这个函数抽出一个脚本出来“我不太明白这个是啥意思

**Comment by wuhuachaocoding** [comment]
首先单机检测没问题就正常。
其次，你是想通过paddle.distributed.launch运行多机的检测情况，但是paddle.distributed.launch后面应该接一个运行的python脚本，比如：python -m paddle.distributed.launch train.py

你直接在后面接一个run_check, 报错信息显示没有run_check这个东西，你得先创建一个run_check脚本把

**Comment by Eddie-zhg** [comment]
![2022-10-20 16-58-11屏幕截图](https://user-images.githubusercontent.com/82798516/196904489-1bc91ffa-3b78-47b0-b25e-9daae2c31703.png)
这样子弄了一个，还是一样的错误。
我不太会，这个run_check需要怎么写呢？麻烦您啦！

**Comment by wuhuachaocoding** [comment]
python -m paddle.distributed.launch  --nnode....   run_check.py
后面跟上你写的这个run_check.py

**Comment by Eddie-zhg** [comment]
> python -m paddle.distributed.launch --nnode.... run_check.py 后面跟上你写的这个run_check.py
解决了 感谢！
