### ISSUE TITLE
Scope::NewVar() not reflecting its implementation.

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#4722]
I think `NewVar` is not a appropriate name. When I first read the name: `NewVar`, I think it will create a new var, or fail. Not expecting that it will return a created var.

Here is the implementation of `NewVar`:

https://github.com/PaddlePaddle/Paddle/blob/c3bf332666bffb009a38bb568198e71673ff48d0/paddle/framework/scope.cc#L34-L43

`NewVar` does not create a new var every time, and does not return an error if no new var is created. `Var` seems to be a better name.

**Comment by wangkuiyi** [comment]
Is there a problem with the convetion that NewVar actually does get-or-create?

**Comment by helinwang** [comment]
When I first read the name: `NewVar`, I think it will create a new var, or fail. Not expecting that it will return a created var.

**Comment by wangkuiyi** [comment]
After looking at the following names for a while

Var
GetVar
NewVar
GetOrNewVar

How about we just rename NewVar into Var?
