### ISSUE TITLE
Paddle Inference X86的推理库

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle#47258]
### 请提出你的问题 Please ask your question

请问在paddle Inference推理库的网页中是否有提供X86平台的CPU推理库呢？

**Comment by ronny1996** [comment]
你好，有提供的

https://paddle-inference.readthedocs.io/en/latest/guides/install/download_lib.html#c

**Comment by fanxiaochen456** [comment]
@ronny1996 您好，我使用
![屏幕截图 2022-10-22 152529](https://user-images.githubusercontent.com/101849755/197326404-9367cf3d-ad19-4115-8b65-69772afb286d.png)
图片中的第一个推理库编译paddlex的时候他出现了X64的包与X86平台不兼容的字样

**Comment by fanxiaochen456** [comment]
![微信图片_20221022152747](https://user-images.githubusercontent.com/101849755/197326500-1f5b36be-e8fd-4c46-af7e-4768838d6620.png)
![屏幕截图 2022-10-22 152529](https://user-images.githubusercontent.com/101849755/197326502-a5a70c3b-a1a5-4527-b4a3-76ab4f39e0d6.png)

**Comment by ronny1996** [comment]
那应该是没有提供x86的预编译库，需要自己编译下
