### ISSUE TITLE
硬件配置问题

### ISSUE THREAD

**Issue by AlphaMind123** [PaddlePaddle/Paddle#47257]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/108966996/197324588-207eeb98-86af-47c5-9a9a-c5e6a068b5d3.png)
为什么会这样，我已经安装了cuda11.6和cudn8.6

**Comment by ronny1996** [comment]
这个API目前是paddle custom device使用的

**Comment by AlphaMind123** [comment]
> 这个API目前是paddle custom device使用的
可是还是空的
![image](https://user-images.githubusercontent.com/108966996/197326141-327792d8-83b0-491e-9249-f224183bfd9e.png)

可是还是为空呀我调用api使用也不行是为什么呢
![image](https://user-images.githubusercontent.com/108966996/197326127-88758d93-f266-4f4e-b75c-fc7bfb663e5e.png)

**Comment by ronny1996** [comment]
![image](https://user-images.githubusercontent.com/25691046/197331218-43594d95-dab6-4653-bf30-dcb3ff2df54a.png)
你好，目前这两个api都是用来查询自定义硬件后端的，用来配合这个repo使用npu，mlu的后端 https://github.com/PaddlePaddle/PaddleCustomDevice

报错信息显示的是找不到 zlibwapi.dll，确保该dll所在目录在path环境变量中
![image](https://user-images.githubusercontent.com/25691046/197331350-71469353-2fce-4d47-82d6-a2d5895789aa.png)

**Comment by AlphaMind123** [comment]
是不是cuda版本太高了


| |
hfqemail
|
|
***@***.***
|
---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2022年10月22日 17:13 |
| 收件人 | ***@***.***> |
| 抄送人 | ***@***.***> ,
***@***.***> |
| 主题 | Re: [PaddlePaddle/Paddle] 硬件配置问题 (Issue #47257) |


你好，目前这两个api都是用来查询自定义硬件后端的，用来配合这个repo使用npu，mlu的后端 https://github.com/PaddlePaddle/PaddleCustomDevice

报错信息显示的是找不到 zlibwapi.dll，确保该dll所在目录在path环境变量中

**Comment by ronny1996** [comment]
paddle安装的是对应cuda11.6的版本吗？安装命令是什么？
