### ISSUE TITLE
请问怎么把动态图转成静态图？

### ISSUE THREAD

**Issue by georgewei** [PaddlePaddle/Paddle#47267]
### 请问怎么把动态图转成静态图？

参考官网文档的 [案例解析](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/case_analysis_cn.html) 的第九部分“jit.save 与默认参数”，我整理了个 python 脚本如下：

```
import paddle
import paddle.nn as nn
from paddle.static import InputSpec

IMAGE_SIZE = 784
CLASS_NUM = 10

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    def forward(self, x):
        return self._linear(x)

# Dynamic model path
src_path = "./det_pcb/best_accuracy.pdparams"
paddle.load(src_path)

layer = LinearNet()
layer = paddle.jit.to_static(layer, input_spec=[InputSpec(shape=[None, IMAGE_SIZE], dtype='float32')])

# Converted static model path
target_path = "./det_pcb_inferrence"
paddle.jit.save(layer, target_path)
```

其中：
src_path是需要转换的动态图路径。脚本中该图是从《PaddleOCR开源大礼包》的OCR场景应用模型库/pcb字符识别/best_model_pcb.tar中解压出来的
target_path是转换后的静态图路径

执行以上脚本后报错：

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
>     func(layer, path, input_spec, **configs)
>   File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
>     concrete_program = static_func.concrete_program_specify_input_spec(
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
>     concrete_program, _ = self.get_concrete_program(
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 421, in get_concrete_program
>     args, kwargs = self._function_spec.unified_args_and_kwargs(args,
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/function_spec.py", line 82, in unified_args_and_kwargs
>     raise ValueError(error_msg)
> ValueError: The decorated function `forward` requires 0 arguments: [], but received 1 with (InputSpec(shape=(-1, 784), dtype=paddle.float32, name=None),).

**Comment by georgewei** [comment]
重新检查下代码，发现执行到def forward(self, x):报错了：

> >>> import paddle
> >>> import paddle.nn as nn
> >>> from paddle.static import InputSpec
> >>> 
> >>> IMAGE_SIZE = 784
> >>> CLASS_NUM = 10
> >>> 
> >>> class LinearNet(nn.Layer):
> ...     def __init__(self):
> ...         super(LinearNet, self).__init__()
> ...         self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)
> ... 
> >>>     def forward(self, x):
>   File "&lt;stdin>", line 1
>     def forward(self, x):
> IndentationError: unexpected indent
> >>>         return self._linear(x)
>   File "&lt;stdin>", line 1
>     return self._linear(x)
> IndentationError: unexpected indent

修改脚本如下（仅删除了def forward(self, x):前的空行）：

```
import paddle
import paddle.nn as nn
from paddle.static import InputSpec

IMAGE_SIZE = 784
CLASS_NUM = 10

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)
    def forward(self, x):
        return self._linear(x)

# Dynamic model path
src_path = "./det_pcb/best_accuracy.pdparams"
paddle.load(src_path)

layer = LinearNet()
layer = paddle.jit.to_static(layer, input_spec=[InputSpec(shape=[None, IMAGE_SIZE], dtype='float32')])

# Converted static model path
target_path = "./det_pcb_inferrence"
paddle.jit.save(layer, target_path)
```

重新执行报错如下：

> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
>     func(layer, path, input_spec, **configs)
>   File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/jit.py", line 860, in save
>     concrete_program = static_func.concrete_program_specify_input_spec(
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 527, in concrete_program_specify_input_spec
>     concrete_program, _ = self.get_concrete_program(
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
>     concrete_program, partial_program_layer = self._program_cache[cache_key]
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
>     self._caches[item_id] = self._build_once(item)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 785, in _build_once
>     concrete_program = ConcreteProgram.from_func_spec(
>   File "/usr/local/lib/python3.9/site-packages/decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 694, in from_func_spec
>     static_func = convert_to_static(dygraph_function)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 140, in convert_to_static
>     static_func = _FUNCTION_CACHE.convert_with_cache(function)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 77, in convert_with_cache
>     static_func = self._convert(func)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 104, in _convert
>     source_code = func_to_source_code(func)
>   File "/usr/local/lib/python3.9/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 550, in func_to_source_code
>     source_code_list, _ = inspect.getsourcelines(function)
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 1006, in getsourcelines
>     lines, lnum = findsource(object)
>   File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/inspect.py", line 835, in findsource
>     raise OSError('could not get source code')
> OSError: could not get source code

**Comment by CtfGo** [comment]
你好，请问你的需求是想把src_path的动态图load之后转换为静态图再save吗？定义LinearNet是什么目的呢

**Comment by georgewei** [comment]
> 你好，请问你的需求是想把src_path的动态图load之后转换为静态图再save吗？定义LinearNet是什么目的呢

是的。手上只有动态图的三个文件，没有其它资料。不知道怎么转，找资料的过程中看到 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/case_analysis_cn.html 的示例代码，就拿来试一试，看来是生搬硬套了。请指点。

**Comment by yeyupiaoling** [comment]
我用你的代码是完全能够正常导出的。
你看那看是不是PaddlePaddle版本问题，我的是2.3.2

```python
import paddle
import paddle.nn as nn
from paddle.static import InputSpec

IMAGE_SIZE = 784
CLASS_NUM = 10

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    def forward(self, x):
        return self._linear(x)

# Dynamic model path
# src_path = "./best_accuracy.pdparams"
# paddle.load(src_path)

layer = LinearNet()
layer = paddle.jit.to_static(layer, input_spec=[InputSpec(shape=[None, IMAGE_SIZE], dtype='float32')])

# Converted static model path
target_path = "./det_pcb_inferrence"
paddle.jit.save(layer, target_path)
```

**Comment by georgewei** [comment]
@yeyupiaoling 是不是加载动态图的方法有问题？我只有动态图的三个文件，没有其它资料。这种情况下该怎么加载呢？

> $ ls -l det_pcb
> total 14472
> -rw-r--r--  1 george  staff  4909039 Jun 23 21:10 best_accuracy.pdopt
> -rw-r--r--  1 george  staff  2493897 Jun 23 21:10 best_accuracy.pdparams
> -rw-r--r--  1 george  staff      178 Jun 23 21:10 best_accuracy.states

**Comment by yeyupiaoling** [comment]
他们分别是：优化方法的参数、模型的参数、训练状态的记录。

**Comment by yeyupiaoling** [comment]
如果你只有这三个文件，是无法导出模型的，要有模型文件。

**Comment by georgewei** [comment]
@yeyupiaoling 谢谢。在PaddleOCR交流群里得到解答，使用tools/export_model.py，指定配置文件后可以导出
