### ISSUE TITLE
飞桨PaddleSpeech语音技术课程系列——语音合成实践项目出错

### ISSUE THREAD

**Issue by Superman-Valencia** [PaddlePaddle/Paddle#47260]
在import包时，出现以下错误：
<img width="788" alt="image" src="https://user-images.githubusercontent.com/70886521/197329721-97562281-e34e-4d3a-91fa-13f1e75c2f03.png">

**Comment by ronny1996** [comment]
请问是不是使用 python3.5 安装的  python3.7的paddle

![image](https://user-images.githubusercontent.com/25691046/197331075-7510ebce-7b56-428c-9679-bf2778572773.png)

**Comment by Superman-Valencia** [comment]
是在notebook下运行的，请问这种情况如何解决？

**Comment by ronny1996** [comment]
要不试试conda环境也用py3.7
