### ISSUE TITLE
DeprecationWarning: `np.bool` is a deprecated

### ISSUE THREAD

**Issue by O-O1024** [PaddlePaddle/Paddle#47272]
不想看到一大串提示，框架更新一下一劳永逸

版本：2.3
```C:\Users\admin\AppData\Roaming\Python\Python38\site-packages\paddle\fluid\framework.py:1104: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.```

**Comment by yeyupiaoling** [comment]
附议

**Comment by gglin001** [comment]
+1

**Comment by ZzSean** [comment]
你好，感谢您对PaddlePaddle的使用提出建议！这些多余的warning信息在https://github.com/PaddlePaddle/Paddle/pull/42929 中已经修复，请尝试使用最新版本的PaddlePaddle，应该不会再出现类似warning信息，谢谢！
