### ISSUE TITLE
cuda11.8支持？

### ISSUE THREAD

**Issue by MarginGitHub** [PaddlePaddle/Paddle#47274]
### 请提出你的问题 Please ask your question

十月cuda11.8已经发布了，支持最新的GPU，请问Paddle官方有计划何时进行适配吗？

**Comment by ZzSean** [comment]
你好，在下个月的release2.4中会支持CUDA11.7。CUDA11.8由于是新版本，在进行充分地评估和测试后，可能会在后续版本中考虑增加支持，您也可以尝试本地编译CUDA11.8，但是可能会存在一些未知问题，所以还是建议使用CUDA11.8以下的版本，感谢您的持续关注！
