### ISSUE TITLE
paddle安装问题

### ISSUE THREAD

**Issue by jingmingtao** [PaddlePaddle/Paddle#47279]
### 问题描述 Please describe your issue

![image](https://user-images.githubusercontent.com/114384977/197443161-a407f500-9b34-4131-b2b8-5505c200ab1d.png)
困扰了我两天了，求解决，万分感谢，我安装的cuda是11.8，python3.9，cudnn8.6

**Comment by jingmingtao** [comment]
尝试了很好不同的版本，就是不可以，请求大佬支援

**Comment by ZzSean** [comment]
你好，请问设置LD_LKIBRARY_PATH=cuda/cudnn安装lib目录也不可以吗？CUDA11.8当前官方仍不支持，所以可能会存在未知问题，可以尝试降低CUDA版本

**Comment by hailiang-wang** [comment]
CUDA11.8 大约什么时候可以支持?

从官方文档中，还是最高支持到 11.6，https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

![image](https://user-images.githubusercontent.com/3538629/200104142-c0e00129-c52c-4523-8992-7503f40e73d2.png)

**Comment by dingjiaweiww** [comment]
release2.4 已经支持CUDA11.7。CUDA11.8由于是新版本，在进行充分地评估和测试后，可能会在后续版本中考虑增加支持，您也可以尝试本地编译CUDA11.8，感谢您的持续关注！
