### ISSUE TITLE
PPYOLOE-L转ONNX输出batch是-1

### ISSUE THREAD

**Issue by 392875** [PaddlePaddle/Paddle#47276]
### 请提出你的问题 Please ask your question

PPYOLOE-L转ONNX输出batch是-1，按照官方给的文档出来的结果input也是-1，更改了用paddle_infer_shape.py输入变成1，但结果依然没有改变

**Comment by XYZ-916** [comment]
> input
batch_size是-1表示模型输入batch_size可以外部指定的。

**Comment by 392875** [comment]
> 

是的，输入指定成功了，但是输出呢？输出还是-1或者unk__6
![image](https://user-images.githubusercontent.com/110003144/197459804-218187b3-ec0d-48d8-80ab-3a7dbf904d25.png)

**Comment by XYZ-916** [comment]
> Author

输出的shape是不是在推理的时候才能确定。

**Comment by 392875** [comment]
> > Author
> 
> 输出的shape是不是在推理的时候才能确定。

paddle转换onnx的时候就已经输出模型了
![image](https://user-images.githubusercontent.com/110003144/197462202-fe148074-4270-4085-8465-2892cd19c63d.png)

在这里改变输入为1，3，640，640，转换模型，output结果batch就是unk__6(这里不能导出1？？？？)

**Comment by XYZ-916** [comment]
> > > Author
> > 
> > 
> > 输出的shape是不是在推理的时候才能确定。
> 
> paddle转换onnx的时候就已经输出模型了 ![image](https://user-images.githubusercontent.com/110003144/197462202-fe148074-4270-4085-8465-2892cd19c63d.png)
> 
> 在这里改变输入为1，3，640，640，转换模型，output结果batch就是unk__6(这里不能导出1？？？？)

![image](https://user-images.githubusercontent.com/14884056/197462520-7013148c-3fc4-46e5-9cc4-717360c173a6.png)
这里多类别非极大值抑制，可能框的个数不能确定吧。

**Comment by 392875** [comment]
> > > > Author
> > > 
> > > 
> > > 输出的shape是不是在推理的时候才能确定。
> > 
> > 
> > paddle转换onnx的时候就已经输出模型了 ![image](https://user-images.githubusercontent.com/110003144/197462202-fe148074-4270-4085-8465-2892cd19c63d.png)
> > 在这里改变输入为1，3，640，640，转换模型，output结果batch就是unk__6(这里不能导出1？？？？)
> 
> ![image](https://user-images.githubusercontent.com/14884056/197462520-7013148c-3fc4-46e5-9cc4-717360c173a6.png) 这里多类别非极大值抑制，可能框的个数不能确定吧。

是需要裁剪掉一部分吗？还有什么解决办法？下游环境不支持-1

**Comment by XYZ-916** [comment]
paddle动态图模型转静态图模型的时候，exclude_nms设置为true

**Comment by 392875** [comment]
> paddle动态图模型转静态图模型的时候，exclude_nms设置为true
![image](https://user-images.githubusercontent.com/110003144/197659438-339ad1db-c0bd-4efd-bc46-df9ac2b06590.png)
![image](https://user-images.githubusercontent.com/110003144/197659479-5100c970-164f-4a60-965a-685f3586d56f.png)

嗯嗯好了
