### ISSUE TITLE
【文档-教程-零基础实践深度学习】work 路径下数据集无处寻找

### ISSUE THREAD

**Issue by gakkistyle** [PaddlePaddle/Paddle#47305]
### 请提出你的问题 Please ask your question

你好，
  在官方文档中，教程一栏的零基础实践深度学习，以下两个网页https://www.paddlepaddle.org.cn/tutorials/projectdetail/4309126 和https://www.paddlepaddle.org.cn/tutorials/projectdetail/3473063 均出现路径./work/...下的数据集引用，如下图
<img width="1197" alt="work" src="https://user-images.githubusercontent.com/41604301/197531670-5502dc77-9338-40db-955a-e8ab0e175a5b.png">
<img width="1046" alt="work2" src="https://user-images.githubusercontent.com/41604301/197531692-d5c34e89-3a96-49fc-8297-a6474eb73d59.png">

请问这个路径下的数据集是开源的吗，如果是，在哪里能获取呢？可否在文档里补充说明一下这些数据集的可获取性。

**Comment by ZzSean** [comment]
您好，这个数据集应该是开源可以获取的，我这里先放个链接，后续会补充到文档中，感谢您的反馈！
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data
目前官网的文档，是通过AI Studio镜像来的，数据集都挂在对应的项目里，可以在线直接运行，我们也是推荐这种方式来学习的哈，课程链接：https://aistudio.baidu.com/aistudio/course/introduce/1297
