### ISSUE TITLE
paddle支持JetPack 5.0.2的预测库

### ISSUE THREAD

**Issue by SunGoodIn** [PaddlePaddle/Paddle#47329]
参考了nvidia官方的l4t镜像（https://catalog.ngc.nvidia.com/orgs/nvidia/containers/l4t-ml/tags），发现没有合适的paddlepaddle预编译wheel（https://paddleinference.paddlepaddle.org.cn/master/user_guides/download_lib.html），
要么是python版本不对应，要么是Jetpack版本不对应；
是否考虑预编译一些合适的预编译wheel呢，以及支持Jetpack5.0.2 python3.8

**Comment by SunGoodIn** [comment]
上周尝试从源码编译，编译成功后引入发现不支持cuda（环境是支持cuda的并且pytorch验证正常）；
且自己编译的wheel名字：paddlepaddle-2.2.0-cp38-cp38-linux_aarch64.whl 41.6M，没有跟踪编译日志，正确编译后支持CUDA的文件名是否会携带gpu标识啊；
困扰我好久了，在线求大佬支持！！！

**Comment by cailuyu** [comment]
> 上周尝试从源码编译，编译成功后引入发现不支持cuda（环境是支持cuda的并且pytorch验证正常）； 且自己编译的wheel名字：paddlepaddle-2.2.0-cp38-cp38-linux_aarch64.whl 41.6M，没有跟踪编译日志，正确编译后支持CUDA的文件名是否会携带gpu标识啊； 困扰我好久了，在线求大佬支持！！！

编译的python whl装完带gpu后缀的,但我的包装完,引入paddle的时候宝.so文件加载失败

**Comment by chalsliu** [comment]
> 

关于编译的wheel不支持cuda的问题，请问可以发一下具体的编译方式吗 @SunGoodIn

**Comment by cailuyu** [comment]
> 
https://github.com/mingquanyuan/PaddlePaddle-Jetson
按这个基本搞定了,最后运行时有个so的缺失,自己apt安装对应软件,放到path里就搞定了
