### ISSUE TITLE
Paddle Segmentation fault SolveGradKernel

### ISSUE THREAD

**Issue by xiequnyi** [PaddlePaddle/Paddle#47335]
### 请提出你的问题 Please ask your question

使用paddle2.2框架的paddle.linalg.solve算子，训练阶段，报如下错误，请问如何解决呢？

<img width="948" alt="image" src="https://user-images.githubusercontent.com/24647238/197763745-c5d376c7-55ca-4c8a-85b0-7100e3e57edf.png">

**Comment by JamesLim-sy** [comment]
看着比较像使用`paddle.linalg.solve`算子时出现了数据类型这类的问题，报错的输入x, y配置信息有记录的话，可以单独把计算中的`paddle.linalg.solve`抽出来进行单测查询下问题.
