### ISSUE TITLE
卸载GPU版本paddle后cpu版本无法正常使用

### ISSUE THREAD

**Issue by ConleyKong** [PaddlePaddle/Paddle#47344]
### 问题描述 Issue Description

CentOS系统，同时安装了paddle的CPU版本和GPU版本，卸载GPU版本后进入python环境无法import paddle，报错说找不到模块，实际系统是存在cpu版本paddle的，但是新建conda环境仅安装cpu版本paddle的话可以导入paddle模块

### 版本&环境信息 Version & Environment Information

paddlepaddle: 2.3.2
paddlepaddle-gpu:2.3.2
os: CentOS7.9

**Comment by thisjiang** [comment]
您好！由于paddle gpu版本和cpu版本的包名都是paddle，都安装在`/usr/local/lib/python3.7/dist-packages/paddle/`目录下。当您卸载其中任意一个版本时，`/usr/local/lib/python3.7/dist-packages/paddle/`也会被同时删除，这也是您使用不了另一个版本的原因。

实际上，即使您安装的是paddle gpu版本，也是可以跑CPU模型的， 只要您在代码起始位置加入`paddle.device.set_device('cpu')`即可。为了您的使用体验，建议只安装一个版本，若想安装另一版本，请先卸载现有版本。
