### ISSUE TITLE
ExternalError: function "pd_prod_env_mat_a_cpu_forward_kernel" is not implemented for data type `float32` when run deepmd with latest Paddle/develop

### ISSUE THREAD

**Issue by yaomichael** [PaddlePaddle/Paddle#47359]
### bug描述 Describe the Bug

This issue is created as a follow-up of https://github.com/PaddlePaddle/Paddle/issues/45058 where the original error was root caused (by #44365) and fixed by #45770. Unfortunately, the changes between these two commits introduced another error as described in https://github.com/PaddlePaddle/Paddle/issues/45058#issuecomment-1289829832

with commit [23def39672](https://github.com/PaddlePaddle/Paddle/commit/23def39672) ，error reported is following listed here:

```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Run()
1   paddle::AnalysisPredictor::ZeroCopyRun()
2   paddle::framework::NaiveExecutor::Run()
3   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
5   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
6   std::function<void (paddle::framework::ExecutionContext const&)>::operator()(paddle::framework::ExecutionContext const&) const
7   phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
8   phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ExternalError: function "pd_prod_env_mat_a_cpu_forward_kernel" is not implemented for data type `float32`
  [/home/paddle-deepmd/source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc:269] (at /home/Paddle/paddle/fluid/framework/custom_operator.cc:302)
  [operator < prod_env_mat_a > error]
Aborted (core dumped)
```
I closed the original #45058 and created this one for the new error and another #47357 for accuracy issue. "one ticket for one problem"

**Comment by thisjiang** [comment]
It's seems the kernel of operator `prod_env_mat_a` did not support data type `float32`, could you check whether the `InferDtypeFn` of `prod_env_mat_a` support `float` if the `prod_env_mat_a` was written by custom operator, or `PD_REGISTER_KERNEL(prod_env_mat_a` if the `prod_env_mat_a` was written by  inner operator(will, but I cannot find this operator in source code).

**Comment by leeleolay** [comment]
the custom op is located is this repo and the link is followed by
https://github.com/X4Science/paddle-deepmd/blob/paddle_progress/source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc

**Comment by thisjiang** [comment]
The `NAME` in `PD_DISPATCH_FLOATING_TYPES(TYPE, NAME, ...)` should be the same as function name, that means the code should be:
```
PD_DISPATCH_FLOATING_TYPES(
      coord_tensor.type(), "PdProdEnvMatAOpCPUForwardKernel", ([&] {
        PdProdEnvMatAOpCPUForwardKernel<data_t>(
``` 

The code at:
https://github.com/X4Science/paddle-deepmd/blob/paddle_progress/source/op/paddle_ops/srcs/pd_prod_env_mat_multi_devices_cpu.cc#L256

**Comment by thisjiang** [comment]
Did you confuse the train mode and infer mode? Their API are different, particularly the custom operator . See detail from: https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#suanzizaituilichangjingzhongdeshiyong .

**Comment by thisjiang** [comment]
Or you can try remove `PD_DISPATCH_FLOATING_TYPES` and replaced by:
```
switch(x.type()) {
  case paddle::DataType::FLOAT32:
    PdProdEnvMatAOpCPUForwardKernel<float>(
            ...);
    break;
  case paddle::DataType::FLOAT64:
    PdProdEnvMatAOpCPUForwardKernel <double>(
            ...);
    break;
  default:
    PD_THROW(
      "function pd_prod_env_mat_a_cpu_forward_kernel is not implemented for data type `",
      paddle::ToString(x.type()), "`");
}
```
ref to  https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#cpu .
And more radically:
```
PdProdEnvMatAOpCPUForwardKernel(
            ...,
            descrpt_tensor.mutable_data<float>(),
            ...);
```
