### ISSUE TITLE
请问pytorch里model._modules这种写法，在paddle里对应的是什么

### ISSUE THREAD

**Issue by Reneea1** [PaddlePaddle/Paddle#47361]
请问pytorch里model._modules这种写法，在paddle里对应的是什么？例如这一行的操作：
https://github.com/salesforce/BLIP/blob/main/models/blip_pretrain.py#L297

**Comment by thisjiang** [comment]
根据源码分析，该接口应该与paddle中的[`Layer._sub_layers`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/dygraph/layers.py#L150)类似。
