### ISSUE TITLE
CUDA 11.8 编译出错

### ISSUE THREAD

**Issue by lileding** [PaddlePaddle/Paddle#47384]
### 问题描述 Issue Description

使用develop分支编译cuda版出现nvcc的编译错误
辛苦开发组给一些线索，我可以自己调试和编码

编译对象：paddle/phi/kernels/funcs/matrix_reduce.cu
错误提示：/opt/cuda/targets/x86_64-linux/include/thrust/system/cuda/detail/scan_by_key.h(905): error: identifier "CUB_TARGET_ALLOWS_DEVICE_SYNC" is undefined

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: commit 016766cc89fabc10181453ce70b701dd8ed019f6
Paddle With CUDA: None

OS: Gentoo 2.8
Python version: 3.10.8

CUDA version: 11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: 8.6.0
Nvidia driver version: 520.56.06
****************************************
gcc version 11.3.0 (Gentoo 11.3.0 p4)

**Comment by thisjiang** [comment]
您好！Paddle目前最高只支持到cuda11.7，cuda11.8尚未进行适配。看报错信息应该是[cub](https://github.com/NVIDIA/cub)库同样还未适配cuda11.8导致的，建议在cuda11.7环境下进行编译安装。

**Comment by jzhang533** [comment]
NGC Container PaddlePaddle是基于cuda11.8的，如果只是直接用的话，可以试试。
https://docs.nvidia.com/deeplearning/frameworks/paddle-paddle-release-notes/rel-22-09.html#rel-22-09

**Comment by MarginGitHub** [comment]
> NGC Container PaddlePaddle是基于cuda11.8的，如果只是直接用的话，可以试试。 https://docs.nvidia.com/deeplearning/frameworks/paddle-paddle-release-notes/rel-22-09.html#rel-22-09

这个容器里面的paddle可以用于训练吗？

**Comment by jzhang533** [comment]
可以用来训练的。

**Comment by MarginGitHub** [comment]
> 可以用来训练的。

好的，非常感谢您的答复

**Comment by zlsh80826** [comment]
Hi @lileding 
這個錯誤是因為 Paddle 在 cuda11.8 安裝了 external cub, 但是跟系統內的 thrust 產生衝突，在 11.8 需要更改 cmake 來避免安裝 cub
https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/third_party.cmake#L320-L321

**Comment by MarginGitHub** [comment]
> cuda11.8 安裝了 external cub

那请问在cuda11.8上是不是不需要编译这个external cub库？

**Comment by zlsh80826** [comment]
@MarginGitHub 是的，用 cuda 自帶的 cub 和 thrust 就好

@betterpig 你能幫忙看一下 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/third_party.cmake#L320-L324 這個分支能否在 11.6/11.7 就好

**Comment by zhouwei25** [comment]
> 

如果这个分支只在11.6/11.7，就会触发另一个编译错误

**Comment by zhwesky2010** [comment]
> @MarginGitHub 是的，用 cuda 自帶的 cub 和 thrust 就好
> 
> @betterpig 你能幫忙看一下 https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/third_party.cmake#L320-L324 這個分支能否在 11.6/11.7 就好

直接使用cuda11.8自带的cub和thrust会导致编译报错
![Uploading infoflow 2023-02-02 19-09-54.png…]()

**Comment by hailiang-wang** [comment]
看官网还未支持 11.8, 问一下时间表，稳定版什么时候能支持 CUDA 11.8？
感谢。
![screenshot_20230321074515](https://user-images.githubusercontent.com/3538629/226489168-835ab25d-1f4f-4a74-80c3-111a7c9ac7bd.png)
