### ISSUE TITLE
请问下fleetrun如何简便启动多机分布式训练？

### ISSUE THREAD

**Issue by Ramlinbird** [PaddlePaddle/Paddle#47396]
### 请提出你的问题 Please ask your question

您好，关于fleetrun的使用，有两个问题想请教一下：
1）fleetrun的参数servers和workers应该分别指 参数节点、训练节点吧？不知道一般这两个的数量应该怎么设定呢？
2）我在多个docker容器上尝试了fleetrun多机分布式训练，但是每次都要手动在各个容器执行fleetrun命令，指定长长的ip:port列表字符串，很麻烦，想请教下有没有其他简便方法？我们公司的机器现在是k8s集群管理的，可以通过arena提交任务，但是不知道怎么和fleetrun结合起来。
谢谢~

paddle版本：2.3.0

**Comment by Ramlinbird** [comment]
请问下有人解答下吗？谢谢~

**Comment by kuizhiqing** [comment]
你好，fleetrun 启动的使用方式请参考[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/launch_cn.html)，fleetrun 等价于 python -m paddle.distributed.launch。

1. ps 训练中 server 和 worker 的数量需要根据业务需要自行配置。
2. fleetrun 的配置可以通过指定 master 节点自动发现 ip，自动分配端口，即在文档中重点关注 master/nnodes 两个参数。
3. k8s 上使用 paddle 建议使用 [paddle-opeartor](https://github.com/PaddleFlow/paddle-operator).

**Comment by Eddie-zhg** [comment]
> 
请问一下，这个master主节点是什么样的一个定义？
假设我两台机器部署一个最基本的参数服务器架构的分布式训练，一台是server，另一台是worker。所以应该是nnodes=2。这里设置master是一个什么概念呢？这个master就是指这一台server吗？

**Comment by Ramlinbird** [comment]
不知道有没有更具体的教程，想具体了解一下实现原理、使用方法，看了文档还是不太清楚要如何操作😂

**Comment by kuizhiqing** [comment]
> master主节点是什么样的一个定义

master 是多节点分布式训练中选取一个节点作为各个节点找到其他节点的媒介，所以在所有节点启动时设置同一个 master 即可。
