### ISSUE TITLE
paddle2.4的adamw中没有_append_decoupled_weight_decay方法

### ISSUE THREAD

**Issue by dolcexu** [PaddlePaddle/Paddle#47395]
### 请提出你的问题 Please ask your question

我们在测试paddle2.4的时候，发现adamw中缺少了_append_decoupled_weight_decay这个方法。这个方法在paddleclas-release-2.5的cae模型训练时会用到。

**Comment by GuoxiaWang** [comment]
增加``_append_decoupled_weight_decay`` 的同学在设计之初就是临时增加的，后续是要被删除的，所以在我重构 AdamW  的时候就删掉了，可以参考 PaddleNLP 的写法实现。

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/ops/optimizer/adamwdl.py
