### ISSUE TITLE
使用Kubernetes进行Paddle分布式训练思路

### ISSUE THREAD

**Issue by drinktee** [PaddlePaddle/Paddle#474]
目前我在Kubernetes上进行Paddle的分布式训练，中间遇到了几个问题与解决思路，想在这个ISSUE中与大家探讨一下。

#### 使用job

[job](http://kubernetes.io/docs/user-guide/jobs/) 是Kubernetes中的一个概念，主要代表一次性任务，任务运行结束后容器生命就结束了。我认为这符合Paddle分布式训练的使用场景。比如在一个Kubernetes集群中，我要进行一次需要10个节点的训练，那么这个job就表示这一次任务，当训练结束以后，训练结果已经保存到持久化存储上，这个job就算完成了，对应的资源会自动释放。

#### Paddle分布式训练的启动

我参考了Paddle文档中关于Cluster training的内容，看到其方法是通过SSH的方式启动每个节点的Paddle进程，这种方式并不符合Kubernetes的思路，所以我通过在Paddle容器启动时，让其运行一个启动脚来运行整个分布式训练，而不是在容器中安装sshd通过脚本进行操作。这个启动脚本主要的功能就是访问Kubernetes api,发现其他节点的IP地址，为自己分配一个trainerID(这里我直接根据IP地址进行排序，把序号作为trainerID),然后启动paddle trainer

#### pserver 与 trainer的分离

在训练时，Paddle其实启动了两类进程，pserver与trainer,如果我们直接用docker启动一个paddle容器，我们可以在容器内同时开启pserver与trainer,也能完成训练。为了配置的方便（pserver启动时并不需要知道其他节点的IP地址，trainer启动时需要知道pserver的端口以及地址），我在Kubernenets上部署时，这两个进程分别在两个容器中运行，pserver容器启动相对简单，只要早yaml文件中配好启动参数就可以运行。trainer容器就通过前文的脚本来启动。这两个容器在同一个[Pod](http://kubernetes.io/docs/user-guide/pods/)中（Pod是Kubernetes的概念，Pod是k8s的最小调度单元，Pod中的容器使用同一个net namespace，且都在同一台物理机/虚拟机上）

#### 关于训练数据的分发

关于训练数据的分发，我目前的做法是先将数据切分成N个文件（N=trainer个数），按照traineridl命名。将数据提前存放在共享存储中,然后通过(volume)[http://kubernetes.io/docs/user-guide/volumes/]挂载到容器里，训练时通过启动脚本去获得对应的数据。

##### 遇到的问题

在分布式训练时，Paddle启动每次都需要知道其他pserver的IP地址，是否需要一个服务发现机制来改善分布式训练？例如每个server启动时向一个组件去注册/获取训练信息

**Comment by wangkuiyi** [comment]
谢谢 @drinktee 发出这个issue。这样极大地方便了讨论。也便于我们把思路沉淀下来，以便其他朋友们参考。

我还在看distributed traininng那篇文档。几个小建议先记录一下：

- Kubernetes *job* 翻译为“作业”而不是“任务”比较好。通常一个作业里包括多个进程，其中一些进程被称为worker，每个worker完成一个或多个“任务”（task）。比如，在MapReduce里，master进程负责把输入文件分组，每一组被称为一个task，被master进程分配个一个map worker。每个map worker要完成多个tasks。

- Job、Pod、Volume都是Kubernetes里的概念，而且不容易一言概之，所以最好附上链接：

   1. [Kubernets jobs](http://kubernetes.io/docs/user-guide/jobs/) http://kubernetes.io/docs/user-guide/jobs/
   1. [Kubernetes pods](http://kubernetes.io/docs/user-guide/pods/) http://kubernetes.io/docs/user-guide/pods/
   1. [Kubernetes volumes](http://kubernetes.io/docs/user-guide/volumes/) http://kubernetes.io/docs/user-guide/volumes/

- 上文提到训练数据放在 volumes 里。Kubernetes支持很[多种 volumes](http://kubernetes.io/docs/user-guide/volumes/#types-of-volumes)，这里计划是放在哪种里面呢？

**Comment by backyes** [comment]
```
我参考了Paddle文档中关于Cluster training的内容，看到其方法是通过SSH的方式启动每个节点的Paddle进程，这种方式并不符合Kubernetes的思路，所以我通过在Paddle容器启动时，让其运行一个启动脚来运行整个分布式训练，而不是在容器中安装sshd通过脚本进行操作。这个启动脚本主要的功能就是访问Kubernetes api,发现其他节点的IP地址，为自己分配一个trainerID(这里我直接根据IP地址进行排序，把序号作为trainerID),然后启动paddle trainer
```
这里要考虑下， 如果要获取的是非标准网络接口IP，比如一台机器配备了多个网卡，多个网络的时候，能否在ks8环境下获取相关接口IP。

```
我在Kubernenets上部署时，这两个进程分别在两个容器中运行，pserver容器启动相对简单，
```
如果psever和trainer在两个contrainer中，要确保pserver container先于trainer container启动。

```
关于训练数据的分发，我目前的做法是先将数据切分成N个文件（N=trainer个数），按照traineridl命名。将数据提前存放在共享存储中,然后通过volume挂载到容器里，训练时通过启动脚本去获得对应的数据。
```
我理解，用户要：
* 先手动分配好数据
* 用户要从那里设置各个节点应该获取的文件列表？


```
在分布式训练时，Paddle启动每次都需要知道其他pserver的IP地址，是否需要一个服务发现机制来改善分布式训练？例如每个server启动时向一个组件去注册/获取训练信息
```
mpi平台 实际上会获取到当前job的所有ip信息，k8s有类似的机制么，主要能获取到所有nodes的ip地址即可。（比如k8s为某个job分配nodes中，有没有master的概念？）？ k8s如果已经存在你说的注册机制，那最好。

**Comment by wangkuiyi** [comment]
@backyes Kubernetes的pod的概念，供参考：

每个pod有自己的IP（pod IP），和所在机器的IP（node IP）毫无关系。在pod里运行的containers互相通信的时候，可以用`localhost`互相引用；跨越pod的通信需要使用对方pod的IP。整个过程里，应用程序无法了解node IP以及node上有多少网卡。

@backyes @drinktee 因为Kubernetes依赖etcd，是不是可以利用etcd来分配trainer id？

**Comment by backyes** [comment]
@wangkuiyi @drinktee 长期角度，要考虑下对rdma网络的支持，rdma不走tcp/ip stack，所以container还不知道是否支持？ 短期内当然不用care。

**Comment by drinktee** [comment]
> mpi平台 实际上会获取到当前job的所有ip信息，k8s有类似的机制么，主要能获取到所有nodes的ip地址即可。（比如k8s为某个job分配nodes中，有没有master的概念？）？ k8s如果已经存在你说的注册机制，那最好。

目前用的方法就是通过调用k8s的接口，查找出这个job对应的所有容器的IP地址
 
> 因为Kubernetes依赖etcd，是不是可以利用etcd来分配trainer id？

我认为直接在容器内调用k8s集群使用的etcd可能并不好，由于通过k8s部署的容器，目前想到的方法是，每个容器内的环境变量里已经有k8s apiserver的地址与端口信息，可以拼凑出接口地址直接查询Pod信息,这本质上也是通过etcd实现的。
现在这样的做法有个缺陷就是如果一个job需要大量Pod，那么在启动的时短时间内就会有大量请求访问apiserver

**Comment by tizhou86** [comment]
> 上文提到训练数据放在 volumes 里。Kubernetes支持很多种 volumes，这里计划是放在哪种里面呢？
目前我们可以放在共享存储中，百度内部是nfs，外部aws是efs，今后我们可以使用其他更为高效的分布式存储模型来使用本地磁盘。

> 在pod里运行的多个containers互相通信的时候，可以用localhost互相引用；跨越pod的通信需要使用对方pod的IP。
跨pod间通信我们需要使用容器网络来进行打通，我们现有的方案是calico。对于单主机上多张网卡的运行，我们可能需要多网卡的机器来试验我们的方案。

**Comment by tizhou86** [comment]
> 我认为直接在容器内调用k8s集群使用的etcd可能并不好，由于通过k8s部署的容器，目前想到的方法是，每个容器内的环境变量里已经有k8s apiserver的地址与端口信息，可以拼凑出接口地址直接查询Pod信息,这本质上也是通过etcd实现的。
现在这样的做法有个缺陷就是如果一个job需要大量Pod，那么在启动的时短时间内就会有大量请求访问apiserver

恩，我们的Pod中包含了我们所需要使用的Ip作为我们的trainerid，通过查询相应的接口，可以直观地获得整个job的全局信息，从而实现job实例与实例之间的互发现。短时间内大量访问这个不用担心，benchmark量级是在千以上的。

**Comment by wangkuiyi** [comment]
@tizhou86 @drinktee 了解job内containers之间互相发现的思路了。期待PR了。

@tizhou86 了解volumnes类型了。赞支持百度内部和AWS上的做法。Sanjeev给你开了AWS上efs权限了吗？

@backyes 如果走Kubernetes，我理解需要Kubernetes（+Paddle一起）来支持RDMA了。从这个[搜索结果](https://github.com/kubernetes/kubernetes/search?p=2&q=rdma&utf8=%E2%9C%93)看，目前还没有支持RDMA。

**Comment by tizhou86** [comment]
> 长期角度，要考虑下对rdma网络的支持，rdma不走tcp/ip stack，所以container还不知道是否支持？ 短期内当然不用care。

我们目前的解决方案是使用docker --net=host来直接使用宿主机网络而不使用网桥，这样就可以使用rdma网卡，但这样带来的问题是宿主机的端口冲突以及服务发现难以实现。这个可以做，但不符合kubernetes的理念，这个需要再讨论一下。

**Comment by tizhou86** [comment]
> 了解volumnes类型了。赞支持百度内部和AWS上的做法。Sanjeev给你开了AWS上efs权限了吗？

恩，已经调通了，现在在简化整个部署步骤，使用户能更简易地在AWS上部署整套paddle+k8s。

**Comment by pineking** [comment]
@wangkuiyi k8s 里有 service 的概念，service + kubedns 是否能解决发现的问题，至少 tensorflow 可以这么搞，但是我不了解 paddle 的分布式过程，需要看下

**Comment by drinktee** [comment]
@wangkuiyi  @backyes 
关于trainer的镜像，我有两个思路：
1. 直接将训练所需文件放在镜像内部，例如要完成recommendation训练，就直接将`paddle/demo/recommendation`文件夹和启动脚本放在镜像内部，但是data放在共享存储，镜像启动的时候下载对应data,直接运行。

2. 把`paddle/demo/recommendation`文件和data都放在共享存储上，trainer镜像内容是`paddledev/paddle:cpu-latest`镜像加上启动脚本，启动时先下载这些文件到容器内， 然后开始训练

第1种方法每次训练都要制作新镜像，不知第2种方式是否可行？

**Comment by backyes** [comment]
@drinktee 第一种方法基本不可接受，也不合理。第二种更好，目前基于mpi平台的架构，与第二种基本一致。

我的建议具体：

* data 一定放到共享存储上。（现有的mpi架构下基本都放到hdfs）
* recommendation这种用户相关的模型配置、解析脚本（例如dataprovider），需要给用户一个入口，能配置这些作业。（现在mpi架构下，基于一个thirdparty的方法，满足用户可配置性，可参看内部平台化）

**Comment by backyes** [comment]
@drinktee 等文档完善了， 什么时候我试试你们build k8s Paddle分布式训练体验， 也算给你们做test。

**Comment by Yancey1989** [comment]
@wangkuiyi  @backyes 
Kubernetes中提供了[Pet Set](http://kubernetes.io/docs/user-guide/petset/#next-steps)资源来解决管理有状态类的服务，能够保证Pod重启后hostname不变。

对于trainer的镜像，可以通过kubernetes中[init containers](http://kubernetes.io/docs/user-guide/production-pods/#handling-initialization)的机制，大致的过程如下：
1. 对于一个Pod，先启动一个container-A完成`hdfs get...、wget..、apt-get..`等初始化的任务
1. container-A完成后会退出，启动需要的业务contianer-b，由于Pod内部container之间的存储是共享的，所以container-a获取的数据在container-b中也可以使用

**Comment by drinktee** [comment]
init containers 特性很好,但还处在beta阶段，之后可以作为训练的初始化容器，Pet Set处于alpha，特性也符合，但是目前主要用来管理“服务”类型应用，长期处于running状态。paddle训练应该属于“作业”类型，有一个running状态-completed状态的过程。
其实还有一个设计我觉得更适合，但是kubernetes还没开发。[Design: Indexed Feature of Job object](https://github.com/kubernetes/kubernetes/blob/master/docs/design/indexed-job.md)

**Comment by helinwang** [comment]
谢谢建立这个issue的讨论，以上提到的几点现在[design doc](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/cluster_train)中都写有了，请移步查看。
我先关闭这个issue，如有问题请再打开。
