### ISSUE TITLE
PaddleInference app C API should wrapping C++ exception as return value

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle#47403]
### 需求描述 Feature Description

Typically C API design should be exception free, because C API is intended to wrapped in another programming languages like C#, and these C++ exceptions are not portable, let's say this API:
```C
BOOL PD_PredictorRun(void* pd_predictor);
```

the return BOOL is actually can't tell whether it's really success or fail, because it might **throw C++ exception**.

C API should also be "exception-safe" according to existing community consensus, the programming language calling C API, should able to rely on the return value to check it's success or not.
从业界规范来说，C API也应该是“异常安全”的，调用C API的外部，应该可以假定可以依赖于返回值来判断调用是否成功。

### 替代实现 Alternatives

Make sure any C++ exception will be catched in C API layer, and won't throw any C++ exception outside of C API boundary.

**Comment by jzhang533** [comment]
Oh, yes, pure C doesn't support exception handling.
I think this API doesn't have nothrow exception guarantee. 
If we are expecting this API being used in pure C, the best practice is to catch all exception inside this API.

cc: @qingqing01

**Comment by sdcb** [comment]
请求重新打开，问题未解决
