### ISSUE TITLE
paddle.onnx.export接口中，模型的输入是List[Tensor, Tensor ...], Tensor, input_spec怎么填写呢?

### ISSUE THREAD

**Issue by liangxuegang** [PaddlePaddle/Paddle#47402]
### 请提出你的问题 Please ask your question

我想将https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/dcn/net.py提供的模型转化为onnx模型保存，使用paddle.onnx.export接口，模型的输入是List[Tensor, Tensor ...], Tensor这种格式。我应该怎么给input_spec参数赋值呢？下面这种方式只能保存List中的一个参数：
`dense_input_dim = config.get('hyper_parameters.dense_input_dim', None)
x1_spec = InputSpec([None, 1], 'int64', 'sparse_inputs')
x2_spec = InputSpec([None, dense_input_dim], 'float32', 'dense_inputs')
paddle.onnx.export(dy_model, save_path, input_spec=[x1_spec, x2_spec], opset_version=11)`
当我把input_desc写成： input_spec=[x1_spec, x1_spec, x2_spec],会报错：ValueError: The decorated function `forward` requires 2 arguments: ['sparse_inputs', 'dense_inputs'], but received 3 with (InputSpec(shape=(-1, 1), dtype=paddle.int64, name=sparse_inputs), InputSpec(shape=(-1, 1), dtype=paddle.int64, name=sparse_inputs), InputSpec(shape=(-1, 13), dtype=paddle.float32, name=dense_inputs)).

**Comment by yeliang2258** [comment]
你好，我看paddle.onnx.export(dy_model, save_path, input_spec=[x1_spec, x2_spec], opset_version=11)的导出方式应该是对的，能否尝试先用paddle.jit.save将模型存下来，然后在用Paddle2ONNX工具来转，看看是不是还存在问题。
Paddle2ONNX工具的链接：https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by liangxuegang** [comment]
> 你好，我看paddle.onnx.export(dy_model, save_path, input_spec=[x1_spec, x2_spec], opset_version=11)的导出方式应该是对的，能否尝试先用paddle.jit.save将模型存下来，然后在用Paddle2ONNX工具来转，看看是不是还存在问题。 Paddle2ONNX工具的链接：https://github.com/PaddlePaddle/Paddle2ONNX

**Comment by liangxuegang** [comment]
> 你好，我看paddle.onnx.export(dy_model, save_path, input_spec=[x1_spec, x2_spec], opset_version=11)的导出方式应该是对的，能否尝试先用paddle.jit.save将模型存下来，然后在用Paddle2ONNX工具来转，看看是不是还存在问题。 Paddle2ONNX工具的链接：https://github.com/PaddlePaddle/Paddle2ONNX

感谢回复，您说的方法我也有过尝试，但是paddle.jit.save也需要传入input_spec这个参数，报错和paddle.onnx.export是一样的。
`dense_input_dim = config.get('hyper_parameters.dense_input_dim', None)
      x1_spec = InputSpec([None, 1], 'int64', 'sparse_inputs')
      x2_spec = InputSpec([None, dense_input_dim], 'float32', 'dense_inputs')
      static_model = paddle.jit.to_static(dy_model)
      paddle.jit.save(static_model, 'AAA', input_spec=[x1_spec, x2_spec])`

另外，我注意到，input_spec可以接受InputSpec|Tensor，尝试使用tensor是可以导出成功的，但是这样就不能让batch可变了。
`save_path = model_load_path + '_paddle'
      sparse_inputs_slots = config.get('hyper_parameters.sparse_inputs_slots', None)
      dense_input_dim = config.get('hyper_parameters.dense_input_dim', None)
      sparse_feature_number = config.get('hyper_parameters.sparse_feature_number', None)
      sparse_tensor = []
      for idx in range(sparse_inputs_slots - 1): # 26 items
        sparse_tensor_ = paddle.randint(low=0, high=sparse_feature_number, shape=[8, 1], dtype='int64', name='sparse_tensor_' + str(idx))
        sparse_tensor.append(sparse_tensor_)
      dense_tensor = paddle.rand(shape=[8, 13], dtype='float32', name='dense_tensor')
      pred, l2_loss = dy_model.forward(sparse_tensor, dense_tensor)
      paddle.onnx.export(dy_model, save_path + '_8batch', input_spec=[sparse_tensor, dense_tensor], output_spec=[pred], opset_version=11)`

是不是对于这种输入来说，使用InputSpec这个描述导出onnx模型这个接口有些问题。对于这种情况，我觉得应该是传入input_spec=[List[InputSpec,InputSpec,InputSpec...], InputSpec]这种和tensor一一对应的参数更加好一点，但是现在这种传入方法是错的。

**Comment by Aurelius84** [comment]
根据 @liangxuegang 你的描述，如果输入是`forwar([Tensor, Tensor], Tensor)`，则导出时input_spec应该为 `jit.save(input_spec=[[spec, spec], spec])`。如果有报错，辛苦贴一下报错栈，以及paddle的版本

**Comment by liangxuegang** [comment]
> 根据 @liangxuegang 你的描述，如果输入是`forwar([Tensor, Tensor], Tensor)`，则导出时input_spec应该为 `jit.save(input_spec=[[spec, spec], spec])`。如果有报错，辛苦贴一下报错栈，以及paddle的版本

感谢解答，试了一下input_spec=[[spec, spec], spec]这种写法，现在导出模型是没问题的，之前是我这边代码有问题。不好意思浪费大家时间了。
