### ISSUE TITLE
paddle_inferencel.dll部署测试时出现级别错误

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle#47424]
您好，我使用的硬件环境为Inter Celetron J1900，windows10x64操作系统，部署方式是PaddleX，测试项目为PaddeSeg，使用C++编写测试文档，测试时，在Windows的事件查看器中出现了级别错误，错误指向了paddle_inference.dll这个包，paddle的产品硬件支持表中提到paddle Inference支持常见CPU型号如Xeon、Core全系列等，请问paddle Inference支持Inter Celetron J1900显卡吗？

**Comment by fanxiaochen456** [comment]
这是我使用的测试显卡
![批注 2022-10-28 125428](https://user-images.githubusercontent.com/101849755/198514788-08242f71-d607-4082-b645-2771202bbaee.png)
下边是相应的报错信息
![批注 2022-10-28 125343](https://user-images.githubusercontent.com/101849755/198514826-dbc11201-8831-41bc-9e26-7b397460866e.png)

**Comment by weishengying** [comment]
你好，目前的信息还看不出错误。建议先跑一下  paddle Inference 的 demo， 这个仓库里有一个 resnet50 的demo， 您可以试一试。
https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/cpu

**Comment by fanxiaochen456** [comment]
@weishengying 您好，请问paddle Inference支持Inte Celetron J1900显卡吗？
![屏幕截图 2022-10-28 142111](https://user-images.githubusercontent.com/101849755/198517407-a80667b3-2987-4438-b835-f7a8ff80303f.png)
在这张表中并未提到J1900

**Comment by weishengying** [comment]
J1900 是一款内置核显的处理器吗？ Inference 目前只支持英伟达这样的独显。不过没关系，它依旧是x86架构的 CPU，你可以试着跑一下上面提供的 resnet50 demo。在 cpu 上应该是可以跑起来的。

**Comment by fanxiaochen456** [comment]
@weishengying 我使用的程序是x64操作系统的，paddle_Inference.dll也是64位的dll
![屏幕截图 2022-10-28 143516](https://user-images.githubusercontent.com/101849755/198519546-426dda47-6a47-4068-a47e-aa3dd952c25f.png)
跟这个指令集有关吗？

**Comment by weishengying** [comment]
跟这个无关，inference也支持 AVX2 指令集加速。

**Comment by fanxiaochen456** [comment]
我试过了不使用paddlex和paddle inference部署的paddleocr可以正常运行，但只要用到paddle inference就会出现上述的那个错误信息
![image](https://user-images.githubusercontent.com/101849755/198531289-57eae31c-8778-4cb9-9085-4849c244a890.png)
是因为指令集缺失还是什么原因呢？

**Comment by weishengying** [comment]
跑我给你提供的这个resnet50 的demo， 也会报上述那个错误信息吗？ https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/cpu

**Comment by weishengying** [comment]
> 我试过了不使用paddlex和paddle inference部署的paddleocr可以正常运行，但只要用到paddle inference就会出现上述的那个错误信息 ![image](https://user-images.githubusercontent.com/101849755/198531289-57eae31c-8778-4cb9-9085-4849c244a890.png) 是因为指令集缺失还是什么原因呢？

你上面发的图是支持 AVX2 指令集的吧
![image](https://user-images.githubusercontent.com/63448337/198538069-4075afb9-30da-42c8-8ead-477920787bb4.png)

**Comment by fanxiaochen456** [comment]
使用
![图片](https://user-images.githubusercontent.com/101849755/198564702-8e2381f9-a6cf-4c7e-8bef-1f0e3ab87af0.png)
这个就会出现那种错误，

**Comment by weishengying** [comment]
> 使用 ![图片](https://user-images.githubusercontent.com/101849755/198564702-8e2381f9-a6cf-4c7e-8bef-1f0e3ab87af0.png) 这个就会出现那种错误，
要不试试这个，我看你发的图片中，cpu 是不支持 AVX 指令集的。你在这里面下载一个没有打开 AVX 的动态库试一试 
https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#windows

**Comment by fanxiaochen456** [comment]
@weishengying 是不是因为
![图片](https://user-images.githubusercontent.com/101849755/198916150-b5d74a03-a244-45ed-aec7-461e78493685.png)
Paddle Inference需要的一些指令集缺失导致了无法使用paddle_inference.dll这个库呢？
