### ISSUE TITLE
强烈建议支持windows下cmake+mingw-64编译c++库。

### ISSUE THREAD

**Issue by lifw555** [PaddlePaddle/Paddle#47426]
### 需求描述 Feature Description

场景：在windows下使用qt编译gui程序，为兼容方便。

希望提供cmake+mingw-64w编译的dll库，或提供mingw-64w的预编译库也可以。

谢谢！

**Comment by zhwesky2010** [comment]
@lifw555 这个目前确实没有去实现的，因为用VS编译与Windows系统适配较好，也是绝大多数用法。
用mingw 需要给paddle库打包很多mingw库才能跑起来，会影响体积大小。请问在QT中是什么使用场景呢？

**Comment by lifw555** [comment]
@zhouwei25 就是用qt开发gui程序，不是用msvc的编译器。出发点很简单，就是windows和linux下，都是用的gcc编译器，只要切换环境就可以编译了。

**Comment by zhwesky2010** [comment]
@lifw555 现在还没有计划支持。QT也可以配置MSVC编译环境哈

**Comment by lifw555** [comment]
好的，了解了。

**Comment by folk113** [comment]
QT使用MINGW，VS编译出来的UI完全是不同的样子，一个大工程要切换到VS简直太难了
