### ISSUE TITLE
跑transformer的时候遇到Segmentation fault错误

### ISSUE THREAD

**Issue by gujianbo** [PaddlePaddle/Paddle#47446]
### 请提出你的问题 Please ask your question

错误日志：
Namespace(_CLS_=0, _MASK_=3, _PAD_=2, _SEP_=1, buffer_size=20, dropout=0.1, emb_dim=768, enable_log=1, eval_batch_size=20, eval_step=80, evaluate_model_path='', exp_settings={'method_name': 'NavieAlgorithm', 'n_gpus': 1, 'init_parameters': '/home/aistudio/models/baidu_ultr_12l_12h_768e.model', 'lr': 2e-07, 'max_candidate_num': 10, 'selection_bias_cutoff': 10, 'feature_size': 768, 'train_input_hparams': '', 'learning_algorithm_hparams': ''}, finetune_epoch=20, init_parameters='/home/aistudio/models/baidu_ultr_12l_12h_768e.model', log_interval=10, lr=2e-07, max_seq_len=128, max_steps=100000, method_name='NavieAlgorithm', n_gpus=1, n_queries_for_each_gpu=6, nhead=12, nlayers=12, ntokens=22000, num_candidates=10, result_path='result.csv', save_model_path='/home/aistudio/save_model', save_step=50, seed=0, test_annotate_path='./data/wsdm_round_1/wsdm_test_1.txt', train_batch_size=60, train_datadir='/home/aistudio/train_data', valid_annotate_path='/home/aistudio/annotate_data/valid_data.txt', valid_click_path='/home/aistudio/click_data/sample_click_1', warmup_steps=4000, weight_decay=0.01)
config.train_datadir: /home/aistudio/train_data
config.valid_annotate_path: /home/aistudio/annotate_data/valid_data.txt
config.valid_click_path: /home/aistudio/click_data/sample_click_1
load annotated data from  /home/aistudio/annotate_data/valid_data.txt
load logged click data from  /home/aistudio/click_data/sample_click_1
Transformer is used for pretrain
W1028 16:27:58.209091  6635 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1028 16:27:58.213253  6635 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
load warm up model  /home/aistudio/models/baidu_ultr_12l_12h_768e.model
loading pos_encoder.pe : [513, 1, 768]
loading transformer_encoder.layers.0.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.0.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.0.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.0.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.0.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.0.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.0.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.0.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.0.linear1.weight : [768, 768]
loading transformer_encoder.layers.0.linear1.bias : [768]
loading transformer_encoder.layers.0.linear2.weight : [768, 768]
loading transformer_encoder.layers.0.linear2.bias : [768]
loading transformer_encoder.layers.0.norm1.weight : [768]
loading transformer_encoder.layers.0.norm1.bias : [768]
loading transformer_encoder.layers.0.norm2.weight : [768]
loading transformer_encoder.layers.0.norm2.bias : [768]
loading transformer_encoder.layers.1.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.1.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.1.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.1.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.1.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.1.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.1.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.1.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.1.linear1.weight : [768, 768]
loading transformer_encoder.layers.1.linear1.bias : [768]
loading transformer_encoder.layers.1.linear2.weight : [768, 768]
loading transformer_encoder.layers.1.linear2.bias : [768]
loading transformer_encoder.layers.1.norm1.weight : [768]
loading transformer_encoder.layers.1.norm1.bias : [768]
loading transformer_encoder.layers.1.norm2.weight : [768]
loading transformer_encoder.layers.1.norm2.bias : [768]
loading transformer_encoder.layers.2.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.2.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.2.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.2.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.2.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.2.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.2.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.2.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.2.linear1.weight : [768, 768]
loading transformer_encoder.layers.2.linear1.bias : [768]
loading transformer_encoder.layers.2.linear2.weight : [768, 768]
loading transformer_encoder.layers.2.linear2.bias : [768]
loading transformer_encoder.layers.2.norm1.weight : [768]
loading transformer_encoder.layers.2.norm1.bias : [768]
loading transformer_encoder.layers.2.norm2.weight : [768]
loading transformer_encoder.layers.2.norm2.bias : [768]
loading transformer_encoder.layers.3.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.3.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.3.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.3.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.3.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.3.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.3.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.3.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.3.linear1.weight : [768, 768]
loading transformer_encoder.layers.3.linear1.bias : [768]
loading transformer_encoder.layers.3.linear2.weight : [768, 768]
loading transformer_encoder.layers.3.linear2.bias : [768]
loading transformer_encoder.layers.3.norm1.weight : [768]
loading transformer_encoder.layers.3.norm1.bias : [768]
loading transformer_encoder.layers.3.norm2.weight : [768]
loading transformer_encoder.layers.3.norm2.bias : [768]
loading transformer_encoder.layers.4.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.4.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.4.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.4.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.4.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.4.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.4.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.4.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.4.linear1.weight : [768, 768]
loading transformer_encoder.layers.4.linear1.bias : [768]
loading transformer_encoder.layers.4.linear2.weight : [768, 768]
loading transformer_encoder.layers.4.linear2.bias : [768]
loading transformer_encoder.layers.4.norm1.weight : [768]
loading transformer_encoder.layers.4.norm1.bias : [768]
loading transformer_encoder.layers.4.norm2.weight : [768]
loading transformer_encoder.layers.4.norm2.bias : [768]
loading transformer_encoder.layers.5.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.5.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.5.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.5.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.5.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.5.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.5.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.5.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.5.linear1.weight : [768, 768]
loading transformer_encoder.layers.5.linear1.bias : [768]
loading transformer_encoder.layers.5.linear2.weight : [768, 768]
loading transformer_encoder.layers.5.linear2.bias : [768]
loading transformer_encoder.layers.5.norm1.weight : [768]
loading transformer_encoder.layers.5.norm1.bias : [768]
loading transformer_encoder.layers.5.norm2.weight : [768]
loading transformer_encoder.layers.5.norm2.bias : [768]
loading transformer_encoder.layers.6.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.6.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.6.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.6.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.6.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.6.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.6.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.6.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.6.linear1.weight : [768, 768]
loading transformer_encoder.layers.6.linear1.bias : [768]
loading transformer_encoder.layers.6.linear2.weight : [768, 768]
loading transformer_encoder.layers.6.linear2.bias : [768]
loading transformer_encoder.layers.6.norm1.weight : [768]
loading transformer_encoder.layers.6.norm1.bias : [768]
loading transformer_encoder.layers.6.norm2.weight : [768]
loading transformer_encoder.layers.6.norm2.bias : [768]
loading transformer_encoder.layers.7.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.7.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.7.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.7.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.7.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.7.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.7.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.7.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.7.linear1.weight : [768, 768]
loading transformer_encoder.layers.7.linear1.bias : [768]
loading transformer_encoder.layers.7.linear2.weight : [768, 768]
loading transformer_encoder.layers.7.linear2.bias : [768]
loading transformer_encoder.layers.7.norm1.weight : [768]
loading transformer_encoder.layers.7.norm1.bias : [768]
loading transformer_encoder.layers.7.norm2.weight : [768]
loading transformer_encoder.layers.7.norm2.bias : [768]
loading transformer_encoder.layers.8.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.8.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.8.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.8.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.8.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.8.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.8.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.8.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.8.linear1.weight : [768, 768]
loading transformer_encoder.layers.8.linear1.bias : [768]
loading transformer_encoder.layers.8.linear2.weight : [768, 768]
loading transformer_encoder.layers.8.linear2.bias : [768]
loading transformer_encoder.layers.8.norm1.weight : [768]
loading transformer_encoder.layers.8.norm1.bias : [768]
loading transformer_encoder.layers.8.norm2.weight : [768]
loading transformer_encoder.layers.8.norm2.bias : [768]
loading transformer_encoder.layers.9.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.9.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.9.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.9.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.9.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.9.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.9.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.9.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.9.linear1.weight : [768, 768]
loading transformer_encoder.layers.9.linear1.bias : [768]
loading transformer_encoder.layers.9.linear2.weight : [768, 768]
loading transformer_encoder.layers.9.linear2.bias : [768]
loading transformer_encoder.layers.9.norm1.weight : [768]
loading transformer_encoder.layers.9.norm1.bias : [768]
loading transformer_encoder.layers.9.norm2.weight : [768]
loading transformer_encoder.layers.9.norm2.bias : [768]
loading transformer_encoder.layers.10.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.10.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.10.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.10.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.10.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.10.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.10.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.10.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.10.linear1.weight : [768, 768]
loading transformer_encoder.layers.10.linear1.bias : [768]
loading transformer_encoder.layers.10.linear2.weight : [768, 768]
loading transformer_encoder.layers.10.linear2.bias : [768]
loading transformer_encoder.layers.10.norm1.weight : [768]
loading transformer_encoder.layers.10.norm1.bias : [768]
loading transformer_encoder.layers.10.norm2.weight : [768]
loading transformer_encoder.layers.10.norm2.bias : [768]
loading transformer_encoder.layers.11.self_attn.q_proj.weight : [768, 768]
loading transformer_encoder.layers.11.self_attn.q_proj.bias : [768]
loading transformer_encoder.layers.11.self_attn.k_proj.weight : [768, 768]
loading transformer_encoder.layers.11.self_attn.k_proj.bias : [768]
loading transformer_encoder.layers.11.self_attn.v_proj.weight : [768, 768]
loading transformer_encoder.layers.11.self_attn.v_proj.bias : [768]
loading transformer_encoder.layers.11.self_attn.out_proj.weight : [768, 768]
loading transformer_encoder.layers.11.self_attn.out_proj.bias : [768]
loading transformer_encoder.layers.11.linear1.weight : [768, 768]
loading transformer_encoder.layers.11.linear1.bias : [768]
loading transformer_encoder.layers.11.linear2.weight : [768, 768]
loading transformer_encoder.layers.11.linear2.bias : [768]
loading transformer_encoder.layers.11.norm1.weight : [768]
loading transformer_encoder.layers.11.norm1.bias : [768]
loading transformer_encoder.layers.11.norm2.weight : [768]
loading transformer_encoder.layers.11.norm2.bias : [768]
loading token_encoder.weight : [22000, 768]
loading segment_encoder.weight : [2, 768]
loading norm_layer.weight : [768]
loading norm_layer.bias : [768]
loading to_logics.weight : [768, 22000]
loading to_logics.bias : [22000]
loading decoder.weight : [768, 1]
loading decoder.bias : [1]
load file part-00006.gz
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:278: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int32, but right dtype is paddle.float32, the right dtype will convert to paddle.int32
  format(lhs_dtype, rhs_dtype, lhs_dtype))
x.shape: [128, 60, 768]
x.shape: [60, 128, 768]
padding_mask.shape: [60, 12, 128, 128]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1666945704 (unix time) try "date -d @1666945704" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 6635 (TID 0x7f99ffb35700) from PID 0 ***]

/bin/bash: 行 1:  6635 段错误               (核心已转储) python -u pretrain.py --init_parameters '/home/aistudio/models/baidu_ultr_12l_12h_768e.model' --emb_dim 768 --nlayer 12 --nhead 12 --dropout 0.1 --buffer_size 20 --train_datadir /home/aistudio/train_data --n_gpus 1 --eval_batch_size 20 --valid_click_path /home/aistudio/click_data/sample_click_1 --save_step 50 --eval_step 80 --n_queries_for_each_gpu 6 --num_candidates 10 --valid_annotate_path /home/aistudio/annotate_data/valid_data.txt --save_model_path /home/aistudio/save_model --enable_log=1

代码路径：
https://github.com/gujianbo/Baidu_Pre_training/blob/main/pretrain.py
跑的时候的脚本：
!export FLAGS_use_cuda_managed_memory=false && echo $FLAGS_use_cuda_managed_memory && cd Baidu_Pre_training && python -u pretrain.py --init_parameters '/home/aistudio/models/baidu_ultr_12l_12h_768e.model' \
    --emb_dim 768 --nlayer 12 --nhead 12 --dropout 0.1 --buffer_size 20 \
    --train_datadir /home/aistudio/train_data --n_gpus 1 \
    --eval_batch_size 20 --valid_click_path /home/aistudio/click_data/sample_click_1 --save_step 50 \
    --eval_step 80 --n_queries_for_each_gpu 6 --num_candidates 10 --valid_annotate_path /home/aistudio/annotate_data/valid_data.txt \
    --save_model_path /home/aistudio/save_model --enable_log=1

从日志打印来看应该是在 https://github.com/gujianbo/Baidu_Pre_training/blob/main/models/transformer_model.py#L140 出现的
有段时候是必现的，有段时间又是好的。
运行环境：aistudio，paddlepaddle2.3.2，python3.7

求问怎么解决

**Comment by ceci3** [comment]
请问下有更多报错信息嘛？现在只是段错误也看不出来是哪里的问题~ 复现出来的环境和复现不出来的环境在paddle版本、cuda版本之类的环境之间有区别嘛

**Comment by gujianbo** [comment]
> 请问下有更多报错信息嘛？现在只是段错误也看不出来是哪里的问题~ 复现出来的环境和复现不出来的环境在paddle版本、cuda版本之类的环境之间有区别嘛

最近跑又没问题了，之前一直有问题，很奇怪
