### ISSUE TITLE
使用paddle.distributed.fleet进行多机多卡的分布式训练时，程序卡住不动

### ISSUE THREAD

**Issue by beaulian** [PaddlePaddle/Paddle#47451]
### Bug描述

使用paddle.distributed.fleet进行多机多卡的静态图的分布式训练时，程序卡住不动，不报错，GPU也在运行。使用`export NCCL_DEBUG_SUBSYS=ALL`查看NCCL的输出发现一直显示`NCCL INFO AllReduce: opCount xx sendbuff xxx recvbuff xxx count xxx`

把DistributedStrategy中的build_strategy里的reduce_strategy设置成static.BuildStrategy.ReduceStrategy.Reduce之后，程序可以正常跑起来。

**改之前的代码**

```
strategy = fleet.DistributedStrategy()
fleet.init(is_collective=True, strategy=strategy)
optimizer = optimizer.Adam(LEARNING_RATE)
optimizer = fleet.distributed_optimizer(optimizer)
optimizer.minimize(loss)
```

**改之后的代码**

```
build_strategy = static.BuildStrategy()
build_strategy.reduce_strategy = static.BuildStrategy.ReduceStrategy.Reduce
strategy = fleet.DistributedStrategy()
strategy.build_strategy = build_strategy
fleet.init(is_collective=True, strategy=strategy)
optimizer = optimizer.Adam(LEARNING_RATE)
optimizer = fleet.distributed_optimizer(optimizer)
optimizer.minimize(loss)
```

### 运行环境
**硬件环境**

机器：两台各自有四张3090的机器，运行环境一致
系统：CentOS Linux release 7.6.1810 (Core)
CPU：Hygon C86 7265 24-core Processor

**软件环境**
CUDA：11.6
CUDNN：8.6.0
NCCL：2.15.5
Paddle：GPU版本/2.3.2.post116

### 运行命令

**机器1**
python -m paddle.distributed.launch --host="xx.xx.xx.xx" --ips="xx.xx.xx.xx,yy.yy.yy.yy" --gpus=0,1 xxx.py
**机器2**
python -m paddle.distributed.launch --host="yy.yy.yy.yy" --ips="xx.xx.xx.xx,yy.yy.yy.yy" --gpus=0,1 xxx.py

**Comment by sljlp** [comment]
请尝试使用启动方式：
两个节点都使用以下命令：
python -m paddle.distributed.launch --master xx.xx.xx.xx:port --nnodes 2 --nproc_per_node 2 --gpus 0,1 xxx.py
master 的ip 是二机器其中之一

**Comment by sljlp** [comment]
请问方便提供最小可复现的完整代码吗？
