### ISSUE TITLE
自定义 c++ 算子，有些情况下 nvcc报错 -ccbin cc

### ISSUE THREAD

**Issue by clearhanhui** [PaddlePaddle/Paddle#47472]
### bug描述 Describe the Bug

我最近在写paddle的自定义c++算子，执行cuda编译的时候，遇到一个bug。
经过查找，发现[这段源代码](https://github.com/PaddlePaddle/Paddle/blob/7097630f3d137c0088c0b60c4b96dd4ecac06409/python/paddle/utils/cpp_extension/extension_utils.py#L382) 没有提前判断cc环境变量，如果没有设置该变量的话，会导致编译失败。
我在PyTorch上找到了[类似的代码](https://github.com/pytorch/pytorch/blob/71fe069d985e97b5947d133f2f2bde9adea01ed7/torch/utils/cpp_extension.py#L549)可以参考下。

我最近在实现的算子是 [【unsorted_segment_sum】](https://tensorflow.google.cn/api_docs/python/tf/math/unsorted_segment_sum)，希望你们可以原生支持一下

**Comment by clearhanhui** [comment]
具体的：执行 python setup.py install之后会出现：
paddle/include/paddle/phi/api/all.h:18:2: error: #error __cplusplus C++14 or later compatible compiler is required to use Paddle.

**Comment by LielinJiang** [comment]
自定义算子找@chenwhql帮忙看了，unsorted_segment_sum算子的功能似乎可以用scatter代替，data是update，segment_id为index，x为一个全0的输入。以下为示例代码：

```
# tf code:
c = [[1,2,3,4], [5,6,7,8], [4,3,2,1]]
tf.math.unsorted_segment_sum(c, [0, 1, 0], num_segments=2).numpy()

# paddle code:

import paddle
import numpy as np

updates_data = np.array([[1,2,3,4], [5,6,7,8], [4,3,2,1]]).astype(np.float32)
index_data = np.array([0, 1, 0]).astype(np.int64)
x_data = np.zeros([2, 5]).astype(np.float32)

x = paddle.to_tensor(x_data)
index = paddle.to_tensor(index_data)
updates = paddle.to_tensor(updates_data)

output1 = paddle.scatter(x, index, updates, overwrite=False)
```

**Comment by Aurelius84** [comment]
在编译cuda文件时也需要gcc的路径，是默认调用cc的，看起来是你环境中cc软链问题，正常应该是软链到gcc上的。

**Comment by clearhanhui** [comment]
> 在编译cuda文件时也需要gcc的路径，是默认调用cc的，看起来是你环境中cc软链问题，正常应该是软链到gcc上的。

对的，但是我的建议是可以借鉴 pytorch 一样写一个判断逻辑，还是可以避免掉一些bug的。

**Comment by clearhanhui** [comment]
> 自定义算子找@chenwhql帮忙看了，unsorted_segment_sum算子的功能似乎可以用scatter代替，data是update，segment_id为index，x为一个全0的输入。以下为示例代码：
> 
> ```
> # tf code:
> c = [[1,2,3,4], [5,6,7,8], [4,3,2,1]]
> tf.math.unsorted_segment_sum(c, [0, 1, 0], num_segments=2).numpy()
> 
> # paddle code:
> 
> import paddle
> import numpy as np
> 
> updates_data = np.array([[1,2,3,4], [5,6,7,8], [4,3,2,1]]).astype(np.float32)
> index_data = np.array([0, 1, 0]).astype(np.int64)
> x_data = np.zeros([2, 5]).astype(np.float32)
> 
> x = paddle.to_tensor(x_data)
> index = paddle.to_tensor(index_data)
> updates = paddle.to_tensor(updates_data)
> 
> output1 = paddle.scatter(x, index, updates, overwrite=False)
> ```

好的，感谢建议。但是我们还有一些别的需求，例如 unsorted_segment_max ，所以这部分API暂时我们还是选择自己开发。

我注意到 paddle 有 segment_max/sum/mean 的API，但是要求 index_data 是经过排序的，其实可以基于此进一步拓展unsorted版本，在GNN 里面会是一个比较有用的 API。

**Comment by chenwhql** [comment]
> 

感谢反馈，我们调研一下，后面优化一下使用体验

**Comment by chenwhql** [comment]
> > 在编译cuda文件时也需要gcc的路径，是默认调用cc的，看起来是你环境中cc软链问题，正常应该是软链到gcc上的。
> 
> 对的，但是我的建议是可以借鉴 pytorch 一样写一个判断逻辑，还是可以避免掉一些bug的。

@clearhanhui 感谢反馈，我们调研一下，后面优化一下使用体验
