### ISSUE TITLE
Where are `api.h`、`sparse_api.h` and `ext/tensor_compat.h`

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#47476]
### 请提出你的问题 Please ask your question

Hi, thanks for Paddle's helpful work!

I try to make a custom op, as I follow the link: [https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html)

After git clone `Paddle` and add `xxxx/Paddle` to my `includePath`, g++ can find `paddle/extension.h`

I just write
```
#include "paddle/extension.h"
#include <vector>
#define CHECK_INPUT(x) PD_CHECK(x.is_cpu(), #x " must be a CPU Tensor.")

std::vector<paddle::Tensor> ReluCPUForward(const paddle::Tensor& x){
    CHECK_INPUT(x);

    auto out = paddle::empty_like(x);

    auto x_numel = x.numel(); // 元素个数
    auto* out_data = x.data<float>();  // 和 OpenCV有些像

    return out;

}
```
And complie this file:
```
/usr/bin/g++ -fdiagnostics-color=always -g xxxxx/relu_cpu_fp32.cc -o xxxx/relu_cpu_fp32 -I xxxxx/Paddle
```

It raise:
```
fatal error: paddle/phi/api/include/api.h: No such file or directory
```

So, where is it? I just can't find some helpful doc about config my Paddle C++ env, Could you please help me?

**Comment by FrostML** [comment]
They are in your python env not in the repo. 

You can find these files in, maybe for example `python3.7/site-packages/paddle/include/`. 
And you can get this dir by executing
``` bash 
python -c "import paddle; print(paddle.sysconfig.get_include())"
```

**Comment by DrRyanHuang** [comment]
It works! Thanks! @FrostML
