### ISSUE TITLE
paddle.nn.MultiHeadAttention计算bug

### ISSUE THREAD

**Issue by 2017040264** [PaddlePaddle/Paddle#47475]
### bug描述 Describe the Bug

在使用paddle.nn.MultiHeadAttention时，按照github源代码中forward函数的描述，query和key的length维度可以是不相同的,但是在实际使用中会出错的。可以通过下述示例进行复现该问题。
``` python
import numpy as np
import paddle
x=np.random.random([64,1000,256])
y=np.random.random([64,100,256])

ppx=paddle.to_tensor(x,dtype='float32')
ppy=paddle.to_tensor(y,dtype='float32')
ppm=paddle.nn.MultiHeadAttention(num_heads=2, embed_dim=256)
pp_out=ppm(ppx,ppy)
print(pp_out.shape)
```

**Comment by FrostML** [comment]
如上代码仅有 `query` 和 `key`，需要再传入 `value`。见具体 [源码](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/layer/transformer.py#L359)

**Comment by 2017040264** [comment]
这个value不是必须的吧？？？如果不传不是默认为key吗？？？？ @FrostML

**Comment by 2017040264** [comment]
哦哦，我看到了，如果不传是默认用query代替。在tensforlow中，不传value值会默认用key代替, 这两种方式效果一样吗？

**Comment by FrostML** [comment]
当前这个 API 设计希望达到的效果是，当 qkv 一致的时候，可以不提供 kv；但是当其不一致的时候，需要显式传入 kv 并且 kv 都需要显式传入。
默认将 k 作为 v 或是 v 作为 k 的行为其实也不能涵盖所有的使用情况，因此需要可感知地使用这三个输入。
