### ISSUE TITLE
PaddleOCR,推理GPU利用率为0

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#47478]
### 请提出你的问题 Please ask your question

paddle_inference版本是2.2.2
在PaddleOCR项目中，C++推理时，本地两台机器上代码运行正常，使用GPU和tensorrt均正常。但是用另一部机器（也是Paddle支持的显卡），在这上运行时，设备GPU的利用率就为0，GPU用不起来，然后程序就会报错。代码和环境都一致，请问这是什么原因呢？？

报错情况如下：
WARNING: Logging before InitGoogleLogging() is written to STDERR
I1028 14:30:40.557919 22346 analysis_config.cc:1044] In CollectShapeInfo mode, we will disable optimizations and collect the shape information of all intermediate tensors in the compute graph and calculate the min_shape, max_shape and opt_shape.
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::~AnalysisPredictor()
3   paddle::AnalysisPredictor::~AnalysisPredictor()
4   paddle::memory::allocation::AllocatorFacade::Release(phi::Place const&)
5   paddle::memory::allocation::AllocatorFacadePrivate::GetAllocator(phi::Place const&, unsigned long)

----------------------
Error Message Summary:
----------------------
NotFoundError: No allocator found for the place, Place(undefined:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /paddle/paddle/fluid/memory/allocation/allocator_facade.cc:343)

Aborted

**Comment by zhangting2020** [comment]
无法跑通的机器是什么显卡？

**Comment by ainndejj11** [comment]
> 无法跑通的机器是什么显卡？

无法跑通的显卡为T4和P4       可以跑通的是2080，1070

**Comment by xiaoxiaohehe001** [comment]
请问你的 paddle inference 库在哪里安装的，本地 nvidia-smi 可以显示GPU设备吗，也可以试一下release/2.4.0rc 库是否会出现相同情况，https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html

**Comment by zhangting2020** [comment]
请问上述回复是否已经解决你的问题呢？如果已解决，可以关闭此issue
