### ISSUE TITLE
相关参数咨询

### ISSUE THREAD

**Issue by Klotho-SA** [PaddlePaddle/Paddle#47470]
### 问题描述 Please describe your issue

尊敬的工程师您好：
	我是同济大学附属上海市第十人民医院的一名博士研究生，目前在做一项关于伤口愈合期分类的研究工作，该工作使用了贵公司的EasyDL零门槛AI开发平台的图像分类功能（https://ai.baidu.com/easydl/app/imgcls/overview），模型ID为260221。因需要发表于国际期刊，所以已经和贵公司相关人员取得了联系并获得了发表许可。但目前仍有相关关键参数问题需要贵公司工程师协助解决：
下面表格是发表在国际期刊上的一篇文章中的截图，文章链接如下：https://doi.org/10.1016/j.cej.2022.134625
 
![图片](https://user-images.githubusercontent.com/90703235/198824704-38dcbcc2-1136-491b-9986-95c033da7970.png)

我希望能得到一些参数，例如上面这样的，能够用于文章发表的，也可以是一些代码类的东西，或者放到GitHub上的都可以。非常感谢，必要时可以给予一些报酬！

**Comment by LielinJiang** [comment]
根据你的描述，没法确定具体是哪个模型。这个数据需要具体的模型代码来确定，可以再联系具体的工作人员问问看。
