### ISSUE TITLE
多机分布式部署，参数服务器架构。处于master not ready状态不训练。

### ISSUE THREAD

**Issue by Eddie-zhg** [PaddlePaddle/Paddle#47484]
两台机器，一台server一台worker
试过很多次，完完全全按按照 [#47130 (comment)](https://github.com/PaddlePaddle/Paddle/issues/47130#issuecomment-1286695801)这个来执行的，两台机器都是master not ready。
![2022-10-31 10-07-54屏幕截图](https://user-images.githubusercontent.com/82798516/198917134-795ca2bf-4ea4-4c40-b7de-d6030f4ed05a.png)
![2022-10-31 10-08-25屏幕截图](https://user-images.githubusercontent.com/82798516/198917138-4781d737-2ab4-469c-8057-07b3086794a5.png)
![2022-10-31 10-09-06屏幕截图](https://user-images.githubusercontent.com/82798516/198917140-7e38b55b-247a-42d6-a86c-a613f2e233c0.png)
![2022-10-31 10-09-23屏幕截图](https://user-images.githubusercontent.com/82798516/198917145-c0010c23-1969-4b34-96fa-45e8537166b2.png)
还是paddle不支持一台机器仅当server、一台机器仅当worker？

_Originally posted by @Eddie-zhg in https://github.com/PaddlePaddle/Paddle/issues/47400#issuecomment-1296451267_

**Comment by zhangting2020** [comment]
你好，我看在#47400 #47484 提了同样的问题？分布式的问题，我们有负责的同学在跟进，为了保持沟通的效率，建议在原始的issue下面继续反馈你尝试后遇到了什么问题。我刚才浏览了下前面的问题：
- 有提到运行报错的：建议先不要多机分布式，先尝试单机，测试程序本身是否可以运行成功
- 有提到分布式训练报错的：如果上面的程序能正常跑通，确认是多机训练的问题，把目前你的运行脚本，执行的命令，都贴在一个comment里面，我们请相关同学排查。

**Comment by Eddie-zhg** [comment]
> 你好，我看在#47400 #47484 提了同样的问题？分布式的问题，我们有负责的同学在跟进，为了保持沟通的效率，建议在原始的issue下面继续反馈你尝试后遇到了什么问题。我刚才浏览了下前面的问题：
> 
> * 有提到运行报错的：建议先不要多机分布式，先尝试单机，测试程序本身是否可以运行成功
> * 有提到分布式训练报错的：如果上面的程序能正常跑通，确认是多机训练的问题，把目前你的运行脚本，执行的命令，都贴在一个comment里面，我们请相关同学排查。

你好，碰到的是一样的问题。重新进行这个提问是因为之前的问题已经没有回音了，我在其后贴上了后续问日，但不确定是否还会查看。
至于问题，单机运行一直就没有问题，出问题的都是多机运行。
程序采用的是https://github.com/PaddlePaddle/PaddleFleetX/tree/old_develop/examples/wide_and_deep_dataset
根据文档评测那边说的，这个程序直接就是可以运行的，我也没进行更改。
运行的指令：
![image](https://user-images.githubusercontent.com/82798516/198942662-8971d83a-6653-4c41-9864-62396c1cc32d.png)
结果就是上面贴出来的，无法训练。
运行的程序和指令就是这些。

**Comment by zhangting2020** [comment]
先根据这个文档，排查下分布式环境。https://github.com/PaddlePaddle/PaddleFleetX/blob/release/2.4/docs/deployment_faq.md#2-%E5%88%86%E5%B8%83%E5%BC%8F%E7%8E%AF%E5%A2%83%E9%AA%8C%E8%AF%81

**Comment by Eddie-zhg** [comment]
> 先根据这个文档，排查下分布式环境。https://github.com/PaddlePaddle/PaddleFleetX/blob/release/2.4/docs/deployment_faq.md#2-%E5%88%86%E5%B8%83%E5%BC%8F%E7%8E%AF%E5%A2%83%E9%AA%8C%E8%AF%81

这个是有问题。
server直接报错：
![2022-10-31 16-31-41屏幕截图](https://user-images.githubusercontent.com/82798516/198966612-d86380ea-da63-4f98-838d-f18082a50f8a.png)
![2022-10-31 16-32-12屏幕截图](https://user-images.githubusercontent.com/82798516/198966617-152048cd-8c8d-42ad-94ee-78ba11eb7a1e.png)
![2022-10-31 16-32-34屏幕截图](https://user-images.githubusercontent.com/82798516/198966622-b29dce05-6544-486e-9c12-dd93b128246a.png)

worker端会卡住：
![2022-10-31 16-32-54屏幕截图](https://user-images.githubusercontent.com/82798516/198966624-1ae7ff37-a19a-416f-960b-e95a31c52bf3.png)
![2022-10-31 16-33-41屏幕截图](https://user-images.githubusercontent.com/82798516/198966626-0640f71d-44b1-4904-babc-65ba36e340bb.png)

**Comment by Eddie-zhg** [comment]
检查了一下，**确认节点间是否能通过ping连接**：正常
**确认节点间是否能通过HTTP/TCP连接**：正常
下载的是CPU版本paddle（develop），不涉及NCCL。

**Comment by kuizhiqing** [comment]
经过提供的日志分析，你的环境paddle无法正确识别到机器IP，两台机器无法建立互联。无法识别正确IP并非paddle侧原因导致，暂时无法进一步排查问题，请先解决该问题后继续使用paddle，谢谢！

**Comment by Eddie-zhg** [comment]
> 经过提供的日志分析，你的环境paddle无法正确识别到机器IP，两台机器无法建立互联。无法识别正确IP并非paddle侧原因导致，暂时无法进一步排查问题，请先解决该问题后继续使用paddle，谢谢！

**更换了paddle版本环境，现在是paddle CPU 2.3.2。
遇到了和之前一样的问题：直接运行检测指令：python -m paddle.distributed.launch run_check，会报错说没有run_check。
按照之前的解答：**
![1](https://user-images.githubusercontent.com/82798516/199037314-e20be1ad-5e15-4260-9727-4ba3e51afa39.png)
![2](https://user-images.githubusercontent.com/82798516/199037316-daa42eb1-aef7-467f-be07-bb01d2f42f89.png)
**能够正常测试：**
![2022-10-31 22-42-03屏幕截图](https://user-images.githubusercontent.com/82798516/199037320-bd090aa7-7dc2-4cff-a6e2-0142c46faa3c.png)
![2022-10-31 22-42-25屏幕截图](https://user-images.githubusercontent.com/82798516/199037329-3fbcd738-550e-47c7-94be-7a7d88f1be8a.png)
![2022-10-31 22-42-46屏幕截图](https://user-images.githubusercontent.com/82798516/199037332-e45c8072-8aeb-49db-b763-4b7b5973a4a5.png)
![2022-10-31 22-43-00屏幕截图](https://user-images.githubusercontent.com/82798516/199037335-ab0ea4d1-3866-4f8d-b1c8-0e1738572d24.png)

不更换版本的话，运行run_check.py，也是可以正常测试。这说明两台机器是能够识别IP并能够有反应的。

**Comment by wchao94** [comment]
主机域名解析存在问题，会导致master上也报错master not ready
通过ping `hostname` 检查一下
