### ISSUE TITLE
请尽快适配Ubuntu 22.04.1 LTS！

### ISSUE THREAD

**Issue by mike-egg123** [PaddlePaddle/Paddle#47482]
### 需求描述 Feature Description

任务目标：模式识别作业; <br /> 需求场景：我目前在做我们学校的模式识别的作业，强制使用paddle框架，但网页版的每天8点算力又无法满足我的训练需求，因此需要在我们实验室的服务器上安装paddle环境，进行训练，但是我们实验室的服务器系统是Ubuntu 22.04.1 LTS，并且已经用了很久，无法重装;  <br /> 功能描述：无

**Comment by zhangting2020** [comment]
您好，我们已经收到反馈。目前，你可以在你的机器上使用docker安装。具体的方式参考官网文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/install/docker/linux-docker.html

**Comment by mike-egg123** [comment]
不是管理员账户，然后环境里没有nvidia-docker咋办呀。。。能不能直接pip安装嘞，像torch一样

**Comment by zhangting2020** [comment]
> 不是管理员账户，然后环境里没有nvidia-docker咋办呀。。。能不能直接pip安装嘞，像torch一样

协调安装一下吧，尤其是在一台公用的机器，有docker是最好的

**Comment by mike-egg123** [comment]
哦哦好吧。。。

**Comment by Tlntin** [comment]
> 不是管理员账户，然后环境里没有nvidia-docker咋办呀。。。能不能直接pip安装嘞，像torch一样

自行编译一下？https://github.com/PaddlePaddle/Paddle/issues/44668

**Comment by engineer1109** [comment]
不会C++编译吗？
这是入门基础吧
应该提问Ubuntu 22 编译遇到有何问题吧？这是OpenSource的意义啊

**Comment by zhangting2020** [comment]
飞桨develop 版本已经支持ubuntu 22.04，安装参考官网说明：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html。2.4版本会发版支持。
