### ISSUE TITLE
paddle如何只对限制部分权重更新呢？

### ISSUE THREAD

**Issue by joseph-chan** [PaddlePaddle/Paddle#4748]
要使用paddle实现 autoencoder（sparse autoencoder），输入有100多w维，隐藏层1024维。由于大部分输入维度都是处于非激活状态，想只对部分被激活、有输出值进行权重更新，假如输入和输出都只有第1和第10维被激活，那么应当如何只对这两个位置相关的值进行权重更新？
 
![autoencoder](https://user-images.githubusercontent.com/11705586/31482188-d6599cb4-af59-11e7-921d-70695f31c1b6.JPG)

**Comment by lcy-seso** [comment]
请问定量的，这里怎样区别激活和非激活状态呢？

**Comment by pkuyym** [comment]
猜测是需要sparse update, 与 issue #4773 相关
