### ISSUE TITLE
python -m paddle.distributed.launch run.py，run.py 的参数怎么传入呢

### ISSUE THREAD

**Issue by popova-2** [PaddlePaddle/Paddle#47492]
### 请提出你的问题 Please ask your question

sys.argv里面没有

**Comment by zhangting2020** [comment]
run.py是你自己的脚本吧。就正常在run.py后面设置参数就可以。

**Comment by popova-2** [comment]
不会被误认为是paddle.distributed.launch的参数吗

**Comment by zhangting2020** [comment]
你可以查阅下python的用法了解-m的使用，这个并不是paddle特有的用法。

**Comment by popova-2** [comment]
谢谢
