### ISSUE TITLE
[PaddleInference]C++如何获取网络模型的输入尺寸和数据类型

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#47494]
### 请提出你的问题 Please ask your question

C++ CreatePredictor 之后如何获取模型的输入尺寸和数据类型
```
paddle_infer::CreatePredictor(config);
    auto input_names = m_predictor->GetInputNames();
    auto input_t = m_predictor->GetInputHandle(input_names[0]);
    auto shape = input_t->shape();
```
这个shape返回的是空，需要自己设置大小。
有没有办法像PaddleLite那样获取模型的输入大小([1,3,256,256])和数据类型(float/ int64_t)。

**Comment by zhangting2020** [comment]
这个呢？
https://github.com/PaddlePaddle/Paddle/blob/2953b708a03d023b6b6b1fecde7ac431f8f48a94/paddle/fluid/inference/api/analysis_predictor.h#L175-L181

**Comment by engineer1109** [comment]
@zhangting2020 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_inference_api.h 这里面对外接口 有 GetInputTypes   没有 GetInputTensorShape
需要提PR补接口吗？

**Comment by engineer1109** [comment]
取消Predictor的 predictor_ 私有， 验证接口有效

**Comment by engineer1109** [comment]
https://github.com/PaddlePaddle/Paddle/pull/47499  PR提交
