### ISSUE TITLE
請問paddle.jit.save中input_spec的設定

### ISSUE THREAD

**Issue by JimmyLyods** [PaddlePaddle/Paddle#47528]
您好，最近在運用可視化visualDL這塊
在模型可視化遇到一些問題
有兩個演算法的模型沒辦法儲存下來
出現以下錯誤
TypeError: In transformed code:

    File "C:\Users\jimmy\AppData\Local\Temp/ipykernel_11152/1309680426.py", line 16, in forward
            )
        def forward(self, x):
            x = x.reshape(-1,1,40)    # 先利用reshape将数据转换为二维的
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
            x = paddle.to_tensor(x,np.float32)  # 再变成paddle张量
            x = self.model1(x)


    TypeError: reshape() takes from 2 to 3 positional arguments but 4 were given

這兩個模型分別是
class Learn(paddle.nn.Layer):
    def __init__(self):
        super(Learn, self).__init__()
        self.model1 = paddle.nn.Sequential(
        #输入通道一定为1，16为输出通道为卷积核的个数，2为卷积核的大小（实际为一个[1,2]大小的卷积核）
            paddle.nn.Conv1D(1,16,2),
            paddle.nn.MaxPool1D(2),
            paddle.nn.Flatten(),  
        )
        self.model2 = paddle.nn.Sequential(
            paddle.nn.Linear(304,2),
            paddle.nn.Sigmoid(),
        )
    def forward(self, x):
        x = x.reshape(-1,1,40)    # 先利用reshape将数据转换为二维的
        x = paddle.to_tensor(x,np.float32)  # 再变成paddle张量
        x = self.model1(x)
        x = self.model2(x)
        return x

還有
class LSTMRNN(paddle.nn.Layer):
    def __init__(self,input_dim,hidden_dim,n_layer,n_classes):
        super(LSTMRNN,self).__init__()
        self.lstm = paddle.nn.LSTM(input_dim,hidden_dim,n_layer)
        # 全连接层
        self.linear1 = paddle.nn.Linear(hidden_dim,n_classes)
        
    # 调用神经网络
    def forward(self,x):
        x = x.reshape(-1,1,40)
        x = paddle.to_tensor(x,np.float32)
        out,(h_n,c_n) = self.lstm(x)
        x = h_n[-1,:,:]
        x = self.linear1(x)
        return x

執行paddle.jit.save(layer=cnn, path='bank.M3.jit', input_spec=[InputSpec(shape=[None, 40, 2], dtype='float32')])
一直出現上述錯誤
shape也調整過各式各樣就不一一贅述
不知道shape要怎麼設定才會正確?

**Comment by danleifeng** [comment]
您好，可以参考下reshape的文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/reshape_cn.html#reshape
![image](https://user-images.githubusercontent.com/52735331/199172573-e6628f22-245a-4c01-b1fb-8edc5c3fc5fa.png)

**Comment by JimmyLyods** [comment]
> 您好，可以参考下reshape的文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/reshape_cn.html#reshape ![image](https://user-images.githubusercontent.com/52735331/199172573-e6628f22-245a-4c01-b1fb-8edc5c3fc5fa.png)

您好，關於這個連結內容有一段有點不太懂
如果不希望输入与输出共享数据，请使用 Tensor.clone
所以這個意思是如果使用reshape沒辦法儲存动态图模式嗎?

**Comment by danleifeng** [comment]
没太懂您的意思，动态图下，直接使用reshape ，x和 reshape_x 会共享数据，后续操作reshape_x也会影响x原来的值
 ```
reshape_x = x.reshape([-1])
reshape_clone_x = x.reshape([-1]).clone()
 ```

**Comment by JimmyLyods** [comment]
您好，現在還不支持動態圖可視化,
https://github.com/PaddlePaddle/VisualDL/issues/1038
所以用paddle.jit.save把靜態圖儲存下來,
模型和訓練執行都沒有問題,
是執行paddle.jit.save(layer=cnn, path='bank.M3.jit', input_spec=[InputSpec(shape=[None, 40, 2], dtype='float32')])
出錯下述錯誤
File "C:\Users\jimmy\AppData\Local\Temp/ipykernel_11152/1309680426.py", line 16, in forward
        )
    def forward(self, x):
        x = x.reshape(-1,1,40)    # 先利用reshape将数据转换为二维的
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        x = paddle.to_tensor(x,np.float32)  # 再变成paddle张量
        x = self.model1(x)


TypeError: reshape() takes from 2 to 3 positional arguments but 4 were given

**Comment by Aurelius84** [comment]
请问您使用的paddle版本是哪个？

**Comment by JimmyLyods** [comment]
您好，paddle版本是2.3.0

**Comment by Aurelius84** [comment]
根据 reshape API的文档，target shape应该是一个list，你改成如下试下呢？
```python
x = x.reshape([-1,1,40])
```

**Comment by JimmyLyods** [comment]
感謝Aurelius84和danleifeng的分享
的確改成這樣就可行x = x.reshape([-1,1,40])
非常感謝
