### ISSUE TITLE
linux预测库没有cuda10.2+cudnn7吗

### ISSUE THREAD

**Issue by renmada** [PaddlePaddle/Paddle#47545]
### 请提出你的问题 Please ask your question

这里没找到
https://www.paddlepaddle.org.cn/inference/v2.3/user_guides/download_lib.html#python

**Comment by zhangjun** [comment]
@renmada  你好，2.3版本没有cuda10.2+cudnn7组合的包。 2.4版本有对应的发布。 https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html 这里有提供2.4rc版本的包。

**Comment by renmada** [comment]
2.4只有C++的，有python会发布吗

**Comment by dingjiaweiww** [comment]
你好，2.4rc 版本的python 安装包就是cudnn7.6.5 的，2.4 版本以后python 安装包既支持训练也支持预测，可以去官网下载cuda10.2+cudnn7 的python wheel 安装包
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/install/pip/linux-pip.html
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/23093488/200222239-f90bece7-abb7-4025-8801-6227ae182333.png">
