### ISSUE TITLE
connection refused by pserver

### ISSUE THREAD

**Issue by RuijieHou** [PaddlePaddle/Paddle#4754]
```
Thu Oct 12 15:59:53 2017[1,0]<stderr>:F1012 15:59:53.317076 12257 LightNetwork.cpp:395] connection refused by pserver, maybe pserver failed!
Thu Oct 12 15:59:53 2017[1,0]<stderr>:*** Check failure stack trace: ***
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1180f250d  google::LogMessage::Fail()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1180f6775  google::LogMessage::SendToLog()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1180f2003  google::LogMessage::Flush()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1180f71de  google::LogMessageFatal::~LogMessageFatal()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd117eda69f  paddle::SocketClient::TcpClient()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd117eda831  paddle::SocketClient::SocketClient()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd119b3bf5f  paddle::ParameterClient2::init()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1196b218d  paddle::RemoteParameterUpdater::init()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1180d21ba  ParameterUpdater::init()
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd117cbadeb  _wrap_ParameterUpdater_init
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b6033  PyEval_EvalFrameEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b5fb8  PyEval_EvalFrameEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b5d10  PyEval_EvalFrameEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b6b28  PyEval_EvalCodeEx
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4b6c52  PyEval_EvalCode
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4e1c7d  PyRun_FileExFlags
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4e3501  PyRun_SimpleFileExFlags
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x4159dd  Py_Main
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @     0x7fd1746f2bd5  __libc_start_main
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @           0x414b71  (unknown)
Thu Oct 12 15:59:53 2017[1,0]<stderr>:    @              (nil)  (unknown)
Thu Oct 12 15:59:53 2017[1,0]<stderr>:./train.sh: line 239: 12257 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf
```

MPI任务，报错

**Comment by pkuyym** [comment]
从日志上看不出具体的问题，试着重启一下任务看？

**Comment by RuijieHou** [comment]
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=1 --nics=xgbe0 --port=7164 --ports_num=8 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.7' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.4' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.14' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.10' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.18' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.19' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.13' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `CXXABI_1.3.5' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.9' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.15' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.11' not found (required by ./paddle_pserver2)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:./paddle_pserver2: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by ./python27-gcc482/lib/libpython2.7.so.1.0)
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ check_return 'paddle_pserver2 failed'
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ '[' 1 -ne 0 ']'
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ echo '[./start_server.sh : 34] [main]'
Thu Oct 12 16:27:49 2017[1,0]<stderr>:[./start_server.sh : 34] [main]
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ echo '[FATAL]: paddle_pserver2 failed'
Thu Oct 12 16:27:49 2017[1,0]<stderr>:[FATAL]: paddle_pserver2 failed
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ get_stack
Thu Oct 12 16:27:49 2017[1,0]<stderr>:+ set +x

server.log有报上面的错误，结点不支持？ 我看同集群下有paddle任务是ok的

**Comment by RuijieHou** [comment]
@pkuyym 重启了多次，稳定复现

**Comment by pkuyym** [comment]
看起来是GLIBC的问题，以前有运行成功过吗

**Comment by RuijieHou** [comment]
在其他集群上成功的，这个集群是第一次跑

**Comment by pkuyym** [comment]
Paddle是自己编译的吗？如果是官方的，而且用reciever提交，是没问题的，如果自己编译，请确保编译环境是/opt/compiler/gcc-4.8.2

**Comment by RuijieHou** [comment]
我知道了，paddle是官方的，之前是用reciever提交的，多谢
