### ISSUE TITLE
单机训练，worker日志出现 bash：python：未找到命令

### ISSUE THREAD

**Issue by Eddie-zhg** [PaddlePaddle/Paddle#47559]
### 请提出你的问题 Please ask your question

单机1server2worker，worker训练日志正常结果应是：
![2022-11-02 10-14-26屏幕截图](https://user-images.githubusercontent.com/82798516/199380902-6d62af81-2ea4-4dd3-841e-77df3fb5406d.png)
现在出现这个问题：
![2022-11-02 10-13-07屏幕截图](https://user-images.githubusercontent.com/82798516/199380899-b03d36df-05cd-4ded-8ea2-45a8d8599368.png)
没有了time等参数，不知道这里缺少的是什么指令。

**Comment by Eddie-zhg** [comment]
你好，有人能解答一下么？

**Comment by zhaocaibei123** [comment]
请提供一下训练配置和脚本

**Comment by Eddie-zhg** [comment]
**训练配置**：paddle2.3.2 CPU版本
**运行脚本**：[https://github.com/PaddlePaddle/PaddleFleetX/tree/old_develop/examples/wide_and_deep_dataset](url)
**指令**：paddle.distributed.launch --server_num=1 --worker_num=2 train.py
**终端显示**：LAUNCH INFO 2022-11-02 14:57:00,061 -----------  Configuration  ----------------------
LAUNCH INFO 2022-11-02 14:57:00,061 devices: None
LAUNCH INFO 2022-11-02 14:57:00,061 elastic_level: -1
LAUNCH INFO 2022-11-02 14:57:00,061 elastic_timeout: 30
LAUNCH INFO 2022-11-02 14:57:00,061 gloo_port: 6767
LAUNCH INFO 2022-11-02 14:57:00,061 host: None
LAUNCH INFO 2022-11-02 14:57:00,061 job_id: default
LAUNCH INFO 2022-11-02 14:57:00,061 legacy: False
LAUNCH INFO 2022-11-02 14:57:00,061 log_dir: log
LAUNCH INFO 2022-11-02 14:57:00,061 log_level: INFO
LAUNCH INFO 2022-11-02 14:57:00,061 master: None
LAUNCH INFO 2022-11-02 14:57:00,061 max_restart: 3
LAUNCH INFO 2022-11-02 14:57:00,061 nnodes: 1
LAUNCH INFO 2022-11-02 14:57:00,061 nproc_per_node: None
LAUNCH INFO 2022-11-02 14:57:00,061 rank: -1
LAUNCH INFO 2022-11-02 14:57:00,061 run_mode: collective
LAUNCH INFO 2022-11-02 14:57:00,061 server_num: 1
LAUNCH INFO 2022-11-02 14:57:00,061 servers:
LAUNCH INFO 2022-11-02 14:57:00,061 trainer_num: None
LAUNCH INFO 2022-11-02 14:57:00,061 trainers:
LAUNCH INFO 2022-11-02 14:57:00,061 training_script: train.py
LAUNCH INFO 2022-11-02 14:57:00,061 training_script_args: []
LAUNCH INFO 2022-11-02 14:57:00,061 with_gloo: 0
LAUNCH INFO 2022-11-02 14:57:00,061 --------------------------------------------------
LAUNCH WARNING 2022-11-02 14:57:00,061 Compatible mode enable with args ['--worker_num=2']
-----------  Configuration Arguments -----------
backend: auto
cluster_topo_path: None
elastic_pre_hook: None
elastic_server: None
enable_auto_mapping: False
force: False
heter_devices:
heter_worker_num: None
heter_workers:
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
rank_mapping_path: None
run_mode: None
scale: 0
server_num: 1
servers:
training_script: train.py
training_script_args: []
worker_num: 2
workers:
------------------------------------------------
INFO 2022-11-02 14:57:00,062 launch.py:494] Run parameter-sever mode. pserver arguments:['--worker_num', '--server_num'], accelerators count:0
INFO 2022-11-02 14:57:00,062 launch.py:494] Run parameter-sever mode. pserver arguments:['--worker_num', '--server_num'], accelerators count:0
WARNING 2022-11-02 14:57:00,062 launch.py:714] launch start with CPUONLY mode
WARNING 2022-11-02 14:57:00,062 launch.py:714] launch start with CPUONLY mode
INFO 2022-11-02 14:57:00,063 launch_utils.py:1566] Local server start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |            PADDLE_PSERVERS_IP_PORT_LIST                 127.0.0.1:49735               |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:39629,127.0.0.1:52087       |
    |                             PADDLE_PORT                      49735                    |
    |                           TRAINING_ROLE                     PSERVER                   |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                                  POD_IP                    127.0.0.1                  |
    |                        PADDLE_WITH_GLOO                        0                      |
    |                  PADDLE_GLOO_RENDEZVOUS                        3                      |
    |                     PADDLE_GLOO_FS_PATH                /tmp/tmpbm9wz8qy               |
    |               PADDLE_GLOO_HTTP_ENDPOINT                 127.0.0.1:33527               |
    +=======================================================================================+

INFO 2022-11-02 14:57:00,063 launch_utils.py:1566] Local server start 1 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |            PADDLE_PSERVERS_IP_PORT_LIST                 127.0.0.1:49735               |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:39629,127.0.0.1:52087       |
    |                             PADDLE_PORT                      49735                    |
    |                           TRAINING_ROLE                     PSERVER                   |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                                  POD_IP                    127.0.0.1                  |
    |                        PADDLE_WITH_GLOO                        0                      |
    |                  PADDLE_GLOO_RENDEZVOUS                        3                      |
    |                     PADDLE_GLOO_FS_PATH                /tmp/tmpbm9wz8qy               |
    |               PADDLE_GLOO_HTTP_ENDPOINT                 127.0.0.1:33527               |
    +=======================================================================================+

INFO 2022-11-02 14:57:00,072 launch_utils.py:1664] Local worker start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |            PADDLE_PSERVERS_IP_PORT_LIST                 127.0.0.1:49735               |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:39629,127.0.0.1:52087       |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                           TRAINING_ROLE                     TRAINER                   |
    |                                  POD_IP                    127.0.0.1                  |
    |                             PADDLE_PORT                      39629                    |
    |                       PADDLE_TRAINER_ID                        0                      |
    |                        PADDLE_WITH_GLOO                        0                      |
    |                  PADDLE_GLOO_RENDEZVOUS                        3                      |
    |                     PADDLE_GLOO_FS_PATH                /tmp/tmpbm9wz8qy               |
    |                     FLAGS_selected_gpus                        0                      |
    |                     FLAGS_selected_xpus                        0                      |
    |                    CUDA_VISIBLE_DEVICES                        0                      |
    |                     XPU_VISIBLE_DEVICES                        0                      |
    |               PADDLE_GLOO_HTTP_ENDPOINT                 127.0.0.1:33527               |
    +=======================================================================================+

INFO 2022-11-02 14:57:00,072 launch_utils.py:1664] Local worker start 2 processes. First process distributed environment info (Only For Debug):
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |            PADDLE_PSERVERS_IP_PORT_LIST                 127.0.0.1:49735               |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:39629,127.0.0.1:52087       |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                           TRAINING_ROLE                     TRAINER                   |
    |                                  POD_IP                    127.0.0.1                  |
    |                             PADDLE_PORT                      39629                    |
    |                       PADDLE_TRAINER_ID                        0                      |
    |                        PADDLE_WITH_GLOO                        0                      |
    |                  PADDLE_GLOO_RENDEZVOUS                        3                      |
    |                     PADDLE_GLOO_FS_PATH                /tmp/tmpbm9wz8qy               |
    |                     FLAGS_selected_gpus                        0                      |
    |                     FLAGS_selected_xpus                        0                      |
    |                    CUDA_VISIBLE_DEVICES                        0                      |
    |                     XPU_VISIBLE_DEVICES                        0                      |
    |               PADDLE_GLOO_HTTP_ENDPOINT                 127.0.0.1:33527               |
    +=======================================================================================+

INFO 2022-11-02 14:57:00,090 launch_utils.py:1482] Please check servers, workers and heter_worker logs in log/workerlog.*, log/serverlog.* and log/heterlog.*
INFO 2022-11-02 14:57:00,090 launch_utils.py:1482] Please check servers, workers and heter_worker logs in log/workerlog.*, log/serverlog.* and log/heterlog.*
INFO 2022-11-02 14:57:01,798 launch_utils.py:1494] all workers exit, going to finish parameter server and heter_worker.
INFO 2022-11-02 14:57:01,798 launch_utils.py:1494] all workers exit, going to finish parameter server and heter_worker.
INFO 2022-11-02 14:57:01,798 launch_utils.py:1507] all parameter server are killed
INFO 2022-11-02 14:57:01,798 launch_utils.py:1507] all parameter server are killed

**server0:**
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
new table_name: embedding
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:591: UserWarning: The PS mode must use MemorySparseTable.
  warnings.warn("The PS mode must use MemorySparseTable.")
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:596: UserWarning: The shard_num of sparse table is not set, use default value 1000.
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:601: UserWarning: The accessor of sparse table is not set, use default value.
  warnings.warn(
new var: persist trainable param embedding : SELECTED_ROWS.shape(1024, 10).dtype(float32).stop_gradient(False), 10, 12
adam_d2sum: False
adam_d2sum: False
I1102 14:57:00.952044 352694 table.cc:81] accessor initializing: table_id: 0, accessor_name: SparseAccessor
I1102 14:57:00.954667 352694 memory_sparse_table.cc:43] initalize MemorySparseTable succ
I1102 14:57:00.954690 352694 table.cc:81] accessor initializing: table_id: 1, accessor_name: CommMergeAccessor
I1102 14:57:00.964277 352694 table.cc:81] accessor initializing: table_id: 2, accessor_name: CommMergeAccessor
I1102 14:57:00.967861 352694 brpc_ps_server.cc:66] running server with rank id: 0, endpoint: 127.0.0.1:49735


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::distributed::FleetWrapper::RunServer(std::string const&, unsigned int)
1   paddle::distributed::BrpcPsServer::Start(std::string const&, unsigned int)

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1667372221 (unix time) try "date -d @1667372221" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800056193) received by PID 352694 (TID 0x7f8060854740) from PID 352659 ***]

**worker0:**
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
ShowClickEntry not configured, will not use
delete_optimizer_pass
pass loss program id: 140652741295216
pass main program id: 140652640348048
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/fluid/executor.py:400: UserWarning: do not use standalone executor in fleet by default
  warnings.warn("do not use standalone executor in fleet by default")
new table_name: embedding
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:591: UserWarning: The PS mode must use MemorySparseTable.
  warnings.warn("The PS mode must use MemorySparseTable.")
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:596: UserWarning: The shard_num of sparse table is not set, use default value 1000.
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:601: UserWarning: The accessor of sparse table is not set, use default value.
  warnings.warn(
new var: persist trainable param embedding : SELECTED_ROWS.shape(1024, 10).dtype(float32).stop_gradient(False), 10, 12
adam_d2sum: False
new table_name: embedding
new var: persist trainable param embedding : SELECTED_ROWS.shape(1024, 10).dtype(float32).stop_gradient(False), 10, 12
adam_d2sum: False
adam_d2sum: False
adam_d2sum: False
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
public get_dense_send_context dense_table: Dense@GRAD_1 430815 ['linear_0.b_0@GRAD', 'linear_0.w_0@GRAD', 'linear_1.b_0@GRAD', 'linear_1.w_0@GRAD', 'linear_2.b_0@GRAD', 'linear_2.w_0@GRAD', 'linear_3.b_0@GRAD', 'linear_3.w_0@GRAD', 'linear_4.b_0@GRAD', 'linear_4.w_0@GRAD']
communicator config: {'communicator_max_merge_var_num': '1', 'communicator_send_queue_size': '1', 'communicator_independent_recv_thread': '1', 'communicator_min_send_grad_num_before_recv': '1', 'communicator_thread_pool_size': '5', 'communicator_send_wait_times': '5', 'communicator_is_sgd_optimizer': '1'}
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/base/role_maker.py:303: UserWarning: gloo is not initialized, will not communicator with other nodes
  warnings.warn(self._err_init)
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/fleet/base/role_maker.py:347: UserWarning: gloo is not initialized, will not communicator with other nodes
  warnings.warn(self._err_init)
/home/ubuntu/.local/lib/python3.8/site-packages/paddle/distributed/ps/the_one_ps.py:973: UserWarning: gloo may not initialize correctly
  warnings.warn("gloo may not initialize correctly")
I1102 14:57:01.343425 352697 brpc_ps_client.cc:153] Client connect success:127.0.1.1:8500,
create c2c connection done
create DownpourLiteWorker
device worker program id: 140652640348048
device worker program_configs: {'140652640348048': {'pull_dense': [1], 'push_dense': [1], 'pull_sparse': [], 'push_sparse': []}}
device worker 140652640348048 140652640348048
device worker pull dense: [1]
device worker dense_table_config: {1: ['linear_0.b_0', 'linear_0.w_0', 'linear_1.b_0', 'linear_1.w_0', 'linear_2.b_0', 'linear_2.w_0', 'linear_3.b_0', 'linear_3.w_0', 'linear_4.b_0', 'linear_4.w_0']}
I1102 14:57:01.366655 352697 fleet.cc:37] RegisterHeterCallback support later
bash: python：未找到命令
bash: python：未找到命令
I1102 14:57:01.390164 352697 brpc_ps_client.cc:440] BrpcPsClient::flush begin
I1102 14:57:01.490658 352697 brpc_ps_client.cc:451] BrpcPsClient::flush done
I1102 14:57:01.490720 352697 brpc_ps_client.cc:460] BrpcPsClient::PrintQueueSize: table 0 size: 0
I1102 14:57:01.490733 352697 brpc_ps_client.cc:467] BrpcPsClient::PrintQueueSize: table 1 size: 0
I1102 14:57:01.492575 352697 brpc_ps_client.cc:440] BrpcPsClient::flush begin
I1102 14:57:01.593055 352697 brpc_ps_client.cc:451] BrpcPsClient::flush done
I1102 14:57:01.593119 352697 brpc_ps_client.cc:460] BrpcPsClient::PrintQueueSize: table 0 size: 0
I1102 14:57:01.593132 352697 brpc_ps_client.cc:467] BrpcPsClient::PrintQueueSize: table 1 size: 0
I1102 14:57:01.593148 352697 brpc_ps_client.cc:481] BrpcPsClient::FinalizeWorker begin join thread
I1102 14:57:01.600955 352697 brpc_ps_client.cc:486] BrpcPsClient::FinalizeWorker begin join server
I1102 14:57:01.601437 352697 brpc_ps_client.cc:490] BrpcPsClient::FinalizeWorker done

**Comment by Eddie-zhg** [comment]
worker0和worker1日志是一样的。正常情况下，worker日志里面‘bash: python：未找到命令’应该是time loss等信息吧。

**Comment by zhaocaibei123** [comment]
直接在bash里运行 python 能运行吗，看起来是运行不了python
![image](https://user-images.githubusercontent.com/48509226/199455245-79272808-0c86-4d4d-a670-26109a9dbb39.png)

**Comment by Eddie-zhg** [comment]
你好，你说的直接在bash里运行是啥意思？另一台一样配置的机子，是能够正常运行的。

**Comment by zhaocaibei123** [comment]
> 你好，你说的直接在bash里运行是啥意思？另一台一样配置的机子，是能够正常运行的。

在命令行里运行python，不行的话换python3试试
