### ISSUE TITLE
PaddlePaddle配不上cuda环境

### ISSUE THREAD

**Issue by Hyperjunct** [PaddlePaddle/Paddle#47560]
### bug描述 Describe the Bug

PaddlePaddle配不上cuda环境，调用不了GPU
CUDA11.4的机器环境配不上paddlegpu112和116两个版本的
<img width="1235" alt="1170870eb15fa058e6a8f7fce84616d" src="https://user-images.githubusercontent.com/98454125/199382191-84829be9-67ba-4bb0-ac7b-d7bf7bd8d073.png">

### 其他补充信息 Additional Supplementary Information

复现环境：
OS : Linux
PaddlePaddle : 2.3.2
PaddleYOLO : release/2.5
Python : 3.9.13
CUDA : 11.4
cuDNN Version : 8.4
GUP : V100

**Comment by ForFishes** [comment]
您好，按照提示设置 ``export LD_LIBRARY_PATH=``这个没有。可以参考设置成
``export LD_LIBRARY_PATH=/usr/local/cuda-11.2/targets/x86_64-linux/lib:/usr/local/nvidia/lib:/usr/local/nvidia/lib64`` （找到自己环境的cuda）
