### ISSUE TITLE
完全离线环境安装paddle

### ISSUE THREAD

**Issue by WethatVivy** [PaddlePaddle/Paddle#47562]
### 需求描述 Feature Description

cpu:ARMv8 CPU
参照文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html
问题描述：部署小白，也没有使用过git管理项目。在获取源代码时使用的是git，离线环境下也能使用git获取源码吗？不能的话是要怎么做呢？

**Comment by ForFishes** [comment]
您好，离线的时候git无法拉取代码。如果源码编译，过程中需要拉取必要的第三方库，所以需要联网。
您可以直接使用编译好的whl包安装，或者看如果使用代理的方式连接外网。

**Comment by WethatVivy** [comment]
由于特殊原因，服务器无法连接外网，且由于CPU架构是ARMv8，我在官网查看相关文档时，没有找到相应的whl包，硬件支持表是没有写支持arm架构cpu的，但又有飞腾/鲲鹏的源码编译安装文档（这两处理器的架构是ARMv8），所以现在就比较迷惑。

**Comment by hitzhu** [comment]
> 您好，离线的时候git无法拉取代码。如果源码编译，过程中需要拉取必要的第三方库，所以需要联网。 您可以直接使用编译好的whl包安装，或者看如果使用代理的方式连接外网。

能提前下载需要的第三方库之后放到对应的文件目录下面嘛
