### ISSUE TITLE
paddle动态图转静态图问题

### ISSUE THREAD

**Issue by will-wiki** [PaddlePaddle/Paddle#47572]
### 请提出你的问题 Please ask your question

paddle动态图转静态图的问题想请教一下，目前在尝试将paddlespeech的ecapa_tdnn模型转静态图，但是碰到了点问题。
<img width="1827" alt="image" src="https://user-images.githubusercontent.com/22003927/199400786-179491de-fdfd-4e38-80c9-c320e05a5405.png">
想问下paddle.concate函数在转静态图都会碰到这个问题么

**Comment by Aurelius84** [comment]
您好，请问能贴一下完整的报错截图么？另外您使用的paddle版本是哪一个？

**Comment by will-wiki** [comment]
@Aurelius84

**Comment by will-wiki** [comment]
@Aurelius84

**Comment by will-wiki** [comment]
@Aurelius84 报错信息
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/22003927/199418409-8e6d2e46-6983-4a55-9d86-622c1a49e86a.png">
但是报错地方是其他位置，主要原因就是出现了两个-1的维度，而出现两个-1的原因就是上面找到的地方。
用的paddle版本是2.2.2。

**Comment by will-wiki** [comment]
@Aurelius84 那个问题用reshap应该解决了，碰到另外一个转换的问题，想问下这个如何解决呀，报错谷歌搜不太到。。
<img width="1570" alt="image" src="https://user-images.githubusercontent.com/22003927/199426618-ccc0634f-4e30-4c16-bd32-687c692672c1.png">

**Comment by ForFishes** [comment]
> @Aurelius84 那个问题用reshap应该解决了，碰到另外一个转换的问题，想问下这个如何解决呀，报错谷歌搜不太到。。 <img alt="image" width="1570" src="https://user-images.githubusercontent.com/22003927/199426618-ccc0634f-4e30-4c16-bd32-687c692672c1.png">

用户通过添加 stop_gradient解决
