### ISSUE TITLE
单机多卡训练

### ISSUE THREAD

**Issue by Manningchan** [PaddlePaddle/Paddle#47607]
### 请提出你的问题 Please ask your question

单机单卡可以训练，改成多卡报错，export LD_LIBRARY_PATH=也已经设置过了，训练的是rtformer

RuntimeError: (PreconditionNotMet) The third-party dynamic library (libnccl.so) that Paddle depends on is not configured correctly. (error code is libnccl.so: cannot open shared object file: No such file or directory)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at /paddle/paddle/phi/backends/dynload/dynamic_loader.cc:303)

**Comment by ForFishes** [comment]
您好，这环境下，nccl没有安装nccl，无法跨卡通信。需要安装nccl，然后在设置nccl的环境变量。
