### ISSUE TITLE
 torch.nn.InstanceNorm2d(32, affine=True)在paddle里怎么实现？

### ISSUE THREAD

**Issue by weibo021** [PaddlePaddle/Paddle#47619]
### 请提出你的问题 Please ask your question

新手提问，torch.nn.InstanceNorm2d(32, affine=True)在paddle里怎么实现？paddle.nn.InstanceNorm2D 不支持affine参数

**Comment by weibo021** [comment]
torch.nn.InstanceNorm2d 的文档
https://pytorch.org/docs/stable/generated/torch.nn.InstanceNorm2d.html
paddle.nn.InstanceNorm2D
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/InstanceNorm2D_cn.html

**Comment by ceci3** [comment]
抱歉，看错了，torch.nn.InstanceNorm2d(affine=True) 等价于 paddle.nn.InstanceNorm2D()
