### ISSUE TITLE
Error FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by MikeLud** [PaddlePaddle/Paddle#47618]
### bug描述 Describe the Bug

I am working on making License Plate Module using paddleOCR for the below project and I am getting the below errors when importing paddle. It imports fine using an interactive window.

System Environment：Python 3.7
Paddle Version：paddlepaddle==2.3.2
PaddleOCR Version: paddleocr==2.6.1.0

Project Link:
https://github.com/codeproject/CodeProject.AI-Server

License Plate Module code Link:
https://github.com/MikeLud/CodeProject.AI-Server/tree/main/src/modules/ALPR

![image](https://user-images.githubusercontent.com/36526272/199621369-5d8a483b-1824-447f-9c14-376d3cf2d847.png)
![image](https://user-images.githubusercontent.com/36526272/199621642-5d0179fd-ac64-4729-80c6-968ae7b166c9.png)

**Comment by MikeLud** [comment]
@luotao1 thanks for looking into this issue, we were able to get it to work, see the below link that has all of the details
https://www.codeproject.com/Tips/5347636/Getting-PaddleOCR-and-PaddlePaddle-to-work-in-Wind

**Comment by luotao1** [comment]
> 
https://www.codeproject.com/Tips/5347636/Getting-PaddleOCR-and-PaddlePaddle-to-work-in-Wind

cc to @dyning

**Comment by luotao1** [comment]
@MikeLud I see you mentioned：
<img width="947" alt="image" src="https://user-images.githubusercontent.com/6836917/212796958-85d25295-22cb-4f0a-9a4a-bcf17b1e64c9.png">
<img width="924" alt="image" src="https://user-images.githubusercontent.com/6836917/212797018-f9d99b91-30e0-46b9-8e41-ac4b6b74d0e5.png">
How about creating a PR to fix it?

**Comment by luotao1** [comment]
> 
https://www.codeproject.com/Tips/5347636/Getting-PaddleOCR-and-PaddlePaddle-to-work-in-Wind

cc to @dyning @Evezerest @D-DanielYang

**Comment by zhwesky2010** [comment]
@MikeLud hello，I tried on Windows, when `shell=False` , it always works.  How to trigger this problem?

<img width="967" alt="infoflow 2023-01-17 11-15-14" src="https://user-images.githubusercontent.com/52485244/212802539-8130b866-f0a3-40ce-81b7-95c245d9e39f.png">

**Comment by MikeLud** [comment]
> @MikeLud hello，I tried on Windows, when `shell=False` , it always works. How to trigger this problem?
> 
> <img alt="infoflow 2023-01-17 11-15-14" width="967" src="https://user-images.githubusercontent.com/52485244/212802539-8130b866-f0a3-40ce-81b7-95c245d9e39f.png">

@ChrisMaunder can you elaborate on how CodeProject.AI is triggering the PaddlePaddel issue

**Comment by ChrisMaunder** [comment]
When using 
```
paddlepaddle==2.3.2
```
 (Windows, non GPU) or 
```
--find-links https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
paddlepaddle-gpu==2.3.2.post116
```
for Windows 10 or 11 with an Nvidia card we see the issue. 

In the (original) code there is
```
    import_cv2_proc = subprocess.Popen(
        [interpreter, "-c", "import cv2"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        shell=False)
    out, err = import_cv2_proc.communicate()
```
When Shell=False, the POpen call works, but the communicate() method just hangs. Setting Shell=True allows the communicate call to complete properly.

**Comment by zhwesky2010** [comment]
@MikeLud I try in different ways, and communicate returns an empty string
<img width="804" alt="infoflow 2023-01-31 16-41-26" src="https://user-images.githubusercontent.com/52485244/215710855-ecf8aeb7-b507-4079-a787-416a381b8dea.png">

**Comment by ChrisMaunder** [comment]
I'm using Python 3.7. I wonder if that's the issue?

**Comment by luotao1** [comment]
close due to the following PR is merged
- https://github.com/PaddlePaddle/Paddle/pull/51235
