### ISSUE TITLE
缺少文件auto_parallel.pb.h

### ISSUE THREAD

**Issue by QwQxwqQwQ** [PaddlePaddle/Paddle#47620]
### 问题描述 Issue Description

Paddle/paddle/fluid/distributed/auto_parallel/dist_attr.h:24:10: fatal error: paddle/fluid/distributed/auto_parallel/auto_parallel.pb.h: No such file or directory
   24 | #include "paddle/fluid/distributed/auto_parallel/auto_parallel.pb.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

### 版本&环境信息 Version & Environment Information

Paddle version: develop
Paddle with CUDA: OFF

**Comment by yaoxuefeng6** [comment]
请问下是什么情况下报的错？编译报错？

**Comment by yzxxxxx** [comment]
我也遇到这个问题，请问怎样解决，third_party里的protoc编译成功也是可执行的，但是好像没有生成auto_parallel.pb.h，导致编译出错

**Comment by aoyulong** [comment]
@QwQxwqQwQ 能否发一下完整的build命令？

**Comment by luotao1** [comment]
@yzxxxxx 能否发一下完整的build命令？

**Comment by ZhangYuef** [comment]
类似问题 #48688

**Comment by supercatking** [comment]
我也遇到这个问题：
![image](https://user-images.githubusercontent.com/87652697/223306742-5278641f-bdea-4371-ad2c-d7f501326c55.png)

**Comment by chenzhijun45** [comment]
> @yzxxxxx 能否发一下完整的build命令？

我也遇到这个问题，操作文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html
报错执行的命令是：`make -j$(nproc)`

我的操作系统：Ubuntu20.04
海光CPU，海光DCU Z100
在  `paddlepaddle/paddle:latest-dev-rocm4.0-miopen2.11` 容器内执行上述命令编译异常，原因未知。
