### ISSUE TITLE
c++ 部署maskrcnn模型 使用ONNXRuntime  CreatePredictor(config)报错

### ISSUE THREAD

**Issue by zly19540609** [PaddlePaddle/Paddle#47637]
### bug描述 Describe the Bug

c++ 部署maskrcnn模型 使用ONNXRuntime  CreatePredictor(config)报错
[ERROR] Cannot find float data from attr: sampling_ratio in op: roi_align

### 其他补充信息 Additional Supplementary Information
paddle_inference版本为c++ cpu版 2.3.2 cpu_avx_mkl
_No response_

**Comment by b3602sss** [comment]
检查一下模型是不是正确。https://github.com/onnx/onnx/blob/main/docs/Operators.md#RoiAlign 按onnx的定义sampling_ratio : int 是整形

**Comment by zly19540609** [comment]
使用PaddleDetection官方提供模型 模型下载地址为https://paddledet.bj.bcebos.com/models/mask_rcnn_r50_vd_fpn_2x_coco.pdparams
使用命令导出模型python tools/export_model.py -c configs/mask_rcnn/mask_rcnn_r50_vd_fpn_2x_coco.yml --output_dir=./inference_model -o weights=weights/mask_rcnn_r50_vd_fpn_2x_coco.pdparams
 PaddleDetection为2.5版本
Paddle为2.3.2版本

**Comment by b3602sss** [comment]
试一下直接用onnx看看模型有没有问题 如果有的话需要在detection下提issue

**Comment by zly19540609** [comment]
具体怎么操作，是使用paddle2onnx转换成onnx格式吗？

**Comment by b3602sss** [comment]
你用的不是onnx 模型吗？那不能跑onnx runtime

**Comment by zly19540609** [comment]
我用的是paddle的模型
