### ISSUE TITLE
paddlepaddle-gpu 2.2.2.post111 运行paddle.utils.run_check()报错

### ISSUE THREAD

**Issue by MrYYYYYYYYYYY** [PaddlePaddle/Paddle#47662]
### paddlepaddle-gpu 2.2.2.post111 运行paddle.utils.run_check()报错
操作系统版本：Linux version 4.14.0_1-0-0-44
gcc：4.8.2
cuda版本：11.1
cudnn版本： 8.1
安装paddlepaddle-gpu 2.2.2.post111 版本后在运行paddle.utils.run_check()以后报以下错误：
<img width="1438" alt="图片" src="https://user-images.githubusercontent.com/41470007/199872749-d11d2d29-48ea-4d21-8c87-c34bf4eb6827.png">
相同环境下pytorch1.9.0+cu111版本可以正常运行

**Comment by pangyoki** [comment]
你好，麻烦提供下执行`nvidia-smi`和`nvcc -V`命令的截图看看。
