### ISSUE TITLE
关于可视化工具

### ISSUE THREAD

**Issue by xiaodaomingye459** [PaddlePaddle/Paddle#47685]
### 请提出你的问题 Please ask your question

请问Paddle有没有提供类似于CAM热力图的特征可视化的工具，（可解释性分析）
或者直接显示中间特征的办法？
如果有的话，有没有使用教程，万分感谢！

**Comment by yaoxuefeng6** [comment]
https://github.com/PaddlePaddle/InterpretDL 可以看下这个哈
