### ISSUE TITLE
c++ 部署yolov3模型 使用ONNXRuntime CreatePredictor(config)报错

### ISSUE THREAD

**Issue by zly19540609** [PaddlePaddle/Paddle#47692]
### bug描述 Describe the Bug

c++ 部署yolov3模型 使用ONNXRuntime CreatePredictor(config)报错
[ERROR] Cannot found attribute iou_aware in op: yolo_box

### 其他补充信息 Additional Supplementary Information

paddle_inference版本为c++ cpu版 2.3.2 cpu_avx_mkl

**Comment by iclementine** [comment]
能说明一下你使用的是哪个代码库的代码，以及复现方法吗？

**Comment by zly19540609** [comment]
[Paddle-Inference-Demo](https://github.com/PaddlePaddle/Paddle-Inference-Demo) c++示例  cpu yolov3

**Comment by wangxinxin08** [comment]
具体使用的命令是啥啊？这个demo里面： https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/001b2b5d9e77be4d82e179eae20a0b05f125dc5c/c%2B%2B/gpu/yolov3 只有Paddle的部署方式啊

**Comment by zly19540609** [comment]
里边cpu示例 不是GPU的 https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/c%2B%2B/cpu/yolov3

**Comment by wangxinxin08** [comment]
好的，我们先复现下
