### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by zcswdt** [PaddlePaddle/Paddle#47696]
### 请提出你的问题 Please ask your question

您好，我是按照说明安装，完成了以后报错。
![image](https://user-images.githubusercontent.com/43515926/200164305-45386806-2a5c-40c6-b81b-91014f8586ac.png)

**Comment by huangjun12** [comment]
日志显示，安装的cuda是11.0版本，安装paddle时也需要安装cuda11.0对应的版本。
没有现成cuda11.0的whl包，需要自行编译
或者把cuda升级到11.1
