### ISSUE TITLE
使用paddlex端侧部署paddleseg

### ISSUE THREAD

**Issue by fanxiaochen456** [PaddlePaddle/Paddle#47694]
### 请提出你的问题 Please ask your question

您好，我使用的部署方式为C++编译paddlex-develop然后用编译好的paddlex推理paddleseg，现在我想使用arm架构的linux平台来部署paddleseg，请问还是想使用paddlex部署paddleseg的方式在arm架构的linux平台应该怎么操作呢？还是说要更换部署方式改用paddle-Lite部署paddleseg呢？

**Comment by iclementine** [comment]
你可以导出 paddleseg 的模型（可以使用 Paddle 的推理模型格式或者 Onnx 模型的格式），然后使用 Paddle Lite 方式部署 PaddleSeg. 可以参考 PaddleSeg 的文档。
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.6/docs/deployment/lite/lite_cn.md

**Comment by fanxiaochen456** [comment]
@iclementine 您好，当我测试官网提供的Paddle-Lite-Demo里的human_segmentation里的demo时出现了以下错误：
![147422561322895156](https://user-images.githubusercontent.com/101849755/200288502-0455170b-54dc-4170-bfec-48796b8c44de.png)
请问这是什么问题呢？

**Comment by iclementine** [comment]
这种情况一般是缺少相应的头文件或者透哦文件版本不对。float32x4_t 之类的类型应该是 arm_neon 提供的。你能说说你构建工程的流程吗？

**Comment by hong19860320** [comment]
> @iclementine 您好，当我测试官网提供的Paddle-Lite-Demo里的human_segmentation里的demo时出现了以下错误： ![147422561322895156](https://user-images.githubusercontent.com/101849755/200288502-0455170b-54dc-4170-bfec-48796b8c44de.png) 请问这是什么问题呢？

原始 demo 有问题吗？看起来是在你自己工程编译出现问题的，可能是你的 cmake 脚本问题，可以先编译 arm64-v8a 试试 https://github.com/PaddlePaddle/Paddle-Lite-Demo/blob/586b0d13757118f366ae22d88560acc6b4a0dd9f/human_segmentation/android/shell/cxx/human_segmentation/CMakeLists.txt#L18

**Comment by fanxiaochen456** [comment]
@iclementine 您好，使用自带的opencv出现了以下错误：
![图片](https://user-images.githubusercontent.com/101849755/201277252-eac62c36-4db0-4fe1-bd57-9373adc6287f.png)
我使用的是ARM32的linux平台，这是我使用的build.sh
![图片](https://user-images.githubusercontent.com/101849755/201277343-5c6b30c0-6758-416c-b2b4-fba0aa069918.png)
这是我的CMakeLists.txt
![图片](https://user-images.githubusercontent.com/101849755/201277423-f6fdf3f8-21e0-4185-860e-fe2a6dbc331d.png)

**Comment by hong19860320** [comment]
我看了下 Paddle-Lite-Demo 没有提供 armlinux 版本的human_segementation 的 demo ，只提供了 Android 和 ios的，你是准备自己迁移到 armlinux 时遇到问题了吗?

**Comment by fanxiaochen456** [comment]
@hong19860320 是的，现在那个问题没有了，他出来了一个新的错误，
![图片](https://user-images.githubusercontent.com/101849755/201308630-66866283-61fe-4501-9776-51da2faf925e.png)
这是要指定他的device吗？

**Comment by fanxiaochen456** [comment]
@hong19860320 我的实际应用平台是选用的linux平台，然后使用的算法是paddle-seg，就想使用paddle-lite在linux平台的开发板上部署paddleseg

**Comment by hong19860320** [comment]
> @hong19860320 是的，现在那个问题没有了，他出来了一个新的错误， ![图片](https://user-images.githubusercontent.com/101849755/201308630-66866283-61fe-4501-9776-51da2faf925e.png) 这是要指定他的device吗？

你要改下 run.sh 脚本，它是为 android 准备的，建议看看 fastdeploy https://github.com/PaddlePaddle/FastDeploy

**Comment by fanxiaochen456** [comment]
@hong19860320 您好，请问可以提供一个fastdeploy具体的参考案例吗，就是run.sh

**Comment by fanxiaochen456** [comment]
@hong19860320 您好，加载模型出现了以下错误：model.nb不可识别的文件格式

**Comment by hong19860320** [comment]
> @hong19860320 您好，加载模型出现了以下错误：model.nb不可识别的文件格式

可以先看下 Paddle Lite 文档 https://www.paddlepaddle.org.cn/lite/develop/guide/introduction.html，model.nb 是paddle lite的模型，你把详细的错误log和代码发一下，建议在 Paddle Lite repo 提下 issue
