### ISSUE TITLE
PaddleDetection换了一个设备，环境和C++代码相同，GPU推理错误，CPU正确

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#47755]
### 请提出你的问题 Please ask your question

使用PaddleDetection-release-2.5分支代码。
C++的推理代码，在本机中编译和推理均正确，但是代码和推理库拷到另一台设备上，另一个设备环境和本机一致，代码和paddle_inference推理库均一致。但是使用GPU推理，却报错了，点的位置乱了，opencv报错。  但是--device=CPU 就可以正确推理。
  请问这是个什么原因呢？

CPU版本正确的输出：
(base) alex@alex-System-Product-Name:~/Pictures/cpp$ ./build/main --device=CPU
total images = 10, batch_size = 1, total steps = 10
class=0 confidence=0.9820 rect=[54 29 677 429]
./test_pic/11.jpg The number of detected box: 1
Visualized output saved as output/11.jpg
class=0 confidence=0.9790 rect=[0 11 352 235]
./test_pic/17.jpg The number of detected box: 1
Visualized output saved as output/17.jpg
class=0 confidence=0.9731 rect=[88 144 634 503]
./test_pic/18.jpg The number of detected box: 1
Visualized output saved as output/18.jpg

GPU版本错误的报错信息：
(base) alex@alex-System-Product-Name:~/Pictures/cpp$ ./build/main --device=GPU
total images = 10, batch_size = 1, total steps = 10
class=0 confidence=285058.0000 rect=[-16285037 -20417588 -20080084 -18133206]
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.7) /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/PaddleOCR-wtj/deploy/cpp_infer/opencv-3.4.7/modules/core/src/matrix.cpp:424: error: (-215:Assertion failed) 0 <= _rowRange.start && _rowRange.start <= _rowRange.end && _rowRange.end <= m.rows in function 'Mat'

已放弃 (核心已转储)

**Comment by JZ-LIANG** [comment]
请对齐两个设备上 OpenCV 的环境。这种情况很多情况是设备1 的 OpenCV 版本和 设备2 不同，推荐直接在 设备2 生重新编译PaddleDetection

**Comment by ainndejj11** [comment]
> 

就是在设备1上编译的opencv3.4.7  然后把这个opencv3.4.7也拷到了设备2上，然后设备2推理有问题
如果是opencv的问题，请问为什么使用CPU就可以正确识别呢？

**Comment by JZ-LIANG** [comment]
opencv 对 gpu 的依赖库拷完了吗 。。。。。。
