### ISSUE TITLE
Error: Can not import noavx core while this file exists

### ISSUE THREAD

**Issue by menkeyi** [PaddlePaddle/Paddle#47757]
(paddle_2_3_cuda_11_6) root@admin:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"

(paddle_2_3_cuda_11_6) root@admin:~# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_Mar__8_18:18:20_PST_2022
Cuda compilation tools, release 11.6, V11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0

(paddle_2_3_cuda_11_6) root@admin:~# nvidia-smi
Tue Nov  8 06:58:13 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.56.06    Driver Version: 520.56.06    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A100 80G...  Off  | 00000000:4F:00.0 Off |                    0 |
| N/A   50C    P0   310W / 300W |  74596MiB / 81920MiB |     98%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

(paddle_2_3_cuda_11_6) root@admin:~# python -m pip install paddlepaddle-gpu==2.3.2.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

>>> import paddle
Error: Can not import avx core while this file exists: /root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/core_avx.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/core.py", line 298, in <module>
    raise e
  File "/root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/core.py", line 256, in <module>
    from . import core_avx
ImportError: /root/anaconda3/envs/paddle_2_3_cuda_11_6/lib/python3.9/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE
>>>

啥情况啊

**Comment by JZ-LIANG** [comment]
编译时cmake 指令不正确， 请参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile

**Comment by menkeyi** [comment]
意思是我这个环境必须手动编译才可以？

**Comment by menkeyi** [comment]
> 编译时cmake 指令不正确， 请参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile

**Comment by menkeyi** [comment]
> 编译时cmake 指令不正确， 请参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile

我这个情况是必须手动编译安装呗

**Comment by jzhang533** [comment]
This is a known issue, and has been fixed.
see #36801 for details.
