### ISSUE TITLE
paddle的stft函数和pytorch的stft函数在参数一致的情况下输出相差很多是为什么呢？

### ISSUE THREAD

**Issue by zxcd** [PaddlePaddle/Paddle#47750]
### bug描述 Describe the Bug

torch.stft(audio, N_FFT, HOP_LENGTH, window=window) 
输出第一行前三个[-1.0551e-02+0.0000e+00j, 2.1227e-03+0.0000e+00j, 8.4413e-03+0.0000e+00j 

paddle.signal.stft(audio, N_FFT, HOP_LENGTH, window=window) 
输出第一行前三个[[(-0.01521775871515274+0j) , (0.0030614458955824375+0j) , (0.012174495495855808+0j)

此时参数：
N_FFT = 400
HOP_LENGTH = 160
window = torch.hann_window(N_FFT)
audio 使用en.wav

**Comment by JZ-LIANG** [comment]
看了一下paddle stft 的输入，参数含义是和pytorch 一致的

但paddle stft单测中只是和 np 对齐， 没有和和pytorch 对齐的单测

python/paddle/fluid/tests/unittests/test_stft_op.py

请检查输出结果和 np 结果是否对齐符合预期，是否满足需求。 

如果明确需要精度和 pytorch 对齐，需要和 paddle PM 提需求。
