### ISSUE TITLE
PaddleClas模型库在训练数据加载部分使用.next() 在Paddle框架commit 4061b1b88f72b3dc5c767d2f026a94515cf0c814合入后报错

### ISSUE THREAD

**Issue by quanxiang-liu** [PaddlePaddle/Paddle#47788]
### bug描述 Describe the Bug

PaddleClas模型库在训练数据加载部分使用.next() 在Paddle框架commit 4061b1b88f72b3dc5c767d2f026a94515cf0c814合入后报错

复现方法：
安装 4061b1b88f72b3dc5c767d2f026a94515cf0c814 对应的Paddle Develop分支包
git clone https://github.com/PaddlePaddle/PaddleClas
cd PaddleClas
cd dataset/
wget https://paddle-imagenet-models-name.bj.bcebos.com/data/flowers102.zip
unzip flowers102.zip
cd ..
python tools/train.py -c ./ppcls/configs/quick_start/new_user/ShuffleNetV2_x0_25.yaml

报错信息如下：
![image](https://user-images.githubusercontent.com/38774750/200731574-07137868-69b7-4360-8855-14c22d8b80c8.png)

**Comment by pangyoki** [comment]
你好，看起来这个commit是删除了python2相关方法，因为paddle已经不支持python2了，请问你使用的python版本是什么？
如果是python3，麻烦尝试下将next方法改成__next__看行不行。
这个改动对套件库可能属于不兼容升级，我找相关同学讨论下这个事情。
