### ISSUE TITLE
operators needed by word embedding

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#4779]
* [x] fully connected  @Xreki 
* [x] cross entropy @jacquesqiao @lcy-seso 
* [x] lookup table, sparse gradient
* [x] sparse sum
* [x] sparse optimizers
* [x] nce cost
* [ ] hsigmoid  @Yancey1989 doing

**Comment by qingqing01** [comment]
We need to optimize sparse updating, but we also can use the dense lookup-table at first.

**Comment by lcy-seso** [comment]
I support @qingqing01 's concern.

**Comment by wangkuiyi** [comment]
I would be great if we can have a design doc about sparse updating, even if it is not urgent in the next few weeks. I searched the repo, but cannot find one.
