### ISSUE TITLE
Paddle Inference building error with ninja failed

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#47807]
### 问题描述 Issue Description

在windows OS下，编译Paddle Inference出错，错误日志如下：
```
D:\AIT\Paddle-Inference\Paddle\build_gpu\third_party\eigen3\src\extern_eigen3\unsupported\Eigen\CXX11\src/Tensor/TensorDeviceGpu.h(57): here

56 errors detected in the compilation of "../paddle/phi/kernels/funcs/eigen/broadcast.cu".
broadcast.cu
ninja: build stopped: subcommand failed.
```

### 版本&环境信息 Version & Environment Information

1. PaddlePaddle commit: b1fb2360e39269bcc93cafcf00200988073ad825
2. WITH_GPU=ON
3. 系统环境：Windows

**Comment by pangyoki** [comment]
你好，报错日志麻烦截取更多信息，可以看到是哪儿出现error了吗？

**Comment by niuhaitaofeilong** [comment]
您好，详细信息如下：
按照如下链接进行Paddle Inference 编译。cpu版本编译成功，gpu版本编译报错。

https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/compile/source_compile_under_Windows.html](https://wx.qq.com/cgi-bin/mmwebwx-bin/webwxcheckurl?requrl=https%3A%2F%2Fwww.paddlepaddle.org.cn%2Finference%2Fv2.4%2Fguides%2Finstall%2Fcompile%2Fsource_compile_under_Windows.html&skey=%40crypt_246577b4_ebb1be2841f9bdaff830a3ab717ddcab&deviceid=e123094347713850&pass_ticket=boxcJ9FKgGvp6eACifBHERTq4rq3jf2n2gqBQjersdT46aHQ15w4P%252FkdO7ADM%252FS6&opcode=2&scene=1&username=@88c9996e0368cafdb328515ac5b3e04bee0d530b6b35953b684e133f62dd8920)

配置信息：
Cuda compilation tools, release 11.1, V11.1.74
python 版本： Python 3.7.1
命令：
cmake .. -GNinja -DWITH_GPU=ON  -DCMAKE_BUILD_TYPE=Release -DWITH_UNITY_BUILD=ON -DWITH_TESTING=OFF -DON_INFER=ON
 ninja -j16

报错信息：

![image](https://user-images.githubusercontent.com/39897311/200976259-f7fe5973-f0de-49ef-a71d-fd5cc687081b.png)
![image](https://user-images.githubusercontent.com/39897311/200976329-3798bed1-f3ac-4118-87d7-6026be65d9c1.png)
![image](https://user-images.githubusercontent.com/39897311/200976351-acbe767d-8082-4b4b-9ae0-0917ca4e87d5.png)
![image](https://user-images.githubusercontent.com/39897311/200976389-580a69ad-a3e8-4d83-b0db-83970809470d.png)

**Comment by niuhaitaofeilong** [comment]
![675594747](https://user-images.githubusercontent.com/39897311/200976470-09d5ff14-bb9f-4ba0-9453-fa29946ee2f1.jpg)
![1041748586](https://user-images.githubusercontent.com/39897311/200976475-9ad8f9e7-1fa6-4158-aef3-98b184aeff36.jpg)
![1287081097](https://user-images.githubusercontent.com/39897311/200976476-1c7e7c7c-0d15-4e73-8584-f70842d44a35.jpg)
![1439361048](https://user-images.githubusercontent.com/39897311/200976478-c2cca593-a2e1-4005-a606-8ce0303eb859.jpg)

**Comment by wanghaoshuang** [comment]
关于windows下使用pip安装PaddleInfence

在2.4.0rc版本之后，不用单独安装Paddle Inference,  安装PaddlePaddle训练包即可, 参考这里：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/install/pip/frompip.html
