### ISSUE TITLE
operators needed by recommender system

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#4780]
* [x] fully connected
* [x] lookup table, sparse gradient
* [x] sequence conv pool
* [x] cos sim
* [x] sparse optimizers, adam
* [x] square error cost

**Comment by mkliegl** [comment]
I was looking a little at what is needed to finish sequence conv pool.

## Option 1

The current implementation seems to be a composite layer consisting of context projection + fully connected + sequence pool:

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/networks.py#L40

It looks like we already have C++ ops for fully connected and sequence pool, so only context projection seems to be missing for this route.

## Option 2

context projection + fully connected is a special case of sequence convolution, as the name "sequence conv pool" already implies.

If we go this route, it would make more sense to prioritize implementing a sequence conv op than a context projection op.

## Questions

- Do others have a preference between Options 1 and 2?
- Is somebody else already working on any of sequence pool / sequence conv / context projection / sequence conv pool layer?

**Comment by chengduoZH** [comment]
I'm developing [context_project_op](https://github.com/PaddlePaddle/Paddle/pull/4814) code, and it's probably going to be done this week.

**Comment by qingqing01** [comment]
@mkliegl @chengduoZH discussed with me a few days ago. Now I prefer to the second option.

**Comment by luotao1** [comment]
I'm developing sequence pool code, and it's probably going to be done this week.
- max_seq (doing) : https://github.com/PaddlePaddle/Paddle/pull/4864
- last_seq/first_seq/sqrt_seq (done) : https://github.com/PaddlePaddle/Paddle/pull/4788
- sum_seq/average_seq (done) : https://github.com/PaddlePaddle/Paddle/pull/4193

**Comment by chengduoZH** [comment]
[sequence conv](https://github.com/PaddlePaddle/Paddle/pull/4814) has been merged. @QiJune
