### ISSUE TITLE
EISeg-Med3D环境安装报错

### ISSUE THREAD

**Issue by masamimayu** [PaddlePaddle/Paddle#47819]
### 问题描述 Issue Description

第三步
import sys
import os
sys.executable # 'E:/3D slicer/Slicer 5.1.0-2022-09-27/bin/PythonSlicer.exe'

os.system(f"'{sys.executable}' -m pip install paddlepaddle-gpu==2.3.2.post116 -f  https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html")
提示文件名、目录名或卷标语法不正确

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.3.2
Paddle With CUDA: True

OS: Windows 10
Python version: 3.8.8

CUDA version: 11.6.124
Build cuda_11.6.r11.6/compiler.31057947_0
Nvidia driver version: 512.89

**Comment by zhwesky2010** [comment]
@masamimayu 你好，这个再适配一下sys.executable的字符路径是不是哪里有问题吧

**Comment by masamimayu** [comment]
> @masamimayu 你好，这个再适配一下sys.executable的字符路径是不是哪里有问题吧

你好，字符路径修改了应该没有问题，最后还是提示文件名、目录名或卷标语法不正确。是不是os.system后面语句的问题？

**Comment by zhwesky2010** [comment]
@masamimayu  我用 `os.system("{} -m pip install paddlepaddle-gpu==2.3.2.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html".format(sys.executable))` 跑通了

![infoflow 2022-11-11 17-05-46](https://user-images.githubusercontent.com/52485244/201305626-95297490-a39a-4b62-bdb3-225a03226b20.png)
