### ISSUE TITLE
pylint docstring checker 不工作原因及可能的解决方案

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#47821]
### 问题描述 Please describe your issue

目前 Paddle 的 pre-commit hooks 里是有 pylint 的，见

https://github.com/PaddlePaddle/Paddle/blob/7c30253841b5e1f6091d61aa0785b950d6c0a904/.pre-commit-config.yaml#L77-L84

这是一个 local hook，hook 源码见

https://github.com/PaddlePaddle/Paddle/blob/7e914386bb889b3ea6ccc9dfdbb9964ec83b8f2d/tools/codestyle/pylint_pre_commit.hook#L1-L25

其实就是关闭所有的 pylint 内置规则，仅仅启用了本地自己写的 docstring_checker 规则

https://github.com/PaddlePaddle/Paddle/blob/develop/tools/codestyle/docstring_checker.py

具体规则可见：

https://github.com/PaddlePaddle/Paddle/blob/7e914386bb889b3ea6ccc9dfdbb9964ec83b8f2d/tools/codestyle/docstring_checker.py#L122-L159

简单来说就是对函数有无 docstring、docstring 长度、包含字段等等做出了一些限制（比如含 `return` 语句的函数、类其 docstring 必须包含 `Returns` 字段，包含 `raise` 语句的则必须包含 `Raises` 等等，其实这个已经与现有的文档规范不一致了）

该 hook 于 #9848 最开始引入并在本地仅起到提示的作用，而在 #11351 正式启用，当时应该是可以在 CI 正确拦截有问题的 docstring 的

之后不清楚什么时候 CI 逻辑修改了导致该 hook 在 CI 上完全失效，cpplint hook 也有相似问题（见 https://github.com/PaddlePaddle/Paddle/pull/46102#issuecomment-1248535300 ），这个问题在 #46136 修复了，其实 cpplint 问题还好，至少本地是 work 的，只是 CI 不 work 而已，而 pylint hook 因为直接使用 git diff 获得改动的文件，在 git 工作区干净的情况下是不会有任何输出的，而我们 commit 时绝大多数情况工作区都是干净的，简单来说，就是本地、CI 基本都不 work

因此 pylint docstring 的存量问题……很吓人，我们可以通过以下方式大概看一下存量：

```bash
pip install pylint==2.12.0
cd tools/codestyle
pylint --disable=all --load-plugins=docstring_checker \
    --enable=doc-string-one-line,doc-string-end-with,doc-string-with-all-args,doc-string-triple-quotes,doc-string-missing,doc-string-indent-error,doc-string-with-returns,doc-string-with-raises ../../python
```

唔，也就 17000+ 行输出吧……

这样的话直接启用肯定不可取，但如果修改一下脚本也许可以考虑一下，比如：

- 单测不需要强制有 docstring
- 强制有 Raises 可以删除或者改成强制没有 Raises
- fluid 目录也可以暂时不管，像 flake8 做的那样
- 等等等等

或者我们可以考虑直接按照新的需求重写一下

不过就算启用，修存量也是一件痛苦的事情，对于 docstring，我还没有找到一个比较合适的自动化修复工具，这意味着可能很大程度依赖于手动修复 / 自己写脚本

此外说一个算是有点相关的问题，[Call-for-contribution - IDEA：iScan 流水线退场](https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions#ideaiscan-%E6%B5%81%E6%B0%B4%E7%BA%BF%E9%80%80%E5%9C%BA) 中提到了可能会考虑 PR-CI-iScan-Python 的替代方式，如果考虑在 pre-commit 中的 pylint 来替代的话，就需要考虑开启其他规则，因此想要用 pylint 替代该流水线可能需要先修复下 pylint hook 的问题

**Comment by SigureMo** [comment]
@Ligoml 这里我整理了下 pylint 存在的问题及可能的修复方式，可能对规范 docstring 格式 / 内容有所帮助

PS: 这个原本是想和 cpplint 一起修的，[flake8 tracking issue](https://github.com/PaddlePaddle/Paddle/issues/46039#issuecomment-1264625301) 里也一直放着这个的 TODO，但也因为上面所说的，存量很难修，所以暂时没有管

**Comment by Ligoml** [comment]
收到，很有用的信息~

**Comment by jzhang533** [comment]
So sad to know this. :(

除了在pre-commit阶段做检查之外，我们另外一个值得做的事情是吧[doctest](https://docs.python.org/3/library/doctest.html) 或者 [xdoctest](https://github.com/Erotemic/xdoctest)，这类工具引入到paddle。相比于现在我们的流水线中，简单的把示例代码抽取出来，直接运行，看是否运行成功的检查来说，这类工具能提供更加灵活（如：运行前设置不同的运行环境），更精准的测试（直接检查运行出来的结果是否符合设定的预期）。
