### ISSUE TITLE
HAPI loss调用机制不合理

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/Paddle#47824]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/5004c33a3834ccfe330ae0b1e134f947dce5b9a5/python/paddle/hapi/model.py#L801

如上所示，如果nn.Layer模型具有多个输出，或具有多个label时，将输出与label平铺在loss入参里，会使得loss设计者迷惑。

因为Loss设计者不知道应当把哪几个入参当作输出，而哪几个入参作为label

建议改为

```python3
losses = self.model._loss(to_list(outputs), labels))
```

这样将模型输出与label忠实地传递给loss函数

但是这一改动将使得loss入参由
```
tensor1, tensor2, ..., tensorN
```
变为
```
[tensor1, tensor2, ...], [label_tensor1, label_tensor2, ...]
```
可能影响现在的hAPI用户，需要评估是否接受此修改，或者是否有更好的解决办法

**Comment by wanghuancoder** [comment]
请@heavengate 及时回复，感谢！
