### ISSUE TITLE
ubuntu下编译paddle源码报错

### ISSUE THREAD

**Issue by thrkingd** [PaddlePaddle/Paddle#47826]
### 问题描述 Issue Description

我在ubuntu下编译paddle源码报错，错误信息如下：
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x90)：对‘CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x180)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x260)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x298)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
collect2: error: ld returned 1 exit status
paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/build.make:1898: recipe for target 'paddle/fluid/eager/auto_code_generator/eager_generator' failed
make[2]: *** [paddle/fluid/eager/auto_code_generator/eager_generator] Error 1
CMakeFiles/Makefile2:462229: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all' failed
make[1]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x90)：对‘CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x180)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x260)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x298)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/build.make:1900: recipe for target 'paddle/fluid/pybind/op_function_generator' failed
make[2]: *** [paddle/fluid/pybind/op_function_generator] Error 1
CMakeFiles/Makefile2:453595: recipe for target 'paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/op_function_generator.dir/all] Error 2
CMakeFiles/kernel_signature_generator.dir/kernel_signature_generator.cc.o：在函数‘phi::DefaultKernelSignatureMap::Get(std::string const&) const’中：
kernel_signature_generator.cc:(.text._ZNK3phi25DefaultKernelSignatureMap3GetERKSs[_ZNK3phi25DefaultKernelSignatureMap3GetERKSs]+0x3ab)：对‘phi::ErrorSummary::to_string() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x90)：对‘CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x180)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x260)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x298)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/build.make:1900: recipe for target 'paddle/fluid/pybind/kernel_signature_generator' failed
make[2]: *** [paddle/fluid/pybind/kernel_signature_generator] Error 1
CMakeFiles/Makefile2:454780: recipe for target 'paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/all] Error 2
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x90)：对‘CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x180)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x260)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE[_ZTVN8CryptoPP20ConcretePolicyHolderINS_5EmptyENS_22AdditiveCipherTemplateINS_20AbstractPolicyHolderINS_28AdditiveCipherAbstractPolicyENS_14CTR_ModePolicyEEEEES4_EE]+0x298)：对‘non-virtual thunk to CryptoPP::AdditiveCipherTemplate<CryptoPP::AbstractPolicyHolder<CryptoPP::AdditiveCipherAbstractPolicy, CryptoPP::CTR_ModePolicy> >::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE0ENS_8Rijndael3EncEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
../framework/io/crypto/libpaddle_crypto.a(aes_cipher.cc.o):(.data.rel.ro._ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE[_ZTVN8CryptoPP16BlockCipherFinalILNS_9CipherDirE1ENS_8Rijndael3DecEEE]+0x100)：对‘non-virtual thunk to CryptoPP::Rijndael::Base::AlgorithmProvider[abi:cxx11]() const’未定义的引用
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/eager_op_function_generator.dir/build.make:1900: recipe for target 'paddle/fluid/pybind/eager_op_function_generator' failed
make[2]: *** [paddle/fluid/pybind/eager_op_function_generator] Error 1
CMakeFiles/Makefile2:455965: recipe for target 'paddle/fluid/pybind/CMakeFiles/eager_op_function_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/eager_op_function_generator.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

### 版本&环境信息 Version & Environment Information

系统环境：
os：ubuntu16.04
cuda：11.1
cudnn：8.1.1
tensorrt：7.2.3.4
paddle版本：
release/2.3
软件环境：
cmake：3.15.0
python：3.7.13
numpy:1.21.6
protobuf: 3.11.3
pycryptodome  3.10.1
编译选项:
cmake ..  -DPY_VERSION=3.7 -DTENSORRT_ROOT=/usr/local/TensorRT-7.2.3.4 -DCUDA_ARCH_NAME=Auto  -DWITH_TENSORRT=ON

**Comment by thrkingd** [comment]
补充一下编译器的版本：
gcc：8.4.0
g++：8.4.0

**Comment by wjj19950828** [comment]
@thrkingd 具体编译可以参考这个文档：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs-official/guides/install/compile/source_compile_under_Linux.md

**Comment by thrkingd** [comment]
我基本是参考这个文档做的，只是系统环境略有区别，这个报错貌似是源码中对CryptoPP这个库的引用有问题，是这个包pycryptodome 有版本要求吗？
