### ISSUE TITLE
Recommend to use logger instead of print function

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#47834]
### 需求描述 Feature Description

Logger module can help users easier to see where and when a logging is being made from, but some Paddle module still uses print to show messages. For instance,

test_logger.py

```python
from paddle.fluid.log_helper import get_logger

print('[Warning] Print warning message')
logger = get_logger(__name__, logging.INFO, 
    fmt='%(asctime)s :: %(levelname)s :: Module %(module)s :: Line No %(lineno)s :: %(message)s'
)
logger.warning('Logger warning message')
```

result

```python
python3 test_logger.py
[Warning] Print warning message
1203: Thu Sep 29 01:36:10 :: WARNING :: Module test_logger :: Line No 7 :: Logger warning message
```

The logger module is better for users to know the time, severity, and the python module where the message from. It should be implemented into python modules in Paddle.

### 替代实现 Alternatives

- Replace `print` function with `logger` module
- Add a CI test to check there is no print function in modified or new python module (warn users to use logger instead of print)

**Comment by wanghuancoder** [comment]
非常感谢您的反馈。说的是有道理的！这方面确实应该统一梳理并监管起来。
我将反馈给PM，由他们适时推动该工作！

**Comment by onecatcn** [comment]
@leo0519 thanks a lot for the valuable suggesitons.

**Comment by jzhang533** [comment]
To anyone who is looking this issue, if you have interest in working on this, please feel free to pick this issue.

And we do have a project idea regarding logging system in paddle: [IDEA：改进飞桨框架的logging系统](https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions#idea%E6%94%B9%E8%BF%9B%E9%A3%9E%E6%A1%A8%E6%A1%86%E6%9E%B6%E7%9A%84logging%E7%B3%BB%E7%BB%9F), if anyone has interest in being a mentor to work on this, we can utilize [this process](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/guide-to-call-for-contribution.md) to implement it.

**Comment by leo0519** [comment]
Hi @luotao1 , is there any update about this issue?

**Comment by luotao1** [comment]
@leo0519 Sorry, no progress now😢

**Comment by tianshuo78520a** [comment]
https://github.com/PaddlePaddle/Paddle/pull/53725 进行监控
