### ISSUE TITLE
SystemError: (Fatal) Operator where_index raises an paddle::memory::allocation::BadAlloc exception.

### ISSUE THREAD

**Issue by David-19940718** [PaddlePaddle/Paddle#47832]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/38575158/201008460-a07c5b9a-751b-4a65-92d1-a4c972f1f09c.png)

BatchSize设置为1还报错，训练 `picodet_lcnet_x2_5_640_mainbody.yml` 这个。

**Comment by wanghuancoder** [comment]
感谢您的反馈！请@littletomatodonkey看一下。

**Comment by littletomatodonkey** [comment]
你好，这里是因为显存不足，建议使用16/32G显存的机器训练，同时可以减小训练尺度看下

**Comment by David-19940718** [comment]
> 你好，这里是因为显存不足，建议使用16/32G显存的机器训练，同时可以减小训练尺度看下

您好，picodet_lcnet_x2_5_640_mainbody.yml 这个模型需要占的显存那么大吗，我BatchSize设置为1都训练不了？

**Comment by David-19940718** [comment]
我这边已经改成BS=1，用416的输入还是暴显存不足

**Comment by minutes1999** [comment]
一样出来了问题，roberta base分类模型，3090TI 24G现存，前100step 显存占用20G，但是下一个step就爆显存了。试着把batchsize减小到原来一半，前100step占用13G现存，下一个step还是飙升到24G 然后爆显存

**Comment by David-19940718** [comment]
请问下能指派个工程师帮忙解决下吗？
