### ISSUE TITLE
链接超时

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#4785]
RT，链接超时，模型已经训练了几十个batch了。错误日志如下，跟平台的同学沟通，他们的建议是修改backlog可以解决这个问题

Fri Oct 13 12:54:07 2017[1,102]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=8 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 13 12:54:07 2017[1,103]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=8 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 13 12:54:07 2017[1,81]<stderr>:+ GLOG_logtostderr=0
Fri Oct 13 12:54:07 2017[1,81]<stderr>:+ GLOG_log_dir=./log
Fri Oct 13 12:54:07 2017[1,81]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=8 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 13 13:13:23 2017[1,88]<stderr>:F1013 13:13:23.445529 30304 SocketChannel.cpp:54] Check failed: len >= 0  peer=10.76.51.16: Connection timed out [110]
Fri Oct 13 13:13:23 2017[1,88]<stderr>:*** Check failure stack trace: ***
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x8d19fd  google::LogMessage::Fail()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x8d54ac  google::LogMessage::SendToLog()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x8d1523  google::LogMessage::Flush()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x8d1729  google::LogMessage::~LogMessage()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x8d49d7  google::ErrnoLogMessage::~ErrnoLogMessage()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x72bc71  paddle::SocketChannel::read()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x72c210  paddle::SocketChannel::readMessage()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @           0x72b2bc  paddle::SocketWorker::run()
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @     0x7fab8d882560  execute_native_thread_routine
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @     0x7fab8e55a1c1  start_thread
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @     0x7fab8cff30ad  __clone
Fri Oct 13 13:13:23 2017[1,88]<stderr>:    @              (nil)  (unknown)
Fri Oct 13 13:13:23 2017[1,88]<stderr>:./start_server.sh: line 33: 28186 Aborted                 GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_pserver2 --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --nics=${nics} ${server_arg} --rdma_tcp=${rdma_tcp} --comment=$comment
Fri Oct 13 13:13:23 2017[1,88]<stderr>:+ check_return 'paddle_pserver2 failed'
Fri Oct 13 13:13:23 2017[1,88]<stderr>:+ '[' 134 -ne 0 ']'
Fri Oct 13 13:13:23 2017[1,88]<stderr>:+ echo '[./start_server.sh : 34] [main]'
Fri Oct 13 13:13:23 2017[1,88]<stderr>:[./start_server.sh : 34] [main]
Fri Oct 13 13:13:23 2017[1,88]<stderr>:+ echo '[FATAL]: paddle_pserver2 failed'

**Comment by typhoonzero** [comment]
先根据 https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/cluster/index_cn.rst 排查是否是其他原因引起的问题。如果可以确定是backlog的问题，等待：https://github.com/PaddlePaddle/Paddle/pull/4659 测试完成后更新二进制即可

**Comment by youan1** [comment]
谢谢，按照上述链接去排查了问题，1）connection timeout是第一个出错误的地方 2）使用的是resource=full来提交的训练任务。但由于我们是例行任务，不能不断的人工变化端口来解决问题 3）paddle那边更新二进制有时间点么，需要我们做什么

**Comment by typhoonzero** [comment]
可以先用上述PR中的代码编译一个二进制来测试。上面的二进制由于我也还在测试中，所以还没merge。

**Comment by youan1** [comment]
好的，等测试完成后，麻烦帮助我们更新一版新的二进制

**Comment by youan1** [comment]
@typhoonzero ,相应的二进制更新是否已经好了，好了的话麻烦在这里更新一下，我们在新的解决了延迟问题的版本上来做测试

**Comment by typhoonzero** [comment]
已经merge可以从 https://paddleci.ngrok.io/viewLog.html?buildId=13164&tab=artifacts&buildTypeId=CentOS6u3gcc482_LegacyBuildCPU 下载最新的whl包更新二进制。

**Comment by youan1** [comment]
@typhoonzero ,这个下载完成后，更新到哪里去，怎么更新，有说明么

**Comment by youan1** [comment]
更新使用了上面的fix 后，仍然有链接超时的问题，这个辛苦看一下

**Comment by typhoonzero** [comment]
job和其他job中的node是有重合的。节点混用了，而且端口都是一样的。应该是另一个问题。我先close本issue了。

**Comment by youan1** [comment]
节点没有混用，他们是前后提交上去的
