### ISSUE TITLE
Review operators required by books.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#4786]
The rest operators needed to be completed at first:

- Top priority: 

Op                 |  Author                   | State     |  Deadline
--------------- | :----------------|:----     | :--------------------
batch_norm   |  @zchen0211        | Done           | 
deconv      |   @zchen0211     | done [PR](https://github.com/PaddlePaddle/Paddle/pull/4739)       | 
seq_conv       | @chengduoZH      | Done [PR](https://github.com/PaddlePaddle/Paddle/pull/4814)         |  
crf_op             | @lcy-seso            | Done [PR](https://github.com/PaddlePaddle/Paddle/pull/5084)              |
crf_decoding_op | @lcy-seso       | Done        |
lstm_op          | @qingqing01         | Done            |
gru_step        | @guoshengCS    |Done [PR](https://github.com/PaddlePaddle/Paddle/pull/4443)    |
gru_op           | @guoshengCS        |Done |
first/last_seq_op | @luotao1  |Done [PR](https://github.com/PaddlePaddle/Paddle/pull/4788)| |
seq_max_op | @luotao1   | Done [PR](https://github.com/PaddlePaddle/Paddle/pull/4864) |
expand_as_op   | @wanghaoshuang |Done [PR](https://github.com/PaddlePaddle/Paddle/pull/4740) |
how to do regularization |  @abhinavarora  | Done [tasks](https://github.com/PaddlePaddle/Paddle/issues/5054)| 
beam search   | @Superjom  | |
rnn_group_op | @Superjom  | |

- Secondary priority: 

Op                 |  Author                        | State     |  Deadline
--------------- | :-------------------|:---------   | :--------------------
lookup-table by sparse row   |        |                  | 
hsigmoid_op       |  @Yancey1989  |  |
nce_op    | @lcy-seso |  |
chunk_evaluator | @guoshengCS | |

<br />

-----

### Recognize Digits And Image Classification

- [x] fc_op, conv2d_op, pool2d_op, relu_op, softmax_op, cross_entropy_op, accuracy_op
- [x] momentum_op, add_op/sum_op
- [x] batch_norm_op

### Generative Adversarial Net

- [x] fc_op, conv2d_op, pool2d_op, relu_op, softmax_op, cross_entropy_op, accuracy_op
- [x] momentum_op, add_op/sum_op
- [x] batch_norm_op
- [x] deconv_op (working)
- [x] dependency engine / anytime block creation
- [x] Multi optimizers in executors

### [Word2Vec](https://github.com/PaddlePaddle/book/blob/develop/04.word2vec/train.py)
- [x] fc_op, concat_op, softmax_op, cross_entropy_op, accuracy_op, sigmoid_op, adagrad_op
- [x] lookup_table_op (use sparse update)

### [Personalized Recommendation](https://github.com/PaddlePaddle/book/blob/develop/05.recommender_system/train.py)
- [x] lookup_table_op  (used dense table by defalut in the book)
- [x] fc_op, tanh_op, cos_sim_op, square_error_op (l2_distance_op), adam_op
- [x] sequence_conv
- [x] sparse matrix as input (maybe can use embeding as inpu)

### [Understand Sentiment](https://github.com/PaddlePaddle/book/blob/develop/06.understand_sentiment/train.py)
- [x] lookup_table_op  (used dense table by defalut in the book)
- [x] fc_op, softmax_op, cross_entropy_op, accuracy_op, relu_op, adam_op
- [x] lstm_op
- [x] sequence_conv
- [x] sequence_max

### [Semantic Role Labeling](https://github.com/PaddlePaddle/book/blob/develop/07.label_semantic_roles/train.py)
- [x] lookup_table_op (used dense table by defalut in the book)
- [x] add_op (mixed_op), fc_op,relu_op, sigmoid_op, momentum_op
- [x] lstm_op
- [x] crf_op
- [x] crf_decoding_op

### [Machine Translation](https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/train.py)
- [x] lookup_table_op (used dense table by defalut in the book)
- [x] fc_op, concat_op ,softmax_op, cross_entropy_op, accuracy_op, tanh_op, identity_op, adam_op
- [x] gru_op
- [x] gru_step
- [x] first_seq_op, last_seq_op
- [x] rnn_group_op
- [x] beam search
- [x] simple_attention
   - [x] add_op, fc_op, scaling_op (element-wise mul op)
   - [x] seq_pool_op, seq_softmax_op
   - [x] expand_as_op (seq_expand)

**Comment by jacquesqiao** [comment]
1. 10月15:  Python Api搞定

2. 10月20: 所有op readey：

3. 正则。
	可以用python拼Op实现

4. sparse_update相关的Op
	10月17之前，美国准备好相关底层支持和部分op。
        10月17和北京同步，北京可以暂时不关心
	
5. 特殊需要考虑的复杂op：
	crf, rnn, beam_search:
	时间可能有问题，需要确认

**Comment by zchen0211** [comment]
batch_norm, I will further discuss with @Canpio
