### ISSUE TITLE
文档中create_parameter无法跳转

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle#47871]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/create_parameter_cn.html  这个链接打不开，无法查看paddle.create_parameter使用方法

**Comment by SigureMo** [comment]
应该是中文文档缺失，点击侧边栏内容后没有更新 @Ligoml

<img width="275" alt="image" src="https://user-images.githubusercontent.com/38436475/201302744-55b12d00-58ab-4bb8-a072-451f7decd59d.png">

中文文档里没有发现这个文件

可以先参考英文文档 https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/create_parameter_en.html
