### ISSUE TITLE
2.4.0-rc0.post111，paddle.utils.run_check()说正常，但是跑paddlespeech说CUDA error(100), no CUDA-capable device is detected

### ISSUE THREAD

**Issue by mandylyin** [PaddlePaddle/Paddle#47874]
环境：ubuntu18.04， paddlepaddle==2.4.0-rc0.post111，PaddleSpeech开发版。

1、paddle安装成功
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W1111 09:50:22.246316 29321 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.1
W1111 09:50:22.251258 29321 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W1111 09:50:24.067153 29321 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W1111 09:50:24.067178 29321 parallel_executor.cc:666] Cannot enable P2P access from 0 to 2
W1111 09:50:24.067183 29321 parallel_executor.cc:666] Cannot enable P2P access from 0 to 3
W1111 09:50:24.067186 29321 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W1111 09:50:24.067189 29321 parallel_executor.cc:666] Cannot enable P2P access from 1 to 2
W1111 09:50:24.067193 29321 parallel_executor.cc:666] Cannot enable P2P access from 1 to 3
W1111 09:50:24.067195 29321 parallel_executor.cc:666] Cannot enable P2P access from 2 to 0
W1111 09:50:24.067198 29321 parallel_executor.cc:666] Cannot enable P2P access from 2 to 1
W1111 09:50:24.067201 29321 parallel_executor.cc:666] Cannot enable P2P access from 2 to 3
W1111 09:50:24.067204 29321 parallel_executor.cc:666] Cannot enable P2P access from 3 to 0
W1111 09:50:24.067207 29321 parallel_executor.cc:666] Cannot enable P2P access from 3 to 1
W1111 09:50:24.067210 29321 parallel_executor.cc:666] Cannot enable P2P access from 3 to 2
W1111 09:50:28.126982 29321 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 4 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>> print(paddle.__version__)
2.4.0-rc0

2、使用PaddleSpeech hard安装，跑命令行“paddlespeech asr --lang zh --input zh.wav”，报“Segmentation fault“错误：
/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/librosa/core/constantq.py:1059: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  dtype=np.complex,
W1111 10:58:01.676314 53816 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.2, Runtime API Version: 11.1
W1111 10:58:01.679399 53816 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/fluid/dygraph/math_op_patch.py:275: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.int64, but right dtype is paddle.bool, the right dtype will convert to paddle.int64
  warnings.warn(
我认为跑步最重要的就是给我带来了身体健康

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::vector<std::unique_ptr<phi::funcs::detail::FFTConfigCache, std::default_delete<phi::funcs::detail::FFTConfigCache> >, std::allocator<std::unique_ptr<phi::funcs::detail::FFTConfigCache, std::default_delete<phi::funcs::detail::FFTConfigCache> > > >::~vector()
1   cufftDestroy

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1668135487 (unix time) try "date -d @1668135487" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x18) received by PID 53816 (TID 0x7f59de5e03c0) from PID 24 ***]

Segmentation fault (core dumped)

3、跑PaddleSpeech下examples/tiny/asr1, 报没找到GPU：
2022-11-11 09:47:54.075 | WARNING  | paddlespeech.s2t.frontend.featurizer.text_featurizer:__init__:57 - TextFeaturizer: not have vocab file or vocab list.
----------- format_data.py Arguments -----------
cmvn_path: data/mean_std.json
manifest_paths: ['data/manifest.tiny.raw']
output_path: data/manifest.tiny
spm_model_prefix: data/lang_char/bpe_unigram_200
unit_type: spm
vocab_path: data/lang_char/vocab.txt
-----------------------------------------------------------
Feature dim: 80
Vocab size: 199
['data/manifest.tiny.raw'] Examples number: 64
LibriSpeech Data preparation done.
using 1 gpus...
W1111 09:48:06.233479 28383 init.cc:182] Compiled with WITH_GPU, but no GPU found in runtime.
/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/fluid/framework.py:594: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
LAUNCH INFO 2022-11-11 09:48:06,451 -----------  Configuration  ----------------------
LAUNCH INFO 2022-11-11 09:48:06,451 devices: 4
LAUNCH INFO 2022-11-11 09:48:06,451 elastic_level: -1
LAUNCH INFO 2022-11-11 09:48:06,452 elastic_timeout: 30
LAUNCH INFO 2022-11-11 09:48:06,452 gloo_port: 6767
LAUNCH INFO 2022-11-11 09:48:06,452 host: None
LAUNCH INFO 2022-11-11 09:48:06,452 ips: None
LAUNCH INFO 2022-11-11 09:48:06,452 job_id: default
LAUNCH INFO 2022-11-11 09:48:06,452 legacy: False
LAUNCH INFO 2022-11-11 09:48:06,452 log_dir: log
LAUNCH INFO 2022-11-11 09:48:06,452 log_level: INFO
LAUNCH INFO 2022-11-11 09:48:06,452 master: None
LAUNCH INFO 2022-11-11 09:48:06,452 max_restart: 3
LAUNCH INFO 2022-11-11 09:48:06,452 nnodes: 1
LAUNCH INFO 2022-11-11 09:48:06,452 nproc_per_node: None
LAUNCH INFO 2022-11-11 09:48:06,452 rank: -1
LAUNCH INFO 2022-11-11 09:48:06,452 run_mode: collective
LAUNCH INFO 2022-11-11 09:48:06,452 server_num: None
LAUNCH INFO 2022-11-11 09:48:06,452 servers:
LAUNCH INFO 2022-11-11 09:48:06,452 start_port: 6070
LAUNCH INFO 2022-11-11 09:48:06,452 trainer_num: None
LAUNCH INFO 2022-11-11 09:48:06,452 trainers:
LAUNCH INFO 2022-11-11 09:48:06,452 training_script: /zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py
LAUNCH INFO 2022-11-11 09:48:06,452 training_script_args: ['--ngpu', '1', '--seed', '0', '--config', 'conf/transformer.yaml', '--output', 'exp/transformer', '--profiler-options', '', '--benchmark-batch-size', '0', '--benchmark-max-step', '0']
LAUNCH INFO 2022-11-11 09:48:06,452 with_gloo: 1
LAUNCH INFO 2022-11-11 09:48:06,452 --------------------------------------------------
LAUNCH INFO 2022-11-11 09:48:06,453 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2022-11-11 09:48:06,454 Run Pod: yzqnbm, replicas 1, status ready
LAUNCH INFO 2022-11-11 09:48:06,469 Watching Pod: yzqnbm, replicas 1, status running
LAUNCH WARNING 2022-11-11 09:48:10,281 save gpu info failed
/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/fluid/framework.py:594: UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  warnings.warn(
LAUNCH WARNING 2022-11-11 09:48:12,703 save gpu log failed
Traceback (most recent call last):
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/exps/u2/bin/train.py", line 20, in <module>
    from paddlespeech.s2t.exps.u2.model import U2Trainer as Trainer
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/exps/u2/model.py", line 29, in <module>
    from paddlespeech.s2t.models.u2 import U2Model
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/models/u2/__init__.py", line 14, in <module>
    from .u2 import U2InferModel
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/models/u2/u2.py", line 43, in <module>
    from paddlespeech.s2t.modules.decoder import BiTransformerDecoder
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/modules/decoder.py", line 30, in <module>
    from paddlespeech.s2t.modules.attention import MultiHeadedAttention
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/modules/attention.py", line 36, in <module>
    class MultiHeadedAttention(nn.Layer):
  File "/zll/work/dev/jirui/PaddleSpeech/paddlespeech/s2t/modules/attention.py", line 92, in MultiHeadedAttention
    mask: paddle.Tensor=paddle.ones([0, 0, 0], dtype=paddle.bool)
  File "/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/tensor/creation.py", line 579, in ones
    return fill_constant(value=1.0, shape=shape, dtype=dtype, name=name)
  File "/home/zkyd/anaconda3/envs/paddle1/lib/python3.8/site-packages/paddle/fluid/layers/tensor.py", line 795, in fill_constant
    out = _C_ops.full(shape, float(value), dtype, place)
OSError: (External) CUDA error(100), no CUDA-capable device is detected.
  [Hint: Please search for the error code(100) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:66)

**Comment by zhwesky2010** [comment]
@mandylyin 这个问题一般需要排查下环境问题，是不是不同的环境、或不同的python；另外如果直接跑 `paddle.ones([0, 0, 0], dtype=paddle.bool)` 会报这样的错吗

**Comment by mandylyin** [comment]
@zhouwei25 直接跑paddle.ones([0, 0, 0], dtype=paddle.bool)不会报错，是正常的。我又重新建了环境，倒腾了几遍，目前正常了，可能是环境问题吧。多谢啦！
