### ISSUE TITLE
调用quanter.save_quantized_model报错，求助----

### ISSUE THREAD

**Issue by Genlk** [PaddlePaddle/Paddle#47906]
### 请提出你的问题 Please ask your question

使用nn.Layer 自己组网之后
构建网络net = Mynet()
插入量化算子
quanter = QAT(config=quant_config)
quanter.quantize(net)
----------------------------------------------------------------------------
启动训练，经过1个epoch可以正常保存模型（paddle.save(net.state_dict(), "./best_model"）
![image](https://user-images.githubusercontent.com/24912927/201457484-00ace0aa-3c1a-4833-ac7b-1fc61b953449.png)
如上图，正常的训练过程
----------------------------------------------------------------------------
转存量化模型的时候，会有报错（quanter.save_quantized_model(
                net,
                "./paddle_quant",
                [Input([None, 2, 320, 512], 'float32', name='input')]
            )）
![image](https://user-images.githubusercontent.com/24912927/201457709-af66bee8-428c-4eec-a3eb-b9986db752ee.png)

ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
  [Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():10 != paddle::experimental::CppTypeToDataType<T>::Type():2.] (at /paddle/paddle/phi/core/dense_tensor.cc:143)

**Comment by haozech** [comment]
您好，报错信息看起来是数据类型错误，可以修改您设置的'float32'为其他您期望量化到的数据类型再试试。
