### ISSUE TITLE
数据并行是否支持 IterableDataset 

### ISSUE THREAD

**Issue by cxy229** [PaddlePaddle/Paddle#47915]
### 请提出你的问题 Please ask your question

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/06_distributed_training/data_parallel/principle_and_demo_cn.html

你好，文档上数据并行，需要用 DistributedBatchSampler，只支持 paddle.io.Dataset
数据量很大，无法用Dataset全部读入，请问 IterableDataset 要怎么数据并行呢？

**Comment by littletomatodonkey** [comment]
你好，可以用num_workers加速，但是每个子进程都会维护一个完成iterabledataset，一个epoch数据会重复num_workers份

另外就是也可以参考这里的内容进行数据划分

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/io/IterableDataset_cn.html#iterabledataset

**Comment by cxy229** [comment]
感谢，请问有没有一个用 iterabledataset 的分布式多级多卡的demo呢? 这个文档上看着只提供了单卡多进程加载数据的写法。

**Comment by cxy229** [comment]
> 你好，可以用num_workers加速，但是每个子进程都会维护一个完成iterabledataset，一个epoch数据会重复num_workers份
> 
> 另外就是也可以参考这里的内容进行数据划分
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/io/IterableDataset_cn.html#iterabledataset

感谢，请问有没有一个用 iterabledataset 的分布式多级多卡的demo呢? 这个文档上看着只提供了单卡多进程加载数据的写法。

**Comment by littletomatodonkey** [comment]
目前应该还没有，多卡的话，需要根据get_rank()去判断当前的card id，再去做数据切分~

**Comment by gongel** [comment]
DistributedBatchSampler应该会进行划分的
