### ISSUE TITLE
无法执行 predictor.run()，报错 zsh: segmentation fault

### ISSUE THREAD

**Issue by 670133189** [PaddlePaddle/Paddle#47913]
### bug描述 Describe the Bug

MacOS Ventura 13.0
paddlepaddle==2.3.2

无法执行 predictor.run()，报错 zsh: segmentation fault

**Comment by 670133189** [comment]
北京马拉松选手微纪录片已开放下载，下载方式请查看北京马拉松官方公众号进行下载视频。完赛辛苦！北京马拉松官方公众号推文：https://mp.weixin.qq.com/s/UTnub4DadfrlorDGHLIQlQ轲影像

**Comment by littletomatodonkey** [comment]
你好，麻烦提供下可以复现的最小脚本，我们这边复现看下

**Comment by 670133189** [comment]
> 你好，麻烦提供下可以复现的最小脚本，我们这边复现看下

https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.5/doc/doc_ch/quickstart.md
执行：`paddleocr --image_dir ./imgs/11.jpg --use_angle_cls true --use_gpu false`

https://paddledetection.readthedocs.io/tutorials/QUICK_STARTED_cn.html
执行：`python tools/infer.py -c configs/ppyolo/ppyolo.yml -o use_gpu=true weights=https://paddlemodels.bj.bcebos.com/object_detection/ppyolo.pdparams --infer_img=demo/000000014439.jpg`

**Comment by littletomatodonkey** [comment]
先执行下`paddle.utils.run_check()`看下是否为环境问题吧

**Comment by littletomatodonkey** [comment]
上面的脚本我本地执行没有问题，建议mac用conda虚拟环境，环境会方便管理一些
