### ISSUE TITLE
PaddleDetection和PaddleOCR C++代码打包镜像后推理报错

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#47924]
### 请提出你的问题 Please ask your question

PaddleDetection+PaddleOCR 调用C++代码时，在镜像外测试没问题，使用Tensorrt也能跑通，然后相同的代码和paddle_inference推理库打包镜像后运行，就报错，用CPU或者GPU/Tensort都是这个错误，请问这是什么原因？

错误信息如下：
I1114 02:11:43.964516    37 analysis_config.cc:1044] In CollectShapeInfo mode, we will disable optimizations and collect the shape information of all intermediate tensors in the compute graph and calculate the min_shape, max_shape and opt_shape.
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::CreatePredictor(paddle::AnalysisConfig const&)
1   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::~AnalysisPredictor()
3   paddle::AnalysisPredictor::~AnalysisPredictor()
4   paddle::memory::allocation::AllocatorFacade::Release(phi::Place const&)
5   paddle::memory::allocation::AllocatorFacadePrivate::GetAllocator(phi::Place const&, unsigned long)

----------------------
Error Message Summary:
----------------------
NotFoundError: No allocator found for the place, Place(undefined:0)
  [Hint: Expected iter != allocators.end(), but received iter == allocators.end().] (at /paddle/paddle/fluid/memory/allocation/allocator_facade.cc:343)

**Comment by littletomatodonkey** [comment]
C++打包镜像，这块之前没有尝试过，建议在镜像里直接编译试下哈

**Comment by littletomatodonkey** [comment]
或者可以直接新建一个基于paddle的docker，在里面去做部署

**Comment by Cute-Yang** [comment]
他这个错误会偶然出现，即使是相同的程序，不同时间也会出现，请问是什么原因呢
