### ISSUE TITLE
在部署ser多输入模型时，推理阶段，auto input_names = predictor_->GetInputNames(); 报错；

### ISSUE THREAD

**Issue by xianyu211** [PaddlePaddle/Paddle#47928]
### bug描述 Describe the Bug

部署的ser模型有五个输入，定义了：std::vector<std::string> input_name_ = {"x_0", "x_1", "x_2", "x_3", "x_4"};
将五个输入依次通过：inputs->push_back(std::move(x_0))；...inputs->push_back(std::move(x_4))，送入inputs中
再进行模型推理时，执行到  auto input_names = predictor_->GetInputNames(); 报错；
显示Segmentation fault.
0x00007fffa840d9bf in paddle_infer::Predictor::GetInputNames[abi:cxx11]() () from /mnt/ssd1/lideyin/resource/paddle_inference/paddle/lib/libpaddle_inference.so

说明：ser推理模型通过paddle 2.3.2版本将训练模型转成推理模型，在paddle 2.2.0中pyhton版本使用推理模型进行了结果推理；
目前在ser推理尝试过paddle_inference2.0、paddle_inference2.2.2、paddle_inference2.3.2均出现了 auto input_names = predictor_->GetInputNames(); 报错；

**Comment by littletomatodonkey** [comment]
你用netron看下是否需要5个输入呢？我记得vi-layoutxlm的话，只需要4个输入，不需要个图像信息了
