### ISSUE TITLE
paddle功能对应torch_geometric问题

### ISSUE THREAD

**Issue by tandangzuoren** [PaddlePaddle/Paddle#47957]
### 请提出你的问题 Please ask your question

from torch_geometric.data import Batch
from torch_geometric.data import Data
from torch_geometric.nn.conv import MessagePassing
from torch_geometric.typing import Adj
from torch_geometric.typing import OptTensor
from torch_geometric.typing import Size
from torch_geometric.utils import softmax
from torch_geometric.utils import subgraph

您好，请问torch程序中用到图结构相关包，paddle有针对以上的对应功能吗
感谢！

**Comment by littletomatodonkey** [comment]
你好，可以参考PGL以及里面的相关issue哈
https://github.com/PaddlePaddle/PGL/issues/447
