### ISSUE TITLE
安装paddle-gpu无法识别gpu

### ISSUE THREAD

**Issue by jyjy007** [PaddlePaddle/Paddle#47950]
### 问题描述 Issue Description

paddle团队你们好。我最近购置一台新电脑，win10系统，配置了3070ti独立显卡。在python pip安装paddlepaddle==2.3.2和paddlepaddle-gpu==2.3.2后，使用rocketqa等开源项目均无法使用gpu。
print(paddle.device.get_device())，始终返回结果为cpu。
我在网上查了不少资料，把cuda版本切换过11.2/11.0/10.2，并更新对应cudnn版本，python版本试了3.9和3.8，也配置了环境变量，均没有成功。
今天试了安装cuda11.0对应的tensorflow2.4，可以识别出gpu。
之前用公司配置好的环境，cuda10和11，均没有问题，可以使用paddlenlp等项目。
不知道还有什么遗漏，请官方大佬们给个回应？ 

### 版本&环境信息 Version & Environment Information

paddlepaddle2.3.2
paddlepaddle-gpu2.3.2
win10
cuda11.0.3
cudnn8.0.2
python3.8
NVIDIA GeForce RTX 3070 Ti Laptop GPU
driver517.00？31.0.15.1700？

**Comment by littletomatodonkey** [comment]
你好，可以先把paddlepaddle与paddlepaddle-gpu都卸载掉，然后重新安装paddlepaddle-gpu就好

**Comment by jyjy007** [comment]
你好，已经解决了。。。

**Comment by Threedoves31** [comment]
太感谢了，解决了
