### ISSUE TITLE
matmul operator is much much slower than torch and numpy

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/Paddle#47982]
### bug描述 Describe the Bug

paddle.matmul在文档说明中表示和numpy行为一致，但是在高维（7维）tensor计算的时候速度比numpy计算慢很多，matmul应该是最常用的op，这个速度上为什么会这么慢呢？
![8d60e00a059b54e5d40f3a2cdf16025d](https://user-images.githubusercontent.com/29754889/201816907-fc6d18a1-1e12-4b49-87bd-d3d1a85d5b32.png)

**Comment by wawltor** [comment]
好的，我们排查一下
