### ISSUE TITLE
paddle Tensor alternative API  about `record_stream`

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#47991]
### 请提出你的问题 Please ask your question

Hi, could you please tell me where an alternative `Tensor.record_stream` API is, which just like `torch.Tensor.record_stream`?

I need control the corrent Stream just like this:

```python
paddle.device.cuda.current_stream().wait_stream(self.stream)
......
if samples is not None:
    samples.record_stream(paddle.device.cuda.current_stream())
```

`samples` is a Paddle Tensor

**Comment by tink2123** [comment]
Sorry, paddle does not have an alternative API for `Tensor.record_stream` now, we will make a note of this requirement.
