### ISSUE TITLE
运行PaddleOCR  C++代码时，显存占用很高。

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#47994]
### 请提出你的问题 Please ask your question

运行PaddleOCR  C++代码时，将gpu_mem参数设置成=500
1.使用GPU进行运行推理，加载图片时候，显存先占大约1.3G，然后涨到1.9个G (无论gpu_mem设置多少，都是稳定显存占用1.9G)
2.然后使用Tensorrt运行推理，显存占用大约3.6G。

请问：为什么使用Tensorrt后，显存会占用这么高？      有什么方法能降低显存占用么？

**Comment by jingsongliujing** [comment]
建议进行模型剪枝，蒸馏，或者参考paddle的推理框架：https://github.com/PaddlePaddle/FastDeploy

**Comment by jingsongliujing** [comment]
量化加速参考：https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/quantize.md
