### ISSUE TITLE
ser c++ 推理时输入报错 Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got 116748592. Please check input value； Expected ids[i] < row_number, but received ids[i]

### ISSUE THREAD

**Issue by xianyu211** [PaddlePaddle/Paddle#48009]
### bug描述 Describe the Bug

在进行serc++推理时，五个输入都定义成了模型输入类型要求的int64，然后传入ser模型输入，在推理时报错
'''
InvalidArgumentError: Variable value (input) of OP(fluid.layers.embedding) expected >= 0 and < 1024, but got 116748592. Please check input value.
  [Hint: Expected ids[i] < row_number, but received ids[i]:116748592 >= row_number:1024.] (at /paddle/paddle/phi/kernels/cpu/embedding_kernel.cc:63)
  [operator < lookup_table_v2 > error]
'''

**Comment by tink2123** [comment]
input 的 id 必须满足 0 =< id < num_embeddings， 建议再检查一下输入。也可以提供一个可复现的代码单元，我们一起看看。

**Comment by kkiskkk** [comment]
> input 的 id 必须满足 0 =< id < num_embeddings，

请问这里的id是输入文本对应的那个id吗？
