### ISSUE TITLE
黑客松挑战性任务列表

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#48022]
| 序号 | 难度 | 任务 ISSUE                                                   | 设计文档                                                     | 完成队伍 |
| ---- | ---- | ------------------------------------------------------------ | ------------------------------------------------------------ | -------- |
| 1    | ⭐️    | [为 Paddle 新增 finfo API](https://github.com/PaddlePaddle/Paddle/issues/44073#task1) | [community#83](https://github.com/PaddlePaddle/community/pull/83) |          |
| 3    | ⭐️    | [为 Paddle 新增 cdist API](https://github.com/PaddlePaddle/Paddle/issues/44073#task3) | [community#37](https://github.com/PaddlePaddle/community/pull/37)  |         |
| 4    | ⭐️    | [为 Paddle 新增 cummax API](https://github.com/PaddlePaddle/Paddle/issues/44073#task4) | [community#39](https://github.com/PaddlePaddle/community/pull/39) |          |
| 6    | ⭐️    | [为 Paddle 新增 trapezoid API](https://github.com/PaddlePaddle/Paddle/issues/44073#task6) | [community#173](https://github.com/PaddlePaddle/community/pull/173) |          |
| 7    | ⭐️    | [为 Paddle 新增 MultivariateNormal API](https://github.com/PaddlePaddle/Paddle/issues/44073#task7) |                                                              |          |
| 19   | ⭐️    | [为 Paddle 新增 nexafter API](https://github.com/PaddlePaddle/Paddle/issues/44073#task19) | [community#243](https://github.com/PaddlePaddle/community/pull/243) |          |
| 24   | ⭐️⭐️   | [为 Paddle 新增 paddle.incubate.sparse.nn.Softmax 稀疏 API 的 coo 格式计算逻辑](https://github.com/PaddlePaddle/Paddle/issues/44073#task24) |                                                              |          |
| 25   | ⭐️⭐️   | [为 Paddle 新增 paddle.incubate.sparse.concat 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task25) |                                                              |          |
| 26   | ⭐️⭐️   | [为 Paddle 新增 paddle.incubate.sparse.index_select 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task26) |                                                              |          |
| 27   | ⭐️    | [为 Paddle 新增 paddle.incubate.sparse.any 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task27) |                                                              |          |
| 28   | ⭐️⭐️   | [为 Paddle 新增 paddle.incubate.sparse.slice 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task28) |                                                              |          |
| 29   | ⭐️⭐️   | [为 Paddle 新增 paddle.incubate.sparse.sum 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task29) |                                                              |          |
| 30   | ⭐️    | [为 Paddle 新增 paddle.incubate.sparse.is_nan 稀疏 API](https://github.com/PaddlePaddle/Paddle/issues/44073#task30) |                                                              |          |
| 32   | ⭐️    | [为 Paddle 优化 expand_as_grad op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task32) |                                                              |          |
| 35   | ⭐️    | [为 Paddle 优化 slice_grad op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task35) | [community#271](https://github.com/PaddlePaddle/community/pull/271) |          |
| 37   | ⭐️⭐️   | [为 Paddle 优化 argmax\argmin op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task37) | [community#256](https://github.com/PaddlePaddle/community/pull/256) |          |
| 39   | ⭐️⭐️   | [为 Paddle 优化 deformable_conv_grad op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task39) |                                                              |          |
| 40   | ⭐️⭐️   | [为 Paddle 优化 matrix_rank op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task40) |                                                              |          |
| 41   | ⭐️⭐️   | [为 Paddle 优化 p_norm op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task41) |                                                              |          |
| 42   | ⭐️⭐️   | [为 Paddle 优化 p_norm_grad op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task42) |                                                              |          |
| 43   | ⭐️⭐️   | [为 Paddle 优化 kthvalue op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task43) |                                                              |          |
| 44   | ⭐️⭐️   | [为 Paddle 优化 cumprod_grad op 在 GPU 上的计算性能](https://github.com/PaddlePaddle/Paddle/issues/44072#task44) |                                                              |          |
| 49   | ⭐️⭐️   | [为 Paddle group_norm 算子实现 float16 数据类型支持](https://github.com/PaddlePaddle/Paddle/issues/44071#task49) |                                                              |          |
| 56   | ⭐️⭐️   | [为 Paddle deformable_conv_v1 算子实现 float16 数据类型支持](https://github.com/PaddlePaddle/Paddle/issues/44071#task56) |                                                              |          |

**Comment by GreatV** [comment]
认领 [No.3：为 Paddle 新增 cdist API](https://github.com/PaddlePaddle/Paddle/issues/44073#task3)
上上次完成的 rfc [【Hackathon No.7】add rfc: api design for cdist](https://github.com/PaddlePaddle/community/pull/37)

**Comment by zrr1999** [comment]
认领 No.29: 为 Paddle 新增 paddle.incubate.sparse.sum 稀疏 API

**Comment by dasenCoding** [comment]
认领 No.7 https://github.com/PaddlePaddle/Paddle/issues/44073#task7
rfc: https://github.com/PaddlePaddle/community/pull/320
api PR: https://github.com/PaddlePaddle/Paddle/pull/47825
docs PR:https://github.com/PaddlePaddle/docs/pull/5551
