### ISSUE TITLE
为什么Linear(in_features=1, out_features=1, dtype=float32)默认的输入数据类型是float32？和numpy默认的float64不同？

### ISSUE THREAD

**Issue by smartleizi** [PaddlePaddle/Paddle#48024]
### 请提出你的问题 Please ask your question

为什么Linear(in_features=1, out_features=1, dtype=float32)默认的输入数据类型是float32？和numpy默认的float64不同？
1用numpy生成的数据x_data = np.arange(1,60,3.0).reshape(20,1)训练的时候报
ValueError: (InvalidArgument) The type of data we are trying to retrieve does not match the type of data currently contained in the container.
[Hint: Expected dtype() == paddle::experimental::CppTypeToDataType<T>::Type(), but received dtype():12 != paddle::experimental::CppTypeToDataType<T>::Type():13.] (at ..\paddle\phi\core\dense_tensor.cc:137)
  [operator < matmul_v2 > error]错误
2这很影响使用者的积极性，用TensorFlow和pytroch的时候都没有遇到这个问题

原来代码连接如下，我只修改了x_data
[hello paddle: 从普通程序走向机器学习程序](https://link.zhihu.com/?target=https%3A//www.paddlepaddle.org.cn/documentation/docs/zh/practices/quick_start/hello_paddle.html%23yiputongchengxugenjiqixuexichengxudeluojiqubie)

**Comment by smartleizi** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Linear_cn.html#linear
查看文档的时候根本没有数据类型的说明，
导入paddle，打印的时才能查看数据类型的要求
linear = paddle.nn.Linear(in_features=1, out_features=1)
print(linear)#Linear(in_features=1, out_features=1, dtype=float32)

**Comment by tink2123** [comment]
感谢反馈，会在文档中添加数据类型的说明。

**Comment by Aganlengzi** [comment]
@smartleizi 感谢反馈，develop PR 已经更改合入，官网的develop分支上明日可看到更新：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/Linear_cn.html

**Comment by smartleizi** [comment]
谢谢回复，文档修改已经看到了。
可是若代码没有修改，如果和numpy都无法兼容，那么怎么吸引更多的人来学这个框架呢？
上来修改一点代码都报错了，而且数据类型的错误。
