### ISSUE TITLE
[Docs]飞桨 API 文档体验提升计划

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#48047]
用于跟踪 [Call-for-Contributions: API文档体验优化](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/docs_optim_for_API.md) 各个任务的计划和进度

## 路线一：API文档问题修复

| 任务名称                                                     | 任务说明                                                     | 认领人      | PR情况                                                       |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ----------- | ------------------------------------------------------------ |
| 示例代码中移除第三方库numpy                                  | 由于历史原因，paddle1.x中的tensor生成与打印需要依赖第三方库numpy来实现，因此在API文档中大量引入了第三方库numpy。当前paddle已经可以很好的支持独立的生成与打印，易用性有了比较大的提升，这一点需要在示例代码中做体现，因此在非必要的情况下，示例代码中应该移除第三方库numpy | @kevinng77  | https://github.com/PaddlePaddle/Paddle/pull/46765, https://github.com/PaddlePaddle/Paddle/pull/47042 (merged) </br>https://github.com/PaddlePaddle/Paddle/pull/47483 (merged, 统一移除多余的 Numpy 依赖导入) </br>https://github.com/PaddlePaddle/Paddle/pull/47555 (merged, 统一移除 Numpy + paddle.to_tensor 构建的输入) </br>https://github.com/PaddlePaddle/Paddle/pull/47916 (merged, 补偿 #47555 中遗留问题)</br>https://github.com/PaddlePaddle/Paddle/pull/48678  |
| [DenseTensor 概念统一](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/tensor_concept_unification.md) | LoD 信息主要是为了处理的语言类模型而引入的机制设计，由于适配复杂，特殊情况多，相比传统的 Padding 机制维护成本高，Paddle 已经废弃了对该机制的维护。需要在文档中移除所有`LoDTensor` 概念的使用，统一飞桨基础框架的 DenseTensor 概念，使代码更容易理解与维护。 |   @Liyulingyue     @Lemon-er    | #48416 (merged)<br/> #48417 (merged)<br/> #48418 (merged)<br/> #48419 (merged)<br/> #48682 (merged) </br>https://github.com/PaddlePaddle/docs/pull/5486|
| 对inplace api增加介绍信息                                    | inplace（原位操作），具体可参考[tensor介绍](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/beginner/tensor_cn.html#tensor-shape)，目前的API文档中对这部分介绍比较少，对新手不够友好（如 [paddle.tanh_](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/tanh__cn.html#tanh)），需要在文档中增加说明或超链接，另外修复部分超链接失效的问题。详见issue：https://github.com/PaddlePaddle/docs/issues/4766 |    @ZhangYuef         |    https://github.com/PaddlePaddle/docs/pull/5469                                                          | 
| 修复broadcasting说明的超链接失效问题                         | 例如 [paddle.add](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/add_cn.html#add)，修复方法可参考 [paddle.broadcast_tensors](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/broadcast_tensors_en.html)，对提到支持broadcast的api，全量查找并统一替换为标准格式。可参考：https://github.com/PaddlePaddle/Paddle/pull/46347 |   @enkilee           |      https://github.com/PaddlePaddle/docs/pull/5441 </br> https://github.com/PaddlePaddle/paddle/pull/48434                                                      |
| 对超链接没有生成的情况，进行全量检索与修复                 | 参考[飞桨文档相互引用](https://github.com/PaddlePaddle/docs/wiki/飞桨文档相互引用)，可以发现由于rst的特殊引用格式，导致很多习惯书写md文档的同学会使用错误的引用方式，导致超链接没有生成的情况，需要在html中全量查找并修复 |   @whisky-12    @tianxingxia-cn      |                                                              https://github.com/PaddlePaddle/docs/pull/5521  |
| 处理API文档中的死链问题                                      | [API文档死链扫描](https://shimo.im/sheets/913JVrN0MOHwPM3E/MODOC/) ，由于文档中英文一致，需要确认一下中英文文档的超链接是否一致，如果遗漏，需要增加   | @jjyaoao            |    https://github.com/PaddlePaddle/Paddle/pull/48969 </br> https://github.com/PaddlePaddle/docs/pull/5500                                                          |
| 英文API文档中的异常报错                                      | 飞桨的英文API文档是通过docstring编译生成的html页面，由于sphinx编译导致的报错有一部分会直接显示在文档中，严重影响用户体验，详见issue：https://github.com/PaddlePaddle/docs/issues/5177 | @ustiniankw | https://github.com/PaddlePaddle/Paddle/pull/47448 （merged）</br> https://github.com/PaddlePaddle/Paddle/pull/47986 （merged）</br> 除fluid api外其他部分已完成全部修复，通过QA验收 |
| 在中文API文档中统一 Tensor 的描述 | 中文文档中存在少量将 Tensor 翻译为张量的情况，虽然没有什么问题，但是会造成理解上的困难，建议统一为 Tensor | @Liyulingyue  @Atlantisming @sanbuphy |  https://github.com/PaddlePaddle/docs/pull/5477 </br> https://github.com/PaddlePaddle/docs/pull/5480 </br> https://github.com/PaddlePaddle/docs/pull/5523 |
| 在英文API文档中统一静态图模式与动态图模式的英文翻译 | dynamic graph mode 和 static graph mode，英文文档中出现了诸如 static mode、imperative mode、dygraph mode 等不规范的翻译，建议统一 | @lizechng  @sanbuphy @Atlantisming | https://github.com/PaddlePaddle/docs/pull/5467 </br> https://github.com/PaddlePaddle/docs/pull/5525 </br> https://github.com/PaddlePaddle/Paddle/pull/49170 </br> https://github.com/PaddlePaddle/Paddle/pull/49243 </br> https://github.com/PaddlePaddle/docs/pull/5535 |

## 路线二：**飞桨API文档写作规范手册制定**

可以参考 [飞桨 API 文档的不规范之处及其规范化方案汇总](https://github.com/PaddlePaddle/docs/discussions/5243)、[【当前版本】官网-API 文档书写规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_docs_guidelines_cn.html)

| 章节名称               | 内容规划（可调整）                                                    | 撰写认领人 | PR情况 |
| ---------------------- | ------------------------------------------------------------ | ---------- | ------ |
| API命名方法与API介绍   | 飞桨API目录结构介绍，可直接参考 [官网文档-API 设计和命名规范](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_design_guidelines_standard_cn.html)</br>API命名方法，含参数，区分class与function </br> API介绍方法，如何用最简短的话讲清一个API是什么，怎么用 |            |        |
| 数字及数学公式的写法   | 数字、数值的写法</br> 数学公式的写法                               |  @DrRyanHuang          |        |
| 字母及标点符号的写法   | 中文标点</br> 英文字母及标点                                       |            |        |
| 外部链接和超链接的写法 | 引用规范：包含引用API、站内文献、站外文献、论文等</br> 超链接的使用，可以参考：[飞桨文档相互引用](https://github.com/PaddlePaddle/docs/wiki/飞桨文档相互引用) |            |        |
| 其他规范               | 空格、段落的规范使用</br> 字体、色块的写法（加粗、斜体、灰色底块等）</br>图、表的使用（图题、图标、居中？）</br>其他补充 |   @isLinXu         |        |
| 参数与返回值的写法     | 参数格式、内容规范</br>返回值格式、内容规范</br>其他补充：如形状(shape) |            |        |
| 代码示例的写法         | 制定代码示例写作规范优秀示例解析                             |            |        |
| API文档-提前预览       | 预览的价值，文档去哪里预览，怎么预览</br>可参考：[[Beta\]飞桨文档预览工具](https://github.com/PaddlePaddle/docs/wiki/[Beta]飞桨文档预览工具) |            |        |
| 常见异常情况           | 1. 源代码丢失</br>2. 示例代码：copy-from未成功</br>3. 出现warning & error</br>4. ... |            |        |
| 完整示例               | 中文API文档示例（常规，即function）</br>中文API文档示例（class）</br>英文API文档示例（常规，即function）</br>英文API文档示例（class）</br> 可参考：https://github.com/PaddlePaddle/docs/pull/5112  |   @Liyulingyue         |        |

**Comment by Liyulingyue** [comment]
认领task
完整示例

**Comment by whisky-12** [comment]
路线一：API文档问题修复 怎么填写认领信息？

**Comment by Ligoml** [comment]
> 路线一：API文档问题修复 怎么填写认领信息？

回复issue就可以啦

**Comment by enkilee** [comment]
修复broadcasting说明的超链接失效问题：
https://github.com/PaddlePaddle/docs/pull/5441

**Comment by enkilee** [comment]
修复broadcasting说明的超链接失效问题（英文文档）：
https://github.com/PaddlePaddle/Paddle/pull/48283

**Comment by Lemon-er** [comment]
路线一：API文档问题修复
题目：使用Grad-CAM 类激活可视化深度学习网络性能的可解释性
认领人：Lemon-er

**Comment by Lemon-er** [comment]
路线一：API文档问题修复
题目：[DenseTensor 概念统一]
认领人：Lemon-er

**Comment by ZhangYuef** [comment]
- 路线一：API文档问题修复
- 题目：对inplace api增加介绍信息
- 认领人：ZhangYuef
----
PR: https://github.com/PaddlePaddle/docs/pull/5469

**Comment by enkilee** [comment]
#48283 关了无法打开了。重修了英文的boardcasting：https://github.com/PaddlePaddle/Paddle/pull/48434

**Comment by lizechng** [comment]
路线一：API文档问题修复
题目：在英文API文档中统一静态图模式与动态图模式的英文翻译
认领人：lizechng

**Comment by Atlantisming** [comment]
路线一：API文档问题修复
题目：在中文API文档中统一 Tensor 的描述
认领人：Atlantisming

**Comment by whisky-12** [comment]
路线一：API文档修复
题目：对与超链接没有生成的情况，进行全量检索与修复
认领人：魔术师

**Comment by isLinXu** [comment]
路线二：飞桨API文档写作规范手册制定
题目：其他规范(作图规范)
认领人：isLinXu
提交：https://github.com/PaddlePaddle/docs/pull/5497

**Comment by jjyaoao** [comment]
路线一：API文档问题修复
题目：处理API文档中的死链问题
认领人：jjyaoao

**Comment by tianxingxia-cn** [comment]
路线一：API文档问题修复
题目：对与超链接没有生成的情况，进行全量检索与修复
认领人：[tianxingxia-cn](https://github.com/tianxingxia-cn)
提交：https://github.com/PaddlePaddle/docs/pull/5521

**Comment by sanbuphy** [comment]
路线一：API文档问题修复
题目：1 在中文API文档中统一 Tensor 的描述 2 在英文API文档中统一静态图模式与动态图模式的英文翻译 3 示例代码中移除第三方库numpy
认领人：sanbuphy

**Comment by DrRyanHuang** [comment]
路线二：飞桨API文档写作规范手册制定
题目：数字及数学公式的写法
认领人：Ryan

**Comment by Atlantisming** [comment]
路线一：API文档问题修复
题目：在英文API文档中统一静态图模式与动态图模式的英文翻译
认领人：Atlantisming

**Comment by luotao1** [comment]
小结：基于docs-sig的全量API文档（1005组）评估结论，对需要优化的594组文档进行重点修正，完成336组API中英文文档优化，本年度共计完成74.3%的API文档优化工作，并完成了示例代码中移除第三方库numpy、DenseTensor概念统一、修复API文档中的死链问题与编译报错、Tensor与动静态图描述统一等9项重点任务。
