### ISSUE TITLE
【开放任务讨论】PyTorch 与 Paddle 2.0 API 映射表文档补全

### ISSUE THREAD

**Issue by PommesPeter** [PaddlePaddle/Paddle#48054]
### 需求描述 Feature Description

任务目标：
完善 PyTorch 1.8 与 Paddle 2.0 API 映射表，补全新增 API

需求场景：
- 论文复现营
- paddle 框架使用
- 代码迁移
- ....

功能描述：
- 补全 paddle 新增的 API 对应 PyTorch 的映射
- 检查之前的文档是否有误

**Comment by zhwesky2010** [comment]
@PommesPeter 你好，非常欢迎参与这项工作。我们近期也正在梳理这项工作所涉及的全量表，目标是产生Pytorch与Paddle的全量API映射关系数据，预计下一两周会和你讨论你这边需要负责的数据补齐，期待后续合作愉快。

**Comment by Ligoml** [comment]
很好的提议！事实上我们最近也在讨论API转换的事情，前置条件就是要梳理清楚当前的API映射情况，并进行查漏补缺。官网上之前发布过一版 [映射表](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api)，正如你所说，我们需要：
- 补全 paddle 新增的 API 对应 PyTorch 的映射
- 检查之前的文档是否有误

后面会考虑开发一些自动转换工具，也很欢迎你和我们一起做这件事~

其他社区开发者的工作参考：https://github.com/zzz2010/paddorch

**Comment by PommesPeter** [comment]
> 

好的

**Comment by PommesPeter** [comment]
> 很好的提议！事实上我们最近也在讨论API转换的事情，前置条件就是要梳理清楚当前的API映射情况，并进行查漏补缺。官网上之前发布过一版 [映射表](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api)，正如你所说，我们需要：
> 
> * 补全 paddle 新增的 API 对应 PyTorch 的映射
> * 检查之前的文档是否有误
> 
> 后面会考虑开发一些自动转换工具，也很欢迎你和我们一起做这件事~
> 
> 其他社区开发者的工作参考：https://github.com/zzz2010/paddorch

那我现在可以针对目前有的一些问题进行补充吗

**Comment by zhwesky2010** [comment]
@PommesPeter https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api 你好，现在可以先把这168个映射关系检查一遍，然后按这个方式重新标注下：
- 功能一致，参数一致（包含默认参数），也就是torch参数是paddle的相等或子集，可被paddle完全覆盖
- 功能一致，torch参数更多（torch多出来的参数，默认下是否一致）
- 功能一致，但两者参数不一致（不一致的参数及转换关系，默认下是否一致）
- 功能不一致，写不一致的用法
- torch独有的API，填paddle无

内容可以提PR到https://github.com/PaddlePaddle/docs里面去

而且我们目前正在梳理其余900+个API，到下周将会有更多API交给你来分析差异，非常感谢来参与这项有价值的工作~

**Comment by PommesPeter** [comment]
> @PommesPeter https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api 你好，现在可以先把这168个映射关系检查一遍，然后按这个方式重新标注下：
> 
> * 功能一致，参数一致（包含默认参数），也就是torch参数是paddle的相等或子集，可被paddle完全覆盖
> * 功能一致，torch参数更多（torch多出来的参数，默认下是否一致）
> * 功能一致，但两者参数不一致（不一致的参数及转换关系，默认下是否一致）
> * 功能不一致，写不一致的用法
> * torch独有的API，填paddle无
> 
> 内容可以提PR到[https://github.com/PaddlePaddle/docs里面去](https://github.com/PaddlePaddle/docs%E9%87%8C%E9%9D%A2%E5%8E%BB)
> 
> 而且我们目前正在梳理其余900+个API，到下周将会有更多API交给你来分析差异，非常感谢来参与这项有价值的工作~

好滴没问题

**Comment by PommesPeter** [comment]
~文档修改已提 pr，https://github.com/PaddlePaddle/docs/pull/5484 （已合入）~

**Comment by PommesPeter** [comment]
> 文档修改已提 pr，[PaddlePaddle/docs#5484](https://github.com/PaddlePaddle/docs/pull/5484)

该 pr 已合入

**Comment by PommesPeter** [comment]
目前还有其他的 API 需要修改吗
