### ISSUE TITLE
源码编译paddle_inference库错误

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#48089]
### 请提出你的问题 Please ask your question

源码编译paddle_inference库的时候，执行命令
cmake  .. \
    -DWITH_CONTRIB=OFF \
    -DWITH_MKL=OFF \
    -DWITH_MKLDNN=OFF  \
    -DWITH_TESTING=OFF \
    -DCMAKE_BUILD_TYPE=Release \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DON_INFER=ON \
    -DWITH_PYTHON=OFF \
    -DWITH_TENSORRT=ON \

编译过程结束后，没有CmakeFile文件，无法 make   .请问是什么原因

错误信息：
generate /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/自己编译paddle库/Paddle-2.4.0/paddle/fluid/operators/ops_extra_info.cc
Merge and generate static library: phi_static_1
fatal: Not a git repository (or any parent up to mount point /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: Not a git repository (or any parent up to mount point /media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
-- commit: 
-- branch: 
-- Download inference test stuff from http://paddle-inference-dist.bj.bcebos.com/word2vec.inference.model.tar.gz
-- Download inference test stuff from http://paddle-inference-dist.bj.bcebos.com/image_classification_resnet.inference.model.tgz
WITH_DLNNE:
-- Configuring incomplete, errors occurred!
See also "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/自己编译paddle库/Paddle-2.4.0/build/CMakeFiles/CMakeOutput.log".
See also "/media/alex/e815e6bf-29c6-44df-a535-184ead5b3f96/自己编译paddle库/Paddle-2.4.0/build/CMakeFiles/CMakeError.log".

(base) alex@alex-System-Product-Name:/media/alex/e815e6bf-29c6-44df-a535-184ead5
b3f96/自己编译paddle库/Paddle-2.4.0$ make -j
make: *** 没有指明目标并且找不到 makefile。 停止。

**Comment by joey12300** [comment]
您好，看起来是执行git出错，试试 `export GIT_DISCOVERY_ACROSS_FILESYSTEM=1`。

参考：[git-discovery-across-filesystem-not-set](https://stackoverflow.com/questions/16853624/git-discovery-across-filesystem-not-set)
