### ISSUE TITLE
paddle.max()

### ISSUE THREAD

**Issue by Farewell-CK** [PaddlePaddle/Paddle#48098]
### bug描述 Describe the Bug

import paddle # paddlepaddle = 2.3.2
执行：
      paddle.max((paddle.to_tensor(1), paddle.to_tensor(6)))
结果：Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [1])
执行：
    b = paddle.to_tensor(1)
    a = paddle.to_tensor(6)
    paddle.max((a,b))
结果：
    Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [6])

### 其他补充信息 Additional Supplementary Information

代码没有区别，但是结果却不同

**Comment by Farewell-CK** [comment]
python版本3.7.13

**Comment by joey12300** [comment]
你好，paddle.max接受的输入是一个tensor，而你传入一个tuple后，会取tuple第一个tensor作为输入。如果想比较两个tensor，可以这么做：

```
b = paddle.to_tensor(1)
a = paddle.to_tensor(6)
paddle.max(paddle.concat(a,b))
```

paddle.max使用：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/max_cn.html#max

**Comment by Farewell-CK** [comment]
好的，感谢
