### ISSUE TITLE
请问飞桨支持arm吗？

### ISSUE THREAD

**Issue by amocken** [PaddlePaddle/Paddle#48091]
我想在倚天710服务器上运行飞桨

**Comment by joey12300** [comment]
您好，请问你是要部署模型吗？PaddleInference是支持ARM架构的芯片的，详情可见以下的链接https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/hardware_info_cn.html

**Comment by nizhaoqiao** [comment]
> 我想在倚天710服务器上运行飞桨

是单独在710上跑训练or推理？还是会加上GPU或者其他AI加速卡？

**Comment by amocken** [comment]
> 

单独跑

**Comment by amocken** [comment]
> > 我想在倚天710服务器上运行飞桨
> 
> 是单独在710上跑训练or推理？还是会加上GPU或者其他AI加速卡？

单独在710上跑

**Comment by amocken** [comment]
> 您好，请问你是要部署模型吗？PaddleInference是支持ARM架构的芯片的，详情可见以下的链接https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/hardware_info_cn.html

希望PaddlePaddle也能在Linux甚至Windows平台上原生支持ARM芯片

**Comment by engineer1109** [comment]
Linux arm CPU是一直支持的
