### ISSUE TITLE
paddle.full()算子动静态图行为不一致

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#48101]
### 请提出你的问题 Please ask your question

在静态图中，当shape参数不为Varible时，会检查shape中的元素个数：
![image](https://user-images.githubusercontent.com/37332773/202409834-b49b3f4e-a56c-4659-9895-648ee5309cf9.png)
因此静态图中，shape不为Variable时，shape=[]会报错。
动态图中没有这样的检查
![image](https://user-images.githubusercontent.com/37332773/202410419-2e5937b3-35f9-4731-8f12-22d75097f8da.png)
导致动静态图对shape不为Variable的情况行为不一致。
静态图中只有在shape参数为Variable类型时才能生成0维向量，动态图shape不管是否为Tensor都能生成0维向量。

**Comment by joey12300** [comment]
你好，请问你这个代码具体是在那个api里呢？我在full api里没看到这段代码哈？是哪一个版本的paddle

**Comment by ZzSean** [comment]
develop中这里并没有描述中的那段代码，https://github.com/PaddlePaddle/Paddle/blob/7f92e27efd72998102cff1ef524dc24ec7288ed2/python/paddle/fluid/layers/utils.py#L413
![image](https://user-images.githubusercontent.com/32410583/202663581-b9b9a123-fab7-4352-b092-c0afcfde68de.png)
