### ISSUE TITLE
在VS2019新建工程测试peddleseg的demo  testseg.cc出现程序无法启动的情况

### ISSUE THREAD

**Issue by aiwenzhu** [PaddlePaddle/Paddle#48120]
### 请提出你的问题 Please ask your question

在VS2019新建工程测试peddleseg的demo  testseg.cc出现程序无法启动的情况:
配置了paddleinference的lib，opencv，yaml并将所有相关dll放下了工程目录下，项目生成没问题；
 auto predictor = create_predictor(yaml_config)但是加上这句代码，程序就无法调试和运行，会报
程序无法正常启动0xc000007b的错误

**Comment by ghostxsl** [comment]
你好，请去PaddleSeg下进行issue的提问：https://github.com/PaddlePaddle/PaddleSeg/issues
