### ISSUE TITLE
Sometimes `mklml` is much slower than `mkl`.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#4813]
If we use `mkl`, the model's forward time is 0.03ms in contrast to 2ms when we use `mklml` library.
Env is put [here](https://github.com/gongweibao/testcapi) and you can use this environment to reproduce the problem.

**Comment by luotao1** [comment]
有几个问题想确认下：
1. 请问复现的步骤是什么？分别编译出使用mklml和使用mkl的两个paddle版本，然后直接跑测试环境中的run.sh脚本？这个测试环境是一个独立于paddle repo的文件夹？
2. 测试环境中的[CMakeLists](https://github.com/gongweibao/tests/blob/develop/zhangtai/CMakeLists.txt)文件中，有很多写死的路径。这些路径应该是什么？
3. 是在独占节点上测试得到的结果么？trainer_count是几？

**Comment by tensor-tang** [comment]
补充一个问题，请问所用的`mkl`版本是什么？相比于`mklml`的时候，单节点时的cpu利用率分别是多少？

**Comment by gongweibao** [comment]
`mkl`库已经不可查，公司内部以前大家用的。可以在`https://hub.docker.com/r/paddlepaddle/centos6u3-capi/`里边的`/opt/intel/mkl`目录下找到

**Comment by gongweibao** [comment]
1.请问复现的步骤是什么？
分别使用`mklml`编译出.so和公司内部`mkl`编译出来的.so，测试其时间
2.测试环境中的CMakeLists文件中，有很多写死的路径。这些路径应该是什么？
那些是使用的第三方.a文件。我把它们打包发上去。
3. 是在独占节点上测试得到的结果么？
独占节点的结果。

**Comment by luotao1** [comment]
1. 公司内部mkl编译出来的.so也放上去吧。
2. https://github.com/gongweibao/tests/tree/develop/zhangtai 这个拉下来就行跑，直接运行run.sh?能把里面写死的路径都改一下么？

**Comment by gongweibao** [comment]
不好意思各位，回复的完了。已经把环境整理的比较整洁了。看大家还有啥问题没有？

**Comment by luotao1** [comment]
从 https://github.com/gongweibao/tests/blob/develop/build_capi/build_capi.sh#L22 这里看`WITH_MKLML=ON`，但从https://github.com/gongweibao/tests/tree/develop/zhangtai/mkl/lib 看缺少`libiomp5.so`和`libmklml_intel.so`这两个库。

**Comment by gongweibao** [comment]
给出的是链接`mkl`库的版本，链接他的时候不需要你说的这两个库。
```
find ./third_party/install -name 'libiomp5.so' -exec cp {} output/usr/local/lib \;
```
找不到不会拷贝过去的。

**Comment by luotao1** [comment]
libiomp5.so是使用mklml库的时候，才有的。那使用mklml编译出.so的时候，有用到这两个库么？

**Comment by gongweibao** [comment]
这个我以为你要自己编，出现diff的时候可以加参数来调整。
我可以加一个上去。

**Comment by luotao1** [comment]
https://github.com/gongweibao/tests/tree/develop/zhangtai/mkl/lib 这个是链接公司内部mkl库的版本？从lib中看不到公司内部mkl的so文件。

> 这个我以为你要自己编?

我可以自己编，但我要怎么编译呢？因为对这个project不熟悉，而README中只给出了编译环境，没给出编译命令。所以请问能不能把两个版本的所有环境都放上去，然后写一下分别是怎么编译得到的？

另外，README写了“然后看其打印的时间作对比”。请问要运行哪个文件？

> 单节点时的cpu利用率分别是多少

也麻烦回答一下这个问题。

初步怀疑，下降10倍，是因为编译的时候没有开启`WITH_MKLML=ON`的选项，只开启了`WITH_MKLDNN=ON`。

**Comment by gongweibao** [comment]
Done。

**Comment by gongweibao** [comment]
![image](https://user-images.githubusercontent.com/10721757/32893446-1d8783a2-ca9f-11e7-8987-032eaa852786.png)

**Comment by gongweibao** [comment]
> 这个是链接公司内部mkl库的版本？从lib中看不到公司内部mkl的so文件。
公司内部 `mkl`库是一个.a，不是.so，link的时候被包含在了`libpaddle_capi_shared.so` 中

**Comment by gongweibao** [comment]
由于`mklml`的.so超过了50M，不能传到github上。
需要的话我可以单独发，或者可以自己编译一下。编译版本和命令都已经写到README当中。

**Comment by gongweibao** [comment]
呃，打开的最佳姿势应该用docker
明天早晨我打一个image给你😄

**Comment by gongweibao** [comment]
运行时间对比：
![image](https://user-images.githubusercontent.com/10721757/32929400-b8c1ab7e-cb92-11e7-9815-0ae6e278b15c.png)

**Comment by luotao1** [comment]
问题已复现。
进入docker环境后，由于MKLML是动态库，所以需要设置了如下变量：
```
export KMP_AFFINITY="granularity=fine,compact,0,0"
export OMP_DYNAMIC="FALSE"
export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
```
![image](https://user-images.githubusercontent.com/6836917/33871502-bc151cb0-df4d-11e7-9fc7-1fa5d514c4d9.png)
从图中看两者差距在1.3倍。

**Comment by luotao1** [comment]
将 https://github.com/gongweibao/testcapi/blob/master/main.cpp#L124 一次循环时间改成十次，两者时间是一样了
![image](https://user-images.githubusercontent.com/6836917/33873156-e549d844-df54-11e7-8b30-355e677df96e.png)
