### ISSUE TITLE
Tensor.any()  [operator < reduce_any > error]

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#48159]
### bug描述 Describe the Bug

请问，是reduce_any算子里的kernel还没实现吗？有什么替代方案吗？
```python
import paddle
a = paddle.rand([4,4,4,4])
a.any()
```
报错信息：
W1118 20:43:02.138398   399 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W1118 20:43:02.143416   399 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_399/3841100286.py in <module>
      1 import paddle
      2 a = paddle.rand([4,4,4,4])
----> 3 a.any()

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py in any(x, axis, keepdim, name)
   3264         axis = axis if axis != None and axis != [] else [0]
   3265         return _C_ops.reduce_any(x, 'dim', axis, 'keep_dim', keepdim,
-> 3266                                        'reduce_all', reduce_all_flag)
   3267 
   3268     attrs = {

RuntimeError: (NotFound) There are no kernels which are registered in the reduce_any operator.
  [Hint: Expected kernels_iter != all_op_kernels.end(), but received kernels_iter == all_op_kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:341)
  [operator < reduce_any > error]

**Comment by ghostxsl** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/any_cn.html#any
参考官方文档，输入的tensor必须得是bool类型
