### ISSUE TITLE
[Targeting on 2024 Q1] Inappropriate cuda arch flags for the third-party libraries 

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#48166]
### 问题描述 Issue Description

I see there are many nvcc warnings reporting `The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated` even when I explict configure the `SM_80` flag (`-DCUDA_ARCH_NAME=Manual  -DCUDA_ARCH_BIN="80"`). 

Paddle should pass the configured `NVCC_FLAGS_EXTRA` or `CMAKE_CUDA_FLAGS` to those third-party libraries to avoid redundant arch compilation.

The following are part of the building log:
```
debug: /workspace/paddle/latest/build/third_party/dgc/src/extern_dgc/build/obj/./csc.cu.o <-- csc.cu
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).

-- Installing: /workspace/paddle/latest/build/third_party/install/libmct/include/mct/impl/serialization.hpp
nvcc warning : The 'compute_35', 'compute_37', 'sm_35', and 'sm_37' architectures are deprecated, and may be removed in a future release (Use -Wno-deprecated-gpu-targets to suppress warning).
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: None
Paddle With CUDA: None

OS: Ubuntu 20.04
Python version: 3.8.10

CUDA version: 11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: None.None.None
Nvidia driver version: 525.33
****************************************

**Comment by nemonameless** [comment]
Thanks for your suggestions. We will seriously consider them.

**Comment by zlsh80826** [comment]
Hi @nemonameless,
There are two third-party libs are critial to the cuda 12.0 build, dgc and warp-ctc. Both of them always apply arch35 in the build flag currently, but cuda 12.0 (not-released, but we are on the internal test) doesn't support arch35.

**Comment by wuhuachaocoding** [comment]
hello, please submit a PR to help us modify the third party about the dgc.
https://github.com/PaddlePaddle/PaddleFleetX/blob/old_develop/deprecated/src/collective/src/Makefile

**Comment by zlsh80826** [comment]
@wuhuachaocoding,
Please help revise the makefile as the following logic:

CUDA >= 11.8: add sm_90
CUDA >= 12.0: deprecate sm_35

Besides, I am wondering why dgc is shipped by [tgz](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/dgc.cmake#L26) but other third-party is shipped by GitHub repo, e.g. [warp-ctc](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/warpctc.cmake#L25)?

**Comment by wuhuachaocoding** [comment]
@zlsh80826 
the dgc tgz has been modified according to your needs, like this: https://github.com/PaddlePaddle/PaddleFleetX/pull/983/files
(this pr just show some content modified for you)
we will move dgc package  into PaddlePaddle framewark, the GitHub repo branch will be deprecated.
the dgc tgz has been modified according to your needs, you can use it directly. https://github.com/PaddlePaddle/Paddle/pull/48700/files

**Comment by zlsh80826** [comment]
Thank you @wuhuachaocoding,
I will try it later! However, I have some advice for dgc `CUDA_ARCH`. The [dgc/collective.tgz](https://fleet.bj.bcebos.com/dgc/collective_f66ef73.tgz) is only for PaddlePaddle, and Paddle already has the [corresponding logic](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cuda.cmake#L264) to handle this stuff. It would be better if we pass the processed `NVCC_FLAGS_EXTRA` to `dgc` so that the dgc arch can match Paddle's configuration, instead of compiling all available architectures. Besides, we don't need to handle such complicated logic on each dependency.

**Comment by wuhuachaocoding** [comment]
OK, thank you for your suggestion @zlsh80826 
we will make the dgc upgraded, and move it into paddle framework. thank you again.

**Comment by GhostScreaming** [comment]
Thank you for your suggestion @zlsh80826. We will upgrade the `dgc` libraries with processed `NVCC_FLAGS_EXTRA` in autumn quarter.

**Comment by tianshuo78520a** [comment]
Resolve [PR61183](https://github.com/PaddlePaddle/Paddle/pull/61183), could you please review if this issue can be resolved

**Comment by tianshuo78520a** [comment]
@zlsh80826 Can we close the issue?

**Comment by zlsh80826** [comment]
@tianshuo78520a I recently encountered an issue when rebuilding the paddle with your new changes (#61183). The `patch` command return error if the warpctc/warprnn are already patched. I will post the error here.

**Comment by tianshuo78520a** [comment]
The latest development has fixed some issues because the files in the previous build/hird_party/directory were not cleaned. You can try pull https://github.com/PaddlePaddle/Paddle/pull/61870 fix build bug

**Comment by zlsh80826** [comment]
Thanks @tianshuo78520a, I already verified that the #61870 fixes the issues.
