### ISSUE TITLE
ERNIE 3.0 int8 performance drop

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#48201]
### 问题描述 Please describe your issue

Commit: https://github.com/PaddlePaddle/Paddle/commit/c3a69111c571edbca0dad313d58a31baf2eb5d69
causes performance drop in ERNIE 3.0 int8 model.
It is connected with memory consumption increasing
![image](https://user-images.githubusercontent.com/10847947/203008662-2da39942-b083-4a6a-9113-5d65d529cfaa.png)

---
### CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```
### Test run command:
```
FLAGS_use_mkldnn=true   /usr/bin/time -v  python /root/models/PaddleNLP/model_zoo/ernie-3.0/infer.py --task_name tnews --model_path /data/PaddlePaddle/pp_models/ernie3.0/int8 --perf --device cpu --num_threads 1 --enable_quantize
```

**Comment by gongel** [comment]
Thank you for your feedback, we have received your question. @zhoutianzi666 Please pay attention to this issue. Thx.
