### ISSUE TITLE
Passes can only be applied to block 0. Please make it applied to inner blocks as well

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#48204]
### 需求描述 Feature Description

We noticed that IR passes are only applied to block 0 e.g. conditional_block_infer inner operators are not a subject to IR passes.
[More](https://github.com/zh794390558/paddle_build/issues/5#issuecomment-1314197418) and [more](https://github.com/PaddlePaddle/Paddle/issues/48109) transformer based models  are using conditional_block_infer so It would be good to have IR passes there to take advantage of fuses and oneDNN kernels.  Some work was done [here](https://github.com/PaddlePaddle/Paddle/pull/47009/files)
but it was to make enabled oneDNN for conditional_infer_block when ENV VAR is set , which is not how we work with PaddlePaddle and oneDNN for inference as we use AnalysisConfig to pass info on using oneDNN.

 Please make IR passes working for inner ops of conditional_infer_block.

This is duplicate of this https://github.com/PaddlePaddle/Paddle/issues/17003.

**Comment by yaomichael** [comment]
this is related to https://github.com/zh794390558/paddle_build/issues/5#issuecomment-1314197418

**Comment by yaomichael** [comment]
this conditional_block_infer issue should have been resolved by @weishengying already. 
@onecatcn can you confirm and close it?
