### ISSUE TITLE
paddle tensor 索引为负数情况下输出nan

### ISSUE THREAD

**Issue by dowdyboy** [PaddlePaddle/Paddle#48231]
### bug描述 Describe the Bug

# paddlepaddle-gpu   2.3.0.post112    Windows11

# paddle 负索引nan bug
    tb = paddle.rand((361, 6))
    i = paddle.to_tensor(np.array([-1+361, 160]))
    ii = paddle.to_tensor(np.array([-1, 160]))
    print(tb[ii])
    print(tb[i])

**Comment by minghaoBD** [comment]
经验证，tb[-1] == tb[360] != tb[-1, 160][0]

感谢您的问题。可以暂时通过tb[-1]取值，再做concate处理。tb[-1, 160]的问题我们定位修复下。
