### ISSUE TITLE
请问现在还是不支持cummax吗

### ISSUE THREAD

**Issue by evi-Genius** [PaddlePaddle/Paddle#48239]
### 请提出你的问题 Please ask your question

找了一圈issures，似乎现在还是不支持cummax

**Comment by minghaoBD** [comment]
对的，现在还不支持。

**Comment by luotao1** [comment]
@evi-Genius 如果有兴趣，可以帮忙添加下 cummax，目前已经有RFC文档了，但代码还没实现
- https://github.com/PaddlePaddle/Paddle/issues/40313
- draft:
  - https://github.com/PaddlePaddle/Paddle/pull/42480
  - https://github.com/PaddlePaddle/Paddle/pull/45073
  - RFC：https://github.com/PaddlePaddle/community/blob/master/rfcs/APIs/20220316_api_design_for_cummax.md

**Comment by enkilee** [comment]
mark, ready to done

**Comment by luotao1** [comment]
close due to the following PR is merged:
- https://github.com/PaddlePaddle/Paddle/pull/45073
