### ISSUE TITLE
paddle可以与pybind配合生成自定义算子吗

### ISSUE THREAD

**Issue by zhao-sy** [PaddlePaddle/Paddle#48237]
### 请提出你的问题 Please ask your question

看到官网写的自定义算子生成方式是使用PD_BUILD_OP和PD_BUILD_GRAD_OP接口进行，我试了发现无法导出带函数的类，像采用pybind11方法，想请问一下飞桨框架可以与pybind11配合使用吗？

**Comment by minghaoBD** [comment]
https://github.com/PaddlePaddle/Paddle/blob/940d8f253239a74e0812faf9a80f60d5c39ebedd/paddle/fluid/pybind/io.cc 可以参照这里的例子，还有一些。可以在paddle框架搜索 pybind11 关键字

**Comment by zhao-sy** [comment]
> 

那么paddle框架在使用pybind的时候，和普通框架一样通过.so编译调用就可以吗？我用gcc对pybind11进行.so编译一直不通过

**Comment by minghaoBD** [comment]
报错是什么呢？编译指令也方便提供下吗？

**Comment by zhao-sy** [comment]
> 报错是什么呢？编译指令也方便提供下吗？

本项目是将基于pytorch的神经网络进行框架迁移，尝试采用原框架的bash run.sh方法编译，其中pybind模块写法如图（文件shift_cuda.cpp）：
PYBIND11_MODULE(shift_cuda, m) {
  m.def("forward", &shift_forward, "shift forward (CUDA)");
  m.def("backward", &shift_backward, "shift backward (CUDA)");
}
setup.py内容如下
from paddle.utils.cpp_extension import CppExtension, CUDAExtension, setup

setup(
    name='shift_cuda_linear_cpp',
    ext_modules=[
        CUDAExtension(sources = [
            'shift_cuda.cpp',
            'shift_cuda_kernel.cu'
        ]),
    ])
使用run.bash进行编译
cd cuda

rm -rf ./__pycache__
rm -rf ./dist
rm -rf ./build
rm -rf ./shift_cuda_linear_cpp.egg-info

python setup.py install

cd ..

CUDA_VISIBLE_DEVICES="0" python demo.py
在bash之后仍然显示AttributeError: module 'shift_cuda' has no attribute 'forward'

gcc编译.so方法也尝试过，会报错#include<paddle/extension.h>文件不存在

**Comment by zyfncg** [comment]
> gcc编译.so方法也尝试过，会报错#include<paddle/extension.h>文件不存在

这个错误看上去是编译时没有将相应的头文件链接进来，可以再编译配置里加上试试

**Comment by zyfncg** [comment]
请问下这里为什么需要写pybind接自定义算子？Paddle提供的自定义算子功能是不能满足什么需求吗？

**Comment by zhao-sy** [comment]
> 请问下这里为什么需要写pybind接自定义算子？Paddle提供的自定义算子功能是不能满足什么需求吗？

因为我想要导出shift_cuda类之后可以引用其forward和backward函数，在paddle的文档中没有找到类似的接口
大概这种引用：
class ShiftFunction(PyLayer):
    
    @staticmethod
    def forward(ctx, input,xpos,ypos,stride=1):
        if stride==1:
            xpos = xpos
            ypos = ypos
        else:
            ypos = ypos + 0.5
            # ypos = ypos + 0.5
        output = shift_cuda.forward(input,xpos,ypos,stride)
        ctx.save_for_backward(input, output, xpos, ypos)
        ctx.stride = stride
        return output

    @staticmethod
    def backward(ctx, grad_output): 
        grad_output = grad_output.contiguous()
        input, output, xpos, ypos = ctx.saved_variables
        grad_input,grad_xpos,grad_ypos = shift_cuda.backward(grad_output, input, output, xpos, ypos, ctx.stride)
        return grad_input, grad_xpos, grad_ypos, None

**Comment by zyfncg** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/custom_op/new_cpp_op_cn.html#setuptools
自定义算子可以封装成一个python接口，编译方面可以参考这里面的一些实现细节。

backward执行一般是框架内部自动调用，导出为python函数后可能还需要关注下是否有被框架执行到

**Comment by zhao-sy** [comment]
> 

嗯，您发的链接我之前看过了，因为是现有代码做框架迁移所以希望尽可能少改动代码内容，想问一下paddle自带的自定义算子功能可以实现我想要的forward和backward函数封装吗?如果可以的话应该怎么做？
附：我编译出来的shift_cuda.py，并不含有以上功能。
#
def shift_cuda(input,xpos,ypos,stride):
    # prepare inputs and outputs
    ins = {'input' : input,'xpos' : xpos,'ypos' : ypos,'stride' : stride}
    attrs = {}
    outs = {}
    out_names = ['Out']

    # The output variable's dtype use default value 'float32',
    # and the actual dtype of output variable will be inferred in runtime.
    if in_dygraph_mode():
        ctx = CustomOpKernelContext()
        for i in [input,xpos,ypos,stride]:
            ctx.add_inputs(i)
        for j in []:
            ctx.add_attr(j)
        for out_name in out_names:
            outs[out_name] = core.eager.Tensor()
            ctx.add_outputs(outs[out_name])
        core.eager._run_custom_op(ctx, "shift_cuda", True)
    else:
        if _in_legacy_dygraph():
            for out_name in out_names:
                outs[out_name] = VarBase()
            _dygraph_tracer().trace_op(type="shift_cuda", inputs=ins, outputs=outs, attrs=attrs)
        else:
            helper = LayerHelper("shift_cuda", **locals())
            for out_name in out_names:
                outs[out_name] = helper.create_variable(dtype='float32')

            helper.append_op(type="shift_cuda", inputs=ins, outputs=outs, attrs=attrs)

    res = [outs[out_name] for out_name in out_names]

    return res[0] if len(res)==1 else res

**Comment by zyfncg** [comment]
导出backward函数的作用是什么？如果只是引入一个`shift_cuda`算子用于组网训练的话，我理解按照自定义C++算子的格式写好算子实现后再调用编译封装好的python接口就可以了

**Comment by zhao-sy** [comment]
> 导出backward函数的作用是什么？如果只是引入一个`shift_cuda`算子用于组网训练的话，我理解按照自定义C++算子的格式写好算子实现后再调用编译封装好的python接口就可以了

好的，我再看看，谢谢您
