### ISSUE TITLE
调用paddle_inference库，并发多线程会报错

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#48244]
### 请提出你的问题 Please ask your question

当前使用单线程推理没问题的，但是如果放到线上设备上，有多线程的请求时，并发到4以上就会报错，请问什么原因该如何解决？   
多线程请求时，难道不能等上一线程结束在执行么？     

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::operators::Conv2DFusionOp::InferShape(paddle::framework::InferShapeContext*) const
6   paddle::operators::Conv2DFusionOp::ComputeOutputShape(paddle::framework::InferShapeContext*) const

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 128, the input's shape is [1, 128, 52, 52]; the filter's channels is 768, the filter's shape is [128, 768, 1, 1]; the groups is 1, the data_format is NCHW. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == filter_dims[1] * groups, but received input_channels:128 != filter_dims[1] * groups:768.] (at /paddle/paddle/fluid/operators/fused/conv_fusion_op.cc:208)
  [operator < conv2d_fusion > error]

**Comment by minghaoBD** [comment]
看起来描述和报错不太相关，可能是某些内部逻辑导致的。可以整理一份复现代码吗？

另外，可以明确下线上设备是什么吗？
