### ISSUE TITLE
capi多个输入、多个样本预测

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#4826]
+ 我的需求是：
   模型有3个输入，一次性预测100个样本。按照下面这个链接写的，代码如下：
   [capi预测](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/dense/main.c)  

+  代码：
```c++
int cnt_samples = 100;
paddle_arguments_resize(in_args, 3); //nn有3个输入

for(int k=0; k<3; k++){
    paddle_matrix mat = paddle_matrix_create( cnt_samples,   64,   false);
    paddle_real* array;
    for(int i=0; i<cnt_samples; i++){
        paddle_matrix_get_row(mat, i, &array);
        copy(a.begin(), a.end(), array);  //假设a已经有值了
    }
    paddle_arguments_set_value(in_args, k, mat);
}    

paddle_arguments out_args = paddle_arguments_create_none();
paddle_gradient_machine_forward(machine, in_args, out_args, false));

//取出预测值
for(int i=0; i<cnt_samples; i++){
    paddle_matrix prob = paddle_matrix_create_none();
    paddle_arguments_get_value(out_args, i, prob);
    paddle_matrix_get_row(prob, i, &array);
    std::cout<< "pCTR ="<<array[1]<<std::endl;
}

```

+ 问题1：
    为啥打印的100个pCTR都是一样的？请问，我这样写是对的吗？

+ 问题2：这两个函数的参数列表都是什么意思呢？
```c++
paddle_arguments_get_value(out_args, i, prob); //这个i是指out_args的第i行，其实也就是第i个样本吧
paddle_matrix_get_row(prob, i, &array);  // 这个i也是上面这个意思？？
```

**Comment by qingqing01** [comment]
@Jarlonyan 

1.  请确保输入100个样本的值都不相同。
2.  paddle_arguments_get_value  

https://github.com/PaddlePaddle/Paddle/blob/8fe7bf38028b9ed9995f35e7fc3bab209d76a99a/paddle/capi/arguments.h#L78-L87

从注释来看，这里的ID指的是第几个输出的Argument，不是第几个样本。你这里有一个输出`paddle_arguments out_args`,  应该是：

```cpp
paddle_arguments_get_value(out_args, 0, prob);
```

**Comment by Jarlonyan** [comment]
已经OK啦。谢谢。
paddle_arguments_get_value(out_args, 0, prob);  这个0是指第几个输出，一般输出只有一个，这里就设为0。
paddle_matrix_get_row(prob, 0, &array); 这个0是指第1个样本。
