### ISSUE TITLE
对LSTM的Cell State进行Bound

### ISSUE THREAD

**Issue by WorldEditors** [PaddlePaddle/Paddle#48277]
### 需求描述 Feature Description

发现Paddle LSTM的Cell State的更新是以经典的方式: $c_t=c_{t-1} * f_t + i_t * g_t$
但这种方式存在$c_t$爆炸的风险。
在一些长序列任务的调研中，我遭遇了该现象。
后来查资料，近来LSTM的实现方式开始对cell state进行Bound，即 （见 https://stackoverflow.com/questions/44184403/exploding-cell-state-in-lstm ）
$c_t=\sigma(c_{t-1} * f_t + i_t * g_t)$
建议Paddle增加这种类型的LSTM支持

### 替代实现 Alternatives
上面式子可以进一步改进为
$c_t=K \sigma(1/K *(c_{t-1} * f_t + i_t * g_t))$
K为预设的常数

**Comment by lyuwenyu** [comment]
收到 感谢建议

**Comment by phlrain** [comment]
建议通过继承paddle.nn.LSTMCell，自定义NewLSTMCell，重载forward函数（重新定义公式），然后通过 paddle.nn.RNN这个接口将NewLSTMCell组装为一个RNN网络来使用，详见：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4rc/api/paddle/nn/RNN_cn.html#rnn
