### ISSUE TITLE
Recently modification of `kernel_factory` cause lots of redundant log

### ISSUE THREAD

**Issue by parap1uie-s** [PaddlePaddle/Paddle#48290]
### bug描述 Describe the Bug

See https://github.com/PaddlePaddle/Paddle/pull/48245,

When we train EfficientNet-B5 (w/ some depthwise_conv2d operations), massive logs fill the screen.

![image](https://user-images.githubusercontent.com/23453851/203542256-4e2299dd-c604-4442-a11a-298d5249121a.png)

### 其他补充信息 Additional Supplementary Information

Any suggestions? Thanks.

**Comment by jiahy0825** [comment]
Actually, https://github.com/PaddlePaddle/Paddle/pull/48245 has solved this problem. 
Try the latest paddlepaddle package please~
