### ISSUE TITLE
Add version info to *.whl files

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#4830]
Sometimes we may need to check the version of paddlepaddle in python code to ensure we are using the proper version of paddlepaddle. Shall we add a variable `__version__` to the paddle module?

**Comment by typhoonzero** [comment]
Currently the version of `whl` package does not match the github release tags. That was because, `pypi` can't overwrite the previously uploaded packages.

We need to keep the pypi package version the same to git tags using CI system.
