### ISSUE TITLE
A30显卡预测遇到cudaErrorNoKernelImageForDevice，cuda版本是11.2

### ISSUE THREAD

**Issue by xprincehf** [PaddlePaddle/Paddle#48305]
### 请提出你的问题 Please ask your question

使用官方的docker（paddlepaddle/paddle:2.3.2-gpu-cuda11.2-cudnn8）
在A30环境遇到cudaErrorNoKernelImageForDevice
机器的驱动如下

<img width="556" alt="image" src="https://user-images.githubusercontent.com/9077041/203679037-5899356d-284a-495c-8de4-08fef715fc39.png">
cuda环境如下：
<img width="530" alt="image" src="https://user-images.githubusercontent.com/9077041/203679211-38fe1b05-c021-4180-8b9f-e87996a490ed.png">

<img width="911" alt="059dd88662ebd1e4b10e0d4ce678e7a4" src="https://user-images.githubusercontent.com/9077041/203678935-5c8b96a4-fd15-45dc-8e76-c5bc5e1f9dae.png">

**Comment by zh794390558** [comment]
cuda 11.4 目前应该不支持。

**Comment by xprincehf** [comment]
> 

drive是11.4的，但是docker的runtime环境是11.2的，应该默认是先用runtime的环境吧？
