### ISSUE TITLE
paddle.logsumexp对于大矩阵存在bug

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#48328]
### bug描述 Describe the Bug
- paddle版本develop。

在jupyter notebook中初始化一下这个tensor！矩阵太大了需要分配一段时间。
```python
import paddle, time
tensor = paddle.randn((1, 4096, 1024))
```

下面的代码在jupyter notebook中循环点击运行N次，发现结果正常。
![image](https://user-images.githubusercontent.com/50394665/203740863-0561624c-a04e-434a-a4ac-f420d0744fd8.png)

```python
def logsumexp(x, axis=0, keepdim=False):
    return paddle.log(x.exp().sum(axis=axis, keepdim=keepdim))

start = time.time()
for i in range(100):
    logsumexp(tensor, axis=1, keepdim=True)
end = time.time()
print("custom logsumexp", end-start)
```

下面的代码在jupyter notebook中循环点击运行N次，发现程序卡住了？感觉好像卡在显存分配上？？？？前几步训练还正常，但是你循环运行N次后代码就挂了。
![image](https://user-images.githubusercontent.com/50394665/203740976-ffcb05ac-6819-4a11-bc41-f92830464c76.png)
![image](https://user-images.githubusercontent.com/50394665/203741135-c0cbea8b-09ea-499b-9ac7-dddd855dfbed.png)

```python
start = time.time()
for i in range(100):
    paddle.logsumexp(tensor, axis=1, keepdim=True)
end = time.time()
print("paddle logsumexp", end-start)
```

**Comment by zh794390558** [comment]
已反馈给相关同学。
