### ISSUE TITLE
[Dy2St] Dygraph to Static function extension tracking issue

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#48334]
## 项目说明

用于跟踪 Call-for-Contributions: [动转静功能扩展和旧接口退场](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/Dy2St/to_static_function_extension.md) 各个任务的计划和进度

## 成果总结（整体进展 9/9）
> 按 merge 的时间顺序，排名不分先后：@Aurelius84 (2.5), @SigureMo (2.5), @Tomoko-hjf (3), @DrRyanHuang (1)

| 子任务 | 具体内容和完成时间|相关 PR | 作者 |
|-|-|-|-|
| 1. 旧接口退场| ✅ 1.1 移除 ProgramTranslator（2023/01/11） |#49628 | @DrRyanHuang 
|| ✅ 1.2 移除 declarative 接口[^1] (2022/12/19) | #49145 | @Tomoko-hjf |
|| ✅ 1.3 import 语句规范[^2]（2022/12/01） | #48566, #48637 |  @Aurelius84、@SigureMo |
|| ✅ 1.4 代码迁移至 paddle.jit 目录（2022/12/01） | #48240, #48449, #48513 | @Aurelius84  |
|| ✅ 1.5 移除 TracedLayer 接口，规范 `__all__` 范围，隐藏非公开的API （2022/12/08）|  #48713 | @Aurelius84 |
| 2. 前端功能扩展 | ✅ 2.1 优化 print 函数动转静效果（2022/12/05） | #48672 | @SigureMo |
|| ✅ 2.2 优化 PartialProgramLayer hash 逻辑 | #49752 |  @Tomoko-hjf |
|| ✅ 2.3 新增 ignore_module 接口（2023/01/10） | #49485,  [#5571](https://github.com/PaddlePaddle/docs/pull/5571)| @Tomoko-hjf |
| 3. 后端功能扩展 | ✅ 3.1 移除 Exectuor、ParallelExecutor 两个内核执行器（2022/11/25） | #48298, #48354 | @SigureMo |

[^1]: ~~建议等一下 #48240 merge，否则会有不太好解决的冲突……~~ 已 merge
[^2]: dygraph_to_static 目录移出 fluid 后会利用 isort 格式化一下（目前因为尚未完全移出 fluid 而暂 ignore 了），无需手动完成；因迁移文件，顺手手动清理了部分import格式 by@Aurelius84

**Comment by Aran-Guo** [comment]
任务名称：移除 ProgramTranslator
认领人：Aran-Guo

**Comment by Fancy-hjyp** [comment]
任务名称： 移除 declarative 接口
认领人：Tomoko-hjf

**Comment by Du-Jia** [comment]
任务名称：清理动态 import 语句，解决 circle import 问题
认领人： Du-Jia

**Comment by Aurelius84** [comment]
感谢各位开发者的热情贡献✿✿ヽ(°▽°)ノ✿
