### ISSUE TITLE
paddle2.3.2 存在Tensor的数值问题

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/Paddle#48333]
### bug描述 Describe the Bug

在使用如下代码进行评估时，出现mIOU等指标出现负数，究其原因发现训练500 iters之后，输入image tensor存在数值问题，导致后续一系列错误，具体数值问题表现为转换为numpy之后的平均值和tensor的平均值不一致。
<img width="489" alt="7167be0cefafdbd28d1fd8ccacb2c03c" src="https://user-images.githubusercontent.com/34859558/203747461-15425c85-c500-45c5-8c6a-8cca2de426a7.png">

代码：https://github.com/shiyutang/PaddleSeg/tree/Maskformer
复现步骤：
1. 在paddle2.3.2上，执行下面指令，训练500 iters，进入评估，出现评估精度异常
```
python train.py --config configs/maskformer/maskformer_ade20k_swin_tiny.yml  --do_eval  --use_vdl --save_interval 500 --save_dir saved_model/maskformer/test --num_workers 4 --log_iters 100
```

### 其他补充信息 Additional Supplementary Information

版本回退到paddle2.2.2，问题解决。

**Comment by zh794390558** [comment]
已反馈给相关同学。

**Comment by shiyutang** [comment]
感觉是2.3.2引入的框架问题，2.2和2.4都ok
