### ISSUE TITLE
InferShape cannot obtain LoD information.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#4835]
The current `InferShape` interface cannot obtain the LoD information(the sequence information). This makes the output dimension of the CRF operator cannot be correctly set in the `InferShape` function.

Because the CRF operator takes sequences as its inputs and outputs a non-sequence as the result. How many sequences are there in the input is required (the LoD information) to determine the output dimension.

I have to set **an arbitrarily wrong** dimension to the output in `InferShape` and then resize the right dimension in `Compute`. This seems very tricky.

Have we already determined that the LoD will not pass to `InferShape` in operator's kernel?

@jacquesqiao @reyoung

**Comment by lcy-seso** [comment]
Do you intend to separating information can be determined without any training data and information depending on training data?

If so, I prefer not to set the dimension rather than setting a wrong dimension.

**Comment by lcy-seso** [comment]
The changes were brought by this issue https://github.com/PaddlePaddle/Paddle/issues/4183 and this PR https://github.com/PaddlePaddle/Paddle/pull/3946.

**Comment by luotao1** [comment]
Same question with sequence_pool_op.
> I prefer not to set the dimension rather than setting a wrong dimension.

+1

**Comment by Yancey1989** [comment]
+1, the same question with sequence_concat_op. And maybe most of the sequence operators have the same question.

**Comment by dzhwinter** [comment]
Maybe we need to implement this base function? @jacquesqiao 
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/shape_inference.h#L60

```
  virtual const std::vector<std::string> &Outputs(
      const std::string &name) const = 0;
  // TODO(qiao) implement this function
  void ShareLoD(const std::string &in, const std::string &out, size_t i = 0,
                size_t j = 0) const {}

```

**Comment by Xreki** [comment]
`ShareLoD` is not enough. Sometimes, 
- the output's `dims` is calculated according to the input's `dims` and `lod`.
- the output's `lod` is related to the input's `lod` but not the same.

**Comment by chengduoZH** [comment]
+1, the same question with sequence_project_op.

**Comment by jacquesqiao** [comment]
ShareLoD is already implemented by https://github.com/PaddlePaddle/Paddle/pull/5259

**Comment by lcy-seso** [comment]
After `ShareLod` has been implemented, does this mean we should move checks related to LoD information from `Compute` into `InferShape` to make our design be consistent. What is you suggestion? @jacquesqiao
