### ISSUE TITLE
paddleX 实力分割模型 推理报错 Cuda error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by tjdster** [PaddlePaddle/Paddle#48366]
### 请提出你的问题 Please ask your question

同样大小的图片有的测试就报错

**Comment by zhiboniu** [comment]
你好，上面的信息太简洁了无法帮助解决问题，能否提供一下完整的报错log，以及执行的命令或模型

**Comment by tjdster** [comment]
paddleX 客户端 测试 错误日志 Cuda error(700), an illegal memory access was encountered 。The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunch

**Comment by tjdster** [comment]
![Uploading 微信图片_20221125125050.png…]()

**Comment by tjdster** [comment]
报错代码
for (int i = 0; i < inputs.size(); i++) {
    auto in_tensor = predictor_->GetInputHandle(input_names[i]);
    in_tensor->Reshape(inputs[i].shape);
    if (inputs[i].dtype == FLOAT32) {
      float* im_tensor_data;
      im_tensor_data = (float*)(inputs[i].data.data());  // NOLINT
      in_tensor->CopyFromCpu(im_tensor_data);
    } else if (inputs[i].dtype == INT64) {
      int64_t* im_tensor_data;
      im_tensor_data = (int64_t*)(inputs[i].data.data());  // NOLINT
      in_tensor->CopyFromCpu(im_tensor_data);
    } else if (inputs[i].dtype == INT32) {
      int* im_tensor_data;
      im_tensor_data = (int*)(inputs[i].data.data());  // NOLINT
      in_tensor->CopyFromCpu(im_tensor_data);
    } else if (inputs[i].dtype == INT8) {
      uint8_t* im_tensor_data;
      im_tensor_data = (uint8_t*)(inputs[i].data.data());  // NOLINT
      in_tensor->CopyFromCpu(im_tensor_data);
    } else {
      std::cerr << "There's unexpected input dtype: " << inputs[i].dtype
                << std::endl;
      return false;
    }
  }

**Comment by tjdster** [comment]
cpu运行正常

**Comment by tjdster** [comment]
paddleX 客户端 测试 错误日志 Cuda error(700), an illegal memory access was encountered 。The device encountered a load or store instruction on an invalid memory address. This leaves the process in an inconsistentstate and any further CUDA work will return the same error. To continue using CUDA, the process must be terminated and relaunch

**Comment by tjdster** [comment]
报错代码
for (int i = 0; i < inputs.size(); i++) {
auto in_tensor = predictor_->GetInputHandle(input_names[i]);
in_tensor->Reshape(inputs[i].shape);
if (inputs[i].dtype == FLOAT32) {
float* im_tensor_data;
im_tensor_data = (float*)(inputs[i].data.data()); // NOLINT
in_tensor->CopyFromCpu(im_tensor_data);
} else if (inputs[i].dtype == INT64) {
int64_t* im_tensor_data;
im_tensor_data = (int64_t*)(inputs[i].data.data()); // NOLINT
in_tensor->CopyFromCpu(im_tensor_data);
} else if (inputs[i].dtype == INT32) {
int* im_tensor_data;
im_tensor_data = (int*)(inputs[i].data.data()); // NOLINT
in_tensor->CopyFromCpu(im_tensor_data);
} else if (inputs[i].dtype == INT8) {
uint8_t* im_tensor_data;
im_tensor_data = (uint8_t*)(inputs[i].data.data()); // NOLINT
in_tensor->CopyFromCpu(im_tensor_data);
} else {
std::cerr << "There's unexpected input dtype: " << inputs[i].dtype
<< std::endl;
return false;
}
}

**Comment by zhiboniu** [comment]
你好，看起来像是拷贝的内存范围大于in_tensor在gpu上分配的空间，请确认in_tensor数据类型，将inputs[i].data数据类型转换成和in_tensor一样后拷贝。如果后者数据类型占用空间大于前者，则拷贝会超出范围。

**Comment by tjdster** [comment]
数据类型都是float吧，上面代码已经做了判断， 但是拷贝出错，有的图测试没有问题，大小一致

**Comment by zhiboniu** [comment]
能否抓一下错误看看图片有什么区别呢，这样看来出错有可能是图片差异的原因。

**Comment by tjdster** [comment]
换个模型或者图片就可以，但是其他图又会出问题，用cpu没问题

**Comment by tjdster** [comment]
![微信图片_20221125125050](https://user-images.githubusercontent.com/61610666/204066196-f3b501ba-b442-4697-a519-bace753a29c2.png)

**Comment by tjdster** [comment]
![488574e32dcb57bfc5265ae204d52e3](https://user-images.githubusercontent.com/61610666/204066260-0ec57075-f3c6-4386-9d8a-b3e0164c4eb9.png)

**Comment by tjdster** [comment]
我改变模型的- ResizeByShort:由
    max_size: 2000
    short_size: 200
改为
    max_size: 2500
    short_size: 200
测试可以通，不知道这是什么原因引起的

**Comment by tjdster** [comment]
更改图片输入尺寸测试通过，但是之后其他图片还是出现

**Comment by tjdster** [comment]
输入图像尺寸长度在3500-5500，宽度在200-300不等

**Comment by tjdster** [comment]
![image](https://user-images.githubusercontent.com/61610666/204074448-1a8bfa19-d2d6-4b5f-8bd9-109b8a76400b.png)
![image](https://user-images.githubusercontent.com/61610666/204074464-bf90f39b-ff5f-45c9-a9c8-47d42e4fb003.png)
应该跟图片有关，将图片这样处理可以通过

**Comment by tjdster** [comment]
![image](https://user-images.githubusercontent.com/61610666/204076025-531d1b06-1197-44f9-9dce-7979aa6b8b84.png)
在图片上画个缺陷检测可以通过，不画就报错，

**Comment by zhiboniu** [comment]
这样有可能跟图像处理有关系，可以先在模型代码对应的repo里去问问，看看图像处理上是不是有什么bug
