### ISSUE TITLE
Tensor.numpy() 在静态图转换成numpy array 失败

### ISSUE THREAD

**Issue by shiyutang** [PaddlePaddle/Paddle#48378]
### bug描述 Describe the Bug

最小可复现代码：
```
https://github.com/shiyutang/PaddleSeg/tree/gscnn
python export.py --config configs/gscnn/gscnn_resnet50_os8_cityscapes_1024x512_80k.yml  --save_dir GSCNN --without_argmax --with_softmax --input_shape 1 3 1024 512
```
报错信息：
<img width="572" alt="image" src="https://user-images.githubusercontent.com/34859558/203945287-41b6ae07-a625-457b-a885-3985e54ad351.png">

打印img_arr 也可以发现其为lod tensor，而不是numpy array，但是不能转换为numpy array 的话，会出现cv2算子报错。

**Comment by zhiboniu** [comment]
你好，numpy和cv2的工作模式是动态执行的方式，静态图是先建图后执行的方式，两者不能兼容。所以tensor.numpy()也只在动态图下使用。

**Comment by shiyutang** [comment]
好的，谢谢
