### ISSUE TITLE
Paddle中tensor的索引取值问题

### ISSUE THREAD

**Issue by zhangyubo0722** [PaddlePaddle/Paddle#48372]
### 请提出你的问题 Please ask your question

假如给一个tensor，x=[[1., 2., 3.],[2., 3., 4.]]，shape为(2,3)   和一个索引index=[[0, 1, 2],   [1, 2, 0,], [2, 1, 0]]，shape为(3,3),当运行y=x[:,index]时报错"IndexError: Valid index accept int or slice or ellipsis or list, but received [slice(None, None, None), Tensor(shape=[49, 49], dtype=int64, place=Place(gpu:0), stop_gradient=True,"而使用pytroch进行索引取值时可以正常运行，y=x[:,index]得到y=[[[1., 2., 3.],[2., 3., 1.],[3., 2., 1.]], [[2., 3., 4.],[3., 4., 2.],[4., 3., 2.]]]

**Comment by zhangyubo0722** [comment]
`import paddle
import torch


index=[[0, 1, 2],
       [1, 2, 0],
       [2, 1, 0]]

x_paddle = paddle.to_tensor([[1., 2., 3.],
                             [2., 3., 4.]])
y_paddle = paddle.to_tensor(index, dtype="int64")
result_paddle = x_paddle[:, y_paddle]
print(result_paddle)

x_torch = torch.tensor([[1., 2., 3.],
                       [2., 3., 4.]])
y_torch = torch.LongTensor(index)
result_torch = x_torch[:, y_torch]
print(result_torch)
print(result_torch.shape)`

**Comment by zhiboniu** [comment]
你好，该种情况可以使用paddle.index_select

**Comment by zhangyubo0722** [comment]
> 你好，该种情况可以使用paddle.index_select

好的非常感谢
