### ISSUE TITLE
torch中的transforms.GaussianBlur如何用paddle实现

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/Paddle#48381]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

### 替代实现 Alternatives

请问，有人将torch中的transforms.GaussianBlur用paddle实现吗

**Comment by zhiboniu** [comment]
你好，数据增强中的GaussianBlur可以调用cv2实现
