### ISSUE TITLE
humanseg_v2 to use shuffle_channel op instead of reshape+transpose+reshape

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#48389]
### 需求描述 Feature Description

Hi,
I it seems to me that this block of operators is performing the same operation as `shuffle_channel` operator with `groups=2`. Have this been considered to replace it?
![image](https://user-images.githubusercontent.com/17185347/203974016-e3d6ea2c-6dfd-43f7-9283-90bb9e191079.png)
The test of shuffle channel is comparing against exactly the same set of operations in numpy python/paddle/fluid/tests/unittests/test_shuffle_channel_op.py
![image](https://user-images.githubusercontent.com/17185347/203976645-121cc843-110d-4e6e-b7f4-167ac3973bce.png)

**Comment by zhiboniu** [comment]
Thanks for your suggestion, we will consider it.

**Comment by juncaipeng** [comment]
Hi, I have checked that the  [HumansegV2 FP32 model](https://paddleseg.bj.bcebos.com/dygraph/pp_humanseg_v2/portrait_pp_humansegv2_lite_256x144_smaller/portrait_pp_humansegv2_lite_256x144_inference_model.zip) does not have `reshape+transpose+reshape`. The above model is quantized format, please seed it to me. @sfraczek

**Comment by sfraczek** [comment]
Ok, sorry for misunderstanding. It was this model:
```
https://github.com/PaddlePaddle/PaddleTest/blob/develop/inference/python_api_test/test_int8_model/prepare.sh

wget https://paddleseg.bj.bcebos.com/dygraph/ppseg/ppseg_lite_portrait_398x224_with_softmax.tar.gz
tar -xf ppseg_lite_portrait_398x224_with_softmax.tar.gz -C ./models
rm -rf ppseg_lite_portrait_398x224_with_softmax.tar.gz
```
Thanks for sharing the actual humanseg_v2.

**Comment by sfraczek** [comment]
I was looking at this model
https://bj.bcebos.com/v1/paddle-slim-models/act/PaddleSeg/qat/pp_humanseg_qat.tar
and this
https://paddleseg.bj.bcebos.com/dygraph/ppseg/ppseg_lite_portrait_398x224_with_softmax.tar.gz

**Comment by sfraczek** [comment]
Do you have non-dygraph version of this model you shared? I have ran profiling and I see that some dygraph operations are taking a significant portion of total execution time. More than 60%.
![image](https://user-images.githubusercontent.com/17185347/205325430-80fe3672-c516-40d4-b893-1adc028ea090.png)

**Comment by yaomichael** [comment]
@juncaipeng @yeliang2258 can you answer @sfraczek question?

**Comment by juncaipeng** [comment]
> I was looking at this model https://bj.bcebos.com/v1/paddle-slim-models/act/PaddleSeg/qat/pp_humanseg_qat.tar and this https://paddleseg.bj.bcebos.com/dygraph/ppseg/ppseg_lite_portrait_398x224_with_softmax.tar.gz

This is the pp-humansegv1 model.  I suggest optimizing the inference speed of the pp-humansegv2 model, which has better performance than pp-humansegv1 model.

**Comment by yaomichael** [comment]
@juncaipeng I believe @sfraczek latest question is about the v2 [HumansegV2 FP32 model](https://paddleseg.bj.bcebos.com/dygraph/pp_humanseg_v2/portrait_pp_humansegv2_lite_256x144_smaller/portrait_pp_humansegv2_lite_256x144_inference_model.zip)

**Comment by onecatcn** [comment]
> Do you have non-dygraph version of this model you shared? I have ran profiling and I see that some dygraph operations are taking a significant portion of total execution time. More than 60%. ![image](https://user-images.githubusercontent.com/17185347/205325430-80fe3672-c516-40d4-b893-1adc028ea090.png)

@sfraczek think the model in the link shared by @juncaipeng is a non-dygraph model. For more information, two versions of non-dygraph model for pp-humansegv2 are provided in the section 4.1 Portrait Segmentation Models on this page: https://github.com/PaddlePaddle/PaddleSeg/tree/develop/contrib/PP-HumanSeg, the inference models in the last column are non-dygraph model.

**Comment by sfraczek** [comment]
Thank you, but all the links in table in section 4.2 seem to have dygraph in url.

**Comment by juncaipeng** [comment]
@sfraczek  These inference models do not have dygraph operations. You can use Netron to open inference models and check again. 

![4c5aeb972894d06bce0ade01b9a58979](https://user-images.githubusercontent.com/52520497/209308767-0bab17b8-15f8-4f98-84e0-6c0b957809a2.jpg)

**Comment by sfraczek** [comment]
Ok, thank you very much for the explanation. 👍

**Comment by sfraczek** [comment]
We have identified the operations with 'pybind_imperative_func' as metrics for calculating mAP called directly from python in test_segmentation_infer.py. Also since I have the model, I will close the issue. Although you could still replace that pattern in humanseg_v1 as I described at the beginning.
