### ISSUE TITLE
在6600xt上编译paddle时，Subprocess aborted！

### ISSUE THREAD

**Issue by TimeYWL** [PaddlePaddle/Paddle#48382]
### 请提出你的问题 Please ask your question

os: ubuntu 20.04
device: 6600xt
rocm: 5.2.0
编译指令：`cmake .. -DPY_VERSION=3.8 -DWITH_ROCM=ON -DWITH_TESTING=OFF -DWITH_DISTRIBUTE=OFF -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release -DWITH_RCCL=OFF`
`make`
错误：
[ 90%] Linking CXX executable eager_generator
[ 90%] Built target eager_generator
free(): invalid pointer
Subprocess aborted
make[2]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/build.make:70: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen] Error 1
make[1]: *** [CMakeFiles/Makefile2:160640: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by zhiboniu** [comment]
你好，上面信息有限，能否补充一下完整的log，包含具体error行的部分。

**Comment by TimeYWL** [comment]
> 你好，上面信息有限，能否补充一下完整的log，包含具体error行的部分。
以下是更为详细的编译输出，但并没有详细的错误信息

/opt/rocm/include/hip/amd_detail/amd_hip_complex.h:105:22: warning: implicitly-declared ‘constexpr hip_impl::Scalar_accessor<double, double [2], 1>::Scalar_accessor(const hip_impl::Scalar_accessor<double, double [2], 1>&)’ is deprecated [-Wdeprecated-copy]
  105 |         lhs.y -= rhs.y;                                                                            \
      |                      ^
/opt/rocm/include/hip/amd_detail/amd_hip_complex.h:257:1: note: in expansion of macro ‘COMPLEX_SUB_PREOP_OVERLOAD’
  257 | COMPLEX_SUB_PREOP_OVERLOAD(hipDoubleComplex)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /opt/rocm/include/hip/amd_detail/amd_channel_descriptor.h:28,
                 from /opt/rocm/include/hip/channel_descriptor.h:32,
                 from /opt/rocm/include/hip/texture_types.h:38,
                 from /opt/rocm/include/hip/hip_runtime_api.h:505,
                 from /opt/rocm/include/hip/hip_runtime.h:113,
                 from /opt/rocm/include/hiprand/hiprand.h:24,
                 from /opt/rocm/include/hiprand.h:20,
                 from /home/ywl/paddle/paddle/fluid/platform/enforce.h:44,
                 from /home/ywl/paddle/paddle/fluid/framework/attribute.h:28,
                 from /home/ywl/paddle/paddle/fluid/framework/op_info.h:22,
                 from /home/ywl/paddle/paddle/fluid/eager/auto_code_generator/eager_generator.cc:21:
/opt/rocm/include/hip/amd_detail/amd_hip_vector_types.h:254:30: note: because ‘hip_impl::Scalar_accessor<double, double [2], 1>’ has user-provided ‘hip_impl::Scalar_accessor< <template-parameter-1-1>, <template-parameter-1-2>, <anonymous> >& hip_impl::Scalar_accessor< <template-parameter-1-1>, <template-parameter-1-2>, <anonymous> >::operator=(const hip_impl::Scalar_accessor< <template-parameter-1-1>, <template-parameter-1-2>, <anonymous> >&) [with T = double; Vector = double [2]; unsigned int idx = 1]’
  254 |             Scalar_accessor& operator=(const Scalar_accessor& x) noexcept {
      |                              ^~~~~~~~
/opt/rocm/include/hip/amd_detail/amd_hip_vector_types.h:311:43: note:   initializing argument 1 of ‘hip_impl::Scalar_accessor< <template-parameter-1-1>, <template-parameter-1-2>, <anonymous> >& hip_impl::Scalar_accessor< <template-parameter-1-1>, <template-parameter-1-2>, <anonymous> >::operator-=(U) [with U = hip_impl::Scalar_accessor<double, double [2], 1>; typename std::enable_if<std::is_convertible<U, T>{}>::type* <anonymous> = 0; T = double; Vector = double [2]; unsigned int idx = 1]’
  311 |             Scalar_accessor& operator-=(U x) noexcept {
      |                                         ~~^
[ 90%] Linking CXX executable eager_generator
[ 90%] Built target eager_generator
free(): invalid pointer
Subprocess aborted
make[2]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/build.make:70: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen] Error 1
make[1]: *** [CMakeFiles/Makefile2:160640: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by TimeYWL** [comment]
> 下是更为详细的编译输出，但并没有详细的错误信息

并没有具体的错误行，这就是头疼的地方，我在输出记录中搜索error都无法搜到。
还想请问一下，我的这个平台和cmake指令有问题吗？

**Comment by zhiboniu** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html
可以按这里的文档详细对照排查一下吧，
另外可以试试直接安装编译好的paddle是否可行，如果可行那肯定是支持的

**Comment by linwownil** [comment]
你好，可以看下[这里](https://github.com/PaddlePaddle/Paddle/issues/49676#issuecomment-1607308511)和对应的[仓库](https://github.com/linwownil/Paddle/tree/develop_rocm502)
gfx1030能用，手动添加6600xt的build target (gfx1032)或许可以编译
