### ISSUE TITLE
paddle2.4.0rc tensor索引问题

### ISSUE THREAD

**Issue by mike-egg123** [PaddlePaddle/Paddle#48385]
### bug描述 Describe the Bug

在paddle2.4.0rc版本中，使用paddle.to_tensor函数将一个numpy的array类型转成paddle的tensor类型后，出现了奇怪的现象，如图：
<img width="1058" alt="image" src="https://user-images.githubusercontent.com/59782185/203959847-dfae7c6b-3a83-4181-85dc-b264c7a13bfc.png">
`X_tensor`索引为0的地方明明是有非零值的，但用`X_tensor[0]`取这个元素的时候，不知道怎么回事全变成0了，试过将place改成cpu，可以解决这问题，但还是很奇怪。同时这个现象不会在paddle2.3.2中出现。

**Comment by zhiboniu** [comment]
你好，我这里无法复现这个问题。辛苦提供一下更详细的信息，方便定位，包括系统、cuda版本、paddle commit版本。谢谢

**Comment by zhiboniu** [comment]
另外，可以确认一下
x_tensor=paddle.randn(())
print(x_tensor)
print(x_tensor[0])
这种最小测试单元能否复现

**Comment by mike-egg123** [comment]
系统版本：
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
```
cuda版本：
```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Tue_May__3_18:49:52_PDT_2022
Cuda compilation tools, release 11.7, V11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
```
paddle commit 版本：未知，但我是用这个指令使用docker的方法安装的：`nvidia-docker pull paddlepaddle/paddle:2.4.0rc-gpu-cuda11.7-cudnn8.4-trt8.4`，时间为11月1日。
最小测试单元可以复现：
![image](https://user-images.githubusercontent.com/59782185/203983377-3e3e9609-d975-4754-8616-b951b8b21b09.png)

**Comment by zhiboniu** [comment]
好的，感谢，我们找到问题后会及时回复，请留意后续消息。
当前使用可以先在其他环境下使用。
