### ISSUE TITLE
加载训练数据时报错

### ISSUE THREAD

**Issue by Farewell-CK** [PaddlePaddle/Paddle#48406]
### bug描述 Describe the Bug

模型保存
paddle.save(model.state_dict(), 'modelweight{}.pdparams'.format(epoch))
paddle.save(Opt.state_dict(), 'SGDepoch:{}.pdpot'.format(epoch))
模型加载
model = Facenet(num_classes=10)
model.load_dict('modelweight6.pdparams')
在加载预测的时候报错
d:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py:1492: UserWarning: Skip loading for satge1.0.0.weight. satge1.0.0.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
d:\anaconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py:1492: UserWarning: Skip loading for satge1.0.1.weight. satge1.0.1.weight is not found in the provided dict.
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))

**Comment by wangxinxin08** [comment]
这个是warning，表示你保存的权重文件中缺失了某一个权重satge1.0.0.weight.，可以检查下组网等代码
