### ISSUE TITLE
paddle2.4在jupyter的import报错

### ISSUE THREAD

**Issue by ZhangzrJerry** [PaddlePaddle/Paddle#48407]
### bug描述 Describe the Bug

系统win10
python3.9.1

<img width="820" alt="image" src="https://user-images.githubusercontent.com/87751816/204071657-061095c0-4909-41ae-aa69-d5bf81f53bd4.png">
如图，终端中完成安装后进入python能够正常引入paddle并输出版本号，在jupyter下运行`import paddle`就会报错，在2.3.2版本下也会有如图问题，同目录下python文件则可以正常引入
<img width="813" alt="image" src="https://user-images.githubusercontent.com/87751816/204071749-da9c8255-b88d-4f64-a49f-d922c930ad09.png">

这个问题我之前在V2.3.2的时候也报过，来自 #45307，后来有段时间不会出现这个问题，但现在又出现了相关情况

**Comment by wangxinxin08** [comment]
这种一般不是paddle的问题，猜测可能没安装到同一python环境或者python环境有问题，建议直接在jupyter的notebook中安装，比如
```
!pip install paddlepaddle
```

**Comment by ZhangzrJerry** [comment]
主要的我项目昨晚还能跑，今天跑的时候告诉我import paddle有问题一下子给我整不会了，我重启了内核解决了问题
