### ISSUE TITLE
飞桨2.4,gpu版本,python3.10.8,cuda10.2,windows10 64位,使用pip uninstall paddleclas报错,跟fassi_cpu有关

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#48414]
### bug描述 Describe the Bug

飞桨2.4,gpu版本,python3.10.8,cuda10.2,windows10 64位,使用pip uninstall paddleclas报错,跟fassi_cpu有关

**Comment by yuwoyizhan** [comment]
970显卡

**Comment by yuwoyizhan** [comment]
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.5/docs/tutorials/INSTALL_cn.md
这个链接,export CUDA_VISIBLE_DEVICES=0报错,这个报错是所有飞桨版本都会报的.
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
这个代码报错,只有飞桨2.4报错,我肯定原来的2.3.2不会报错.

**Comment by yuwoyizhan** [comment]
不知道是昨天还是前天,飞桨官网上线了2.4版本,我就安装了,然后初步试了一下,就报了3个错误了,真是无语.2个半月的测试,怎么还会有这么低级的报错?

**Comment by wangxinxin08** [comment]
发一下报错截图看看呢？我这边运行以下命令没有报错，另外fassi是paddleclass引入的向量检索库，和PaddlePaddle无关
```
python tools/infer.py -c configs/ppyolo/ppyolo_r50vd_dcn_1x_coco.yml -o use_gpu=true weights=https://paddledet.bj.bcebos.com/models/ppyolo_r50vd_dcn_1x_coco.pdparams --infer_img=demo/000000014439.jpg
```

**Comment by jingsongliujing** [comment]
这个估计是paddledetection套件版本没跟上paddle的新版本，建议就是还是用2.3，估计官方还要一段时间和套件进行适配
