### ISSUE TITLE
Paddle 2.4.0版本的缺少 libpython3.8.so.1.0

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#48428]
### bug描述 Describe the Bug

 - PaddlePaddle 2.4.0
 - Ubuntu 18.04
 - Python 3.8
 - Anaconda 3

如果安装的是 2.4.0rc0是没有任何问题的，安装这个稳定版本就这样了。安装命令：
```
conda install paddlepaddle-gpu==2.4.0 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
or
conda install paddlepaddle-gpu==2.4.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```

报错信息：
```
Error: Can not import paddle core while this file exists: /home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "train.py", line 6, in <module>
    from ppasr.trainer import PPASRTrainer
  File "/home/test/yeyupiaoling/PPASR/ppasr/trainer.py", line 11, in <module>
    import paddle
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
```

**Comment by XieYunshen** [comment]
可以把Anaconda的python路径中的lib加入到LD_LIBRARY_PATH中，方法如下
```
find / -name "libpython3.8.so*"
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${your_path}
# 如:
# export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/opt/conda/envs/paddle/lib
```

**Comment by jc-zju** [comment]
> ### bug描述 Describe the Bug
> * PaddlePaddle 2.4.0
> * Ubuntu 18.04
> * Python 3.8
> * Anaconda 3
> 
> 如果安装的是 2.4.0rc0是没有任何问题的，安装这个稳定版本就这样了。安装命令：
> 
> ```
> conda install paddlepaddle-gpu==2.4.0 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge 
> or
> conda install paddlepaddle-gpu==2.4.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
> ```
> 
> 报错信息：
> 
> ```
> Error: Can not import paddle core while this file exists: /home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
> Traceback (most recent call last):
>   File "train.py", line 6, in <module>
>     from ppasr.trainer import PPASRTrainer
>   File "/home/test/yeyupiaoling/PPASR/ppasr/trainer.py", line 11, in <module>
>     import paddle
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
>     from .framework import monkey_patch_variable
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
>     from . import random  # noqa: F401
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
>     import paddle.fluid as fluid
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
>     from . import framework
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
>     from . import core
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 304, in <module>
>     raise e
>   File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 249, in <module>
>     from . import libpaddle
> ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

你好，我也遇到了类似的问题，最后发现是paddle只装了gpu版本的原因，把cpu版本装上就可以了

**Comment by jc-zju** [comment]
我也遇到类似问题，参考这篇博客解决了
https://blog.csdn.net/w5688414/article/details/128070172

**Comment by yeyupiaoling** [comment]
这个的根源是paddlepaddle的问题，应该从根本上解决问题。

**Comment by yier2333** [comment]
> 这个的根源是paddlepaddle的问题，应该从根本上解决问题。

确实，我也报这个错误，感觉需要改系统文件什么的就很不合理

**Comment by tong-zeng** [comment]
从报错信息上看，个人觉得并不是说找不到 libpython3.8.so.1.0 ，而是 libpython3.8.so.1.0 抛出了错误消息，错误是 from . import libpaddle 引起的，也就是说 libpaddle import 不了，请检查下 PaddlePaddle 是否安装成功，例如 import paddle 试试。

**Comment by tong-zeng** [comment]
#48667 
试试把 libpython3.9.so.1.0 这个文件复制到 /usr/lib 目录
libpython3.9.so.1.0 这个文件在 /your/anaconda_home/envs/your_environment_name/lib 目录下

**Comment by rsong0606** [comment]
https://blog.csdn.net/jaket5219999/article/details/127823120?spm=1001.2101.3001.6650.1&utm_medium=distribute.pc_relevant.none-task-blog-2%7Edefault%7EAD_ESQUERY%7Eyljh-1-127823120-blog-121096993.pc_relevant_multi_platform_whitelistv4&depth_1-utm_source=distribute.pc_relevant.none-task-blog-2%7Edefault%7EAD_ESQUERY%7Eyljh-1-127823120-blog-121096993.pc_relevant_multi_platform_whitelistv4&utm_relevant_index=2
这个博客解决了问题 但是cuda又出了问题...
```
 UserWarning: You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default.
  "You are using GPU version Paddle, but your CUDA device is not set properly. CPU device will be used by default."

```

**Comment by jiangke-sr** [comment]
没人说下啥原因，在哪个版本解决吗😒

**Comment by XieYunshen** [comment]
> 没人说下啥原因，在哪个版本解决吗😒

2.4.1已经修复了

**Comment by yeyupiaoling** [comment]
2.4.1的确没有报这个动态库的问题，但是报了其他动态库的问题，如cuda的动态库。

**Comment by yeyupiaoling** [comment]
做个笔记
```
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/test/anaconda3/envs/PaddlePaddle/lib/
```
