### ISSUE TITLE
多卡报错Retry to connect to 0.1.68.146:63314 while the server is not yet listening.

### ISSUE THREAD

**Issue by ZhangJingweiYa** [PaddlePaddle/Paddle#48421]
### bug描述 Describe the Bug

安装的paddle是支持多卡的，但是在多卡的时候一直报错不往下进行

`python -m paddle.distributed.launch train.py \
       --config configs/segformer/segformer_b5_cityscapes_1024x1024_160k.yml \
       --do_eval \
       --use_vdl \
       --save_interval 500 \
       --save_dir output `

2022-11-27 21:31:55 [INFO]      There are 1052/1067 variables loaded into SegFormer.
I1127 21:31:55.544849 3935673 tcp_utils.cc:181] The server starts to listen on IP_ANY:63314
I1127 21:34:05.015228 3935673 tcp_utils.cc:107] Retry to connect to 0.1.68.146:63314 while the server is not yet listening.
I1127 21:36:18.135196 3935673 tcp_utils.cc:107] Retry to connect to 0.1.68.146:63314 while the server is not yet listening.
I1127 21:38:31.255204 3935673 tcp_utils.cc:107] Retry to connect to 0.1.68.146:63314 while the server is not yet listening.

请问这是什么原因？

**Comment by WenmuZhou** [comment]
paddle.run.check()显示多卡ok的吗

**Comment by kuizhiqing** [comment]
It seems the machine network is not configured properly, which get a wrong IP `0.1.68.146`.

Please check network configuration and try it again.
