### ISSUE TITLE
paddle的Layer模块没有register_backward_hook函数可以使用，有替代的函数吗

### ISSUE THREAD

**Issue by lunlu** [PaddlePaddle/Paddle#48430]
### 问题描述 Please describe your issue

paddle的Layer模块没有看到类似torch这种在Module模块可以调用register_backward_hook，请问有替代的方法吗。

**Comment by wanghuancoder** [comment]
Paddle暂时没有支持这个API。但Paddle支持tensor.register_hook。可以实现类似的功能。
