### ISSUE TITLE
期待飞桨全面支持C++,目前飞桨对C++的支持只限于推理

### ISSUE THREAD

**Issue by yuwoyizhan** [PaddlePaddle/Paddle#48433]
### 需求描述 Feature Description

pytorch几年前就支持C++和java了,目前飞桨对于C++的支持,仅仅限于推理.
安装飞桨和飞桨套件,组网,训练,评估等步骤功能,全部不支持C++,顶多算是在推理步骤支持C++.
我提了几个支持C++的issue,飞桨官方找了个人加了我微信,聊了几句,最后他告诉我,支持C++用处不大,难度很大,甚至他还说,支持C++得由更高层的人拍板决定.说白了支持C++就是费力不讨好.
不知道各位飞桨大佬什么想法,反正我希望,有一天可以整个工作流程都可以用C++语言,包括安装,训练,评估,推理等步骤,而不是用python语言.天生厌恶python语言.
飞桨6个月左右更新一次,一年更新2次.pytorch3个月更新一次,而且pytorch对于新技术,新东西的支持速度,比飞桨快多了,比如pytorch比飞桨更快支持3090显卡,更快支持python3.10,更快支持C++和java,目前pytorch为了支持C++17标准,把cuda10.2都去掉了.
说大实话,支持C++我也不知道有什么很大的好处,对我来说,就是不用学习python,只学习C++一门语言就行了.C++的最大优势在于运行速度极快,比python快得多,那个加我微信的飞桨官方人员告诉我,他个人认为,支持C++并不会提高训练速度和推理速度.
pytorch同时支持C++和python,我见过的一个强化学习大项目,绝大多数代码使用C++,我相信,支持C++肯定是有益的,虽然我也不知道具体有什么收益.提高训练速度?提高推理速度?至于说到提高编码速度,编译速度,我觉得更不可能.

**Comment by yghstill** [comment]
@yuwoyizhan 感谢反馈，C++的API正在逐步支持中，具体可以参考demo：https://github.com/chenwhql/paddle-cpp-demo

**Comment by engineer1109** [comment]
phi单独算子在develop可用，但是不可以训练
