### ISSUE TITLE
DenseTensor::rank()

### ISSUE THREAD

**Issue by zh794390558** [PaddlePaddle/Paddle#48444]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

支持 phi::DenseTensor::rank() 接口。

**Comment by chenwhql** [comment]
您好，目前DenseTensor的接口管理非常严格，不会轻易增减，rank()这个接口不是必要的，DenseTensor::dims().size()就是rank()
