### ISSUE TITLE
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by jackyang122** [PaddlePaddle/Paddle#48463]
### bug描述 Describe the Bug

    import paddle
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/home/yangjie/anaconda3/envs/paddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libpython3.8.so.1.0: cannot open shared object file: No such file or directory

**Comment by jackyang122** [comment]
已经看到其他多人也遇到这个bug 了,已经尝试export 修改环境变量.发现conda 创建新环境时,确实不存在这个依赖lib,目前paddle==2.4.0 或许麻烦告知下paddle 之前的版本可以通过使用,或者python 除了3.8还有哪些可以支持的.感谢

**Comment by XieYunshen** [comment]
创建conda环境的命令和conda版本可以发一下么？

**Comment by jackyang122** [comment]
创建命令:conda create -n paddle python=3.8

版本:conda 4.13.0

**Comment by XieYunshen** [comment]
> 创建命令:conda create -n paddle python=3.8
> 
> 版本:conda 4.13.0
我本地使用Linux安装anaconda后，创建环境，或者使用默认环境都是可以找到这个so文件的
<img width="841" alt="image" src="https://user-images.githubusercontent.com/32428676/204271481-b8345378-9d90-46c0-891d-ead46d5a4ffe.png">

**Comment by jackyang122** [comment]
你好,我也是能找到的.找到一堆
/home/yangjie/anaconda3/envs/bbt/lib/libpython3.8.so
/home/yangjie/anaconda3/envs/bbt/lib/libpython3.8.so.1.0
/home/yangjie/anaconda3/envs/bbt/lib/libpython3.so
/home/yangjie/anaconda3/envs/digo/lib/libpython3.8.so
/home/yangjie/anaconda3/envs/digo/lib/libpython3.8.so.1.0
/home/yangjie/anaconda3/envs/digo/lib/libpython3.so
/home/yangjie/anaconda3/envs/paddle/lib/libpython3.8.so
/home/yangjie/anaconda3/envs/paddle/lib/libpython3.8.so.1.0
/home/yangjie/anaconda3/envs/paddle/lib/libpython3.so
但是,
![企业微信截图_16696366616115](https://user-images.githubusercontent.com/31682914/204272256-db36ef85-146c-4bb7-94e5-0b7ed0e417ab.png)

**Comment by jackyang122** [comment]
代码就一行 
![企业微信截图_1669636730734](https://user-images.githubusercontent.com/31682914/204272417-4c6b8bda-22cd-49ba-a74f-4d951d609c64.png)

**Comment by jackyang122** [comment]
![企业微信截图_1669636730734](https://user-images.githubusercontent.com/31682914/204272440-291e8b71-d51e-4e3a-af76-3d8a3ccfe632.png)

**Comment by XieYunshen** [comment]
你先这样操作一下,然后再执行import 命令
`
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/home/yangjie/anaconda3/envs/paddle/lib/
`
参考这个ISSUE：https://github.com/PaddlePaddle/Paddle/issues/48428

**Comment by jackyang122** [comment]
感谢,已经解决

**Comment by hritikakolkar** [comment]
how to do this with  pip environment

**Comment by Harshad165** [comment]
> how to do this with pip environment

Did you get a solution for this?

**Comment by hritikakolkar** [comment]
It has something to do with openssl or simple you can use conda environment. Also make sure python version is greater that 3.7

**Comment by idontkonwher** [comment]
@yghstill Hello, was this bug fixed?
