### ISSUE TITLE
paddle2.4 多卡警告

### ISSUE THREAD

**Issue by jackyang122** [PaddlePaddle/Paddle#48486]
### bug描述 Describe the Bug

目前信息存在如下,请问会影响后续什么吗?还是已经正常安装了?
![企业微信截图_16696892262330](https://user-images.githubusercontent.com/31682914/204424552-29ccca81-0277-4e86-a0c7-f1bbe2e1305e.png)

**Comment by jackyang122** [comment]
参考别人,建议大家在2022.11.29 前后还是用2.3.2版本,2.4.0 兼容性太差

**Comment by LiuChiachi** [comment]
看日志您已经正常安装了。
请问您遇到了什么兼容性问题？

**Comment by jackyang122** [comment]
2.4.0版本会报warning ,可以参考下上图信息,cant enable P2P access 可能是英伟达底层的坑, 目前不影响使用

**Comment by jackyang122** [comment]
麻烦有空讲述下, 这个的含义 cant enable P2P access , 谢谢
