### ISSUE TITLE
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'save_op_compatible_info'

### ISSUE THREAD

**Issue by kulongwei** [PaddlePaddle/Paddle#48489]
### 请提出你的问题 Please ask your question

不知道是不是版本的问题，在运行这行代码时会报错：

File "PaddleSeg/pdseg/train.py", line 403, in train
    save_infer_program(test_prog, ckpt_dir)
  File "PaddleSeg/pdseg/train.py", line 167, in save_infer_program
    paddle.fluid.core.save_op_compatible_info(_test_program.desc)
AttributeError: module 'paddle.fluid.core_avx' has no attribute 'save_op_compatible_info'

请大佬帮忙看一下，如何解决！！！

**Comment by LiuChiachi** [comment]
应该是环境问题～
你使用的paddle版本是？如何安装的呢？机器环境是？
如果跑的代码是seg的原本的代码可以附上链接，我们可以找同学确认下对paddle要求的版本
