### ISSUE TITLE
论文复现时多卡训练报错

### ISSUE THREAD

**Issue by zhangyubo0722** [PaddlePaddle/Paddle#48508]
### 请提出你的问题 Please ask your question

单卡训练时可以跑通，多卡训练时报这个错误`RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to trav
erse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for thi
s error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculat
ion of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate 
gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the 
autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.   
  [Hint: Expected groups_need_finalize_ == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/padd
le/fluid/imperative/reducer.cc:681)`，然后修改ppcls/engine/engine.py里面self.model = paddle.DataParallel(self.model,find_unused_parameters=True)还是不行，请问这是为什么

**Comment by LiuChiachi** [comment]
您好，是否可以 提供最小可复现代码呢，我们可以 更快的帮您定位问题

**Comment by w5688414** [comment]
I meet the same problem when i use all gather in the forward pass on multi gpu training

**Comment by Poet-LiBai** [comment]
使用Paddle3D多卡训练也遇到同样的问题
