### ISSUE TITLE
Create Android toolchain at Docker build time other than runtime

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4851]
The [Dockerfile.android file](https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile.android#L54) runs [`build_android.sh`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build_android.sh) in the `CMD` directive.  It seems that this would make it build Android toolchain every time we run `docker run`. If so, it seems more reasonable to build the toolchain at Docker build time.

**Comment by Xreki** [comment]
In fact, [NDK](https://developer.android.com/ndk/downloads/index.html) is the official toolchain of Google. It contains all tools for all `ANDROID_API` and `ANDROID_ABI`. [Standalone toolchain](https://developer.android.google.cn/ndk/guides/standalone_toolchain.html?hl=zh-cn) is a subset of NDK, and it is generated for specific `ANDROID_ABI` and `ANDROID_API`. The NDK is packaged into docker images, [see](https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile.android#L46).
Currently, Paddle can only be cross-compiled for Android using standalone toolchain. But for different arguments [`ANDROID_ABI` and `ANDROID_API`](https://developer.android.google.cn/ndk/guides/standalone_toolchain.html?hl=zh-cn), different version of standalone toolchain is needed to be generated. The main reason to build standalone toolchain every time when we run `docker run`, is to support all user given `ANDROID_ABI` and `ANDROID_API`.

**Comment by wangkuiyi** [comment]
Got it. I noticed that the building of standalone toolchain doesn't cost much time -- around 1 min. So it is reasonable to keep it in the docker-run stage.
