### ISSUE TITLE
学习策略

### ISSUE THREAD

**Issue by awsssix** [PaddlePaddle/Paddle#48530]
### 请提出你的问题 Please ask your question

请问按OneCycleLR学习策略，在700 iters达到最大学习率，是这样设置配置文件吗
        "lr_scheduler":{
            "name":"OneCycleLR",
            "max_learning_rate": 0.0001,
            "total_steps": 500000,
            "warmup_steps": 700

**Comment by LiuChiachi** [comment]
我查看文档，找到这个参数`phase_pct`。https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/lr/OneCycleLR_cn.html#onecyclelr

你可以在日志中打印出 `learning_rate` 以确保你的修改

**Comment by awsssix** [comment]
需要paddle2.4，CUDA10.1，安装`pip install --upgrade paddlepaddle-gpu==2.4.0 -i https://pypi.tuna.tsinghua.edu.cn/simple`，执行`import paddle`报错
![图片](https://user-images.githubusercontent.com/46213799/204701850-20e244fd-bf88-4b1c-83eb-985d6a133ca2.png)

然后安装`pip install --upgrade paddlepaddle-gpu==2.4.0post101 -i https://pypi.tuna.tsinghua.edu.cn/simple`显示没有这个版本，在CUDA10.1如何安装paddle2.4版本

**Comment by LiuChiachi** [comment]
可以升级cuda版本，现在cuda版本已经支持到11.7了。
或者是你可以查看之前版本的API文档，确保传入的参数正确

**Comment by awsssix** [comment]
release2.3文档没有这个API，2.4新增加的吧，CUDA10.1不能安装2.4.0吗

**Comment by LiuChiachi** [comment]
您好，咨询过安装同学，PaddlePaddle从2.4.0开始不再支持cuda10.1了，您可以使用cuda10.1环境自行编译，但是可能会遇到问题。如果可以的话，建议还是直接升级cuda版本比较方便，可能训练性能也会更好～
