### ISSUE TITLE
静态图下nonezero算子结果shape不对

### ISSUE THREAD

**Issue by yudan12** [PaddlePaddle/Paddle#48547]
### bug描述 Describe the Bug

静态图下nonezero算子结果shape不对

环境：paddle2.4
代码：
import paddle
import paddle.fluid.layers as layers
import numpy as np
import paddle.fluid as fluid

paddle.enable_static()
x1 = paddle.to_tensor([[1.0, 0.0, 0.0],
                       [0.0, 2.0, 0.0],
                       [0.0, 0.0, 3.0]])
x2 = paddle.to_tensor([0.0, 1.0, 0.0, 3.0])
out_z1 = paddle.nonzero(x1)
layers.Print(out_z1, message="out_z1")
tmp = layers.fill_constant(shape=[1], dtype="int64", value=out_z1.shape[0], force_cpu=False)
layers.Print(tmp, message="out_z1.shape")
place = fluid.CPUPlace()
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
ret = exe.run()

结果：
![image](https://user-images.githubusercontent.com/9022958/204693634-9eb9c43a-7239-441a-862e-0c5132bfee27.png)

**Comment by cuicheng01** [comment]
您好，fluid这块暂时是维护状态，您切换到2.2之后的paddlepaddle试下呢？
