### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle._C_ops'

### ISSUE THREAD

**Issue by liuyuemaicha** [PaddlePaddle/Paddle#48552]
### bug描述 Describe the Bug

调用“paddle._C_ops”错误

python3.7/site-packages/backports/configparser/__init__.py:130: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  from collections import MutableMapping
python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
Traceback (most recent call last):
  File "ppdet/modeling/ops.py", line 21, in <module>
    import paddle._legacy_C_ops as C_ops
ModuleNotFoundError: No module named 'paddle._legacy_C_ops'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "eval.py", line 31, in <module>
    from ppdet.core.workspace import load_config, merge_config
  File "ppdet/__init__.py", line 15, in <module>
    from . import (core, data, engine, modeling, model_zoo, optimizer, metrics,
  File "ppdet/data/__init__.py", line 16, in <module>
    from . import transform
  File "ppdet/data/transform/__init__.py", line 15, in <module>
    from . import operators
  File "ppdet/data/transform/operators.py", line 53, in <module>
    from ppdet.modeling.keypoint_utils import get_affine_transform, affine_transform
  File "ppdet/modeling/__init__.py", line 19, in <module>
    from . import ops
  File "ppdet/modeling/ops.py", line 23, in <module>
    import paddle._C_ops as C_ops
ModuleNotFoundError: No module named 'paddle._C_ops'

**Comment by cuicheng01** [comment]
你好，我这边不能复现这个问题，麻烦提供一下paddle版本号

**Comment by liuyuemaicha** [comment]
你好，我出错版本是2.0.1，是系统默认自带的。我升级到2.3.2就没问题了。谢谢
