### ISSUE TITLE
关于PaddleOCR 文字检测模型finetune的问题

### ISSUE THREAD

**Issue by ainndejj11** [PaddlePaddle/Paddle#48562]
### 请提出你的问题 Please ask your question

自己训练过了一个特定场景的文字检测的模型，效果也还不错，现在想继续优化该模型

1. 原先数据+新增数据，使用官方提供的预训练模型，finetune进行训练
2. 只使用新增数据，使用自己上一个训练的模型作为预训练模型进行finetune
3. 原先数据+新增数据，使用自己上一个训练的模型作为预训练模型进行finetune

请问：上面三种方法哪个对检测模型优化效果会更好些呢（由于数据量较大，没有时间逐一训练尝试比对）

**Comment by cuicheng01** [comment]
您好，关于PaddleOCR的问题建议在https://github.com/PaddlePaddle/PaddleOCR/issues 提问呢
