### ISSUE TITLE
nonzero 存在bug

### ISSUE THREAD

**Issue by zkyseu** [PaddlePaddle/Paddle#48587]
### bug描述 Describe the Bug

如图所示，所有参数均非None
![image](https://user-images.githubusercontent.com/118790294/204813841-a23705c4-c290-401a-aea0-10f4b225ac33.png)
![image](https://user-images.githubusercontent.com/118790294/204813988-6cb4d160-c6a3-4c4a-8a3b-74aa7c049362.png)
![image](https://user-images.githubusercontent.com/118790294/204814022-69fc132a-62cc-49de-9925-f4e6aae4f12b.png)

**Comment by cuicheng01** [comment]
您好，可以提供一个可最小复现的代码块吗？

**Comment by zkyseu** [comment]
> 您好，可以提供一个可最小复现的代码块吗？

我这边问题解决了，是我自己代码的问题，我将关闭这个issue，但是报错的地方就是CUDA error的地方不是在nonzero，但python提示是在这个地方报错，导致我花了较长时间。
