### ISSUE TITLE
在编译到eager_generator时出现的错误

### ISSUE THREAD

**Issue by TimeYWL** [PaddlePaddle/Paddle#48583]
### 请提出你的问题 Please ask your question

平台：rocm
cmake：cmake .. -DWITH_ROCM=ON -DWITH_MKL=ON -DWITH_DISTRIBUTE=ON _DWITH_BUILD_TYPE=Release
make

详细的错误内容：

[ 92%] Linking CXX executable eager_generator
[ 92%] Built target eager_generator
free(): invalid pointer
Subprocess aborted
paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/build.make:70: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen' failed
make[2]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen] Error 1
CMakeFiles/Makefile2:175296: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/all' failed
make[1]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

而 paddle/fluid/....../build.make:70 中的内容如下：
cd /home/ywl/paddle/build/paddle/fluid/eager/auto_code_generator && /snap/cmake/1204/bin/cmake -E env LD_LIBRARY_PATH=:~/paddle/build/paddle/fluid/eager/auto_code_generator/../../pybind:
~/paddle/build/third_party/install/mklml/lib ~/paddle/build/paddle/fluid/eager/auto_code_generator/eager_generator ~/paddle/paddle/fluid/eager/api/generated/fluid_generated 8

**Comment by cuicheng01** [comment]
您的问题已收到，请问编译过程中网络是畅通的吗？

**Comment by TimeYWL** [comment]
> 您的问题已收到，请问编译过程中网络是畅通的吗？

是畅通的

**Comment by TimeYWL** [comment]
在第二次编译中，又遇到如下错误：

/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start':
(.text+0x26): relocation truncated to fit: R_X86_64_GOTPCRELX against symbol `__libc_start_main@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o:(.eh_frame+0x20): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o: In function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
/usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/build.make:1116: recipe for target 'paddle/fluid/eager/auto_code_generator/eager_generator' failed
make[2]: *** [paddle/fluid/eager/auto_code_generator/eager_generator] Error 1
CMakeFiles/Makefile2:175007: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all' failed
make[1]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all] Error 2
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by cuicheng01** [comment]
您的环境可以说一下吗？

**Comment by luotao1** [comment]
@TimeYWL `R_X86_64_REX_GOTPCRELX against undefined symbol` 问题可以参考以下 issue
- https://github.com/PaddlePaddle/Paddle/issues/46966

**Comment by Aiga-Andrijanova** [comment]
> In the second compilation, the following error was encountered:
> 
> /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o: In function `_start': (.text+0x26): relocation truncated to fit: R_X86_64_GOTPCRELX against symbol `__libc_start_main@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6 /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/Scrt1.o:(.eh_frame+0x20): relocation truncated to fit: R_X86_64_PC32 against `.text' /usr/lib/gcc/x86_64-linux-gnu/7/../../../x86_64-linux-gnu/crti.o: In function `_init': (.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol ` **gmon_start **' /usr/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax collect2: error: ld returned 1 exit status paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/build.make:1116: recipe for target 'paddle/fluid/eager/auto_code_generator/eager_generator' failed make[2]: *** [paddle/fluid/eager/auto_code_generator/eager_generator] Error 1 CMakeFiles/Makefile2:175007: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all' failed make[1]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all] Error 2 Makefile:135: recipe for target 'all' failed make: *** [all] Error 2

How did you fix this?
