### ISSUE TITLE
请教：依赖冲突问题

### ISSUE THREAD

**Issue by DanceCorgi** [PaddlePaddle/Paddle#48597]
### 请提出你的问题 Please ask your question

请教：
我用paddle BML 的notebook类型想要复现别人github上的项目，安装项目的包时，发生依赖冲突怎么办？用pycharm在本地安装需要的包时没有报错依赖冲突，是和飞桨独有的包冲突了吗？
比如我这里，需要tqdm>=4.48.2，已有4.27.0版本
sahi 0.10.1 requires tqdm>=4.48.2, but you have tqdm 4.27.0 which is incompatible.
但是我安装了4.48.2版本后，另一个包又需要4.27.0版本
paddlefsl 1.0.0 requires tqdm~=4.27.0, but you have tqdm 4.48.2 which is incompatible.

**Comment by cxxly** [comment]
具体是哪两个包依赖的基础包出现冲突，比如a->(c<1.0), b->(c>2.0)，可以用[pipdeptree](https://pypi.python.org/pypi/pipdeptree)等工具分析；确定之后，升级对应包到最新版本，如升级a；如果升级后仍有冲突，可能确实是a的版本比较旧，向对应repo提issue修复

**Comment by DanceCorgi** [comment]
想要复现的项目是用的torch框架，项目的requirements.txt文件里是：seaborn  pyyaml  nvidia-ml-py3  tensorboardX
最开始运行!pip install -r requirements.txt报错是这样的：
sahi 0.10.1 requires tqdm>=4.48.2, but you have tqdm 4.27.0 which is incompatible.
parl 1.4.1 requires pyzmq==18.1.1, but you have pyzmq 23.2.1 which is incompatible.
parl 1.4.1 requires tensorboardX==1.8, but you have tensorboardx 2.5.1 which is incompatible.
paddlepaddle-gpu 2.3.2.post112 requires protobuf<=3.20.0,>=3.1.0, but you have protobuf 3.20.1 which is incompatible.
paddlefsl 1.0.0 requires numpy~=1.19.2, but you have numpy 1.21.6 which is incompatible.
paddlefsl 1.0.0 requires pillow==8.2.0, but you have pillow 9.3.0 which is incompatible.

我就想尝试升级tqdm到4.48.2试一下，但是：
paddlefsl 1.0.0 requires tqdm~=4.27.0, but you have tqdm 4.48.2 which is incompatible.

paddlefsl 1.0.0需要tqdm~=4.27.0，但是sahi 0.10.1需要tqdm>=4.48.2。

其实不只是这两个包，其他几个还没有尝试，是不是因为我还没有转换模型成paddle的问题，转换完之后是不是可能就好了
