### ISSUE TITLE
paddle保存模型的时候，支持子图保存吗？

### ISSUE THREAD

**Issue by welsonzhang** [PaddlePaddle/Paddle#48607]
### 请提出你的问题 Please ask your question

问题：
    我们在线预估的服务，会将dense和sparse部分进行切割， sparse部分的embeding lookup会放在特征抽取的环节实现。想问一下paddle在保存模型的时候，支持将dense部分的子图进行切割保存，并用于在线预估吗？

**Comment by cxxly** [comment]
目前还不支持
