### ISSUE TITLE
`paddle.transpose`op不是inplace操作，对高维tensor操作时非常消耗显存

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/Paddle#48601]
### 需求描述 Feature Description

进行模型复现时发现`tranpose`不是inplace op，会把显存占用给double了，当tensor较大的时候会非常耗费显存。而torch的`permute`操作是不会开辟新的存储空间的，这块transpose是否可以支持inplace操作呢？

### 替代实现 Alternatives

无

**Comment by cxxly** [comment]
收到需求了，这个我们评估下
