### ISSUE TITLE
0.10.0-dev & latest-dev docker镜像不能用

### ISSUE THREAD

**Issue by zxiaotian** [PaddlePaddle/Paddle#4861]
python代码报错：
λ b08d7138596f / python
Python 2.7.6 (default, Oct 26 2016, 20:30:19)
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```bash
import paddle.v2 as paddle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named paddle.v2
```

**Comment by typhoonzero** [comment]
您好。paddle的docker镜像分为develop镜像和production镜像，develop镜像仅包含paddle开发/编译所需环境，并不会预装paddle。tag已`-dev`结束的均为develop镜像。

详细内容请参考[官方文档](http://doc.paddlepaddle.org/develop/doc/getstarted/build_and_install/docker_install_en.html)。
