### ISSUE TITLE
[Dy2St] Dygraph to Static Unify API Behavior tracking issue

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle#48612]
## 项目说明

用于跟踪 Call-for-Contributions: [飞桨 API 动静行为统一](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/Dy2St/unify_api_behavior.md) 各个任务的计划和进度

## 成果总结（整体进展 7/7）
> 按 merge 的时间顺序，排名不分先后: @DrRyanHuang (6)、@Liyulingyue(1)

| 子任务 | 具体内容和完成时间|相关 PR | 作者 |
|-|-|-|-|
| 1. API 行为统一|  ✅ 1.1 paddle.vision.transform.RandomCrop 接口（2022-12-16） | #49057 | @DrRyanHuang |
|| ✅ 1.2 paddle.vision.transform.RandomHorizontalFlip 接口 | #49590 | @Liyulingyue |
|| ✅ 1.3 paddle.vision.transform.RandomResizedCrop 接口 | #49619 |  @DrRyanHuang |
|| ✅ 1.4 paddle.vision.transform.RandomRotation 接口（2022-12-20） | #49128 |  @DrRyanHuang |
|| ✅ 1.5 paddle.vision.transform.RandomVerticalFlip 接口 （2022-12-13） | #49024 | @DrRyanHuang |
|| ✅ 1.6 paddle.vision.transform.Resize 接口（2022-12-13） | #49024 #49008 | @Aurelius84 @DrRyanHuang |
|| ✅ 1.7 paddle.vision.transform.RandomErasing 接口 | #49617 | @DrRyanHuang |
|| 待发现和动态新增中.....，欢迎贡献 | | |

**Comment by luotao1** [comment]
小结：扩展`paddle.vision.transform`下7个API支持静态图的功能，提升API的动静行为统一的用户使用体验。
