### ISSUE TITLE
FatalError: `Process abort signal` is detected by the operating system.

### ISSUE THREAD

**Issue by DankoZhang** [PaddlePaddle/Paddle#48615]
### 请提出你的问题 Please ask your question

paddle和pytorch一起使用导致的吗？怎么解决呢？

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::platform::MKLDNNDeviceContextThreadLocals::Body::~Body()
1   paddle::platform::MKLDNNDeviceContext::ResetBlobMap(void*)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1669884209 (unix time) try "date -d @1669884209" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3ee000182ae) received by PID 98990 (TID 0x7fdddcb1d740) from PID 98990 ***]

Aborted (core dumped)

**Comment by ZYNORl** [comment]
应该是你的bach_size设置过大，导致显存吃力导致的。并请将bach_size设置为2的n次方，以免不必要的错误
