### ISSUE TITLE
飞桨官网教程无法正常显示（无法查看代码）

### ISSUE THREAD

**Issue by songbbgame** [PaddlePaddle/Paddle#48649]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/tutorials/projectdetail/3445243
我在三台电脑，使用edge，火狐，谷歌浏览器，均无法查看网站上的示例代码。示例代码是极其窄的一条线。只能看到输出。言外之意，当前的飞桨官网教程几乎无法使用。并且，我记得很久以前就是这样。

**Comment by wangna11BD** [comment]
已收到反馈，我们会尽快修复~

**Comment by qiceng** [comment]
已修复：https://www.paddlepaddle.org.cn/tutorials/projectdetail/3445243
