### ISSUE TITLE
attention weight如何输出？

### ISSUE THREAD

**Issue by Yipeng-Sun** [PaddlePaddle/Paddle#4865]
如题。

**Comment by lcy-seso** [comment]
请问是希望训练时候输出还是生成时候输出呢？

**Comment by Yipeng-Sun** [comment]
在paddle test中输出结果过程中，如何利用value_printer_evaluator实现`simple_attention`中attention weights

**Comment by lcy-seso** [comment]
是否会用到 beam search？还是固定beam size = 1 呢？

**Comment by Yipeng-Sun** [comment]
预测输出beam size = 1就可以

**Comment by Yipeng-Sun** [comment]
将'simple_attention'函数内的'attention_weight'变量进行输出，通过'printer = value_printer_evaluator(attention_weight)'打出来即可
