### ISSUE TITLE
可以只编译出paddle_inference.lib吗？

### ISSUE THREAD

**Issue by DevilcLo** [PaddlePaddle/Paddle#48689]
### 请提出你的问题 Please ask your question

想编译出只有paddle_inference.lib而没有paddle_inference.dll，也就是能做成静态链接库吗？怎么样做

**Comment by zrr1999** [comment]
好像目前Paddle社区就在做这方面的事情，应该需要把phi算子库独立之后才能单独生成inference的动态库
https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/decoupled_phi_from_fluid.md

**Comment by zhangjun** [comment]
> ### 请提出你的问题 Please ask your question
> 想编译出只有paddle_inference.lib而没有paddle_inference.dll，也就是能做成静态链接库吗？怎么样做

是不是paddle_inference.dll直接删掉就可以？

**Comment by engineer1109** [comment]
```
cmake ..
cmake --build . --target paddle_inference_shared -j16
```

**Comment by DevilcLo** [comment]
> 好像目前Paddle社区就在做这方面的事情，应该需要把phi算子库独立之后才能单独生成inference的动态库 https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/decoupled_phi_from_fluid.md

好的，感谢

**Comment by DevilcLo** [comment]
> ```
> cmake ..
> cmake --build . --target paddle_inference_shared -j16
> ```

这个不是应该生成动态链接库吗

**Comment by DevilcLo** [comment]
> > ### 请提出你的问题 Please ask your question
> > 想编译出只有paddle_inference.lib而没有paddle_inference.dll，也就是能做成静态链接库吗？怎么样做
> 
> 是不是paddle_inference.dll直接删掉就可以？

实际的执行代码就在dll里面，删了那就用不了了

**Comment by engineer1109** [comment]
> > ```
> > cmake ..
> > cmake --build . --target paddle_inference_shared -j16
> > ```
> 
> 这个不是应该生成动态链接库吗

那就是
cmake ..
cmake --build . --target paddle_inference -j16
