### ISSUE TITLE
cmake ERROR：“list sub-command REMOVE_DUPLICATES requires list to be present.”

### ISSUE THREAD

**Issue by moosewoler** [PaddlePaddle/Paddle#48711]
### 问题描述 Issue Description

在loongarch64上构建Paddle v2.3.2，cmake过程中出现“list sub-command REMOVE_DUPLICATES requires list to be present.”
经排查，在`cmake/phi.cmake`中的`kernel_library`函数中，某些target的`kernel_deps`为空，于是按下图修改，对`kernel_deps`的长度进行判断，问题解除。

![图片](https://user-images.githubusercontent.com/526821/205553921-76fdeeb1-c8a4-4119-8cd4-bf1fe337fa01.png)

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 0.0.0
Paddle With CUDA: False
OS: Loongnix GNU/Linux 20
Python version: 3.7.3
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None
****************************************

**Comment by chenwhql** [comment]
感谢反馈，我们修复一下

**Comment by chenwhql** [comment]
您好，这里的实现我们已经升级了，2.4已经不再使用kernel_library去注册kernel了，所以这里也没有这个问题了

**Comment by moosewoler** [comment]
> 您好，这里的实现我们已经升级了，2.4已经不再使用kernel_library去注册kernel了，所以这里也没有这个问题了

谢谢，顺便问一下，我发现目前repo里没有loongarch相关的支持代码，这部分支持工作有人在做吗？

**Comment by luotao1** [comment]
> 我发现目前repo里没有loongarch相关的支持代码，这部分支持工作有人在做吗？

@moosewoler 目前飞桨没有在支持loongarch64的工作，非常欢迎您帮忙贡献代码～

**Comment by cheungxi** [comment]
> > 我发现目前repo里没有loongarch相关的支持代码，这部分支持工作有人在做吗？
> 
> @moosewoler 目前飞桨没有在支持loongarch64的工作，非常欢迎您帮忙贡献代码～

2021年不就发文章说支持了吗？ https://www.paddlepaddle.org.cn/support/news?action=detail&id=2572

**Comment by luotao1** [comment]
@cheungxi 
1. 之前有适配，但是由于没有CI的机器，没有持续验证，飞桨和龙芯的软件栈都有升级，所以官网上提供的安装方式，现在会遇到问题。
2. 可以参考 这个2.4的文档试一下：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_loongson_cn.html
