### ISSUE TITLE
是否有考虑增加表面缺陷检测的框架

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle#48729]
### 需求描述 Feature Description

是否有考虑增加表面缺陷检测的框架
工业场景

### 替代实现 Alternatives
`https://github.com/openvinotoolkit/anomalib
`

**Comment by jerrywgz** [comment]
可以试下[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection) 我们在aistudio上也提供了一个pcb缺陷检测的[范例](https://aistudio.baidu.com/aistudio/projectdetail/4670836)

**Comment by monkeycc** [comment]
没用的
这个只是目标识别
只能识别 不一样的

比如 有个洞 完全没有了
和背景色一样

这个就检测不出来的

是指
`https://github.com/openvinotoolkit/anomalib
`
类似这样框架

**Comment by jerrywgz** [comment]
那可以参考https://github.com/ultranity/Anomaly.Paddle 这个repo

**Comment by monkeycc** [comment]
谢谢 我试试
