### ISSUE TITLE
如何使用动态 cuda runtime/driver library 编译 paddlepaddle

### ISSUE THREAD

**Issue by freeliuzc** [PaddlePaddle/Paddle#48738]
### 请提出你的问题 Please ask your question

飞桨框架默认使用静态链接编译主框架及 ops(使用 nv_library 函数)，因此 cuda 也使用的静态库。现在有个需求，需要使用 cudart.so 动态链接而不使用 libcudart.a，应该怎么做呢？  
目前已尝试将用到 cc_library / nv_library 的位置改成 SHARED 属性进行编译，但会由于框架内部的循环依赖报错，如下图所示：
<img width="933" alt="image" src="https://user-images.githubusercontent.com/23568094/205622061-89deed23-ee09-4f64-86a4-f3d875e1d778.png">

**Comment by Shixiaowei02** [comment]
您好，请试下 cmake 自带编译选项 -DCUDA_USE_STATIC_CUDA_RUNTIME=OFF 是否可以解决问题，谢谢
