### ISSUE TITLE
Build issue on ROCm 4.5.2: free(): invalid pointer

### ISSUE THREAD

**Issue by llseek** [PaddlePaddle/Paddle#48757]
### 问题描述 Issue Description

Steps to reproduce:

```
$ python3.8 -m pip install numpy protobuf patchelf
$ git clone -b release/2.4 https://github.com/PaddlePaddle/Paddle
$ mkdir build
$ cd build
$ cmake -DPY_VERSION=3.8 -DWITH_ROCM=ON -DWITH_NCCL=OFF -DWITH_RCCL=ON -DWITH_TESTING=ON -DCMAKE_HIP_ARCHITECTURES=any ..
$ make -j
```

Same issue as:

https://github.com/skarupke/flat_hash_map/issues/11
in paddle/utils/flat_hash_map.h

Possible solution:

https://github.com/smessmer/flat_hash_map/commit/a4be1e423d07d6646cfd5d0d95d51fc0cce5b2cd

### 版本&环境信息 Version & Environment Information

Paddle version: release/2.4
ROCm version: 4.5.2
Python version: 3.8

**Comment by Shixiaowei02** [comment]
您好，我们正在复现这个问题

**Comment by ronny1996** [comment]
paddle只支持rocm4.0.1 ，建议参考官方文档编译 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html#anzhuangfangshier-tongguoyuanmabianyianzhuang

**Comment by llseek** [comment]
请问 ROCm 4.5 和 之后的 5.0+ 有适配计划吗

**Comment by milliar2020** [comment]
hi,@ronny1996 :
基于CentOS7.6 + devtoolset7-gcc-7.3.1+rocm-4.5.2编译paddle v2.4.2是成功的，但是Ubuntu 18.04就不行，编译会报free(): invalid pointer错误。
