### ISSUE TITLE
memory optimize pass crashes on ppyoloe

### ISSUE THREAD

**Issue by sfraczek** [PaddlePaddle/Paddle#48750]
## Error description
I built paddle develop (SHA a0f4388946535070d8cde2f6dfbf17ef7bf61c4c) and run ppyoloe test and have a crash in memory_optimize_pass.
I tried this SHA and it worked: 93099bb8c3e112d1d102c3a4e16a97f24fc778d9

## Command
```shell
python3.9 test_ppyoloe_infer.py --model_path=models/ppyoloe_crn_l_300e_coco_quant --reader_config=configs/ppyoloe_reader.yml --device=CPU --use_mkldnn=True --cpu_threads=10 --precision=fp32
```
## Error message
![image](https://user-images.githubusercontent.com/17185347/205747162-f85fb78b-4691-48f1-b3dd-2ecd0c6c6adc.png)

**Comment by Shixiaowei02** [comment]
We are following up on this issue, thanks.

**Comment by jiweibo** [comment]
I found that `memory_optimize_pass` does not take effect when `mkldnn` and `memory_optimize_pass` are enabled at the same time, but I don't know why.

![image](https://user-images.githubusercontent.com/26377421/205855455-36bed285-b46b-432f-81af-0a4e14256ffc.png)

**Comment by jiweibo** [comment]
@sfraczek If I use `config.enable_mkldnn()`, can I enable memory_optimize? Is there a conflict between these two ways?

**Comment by jiweibo** [comment]
> @sfraczek If I use `config.enable_mkldnn()`, can I enable memory_optimize? Is there a conflict between these two ways?

I found the code, which cause the error. Do you know the background of this code? @sfraczek 

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/analysis_config.cc#L943

**Comment by sfraczek** [comment]
I only read the issue and PR threads but I don't know the background of this problem. I ran ppyoloe with your fix - reenabling this pass for mkldnn and it seems to work. It fixed ppyoloe problem. I'm waiting for some more int8 and bf16 tests.

**Comment by sfraczek** [comment]
I run into some problems with our validation. Sorry for the delay. I don't have the results yet.
