### ISSUE TITLE
paddle jit to_static  有没有可能会使精度降低

### ISSUE THREAD

**Issue by pogevip** [PaddlePaddle/Paddle#48755]
### 请提出你的问题 Please ask your question

paddle版本是2.3.1

用原模型和推理模型分别跑了一遍，打印了输入和输出，输入完全相同，输出在小数点4位以后不相同，导致精度不一致。、

想问一下，paddle jit to_static  有没有可能会使精度降低？

**Comment by Shixiaowei02** [comment]
您好，Paddle 有不同后端实现同一种计算，当使用 to_static 之后，可能会导致精度不同的问题，这可能是由于算子粒度变化 / 后端加速库等原因导致。

**Comment by pogevip** [comment]
> 

好的，谢谢。
