### ISSUE TITLE
win11+3090ti+cuda11.6无法训练和推理，pycharm显示进程已结束。

### ISSUE THREAD

**Issue by zhaop-l** [PaddlePaddle/Paddle#48760]
### 问题描述 Issue Description

新配置的环境，用的是官方实例的MNIST识别代码。
![image](https://user-images.githubusercontent.com/50993924/205808814-f4502b12-8b8f-4b88-ae9e-dde46f41ab76.png)

### 版本&环境信息 Version & Environment Information

不知道为啥，明明是win11，代码读的确实win10
****************************************
Paddle version: 2.4.0
Paddle With CUDA: True

OS: Windows 10
Python version: 3.9.15

CUDA version: 11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
cuDNN version: None.None.None
Nvidia driver version: 527.37
****************************************

**Comment by Shixiaowei02** [comment]
您好，请问能贴一下具体的报错信息吗，我们判断下是否和打开 Rocm 或者编译环境相关，谢谢！

**Comment by engineer1109** [comment]
崩了，换linux
