### ISSUE TITLE
torch中Tensor的属性data 对应paddle中Tensor中的哪一个类型。

### ISSUE THREAD

**Issue by Farewell-CK** [PaddlePaddle/Paddle#48814]
### bug描述 Describe the Bug

代码：g.cpu().data.numpy()
报错：AttributeError: 'Tensor' object has no attribute 'data'

**Comment by Shixiaowei02** [comment]
您好，paddle 中的 tensor.numpy() 可实现 torch 中转换为 numpy 数组的功能。谢谢
