### ISSUE TITLE
tensor A用tensor B的值当作index处理非常慢

### ISSUE THREAD

**Issue by yangzhao1230** [PaddlePaddle/Paddle#48822]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/52462696/206080829-02da3459-94a1-4c4b-a1de-398464ff345c.png)
mask是一个一维全零tensor，idx是一个记录着index的tensor，我想通过self.mask[idx] = True来讲mask中一部份值赋值成True，但这行简单的操作非常慢，大概要花上几分钟，我想知道这是什么原因，谢谢！

**Comment by yangzhao1230** [comment]
![image](https://user-images.githubusercontent.com/52462696/206081242-6350a784-a07a-41f8-bfb6-35b735c377bb.png)
mask和index的大小如图

**Comment by SunNy820828449** [comment]
谢谢，我们已经收到问题，反馈给相关负责的同学了。
