### ISSUE TITLE
静态图reshape，squeeze，unsqueeze会与原Tensor共享数据吗？

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#48832]
### 请提出你的问题 Please ask your question

请问，我在网络中需要对tensor做reshape, squeeze, unsqueeze这类仅改变shape的操作，静态图模式下（GPU训练）会发生tensor的拷贝吗？
Paddle文档中只说明了动态图模式下是共享输入的数据的。

**Comment by SunNy820828449** [comment]
会创建一个新的空间，动态图的支持inplace，你可以试试。

**Comment by Wong4j** [comment]
理论上这几个op不需要修改任何元素，也不改变存储方式，只是从不同的维度来看待这个tensor。
为什么静态图中这几个op不能实现成inplace呢？
