### ISSUE TITLE
公司同一IP出口，只能使用一台机器

### ISSUE THREAD

**Issue by lynnlynn01** [PaddlePaddle/Paddle#48830]
### 请提出你的问题 Please ask your question

公司同一IP出口，只能使用一台机器，如何解决？
![reliao_1670388715274](https://user-images.githubusercontent.com/119998286/206093069-4f53c9b1-1e23-4296-8aee-a74494ff06f5.jpeg)
卡在了运行

**Comment by lynnlynn01** [comment]
什么时候可以回复呀

**Comment by SunNy820828449** [comment]
这个问题不属于paddle的问题，这个应该是网络相关的，我们没法给你解决方案。

**Comment by lynnlynn01** [comment]
好的，感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年12月7日(周三) 晚上7:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 公司同一IP出口，只能使用一台机器 (Issue #48830)




 
这个问题不属于paddle的问题，这个应该是网络相关的，我们没法给你解决方案。
