### ISSUE TITLE
paddle need to release a new version 

### ISSUE THREAD

**Issue by tanzhongyibidu** [PaddlePaddle/Paddle#4885]
0.10.0 release  is long ago,
after it , there are many features added and API changes.
for example, support dataset convert for cloud user.
and mse_error has been renamed.

how about release a new version?

**Comment by Yancey1989** [comment]
Thanks for @tanzhongyibidu 's suggestion, to release a new version is necessary, maybe we could release a new version after finish a part of work of the code refactoring? @reyoung 
But before this, maybe you can use the latest image, such as:
`paddlepaddle/paddle` for the latest PaddlePaddle.
`paddlepaddle/paddlecloud-job` for the latest PaddleCloud Job.
