### ISSUE TITLE
paddle的稀疏矩阵是否支持矩阵乘法？

### ISSUE THREAD

**Issue by yangzhao1230** [PaddlePaddle/Paddle#48854]
### 请提出你的问题 Please ask your question

我尝试使用paddle的稀疏矩阵
![image](https://user-images.githubusercontent.com/52462696/206137054-53012281-ad71-43ca-a6f7-cabc55fed417.png)
但发现无法进行矩阵乘法，请问有什么解决方法吗？
![image](https://user-images.githubusercontent.com/52462696/206137245-33ba1edd-597b-4c22-ab29-52f5175490d2.png)

**Comment by SunNy820828449** [comment]
你好，我们已经收到问题，并且已经反馈给相关负责的同学，有结果会第一时间回复你。

**Comment by SunNy820828449** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/sparse/matmul_cn.html#matmul
你好参考这个API

**Comment by yangzhao1230** [comment]
@SunNy820828449 非常感谢您的回复。我看到文档中提到从cuda11.0开始支持，但我尝试使用稀疏乘法的反向传播时，发现需要cuda11.3
![image](https://user-images.githubusercontent.com/52462696/206356254-2578a323-c088-476d-960b-531ef04cafbd.png)

**Comment by yangzhao1230** [comment]
@SunNy820828449 还有我想请问现在提供实际应用sparse的完整paddle代码供参考吗？因为我看到文档中提到说已经应用到了Sparse Transformer等模型中，但我还没有找到相关供参考的代码。非常感谢！
![image](https://user-images.githubusercontent.com/52462696/206367276-8cec9c8c-3107-49c4-8eb2-d8951367e555.png)

**Comment by SunNy820828449** [comment]
https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/models/middle_encoders/sparse_resnet.py
