### ISSUE TITLE
pad算子的pad参数

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#48862]
### 请提出你的问题 Please ask your question

paddle version: 2.2.2
python version: 3.7

请问pad算子，当输入x的dims=4时，pad参数的长度可以为2吗？使用过程中发现这样会报错，复现代码如下：
```
import numpy as np
import paddle
import paddle.nn.functional as F

x_shape = (1, 1, 3, 4)
x = paddle.arange(np.prod(x_shape), dtype="float32").reshape(x_shape) + 1
y = F.pad(x, [1,1], value=1, mode='constant', data_format="NCHW")
print(y)
```
报错如下：
![image](https://user-images.githubusercontent.com/37332773/206180854-5eed1392-fb61-4ecf-8fed-6a7f1ef304ed.png)

**Comment by SunNy820828449** [comment]
请参考pad2d的文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Pad2D_cn.html

**Comment by peiwenYe** [comment]
> 请参考pad2d的文档，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Pad2D_cn.html

收到，看了一些其他的资料，看下来是pad算子的pad参数长度必须等于rank(x)*2或者(rank(x)-2)*2，是这样吧？
这里又遇到另一个问题，当pad输入tensor时，若已经指定pad的dtype为int64，仍然报错，复现代码如下：
```
import numpy as np
import paddle
import paddle.nn.functional as F

x_shape = (1, 1, 3, 4)
x = paddle.arange(np.prod(x_shape), dtype="float32").reshape(x_shape) + 1
pad = paddle.to_tensor([1, 2, 3, 4, 1, 1, 1, 1], dtype="int64")
y = F.pad(x, pad, value=-1, mode='constant', data_format="NCHW").numpy()
print(y)
```
报错如下：
![image](https://user-images.githubusercontent.com/37332773/206383504-7d977b18-f747-4644-9579-0ad348ec5c25.png)
