### ISSUE TITLE
根据官方文档，使用conda 在mac m1上面安装无法找到源。paddlepaddle是不支持m1吗？

### ISSUE THREAD

**Issue by charlesssssssssssssss** [PaddlePaddle/Paddle#48868]
### bug描述 Describe the Bug

(paddle_env) ➜  ~ conda install paddlepaddle==2.4.0 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - paddlepaddle==2.4.0

Current channels:

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/pytorch/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-arm64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

(paddle_env) ➜  ~ python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())"               
64bit
arm64

**Comment by SigureMo** [comment]
2.3.0 就已经原生支持 M1 了（#38379），使用 conda 创建环境后直接 pip 安装即可

```bash
pip install paddlepaddle==2.4.0
```
