### ISSUE TITLE
关于GPU版本的paddle的改进建议

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/Paddle#48874]
### 需求描述 Feature Description

最近使用docker容器启动模型训练的时候，对比pytorch的GPU版本依赖包，paddlepaddle仍旧需要独立安装相应的cuda和cudnn才能调用gpu加速训练和预测。而对pytorch来说，只要宿主机中安装了英伟达的显卡驱动，不要求安装cuda和cudnn，只要安装的是GPU版本的pytorch，即可自动调用GPU完成加速训练。这样对很多使用者来说，方便了很多，不必各种找相应的cuda版本安装。同时，用这种方式生成的带GPU加速的镜像大小只有3G+，而如果需要独立安装cuda和cudnn的话，镜像则要达到10G+了，差别还是比较大的。
如果可以的话，个人建议paddlepaddle也能和pytorch一样，将cuda和cudnn集成到whl的依赖包中，这样可能会方便很多。

**Comment by lmw0320** [comment]
另外，对于paddle判断cuda是否可用的情况方法：paddle.fluid.install_check.run_check()，如果不可用，是否可以返回False，而不是报错？ 
对pytorch，其方法torch.cuda.is_available()感觉就比较友好，返回是True或False，这样代码方便自动设置在CPU还是GPU上执行。。对paddle检测cuda不可用的情况下，报错的话，很影响使用体验。。

**Comment by lmw0320** [comment]
另外，对于paddle判断cuda是否可用的情况方法：paddle.fluid.install_check.run_check()，如果不可用，是否可以返回False，而不是报错？ 
对pytorch，其方法torch.cuda.is_available()感觉就比较友好，返回是True或False，这样代码方便自动设置在CPU还是GPU上执行。。对paddle检测cuda不可用的情况下，报错的话，很影响使用体验。。

**Comment by 2742195759** [comment]
好的，感谢给Paddle提出意见，我们会评估需求并有选择性的采纳。

**Comment by pangyoki** [comment]
你好，感谢你的建议，我们会考虑这个需求，看是否要将cuda和cudnn打入whl包，目前看打入whl包会导致whl体积增大，我们会进一步评估。
对于镜像问题，请问是哪个镜像太大了呢？镜像方面我们也可以考虑从其他角度缩小下体积。

**Comment by lmw0320** [comment]
> 你好，感谢你的建议，我们会考虑这个需求，看是否要将cuda和cudnn打入whl包，目前看打入whl包会导致whl体积增大，我们会进一步评估。 对于镜像问题，请问是哪个镜像太大了呢？镜像方面我们也可以考虑从其他角度缩小下体积。

只是相对而言，相同的GPU训练环境，如果是pytorch的话，宿主机只需要安装显卡驱动，不必安装cuda和cudnn。容器内也无需安装cuda和cudnn，只要安装gpu版本的pytorch，即可正常调用宿主机的显卡加速训练。
而目前是发现tf和paddle无法实现这种操作。需要额外安装独立的cuda和cudnn（要么是宿主机安装，启动容器时映射进去，要么是容器内自己安装cuda和cudnn）。这样相比较下，同样是gpu的训练环境，pytorch的docker镜像只要3G+就可以了，而paddle和tf基本都要10G+。
我对pytorch的情况不了解，个人是觉得应该是英伟达官方的cuda和cudnn中包含了比较完整的组件，而实际上对模型调用gpu来说，用不到那么多。所以pytorch只是将有用的部分直接打包到whl文件中，这样whl文件也不会显得非常大。

**Comment by jingsongliujing** [comment]
同建议希望能把镜像体积缩小，从官方拉下来的镜像体积最小也要10个G,对于需要内网训练来说确实挺痛苦的
