### ISSUE TITLE
run_check()时出现错误

### ISSUE THREAD

**Issue by TimeYWL** [PaddlePaddle/Paddle#48891]
### 请提出你的问题 Please ask your question

我在海光dcu上自己编译了paddle，但在运行run_check时，出现如下错误：

RuntimeError: (NotFound) Operator (share_buffer) does not have kernel for {data_type[float]; data_layout[Undefined(AnyLayout)]; place[Place(gpu:0)]; library_type[PLAIN]}.
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at ~/Paddle/paddle/fluid/framework/operator.cc:2019)
  [operator < share_buffer > error]

我在编译好paddle后，运行了两个模型都没有出现问题，但运行run_check却无法通过，不知道是什么原因导致的

**Comment by lifulll** [comment]
想问一下这个问题解决了吗，我也碰到这个问题了
