### ISSUE TITLE
ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted.

### ISSUE THREAD

**Issue by chen80** [PaddlePaddle/Paddle#48898]
### 请提出你的问题 Please ask your question

在使用单机多卡训练的过程，单卡没问题，多卡报错；
使用命令：python3 -m paddle.distributed.launch --selected_gpus='4,5'  train.py 
错误如下：
-----------  Configuration Arguments -----------
backend: auto
elastic_server: None
force: False
gpus: 4,5
heter_devices: 
heter_worker_num: None
heter_workers: 
host: None
http_port: None
ips: 127.0.0.1
job_id: None
log_dir: log
np: None
nproc_per_node: None
run_mode: None
scale: 0
server_num: None
servers: 
training_script: train.py
training_script_args: ['--batchSize', '8', '--dataRoot', '/dev/shm/train_datasets/images', '--net', 'idr', '--mode', 'l1', '--lr', '2e-4', '--lr_decay_iters', '350000', '--loadSize', '512', '--modelsSavePath', './ckpts/', '--logPath', 'logs']
worker_num: None
workers: 
------------------------------------------------
WARNING 2022-12-08 15:12:52,215 launch.py:423] Not found distinct arguments and compiled with cuda or xpu. Default use collective mode
launch train in GPU mode!
INFO 2022-12-08 15:12:52,215 launch_utils.py:641] Change selected_gpus into reletive values. --ips:4,5 will change into relative_ips:[0, 1] according to your CUDA_VISIBLE_DEVICES:['4', '5']
INFO 2022-12-08 15:12:52,216 launch_utils.py:528] Local start 2 processes. First process distributed environment info (Only For Debug):
+=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:46193               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:46193,127.0.0.1:52227       |
    |                     PADDLE_RANK_IN_NODE                        0                      |
    |                 PADDLE_LOCAL_DEVICE_IDS                        0                      |
    |                 PADDLE_WORLD_DEVICE_IDS                       0,1                     |
    |                     FLAGS_selected_gpus                        0                      |
    |             FLAGS_selected_accelerators                        0                      |
    +=======================================================================================+

INFO 2022-12-08 15:12:52,216 launch_utils.py:532] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
launch proc_id:335985 idx:0
launch proc_id:335992 idx:1
[12/08 15:12:53] idr INFO: Namespace(batchSize=8, dataRoot='/dev/shm/train_datasets/images', gamma=0.5, loadSize=512, logPath='logs', lr=0.0002, lr_decay_iters=350000, mode='l1', modelsSavePath='./ckpts/', net='idr', numOfWorkers=8, num_epochs=15, pretrained='', seed=2022)
server not ready, wait 3 sec to retry...
not ready endpoints:['127.0.0.1:52227']
I1208 15:12:56.935676 335985 nccl_context.cc:74] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W1208 15:12:57.337779 335985 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.0
W1208 15:12:57.340775 335985 device_context.cc:465] device: 0, cuDNN Version: 8.0.
[12/08 15:12:59] idr INFO: ========> Random Seed: 2022
============== 390656 4
==============>net use:  idr
OK!
/home/easyits/anaconda3/envs/paddlewater/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
Traceback (most recent call last):
  File "train.py", line 106, in <module>
    x_o1, x_o2, x_o3, fake_images, mm = netG(imgs)
  File "/home/easyits/anaconda3/envs/paddlewater/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/easyits/anaconda3/envs/paddlewater/lib/python3.7/site-packages/paddle/fluid/dygraph/parallel.py", line 708, in forward
    list(self._find_varbase(outputs)))
RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for this error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.
  [Hint: Expected groups_need_finalize_ == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:573)

INFO 2022-12-08 15:13:11,279 launch_utils.py:341] terminate all the procs
ERROR 2022-12-08 15:13:11,280 launch_utils.py:604] ABORT!!! Out of all 2 trainers, the trainer process with rank=[0, 1] was aborted. Please check its log.
INFO 2022-12-08 15:13:15,284 launch_utils.py:341] terminate all the procs
INFO 2022-12-08 15:13:15,284 launch.py:311] Local processes completed.

**Comment by 2742195759** [comment]
RuntimeError: (PreconditionNotMet) A serious error has occurred here. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, There may be several reasons for this error: 1) Please note that all forward outputs derived from the module parameters must participate in the calculation of losses and subsequent gradient calculations. If not, the wrapper will hang, waiting for autograd to generate gradients for these parameters. you can use detach or stop_gradient to make the unused parameters detached from the autograd graph. 2) Used multiple forwards and one backward. You may be able to wrap multiple forwards in a model.
[Hint: Expected groups_need_finalize == false, but received groups_need_finalize_:1 != false:0.] (at /paddle/paddle/fluid/imperative/reducer.cc:573)

请问有按照上述的 Error Hint 进行检查一下网络吗，比如设置 find_unused_parameters=True 等？

**Comment by chen80** [comment]
>
> 运行时错误：（前提条件未满足）此处发生严重错误。请设置 find_unused_parameters=True 以在每一步中向后遍历图，以便提前准备减少。如果已设置，则此错误可能有多种原因：1）请注意，从模块参数派生的所有前向输出都必须参与损耗的计算和随后的梯度计算。如果没有，包装器将挂起，等待自动grad为这些参数生成渐变。您可以使用分离或stop_gradient将未使用的参数与自动grad图形分离。2）使用多个向前和一个向后。您可以在一个模型中换行多个前向。 [提示：预期groups_need_finalize==假，但收到groups_need_finalize_：1！=假：0。（在 /paddle/paddle/fluid/imperative/reducer.cc：573）
> 
> 请问有按照上述的 Error Hint 进行检查一下网络吗，比如设置 find_unused_parameters=True 等？

是的，netG = paddle.DataParallel(netG,find_unused_parameters=True) 设置了，但是仍然报错。

**Comment by JZ-LIANG** [comment]
find_unused_parameters=True 大概率是 模型里使用了pylayer 或其他 autograd 重入的模块， 这种情况下的数据并行请参考：
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/DataParallel_cn.html#no_sync
