### ISSUE TITLE
Error: Can not import paddle core while this file exists: /home/jdy/anaconda3/envs/pytorch/lib/python3.7/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by jdyjjj** [PaddlePaddle/Paddle#48904]
### 请提出你的问题 Please ask your question

我是在linux服务器上运行的，之前还能正常运行，今天突然就有报错了，pip uninstall然后重新下载paddlepaddle也解决不了，看到网上的解决方案没有找到针对linux服务器的解决方法。
报错信息：
![image](https://user-images.githubusercontent.com/73057174/206392079-c70a8baf-f48e-42a5-bb7e-4379a6160f99.png)
libpaddle.so文件位置：
![image](https://user-images.githubusercontent.com/73057174/206392216-b08c411b-46d0-4833-9c92-f77f6e42dd9f.png)
linux服务器信息：
![image](https://user-images.githubusercontent.com/73057174/206392480-fae35ba2-c586-4b87-86e2-800f4b4158a7.png)

**Comment by 2742195759** [comment]
这边看是你的libpython3.7.so.1 找不到，麻烦检查一下这个文件是不是被误删除了。这个文件应该在你的Python3.7的环境下

**Comment by jdyjjj** [comment]
> 
请问是在这个路径下查找libpython3.7.so.1这个文件吗？我在这里确实没有找到，只有下图两个find到了，请问这样该怎么解决呀？
![image](https://user-images.githubusercontent.com/73057174/206408236-db314fda-5055-40f1-9273-0feff536c550.png)

**Comment by jdyjjj** [comment]
我在~/anaconda3/envs路径下找到了libpython3.7.so.1这个文件。import paddle失败这个问题我确实无法解决
![image](https://user-images.githubusercontent.com/73057174/206408976-2876195d-fcf0-4a4d-8ad8-f1b69848c4e1.png)

**Comment by 2742195759** [comment]
可以运行一下：whereis libpython3.7m.so.1.0 看下结果呢.
同时可以试下这样修改呢：export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:<添加你上面找到的libpython3.7m.so.1.0的文件夹前缀>。这样就可以找到这个library了，然后看看还会报错吗

**Comment by jdyjjj** [comment]
解决了，太感谢您啦
