### ISSUE TITLE
paddle 2.4.0 + cuda 11.6安装问题 Error: Can not import paddle core while this file exists: /envs/sparse/lib/python3.8/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by yangzhao1230** [PaddlePaddle/Paddle#48914]
### 请提出你的问题 Please ask your question

我本来是想使用paddle.sparse中的反向传播功能，原文档提到cuda 11.0就可以。
![image](https://user-images.githubusercontent.com/52462696/206416970-b2893887-1635-45be-8478-d9548abdf7ae.png)
但我在实际使用中遇到要求cuda 11.3
![image](https://user-images.githubusercontent.com/52462696/206417214-07f061b6-8869-4b71-b1ad-e7ec40a26a50.png)
于是我只能考虑安装目前支持的cuda 11.6，参考官网命令
![image](https://user-images.githubusercontent.com/52462696/206417316-78d28e43-2956-4c6e-b6dc-96b0d7afd6d4.png)
但是直接import paddle就报错了
![image](https://user-images.githubusercontent.com/52462696/206417396-4c848364-5e6e-4844-bc43-c352e641e0e4.png)
现在有两个方向可以解决我的问题：
1、我如何才能正常在现有版本使用sparse中的反向传播
2、为什么我安装cuda 11.6会有这个问题（我不清楚paddle安装的这个cuda版本指定和torch中的cudatoolkit有什么关系），按理说
![image](https://user-images.githubusercontent.com/52462696/206417815-69fcd99d-c8f8-4aaf-a661-20e323c2a1fd.png)
我应该能支持cuda 11.6？

非常感谢paddle团队的耐心解答，希望能继续得到你们的帮助！

**Comment by 2742195759** [comment]
麻烦确认一下机器中有几个cuda版本，有可能是搜索到了错误的cuda版本路径。因为这个确实的Symbol是11.3引入的，所以如果搜索到了11.6的话，应该是不会出现Symbol找不到的情况。具体可以运行类似下面命令搜索一下cuda版本：
![截屏2022-12-08 19 24 28](https://user-images.githubusercontent.com/16025309/206434809-6eb8ae43-24af-4cae-873e-bb6ea88ffe5e.png)
按照你的错误来看，你应该是链接到了11.0 的版本，而不是 11.6 的版本

**Comment by yangzhao1230** [comment]
@2742195759 感谢你的回答。我本地的cuda版本确实是11.0。但是比如对于pytorch，执行conda install pytorch torchvision cudatoolkit=11.6 -c pytorch，那么就会在conda环境内安装一个11.6的cuda运行api，在本地跑代码就是优先用这个11.6。但同样我在装paddle的时候也有相似的命令conda install paddlepaddle-gpu==2.4.0 cudatoolkit=11.6 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge ，按照我类比pytorch的想法，我运行代码应该就是默认是用这个cuda 11.6了。但好像最终结果是我安装了这个cudatoolkit=11.6，它还是去找我本地11.0的cuda吗？

**Comment by 2742195759** [comment]
目前来看好像是的，所以你可以通过修改 LD_LIBRARY_PATH 环境变量来优先搜索这个 cuda11.6。
