### ISSUE TITLE
paddle.topk 无法与torch.topk对齐

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#48925]
### 请提出你的问题 Please ask your question

```python
import paddle
import torch
import numpy as np

a = paddle.rand([1024])
res1,res2 = paddle.topk(a, 1000, sorted=False)
b = torch.from_numpy(a.numpy())
res11,res22 = torch.topk(b,1000, sorted=False)
diff = res1.numpy() - res11.cpu().detach().numpy()
diff = np.abs(diff)
print(diff.max())
#diff.max() = 0.65839833
```
当我把`sorted`参数设置为True时就是可以对齐的。

补充：看了paddle.topk API的介绍，在GPU上永远返回有序的结果，请问有什么方式可以解决这个问题吗（除了转为CPU）？

**Comment by 2742195759** [comment]
有序和无序也不影响返回的是TopK，请问为什么一定要保证返回值是有序的呢？只是为了与Torch对齐吗？还是有序会影响后续的模型？

**Comment by Li-fAngyU** [comment]
是的，有序和无序不影响返回的是TopK。目前是在复现模型，需要与Torch对齐。

使用场景：A，B为两个维度相同的Tensor且相互之间有联系，需要获取Tensor A的topk index，然后去获取Tensor B在该index下的对应值，进行后续处理。

`_, index = torch.topk(x, num, sorted= False)`实现了以上功能。

```python
# A, B 是维度一致的Tensor，eg. paddle.rand([1024,1])  or torch.rand(1024,1)

# torch 代码
_,index = A.topk(1000, sorted = False)
expect = B[index, :]

# paddle 代码 (gpu)
_,index = paddle.topk(A, 1000, sorted = False)
expect = paddle.gather(B, index, axis = 1)
```
因为有序和无序的情况下返回的index是不一样的，而`paddle.topk`在gpu下总是返回有序的结果。

**Comment by zhangyimi** [comment]
paddle2.4.2，这个bug还没修
