### ISSUE TITLE
我利用paddle的静态图实现一个简单的GCN，仅仅利用邻接矩阵×embedding矩阵，可是他告诉我，paddle.matmul 的参数均要初始化， 训练是可以进行的，但是推理不行

### ISSUE THREAD

**Issue by sanyu6** [PaddlePaddle/Paddle#48933]
### 请提出你的问题 Please ask your question

 InvalidArgumentError: The Tensor in the matmul_v2 Op's Input Variable X(text_a_adj) is not initialized.
      [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:2228)
      [operator < matmul_v2 > error]python-BaseException

**Comment by zyfncg** [comment]
你好，可以提供下运行的代码和复现步骤吗？
