### ISSUE TITLE
不知道paddleInference咋和opencv 配合

### ISSUE THREAD

**Issue by qinxue123321** [PaddlePaddle/Paddle#48941]
PreProcess(img,img);
	cvtColor(img,img,cv::COLOR_BGR2RGB);
	resize(img,img,Size(224,224));
	normalize(img, img, 0, 1);
	img = img.clone() - 0.5;
	//
	// 设置输入 Tensor 数据
	input_tensor->CopyFromCpu(img.data);
	// 执行推理
	predictor->Run()
	// 获取 Output Tensor
	auto output_names = predictor->GetOutputNames();

用示例的随机数据可以，但是opencv读入图片，最后获得输出的名字就报错

**Comment by b3602sss** [comment]
参考这个 https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/gpu/resnet50
