### ISSUE TITLE
关于在loongarch64上编译飞桨的讨论

### ISSUE THREAD

**Issue by moosewoler** [PaddlePaddle/Paddle#48944]
### 问题描述 Issue Description

分享我在loongarch64上构建Paddle v2.3.2的经验：
1、龙芯3A4000（含）以前用的是MIPS的变体，3A5000是loongarch（由于一些非技术的因素，无奈）。而loongarch在设计上与MIPS并不兼容，所以我新增了WITH_LOONGARCH条件选项。
1.1、增加WITH_LOONGARCH还有另外一层意图，我想试着增加axpy的支持，因loongarch也有向量指令。
2、要想顺利编译通过，需要开发者仔细阅读和分析cmake和代码结构。我用的是龙芯中科发布loongnix，其工具链有些功能是闭源的。据我所知，用户用uos、archlinux、gentoo的都有，这些系统的工具链缺少那些闭源的功能，我猜想这是造成龙芯环境难以编译通过的原因吧。另外，这也给爱好者们想自发为龙芯生态增加功能造成了阻碍。

附：
关于构建过程的记录见知乎[从源码编译飞桨（loongarch版）](https://zhuanlan.zhihu.com/p/589311248)
构建过程的视频记录见B站[龙芯3A5000构建飞桨全过程纯享版](https://www.bilibili.com/video/BV1844y1S7Sb/)

### 版本&环境信息 Version & Environment Information

Paddle version: 2.3.2
Paddle With CUDA: False
OS: Loongnix GNU/Linux 20
Python version: 3.7.3
CUDA version: None
cuDNN version: None.None.None
Nvidia driver version: None

**Comment by ZHUI** [comment]
可以提个pr支持一下？

**Comment by engineer1109** [comment]
你可以先提交到fork仓库里
