### ISSUE TITLE
docker启动错误

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Paddle#48950]
### 请提出你的问题 Please ask your question

docker启动registry.baidubce.com/paddlepaddle/paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0错误

docker: Error response from daemon: failed to create shim task: OCI runtime create failed: could not apply required modification to OCI specification: error modifying OCI spec: failed to locate NVIDIA Container Runtime Hook: pattern nvidia-container-runtime-hook not found: unknown.

**Comment by zyfncg** [comment]
可能是显卡驱动或者nvidia-docker安装存在问题，可以尝试重新安装
https://blog.csdn.net/alex_yangchuansheng/article/details/119224283
<img width="998" alt="image" src="https://user-images.githubusercontent.com/13048366/206644913-675b4bfe-e695-420a-a3c9-6b9e44380eb9.png">

**Comment by ZTurboX** [comment]
> 可能是显卡驱动或者nvidia-docker安装存在问题，可以尝试重新安装 https://blog.csdn.net/alex_yangchuansheng/article/details/119224283 <img alt="image" width="998" src="https://user-images.githubusercontent.com/13048366/206644913-675b4bfe-e695-420a-a3c9-6b9e44380eb9.png">

重新安装nvidia-docker吗

**Comment by ZTurboX** [comment]
> 可能是显卡驱动或者nvidia-docker安装存在问题，可以尝试重新安装 https://blog.csdn.net/alex_yangchuansheng/article/details/119224283 <img alt="image" width="998" src="https://user-images.githubusercontent.com/13048366/206644913-675b4bfe-e695-420a-a3c9-6b9e44380eb9.png">

nvidia-docker重新安装很多次了
测试运行“docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi”
报docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

**Comment by zyfncg** [comment]
> nvidia-docker重新安装很多次了 测试运行“docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi” 报docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].

这样的话看上去更像是显卡驱动的问题

**Comment by ZTurboX** [comment]
> 



> > nvidia-docker重新安装很多次了 测试运行“docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi” 报docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> 
> 这样的话看上去更像是显卡驱动的问题

宿主机的
![image](https://user-images.githubusercontent.com/5669444/206647943-e97365d7-5265-42f5-b2c0-ead7fb78fd12.png)

**Comment by zyfncg** [comment]
> 宿主机的 ![image](https://user-images.githubusercontent.com/5669444/206647943-e97365d7-5265-42f5-b2c0-ead7fb78fd12.png)

目前有docker容器可以成功使用这块GPU吗？如果都有问题的话可以重装驱动试一下，这类环境问题一般也很少有比重装更有效的办法了

**Comment by gouzil** [comment]
> > 
> 
> > > nvidia-docker重新安装很多次了 测试运行“docker run --rm --gpus all nvidia/cuda:10.2-base nvidia-smi” 报docker: Error response from daemon: could not select device driver "" with capabilities: [[gpu]].
> > 
> > 
> > 这样的话看上去更像是显卡驱动的问题
> 
> 宿主机的 ![image](https://user-images.githubusercontent.com/5669444/206647943-e97365d7-5265-42f5-b2c0-ead7fb78fd12.png)

需要注意 docker 的版本要大于19.03

可以参考一下 [linux docker install](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/docker/linux-docker.html) 这篇
