### ISSUE TITLE
upsample不支持高阶导数

### ISSUE THREAD

**Issue by crwsr124** [PaddlePaddle/Paddle#48988]
### bug描述 Describe the Bug

upsample不支持高阶导数，create_graph为true的时候报错：
RuntimeError: (NotFound) The Op nearest_interp_v2_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set `create_graph` to False.

**Comment by wjj19950828** [comment]
@crwsr124 麻烦提供一下复现脚本吧

**Comment by cxxly** [comment]
您好，这个需求背景是啥，能麻烦补充下吗

**Comment by crwsr124** [comment]
stylegan2里面进行梯度惩罚的时候需要对discriminator的输出求二阶导，并且retain_graph=true。paddle貌似很多算子都不支持二阶导，导致penalty = grad(intput, output, retain_graph=true) loss = loss + penalty这里的loss无法BP。

**Comment by cxxly** [comment]
是的，Paddle目前在做这个事，upsample可能得稍晚一些，支持了会通知您
