### ISSUE TITLE
m1pro 版本mac芯片 安装paddle2.4.1无法运行

### ISSUE THREAD

**Issue by violetweir** [PaddlePaddle/Paddle#48985]
### bug描述 Describe the Bug

这个是我装的2.3.2b版本的paddle可以正常import
<img width="686" alt="image" src="https://user-images.githubusercontent.com/78856426/206829320-ee3ac6e7-1789-4042-99a2-3c4e6b61b1d2.png">

而这个是我2.4.1的paddle iimport之后会卡十几秒然后就显示python进程崩溃了，可能是在转译的时候哪里出了问题
<img width="686" alt="image" src="https://user-images.githubusercontent.com/78856426/206829350-3a2fc62f-f497-417d-a4db-a521c8f47f6c.png">

希望能尽快解决

### 其他补充信息 Additional Supplementary Information

这个是我装的2.3.2b版本的paddle可以正常import
<img width="686" alt="image" src="https://user-images.githubusercontent.com/78856426/206829320-ee3ac6e7-1789-4042-99a2-3c4e6b61b1d2.png">

而这个是我2.4.1的paddle iimport之后会卡十几秒然后就显示python进程崩溃了，可能是在转译的时候哪里出了问题
<img width="686" alt="image" src="https://user-images.githubusercontent.com/78856426/206829350-3a2fc62f-f497-417d-a4db-a521c8f47f6c.png">

希望能尽快解决

**Comment by zhengqiwen1997** [comment]
你好，目前暂不支持在mac M1用conda安装2.4.1，建议用pip安装即可。

**Comment by violetweir** [comment]
pip也不行还是相同的问题

**Comment by zhengqiwen1997** [comment]
退出conda的虚拟环境了吗
