### ISSUE TITLE
paddle.autograd.grad报错 Tensor holds no memory

### ISSUE THREAD

**Issue by lunlu** [PaddlePaddle/Paddle#49015]
### 问题描述 Please describe your issue

self.model.eval()
outputs = self.model(X)
grad = paddle.autograd.grad(outputs, X, retain_graph=True, allow_unused=True)[0]
这种使用方式下，报错
RuntimeError: (PreconditionNotMet) Tensor holds no memory. Call Tensor::mutable_data firstly.
  [Hint: holder_ should not be null.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:46)

请问是为什么？Tensor holds no memory.具体是什么含义？

我发现只要模型里面包括了与LSTM有关的算子都会报错，与LSTM无关能正常求取梯度，为什么？

**Comment by linjieccc** [comment]
@lunlu Hi，麻烦提供下paddle版本信息以及最小复现代码

**Comment by lunlu** [comment]
paddle版本：2.3.0
代码如下

import paddle
class LstmModel(paddle.nn.Layer):
    """
    """

    def __init__(self, **kwargs):
        super(LstmModel, self).__init__()
        self.lstm = paddle.nn.LSTM(1, 1)

    def forward(self, x):
        output = self.lstm(x)[0]
        return output

model = LstmModel()
model.eval()

input_ = paddle.rand((1, 24, 1))
input_.stop_gradient = False
output = model(input_)

paddle.autograd.grad(output, input_, retain_graph=True, allow_unused=True)[0]

运行该代码报错上面的信息

**Comment by lunlu** [comment]
hi，有在测试解决吗？

**Comment by joey12300** [comment]
@lunlu 您好，我这边使用2.4.0可以正常跑，要不你试试安装最新版本的paddle？

**Comment by lunlu** [comment]
您的python版本是？

**Comment by lunlu** [comment]
我试了试，2.4.0也不行

**Comment by lunlu** [comment]
py3.7 py3.6使用paddle=2.4.0报错ImportError: libpython3.6m.so.1.0: cannot open shared object file: No such file or directory这种错误

**Comment by linjieccc** [comment]
@lunlu 推荐用conda+python 3.7以上版本进行安装

**Comment by yangyuke001** [comment]
这个问题不是很好复现，一般都是偶尔才会出现的，不是每次推理都会出现。我用最新的paddle还是会出现这个问题

**Comment by yangyuke001** [comment]
> 这个问题不是很好复现，一般都是偶尔才会出现的，不是每次推理都会出现。我用最新的paddle还是会出现这个问题

是多线程没加锁导致的资源被抢占，加了锁就没这个问题了
