### ISSUE TITLE
官方提供的bert_base_uncased模型的输出的含义以及具体的下游任务是什么？

### ISSUE THREAD

**Issue by chenqion** [PaddlePaddle/Paddle#49038]
### 请提出你的问题 Please ask your question

模型链接https://paddlelite-demo.bj.bcebos.com/NNAdapter/models/PaddleNLP/bert_base_uncased.tgz
我的输入是一句话“this day is a good day”
模型的输出是：0.042511  -0.256104， 请问怎么理解这个输出呢？

**Comment by LiuChiachi** [comment]
输出shape是[None, 2]，None代表batch_size，现在应该是1；2代表该任务是2分类。0.042511 -0.256104分别对应着2个类的logits，第0个类的概率比第1个类的概率高。

顺便问一下，这个模型是在哪个页面下载的呢？

**Comment by chenqion** [comment]
感谢您的回复！
模型是在这个页面上下载的https://www.paddlepaddle.org.cn/lite/develop/demo_guides/huawei_ascend_npu.html
在模型库上也找到了该模型https://www.paddlepaddle.org.cn/modelsDetail?modelId=88， 看文档的描述该模型的下游任务是一个槽位填充。。。
我还有几个问题：
如果我的输入只有一句话，那token_type_ids是全0吗？
这个二分类就是一个积极情感和消极情感的分类吗？
我刚刚重新跑了一遍模型， 输入为“i feel so bad”,  输出结果是0.0614  -0.2247， 
换了好几个输入，输出的结果都是只能分到第一类中，这种情况我应该怎么定位问题呢

**Comment by LiuChiachi** [comment]
lite 和 模型库是2个单独的产品了，lite上的例子是某个分类任务上的demo，模型库是模型简要介绍，不需要把2个模型对应起来。
主要是看你需要解决的问题是什么。
模型预测之前需要训练，不能直接使用下载的模型，demo只是个示例模型不能直接用在你的任务上。所以你会发现你的模型不work，所以也就不需要定位问题只需要重训就可以。

token_type_ids还包括cls token和sep token，token_type_ids可以通过调用paddlenlp的tokenizer得到。[paddlenlp](https://github.com/PaddlePaddle/PaddleNLP)里面有很多文本分类的例子可以参考[链接](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/sentiment_analysis)。

有 PaddleNLP 相关问题可以在 PaddleNLP 继续提 issue 讨论。

月底 PaddleNLP 会开源出 ERNIE 模型在lite上的推理示例（意图识别和槽位填充任务）。

**Comment by chenqion** [comment]
感谢感谢，明白了

**Comment by chenqion** [comment]
关于token type ids , 可以给我举个例子吗？
比如cls token、sep token对应的值是多少？
想透彻理解一下输入，麻烦您再帮我回答一下

**Comment by LiuChiachi** [comment]
这个相关的paper都会有解释，或者调用API 都是可以的:)
