### ISSUE TITLE
关于DygraphExecutionContext中Attrs接口的语义的疑问

### ISSUE THREAD

**Issue by phjbest** [PaddlePaddle/Paddle#49063]
### 请提出你的问题 Please ask your question

你好，我在调用paddle/fluid/imperative/execution_context.h 中 DygraphExecutionContext 中的 const framework::AttributeMap& Attrs()接口时，发现返回的attrs不是完整
通过阅读源码发现该class存在两个存储attr的成员变量：const framework::AttributeMap& attrs_; const framework::AttributeMap& default_attrs_; ，当调用GetAttr 或HasAttr是，会在attrs_和default_attrs_中查找，相当于attrs_和default_attrs_是一个全集，而调用Attrs()接口仅返回attrs_，从Attrs()的语义上看，这是一个全集，但返回的attrs_确实一个子集，请问这里是出于什么考量呢，是否属于bug，如果不属于BUG，是否有其他方式可以获取到全集呢

**Comment by an1018** [comment]
收到，我们看一下

**Comment by wanghuancoder** [comment]
const framework::AttributeMap& Attrs()这个接口，返回的是上层python用户调用时，传入的attrs。
通常1个算子有多个attr，而且有默认值。用户可以不传或者只传部分attr的值，剩余的使用默认值。
所以，default_attrs_里是全量的默认值。attrs_里是用户提供的部分attr的值。
暂时这个类没有对外开放获取到获取到全集的方法。
