### ISSUE TITLE
Build for mac os on m1

### ISSUE THREAD

**Issue by grinay** [PaddlePaddle/Paddle#49076]
### 问题描述 Issue Description

Hello, let me describe the issue I faces. 
I'm trying to build "paddle inference c" library, we are using it in our OCR solution based on dotnet core. 
We are using OpenCvSharp4 and custom wrapper for paddle inference c library. There are no problem to use it on windows and linux. 
I'm trying to make it work on osx with m1 processors. 
I'm using building flags:

```
cmake ..  -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DWITH_SYSTEM_BLAS=ON -DCMAKE_BUILD_TYPE=Release -DWITH_INFERENCE_API_TEST=OFF -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_GPU=OFF -DWITH_AVX=OFF -DAPPLE=ON -DWITH_ARM=ON
make TARGET=ARMV8 -j4
```

as a result I have libpaddle_inference_c.dylib
But when I trying to use it in a project it throws the error:

```
ERROR: flag 'flagfile' was defined more than once (in files '/Users/grinay/paddleinference/Paddle/build/third_party/gflags/src/extern_gflags/src/gflags.cc' and '/tmp/gflags-20211021-3963-1mi18ai/gflags-2.2.2/src/gflags.cc').
```

I think the problem is that OpenCv4.6 uses gflags as well, When you install it with brew install opencv@4 it installs gflags 2.2 as well. 

When you build paddle I see it checkout git repository of gflags and build its own version. 
May you advice how to overcome this issue and make that work ?

### 版本&环境信息 Version & Environment Information

Macos 12.4 Monterey
Python 3.10.8
No GPU
CPU m1
Paddle last develop branch

**Comment by RichardWooSJTU** [comment]
> I think the problem is that OpenCv4.6 uses gflags as well

You can try to uninstall opencv and glog, and then reinstall opencv from the source code

**Comment by grinay** [comment]
I’ve tried that already, didn’t help.
May be there is a way to link existing gflags setup into the building process?

**Comment by grinay** [comment]
@RichardWooSJTU any advice?

**Comment by grinay** [comment]
Modified cmake files to reference existing gflags installation. Solved.

**Comment by wbudd** [comment]
@grinay 
May I ask you to share the details of how you modified those CMake files? 🙏

I'm trying to reproduce the way you built for M1 (also using the same CMake flags as you), but I'm running into issues including gfortran not being found and other annoyances.

**Comment by May-Yaha** [comment]
> @grinay May I ask you to share the details of how you modified those CMake files? 🙏
> 
> I'm trying to reproduce the way you built for M1 (also using the same CMake flags as you), but I'm running into issues including gfortran not being found and other annoyances.

https://github.com/PaddlePaddle/Paddle/pull/50787

**Comment by ltto** [comment]
@grinay  Can you share your. whl

**Comment by grinay** [comment]
@ltto @May-Yaha @wbudd   sorry for long answer, please check diff file, branch is develop at head of d4f43ad4ced51f9eb4979172d6a4be80090ac530
[diff_output.txt](https://github.com/PaddlePaddle/Paddle/files/10981453/diff_output.txt)
