### ISSUE TITLE
paddle.tensor.layer_function_generator錯誤

### ISSUE THREAD

**Issue by JimmyLyods** [PaddlePaddle/Paddle#49089]
您好,我再執行
import paddle
paddle.utils.run_check()

出現錯誤
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_13228/1711838367.py in <module>
----> 1 import paddle
      2 paddle.utils.run_check()

C:\ProgramData\Anaconda3\lib\site-packages\paddle\__init__.py in <module>
     26 from .framework import monkey_patch_math_varbase
     27 
---> 28 monkey_patch_variable()
     29 monkey_patch_math_varbase()
     30 

C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\layers\math_op_patch.py in monkey_patch_variable()
    530             setattr(Variable, method_name, method_impl)
    531     else:
--> 532         import paddle.tensor
    533         for method_name in paddle.tensor.tensor_method_func:
    534             if hasattr(Variable, method_name): continue

C:\ProgramData\Anaconda3\lib\site-packages\paddle\tensor\__init__.py in <module>
     20 from .attribute import imag  # noqa: F401
     21 from .attribute import is_floating_point  # noqa: F401
---> 22 from .creation import to_tensor  # noqa: F401
     23 from .creation import diag  # noqa: F401
     24 from .creation import diagflat  # noqa: F401

C:\ProgramData\Anaconda3\lib\site-packages\paddle\tensor\creation.py in <module>
     15 from __future__ import print_function
     16 import numpy as np
---> 17 from paddle.common_ops_import import fill_constant
     18 from ..fluid.layers import utils
     19 

C:\ProgramData\Anaconda3\lib\site-packages\paddle\common_ops_import.py in <module>
     23 from paddle.fluid.data_feeder import check_type, check_dtype, check_variable_and_dtype, convert_dtype
     24 from paddle.fluid.layers import fill_constant, utils, scale
---> 25 from paddle.tensor.layer_function_generator import templatedoc
     26 import paddle.fluid as fluid
     27 import numpy

ModuleNotFoundError: No module named 'paddle.tensor.layer_function_generator'

我把paddlepaddle移除又重新安裝好多次都沒辦法排除,
不知道要怎麼排除此問題

**Comment by yt605155624** [comment]
请根据官网文档，安装最新版或者develop版本 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/compile/linux-compile.html

**Comment by JimmyLyods** [comment]
感謝 已經排除了
我這邊做法是
先移除
python -m pip uninstall paddlepaddle
再重新安裝
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/windows/cpu-mkl-avx/develop.html
但出現存取錯誤 所以我重新開機後,
先到C:\ProgramData\Anaconda3\Lib\site-packages把paddle的資料夾刪除,
再重新安裝
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/windows/cpu-mkl-avx/develop.html
就正常了,執行
import paddle
paddle.utils.run_check()
已經出現
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
