### ISSUE TITLE
关于reduce_sum这个op，在代码不同位置的逻辑不太一样。paddle版本:2.2.2

### ISSUE THREAD

**Issue by yz-tang** [PaddlePaddle/Paddle#49098]
### bug描述 Describe the Bug

在paddle.sum和paddle.linalg.norm这两个API里都用到了reduce_sum这个OP，但这个OP的reduce_all属性的决定策略却不一样。详细见下面两个位置:   
在python/paddle/tensor/linalg.py:[372行](https://github.com/PaddlePaddle/Paddle/blob/v2.2.2/python/paddle/tensor/linalg.py#:~:text=%27reduce_all%27%3A%20True%20if%20axis%20is%20None%20else%20False)  
![image](https://user-images.githubusercontent.com/62792991/207797007-ee187c12-4970-40d5-86b5-4a0ee42367e2.png)

在python/paddle/tensor/math.py:[720-726行](https://github.com/PaddlePaddle/Paddle/blob/v2.2.2/python/paddle/tensor/math.py#:~:text=%5Baxis%5D-,if%20not%20axis%3A,reduce_all_flag%20%3D%20False,-def%20get_dtype()
![image](https://user-images.githubusercontent.com/62792991/207797557-d26d6904-1777-4d3d-bd7b-c1ae81f4709e.png)

**Comment by yt605155624** [comment]
请看看最新版 or develop 是否存在这个问题

**Comment by yz-tang** [comment]
新版本一样的问题。我再重复一遍我的问题:在paddle.sum和paddle.linalg.norm这两个API里都用到了reduce_sum这个OP，但这个OP的reduce_all属性的决定策略却不一样

在paddle.linalg.norm里关于reduce_sum的reduce_all仅仅取决于axis是否为空，但是在paddle.sum里关于reduce_sum的reduce_all不仅和axis是否为空有关，还和len(axis) == len(x.shape)有关。

这两个地方为什么没有对齐？还是出于别的原因的考虑？

**Comment by yt605155624** [comment]
你认为为什么这两个地方一定要对齐？你建议的策略是什么？
