### ISSUE TITLE
Paddle Inference连续推理有小概率遇到输出与输入不匹配

### ISSUE THREAD

**Issue by jaysontree** [PaddlePaddle/Paddle#49102]
### 请提出你的问题 Please ask your question

Hi，你好~

在使用PaddleInference大量推理时遇到了偶发性的输出与输入维度不一致的情况导致后续程序错误、定位到predictor.run返回的结果与输入不一致。需要您的帮助！

Paddle版本 2.3.0

代码块如下：
`class SegPredictor:

    _defaults = {
        'model_dir': './models/seg/',
        'sauvola_size': 7
    }

    def __init__(self, **kwargs):
        self.__dict__.update(self._defaults)  # set up default values
        self.__dict__.update(kwargs)  # and update with user overrides
        self._init_model()

    def _init_model(self):
        self.model_dir = Path(self.model_dir)

        # init base config
        self.pred_cfg = PredictConfig(
            str(self.model_dir.joinpath('model.pdmodel')),
            str(self.model_dir.joinpath('model.pdiparams')),
        )
        self.pred_cfg.disable_glog_info()
        self.pred_cfg.enable_memory_optim()
        self.pred_cfg.switch_ir_optim(True)

        # use cpu
        """
        # mkldnn 有连续重复图片请求会报错的问题，无法解决。暂时使用GPU推理。 ref: https://github.com/PaddlePaddle/PaddleOCR/issues/3313
        self.pred_cfg.disable_gpu()
        self.pred_cfg.set_mkldnn_cache_capacity(self.mkldnn_cache_capacity)
        self.pred_cfg.enable_mkldnn()
        self.pred_cfg.set_cpu_math_library_num_threads(self.cpu_threads)
        """
        # use gpu
        self.pred_cfg.enable_use_gpu(5000,0)

        # init predictor
        self.model = create_predictor(self.pred_cfg)
        self.input_handle = self.model.get_input_handle(self.model.get_input_names()[0])
        self.output_handle = self.model.get_output_handle(self.model.get_output_names()[0])

    def preprocess(self, img):
        img = _binarization(img, self.sauvola_size)
        img = _normalize(img)
        img = np.transpose(img, (2, 0, 1))
        img = img.astype(np.float32, copy=False)
        return img[np.newaxis, :]

    def inference(self, inputs):
        self.input_handle.reshape(inputs.shape)
        self.input_handle.copy_from_cpu(inputs)
        self.model.run()
        outputs = self.output_handle.copy_to_cpu()
        print(inputs.shape, outputs.shape)
        return outputs

    def __call__(self, img):
        inputs = self.preprocess(img)
        print('input: ', inputs.shape)
        model_outputs = self.inference(inputs)[0]
        print('input: ', img.shape, 'mask: ', model_outputs.shape)
        return model_outputs
`

模型正常输入 (1， h0，w0,  c）  -> 输出 (1, h0, w0)的数组
创建实例后，大量调用下，有概率遇到输入和输出维度不一致的情况，如下：
`
...
input:  (1, 3, 93, 257)

input:  (1, 3, 156, 295) 

(1, 3, 93, 257) (1, 156, 295)

input:  (93, 257, 3) mask:  (156, 295) 

(1, 3, 156, 295) (1, 156, 295)

input:  (156, 295, 3) mask:  (156, 295)
...
`
请问这种情况的原因是什么？除了添加容错，能否从根源上解决呢？

**Comment by ccrrong** [comment]
你好，麻烦提供一下可复现的测试用例

**Comment by jaysontree** [comment]
> 你好，麻烦提供一下可复现的测试用例

不好意思突然阳了没有及时回复您...

我想请问一下Paddle Inference本身不是线程安全的，是吗？不可以多线程调用推理？

我是在框架部署服务的时候遇到的，同样的数据量单纯顺序做推理的话没有遇到这个问题的。我重构了一下代码加了容错机制减小这种情况的影响。非常感谢，暂时不花更多时间研究原因了。

谢谢！

**Comment by jaysontree** [comment]
谢谢！估计是多线程的问题。不再追究原因了。我close issue了
