### ISSUE TITLE
海光DCU运行centernet_mobilenetv3_small模型报错

### ISSUE THREAD

**Issue by markluofd** [PaddlePaddle/Paddle#49110]
### 请提出你的问题 Please ask your question

编译的paddle rocm版本在海光Z100机器运行 centernet_mobilenetv3_large 模型会hang住，hang住前有一条报错信息：
hsaQueueDispatchCallBack: resultStatus=41, lastHipError=719, internalErrorID=131336
请问能根据报错信息知道具体可能的原因吗？
![23fd9ab90bbce63d0a13b8189cbc0d2f](https://user-images.githubusercontent.com/94596925/208035055-4287ec99-e9b0-4f40-b37b-810fe7bd6fff.png)

**Comment by w5688414** [comment]
> ### 请提出你的问题 Please ask your question
> 编译的paddle rocm版本在海光Z100机器运行 centernet_mobilenetv3_large 模型会hang住，hang住前有一条报错信息： hsaQueueDispatchCallBack: resultStatus=41, lastHipError=719, internalErrorID=131336 请问能根据报错信息知道具体可能的原因吗？ ![23fd9ab90bbce63d0a13b8189cbc0d2f](https://user-images.githubusercontent.com/94596925/208035055-4287ec99-e9b0-4f40-b37b-810fe7bd6fff.png)

请问您使用的是哪个套件？

**Comment by chenzhijun45** [comment]
> ### 请提出你的问题 Please ask your question
> 编译的paddle rocm版本在海光Z100机器运行 centernet_mobilenetv3_large 模型会hang住，hang住前有一条报错信息： hsaQueueDispatchCallBack: resultStatus=41, lastHipError=719, internalErrorID=131336 请问能根据报错信息知道具体可能的原因吗？ ![23fd9ab90bbce63d0a13b8189cbc0d2f](https://user-images.githubusercontent.com/94596925/208035055-4287ec99-e9b0-4f40-b37b-810fe7bd6fff.png)

您好，请问您的安装环境是什么呢？
我这边是 ubuntu20.04 + 海光DCU Z100 + DTK 22.04，安装 Paddle 后运行异常。
详见：https://github.com/PaddlePaddle/Paddle/issues/52732
