### ISSUE TITLE
paddlepaddle-gpu 2.3.2 paddle.utils.run_check() error: Invalid enum backend type `64`.

### ISSUE THREAD

**Issue by pigwing** [PaddlePaddle/Paddle#49133]
### bug描述 Describe the Bug

paddlepaddle-gpu 2.3.2安装后无法运行测试通过
```python
import paddle
paddle.utils.run_check()
```
详细报错如下.请问是操作系统的问题吗?
![image](https://user-images.githubusercontent.com/8393545/208228352-263c2762-ebde-4740-983a-e4253e8742c6.png)

**Comment by 1649759610** [comment]
您好，可以详细描述一下你的运行环境吗，比如操作系统，是否是gpu环境，gpu型号，paddle版本等信息

**Comment by pigwing** [comment]
操作系统是win10
![Snipaste_2022-12-20_16-04-26](https://user-images.githubusercontent.com/8393545/208615368-a0bd4829-8ee5-46c0-be12-dc4f1dfdc3af.png)

GPU的环境试下,还有CUDA
![Snipaste_2022-12-20_16-05-24](https://user-images.githubusercontent.com/8393545/208615448-d70280ce-0645-4e0c-983f-0328d94ef36d.png)
paddlepaddle2.3.2的版本
Python3.9

**Comment by 1649759610** [comment]
当前cuda12还没支持，可以尝试用低版本的cuda

**Comment by qq401834804** [comment]
> 当前cuda12还没支持，可以尝试用低版本的cuda

我也遇到了这个问题

![image](https://user-images.githubusercontent.com/17737568/208999952-310b00f6-cd93-4023-81ff-eeed50ebe616.png)
这里的CUDA版本说的最大支持的吧不是当前安装的吧

**Comment by qq401834804** [comment]
换2.2版本没这个问题了，paddlepaddle-gpu==2.2.2

**Comment by 1649759610** [comment]
不是当前安装的，当前暂不支持CUDA12。
换成2.2没有问题了，您的CUDA版本是多少呢？ @qq401834804

**Comment by pigwing** [comment]
@1649759610 我安装的cuda tool kit是11.6版本的呢,也黏贴了cudnn进去.按理来说,paddle不应该是调用cuda tool kit上面的cuda的吗?

**Comment by qq401834804** [comment]
> 

我按paddlepaddle.org.cn首页推荐装的，CUDA10.2，cuDNN装了7.6.5和8.7.0两个（之前遇到过问题少东西，就把两个都贴进去了）

**Comment by qq401834804** [comment]
> 不是当前安装的，当前暂不支持CUDA12。 换成2.2没有问题了，您的CUDA版本是多少呢？ @qq401834804

CUDA10.2，不过现在有了新问题，评估的时候报错，搞了一天也没解决，打算换Ubuntu试试，反正Windows上显卡跑不满，据说num_workers参数在Windows上没用，试试Linux效果如何

如果知道这个报错怎么解决也请指教，报错信息如下：
[2022/12/22 06:28:53] ppocr INFO: epoch: [6/500], global_step: 400, lr: 0.001000, loss: 0.965219, loss_shrink_maps: 0.382801, loss_threshold_maps: 0.507956, loss_binary_maps: 0.076599, avg_reader_cost: 1.58958 s, avg_batch_cost: 1.78
802 s, avg_samples: 10.0, ips: 5.59278 samples/s, eta: 17:09:05
eval model::   0%|                                                                                                                                                                                               | 0/30 [00:00<?, ?it/s]E
xception in thread Thread-10:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 980, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python39\lib\threading.py", line 917, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\paddle\fluid\dataloader\dataloader_iter.py", line 212, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices,
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\paddle\fluid\dataloader\fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in default_collate_fn
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\paddle\fluid\dataloader\collate.py", line 77, in <listcomp>
    return [default_collate_fn(fields) for fields in zip(*batch)]
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\paddle\fluid\dataloader\collate.py", line 58, in default_collate_fn
    batch = np.stack(batch, axis=0)
  File "<__array_function__ internals>", line 5, in stack
  File "C:\Users\40183\.virtualenvs\paddle-ocr\lib\site-packages\numpy\core\shape_base.py", line 427, in stack
    raise ValueError('all input arrays must have the same shape')
ValueError: all input arrays must have the same shape

**Comment by qq401834804** [comment]
> > 不是当前安装的，当前暂不支持CUDA12。 换成2.2没有问题了，您的CUDA版本是多少呢？ @qq401834804
> 
> CUDA10.2，不过现在有了新问题，评估的时候报错，搞了一天也没解决，打算换Ubuntu试试，反正Windows上显卡跑不满，据说num_workers参数在Windows上没用，试试Linux效果如何
> 

换Linux就没问题了，用啥版本都行。换了国产的发行版UOS，还不错，速度提升了4倍左右，其他Linux应该也一样

**Comment by qq401834804** [comment]
> ValueError: all input arrays must have the same shape

ValueError: all input arrays must have the same shape 这个问题也解决了，Eval.loader.batch_size_per_card只能设置成1？搞了大半天，终于解决了，这对新手太也不友好了~  本质原因后续再研究

**Comment by pigwing** [comment]
@qq401834804 也就是说windows上兼容有问题了?必须换Linux?但蛋疼的是,这台机不只是我用的,装Linux还有点麻烦.

**Comment by pigwing** [comment]
哎,换成paddlepaddle2.4.1-gpu,警告的类型从64变成63
![Snipaste_2022-12-26_10-38-18](https://user-images.githubusercontent.com/8393545/209492574-6d2aa201-0f98-427c-982e-0cf1e4889762.png)

**Comment by qq401834804** [comment]
> @qq401834804 也就是说windows上兼容有问题了?必须换Linux?但蛋疼的是,这台机不只是我用的,装Linux还有点麻烦.

1、Windows上这边用paddlepaddle-gpu==2.2.2没问题，可以跑（上面已经说了）
2、ValueError: all input arrays must have the same shape 这个问题也解决了，Eval.loader.batch_size_per_card设置成1就行（上面也说过了）
3、Windows下显卡跑不满Train.loader.num_workers只能设置成0（不能使用子线程），速度会慢很多，显卡性能够用的情况下，切Linux速度可提高至4倍左右
4、建议换Linux跑，用Ubuntu或其他发行版，我用的Windows+UOS双系统，很好用，国产Linux发行版竟然如此之强了！虽然还有很多问题，但确实很好了，你可以试下

**Comment by pigwing** [comment]
> > @qq401834804 也就是说windows上兼容有问题了?必须换Linux?但蛋疼的是,这台机不只是我用的,装Linux还有点麻烦.
> 
> 1、Windows上这边用paddlepaddle-gpu==2.2.2没问题，可以跑（上面已经说了） 2、ValueError: all input arrays must have the same shape 这个问题也解决了，Eval.loader.batch_size_per_card设置成1就行（上面也说过了） 3、Windows下显卡跑不满Train.loader.num_workers只能设置成0（不能使用子线程），速度会慢很多，显卡性能够用的情况下，切Linux速度可提高至4倍左右 4、建议换Linux跑，用Ubuntu或其他发行版，我用的Windows+UOS双系统，很好用，国产Linux发行版竟然如此之强了！虽然还有很多问题，但确实很好了，你可以试下

2.2太低了,无法使用paddlets.哎,郁闷啊

**Comment by qq401834804** [comment]
> > > @qq401834804 也就是说windows上兼容有问题了?必须换Linux?但蛋疼的是,这台机不只是我用的,装Linux还有点麻烦.
> > 
> > 
> > 1、Windows上这边用paddlepaddle-gpu==2.2.2没问题，可以跑（上面已经说了） 2、ValueError: all input arrays must have the same shape 这个问题也解决了，Eval.loader.batch_size_per_card设置成1就行（上面也说过了） 3、Windows下显卡跑不满Train.loader.num_workers只能设置成0（不能使用子线程），速度会慢很多，显卡性能够用的情况下，切Linux速度可提高至4倍左右 4、建议换Linux跑，用Ubuntu或其他发行版，我用的Windows+UOS双系统，很好用，国产Linux发行版竟然如此之强了！虽然还有很多问题，但确实很好了，你可以试下
> 
> 2.2太低了,无法使用paddlets.哎,郁闷啊

2.3呢，或者找官方的人问下看怎么解决

**Comment by pigwing** [comment]
> 

2.4和2.3都是报枚举有问题,一个是63错误,一个是64错误.真的奇怪...cuda tool kit我都安装了11.7,11.6之类的版本去适配,一样不行.不知道跟操作系统是否也有关系.我是win10 22h2的

**Comment by qq401834804** [comment]
> > 
> 
> 2.4和2.3都是报枚举有问题,一个是63错误,一个是64错误.真的奇怪...cuda tool kit我都安装了11.7,11.6之类的版本去适配,一样不行.不知道跟操作系统是否也有关系.我是win10 22h2的

不是说了嘛，Linux根本不报这个问题，版本随便用都行

**Comment by pigwing** [comment]
> > > 
> > 
> > 
> > 2.4和2.3都是报枚举有问题,一个是63错误,一个是64错误.真的奇怪...cuda tool kit我都安装了11.7,11.6之类的版本去适配,一样不行.不知道跟操作系统是否也有关系.我是win10 22h2的
> 
> 不是说了嘛，Linux根本不报这个问题，版本随便用都行

我也想用Linux,但这台机不只是我一个人使用.

**Comment by zhwesky2010** [comment]
@pigwing 你好，可能是机器环境问题，这个是我这边用内部机器测试的结果没问题。
![infoflow 2022-12-26 12-39-58](https://user-images.githubusercontent.com/52485244/209500825-98aa089b-0b96-4a80-a838-c8c300da3d22.png)

**Comment by qq401834804** [comment]
> 

有可能，我俩都是服务器主机，我是E5-1650v2 HP的机器

**Comment by qq401834804** [comment]
X79的老机器

**Comment by pigwing** [comment]
@zhouwei25 有没有办法知道这个枚举到底是那个报出来的呢.换了paddlepaddle版本,枚举的值也变了.

**Comment by pigwing** [comment]
我发现有个计算能力的指标,估计这个type是这个类型?他只有60和61
![Snipaste_2022-12-31_13-36-53](https://user-images.githubusercontent.com/8393545/210126379-f7db1a6f-3790-422a-9657-5c0e049b1722.png)

**Comment by pigwing** [comment]
并且我的显卡也不在列.

**Comment by windhw** [comment]
这个问题根本原因是Paddle用到CPU的BMI特性但没有提前检查，paddle从2.3开始在phi模块里用到了__lzcnt64指令 这个指令只有在支持BMI的CPU上才有，不支持BMI的CPU会跑出错误的结果。

**Comment by zhwesky2010** [comment]
> 这个问题根本原因是Paddle用到CPU的BMI特性但没有提前检查，paddle从2.3开始在phi模块里用到了__lzcnt64指令 这个指令只有在支持BMI的CPU上才有，不支持BMI的CPU会跑出错误的结果。

你好，非常感谢发现问题。请问 `__lzcnt64` 是在什么位置被使用的呢，可以提PR支持下哈

**Comment by windhw** [comment]
> > 这个问题根本原因是Paddle用到CPU的BMI特性但没有提前检查，paddle从2.3开始在phi模块里用到了__lzcnt64指令 这个指令只有在支持BMI的CPU上才有，不支持BMI的CPU会跑出错误的结果。
> 
> 你好，非常感谢发现问题。请问 `__lzcnt64` 是在什么位置被使用的呢，可以提PR支持下哈

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/api/lib/kernel_dispatch.cc#L80

在这一行里

**Comment by zhwesky2010** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/api/lib/kernel_dispatch.cc#L80

感谢。目前这边有建议的改法吗，我们这边机器不太好复现这个问题，开源社区 欢迎向我们提PR

**Comment by zhwesky2010** [comment]
@pigwing @qq401834804 @1649759610 你好，该问题已修复，可以安装最新的develop版本whl包试试
`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html`
