### ISSUE TITLE
Jeston编译paddle2.4出错

### ISSUE THREAD

**Issue by xuhi1996** [PaddlePaddle/Paddle#49141]
### bug描述 Describe the Bug

![1671353175347](https://user-images.githubusercontent.com/35521261/208289205-310b48a2-07bb-4a8a-a8aa-02d8bf35d1e2.jpg)

**Comment by wangzhen38** [comment]
请问你用的gcc是什么版本呢？

**Comment by xuhi1996** [comment]
> 请问你用的gcc是什么版本呢？
8.4.0的版本

**Comment by wangzhen38** [comment]
你是编译paddlepaddle还是paddle inference呢，目前应该是只支持后者，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/hardware_support/hardware_info_cn.html#feijiangchanpinyingjianzhichibiao
