### ISSUE TITLE
Jetson NX系统启动自动加载Paddle失败

### ISSUE THREAD

**Issue by zhanglei-rlsd-vip** [PaddlePaddle/Paddle#49180]
### 问题描述 Issue Description

![A5@GUI@ZE2}RC2LP IH(ZHH](https://user-images.githubusercontent.com/121075017/208576542-f03eb4bc-2a66-4701-97fa-7c349892f6d8.png)
上述demo，手动运行脚本文件可以正常完成；可是采用系统启动自动加载脚本运行，调试信息仅在import paddle前有输出，import paddle后的调试信息无输出显示。
加载脚本如下图：
<img width="437" alt="1671507292824" src="https://user-images.githubusercontent.com/121075017/208577983-646ada46-dfa4-43fa-a9c5-89be61c1406e.png">

  请问import paddle模块加载为什么失败，谢谢

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：paddlepaddle_gpu-2.3.0rc0-cp36-cp36m-linux_aarch64.whl。
CPU：Jeson NX。
GPU：Jetpack 4.4[L4T 32.4.3]，CUDA10.2.89 和CUDNN8.0.0.180
系统环境：ubuntu 18.04
Python版本:Python 3.6.9。

**Comment by XYZ-916** [comment]
没有报错是吗？

**Comment by zhanglei-rlsd-vip** [comment]
刚 加了调试代码：
<img width="220" alt="1671512191933" src="https://user-images.githubusercontent.com/121075017/208587085-3673c12a-40c9-4f66-af1a-622bccfb8bbb.png">

依然没有异常报错信息。

**Comment by XYZ-916** [comment]
没有报错您是怎么确定paddle import失败的呢？

**Comment by zhanglei-rlsd-vip** [comment]
感谢您的答复。
手动启动demo代码：在启动日志中会有所有的logging信息，
在采用jetson reboot的启动方式，启动日志中仅有import paddle之前的logging信息，另外main函数中的代码（含logging）均未执行输出。
所以感觉像import paddle异常退出了。因为是系统启动自动加载运行，所有只能从logging判断，其它没有合适的调试手段

**Comment by XYZ-916** [comment]
这没有log没有报错我这边也不太好判断。
