### ISSUE TITLE
并发推理问题：2个并发就报错：(PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.

### ISSUE THREAD

**Issue by ruijf** [PaddlePaddle/Paddle#49187]
### 请提出你的问题 Please ask your question

我的程序是这样设计的，gRPC Server监听推理请求，收到请求调用推理方法。在只有一个并发请求下是正常的，但是用压测工具并发2个请求时就出错了，错误信息如下：
Traceback (most recent call last):
  File "/paddle/weld_test/Detect/infer.py", line 720, in main
    results = detector.predict([img], 0.5) 
  File "/paddle/weld_test/Detect/infer.py", line 192, in predict
    np_boxes = boxes_tensor.copy_to_cpu()
RuntimeError: (PreconditionNotMet) Tensor not initialized yet when Tensor::type() is called.
  [Hint: holder_ should not be null.] (at /paddle/paddle/fluid/framework/tensor.h:218)

推理环境如下, 应用运行在Docker中：
Ubuntu 20.04 
PadddlePaddle 2.2
CUDA 11.2

**Comment by XYZ-916** [comment]
请检查每次请求的数据是否正确。

**Comment by ruijf** [comment]
> 请检查每次请求的数据是否正确。

请求数据是对的，因为在图片解码时没有出错。

**Comment by XYZ-916** [comment]
确认下boxes_tensor是否有值呢？

**Comment by ruijf** [comment]
原因找到了，prediction对象不是线程安全的，改成线程绑定就OK了
