### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid.core_avx'

### ISSUE THREAD

**Issue by Ouyang-cmd** [PaddlePaddle/Paddle#49185]
My computer instruction set includes avx

python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

But running the demo eventually still reports an error

![P4W9AYONTC`SSY(XIRQV4~S](https://user-images.githubusercontent.com/69027135/208598608-b4a723ce-d652-467a-8db7-a3c3498fd6c9.png)

**Comment by XYZ-916** [comment]
What's the version of CUDA on your device?

**Comment by Ouyang-cmd** [comment]
11.4

**Comment by Ouyang-cmd** [comment]
> What's the version of CUDA on your device?

11.4

**Comment by XYZ-916** [comment]
Command `python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html` is for CUDA11.2.

**Comment by Ouyang-cmd** [comment]
> Command `python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html` is for CUDA11.2.

But which command should be used in 11.4？

**Comment by Ouyang-cmd** [comment]
> Command `python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html` is for CUDA11.2.

Because there is no version for 11.4 in paddlepaddle, how should I install paddlepaddle？

**Comment by XYZ-916** [comment]
try command: python -m pip install paddlepaddle-gpu==2.4.1.post114 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

**Comment by Ouyang-cmd** [comment]
> try command: python -m pip install paddlepaddle-gpu==2.4.1.post114 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
There is no post114 version here

![image](https://user-images.githubusercontent.com/69027135/208634676-8e31bd40-9fbf-4f2b-b7cb-a6084a086b16.png)

**Comment by Ouyang-cmd** [comment]
> try command: python -m pip install paddlepaddle-gpu==2.4.1.post114 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

其实，见到大多的建议是11.4应该选用低于11.4的最高版本，所以还是不明白问题出在哪里？

**Comment by Ouyang-cmd** [comment]
已经找到问题所在了：调用Senta，跑Senta在Github中提供的demo，报错ModuleNotFoundError: No module named 'paddle.fluid.core_avx' ，因为Senta依赖的是paddlepaddle-gpu的版本不是当前版本，当前版本中已经没有文件core_avx.pyd。

所以说，我所采用的paddlepaddle-gpu安装命令并无误，应该是可以正常使用的

当我根据Senta的时间选用了大概相应的paddlepaddle旧版本【根据paddlepaddle中版本时间线说明】，卸载原有版本，安装相应版本，即可运行

![~VIUKXRZC3ZGSNU_OK@$E 5](https://user-images.githubusercontent.com/69027135/208659153-0fb11372-2cfa-4d84-86de-8f1fce9f534e.png)

【paddle版本说明中所附的源码，不含有core_avx.pyd,是安装编译生成的】

**Comment by warmcolytas** [comment]
你好，请问你paddle用的是哪个版本

**Comment by warmcolytas** [comment]
实测paddle2.2.0可以，后来的同学可以直接装
