### ISSUE TITLE
使用greater_than算子静态图时报错

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#49190]
### 请提出你的问题 Please ask your question

您好，在使用greater_than算子的静态图模式时报了一个numpy的错，可以帮我看一下是为啥吗？
![image](https://user-images.githubusercontent.com/37332773/208619089-72271e25-93db-4ea3-bda0-5017ce45c368.png)

**Comment by XYZ-916** [comment]
你好，报错信息能给的更全一些吗？
