### ISSUE TITLE
调用WordSubstitute方法时报错，download word_synonym.json failed

### ISSUE THREAD

**Issue by XCD4P** [PaddlePaddle/Paddle#49205]
### bug描述 Describe the Bug

运行如下代码：
```
from paddlenlp.dataaug import WordSubstitute
s1 = "工地买了建工险，出了事故多长时间上报保险公司有效。"
aug = WordSubstitute('synonym', create_n=3, aug_percent=0.3)
augmented = aug.augment(s1)
print("origin:", s1)
print("augmented:", augmented)
```

会报如下错误，无法下载此json文件，但是点击报错中的src链接，是可以下载改文件的，请问如何修复此问题？
<img width="679" alt="image" src="https://user-images.githubusercontent.com/47018977/208706278-666e705a-e6c1-4ad1-b329-e2bb53ff98f2.png">

**Comment by XYZ-916** [comment]
请问手动下载可以吗？
