### ISSUE TITLE
如何通过pip或者conda安装paddle-1.6.3版本？（目前旧版本的pip和conda的网址均失效，因而命令行中自然也无效）

### ISSUE THREAD

**Issue by Ouyang-cmd** [PaddlePaddle/Paddle#49206]
### 需求描述 Feature Description

如何通过pip或者conda安装paddle-1.6.3版本？（目前旧版本的pip和conda的网址均失效，因而命令行中自然也无效）

因为我需要调用Senta库，而Senta库依赖的paddle版本是1.6.3的版本

**Comment by zhaoyinglia** [comment]
你好，请问是哪里提供的网址失效了呢？可以参考一下这个链接。https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/macos-pip.html#old-version-anchor-55-V1.6

**Comment by 4qwe** [comment]
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/macos-pip.html#old-version-anchor-55-V1.6该网页提供的paddle1.6.3仍处于无法下载状态

**Comment by 4qwe** [comment]
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/macos-pip.html#old-version-anchor-55-V1.6    该网页提供的paddlepaddle1.6.3仍处于无法下载状态
