### ISSUE TITLE
/fluid/memory/allocation/cuda_allocator.cc中managed_memory_msg提示语好像写反了

### ISSUE THREAD

**Issue by gongjimin** [PaddlePaddle/Paddle#49225]
### bug描述 Describe the Bug

我在参考<https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/applications/%E5%8F%91%E7%A5%A8%E5%85%B3%E9%94%AE%E4%BF%A1%E6%81%AF%E6%8A%BD%E5%8F%96.md>做训练的时候，发现GPU内存资源耗尽，系统提示：

```txt
Out of memory error on GPU 0. Cannot allocate 57.627197MB memory on GPU 0, 10.874146GB memory has been allocated and available memory is only 43.375000MB.

Please check whether there is any other process using GPU 0.
1. If yes, please stop them, or start PaddlePaddle on another GPU.
2. If no, please decrease the batch size of your model.
If the above ways do not solve the out of memory problem, you can try to use CUDA managed memory. The command is `export FLAGS_use_cuda_managed_memory=false`.
 (at /paddle/paddle/fluid/memory/allocation/cuda_allocator.cc:87)
. (at /paddle/paddle/fluid/imperative/tracer.cc:307)
```
按照提示设置“export FLAGS_use_cuda_managed_memory=false”之后发现仍然不行，仔细看提示后我改为“export FLAGS_use_cuda_managed_memory=true”就好了。

我查看了对应的代码`/fluid/memory/allocation/cuda_allocator.cc`中`managed_memory_msg`这个变量对应的信息，感觉这个提示信息似乎写反了？

**Comment by From00** [comment]
你好，非常感谢对这个问题的反馈。关于managed_memory的提示信息确实写反了，我们已经更正过来了，见PR： https://github.com/PaddlePaddle/Paddle/pull/49228
