### ISSUE TITLE
windows 推理的日志有没有关闭开关

### ISSUE THREAD

**Issue by LuWei6896** [PaddlePaddle/Paddle#49269]
### 请提出你的问题 Please ask your question

![2ceb1e9c1666992155db3fbb9162d32](https://user-images.githubusercontent.com/32614962/209114663-106b7e1d-1278-4f46-87e3-95fa363341dd.png)

**Comment by yeliang2258** [comment]
可以参考这个API：paddle.inference.Config.disable_glog_info()
https://www.paddlepaddle.org.cn/inference/v2.4/api_reference/python_api_doc/Config/OtherFunction.html#log

**Comment by LuWei6896** [comment]
好的 谢谢您的答复😊--发自新浪邮箱客户端
在 12月23日 10:08，yeliang2258 ***@***.***> 写道：


可以参考这个API：paddle.inference.Config.glog_info_disabled()


https://www.paddlepaddle.org.cn/inference/v2.4/api_reference/python_api_doc/Config/OtherFunction.html#log



&mdash;
