### ISSUE TITLE
按手册安装paddlepaddle出现的问题

### ISSUE THREAD

**Issue by pjyaaa** [PaddlePaddle/Paddle#49315]
### 问题描述 Issue Description

按此命令在anaconda3的prompt中运行以下命名python -m pip install paddlepaddle==2.4.1 -i https://pypi.tuna.tsinghua.edu.cn/simple后提示安装成功，但用以下方式验证：安装完成后您可以使用 python 进入 python 解释器，输入import paddle ，再输入 paddle.utils.run_check()后提示错误信息OSError: Invalid enum backend type `64`.后又用python -m pip uninstall paddlepaddle删除paddlepaddle后提示paddle 2.4.1删除成功，再上面步骤重新安装paddlepaddle后提示安装成功，再用上述验证方法验证后又出现同样错误，电脑重新启动后重复上述步骤问题依旧。python3.8   cpu:Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz   3.10 GHz

### 版本&环境信息 Version & Environment Information

Paddle version:2.4.1
python version:3.8
cpu:Intel(R) Xeon(R) CPU E3-1220 V2 @ 3.10GHz   3.10 GHz
system:window10  64

**Comment by pigwing** [comment]
你这是CPU版本的也报这个错误?我安装GPU版的,一样是这个OSError: Invalid enum backend type `63`,我的type会根据版本变2.3.2的是64..........2.4.1的是63
