### ISSUE TITLE
部署安装问题

### ISSUE THREAD

**Issue by rap8** [PaddlePaddle/Paddle#49325]
### 问题描述 Issue Description

服务器是国产，CPU是鲲鹏920，安装官网的步骤下载cmake后没有报错一切正常安装可是他这个安装位置好像有点问题，安装完成后无法调用
![f63a8bd54283f0c0f53c920f9c97ffa](https://user-images.githubusercontent.com/110172520/209490341-58d167d4-b441-4851-9a53-dfb5828335a4.png)
![d2e8f7685897937af81a52e5af471b5](https://user-images.githubusercontent.com/110172520/209490346-5726cac4-8b94-4124-a0b3-48941a6a0b3e.png)
![981b03c4a05d4ff6dac5ceb479a39f8](https://user-images.githubusercontent.com/110172520/209490352-91d94188-9763-4255-aa50-ad26d0e6305b.png)
![54e9c15565c2ed4cd2f01f839321f28](https://user-images.githubusercontent.com/110172520/209490358-6ccd8cf1-c153-4b7a-af65-3a4f60f72b61.png)
![57c3f06e877de47220b1a832b587d62](https://user-images.githubusercontent.com/110172520/209490363-e44ae477-a0d4-40fa-82af-d851d191c27a.png)

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: uos 20
GCC version: (Uos 8.3.0.5-1+dde) 8.3.0
Clang version: N/A
CMake version: version 3.25.0
Libc version: glibc 2.17
Python version: 3.7.12

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by rap8** [comment]
![3a254c865b95dd79ddcfee710bfd6c2](https://user-images.githubusercontent.com/110172520/209490829-99c935dd-c4d3-4352-8457-86c9cf868900.png)

**Comment by rap8** [comment]
我看是要把环境变量加里面现在解压后的目录和安装后的目录分别为这些，
![7aeb68f1630cacdf8508c459e57d23b](https://user-images.githubusercontent.com/110172520/209491779-af76e6ce-ff1b-4533-9a93-6f0450a47ab8.png)
![6a9cc5bab5b9464b9ba79ad02009a86](https://user-images.githubusercontent.com/110172520/209491781-dffdd79d-2b14-4f88-9194-c832c569698d.png)

**Comment by rap8** [comment]
我把bin目录添加到环境变量后继续执行步骤，然后到
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
报错了
![image](https://user-images.githubusercontent.com/110172520/209496682-68338318-aa18-49bc-af59-a3df92b7a0d0.png)
是我cmake的缘故吗，我没有添加的bin目录有问题还是？

**Comment by ccsuzzh** [comment]
-DPY_VERSION这里指定一下具体python版本试试。例如-DPY_VERSION=3.7。

**Comment by rap8** [comment]
> -DPY_VERSION这里指定一下具体python版本试试。例如-DPY_VERSION=3.7。

谢谢你的回复，安装您的方法我成功到了第9步（make TARGET=ARMV8 -j$(nproc)），但是我这边一直报连接超时，您知道w为什么吗？
![799ba591d887d4c4e17f3998aca1468](https://user-images.githubusercontent.com/110172520/209529077-76f5f76d-e3bc-46d5-bc23-80c54eac3f30.png)

**Comment by ccsuzzh** [comment]
编译过程中需要下载很多第三方库，您可能需要科学上网确保这些库能够正常下载。

**Comment by rap8** [comment]
> 编译过程中需要下载很多第三方库，您可能需要科学上网确保这些库能够正常下载。

您意思是在自己电脑上开还是服务器上面呢？，因为我自己电脑有开启

**Comment by ccsuzzh** [comment]
如果您是在服务器上编译安装paddle，那就是服务器上开。

**Comment by rap8** [comment]
> 

好的，谢谢您今天的回答对我很有帮助。

**Comment by rap8** [comment]
> 如果您是在服务器上编译安装paddle，那就是服务器上开。

好的。谢谢您的回答对我很有帮助。谢谢您

**Comment by veyron95** [comment]
@rap8 已经联系了相关同学远程支持，已邮件回复。

**Comment by rap8** [comment]
问题解决了，UOS源码编译必须要科学上网，开了个VPN又重新编译了一遍可以运行
