### ISSUE TITLE
使用enable_tuned_tensorrt_dynamic_shape设置动态shape推理出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#49332]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.4.1
 - Windows 10
 - Python 3.8

代码片段：
```python
            config.enable_use_gpu(gpu_mem, 0)
            # 是否使用TensorRT
            if use_tensorrt:
                shape_file = f"{model_dir}/shape_range_info.pbtxt"
                if not os.path.exists(shape_file):
                    config.collect_shape_range_info(shape_file)
                config.enable_tensorrt_engine(workspace_size=1 << 30,
                                              max_batch_size=1,
                                              min_subgraph_size=5,
                                              precision_mode=paddle_infer.PrecisionType.Float32,
                                              use_static=False,
                                              use_calib_mode=False)
                if os.path.exists(shape_file):
                    config.enable_tuned_tensorrt_dynamic_shape(shape_file, True)
```

错误信息：
```
    self.predictor.run()
ValueError: (InvalidArgument) The input tensor named att_cache of trt-subgraph must have >0 elements, but now have 0 elements. It's likely that this tensor is connected to a Concat op inside a trt-subgraph, try to ues API to forbid this op into trt-subgraph.
  [Hint: Expected t.numel() > 0, but received t.numel():0 <= 0:0.] (at ..\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:516)
```

它说可以禁用某个API解决，如果禁用呢？

**Comment by fengxiaoshuai** [comment]
> ### 请提出你的问题 Please ask your question
> * PaddlePaddle 2.4.1
> * Windows 10
> * Python 3.8
> 
> 代码片段：
> 
> ```python
>             config.enable_use_gpu(gpu_mem, 0)
>             # 是否使用TensorRT
>             if use_tensorrt:
>                 shape_file = f"{model_dir}/shape_range_info.pbtxt"
>                 if not os.path.exists(shape_file):
>                     config.collect_shape_range_info(shape_file)
>                 config.enable_tensorrt_engine(workspace_size=1 << 30,
>                                               max_batch_size=1,
>                                               min_subgraph_size=5,
>                                               precision_mode=paddle_infer.PrecisionType.Float32,
>                                               use_static=False,
>                                               use_calib_mode=False)
>                 if os.path.exists(shape_file):
>                     config.enable_tuned_tensorrt_dynamic_shape(shape_file, True)
> ```
> 
> 错误信息：
> 
> ```
>     self.predictor.run()
> ValueError: (InvalidArgument) The input tensor named att_cache of trt-subgraph must have >0 elements, but now have 0 elements. It's likely that this tensor is connected to a Concat op inside a trt-subgraph, try to ues API to forbid this op into trt-subgraph.
>   [Hint: Expected t.numel() > 0, but received t.numel():0 <= 0:0.] (at ..\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:516)
> ```
> 
> 它说可以禁用某个API解决，如果禁用呢？
类似于下面的使用方式：
config.exp_disable_tensorrt_ops(["where","group_norm","reshape2"])

**Comment by fengxiaoshuai** [comment]
可以这样去禁掉一些op进入trt：config.exp_disable_tensorrt_ops(["where","group_norm","reshape2"])

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 你这个只指定Paddle的API，看错误信息只给出`The input tensor named att_cache of trt-subgraph must have >0 elements,`的事变量名，这个要怎么处理？

**Comment by fengxiaoshuai** [comment]
日志里建议你delete掉Concat这个op

**Comment by yeyupiaoling** [comment]
好的，我试试

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 加了`config.exp_disable_tensorrt_ops(["Concat"])`还是一样的错误。

**Comment by fengxiaoshuai** [comment]
把reshape2也禁掉试试， 或者用最新的develop的版本试试

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 好的，我试试

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 没有报上面的错了，是新的错误，说op没有注册

```
    self.predictor = paddle_infer.create_predictor(config)
RuntimeError: (NotFound) Operator (preln_residual_bias) is not registered.
  [Hint: op_info_ptr should not be null.] (at ..\paddle/fluid/framework/op_info.h:156)
```

使用develop的版本报下面错误，所以就没有用。
```
    field_dict[key] = _ConvertToUnicode(buffer[pos:new_pos])
  File "D:\Anaconda3\envs\PaddlePaddle\lib\site-packages\google\protobuf\internal\decoder.py", line 553, in _ConvertToUnicode
    value = str(byte_str, 'utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 325-326: 'utf-8' codec can't decode bytes in position 325-326: invalid continuation byte in field: paddle.framework.proto.OpProto.Attr.comment
```

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 我用了develop版本的，还是这样的错误

```
Traceback (most recent call last):
  File "infer_path.py", line 24, in <module>
    predictor = PPASRPredictor(configs=args.configs,
  File "/home/test/yeyupiaoling/PPASR/ppasr/predict.py", line 83, in __init__
    self.predictor = InferencePredictor(configs=self.configs,
  File "/home/test/yeyupiaoling/PPASR/ppasr/infer_utils/inference_predictor.py", line 73, in __init__
    self.predictor = paddle_infer.create_predictor(config)
RuntimeError: (NotFound) Operator (preln_residual_bias) is not registered.
  [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:156)
```

**Comment by yeyupiaoling** [comment]
@fengxiaoshuai 

已经禁用了，还是报错，使用的是最新的develop。
```
config.exp_disable_tensorrt_ops(["Concat", "reshape2"])
```

![image](https://user-images.githubusercontent.com/26297768/228190000-ab3d4e25-2ec3-4ead-9833-82c96f8504dd.png)


错误信息：
```
ValueError: (InvalidArgument) The input tensor named att_cache of trt-subgraph must have >0 elements, but now have 0 elements. It's likely that this tensor is connected to a Concat op inside a trt-subgraph, try to ues API to forbid this op into trt-subgraph.
  [Hint: Expected t.numel() > 0, but received t.numel():0 <= 0:0.] (at ..\paddle/fluid/operators/tensorrt/tensorrt_engine_op.h:524)

```

**Comment by yeyupiaoling** [comment]
#52365

**Comment by qxr04025** [comment]
> @fengxiaoshuai 我用了develop版本的，还是这样的错误
> 
> ```
> Traceback (most recent call last):
>   File "infer_path.py", line 24, in <module>
>     predictor = PPASRPredictor(configs=args.configs,
>   File "/home/test/yeyupiaoling/PPASR/ppasr/predict.py", line 83, in __init__
>     self.predictor = InferencePredictor(configs=self.configs,
>   File "/home/test/yeyupiaoling/PPASR/ppasr/infer_utils/inference_predictor.py", line 73, in __init__
>     self.predictor = paddle_infer.create_predictor(config)
> RuntimeError: (NotFound) Operator (preln_residual_bias) is not registered.
>   [Hint: op_info_ptr should not be null.] (at /paddle/paddle/fluid/framework/op_info.h:156)
> ```

请问这个错误怎么解决的
