### ISSUE TITLE
OSError: Data type error. Currently, The data type of IntArrayBase only supports Tensor with int32 and int64, but now received `float32`.

### ISSUE THREAD

**Issue by hzy-del** [PaddlePaddle/Paddle#49352]
### 请提出你的问题 Please ask your question

在这里报错是什么原因？
weight_diff = paddle.max(
            paddle.to_tensor([1]).cuda() + 10000 * paddle.min(org_pool - paddle.to_tensor([0.3]).cuda(),
                                                               paddle.to_tensor([0]).cuda()),
            paddle.to_tensor([0.5]).cuda())

**Comment by 0x45f** [comment]
paddle.min/max的axis参数直接传入int值就可以，参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/max_cn.html#max
