### ISSUE TITLE
paddle user defined loss  not work

### ISSUE THREAD

**Issue by Sky-zzt** [PaddlePaddle/Paddle#49350]
### 请提出你的问题 Please ask your question

<img width="604" alt="33f386bd97033f5af252fdc4be0dde73" src="https://user-images.githubusercontent.com/52705155/209555661-df9a3a30-2938-418a-9f1f-019fecf74839.png">

<img width="1114" alt="42087909c46aef7b70fa94c77e6fa3d2" src="https://user-images.githubusercontent.com/52705155/209555686-e8eab09f-51a7-4315-b368-eead4d8162ba.png">

as picture  we can see, though  I set fixed loss equal 1 .but the model metric  AUC is still very nice.

by the way  ,I run the model in  https://aistudio.baidu.com/bj-cpu-01/user/324626/5083222/notebooks/5083222.ipynb which is PaddleRec  example  .

code  path : https://github.com/PaddlePaddle/PaddleRec/blob/master/models/rank/din/dygraph_model.py
![image](https://user-images.githubusercontent.com/52705155/209556655-a79e9fbc-4105-4bc3-8e7f-c3f51186ee53.png)

paddle version >= 2.0

**Comment by DesmonDay** [comment]
Can you provide the minimum reproducible code? Maybe upload to your github repository or aistudio, then I can check it.

**Comment by DesmonDay** [comment]
Ok. Let me take a look later.
