### ISSUE TITLE
paddle\sision\dataset\mnist文件的Args中解释backend参数的描述有误

### ISSUE THREAD

**Issue by xiaokai-lyk** [PaddlePaddle/Paddle#49359]
### 问题描述 Please describe your issue

`If this option is not set, will get backend from ``paddle.vsion.get_image_backed`中的paddle.vsion应写为 paddle.vision，少了一个i

**Comment by 0x45f** [comment]
我看最新的代码中这个拼写错误已经修复了，感谢反馈~
