### ISSUE TITLE
python v2 from_tar()接口是否需要对输入文件的完整性加一些检查？

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#4935]
在使用paddle v2进行增量训练时，使用如下的接口初始化模型，在tar.gz里缺少了一部分`*.wbias`文件的情况下，能够加载成功，但是最后保存的时候不能完整的保存模型
```
#init
parameters = paddle.parameters.Parameters.from_tar(gzip.open("xxx.tar.gz"))
...
# save
parameters.to_tar(f)
```
是否可以在from_tar接口中对模型文件的完整性进行一些检查，以便更好地定位问题。

**Comment by typhoonzero** [comment]
我理解现在`from_tar`是根据模型配置的proto文件读取模型的参数文件并加载的，如果缺少参数文件会报错。而`init_from_tar`可以自动的跳过缺少的参数文件。

先关闭这个issue了，如果上面的解答仍未能解决您的问题，可以reopen此issue
