### ISSUE TITLE
报错信息英文单词拼写错误

### ISSUE THREAD

**Issue by Anyon123** [PaddlePaddle/Paddle#49362]
### 文档链接&描述 Document Links & Description

文档链接：
https://www.paddlepaddle.org.cn/documentation/docs/en/guides/beginner/tensor_en.html

存在问题：
在页面上搜索"Faild"，会跳转到如下地方：

Tensor must be “rectangular” – that is, along each dimension, the number of elements must be equal. For example:

ndim_2_tensor = paddle.to_tensor([[1.0, 2.0],
                                  [4.0, 5.0, 6.0]])
An exception will be thrown in this case:

ValueError:
        Faild to convert input data to a regular ndarray :
         - Usually this means the input data contains nested lists with different lengths.

其中"ValueError"下面的"Faild"拼写错误，应该为"Failed"。

### 请提出你的建议 Please give your suggestion

应该把文档中的"Faild"改为"Failed"。除了官网文档中，在各种代码的注释中也出现了相同的错误。

**Comment by 0x45f** [comment]
感谢反馈~我们会联系相关同学修改相关拼写错误

**Comment by 0x45f** [comment]
已通过 https://github.com/PaddlePaddle/Paddle/pull/49366 和 https://github.com/PaddlePaddle/docs/pull/5546 进行了修复，感谢反馈
