### ISSUE TITLE
Nesterov Momentum

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#4939]
- doc: http://cs231n.github.io/neural-networks-3/
- PyTorch: http://pytorch.org/docs/master/optim.html#torch.optim.SGD

**Comment by chengduoZH** [comment]
[`Nesterov Momentum`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/momentum_op.cc#L86) has been implemented.
