### ISSUE TITLE
请问高阶自动微分API paddle.grad在哪个版本可以用？好像和文档对不上，心塞

### ISSUE THREAD

**Issue by cloud2009** [PaddlePaddle/Paddle#49399]
### 请提出你的问题 Please ask your question

代码：
import paddle
x = paddle.ones(shape=[1], dtype='float32')
x.stop_gradient = False
print('x:',x)
y = x ** 2 + x * 2 + 1
print('y:',y)
dydx = paddle.grad(y,x,create_graph=True)[0] 
print('dydx:',dydx)
try: 
    ddydx = paddle.grad(dydx,x)[0]
    print('ddydx:',ddydx)
except:
    print('Cannot Support Higher Order Auto-Differentiation')

输出结果：

# Paddle develop 版本，没有问题，可以按照文档的说明算高阶自动微分

x: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [1.])
y: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [4.])
dydx: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [4.])
ddydx: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [2.])

# Paddle 2.4.0 版本，不能高阶自动微分，但一阶自动微分没报错

x: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [1.])
y: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [4.])
dydx: Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=False,
       [4.])
Cannot Support Higher Order Auto-Differentiation

# Paddle 2.2.2 版本，不能高阶自动微分，而且在一阶微分那里有报错

x: Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [1.])
y: Tensor(shape=[1], dtype=float32, place=CUDAPlace(0), stop_gradient=False,
       [4.])
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_263/2829770891.py in <module>
      7 y = x ** 2 + x * 2 + 1
      8 print('y:',y)
----> 9 dydx = paddle.grad(y,x,create_graph=True)[0] # 尝试修改crete_graph为False
     10 print('dydx:',dydx)
     11 

<decorator-gen-161> in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, no_grad_vars)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs)
     23     def __impl__(func, *args, **kwargs):
     24         wrapped_func = decorator_func(func)
---> 25         return wrapped_func(*args, **kwargs)
     26 
     27     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py in __impl__(*args, **kwargs)
    227         assert in_dygraph_mode(
    228         ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
--> 229         return func(*args, **kwargs)
    230 
    231     return __impl__

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in grad(outputs, inputs, grad_outputs, retain_graph, create_graph, only_inputs, allow_unused, no_grad_vars)
    626     return core.dygraph_partial_grad(inputs, outputs, grad_outputs,
    627                                      no_grad_vars, place, create_graph,
--> 628                                      retain_graph, allow_unused, only_inputs)
    629 
    630 

RuntimeError: (NotFound) The Op elementwise_pow_grad doesn't have any grad op. If you don't intend calculating higher order derivatives, please set `create_graph` to False.
  [Hint: double_grad_node should not be null.] (at /paddle/paddle/fluid/imperative/partial_grad_engine.cc:908)

**Comment by JiabinYang** [comment]
这个原因是

**Comment by JiabinYang** [comment]
这个原因是
1. 2.2.2的时候pow尚未支持2阶微分，当计算1阶微分且create_graph=True时由于需要创建2阶的节点，而pow并不支持因此会报错
2. 2.4.0本质上也应该报错只是当时策略有些问题并未报错出来
3. develop已经正确修复了这个问题因此可以正常使用

**Comment by cloud2009** [comment]
> 

好的 谢谢啦 我以后用develop版本。

但是2.2.2版本现在运行这个AI Studio的项目，https://aistudio.baidu.com/aistudio/projectdetail/4178470?channelType=0&channel=0， 没有报错，里面调用了一阶自动微分和二阶自动微分。

涉及的代买如下：
在这个路径下的py文件 /work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/pinn_solver.py
的def neural_net_equations(self, t, x, y) 这里面能：  
先进行一阶微分      u_x = self.autograd(u, x)
再进行二阶微分      u_xx = self.autograd(u_x, x, create_graph=True)
autograd调用了paddle.autograd.grad: 
    def autograd(self, U, x, create_graph=True):
        return paddle.autograd.grad(U, x,
               retain_graph=True, create_graph=create_graph)[0]

<img width="492" alt="594405b67fff2ea26985a80af" src="https://user-images.githubusercontent.com/113963162/209904426-a48e1b44-14d2-4015-b3b2-f021cfb4c0b5.png">

版本号是2.2.2
<img width="392" alt="0cab0905bec02d95ee49fb50f" src="https://user-images.githubusercontent.com/113963162/209904443-e6351303-9ddf-4842-93bb-1546b1794c48.png">

**Comment by cloud2009** [comment]
> Cannot Support Higher Order Auto-Differentiation

非常感谢回复～我以后用develop版本。和这个API相关的还有个问题，是2.3.2版本的AI Studio的加精项目
https://aistudio.baidu.com/aistudio/projectdetail/4178470?channelType=0&channel=0

这里面有个文件叫pinn_solver.py 路径是在/home/aistudio/work/PaddleScience_CubeDomain/refactor_PaddleScience_0430/Module/CFD/

他里面调用了paddle.autograd.grad的二阶微分
<img width="492" alt="594405b67fff2ea26985a80af" src="https://user-images.githubusercontent.com/113963162/209907289-e6fb6bbe-1341-42c5-b4c7-9fb17a8c822b.png">

这个项目现在在2.3版本是可以正常运行的，二阶微分也能算出来一个数，是不是其实这个算的数是不对的？

**Comment by cloud2009** [comment]
已经解决了，是因为autograd在非develop版本下无法支持幂次方的微分，如果不带幂次方项的自动微分就可以跑通。
