### ISSUE TITLE
IR打印默认打开

### ISSUE THREAD

**Issue by wjddd** [PaddlePaddle/Paddle#49454]
### 文档链接&描述 Document Links & Description

[设置模型优化方法](https://www.paddlepaddle.org.cn/inference/v2.4/api_reference/python_api_doc/Config/OptimConfig.html)显示IR打印默认关闭，但源码中显示是默认打开，需要自己设置关闭。

![image](https://user-images.githubusercontent.com/65559675/210027341-17d32de3-0702-4f77-b628-14506babc4cc.png)

```
def switch_ir_debug(self, x=True): # real signature unknown; restored from __doc__
    """ switch_ir_debug(self: paddle.fluid.libpaddle.AnalysisConfig, x: int = True) -> None """
      pass
```

**Comment by Aganlengzi** [comment]
感谢反馈，switch_ir_debug最终影响的是 [ir_debug_](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_analysis_config.h#L1138)，这个是默认关闭的。switch_ir_debug带的默认参数是true，调用就会打开。具体可见：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/inference_api.cc#L796 与 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/analysis_config.cc#L1182

**Comment by wjddd** [comment]
> 感谢反馈，switch_ir_debug最终影响的是 [ir_debug_](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/paddle_analysis_config.h#L1138)，这个是默认关闭的。switch_ir_debug带的默认参数是true，调用就会打开。具体可见：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/inference_api.cc#L796 与 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/analysis_config.cc#L1182

了解，感谢解答~
