### ISSUE TITLE
Changing LoD's absolute offset to relative offsets

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4945]
The current `LoDTensor` is designed to store levels of variable-length sequences,
it stores several arrays of integers each represents a level.

The integers in each level represents the begin and end (not inclusive) offset of a sequence **in the underlying tensor**, 
let's call this format the **absolute-offset LoD** for clear.

The absolute-offset LoD can fast retrieve any sequence but fails to represent empty sequences, for example, a two-level LoD is as follows
```python
[[0, 3, 12]
 [0, 2, 3, 3, 3, 9, 12]]
```
The first level tells that there are two sequences:
- the first's offset is `[0, 3)`
- the second's offset is `[3, 12)`

while on the second level, there are several empty sequences that both begin and end at `3`.
It is impossible to tell how many empty second-level sequences exist in the first-level sequences.

There are many scenarios that relay on empty sequence representation,
such as machine translation or image to text, one instance has no translations or the empty candidate set for a prefix.

So let's introduce another format of LoD, 
it stores **the offsets of the lower level sequences** and is called **relative-offset** LoD.

For example, to represent the same sequences of the above data

```python
[[0, 3, 7]
 [0, 2, 3, 3, 3, 9, 12]
```

the first level represents that there are two sequences, 
their offsets in the second-level LoD is `[0, 3)` and `[3, 7)`.

The second level is the same with the relative offset example because the lower level is a tensor.
It is easy to find out the second sequence in the first-level LoD has two empty sequences.

**Comment by luotao1** [comment]
> the first level represents that there are two sequences,
their offsets in the second-level LoD is `[0, 3)` and `[3, 5)`.

I am not understanding how `5` comes from? Is there a more detail explanation?

**Comment by Superjom** [comment]
I've updated the examples.
[[0, 3, 7]
 [0, 2, 3, 3, 3, 9, 12]]

In the first level, `0, 3` means the 0-th element to 3-th element in the lower level, which is the subarry `0, 2, 3, 3`.
