### ISSUE TITLE
鲲鹏920服务器安装报错

### ISSUE THREAD

**Issue by rap8** [PaddlePaddle/Paddle#49458]
### 问题描述 Issue Description

您好，安装官网的下载步骤执行到make TARGET=ARMV8 -j$(nproc)
报错。
[报错信息.txt](https://github.com/PaddlePaddle/Paddle/files/10322947/default.txt)

我看好多报错信息为连接超时,后我在服务器上的hosts添加了GitHub的ip后还是没能解决报错，问一下您有什么好的办法吗请问？

txt文件是我的报错信息。
[报错信息.txt](https://github.com/PaddlePaddle/Paddle/files/10322947/default.txt)

依赖包都装上了

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: uos 20
GCC version: (Uos 8.3.0.5-1+dde) 8.3.0
Clang version: N/A
CMake version: version 3.16.8
Libc version: glibc 2.17
Python version: 3.7.12

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by Aganlengzi** [comment]
你好，错误信息显示为依赖的第三方库下载问题，非具体编译问题，建议尝试更换代理等方法解决。

**Comment by rap8** [comment]
> 你好，错误信息显示为依赖的第三方库下载问题，非具体编译问题，建议尝试更换代理等方法解决。

好的谢谢您

**Comment by rap8** [comment]
问题解决了，UOS源码编译必须要科学上网，开了个VPN又重新编译了一遍可以运行
