### ISSUE TITLE
torch.coalesce() 可以对稀疏矩阵进行  对相同索引的多个值求和, paddle中有吗

### ISSUE THREAD

**Issue by ziwenjie** [PaddlePaddle/Paddle#49467]
### 需求描述 Feature Description

对稀疏矩阵进行  对相同索引的多个值求和

### 替代实现 Alternatives

对稀疏矩阵进行  对相同索引的多个值求和

**Comment by Aganlengzi** [comment]
请问这个是否是你想要的：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/sparse/unary.py#L524

**Comment by ziwenjie** [comment]
> 请问这个是否是你想要的：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/sparse/unary.py#L524
是的，十分感谢！
