### ISSUE TITLE
paddlehub.module.manager.EnvironmentMismatchError: ernie cannot be installed because some conditions are not met:

### ISSUE THREAD

**Issue by rrryan2016** [PaddlePaddle/Paddle#49482]
### bug描述 Describe the Bug

通过下面代码调用ernie模型时，报错
`model = paddlehub.Module(name='ernie', task='seq-cls', num_classes=len(MyDataset.label_list))`

paddlehub.module.manager.EnvironmentMismatchError: ernie cannot be installed because some conditions are not met:

### 其他补充信息 Additional Supplementary Information

paddlehub版本为2.3.1，paddlepaddle 版本尝试过2.0.2/2.4.1，尝试过安装cuda 10 gpu版本和cpu版本，均会报如下错

**Comment by rrryan2016** [comment]
如果把参数name中的ernie改成ernie_tiny，则不会报错

**Comment by rainyfly** [comment]
你好，使用 hub install ernie==2.0.2 ，指定一下版本号试试
