### ISSUE TITLE
java调用paddlex的demo示例

### ISSUE THREAD

**Issue by chengxiaobo-github** [PaddlePaddle/Paddle#49480]
### 需求描述 Feature Description

![image](https://user-images.githubusercontent.com/64942949/210122830-210bcfc0-2005-4b00-8bc3-0cb3a81e86b4.png)
如何用java的方式替换这个python写法

**Comment by YuanRisheng** [comment]
麻烦提供一下具体的paddlex的demo路径，方便我们找相关同学进行分析
