### ISSUE TITLE
slice对batch size（-1）修改导致shape与其他variable不匹配

### ISSUE THREAD

**Issue by chaos-dd** [PaddlePaddle/Paddle#49527]
slice对batch size维度支持不够，一个variable的维度原来是（-1,9），希望能slice得到一个(-1,2)的variable。目前的slice算子start和end必须显示写出来导致后续batch维度和其他variable shape不匹配。
如何绕过这个限制呢？
例如：
y = fluid.layers.slice(x, axes=[0, 1], starts=[0, 0], ends=[2**31-1, 2])
x的维度是(-1,9)，但是y的维度是（2**31-1,2)，行数不一样，导致后续x和y操作的时候shape检查不通过。

**Comment by seemingwang** [comment]
对于这种第一维度确定不了的情况，slice op确实绕不开这个问题，建议尝试换tensor的切片。
例如，y = x[:,0:2]
