### ISSUE TITLE
使用fleet单机多卡训练，paddle.optimizer.lr.LambdaDecay不起作用，默认学习率为1e-6

### ISSUE THREAD

**Issue by xyzkk3** [PaddlePaddle/Paddle#49530]
### 请提出你的问题 Please ask your question

使用fleetAPI，进行多卡训练，paddle.optimizer.lr.LambdaDecay总是初始学习率为1e-6，无论传参为什么，paddle版本2.3.2。如果进行单卡训练，paddle.optimizer.lr.LambdaDecay能起作用

**Comment by xyzkk3** [comment]
又有个新问题，fleet多卡训练会卡在第二个batch backward传播那，一直都不动

**Comment by xyzkk3** [comment]
worker log 0
I0104 07:26:35.937018  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.937023  5422 reducer.cc:734] Var[48] [create_parameter_44.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.937028  5422 basic_engine.cc:626] Remove op after op cast runs
I0104 07:26:35.937039  5422 basic_engine.cc:571] Start to execute grad op elementwise_add_grad
I0104 07:26:35.937052  5422 copy_kernel.cu:38] TensorCopy 48, 128, 28, 28 from Place(gpu:0) to Place(gpu:0)
I0104 07:26:35.937081  5422 basic_engine.cc:626] Remove op after op elementwise_add_grad runs
I0104 07:26:35.937094  5422 basic_engine.cc:571] Start to execute grad op batch_norm_grad
I0104 07:26:35.937126  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.937134  5422 reducer.cc:734] Var[42] [create_parameter_38.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.937145  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.937150  5422 reducer.cc:734] Var[41] [create_parameter_37.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.937155  5422 basic_engine.cc:626] Remove op after op batch_norm_grad runs
I0104 07:26:35.937170  5422 basic_engine.cc:571] Start to execute grad op batch_norm_grad
I0104 07:26:35.937198  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.937204  5422 reducer.cc:734] Var[45] [create_parameter_41.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.937209  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.937214  5422 reducer.cc:734] Var[44] [create_parameter_40.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.937218  5422 basic_engine.cc:626] Remove op after op batch_norm_grad runs
I0104 07:26:35.937232  5422 basic_engine.cc:571] Start to execute grad op conv2d_grad
I0104 07:26:35.937248  5422 conv_grad_kernel.cu:93] Compute ConvGradOp with cuDNN: data_format=NCHW compute_format=NCHW
I0104 07:26:35.937323  5422 conv_cudnn_helper.h:381] [cuDNN Convoltion] exhaustive_search=0, deterministic=0, choose algo=1, workspace=46.2388 MB
I0104 07:26:35.937377  5422 conv_cudnn_helper.h:563] [cuDNN Convoltion] exhaustive_search=0, deterministic=0, choose algo=1, workspace=46.5022 MB
I0104 07:26:35.937387  5422 conv_grad_kernel.cu:406] filter algo: 1, time -1
I0104 07:26:35.937886  5422 basic_engine.cc:626] Remove op after op conv2d_grad runs
I0104 07:26:35.937906  5422 basic_engine.cc:571] Start to execute grad op conv2d_grad
I0104 07:26:35.937928  5422 conv_grad_kernel.cu:93] Compute ConvGradOp with cuDNN: data_format=NCHW compute_format=NCHW
I0104 07:26:35.938021  5422 conv_cudnn_helper.h:381] [cuDNN Convoltion] exhaustive_search=0, deterministic=0, choose algo=1, workspace=27.5982 MB
I0104 07:26:35.938086  5422 conv_cudnn_helper.h:563] [cuDNN Convoltion] exhaustive_search=0, deterministic=0, choose algo=1, workspace=27.5959 MB
I0104 07:26:35.938098  5422 conv_grad_kernel.cu:406] filter algo: 1, time -1
I0104 07:26:35.938390  5422 basic_engine.cc:626] Remove op after op conv2d_grad runs
I0104 07:26:35.938403  5422 basic_engine.cc:571] Start to execute grad op cast
I0104 07:26:35.938427  5422 basic_engine.cc:626] Remove op after op cast runs
I0104 07:26:35.938436  5422 basic_engine.cc:571] Start to execute grad op cast
I0104 07:26:35.938454  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.938462  5422 reducer.cc:734] Var[40] [create_parameter_36.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.938467  5422 basic_engine.cc:626] Remove op after op cast runs
I0104 07:26:35.938475  5422 basic_engine.cc:571] Start to execute grad op cast
I0104 07:26:35.939038  5422 gradient_accumulator.cc:757] call gradient accumulator backward hooks.
I0104 07:26:35.939044  5422 reducer.cc:734] Var[43] [create_parameter_39.w_0@GRAD] arrived and triggered disthook
I0104 07:26:35.939049  5422 basic_engine.cc:626] Remove op after op cast runs
I0104 07:26:35.939059  5422 basic_engine.cc:571] Start to execute grad op prelu_grad
I0104 07:26:35.941344  5422 auto_growth_best_fit_allocator.cc:106] Not found and reallocate 77070336(0x7f0a6e000000), and remaining 0
I0104 07:26:35.942869  5422 auto_growth_best_fit_allocator.cc:164] Free chunk with size 294912

**Comment by seemingwang** [comment]
> ### 请提出你的问题 Please ask your question
> 使用fleetAPI，进行多卡训练，paddle.optimizer.lr.LambdaDecay总是初始学习率为1e-6，无论传参为什么，paddle版本2.3.2。如果进行单卡训练，paddle.optimizer.lr.LambdaDecay能起作用

你好，对于这个问题，能否提供一段简短的代码复现问题，这边会尽快排查。
