### ISSUE TITLE
求问怎么将矩阵（或多个fc结果）按列softmax，sequence softmax是否能够满足该需求？

### ISSUE THREAD

**Issue by snowhws** [PaddlePaddle/Paddle#4954]
能否给个例子？希望得到如下新的向量结果，新向量每个元素是左侧对应第i列元素取softmax的结果，得到新的矩阵：
col1 col2 col3 col4
[a1     a2    a3    a4]
[b1     b2    b3    b4]       =>     [[softmax(col1)], [softmax(col2)], [softmax(col3)], [softmax(col4)]] 
[c1     c2     c3    c4]      
[d1     d2    d3    d4]

谢谢！

**Comment by luotao1** [comment]
SequenceSoftmax做不了：比如s0 s0 s0 s0 s1 s1 s2 s2 s2，是分别在(s0 s0 s0 s0) (s1 s1) (s2 s2 s2)之间求，3个sequence则算3个softmax。

**Comment by luotao1** [comment]
可以先用seq_concat将这几个拼起来，再用sequence_softmax。

**Comment by lcy-seso** [comment]
可以先转置之后接softmax，然后再转置回来。seq concat 不可以。

**Comment by lcy-seso** [comment]
但 transpose 在 paddle 中可以有两种处理：
1. transpose layer；
2. mixed layer 以 tranpose full matrix projection.

后者是对转置乘，请按照需要的计算逻辑选择。

**Comment by snowhws** [comment]
能否举个例子？比如三个fc的结果，最后怎么拼接成矩阵再做转置？
fc1 = fc_layer(...)
fc2 = fc_layer(...)
fc2 = fc_layer(...)

**Comment by hedaoyuan** [comment]
多个fc拼接和标题中的问题是两个问题了

> 能否举个例子？比如三个fc的结果，最后怎么拼接成矩阵再做转置？

可以用concat拼接多个fc的输出为一个输出，再接transpose layer。

**Comment by hedaoyuan** [comment]
https://github.com/PaddlePaddle/models/blob/8e80e207006ab58c0fa2377ab63d8122670807a5/image_classification/googlenet.py#L64

**Comment by luotao1** [comment]
请按照 @lcy-seso 的意见（先转置之后接softmax，然后再转置回来）进行操作：https://github.com/PaddlePaddle/Paddle/issues/4954#issuecomment-338107629

**Comment by zishuaiz** [comment]
lstmmemory_group的输出，fw和bw，concat[fw, bw]是按照哪个维度来concat的
比如：
fw和bw是 [batch, max_sen_len, lstm_units]维度的，
那concat后是什么维度的，求问怎样得到 [batch, max_sen_len, 2*lstm_units]?
@luotao1
