### ISSUE TITLE
Mac m1 安装paddlepaddle 报错 zsh: illegal hardware instruction  python3

### ISSUE THREAD

**Issue by 19920202** [PaddlePaddle/Paddle#49567]
### 问题描述 Issue Description

我按照官网文档安装paddlepaddle==2.4.1 要求安装
MacBook Pro (13-inch, M1, 2020) Apple M1
以下为安装过程与官网安装过程一致：
          python3 --version : Python 3.7.0
          python3 -c "import platform;print(platform.architecture()[0]);print(platform.machine())": 
                  64bit
                  x86_64
          conda install paddlepaddle==2.4.1 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
(paddle_env) xxxMacBook-Pro movie_recommand % python3
      Python 3.7.0 (default, Jun 28 2018, 07:39:16) 
      [Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
      Type "help", "copyright", "credits" or "license" for more information.
      >>> import paddle
      zsh: illegal hardware instruction  python3
请问这是什么原因造成的？该怎么解决？

### 版本&环境信息 Version & Environment Information

Python version: 3.7.0
os version:11.6 (20G165)
chip：MacBook Pro (13-inch, M1, 2020)

**Comment by LumanYang** [comment]
我也遇到了这个问题，请问找到解决的方法了吗

**Comment by 19920202** [comment]
没解决，官方没回复

**Comment by Godlikemandyy** [comment]
> 没解决，官方没回复

我测试了一下，paddle在2.4.0之后的版本会有这个问题；目前也没解决，期待官网尽快给个解决方案，一般情况下还是希望在本地进行测试

**Comment by Godlikemandyy** [comment]
我测试了一下，paddle在2.4.0之后的版本会有这个问题；目前也没解决，期待官网尽快给个解决方案，一般情况下还是希望在本地进行测试

**Comment by LumanYang** [comment]
> > 没解决，官方没回复
> 
> 我测试了一下，paddle在2.4.0之后的版本会有这个问题；目前也没解决，期待官网尽快给个解决方案，一般情况下还是希望在本地进行测试

请问2.4.0版本是可以的吗

**Comment by Godlikemandyy** [comment]
> 

不可以，2.3.2可以

**Comment by lorealjackerliu** [comment]
同样的问题2.4.1

**Comment by godsoul** [comment]
还没解决，求解决，一样是m1

**Comment by XieYunshen** [comment]
M1使用x86的python安装paddlepaddle的命令如下：
```
python -m pip download paddlepaddle==2.4.1 -f https://www.paddlepaddle.org.cn/whl/mac/openblas/noavx/stable.html  --no-index --no-deps

python -m pip install paddlepaddle*whl
```

**Comment by Godlikemandyy** [comment]
你好，这种方式貌似可以了，不过我还有个疑问：
这种方式是不是只使用python3.7呢，使用python3.9能不能行呢？
还有就是这样安装是针对m1芯片的paddle版本吗？








多谢！

**Comment by XieYunshen** [comment]
3.7-3.10都可以这么使用的
针对mac-m1机器的包(arm版本)，可以直接在pypi上下载，但是你机器中的python是x86的，所以默认不会下载arm版本的包，你可以检查一下你的python环境，更换成arm版本；

arm版本只支持python3.8-3.10,可以去pypi链接上查看
https://pypi.org/project/paddlepaddle/#files

**Comment by Godlikemandyy** [comment]
但是你机器中的python是x86的，所以默认不会下载arm版本的包，你可以检查一下你的python环境，更换成arm版本；
多谢指教，多谢多谢！
麻烦请问一下如何查看我的python是x86的，怎么更换成arm版本呢，有没有教程啥的？
我的python环境都是用conda创建的，conda create -n env_name python=***；之前没有出现过这个情况

**Comment by XieYunshen** [comment]
> 但是你机器中的python是x86的，所以默认不会下载arm版本的包，你可以检查一下你的python环境，更换成arm版本； 多谢指教，多谢多谢！ 麻烦请问一下如何查看我的python是x86的，怎么更换成arm版本呢，有没有教程啥的？ 我的python环境都是用conda创建的，conda create -n env_name python=***；之前没有出现过这个情况

`CONDA_SUBDIR=osx-arm64 conda create -n env_name python=***`
这样应该就可以的

**Comment by Godlikemandyy** [comment]
我测试了一下，用你这种方式确实创建出的环境里的python是arm的

正常用conda命令创建的虚拟环境里的python是x86_64的




我想咨询的是这种正常创建的环境是x86_64d的情况有没有可能是因为我安装miniconda3的是误装成了intel版本的，所以才导致后续创建的都是x86的，因为我也不记得miniconda安装的哪个版本了


多谢你的回复

**Comment by XieYunshen** [comment]
> 我测试了一下，用你这种方式确实创建出的环境里的python是arm的 正常用conda命令创建的虚拟环境里的python是x86_64的 我想咨询的是这种正常创建的环境是x86_64d的情况有没有可能是因为我安装miniconda3的是误装成了intel版本的，所以才导致后续创建的都是x86的，因为我也不记得miniconda安装的哪个版本了 多谢你的回复

这个你可以查看一下你conda的设置`conda config --env --show`，将subdir的值修改为arm，之后使用conda create创建的环境就是arm版本了,具体命令如下
`conda config --env --set subdir osx-arm64`
但这种方法应该不能修改安装conda时默认python的版本。
当然也可以重装一下conda，选择arm版本，就不存在上述的问题了。

**Comment by Godlikemandyy** [comment]
我测试了一下确实能更改

非常感谢你的帮助，多谢！！！
