### ISSUE TITLE
Ubuntu18.04, Python3.9, cuda10.2, cudnn7.6.5, Paddle2.4.1， conda安装完后import报错。ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by holyseven** [PaddlePaddle/Paddle#49581]
### 问题描述 Issue Description

Ubuntu18.04, Python3.9, cuda10.2, cudnn7.6.5, Paddle2.4.1， conda安装完后import报错。ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory。但是Paddle2.3.2安装后没有问题

### 版本&环境信息 Version & Environment Information

Ubuntu18.04, Python3.9, cuda10.2, cudnn7.6.5, Paddle2.4.1， conda安装完后import报错。ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory。但是Paddle2.3.2安装后没有问题

**Comment by kuizhiqing** [comment]
首先确保 LD_LIBRARY_PATH 中包含所需 so 文件，建议在 python 代码中打印以验证 python session 可以找到 so 文件。

**Comment by holyseven** [comment]
嗯，有的，在conda envs lib下面。conda的环境不需要配置 LD_LIBRARY_PATH ，只需要保证nvidia driver的bin和path就可以。

主要的问题是2.4.1下报错，但是降到2.3.2就没有问题了。

我发现
Paddle2.4.1加入了一个libpaddle.so，和之前的版本不一样了？
Paddle2.3.2里没有这个文件：`/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/libpaddle.so`

```
>>> import paddle
Error: Can not import paddle core while this file exists: /opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/core.py", line 304, in <module>
    raise e
  File "/opt/conda/envs/ttt/lib/python3.9/site-packages/paddle/fluid/core.py", line 249, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
>>>
```

**Comment by smarbal** [comment]
Same error here, someone has solved it ?

**Comment by kuizhiqing** [comment]
@smarbal 添加 so 包路径至 LD_LIBRARY_PATH。

**Comment by Truong-Thanh-Quang** [comment]
libpaddle.so using CUDA 10.2
Downgrade CUDA to 10.2 may solve the problem.

**Comment by Huang-yn** [comment]
same error！

**Comment by holyseven** [comment]
My temporal solution is adding library path before running the program:
```bash
export LD_LIBRARY_PATH=[conda_path]/envs/paddle241/lib:$LD_LIBRARY_PATH 

python [paddle_program].py  # or fleetrun
```

**Comment by ericg108** [comment]
paddlepaddle 竟然只支持cuda10.2?其他版本都不行吗？我机器上安装的是libcudart.so.11.0，只能降级吗

**Comment by ericg108** [comment]
在这找到了其他版本 https://www.paddlepaddle.org.cn/install/quick/)?docurl=/documentation/docs/zh/install/pip/linux-pip.html
