### ISSUE TITLE
paddle.flatten执行报错

### ISSUE THREAD

**Issue by Zhao-Yian** [PaddlePaddle/Paddle#49608]
### 请提出你的问题 Please ask your question

对tensor执行flatten操作时抛出异常如下：
 
<img width="901" alt="image" src="https://user-images.githubusercontent.com/77494834/210974066-42a95925-b65d-46f3-8c75-acf602252981.png">

环境：paddle2.3.2

**Comment by sljlp** [comment]
请问是GPU还是CPU版本？

**Comment by sljlp** [comment]
同时请检查下flatten的输入的数据类型，目前支持float32, float64, uint8, int32, int8, int64.

**Comment by Zhao-Yian** [comment]
哦哦这样子，输入是bool类型，好的，我用reshape替代吧
