### ISSUE TITLE
paddle-2.4.1 gpu docker镜像是否已经预安装NCCL?

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/Paddle#49601]
### bug描述 
使用paddle 2.4.1 提供的docker镜像运行 paddle.utils.run_check() 后， 卡住不动。具体复现步骤如下：

【1】拉取并启动 registry.baidubce.com/paddlepaddle/paddle:2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0
```bash
nvidia-docker run -it -d --name demo --rm --gpus '"device=0,1,3"' registry.baidubce.com/paddlepaddle/paddle:2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0 /bin/bash

nvidia-docker exec -it demo /bin/bash
```

【2】容器内查看nvidia-smi信息
λ 709a3598ff44 /home nvidia-smi
Fri Jan  6 07:03:53 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.82.01    Driver Version: 470.82.01    CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA A30          On   | 00000000:17:00.0 Off |                    0 |
| N/A   34C    P0    34W / 165W |   4389MiB / 24258MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   1  NVIDIA A30          On   | 00000000:65:00.0 Off |                    0 |
| N/A   36C    P0    32W / 165W |   4462MiB / 24258MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
|   2  NVIDIA A30          On   | 00000000:E3:00.0 Off |                    0 |
| N/A   36C    P0    32W / 165W |   1859MiB / 24258MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+

【3】运行 paddle.utils.run_check()
**这里bug出现**，一直卡在 executor.py:1585: UserWarning: Standalonw executor is not used for data parallel 这一行不动。

```python
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0106 07:04:07.160100   154 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.2
W0106 07:04:07.168434   154 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
PaddlePaddle works well on 1 GPU.
/usr/local/lib/python3.7/dist-packages/paddle/fluid/executor.py:1585: UserWarning: Standalone executor is not used for data parallel
  UserWarning)
```

### 其他补充信息 Additional Supplementary Information

请问paddle提供的gpu docker镜像中是否已经预先安装了 nccl？
如果希望再paddle提供的docker镜像中单机多卡训练，是否要自己手动安装nccl？

感谢！

**Comment by sljlp** [comment]
已经安装了NCCL，不需要手动安装

**Comment by sljlp** [comment]
建议先独占GPU试下，猜想可能是由于没有开启[MIG](https://zhuanlan.zhihu.com/p/347136077)导致的问题。

**Comment by kehuo** [comment]
> 

感谢解答～
请教一下：如果希望 paddle.utils.run_check() 返回 "works well on **MANY GPUS**"，必须要开启MIG才行吗？

**Comment by freedomaswind94** [comment]
> 建议先独占GPU试下，猜想可能是由于没有开启[MIG](https://zhuanlan.zhihu.com/p/347136077)导致的问题。

你好，怎么开启呢MIG

**Comment by freedomaswind94** [comment]
> > 
> 
> 感谢解答～ 请教一下：如果希望 paddle.utils.run_check() 返回 "works well on **MANY GPUS**"，必须要开启MIG才行吗？

你好，请问你解决了吗，我也是双卡第二张识别不到，我是在docker运行的

**Comment by overjjjj** [comment]
> 建议先独占GPU试下，猜想可能是由于没有开启[MIG](https://zhuanlan.zhihu.com/p/347136077)导致的问题。

您好，请问怎么开启mig呢
