### ISSUE TITLE
Randint parameter static mode bug

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#49620]
### bug描述 Describe the Bug

Hi, thx for your work! 

It seem that the parameter `low` and `high` of `paddle.randint` does not support static `Variable`.

```python
import paddle

paddle.enable_static()

main_program = paddle.static.Program()
with paddle.static.program_guard(main_program):
    zero = paddle.zeros([1], dtype="int32")
    ten  = paddle.ones([1], dtype="int32") * 10
    # out = paddle.uniform(shape=[1], min=zero, max=ten).astype("int32")
    out = paddle.randint(low=zero, high=ten, shape=[1])

exe = paddle.static.Executor()
res = exe.run(main_program, fetch_list=[out], feed={})

paddle.disable_static()
print(res[0])
```

but got:
```
ValueError: randint's low must less then high, but received low = var fill_constant_9.tmp_0 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(True), high = var tmp_3 : LOD_TENSOR.shape(1,).dtype(int32).stop_gradient(False)
```

Because the `low` and `high` are  static `Variable`, `low >= high` will always be `True`

However, when I comment it in the source code of `randint`:

![image](https://user-images.githubusercontent.com/44900829/211129077-3ca5147c-1f3b-461b-a917-3395f99d64b0.png)

it raise:
```
.......
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3013, in __init__
    self.desc.check_attrs()
ValueError: (InvalidArgument) Found Attribute('low') with type(Variable), but it doesn't support Tensor type.
  [Hint: Expected attr_->support_tensor() == true, but received attr_->support_tensor():0 != true:1.] (at /paddle/paddle/fluid/framework/attribute_checker.h:250)
```

Currently, We can use `uniform` to replace `randint`:
```
out = paddle.uniform(shape=[1], min=zero, max=ten).astype("int32")
```

**Comment by FeixLiu** [comment]
Hi there, thanks for reaching us. Yes, currently the `low` and `high` params for `randint` api are only support an `int` as input. For more detail information, you can refer this document: https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/randint_en.html. Our developers will discuss whether to take a `variable` as input.
