### ISSUE TITLE
importError:/lib64/libstdc++.so.6:version 'CXXABI_1.3.8' not found

### ISSUE THREAD

**Issue by yqp1453552101** [PaddlePaddle/Paddle#49636]
### 问题描述 Issue Description

import paddle时，报importError:/lib64/libstdc++.so.6:version 'CXXABI_1.3.8' not found错误，目前系统提供CXXABI_1.3.7，系统不能升级，请问哪个版本的paddlepaddle支持CXXABI_1.3.7，目前安装的是paddlepaddle2.2.2

### 版本&环境信息 Version & Environment Information

Cpu版本：
paddle version:2.2.2
GCC version:4.8.5

**Comment by leizhu900516** [comment]
升级操作系统版本，本人测试，centos7.8以上无此问题
