### ISSUE TITLE
【版本2.4.1】tensor切片赋值不符合预期；

### ISSUE THREAD

**Issue by MLgeek7325** [PaddlePaddle/Paddle#49659]
### bug描述 Describe the Bug

【版本2.4.1】tensor切片赋值不符合预期；
>>> a = paddle.ones([4,4])
>>> a
Tensor(shape=[4, 4], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
>>> a[:, 1] = paddle.reshape(3 * paddle.ones([4,1]), shape=[1,4])
>>> a
Tensor(shape=[4, 4], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[ 1., -3.,  1.,  1.],
        [ 1., -3.,  1.,  1.],
        [ 1., -3.,  1.,  1.],
        [ 1., -3.,  1.,  1.]])
>>> paddle.reshape(3 * paddle.ones([4,1]), shape=[1,4])
Tensor(shape=[1, 4], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[3., 3., 3., 3.]])

**Comment by MLgeek7325** [comment]
您好，您的邮件我已收到！

**Comment by zoooo0820** [comment]
感谢反馈，问题已复现，看起来是cpu上存在此问题，gpu上无此问题。我们定位下问题原因
