### ISSUE TITLE
关于数据类型sparse_float_vector不识别的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#4965]
我的paddle版本是：
```
PaddlePaddle 0.10.5, compiled with
    with_avx: OFF
    with_gpu: OFF
    with_mkldnn: @WITH_MKLDNN
    with_mklml: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```
设置data_type:
data_title = paddle.layer.data("title", paddle.data_type.sparse_float_vector(input_dim))
报错：
data_type找不到属性：sparse_float_vector
![tim 20171020164446](https://user-images.githubusercontent.com/22980558/31812599-17272ac4-b5b6-11e7-8021-dbefa6beaa08.png)

【解决方式】：
将sparse_float_vector 改为 sparse_vector， 不知道这个问题是否需要修复。

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/PyDataProvider2.py#L178
这行目前写的是`sparse_vector = sparse_value_slot`，改成sparse_float_vector即可。
