### ISSUE TITLE
使用cpu版本paddle接口so文件，运行时出core

### ISSUE THREAD

**Issue by uniqueliulin** [PaddlePaddle/Paddle#49661]
### bug描述 Describe the Bug

使用2017版本libpaddle_capi_shared.so文件，在新的机器环境中运行出core。
![image](https://user-images.githubusercontent.com/13608746/211278606-0fb71cb1-3ac9-46e3-962e-c1059e760cb2.png)

出core机器环境，沟通时提供。

**Comment by wuhuachaocoding** [comment]
您好，我们已经收到您反馈的问题，已经安排人员尽快解决。

**Comment by zhwesky2010** [comment]
@uniqueliulin  你好，你这个是windows机器还是linux机器呢？2017的版本是指？
