### ISSUE TITLE
什么时候支持SSE指令集CPU

### ISSUE THREAD

**Issue by yzm0080** [PaddlePaddle/Paddle#49674]
### 需求描述 Feature Description

任务目标：支持SSE指令集CPU
需求场景：在一些低功耗CPU上使用
功能描述：工控机上多采用低功耗的cpu，例如 Intel Atom系列，它不支持AVX 及 FMA指令集，只支持SSE。
在windows开发机上编译PaddleOCR工程示例，正常运行，部署到工控机的windows10上却无法运行，用cpu-z工具查看cpu信息时才注意到是 Intel Atom x5-Z8350，不支持AVX 及 FMA指令集。

### 替代实现 Alternatives

TensorFlow Lite好像是支持SSE指令集cpu。

**Comment by GuoxiaWang** [comment]
这个问题已经反馈到内部，我们会继续跟进

**Comment by jiangjiajun** [comment]
Duplicate of https://github.com/PaddlePaddle/FastDeploy/issues/1103
