### ISSUE TITLE
深度学习C++

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Paddle#49686]
### 请提出你的问题 Please ask your question

之前都是python使用深度学习框架，想进阶在C++方面对神经网络的学习，从模型搭建、训练、部署、及优化，请问有推荐的学习方法路线吗

**Comment by GuoxiaWang** [comment]
我理解的是，目前训练基本是python，而 推理会涉及到 C++ 方面的知识，可以从这里作为一个主入口去学习了解 https://www.paddlepaddle.org.cn/inference/v2.4/guides/introduction/index_intro.html

**Comment by ZTurboX** [comment]
> 我理解的是，目前训练基本是python，而 推理会涉及到 C++ 方面的知识，可以从这里作为一个主入口去学习了解 https://www.paddlepaddle.org.cn/inference/v2.4/guides/introduction/index_intro.html

好的，谢谢
