### ISSUE TITLE
Paddle Inference运行预测示例程序mobilenetv1_full_api.py报错：ValueError: Unsupported backend: . 

### ISSUE THREAD

**Issue by sweetboxwwy** [PaddlePaddle/Paddle#49688]
- 版本、环境信息：
- paddlepaddle:
- paddlepaddle-gpu: 2.4.1
- paddlenlp: 
- CUDA 10.2
- DOCKER
- UBUNTU 18.04
- paddlelite 2.8

- 编译/安装方式信息：
    1）pip 安装/docker 安装

运行预测示例程序mobilenetv1_full_api.py报错：ValueError: Unsupported backend: .

python mobilenetv1_full_api.py --model_dir=./mobilenet_v1

Traceback (most recent call last):
File "mobilenetv1_full_api.py", line 237, in <module>
RunModel(args)
File "mobilenetv1_full_api.py", line 184, in RunModel
raise ValueError("Unsupported backend: %s." % args.backend)
ValueError: Unsupported backend: .

**Comment by GuoxiaWang** [comment]
从错误信息看，  `args.backend` 是 `.`，请确认一下，是否符合输入的规定

**Comment by sweetboxwwy** [comment]
> 

代码是这个https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_full_api.py，我没修改过

**Comment by sweetboxwwy** [comment]
> 从错误信息看， `args.backend` 是 `.`，请确认一下，是否符合输入的规定

代码参考的官方的，没有修改过。https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_full_api.py

**Comment by GuoxiaWang** [comment]
从代码上看， 是在这行报错了 https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_full_api.py#L185

从逻辑上看，是需要手工设定 backend 的。

可选项参考参数说明 https://github.com/PaddlePaddle/Paddle-Lite/blob/develop/lite/demo/python/mobilenetv1_full_api.py#L45
