### ISSUE TITLE
Linux系统下编译，源码路径若包含中文，就会出错

### ISSUE THREAD

**Issue by Zhang-Junzhi** [PaddlePaddle/Paddle#49699]
### 问题描述 Issue Description

放置路径为：~/Documents/碼/飛槳
运行make编译，到了连接libphi_static_1.a这一步的时候，会报错：
[ 51%] Linking CXX static library libphi_static_1.a
Merge and generate static lib: libphi_static_1.a
碼Syntax error in archive script, line 1

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: deepin 20.8
GCC version: (Uos 8.3.0.3-3+rebuild) 8.3.0
Clang version: 15.0.6
CMake version: version 3.22.1
Libc version: glibc 2.28
Python version: 3.10.9

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by GuoxiaWang** [comment]
这个应该是路径编码问题吧，尽量改成纯英文

**Comment by Zhang-Junzhi** [comment]
这个要求不合理吧。我编译项目这么多年，从来都是放中文路径，从没出过问题。第一个出问题不支持中文的就是飞桨项目，这还是国人的项目

**Comment by Zhang-Junzhi** [comment]
> 这个应该是路径编码问题吧，尽量改成纯英文

我可以改成放在英文路径，这没有多大问题。不过，编译系统假设源码目录就是纯ASCII路径，是不合理的，属于BUG。

**Comment by GuoxiaWang** [comment]
好的，我已经反馈到内部，我们会跟踪这个问题，并解决
