### ISSUE TITLE
Jetson Nano编译问题

### ISSUE THREAD

**Issue by qq-tt** [PaddlePaddle/Paddle#49694]
### 问题描述 Issue Description

在编译make之后出现报错：
![image](https://user-images.githubusercontent.com/32315802/211496217-475710b5-99bd-4e74-8a94-2cd3901e11b9.png)
![image](https://user-images.githubusercontent.com/32315802/211496186-8da5ef04-c9d9-4925-a7a1-ba4d353e64f6.png)
请问，该怎么解决？

### 版本&环境信息 Version & Environment Information

系统情况如图：
![image](https://user-images.githubusercontent.com/32315802/211496522-77e5c760-83d0-4281-85f6-95cb5d93ca1b.png)
cmake版本3.10

**Comment by b3602sss** [comment]
这个是第三库下载失败 可能需要你设置一下代理

**Comment by qq-tt** [comment]
> 这个是第三库下载失败 可能需要你设置一下代理

我在网络好的时候，已经解决这种第三库下载失败的问题了，但是还是报错，后面的报错还存在，就是：
![image](https://user-images.githubusercontent.com/32315802/211694596-cc002ab5-4b97-4387-b5c3-ceac773b9556.png)

**Comment by qq-tt** [comment]
paddle/fluid/framework/heter_service.pb.h这个文件确实没有，但是这个文件到底是预编译生成的还是编译的时候生成的，也不知道

**Comment by GuoxiaWang** [comment]
你 `git status` 看是不是少了文件?

这种有一种可能会发生。你之前在新的commit编译过一次，然后再checkout到捞的commit上继续编译。

通常情况，在切换不同commit号后，需要确认一下，最好是删掉build 目录重新 cmake

**Comment by qq-tt** [comment]
> 你 `git status` 看是不是少了文件?
> 
> 这种有一种可能会发生。你之前在新的commit编译过一次，然后再checkout到捞的commit上继续编译。
> 
> 通常情况，在切换不同commit号后，需要确认一下，最好是删掉build 目录重新 cmake

就是少了这个文件paddle/fluid/framework/heter_service.pb.h，我每次编译都是删除build文件夹，然后从cmake开始重新编译的，但是make的时候还是会报错，没成功过

**Comment by GuoxiaWang** [comment]
你没有对 paddle 源码做修改是吧？如果没有的话，你删掉 paddle 重新 git clone 一下。

或者，你能跟我描述一下，你目的是要编译什么，其中做了什么操作？让我获得更多信息。

**Comment by qq-tt** [comment]
> 你没有对 paddle 源码做修改是吧？如果没有的话，你删掉 paddle 重新 git clone 一下。
> 
> 或者，你能跟我描述一下，你目的是要编译什么，其中做了什么操作？让我获得更多信息。

我本意是想在jetson上能跑PaddleDetection里的行人检测和骨骼关键点检测模型，并用GPU加速和tensort加速，看看这两个能加速到什么程度，然后就参考了这个链接https://zhuanlan.zhihu.com/p/319371293去编译Paddle.因为使用tensor加速就是需要编译paddle，我在官方文档https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.5/deploy/python最后几行打开看，编译命令也是跟我参考的链接差不多，反正就是进行到make就不行了。

**Comment by GuoxiaWang** [comment]
我刚看了一下知乎文章。

那还请你详细列一下。 

你从 git clone 开始，到 camke 命令。你做了哪些操作。 

你可以试着重来一下，并记录下来。我再判断一下。

**Comment by GuoxiaWang** [comment]
我担心你执行了这句话 `git clone -b release/2.0-beta https://gitee.com/paddlepaddle/Paddle.git`

你可以先直接 `git clone https://gitee.com/paddlepaddle/Paddle.git`

然后手动 checkout 分支出来，请看看执行前和执行后的 git status，文件是否有少。

**Comment by qq-tt** [comment]
> 我刚看了一下知乎文章。
> 
> 那还请你详细列一下。
> 
> 你从 git clone 开始，到 camke 命令。你做了哪些操作。
> 
> 你可以试着重来一下，并记录下来。我再判断一下。

我就是进行到这篇知乎文章的"3）准备Paddle源码"这个步骤，按顺序走到第6）的make，每次重新编译我都删掉Paddle整个目录或者删掉build文件夹重新编译，就到make报错了

**Comment by qq-tt** [comment]
> 

好的，我试试

**Comment by GuoxiaWang** [comment]
比如我们官方教程里写的

```
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout release/2.0
```

**Comment by qq-tt** [comment]
> 比如我们官方教程里写的
> 
> ```
> git clone https://github.com/PaddlePaddle/Paddle.git
> cd Paddle
> git checkout release/2.0
> ```
重新编译了一遍，还是错
执行顺序：
![image](https://user-images.githubusercontent.com/32315802/211706087-514efd7f-a57c-402c-8f9e-68fdb5dc1787.png)
预编译结果：
-- Found Paddle host system: ubuntu, version: 18.04.5
-- Found Paddle host system's CPU: 4 cores
-- The CXX compiler identification is GNU 7.5.0
-- The C compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- The CUDA compiler identification is NVIDIA 10.2.89
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc
-- Check for working CUDA compiler: /usr/local/cuda/bin/nvcc -- works
-- Detecting CUDA compiler ABI info
-- Detecting CUDA compiler ABI info - done
-- CUDA compiler: /usr/local/cuda/bin/nvcc, version: NVIDIA 10.2.89
-- CXX compiler: /usr/bin/c++, version: GNU 7.5.0
-- C compiler: /usr/bin/cc, version: GNU 7.5.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.17.1") 
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
-- Current NCCL header is /usr/local/include/nccl.h. Current NCCL version is v21602. 
-- CUDA detected: 10.2.89
-- WARNING: This is just a warning for publishing release.
      You are building GPU version without supporting different architectures.
      So the wheel package may fail on other GPU architectures.
      You can add -DCUDA_ARCH_NAME=All in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local GPU architecture.
-- NVCC_FLAGS_EXTRA:  -gencode arch=compute_53,code=sm_53
-- Current cuDNN header is /usr/include/cudnn_version.h Current cuDNN version is v8.0. 
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /home/aiuser/projects/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Build OpenBLAS by External Project (include: /home/aiuser/projects/Paddle/build/third_party/install/openblas/include, library: /home/aiuser/projects/Paddle/build/third_party/install/openblas/lib/libopenblas.a)
-- Protobuf protoc executable: /home/aiuser/projects/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/aiuser/projects/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/aiuser/projects/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/aiuser/projects/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Download dependence[cudaerror] from http://paddlepaddledeps.bj.bcebos.com/cudaErrorMessage.tar.gz
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - done
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - done
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 0.0.0
-- Found CUDA: /usr/local/cuda (found version "10.2") 
-- Cannot find CUPTI, GPU Profiling is incorrect.
-- On inference mode, will take place some specific optimization.
-- commit: 2a7c2cf8f3
-- branch: release/2.0
-- Configuring done
-- Generating done
-- Build files have been written to: /home/aiuser/projects/Paddle/build
然后继续执行以下指令：
![image](https://user-images.githubusercontent.com/32315802/211706171-079cbd0e-d5ab-4869-9444-8b7c8923dcbe.png)

编译（make）结果：
![image](https://user-images.githubusercontent.com/32315802/211706199-008ff42d-c4e7-4b6f-8f2a-93f6e55d7195.png)

**Comment by GuoxiaWang** [comment]
最后这张图，git status 是没有少文件的。 

错误在于编译时，拉取第三方库出现了网络问题，此时不用删除 build，调整一下网络，再执行编译就行

**Comment by qq-tt** [comment]
> 最后这张图，git status 是没有少文件的。
> 
> 错误在于编译时，拉取第三方库出现了网络问题，此时不用删除 build，调整一下网络，再执行编译就行

预编译结果那里有一句话：-- Cannot find CUPTI, GPU Profiling is incorrect. 这个真的没错么？

**Comment by JZZ-NOTE** [comment]
你好，我先了解下为什么要自己编译源码。不下载官方提供的预测库呢

**Comment by qq-tt** [comment]
> 你好，我先了解下为什么要自己编译源码。不下载官方提供的预测库呢

官方预测库可以GPU和TensorRT都加速么？在哪里？

**Comment by JZZ-NOTE** [comment]
可以的，提供了jetson的多个版本： https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html

**Comment by JZZ-NOTE** [comment]
如果问题得到解决，辛苦反馈一下哈

**Comment by qq-tt** [comment]
> 如果问题得到解决，辛苦反馈一下哈

好的，我先试试
