### ISSUE TITLE
version `CXXABI_1.3.8' not found 

### ISSUE THREAD

**Issue by wangbin11** [PaddlePaddle/Paddle#4969]
pip install paddlepaddle 之后，运行[image_classification](http://book.paddlepaddle.org/03.image_classification/)例子，
出现了 如下错误
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    main()
  File "train.py", line 30, in main
    paddle.init(use_gpu=with_gpu, trainer_count=3)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/__init__.py", line 66, in init
    import py_paddle.swig_paddle as api
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /usr/local/lib/python2.7/dist-packages/py_paddle/_swig_paddle.so)

gcc版本：
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with:  ../src/configure -v --with-pkgversion='Ubuntu 4.8.4-2ubuntu1 14.04.3' --with -bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.4 (Ubuntu 4.8.4-2ubuntu1~14.04.3) 
求教一下，这是什么原因，网上说得升级到4.9，升级到4.9，又会出现 version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference xxx

**Comment by luotao1** [comment]
> version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference xxx

gcc升级后，有没有`export LD_LIBRARY_PATH=/opt/gcc48/lib64`

**Comment by wangbin11** [comment]
后来觉得gcc环境配置有点繁琐，索性升级了16.04，解决了问题

**Comment by CuteCha** [comment]
@wangbin11 “索性升级了16.04”是什么意思？能不能解释一下？谢谢

**Comment by NicoleWongXiao** [comment]
还有一个可能的原因是还没有切换anaconda 的环境，比如我的paddle是安装在py36环境下的， base环境里没有 ， 在source activate py36之后再python train.py就没错误了。
