### ISSUE TITLE
Infershape  Question

### ISSUE THREAD

**Issue by wanx7130** [PaddlePaddle/Paddle#49719]
1、逻辑Op输出数据类型编译后和实际kernel执行不一致问题，影响整图的编译执行
看LogicalOp的默认输出数据类型是和输入一致，但实际执行时输出类型却都为bool
LogicalOp构图的代码段
![image](https://user-images.githubusercontent.com/30257601/211706065-c6fdbec0-1373-49a3-b738-651c4db47bd1.png)
代码中也未见到infer dtype的动作
kernel执行的时候，输出却直接申请的是bool类型
![image](https://user-images.githubusercontent.com/30257601/211706508-03f5ba31-71a9-4369-833c-341511ce59a3.png)

2、bipartite_match infershape和实际running时shape不匹配问题
结果如下：
<img width="849" alt="企业微信截图_16734041599363" src="https://user-images.githubusercontent.com/30257601/211707132-33de2887-5d83-4e85-bff3-13946d65ef85.png">

有点confuse。。。

**Comment by zhangbo9674** [comment]
你好，收到上述问题，我们会尽快对上述算子进行分析
