### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by ming-book** [PaddlePaddle/Paddle#49713]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.
![image](https://user-images.githubusercontent.com/23448349/211694511-10971af8-ff41-47e4-a099-0cfb4a30fb2f.png)

**Comment by zhangbo9674** [comment]
你好，应该前面还有其他报错日志，可以查看一下对应目标文件没有生成的原因是什么。此外，下面还提示了too many open files，可能是ulimit的原因，可以设置大一些。
