### ISSUE TITLE
deepcopy model深拷贝模型

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/Paddle#49764]
### 需求描述 Feature Description

如何复制一个和原始模型A一模一样的模型A1,包括模型定义和权重值？
背景：复制一个备份模型A1，修改其中的特定层的前向方法，如更改bn计算方式。
直接使用deepcopy复制报一下错误，请问有其他替换方案么？
![image](https://user-images.githubusercontent.com/20673237/211970232-081d9653-a97e-4a96-9244-8f1b2bdcc1ed.png)

**Comment by AnnaTrainingG** [comment]
1. 方法一：尝试save api保存模型再重新load
2. 方法二：可以参考这个https://github.com/PaddlePaddle/Paddle/issues/25657 使用set_value的方式进行
