### ISSUE TITLE
使用develop分支源码构建aarch64架构的包，打完之后包版本显示0.0.0，请问修改哪部分代码可以修改版本

### ISSUE THREAD

**Issue by xuhao-excellent** [PaddlePaddle/Paddle#49789]
### 问题描述 Issue Description

使用develop分支源码构建aarch64架构的包，打完之后包版本显示0.0.0，安装完whl之后，pip list也显示paddle的版本为0.0.0，请问我应该如何解决这个问题，谢谢

### 版本&环境信息 Version & Environment Information

操作系统：统信UOSV20-服务器版
CPU：鲲鹏920
CPU架构：aarch64

**Comment by xuhao-excellent** [comment]
我是按照官网提供的鲲鹏打包文档来的，也打出来包了，但是版本是0.0.0

**Comment by ronny1996** [comment]
你好，可以在执行cmake命令前export PADDLE_VERSION=xxx，填写你想要显示的版本，否则会根据git tag信息生成，没有的话就是0.0.0

**Comment by xuhao-excellent** [comment]
> 你好，可以在执行cmake命令前export PADDLE_VERSION=xxx，填写你想要显示的版本，否则会根据git tag信息生成，没有的话就是0.0.0

好的，我试一下，谢谢
