### ISSUE TITLE
源码编译安装develop分支后，找不到gaussian_random python api

### ISSUE THREAD

**Issue by Nepths** [PaddlePaddle/Paddle#49790]
### 问题描述 Please describe your issue

编译环境：docker镜像 registry.baidubce.com/paddlepaddle/paddle:latest-dev
编译命令：cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPY_VERSION=3.8 -DWITH_GPU=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release  -DWITH_MKL=OFF .. && make TARGET=HASWELL -j32
完成编译安装之后，调用paddle.fluid.layers.gaussian_random api，提示”AttributeError: module 'paddle.fluid.layers' has no attribute 'gaussian_random'“

**Comment by ronny1996** [comment]
你好，该api已经废弃，请使用paddle.normal https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/normal_cn.html#normal
