### ISSUE TITLE
期望paddle实现 torch的TORCH.LINALG.MATRIX_EXP函数

### ISSUE THREAD

**Issue by bit-pku-zdf** [PaddlePaddle/Paddle#49801]
### 需求描述 Feature Description

项目名称：语义索引优化
需求：paddle实现torch同样功能的函数：https://pytorch.org/docs/stable/generated/torch.linalg.matrix_exp.html#torch.linalg.matrix_exp

**Comment by bit-pku-zdf** [comment]
目标是静态图能使用这个op

**Comment by luotao1** [comment]
@bit-pku-zdf 这个题目在 [黑客松活动](https://github.com/PaddlePaddle/Paddle/issues/50629) 中，序号18（奖金8000），有兴趣的话可以来参加活动～
