### ISSUE TITLE
image.py  import cv2 bug

### ISSUE THREAD

**Issue by 143230** [PaddlePaddle/Paddle#49809]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/dataset/image.py   咨询一下paddle源码的一个问题，这里52行为什么要用进程方式去import cv2，而不是try catch ImportError这种？我们用了公司内应用加固方式运行，但是他们的程序统一返回0，造成这里失败了

**Comment by ronny1996** [comment]
https://github.com/PaddlePaddle/Paddle/pull/14781 好像是为了修numpy的一个bug
