### ISSUE TITLE
请问 paddle 有没有计划开发 torch.vmap 类似功能实现？

### ISSUE THREAD

**Issue by firestonelib** [PaddlePaddle/Paddle#49817]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）;
模型研发
 <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  
vmap 支持在单张GPU的多个CUDA核心上并行计算，以matmul为例，vmap [比for循环快了100倍](https://zhuanlan.zhihu.com/p/567662038)
<br /> 功能描述（请简单描述或设计这个功能）
vmap 实现了GPU对函数向量化并行计算的功能。可参考[torch.vmap](https://pytorch.org/tutorials/prototype/vmap_recipe.html#torch-vmap), [jax.vmap](https://jax.readthedocs.io/en/latest/_autosummary/jax.vmap.html)

**Comment by ronny1996** [comment]
你好，这个我反馈下
