### ISSUE TITLE
为什么paddle这个问题这么多版本了一直不修复呢:OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by youlingforever0328** [PaddlePaddle/Paddle#49829]
### bug描述 Describe the Bug

在data_loader里面启用多线程num_workers=4，运行不久后就会出现这个问题。
**_OSError: [Errno 24] Too many open files_**

![image](https://user-images.githubusercontent.com/57934209/212456653-cf1cd686-db16-4c56-b771-ba2008cf5cea.png)

```  File "/mnt/data4/stzheng/Conda/envs/paddle/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/mnt/data4/stzheng/Conda/envs/paddle/lib/python3.9/multiprocessing/popen_fork.py", line 64, in _launch
    parent_r, child_w = os.pipe()
OSError: [Errno 24] Too many open files
Exception in thread Thread-43:
Traceback (most recent call last):
  File "/mnt/data4/stzheng/Conda/envs/paddle/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 623, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/mnt/data4/stzheng/Conda/envs/paddle/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty

```

  我也搜过这个issue,有好几个一样的issue问题，还是2021年的，给出的解决办法都是修改
ulimit -n 改的尽量大一些。但是有时候改大了还是会出问题，况且有时候也不能一味地改打，这只是权宜之计。本来我用的paddle-gpu 2.2.2版本，出现了这个问题，还以为2.4.版本会解决这个问题，于是又安装了2.4版本，还是一样的问题。

为什么同样的用pytorch 在data_loader里面启用多线程num_workers=4运行多久都没问题呢，我服务器上两个框架都装了，但是更喜欢用paddle一些，最近发现这个问题，没有什么好的办法解决，训练到一半突然给你来个这个报错真的很头疼，相比之下pytorch就没有这个问题。但是我真的挺喜欢用paddle，希望官方可以好好解决一些这个问题，以及重视一下data_loader内存方面的问题（2.2版本），就这点来说，pytorch要更稳定些至少没遇到问题，个人非常支持国产框架，真的希望官方重视这个问题，看到同样的issue还是2021年的，到现在还没解决真的有点。。

这个问题2.2，2.4版本都有
环境简单说一下吧
CUDA 11.2 
python3.9 
paddle(2.2和2.4最新版)

**Comment by youlingforever0328** [comment]
再补充一个2.2版本的
``` 
File"/home/xxx/.conda/envs/xxx/lib/python3.9/multiprocessing/popen_fork.py", line 65, in _launch
OSError: [Errno 24] Too many open files
Exception in thread Thread-397:
Traceback (most recent call last):
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 583, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/home/xxx/.conda/envs/xxx/lib/python3.9/multiprocessing/queues.py", line 114, in get
    raise Empty
_queue.Empty
```

并且如其他相同的issue一样我只加载过一次数据集文件，生成全部的data,然后输入到dataset中。

`

    X = []
    Y = []
    for f in filelist:
        data = np.load(os.path.join(dir, f))
        X.append(data['x'][:, ch, :])
        Y.append(data['y'])
        print(f)
    
    X = np.concatenate(X, axis=0)
    Y = np.concatenate(Y, axis=0)

    print(X.shape, Y.shape)

    Xdataset = Raw_Dataset((X, Y))
    Xloader = DataLoader(Xdataset,
                        batch_size=batch_size,
                        shuffle=shuffle,
                        num_workers=num_workers)

    print('test_loader length: ', len(Xloader))
    if need_weight:
        ret = (Xloader, w)
    else:
        ret = Xloader
    return ret`

**Comment by CtfGo** [comment]
您好，感谢您的反馈，我们这边安排负责dataloader的同学跟进分析一下这个问题

**Comment by chenwhql** [comment]
您好，请问前面这个示例的数据方便提供下吗？我们运行分析一下

以及，num_workers设置的是多进程不是多线程，从现象来看，[[Errno 24] Too many open files:](https://stackoverflow.com/questions/18280612/ioerror-errno-24-too-many-open-files)是个环境相关的报错，并非paddle内部的报错提示，我们分析下是哪里需要补充完善下机制
