### ISSUE TITLE
Configure downloads Python modules that are already installed

### ISSUE THREAD

**Issue by yurivict** [PaddlePaddle/Paddle#49827]
### bug描述 Describe the Bug

Python-3.9

### 其他补充信息 Additional Supplementary Information

```
-- Found PythonInterp: /usr/local/bin/python3.9 (found version "3.9.16") 
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pyyaml in /usr/local/lib/python3.9/site-packages (5.4.1)
Collecting pyyaml
  Downloading PyYAML-6.0.tar.gz (124 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.0/125.0 kB 4.7 MB/s eta 0:00:00
  Installing build dependencies: started
^C*** Signal 2

[yuri@yv /usr/ports/misc/paddlepaddle]$ ^C
[yuri@yv /usr/ports/misc/paddlepaddle]$ pkg info | grep yaml
libyaml-0.2.5                  YAML 1.1 parser and emitter written in C
py39-yaml-5.4.1                Python YAML parser
```

> Defaulting to user installation because normal site-packages is not writeable

Why would it be writable? It is installed as a package.
Configure should just fail when it can't find required packages.
In this case it isn't clear what is missing at all.

**Comment by CtfGo** [comment]
@yurivict sorry for the late reply, the error hint was not reported by Paddle and it seems to be a common problem when installing package in python, you can refer to this link firstly [https://linuxhint.com/default-user-installation](https://linuxhint.com/default-user-installation/) to see if it can help
