### ISSUE TITLE
Design doc for performance analysis, testing, and tuning

### ISSUE THREAD

**Issue by mkliegl** [PaddlePaddle/Paddle#4982]
@ajkannan and I are going to look into ideas for making it easy to do performance analysis, testing, and tuning for Paddle (both at the individual operator level and for benchmarking whole networks). Please feel free to join the discussion and share your ideas here!

**Comment by ajkannan** [comment]
We will survey existing techniques for performance analysis, optimization, and testing on [this wiki page](https://github.com/PaddlePaddle/Paddle/wiki/Performance-Analysis-Survey) -- feel free to read and contribute:

**Comment by ajkannan** [comment]
This task is currently unstaffed.  When this becomes a high-priority, please feel free to pick this task up!

**Comment by typhoonzero** [comment]
I think we have https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/performance/profiler.md, so closing this issue for now, please feel free to reopen it.
