### ISSUE TITLE
PaddleInferTensor转paddle.Tensor怎么实现

### ISSUE THREAD

**Issue by dinglei0719** [PaddlePaddle/Paddle#49833]
### 请提出你的问题 Please ask your question

我现在用PaddleClas做文字分类
因为类型很多（7000类），所以大部分时间消耗在了结果的返回output_tensor.copy_to_cpu()上。
我注意到paddle.topk方法可以得到topk的结果，这正是我需要的，但是他的输入类型是paddle.Tensor。
请问有没有PaddleInferTensor转paddle.Tensor的方法（直接在GPU里边处理，不要读取到CPU中）
谢谢

**Comment by ZzSean** [comment]
你好，PaddleInferTensor是inference中的数据结构，目前框架中尚不支持PaddleInferTensor转Tensor

**Comment by dinglei0719** [comment]
> 你好，PaddleInferTensor是inference中的数据结构，目前框架中尚不支持PaddleInferTensor转Tensor

您好，谢谢。
那请问有什么方法在GPU中对PaddleInferTensor进行后处理么？主要是排序和切片。
我现在就是PaddleInferTensor结果比较大，所以output_tensor.copy_to_cpu()执行的时间很长。
想排序切片后再执行copy_to_cpu

**Comment by ZzSean** [comment]
能否将排序和切片这一过程放在模型组网中，即PaddleInferTensor输出前，这样输出的PaddleInferTensor应该就是你需要的大小了？

**Comment by dinglei0719** [comment]
> 能否将排序和切片这一过程放在模型组网中，即PaddleInferTensor输出前，这样输出的PaddleInferTensor应该就是你需要的大小了？

“放在模型组网中”的话，这个过程可以只在预测时使用么？
我是在用PaddleClas对图片进行7000分类，所以在训练过程中是没有这个排序和切片过程的，而是直接算Loss。
在预测是想减少copy_to_cpu的耗时（一多半都消耗在这个步骤了）猜想把切片和排序放到GPU里执行，只是为了减少copy_to_cpu需要传输的数据量。

**Comment by ZzSean** [comment]
Inference相关问题，请 @RichardWooSJTU 帮忙解答一下

**Comment by RichardWooSJTU** [comment]
> “放在模型组网中”的话，这个过程可以只在预测时使用么

可以在训练结束之后（或者加载pretrain ckpt之后）再封装一个function或者Layer， 调用jit.to_static/jit.save 保存推理模型即可。PaddleInference仅设计为推理引擎，不提供计算类API
