### ISSUE TITLE
Add ability to control operator dependency in the block

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#4983]
There are lot of instances where we need to add control information to the operators. For example, we would want to execute some operators only after some other operators have been been executed. 

For example, this is needed for Adam and Adamax Optimizer. There can be many more instances. In such cases something like [`tf. control_dependencies `](https://www.tensorflow.org/api_docs/python/tf/control_dependencies) might be useful.

**Comment by Superjom** [comment]
In the short run, we didn't have any plan to make the operators parallel, the control operators are only needed in parallel scenarios?

**Comment by jacquesqiao** [comment]
In the current design, we use input/output and order of op to know how to execute all the operators, but sometimes, ops do not have relation with input/output, but just have a dependency relation logically.

**Comment by wangkuiyi** [comment]
I think the current executor doesn't yet support asynchronous execution -- operators in `BlockDesc` are executed one-by-one -- each operator starts after all previous operators complete.  This implies bad performance but simplifies the synchronization.  

We will need to add `tf.control_dependencies` as you reminded after the Nov release.

**Comment by typhoonzero** [comment]
@abhinavarora @reyoung can we close this issue now, I think this is done by SSA graph currently.

**Comment by jacquesqiao** [comment]
Can SSA executor do backtrace dependency analyze?
