### ISSUE TITLE
请问paddle框架是否支持导出网络中间层生成的特征图？

### ISSUE THREAD

**Issue by Yuuchuin** [PaddlePaddle/Paddle#49834]
问题同上，劳烦解答，谢谢

**Comment by ZzSean** [comment]
你好，如果您使用的是动态图，那直接将中间结果copy到CPU进行保存即可

**Comment by Yuuchuin** [comment]
您好，请问您所述的操作涉及了哪些接口，或者有相关的文档嘛？paddle官方的文档没有找到相关的内容。paddle新手

**Comment by Yuuchuin** [comment]
> 你好，如果您使用的是动态图，那直接将中间结果copy到CPU进行保存即可

您好，请问您所述的操作涉及了哪些接口，或者有相关的文档嘛？paddle官方的文档没有找到相关的内容。

**Comment by ZzSean** [comment]
如果是要保存中间层的特征图，那将要保存的Tensor转为numpy，如想要保存的Tensor为x，
1. x.numpy();
2. 然后使用numpy.save就可以将其保存了

如果是保存模型中的某一参数，可以参考这里https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/save_cn.html#paddle-load

**Comment by zh-hike** [comment]
> 

<img width="481" alt="image" src="https://user-images.githubusercontent.com/57249890/212535559-598fe2ca-f117-493d-9777-49f2784e4b5f.png">
可以尝试下，支持保存多个中间层的特征
