### ISSUE TITLE
在vs2022下面编译推理代码时出现：需要有 dll 接口由 class“paddle_infer::Tensor”的客户端使用

### ISSUE THREAD

**Issue by Dandelion111** [PaddlePaddle/Paddle#49841]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/48303408/212538179-b5449ab4-4661-489f-ab76-806f07b37f18.png)

**Comment by ZzSean** [comment]
你好，我看Issue描述中的log截图，这个应该是编译过程中的warning信息，不是报错，所以应该不影响编译的
