### ISSUE TITLE
ExternalError: CUDA error(700), an illegal memory access was encountered

### ISSUE THREAD

**Issue by xujili8691** [PaddlePaddle/Paddle#49897]
### 问题描述 Issue Description

服务器安装paddlepaddle环境安装完成，测试paddle.utils.run_check()的时候出现 ExternalError: CUDA error(700), an illegal memory access was encountered. 问题。

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.1
Paddle With CUDA: True
OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.9.13
CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: N/A
Nvidia driver version: 515.48.07
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3080 Ti
GPU 1: NVIDIA GeForce RTX 3080 Ti
GPU 2: NVIDIA GeForce RTX 3080 Ti
GPU 3: NVIDIA GeForce RTX 3080 Ti

****************************************

**Comment by xujili8691** [comment]
ExternalError: CUDA error(700), an illegal memory access was encountered. 
      [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:252)
      [operator < fetch_v2 > error]

**Comment by thisjiang** [comment]
Hi~请问您的安装命令是`python -m pip install paddlepaddle-gpu==2.4.1.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`么？

**Comment by xujili8691** [comment]
是的

**Comment by xujili8691** [comment]
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)
  [operator < fc > error]

**Comment by thisjiang** [comment]
麻烦看看`nvcc --version`版本是正确的么？

**Comment by xujili8691** [comment]
是正确的11.7

**Comment by thisjiang** [comment]
Hi~参考这个issue: https://github.com/PaddlePaddle/Paddle/issues/47749 ，这是paddle 调用cublas底层库时的报错，根据 Cublas官方document 解释，这个和硬件驱动版本和 cublas 是否正确安装相关，不是Paddle调用时入参的问题。可以参考下文档https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#id4 ：
<img width="912" alt="image" src="https://user-images.githubusercontent.com/31386411/213099398-a0993e7d-d17c-43ae-af8f-d635590994b7.png">

**Comment by xujili8691** [comment]
ExternalError: CUDA error(700), an illegal memory access was encountered.
[Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:252)
[operator < fetch_v2 > error]
这个问题呢

**Comment by HustleOoo** [comment]
我也遇到了这个问题，请问下怎么解决的？

**Comment by JP-Leite** [comment]
Encounter a similar error when running a custom EN dataset on Ernie-Layout. No issue with testing after install using: 

```
import paddle.fluid as fluid
fluid.install_check.run_check()
```

**Comment by aixuedegege** [comment]
> fluid.install_check.run_check()

hi，did you solve "CUDA error(700), an illegal memory access was encountered." this issue?

**Comment by aixuedegege** [comment]
@JP-Leite hi，did you solve "CUDA error(700), an illegal memory access was encountered." this issue?

**Comment by xinj7** [comment]
anyone solved the issue?

**Comment by ZishuaiW** [comment]
@xujili8691 你好， ExternalError: CUDA error(700), an illegal memory access was encountered. 这个问题解决了吗，能分享一下是怎么解决的吗？
