### ISSUE TITLE
Do/don't need targets when executing a ProgramDesc

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#4989]
In the design of optimizers
https://github.com/PaddlePaddle/Paddle/blame/e9e0d7d774d2fa73a7621ee0bfc5f87718115cc0/doc/design/optimizer.md#L44-L55

we said that `optimizer.minimize` needs to return a list of optimization operators (optimizers), which will go into the invocation of `session.run`.

My point is that our `ProgramDesc` should be sufficient to describe a program so we don't need to specify any targets.

To verify my idea, let's try to implement a model -- which has multiple CNN layers, each has its own parameter, which is optimized using a unique cost.  Here is the Python program in my mind that generates the `ProgramDesc` message to run in each iteration.

```python
x = layer.data("image")

l1 = layer.data("label_1")
l2 = layer.data("label_2")
l3 = layer.data("label_3")

f1, P1 = layer.cnn(x)
f2, P2 = layer.cnn(f1)
f3, P3 = layer.cnn(f2)

c1 = layer.mse(f1, l1)
c2 = layer.mse(f2, l2)
c3 = layer.mse(f3, l3)

optimize(l1, parameters=[P1])
optimize(l2, parameters=[P2])
optimize(l3, parameters=[P3])
```

**Comment by helinwang** [comment]
It's likely that the user want to optimize `l1` only in the first 1000 steps, `l2` only in the send 1000 steps, `l3` only in the third 1000 steps.

**Comment by wangkuiyi** [comment]
I got your point @helinwang .Such a requirement depends on representing the training loop with a WhileOp.  Before we have the WhileOp, we cannot support it with `ProgramDesc` without targets. And I think we'd rather to create the WhileOp ASAP instead of implementing targets in execution -- for this case.  I am thinking of GAN.

**Comment by jacquesqiao** [comment]
https://github.com/wiseodd/generative-models/blob/master/GAN/dual_gan/dualgan_tensorflow.py#L173
