### ISSUE TITLE
中断服务推理以后，如何释放对应显存？

### ISSUE THREAD

**Issue by boreas-l** [PaddlePaddle/Paddle#49905]
### 请提出你的问题 Please ask your question

在使用paddlegan部署相应服务以后，在客户端进行post请求的时候，在请求还没返回结果的时候强行中断，会发现相应线程所占用的显存并没有释放。然后多次执行中断操作以后，显存就会被占满，无法进行正常推理。

**Comment by thisjiang** [comment]
Hi~[PaddleGAN](https://github.com/PaddlePaddle/PaddleGAN)相关问题欢迎前往https://github.com/PaddlePaddle/PaddleGAN/issues 提issue
