### ISSUE TITLE
paddlepaddle-gpu中paddle.cast转换tensor，int64，输出的tensor值被全部置0

### ISSUE THREAD

**Issue by yating0823** [PaddlePaddle/Paddle#49915]
## 调用paddle.cast对tensor做int64类型的转换，输出tensor的值被全部置0

```
import paddle

a =  [[ 296 ,  438 , 18016, -100 , -100 , -100 ],
        [-100 , -100 , -100 , 18016,  8   ,  122 ],
        [18021,  129 ,  861 , -100 , -100 , -100 ]]
a_tensor = paddle.to_tensor(a)
a_tensor = paddle.cast(a_tensor, 'int64')
print("++++++++++++++++++paddle.cast: ", a_tensor)
```
### 预期输出值：
```
++++++++++++++++++paddle.cast:  Tensor(shape=[3, 6], dtype=int64, place=Place(cpu), stop_gradient=True,
       [[ 296 ,  438 , 18016, -100 , -100 , -100 ],
        [-100 , -100 , -100 , 18016,  8   ,  122 ],
        [18021,  129 ,  861 , -100 , -100 , -100 ]])
```
### 实际输出值：
```
++++++++++++++++++paddle.roll:  Tensor(shape=[3, 6], dtype=int64, place=CUDAPlace(0), stop_gradient=True,
       [[0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]])
```

### 测试过的paddlepaddle-gpu版本
2.4.1 / 2.3.0 / 2.0.0

### paddlepaddle版本
没有这类问题

### 其他补充信息 Additional Supplementary Information

我是在PaddleNLP-develop/examples/information_extraction/DuUIE的项目调试中发现这个bug的。

**Comment by yating0823** [comment]
GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2

**Comment by wangzhen38** [comment]
![截屏2023-01-18 下午2 03 11](https://user-images.githubusercontent.com/41941775/213096520-57a848d1-d449-4084-b60a-a48ab8240b81.png)
换这个版本试试呢，`python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

**Comment by yating0823** [comment]
试过了，已解决。非常感谢您的回复。

**Comment by yating0823** [comment]
试过了 已解决 非常感谢您的回复

**Comment by yating0823** [comment]
### Could not load library libcublasLt.so.10

您好，我按照你们的建议，安装了paddlepaddle-gpu==2.4.1.post112，然后，报缺少libcudart.so.11.0， 于是我卸载了cuda toolkit 10.2 重新安装了 cuda toolkit 11.0， 解决了上面的问题，但是另一个问题又出现了，在运行整个项目的时候，报了：
`Could not load library libcublasLt.so.10. Error: libcublasLt.so.10: cannot open shared object file: No such file or directory`
这个libcublasLt.so.10似乎是cuda 10版本的一个工具类

### 我是否需要在ubuntu上同时安装cuda 11.0 和 cuda 10.2 版本的toolkit？

**Comment by yating0823** [comment]
> ![截屏2023-01-18 下午2 03 11](https://user-images.githubusercontent.com/41941775/213096520-57a848d1-d449-4084-b60a-a48ab8240b81.png) 换这个版本试试呢，`python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

### 报 Could not load library libcublasLt.so.10 错误

您好，我按照你们的建议，安装了paddlepaddle-gpu==2.4.1.post112，然后，报缺少libcudart.so.11.0， 于是我卸载了cuda toolkit 10.2 重新安装了 cuda toolkit 11.0， 解决了上面的问题，但是另一个问题又出现了，在运行整个项目的时候，报了：
`Could not load library libcublasLt.so.10. Error: libcublasLt.so.10: cannot open shared object file: No such file or directory`
这个libcublasLt.so.10似乎是cuda 10版本的一个工具类

### 我是否需要在ubuntu上同时安装cuda 11.0 和 cuda 10.2 版本的toolkit？

**Comment by wangzhen38** [comment]
> 

看起来你项目中似乎用到了cuda10相关的依赖，我这里提供两个建议：

1. 重新安装下cuda10.2对应的paddle版本`python -m pip install paddlepaddle-gpu==2.3.2 -i https://pypi.tuna.tsinghua.edu.cn/simple`
3. 针对最新报错，参考下这个[解决方案](https://stackoverflow.com/questions/70268140/could-not-load-dynamic-library-libcublaslt-so-11-dlerror-libcublaslt-so-11)
