### ISSUE TITLE
CompileTimeInferShapeContext::HasInput needs to handle empty input

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#4992]
Suspect bug in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.h#L327

Traceback:
```
======================================================================
ERROR: test_check_output (__main__.TestCropOp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "../python/paddle/v2/framework/tests/test_crop_op.py", line 54, in test_check_output
    self.check_output()
  File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 350, in check_output
    self.check_output_with_place(place, atol)
  File "/paddle/python/paddle/v2/framework/tests/op_test.py", line 302, in check_output_with_place
    attrs=self.attrs if hasattr(self, "attrs") else dict())
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/framework/framework.py", line 351, in append_op
    op = Operator(self, op_desc, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/framework/framework.py", line 259, in __init__
    self.desc.infer_shape(self.block.desc)
EnforceNotMet: Input Y cannot be found in Op crop at [/paddle/paddle/framework/op_desc.cc:43]
PaddlePaddle Call Stacks:
0       0x7f9976d09706p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 582
1       0x7f9976d92604p paddle::framework::OpDescBind::Input(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const + 324
2       0x7f9976d96766p paddle::framework::CompileTimeInferShapeContext::HasInput(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const + 54
```

**Comment by jacquesqiao** [comment]
there are two problems about this issue, 

1. one is that, when the test framework passes a OpDesc to CPP, it need to make sure all the inputs/outputs are in the Desc, if user does not pass one to it, just create a empty vector. @tonyyang-svail 
2. The other one is that, if use call HasInput() in InferShapeContext, when Input(xx) return a empty vector, it need to return false, but not enforce the return size is one. @jacquesqiao

**Comment by tonyyang-svail** [comment]
@jacquesqiao I will make sure the first bullet point at `class Operator(object)`

**Comment by chengduoZH** [comment]
@jacquesqiao
I also encountered this problem in the process of developing [context_project_op](https://github.com/PaddlePaddle/Paddle/pull/4814/files#diff-f5908b17334053d717ae563502adc568R24). In some cases, context_project_op doesn't need padding, and [PaddingData](https://github.com/PaddlePaddle/Paddle/pull/4814/files#diff-f5908b17334053d717ae563502adc568R37) should be empty.
