### ISSUE TITLE
nn.utils.remove_spectral_norm 

### ISSUE THREAD

**Issue by yt605155624** [PaddlePaddle/Paddle#49920]
### 需求描述 Feature Description
paddle 没有类似 pytorch 中 nn.utils.remove_spectral_norm 的操作，参考: 
https://github.com/pytorch/pytorch/blob/dfbdfb276eb5b0492b39036f1c49c196b826587f/torch/nn/utils/spectral_norm.py#L286

**Comment by wangzhen38** [comment]
收到，我稍后反馈给框架同学～
