### ISSUE TITLE
wav2lip 生成头像有背景

### ISSUE THREAD

**Issue by wwh5441** [PaddlePaddle/Paddle#49956]
### 请提出你的问题 Please ask your question

wav2lip 生成的头像后有一个浅浅的背景，请问这个该如何去除掉？

**Comment by LielinJiang** [comment]
wav2lip确实存在这样的问题，可以看看是否接一个背景分割器。或者是否有新的优化wav2lip的算法

**Comment by wwh5441** [comment]
我们已经解决了，谢谢您

**Comment by wwh5441** [comment]
> wav2lip确实存在这样的问题，可以看看是否接一个背景分割器。或者是否有新的优化wav2lip的算法

我们已经解决了，谢谢您
