### ISSUE TITLE
求解：rtx3060 安装paddle失败 OSError: Invalid enum backend type `63`

### ISSUE THREAD

**Issue by gq67735578** [PaddlePaddle/Paddle#49964]
### 问题描述 Issue Description

系统：win11
显卡rtx3060 驱动显示： NVIDIA-SMI 528.02 Driver Version: 528.02 CUDA Version: 12.0
python 3.10.9
cuda：cuda_11.7.1_516.94_windows
cudnn：cudnn-windows-x86_64-8.6.0.163_cuda11-archive
paddlepaddle：pip安装  版本：gpu==2.4.1.post117

安装完python和cuda后，将cudnn解压
1、把bin目录下的.dll全部复制到 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin
2、把\cuda\include\cudnn.h复制到 C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\include
3、把\cuda\lib\x64\cudnn.lib复制到C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\lib\x64
然后安装paddle（GPU cuda11.7），安装完成后验证就出现 OSError: Invalid enum backend type 63错误，请问下应该怎么解决。谢谢！

![nvidia-smi](https://user-images.githubusercontent.com/123165660/213683670-3c194002-68c8-4758-b1fc-b57164b8b279.jpg)

![nvcc -V](https://user-images.githubusercontent.com/123165660/213683912-094ec5b4-ba88-48f6-839a-5e587bc7a9bd.jpg)

下面是安装信息：
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec 6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0120 00:02:58.819399 21836 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
W0120 00:02:58.828402 21836 gpu_resources.cc:91] device: 0, cuDNN Version: 8.6.
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "H:\AI\paddle\venv\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
_run_dygraph_single(use_cuda, use_xpu, use_npu)
File "H:\AI\paddle\venv\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
linear_out = linear(input_tensor)
File "H:\AI\paddle\venv\lib\site-packages\paddle\fluid\dygraph\layers.py", line 948, in __call__
return self.forward(*inputs, **kwargs)
File "H:\AI\paddle\venv\lib\site-packages\paddle\nn\layer\common.py", line 175, in forward
out = F.linear(
File "H:\AI\paddle\venv\lib\site-packages\paddle\nn\functional\common.py", line 1882, in linear
return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `63`.

### 版本&环境信息 Version & Environment Information

paddle： version 2.4.1
cpu：E5-2670 支持AVX
GPU：RTX3060 12G  （驱动支持最高CUDA12.0.133）（安装cuda_11.7.1_516.94）（cudnn-windows-x86_64-8.6.0.163_cuda11） 
系统：win11
python：3.10.9
安装方式：pip使用cuda11.7安装链接
详细安装信息在上文中有描述

**Comment by LielinJiang** [comment]
感谢像是你的cuda是12.0的版本，安装的paddle是11.7的版本。我们目前应该还没有适配12.0。看看能否cuda降下版本

**Comment by gq67735578** [comment]
您好 非常感谢您这么晚还帮我解决问题显卡驱动安装好后是显示支持的cuda最高版本是12.0&nbsp; &nbsp;cuda我单独装的是11.7&nbsp; 我找个旧版本的显卡驱动试试






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月20日(星期五) 晚上11:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 求解：rtx3060 安装paddle失败 OSError: Invalid enum backend type `63` (Issue #49964)





 
感谢像是你的cuda是12.0的版本，安装的paddle是11.7的版本。我们目前应该还没有适配12.0。看看能否cuda降下版本

**Comment by gq67735578** [comment]
您好 我降了显卡驱动程序版本后 仍然是这个错误。。。







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年1月20日(星期五) 晚上11:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 求解：rtx3060 安装paddle失败 OSError: Invalid enum backend type `63` (Issue #49964)





 
感谢像是你的cuda是12.0的版本，安装的paddle是11.7的版本。我们目前应该还没有适配12.0。看看能否cuda降下版本

**Comment by gq67735578** [comment]
![1](https://user-images.githubusercontent.com/123165660/213847297-b577d981-0c8b-4511-be0e-5f46ffe30204.jpg)

**Comment by LielinJiang** [comment]
收到，那这个错误看起来确实不是版本不匹配的问题。可能需要等节后找负责安装的同学帮忙看下了

**Comment by gq67735578** [comment]
好的 谢谢

**Comment by gq67735578** [comment]
请问下 这算安装成功还是没成功
![2](https://user-images.githubusercontent.com/123165660/215268514-0ce82e99-38b8-4118-92fb-e54eac0e6c22.png)

**Comment by LielinJiang** [comment]
最前面那个显示是paddle好像还是有问题，fluid的部分后续会删除，目前已经不建议使用了

**Comment by gq67735578** [comment]
好的 有时间时候麻烦帮我看下 谢谢
显卡显卡驱动也降到11.7 
cuda 和cudnn的版本也换了试过  
paddle也换了2.4.0试过  
gpu版本也换了11.6试过  
全是‘63’错误  实在装不上去。。。

**Comment by LielinJiang** [comment]
问了下负责的同学，可以先试下cpu的包或者11.2的

**Comment by gq67735578** [comment]
cpu版的安装了 报OSError: Invalid enum backend type ‘64’  。。
![1](https://user-images.githubusercontent.com/123165660/215325774-f18f76e7-4dac-4465-b7ba-23b22b6e74ca.png)

**Comment by LielinJiang** [comment]
好吧，负责windows安装的同学要后天才回来。麻烦再等等

**Comment by gq67735578** [comment]
好的 谢谢   

CPU版用2.3.2就不报错了
2.4.0和2.4.1 都报 OSError: Invalid enum backend type ‘64’

GPU版的2.3.2 没有cuda11.7的 就没试了
2.4.0和2.4.1 都报 OSError: Invalid enum backend type ‘63’

**Comment by zhwesky2010** [comment]
@gq67735578 你好，这个 Invalid enum backend type 63. 在某些机器上会触发，是一个已知bug。我们会定位并修复

**Comment by WesternTrail** [comment]
同样的错误，请尽快解决！！！

系统：win11
显卡：tesla_p40 
python 3.8.0
cuda：cuda 11.6.0
cudnn：cudnn 8.1.1.3
paddlepaddle：pip安装 版本：gpu==2.4.1.post116

- 使用`python -c "import paddle; conv = paddle.nn.Conv1D(3, 1, 1); ts = paddle.to_tensor([[[1.1], [4.5], [1.4]]], dtype='float32'); print(conv(ts))`验证安装时报错：

![image](https://user-images.githubusercontent.com/28615285/224469940-b8cb74ba-2863-42ef-985b-fcfec9df5cce.png)

- 使用 `python -c "import paddle;paddle.utils.run_check()"`验证安装依然如上述报错

- 使用 `python -c "import paddle.fluid as fluid;fluid.install_check.run_check()"`时正常

![image](https://user-images.githubusercontent.com/28615285/224470140-6603b44a-3cd9-43b2-a192-902597008491.png)

- 运行 `paddleRS/tutorials/train/change_detection/bit.py`时依然出现上述63错误

@zhouwei25 @LielinJiang

**Comment by WesternTrail** [comment]
@zhouwei25

**Comment by WesternTrail** [comment]
同样的错误，请尽快解决！！！

系统：win11
显卡：tesla_p40 
python 3.8.0
cuda：cuda 11.6.0
cudnn：cudnn 8.1.1.3
paddlepaddle：pip安装 版本：gpu==2.4.1.post116

- 使用`python -c "import paddle; conv = paddle.nn.Conv1D(3, 1, 1); ts = paddle.to_tensor([[[1.1], [4.5], [1.4]]], dtype='float32'); print(conv(ts))`验证安装时报错：

![image](https://user-images.githubusercontent.com/28615285/224469940-b8cb74ba-2863-42ef-985b-fcfec9df5cce.png)

- 使用 `python -c "import paddle;paddle.utils.run_check()"`验证安装依然如上述报错

- 使用 `python -c "import paddle.fluid as fluid;fluid.install_check.run_check()"`时正常

![image](https://user-images.githubusercontent.com/28615285/224470140-6603b44a-3cd9-43b2-a192-902597008491.png)

- 运行 `paddleRS/tutorials/train/change_detection/bit.py`时依然出现上述63错误

@zhouwei25 @LielinJiang

**Comment by zhwesky2010** [comment]
@gq67735578  你好，该问题已修复，可以安装最新的develop版本whl包试试
`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html`
