### ISSUE TITLE
【demo情感分析 Ubuntu 14.04.5 LTS】执行./get_imdb.sh获取数据脚本问题

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#500]
1.	在进行数据准备时，如果系统为新系统，且没有安装zip解压工具时，执行./get_imdb.sh 下载的原始数据中有.zip的压缩包，脚本执行最后会报错，避免用户执行后才发现问题。
是否可以进行如下修复
1.	在文档中说明需要预先安装zip解压软件
2.	或直接加which unzip 并进行判断$?，如果不存在直接提示用户进行安装
![image](https://cloud.githubusercontent.com/assets/6229206/20378425/f75fbe48-acd0-11e6-8e4c-b307dde1390c.png)

**Comment by backyes** [comment]
@wen-bo-yang   

脚本里提示安装即可。对这些原始的常用工具，感觉不必文档赘述，脚本完善一些us'er'-friendly的提示即可。

**Comment by luotao1** [comment]
目前这样也可以把，感觉`unzip: command not found`也蛮清楚的了

**Comment by wen-bo-yang** [comment]
因为执行该脚本后需要一定时间，执行完后才提示用户需要安装unzip感觉不太友好

**Comment by luotao1** [comment]
因为unzip是最基本的命令，如果每个文档和脚本都要提示的话，会很冗余。
