### ISSUE TITLE
paddle多gpu支持时能否安装方法简单点

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle#50038]
### 需求描述 Feature Description

我们使用的是内网机器，无法顺畅连接internet,安装nccl不方便，还用是会使用conda环境下paddle的多gpu,就像pytorch或者tensorflow,都是不需要在装nccl的，paddle能否解决一下呢，

**Comment by JZ-LIANG** [comment]
已经收录，待反馈给PM 同事
