### ISSUE TITLE
官网安装指令错误

### ISSUE THREAD

**Issue by bigsk05** [PaddlePaddle/Paddle#50030]
### 文档链接&描述 Document Links & Description

选择2.4Stable Linux Pip CUDA11.6时生成了以下命令：
`python -m pip install paddlepaddle-gpu==2.4.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`
实际上不存在2.4.1.post116 应为 2.4.1，即：
`python -m pip install paddlepaddle-gpu==2.4.1 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`

**Comment by huangjun12** [comment]
https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 看这个网址里应该是有post116后缀的哈
