### ISSUE TITLE
conda环境安装paddle2.4.1 nccl不支持

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle#50037]
### 1、paddle2.3.2 gpu 
ubuntu 18.04 cuda driver 11.4
之前安装的paddle2.3.2使用conda环境命令如下：
`conda install paddlepaddle-gpu==2.3.2 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

conda install -c nvidia cuda-nvcc_linux-64

conda install nccl -c conda-forge

`
安装完成后执行
`paddle.utils.run_check()`
显示是支持多GPU的
### 2、paddle 2.4.1 gpu
同一台机器，再创建一个新的conda环境，命令相似如下：
`
conda install paddlepaddle-gpu==2.4.1 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/

conda install -c nvidia cuda-nvcc_linux-64

conda install nccl -c conda-forge

`
安装完成后执行
`paddle.utils.run_check()`
显示只支持单gpu.
### 版本&环境信息 Version & Environment Information

ubuntu 18.04 cuda driver 11.4 python3.9

**Comment by JZ-LIANG** [comment]
可能有两个原因：
paddle2.4 多卡需要 nccl 2.7 + 版本，请核对检查
新conda 环境中nccl 环境变量未正确配置

可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html#erkaishianzhuang

**Comment by DLlearn** [comment]
@JZ-LIANG 是这样，paddle2.3同样需要nccl2.7以上的，另外，conda安装nccl 是用的 conda install -c nvidia cuda-nvcc_linux-64  conda install nccl -c conda-forge
 这种命令，这个nccl只在当前环境中生效，也不需要别外设置环境变量的，并非官网的nccl安装方法，官网那种适合系统全局安装paddle吧。我是这样理解的哈，同样的命令，只是换个版就不成功，感觉是有点问题的。
