### ISSUE TITLE
Significant performance drop in BF16 models

### ISSUE THREAD

**Issue by pmajchrzak** [PaddlePaddle/Paddle#50032]
### 问题描述 Please describe your issue

Commit: https://github.com/PaddlePaddle/Paddle/commit/7f0eb2e3e98d8ace072a33c65e39aef4443d2035 causes a significant performance drop in **BF16** models:
- mobilenetV1
- mobilenetV2
- mobilenetV3
- googlenet
- resnet50

Tests was performed on two machines:
#### CPX:
```
           Turbo: OFF
            Name: Intel(R) d on(R) Gold 6348H CPU @ 2.30GHz
           Model: 85
          Family: 6
         Sockets: 4
Cores per socket: 24
Threads per core: 2
     CPU MHx min: 1000.0000
     CPU MHx max: 4200.0000
       cache L1d: 32K
       cache L1i: 32K
        cache L2: 1024K
        cache L3: 33792K
```
#### SPR:
```
           Turbo: OFF
            Name: Genuine Intel(R) CPU 0000%@
           Model: 143
          Family: 6
         Sockets: 2
Cores per socket: 60
Threads per core: 2
     CPU MHx min: 800.0000
     CPU MHx max: 3500.0000
       cache L1d: 48K
       cache L1i: 32K
        cache L2: 2048K
        cache L3: 115200K
```
#### RUN COMMAND:
```
KMP_AFFINITY=granularity=fine,compact,1,0 KMP_BLOCKTIME=1 OMP_NUM_THREADS=1   /usr/bin/time -v  /logs_paddle_paddle/build/paddle/fluid/inference/tests/api/test_analyzer_bfloat16_image_classification --infer_data=/data/PaddlePaddle/datasets/imagenet_int8/int8_full_val.bin --infer_model=/data/PaddlePaddle/pp_models/MobileNetV3_large_x1_0_infer --enable_fp32=false --enable_bf16=true --paddle_num_threads=1 --with_accuracy_layer=false  --batch_size=1   --iterations=100
```
#### CMAKE parameters:
```
-DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_MKLDNN=ON -DWITH_TESTING=ON -DWITH_PROFILER=OFF -DWITH_STYLE_CHECK=OFF -DON_INFER=ON -DWITH_INFERENCE_API_TEST=ON -DPY_VERSION=3.6
```
#### Environment
```
            OS: Ubuntu18.04 with mkldnn 
 cmake version: 3.20
      Compiler: GCC 8.2.0
```

#### Obtained results:
CPX:
![image](https://user-images.githubusercontent.com/10847947/214847784-8b4b457b-7e62-4365-b40a-2a35a479467f.png)

SPR:
![image](https://user-images.githubusercontent.com/10847947/214847897-681e8186-b437-43a9-b1c5-41035602cd6b.png)

**Comment by zyfncg** [comment]
@pmajchrzak Hello~ I'm not sure whether this PR ([#50283](https://github.com/PaddlePaddle/Paddle/pull/50283)) could solve the problem of performance regression, because I have no machine which supports `avx512_bf16` and the test results on my platform is inaccurate. Could you please test this PR ([#50283](https://github.com/PaddlePaddle/Paddle/pull/50283)) on your machines to check whether this PR could solve the issue?
