### ISSUE TITLE
paddle.linalg.corrcoef的计算结果不对称

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/Paddle#50048]
### bug描述 Describe the Bug

相关系数矩阵不对称。

```
import paddle 
print(paddle.__version__)

y = list(range(10000))
def acf(y, order):
    inputs = []
    for i in range(order+1):
        inputs.append(y[i:len(y)-(order-i)])
    inputs = paddle.to_tensor(inputs).astype('float32')
    outputs = paddle.linalg.corrcoef(inputs)
    return outputs
x = acf(y,5)
```

![image](https://user-images.githubusercontent.com/83450930/215295108-3fbc8d24-c503-4234-b20f-1db50da627b2.png)

**Comment by pangyoki** [comment]
你好，我复现了你的问题，这个bug会找相关API负责人（ https://github.com/PaddlePaddle/Paddle/pull/40690 ）修复，谢谢反馈。
另外，我测试只有cpu设备下才会有这个问题，gpu场景下数值应该正常吧？
<img width="670" alt="图片" src="https://user-images.githubusercontent.com/26408901/215325848-1c513eb1-ddcc-4327-996f-d656cf5d80f1.png">

**Comment by Liyulingyue** [comment]
> 你好，我复现了你的问题，这个bug会找相关API负责人（ #40690 ）修复，谢谢反馈。 另外，我测试只有cpu设备下才会有这个问题，gpu场景下数值应该正常吧？ <img alt="图片" width="670" src="https://user-images.githubusercontent.com/26408901/215325848-1c513eb1-ddcc-4327-996f-d656cf5d80f1.png">

你好，根据你的截图来看，gpu场景不正常鸭，它只保证了对角线为1，对称不同。

**Comment by luotao1** [comment]
@liqitong-a 可以帮忙看下这个问题么？

**Comment by AndPuQing** [comment]
numpy 其实也有该问题，输出的矩阵并非严格对称，[numpy.corrcoef](https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html#numpy.corrcoef):

```python
import numpy as np

print(np.__version__) # 1.23.2

xt = np.random.rand(30, 40)

r = np.corrcoef(xt, dtype="float32")
print(np.allclose(r, r.T, rtol=1e-8)) # False

print(np.count_nonzero(r != r.T)) # 300
for i in range(r.shape[0]):
    for j in range(r.shape[1]):
        if r[i][j] != r[j][i]:
            print(r[i][j], r[j][i])
```

**Comment by liqitong-a** [comment]
由于是在其他算子的基础上进行运算，所以和其他算子的精度也有关系，使用float64精度会高一些，使用float32cov算子也会有偏差。
```
import os
import paddle
import numpy as np

os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"

y = list(range(10000))
def acf(y, order):
    inputs = []
    for i in range(order+1):
        inputs.append(y[i:len(y)-(order-i)])

    t1 = np.array(inputs).astype('float32')
    print(np.cov(t1))
    t2 = paddle.to_tensor(inputs).astype("float32")
    print(paddle.linalg.cov(t2))

acf(y,5)
```

**Comment by luotao1** [comment]
> 1）使用float64精度会高一些；2）numpy 其实也有该问题，输出的矩阵并非严格对称

@Liyulingyue 看下这个问题是否解决了？

**Comment by Liyulingyue** [comment]
> > 1）使用float64精度会高一些；2）numpy 其实也有该问题，输出的矩阵并非严格对称
> 
> @Liyulingyue 看下这个问题是否解决了？

got it

但是我有个小问题，这种情况需要特意对齐吗？毕竟按照计算逻辑，对角线默认为1，对称元素应当相同？

**Comment by Liyulingyue** [comment]
64可以对齐
