### ISSUE TITLE
auto topology communication is awesome, is it open sourced?

### ISSUE THREAD

**Issue by Jack47** [PaddlePaddle/Paddle#50044]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）
auto topology communicaton is awesome and inspiring!
<img width="969" alt="image" src="https://user-images.githubusercontent.com/1720972/215259644-5db639c3-224b-43db-b10f-446beef2822c.png">

Question:

1. auto topology is illustrated by Figure 7 as below?

 <img width="872" alt="image" src="https://user-images.githubusercontent.com/1720972/215259690-38166039-dbee-4a99-94ea-1284103e3e88.png">
2. is it open sourced?
<img width="769" alt="image" src="https://user-images.githubusercontent.com/1720972/215259790-b23296da-bee8-4f04-a099-3fc3eb33599a.png">

3. is it implemented as nccl plugin? which we can select best topology through switches.

**Comment by JZ-LIANG** [comment]
@ForFishes   
invited the author of paper for this question

**Comment by ForFishes** [comment]
hi，The first question, this is not an automatic architecture, it is to adjust the communication according to the actual cluster architecture, which is currently implemented manually.
The second question is that part of the code of SE-MoE is open source, and part of the performance optimization is still being sorted out. https://github.com/PaddlePaddle/PaddleNLP/tree/develop/examples/language_model/moe
The third question is currently based on nccl2.8.4 version. As far as I know, higher nccl versions can realize adaptive topology perception. https://developer.nvidia.com/blog/doubling-all2all-performance-with-nvidia-collective-communication-library-2-12/

**Comment by Jack47** [comment]
Hi ForFishes, great thanks for your reply, I will check that nccl link.
