### ISSUE TITLE
验证paddle时导包出现错误

### ISSUE THREAD

**Issue by 258863** [PaddlePaddle/Paddle#50056]
### 请提出你的问题 Please ask your question

验证paddle安装时
ImportError: /home/wjn/anaconda3/lib/python3.9/site-packages/paddle/fluid/core_avx.so: undefined symbol: _dl_sym, version GLIBC_PRIVATE

**Comment by pangyoki** [comment]
请问你使用的是ubuntu22.04以上的版本吗？
这个是已知问题，现在已经解决了，你可以安装最新的2.4.1版本的Paddle试试。

**Comment by 258863** [comment]
我用的是ubuntu22.04但是刚刚又试了一下，海斯没有解决

**Comment by pangyoki** [comment]
paddle.__version__看下安装的paddle版本，确定安装的是2.4.1版本的paddle吗？

**Comment by 258863** [comment]
import paddle 时报错，无法使用paddle.__version__，但是确定是2.4.1版本

**Comment by pangyoki** [comment]
安装命令发我看下吧？建议pip uninstall之后再按官网命令pip install试试。
2.4.1版本应该没有`core_avx.so`了，应该叫`libpaddle.so`。

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/215425317-7032ce47-48db-48d1-80e8-62e60c89325d.png)
重新按照官方安装了，但是还是出现这样的错误

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/215425856-6adeece0-f84e-4973-bf9f-a369e1995574.png)
安装的是2.41的

**Comment by pangyoki** [comment]
现在的报错应该是另一个问题了，你可以`find / -name libcudart*' 找下你环境里的相关so文件在哪里，把这个so文件的路径加到LD_LIBRARY_PATH里看行不行。
另外，可以试下直接pip安装有没有问题，看是不是conda改变了相关的环境变量。

**Comment by 258863** [comment]
把这个so文件的路径加到LD_LIBRARY_PATH里也不行，又试了pip也一样

**Comment by zhiyuan1i** [comment]
我也是，按照官方使用 conda 的命令安装失败。
<img width="1063" alt="截屏2023-01-31 14 09 20" src="https://user-images.githubusercontent.com/31544054/215680275-646cb696-2061-4bec-b09b-cc60c3d8d648.png">
这几个都有问题，11.7 之前的版本是 import 就有问题，11.7 是 check 有问题
<img width="853" alt="image" src="https://user-images.githubusercontent.com/31544054/215681082-53e8bb08-3da9-49b4-bde5-cbc25570589e.png">

**Comment by pangyoki** [comment]
find到的so文件麻烦发我看下？LD_LIBRARY_PATH麻烦也发给我看下？

**Comment by pangyoki** [comment]
有可能是cuda驱动的版本与whl包的版本不对应。
麻烦nvidia-smi看下cuda driver的版本，选择对应的cuda版本安装。

**Comment by zhiyuan1i** [comment]
<img width="690" alt="截屏2023-01-31 17 04 34" src="https://user-images.githubusercontent.com/31544054/215715867-31983d60-9a99-4788-91a7-98cdf08518ab.png">
<img width="1192" alt="截屏2023-01-31 17 03 58" src="https://user-images.githubusercontent.com/31544054/215715913-d5dd5d2c-d931-41e0-9bc8-ab07aa6c5319.png">
<img width="738" alt="截屏2023-01-31 17 05 06" src="https://user-images.githubusercontent.com/31544054/215715985-b659017e-6400-416b-a5bc-3056a069fba2.png">


> 有可能是cuda驱动的版本与whl包的版本不对应。 麻烦nvidia-smi看下cuda driver的版本，选择对应的cuda版本安装。

同一个版本都是 11.6 的:(

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/215749429-d19d7806-c98c-4e7d-8586-0e00d18f8c14.png)
我是需要安装下驱动吗

**Comment by 258863** [comment]
![image](https://user-images.githubusercontent.com/91120551/215845773-c8f9e4b6-710d-4434-a7e7-96cbf9f5c8cb.png)
忘记打开的是cpu环境，在aistudio下运行程序报一样的错误，pytorch可以用gpu，paddle就报这样的错误

**Comment by pangyoki** [comment]
> 
> > 有可能是cuda驱动的版本与whl包的版本不对应。 麻烦nvidia-smi看下cuda driver的版本，选择对应的cuda版本安装。
> 
> 同一个版本都是 11.6 的:(

有使用镜像吗？`nvcc -V`看下呢？
另外使用`find / -name 'libcudart*'`命令打印下路径我看看？也`echo $LD_LIBRARY_PATH`看下这个环境变量。
