### ISSUE TITLE
运行dssm模型报AttributeError: 'module' object has no attribute 'square_error_cost'错误

### ISSUE THREAD

**Issue by zjgtan** [PaddlePaddle/Paddle#5006]
背景：
跑dssm模型regression代码，报
network_conf.py", line 279,
cost = paddle.layer.square_error_cost(prediction, label)
AttributeError: 'module' object has no attribute 'square_error_cost'

**Comment by NHZlX** [comment]
很大原因是因为目前你的paddle 版本 太旧， 请更新你的paddle版本

**Comment by sandycs** [comment]
我有一样的问题。
用的还是 @luotao1 给的最新版本...

**Comment by lcy-seso** [comment]
和此issue中的问题一样：https://github.com/PaddlePaddle/Paddle/issues/5390
