### ISSUE TITLE
编译paddle时执行op_function_generator命令时出现错误

### ISSUE THREAD

**Issue by zyx2095** [PaddlePaddle/Paddle#50069]
### 请提出你的问题 Please ask your question

平台：兼容CUDA的自有软件栈
cmake：cmake .. -DWITH_GPU=ON
详细的错误内容为

![Dingtalk_20230130104949](https://user-images.githubusercontent.com/115382819/215378351-0a3c8fef-e46c-47b5-b118-c8492a90ddb2.jpg)
因为错误的信息少，需要技术支持去调试这个问题。

**Comment by wanghuancoder** [comment]
你好，近期develop已经删除了op_function_generator。这个generator已经不再使用了。是不是因为你拉了新的代码导致问题出现的啊。你试试：1. 删除build目录，重新新建。2. 拉最新的develop的代码。3. 重新cmake+make。

**Comment by zyx2095** [comment]
最近我没有更新paddle的代码，通过gbd对core dump trace发现是 ConstructKernel函数里的问题，目前定位是在KernelFactory::Instance().kernel();这里出现错误的。我用的环境是自研的兼容cuda的软件栈，另外我搜索发现有几个issues也提到了这个问题，#48382 #48583 #48757都是Rocm平台出现的问题，不知道和平台是否有关系。
