### ISSUE TITLE
paddle 动转静 ifelse 报错

### ISSUE THREAD

**Issue by MarsMeng1994** [PaddlePaddle/Paddle#50083]
您好我在做一个cnn模型的动转静，其中有一个ifelse逻辑，模型代码如下：
![image](https://user-images.githubusercontent.com/24523981/215428826-06a3ba81-4495-4451-a5b8-6d3ec81ea570.png)
动转静无问题，但在用paddle inference运行时报错，信息是
![image](https://user-images.githubusercontent.com/24523981/215428900-f21f5380-3d9b-481a-b477-fa5050ee7c15.png)
我猜测是不是由于改写时这两个函数对x进行了修改导致的报错？
<img width="1116" alt="image" src="https://user-images.githubusercontent.com/24523981/215429058-79f9ed53-1e52-4a5b-ae9a-e6ae8146392f.png">

**Comment by wanghuancoder** [comment]
请0x45f帮忙看看这个问题

**Comment by 0x45f** [comment]
已经协助用户解决该问题
