### ISSUE TITLE
paddle inference中的config.enable_xpu()接口，设置xpu L3 缓存无效

### ISSUE THREAD

**Issue by Intsigstephon** [PaddlePaddle/Paddle#50084]
### bug描述 Describe the Bug

复现步骤：

在x86 CPU + R200环境配置下，使用PaddleOCR(https://github.com/PaddlePaddle/PaddleOCR)，参照该文档运行文本检测推理： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_ch/inference_ppocr.md#%E5%9F%BA%E4%BA%8Epython%E5%BC%95%E6%93%8E%E7%9A%84pp-ocr%E6%A8%A1%E5%9E%8B%E5%BA%93%E6%8E%A8%E7%90%86

命令如下：
# 下载超轻量中文检测模型：
wget  https://paddleocr.bj.bcebos.com/PP-OCRv3/chinese/ch_PP-OCRv3_det_infer.tar
tar xf ch_PP-OCRv3_det_infer.tar
python3 tools/infer/predict_det.py --image_dir="./doc/imgs/00018069.jpg" --det_model_dir="./ch_PP-OCRv3_det_infer/"  --use_gpu=false  --use_xpu=True

问题：
后台L3使用始终为13M.  不会随config的配置而改变。 该接口enable_xpu() 可能存在实现问题。

修改L3设置：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/tools/infer/utility.py  250行

![image](https://user-images.githubusercontent.com/17264083/215433834-fc921ac2-8960-404b-afc3-9b9fdb01add5.png)

截图如下：
<img width="750" alt="image" src="https://user-images.githubusercontent.com/17264083/215433916-8839c0af-d1e8-4269-9687-a8fbef89cacd.png">

<img width="760" alt="image" src="https://user-images.githubusercontent.com/17264083/215433949-97ab9cbc-825b-42a4-a58d-ab30e2ca889b.png">

<img width="766" alt="image" src="https://user-images.githubusercontent.com/17264083/215433982-2b263158-3800-4204-b74a-90a48b8fae29.png">

**Comment by wanghuancoder** [comment]
请@hong19860320帮忙看看这个问题

**Comment by MuShangCC** [comment]
@Intsigstephon 
Paddle Inference 这个L3 cache的值并不会改变底层的SetL3Cache的l3_size。
![image](https://user-images.githubusercontent.com/117341294/220314908-999da4f8-1570-436a-8e76-a6326f536821.png)
![image](https://user-images.githubusercontent.com/117341294/220326175-a951e9ef-72ff-40ae-8d7e-87e779df1c1f.png)
数值并没有传到SetL3Cache，目前L3 cache固定为默认值13.5M，这部分涉及到一些api的修改，之后会修复。

如果现在要使用L3 cache的配置功能，建议使用Lite实现，utility.py 需要做如下修改：
![image](https://user-images.githubusercontent.com/117341294/220315236-2e636461-c4a6-40e3-a159-1d658c75cec0.png)
添加 config.enable_lite_engine()
另外需要重新编译并安装PaddlePaddle whl包，编译选项需要加上-DWITH_LITE=ON -DLITE_WITH_XPU=ON 才能生效

**Comment by MuShangCC** [comment]
Inference 可以通过设置环境变量 XPU_PADDLE_L3_SIZE 来配置L3 cache。
