### ISSUE TITLE
Broken logical operations

### ISSUE THREAD

**Issue by sergiev** [PaddlePaddle/Paddle#50099]
### bug描述 Describe the Bug

```
>>> a = paddle.to_tensor([0], dtype='float32')
>>> a
Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [0.])
>>> a>a
Tensor(shape=[1], dtype=bool, place=Place(gpu:0), stop_gradient=True,
       [False])
>>> a==a
Tensor(shape=[1], dtype=bool, place=Place(gpu:0), stop_gradient=True,
       [False])
>>> paddle.equal(a,a)
Tensor(shape=[1], dtype=bool, place=Place(gpu:0), stop_gradient=True,
       [False])
```

Environment: docker image registry.baidubce.com/paddlepaddle/paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0

**Comment by zhwesky2010** [comment]
@sergiev 你好我这边没有复现你的问题
![infoflow 2023-02-01 15-17-05](https://user-images.githubusercontent.com/52485244/215976655-bde7c5a7-dd9f-4ffc-ab81-c99be13cac49.png)

**Comment by zhwesky2010** [comment]
@sergiev 可以装个最新的nightly build的 whl包试试是否有这个问题 `python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html`
