### ISSUE TITLE
paddlebox某一层的梯度乘一个系数怎么实现

### ISSUE THREAD

**Issue by angleyang** [PaddlePaddle/Paddle#50104]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by zhwesky2010** [comment]
@angleyang 动态图下可以用hook来修改反向传播中的梯度https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#register-hook-hook ，静态图不支持此功能
