### ISSUE TITLE
Missing timeout setting for bash_test_modules

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#50109]
### bug描述 Describe the Bug

[(bash_test_modules)](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/CMakeLists.txt#L328-L373) 是一個 cmake function, 用來提供給分散式測試做單測的模板，其中有一項參數 `TIMEOUT` 會在跑 test 的過程中設定 `TEST_TIMEOUT` 的環境變數，並且對超時的程序執行 kill。但是 `test_parallel_dygrph_pipeline_parallel` [代碼](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/collective/fleet/CMakeLists.txt#L181-L191) 在使用 `bash_test_modules` 沒有進行 `TIMEOUT` 設定，只對 ctest 的原生 timeout 做設定，導致 `test_parallel_dygrph_pipeline_parallel` 仍會被  `bash_test_modules` 的`TEST_TIMEOUT` kill 掉，而導致單測失敗

### 其他补充信息 Additional Supplementary Information

除了 `test_parallel_dygrph_pipeline_parallel`, 其他多項使用 `bash_test_modules` 的單測也有同樣問題。需要在設定 ctest timeout 的同時也對 `bash_test_modules` 的 TIMEOUT 做設定，或是整合 ctest timeout 到 `bash_test_modules` 內

**Comment by sljlp** [comment]
可以通过set_tests_properties 设置timeout属性，请参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/collective/CMakeLists.txt#L11.
建议增加分布式单测时你不要直接修改CMakeLists.txt文件， 增加方法请参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/collective/README.md

**Comment by sljlp** [comment]
抱歉之前误解了您的问题，现在发现确实有问题，后续会修复的。 @zlsh80826

**Comment by zlsh80826** [comment]
Hi @sljlp @zhouwei25 
Is there any update for this?

**Comment by sljlp** [comment]
https://github.com/PaddlePaddle/Paddle/pull/51961 Hi，这是解决这个问题的 PR @zlsh80826
