### ISSUE TITLE
Does paddle.sparse.nn.Conv3D fully implement spconv?

### ISSUE THREAD

**Issue by zeruniverse** [PaddlePaddle/Paddle#50127]
### 请提出你的问题 Please ask your question

Does paddlepaddle paddle.sparse.nn.Conv3D fully implement
 https://github.com/traveller59/spconv/blob/master/docs/USAGE.md#short-api-description

I currently use spconv for my model which is hard to deploy. I’m wondering if paddlepaddle has same capability and exported model can be served using C++ API

by the way, will paddlepaddle support common util ops for pointcloud / volume  tasks? Like https://github.com/thangvubk/SoftGroup/tree/main/softgroup/ops/src

**Comment by zkh2016** [comment]
Currently PaddlePaddle implements Sparse Conv3D and Submanifold Conv3D. 
Deployment method reference:
https://github.com/PaddlePaddle/Paddle3D/tree/develop/docs/models/centerpoint#%E5%AF%BC%E5%87%BA--%E9%83%A8%E7%BD%B2

**Comment by FlyingQianMM** [comment]
Paddle 3D regular Sparse Conv and 3D submanifold Conv can be deployed  directly by using our inference engine `Paddle Inference`. The usage example of paddle 3D sparse conv  can be found in Paddle3D: https://github.com/PaddlePaddle/Paddle3D/blob/release/1.0/paddle3d/models/middle_encoders/sparse_resnet.py

The ops in https://github.com/thangvubk/SoftGroup/tree/main/softgroup/ops/src can be implemented by paddle custom op, which also could be deployed directly by `Paddle Inference`. Paddle3D implemented hard/dynamic voxelize by paddle custom op, your can refer it to implement other custom ops: https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/paddle3d/ops/voxel

CenterPoint composed with aboved 3D sparse conv and custom voxelize op can be found in Paddle3D , which can be trained and deployed end-to-end by Paddle. You can refer to https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/centerpoint for the details.

**Comment by zeruniverse** [comment]
> Paddle 3D regular Sparse Conv and 3D submanifold Conv can be deployed directly by using our inference engine `Paddle Inference`. The usage example of paddle 3D sparse conv can be found in Paddle3D: https://github.com/PaddlePaddle/Paddle3D/blob/release/1.0/paddle3d/models/middle_encoders/sparse_resnet.py
> 
> The ops in https://github.com/thangvubk/SoftGroup/tree/main/softgroup/ops/src can be implemented by paddle custom op, which also could be deployed directly by `Paddle Inference`. Paddle3D implemented hard/dynamic voxelize by paddle custom op, your can refer it to implement other custom ops: https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/paddle3d/ops/voxel
> 
> CenterPoint composed with aboved 3D sparse conv and custom voxelize op can be found in Paddle3D , which can be trained and deployed end-to-end by Paddle. You can refer to https://github.com/PaddlePaddle/Paddle3D/tree/release/1.0/docs/models/centerpoint for the details.

Thanks for such a detailed reply. I will give it a try
