### ISSUE TITLE
编译paddle时执行op_function_generator命令时出现错误

### ISSUE THREAD

**Issue by zyx2095** [PaddlePaddle/Paddle#50128]
### 请提出你的问题 Please ask your question

#50069

**Comment by qili93** [comment]
hi，您好，

请您这里提供以下信息方便复现您的问题：

1. 编译的容器镜像，建议使用 `docker pull paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82`
2. Paddle 的源码版本，建议拉取最新的 develop 分支的最新代码，如果不是请通过如下命令提供 commit id

```bash
# 在 Paddle 源码目录下运行如下命令，输出为 commit history
git log --oneline -10
```

4. CMAKE 命令，请提供完成的编译命令，建议使用如下命令编译

```bash
cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DWITH_NCCL=ON -DWITH_TESTING=OFF \
         -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON -DCMAKE_BUILD_TYPE=Release 
```

5. 编译输出的完成日志 LOG 文件，建议采用如下方式保存完整的日志文件

```bash
make -j16 > paddle_build.log 2>&1
```
