### ISSUE TITLE
ExpandLayer get wrong result

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#5013]
```
input(x):
seq = [a, b], [c]
seq_starts = [0, 2, 3]

input(y):
seq_starts = [0, 2, 3, 5]
sub_seq_starts = [0, 3, 5]

output = ?
```

我按原[paddle expand layer](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ExpandLayer.cpp)的计算方法，得到：
[[a, a], [a]], [[b, b]]

这个结果貌似是不对的

上边的例子也过不了这个[check](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ExpandLayer.cpp#L64):
```
CHECK_EQ(dataInput.getNumSequences(), shapeInput.getNumSequences());
```
因为：
dataInput.getNumSequences() == 2
shapeInput.getNumSequences() == 3

是不是应该改成：
```
CHECK_EQ(dataInput.getBatchSize(), shapeInput.getNumSequences());
```

**Comment by luotao1** [comment]
正确的结果应该是[[a, a], [b]], [[c, c]]，原来的计算有问题。

**Comment by luotao1** [comment]
```
input(y):
sub_seq_starts = [0, 2, 3, 5]
seq_starts = [0, 3, 5]
```
这里写反了。不过还是要加个单测，这样更容易懂。

**Comment by luotao1** [comment]
但原来的ExpandLayer在non-seq->subseq的时候有错：
```
input(x):
non-seq: a, b, c
input(y):
seq_starts = [0, 3, 5]
sub_seq_starts = [0, 2 3, 5]
```
打印结果为：
```
output = [[a, a], [a]], [[b, b]]
```
正确结果为：
```
output = [[a, a], [b]], [[c, c]]
```
