### ISSUE TITLE
推理时如何实现模型保存中间计算状态？

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#50147]
推理时如何实现模型保存中间计算状态，每次任务的执行需要进行多步推理，多步推理中大部分计算是一致的，后面每步计算时，如何复用计算状态，以提高运行速度，减少计算量？

我们采取的模型结构，是UniLM型的模型，这个模型在一次请求时，会运行多次，每次运行时，其中双向编码部分（encoder）的输入是完全一样的。由于双向编码部分的计算量是模型的主要计算部分，所以如果能够复用这部分计算结果，那实际的计算速度会显著提升，计算量也会大幅下降。

因此希望实现能够保存双向编码部分的计算结果，基于这部分结果去继续完成单向部分推理的能力。通过对单向部分设置不同的prompt前缀，实现完成不同的任务。目前还不了解如何基于paddle的推理能力实现相应的能力，希望得到帮助

**Comment by ccrrong** [comment]
你好，推理暂不支持保存中间计算状态

**Comment by jshower** [comment]
这个有计划什么时间解决吗。我们的项目依赖这个能力

**Comment by jshower** [comment]
可以通过如流联系我，企业邮箱明jiaozhenyu。我们的项目还是非常需要这个能力的。
