### ISSUE TITLE
人脸表情识别实战：你的喜怒哀乐飞桨统统get！

### ISSUE THREAD

**Issue by lhk09** [PaddlePaddle/Paddle#50154]
### 请提出你的问题 Please ask your question

你好！我想问一下还有这个项目的源码吗？

**Comment by RainFrost1** [comment]
能否提供一下项目的原始链接？

**Comment by sunzhongkai588** [comment]
可以看看这个： https://aistudio.baidu.com/aistudio/projectdetail/54204
