### ISSUE TITLE
[PHI decoupling]Can we delete the RecordEvent in OneDNN code ?

### ISSUE THREAD

**Issue by YuanRisheng** [PaddlePaddle/Paddle#50161]
### 请提出你的问题 Please ask your question

Now, We are removing the Fluid headers in PHI for decoupling from Fluid. The header `"paddle/fluid/platform/profiler/event_tracing.h"` is only used in OneDNN code(except generated code) as below:
![image](https://user-images.githubusercontent.com/29249150/216262386-687324d6-bf56-47ac-bf28-cc7f1495936f.png)
It seems that `RecordEvent` is unnecessary in Phi Kernel. Is it necessary in OneDNN code and can we delete it? This conclusion will affect our next steps.  Please help me for this question and thank you.

**Comment by YuanRisheng** [comment]
@piotrekobi @jakpiase @yaomichael @Silv3S

**Comment by jczaja** [comment]
@YuanRisheng Hi, We disscussed internally and ext_reorder presents much bigger value for our optimization efforts so yes you can get rid of int_reorder from kernels.

**Comment by YuanRisheng** [comment]
> @YuanRisheng Hi, We disscussed internally and ext_reorder presents much bigger value for our optimization efforts so yes you can get rid of int_reorder from kernels.

@jczaja Thank you for your valuable feedback!
