### ISSUE TITLE
PaddlePaddle较新版本中缺少libpaddle.py，无法调用，求分享

### ISSUE THREAD

**Issue by xyh4783** [PaddlePaddle/Paddle#50164]
### 问题描述 Issue Description

PaddlePaddle v2.4的版本中 paddle\fluid\core.py程序调用了libpaddle.py模块，而该文件夹下该文件为libpaddle.pyd,无法调用。v2.1以前的版本已经无法下载，v2.1以后的版本均无libpaddle.py模块。求分享

### 版本&环境信息 Version & Environment Information

python 3.8

**Comment by RainFrost1** [comment]
fluid api已经逐渐废弃，不建议使用。如果要下载相应的文件，可以根据tag，找到相应的版本下载，如[2.0.1](https://github.com/PaddlePaddle/Paddle/tree/v2.0.1)版本
