### ISSUE TITLE
新环境下编译源码出现 data_type_transform.cu 找不到错误

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/Paddle#50177]
### bug描述 Describe the Bug

之前编译过很多次框架，没有出现问题；这次发现用 官方推荐的编译docker的自带cmake（3.10）无法进行编译了；所以自己编译了3.22版本的cmake进行框架编译，但是我遇到了这样的错误：

![image](https://user-images.githubusercontent.com/96160062/216490946-b58c6b0c-a3ef-4652-a44b-cbb5b58bfe0a.png)

![image](https://user-images.githubusercontent.com/96160062/216493289-11a6cb66-4a9a-45e1-ad6a-eeb7c7968a27.png)

我没有改动其他的软件版本，请问我该怎么解决这个问题呢？谢谢

### 其他补充信息 Additional Supplementary Information

这是我的编译环境和选项：
![image](https://user-images.githubusercontent.com/96160062/216491106-ff52c69d-157a-4769-aff8-c7c05b80f68c.png)

![image](https://user-images.githubusercontent.com/96160062/216491157-a64275e5-80b8-4511-8a8f-f9d036f1ccc0.png)

**Comment by ZHUI** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/data_type_transform.cu 

这是个软链接，可以检查一下

**Comment by sanbuphy** [comment]
说一下自己的解决方案，现在又遇到了这个问题。

这个问题的缘由是[data_type_transform.cu](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/data_type_transform.cu) 是一个软链接，在WSL上无法通过Clion上传，所以我们只需要把他改成对应的cc实体，或者在Clion远程的上传路径虚拟地址把data_type_transform.cc拷贝成 cu吗，就可以完美通关。
