### ISSUE TITLE
uos 编译安装失败，Python.h 

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/Paddle#50180]
### 问题描述 Issue Description

![1675389341223](https://user-images.githubusercontent.com/57654726/216493103-881f7b30-3c7d-4d8c-81e4-c8fddd1f0839.png)

环境：
![1675389590323](https://user-images.githubusercontent.com/57654726/216493873-cd0def58-aa36-4964-bd0c-7986213ef28f.png)

### 版本&环境信息 Version & Environment Information

Paddle version: N/APaddle with CUDA: N/A
0s: uos 20Gcc version: (Gcc) 8.2.0lang version: N/AMake version: version 3.16.8ibc version: glibc 2.28ython version: 3.8.15
UDA version: 11.2.152u1ld cuda 11.2.r11.2/compiler.29618528 0CUDNNversion: 8.3.3Nvidia' driver version: 460.106.00Nvidia driver List:
GPU 0: Tesla T4

**Comment by ZHUI** [comment]
辛苦检查一下是否 安装了 python-dev 

https://stackoverflow.com/questions/31002091/what-is-python-dev-package-used-for

**Comment by xialei2821212670** [comment]
> 辛苦检查一下是否安装了python-dev
> 
> https://stackoverflow.com/questions/31002091/what-is-python-dev-package-used-for

pip install lxml  ,
安装了 sudo apt aptitude

安装了sudo aptitude python3-dev

**Comment by ZHUI** [comment]
再重新cmake试试？

**Comment by xialei2821212670** [comment]
> 再重新cmake试试？
已经编译成功，但是显卡无法使用，paddle-gpu验证通过，但是无法使用显卡进行推理加速。
![1675476591027](https://user-images.githubusercontent.com/57654726/216740964-0c00fc95-0ce7-476e-aefc-b6bc5129e3d3.png)
cmake命令：sudo cmake .. -DPY_VERSION=3.8  -DPYTHON_EXECUTABLE=`which python3` -DPYTHON_INCLUDE_DIR=/home/uos/anaconda3/envs/py38/include/python3.8  -DPYTHON_LIBRARY=/home/uos/anaconda3/envs/py38/lib  -DWITH_ARM=ON   -DWITH_AVX=OFF    -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF   -DCUDA_ARCH_NAME=Maxwell  -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc  -DWITH_GPU=ON -DWITH_AVX=OFF -DCMAKE_THREAD_LIBS_INIT=pthread  -DCUDNN_ROOT=/usr/local/cuda
