### ISSUE TITLE
【文档】【demo情感分析】在 User-defined Data Preparation中，处理数据进行数据预处理的脚本是否需要指明在那个路径下，以及脚本名？以及需要执行的参数解释

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#502]
在 User-defined Data Preparation中，处理数据进行数据预处理的脚本是否需要指明在那个路径下，以及脚本名？以及需要执行的参数解释，文档中只给出一部分参数含义
![image](https://cloud.githubusercontent.com/assets/6229206/20378629/48197b5c-acd2-11e6-9a0c-cda1f85bb508.png)

**Comment by luotao1** [comment]
如果都解释的话，太冗余了。处理数据的脚本在你这张图的底部`preprocess.sh`，路径就在该demo下。这块还是比较清楚的。
