### ISSUE TITLE
Failed to import Paddle in Colab

### ISSUE THREAD

**Issue by KhoiNgo0703** [PaddlePaddle/Paddle#50210]
### 问题描述 Issue Description

Hi, I have some issue while installing GPU version of Paddle. I had no issue with the CPU version of it. 
I used the CUDA 11.6, Persistence-M, Tesla T4, python 3.8.10, pip 22.0.4, Python and pip are 64 bit, and the processor architecture is x86_64 architecture. I was running Google Colab on Window 10.
I used install paddlepaddle-gpu to install paddle and it was successful. However, when I import paddle, I got the issue. I could import paddle if I installed the Cpu version. Can someone explain me the issue and how I can fix it ?
![image](https://user-images.githubusercontent.com/118782728/216649211-b54ad8bf-c3dd-4e94-bcca-5412add684c5.png)
![image](https://user-images.githubusercontent.com/118782728/216649643-6fc61c12-3546-48ba-beca-4be643e72aaf.png)

### 版本&环境信息 Version & Environment Information

paddlepaddle-gpu-2.4.1
CUDA 11.6
Google Colab on Window 10
Python 3.8.10
![image](https://user-images.githubusercontent.com/118782728/216650128-94667550-fdf8-41d8-a3c0-a09516ac8eec.png)

**Comment by joey12300** [comment]
When use the command `pip install paddlepadlde-gpu`, actually you install the paddle compiled with cuda 10.2. If you want to install paddle compiled with cuda 11+, you can execute `python -m pip install paddlepaddle-gpu==2.4.1.post112`

**Comment by KhoiNgo0703** [comment]
> When use the command `pip install paddlepadlde-gpu`, actually you install the paddle compiled with cuda 10.2. If you want to install paddle compiled with cuda 11+, you can execute `python -m pip install paddlepaddle-gpu==2.4.1.post112`

**Comment by KhoiNgo0703** [comment]
> When use the command `pip install paddlepadlde-gpu`, actually you install the paddle compiled with cuda 10.2. If you want to install paddle compiled with cuda 11+, you can execute `python -m pip install paddlepaddle-gpu==2.4.1.post112`

I tried to excute that way but it could not work. 
![image](https://user-images.githubusercontent.com/118782728/216977425-8412c7fa-5c0d-49be-9e70-fdd5c494e550.png)
I also tried execute the command python -m pip install paddlepaddle-gpu==2.3.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html but the issue still happened.

**Comment by np-n** [comment]
`!python -m pip install paddlepaddle-gpu==2.1.3.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html` works for me and I have `NVIDIA-SMI 525.85.12    Driver Version: 525.85.12    CUDA Version: 12.0   ` GPU in google colab.
