### ISSUE TITLE
RuntimeError: (NotFound) The kernel with key (GPU, NCHW, int64) of kernel `sigmoid_cross_entropy_with_logits` is not registered and fail to fallback to CPU one.

### ISSUE THREAD

**Issue by DankoZhang** [PaddlePaddle/Paddle#50212]
### 请提出你的问题 Please ask your question

File "/home/disk2/work/zhangce/PaddleVideo/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/base.py", line 51, in forward
    return self.val_step(data_batch)
  File "/home/disk2/work/zhangce/PaddleVideo/PaddleVideo-develop/paddlevideo/modeling/framework/recognizers/recognizer2d.py", line 55, in val_step
    loss_metrics = self.head.loss(cls_score, labels, valid_mode=True)
  File "/home/disk2/work/zhangce/PaddleVideo/PaddleVideo-develop/paddlevideo/modeling/heads/base.py", line 87, in loss
    loss = self.loss_func(scores, labels, **kwargs)
  File "/home/work/anaconda3/envs/zhangce-envs/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/disk2/work/zhangce/PaddleVideo/PaddleVideo-develop/paddlevideo/modeling/losses/base.py", line 49, in forward
    return self._forward(*args, **kwargs) * self.loss_weight
  File "/home/disk2/work/zhangce/PaddleVideo/PaddleVideo-develop/paddlevideo/modeling/losses/cross_entropy_loss.py", line 36, in _forward
    loss = F.binary_cross_entropy_with_logits(score, labels)
  File "/home/work/anaconda3/envs/zhangce-envs/lib/python3.8/site-packages/paddle/nn/functional/loss.py", line 824, in binary_cross_entropy_with_logits
    out = _C_ops.sigmoid_cross_entropy_with_logits(
RuntimeError: (NotFound) The kernel with key (GPU, NCHW, int64) of kernel `sigmoid_cross_entropy_with_logits` is not registered and fail to fallback to CPU one.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:168)

**Comment by joey12300** [comment]
辛苦补充一下paddle版本，复现代码以及测试环境

**Comment by jjyaoao** [comment]
我这里有类似的问题,解决方案是更改co_occur的数据类型,该变量是二维tensor，设置dtype为float32即可
报错行为：
        loss = similarity + bi + bj - paddle.log(co_occur)

paddlepaddle版本为2.4，
代码为：
~~~python
import paddle
import paddle.nn as nn  #神经网络工具箱
import paddle.nn.functional as F  #神经网络函数
import numpy as np
import sys
import math


class GloveModel(nn.Layer):
    def __init__(self, vocab_size, embed_size):
        super().__init__()
        self.vocab_size = vocab_size
        self.embed_size = embed_size

        #声明v和w为Embedding向量
        self.v = nn.Embedding(vocab_size, embed_size)
        self.w = nn.Embedding(vocab_size, embed_size)
        self.biasv = nn.Embedding(vocab_size, 1)
        self.biasw = nn.Embedding(vocab_size, 1)

        #随机初始化参数
        initrange = 0.5 / self.embed_size
        self.v.weight.data = paddle.uniform(shape = [-int(initrange), int(initrange)])
        self.w.weight.data = paddle.uniform(shape = [-int(initrange), int(initrange)])

    def forward(self, i, j, co_occur, weight):
        vi = self.v(i)
        wj = self.w(j)
        bi = self.biasv(i)
        bj = self.biasw(j)

        similarity = paddle.multiply(vi, wj)
        similarity = paddle.sum(similarity)

        loss = similarity + bi + bj - paddle.log(co_occur)
        loss = 0.5 * weight * loss * loss

        return loss.sum().mean()
~~~
错误提示：
~~~
/tmp/ipykernel_417/842535059.py in forward(self, i, j, co_occur, weight)
     33         similarity = paddle.sum(similarity)
     34 
---> 35         loss = similarity + bi + bj - paddle.log(co_occur)
     36         loss = 0.5 * weight * loss * loss
     37 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/math.py in log(x, name)
    132     """
    133     if in_dygraph_mode():
--> 134         return _C_ops.log(x)
    135     if _in_legacy_dygraph():
    136         return _legacy_C_ops.log(x)

RuntimeError: (NotFound) The kernel with key (GPU, NCHW, int64) of kernel `log` is not registered and fail to fallback to CPU one.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at /paddle/paddle/phi/core/kernel_factory.cc:168)
~~~

**Comment by Phoenix8215** [comment]
我也碰到了类似的问题，将label从原来的int8改为int64就好了
```python
labels = np.reshape(self.labels[item],(1,)).astype("int64")
```
