### ISSUE TITLE
使用cmake在win10平台编译paddleseg的CPP部署例程报错error LNK2019: 无法解析的外部符号，均与paddle库相关。

### ISSUE THREAD

**Issue by elkslanlanlan** [PaddlePaddle/Paddle#50219]
### 请提出你的问题 Please ask your question

`#include <algorithm>
#include <chrono>
#include <iostream>
#include <fstream>
#include <numeric>

#include <gflags/gflags.h>
#include <glog/logging.h>

#include "paddle/include/paddle_inference_api.h"
#include "yaml-cpp/yaml.h"
#include "opencv2/core.hpp"
#include "opencv2/imgproc.hpp"
#include "opencv2/highgui.hpp"

DEFINE_string(model_dir, R"(D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\pp_liteseg_infer_model)", "Directory of the inference model. "
                             "It constains deploy.yaml and infer models");
DEFINE_string(img_path, R"(D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\cityscapes_demo.png)", "Path of the test image.");
DEFINE_string(devices, "CPU", "Use GPU or CPU devices. Default: GPU");
DEFINE_bool(use_trt, false, "Wether enable TensorRT when use GPU. Defualt: false.");
DEFINE_string(trt_precision, "fp32", "The precision of TensorRT, support fp32, fp16 and int8. Default: fp32");
DEFINE_bool(use_trt_dynamic_shape, false, "Wether enable dynamic shape when use GPU and TensorRT. Defualt: false.");
DEFINE_string(dynamic_shape_path, "", "If set dynamic_shape_path, it read the dynamic shape for TRT.");
DEFINE_bool(use_mkldnn, false, "Wether enable MKLDNN when use CPU. Defualt: false.");
DEFINE_string(save_dir, R"(D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\src)", "Directory of the output image.");

typedef struct YamlConfig {
  std::string model_file;
  std::string params_file;
  bool is_normalize;
  bool is_resize;
  int resize_width;
  int resize_height;
}YamlConfig;

YamlConfig load_yaml(const std::string& yaml_path) {
  YAML::Node node = YAML::LoadFile(yaml_path);
  std::string model_file = node["Deploy"]["model"].as<std::string>();
  std::string params_file = node["Deploy"]["params"].as<std::string>();
  YamlConfig yaml_config = {model_file, params_file};
  if (node["Deploy"]["transforms"]) {
    const YAML::Node& transforms = node["Deploy"]["transforms"];
    for (size_t i = 0; i < transforms.size(); i++) {
      if (transforms[i]["type"].as<std::string>() == "Normalize") {
        yaml_config.is_normalize = true;
      } else if (transforms[i]["type"].as<std::string>() == "Resize") {
        yaml_config.is_resize = true;
        const YAML::Node& target_size = transforms[i]["target_size"];
        yaml_config.resize_width = target_size[0].as<int>();
        yaml_config.resize_height = target_size[1].as<int>();
      }
    }
  }
  return yaml_config;
}

std::shared_ptr<paddle_infer::Predictor> create_predictor(
    const YamlConfig& yaml_config) {
  std::string& model_dir = FLAGS_model_dir;

  paddle_infer::Config infer_config;
  infer_config.SetModel(model_dir + "/" + yaml_config.model_file,
                  model_dir + "/" + yaml_config.params_file);
  infer_config.EnableMemoryOptim();

  if (FLAGS_devices == "CPU") {
    LOG(INFO) << "Use CPU";
    if (FLAGS_use_mkldnn) {
      LOG(INFO) << "Use MKLDNN";
      infer_config.EnableMKLDNN();
      infer_config.SetCpuMathLibraryNumThreads(5);
    }
  } else if(FLAGS_devices == "GPU") {
    LOG(INFO) << "Use GPU";
    infer_config.EnableUseGpu(100, 0);

    // TRT config
    if (FLAGS_use_trt) {
      LOG(INFO) << "Use TRT";
      LOG(INFO) << "trt_precision:" << FLAGS_trt_precision;

      // TRT precision
      if (FLAGS_trt_precision == "fp32") {
        infer_config.EnableTensorRtEngine(1 << 20, 1, 3,
          paddle_infer::PrecisionType::kFloat32, false, false);
      } else if (FLAGS_trt_precision == "fp16") {
        infer_config.EnableTensorRtEngine(1 << 20, 1, 3,
          paddle_infer::PrecisionType::kHalf, false, false);
      } else if (FLAGS_trt_precision == "int8") {
        infer_config.EnableTensorRtEngine(1 << 20, 1, 3,
          paddle_infer::PrecisionType::kInt8, false, false);
      } else {
        LOG(FATAL) << "The trt_precision should be fp32, fp16 or int8.";
      }

      // TRT dynamic shape
      if (FLAGS_use_trt_dynamic_shape) {
        LOG(INFO) << "Enable TRT dynamic shape";
        if (FLAGS_dynamic_shape_path.empty()) {
          std::map<std::string, std::vector<int>> min_input_shape = {
              {"image", {1, 3, 112, 112}}};
          std::map<std::string, std::vector<int>> max_input_shape = {
              {"image", {1, 3, 1024, 2048}}};
          std::map<std::string, std::vector<int>> opt_input_shape = {
              {"image", {1, 3, 512, 1024}}};
          infer_config.SetTRTDynamicShapeInfo(min_input_shape, max_input_shape,
                                        opt_input_shape);
        } else {
          infer_config.EnableTunedTensorRtDynamicShape(FLAGS_dynamic_shape_path, true);
        }
      }
    }
  } else {
    LOG(FATAL) << "The devices should be GPU or CPU";
  }

  auto predictor = paddle_infer::CreatePredictor(infer_config);
  return predictor;
}

void hwc_img_2_chw_data(const cv::Mat& hwc_img, float* data) {
  int rows = hwc_img.rows;
  int cols = hwc_img.cols;
  int chs = hwc_img.channels();
  for (int i = 0; i < chs; ++i) {
    cv::extractChannel(hwc_img, cv::Mat(rows, cols, CV_32FC1, data + i * rows * cols), i);
  }
}

cv::Mat read_process_image(const YamlConfig& yaml_config) {
  cv::Mat img = cv::imread(FLAGS_img_path, cv::IMREAD_COLOR);
  cv::cvtColor(img, img, cv::COLOR_BGR2RGB);
  if (yaml_config.is_resize) {
    cv::resize(img, img, cv::Size(yaml_config.resize_width, yaml_config.resize_height));
  }
  if (yaml_config.is_normalize) {
    img.convertTo(img, CV_32F, 1.0 / 255, 0);
    img = (img - 0.5) / 0.5;
  }
  return img;
}

int main(int argc, char *argv[]) {
  google::ParseCommandLineFlags(&argc, &argv, true);
  if (FLAGS_model_dir == "") {
    LOG(FATAL) << "The model_dir should not be empty.";
  }

  // Load yaml
  std::string yaml_path = FLAGS_model_dir + "/deploy.yaml";
  YamlConfig yaml_config = load_yaml(yaml_path);

  // Prepare data
  cv::Mat img = read_process_image(yaml_config);
  int rows = img.rows;
  int cols = img.cols;
  int chs = img.channels();
  std::vector<float> input_data(1 * chs * rows * cols, 0.0f);
  hwc_img_2_chw_data(img, input_data.data());

  // Create predictor
  auto predictor = create_predictor(yaml_config);

  // Set input
  auto input_names = predictor->GetInputNames();
  auto input_t = predictor->GetInputHandle(input_names[0]);
  std::vector<int> input_shape = {1, chs, rows, cols};
  input_t->Reshape(input_shape);
  input_t->CopyFromCpu(input_data.data());

  // Run
  predictor->Run();

  // Get output
  auto output_names = predictor->GetOutputNames();
  auto output_t = predictor->GetOutputHandle(output_names[0]);
  std::vector<int> output_shape = output_t->shape();
  int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                std::multiplies<int>());
  std::vector<int32_t> out_data(out_num);
  output_t->CopyToCpu(out_data.data());

  // Get pseudo image
  std::vector<uint8_t> out_data_u8(out_num);
  for (int i = 0; i < out_num; i++) {
    out_data_u8[i] = static_cast<uint8_t>(out_data[i]);
  }
  cv::Mat out_gray_img(output_shape[1], output_shape[2], CV_8UC1, out_data_u8.data());
  cv::Mat out_eq_img;
  cv::equalizeHist(out_gray_img, out_eq_img);
  cv::imwrite("out_img.jpg", out_eq_img);
  
  LOG(INFO) << "Finish, the result is saved in out_img.jpg";
}`

1. 我尝试在windows10平台用cmake编译paddleseg的cpp例程test_seg.cc。

2.由于cmake编译过程中yaml库部分总是报错，所以注释掉了makelist中的yaml库安装代码`
#find_package(yaml-cpp REQUIRED)
#include_directories(${YAML_CPP_INCLUDE_DIRS})
#link_directories(${YAML_CPP_LIBRARIES})
#set(DEPS ${DEPS} "-lyaml-cpp")`
并添加了paddle_lib等参数
`set(PADDLE_LIB D:\\AI-test\\PaddleSeg-release-2.7\\deploy\\cpp\\paddle_inference)
set(CMAKE_BUILD_TYPE Release)
set(DEMO_NAME test_seg)`
除此之外cmakelist中未修改其他代码，之后cmke编译成功生成sln工程。

3.在VS工程中手动配置了yaml静态库，在运行工程的时候出现了18个无法解析的外部符号 都与paddle库相关。
4.附加库目录如下
`D:\Qt5.15.2\opencv_MSVC\opencv\build\x64\vc15\lib
D:\Qt5.15.2\yaml-cpp-yaml-cpp-0.7.0\build_MSVC\Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/protobuf/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/protobuf/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/glog/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/glog/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/gflags/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/gflags/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/xxhash/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/xxhash/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/cryptopp/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/cryptopp/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/onnxruntime/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/onnxruntime/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/paddle2onnx/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/third_party/install/paddle2onnx/lib/Release
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/paddle/lib
D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/paddle_inference/paddle/lib/Release
/usr/local/lib
/usr/local/lib/Release
%(AdditionalLibraryDirectories)`
5.附加依赖项如下：
`D:\Qt5.15.2\yaml-cpp-yaml-cpp-0.7.0\build_MSVC\Release\yaml-cpp.lib
D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\paddle_inference\paddle\lib\libpaddle_inference.lib
D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\paddle_inference\third_party\install\mklml\lib\mklml.lib
D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\paddle_inference\third_party\install\mklml\lib\libiomp5md.lib
D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\paddle_inference\third_party\install\mkldnn\lib\mkldnn.lib
glog.lib
gflags_static.lib
libprotobuf.lib
xxhash.lib
cryptopp-static.lib
shlwapi.lib
D:\Qt5.15.2\opencv_MSVC\opencv\build\x64\vc15\lib\opencv_world460.lib
kernel32.lib
user32.lib
gdi32.lib
winspool.lib
shell32.lib
ole32.lib
oleaut32.lib
uuid.lib
comdlg32.lib
advapi32.lib`
6.报错如下：
` Building Custom Rule D:/AI-test/PaddleSeg-release-2.7/deploy/cpp/src/CMakeLists.txt
  test_seg.cc
d:\ai-test\paddleseg-release-2.7\deploy\cpp\paddle_inference\paddle\include\paddle_analysis_config.h(410): warning C4244: “return”: 从“const uint64_t”转换到“int”，可能丢失数据
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle_infer::Tensor::Reshape(class std::vector<int,class std::allocator<int> > const &)" (?Reshape@Tensor@paddle_infer@@QEAAXAEBV?$vector@HV?$allocator@H@std@@@std@@@Z)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: class std::vector<int,class std::allocator<int> > __cdecl paddle_infer::Tensor::shape(void)const " (?shape@Tensor@paddle_infer@@QEBA?AV?$vector@HV?$allocator@H@std@@@std@@XZ)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::SetModel(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetModel@AnalysisConfig@paddle@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableUseGpu(unsigned __int64,int)" (?EnableUseGpu@AnalysisConfig@paddle@@QEAAX_KH@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableTensorRtEngine(int,int,int,enum paddle::AnalysisConfig::Precision,bool,bool)" (?EnableTensorRtEngine@AnalysisConfig@paddle@@QEAAXHHHW4Precision@12@_N1@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::SetTRTDynamicShapeInfo(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<int,class std::allocator<int> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<int,class std::allocator<int> > > > >,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<int,class std::allocator<int> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<int,class std::allocator<int> > > > >,class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::vector<int,class std::allocator<int> >,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::vector<int,class std::allocator<int> > > > >,bool)" (?SetTRTDynamicShapeInfo@AnalysisConfig@paddle@@QEAAXV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@HV?$allocator@H@std@@@2@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$vector@HV?$allocator@H@std@@@2@@std@@@2@@std@@00_N@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableTunedTensorRtDynamicShape(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,bool)" (?EnableTunedTensorRtDynamicShape@AnalysisConfig@paddle@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@_N@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableMKLDNN(void)" (?EnableMKLDNN@AnalysisConfig@paddle@@QEAAXXZ)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::SetCpuMathLibraryNumThreads(int)" (?SetCpuMathLibraryNumThreads@AnalysisConfig@paddle@@QEAAXH@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle::AnalysisConfig::EnableMemoryOptim(bool)" (?EnableMemoryOptim@AnalysisConfig@paddle@@QEAAX_N@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl paddle_infer::Predictor::GetInputNames(void)" (?GetInputNames@Predictor@paddle_infer@@QEAA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@XZ)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: class std::unique_ptr<class paddle_infer::Tensor,struct std::default_delete<class paddle_infer::Tensor> > __cdecl paddle_infer::Predictor::GetInputHandle(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetInputHandle@Predictor@paddle_infer@@QEAA?AV?$unique_ptr@VTensor@paddle_infer@@U?$default_delete@VTensor@paddle_infer@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: bool __cdecl paddle_infer::Predictor::Run(void)" (?Run@Predictor@paddle_infer@@QEAA_NXZ)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: class std::vector<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class std::allocator<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > __cdecl paddle_infer::Predictor::GetOutputNames(void)" (?GetOutputNames@Predictor@paddle_infer@@QEAA?AV?$vector@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V?$allocator@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@@std@@XZ)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: class std::unique_ptr<class paddle_infer::Tensor,struct std::default_delete<class paddle_infer::Tensor> > __cdecl paddle_infer::Predictor::GetOutputHandle(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?GetOutputHandle@Predictor@paddle_infer@@QEAA?AV?$unique_ptr@VTensor@paddle_infer@@U?$default_delete@VTensor@paddle_infer@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@@Z)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl paddle_infer::CreatePredictor(struct paddle::AnalysisConfig const &)" (?CreatePredictor@paddle_infer@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUAnalysisConfig@paddle@@@Z)，该符号在函数 "class std::shared_ptr<class paddle_infer::Predictor> __cdecl create_predictor(struct YamlConfig const &)" (?create_predictor@@YA?AV?$shared_ptr@VPredictor@paddle_infer@@@std@@AEBUYamlConfig@@@Z) 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle_infer::Tensor::CopyFromCpu<float>(float const *)" (??$CopyFromCpu@M@Tensor@paddle_infer@@QEAAXPEBM@Z)，该符号在函数 main 中被引用
test_seg.obj : error LNK2019: 无法解析的外部符号 "public: void __cdecl paddle_infer::Tensor::CopyToCpu<int>(int *)const " (??$CopyToCpu@H@Tensor@paddle_infer@@QEBAXPEAH@Z)，该符号在函数 main 中被引用
D:\AI-test\PaddleSeg-release-2.7\deploy\cpp\src\build\Release\test_seg.exe : fatal error LNK1120: 18 个无法解析的外部命令`

**Comment by ghostxsl** [comment]
建议到PaddleSeg下提issue：https://github.com/PaddlePaddle/PaddleSeg/issues

**Comment by ghostxsl** [comment]
可以参考windows下部署的文档：https://github.com/PaddlePaddle/PaddleSeg/blob/develop/docs/deployment/inference/cpp_inference_windows_cn.md
此外，也可以检查下自己的paddle预测库版本是否正确，或者可以自己尝试本地编译一下paddle预测库

**Comment by elkslanlanlan** [comment]
谢谢，paddle预测库我跑通过resnet50的推理例程所以paddle的版本是没问题的，我感觉可能是camkelist的问题 我去paddleseg下提问看看
