### ISSUE TITLE
tools/train.py找不到模块

### ISSUE THREAD

**Issue by guyui** [PaddlePaddle/Paddle#50216]
### 请提出你的问题 Please ask your question

F:\captcha-main\PaddleOCR>python tools/train.py -c captcha/configs/captcha_num_rec_dev.yml
Traceback (most recent call last):
  File "tools/train.py", line 27, in <module>
    import paddle
ModuleNotFoundError: No module named 'paddle'
坏境idle pycharm python3.9  已经安装paddle

**Comment by joey12300** [comment]
试试 `python -m pip show paddlepaddle-gpu`看看有没有成功安装

**Comment by guyui** [comment]
> 

没问题，显示正常版本2.4.1

**Comment by guyui** [comment]
> > 
> 
> 没问题，显示正常版本2.4.1

paddlepaddle版本也是2.4.1

**Comment by guyui** [comment]
问题就是  python tools/train.py   ***   就会各种缺模块

**Comment by joey12300** [comment]
可以试试重新创建一个python的环境，重新安装paddle再试试
