### ISSUE TITLE
Failed to import PaddleGPU in Colab.

### ISSUE THREAD

**Issue by KhoiNgo0703** [PaddlePaddle/Paddle#50224]
### 请提出你的问题 Please ask your question

Hi, I have some issue while installing GPU version of Paddle. I had no issue with the CPU version of it.
I used the CUDA 11.6, Persistence-M, Tesla T4, python 3.8.10, pip 22.0.4, Python and pip are 64 bit, and the processor architecture is x86_64 architecture. I was running Google Colab on Window 10.
I used install paddlepaddle-gpu to install paddle and it was successful. However, when I import paddle, I got the issue. I could import paddle if I installed the Cpu version. Can someone explain me the issue and how I can fix it ?
![image](https://user-images.githubusercontent.com/118782728/216863063-3d79d4b8-9971-4195-9ef7-861cbff61fe1.png)
![image](https://user-images.githubusercontent.com/118782728/216863101-79a119dc-c267-4a06-998a-76b6b7d992dd.png)

**Comment by KhoiNgo0703** [comment]
I also tried execute the command python -m pip install paddlepaddle-gpu==2.3.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html but the issue still happened.

**Comment by whisperingkahuna** [comment]
This issue persists. Has anyone solved this issue?
