### ISSUE TITLE
请问怎么保存推理模型生成的特征图

### ISSUE THREAD

**Issue by Yuuchuin** [PaddlePaddle/Paddle#50222]
### 请提出你的问题 Please ask your question

Model.py文件中有一个Model网络的实现类，实例化了一个model对象。模型训练完毕之后通过paddle.jit.save(model, path)能够将模型和模型参数保存到本地，获得model.pdmodel和model.pdiparams文件。
在需要推理时，通过paddle.jit.load(path)可以加载并获得一个TranslatedLayer对象tl_model。目标是tl_model正向推理的时候，获取所有Model网络中间层生成的特征图(推理时仅能够获取到model.pdmodel和model.pdiparams文件，获取不到Model.py)，请问能否实现呢？

**Comment by nemonameless** [comment]
你好，可以用netron工具打开 model.pdmodel，可看到网络结构，但是无法获取中间某一层输出。
