### ISSUE TITLE
请问Paddle CPU版如何开启多核运算？

### ISSUE THREAD

**Issue by KenPanda** [PaddlePaddle/Paddle#50231]
### 请提出你的问题 Please ask your question
找了几个小时，做了N次尝试均失败。

如题，先谢！请各位大神赐教！

**Comment by KenPanda** [comment]
额，没人能够解答吗？还是仅限单核运算呢？

**Comment by nemonameless** [comment]
你好，默认是多核的。
https://github.com/PaddlePaddle/Paddle/issues/50223 这个问题主要是因为显存不够，可以去AIStudio申请免费的大显卡使用：[https://aistudio.baidu.com/aistudio/index](https://aistudio.baidu.com/aistudio/index%EF%BC%8C%E6%88%96%E8%80%85%E5%B0%9D%E8%AF%95%E6%9B%B4%E6%8D%A2%E6%9B%B4%E5%A4%A7%E7%9A%84GPU%E3%80%81%E6%88%96%E8%80%85%E7%94%A8CPU) ，或者尝试更换更大的GPU、或者用CPU
