### ISSUE TITLE
conda环境安装好openvino后，报错emebdding input only support int32 and int64

### ISSUE THREAD

**Issue by NB-Group** [PaddlePaddle/Paddle#50244]
### bug描述 Describe the Bug

在openvino环境下运行报错NotImplementedError: (Unimplemented) emebdding input only support int32 and int64 (at C:\home\workspace\Paddle\paddle\phi\kernels\cpu\embedding_kernel.cc:106)
  [operator < lookup_table_v2 > error]

pip install openvino前不报错，pip后报错

from pathlib import Path
import pyaudio
from paddlespeech.t2s.exps.syn_utils import get_am_output
from paddlespeech.t2s.exps.syn_utils import get_frontend
from paddlespeech.t2s.exps.syn_utils import get_predictor
from paddlespeech.t2s.exps.syn_utils import get_voc_output

# 模型路径
am_inference_dir = "./MOSS/"
# 声码器路径
voc_inference_dir = "./hifigan_aishell3_static_1.1.0/"
# 音频生成的路径，修改成你音频想要保存的路径
wav_output_dir = "./"

# 选择设备[gpu / cpu]，这里以GPU为例子，
device = "cpu"

# 想要生成的文本和对应文件名

# frontend
frontend = get_frontend(
    lang="en",
    phones_dict=os.path.join(am_inference_dir, "phone_id_map.txt"),
    tones_dict=None
)

# am_predictor
am_predictor = get_predictor(
    model_dir=am_inference_dir,
    model_file="fastspeech2_mix" + ".pdmodel",
    params_file="fastspeech2_mix" + ".pdiparams",
    device=device)

# voc_predictor
voc_predictor = get_predictor(
    model_dir=voc_inference_dir,
    model_file="hifigan_aishell3" + ".pdmodel",  # 这里以 pwgan_aishell3 为例子，其它模型记得修改此处模型名称
    params_file="hifigan_aishell3" + ".pdiparams",
    device=device)

output_dir = Path(wav_output_dir)
output_dir.mkdir(parents=True, exist_ok=True)

def speak(a):
    path = ".\\语音包\\"
    file_name_list = os.listdir(path)
    print(file_name_list)
    print(a + ".wav")
    # if a + ".wav" in file_name_list:

    text_dict = {
        a: a
    }
    sentences = list(text_dict.items())

    merge_sentences = True
    fs = 24000
    t1 = time.time()
    for utt_id, sentence in sentences:
        am_output_data = get_am_output(
            input=sentence,
            am_predictor=am_predictor,
            am="fastspeech2_mix",
            frontend=frontend,
            lang="en",
            merge_sentences=merge_sentences,
            speaker_dict=os.path.join(am_inference_dir, "phone_id_map.txt"),
            spk_id=0, )
        wav = get_voc_output(
            voc_predictor=voc_predictor, input=am_output_data)
        # 保存文件
        sf.write(output_dir / (utt_id + ".wav"), wav, samplerate=fs)
    print(time.time() - t1)
    chunk = 1024
    wf = wave.open(path + a + '.wav', 'rb')
    p = pyaudio.PyAudio()
    stream = p.open(format=p.get_format_from_width(wf.getsampwidth()),
                    channels=wf.getnchannels(),
                    rate=wf.getframerate(),
                    output=True)

    data = wf.readframes(chunk)

    while len(data) > 0:
        stream.write(data)
        data = wf.readframes(chunk)

    stream.stop_stream()
    stream.close()

    p.terminate()

speak("hi")

**Comment by NB-Group** [comment]
对不起，报错代码里没有imort time,os库

**Comment by nemonameless** [comment]
你好，如已解决可关闭issue，如未解决可以再开或再提问谢谢。
