### ISSUE TITLE
lookup_table_v2 is not deterministic

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#50245]
### bug描述 Describe the Bug

The implementation of the `Embedding` layer (lookup_table_v2) is not deterministic due to the `AtomicAdd` here -  [paddle/fluid/operators/lookup_table_v2_op.cu#L68](https://github.com/PaddlePaddle/Paddle/blob/b8e6ca92274b8540cdb799fbb787b6bb7a44111c/paddle/fluid/operators/lookup_table_v2_op.cu#L68).

Obviously, AtomicAdd in CUDA is the source of non-determinism. Because the order of float-point accumulation is uncertain.

PyTorch ensures determinism in their implementation of embedding - [aten/src/ATen/native/cuda/Embedding.cu#L94](https://github.com/pytorch/pytorch/blob/f3bf46e801dec2637751224fd6e27fbf97453bc6/aten/src/ATen/native/cuda/Embedding.cu#L94)

Ps:
I need to make BERT pretraining results completely reproducible. `PyTorch` can do it, but `PaddlePaddle` can't even if I already fixed all random seeds. I've verified that `embedding` is the only non-deterministic layer in BERT-Paddle model.

**Comment by nemonameless** [comment]
Hi, you can try `export FLAGS_cudnn_deterministic=1` at first.

**Comment by jeng1220** [comment]
It was resolved by #50494. This issue can be closed now.
