### ISSUE TITLE
cmake安装失败

### ISSUE THREAD

**Issue by SanguanZheng** [PaddlePaddle/Paddle#50256]
### bug描述 Describe the Bug

本机环境：Dell7920服务器+Ubuntu18.04，git clone的最新的paddle
在准备编译之前，由于链接过程中打开文件数较多，可能超过系统默认限制导致编译出错，设置进程允许打开的最大文件数后，执行cmake
tmpulimit -n 4096
cmake .. -DPY_VERSION=3.7 \
-DCMAKE_BUILD_TYPE=Release \
-DWITH_GPU=OFF \
-DWITH_XPU=ON \
-DON_INFER=ON \
-DWITH_PYTHON=ON \
-DWITH_MKL=OFF \
-DWITH_XPU_BKCL=ON \
-DWITH_TESTING=ON 
后报错，不确定是什么原因引起的错误？请帮助看下，谢谢。
![执行指令](https://user-images.githubusercontent.com/37808095/216945809-fd7eed86-2637-4543-ad74-6b56623cd9ad.png)
![cmake报错](https://user-images.githubusercontent.com/37808095/216945833-ceb6dfd0-9dca-4ccc-905f-f81a25ef4740.png)

**Comment by nemonameless** [comment]
你好，根据报错信息，请先安装或升级 jinja2再尝试。可指定jinja2的版本比如 3.1。
