### ISSUE TITLE
运行PaddleSlim-develop 出现问题：‘ModuleNotFoundError: No module named 'paddle.quantization'’

### ISSUE THREAD

**Issue by Hongyao98** [PaddlePaddle/Paddle#50255]
![image](https://user-images.githubusercontent.com/124556509/216942578-3e66aeb4-a097-4b7a-8f39-f324e0c063b6.png)
paddle版本为2.4.0

**Comment by Hongyao98** [comment]
![image](https://user-images.githubusercontent.com/124556509/216943034-dbc5e840-20fb-4683-85c1-0ac14afa6b30.png)
![image](https://user-images.githubusercontent.com/124556509/216943067-c28f5cd5-a254-40d4-b4ba-b4f3bd515055.png)

**Comment by nemonameless** [comment]
你好，如使用develop分支的PaddleSlim，请配合安装PaddlePaddle的develop版本，也可前往PaddleSlim提issue。
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
Paddle框架里的这部分源码可以看 https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/quantization

**Comment by yui330** [comment]
我遇到了同样的问题，这是我安装的版本。
paddleslim                2.3.0
paddlepaddle-gpu          2.3.2.post116
