### ISSUE TITLE
paddle中没有找到类似torch中torch.bitwise_right_shift()的函数，请问是否有替代方案？

### ISSUE THREAD

**Issue by cycao77** [PaddlePaddle/Paddle#50275]
### 请提出你的问题 Please ask your question

在paddle的API文档和历史issue里找了下，没有类似的函数，请问paddle中是否有torch.bitwise_right_shift()的替代方案？

**Comment by tink2123** [comment]
您好，暂时没有替代方案，我们记录下您的需求，会评估新增API
