### ISSUE TITLE
无法安装paddlepaddle-gpu==0.0.0.post117版本

### ISSUE THREAD

**Issue by Hongyao98** [PaddlePaddle/Paddle#50276]
### 请提出你的问题 Please ask your question

官网上安装cudu11.7版本的paddle命令”python -m pip install paddlepaddle-gpu==0.0.0.post117 -f [https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html”无法使用，安装时提示没有paddlepaddle-gpu==0.0.0.post117版本。请问如何解决这个问题？

**Comment by Hongyao98** [comment]
![image](https://user-images.githubusercontent.com/124556509/217137274-0635a70a-eb48-422b-9d37-258d0dc25f1c.png)

**Comment by tink2123** [comment]
请问使用的哪个python版本呢？

**Comment by Hongyao98** [comment]
python 3.7.6

**Comment by zhwesky2010** [comment]
@Hongyao98 你好，需要升级下pip版本，目前-f没有生效，会从pypi源上下载

**Comment by Hongyao98** [comment]
![image](https://user-images.githubusercontent.com/124556509/217165905-c9eb3fd1-e152-4310-9973-0c2c354748be.png)


> @Hongyao98 你好，需要升级下pip版本，目前-f没有生效，会从pypi源上下载

**Comment by Hongyao98** [comment]
列表里显示没有这个版本，pip的版本为23.0应该不是pip的问题

**Comment by Hongyao98** [comment]
> 请问使用的哪个python版本呢？

python为3.7.6，请问需要更新么？

**Comment by zhwesky2010** [comment]
@Hongyao98 你好，发现了官网的bug @dingjiaweiww 在修复中

**Comment by Synmul** [comment]
paddlepaddle-gpu==0.0.0   
0.0.0？版本号
