### ISSUE TITLE
paddle-gpu编译成功，验证成功，但是paddleocr,无法检测到文字

### ISSUE THREAD

**Issue by xialei2821212670** [PaddlePaddle/Paddle#50286]
> 再重新cmake试试？
已经编译成功，但是显卡无法使用，paddle-gpu验证通过，但是无法使用显卡进行推理加速。
![1675476591027](https://user-images.githubusercontent.com/57654726/216740964-0c00fc95-0ce7-476e-aefc-b6bc5129e3d3.png)
cmake命令：sudo cmake .. -DPY_VERSION=3.8  -DPYTHON_EXECUTABLE=`which python3` -DPYTHON_INCLUDE_DIR=/home/uos/anaconda3/envs/py38/include/python3.8  -DPYTHON_LIBRARY=/home/uos/anaconda3/envs/py38/lib  -DWITH_ARM=ON   -DWITH_AVX=OFF    -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF   -DCUDA_ARCH_NAME=Maxwell  -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc  -DWITH_GPU=ON -DWITH_AVX=OFF -DCMAKE_THREAD_LIBS_INIT=pthread  -DCUDNN_ROOT=/usr/local/cuda

_Originally posted by @xialei2821212670 in https://github.com/PaddlePaddle/Paddle/issues/50180#issuecomment-1416607802_

**Comment by tink2123** [comment]
无法使用显卡推理加速？ 麻烦提供下paddleocr推理的命令以及输出报错

**Comment by xialei2821212670** [comment]
> 无法使用显卡推理加速？ 麻烦提供下paddleocr推理的命令以及输出报错

 命令：paddleocr --image_dir ./doc/imgs_en/254.jpg --lang=en --use_gpu=fasle
![image](https://user-images.githubusercontent.com/57654726/217404740-046753c6-efd1-4c3e-abb0-44d316007663.png)
当我打开GPU的时候，检测文本就检测不出来，识别为空
![image](https://user-images.githubusercontent.com/57654726/217404866-5ade4557-b2bc-4696-9e78-7eb5516d8dd4.png)
pip安装了自己编译的paddle-gpu，也进行了测试
![image](https://user-images.githubusercontent.com/57654726/217405078-21a3e9d3-c077-49dc-af50-95454c49e45f.png)

**Comment by tink2123** [comment]
直接使用官网下载的paddle-gpu 能否正确识别呢？ 建议简单跑一个python测试代码，计算一个Linear看能否得到正确结果，验证本地编译whl包的正确性：
```
import paddle

# Define the linear layer.
weight_attr = paddle.ParamAttr(
    name="weight",
    initializer=paddle.nn.initializer.Constant(value=0.5))
bias_attr = paddle.ParamAttr(
    name="bias",
    initializer=paddle.nn.initializer.Constant(value=1.0))
linear = paddle.nn.Linear(2, 4, weight_attr=weight_attr, bias_attr=bias_attr)
# linear.weight: [[0.5 0.5 0.5 0.5]
#                 [0.5 0.5 0.5 0.5]]
# linear.bias: [1. 1. 1. 1.]

x = paddle.randn((3, 2), dtype="float32")
# x: [[-0.32342386 -1.200079  ]
#     [ 0.7979031  -0.90978354]
#     [ 0.40597573  1.8095392 ]]
y = linear(x)
# y: [[0.23824859 0.23824859 0.23824859 0.23824859]
#     [0.9440598  0.9440598  0.9440598  0.9440598 ]
#     [2.1077576  2.1077576  2.1077576  2.1077576 ]]
```

**Comment by xialei2821212670** [comment]
系统为统信，鲲鹏920处理器，arm架构处理器。
![image](https://user-images.githubusercontent.com/57654726/217470863-e0cb6fbe-2e83-4922-bb0a-5383957742dd.png)

**Comment by tink2123** [comment]
打开GPU的时候推理时，终端有显示推理结果吗？包括检测框和文本内容

**Comment by xialei2821212670** [comment]
> 打开GPU的时候推理时，最终有显示推理结果吗？包括测试框架和文档内容

上面就是关闭和开启GPU检测的结果。开启gpu，检测不出文字

**Comment by xialei2821212670** [comment]
已解决，注意编译的GPU架构

**Comment by minboo** [comment]
@xialei2821212670 您好，请问您是如何解决的呢，还有您的cmake命令是什么？希望能回复一下，谢谢。

**Comment by henryhust** [comment]
@minboo，我参考了楼主的编译命令，用一下命令完成congfige：
cmake .. -DPY_VERSION=3.8 -DWITH_GPU=ON -DWITH_NCCL=OFF -DPYTHON_INCLUDE_DIR=/usr/local/python3.8/include/python3.8 -DPYTHON_LIBRARY=/usr/local/python3.8/lib/ -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DCUDA_ARCH_NAME=Ampere -DCMAKE_CUDA_COMPILER=/usr/local/cuda/bin/nvcc -DWITH_AVX=OFF -DCMAKE_THREAD_LIBS_INIT=pthread -DCUDNN_ROOT=/usr/local/cuda
