### ISSUE TITLE
paddle转onnx格式报错

### ISSUE THREAD

**Issue by huntlin** [PaddlePaddle/Paddle#50284]
/usr/lib/python3/dist-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/home/test/.local/lib/python3.7/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/test/.local/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/test/.local/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/test/.local/lib/python3.7/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
Traceback (most recent call last):
  File "export.py", line 9, in <module>
    paddle.onnx.export(lenet, "mnist_cnn", input_spec=[x_spec], opset_version=9)
  File "/home/test/.local/lib/python3.7/site-packages/paddle/onnx/export.py", line 105, in export
    **configs
  File "/home/test/.local/lib/python3.7/site-packages/paddle2onnx/convert.py", line 181, in dygraph2onnx
    output_spec)
  File "/home/test/.local/lib/python3.7/site-packages/paddle2onnx/graph/paddle_graph.py", line 272, in build_from_dygraph
    layer, input_spec, output_spec)
  File "<decorator-gen-510>", line 2, in get_program
  File "/home/test/.local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 67, in __impl__
    return func(*args, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/paddle2onnx/graph/dygraph_helper.py", line 239, in get_program
    src_tensor = state_var_dict[param_or_buffer.name].value(
  File "<decorator-gen-164>", line 2, in value
  File "/home/test/.local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/home/test/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 532, in __impl__
    % func.__name__
AssertionError: We only support 'value()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

按照官方提供的转onnx示例报错
代码如下：
import paddle

lenet = paddle.vision.models.LeNet(num_classes=10)

# # 设置模型输入输出
x_spec = paddle.static.InputSpec([None, 1, 28, 28], 'float32', 'x') 

# 模型导出
paddle.onnx.export(lenet, "mnist_cnn", input_spec=[x_spec], `opset_version=11)

**Comment by huntlin** [comment]
paddlepaddle:2.4.1
paddle2onnx:0.9.2

**Comment by tink2123** [comment]
您好，验证如下代码进行模型转换没有问题：
可以尝试升级paddle2onnx至1.0.5，或者在import paddle 后添加代码 paddle.disable_static()
```
import paddle
lenet = paddle.vision.models.LeNet(num_classes=10)
x_spec = paddle.static.InputSpec([None, 1, 28, 28], 'float32', 'x')
paddle.onnx.export(lenet, "mnist_cnn", input_spec=[x_spec], opset_version=11)
```

**Comment by huntlin** [comment]
> 您好，验证如下代码进行模型转换没有问题： 可以尝试升级paddle2onnx至1.0.5，或者在import paddle 后添加代码 paddle.disable_static()
> 
> ```
> import paddle
> lenet = paddle.vision.models.LeNet(num_classes=10)
> x_spec = paddle.static.InputSpec([None, 1, 28, 28], 'float32', 'x')
> paddle.onnx.export(lenet, "mnist_cnn", input_spec=[x_spec], opset_version=11)
> ```

你好，我的尝试安装升级到1.0.5版本，但是系统提示最新版本为0.9.2

**Comment by huntlin** [comment]
问题解决了，pip没更新导致的版本问题，多谢指导
