### ISSUE TITLE
Paddle docker 是否有包含tensorrt安装的镜像？

### ISSUE THREAD

**Issue by sanbuphy** [PaddlePaddle/Paddle#50297]
### 需求描述 Feature Description

对于paddle框架开发docker类任务，需要有tensorrt安装才能自动补全符号信息；但是gpu镜像没有安装tensorrt

### 替代实现 Alternatives

我自己打包了一个基于官方编译包含tensorrt的gpu镜像，可以打包到dockerhub上；不知道官方gpu编译用的docker是否有dockerfile，可以的话我能够对他进行dockerfile改造

**Comment by tink2123** [comment]
有的，可以参考：
nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0
nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0
nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda11.7-cudnn8.4-trt8.4

**Comment by sanbuphy** [comment]
> 有的，可以参考： nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0 nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda11.2-cudnn8.2-trt8.0 nvidia-docker pull paddlepaddle/paddle:2.4.1-gpu-cuda11.7-cudnn8.4-trt8.4

收到，谢谢。
