### ISSUE TITLE
paddlepaddle-gpu==0.0.0.post117版本无法安装

### ISSUE THREAD

**Issue by Hongyao98** [PaddlePaddle/Paddle#50296]
### 请提出你的问题 Please ask your question

develop的paddlepaddle-gpu==0.0.0.post117版本不能安装是什么情况？python版本为3.9.1，pip为23.0
![fd44626c2fb0821a755a857bac2159d](https://user-images.githubusercontent.com/124556509/217198243-b6daf887-195f-41a6-9d08-57865f5dadb3.png)
![d929670baa659217a6cf57a525be2a8](https://user-images.githubusercontent.com/124556509/217198266-3ad365f1-4001-4acf-910c-84478af2fc65.png)

**Comment by zhwesky2010** [comment]
@Hongyao98 你好，发现了官网的bug @dingjiaweiww 在修复中

**Comment by Synmul** [comment]
0.0.0
