### ISSUE TITLE
windows11 arm版系统上使用paddlepaddle==2.4.1报错的问题，2.3.2版的正常

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#50300]
### bug描述 Describe the Bug

windows11 arm版系统上使用paddlepaddle==2.4.1报错的问题，2.3.2版的正常。
python版本：3.8.9(amd版)
安装2.4.1 支持avx版的，报错如下：
NameError:name 'libpaddle' is not paddle
![7K)UYXESWVY02@ Z~RDGF3P](https://user-images.githubusercontent.com/15188456/217220288-e6e35ce4-bc31-4753-99ae-a9e6ab0adb8b.png)
安装2.4.1 不支持avx版的，报错如下：
OSError:Invalid enum_backend type '64'
![0J6$W0MA~ P7N~} @QTDT@P](https://user-images.githubusercontent.com/15188456/217220497-4c779636-b0ec-452d-a778-fefdacb215b9.png)
但是，安装2.3.2版的就可以正常运行：
![RC9~32 65 T0X2IM`}_2RBP](https://user-images.githubusercontent.com/15188456/217221321-40c4c507-72b5-493c-b13e-eae35b3828a8.png)

**Comment by zhwesky2010** [comment]
@yangy996  和这个问题一样 https://github.com/PaddlePaddle/Paddle/issues/49964
