### ISSUE TITLE
fleet分布式训练使用fluid.layers.collective._c_allgather程序hang住，GPU利用率固定在100%，没有输出

### ISSUE THREAD

**Issue by Wenze7** [PaddlePaddle/Paddle#50308]
### 请提出你的问题 Please ask your question

我需要调用4次fluid.layers.collective._c_allgather，但是只有第一个fluid.layers.collective._c_allgather有输出，其他的直接卡住，但是gpu利用率是满的
![image](https://user-images.githubusercontent.com/55132749/217280471-34ec4be6-a716-47b4-830a-b3afb479623a.png)
![image](https://user-images.githubusercontent.com/55132749/217280591-22820da0-a131-4539-9ade-732bb03b7146.png)

**Comment by Wenze7** [comment]
@tink2123 您好～能方便看下吗

**Comment by tink2123** [comment]
建议检查下各个卡allgather的数据是否长度一致

**Comment by Wenze7** [comment]
> 
好的，确实我的每张卡的长度可能是不一致的
