### ISSUE TITLE
MPI train exit: check_return 'hadoop_ls_file: Generate filelist for train meta failed'

### ISSUE THREAD

**Issue by Jarlonyan** [PaddlePaddle/Paddle#5031]
MPI训练异常退出，信息如下，请问这是什么原因呢？

Job Status Series :
```
epilogue finished
epilogue started
user_main failed (Status:kTaskStatusExited)
user_main startedprologue finishedprologue startedReady
```

train.log中提示：
```
check_return 'hadoop_ls_file: Generate filelist for train meta failed'
```

**Comment by hedaoyuan** [comment]
Check the file path is correct.

**Comment by typhoonzero** [comment]
`check_return 'hadoop_ls_file: Generate filelist for train meta failed'` 这个应该是`bash -x`的输出（前面应该包含一个`+`），应该不是根本问题，请仔细检查日志，找到根本错误。

**Comment by Jarlonyan** [comment]
server.log中没有相关的错误日志。train.log中都是`check_return 'hadoop_ls_file: Generate filelist for train meta failed`这种错误，没有别的错误提示，这个改怎么办？

**Comment by hedaoyuan** [comment]
仔细看train.log里面提示了`ls: Cannot access xxxxxxxxxxxxxxxxx: No such file or directory.`

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
