### ISSUE TITLE
enable_tensorrt_engine 

### ISSUE THREAD

**Issue by moonnyeon** [PaddlePaddle/Paddle#50319]
### 请提出你的问题 Please ask your question

I had trained a Fairmot model and then ran export_model.py. At that time, my environment was PaddlePaddle-gpu 2.3.0, CUDA 11.2, cuDNN 8.0.0, and TensorRT 8.0.0.3 However, an error occurred while continuously running run_mode=trt_fp32,trt_fp16(command : python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_864x480/ --video_file=3015_2_52.mp4 --device=GPU --run_mode=trt_fp16)

![image](https://user-images.githubusercontent.com/87063668/217433658-a13cd3bd-30f4-410b-b2ca-35cc868f72fd.png)
so I changed my environment. The new environment I changed to is PaddlePaddle 2.4.1.post116, CUDA 11.6, cuDNN 8.7.0, and TensorRT 8.5.3.1.

And then I ran mot_jde_infer.py in paddle mode (command : python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_864x480/ --video_file=3015_2_52.mp4 --device=GPU)

And I got very good results as shown in the figure below

![image](https://user-images.githubusercontent.com/87063668/217433635-2a5a5ab2-24ad-418a-a59b-106d55b78ec0.png)

However, even after changing the environment, if I run in TensorRT mode like run_mode=trt_fp32,tft_fp16, it still produces errors like the figure below and doesn't work (command : python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --image_dir ./test_data/image1/ --device=GPU --run_mode=trt_fp16)

![image](https://user-images.githubusercontent.com/87063668/217433618-f3eef5dd-67a2-40fc-b562-f72b4f44a9a3.png)

"after looking for related errors on Github, I saw a post saying to change the min_subgraph_size parameter when calling enable_tensorrt_engine.
before
![image](https://user-images.githubusercontent.com/87063668/217433605-29240863-f774-47e2-8971-f7f11209f60d.png)

after:
![image](https://user-images.githubusercontent.com/87063668/217433593-21b19cf0-530e-445f-b3ac-6d78432a72e7.png)

After running it that way, I saw results that seem to indicate TensorRT is being run in terms of inference time, etc. as shown in the figure below." (command : CUDA_VISIBLE_DEVICES=0 python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_1088x608 --image_dir ./test_data/image1/ --device=GPU --run_mode=trt_fp16
)
![image](https://user-images.githubusercontent.com/87063668/217433576-7e1c7f99-39c3-417a-8083-f6849e62b9ec.png)

Although the inference time appears to have decreased, errors are still continuing to occur
Error :
" E0207 17:18:03.091236 46584 helper.h:114] 3: [elementWiseLayer.cpp::setOperation::87] Error Code 3: API Usage Error (Parameter check failed at: optimizer/api/layers/elementWiseLayer.cpp::setOperation::87, condition: !mNetwork->hasImplicitBatchDimension() || !builder::hasBoolOutput(op) "

And although the inference time has decreased, the results are strange. It appears that NMS is not functioning properly

The result generated using "run_mode=trt_fp32" is as follows: (command : python deploy/pptracking/python/mot_jde_infer.py --model_dir=output_inference/fairmot_dla34_30e_864x480/ --video_file=3015_2_52.mp4 --device=GPU --run_mode=trt_fp16 --output_dir=./out --save_images)
![image](https://user-images.githubusercontent.com/87063668/217433554-8110ed5e-740e-4f29-a61b-c23c95c937f1.png)

**Comment by gongel** [comment]
Hi, @nemonameless please follow this issue.

**Comment by nemonameless** [comment]
Please try paddle 2.2.2, maybe later versions of paddle have some problems with fairmot, we will re-check. 
In addition, fairmot of MOT is out of date. We recommend you to use bytetrack or ocsort. You can see [pphuman](https://github.com/PaddlePaddle/PaddleDetection/blob/develop/deploy/pipeline/docs/tutorials/PPHuman_QUICK_STARTED_en.md) project or [pptracking-bytetrack](https://github.com/PaddlePaddle/PaddleDetection/tree/develop/deploy/pptracking/python#3-bytetrack%E5%92%8Coc_sort%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E5%92%8C%E9%A2%84%E6%B5%8B).

https://github.com/PaddlePaddle/PaddleDetection/issues/7676

**Comment by moonnyeon** [comment]
Are paddle2.2.2 and paddle-gpu2.2.2 the same? If I want to use a GPU, should I use paddle-gpu2.2.2?

**Comment by nemonameless** [comment]
If I want to use on GPU,  paddlepaddle-gpu 2.2.2
