### ISSUE TITLE
训练gpt的过程中保存模型出错，'ParamBase' object has no attribute 'is_floating_point'

### ISSUE THREAD

**Issue by supinyu** [PaddlePaddle/Paddle#50312]
### bug描述 Describe the Bug

1、代码
使用的是，这个下面的代码
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/model_zoo/gpt

2、相关环境

paddle-bfloat      0.1.7
paddle2onnx        1.0.3
paddlefsl          1.1.0
paddlehub          2.2.0
paddlenlp          2.5.0
paddlepaddle-gpu   2.2.1.post110

3、训练命令

```bash
CUDA_VISIBLE_DEVICES=3 python run_pretrain.py \
  --model_name_or_path gpt-cpm-small-cn-distill \
  --model_type gpt-cn \
  --input_dir ./data \
  --output_dir ./output_dir/pretrain \
  --weight_decay 0.01 \
  --max_steps 500000 \
  --save_steps 100000 \
  --device gpu \
  --warmup_steps 320000 \
  --max_seq_len 1024 \
  --warmup_ratio 0.01 \
  --eval_steps 100 \
  --do_train true \
  --do_predict true > train.log
```

4、中间保存模型报错

<img width="1438" alt="截屏2023-02-08 10 51 30" src="https://user-images.githubusercontent.com/12369067/217417292-cd94b098-c03b-4228-8df5-554b4d3eebc7.png">

5、查看代码发现

paddlenlp/transformers/model_utils.py

```
def get_parameter_dtype(parameter: nn.Layer) -> paddle.dtype:
    """get dtype of parameter which should be sub-class of nn.Layer

    Args:
        parameter (nn.Layer): the instance of layer

    Returns:
        paddle.dtype: the dtype of tensor
    """

    last_dtype = None
    for t in parameter.parameters():
        last_dtype = t.dtype
        if t.is_floating_point():
            return t.dtype
```

通过查看api发现，is_floating_point放到了paddle下面

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/is_floating_point_cn.html

请问这个情况如何修复

**Comment by gongel** [comment]
你好，升级PaddlePaddle到最新版本即可解决

**Comment by supinyu** [comment]
paddle升级到了2.4.1，问题得到了解决，谢谢
```bash
python -m pip install paddlepaddle-gpu==2.4.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```
