### ISSUE TITLE
gcc12编译Paddle报错

### ISSUE THREAD

**Issue by risemeup1** [PaddlePaddle/Paddle#50334]
### bug描述 Describe the Bug

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/62429225/217479657-4aaf92a5-2cf5-4de9-9caa-0c557d893d8c.png">

### 其他补充信息 Additional Supplementary Information

将gcc8升级到gcc12在cpu下编译Paddle时候报错，gcc8编译则没有问题，错误如下：
In file included from /home/workspace/paddle/phi/backends/gpu/gpu_context.h:18,
                 from /home/workspace/paddle/phi/backends/all_context.h:25,
                 from /home/workspace/paddle/phi/core/kernel_utils.h:17,
                 from /home/workspace/paddle/phi/core/kernel_registry.h:28,
                 from /home/workspace/paddle/phi/kernels/cpu/index_add_kernel.cc:17:
In static member function ‘static constexpr _Tp& std::__array_traits<_Tp, _Nm>::_S_ref(const _Tp (&)[_Nm], std::size_t) [with _Tp = long int; long unsigned int _Nm = 2]’,
    inlined from ‘constexpr const std::array<_Tp, _Nm>::value_type& std::array<_Tp, _Nm>::operator[](size_type) const [with _Tp = long int; long unsigned int _Nm = 2]’ at /usr/local/gcc-12.2/include/c++/12.2.0/array:219:25,
    inlined from ‘IndexType Eigen::internal::TensorBlockDescriptor<NumDims, IndexType>::dimension(int) const [with int NumDims = 2; IndexType = long int]’ at /home/workspace/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorBlock.h:300:61,
    inlined from ‘void Eigen::TensorEvaluator<Eigen::TensorChippingOp<DimId, XprType>, Device>::writeBlock(const TensorBlockDesc&, const TensorBlock&) [with TensorBlock = Eigen::internal::TensorCwiseBinaryBlock<Eigen::internal::scalar_sum_op<float, float>, Eigen::internal::TensorMaterializedBlock<float, 2, 1, long int>, Eigen::internal::TensorMaterializedBlock<float, 2, 1, long int> >; long int DimId = -1; ArgType = Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer>; Device = Eigen::DefaultDevice]’ at /home/workspace/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorChipping.h:494:58,
    inlined from ‘void Eigen::TensorEvaluator<const Eigen::TensorAssignOp<LhsXprType, RhsXprType>, Device>::evalBlock(TensorBlockDesc&, TensorBlockScratch&) [with LeftArgType = Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> >; RightArgType = const Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_sum_op<float, float>, const Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> >, const Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> > >; Device = Eigen::DefaultDevice]’ at /home/workspace/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorAssign.h:224:28,
    inlined from ‘static void Eigen::internal::TensorExecutor<Expression, Eigen::DefaultDevice, Vectorizable, Eigen::internal::On>::run(const Expression&, const Eigen::DefaultDevice&) [with Expression = const Eigen::TensorAssignOp<Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> >, const Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_sum_op<float, float>, const Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> >, const Eigen::TensorChippingOp<-1, Eigen::TensorMap<Eigen::Tensor<float, 3, 1, long int>, 0, Eigen::MakePointer> > > >; bool Vectorizable = true]’ at /home/workspace/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorExecutor.h:206:28:
/usr/local/gcc-12.2/include/c++/12.2.0/array:61:36: error: array subscript 18446744073709551615 is above array bounds of ‘std::__array_traits<long int, 2>::_Type’ {aka ‘const long int [2]’} [-Werror=array-bounds]
   61 |       { return const_cast<_Tp&>(__t[__n]); }

**Comment by gongel** [comment]
你好，gcc12编译正在支持中。
