### ISSUE TITLE
Paddle mpi训练save model时间长

### ISSUE THREAD

**Issue by wangsouc** [PaddlePaddle/Paddle#5034]
集群训练设置--saving_period_by_batches=60，每次保存模型需要1.8个小时左右：

I1024 08:48:05.537341 43665 TrainerInternal.cpp:165]  Batch=360 
I1024 10:32:20.213470 43665 TrainerInternal.cpp:165]  Batch=380

**Comment by wangsouc** [comment]
排查原因：每次save model前会test数据，耗时
I1024 08:44:31.620820 43665 Tester.cpp:127]  Test samples=9301599 
I1024 10:30:51.922046 43665 Tester.cpp:127]  Test samples=9301599

**Comment by typhoonzero** [comment]
先关闭此issue了，重构后的版本可以比较方便的通过op指定保存模型的方式，和test是独立的。
