### ISSUE TITLE
什么时候能够支持rk3399pro rk3588 

### ISSUE THREAD

**Issue by zhangzaixiu** [PaddlePaddle/Paddle#50342]
### 请提出你的问题 Please ask your question

什么时候能够支持rk3399pro rk3588

**Comment by gongel** [comment]
你好，内部评估中，敬请期待。

**Comment by onecatcn** [comment]
我们通过paddle2onnx方式支持rk3588，请参考：
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/build_and_install/rknpu2.md
https://github.com/PaddlePaddle/FastDeploy/blob/develop/docs/cn/faq/rknpu2/rknpu2.md

rk3399pro暂时没测试过，如果使用paddle2onnx方式，可能会遇到一些问题。
