### ISSUE TITLE
@to_static 未能正确处理逻辑截断

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/Paddle#50365]
### bug描述 Describe the Bug

```python
import paddle
from paddle.jit import to_static

def T(val):
  return paddle.to_tensor([val])

def foo(x, y):
  def reset_first(x):
    x[0] = 999999
    return x

  if x[0] and reset_first(y):
    pass
  return y

dynamic_ret = foo(T(False), T(0))[0].item()
static_ret = to_static(foo)(T(False), T(0))[0].item()
assert dynamic_ret == static_ret, "dynamic_ret: %s, static_ret: %s" %(dynamic_ret, static_ret)
```

输出日志：

```
Traceback (most recent call last):
  File "a.py", line 18, in <module>
    assert dynamic_ret == static_ret, "dynamic_ret: %s, static_ret: %s" %(dynamic_ret, static_ret)
AssertionError: dynamic_ret: 0, static_ret: 999999
```

上述日志显示to_static(foo)和foo的行为不一致，to_static(foo)没有遵循逻辑截断的原则，仍然执行了reset_first函数所对应的op。

### 其他补充信息 Additional Supplementary Information

编译paddle所用的代码版本: develop:e44ff495346eab962bcaa764778f0cabc78dfce6

**Comment by Aurelius84** [comment]
reset_first(y) 总是会在组网期被评估执行，因为x[0] 在组网期没有数据区，无法触发Python端and语句的「逻辑截断」，可以思考下在深度学习框架静态图下如何实现上述逻辑，且可以触发逻辑截断的组网代码

**Comment by Aurelius84** [comment]
对于 `if x[0] and reset_first(y):`  似乎可以借助之前讨论的： `IfElse(IfElse(x[0], lambda: TrueTensor, lambda: reset_first(y)), true_body, false_body)` 来解决
