### ISSUE TITLE
利用官网提供的镜像，在P4机器上编译release_2.4的whl包，在V100机器上跑存在bug

### ISSUE THREAD

**Issue by yc556600** [PaddlePaddle/Paddle#50361]
### bug描述 Describe the Bug

分支：release_2.4
编译镜像：registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.2-cudnn8-gcc82
编译机器：
![image](https://user-images.githubusercontent.com/12397350/217725798-009d4a23-0e8a-4380-bd3b-1e7ca0e25813.png)

编译步骤：
```
mkdir build
cmake .. -DPY_VERSION=3.8 -DWITH_GPU=ON -DCMAKE_BUILD_TYPE=Release -DCUDA_ARCH_NAME=Auto
make -j32
``` 
得到的whl包，安装至V100机器
![image](https://user-images.githubusercontent.com/12397350/217725877-e2275c24-8c46-4abc-999a-375787a20163.png)

dropout得到的结果为0
![image](https://user-images.githubusercontent.com/12397350/217726084-3050d872-14f5-4cd8-8c6c-ee25e3831bb1.png)

示例代码：
```python
import paddle

paddle.enable_static()
import paddle.fluid as fluid
import numpy as np

x = fluid.layers.data(name="x", shape=[32, 32], dtype="float32")
droped = fluid.layers.dropout(x, dropout_prob=0.5)
place = fluid.CUDAPlace(0)
exe = fluid.Executor(place)
exe.run(fluid.default_startup_program())
np_x = np.random.random(size=(32, 32)).astype('float32')
output = exe.run(feed={"x": np_x}, fetch_list = [droped])
print(output)
```

**Comment by minghaoBD** [comment]
建议先在同一台机器编译和安装，看是否有这个问题。

**Comment by yc556600** [comment]
> 建议先在同一台机器编译和安装，看是否有这个问题。

同一台机器上编译使用没有问题

**Comment by minghaoBD** [comment]
嗯那可能是底层cuda/tensor core架构导致的。那就不建议跨约不同的gpu架构编译和使用了。

**Comment by yc556600** [comment]
> 嗯那可能是底层cuda/tensor core架构导致的。那就不建议跨约不同的gpu架构编译和使用了。

但是官网的 https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html  里的whl包可以用啊，这是啥原因

**Comment by minghaoBD** [comment]
CUDA_ARCH_BIN=70 80
CUDA_ARCH_NAME=Manual
