### ISSUE TITLE
麒麟系统如何安装低版本的paddlepaddle

### ISSUE THREAD

**Issue by yqp1453552101** [PaddlePaddle/Paddle#50402]
在麒麟系统安装低版本的paddlepaddle

想在麒麟系统安装2.2.2版本的paddlepaddle，请问如何安装

**Comment by lyuwenyu** [comment]
1. 源码编译安装
2. 在这里找下预编译的历史版本 https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
