### ISSUE TITLE
import Paddle的时候因为BRPC版本冲突导致进程crash

### ISSUE THREAD

**Issue by larrylian** [PaddlePaddle/Paddle#50408]
### bug描述 Describe the Bug

我的python里先import了一个 有brpc so的模块， 然后再import paddle。 就导致了进程crash。
怀疑是两边的brpc版本不同 导致so导入的时候冲突了。  然后发现paddle== 1.8.2没问题。  2.0.0以上就有问题了。  
问下现在paddle brpc用的什么版本。 然后有办法改版本和绕过不？
![image](https://user-images.githubusercontent.com/11072802/217998921-970686cb-c088-49d1-8157-b686f660a7d1.png)

**Comment by lyuwenyu** [comment]
你用的paddle是什么版本的  所有的2.0以上的都有这个问题？

**Comment by larrylian** [comment]
brpc-0.9.7-rc05.tar.gz  我们的brpc用的是这个版本。 你们用的brpc是什么版本，我尝试去看 都看不出来

**Comment by lyuwenyu** [comment]
这个建议你看下使用的paddle版本 在相应分支的cmake里搜一下相关的版本
<img width="856" alt="image" src="https://user-images.githubusercontent.com/17582080/218080413-55586e05-2dd3-4284-8c66-db5a22e32fc4.png">

**Comment by larrylian** [comment]
> 这个建议你看下使用的paddle版本 在相应分支的cmake里搜一下相关的版本 <img alt="image" width="856" src="https://user-images.githubusercontent.com/17582080/218080413-55586e05-2dd3-4284-8c66-db5a22e32fc4.png">

嗯嗯， 这个我之后看下。  另外你们是否考虑隐藏一下你们dlopen的so的符号呢？  用编译选项 "-Wl,--version-script" 这样可以一定程度避免和用户自己的so的符号冲突。

**Comment by lyuwenyu** [comment]
收到  多谢反馈 我们会讨论一下

**Comment by larrylian** [comment]
Hi, thanks. I will reply to you soon when I'm back.
