### ISSUE TITLE
未指定init_model_path情况下，默认设置了init_model_path

### ISSUE THREAD

**Issue by hikkinight** [PaddlePaddle/Paddle#5042]
提交任务时，在没有显示指定init_model_path情况下，init_model_path被指定为
/user/score-int/pangrenming/wenda_paddle_model_sum。
在自身集群里检查不到该文件导致任务失败。

![3](https://user-images.githubusercontent.com/1262600/31929996-acc2fca8-b8d0-11e7-8a07-bc194067ca1b.png)

**Comment by hedaoyuan** [comment]
可以在job.sh中打印一下`init_model_path`试一下，应该是设置了才会去检查初始模型。

**Comment by typhoonzero** [comment]
在提交作业的时候指定下面几个参数为空防止被其他用户的参数覆盖即可：
```
./paddle cluster_train
...
--init_model_path \"\" \
--train_meta_data_path \"\" \
--test_meta_data_path \"\" \
```

**Comment by hikkinight** [comment]
我仔细看了下，好像是我的任务init_model_path被其他任务给覆盖了，还能这样啊......
