### ISSUE TITLE
DataLoader关于dtype和place的问题

### ISSUE THREAD

**Issue by ZhangzrJerry** [PaddlePaddle/Paddle#50426]
经过我的排查,我发现尽管我自定义`dataset`输出的是`np.astype('float32')`,`paddle.io.DataLoader`迭代器给出的数据都是`dtype=float64, place=Place(gpu_pinned)`
我把代码修改为如下即可正常运行
```py
trainloader = paddle.io.DataLoader(MyDataset())
paddle.set_device('gpu')
for x in trainloader:
    print(x)
    break
a = paddle.to_tensor(x[0], place='gpu:0', dtype='float32')
b = paddle.to_tensor(x[1], place='gpu:0', dtype='float32')
c = paddle.to_tensor(x[2], place='gpu:0', dtype='float32')
MyNet()(a,b,c)
```

_Originally posted by @ZhangzrJerry in https://github.com/PaddlePaddle/Paddle/issues/50273#issuecomment-1425776204_

**Comment by ZhangzrJerry** [comment]
正如我在这里提到的 https://github.com/PaddlePaddle/Paddle/issues/50273#issuecomment-1425771640
我在dataset中重写的getitem方法下返回np.astype('float32')的数据,但放入dataloader后数据类型就会变成float64并且device会变成undefined的gpu_pinned

**Comment by lyuwenyu** [comment]
这个试一下  np.astype(np.float32)呢

**Comment by heavengate** [comment]
请提供一下Paddle版本，环境版本及复现demo，我们排查一下

**Comment by ZhangzrJerry** [comment]
关于数据类型的定义看起来是我在格式转换时的疏忽,但是还有一个问题看起来不是数据类型为float64引起的
***
paddle-gpu 2.4.1
ubuntu 22.04.1LTS
cuda 11.7
cudnn 8.7
***
```pyimport numpy as np
import paddle
class MyDataset(paddle.io.Dataset):
    def __init__(self):
        pass
    def __getitem__(self, idx):
        return np.ones((1,7)).astype('float32')
    def __len__(self):
        return 1
    pass

mydataset = MyDataset()
mydataset[0]
paddle.to_tensor(mydataset[0])
mydataloader = paddle.io.DataLoader(mydataset,batch_size=1)
for x in mydataloader:
    print(x)
    lstm = paddle.nn.LSTM(
        input_size=1,
        hidden_size=1,
        num_layers=1,
        time_major=False
    )
    lstm(x)
    break
```
这看起来是lstm层的一个问题
```
Tensor(shape=[1, 1, 7], dtype=float32, place=Place(gpu_pinned), stop_gradient=True,
       [[[1., 1., 1., 1., 1., 1., 1.]]])
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6d0f6dc5-19a2-4a62-b711-0c615d2822f8)
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
Cell In[13], line 18
     16 for x in mydataloader:
     17     print(x)
---> 18     paddle.nn.LSTM(input_size=1,hidden_size=1)(x)
     19     break

File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py:948, in Layer.__call__(self, *inputs, **kwargs)
    945 if (not in_declarative_mode()) and (not self._forward_pre_hooks) \
    946     and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
    947     self._build_once(*inputs, **kwargs)
--> 948     return self.forward(*inputs, **kwargs)
    949 else:
    950     return self._dygraph_call_func(*inputs, **kwargs)

File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/nn/layer/rnn.py:1070, in RNNBase.forward(self, inputs, initial_states, sequence_length)
   1067 if initial_states is None:
   1068     state_shape = (self.num_layers * self.num_directions, -1,
   1069                    self.hidden_size)
-> 1070     initial_states = tuple([
   1071         paddle.fluid.layers.fill_constant_batch_size_like(
   1072             inputs, state_shape, dtype, 0, batch_index, 1)
   1073         for _ in range(self.state_components)
   1074     ])
...
    910 out.stop_gradient = True
    911 return out

NotImplementedError: (Unimplemented) Unsupported backend `Undefined` when casting it to paddle place type. (at /paddle/paddle/phi/core/compat/convert_utils.cc:103)
```

**Comment by heavengate** [comment]
用你提供的代码跑了下，dataloader返回是的数据类型是float32，不是float64
<img width="596" alt="截屏2023-02-13 下午6 56 21" src="https://user-images.githubusercontent.com/12605721/218439729-5ea1f2a2-3cd2-4bb2-9b10-02c88ccbe4ca.png">

**Comment by ZhangzrJerry** [comment]
额关于dtype的问题是我之前写代码时一点疏漏没转换好，但是我提供的这段代码会有些奇怪的报错，我尝试把x再用一次totensor才可以正常运行

> ```
> import paddle
> class MyDataset(paddle.io.Dataset):
>     def __init__(self):
>         pass
>     def __getitem__(self, idx):
>         return np.ones((1,7)).astype('float32')
>     def __len__(self):
>         return 1
>     pass
> 
> mydataset = MyDataset()
> mydataset[0]
> paddle.to_tensor(mydataset[0])
> mydataloader = paddle.io.DataLoader(mydataset,batch_size=1)
> for x in mydataloader:
>     print(x)
>     lstm = paddle.nn.LSTM(
>         input_size=1,
>         hidden_size=1,
>         num_layers=1,
>         time_major=False
>     )
>     lstm(x)
>     break
> ```
> 
> 这看起来是lstm层的一个问题
> 
> ```
> Tensor(shape=[1, 1, 7], dtype=float32, place=Place(gpu_pinned), stop_gradient=True,
>        [[[1., 1., 1., 1., 1., 1., 1.]]])
> Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?6d0f6dc5-19a2-4a62-b711-0c615d2822f8)
> ---------------------------------------------------------------------------
> NotImplementedError                       Traceback (most recent call last)
> Cell In[13], line 18
>      16 for x in mydataloader:
>      17     print(x)
> ---> 18     paddle.nn.LSTM(input_size=1,hidden_size=1)(x)
>      19     break
> 
> File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/fluid/dygraph/layers.py:948, in Layer.__call__(self, *inputs, **kwargs)
>     945 if (not in_declarative_mode()) and (not self._forward_pre_hooks) \
>     946     and (not self._forward_post_hooks) and (not self._built) and in_dygraph_mode() and (not in_profiler_mode()):
>     947     self._build_once(*inputs, **kwargs)
> --> 948     return self.forward(*inputs, **kwargs)
>     949 else:
>     950     return self._dygraph_call_func(*inputs, **kwargs)
> 
> File ~/anaconda3/envs/globalenv/lib/python3.10/site-packages/paddle/nn/layer/rnn.py:1070, in RNNBase.forward(self, inputs, initial_states, sequence_length)
>    1067 if initial_states is None:
>    1068     state_shape = (self.num_layers * self.num_directions, -1,
>    1069                    self.hidden_size)
> -> 1070     initial_states = tuple([
>    1071         paddle.fluid.layers.fill_constant_batch_size_like(
>    1072             inputs, state_shape, dtype, 0, batch_index, 1)
>    1073         for _ in range(self.state_components)
>    1074     ])
> ...
>     910 out.stop_gradient = True
>     911 return out
> 
> NotImplementedError: (Unimplemented) Unsupported backend `Undefined` when casting it to paddle place type. (at /paddle/paddle/phi/core/compat/convert_utils.cc:103)
> ```

**Comment by ZhangzrJerry** [comment]
当我这么写就没问题
```diff
import paddle
class MyDataset(paddle.io.Dataset):
    def __init__(self):
        pass
    def __getitem__(self, idx):
        return np.ones((1,7)).astype('float32')
    def __len__(self):
        return 1
    pass

mydataset = MyDataset()
mydataset[0]
paddle.to_tensor(mydataset[0])
mydataloader = paddle.io.DataLoader(mydataset,batch_size=1)
for x in mydataloader:
    print(x)
    lstm = paddle.nn.LSTM(
        input_size=1,
        hidden_size=1,
        num_layers=1,
        time_major=False
    )
 +   x=paddle.to_tensor(x, place="gpu:0")
    lstm(x)
    break

**Comment by ZhangzrJerry** [comment]
怎么让dataloader返回的值直接为paddle的float32类型的tensor
