### ISSUE TITLE
反向调用API

### ISSUE THREAD

**Issue by Jaason19** [PaddlePaddle/Paddle#50435]
请问在eager下，是否有方法直接调用op反向计算函数？
比如add_grad的输入有x, y, dout, axis, 输出有dx和dy，我想尝试不同的输入得到输出，请问有什么方法吗？
最好是类似python端调用，比如最理想情况：dx, dy = paddle.add_grad(x, y, dout, axis) 
```
template <typename T, typename Context>
void AddGradKernel(const Context& dev_ctx,
                   const DenseTensor& x,
                   const DenseTensor& y,
                   const DenseTensor& dout,
                   int axis,
                   DenseTensor* dx,
                   DenseTensor* dy) {
  phi::AddGradImpl<T>(dev_ctx, x, y, dout, axis, dx, dy, AddGradFunc<T>);
}
```

**Comment by zhiboniu** [comment]
可以尝试直接调用xxxop_grad试试行不行，_grad表示反向op，应该都是一样注册过可调用的

**Comment by Jaason19** [comment]
> 可以尝试直接调用xxxop_grad试试行不行，_grad表示反向op，应该都是一样注册过可调用的

![image](https://user-images.githubusercontent.com/92357709/218424375-58e8dcf5-0b03-40c3-922b-b68aa27582d7.png)

@zhiboniu 应该是没有bind到python 还有什么方式可以调吗？

**Comment by zhiboniu** [comment]
你这个libpaddle.eager.ops的使用方式我不大熟，可以参考def add函数里的类似实现试试
    if in_dygraph_mode():
        return _C_ops.add(x, y)
    else:
        if _in_legacy_dygraph():
            return _legacy_C_ops.elementwise_add(x, y)
        else:
            return _elementwise_op(LayerHelper('elementwise_add', **locals()))

**Comment by Jaason19** [comment]
这里的_C_ops中不含add_grad，所以没法调用

**Comment by zhiboniu** [comment]
咨询了相关同学，目前没有开放反向api的python接口，无法直接调用
