### ISSUE TITLE
Paddle V2 通过receiver提交MPI任务，版本不支持square_error_cost

### ISSUE THREAD

**Issue by hikkinight** [PaddlePaddle/Paddle#5043]
通过receiver提交时，似乎不能指定paddle版本？这个时候怎么使用paddle.layer.square_error_cost呢？
`train_dnn_model(num_pass=num_pass)
File "conf/trainer_config.conf", line 87, in train_dnn_model
[cost, output, label] = fc_net(dict_dim)
File "conf/trainer_config.conf", line 75, in fc_net
cost = paddle.layer.square_error_cost(input=inference, label=label)
AttributeError: 'module' object has no attribute 'square_error_cost'`

**Comment by typhoonzero** [comment]
receiver不能指定版本。可以使用`mse_cost`，实现其实是一样的。

**Comment by hikkinight** [comment]
paddle.layer.mse_cost？
