### ISSUE TITLE
飞桨昇腾 NPU 版安装问题

### ISSUE THREAD

**Issue by FlickerMi** [PaddlePaddle/Paddle#50462]
### 请提出你的问题 Please ask your question

参照该文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html

环境：`npu-smi info`

+-------------------------------------------------------------------------------------------+
| npu-smi 22.0.0.3                 Version: 22.0.0.3                                                                                |
+----------------------+---------------+----------------------------------------------------+
| NPU   Name                  | Health              | Power(W)    Temp(C)           Hugepages-Usage(page)  |
| Chip                               | Bus-Id              | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)   |
+======================+===============+===========================+
| 1      910PremiumA       | Warning           | 84.4              36                         15   / 15                       |
| 0                                    | 0000:81:00.0   | 0                   854  / 15170         0    / 32768         |
+======================+===============+=========================+

**我是直接通过源码编译安装，并未使用docker**

```
# 下载源码
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle

# 创建编译目录
mkdir build && cd build

# 执行 cmake
cmake .. -DPY_VERSION=3.7 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON \
         -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# 使用以下命令来编译
make TARGET=ARMV8 -j$(nproc)

# 安装命令
python -m pip install -U paddlepaddle_npu-0.0.0-cp37-cp37m-linux_aarch64.whl

```

**最后我使用验证命令，并未返回npu，而是返回了cpu，请问问题出在哪儿？**

`python -c "import paddle; paddle.utils.run_check()"`

Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
W0213 18:16:36.562826 43452 fuse_all_reduce_op_pass.cc:76] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
I0213 18:16:36.563867 43452 parallel_executor.cc:484] Cross op memory reuse strategy is enabled, when build_strategy.memory_optimize = True or garbage collection strategy is disabled, which is not recommended
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by wangxinxin08** [comment]
可以尝试使用下docker进行编译，可能是一些环境变量没有正确配置，导致检测不到相关的动态链接库而直接编译的CPU版本

**Comment by FlickerMi** [comment]
> 可以尝试使用下docker进行编译，可能是一些环境变量没有正确配置，导致检测不到相关的动态链接库而直接编译的CPU版本

谢谢，不过我这边不能用docker，能说说可能有哪些环境变量会影响到吗？

**Comment by wangxinxin08** [comment]
应该是和CANN相关的环境变量，比如CANN的动态链接库是否添加到LD_LIBRARY_PATH

**Comment by qili93** [comment]
您好，请问您这里编译的 NPU 代码是 Paddle develop 分支的最新代码吗？

目前  Paddle 和昇腾 NPU的适配已经全面转为插件式，develop 分支上遗留的 NPU 代码我们会在后续进行清理。

请参考此文档进行飞桨+昇腾的编译与安装，以及后续的功能和模型验证

https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

**Comment by FlickerMi** [comment]
> 您好，请问您这里编译的 NPU 代码是 Paddle development 分支的最新代码吗？
> 
> 目前 Paddle 和昇腾 NPU的适配已经全面转为插件式，develop分支上遗留的 NPU 代码我们会在后续进行清理。
> 
> 请参考此文档进行飞桨+昇腾的编译与安装，以及后续的功能和模型验证
> 
> https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

使用PaddleCustomDevice中的方法编译一直报错呢，麻烦看看那个项目中的Issue。

**Comment by minboo** [comment]
好兄弟，你安装成功了吗

**Comment by FlickerMi** [comment]
> 好兄弟，你安装成功了吗

不行，CANN版本和paddle支持的版本不适配，放弃了。
