### ISSUE TITLE
这里调用了paddle.nn.initializer.ConstantInitializer这个函数会core

### ISSUE THREAD

**Issue by zstbackcourt** [PaddlePaddle/Paddle#50470]
https://github.com/PaddlePaddle/Paddle/blob/8df8cb107147e7e68d8518feb147b35193bca650/python/paddle/fluid/contrib/layers/metric_op.py#L150
调用了paddle.nn.initializer.ConstantInitializer这个函数，但是脚本没有import paddle所以会core
![0fa8fd911b9047cf3bf651cdb7fb78d6](https://user-images.githubusercontent.com/6514291/218460393-f26f9571-27f2-4af4-95a9-df2143dc68d4.png)

**Comment by wangxinxin08** [comment]
感谢你的反馈，我们验证下
