### ISSUE TITLE
format label_min ValueError: label should not out of bound, but gotTensor shape=[1], dtype=int64, place=CUDAPlace 0 , stop_gradient=True, [-1]

### ISSUE THREAD

**Issue by ShonLy** [PaddlePaddle/Paddle#50476]
### 请提出你的问题 Please ask your question

/usr/lib/python3/dist-packages/urllib3/util/selectors.py:14: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import namedtuple, Mapping
/usr/lib/python3/dist-packages/urllib3/_collections.py:2: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import Mapping, MutableMapping
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:36: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.NEAREST or Dither.NONE instead.
'nearest': Image.NEAREST,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:37: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.BILINEAR instead.
'bilinear': Image.BILINEAR,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:38: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.BICUBIC instead.
'bicubic': Image.BICUBIC,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:39: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.BOX instead.
'box': Image.BOX,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:40: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.LANCZOS instead.
'lanczos': Image.LANCZOS,
/usr/local/lib/python3.7/dist-packages/paddle/vision/transforms/functional_pil.py:41: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10
2023-07-01
. Use Resampling.HAMMING instead.
'hamming': Image.HAMMING
/usr/local/lib/python3.7/dist-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
"When training, we now always track global mean and variance."
Traceback
most recent call last
:
File "/project/train/src_repo/PaddleSeg/train.py", line 262, in <module>
main
args
File "/project/train/src_repo/PaddleSeg/train.py", line 254, in main
to_static_training=cfg.to_static_training
File "/project/train/src_repo/PaddleSeg/paddleseg/core/train.py", line 211, in train
losses=losses
File "/project/train/src_repo/PaddleSeg/paddleseg/core/train.py", line 55, in loss_computation
loss_list.append
coef_i * loss_i
logits, labels
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
return self._dygraph_call_func
*inputs, **kwargs
File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
outputs = self.forward
*inputs, **kwargs
File "/project/train/src_repo/PaddleSeg/paddleseg/models/losses/cross_entropy_loss.py", line 86, in forward
weight=self.weight
File "/usr/local/lib/python3.7/dist-packages/paddle/nn/functional/loss.py", line 1659, in cross_entropy
format
label_min
ValueError: label should not out of bound, but gotTensor
shape=[1], dtype=int64, place=CUDAPlace
0
, stop_gradient=True,
[-1]

![image](https://user-images.githubusercontent.com/61611859/218520411-9c12c2db-1248-4fdb-8f96-06bd08c14176.png)

--------------------------------------------------------------------------------------------------------------------------
label之前都检查了，全是单通道的0和1，它为什么说label有-1的情况啊

**Comment by WenmuZhou** [comment]
这个辛苦在paddleseg下提问

**Comment by juncaipeng** [comment]
建议关注PaddleSeg下相同的issue，已经有回复。

https://github.com/PaddlePaddle/PaddleSeg/issues/2972
