### ISSUE TITLE
win10+cuda10.2+cudnnv7.6.5 使用 PaddleTensorRT 推理的问题

### ISSUE THREAD

**Issue by ZJDATY** [PaddlePaddle/Paddle#50485]
### 请提出你的问题 Please ask your question

我仔细阅读的官方的说明文档，非安培架构的GPU建议使用cuda10 。 然后我就遇到了不少问题。
![image](https://user-images.githubusercontent.com/29767049/218645787-191e4385-ea88-46e0-81c5-02d963afd916.png)
上图所示 ，想使用 PaddleTensorRT 推理，需配合 TensorRT7.0.0.11。于是我就下载了win版的tenserrt7.0 .
![image](https://user-images.githubusercontent.com/29767049/218645946-473a91e0-8779-4a16-984d-5c45568d17f1.png)
这里面并没有python这个文件夹。去官网找了一圈也没能找到怎么安装windows平台的 tenserrt-7.0.0.11 .
![image](https://user-images.githubusercontent.com/29767049/218646249-d0901482-292b-4930-8617-71cb9a06a2a8.png)
 新版本的里面直接就有 tenserrt 的python 包。
请问我该怎么办。
第一张图上并没有写，windows平台不支持安装 tenserrt-7.0.0.11 。如果是确实不支持，还麻烦官方能加上这句话。省得别人也被浪费许多时间。

**Comment by JZZ-NOTE** [comment]
你好，windows平台是支持安装 tenserrt-7.0.0.11。下载解压，并把 lib目录设置到环境变量即可。不需要寻找python目录。

**Comment by ZJDATY** [comment]
> 你好，Windows平台是支持安装 tenserrt-7.0.0.11。下载解压，并把 lib目录设置到环境变量即可。不需要寻找python目录。

ok
 o感谢
