### ISSUE TITLE
【文档】关于《分组切分并行》文档中的效果有疑问

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/Paddle#50482]
### 文档链接&描述 Document Links & Description

有问题的文档：【分布式训练 - 分组切分并行】https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/group_sharded_parallel_cn.html

在该文档的【二、功能效果】中，列出了以下表格：

setting | GPU Mem | Speed
-- | -- | --
GroupSharded—off | 30474 MB | 9344 tokens/s
GroupSharded—on N2C16 | 30160 MB | 12663 tokens/s
GroupSharded—on N4C32 | 30190 MB | 22235 tokens/s

这是否说明：开启GroupSharded功能后（以 N2C16 为例），GPU内存仅仅从 30474MB 降到了 30160MB? 仅仅降低了 1%的内存占用？

如果我的理解有错误，请指出我的错误，并解释以上表格的正确含义；
如果我的理解正确，我很好奇这么低（1%）的内存降低，值得用4卡、8卡去启动该功能吗？

关于paddle官网GroupSharded文档，我对以上内容表示疑惑，请Paddle同学解答，非常感谢。

### 请提出你的建议 Please give your suggestion

（1）如果我的理解有错误，请指出我的错误，并解释以上表格的正确含义；
（2）如果我的理解正确，我很好奇这么低（1%）的内存降低，值得用4卡、8卡去启动该功能吗？请Paddle同学在此Issue中解答我的疑惑，感谢。
（3）如果可以，请在文档中给出一个最小可运行的示例代码，并且给出基于此代码《开启》/《关闭》分组切分功能的GPU内存占用对比，以表明这个功能确实有效（而不是仅降低1%这么少）。

**Comment by WenmuZhou** [comment]
和另一个有重复，这个我先关闭了

**Comment by kehuo** [comment]
> 和另一个有重复，这个我先关闭了

感谢回复。

其实也没有完全重复，因为当前issue的是对【二、功能效果】中表格的含义有疑问。
另外一个 [issue 50483](https://github.com/PaddlePaddle/Paddle/issues/50483) 主要是对 【三、示例代码】中的代码，以及我自己运行结果有疑问。

当然，如果这些问题（【二、的表格含义】+【三、的代码相关问题】）都会在 [issue 50483](https://github.com/PaddlePaddle/Paddle/issues/50483) 中回答的话，这个Issue可以关没问题～

**Comment by wuhuachaocoding** [comment]
![image](https://user-images.githubusercontent.com/77733235/218919678-f949106a-28ce-438e-a1cf-e9a9cb0619a1.png)

您好，关于【二、功能效果】里面描述了两方面的内容：
-1. Group-Sharded功能可以跑起来GPT(11.375B)的模型，如果不用该功能，用数据并行，会爆显存。
-2. 表格中的off, on是针对的hybrid-dp的功能，就是Group-Sharded可以和数据并行一起使用，比如：2机16卡， 机内使用Group-Sharded, 机器间使用数据并行， 也就是说机器内的情况和纯单机8卡一样，所以显存基本一样， 然而使用Group-Sharded + hybrid-dp 可以加速，这个区别于16卡全部使用Group-Sharded的功能，如果16卡全部使用Group-Sharded功能，显存确实会比这个少很多，但是速度会慢很多，也正如你所说，单机已经放得下这个模型，为啥还要用16卡去放呢？所以我们这里是Group-Sharded + hybrid-dp混合并行，增加机器数进一步加速，而非进一步生省下显存。
