### ISSUE TITLE
【文档】关于《分组切分并行》文档中的示例代码有疑问

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/Paddle#50483]
### 文档链接&描述 Document Links & Description

有问题的文档：【分布式训练 - 分组切分并行】https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/group_sharded_parallel_cn.html

在该文档的 【三、使用方法】部分提供了一段示例python代码。我对该代码存在以下疑惑：
（1）示例代码中定义了一个叫做 group 的变量：
```python
group = paddle.distributed.new_group([0, 1])
```

但是定义之后，整段代码其实根本没用到此变量，是否意味着这行代码是多余的？可以该示例中删除？

（2）我在自己8 x Nvidia GeForce 3090 的环境下运行了该文档的示例代码，得到的结论是开启分组切分并行功能后，每个GPU卡的内存占用仅仅降低了 6% （2229MiB/卡 -> 2083MiB/卡）。
以下是我运行的示例代码，如果我的使用方式不对，也请帮忙指正：

```python
import paddle
from paddle.vision.models import ResNet
from paddle.vision.models.resnet import BasicBlock
from paddle.distributed import fleet
from paddle.distributed.sharding import group_sharded_parallel, save_group_sharded_model


def main():
    """
    https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/group_sharded_parallel_cn.html

    grp_shd_demo.py 是用户运行动态图 GroupSharded 的 python 文件
    python -m paddle.distributed.launch --gpus=0,1,2,3,4,5,6,7 grp_shd_demo.py
    """
    fleet.init(is_collective=True)
    group = paddle.distributed.new_group([0, 1])
    use_pure_fp16 = True

    clip = paddle.nn.ClipGradByGlobalNorm(clip_norm=1.0)
    model = ResNet(BasicBlock, 18)
    optimizer = paddle.optimizer.AdamW(
        learning_rate=0.001,
        parameters=model.parameters(),
        weight_decay=0.00001,
        grad_clip=clip
    )

    scaler = None
    if use_pure_fp16:
        scaler = paddle.amp.GradScaler(init_loss_scaling=32768)
        # level O2 means converting the network to FP16
        model = paddle.amp.decorate(
            models=model,
            level='O2',
            save_dtype='float32')

    # wrap GroupSharded model, optimizer and scaler
    model, optimizer, scaler = group_sharded_parallel(model, optimizer, "os_g", scaler=scaler)

    for step_id in range(1, 500):
        x = paddle.rand([1, 3, 224, 224])
        with paddle.amp.auto_cast(use_pure_fp16):
            out = model(x)
        loss = out.mean()

        if use_pure_fp16:
            scaler.scale(loss).backward()
            scaler.step(optimizer)
            scaler.update()
        else:
            loss.backward()
            optimizer.step()
        optimizer.clear_grad()

        print("=== step_id : {}    loss : {}".format(step_id, loss.numpy()))

    # save model and optimizer state_dict
    output_dir = "./model_output"
    save_group_sharded_model(model, output_dir, optimizer)


if __name__ == "__main__":
    main()

```

结果：
(1) 8卡，**关闭**Group Sharded Parallel功能：
以 0号卡为例，内存占用 = 2229MiB
![Henory-Uxoge C-U11 Corpute w](https://user-images.githubusercontent.com/48248227/218642304-e07eb732-f02b-4dd2-adf7-8729375ad09c.png)

(2) 8卡，**开启**Group Sharded Parallel功能：
以 0号卡为例，内存占用 = 2083MiB，相比于关闭的情况，单卡GPU内存占用仅仅降低了 2299 - 2083 = 216MiB，降低比例等于 6%，很低很低。
![Feb 14 113316 2023](https://user-images.githubusercontent.com/48248227/218642287-36f87750-5908-4eff-ad57-ada080e30591.png)

请问8卡场景，每张卡只降低 6%的内存占用，是否符合预期？如果符合，请解释为什么这么低的性价比是否值得开启？如果不符合预期，请帮忙指正我的使用方法哪里有问题（我几乎完全照搬了官网文档的代码）？

感谢，期待回复。

**Comment by WenmuZhou** [comment]
您好，我们确认一下，会尽快回复您～

**Comment by wuhuachaocoding** [comment]
您好，具体原因如下：
（1）group是有用的，您在这里只使用Group_Sharded功能，所以就不用关心这个参数，Group_Sharded功能可以和数据并行混合使用，如果您想使用这种混合并行能力，就得设置group。

（2）您在这里使用的是Resnet18, fp16参数， Resnet的参数量为12M左右：
-参数： 12M * 2Byte = 24MB
-梯度：  12M * 2Byte = 24MB
-优化器状态： 12 M* （4 + 4 + 4）Byte = 144MB
您使用的是os-g模式， 即Group_Sharded功能仅仅对梯度和优化器进行切分节省：
（24MB + 144MB）/  8 = 168MB / 8 = 21MB
粗略估计每张卡大概节省： 168MB - 21MB = 147MB
模型中间变量就不算。

您观察到的节省显存太少的原因是，您使用的模型resent18参数量太少，您用数据并行就可以跑起来。当您的模型使用数据并行时都跑不起来的时候， group_sharded功能就会发挥出来。

**Comment by kehuo** [comment]
感谢回复。

小建议，既然是分组切分并行的示例代码，如果运行代码能提现出【开启】和【关闭】此功能带来内存上的显著变化，更有助于读者理解此功能，否则就像我这个Issue一样，开关后内存差距不大，反而容易带来“内存几乎没有降低，这个功能到底有没有生效”的疑惑～
