### ISSUE TITLE
飞桨 Ai studio

### ISSUE THREAD

**Issue by haoaZ** [PaddlePaddle/Paddle#50480]
### 请提出你的问题 Please ask your question

请问上传文件一直失败是怎么回事呀。
![Z1C833L28 YVM)8_E0GTI2M](https://user-images.githubusercontent.com/113076135/218629867-236df10a-d2e8-48fe-a85f-ba20e901ca1c.png)

**Comment by WenmuZhou** [comment]
文件太大了吗，aistudio对文件大小有限制了，再就是看看网络是不是不稳定
