### ISSUE TITLE
静态图存在非成对的StreamWaitEvent

### ISSUE THREAD

**Issue by ronny1996** [PaddlePaddle/Paddle#50505]
### bug描述 Describe the Bug

[workerlog.txt](https://github.com/PaddlePaddle/Paddle/files/10730978/workerlog.txt)

在runtime中打印 create_event, record_event, stream_wait_event，发现有stream_wait_event调用时，没有调用record_event，该问题导致使用PaddleCustomDevice npu时报错

**Comment by parap1uie-s** [comment]
补充信息：在NPU环境执行inference model推理（推理模型资源文件导出自paddle 1.8），整个项目基于Tornado构建了web服务。服务端第一次执行可以正常推理，第二次Crash。经NPU团队同学帮助定位问题原因，疑似Paddle执行器的问题。

Paddle版本：develop
运行环境：NPU
Python版本：python 3.7
运行模式：静态图
