### ISSUE TITLE
paddledetection多机多卡运行报错

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#50508]
### 请提出你的问题 Please ask your question

1、单机多卡运行正常
2、多机多卡运行报错，错误如下：
![5286a1a49f9d53a0ef46893e96f471df](https://user-images.githubusercontent.com/31760851/218758272-03793a9c-90a5-4689-9881-63414acc5f53.png)

**Comment by WenmuZhou** [comment]
能提供一下复现脚本吗
