### ISSUE TITLE
零维张量shape问题

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#50515]
### bug描述 Describe the Bug

零维Tensor的shape是否应该为[]

```python
import paddle

x = paddle.to_tensor(1)
print(x.shape)
'''
[1]
'''
```

**Comment by yghstill** [comment]
@linjieccc 你这样设置是set value为1的1维tensor，如果想要设置零维tensor，可以：
```python
a = paddle.to_tensor([])
```

**Comment by linjieccc** [comment]
我理解x = paddle.to_tensor(1)应该是一个零维张量，x.shape的输出应该是[]，表示该张量没有维度，这个和torch实现有diff

**Comment by zhwesky2010** [comment]
@linjieccc 你好这个问题我们后续会修复，目前to_tensor会把一个0D的Tensor转换成1D shape为[1]的Tensor

**Comment by zhwesky2010** [comment]
@linjieccc 你好，飞桨将于2.5版本全面支持0维Tensor，上述反馈的0D问题也将同时解决。

欢迎试用并安装develop 版本的paddle whl包，将体验最新的0维特性：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
安装命令：
`pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

---
Hello, Paddle will fully support the 0-dimensional Tensor in version 2.5, and the 0D issue will also be resolved at the same time.
Welcome to try and install the develop version of the paddle whl package, and you will experience the latest 0-dimensional features: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux -pip.html
Install Command:
`pip install paddlepaddle-gpu==0.0.0.post112 -f  https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html `
