### ISSUE TITLE
we use paddle2onnx to convert paddle static model to  onnx, it can not work , when can we support bitwise_and?

### ISSUE THREAD

**Issue by liroda** [PaddlePaddle/Paddle#50511]
### 需求描述 Feature Description

tts项目，paddle2onnx 转换过程报错？
[Paddle2ONNX] Oops, there are some operators not supported yet, including bitwise_and,

**Comment by yeliang2258** [comment]
您好，麻烦提供一下静态图的模型，我可以直接用Paddle2ONNX转换验证。
另外请问转换ONNX之后是用什么引擎部署到什么硬件上呢？
