### ISSUE TITLE
CUDA11.5安装哪个版本的paddlepaddle好？

### ISSUE THREAD

**Issue by YELLOWZAN** [PaddlePaddle/Paddle#50514]
### 请提出你的问题 Please ask your question

我的电脑显卡是GTX1650，CUDA11.5，请问安装哪一个版本的paddlepaddle好一点？
nvcc信息如下：
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_Sep_13_20:11:50_Pacific_Daylight_Time_2021
Cuda compilation tools, release 11.5, V11.5.50
Build cuda_11.5.r11.5/compiler.30411180_0

**Comment by 1196228233** [comment]
向下兼容，算力平台11.2版本试试。

**Comment by yghstill** [comment]
@YELLOWZAN cuda11.2 PaddlePaddle可以跑cuda11.5
