### ISSUE TITLE
Compile speed is slower than 1 month ago (13 minutes -> 22 minutes)

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#5051]
Following are two teamcity logs:
- [#6469 (24 Oct 17 16:19) ](https://paddleci.ngrok.io/viewLog.html?buildId=14601&buildTypeId=Paddle_PrCi&tab=buildLog#_state=64)
  -  It costs 27 minutes totally, 22 minutes for compiler.
  - 6 minutes (16:19-16:25) for compiling`WITH_GPU=False`
  - 16 minutes (16:25-16:41) for  compiling`WITH_GPU=true`
  - 4 minutes for unittest. (`Total Test time (real) = 230.80 sec`)
- [#5019 (30 Sep 17 03:49)](https://paddleci.ngrok.io/viewLog.html?buildId=10812&buildTypeId=Paddle_PrCi&tab=buildLog)
   -  It costs 17 minutes totally, 13 minutes for compiler.
  - 4 minutes (3:49-3:53) for compiling`WITH_GPU=False`
  - 9 minutes (3:53-4:02) for  compiling`WITH_GPU=true`
  - 2 minutes for unittest. (`Total Test time (real) = 137.64 sec`)

From 13 minutes to 22 minutes, current compile speed is almost 1 times slower than 1 month ago. Maybe the reason is that there are a lot of ops merged now. 

Hope somebody can help to make the compiler faster, which will make developing faster as well.

**Comment by luotao1** [comment]
The reason why teamcity compile both `WITH_GPU=False` and `WITH_GPU=True` is in https://github.com/PaddlePaddle/Paddle/issues/4476

**Comment by lcy-seso** [comment]
I felt recent days the compiling time become much slower (but I did not check exactly, I just can clearly feel the changes of compiling speed becomes much slower).

I changed a newly added file, but many files I did not change re-compiled. Are there any changes in the dependencies?

**Comment by wangkuiyi** [comment]
Is this due to book chapters being added into paddle/framework/tests/test_*?

**Comment by luotao1** [comment]
> Is this due to book chapters being added into paddle/framework/tests/test_*?

I think this is not the main reason, since this issue is created on Oct.24, when book chapters haven't been added in.

**Comment by wangkuiyi** [comment]
I noticed that in TeamCity log there are 

```
[21:12:28]	251/256 Test #233: test_seq_conv ............................... Passed 19.33 sec
[21:12:30]	252/256 Test #256: test_recommender_system .....................***Failed 8.88 sec
[21:12:30]	Cache file /root/.cache/paddle/dataset/movielens/ml-1m.zip not found, downloading http://files.grouplens.org/datasets/movielens/ml-1m.zip
[21:12:30]	[ ]
[21:12:30]	[= ]
[21:12:30]	[== ]
[21:12:30]	[=== ]
[21:12:30]
```

which means that our book chapter tests in `python/paddle/v2/framework/tests` are downloading datasets.

This would definitely cause slow CI tests.

**Comment by luotao1** [comment]
close due to #5712 and #5491
