### ISSUE TITLE
从头编译paddle生成whl与指定的python版本不一致

### ISSUE THREAD

**Issue by MARD1NO** [PaddlePaddle/Paddle#50540]
### bug描述 Describe the Bug

从头编译Paddle，尽管指定了 PY_VERSION，但也有可能编译出非指定的python包。

比如指定PY_VERSION=3.8，编译出3.7的包

还有一些其他奇怪的现象，在不新增文件的情况下，单独修改原有文件有可能触发重新cmake

### 其他补充信息 Additional Supplementary Information

cmake选项：
```
cmake .. \
        -DPY_VERSION=3.8 \
        -DCMAKE_BUILD_TYPE=Release \
        -DWITH_PYTHON=ON \
        -DWITH_AVX=ON \
        -DWITH_MKL=ON \
        -DWITH_MKLDNN=ON \
        -DWITH_GPU=ON \
        -DWITH_NCCL=ON \
        -DCMAKE_CXX_FLAGS="-Wno-error -w" \
        -DWITH_DISTRIBUTE=ON \
        -DON_INFER=ON \
        -DWITH_TESTING=OFF \
        -DWITH_INFERENCE_API_TEST=OFF \
        -DCUDA_ARCH_NAME=Auto
```

<img width="1315" alt="image" src="https://user-images.githubusercontent.com/42901638/222039869-24a74dbc-e7b4-40f9-8fe8-b4aa4f1284df.png">

**Comment by yangy996** [comment]
系统上装的python版本是3.7的，必须转3.8的python才能编译出来
