### ISSUE TITLE
trt  matmul fc类op存在精度问题

### ISSUE THREAD

**Issue by b3602sss** [PaddlePaddle/Paddle#50543]
### bug描述 Describe the Bug
在输入shape与opt shape相差较大时存在精度问题, 
复现方式(在 Paddle/python/paddle/fluid/tests/unittests/ir/inference/ 目录下新建一个.py文件 复制下面的代码, 直接运行就可以)：
mul最后会被convert成trt fc
mul fp32 时最大相对误差 > 0.05
mul fp16 时最大相对误差 > 100
```
import unittest

import hypothesis.strategies as st
from auto_scan_test import IgnoreReasons, PassAutoScanTest
from program_config import OpConfig, ProgramConfig, TensorConfig
import paddle.inference as paddle_infer

class TestMapMatmulToMulPass(PassAutoScanTest):
    r"""
    x_var    y_var(persistable)
      \       /
      matmul_v2
    """

    def sample_predictor_configs(self, program_config):
        # TRT
        config = self.create_trt_inference_config()
        config.enable_tensorrt_engine(
             max_batch_size=10,
             workspace_size=4194304,
             min_subgraph_size=0,
             precision_mode=paddle_infer.PrecisionType.Half,
             use_static=False,
            use_calib_mode=False)

        config.set_trt_dynamic_shape_info(
            {
                "matmul_x": [1, 64, 312],
                "matmul_y": [312, 312],
            },
            {
                "matmul_x": [64, 64, 312],
                "matmul_y": [312, 312],
            },
            {
                "matmul_x": [32, 64, 312],
                "matmul_y": [312, 312],
            },
        )
        yield config, ["mul", ], (1e-3, 1e-3)

    def sample_program_config(self, draw):
        # 1. Generate shape and attr of matmul
        x_shape = [1, 64, 312]
        y_shape = [312, 1248]
        alpha = 1.0
        transpose_X = False
        transpose_Y = False

        matmul_op = OpConfig(
            "matmul_v2",
            inputs={"X": ["matmul_x"], "Y": ["matmul_y"]},
            outputs={"Out": ["matmul_out"]},
            alpha=alpha,
            trans_x=transpose_X,
            trans_y=transpose_Y,
        )

        ops = [
            matmul_op,
        ]
        weights = {
            "matmul_y": TensorConfig(shape=y_shape),
        }
        inputs = {
            "matmul_x": TensorConfig(shape=x_shape),
        }
        program_config = ProgramConfig(
            ops=ops,
            weights=weights,
            inputs=inputs,
            outputs=ops[-1].outputs["Out"],
        )
        return program_config

    def test(self):
        self.run_and_statis(
            quant=False,
            max_examples=1,
            min_success_num=1,
            passes=["trt_map_matmul_v2_to_mul_pass"],
        )


if __name__ == "__main__":
    unittest.main()
```
测试二 ：
matmul_v2 fp32 时最大绝对误差 >1e-4
matmul_v2 fp16 时最大绝对误差 > 0.2
```
import os
import unittest
from functools import partial
from typing import List

import numpy as np
from program_config import ProgramConfig, TensorConfig
from trt_layer_auto_scan_test import TrtLayerAutoScanTest

import paddle.inference as paddle_infer

class TrtConvertMatmulTest_dynamic2(TrtLayerAutoScanTest):
    def sample_program_configs(self):
        def generate_input(shape):
            return np.random.random(shape).astype(np.float32)

        for batch in [1,2,4]:
            for trans_x in [False]:
                for trans_y in [False]:
                    input1_shape = [batch, 64, 312]
                    input2_shape = [312, 1248]
                    dics = [
                        {
                            "trans_x": trans_x,
                            "trans_y": trans_y,
                        }
                    ]
                    ops_config = [
                        {
                            "op_type": "matmul_v2",
                            "op_inputs": {
                                "X": ["input1_data"],
                                "Y": ["input2_data"],
                            },
                            "op_outputs": {"Out": ["output_data"]},
                            "op_attrs": dics[0],
                        }
                    ]
                    ops = self.generate_op_config(ops_config)

                    program_config = ProgramConfig(
                        ops=ops,
                        weights={  "input2_data": TensorConfig(
                            data_gen=partial(generate_input, input2_shape)
                        ),},
                        inputs={
                            "input1_data": TensorConfig(
                                data_gen=partial(generate_input, input1_shape)
                            ),
                        },
                        outputs=["output_data"],
                    )

                    yield program_config

    def sample_predictor_configs(
        self, program_config
    ) -> (paddle_infer.Config, List[int], float):
        def generate_dynamic_shape(attrs):
            self.dynamic_shape.min_input_shape = {
                "input1_data": [1, 64, 312],
                "input2_data": [312, 1248],
            }
            self.dynamic_shape.max_input_shape = {
                "input1_data": [4, 64, 312],
                "input2_data": [312, 1248],
            }
            self.dynamic_shape.opt_input_shape = {
                "input1_data": [2, 64, 312],
                "input2_data": [312, 1248],
            }

        attrs = [
            program_config.ops[i].attrs for i in range(len(program_config.ops))
        ]
        # The output has little diff between gpu and trt in CI-Windows-Inference
        tol_fp32 = 1e-5
        tol_half = 1e-5
        if os.name == 'nt':
            tol_fp32 = 1e-3
            tol_half = 1e-3
        # for dynamic_shape
        generate_dynamic_shape(attrs)
        self.trt_param.precision = paddle_infer.PrecisionType.Float32
        yield self.create_inference_config(), (1, 2), tol_fp32

    def add_skip_trt_case(self):
        pass

    def test(self):
        self.add_skip_trt_case()
        self.run_test()

if __name__ == "__main__":
    unittest.main()```

**Comment by leo0519** [comment]
Hi @b3602sss ,

Could you please provide the runtime configuration (ex. hardware, docker image)?

**Comment by b3602sss** [comment]
> 

gpu : T4 
software : cuda11.7 cudnn8.6 trt 8.5 or cuda11.7-cudnn8.4-trt8.4
docker paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.7-cudnn8.4-trt8.4

**Comment by leo0519** [comment]
Hi @b3602sss ,

The reproduce steps are as follows:

1. `docker run -it --rm paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.7-cudnn8.4-trt8.4`
2. `git clone https://github.com/leo0519/Paddle.git --branch matmul-tol`
3. `pip install hypothesis`
4. `cd Paddle/python/paddle/fluid/tests/unittests/ir/inference`
5. `python test.py`

在執行 `test.py` 時，可以用環境變數 PRECISION 控制測試精度 (ex. `PRECISION=FP16 python test.py`) (default FP32)，也可用環境變數 K_SIZE 控制矩陣乘 K 的大小 (ex `K_SIZE=156 python test.py`) (default 312)

以下有兩段解釋


1.  在執行 `PRECISION=FP32 python test.py` 時，會有一段額外的 log 如下
     ```
     The index of the max rel_err is (0, 31, 176)              # relative error 最大的 index
     The corresponding element in baseline is 1.9073486e-05    # Baseline 的值
     The corresponding element in TRT result is 1.8119812e-05  # Paddle-TRT 的結果
     ```
     矩陣乘因為算法的不同，是會有些微誤差的，但因某些 elements 最後結果太接近 0，才使得相對誤差被放大
2.  矩陣乘的 K 越大，會導致最後結果的 absolute error 放大，因為不同算法累加的方式不一樣
     可以試試 `K_SIZE=156 python test.py` 便能通過測試

**Comment by leo0519** [comment]
另外有關**在輸入 shape 與 opt shape 相差較大时存在精度問題**，我在 local 測試過將 opt shape 改為 [1, 64, 312] (輸入 shape 也是 [1, 64, 312]) 仍會出現相同的精度問題，因此該問題與輸入 shape 和 opt shape 應無關~

**Comment by b3602sss** [comment]
> Hi @b3602sss ,
> 
> The reproduce steps are as follows:
> 
> 1. `docker run -it --rm paddlepaddle/paddle:2.4.0rc0-gpu-cuda11.7-cudnn8.4-trt8.4`
> 2. `git clone https://github.com/leo0519/Paddle.git --branch matmul-tol`
> 3. `pip install hypothesis`
> 4. `cd Paddle/python/paddle/fluid/tests/unittests/ir/inference`
> 5. `python test.py`
> 
> 在執行 `test.py` 時，可以用環境變數 PRECISION 控制測試精度 (ex. `PRECISION=FP16 python test.py`) (default FP32)，也可用環境變數 K_SIZE 控制矩陣乘 K 的大小 (ex `K_SIZE=156 python test.py`) (default 312)
> 
> 以下有兩段解釋
> 
> 1. 在執行 `PRECISION=FP32 python test.py` 時，會有一段額外的 log 如下
>    ```
>    The index of the max rel_err is (0, 31, 176)              # relative error 最大的 index
>    The corresponding element in baseline is 1.9073486e-05    # Baseline 的值
>    The corresponding element in TRT result is 1.8119812e-05  # Paddle-TRT 的結果
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    矩陣乘因為算法的不同，是會有些微誤差的，但因某些 elements 最後結果太接近 0，才使得相對誤差被放大
> 2. 矩陣乘的 K 越大，會導致最後結果的 absolute error 放大，因為不同算法累加的方式不一樣
>    可以試試 `K_SIZE=156 python test.py` 便能通過測試

对于测试代码（1） 相对误差我这边测试结果是
fp32：结果里最小数值是1.7613997e-05 相对误差是0.08285967
fp16:  结果里最小数值0.0002799034  最大相对误差3可以到100
这个结果是符合预期的吗？
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/76512663/220019280-67e8bcec-1739-484e-afc1-dcae74bcdbfd.png">

**Comment by b3602sss** [comment]
对于测试二 , 使用K_SIZE后FP16绝对误差依然存在,需要修改 ：
‘’‘
        self.trt_param.precision = paddle_infer.PrecisionType.Half
        yield self.create_inference_config(), (1, 2), (1e-3, 1e-3) 
’‘’
结果：
<img width="1212" alt="image" src="https://user-images.githubusercontent.com/76512663/220021183-6ba9c989-1684-4b82-b2c4-9eb345b26cdc.png">

**Comment by b3602sss** [comment]
测试二关于matmul 绝对误差的测试 FP16下测试依然是不通过，改小k_size到39一样能复现问题：
测试FP16需要修改
‘’‘
        self.trt_param.precision = paddle_infer.PrecisionType.Half
        yield self.create_inference_config(), (1, 2), (1e-3, 1e-3)
’‘’
<img width="1217" alt="image" src="https://user-images.githubusercontent.com/76512663/220023131-3bf012e5-fb54-4867-b80a-8b09b2d7d797.png">

**Comment by leo0519** [comment]
> 对于测试代码（1） 相对误差我这边测试结果是
> fp32：结果里最小数值是1.7613997e-05 相对误差是0.08285967
> fp16: 结果里最小数值0.0002799034 最大相对误差3可以到100
> 这个结果是符合预期的吗？

矩陣乘算法不同，可能都會有 1e-5 級別的**絕對誤差**，而**相對誤差** = 絕對誤差 / 結果，結果太接近零，所以相對誤差才會被放大。

類似的情況可以透過修改輸入讓結果不可能靠近零來解決
(ex. the values of input are in [0.1, 1.0]; the values of the weight are in [0.1, 1.0])
