### ISSUE TITLE
安装pynrrd成功但是导入nrrd模块失败

### ISSUE THREAD

**Issue by pursuettt** [PaddlePaddle/Paddle#50548]
### 问题描述 Issue Description

在aistudio中安装pynrrd成功，但是导入import nrrd无法找到该模块
![安装](https://user-images.githubusercontent.com/68597123/219111341-3423af9a-61e5-4e12-ae44-c7acd1dd1c48.png)
![包管理](https://user-images.githubusercontent.com/68597123/219111374-a71b82fc-71c5-499f-abd3-d07aaeeba1d4.png)
![导入失败](https://user-images.githubusercontent.com/68597123/219111398-6adf2012-8e65-441d-9745-5def9f44a187.png)

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.1.2
Paddle With CUDA: False

OS: ubuntu 16.04
GCC version: (Ubuntu 7.5.0-3ubuntu1~16.04) 7.5.0
Clang version: N/A
CMake version: version 3.24.2
Libc version: glibc 2.10
Python version: 3.7.4

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by LiuChiachi** [comment]
看安装Pynrrd时有依赖不兼容的报错，会不会是没有成功安装的原因？
是否可以考虑将pyzmq回退到报错中建议的18.1.1？

**Comment by pursuettt** [comment]
谢谢，我重新导入了一次该包，问题就解决了。我猜可能是因为工作人员修复了该问题，感谢感谢！！！
