### ISSUE TITLE
TensorRT gather OP is_use_only  error

### ISSUE THREAD

**Issue by vivienfanghuagood** [PaddlePaddle/Paddle#50551]
## TensorRT bug
trt version：8.5.2.2

We meet some errors when build trt engine in these cases: 
#### wrong result:
![image](https://user-images.githubusercontent.com/89012307/219252901-c245a961-b615-4dd4-8c9e-cd0945674578.png)

![image](https://user-images.githubusercontent.com/89012307/219252914-64e2bb2e-7dd1-40fa-8c14-b2bf147f2dce.png)

In these cases, the result is right: 
#### right result:
![image](https://user-images.githubusercontent.com/89012307/219253132-6f39210a-50a2-4e81-9fd8-d99e95d72bc9.png)
![image](https://user-images.githubusercontent.com/89012307/219253148-b6dc38fe-22bf-483d-9bf7-c6b92030279e.png)

The error messages: 
### 错误日志
![image](https://user-images.githubusercontent.com/89012307/219253171-423f3cc8-19f0-4233-8bbe-3798a30f0f58.png)

Some information about these error messages: 
https://forums.developer.nvidia.com/t/tensorrt-conversion-fails-with-dcheck-i-is-use-only/237282

Can reproduce the results by download the model.zip and unzip it. 
[model.zip](https://github.com/PaddlePaddle/Paddle/files/10751560/model.zip).

**Comment by leo0519** [comment]
Hi @vivienfanghuagood.
This issue is solved in TRT8.6 EA. Could you please verify that? Thanks.
