### ISSUE TITLE
2.4.0之后的paddle版本不支持在mac本地跑，能不能支持一下

### ISSUE THREAD

**Issue by Godlikemandyy** [PaddlePaddle/Paddle#50550]
### 请提出你的问题 Please ask your question

Mac信息：
<img width="496" alt="图片" src="https://user-images.githubusercontent.com/36065226/219253601-dc5c3384-da86-417b-9986-ddc3f5fbc89f.png">
最新版paddle报错信息：
<img width="1364" alt="图片" src="https://user-images.githubusercontent.com/36065226/219253799-88550a86-d10b-480b-ad3a-2e0fb19d4d5c.png">
paddle==2.5.0

目前用paddle2.3.2的版本是能在本地跑的，希望新版本能支持一下本地运行！

**Comment by Godlikemandyy** [comment]
纠正一下paddle的版本写错了，看成paddlenlp的版本了，paddle paddle==2.4.1

**Comment by LiuChiachi** [comment]
经过确认paddle是支持m1的，你可以检查下安装。

**Comment by Godlikemandyy** [comment]
> 经过确认paddle是支持m1的，你可以检查下安装。

我这里新版本的paddle确实是跑不了的
<img width="617" alt="图片" src="https://user-images.githubusercontent.com/36065226/219537166-4cd02e9a-27af-4f2a-acf1-68a7a879664d.png">
我用的是miniconda创建的虚拟环境，2.3.2的版本是可以跑的，但是2.4.0之后的版本就会报硬件错误的

**Comment by LiuChiachi** [comment]
请问下你安装的包是哪个呢？这样安装也是不可以的吗？
![image](https://user-images.githubusercontent.com/26483581/219576361-a37c41a1-71ba-4f3b-bd47-4bbbad0a6475.png)

**Comment by Godlikemandyy** [comment]
> 请问下你安装的包是哪个呢？这样安装也是不可以的吗？ ![image](https://user-images.githubusercontent.com/26483581/219576361-a37c41a1-71ba-4f3b-bd47-4bbbad0a6475.png)

我是直接在conda创建的虚拟环境中pip install paddlepaddle安装的，刚试了一下你说的那种安装方式结果还是报和之前一样的错

**Comment by graphnj** [comment]
同样的问题，
之前是paddlepaddle2.3.2+paddlenlp2.4.0， 运行正常
paddlenlp升级到最新后，
`ModuleNotFoundError: No module named 'paddle.distributed.fleet.layers'
`
但升级paddlepaddle至2.4.x后，报如上SIGILL错误， 无法运行

**Comment by ajayghiyad** [comment]
If anyone is looking to run paddle on mac 
got it running using docker ubuntu image

https://github.com/PaddlePaddle/Paddle/issues/54531#issuecomment-1619601905
