### ISSUE TITLE
paddle.jit.to_static返回实例仍然是nn.Layer

### ISSUE THREAD

**Issue by intelyoungway** [PaddlePaddle/Paddle#50556]
[###] bug描述 Describe the Bug

1 历史上没有类似bug；
2 我在调用 paddle.jit.to_static时，返回的结果仍为nn.Layer类型；
  2.1 引入依赖库:
    
![Screenshot 2023-02-16 113038](https://user-images.githubusercontent.com/99377901/219261419-4bb54c77-f612-492f-8e11-3162a481f968.png)

  2.2 创建静态模块类型：

![image](https://user-images.githubusercontent.com/99377901/219261603-ac2f6c05-2296-4256-90e7-d7aa49db6056.png)

  2.3 随意引入一个网络层，继承nn.Layer即可:

![image](https://user-images.githubusercontent.com/99377901/219261768-f69b8c59-1b97-4929-acfd-68163a3b5a7f.png)

  2.4 创建新的类型，继承StaticModule:
  
![image](https://user-images.githubusercontent.com/99377901/219261931-b6a0b02f-d8b1-49a7-99fb-37db4af15b39.png)

  2.5 测试初始化过程，发现 以下问题：
![image](https://user-images.githubusercontent.com/99377901/219262053-42ee1c49-870e-40d1-90f9-8aebd17b632d.png)

![image](https://user-images.githubusercontent.com/99377901/219263261-2708ce10-967c-45f7-a2c8-3af19592241d.png)

3 总结问题
  不难发现，main_program之所以不存在，是因为to_static返回的net不是静态图，而是 EmbeddingsAndEvoformer，而后者继承了nn.Layer，所以实际上to_static返回的依然是动态图。
  所以我的问题是，to_static不能返回静态图的话，该如何设定，才能动转静？
  谢谢啦。

以下是paddle的版本信息：
![image](https://user-images.githubusercontent.com/99377901/219262860-cab61661-2a9b-4eaa-839a-58ffc9140f5f.png)

### 其他补充信息 Additional Supplementary Information
用于重现issue的单元检测脚本：
(https://github.com/PaddlePaddle/Paddle/files/10793960/ut_tostatic.zip)
解压缩后，执行 python ut_tostatic.py

**Comment by LiuChiachi** [comment]
似乎您没有贴出报错的代码？
不过从报错来看应该是使用存在问题。而且动转静也不需要用到main_program。
to_static的使用也十分简单，https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/jit/to_static_cn.html#to-static

**Comment by intelyoungway** [comment]
感谢，我研究一下，如果没问题，我就close. 谢谢！

**Comment by intelyoungway** [comment]
Hi 我看了一下你发的链接，这个是function的JIT，但是我需要的是nn.Layer模型的JIT，不一样。

**Comment by LiuChiachi** [comment]
你是怎么使用的呢？

**Comment by intelyoungway** [comment]
[ut_tostatic.zip](https://github.com/PaddlePaddle/Paddle/files/10793960/ut_tostatic.zip)
我整理了一份单元检测的脚本，可以重现issue. 
求帮忙检查一下StaticModule初始化函数中to_static调用是否合理。
麻烦你啦

**Comment by intelyoungway** [comment]
> 你是怎么使用的呢？

我主要是想调用 static_function.main_program.blocks 来查询并删除 op_stack 信息，这部分太大了，我构建的模型很大，导致报错“protostring too long”，需要删除无关信息以成功构建计算图。

**Comment by Aurelius84** [comment]
@intelyoungway 飞桨的@to_static是Lazy mode生效的，net = to_static(net)返回的是原生的net object，但已默认对net.forward进行标记，在调用 out = net(x) 时才会触发「根据x的shape信息构建完整的Program，并执行Program」

**Comment by Aurelius84** [comment]
@intelyoungway  program中的op_call_stack是为了在报错时向用户提供完整的报错栈，便于debug，这部分信息在大模型下确实会占用proto较多的字节，某些case也会超出64M的限制。

可以尝试在python 代码文件里加上 `sys.tracebacklimit = 0`，参考：https://www.oreilly.com/library/view/python-in-a/0596001886/re119.html

**Comment by intelyoungway** [comment]
> @intelyoungway program中的op_call_stack是为了在报错时向用户提供完整的报错栈，便于debug，这部分信息在大模型下确实会占用proto较多的字节，某些case也会超出64M的限制。
> 
> 可以尝试在python 代码文件里加上 `sys.tracebacklimit = 0`，参考：https://www.oreilly.com/library/view/python-in-a/0596001886/re119.html

Aurelius: 太感谢了，特别有效！

**Comment by intelyoungway** [comment]
这个问题已经解决，非常感谢Aurelius，感觉这个方法应该存入paddlepaddle的官方文档里，以便帮到更多遇到类似问题的其它同学！^_^
