### ISSUE TITLE
A100安装noavx版本，import paddle 出错

### ISSUE THREAD

**Issue by 2017040264** [PaddlePaddle/Paddle#50553]
### 问题描述 Issue Description

我按照官网的教程安装paddle,noavx版本，好像目前官网支持到cuda10.2；但是我用的机器是cuda11.7。然后就报错了，是cuda版本的问题吗，还是？

### 版本&环境信息 Version & Environment Information

Error: Can not import paddle core while this file exists: /home/xumingrui/.conda/envs/pp/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: centos 7
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.17
Python version: 3.8.16

CUDA version: 11.6.55
Build cuda_11.6.r11.6/compiler.30794723_0
cuDNN version: N/A
Nvidia driver version: 515.65.01
Nvidia driver List:
GPU 0: NVIDIA A100 80GB PCIe

****************************************

**Comment by 2017040264** [comment]
![1676517953407(1)](https://user-images.githubusercontent.com/57398559/219260620-cab39b90-af54-49ab-a424-404150c39b18.png)

pip list 显示是装了paddlepaddle-gpu的

**Comment by LiuChiachi** [comment]
确认下，你的机器是不支持avx吗

**Comment by 2017040264** [comment]
是的，不支持



---原始邮件---
发件人: "Jiaqi ***@***.***&gt;
发送时间: 2023年2月16日(周四) 中午11:36
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] A100安装noavx版本，import paddle 出错 (Issue #50553)




 
确认下，你的机器是不支持avx吗

**Comment by LiuChiachi** [comment]
可能确实是cuda版本不兼容的问题。官网里如果没有适合您的paddle版本，要不尝试一下自己编译呢？

**Comment by 2017040264** [comment]
自己编译是不是有点难度呀，暂时不弄了，等你们更新个11.7的吧



---原始邮件---
发件人: "Jiaqi ***@***.***&gt;
发送时间: 2023年2月16日(周四) 晚上7:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] A100安装noavx版本，import paddle 出错 (Issue #50553)




 
可能确实是cuda版本不兼容的问题。官网里如果没有适合您的paddle版本，要不尝试一下自己编译呢？

**Comment by LiuChiachi** [comment]
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by wujohns** [comment]
> 自己编译是不是有点难度呀，暂时不弄了，等你们更新个11.7的吧
> […](#)
> ---原始邮件--- 发件人: "Jiaqi ***@***.***&gt; 发送时间: 2023年2月16日(周四) 晚上7:21 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [PaddlePaddle/Paddle] A100安装noavx版本，import paddle 出错 (Issue #50553) 可能确实是cuda版本不兼容的问题。官网里如果没有适合您的paddle版本，要不尝试一下自己编译呢？ — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

同等，也是一样的问题，自编译指不定还会出其他妖蛾子，幸好项目不急，后续急了再考虑自编译

**Comment by LiuChiachi** [comment]
咨询了产品同学，noavx的版本不再维护了，所以还是建议自己编译的。编译可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html 编译。
我们日常开发经常自行编译，有问题欢迎交流。

**Comment by wujohns** [comment]
> 咨询了产品同学，noavx的版本不再维护了，所以还是建议自己编译的。编译可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html 编译。 我们日常开发经常自行编译，有问题欢迎交流。

老大那边已经同意换成基于pytorch开发了，暂时应该不会考虑用paddle

**Comment by wujohns** [comment]
build了几个小时，在96%的进度时出现Makefile:129: recipe for target 'all' failed，这种问题找谁都得磨死，要么等之后换机器，要么就干脆放弃了
