### ISSUE TITLE
张量模型并行如何 load checkpoint

### ISSUE THREAD

**Issue by Ehaschia** [PaddlePaddle/Paddle#50555]
我在尝试[张量模型并行](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/model_parallel_cn.html) 的时候，遇到了一个问题：

在并行的时候，我想使用 `paddle.load` load 之前在单卡上训练的模型。因为原模型并没有被切片，因此无法用于初始化切片模型，遇到如下错误：
![图片](https://user-images.githubusercontent.com/11350952/219260975-0feb5bca-cfe8-467c-b40a-a4f695a8a72b.png)
请问，如何实现这个 checkpoint 自动切片？

**Comment by wuhuachaocoding** [comment]
你好，目前没有直接提供自动切分的功能接口，你可以在代码里面手动根据rank号取出该卡的需要的初始化参数。

**Comment by wuhuachaocoding** [comment]
张量并行就是把参数切分到各卡上，你可以在paddle.load后，拿到对应的参数，通过rank号取出该卡需要的部分参数进行初始化即可。
