### ISSUE TITLE
零基础实践深度学习第四章目标检测yolov3下  get_objectness_label()函数的代码看起来有点问题

### ISSUE THREAD

**Issue by FengRongYue** [PaddlePaddle/Paddle#50567]
### 文档链接&描述 Document Links & Description

[https://www.paddlepaddle.org.cn/tutorials/projectdetail/2450225#anchor-23](url)

1. ![image](https://user-images.githubusercontent.com/95663126/219309846-a9b3d353-8878-46de-bc09-839101c0f18b.png)

图片上这个函数的参数不对啊，函数定义里没有这个参数，注释里却写了这个参数。

2.
![image](https://user-images.githubusercontent.com/95663126/219310828-25872374-a886-4c84-9baa-14f241803a91.png)
 

### 请提出你的建议 Please give your suggestion

我是在学习源码。
第一点我没看懂。
第二点的真实框的代码应该是` bbox1 = [float(gt_center_x), float(gt_center_y), float(gt_width), float(gt_height)]`

**Comment by wangxinxin08** [comment]
文档中并无错误，yolov3的原始匹配方式就是使用center和(w, h)分两步确定，center首先确定是feature map的哪一个位置，(w, h)用于比较和gt的(w, h)的形状相似性来确定是哪一个anchor

**Comment by FengRongYue** [comment]
> 文档中并无错误，yolov3的原始匹配方式就是使用center和(w, h)分两步确定，center首先确定是feature map的哪一个位置，(w, h)用于比较和gt的(w, h)的形状相似性来确定是哪一个anchor
好像明白了，就是锚框的匹配虽然是通过IOU高低确定的，但是不用太严格的遵循原始的IOU计算方法，用你提到的形状相似性就好了。但是感觉很奇怪，下面计算IOU的代码明显是考虑中心点不重合的情况的呀，虽然不影响结果但是感觉很奇怪。

**Comment by wangxinxin08** [comment]
中心点影响iou，把中心点设置为0，表示只考虑(w, h)的形状相似性，两个相同的框，只要其足够远，则其iou为0，但其形状依然相似，yolov3在匹配anchor的时候就只用了(w, h)
