### ISSUE TITLE
编译运行WITH_OPENCV的serving出现protobuf版本不匹配的问题

### ISSUE THREAD

**Issue by lhmwzy** [PaddlePaddle/Paddle#50575]
### 问题描述 Issue Description

参照https://github.com/PaddlePaddle/Serving/blob/v0.9.0/doc/Compile_CN.md编译开启WITH_OPENCV选项编译C++ Server，编译成功后，运行serving出现protobuf版本不匹配的问题
```
core/general-server/serving 
[libprotobuf FATAL /home/Serving/build_server_opencv4/third_party/protobuf/src/extern_protobuf/src/google/protobuf/stubs/common.cc:78] This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.1.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  This program was compiled against version 2.6.1 of the Protocol Buffer runtime library, which is not compatible with the installed version (3.1.0).  Contact the program author for an update.  If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.  (Version verification failed in "/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc".)
Aborted
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 16.04
GCC version: (GCC) 8.2.0
Clang version: N/A
CMake version: version 3.16.0
Libc version: glibc 2.23
Python version: 3.9.0

CUDA version: 9.0.176
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: 

****************************************

**Comment by LiuChiachi** [comment]
那按照报错信息重新安装protobuf到一个兼容的版本呢？

**Comment by lhmwzy** [comment]
> 那按照报错信息重新安装protobuf到一个兼容的版本呢？

docker系统里默认安装的就是2.6.1，这个3.1.0的版本是编译过程中自动下载的。
系统里的/build/mir-O8_xaj/mir-0.26.3+16.04.20170605/obj-x86_64-linux-gnu/src/protobuf/mir_protobuf.pb.cc这个是2.6.1版本的，有办法换成3.1.0的吗？

**Comment by LiuChiachi** [comment]
重新pip安装protobuf指定（3.1.0）版本呢

**Comment by lhmwzy** [comment]
> 重新pip安装protobuf指定（3.1.0）版本呢

这个与python下的protobuf模块没关系吧？编码的是C++文件，用的都是C++的protobuf库

**Comment by LiuChiachi** [comment]
好的
不过看这个报错信息
If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library.
可以保证吗

**Comment by lhmwzy** [comment]
> 好的 不过看这个报错信息 If you compiled the program yourself, make sure that your headers are from the same version of Protocol Buffers as your link-time library. 可以保证吗

恕我水平太低，不知道如何去保证 
编译serve的时候，如何使用特定版本的protobuf呢？

**Comment by lhmwzy** [comment]
这个是由于opencv的编译参数引起的，需要在编码时指定   
     ```
-DWITH_PROTOBUF=OFF  \
    -DBUILD_PROTOBUF=OFF  \
    -DWITH_GTK=OFF
```
变为：
```
cmake .. \
    -DCMAKE_INSTALL_PREFIX= /home/serve/opencv4 \
    -DCMAKE_BUILD_TYPE=Release \
    -DBUILD_SHARED_LIBS=OFF \
    -DWITH_IPP=OFF \
    -DBUILD_IPP_IW=OFF \
    -DWITH_LAPACK=OFF \
    -DWITH_EIGEN=OFF \
    -DCMAKE_INSTALL_LIBDIR=lib64 \
    -DWITH_ZLIB=ON \
    -DBUILD_ZLIB=ON \
    -DWITH_JPEG=ON \
    -DBUILD_JPEG=ON \
    -DWITH_PNG=ON \
    -DBUILD_PNG=ON \
    -DWITH_TIFF=ON \
    -DBUILD_TIFF=ON \
    -DWITH_PROTOBUF=OFF  \
    -DBUILD_PROTOBUF=OFF  \
    -DWITH_GTK=OFF
```
要不然，会自动把系统自动的protobuf的版本编译进去，造成protobuf版本不一致的错误。
