### ISSUE TITLE
Paddle框架Auto Differentiation无法处理计算图中有log或log10函数的情况

### ISSUE THREAD

**Issue by ManwouldconquerDC** [PaddlePaddle/Paddle#50571]
### bug描述 Describe the Bug

用户：Gallardo66
项目：test
test for log
运行其中run_train.ipynb
当存在log或log10函数在计算图中时，Auto Differentiation计算会导致内核kernel会崩溃
pytorch中测试log及log10函数可以正常参与Auto Differentiation计算

**Comment by LiuChiachi** [comment]
用户：Gallardo66
项目：test
test for log
这个可以辛苦帮忙发出链接吗

**Comment by LiuChiachi** [comment]
或者是否可以详细讲下Auto Differentiation的过程/代码？
