### ISSUE TITLE
phytium d2000 + nvidia GTX1060 + kylin v10源码编译安装后，生成whl文件，安装后测试问题

### ISSUE THREAD

**Issue by xman1991** [PaddlePaddle/Paddle#50591]
### 问题描述 Issue Description

问题描述 Issue Description
软件环境: kylinv10 、cuda11.2、cudnn8.1;
硬件环境: cpu:phytium GPU:nvidia GTX1060;
安装步骤：
1、git clone https://github.com/PaddlePaddle/Paddle.git
2、cd paddlepaddle
3、cd python && pip install -r requirement.txt
4、mkdir build && cd build
5、ulimit -n 4096
6、cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON - DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_CUDNN_DSO=ON
7、出现：/home/kylin/2230/Paddle/build/paddle/fluid/eager/auto_code_generator/eager_generator: error while loading shared libraries: libcudart.so.11.0: cannot open shared object file: No such file or directory，问题；
解决方案：
sudo cp /usr/local/cuda-10.0/lib64/libcudnn.so.7 /usr/local/lib/libcudnn.so.7 && sudo ldconfig
[https://blog.csdn.net/martinkeith/article/details/102997059]
8、cd python/dist
9、pip install paddlepaddle_gpu-0.0.0-cp37-cp37m-linux_aarch64.whl
测试方案:
进入python:
import paddle
paddle.utils.run_check()

报错:
Running verify PaddlePaddle program ...
I0215 15:09:51.850409 3916 interpretercore.cc:279] New Executor is Running.
W0215 15:09:51.850878 3916 gpu_resources.cc:85] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2

C++ Traceback (most recent call last):
0 paddle::framework::StandaloneExecutor::Run(paddle::framework::Scope*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&)
1 paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&, bool)
2 paddle::framework::interpreter::BuildOpFuncList(phi::Place const&, paddle::framework::BlockDesc const&, std::set<std::string, std::less<std::string >, std::allocator<std::string > > const&, std::vector<paddle::framework::OpFuncNode, std::allocatorpaddle::framework::OpFuncNode >, paddle::framework::VariableScope, paddle::framework::interpreter::ExecutionConfig const&, bool)
3 paddle::platform::DeviceContextPool::Get(phi::Place const&)
4 std::__future_base::_Deferred_state<std:thread:_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > ()(phi::Place const&, bool, int), phi::Place, bool, int> >, std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > >::_M_complete_async()
5 std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>, bool*)
6 std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > >, std::__future_base::_Result_base::_Deleter>, std:thread:_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > ()(phi::Place const&, bool, int), phi::Place, bool, int> >, std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > > >::_M_invoke(std::_Any_data const&)
7 std::unique_ptr<phi::DeviceContext, std::default_deletephi::DeviceContext > paddle::platform::CreateDeviceContextphi::GPUContext(phi::Place const&, bool, int)
8 std::enable_if<std::is_same<phi::GPUContext, phi::GPUContext>::value, phi::GPUContext>::type paddle::platform::ConstructDevCtxphi::GPUContext(phi::Place const&, int)
9 phi::GPUContext::GPUContext(phi::GPUPlace const&, bool, int)
10 phi::InitGpuProperties(phi::Place, int*, int*, int*, int*, int*, int*, std::array<int, 3ul>*)
11 cudnnGetVersion

Error Message Summary:
FatalError: Access to an undefined portion of a memory object is detected by the operating system.
[TimeInfo: *** Aborted at 1676444991 (unix time) try "date -d @1676444991" if you are using GNU date ***]
[SignalInfo: *** SIGBUS (@0x7f57890858) received by PID 3916 (TID 0x7fb7515750) from PID 1468598360 ***]

总线错误

### 版本&环境信息 Version & Environment Information

Paddle version: 0.0.0
Paddle With CUDA: True

OS: kylin v10
GCC version: (Ubuntu 9.3.0-10kylin2) 9.3.0
Clang version: 10.0.0-4kylin1
CMake version: version 3.26.0-rc2
Libc version: glibc 2.17
Python version: 3.7.12

CUDA version: 11.0.194
Build cuda_11.0_bu.TC445_37.28540450_0
cuDNN version: N/A
Nvidia driver version: 460.84
Nvidia driver List:
GPU 0: GeForce GTX 1060 6GB

**Comment by xman1991** [comment]
项目紧急，希望能尽快得到回复。

**Comment by cuicheng01** [comment]
您好，请检查一下是否正确安装cudnn

**Comment by xman1991** [comment]
![GITHUB_01](https://user-images.githubusercontent.com/63028986/219573682-c2bbf8b3-0549-4eb0-b287-c3d1af6a45a4.png)

**Comment by xman1991** [comment]
修改你们脚本后，可以看到cudnn的版本
![2023-02-17_11-12-12](https://user-images.githubusercontent.com/63028986/219573716-8fa9799f-d77c-4562-a6d3-95c93a0c4d08.png)

**Comment by xman1991** [comment]
修改你们的脚本，可以看到cudnn的版本
![GITHUB_02](https://user-images.githubusercontent.com/63028986/219573877-9f2f056c-c6de-41d3-b677-9b87ccab4efe.png)

**Comment by xman1991** [comment]
这是我修改的部分
![GITHUB_03](https://user-images.githubusercontent.com/63028986/219574145-665f8a42-79e1-4f69-ae9b-db4ee6f80d4e.png)

**Comment by xman1991** [comment]
> 您好，请检查一下是否正确安装cudnn

方便加下微信么？这样沟通有点慢哈。

**Comment by cuicheng01** [comment]
这块我也不是很懂，我会尽快联系负责编译、安装的同学和你联系～

**Comment by xman1991** [comment]
> 这块我也不是很懂，我会尽快联系负责编译、安装的同学和你联系～

等了两天了哈，希望能尽快得到解决哈。

**Comment by cuicheng01** [comment]
目前提供的whl包没有涵盖你的环境是吗？

**Comment by xman1991** [comment]
> 目前提供的whl包没有涵盖你的环境是吗？
没有，因为我是aarch64的飞腾d2000的cpu,装jetpack不支持

**Comment by xman1991** [comment]
> 目前提供的whl包没有涵盖你的环境是吗？

你好？

**Comment by rap8** [comment]
我uos系统，也是aarch64框架编译，编译时下载很多依赖包开了个vpn就好了

**Comment by xman1991** [comment]
> 我uos系统，也是aarch64框架编译，编译时下载很多依赖包开了个vpn就好了
编译没问题，是安装后,paddle.utils.run_check()报错哈

**Comment by xman1991** [comment]
> 我uos系统，也是aarch64框架编译，编译时下载很多依赖包开了个vpn就好了

我的显卡是nvidia gtx1060，你是什么卡呢？

**Comment by cuicheng01** [comment]
您好，问下这个问题解决了吗？

**Comment by rap8** [comment]
> > 我uos系统，也是aarch64框架编译，编译时下载很多依赖包开了个vpn就好了
> > 编译没问题，是安装后,paddle.utils.run_check()报错哈

确定编译没问题吗，我最开始没开vpn编译也能成功，但是最终下载包是无法使用的。开了vpn后编译的whl包安装才能正常使用

**Comment by qili93** [comment]
hi, @xman1991 

这个应该是这一步导致的cudnn版本和CUDA版本不匹配导致的问题，您的环境里面安装的CUDA版本是11.0，但是这一步是拷贝了一个CUDA10.0对应的cudnn的库过去，您这里需要安装一个CUDA 11.0对应的cudnn版本

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/15017f0f-ba6c-4d40-bd8f-f0e509213da0)
 
最终报错也是在cudnnGetVersion上，不是飞桨的错误，您需要修复您环境中CUDA和cuDNN版本不匹配的问题 

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/c2a56e0d-08d5-42fc-a7dc-522831255129)
