### ISSUE TITLE
paddle.static.nn.prelu示例代码都跑不通，麻烦修一下

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#50598]
### bug描述 Describe the Bug

paddle.static.nn.prelu示例代码都跑不通，麻烦修一下

**Comment by cuicheng01** [comment]
您好，请问使用的是paddle版本是多少呢？

**Comment by zhwesky2010** [comment]
@cuicheng01  https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/nn/prelu_cn.html develop版本
就跑不通，任意版本都跑不通吧，你这里有能跑通的版本么
<img width="928" alt="infoflow 2023-02-17 20-34-01" src="https://user-images.githubusercontent.com/52485244/219654766-133ed5a1-fe8a-4009-9c1c-1d8bd02d975e.png">

**Comment by zhwesky2010** [comment]
我找到问题了，是没有跑default_startup_program，先 `exe.run(paddle.static.default_startup_program())` 就可以
