### ISSUE TITLE
使用hub 安装 baidu_translate,发送预测请求后报Invalid Sign

### ISSUE THREAD

**Issue by LiuHaodongdong** [PaddlePaddle/Paddle#50613]
### bug描述 Describe the Bug

#安装baidu_translate
hub install baidu_translate==1.0.0
#启动服务
hub serving start -m baidu_translate

#请发送预测请求
import requests
import json

text = "I like panda"
data = {"query": text, "from_lang":'en', "to_lang":'zh'}
# 发送post请求，content-type类型应指定json方式，url中的ip地址需改为对应机器的ip
url = "http://127.0.0.1:8866/predict/baidu_translate"
# 指定post请求的headers为application/json方式
headers = {"Content-Type": "application/json"}

r = requests.post(url=url, headers=headers, data=json.dumps(data))
print(r.json())

#期待得到翻译结果
#实际得到的是
{'msg': 'Invalid Sign', 'results': '', 'status': '101'}

**Comment by rainyfly** [comment]
你好，该模块会直接访问百度翻译平台，目前该模块正在维护中，之后可能需要用户自己申请token进行使用
