### ISSUE TITLE
index 139809198587392 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by impactcolor** [PaddlePaddle/Paddle#50628]
### 请提出你的问题 Please ask your question

`    sin_theta = paddle.sin(math.pi * theta)
    cos_theta = paddle.cos(math.pi * theta)
    index = paddle.full((b,), -1, dtype='int64').numpy()

    index[(h > w).numpy()] = 0
    index[(h <= w).numpy()] = 1
    meta_brushes_resize = F.interpolate(meta_brushes, (H, W)).numpy()
    brush = paddle.to_tensor(meta_brushes_resize[index])`

H is 1280 and so is W

brush = paddle.to_tensor(meta_brushes_resize[index])
IndexError: index 139809198587392 is out of bounds for axis 0 with size 2

any idea how I can resolve this?

**Comment by wangna11BD** [comment]
使用paddle.index_select(x, index, axis=0)试试呢

**Comment by impactcolor** [comment]
@wangna11BD thank you for your response, where should I insert this?
`paddle.index_select(x, index, axis=0)`

**Comment by wangna11BD** [comment]
index = paddle.full((b,), -1, dtype='int64')
index = paddle.where(h > w, paddle.zeros_like(index), paddle.ones_like(index)) # h, w is tensor,  which shape is same as index
meta_brushes_resize = F.interpolate(meta_brushes, (H, W))
brush = paddle.index_select(meta_brushes_resize, index, axis=0)

**Comment by impactcolor** [comment]
@wangna11BD THANK YOU!
