### ISSUE TITLE
搭建网络的时候，paddle.nn.Conv2D不能调用自身的属性stride

### ISSUE THREAD

**Issue by yizhiyangou** [PaddlePaddle/Paddle#50623]
### bug描述 Describe the Bug

 184         self.conv1 = nn.Conv2D(1, 64, kernel_size=7, stride=[2, 2], padding=3, bias_attr=False)
    185         # self.conv1 = nn.Conv2D(3, 64, kernel_size=3, stride=1, padding=1, bias=False)
--> 186         if self.conv1.stride[0] == 2:
    187             self.resolution[0] /= 2
    188         if self.conv1.stride[1] == 2:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py in __getattr__(self, name)
   1121                     return _convert_into_variable(_buffers[name])
   1122                 return _buffers[name]
-> 1123         return object.__getattribute__(self, name)
   1124 
   1125     def __setattr__(self, name, value):
AttributeError: 'Conv2D' object has no attribute 'stride'

**Comment by cuicheng01** [comment]
您好，请使用`self.conv._stride`
