### ISSUE TITLE
TypeError: Only support float and double tensor for bool index, but received paddle.int64.

### ISSUE THREAD

**Issue by Wenze7** [PaddlePaddle/Paddle#50636]
### 请提出你的问题 Please ask your question

我想对ids里面为0（padding）的位置替换为-100（为了使用CEloss），我是这样实现的：
<img width="363" alt="image" src="https://user-images.githubusercontent.com/55132749/219851275-1713e182-e043-442a-8e7f-93e547248ac0.png">
但是却报了下面的错误：
<img width="1077" alt="image" src="https://user-images.githubusercontent.com/55132749/219851305-cc16e338-e146-4f79-ba60-e944a4012caa.png">
我输出了y，是一个float32，我该怎么改呢

**Comment by wangna11BD** [comment]
看报错是因为input_ids是int64，y是float32，需要修改input_ids为float32或float64
