### ISSUE TITLE
How to set output type of `DataLoader` to `np.ndarray` rather than `tensor`?

### ISSUE THREAD

**Issue by OrangeSodahub** [PaddlePaddle/Paddle#50647]
I want to use `DataLoader` to feed data into PaddleOCR but ocr does not support `tensor` intput type..

**Comment by LemonNoel** [comment]
DataLoader返回值默认为Tensor，可将 places 设为 paddle.static.cpu_places()，在返回后 data.numpy() 转换为 np.array 格式。

**Comment by OrangeSodahub** [comment]
转为numpy格式后dataloader只返回第一个batch就停止了，不转就能正常输出。请问怎么解决呢？

**Comment by LemonNoel** [comment]
转换的代码是怎样的，第一个batch停止有什么输出信息吗？

**Comment by OrangeSodahub** [comment]
```
for idx, (imgs, lbls) in enumerate(dataloader):
    # (bs, 3, h, w)
    imgs=[img.numpy() for img in imgs]
```
没有输出，打印了第一个idx就退出了

**Comment by OrangeSodahub** [comment]
问题解决了，OCR输入的维度没有转对，感谢~

**Comment by gzzyyxh** [comment]
> 问题解决了，OCR输入的维度没有转对，感谢~

How does Dr. Yang feel about his two stupid issues?
