### ISSUE TITLE
paddle什么时候会支持intel的gpu

### ISSUE THREAD

**Issue by Dark1Forest** [PaddlePaddle/Paddle#50643]
### 需求描述 Feature Description

paddle会考虑支持intel的gpu吗？如果会，预计什么时候会发布呢？

**Comment by cxxly** [comment]
您好，收到您的请求，我转给PM评估下，后续给您答复

**Comment by Dark1Forest** [comment]
> 您好，收到您的请求，我转给PM评价下，之后继续给您答复

有反馈了吗？后续考虑支持吗？
