### ISSUE TITLE
paddle.distribution中Bernoulli分布如何实现？

### ISSUE THREAD

**Issue by XSY3000** [PaddlePaddle/Paddle#50649]
### 请提出你的问题 Please ask your question

我需要使用pytorch中torch.distribution.bernoulli()，但paddle.distribution中似乎没有这个类。
我尝试使用Multinomial(total_count=1,probs=prob)代替。
但参数和输入都相同的情况下，paddle的log_prob()输出和pytorch中的输出结果不同。
请问一下我该如何实现？

下面是我的测试：
```
import torch
from torch.distribution import Bernoulli
import paddle
from paddle.distribution import Multinomial
import numpy as np

prob = np.array([[[0.3, 0.7], [0.1, 0.6]], [[0.1, 0.9], [0.7, 0.2]]])
torch_bd = Bernoulli(torch.tensor(prob))
paddle_bd = Multinomial(1,paddle.to_tensor(prob))

torch_sample = torch_bd.sample()
sample = torch_sample.numpy()
paddle_sample = paddle.to_tensor(sample)
torch_sample
Out:
tensor([[[0., 1.],
         [0., 1.]],
        [[0., 1.],
         [0., 0.]]], dtype=torch.float64)

torch_log_prob = torch_bd.log_prob(torch_sample)
paddle_log_prob = paddle_bd.log_prob(paddle_sample)

torch_log_prob.size()
Out: torch.Size([2, 2, 2])
torch_log_prob
Out:
tensor([[[-0.3567, -0.3567],
         [-0.1054, -0.5108]],
        [[-0.1054, -0.1054],
         [-1.2040, -0.2231]]], dtype=torch.float64)
paddle_log_prob
Out:
Tensor(shape=[2, 2], dtype=float64, place=Place(gpu:0), stop_gradient=True,
       [[-0.35667494, -0.15415068],
        [-0.10536052,  0.        ]])
```

**Comment by LemonNoel** [comment]
[paddle.bernoulli](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/bernoulli_cn.html#bernoulli) 与 [torch.bernoulli](https://pytorch.org/docs/stable/generated/torch.bernoulli.html?highlight=bernoulli#torch.bernoulli) 对应，参数区别见[文档](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/ops/torch.bernoulli.md)。

**Comment by XSY3000** [comment]
> [paddle.bernoulli](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/bernoulli_cn.html#bernoulli) 与 [torch.bernoulli](https://pytorch.org/docs/stable/generated/torch.bernoulli.html?highlight=bernoulli#torch.bernoulli) 对应，参数区别见[文档](https://github.com/PaddlePaddle/X2Paddle/blob/develop/docs/pytorch_project_convertor/API_docs/ops/torch.bernoulli.md)。

你好，我想问的是[torch.distribution.Bernoulli()](https://pytorch.org/docs/stable/distributions.html#torch.distributions.bernoulli.Bernoulli)，并不是torch.bernoulli。
paddle.bernoulli没有sample(),log_prob()方法

**Comment by cxxly** [comment]
目前Paddle没有Bernoulli分布，如果感兴趣可以参考已有分布的代码，自己实现一个，并提交给Paddle；如果没兴趣的话，那辛苦@LemonNoel  把该功能需求提交给PM。

**Comment by cxxly** [comment]
至于你代码中的问题，多项分布中probs需要传入落到每个分类的概率(比如即使是二项分布，也要传入(0.3, 0.7), 0.3表示为0的概率，0.7表示为1的概率)，Bernoulli分布中只需要传入为1的概率(0.7)

```python
In [20]: import paddle
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script

In [21]: import torch

In [22]: b = torch.distributions.Bernoulli(probs=torch.tensor([0.7]))

In [23]: b.log_prob(torch.tensor([1.]))
Out[23]: tensor([-0.3567])

In [24]: m = paddle.distribution.Multinomial(total_count=1, probs=paddle.to_tensor([0.3, 0.7]))
W0220 05:46:46.337211 36765 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.8, Runtime API Version: 11.2
W0220 05:46:46.340873 36765 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.

In [25]: m.log_prob(paddle.to_tensor([0., 1.]))
Out[25]: 
Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [-0.35667497])

In [26]: 
```

**Comment by XSY3000** [comment]
> 目前Paddle没有Bernoulli分布，如果感兴趣可以参考已有分布的代码，自己实现一个，并提交给Paddle；如果没兴趣的话，那辛苦@LemonNoel 把该功能需求提交给PM。

谢谢，我尝试写了一下，提交了pr。不过对自己的代码不太自信😂

**Comment by luotao1** [comment]
> 谢谢，我尝试写了一下，提交了pr

请问是哪个 PR 呀？

**Comment by XSY3000** [comment]
> > 谢谢，我尝试写了一下，提交了pr
> 
> 请问是哪个 PR 呀？

啊我不太会用github，[bernoulli.py](https://github.com/XSY3000/Paddle/blob/XSY3000-patch-1/python/paddle/distribution/bernoulli.py) 这里应该能看到我提交的

**Comment by luotao1** [comment]
为飞桨框架新增一系列 API，提交流程请参考 [新增API 开发&提交流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/api_contributing_guides_cn.html)，开发请参考 [贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/index_cn.html)

**Comment by luotao1** [comment]
close due to the following PR is merged:
- #52244
