### ISSUE TITLE
paddle CPU多核训练和多GPU训练和单核训练，但CPU训练速度差不多，是因为什么

### ISSUE THREAD

**Issue by zzh-sonny** [PaddlePaddle/Paddle#50641]
### 请提出你的问题 Please ask your question

我在用paddle的parl进行强化学习的训练时候。服务器配置已经安装nvcl。在用多GPU卡和多CPU训练的时候遇到一些问题。
硬件是，2个cpu 36核，2个GPU。
用的指令是基于launch 启动方式，方式
cpu：python -m paddle.distributed.launch --backend=gloo --nproc_per_node=12 train.py
gpu:  python -m paddle.distributed.launch train.py
问题：
1.用上边的命令，比较了一下和我正常用 python train.py训练速度是一样的。这个是因为有自动调节的作用。还是需要一些额外的设置？
2.用单机多卡训练的时候GPU的利用率，我用单机是一张卡百分8，两个一起用可能每个卡反而百分10，这个是什么原因阿
3.单机多卡启动方式 spawn的多CPU启动应该怎么设置那。用多GPU训练的时候，如果用了argparse.ArgumentParser()，也会报错。这个该怎么解决那
代码类似下边
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    ..(省略)
    dist.spawn(train)

**Comment by cxxly** [comment]
您好，需要您去强化学习repo咨询下，这里主要处理Paddle框架相关问题
