### ISSUE TITLE
vs2019 编译失败

### ISSUE THREAD

**Issue by Synmul** [PaddlePaddle/Paddle#50646]
### 请提出你的问题 Please ask your question

本来下载了官方编译的推理库  但是cpu和gpu 、c++和c库都是运行出现0xC000007B  
然后尝试编译源码也没成功
![1](https://user-images.githubusercontent.com/50161120/219955723-640a8308-99d1-4a7a-9ad7-bed8e4d9ce67.png)

D:\paddle_vs2019\Paddle\build\paddle\fluid\pybind>exit /b 0
[2835/3035] Linking CXX executable paddle\fluid\eager\auto_code_generator\eager_generator.exe
  正在创建库 paddle\fluid\eager\auto_code_generator\eager_generator.lib 和对象 paddle\fluid\eager\auto_code_generator\eager_generator.exp
[2846/3035] Building CXX object paddle\fluid\eager\api\generated\fluid_...wards\CMakeFiles\dygraph_function.dir\dygraph_forward_functions1.cc.ob
FAILED: paddle/fluid/eager/api/generated/fluid_generated/forwards/CMakeFiles/dygraph_function.dir/dygraph_forward_functions1.cc.obj
C:\PROGRA~2\MICROS~2\2019\COMMUN~1\VC\Tools\MSVC\1429~1.301\bin\Hostx64\x64\cl.exe  /nologo /TP -DCUDA_TOOLKIT_ROOT_DIR="\"C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.2\"" -DCUDA_VERSION_MAJOR=\"11\" -DCUDA_VERSION_MINOR=\"2\" -DCUDNN_MAJOR_VERSION=\"8\" -DEIGEN_STRONG_INLINE=inline -DEIGEN_USE_GPU -DGOOGLE_GLOG_DLL_DECL="" -DLAPACK_FOUND -DNOMINMAX -DPADDLE_DISABLE_PROFILER -DPADDLE_DLL_EXPORT -DPADDLE_DLL_INFERENCE -DPADDLE_ON_INFERENCE -DPADDLE_VERSION=0.0.0 -DPADDLE_VERSION_INTEGER=0 -DPADDLE_WITH_AVX -DPADDLE_WITH_CRYPTO -DPADDLE_WITH_CUDA -DPADDLE_WITH_MKLDNN -DPADDLE_WITH_MKLML -DPADDLE_WITH_POCKETFFT -DPADDLE_WITH_SSE3 -DTRT_PLUGIN_FP16_AVALIABLE -DUTF8PROC_STATIC -DWIN32_LEAN_AND_MEAN -D_XKEYCHECK_H -I. -I..\paddle\fluid\framework\io -Ithird_party\install\zlib\include -Ithird_party\install -Ithird_party\install\gflags\include -Ithird_party\install\glog\include -Ithird_party\eigen3\src\extern_eigen3 -Ithird_party\threadpool\src\extern_threadpool -Ithird_party\dlpack\src\extern_dlpack\include -Ithird_party\install\xxhash\include -Ithird_party\install\warpctc\include -Ithird_party\install\utf8proc\include -Ithird_party\install\mklml\include -Ithird_party\install\mkldnn\include -Ithird_party\install\protobuf\include -I"C:\Program Files\Python36\include" -I"C:\Program Files\Python36\Lib\site-packages\numpy\core\include" -Ithird_party\pybind\src\extern_pybind\include -Ithird_party\install\cryptopp\include -Ithird_party\pocketfft\src -Ithird_party\dirent\src\extern_dirent\include -I"C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include" -I..\ -I..\paddle\fluid\framework\io /DWIN32 /D_WINDOWS  /W0  /GR /EHsc /w /wd4068 /wd4129 /wd4244 /wd4267 /wd4297 /wd4530 /wd4577 /wd4819 /wd4838  /arch:AVX /MT /O2 /Ob2 /DNDEBUG /bigobj /Zc:inline   -std:c++14 /showIncludes /Fopaddle\fluid\eager\api\generated\fluid_generated\forwards\CMakeFiles\dygraph_function.dir\dygraph_forward_functions1.cc.obj /Fdpaddle\fluid\eager\api\generated\fluid_generated\forwards\CMakeFiles\dygraph_function.dir\dygraph_function.pdb /FS -c ..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(147): error C2065: “complexGradNodeCompat”: 未声明的标识符
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(147): error C2923: “std::shared_ptr”: 对于参数“_Ty”，“complexGradNodeCompat”不是有效的 模板 类型变量
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(147): note: 参见“complexGradNodeCompat”的声明
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(147): error C2955: “std::shared_ptr”: 使用 类 模板 需要 模板 参数列表
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(1490): note: 参见“std::shared_ptr”的声明..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(147): error C2061: 语法错误: 标识符“complexGradNodeCompat”
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(150): error C3536: “grad_node”: 初始化之前无法使用
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(160): error C2665: “egr::EagerUtils::SetHistory”: 2 个重载中没有一个可以转换所有参数类型
..\paddle/fluid/eager/utils.h(115): note: 可能是“void egr::EagerUtils::SetHistory(egr::AutogradMeta *,const std::shared_ptr<egr::GradNodeBase> &)”
..\paddle/fluid/eager/utils.h(113): note: 或    “void egr::EagerUtils::SetHistory(std::vector<ElementType,std::allocator<ElementType>> *,const std::shared_ptr<egr::GradNodeBase> &)”
        with
        [
            ElementType=egr::AutogradMeta *
        ]
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(160): note: 尝试匹配参数列表“(egr::AutogradMeta *, int)”时
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(224): error C2065: “triangular_solveGradNodeCompat”: 未声明的标识符
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(224): error C2923: “std::shared_ptr”: 对于参数“_Ty”，“triangular_solveGradNodeCompat”不是有效的 模板 类型变量
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(224): note: 参见“triangular_solveGradNodeCompat”的声明
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(224): error C2955: “std::shared_ptr”: 使用 类 模板 需要 模板 参数列表
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(1490): note: 参见“std::shared_ptr”的声明..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(224): error C2061: 语法错误: 标识符“triangular_solveGradNodeCompat”
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(227): error C3536: “grad_node”: 初始化之前无法使用
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(238): error C2665: “egr::EagerUtils::SetHistory”: 2 个重载中没有一个可以转换所有参数类型
..\paddle/fluid/eager/utils.h(115): note: 可能是“void egr::EagerUtils::SetHistory(egr::AutogradMeta *,const std::shared_ptr<egr::GradNodeBase> &)”
..\paddle/fluid/eager/utils.h(113): note: 或    “void egr::EagerUtils::SetHistory(std::vector<ElementType,std::allocator<ElementType>> *,const std::shared_ptr<egr::GradNodeBase> &)”
        with
        [
            ElementType=egr::AutogradMeta *
        ]
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(238): note: 尝试匹配参数列表“(egr::AutogradMeta *, int)”时
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(300): error C2065: “reduce_maxGradNodeCompat”: 未声明的标识符
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(300): error C2923: “std::shared_ptr”: 对于参数“_Ty”，“reduce_maxGradNodeCompat”不是有效的 模板 类型变量
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(300): note: 参见“reduce_maxGradNodeCompat”的声明
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(300): error C2955: “std::shared_ptr”: 使用 类 模板 需要 模板 参数列表
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(1490): note: 参见“std::shared_ptr”的声明..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(300): error C2061: 语法错误: 标识符“reduce_maxGradNodeCompat”
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(303): error C3536: “grad_node”: 初始化之前无法使用
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(312): error C2665: “egr::EagerUtils::SetHistory”: 2 个重载中没有一个可以转换所有参数类型
..\paddle/fluid/eager/utils.h(115): note: 可能是“void egr::EagerUtils::SetHistory(egr::AutogradMeta *,const std::shared_ptr<egr::GradNodeBase> &)”
..\paddle/fluid/eager/utils.h(113): note: 或    “void egr::EagerUtils::SetHistory(std::vector<ElementType,std::allocator<ElementType>> *,const std::shared_ptr<egr::GradNodeBase> &)”
        with
        [
            ElementType=egr::AutogradMeta *
        ]
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(312): note: 尝试匹配参数列表“(egr::AutogradMeta *, int)”时
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(374): error C2065: “padGradNodeCompat”: 未声明的标识符
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(374): error C2923: “std::shared_ptr”: 对于参数“_Ty”，“padGradNodeCompat”不是有效的 模板 类型变量
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(374): note: 参见“padGradNodeCompat”的声明
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(374): error C2955: “std::shared_ptr”: 使用 类 模板 需要 模板 参数列表
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\memory(1490): note: 参见“std::shared_ptr”的声明..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(374): error C2061: 语法错误: 标识符“padGradNodeCompat”
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(377): error C3536: “grad_node”: 初始化之前无法使用
..\paddle\fluid\eager\api\generated\fluid_generated\forwards\dygraph_forward_functions1.cc(384): error C2665: “egr::EagerUtils::SetHistory”: 2 个重载中没有一个可以转换所有参数类型

**Comment by Synmul** [comment]
paddle240

WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
WITH_IPU: OFF
CUDA version: 11.2
CUDNN version: v8.2
CXX compiler version: 19.29.30148.0

**Comment by Synmul** [comment]
问题解决了   以管理员身份运行就编译成功了

**Comment by wuyefeilin** [comment]
可能是你的cuda版本过高导致，参考该文档进行编译哈：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#anchor-0
