### ISSUE TITLE
predictor->Run() : Microsoft C++ 异常: phi::enforce::EnforceNotMet

### ISSUE THREAD

**Issue by Synmul** [PaddlePaddle/Paddle#50648]
![1](https://user-images.githubusercontent.com/50161120/219964002-8dd9916a-5b7b-40b3-a035-786b1a743526.png)

win10
vs2019
CUDA version: 11.2
CUDNN version: v8.2
推理库240

CPU&GPU都一样

**Comment by Synmul** [comment]
今天又编译了paddle23  还是同样的问题
![1](https://user-images.githubusercontent.com/50161120/220010180-f6812c30-c511-456f-ab25-30d7b036b916.png)
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
WITH_IPU: OFF
CUDA version: 11.2
CUDNN version: v8.2
CXX compiler version: 19.29.30148.0
WITH_TENSORRT: ON
TensorRT version: v8.2.4.2

**Comment by LemonNoel** [comment]
请详细描述一下遇到的问题，包括安装的 paddle 版本，具体跑的代码以及更多的报错信息。

**Comment by Synmul** [comment]
> 请详细描述一下遇到的问题，包括安装的 paddle 版本，具体跑的代码以及更多的报错信息。

模型用paddle2.2.2训练的，PaddleDetection的ppyoloe+,我有点怀疑是不是这个模型不支持C++推理，晚点下载一下官方训练的模型试试，我下载了官方resnet50模型是没有出异常。

**Comment by LemonNoel** [comment]
好的，如果后续有问题可以再反馈。

**Comment by Synmul** [comment]
> 好的，如果后续有问题可以再反馈。

问题已经解决了，看了一下PaddleDetection的demo发现是没有设置scale_factor。

**Comment by GoXian** [comment]
scale_factor 是什么，我也遇到了，下载了官方resnet50模型是没有出异常，但是我自己的却有问题的情况。
