### ISSUE TITLE
PaddleServing的镜像中没有core_noavx文件

### ISSUE THREAD

**Issue by btobab** [PaddlePaddle/Paddle#50656]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/66876429/220020141-c8103e38-222e-4dfe-b226-926d19e601ca.png">
我的环境是m1 macOS，pull镜像后按照PaddleServing的步骤安装了paddlepaddle2.3.0等，python版本3.6，但是python交互式界面中import paddle后报上面图片中的错误，我谷歌查到是因为fluid文件夹下没有core_noavx文件，但是我去飞桨官网查看2.3.0的wheel文件中，没找到macOS m1 amd的配置文件，只找到了x86的配置文件，我尝试下载了x86的文件，pip安装失败，我实在是黔驴技穷了= =

**Comment by LemonNoel** [comment]
可能是机器的CPU不支持avx指令集，可使用 `sysctl -a | grep machdep.cpu.features` 查看支持的指令集。另外推荐使用 conda 安装最新版本 2.4.1 试试。

**Comment by btobab** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/66876429/220036917-cc6e6807-fb85-45df-90be-3a3ecebc28cd.png">
试过了，还是不行

**Comment by btobab** [comment]
<img width="525" alt="image" src="https://user-images.githubusercontent.com/66876429/220037158-af950d48-e2c1-4479-91f0-9220f20ef28a.png">

**Comment by LemonNoel** [comment]
拉的镜像是 Mac OS 的吗？按照教程再 pull 一个？ https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/macos-docker.html

**Comment by btobab** [comment]
<img width="697" alt="image" src="https://user-images.githubusercontent.com/66876429/220237078-d9516e10-173c-48bc-9127-ca7938476a61.png">
还是不行。。。
我的macOS是13.2，是这个原因吗？

**Comment by btobab** [comment]
<img width="897" alt="image" src="https://user-images.githubusercontent.com/66876429/220281723-9e2ee082-a2f3-483f-81be-bded5dd4ba07.png">

**Comment by wujohns** [comment]
不明白你们为什么要一直执着于avx指令集而放弃设备兼容性。

**Comment by hbo-lambda** [comment]
> 不明白你们为什么要一直执着于avx指令集而放弃设备兼容性，是为了年终答辩的kpi么

是的，有问题么

**Comment by wujohns** [comment]
6，这边已经换机器解决了，但是生态上到现在都玩不懂paddle那套，这一段时间连 hugging face的部署/autodl部署 这边都搞明白了，但依旧搞不懂paddle怎么快捷的部署到百度的平台（文档和产品导航杂，乱，不可能抽出时间每个都去摸一下）。

**Comment by jzhang533** [comment]
我们focus在问题上吧，另外请注意飞桨社区是有[Code of Conduct](https://github.com/PaddlePaddle/Paddle/blob/develop/CODE_OF_CONDUCT_cn.md)需要遵守的。
