### ISSUE TITLE
paddle 能否在ARM环境下安装

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/Paddle#50675]
### 请提出你的问题 Please ask your question

paddle 能否在ARM环境下安装，具体的CPU是飞腾D2000和华芯1620 64c处理器，操作系统都是银河麒麟

**Comment by LemonNoel** [comment]
目前支持的硬件可以参考 [安装文档——更多硬件支持](https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html)，已有支持飞腾FT2000，您可以尝试编译安装。如无法成功使用，可以提出具体需求，我们后续进行评估。
