### ISSUE TITLE
【profiler使用】请问profiler是否可以获取GPU带宽数据，应该怎样获取？

### ISSUE THREAD

**Issue by Jaason19** [PaddlePaddle/Paddle#50682]
RT. 在官网教程中没有找到相关信息。

**Comment by rainyfly** [comment]
你好，我理解这里说的你说的GPU带宽应该不是指厂家硬件规格标注的参数，请问是想指GPU的数据传输速率么。目前profiler会收集Nvidia显卡到计算机内存之间所发生的数据传输的事件，比如当调用memcpy从内存传数据到显存，或者从显存传数据到内存是，profiler是能够获取到memcpy这个行为所传输的数据量和所耗费的时间，然后将数据量/传输时间，来获得传输速率。这个传输速率，你可以通过查看profiler导出的json格式的数据数据，直接用浏览器的trace插件查看，然后在里面找到memcpy的事件，下方的参数列表里会有这一信息。具体操作可以看一下文档
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/performance_improving/profiling_model.html#timeline
