### ISSUE TITLE
官方示例代码问题

### ISSUE THREAD

**Issue by xiaotingyun** [PaddlePaddle/Paddle#50684]
### bug描述 Describe the Bug

https://gitee.com/paddlepaddle/PaddleNLP/blob/develop/model_zoo/bert/create_pretraining_data.py
该代码246行的max_num_tokens是否应该改为target_seq_length

**Comment by LemonNoel** [comment]
gitlab代码非最新官方版本，PaddleNLP相关问题可以到 [PaddleNLP Github](https://github.com/PaddlePaddle/PaddleNLP)  issue 区提问
