### ISSUE TITLE
请问 paddle 中有判断 +0 和 -0 API 吗？

### ISSUE THREAD

**Issue by Ainavo** [PaddlePaddle/Paddle#50694]
### 请提出你的问题 Please ask your question

Pytorch 和 Numpy 中有对应的 signbit 来判断-0还是+0，请问 paddle 中也有类似的 API，或者可以通过组合的方式实现吗？

**Comment by DesmonDay** [comment]
请问这个API一般有什么使用场景呢？我目前没有找到可替代的方案，可能需要内部讨论是否要支持这个API。

**Comment by Ainavo** [comment]
> 请问这个API一般有什么使用场景呢？我目前没有找到可替代的方案，可能需要内部讨论是否要支持这个API。

你好，我在参与 Hackathon API 开发[第10题](https://github.com/PaddlePaddle/Paddle/issues/50630#task10)时，考虑到 -0 和 +0 对应的结果不同（[Pytorch文档](https://pytorch.org/docs/stable/generated/torch.copysign.html?highlight=copysign#torch.copysign)中有指出要注意 0 的符号）

**Comment by DesmonDay** [comment]
那我感觉如果copysign也是torch里面有的函数，那signbit也类似的，需要进行开发。可以考虑能不能放到Hackathon API 开发题目里面看看。

**Comment by Ainavo** [comment]
好的，谢谢

**Comment by cloud2009** [comment]
> 好的，谢谢

您好，Hackathon 的API开发题正在添加这个功能实现要求，请稍等。
