### ISSUE TITLE
静态图运行出错：InvalidArgumentError: The index of 0 in `shape` must be less than the input tensor X's dimensions. But received shape = [1, 10, 0], shape[2] = 0, X's shape = [10, 1024], X's dimensions = 2.

### ISSUE THREAD

**Issue by Ehaschia** [PaddlePaddle/Paddle#50696]
### 请提出你的问题 Please ask your question

一个Transformer Encoder。动态图运行没问题。使用如下方法转成静态图后：
![图片](https://user-images.githubusercontent.com/11350952/220241821-09cdaf73-8972-4fb0-a787-9244ed67a2d9.png)
运行如下代码：
![图片](https://user-images.githubusercontent.com/11350952/220241932-8255d22a-d540-4729-a070-2b6603cdfd32.png)
出现如下错误
![图片](https://user-images.githubusercontent.com/11350952/220242041-f6b1db84-69a4-43b2-b12f-f98542d01f8a.png)
看起来是输入size 的问题，将输入由[1, 10]改为[10]后（debug = np.zeros([10])），出现如下错误：
![图片](https://user-images.githubusercontent.com/11350952/220242357-71daa68f-fab1-4f52-8178-e0490123399d.png)

**Comment by Ehaschia** [comment]
提供一个不知道是否有用的信息：
reshape2 这个operater，如果在加载模型时打开mkldnn:
`config.enable_mkldnn()`
会直接无法load 模型：
![图片](https://user-images.githubusercontent.com/11350952/220245140-062e9466-7e0e-458d-a556-d7567dcbd5d6.png)

**Comment by DesmonDay** [comment]
如果shape换成[10, 1]会怎么样？因为我不是做这方面的，可能后续会需要麻烦推理的同学来看看，但是先提前问问shape如果调整成[10, 1]，运行起来会如何？

**Comment by Ehaschia** [comment]
> 如果shape换成[10, 1]会怎么样？因为我不是做这方面的，可能后续会需要麻烦推理的同学来看看，但是先提前问问shape如果调整成[10, 1]，运行起来会如何？

改成[10, 1]，报错如下：
![图片](https://user-images.githubusercontent.com/11350952/220245738-58e2c370-0ad3-4278-adb4-050235218d4b.png)

**Comment by DesmonDay** [comment]
看起来问题是它会自动加一个维度，填充shape 0？

**Comment by Ehaschia** [comment]
> 看起来问题是它会自动加一个维度，填充shape 0？

可能不确切。下图是我将 input 改为[10, 3, 3]时候的报错（此处 1024 是embedding的纬度）。看起来是只取输入的 [0, 1] dim，然后将[2]这个 dim 填为 0。
![图片](https://user-images.githubusercontent.com/11350952/220249632-c96b91b8-856e-4487-855e-e9073654b217.png)
下图是改成[10, 3, 3, 3]：
![图片](https://user-images.githubusercontent.com/11350952/220249899-49675a64-b85f-4208-9fe9-4f445280ceb9.png)

**Comment by DesmonDay** [comment]
这个代码是基于x2paddle完成的么？

**Comment by Ehaschia** [comment]
> 这个代码是基于x2paddle完成的么？

是的。转出的paddle 动态图运行没问题。转出的静态图，以及自己利用动态图转成的静态图都遇到了这个问题。

**Comment by DesmonDay** [comment]
嗯嗯，最好是可以在x2paddle那边提个issue看看。不过我也麻烦相关同学在看这个问题了。

**Comment by Ehaschia** [comment]
> 嗯嗯，最好是可以在x2paddle那边提个issue看看。不过我也麻烦相关同学在看这个问题了。

改了下代码，输入是[batch, length]形式下， x2paddle 转出的静态图是好的，暂时可用了，非常感谢。
如果你们有时间可以帮忙看下为啥主楼中图一转出的静态图为啥没法用就更好了。谢谢 XD
