### ISSUE TITLE
数据量过大,  线上无法正常预测

### ISSUE THREAD

**Issue by ziyenano** [PaddlePaddle/Paddle#5071]
当数据量不大时, 可以使用少量节点预测 (num_nodes = 5), 但output中, rank-00000 到 rank-00004数据均相同.
同样的脚本和配置, 当需要预测的数据量很大时, 已经碰到如下几种错误:
1. Job Status Series:
epilogue finished
epilogue started
user_main failed (Killed)
job will be killed because agent(16) lost
job will be killed because agent(23) lost
job will be killed because agent(19) lost
user_main started
prologue finished
prologue started
Ready

2. epilogue finished
epilogue started
user_main failed (Status:kTaskStatusExited)
user_main started
prologue finished
prologue started
Ready

3. 不报错, 但是output一直为空

**Comment by majiayuanyuan** [comment]
请问这个问题后来解决了吗？

**Comment by Yancey1989** [comment]
我先关闭这个issue了，MPI集群任务相关信息可以参考内网wiki。
