### ISSUE TITLE
Paddle Inference时FLAGS_gpu_memory_limit_mb=1024设置不生效

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/Paddle#50724]
### bug描述 Describe the Bug

已知FLAGS_gpu_memory_limit_mb=1024用于限制GPU最大允许使用的内存为1GiB。
以下简单代码中，该设置可以工作：
```python
import paddle

paddle.set_flags({"FLAGS_gpu_memory_limit_mb": 1024})

# failed to allocate 8GiB memory on a 3090 24GiB GPU.
tensor = paddle.randn((2, 1024, 1024, 1024), dtype="float32")
```

会有以下报错，说明FLAG生效了，没问题：
```bash
Out of memory error on GPU 0. Cannot allocate 8.000000GB memory on GPU 0, 0.000000B memory has been allocated and available memory is only 1.000000GB.
```

但是, 使用paddle inference推理时，此设置不生效，GPU仍然分配了4GiB的内存。

我的问题是：
**如何在Paddle Inference推理时使用PaddlePaddle提供的 FLAGS_xxx 变量？**

### 其他补充信息 Additional Supplementary Information

参考PaddlePaddle提供的FLAGS_xxx文档：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-eager-delete-scope

**Comment by DesmonDay** [comment]
好的，这块可能得咨询Paddle Inference同学，我问问看。

**Comment by yuanlehome** [comment]
是用的c++做预测吗？另外paddle版本是多少？

**Comment by yuanlehome** [comment]
Paddel Inference c++端设置gflags环境变量不生效问题相关开发人员已经定位原因，请关注后续paddle版本修复情况。

**Comment by yuanlehome** [comment]
ref to https://github.com/PaddlePaddle/Paddle/pull/50864
