### ISSUE TITLE
机器翻译：训练时做beam_search生成（beam_size = 1）

### ISSUE THREAD

**Issue by ColainCYY** [PaddlePaddle/Paddle#5073]
#嗨，我在翻译的demo【seqToseq】里做修改，实现MRT，需要计算当前输入句子的最优解码结果。

目前直接使用了beam_search函数，但是训练过程在forward时崩溃。

这是原解码过程，可以正常训练并预测：

```python
target_language_word = data_layer(name = 'target_language_word', size = target_dict_dim)

trg_embedding = embedding_layer(input = target_language_word, size = word_vector_dim, param_attr = ParamAttr(name='_target_language_embedding'))

group_inputs.append(trg_embedding)

decoder = recurrent_group(name = decoder_group_name, step = lau_decoder_with_attention, input = group_inputs)

lbl = data_layer(name = 'target_language_next_word', size = target_dict_dim)      

cost = classification_cost(input = decoder, label = lbl)

outputs(cost)
```

现在将解码的decoder，换成beam_search()。写法参考 gennerate = true 时的代码。
```python
gipt = GeneratedInput(size=target_dict_dim, embedding_name='_target_language_embedding', embedding_size=word_vector_dim)

group_inputs.append(gipt)

sample_gen = beam_search(name="decode_group", step=lau_decoder_with_attention, input=group_inputs, bos_id=0, eos_id=1, beam_size=1, max_length=max_length)

```

训练过程在 “decode_group”的forward时崩溃了。请问beam_search()是否支持在训练过程使用呢？最小风险训练MRT需要在训练时生成多组译文候选，是否有更好的实现方法呢？

万分苦恼

**Comment by lcy-seso** [comment]
beam search 不能用在训练中，这是PaddlePaddle 目前代码决定的。Minimal Risk Training 想在 Paddle不修改代码现在无法实现。

**Comment by ColainCYY** [comment]
>___< 看来要放弃beam_search... 如果继续使用 recurrent_group ，配合修改内部代码，理论上是否可以实现呢？目前python接口中的 eos_layer，GeneratedInput 等，能否利用呢？
如果可以使用，我打算继续试一试；如果全部需要重写，对我来说也许再继续研究也做不完...
非常感谢！

**Comment by lcy-seso** [comment]
- >目前python接口中的 eos_layer，GeneratedInput 等，能否利用呢？

    - 可以参考 Scheduled Sampling，在这个例子里面，也会将生成的词拿出来。GeneratedInput 并没有什么特别的，只是 maxid + embedding 层。
    - EOS 层只能在beam search中用，实际上逻辑非常简单。https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/RecurrentGradientMachine.cpp#L1089
    - 在recurrent_group 中始终只可以得到上**一个**时刻的输出。如果需要生成前缀，需要自己来实现beam search。

- RecurrentGroup 的代码在这里 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/RecurrentGradientMachine.cpp#L538。
    - recurrent group 的代码非常复杂。我个人感觉，如果不了解这个东西的原理，想明白他在做什么，并且灵活的修改是比较花时间的事情。

**Comment by ColainCYY** [comment]
阻止在训练过程中使用beam_search的模块，是否只是以下每个解码步骤中的  RecurrentLayerGroupSetGenerator 和 eos_layer？
`
    def __real_step__(*args):
        eos_name = "__%s_eos_layer__" % name
        RecurrentLayerGroupSetGenerator(
            Generator(eos_layer_name = eos_name, max_num_frames = max_length, beam_size = beam_size, num_results_per_sample = num_results_per_sample)
            )

        args = list(args)
        args.insert(generated_input_index, gipt.before_real_step()) # 上一时刻译文的trg_embedding.

        predict = gipt.after_real_step(step(*args))

        eos_layer(input=predict, eos_id=eos_id, name=eos_name)

        return predict
`

如果是这样，理论上我换掉相关代码，还是有希望的对不

**Comment by lcy-seso** [comment]
这样修改不可以，会在C++端core掉，这涉及到 RecurrentGroup 实现的原理。

对RecurrentGroup 来说，训练和生成是两个在代码上就完全独立的流程。通过设置`Generator`来决定是否走生成分枝（我记得是）。
1.  Generator 只在生成被处理；
2. Eos 只在生成分枝被处理； 

强行在训练中引入这两个东西，或者没有效果，或者直接让程序崩掉（应该是会崩掉）。上面这些配置在C++端都对应了特殊去处理他们的代码，处于不同的逻辑分枝。这样的修改违背了 RecurrentGroup 正常的使用逻辑。如果不是非常了解/不太想花时间了解，建议不要轻易尝试。
