### ISSUE TITLE
OSError: (External) CUDA error(35), CUDA driver version is insufficient for CUDA runtime version.

### ISSUE THREAD

**Issue by March35** [PaddlePaddle/Paddle#50747]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/48037392/220351126-57ca58eb-bcd8-4ff1-963d-ded9377d6c44.png)

**Comment by DesmonDay** [comment]
这个看错误原因就是cuda driver版本的问题，可以考虑重新安装。
