### ISSUE TITLE
paddle源码编译 aarch64

### ISSUE THREAD

**Issue by kero1997** [PaddlePaddle/Paddle#50748]
### 问题描述 Issue Description

按照飞腾/鲲鹏对于aarch64架构cpu进行源码编译：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 对paddle进行源码编译，在docker里边编译，到了最后一步，似乎无法正确生成whl包

[100%] Packing whl packages------>>>
fatal: no tag exactly matches 'a5875319fe3bdd359895f1f6a11faf21df886f88'
package init file '/root/src/paddle_compile/Paddle/build/python/paddle/libs/__init__.py' not found (or not a regular file)
package init file '/root/src/paddle_compile/Paddle/build/python/paddle/incubate/nn/layer/__init__.py' not found (or not a regular file)
package init file '/root/src/paddle_compile/Paddle/build/python/paddle/incubate/distributed/__init__.py' not found (or not a regular file)
package init file '/root/src/paddle_compile/Paddle/build/python/paddle/incubate/distributed/models/__init__.py' not found (or not a regular file)
/usr/bin/ld: cannot find -lpython3.7m
collect2: error: ld returned 1 exit status
error: command 'g++' failed with exit status 1
make[2]: *** [python/build/.timestamp] Error 1
make[1]: *** [python/CMakeFiles/paddle_python.dir/all] Error 2
make: *** [all] Error 2

### 版本&环境信息 Version & Environment Information

paddle: release/2.3
python版本：3.7
系统环境：主机是统信UOS
docker中源码编译命令如下：cmake编译时指定了自己的python

1. `cmake .. -DPY_VERSION=2 -DPYTHON_EXECUTABLE=xxxx/python/bin/python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF`
2. `make TARGET=ARMV8 -j$(nproc)`

**Comment by peter5232** [comment]
/usr/bin/ld: cannot find -lpython3.7m
这句话不是说明没有这个lib吗，你检查过环境吗，确定一下libpython3.7m.so是否存在？

**Comment by kero1997** [comment]
> /usr/bin/ld: cannot find -lpython3.7m 这句话不是说明没有这个lib吗，你检查过环境吗，确定一下libpython3.7m.so是否存在？

谢谢，已解决，有这个libpython3.7m.so, 但是它找不到，后边重新安装了python3.7, 将libpython3.7m.so，再拷贝到 /usr/local/lib下 编译通过了
