### ISSUE TITLE
Versions were removed from PyPi

### ISSUE THREAD

**Issue by donchkat** [PaddlePaddle/Paddle#50750]
Looks like some versions of PaddlePaddle were removed from PyPi, but they still exist in the original repository.
The versions are: 1.8.2, 1.8.3, 1.8.4.
I opened an issue in PyPi and their answer was that these versions were removed by the owner of the package. 
But I see that these versions were not removed from the Github repository, and they are still listed in many other sources.
Are these versions deprecated or something like this?
This influences different security tools that relay on the PyPi documentation of all available versions for a package.
Thank you.

**Comment by haoyuying** [comment]
The version of paddle<2.1 has been removed,  we recommend using the latest version of the paddle. For version of 1.8, you may download here: https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/conda/linux-conda.html
