### ISSUE TITLE
请问PaddleDetection如何保证两次训练结果一致？

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#50762]
### 请提出你的问题 Please ask your question

目前控制了随机种子，cudnn等变量依然无法保证训练一致，应该如何控制呢？

**Comment by jerrywgz** [comment]
请问是哪个模型呢，随机种子包括numpy seed和paddle seed，可以先看下dataloader产生的数据是否固定，然后再看下网络输出部分。关于cudnn，可以设置下面的环境变量检查cudnn选择的算法
```
export CUDNN_LOGINFO_DBG=1 
export CUDNN_LOGDEST_DBG=./debug.txt
```
