### ISSUE TITLE
编译安装npu版成功，且能识别到卡数，执行却报不是npu版本

### ISSUE THREAD

**Issue by Wuguangnann** [PaddlePaddle/Paddle#50779]
### bug描述 Describe the Bug

如下图，编译安装npu版paddle成功，能识别卡信息，但是训练时失败，定位到是校验不通过。
paddle-custom-npu     0.0.0
paddleocr             2.6.1.0
paddlepaddle          0.0.0

![image](https://user-images.githubusercontent.com/110798296/220287169-256c02b4-1851-4df5-a8cb-c238c4a21bc1.png)

![image](https://user-images.githubusercontent.com/110798296/220286868-8266fb47-a3b3-4661-bd3e-9701d04ed671.png)

![image](https://user-images.githubusercontent.com/110798296/220345421-0668a79b-e64c-4f00-9bbc-74dd85114158.png)

**Comment by qili93** [comment]
您好，is_compiled_with_npu 这个接口在 Custom Device 的适配方式下已经被废弃了，我们后续会开始清理框架中的遗留代码。

请使用 “paddle.is_compiled_with_custom_device('npu')” 来判断，示例如下


![image](https://user-images.githubusercontent.com/16605440/220811422-3b7d37a1-7277-4662-add8-4ba8ce2c48e4.png)
