### ISSUE TITLE
paddle/models的ctr模型，wide部分开启sparse_update后报错

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#5077]
用的paddle/model中的ctr的例子，里面的模型是wide&deep，其中的wide部分输入数据是01稀疏矩阵，因为训练速度很慢，开启了sparse_update，训练时报如下错误，关闭sparse_update时错误消失
![image](https://user-images.githubusercontent.com/10849519/31990097-b9590e6c-b939-11e7-9972-d4dceee3d708.png)

其中wide部分的数据声明（数据为01稀疏矩阵）
![image](https://user-images.githubusercontent.com/10849519/31990246-25f1b6d2-b93a-11e7-9b2b-dae61091f729.png)

开启sparse_update的位置
![image](https://user-images.githubusercontent.com/10849519/31990346-7636b282-b93a-11e7-844d-2124fe5a217d.png)

读取数据那部分代码我根据我们的数据格式做了一些修改，不开启sparse_update是可以正常跑的，issue看到了类似的报错，给的解决方案是让把sparse_update关了，https://github.com/PaddlePaddle/Paddle/issues/364

**Comment by typhoonzero** [comment]
这应该是个bug，可能在这里：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/ParameterClient2.cpp#L269
