### ISSUE TITLE
log类型API需要支持Int类型

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#50772]
### 需求描述 Feature Description

目前在参与【Hackthon No.8】Paddle.xlogy API 的开发，因该API要求需要支持int类型，而paddle.log 并不支持int类型，导致无法完成该任务; 

【Hackathon No.8】的rfc pr链接: https://github.com/PaddlePaddle/community/pull/365

**Comment by haoyuying** [comment]
您好，感谢您提供的pr，我们会尽快发起评审并给予反馈，感谢您对开源社区的贡献。

**Comment by luotao1** [comment]
fixed by:
-  #54089

**Comment by luotao1** [comment]
fixed by:
- https://github.com/PaddlePaddle/Paddle/pull/54089
