### ISSUE TITLE
在book中“识别数字”如何引用其他训练数据

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#5079]
在book的第二章，手写体识别，我想测试使用我的自己的训练数据，应该怎么做呢？[章节链接](https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/README.cn.mdl)

**Comment by pkuyym** [comment]
这个需要你按照文档说明的格式，提供相应的data reader，参考https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/mnist.py

**Comment by yeyupiaoling** [comment]
官网教程[http://paddlepaddle.org/docs/develop/models/image_classification/README.html](http://paddlepaddle.org/docs/develop/models/image_classification/README.html)
