### ISSUE TITLE
官网给的paddle老版本pip安装镜像地址里没有1.8之前的版本，想问问该怎么去哪下

### ISSUE THREAD

**Issue by a986052522** [PaddlePaddle/Paddle#50795]
### 请提出你的问题 Please ask your question

如上，想在colab使用paddle1.7，但镜像里找不到所以报错了，最旧的是1.8的

**Comment by haoyuying** [comment]
您好，建议使用paddle2.0以上版本，目前1.x版本已经停止维护，2.x版本在持续更新中。
旧版本安装链接：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/conda/linux-conda.html
