### ISSUE TITLE
paddle和pytorch的Tensor的切片特性为何有差异？

### ISSUE THREAD

**Issue by ellinyang** [PaddlePaddle/Paddle#50806]
paddle和pytorch的Tensor的特性差异

paddle原数据和切片后内存地址会变
![image](https://user-images.githubusercontent.com/20673237/220815467-1f2d69e8-1017-4d80-908f-fff58ab9122c.png)

pytorch原数据和切片后内存地址不变
![image](https://user-images.githubusercontent.com/20673237/220815597-6284b184-8f1f-489b-bbe8-fe554546d87b.png)
paddle内存地址变更，导致paddle在对局部值修改时无效，但pytorch可以修改局部值。paddle侧是否有相关的接口可以对齐torch的这个特性，或者能更显示的提示修改无效？
示例：
paddle
paddle_tensor1[:2].set_value(paddle_tensor2) #修改paddle_tensor1无效

pytorch
torch_ensor1.data[:2].copy_(torch_ensor2) # 修改torch_ensor1有效

**Comment by Shixiaowei02** [comment]
您好，请参照 [官网文档说明](https://www.paddlepaddle.org.cn/documentation/docs/api/paddle/Tensor_cn.html)，目前底层内存地址是内部实现，可能不能行为对齐。谢谢

**Comment by liuwqiang** [comment]
我该如何实现copy_算子呢？通过paddle，
![image](https://github.com/PaddlePaddle/Paddle/assets/58454582/a81d0fd7-af67-4aaa-8a72-25dfa60f397c)
例如实现这个功能
