### ISSUE TITLE
Build failed when building in ibm power 8, ppc64le

### ISSUE THREAD

**Issue by juhonkang** [PaddlePaddle/Paddle#50804]
### 问题描述 Issue Description

Due to some key project points, I want to install it on this docker image.
Main OS: RHEL 7.9
[docker image base](https://hub.docker.com/r/ibmcom/powerai)

### 版本&环境信息 Version & Environment Information

Paddle version: 2.4
all the versions of CMake, GCC v.v. I used the same [installation guide](https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/linux-compile_en.html#compile_from_host). 
![image](https://user-images.githubusercontent.com/67153600/220813592-6672cdf1-3bf7-44aa-83a7-f5670655bd20.png)

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: N/A
CMake version: version 3.16.0
Libc version: glibc 2.27
Python version: 3.8.16

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by Shixiaowei02** [comment]
您好，Paddle 可能还不支持这个 docker 镜像，请在 gcc 目录下尝试搜索 pmmintrin.h 头文件，看是否存在。如果不存在，请在源代码中修改对应宏定义（`GCC_WITHOUT_INTRINSICS`），关闭这个头文件的包含，然后再次尝试。谢谢
