### ISSUE TITLE
在“book”中的“数字识别”如何使用已训练的模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#5080]
在[数字识别](https://github.com/PaddlePaddle/book/blob/develop/02.recognize_digits/README.cn.md)这章中，每次都有从零开始训练，太慢了，能不能使用之前已经训练过的模型

**Comment by pkuyym** [comment]
可以调用from_tar用训练好的模型初始化参数，然后继续训练即可

**Comment by yeyupiaoling** [comment]
@pkuyym 解决了，谢谢。我之前搞了好几天
