### ISSUE TITLE
one_hot 算子参数问题

### ISSUE THREAD

**Issue by Patrick-Star125** [PaddlePaddle/Paddle#50812]
### 关于`one_hot`算子的`num_class`参数定义问题

![image](https://user-images.githubusercontent.com/69072522/220849367-cf20d859-28ca-4386-909f-442465045e0d.png)
![image](https://user-images.githubusercontent.com/69072522/220849394-e7c36f4b-ab0a-4559-984a-df7befb10850.png)

文档中表示它只能是一个标量，实际使用也确实只能是int标量，但是在代码中它还是有`tensor`形式

![image](https://user-images.githubusercontent.com/69072522/220849683-943ceee7-3f4e-484e-874b-7c295d81183b.png)

请问它作为tensor时表示什么含义呢，什么场景下num_class可以作为tensor输入？

**Comment by Shixiaowei02** [comment]
您好，看了下源代码，我的理解是，`depth` 在传入 Tensor 的时候，不再是一个超参数，将是网络的中间变量，在 `one_hot_v2_op.cc` 中以 `depth_tensor` 传入。

**Comment by Patrick-Star125** [comment]
谢谢，我理解了，只有输入`depth_tensor `的形状为0-D时成立
