### ISSUE TITLE
AttributeError: 'ParallelEnv' object has no attribute '_device_id'

### ISSUE THREAD

**Issue by shubhamrai99** [PaddlePaddle/Paddle#50863]
### bug描述 Describe the Bug

#FROM nvidia/cuda:11.2-cudnn8-runtime-ubuntu20.04
#RUN apt-get update
#FROM python:3.7
FROM registry.baidubce.com/paddlepaddle/paddle:2.1.3-gpu-cuda11.2-cudnn8
#RUN apt-get update 
#RUN apt-get install -y python3.7-pip3.7
RUN pip3.7 install --upgrade pip -i https://mirror.baidu.com/pypi/simple
RUN pip3.7 install mlflow --ignore-installed certifi
ENV DEBIAN_FRONTEND=noninteractive

# Install pip packages
COPY requirements.txt .

RUN pip3.7 install -r requirements.txt

#RUN apt update

#RUN apt install -y python3-opencv

# Create working directory
RUN mkdir -p /app

WORKDIR /app

# Copy contents
COPY . .

# Set environment variables
RUN chmod +x train.sh
CMD ./train.sh

trying to create a docker file for training but getting above error , installing paddelpaddel-gpu also ,can anybody help please

**Comment by SunNy820828449** [comment]
请给出更加详细的错误信息，是安装问题还是跑代码报错

**Comment by Rudragoud** [comment]
File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/train.py", line 205, in <module>
    config, device, logger, vdl_writer = program.preprocess(is_train=True)
  File "/content/drive/MyDrive/PaddleOCR-release-2.6/tools/program.py", line 666, in preprocess
    .dev_id) if use_gpu else 'cpu'
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/dygraph/parallel.py", line 208, in device_id
    return self._device_id
AttributeError: 'ParallelEnv' object has no attribute '_device_id'. Did you mean: 'device_id'?

**Comment by EdwirdsLy** [comment]
The answers to issue #46377 are related to your question and installing paddlepaddle-gpu helped me solve the same problem.

**Comment by MathewsJosh** [comment]
The answers to issue #46377 are related to your question and installing paddlepaddle-gpu helped me solve the same problem.
