### ISSUE TITLE
我对GeomGCL该文章模型进行调试发现一个bug 希望得到帮助

### ISSUE THREAD

**Issue by liutiaxqabs** [PaddlePaddle/Paddle#50860]
### 请提出你的问题 Please ask your question

文章 GeomGCL: Geometric Graph Contrastive Learning for Molecular Property Prediction
代码位置 preprocess.py 函数 3D文件生成 preprocess.featurize_mol_sdf（mol）
 问题描述：该部分报错提示要将smiles分子转换成mol格式进行预处理。但是在经过修改后出现了另一个无法解决的错误，导致部分数据集无法正常生成pkl文件 （官方数据集esol可运行，freesolv和lipop无法运行。运行到一半报错ValueError: Bad Conformer Id） ，且针对报错信息在经过AllChem.EmbedMolecule(mol）优化后仍无法解决
代码：
def featurize_mol_sdf(smiles):
    mol =  AllChem.MolFromSmiles(smiles)
    AllChem.EmbedMolecule(mol)
    #AllChem.MMFFOptimizeMolecule(mol)
    #AllChem.UFFOptimizeMolecule(mol)
    Chem.AddHs(mol)
    pos_matrix = mol.GetConformer().GetPositions()
    ******
    ******

**Comment by SunNy820828449** [comment]
好的 已经反馈给相关开发的同学

**Comment by anonymous-kdd** [comment]
由于运行环境和rdkit版本的不同，有可能会产生构象生成失败的情况，因为生成过程是随机的，可以考虑重复几次看看是否能完成转换过程；如果还无法解决可以直接使用freesolv和lipop生成好的sdf文件：https://pan.baidu.com/s/1Wjx73AV3grqtR6DgCMzUHA  密码:85f1

**Comment by agave233** [comment]
由于运行环境和rdkit版本的不同，有可能会产生构象生成失败的情况，因为生成过程是随机的，可以考虑重复几次看看是否能完成转换过程；如果还无法解决可以直接使用freesolv和lipop生成好的sdf文件：https://pan.baidu.com/s/1Wjx73AV3grqtR6DgCMzUHA 密码:85f1
