### ISSUE TITLE
自动检测显卡驱动问题

### ISSUE THREAD

**Issue by abcdlwe** [PaddlePaddle/Paddle#50873]
### 请提出你的问题 Please ask your question

报错提示：
E0224 15:37:10.817626 18616 place.cc:359] Cannot use GPU because you have installed CPU version PaddlePaddle.
If you want to use GPU, please try to install GPU version PaddlePaddle by: pip install paddlepaddle-gpu
If you only have CPU, please change CUDAPlace(0) to be CPUPlace().
飞浆版本为：2.4 CPU版本
请问各位大佬这种问题如何解决呀

**Comment by SunNy820828449** [comment]
添加一句paddle.set_device("cpu") 试试
