### ISSUE TITLE
Support for newer protobuf versions 

### ISSUE THREAD

**Issue by p-wysocki** [PaddlePaddle/Paddle#50888]
### 需求描述 Feature Description

Version specified in the newest release (2.4.2) is quite low: 
`protobuf>=3.1.0, <=3.20.0`

Version currently on `develop` allows for higher versions: 
`protobuf>=3.20.0 ; platform_system != "Windows"`
`protobuf>=3.1.0, <=3.20.2 ; platform_system == "Windows"`

Is there any ETA of the required `protobuf` version changes?

### 替代实现 Alternatives

NA

**Comment by SunNy820828449** [comment]
好的 我给负责同学反馈一下
