### ISSUE TITLE
seqToseq demo Pretrained model can't be downloaded

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#509]
I want to download the pretrained model by the script "wmt14_model.sh" in the seqToseq demo.  The command is "wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/wmt14_model.tar.gz --no-check-certificate". I tried many kinds of VPNs but failed to download. So I wonder if you can provide a download site which can be reached in China without VPN.

**Comment by luotao1** [comment]
You can have a look in `wmt14_model.sh`, it says: 
```# you can also directly download from https://pan.baidu.com/s/1o8q577s```

**Comment by reyoung** [comment]
@luotao1 @dayhaha It should be added to Paddle CDN. I will handle it.
