### ISSUE TITLE
arm64编译安装paddle出错

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/Paddle#50935]
### 问题描述 Issue Description

如图
![image](https://user-images.githubusercontent.com/55450821/221409992-9d50ebe8-defa-4b9d-910f-d3acb0ef8f96.png)

### 版本&环境信息 Version & Environment Information

2.4.1
ARM64 CPU
无GPU
unbutu20.04
python3.8
编译出错make TARGET=ARMV8 -j$(nproc)

**Comment by hitzhu** [comment]
是在unbutu/arm64的docker镜像里面编译的，docker宿主机是x86架构

**Comment by engineer1109** [comment]
这个问题，自己动手该一改，强转void*

**Comment by zyfncg** [comment]
如果是编译ARM的代码，建议使用arm架构的宿主机。x86主机编译ARM可能有架构不兼容的问题

**Comment by Mewral** [comment]
@zyfncg 你好，想问下如果arm机器无法联网，编译时需要通过git下载 如何解决？

**Comment by zyfncg** [comment]
> @zyfncg 你好，想问下如果arm机器无法联网，编译时需要通过git下载 如何解决？

这种得先在有网的机器上下好之后，再拷贝到arm机器上了

**Comment by Mewral** [comment]
> > @zyfncg 你好，想问下如果arm机器无法联网，编译时需要通过git下载 如何解决？
> 
> 这种得先在有网的机器上下好之后，再拷贝到arm机器上了

谢谢，想问下在x86的宿主机的arm64镜像里编译是一定不行吗？还是可能有问题

**Comment by zyfncg** [comment]
也不是一定不行，这个因为没有做过专门的验证，所以可能会有问题。
git下载的源码大部分应该是和架构无关的。
