### ISSUE TITLE
报名

### ISSUE THREAD

**Issue by LittlefishStudent** [PaddlePaddle/Paddle#50960]
### 问题描述 Please describe your issue

【队名】：想发sci的小鱼

【序号】：104

【状态】：报名

【链接】：https://github.com/PaddlePaddle/PaddleNLP

**Comment by zoooo0820** [comment]
你好，黑客松活动报名的话，请直接在该issue下回复 https://github.com/PaddlePaddle/Paddle/issues/50629

**Comment by LittlefishStudent** [comment]
#50629

**Comment by zoooo0820** [comment]
@LittlefishStudent 辛苦点到对应的issue链接里，参考其他参与者的格式，在任务总览的页面里回复哈
