### ISSUE TITLE
paddle训练报错：python: ./eigen-3.4-rc1/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceGpu.h:140: virtual void* Eigen::GpuStreamDevice::allocate(std::size_t) const: Assertion  `err == cudaSuccess' failed.

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/Paddle#50984]
### bug描述 Describe the Bug
PaddlePaddle 2.2.2, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_python: ON
运行环境为v100，python3.7.6

paddle 运行ernie3 base text_matching任务报错
错误信息如：
python: ./eigen-3.4-rc1/unsupported/Eigen/CXX11/src/Tensor/TensorDeviceGpu.h:140: virtual void* Eigen::GpuStreamDevice::allocate(std::size_t) const: Assertion
 `err == cudaSuccess' failed.

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::imperative::BasicEngine::Execute()
1   paddle::imperative::PreparedOp::Run(paddle::imperative::NameVariableWrapperMap const&, paddle::imperative::NameVariableWrapperMap const&, paddle::framewor
k::AttributeMap const&, paddle::framework::AttributeMap const&)
2   paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const
&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tens
or const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::Compute(std::vec
tor<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vec
tor<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&)
3   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddl
e::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bo
ol, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor co
nst&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, pad
dle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<0, 0, 0>(std::vector<paddle::Tensor, std::alloc
ator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::alloc
ator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&)
4   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddl
e::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bo
ol, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<1, 0, 0, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&)
5   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<2, 0, 0, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&)
6   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<3, 0, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
7   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<4, 0, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
8   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<5, 0, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
9   std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::Tensor const&, bool, float, paddle::TypeTag<int> >::Compute<6, 0, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
10  std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<bool, float, paddle::TypeTag<int> >::Compute<7, 0, 0, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&)
11  std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<float, paddle::TypeTag<int> >::Compute<7, 0, 1, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, paddle::Tensor, bool>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool const&)
12  std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > paddle::KernelFuncImpl<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > (*)(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float), &(EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float))>::ComputeCallHelper<paddle::TypeTag<int> >::Compute<7, 0, 2>(std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > const&, std::vector<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> >, std::allocator<std::vector<paddle::Tensor, std::allocator<paddle::Tensor> > > > const&, std::vector<paddle::any, std::allocator<paddle::any> > const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool const&, float const&)
13  EncBackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float)
14  EncCUDABackward(paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, paddle::Tensor const&, bool, float)
15  void enc_cuda_backward_kernel<float>(paddle::Tensor const&, float const*, paddle::Tensor const&, float const*, paddle::Tensor const&, float const*, float*, float*, float*, float*, float*, long, long, long, long, long, float const*, bool, float)
16  Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>& Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>::operator=<Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> >(Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const&)
17  Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const> const, Eigen::GpuDevice, false, (Eigen::internal::TiledEvaluation)0>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const> const&, Eigen::GpuDevice const&)
18  Eigen::TensorEvaluator<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const> const, Eigen::GpuDevice>::evalSubExprsIfNeeded(float*)
19  Eigen::TensorEvaluator<Eigen::TensorCwiseBinaryOp<Eigen::internal::scalar_difference_op<float, float>, Eigen::TensorCwiseUnaryOp<Eigen::internal::scalar_opposite_op<float>, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const> const, Eigen::GpuDevice>::evalSubExprsIfNeeded(float*)
20  Eigen::TensorEvaluator<Eigen::TensorContractionOp<Eigen::array<Eigen::IndexPair<long>, 1ul> const, Eigen::TensorMap<Eigen::Tensor<float, 2, 0, long>, 0, Eigen::MakePointer> const, Eigen::TensorMap<Eigen::Tensor<float, 3, 0, long>, 0, Eigen::MakePointer> const, Eigen::NoOpOutputKernel const> const, Eigen::GpuDevice>::evalSubExprsIfNeeded(float*)
21  Eigen::GpuDevice::allocate(unsigned long) const
22  Eigen::GpuStreamDevice::allocate(unsigned long) const

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1677500509 (unix time) try "date -d @1677500509" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3f800003d97) received by PID 15767 (TID 0x7f87ecebb740) from PID 15767 ***]

### 其他补充信息 Additional Supplementary Information

另外模型支持core之后，无损重启吗？比如训练了几天的任务因为异常失败，重新训练的效率很低

_No response_

**Comment by zoooo0820** [comment]
你好，辛苦尝试下新一些的Paddle版本呢。 另外可以把这个issue在 https://github.com/PaddlePaddle/PaddleNLP/issues 提问一下

**Comment by quaeast** [comment]
@veridone 请问您这个问题最后解决了吗，是哪里出了问题，如何解决了，我今天也遇到了这个问题
