### ISSUE TITLE
Helixfold-Single中出现ImportError

### ISSUE THREAD

**Issue by Yangqy-16** [PaddlePaddle/Paddle#51011]
### bug描述 Describe the Bug

ImportError: cannot import name 'LayerList' from 'paddle.fluid.dygraph' 
when running 'from paddle.fluid.dygraph import Layer, LayerList' 
in helixfold-single/tape/others/transformer_block.py

**Comment by giovannicaprio** [comment]
Same issue here

**Comment by giovannicaprio** [comment]
@Yangqy-16 did you solve it?

**Comment by liguanyun-tech** [comment]
same issue, some one help us?

**Comment by Cynthia29-Wang** [comment]
Same issue here

**Comment by WangZhiwei9** [comment]
changed "from paddle.fluid.dygraph import LayerList"  into "from paddle.nn import LayerList" .
