### ISSUE TITLE
我在使用aistudio上的FairMOT的一个项目，idloss下降的很慢是什么原因呢？

### ISSUE THREAD

**Issue by Zhw1997** [PaddlePaddle/Paddle#51038]
### 请提出你的问题 Please ask your question

我在使用aistudio上的FairMOT的一个项目，idloss下降的很慢是什么原因呢？就刚开始有下降 后面就下降的很慢很慢，有人遇到过这个问题吗？

**Comment by wjj19950828** [comment]
@Zhw1997 建议去[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)提一个Issue~
