### ISSUE TITLE
paddle.utils.run_check()报错

### ISSUE THREAD

**Issue by wrz1999** [PaddlePaddle/Paddle#51060]
### 请提出你的问题 Please ask your question

Running verify PaddlePaddle program ...  W0301 15:27:15.783633 23817 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 3.7, Driver API Version: 11.4, Runtime API Version: 11.7 Could not load library libcudnn_ops_infer.so.8. Error: libcublas.so.11: cannot open shared object file: No such file or directory 
如何解决?

**Comment by linjieccc** [comment]
@wrz1999 你好，请排查下你的cuDNN版本是否和CUDA匹配？
