### ISSUE TITLE
关于文档中NCCL_IB_DISABLE变量的描述

### ISSUE THREAD

**Issue by kehuo** [PaddlePaddle/Paddle#51064]
### 文档链接&描述 Document Links & Description

Hi Paddle同学 你好，

**文档链接**：
【多机多卡训练Tutorial】https://www.paddlepaddle.org.cn/tutorials/projectdetail/2538252

**我的疑问**：
如果我想开启RDMA，那我应该设置 NCCL_IB_DISABLE = 1 还是 0？

**详细描述**：
文档中【常见性能调优设置 - 设置环境变量】一节提到了 NCCL_IB_DISABLE 的设置方法：
![image](https://user-images.githubusercontent.com/48248227/222078745-3b096952-d4cc-4317-be38-e3bde609494e.png)

第一条红线处说：设置 NCCL_IB_DISABLE = 1 开启RDMA
第二条红线处说：设置 NCCL_IB_DISABLE = 1 开启TCP（也就是关闭RDMA）

虽然[Nvidia官方文档](https://docs.nvidia.com/deeplearning/nccl/user-guide/docs/env.html#nccl-ib-disable)说 设置为 1 是**关闭RDMA**（InfiniBand），强制使用TCP。但是这篇Paddle Tutorial文档弄的我有点**不确定**到底怎么设置。

辛苦Paddle同学有空看一下是不是文档的2处写的内容不一致，还是我理解错了。

感谢。

### 请提出你的建议 Please give your suggestion

如果文档有误，辛苦回复我一下 + 更新文档。如果我理解错了，麻烦paddle同学指正～ 感谢哈

**Comment by ForFishes** [comment]
您好，这里应该是paddle的官方文档存在问题。应该是设置为1，就会关闭IB，使用IP scoket。

**Comment by kehuo** [comment]
> 您好，这里应该是paddle的官方文档存在问题。应该是设置为1，就会关闭IB，使用IP scoket。

感谢回复，没其他问题了～
