### ISSUE TITLE
torch API转paddle API

### ISSUE THREAD

**Issue by awsssix** [PaddlePaddle/Paddle#51075]
### 请提出你的问题 Please ask your question

请问torch.initial_seed()怎么改写为paddle代码

**Comment by linjieccc** [comment]
@awsssix 你好，可以用paddle.seed https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/seed_cn.html#seed

**Comment by awsssix** [comment]
不一样的，torch.initial_seed()是产生一个种子，paddle.seed是设置种子

**Comment by linjieccc** [comment]
可以考虑用randomint来生成随机数哈
