### ISSUE TITLE
关于龙芯CPU的说明部分有误

### ISSUE THREAD

**Issue by loongson-zn** [PaddlePaddle/Paddle#51113]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/inference/master/guides/hardware_support/cpu_loongson_cn.html
关于龙芯CPU安装说明部分

第一步用 -DWITH_MIPS=ON 
第二步生成的wheel的后缀是确是loongarch
paddlepaddle-0.0.0-cp37-cp37m-linux_loongarch64.whl
这两步显然是冲突的
### 请提出你的建议 Please give your suggestion

龙芯CPU有两种指令集：Mips 和 LoongArch，建议两种架构可以分开写，毕竟构建过程不一样。Mips 使用的是-DWITH_MIPS=ON， LoongArch 使用的-DWITH_LOONGARCH=ON

WITH_LOONGARCH的定义部分已提交PR
https://github.com/PaddlePaddle/Paddle/pull/51109/files

Other：
默认编译出的whl包，为什么版本都显示0.0.0呢？ 为什么不能显示真正的tag 版本

**Comment by yuanlehome** [comment]
Hi. 这个issue已经在跟进，稍后给您答复。

**Comment by jiweibo** [comment]
> 龙芯CPU有两种指令集：Mips 和 LoongArch，建议两种架构可以分开写，毕竟构建过程不一样

您好，看pr的代码，并没有发现构建过程有什么不一样的地方，如果有不一样的地方，可以详细补充下吗？

**Comment by loongson-zn** [comment]
方法相似，但用WITH_MIPS来控制LoongArch不合适吧，就像WITH_MIPS来控制x86、arm、sw，您觉着合适吗

**Comment by loongson-zn** [comment]
不能让用户对LoongArch和Mips有混淆的概念，这是两种完全不同的架构。

**Comment by loongson-zn** [comment]
其次openblas支持的版本也是区别的，v0.3.18 才开始支持LoongArch ，[opebblas 0.3.18版本发布声明](https://github.com/xianyi/OpenBLAS/releases/tag/v0.3.18)
```
if(WITH_MIPS)
  set(CBLAS_TAG v0.3.13)
endif()

if(WITH_LOONGARCH)
  set(CBLAS_TAG v0.3.18)
endif()

```

**Comment by yuanlehome** [comment]
> 方法相似，但用WITH_MIPS来控制LoongArch不合适吧，就像WITH_MIPS来控制x86、arm、sw，您觉着合适吗

在指令集为MIPS的龙芯CPU上，python识别出的platform name是不是也是这个 ”*_loongarch64.whl“？

**Comment by loongson-zn** [comment]
> > 方法相似，但用WITH_MIPS来控制LoongArch不合适吧，就像WITH_MIPS来控制x86、arm、sw，您觉着合适吗
> 
> 在指令集为MIPS的龙芯CPU上，python识别出的platform name是不是也是这个 ”*_loongarch64.whl“？

当然不一样，LA（即LoongArch）输出为linux_loongarch64.whl；Mips输出为linux_mips64.whl

**Comment by loongson-zn** [comment]
https://github.com/PaddlePaddle/Paddle/pull/51109#issue-1606283299  WITH_LOONGARCH代码已合入，文档未更新
Mips构建：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_MIPS=ON \
         -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF
LoongArch构建：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_LOONGARCH=ON \
         -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF

**Comment by loongson-zn** [comment]
问题已解决，关闭issue
