### ISSUE TITLE
paddleocr c++源码部署，window10编译成功的dll，如何在Windows7 旗舰版 SP1中正常运行，需要的运行库要安装哪些

### ISSUE THREAD

**Issue by zhaocanglong** [PaddlePaddle/Paddle#51116]
### 请提出你的问题 Please ask your question

系统环境/System Environment：Windows7 旗舰版 SP1
版本号/Version： PaddleOCR： 2.6
完整报错/Complete Error Message： window10编译成功的dll报错，找不到指定模块
Windows 10中安装了
VC_redist.x64.exe
VisualCppBuildTools_Full.exe离线版
这两个安装后，paddleocr便可以成功执行

**Comment by tink2123** [comment]
w7上检查下paddle是否安装正确：

import paddle
paddle.utils.run_check()

**Comment by tangzhezhi** [comment]
同样的问题，windows10 可以正常运行。windows7 无法运用，报缺少dll。

**Comment by zhaocanglong** [comment]
> 同样的问题，windows10 可以正常运行。windows7 无法运用，报缺少dll。

Windows7缺少了系统运行库 
api-ms-win-core系列的dll

**Comment by tangzhezhi** [comment]
> > 同样的问题，windows10 可以正常运行。windows7 无法运用，报缺少dll。
> 
> Windows7缺少了系统运行库 api-ms-win-core系列的dll

具体缺少了什么呢？把报错的dll都加上了，还是不行啊。
![image](https://user-images.githubusercontent.com/5733504/224258351-ddabca18-e42c-48fc-9a23-dc5b1b454d50.png)
![image](https://user-images.githubusercontent.com/5733504/224258446-f0dd7d8a-caed-4d1e-bc19-ea03d320ed63.png)

**Comment by zhaocanglong** [comment]
微软的运行库需要安装一下 VC_redist.x64.exe
还有需要安装一下
![屏幕截图 2023-03-10 173305](https://user-images.githubusercontent.com/34065993/224279289-6207b34d-f495-4ecf-93ce-0325f3fcb8cf.png)
xu'yao
