### ISSUE TITLE
paddle安装cudnn错误

### ISSUE THREAD

**Issue by zhangzhiqiangccm** [PaddlePaddle/Paddle#51127]
### 问题描述 Issue Description

在ununtu20上安装paddle的develop版本，cuda是11.7版本，cudnn是8.6，在torch环境下已经测试成功，但是paddle下一直报错，错误如下：RuntimeError: (PreconditionNotMet) Cannot load cudnn shared library. Cannot invoke method cudnnGetVersion.
  [Hint: cudnn_dso_handle should not be null.] (at /paddle/paddle/phi/backends/dynload/cudnn.cc:64)

### 版本&环境信息 Version & Environment Information

paddle.version.cudnn()   8.4.1
cuda:11.7

**Comment by ZhangHandi** [comment]
应该是环境变量没有正确设置。请参考这个链接，进行尝试https://github.com/PaddlePaddle/Paddle/issues/50977#issuecomment-1446144205

**Comment by Qiaojiao-225** [comment]
我参考这个命令解决了，使用conda安装，并且把cudnn也安装了
https://github.com/PaddlePaddle/Paddle/issues/42166#issuecomment-1122311209
