### ISSUE TITLE
missing code or unused comment

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#5112]
我在修改[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L2437)的时候发现，有一句注释 `Also based on cudnn ` 并且有获取` cudnn_version = int(g_command_config_args.get("cudnn_version", 0))`，但是好像并没有使用。

翻看很早之前的code是有`cudnn_version >= 4007 `这样一句话的，不知道是在后期改动中误删了？还是说那句comment和`cudnn_version `现在是多余了？

**Comment by luotao1** [comment]
目前cudnn_version建议大于5.0。

**Comment by luotao1** [comment]
需要修改一下代码里的版本号。
