### ISSUE TITLE
请问Paddle静态图下因设备不同导致 empty API在返回空Tensor时不一致是正常情况吗？

### ISSUE THREAD

**Issue by Li-fAngyU** [PaddlePaddle/Paddle#51133]
### 请提出你的问题 Please ask your question
请问Paddle静态图下因设备不同(如CPU，CUDA)导致 empty API在返回空Tensor时不一致是正常情况吗

example code：
```python
import paddle
print(paddle.__version__)
import numpy as np
N = 0
places = [paddle.CPUPlace(),paddle.CUDAPlace(0)]
paddle.enable_static()
for place in places:
    with paddle.static.program_guard(paddle.static.Program()):
        out = paddle.empty([3, N])
        exe = paddle.static.Executor(place)
        res = exe.run(fetch_list=[out])
    print('static:', place, res)
# 2.3.2
# static: Place(cpu) [None]
# static: Place(gpu:0) [array([], shape=(3, 0), dtype=float32)]
```

**Comment by luotao1** [comment]
应该是静态图CPUPlace的问题，换成 `paddle.randint(0, 1, [4, 0])`，输出也是None https://github.com/PaddlePaddle/Paddle/pull/51048#discussion_r1133646661

**Comment by luotao1** [comment]
来自 @chenwhql 的分析
![2A1879C113996E5577D5532309E77169](https://user-images.githubusercontent.com/6836917/225497170-cbe473bc-d33c-458b-a4c4-6b2359b3720a.jpg)
正常这个var都被erase掉了，但gpu在fetch之前，插入了一个memcpy kernel，copy之后的var name变了，所以就还有变量

请 @zhiqiu @From00 看下这个静态图执行器的问题

**Comment by zhiqiu** [comment]
Thanks for feedback, it is fixed in #51735

**Comment by Li-fAngyU** [comment]
感谢大佬们的修复！！！
