### ISSUE TITLE
如何判断paddlepaddle支持tensorrt

### ISSUE THREAD

**Issue by futureflsl** [PaddlePaddle/Paddle#51144]
### 请提出你的问题 Please ask your question

我自己编译了一个paddlepaddle-gpu whl然后安装也成功了，但是不知道是不是支持tensorrt，我编译前已经打开tensorrt，如果在python代码检验是否支持tensorrt.

**Comment by an1018** [comment]
可以在模型推理是开启tensorrt看看是否报错
