### ISSUE TITLE
Paddle缺失 torch.randn_like函数

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#51162]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

复现repo ppdiffusers，发现缺失rand_like：

https://pytorch.org/docs/stable/generated/torch.randn_like.html

### 替代实现 Alternatives

https://pytorch.org/docs/stable/generated/torch.randn_like.html

**Comment by an1018** [comment]
可以通过paddle.randint_like绕过，rand_like生成范围在[0,1)，randint_like设置了low和high
