### ISSUE TITLE
exp算子不支持complex输入

### ISSUE THREAD

**Issue by longRookie** [PaddlePaddle/Paddle#51172]
### 请提出你的问题 Please ask your question

请问我想计算exp(x)，x为复数，但paddle的exp算子不支持复数输入，请问我该怎么解决或者有什么替代办法吗

**Comment by an1018** [comment]
把复数转为实数：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/as_real_cn.html#as-real，
再计算exp试试呢

**Comment by longRookie** [comment]
我们使用欧拉公式进行替代了

**Comment by longRookie** [comment]
我们使用欧拉公式分别计算实部和虚部，然后使用complex转为复数。https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/complex_en.html#complex
