### ISSUE TITLE
paddle inferrence部分函数无法使用

### ISSUE THREAD

**Issue by liumy1111** [PaddlePaddle/Paddle#51173]
### 请提出你的问题 Please ask your question

环境：
gcc 8.4.0
cmake 3.16.8

.h文件
#pragma once
#include <iostream>
#include "paddle_inference_api.h"
#include "common/GlobalConfig.h"
#include "option/DepthSubConfig.h"

using paddle_infer::Config;
using paddle_infer::Predictor;
using paddle_infer::CreatePredictor;

using std::cout;
using std::endl;

class AIPredictor
{
public:
	virtual ~AIPredictor() {};
	virtual void initialize(const AIPredictorParam &param);

public:

    int predict(const std::vector<float> &input0, const std::vector<int> &input_shape0,
                const std::vector<float> &input1, const std::vector<int> &input_shape1,
                std::vector<float> *out_data);
private:
	std::shared_ptr<paddle_infer::Predictor> _predictor;
};

.cpp文件
#include<numeric>
#include "AIPredictor.h"
#include "paddle_inference_api.h"

using paddle_infer::Config;
using paddle_infer::Predictor;
using paddle_infer::CreatePredictor;

void AIPredictor::initialize(const AIPredictorParam &param)
{
    paddle_infer::Config config;
    config.SetCpuMathLibraryNumThreads(param.cpuMathLibraryNumThreads);
    if (param.modelDir != "") {
        config.SetModel(param.modelDir);
    }
    config.SetModel(param.progFilePath, param.paramsFilePath);
    if (param.useOrt) {
        config.EnableONNXRuntime();
        config.EnableORTOptimization();
    } else {
        config.EnableMKLDNN();
    }

    config.EnableMemoryOptim();
    _predictor = CreatePredictor(config);
    return;
}

int AIPredictor::predict(const std::vector<float> &input0, const std::vector<int> &input_shape0,
                        const std::vector<float> &input1, const std::vector<int> &input_shape1,
                        std::vector<float> *out_data) {

    Predictor *ptr = _predictor.get();

    auto input_names = ptr->GetInputNames();
    auto output_names = ptr->GetOutputNames();
    auto input_t0 = ptr->GetInputHandle(input_names[0]);
    input_t0->Reshape(input_shape0);
    input_t0->CopyFromCpu(input0.data());

    auto input_t1 = ptr->GetInputHandle(input_names[1]);
    input_t1->Reshape(input_shape1);
    input_t1->CopyFromCpu(input1.data());

    // auto st = time();
    if (false == ptr->Run())
    {
        LOG_LOGIC_ERROR("predictor run failed!" << endl);
        return -1;
    }
    auto output_t = ptr->GetOutputHandle(output_names[0]);
    std::vector<int> output_shape = output_t->shape();
    int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                  std::multiplies<int>());
    out_data->resize(out_num);
    output_t->CopyToCpu(out_data->data());
    
    // LOG_LOGIC_INFO("run avg time is " << time_diff(st, time()) << " ms" << endl);
    return 0;
}

报错部分函数不能使用：
CMakeFiles/AISubServer.dir/AIPredictor.cpp.o：在函数‘AIPredictor::predict(std::vector<float, std::allocator<float> > const&, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> > const&, std::vector<int, std::allocator<int> > const&, std::vector<float, std::allocator<float> >*)’中：
AIPredictor.cpp:(.text+0x1d6)：对‘paddle_infer::Predictor::GetInputNames()’未定义的引用
AIPredictor.cpp:(.text+0x1e5)：对‘paddle_infer::Predictor::GetOutputNames()’未定义的引用
AIPredictor.cpp:(.text+0x1fb)：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
AIPredictor.cpp:(.text+0x237)：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
AIPredictor.cpp:(.text+0x6f2)：对‘paddle_infer::Predictor::GetOutputHandle(std::string const&)’未定义的引用
CMakeFiles/AISubServer.dir/AIPredictor.cpp.o：在函数‘AIPredictor::initialize(AIPredictorParam const&)’中：
AIPredictor.cpp:(.text+0xbaf)：对‘paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)’未定义的引用
collect2: 错误：ld 返回 1
make[3]: *** [bin/AISubServer] 错误 1
make[2]: *** [src/AISubServer/CMakeFiles/AISubServer.dir/all] 错误 2
make[1]: *** [src/AISubServer/CMakeFiles/AISubServer.dir/rule] 错误 2

把注释的这些函数注释掉，其他函数是可以正常编译的，所以想麻烦帮看一下到底是引用lib库的问题，还是代码本身的问题

**Comment by an1018** [comment]
收到，这边找相关同学看一下

**Comment by liumy1111** [comment]
感谢，请问有结果了吗？

**Comment by b3602sss** [comment]
这几个函数一直都是有定义的，应该是库版本没匹配上之类的问题。请试下https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/ demo看是不是能编译，一步步排查问题.

**Comment by liumy1111** [comment]
请问有适用于gcc 4.8.5的paddle inference 版本吗？发现是gcc 4.8.5版本导致的上面的问题

**Comment by b3602sss** [comment]
没有。下载包最低版本是gcc5.4.

**Comment by liumy1111** [comment]
好的

**Comment by liumy1111** [comment]
https://www.paddlepaddle.org.cn/inference/v2.3/introduction/faq.html 我看上面说支持gcc4.8.2版本？

**Comment by b3602sss** [comment]
> https://www.paddlepaddle.org.cn/inference/v2.3/introduction/faq.html 我看上面说支持gcc4.8.2版本？

没有现成的安装包 你可以自己编译

**Comment by liumy1111** [comment]
GitHub地址是https://github.com/PaddlePaddle/Paddle这个吗？有具体的编译说明吗?直接编译报错

**Comment by liumy1111** [comment]
CMakeFiles/cmTC_0bec1.dir/src.c.o：在函数‘main’中：
src.c:(.text+0x2d)：对‘pthread_create’未定义的引用
src.c:(.text+0x39)：对‘pthread_detach’未定义的引用
src.c:(.text+0x4a)：对‘pthread_join’未定义的引用
src.c:(.text+0x5e)：对‘pthread_atfork’未定义的引用
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_0bec1.dir/build.make:90：cmTC_0bec1] 错误 1
gmake[1]: 离开目录“/home/lmy/code/paddle-inference/Paddle-develop/CMakeFiles/CMakeTmp”
gmake: *** [Makefile:124：cmTC_0bec1/fast] 错误 2

**Comment by liumy1111** [comment]
或者有没有比较快捷的方式，尽快把这个问题沟通一下？

**Comment by b3602sss** [comment]
> CMakeFiles/cmTC_0bec1.dir/src.c.o：在函数‘main’中： src.c:(.text+0x2d)：对‘pthread_create’未定义的引用 src.c:(.text+0x39)：对‘pthread_detach’未定义的引用 src.c:(.text+0x4a)：对‘pthread_join’未定义的引用 src.c:(.text+0x5e)：对‘pthread_atfork’未定义的引用 collect2: error: ld returned 1 exit status gmake[1]: *** [CMakeFiles/cmTC_0bec1.dir/build.make:90：cmTC_0bec1] 错误 1 gmake[1]: 离开目录“/home/lmy/code/paddle-inference/Paddle-develop/CMakeFiles/CMakeTmp” gmake: *** [Makefile:124：cmTC_0bec1/fast] 错误 2

你之前有编译过paddle吗？可以在gcc8.2上尝试编译一下看能不能成功看看是不是gcc版本引起的

**Comment by liumy1111** [comment]
我用gcc8.2是可以正常使用的，但是为了兼容其他的第三方库，需要加上add_definitions(-D _GLIBCXX_USE_CXX11_ABI=0)，此时会报部分函数无法找到
MakeFiles/AISubServer.dir/AIPredictor.cpp.o：在函数‘AIPredictor::predict(std::vector<float, std::allocator > const&, std::vector<int, std::allocator > const&, std::vector<float, std::allocator > const&, std::vector<int, std::allocator > const&, std::vector<float, std::allocator >*)’中：
AIPredictor.cpp:(.text+0x1d6)：对‘paddle_infer::Predictor::GetInputNames()’未定义的引用
AIPredictor.cpp:(.text+0x1e5)：对‘paddle_infer::Predictor::GetOutputNames()’未定义的引用
AIPredictor.cpp:(.text+0x1fb)：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
AIPredictor.cpp:(.text+0x237)：对‘paddle_infer::Predictor::GetInputHandle(std::string const&)’未定义的引用
AIPredictor.cpp:(.text+0x6f2)：对‘paddle_infer::Predictor::GetOutputHandle(std::string const&)’未定义的引用
CMakeFiles/AISubServer.dir/AIPredictor.cpp.o：在函数‘AIPredictor::initialize(AIPredictorParam const&)’中：
AIPredictor.cpp:(.text+0xbaf)：对‘paddle::AnalysisConfig::SetModel(std::string const&, std::string const&)’未定义的引用
collect2: 错误：ld 返回 1
make[3]: *** [bin/AISubServer] 错误 1
make[2]: *** [src/AISubServer/CMakeFiles/AISubServer.dir/all] 错误 2
make[1]: *** [src/AISubServer/CMakeFiles/AISubServer.dir/rule] 错误 2
请问这种有解决办法吗？

**Comment by liumy1111** [comment]
或者哪个分支是比较稳定并且可以被gcc4.8.5或者gcc4.8.2编译的呢？

**Comment by liumy1111** [comment]
请问2.0分支和目前官方lib区别大吗？我用同样的代码
int main(int argc, char *argv[]) {

  int tmprow = 1;
  int tmpcol0 = 39;
  int tmprow1 = 100;
  int tmpcol1 = 20;
  std::vector<float> tmpinput_data0(tmprow * tmpcol0);
  std::vector<int> tmpinput_shape0 = {tmprow, tmpcol0};
  std::vector<float> tmpinput_data1(tmprow * tmprow1 * tmpcol1);
  std::vector<int> tmpinput_shape1 = {tmprow, tmprow1, tmpcol1};
  std::vector<float> tmpout_data;
  ifstream in("/home/lmy/code/paddle/test/resnet50/data.txt", ios::in);
  if (!in.is_open())
	{
	  cout << "open error!" << endl;
		exit(0);
	}
  string line;
  int pos0 = 0;
  int pos1 = 0;
  int linenum = 0;
  while (getline(in, line) && linenum < tmprow) // line中不包括每行的换行符
  { 
    auto data = split(line, " ");
    for (int i = 1; i < tmpcol0 + 1; i++)
    {
      tmpinput_data0[pos0++] = data[i];
    }
    cout << endl;
    for (int i = tmpcol0 + 1; i < data.size(); i++)
    {
      tmpinput_data1[pos1++] = data[i];
    }
    linenum++;
  }
  
  string model_file = "/home/lmy/code/paddle/test/resnet50/resnet50/603392.SH.pdmodel";
  string model_param = "/home/lmy/code/paddle/test/resnet50/resnet50/603392.SH.pdiparams";
  Config config;
  config.SetModel(model_file, model_param);

  config.EnableMemoryOptim();

  auto predictor = CreatePredictor(config);

  auto input_names = predictor->GetInputNames();
  auto input_t0 = predictor->GetInputHandle(input_names[0]);

  input_t0->Reshape(tmpinput_shape0);
  input_t0->CopyFromCpu(tmpinput_data0.data());

  auto input_t1 = predictor->GetInputHandle(input_names[1]);

  input_t1->Reshape(tmpinput_shape1);
  input_t1->CopyFromCpu(tmpinput_data1.data());

  predictor->Run();

  auto output_names = predictor->GetOutputNames();
  auto output_t = predictor->GetOutputHandle(output_names[0]);
  std::vector<int> output_shape = output_t->shape();
  int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                std::multiplies<int>());

  

  std::vector<float> out_data;
  out_data.resize(out_num);
  output_t->CopyToCpu(out_data.data());
  predictor->ClearIntermediateTensor();

  for (auto i = 0; i < out_data.size(); i++)
  {
    cout << "i: " << i << ", data: " << out_data[i] << endl;
  }

  cout << "finished" << endl;
}
官方lib是可以正常运行的，2.0分支报错：
terminate called after throwing an instance of 'paddle::platform::EnforceNotMet'
  what():  

  Compile Traceback (most recent call last):
    File "train_one.py", line 98, in <module>
      TrainTestOne(target_file, gpu_id)
    File "train_one.py", line 84, in TrainTestOne
      paddle.jit.save(model, "{}/{}".format(model_dir_, symbol), input_spec=[feature_input_spec, history_input_spec])
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 631, in wrapper
      func(layer, path, input_spec, **configs)
    File "/home/local/anaconda3/envs/py37/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 872, in save
      with_hook=with_hook)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 528, in concrete_program_specify_input_spec
      *desired_input_spec, with_hook=with_hook)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 436, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 801, in __getitem__
      self._caches[item_id] = self._build_once(item)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 790, in _build_once
      **cache_key.kwargs)
    File "/home/local/anaconda3/envs/py37/lib/python3.7/site-packages/decorator.py", line 232, in fun
      return caller(func, *(extras + args), **kw)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
      return func(*args, **kwargs)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 733, in from_func_spec
      outputs = static_func(*inputs)
    File "/home/aiusers/dxl/feature_cal_ts1/model.py", line 308, in forward
      combine_pred0, combine_pred1, combine_pred2 = self.endToEndFeature(feature)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
      return self._dygraph_call_func(*inputs, **kwargs)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
      outputs = self.forward(*inputs, **kwargs)
    File "/home/aiusers/dxl/feature_cal_ts1/model.py", line 174, in forward
      combine_fea1[:,1:21:2] = paddle.log(combine_fea1[:,1:21:2])
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2189, in __setitem__
      return _setitem_impl_(self, item, value)
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/variable_index.py", line 704, in _setitem_impl_
      inplace_map={"Input": "Out"})
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3621, in append_op
      attrs=kwargs.get("attrs", None))
    File "/home/aiusers/dxl/.local/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2635, in __init__
      for frame in traceback.extract_stack():

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
5   std::_Function_handler<void (paddle::framework::ExecutionContext const&), paddle::framework::OpKernelRegistrarFunctor<paddle::platform::CPUPlace, false, 2ul, paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, int>, paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, long>, paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, float>, paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, double>, paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, bool> >::operator()(char const*, char const*, int) const::{lambda(paddle::framework::ExecutionContext const&)#1}>::_M_invoke(std::_Any_data const&, paddle::framework::ExecutionContext const&)
6   void paddle::operators::SetValueKernel<paddle::platform::CPUDeviceContext, float>::SetValueCompute<2ul>(paddle::framework::ExecutionContext const&) const
7   void paddle::operators::ElementwiseComputeEx<paddle::operators::SubFunctor<float, void>, paddle::platform::CPUDeviceContext, float, float>(paddle::framework::ExecutionContext const&, paddle::framework::Tensor const*, paddle::framework::Tensor const*, int, paddle::operators::SubFunctor<float, void>, paddle::framework::Tensor*)
8   paddle::operators::get_mid_dims(paddle::framework::DDim const&, paddle::framework::DDim const&, int, int*, int*, int*, int*)
9   paddle::platform::EnforceNotMet::EnforceNotMet(paddle::platform::ErrorSummary const&, char const*, int)
10  paddle::platform::GetCurrentTraceBackString()

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 19] and the shape of Y = [1, 10]. Received [19] in X is not equal to [10] in Y.
  [Hint: Expected y_dims[i] == 1 || x_dims[i + axis] == 1 == true, but received y_dims[i] == 1 || x_dims[i + axis] == 1:0 != true:1.] (at /home/lmy/code/paddle-inference/Paddle/paddle/fluid/operators/elementwise/elementwise_op_function.h:88)
  [operator < set_value > error]
已放弃

**Comment by liumy1111** [comment]
麻烦帮看一下上面这个是什么问题？如何解决？

**Comment by liumy1111** [comment]
2.0分支是用的gcc 4.8.5编译的

**Comment by b3602sss** [comment]
一年前已经升级到gcc5.4，gcc4.8已经不支持 建议升级下gcc，老版本的bug也已经不维护

**Comment by liumy1111** [comment]
现在项目gcc升级到5.4，会引起其他库无法编译，这个请问有什么解决办法吗？

**Comment by liumy1111** [comment]
或者4.8.5之前的有没有可以稳定使用的分支？
