### ISSUE TITLE
paddle 能否部分加载fp16权重？

### ISSUE THREAD

**Issue by jiaohuix** [PaddlePaddle/Paddle#51181]
目前我正在搬运[llama](https://github.com/facebookresearch/llama)的代码和权重，发现它的权重是fp16存储的，我尝试用paddle.load加载fp16后转为fp32,再让模型加载，报了如下错：
![6c058b8f2b317f61db46a08f8521f35](https://user-images.githubusercontent.com/68314259/222763658-7fb91c84-ab67-4816-b162-6aeb598d8a1b.png)
我发现如下两个问题：
（1）应该加载fp32的权重，才不会报如上的错误。可是fp32存储会占2倍的内存，为什么加载fp16,在模型加载权重前将权重转为fp32会报错？
（2）llama 7b模型的fp32占26g磁盘，若要加载到显存会超过40g，paddle目前支不支持部分权重加载fp16？我注意到[论文复现）模型参数转换成float16无法读取，pytorch就可以](https://github.com/PaddlePaddle/Paddle/issues/38717)提到只能加载fp32，然后混合精度，这个混合精度是只针对训练的吗？我尝试用auto_cast的o1和o2，都没有减少显存的占用。

希望哪位大佬能给我提提宝贵的建议,感谢感谢感谢！！！

[ppllama](https://github.com/MiuGod0126/ppllama)
[aistudio](https://aistudio.baidu.com/aistudio/projectdetail/5619235)

**Comment by chenqianhe** [comment]
遇到同样的问题。感觉这里跟pytorch差距好大，涉及到llama这类大模型如果不用fp16的话单显卡根本就没办法用了。非常需要一个好的解决方案。

**Comment by engineer1109** [comment]
这些代码需要自己在IR Pass编写

**Comment by jiaohuix** [comment]
> 这些代码需要自己在IR Pass编写

ir pass是？   不过我把权重、模型的加载放到cpu上了，然后每次加载部分权重，内存和显存已经在32g下了，可以close了。不过如果有方法加载更小的模型还请大佬指明方向哈啊哈

**Comment by jiaohuix** [comment]
。
