### ISSUE TITLE
paddle利用docker源码编译，clone github代码连接不上的问题

### ISSUE THREAD

**Issue by zzh-sonny** [PaddlePaddle/Paddle#51196]
### 请提出你的问题 Please ask your question

1.官方文档要求
注意： 编译过程中需要从 github 上下载依赖，请确保您的编译环境能正常从 github 下载代码。
这些要求是具体那些依赖阿，linux服务器科学上网不能保证。如果提前下载下来，需要放入那些文件夹那，对应cmake是不是也要修改。

2.make 时提示下载失败的有这些
443: Connection timed out
Cloning into 'extern_warpctc'...
Cloning into 'extern_mkldnn'...
Cloning into 'extern_cryptopp'...
Cloning into 'extern_threadpool'...
Cloning into 'extern_gflags'...
Cloning into 'extern_gloo'...
Cloning into 'extern_utf8proc'...
Cloning into 'extern_zlib'...
Cloning into 'extern_xbyak'...
Cloning into 'extern_dlpack'...
Cloning into 'extern_pybind'...

**Comment by yt605155624** [comment]
想办法开个代理

**Comment by zzh-sonny** [comment]
挂代理，编译完了。就好奇不挂代理咋操作
