### ISSUE TITLE
FATAL]: hadoop_ls_file: Generate filelist for test failed

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#5120]
请paddle 同学看看，这个是否是由于下载训练集或者测试集导致的

Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local hadoop_home=/home/mpi/nma/bin/../tools/hadoop-client/hadoop
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local fs_name=hdfs://yq01-heng-hdfs.dmop.baidu.com:54310
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local fs_ugi=ns-tieba,ns_tieba_123
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local remote_file=/app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local file_list=./conf/testfilelist
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ local use_hadoop_vfs=False
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ '[' /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata = None ']'
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ '[' False = True ']'
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ /home/mpi/nma/bin/../tools/hadoop-client/hadoop/bin/hadoop dfs -Dfs.default.name=hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 -Dhadoop.job.ugi=ns-tieba,ns_tieba_123 -ls /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata
Thu Oct 26 11:08:33 2017[1,106]<stderr>:+ egrep -v '^Found.*items$'
Thu Oct 26 11:08:33 2017[1,1]<stderr>:ls: Cannot access /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata: No such file or directory.
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ return 0
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ check_return 'hadoop_ls_file: Generate filelist for test meta failed'
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ '[' 0 -ne 0 ']'
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ hadoop_ls_file /home/mpi/nma/bin/../tools/hadoop-client/hadoop hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 ns-tieba,ns_tieba_123 /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata ./conf/testfilelist False
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local hadoop_home=/home/mpi/nma/bin/../tools/hadoop-client/hadoop
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local fs_name=hdfs://yq01-heng-hdfs.dmop.baidu.com:54310
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local fs_ugi=ns-tieba,ns_tieba_123
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local remote_file=/app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local file_list=./conf/testfilelist
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ local use_hadoop_vfs=False
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ '[' /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata = None ']'
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ '[' False = True ']'
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ /home/mpi/nma/bin/../tools/hadoop-client/hadoop/bin/hadoop dfs -Dfs.default.name=hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 -Dhadoop.job.ugi=ns-tieba,ns_tieba_123 -ls /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata
Thu Oct 26 11:08:33 2017[1,87]<stderr>:+ egrep -v '^Found.*items$'
Thu Oct 26 11:08:33 2017[1,69]<stdout>:Download File:  /app/ns/tieba/recommend/deeplearning/increment/38_23/traindata/part-00093
Thu Oct 26 11:08:33 2017[1,69]<stdout>:train meta file numbers:  0
Thu Oct 26 11:08:33 2017[1,69]<stdout>:Download thread numbers:  0
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ return 1
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ check_return 'hadoop_ls_file: Generate filelist for test failed'
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ '[' 1 -ne 0 ']'
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ echo '[./train.sh : 144] [main]'
Thu Oct 26 11:08:33 2017[1,1]<stderr>:[./train.sh : 144] [main]
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ echo '[FATAL]: hadoop_ls_file: Generate filelist for test failed'
Thu Oct 26 11:08:33 2017[1,1]<stderr>:[FATAL]: hadoop_ls_file: Generate filelist for test failed
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ get_stack
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ set +x
Thu Oct 26 11:08:33 2017[1,1]<stderr>:
Thu Oct 26 11:08:33 2017[1,1]<stderr>:*********************Shell Script Stack Trace********************
Thu Oct 26 11:08:33 2017[1,1]<stderr>: @: [./log.sh: 61] check_return
Thu Oct 26 11:08:33 2017[1,1]<stderr>: @: [./train.sh: 144] main
Thu Oct 26 11:08:33 2017[1,1]<stderr>:
Thu Oct 26 11:08:33 2017[1,1]<stderr>:+ exit 1
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ check_return 'mpirun download.py download train data failed'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' 0 -ne 0 ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' 0 -eq 0 ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ test_data_path_var=test_data_path
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ test_meta_data_path_var=test_meta_data_path
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ hdfs_ls_list=./conf/testfilelist
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local_file_list=./test.list
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ hdfs_test_meta_file_list=./conf/test_meta_list
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local_test_meta_file_list=./test.meta.list
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ real_test_data_path=/app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ real_test_meta_data_path=
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' -z /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' -z '' ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ real_test_meta_data_path=None
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata = None ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ hadoop_ls_file /home/mpi/nma/bin/../tools/hadoop-client/hadoop hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 ns-tieba,ns_tieba_123 None ./conf/test_meta_list False
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local hadoop_home=/home/mpi/nma/bin/../tools/hadoop-client/hadoop
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local fs_name=hdfs://yq01-heng-hdfs.dmop.baidu.com:54310
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local fs_ugi=ns-tieba,ns_tieba_123
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local remote_file=None
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local file_list=./conf/test_meta_list
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ local use_hadoop_vfs=False
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' None = None ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ cat /dev/null
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ return 0
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ check_return 'hadoop_ls_file: Generate filelist for test meta failed'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ '[' 0 -ne 0 ']'
Thu Oct 26 11:08:33 2017[1,69]<stderr>:+ hadoop_ls_file /home/mpi/nma/bin/../tools/hadoop-client/hadoop hdfs://yq01-heng-hdfs.dmop.baidu.com:54310 ns-tieba,ns_tieba_123 /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata ./conf/testfilelist False

**Comment by pkuyym** [comment]
```Cannot access /app/ns/tieba/recommend/deeplearning/increment/38_23/test_output/testdata: No such file or directory.```
看一下这个路径能否正常访问到？
