### ISSUE TITLE
Linear网络层输入尺寸单元不匹配的问题

### ISSUE THREAD

**Issue by zcg-joker** [PaddlePaddle/Paddle#51202]
### bug描述 Describe the Bug

在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
```
class Invariance(nn.Layer):
    def __init__(self, extend_channel):
        super(Invariance, self).__init__()
        self.extend_channel =extend_channel
        self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)

    def forward(self, x):
        out =self.dense(x.flatten())
        out=F.relu(out)
        out=paddle.reshape([-1,self.extend_channel,132,132])
        return out,paddle
```
可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下：
Traceback (most recent call last):
  File "train.py", line 131, in <module>
    train(model,train_loader,test_loader)
  File "train.py", line 50, in train
    embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/model.py", line 175, in forward
    extend_channel_img,approximate_yacobian = self.invariance(embedded_img)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/home/aistudio/model.py", line 105, in forward
    out =self.dense(x.flatten())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear
    return _C_ops.linear(x, weight, bias)
ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272
  [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157)
  [operator < linear > error]

**Comment by w5688414** [comment]
> ### bug描述 Describe the Bug
> 在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
> 
> ```
> class Invariance(nn.Layer):
>     def __init__(self, extend_channel):
>         super(Invariance, self).__init__()
>         self.extend_channel =extend_channel
>         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)
> 
>     def forward(self, x):
>         out =self.dense(x.flatten())
>         out=F.relu(out)
>         out=paddle.reshape([-1,self.extend_channel,132,132])
>         return out,paddle
> ```
> 
> 可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下： Traceback (most recent call last): File "train.py", line 131, in train(model,train_loader,test_loader) File "train.py", line 50, in train embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 175, in forward extend_channel_img,approximate_yacobian = self.invariance(embedded_img) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 105, in forward out =self.dense(x.flatten()) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in **call** return self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward x=input, weight=self.weight, bias=self.bias, name=self.name File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear return _C_ops.linear(x, weight, bias) ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272 [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157) [operator < linear > error]
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

您好，flatten会把batch_size的维度给flatten，我尝试实现了一下您想要的版本：

```
import paddle
import paddle.nn as nn
import paddle.nn.functional as F

class Invariance(nn.Layer):
    def __init__(self, extend_channel):
        super(Invariance, self).__init__()
        self.extend_channel =extend_channel
        self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)

    def forward(self, x):
        out =self.dense(x.reshape([x.shape[0],-1]))
        out=F.relu(out)
        out=paddle.reshape([-1,self.extend_channel,132,132])
        return out,paddle

if  __name__ == '__main__':
    model = Invariance(extend_channel=3)
    x = paddle.zeros([32,3,132,132])
    y = model(x)
```

**Comment by zcg-joker** [comment]
是的是的，谢谢你的解答！&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] Linear网络层输入尺寸单元不匹配的问题 (Issue #51202)





  
bug描述 Describe the Bug
 
在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
 class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         out =self.dense(x.flatten())         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle  
可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下： Traceback (most recent call last): File "train.py", line 131, in train(model,train_loader,test_loader) File "train.py", line 50, in train embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 175, in forward extend_channel_img,approximate_yacobian = self.invariance(embedded_img) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 105, in forward out =self.dense(x.flatten()) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward x=input, weight=self.weight, bias=self.bias, name=self.name File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear return _C_ops.linear(x, weight, bias) ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272 [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157) [operator < linear &gt; error]
 
其他补充信息 Additional Supplementary Information
 
No response
  
您好，flatten会把batch_size的维度给flatten，我尝试实现了一下您想要的版本：
 import paddle import paddle.nn as nn import paddle.nn.functional as F class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         breakpoint()         out =self.dense(x.reshape([x.shape[0],-1]))         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle if  __name__ == '__main__':     model = Invariance(extend_channel=3)     x = paddle.zeros([32,3,132,132])     y = model(x)  
&mdash;

**Comment by zcg-joker** [comment]
但是您好，修改了之后还是出现了问题，就是代码能运行，但是似乎没有训练起来？
&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月6日(星期一) 下午4:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] Linear网络层输入尺寸单元不匹配的问题 (Issue #51202)





  
bug描述 Describe the Bug
 
在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
 class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         out =self.dense(x.flatten())         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle  
可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下： Traceback (most recent call last): File "train.py", line 131, in train(model,train_loader,test_loader) File "train.py", line 50, in train embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 175, in forward extend_channel_img,approximate_yacobian = self.invariance(embedded_img) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 105, in forward out =self.dense(x.flatten()) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward x=input, weight=self.weight, bias=self.bias, name=self.name File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear return _C_ops.linear(x, weight, bias) ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272 [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157) [operator < linear &gt; error]
 
其他补充信息 Additional Supplementary Information
 
No response
  
您好，flatten会把batch_size的维度给flatten，我尝试实现了一下您想要的版本：
 import paddle import paddle.nn as nn import paddle.nn.functional as F class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         breakpoint()         out =self.dense(x.reshape([x.shape[0],-1]))         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle if  __name__ == '__main__':     model = Invariance(extend_channel=3)     x = paddle.zeros([32,3,132,132])     y = model(x)  
&mdash;

**Comment by zcg-joker** [comment]
但是您好，修改了之后还是出现了问题，就是代码能运行，但是似乎没有训练起来？







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Linear网络层输入尺寸单元不匹配的问题 (Issue #51202)





  
bug描述 Describe the Bug
 
在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
 class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         out =self.dense(x.flatten())         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle  
可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下： Traceback (most recent call last): File "train.py", line 131, in train(model,train_loader,test_loader) File "train.py", line 50, in train embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 175, in forward extend_channel_img,approximate_yacobian = self.invariance(embedded_img) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 105, in forward out =self.dense(x.flatten()) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward x=input, weight=self.weight, bias=self.bias, name=self.name File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear return _C_ops.linear(x, weight, bias) ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272 [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157) [operator < linear &gt; error]
 
其他补充信息 Additional Supplementary Information
 
No response
  
您好，flatten会把batch_size的维度给flatten，我尝试实现了一下您想要的版本：
 import paddle import paddle.nn as nn import paddle.nn.functional as F class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         breakpoint()         out =self.dense(x.reshape([x.shape[0],-1]))         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle if  __name__ == '__main__':     model = Invariance(extend_channel=3)     x = paddle.zeros([32,3,132,132])     y = model(x)

**Comment by zcg-joker** [comment]
但是您好，修改了之后还是出现了问题，就是代码能运行，但是似乎没有训练起来？
出现的情况就是显存已经被大量占用了，但是GPU利用率为零，调小了batch_size仍然这样？
请问这种情况的原因是什么？







&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月6日(星期一) 下午4:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Linear网络层输入尺寸单元不匹配的问题 (Issue #51202)





  
bug描述 Describe the Bug
 
在定义网络时，我定义了一个网络结构中包含了一个Linear层，定义如下：
 class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         out =self.dense(x.flatten())         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle  
可是在运行过程中，输入tensor的shape为[32,3,132,132]，却报错如下： Traceback (most recent call last): File "train.py", line 131, in train(model,train_loader,test_loader) File "train.py", line 50, in train embedded_img, decoded_watermark,feature_maps,approximate_yacobian = model(carrige_img, watermark) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 175, in forward extend_channel_img,approximate_yacobian = self.invariance(embedded_img) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/home/aistudio/model.py", line 105, in forward out =self.dense(x.flatten()) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in call return self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/common.py", line 176, in forward x=input, weight=self.weight, bias=self.bias, name=self.name File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1882, in linear return _C_ops.linear(x, weight, bias) ValueError: (InvalidArgument) Input(Y) has error dim.Y'dims[0] must be equal to 1672704But received Y'dims[0] is 52272 [Hint: Expected y_dims[y_ndim - 2] == N, but received y_dims[y_ndim - 2]:52272 != N:1672704.] (at /paddle/paddle/phi/kernels/impl/matmul_kernel_impl.h:157) [operator < linear &gt; error]
 
其他补充信息 Additional Supplementary Information
 
No response
  
您好，flatten会把batch_size的维度给flatten，我尝试实现了一下您想要的版本：
 import paddle import paddle.nn as nn import paddle.nn.functional as F class Invariance(nn.Layer):     def __init__(self, extend_channel):         super(Invariance, self).__init__()         self.extend_channel =extend_channel         self.dense =nn.Linear(in_features=3*132*132,out_features=extend_channel*132*132)     def forward(self, x):         breakpoint()         out =self.dense(x.reshape([x.shape[0],-1]))         out=F.relu(out)         out=paddle.reshape([-1,self.extend_channel,132,132])         return out,paddle if  __name__ == '__main__':     model = Invariance(extend_channel=3)     x = paddle.zeros([32,3,132,132])     y = model(x)

**Comment by w5688414** [comment]
@zcg-joker  把代码里面的breakpoint给去掉就行，我加了断点
