### ISSUE TITLE
docker镜像的链接需要更新

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#5122]
http://doc.paddlepaddle.org/doc_cn/getstarted/build_and_install/docker_install_cn.html
![image](https://user-images.githubusercontent.com/10849519/32037743-5a63be12-b9ec-11e7-8ec6-33a2f5f2f6d3.png)
图中docker镜像的链接指向https://hub.docker.com/r/paddledev/paddle/
paddledev的tags已经不更新
最新的地址应该是https://hub.docker.com/r/paddlepaddle/paddle/
麻烦更新下链接

**Comment by luotao1** [comment]
最新的文档请参考：http://doc.paddlepaddle.org/develop/doc_cn/getstarted/build_and_install/docker_install_cn.html 这里我们已经更新地址了。

**Comment by buptwds** [comment]
但是paddle官网进入安装页面，还是会导航到上述的地址

**Comment by luotao1** [comment]
> paddle官网进入安装页面

请问是从哪个地方点进去呢，能否给予详细说明，谢谢

**Comment by buptwds** [comment]
http://doc.paddlepaddle.org/ -> 文档中心 -> 新手入门 -> 安装与编译 -> PaddlePaddle的Docker容器使用方式 -> PaddlePaddle发布的Docker镜像使用说明 -> 链接dockerhub.com会导航到https://hub.docker.com/r/paddledev/paddle/
如果从http://paddlepaddle.org/ 进入文档中心则不会出现上述情况，但是点击home返回首页，也会进入http://doc.paddlepaddle.org/进而复现上述情形

**Comment by luotao1** [comment]
谢谢您的反馈，我们网站正在全面改版，预计11月中旬会上新版。目前最新文档地址为：http://doc.paddlepaddle.org/develop/doc_cn/ 。
