### ISSUE TITLE
paddleinference 多次运行 predictor.run() 出现内存溢出

### ISSUE THREAD

**Issue by robinraicy2018** [PaddlePaddle/Paddle#51223]
### bug描述 Describe the Bug

@paddle.no_grad()
def run(predictor, img):
    # copy img data to input tensor
    input_names = predictor.get_input_names()
    # print("input_names:",input_names)
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)

        input_tensor.reshape(img[i].shape)
        # print("input_tensor:",img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())
    
    # do the inference
    for i in range (1,1000):    
        with paddle.no_grad():
            predictor.run()

    results = []
    # get out data from output tensor
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results

**Comment by 1649759610** [comment]
你好，在跑什么任务呢，模型是什么，batch_size怎么设置的，内存怎么样？可以多描述一些背景，最好提供下最小可复现代码。

**Comment by robinraicy2018** [comment]
from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
import numpy as np
import argparse
import cv2
from PIL import Image, ImageDraw

import time

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img


def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img

def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    img = img[np.newaxis, :]

    return img


if __name__ == '__main__':
    model_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdmodel"
    params_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdiparams"
    use_gpu = True
    img_name = '/home/ais/paddlepaddle/100779044401373698337769799539456113481.jpg'
    im_size = 512
    img = cv2.imread(img_name)
    data = preprocess(img, im_size)
    scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(
        np.float32)
    im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)

    config = Config(model_file, params_file)
    config.enable_memory_optim()
    config.enable_use_gpu(3000, 0)
    predictor = create_predictor(config)
    img = [im_shape, data, scale_factor]
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i].copy())

    for i in range(500):
        predictor.run()
        results = []
        output_names = predictor.get_output_names()
        for i, name in enumerate(output_names):
            output_tensor = predictor.get_output_handle(name)
            output_data = output_tensor.copy_to_cpu()
            results.append(output_data)

        print('results ',time.time(),results)
![微信图片_20230309161015](https://user-images.githubusercontent.com/127073006/223960010-cbec1d5e-1f8d-48cf-9e0e-828b3a8b9573.jpg)
![微信图片_202303091610151](https://user-images.githubusercontent.com/127073006/223960053-a4418af6-e1ce-49f7-b7a9-286e9d30cfc2.jpg)
![微信图片_202303091610152](https://user-images.githubusercontent.com/127073006/223960095-fabaafda-0d94-4dbd-b7fe-6d9074760c70.jpg)
![微信图片_202303091610153](https://user-images.githubusercontent.com/127073006/223960132-97e0fc51-4f66-4950-8698-2d263085d3e4.jpg)

**Comment by robinraicy2018** [comment]
代码如下，后面图片为内存增长情况

from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
import numpy as np
import argparse
import cv2
from PIL import Image, ImageDraw
import time

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img


def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img

def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    img = img[np.newaxis, :]
    return img


  model_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdmodel"
  params_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdiparams"
  use_gpu = True
  img_name = '/home/ais/paddlepaddle/100779044401373698337769799539456113481.jpg'
  im_size = 512
  img = cv2.imread(img_name)
  data = preprocess(img, im_size)
  scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(
      np.float32)
  im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)

  config = Config(model_file, params_file)
  config.enable_memory_optim()
  config.enable_use_gpu(3000, 0)
  predictor = create_predictor(config)
  img = [im_shape, data, scale_factor]
  input_names = predictor.get_input_names()
  for i, name in enumerate(input_names):
      input_tensor = predictor.get_input_handle(name)
      input_tensor.reshape(img[i].shape)
      input_tensor.copy_from_cpu(img[i].copy())

  for i in range(500):
      predictor.run()
      results = []
      output_names = predictor.get_output_names()
      for i, name in enumerate(output_names):
          output_tensor = predictor.get_output_handle(name)
          output_data = output_tensor.copy_to_cpu()
          results.append(output_data)

      print('results ',time.time(),results)


![微信图片_20230309204556](https://user-images.githubusercontent.com/127073006/224027780-0c7e8fb1-ceec-49ef-b68d-a065ad1f6dbe.jpg)
![微信图片_202303092045561](https://user-images.githubusercontent.com/127073006/224027802-a0e1242c-ba74-45b7-b2f7-099897a9574d.jpg)
![微信图片_20230309204557](https://user-images.githubusercontent.com/127073006/224027792-21682bd1-b0bc-4e5e-b2a9-aab4b1e2acb4.jpg)
![微信图片_20230309204558](https://user-images.githubusercontent.com/127073006/224027797-227ca0f8-fd3c-4ad2-b44b-9870ea6fb218.jpg)
