### ISSUE TITLE
Linux 下的 PIP 安装2.4版本 失败

### ISSUE THREAD

**Issue by dreamwpm** [PaddlePaddle/Paddle#51231]
### 问题描述 Issue Description

执行： 
python3 -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
报错：
ERROR: Could not find a version that satisfies the requirement paddlepaddle==2.4.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle==2.4.2

<img width="836" alt="image" src="https://user-images.githubusercontent.com/15938916/223051638-28282a69-f8ef-45d7-947c-d7eda94519a5.png">

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4
Paddle With CUDA: N/A

OS: centos 7
GCC version: (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.17
Python version: 3.11.1

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by 1649759610** [comment]
验证了一下没有问题，可以验证下是否是机器网络环境的原因。

**Comment by kyochou** [comment]
i have the same problem. just use python3.10 to install it. 
python3.10 -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple
3.11 is not  available.


我也有同样的问题, 使用 python3.10 版本安装就可以了. 3.11 安装不了.

**Comment by wencan** [comment]
未解之谜
我python 3.11 安装 2.3.0 也不行
但换上python 3.8 就没问题
