### ISSUE TITLE
Please provide well-structured developer's guide

### ISSUE THREAD

**Issue by zealoct** [PaddlePaddle/Paddle#5125]
I believe it would provide a lot of help to those developers who want to contribute code to Paddle. I really hope there could be a well structured document introducing Paddle's system design from the highest perspective into the very detailed implementation (of course the overview is much more important than the detail).

For me, I have to read a lot of scattered design document and dig into many code implementations without much direction to figure out how to add a new feature. I think this cost developers extra efforts to contribute code.

**Comment by typhoonzero** [comment]
I think our website has improved the document structure very much now, please check out http://www.paddlepaddle.org, I'm going to close this issue for now, please feel free to open some new issue if there's still a problem.
