### ISSUE TITLE
Warning when compiling save_load_op_test.cc

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#5126]
> /home/work/***/softwares/Paddle/paddle/operators/save_load_op_test.cc: In member function 'virtual void SaveLoadOp_CPU_Test::TestBody()':
> /home/work/***/softwares/Paddle/paddle/operators/save_load_op_test.cc:37:67: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (size_t i = 0; i < paddle::framework::product(tensor->dims()); ++i) {
>                                                                    ^
> /home/work/***/softwares/Paddle/paddle/operators/save_load_op_test.cc:53:67: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
>    for (size_t i = 0; i < paddle::framework::product(tensor->dims()); ++i) {

**Comment by luotao1** [comment]
This issue has been fixed
