### ISSUE TITLE
Apple M2如何安装使用PaddlePaddle呢

### ISSUE THREAD

**Issue by Gaia-Wu** [PaddlePaddle/Paddle#51268]
### 请提出你的问题 Please ask your question

我想使用PaddleLabel，我的电脑是Apple M2，不支持AVX，所以我根据官网的提示使用“python3 -m pip download paddlepaddle==2.4.2 -f https://www.paddlepaddle.org.cn/whl/mac/openblas/noavx/stable.html --no-index --no-deps”来进行安装，有提示Successful，但当我import paddle的时候却报错“ModuleNotFoundError: No module named 'paddle'”，我想知道这是什么原因，有解决方法吗？

**Comment by haohongxiang** [comment]
@Gaia-Wu 您好，请先确认您的环境中是否有多个 Python，安装 PaddlePaddle 的 Python3 是否是您预期的位置。如果已确认，麻烦提供一下安装成功的截图。

**Comment by Gaia-Wu** [comment]
> @Gaia-Wu 您好，请先确认您的环境中是否有多个 Python，安装 PaddlePaddle 的 Python3 是否是您预期的位置。如果已确认，麻烦提供一下安装成功的截图。

你好，我确认我设置的虚拟环境里只有一个python，并且安装到的是虚拟环境里。我重新下载旧版本的PaddlePaddle就解决这个问题了😂

**Comment by 350050183** [comment]
楼主的安装方法不是写的是download吗？又没有安装。。。
