### ISSUE TITLE
paddlepaddle不支持aarch64吗?

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/Paddle#51279]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/50578167/223323624-2efefe7b-6863-4853-b346-14790d011cc5.png)

**Comment by haohongxiang** [comment]
@zongzijiayou 请问你是在什么硬件环境下安装paddle呢？

**Comment by zongzijiayou** [comment]
> @zongzijiayou 请问你是在什么硬件环境下安装paddle呢？

你好
![eadc883043c66b4b643993eed0acfe9](https://user-images.githubusercontent.com/50578167/223351366-7d8e2bc1-af6b-46a2-b8c1-d0dfe043eec9.jpg)

**Comment by haohongxiang** [comment]
@zongzijiayou 您好，

**Comment by haohongxiang** [comment]
@zongzijiayou 您好，当前在鲲鹏机器上仅支持通过源码编译的方式安装Paddle，没有release包。源码编译详见[官方文档](https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html)
