### ISSUE TITLE
进行OCR训练时，只会提示NFO: save model in ./output/ch_PP-OCR_v3_det/latest

### ISSUE THREAD

**Issue by HanChinese-LIURUI** [PaddlePaddle/Paddle#51277]
### 请提出你的问题 Please ask your question

![Z%ZEY5PDU45BI0XS{8}RDY](https://user-images.githubusercontent.com/53245262/223317304-923d2139-1157-4c68-8b07-3fddd5fc9ad4.png)
如图，我进行OCR文本检测训练时，只会出现这个INFO,没有其他可用信息

**Comment by haohongxiang** [comment]
用户在PaddleOCR repo下也提了[issue](https://github.com/PaddlePaddle/PaddleOCR/issues/9330)，值班同学已回复。
