### ISSUE TITLE
设置trainer_count > 2时报错

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#5127]
用非cpu的latest版本的paddle，模型用的是models里的ctr，想要提高训练速度，trainer_count=1和trainer_count=2都可以跑，trainer_count > 2时报错，看错误好像是内存不足，但是top查看内存还剩挺多，错误如下BLAS : Program is Terminated. Because you tried to allocate too many memory regions.：
![image](https://user-images.githubusercontent.com/10849519/32048589-9b9cb97e-ba0f-11e7-849f-e23f02c2c606.png)

**Comment by ranqiu92** [comment]
是否可以贴下运行的top情况。
另，报错与内存有关，可以将batch_size改小测试下。

**Comment by buptwds** [comment]
![image](https://user-images.githubusercontent.com/10849519/32212737-3c241cbe-bde6-11e7-8a27-c77ed42d8689.png)
batch_size已经改到100了，还是没用，由于paddle是在docker中运行的，但是启动docker时没有用-m指定内存大小，所以docker可用内存应该就是top中剩余的机器内存。

**Comment by ranqiu92** [comment]
经确认，出现上述问题时使用的是6月前版本的Paddle，目前版本无该问题。
