### ISSUE TITLE
在运行代码时，报错 The device should not be 'gpu'

### ISSUE THREAD

**Issue by F5Psyche** [PaddlePaddle/Paddle#51298]
### 请提出你的问题 Please ask your question

版本：paddle-version 2.4.2
电脑是没有GPU的，故默认配置cpu，具体详情如图

![image](https://user-images.githubusercontent.com/50907156/223364937-17980f2a-6eb8-4dc5-8b32-bb882c07d32d.png)

**Comment by haohongxiang** [comment]
@F5Psyche 看起来像是这段代码只支持在GPU环境下运行，不支持CPU。我找PaddleNLP同学看下。

**Comment by linjieccc** [comment]
@F5Psyche 你好，请尝试下在执行脚本的时候传入参数 ``--device cpu``

**Comment by F5Psyche** [comment]
> @F5Psyche 你好，请尝试下在执行脚本的时候传入参数 `--device cpu`

嗯，一样的报错

**Comment by w5688414** [comment]
Hi, @F5Psyche 这是一个接入taskflow的bug，需要仿照这样修改一下源代码, https://github.com/PaddlePaddle/PaddleNLP/blob/e40e40be094f98d71179cd1a73f07650cc22c455/pipelines/pipelines/nodes/retriever/dense.py#L158

https://github.com/PaddlePaddle/PaddleNLP/blob/e40e40be094f98d71179cd1a73f07650cc22c455/pipelines/pipelines/nodes/question_generator/question_generator.py#L114

**Comment by westfish** [comment]
bug已修复，请参考https://github.com/PaddlePaddle/PaddleNLP/pull/5139 ，运行时注意设置device=cpu
