### ISSUE TITLE
Good first issue for phi kernel output definition

### ISSUE THREAD

**Issue by From00** [PaddlePaddle/Paddle#51292]
### 问题描述 Please describe your issue

大家好，近期我们在Paddle框架中发现一些phi算子库中的算子，在kernel注册时未注册输出参数的数据类型（DataType）信息，导致静态图模式下执行器全静态选kernel出错。我们一共收集了68个存在问题的算子，欢迎大家提交PR来一起修复这些问题。

为了修复这些问题，你需要做的是：
1. 阅读[《开发C++算子》](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/api_contributing_guides/new_cpp_op_cn.html)文档，学习C++算子开发流程。本次任务涉及对已有算子的改动，不需要完整地实现一个新算子，但了解新增算子所涉及的一些基本概念和流程，有助于更好地理解本次任务的具体工作，在遇到问题时也更容易分析排查。
2. 阅读算子的kernel实现，确定该kernel的哪些输出参数是需要注册DataType的。
3. 参考[《Paddle代码贡献指南》](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/code_contributing_path_cn.html)，为kernel添加DataType注册信息。
4. 完成本地测试，并提交PR将代码贡献到PaddlePaddle/Paddle仓库中。

**注：**

1. PR https://github.com/PaddlePaddle/Paddle/pull/51233 给出了修复`top_k`算子的一个具体示例，你可以参照PR描述完成对其它算子的修复。这些case修复难度不大，还能借此了解飞桨的算子开发和注册机制。
2. **该任务时间：PR 截止提交时间是3月31日，截止合入时间是4月3日。**
3. **认领规则：直接回复下 issue 下方**
4. **PR 通过 CI 后，可以评论里 @From00** ，研发会进行审核
5. [历史上的 good first issue 列表](https://github.com/PaddlePaddle/community/tree/master/pfcc#good-first-issue)，也欢迎来提 PR 解决~ 欢迎联系花花加入社区，和我们一起[快乐开源](https://github.com/PaddlePaddle/Paddle/issues/48019)！
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39876205/213131273-361d2bb8-ea48-4f62-9603-0b0401f50337.png">

**待修复算子列表**（整体进度 68/68）
> 按 merge 的时间顺序，排名不分先后：@From00 (1) @huangjiyi (8) @DrRyanHuang (5) @Liyulingyue (6) @Ainavo (2) @GreatV (3) @jinyouzhi (6) @PPPPzhang (2) @sanbuphy(7) @hellolllw (1) @hellockx (1) @404988613 (1) @Little-chick(1) @junxiu777(1) @ccsuzzh (1) @lubiu (1) @Ackeraa (1) @enkilee (3) @AndPuQing (6) @Difers (2) @Tomoko-hjf (2) @LinearTemporalLogic (1) @AndSonder (7)

| 序号 </br>                  | 算子名称</br>                                          | 认领人 | 修复 PR</br> |
| ---------------- | ------------------------------------------------------------ | -------------- | ---------------- | 
|  1  |  accuracy✅ (2023/03/09) | @Liyulingyue   | #51308   |
|  2  |all_close✅ (2023/03/12)| @sanbuphy   | #51410  |
|  3  | all_raw✅ (2023/03/12) | @sanbuphy   |  #51410 |
|  4  |  angle✅ (2023/03/10) | @Liyulingyue   | #51314  |
|  5  |  argsort ✅ (2023/03/19) | @sanbuphy   | #51407   |
|  6  |   argmax ✅ (2023/03/08)| @DrRyanHuang  | #51315  |
|  7  |   argmin ✅ (2023/03/08)| @DrRyanHuang  | #51315  |
|  8  |  as_real✅ (2023/03/09) | @Liyulingyue   | #51313  |
|  9 |  atan2 ✅ (2023/03/16)| @enkilee   | #51312   |
|  10  | auc ✅ (2023/03/13) | @Little-chick    | #51451   |
|  11  |  bincount✅ (2023/03/12) | @hellockx  | #51508   |
|  12  |  check_finite_and_unscale ✅ (2023/04/17)| @AndSonder    | #52941   |
|  13  | clip_by_norm ✅ (2023/03/23) |  @jinyouzhi   |  #51993  |
|  14  |  complex ✅ (2023/03/13)|  @lubiu  | #51478  |
| 15   |  conv3d_coo✅ (2023/03/13) | @sanbuphy   | #51516  |
|  16  |distribute_fpn_proposals✅ (2023/03/13)| @sanbuphy   |  #51516 |
|  17  |  edit_distance ✅ (2023/03/09)| @jinyouzhi   |#51324   |
|  18  |  eig✅ (2023/03/15) | @enkilee   | #51319  |
| 19   | eig_grad  ✅ (2023/04/17)| @AndSonder    | #52941   |
|  20  |  eigh ✅ (2023/04/11) | @LinearTemporalLogic  | #51362  |
|  21  | eigvals ✅ (2023/03/09) | @GreatV   | #51393  |
|  22  |  fft_c2r ✅ (2023/03/19) | @Difers  | #51563 |
|  23  | fft_r2c ✅ (2023/03/19)  | @Difers  | #51563 |
|  24  | fused_adam ✅ (2023/03/09) | @jinyouzhi   | #51323  |
|  25  | fused_matmul ✅ (2023/03/13) | @jinyouzhi   | #51326  |
|  26  |  generate_proposals✅ (2023/03/16) |sanbuphy   |  #51576  |
|  27  | graph_sample_neighbors ✅ (2023/03/29)  | @Tomoko-hjf   | #51503   |
|  28  |  group_norm ✅ (2023/03/29) | @Tomoko-hjf    | #51503  |
| 29   |   histogram✅ (2023/03/14)| @enkilee   | #51317  |
|  30  | instance_norm✅ (2023/03/16)  | @sanbuphy   | #51576  |
| 31   |  is_empty✅ (2023/03/12) | @hellolllw  | #51484  |
|  32  |  is_finite ✅ (2023/03/08)| @DrRyanHuang   | #51322  |
|  33  |  kthvalue✅ (2023/03/13) | @junxiu777    | #51534  |
|  34  |  lamb✅ (2023/04/17)| @AndSonder    | #52941   |
|  35  |   logical_and ✅ (2023/03/08)| @huangjiyi   | #51331  |
|  36  |  logical_not ✅ (2023/03/08)| @huangjiyi   | #51331  |
|  37  |  logical_or ✅ (2023/03/08)| @huangjiyi   |  #51331 |
|  38  |  logical_xor ✅ (2023/03/08)| @huangjiyi    | #51331  |
| 39   | lstsq ✅ (2023/03/08) | @huangjiyi   | #51333  |
| 40   |  lu ✅ (2023/03/08)|  @huangjiyi  |  #51333  |
| 41   | matrix_nms ✅ (2023/03/08) | @huangjiyi   | #51333   |
| 42   |  matrix_rank_tol✅ (2023/03/08) | @huangjiyi   | #51333   |
| 43   |  mode ✅ (2023/03/12)| @ccsuzzh   | #51363  |
|  44  | momentum ✅ (2023/03/24) | @AndPuQing   | #51353  |
|  45  | multiclass_nms3✅ (2023/03/22)  | @AndPuQing   | #51355  |
|  46  | multinomial ✅ (2023/03/17) | @AndPuQing   | #51357  |
|  47  | nanmedian✅ (2023/03/23)  | @AndPuQing   | #51358  |
|  48  | nms ✅ (2023/03/08)  | @Ainavo   | #51325  |
|  49  |  nonzero  ✅ (2023/03/08) |@Ainavo   |  #51325  |
|  50  | numl ✅ (2023/03/10) | @DrRyanHuang   | #51356  |
| 51   |  qr ✅ (2023/03/08)| @GreatV   |#51311   |
|  52  | qr_grad ✅ (2023/03/08) | @GreatV   |#51311   |
|  53  | rnn ✅ (2023/03/16) | @AndPuQing   | #51360  |
|  54  | roi_pool✅ (2023/03/08)  | @Liyulingyue   | #51320  |
|  55  |search_sort✅ (2023/03/16) | @AndPuQing   | #51360  |
|  56  |select✅ (2023/03/14)| @Ackeraa   |  #51595 |
|  57  | send_u_recv ✅ (2023/03/12)  | @PPPPzhang   | #51501  |
|  58  |send_ue_recv ✅ (2023/03/12)|  @PPPPzhang  | #51522   |
|  59  | sgd ✅ (2023/03/09) | @jinyouzhi   | #51332  |
|  60  | svd ✅ (2023/03/10) | @DrRyanHuang   | #51356  |
|  61  |  sync_batch_norm_grad ✅ (2023/04/17)| @AndSonder    | #52941   |
|  62  |  top_k ✅ (2023/03/07)| @From00   |  #51233  |
|  63  |unique✅ (2023/04/17)| @AndSonder    | #52941   |
| 64   | unique_consecutive_flattened_tensor ✅ (2023/04/17)| @AndSonder    | #52941   |
|  65  | unique_raw  ✅ (2023/04/17)| @AndSonder    | #52941   |
|  66  |  viterbi_decode✅ (2023/03/09) | @Liyulingyue   | #51318  |
|  67  |  viterbi_devode✅ (2023/03/13) | @404988613   |  #51523  |
| 68   | yolo_loss ✅ (2023/03/10)  | @Liyulingyue   | #51316  |

**Comment by DrRyanHuang** [comment]
<html>
<body>


认领人 | 任务 | 内容 | PR
-- | -- | -- | --
DrRyanHuang | 6 | arg_max | https://github.com/PaddlePaddle/Paddle/pull/51315
DrRyanHuang | 7 |  argmin | https://github.com/PaddlePaddle/Paddle/pull/51315


</body>
</html>

**Comment by enkilee** [comment]
atan2

**Comment by GreatV** [comment]
|认领人|任务|内容|PR|
|------|------|------|------|
|@GreatV|51| qr | #51311 |
|@GreatV|52| qr_grad| #51311 |

**Comment by longranger2** [comment]
认领10、11、12

**Comment by sanbuphy** [comment]
认领2、3、5

**Comment by Liyulingyue** [comment]
认领1、8、4

**Comment by zade23** [comment]
认领22、23

**Comment by enkilee** [comment]
histogram

**Comment by zrr1999** [comment]
认领 31.is_empty

**Comment by jjyaoao** [comment]
认领63.unique

**Comment by Liyulingyue** [comment]
68

**Comment by Ainavo** [comment]
49

**Comment by Liyulingyue** [comment]
66

**Comment by enkilee** [comment]
18

**Comment by ccsuzzh** [comment]
认领38.logical_xor

**Comment by Liyulingyue** [comment]
54

**Comment by DrRyanHuang** [comment]
<html>
<body>


认领人 | 任务 | 内容 | PR
-- | -- | -- | --
DrRyanHuang | 32 | is_finite | https://github.com/PaddlePaddle/Paddle/pull/51322

</body>
</html>

**Comment by Ainavo** [comment]
48

**Comment by huangjiyi** [comment]
| 序号  | 算子 | 认领人 | PR | 
| ----- | ------ | ------ | ------ | 
| 35, 36, 37, 38  | logical_xxx | @huangjiyi | #51331 |
| 39, 40, 41, 42  | lstsq, lu, matrix_nms, matrix_rank_tol | @huangjiyi | #51333 |

**Comment by jinyouzhi** [comment]
|序号|算子名称|认领人|	修复 PR|
|--|--|--|--|
|17 |edit_distance| @jinyouzhi |#51324|
|24 |fused_adam| @jinyouzhi |#51323|
|25|fused_matmul|@jinyouzhi|#51326|
|59|sgd|@jinyouzhi|#51332|

**Comment by ccsuzzh** [comment]
认领人 | 任务 | 内容 | PR
-- | -- | -- | --
ccsuzzh | 43 | mode | #51363

**Comment by luotao1** [comment]
> 认领38.logical_xor

@ccsuzzh 任务38已经被提 PR 了，可以换一个任务：https://github.com/PaddlePaddle/Paddle/issues/51292#issuecomment-1458396191

**Comment by DrRyanHuang** [comment]
<html>
<body>


认领人 | 任务 | 内容 | PR
-- | -- | -- | --
DrRyanHuang | 50 | numel |  https://github.com/PaddlePaddle/Paddle/pull/51356
DrRyanHuang | 60| svd|   https://github.com/PaddlePaddle/Paddle/pull/51356


</body>
</html>

**Comment by chengyuma** [comment]
认领20

**Comment by AndPuQing** [comment]
| 认领人 |       任务      |                         PR                        |
|:------:|:---------------:|:-------------------------------------------------:|
| PuQing |     momentum    | https://github.com/PaddlePaddle/Paddle/pull/51353 |
| PuQing | multiclass_nms3 | https://github.com/PaddlePaddle/Paddle/pull/51355 |
| PuQing |   multinomial   | https://github.com/PaddlePaddle/Paddle/pull/51357 |
| PuQing |    nanmedian    | https://github.com/PaddlePaddle/Paddle/pull/51358 |
| PuQing |       rnn       | https://github.com/PaddlePaddle/Paddle/pull/51360 |
| PuQing |   searchsorted  | https://github.com/PaddlePaddle/Paddle/pull/51360 |

**Comment by jjyaoao** [comment]
认领33

**Comment by ComputationTreeLogic** [comment]
认领 34 lamb

**Comment by GreatV** [comment]
|认领人|任务|内容|PR|
|------|------|------|------|
|@GreatV|21| eigvals | #51393 |

**Comment by AndSonder** [comment]
认领 56 select

**Comment by sanbuphy** [comment]
认领13 14 15 16

**Comment by Little-chick** [comment]
认领10,PR #51451

**Comment by PPPPzhang** [comment]
认领57，58

**Comment by ShiYue-oo** [comment]
认领 19，64，65

**Comment by 404988613** [comment]
认领61，67

**Comment by Little-chick** [comment]
认领13 14

**Comment by Little-chick** [comment]
#51451

**Comment by luotao1** [comment]
@longranger2 任务10已经有PR：https://github.com/PaddlePaddle/Paddle/issues/51292#issuecomment-1463036231

@sanbuphy @Little-chick 两位请注意：13/14两位都认领了。

**Comment by PPPPzhang** [comment]
认领 26

**Comment by PPPPzhang** [comment]
您好，57中的 send_recv 在kernels目录下没有，但是有 send_u_recv 和 send_uv_recv，请问是对应哪个呢？

**Comment by Fancy-hjyp** [comment]
认领 27， 28

**Comment by From00** [comment]
> 您好，57中的 send_recv 在kernels目录下没有，但是有 send_u_recv 和 send_uv_recv，请问是对应哪个呢？

@PPPPzhang 是send_u_recv

**Comment by PPPPzhang** [comment]
> 

非常感谢！

**Comment by sanbuphy** [comment]
认领 26 27 28 30

**Comment by 404988613** [comment]
认领30

**Comment by 404988613** [comment]
您好，viterbi_devode在phi/kernels中没有找到，该怎么去找对应的呢

**Comment by 404988613** [comment]
您好，61中的sync_batch_norm_grad在phi/kernels中也没有找到，该怎么去找对应的呢

**Comment by From00** [comment]
> 您好，viterbi_devode在phi/kernels中没有找到，该怎么去找对应的呢

@404988613 `viterbi_devode`应为`viterbi_decode`，列表里打错了，已更正。

**Comment by From00** [comment]
> 您好，viterbi_devode在phi/kernels中没有找到，该怎么去找对应的呢

这个算子不存在，是统计错误，`viterbi_devode`应为`viterbi_decode`。`viterbi_decode`已经被修复了，你只需要在黑名单中移除`viterbi_devode`即可。

**Comment by From00** [comment]
> sync_batch_norm_grad

@404988613 sync_batch_norm_grad有两个kernel：
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/sync_batch_norm_grad_kernel.cu
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/sparse/gpu/sync_batch_norm_grad_kernel.cu

**Comment by junxiu777** [comment]
认领33

**Comment by Little-chick** [comment]
case12 -- check_finite_and_unscale找不到这个文件,

**Comment by From00** [comment]
> case12 -- check_finite_and_unscale找不到这个文件,

@Little-chick 看下amp_kernel.cc/.cu

**Comment by Difers** [comment]
<html>
<body>


认领人 | 任务 | 内容 | PR
-- | -- | -- | --
@Difers | 22 | fft_c2r | #51563 
@Difers | 23 | fft_r2c | #51563 


</body>
</html>认领人	任务	内容	PR
@Difers  22	fft_c2r	https://github.com/PaddlePaddle/Paddle/pull/51563
@Difers  23	fft_c2r	https://github.com/PaddlePaddle/Paddle/pull/51563

**Comment by kendaji12138** [comment]
认领22,23  
#51594

**Comment by Ackeraa** [comment]
认领 case56  #51595

**Comment by sanbuphy** [comment]
认领 63 64 65

**Comment by AndSonder** [comment]
认领人 | 任务 | 内容 | PR
-- | -- | -- | --
@AndSonder  | 12 | check_finite_and_unscale | #52941
@AndSonder | 19 | eig_grad | #52941
@AndSonder | 34 | lamb | #52941
@AndSonder | 63 | unique | #52941
@AndSonder | 64 | unique_consecutive_flattened_tensor | #52941
@AndSonder | 65 | unique_raw | #52941

**Comment by luotao1** [comment]
PHI 算子注册信息修复已全部完成，感谢参与的小伙伴们！

> 按 merge 的时间顺序，排名不分先后：@From00 (1) @huangjiyi (8) @DrRyanHuang (5) @Liyulingyue (6) @Ainavo (2) @GreatV (3) @jinyouzhi (6) @PPPPzhang (2) @sanbuphy(7) @hellolllw (1) @hellockx (1) @404988613 (1) @Little-chick(1) @junxiu777(1) @ccsuzzh (1) @lubiu (1) @Ackeraa (1) @enkilee (3) @AndPuQing (6) @Difers (2) @Tomoko-hjf (2) @LinearTemporalLogic (1) @AndSonder (7)

欢迎继续参与[快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/56689)！
