### ISSUE TITLE
export model时请问是否能直接串联两个已有模型？

### ISSUE THREAD

**Issue by SnowWhite11235** [PaddlePaddle/Paddle#51304]
### 请问如何在export model中实现模型A、B的融合，使之产出一个完整的大模型，感谢回复
<img width="734" alt="image" src="https://user-images.githubusercontent.com/18139463/223393930-b109665e-4373-43bd-b0c8-81a9c1f9cc67.png">

**Comment by engineer1109** [comment]
不可以
