### ISSUE TITLE
图像目标检测算法（需求）

### ISSUE THREAD

**Issue by zhifengqi** [PaddlePaddle/Paddle#5131]
是否支持图像目标检测算法，例如比较经典的faster rcnn，ssd等框架，好像没有看到相关的实现。

**Comment by llxxxll** [comment]
ssd demo:https://github.com/PaddlePaddle/models/tree/develop/ssd
[doing]faster-rcnn :https://github.com/PaddlePaddle/Paddle/pull/3496
