### ISSUE TITLE
from x2paddle import models 报错

### ISSUE THREAD

**Issue by SmallRedFeel** [PaddlePaddle/Paddle#51339]
### bug描述 Describe the Bug

from x2paddle import models 报错：AttributeError: type object 'paddle.fluid.libpaddle.VarBase' has no attribute '__getitem__'
<img width="837" alt="微信图片_20230308102221" src="https://user-images.githubusercontent.com/104000067/223604921-94eacaae-6f10-4a8f-89bb-abfb32a4231d.png">
<img width="832" alt="微信图片_20230308102229" src="https://user-images.githubusercontent.com/104000067/223604938-61305c71-9c75-496d-810d-7ab2a0015fcc.png">

**Comment by yhz5256** [comment]
这个问题怎么解决的，我也遇到这个问题，在x2paddle下提了问题，没人回答

**Comment by wjj19950828** [comment]
@yhz5256 ok，我看下

**Comment by wjj19950828** [comment]
@SmallRedFeel 目前问题已经修复

相关PR：https://github.com/PaddlePaddle/X2Paddle/pull/963
