### ISSUE TITLE
麒麟操作系统编译Pdddle 执行cmake时报错

### ISSUE THREAD

**Issue by zongzijiayou** [PaddlePaddle/Paddle#51352]
### 请提出你的问题 Please ask your question

![0586cf804fc0e1dba69dbfaffb0421e](https://user-images.githubusercontent.com/50578167/223640887-0c99dda2-dc2d-4b6f-92df-a775adfbc72e.jpg)

执行命令：cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

python版本：3.9.0

**Comment by zhaoyinglia** [comment]
你好。可以尝试着指定一下 python 版本呢？

**Comment by zhaoyinglia** [comment]
你好。可以尝试指定一下 python 版本呢？-DPY_VERSION=3.9

**Comment by zongzijiayou** [comment]
> 你好。可以尝试指定一下 python 版本呢？-DPY_VERSION=3.9

谢谢，我刚才尝试改了变量换成了3.9，出现了新的错误
![687a12150d19bab6eabac2d0a65aa29](https://user-images.githubusercontent.com/50578167/223642568-78614a2a-5f3a-4e2b-acb8-533ec44c6a1b.jpg)

**Comment by zhaoyinglia** [comment]
pip install wheel
cmake .. -DWITH_GPU=OFF -DPY_WHEEL=/usr/local/lib/python2.7/site-packages/wheel

**Comment by zhaoyinglia** [comment]
你好。可以先安装一下 wheel，pip install wheel。如果已经装好了，可以指定一下路径 -DPY_WHEEL=/usr/...

**Comment by zongzijiayou** [comment]
> 你好。可以先安装一下 wheel，pip install wheel。如果已经装好了，可以指定一下路径 -DPY_WHEEL=/usr/...

好的，我试一下，谢谢

**Comment by zongzijiayou** [comment]
> > 你好。可以先安装一下 wheel，pip install wheel。如果已经装好了，可以指定一下路径 -DPY_WHEEL=/usr/...
> 
> 好的，我试一下，谢谢

你好，我现在还有两个问题：
1、安装wheel后，这个问题可以了，但是还有新的错误，这台服务器没有外网，我已经把相关的依赖手动装上去了，这些信息是否有影响?
![5fb7b221e4fe41b1022698517feccb9](https://user-images.githubusercontent.com/50578167/223651943-4c31bc73-f3c6-4864-a26e-297ac517b25f.jpg)
![403d3ce69c9c14c8f90a97f9c381bd6](https://user-images.githubusercontent.com/50578167/223651959-385aedac-0180-44f1-9645-6e527c2a94fa.jpg)

2、我接下来该执行第九步了，请问aarch64该怎么执行？
![image](https://user-images.githubusercontent.com/50578167/223652169-ad30398e-17c2-4412-87a2-b6be3850e17c.png)
