### ISSUE TITLE
 paddle如何读序列特征，实现类似如下功能：

### ISSUE THREAD

**Issue by caojiangbo0416** [PaddlePaddle/Paddle#51359]
### 请提出你的问题 Please ask your question

 通过 paddle.*.data 和 embedding op，如何读序列特征，实现类似如下功能：
![image](https://user-images.githubusercontent.com/127290167/223652707-bc38c5a9-b2ab-494a-b817-3227ddf36614.png)

**Comment by zhaoyinglia** [comment]
你好。可以试着用一下这个api。https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/pad_cn.html#pad
