### ISSUE TITLE
重新初始化的 optimizer 无法加载权重

### ISSUE THREAD

**Issue by x54-729** [PaddlePaddle/Paddle#51361]
### 请提出你的问题 Please ask your question

您好！最近在实现断点重训的时候发现了一个问题，就是 optimizer 似乎不支持重新加载 state_dict，类似下面的场景：
```python
import paddle
from paddle import nn
from paddle.optimizer import Adam

data = [
    paddle.randn((10, 10)) for _ in range(10)
]
model1 = nn.Linear(10, 10)
optim1 = Adam(0.001, parameters=model1.parameters())
for d in data:
    output = model1(d)
    optim1.clear_grad()
    output.sum().backward()
    optim1.step()

print(optim1.state_dict())

model2 = nn.Linear(10, 10)
optim2 = Adam(0.001, parameters=model2.parameters())
model2.load_dict(model1.state_dict())
optim2.set_state_dict(optim1.state_dict())
print(optim2.state_dict())
```
此时 `optim2` 的 `state_dict` 为空。在实际场景中对应的情况是程序在训练开始前可能会根据参数来加载已经保存好的权重。

我看了一下代码似乎是因为在 optimizer 更新之前 `_accumulators` 为空，所以 `set_state_dict` 在遍历的时候不会加载这些权重。请问目前 paddle 有什么方法来实现这样从零加载 optimizer 权重的方法吗？十分感谢！

**Comment by haohongxiang** [comment]
@x54-729 您好，optimizer初始化后_accumulators为空，此时set_state_dict不会加载权重；但是

**Comment by haohongxiang** [comment]
@x54-729 您好，optimizer set_state_dict的代码如下：
```
self._accumulators_holder = state_dict
for k, v in self._accumulators.items():
         ......
```

虽然在set_state_dict时不会直接添加，但是会用holder dict去维护loaded state dict。正式开始训练时，optimizer.step()会调用_add_accumulator去添加或生成accumulator，这里会在holder dict中匹配相应的权重，代码如下：
```
def _add_accumulator(...):
      ...
      if framework._non_static_mode():
            if len(self._accumulators_holder) > 0:
                  assert (
                        var_name in self._accumulators_holder
                  ), "Optimizer set error, {} should in state dict".format(var_name)
                  var.set_value(self._accumulators_holder[var_name])

            self._accumulators[name][param.name] = var
```

因此，您给的demo中`optim2.set_state_dict(optim1.state_dict())`之后打印是没有信息的，训练第1个step中的优化器计算前才会添加到optimizer._accumulators中。

**Comment by x54-729** [comment]
> @x54-729 您好，optimizer set_state_dict的代码如下：
> 
> ```
> self._accumulators_holder = state_dict
> for k, v in self._accumulators.items():
>          ......
> ```
> 
> 虽然在set_state_dict时不会直接添加，但是会用holder dict去维护loaded state dict。正式开始训练时，optimizer.step()会调用_add_accumulator去添加或生成accumulator，这里会在holder dict中匹配相应的权重，代码如下：
> 
> ```
> def _add_accumulator(...):
>       ...
>       if framework._non_static_mode():
>             if len(self._accumulators_holder) > 0:
>                   assert (
>                         var_name in self._accumulators_holder
>                   ), "Optimizer set error, {} should in state dict".format(var_name)
>                   var.set_value(self._accumulators_holder[var_name])
> 
>             self._accumulators[name][param.name] = var
> ```
> 
> 因此，您给的demo中`optim2.set_state_dict(optim1.state_dict())`之后打印是没有信息的，训练第1个step中的优化器计算前才会添加到optimizer._accumulators中。

原来如此，谢谢解答！
