### ISSUE TITLE
oneDNN operators need to support 0D Tensor

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#51364]
## Backgroud

Paddle plan to support 0D Tensor for API fully.

For 0D Tensor, first describe its concept from a mathematical point of view: 

* **0D Tensor** represents a scalar Tensor, which corresponds to Numpy's 0D array, which can be expressed as np.array (10.), with shape of [], dimension of 0, and size of 1.
* **1D Tensor** represents a vector Tensor, which corresponds to the Numpy's 1D array. If there is only one element, it can be expressed as np.array ([10.]), with shape of [1], dimension of 1, and size of 1.

Scalar Tensor is easily confused with vector Tensor with shape [1].  Although the number of elements are the same, the mathematical definition is completely different. If shape=[1] is forcibly used to represent shape=[], the scalar Tensor and vector Tensor cannot be distinguished. There is a serious diff with the existing mathematical semantics and the general calculation rules in the industry. 

## Feature Description
At present, many APIs have supported 0D in CPU/GPU/XPU/NPU, but there are still some onednn operators that may not support it. 

In total, **the following 35 oneDNN kernels** involve the usage of 0D. There may not be many problems, or there may be a few public problems, or some kernels themselves support them already. And it's need to add thses 0D usage test in OpTest. Like this: https://github.com/PaddlePaddle/Paddle/pull/51265 .

<div class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element"><b style="font-weight:bold"><span>Input 0D</span></b>:</div><div class="mp-table-wrapper"><div data-slate-node="element" style="padding-left:0px" class="mp-table-container">

kernel | 0D Usage need to be supported
-- | --
abs | element-wise unary, 0D->0D
elu | element-wise unary, 0D->0D
exp | element-wise unary, 0D->0D
gelu | element-wise unary, 0D->0D
hardswish | element-wise unary, 0D->0D
leaky_relu | element-wise unary, 0D->0D
mish | element-wise unary, 0D->0D
relu | element-wise unary, 0D->0D
relu6 | element-wise unary, 0D->0D
sigmoid | element-wise unary, 0D->0D
sqrt | element-wise unary, 0D->0D
swish | element-wise unary, 0D->0D
tanh | element-wise unary, 0D->0D
softplus | element-wise unary, 0D->0D
transpose | 0D transpose return itself, perm must be []
cast | element-wise unary, 0D->0D
clip | element-wise unary, 0D->0D
scale | element-wise unary, 0D->0D
expand | 0D can be expanded to 0D or higher dimensions
softmax | when input 0D, outputs is 0D and value is 1.0, grad is 0D and value is 0.0
log_softmax | when input 0D, outputs is 0D and value is 0.0, grad is 0D and value is 0.0
prelu | x and alpha can be 0D, and output is 0D
reshape | []/[1]/[1, 1]/[1, 1, 1] can be reshape to each other
stack | stack multiple 0D to 1D
shape | input can be 0D Tensor, output is [] with shape [0]
add | element-wise binary, should support broadcast. 0D+0D->0D; 0D+ND->ND; ND+0D->ND
substract | element-wise binary, should support broadcast. 0D+0D->0D; 0D+ND->ND; ND+0D->ND
multiply | element-wise binary, should support broadcast. 0D+0D->0D; 0D+ND->ND; ND+0D->ND
divide | element-wise binary, should support broadcast. 0D+0D->0D; 0D+ND->ND; ND+0D->ND
add_n | element-wise multiary, each input can be 0D

</div><div class="mp-table-serialize-flag"><br/></div></div><div class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element"></div><span data-morpho-doc-data='{"token":"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiYXBwSWQiOjEsInVpZCI6IkM2MzhyYVRzbkUiLCJkb2NJZCI6IngwTmxhdjVITXQweVVaIn0..YfjeZbDwvv66wM6X.nDFoj6TgUx_dRCRPeplXmRhbqrnDbaULvWmo32nHBczARmG3KVwFCneebM6P7sRHC5s0q8QhX3mxMm9LIAhplkyAo11fUkrsedcNXKIuYiqmGk8_fNdcCGRyK_clB0DjBzGe8b-d05fCA3_s-Uk0AFIps7uJ7NMjctBSZPiMy6M7aya681ST8jNsuOzZIDajkmoa9Wg4X_77_Ealm5yjtx2kOw.0jqJzHYn143k0wVRqOlEmg"}' class='mp-morpho-clipboard-doc-data'></span>

<div class="mp-paragraph-wrapper" data-morpho-type="paragraph" style="text-align:left;padding-left:0px" data-slate-node="element"><b style="font-weight:bold"><span>Output 0D</span></b>:</div><div class="mp-table-wrapper"><div data-slate-node="element" style="padding-left:0px" class="mp-table-container">

kernel | 0D Usage need to be supported
-- | --
reduce_max | 1) x can be 0D, axis is [], and output is 0D; 2) x is ND, and output is 0D
reduce_min | 1) x can be 0D, axis is [], and output is 0D; 2) x is ND, and output is 0D
reduce_mean | 1) x can be 0D, axis is [], and output is 0D; 2) x is ND, and output is 0D
reduce_sum | 1) x can be 0D, axis is [], and output is 0D; 2) x is ND, and output is 0D
squeeze | compression dimension. The input and output can be 0D, depending on the specific compression dimension. such as 1D.squeeze->0D, 0D.squeeze->0D.
full | when shape=[], will output a 0D Tensor
gaussian | when shape=[], will output a 0D Tensor

</div><div class="mp-table-serialize-flag"><br/></div></div><span data-morpho-doc-data='{"token":"eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2R0NNIiwiYXBwSWQiOjEsInVpZCI6IkM2MzhyYVRzbkUiLCJkb2NJZCI6IngwTmxhdjVITXQweVVaIn0..YfjeZbDwvv66wM6X.nDFoj6TgUx_dRCRPeplXmRhbqrnDbaULvWmo32nHBczARmG3KVwFCneebM6P7sRHC5s0q8QhX3mxMm9LIAhplkyAo11fUkrsedcNXKIuYiqmGk8_fNdcCGRyK_clB0DjBzGe8b-d05fCA3_s-Uk0AFIps7uJ7NMjctBSZPiMy6M7aya681ST8jNsuOzZIDajkmoa9Wg4X_77_Ealm5yjtx2kOw.0jqJzHYn143k0wVRqOlEmg"}' class='mp-morpho-clipboard-doc-data'></span>

**Step1**： First of all, it's need to add 0D case in MKLDNN OpTest Like https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_elementwise_add_op.py#L112-L133 . 

  About how to write 0D unittest case, Maybe you can refer to the https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_zero_dim_tensor.py and imitate it into MKLDNN OpTest.

**Step2**： If the 0D case in OpTest fails, it's need to modify the oneDNN kernel to support 0D case. If success, nothing else will do and only need to push code.

https://github.com/PaddlePaddle/Paddle/pull/51265  just try, because onednn `full kernel` failures when shape=[].

Due to the release of 2.5rc on 2022/4, 0D is expected to be released in this paddle version. It's hoped to support 0D of oneDNN kernel above table in that time. Thank all of you very much.

**Comment by zhwesky2010** [comment]
hi, @YangQun1 `mean/sum` will output 0D.  When I change mean op infermeta from {1} to {}, from 1D to 0D, `test_reduce_mkldnn_op` will failed. 

<img width="795" alt="infoflow 2023-04-16 00-55-08" src="https://user-images.githubusercontent.com/52485244/232244743-0ce5cfad-4cc5-4239-a8dc-50ff1d531960.png">

But https://github.com/PaddlePaddle/Paddle/pull/52185 has been merged. Has it not been fully supported yet?

**Comment by zhwesky2010** [comment]
@YangQun1 @xinyu-intel Hi, https://github.com/PaddlePaddle/Paddle/pull/52739 changed out shape of `paddle.sum/mean` to {}, but `test_reduce_mkldnn_op` failed because of `dnnl error: dimensions are invalid` , so it may not fully supported.

**Comment by YangQun1** [comment]
> @YangQun1 @xinyu-intel Hi, #52739 changed out shape of `paddle.sum/mean` to {}, but `test_reduce_mkldnn_op` failed because of `dnnl error: dimensions are invalid` , so it may not fully supported.

What case is you running? Why changes in https://github.com/PaddlePaddle/Paddle/pull/52739 will impact the onednn ut?

**Comment by YangQun1** [comment]
> @YangQun1 @xinyu-intel Hi, #52739 changed out shape of `paddle.sum/mean` to {}, but `test_reduce_mkldnn_op` failed because of `dnnl error: dimensions are invalid` , so it may not fully supported.

@zhouwei25  Hi, I checked the case. Before https://github.com/PaddlePaddle/Paddle/pull/52739 changes, the output dims of reduce sum op is {1} even reduce_all=true and keep_dims=false, so the issue is not exposed. Can I open a PR against your [zhouwei25:sum_mean_0d](https://github.com/zhouwei25/Paddle/tree/sum_mean_0d) branch? since I can't reproduce the issue without your changes.

**Comment by zhouwei25** [comment]
> 

Yes, you can just change `SumRawInfermeta` to {}, just remove `push_back(1)`, and shape will be 0D: []

**Comment by zhouwei25** [comment]
> Yes, you can just change `SumRawInfermeta` to {}, just remove `push_back(1)`, and shape will be 0D: []

当前判断是否支持标准为：基于0D Tensor的用法，覆盖测试case并通过

**Comment by zhwesky2010** [comment]
![infoflow 2023-04-18 22-04-05](https://user-images.githubusercontent.com/52485244/232802299-ee4a21cd-d2dd-433b-9b6e-1504d00f1e36.png)

It's this usage,  have not list completely before. we'll change reduce out infermeta recently.
