### ISSUE TITLE
请问下increment在处理整数时候的一个问题

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#51373]
### 请提出你的问题 Please ask your question

我看的是这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/increment_cn.html
根据文档的说明，输入`x`可以是整数类型，但是`value`只能是浮点数类型。
所以我就写了下面的示例代码，期望是numpy的加法的结果，和paddle的increment函数的结果一致。

``` python
import numpy as np
import paddle

value = -1.5
for i in [-3, -1, 0, 1, 3]:
    data_input = np.array(i).astype('int32')

    data_output_np = data_input + value
    data_output_np = data_output_np.astype('int32')
    data_output_paddle = paddle.increment(paddle.to_tensor(data_input), value=-1.5)
    print(data_input)
    print(data_output_np)
    print(data_output_paddle)

```

当输入是-3的时候，numpy和paddle输出都是-4。
当输入是-1的时候，numpy和paddle输出都是-2。
当输入是0的时候，numpy和paddle输出都是-1。
当输入是1的时候，numpy和paddle输出都是0。
当输入是3的时候，numpy输出1，paddle输出2。

推测和取整或者四舍五入之类的有关系，请帮忙看下。或者可能是我对“increment本身应该怎么算”的理解有问题。

**Comment by houj04** [comment]
问题可能出在这里：当输入是int，value是float的时候，如何做类型转换？是下面的哪一种？
1、value先cast成int，然后都按int算。
2、输入先cast成float，和value计算，算完了再把结果cast回int。

**Comment by zhaoyinglia** [comment]
你好。查看了源码。这里确实会将 value cast 成 int，然后按照 int 计算。https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/impl/increment_kernel_impl.h#L34
