### ISSUE TITLE
 error: 'isnan' was not declared in this scope && 'isinf' was not declared in this scope

### ISSUE THREAD

**Issue by lichangW** [PaddlePaddle/Paddle#51371]
### bug描述 Describe the Bug

Hi I compile paddle from source(release/2.4), with gcc 5.4, cmake18.04,  it reports below error, I realize that others has also reported the same problem, but it seems not be sloved? thanks for help :

![image](https://user-images.githubusercontent.com/9452272/223677278-e67dd4b6-d581-4feb-a684-864f337177a3.png)

**Comment by zhaoyinglia** [comment]
你好。需要换一下gcc版本。使用gcc82编译

**Comment by jizhu1023** [comment]
我遇到了同样的问题，我在compare_functors.h，elementwise_functor.h做了以下改动解决了该问题：
将 #include <math.h> 换成 cmath
将 isnan换成std:isnan, 将isinf换成std::isinf
