### ISSUE TITLE
hub命令无法使用

### ISSUE THREAD

**Issue by LegendWang** [PaddlePaddle/Paddle#51370]
### 请提出你的问题 Please ask your question

下载完conda,paddlepaddle ,paddlehub后，在conda环境中用hub命令为什么是非法指令？我的系统是CentOS7  x86_64
![image](https://user-images.githubusercontent.com/52845411/223676344-2c553767-1fbe-4d16-9b0e-c9aa54d128e4.png)

**Comment by rainyfly** [comment]
你好，如果用python， import paddlehub 可以正常import进来吗

**Comment by LegendWang** [comment]
> 你好，如果用python， import paddlehub 可以正常import进来吗

不可以，也是非法指令

**Comment by rainyfly** [comment]
你好，我怀疑不是paddlehub的问题，是paddle的问题，https://blog.csdn.net/clever_wr/article/details/89057427 ，这是我找到的一个blog，你可以试一下import paddle, 是不是也会出现这个报错信息。根据那篇文章的建议，可能需要下载no avx的paddle版本

**Comment by LegendWang** [comment]
> 你好，我怀疑不是paddlehub的问题，是paddle的问题，https://blog.csdn.net/clever_wr/article/details/89057427 ，这是我找到的一个blog，你可以试一下import paddle, 是不是也会出现这个报错信息。根据那篇文章的建议，可能需要下载no avx的paddle版本

666,就是cpu没用avx指令，下载noave的安装包就好了！https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
