### ISSUE TITLE
分布式数据并行下模型不运行重写的forward方法

### ISSUE THREAD

**Issue by tangpanyu** [PaddlePaddle/Paddle#51398]
### 请提出你的问题 Please ask your question

训练代码
`import models
from models.l_r import WarmupCosineLR
from datasets.Cifar10 import get_dataloader,get_cifar10_dataset
from parameters import parse_option
from pretrain import mae_vit_b_p16_dec512d8b
import paddle
from visulize import visualize,get_random_img
from paddle.distributed import fleet
from paddle.io import DataLoader,DistributedBatchSampler

paddle.set_device('gpu')
fleet.init(is_collective=True)
args = parse_option()
pt_model = mae_vit_b_p16_dec512d8b(img_size=args.IMAGE_SIZE, patch_size=args.PATCH_SIZE)
pt_model = fleet.distributed_model(pt_model)
train_dataset,train_sampler = get_cifar10_dataset(mode='train')
train_loader = DataLoader(train_dataset, batch_sampler=train_sampler, num_workers=2)
# train_dataloader = get_dataloader(train_dataset, mode='train', batch_size=args.BATCH_SIZE)
val_dataset,val_sampler = get_cifar10_dataset(mode='val')
valid_loader = DataLoader(val_dataset, batch_sampler=val_sampler, num_workers=2)

lr_schedule = WarmupCosineLR(
    learning_rate=args.BLR,
    warmup_start_lr=args.WARMUP_START_LR,
    end_lr=args.END_LR,
    warmup_epochs=args.WARMUP_EPOCHS,
    total_epochs=args.TOTAL_EPOCHS
)
opt = paddle.optimizer.AdamW(learning_rate=lr_schedule,
                             beta1=0.9,
                             beta2=0.95,
                             parameters=pt_model.parameters(),
                             weight_decay=args.WEIGHT_DECAY)

opt = fleet.distributed_optimizer(opt)
for epoch in range(1, args.TOTAL_EPOCHS + 1):
    pt_model.train()
    print(f'===> [start train] epoch: {epoch}, lr: {opt.get_lr():.6f}')
    for b_id, b_data in enumerate(train_loader):
        imgs = b_data[0]
        # labels = b_data[1]  # mae pretrain 是无监督，不需要标签

        loss, _, _ = pt_model(imgs, mask_ratio=args.MASK_RATIO)

        loss.backward()
        opt.step()
        opt.clear_grad()

        if b_id % 25 == 0:
            print(f"- batch_id: {b_id}, loss: {loss.item():.4f}")

    lr_schedule.step()

    print(' ')

    # visualize
    print(f'===> [get visualize] epoch: {epoch}')
    img, label = get_random_img(val_dataset)
    visualize(img, pt_model)

    print(' ')

    #  save model
    paddle.save(pt_model.state_dict(), "mae_pt_vit_b.pdparams")`

报错信息
`D:\Anaconda3\envs\paddle\python.exe E:\pythonProject\MAE_C\main_pretrain.py 
2023-03-09 10:24:04,806-INFO: [topology.py:169:__init__] HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 1, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0], check/clip group: [0]
W0309 10:24:04.936769 15596 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.7, Runtime API Version: 10.2
W0309 10:24:05.516182 15596 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
E:\pythonProject\MAE_C\models\embedding_p.py:26: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  grid_h = np.arange(grid_size,dtype = np.float)
E:\pythonProject\MAE_C\models\embedding_p.py:27: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  grid_w = np.arange(grid_size,dtype = np.float)
E:\pythonProject\MAE_C\models\embedding_p.py:5: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  omega = np.arange(embed_dim//2,dtype=np.float)
D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\reader.py:484: UserWarning: DataLoader with multi-process mode is not supported on MacOs and Windows currently. Please use signle-process mode with num_workers = 0 instead
  warnings.warn(
===> [start train] epoch: 1, lr: 0.000001
Traceback (most recent call last):
  File "E:\pythonProject\MAE_C\main_pretrain.py", line 44, in <module>
    loss, _, _ = pt_model(imgs, mask_ratio=args.MASK_RATIO)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "E:\pythonProject\MAE_C\pretrain.py", line 234, in forward
    latent, mask, ids_restore = self.forward_encoder(imgs, mask_ratio)
  File "E:\pythonProject\MAE_C\pretrain.py", line 182, in forward_encoder
    x = blk(x)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "D:\Anaconda3\envs\paddle\lib\site-packages\paddle\fluid\dygraph\layers.py", line 941, in forward
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1
`

**Comment by tangpanyu** [comment]
搞错了，我的，有一个forward没缩进。

**Comment by yeliang2258** [comment]
所以还有问题吗
