### ISSUE TITLE
quick start的summary中Configuration file name对于Word embedding 有误

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#514]
quick start的summary中Configuration file name对于Word embedding 有误

![image](https://cloud.githubusercontent.com/assets/12882811/20388797/83b0efcc-ad01-11e6-8eea-5383c1b00623.png)

根据代码中中的配置，需要修改为trainer_config.emb.py

**Comment by qingqing01** [comment]
感谢您提出，我们修正下。

**Comment by luotao1** [comment]
#597 fix it
