### ISSUE TITLE
推理库更新

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/Paddle#51403]
### 请提出你的问题 Please ask your question

https://www.paddlepaddle.org.cn/inference/v2.4/guides/install/download_lib.html#c  计划更新Orin系列及jetpack5.1下载吗

**Comment by yeliang2258** [comment]
你好，2.5rc的时候会发布jetpack5.2

**Comment by ShawnXsw** [comment]
> 你好，2.5rc的时候会发布jetpack5.2

@yeliang2258  方便透露大概时间计划吗
