### ISSUE TITLE
paddleinference 多次运行 predictor.run() 出现内存溢出

### ISSUE THREAD

**Issue by robinraicy2018** [PaddlePaddle/Paddle#51442]
### bug描述 Describe the Bug

代码如下，跑到是一个推理任务，里面加入了循环推理，问题是循环时出现内存溢出，如图所示。

from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType
import numpy as np
import argparse
import cv2
from PIL import Image, ImageDraw
import time

def resize(img, target_size):
    """resize to target size"""
    if not isinstance(img, np.ndarray):
        raise TypeError('image type is not numpy.')
    im_shape = img.shape
    im_size_min = np.min(im_shape[0:2])
    im_size_max = np.max(im_shape[0:2])
    im_scale_x = float(target_size) / float(im_shape[1])
    im_scale_y = float(target_size) / float(im_shape[0])
    img = cv2.resize(img, None, None, fx=im_scale_x, fy=im_scale_y)
    return img

def normalize(img, mean, std):
    img = img / 255.0
    mean = np.array(mean)[np.newaxis, np.newaxis, :]
    std = np.array(std)[np.newaxis, np.newaxis, :]
    img -= mean
    img /= std
    return img

def preprocess(img, img_size):
    mean = [0.485, 0.456, 0.406]
    std = [0.229, 0.224, 0.225]
    img = resize(img, img_size)
    img = img[:, :, ::-1].astype('float32')  # bgr -> rgb
    img = normalize(img, mean, std)
    img = img.transpose((2, 0, 1))  # hwc -> chw
    img = img[np.newaxis, :]
    return img

  model_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdmodel"
  params_file = "/home/ais/paddlepaddle/output_inference/faster_rcnn_r101_fpn_2x_coco/model.pdiparams"
  use_gpu = True
  img_name = '/home/ais/paddlepaddle/100779044401373698337769799539456113481.jpg'
  im_size = 512
  img = cv2.imread(img_name)
  data = preprocess(img, im_size)
  scale_factor = np.array([im_size * 1. / img.shape[0], im_size * 1. / img.shape[1]]).reshape((1, 2)).astype(np.float32)
  im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)
  config = Config(model_file, params_file)
  config.enable_memory_optim()
  config.enable_use_gpu(3000, 0)
  predictor = create_predictor(config)
  img = [im_shape, data, scale_factor]
  input_names = predictor.get_input_names()
  for i, name in enumerate(input_names):
      input_tensor = predictor.get_input_handle(name)
      input_tensor.reshape(img[i].shape)
      input_tensor.copy_from_cpu(img[i].copy())
  for i in range(500):
      predictor.run()
      results = []
      output_names = predictor.get_output_names()
      for i, name in enumerate(output_names):
          output_tensor = predictor.get_output_handle(name)
          output_data = output_tensor.copy_to_cpu()
          results.append(output_data)
      print('results ',time.time(),results)

![微信图片_20230309204556](https://user-images.githubusercontent.com/127073006/224029585-3ac96fb6-4ba8-4e7f-b869-09994c0ed284.jpg)
![微信图片_202303092045561](https://user-images.githubusercontent.com/127073006/224029602-db1dd63d-5c1d-4c06-a179-fc214c400cce.jpg)
![微信图片_20230309204557](https://user-images.githubusercontent.com/127073006/224029594-0ad5d42a-d3bd-4605-8802-f2f862512e68.jpg)
![微信图片_20230309204558](https://user-images.githubusercontent.com/127073006/224029599-e83d4217-40e5-4e4a-a36d-752298343022.jpg)

**Comment by yeliang2258** [comment]
你只运行下面代码，看看会有溢出吗？
for i in range(500):
     predictor.run()

**Comment by robinraicy2018** [comment]
会溢出

**Comment by robinraicy2018** [comment]
这个没人遇到过吗？还是用的另外的代码，还请大神们给点建议

**Comment by n0099** [comment]
有没有用mkldnn？有的话试试
https://github.com/PaddlePaddle/Paddle/issues/25506
https://github.com/PaddlePaddle/PaddleOCR/issues/429
https://github.com/PaddlePaddle/Paddle/issues/27252
