### ISSUE TITLE
nccl_op_test failed on Hopper

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#51454]
### bug描述 Describe the Bug

In our CI tests, nccl_op_test can pass on A100, but failed on H100.

For example, I run the UT on 2xH100 GPU for 4 times, only one passed.
```
Input tensor:
    Thread 0: [42, 42, 42, 42, 42, 42, 42, 42]
    Thread 1: [43, 43, 43, 43, 43, 43, 43, 43]
Expected results after allreduce:  
    [85, 85, 85, 85, 85, 85, 85, 85]
Actual results after allreduce:  
    Run1: [0, 0, 0, 0, 0, 0, 0, 0]             Fail
    Run2: [85, 85, 85, 85, 0, 0, 0, 0]         Fail
    Run3: [85, 85, 0, 0, 0, 0, 85, 85]         Fail
    Run4: [85, 85, 85, 85, 85, 85, 85, 85]     Pass
```

I found that the [stream](https://github.com/PaddlePaddle/Paddle/blob/f3448977f30be15ac75f38f27bed426efca1923d/paddle/fluid/operators/nccl/nccl_op.cu.cc#L83) where the allreduce op runs is different from the [stream](https://github.com/PaddlePaddle/Paddle/blob/f3448977f30be15ac75f38f27bed426efca1923d/paddle/fluid/operators/nccl/nccl_op_test.cu.cc#L194) used for synchronization, which causes the allreduce op to not be synchronized, so the results copied back to CPU are wrong.

Print pointer address of the two CUDA streams:
![image](https://user-images.githubusercontent.com/21985950/224091704-5f05242f-947c-4fc9-bf24-6c93ac696803.png)

Adding an extra cudaDeviceSynchronize() or cudaStreamSynchronize() after allreduce op can make it pass. But I can't find a way to get the correct stream outside NCCLAllReduceKernel::Compute. So I have to use cudaDeviceSynchronize after [Op->Run](https://github.com/PaddlePaddle/Paddle/blob/f3448977f30be15ac75f38f27bed426efca1923d/paddle/fluid/operators/nccl/nccl_op_test.cu.cc#L132)
I think this design is very strange, why create a new stream for the allreduce op instead of using the same stream as the memcpyAsync?

**Comment by Wong4j** [comment]
对于op = OpRegistry::CreateOp(op_desc)创建出来的op，似乎没有办法获取这个op运行的device_context？
能否给OperatorBase或者OperatorWithKernel添加一个成员变量DeviceContext* dev_ctx。这样就可以用op->dev_ctx->Wait()来同步这个op

**Comment by Caozhou1995** [comment]
您好，感谢您的反馈，目前该nccl_op已维护不足，如果想要完成allreduce操作，建议您直接使用这个all_reduce op：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/all_reduce_cn.html#all-reduce。
