### ISSUE TITLE
PaddlePaddle可以在麒麟v5上安装吗

### ISSUE THREAD

**Issue by hujimei** [PaddlePaddle/Paddle#51471]
### 请提出你的问题 Please ask your question

PaddlePaddle可以在麒麟v5上安装吗？如果可以，有相关教程可以参考吗？

**Comment by Caozhou1995** [comment]
您好，您可以参考官方安装教程尝试一下安装：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html

**Comment by Caozhou1995** [comment]
理论上只要满足GCC等版本就能安装，建议您在V5里面装DOCKER，然后跑标准的飞桨镜像，更多参考：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/compile/linux-compile.html，该链接里有麒麟 V10的安装教程供参考

**Comment by hujimei** [comment]
> 理论上只要满足GCC等版本就能安装，建议您在V5里面安装DOCKER，然后跑标准的飞碟镜像，更多参考：[https://www.paddlepaddle.org.cn/install/other?docurl=/ documentation/docs/zh/install/compile/linux-compile.html，该链接里有麒麟](https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/compile/linux-compile.html%EF%BC%8C%E8%AF%A5%E9%93%BE%E6%8E%A5%E9%87%8C%E6%9C%89%E9%BA%92%E9%BA%9F)V10的安装教程供参考

V5 版本的和V10 版本的安装环境是一样的吗？也就是说，我按照V10的流程来安装是没问题的吗？

**Comment by Caozhou1995** [comment]
可以参考V10流程或者DOCKER里跑标准飞桨镜像
