### ISSUE TITLE
cannot import name 'save_persistables' from 'paddle.fluid.io'

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#51477]
### bug描述 Describe the Bug

cannot import name 'save_persistables' from 'paddle.fluid.io'

![image](https://user-images.githubusercontent.com/47998305/224250680-d56923af-992e-4e46-9661-8f8aacd57b14.png)

**Comment by Caozhou1995** [comment]
麻烦提供一下更多的环境信息，如paddle版本，python版本，硬件信息等

**Comment by dingjiaweiww** [comment]
fluid 下面的API 即将废弃了，可以使用最新版本的paddle
