### ISSUE TITLE
Add RNN backward InferShape

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5147]
Background:
- Every Op should have a backward infer shape because `backward.cc` needs it.
- For an `OperatorWithKernel`, its backward infer shape is usually auto-generated.
- RnnOp is derived from `Operator` rather than `OperatorWithKernel`, because RnnOp doesn't do the computation but serve as a wrapper to a list of `OperatorWithKernel`.

Then how does RNN do infer shape?
- In the forward pass, it is handled at python API
- In the backward pass, we need to write one.

**Comment by typhoonzero** [comment]
I think this is done by https://github.com/PaddlePaddle/Paddle/pull/5224, closing this issue, feel free to reopen it.
