### ISSUE TITLE
训练的模型无法进行eval

### ISSUE THREAD

**Issue by blurmemo** [PaddlePaddle/Paddle#51485]
### bug描述 Describe the Bug

输入eval指令后，卡在[03/10 16:32:42] ppdet.engine INFO: Eval iter: 0这里然后就挂掉了

报错信息
E:\soft\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
E:\soft\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
E:\soft\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
E:\soft\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
Warning: Unable to use numba in PP-Tracking, please install numba, for example(python3.7): `pip install numba==0.56.4`
W0310 16:32:37.948554 16696 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.6
W0310 16:32:38.187937 16696 gpu_resources.cc:91] device: 0, cuDNN Version: 8.4.
loading annotations into memory...
Done (t=0.07s)
creating index...
index created!
[03/10 16:32:39] ppdet.data.source.coco INFO: Load [310 samples valid, 0 samples invalid] in file dataset/blind\annotations/instance_val.json.
[03/10 16:32:39] ppdet.utils.checkpoint INFO: Finish loading model weights: checkpoints/67.pdparams
[03/10 16:32:42] ppdet.engine INFO: Eval iter: 0

### 其他补充信息 Additional Supplementary Information

环境信息
paddlepaddle-gpu     2.4.2.post116
cuda 11.6
cudnn 8.4.0.27

eval命令
python tools/eval.py -c configs/solov2/solov2_r50_enhance_coco_blind.yml -o weights=checkpoints/67.pdparams

**Comment by Caozhou1995** [comment]
需要您提供一下详细的信息，包括环境信息（paddle版本，python版本，硬件信息）和代码信息（如果是套件，提供下套件版本和跑的模型）

**Comment by nemonameless** [comment]
请前往 https://github.com/PaddlePaddle/PaddleDetection/issues 提问。
先保持原代码不改动，eval对应模型的原始coco配置文件和权重，以确保环境和原代码无误，然后再排查你的代码改动是否引起问题，一步步来。

**Comment by blurmemo** [comment]
> 请前往 https://github.com/PaddlePaddle/PaddleDetection/issues 提问。 先保持原代码不改动，eval对应模型的原始coco配置文件和权重，以确保环境和原代码无误，然后再排查你的代码改动是否引起问题，一步步来。

已经提交

**Comment by blurmemo** [comment]
> 需要您提供一下详细的信息，包括环境信息（paddle版本，python版本，硬件信息）和代码信息（如果是套件，提供下套件版本和跑的模型）

转到paddleDetection进行提交issue
