### ISSUE TITLE
官网首页页面和浏览器适配差

### ISSUE THREAD

**Issue by BeyondYourself** [PaddlePaddle/Paddle#51489]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html
在这个链接中，谷歌或者火狐浏览器都显示页面不全，页面有种放大的效果，电脑屏幕14寸，分辨率用的默认的，以前都正常，最近突然飞桨主页显示适配不正常，其他网站都正常。
出现的问题如下图所示，左右过于靠近页面边界。
![image](https://user-images.githubusercontent.com/12640462/224270538-84e7dfdd-dd42-4601-a781-4e3b3d453c2b.png)

**Comment by Caozhou1995** [comment]
收到，已反馈给相关人员
