### ISSUE TITLE
Paddle能否加载tensorflow训练出来的模型？

### ISSUE THREAD

**Issue by QingshuChen** [PaddlePaddle/Paddle#5150]
我们用TensorFlow训练出了一个模型，能否用Paddle的C-API进行预测服务？有什么相关文档吗？

**Comment by gongweibao** [comment]
现在还不支持

**Comment by lcy-seso** [comment]
首先，不是所有层都可以成功互转，目前有同学在做。

如果想快速试试，可以参考这个项目 https://github.com/ysh329/deep-learning-model-convertor ，TF转caffe，caffe转PaddlePaddle（https://github.com/PaddlePaddle/models/tree/develop/image_classification/caffe2paddle）。

**Comment by yeyupiaoling** [comment]
比如图像分类就有支持了:[https://github.com/PaddlePaddle/models/tree/develop/image_classification/tf2paddle](https://github.com/PaddlePaddle/models/tree/develop/image_classification/tf2paddle)
