### ISSUE TITLE
AI studio模型评估

### ISSUE THREAD

**Issue by wangqiong1981** [PaddlePaddle/Paddle#51518]
### 请提出你的问题 Please ask your question

请问一下，在AI Studio中用model.fit自动保存了训练好的模型后，然后退出了项目，等下次再进项目的时候，用model.load加载上次训练的模型参数到网络中，用model.evaluate进行评估，结果效果很差，如果训练之后不退出项目，直接进行评估，结果就很好。请问这是为什么呢？如果我想进项目后直接用上次保存的参数来进行评估要怎么做才行？

**Comment by shiyutang** [comment]
请提供下项目id方便排查。

**Comment by shiyutang** [comment]
AI Studio 项目中的内容，如果没有存放在持久化目录或没有存放在已有的文件目录中，是不会被持久化保存的，这里应该是没有指定存放路径，导致文件存在了临时的存放目录下， 建议存放在当前目录中的任意文件夹下，如home/aistudio/work/model_save
