### ISSUE TITLE
导入parl库的时候出现问题

### ISSUE THREAD

**Issue by yilongfengshen** [PaddlePaddle/Paddle#51515]
### 请提出你的问题 Please ask your question

![CPH4P9~0D1GW3`@677P917E](https://user-images.githubusercontent.com/105027125/224518561-90f68926-0f69-4d2b-921e-c5b48d7a8221.png)
无法导入parl库，会出现AttributeError: Can't pickle local object 'check_installed_framework.<locals>.check'的错误，不知道如何解决。

**Comment by shiyutang** [comment]
你好，看到你已经在PARL套件库下提交问题，并已经有相关同学跟进，如果有其他paddle相关问题，欢迎重新提交issue。
