### ISSUE TITLE
paddle BML上传文件总是卡住

### ISSUE THREAD

**Issue by yizhiyangou** [PaddlePaddle/Paddle#51526]
### bug描述 Describe the Bug

我在上传数据集的时候，前面的都正常，从54999到64999的过程中，总是在传了2000多的时候卡住了；提供截图：
![image](https://user-images.githubusercontent.com/107088741/224528951-33c01554-bd88-4efc-abf4-b80ebb159a03.png)
就是这样，我以为是网卡了，试了好几次都不行，是不是文件有数量上限？但是这个数字也太零碎了

**Comment by shiyutang** [comment]
请尝试进行数据进一步拆分，查看是否能上传成功。

**Comment by shiyutang** [comment]
你好，更好的上传数据集的方式建议使用在项目中添加并挂载相应的数据集，挂载数据集上传zip压缩包即可。
![5f8bf7b60e6889f828d9bdf508881ebe](https://user-images.githubusercontent.com/34859558/224595454-7907aa8d-a067-491c-a554-ffc61883fb4d.jpg)
