### ISSUE TITLE
在book如何写一个接口给其他人访问

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#5152]
在“数字识别”这章中，我想做一个接口给别人上传图片，然后返回识别结果，这样怎么做？
```python
#添加要识别数据
test_data = []
for k in range(9):
    test_data.append((load_image(cur_dir + '/image/test_%s.png' % str(k+1)),))

#获取识别结果
probs = paddle.infer(
    output_layer=predict, parameters=parameters1, input=test_data)
lab = np.argsort(-probs)

#打印识别结果
for i in range(len(test_data)):
    print "Label of image/test_%s.png is: %d" % (i+1, lab[i][0])```

**Comment by llxxxll** [comment]
接口服务也打算用python实现吗？
可能你需要先搭建一个python的web服务，在服务内获取用户上传的图片路径，然后将路径替换至
```python
load_image(cur_dir + '/image/test_%s.png' % str(k+1)),
```
中image的路径即可

**Comment by yeyupiaoling** [comment]
@llxxxll 是想用Python实现，book都可以当做网站来访问，我估计可以直接在上面写接口，还有新搭建的Python搭建的网络服务，会不会关联不了paddlepaddle

**Comment by llxxxll** [comment]
我在Flask上尝试过`import paddle.v2`，是没问题的。如果能在notebook上实现，将是一次非常棒的尝试！

**Comment by yeyupiaoling** [comment]
@llxxxll 你有没有写教程这样的博客，我不知道是不是在book容器上建立Python网站服务

**Comment by llxxxll** [comment]
我周末会尝试一下，有结果会分享给你。

**Comment by yeyupiaoling** [comment]
@llxxxll 非常感谢

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/book/blob/develop/serve/main.py

**Comment by yeyupiaoling** [comment]
@gongweibao 里面缺少包，`from flask import Flask, jsonify, request`

**Comment by yeyupiaoling** [comment]
@gongweibao 能教我如何在paddlepaddle容器中运行一个web服务吗，helloworld就好

**Comment by gongweibao** [comment]
google之 @yeyupiaoling
