### ISSUE TITLE
pool2d在ceil_mode=True情况下，某些特定case计算存在bug。

### ISSUE THREAD

**Issue by gqzhang-ai** [PaddlePaddle/Paddle#51542]
### bug描述 Describe the Bug

avg_pool2d在input_size=[1, 1, 6, 7], ksize=1, stride=2, padding=0, exclusive=True, ceil_mode = True下计算错误。
可复现bug代码：
`import paddle

paddle.device.set_device("cpu")
input = paddle.uniform([1, 1, 6, 7], dtype="float32", min=-1, max=1)
AvgPool2D = paddle.nn.AvgPool2D(kernel_size=1, stride=2, padding=0, exclusive=True,ceil_mode = True)
output = AvgPool2D(input)
print(output)`

paddle-cpu计算结果：
![图片](https://user-images.githubusercontent.com/75768741/224599499-8f3d6e1d-c043-4370-99ac-9a5944ce96f4.png)
我希望得到的output_size应为[1, 1, 3, 4]。

### 其他补充信息 Additional Supplementary Information

查看了paddle框架代码后，怀疑是PoolInferMeta()中PoolOutputSize()计算存在bug。
![图片](https://user-images.githubusercontent.com/75768741/224598987-67cca76e-7360-452b-a1ad-fceda12859e2.png)

**Comment by weisy11** [comment]
是的，这是一个错误。
不过使用pooling相关的api的用户非常多，我们也进行了简单的评估，如果修复这个问题会使大量模型受到影响，所以短期可能暂时无法修复。您可以在pooling之后手动转换一下模型的维度，去掉多余的部分，来暂时解决这个问题。
