### ISSUE TITLE
Paddle外发头文件包含fluid依赖导致编译错误

### ISSUE THREAD

**Issue by zhaohaixu** [PaddlePaddle/Paddle#51550]
官网下载develop（Nightly build）Linux CPU pip包安装后发现 paddle wheel包安装路径下trace_event.h包含fluid头文件(未对外发布)，导致在插件接入开发时无法编译。（python3.8/site-packages/paddle/include/paddle/phi/backends/custom/trace_event.h）
![image](https://user-images.githubusercontent.com/49297029/224616737-87b4a18c-2f1d-4451-a2dc-2b1f296e3072.png)
![image](https://user-images.githubusercontent.com/49297029/224617235-bc6bff7d-d198-4463-8d33-7577f5c9fbc4.png)
另外之前使用的头文件看上去为：Paddle\paddle\phi\api\profiler\trace_event.h，不知为何换成了目前这个。
期望提供外部可使用的修复。

**Comment by YuanRisheng** [comment]
麻烦提供一下问题的具体复现方式，我们复现后解决一下

**Comment by tiandou-tangdou** [comment]
> 麻烦提供一下问题的具体复现方式，我们复现后解决一下

@YuanRisheng hi, 辛苦查看CPU版本安装的路径下的 python3.8/site-packages/paddle/include/paddle/phi/backends/custom/trace_event.h 其头文件中包含了未外发的fluid文件，CustomDevice方式接入仅依赖paddle的wheel包和发布的头文件编译，所以找不到这个文件编译报错：
![image](https://user-images.githubusercontent.com/127805199/224864266-bb5f12b4-3a4d-4a3f-9466-77392d32dd06.png)

我理解是否改成发布phi下的这个头文件就可以了：Paddle\paddle\phi\api\profiler\trace_event.h
不知为何改成了带fluid头文件的这个版本了。

相关PR：https://github.com/PaddlePaddle/Paddle/pull/50183/files 原本发布的头文件：https://github.com/PaddlePaddle/Paddle/issues/45130

**Comment by YuanRisheng** [comment]
> > 麻烦提供一下问题的具体复现方式，我们复现后解决一下
> 
> @YuanRisheng hi, 辛苦查看CPU版本安装的路径下的 python3.8/site-packages/paddle/include/paddle/phi/backends/custom/trace_event.h 其头文件中包含了未外发的fluid文件，CustomDevice方式接入仅依赖paddle的wheel包和发布的头文件编译，所以找不到这个文件编译报错： ![image](https://user-images.githubusercontent.com/127805199/224864266-bb5f12b4-3a4d-4a3f-9466-77392d32dd06.png)
> 
> 我理解是否改成发布phi下的这个头文件就可以了：Paddle\paddle\phi\api\profiler\trace_event.h 不知为何改成了带fluid头文件的这个版本了。
> 
> 相关PR：https://github.com/PaddlePaddle/Paddle/pull/50183/files 原本发布的头文件：#45130

这个我再看看，按理说改成这个Paddle\paddle\phi\api\profiler\trace_event.h就可以，但是我需要复现问题以方便找原因

**Comment by YuanRisheng** [comment]
已提交修复PR:https://github.com/PaddlePaddle/Paddle/pull/51511
