### ISSUE TITLE
paddle.distributed.launch训练多个模型时候，两个控制台打印的一样，该怎么区分开

### ISSUE THREAD

**Issue by northeastsquare** [PaddlePaddle/Paddle#51599]
### 请提出你的问题 Please ask your question

python -m paddle.distributed.launch的时候，同一台机器，我训练了一个检测任务，一个分类任务，结果两个控制台打印的是一样的，把两个任务在两个控制台都打印了，是怎么回事

**Comment by veyron95** [comment]
请提供最小复现代码，方便复现问题。
理论上，不同的控制台分别执行不同的任务，是不会出现打印信息一致的，请检查下是否执行两个同样的命令。

**Comment by wuhuachaocoding** [comment]
你好， python -m paddle.distributed.launch是跑一个模型的分布式训练，就是代码相同，用多个进程跑同一份代码，相对于单卡，不同进程多了通信。辛苦把你的需求进一步描述一下。
