### ISSUE TITLE
paddleseg训练时出现 "When training, we now always track global mean and variance."之后就退出训练了

### ISSUE THREAD

**Issue by loxoo6** [PaddlePaddle/Paddle#51642]
### 请提出你的问题 Please ask your question

![599bf8d5bfdc468bb9a54993f5c5c5b](https://user-images.githubusercontent.com/119844692/224976738-620a4847-77de-4990-af89-08a99951d19b.png)

**Comment by 0x45f** [comment]
你好，这个warning不会导致程序退出，只是输出了一段日志。应该是程序代码问题导致的，可以打断点调试一下找到具体报错的代码行。
