### ISSUE TITLE
0.10.0的noavx的 docker 镜像无法下载

### ISSUE THREAD

**Issue by fat32jin** [PaddlePaddle/Paddle#5166]
docker pull docker.paddlepaddle.org/paddle:0.10.0-noavx  报错 
Error: image paddle:0.10.0-noavx not found

但是0.10.0rc3-noavx  可以下  ， 但是这个版本很多是老函数

如果强制用 0.10.0 的 ，报错 18521 Illegal instruction (core dumped)

请问要如何解决？我是按照文档一步步来的 ，文档说0.10.0 以后自动识别avx
可是在我这不行 呢，我用虚拟机的centos7  
cpu 信息如下
vendor_id	: AuthenticAMD
cpu family	: 16
model		: 5
model name	: AMD Athlon(tm) II X4 640 Processor
stepping	: 3
microcode	: 0x10000c8
cpu MHz		: 3013.329
cache size	: 512 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 5
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt rdtscp lm 3dnowext 3dnow constant_tsc rep_good nopl tsc_reliable nonstop_tsc pni cx16 popcnt hypervisor lahf_lm extapic abm sse4a misalignsse 3dnowprefetch osvw
bogomips	: 6026.65
TLB size	: 1024 4K pages
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual

**Comment by llxxxll** [comment]
https://hub.docker.com/r/paddlepaddle/paddle/tags/
官方镜像里好像没有这个版本

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
