### ISSUE TITLE
infer_shape似乎有问题

### ISSUE THREAD

**Issue by 2020zyc** [PaddlePaddle/Paddle#51675]
### bug描述 Describe the Bug

paddle2.4.1

shufflenet动态模型方式加载pdparams后，使用paddle.jit.to_static转成静态并设置input_spec为[-1,3,224,224]，保存，得到网络结果如下图：
![image](https://user-images.githubusercontent.com/7539692/225184785-5e17bfdd-0a10-449b-90a7-46329368ebff.png)
![image](https://user-images.githubusercontent.com/7539692/225184353-f911fd06-de87-47cf-8123-c8b2a0cfbdb5.png)

重新用paddle.jit.load加载后，想更改input_shape为[8,3,224,224]并更新整个模型的shape；
利用以下代码段更改，
![image](https://user-images.githubusercontent.com/7539692/225183825-9ac2be0c-c0e6-4bef-9e96-ad82eec4ba94.png)

发现模型shape前面小部分更改，后面大部分无法更改，
![image](https://user-images.githubusercontent.com/7539692/225184118-f41df1c1-f204-4821-875d-7d888bb3c08c.png)

**Comment by zmxdream** [comment]
你好，可以到PaddleClas套件库提issue, https://github.com/PaddlePaddle/PaddleClas

**Comment by Aurelius84** [comment]
batch_size维度指定为-1后，已经支持动态的改变batch_size了，想问下为什么要显示指定8再导出一遍呢？
