### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.jit.dy2static.utils'

### ISSUE THREAD

**Issue by superwinner1** [PaddlePaddle/Paddle#51674]
### 请提出你的问题 Please ask your question

测试时的问题：
Traceback (most recent call last):
  File "test_erf_op.py", line 18, in <module>
    from eager_op_test import OpTest
  File "/home/Paddle/python/paddle/fluid/tests/unittests/eager_op_test.py", line 42, in <module>
    from prim_op_test import OpTestUtils, PrimForwardChecker, PrimGradChecker
  File "/home/Paddle/python/paddle/fluid/tests/unittests/prim_op_test.py", line 25, in <module>
    from paddle.jit.dy2static.utils import parse_arg_and_kwargs
ModuleNotFoundError: No module named 'paddle.jit.dy2static.utils'
这个模块在paddlepaddle2.4.2已经弃用了吗，import optest一直没通过

**Comment by zmxdream** [comment]
你好，最新Paddle develop分支代码有这个模块，目前看最新的release版本是2.4.1

**Comment by superwinner1** [comment]
你好，我已经在自己的conda虚拟环境中安装了paddlepaddle-gpu=2.4.1，可是我运行程序后它依然会出现相同的错误。我之前安装的paddlepaddle-gpu版本为2.4.2，错误和现在一致。
![屏幕截图 2023-03-17 195528](https://user-images.githubusercontent.com/82640284/225898138-702629f1-9528-4332-85a4-0cf238715b2f.png)
![image](https://user-images.githubusercontent.com/82640284/225898392-99b34836-8fd5-4cca-9374-0756d6818cc3.png)

**Comment by superwinner1** [comment]
我还是不明白错误应该如何改正

**Comment by superwinner1** [comment]
我并未在paddle.jit.dy2static中发现utils文件
![1679054791908](https://user-images.githubusercontent.com/82640284/225900142-fd115255-6246-4801-83cf-9a39db8fd438.jpg)

**Comment by SigureMo** [comment]
> 这个模块在paddlepaddle2.4.2已经弃用了吗，import optest一直没通过

是在开发 API 是吗，那不应该使用 release 版本，应该使用你正在开发的 develop 分支（自行编译后可得到），`paddle.jit.dy2static.utils` 是 2.4 还没有的，develop 才迁移过去的，可按照[贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/code_contributing_path_cn.html) 使用 ctest 运行单测

**Comment by superwinner1** [comment]
好的，谢谢你的解答
