### ISSUE TITLE
Rename doc/howto/cross_compiling into doc/mobile ?

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5168]
Would this make the documentation structure cleaner?

**Comment by jetfuel** [comment]
Yes. It will. The Mobile README.md has references to doc/howto/cross_compiling and take the users away from Mobil. It will be ideal for the Mobile repo to update this section.

**Comment by Xreki** [comment]
I think it is a good idea, then mobile will be considered as a main feature of Paddle.
