### ISSUE TITLE
推理过程中显存增加以致于出core

### ISSUE THREAD

**Issue by gongchenting** [PaddlePaddle/Paddle#51691]
### 请提出你的问题 Please ask your question

目的：对网络输出的特征进行类中心特征计算
实现：实现了一个Store类，来存储每个类的类中心特征，在每个iter下利用该类的update函数进行类中心特征更新
问题：随着iter数增加，显存增加明显，导致程序断掉
class Store:
    def __init__(self, total_num_classes, items_per_class, shuffle=False):
        self.shuffle = shuffle
        self.items_per_class = items_per_class
        self.total_num_classes = total_num_classes
        self.store = [deque(maxlen=self.items_per_class) for _ in range(self.total_num_classes)]
        self.mean_fea = [None] * total_num_classes
        self.total_class_items_num = [0] * total_num_classes

    def update(self, cls_id, cur_vec_num, cur_mean_vec):
        if self.mean_fea[cls_id] is None:
            self.mean_fea[cls_id] = cur_mean_vec
            self.total_class_items_num[cls_id] = cur_vec_num
        else:
            self.mean_fea[cls_id] = (self.mean_fea[cls_id] + cur_mean_vec)  / 2
            self.total_class_items_num[cls_id] = self.total_class_items_num[cls_id] + cur_vec_num

主函数：其中cls_feature是一个字典，key为类id，value为当前iter通过网络获得的各类的特征

self.feature_store = Store(self.cfg.num_classes, clustering_items_per_class)
for cls_id in cls_feature:
    cur_vec_num = cls_feature[cls_id].shape[0]
    cur_mean_vec = cls_feature[cls_id].mean(axis=0)
    self.feature_store.update(cls_id, cur_vec_num, cur_mean_vec)

**Comment by zmxdream** [comment]
你好，已沟通，请具体确认是哪行代码导致显存问题
