### ISSUE TITLE
Unify Docker and Travis build.sh for Android

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5169]
We have two build scripts for Android:

1. the one we use in Dockerfile.android: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build_android.sh, and

1. the one we use with Travis-CI: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/travis/build_android.sh

To keep the simplicity and consistency of the codebase, could we merge them into one?

**Comment by Xreki** [comment]
Maybe we can add a build_android task on teamcity, then https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/travis/build_android.sh can be moved.

**Comment by Xreki** [comment]
But, teamcity seems slow for CI. #5051
