### ISSUE TITLE
paddlepaddl使用pip安装出错

### ISSUE THREAD

**Issue by zhandand** [PaddlePaddle/Paddle#51702]
### 问题描述 Issue Description

![155f8f6d9466afc292ec55be830e34af](https://user-images.githubusercontent.com/46822127/225253628-8535b341-d92f-49ab-9551-60d87b5c74d8.jpg)

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: centos 6.3
GCC version: (GCC) 4.4.6 20120305 (Red Hat 4.4.6-4)
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.2.5
Python version: 3.6.4

CUDA version: 10.2.89
cuDNN version: N/A
Nvidia driver version: 470.57.02
Nvidia driver List:
GPU 0: Tesla V100-SXM2-32GB
GPU 1: Tesla V100-SXM2-32GB
GPU 2: Tesla V100-SXM2-32GB
GPU 3: Tesla V100-SXM2-32GB
GPU 4: Tesla V100-SXM2-32GB
GPU 5: Tesla V100-SXM2-32GB
GPU 6: Tesla V100-SXM2-32GB
GPU 7: Tesla V100-SXM2-32GB

****************************************

**Comment by zhandand** [comment]
另外，可能是网络的问题吗，我wget那个.py文件的时候出错，所以直接复制内容到开发机上运行的

**Comment by zmxdream** [comment]
你好，官网推荐方式是python -m pip install paddlepaddle==2.4.2 -i https://pypi.tuna.tsinghua.edu.cn/simple， 可以去官网选择合适的安装命令 https://www.paddlepaddle.org.cn/
