### ISSUE TITLE
完成跨GPU运算后，将计算结果的张量使用cpu()进行转换产生an illegal memory access was encountered

### ISSUE THREAD

**Issue by rubbberrabbit** [PaddlePaddle/Paddle#51706]
### bug描述 Describe the Bug

import paddle
x = paddle.to_tensor([1.0, 2.0, 3.0])
y = paddle.to_tensor([1.0, 2.0, 3.0])
x = x.cuda(0)
y = y.cuda(1) # 跨GPU运算Tensor
print(x.place)
print(y.place)
z = paddle.equal_all(x,y)
print(z.element_size())
print(z.place)
z = z.cpu() # 将一个gpu：0的paddle.bool进行device的迁移和输出 非法内存访问
\# 期望情况如下
a = paddle.to_tensor(1, dtype='bool')
a = a.cuda(0)
b = a.cpu() # 此时可以将一个gpu：0的paddle.bool进行device的迁移和输出
print(b)
“”“
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0315 08:49:47.787365 22334 gpu_resources.cc:61] Please NOTE: device: 1, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
W0315 08:49:47.788669 22334 gpu_resources.cc:91] device: 1, cuDNN Version: 8.2.
Place(gpu:0)
Place(gpu:1)
1
Place(gpu:0)
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    z = z.cpu()
  File "/usr/local/lib/python3.7/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 869, in cpu
    res = self._copy_to(core.CPUPlace(), True)
OSError: (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/backends/gpu/cuda/cuda_info.cc:259)
”“”

**Comment by rubbberrabbit** [comment]
GPU为3090*2 Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.6, Runtime API Version: 11.2
使用为paddle镜像 nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0

**Comment by zyfncg** [comment]
您好，目前飞桨的算子不支持跨GPU Tensor之间的运算，所以`z = paddle.equal_all(x,y)`在执行时会有问题。

要解决这个问题可以在调用 `paddle.equal_all` 之前将 `x` 先手动拷贝到 `gpu:1` 上，确保`x`和`y`是在同一设备。

**Comment by rubbberrabbit** [comment]
您好，感谢回复 我大概了解原因了 但是z = paddle.equal_all(x,y)这一步并没有抛出错误，而是在对z进行操作后才抛出错误，可否在正确的位置抛出错误呢？

**Comment by zyfncg** [comment]
这里确实应该抛出一个更准确的错误提示信息，我们在后续版本中优化下
