### ISSUE TITLE
paddle_infer::Tensor::mutable_data缺乏custom_device的place处理

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#51720]
### bug描述 Describe the Bug

Paddle Version:  develop lastest

[zero_copy_tensor.cc](
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/inference/api/details/zero_copy_tensor.cc)

```cpp
template <typename T>
T *Tensor::data(PlaceType *place, int *size) const

template <typename T>
T *Tensor::mutable_data(PlaceType place)
```
这两个函数缺乏对custom device的place处理。
导致CustomDevice无法使用paddle_infer::Tensor::mutable_data 或 data
例如
```cpp
auto input_t = m_predictor->GetInputHandle(input_names[0]);
auto inputPtr = input_t->mutable_data<float>(paddle_infer::PlaceType::kCUSTOM);
```
会直接报出如下错误

```
Only CPU / CUDA / XPU / NPU places is supported.
```

需要补充Custom Place的实现

修复PR
https://github.com/PaddlePaddle/Paddle/pull/51710

**Comment by zmxdream** [comment]
你好，感谢对于Paddle的贡献，会尽快对PR进行review

**Comment by engineer1109** [comment]
pr 已经merge
