### ISSUE TITLE
(PreconditionNotMet) For batch [1]: U(2, 2) is zero, singular U. Please check the matrix value and change it to a non-singular matrix

### ISSUE THREAD

**Issue by aishoot** [PaddlePaddle/Paddle#51724]
### bug描述 Describe the Bug

```bash
  File "/usr/local/lib/python3.8/dist-packages/paddle/tensor/math.py", line 1117, in inverse
    return core.ops.inverse(x)
RuntimeError: (PreconditionNotMet) For batch [1]: U(2, 2) is zero, singular U. Please check the matrix value and change it to a non-singular matrix
  [Hint: Expected info[i] == 0, but received info[i]:2 != 0:0.] (at /paddle/paddle/fluid/operators/math/matrix_inverse.cu.cc:114)
  [operator < inverse > error]
```
cpu版本paddle跑没问题，gpu版一大堆问题，目前cuda 11.2，paddlepaddle-gpu 2.3.2，2.4.2等等版本试都有这个问题 ...

**Comment by From00** [comment]
根据报错提示，你用于求逆的矩阵是奇异矩阵，U(2, 2) = 0，无法求逆。请检查下输入矩阵合法性。

**Comment by aishoot** [comment]
> 根据报错提示，你用于求逆的矩阵是奇异矩阵，U(2, 2) = 0，无法求逆。请检查下输入矩阵合法性。

但是为啥cpu版的paddle没问题呢

**Comment by From00** [comment]
> 但是为啥cpu版的paddle没问题呢

CPU和GPU底层计算逻辑可能不同，但具体的原因需要分析定位。辛苦提供一个可复现的demo，我们这边测试一下。

**Comment by mechnotech** [comment]
"tps_spatial_transformer.py", line 106

#### # compute inverse matrix
inverse_kernel = paddle.inverse(forward_kernel)

forward_kernel sends filled tensor, but if debug **def inverse(x, name=None):**  x = recieved as zeros!
