### ISSUE TITLE
train_from_dataset打印Lod变量？

### ISSUE THREAD

**Issue by Adam86546853** [PaddlePaddle/Paddle#51723]
### 请提出你的问题 Please ask your question

`import paddle
import os
paddle.enable_static()

with open("test_queue_dataset_run_a.txt", "w") as f:
    data = "2 1 2 2 5 4 2 2 7 2 1 3"
    f.write(data)
with open("test_queue_dataset_run_b.txt", "w") as f:
    data = "2 1 2 2 5 4 2 2 7 2 1 3"
    f.write(data)

slots = ["slot1", "slot2", "slot3", "slot4"]
slots_vars = []
for slot in slots:
    var = paddle.static.data(
        name=slot, shape=[None, 1], dtype="int64", lod_level=1)
    slots_vars.append(var)

dataset = paddle.distributed.InMemoryDataset()
dataset.init(
    batch_size=1,
    thread_num=2,
    input_type=1,
    pipe_command="cat",
    use_var=slots_vars)
dataset.set_filelist(
    ["test_queue_dataset_run_a.txt", "test_queue_dataset_run_b.txt"])
dataset.load_into_memory()

place = paddle.CPUPlace()
exe = paddle.static.Executor(place)
startup_program = paddle.static.Program()
main_program = paddle.static.Program()
exe.run(startup_program)

exe.train_from_dataset(main_program, dataset,print_period=1,fetch_list=slots_vars,fetch_info=slots)

os.remove("./test_queue_dataset_run_a.txt")
os.remove("./test_queue_dataset_run_b.txt")`

文档上的例子，想打印看看slots_vars的取值【不是很熟悉lod_level的作用】，有哪位能帮忙解释一下么？这几行代码实在不理解咋弄得

**Comment by Adam86546853** [comment]
![image](https://user-images.githubusercontent.com/43706523/225371070-32d95e9e-1f07-430e-8332-c57322cfa008.png)

**Comment by zmxdream** [comment]
数据格式是: slot1的feasign数 feasign1 feasign2... slot2feasign数 feasign3 feasign4....
