### ISSUE TITLE
Rename "C-API" into "inference library"

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5175]
In our CMakeLists file and [documents](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/cross_compiling/cross_compiling_for_raspberry_cn.md), we use the phrase "C-API" for "inference library". Indeed, the later is more accurate and readable.

**Comment by chengduoZH** [comment]
The documents connection is empty.
