### ISSUE TITLE
CPU 环境下使用fleetrun 分布式训练，怎么提早终止多节点训练

### ISSUE THREAD

**Issue by jylong91** [PaddlePaddle/Paddle#51788]
### 请提出你的问题 Please ask your question

paddle 版本2.2.0， 多cpu训练。希望在 first_worker 达到训练终止条件时，其他节点也能够同时终止训练。

**Comment by ForFishes** [comment]
您好，这个只能在fisrtworker终止后，给其他节点发送消息的方式，使其他节点终止训练。

**Comment by jylong91** [comment]
> 您好，这个只能在fisrtworker终止后，给其他节点发送消息的方式，使其他节点终止训练。

@ForFishes 
您好，这个能提供一个样例吗？该怎么发送终止训练的消息

**Comment by ForFishes** [comment]
您好，就是每一轮都执行broadcast，将0卡的形象广播到其他卡上，其他卡判断信息，看是否需要终止计算。

```
paddle.distributed.broadcast(data, src=0)
if data == 1:
    exit()
```
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/broadcast_cn.html#broadcast
