### ISSUE TITLE
错字

### ISSUE THREAD

**Issue by zlpoot** [PaddlePaddle/Paddle#51780]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/tutorials/projectdetail/4456692#anchor-10

### 请提出你的建议 Please give your suggestion

数据增强是一种挖机数据集潜力的方法 => 数据增强是一种挖掘数据集潜力的方法

**Comment by YuanRisheng** [comment]
收到反馈，后续提交修复

**Comment by sunzhongkai588** [comment]
已修改，原链接已作废，可以直接通过官网入口查看最新文章：https://www.paddlepaddle.org.cn/tutorials/projectdetail/4906311
