### ISSUE TITLE
PR-CI-Build-ALLFramework-Compile流水线列表是失败状态

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#51813]
### bug描述 Describe the Bug

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/builds/24322?module=PaddlePaddle/Paddle&pipeline=PR-CI-Build-ALLFramework-Compile&branch=branches
PR-CI-Build-ALLFramework-Compile流水线列表是失败状态
![图片](https://user-images.githubusercontent.com/4617245/226097376-6b82b80a-2f5c-41f4-8c2c-48f9537302a4.png)

**Comment by rainyfly** [comment]
看看是哪里报错了，没问题就rerun一下试试

**Comment by co63oc** [comment]
> 看看是哪里报错了，没问题就rerun一下试试

提示/paddle/paddle/phi/kernels/gpu/cumprod_grad_kernel.cu问题，这里代码没有修改
![图片](https://user-images.githubusercontent.com/4617245/226108025-cef4be84-7cd2-4cf8-8746-b09a994064f2.png)

**Comment by SigureMo** [comment]
这条流水线目前是非 required，可以不用管
