### ISSUE TITLE
任务队列链接打开无效地址

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#51815]
### bug描述 Describe the Bug

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8030999/job/22111779
![图片](https://user-images.githubusercontent.com/4617245/226102282-c38c4974-1222-4e89-8820-10563e3d19c1.png)
效率云任务队列链接打开无效地址

**Comment by rainyfly** [comment]
可以直接看你自己的CI下面的报错信息就行
