### ISSUE TITLE
单机怎么模拟PS运行环境呢？

### ISSUE THREAD

**Issue by Adam86546853** [PaddlePaddle/Paddle#51818]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/43706523/226107542-6b379f7d-41e5-4db4-ac46-5634c600e96d.png)

看到原先有这样测试，然而paddle 2.4 测试了一下，没有这个命令python -m paddle.distributed.launch_ps ；这个命令咋没了呢？ 想单机跑下PS-dnn

**Comment by wangzhen38** [comment]
可以参考下这个，https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_ps_cn.html#dingyifenbushimoshibingchushihuafenbushixunlianhuanjing
