### ISSUE TITLE
window11的docker环境下paddle编译错误

### ISSUE THREAD

**Issue by a-strong-python** [PaddlePaddle/Paddle#51824]
### bug描述 Describe the Bug

电脑环境：windows11
docker环境：docker-desktop

这个bug是在我用docker编译paddle框架时出现的，运行的命令为 `time make -j$(nproc)` ，我是严格按照官方文档[【Linux下从源码编译】文档的【使用Docker编译】](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile.html#span-id-compile-from-docker-docker-span)进行编译的。

下面是报错信息截图
![VUCRUWV~WI{I}V7{5@VU{S0](https://user-images.githubusercontent.com/65645246/226153689-11ec1ecb-17b0-4e07-9b85-17611ab4cab3.png)

**Comment by zkh2016** [comment]
你好，从这个编译日志看"Killed signal terminated program cc1plus"像是内存不足导致编译被中断了，参考：https://blog.csdn.net/weixin_44796670/article/details/121234446

也可以调小make的线程数，不要make -j$(nproc)， 比如可以指定make  -j4

**Comment by zkh2016** [comment]
@a-strong-python 看你在https://github.com/PaddlePaddle/Paddle/issues/45347 中也提到了这个是编译消耗太多内存导致的，这个不是paddle本身的问题，另外看你在ai-studio上已经编译通过，所以关闭这个issue
