### ISSUE TITLE
安装验证时63错误

### ISSUE THREAD

**Issue by WesternTrail** [PaddlePaddle/Paddle#51822]
同样的错误，请尽快解决！！！

系统：win11
显卡：tesla_p40 
python 3.8.0
cuda：cuda 11.6.0
cudnn：cudnn 8.1.1.3
paddlepaddle：pip安装 版本：gpu==2.4.1.post116

- 使用`python -c "import paddle; conv = paddle.nn.Conv1D(3, 1, 1); ts = paddle.to_tensor([[[1.1], [4.5], [1.4]]], dtype='float32'); print(conv(ts))`验证安装时报错：

![image](https://user-images.githubusercontent.com/28615285/224469940-b8cb74ba-2863-42ef-985b-fcfec9df5cce.png)

- 使用 `python -c "import paddle;paddle.utils.run_check()"`验证安装依然如上述报错

- 使用 `python -c "import paddle.fluid as fluid;fluid.install_check.run_check()"`时正常

![image](https://user-images.githubusercontent.com/28615285/224470140-6603b44a-3cd9-43b2-a192-902597008491.png)

- 运行 `paddleRS/tutorials/train/change_detection/bit.py`时依然出现上述63错误

@zhouwei25 @LielinJiang

_Originally posted by @WesternTrail in https://github.com/PaddlePaddle/Paddle/issues/49964#issuecomment-1464845547_

**Comment by zkh2016** [comment]
你好，这个问题已经在修复，会在下个版本发布时支持。

**Comment by guotao** [comment]
> 你好，这个问题已经在修复，会在下个版本发布时支持。

可否提供临时解决方案？如果改动不大的话。

**Comment by zkh2016** [comment]
@zhouwei25 你这边有临时解决方案吗？

**Comment by zhwesky2010** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/api/lib/kernel_dispatch.cc#L80  这边有建议的改法吗，目前我们这边机器不太好复现这个问题，开源社区 欢迎向我们提PR

**Comment by guotao** [comment]
> https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/api/lib/kernel_dispatch.cc#L80 这边有建议的改法吗，目前我们这边机器不太好复现这个问题，都是支持的

@zhouwei25  我不会编译 😂，如果有需要，可以配合修改调试。

**Comment by WesternTrail** [comment]
新的反馈：安装2.3.0的老版本paddle，上述报错消失。

**Comment by zhwesky2010** [comment]
@guotao @WesternTrail 你好，该问题已修复，可以安装最新的develop版本whl包试试
`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/windows/gpu/develop.html`

**Comment by WesternTrail** [comment]
@zhwesky2010 感谢修复，可行！
