### ISSUE TITLE
【社区治理】Liyulingyue 发起 Committer 身份申请

### ISSUE THREAD

**Issue by Liyulingyue** [PaddlePaddle/Paddle#51820]
# 基本信息

| 申请人 GitHub ID | Paddle Repo 整体 merge PR 数 | Paddle Repo 整体 review PR 数 | Paddle Repo 整体报告 Issue 数|
| -- | -- | -- | -- |
| Liyulingyue | [55](https://github.com/PaddlePaddle/Paddle/pulls?page=3&q=is%3Apr+is%3Amerged+author%3ALiyulingyue) | [3](https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3ALiyulingyue+-author%3ALiyulingyue+)| [1](https://github.com/PaddlePaddle/Paddle/issues?q=is%3Aissue+author%3ALiyulingyue) |

# 社区贡献概况

以下是此前在本 repo 里做过的贡献：
- 修复部分文档错误
- 修复部分LoDTensor 带来的影响
- 修复部分除零错误、空指针错误
- 给部分算子注册参数、扩展类型

其他相关贡献：
- 推动.md文档生成工具的构建，促进pytorch2paddle API映射工作进行。

申请理由：便于在快乐开源活动中整理表单，添加和调整说明。

## 部分PR展示

| PR 号 | PR 标题 | PR 简介 | Reviewer |
| -- | -- | -- | -- |
| https://github.com/PaddlePaddle/Paddle/pull/46165 | Fix the En docs (delete some expression like 'This OP') | 调整英文介绍的表达 | Ligoml XiaoguangHu01 |
| https://github.com/PaddlePaddle/Paddle/pull/46165 https://github.com/PaddlePaddle/Paddle/pull/48417 https://github.com/PaddlePaddle/Paddle/pull/48418 | [phi::DenseTensor] Replace Tensor with phi::DenseTensor | 清除对LoDTensor的使用 |zyfncg YuanRisheng Ligoml XiaoguangHu01 luotao1 |
| https://github.com/PaddlePaddle/Paddle/pull/49953 https://github.com/PaddlePaddle/Paddle/pull/49948 | fix div 0 error of NoamDecay | 消除部分API传入空指针时的除零误差 | wanghuancoder zhouwei25 seemingwang | 
| https://github.com/PaddlePaddle/Paddle/pull/50916 | [fp16] support fp16 on unbind | 给unbind添加Fp16支持 | zhangting2020 | 
| https://github.com/PaddlePaddle/Paddle/pull/51313 | [phi] add register of asreal | 给asreal注册输出 | luotao1 From00 | 

## 部分review PR展示
| PR 号 | PR 标题 | PR 简介 | Review详情 |
| -- | -- | -- | -- |
| https://github.com/PaddlePaddle/Paddle/pull/50936 | [fp16] suppot fp16 in std | 给std增加fp16支持 | 单测代码书写建议 |

## 其他贡献
| 链接 | 标题 | 简介 |
| -- | -- | -- |
| https://github.com/PFCCLab/PaddleAutoProject | PaddleAutoProject  | 根据输入网址，生成指定的.md文档，用于提高[Torch和Paddle之间API对照关系梳理任务](https://github.com/PaddlePaddle/docs/issues/5691) 的作业效率。该repo的协作者为@gouzil, @sanbuphy |

# 担保人意见

@Ligoml, @luotao1

**Comment by luotao1** [comment]
+1
@Liyulingyue 在快乐开源的多个活动（如 DenseTensor 概念统一、API 鲁棒性增强、PHI 算子注册信息修复、fp16开发、Paddle 2.4 API 映射文档等）都很积极，不仅自己完成了很多子任务，还会在交流群里帮助和鼓励其他开发者。

**Comment by XiaoguangHu01** [comment]
+1
支持

**Comment by raindrops2sea** [comment]
代表飞桨再次感谢Liyulingyue的突出贡献！已添加对应权限，请注意查看:-)祝贺！

**Comment by Liyulingyue** [comment]
> 代表飞桨再次感谢Liyulingyue的突出贡献！已添加对应权限，请注意查看:-)祝贺！

已收到，感谢~ =w=
