### ISSUE TITLE
单测目录迁移-ISSUES

### ISSUE THREAD

**Issue by tianshuo78520a** [PaddlePaddle/Paddle#51853]
### 问题描述 Please describe your issue Alternatives

大家好，近期我们在重新整理Paddle框架中所有测试文件，希望把所有单测整合到test目录下，让单测目录变的清晰，方便大家进行代码测试。我们一共统计了62个单测目录，需要进行迁移，欢迎大家提交PR一起整理单测目录。

为了修改单测目录，你需要做的是: 

  1. 下载 Paddle 代码，进行任务目录下文件迁移工作：
        a. 创建新路径目录，把现路径下的所有文件进行迁移，迁移到新目录下。（现路径下不需要保留）
        b. 修改新路径下的 CMakeLists.txt 文件，保证单测文件不会丢失
  2. 参考<a href="https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/index_cn.html" data-morpho-href="https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/index_cn.html"><span>《Paddle贡献指南》</span></a>进行本地验证（编译、执行单测，本地可以先进行迁移部分单测验证），成功后可以提交代码

注:
  1. 你可以参考：[Mv phi and fluid/test To test dir](https://github.com/PaddlePaddle/Paddle/pull/50640) 进行单测目录迁移，迁移工作难度不大，还可以熟悉cmake写法和paddle单测逻辑。
  2. 该任务时间：PR 截止提交时间是3月31日，截止合入时间是4月3日
  3. 认领规则：直接回复下 issue 下方
  4. PR通过CI后，可以评论里或者 review request @tianshuo78520a @zhiqiu ，研发会进行审核
  5. [历史上的 good first issue 列表](https://github.com/PaddlePaddle/community/tree/master/pfcc#good-first-issue)，也欢迎来提 PR 解决~ 欢迎联系花花加入社区，和我们一起[快乐开源](https://github.com/PaddlePaddle/Paddle/issues/48019)！

<img width="200" alt="image" src="https://user-images.githubusercontent.com/39876205/213131273-361d2bb8-ea48-4f62-9603-0b0401f50337.png">

待迁移单测目录列表：（59/63）
> 按 merge 的时间顺序，排名不分先后： @tianshuo78520a (17) @Zheng-Bicheng (23) @jjyaoao (2) @KimBioInfoStudio (2) @Ainavo (2) @gouzil (6) @jinyouzhi (1) @Liyulingyue (1) @Happyd99 (1) @Xingkai98 (1) @RedContritio (2)

序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
1 | test/quantization✅(2023/4/1) |  @Liyulingyue | #52353  | python/paddle/static/quantization/tests
2 | test/legacy_test✅(2023/3/22) |  @Zheng-Bicheng | #51941  | python/paddle/tests
3 | test/quantization✅(2023/3/25) |  @Zheng-Bicheng |  #51942 | python/paddle/tests/quantization
4 | test/legacy_test ✅(2023/3/23)|  @Zheng-Bicheng |  #51943 | python/paddle/reader/tests
5 | test/legacy_test ✅(2023/3/24)| @Zheng-Bicheng  | #51944  | python/paddle/fluid/tests
6 | test/book✅(2023/3/24) | @Zheng-Bicheng  | #51945  | python/paddle/fluid/tests/book
7 | test/custom_kernel ✅(2023/3/24) |  @Zheng-Bicheng |  #51946 | python/paddle/fluid/tests/custom_kernel/*.py
8 | test/custom_op✅(2023/3/28)  | @Zheng-Bicheng  |  #51948 | python/paddle/fluid/tests/custom_op/*.py
9 | test/custom_runtime✅(2023/3/29) | @Zheng-Bicheng  | #52021  | python/paddle/fluid/tests/custom_runtime/*.py
10 | test/legacy_test ✅(2023/6/1)| @tianshuo78520a  |  #53235 | python/paddle/fluid/tests/unittests
11 | test/collective ✅(2023/6/1)| @tianshuo78520a  |  #53235 | python/paddle/fluid/tests/unittests/collective
12 | test/collective/fleet ✅(2023/6/1)| @tianshuo78520a | #53235 | python/paddle/fluid/tests/unittests/collective/fleet
13 | test/collective/multinode ✅(2023/3/28)|  @Ainavo |  #51982 | python/paddle/fluid/tests/unittests/collective/multinode
14 | test/sequence  ✅(2023/4/19)| @tianshuo78520a  | #52985 | python/paddle/fluid/tests/unittests/sequence
15 | 删除✅(2023/3/29) | @Zheng-Bicheng  | #52022  | python/paddle/fluid/tests/unittests/npu
16 | test/fft ✅(2023/4/10)| @Xingkai98 |  #52634 | python/paddle/fluid/tests/unittests/fft
17 | test/auto_parallel ✅(2023/4/17)| @tianshuo78520a | #52885  | python/paddle/fluid/tests/unittests/auto_parallel
18 | test/rnn  ✅(2023/4/17)| @liulinduo  | #52513  | python/paddle/fluid/tests/unittests/rnn
19 | test/distribution ✅(2023/4/17)| @tianshuo78520a | #52885  | python/paddle/fluid/tests/unittests/distribution
20 | test/rpc ✅(2023/3/28) | @Zheng-Bicheng  | #52166  | python/paddle/fluid/tests/unittests/rpc
21 | test/prim ✅(2023/3/30) |  @Zheng-Bicheng | #52167  | python/paddle/fluid/tests/unittests/prim
22 | test/prim/model ✅(2023/3/30) | @Zheng-Bicheng  | #52167  | python/paddle/fluid/tests/unittests/prim/model
23 | test/prim/prim ✅(2023/3/30) |  @Zheng-Bicheng | #52167  | python/paddle/fluid/tests/unittests/prim/prim
24 | test/prim/prim ✅(2023/3/30) | @Zheng-Bicheng  | #52167  | python/paddle/fluid/tests/unittests/prim/prim/vjp
25 | test/prim/prim/vjp/static ✅(2023/3/30) | @Zheng-Bicheng  | #52167  | python/paddle/fluid/tests/unittests/prim/prim/vjp/static
26 | test/prim/prim/vjp/eager ✅(2023/3/30) | @Zheng-Bicheng  | #52167  | python/paddle/fluid/tests/unittests/prim/prim/vjp/eager
27 | test/prim/prim/flags ✅(2023/3/30)| @Zheng-Bicheng  | #52167  | python/paddle/fluid/tests/unittests/prim/prim/flags
28 | test/mkldnn ✅(2023/3/31)| @jinyouzhi  | #51911  | python/paddle/fluid/tests/unittests/mkldnn
29 | test/dygraph_to_static ✅(2023/3/31)| @Ainavo | #52069 | python/paddle/fluid/tests/unittests/dygraph_to_static
30 | test/ir ✅(2023/4/17)|  @tianshuo78520a | #52834 | python/paddle/fluid/tests/unittests/ir
31 | test/ir/inference ✅(2023/4/17)|  @tianshuo78520a | #52834 | python/paddle/fluid/tests/unittests/ir/inference
32 | test/white_list |  @Zheng-Bicheng |  #52129 | python/paddle/fluid/tests/unittests/white_list
33 | test/ps ✅(2023/4/11) | @tianshuo78520a  | #52885  | python/paddle/fluid/tests/unittests/ps
34 | test/tokenizer ✅(2023/4/11) | @RedContritio |  #52658 | python/paddle/fluid/tests/unittests/tokenizer
35 | test/xpu ✅(2023/4/12) | @RedContritio | #52661  | python/paddle/fluid/tests/unittests/xpu
36 | test/standalone_executor✅(2023/4/7) | @Happyd99  | #52520  | python/paddle/fluid/tests/unittests/standalone_executor
37 | test/ipu ✅(2023/3/30)| @gouzil  |  #52143 | python/paddle/fluid/tests/unittests/ipu
38 | test/ipu/custom_ops ✅(2023/3/30)| @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu/custom_ops
39 | test/ipu/custom_ops/deprecated ✅(2023/3/30)| @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu/custom_ops/deprecated
40 | test/ipu/distributed✅(2023/3/30) |  @gouzil | #52143  | python/paddle/fluid/tests/unittests/ipu/distributed
41 | test/asp ✅(2023/3/29)|  @gouzil | #52141  | python/paddle/fluid/tests/unittests/asp
42 | test/distributed_passes ✅(2023/4/11) | @tianshuo78520a |  #52885 | python/paddle/fluid/tests/unittests/distributed_passes
43 | 删除✅(2023/3/25) | @jjyaoao  |  #52064, #52291 | python/paddle/fluid/tests/unittests/mlu
44 | test/prim/composite_ops ✅(2023/3/30)|  @Zheng-Bicheng  |  #52167 | python/paddle/fluid/tests/unittests/prim/composite_ops
45 | test/autograd ✅(2023/3/28) | @gouzil  | #52142  | python/paddle/fluid/tests/unittests/autograd
46 | test/contrib ✅(2023/3/28)| @Zheng-Bicheng  | #52168  | paddle/fluid/contrib/tests
47 | 删除 ✅(2023/3/29)| @Zheng-Bicheng  | #52169  | python/paddle/fluid/incubate/fleet
48 | test/dataset✅(2023/3/28) | @KimBioInfoStudio  | #52148  | python/paddle/dataset/tests
49 | test/cpp/phi/api  ✅(2023/3/20)|  @tianshuo78520a  |  #50640  | paddle/phi/tests/api
50 | test/cpp/phi/common ✅(2023/3/20) |  @tianshuo78520a  |  #50640  | paddle/phi/tests/common
51 | test/cpp/phi/core  ✅(2023/3/20)|  @tianshuo78520a  |  #50640 | paddle/phi/tests/core
52 | test/cpp/phi/kernels  ✅(2023/3/20)| @tianshuo78520a  |  #50640 | paddle/phi/tests/kernels
53 | test/cpp/phi/ops  ✅(2023/3/20)| @tianshuo78520a  |  #50640   | paddle/phi/tests/ops
54 | 删除 ✅(2023/3/29)| @jjyaoao  |  #52063 | paddle/infrt/tests
55 | test/cpp/imperative ✅(2023/3/29)| @Zheng-Bicheng  |  #52170 | paddle/fluid/imperative/tests
56 | test/cpp/prim✅(2023/3/30) | @Zheng-Bicheng  | #52173  | paddle/fluid/prim/tests
57 | test/xpu/cpp✅(2023/3/30) | @KimBioInfoStudio  | #52243  | paddle/fluid/platform/device/xpu/tests
58 | test/cpp/inference/api ✅(2023/4/21)| @tianshuo78520a  | #52987  | paddle/fluid/inference/tests/api
59 | test/cpp/inference/infer_ut ✅(2023/4/21)| @tianshuo78520a  |  #52987 | paddle/fluid/inference/tests/infer_ut
60 | test/cpp/eager/data_structure_tests  ✅(2023/4/24)| @tianshuo78520a  |  #53167 | paddle/fluid/eager/tests/data_structure_tests
61 | test/cpp/eager/performance_tests  ✅(2023/4/24)|  @tianshuo78520a |  #53167 | paddle/fluid/eager/tests/performance_tests
62 | test/cpp/eager/task_tests  ✅(2023/4/24)| @tianshuo78520a  | #53167  | paddle/fluid/eager/tests/task_tests
63 | test/prim/process ✅(2023/3/30) |  @Zheng-Bicheng |  #52167 | python/paddle/fluid/tests/unittests/prim/process

### 其他成果总结
子任务 | 作者 | 相关PR 
-- | -- | -- 
预先设置单测目录，避免频繁冲突 ✅(2023/3/26)| @Zheng-Bicheng  | #52131 #52152
test/cpp/fluid https://github.com/PaddlePaddle/Paddle/pull/52782#issuecomment-1523219572 | @gouzil | #53426✅ #53429✅ #53434✅ #53443✅ #53446✅ #53448✅ #53458✅ #53460✅ #53472✅ #53470✅

**Comment by Liyulingyue** [comment]
<html>
<body>


序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
1 | test/quantization | Liyulingyue  |  https://github.com/PaddlePaddle/Paddle/pull/51890 | python/paddle/static/quantization/tests


</body>
</html>

**Comment by Ainavo** [comment]
| 序号 | 新路径 | 认领人 | 修复pr | 现路径 |
|--------|--------|--------|--------|--------|
| 29 | test/dygraph_to_static | @Ainavo | https://github.com/PaddlePaddle/Paddle/pull/52069  | python/paddle/fluid/tests/unittests/dygraph_to_static |

**Comment by jinyouzhi** [comment]
| 序号	|新路径|	认领人|	修复pr|	现路径|
|---|---|---|---|---|
| 28	|test/mkldnn|	@jinyouzhi | #51911 |		python/paddle/fluid/tests/unittests/mkldnn|

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 2    | test/legacy_test | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/51941     | python/paddle/tests |

@tianshuo78520a @luotao1 ，大佬们，2已经合入了哦，帮忙改一下榜单呗🫡

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 3    | test/quantization | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/51942   | python/paddle/tests/quantization |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 4    | test/legacy_test | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/51943   | python/paddle/reader/tests |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 5    | test/legacy_test | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/51944   | python/paddle/fluid/tests |
| 6    | test/book | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/51945    | python/paddle/fluid/tests/book |
| 7    | test/custom_kernel | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/51946    | python/paddle/fluid/tests/custom_kernel/*.py |
| 8    | test/custom_op | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/51948    | python/paddle/fluid/tests/custom_op/*.py |

**Comment by Ainavo** [comment]
| 序号 | 新路径 | 认领人 | 修复pr | 现路径 |
|--------|--------|--------|--------|--------|
| 11 | test/collective |  |   | python/paddle/fluid/tests/unittests/collective |
| 12 | test/collective/feet | |   | python/paddle/fluid/tests/unittests/collective/feet |
| 13 | test/collective/multinode | @Ainavo | https://github.com/PaddlePaddle/Paddle/pull/51982  | python/paddle/fluid/tests/unittests/collective/multinode |

**Comment by co63oc** [comment]
| 序号  | 新路径  | 认领人  | 修复PR  | 现路径  |
| - | - | - | - | - |
| 30  | test/ir  | @co63oc  | 关闭PR | python/paddle/fluid/tests/unittests/ir  |
| 31  | test/ir/inference  | @co63oc  |  关闭PR | python/paddle/fluid/tests/unittests/ir/inference  |

develop更新较多，合并分支CI较多时间，关闭PR
迁移主要修改
CMakeLists.txt 修改目录配置
py_test_modules 函数迁移

**Comment by kendaji12138** [comment]
<html>
<body>
<!DOCTYPE html>

序号 | 新路径 | 认领人 | 修复pr | 现路径
-- | -- | -- | -- | --
16 | test/fft | kendaji12138 |   | python/paddle/fluid/tests/unittests/fft
17 | test/auto_parallel | kendaji12138 |   | python/paddle/fluid/tests/unittests/auto_parallel
18 | test/rnn | kendaji12138 |   | python/paddle/fluid/tests/unittests/rnn
19 | test/distribution | kendaji12138 |   | python/paddle/fluid/tests/unittests/distribution


</body>
</html>

**Comment by liulinduo** [comment]
<

序号 | 新路径 | 认领人 |   | 现路径
-- | -- | -- | -- | --
33 | test/ps |   |   | python/paddle/fluid/tests/unittests/ps
34 | test/tokenizer |   |   | python/paddle/fluid/tests/unittests/tokenizer
35 | test/xpu |   |   | python/paddle/fluid/tests/unittests/xpu
36 | test/standalone_executor |   |   | python/paddle/fluid/tests/unittests/standalone_executor

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 9    | test/custom_runtime | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52021   | python/paddle/fluid/tests/custom_runtime/*.py |
| 10    | test/legacy_test | Zheng-Bicheng |    | python/paddle/fluid/tests/unittests |
| 15    | 删除 | Zheng-Bicheng |   https://github.com/PaddlePaddle/Paddle/pull/52022  | python/paddle/fluid/tests/unittests/npu |
| 14    | test/sequence | Zheng-Bicheng |   https://github.com/PaddlePaddle/Paddle/pull/52023  | python/paddle/fluid/tests/unittests/sequence |

**Comment by luotao1** [comment]
> @tianshuo78520a @luotao1 ，大佬们，2已经合入了哦，帮忙改一下榜单呗🫡

@Zheng-Bicheng 榜单会不定时更新，BTW，在原来的评论里修改内容，我们会收不到邮件提醒

**Comment by jjyaoao** [comment]
<html>
<body>


序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
54 | 删除 | jjyaoao | #52063 | paddle/infrt/tests
43 | 删除 | jjyaoao | #52064 | python/paddle/fluid/tests/unittests/mlu

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 32    | test/white_list | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/52129  | python/paddle/fluid/tests/unittests/white_list |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 20    | test/rpc | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52166   | test/rpc |

**Comment by gouzil** [comment]
序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
41 | test/asp | @gouzil | #52141  | python/paddle/fluid/tests/unittests/asp
45 | test/autograd | @gouzil | #52142  | python/paddle/fluid/tests/unittests/autograd
37 | test/ipu | @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu
38 | test/ipu/custom_ops | @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu/custom_ops
39 | test/ipu/custom_ops/deprecated | @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu/custom_ops/deprecated
40 | test/ipu/distributed | @gouzil  | #52143  | python/paddle/fluid/tests/unittests/ipu/distributed

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 21    | test/prim | Zheng-Bicheng |   https://github.com/PaddlePaddle/Paddle/pull/52167  | python/paddle/fluid/tests/unittests/prim |
| 22    | test/prim/model | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52167   | python/paddle/fluid/tests/unittests/prim/model |
| 23    | test/prim/prim | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/52167    | python/paddle/fluid/tests/unittests/prim/prim |
| 24    | test/prim/prim/vjp | Zheng-Bicheng |   https://github.com/PaddlePaddle/Paddle/pull/52167  | python/paddle/fluid/tests/unittests/prim/prim/vjp |
| 25    | test/prim/prim/vjp/static | Zheng-Bicheng | https://github.com/PaddlePaddle/Paddle/pull/52167    | python/paddle/fluid/tests/unittests/prim/prim/vjp/static |
| 26    | test/prim/prim/vjp/eager | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52167   | python/paddle/fluid/tests/unittests/prim/prim/vjp/eager ｜
| 27    | test/prim/prim/flags | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52167   | python/paddle/fluid/tests/unittests/prim/prim/flags｜

**Comment by KimBioInfoStudio** [comment]
序号 | 新路径 | 认领人 | 修复PR | 现路径
---- |  -- | -- | -- | --
48 | test/dataset | @KimBioInfoStudio | #52148 | python/paddle/dataset/tests

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 46    | test/contrib | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52168   | paddle/fluid/contrib/tests |

**Comment by Zheng-Bicheng** [comment]
47题经过沟通改为删除目录

| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 47    | 删除 | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52169   | python/paddle/fluid/incubate/fleet/tests |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 44    | test/prim/composite_ops | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52167   | python/paddle/fluid/tests/unittests/prim/composite_ops |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 55    | test/cpp/imperative | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52170   | paddle/fluid/imperative/tests |

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 56    | test/cpp/prim | Zheng-Bicheng |  https://github.com/PaddlePaddle/Paddle/pull/52173   | paddle/fluid/prim/tests |

**Comment by kendaji12138** [comment]
<html>
<body>
<!DOCTYPE html>

序号 | 新路径 | 认领人 | 修复pr | 现路径
-- | -- | -- | -- | --
16 | test/fft | @kendaji12138 | #52178 | python/paddle/fluid/tests/unittests/fft
17 | test/auto_parallel | @liulinduo | #52180 | python/paddle/fluid/tests/unittests/auto_parallel
18 | test/rnn | @Ackeraa | #52182 | python/paddle/fluid/tests/unittests/rnn
19 | test/distribution | @xiaoyuanzi914 | #52212 | python/paddle/fluid/tests/unittests/distribution


</body>
</html>

**Comment by KimBioInfoStudio** [comment]
序号 | 新路径 | 认领人 | 修复pr | 现路径
-- | -- | -- | -- | --
42 | test/distributed_passes | @KimBioInfoStudio | #52242 |python/paddle/fluid/tests/unittests/distributed_passes
57 | test/xpu/cpp | @KimBioInfoStudio  | #52243  | paddle/fluid/platform/device/xpu/tests
58 | test/cpp/inference/api | @KimBioInfoStudio  | #52249  | paddle/fluid/inference/tests/api
59 | test/cpp/inference/infer_ut | @KimBioInfoStudio  | #52249   | paddle/fluid/inference/tests/infer_ut
60 | test/cpp/eager/data_structure_tests | @KimBioInfoStudio  | #52255   | paddle/fluid/eager/tests/data_structure_tests
61 | test/cpp/eager/performance_tests | @KimBioInfoStudio  | #52255   | paddle/fluid/eager/tests/performance_tests
62 | test/cpp/eager/task_tests | @KimBioInfoStudio  | #52255  | paddle/fluid/eager/tests/task_tests

**Comment by Zheng-Bicheng** [comment]
| 序号 | 新路径           | 认领人        | 修复PR | 现路径              |
|------|------------------|---------------|:-------|:--------------------|
| 63    | test/prim/process | Zheng-Bicheng |   https://github.com/PaddlePaddle/Paddle/pull/52167  | python/paddle/fluid/tests/unittests/prim/process |

**Comment by KimBioInfoStudio** [comment]
@tianshuo78520a  this test mv will block PaddleCustomDevice next submodule uplift 
cc: @luotao1 @zhiqiu  @ronny1996 @qili93

**Comment by qili93** [comment]
> @tianshuo78520a this test mv will block PaddleCustomDevice next submodule uplift cc: @luotao1 @zhiqiu @ronny1996 @qili93

Hi Kim,

PaddleCustomDevice only depends on op_test.py  and if you do not update the submodule of Paddle then there will be no impact to PaddleCustomDevice. Please kindly help to let me know which problem you met and propose to fix it in PaddleCustomDevice repo :)

Thanks 
Qi

**Comment by KimBioInfoStudio** [comment]
> > @tianshuo78520a this test mv will block PaddleCustomDevice next submodule uplift cc: @luotao1 @zhiqiu @ronny1996 @qili93
> 
> Hi Kim,
> 
> PaddleCustomDevice only depends on op_test.py and if you do not update the submodule of Paddle then there will be no impact to PaddleCustomDevice. Please kindly help to let me know which problem you met and propose to fix it in PaddleCustomDevice repo :)
> 
> Thanks Qi

Thx for ur reply, Chi

What do u guys think about mv all test base class to wheel like PyTorch do? Then we do not need symlink TestBaseClass in PaddleCustomDevice, my concern is that with growing of PaddleCustomDevice, symlink will growing as well.

Thx Kim

**Comment by tianshuo78520a** [comment]
> 序号	新路径	认领人	修复pr	现路径
> 11	test/collective	@Ainavo		python/paddle/fluid/tests/unittests/collective
> 12	test/collective/feet	@Ainavo	#52068	python/paddle/fluid/tests/unittests/collective/feet
> 13	test/collective/multinode	@Ainavo	#51982	python/paddle/fluid/tests/unittests/collective/multinode

11任务的PR号

**Comment by tianshuo78520a** [comment]
> <
> 
> 序号	新路径	认领人	 	现路径
> 33	test/ps	 	 	python/paddle/fluid/tests/unittests/ps
> 34	test/tokenizer	 	 	python/paddle/fluid/tests/unittests/tokenizer
> 35	test/xpu	 	 	python/paddle/fluid/tests/unittests/xpu
> 36	test/standalone_executor	 	 	python/paddle/fluid/tests/unittests/standalone_executor

请问是否已经提PR？

**Comment by qili93** [comment]
> > > @tianshuo78520a this test mv will block PaddleCustomDevice next submodule uplift cc: @luotao1 @zhiqiu @ronny1996 @qili93
> > 
> > 
> > Hi Kim,
> > PaddleCustomDevice only depends on op_test.py and if you do not update the submodule of Paddle then there will be no impact to PaddleCustomDevice. Please kindly help to let me know which problem you met and propose to fix it in PaddleCustomDevice repo :)
> > Thanks Qi
> 
> Thx for ur reply, Chi
> 
> What do u guys think about mv all test base class to wheel like PyTorch do? Then we do not need symlink TestBaseClass in PaddleCustomDevice, my concern is that with growing of PaddleCustomDevice, symlink will growing as well.
> 
> Thx Kim

Hi Kim,

That's exactly what we are doing now :)

And I think there is already an issue opened for this, @luotao1 please help to comment the issue if we already have, thanks!

**Comment by tianshuo78520a** [comment]
> 序号	新路径	认领人	修复PR	现路径
> 30	test/ir	@co63oc	关闭PR	python/paddle/fluid/tests/unittests/ir
> 31	test/ir/inference	@co63oc	关闭PR	python/paddle/fluid/tests/unittests/ir/inference
> develop更新较多，合并分支CI较多时间，关闭PR 迁移主要修改 CMakeLists.txt 修改目录配置 py_test_modules 函数迁移

@co63oc 请问还要认领么？

**Comment by RedContritio** [comment]
序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
| 34 | test/tokenizer | @RedContritio | #52658 | python/paddle/fluid/tests/unittests/tokenizer |
| 35 | test/xpu | @RedContritio | #52661 | python/paddle/fluid/tests/unittests/xpu |

**Comment by Xingkai98** [comment]
<html>
<body>


序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
16 | test/fft | @Xingkai98 | #52634 | python/paddle/fluid/tests/unittests/fft



</body>
</html>

**Comment by tipHkB5n** [comment]
<html>
<body>


序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
17	| test/auto_parallel	|@tipHkB5n	| #52635	|python/paddle/fluid/tests/unittests/auto_parallel

</body>
</html>

**Comment by ccsuzzh** [comment]
序号 | 新路径 | 认领人 | 修复PR | 现路径
-- | -- | -- | -- | --
33 | test/ps | @ccsuzzh  | #52689  | python/paddle/fluid/tests/unittests/ps

**Comment by luotao1** [comment]
感谢所有参与的10位小伙伴，这个任务已经基本做完了，收尾工作由 @tianshuo78520a 完成：

> 按 merge 的时间顺序，排名不分先后： @Zheng-Bicheng (23) @jjyaoao (2) @KimBioInfoStudio (2) @Ainavo (2) @gouzil (6) @jinyouzhi (1) @Liyulingyue (1) @Happyd99 (1) @Xingkai98 (1) @RedContritio (2)

欢迎大家继续关注[飞桨快乐开源活动](https://github.com/PaddlePaddle/Paddle/issues/48019)，我们近期会发布新的任务，谢谢大家！
