### ISSUE TITLE
使用飞桨的容器进行CenterPoint模型训练，并将其部署在apollo中，启动用是出现aborted的情况，请问是什么原因导致的

### ISSUE THREAD

**Issue by cherishTMYY** [PaddlePaddle/Paddle#51868]
### 请提出你的问题 Please ask your question
训练容器信息：
paddle:2.4.1-gpu-cuda10.2-cudnn7.6-trt7.0
下载的最新的Paddle3D 的代码

错误描述：
--- Running analysis [ir_graph_to_program_pass]
I0320 15:48:59.317131 17084 analysis_predictor.cc:1318] ======= optimize end =======
I0320 15:48:59.318094 17084 naive_executor.cc:110] ---  skip [feed], feed -> data
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (NotFound) Operator (hard_voxelize) is not registered.
  [Hint: op_info_ptr should not be null.] (at /apollo/data/Paddle/paddle/fluid/framework/op_info.h:156)

Aborted (core dumped)

**Comment by wuyefeilin** [comment]
请到Paddle3D下进行提问哈，https://github.com/PaddlePaddle/Paddle3D

**Comment by cherishTMYY** [comment]
> 请到Paddle3D下进行提问哈，https://github.com/PaddlePaddle/Paddle3D

好的，感谢您的解答
