### ISSUE TITLE
win11下golang编译直接报错

### ISSUE THREAD

**Issue by xushushun** [PaddlePaddle/Paddle#51863]
### bug描述 Describe the Bug

win11环境安装了c库并进行了软连接,安装了tdm-gcc编译器,用demo代码调试运行直接报错could not launch process: Process 1704 has exited with status 3221225781

### 其他补充信息 Additional Supplementary Information
golang版本 1.19.3
_No response_

**Comment by wuyefeilin** [comment]
麻烦给一下编译选项和应用场景哈

**Comment by xushushun** [comment]
C:\Users\xushushun\sdk\go1.19.3\bin\go.exe build -o C:\Users\xushushun\AppData\Local\Temp\GoLand\___41go_build_main_go.exe -gcflags "all=-N -l" C:\Users\xushushun\GolandProjects\fjocr\main.go #gosetup
安装的tdm-gcc,应用场景是编译go在win下的推理服务器.

**Comment by jiweibo** [comment]
您好，目前没有对golang的高版本进行适配，可以试下https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/inference/goapi 文档中的go版本
