### ISSUE TITLE
sum算子bug

### ISSUE THREAD

**Issue by Difers** [PaddlePaddle/Paddle#51882]
在调试Beta算子时发现了sum算子的一个bug，
 gpu环境下出错，cpu正常：测试代码如下
```
import paddle
import numpy as np
paddle.set_device("gpu")
array = np.array([], dtype=np.float32)
x = paddle.to_tensor(np.reshape(array, [0, 2]), dtype='float32')
x.sum(-1)
```
![image](https://user-images.githubusercontent.com/10421743/226251052-a5d16db4-b555-4e34-a5ba-f712fe14ee6a.png)
应该是reduce_ function.h下Run函数某一步出错，但下面的维度变化我没看懂QAQ

_Originally posted by @Difers in https://github.com/PaddlePaddle/Paddle/issues/49922#issuecomment-1475629864_

**Comment by wuyefeilin** [comment]
x为零维tensor, sum算子目前不支持该类型计算。

**Comment by Difers** [comment]
> x为零维tensor, sum算子目前不支持该类型计算。

cpu环境下是支持的，想要修复的话是处理至和CPU环境下一致的结果，还是直接在两端都加上维度检查呢？

**Comment by wuyefeilin** [comment]
我看在cpu下面x.sum()结果时错的，x.sum(-1)符合逻辑结构。要修复的话还是得在cpu和gpu下都进行修复，使其符合逻辑

**Comment by luotao1** [comment]
@Difers 可以尝试修复一下～
