### ISSUE TITLE
请问paddle2.2版本支持昆仑R200加速卡吗？

### ISSUE THREAD

**Issue by kgstutwh** [PaddlePaddle/Paddle#51901]
### 请提出你的问题 Please ask your question

在paddle的安装文档中（https://www.paddlepaddle.org.cn/documentation/docs/zh/2.2/guides/09_hardware_support/xpu_docs/paddle_install_cn.html），选择paddle2.2版本的时候，发现安装包中使用的是2.1的paddle包，请问有paddle2.2版本的安装包吗？
![image](https://user-images.githubusercontent.com/22112092/226530112-4c9709f0-a7d0-4455-a021-4de65a28f922.png)

**Comment by seemingwang** [comment]
暂时不支持，2.3开始支持

**Comment by kgstutwh** [comment]
您的邮件我已收到！
