### ISSUE TITLE
License for strongbaseline model from Attribute Recognition Modules of PP-Human project

### ISSUE THREAD

**Issue by lipo5476** [PaddlePaddle/Paddle#51938]
### 请提出你的问题 Please ask your question

Hello Paddle team,

I would like to ask about the possibility of using the strongbaseline model from the Attribute Recognition Modules of PP-Human project in a commercial application. 
I understand that the strongbaseline graph was trained also with "research only" datasets but the PaddleDetection project is under Apache-2.0 license. So, can the pre-trained model be used in a commercial application as it is or it has to be retrained with different data? And under what license it can be used?

Thank you in advance for your reply.

Lipo

**Comment by zhiboniu** [comment]
As your mentioned the dataset is just for "research only", i would suggest to retrain the model for commercial purpose.
