### ISSUE TITLE
[CustomDevice] profiler支持profile_memory

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#51952]
RT. 
看到systom_allocator中没有RecordMemEvent，或者应该在phi的customallocator中添加？
![image](https://user-images.githubusercontent.com/127805199/226782516-b6bf7360-7ed4-450d-9c49-b407ed9d0181.png)
看到代码中没有实现RecordMemEvent，希望添加支持在profiler中profile_memory

**Comment by engineer1109** [comment]
有时间我试一下，不过这个功能Custom Plugin自己也能做到

**Comment by tiandou-tangdou** [comment]
@ronny1996 这个可以在paddle2.5.0中支持一下吗？

**Comment by zhaohaixu** [comment]
@engineer1109 我也在做这方面的尝试，请教下是在Custom Plugin中的runtime接口来实现么，能否详细说下方案呢，感谢~
