### ISSUE TITLE
麒麟v10SP2系统+飞桨安装成功后，验证安装时，提示使用的还是CPU；

### ISSUE THREAD

**Issue by wangguangbo66** [PaddlePaddle/Paddle#51979]
系统:麒麟v10SP2
显卡:寒武纪s4
问题：飞桨安装成功后，验证安装时，提示使用的还是CPU；没有识别到MLU。

**Comment by kuizhiqing** [comment]
请根据这里的提示编译对应版本的 paddle，
https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
