### ISSUE TITLE
MTMCT 跨镜跟踪体验运行出错

### ISSUE THREAD

**Issue by 3250446980** [PaddlePaddle/Paddle#51988]
### 请提出你的问题 Please ask your question

没有改动文件，出现错误，没找到相关设置文件

出现错误提示：
Traceback (most recent call last):
  File "deploy/pptracking/python/mot_sde_infer.py", line 952, in <module>
    main()
  File "deploy/pptracking/python/mot_sde_infer.py", line 912, in main
    mtmct_dir=FLAGS.mtmct_dir )
  File "deploy/pptracking/python/mot_sde_infer.py", line 164, in __init__
    assert tracker_config is not None, 'Note that tracker_config should be set.'
AssertionError: Note that tracker_config should be set.

**Comment by kuizhiqing** [comment]
请设置 tracker_config 然后尝试。

**Comment by 3250446980** [comment]
找不到tracker_config相关设置

**Comment by kuizhiqing** [comment]
请提供更多背景信息，比如，你这是在做什么，怎么做的？

**Comment by 217TYNB** [comment]
我也是这个报错，它文档里面没有介绍 tracker_config的配置，项目里面也没有这个文件，有人知道怎么配置么

**Comment by kuizhiqing** [comment]
@3250446980 @217TYNB , 根据查阅你们使用的代码并不在本 repo 内，请尝试明确以下问题？

* 你们说的“项目”是指什么？是不是 AIStudio ?
* 你们使用代码是什么？
* 你们的预期是什么？
