### ISSUE TITLE
关于paddlehub中ernie_zeus模型的ak和sk问题

### ISSUE THREAD

**Issue by Fly-betterme** [PaddlePaddle/Paddle#51986]
### 请提出你的问题 Please ask your question

import paddlehub as hub
# 加载模型
model = hub.Module(name='ernie_zeus')
谁有ernie_zeus模型能用的ak和sk，默认的也行，或者知道如何申请一个可用的，我申请的不可用Error message: '日访问量超限'.

**Comment by kuizhiqing** [comment]
paddlehub 问题请到 https://github.com/PaddlePaddle/PaddleHub 提交 issue。
