### ISSUE TITLE
基于CustomDevice的分布式训练精度收敛差

### ISSUE THREAD

**Issue by tjs2200120** [PaddlePaddle/Paddle#51985]
### bug描述 Describe the Bug

1、问题描述

- 基于CustomDevice训练vgg16，网络单卡训练精度收敛正常，分布式单机多卡训练精度收敛差。

- 分布式训练网络性能是单卡的一半。

![image](https://user-images.githubusercontent.com/32358954/226845826-fad3e9d3-5d39-4afe-ac54-e89c22c679ac.png)

2、环境配置

PaddlePaddle版本：develop分支上手动编译
CustomDevice：develop分支

**Comment by kuizhiqing** [comment]
请问基于什么样的 device 进行的比较？

**Comment by tjs2200120** [comment]
> 请问基于什么样的 device 进行的比较？

寒武纪MLU590

**Comment by kuizhiqing** [comment]
1. 网络性能差的问题，受限于具体的网络环境，无法直接判断是否合理。模型层面能给出的建议是镜像 profiler 确定瓶颈，然后进行比如通信计算 overlap 的优化。
2. 精度问题需要排查组网逻辑，比如初始化状态是否一致，否则两机的贡献相互抵消，总体效果变差。
