### ISSUE TITLE
大家一起来选择一个文档模板吧！

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#520]
下面几个选择中，如果大家喜欢某一个，请点其中的大拇指图标吧！
<img width="288" alt="screen shot 2016-11-18 at 2 43 43 pm" src="https://cloud.githubusercontent.com/assets/1548775/20421203/742d2592-ad9d-11e6-8acb-744c2331fb44.png">

投票截止时间：北京时间 11月21日 8:00 AM

**Comment by llxxxll** [comment]
Plan B
![paddle](https://cloud.githubusercontent.com/assets/1908992/20421071/aa964736-ad9c-11e6-9b7d-72a282db2675.jpg)

**Comment by llxxxll** [comment]
Plan C
![planc](https://cloud.githubusercontent.com/assets/1908992/20421146/207a68ce-ad9d-11e6-9add-66923abdfbb7.png)

**Comment by llxxxll** [comment]
Plan A
![paddle](https://cloud.githubusercontent.com/assets/1908992/20421060/a3e562aa-ad9c-11e6-8679-36d3a76c3810.jpg)

**Comment by shihongbo0810** [comment]
第二张设计师跑了 pm自己p的😄
