### ISSUE TITLE
如何在不需要使用GPU的时候如何清空GPU缓存？

### ISSUE THREAD

**Issue by xiabingbao-ok** [PaddlePaddle/Paddle#52011]
### 请提出你的问题 Please ask your question

使用 paddle.device.cuda.empty_cache()语句后，GPU显存反而会残留大约600MB的占用，这是什么原因？如果我根据自己的需要想在使用GPU之前将显存全部清空，请问该怎么做？？？？

paddle-bfloat      0.1.7
paddle2onnx        1.0.6
paddlefsl          1.1.0
paddlenlp          2.5.2
paddlepaddle-gpu   2.3.2.post101

代码执行前：
export CUDA_VISIBLE_DEVICES=1
export FLAGS_eager_delete_tensor_gb=0.0
export FLAGS_fast_eager_deletion_mode=1
export FLAGS_memory_fraction_of_eager_deletion=1

代码如下：
import time
import paddle

for i in range(10):
# required: gpu
paddle.set_device("gpu")
#tensor = paddle.randn([512, 512, 512], "float")
#del tensor
paddle.device.cuda.empty_cache()
print('***')
time.sleep(5)

结果：
<img width="632" alt="image" src="https://user-images.githubusercontent.com/84067090/227072522-94e8af4f-0706-4d6b-ada9-905fcf837725.png">

**Comment by sljlp** [comment]
你好，一般不会出现这个情况，请确认是不是有其他进程挥着残留进程在使用GPU吗？

**Comment by xiabingbao-ok** [comment]
> 你好，一般不会出现这个情况，请确认是不是有其他进程挥着残留进程在使用GPU吗？
你可以运行一下，我试了很多次，每次都有残留。如果我使用循环加载模型进行批量预测的时候，gpu显存还会增加，即使我不预测，仅仅加载模型，显存也会慢慢上升。这个和torch好像一样，torch加载模型不使用的时候gpu显存不变。所以我单独使用paddle清空命名试了一下，没有paddle清空命令的时候，gpu显存占用为0，使用了这个命令，gpu现在占用就是600mb左右

**Comment by sljlp** [comment]
这部分是第三方库（例如cuda）占用的显存，paddle无法清空。
