### ISSUE TITLE
minimize_lbfgs在line_search中Wolfe条件错误

### ISSUE THREAD

**Issue by DrownFish19** [PaddlePaddle/Paddle#52020]
### minimize_lbfgs在line_search中Wolfe条件错误

版本：develop最新版本（2023-03-23）

文件路径：
https://github.com/PaddlePaddle/Paddle/blob/2add31f4c994684ce038931d1eda8a17a17a086d/python/paddle/incubate/optimizer/functional/line_search.py#L316

代码位置：
```python
line 316        pred1 = ~done & (
line 317            (phi_2 > phi_0 + c1 * a2 * derphi_0) | ((phi_2 >= phi_0) & (i > 1))
line 318        )
```

应修改：
```python
line 316        pred1 = ~done & (
line 317            (phi_2 > phi_0 + c1 * a2 * derphi_0) | ((phi_2 >= phi_1) & (i > 1)) # 修改phi_0 为 phi_1
line 318        )
```

其他小错误：minimize_lbfgs中max_line_search_iters参数未传递给line_search函数
文件路径：https://github.com/PaddlePaddle/Paddle/blob/325fdf1d87b512fb679aad12cfcd7cae478711b3/python/paddle/incubate/optimizer/functional/lbfgs.py#L212

代码位置：
```python
line 212        if line_search_fn == 'strong_wolfe':
line 213            alpha, value, g2, ls_func_calls = strong_wolfe(
line 214                f=objective_func,
line 215                xk=xk,
line 216                pk=pk,
line 217                initial_step_length=initial_step_length,
line 218                dtype=dtype,
line 219            )
```

**Comment by sljlp** [comment]
辛苦提个PR可以么？
