### ISSUE TITLE
paddle内server启动失败

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#5203]
日志如下：请paddle同学看看，是否端口冲突了

Fri Oct 27 16:29:05 2017[1,91]<stderr>:+ LD_LIBRARY_PATH=/usr/local/lib:./python27-gcc482/lib::/usr/local/openmpi/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/libhce/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/libhdfs:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/../java6/jre/lib/amd64/server
Fri Oct 27 16:29:05 2017[1,95]<stderr>:*** Check failure stack trace: ***
Fri Oct 27 16:29:05 2017[1,96]<stderr>:    @           0x8030ac  paddle::SocketServer::run()
Fri Oct 27 16:29:05 2017[1,99]<stderr>:F1027 16:29:05.697548  5717 LightNetwork.cpp:194] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.76.78.44
Fri Oct 27 16:29:05 2017[1,102]<stderr>:    @           0x8030ac  paddle::SocketServer::run()
Fri Oct 27 16:29:05 2017[1,105]<stderr>:+ GLOG_logtostderr=0
Fri Oct 27 16:29:05 2017[1,108]<stderr>:    @     0x7fb9a68b30ad  __clone
Fri Oct 27 16:29:05 2017[1,108]<stderr>:    @     0x7fb9a68b30ad  __clone
Fri Oct 27 16:29:05 2017[1,110]<stderr>:    @           0x98df6c  google::LogMessage::SendToLog()
Fri Oct 27 16:29:05 2017[1,110]<stderr>:    @           0x98df6c  google::LogMessage::SendToLog()
Fri Oct 27 16:29:05 2017[1,111]<stderr>:    @           0x989fe3  google::LogMessage::Flush()
Fri Oct 27 16:29:05 2017[1,113]<stderr>:*** Check failure stack trace: ***
Fri Oct 27 16:29:05 2017[1,115]<stderr>:+ '[' -z tcp ']'
Fri Oct 27 16:29:05 2017[1,117]<stderr>:*** Check failure stack trace: ***
Fri Oct 27 16:29:05 2017[1,22]<stderr>:+ GLOG_logtostderr=0
Fri Oct 27 16:29:05 2017[1,22]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,22]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 27 16:29:05 2017[1,23]<stderr>:+ GLOG_logtostderr=0
Fri Oct 27 16:29:05 2017[1,23]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,54]<stderr>:+ GLOG_logtostderr=0
Fri Oct 27 16:29:05 2017[1,54]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,59]<stderr>:++ download_thread_num=15
Fri Oct 27 16:29:05 2017[1,71]<stderr>:++ LD_LIBRARY_PATH=./python27-gcc482/lib::/usr/local/openmpi/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/libhce/lib:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/libhdfs:/home/mpi/nma/bin/../tools/hadoop-client/hadoop/../java6/jre/lib/amd64/server
Fri Oct 27 16:29:05 2017[1,73]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 27 16:29:05 2017[1,75]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,75]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 27 16:29:05 2017[1,83]<stderr>:+ source ./common.sh
Fri Oct 27 16:29:05 2017[1,89]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,89]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 27 16:29:05 2017[1,91]<stderr>:+ GLOG_logtostderr=0
Fri Oct 27 16:29:05 2017[1,95]<stderr>:F1027 16:29:05.712054 11063 LightNetwork.cpp:194] Check failed: bind(socket_, (struct sockaddr *)&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.76.78.39
Fri Oct 27 16:29:05 2017[1,95]<stderr>:*** Check failure stack trace: ***
Fri Oct 27 16:29:05 2017[1,96]<stderr>:    @           0x802df7  paddle::SocketServer::tcpServer()
Fri Oct 27 16:29:05 2017[1,99]<stderr>:*** Check failure stack trace: ***
Fri Oct 27 16:29:05 2017[1,102]<stderr>:    @           0x8030ac  paddle::SocketServer::run()
Fri Oct 27 16:29:05 2017[1,105]<stderr>:+ GLOG_log_dir=./log
Fri Oct 27 16:29:05 2017[1,105]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=120 --nics=xgbe0 --port=7164 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Oct 27 16:29:05 2017[1,108]<stderr>:    @              (nil)  (unknown)
Fri Oct 27 16:29:05 2017[1,108]<stderr>:    @              (nil)  (unknown)

**Comment by typhoonzero** [comment]
```
Fri Oct 27 16:29:05 2017[1,95]:F1027 16:29:05.712054 11063 LightNetwork.cpp:194] Check failed: bind(socket_, (struct sockaddr )&serv_addr, sizeof(serv_addr)) >= 0 ERROR on binding 10.76.78.39
```
tcp server bind失败，应该是端口被占用了

**Comment by youan1** [comment]
我们是例行任务，不可能人工去干预手动换端口，另外我们也是用 resource=full提交的，这个有什么办法解决么

**Comment by Yancey1989** [comment]
Close the inactivate issue, please feel free to reopen it if the problem is still existed.
