### ISSUE TITLE
paddle.fidlu.layers.collective 被替换到哪里去了呢

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#52034]
### 请提出你的问题 Please ask your question

paddle.fidlu.layers.collective 没有了
![image](https://user-images.githubusercontent.com/47998305/227130363-5a724ff7-a4e0-47b9-96c4-e37d725d1152.png)
最新的develop分支 2add31f4c994684ce038931d1eda8a17a17a086d

**Comment by sljlp** [comment]
换成 paddle.dsitributed里的接口

**Comment by HarperCy** [comment]
> 换成 paddle.dsitributed里的接口

可是新的接口里没有这些参数

**Comment by HarperCy** [comment]
> 换成 paddle.dsitributed里的接口

![image](https://user-images.githubusercontent.com/47998305/227131583-7df913f4-c295-4810-a025-0e32db4c6cfd.png)

**Comment by HarperCy** [comment]
> 换成 paddle.dsitributed里的接口

<img width="538" alt="image" src="https://user-images.githubusercontent.com/47998305/227131649-e0893576-4b0f-4039-b171-d91f2c9dd3db.png">

**Comment by sljlp** [comment]
group 包含了 fleet.worker_num, ring id 等信息，如果没有group参数的话，可能需要修改下模型代码，先获取一下。你现在用的是哪个模型代码？
