### ISSUE TITLE
PaddleSeg套件nnunet模型本地推理无法保存推理结果

### ISSUE THREAD

**Issue by Arthus666** [PaddlePaddle/Paddle#52056]
### bug描述 Describe the Bug

环境：paddlepaddle-gpu2.4，cuda 10.2，cudnn7.6.5
显卡：nvidia 3060
![图片](https://user-images.githubusercontent.com/76039868/227205408-c00b2c3b-2b25-46c9-8035-4dba57134e0e.png)

本地执行推理命令，输出日志prediction done，inference done，在输出separate z ，order in z is 0 order inplane is 1之后就命令行卡住不动了，输出文件夹中生成了.pkl文件，可是没有保存推理结果，5个小时之后依旧是这样，无法保存推理结果

执行命令和目录结构如下：
![图片](https://user-images.githubusercontent.com/76039868/227207942-d18a0f2b-90a1-4396-9985-50ca3d1be58e.png)

日志输出如下：
![图片](https://user-images.githubusercontent.com/76039868/227209507-00f4d86f-c430-443a-9a9c-4830991a1595.png)

以上推理流程在aistudio上运行成功并保存了推理结果，可是在本地没有，望解决！谢谢！

**Comment by shiyutang** [comment]
如果切换环境导致错误的话，怀疑是本地资源限制导致，请查看本地的存储空间，cpu资源、显存资源是否有超出现象。另外为什么需要再本地推理呢？ AIStudio的保存结果保存不下么？

**Comment by Arthus666** [comment]
> 
因为模型需要部署在本地才能整合到项目里，云端部署没有相应的GPU服务器

**Comment by shiyutang** [comment]
那么本地的资源是否有超过限制呢？ 因为数据和代码保证一致的情况下，只有资源/环境的原因了。

**Comment by Arthus666** [comment]
>会不会是因为CUDA版本不同呢，aistudio上是CUDA11.2，本地的是10.6

**Comment by shiyutang** [comment]
可以进一步在```separate z ，order in z is 0 order inplane is 1```后的代码部分增加打印输出，查看卡住位置，进行精细定位。

**Comment by Arthus666** [comment]
> 可以进一步在`separate z ，order in z is 0 order inplane is 1`后的代码部分增加打印输出，查看卡住位置，进行精细定位。


Debug之后卡在这里
![~9DSNC3~_90G7U2`2$K 3I2](https://user-images.githubusercontent.com/76039868/228217772-98144618-4a6b-438d-989f-aae6abe02bd4.png)

![~9DSNC3~_90G7U2`2$K 3I2](https://user-images.githubusercontent.com/76039868/228217772-98144618-4a6b-438d-989f-aae6abe02bd4.png)

3P7PC R67RTB`X](https://user-images.githubusercontent.com/76039868/228217845-67d749dc-466a-401e-a6c0-2f0079f09a99.png)

**Comment by Arthus666** [comment]
debug之后卡在这里

![~9DSNC3~_90G7U2`2$K 3I2](https://user-images.githubusercontent.com/76039868/228219588-f95bd49a-bd8e-4c22-a276-100c2b6e824e.png)
![68 YV8Cdebug之后卡在这里

![~9DSNC3~_90G7U2`2$K 3I2](https://user-images.githubusercontent.com/76039868/228219588-f95bd49a-bd8e-4c22-a276-100c2b6e824e.png)
3P7PC R67RTB`X](https://user-images.githubusercontent.com/76039868/228219615-fcb2a1c8-8c18-420d-8930-d80809588852.png)

**Comment by shiyutang** [comment]
目前看来是pool保存分割结果卡住，建议增大数量为所有可用的cpu数量，即替换下图中的num_threads_nifti_save为None。
<img width="720" alt="image" src="https://user-images.githubusercontent.com/34859558/228462969-08bd3417-3b27-4a64-8760-dd6ce58085b7.png">

**Comment by Arthus666** [comment]
> 目前看来是pool保存分割结果卡住，建议增大数量为所有可用的cpu数量，即替换下图中的num_threads_nifti_save为None。 <img alt="image" width="720" src="https://user-images.githubusercontent.com/34859558/228462969-08bd3417-3b27-4a64-8760-dd6ce58085b7.png">

试了还是不可以

**Comment by shiyutang** [comment]
如果还是不可以的话，说明资源不足以保存，建议减少处理的数据，并观察是否有cpu内存/硬盘存储超出的情况。
