### ISSUE TITLE
CustomDevice 中 runtime 和 CCL 的 stream 不属于同一 class/struct 时，要如何管理？

### ISSUE THREAD

**Issue by yangulei** [PaddlePaddle/Paddle#52077]
我们团队正在通过 CustomDevice API 提供[对 intel dGPU 的支持](https://github.com/PaddlePaddle/PaddleCustomDevice/tree/develop/backends/intel_gpu)。其中 runtime 基于 DPCPP/SYCL，使用的是 [sycl::queue](https://intel.github.io/llvm-docs/doxygen/classsycl_1_1__V1_1_1queue.html) 作为 stream；而集合通讯基于 oneCCL，使用的是 [ccl::stream](https://oneapi-src.github.io/oneCCL/api/concepts/stream.html)。目前 CustomDevice API 没有区分 runtime 和 CCL 的 stream，请问这种情况下如何管理(创建、获取、使用、销毁) CCL 的 stream？

**Comment by FeixLiu** [comment]
稍等，我让相关同学看下～

**Comment by qili93** [comment]
请问是否可以使用一个work-around，比如可以在 create_stream 的时候同时对 sycl::queue 与 ccl::stream 进行创建，然后再  destroy_stream 的时候同时对两个对象进行销毁。目前Paddle主框架内部对于通信和计算是分成2个stream对象，但是类都还是一个类，比如 GPU 都是 cudaStream_t，如果要分别支持2种不同类型的stream需要对框架的通信库接口做比较大的改造，工作量会比较大，建议先尝试下 work-around 的方法。

**Comment by yangulei** [comment]
> 请问是否可以使用一个work-around，比如可以在 create_stream 的时候同时对 sycl::queue 与 ccl::stream 进行创建，然后再 destroy_stream 的时候同时对两个对象进行销毁。目前Paddle主框架内部对于通信和计算是分成2个stream对象，但是类都还是一个类，比如 GPU 都是 cudaStream_t，如果要分别支持2种不同类型的stream需要对框架的通信库接口做比较大的改造，工作量会比较大，建议先尝试下 work-around 的方法。

目前我们想到两种方案：

方案一：API依然只传递 sycl::queue；CustomDevice 这边维护一个 map<sycl::queue, ccl::stream>；需要 ccl::stream 时先查找 map 中是否已有 key，有则取其 value，否则创建 ccl:stream，并添加到 map。

方案二：定义一个形如
``` c
typedef struct {
  sycl::queue queue;    // stream for runtime
  ccl::stream stream;    // stream for CCL
} C_Stream_Pool;
```
的结构体，将两种 stream 打包。

我个人更倾向于方案二，请问有什么建议？

**Comment by qili93** [comment]
> > 请问是否可以使用一个work-around，比如可以在 create_stream 的时候同时对 sycl::queue 与 ccl::stream 进行创建，然后再 destroy_stream 的时候同时对两个对象进行销毁。目前Paddle主框架内部对于通信和计算是分成2个stream对象，但是类都还是一个类，比如 GPU 都是 cudaStream_t，如果要分别支持2种不同类型的stream需要对框架的通信库接口做比较大的改造，工作量会比较大，建议先尝试下 work-around 的方法。
> 
> 目前我们想到两种方案：
> 
> 方案一：API依然只传递 sycl::queue；CustomDevice 这边维护一个 map<sycl::queue, ccl::stream>；需要 ccl::stream 时先查找 map 中是否已有 key，有则取其 value，否则创建 ccl:stream，并添加到 map。
> 
> 方案二：定义一个形如
> 
> ```c
> typedef struct {
>   sycl::queue queue;    // stream for runtime
>   ccl::stream stream;    // stream for CCL
> } C_Stream_Pool;
> ```
> 
> 的结构体，将两种 stream 打包。
> 
> 我个人更倾向于方案二，请问有什么建议？

同意方案二，用结构体会更加清晰，感谢您的理解 :)
