### ISSUE TITLE
Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by xiaofengese** [PaddlePaddle/Paddle#52074]
### 问题描述 Please describe your issue

Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/libpaddle.so

**Comment by xiaofengese** [comment]
怎么处理

**Comment by FeixLiu** [comment]
稍等，我让相关同学来看下

**Comment by xiaofengese** [comment]
一直就这样

**Comment by xiaofengese** [comment]
import  paddle 导入不进去

**Comment by xiaofengese** [comment]
![image](https://user-images.githubusercontent.com/67010388/227414691-6ab71c36-f4d4-4f5d-a0b3-089410da34c1.png)
jiu'zhe'y就这样

**Comment by mzq20180601** [comment]
我也刚遇到这个问题，目前是下载了paddlepaddle-2.4.2-cp38-cp38-manylinux1_x86_64.whl去centos7下安装的，网上说是gcc版本的问题，不知是否

**Comment by mzq20180601** [comment]
我也刚遇到这个问题，目前是下载了paddlepaddle-2.4.2-cp38-cp38-manylinux1_x86_64.whl去centos7下安装的，网上说是gcc版本的问题，不知是否，目前我的gcc版本是4.8.5

**Comment by xiaofengese** [comment]
我现在在更新gcc




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 中午11:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/libpaddle.so (Issue #52074)





 
我也刚遇到这个问题，目前是下载了paddlepaddle-2.4.2-cp38-cp38-manylinux1_x86_64.whl去centos7下安装的，网上说是gcc版本的问题，不知是否

**Comment by xiaofengese** [comment]
怎么找官方人员






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年3月24日(星期五) 中午11:13
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/libpaddle.so (Issue #52074)





 
我也刚遇到这个问题，目前是下载了paddlepaddle-2.4.2-cp38-cp38-manylinux1_x86_64.whl去centos7下安装的，网上说是gcc版本的问题，不知是否，目前我的gcc版本是4.8.5

**Comment by xiaofengese** [comment]
> 我也刚遇到这个问题，目前是下载了paddlepaddle-2.4.2-cp38-cp38-manylinux1_x86_64.whl去centos7下安装的，网上说是gcc版本的问题，不知是否，目前我的gcc版本是4.8.5

不知道第一条什么意思

**Comment by zhengqiwen1997** [comment]
需要用gcc82安装

**Comment by xiaofengese** [comment]
我现在就在安装gcc&nbsp; 那么上面那个报错了


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月24日(星期五) 中午11:24
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.7/site-packages/paddle/fluid/libpaddle.so (Issue #52074)





 
需要用gcc82安装

**Comment by zhengqiwen1997** [comment]
你好，目前进展如何。

**Comment by alibabadoufu** [comment]
我也遇到了相同的问题，解决了吗？ @FeixLiu
