### ISSUE TITLE
集合通信队列管理相关说明

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/Paddle#52071]
### 请提出你的问题 Please ask your question

是否能够提供一下分布式训练时通信队列和计算队列并行流水的设计文档，或者简单说明？

**Comment by FeixLiu** [comment]
您是想咨询分布式训练时，通讯与计算放到不同的cuda stream上达到通讯与计算overlap的功能么？

**Comment by ShawnNew** [comment]
> 您是想咨询分布式训练时，通讯与计算放到不同的cuda stream上达到通讯与计算overlap的功能么？

是的

**Comment by FeixLiu** [comment]
如果使用的是动态图下数据并行（DataParallel），Paddle框架底层是默认通讯计算overlap的。

**Comment by ShawnNew** [comment]
> 如果使用的是动态图下数据并行（DataParallel），Paddle框架底层是默认通讯计算overlap的。

能提供一下相关细节吗？具体点来讲，ddp过程中通信会管理几条队列？计算会有几条队列？训练过程中哪些操作会涉及到集合通信？这些队列之间的同步点是如何设置的？

**Comment by ForFishes** [comment]
您好。
1、ddp中通信一个stream，计算一个stream。
2、训练过程中，只有在backward阶段触发allredcue通信。在实现计算和通信的overlap。
3、通信是异步的，会在最后一个梯度通信后，让计算的stream等待该通信，实现同步。

**Comment by ShawnNew** [comment]
> 您好。 1、ddp中通信一个stream，计算一个stream。 2、训练过程中，只有在backward阶段触发allredcue通信。在实现计算和通信的overlap。 3、通信是异步的，会在最后一个梯度通信后，让计算的stream等待该通信，实现同步。

通信队列上的梯度应该是分批下发的吧？中间会不会下event？最后同步的过程是通过event实现的吗？

**Comment by ForFishes** [comment]
您好，1、梯度是分批下发的，但是会有fuse，不是每一个梯度产生了就通信。2、中间会有event控制，保证梯度产生完成，才会进行通信。3、最后的同步是通过event事件进行控制的。
