### ISSUE TITLE
安装paddlepaddle-gpu 2.4.2多次失败，急需帮助！！谢谢！！

### ISSUE THREAD

**Issue by VampireWiz** [PaddlePaddle/Paddle#52075]
### 问题描述 Issue Description

Window11,硬件环境i7 12700H,  显卡 4060
cuda runtime 11.2 版本, cudnn 8.2.1, python 3.8.10 
按官网说明安装，命令为：
python -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

之后执行
import paddle 
paddle.utils.run_check()

显示AttributeError: module 'paddle' has no attribute 'utils'

多次安装均是这样。
请问这是什么情况？
最后一次安装，清除了所有的环境，重新安装CUDA,cuDNN，paddlepaddle-gpu，依旧不行。
官方给出的summary_env.py，执行后找不到 paddle version，找不到paddle with CUDA，找不到cuDNN……

同样的环境安装cpu版本是可以的，且可以训练。
求帮助！！非常感谢！！

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: N/A
Libc version: N/A
Python version: 3.8.10

CUDA version: 11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0
cuDNN version: N/A
Nvidia driver version: 528.66
Nvidia driver List:
GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU

****************************************
![1](https://user-images.githubusercontent.com/8721420/227415163-43e4aafb-c511-4237-b841-077e0bdeb82b.png)
![2](https://user-images.githubusercontent.com/8721420/227415187-99c0f2fa-751e-4a95-970b-5b3a3af7c7aa.png)

**Comment by FeixLiu** [comment]
稍等，我让相关同学来看下

**Comment by zhwesky2010** [comment]
@VampireWiz 可以去相应的python目录下的site_packages目录下查一下，是否有utils文件

**Comment by VampireWiz** [comment]
> @VampireWiz 可以去相应的python目录下的site_packages目录下查一下，是否有utils文件

的确没有，还需要手动pip install paddle?
官网的教程里没说这个。

**Comment by VampireWiz** [comment]
已经查明是python安装的问题，卸载重装后问题解决。感谢大家！

**Comment by TimenoLong** [comment]
能不能细说具体的Python安装问题，因为我遇到了和你一样的问题
