### ISSUE TITLE
关于channel last(NHWC)layout的算子在paddle中调度的优先级为什么低于非channel last的layout？

### ISSUE THREAD

**Issue by tangleintel** [PaddlePaddle/Paddle#52081]
### 请提出你的问题 Please ask your question

目前在paddle的dispatch机制中，当面对一个op有多个输入tensor且他们的layout不一致时，对最终op将采用的layout的选取机制如下：
`phi::DataLayout tensor_layout = tensor.layout();
    key_set.layout =
        tensor_layout > key_set.layout ? tensor_layout : key_set.layout;
`位于kernel_dispatch.h文件的KernelKeyParser结构体的[AssignKernelKeySet](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/api/lib/kernel_dispatch.h#L100-L113)成员函数中。同时，目前[DataLayout](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/common/layout.h#L36-L44)枚举类型中对layout定义的顺序为NHWC < NCHW < NCDHW < NDHWC ... 
对于此实现，提问者想请教一下：

1. 关于layout dispatch背后的设计思想是什么？
2. 基于此逻辑，如果用户想让模型中的算子走进channel last版本的实现，在python前端需要做什么样的改动？如果可以显示的设置输入tensor和weight的layout为NHWC(目前paddle貌似没有提供这样的接口)，在后续的传播中，NHWC是否会因为优先级低于tensor默认的NCHW格式给覆盖？
3. 对于NHWC，NCHW，NCDHW，NDHWC 以及其他的一些layout在DataLayout这个枚举类型中的定义的顺序是基于什么来决定的？

**Comment by FeixLiu** [comment]
稍等，我让相关同学看下～

**Comment by jiahy0825** [comment]
您好，相关的设计思想可以参考文档：[飞桨高可复用算子库 PHI 设计文档](https://github.com/PaddlePaddle/docs/blob/develop/docs/design/phi/design_cn.md)

DataLayout 中的这四种 layout 相当于预留出来的扩展选项，kernel 在实际注册时，指定的是 ALL_LAYOUT，因此动态图在执行时其实对 layout 是不敏感的。

某些算子支持按照特殊的 layout 执行，在 python 端使用 `data_format` 控制，例如 conv2d 提供了 `data_format` 参数。

**Comment by tangleintel** [comment]
> 您好，相关的设计思想可以参考文档：[飞桨高可复用算子库 PHI 设计文档](https://github.com/PaddlePaddle/docs/blob/develop/docs/design/phi/design_cn.md)
> 
> DataLayout 中的这四种 layout 相当于预留出来的扩展选项，kernel 在实际注册时，指定的是 ALL_LAYOUT，因此动态图在执行时其实对 layout 是不敏感的。
> 
> 某些算子支持按照特殊的 layout 执行，在 python 端使用 `data_format` 控制，例如 conv2d 提供了 `data_format` 参数。

谢谢回复。
拿conv2d的cpu kernel为例，在python端使用data_format="NHWC"创建好算子后，在实际的kernel的选择的时候会选择(cpu, ALL_LAYOUT)的版本，从kernel的实现上看，对于一个原本在物理内存上以NCHW格式为输入的input tensor的layout转换是发生在kernel内部而不是在api.cc这个文件的conv2d()中的input_input = PrepareData() 这一步，对吗？此外，在指定了data_format为"NHWC"的conv中，它的输出tensor的物理内存排布也是NHWC格式的对吧？那输出tensor中的meta data里对应的layout属性有没有被设置为NHWC呢？

**Comment by jiahy0825** [comment]
> 拿conv2d的cpu kernel为例，在python端使用data_format="NHWC"创建好算子后，在实际的kernel的选择的时候会选择(cpu, ALL_LAYOUT)的版本，从kernel的实现上看，对于一个原本在物理内存上以NCHW格式为输入的input tensor的layout转换是发生在kernel内部而不是在api.cc这个文件的conv2d()中的input_input = PrepareData() 这一步，对吗？

对的，conv2d 实际的转换在 kernel 内部实现

> 此外，在指定了data_format为"NHWC"的conv中，它的输出tensor的物理内存排布也是NHWC格式的对吧？

对的，`data_format` 实际上指示了 input 的格式，输出的格式与 input 的一致，因此物理内存排布也会变为 NHWC 格式（参考 conv2d 注释：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/conv.py#L627）

> 那输出tensor中的meta data里对应的layout属性有没有被设置为NHWC呢？

这块需要根据每个 op 分析其对应的 InferMeta 函数。我查看了 `ConvInferMeta` 和 `ConvKernelImpl` 的实现，并没有找到在 C++ 端显式的指定 TensorMeta 中的 layout 属性，此时 tensor 中的 meta data 里的 layout 属性可能是不确定的。
