### ISSUE TITLE
ddpg训练报错

### ISSUE THREAD

**Issue by zhl606** [PaddlePaddle/Paddle#52090]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/96058439/227445785-69d0423f-f5ce-49ab-ba99-655a8558c135.png)
在ddpg算法中，实例化了多个agent，每个agent的action_dim和obs_dim不同，在run_train_episode的agent.learn()中，出现了报错

**Comment by FeixLiu** [comment]
请检查调用concat算子的地方，传入tensor的shape与传入axis的信息是否匹配。是否出现要在某一个不存在的axis上concat的情况。

**Comment by zhl606** [comment]
![image](https://user-images.githubusercontent.com/96058439/227457566-1dc27f61-5d52-4073-9804-729b6bc343ad.png)
调试的结果axis=1，看之前的报错消息，axis不应该等于1，所以这里应该怎么改呢？谢谢

**Comment by FeixLiu** [comment]
你传入的这两个tensor都是1维tensor，如果要将其concat成[430]的tensor，axis应该是0，不应该是1。

**Comment by zhl606** [comment]
所以可以直接在代码中将axis设置为0么？

**Comment by FeixLiu** [comment]
是的呀，这个axis应该是你coding的时候调用concat接口设置的吧

**Comment by zhl606** [comment]
好的谢谢，我也不懂为啥每次debug到这里都是1，现在能跑通啦，再次感谢~
