### ISSUE TITLE
执行demo报错

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5209]
我希望在一个干净的环境里工作，所以我在指定路径里依次装了gilbc，设置LD_LIBRARY_PATH的环境变量增加我自己的lib路径
python pip numpy 和protobuf，最后执行安装 python pip install paddlepaddle 
安装是成功的，执行paddle version也可以有正常输出
但是下载demo执行 python train.py的时候，报Segmentation fault。没有找到core文件。
在main里面第一行加print依旧打印不出来。求问怎么调试

**Comment by sweetsky0901** [comment]
>>> import paddle.v2 as paddle
Segmentation fault

执行 import paddle是可以的

**Comment by cxysteven** [comment]
你的train.py是什么？

**Comment by sweetsky0901** [comment]
包含import paddle.v2 as paddle就会报错

**Comment by Xreki** [comment]
> 所以我在指定路径里依次装了gilbc，设置LD_LIBRARY_PATH的环境变量增加我自己的lib路径

你是在什么环境上安装的glibc，glibc的版本是？先确认下你安装的glibc是否能正常使用。安装高版本的glibc后，通常很容易因为glibc跟系统的内核不兼容，而直接出现`Segmentation fault`。

**Comment by ultimatesword** [comment]
@sweetsky0901 我也遇见了这个问题，你解决了吗
