### ISSUE TITLE
Error: Can not import paddle core while this file exists: /usr/local/lib64/python3.6/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by xiaofengese** [PaddlePaddle/Paddle#52106]
### 问题描述 Please describe your issue

Error: Can not import paddle core while this file exists: /usr/local/lib64/python3.6/site-packages/paddle/fluid/libpaddle.so

**Comment by FeixLiu** [comment]
可以参考这个issue：https://github.com/PaddlePaddle/Paddle/issues/52074

**Comment by zhengqiwen1997** [comment]
请提供环境信息

**Comment by alibabadoufu** [comment]
我也遇到了相同的问题
