### ISSUE TITLE
tensor为int8类型使用stack操作报错

### ISSUE THREAD

**Issue by SumFunction** [PaddlePaddle/Paddle#52127]
### 如题

![image](https://user-images.githubusercontent.com/70028523/227542453-39408318-c20b-433d-b689-3ca68fe0a047.png)
代码如上，请问为什么两个tensor格式为int8类型的使用stack会报上述错误，如果tensor改为其它类型就不会，如果在不更换tensor数据格式的前提下，请问要如何解决？

**Comment by FeixLiu** [comment]
`paddle.ones` 不支持int8类型，该api支持的类型可以参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/ones_cn.html#ones
