### ISSUE TITLE
本地单机多卡训练速度慢

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#52138]
### bug描述 Describe the Bug

本地单机多卡训练速度慢，和paddlecloud速度差别很大，本地单机多卡训练速度和单卡差不多，这有可能是什么原因导致？本地单机多卡的的代码和提交paddlecloud的代码是一致的

**Comment by WorgenZhang** [comment]
麻烦您补充一下信息：
1. 训练模式是什么，Collective还是PS
2. 训练场景是什么
3. 实际训练性能是多少
4. 实际训练代码
