### ISSUE TITLE
为什么import paddle后有那么多DeprecationWarning

### ISSUE THREAD

**Issue by 6tt101** [PaddlePaddle/Paddle#52132]
### 请提出你的问题 Please ask your question

![AP{CP2$MY6VVT4V@CGZ2S30](https://user-images.githubusercontent.com/128829198/227572813-a7dac546-0aaf-49f2-a3d9-5c180b47594f.png)

**Comment by FeixLiu** [comment]
看上去都是Pillow库的一些接口的warning，应该是第三方库做了更新，会在新版本paddle种进行跟进。

**Comment by SigureMo** [comment]
同 #41674、#43572，该问题在 2.3.0 及以上版本就应该就没有了
