### ISSUE TITLE
安装过程没报错，安装完验证的时候报错：OSError: Invalid enum backend type `63`

### ISSUE THREAD

**Issue by zhao791204** [PaddlePaddle/Paddle#52174]
### 问题描述 Issue Description

控制台运行：

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
W0327 14:09:17.983440  1796 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 10.2, Runtime API Version: 10.2
W0327 14:09:19.393191  1796 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Python37\lib\site-packages\paddle\utils\install_check.py", line 270, in run_check
    _run_dygraph_single(use_cuda, use_xpu, use_npu)
  File "C:\Program Files\Python37\lib\site-packages\paddle\utils\install_check.py", line 136, in _run_dygraph_single
    linear_out = linear(input_tensor)
  File "C:\Program Files\Python37\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\paddle\nn\layer\common.py", line 176, in forward
    x=input, weight=self.weight, bias=self.bias, name=self.name
  File "C:\Program Files\Python37\lib\site-packages\paddle\nn\functional\common.py", line 1886, in linear
    return _C_ops.linear(x, weight, bias)
OSError: Invalid enum backend type `63`.
  [..\paddle/phi/common/backend.h:140]

以下是 GPU Tesla P4 信息
C:\Users\Administrator\Desktop>nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89

C:\Users\Administrator\Desktop>nvidia-smi
Mon Mar 27 14:07:03 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 443.66       Driver Version: 443.66       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla P4            TCC  | 00000000:03:00.0 Off |                    0 |
| N/A   46C    P8     8W /  75W |      8MiB /  7611MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.2
Paddle With CUDA: True
OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: version 3.16.9
Libc version: N/A
Python version: 3.7.0
CUDA version: 10.2.89
cuDNN version: 7.6.5
Nvidia driver version: 443.66
Nvidia driver List:
GPU 0: Tesla P4

****************************************

**Comment by AnnaTrainingG** [comment]
你好，可以尝试进行本地编译安装， 或者是直接拉取Paddle最新的安装包进行尝试。https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

**Comment by gg22mm** [comment]
2.4以后确实有些机子是这个问题，我linux上gpu可以,wind10上不行
