### ISSUE TITLE
建议：在Quick Start Tutorial关于Network Architecture部门，添加现有网络结构的整体描述

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#522]
建议：在Quick Start Tutorial关于Network Architecture部门，添加现有网络结构的整体描述。

![image](https://cloud.githubusercontent.com/assets/12882811/20421471/138c9694-ad9f-11e6-8827-a874c11660c3.png)

**Comment by reyoung** [comment]
这个会在下一个release修改。

**Comment by luotao1** [comment]
网站已全新改版，该issue就close了。
