### ISSUE TITLE
inconsistent behavior with torch/numpy when operating +=

### ISSUE THREAD

**Issue by SylarTiaNII** [PaddlePaddle/Paddle#52217]
### bug描述 Describe the Bug

```python
import paddle, numpy
a = paddle.to_tensor([1.])
b = a
print(b) #[1.]
a += 1
print(b) #[1.]

a = numpy.array([1.])
b = a #[1.]
a += 1
print(b) #[2.]
```

### 其他补充信息 Additional Supplementary Information

When operating "+=" in paddle, paddle will return a new constructed tensor instead of modify the tensor in-place, which is inconsistent with torch/numpy and finally results in different values on the variables get assigned by the tensor to perform "+=" (refer to variable 'b' in the previous example).

**Comment by zhangbo9674** [comment]
感谢反馈，我们会尽快对该问题进行分析
