### ISSUE TITLE
arrch64 build paddle paddlehub, No RNNCell

### ISSUE THREAD

**Issue by hbo-lambda** [PaddlePaddle/Paddle#52211]
### 请提出你的问题 Please ask your question

参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html
paddle编译成功，安装后检查也没问题，但是安装了paddlehub后，调用时却找不到RNNCell，为什么呢
![image](https://user-images.githubusercontent.com/7626261/228099468-aaf369b2-d138-4761-918a-51cef344291d.png)

**Comment by rainyfly** [comment]
paddle版本是多少，直接在命令行打开一个python， import paddle,  from paddle.fluid.layers import RNNCell 可以import进来么

**Comment by hbo-lambda** [comment]
> paddle版本是多少，直接在命令行打开一个python， import paddle, from paddle.fluid.layers import RNNCell 可以import进来么

为了回复，我又痛苦的编译了一遍，盼复...
---------------------------------------------
1.我是在arm服务器上编译的paddle，所以version是0.0.0
2.命令行打开python，import paddle, from paddle.fluid.layers import RNNCell不可以调用
![Snip20230330_2](https://user-images.githubusercontent.com/7626261/228717800-6266b2c4-87fd-4961-86ad-ebea892d1889.png)

**Comment by rainyfly** [comment]
我们发现paddle的develop的版本里，这个类确实没有了。可能是因为最近paddle再清理fluid下的接口的原因，我在paddle 2.4.2版本里import了这个类，是可以import进来的。你这个只有自己编译才能吗，不能直接pip install 发行版么。如果真的只能自己编译的化，建议编译paddle 2.4.2之前的paddle版本使用

**Comment by rainyfly** [comment]
https://github.com/PaddlePaddle/Paddle/pull/48972  这个是导致这个问题的原因，之后跟着paddle升级后，paddlehub这块会更新版本处理一下这个问题

**Comment by hbo-lambda** [comment]
> 我们发现paddle的develop的版本里，这个类确实没有了。可能是因为最近paddle再清理fluid下的接口的原因，我在paddle 2.4.2版本里import了这个类，是可以import进来的。你这个只有自己编译才能吗，不能直接pip install 发行版么。如果真的只能自己编译的化，建议编译paddle 2.4.2之前的paddle版本使用

我编译一个低版本的试试，谢谢啦

**Comment by mmfei** [comment]
我编译了2.5.....感人.....也一样遇到这个...这个是不是可以修一下呢....

**Comment by rainyfly** [comment]
先降低paddle版本使用一下吧~

**Comment by yz8654773** [comment]
楼主，话说，你的最后解决了么！你是用的gpu版，还是cpu
