### ISSUE TITLE
docker基础镜像registry.baidubce.com/paddlepaddle/paddle是否有ARM架构镜像

### ISSUE THREAD

**Issue by leoterry-ulrica** [PaddlePaddle/Paddle#52223]
### 请提出你的问题 Please ask your question

在docker环境下部署paddleocr，里面用到一个基础镜像：registry.baidubce.com/paddlepaddle/paddle:2.3.2，请问是否有ARM架构对应的基础镜像？如果没有，那么是否支持在ARM架构服务器下进行源码编译？但看你们官方网站说明，paddle又不支持ARM64:，如下图所示：

![image](https://user-images.githubusercontent.com/18339429/228137925-4c93ca40-2925-421a-b841-29002793abdf.png)

**Comment by zhangbo9674** [comment]
你好，官方暂未提供 arm 架构的基础镜像，麻烦您提供一下具体的应用场景，我们后续会对您的需求进行评估。

**Comment by leoterry-ulrica** [comment]
> 你好，官方暂未提供 arm 架构的基础镜像，麻烦您提供一下具体的应用场景，我们后续会对您的需求进行评估。

现在客户提供的服务器环境是麒麟V10的操作系统，打算使用docker方式运行，需要一个ARMV8的基础镜像构建镜像。

**Comment by zhangbo9674** [comment]
你好，官方提供了麒麟V10下源码编译方法，请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html

**Comment by leoterry-ulrica** [comment]
> 你好，官方提供了麒麟V10下源码编译方法，请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html

如果我本地没有麒麟操作系统，然后我在一台ARM架构的Alibaba Cloud Linux操作系统上编译，是不是也可以？

**Comment by zhangbo9674** [comment]
应该也是可以的

**Comment by engineer1109** [comment]
目前来看不太可能有，CI只有Mac arm的，这一块没人管
