### ISSUE TITLE
在使用新功能pytorch转paddle时报错Can not import paddle core while this file exists: /root/miniconda3/lib/python3.8/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by linnnn1** [PaddlePaddle/Paddle#52237]
### 请提出你的问题 Please ask your question

rootaautodl-container-c6d211a83c-218e14b0:/autodl-tmp/FSRCNN/X2Paddle#setup .pproject-projectconwerttorcdir='/root/autodl-tmp/FSRCNN/’ --save dir='/root/autodl-tmp/FSRCNN-paddle/Error: Can not import paddle core wile this file exists: /root/miniconda3/lib/python3.8/site-packages/paddle/fluid/libpaddle.soTraceback (most recent call last):File "setup.py",line 2, in <module>import X2paddleFile "/root/autodl-tmp/FSRCNN/X2Paddle/x2paddle/ init .py"，line 3, in <module>from .core.program import PaddleGraphFile "/root/autodl-tmp/FSRCNN/X2Paddle/x2paddle/core/program.py"，line 18,in <module>import paddleFile "/root/miniconda3/lib/python3.8/site-packages/paddle/ init .py" line 25, in <module>from .framework import monkey patch variableFile "/root/miniconda3/lib/python3.8/site-packages/paddle/framework/ init .py", line 17, in <module>from . import random # noga: F401File "/root/miniconda3/lib/python3.8/site-packages/paddle/framework/random.py", line 16, in <module>import paddle.fluid as fluidFile "/root/miniconda3/lib/pvthon3.8/site-packages/paddle/fluid/init .py",line 36,in <module>
from . import frameworkFile "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework,py", line 37, in <module>
from .import coreFile "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/core.py", line 338, in <module>
raise e
File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/core.py", line 274, in <modulex
from . import libpaddle
ImortError: /root/miniconda/li/python3.8/site-packages/paddle/fluid/libpaddleso: syol cudarahDebuedotPrint version libcudart,so1
1.0 not defined in file libcudart.so.110 with link time reference

这个报错应该怎么解决呢？

**Comment by zhangbo9674** [comment]
你好，请麻烦先检查一下paddle是否安装成功

**Comment by linnnn1** [comment]
您好，是安装成功的，是2.4.2版本



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年3月28日(周二) 晚上6:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 在使用新功能pytorch转paddle时报错Can not import paddle core while this file exists: /root/miniconda3/lib/python3.8/site-packages/paddle/fluid/libpaddle.so (Issue #52237)




 
你好，请麻烦先检查一下paddle是否安装成功

**Comment by zhangbo9674** [comment]
看报错提示是 cuda库没有链接上，执行paddle.utils.run_check()可以成功么
