### ISSUE TITLE
TypeError: unhashable type: 'DecoderSQLItem'，paddle.jit.to_static 进行静态模型训练时，不支持lable非哈希对象

### ISSUE THREAD

**Issue by gaohongfeng1977** [PaddlePaddle/Paddle#52238]
代码片段，增加to_static 开关：
![image](https://user-images.githubusercontent.com/86485131/228202835-b9e3a2a4-fcb1-466d-8d15-6520c6457e62.png)

调试时变量信息：
![image](https://user-images.githubusercontent.com/86485131/228204626-ea3fd180-b8ac-4599-bd80-85d75430a25f.png)

train时错误信息：
在将动态模型转换为静态模型，进行训练过程时，报错：
TypeError: unhashable type: 'DecoderSQLItem'

详细错误信息：

_Traceback (most recent call last):
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 263, in make_hashable
    hash(x)
TypeError: unhashable type: 'DecoderSQLItem'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/tools/NLP/Text2SQL-BASELINE/script/text2sql_main.py", line 367, in <module>
    train(config)
  File "/var/tools/NLP/Text2SQL-BASELINE/script/text2sql_main.py", line 134, in train
    launch.trainer.train(config, model, optimizer, config.train.epochs, train_reader, dev_reader)
  File "/var/tools/NLP/Text2SQL-BASELINE/text2sql/launch/trainer.py", line 173, in train
    loss = epoch_train(config, model, optimizer, epoch, train_data, config.general.is_debug)
  File "/var/tools/NLP/Text2SQL-BASELINE/text2sql/launch/trainer.py", line 84, in epoch_train
    loss = model(inputs, labels)
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 948, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 411, in __call__
    raise e
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 385, in __call__
    *args, **kwargs, is_train=self._is_train_mode())
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 485, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 951, in __getitem__
    item_id = hash(item)
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 205, in __hash__
    make_hashable(self.input_args_with_spec, error_msg),
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 260, in make_hashable
    return tuple(map(make_hashable, x))
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 260, in make_hashable
    return tuple(map(make_hashable, x))
  File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 273, in make_hashable
    raise ValueError(error_msg + " But received type: %s" % type_name(x))
ValueError: Requires a hashable object. But received type: DecoderSQLItem

Process finished with exit code 1_

代码部分：
DecoderSQLItem 是自定义对象，代码如下：

```
class DecoderSQLItem:
    """DecoderSQLItem"""
    tree = attr.ib()
    orig_code = attr.ib()
    sql_query = attr.ib(default="")

```
运行时，值如下：
[DecoderSQLItem(tree={'_type': 'sql', 'select': {'_type': 'select', 'aggs': [{'_type': 'agg', 'agg_id': {'_type': 'NoneAggOp'}, 'val_unit': {'_type': 'Column', 'col_unit1': {'_type': 'col_unit', 'agg_id': {'_type': 'NoneAggOp'}, 'col_id': 6}}}, {'_type': 'agg', 'agg_id': {'_type': 'NoneAggOp'}, 'val_unit': {'_type': 'Column', 'col_unit1': {'_type': 'col_unit', 'agg_id': {'_type': 'NoneAggOp'}, 'col_id': 5}}}, {'_type': 'agg', 'agg_id': {'_type': 'Avg'}, 'val_unit': {'_type': 'Column', 'col_unit1': {'_type': 'col_unit', 'agg_id': {'_type': 'NoneAggOp'}, 'col_id': 13}}}]}, 'from': {'_type': 'from', 'table_units': [{'_type': 'Table', 'table_id': 3}, {'_type': 'Table', 'table_id': 1}]}, 'sql_where': {'_type': 'sql_where'}, 'sql_groupby': {'_type': 'sql_groupby', 'group_by': [{'_type': 'col_unit', 'agg_id': {'_type': 'NoneAggOp'}, 'col_id': 12}]}, 'sql_orderby': {'_type': 'sql_orderby', 'limit': 2}, 'sql_ieu': {'_type': 'sql_ieu'}}, orig_code={'orderBy': [], 'from': {'table_units': [['table_unit', 3], ['table_unit', 1]], 'conds': [[0, 2, [0, [0, 12, False], None], 4, None]]}, 'union': None, 'except': None, 'having': [], 'limit': 2, 'intersect': None, 'where': [], 'groupBy': [[0, 12, False]], 'select': [[0, [0, [0, 6, False], None]], [0, [0, [0, 5, False], None]], [5, [0, [0, 13, False], None]]]}, sql_query='')]

请问：paddle框架底层动态模型转静态模型，lable不支持可变数据类型的比较操作吗？

**Comment by gaohongfeng1977** [comment]
触发错误的源码分析：
![image](https://user-images.githubusercontent.com/86485131/228208889-0fc7fb2a-ec1c-45c7-a62b-836cc3a628c2.png)
```
 def __hash__(self):
        error_msg = "Arguments to a `@paddle.jit.to_static` must be a hashable Python objects (or nested structures of these types)."
        with_hook = self.kwargs.get("with_hook", False)
        is_train = self.kwargs.get("is_train", False)
        return hash((id(self.function_spec),
                     make_hashable(self.input_args_with_spec, error_msg),
                     make_hashable(self.input_kwargs_with_spec,
                                   error_msg), self._spec_names_id,
                     self.class_instance, with_hook, is_train))

```
//
 """
def make_hashable(x, error_msg=None):

    Makes input `x` hashable.

    For some unhashable objects, such as `dict/list/set/np.ndarray`,applying hash function by using their values.
    """
    if isinstance(x, (tuple, list, set)):
        return tuple(map(make_hashable, x))

    try:
        hash(x)
    except TypeError:
        if isinstance(x, np.ndarray):
            # Note: `tostring()` will return the binary data from np.ndarray that
            # means different value will lead to different hash code.
            return hash(x.tostring())
        elif isinstance(x, dict):
            return tuple(map(make_hashable, x.values()))

        error_msg = error_msg or "Requires a hashable object."
        raise ValueError(error_msg + " But received type: %s" % type_name(x))

    return x

**Comment by 0x45f** [comment]
你好，to_static装饰的函数的输入需要是hashable的

**Comment by gaohongfeng1977** [comment]
> 你好，to_static装饰的函数的输入需要是hashable的

动态模型的输入可以是unhashable的，为什么to_static装饰的forward的输入就需要hashable？ 这样不是违背了paddle框架只需要加to_static就可以转换为静态模型的设计了吗？

**Comment by 0x45f** [comment]
> > 你好，to_static装饰的函数的输入需要是hashable的
> 
> 动态模型的输入可以是unhashable的，为什么to_static装饰的forward的输入就需要hashable？ 这样不是违背了paddle框架只需要加to_static就可以转换为静态模型的设计了吗？

因为静态图有自身的限制，所以无法和动态图做到『完全』的统一

**Comment by gaohongfeng1977** [comment]
> > > 你好，to_static装饰的函数的输入需要是hashable的
> > 
> > 
> > 动态模型的输入可以是unhashable的，为什么to_static装饰的forward的输入就需要hashable？ 这样不是违背了paddle框架只需要加to_static就可以转换为静态模型的设计了吗？
> 
> 因为静态图有自身的限制，所以无法和动态图做到『完全』的统一

非常感谢你即时的回复，那基于这种输入为列表的情况，我应该怎么改呢？

**Comment by gaohongfeng1977** [comment]
我在except增加了一个else判断，强制转换为string
```
def make_hashable(x, error_msg=None):
    """
    Makes input `x` hashable.

    For some unhashable objects, such as `dict/list/set/np.ndarray`,applying hash function by using their values.
    """
    if isinstance(x, (tuple, list, set)):
        return tuple(map(make_hashable, x))

    try:
        hash(x)
    except TypeError:
        if isinstance(x, np.ndarray):
            # Note: `tostring()` will return the binary data from np.ndarray that
            # means different value will lead to different hash code.
            return hash(x.tostring())
        elif isinstance(x, dict):
            return tuple(map(make_hashable, x.values()))
        else:
            return hash(str(x))  //增加异常强制转换string


        error_msg = error_msg or "Requires a hashable object."
        raise ValueError(error_msg + " But received type: %s" % type_name(x))

    return x
```

错误不发生了，但是有产生了后续的错误：

> if type_info.fields:
    File "/var/tools/NLP/Text2SQL-BASELINE/text2sql/models/sql_decoder/decoder.py", line 441, in compute_mle_loss
        rule = (node['_type'], tuple(present))
        rule_idx = self.rules_index[rule]
        assert traversal.cur_item.state == TreeTraversal.State.CHILDREN_APPLY
        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        traversal.step(rule_idx)

    File "/root/miniconda3/envs/cuda10.2_env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 661, in convert_assert
	assert cond, message

**Comment by 0x45f** [comment]
> 

看报错是assert语句出错了，可以打个断点看一下等号左右两边的值都是什么
