### ISSUE TITLE
paddle inference用最简单的Mnist的模型,在部署测试时报错

### ISSUE THREAD

**Issue by jiang123lim** [PaddlePaddle/Paddle#52252]
### bug描述 Describe the Bug

在采用最简单的Mnist手写数字识别的模型通过paddle inference进行部署时发生以下报错:

InvalidArgumentError: The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [1, 20, 7, 7], X's size = 980, 'shape' is [100, 980], the capacity of 'shape' is 98000.
      [Hint: Expected capacity == in_size, but received capacity:98000 != in_size:980.] (at ..\paddle/fluid/operators/reshape_op.cc:230)

在模型训练时的代码中进行eval传入的shape是:[1,1,28,28],但采用paddle inference部署时,直接传入np.ones((1, 1, 28, 28)).astype(np.float32)都会产生报错,报错内容如上.

当时的代码如下:
https://aistudio.baidu.com/aistudio/projectdetail/5824858

盼复,已经试了3天了

**Comment by zhangbo9674** [comment]
你好，为了方便定位问题，麻烦上传一下pdmodel和可复现脚本

**Comment by jiang123lim** [comment]
[infer.zip](https://github.com/PaddlePaddle/Paddle/files/11099702/infer.zip)
以上为该文件压缩包,多谢

**Comment by vivienfanghuagood** [comment]
> 在模型训练时的代码中进行eval传入的shape是:[1,1,28,28],但采用paddle inference部署时,直接传入np.ones((1, 1, 28, 28)).astype(np.float32)都会产生报错,报错内容如上.

从你的pdmodel可以导出的模型带了两个输入，尺寸分别为[100,1,28,28]和[100,1]，所以Infer.py 对输入的处理也必须符合相应的尺寸。具体可以参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/gpu/resnet50

**Comment by jiang123lim** [comment]
但是我们在模型定义和导出和Eval时都是使用[1,1,28,28]或者[100,1,28,28],然后我在img = np.ones((100, 1, 28, 28)).astype(np.float32)这样直接传入时是会报错的,报错结果如下
InvalidArgumentError: ShapeError: label's dimensions of AccuracyOp must be 2. But received label's dimensions = 4, label's shape = [100, 1, 28, 28]
      [Hint: Expected label_dim.size() == 2, but received label_dim.size():4 != 2:2.] (at ..\paddle\phi\infermeta\ternary.cc:44)
      [operator < accuracy > error]

**Comment by jiang123lim** [comment]
还没解决啊

**Comment by Aurelius84** [comment]
@jiang123lim 你好，看了下你 paddle.jit.to_static 和 paddle.jit.save 的用法是有一些问题的。

第一点：从你的MNIST组网代码来看，里面包含了accuracy的计算逻辑，这部分在预测时应该是不需要的吧？
```python
# 定义模型结构
class MNIST(paddle.nn.Layer):
    def __init__(self):
        super(MNIST, self).__init__()

        # 定义卷积层和池化层以及最后的全连接层，输出特征通道为20，卷积核的大小为5，卷积步长为1，padding为2
        self.conv1 = Conv2D(in_channels=1, out_channels=20, kernel_size=5, stride=1, padding=2)
        self.max_pool1 = MaxPool2D(kernel_size=2, stride=2)
        self.conv2 = Conv2D(in_channels=20, out_channels=20, kernel_size=5, stride=1, padding=2)
        self.max_pool2 = MaxPool2D(kernel_size=2, stride=2)
        self.fc = Linear(in_features=980, out_features=10)

        # 定义前向计算过程
    @paddle.jit.to_static  # 添加装饰器，使动态图网络结构在静态图模式下运行
    def forward(self, inputs, label):
        x = self.conv1(inputs)
        x = F.relu(x)
        x = self.max_pool1(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = self.max_pool2(x)
        x = paddle.reshape(x, [x.shape[0], 980])
        x = self.fc(x)
        if label is not None:
            acc = paddle.metric.accuracy(input=x, label=label)   # <------ 非预测逻辑，动转静下会放到静态Program里
            return x, acc
        else:
            return x
```
推荐解决方式：将非预测的逻辑从forward函数移除，将其放到 train 函数里，详见[官方文档介绍](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/basic_usage_cn.html#id1)中「值得注意的是」部分
```python
        # 定义前向计算过程
    @paddle.jit.to_static  # 添加装饰器，使动态图网络结构在静态图模式下运行
    def forward(self, inputs):   # <------ 输入只有 inputs
        x = self.conv1(inputs)
        x = F.relu(x)
        x = self.max_pool1(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = self.max_pool2(x)
        x = paddle.reshape(x, [x.shape[0], 980])
        x = self.fc(x)
        
       return x
```


第二点：你在train 函数末尾使用了 paddle.jit.save 导出预测模型之前，没有使用 model.eval() 切换到eval模式，虽然在你的模型里没有什么问题，但如果模型里有dropout或BatchNorm，就会有潜在的风险，详见[官方文档介绍](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/basic_usage_cn.html#moxingbaocunyangli)

第三点：如果你预测时指定的 batch_size 或者 image图片的大小与训练可能不一致，推荐在paddle.jit.to_static接口里指定input_sepc参数，将batch_size等shape动态变化的维度指定为 -1 或None。这样导出的预测模型是指定batch_size为任意值的，而非仅为1或者训练时的值。详见[官方文档InputSpec章节介绍](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/basic_usage_cn.html#jibenyongfa)


第四点：按照你提供的 Train.py 里的forward函数，它有两个输入：inputs 和 labels，意味着导出的推理模型也应该有两个输入。因为你没有将forward中与预测无关的label计算逻辑移出forward。但你在infer.py里提供给Predictor的输入只有一个img，却少了label。但其实你期望推理模型本来就没有label，这一点与你的Train.py代码相互矛盾。这也是在第一点中我建议你将非预测逻辑移出forward的原因。

可以系统性看下[动态图转静态--使用样例](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/jit/basic_usage_cn.html)官方文档，参考修改下代码即可导出推理

**Comment by jiang123lim** [comment]
多谢,修改了几次最后成功了
