### ISSUE TITLE
paddle.topk returns tensor with stop_gradient=False

### ISSUE THREAD

**Issue by SylarTiaNII** [PaddlePaddle/Paddle#52283]
### bug描述 Describe the Bug

```python
import paddle
a = paddle.to_tensor([1., 2., 3.])
a.stop_gradient = True
b = paddle.topk(a, 1)
print(b.stop_gradient)
```

### 其他补充信息 Additional Supplementary Information

Maybe leads to incorrectness when calculating gradients.

**Comment by SylarTiaNII** [comment]
There is same issue when casting a tensor into boolean value.

**Comment by SylarTiaNII** [comment]
similar issue with #52286

**Comment by GuoxiaWang** [comment]
![image](https://user-images.githubusercontent.com/16953187/228755984-c60a8807-68f4-4021-93d1-152eefde033c.png)
