### ISSUE TITLE
模型训练报错无内容

### ISSUE THREAD

**Issue by yizhiyangou** [PaddlePaddle/Paddle#52290]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/107088741/228468602-6e3561bc-67b8-4a73-9054-e1cb6ede42f1.png)
如图，在编写完model.fit函数后无法运行，且没有报错内容。
贴一张代码图
![image](https://user-images.githubusercontent.com/107088741/228468971-a5918448-92f2-4153-927f-643bf2c9de56.png)

**Comment by GuoxiaWang** [comment]
![image](https://user-images.githubusercontent.com/16953187/228758084-aaaba56d-246c-4c9d-9c58-7b7708d31199.png)
这里已经 assert 了， 检查一下 metrics 的设置。

**Comment by yizhiyangou** [comment]
我想问一下这里的assert是什么意思呢

**Comment by GuoxiaWang** [comment]
就是为了判断，你可以在这个地方打印一下。
