### ISSUE TITLE
建议：Quick Start Tutorial的页面整体结构的标题要有明显的分级

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#523]
建议：Quick Start Tutorial的页面整体结构的标题要有明显的分级。

可以用其他颜色标注，各个标题的字体大小等都可以标注

**Comment by reyoung** [comment]
这个会在下一次Release的时候修改的。

**Comment by luotao1** [comment]
网站页面已全新改版，该issue就close了。
