### ISSUE TITLE
is:issue is:open 一个八张卡的机器，运行两个ddp程序，一个显卡设置0，1，2，3，另一个设置4，5，6，7。 这两个程序print到终端的语句会混合错乱，是怎么回事？

### ISSUE THREAD

**Issue by dongfangyixi** [PaddlePaddle/Paddle#52309]
### bug描述 Describe the Bug

如题

**Comment by dongfangyixi** [comment]
运行程序的cmd如下：

一个程序是：
CUDA_VISIBLE_DEVICES=0,1,2,3 \
python  -m paddle.distributed.launch --gpus=0,1,2,3 train.py

另一个是：
CUDA_VISIBLE_DEVICES=4,5,6,7 \
python  -m paddle.distributed.launch --gpus=4,5,6,7 train.py

**Comment by GuoxiaWang** [comment]
`launch` https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/launch_cn.html#launch 有个参数是   `--log_dir`，默认值是 `--log_dir=log`，在同一目录中同时运行两个程序，会都写进  `log/workerlog.x` 中，你在 terminal 中看到的 print，其实是从 `log/workerlog.0` 中读出来回显的。本质上是 `log/workerlog.0` 被两个程序写串了，导致回显乱了。

你可以通过加一个 `--log_dir` 设置不同的目录来规避。

**Comment by dongfangyixi** [comment]
> 

明白了，多谢
