### ISSUE TITLE
paddle.fluid.layers.filter_by_instag 使用咨询

### ISSUE THREAD

**Issue by ShaominFan** [PaddlePaddle/Paddle#52312]
### 请提出你的问题 Please ask your question

想咨询一下paddle1.8.5版本中的paddle.fluid.layers.filter_by_instag 迁移到paddle 2.4.2版本中有什么对应的方法吗
对于filter_by_instag使用中会fake一条假样本有什么使用避雷的地方吗，谢谢！！

**Comment by GuoxiaWang** [comment]
`filter_by_instag` 在  paddle 2.1 以后就废弃了。

**Comment by ShaominFan** [comment]
在多业务多塔的模型中需要filter 样本现在一般是怎么操作呢
