### ISSUE TITLE
在使用OCR进行模型训练时候，报bug TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by foolfish1** [PaddlePaddle/Paddle#52329]
### bug描述 Describe the Bug

**使用PaddleOCR 做模型训练时候，报如下错误信息**
![image](https://user-images.githubusercontent.com/11812086/228725859-64e86208-f534-4227-8ead-51d6a84f69a0.png)

"/study/ocr/paddleOCR/PaddleOCR/ppocr/metrics/distillation_metric.py", line 63, in get_metric
    for key in self.metrics:
TypeError: 'NoneType' object is not iterable
eval model::   0%|

**版本：paddleOCR release 2.6**
**OS：Windows10**

**Comment by ronny1996** [comment]
你好，这个应该不是框架问题，可以在PaddleOCR提个issue

**Comment by beafidmei** [comment]
你好，请问解决了吗，我现在遇到了一样的问题
