### ISSUE TITLE
paddle xpu版本paddle.topk api报错

### ISSUE THREAD

**Issue by kgstutwh** [PaddlePaddle/Paddle#52328]
### bug描述 Describe the Bug

在测试昆仑R200加速卡的时候，调用paddle.topk api报错。
问题：paddle.topk报错OSError: (External) XPU API 2nd Transpose kernel returns wrong value[1 xpu api invalid param]，具体信息如下：
![image](https://user-images.githubusercontent.com/22112092/228721997-22d6c2ff-ed3b-4059-9716-cb622698cb8e.png)

复现环境：
* python 3.7.6
* paddlepaddle-xpu==2.3.0rc0

代码：
```
import paddle
# iou.pd文件地址：https://drive.google.com/file/d/1QjHt03YKmxHg28U2Su2rohYmV1Ytz1gS/view?usp=share_link
iou = paddle.load("/tmp/iou.pd")
matched_vals, matches = paddle.topk(iou, k=1, axis=0)
```

**Comment by ronny1996** [comment]
你好，可以安装最新版的paddle尝试下是否还存在问题，我这里尝试develop的paddle没有问题

![image](https://user-images.githubusercontent.com/25691046/228728739-aaf98246-dd45-449a-be8d-f9e5efb9737d.png)
