### ISSUE TITLE
paddle导出onnx格式报错

### ISSUE THREAD

**Issue by Obiany-Sr** [PaddlePaddle/Paddle#52339]
### bug描述 Describe the Bug

!pip install paddle2onnx
save_path = 'data/onnx' # 需要保存的路径
x_spec = paddle.static.InputSpec([1, 1, 7,7 ], 'float32','x') # 为模型指定输入的形状和数据类型，支持持 Tensor 或 InputSpec ，InputSpec 支持动态的 shape。
paddle.onnx.export(model, save_path, input_spec=[x_spec], opset_version=11)

报错：
---------------------------------------------------------------------------RuntimeError Traceback (most recent call last)/tmp/ipykernel_99/1893687119.py in <module> 4 save_path = 'data/onnx' # 需要保存的路径 5 x_spec = paddle.static.InputSpec([1, 1, 7,7 ], 'float32') # 为模型指定输入的形状和数据类型，支持持 Tensor 或 InputSpec ，InputSpec 支持动态的 shape。 ----> 6 paddle.onnx.export(model, save_path, input_spec=[x_spec], opset_version=11) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/onnx/export.py in export(layer, path, input_spec, opset_version, **configs) 103 input_spec=input_spec, 104 opset_version=opset_version, --> 105 **configs) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/convert.py in dygraph2onnx(layer, save_file, input_spec, opset_version, **configs) 54 if os.path.isfile(params_file): 55 os.remove(params_file) ---> 56 paddle.jit.save(layer, os.path.join(paddle_model_dir, "model"), input_spec) 57 logging.info("Static PaddlePaddle model saved in {}.".format( 58 paddle_model_dir)) <decorator-gen-182> in save(layer, path, input_spec, **configs) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs) 23 def __impl__(func, *args, **kwargs): 24 wrapped_func = decorator_func(func) ---> 25 return wrapped_func(*args, **kwargs) 26 27 return __impl__ /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in __impl__(*args, **kwargs) 38 def __impl__(*args, **kwargs): 39 with framework._dygraph_guard(None): ---> 40 return func(*args, **kwargs) 41 42 return __impl__ /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py in save(layer, path, input_spec, **configs) 734 static_forward = declarative( 735 inner_layer.forward, input_spec=inner_input_spec) --> 736 concrete_program = static_forward.concrete_program 737 # the input_spec has been used in declarative, which is equal to 738 # @declarative with input_spec and jit.save without input_spec, /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in concrete_program(self) 451 print(decorated_foo.concrete_program) 452 """ --> 453 return self.concrete_program_specify_input_spec(input_spec=None) 454 455 def concrete_program_specify_input_spec(self, input_spec=None): /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in concrete_program_specify_input_spec(self, input_spec) 489 if has_input_spec: 490 concrete_program, _ = self.get_concrete_program( --> 491 *desired_input_spec) 492 return concrete_program 493 else: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in get_concrete_program(self, *args, **kwargs) 399 400 # 3. check whether hit the cache or build a new program for the input arguments --> 401 concrete_program, partial_program_layer = self._program_cache[cache_key] 402 return concrete_program, partial_program_layer 403 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in __getitem__(self, item) 712 713 if item not in self._caches: --> 714 self._caches[item] = self._build_once(item) 715 # Note: raise warnings if number of traced program is more than `max_tracing_count` 716 current_tracing_count = len(self._caches) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in _build_once(self, cache_key) 703 input_spec=cache_key.input_args_with_spec, 704 input_kwargs_spec=cache_key.input_kwargs_with_spec, --> 705 class_instance=cache_key.class_instance) 706 return concrete_program, partial_program_from(concrete_program) 707 <decorator-gen-180> in from_func_spec(func_spec, input_spec, input_kwargs_spec, class_instance) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py in __impl__(func, *args, **kwargs) 23 def __impl__(func, *args, **kwargs): 24 wrapped_func = decorator_func(func) ---> 25 return wrapped_func(*args, **kwargs) 26 27 return __impl__ /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py in __impl__(*args, **kwargs) 38 def __impl__(*args, **kwargs): 39 with framework._dygraph_guard(None): ---> 40 return func(*args, **kwargs) 41 42 return __impl__ /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py in from_func_spec(func_spec, input_spec, input_kwargs_spec, class_instance) 659 error_data = getattr(e, error.ERROR_DATA, None) 660 if error_data: --> 661 error_data.raise_new_exception() 662 raise 663 /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py in raise_new_exception(self) 190 # 2. Use exec to bypass syntax error checking in Python 2. 191 --> 192 six.exec_("raise new_exception from None") 193 else: 194 raise new_exception /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py in <module> RuntimeError: In transformed code: File "/home/aistudio/.paddlehub/modules/resnet50_vd_imagenet_ssld/module.py", line 255, in forward (* user code *) y = self.conv1_1(inputs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__ outputs = self.forward(*inputs, **kwargs) File "/home/aistudio/.paddlehub/modules/resnet50_vd_imagenet_ssld/module.py", line 73, in forward (* user code *) y = self._conv(inputs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__ outputs = self.forward(*inputs, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 667, in forward use_cudnn=self._use_cudnn) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/conv.py", line 139, in _conv_nd type=op_type, inputs=inputs, outputs=outputs, attrs=attrs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op return self.main_program.current_block().append_op(*args, **kwargs) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2942, in append_op attrs=kwargs.get("attrs", None)) File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2129, in __init__ self.desc.infer_shape(self.block.desc) RuntimeError: (NotFound) No Input(Filter) found for Conv operator. [Hint: Expected ctx->HasInput("Filter") == true, but received ctx->HasInput("Filter"):0 != true:1.] (at /paddle/paddle/fluid/operators/conv_op.cc:42) [operator < conv2d > error]

**Comment by ronny1996** [comment]
![image](https://user-images.githubusercontent.com/25691046/228768924-f5397073-bdee-4351-9fc0-f4a0b55ce641.png)
你好，请问下，是不是模型有问题

**Comment by Obiany-Sr** [comment]
> 

请问这句说明模型有什么问题啊

**Comment by ronny1996** [comment]
conv缺少了filter输入

**Comment by Obiany-Sr** [comment]
![20230330202438](https://user-images.githubusercontent.com/125880128/228834998-256d42f2-3296-404a-9306-3f496e5effcb.png)
模型已经经过评估了没有问题，会不会是输入形状输错了？不清楚这InputSpec后面的数字怎么得到

**Comment by yeliang2258** [comment]
辛苦提供一下复现脚本，我这边来看看
