### ISSUE TITLE
[paddle.Tensor.where] 使用方法

### ISSUE THREAD

**Issue by Fancy-hjyp** [PaddlePaddle/Paddle#52337]
### 请提出你的问题 Please ask your question

按照官网对 paddle.Tensor.where 的用法，出现错误，请问应该如何使用这个 API 呢 
官网链接： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/Tensor_cn.html#where-y-name-none
```python
import paddle
a = paddle.to_tensor([0, 1, 2])
b = paddle.to_tensor([2, 3, 0])
c = a.where(b)
print(c)
```
![image](https://user-images.githubusercontent.com/53164956/228756816-22d58f4f-2634-4101-aa14-5d34a7f0ba84.png)

```python
import paddle
a = paddle.to_tensor([0, 1, 2])
b = paddle.to_tensor([2, 3, 0])
c = a.where(a>0, b)
print(c)
```
![image](https://user-images.githubusercontent.com/53164956/228756697-302541c2-1301-473c-ae3b-b69482781e83.png)

**Comment by ronny1996** [comment]
你好，where的输入tensor dtype应该为bool类型，可以使用

paddle.where(a > 0, a, b)
或者 
(a > 0).where(a, b)

**Comment by Fancy-hjyp** [comment]
好的，谢谢~
那官网这里我需要提个PR修复一下吗，还是等官方修复呢
![image](https://user-images.githubusercontent.com/53164956/228789996-b0cb8aa3-5bbc-4f9a-92e0-e8d8cfc2a4ef.png)

**Comment by ronny1996** [comment]
@Tomoko-hjf 你好，欢迎提pr修复一下~
