### ISSUE TITLE
fleet.save_persistables 中的各种mode分别有什么区别呢

### ISSUE THREAD

**Issue by ShaominFan** [PaddlePaddle/Paddle#52345]
### 请提出你的问题 Please ask your question

fleet.save_persistables(self, executor, dirname, main_program=None, mode=0)
fleet.save_persistables(None, path, mode=mode)
fleet.save_persistables(None, model_path, mode=3)
fleet.save_persistables(None, model_path, mode=1)
fleet.save_persistables(None, model_path, mode=2)
各类mod有什么区别呢，不清楚现在paddle 2.x中还会有这样的区别吗，在分布式训练save的时候现在推荐用那种方式save呢

**Comment by ronny1996** [comment]
你好，可以参考这个文档 
https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/io_cn/save_persistables_cn.html#save-persistables
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/load_old_format_model_cn.html#paddle-fluid-io-save-params-save-persistables

**Comment by ShaominFan** [comment]
paddle 1.8.5中 fleet.save_persistables 中的各种mode分别有什么区别呢
