### ISSUE TITLE
 raise ValueError("can't optimize a non-leaf Tensor")

### ISSUE THREAD

**Issue by linnnn1** [PaddlePaddle/Paddle#52343]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/117170721/228764459-1517e34a-3d16-483f-9f1e-4f3248c056f7.png)
使用x2paddle的新功能将pytorch模型转成paddle之后，报错 raise ValueError("can't optimize a non-leaf Tensor")
其中参数的叶子节点：
![image](https://user-images.githubusercontent.com/117170721/228765163-29231f69-d64c-41ef-a3fa-c932d7363ae6.png)
请问该怎么解决呢

**Comment by ronny1996** [comment]
模型里有no-leaf tensor作为可训练参数，应该是转换问题，可以在X2Paddle repo下提个issue
