### ISSUE TITLE
希望Paddle可以支持DirectML

### ISSUE THREAD

**Issue by zhangsilly** [PaddlePaddle/Paddle#52367]
### 需求描述 Feature Description

希望能够支持DirectML，让AMD 的 APU 可以使用显卡加速，降低Paddle的学习门槛

在体验Stable Diffusion的时候，发现 PyTorch、tensorflow都已经支持DirectML了：
https://github.com/microsoft/DirectML#hardware-requirements

**Comment by engineer1109** [comment]
感觉不太可能。没人维护最后还是死掉删代码。

**Comment by engineer1109** [comment]
AMD可以使用rocm

**Comment by zhangsilly** [comment]
> 

rocm不支持APU😓

传统上程序员的电脑也较少配置高端显卡的，但支持DirectX 12的不少，如果能支持DirectML，可以显著降低学习门槛

**Comment by engineer1109** [comment]
你指望BackEnd级别的支持是不可能的，OpenCL的Backend官方都没有做。
或者你用Custom Device，自己编写BackEnd。
且DirectML平台更窄，且only 美国微软平台，做更多的BackEnd不会带来效益（国产化）。
如果你是需要推理，你可以用onnxruntime，Paddle支持套皮onnxruntime的接口。
