### ISSUE TITLE
单机多卡利用fleet分布式训练  训练过程中某worker出core  不能够稳定复现 worker堆栈看不出什么信息

### ISSUE THREAD

**Issue by LeeJuly30** [PaddlePaddle/Paddle#52391]
### 请提出你的问题 Please ask your question

PADDLE版本：paddle-v2.2.1
单机多卡利用fleet分布式训练  训练过程中某worker出core  不能够稳定复现 worker堆栈信息如下：
worker1:
![fe2578039d3a207cf875466599112bcb](https://user-images.githubusercontent.com/31088072/229009452-a6390fe3-8027-4e49-b005-f2185b25163f.png)
worker2:
![dc5081014485ee8d5f83ec419aa803f3](https://user-images.githubusercontent.com/31088072/229009572-f38abe91-a487-42ec-9c51-787088ea0faf.png)
 打印了一些中间变量发现是在反向传播梯度or更新参数时挂掉了

**Comment by danleifeng** [comment]
请问下是单机多卡跑的什么任务呢？怎么启动的呢？有最小复现demo吗？
