### ISSUE TITLE
报错loss can be list only in PS mode

### ISSUE THREAD

**Issue by ShaominFan** [PaddlePaddle/Paddle#52394]
### 请提出你的问题 Please ask your question

背景：abacus平迁paddle1.8 后 尝试升级使用paddle2.4
paddle1.8：  mpirun --wdir ./ -np 2 python trainer_offline_debug.py 'local'
使用paddle2.4后用上述命令报错，loss can be list only in PS mode，
使用python37 -m paddle.distributed.launch --server_num=2 --worker_num=4 trainer_offline_debug.py 报错ValueError: paddle.distributed initialize error, environment variable PADDLE_CURRENT_ENDPOINT is needed, but not set.

想咨询一下paddle 2.4 下，feet分布式训练 本地和集群训练 需要怎么init fleet 以及跑集群任务，和之前1.8版本有什么不一样的地方吗，有demo吗

**Comment by danleifeng** [comment]
请问下paddle1.8使用上有什么问题吗，需要升级2.4的原因是？
目前分布式cpups下业务支持稳定版本是1.8，高版本下cpups目前没有适配过

**Comment by ShaominFan** [comment]
请问分布式gpu ps下适配 paddle2.0以上的版本吗

**Comment by danleifeng** [comment]
适配的
