### ISSUE TITLE
[PHI] Functionalization for Fluid kernel

### ISSUE THREAD

**Issue by From00** [PaddlePaddle/Paddle#52395]
### 问题描述 Please describe your issue
大家好，当前Fluid下有部分算子由于未迁移到新的PHI算子体系，无法具备PHI下函数式算子注册时”记录自身输入输出属性“的能力，既使PHI算子库无法达成统一所有算子的理想状态，也给框架调度体系的优化工作带来较大的负担。我们一共收集了14个需要迁移的算子，欢迎大家提交PR一起对这些算子做迁移改造。

更多详细介绍见 [Call-for-Contributions: Fluid算子函数式迁移专项](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/functionalization_for_fluid_kernel.md)， 本issue用于跟踪记录该项目下各个算子的迁移改造进度。

**注：**
1. 同一个算子的cpu/gpu/xpu kernel以及InferShape尽量由同一个同学进行迁移改造，可直接在本issue下方回复认领。
2. **该任务时间：PR 截止提交时间是5月20日，截止合入时间是5月31日。**
3. **PR 通过 CI 后，在评论里 @From00 进行code review。**
4. 本任务挑战性较大，对于刚接触Paddle开发的同学，建议先在[good first issue](https://github.com/PaddlePaddle/community/tree/master/pfcc#good-first-issue)中挑选一些简单的任务尝试。 欢迎联系花花加入社区，和我们一起[快乐开源](https://github.com/PaddlePaddle/Paddle/issues/48019)！
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39876205/213131273-361d2bb8-ea48-4f62-9603-0b0401f50337.png">

**待迁移算子列表**（整体进度 14/14）
> 按 merge 的时间顺序，排名不分先后：@AndSonder (6) @gouzil (2) @huangjiyi (5)  @GreatV (1)

| 序号 </br> | 算子名称</br> | 认领人 </br>| PR</br> (cpu/gpu kernel )</br> |PR</br> (xpu kernel)</br> | PR</br> (InferShape)</br> | 
| ---------- | ---------------|--------------|------------------------------| ----------------|-------- | 
|  1  |  cudnn_lstm ✅（2023/5/16）| @huangjiyi     |  #53730  | 无需  |   无需 |
|  2  | dequantize ✅（2023/5/15） | @huangjiyi     |  #53739  | 无需  | 无需   |
|  3  | distributed_fused_lamb ✅（2023/5/23）| @huangjiyi     | #53896    |  无需 |  无需  |
|  4  |   fused_attention ✅（2023/4/17） |  @AndSonder    |  #51743  |  #53011 |  无需  |
|  5  |  fused_attention_grad ✅（2023/4/17） |  @AndSonder    | #51909   |  #53011 | 无需   |
|  6  |  fused_batch_norm_act ✅ (2023/05/16) |  @AndSonder   | #53476   | 无需  | 无需   |
|  7  |  fused_batch_norm_act_grad ✅ (2023/05/16) |  @AndSonder   |  #53476  | 无需  | 无需   |
|  8  |  fused_feedforward ✅（2023/4/24）|  @AndSonder |  #53166  | #53196  |  无需  |
|  9  |  fused_feedforward_grad ✅（2023/4/24） |  @AndSonder   | #53166  |  #53196 |  无需  |
|  10  |  fusion_group ✅（2023/5/23）|   @huangjiyi  | #53781    | 无需  | https://github.com/PaddlePaddle/Paddle/pull/53934   |
|  11 |  pow2_decay_with_linear_warmup ✅ (2023/05/12) | @huangjiyi  |  https://github.com/PaddlePaddle/Paddle/pull/53741  | https://github.com/PaddlePaddle/Paddle/pull/53741  |  无需  | 
|  12  | sequence_mask ✅（2023/5/18）| @GreatV     | https://github.com/PaddlePaddle/Paddle/pull/53478   | 无需  |  #53782   |
|  13  |  sequence_pool ✅（2023/4/17）| @gouzil     |  #52750  | 无需 | 无需 |
|  14  |  stft ✅ (2023/05/16) | @gouzil    | [#53517](https://github.com/PaddlePaddle/Paddle/pull/53517)   | 无需  | 无需   |

**Comment by engineer1109** [comment]
我记得 xxx_grad的算子 现在一个也没有吧

**Comment by GreatV** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
10| sequence_mask | @GreatV | #53478 | |

**Comment by huangjiyi** [comment]
| 序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape) |
| ---    |   ---         |  ---       | ---                            | ---                    | ---                    |
| 1      | cudnn_lstm | @huangjiyi | #53730 | 无需 | 无需 |
| 2      | dequantize |  @huangjiyi | #53739 | 无需 | 无需 |
| 3      | distributed_fused_lamb|  @huangjiyi | #53896 | 无需 | 无需 |
| 10  | fusion_group | @huangjiyi | #53781 | 无需 | #53934 |
| 11   | pow2_decay_with_linear_warmup | @huangjiyi | #53741 | #53741 | 无需 |

**Comment by Liyulingyue** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
3| distributed_fused_lamb| @Liyulingyue

**Comment by gouzil** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
11 | sequence_pool | @gouzil | #52680,#52750,#52782 |  - | |

**Comment by sanbuphy** [comment]
认领  2 dequantize

**Comment by jinyouzhi** [comment]
| 序号| 算子名称| 认领人	| PR(cpu/gpu kernel )	| PR(xpu kernel)	| PR(InferShape)|
|--------|--------|--------|--------|--------|---|
| 9| pow2_decay_with_linear_warmup| @jinyouzhi |  |  ||

**Comment by AndSonder** [comment]
|序号|算子名称|认领人|	PR(cpu/gpu kernel )|PR(xpu kernel)|PR(InferShape)|
|-|-|-|-|-|-|		
|6| fused_batch_norm_act |@AndSonder|#53476|-|-|		
|7| fused_batch_norm_act_grad |@AndSonder|#53476|-|-|		
|8| fused_feedforward |@AndSonder|#53166|#53196|-|		
|9| fused_feedforward_grad |@AndSonder|#53166|#53196|-|

**Comment by gouzil** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
14 | stft | @gouzil | #53517 |  - | |

**Comment by luotao1** [comment]
Fluid算子函数式迁移专项已全部完成，感谢参与的小伙伴们！

> 按 merge 的时间顺序，排名不分先后：@AndSonder (6) @gouzil (2) @huangjiyi (4)  @GreatV (1)

欢迎继续参与[快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/48019) 和 [中国软件开源创新大赛：飞桨框架任务挑战赛的其他赛题](https://github.com/PaddlePaddle/Paddle/issues/53172)！
