### ISSUE TITLE
paddlehub 上的 最新模型 运行都报错啊，目标检测 

### ISSUE THREAD

**Issue by alexhmyang** [PaddlePaddle/Paddle#52390]
### bug描述 Describe the Bug

yolov3_mobilenet_v1_coco2017

deeplabv3p_xception65_humanseg

21年的模型 我装的是 cuda11.7  paddle按你们命令装的 ，很多模型都报错

![image](https://user-images.githubusercontent.com/10215059/229008680-6f327a4e-2ab3-4989-833e-217ac0b87061.png)

https://www.paddlepaddle.org.cn/hublist?filter=en_category&value=ImageClassification

paddlehub 上的 最新模型 运行都报错啊，目标检测

**Comment by rainyfly** [comment]
yolov3_mobilenet_v1_coco2017 会报错吗，我这里跑了是正常的额。你贴的报错像是报了显存

**Comment by rainyfly** [comment]
deeplabv3p_xception65_humanseg 这个模型测了一下也能跑，你那边的paddlehub和paddle的版本分别是多少呢，我这里测试时候paddlehub==2.3.1 paddlepaddle-gpu==2.4.2

**Comment by alexhmyang** [comment]
重新装了一遍cuda 和 paddle环境，就好了
