### ISSUE TITLE
AttributeError   Topology

### ISSUE THREAD

**Issue by lvpchen** [PaddlePaddle/Paddle#5240]
Run classification demo:
AttributeError:   Topology  object has no attribute 'serialize_for_inference'

**Comment by ranqiu92** [comment]
I this it may be the Paddle version problem. The serialize_for_inference is added on Seq 11, 2017.
Can you provide and check the version information or git log of the Paddle you have installed?

**Comment by lvpchen** [comment]
My paddle version is 0.10.0.

**Comment by ranqiu92** [comment]
Oh, sorry. The git log of your paddle is also needed, and i want the last commit id.

**Comment by lcy-seso** [comment]
`serialize_for_inference` is introduced by this PR https://github.com/PaddlePaddle/Paddle/pull/4023 . I guess the problem can be solved by updating PaddlePaddle.

**Comment by lvpchen** [comment]
I use command line：git log
commit cdd1da34244bbe0367c7acd1805b01a917518446

And I also use "git pull" to update code, this problem is also exist.

**Comment by ranqiu92** [comment]
Is this commit id related to the Paddle you updated today?
And have you uninstalled the older Paddle before installing the newer one?

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
