### ISSUE TITLE
安装paddle2.3.2gpu版本出错

### ISSUE THREAD

**Issue by hei898** [PaddlePaddle/Paddle#52427]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/79127047/229201611-5714a478-2a67-4925-bde9-3d4129549571.png)
![image](https://user-images.githubusercontent.com/79127047/229201736-fe13aea8-0018-46b3-9872-a69d90da4708.png)
![image](https://user-images.githubusercontent.com/79127047/229202256-bbe58be0-bf95-4ddc-95bb-b99c0bff8ed3.png)

**Comment by hei898** [comment]
![image](https://user-images.githubusercontent.com/79127047/229202797-5fe0aaaf-e1dc-4beb-a1bd-97046bcd7bb8.png)

**Comment by ZzSean** [comment]
你好，根据提供的报错信息来看，安装失败的原因应该是缺少cuBLAS库，建议正确安装cuBLAS库后，添加好相应的LD_LIBRARY_PATH，然后再尝试安装PaddlePaddle

**Comment by hei898** [comment]
好的谢谢，已解决
