### ISSUE TITLE
Wrong documentation - this package is almost impossible to install for users which does not know the basics of CUDA and the whole terminology behind it

### ISSUE THREAD

**Issue by Kammelleon** [PaddlePaddle/Paddle#52442]
### 问题描述 Issue Description

Hi, i just wanted to say thank you. Thank you for making this package almost impossible to install with documentation instructions. Like I've tried installation via PIP with documentation - it just failed. I tried installation via Conda with documentation - also failed. I've made everything 1:1 with documentation and it still failed. Fails on "libcudart.so", fails on cuBLAS fails on every single thing that this documentation requires (99% of errors were connected with CUDA errors). Configuring this via documentation is almost impossible if you don't know the whole CUDA concepts and if you didn't meet any problems with CUDA and its libraries before. Thank you for making this library almost impossible to install without errors EVEN WITH HAVING EXACT VERSION OF EVERY PACKAGE/LIBRARY/PROGRAM YOU'VE INCLUDED WITH THIS DOCUMENTATION.

PS: You've wrote in the documentation that the CUDA 11.7 + cuDNN 8.4.1 will also work but you didn't notice that cuDNN 8.4.1 is not possible to install for CUDA 11.7. It supports up to CUDA 11.6 :) :) :) :) :) :)

It is the worst library to install for Python that I've meet in my whole life.

Worst wishes.

### 版本&环境信息 Version & Environment Information

CUDA VERSIONS TRIED: 11.6, 11.7
PYTHON VERSIONS TRIED: 3.10, 3.9
INSTALLATIONS TRIED: VIA PIP, VIA CONDA
CUDNN TRIED: 8.4.1, 8.4.0
NVIDIA DRIVERS TRIED: 515, 530

STILL FAILS 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 👎🏻 v

**Comment by Kammelleon** [comment]
contents deleted by maintainer

**Comment by jzhang533** [comment]
issue will be closed, since it violates [code of conduct](https://github.com/PaddlePaddle/Paddle/blob/develop/CODE_OF_CONDUCT.md).

**Comment by Kammelleon** [comment]
Wypierdalaj kurwo chińsko

**Comment by Kammelleon** [comment]
W chuju cie mom
