### ISSUE TITLE
为什么trainer.train中没有feeding参数也可以保持数据输入与模型中input的关系

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#5244]
根据paddle文档的介绍，“ Reader返回的数据可以包括多列，我们需要一个Python dict把列 序号映射到网络里的数据层。”
参考：http://book.paddlepaddle.org/01.fit_a_line/index.cn.html

但是我发现在机器翻译例子中，并没有使用feeding方式，没有指定数据与模型input的关系，
参考：https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/train.py
请问程序是如何保证数据与模型input对应一致的呢

**Comment by ranqiu92** [comment]
Paddle会对网络配置进行解析，解析出来的 数据层 的顺序和定义顺序一致，而Paddle默认的input顺序和解析出的数据层的顺序一致。所以在不使用feeding方式时，input顺序须和数据层定义顺序保持一致。
