### ISSUE TITLE
Paddle自定义c++算子打包方式

### ISSUE THREAD

**Issue by aalss** [PaddlePaddle/Paddle#52459]
### 请提出你的问题 Please ask your question

你好，我在根据[自定义c++算子使用文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/custom_op/new_cpp_op_cn.html#setuptools)里面的方法定义自定义设备的自定义c++算子时，遇见了两个问题。
1.使用python setup.py install后可以正常导入和使用自定义算子，但是python setpy.py bdist_wheel打包成whl后再安装，导入自定义算子时就会报下面的错，安装时没有生成对应的py文件。
![image](https://user-images.githubusercontent.com/41711529/229420431-93569bcb-79e7-4f55-9c65-80e243c943b4.png)
所以想问下是不是目前自定义c++算子是不是不支持打包后再使用，以及能否直接将自定义c++算子直接打包进custom_device的插件包里？
2.目前看自定义c++算子都是使用setup.py组织编译的，想知道cpp_extension里面的setup接口是否支持自定义了cmake类的cmdclass参数？目前如果自定义了cmdclass参数的build_ext，cpp_extension里似乎就不会走框架的BuildExtension逻辑了，导致自定义算子没法成功导入。
![image](https://user-images.githubusercontent.com/41711529/229422111-a2542ae4-6e6e-42af-8343-3abb7c9c7f35.png)

**Comment by jiahy0825** [comment]
您好
1. 建议使用官方文档中的 `python setup.py install` 编译方式，这种编译方式自动生成了对应的 py 文件以及 python API 接口。python setpy.py bdist_wheel 的方式则不支持，因此会出现您截图中的报错。
2. setup 接口支持自定义 cmdclass 参数，setup 接口相当于是对 python 已有的 `setuptools.setup` 做了一层封装，对 `setuptools.setup` 中的参数都是支持的，只是如果自定义了 `build_ext` 参数，相当于覆盖了框架内默认的封装方式，此时需要由用户自行实现`build_ext`对应的逻辑。

**Comment by aalss** [comment]
> 您好
> 
> 1. 建议使用官方文档中的 `python setup.py install` 编译方式，这种编译方式自动生成了对应的 py 文件以及 python API 接口。python setpy.py bdist_wheel 的方式则不支持，因此会出现您截图中的报错。
> 2. setup 接口支持自定义 cmdclass 参数，setup 接口相当于是对 python 已有的 `setuptools.setup` 做了一层封装，对 `setuptools.setup` 中的参数都是支持的，只是如果自定义了 `build_ext` 参数，相当于覆盖了框架内默认的封装方式，此时需要由用户自行实现`build_ext`对应的逻辑。

好的，谢谢。那还想请问下有没有办法将自定义算子直接集成到custom_device的插件包里呢？就是放到[新硬件接入](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/custom_device_docs/custom_device_example_cn.html#setuptools)里面的setup.py一起。如果只是python install的方式安装，用户需要每次拷贝代码后执行python install的命令才能够使用自定义算子，没有打包成whl使用方便，目前是想将自定义C++算子集成到插件包，然后导入相应的模块就可以使用自定义算子，这种方式是否可行呢？

**Comment by jiahy0825** [comment]
您好，非常抱歉，使用 whl 打包这个项点暂未支持，核心问题仍是加载 whl 包后，没有对应的 python API，所以集成到自定义硬件里也是没办法使用的。（P.S. 自定义算子机制仅保证源码级别的兼容，不保证二进制级别的兼容（[自定义 C++算子-概述](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/custom_op/new_cpp_op_cn.html#gaishu)），因此如果使用 whl 包安装自定义算子，无法保证兼容性。）


感谢反馈这个需求点，后续如果有关于这个项点的最新消息，再来和您同步。

**Comment by aalss** [comment]
> 您好，非常抱歉，使用 whl 打包这个项点暂未支持，核心问题仍是加载 whl 包后，没有对应的 python API，所以集成到自定义硬件里也是没办法使用的。（P.S. 自定义算子机制仅保证源码级别的兼容，不保证二进制级别的兼容（[自定义 C++算子-概述](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/custom_op/new_cpp_op_cn.html#gaishu)），因此如果使用 whl 包安装自定义算子，无法保证兼容性。）
> 
> 感谢反馈这个需求点，后续如果有关于这个项点的最新消息，再来和您同步。

好的，了解了，非常感谢您的解答。
