### ISSUE TITLE
NotFoundError: Input variable(xxx) cannot be found in scope for operator 'Fetch'.

### ISSUE THREAD

**Issue by zhangpeng-HEBUT** [PaddlePaddle/Paddle#52458]
### 请提出你的问题 Please ask your question

代码如下：
`def predict(args,
            exe,
            test_program,
            test_pyreader,
            graph_vars,
            dev_count=1,
            output_item=0,
            output_file_name='emb',
            hidden_size=768):

    test_pyreader.start()
    fetch_list = [graph_vars["q_rep"].name, graph_vars["p_rep"].name,]
    para_embs = []

    batch_id = 0
    while True:
        try:
            batch_id += 1
            if batch_id % 500 == 0:
                log.info("complete batch %s" % batch_id)
            q_rep, p_rep = exe.run(program=test_program,
                                   # fetch_list=[graph_vars["q_rep"].name, graph_vars["p_rep"].name])
                                            fetch_list=fetch_list)

            if output_item == 0:
                for item in q_rep:
                    para_embs.append(np.array(item, dtype='float32'))
            elif output_item == 1:
                for item in p_rep:
                    para_embs.append(np.array(item, dtype='float32'))

        except fluid.core.EOFException:
            test_pyreader.reset()
            break`
错误日志如下：
`Traceback (most recent call last):
  File "./src/inference_de.py", line 130, in <module>
    main(args)
  File "./src/inference_de.py", line 123, in main
    hidden_size=ernie_config['hidden_size'])
  File "/data/c21/zp/PAIR/model/src/finetune/dual_encoder_infer.py", line 158, in predict
    fetch_list=fetch_list)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1117, in run
    six.reraise(*sys.exc_info())
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/six.py", line 719, in reraise
    raise value
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1114, in run
    return_merged=return_merged)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1245, in _run_impl
    use_program_cache=use_program_cache)
  File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1335, in _run_program
    [fetch_var_name])
RuntimeError: In user code:

    File "./src/inference_de.py", line 130, in <module>
      main(args)
    File "./src/inference_de.py", line 123, in main
      hidden_size=ernie_config['hidden_size'])
    File "/data/c21/zp/PAIR/model/src/finetune/dual_encoder_infer.py", line 158, in predict
      fetch_list=fetch_list)
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1114, in run
      return_merged=return_merged)
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1245, in _run_impl
      use_program_cache=use_program_cache)
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1320, in _run_program
      fetch_var_name=fetch_var_name)
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/executor.py", line 647, in _add_feed_fetch_ops
      attrs={'col': i})
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2970, in append_op
      attrs=kwargs.get("attrs", None))
    File "/data/anaconda3/envs/zpP37/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2042, in __init__
      for frame in traceback.extract_stack():

    NotFoundError: Input variable(squeeze_0.tmp_0) cannot be found in scope for operator 'Fetch'.Confirm that you have used the fetch `Variable` format instead of the string literal('squeeze_0.tmp_0') in `fetch_list` parameter when using `executor.run` method. In other words, the format of `executor.run(fetch_list=[fetch_var])`(fetch_var is a Variable) is recommended.
      [Hint: fetch_var should not be null.] (at /paddle/paddle/fluid/operators/controlflow/fetch_op.cc:87)
      [operator < fetch > error]`
其中fetch_list是有数据的，所有想请教我应该如何解决这个问题呢？paddle版本：paddlepaddle-gpu 2.1.3，cuda：10.1，python：3.7

**Comment by thisjiang** [comment]
你好，请问Paddle升级至2.4.2后还会遇到这个问题么？

安装指南见：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

**Comment by zhangpeng-HEBUT** [comment]
> 你好，请问Paddle升级至2.4.2后还会遇到这个问题么？
> 
> 安装指南见：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

您好，我升级paddle版本后，又出现了如下错误：
`RuntimeError: (NotFound) squeeze_0.tmp_0 not in VariableScope.
  [Hint: Expected HasVar(name) == true, but received HasVar(name):0 != true:1.] (at /paddle/paddle/fluid/framework/new_executor/new_executor_defs.cc:674)
`
其中squeeze_0.tmp_0是fetch_list中的第一个变量

**Comment by thisjiang** [comment]
Hi~请问可以找到个最小复现代码么？我这边复现下

**Comment by zhangpeng-HEBUT** [comment]
> Hi~请问可以找到个最小复现代码么？我这边复现下

很抱歉，由于我是个新手，我不太确定哪一部分可以作为最小复现代码，我复现的模型是这篇：https://github.com/PaddlePaddle/RocketQA/tree/main/research/PAIR_ACL2021#dual-encoder-inference。其中报错文件的路径是/src/dual_encoder_infer.py的def predict中的`    while True:
        try:
            batch_id += 1
            if batch_id % 500 == 0:
                log.info("complete batch %s" % batch_id)
            q_rep, p_rep = exe.run(program=test_program,
                                   # fetch_list=[graph_vars["q_rep"].name, graph_vars["p_rep"].name])
                                            fetch_list=fetch_list)`
很抱歉给您带来了麻烦。

**Comment by zhangpeng-HEBUT** [comment]
> Hi~请问可以找到个最小复现代码么？我这边复现下

很抱歉，由于我是个新手，我不太确定哪一部分可以作为最小复现代码，我复现的模型是这篇：https://github.com/PaddlePaddle/RocketQA/tree/main/research/PAIR_ACL2021#dual-encoder-inference  。 其中报错文件的路径是/model/src/dual_encoder_infer.py的def predict中的
很抱歉给您带来了麻烦。而 True： try： batch_id += 1 如果 batch_id % 500 == 0： log.info（“完成批处理 %s” % batch_id） q_rep， p_rep = exe.run（program=test_program， # fetch_list=[graph_vars[“q_rep”].name， graph_vars[“p_rep”].name]） fetch_list=fetch_list）

**Comment by zhangpeng-HEBUT** [comment]
> Hi~请问可以找到个最小复现代码么？我这边复现下

很抱歉，由于我是个新手，我不太确定哪一部分可以作为最小复现代码，我复现的模型是这篇：https://github.com/PaddlePaddle/RocketQA/tree/main/research/PAIR_ACL2021#dual-encoder-inference 。 其中报错文件的路径是/model/src/dual_encoder_infer.py的def predict方法中的
`    while True:
        try:
            batch_id += 1
            if batch_id % 500 == 0:
                log.info("complete batch %s" % batch_id)
            q_rep, p_rep = exe.run(program=test_program,
                                            fetch_list=fetch_list)`
很抱歉给您带来了麻烦。

**Comment by thisjiang** [comment]
Hi~我这边可能环境有点问题，没能跑起来。不过我看文档中写的Paddle版本是1.8，请问有试过这个版本么？
<img width="447" alt="image" src="https://user-images.githubusercontent.com/31386411/229458031-a3bf6803-9ada-4af8-8204-cd3ac615590c.png">

**Comment by zhangpeng-HEBUT** [comment]
> Hi~我这边可能环境有点问题，没能跑起来。不过我看文档中写的Paddle版本是1.8么，请问有试过这个版本？ <img alt="图像" width="447" src="https://user-images.githubusercontent.com/31386411/229458031-a3bf6803-9ada-4af8-8204-cd3ac615590c.png">

感谢您的回复，这个版本我试过，当时的问题是说我的版本不对应，因为我的cuda版本是11.2，而paddle1.8版本不支持cuda11.2版本的

**Comment by thisjiang** [comment]
Hi~这个代码写的时候Paddle版本可能太老了，很多功能在之后的版本中已经不兼容升级了。您可以去该repo下提Issue问问，或者看看这个同学转的Paddle Inference 版本？：https://github.com/PaddlePaddle/RocketQA/issues/73

**Comment by zhangpeng-HEBUT** [comment]
> Hi~这个代码写的时候Paddle版本可能太老了，很多功能在之后的版本中已经不兼容升级了。您可以去该repo下提Issue问问，或者看看这个同学转的Paddle Inference 版本？：[PaddlePaddle/RocketQA#73](https://github.com/PaddlePaddle/RocketQA/issues/73)

好的，感谢您的回复，祝身体健康，工作顺利！
