### ISSUE TITLE
Cannot acquire graphs/modify passes when using `Custom Device Plugin` mode to support Intel-GPU

### ISSUE THREAD

**Issue by BaihuiJin** [PaddlePaddle/Paddle#52452]
Hi, we are supporting both training and inference on Intel GPUs for PaddlePaddle. We realized that current API provided by custom device mode doesn't include graph API/ pass API, which make it hard for us to implement fusion and other optimizations. 
Is there any solutions for us to acquire graph and support fusion or other graph level transformation?

**Comment by qili93** [comment]
hi, @BaihuiJin 

Yes, current now Paddle custom device not support pass fusion via plugin way. And we are under planning to provide a new method to support this in roadmap and plan to deliver in Q2 or Q3.

Please kindly help to confirm if the following two PRs can resolve your problem. And we will share our roadmap plan of pass fusion via custom device plugin if determined, thanks :)

https://github.com/PaddlePaddle/Paddle/pull/35602 - Pyhon Pass
https://github.com/PaddlePaddle/Paddle/pull/36095 - C++ Pass

**Comment by BaihuiJin** [comment]
Hi, Qi
Thanks for replying. We've gone through these PRs. As we understanded the intension for generate_pass design is to achieve following goals(using C++ interface as example):
1.  Using `OP_` to represent a op node, using `SUBGRAPH_` to represent a pattern, using `VAR_` to represent i/o parameters for `OP_` and `SUBGRAPH_`, and furtherly the dataflow within the pattern.
2. Given a ir::Graph, user can define a pattern to recognize (says SUB1), and define another pattern to replace (says SUB2), and replace SUB1 with SUB2 on the graph and call a different (fused or transformed) kernel.

We think these are great designs as it simplified pass implementation and users does not need to visit the entire graph themselves. But these simplifications does brought up some concerns.
1. On the lowest level, how do we custom our own kernel for transformed kernel? Or do we have to use fused patterns defined by paddle main fwk and implement corresponding kernels like unfused `matmul_kernel.cc`? If so, the developing flexibility would be very limited.
2. Graph transformation procedures can be as simple as conv-mul-add-add, or as complicated as merge multiple matrices horizontally for matmul or even adjust global calculation orders if some patterns/shapes are detected. I'm not sure if using local pattern replacement only without the ability to visit the whole graph can cover these more complicate cases. Is it possible that paddle could provide a complete gragh and ability to visit/modify/check connection to expand the fusion ability?
3. There are some transformations that are shape/format relative, like reorder or transpose, I don't think these infos are provided by these two PRs. (maybe we missed them)
4. Some times one pattern can hit multiple passes, or needs to be fuse many time. In the most common case: conv-deq-relu-quant pattern in inference situation, when it's translated into basic ops, it would be like: conv-mul-relu-mul, but in other case it could be like conv-mul-mul, ideally all element-wise op can be fused into one op, but do we have to implement multiple passes for every different case? Furtherly do we have to implement multiple c++ kernels for them? 
5. Could generate_pass aware different devices as different backends might have different way to impl fusion patterns.
These are some potential risks that we can think of currently. Please correct me if I'm wrong, thanks again!

**Comment by KevinYuk** [comment]
Hi @qili93,

Could you please help include the corresponding developer to check the questions above?

Thanks.
