### ISSUE TITLE
Nightly build Linux平台GPU wheel包编译cmake命令

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#52477]
请问PaddlePaddle在GPU上Nightly build的具体cmake编译命令是什么？

比如这个包：paddlepaddle_gpu-0.0.0.post117-cp38-cp38-linux_x86_64.whl

**Comment by thisjiang** [comment]
你好，源码编译可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html
CMake选项参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile

建议使用官方提供的Docker环境进行编译避免环境问题引发的编译报错问题

**Comment by tiandou-tangdou** [comment]
> 你好，源码编译可参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html CMake选项参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile
> 
> 建议使用官方提供的Docker环境进行编译避免环境问题引发的编译报错问题


@thisjiang 谢谢，这些有看过，是想了解在编译GPU Nightly build包时具体的cmake编译选项开关情况，能帮提供下吗？

**Comment by XieYunshen** [comment]
cmake编译选项如下:
`cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_CUDNN_DSO=OFF -DWITH_TENSORRT=ON -DWITH_ROCM=OFF -DWITH_CINN=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON -DWITH_AVX=ON -DCUDA_ARCH_NAME=All -DNEW_RELEASE_PYPI=ON -DNEW_RELEASE_ALL=OFF -DNEW_RELEASE_JIT=OFF -DWITH_PYTHON=ON -DCUDNN_ROOT=/usr/ -DWITH_TESTING=OFF -DWITH_COVERAGE=OFF -DWITH_INCREMENTAL_COVERAGE=OFF -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_CONTRIB=ON -DWITH_INFERENCE_API_TEST=ON -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo -DPY_VERSION=3.8 -DCMAKE_INSTALL_PREFIX=/paddle/build -DWITH_PSCORE=ON -DWITH_PSLIB=OFF -DWITH_GLOO=ON -DLITE_GIT_TAG=release/v2.10 -DWITH_XPU=OFF -DWITH_IPU=OFF -DWITH_CNCL=OFF -DXPU_SDK_ROOT= -DWITH_LITE=OFF -DWITH_XPU_BKCL=OFF -DWITH_ARM=OFF -DWITH_STRIP=ON -DON_INFER=ON -DWITH_HETERPS=OFF -DWITH_GPU_GRAPH=OFF -DWITH_FLUID_ONLY=OFF -DWITH_RECORD_BUILDTIME=OFF -DWITH_UNITY_BUILD=OFF -DWITH_ONNXRUNTIME=OFF -DWITH_CUDNN_FRONTEND=OFF`

**Comment by tiandou-tangdou** [comment]
@XieYunshen 多谢
