### ISSUE TITLE
求问：TypeError: __init__() got an unexpected keyword argument 'paddle_dtype'

### ISSUE THREAD

**Issue by alice1883** [PaddlePaddle/Paddle#52484]
### 请提出你的问题 Please ask your question

在https://aistudio.baidu.com/aistudio/index网站
使用和好几个novelai的项目，全部出现了：TypeError: __init__() got an unexpected keyword argument 'paddle_dtype'
这个错误，没办法解决啊？？
FAQ内没有 'paddle_dtype' 相关的解决办法......
使用的项目包括：
https://aistudio.baidu.com/aistudio/projectdetail/5866872?contributionType=1
https://aistudio.baidu.com/aistudio/projectdetail/5871361?contributionType=1
https://aistudio.baidu.com/aistudio/projectdetail/5680370?contributionType=1
https://aistudio.baidu.com/aistudio/projectdetail/4890925?contributionType=1
......芒果自用NovelAI 相关就开了好几个项目，都不可以用，更新库也不行，抱歉刚开始学习什么都不会，这个问题对我来说就非常困难了 TUT 

[2023-04-03 23:23:13,082] [    INFO] - loading configuration file NovelAI_latest_ab21ba3c_paddle/text_encoder/config.json
[2023-04-03 23:23:13,086] [    INFO] - Model config CLIPTextConfig {
  "architectures": [
    "CLIPTextModel"
  ],
  "attention_dropout": 0.0,
  "bos_token_id": 0,
  "dropout": 0.0,
  "eos_token_id": 2,
  "hidden_act": "quick_gelu",
  "hidden_size": 768,
  "initializer_factor": 1.0,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-05,
  "max_position_embeddings": 77,
  "model_type": "clip_text_model",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 1,
  "paddlenlp_version": null,
  "projection_dim": 768,
  "return_dict": true,
  "vocab_size": 49408
}

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
~/ui.py in on_run_button_click(self, b)
    111         with self.run_button_out:
    112             clear_output()
--> 113             self.pipeline.run(get_widget_extractor(self.widget_opt), task = self.task)
    114 
    115 

~/utils.py in run(self, opt, task)
    222 
    223     def run(self, opt, task = 'txt2img'):
--> 224         self.from_pretrained(precision = opt.precision)
    225         seed = None if opt.seed == -1 else opt.seed
    226 

~/utils.py in from_pretrained(self, precision, verbose, force)
    178         # text to image
    179         # do not directly load with fp16, since certain operators only support fp32
--> 180         self.pipe = StableDiffusionPipeline.from_pretrained(model)
    181 
    182         if vae is not None:

~/diffusers_paddle/pipeline_utils.py in from_pretrained(cls, pretrained_model_name_or_path, **kwargs)
    379                 # check if the module is in a subdirectory
    380                 if os.path.isdir(os.path.join(cached_folder, name)):
--> 381                     loaded_sub_model = load_method(os.path.join(cached_folder, name), **loading_kwargs)
    382                 else:
    383                     # else load from the root directory

~/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py in from_pretrained(cls, pretrained_model_name_or_path, from_hf_hub, subfolder, *args, **kwargs)
    483         if cls.constructed_from_pretrained_config():
    484             return cls.from_pretrained_v2(
--> 485                 pretrained_model_name_or_path, from_hf_hub=from_hf_hub, subfolder=subfolder, *args, **kwargs
    486             )
    487 

~/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py in from_pretrained_v2(cls, pretrained_model_name_or_path, from_hf_hub, subfolder, *args, **kwargs)
   1360         # 3. init the model
   1361         init_args = config["init_args"] or ()
-> 1362         model = cls(config, *init_args, **model_kwargs)
   1363 
   1364         loaded_state_dict_keys = list(model_state_dict.keys())

~/.data/webide/pip/lib/python3.7/site-packages/paddlenlp/transformers/utils.py in __impl__(self, *args, **kwargs)
    168                 pre_init_func(self, init_func, *args, **kwargs)
    169             # keep full configuration
--> 170             init_func(self, *args, **kwargs)
    171             # registed helper by `post_init_func`
    172             if post_init_func:

TypeError: __init__() got an unexpected keyword argument 'paddle_dtype'

**Comment by thisjiang** [comment]
这看上去是PaddleNLP出的错，建议前往PaddleNLP提Issue，好像挺多类似问题的，不过解决方案各不相同：https://github.com/PaddlePaddle/PaddleNLP/issues

**Comment by alice1883** [comment]
好的非常感谢！我去试试
