### ISSUE TITLE
import paddle 调用print打印输出，为什么会打印输出两遍

### ISSUE THREAD

**Issue by Ares107** [PaddlePaddle/Paddle#52493]
参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/linux-conda.html
在ubuntu18.04 conda 环境下安装了paddle, python3版本为3.9.16, paddle版本为2.4.2, 编写测试程序
```
import numpy as np
import os
import paddle

print("Hello, World")
```
运行该python程序, 控制台打印输出两遍"Hello, World", 注释掉"import paddle", 则只打印一遍"Hello, World",
请问这个现象是否正常，是什么原因导致的，有无解决方案?

**Comment by wangzhen38** [comment]
![截屏2023-04-04 11 40 15](https://user-images.githubusercontent.com/41941775/229681335-136fd290-28c1-4379-8a34-b323333cf372.png)
按你所说，确实不正常，但我并没有复现你说的问题，或者你可以尝试下别的paddle版本？

**Comment by Ares107** [comment]
![1680579862963_958C3482-C185-4aac-B064-83962783B655](https://user-images.githubusercontent.com/18276708/229681955-ca4c2430-0d88-4ee7-bc5b-94f86e5cb144.png)

请在控制台，使用python解释器调用python脚本，执行可以复现该问题;

**Comment by wangzhen38** [comment]
> 

执行脚本我这边也是没问题的，你换个paddle版本后，也存在这样的问题吗

**Comment by Ares107** [comment]
是的，使用paddle  2.4.0 也是这个现象; 且在检查是否安装成功时，提示这个错误;

![1680582100851_7B97425F-716F-4f1f-9AA6-A035B9FF5592](https://user-images.githubusercontent.com/18276708/229686328-8ff44e78-e104-4791-872b-272233d0aff3.png)

**Comment by wangzhen38** [comment]
感觉还是你安装的不太对，试试执行下列命令呢
`pip uninstall paddlepaddle `
`python -m pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple`

**Comment by Ares107** [comment]
感觉应该跟我ubuntu(18.04)环境有关系, 我在ubuntu18.04 上使用conda和pip安装paddle 目前运行都是这个现象(像是连续运行两次一样, 不是重复打印); 我在另外一台电脑上(Ubuntu20.04)上面 使用pip安装是正常的.
