### ISSUE TITLE
关于 conditional_block 映射到 TRT 的问题

### ISSUE THREAD

**Issue by Young-Flash** [PaddlePaddle/Paddle#52498]
### 请提出你的问题 Please ask your question

想请教关于 conditional_block 算子映射到 TRT 的问题：TRT 中对应功能的是 [If](https://docs.nvidia.com/deeplearning/tensorrt/operators/docs/If.html)，要求设置 trueSubgraph 和 falseSubgraph。但是 paddle 中 cond 算子中是由两个独立的 ConditionalBlock 构成的，貌似不能在重载 operator() 时一次性映射到 trueSubgraph 和 falseSubgraph ？另外一个问题就是 cond 算子中的分支操作包含了 TRT 中没有的算子应该怎么办呢？

**Comment by xiaoxiaohehe001** [comment]
目前 conditional_block 还无法使用完整的 trt 推理，所以尽可能在组网中避免 conditional_block 的使用。
