### ISSUE TITLE
Inference部分，存在预测不相干的内容

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#525]
Inference部分，存在预测不相干的内容。

![image](https://cloud.githubusercontent.com/assets/12882811/20423415/0c1d1c2e-adab-11e6-8d1f-ff316b26d721.png)

**Comment by reyoung** [comment]
不太理解这个issue是什么意思？ @beckett1124

**Comment by reyoung** [comment]
Closed due to no response for long time.
