### ISSUE TITLE
paddle在飞腾d2000+openeuler下源码安装报错

### ISSUE THREAD

**Issue by gkjmax** [PaddlePaddle/Paddle#52519]
### 问题描述 Issue Description

如题，飞腾d2000和openeuler22.03环境下，安装paddle2.4
参考教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#anchor-0

执行cmake时报错：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Paddle host system: , version: 
-- Found Paddle host system's CPU: 8 cores
EXP_CUDA_MODULE_LOADING_LAZY only works with GPU
-- CXX compiler: /usr/local/bin/c++, version: GNU 9.4.0
-- C compiler: /usr/local/bin/gcc, version: GNU 9.4.0
-- AR tools: /usr/bin/ar
-- Do not have AVX2 intrinsics and disabled MKL-DNN.
-- warp-ctc library: /home/jss/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- warp-rnnt library: /home/jss/Paddle/build/third_party/install/warprnnt/lib/libwarprnnt.so
-- Found OpenBLAS (include: /usr/include/openblas, library: /usr/lib64/libopenblas.so)
-- Found lapack in OpenBLAS (include: /usr/include/openblas)
-- CBLAS_PROVIDER: OPENBLAS
-- Protobuf protoc executable: /home/jss/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /home/jss/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /home/jss/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /home/jss/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 21.12
CMake Error at cmake/python_module.cmake:56 (message):
  Please input Python version, eg:3.7 or 3.8 and so on
Call Stack (most recent call first):
  cmake/external/python.cmake:17 (check_py_version)
  cmake/third_party.cmake:305 (include)
  CMakeLists.txt:604 (include)

-- Configuring incomplete, errors occurred!
See also "/home/jss/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/home/jss/Paddle/build/CMakeFiles/CMakeError.log".

### 版本&环境信息 Version & Environment Information

paddle：2.4
cpu:飞腾d2000
python：3.9
系统:openeuler22.03

**Comment by risemeup1** [comment]
-DPY_VERSION=3?这样的写法不对，建议改成-DPY_VERSION=3.9
