### ISSUE TITLE
启动提示：analysis_config.cc:110] Please use PaddlePaddle with GPU version.

### ISSUE THREAD

**Issue by zhang7249** [PaddlePaddle/Paddle#52528]
在paddleX中创建了“目标检测”并训练好了模型，使用paddlepaddle-gpu进行部署，推理时间很慢，训练素材是6000*4000的图片，传入图片分辨率是 1960*1080 ，推理过程非常的慢。

并且在进程启动时，提示 analysis_config.cc:110] Please use PaddlePaddle with GPU version.

### **安装的是paddlepaddle-gpu的版本。**
C:\Users\ASUS>pip list
Package            Version
------------------ -------------
astor              0.8.1
certifi            2022.12.7
charset-normalizer 3.1.0
decorator          5.1.1
dnspython          2.3.0
idna               3.4
numpy              1.21.6
opencv-python      4.7.0.72
opt-einsum         3.3.0
paddle-bfloat      0.1.7
paddlepaddle-gpu   2.4.2.post112
Pillow             9.5.0
pip                23.0.1
protobuf           3.20.0
pymongo            4.3.3
PyMySQL            1.0.2
requests           2.28.2
setuptools         47.1.0
six                1.16.0
some-package       0.1
urllib3            1.26.15

### **机器是：windows+ CPU AMD Ryzen 9 5950X 16-Core Processor  + GPU 0 NVIDIA GeForce RTX 3060** 

**### 源代码：**
import shutil
import time

import numpy as np
import argparse
import cv2
from PIL import Image
import os

from paddle.inference import Config
from paddle.inference import create_predictor
from paddle.inference import PrecisionType

from utils import preprocess, draw_bbox

def init_predictor(args):
    if args.model_dir != "":
        config = Config(args.model_dir)
    else:
        config = Config(args.model_file, args.params_file)

    config.enable_memory_optim()
    config.use_gpu()
    config.enable_use_gpu(1000, 0)

    if args.run_mode == "trt_fp32":
        config.enable_tensorrt_engine(
            workspace_size=1 << 30,
            max_batch_size=1,
            min_subgraph_size=5,
            precision_mode=PrecisionType.Float32,
            use_static=False,
            use_calib_mode=False,
        )
    elif args.run_mode == "trt_fp16":
        config.enable_tensorrt_engine(
            workspace_size=1 << 30,
            max_batch_size=1,
            min_subgraph_size=5,
            precision_mode=PrecisionType.Half,
            use_static=False,
            use_calib_mode=False,
        )
    elif args.run_mode == "trt_int8":
        config.enable_tensorrt_engine(
            workspace_size=1 << 30,
            max_batch_size=1,
            min_subgraph_size=5,
            precision_mode=PrecisionType.Int8,
            use_static=False,
            use_calib_mode=True,
        )
    if args.use_dynamic_shape:
        names = [
            "image",
            "batch_norm_45.tmp_2",
            "deformable_conv_0.tmp_0",
            "relu_44.tmp_0",
            "deformable_conv_1.tmp_0",
            "relu_23.tmp_0",
            "relu_47.tmp_0",
            "deformable_conv_2.tmp_0",
        ]
        min_input_shape = [
            [1, 3, 608, 608],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 512, 76, 76],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
        ]
        max_input_shape = [
            [1, 3, 608, 608],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 512, 76, 76],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
        ]
        opt_input_shape = [
            [1, 3, 608, 608],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
            [1, 512, 76, 76],
            [1, 2048, 19, 19],
            [1, 512, 19, 19],
        ]

        config.set_trt_dynamic_shape_info(
            {
                names[0]: min_input_shape[0],
                names[1]: min_input_shape[1],
                names[2]: min_input_shape[2],
                names[3]: min_input_shape[3],
                names[4]: min_input_shape[4],
                names[5]: min_input_shape[5],
                names[6]: min_input_shape[6],
                names[7]: min_input_shape[7],
            },
            {
                names[0]: max_input_shape[0],
                names[1]: max_input_shape[1],
                names[2]: max_input_shape[2],
                names[3]: max_input_shape[3],
                names[4]: max_input_shape[4],
                names[5]: max_input_shape[5],
                names[6]: max_input_shape[6],
                names[7]: max_input_shape[7],
            },
            {
                names[0]: opt_input_shape[0],
                names[1]: opt_input_shape[1],
                names[2]: opt_input_shape[2],
                names[3]: opt_input_shape[3],
                names[4]: opt_input_shape[4],
                names[5]: opt_input_shape[5],
                names[6]: opt_input_shape[6],
                names[7]: opt_input_shape[7],
            },
        )

    predictor = create_predictor(config)
    return predictor

def run(predictor, img):
    # copy img data to input tensor
    input_names = predictor.get_input_names()
    for i, name in enumerate(input_names):
        input_tensor = predictor.get_input_handle(name)
        input_tensor.reshape(img[i].shape)
        input_tensor.copy_from_cpu(img[i])

    # do the inference
    predictor.run()

    results = []
    # get out data from output tensor
    output_names = predictor.get_output_names()
    for i, name in enumerate(output_names):
        output_tensor = predictor.get_output_handle(name)
        output_data = output_tensor.copy_to_cpu()
        results.append(output_data)
    return results

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--model_file",
        type=str,
        default="./inference_model/model.pdmodel",
        help="Model filename, Specify this when your model is a combined model.",
    )
    parser.add_argument(
        "--params_file",
        type=str,
        default="./inference_model/model.pdiparams",
        help="Parameter filename, Specify this when your model is a combined model.",
    )
    parser.add_argument(
        "--model_dir",
        type=str,
        default="",
        help="Model dir, If you load a non-combined model, specify the directory of the model.",
    )
    parser.add_argument(
        "--run_mode",
        type=str,
        default="",
        help="Run_mode which can be: trt_fp32, trt_fp16, trt_int8 and gpu_fp16.",
    )
    parser.add_argument(
        "--use_dynamic_shape",
        type=int,
        default=0,
        help="Whether use trt dynamic shape.",
    )
    return parser.parse_args()

if __name__ == "__main__":

    args = parse_args()
    img_name = "DJI_0001.JPG"
    save_img_name = "res.JPG"
    im_size = 608
    pred = init_predictor(args)
    video = cv2.VideoCapture("人.MP4")
    result_path = 'save_result/'
    shutil.rmtree(result_path)
    if not os.path.exists(result_path):
        os.makedirs(result_path)
    success, frame = video.read()
    i = 0
    while success:
        i = i + 1
        # if not i % 1000 == 0:
        #     success, frame = video.read()
        #     continue
        startTime = (int(round(time.time() * 1000)))
        cv2.imwrite(os.path.join(result_path, str(i) + '.png'), frame)
        endTime1 = (int(round(time.time() * 1000)))
        img = frame
        data = preprocess(img, im_size)
        scale_factor = (
            np.array([im_size * 1.0 / img.shape[0], im_size * 1.0 / img.shape[1]])
            .reshape((1, 2))
            .astype(np.float32)
        )
        im_shape = np.array([im_size, im_size]).reshape((1, 2)).astype(np.float32)
        result = run(pred, [im_shape, data, scale_factor])
        endTime2 = (int(round(time.time() * 1000)))
        img = Image.open(result_path + str(i) + '.png').convert("RGB")
        draw_bbox(img, result[0], save_name=result_path + str(i) + '.png')
        endTime3 = (int(round(time.time() * 1000)))
        # cv2.imwrite(os.path.join(result_path, str(i) + '.png'), img)
        success, frame = video.read()
        print("i=", i)
        print("取帧时间", endTime1 - startTime)
        print("算法处理时间", endTime2 - endTime1)
        print("画框时间", endTime3 - endTime2)

**### 下面是完整的启动日志：**

PyDev console: starting.
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
runfile('C:\\Users\\ASUS\\PycharmProjects\\pythonProject\\QicheTuili.py', wdir='C:\\Users\\ASUS\\PycharmProjects\\pythonProject')
E0404 18:00:55.468547 33640 analysis_config.cc:110] Please use PaddlePaddle with GPU version.
e[1me[35m--- Running analysis [ir_graph_build_pass]e[0m
e[1me[35m--- Running analysis [ir_analysis_pass]e[0m
e[32m--- Running IR pass [simplify_with_basic_ops_pass]e[0m
e[32m--- Running IR pass [layer_norm_fuse_pass]e[0m
e[37m---    Fused 0 subgraphs into layer_norm op.e[0m
e[32m--- Running IR pass [attention_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [seqconv_eltadd_relu_fuse_pass]e[0m
e[32m--- Running IR pass [seqpool_cvm_concat_fuse_pass]e[0m
e[32m--- Running IR pass [mul_lstm_fuse_pass]e[0m
e[32m--- Running IR pass [fc_gru_fuse_pass]e[0m
e[37m---    fused 0 pairs of fc gru patternse[0m
e[32m--- Running IR pass [mul_gru_fuse_pass]e[0m
e[32m--- Running IR pass [seq_concat_fc_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_squeeze2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_reshape2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_flatten2_matmul_fuse_pass]e[0m
e[32m--- Running IR pass [matmul_v2_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_mul_pass]e[0m
I0404 18:00:55.695583 33640 fuse_pass_base.cc:59] ---  detected 4 subgraphs
e[32m--- Running IR pass [gpu_cpu_map_matmul_v2_to_matmul_pass]e[0m
e[32m--- Running IR pass [matmul_scale_fuse_pass]e[0m
e[32m--- Running IR pass [gpu_cpu_map_matmul_to_mul_pass]e[0m
e[32m--- Running IR pass [fc_fuse_pass]e[0m
I0404 18:00:55.720584 33640 fuse_pass_base.cc:59] ---  detected 4 subgraphs
e[32m--- Running IR pass [repeated_fc_relu_fuse_pass]e[0m
e[32m--- Running IR pass [squared_mat_sub_fuse_pass]e[0m
e[32m--- Running IR pass [conv_bn_fuse_pass]e[0m
I0404 18:00:55.820583 33640 fuse_pass_base.cc:59] ---  detected 53 subgraphs
e[32m--- Running IR pass [conv_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_bn_fuse_pass]e[0m
e[32m--- Running IR pass [conv_transpose_eltwiseadd_bn_fuse_pass]e[0m
e[32m--- Running IR pass [is_test_pass]e[0m
e[32m--- Running IR pass [constant_folding_pass]e[0m
e[32m--- Running IR pass [runtime_context_cache_pass]e[0m
e[1me[35m--- Running analysis [ir_params_sync_among_devices_pass]e[0m
e[1me[35m--- Running analysis [adjust_cudnn_workspace_size_pass]e[0m
e[1me[35m--- Running analysis [inference_op_replace_pass]e[0m
e[1me[35m--- Running analysis [memory_optimize_pass]e[0m
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : roi_align_0.tmp_0  size: 50176
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : roi_align_3.tmp_0  size: 50176
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : concat_4.tmp_0  size: 50176
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : roi_align_2.tmp_0  size: 50176
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : relu_49.tmp_0  size: 1024
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : roi_align_1.tmp_0  size: 50176
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : shape_1.tmp_0_slice_0  size: 8
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : conv2d_58.tmp_1  size: 1024
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : distribute_fpn_proposals_0.tmp_6  size: 4
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : batch_norm_51.tmp_3  size: 2048
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : conv2d_59.tmp_1  size: 1024
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : conv2d_60.tmp_1  size: 1024
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : image  size: 12
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : distribute_fpn_proposals_0.tmp_7  size: 4
I0404 18:00:55.893584 33640 memory_optimize_pass.cc:219] Cluster name : distribute_fpn_proposals_0.tmp_4  size: 4
e[1me[35m--- Running analysis [ir_graph_to_program_pass]e[0m
I0404 18:00:56.716620 33640 analysis_predictor.cc:1318] ======= optimize end =======
I0404 18:00:56.717620 33640 naive_executor.cc:110] ---  skip [feed], feed -> scale_factor
I0404 18:00:56.717620 33640 naive_executor.cc:110] ---  skip [feed], feed -> image
I0404 18:00:56.717620 33640 naive_executor.cc:110] ---  skip [feed], feed -> im_shape
I0404 18:00:56.726620 33640 naive_executor.cc:110] ---  skip [concat_12.tmp_0], fetch -> fetch
I0404 18:00:56.726620 33640 naive_executor.cc:110] ---  skip [multiclass_nms3_0.tmp_2], fetch -> fetch
i= 1
取帧时间 66
算法处理时间 4591
画框时间 429
i= 2
取帧时间 63
算法处理时间 4576
画框时间 444
进程已结束,退出代码-1

**### 麻烦帮忙解答下，推理的时候gpu内存没有任何变化，感觉都没用到gpu，想提高推理的速度，麻烦帮忙解答下，谢谢！**

**Comment by FlyingQianMM** [comment]
> 使用paddlepaddle-cpu进行部署，推理时间很慢

相比GPU，CPU推理会比较慢，可以设置use_mkl为True使用mkldnn加速。https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/deploy.md#predictor%E7%B1%BB

如果要使用GPU推理，需要安装paddlepaddle_gpu，且将use_gpu设置为True。相比GPU，CPU推理会比较慢，可以设置use_mkl为True使用mkldnn加速。https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/deploy.md#predictor%E7%B1%BB

**Comment by zhang7249** [comment]
> > 使用paddlepaddle-cpu进行部署，推理时间很慢
> 
> 相比GPU，CPU推理会比较慢，可以设置use_mkl为True使用mkldnn加速。https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/deploy.md#predictor%E7%B1%BB
> 
> 如果要使用GPU推理，需要安装paddlepaddle_gpu，且将use_gpu设置为True。相比GPU，CPU推理会比较慢，可以设置use_mkl为True使用mkldnn加速。https://github.com/PaddlePaddle/PaddleX/blob/develop/docs/apis/deploy.md#predictor%E7%B1%BB

我上面问题中输入错了，我下载的就是paddle paddle-gpu的版本，你看我提交的pip list中有证明，但是觉得就是没使用到gpu，您帮忙完整的看下，为啥我没用到gpu，谢谢！

**Comment by wangzhen38** [comment]
你可以确认下，安装paddle的python和启动命令的python是否为同一个
