### ISSUE TITLE
动转静在调用某类函数方法时一直报missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by tianyan01** [PaddlePaddle/Paddle#52574]
### 请提出你的问题 Please ask your question

跑动态图时没问题，但是在调用paddle.jit.to_static(layer, ...)后，会报这个错
在这个layer的forword里调用了paddlenlp的BeamSearchScorer的process方法，这个方法又会调用BeamHypotheses的add，在add这里报missing argument 'self'
![image](https://user-images.githubusercontent.com/124153989/230281479-1996aa73-c5f5-4bdc-acc3-c4842a0cf1f3.png)
但是我确认beam_hyp是BeamHypotheses类的实例，并且被初始化了，为什么还会报这个错呢？
![image](https://user-images.githubusercontent.com/124153989/230281686-0efd0649-13ec-4fc0-b407-fa961a3a3bbb.png)

**Comment by 2742195759** [comment]
可以看下 add 的签名和定义吗。

**Comment by tianyan01** [comment]
![image](https://user-images.githubusercontent.com/124153989/230289626-ad987077-ab16-4821-95d2-8cad6bf20263.png)


> 可以看下 add 的签名和定义吗。

**Comment by 2742195759** [comment]
请问使用的Paddle版本是什么版本的呢？

**Comment by tianyan01** [comment]
2.4.2

**Comment by 2742195759** [comment]
麻烦先使用 develop 版本试试吧：可以到下面的页面下载，选择合适的 cuda 版本。
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/16025309/230290921-637c59a2-86e6-4c40-9730-ec469f18b337.png">

**Comment by tianyan01** [comment]
抱歉，看错了。。用的是develop的

**Comment by 2742195759** [comment]
好像这个问题不是直接就可以看出来的，我本地构造了一个case，没有上述的问题。可以给我复现环境吗？

**Comment by tianyan01** [comment]
我自己也没复现出来。。刚换了另一套实现beamscore的代码，就不报这个错了

**Comment by 2742195759** [comment]
那我这个issue就关闭了哈，有问题可以随时在打开。
