### ISSUE TITLE
num workers疑问

### ISSUE THREAD

**Issue by awsssix** [PaddlePaddle/Paddle#52578]
### 请提出你的问题 Please ask your question

请问为什么设置num workers>0（如2、4、10），比num workers=0训练速度还慢

**Comment by awsssix** [comment]
可以回复一下吗

**Comment by LielinJiang** [comment]
是在什么环境运行？具体传给dataloader的参数是什么？

**Comment by awsssix** [comment]
分布式训练8卡V100
```
 data_loader_train = paddle.io.DataLoader(
        dataset_train,
        batch_sampler=sampler_train,
        places=device,
        num_workers=num_workers)
```

**Comment by LielinJiang** [comment]
设置上看没啥问题，可以单独跑下dataloader比较一下不同num_workers的耗时。以及单独跑dataset_train的耗时，并且查看sampler_train是否有特殊之处，不传sampler_train，直接使用batch_size是否有一样的现象

**Comment by GuangmingCao** [comment]
> ### 请提出你的问题 Please ask your question
> 请问为什么设置num workers>0（如2、4、10），比num workers=0训练速度还慢

我想问一下这个numworkers在哪里设置，我使用paddleX的如下训练代码训练没有找个设置这个的位置：
python main.py -c paddlex/configs/object_detection/PicoDet-S.yaml \
    -o Global.mode=check_dataset \
    -o Global.dataset_dir=./dataset/det_coco_examples
