### ISSUE TITLE
max op 请求支持fp16 bf16

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#52601]
### 需求描述 Feature Description

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/reduce_max_kernel.cc#L34-L40 

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/16911935/230374068-091d498c-ab6c-4093-892d-9322683a3f00.png">

**Comment by PommesPeter** [comment]
兄弟，我也遇到了和你一样的问题，我也提了 issue，目前我也希望 `paddle.max` 能够支持 float16 运算。 #52584
