### ISSUE TITLE
macbook m1 2021 安装不了paddlepaddle

### ISSUE THREAD

**Issue by duffercn** [PaddlePaddle/Paddle#52649]
### 问题描述 Issue Description

能搜到的解决方法都试了，但还是安装不上，显示：
master* $ pip install paddlepaddle                                                                                                                                                             [18:58:30]
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: macOS 13.2.1
GCC version: N/A
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.2
Libc version: N/A
Python version: 3.11.2

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by engineer1109** [comment]
编译啊

**Comment by duffercn** [comment]
> 编译啊

谢谢，发现可能是Python 3.11的问题，编译后可以安装了。

**Comment by duffercn** [comment]
已解决
