### ISSUE TITLE
paddle.slice的注释是不是写错了

### ISSUE THREAD

**Issue by changzipeng** [PaddlePaddle/Paddle#52640]
### 文档链接&描述 Document Links & Description

import paddle

input = paddle.rand(shape=[4, 5, 6], dtype='float32')
# example 1:
# attr starts is a list which doesn't contain tensor.
axes = [0, 1, 2]
starts = [-3, 0, 2]
ends = [3, 2, 4]
sliced_1 = paddle.slice(input, axes=axes, starts=starts, ends=ends)
# sliced_1 is input[0:3, 0:2, 2:4].

### 请提出你的建议 Please give your suggestion

这段代码我运行了一下，发现shape是[2, 2, 2],因此注释是不是应该改为sliced_1 is input[1:3, 0:2, 2:4].

**Comment by zyfncg** [comment]
您好~感谢反馈，这里注释的问题在develop分支已经修正
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/slice_cn.html
