### ISSUE TITLE
Polish C++ operators documentation

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5265]
We need to polish documentations of our operators. An example is 

https://github.com/PaddlePaddle/Paddle/blob/1363ddb6d724a19880b55cbefc0e62819a25a7d5/paddle/operators/auc_op.cc#L77-L91

We can take [ONNX's documentation](https://github.com/onnx/onnx/blob/master/docs/Operators.md) as a reference.  This also helps us preparing joining ONNX.

The following operators' documentation needs polishment. 

If you are going to file a PR to polish one or more of them, please check them so to avoid conflict of interests with others.

- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] accuracy_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] activation_op.cc
- [x] adadelta_op.cc
- [x] adagrad_op.cc
- [x] adam_op.cc
- [x] adamax_op.cc
- [x] auc_op.cc
- [x] batch_norm_op.cc
- [x] cast_op.cc
- [x] clip_op.cc
- [x] concat_op.cc
- [x] cond_op.cc
- [x] conv2d_op.cc
- [x] conv2dtranspose_op.cc
- [x] conv_shift_op.cc
- [x] cos_sim_op.cc
- [x] crop_op.cc
- [x] cross_entropy_op.cc
- [x] decayed_adagrad_op.cc
- [x] dropout_op.cc
- [x] dynamic_recurrent_op.cc
- [x] elementwise_add_op.cc
- [x] elementwise_div_op.cc
- [x] elementwise_mul_op.cc
- [x] elementwise_op.h
- [x] elementwise_sub_op.cc
- [x] feed_op.cc
- [x] fetch_op.cc
- [x] fill_constant_batch_size_like_op.cc
- [x] fill_constant_op.cc
- [x] fill_zeros_like_op.cc
- [x] gather_op.cc
- [x] gaussian_random_op.cc
- [x] gru_unit_op.cc
- [x] huber_loss_op.cc
- [x] increment_op.cc
- [x] l1_norm_op.cc
- [x] load_op.cc
- [x] lookup_table_op.cc
- [x] lrn_op.cc
- [x] lstm_op.cc
- [x] lstm_unit_op.cc
- [x] margin_rank_loss_op.cc
- [x] matmul_op.cc
- [x] mean_op.cc
- [x] minus_op.cc
- [x] modified_huber_loss_op.cc
- [x] momentum_op.cc
- [x] mul_op.cc
- [x] multiplex_op.cc
- [x] nccl_op.cc
- [x] nccl_op.cc
- [x] nccl_op.cc
- [x] nccl_op.cc
- [x] pad_op.cc
- [x] pool_op.cc
- [x] pool_op.cc
- [x] pool_with_index_op.cc
- [x] pool_with_index_op.cc
- [x] prelu_op.cc
- [x] proximal_adagrad_op.cc
- [x] proximal_gd_op.cc
- [x] rank_loss_op.cc
- [x] recurrent_op.cc
- [x] reduce_op.cc
- [x] reduce_op.cc
- [x] reduce_op.cc
- [x] reduce_op.cc
- [x] reduce_op.cc
- [x] reshape_op.cc
- [x] rmsprop_op.cc
- [x] save_op.cc
- [x] scale_op.cc
- [x] scatter_op.cc
- [x] seq_expand_op.cc
- [x] sequence_concat_op.cc
- [x] sequence_conv_op.cc
- [x] sequence_pool_op.cc
- [x] sequence_softmax_op.cc
- [x] sgd_op.cc
- [x] sigmoid_cross_entropy_with_logits_op.cc
- [x] sign_op.cc
- [x] smooth_l1_loss_op.cc
- [x] softmax_op.cc
- [x] softmax_with_cross_entropy_op.cc
- [x] split_op.cc
- [x] squared_l2_distance_op.cc
- [x] squared_l2_norm_op.cc
- [x] sum_op.cc
- [x] top_k_op.cc
- [x] transpose_op.cc
- [x] uniform_random_op.cc

**Comment by kavyasrinet** [comment]
Is anyone working on activation_op already ? If not I can start from there.

**Comment by kexinzhao** [comment]
Yes, I am working on them.

**Comment by kavyasrinet** [comment]
Alright! Thanks for the update. I will start from the other ones.

**Comment by kavyasrinet** [comment]
This has been successfully accomplished. Closing the issue.
