### ISSUE TITLE
onnx和paddle对protobuf的版本要求冲突

### ISSUE THREAD

**Issue by duffercn** [PaddlePaddle/Paddle#52655]
### 问题描述 Issue Description

paddle要求<=3.20.0，onnx 1.13.1又要求>=3.20.2

尝试安装低版本onnx但未成功。请问应以何种顺序和具体哪个版本安装相应的包？

### 版本&环境信息 Version & Environment Information

Error: Can not import paddle core while this file exists: /opt/homebrew/lib/python3.11/site-packages/paddle/fluid/libpaddle.so
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: macOS 13.2.1
GCC version: N/A
Clang version: 14.0.0 (clang-1400.0.29.202)
CMake version: version 3.25.2
Libc version: N/A
Python version: 3.11.2

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by jianbin-zqu** [comment]
protobuf==3.20.0
onnx==1.11.0
试一下

**Comment by useriiiiikkkknnnbsaawww** [comment]
你好 我安装好了paddleocr 也训练好了官方的一个模型 要勇于车牌识别 但是识别的时候只能从命令行执行 怎么才能从pychrm代码里运行呢 而且我要用pyqt写可视化界面

**Comment by kankanjiuzou123** [comment]
我也遇到了同样的问题，你解决了么？

**Comment by duffercn** [comment]
> 我也遇到了同样的问题，你解决了么？

我只是想用OCR功能，折腾了一天都没搞定，后来放弃了，换别的OCR了
