### ISSUE TITLE
 DLL load failed: 找不到指定的模块

### ISSUE THREAD

**Issue by yuanyu1111** [PaddlePaddle/Paddle#52703]
### 请提出你的问题 Please ask your question

Error: Can not import avx core while this file exists: d:\anaconda\lib\site-packages\paddle\fluid\core_avx.pyd
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-5-834e18e507a1> in <module>
----> 1 import paddle
      2 import paddlenlp
      3 print(paddle.__version__)
      4 print(paddlenlp.__version__)

d:\anaconda\lib\site-packages\paddle\__init__.py in <module>
     23 
     24 from .batch import batch  # noqa: F401
---> 25 from .fluid import monkey_patch_variable
     26 from .fluid.dygraph import monkey_patch_math_varbase
     27 monkey_patch_variable()

d:\anaconda\lib\site-packages\paddle\fluid\__init__.py in <module>
     34 
     35 # import all class inside framework into fluid module
---> 36 from . import framework
     37 from .framework import *
     38 # import all class inside executor into fluid module

d:\anaconda\lib\site-packages\paddle\fluid\framework.py in <module>
     35 from .proto import framework_pb2
     36 
---> 37 from . import core
     38 from . import unique_name
     39 import paddle.version as fluid_version

d:\anaconda\lib\site-packages\paddle\fluid\core.py in <module>
    292                 'Error: Can not import avx core while this file exists: ' +
    293                 current_path + os.sep + 'core_avx.' + core_suffix + '\n')
--> 294             raise e
    295         else:
    296             from .. import compat as cpt

d:\anaconda\lib\site-packages\paddle\fluid\core.py in <module>
    254 if avx_supported():
    255     try:
--> 256         from .core_avx import *
    257         from .core_avx import __doc__, __file__, __name__, __package__
    258         from .core_avx import __unittest_throw_exception__

ImportError: DLL load failed: 找不到指定的模块。

**Comment by danleifeng** [comment]
看着是安装paddle不正确，辛苦提供下paddle安装的环境信息、版本信息，也可以先参考下官网 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html 进行确认

**Comment by yuanyu1111** [comment]
已解决谢谢，没看到有教程

**Comment by danleifeng** [comment]
好的~
