### ISSUE TITLE
paddle run_check显示killed

### ISSUE THREAD

**Issue by deepblacksky** [PaddlePaddle/Paddle#52735]
### bug描述 Describe the Bug

使用paddle被莫名killed
![c21a4ab05b49a220c2e5f2e67949880f](https://user-images.githubusercontent.com/16918021/230888310-31f1f88c-644e-479d-9848-e331da46fb21.png)

环境:
paddlepaddle-gpu 2.3.2.post112
cuda 11.2
cudnn 8.1
GPU:A10

**Comment by ForFishes** [comment]
您好，是不是内存爆了，导致容器kill了。
