### ISSUE TITLE
多进程运行模型的问题

### ISSUE THREAD

**Issue by zhang7249** [PaddlePaddle/Paddle#52758]
### 请提出你的问题 Please ask your question

我用PaddleX训练了一批数据，无人机在天上识别车辆的物体检测模型，在paddle上部署，运行失常90ms，不满足我实时一秒30帧。我尝试用多进程启动了三个脚本模型，队列分发，但是实际测一下来，每个模型需要运行300ms左右，性能不增反减……..

**Comment by LDOUBLEV** [comment]
你预测的多张图像的平均时长还是单个图像的运行时间，，第一次预测需要模型初始化耗时较多；
如果要加速预测，gpu上可以用tensorrt，cpu上可以开启mkldnn（并设置比较大的线程数）

多进程变慢的问题，是多进程本身耗时较多，不是因为多进程影响了paddle预测耗时

**Comment by zhang7249** [comment]
> 你预测的多张图像的平均时长还是单个图像的运行时间，，第一次预测需要模型初始化耗时较多； 如果要加速预测，gpu上可以用tensorrt，cpu上可以开启mkldnn（并设置比较大的线程数）
> 
> 多进程变慢的问题，是多进程本身耗时较多，不是因为多进程影响了paddle预测耗时

多张图片，取得rtmp 的帧数据，源源不断，观察了有大概五六分钟时间，都是差不多300毫秒。我在每个多进程中都初始化了对象，观察了显存，确实是倍数增长，正常单进程消耗2G显存，开三个进程就是6G显存，机器是amd32核cpu，128g内存，rtx3060的12G显存显卡，理论上这机器够用了，很诡异的是，多进程的耗时就是单进程的倍数。而且我打印的就是paddle的run运行时间，run之前记录个时间，run之后记录个时间两个时间的差，并不是多进程运行耗费的时间

**Comment by LDOUBLEV** [comment]
每个进程的predictor可以复用，不用每个进程开一个predictor；

> 而且我打印的就是paddle的run运行时间，run之前记录个时间，run之后记录个时间两个时间的差

因为你是多进程跑，用总时间除以图像数量计算平均时间；看下相比单进程是否有加速；

> 并不是多进程运行耗费的时间

设置进程数为1，看下是否和不使用多进程的平均预测时间一致
