### ISSUE TITLE
静态图中如何打印梯度，使用fluid.layers.Print(**, print_phase='backward') 无打印信息，fetch_list 也无信息输出

### ISSUE THREAD

**Issue by ShaominFan** [PaddlePaddle/Paddle#52755]
### 请提出你的问题 Please ask your question

fc = fluid.layers.fc(
                    input=fc_layers_input[-1],
                    size=fc_layers_size[i],
                    act=fc_layers_act[i],
                    param_attr=fluid.ParamAttr(learning_rate=learning_rate_fc, \
                        initializer=fluid.initializer.NormalInitializer( \
                        loc=0.0, scale=1.0 * scales[i]), name=w_name),
                    bias_attr=fluid.ParamAttr(learning_rate=learning_rate_fc, \
                        initializer=fluid.initializer.NormalInitializer( \
                        loc=0.0, scale=1.0 * scales[i]), name=b_name))
fluid.layers.Print(fc, print_phase='backward')
无信息输出

**Comment by LDOUBLEV** [comment]
参考文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/train_cn.html#variable
