### ISSUE TITLE
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: misaligned address

### ISSUE THREAD

**Issue by wfangyan** [PaddlePaddle/Paddle#52763]
### 请提出你的问题 Please ask your question

When running a model converted to tensorrt for a long time, this exception error occurs.
"common.py", line 108, in do_inference
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
"common.py", line 108, in <listcomp>
    [cuda.memcpy_htod_async(inp.device, inp.host, stream) for inp in inputs]
pycuda._driver.LogicError: cuMemcpyHtoDAsync failed: misaligned address

tensorrt   8.2.5.1
paddle  2.2.0
pycuda    2022.1
cuda 11.6

**Comment by LDOUBLEV** [comment]
please provide the model you used and the inference code for debugging.
 
The reason for the misaligned address is that the pointer is not aligned with the boundary required by the processor. 

And If this problem occurs repeatedly on a certain sample, you can check this input sample.
