### ISSUE TITLE
paddle 中的lstm 可以实现 seq 到 seq的预测吗？eg: for one  seq  A = [1,2,3,4,5,6,7]   ,I hope  the input x = [1,2,3,4,5,6], and y = [2,3,4,5,6,7] 

### ISSUE THREAD

**Issue by majiayuanyuan** [PaddlePaddle/Paddle#5278]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [x] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [x] Did you retrieve your issue from widespread search engines ?
- [x] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by peterzhang2029** [comment]
你好，我理解的你说的任务有点像语言模型， 这种数据的输入paddlepaddle是支持的， 可参考 https://github.com/PaddlePaddle/models/tree/develop/generate_sequence_by_rnn_lm 中的示例。
