### ISSUE TITLE
Inconsistent type exception in mean_op when doing gradient test 

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#5281]
When checking gradient for an operator, a mean operator will be appended after the operator.  However, in mean_op sometimes getting data pointer from OG will be failed due to inconsistent type (op type is **float32** and OG type is **double**). My question is how to specify the data type for mean_op's OG?

**Comment by pkuyym** [comment]
Please refer this issue: #5163

**Comment by reyoung** [comment]
It because the numpy arrary of output is wrong.
