### ISSUE TITLE
import paddle提示信息如何理解？

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/Paddle#52817]
### bug描述 Describe the Bug

import paddle

### 其他补充信息 Additional Supplementary Information

>>> import paddle
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

**Comment by huangjun12** [comment]
pkg_resources介绍可以参考下 https://blog.csdn.net/bocai_xiaodaidai/article/details/125971394

**Comment by 38weiying** [comment]
請問是否解決，我也遇到一樣的問題
