### ISSUE TITLE
Could not load library libcublasLt.so.12, 我的是libcublasLt.so.11

### ISSUE THREAD

**Issue by alantseone** [PaddlePaddle/Paddle#52869]
### 问题描述 Issue Description

Please NOTE: device: 0, GPU Compute Capability: 8.9, Driver API Version: 12.0, Runtime API Version: 11.7
我是driver 12.0 ，但我是跑11.7 cuda

彈出錯誤: Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory
我查過11.7 底下只有libcublasLt.so.11的文件，要怎麼才能把他要求的12版本換到11裡?

我沒辦法安裝cuda12 因為飛樂只支援到11.7，而4080只能裝cuda12的driver版本，導致現在飛樂好像是根據我drive的cuda版本來抓libcublasLt.so.12這個檔案，該如何把他修改成libcublasLt.so.11的版本

### 版本&环境信息 Version & Environment Information

【编译命令】sh tests/install/check_predict.sh
【系统平台】: Linux x64(Ubuntu 22.04)
【硬件】： Nvidia GPU 4080， CUDA 11.7 cuDNN 8.8.
【编译语言】：Python(3.10）

根據   https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/docs/install.md
的手冊
我所有安裝都成功，沒有出現bug，
直到要跑sh tests/install/check_predict.sh

**Comment by JZ-LIANG** [comment]
将 libcublasLt.so.12 放到 LD_LIBRARY 目录下

**Comment by alantseone** [comment]
@JZ-LIANG  我並沒有安裝cuda12的api版本 只有driver，所以我沒有 libcublasLt.so.12

**Comment by JZ-LIANG** [comment]
你需要装 cuda12 的driver。

**Comment by AkagawaTsurunaki** [comment]
我使用的 CUDA 11.8 和 Python 3.10，根据官方手册用 conda 安装后，调用 OCR 模型的时候发生了同样的错误，但是使用 pip 安装就安然无恙。
```shell
python3 -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
```
