### ISSUE TITLE
静态图梯度累加

### ISSUE THREAD

**Issue by cwings316** [PaddlePaddle/Paddle#52895]
### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/Paddle/issues/41185
请问静态图的梯度累加应该怎么实现呢？在官方文档中没有看到代码示例。谢谢解答～

**Comment by JZ-LIANG** [comment]
请参考：
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/optimizer.py#L7434
