### ISSUE TITLE
Python help outputs operator documents

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#5289]
The following code snippet automatically exports operators into Python layer functions:

https://github.com/PaddlePaddle/Paddle/blob/6d649d9ebd2be27f796e07cf79d26d5e8539d2f3/python/paddle/v2/framework/layers.py#L111-L179

We need to improve it so that users can use [Python's `help ` function](https://docs.python.org/2/library/functions.html#help) to retrieve the document of the layer/operator.

**Comment by wangkuiyi** [comment]
I assigned @reyoung as the assignee. @reyoung please feel free to assign to others in the team who might be able to fix this. Thanks!

**Comment by reyoung** [comment]
@wangkuiyi @emailweixu 
This feature is implemented before, I will move them to the newest code within this week.

https://github.com/PaddlePaddle/Paddle/blob/53f85df1abbafdd248c06c065beebfa2b5d27b29/python/paddle/v2/framework/operator.py#L149-L208
