### ISSUE TITLE
【AI Studio脚本任务】安装依赖时没有相应权限

### ISSUE THREAD

**Issue by PHuiC** [PaddlePaddle/Paddle#52916]
### 请提出你的问题 Please ask your question

你好，我在脚本任务中，想要使用PaddleDetection，但是，在安装依赖，和编译安装PaddleDetection的时候会报错，主要是提示没有权限。报错如下：

**执行：pip install -r requirements.txt报错：**

WARNING: The directory '/home/aistudio/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag.

**执行：python setup.py install报错：**

error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

[Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/test-easy-install-938.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

/usr/local/lib/python3.7/dist-packages/

**执行python setup.py install（ppyoloe-r安装外部算子）报错：**

error: can't create or remove files in install directory

The following error occurred while trying to add or remove files in the
installation directory:

[Errno 13] Permission denied: '/usr/local/lib/python3.7/dist-packages/test-easy-install-951.write-test'

The installation directory you specified (via --install-dir, --prefix, or
the distutils default setting) was:

/usr/local/lib/python3.7/dist-packages/

**Comment by wanghuancoder** [comment]
你好你的问题可以通过AI Studio官网的反馈按钮进行反馈。也可以通过邮箱联系AI Studio的技术人员aistudio@baidu.com。
Paddle issue的答疑同学对这方面问题，也不懂，没办法回答。非常抱歉！
