### ISSUE TITLE
Isnan的测试样例为什么这么写

### ISSUE THREAD

**Issue by blacksheep-Aristotle** [PaddlePaddle/Paddle#52931]
### 请提出你的问题 Please ask your question

`        x = np.random.uniform(0.1, 1, [11, 17]).astype(self.dtype)
        x[0] = np.nan
        x[-1] = np.nan

        self.inputs = {'X': x}
        self.outputs = {'Out': np.array(True).astype(self.dtype)}`
输出是一个元素，还不是Bool值？？？
和文档Api里的使用说明不一致。

**Comment by wanghuancoder** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/isnan_cn.html#isnan
请已官网为准。isnan返回的是Tensor中每个元素是否为nan的Tensor，元素个数与输入Tensor的元素个数相等。即使Tensor为只有1个元素，返回的也是Tensor。而且如果使用GPU，这个Tensor会在GPU上。不会转换为Bool返回给用户。

你发的是单测中的测试用例。这个是测试isnan算子的。但是paddle.isnan，使用的是isnan_v2算子。
