### ISSUE TITLE
FLAGS_use_cuda_managed_memory true和false 两种内存管理方式有什么区别？

### ISSUE THREAD

**Issue by zhaoyuehao** [PaddlePaddle/Paddle#52945]
### 请提出你的问题 Please ask your question

FLAGS_use_cuda_managed_memory true和false 两种内存管理方式有什么区别？

**Comment by From00** [comment]
`FLAGS_use_cuda_managed_memory`用于开启CUDA的CPU-GPU统一内存寻址功能，设置为`true`的情况下框架将默认使用`cudaMallocManaged`接口进行显存申请，以支持模型对GPU显存的超额使用。
关于CUDA的统一内存寻址，可以参考：https://developer.nvidia.com/blog/unified-memory-cuda-beginners/

**Comment by zhaoyuehao** [comment]
嗯嗯，这里是设置为true的情况，默认false的情况下，paddle是做了哪些优化吗？

**Comment by zhaoyuehao** [comment]
> `FLAGS_use_cuda_managed_memory`用于开启CUDA的CPU-GPU统一内存寻址功能，设置为`true`的情况下框架将默认使用`cudaMallocManaged`接口进行显存申请，以支持模型对GPU显存的超额使用。 关于CUDA的统一内存寻址，可以参考：https://developer.nvidia.com/blog/unified-memory-cuda-beginners/


上述是设置为true的情况；默认false下，paddle是做了哪些优化吗？这里设置为true 会有什么影响吗？

**Comment by From00** [comment]
> > `FLAGS_use_cuda_managed_memory`用于开启CUDA的CPU-GPU统一内存寻址功能，设置为`true`的情况下框架将默认使用`cudaMallocManaged`接口进行显存申请，以支持模型对GPU显存的超额使用。 关于CUDA的统一内存寻址，可以参考：https://developer.nvidia.com/blog/unified-memory-cuda-beginners/
> 
> 上述是设置为true的情况；默认false下，paddle是做了哪些优化吗？这里设置为true 会有什么影响吗？

paddle针对显存分配，有许多优化策略，包括缓存池、碎片管理、多流管理等，具体可以参考memory目录下的代码：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/memory

`FLAGS_use_cuda_managed_memory`仅用于控制框架在调用`cudaMalloc`时是否使用CUDA的统一内存寻址接口`cudaMallocManaged`，与paddle中其它显存优化策略是解耦的，不会相互影响；但统一内存寻址本身是一种牺牲时间换空间的技术，开启后对运行性能可能会产生影响。
