### ISSUE TITLE
编译错误

### ISSUE THREAD

**Issue by zhink** [PaddlePaddle/Paddle#52950]
### bug描述 Describe the Bug

gcc version 8.2.0
from registry.baidubce.com/paddlepaddle/paddle:latest-dev-cuda11.4.1-cudnn8-gcc82
.......
Scanning dependencies of target analysis_passes
[ 98%] Building CXX object paddle/fluid/inference/analysis/passes/CMakeFiles/analysis_passes.dir/passes.cc.o
[ 98%] Linking CXX executable eager_legacy_op_function_generator
[ 98%] Linking CXX static library libanalysis_passes.a
[ 98%] Built target analysis_passes
Scanning dependencies of target analysis
[ 98%] Building CXX object paddle/fluid/inference/analysis/CMakeFiles/analysis.dir/analyzer.cc.o
[ 98%] Linking CXX executable eager_generator
/usr/lib/x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x26): relocation truncated to fit: R_X86_64_GOTPCRELX against symbol `__libc_start_main@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x20): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x50): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crti.o: in function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/kernel_signature_generator.dir/kernel_signature_generator.cc.o: in function `paddle::safe_realloc(void*, unsigned long) [clone .part.34]':
kernel_signature_generator.cc:(.text+0x11): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
kernel_signature_generator.cc:(.text+0x18): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `typeinfo for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
kernel_signature_generator.cc:(.text+0x29): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `std::bad_alloc::~bad_alloc()@@GLIBCXX_3.4' defined in .text section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
CMakeFiles/kernel_signature_generator.dir/kernel_signature_generator.cc.o: in function `paddle::report_at_maximum_capacity(unsigned long)':
kernel_signature_generator.cc:(.text+0x1cc): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/kernel_signature_generator.dir/kernel_signature_generator.cc.o: in function `paddle::report_size_overflow(unsigned long, unsigned long) [clone .constprop.487]':
kernel_signature_generator.cc:(.text+0x26c): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/kernel_signature_generator.dir/kernel_signature_generator.cc.o: in function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode) [clone .constprop.484]':
kernel_signature_generator.cc:(.text+0x493): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::basic_ios<char, std::char_traits<char> >@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
kernel_signature_generator.cc:(.text+0x4ce): additional relocation overflows omitted from the output
/usr/local/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/build.make:1506: recipe for target 'paddle/fluid/pybind/kernel_signature_generator' failed
make[2]: *** [paddle/fluid/pybind/kernel_signature_generator] Error 1
CMakeFiles/Makefile2:161303: recipe for target 'paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/kernel_signature_generator.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 98%] Linking CXX static library libanalysis.a
[ 98%] Built target analysis
/usr/lib/x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x26): relocation truncated to fit: R_X86_64_GOTPCRELX against symbol `__libc_start_main@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x20): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x50): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crti.o: in function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/eager_legacy_op_function_generator.dir/eager_legacy_op_function_generator.cc.o: in function `paddle::safe_realloc(void*, unsigned long) [clone .part.40]':
eager_legacy_op_function_generator.cc:(.text+0x21): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_legacy_op_function_generator.cc:(.text+0x28): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `typeinfo for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_legacy_op_function_generator.cc:(.text+0x39): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `std::bad_alloc::~bad_alloc()@@GLIBCXX_3.4' defined in .text section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
CMakeFiles/eager_legacy_op_function_generator.dir/eager_legacy_op_function_generator.cc.o: in function `paddle::report_at_maximum_capacity(unsigned long)':
eager_legacy_op_function_generator.cc:(.text+0x2ac): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/eager_legacy_op_function_generator.dir/eager_legacy_op_function_generator.cc.o: in function `paddle::report_size_overflow(unsigned long, unsigned long) [clone .constprop.685]':
eager_legacy_op_function_generator.cc:(.text+0x34c): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/eager_legacy_op_function_generator.dir/eager_legacy_op_function_generator.cc.o: in function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode) [clone .constprop.682]':
eager_legacy_op_function_generator.cc:(.text+0x573): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::basic_ios<char, std::char_traits<char> >@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_legacy_op_function_generator.cc:(.text+0x5ae): additional relocation overflows omitted from the output
/usr/local/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator.dir/build.make:1506: recipe for target 'paddle/fluid/pybind/eager_legacy_op_function_generator' failed
make[2]: *** [paddle/fluid/pybind/eager_legacy_op_function_generator] Error 1
CMakeFiles/Makefile2:160484: recipe for target 'paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator.dir/all' failed
make[1]: *** [paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator.dir/all] Error 2
/usr/lib/x86_64-linux-gnu/crt1.o: in function `_start':
(.text+0x26): relocation truncated to fit: R_X86_64_GOTPCRELX against symbol `__libc_start_main@@GLIBC_2.2.5' defined in .text section in /lib/x86_64-linux-gnu/libc.so.6
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x20): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crt1.o:(.eh_frame+0x50): relocation truncated to fit: R_X86_64_PC32 against `.text'
/usr/lib/x86_64-linux-gnu/crti.o: in function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/eager_generator.dir/eager_generator.cc.o: in function `paddle::safe_realloc(void*, unsigned long) [clone .part.51]':
eager_generator.cc:(.text+0x21): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_generator.cc:(.text+0x28): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `typeinfo for std::bad_alloc@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_generator.cc:(.text+0x39): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `std::bad_alloc::~bad_alloc()@@GLIBCXX_3.4' defined in .text section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
CMakeFiles/eager_generator.dir/eager_generator.cc.o: in function `paddle::report_at_maximum_capacity(unsigned long)':
eager_generator.cc:(.text+0x8fc): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/eager_generator.dir/eager_generator.cc.o: in function `paddle::report_size_overflow(unsigned long, unsigned long) [clone .constprop.1638]':
eager_generator.cc:(.text+0xa2c): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vsnprintf@@GLIBC_2.2.5' defined in .plt.got section in /usr/lib/x86_64-linux-gnu/crt1.o
CMakeFiles/eager_generator.dir/eager_generator.cc.o: in function `std::__cxx11::basic_ostringstream<char, std::char_traits<char>, std::allocator<char> >::basic_ostringstream(std::_Ios_Openmode) [clone .constprop.1635]':
eager_generator.cc:(.text+0xba3): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against symbol `vtable for std::basic_ios<char, std::char_traits<char> >@@GLIBCXX_3.4' defined in .data.rel.ro section in /usr/local/gcc-8.2/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../lib64/libstdc++.so
eager_generator.cc:(.text+0xbde): additional relocation overflows omitted from the output
/usr/local/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/build.make:1503: recipe for target 'paddle/fluid/eager/auto_code_generator/eager_generator' failed
make[2]: *** [paddle/fluid/eager/auto_code_generator/eager_generator] Error 1
CMakeFiles/Makefile2:164221: recipe for target 'paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all' failed
make[1]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/eager_generator.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by will-jl944** [comment]
是编译Paddle时候出现的报错吗？基于的commit id是多少？辛苦提供一下复现步骤或编译时的指令。

**Comment by tianyan01** [comment]
请问这个报错最后怎么解决的呢？

**Comment by Aiga-Andrijanova** [comment]
> Is it an error when compiling Paddle? What is the commit id based on? Please kindly provide the reproduction steps or compile-time instructions.

It is an error while compiling paddle, I have the same issue based on release/2.5 Paddle branch.
I followed the steps on PaddleOCR repo https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/cpp_infer/readme.md

**Comment by grinay** [comment]
Same issue, trying to compile , no luck , tried different version of docker releases, the same issue. Following instruction from here (https://www.paddlepaddle.org.cn/documentation/docs/en/install/compile/linux-compile_en.html)
