### ISSUE TITLE
API文档写的太粗糙

### ISSUE THREAD

**Issue by zishuaiz** [PaddlePaddle/Paddle#5295]
api文档写的太粗糙，dataprovider中的hook函数中的settings是个什么类型，
找了半天都找不到。
烦请把paddle自己定义的类、数据类型写清楚好么，程序员最基本的素养！
用paddle全靠猜和试，这太。。。

**Comment by will-am** [comment]
dataprovider中的settings类型请见：http://doc.paddlepaddle.org/release_doc/0.9.0/doc/ui/data_provider/pydataprovider2.html#init-hook

settings是一个dict，默认有两个key：input_types和logger。

可以自己在settings中添加其他key-value，然后在process中使用。

现在v1的文档基本不维护了，主要推荐使用paddle v2版本，v2的文档比较全面：http://doc.paddlepaddle.org/develop/doc/api/index_en.html
