### ISSUE TITLE
[phi]Kernel注册时函数体内针对OutputAt 设置dtype的作用，具体在哪里会使用？

### ISSUE THREAD

**Issue by Jaason19** [PaddlePaddle/Paddle#52966]
RT.

![image](https://user-images.githubusercontent.com/92357709/232315518-9b964eb5-d546-49d0-8702-62e7536aabe3.png)

看代码这里会修改kernel key中的TensorArgDef，但在哪里使用呢？场景是eager运行

**Comment by Aurelius84** [comment]
batch_norm_infer 的index为1和2的输出分别是 mean 和 variance，这两个输出的计算涉及到复杂的累加求平均等操作。在FP16类型的输入下，如果不将mean和variance设置为FLoat32，则在累加求平均等操作时很容易上溢或下溢出FP16的范围，导致预测精度有损失，故这里设置为了FLoat32
