### ISSUE TITLE
EmbeddingSparseGradKernel 的返回值SelectedRows是如何梯度更新的？

### ISSUE THREAD

**Issue by happyfc1** [PaddlePaddle/Paddle#52971]
### 请提出你的问题 Please ask your question

EmbeddingSparseGradKernel 的主要逻辑，是在SelectedRows填入如下数据：

1. input_ids拉平，调用set_rows设置
2. 获取table长度，调用set_height设置
3. 获取dout，(n,s,d) reshape成(n*s,d)，设置至value_

此处只有sparse梯度信息，具体参数更新逻辑在哪里？如何更新？

**Comment by FlyingQianMM** [comment]
参数梯度的更新在后面的拷贝函数里：

https://github.com/PaddlePaddle/Paddle/blob/205a4d9a9ecfb8044e03f1e6ea7378d485589c1b/paddle/phi/kernels/gpu/embedding_grad_kernel.cu#L216-L221
