### ISSUE TITLE
单价四卡并行计算在recompute下报错

### ISSUE THREAD

**Issue by Nefefilibata** [PaddlePaddle/Paddle#52980]
### 请提出你的问题 Please ask your question

不加入recompute，单机四卡分组切分并行可以正常训练
但开启recompute后
即在模型中：x = blk(x,H,W)
改为：x = recompute(blk,x,H,W)
训练完第一个epoch后报以下错误：
epoch: 1, batch_id: 1, loss is: [2.6346893]
Traceback (most recent call last):
  File "PVT-v2_distribute.py", line 425, in <module>
    train2()
  File "PVT-v2_distribute.py", line 402, in train2
    scaler.scale(avg_loss).backward()
  File "<decorator-gen-157>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) RuntimeError: (PreconditionNotMet) Error happened, when parameter[341][linear_79.b_0] has been ready before. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, there may be several reasons for this error: 1) In multiple reentrant backward phase, some parameters are reused.2) Using model parameters outside of forward function. Please make sure that model parameters are not shared in concurrent forward-backward passes.
  [Hint: Expected has_marked_unused_vars_ == false, but received has_marked_unused_vars_:1 != false:0.] (at /paddle/paddle/fluid/distributed/collective/reducer.cc:689)

At:
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/autograd/backward_mode.py(125): backward
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py(534): __impl__
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py(26): __impl__
  <decorator-gen-269>(2): backward
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/distributed/fleet/recompute/recompute.py(392): backward
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/autograd/py_layer.py(546): backward
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py(297): backward
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py(534): __impl__
  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py(26): __impl__
  <decorator-gen-157>(2): backward
  PVT-v2_distribute.py(402): train2
  PVT-v2_distribute.py(425): <module>
 (at /paddle/paddle/fluid/eager/pylayer/py_layer_node.cc:113)

**Comment by FlyingQianMM** [comment]
您好，请问您现在使用的是哪个repo里的模型？基于官网模型是否有做自己的修改？

**Comment by Nefefilibata** [comment]
模型是PVT-V2。recompute在单卡下可以正常训练，但是在四卡并行会报如上错误。四卡下关闭recompute能正常训练。
在模型上只修改了这部分
    def forward_features(self, x):
        B = x.shape[0]

        for i in range(self.num_stages):
            patch_embed = getattr(self, f"patch_embed{i + 1}")
            block = getattr(self, f"block{i + 1}")
            norm = getattr(self, f"norm{i + 1}")
            x, H, W = patch_embed(x)
            # x, H, W = recompute(patch_embed,x)
            for blk in block:
                x = recompute(blk,x,H,W)
                # x = blk(x,H,W)
            x = norm(x)
            if i != self.num_stages - 1:
                x = x.reshape([B, H, W, -1]).transpose([0, 3, 1, 2])
        return x.mean(axis=1)

    def forward(self, x):
        x = self.forward_features(x)
        x = self.head(x)
        return x
即在原有的forward_features上加入了recompute

**Comment by FlyingQianMM** [comment]
看前面的报错提醒给的解释：

```
OSError: (External) RuntimeError: (PreconditionNotMet) Error happened, when parameter[341][linear_79.b_0] has been ready before. Please set find_unused_parameters=True to traverse backward graph in each step to prepare reduce in advance. If you have set, there may be several reasons for this error: 1) In multiple reentrant backward phase, some parameters are reused.2) Using model parameters outside of forward function. Please make sure that model parameters are not shared in concurrent forward-backward passes.
```

尝试以下：
1. 将find_unused_parameters设置为True，https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/DataParallel_cn.html#dataparallel
2. 看报错提醒有参数被shared利用了，看下recompute的位置加的是否正确
