### ISSUE TITLE
import paddlehub as hub importing libpaddle: 找不到指定的模块

### ISSUE THREAD

**Issue by 57073629** [PaddlePaddle/Paddle#52992]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/95571683/232443870-8262e23f-d639-498f-aab8-1439de8392e3.png)

**Comment by FlyingQianMM** [comment]
看着是安装paddle不正确，辛苦提供下paddle安装的环境信息、版本信息，也可以先参考下官网 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/conda/windows-conda.html 进行确认
