### ISSUE TITLE
随机数据增强，可复现实验

### ISSUE THREAD

**Issue by awsssix** [PaddlePaddle/Paddle#53002]
### 问题描述 Please describe your issue

论文复现中代码中包含随机数据增强操作，请问是通过seed()、np.random.seed、random.seed，来保证torch和paddle数据增强结果一致吗

**Comment by FlyingQianMM** [comment]
np.rand.seed可以保证np的随机性，但是框架内部的随机性无法统一保证。随机性固定一般是做模型前反向对齐的时候才需要固定，训练过程中不需要固定随机性
