### ISSUE TITLE
昇腾源码编译安装paddlepaddle连接超时

### ISSUE THREAD

**Issue by lchnp** [PaddlePaddle/Paddle#53006]
### 问题描述 Issue Description

![image](https://user-images.githubusercontent.com/130987352/232496158-94b7c103-ceaa-48ad-b686-0c128446920c.png)
源码编译安装过程中下载第三方包报错，访问github会超时。自己下载第三方包进行编译也会出现版本不合适或者编译错误等问题。

### 版本&环境信息 Version & Environment Information

AI加速卡：昇腾310 ，操作系统麒麟v10 arm架构， python3.7.16 ，cann版本为6.0.0.alpha006

**Comment by FlyingQianMM** [comment]
这个是网络问题，试下开个代理访问github
