### ISSUE TITLE
昇腾服务器在安装过程中pip install paddlepaddle==2.3.2报错

### ISSUE THREAD

**Issue by lchnp** [PaddlePaddle/Paddle#53001]
### 问题描述 Issue Description

AI加速卡  昇腾310 操作系统麒麟v10 arm架构  python3.7.16
安装paddlepaddle过程中报错
![image](https://user-images.githubusercontent.com/130987352/232485122-af6dc365-0a2c-4be1-a713-e86f59bcf7fa.png)

### 版本&环境信息 Version & Environment Information

paddlepaddle==2.3.2
系统是麒麟v10
python3.7.16

**Comment by lchnp** [comment]
cann是6.0.0.alpha006

**Comment by FlyingQianMM** [comment]
您好，请参考文档 https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 进行安装

**Comment by lchnp** [comment]
您好，这个不是安装得paddle lite吗？


空白
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月17日(星期一) 晚上9:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 昇腾服务器在安装过程中pip install paddlepaddle==2.3.2报错 (Issue #53001)





 
您好，请参考文档 https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 进行安装

**Comment by lchnp** [comment]
> 您好，请参考文档 https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 进行安装

您好，这个文档我打开之后安装对应的环境点开安装教程，安装教程是paddle lite的，不是paddlepaddle

**Comment by FlyingQianMM** [comment]
你是要用来做训练吗？训练的话参考昇腾910的安装教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html
