### ISSUE TITLE
Make program and init_program as optional when constructing a layer

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#5301]
It is very cumbersome to have to adding these two arguments seemly unrelated to the logic in every layer or operator:
 
layers.square_error_cost(
    input=y_predict, label=y, program=program, init_program=init_program)

In general, we should aims to make writing the model similar to how we write equations. We should make things unrelated to equations as minimal as possible.

**Comment by helinwang** [comment]
Done. Currently they are optional, and the demo code don't use them.
