### ISSUE TITLE
Torch转过来的模型，在Python和C++下性能有较大差异

### ISSUE THREAD

**Issue by LiYouR** [PaddlePaddle/Paddle#53029]
### 请提出你的问题 Please ask your question

从Torch通过x2paddle转换过来的模型。
在python动图模式下运行良好
导出模型后，通过paddle inference使用C++调用，性能很差。
请问这大概会是什么问题呢。

**Comment by ccrrong** [comment]
你好，可以确认一下python和C++调用的参数是否一致，例如有没有开tensorrt、fp16等

**Comment by engineer1109** [comment]
你没开图优化

**Comment by LiYouR** [comment]
> 你没开图优化

可以请教一下具体是哪个api吗

**Comment by engineer1109** [comment]
EnableMemoryOptim   允许内存优化
SwitchIrOptim   图优化
如果还有问题，那就是生成的东西有问题。自己排查下。

**Comment by LiYouR** [comment]
> EnableMemoryOptim 允许内存优化 SwitchIrOptim 图优化 如果还有问题，那就是生成的东西有问题。自己排查下。

好的 ~多谢
