### ISSUE TITLE
paddle.fluid.layers.beam_search在2.0之后没有了

### ISSUE THREAD

**Issue by XXYMAN** [PaddlePaddle/Paddle#53027]
### 请提出你的问题 Please ask your question

paddle.fluid.layers.beam_search在2.0之后没有了，请问有没有类似的接口
其中 paddle.nn.BeamSearchDecoder，需要传cell，不满足需求

**Comment by winter-wang** [comment]
你好，有功能上等价的接口，就是 BeamSearchDecoder，但是使用方法上不等价。
https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/transformer/modeling.py#L1080
比如说这个例子，现在这个 API 需要结合 dynamic decode 来使用，可以通过继承于 BeamSearchDecoder 来自定义解码过程，如果想实现和 layers.beam_search 相似的功能，也可以直接用 paddlenlp 的代码
