### ISSUE TITLE
Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples

### ISSUE THREAD

**Issue by hikkinight** [PaddlePaddle/Paddle#5304]
提交任务时曝出这个错误。现在能确认的是问题出topology定义上，reader没问题。另外topology的定义里, simple_gru换成sequence_conv_pool后也没问题.
```python
def fc_net(dict_dim):
    # input layers
    dict_dim_real = int(dict_dim + 1)
    query_id = paddle.layer.data(
        name='query',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    query_emb = paddle.layer.embedding(input=query_id, size=64)
    #query_conv = paddle.networks.sequence_conv_pool(
    #    input=query_emb, hidden_size=32, context_len=3)
    query_conv = paddle.networks.simple_gru(input=query_emb, size=64)
    query_fc = paddle.layer.fc(input=query_conv, size=64, act=paddle.activation.Tanh())
    
    pos_title_id = paddle.layer.data(
        name='pos_title',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    pos_title_emb = paddle.layer.embedding(input=pos_title_id, size=64)
    #pos_title_conv = paddle.networks.sequence_conv_pool(
    #    input=pos_title_emb, hidden_size=32, context_len=3)
    pos_title_conv = paddle.networks.simple_gru(input=pos_title_emb, size=64)
    pos_title_fc = paddle.layer.fc(input=pos_title_conv, size=64, act=paddle.activation.Tanh())

    neg_title_id = paddle.layer.data(
        name='neg_title',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    neg_title_emb = paddle.layer.embedding(input=neg_title_id, size=64)
    #neg_title_conv = paddle.networks.sequence_conv_pool(
    #    input=neg_title_emb, hidden_size=32, context_len=3)
    neg_title_conv = paddle.networks.simple_gru(input=neg_title_emb, size=64)
    neg_title_fc = paddle.layer.fc(input=neg_title_conv, size=64, act=paddle.activation.Tanh())
 
    pos_inference = paddle.layer.cos_sim(a=query_fc, b=pos_title_fc, size=1, scale=1)
    neg_inference = paddle.layer.cos_sim(a=query_fc, b=neg_title_fc, size=1, scale=1)
    label = paddle.layer.data(name='label', type=paddle.data_type.integer_value(1))
    cost = paddle.layer.rank_cost(left=pos_inference, right=neg_inference, label=label)
    output = 0
    if pos_inference > neg_inference:
        output = 1
    return cost, output, label
```

**Comment by hikkinight** [comment]
补充stack信息
`Thu Nov  2 13:25:03 2017[1,0]<stderr>:F1102 13:25:03.481375  5208 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples
Thu Nov  2 13:25:03 2017[1,0]<stderr>:*** Check failure stack trace: ***
Thu Nov  2 13:25:03 2017[1,0]<stderr>:F1102 13:25:03.483494  5210 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples
Thu Nov  2 13:25:03 2017[1,0]<stderr>:*** Check failure stack trace: ***
Thu Nov  2 13:25:03 2017[1,0]<stderr>:F1102 13:25:03.483494  5210 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples F1102 13:25:03.483767  5211 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples
Thu Nov  2 13:25:03 2017[1,0]<stderr>:*** Check failure stack trace: ***
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589427d  google::LogMessage::Fail()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589427d  google::LogMessage::Fail()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589427d  google::LogMessage::Fail()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695897d2c  google::LogMessage::SendToLog()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:F1102 13:25:03.483494  5210 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples F1102 13:25:03.483767  5211 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples F1102 13:25:03.491542  5209 CosSimOp.cpp:43] Check failed: in2_mat.getHeight() == 1LU || in2_mat.getHeight() == num_samples
Thu Nov  2 13:25:03 2017[1,0]<stderr>:*** Check failure stack trace: ***
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695897d2c  google::LogMessage::SendToLog()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695897d2c  google::LogMessage::SendToLog()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695893da3  google::LogMessage::Flush()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589427d  google::LogMessage::Fail()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695893da3  google::LogMessage::Flush()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695893da3  google::LogMessage::Flush()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589923e  google::LogMessageFatal::~LogMessageFatal()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695897d2c  google::LogMessage::SendToLog()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589923e  google::LogMessageFatal::~LogMessageFatal()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589923e  google::LogMessageFatal::~LogMessageFatal()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956bf970  paddle::CosSimForward<>()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695893da3  google::LogMessage::Flush()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956bf970  paddle::CosSimForward<>()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956c48e5  paddle::CosSimForwardFunc<>::calc()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956bf970  paddle::CosSimForward<>()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69589923e  google::LogMessageFatal::~LogMessageFatal()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956c48e5  paddle::CosSimForwardFunc<>::calc()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695608a2f  paddle::CosSimLayer::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956c48e5  paddle::CosSimForwardFunc<>::calc()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956bf970  paddle::CosSimForward<>()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695608a2f  paddle::CosSimLayer::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695654562  paddle::NeuralNetwork::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe6956c48e5  paddle::CosSimForwardFunc<>::calc()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695608a2f  paddle::CosSimLayer::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695654562  paddle::NeuralNetwork::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565d1e4  paddle::TrainerThread::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695608a2f  paddle::CosSimLayer::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695654562  paddle::NeuralNetwork::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565d1e4  paddle::TrainerThread::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565e665  paddle::TrainerThread::computeThread()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69484a8a0  execute_native_thread_routine
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe695654562  paddle::NeuralNetwork::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565e665  paddle::TrainerThread::computeThread()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565d1e4  paddle::TrainerThread::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69853b1c3  start_thread
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565d1e4  paddle::TrainerThread::forward()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69484a8a0  execute_native_thread_routine
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565e665  paddle::TrainerThread::computeThread()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe697b6312d  __clone
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69565e665  paddle::TrainerThread::computeThread()
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69853b1c3  start_thread
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @     0x7fe69484a8a0  execute_native_thread_routine
Thu Nov  2 13:25:03 2017[1,0]<stderr>:    @              (nil)  (unknown)
Thu Nov  2 13:25:03 2017[1,0]<stderr>:./train.sh: line 239:  4196 Aborted                 python27-gcc482/bin/python conf/trainer_config.conf
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ '[' 134 -ne 0 ']'
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ kill_pserver2_exit
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ ps aux
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ grep paddle_pserver2
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ grep paddle_cluster_job
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ grep -v grep
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ cut -c10-14
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ xargs kill -9
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Thu Nov  2 13:25:03 2017[1,0]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Thu Nov  2 13:25:03 2017[1,0]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ get_stack
Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ set +x
1Thu Nov  2 13:25:03 2017[1,0]<stderr>:
00Thu Nov  2 13:25:03 2017[1,0]<stderr>:*********************Shell Script Stack Trace********************
 Thu Nov  2 13:25:03 2017[1,0]<stderr>: @: [./log.sh: 41] log_fatal
68Thu Nov  2 13:25:03 2017[1,0]<stderr>: @: [./common.sh: 399] kill_pserver2_exit
81kThu Nov  2 13:25:03 2017[1,0]<stderr>: @: [./train.sh: 242] main
  Thu Nov  2 13:25:03 2017[1,0]<stderr>:
  Thu Nov  2 13:25:03 2017[1,0]<stderr>:+ exit 1`

**Comment by will-am** [comment]
```
label = paddle.layer.data(name='label', type=paddle.data_type.integer_value(1))
```
label不应该是integer_value，应该是维度是1的dense_vector:
```
label = paddle.layer.data(name='label', type=paddle.data_type.dense_vector(1))
```
integer_value对应的是one-hot vector，既相应的位置是1，其他位置全是0的一个vector。

datareader里
```
yield query_vec, pos_title_vec, neg_title_vec, 1
```
相应的也要改成
```
yield query_vec, pos_title_vec, neg_title_vec, [1]
```

**Comment by hikkinight** [comment]
不是这个问题。label的data_type改为了dense_vector，还是报这个错误。
我是用receiver提交的mpi任务，会不会receiver的paddle 版本对simple_gru支持的有问题呢？毕竟换成cnn后（sequence_conv_pool）就不报错了

**Comment by hikkinight** [comment]
已验证，通过receiver提交的任务：
paddle.networks.simple_lstm
paddle.networks.simple_gru 
都会报上述的错误，而paddle.networks.sequence_conv_pool不会出错

**Comment by hikkinight** [comment]
更新网络
```python
def fc_net(dict_dim):
    # input layers
    dict_dim_real = int(dict_dim + 1)
    query_id = paddle.layer.data(
        name='query',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    query_emb = paddle.layer.embedding(input=query_id, size=128)
    #query_conv = paddle.networks.sequence_conv_pool(
    #    input=query_emb, hidden_size=64, context_len=3)
    query_conv = paddle.networks.simple_gru(input=query_emb, size=64)
    query_pool = paddle.layer.pooling(
            input=query_conv,
            agg_level=paddle.layer.AggregateLevel.EACH_SEQUENCE
        )
    query_fc = paddle.layer.fc(input=query_pool, size=32, act=paddle.activation.Tanh())
    
    pos_title_id = paddle.layer.data(
        name='pos_title',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    pos_title_emb = paddle.layer.embedding(input=pos_title_id, size=128)
    #pos_title_conv = paddle.networks.sequence_conv_pool(
    #   input=pos_title_emb, hidden_size=64, context_len=3)
    pos_title_conv = paddle.networks.simple_gru(input=pos_title_emb, size=64)
    pos_title_pool = paddle.layer.pooling(
            input=pos_title_conv,
            agg_level=paddle.layer.AggregateLevel.EACH_SEQUENCE
        ) 
    pos_title_fc = paddle.layer.fc(input=pos_title_pool, size=32, act=paddle.activation.Tanh())

    neg_title_id = paddle.layer.data(
        name='neg_title',
        type=paddle.data_type.integer_value_sequence(dict_dim_real))
    neg_title_emb = paddle.layer.embedding(input=neg_title_id, size=128)
    #neg_title_conv = paddle.networks.sequence_conv_pool(
    #   input=neg_title_emb, hidden_size=64, context_len=3)
    neg_title_conv = paddle.networks.simple_gru(input=neg_title_emb, size=64)
    neg_title_pool = paddle.layer.pooling(
            input=neg_title_conv,
            agg_level=paddle.layer.AggregateLevel.EACH_SEQUENCE
        )
    neg_title_fc = paddle.layer.fc(input=neg_title_pool, size=32, act=paddle.activation.Tanh())
 
    pos_inference = paddle.layer.cos_sim(a=query_fc, b=pos_title_fc, size=1, scale=1)
    neg_inference = paddle.layer.cos_sim(a=query_fc, b=neg_title_fc, size=1, scale=1)
    label = paddle.layer.data(name='label', type=paddle.data_type.dense_vector(1))
    cost = paddle.layer.rank_cost(left=pos_inference, right=neg_inference, label=label)
    output = 0
    if pos_inference > neg_inference:
        output = 1
    return cost, output, label

```
