### ISSUE TITLE
AdamDenseParamSparseGradKernel和AdamDenseKernel计算逻辑不一致？

### ISSUE THREAD

**Issue by happyfc1** [PaddlePaddle/Paddle#53052]
### 请提出你的问题 Please ask your question

adam的计算逻辑为：

`lr *= sqrt(1 - beta2_pow) / (1 - beta1_pow);`
`moment1_out = beta1_ * mom1 + (1 - beta1_) * g;`
`moment2_out = beta2_ * mom2 + (1 - beta2_) * g * g;`
`param_out = param - lr * (moment1_out / (moment2_out.sqrt() +epsilon_ * sqrt(1 - beta2_pow)));`

当初始param为0，g为1，lr为1，epsilon为0，mom1和mom2为0；beta1=beta1_pow，beta2=beta2_pow分别为以下数值时，param_out结果如下：
（此处为一表格）
                        beta1=0    beta1=0.5    beta1=0.999
beta2=0          out=-1       out=-1         out=-1
beta2=0.5       out=-1       out=-1         out=-1
beta2=0.999   out=-1       out=-1         out=-1
**out均在-1左右，通过公式可知第一个step可简化为param_out = param - lr，结果与beta1、beta2无关**

而使用AdamDenseParamSparseGradKernel处理SeletedRows时，param_out结果如下：
（此处为一表格）
                       beta1=0    beta1=0.5    beta1=0.999
beta2=0          out=-1       out=-0.666  out=-0.5
beta2=0.5       out=-1.224  out=-0.816  out=-0.612
beta2=0.999   out=-1.414  out=-0.942  out=-0.707
**结果和beta1、beta2相关**

请问AdamDenseParamSparseGradKernel中的计算公式具体是什么？是否有误？

**Comment by wangzhen38** [comment]
计算公式应该是没问题的，可以参考这里哈，https://github.com/PaddlePaddle/Paddle/blob/205a4d9a9ecfb8044e03f1e6ea7378d485589c1b/paddle/phi/kernels/funcs/adam_functors.h#L339

**Comment by happyfc1** [comment]
![image](https://user-images.githubusercontent.com/130947796/232983474-9ae907cc-e2ca-4a37-9921-32faa6a7dd90.png)
其结果为
![image](https://user-images.githubusercontent.com/130947796/232983541-03ca197e-524d-4807-af9d-1217c6cac113.png)

如果调整embedding为sparse
![image](https://user-images.githubusercontent.com/130947796/232983629-79ef8c46-e35c-468d-9c2b-53e00ce0ed2f.png)
其结果为
![image](https://user-images.githubusercontent.com/130947796/232983742-2a26be1e-fd10-413d-abab-022c858762a7.png)

为什么AdamDenseParamSparseGradKernel和AdamDenseKernel计算逻辑不一致？

**Comment by wangzhen38** [comment]
Adam 算法有两个移动平均累加器。累加器在每一步都会更新。在密集模式和稀疏模式下，两条移动平均线的每个元素都会更新。如果参数非常大，那么更新可能很慢。稀疏模式下更新当前具有梯度的元素，所以它会更快。但是这种模式与原始的算法有不同的描述，可能会导致不同的结果

**Comment by happyfc1** [comment]
感谢你的回复
sparse adam是adam的一种加速手段，当初始条件相同时，其结果应当和adam一致
但从实验结果来看，sparse adam并没有做到

**Comment by chudouye** [comment]
> Adam 算法有两个移动平均累加器。累加器在每一步都会更新。在密集模式和稀疏模式下，两条移动平均线的每个元素都会更新。如果参数非常大，那么更新可能很慢。稀疏模式下更新当前具有梯度的元素，所以它会更快。但是这种模式与原始的算法有不同的描述，可能会导致不同的结果

CPU的sparse adam的确存在问题，看代码更新参数的时候使用的beta1_pow和beta2_pow其实是beta1_pow * beta1和beta2_pow * beta2，也就是说beta_pow多乘了一次beta。
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/selected_rows/cpu/adam_kernel.cc#L160

**Comment by chudouye** [comment]
使用下面的代码可以清楚的看出来这个问题。其输出为
```Python
import math
import paddle
import torch


def adam_update(
    param, grad, lr, beta1, beta2, beta1_p, beta2_p, mom1=0, mom2=0, eps=1e-8
):
    lr = lr * math.sqrt(1 - beta2_p) / (1 - beta1_p)
    mom1 = beta1 * mom1 + (1 - beta1) * grad
    mom2 = beta2 * mom2 + (1 - beta2) * grad * grad
    param = param - lr * mom1 / (math.sqrt(mom2) + eps)
    return param


def main():
    lr = 1.0
    eps = 1e-8

    for beta1 in [0, 0.5, 0.9999]:
        for beta2 in [0, 0.5, 0.9999]:
            result = []
            for sparse in (False, True):
                model = paddle.nn.Embedding(
                    1,
                    1,
                    sparse=sparse,
                    weight_attr=paddle.nn.initializer.Constant(0),
                )
                x = paddle.zeros([1, 1], dtype='int64')
                y = model(x)
                g = paddle.ones([1, 1, 1], dtype='float32')
                paddle.autograd.backward([y], [g])
                opt = paddle.optimizer.Adam(
                    lr, beta1, beta2, eps, parameters=model.parameters()
                )
                opt.step()
                result.append(model.weight.numpy()[0, 0])

            res0 = adam_update(0.0, 1.0, lr, beta1, beta2, beta1, beta2)
            res1 = adam_update(
                0.0, 1.0, lr, beta1, beta2, beta1 * beta1, beta2 * beta2
            )
            print(f'beta1 {beta1}, beta2 {beta2}')
            print(
                f'dense result {result[0]}, sparse result {result[1]}, res0 {res0}, res1 {res1}'
            )

    # for sparse in (False, True):
    #     for beta1 in [0, 0.5, 0.9999]:
    #         for beta2 in [0, 0.5, 0.9999]:
    #             model = torch.nn.Embedding(
    #                 1,
    #                 1,
    #                 sparse=sparse,
    #                 _weight=torch.zeros(1, 1, dtype=torch.float),
    #             )
    #             x = torch.zeros(1, 1, dtype=torch.int64)
    #             y = model(x)
    #             g = torch.ones(1, 1, 1, dtype=torch.float)
    #             torch.autograd.backward([y], [g])
    #             if sparse:
    #                 opt = torch.optim.SparseAdam(
    #                     model.parameters(), lr, [beta1, beta2], eps
    #                 )
    #             else:
    #                 opt = torch.optim.Adam(
    #                     model.parameters(), lr, [beta1, beta2], eps
    #                 )
    #             for i in range(steps):
    #                 opt.step()
    #             print(
    #                 f'torch sparse {sparse}: beta1 {beta1}, beta2 {beta2}, weight {model.weight.detach().numpy()[0, 0]}'
    #             )


if __name__ == '__main__':
    main()
```

```Shell
beta1 0, beta2 0
dense result -1.0, sparse result -1.0, res0 -0.9999999900000002, res1 -0.9999999900000002
beta1 0, beta2 0.5
dense result -0.9999999403953552, sparse result -1.2247447967529297, res0 -0.9999999858578645, res1 -1.224744854071081
beta1 0, beta2 0.9999
dense result -1.0, sparse result -1.4142135381698608, res0 -0.9999990000010001, res1 -1.414176792415113
beta1 0.5, beta2 0
dense result -1.0, sparse result -0.6666666865348816, res0 -0.9999999900000002, res1 -0.6666666600000001
beta1 0.5, beta2 0.5
dense result -0.9999999403953552, sparse result -0.8164965510368347, res0 -0.9999999858578645, res1 -0.8164965693807207
beta1 0.5, beta2 0.9999
dense result -1.0, sparse result -0.9428091049194336, res0 -0.9999990000010001, res1 -0.942784528276742
beta1 0.9999, beta2 0
dense result -1.0, sparse result -0.5, res0 -0.9999999900000001, res1 -0.5000249962499382
beta1 0.9999, beta2 0.5
dense result -0.9999999403953552, sparse result -0.6123724579811096, res0 -0.9999999858578645, res1 -0.6124030471880538
beta1 0.9999, beta2 0.9999
dense result -1.0, sparse result -0.7071067690849304, res0 -0.9999990000010001, res1 -0.7071237523953539
```

**Comment by chudouye** [comment]
另外还有个问题，adam中为什么要将epsilon乘上sqrt(1 - beta2_pow)
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/adam_functors.h#L490
这和adam的公式不符合
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/Adam_cn.html#adam
