### ISSUE TITLE
提交PR提示“The PR is not created using  PR's template.”但已按参考例子提交，仍然报错，想咨询是什么原因以及需要怎么修改呐

### ISSUE THREAD

**Issue by alimagic** [PaddlePaddle/Paddle#53064]
### 问题描述 Please describe your issue

在提交PR提示“The PR is not created using  PR's template.”但已按参考例子提交，仍然报错，想咨询是什么原因以及需要怎么修改呐？
A、PR如下：https://github.com/PaddlePaddle/Paddle/pull/53062
B，PR格式如下：
PR types
Function optimization

PR changes
Others

Describe
1、add multi threads to accelerate quant fused_multi_transformer_xpu_pass

C、报错如下：
![image](https://user-images.githubusercontent.com/9319195/232958280-7431c758-c4b9-4796-8673-abd711a5864a.png)
![image](https://user-images.githubusercontent.com/9319195/232958343-8804c9ca-3695-4be5-9a65-5a503084fba5.png)

**Comment by LiYuRio** [comment]
不要更改这里提交pr的markdown语法，可以参考其他pr，把markdown复制过来。
<img width="697" alt="image" src="https://user-images.githubusercontent.com/63526175/232958893-0a4e2722-4cb6-4cd8-b495-6b47a4bb6c83.png">

比如这里的PR types等应该是Header，而不是普通字体
