### ISSUE TITLE
BF16 Tensor创建问题

### ISSUE THREAD

**Issue by linjieccc** [PaddlePaddle/Paddle#53068]
### bug描述 Describe the Bug

BF16下tensor构建有误，复现方式如下：

```python
import torch
import paddle

torch.tensor(-1e6, dtype=torch.bfloat16)
paddle.to_tensor(-1e6, dtype=paddle.bfloat16)
'''
tensor(-999424., dtype=torch.bfloat16)
Tensor(shape=[1], dtype=bfloat16, place=Place(gpu:0), stop_gradient=True,
       [-0.09375000])
'''
```

**Comment by LiYuRio** [comment]
感谢你的反馈，这确实是个bug，后续会找对应负责人修复

**Comment by zhouwei25** [comment]
![infoflow 2023-04-19 14-54-33](https://user-images.githubusercontent.com/52485244/232991244-cde08cc2-13af-45aa-9c51-e4c825fe585e.png)
目前这个api还不支持bfloat16

**Comment by zhwesky2010** [comment]
与这个问题可能类似 https://github.com/PaddlePaddle/Paddle/issues/34927

**Comment by zhwesky2010** [comment]
@xinyu-intel https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/creation.py#L616 it's astype here, and `convert_dtype` return `np.uint16` ,  this 16 bits will not right. 

And then, this 16 bits will be copy to `Tensor.data` in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/tensor_py.h#L524, and the value of tensor will be wrong.

**Comment by zhwesky2010** [comment]
suppoted in https://github.com/PaddlePaddle/Paddle/pull/53151

**Comment by xinyu-intel** [comment]
> #53151 使用 `paddle.cast` 先进行了支持

Hi, sorry for the late reply. As you mentioned, numpy doesn't have native support for bfloat16 data type. So`astype()` here introduced the wrong typecast from fp64 to uint16. I think your fix is correct to solve the problem a.k.a skip numpy typecast and use paddle typecast directly.

Regarding the issue, what will be the problem to use paddle.cast? I checked from PyTorch side https://github.com/pytorch/pytorch/blob/main/torch/csrc/utils/tensor_new.cpp#L319, it creates numpy tensor with dtype infered from `PyArray_TYPE` and then use `torch.to()` for casting to the defined dtype whatever it has bfloat16 dtype.

**Comment by zhwesky2010** [comment]
@xinyu-intel In addition to use `paddle.cast` , it also work to use another custom implement of `ndarray.asttype ('unint16 ')`. In https://github.com/PaddlePaddle/Paddle/pull/53151 . I will merge this.
