### ISSUE TITLE
始终无法解决shape的问题

### ISSUE THREAD

**Issue by banping957** [PaddlePaddle/Paddle#53086]
### bug描述 Describe the Bug

下面是全代码和报错信息，版本都是最新的paddelpaddle和paddlenlp，使用了很多方法都无法搞定reshape的问题
from paddlenlp.transformers import ErnieModel, ErnieTokenizer
import paddle
from sklearn.metrics import classification_report, confusion_matrix, f1_score
class CustomErnieModel(ErnieModel):
    def __init__(self, *args, num_classes=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.dropout = paddle.nn.Dropout(self.config["hidden_dropout_prob"])
        self.classifier = paddle.nn.Linear(self.config["hidden_size"], num_classes) if num_classes is not None else None
    def forward(self, input_ids, token_type_ids=None, position_ids=None, attention_mask=None, return_dict=False):
        sequence_output, pooled_output = super().forward(input_ids, token_type_ids, position_ids, attention_mask,return_dict)
        print("pooled_output.shape:", pooled_output.shape)  # Add this line
        pooled_output = pooled_output.reshape((-1, self.config["hidden_size"]))
        logits = self.classifier(pooled_output)
        return logits
    @classmethod
    def from_pretrained(cls, pretrained_model_name_or_path, *model_args, **model_kwargs):
        num_classes = model_kwargs.pop('num_classes', None)
        base_model = super().from_pretrained(pretrained_model_name_or_path, *model_args, **model_kwargs)
        model = cls(base_model.config, num_classes=num_classes, **model_kwargs)
        model.set_dict(base_model.state_dict())
        return model
class CustomDataset(paddle.io.Dataset):
    def __init__(self, data, tokenizer, max_seq_length=512):
        self.data = data
        self.labels = [d[1] for d in data]
        self.tokenizer = tokenizer
        self.max_seq_length = max_seq_length
    def __getitem__(self, index):
        example = self.data[index]
        input_ids, token_type_ids, attention_mask, label = convert_example(example[0], example[1], self.tokenizer, self.max_seq_length)
        return input_ids, token_type_ids, attention_mask, label
    def __len__(self):
        return len(self.data)
def collate_fn(batch, tokenizer):
    input_ids, token_type_ids, attention_mask, labels = zip(*batch)
    max_len = max([len(x) for x in input_ids])
    padded_input_ids = []
    padded_token_type_ids = []
    padded_attention_mask = []
    for i in range(len(input_ids)):
        input_ids_i = input_ids[i] + [tokenizer.pad_token_id] * (max_len - len(input_ids[i]))
        token_type_ids_i = token_type_ids[i] + [0] * (max_len - len(token_type_ids[i]))
        attention_mask_i = attention_mask[i] + [0] * (max_len - len(attention_mask[i]))
        padded_input_ids.append(input_ids_i)
        padded_token_type_ids.append(token_type_ids_i)
        padded_attention_mask.append(attention_mask_i)
    input_ids = paddle.to_tensor(padded_input_ids)
    token_type_ids = paddle.to_tensor(padded_token_type_ids)
    attention_mask = paddle.to_tensor(padded_attention_mask)
    labels = paddle.to_tensor(labels, dtype="int64")
    return input_ids, token_type_ids, attention_mask, labels
def convert_example(text, label, tokenizer, max_seq_length=512):
    assert label in [0, 1], f"Invalid label: {label}"
    encoded_inputs = tokenizer(text=text, max_seq_len=max_seq_length, pad_to_max_seq_len=False)
    input_ids = encoded_inputs['input_ids']
    token_type_ids = encoded_inputs['token_type_ids']
    attention_mask = [1 if token_id != tokenizer.pad_token_id else 0 for token_id in input_ids]
    return input_ids, token_type_ids, attention_mask, label
sample_data = [
    ("这是一个正面的评论。", 1),
    ("这是一个负面的评论。", 0),
    ("我喜欢这个产品。", 1),
    ("我不喜欢这个产品。", 0),
]
model_name = "ernie-1.0"
tokenizer = ErnieTokenizer.from_pretrained(model_name)
custom_ernie = CustomErnieModel.from_pretrained(model_name, num_classes=2)
model = paddle.Model(custom_ernie)
# 将数据拆分为训练和测试集
train_size = int(0.8 * len(sample_data))
X_train, y_train = zip(*sample_data[:train_size])
X_test, y_test = zip(*sample_data[train_size:])
# 使用您提供的代码处理数据
train_dataset = CustomDataset(list(zip(X_train, y_train)), tokenizer, max_seq_length=512)
test_dataset = CustomDataset(list(zip(X_test, y_test)), tokenizer, max_seq_length=512)
train_data_loader = paddle.io.DataLoader(train_dataset, batch_size=2, shuffle=True, collate_fn=lambda x: collate_fn(x, tokenizer))
test_data_loader = paddle.io.DataLoader(test_dataset, batch_size=2, shuffle=False, collate_fn=lambda x: collate_fn(x, tokenizer))
optimizer = paddle.optimizer.Adam(learning_rate=2e-5, parameters=model.parameters())
loss_fn = paddle.nn.loss.CrossEntropyLoss()
metric = paddle.metric.Accuracy()
model.prepare(optimizer, loss_fn, metric)
model.fit(train_data_loader, epochs=3, verbose=1, batch_size=2)
predictions = model.predict(test_data_loader)
y_pred = [pred[0] for pred in predictions[0].argmax(axis=1)]
print("PaddleNLP Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("F1 Score: {:.3f}".format(f1_score(y_test, y_pred)))

报错信息为：
File "C:\Users\Administrator\PycharmProjects\pythonProject\paddle模型.py", line 149, in <module>
    model.fit(train_data_loader, epochs=3, verbose=1, batch_size=2)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\hapi\model.py", line 1929, in fit
    logs = self._run_one_epoch(train_loader, cbks, 'train')
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\hapi\model.py", line 2282, in _run_one_epoch
    outs = getattr(self, mode + '_batch')(*_inputs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\hapi\model.py", line 1207, in train_batch
    loss = self._adapter.train_batch(inputs, labels, update)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\hapi\model.py", line 806, in train_batch
    outputs = self.model.network(*[to_variable(x) for x in inputs])
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\Users\Administrator\PycharmProjects\pythonProject\paddle模型.py", line 22, in forward
    sequence_output, pooled_output = super().forward(input_ids, token_type_ids, position_ids, attention_mask,
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\transformers\ernie\modeling.py", line 357, in forward
    encoder_outputs = self.encoder(
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\transformers\model_outputs.py", line 300, in _transformer_encoder_fwd
    layer_outputs = mod(
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddlenlp\transformers\model_outputs.py", line 82, in _transformer_encoder_layer_fwd
    attn_outputs = self.self_attn(src, src, src, src_mask, cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\fluid\dygraph\layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\nn\layer\transformer.py", line 408, in forward
    q, k, v = self._prepare_qkv(query, key, value, cache)
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\nn\layer\transformer.py", line 235, in _prepare_qkv
    q = tensor.reshape(x=q, shape=[0, 0, self.num_heads, self.head_dim])
  File "C:\ProgramData\Anaconda3\lib\site-packages\paddle\tensor\manipulation.py", line 3543, in reshape
    out = _C_ops.reshape(x, shape)
ValueError: (InvalidArgument) The 'shape' in ReshapeOp is invalid. The input tensor X'size must be equal to the capacity of 'shape'. But received X's shape = [2, 2, 12, 768], X's size = 36864, 'shape' is [0, 0, 12, 64], the capacity of 'shape' is 3072.
  [Hint: Expected capacity == in_size, but received capacity:3072 != in_size:36864.] (at ..\paddle\phi\infermeta\unary.cc:1435)

**Comment by LiYuRio** [comment]
按报错信息说的，是不是模型配置错了，在transformer里num_head是12，hidden_size是64，但你的q怎么会是一个2, 2, 12, 768的tensor呢

**Comment by banping957** [comment]
ErnieConfig {
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "relu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 513,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 2,
  "use_task_id": false,
  "vocab_size": 18000
}
我这个配置好像没问题哎

**Comment by LiYuRio** [comment]
麻烦在模型里打印打印值，看看是不是没生效，就从报错来看，是对不上的

**Comment by banping957** [comment]
model_name = "ernie-1.0"
tokenizer = ErnieTokenizer.from_pretrained(model_name)
custom_ernie = CustomErnieModel.from_pretrained(model_name, num_classes=2)
**print(custom_ernie.config)  #我增加了这一句打印**
打印的结果就是这个
ErnieConfig {
  "attention_probs_dropout_prob": 0.1,
  "enable_recompute": false,
  "fuse": false,
  "hidden_act": "relu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 513,
  "model_type": "ernie",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "paddlenlp_version": null,
  "pool_act": "tanh",
  "task_id": 0,
  "task_type_vocab_size": 3,
  "type_vocab_size": 2,
  "use_task_id": false,
  "vocab_size": 18000
}

**Comment by LiYuRio** [comment]
你这里打印的是模型配置，我的意思是，在模型里打印打印shape，从你给的信息里，在transformer里num_head是12，hidden_size是64，和你的模型配置对不上

**Comment by banping957** [comment]
是这个么
(0): TransformerEncoderLayer(
          (self_attn): MultiHeadAttention(
            (q_proj): Linear(in_features=768, out_features=768, dtype=float32)
            (k_proj): Linear(in_features=768, out_features=768, dtype=float32)
            (v_proj): Linear(in_features=768, out_features=768, dtype=float32)
            (out_proj): Linear(in_features=768, out_features=768, dtype=float32)
          )
          (linear1): Linear(in_features=768, out_features=3072, dtype=float32)
          (dropout): Dropout(p=0, axis=None, mode=upscale_in_train)
          (linear2): Linear(in_features=3072, out_features=768, dtype=float32)
          (norm1): LayerNorm(normalized_shape=[768], epsilon=1e-12)
          (norm2): LayerNorm(normalized_shape=[768], epsilon=1e-12)
          (dropout1): Dropout(p=0.1, axis=None, mode=upscale_in_train)
          (dropout2): Dropout(p=0.1, axis=None, mode=upscale_in_train)
        )

**Comment by LiYuRio** [comment]
不是，这打印的还是模型参数，建议在执行过程中通过x.shape诸如类似的方式打印

**Comment by banping957** [comment]
在下面代码增加了打印shape
def collate_fn(batch, tokenizer):
    input_ids, token_type_ids, attention_mask, labels = zip(*batch)
    max_len = max([len(x) for x in input_ids])
    input_ids_padded = []
    token_type_ids_padded = []
    attention_mask_padded = []
    for i in range(len(input_ids)):
        padding_length = max_len - len(input_ids[i])
        input_ids_padded.append(input_ids[i] + [tokenizer.pad_token_id] * padding_length)
        token_type_ids_padded.append(token_type_ids[i] + [0] * padding_length)
        attention_mask_padded.append(attention_mask[i] + [0] * padding_length)
    input_ids = paddle.to_tensor(input_ids_padded)
    token_type_ids = paddle.to_tensor(token_type_ids_padded)
    attention_mask = paddle.to_tensor(attention_mask_padded, dtype='int64')
    labels = paddle.to_tensor(labels, dtype="int64")
    print("input_ids.shape:", input_ids.shape)
    print("token_type_ids.shape:", token_type_ids.shape)
    print("attention_mask.shape:", attention_mask.shape)
    print("labels.shape:", labels.shape)
    return input_ids, token_type_ids, attention_mask, label
结果如下：
input_ids.shape: [2, 12]
token_type_ids.shape: [2, 12]
attention_mask.shape: [2, 12, 1]
labels.shape: [2]
input_ids.shape: [1, 10]
token_type_ids.shape: [1, 10]
attention_mask.shape: [1, 10, 1]
labels.shape: [1]
报错如下：
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [2, 12, 768] and the shape of Y = [2, 12, 1, 768]. Received [2] in X is not equal to [12] in Y at i:1.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home\workspace\Paddle_release\paddle/fluid/operators/elementwise/elementwise_op_function.h:240)
  [operator < elementwise_add > error]
我将版本降为2.2了

**Comment by LiYuRio** [comment]
啥意思，没理解，之前不是能跑吗，你改了啥

**Comment by banping957** [comment]
在gpt的帮助下 我解决了问题 谢谢大佬帮忙
