### ISSUE TITLE
InvalidArgumentError: Invalid python callable id 0, which should be less than 0.   [Hint: Expected i < g_py_callables.size(), but received i:0 >= g_py_callables.size():0.] at (baidu/third-party/paddle/paddle/fluid/operators/py_func_op.cc:49)   [operator < py_func > error]

### ISSUE THREAD

**Issue by Sky-zzt** [PaddlePaddle/Paddle#53103]
### 请提出你的问题 Please ask your question

生产环境使用py_func 报错。paddle版本1.8 
报错信息
python
`paddle/fluid/layer_helper.py", line 43, in append_op
    return self.main_program.current_block().append_op(*args, **kwargs)
paddle/fluid/layers/nn.py", line 14568, in py_func
    'backward_skip_vars': list(backward_skip_vars)`
c++

`InvalidArgumentError: Invalid python callable id 0, which should be less than 0.
  [Hint: Expected i < g_py_callables.size(), but received i:0 >= g_py_callables.size():0.] at (baidu/third-party/paddle/paddle/fluid/operators/py_func_op.cc:49)
  [operator < py_func > error]`

代码：
<img width="541" alt="image" src="https://user-images.githubusercontent.com/52705155/233148480-2fe5b13a-f1ca-4a5e-85c2-77b69b600507.png">
<img width="941" alt="image" src="https://user-images.githubusercontent.com/52705155/233148008-cb24db49-d80b-4bf7-9c2c-867e6a8f09d1.png">

**Comment by lym0302** [comment]
您好，可以尝试下新版本的paddle

**Comment by jiweibo** [comment]
py_func大概是1.4之前为支持自定义算子使用的方式，限制、性能等问题较多，目前没有继续维护的计划。
动态图、自定义算子均已比较完善，您可以考虑以上方案。
