### ISSUE TITLE
源码编译paddle 后，出现报错不能import libpaddle

### ISSUE THREAD

**Issue by xman1991** [PaddlePaddle/Paddle#53117]
### bug描述 Describe the Bug

 cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import) 

软件环境： kylin v10  cuda-10.2
硬件环境：phytium d2000  nvidia GTX-1060
源码成功编译后，
import paddle报错：
 cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import)

**Comment by xman1991** [comment]
项目紧急，希望尽快得到回复。

**Comment by lym0302** [comment]
您好，请问编译的哪个版本的paddle？源码编译可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

**Comment by xman1991** [comment]
> 您好，请问编译的哪个版本的paddle？源码编译可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

是按照这个来的哈

**Comment by xman1991** [comment]
> 您好，请问编译的哪个版本的paddle？源码编译可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html

编译2.4.1

**Comment by qili93** [comment]
您好，根据这个报错信息

```
cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import)
```

可能是您在执行 import paddle的命令目录下或者PYTHONPATH环境中可能存在名为 paddle.py 的文件，导致Python在执行 import paddle的时候存在混淆。可以参考这个答案 https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m

如果不是由于以上原因造成的问题，请提供更多详细的报错日志信息，包括但不限于

1. Paddle 的源码 commit ID
2. 编译的 CMAKE 和 MAKE 命令
3. 编译出来的 paddle whl 安装包

另外，目前飞桨主要支持飞腾CPU的推理

https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html

对于飞腾CPU+英伟达GPU的组合飞桨侧暂无相应机器环境进行功能验证上的支持，很抱歉！

**Comment by xman1991** [comment]
> 您好，根据这个报错信息
> 
> ```
> cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import)
> ```
> 
> 可能是您在执行 import paddle的命令目录下或者PYTHONPATH环境中可能存在名为 paddle.py 的文件，导致Python在执行 import paddle的时候存在混淆。可以参考这个答案 https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m
> 
> 如果不是由于以上原因造成的问题，请提供更多详细的报错日志信息，包括但不限于
> 
> 1. Paddle 的源码 commit ID
> 2. 编译的 CMAKE 和 MAKE 命令
> 3. 编译出来的 paddle whl 安装包
> 
> 另外，目前飞桨主要支持飞腾CPU的推理
> 
> https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html
> 
> 对于飞腾CPU+英伟达GPU的组合飞桨侧暂无相应机器环境进行功能验证上的支持，很抱歉！
1、f0422a28d75f9345fa3b801c01cd0284b3b44be3
2、
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
make make TARGET=ARMV8 -j8
3、cpu和gpu版本以前都用过，但是备份丢失了；

**Comment by xman1991** [comment]
> > 您好，根据这个报错信息
> > ```
> > cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 可能是您在执行 import paddle的命令目录下或者PYTHONPATH环境中可能存在名为 paddle.py 的文件，导致Python在执行 import paddle的时候存在混淆。可以参考这个答案 https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m
> > 如果不是由于以上原因造成的问题，请提供更多详细的报错日志信息，包括但不限于
> > 
> > 1. Paddle 的源码 commit ID
> > 2. 编译的 CMAKE 和 MAKE 命令
> > 3. 编译出来的 paddle whl 安装包
> > 
> > 另外，目前飞桨主要支持飞腾CPU的推理
> > https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html
> > 对于飞腾CPU+英伟达GPU的组合飞桨侧暂无相应机器环境进行功能验证上的支持，很抱歉！
> > 1、f0422a28d75f9345fa3b801c01cd0284b3b44be3
> > 2、
> > cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
> > make make TARGET=ARMV8 -j8
> > 3、cpu和gpu版本以前都用过，但是备份丢失了；
我是用jetson拷贝的arm版cuda-10.2和cudnn8.2.1之前是可以的，但是机器已经不在了，备份也丢失了，我记得好像是cmake需要特定一下。

**Comment by xman1991** [comment]
> 您好，根据这个报错信息
> 
> ```
> cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import)
> ```
> 
> 可能是您在执行 import paddle的命令目录下或者PYTHONPATH环境中可能存在名为 paddle.py 的文件，导致Python在执行 import paddle的时候存在混淆。可以参考这个答案 https://stackoverflow.com/questions/64807163/importerror-cannot-import-name-from-partially-initialized-module-m
> 
> 如果不是由于以上原因造成的问题，请提供更多详细的报错日志信息，包括但不限于
> 
> 1. Paddle 的源码 commit ID
> 2. 编译的 CMAKE 和 MAKE 命令
> 3. 编译出来的 paddle whl 安装包
> 
> 另外，目前飞桨主要支持飞腾CPU的推理
> 
> https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html
> 
> 对于飞腾CPU+英伟达GPU的组合飞桨侧暂无相应机器环境进行功能验证上的支持，很抱歉！

(paddle-2.4) kylin@kylin-D2000:~/paddle/code/paddle-2.4/Paddle/build/python/dist$ python
Python 3.8.16 | packaged by conda-forge | (a9dbdca6, Jan 29 2023, 10:19:50)
[PyPy 7.3.11 with GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>> import paddle
Error: Can not import paddle core while this file exists: /home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/core.py", line 274, in <module>
    from . import libpaddle
ImportError: cannot import name 'libpaddle' from partially initialized module 'paddle.fluid' (most likely due to a circular import) (/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/framework/random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/home/kylin/.conda/envs/paddle-2.4/lib/pypy3.8/site-packages/paddle/fluid/core.py", line 333, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined
整个错误是这个。

**Comment by xman1991** [comment]
whl我应该怎么发给你呢？你邮箱是多少呢？

**Comment by xman1991** [comment]
你们编译jetson的cmake指令能否发一下呢？

**Comment by xman1991** [comment]
> 你们编译jetson的cmake指令能否发一下呢？

在jeston下编译paddle的cmake指令

**Comment by xman1991** [comment]
python换成3.7、gcc、g++换成7.5.0可以解决。

**Comment by hitzhu** [comment]
> python换成3.7、gcc、g++换成7.5.0可以解决。
你好请问麒麟系统升级gcc的具体帖子步骤你还有吗
