### ISSUE TITLE
你好，想问一下咱paddle的免费gpu现在不支持caffe这种框架了吗 

### ISSUE THREAD

**Issue by y1b2h3** [PaddlePaddle/Paddle#53121]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by Ligoml** [comment]
你好，AIStudio上仅支持使用paddle框架，其他框架都是不支持的哈
