### ISSUE TITLE
你好，想问一下咱paddle的免费gpu现在不支持caffe这种框架了吗 

### ISSUE THREAD

**Issue by y1b2h3** [PaddlePaddle/Paddle#53123]
### 请提出你的问题 Please ask your question

你好，想问一下咱paddle的免费gpu现在不支持caffe这种框架了吗

**Comment by lym0302** [comment]
您好， paddle的免费gpu 指的是什么？ AI studio 吗？

**Comment by y1b2h3** [comment]
嗯 是的

**Comment by Ligoml** [comment]
你好，AIStudio上仅支持使用paddle框架，其他框架都是不支持的哈
