### ISSUE TITLE
咨询PADDLE_WITH_CUSTOM_DEVICE编译选项的问题

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#53148]
### 问题描述 Issue Description

请问一下关于`PADDLE_WITH_CUSTOM_DEVICE`编译选项：我的cmake命令如下：
``` shell
cmake .. -DPY_VERSION=3.7 -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=ON -DWITH_MKL=OFF -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON -DCUDA_ARCH_NAME=Ampere
```
里面没有开`WITH_CUSTOM_DEVICE`。但是在编译的过程中，我开了`VERBOSE=1`，看到打印出来的实际编译命令行中间出现了`-DPADDLE_WITH_CUSTOM_DEVICE`这个选项。
我自己在代码库里面搜了一下相关的配置是怎么一层一层传递下来的，没找到，不知道是不是搜索方法有误。
我在官网搜索了文档，看到这个[编译选项表](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html#Compile)，里面也没提。
想问一下遇到这个选项开启，是否符合预期。

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：
> 最新develop

CUDA：
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2022 NVIDIA Corporation
> Built on Tue_Mar__8_18:18:20_PST_2022
> Cuda compilation tools, release 11.6, V11.6.124
> Build cuda_11.6.r11.6/compiler.31057947_0

硬件：
> A100

**Comment by lym0302** [comment]
您好，可以以最终使用是否正常为主，使用上没问题就OK

**Comment by lym0302** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt#L335

**Comment by houj04** [comment]
收到，多谢多谢~
