### ISSUE TITLE
Rename Python package framework.layers into fluid.layer

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5315]
Current we create a layer by calling `layers.fc`:

https://github.com/PaddlePaddle/Paddle/blob/66d1c6ce1edad4ee8505347c6dfab5a733b45772/python/paddle/v2/framework/tests/test_fit_a_line.py#L21-L25

However, it should be `layer.fc` instead -- no `s`.

-------

We are going to name the newly added features in `python/paddle/v2/framework` and related C++ code `fluid`.  So we should rename `python/paddle/v2/framework` into `python/paddle/v2/fluid`.

**Comment by Yancey1989** [comment]
I will close this issue, `python/paddle/v2/framework` has already been move to `python/paddle/fluid`
