### ISSUE TITLE
collective分布式训练中EagerGroup的dense_contents_为什么改成了每次都重新初始化

### ISSUE THREAD

**Issue by chudouye** [PaddlePaddle/Paddle#53159]
### collective分布式训练中EagerGroup的dense_contents_为什么改成了每次都重新初始化

相关改动对应这个PR，https://github.com/PaddlePaddle/Paddle/commit/196b01876a3f1e8b4c5a4599421d708fc5d34fcf
原来的实现是dense_contents_只在EagerGroup初始化时初始化一次，现在的实现时每次ConcatTensors都初始化一次。
因为dense_contents_时可以复用的，这么改是否没有必要且增加了不必要的开销？

**Comment by SmileGoat** [comment]
@ sneaxiy
麻烦回答一下

**Comment by sneaxiy** [comment]
这是为了节省显存。如果提前分配好空间，这个空间会一直占着，当模型参数量很大时这个空间是很可观的。

至于你说的开销问题，只是多了分配显存的开销，这个开销很小。

**Comment by chudouye** [comment]
> 这是为了节省显存。如果提前分配好空间，这个空间会一直占着，当模型参数量很大时这个空间是很可观的。
> 
> 至于你说的开销问题，只是多了分配显存的开销，这个开销很小。

了解了，多谢回复
