### ISSUE TITLE
docker安装paddle报错error: can not import paddle core while this file exists: /usr/local/lib/python3.6/site-packages/pad

### ISSUE THREAD

**Issue by hjing100** [PaddlePaddle/Paddle#53160]
### 问题描述 Issue Description

相关Dockerfile内容：
FROM python:3.7-slim as base_image
RUN pip install git+https://github.com/huggingface/transformers@c612628045822f909020f7eb6784c79700813eda flask==2.2.3
RUN pip install ConcurrentLogHandler numpy==1.18.5 pandas==1.1.0 setuptools==52.0.0
RUN pip install setuptools_scm django==3.1.7
RUN pip install paddlepaddle paddlenlp

### 版本&环境信息 Version & Environment Information

python3.7
docker安装paddlepaddle
linux环境

**Comment by SmileGoat** [comment]
上面的是python3.6 的报错，指定安装python3.7 吧
