### ISSUE TITLE
导入paddlehub里的stable_diffsusion模型出错

### ISSUE THREAD

**Issue by Xiaoyanxun** [PaddlePaddle/Paddle#53165]
### bug描述 Describe the Bug

最小可复现代码：
!pip install --upgrade paddlehub
!pip install xlwt

from PIL import Image
import paddlehub as hub
module = hub.Module(name='stable_diffusion')

**Comment by SmileGoat** [comment]
有什么更加详细的报错信息吗？

**Comment by Xiaoyanxun** [comment]
你好，我发截图给你看，麻烦处理一下啦
图1：

图2：



&nbsp;


韭菜盒子不要韭菜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 中午1:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 导入paddlehub里的stable_diffsusion模型出错 (Issue #53165)






有什么更加详细的报错信息吗？

—
直接回复这封邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by SmileGoat** [comment]
您好，图片都没有显示

**Comment by Xiaoyanxun** [comment]
你好，我重发截图给你看，麻烦处理一下啦
图1：


图2：



&nbsp;


韭菜盒子不要韭菜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 导入paddlehub里的stable_diffsusion模型出错 (Issue #53165)





 
您好，图片都没有显示

**Comment by SmileGoat** [comment]
看不到截图信息

**Comment by Xiaoyanxun** [comment]
你好，我重发截图给你看，以附件形式，麻烦处理一下啦
图1：
图2：




韭菜盒子不要韭菜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月21日(星期五) 中午1:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 导入paddlehub里的stable_diffsusion模型出错 (Issue #53165)





 
有什么更加详细的报错信息吗？

**Comment by Xiaoyanxun** [comment]
ImportError                               Traceback (most recent call last)
/tmp/ipykernel_289/1696474352.py in <module>
      1 from PIL import Image
      2 import paddlehub as hub
----> 3 module = hub.Module(name='stable_diffusion')

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, ignore_env_mismatch, **kwargs)
    398                     branch=branch,
    399                     ignore_env_mismatch=ignore_env_mismatch,
--> 400                     **kwargs)
    401                 CacheUpdater("update_cache", module=name, version=version).start()
    402             elif directory:

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, source, update, branch, ignore_env_mismatch, **kwargs)
    496                 update=update,
    497                 branch=branch,
--> 498                 ignore_env_mismatch=ignore_env_mismatch)
    499 
    500         directory = manager._get_normalized_path(user_module_cls.name)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in install(self, name, directory, archive, url, version, source, update, branch, ignore_env_mismatch)
    188                 if source:
    189                     return self._install_from_source(name, version, source, update, branch)
--> 190                 return self._install_from_name(name, version, ignore_env_mismatch)
    191         elif directory:
    192             return self._install_from_directory(directory)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_name(self, name, version, ignore_env_mismatch)
    263         for item in result:
    264             if name.lower() == item['name'].lower() and utils.Version(item['version']).match(version):
--> 265                 return self._install_from_url(item['url'])
    266 
    267         module_infos = module_server.get_module_compat_info(name=name)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_url(self, url)
    256                     bar.update(float(ds) / ts)
    257 
--> 258             return self._install_from_archive(file)
    259 
    260     def _install_from_name(self, name: str, version: str = None, ignore_env_mismatch: bool = False) -> HubModule:

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_archive(self, archive)
    378             path = os.path.normpath(path)
    379             directory = os.path.join(_tdir, path.split(os.sep)[0])
--> 380             return self._install_from_directory(directory)
    381 
    382     def _install_module_requirements(self, directory: str):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_directory(self, directory)
    362             self._install_module_requirements(directory)
    363 
--> 364             hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))
    365             self._local_modules[module_info.name] = hub_module_cls
    366 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in load(cls, directory)
    421         basename = os.path.split(directory)[-1]
    422         dirname = os.path.join(*list(os.path.split(directory)[:-1]))
--> 423         py_module = utils.load_py_module(dirname, '{}.module'.format(basename))
    424 
    425         for _item, _cls in inspect.getmembers(py_module, inspect.isclass):

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/utils/utils.py in load_py_module(python_path, py_module_name)
    248         sys.modules.pop(py_module_name)
    249 
--> 250     py_module = importlib.import_module(py_module_name)
    251     sys.path.pop(0)
    252 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)
    128 
    129 

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module)

/opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds)

~/.paddlehub/modules/stable_diffusion/module.py in <module>
     24 from PIL import Image
     25 from tqdm.auto import tqdm
---> 26 from docarray import Document
     27 from docarray import DocumentArray
     28 from IPython import display

ImportError: cannot import name 'Document' from 'docarray' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/docarray/__init__.py)

**Comment by Xiaoyanxun** [comment]
ImportError                               Traceback (most recent call last) /tmp/ipykernel_289/1696474352.py in <module&gt;       1 from PIL import Image       2 import paddlehub as hub ----&gt; 3 module = hub.Module(name='stable_diffusion') /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in __new__(cls, name, directory, version, source, update, branch, ignore_env_mismatch, **kwargs)     398                     branch=branch,     399                     ignore_env_mismatch=ignore_env_mismatch, --&gt; 400                     **kwargs)     401                 CacheUpdater("update_cache", module=name, version=version).start()     402             elif directory: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in init_with_name(cls, name, version, source, update, branch, ignore_env_mismatch, **kwargs)     496                 update=update,     497                 branch=branch, --&gt; 498                 ignore_env_mismatch=ignore_env_mismatch)     499      500         directory = manager._get_normalized_path(user_module_cls.name) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in install(self, name, directory, archive, url, version, source, update, branch, ignore_env_mismatch)     188                 if source:     189                     return self._install_from_source(name, version, source, update, branch) --&gt; 190                 return self._install_from_name(name, version, ignore_env_mismatch)     191         elif directory:     192             return self._install_from_directory(directory) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_name(self, name, version, ignore_env_mismatch)     263         for item in result:     264             if name.lower() == item['name'].lower() and utils.Version(item['version']).match(version): --&gt; 265                 return self._install_from_url(item['url'])     266      267         module_infos = module_server.get_module_compat_info(name=name) /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_url(self, url)     256                     bar.update(float(ds) / ts)     257  --&gt; 258             return self._install_from_archive(file)     259      260     def _install_from_name(self, name: str, version: str = None, ignore_env_mismatch: bool = False) -&gt; HubModule: /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_archive(self, archive)     378             path = os.path.normpath(path)     379             directory = os.path.join(_tdir, path.split(os.sep)[0]) --&gt; 380             return self._install_from_directory(directory)     381      382     def _install_module_requirements(self, directory: str): /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/manager.py in _install_from_directory(self, directory)     362             self._install_module_requirements(directory)     363  --&gt; 364             hub_module_cls = HubModule.load(self._get_normalized_path(module_info.name))     365             self._local_modules[module_info.name] = hub_module_cls     366  /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/module/module.py in load(cls, directory)     421         basename = os.path.split(directory)[-1]     422         dirname = os.path.join(*list(os.path.split(directory)[:-1])) --&gt; 423         py_module = utils.load_py_module(dirname, '{}.module'.format(basename))     424      425         for _item, _cls in inspect.getmembers(py_module, inspect.isclass): /opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddlehub/utils/utils.py in load_py_module(python_path, py_module_name)     248         sys.modules.pop(py_module_name)     249  --&gt; 250     py_module = importlib.import_module(py_module_name)     251     sys.path.pop(0)     252  /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/__init__.py in import_module(name, package)     125                 break     126             level += 1 --&gt; 127     return _bootstrap._gcd_import(name[level:], package, level)     128      129  /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _gcd_import(name, package, level) /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load(name, import_) /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _find_and_load_unlocked(name, import_) /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _load_unlocked(spec) /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap_external.py in exec_module(self, module) /opt/conda/envs/python35-paddle120-env/lib/python3.7/importlib/_bootstrap.py in _call_with_frames_removed(f, *args, **kwds) ~/.paddlehub/modules/stable_diffusion/module.py in <module&gt;      24 from PIL import Image      25 from tqdm.auto import tqdm ---&gt; 26 from docarray import Document      27 from docarray import DocumentArray      28 from IPython import display ImportError: cannot import name 'Document' from 'docarray' (/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/docarray/__init__.py)
&nbsp;


韭菜盒子不要韭菜
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月21日(星期五) 下午2:29
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 导入paddlehub里的stable_diffsusion模型出错 (Issue #53165)





 
看不到截图信息

**Comment by SmileGoat** [comment]
docarray import error，这个包这区安装了吗？

**Comment by Xiaoyanxun** [comment]
你好，建议你们测试一下，尽快解决这个bug,感觉可能是包封装那边的问题

**Comment by D-DanielYang** [comment]
首先还是要表示非常抱歉，这个问题排查的过程确实走了一些岔路，没有给您尽快解决问题深表歉意
我们在AIStudio上按照您的代码复现了这个问题，确实也得到了类似的报错信息（给您的提issue包含最小复现代码方式点赞）
https://aistudio.baidu.com/aistudio/projectdetail/6066784
排查了一下，发现问题确实是因为python依赖少了一个docarray的包
这里，我们考虑可以有两种解决方案：
1：在aistudio项目里使用临时方案：在pip安装一下docarray应该可以解决
    A：持久化安装（推荐，关闭项目之后包仍然在）
      !mkdir /home/aistudio/external-libraries
      !pip install docarray -t /home/aistudio/external-libraries
    B：本地使用或者临时安装：（关闭项目后丢弃）
      !pip install docarray
2：长期方案，考虑到PaddleHub中提供的SD相关能力比较有限，我们推荐PPdiffuser提供更强大的SD的支持能力
      https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers
再次对问题解决不及时深表歉意，感谢各位开发者对于飞桨的支持，我们也努力改正，争取可以做的更好一点，谢谢~

**Comment by rainyfly** [comment]
你好，paddlehub上的使用问题已经解决，发生该问题的原因是docarray近期进行了一个大升级到0.30版本，把之前的核心接口进行了修改，目前hub的模块已经对这一问题进行了修复
