### ISSUE TITLE
embedding层为nan，loss为nan

### ISSUE THREAD

**Issue by Isabellahu** [PaddlePaddle/Paddle#53170]
### 请提出你的问题 Please ask your question

![image](https://user-images.githubusercontent.com/35736172/233567762-8171e5d1-0b17-4cb3-8a7e-d0c95697fa98.png)
![image](https://user-images.githubusercontent.com/35736172/233567807-88783a0a-fdca-4ba6-889f-5177170d8737.png)

**Comment by SmileGoat** [comment]
@phlrain 可以帮助看一下吗

**Comment by dingjiaweiww** [comment]
问题描述不清，暂时关闭
