### ISSUE TITLE
Pip install support

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5318]
@reyoung had been working on this. He noticed that the manylinux standard requires that wheel packages (or pip packages) must be built on CentOS 5.  However, CentOS 5 is too old a Linux distribution whose kernel doesn't support Golang.

@helinwang reminded that if we are to distribute pip packages of PaddlePaddle, we can simply disable Golang during building (`cmake WITH_GO=OFF`) because currently Golang is only used with the parameter server and in our future plan we are not going to have the parameter server.

**Comment by reyoung** [comment]
Related issue #4050

**Comment by Yancey1989** [comment]
I'll close this issue since we have already support `pip install paddlepaddle`.
