### ISSUE TITLE
程序运行不了

### ISSUE THREAD

**Issue by liuweida1** [PaddlePaddle/Paddle#53198]
### bug描述 Describe the Bug

ValueError: (InvalidArgument) Leaf Tensor (batch_norm2d_0.w_0) that doesn't stop gradient can't use inplace strategy.

### 其他补充信息 Additional Supplementary Information

有的模型训练出现这个问题，导致模型无法训练

**Comment by ceci3** [comment]
麻烦贴多一点报错信息，看起来像是使用问题
