### ISSUE TITLE
add the CN version of /tools/externalError/README.md

### ISSUE THREAD

**Issue by Bushilei** [PaddlePaddle/Paddle#53218]
### 文档链接&描述 Document Links & Description

https://github.com/PaddlePaddle/Paddle/tree/develop/tools/externalError

**Comment by Bobholamovic** [comment]
你好，我注意到你为PaddlePaddle提了一个[PR](https://github.com/PaddlePaddle/Paddle/pull/53219)，感谢你的贡献！这样的话，请问这个issue是不是可以先关闭呀？
