### ISSUE TITLE
CustomDevice使用其他设备时候的layout优化

### ISSUE THREAD

**Issue by ShawnNew** [PaddlePaddle/Paddle#53216]
### 请提出你的问题 Please ask your question

如题，请问paddle是否支持提供CustomDevice的layout优化选项？例如期望运行NHWC的摆数，并且能够在paddleinference支持该种类型。

**Comment by qili93** [comment]
这个目前暂不支持，如果PaddleInference在NV GPU上已经支持此类配置，请提供对应的Pass或者接口，我们这里会尽快增加对CustomDevice的支持。

**Comment by engineer1109** [comment]
只有NCHW，NHWC从来没人试过
