### ISSUE TITLE
Paddle 的 dist 算子在动态图模式下无法进行求导

### ISSUE THREAD

**Issue by yangguohao** [PaddlePaddle/Paddle#53213]
### bug描述 Describe the Bug

```
x_shape = (2, 2, 3, 2)
y_shape = (1, 1, 3, 1)
p = 2
x_paddle = paddle.rand(shape=x_shape)
y_paddle = paddle.rand(shape=y_shape)
x_paddle.stop_gradient = False
z = paddle.dist(x_paddle, y_paddle, p)
z.backward()
```
以上这段代码在动态图模式下运行，显示 `Process finished with exit code -1073741819 (0xC0000005)`，在 AIStudio 上 kernel 直接挂掉。使用的是飞桨 2.4 版本。

**Comment by Bobholamovic** [comment]
你好，我注意到当同时指定`y_paddle.stop_gradient = False`时，程序可以跑通。不过，只有`x_paddle`需要梯度时程序无法跑通，看起来是一个bug，我们的相关同学正在排查中~

**Comment by yangguohao** [comment]
好的，感谢回复.
