### ISSUE TITLE
混合精度推理报错

### ISSUE THREAD

**Issue by XXYMAN** [PaddlePaddle/Paddle#53232]
### 请提出你的问题 Please ask your question

模型是fp32训练得到的
当config这样设置时，可以得到正常结果
self.config = paddle_infer.Config(model_path, param_path)
self.config.enable_use_gpu(1024 * 8, 0)
self.config.switch_ir_optim(False)
self.predictor = paddle_infer.create_predictor(self.config)

当config如下设置时，
self.config = paddle_infer.Config(model_path, param_path)
self.config.enable_use_gpu(1024 * 8, 0, PrecisionType.Half) // 和上面的唯一区别
self.config.switch_ir_optim(False)
self.predictor = paddle_infer.create_predictor(self.config)
报错如下:
Traceback (most recent call last):
  File "infer_glm.py", line 200, in <module>
    test()
  File "infer_glm.py", line 188, in test
    glm_infer.run(glm_txt)
  File "infer_glm.py", line 107, in run
    self.predictor.run()
OSError: (External) CUDA error(700), an illegal memory access was encountered. 
  [Hint: Please search for the error code(700) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/fluid/platform/device/gpu/gpu_info.cc:142)
  [operator < concat > error]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::~AnalysisPredictor()
1   paddle::AnalysisPredictor::~AnalysisPredictor()
2   paddle::memory::allocation::StreamSafeCUDAAllocator::ReleaseImpl(phi::Place const&)
3   paddle::memory::allocation::AutoGrowthBestFitAllocator::FreeIdleChunks()
4   paddle::memory::allocation::CUDAAllocator::FreeImpl(phi::Allocation*)
5   paddle::platform::RecordedGpuMallocHelper::Free(void*, unsigned long)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1682236243 (unix time) try "date -d @1682236243" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3ee0000678d) received by PID 26509 (TID 0x7f2081893740) from PID 26509 ***]

Aborted (core dumped)

**Comment by jiweibo** [comment]
您好，请问下当跑fp32模型的时候设置
self.config.switch_ir_optim(True)可以跑通吗？

当上述情况ok时，请再尝试跑fp16（self.config.switch_ir_optim(True)）的情况，如果遇到问题请在issue中贴下报错日志哈

**Comment by XXYMAN** [comment]
self.config.switch_ir_optim(True)是可以跑通的，但是fp16（self.config.switch_ir_optim(True)）无法跑通

init_prs_mask = paddle.reshape(init_prs_mask, [-1, 1])
init_prs_mask = paddle.tile(init_prs_mask, repeat_times=[1, 50048])       
prs_msk = paddle.multiply(self.prs_mask_a_tensor, init_prs_mask)
prs_msk = paddle.unsqueeze(prs_msk, axis=1)
当注释掉上面4行代码，对输出的pr值不做mask时，把动态图转成静态图，fp16就可以直接跑通了
prs += prs_msk
