### ISSUE TITLE
 if input[0].desc.type() == core.VarDesc.VarType.LOD_TENSOR_ARRAY:   IndexError: list index out of range

### ISSUE THREAD

**Issue by lwgkzl** [PaddlePaddle/Paddle#53244]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/manipulation.py#L1072  中的concat函数。

在静态态图模式下， 运行到第1164行，会访问input[0]来报错。
<img width="945" alt="image" src="https://user-images.githubusercontent.com/30727306/233841273-6fc7a68e-9f77-4593-8325-4fc0a7c31a57.png">
报错为：
![image](https://user-images.githubusercontent.com/30727306/233841333-b4becd63-eef5-4354-9e5d-8a7093104dec.png)
估计是： 静态图在实际运行之前会进行构图操作， 在构图的时候， input是没有实际变量的， 这个时候访问input，会造成报错。

### 其他补充信息 Additional Supplementary Information

无

**Comment by Bobholamovic** [comment]
请提供最小可复现例子，以便我们能够定位问题~

**Comment by lwgkzl** [comment]
> 请提供最小可复现例子，以便我们能够定位问题~

可能需要你这边提供一个静态图的最小可运行代码， 我在paddle官网上没有看到静态图的例子

**Comment by Bobholamovic** [comment]
好的。我写了一个动态图、动转静、静态图3种方式使用`paddle.concat`（也就是https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/manipulation.py#L1072 定义的`concat`函数）的例子：

```python
import paddle
import numpy as np

# 动态图
x = paddle.to_tensor([1.0, 2.0, 3.0], dtype='float32')
print(paddle.concat([x, x]))

# 动转静
x = paddle.to_tensor([1.0, 2.0, 3.0], dtype='float32')
@paddle.jit.to_static
def func(x):
    return paddle.concat([x, x])
print(func(x))

# 静态图
paddle.enable_static()
x = paddle.static.data(shape=[3], dtype='float32', name='x')
y = paddle.concat([x, x])
exe = paddle.static.Executor()
exe.run(paddle.static.default_startup_program())
compiled_program = paddle.static.CompiledProgram(paddle.static.default_main_program())
print(exe.run(compiled_program, feed={'x': np.array([1.0, 2.0, 3.0], dtype='float32')}, fetch_list=[y]))
```

但我这边在Paddle 2.4环境下是可以正常执行的，可能需要你提供一个可以复现错误的case~

**Comment by lwgkzl** [comment]
感谢manhui哥， 我发现自己的错误在哪了， 我想自己实现一下torch.gather函数，所以通过fc_out.shape来获取长度， 后面观察了下发现， fc_output.shape[0]是-1。 所以会使得tmpx的长度是0， 是我自己代码的问题。
···
tmp_x = [fluid.layers.gather(fc_out[i,:], mask_label[i,:]) for i in range(fc_out.shape[0])]
masked_probs = fluid.layers.concat(tmp_x, axis=0)
···

最后请教下， 在paddle2.2的版本， 还没有take_along_axis的函数， 该如何更好的实现torch.gather函数呢， 对paddle升级的话要考虑许多依赖， 成本太高。

**Comment by Bobholamovic** [comment]
[这里](https://github.com/PaddlePaddle/Paddle/issues/38655)有一个通过组合算子实现`torch.gather`功能的例子，可以参考~

**Comment by lwgkzl** [comment]
好的， 感谢
