### ISSUE TITLE
paddle.io.Dataloader()实例化后，循环取数据报错。

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#53264]
### 请提出你的问题 Please ask your question

问题描述：自定义数据集类后，传入Dataloader()。用 for i, (image, label) in enumerate(loader()):  循环取值时报错。
环境信息：
![1](https://user-images.githubusercontent.com/65533171/233905852-8e0755d6-a15e-4465-8a53-03009a13ab9a.png)
报错信息：
![5](https://user-images.githubusercontent.com/65533171/233906149-ab100d3c-731c-4837-9c7f-0e81a2d0f052.png)
![7](https://user-images.githubusercontent.com/65533171/233906280-6573b128-bb52-42d0-8167-ff8803870fc7.png)
![2](https://user-images.githubusercontent.com/65533171/233905882-e32e6081-5643-4919-8a79-7feee34c3ede.png)
数据集准备代码：
其中class CSIRGB_dataset 中的traindata，testdata为自己生成的数据，打印信息如下：
traindata的shape: (336, 90, 90, 3) testdata的shape: (84, 90, 90, 3) trainlabel的shape: (336,) testlabel的shape: (84,)
![3](https://user-images.githubusercontent.com/65533171/233906010-1540c5ea-8b06-4c75-a6df-c0fd6e1e7cc5.png)
![4](https://user-images.githubusercontent.com/65533171/233906012-5e501f39-35b4-4617-a05b-4f0011e54ba9.png)

**Comment by xiaoguoguo626807** [comment]
![image](https://user-images.githubusercontent.com/100397923/233914886-d20a71ba-0a4c-4fb1-baf1-9d899dfe3840.png)
这个地方显示在使用stack api 的时候没有找到对应类型的执行kernel，看一下你的数据是不是double类型的，换成float行不行

**Comment by xiaoguoguo626807** [comment]
这是stack支持的数据类型：float,
                   double,
                   bool,
                   int64_t,
                   int,
                   uint8_t,
                   int8_t,
                   phi::dtype::float16,
                   phi::dtype::bfloat16

**Comment by JJYjackson** [comment]
好的我试试，之前我的数据是complex类型的。

**Comment by JJYjackson** [comment]
换成float32后就没有报错了，但是我想用complex类型的数据，所以不适合用Dataloader()是嘛？

**Comment by xiaoguoguo626807** [comment]
本质上是Dataloader调用了stack 不支持复数，我们会在今年六月底完成一批算子的复数类型支持，到时候可以试一下。
