### ISSUE TITLE
在麒麟V10(sp1)系统飞腾arm64架构编译安装paddle，运行存在如下报错，请帮忙确认是否正常

### ISSUE THREAD

**Issue by wuzhaohui100** [PaddlePaddle/Paddle#53275]
### bug描述 Describe the Bug

系统：麒麟V10SP1
架构：飞腾 arm64
python:python3.8

编译安装
git clone https://gitee.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout develop
pip3 install -r python/requirements.txt
mkdir build && cd build
ulimit -n 4096
cmake .. -DPY_VERSION=3.8 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
make TARGET=ARMV8 -j$(nproc)

复现：
kylin@kylin-kunpeng-arm64-v10sp1-2203:~/paddle$ python3
Python 3.8.2 (default, May 10 2021, 05:51:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0424 16:28:43.846396  8028 interpretercore.cc:282] New Executor is Running.
I0424 16:28:43.853920  8028 interpreter_util.cc:575] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
/home/kylin/.local/lib/python3.8/site-packages/paddle/distributed/spawn.py:304: UserWarning: Your model will be trained under CPUONLY mode by using GLOO,because CPUPlace is specified manually or your installed PaddlePaddle only support CPU Device.
  warnings.warn(
I0424 16:28:44.883075  8269 tcp_utils.cc:105] Retry to connect to 127.0.0.1:40931 while the server is not yet listening.
I0424 16:28:44.898972  8268 tcp_utils.cc:179] The server starts to listen on IP_ANY:40931
I0424 16:28:44.899107  8268 tcp_utils.cc:128] Successfully connected to 127.0.0.1:40931
I0424 16:28:47.883215  8269 tcp_utils.cc:128] Successfully connected to 127.0.0.1:40931
I0424 16:28:47.992233  8286 tcp_store.cc:270] receive shutdown event and so quit from MasterDaemon run loop
 
 
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::OpAttrTypeMap::~OpAttrTypeMap()
 
----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1682324928 (unix time) try "date -d @1682324928" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800001f5c) received by PID 8268 (TID 0x7f809e2420) from PID 8028 ***]
 
WARNING:root:PaddlePaddle meets some problem with 2 CPUs. This may be caused by:
 1. There is not enough GPUs visible on your system
 2. Some GPUs are occupied by other process now
 3. NVIDIA-NCCL2 is not installed correctly on your system. Please follow instruction on https://github.com/NVIDIA/nccl-tests
 to test your NCCL, or reinstall it following https://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html
WARNING:root:
 Original Error is:
 
----------------------------------------------
Process 1 terminated with the following error:
----------------------------------------------
 
Traceback (most recent call last):
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/distributed/spawn.py", line 394, in _func_wrapper
    result = func(*args)
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/utils/install_check.py", line 199, in train_for_run_parallel
    paddle.distributed.init_parallel_env()
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/distributed/parallel.py", line 1098, in init_parallel_env
    pg = _new_process_group_impl(
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/distributed/collective.py", line 152, in _new_process_group_impl
    pg = core.ProcessGroupGloo.create(store, rank, world_size, group_id)
AttributeError: module 'paddle.fluid.libpaddle' has no attribute 'ProcessGroupGloo'

**Comment by zhengqiwen1997** [comment]
是单卡没问题，多cpu出的问题吗？
首先查看nccl版本，需要大于等于2.7.8；然后试试修改环境变量：
export NCCL_SHM_DISABLE=1、export NCCL_P2P_LEVEL=SYS

**Comment by wuzhaohui100** [comment]
> 

飞腾机器上面没有NVIDIA显卡，是不是这个报错就是正常的？
我使用如下参数编译后，可以正常运行
git clone https://gitee.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout develop
pip3 install -r python/requirements.txt
mkdir build && cd build
ulimit -n 4096
cmake .. -DPY_VERSION=3.8 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_GPU=OFF
make TARGET=ARMV8 -j$(nproc)

$ python3
Python 3.8.2 (default, May 10 2021, 05:51:26)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ...
I0425 15:30:24.000661 252696 interpretercore.cc:267] New Executor is Running.
I0425 15:30:24.008322 252696 interpreter_util.cc:480] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.


另外，PaddlePaddle works well on 1 CPU.是正常的吗？这个和CPU的核数有关系吗？这个提示意思是只用了CPU的一个核心吗？

**Comment by zhengqiwen1997** [comment]
你这个结果显示是正确的，而且是在单CPU上（可以是多核的）。

**Comment by wuzhaohui100** [comment]
> 你这个结果显示是正确的，而且是在单CPU上（可以是多核的）。

要想使用多CPU，是编译的时候设置还是运行的时候进行设置呢？

另外，我使用上面-DWITH_GPU=OFF编译的paddlepaddle，然后安装paddlespeech，运行demo会有如下报错
$ paddlespeech asr --lang zh --input zh.wav
[2023-04-26 13:34:48,142] [   ERROR] - list index out of range
Traceback (most recent call last):
  File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/cli/asr/infer.py", line 314, in infer
    result_transcripts = self.model.decode(
  File "/home/kylin/.local/lib/python3.8/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/kylin/.local/lib/python3.8/site-packages/paddle/fluid/dygraph/base.py", line 350, in _decorate_function
    return func(*args, **kwargs)
  File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 819, in decode
    hyp = self.attention_rescoring(
  File "/home/kylin/.local/lib/python3.8/site-packages/paddlespeech/s2t/models/u2/u2.py", line 533, in attention_rescoring
    assert speech.shape[0] == speech_lengths.shape[0]
IndexError: list index out of range
KeyError: 'result'

如果使用没有添加-DWITH_GPU=OFF参数编译出来的paddlepaddle就是正常的
$ paddlespeech asr --lang zh --input zh.wav
我认为跑步最重要的就是给我带来了身体健康

**Comment by zhengqiwen1997** [comment]
多cpu的调用可参考https://www.paddlepaddle.org.cn/documentation/api/paddle/static/ParallelExecutor_cn.html#cn-api-fluid-parallelexecutor
您遇到的这个报错可能是内部代码有问题，可以提个issue促进我们代码的改进，谢谢。

**Comment by wuzhaohui100** [comment]
> 是单卡没问题，多cpu出的问题吗？ 首先查看nccl版本，需要大于等于2.7.8；然后试试修改环境变量： export NCCL_SHM_DISABLE=1、export NCCL_P2P_LEVEL=SYS

我系统上确实没有GPU，应该是没有GPU导致的

**Comment by wuzhaohui100** [comment]
> 多cpu的调用可参考https://www.paddlepaddle.org.cn/documentation/api/paddle/static/ParallelExecutor_cn.html#cn-api-fluid-parallelexecutor 您遇到的这个报错可能是内部代码有问题，可以提个issue促进我们代码的改进，谢谢。

已经新提交issue:https://github.com/PaddlePaddle/Paddle/issues/53367
