### ISSUE TITLE
paddle.floor_divide仅支持整数

### ISSUE THREAD

**Issue by soyons** [PaddlePaddle/Paddle#53299]
paddle.floor_divide仅支持整数太憨了吧，人家torch能支持浮点数啊，、、

**Comment by Birdylx** [comment]
@soyons 你好，`torch.floor_divde`支持float型，是trunc的取整方式，`paddle.floor_divide`只支持int型，也是trunc的取整方式，你可以采用`paddle.trunc`来满足你的需求。

torch:
```
out = torch.floor_divide(x, y)
```

paddle:
```
out = paddle.trunc(x / y)
```
