### ISSUE TITLE
Ubuntu20.04+海光DCUZ100+DTK22.04

### ISSUE THREAD

**Issue by chenzhijun45** [PaddlePaddle/Paddle#53298]
Ubuntu20.04+海光DCUZ100+DTK22.04
基于以上环境，请问如何安装Paddle？尝试过安装ROMC版本的Paddle，运行异常 Hip error。

**Comment by ronny1996** [comment]
你好，dtk环境下需要自己编译，可参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html#anzhuangfangshier-tongguoyuanmabianyianzhuang

**Comment by chenzhijun45** [comment]
> 你好，dtk环境下需要自己编译，可参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html#anzhuangfangshier-tongguoyuanmabianyianzhuang

可能是系统问题，ubuntu使用这里的方式编译安装paddle，压根儿没用，还是找的海光官方要了whl文件安装才可以。
