### ISSUE TITLE
paddle.gather 如何支持高维索引？

### ISSUE THREAD

**Issue by triple-mu** [PaddlePaddle/Paddle#53302]
### 请提出你的问题 Please ask your question

paddle.gather 如何支持高维索引？

**Comment by Birdylx** [comment]
@triple-Mu ，`paddle.gather_nd`是高纬的推广，如果你是需要具有和`torch.gather`行为一致的API，你可以使用`paddle.take_along_axis`

**Comment by triple-mu** [comment]
> @triple-Mu ，`paddle.gather_nd`是高纬的推广，如果你是需要具有和`torch.gather`行为一致的API，你可以使用`paddle.take_along_axis`

感谢您的解答！
