### ISSUE TITLE
paddle.gather在cpu环境运行报错，gpu环境运行正常

### ISSUE THREAD

**Issue by z3guo11** [PaddlePaddle/Paddle#53348]
### bug描述 Describe the Bug

results = dict()
import paddle
paddle.device.set_device('cpu')
arg_1_tensor = paddle.rand([9, 5], dtype='float64')
arg_1 = arg_1_tensor.clone()
arg_2_tensor = paddle.randint(-2048,16384,[3])
arg_2 = arg_2_tensor.clone()
arg_3 = 0
try:
  results["res_cpu"] = paddle.gather(arg_1,arg_2,axis=arg_3,)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
paddle.device.set_device('gpu')
arg_1 = arg_1_tensor.clone().cuda()
arg_2 = arg_2_tensor.clone().cuda()
try:
  results["res_gpu"] = paddle.gather(arg_1,arg_2,axis=arg_3,)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)

print(results)

### 其他补充信息 Additional Supplementary Information

报错信息:
{'err_cpu': 'ERROR:(OutOfRange) The element of Index must be less than the size of input dim size of axis which is 45, but received index element which is 7273 in the 0 index.\n  [Hint: Expected p_index[i] < input_size, but received p_index[i]:7273 >=input_size:45.] (at ..\\paddle/phi/kernels/funcs/gather.h:84)\n'

'res_gpu': Tensor(shape=[3, 5], dtype=float64, place=Place(gpu:0), stop_gradient=True,
       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

**Comment by kangguangli** [comment]
你好，目前看原因应该是因为这里传入的`index`不合法，这里的`x`只有 45个元素，没法获取到对应`index`的元素，这里报错应该是正常的。
GPU没有报错的原因是没有办法对GPU的输入数据进行检查，因此返回了0，可以看到gpu的返回结果全部是0，也不算是一个正常的结果。

**Comment by z3guo11** [comment]
> 你好，目前看原因应该是因为这里传入的`index`不合法，这里的`x`只有 45个元素，没法获取到对应`index`的元素，这里报错应该是正常的。 GPU没有报错的原因是没有办法对GPU的输入数据进行检查，因此返回了0，可以看到gpu的返回结果全部是0，也不算是一个正常的结果。

那gpu情况下index不合法不是也应该报同样的错误吗，返回都是0也是有问题的吧。毕竟gpu的返回值不是exception 会正常代入到后续计算里面。

**Comment by kangguangli** [comment]
这里我理解主要有两个问题：
1. 在gpu kernel里进行这种检测，抛出异常实现起来比较麻烦
2.非要检测当然是可能的，但是这对性能会有影响，具体影响多少还需要比较详细的测试。如果你有兴趣的话，可以提PR测试下
