### ISSUE TITLE
test_hubserving.py 报错IndexError:string index out of range该怎么处理

### ISSUE THREAD

**Issue by chasezhao** [PaddlePaddle/Paddle#53353]
### 请提出你的问题 Please ask your question

test_hubserving.py 报错IndexError:string index out of range该怎么处理

**Comment by chasezhao** [comment]
![image](https://user-images.githubusercontent.com/59431019/234464884-78073fa1-e2ab-452c-908e-cdb0cd7ebbe6.png)

**Comment by kangguangli** [comment]
你好，关于PaddleOCR的问题推荐在对应的[repo](https://github.com/PaddlePaddle/PaddleOCR/issues)下提问。
