### ISSUE TITLE
paddle.reshape 对于 shape 支持的数据类型问题

### ISSUE THREAD

**Issue by Ainavo** [PaddlePaddle/Paddle#53366]
### 请提出你的问题 Please ask your question

最近在使用 paddle.reshape 或 Tensor.reshape 时，发现当参数 `shape` 设置成 `list(np.array([4, 2.0, 3.0, 9]).astype('float32'))` 这个形式，[paddle.reshape](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/reshape_en.html#reshape) 是不进行报错的（正常创建的列表中的浮点数是会报错的）如下图，这里不知道是不是我用错了的原因。
```Python
import paddle
import numpy as np 

if __name__ == '__main__':
    x = np.random.random((4, 6, 9))
    paddle_x = paddle.to_tensor(x)
    shape = list(np.array([4, 2.0, 3.0, 9]).astype('float32'))
    # shape = [4, 2.0, 3.0, 9]
    print(shape)
    out = paddle.reshape(paddle_x, shape)
    print(out)
```
![C8RLQ@(5OSGRSAGN78BQP0F](https://user-images.githubusercontent.com/57820731/234524151-cecb135f-9df7-467a-aa48-51238416d34e.png)
![Z9_3JPI$A8N3MCB4@T~G4FC](https://user-images.githubusercontent.com/57820731/234524171-560cf8f2-33c1-4dc1-9484-207414388713.png)

**Comment by kangguangli** [comment]
你好，目前看在使用numpy时变量是`np.float32`类型，而使用列表时是`float`类型，和同事沟通了下，这里paddle对numpy会有特殊处理，将相关类型强制转为`long`。
https://github.com/PaddlePaddle/Paddle/blob/3650c4a85dd2a0e52885897cfa4a3303a7f45645/paddle/fluid/pybind/op_function_common.cc#L80

这段代码比较早，我们会再斟酌下这里的处理，感谢你的反馈。
