### ISSUE TITLE
3.11.1无法通过pip安装，3.10.6可以

### ISSUE THREAD

**Issue by Erimus-Koo** [PaddlePaddle/Paddle#53363]
### 问题描述 Issue Description

3.11.1无法通过pip安装，3.10.6可以

### 版本&环境信息 Version & Environment Information

3.11.1无法通过pip安装，3.10.6可以

**Comment by kangguangli** [comment]
你好，麻烦补充下这两条信息：
1. 具体的安装命令
2. 报错提示或截图

**Comment by kangguangli** [comment]
抱歉，更新一下，对于python3.11的支持正在验证中，后续会支持。

**Comment by tianlichunhong** [comment]
不知道什么时候支持。希望能尽早支持，感谢大佬！如果还得装一个pip3.10，不知是否又有各种冲突。晕！
