### ISSUE TITLE
Paddle.add Overflow Error

### ISSUE THREAD

**Issue by Rainsworth-cmd** [PaddlePaddle/Paddle#53395]
### bug描述 Describe the Bug

paddle.add result in return code : 3221225477 when input tensors on CPU

import paddle
results = []
paddle.device.set_device('cpu')
arg_1_tensor = paddle.rand([1], dtype='float64')
arg_2_tensor = paddle.rand([18, 0, 3, 4, 0], dtype='float64')
results.append(paddle.add(arg_1_tensor,arg_2_tensor,))
print(results)

If run the above script directly in shell nothing will be printed.
If run the above script using subprocess library and print the return code 3221225477 will be printed.

**Comment by USTCKAY** [comment]
Hello, could you please provide the environment and detailed steps to reproduce the bug?

**Comment by Rainsworth-cmd** [comment]
Python 3.10.7
lib version : paddlepaddle-gpu==2.4.2
runtime cuda : 10.2
cudnn : 7.6 

To reproduce the bug simply run the code provided and will result in the first case - nothing printed.

Using the following code will result in the return code : 3221225477

import subprocess

result = subprocess.run(["python", "[the file contain the provided code]"], shell=False,
                                      timeout=100)
print(result.returncode)

**Comment by USTCKAY** [comment]
> 

I tried it on my machine, `Segmentation fault` would happen when print results.It might be resulted by that the result of add operation has dynamic shape of [18, -1, 3, 4, -1].

**Comment by Rainsworth-cmd** [comment]
That could be the cause. But with the same input, if I put it on GPU it will result in a different runtime status from my end. Removing paddle.device.set_device('cpu') will result in a Invalid arugment error: ValueError: (InvalidArgument) The 2-th dimension of input tensor is expected to be equal with the 2-th dimension of output tensor -1 or 1, but received 0. (at ../paddle/phi/kernels/funcs/broadcast_function.h:77). It is possible there is a missing arugment check in the implmentation for cpu.

**Comment by USTCKAY** [comment]
> That could be the cause. But with the same input, if I put it on GPU it will result in a different runtime status from my end. Removing paddle.device.set_device('cpu') will result in a Invalid arugment error: ValueError: (InvalidArgument) The 2-th dimension of input tensor is expected to be equal with the 2-th dimension of output tensor -1 or 1, but received 0. (at ../paddle/phi/kernels/funcs/broadcast_function.h:77). It is possible there is a missing arugment check in the implmentation for cpu.

The CPU elementwise_add kernel has diff with GPU kernel on input broadcast. In the case you provided, CPU kernel would skip input braodcast but GPU kernel would not, so you got different results when execute the same code on different devices. Thanks for your feedback, we would consider this problem later.
