### ISSUE TITLE
先安装官方v2.4.2版本的whl包，再安装paddle plugin生成的whl包，执行模型训练时，报"stack smashing detected" error

### ISSUE THREAD

**Issue by Nepths** [PaddlePaddle/Paddle#53393]
### 请提出你的问题 Please ask your question

操作系统为：Ubuntu18.04 ；gcc版本：7.5；python版本：3.8.16
1.  基于paddle tag v2.4.2版本的代码 ，进行源码编译paddle whl，编译命令为：cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPY_VERSION=3.8 -DWITH_GPU=OFF -DWITH_TESTING=OFF 
-DCMAKE_BUILD_TYPE=Release  -DWITH_MKL=OFF .. && make TARGET=HASWELL -j32，编译完成之后安装该whl包，然后再安装paddle plugin 生成的whl包，可以正常进行模型训练；
2. 直接从pypi上拉取 paddle v2.4.2 whl包进行安装，再安装paddle plugin 生成的whl包，进行模型训练，报：stack smashing detected
3. 应当如何确保paddle plugin生成的whl可以搭配paddle 官方的v2.4.2 whl，进行模型训练？

**Comment by USTCKAY** [comment]
你好，能否提供一下更详细一点的报错信息和环境信息？以及能否提供一下直接安装paddle 2.4.2 whl包方式复现错误的步骤？

**Comment by Nepths** [comment]
问题已解决
