### ISSUE TITLE
TypeReport: Redundant parenthesis that may cause compile error

### ISSUE THREAD

**Issue by yuehaoshi** [PaddlePaddle/Paddle#53438]
### 文档链接&描述 Document Links & Description

Dear Paddle developers,
There are two typos in PaddlePaddle 2.4 official website/API Reference examples:
The first one is on the page of [CountFilterEntry](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/distributed/CountFilterEntry_en.html#countfilterentry)
The second one is on the page of [ProbabilityEntry](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/distributed/ProbabilityEntry_en.html#probabilityentry)

### 请提出你的建议 Please give your suggestion

Both typos are on the line of:
`emb = paddle.static.nn.sparse_embedding((,`
where there should be only one parenthesis:
`emb = paddle.static.nn.sparse_embedding(,`
otherwise there will be compile error when running this example code.
Thanks!

**Comment by luotao1** [comment]
@yuehaoshi Hope you can create a PR to fix it, thanks very much!
