### ISSUE TITLE
PaddleDetection pptracking C++不返回推理结果（CPU)

### ISSUE THREAD

**Issue by vivid333** [PaddlePaddle/Paddle#53436]
### 问题描述 Please describe your issue

你好：
        问题现象： 同样的inference库，python下运行正常， c++下图像没有返回推理结果（全是原始代码，未做任何修改）
        inference库：MKL (8.2) Paddle_inference.tar
        编译及运行路径：  
                         padleDetection/deploy/pptracking/cpp
                         ./build/main --video_file=palace2s.mp4 --track_model_dir=fairmot_hrnetv2_w18_dlafpn_30e_576x320 --do_entrance_counting=True --save_result=True  --cpu_threads=4
           
        运行输出：
                         ---    fused 26 elementwise_add with relu activation
                         ---    fused 0 elementwise_add with tanh activation
                        ---    fused 0 elementwise_add with leaky_relu activation
                        ---    fused 0 elementwise_add with swish activation
                        ---    fused 0 elementwise_add with hardswish activation
                       ---    fused 0 elementwise_add with sqrt activation
                       ---    fused 0 elementwise_add with abs activation
                      ---    fused 0 elementwise_add with clip activation
                      ---    fused 0 elementwise_add with gelu activation
                      ---    fused 0 elementwise_add with relu6 activation
                      ---    fused 0 elementwise_add with sigmoid activation
                      ---    fused 0 elementwise_sub with relu activation
                     ---    fused 0 elementwise_sub with tanh activation
                     ---    fused 0 elementwise_sub with leaky_relu activation
                     ---    fused 0 elementwise_sub with swish activation
                     ---    fused 0 elementwise_sub with hardswish activation
                     ---    fused 0 elementwise_sub with sqrt activation
                     ---    fused 0 elementwise_sub with abs activation
                     ---    fused 0 elementwise_sub with clip activation
                     ---    fused 0 elementwise_sub with gelu activation 
                     ........
                    ---    fused 0 elementwise_mul with sigmoid activation
                   WARNING: Logging before InitGoogleLogging() is written to STDERR
                   I0428 08:33:39.726893  1832 pipeline.cc:156] ----------------------- Input info -----------------------
                   I0428 08:33:39.726922  1832 pipeline.cc:157] video_width: 1280
                   I0428 08:33:39.726925  1832 pipeline.cc:158] video_height: 720
                   I0428 08:33:39.726927  1832 pipeline.cc:159] input fps: 30
                   OpenCV: FFMPEG: tag 0x7634706d/'mp4v' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
                  OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'
                  I0428 08:33:39.729526  1832 pipeline.cc:196] ------------------- Predict info ------------------------
                  I0428 08:33:40.364944  1832 pipeline.cc:208] frame_id: 1 predict time(s): 0.605698
                  I0428 08:33:40.369953  1832 postprocess.cc:177] Frame id: 1, Total count: 0, In count: 0, Out count: 0
                  I0428 08:33:40.752766  1832 pipeline.cc:208] frame_id: 2 predict time(s): 0.488286
                  I0428 08:33:40.753304  1832 postprocess.cc:177] Frame id: 2, Total count: 0, In count: 0, Out count: 0
                  I0428 08:33:41.080991  1832 pipeline.cc:208] frame_id: 3 predict time(s): 0.429754
                  I0428 08:33:41.081614  1832 postprocess.cc:177] Frame id: 3, Total count: 0, In count: 0, Out count: 0
                  I0428 08:33:41.447062  1832 pipeline.cc:208] frame_id: 4 predict time(s): 0.408565
                  I0428 08:33:41.447728  1832 postprocess.cc:177] Frame id: 4, Total count: 0, In count: 0, Out count: 0
                 I0428 08:33:41.800246  1832 pipeline.cc:208] frame_id: 5 predict time(s): 0.395552
                 I0428 08:33:41.800863  1832 postprocess.cc:177] Frame id: 5, Total count: 0, In count: 0, Out count: 0

                 .......
                 I0428 08:34:36.767071  1975 pipeline.cc:340] ----------------------- Config info -----------------------
                 I0428 08:34:36.767119  1975 pipeline.cc:341] runtime_device: CPU
                 I0428 08:34:36.767122  1975 pipeline.cc:342] ir_optim: True
                 I0428 08:34:36.767124  1975 pipeline.cc:344] enable_memory_optim: True
                 I0428 08:34:36.767163  1975 pipeline.cc:353] enable_tensorrt: False
                 I0428 08:34:36.767170  1975 pipeline.cc:355] precision: fp32
                 I0428 08:34:36.767172  1975 pipeline.cc:358] enable_mkldnn: True
                 I0428 08:34:36.767174  1975 pipeline.cc:359] cpu_math_library_num_threads: 4
                 I0428 08:34:36.767177  1975 pipeline.cc:360] ----------------------- Perf info ------------------------
                 I0428 08:34:36.767201  1975 pipeline.cc:361] Total number of predicted data: 60 and total time spent(s): 21.9534
                 I0428 08:34:36.767220  1975 pipeline.cc:365] preproce_time(ms): 11.9034, inference_time(ms): 330.463, postprocess_time(ms): 23.5228
                I0428 08:34:36.767225  1975 pipeline.cc:247] -------------------- Final Output info -------------------
                I0428 08:34:36.767228  1975 pipeline.cc:248] Total frame: 60
                I0428 08:34:36.767253  1975 pipeline.cc:249] Visualized output saved as output/mot_output.mp4
                I0428 08:34:36.767333  1975 pipeline.cc:264] txt result output saved as output/mot_output.txt
               I0428 08:34:36.767382  1975 pipeline.cc:275] txt flow statistic saved as output/flow_statistic.txt

**Comment by vivid333** [comment]
python下的正常输出
# cat output/palace2s_flow_statistic.txt 
Frame id: 1, Total count: 14
Frame id: 2, Total count: 14
Frame id: 3, Total count: 14
Frame id: 4, Total count: 14
Frame id: 5, Total count: 14
Frame id: 6, Total count: 16
Frame id: 7, Total count: 16
Frame id: 8, Total count: 17
Frame id: 9, Total count: 17
.....

**Comment by vivid333** [comment]
************   script/build.sh   **************

# 是否使用GPU(即是否使用 CUDA)
WITH_GPU=OFF

# 是否使用MKL or openblas，TX2需要设置为OFF
WITH_MKL=ON

# 是否集成 TensorRT(仅WITH_GPU=ON 有效)
WITH_TENSORRT=OFF

# paddle 预测库lib名称，由于不同平台不同版本预测库lib名称不同，请查看所下载的预测库中`paddle_inference/lib/`文件夹下`lib`的名称
PADDLE_LIB_NAME=libpaddle_inference

# TensorRT 的include路径
TENSORRT_INC_DIR=/path/to/tensorrt/include

# TensorRT 的lib路径
TENSORRT_LIB_DIR=/path/to/tensorrt/lib

# Paddle 预测库路径
PADDLE_DIR=/home/xxxx/paddle_cpp/paddle_inference
# CUDA 的 lib 路径
CUDA_LIB=/path/to/cuda/lib

# CUDNN 的 lib 路径
CUDNN_LIB=/path/to/cudnn/lib
 

# 以下无需改动
rm -rf build
mkdir -p build
cd build
cmake .. \
    -DWITH_GPU=${WITH_GPU} \
    -DWITH_MKL=${WITH_MKL} \
    -DWITH_TENSORRT=${WITH_TENSORRT} \
    -DTENSORRT_LIB_DIR=${TENSORRT_LIB_DIR} \
    -DTENSORRT_INC_DIR=${TENSORRT_INC_DIR} \
    -DPADDLE_DIR=${PADDLE_DIR} \
    -DWITH_STATIC_LIB=${WITH_STATIC_LIB} \
    -DCUDA_LIB=${CUDA_LIB} \
    -DCUDNN_LIB=${CUDNN_LIB} \
    -DOPENCV_DIR=${OPENCV_DIR} \
    -DPADDLE_LIB_NAME=${PADDLE_LIB_NAME} \

make
echo "make finished!"

**Comment by zhiboniu** [comment]
看起来像是本地opencv读视频环境问题？
尝试修复这段报错log试试呢，也可以看看保存的视频画面有没有问题output/mot_output.mp4
               OpenCV: FFMPEG: tag 0x7634706d/'mp4v' is not supported with codec id 13 and format 'mp4 / MP4 (MPEG-4 Part 14)'
              OpenCV: FFMPEG: fallback to use tag 0x00000020/' ???'

**Comment by vivid333** [comment]
保存的mot_output.mp4是正常的MP4文件
