### ISSUE TITLE
TypeReport: Missing parenthesis that may cause compile error

### ISSUE THREAD

**Issue by yuehaoshi** [PaddlePaddle/Paddle#53437]
### 文档链接&描述 Document Links & Description

Dear Paddle developers,
There are two typos in PaddlePaddle 2.4 official website/API Reference examples on the page of [InMemoryDataset](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/distributed/InMemoryDataset_en.html#inmemorydataset)
The first one is in the example code of `get_memory_data_size(fleet=None)`,
the second one is in the example code of `get_shuffle_data_size(fleet=None)`

### 请提出你的建议 Please give your suggestion

In the last line of each example mentioned, there should be parenthesis after `print`:
`print dataset.get_memory_data_size()` should be `print(dataset.get_memory_data_size())`, and
`print dataset.get_shuffle_data_size()` should be `print(dataset.get_shuffle_data_size())`

**Comment by luotao1** [comment]
@yuehaoshi Hope you can create a PR to fix it, thanks very much!
