### ISSUE TITLE
paddle.exp different outputs on cpu and gpu

### ISSUE THREAD

**Issue by z3guo11** [PaddlePaddle/Paddle#53435]
### bug描述 Describe the Bug

results = dict()
import paddle
paddle.device.set_device('cpu')
arg_1_tensor = paddle.randint(-8,512,[2, 1])
arg_1 = arg_1_tensor.clone()
try:
  results["res_cpu"] = paddle.exp(arg_1,)
except Exception as e:
  results["err_cpu"] = "ERROR:"+str(e)
paddle.device.set_device('gpu')
arg_1 = arg_1_tensor.clone().cuda()
try:
  results["res_gpu"] = paddle.exp(arg_1,)
except Exception as e:
  results["err_gpu"] = "ERROR:"+str(e)

print(results)

### 其他补充信息 Additional Supplementary Information

'res_cpu': Tensor(shape=[2, 1], dtype=int64, place=Place(cpu), stop_gradient=True,
       [[-9223372036854775808],
        [-9223372036854775808]])

 'res_gpu': Tensor(shape=[2, 1], dtype=int64, place=Place(gpu:0), stop_gradient=True,
       [[9223372036854775807],
        [9223372036854775807]])

**Comment by haoyuying** [comment]
您好，您所产生的问题是由于提供的指数幂非法，使得得到的指数溢出，提供幂值可以得到相同的结果。
