### ISSUE TITLE
编译报错symbol lookup error:   undefined symbol: dnnl_layer_normalization_v2_forward_desc_init

### ISSUE THREAD

**Issue by vivid333** [PaddlePaddle/Paddle#53467]
### 问题描述 Issue Description

git checkout
Your branch is up to date with 'origin/release/2.5'.

cmake  -DPY_VERSION=3.7 -DWITH_TESTING=OFF -DWITH_MKL=ON -DON_INFER=ON -DWITH_GPU=OFF   ..
编译到95%左右时报错：
[ 94%] Built target eager_legacy_op_function_generator
[ 95%] Built target kernel_signature_generator
/home/vivid/paddle/Paddle/build/paddle/fluid/eager/auto_code_generator/eager_generator: symbol lookup error: /home/vivid/paddle/Paddle/build/paddle/fluid/eager/auto_code_generator/eager_generator: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init
make[2]: *** [paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/build.make:57: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen] Error 127
[ 95%] Generating libdnnl.so.0
make[1]: *** [CMakeFiles/Makefile2:152394: paddle/fluid/eager/auto_code_generator/CMakeFiles/legacy_eager_codegen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 95%] Built target analysis_helper
[ 95%] Built target final_dygraph_node
[ 95%] copy_if_different /home/vivid/paddle/Paddle/paddle/fluid/pybind/eager_legacy_op_function.cc.tmp to /home/vivid/paddle/Paddle/paddle/fluid/pybind/eager_legacy_op_function.cc
/home/vivid/paddle/Paddle/build/paddle/fluid/pybind/eager_legacy_op_function_generator: symbol lookup error: /home/vivid/paddle/Paddle/build/paddle/fluid/pybind/eager_legacy_op_function_generator: undefined symbol: dnnl_layer_normalization_v2_forward_desc_init
make[2]: *** [paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator_cmd.dir/build.make:63: ../paddle/fluid/pybind/eager_legacy_op_function.cc] Error 127
make[1]: *** [CMakeFiles/Makefile2:149851: paddle/fluid/pybind/CMakeFiles/eager_legacy_op_function_generator_cmd.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

尝试过：
   1. 卸载fastdeploy
         pip3 uninstall fastdeploy-python 
   2.  卸载python命令行安装的paddle,本机根本没安装过gpu的paddle  
              python3 -m pip uninstall paddlepaddle

重新执行编译， 仍报此错误。
从报错现象来看， 是找不到dnnl_layer_normalization_v2_forward_desc_init 定义， 实际上在third_party/mkldnn/src/extern_mkldnn/src/common/layer_normalization.cpp里有实现的。不清楚为什么还报错。

### 版本&环境信息 Version & Environment Information

'origin/release/2.5'.

**Comment by KimBioInfoStudio** [comment]
是不是你环境中存在其他版本的 libdnnl? 可以贴一下 `env|grep dnnl` 或者 `locate libdnnl.so.2`

**Comment by vivid333** [comment]
> env|grep dnnl

万分感谢您的解答。根因确实如你所说，系统里包含了libdnnl.so.2

在此之前是直接基于官方的paddle_inference  so库（根据version.txt说明，好像是v23版本的）使用的，在.bashrc里export此库的所有库路径。  
在代码编译过程中，paddle自己会github里下载extern_mdldnn,  与原来官方的so库产生重复，导致 （个人理解）


总之，问题已经解决，感谢大神指点~~~

**Comment by yywangfei** [comment]
> env|grep

请教一下如何卸载呢，我是用fastdeploy出现了这个问题，我是在镜像里面重新编译了fastdeploy，但是发现/opt下面也有一个fastdeploy
