### ISSUE TITLE
鲲鹏920 cpu  ubuntu系统没带昇腾加速卡

### ISSUE THREAD

**Issue by leizhu1989** [PaddlePaddle/Paddle#53463]
### 请提出你的问题 Please ask your question

请问鲲鹏920 cpu、ubuntu系统没带昇腾加速卡，用cpu推理，也是需要自己编译推理库吗。还是可以下载使用https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html中linux的推理库

**Comment by KimBioInfoStudio** [comment]
https://paddleinference.paddlepaddle.org.cn/master/user_guides/compile_ARM.html

**Comment by westfish** [comment]
x86架构的 arm 都需要自己编译的
