### ISSUE TITLE
[Warning] A lot of slice ops use decrease dims have warning

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#53464]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/PaddleYOLO/tree/release/2.6/configs/ppyolo

对ppyolo和gpt2, 有如下大量warning
每个slice算子都会有这个LOG
```
I0428 17:22:46.380196 157430 slice_utils.h:211] Warning:: In Tensor '__getitem__', if the number of scalar elements in the index is equal to the rank of the Tensor, the output should be 0-D. In order to be consistent with the behavior of previous versions, it will be processed to 1-D. But it is not correct and will be removed in release 2.6. If 1-D is still wanted, please modify the index element from scalar to slice (e.g. 'x[i]' => 'x[i:i+1]'). 
```

这是由于slice算子触发的。
输入int32[4]  输出int32[1]
参数
axes 0 
decrease_axis 0
ends 1

我看了下说是1D slice decrease 输出1D的行为是错的，将要被在2.6删除，但是有大量模型使用了这种方式。
ppyolo模型
链接: https://pan.baidu.com/s/1rFIwvfpi-2QFF67woA4r6w?pwd=krcd 提取码: krcd

**Comment by engineer1109** [comment]
![Screenshot from 2023-04-28 17-37-17](https://user-images.githubusercontent.com/11912040/235112945-7a9031d3-32ab-40d2-8219-7f8627e469f1.png)

**Comment by engineer1109** [comment]
代码Warning https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/slice_utils.h

**Comment by engineer1109** [comment]
@zoooo0820

**Comment by zoooo0820** [comment]
可以先设置环境命令 `export FLAGS_set_to_1d=False`，再执行模型代码。
