### ISSUE TITLE
pptracking C++的threshold_ 参数取值异常

### ISSUE THREAD

**Issue by vivid333** [PaddlePaddle/Paddle#53481]
### bug描述 Describe the Bug

fairmot_hrnetv2_w18_dlafpn_30e_576x320/infer_cfg.yml:
mode: paddle
**draw_threshold: 0.5**
metric: MOT
use_dynamic_shape: false
   

**(gdb) p threshold_
$2 = 2.1822658369689372e+243**
(gdb) l
112	    mot_track.score = *dets.ptr<float>(0, 4);
113	    mot_track.rects = ret;
114	    result->push_back(mot_track);
115	  } else {
116	    std::vector<Track>::iterator titer;
**117	    for (titer = tracks.begin(); titer != tracks.end(); ++titer) {**
118	      //if (titer->score < 0.4) {
119	      if (titer->score < threshold_) {
120	        continue;
121	      } else {

### 其他补充信息 Additional Supplementary Information

release/2.6

**Comment by vivid333** [comment]
根因： threshold_  这个变量没有初始化
解决方案：JDEPredictor构造函数里 最后一行添加   this->threshold_   = config_.draw_threshold_; 或者置其它值

**Comment by Charles-hit** [comment]
感谢反馈，这边已经在修复中了。

**Comment by Charles-hit** [comment]
感谢反馈，这边已经在修复中了。
