### ISSUE TITLE
Could not locate cudnn_ops_infer64_8.dll

### ISSUE THREAD

**Issue by chenzx2** [PaddlePaddle/Paddle#53484]
### 问题描述 Issue Description

import paddle
print(paddle.version.cuda())
print(paddle.version.cudnn())
paddle.utils.run_check()

cuda 11.7
cudnn 8.4.0
Running verify PaddlePaddle program ... 
W0502 16:24:49.593289 13852 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

后面安装了cuda10.2 +cudnn7 paddle验证过了，但运行各种错误，又换回来cuda11.7 cudnn8.5 8.8版本，都不行
我的电脑是 3060 12G的显卡

### 版本&环境信息 Version & Environment Information

import paddle
print(paddle.version.cuda())
print(paddle.version.cudnn())
paddle.utils.run_check()

PaddlePaddle: python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
cuda: 11.7
cudnn: 8.4.0
Running verify PaddlePaddle program ... 
W0502 16:24:49.593289 13852 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.7
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

后面安装了cuda10.2 +cudnn7 paddle验证过了，但运行各种错误，又换回来cuda11.7 cudnn8.5 8.8版本，都不行
我的电脑是 3060 12G的显卡

**Comment by chenzx2** [comment]
zlib也搞过，没用

**Comment by jiahy0825** [comment]
您好，有几个建议：
1. 可以先参考下安装文档，看下 cuda 和 cudnn 版本是否适配，建议参照https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/windows-pip.html 用匹配的cudNN版本。
![97b507acb6a66c7b95e57f650182bf5a](https://user-images.githubusercontent.com/17810795/236613109-b6339daa-ceec-43bc-acfe-55ef4d9a5c0b.png)


2. 从报错信息来看，与 cuda 安装路径错误有关，麻烦检查下 cuda 的安装过程是否有问题，找到一篇链接也许可以参考：https://stackoverflow.com/questions/66355477/could-not-load-library-cudnn-ops-infer64-8-dll-error-code-126-please-make-sure
