### ISSUE TITLE
JamesLim-sy老师可以再审核一下黑客松第四期的34题吗？

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#53487]
### 请提出你的问题 Please ask your question

PR连接：https://github.com/PaddlePaddle/Paddle/pull/53154
CI已经过了。但是老师提出的代码修改意见中，有一处我不知道怎么改合适，希望JamesLim-sy老师能多给一点指导。打扰您了！

**Comment by JamesLim-sy** [comment]
已经在PR里面回复了，我的修改意见核心是能否用一次 broadcast::kTenery操作代替掉，broadcast::kUnary + broadcast::kTenery 的操作组合.

**Comment by WintersMontagne10335** [comment]
@JamesLim-sy 老师您好，抱歉抱歉！没注意到issue里的回复。我已经修改啦。我是新手，不是很熟悉相关流程。非常抱歉。我后来了解到单开issue催是不和规矩的，我以为这个issue关闭了呢，所以没有注意到。
