### ISSUE TITLE
paddleocr文件和官方的不一样

### ISSUE THREAD

**Issue by xia6321** [PaddlePaddle/Paddle#53480]
### 请提出你的问题 Please ask your question

模型训练中要用到train.py文件，我的文件里面没有，我把自己的文件和官方文档对照，发现有很多地方不相同，但我能够使用快速开始里面的方法进行图文识别

**Comment by MissPenguin** [comment]
train.py在这个目录下：https://github.com/PaddlePaddle/PaddleOCR/tree/release/2.6/tools

有别的问题可以到PaddleOCR官网提问哈：https://github.com/PaddlePaddle/PaddleOCR/issues
