### ISSUE TITLE
dims_simplifier.h代码中疑似含有两处小问题

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#53488]
### 问题描述 Please describe your issue

链接：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/dims_simplifier.h

一是，`ExtendInputDimensions`的参数`int N`应该可以删掉，函数中并没有使用该参数；
二是，根据上下文逻辑，123行代码中的`axis`应该修改为`out_idx`。

**Comment by luotao1** [comment]
@WintersMontagne10335 可以直接提 PR 修复一下
