### ISSUE TITLE
"output_tensor.copy_to_cpu()" take too long to execute (PaddleOCR)

### ISSUE THREAD

**Issue by chelzakaria** [PaddlePaddle/Paddle#53485]
### 请提出你的问题 Please ask your question

I have already opened an issue at Paddleocr : https://github.com/PaddlePaddle/PaddleOCR/issues/9836 . But still with no answer, so I thought of opening it here also. 
-----------------------------------------------------------
系统环境/System Environment：Python 3.10.7 | Win10
版本号/Version：CUDA 11.6, CuDNN 8.8 Paddle：2.4.2.post112 PaddleOCR：2.6.1.3
问题相关组件/Related components: RTX 3080 
运行指令/Command Code：
--------------------------------
Trying to optimize the model performance speed by identifying how long code cells/blocks/functions take to execute, I found that in this line "Copying the output of recognition to the CPU": 
https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_rec.py#L542
that it took approximately 50% of whole recognition process which I found weird, compared to the same process for Detection (https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_det.py#L246) or TextClassifier (https://github.com/PaddlePaddle/PaddleOCR/blob/013870d9bc963f7508d5a76f81da872b84471a71/tools/infer/predict_cls.py#L112).
Aiming to optimize the OCR process I want to know why exactly it took that long to execute, and if there is any way to improve it?

**Comment by jiahy0825** [comment]
您好～已联系到对应负责人，后续沟通可以在 [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR) 仓库的 issue 中进行～
issue 跳转链接：https://github.com/PaddlePaddle/PaddleOCR/issues/9836
