### ISSUE TITLE
模型预测执行infer.py无反应

### ISSUE THREAD

**Issue by Junxiang-Zeng8443** [PaddlePaddle/Paddle#53499]
### bug描述 Describe the Bug

![image](https://user-images.githubusercontent.com/112910942/236146005-5e1fe2c6-b534-471a-ab8b-46094112d62d.png)
如图，模型是用paddleclas训练的，已训练成功，在预测的时候执行infer.py无反应，求解答

**Comment by JunnYu** [comment]
你好，这是关于paddleclas套件的问题，建议可以前往 https://github.com/PaddlePaddle/PaddleClas 提问
