### ISSUE TITLE
多机训练场景下, 加载已有模型的重训练（--init_model_path参数）过程中，各个节点模型参数如何初始化？

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#535]
RT， 重点关注：

*  各个节点的参数加载方法？
*  如何支持is_static参数的？

**Comment by backyes** [comment]
早期部分版本对多机的**加载已有模型的重训练** 有部分bug，主要体现在：
* 非0节点会在pserver完成被主节点初始化之前试图从pserver获取模型，此处逻辑有误

最新主干代码对相关逻辑实现比较清晰：
* 集群外围脚本负责为所有节点准备已有模型文件，并存储到本地磁盘
* 所有节点paddle trainer会负责从本地磁盘加载模型，完成初始化。
* 从上面两条可确定，该场景下的模型初始化逻辑基本是共享单机的逻辑，因此 is_static的参数初始化可以理解为等同于单机策略。

@reyoung @qingqing01 @emailweixu @luotao1 各位修改意见的，请comments，这个feature将会有很多同学逐渐使用。

**Comment by qingqing01** [comment]
逻辑是：
- 集群训练提交环境脚本，改过让**所有**节点均下载初始化模型到本地, 然后各个节点均加载模型。这个最新的集群提交环境的脚本里这样做的。
- 加载完毕之后，主节点pserver还会将非static参数(包括随机初始化参数)发送给其他节点 。这点不使用init_model_path也会走这个流程。

我觉得这个逻辑是没有问题的，比如：部分参数load初始化模型、部分参数随机初始化，这样主节点广播一次非static参数到其他节点，我觉得是没有问题，这样保证了每个节点起始的参数是相同的。

这个逻辑很早之前就是这样的，只是部分同学一直只更新paddle代码，并没有更新提交集群环境的外围脚本，导致出错，代码之前也是check的：

```
if (!testing &&
      (trainerInternal_.getGradientMachine()->hasStaticParameters())) {
    CHECK(!FLAGS_init_model_path.empty())
        << "Static parameters should be initialized by --init_model_path";
}
```

@backyes 你指的是要更改这个逻辑吗？

**Comment by backyes** [comment]
从目前github版本来看，处理命令行init_model_path参数和parameter选项is _staticc参数的逻辑，并没有任何问题。

@qingqing01 新版本代码中，init_model_path使能的时候，所有节点应该是各自主动从本地磁盘读取模型完成trainer端参数初始化。

**Comment by backyes** [comment]
经过跟 @qingqing01 讨论，总结如下，以便参考（所有以最新代码为准commit SHA1 77ddce0f0be883bc60d3949bf18dee96dd118e64）： 

* 多机下，每个节点均会从本地节点试图加载参数（第一阶段）
``` c++
 227   if (testing) {
  228     // will load per pass for tester
  229   } else if (paramUtil_->tryLoadParametersFromConfig()) {
  230     // load from config already.
  231   } else {
  232     trainerInternal_.getGradientMachine()->randParameters();
  233   }
```
Trainer.cpp init函数调用开始尝试加载本地参数。如果本地没有相关参数，本阶段加载参数会失败（下一个阶段仍然有一个次加载参数过程，发生在pserver启动之后）
注意： is_static 参数初始化只能发生在该阶段，如果该阶段没有成功加载，那么程序逻辑将不符合预期。（这是一个潜在可能出现风险的坑，最好能加一个check，比如发生is_static配置，必须从本地磁盘完成部分参数的加载）
```
  102   /**
  103    * Try to load parameter from config.
  104    * @return true if can load from trainer config.
  105    */
  106   inline bool tryLoadParametersFromConfig() {
  107     auto& c = config_->getConfig();
  108     if (!c.init_model_path().empty()) {
  109       loadParametersWithPath(c.init_model_path());
  110       return true;
  111     } else if (c.start_pass() > 0) {
  112       CHECK(loadParameters(c.start_pass() - 1));
  113       return true;
  114     } else {
  115       return false;
  116     }
  117   }
```
尝试加载函数实现。

* pserver启动后，会进行第二阶段参数加载（主要进行non static参数初始化）
 ``` c++
  83   parameterClient_.reset(new ParameterClient2(separateSendAndRecv_));
   84   parameterClient_->init(cpuParameters_);
   85   parameterClient_->setTrainerId(FLAGS_trainer_id);
   86
   87   if (FLAGS_trainer_id == 0) {
   88     parameterClient_->setConfig(config_);
   89     copyParametersFromDevice(PARAMETER_VALUE);
   90     parameterClient_->setParameter();
   91     parameterClient_->setStatus(PSERVER_STATUS_PARAMETER_READY);
   92   } else {
   93     parameterClient_->waitForStatus(PSERVER_STATUS_PARAMETER_READY);
   94    ** parameterClient_->getParameter(); **
   95     copyParametersToDevice(PARAMETER_VALUE);
   96   }
```

parameter启动后，主节点完成对所有pserver节点的参数初始化， 然后从节点等待
```
parameterClient_->waitForStatus(PSERVER_STATUS_PARAMETER_READY);
``` 

信号完成自己trainer参数的初始化。

@qingqing01  请review下，逻辑。 方便以后同学熟悉。

**Comment by backyes** [comment]
此issue由内部用户使用集群训练带有is_static参数配置选项的场景下延伸出来，相关问题已经解决，同时对上述问题已做清晰阐述， 故close此issue
