### ISSUE TITLE
内网安装报错 bad interpreter: No such file or directory

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#5350]
运行程序，报错：
bash: /home/work/app/paddle/python27-gcc482/bin/pip: /home/xxx/paddle_internal_release_tools/idl/paddle/output/python27-gcc4: bad interpreter: No such file or directory

解决方案：
在paddle的安装路径home/work/app/paddle下执行
python27-gcc482/install.sh
程序可以运行了。

**Comment by qingqing01** [comment]
@cszhou  感谢你的Issue和解决方法~
