### ISSUE TITLE
RTDETR使用SAHI切图拼图评估报错

### ISSUE THREAD

**Issue by leechenggg** [PaddlePaddle/Paddle#53500]
### 请提出你的问题 Please ask your question

用RTDETR训练visdrone切图版本的数据集时，对训练后的model进行切图拼图评估报错，请问RTDETR支持SAHI切图拼图评估吗？

```
# 模型评估
!python -u tools/eval.py \
-c configs/rtdetr/rtdetr_r101vd_6x_coco.yml \
-o weights=output/rtdetr_r101vd_6x_coco/best_model \
--slice_infer \
--combine_method=nms \
--match_threshold=0.6 \
--match_metric=ios

```
**以下为报错信息**

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
W0504 16:00:10.260017 19411 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0504 16:00:10.263295 19411 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
loading annotations into memory...
Done (t=0.29s)
creating index...
index created!
[05/04 16:00:20] ppdet.data.source.coco INFO: 548 samples and slice to 2842 sub_samples in file /home/aistudio/MyDataset/val.json
[05/04 16:00:23] ppdet.utils.checkpoint INFO: Finish loading model weights: output/rtdetr_r101vd_6x_coco/best_model.pdparams
Traceback (most recent call last):
  File "tools/eval.py", line 208, in <module>
    main()
  File "tools/eval.py", line 204, in main
    run(FLAGS, cfg)
  File "tools/eval.py", line 157, in run
    match_metric=FLAGS.match_metric)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 764, in evaluate_slice
    match_metric)
  File "/home/aistudio/PaddleDetection/ppdet/engine/trainer.py", line 708, in _eval_with_loader_slice
    outs['bbox'][:, 2:4] = outs['bbox'][:, 2:4] + shift_amount
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 304, in __impl__
    return math_op(self, other_var, -1)
ValueError: (InvalidArgument) Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1200, 2] and the shape of Y = [4, 2]. Received [1200] in X is not equal to [4] in Y at i:0.
  [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at /paddle/paddle/phi/kernels/funcs/common_shape.h:84)

**Comment by leechenggg** [comment]
项目链接
项目“RTDETR+SAHI切图”共享链接(有效期三天)：https://aistudio.baidu.com/studio/project/partial/verify/6092017/cadb48b85f3b4aaaae703e1b91883de2

**Comment by JunnYu** [comment]
你好，关于这个问题，你可以去 https://github.com/PaddlePaddle/PaddleDetection 库去问一下

**Comment by JunnYu** [comment]
发现已在 https://github.com/PaddlePaddle/PaddleDetection/issues/8192 提问，关闭issue
