### ISSUE TITLE
API文档—— Momentum解释的疑惑

### ISSUE THREAD

**Issue by utopiar** [PaddlePaddle/Paddle#5351]
<img width="1079" alt="qq20171103-144704 2x" src="https://user-images.githubusercontent.com/5753928/32362673-247bd3e6-c0a6-11e7-96d2-3804d8fc444b.png">
根据文档中的介绍，感觉并不像是是介绍Momentum的优化方法，同时也没有说明其中 `momentum`参数的作用，希望更新下！！！！

同时文档中的公式为什么不能正常显示？这样很影响阅读，每次还要粘出去自己生成公式，用户体验很差！

**Comment by qingqing01** [comment]
@utopiar 感谢指出文档问题，我们正在改进文档~

> 同时文档中的公式为什么不能正常显示？

有可能是网速问题，我这里就能正常显示~

**Comment by utopiar** [comment]
刚试了下，可能是浏览器兼容的问题吧，mac下safari、chrom都不能正常显示公式，win下浏览器可以正常显示，辛苦看下是否是适配问题吧~

**Comment by utopiar** [comment]
刚看了下应该是中文文档里的公式无法正常显示，而英文文档里的公式可以正常显示，应该是配置上的问题吧，
http://doc.paddlepaddle.org/doc_cn/api/v2/config/optimizer.html  ——> 无法正常显示
http://doc.paddlepaddle.org/doc/api/v2/config/optimizer.html        ——> 可以正常显示

**Comment by utopiar** [comment]
同时关于`Adam`优化算法，感觉api文档里写的有些问题，代码中实现如下：

```
  for (size_t i = 0; i < param.size(); ++i) {
    m[i] = beta_1_ * m[i] + (1.0 - beta_1_) * grad[i];
    v[i] = beta_2_ * v[i] + (1.0 - beta_2_) * grad[i] * grad[i];
    param[i] -=
        learning_rate * (m[i] / std::sqrt(v[i] + epsilon_) + decay_ * param[i]);
  }
```

而api文档中的公式如下：
<img width="391" alt="wx20171103-161911 2x" src="https://user-images.githubusercontent.com/5753928/32365350-8a6205f0-c0b4-11e7-83a3-4247aa7d5b84.png">
个人感觉应该是这样的：
![15096976909641](https://user-images.githubusercontent.com/5753928/32365369-99a7fdd0-c0b4-11e7-8427-4880fe3c31a0.jpg)

**Comment by qingqing01** [comment]
@utopiar 感谢反馈，在https://github.com/PaddlePaddle/Paddle/pull/5391更改了你的建议。其他文档质量问题，我们也正在提升。感谢你的反馈。
