### ISSUE TITLE
torch模型 转为 paddle 模型，动态模型可以正常运行，静态模型运行报错

### ISSUE THREAD

**Issue by nlpslg001** [PaddlePaddle/Paddle#53519]
### bug描述 Describe the Bug
问题描述：
加载paddle 静态模型在 paddle.inference.create_predictor(config) 时报错，但是对应的动态模型能够正常加载已经推理部署

运行环境
Python 3.8.5
paddlepaddle==2.4.2
gcc version 4.8.5
x86_64
CentOS Linux release 7.6.1810 (Core)
运行代码在报错日志后面

以下是运行出错信息：
--- Running analysis [ir_graph_build_pass]
--- Running analysis [ir_analysis_pass]
--- Running IR pass [simplify_with_basic_ops_pass]
--- Running IR pass [layer_norm_fuse_pass]
---    Fused 0 subgraphs into layer_norm op.
--- Running IR pass [attention_lstm_fuse_pass]
--- Running IR pass [seqconv_eltadd_relu_fuse_pass]
--- Running IR pass [seqpool_cvm_concat_fuse_pass]

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle_infer::Predictor::Predictor(paddle::AnalysisConfig const&)
1   std::unique_ptr<paddle::PaddlePredictor, std::default_delete<paddle::PaddlePredictor> > paddle::CreatePaddlePredictor<paddle::AnalysisConfig, (paddle::PaddleEngineKind)2>(paddle::AnalysisConfig const&)
2   paddle::AnalysisPredictor::Init(std::shared_ptr<paddle::framework::Scope> const&, std::shared_ptr<paddle::framework::ProgramDesc> const&)
3   paddle::AnalysisPredictor::PrepareProgram(std::shared_ptr<paddle::framework::ProgramDesc> const&)
4   paddle::AnalysisPredictor::OptimizeInferenceProgram()
5   paddle::inference::analysis::Analyzer::RunAnalysis(paddle::inference::analysis::Argument*)
6   paddle::inference::analysis::IrAnalysisPass::RunImpl(paddle::inference::analysis::Argument*)
7   paddle::inference::analysis::IRPassManager::Apply(std::unique_ptr<paddle::framework::ir::Graph, std::default_delete<paddle::framework::ir::Graph> >)
8   paddle::framework::ir::Pass::Apply(paddle::framework::ir::Graph*) const
9   paddle::framework::ir::SeqPoolCVMConcatFusePass::ApplyImpl(paddle::framework::ir::Graph*) const
10  paddle::framework::ir::GraphPatternDetector::operator()(paddle::framework::ir::Graph*, std::function<void (std::map<paddle::framework::ir::PDNode*, paddle::framework::ir::Node*, paddle::framework::ir::GraphPatternDetector::PDNodeCompare, std::allocator<std::pair<paddle::framework::ir::PDNode* const, paddle::framework::ir::Node*> > > const&, paddle::framework::ir::Graph*)>)
11  paddle::framework::ir::GraphPatternDetector::MarkPDNodesInGraph(paddle::framework::ir::Graph const&)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1683268690 (unix time) try "date -d @1683268690" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 5729 (TID 0x7f78d36d8740) from PID 0 ***]

Segmentation fault

### 其他补充信息 Additional Supplementary Information

模型加载代码
import sys

import numpy as np
import paddle
import paddle.inference as paddle_infer

#modelPath = "./pd_model/inference_model/model.pdmodel"
#paramsPath = "./pd_model/inference_model/model.pdiparams"

modelPath = "./newmodel/newmodel.pdmodel"
paramsPath = "./newmodel/newmodel.pdiparams"
config = paddle.inference.Config(modelPath, paramsPath)
config.disable_gpu()
predictor = paddle.inference.create_predictor(config)

print("模型加载完成")

**Comment by risemeup1** [comment]
bug描述可以写详细点儿吗，你要干什么以及你的环境还有你出问题的代码等等

**Comment by nlpslg001** [comment]
> bug描述可以写详细点儿吗，你要干什么以及你的环境还有你出问题的代码等等

问题描述已经更新，你看可以吗？还需要其它错误信息吗？

**Comment by jiweibo** [comment]
看log可能是pass匹配逻辑遇到了问题，您可以尝试下禁用这个pass。

`config.delete_pass("seqpool_cvm_concat_fuse_pass")`

如果还是有问题，可以尝试关闭所有优化

`config.switch_ir_optim(False)`

**Comment by nlpslg001** [comment]
> 看log可能是pass匹配逻辑遇到了问题，您可以尝试下禁用这个pass。
config.delete_pass("seqpool_cvm_concat_fuse_pass")`

加上这个限制模型加载成功。
但是通过config.enable_mkldnn()
开启 MKLDNN 加速选项
是的模型推理非常慢，且推理结果错误(和不开启MKLDNN 加速结果不一样)
