### ISSUE TITLE
paddle full和nonzero各种奇怪现象

### ISSUE THREAD

**Issue by weishu27** [PaddlePaddle/Paddle#53520]
### bug描述 Describe the Bug

![截屏2023-05-05 下午3 13 30](https://user-images.githubusercontent.com/129355431/236398150-4cead58e-679e-4252-8f95-11fe97b1a737.png)

各种诡异情况
环境：GPU Compute Capability: 8.6, Driver API Version: 11.7, Runtime API Version: 10.2
W0505 07:11:12.595060  5144 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
安装：
paddle-bfloat       0.1.7
paddlepaddle-gpu    2.3.2

**Comment by weishu27** [comment]
改成paddlepaddle-gpu 2.4.2.post112就正常了-_-.....

**Comment by risemeup1** [comment]
对，我这边也复现了，改成paddlepaddle-gpu 2.4.2.post112就正常了
