### ISSUE TITLE
paddle.rand 输出全是0 

### ISSUE THREAD

**Issue by gsnow11** [PaddlePaddle/Paddle#53536]
### 请提出你的问题 Please ask your question

我在对paddle API 进行学习时候出现 paddle.rand 输出全是0 情况请问是什么原因导致的？

import paddle
# example 1: attr shape is a list which doesn't contain Tensor.
out1 = paddle.rand(shape=[2, 3]).numpy()*100
out4 = paddle.randn(shape=[2, 3])
# example 2: attr shape is a list which contains Tensor.
dim1 = paddle.to_tensor([2], 'int64')
dim2 = paddle.to_tensor([3], 'int32')
out2 = paddle.rand(shape=[dim1, dim2, 2])shape_tensor = paddle.to_tensor([2, 3])
out3 = paddle.rand(shape_tensor)

输出out1,out2,out3,out4 所有的数据都为0

环境为

Please NOTE: device: 0, GPU Compute Capability: 5.0, Driver API Version: 12.0, Runtime API Version: 11.2
W0505 21:01:24.236230 17196 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.

paddlepaddle-gpu    2.4.2.post112

**Comment by risemeup1** [comment]
你好，我目前正在复现这个问题

**Comment by risemeup1** [comment]
你好，我们这边无法复现这个问题
