### ISSUE TITLE
paddle.inference 使用 mkldnn_enabled 加速，推理速度变慢，且推理结果和原模型结果不一致

### ISSUE THREAD

**Issue by nlpslg001** [PaddlePaddle/Paddle#53543]
### 请提出你的问题 Please ask your question

paddle.inference 使用 mkldnn_enabled 加速，推理速度变慢，且推理结果和原模型结果不一致。
1.没有设置config.enable_mkldnn() 时，推理速度1s左右
2.设置config.enable_mkldnn()后，推理速度60s以上

运行环境
Python 3.8.5
paddlepaddle==2.4.2
gcc version 4.8.5
x86_64
CentOS Linux release 7.6.1810 (Core)
下面是加速前后对比，以及代码：
未加速截图
![image](https://user-images.githubusercontent.com/125854883/236593557-c2c48e23-bdf7-44cb-b045-5e5c8b4dc31f.png)

加速截图
![image](https://user-images.githubusercontent.com/125854883/236593535-b70227a5-1967-4536-b907-5d252a423ad0.png)

代码：
import sys
#import trans
import numpy as np
import paddle
import paddle.inference as paddle_infer
import time
import readpic

transform = readpic._transform(224)

modelPath = "./pd_model/inference_model/model.pdmodel"
paramsPath = "./pd_model/inference_model/model.pdiparams"
config = paddle.inference.Config(modelPath, paramsPath)
config.delete_pass("seqpool_cvm_concat_fuse_pass")
config.disable_gpu()
config.set_cpu_math_library_num_threads(4)
config.enable_mkldnn()
predictor = paddle.inference.create_predictor(config)

print("模型加载完成")

picurl = "http://static2.ivwen.com/users/810860/80dccbca38de419d90defc7cea966a7d.jpeg"
image = readpic.readpic(picurl)
image = transform(image).unsqueeze(0).to("cpu")
image = image.numpy()

input_names = predictor.get_input_names()
input_tensor = predictor.get_input_handle(input_names[0])
input_tensor.reshape(image.shape)
input_tensor.copy_from_cpu(image)

start = time.time()
predictor.run()
print("耗时：",time.time() - start)
output_names = predictor.get_output_names()
output_tensor = predictor.get_output_handle(output_names[0])
output_data = output_tensor.copy_to_cpu()
print(output_data)

**Comment by xiaoxiaohehe001** [comment]
可以使用develop版本库测试下，是否存在相同的问题
