### ISSUE TITLE
How to put tensor in share memory?

### ISSUE THREAD

**Issue by Birdylx** [PaddlePaddle/Paddle#53544]
### 请提出你的问题 Please ask your question

torch可以用[`share_memory_`](https://pytorch.org/docs/1.9.1/generated/torch.Tensor.share_memory_.html?highlight=share_memory#torch.Tensor.share_memory_) api把数据放在share_memory中让不同的worker共享，paddle有类似的实现吗？

**Comment by LokeZhou** [comment]
你好，paddle暂不支持该api。如果是在DataLoader阶段使用，可以设置use_shared_memory参数，具体可参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/io/DataLoader_cn.html#dataloader
