### ISSUE TITLE
device_guard 不支持 除npu外的其它device，希望支持

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#53578]
RT.
![image](https://user-images.githubusercontent.com/127805199/236724265-60a6e56a-b993-4eaa-ad47-614554da8514.png)

related: https://github.com/PaddlePaddle/Paddle/pull/52774/files

是否可以使用get_all_custom_device_type等接口实现对CustomDevice的支持，期望paddle 2.5版本支持，谢谢

**Comment by YanhuiDua** [comment]
你好，你的需求已经收到，我们最近会开发，开发完成后会在此issue给出PR链接

**Comment by YanhuiDua** [comment]
https://github.com/PaddlePaddle/Paddle/pull/53808

**Comment by YanhuiDua** [comment]
你好，这个功能在develop支持，不合入2.5版本

**Comment by YanhuiDua** [comment]
PR已经合入，这个issue先关闭了，有问题可以再提问
