### ISSUE TITLE
作分类任务，训练时报错标签超界问题

### ISSUE THREAD

**Issue by JJYjackson** [PaddlePaddle/Paddle#53574]
### 请提出你的问题 Please ask your question

——环境：
AI Studio 经典版
![image](https://user-images.githubusercontent.com/65533171/236682530-3d0e904a-cc54-494f-8f52-46ef2aca99bd.png)
——问题描述：作分类问题，自定义了数据集和标签，然后将生成的traindata和testdata输入到model_CNN_net.fit()中去训练，然后报错为标签超界问题。标签类别为31种，每种有33张图片，检查标签打印信息为[0,0,0,0,.....,30,30,30,30,30],并未超界，不知道哪里出了问题。
——报错信息及训练代码：
![image](https://user-images.githubusercontent.com/65533171/236682882-bf030d9c-707f-4734-9a3a-e6f40442aef5.png)
![image](https://user-images.githubusercontent.com/65533171/236682906-5a7c47c7-8bfb-4b47-b12b-e446a051b5e2.png)
![image](https://user-images.githubusercontent.com/65533171/236683067-cdccd462-d214-407d-a398-db66fa3c2fcc.png)

自定义数据集代码及打印信息：
![image](https://user-images.githubusercontent.com/65533171/236683275-24f2965f-fded-432f-9e9c-1b9c576ab41f.png)
![image](https://user-images.githubusercontent.com/65533171/236683128-98a511a0-f1f7-4e45-9ccf-c3a03963a6cc.png)
![image](https://user-images.githubusercontent.com/65533171/236683147-156496a3-857b-4323-aab9-a5a86911596f.png)
![image](https://user-images.githubusercontent.com/65533171/236683160-5764b090-1ef8-43aa-b5f9-bb1e9748bb71.png)

**Comment by JJYjackson** [comment]
问题已经解决，是自己网络最后一层线性层的输出个数没改过来。

**Comment by GGBond8488** [comment]
hello,是还有什么问题吗，又打开了这个issue
