### ISSUE TITLE
docer运行失败

### ISSUE THREAD

**Issue by 350050183** [PaddlePaddle/Paddle#53597]
### bug描述 Describe the Bug

λ 9372568bdeb5 /home python
Python 3.7.13 (default, Apr 24 2022, 01:04:09) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy
>>> import paddle
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
Segmentation fault

### 其他补充信息 Additional Supplementary Information

system env: CPU arm64(apple m2)
docker version:4.19.0 (106363)

按官方的教程，运行后直接segmentation fault

**Comment by zxcd** [comment]
应该是paddle安装出现了问题，建议重新安装paddle，关注一下中间是否有安装失败的地方
