### ISSUE TITLE
【demo】【语义标注】demo/semantic_role_labeling中的可执行脚本需要一可执行方式更新到github中

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#536]
1.	demo/semantic_role_labeling中的可执行脚本需要一可执行方式更新到github中，当前demo中并没有执行权限，建议以执行权限更新。
![image](https://cloud.githubusercontent.com/assets/6229206/20453866/2a50186e-ae6d-11e6-99de-7b31a5c7c6db.png)
![image](https://cloud.githubusercontent.com/assets/6229206/20453867/2fec3276-ae6d-11e6-912e-d7576e0f68c4.png)

**Comment by qingqing01** [comment]
#407
