### ISSUE TITLE
python3.7  on windows :ValueError: Target -37 is out of lower bound. 

### ISSUE THREAD

**Issue by Alexhk01** [PaddlePaddle/Paddle#53603]
### bug描述 Describe the Bug

Paddle detection在windows上python3.7训练遇到如下问题：paddle\nn\functional\loss.py", line 1720, in cross_entropy
    label_min.item()))
ValueError: Target -37 is out of lower bound.

### 其他补充信息 Additional Supplementary Information

Paddle detection在windows上python3.7训练遇到如下问题：paddle\nn\functional\loss.py", line 1720, in cross_entropy
    label_min.item()))
ValueError: Target -37 is out of lower bound.

**然后paddle detection的工作人员帮忙发现是paddle框架的问题**，其回复如下：

首先，我这边在Windows上复现了这个问题，是paddle框架的bug，paddle.masked_select这个算子在gpu下的运算是错误的。附上截图：

<img width="713" alt="203725256-df6d87b9-1f6d-44e9-a080-fb4c7232331c" src="https://user-images.githubusercontent.com/92071703/236788117-e15e4c72-7eec-45cc-b049-57c92a42487d.png">

ppyoloe模型在计算loss的时候使用到了这个算子，导致了后续结果出nan。
其次，这个问题我是在Python3.7的环境下才能复现，在Python3.9的环境下是正常的，附上截图：

<img width="842" alt="203725827-f07a4482-cc55-4449-8e6d-d4f170259c9e" src="https://user-images.githubusercontent.com/92071703/236787975-4d2865ab-a7d2-4cc6-b1f7-9d2a35abf9a2.png">

最后，这个问题我已经反馈给了Paddle框架的同学，后续会进行排期修复。为了不影响你使用，建议你试一下在Python3.9环境下安装paddle-develop版本跑ppyoloe模型的训练，给你带来的不便，我们深感抱歉～

Originally posted by @ghostxsl in https://github.com/PaddlePaddle/PaddleDetection/issues/6723#issuecomment-1326083748

————
遇到相同的问题，请问paddle框架的这个bug解决了么？

**Comment by zxcd** [comment]
可以尝试一下paddle 2.4之后的版本看看是否还有问题

**Comment by Alexhk01** [comment]
> 可以尝试一下paddle 2.4之后的版本看看是否还有问题

it works,thanks
