### ISSUE TITLE
LaTeX in Chinese documents doesn't display, but works in the English documents.

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5362]
This issue is copied from https://github.com/PaddlePaddle/Paddle/issues/5351#issuecomment-341636097 by @5idaidai 

I confirmed it by click the following two URLs

1. http://doc.paddlepaddle.org/doc_cn/api/v2/config/optimizer.html
1. http://doc.paddlepaddle.org/doc/api/v2/config/optimizer.html

**Comment by daming-lu** [comment]
This should be related to https://github.com/PaddlePaddle/PaddlePaddle.org/issues/256
We are looking into it. Thanks Yi!

**Comment by daming-lu** [comment]
We do not have this issue in the new website:

http://staging.paddlepaddle.org:82/docs/0.10.0/documentation/zh/api/v2/config/optimizer.html

**Comment by daming-lu** [comment]
![screen shot 2017-11-08 at 12 02 22 pm](https://user-images.githubusercontent.com/5635322/32571577-c45e3f96-c47c-11e7-9492-1af479a48426.png)
