### ISSUE TITLE
编译推理库是否可以依赖静态库

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/Paddle#53639]
### 请提出你的问题 Please ask your question

缘由：编译服务器和部署服务器是分开的，部署服务器不可能每个都装一下CUDA，CUDNN，TensorRT这些包，但是目前paddle inference推理库编译依赖的是CUDA,CUDNN,TensorRT动态库，以至于要将算法包移植到部署服务器上这些库都需要移植。**是否可以**在编译paddle inference库的时候对其赖库使用静态连接，只是用CUDA/CUDNN/TensorRT的静态库（.a库），而不是用动态库（.so库），这样后续使用paddle inference的时候就不需要连带CUDA/CUDNN/TenosrRT一起了。

如果可以基于CUDA/CUDNN/TensorRT的静态库编译paddle inference，那我应该怎么设置，有没有控制变量用于控制。

**Comment by chalsliu** [comment]
建议：
1、可以考虑容器化部署
2、或者，编译后CUDA,CUDNN,TensorRT动态库放到third_party路径，再部署


静态链接；
1、会造成库体积过大
2、可能造成运行时占用的内存大小增加
3、nvcc_lazy功能要求使用动态库

**Comment by LiquorPerfect** [comment]
@chalsliu 
但是使用paddle infernece推理库的动态库，有一个多G，有没有什么编译开关可以使推理库小一点，我只要在 x86CPU和T4/P4 GPU上推理。
现在使用paddle inferece的动态库，再使用tensorrt，整个依赖接近3G（cuda的相关库+tensorrt的库+paddle库）。部署环境不可能事先都已经安装好cuda/tensorrt，一般都是将所有的依赖库放在一起整包给出去。**有没有可以减小依赖库大小的操作**。

我看了下编译开关：除了设置CUDA_ARCH_NAME为指定的GPU架构不设置为ALL，可以减少生成的推理库，还有其他的方法吗？
