### ISSUE TITLE
dlpack 提问

### ISSUE THREAD

**Issue by ahua2333** [PaddlePaddle/Paddle#53640]
### 请提出你的问题 Please ask your question

想问下dlpack 在完成框架间转换的时候是如何 确定stream 同步的，因为不同框架间同步的方式不同，看array api 中是有__dlpack__(steam) 来保证自己框架去做同步，pytotch 类似的实现是：https://github.com/pytorch/pytorch/blob/main/torch/utils/dlpack.py#L115， 但是在paddle中好像并没有这个功能，我理解是说用户自己在调用dlpack的自己手动调用一些torch.full_sync这样的接口来保证steam的同步性吗？框架本身只做转换，还是说paddle内部已经支持了？

**Comment by DesmonDay** [comment]
稍等，我看代码确认下，大概明天给你答复。

**Comment by DesmonDay** [comment]
看了一下实现代码，我们在进行dlpack数据的拷贝时调用了paddle::memory::Copy接口，然而这个接口并不会自动做同步，所以目前的实现代码是需要自动手动同步的。但正常来说应当让框架来保证同步性，这个后续我会增加相应的实现来保证。如果提PR了就在这里同步一下。
