### ISSUE TITLE
Could not load library libcudnn_ops_infer.so.8

### ISSUE THREAD

**Issue by shamojiayu001** [PaddlePaddle/Paddle#53651]
### 问题描述 Issue Description

安装paddle之后运行paddle.utils.run_check()报错
`
Running verify PaddlePaddle program ... 
W0509 18:35:53.972074  4272 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.0
Could not load library libcudnn_ops_infer.so.8. Error: libcudnn_ops_infer.so.8: cannot open shared object file: No such file or directory
Please make sure libcudnn_ops_infer.so.8 is in your library path!

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::StandaloneExecutor::Run(paddle::framework::Scope*, std::vector<std::string, std::allocator<std::string > > const&, std::vector<std::string, std::allocator<std::string > > const&)
1   paddle::framework::InterpreterCore::Run(std::vector<std::string, std::allocator<std::string > > const&)
2   paddle::framework::interpreter::build_op_func_list(phi::Place const&, paddle::framework::BlockDesc const&, std::set<std::string, std::less<std::string >, std::allocator<std::string > > const&, std::vector<paddle::framework::OpFuncNode, std::allocator<paddle::framework::OpFuncNode> >*, paddle::framework::VariableScope*, bool, bool)
3   paddle::platform::DeviceContextPool::Get(phi::Place const&)
4   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_complete_async()
5   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
6   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
7   std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > paddle::platform::CreateDeviceContext<phi::GPUContext>(phi::Place const&, bool)
8   phi::GPUContext::GPUContext(phi::GPUPlace const&, bool)
9   phi::InitGpuProperties(phi::Place, int*, int*, int*, int*, int*, int*, std::array<int, 3ul>*)
10  cudnnGetVersion

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1683628553 (unix time) try "date -d @1683628553" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3ec000010b0) received by PID 4272 (TID 0x7ff89d214200) from PID 4272 ***]

Aborted (core dumped)
`
我在机器上找到了 libcudnn_ops_infer.so.8这个文件并尝试把它所在的路径放到LD_LIBRARY_PATH或者在/usr/lib建立软链接到这个文件，但都没有起作用

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.2
Paddle With CUDA: True

OS: ubuntu 18.04
GCC version: (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: version 3.23.0-rc4
Libc version: glibc 2.27
Python version: 3.8.7

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: 470.86
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090
GPU 3: NVIDIA GeForce RTX 3090
GPU 4: NVIDIA GeForce RTX 3090
GPU 5: NVIDIA GeForce RTX 3090
GPU 6: NVIDIA GeForce RTX 3090
GPU 7: NVIDIA GeForce RTX 3090
GPU 8: NVIDIA GeForce RTX 3090
GPU 9: NVIDIA GeForce RTX 3090

****************************************

**Comment by zhengqiwen1997** [comment]
你的cuda版本是什么呀？是11.4吗？paddle不支持cuda11.4的安装。
