### ISSUE TITLE
paddleslim 静态量化后的模型 预测问题：input and filter data type should be consistent, but received input data type is int and filter type is int8_t

### ISSUE THREAD

**Issue by nlpslg001** [PaddlePaddle/Paddle#53664]
### 请提出你的问题 Please ask your question

环境：python3.8

cpu 详情
![image](https://github.com/PaddlePaddle/Paddle/assets/125854883/a0fc9a25-9b1e-4134-838a-5bb211a43dc7)

报错信息
![image](https://github.com/PaddlePaddle/Paddle/assets/125854883/836c6df6-76eb-4cee-940e-9f9abf27f112)

问题：
 在图片预处理后，输入模型前，我已经通过image = image.astype('int8')  转换了数据类型。但是在转为tensor时，还是int32，验证方法如下
![image](https://github.com/PaddlePaddle/Paddle/assets/125854883/20870b00-51ca-453e-9cbe-4383a377d181)

请问这个问题怎么处理？

**Comment by heavengate** [comment]
导出模型得时候就需要指定输入的dtype=int8
