### ISSUE TITLE
Some operators do not follow naming convention

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#5366]
Authors of operators should follow the name convention as detailed in [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/name_convention.md).

Below is the list of ops that does not follow parameter naming convention. 
It is suggested that the main author of the operator fix the issue.

People can add to this list when they find applicable cases.

- [x] lstm_op (attribute names does not follow snake_case) ( @qingqing01 ) 
- [ ] lstm_unit_op (Input name C_prev does not follow CamelCase) ( @zchen0211 )
- [x] momentum_op (attribute name useNesterov does not follow snake_case) ( @sidgoyal78 )
- [x] pool_op (some attribute names does not follow snake_case) ( @chengduoZH )
- [x] pool_with_index_op (some attribute names does not follow snake_case) ( @chengduoZH )
- [ ] recurrent_op (input/output/attr names does not follow conventions) ( @reyoung )

**Comment by qingqing01** [comment]
The attribute names for `lstm_op` is fixed in https://github.com/PaddlePaddle/Paddle/pull/5429
