### ISSUE TITLE
get_available_device 返回空列表

### ISSUE THREAD

**Issue by liangjihua** [PaddlePaddle/Paddle#53675]
在安装有 GPU 的机器上调用 `paddle.device.get_available_device()` 返回空列表，这个情况文档中没有描述。
![image](https://github.com/PaddlePaddle/Paddle/assets/35123083/45626e88-e069-43a6-9cb2-9f69e6b7999c)

**Comment by Miracle2333** [comment]
您好，可以提供下运行环境的具体信息吗，比如cuda版本，安装paddle的版本等，以帮助我们这边复现问题

**Comment by liangjihua** [comment]
cuda 版本： 10.2
paddle 版本：2.4.2 （gpu版的）

**Comment by ronny1996** [comment]
目前这个接口只开放给custom device

**Comment by liangjihua** [comment]
好吧，了解了

**Comment by lmw0320** [comment]
> 目前这个接口只开放给custom device

这个是什么意思？？
我测试了好几个接口，都是返回的空列表。---使用paddlepaddle-gpu:2.3.2.post112
<img width="539" alt="0" src="https://github.com/PaddlePaddle/Paddle/assets/37755235/c3691c10-04d9-4e50-953b-eb9721127944">
