### ISSUE TITLE
【社区治理】enkilee 发起 Committer 身份申请

### ISSUE THREAD

**Issue by enkilee** [PaddlePaddle/Paddle#53670]
## 基本信息
<html>
<body>

申请人 GitHub ID | Paddle Repo 整体 merge PR 数 | Paddle Repo 整体 review PR 数 | Paddle Repo 整体报告 Issue 数
-- | -- | -- | --
enkilee | [36](https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Apr+is%3Amerged+author%3Aenkilee+sort%3Aupdated-desc) | [0](https://github.com/PaddlePaddle/Paddle/pulls?q=is%3Apr+is%3Amerged+reviewed-by%3Aenkilee+-author%3Aenkilee+sort%3Aupdated-desc) | [2](https://github.com/PaddlePaddle/Paddle/issues?q=is%3Aissue+author%3Aenkilee+sort%3Aupdated-desc)

</body>
</html>

## 社区贡献概况
以下是此前在本 repo 里做过的贡献：

添加PaddlePaddle API
添加CINN代码
修复部分 API 文档及一些 typo 之类的
单测报错信息优化

## “高质量” merged PR 展示
<html>
<body>

PR 号 | PR 标题 | PR 简介 | Reviewer
-- | -- | -- | --
[#52544](https://github.com/PaddlePaddle/Paddle/pull/52544) | [PaddlePaddle Hackathon4] add nextafter API ...| 第四期 Hackathon 任务 | luotao1, jeff41404, heavyrain-lzy, sunzhongkai588
[#51275](https://github.com/PaddlePaddle/Paddle/pull/51275),[#51615](https://github.com/PaddlePaddle/Paddle/pull/51615), [#52668](https://github.com/PaddlePaddle/Paddle/pull/52668), [#51300](https://github.com/PaddlePaddle/Paddle/pull/51300), [#52388](https://github.com/PaddlePaddle/Paddle/pull/52388),[#51197](https://github.com/PaddlePaddle/Paddle/pull/51197),  [#51185](https://github.com/PaddlePaddle/Paddle/pull/51185) | [PaddlePaddle Hackathon4] add float16 and bfloat16 for ...| 第四期 Hackathon 任务 | ZzSean
[#51439](https://github.com/PaddlePaddle/Paddle/pull/51493) | [PaddlePaddle Hackathon4] label_smooth add fp16 support | 第四期 Hackathon 任务 | zhangting2020
[#1270](https://github.com/PaddlePaddle/CINN/pull/1270) | CINN调度原语开发 | Add SampleCategorical function | CtfGo
[#1069](https://github.com/PaddlePaddle/CINN/pull/1069) | CINN基础算子开发 | Add reciprocal function | thisjiang
[#5441](https://github.com/PaddlePaddle/docs/pull/5441) | API 文档 修复| broadcasting超链接失效  | Ligoml

</body>
</html>

## 担保人意见
@Ligoml, @luotao1

**Comment by luotao1** [comment]
+1
@enkilee 在黑客松的多个方向（基础API开发、数据类型扩展），快乐开源的多个活动（如 CINN开发、框架静态图算子自动生成、PHI 算子注册信息修复、flake8 代码工具引入、API文档体验提升）都很积极，不仅自己完成了很多子任务，还会在交流群里帮助和鼓励其他开发者。

**Comment by Ligoml** [comment]
+1

**Comment by raindrops2sea** [comment]
+1

**Comment by raindrops2sea** [comment]
感谢enkilee对飞桨社区的贡献！祝贺成为Paddle repo 的 Committer！

**Comment by enkilee** [comment]
@luotao1 @Ligoml @raindrops2sea 
已收到，感谢~ =w=
