### ISSUE TITLE
使用dockerfile构建镜像，安装paddlepaddle失败

### ISSUE THREAD

**Issue by wfs420100** [PaddlePaddle/Paddle#53688]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/64070362/f1dbf9d8-171f-4867-9327-996e3d34bfba)

![image](https://github.com/PaddlePaddle/Paddle/assets/64070362/f457efd0-d70f-4ece-8936-eaefa06640fa)

**Comment by Miracle2333** [comment]
你好，可以提供下安装的硬件环境吗，还有docker的信息

**Comment by wfs420100** [comment]
已经尝试在服务器上进行构建，构建成功

构建失败的设备信息：
Apple M1 Pro  
![image](https://github.com/PaddlePaddle/Paddle/assets/64070362/18d06a0a-d9fb-4c5f-9bb6-8f7ae509aafa)

**Comment by Miracle2333** [comment]
pip install的具体log有吗，一般pip install的问题有链接失败没法下载到安装包或者安装的时候有环境冲突，所以需要提供下pip install的具体log

**Comment by doylecl** [comment]
你好，解决了吗
