### ISSUE TITLE
提交合并时CI错误

### ISSUE THREAD

**Issue by SaltFish11** [PaddlePaddle/Paddle#53693]
### 问题描述 Please describe your issue

<img width="869" alt="cfafa4607b7e03c7b9fdcb2335771509" src="https://github.com/PaddlePaddle/Paddle/assets/108038822/ffee462a-65be-49f2-9ef9-18a4771f05d6">

**Comment by Miracle2333** [comment]
您好，可以提供下pr的具体地址吗

**Comment by SaltFish11** [comment]
您好，已解决。谢谢
