### ISSUE TITLE
【demo】【Installing from source】是否需要将mkdir build && cd build 提前到download and setup章节中

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#537]
1.	在使用源码编译安装时，用户按照文档顺序进行安装。在download and setup中，让读者下载paddle后，紧接下文汇总的options直接使用cmake .. xxx 方式进行预写编译文件，但是，此时用户所在路径为paddle跟路径，如果进行cmake .. xxx会出现报错。虽然在build and install中有指引用户建立build路径并进入该路径进行 cmake ..。但是否应该将mkdir build && cd build 提前到download and setup章节中？
![image](https://cloud.githubusercontent.com/assets/6229206/20460469/681e62b6-af1e-11e6-9bdc-93d9c73e9fac.png)
options  章节
![image](https://cloud.githubusercontent.com/assets/6229206/20460470/6dbae9a6-af1e-11e6-99b5-2e03892235b7.png)

**Comment by backyes** [comment]
@wen-bo-yang 
的意见我觉得是对的。不过可以把意见并到到这次统一的文档修改行动中去，不需要单独提PR了。

**Comment by reyoung** [comment]
V0.10.0解决
