### ISSUE TITLE
在CMAKE下generate时候出错

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#5371]
提示信息：

CMake Error at cmake/generic.cmake:189 (add_dependencies):
  The dependency target "activation_functions" of target "lstm_compute" does
  not exist.
Call Stack (most recent call first):
  paddle/operators/math/CMakeLists.txt:24 (cc_library)

**Comment by luotao1** [comment]
1. 可以使用最新的develop分支编译。
2. 如果出现这种情况，可以试试删掉整个build目录，重新再编译过。

**Comment by sandycs** [comment]
这两者都已经试验过了
没有用。问题仍然存在。不过我现在放弃了。还是用docker
docker两天时间了。编译都没编过

**Comment by luotao1** [comment]
你是在mac还是linux上编译的？
