### ISSUE TITLE
运行程序时显示atch_norm2d_0.w_0文件无法打开

### ISSUE THREAD

**Issue by weiboaas** [PaddlePaddle/Paddle#53724]
RuntimeError: (Unavailable) Load operator fail to open file /batch_norm2d_0.w_0, please check whether the model file is complete or damaged.
  [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at ..\paddle/fluid/operators/load_op.cc:41)
  [operator < load > error]

**Comment by GhostScreaming** [comment]
你好，先check一下/batch_norm2d_0.w_0这个文件是否存在或者损坏？
