### ISSUE TITLE
paddle.nan_to_num缺少API中文文档

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#53755]
### 文档链接&描述 Document Links & Description

paddle.nan_to_num没有API中文文档，文档缺失

**Comment by YanhuiDua** [comment]
你好，可以参考下develop版本的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nan_to_num_cn.html#nan-to-num
