### ISSUE TITLE
ValueError 报错不清楚

### ISSUE THREAD

**Issue by GSHZhang** [PaddlePaddle/Paddle#53763]
### 问题描述 Please describe your issue

ValueError: (InvalidArgument) Required tensor shall not be nullptr, but received nullptr.
  [Hint: tensor should not be null.] (at /paddle/paddle/phi/core/device_context.cc:100)
网络完整训练没问题，当固定网络部分参数，训练出现如下报错，无法定位

**Comment by YanhuiDua** [comment]
你好，可以打开GLOG_v=10，看下log挂在什么kernel来定位
