### ISSUE TITLE
NCCL库不应该只检查系统默认路径

### ISSUE THREAD

**Issue by Meiyim** [PaddlePaddle/Paddle#53784]
### bug描述 Describe the Bug

目前对NCCL版本的[这一处检查](https://github.com/PaddlePaddle/Paddle/blob/b75d8c7ec535bb26d0d40ad56336d70e53452453/python/paddle/distributed/utils/nccl_utils.py#L21)只考虑了/usr/lib下的nccl库，在非标准路径安装nccl会导致检查失败。

应该直接调用`paddle.fluid.core.nccl_version()`检查运行时链接的NCCL版本。

**Comment by zhwesky2010** [comment]
@Meiyim 你好，这个问题会由 @haohongxiang 进行修复
