### ISSUE TITLE
`paddle.linalg.pinv` returns `nan` if the input matrix has the same value at all indices

### ISSUE THREAD

**Issue by hmahmood24** [PaddlePaddle/Paddle#53786]
### bug描述 Describe the Bug

The `paddle.linalg.pinv` returns `nan`(s) in the output matrix if the input matrix has the same value at all indices, which is not an expected behavior and can be cross-verified with results from `numpy.linalg.pinv` and other similar frameworks.

Minimum reproducible code:

```python
import paddle
import numpy as np

x = np.array([[1.01, 1.01], [1.01, 1.01]], dtype="float32")

print(paddle.linalg.pinv(paddle.to_tensor(x, dtype="float32")))  # [[nan, nan], [nan, nan]]

print(np.linalg.pinv(x))  # [[0.24752475 0.24752475], [0.24752475 0.24752475]]

```

Output:
```python
Tensor(shape=[2, 2], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[nan, nan],
        [nan, nan]])
[[0.24752475 0.24752475]
 [0.24752475 0.24752475]]
```

### 其他补充信息 Additional Supplementary Information

PaddlePaddle version: `2.4.2` installed via pip
NumPy version: `1.24.2` installed via pip
Python version: `3.10.4`
OS: `Ubuntu 20.04.6 LT`
Machine: `Github Codespaces`

**Comment by zhwesky2010** [comment]
@hmahmood24 这是一个API bug，我们将会修复这个问题。
