### ISSUE TITLE
model.to报错

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#53792]
### bug描述 Describe the Bug

```
import paddle
model = paddle.nn.LSTM(16, 32)
model.to(dtype='float64') # 无论是 cpu 还是 gpu 都会报错
```
报错：
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1990, in to
    return self._to_impl(
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2139, in _to_impl
    self._apply(transform, device, dtype, blocking, include_sublayers)
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2016, in _apply
    self._buffers[key] = func(buf, device, dtype, blocking)
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2135, in transform
    return self._transform(t, device, dtype, blocking)
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2056, in _transform
    t_casted = t_used.cast(dtype=dtype)
  File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 186, in cast
    return _C_ops.cast(x, dtype)
RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 1, memory's size is 0.
  [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):1 > memory_size():0.] (at /data/application/zhangrb/paddlepaddle-swai/Paddle/paddle/phi/core/dense_tensor_impl.cc:54)

```
related: https://github.com/PaddlePaddle/Paddle/issues/43192

**Comment by qili93** [comment]
您好，请提供更多的Paddle版本信息来方便定位，包括

1. 飞桨的容器的环境和对应的镜像
2. Paddle的版本信息如 commit id 等，可通过 paddle.version.show() 接口获取

**Comment by qili93** [comment]
此问题可能和 https://github.com/PaddlePaddle/Paddle/pull/43277 是同一个问题导致的，建议等这个PR合入之后试一下飞桨develop分支的最新版本试试看。

**Comment by joey12300** [comment]
> ### bug描述 Describe the Bug
> ```
> import paddle
> model = paddle.nn.LSTM(16, 32)
> model.to(dtype='float64') # 无论是 cpu 还是 gpu 都会报错
> ```
> 
> 报错：
> 
> ```
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 1990, in to
>     return self._to_impl(
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2139, in _to_impl
>     self._apply(transform, device, dtype, blocking, include_sublayers)
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2016, in _apply
>     self._buffers[key] = func(buf, device, dtype, blocking)
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2135, in transform
>     return self._transform(t, device, dtype, blocking)
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/nn/layer/layers.py", line 2056, in _transform
>     t_casted = t_used.cast(dtype=dtype)
>   File "/data/application/songjc/anaconda3/envs/paddle_dev/lib/python3.8/site-packages/paddle/tensor/manipulation.py", line 186, in cast
>     return _C_ops.cast(x, dtype)
> RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 1, memory's size is 0.
>   [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):1 > memory_size():0.] (at /data/application/zhangrb/paddlepaddle-swai/Paddle/paddle/phi/core/dense_tensor_impl.cc:54)
> ```
> 
> related: #43192
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

@tiandou-tangdou 你好，目前修复代码正在推进合入中，现在的解决方案是可以先运行一次model前向，再进行to操作，如：

```python
import paddle
x = paddle.randn((1, 1, 16))
model = paddle.nn.LSTM(16, 32)
model(x)
model.to(dtype='float64')
```

**Comment by tiandou-tangdou** [comment]
@qili93 @joey12300 嗯，感谢，之前已基于 related: https://github.com/PaddlePaddle/Paddle/issues/43192 做了尝试，可以解决
