### ISSUE TITLE
CI 任务 No space left on device

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#53819]
### bug描述 Describe the Bug

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8424818/job/22740632

![图片](https://github.com/PaddlePaddle/Paddle/assets/4617245/04c7eefc-b50b-4100-a3d9-9aac9a3b6d39)

**Comment by ghostxsl** [comment]
可以重新构建一下CI试试呢
