### ISSUE TITLE
Why doesn't paddle.seed() reset the program.random_seed?

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#53813]
### bug描述 Describe the Bug

I just found that **_dropout_**'s seed is always 0 (from main_program.random_seed) instead of the seed I set with paddle.seed(42).
If users set paddle.seed(42), they expect all random seeds in Paddle side (including program.random_seed) can be set to 42. But the fact is that they need extra code to set program.random_seed=42. 

Why is Paddle's seed designed this way? 
Would it make more sense to set the default value of program.random_seed as paddle.seed() when users create the program?

**Comment by jeng1220** [comment]
等王凱再指派人力調研
