### ISSUE TITLE
无法识别到多张gpu

### ISSUE THREAD

**Issue by ericosmic** [PaddlePaddle/Paddle#53812]
### bug描述 Describe the Bug

使用paddle-gpu2.3.2 只能识别到第一张gpu，其他gpu没有被识别到。
服务器上共有3张显卡
![image](https://github.com/PaddlePaddle/Paddle/assets/35327931/ae306c51-c059-4182-aaea-e81bec8ba307)
但paddle只能识别到第一张gpu
![image](https://github.com/PaddlePaddle/Paddle/assets/35327931/2d104711-ab11-483c-9d56-ecb0c00f7241)

### 其他补充信息 Additional Supplementary Information
使用export CUDA_VISIBLE_DEVICE=0,1,2 ,也无法解决
_No response_

**Comment by ghostxsl** [comment]
建议看下官方文档的说明：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/get_device_cn.html#get-device

**Comment by ericosmic** [comment]
@ghostxsl  我使用官方程序进行多卡训练时就会报错没有gpu:1 ，说明程序找不到第二张gpu， 那这是需要设置全局设备吗？

**Comment by ericosmic** [comment]
@ghostxsl  我使用下面的命令进行多卡训练，也会报错没有找的gpu1
`python3 -m paddle.distributed.launch --gpus '0,1' tools/train.py -c configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=ppocr_models/pretrain/ch_PP-OCRv3_rec_train/best_accuracy`
那这该怎么解决，需要设置全局设备？

**Comment by ghostxsl** [comment]
建议可以试一下paddle官方发布的docker
