### ISSUE TITLE
Docker镜像使用gpu问题。

### ISSUE THREAD

**Issue by wfs420100** [PaddlePaddle/Paddle#53821]
### 请提出你的问题 Please ask your question

您好，我写了一个基于nvidia/cuda:11.7.0-cudnn8-devel-ubuntu22.04镜像的dockerfile文件，在创建出来的容器内进行paddlepaddle安装（python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html）。。Dockerfile文件内容如下：
[Dockerfile](https://github.com/PaddlePaddle/Paddle/files/11476752/Dockerfile.txt)

进行验证  import paddle   paddle.utils.run_check()  时打印日志如下提示信息：![image](https://github.com/PaddlePaddle/Paddle/assets/64070362/6a6fefde-c404-4fdc-870f-f554cda9e5f5)

能否解答一下是什么情况？

**Comment by ghostxsl** [comment]
可能是该镜像没有配置好，你换个镜像试试呢

**Comment by wfs420100** [comment]
> 可能是该镜像没有配置好，你换个镜像试试呢

使用镜像 nvidia/cuda:11.7.0-cudnn8-devel-ubuntu20.04，具有同样的问题。

使用nvidia/cuda:11.7.0-cudnn8-devel-ubuntu22.04的镜像，pytorch框架下是正常的

**Comment by ghostxsl** [comment]
有可能是paddle的环境依赖没有配置好，建议你使用下paddle官方的镜像～

**Comment by wfs420100** [comment]
> 有可能是paddle的环境依赖没有配置好，建议你使用下paddle官方的镜像～

您好，在进行  "import paddle   paddle.utils.run_check()"  验证安装是否成功时，打印出"Cannot enable P2P access from 0 to 1"，会有什么影响吗？
![image](https://github.com/PaddlePaddle/Paddle/assets/64070362/8352212b-d569-4d56-ae9f-ae3ca49beb18)

**Comment by msbrm** [comment]
docker pull paddlepaddle/paddle:latest-dev-cuda12.0-cudnn8.9-trt8.6-gcc12.2 这个是官方的镜像吗
默认python环境 没有paddle 这么离谱吗 还是我打开方式不对
