### ISSUE TITLE
paddle 目标检测的模型转ascend om模型的时候 scale_factor该如何设置呢

### ISSUE THREAD

**Issue by Viserion-nlper** [PaddlePaddle/Paddle#53833]
### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/PaddleDetection/blob/e6324fd544175a3787b28a31c87da5a9ae03a018/ppdet/engine/trainer.py#L63
参考这个项目训练的代码
转换成onnx 后转换成om时，需要传入两个参数，第一个image，第二个scale_fartor ，不太清楚第二个参数的输入设置是什么。
请帮忙解答下，谢谢、

**Comment by nemonameless** [comment]
scale_factor是数据增强变换后的输入图和真实原图的尺度的比例，比如YOLO网络模型输入尺度是640x640，而原图可能是800x400，就需要图片连同gt标注框一起resize到640x640，记录scale_factor是为了将640尺度上得到的坐标映射回原图尺度上。
自己另写一套获取 可以参考 https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/python/preprocess.py
搜关键字 scale_factor 找相关代码

**Comment by Viserion-nlper** [comment]
可是在转到om模型的时候需要用到该参数，请问这个参数本身是一个动态的，在转换om模型的时候该怎么办呢？
om模型是华为npu支持的模型格式
![image](https://github.com/PaddlePaddle/Paddle/assets/48983651/8e067be6-fe51-43fc-aeed-7d55c7234b19)

**Comment by nemonameless** [comment]
只要获取原图的h w，再和你设定的尺度比如640x640去求比例就计算出来了scale_factor
