### ISSUE TITLE
如何实现tensor列表索引功能，或者实现类似torch的gather功能

### ISSUE THREAD

**Issue by CfromBU** [PaddlePaddle/Paddle#53834]
### 需求描述 Feature Description

我现在正在构造一个nlp模型，现在有一个tensor的shape=(32,128,10)，现在我想要在提取axis=1中特定的某个张量组成一个shape=（32,10）的新张量，即分别提取tensor[0,12,:],tensor[1,18,:],tensor[2,99,:],tensor[4,56,:].....组成一个新张量。在我使用pytorch时，可以使用tensor[range(32),list,:](list为每一行要提取的数据索引)或者使用torch.gather函数实现，但是在paddle中gather函数不能实现这个操作。
如：
```
input = [
    [2, 3, 4, 5, 0, 0],
    [1, 4, 3, 0, 0, 0],
    [4, 2, 2, 5, 7, 0],
    [1, 0, 0, 0, 0, 0]
]
input = paddle.to_tensor(input)
length = paddle.to_tensor([1,2,3,4])
out = paddle.gather(input, axis=1, index=length)
```
我希望得到的是
`[3,3,5,0]`
但是实际输出的是
```
[[1, 4, 3, 0, 0, 0],
        [4, 2, 2, 5, 7, 0],
        [1, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0]]
```

**Comment by Asthestarsfalll** [comment]
可以尝试使用[gather_nd](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/gather_nd_cn.html#gather-nd)：
```python
import paddle

inp = paddle.randn((32, 128, 10))
index1 = paddle.to_tensor([12, 18, 99, 56])
index2 = paddle.arange(0, 4)
index = paddle.stack([index2, index1], axis=1)

out = paddle.gather_nd(inp, index)
print(out.shape)

```

**Comment by CfromBU** [comment]
> 可以尝试使用[gather_nd](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/gather_nd_cn.html#gather-nd)：
> 
> ```python
> import paddle
> 
> inp = paddle.randn((32, 128, 10))
> index1 = paddle.to_tensor([12, 18, 99, 56])
> index2 = paddle.arange(0, 4)
> index = paddle.stack([index2, index1], axis=1)
> 
> out = paddle.gather_nd(inp, index)
> print(out.shape)
> ```

谢谢大佬，问题解决了。真希望paddlepaddle以后可以把这个功能集成到tensor的索引中啊，这个函数找了好久没有找到。

**Comment by nemonameless** [comment]
https://www.paddlepaddle.org.cn/ 右上角搜 gather 会出来相关的，可以逐个看看
