### ISSUE TITLE
float point exception

### ISSUE THREAD

**Issue by BroJackfeely** [PaddlePaddle/Paddle#5385]
利用paddle复现baidu在youtube-8M数据集下的two-stream-lstm模型，
dataprovider中将tfrecord转换成numpy格式，然后yield (out_rgb_feature, out_audio_feature, [label])

但在训练一开始即报错float point exception，但没有具体信息，报错如下：
“
*** Aborted at 1509931935 (unix time) try "date -d @1509931935" if you are using GNU date ***
PC: @     0x7f225f362ee2 longdouble_multiply
*** SIGFPE (@0x7f225f362ee2) received by PID 266 (TID 0x7f22bff03780) from PID 1597386466; stack trace: ***
    @     0x7f22bf7e3330 (unknown)
    @     0x7f225f362ee2 longdouble_multiply
    @     0x7f22becad79d (unknown)
    @     0x7f22bed2d93a (unknown)
    @     0x7f22bed31c3d (unknown)
    @     0x7f22bed31f22 (unknown)
    @     0x7f22bed3277c (unknown)
    @     0x7f22bed95ef6 (unknown)
    @     0x7f22bed96609 (unknown)
    @     0x7f22bec9647f (unknown)
    @     0x7f22bed8fa46 (unknown)
    @     0x7f22bed6385f (unknown)
    @     0x7f22bed060a3 (unknown)
    @     0x7f22bed995f7 (unknown)
    @     0x7f22bed2d6d3 (unknown)
    @     0x7f22bed31c3d (unknown)
    @     0x7f22bed31f22 (unknown)
    @     0x7f22bed3277c (unknown)
    @     0x7f22bed95ef6 (unknown)
    @     0x7f22bedc79a9 (unknown)
    @     0x7f22bed96609 (unknown)
    @     0x7f22bed8f882 (unknown)
    @     0x7f22bed6385f (unknown)
    @     0x7f22bed060a3 (unknown)
    @     0x7f22bed995f7 (unknown)
    @     0x7f22bed2d6d3 (unknown)
    @     0x7f22bed31c3d (unknown)
    @     0x7f22bed31f22 (unknown)
    @     0x7f22bed3277c (unknown)
    @     0x7f22bed95ef6 (unknown)
    @     0x7f22bed96609 (unknown)
    @     0x7f22bed8f7c3 (unknown)
/usr/local/bin/paddle: line 109:   266 Floating point exception${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
”
请问如何解决这个bug？ 且如何查看network configuration具体哪一行出现FPE？

**Comment by luotao1** [comment]
你是用v1还是v2，训练的命令是什么？打印出来的所有日志就是上面贴的么？

**Comment by BroJackfeely** [comment]
谢谢您的回复！

用的paddle版本是dockerhub里的paddledev/paddle:cpu-release-v0.9.0， 训练的命令如下：

cfg=broj_paddle_twoStream_lstm.py
paddle train \
    --config=$cfg \
    --save_dir=./models \
    --trainer_count=4 \
    --log_period=20 \
    --num_passes=1 \
    --use_gpu=false \
    --test_period=0 \
    --show_parameter_stats_period=100

上面打印的是全部日志，没有其他信息。

**Comment by luotao1** [comment]
您使用的版本太老了。可以使用paddlepaddle/paddle:latest下的。
另外，yield的数据格式请自行检查下，http://doc.paddlepaddle.org/develop/doc_cn/getstarted/concepts/use_concepts_cn.html

**Comment by BroJackfeely** [comment]
由于是在复现baidu在Youtube-8M数据集上的工作，具体信息在https://github.com/baidu/Youtube-8M中, 所以使用了0.9.0的版本

yield的数据如下，
rgb_features = [ [rgb1], [rgb2], [rgb3], ......., [rgb300] ], 其中rgb_i是1024x1维的float型向量
audio_features = [ [audio1], [audio2], ......, [audio300] ], 其中audio_i是128x1维的float型向量
label = [label]， label是一个4716x1维int型向量

在data_provider中定义input_types如下：
 settings.input_types = {'rgb_feature':   dense_vector(1024,      
                                                               seq_type=SequenceType.SEQUENCE),
                                      'audio_feature': dense_vector(128,     
                                                                seq_type=SequenceType.SEQUENCE),
                                      'label':         sparse_binary_vector(4716, 
                                                         seq_type=SequenceType.NO_SEQUENCE)}

**Comment by luotao1** [comment]
1. 建议您也可以在 https://github.com/baidu/Youtube-8M 提issue，咨询下作者？
2. 直接按照那个Youtube-8M的README跑是正确的么？

**Comment by BroJackfeely** [comment]
再次感谢您的耐心解答。

1. 已经在/baidu/Youtube-8M下提了issue，但是没有收到回复

2. 问题在于Youtube-8M这个respo里提供的dataprovider代码是直接load的Pickle格式的数据，但respo中并没有提供将tfrecord转成pickle格式的代码，所以我不知道从tfrecord转为pickle格式之间有没有什么其他的操作，所以并不知道如何按Youtube-8M中的README来跑通这个网络。
p.s. 对input_types的各数据维度和seq_type的定义，参考paddle的doc，我也不是很确定我写的是否正确。

**Comment by luotao1** [comment]
请问您是厂内员工么？如果是厂内员工，可以帮您联系作者。

**Comment by BroJackfeely** [comment]
您好，我不是厂内员工，目前是上海交大在校生，希望可以使用paddle复现您司在Youtube-8M数据集上的Classification工作，paddle目前的社区支持和技术文档还在起步阶段，所以也希望能和您那边多一些直接沟通，也能更好的推广paddle。

**Comment by luotao1** [comment]
@CrossLee1 您能来看下这个问题么？

**Comment by BroJackfeely** [comment]
问题已全部解决，非常感谢您的耐心解答和鼎力帮助！

**Comment by luotao1** [comment]
已经在 https://github.com/baidu/Youtube-8M/issues/1 解决了！

**Comment by luotao1** [comment]
@BroJackfeely 感谢您对PaddlePaddle的支持，我们将于本周四下午1:30在上海举行【百度AI开发者实战营】，其中有【PaddlePaddle加速AI落地与workshop】环节，非常期待您的参加！报名地址：http://ai.baidu.com/event/createwithai

**Comment by babiking** [comment]
收到，感谢通知！已报名。

**Comment by BroJackfeely** [comment]
收到，感谢通知！已报名。

**Comment by luotao1** [comment]
期待周四下午与您的见面，可以来PaddlePaddle展台找我们。

**Comment by luotao1** [comment]
周四下午听说你在展台等了我们很久，抱歉由于会场比较乱，没有在展台见到你。关于实习，欢迎发简历到paddle-dev@baidu.com，北京/上海均可以。邮件中请注明您的github账号。

**Comment by BroJackfeely** [comment]
当时听完PaddlePaddle的workshop想和您沟通交流一下。
收到，谢谢您！：）
