### ISSUE TITLE
黑客松第四期任务评审细则

### ISSUE THREAD

**Issue by Ligoml** [PaddlePaddle/Paddle#53853]
大家好，第四期 [PaddlePaddle Hackathon](https://www.paddlepaddle.org.cn/PaddlePaddleHackathon-2023-2?fr=paddleg) 接近尾声，依据活动规则，其中有部分任务需要通过答辩评审的方式选出最佳作品、完成奖金发放。本细则用于汇总各任务的具体情况，及答辩评审规则。

本期黑客松共计四大赛道：[赛道一：核心框架开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlepaddle)、[赛道二：模型套件开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlefamily)、[赛道三：生态伙伴开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlefriend)、[赛道四：产业合作开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddleindustry)，其中赛道一、二、四均有任务需要参与答辩，包括赛道一的开源社区洞察、赛道二的 PaddleNLP 任务和赛道四的全部任务，请完成提交作品的团队注意群内通知，准备材料参与答辩评审。

## 时间安排

- 5.15-19 在社区发布答辩通知与评审规则
- 5.22 黑客松作品提交截止
- 5.23-25 启动评审
- 5.26 结果公示

## 待评审作品公示

| **所属赛道**                                                 | **任务说明**                                                 | **任务难度** | **提交情况**                                                 |
| ------------------------------------------------------------ | ------------------------------------------------------------ | ------------ | ------------------------------------------------------------ |
| [赛道一：核心框架开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlepaddle) | [【开源贡献对比研究】以 CI 流水线为例](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E6%B4%9E%E5%AF%9F%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task85) | ⭐️            | 花花又偷懒了([community#498](https://github.com/PaddlePaddle/community/pull/498)) |
| [赛道一：核心框架开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlepaddle) | [【开源贡献对比研究】以贡献文档为例](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E6%B4%9E%E5%AF%9F%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task86) | ⭐️            | 梦师傅的猫([community#420](https://github.com/PaddlePaddle/community/pull/420)) |
| [赛道一：核心框架开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlepaddle) | [【开源贡献对比研究】以代码组织为例](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E6%B4%9E%E5%AF%9F%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task87) | ⭐️            | -                                                            |
| [赛道一：核心框架开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlepaddle) | [飞桨框架API文档发布的工具链的分析](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E6%B4%9E%E5%AF%9F%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task88) | ⭐️⭐️           | -                                                            |
| [赛道二：模型套件开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddlefamily) | [基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型](https://github.com/PaddlePaddle/PaddleNLP/issues/4775) | ⭐️            | 大江向东我向西画画队-美食、中国美食、顶尖美食([5695749](https://aistudio.baidu.com/aistudio/projectdetail/5695749))</br>AI爱画画-流浪地球中的巨型行星发动机([5696904](https://aistudio.baidu.com/aistudio/projectdetail/5696904))</br>活宝-隔空将你的狗狗放进桶里([5704542](https://aistudio.baidu.com/aistudio/projectdetail/5704542))</br>together-This is my hometown([5682527](https://aistudio.baidu.com/aistudio/projectdetail/5682527))</br>LPC-Jedi Teddy: Rebuilding the Order of the Jedi, Fallen But Not Forgotten.([5797270](https://aistudio.baidu.com/aistudio/projectdetail/5797270))</br>炼丹师-饿了？整点薯条([5817401](https://aistudio.baidu.com/aistudio/projectdetail/5817401))</br>不想画图-生成独一无二的玫瑰花([5876560](https://aistudio.baidu.com/aistudio/projectdetail/5876560))</br>I_B_M-钢铁侠与蝙蝠侠的复合体([5823506](https://aistudio.baidu.com/aistudio/projectdetail/5823506))</br>花开富贵-史前巨兽将以高达形态出击！！！机甲风炫酷恐龙一枚~~([5932453](https://aistudio.baidu.com/aistudio/projectdetail/5932453))</br>一根外向的腿毛-通过'Neolle with xxxx'的语句生成原神角色诺艾尔的图片([5912535](https://aistudio.baidu.com/aistudio/projectdetail/5912535))</br>易八鸽铁匠铺-剑，出自易八鸽铁匠铺。([5906465](https://aistudio.baidu.com/aistudio/projectdetail/5906465))</br>megemini-当中国水墨山水遇上AIGC([6103948](https://aistudio.baidu.com/aistudio/projectdetail/6103948))</br>Mortal-万物皆可coding([6065063](https://aistudio.baidu.com/aistudio/projectdetail/6065063))</br>摸鱼-利用皮卡丘生成动漫皮卡新造型([5680388](https://aistudio.baidu.com/aistudio/projectdetail/5680388))</br>thunder95-用 LoRA 和 DreamBooth 创作出奥特曼的舞姿([6176091](https://aistudio.baidu.com/aistudio/projectdetail/6176091)) |
| [赛道四：产业合作开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddleindustry) | [基于PaddleOCR的工频场强计读数识别](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E4%BA%A7%E4%B8%9A%E5%90%88%E4%BD%9C%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task236) | ⭐️            | megemini([6044433](https://aistudio.baidu.com/aistudio/projectdetail/6044433)) </br>电工弃徒([6161867](https://aistudio.baidu.com/aistudio/projectdetail/6161867))</br>还没睡觉的一根腿毛(提交作品)([5852670](https://aistudio.baidu.com/aistudio/projectdetail/5852670)) |
| [赛道四：产业合作开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddleindustry) | [基于PaddleNLP的跨模态文档信息抽取](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E4%BA%A7%E4%B8%9A%E5%90%88%E4%BD%9C%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task237) | ⭐️            | cnrk([5958649](https://aistudio.baidu.com/aistudio/projectdetail/5958649)) |
| [赛道四：产业合作开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddleindustry) | [基于PaddleClas的中草药识别](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E4%BA%A7%E4%B8%9A%E5%90%88%E4%BD%9C%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task238) | ⭐️            | 梦境爱丽丝([5554057](https://aistudio.baidu.com/aistudio/projectdetail/5554057)) </br>开始好好工作([5676228](https://aistudio.baidu.com/aistudio/projectdetail/5676228)) </br>唯心而已([5634822](https://aistudio.baidu.com/aistudio/projectdetail/5634822)) </br>决战紫禁城([5915109](https://aistudio.baidu.com/aistudio/projectdetail/5915109)) |
| [赛道四：产业合作开源贡献](https://github.com/PaddlePaddle/Paddle/issues/51281#paddleindustry) | [基于PaddleDetection的无人机航拍图像检测](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E4%BA%A7%E4%B8%9A%E5%90%88%E4%BD%9C%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task239) | ⭐️            | yao-yu([5704345](https://aistudio.baidu.com/aistudio/projectdetail/5704345)) </br>NONAME([5582072](https://aistudio.baidu.com/aistudio/projectdetail/6164618))</br>求大佬带带([6071556](https://aistudio.baidu.com/aistudio/projectdetail/6071556)) |

### 赛道一：核心框架开源贡献 - 开源社区洞察

答辩时间为 10 分钟（含 8 分钟陈述与 2 分钟提问），5 位评委打分取平均值，满分 100 分，60 分为及格线（基本符合任务要求，可以获奖），80 分以上可获得完整奖励，80 分以下酌情扣除部分奖金。

**评估维度：**

- 任务完成度（满分 50）：依据任务要求，完成指定内容，如[【开源贡献对比研究】以 CI 流水线为例](https://github.com/PaddlePaddle/community/blob/master/hackthon_4th/%E3%80%90PaddlePaddle%20Hackathon%204%E3%80%91%20%E6%A0%B8%E5%BF%83%E6%A1%86%E6%9E%B6%E5%BC%80%E6%BA%90%E8%B4%A1%E7%8C%AE%E5%BC%80%E6%BA%90%E7%A4%BE%E5%8C%BA%E6%B4%9E%E5%AF%9F%E4%BB%BB%E5%8A%A1%E5%90%88%E9%9B%86.md#task85) 中，要求 1.针对开源贡献当中涉及到的因素和流程做出概要分析；2. 与其他开源项目对比，就飞桨框架的 CI 流水线的使用体验、自动化程度、对项目的保护情况等等方面（不限于前述三个方面）给出有论据支撑的分析结论。因此，报告中需要同时包含 1 和 2 的内容，且重点落在飞桨框架的 CI 流水线，给出有效的分析结论。
- 结论准确度（满分 40）：报告给出的结论需要符合客观事实，不可主观臆造或过度推断。
- 亮点结论（满分 10）：结论中包含高价值内容，可以对飞桨核心框架有指导意义或参考价值。

### 赛道二：模型套件开源贡献 - 基于PaddleNLP PPDiffusers 训练 AIGC 趣味模型

无现场答辩，5 位评委根据项目质量打分取平均值，满分 150 分（含附加分，50 分封顶），根据打分排名，评选出一等奖 1 名（奖金 3k），二等奖 5 名（奖金 1k），三等奖 10 名（面值 200 元京东卡），获奖队伍还可获得 50 美元 HuggingFace store 代金券一张。

**评估维度：**

- 人气加分：AI Studio 项目like数 + Fork数/10 + Hugging Face like数，50 分封顶，统计 5.23 截止。
- 项目完成度（满分 50）：结合 [PPDiffusers](https://github.com/PaddlePaddle/PaddleNLP/tree/develop/ppdiffusers) 最新版本，基于自己的数据集，训练并开源趣味模型。要求项目可运行，可现场展示。
- 项目创意度（满分 20）：项目是否有趣，是否有独特的结合点和新玩法，是否有一定的应用场景或满足娱乐需求。
- 教程成熟度（满分 30）：AIStudio 项目作为教程和精选项目的成熟度，包括结构条理清晰、内容易读易懂易用、带有作者个人风格、易于传播等。

### 赛道四：产业合作开源贡献 - 全部任务

答辩时间为 10 分钟（含 8 分钟陈述与 2 分钟提问），5 位评委打分取平均值，满分 100 分，60 分为及格线（基本符合任务要求，可以获奖），80 分以上可获得完整奖励，80 分以下酌情扣除部分奖金。

**评估维度：**

- 技术完成度（满分 80）
  - 项目完成度（满分 50，任务导师打分）：项目可跑通训练、推理代码，达到任务发布时的指标要求。
  - 技术方案可用性与可扩展性（满分 30）：项目中的技术方案是否可以解决产业问题，是否是最佳方案，是否可以扩展到其他产业应用场景中。
- 产业落地价值和影响（满分 10）：项目方案是否有机会或已经落地到产业中，是否产生了产业或社区影响。
  - NOTE：产业落地价值 > 社区影响，当有项目产生产业落地价值时，只做产业落地价值比较；当均暂无产业影响时，才做社区影响比较。
- 教程成熟度（满分 10）：AIStudio 项目作为教程和精选项目的成熟度，包括结构条理清晰、内容易读易懂易用、带有作者个人风格、易于传播等。

**Comment by dddlli** [comment]
赛道二在哪儿看成绩呀

**Comment by peteli25** [comment]
结果在哪儿公示呢？

**Comment by Ligoml** [comment]
结果详见任务总览：https://github.com/PaddlePaddle/Paddle/issues/51281
黑客松第四期获奖榜单已在飞桨公众号公示
