### ISSUE TITLE
tensor创建一直为0

### ISSUE THREAD

**Issue by Jhonwivk** [PaddlePaddle/Paddle#53858]
### 请提出你的问题 Please ask your question

tensor 值一直为0
![image](https://github.com/PaddlePaddle/Paddle/assets/38974254/e1374bb5-0687-419e-9702-7270bae24cfb)

**Comment by nemonameless** [comment]
你好，这个问题可能是因为paddle安装的版本和cuda没有适配，建议安装对应版本再试试，以及python版本也降一下试试。

**Comment by nemonameless** [comment]
你好，请重装下paddle对应版本试试。如有问题可再开启。

**Comment by Jhonwivk** [comment]
> 你好，请重装下paddle对应版本试试。如有问题可再开启。

忘记回复了，已通过降低cuda和python版本解决。
