### ISSUE TITLE
使用fit的时候不打印每个epoch的信息

### ISSUE THREAD

**Issue by GitAlice123** [PaddlePaddle/Paddle#53867]
### 请提出你的问题 Please ask your question

一开始以为是在CPU上跑的原因，今天改成了GPU版本的paddle，但是还是没有打印出来，verbose也有设置，请问怎么办？

**Comment by nemonameless** [comment]
你好，可以提供下代码实例等链接吗，以及如何使用的？谢谢。可先使用paddle2.4.2等稍低版本。
