### ISSUE TITLE
【PaddlePaddle Hackathon】使用Docker初次编译Paddle出错

### ISSUE THREAD

**Issue by yao-yu1999** [PaddlePaddle/Paddle#53860]
### 问题描述 Issue Description

使用time make -j8命令进行初次编译，但是报了这个错误。
这个错误提示表明在编译 Paddle 时发生了问题，具体是在 imperative.cc 文件的第 2490 行出现了错误。根据错误信息显示，Reducer 不是 paddle::imperative 的成员。这个错误是否是由于PaddlePaddle版本更新导致的API更改所致，已经使用的是最新版本的PaddlePaddle。也有人说是pybind过高的问题，但是我的和python版本是匹配的。
![image](https://github.com/PaddlePaddle/Paddle/assets/81399827/3756c572-b1a8-4cee-8c33-88160e3b1431)
![image](https://github.com/PaddlePaddle/Paddle/assets/81399827/973846f3-697e-4746-bd5b-e81962dea1d5)

### 版本&环境信息 Version & Environment Information

CPU 8核
python：3.7

**Comment by nemonameless** [comment]
你好，这几天可能更新比较频繁，建议可以回退下几次commit前的状态再去试试
https://github.com/PaddlePaddle/Paddle/commits/develop/paddle/fluid/pybind/imperative.cc

**Comment by yao-yu1999** [comment]
> 你好，这几天可能更新比较频繁，建议可以回退下几次commit前的状态再去试试 https://github.com/PaddlePaddle/Paddle/commits/develop/paddle/fluid/pybind/imperative.cc

请问具体怎么回退呢？重新git一下paddle吗？

**Comment by yao-yu1999** [comment]
> > 你好，这几天可能更新比较频繁，建议可以回退下几次commit前的状态再去试试 https://github.com/PaddlePaddle/Paddle/commits/develop/paddle/fluid/pybind/imperative.cc
> 
> 请问具体怎么回退呢？重新git一下paddle吗？



> 你好，这几天可能更新比较频繁，建议可以回退下几次commit前的状态再去试试 https://github.com/PaddlePaddle/Paddle/commits/develop/paddle/fluid/pybind/imperative.cc

请问具体怎么回退呢？重新git一下paddle吗？

**Comment by yao-yu1999** [comment]
> 你好，这几天可能更新比较频繁，建议可以回退下几次commit前的状态再去试试 https://github.com/PaddlePaddle/Paddle/commits/develop/paddle/fluid/pybind/imperative.cc

请问具体怎么回退呢？重新git一下paddle吗？
