### ISSUE TITLE
用docker编译报错：cannot dectect VCS 

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#5387]
已经连续编译了3次了。每次都在不同的地方报错
快要崩溃了
目前编译进度走的最远的是18

本次错误内容卡在：
[WARN]  Unable to checkout golang.org/x/net
[ERROR] Update failed for golang.org/x/net: Cannot detect VCS
[WARN]  Unable to checkout google.golang.org/grpc
[ERROR] Update failed for google.golang.org/grpc: Cannot detect VCS

**Comment by sandycs** [comment]
这次出来个新问题：
CMake Error: Cannot open file for write: /paddle/build/compile_commands.json.tmp
CMake Error: : System Error: No such file or directory

**Comment by sandycs** [comment]
把build目录删除后，重新build
这次是：
CMake Error at cmake/generic.cmake:189 (add_dependencies):
  The dependency target "activation_functions" of target "lstm_compute" does
  not exist.
Call Stack (most recent call first):
  paddle/operators/math/CMakeLists.txt:24 (cc_library)

**Comment by sandycs** [comment]
对了：我用master和develop分支都试过了。。。

**Comment by gongweibao** [comment]
检查一下是否被我们伟大的墙保护了？

**Comment by sandycs** [comment]
不是。问题解决了。谢谢

**Comment by luotao1** [comment]
@sandycs 请问可以说下是怎么解决的么，谢谢！

**Comment by sandycs** [comment]
1、把所有目录都清空，重新下载MASTER镜像（DEV镜像亲测不行）
2、把build.sh用SUBLIME将windows的换行改为UNIX的换行
3、翻墙
4、重新编译

**Comment by luotao1** [comment]
> MASTER镜像（DEV镜像亲测不行）

镜像下载 paddlepaddle/paddle:latest的就行了。您下的是什么呢？

> 把build.sh用SUBLIME将windows的换行改为UNIX的换行

换行应该都是linux的，请问您看的build.sh是什么样？

**Comment by sandycs** [comment]
我也不知道。我从来没改过这个文件。如果不是它报错。我根本不知道这个文件的存在。
用SUBLIME改了换行就可以执行了。之前不行
镜像下载我之前是在网页上点CLONE的不是用github
美女您看看我提的另一个问题好吗

我离成功很近了

**Comment by sandycs** [comment]
#5390 现在碰到的是这个问题
