### ISSUE TITLE
teacher_student_sigmoid_loss在GPU上的实现

### ISSUE THREAD

**Issue by napoleonhoo** [PaddlePaddle/Paddle#53884]
### 需求描述 Feature Description

1. 最新的2.4版本上，teacher_student_sigmoid_loss没有在GPU上实现，不知道是否可以添加一下？
2. 另外，请问下，这个loss的梯度计算是怎么确定的？为什么是代码中实现的这个样子的？

**Comment by tink2123** [comment]
请问 `teacher_student_sigmoid_loss` 是在哪里看到的API呢，并没有在官方API中找到这个loss：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/index_cn.html

**Comment by napoleonhoo** [comment]
文档里面确实没有，但是代码里面是有的 https://github.com/PaddlePaddle/Paddle/blob/release/2.4/paddle/fluid/operators/teacher_student_sigmoid_loss_op.h

**Comment by tink2123** [comment]
这个op是很久之前开发的，目前没有人在维护了，请问具体需要什么功能呢？建议看下有哪个公开的API可以替代。
