### ISSUE TITLE
paddle.vision.transforms.resize里面能不能增加antialias选项，增加反锯齿

### ISSUE THREAD

**Issue by starplanet** [PaddlePaddle/Paddle#53895]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 
旋转目标检测，检测旋转角度

需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 
生成旋转图片时，图片边缘出现锯齿状，pytorch的resize可以直接提供antialias选项。

功能描述（请简单描述或设计这个功能）
增加antialias选项，为true时，参考pytorch插值的时候，增加抗锯齿。

**Comment by tink2123** [comment]
已记录您的需求，我们会评估是否更新功能。
