### ISSUE TITLE
使用paddlepaddle在 2个8卡GPU机器上跑 Bert训练，GPU报999错误

### ISSUE THREAD

**Issue by BiduCui** [PaddlePaddle/Paddle#53906]
### 请提出你的问题 Please ask your question

环境信息：2台A800 8卡机器，每台机器具备8张GPU和8张RDMA网卡，1张CPU网卡

出错信息：
----------------------
Error Message Summary:
----------------------
ExternalError: CUDA error(999), unknown error.
  [Hint: Please search for the error code(999) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /workspace/Paddle_src/Paddle/paddle/phi/core/cuda_stream.h:73)

Traceback (most recent call last):
  File "run_pretrain.py", line 1267, in <module>
    do_train(args)
  File "run_pretrain.py", line 957, in do_train
    exe.run(startup_program)
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1461, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.8/site-packages/six.py", line 719, in reraise
    raise value
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1448, in run
    res = self._run_impl(program=program,
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1711, in _run_impl
    return self._run_program(program,
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/executor.py", line 1805, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
OSError:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string > > const&, bool, bool)
1   paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
2   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
3   paddle::framework::UnsafeFastGPUGarbageCollector::UnsafeFastGPUGarbageCollector(phi::GPUPlace const&, unsigned long)
4   paddle::framework::GarbageCollector::GarbageCollector(phi::Place const&, unsigned long)
5   paddle::platform::DeviceContextPool::Get(phi::Place const&)
6   std::__future_base::_Deferred_state<std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >::_M_complete_async()
7   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
8   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > >, std::__future_base::_Result_base::_Deleter>, std::thread::_Invoker<std::tuple<std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > (*)(phi::Place const&, bool), phi::Place, bool> >, std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > > >::_M_invoke(std::_Any_data const&)
9   std::unique_ptr<phi::DeviceContext, std::default_delete<phi::DeviceContext> > paddle::platform::CreateDeviceContext<phi::GPUContext>(phi::Place const&, bool)
10  phi::GPUContext::GPUContext(phi::GPUPlace const&, bool)
11  phi::CUDAStream::CUDAStream(phi::Place const&, phi::CUDAStream::Priority const&, phi::CUDAStream::StreamFlag const&)
12  phi::enforce::EnforceNotMet::EnforceNotMet(phi::ErrorSummary const&, char const*, int)
13  phi::enforce::GetCurrentTraceBackString[abi:cxx11](bool)

----------------------
Error Message Summary:
----------------------
ExternalError: CUDA error(999), unknown error.
  [Hint: Please search for the error code(999) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /workspace/Paddle_src/Paddle/paddle/phi/core/cuda_stream.h:73)

server not ready, wait 3 sec to retry...
not ready endpoints:['10.174.148.80:60000', '10.174.148.80:60001', '10.174.148.80:60002', '10.174.148.80:60003', '10.174.148.80:60004', '10.174.148.80:60005', '10.174.148.80:60006', '10.174.148.80:60007']
server not ready, wait 3 sec to retry...
not ready endpoints:['10.174.148.80:60000', '10.174.148.80:60001', '10.174.148.80:60002', '10.174.148.80:60003', '10.174.148.80:60004', '10.174.148.80:60005', '10.174.148.80:60006', '10.174.148.80:60007']
^C

**Comment by yangy996** [comment]
请问你在多开的A800上可以跑单机多卡的服务吗？我的单机单卡没问题，单机多卡数据读取后就不动了

**Comment by BiduCui** [comment]
> 请问你在多开的A800上可以跑单机多卡的服务吗？我的单机单卡没问题，单机多卡数据读取后就不动了

可以的。

**Comment by yangy996** [comment]
我输入nvidia-smi命令是这样的
![Uploading Z@M]SXSI8X}0P75JY%[`T67.png…]()

**Comment by BiduCui** [comment]
> 我输入nvidia-smi命令是这样的 ![Uploading Z@M]SXSI8X}0P75JY%`T67.png…

你这图片根本看不到。
