### ISSUE TITLE
[CustomDevice] buffered_reader中SetDevice提前,否則mutable_data异常

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#53921]
### bug描述 Describe the Bug

请问3处的SetDevice是否可以提前到1处，否则2处mutable_data异常
![image](https://github.com/PaddlePaddle/Paddle/assets/127805199/b608425e-9c0c-45ae-a274-f9b588e4be91)

### 其他补充信息 Additional Supplementary Information

期望合入paddlepaddle2.5.0发版

**Comment by ronny1996** [comment]
你好，我们提个PR修一下

**Comment by ronny1996** [comment]
你好，该问题已修复，https://github.com/PaddlePaddle/Paddle/pull/53925
