### ISSUE TITLE
华为云的鲲鹏arm服务器，编译PaddlePaddle到一半报错：

### ISSUE THREAD

**Issue by 18018031559** [PaddlePaddle/Paddle#53932]
### bug描述 Describe the Bug

[ 83%] Linking CXX static library librenorm_op.a
[ 83%] Built target renorm_op
Scanning dependencies of target dequeue_op
[ 83%] Linking CXX static library libbce_loss_op.a
[ 83%] Building CXX object paddle/fluid/operators/CMakeFiles/dequeue_op.dir/dequeue_op.cc.o
[ 83%] Built target bce_loss_op
Scanning dependencies of target shard_index_op
[ 83%] Building CXX object paddle/fluid/operators/CMakeFiles/shard_index_op.dir/shard_index_op.cc.o
cc1plus: all warnings being treated as errors
make[2]: *** [paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/build.make:66: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/memcpy_h2d_op.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:80372: paddle/fluid/operators/CMakeFiles/memcpy_h2d_op.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 83%] Linking CXX static library libspace_to_depth_op.a
[ 83%] Built target space_to_depth_op
[ 83%] Linking CXX static library libtriu_indices_op.a
[ 83%] Built target triu_indices_op
[ 83%] Linking CXX static library liblog_softmax_op.a
[ 83%] Built target log_softmax_op
[ 83%] Linking CXX static library liblabel_smooth_op.a
[ 83%] Built target label_smooth_op
[ 83%] Linking CXX static library libunsqueeze_op.a
[ 83%] Built target unsqueeze_op
[ 83%] Linking CXX static library libsample_logits_op.a
[ 83%] Built target sample_logits_op
[ 83%] Linking CXX static library libgaussian_random_batch_size_like_op.a
[ 83%] Built target gaussian_random_batch_size_like_op
[ 83%] Linking CXX static library liblu_unpack_op.a
[ 83%] Built target lu_unpack_op
[ 83%] Linking CXX static library libdequeue_op.a
[ 83%] Built target dequeue_op
[ 83%] Linking CXX static library libshard_index_op.a
[ 83%] Built target shard_index_op
[ 83%] Linking CXX static library libgrid_sampler_op.a
[ 83%] Built target grid_sampler_op
[ 83%] Linking CXX static library libgenerated_op.a
[ 83%] Built target generated_op
[ 83%] Linking CXX static library libpad2d_op.a
[ 83%] Built target pad2d_op
[ 83%] Linking CXX static library libcrop_op.a
[ 83%] Built target crop_op
[ 83%] Linking CXX static library libtdm_sampler_op.a
[ 83%] Built target tdm_sampler_op
make: *** [Makefile:133: all] Error 2

**Comment by minghaoBD** [comment]
CMAKE命令添加-DCMAKE_CXX_FLAGS="-Wno-error -w" 选项

**Comment by 18018031559** [comment]
我试一下，谢谢

**Comment by 18018031559** [comment]
我试一下，谢谢
