### ISSUE TITLE
使用CAPI进行预测, 对应的data provider.py该怎么写?

### ISSUE THREAD

**Issue by ziyenano** [PaddlePaddle/Paddle#5393]
RT, 
https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference,
这几个example好像都没有涉及到data provider的问题.
Btw, capi相关的能给出一个具体的demo吗, 内网以及github上的文档感觉都不是很完整.

**Comment by luotao1** [comment]
1. c-api不需要data provider。
2. 这部分的例子，我们目前正在做，还没有merge中。您可以先参考以下几个：
  - https://github.com/PaddlePaddle/models/pull/320
  - https://github.com/PaddlePaddle/models/pull/324
  - https://github.com/PaddlePaddle/models/pull/346
  - https://github.com/PaddlePaddle/models/pull/385

**Comment by ziyenano** [comment]
多谢, 但是我的数据在data_provider中进行了转化,  转成了spare_binary格式
![image](https://user-images.githubusercontent.com/11867700/32429839-1a69faca-c292-11e7-9ea7-10a1d91cd04e.png)
如果不需要dp, 需要在哪边添加上转化数据的步骤

**Comment by luotao1** [comment]
请先学习下上面的几个例子，了解下c-api的运行原理和流程。

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
