### ISSUE TITLE
paddle无法使用GPU

### ISSUE THREAD

**Issue by coolge** [PaddlePaddle/Paddle#53949]
### 问题描述 Issue Description

paddle无法使用GPU
一块Tesla P4, 使用命令paddle.fluid.is_compiled_with_cuda()验证是True，但是fluid.core.get_cuda_device_count()获取的GPU个数是0，即无法识别设备上的GPU。
环境：
python: 2.7.13
paddlepaddle-gpu: 1.8.1.post107

### 版本&环境信息 Version & Environment Information

环境：
python: 2.7.13
paddlepaddle-gpu: 1.8.1.post107
<img width="571" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/14039870/4ecea792-1d1b-499b-a7f8-5cc9ed647610">

**Comment by minghaoBD** [comment]
用户host机器是centos6系统，建议使用 paddle的镜像。
