### ISSUE TITLE
Paddle推理模型怎么转换为paddle.nn.Layer对象

### ISSUE THREAD

**Issue by Ikkyu321** [PaddlePaddle/Paddle#53946]
### 请提出你的问题 Please ask your question

rt
通过paddle.static.save_inference_model保存的
model.pdiparams
model.pdmodel
model.pdiparams.info
怎么载入模型，转换成paddle.nn.Layer

**Comment by minghaoBD** [comment]
你好，转换成paddle.nn.layer做不到。但是转换成动态图权重可以参考这个：

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/transformers/ernie/static_to_dygraph_params/match_static_to_dygraph.py
