### ISSUE TITLE
Question about multi_lr_scheduler?

### ISSUE THREAD

**Issue by Xiaolong-RRL** [PaddlePaddle/Paddle#53962]
想问一下，如何在paddle的config文件中设置不同的学习率策略？要求是前5个epoch采用cosine形式的warmup，之后采取steplr形式，在90和120个epoch分别变为原来的十分之一，一共训练140个epoch

**Comment by lyuwenyu** [comment]
框架本身没有config文件设置，  如果是使用相关的套件的话  在相应的repo-issue提问 或者 repo相应的文档

**Comment by Xiaolong-RRL** [comment]
感谢回复~已在对应的repo-issue中提问
