### ISSUE TITLE
PP-YOLOE+  模型 没有 ppyoloe_plus_crn_x_80e_coco 资源

### ISSUE THREAD

**Issue by zhou1591** [PaddlePaddle/Paddle#53972]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/39522200/c6711ef8-a18b-4707-b432-12bee07afad8)

文档里边有四个模型  s m l x  然后文档里边给了一个demo项目

项目运行的时候配置文件里边  s  m l  模型都有   切换到 x  得时候资源404 

![image](https://github.com/PaddlePaddle/Paddle/assets/39522200/59b82283-573c-48a0-bfa3-2925b1f5d85d)

**Comment by lyuwenyu** [comment]
请在相关项目下留言
