### ISSUE TITLE
image模块无法快速找到函数说明

### ISSUE THREAD

**Issue by liminhust** [PaddlePaddle/Paddle#5397]
开发过程中需要查找paddle.image.simple_transform(img, 256, 224, True) 语句中simple_transform的功能，但是在官方文档http://doc.paddlepaddle.org/develop/doc_cn/api/v2/data.html 中无法直接搜到此函数说明，不便于快速解决问题，麻烦补充下说明文档。

ps：多谢rd同学给力支持

**Comment by luotao1** [comment]
可以查看 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py 
后续我们需要将image的api也展现在网站上。
