### ISSUE TITLE
autots错误

### ISSUE THREAD

**Issue by ifengli** [PaddlePaddle/Paddle#53998]
### 请提出你的问题 Please ask your question

import warnings
warnings.filterwarnings('ignore')
from paddlets.automl.autots import AutoTS
from paddlets.models.forecasting import MLPRegressor
from paddlets.datasets.repository import get_dataset
tsdataset = get_dataset("UNI_WTH")
autots_model = AutoTS(MLPRegressor, 96, 2)
autots_model.fit(tsdataset)
predicted_tsdataset = autots_model.predict(tsdataset)
best_param = autots_model.best_param

报错 DeprecationWarning: The module `ray.tune.suggest` has been moved to `ray.tune.search` and the old location has been deprecated. Please adjust your imports to point to the new location. Example: Do a global search and replace `ray.tune.suggest` with `ray.tune.search`.

这个警告直接影响不能运行，在某次成功运行以后依然无法自动寻参，出现“RuntimeError: The actor with name ImplicitFunc failed to import on the worker. This may be because needed library dependencies are not installed in the worker environment:”   以及“TuneError: ('Trials did not complete', [run_trial_793c7123])”这个错误   。同时在BML上可以运行的项目，复制到本地运行，在fit部分直接出现“inputs nan”，查看了数据summary，missing都为0。也尝试了将数据修改为np.float64,依然失效

**Comment by zh794390558** [comment]
可以去PaddleTS的repo下提issue，目测是repo自己的问题，`ray.tune.suggest with ray.tune.search.`.

**Comment by kightbal** [comment]
这个问题应该是paddlets的Autots不支持新版本的ray，你可以把ray降级到1.13.0试一试

**Comment by kightbal** [comment]
这个问题可能是AUTOTS不支持高版本的ray你可以把你的ray降级到1.13.0试一试
