### ISSUE TITLE
paddle.nn.functional.sequence_mask算子在多卡状态下crash

### ISSUE THREAD

**Issue by yzhw9981** [PaddlePaddle/Paddle#54013]
### bug描述 Describe the Bug

静态图下，多卡训练1000多step后，报错如下（单卡正常）
sequence_mask raises an exception thrust::system::system_error, after reduction step 2

换成fluid.layers.sequence_mask正常

可复现环境
afs://yinglong.afs.baidu.com:9902/user/index-diaoyan/huangwei16/page-transformer-v3/output/paddlecloud_code/20230522003614834869/code.tar.gz
ugi请hi huangwei16或者直接申请目录读权限

**Comment by wangxinxin08** [comment]
可以先使用fluid的静态图API，相关问题将反馈给对应负责人
