### ISSUE TITLE
NN Conv doesn't work in GPU for CUDA 10.2 and cuDNN v7.6.5

### ISSUE THREAD

**Issue by Serif-NNR** [PaddlePaddle/Paddle#54014]
### 请提出你的问题 Please ask your question

Hello, 

After very boring hours, I have installed Paddlepaddle-gpu for my machine. 
However, I guess some configs aren't suitable without any error thrown by paddle lib.

I use 10.2 Cuda with cuDNN v7.6.5. There is no problem when using most of methods
such as creating new tensor or quering system status like paddle.utils.run_check(). But
when I use conv from nn lib, the interpreter stops working and frozen without any signal 
and alert. I can define conv but can't use conv.

Any solution for this issue is known by the community? Reinstalling the cuda may not a properly
solution.

Note: I use Python 3.10 and paddlepaddle_gpu-2.4.2 together with 3050 for Laptop

**Comment by Serif-NNR** [comment]
Additionally, when I run a model using Python 3.10, I gotta these warnings:

...\paddleseg\cvlibs\manager.py:113: UserWarning: PPMobileSeg exists already! It is now updated to <class 'PaddleSeg.PPMobileSeg'> !!!
  warnings.warn("{} exists already! It is now updated to {} !!!".
W0522 00:39:35.068246  9964 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 10.2
W0522 00:39:35.138263  9964 gpu_resources.cc:91] device: 0, cuDNN Version: 7.6.


Also I don't any error when using conv with pytorch lib and same cuda configurations.

**Comment by wangxinxin08** [comment]
Can you show me the screenshot while running the nn.conv? The warning is nothing to do with PaddlePaddle framework，you can leave it alone or seek help in https://github.com/PaddlePaddle/PaddleSeg/issues
