### ISSUE TITLE
在安装飞浆GPU开发版本

### ISSUE THREAD

**Issue by cheercao** [PaddlePaddle/Paddle#54020]
### 问题描述 Issue Description

根据飞浆文档，使用命令：python -m pip install paddlepaddle-gpu==0.0.0.post117 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html安装paddle-gpu开发版本，安装成功之后，在python中使用import paddle报错误非法指令 (核心已转储)，cuda版本为11.7

### 版本&环境信息 Version & Environment Information

paddle版本为开发者版本，cuda版本为11.7

**Comment by cheercao** [comment]
好像是由于不支持AVX的原因

**Comment by wangxinxin08** [comment]
可以贴下报错截图

**Comment by cheercao** [comment]
根据文档我安装了noavx版本的paddle，但是又有新的问题出现，根据文档我执行python3 -m pip download paddlepaddle-gpu==2.4.2 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html --no-index --no-deps
命令，安装好了noavx版本的paddle，但又有问题出现了。
![@G`%5JUUEBDO6NWZ`}JPTXX](https://github.com/PaddlePaddle/Paddle/assets/60064870/7a4ca0fd-8053-49fb-bd84-48fb4039b105)

**Comment by cheercao** [comment]
根据文档说明，这里的cuda为10.2，但我的cuda为11.7.
![image](https://github.com/PaddlePaddle/Paddle/assets/60064870/7ea7e9c7-9080-4950-b47e-853e7b8eb244)

**Comment by wangxinxin08** [comment]
可以在安装时指定cuda版本，如paddlepaddle-gpu==2.4.2.post117

**Comment by cheercao** [comment]
这个cuda版本是支持AVX的，但我的cpu不支持AVX，而我找不到不支持AVX的paddlepaddle-gpu==2.4.2.post117

**Comment by cheercao** [comment]
文档只给出了这一种方法：
![image](https://github.com/PaddlePaddle/Paddle/assets/60064870/d5d5839e-a287-4c03-a5b8-cb8842b5a042)

**Comment by cheercao** [comment]
我在文件夹中能找到对应的文件：
![image](https://github.com/PaddlePaddle/Paddle/assets/60064870/b4d18987-a05e-4100-9caf-fde705397b9c)

**Comment by luofeng1999** [comment]
我也碰到了同样的问题，请问题主最后解决了吗？ 我的paddle版本是开发者版本，CUDA是10.2
![image](https://github.com/PaddlePaddle/Paddle/assets/77435112/39770d98-70e0-4898-989d-08131daba51e)

**Comment by MooTong123** [comment]
> 可以在安装时指定cuda版本，如paddlepaddle-gpu==2.4.2.post117

请问下，找不到noavx版本的paddlepaddle-gpu==2.4.2.post117该如何处理？

安装命令：
```
pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
Looking in links: https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
```

报错如下：
```
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.4.2.post117 (from versions: 1.8.5.post97, 1.8.5.post107, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.2.post101, 2.1.3, 2.1.3.post101, 2.2.0rc0, 2.2.0rc0.post101, 2.2.0, 2.2.0.post101, 2.2.1, 2.2.1.post101, 2.2.2, 2.2.2.post101, 2.3.0rc0, 2.3.0rc0.post101, 2.3.0rc0.post102, 2.3.0, 2.3.0.post101, 2.3.1, 2.3.1.post101, 2.3.2, 2.3.2.post101, 2.4.0rc0, 2.4.0rc0.post101, 2.4.0, 2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2.post117
```

看报错信息，是没有paddlepaddle-gpu==2.4.2.post117这个的，那该如何下载noavx版本的cuda11.7版本的呢？？
