### ISSUE TITLE
ResNet_MS3模型python版本推理结果和C++版本推理结果不匹配

### ISSUE THREAD

**Issue by andrew8yang** [PaddlePaddle/Paddle#54021]
### bug描述 Describe the Bug

paddle version 2.4.2版本
1.导出模型作为C++版本的模型文件
https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/QualityInspector/tools/uad/stfpm/predict.py#L24
在上面的python文件中导出模型的代码如下
    print(paddle.__version__)
    from paddle.static import InputSpec
    # 2. 构造 InputSpec 信息
    input_spec = InputSpec([1, 3,256,256], 'float32', 'x')
    # 3.调用 paddle.jit.save 接口转为静态图模型
    path = "my-models/teacher"
    paddle.jit.save( layer=teacher, path=path, input_spec=[input_spec])
    #  teacher=paddle.jit.load(path)
    path = “my-models/student"
    paddle.jit.save( layer=student, path=path, input_spec=[input_spec])

2.C++推理代码

//run function
void run(Predictor *predictor, const std::vector<float> &input,
         const std::vector<int> &input_shape, std::vector<float> *out_data) {
  int input_num = std::accumulate(input_shape.begin(), input_shape.end(), 1,
                                  std::multiplies<int>());

  auto input_names = predictor->GetInputNames();
  auto output_names = predictor->GetOutputNames();
  auto input_t = predictor->GetInputHandle(input_names[0]);
  input_t->Reshape(input_shape);
  input_t->CopyFromCpu(input.data());

  for (size_t i = 0; i < FLAGS_warmup; ++i)
    CHECK(predictor->Run());

  std::vector<float> out_data0 , out_data1,out_data2;
  auto st = time();
  for (size_t i = 0; i < FLAGS_repeats; ++i) {
    CHECK(predictor->Run());
    auto output_t = predictor->GetOutputHandle(output_names[0]);
    std::vector<int> output_shape = output_t->shape();
    int out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                  std::multiplies<int>());
    out_data0.resize(out_num);
    output_t->CopyToCpu(out_data0.data());

    // output 1
    output_t = predictor->GetOutputHandle(output_names[1]);
    output_shape = output_t->shape();
    out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                  std::multiplies<int>());
    printf("andrew debug out_num %d\n" , out_num);
    out_data1.resize(out_num);
    output_t->CopyToCpu(out_data1.data());

    //output2
    output_t = predictor->GetOutputHandle(output_names[2]);
    output_shape = output_t->shape();
    out_num = std::accumulate(output_shape.begin(), output_shape.end(), 1,
                                  std::multiplies<int>());
    out_data2.resize(out_num);
    output_t->CopyToCpu(out_data2.data());
  }

  LOG(INFO) << "run avg time is " << time_diff(st, time()) / FLAGS_repeats
            << " ms";
}

3. 其中发现推理错误的地方是output2 , 也就是relu_12.tmp_0这个output有问题。shape大小是1, 256, 16, 16 ， 保存这个output的数据和 https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/QualityInspector/tools/uad/stfpm/predict.py 中的t_feat[2] 数据做对比，发现余弦相似度只有0.22 . 前面两个output的相似度则可以达到0.99。 

复现步骤
1. checkout 工程https://github.com/PaddlePaddle/PaddleSeg/blob/release/2.8/contrib/QualityInspector/
2. python tools/uad/stfpm/predict.py --config ./configs/uad/stfpm/stfpm_resnet18_mvtec.yml --category bottle （提前添加导出模型的代码和保存tfeat[2]输出）
3. C++代码推理实现run代码前面已经提供，是否需要提供完整代码？
4. 对比两个输出发现python版本的tfeat[2]和c++版本的t_feat[2] 复现结果

**Comment by wangxinxin08** [comment]
paddleseg相关问题可以到PaddleSeg的repo下去提问

**Comment by andrew8yang** [comment]
OK，但似乎这个问题是C++版本的paddle出了问题？
