### ISSUE TITLE
不能成功运行deepxde提供的例子

### ISSUE THREAD

**Issue by xusuyong** [PaddlePaddle/Paddle#54040]
### bug描述 Describe the Bug

跑deepxde官网提供的所有example都会出现这样的报错：
'''C:\Users\hcxy\.conda\envs\pdd\python.exe E:\迅雷下载\deepxde-master\deepxde-master\examples\pinn_inverse\Navier_Stokes_inverse.py 
Using backend: paddle
Other supported backends: tensorflow.compat.v1, tensorflow, pytorch, jax.
paddle supports more examples now and is recommended.
W0523 11:00:40.093221  8060 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.1, Runtime API Version: 10.2
W0523 11:00:40.339197  8060 gpu_resources.cc:149] device: 0, cuDNN Version: 7.6.
Compiling model...
'compile' took 0.000104 s

Training model...

Traceback (most recent call last):
  File "E:\迅雷下载\deepxde-master\deepxde-master\examples\pinn_inverse\Navier_Stokes_inverse.py", line 124, in <module>
    loss_history, train_state = model.train(
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\utils\internal.py", line 22, in wrapper
    result = f(*args, **kwargs)
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 618, in train
    self._test()
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 807, in _test
    ) = self._outputs_losses(
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 533, in _outputs_losses
    outs = outputs_losses(inputs, targets, auxiliary_vars)
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 459, in outputs_losses_train
    return outputs_losses(
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 450, in outputs_losses
    losses = paddle.concat(losses, axis=0)
  File "C:\Users\hcxy\.conda\envs\pdd\lib\site-packages\paddle\tensor\manipulation.py", line 1121, in concat
    return _C_ops.concat(input, axis)
ValueError: (InvalidArgument) The axis is expected to be in range of [0, 0), but got 0
  [Hint: Expected axis >= -rank && axis < rank == true, but received axis >= -rank && axis < rank:0 != true:1.] (at ..\paddle\phi\infermeta\multiary.cc:959)

进程已结束,退出代码1
'''
请问该如何解决呢？使用的是paddle(develop)版

**Comment by xiaoguoguo626807** [comment]
拉取的是deepxde 的新代码吗，这个问题之前在deepxde 里修复了

**Comment by xusuyong** [comment]
> 拉取的是deepxde 的新代码吗，这个问题之前在deepxde 里修复了

是最新的deepxde（1.9.0）

**Comment by lijialin03** [comment]
> > 拉取的是deepxde 的新代码吗，这个问题之前在deepxde 里修复了
> 
> 是最新的deepxde（1.9.0）

请问能贴一下你install deepxde的方法吗？我这边直接pip install显示没有1.9.0

**Comment by lijialin03** [comment]
报错的语句File "C:\Users\hcxy.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 450, in outputs_losses
losses = paddle.concat(losses, axis=0)
在deepxde github代码中已经更改为losses = paddle.stack(losses, axis=0)
可以看这个commit https://github.com/lululxvi/deepxde/commit/21ca6afa855ca59dfed381a14574f3350a548125
可能是deepxde作者还没有将最新代码打包，可以手动将这一行代码改掉，或者git clone deepxde后，再export PYTHONPATH=/yourpath/deepxde/ 使用

**Comment by xusuyong** [comment]
> 报错的语句File "C:\Users\hcxy.conda\envs\pdd\lib\site-packages\deepxde\model.py", line 450, in outputs_losses losses = paddle.concat(losses, axis=0) 在deepxde github代码中已经更改为losses = paddle.stack(losses, axis=0) 可以看这个commit [lululxvi/deepxde@21ca6af](https://github.com/lululxvi/deepxde/commit/21ca6afa855ca59dfed381a14574f3350a548125) 可能是deepxde作者还没有将最新代码打包，可以手动将这一行代码改掉，或者git clone deepxde后，再export PYTHONPATH=/yourpath/deepxde/ 使用

懂了，谢谢！

**Comment by luotao1** [comment]
@xusuyong 飞桨护航计划集训营的简历请尽快提交，10/11号截止，公布名单
<img width="559" alt="be850586031a9cddd6db74f72c880a20" src="https://github.com/PaddlePaddle/Paddle/assets/6836917/ce5de8a6-90db-4d88-8a76-625331e9393d">
