### ISSUE TITLE
paddle训练工具打包，解压到另一台机器训练出错

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#5405]
我在A机器上编译好了paddle，安装到了paddle_bin, 有如下目录：
paddle_bin
├── bin
│   └── paddle
└── opt
    └── paddle
        ├── bin
        │   ├── paddle_merge_model
        │   ├── paddle_pserver_main
        │   ├── paddle_trainer
        │   └── paddle_usage
        └── share
            └── wheels
                ├── paddle-0.10.0rc4-py2-none-any.whl
                └── py_paddle-0.10.0rc4-py2-none-any.whl
我将paddle_bin打包，放到另一个机器中，再执行训练任务时，报错:

```text
First time run paddle, need to install some python dependencies.
Requirement '/home/work/local/online_train/paddle_software/paddle_bin/bin/../opt/paddle/share/wheels/*--*.whl' looks like a filename, but the file does not exist
*--*.whl is not a valid wheel filename.
pip install wheels failed.
Please use 'sudo paddle' at the first time you use PaddlePaddle
PaddlePaddle will install some python dependencies automatically.
```
我是无法获取sudo的权限的。这应该怎么办呢？

**Comment by lcy-seso** [comment]
看上去是因为两台机器的环境不一样。wheel 的名字里也包含程序版本，支持的python版本，平台等很多信息。之前编译出的wheel包无法在这台机器上直接安装。
