### ISSUE TITLE
Heterogeneous environment support

### ISSUE THREAD

**Issue by abuvaneswari** [PaddlePaddle/Paddle#5406]
Hello,

I read from your homepage that you support heterogeneous training environment. Does that include both compute and network heterogeneity? Do you determine the extent of heterogeneity by profiling, or the user would hardcode? 

And how do you address the heterogeneity? there are many ways to treat compute heterogeneity in Async & Sync distributed training. Please provide links to papers that you may have utilized. 

thanks,
Buvana

**Comment by typhoonzero** [comment]
Hi, thanks for your question. Please check out this [link](http://doc.paddlepaddle.org/develop/doc/howto/usage/cluster/cluster_train_en.html), it describes running distributed training jobs using fabric, OpenMPI and Kubernetes.
