### ISSUE TITLE
Required paddlepaddle cpu 1.5.x version wheel for installation 

### ISSUE THREAD

**Issue by dineshresearch** [PaddlePaddle/Paddle#54093]
### 请提出你的问题 Please ask your question

For running the metagym/liftsim baselines i need to install the paddlepaddle cpu 1.5.x version but could not find the prebuilt wheel from pip (https://pypi.org/project/paddlepaddle/#history).  Please kindly help me with the wheel.  
![image](https://github.com/PaddlePaddle/Paddle/assets/26215090/358faa88-7e78-4f23-83e8-0da0f30c0e00)

thank you

**Comment by wangna11BD** [comment]
we do not provide cpu_1.5.x version wheel. if you need it, you can compile it by yourself.

**Comment by dineshresearch** [comment]
Could you kindly provide the build instructions for paddle cpu 1.5.x. As i could only find instructions upto 1.8.x version only.
![1](https://github.com/PaddlePaddle/Paddle/assets/26215090/7e0f2570-faba-4721-9dc4-d928df91f0cd)

**Comment by dineshresearch** [comment]
@wangna11BD I have found the docker image for paddle cpu 1.5.1 but it contains only python 2.7. Will it support python3 or not could you please clarify. 
fyi i want to run the liftsim parl baselines and it requires paddle cpu 1.5.1 and the required python version they mentioned was 3.6. https://github.com/PaddlePaddle/PARL/issues/971

![image](https://github.com/PaddlePaddle/Paddle/assets/26215090/9a7addf2-e532-4d4a-bebf-1d59963331e5)
