### ISSUE TITLE
數個重要修正需要 cherry-pick 到 release/2.5 branch

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#54100]
### 需求描述 Feature Description

經過大家的努力，有數個重要的PR已合併進 develop branch，麻煩協助 cherry-pick 到 release/2.5 branch

## PR list ##
- [ ] #51554
- [ ] #52401
- [ ] #52485
- [ ] #53937
- [ ] #54032
- [ ] #54038
- [ ] #54042
- [ ] #54057

**Comment by onecatcn** [comment]
Due to the schedule change, the cherry-pick work is not necessary anymore. Thanks for the contributions.
