### ISSUE TITLE
requirements.txt is not fully aligned between the build and the unit tests

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#54102]
### 问题描述 Issue Description

Paddle 現在有兩份 requirements.txt, [python/requirements.txt](https://github.com/PaddlePaddle/Paddle/blob/v2.5.0-rc1/python/requirements.txt) 以及 [python/unittest_py/requirements.txt](https://github.com/PaddlePaddle/Paddle/blob/v2.5.0-rc1/python/unittest_py/requirements.txt)。但是這兩個檔案裡面描述的部分套件並沒有對齊，例如 numpy 在 [python/requirements.txt](https://github.com/PaddlePaddle/Paddle/blob/v2.5.0-rc1/python/requirements.txt) 是 `numpy>=1.13`，並在 [python/unittest_py/requirements.txt](https://github.com/PaddlePaddle/Paddle/blob/v2.5.0-rc1/python/unittest_py/requirements.txt) 是 `numpy >=1.20`。我們應該避免在 [python/unittest_py/requirements.txt](https://github.com/PaddlePaddle/Paddle/blob/v2.5.0-rc1/python/unittest_py/requirements.txt) 中記錄重複的套件來避免安裝環境跟測試環境不同。

### 版本&环境信息 Version & Environment Information

Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 22.04
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Clang version: N/A
CMake version: version 3.25.1
Libc version: glibc 2.35
Python version: 3.10.6

CUDA version: 12.1.105
Build cuda_12.1.r12.1
cuDNN version: 8.9.1
Nvidia driver version: 525.105.17
Nvidia driver List:
GPU 0: NVIDIA H100 80GB HBM3

**Comment by tianshuo78520a** [comment]
可以临时设置pip install numpy==1.23.5解决，我们在尝试完全修复这个问题
