### ISSUE TITLE
dataloader 关于signal 信号报错的疑惑

### ISSUE THREAD

**Issue by ahua2333** [PaddlePaddle/Paddle#54119]
### 请提出你的问题 Please ask your question

在dataloder 关于signal 信号的报错反馈有些问题，翻了下代码，我看报错的类型是在这里注册的：https://github.com/PaddlePaddle/Paddle/blob/7bf97d2c626d46fa2c62f1e171d806c7a973c3d0/paddle/fluid/imperative/data_loader.cc#L123
就是不同的signal 信号 就注册不同的 错误信息嘛？ 如果这样的话是不是直接在python 层 看子进程exitcode，不同的退出码注册一个错误信息是不是更简单：）

**Comment by Zhiy-Zhang** [comment]
请问有啥comments嘛？ @cxxly

**Comment by ahua2333** [comment]
您好，求问下有啥考虑嘛 @cxxly

**Comment by cxxly** [comment]
这快代码我也刚看，我们讨论下哈，个人观点，不一定正确，首先 1) exitcode 和Signal不是一回事吧， exitcode 就是程序状态，成功、失败、各种错误码等，signal是一些硬件中断处理，如计算机ctrl+c 2) 至于Signal处理我个人感觉在哪一层处理，区别不大，关键是报错信息是否友好

**Comment by ahua2333** [comment]
@cxxly 非常感谢您的回复 关于第一点他们确实不是一回事，但是由于signal导致的进程退出应该是有exitcode对应的，也就是能够根据这个exitcode来找到是啥错误，看起来这里也是这么处理的https://github.com/PaddlePaddle/Paddle/blob/7bf97d2c626d46fa2c62f1e171d806c7a973c3d0/paddle/fluid/imperative/data_loader.cc#L184     strsignal(infop.si_status) 找到对应的具体错误，找不到的就直接以exitcode的形式返回：https://github.com/PaddlePaddle/Paddle/blob/7bf97d2c626d46fa2c62f1e171d806c7a973c3d0/paddle/fluid/imperative/data_loader.cc#L162    只是没有触发coredump嘛

关于第二点我得理解是这样的：1、如果是进程堵塞或者其他情况导致进程卡在导致无法回到主进程可能就没法检查exitcode了，所以这种方式“不靠谱”，用cpython自定义函数来catch signal的信息是会在报错第一时间throw 出error
2、这种方式是否报错信息更友好，看signal 库中的signal handler会有frame，是不是会多些backtrace来方便调试

以为有些地方不太熟悉，所以只是我得一些见解

**Comment by cxxly** [comment]
@heavengate 能否帮忙看下？

**Comment by heavengate** [comment]
这个是子进程singal的callback，不影响主进程的singnal

**Comment by ahua2333** [comment]
@heavengate 感谢您回复，但是可能没太理解明白- -，所以这里用singal 的callback来throw出error跟 子进程退出后 的exitcode 来 throw error是不是应该是一样的
