### ISSUE TITLE
paddlepaddle使用昆仑R200 xpu训练后，如何使用xpu进行预测，是否有相关的参数设置或调用？

### ISSUE THREAD

**Issue by renyukun0404** [PaddlePaddle/Paddle#54111]
### 请提出你的问题 Please ask your question

paddlepaddle使用昆仑R200 xpu训练后，如何使用xpu进行预测，是否有相关的参数设置或调用？

**Comment by cxxly** [comment]
训练和推理过程应该是和硬件无关的，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/beginner/train_eval_predict_cn.html#paddle-model-api

**Comment by renyukun0404** [comment]
> 训练和推理过程应该是和硬件无关的，参考https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/beginner/train_eval_predict_cn.html#paddle-model-api

这个网站上面的api接口不行，我使用的是paddlepaddle里面的infer.py进行预测，传递xpu的参数不行。有没有专门针对xpu的调用接口提供？

**Comment by cxxly** [comment]
应该是没有的
