### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by tangpanyu** [PaddlePaddle/Paddle#54128]
### 请提出你的问题 Please ask your question

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:277: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float32, but right dtype is paddle.float16, the right dtype will convert to paddle.float32
  .format(lhs_dtype, rhs_dtype, lhs_dtype))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/math_op_patch.py:277: UserWarning: The dtype of left and right variables are not the same, left dtype is paddle.float16, but right dtype is paddle.float32, the right dtype will convert to paddle.float16
  .format(lhs_dtype, rhs_dtype, lhs_dtype))
C++ Traceback (most recent call last):
--------------------------------------
0   sum_ad_func(paddle::experimental::Tensor const&, paddle::experimental::IntArrayBase<paddle::experimental::Tensor>, paddle::experimental::DataType, bool)
1   sum_ad_func(paddle::experimental::Tensor const&, paddle::experimental::IntArrayBase<paddle::experimental::Tensor>, paddle::experimental::DataType, bool)
2   paddle::experimental::sum(paddle::experimental::Tensor const&, paddle::experimental::IntArrayBase<paddle::experimental::Tensor> const&, paddle::experimental::DataType, bool)
3   void phi::SumKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, paddle::experimental::DataType, bool, phi::DenseTensor*)
4   void phi::SumRawKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, paddle::experimental::IntArrayBase<phi::DenseTensor> const&, bool, bool, paddle::experimental::DataType, phi::DenseTensor*)
5   void phi::Reduce<float, phi::kps::AddFunctor, phi::kps::IdentityFunctor>(phi::GPUContext const&, phi::DenseTensor const&, bool, std::vector<long, std::allocator<long> > const&, bool, paddle::experimental::DataType, phi::DenseTensor*, bool)
6   void phi::funcs::ReduceKernel<float, float, phi::kps::AddFunctor, phi::kps::IdentityFunctor<float, float> >(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor*, phi::kps::IdentityFunctor<float, float> const&, std::vector<int, std::allocator<int> > const&, bool)

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1685072710 (unix time) try "date -d @1685072710" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7fc070d1f22a) received by PID 800 (TID 0x7fc0eda57700) from PID 1892807210 ***]

LAUNCH INFO 2023-05-26 11:45:12,392 Exit code -15

W0526 11:44:37.547624   798 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 11.2
W0526 11:44:37.551545   798 gpu_resources.cc:91] device: 0, cuDNN Version: 8.2.
[2023-05-26 11:44:45,210] [    INFO] topology.py:187 - HybridParallelInfo: rank_id: 0, mp_degree: 1, sharding_degree: 1, pp_degree: 1, dp_degree: 4, mp_group: [0],  sharding_group: [0], pp_group: [0], dp_group: [0, 1, 2, 3], check/clip group: [0]

不懂但是很震惊

**Comment by DesmonDay** [comment]
这里我也看不太出来问题。可以考虑定位到具体是哪个OP执行时报的错，打印对应的输入，看输入数据是否符合要求。
