### ISSUE TITLE
paddlepaddle中用到了onnxruntime-gpu,昆仑R200的XPU如何支持安装？

### ISSUE THREAD

**Issue by renyukun0404** [PaddlePaddle/Paddle#54137]
### 问题描述 Issue Description

paddlepaddle中用到了onnxruntime-gpu,昆仑R200的XPU如何支持安装？

### 版本&环境信息 Version & Environment Information

paddlepaddle中用到了onnxruntime-gpu,昆仑R200的XPU如何支持安装？

**Comment by DesmonDay** [comment]
可以考虑看一下安装文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/xpu_docs/paddle_install_xpu2_cn.html

**Comment by renyukun0404** [comment]
> 可以考虑看一下安装文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/xpu_docs/paddle_install_xpu2_cn.html

这个没啥用，paddle的包我已经安装了，但是运行预测的时候，速度比普通cpu还慢，如果使用gpu，onnxruntime包又过不去，这个需要怎么样支持才行。

**Comment by DesmonDay** [comment]
请问你是厂内用户么？

**Comment by DesmonDay** [comment]
“但是运行预测的时候，速度比普通cpu还慢，如果使用gpu，onnxruntime包又过不去”。想知道这里是在说xpu推理慢，还是说onnxruntime和paddle的gpu有冲突呢？

**Comment by renyukun0404** [comment]
> “但是运行预测的时候，速度比普通cpu还慢，如果使用gpu，onnxruntime包又过不去”。想知道这里是在说xpu推理慢，还是说onnxruntime和paddle的gpu有冲突呢？

我现在使用的是xpu，没有使用gpu，但是我推理过程，我不知道是否调用了xpu进行了推理，相关的参数都设置了xpu，但是速度还是很慢，我使用的是百度云环境进行的部署，使用的是昆仑R200，我训练使用的是xpu速度有提升，使用paddle.onnx.export(model, save_path, input_spec=[in_spec],opset_version=13)导出模型文件，预测加载使用的是float_onnx_file = os.path.join(infer_model_dir, "model.onnx")，
import onnx
onnx_model = onnx.load_model(float_onnx_file)
self.predictor = ort.InferenceSession(
                onnx_model.SerializeToString(),
                sess_options=sess_options,
                #providers=['CPUExecutionProvider'])
                providers=['TensorrtExecutionProvider'])
，正常预测速度比我正常使用cpu预测还慢好多倍。

**Comment by RichardWooSJTU** [comment]
> 相关的参数都设置了xpu

看您的代码是直接调用了onnx_runtime？我理解没有这样的支持，可以使用paddleinference进行推理部署，demo参考https://github.com/PaddlePaddle/Paddle-Inference-Demo/tree/master/python/xpu/resnet50
