### ISSUE TITLE
Paddle算子缺失torch.hann_window

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#54138]
### bug描述 Describe the Bug

在复现HF论文的时候，发现Paddle缺失hann_window算子。希望尽快补齐

https://pytorch.org/docs/stable/generated/torch.hann_window.html

**Comment by 233lol** [comment]
paddle 是paddle.audio.functional.get_window
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/audio/functional/get_window_cn.html
