### ISSUE TITLE
lstmemory的hidden size怎么指定，官网教程为什么除以4

### ISSUE THREAD

**Issue by zishuaiz** [PaddlePaddle/Paddle#5414]
rt
hidden_dim = 512，LSTM hidden vector = 128，为什么要除以4，官网教程给的解释连接已经失效。
http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers.html#lstmemory
求补充~

如果要指定lstm hidden vector长度为80，那是不是要定义hidden_dim = 320？
有点怪异。

**Comment by lcy-seso** [comment]
这个并不怪异~  LSTM 的hidden size 根据输入向量自动推断出来，需要理解 hidden vector的含义。

![image](https://user-images.githubusercontent.com/5842774/32474519-72fc9cba-c332-11e7-9c26-2a5fbca0d007.png)

下面`fc`层的size是hidden size * 4，而fc层可学习参数就对应了上图公式中圈出来的红色部分。降四个乘法运算合并一次计算完毕，这一点并不怪异。
```python
fc = paddle.layer.fc(
    input=inputs,
    size=hidden_size * 4,
    act=linear,
    param_attr=para_attr,
    bias_attr=bias_attr)
lstm = paddle.layer.lstmemory(input=fc, reverse 0, act=tanh)
```

**Comment by zishuaiz** [comment]
@lcy-seso 多谢解答。
还有个疑问，[bidirectional_lstm](http://doc.paddlepaddle.org/release/0.10.0/doc/api/v2/config/networks.html#bidirectional-lstm)，如果return_seq，那这个seq的长度是每个句子的实际长度还是这个batch中最大的那个长度？
如果是每个句子的实际长度，那paddle是怎么做到batch计算的；如果是batch中的最长句子长度，那如果对返回的seq操作时，怎样知道句子的实际长度？

**Comment by lcy-seso** [comment]
- RNN每个时间步都有输出，return_seq=True时，会将RNN所有时刻的输出全部返回，就等于句子的实际长度。

**Comment by lcy-seso** [comment]
一个序列在内存中是连续的，如果一个batch中含有多个不等长的序列，在PaddlePaddle中有专门的信息标示每个序列在batch中的起始位置。这个信息在data layer中接受序列输入时，已经计算好，不需要用户特别的关心。

**Comment by zishuaiz** [comment]
👍
