### ISSUE TITLE
CentOS 7 安装paddle develop之后 libssl.so.1.1: cannot open shared object file

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#54194]
### 问题描述 Issue Description

```python
>>> import paddle
Error: Can not import paddle core while this file exists: /ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/fluid/core.py", line 355, in <module>
    raise e
  File "/ssd1/username/miniconda3/envs/py39/lib/python3.9/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### 版本&环境信息 Version & Environment Information

centos 7

**Comment by ZHUI** [comment]
2.4.2 的paddle没有问题。develop不行。

**Comment by tiandou-tangdou** [comment]
遇到同样问题 0630 linux cpu daily包，請問具体是哪里的升级？
![image](https://github.com/PaddlePaddle/Paddle/assets/127805199/c4adbc21-946f-46c4-acce-6018a536bab8)

**Comment by hunter2009pf** [comment]
也遇到这个问题，我本地有libssl.so.1.1文件，加入了环境变量中，它还是找不到。。

**Comment by zrr1999** [comment]
我也不知道什么时候更新了下，突然也出现了这个问题

**Comment by zrr1999** [comment]
```bash
wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```
可以先使用手动安装的方式解决

**Comment by Tlntin** [comment]
> ```shell
> wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> ```
> 
> 可以先使用手动安装的方式解决

他是CentOS, deb不适合他。
其次，libssl和libc都是比较底层的东西，不建议手动安装第三方库，可能会造成无法上网，系统崩溃问题。
再者，不同系统默认的libc/libssl版本都不一样，建议从源仓库安装而不是手动安装，当然，某些系统可能没有这个版本的libssl。
最后，作为一个AI框架，绑定libssl版本我觉得有些xx。

**Comment by ZHUI** [comment]
现在还有这个问题吗？应该已经修复了

**Comment by Tlntin** [comment]
> 现在还有这个问题吗？应该已经修复了

今天刚装的，ubuntu 22.04用户，提示这个报错。

**Comment by ZHUI** [comment]
> > 现在还有这个问题吗？应该已经修复了
> 
> 今天刚装的，ubuntu 22.04用户，提示这个报错。

paddle 2.5.1 吗？还是 paddle develop

**Comment by Tlntin** [comment]
> paddle 2.5.1

paddle 2.5.1

**Comment by Adachi324** [comment]
请问解决了吗？

**Comment by Tlntin** [comment]
> 请问解决了吗？

只能换docker了。

**Comment by zhengqiwen1997** [comment]
https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory
可以看看这个，是不是你ubu22.04的openssl默认版本不是1.1.1

**Comment by Adachi324** [comment]
> > 请问解决了吗？
> 
> 只能换docker了。

尝试过他们提供的景象，会报一样的错误

**Comment by Adachi324** [comment]
> https://stackoverflow.com/questions/72133316/libssl-so-1-1-cannot-open-shared-object-file-no-such-file-or-directory 可以看看这个，是不是你ubu22.04的openssl默认版本不是1.1.1

是centos

**Comment by Tlntin** [comment]
> > > 请问解决了吗？
> > 
> > 
> > 只能换docker了。
> 
> 尝试过他们提供的景象，会报一样的错误

哦吼？我刚刚试了一下dokcer,可以运行，但是推理了几次就显存溢出了（跑了PaddleOCR,显存2G左右，有时候突然就爆显存了），我怀疑是paddle最新版有内存泄露问题，准备降到2.4.2试试了。

**Comment by risemeup1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56366，次PR修复这个问题

**Comment by risemeup1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56366
此PR修复这个问题

**Comment by hhxdestiny** [comment]
这个问题难道不是python版本引起的么？我发现conda创建env时，在python=3.11.2时依赖还是openssl-1.1.1，而python=3.11.3时就成了openssl-3.0.11
![image](https://github.com/PaddlePaddle/Paddle/assets/44420757/a9a2abe5-c0b3-4d6c-9655-6e42299ff6dd)
![image](https://github.com/PaddlePaddle/Paddle/assets/44420757/cb906d19-a0b0-41b5-8e14-26dae041badc)

**Comment by ReadyGo666** [comment]
降低paddlepaddle的版本。
亲测有效，错误libssl.so.1.1: cannot open shared object file: No such file or directory消失了
我用的是paddlepaddle==2.4.0

**Comment by lijiajun3029** [comment]
ubuntu22.04 conda env
paddlepaddle 2.5.1

`conda install openssl=1.1.1`
