### ISSUE TITLE
Operator "gen_nccl_id" has not been registered

### ISSUE THREAD

**Issue by sifuhr** [PaddlePaddle/Paddle#54192]
### 问题描述 Please describe your issue

那windows 怎么用呢？document_intelligence 文档检索， File "D:\anaconda\envs\llm\lib\site-packages\paddle\fluid\framework.py", line 2713, in get_op_proto
raise ValueError("Operator "%s" has not been registered." % type)
ValueError: Operator "gen_nccl_id" has not been registered.
LAUNCH INFO 2023-05-30 10:42:54,298 Exit code 1

**Comment by sifuhr** [comment]
windows 下不可以安装nccl 那么如何运行呢

**Comment by zyfncg** [comment]
你好，Window系统上不支持分布式训练，这里是使用了分布式的相关接口吗？

**Comment by sifuhr** [comment]
https://github.com/PaddlePaddle/PaddleNLP/tree/develop/applications/document_intelligence/doc_vqa    我是按照这个一步一步弄的，安装没问题，结果报错。训练里边有配置吗，不让分布式，有单个节点吗？没有配置的地方吗

**Comment by sifuhr** [comment]
即使不能分布式，也会有单节点运行把，cd Rerank
bash run_train.sh ./data/train.tsv ./checkpoints/base_model 50 1 就是这一步报错

**Comment by sifuhr** [comment]
也没什么特别的地方呢，就是计算损失的时候，出现这个错误，不知道为什么了

**Comment by zyfncg** [comment]
> 即使不能分布式，也会有单节点运行把，cd Rerank bash run_train.sh ./data/train.tsv ./checkpoints/base_model 50 1 就是这一步报错

window系统上是怎么执行shell脚本的？

**Comment by zyfncg** [comment]
<img width="843" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/13048366/2ad3275f-2a18-4125-b811-a48cb9fbe0f2">
shell脚本里默认是用分布式执行器做的训练，如果想要在window上修改运行脚本的话可以在 https://github.com/PaddlePaddle/PaddleNLP/issues 里再具体咨询下

**Comment by sifuhr** [comment]
好的谢谢

**Comment by Longer767** [comment]
> 

你好！这一步报错请问怎么解决的？
