### ISSUE TITLE
Profiler `TracerEventType` lacks runtime type for custom device

### ISSUE THREAD

**Issue by ziyanwangin** [PaddlePaddle/Paddle#54200]
### 请提出你的问题 Please ask your question

- 在 #52319 中，从[`phi::TracerEventType`](https://github.com/PaddlePaddle/Paddle/blob/14425c066956bd65504e86533db360311e142029/paddle/phi/api/profiler/trace_event.h#L23)枚举中[移除了MluRuntime](https://github.com/PaddlePaddle/Paddle/pull/53194/files#diff-fc230630fe5f05ff9b901399b40c1990e2dcc47367a6df745924ba32cf38ea92)，因此[所有custom device只能使用`CudaRuntime`来表示自己的runtime](https://github.com/PaddlePaddle/PaddleCustomDevice/blob/579f656c420d8ba4f46f94a14af674e824981c23/backends/mlu/runtime/process_data.cc#L248)。

请问是否可以提供一个custom device通用的runtime类型？@qili93 @ronny1996

**Comment by qili93** [comment]
收到您这里的需求，目前在custom device中使用cudaruntime不影响飞桨原生profiler的功能使用，我们内部评估调研下专门为Custom Device增加一个通用 runtime 的方案。非常感谢！
