### ISSUE TITLE
matmul精度问题

### ISSUE THREAD

**Issue by Yelrose** [PaddlePaddle/Paddle#54208]
### bug描述 Describe the Bug

paddle的matmul精度有问题

```python
import paddle
q = paddle.to_tensor([1.0], dtype="float32")
k = paddle.to_tensor([-44.54772186], dtype="float32")

print("q", q)
print("k", k)
print("q * k", q * k)
print("q.matmul(k)", q.matmul(k))
print(paddle.allclose(q * k, q.matmul(k)))
```

上面代码，matmul的值不对，输出如下
```python
q Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [1.])
k Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [-44.54772186])
W0530 20:06:54.490236  5973 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.0
W0530 20:06:54.493073  5973 gpu_resources.cc:149] device: 0, cuDNN Version: 8.0.
q * k Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [-44.54772186])
q.matmul(k) Tensor(shape=[1], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [-44.56250000])
Tensor(shape=[], dtype=bool, place=Place(gpu:0), stop_gradient=True,
       False)

```

我的环境如下：

W0530 19:55:36.895370  5780 gpu_resources.cc:119] Please NOTE: device: 5, GPU Compute Capability: 8.0, Driver API Version: 11.4, Runtime API Version: 11.0
W0530 19:55:36.901897  5780 gpu_resources.cc:149] device: 5, cuDNN Version: 8.0.

**Comment by Yelrose** [comment]
加上这个export NVIDIA_TF32_OVERRIDE=0 解决了

**Comment by ZHUI** [comment]
是否推动一下 默认 关闭 TF32 ? 这个对精度的影响很大，很多人在对比精度的时候踩坑了。

如果用户想提速，自己打开即可。

**Comment by zyfncg** [comment]
经沟通确认，NVIDIA_TF32_OVERRIDE并非Paddle提供的Flag，如果关闭会出现性能下降的问题，目前还是倾向于使用默认值，即默认打开。

**Comment by ZHUI** [comment]
> 经沟通确认，NVIDIA_TF32_OVERRIDE并非Paddle提供的Flag，如果关闭会出现性能下降的问题，目前还是倾向于使用默认值，即默认打开。

torch后面也是默认关闭 TF32 的，这个对精度影响很大。
如果性能下降，用户打卡开关即可。
像这个例子的计算，直接出TF32的结果，误差太大了。

可以拉群一起沟通反馈吧。
