### ISSUE TITLE
请问如何自定义优化器？

### ISSUE THREAD

**Issue by xiehuanyi** [PaddlePaddle/Paddle#54211]
### 需求描述 Feature Description

我想实现一下新提出的Lion和Tiger优化器，请问基于Optimizer怎么开发自己的优化器呢？我在论坛上没看到，官方有没有考虑出一下文档？

**Comment by zyfncg** [comment]
目前paddle中的优化器都是以C++算子的形式添加，开发流程见：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_cpp_op_cn.html

具体的运算实现可以参考sgd算子：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/sgd_kernel.cu
