### ISSUE TITLE
pdf的OCR处理失败

### ISSUE THREAD

**Issue by vincenthw86** [PaddlePaddle/Paddle#54238]
### 问题描述 Please describe your issue

我用了pdf2word_0.2.3的exe转一些硕士论文的扫描件pdf，但是结果只是把每一页的图倒转了
以下是原始pdf
[_相关-PECVD分层结构对氢化非晶硅TFT迁移率的影响.pdf](https://github.com/PaddlePaddle/Paddle/files/11610546/_.-PECVD.TFT.pdf)

**Comment by zoooo0820** [comment]
你好，ocr相关的问题，可以在 https://github.com/PaddlePaddle/PaddleOCR/issues 提问下呢
