### ISSUE TITLE
paddle 2.4.2 nn.functional.linear  小数点后4/5位存在diff

### ISSUE THREAD

**Issue by byrsongyuxin** [PaddlePaddle/Paddle#54246]
### bug描述 Describe the Bug

paddle 2.4.2 nn.functional.linear  小数点后4/5位存在diff， 输入及模型参数完全一致，麻烦帮忙看一下，感谢🙏

paddle调用如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/42733639/07fd1c85-686f-4ada-ba52-bf0e0e5c7c35)
输入：
![image](https://github.com/PaddlePaddle/Paddle/assets/42733639/7da63652-64dd-4b6d-a581-a115a2f03dd1)
参数：
![image](https://github.com/PaddlePaddle/Paddle/assets/42733639/3b4049ca-464b-4207-b445-1cc367a55f57)

torch调用如下：
<img width="912" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/42733639/01469ed9-822e-41fb-9539-a16b13a89665">
输入：
<img width="522" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/42733639/fa9b6396-a010-4729-a81f-3bb39c7e9dc6">
参数：
<img width="643" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/42733639/045283e0-7cd5-4ade-924f-15e83c0d67a5">

环境：
paddle 2.4.2
torch 1.12.1

**Comment by zoooo0820** [comment]
复现了下，多次随机生成了同样shape的输入，是可以通过rtol=1e-6的测试的，可能和具体输入值有关系？能否方便提供下复现的输入值或者可复现的random seed呢

**Comment by byrsongyuxin** [comment]
import numpy as np
import torch
import paddle

torch.set_printoptions(precision = 12, sci_mode = False)
paddle.set_printoptions(precision = 12, sci_mode = False)

linea_input_np = np.load('linea_input_np.npy')
linea_weight = np.load('linea_weight.npy')    
linea_bias = np.load('linea_bias.npy')

paddle_out = paddle.nn.functional.linear(paddle.to_tensor(linea_input_np), paddle.to_tensor(linea_weight).transpose([1,0]), paddle.to_tensor(linea_bias))
torch_out = torch.nn.functional.linear(torch.tensor(linea_input_np), torch.tensor(linea_weight), torch.tensor(linea_bias))

print('paddle_out', paddle_out)
print('torch_out', torch_out)

_____________
您好这是我的调用，输入及权重地址如下，麻烦您帮忙check下吧，感谢
wget http://yq01-inf-hic-k8s-a100-aa24-0203.yq01.baidu.com:8990/linea_weight.npy
wget http://yq01-inf-hic-k8s-a100-aa24-0203.yq01.baidu.com:8990/linea_bias.npy
wget http://yq01-inf-hic-k8s-a100-aa24-0203.yq01.baidu.com:8990/linea_input_np.npy

**Comment by zoooo0820** [comment]
你好，我分别使用2.4.2和develop的whl包验证了下这部分数据，其中torch需要转到gpu上计算。
```python
paddle_out = paddle.nn.functional.linear(paddle.to_tensor(linea_input_np), paddle.to_tensor(linea_weight).transpose([1,0]), paddle.to_tensor(linea_bias))
torch_out = torch.nn.functional.linear(torch.tensor(linea_input_np).to('cuda'), torch.tensor(linea_weight).to('cuda'), torch.tensor(linea_bias).to('cuda'))
print(paddle_out)
print(torch_out)np.testing.assert_allclose(paddle_out.numpy(), torch_out.cpu().numpy(), rtol=1e-6)

# 结果如下：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
W0601 02:55:07.649032 12245 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.2, Runtime API Version: 11.2
W0601 02:55:07.654408 12245 gpu_resources.cc:91] device: 0, cuDNN Version: 8.1.
Tensor(shape=[1, 257, 4224], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [[[-0.487682282925, -0.023514121771,  0.073371276259, ...,
          -0.403404682875, -0.011863723397, -0.101633854210],
         [-1.019340634346, -0.116198793054,  0.625149726868, ...,
          -0.032877285033, -0.009718149900,  0.020580982789],
         [-1.082432746887, -0.151376068592,  0.774281799793, ...,
          -0.088918387890, -0.020489584655, -0.003160742577],
         ...,
         [-0.820818662643, -0.024513829499,  0.536564826965, ...,
          -0.049762494862,  0.044990401715, -0.086452625692],
         [-0.980124890804,  0.081208914518,  0.551025032997, ...,
          -0.093053340912, -0.044254992157, -0.039283860475],
         [-0.878791451454, -0.032059367746,  0.506986975670, ...,
           0.005874492228, -0.046247828752,  0.022528287023]]])
tensor([[[-0.487682282925, -0.023514121771,  0.073371276259,  ...,
          -0.403404682875, -0.011863723397, -0.101633854210],
         [-1.019340634346, -0.116198793054,  0.625149726868,  ...,
          -0.032877285033, -0.009718149900,  0.020580982789],
         [-1.082432746887, -0.151376068592,  0.774281799793,  ...,
          -0.088918387890, -0.020489584655, -0.003160742577],
         ...,
         [-0.820818662643, -0.024513829499,  0.536564826965,  ...,
          -0.049762494862,  0.044990401715, -0.086452625692],
         [-0.980124890804,  0.081208914518,  0.551025032997,  ...,
          -0.093053340912, -0.044254992157, -0.039283860475],
         [-0.878791451454, -0.032059367746,  0.506986975670,  ...,
           0.005874492228, -0.046247828752,  0.022528287023]]],
       device='cuda:0')
```
结果是可以通过atol=0, rtol=1e-6的误差检测的。

对比了下上面你给出的结果，torch基本没有差异，但是paddle结果有一定区别。辛苦你也再对比下paddle的结果呢。如果仍然有diff，怀疑和设备有一定关系。可以提供下gpu型号，cuda版本等环境信息。

**Comment by byrsongyuxin** [comment]
我这面测试还是存在diff，我的测试环境如下：
torch 1.12.1+cu113
paddlepaddle-gpu 2.4.2.post112

cuda 11.3, 40G A100

**Comment by zoooo0820** [comment]
same with https://github.com/PaddlePaddle/Paddle/issues/54208
