### ISSUE TITLE
nn.GroupNorm反向传播存在BUG，torch正确。

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#54244]
### bug描述 Describe the Bug

```python
import paddle
model = paddle.nn.GroupNorm(32, 32)
model.train()
x = paddle.randn([4, 32, 32, 32])
out = model(x)
loss = out - 0.001
loss.mean().backward()
print(model.weight.grad)
```
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/2f41c41a-3fa5-4f9f-b877-4043816dad91)

```python
import torch
model = torch.nn.GroupNorm(32, 32).cuda()
model.train()
x = torch.randn([4, 32, 32, 32]).cuda()
out = model(x)
loss = out - 0.001
loss.mean().backward()
print(model.weight.grad)
```
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/01b38718-4910-4888-8418-843b082a7e54)

**Comment by zoooo0820** [comment]
看起来和https://github.com/PaddlePaddle/Paddle/issues/46458 这个问题类似，加上`x.stop_gradient=False`后，可以正确运行

**Comment by JunnYu** [comment]
@zoooo0820 你这里只是临时解决方法，不符合实际应用场景。
例如，在实际使用上，如果我只训练group norm往后的层，那么就无法正常训练。
Bert() -> GroupNorm() ->Linear()-> Conv2D 等等等。
其中Bert的输出是没有梯度的，这时候传递给GroupNorm，也会报错。

还有例如nn.Linear，如果输入的x没有梯度，他也能正常运行。

**Comment by zoooo0820** [comment]
> @zoooo0820 你这里只是临时解决方法，不符合实际应用场景。 例如，在实际使用上，如果我只训练group norm往后的层，那么就无法正常训练。 Bert() -> GroupNorm() ->Linear()-> Conv2D 等等等。 其中Bert的输出是没有梯度的，这时候传递给GroupNorm，也会报错。
> 
> 还有例如nn.Linear，如果输入的x没有梯度，他也能正常运行。

定位了下 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/group_norm_grad_kernel.cu#L294   这里应该和`d_scale/d_bias`一样做空检查。 我同步给对应API负责同学修复下
