### ISSUE TITLE
如何使用  trainer.save_parameter_to_tar(f) 保存下来的参数

### ISSUE THREAD

**Issue by zhipengli0524** [PaddlePaddle/Paddle#5426]
在模型训练好之后，使用trainer.save_parameter_to_tar(f) 保存参数，下一次使用模型的时候，是不是可以直接调用保存好的参数？
请问如何使用？
没有找到相应的例子。

**Comment by lcy-seso** [comment]
Paddle models/book 的例子下面都有预测过程，照做即可。https://github.com/PaddlePaddle/models/tree/develop/text_classification
