### ISSUE TITLE
Can not import paddle core while this file exists

### ISSUE THREAD

**Issue by Ashionnal** [PaddlePaddle/Paddle#54293]
### bug描述 Describe the Bug

系统是Ubuntu20LTS
![3](https://github.com/PaddlePaddle/Paddle/assets/23193694/7056893f-6047-47cb-b72b-bed7eed48a65)
存在GPU
![5](https://github.com/PaddlePaddle/Paddle/assets/23193694/fd729ee2-1182-45c1-9024-1e2b0f51573b)

使用官方的conda安装命令
![0](https://github.com/PaddlePaddle/Paddle/assets/23193694/f6bc1881-407e-40eb-a532-534b7cf9a4e4)
也安装成功
![1](https://github.com/PaddlePaddle/Paddle/assets/23193694/e3b8274c-1060-40cc-87c3-7a6ae3ce0730)

但是导入paddle的时候报错
![2](https://github.com/PaddlePaddle/Paddle/assets/23193694/dee7b207-540c-43b8-ae61-1f9a52f1b2ac)

**Comment by Ashionnal** [comment]
解决了，参考了#48681
![6](https://github.com/PaddlePaddle/Paddle/assets/23193694/c5b65cb6-6571-472f-abb5-9422503c815b)
希望官方能解决这个问题，通过官方安装方式都能报错

**Comment by prkhrv** [comment]
How to resolve this?

**Comment by said46** [comment]
Same issue for me.
