### ISSUE TITLE
paddle.pow与torch.pow计算不一致

### ISSUE THREAD

**Issue by longranger2** [PaddlePaddle/Paddle#54314]
### bug描述 Describe the Bug

torch.pow(x, y)，如果指数是负数，是不支持x是int的

![image](https://github.com/PaddlePaddle/Paddle/assets/52858395/6366d5c8-63fc-4f02-8a89-eaa3b252ab24)

而paddle.pow(x, y)此时是可以进行计算的

<img width="659" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/52858395/3825c7bd-4774-4c0f-b851-cb5cdcb0acd6">

**Comment by luotao1** [comment]
同时 paddle.pow 在 指数是负数的情况下，会出现精度损失的情况：https://github.com/PaddlePaddle/Paddle/pull/51395#discussion_r1212828047

**Comment by Bobholamovic** [comment]
> ### bug描述 Describe the Bug
> torch.pow(x, y)，如果指数是负数，是不支持x是int的
> 
> ![image](https://user-images.githubusercontent.com/52858395/242906898-6366d5c8-63fc-4f02-8a89-eaa3b252ab24.png)
> 
> 而paddle.pow(x, y)此时是可以进行计算的
> 
> <img alt="image" width="659" src="https://user-images.githubusercontent.com/52858395/242907354-3825c7bd-4774-4c0f-b851-cb5cdcb0acd6.png">
> ### 其他补充信息 Additional Supplementary Information
> _No response_

你好，通过`paddle.to_tensor([2], dtype='float32')`创建的Tensor数据类型为float32，这与题目中的文字表述（以及torch的对应例子）不符。
