### ISSUE TITLE
分布式推理

### ISSUE THREAD

**Issue by 0xlyc** [PaddlePaddle/Paddle#54313]
### 请提出你的问题 Please ask your question

hello~想咨询一下paddle目前支持分布式推理么？将模型参数分布在多卡上，多卡共同Infer一次输入。有相关的文档或者demo可以参考么？

**Comment by an1018** [comment]
多卡预测可以参考这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/practices/quick_start/high_level_api.html#shiyongduokajinxingyuce
