### ISSUE TITLE
如何使用profiler工具测试自己的网络的在推理时候的每一层耗时/计算量

### ISSUE THREAD

**Issue by sg-goldrush** [PaddlePaddle/Paddle#54320]
### 请提出你的问题 Please ask your question

import paddle
import paddle.fluid.profiler as profiler
from paddle.vision.models import mobilenet_v1
import numpy as np
import time

model = mobilenet_v1(num_classes=1000)

place = paddle.CUDAPlace(0)  # 使用GPU
exe = paddle.fluid.Executor(place)

# 开启Profiler
profiler.start_profiler("All")
model.eval()

# 运行模型
x = np.random.randn(1, 3, 224, 224).astype(np.float32)
x = paddle.to_tensor(x)
with paddle.fluid.dygraph.guard(place):
    out = model(x)

# 结束Profiler
profiler.stop_profiler("total", "/path/to/profile")

比如以上代码，我这样是可以看出mobilenet_v1 的卷积耗时等，但是如何导入自己的模型进行查看呢？？

**Comment by sg-goldrush** [comment]
我想查看ppyolo tiny的每一层的情况，但是报这个错误。


ValueError: (InvalidArgument) The conv2d Op's Input Variable `Input` contains uninitialized Tensor.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1988)
  [operator < conv2d > error]  [operator < run_program > error]

**Comment by w5688414** [comment]
> 我想查看ppyolo tiny的每一层的情况，但是报这个错误。
> 
> ValueError: (InvalidArgument) The conv2d Op's Input Variable `Input` contains uninitialized Tensor. [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] (at /paddle/paddle/fluid/framework/operator.cc:1988) [operator < conv2d > error] [operator < run_program > error]

您是用的静态图吗？可以尝试使用动态图的profile的API。https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/profiler/Profiler_cn.html#profiler
