### ISSUE TITLE
AssertionError:  'decay_steps' must be a positive integer.

### ISSUE THREAD

**Issue by WesternTrail** [PaddlePaddle/Paddle#54327]
### bug描述 Describe the Bug

用的是ai studio的环境跑的代码，自己的电脑上已经试过，也能成功运行。放到ai studio上就出现这个报错，似乎是Paddle库的原因？？请即使解决

![image](https://github.com/PaddlePaddle/Paddle/assets/28615285/e182eea5-3b35-43a2-b52c-d157d57da2e4)

### 其他补充信息 Additional Supplementary Information
环境如下
![image](https://github.com/PaddlePaddle/Paddle/assets/28615285/280f232e-6df0-4663-851a-f9fd8a4a5cf4)

_No response_

**Comment by 1649759610** [comment]
请验证下自己电脑和aistudio上的paddle和使用到的相关套件版本
