### ISSUE TITLE
有现成的paddle实现的hard triplet loss吗？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/Paddle#54328]
### 请提出你的问题 Please ask your question

triplet loss有了
https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/TripletMarginLoss_en.html#tripletmarginloss
但是hard triplet loss似乎没有实现，这个有增加的打算吗？

找到个pytorch版本的
https://github.com/UKPLab/sentence-transformers/blob/master/sentence_transformers/losses/BatchHardTripletLoss.py

**Comment by 1649759610** [comment]
感谢反馈，我们后续会对此进行评估，也欢迎提供相关PR。
