### ISSUE TITLE
paddle tensor如何进行非连续切片

### ISSUE THREAD

**Issue by bingoyuanybb** [PaddlePaddle/Paddle#54333]
### 问题描述 Please describe your issue

x = paddle.ones(shape=[10, 10, 10, 10])
print(x[[1,6],1,1,:].numpy())
#ValueError: (InvalidArgument) When index contains a list, its length is excepted to 1, but received 4
  [Hint: Expected size == 1, but received size:4 != 1:1.] (at ..\paddle/fluid/pybind/slice_utils.h:246)

#pytoch非常简单就实现了这个功能
x = torch.ones(size=[10, 10, 10, 10])
print(x[[1,6],1,1,:])
#tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

**Comment by 1649759610** [comment]
请参考gather_nd API：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/gather_nd_cn.html#gather-nd
