### ISSUE TITLE
源码编译报错

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/Paddle#54386]
### bug描述 Describe the Bug

[  5%] Built target extern_gloo
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
Traceback (most recent call last):
  File "/home/mitlab/207/Paddle/paddle/fluid/eager/auto_code_generator/generator/eager_gen.py", line 19, in <module>
    from codegen_utils import (
  File "/home/mitlab/207/Paddle/paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py", line 17, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_codegen.dir/build.make:57: paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_codegen] Error 1
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:76908: paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_codegen.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  5%] Performing patch step for 'extern_protobuf'
[  6%] Built target extern_glog
[  6%] Built target ps_py_proto_init
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
fatal: detected dubious ownership in repository at '/home/mitlab/207/Paddle/third_party/protobuf'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/mitlab/207/Paddle/third_party/protobuf
make[2]: *** [CMakeFiles/extern_protobuf.dir/build.make:100: third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-patch] Error 128
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:4580: CMakeFiles/extern_protobuf.dir/all] Error 2
Traceback (most recent call last):
  File "/home/mitlab/207/Paddle/paddle/fluid/eager/auto_code_generator/generator/python_c_gen.py", line 18, in <module>
    from codegen_utils import (
  File "/home/mitlab/207/Paddle/paddle/fluid/eager/auto_code_generator/generator/codegen_utils.py", line 17, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_python_c_codegen.dir/build.make:57: paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_python_c_codegen] Error 1
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:76935: paddle/fluid/eager/auto_code_generator/generator/CMakeFiles/eager_python_c_codegen.dir/all] Error 2
Traceback (most recent call last):
  File "/home/mitlab/207/Paddle/python/paddle/incubate/autograd/generate_op_map.py", line 22, in <module>
[  6%] Built target fleet_proto_init
    import yaml
ModuleNotFoundError: No module named 'yaml'
make[2]: *** [python/CMakeFiles/op_map_codegen.dir/build.make:57: python/CMakeFiles/op_map_codegen] Error 1
make[2]: Leaving directory '/home/mitlab/207/Paddle/build'
make[1]: *** [CMakeFiles/Makefile2:95427: python/CMakeFiles/op_map_codegen.dir/all] Error 2
make[1]: Leaving directory '/home/mitlab/207/Paddle/build'
make: *** [Makefile:130: all] Error 2
[mitlab@localhost build]$ yaml
-bash: yaml: command not found
[mitlab@localhost build]$ python
Python 3.7.9 (default, Mar 13 2023, 15:56:11)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> quit()

### 其他补充信息 Additional Supplementary Information

![WechatIMG1046](https://github.com/PaddlePaddle/Paddle/assets/55450821/929512b0-6c7d-4c24-bf1b-dc8d728abfad)

**Comment by zhaoyinglia** [comment]
你好编译命令可以发一下吗？

**Comment by hitzhu** [comment]
> 你好编译命令可以发一下吗？

cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

make -j8

**Comment by hitzhu** [comment]
> > 你好编译命令可以发一下吗？
> 
> cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF
> 
> make -j8



> 你好编译命令可以发一下吗？

arm cpu
操作系统是麒麟

**Comment by hitzhu** [comment]
> 

在python命令行里面能正常import yaml,编译过程中就找不到，重新安装pyyaml也不行

**Comment by zhaoyinglia** [comment]
可以确认一下编译paddle使用的python和安装yaml的python版本一致吗？
