### ISSUE TITLE
avg_pool2d 不对称padding时，存在bug

### ISSUE THREAD

**Issue by Kevin-XiongC** [PaddlePaddle/Paddle#54404]
### bug描述 Describe the Bug

``` python
import torch
import paddle
import numpy as np
x = np.ones((1,1,8,5)).astype("float32")
t = torch.functional.F.pad(torch.tensor(x),[1,2,1,2])
res_torch = torch.functional.F.avg_pool2d(t,kernel_size=4,padding=0,count_include_pad=True).numpy()
res_paddle = paddle.nn.functional.avg_pool2d(paddle.to_tensor(x),kernel_size=4,padding=[1,2,1,2],exclusive=False).numpy()
```

torch的output
``` bash
array([[0.5625, 0.375 ],
       [0.75  , 0.5   ]], dtype=float32)
```

paddle的ouput
``` bash
array([[0.5625   , 0.5      ],
       [0.75     , 0.6666667]], dtype=float32)
```

![image](https://github.com/PaddlePaddle/Paddle/assets/22584786/a5b93a8f-2083-480c-a569-82ed6bc15b82)
由图所示应该为6/16=0.375

貌似是paddle/phi/kernels/funcs/pooling.cc中没考虑padding是4个元素的情况,算成了6/12=0.5
![image](https://github.com/PaddlePaddle/Paddle/assets/22584786/9003745f-0339-4d65-8d63-26bd00cc75bc)

### 其他补充信息 Additional Supplementary Information

paddle2.4.2
macos

**Comment by Caozhou1995** [comment]
感谢反馈，已收到问题，正在和相关同学确认
