### ISSUE TITLE
Wrong detection while running on GPU (detection on CPU works fine)

### ISSUE THREAD

**Issue by Gokulnath-V** [PaddlePaddle/Paddle#54418]
### 问题描述 Issue Description

I use the Jetson Orin NANO to perform the OCR. I downloaded the paddlepaddle wheel from below link (Jetpack 5.0.2, Python 3.8). And used 'pip install' to install the downloaded wheel.

https://forums.developer.nvidia.com/t/paddlepaddle-for-jetson/242765

And installed paddleocr (v2.6.1.3) using pip. 

When I run '**paddleocr --image_dir path/to/img --lang en --use_gpu false**', i get the expected result.

![Screenshot from 2023-06-07 16-04-23](https://github.com/PaddlePaddle/Paddle/assets/88284164/10872d00-8526-4e56-82fa-f8f1ad0a08b8)

But if I set '**--use_gpu'** to **true**, the result is not good. 

![Screenshot from 2023-06-07 16-06-52](https://github.com/PaddlePaddle/Paddle/assets/88284164/3fad30dc-c761-4bf5-96a1-8fca96882b36)

Could you please suggest me how can I deal with this issue?

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.4.1
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.16.3
Libc version: glibc 2.31
Python version: 3.8.10

CUDA version: 11.4.239
Build cuda_11.4.r11.4/compiler.31294910_0
cuDNN version: 8.4.1
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by thebor1337** [comment]
how to fix this? I have the same issue
