### ISSUE TITLE
算子的序列化规则

### ISSUE THREAD

**Issue by peiwenYe** [PaddlePaddle/Paddle#54421]
### 请提出你的问题 Please ask your question

请问算子定义序列化规则，联结python前端代码和后端c++代码的方法除了使用helper.append_op外还有其他方式吗？
我理解通过helper.append_op中的type参数找到c++中注册的算子名，但rnn算子，我找到了c++的算子注册部分的代码，但没有找到python中使用helper定义序列化规则的代码，请问这部分是通过什么方式从python找到c++实现的？

**Comment by Caozhou1995** [comment]
可以参考最新的算子开发代码：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_cpp_op_cn.html

**Comment by peiwenYe** [comment]
> 可以参考最新的算子开发代码：https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/new_cpp_op_cn.html

收到，请问rnn算子的
![image](https://github.com/PaddlePaddle/Paddle/assets/37332773/e6067cc5-300f-42b1-8fbc-de09dd005208)
这个部分定义是在哪里呢？
从https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/control_flow.py
没有找到
```
append_op(type="rnn",...)
```
类似定义序列化规则的语句

**Comment by Caozhou1995** [comment]
rnn是一个神经网络模型，paddle是用多个基础算子实现它的网络结构。从算子角度来讲，没有单独的名叫rnn的算子
