### ISSUE TITLE
Need to document layers

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5442]
All our layers are currently defined as Python functions in [layers.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/layers.py).  In the future, when we are going to have more layers, we might have more modules.

At the right time, we need to document these layers by adding formal Python function comments, so could Sphinx automatically generate the documentation.

**Comment by kavyasrinet** [comment]
Thanks for creating the issue @wangkuiyi . 
I have a few questions: 
1. Do we add the comments to this file at the moment ?
2. If we do, what would be the preferred way of doing so : 
    1. Add in the beginning of the function, eg:
       ```
        ```
        This function executes the following blob of code.
        ```
        def fn(att):
              <code here>
        ```
    2. Add after function definition, eg:
        ```
        def fn(att):
              ```
               This function executes the following blob of code.
              ```
              <code here>
        ```

**Comment by luotao1** [comment]
As we have [API doc standard](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md) and [a list of API doc jobs](https://github.com/PaddlePaddle/Paddle/issues?q=is:issue%20is:open%20label:documentation%20label:pythonapi) now, this issue could be closed.
