### ISSUE TITLE
cufT Ero at /paddle/paddle/phi/kernels/funcs/cufft_util.h;127

### ISSUE THREAD

**Issue by jb893495492** [PaddlePaddle/Paddle#54426]
### bug描述 Describe the Bug

系统Ubantu 22.04  目前已安装了11.7的cuda和cudnn8.6  base环境直接执行python脚本正常。用conda创建虚拟环境  并在虚拟环境 paddlepaddle-gpu==2.4.1 cudatoolkit=11.7 安装完成后，查看paddle环境提示安装成功，执行python脚本就出错，所有的脚本都是同样的错误。求大佬帮解答一下~ 

Traceback (most recent call last):
File "infer server.py", line 5o, in <module>
predictor=PPASRPredictor(configs=args.configs，
File "/opt/PPASR-develop/ppasr/predict.py", line 89, in__init_ self.predict(audio data=warmup audio,is itn=False)
File "/opt/PPASR-develop/ppasr/predict.py",line 171, in predict audio_feature = self.audio_featurizerfeaturize(audio segment)
File "/0pt/PPASR-develop/ppasr/data_utils/featurizer/audio_featurizer.py",line 64, in featurize return self._compute_fbank(samples=samples
File"/opt/PPASR-develop/ppasr/data_utils/featurizer/audio_featurizer.py",line 131,in _compute_fbank mat=fbank(waveform,
File"/root/anaconda3/envs/paddle_env/lib/python3.8/site-packages/paddleaudio/compliance/kaldi.py"line 468, in fbank spectrum=paddle.fft.rfft(strided input).abs()
File"/root/anaconda3/envs/paddle eny/1b/pvthon3.8/site-packages/paddle/fft.py"line 330, in rfft return fft_r2c(x, n,axis,norm,forward=Trueonesided=Truename=name)
File"/roo/anaconda3/envs/paddle_env/ib/python38/site-packages/paddle/fftpy"line 1443, in fft_r2c out=Cops.fftr2c(xaxesnorm,forwardonesided) OSError:(External)CUFFTerror(5)，
SErrat:Please searc for the efor code(5) on website(https://docsnvidia.com/cuda/cuff/index,htmlecufftresul) to get vidia's officiat solution and advice about cufT Ero at /paddle/paddle/phi/kernels/funcs/cufft_util.h;127)

Ln 12,Col 81(37selected)Spces4UTF8 LF f2 PythonJ.10664-bit

**Comment by Caozhou1995** [comment]
还是环境的问题：https://docs.nvidia.com/cuda/cufft/index.html#:~:text=CUFFT_INTERNAL_ERROR%20%3D%205%2C%20%20//%20%20Driver%20or%20internal%20cuFFT%20library%20error
建议直接在base环境下操作
