### ISSUE TITLE
训练时显存间断增加导致显存溢出out of memory

### ISSUE THREAD

**Issue by sewkyz1** [PaddlePaddle/Paddle#54434]
### 请提出你的问题 Please ask your question

训练时每隔随机的显存会出现上升，每次上升的显存大小相等，最终导致显存溢出。
初步判断问题可能发生在数据经过网络时（尝试过注释掉loss.backward(),optimizer.step(),optimizer.clear_grad()，仍然存在显存增加情况）

**Comment by Caozhou1995** [comment]
建议先在脚本中使用memory_llocated api打印出显存信息进一步的去定位，参考链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/cuda/memory_allocated_cn.html

**Comment by sewkyz1** [comment]
请问这一api和paddle.device.cuda.memory_reserved()有什么区别呢

**Comment by Caozhou1995** [comment]
没有什么大的区别，都可以用来分析显存占用
