### ISSUE TITLE
PaddlePaddle 1.8 源码编译报错

### ISSUE THREAD

**Issue by myuniqueplayground** [PaddlePaddle/Paddle#54430]
### 问题描述 Please describe your issue

在对PaddlePaddle 1.8版本进行源码编译时，最后遇到了这个错误。请问应该怎样解决，谢谢！
这段代码之前输入的指令是：make -j$(nproc)
编译环境：Ubuntu 22.04.2 上的 Docker，编译的PaddlePaddle 1.8适用于Python 3.5。

![Screenshot_20230607_193121](https://github.com/PaddlePaddle/Paddle/assets/68016500/4df78ba9-5851-4190-98d3-c69e740612dd)

**Comment by Caozhou1995** [comment]
先确认所要编译的版本是否和当前系统环境匹配，参考：https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-37-V1.8

**Comment by myuniqueplayground** [comment]
Docker里的环境的截图如下：

![image](https://github.com/PaddlePaddle/Paddle/assets/68016500/e8dc6bfe-ee6f-4b97-a9b9-a0e6cda19858)

这个是官网上的安装说明：

![image](https://github.com/PaddlePaddle/Paddle/assets/68016500/f32f96db-ace2-494a-822e-9d98114b7541)

Docker里的环境应该是与宿主机的环境相互隔离的，Docker的环境应该是满足要求的。但是重新编译了一下，还是报同样的错误。请问应该怎样解决，谢谢！

**Comment by zhanglirong1999** [comment]
一样的报错，换了一台机子就好了。但是两台都是Ubuntu18.04。希望官方帮忙看一下
