### ISSUE TITLE
Paddle生态中对推理结果与视频流的帧同步有支持吗？

### ISSUE THREAD

**Issue by hangvane** [PaddlePaddle/Paddle#54446]
### 请提出你的问题 Please ask your question

在生产环境部署视频流的目标检测模型，请问paddle生态有对推理结果与视频流的帧同步有相关支持吗？

直接在推理设备上进行推理结果的硬叠加，这个我发现PP-Human、PP-Vehicle有提供`--pushurl`进行rtsp输出，基于[rtsp-simple-server](https://github.com/aler9/rtsp-simple-server)。类似的还有NVIDIA生态的deepsteam等。

但有些边缘推理设备性能较差，例如RK3588等，在上面进行视频流叠加会影响推理性能。基于rtsp-simple-server的推流也比deepstream占用更多的RAM CPU资源。另外很多视频流的前端播放模块也是支持软叠加的，收到推理结果后实时绘制到视频流上，而无需硬叠加视频流。

问题是软叠加如何进行时间同步，由于不是推理侧串行处理视频流，难以保证推理结果与视频前端播放模块的时间同步，特别是在推理速度不及视频流帧率的情况下处理更加复杂。

请问Paddle生态下有相应的解决方案或最佳实践吗？抱歉我甚至不清楚这个问题的关键词是什么，百度谷歌多次无果。

**Comment by andyjiang1116** [comment]
你好，这个问题可以到[PaddleDetection](https://github.com/PaddlePaddle/PaddleDetection)的repo下面进行提问
