### ISSUE TITLE
有没朋友能提供一个已经编译好的cpu的debug版本?

### ISSUE THREAD

**Issue by weedsacc** [PaddlePaddle/Paddle#54444]
### 请提出你的问题 Please ask your question

我的电脑太破了,编译几个小时卡死机了,没法编译..
有好人提供能调试的debug版本吗?c++接口cpu的

**Comment by andyjiang1116** [comment]
建议在自己机器上进行编译，否则会出现依赖库和机器环境配置不匹配的问题

**Comment by Ligoml** [comment]
如果缺乏本地编译环境，可以考虑申请aistudio提供的云上开发环境：https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions#%E9%A3%9E%E6%A1%A8%E7%BA%BF%E4%B8%8A%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83ai-studio
