### ISSUE TITLE
Test error "Insufficient GPU memory to allocation."

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#5446]
I run test using "ctest -j6" and got this error for some tests. How much memory do we use for tests? Is it possible to use less memory for each tests so that tests can run in parallel?

**Comment by QiJune** [comment]
Currently, the buddy allocator will occupy all available GPU memory by default. We can set a gflags in env variable to reduce GPU memory consuming.
```
FLAGS_fraction_of_gpu_memory_to_use=0.15
```

**Comment by emailweixu** [comment]
Still got "Insufficient GPU memory to allocation." even using FLAGS_fraction_of_gpu_memory_to_use=0.1

FLAGS_fraction_of_gpu_memory_to_use=0.1 ctest -I 0,0,0,161,171,181,191 -j6

**Comment by QiJune** [comment]
Our GPU memory allocation policy has been updated in #6159 yesterday. Could you please update to the latest code？
