### ISSUE TITLE
现有的triplet_margin_loss是需要自己区分anchor、positive、negative

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/Paddle#54485]
### 请提出你的问题 Please ask your question

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/triplet_margin_loss_cn.html
api如上面的链接所示

按我的想法，就提供输入（batch，feature）和label（batch，），然后内部由loss实现anchor、positive、negative的分组不是更方便使用？

**Comment by shiyutang** [comment]
你好，作为损失函数的接口需要传入的是损失计算对象，如果传入标签会将损失和输入数据的特性进行耦合，不利于代码的独立性。如果你有label需要区分正负样本，可以使用index_select对feature 基于label数值进行分组后传入损失函数。
