### ISSUE TITLE
pdopt模型怎样导出为paddle inference？

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/Paddle#54484]
### 问题描述 Please describe your issue

大礼包里面有一个手写识别模型，要导出paddle inference模型，没有yml文件怎么办？哪里有？
![image](https://github.com/PaddlePaddle/Paddle/assets/40328063/f0930a55-29f6-4378-983b-ae53eb96065d)

**Comment by WilliamQf-AI** [comment]
或者说要怎样量化成pdmodel模型？

**Comment by andyjiang1116** [comment]
你好，配置文件使用[v3蒸馏配置](https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/configs/rec/PP-OCRv3/ch_PP-OCRv3_rec_distillation.yml)即可

**Comment by WilliamQf-AI** [comment]
谢谢大佬们，问题解决啦

**Comment by WilliamQf-AI** [comment]
执行如下命令：
python3 tools/export_model.py -c ./inference_model/case_handwrite/ch_PP-OCRv3_rec_distillation.yml -o Global.pretrained_model=./inference_model/case_handwrite/best_accuracy Global.save_inference_dir=./inference_model/1/
