### ISSUE TITLE
PaddleX已经2年没有更新

### ISSUE THREAD

**Issue by dilsm56-github** [PaddlePaddle/Paddle#54515]
### 请提出你的问题 Please ask your question

PaddleX已经2年没有更新了，难道百度的一众大佬们打算放弃了PaddleX了吗，我现在手头上有个项目，用你们现有的PaddleX2.0可以训练，但是部署遇到很多问题，特别是我现在用的30系列的显卡，在CUDA11.6的文件配置就一直配置不成功，加载你们的那个PaddleX上面显示的CUDA的版本信息跟我电脑上面的使用的CUDA不一致，这些你们都不打算更新了吗，部署烂尾的问题，真的觉得太可惜了啊

**Comment by lailuboy** [comment]
请问是用PaddleX2.0训练的模型，想在30系列的显卡上部署是吗？具体部署方式（Python or C++）以及配置不成功的错误提示请发一下。

**Comment by dilsm56-github** [comment]
我是配置好了给C#调用的，但是怎么尝试都不成功,以下就是我配置时候选的各程序的情况
我的显卡类型【NVIDIA GeForce RTX 3050 Laptop GPU】,系统win10专业版

CMake 3.18.5,
paddle_inference(官网网站下载的)11.6最新版,
TensorRT-8.4.1.5.Windows10.x86_64.cuda-11.6.cudnn8.4,
cuda_11.6.2_511.65_windows,
cudnn-windows-x86_64-8.4.1.50_cuda11.6-archive,
PaddleX-develop(官方的)，
opencv-3.4.6-vc14_vc15.exe，
![1686619475855](https://github.com/PaddlePaddle/Paddle/assets/134047873/8107c9f9-7801-4be4-9393-92b1857e9b0d)
![1686621233888](https://github.com/PaddlePaddle/Paddle/assets/134047873/c422c65a-3db7-4d2b-888a-b8730241723e)

**Comment by dilsm56-github** [comment]
部署完成后得到的dll放在你们提供的C#Demo中验证的时候一直提示，不能加载model_infer.dll库文件啊

**Comment by lailuboy** [comment]
那就是编译可以成功，加载DLL失败了。可以把加载DLL失败的错误信息抛出来看下详细信息。或者在对应时间的操作系统日志->应用日志中的错误信息。一般来说可能是有依赖DLL加载失败。可以用C调用下DLL看是否有异常。
另外看下paddle_inference取的版本，30显卡cuda11.2也是可以的，使用2.3.1的版本 cuda11.2 编译看看是否正常。

**Comment by dilsm56-github** [comment]
亲，可以列出一份程序对应的列表清单吗？我就按照你给出的清单去配置对应的程序，这样可以增加成功的概率，谢谢！

**Comment by dilsm56-github** [comment]
亲，可以列出一份程序对应的列表清单吗，像我上面列出的清单一样，麻烦了，我就按照你给出的清单去配置对应的程序，这样可以增加成功的概率，谢谢！

**Comment by lailuboy** [comment]
C#的示例是由是社区开发者提供，这里可以参考：https://www.aweisite.site/posts/5617c6c1.html
影响模型推理的主要是预测库paddle_inference，建议选择2.3.1
