### ISSUE TITLE
希望AI studio支持paddle2.4.2版本，目前最新是paddle2.4.1

### ISSUE THREAD

**Issue by LDX17** [PaddlePaddle/Paddle#54532]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by zmxdream** [comment]
您好，飞桨官网6月底会上线2.5正式版本，ai studio也会同步更新
