### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by MaDFolking** [PaddlePaddle/Paddle#54534]
### 需求描述 Feature Description

我们是本地化场景很多，无法联网，python环境为3.7.0，cuda为11.7，需要paddle,paddle-gpu,paddlenlp的一套whl依赖包，针对python3.7.0和cuda11.7版本的场景，我测试过依赖包实在太多，而且依赖包里还有其他依赖包实在太麻烦，所以想官方给我提供一个whl包组合。

**Comment by MaDFolking** [comment]
忘记说了，paddle和paddle-gpu是2.4.2，paddlenlp是2.5.2，python是3.7.0，cuda是11.7。这个版本官网是对应的，请求给出他们的所有whl依赖包哈。

**Comment by zmxdream** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排对本地安装的评估，未来有计划尽快回复

**Comment by XieYunshen** [comment]
可以使用`python -m pip download paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`在一台可以联网的机器中下载飞桨及依赖的安装包，然后copy使用就可以了
