### ISSUE TITLE
希望支持mac m2芯片下面使用docker安装

### ISSUE THREAD

**Issue by ouzhou** [PaddlePaddle/Paddle#54530]
### 需求描述 Feature Description

目前在m2芯片下docker安装的是amd64的，无法运行，期望支持arm64/aarch64的镜像

**Comment by zmxdream** [comment]
您好，您的反馈对产品非常有价值，我们内部会安排评估，未来有计划尽快回

**Comment by ajayghiyad** [comment]
@ouzhou 
Here is my solution 
had similar situation
docker based on ubuntu image
https://github.com/PaddlePaddle/Paddle/issues/54531#issuecomment-1619601905
