### ISSUE TITLE
Dataloader 训练报错问题

### ISSUE THREAD

**Issue by HydrogenSulfate** [PaddlePaddle/Paddle#54546]
### bug描述 Describe the Bug

类似问题 #41635 

报错信息如下：

![image](https://github.com/PaddlePaddle/Paddle/assets/23737287/ddd6fd94-dd9f-40b2-8c05-ab208eabb705)

当 num_workers > 0 的时候，就会出现这个问题，导致频繁出现训练启动半小时或几小时后报错中断的情况，而且ctrl + c 无法中断，只能 ctrl+z 后 kill %1 杀死进程

提了一个PR，但是不知道这样对不对：#54498

**Comment by dingjiaweiww** [comment]
你提交的pr 已经合入，感谢你的参与～
