### ISSUE TITLE
Compiling issue in Ubuntu 22.04

### ISSUE THREAD

**Issue by pkuppusamy77** [PaddlePaddle/Paddle#54596]
### 问题描述 Issue Description

I tried to compile the paddle in Ubuntu 22.04 in both aarch64 and x64 platform.
It gave a below error

`FAILED: third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build third_party/install/protobuf/lib/libprotobuf.a third_party/install/protobuf/lib/libprotobuf-lite.a third_party/install/protobuf/lib/libprotoc.a third_party/install/protobuf/bin/protoc /home/prabhumk/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build /home/prabhumk/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a /home/prabhumk/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a /home/prabhumk/Paddle/build/third_party/install/protobuf/lib/libprotoc.a /home/prabhumk/Paddle/build/third_party/install/protobuf/bin/protoc 
cd /home/prabhumk/Paddle/build/third_party/protobuf/src/extern_protobuf-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /home/prabhumk/Paddle/build/third_party/protobuf/src/extern_protobuf-stamp/extern_protobuf-build
`

` |               is_invocable_v<const _Compare&, const _Key&, const _Key&>,
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/c++/11/bits/stl_tree.h:770:15: note: ‘std::is_invocable_v<const google::protobuf::compiler::java::{anonymous}::FieldDescriptorCompare&, const google::protobuf::FieldDescriptor* const&, const google::protobuf::FieldDescriptor* const&>’ evaluates to false
gmake[2]: *** [CMakeFiles/libprotoc.dir/build.make:636: CMakeFiles/libprotoc.dir/home/prabhumk/Paddle/build/third_party/protobuf/src/extern_protobuf/src/google/protobuf/compiler/java/java_file.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:141: CMakeFiles/libprotoc.dir/all] Error 2
gmake: *** [Makefile:136: all] Error 2
`
$ /usr/bin/protoc --version
libprotoc 3.12.4

$gcc --version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0

Regards
Prabhu M K

### 版本&环境信息 Version & Environment Information

Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 22.04
GCC version: (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0
Clang version: N/A
CMake version: version 3.22.1
Libc version: glibc 2.35
Python version: 3.10.6

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A

**Comment by risemeup1** [comment]
把java_file.cc里的 bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2){改为
  bool operator ()(const FieldDescriptor* f1, const FieldDescriptor* f2)const {

**Comment by pkuppusamy77** [comment]
Thank you
