### ISSUE TITLE
表格识别数据集转换

### ISSUE THREAD

**Issue by 1078755567** [PaddlePaddle/Paddle#54598]
### 请提出你的问题 Please ask your question

paddleocr表格识别部分。数据集使用WTW，voc格式  怎么转换为所需要的带标注txt？   文档中只有【需要进行转换后才能用[pubtab_dataset.py](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppocr/data/pubtab_dataset.py)加载】     但是没说明细节。怎么使用pubtab_dataset.py)加载的过程是什么。
我把voc用x2coco转换为coco了，但下一步该做啥？

**Comment by andyjiang1116** [comment]
表格识别数据集准备可以参考文档https://github.com/PaddlePaddle/PaddleOCR/blob/dygraph/doc/doc_ch/table_recognition.md#11-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%A0%BC%E5%BC%8F

**Comment by nissansz** [comment]
转换好了吗？怎么训练？
