### ISSUE TITLE
PR-CI-Clone job need to update submodule again after checkout to PR branch

### ISSUE THREAD

**Issue by YangQun1** [PaddlePaddle/Paddle#54612]
### bug描述 Describe the Bug

根据 PR-CI-Clone job的log，job执行时会先clone develop branch，然后update submodule，之后再checkout 到PR branch。

但如果developer在PR branch中更新了submodule的commmit，则CI Clone job需要在checkout之后再次update submodule，否则build阶段会直接使用develop branch的submodule version，进而发生编译错误。

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8595533/job/23003342

**Comment by YangQun1** [comment]
cc @xinyu-intel @yaomichael

**Comment by risemeup1** [comment]
> 之后再checkout 到PR branch。

我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题

**Comment by xinyu-intel** [comment]
> > 之后再checkout 到PR branch。
> 
> 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题

git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。

**Comment by risemeup1** [comment]
> > > 之后再checkout 到PR branch。
> > 
> > 
> > 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题
> 
> git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。

我们的setup.py和third_party.cmake都有这个操作的，你可以仓库代理搜下git submodue就看到了

**Comment by xinyu-intel** [comment]
@

> > > > 之后再checkout 到PR branch。
> > > 
> > > 
> > > 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题
> > 
> > 
> > git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。
> 
> 我们的setup.py和third_party.cmake都有这个操作的，你可以仓库代理搜下git submodue就看到了

WITH_SETUP_INSTALL 这个cmake var是在CI里关掉的吗？

https://github.com/PaddlePaddle/Paddle/blob/develop/setup.py#L1637 setup.py里面是说文件夹是empty的时候才会更新submodule，但是这个时候submodule已经是develop branch的状态了，不是空目录，所以不会切换到PR branch的版本上。

**Comment by xinyu-intel** [comment]
https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8595585/job/23003410 这个build job里，WITH_SETUP_INSTALL是打开的所以不会走到third_party.cmake里，所以结合上一条comments，还是会有问题。

**Comment by risemeup1** [comment]
> @
> 
> > > > > 之后再checkout 到PR branch。
> > > > 
> > > > 
> > > > 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题
> > > 
> > > 
> > > git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。
> > 
> > 
> > 我们的setup.py和third_party.cmake都有这个操作的，你可以仓库代理搜下git submodue就看到了
> 
> WITH_SETUP_INSTALL 这个cmake var是在CI里关掉的吗？
> 
> https://github.com/PaddlePaddle/Paddle/blob/develop/setup.py#L1637 setup.py里面是说文件夹是empty的时候才会更新submodule，但是这个时候submodule已经是develop branch的状态了，不是空目录，所以不会切换到PR branch的版本上。

ok，理解了，我去做个实验测试下，如果有问题尽快修复

**Comment by risemeup1** [comment]
> > @
> > > > > > 之后再checkout 到PR branch。
> > > > > 
> > > > > 
> > > > > 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题
> > > > 
> > > > 
> > > > git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。
> > > 
> > > 
> > > 我们的setup.py和third_party.cmake都有这个操作的，你可以仓库代理搜下git submodue就看到了
> > 
> > 
> > WITH_SETUP_INSTALL 这个cmake var是在CI里关掉的吗？
> > https://github.com/PaddlePaddle/Paddle/blob/develop/setup.py#L1637 setup.py里面是说文件夹是empty的时候才会更新submodule，但是这个时候submodule已经是develop branch的状态了，不是空目录，所以不会切换到PR branch的版本上。
> 
> ok，理解了，我去做个实验测试下，如果有问题尽快修复

的确有这个问题，明天让我同事改一下CI插件就好了，明天rerun下

**Comment by risemeup1** [comment]
> > > @
> > > > > > > 之后再checkout 到PR branch。
> > > > > > 
> > > > > > 
> > > > > > 我们在build的时候，会重新执行git pull upstream develop的操作，可以解决问题
> > > > > 
> > > > > 
> > > > > git pull upstream develop 只会将PR branch rebase against develop branch，还是需要再执行git submodule update --init --recursive将submodule切换到PR branch指定的版本上的。
> > > > 
> > > > 
> > > > 我们的setup.py和third_party.cmake都有这个操作的，你可以仓库代理搜下git submodue就看到了
> > > 
> > > 
> > > WITH_SETUP_INSTALL 这个cmake var是在CI里关掉的吗？
> > > https://github.com/PaddlePaddle/Paddle/blob/develop/setup.py#L1637 setup.py里面是说文件夹是empty的时候才会更新submodule，但是这个时候submodule已经是develop branch的状态了，不是空目录，所以不会切换到PR branch的版本上。
> > 
> > 
> > ok，理解了，我去做个实验测试下，如果有问题尽快修复
> 
> 的确有这个问题，明天让我同事改一下CI插件就好了，明天rerun下

rerun吧，已改

**Comment by xinyu-intel** [comment]
works now.

**Comment by xinyu-intel** [comment]
@risemeup1 Hi, looks like build job https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8622223/stage/14161165/0?jump=latestJob in #52463 failed again due to the wrong submodule version. Can you please help on checking it?

**Comment by yaomichael** [comment]
@weishengying @qingqing01 请帮忙催催

**Comment by YangQun1** [comment]
@risemeup1 According to the build log, it seems to have two round of build ? The first round of build successes, then the repo is checkout to develop branch again and run the second round of build.
But before running the second round of build, we need to update the submodule again?

```
2023-06-18 14:34:04 + git checkout -b develop_base_pr upstream/develop
2023-06-18 14:34:04 Switched to a new branch 'develop_base_pr'
2023-06-18 14:34:04 M	third_party/mkldnn
```

**Comment by risemeup1** [comment]
> @risemeup1 Hi, looks like build job https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8622223/stage/14161165/0?jump=latestJob in #52463 failed again due to the wrong submodule version. Can you please help on checking it?

ok，我下午帮你看看，看了回复你

**Comment by risemeup1** [comment]
> @risemeup1 Hi, looks like build job https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8622223/stage/14161165/0?jump=latestJob in #52463 failed again due to the wrong submodule version. Can you please help on checking it?

这个急嘛，上午有些忙，我今天看了回复你吧

**Comment by yaomichael** [comment]
@risemeup1 今天千万看一下。因为 #52463 这个规模大，非常容易和别的PR产生冲突，导致无谓的不停解决冲突，重新跑CI。而每次CI都会出不同的错误，找不同的人。所以想尽快merge，一劳永逸。拜托！

**Comment by risemeup1** [comment]
> @risemeup1 今天千万看一下。因为 #52463 这个规模大，非常容易和别的PR产生冲突，导致无谓的不停解决冲突，重新跑CI。而每次CI都会出不同的错误，找不同的人。所以想尽快merge，一劳永逸。拜托！

好的，我下午看看，然后看完第一时间联系你

**Comment by risemeup1** [comment]
> @risemeup1 According to the build log, it seems to have two round of build ? The first round of build successes, then the repo is checkout to develop branch again and run the second round of build. But before running the second round of build, we need to update the submodule again?
> 
> ```
> 2023-06-18 14:34:04 + git checkout -b develop_base_pr upstream/develop
> 2023-06-18 14:34:04 Switched to a new branch 'develop_base_pr'
> 2023-06-18 14:34:04 M	third_party/mkldnn
> ```

已反馈，今天应该可以修复这个问题

**Comment by risemeup1** [comment]
> @risemeup1 Hi, looks like build job https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/8622223/stage/14161165/0?jump=latestJob in #52463 failed again due to the wrong submodule version. Can you please help on checking it?

https://github.com/PaddlePaddle/Paddle/pull/54735 拉这个PR试一下
