### ISSUE TITLE
在jetson nano下安装wheel, 版本都正确，但报whl is not a supported wheel on this platform

### ISSUE THREAD

**Issue by 23michael45** [PaddlePaddle/Paddle#54631]
### 问题描述 Issue Description

在jetson nano下安装wheel, 版本都正确，但报whl is not a supported wheel on this platform

jetpack 4.6.1   python 3.7.1

Jetpack4.6.1：nv_jetson-cuda10.2-trt8.2-nano		[paddlepaddle_gpu-2.4.2-cp37-cp37m-linux_aarch64.whl](https://paddle-inference-lib.bj.bcebos.com/2.4.2/python/Jetson/jetpack4.6.1_gcc7.5/nano/paddlepaddle_gpu-2.4.2-cp37-cp37m-linux_aarch64.whl)

安装的是这个版本的whl

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：2.4.2
Jetson Nano ,JetPack 4.6.1
CPU（可选）：ARM
GPU：cuda10.2
系统环境：ubuntu18.04
Python版本python 3.7.1。

**Comment by zhengqiwen1997** [comment]
根据https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
![image](https://github.com/PaddlePaddle/Paddle/assets/118182234/92d9429b-bfd6-4d19-8baf-026594f1b9b3)
您可以试一下看看输出的是不是如图所示的架构

**Comment by 23michael45** [comment]
按上面操作，打印出来是：
64bit
aarch64

**Comment by 23michael45** [comment]
我是在nvidia的jetson nano上安装的，是arm架构，我是从https://paddleinference.paddlepaddle.org.cn/user_guides/download_lib.html这里，下载的

**Comment by chalsliu** [comment]
1、是否修改了文件名
2、可以试试python3.7 -m pip install paddlepaddle_gpu-2.4.2-cp37-cp37m-linux_aarch64.whl
