### ISSUE TITLE
在线预估时，如何仅将最后一层的inference放到线上，其余部分在线下完成

### ISSUE THREAD

**Issue by hikkinight** [PaddlePaddle/Paddle#5464]
背景类似demo中的电影推荐任务。为了性能考虑我们想尝试下如下图这种半全连接的网络。
线上预估的步骤是：
1、user_fc_layer在线上检索时只需计算一次得到
2、item_fc_layer可以多次查表得到
3、last_fc_layer因为是user_fc_layer和item_fc_layer concat后全连激活得来，因此需要在线上做N（N是候选item数量）次激活函数计算得到；
4、对last_fc_layer进行sigmod得到预估值

问题来了，我们如何在线上完成3和4两个步骤呢？即给定user_fc_layer和item_fc_layer情况下，如何得到last_fc_layer和最后的预估值呢？毕竟这个场景下不是原始的input，也就不能直接调用paddle c++ inference的api。

我能想到的方案：
因为paddle现在训练得到的模型文件是分层保留成二进的。通过反解last_fc_layer的模型文件，得到权重后在线上完成激活函数的计算。

有没有更好的方法？另外如果要反解模型文件的话有没有工具呢？

<img width="783" alt="default" src="https://user-images.githubusercontent.com/1262600/32530564-7f1e874c-c404-11e7-815a-1aa88e1d6bbc.png">

**Comment by hikkinight** [comment]
<img width="879" alt="default" src="https://user-images.githubusercontent.com/1262600/32530467-eba0960e-c403-11e7-9ef6-fc5636163529.png">

**Comment by typhoonzero** [comment]
> 因为paddle现在训练得到的模型文件是分层保留成二进的。

我理解简单点处理的话，和你说的方法类似。capi inferenc需要layer配置和parameters。parameters可以很容易通过解压参数输出，然后只保留`last_fc_layer`在重新打包；layer配置capi是读取proto格式的，可以通过写一个只包含`last_fc_layer`，并正确配置这个层的输入，然后把这个layer配置使用[这里](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md#convert-configuration-file-to-protobuf-binary)的方法导出成proto格式。然后使用capi inference最后一层。

**Comment by hikkinight** [comment]
> parameters可以很容易通过解压参数输出，然后只保留last_fc_layer在重新打包
感谢回复。其他部分看懂了，请问这个步骤的命令是哪个？

**Comment by hikkinight** [comment]
> parameters可以很容易通过解压参数输出，然后只保留last_fc_layer在重新打包  <
感谢回复。其他部分看懂了，请问哪个命令能完成这两个操作。

**Comment by hikkinight** [comment]
> capi inferenc需要layer配置和parameters。parameters可以很容易通过解压参数输出，然后只保留last_fc_layer在重新打包

感谢回复。其他部分看懂了，请问哪个命令能完成这两个操作。

**Comment by hikkinight** [comment]
> parameters可以很容易通过解压参数输出，然后只保留last_fc_layer在重新打包

感谢回复。其他看懂了，请问哪个命令能完成这两部操作。

**Comment by typhoonzero** [comment]
`gunzip`或者`tar xzf`解压训练得到的模型输出，里面应该有每个layer的参数的proto文件，删掉其他的，只保留`last_fc_layer`层相关的文件，然后重新打包。

**Comment by hikkinight** [comment]
ok，多谢了

**Comment by leidaxia** [comment]
> 问题来了，我们如何在线上完成3和4两个步骤呢？即给定user_fc_layer和item_fc_layer情况下，如何得到last_fc_layer和最后的预估值呢？毕竟这个场景下不是原始的input，也就不能直接调用paddle c++ inference的api。

hello,  我当前也遇到类似问题，请问这个你是如何处理的
