### ISSUE TITLE
花卉数据自定义数据训练提示 Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 推出训练！

### ISSUE THREAD

**Issue by Ihuzb** [PaddlePaddle/Paddle#5466]
按照“http://models.paddlepaddle.org/2017/05/10/image-classification-README.html” 里的模型训练花卉图片分类模型，使用自定义数据集运行的时候，提示：
F1108 12:51:54.599757  4167 Allocator.h:51] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f64a62d818d  google::LogMessage::Fail()
    @     0x7f64a62da4d8  google::LogMessage::SendToLog()
    @     0x7f64a62d7c9b  google::LogMessage::Flush()
    @     0x7f64a62db3ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f64a6204031  paddle::CpuAllocator::alloc()
    @     0x7f64a60e2078  paddle::PoolAllocator::alloc()
    @     0x7f64a6090985  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7f64a609fb83  paddle::CpuMatrix::CpuMatrix()
    @     0x7f64a609fcee  paddle::Matrix::create()
    @     0x7f64a60b2c18  paddle::Matrix::resizeOrCreate()
    @     0x7f64a5eed663  paddle::Layer::resetSpecifyOutput()
    @     0x7f64a5eed892  paddle::Layer::resetOutput()
    @     0x7f64a5ecb078  paddle::ExpandConvLayer::forward()
    @     0x7f64a5ffb203  paddle::NeuralNetwork::forward()
    @     0x7f64a62a7bb0  GradientMachine::forwardBackward()
    @     0x7f64a5e38364  _wrap_GradientMachine_forwardBackward
    @           0x4cb45e  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca8d1  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4ca099  PyEval_EvalFrameEx
    @           0x4c2765  PyEval_EvalCodeEx
    @           0x4c2509  PyEval_EvalCode
    @           0x4f1def  (unknown)
    @           0x4ec652  PyRun_FileExFlags
    @           0x4eae31  PyRun_SimpleFileExFlags
    @           0x49e14a  Py_Main
    @     0x7f64a96f9830  __libc_start_main
    @           0x49d9d9  _start
    @              (nil)  (unknown)
bash: line 1:  4167 Aborted                 (core dumped) env "PYTHONUNBUFFERED"="1" "PYTHONPATH"="/home/showme/python" "PYCHARM_HOSTED"="1" "JETBRAINS_REMOTE_RUN"="1" "PYTHONIOENCODING"="UTF-8" /usr/bin/python2.7 -u /home/showme/python/ceshi.py

**Comment by typhoonzero** [comment]
应该是内存不足。请确保机器有足够的空闲内存。

**Comment by 466821202** [comment]
如何自定义数据,求指教啊！
