### ISSUE TITLE
k8s单机训练，Unable to mount volumes for pod

### ISSUE THREAD

**Issue by yyydido** [PaddlePaddle/Paddle#5468]
参考链接[http://doc.paddlepaddle.org/doc_cn/howto/usage/k8s/k8s_cn.html](url)
YAML文件：
![default](https://user-images.githubusercontent.com/26373884/32533237-80dd3d90-c48a-11e7-9a26-0cb8b9bf4f62.png)
Unable to mount volumes for pod：
![mount](https://user-images.githubusercontent.com/26373884/32533249-8fd85e92-c48a-11e7-9a04-111efd0c2401.png)
挂载失败是什么原因导致？

**Comment by typhoonzero** [comment]
> 挂载失败是什么原因导致？

请确认volumes定义的路径`/atlas/home/....`这个路径在host上存在

**Comment by yyydido** [comment]
![1111](https://user-images.githubusercontent.com/26373884/32534721-bf84c912-c491-11e7-92ba-8b5e4e876203.png)
存在的

**Comment by typhoonzero** [comment]
这个问题我理解属于k8s集群的问题。hostpath挂载失败，无非就是目录不存在之类的。如果是多个node那么需要每个node有这个路径，如果你的集群是在虚拟机里，要确定目录是在虚拟机里。

**Comment by yyydido** [comment]
@typhoonzero 路径没问题的，所有node节点都是通过nfs挂载的同一个目录。

**Comment by yyydido** [comment]
@typhoonzero 还有什么可能的原因？
Unable to mount volumes for pod

**Comment by typhoonzero** [comment]
我不确定，你可以搜索下k8s的相关文档，或者私下交流。这个issue和paddle关系比较小我先关闭了。
