### ISSUE TITLE
Build failure while extern_protobuf is getting constructed

### ISSUE THREAD

**Issue by KaviyaSubramanian706** [PaddlePaddle/Paddle#54697]
### 问题描述 Issue Description

After following the native installation steps given in [https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile.html](url) in raspberry pi 64 bit architecture without docker
The build failed while the protobuf was getting built

Attaching the error from terminal

Scanning dependencies of target cryptopp-static
Scanning dependencies of target cryptopp-shared
[100%] Linking CXX shared library libcryptopp.so
[100%] Linking CXX static library libcryptopp.a
[100%] Built target cryptopp-static
[100%] Built target cryptopp-shared
[  3%] Performing install step for 'extern_cryptopp'
-- extern_cryptopp install command succeeded.  See also /home/pi/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-install-*.log
[  3%] Completed 'extern_cryptopp'
[  3%] Built target extern_cryptopp
make: *** [Makefile:149: all] Error 2

Also for additional info,the node files on /home/pi/Paddle/paddle/fluid/eager/api/generated/fluid_generated/nodes remain empty ,if thats useful.

### 版本&环境信息 Version & Environment Information

Paddle version: N/A
Paddle With CUDA: N/A

OS: debian 11
GCC version: (Debian 10.2.1-6) 10.2.1 20210110
Clang version: 11.0.1-2
CMake version: version 3.18.4
Libc version: glibc 2.31
Python version: 3.9.2

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A

**Comment by wuyefeilin** [comment]
可以看一下安装教程：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
如果需要编译安装请参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html

**Comment by KaviyaSubramanian706** [comment]
This is the same link I followed for compile and install for getting c++ library and header files..where I was stuck at make .

**Comment by wuyefeilin** [comment]
建议使用docker编译，以免环境依耐出问题

**Comment by KaviyaSubramanian706** [comment]
Ok I will try that
