### ISSUE TITLE
module 'paddlex.cv.transforms.cls_transforms' has no attribute 'Normailze'

### ISSUE THREAD

**Issue by uesrs** [PaddlePaddle/Paddle#54691]
### bug描述 Describe the Bug

#导入库
import matplotlib
matplotlib.use('Agg')
import os
os.environ['CUDA_VISIBLE_DEVICES']='0' #使用指定GPU进行计算
import paddlex as pdx
import imghdr
import paddle.fluid as fluid
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
from paddlex.cls import transforms

#训练集预处理模块
train_transforms=transforms.Compose([
    #随即裁剪
    transforms.RandomCrop(crop_size=224),
    #随机水平翻转
    transforms.RandomHorizontalFlip(),
    #随机像素内容变换
    transforms.RandomDistort(brightness_range=0.9,brightness_prob=0.5,contrast_range=0.9,contrast_prob=0.5,saturation_range=0.9,saturation_prob=0.5,hue_range=18,hue_prob=0.5),
    #归一化处理
    transforms.Normailze()
])
#测试集预处理模块
val_transforms=transforms.Compose([
    #根据图像的短边调整图像大小
    transforms.ResizeByShort(short_size=256),
    #以图像中心点扩散裁剪正方形
    transforms.CenterCrop(crop_size=224),
    #归一化处理
    transforms.Normailze()
])

### 其他补充信息 Additional Supplementary Information

![image](https://github.com/PaddlePaddle/Paddle/assets/118713813/72558e39-1a7a-488a-8dbd-d34a1c7dfe0a)

**Comment by wuyefeilin** [comment]
或许是你打错了归一化的单词

**Comment by uesrs** [comment]
> 或者也许是你错了归一化的单词

谢谢

**Comment by dingjiaweiww** [comment]
问题已解决
