### ISSUE TITLE
新增统计需求

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#547]
需求目标：
统计用户在运行demo\exsample的成功率、运行时间

需求详情：

train开始
- 动作记录
- 时间记录

train结束
- 动作记录
- 记录时间差

**Comment by llxxxll** [comment]
常规使用统计中能否区分新老用户？@reyoung

**Comment by yebie** [comment]
最近两天刚好也在考虑类似的功能。。。
是不是可以在主页域名下开个上传接口，然后客户端里面开个上传log/config文件的功能，平时不打开但demo中额外调用一次？
另外如果用户使用过程中有出错，也可以用这个功能上传出错log和config，然后我们可以人工/自动协助诊断。

**Comment by reyoung** [comment]
> 是不是可以在主页域名下开个上传接口，然后客户端里面开个上传log/config文件的功能，平时不打开但demo中额外调用一次？
另外如果用户使用过程中有出错，也可以用这个功能上传出错log和config，然后我们可以人工/自动协助诊断。

感觉没有必要，用户如果有问题也会去交issue的，况且这个只能统计有外网访问的情况，很多用户都是线下用的。

**Comment by reyoung** [comment]
感觉，如果能把百度内部用户的使用情况先加进统计，是比较有价值的。但是这块不太清楚怎么做。

**Comment by wen-bo-yang** [comment]
内部用户如果安装paddle的话，应该都能访问外网，能否在所有demo的例子中添加一个post的请求脚本，一旦运行失败触发这个脚本，像统计服务器发送请求，具体统计参数可以自己定义，统计服务器处理请求之后入库，这样就能拿到内部用户的统计数据了，而且外部用户也可以这样弄，这样是否可行？

**Comment by yebie** [comment]
内部用户可能采用一台机器访问外网并编译、再分发到多台不能访问外网的机器造集群，数据可能不方便直接传。
考虑在百度内部开个内部服务接口如何，发现外网访问不了就转到内网提交。然后内网这个服务自己做存储也可以、或者转发到外部存储也可以？

当然其它公司的内网就没办法了。。。

**Comment by luotao1** [comment]
close this issue due to #965
