### ISSUE TITLE
teacher_student_sigmoid_loss 为什么这么设计

### ISSUE THREAD

**Issue by zxy951005** [PaddlePaddle/Paddle#54715]
请问paddle loss 函数 teacher_student_sigmoid_loss为什么这么设计，文档上说这是个定制化loss。

loss表示式为，loss=max(x,0)−x∗z+log(1+exp(−abs(x)))+max(x,0)−x∗z′+log(1+exp(−abs(x)))。

x是预估的值，未经sigmoid的预估输出值；z代表是否点击，z'代表teacher model的预估值。

**Comment by kuizhiqing** [comment]
You may refer to https://seblee97.github.io/assets/pdf/icml.pdf for more detail.
