### ISSUE TITLE
打印信息缺少详细说明：Create dense tensor with dims[0] equal to 0

### ISSUE THREAD

**Issue by LemonNoel** [PaddlePaddle/Paddle#54712]
### 请提出你的问题 Please ask your question

版本：develop（commit id: c037453d6dc0378158e264ce7df64e0dafe075d9)

运行 PaddleNLP 代码会大量打印这条报错信息，严重干扰 log 读取，但是根据信息不知道该修改什么，Paddle 库里也搜不到相关的说明。

<img width="647" alt="截屏2023-06-16 16 48 48" src="https://github.com/PaddlePaddle/Paddle/assets/25607475/12f7ac82-71a5-413d-a561-4176f412680a">

**Comment by kuizhiqing** [comment]
请使用最新版本的 paddle 解决此问题。
