### ISSUE TITLE
python11 安装paddle_bfloat失败

### ISSUE THREAD

**Issue by hitzhu** [PaddlePaddle/Paddle#54721]
### 请提出你的问题 Please ask your question

python11 arm 环境下编译安装paddle,在安装依赖paddle_bfloat==0.1.7的时候报错
<img width="1424" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/55450821/a0c7ace7-108a-4b72-81de-9deede522e16">

**Comment by FeixLiu** [comment]
paddle现在支持python版本为 `3.6/3.7/3.8/3.9/3.10`，可以尝试降低python版本。https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-1-%E4%B8%80%E3%80%81%E7%8E%AF%E5%A2%83%E5%87%86%E5%A4%87
