### ISSUE TITLE
Hygon CPU + Windows

### ISSUE THREAD

**Issue by SunChao3555** [PaddlePaddle/Paddle#54728]
### 请提出你的问题 Please ask your question

请问是否支持Hygon CPU + Windows操作系统，或者是否能够源码编译安装

**Comment by zhengqiwen1997** [comment]
可以按照 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html#compile_from_host 进行编译安装。编译安装whl包后，进入python运行paddle.device.is_compiled_with_rocm()，若为true则支持。

**Comment by SunChao3555** [comment]
> 可以按照 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html#compile_from_host 进行编译安装。编译安装whl包后，进入python运行paddle.device.is_compiled_with_rocm()，若为true则支持。

![图片](https://github.com/PaddlePaddle/Paddle/assets/35911336/75e7c564-48f4-4343-9923-6eb6055e8d11)

你好，执行ninja后有报错！

机器相关信息：
  设备名称	DESKTOP-VCFOFUC
  处理器	Hygon C86 3230  4-core Processor                  2.79 GHz
  机带 RAM	16.0 GB
  设备 ID	FE2287FC-A170-4EC4-AD8C-D9F5B0CA8CA9
  产品 ID	00391-80000-00001-AA702
  系统类型	64 位操作系统, 基于 x64 的处理器
  笔和触控	没有可用于此显示器的笔或触控输入
  
  版本	Windows 10 专业工作站版
  版本号	21H2
  安装日期	‎2022/‎8/‎11
  操作系统内部版本	19044.2965
  体验	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by qili93** [comment]
您好，

Hygon C86 CPU 架构同 Intel CPU架构一致都是X86架构的CPU，您这里可以直接参考 Intel CPU + Windows的源码编译方案，或者已有的编译程序进行安装即可。
