### ISSUE TITLE
如何保存paddle.io.dataloader

### ISSUE THREAD

**Issue by Gelisi** [PaddlePaddle/Paddle#54726]
### 请提出你的问题 Please ask your question

我现在再跑一个模型，但是我每次得到dataloader预处理都很麻烦，我想处理一次保存到本地，但是我试了很多方法,pickle, dill都不行，求指点迷津

**Comment by wuhuachaocoding** [comment]
你可以将传入dataloader的Dataset提前进行预处理，并存到本地。下次启动的时候，将存到本地的Dataset数据传入Dataloader，这样预处理操作就不需要了。
