### ISSUE TITLE
paddle需要指定cuda版本，不能向上兼容

### ISSUE THREAD

**Issue by super-tian** [PaddlePaddle/Paddle#54744]
### 需求描述 Feature Description

1，paddle框架只能选择相同的cuda版本进行安装，cuda版本不一样需要自行编译安装，希望可以和pytorch一样向上兼容cuda版本，不然更新/切换cuda版本paddle需要重新编译/安装

### 替代实现 Alternatives

pytorch框架基本做到了同cuda大版本正常运行，且需要的相关组件在安装时一并安装到python的site_package中，如cublas64_11.dll组件是一并安装到了package中，且对版本限制不大，可以向上兼容更高等级的cuda，希望paddle也可以用类似的方式实现。
我是paddle的重度使用者，希望paddle能越做越好🎉🎉🎉

**Comment by GuoxiaWang** [comment]
已收到反馈，感谢。已经向内部反馈了。
