### ISSUE TITLE
[CustomDevice] GPU-specific watcher affects CustomDevice

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#54753]
### bug描述 Describe the Bug

paddle/distributed/launch/controllers/watcher.py
如果没有红框中临时禁用，PaddleCustomDevice中的这个watcher也会启线程。造成日志困惑，请修复。
```
LAUNCH WARNING 2023-06-19 16:58:17,493 save gpu log failed
```
![98f94e7c20b24487f4c43d34fea0b107](https://github.com/PaddlePaddle/Paddle/assets/127805199/05e14da0-7053-4c87-b75a-43920f6bf649)

### 其他补充信息 Additional Supplementary Information

相关PR：https://github.com/PaddlePaddle/Paddle/pull/42675/files

**Comment by GuoxiaWang** [comment]
已收到反馈，会尽快修复。感谢。
