### ISSUE TITLE
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

### ISSUE THREAD

**Issue by ShihPing0803** [PaddlePaddle/Paddle#54767]
### 请提出你的问题 Please ask your question

​在使用 PP Vehicle 进行二次开发时出现的问题，cuda 为 11.6 搭配 cudnn 8.4.0，找过网路上的解法，但都无法解决，求解!!! 整段运行如下:
<img width="960" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/119124535/ce8f4818-a06c-476b-ab7c-459bc2256db8">

**Comment by zhangbo9674** [comment]
您好，cudnn_ops_infer64_8.dll 是 cuda 环境自身的动态库，您可以尝试一下这个修复办法：https://blog.csdn.net/Kelen99/article/details/121883743

**Comment by loading2022** [comment]
> 您好，cudnn_ops_infer64_8.dll 是 cuda 环境自身的动态库，您可以尝试一下这个修复办法：https://blog.csdn.net/Kelen99/article/details/121883743
您好，因为我用的是本身电脑的环境，不是 anaconda，也是一样的步骤吗

**Comment by ShihPing0803** [comment]
@zhangbo9674 您好，因为我用的是本身电脑的环境，不是 anaconda，也是一样的步骤吗?

**Comment by zhangbo9674** [comment]
应该也是一样的

**Comment by ShihPing0803** [comment]
非常感谢，已解决
