### ISSUE TITLE
Paddlescience 的viv样例在cuda11.2和cpu上训练效果不佳

### ISSUE THREAD

**Issue by jiangzhangze** [PaddlePaddle/Paddle#54773]
### bug描述 Describe the Bug

Paddlescience 的viv样例在cuda11.2和cpu上训练效果不佳，训练代码和[教程](https://paddlescience-docs.readthedocs.io/zh/latest/zh/examples/viv/#31)中的完全一样，在cuda11.2上训练100000步的效果如下:
![viv_pred](https://github.com/PaddlePaddle/Paddle/assets/99314760/d4420a93-ce5f-4b60-9929-b77b6592fbf4)
在cpu上训练100000步的效果如下:
![viv_pred](https://github.com/PaddlePaddle/Paddle/assets/99314760/e7faeeeb-7d51-4cb8-a25f-6d73a947fb8f)

### 其他补充信息 Additional Supplementary Information

>>> paddle.version.show()
commit: 3261b10601279260b723a0d49aba5e90adeb2a83
cuda: 11.7
cudnn: 8.4.0
xpu: False
xpu_xccl: False
cinn: False

**Comment by cxxly** [comment]
@HydrogenSulfate

**Comment by HydrogenSulfate** [comment]
你好，我在 AIStudio 上CPU / CUDA 11.2 的测试结果可视化都是正常的
![image](https://github.com/PaddlePaddle/Paddle/assets/23737287/d4dc600c-d33d-447b-bfc9-c9aa29abee05)
