### ISSUE TITLE
OSError: (External) CUBLAS error(7).

### ISSUE THREAD

**Issue by estuday** [PaddlePaddle/Paddle#54770]
### bug描述 Describe the Bug

使用uie进行事件抽取时会报错。不知道为什么，环境什么的都没改，突然就报这个错了。
python 3.9
cuda 11.4
cudnn 8
paddlepaddle-gpu 2.4

**Comment by zhangbo9674** [comment]
您好，根据上述问题描述无法定位到问题，此外，这里的 UIE 并未在 PaddlePaddle/Paddle repo 查找到相关内容，麻烦提供一下更详细的细节信息
