### ISSUE TITLE
您好，请问在mRNA序列设计过程中使用来自pdb或者NCBI获取的序列FASTA结构全部都提示序列格式有误

### ISSUE THREAD

**Issue by Duan-xiang** [PaddlePaddle/Paddle#54782]
### bug描述 Describe the Bug

无代码

### 其他补充信息 Additional Supplementary Information

诸如在pdb获取的数据：
>7YRF_2|Chain B[auth E]|Light chain of chain|Coxsackievirus A16 (31704)
DIQMTQSSSYLSVSLGGRVTITCKASDHINNWLAWYQQKPGNAPRLLISGATSLETGVPSRFSGSGSGKDYTLSITSLQTEDVATYYCQQYWNSPYTFGGGTKLEIKRADAAPTVSIFPPSSEQLTSGGASVVCFLNNFYPKDINVKWKIDGSERQNGVLNSWTDQDSKDSTYSMSSTLTLTKDEYERHNSYTCEATHKTSTSPIVKSFNRNEC
以及在ncbi获取的数据
EV71-VP1：
MDRVADVIESSIGDSVSRALTQALPAPTGQNTQVSSHRLDTGKVPALQAAEIGASSNASDESMIETRCVLNSHSTAETTLDSFFSRAGLVGEIDLPLEGTTNPNGYANWDIDITGYAQMRRKVELFTYMRFDAEFTFVACTPTGQVVPQLLQYMFVPPGAPKPDSRESLAWQTATNPSVFVKLSDPPAQVSVPFMSPASAYQWFYDGYPTFGEHKQEKDLEYGACPNNMMGTFSVRTVGTSKSKYPLVVRIYMRMKHVRAWIPRPMRNQNYLFKANPNYAGNSIKPTGASRAAITTL
这样的格式全部都报错

**Comment by zhangbo9674** [comment]
你好，能反馈一下具体在 Paddle 使用过程中哪个环节报错么？

**Comment by Duan-xiang** [comment]
在使用PaddleHelix的疫苗设计中的mRNA序列设计条目下的输入方式一栏，直接俄输入pdb和ncbi获取的fasta格式的数据都提示序列格式错误，序列就是之前问题中提到的，不知道哪里错了，未进行任何修改直接上传网站下载的文件也提示文件内序列格式错误

**Comment by sdnjly** [comment]
> 在使用PaddleHelix的疫苗设计中的mRNA序列设计条目下的输入方式一栏，直接俄输入pdb和ncbi获取的fasta格式的数据都提示序列格式错误，序列就是之前问题中提到的，不知道哪里错了，未进行任何修改直接上传网站下载的文件也提示文件内序列格式错误
请问，提交的时候是直接上传的fasta文件，还是手动粘贴到输入框提交的呢

**Comment by sdnjly** [comment]
> 在使用PaddleHelix的疫苗设计中的mRNA序列设计条目下的输入方式一栏，直接俄输入pdb和ncbi获取的fasta格式的数据都提示序列格式错误，序列就是之前问题中提到的，不知道哪里错了，未进行任何修改直接上传网站下载的文件也提示文件内序列格式错误

请问，提交的时候是直接上传的fasta文件，还是手动粘贴到输入框提交的呢

**Comment by sdnjly** [comment]
如果是手动粘贴，根据fasta格式的要求，第一行需要包含>，类似下面这样的
>EV71-VP1：
MDRVADVIESSIGDSVSRALTQALPAPTGQNTQVSSHRLDTGKVPALQAAEIGASSNASDESMIETRCVLNSHSTAETTLDSFFSRAGLVGEIDLPLEGTTNPNGYANWDIDITGYAQMRRKVELFTYMRFDAEFTFVACTPTGQVVPQLLQYMFVPPGAPKPDSRESLAWQTATNPSVFVKLSDPPAQVSVPFMSPASAYQWFYDGYPTFGEHKQEKDLEYGACPNNMMGTFSVRTVGTSKSKYPLVVRIYMRMKHVRAWIPRPMRNQNYLFKANPNYAGNSIKPTGASRAAITTL

**Comment by sdnjly** [comment]
输入的蛋白序列需要以起始密码子M开头，所以上面第一条需要不满足这个要求。至于第二条蛋白，我这边提交时并没有报错。另外，需要注意的是输入的第一行如果是蛋白的名称描述等，根据fasta格式的要求，需要以>开头

**Comment by sdnjly** [comment]
输入的蛋白序列需要以起始密码子M开头，所以上面第一条序列不满足这个要求。至于第二条蛋白，我这边提交时并没有报错。另外，需要注意的是输入的第一行如果是蛋白的名称描述等，根据fasta格式的要求，需要以>开头
