### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.nn.quant.format'， 'paddle.quantization'

### ISSUE THREAD

**Issue by Victoria-1** [PaddlePaddle/Paddle#54785]
### bug描述 Describe the Bug

platform: windows11
paddlepaddle-gpu: 2.4.2
paddledet: 2.6.0
paddleslim: setup安装

example/auto_compression/detection/run.py报错如下:
ModuleNotFoundError: No module named 'paddle.nn.quant.format'

导入代码：
`from paddle.nn.quant.format import ConvertibleQuantedLayer`
其次
`from paddle.quantization.config import QuantConfig`

导入quantization也失败

**Comment by zhangbo9674** [comment]
你好，2.4.2版本中还未支持paddle.nn.quant.format，建议升级到2.5或者 develop

**Comment by iamvijayakumar** [comment]
khb

**Comment by muyele** [comment]
请问这个问题解决了吗
