### ISSUE TITLE
paddle为啥不提供升级和卸载功能？

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#548]
概述：
      paddle为啥不提供升级和卸载功能？

**Comment by hedaoyuan** [comment]
你这个升级卸载具体指什么环境下的升级卸载？
如果是`apt-get install`对应有`uninstall`命令。

**Comment by beckett1124** [comment]
如何在一键安装的情况下，是否考虑一键卸载！如果是install的话，确实uninstall命令可以搞定，但是安装paddle的依赖，还是没有卸载。是否考虑这个方向？
升级的话，我所想的是：paddle有新的release版本，是否会自动推送到已安装的？或者邮件提醒推送。

**Comment by reyoung** [comment]
不会考虑这个功能的。

Paddle官方主推docker使用。docker自己有版本管理机制。
如果是ubuntu安装包，也自己有版本管理机制。我们可以考虑弄一下ubuntu的ppa，不过目前没有人力去做。

其他的安装方式，可以自行卸载。
