### ISSUE TITLE
飞腾/鲲鹏下编译paddle2.2.2报错

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Paddle#54805]
### bug描述 Describe the Bug

-- Found Paddle host system: , version: 
-- Found Paddle host system's CPU: 8 cores
-- The CXX compiler identification is GNU 7.3.0
-- The C compiler identification is GNU 7.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- CXX compiler: /usr/bin/c++, version: GNU 7.3.0
-- C compiler: /usr/bin/cc, version: GNU 7.3.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.27.0") 
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
CMake Warning at CMakeLists.txt:261 (MESSAGE):
  Disable NCCL when compiling without GPU.  Force WITH_NCCL=OFF.

CMake Warning at CMakeLists.txt:308 (MESSAGE):
  Disable RCCL when compiling without ROCM.  Force WITH_RCCL=OFF.

-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- BOOST_VERSION: 1.41.0, BOOST_URL: http://paddlepaddledeps.bj.bcebos.com/boost_1_41_0.tar.gz
-- warp-ctc library: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/warpctc/lib/libwarpctc.so
-- Build OpenBLAS by External Project (include: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/openblas/include, library: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/openblas/lib/libopenblas.a)
-- CBLAS_PROVIDER: EXTERN_OPENBLAS
-- Protobuf protoc executable: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /mnt/vdb1/Paddle-2.2.2/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Found PythonInterp: /mnt/vdb1/miniconda3/bin/python3 (found suitable version "3.7.10", minimum required is "3") 
-- Found PythonLibs: /mnt/vdb1/miniconda3/lib/libpython3.7m.so (found suitable version "3.7.10", minimum required is "3") 
-- Found PY_pip: /mnt/vdb1/miniconda3/lib/python3.7/site-packages/pip  
-- Could NOT find PY_numpy (missing: PY_NUMPY) 
CMake Error at cmake/python_module.cmake:27 (message):
  python module numpy is not found
Call Stack (most recent call first):
  cmake/external/python.cmake:69 (find_python_module)
  cmake/third_party.cmake:243 (include)
  CMakeLists.txt:334 (include)

-- Configuring incomplete, errors occurred!
See also "/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeError.log".
(base) [root@localhost build]# cat /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeError.log
Performing C SOURCE FILE Test CMAKE_HAVE_LIBC_PTHREAD failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_53463/fast && /usr/bin/gmake -f CMakeFiles/cmTC_53463.dir/build.make CMakeFiles/cmTC_53463.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_53463.dir/src.c.o
/usr/bin/cc   -DCMAKE_HAVE_LIBC_PTHREAD   -o CMakeFiles/cmTC_53463.dir/src.c.o   -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.c
Linking C executable cmTC_53463
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_53463.dir/link.txt --verbose=1
/usr/bin/cc  -DCMAKE_HAVE_LIBC_PTHREAD    CMakeFiles/cmTC_53463.dir/src.c.o  -o cmTC_53463 
/usr/bin/ld: CMakeFiles/cmTC_53463.dir/src.c.o: in function `main':
src.c:(.text+0x34): undefined reference to `pthread_create'
/usr/bin/ld: src.c:(.text+0x3c): undefined reference to `pthread_detach'
/usr/bin/ld: src.c:(.text+0x48): undefined reference to `pthread_join'
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_53463.dir/build.make:87: cmTC_53463] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_53463/fast] Error 2

Source file was:
#include <pthread.h>

void* test_func(void* data)
{
  return data;
}

int main(void)
{
  pthread_t thread;
  pthread_create(&thread, NULL, test_func, NULL);
  pthread_detach(thread);
  pthread_join(thread, NULL);
  pthread_atfork(NULL, NULL, NULL);
  pthread_exit(NULL);

  return 0;
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_51434/fast && /usr/bin/gmake -f CMakeFiles/cmTC_51434.dir/build.make CMakeFiles/cmTC_51434.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_51434.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_51434.dir/CheckFunctionExists.c.o   -c /usr/share/cmake/Modules/CheckFunctionExists.c
Linking C executable cmTC_51434
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_51434.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_51434.dir/CheckFunctionExists.c.o  -o cmTC_51434  -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [CMakeFiles/cmTC_51434.dir/build.make:87: cmTC_51434] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_51434/fast] Error 2

Performing C++ SOURCE FILE Test MMX_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_57007/fast && /usr/bin/gmake -f CMakeFiles/cmTC_57007.dir/build.make CMakeFiles/cmTC_57007.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_57007.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DMMX_FOUND -mmmx   -o CMakeFiles/cmTC_57007.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mmmx’
gmake[1]: *** [CMakeFiles/cmTC_57007.dir/build.make:66: CMakeFiles/cmTC_57007.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_57007/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <mmintrin.h>
int main()
{
    _mm_setzero_si64();
    return 0;
}
Performing C++ SOURCE FILE Test SSE2_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_80626/fast && /usr/bin/gmake -f CMakeFiles/cmTC_80626.dir/build.make CMakeFiles/cmTC_80626.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_80626.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DSSE2_FOUND -msse2   -o CMakeFiles/cmTC_80626.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-msse2’
gmake[1]: *** [CMakeFiles/cmTC_80626.dir/build.make:66: CMakeFiles/cmTC_80626.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_80626/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <emmintrin.h>
int main()
{
    _mm_setzero_si128();
    return 0;
}
Performing C++ SOURCE FILE Test SSE3_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_a1687/fast && /usr/bin/gmake -f CMakeFiles/cmTC_a1687.dir/build.make CMakeFiles/cmTC_a1687.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_a1687.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DSSE3_FOUND -msse3   -o CMakeFiles/cmTC_a1687.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-msse3’
gmake[1]: *** [CMakeFiles/cmTC_a1687.dir/build.make:66: CMakeFiles/cmTC_a1687.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_a1687/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <pmmintrin.h>
int main()
{
    __m128d a = _mm_set1_pd(6.28);
    __m128d b = _mm_set1_pd(3.14);
    __m128d result = _mm_addsub_pd(a, b);
    result = _mm_movedup_pd(result);
    return 0;
}
Performing C++ SOURCE FILE Test AVX_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_81e65/fast && /usr/bin/gmake -f CMakeFiles/cmTC_81e65.dir/build.make CMakeFiles/cmTC_81e65.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_81e65.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX_FOUND -mavx   -o CMakeFiles/cmTC_81e65.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx’
gmake[1]: *** [CMakeFiles/cmTC_81e65.dir/build.make:66: CMakeFiles/cmTC_81e65.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_81e65/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256 a = _mm256_set_ps (-1.0f, 2.0f, -3.0f, 4.0f, -1.0f, 2.0f, -3.0f, 4.0f);
    __m256 b = _mm256_set_ps (1.0f, 2.0f, 3.0f, 4.0f, 1.0f, 2.0f, 3.0f, 4.0f);
    __m256 result = _mm256_add_ps (a, b);
    return 0;
}
Performing C++ SOURCE FILE Test AVX2_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_51539/fast && /usr/bin/gmake -f CMakeFiles/cmTC_51539.dir/build.make CMakeFiles/cmTC_51539.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_51539.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX2_FOUND -mavx2   -o CMakeFiles/cmTC_51539.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx2’
gmake[1]: *** [CMakeFiles/cmTC_51539.dir/build.make:66: CMakeFiles/cmTC_51539.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_51539/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m256i a = _mm256_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4);
    __m256i result = _mm256_abs_epi32 (a);
    return 0;
}
Performing C++ SOURCE FILE Test AVX512F_FOUND failed with the following output:
Change Dir: /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake cmTC_477e7/fast && /usr/bin/gmake -f CMakeFiles/cmTC_477e7.dir/build.make CMakeFiles/cmTC_477e7.dir/build
gmake[1]: Entering directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_477e7.dir/src.cxx.o
/usr/bin/c++    -Wno-error=deprecated-declarations -Wno-deprecated-declarations -DAVX512F_FOUND -mavx512f   -o CMakeFiles/cmTC_477e7.dir/src.cxx.o -c /mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp/src.cxx
c++: error: unrecognized command line option ‘-mavx512f’
gmake[1]: *** [CMakeFiles/cmTC_477e7.dir/build.make:66: CMakeFiles/cmTC_477e7.dir/src.cxx.o] Error 1
gmake[1]: Leaving directory '/mnt/vdb1/Paddle-2.2.2/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:121: cmTC_477e7/fast] Error 2

...and run output:

Return value: 1
Source file was:

#include <immintrin.h>
int main()
{
    __m512i a = _mm512_set_epi32 (-1, 2, -3, 4, -1, 2, -3, 4,
                                  13, -5, 6, -7, 9, 2, -6, 3);
    __m512i result = _mm512_abs_epi32 (a);
    return 0;
}

**Comment by AnnaTrainingG** [comment]
你好，paddle2.2.2到paddle2.4中间升级众多，且修复了一些问题，建议拉取最新paddle进行编译

你遇到的错误信息表明 c++ 编译器无法识别 -mavx512f 命令行选项。这通常发生在编译器不支持该选项的情况下。这可能是由于使用的编译器版本较旧或不支持 AVX-512 指令集。要解决这个问题，你可以尝试以下几个步骤：

确保你使用的是支持 AVX-512 指令集的编译器版本。你可以查看编译器文档或升级编译器以获得更好的支持。

如果你无法更换编译器，可以尝试使用更低级别的指令集选项，例如 -mavx2。请注意，这可能会导致性能下降或功能不完整。

如果你正在构建第三方库或框架，可以检查其文档或配置选项，了解是否支持 AVX-512，并相应地调整编译选项。

**Comment by ZTurboX** [comment]
> 你好，paddle2.2.2到paddle2.4中间升级众多，且修复了一些问题，建议拉取最新paddle进行编译
> 
> 你遇到的错误信息表明 c++ 编译器无法识别 -mavx512f 命令行选项。这通常发生在编译器不支持该选项的情况下。这可能是由于使用的编译器版本较旧或不支持 AVX-512 指令集。要解决这个问题，你可以尝试以下几个步骤：
> 
> 确保你使用的是支持 AVX-512 指令集的编译器版本。你可以查看编译器文档或升级编译器以获得更好的支持。
> 
> 如果你无法更换编译器，可以尝试使用更低级别的指令集选项，例如 -mavx2。请注意，这可能会导致性能下降或功能不完整。
> 
> 如果你正在构建第三方库或框架，可以检查其文档或配置选项，了解是否支持 AVX-512，并相应地调整编译选项。

我怎么查看 是否是AVX-512 指令集的编译器呢？如果不是，需要怎样升级？

**Comment by AnnaTrainingG** [comment]
建议优先试用最新paddle进行编译

**Comment by ZTurboX** [comment]
> 建议优先试用最新paddle进行编译

是最新的paddle
