### ISSUE TITLE
aarch64 架构镜像

### ISSUE THREAD

**Issue by baizipo** [PaddlePaddle/Paddle#54811]
### 需求描述 Feature Description

nvidia-docker pull registry.baidubce.com/paddlepaddle/paddle:2.4.2-gpu-cuda10.2-cudnn7.6-trt7.0  这些镜像没有基于aarch64架构的，aarch64架构的镜像哪里可以获取，或者怎么制作？

**Comment by AnnaTrainingG** [comment]
抱歉这个版本目前没有对应的aarch64架构镜像，目前可查的镜像是这些https://hub.docker.com/r/paddlepaddle/paddle/tags/?pag=&page=1&name=aar     请问你的需求背景是什么呢

**Comment by zhengqiwen1997** [comment]
请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile.html#compile_from_docker 从源码编译
