### ISSUE TITLE
typo in logical_xor docs

### ISSUE THREAD

**Issue by MuhammadNizamani** [PaddlePaddle/Paddle#54835]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/logical_xor_en.html

### 请提出你的建议 Please give your suggestion

There is typo in the logical_xor 
Typo is when input and output datatypes are define it shown in the following image

![paddleisue1](https://github.com/PaddlePaddle/Paddle/assets/49721249/51555096-f45e-4ff9-84df-bf35d7d89c8c)

PS: can anyone tell where I can find doc string for this docs. i want to create PR

**Comment by thisjiang** [comment]
Hi~Thanks for your reminder and welcome your fix PR! You can find the doc string at:
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/tensor/logic.py#L185

**Comment by MuhammadNizamani** [comment]
Thanks I am on it

**Comment by MuhammadNizamani** [comment]
Issue in solved
