### ISSUE TITLE
Out of memory error on GPU 0. Cannot allocate 7.781267GB memory on GPU 0

### ISSUE THREAD

**Issue by ww09057118** [PaddlePaddle/Paddle#54852]
### 请提出你的问题 Please ask your question

paddlex实例分割训练，14张图片，batchsize 1，迭代轮数2，每次都报内存不足

**Comment by thisjiang** [comment]
Hi~ PaddleX相关问题欢迎前往PaddleX issue区提问~
https://github.com/PaddlePaddle/PaddleX/issues

**Comment by thisjiang** [comment]
您也可以试试通过设置FLAGS_memory_fraction_of_eager_deletion等环境变量来启用激进的垃圾回收策略来降低显存使用量：
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/memory_cn.html#flags-memory-fraction-of-eager-deletion
