### ISSUE TITLE
请问PaddleHub 模型列表中推荐指数(96分）是如何计算得来的

### ISSUE THREAD

**Issue by zed-2018** [PaddlePaddle/Paddle#54878]
### 请提出你的问题 Please ask your question

https://www.paddlepaddle.org.cn/hublist
请问PaddleHub 模型列表中推荐指数(96分）是如何计算得来的

**Comment by wangxn12138** [comment]
你好，PaddleHub相关问题，可以在 https://github.com/PaddlePaddle/PaddleHub/issues 下提出。
