### ISSUE TITLE
paddle  train from scratch  参数初始化问题

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#5489]
这个不光是我遇到的问题，有好多人也跟我吐槽。 事情是：最近要用paddle train模型（图像）， 发现如果train scratch 很难收敛， 得知得用caffe 初始化的参数来init paddle 就训练的比较好，试了一下确实有该问题。还有， 图像方面， 分类和检测任务最终训练精度都比caffe低， 不知道为什么，这个问题也希望探测一下

**Comment by lcy-seso** [comment]
是说用 caffe 产生的随机参数来初始化Paddle，然后再训练效果会比较好，对吗？

如果是这种情况，看上去是不是因为对图像类问题初始化策略现在的选择有问题？研究一下我们应该可以试着解决一下。

**Comment by lcy-seso** [comment]
听专门做过学习性能对比的同学说（在同任务上严格对比过 paddle / caffe / torch ），分类和 OCR 的任务都没有任何问题。现在的默认初始化参数已经是较好的，即使用caffe，也需要用户自己选择初始化。

这个问题“听上去”挺奇怪的，原则上只要实现没有错误，不收敛的原因，通过实验出来都是可以找出来精确原因，并不一定是我们的初始化有差异这么粗暴的原因？

**Comment by NHZlX** [comment]
刚刚跟用户调研了一下， 使用ssd model的遇到第一种问题，是用的是默认的paddle 的初始化（但是demo 给的是默认的），这个最近我会验证一下其他init 的方式。
