### ISSUE TITLE
不同trainer支持配置不同的端口

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#549]
目前在paddle集群中所有trainer必须配置同样的端口，但是在集群中很有可能某些机器上端口被占用了，如果支持不同机器配不一样的端口就能避免这种问题了

**Comment by backyes** [comment]
@jacquesqiao 

如果遇到了这种冲突，临时解决方法是 换一组端口，一般非常容易找到一组可用的端口。

另外， PaddlePaddle提供的docker训练场景下一般不存在端口冲突问题。长期，我们会根据将来的多机架构优化设计，考虑是否支持动态非连续的端口策略。

**Comment by helinwang** [comment]
多谢issue。新的pserver支持自定义端口，如backyes所说docker也可以自定义端口。
