### ISSUE TITLE
C-API使用GPU进行inference时，训练数据如何存入GPU_Matrix中？

### ISSUE THREAD

**Issue by QingshuChen** [PaddlePaddle/Paddle#5490]
C-API使用GPU进行计算时，需要把特征值存入输入的Argument中，有什么接口吗？
另外，推理完后，结果是放在输出的Argument（数据在GPU上面）中，如何把数据从GPU拷贝到CPU上面，有什么接口？

**Comment by typhoonzero** [comment]
参考issue: https://github.com/PaddlePaddle/Paddle/issues/3969

输入数据可以使用类似以下代码创建

```c++
paddle_matrix_create(uint64_t height,
                                          uint64_t width,
                                          bool useGpu);
```

**Comment by QingshuChen** [comment]
输出结果是一个GPUMatrix类型，如果把数据从里面拷贝出来?

**Comment by typhoonzero** [comment]
下面是我的理解，没有实际写过可能有问题：

先调用

```
PD_API paddle_error paddle_matrix_get_row(paddle_matrix mat,
                                          uint64_t rowID,
                                          paddle_real** rawRowBuffer);
```

拿到类型是`paddle_real`的指针，然后调用`cudaMemcpy ( void* dst, const void* src, size_t count, cudaMemcpyKind kind )` 拷贝到CPU。

参考：http://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__MEMORY.html#group__CUDART__MEMORY_1gc263dbe6574220cc776b45438fc351e8

**Comment by QingshuChen** [comment]
这也太难用了，还需要去调用cuda的API，我建议这边再封装一些接口，比如cpuMatrix.copyFrom(gpuMatrix), 这些实现paddle都已经有了，只需要在API这边暴露给用户就可以了

**Comment by typhoonzero** [comment]
嗯。这个方法是我刚才看了下代码，看起来目前是没有实现GPU-CPU的实现。的确暴露这样的API很有必要。这个issue先保留着，后续跟进增加此接口。

**Comment by QingshuChen** [comment]
另外还有一个问题：输入数据从CPU拷贝到GPU matrixt时，目前的接口只支持一行一行的拷贝（paddle_matrix_set_row）,如果batch_size比较大时，会影响性能，需要暴露一个批量拷贝的接口

**Comment by Xreki** [comment]
```cpp
paddle_error paddle_matrix_get_row(paddle_matrix mat,
                                   uint64_t rowID,
                                   paddle_real** rawRowBuffer)
```

你可以调用`paddle_matrix_get_row(mat, 0, rawRowBuffer)`获取到第0行的指针后，使用`cudaMemcpy`将整个`batch`的数据一次拷贝过去。

PS：你不说我都忘了还有`paddle_matrix_set_row`这样一个接口，这个接口有点鸡肋了，从来没用过。。。
