### ISSUE TITLE
是否可以提供更友好的whl

### ISSUE THREAD

**Issue by cole-dda** [PaddlePaddle/Paddle#54923]
### 问题描述 Issue Description

因为paddlepaddle太依赖用户的linux环境，必须安装合适的驱动和cuda/cudnn，而且经常因为路径/版本/so找不到的问题折腾，导致在这些上面浪费了太多时间。是否可以学习pytorch，把cuda/cudnn等依赖（so文件）也打包在whl中，用户只需要简单的pip install paddlepaddle，即可。当然，还需要安装nvidia的driver，而不需要安装cuda/cudnn等。

另外对python3.11的支持太慢了，都已经半年以上了。既然都支持python3.10-python3.7，而python3.11基本没有什么大的改动，
是否可以支持得更快一些。有时候为了使用paddlepaddle，要么项目迁就使用python3.10，要么转为使用pytorch。

### 版本&环境信息 Version & Environment Information

目前最新的paddlepaddle版本

**Comment by zhangting2020** [comment]
您好，感谢您的建议。关于您提到的安装问题，我们会进行需求评估在后续版本中持续改进安装体验。

另外，目前python3.11的whl包，暂时未发布稳定版本，在官网中 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html 页面，develop(nightly build)有支持部分cuda版本的whl包可以使用。
