### ISSUE TITLE
麒麟系统编译paddle在make TARGET=ARMV8后报错

### ISSUE THREAD

**Issue by Phoenix2Legend** [PaddlePaddle/Paddle#54941]
### bug描述 Describe the Bug

在麒麟v10系统上编译paddle，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。参考文档链接为：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html。在完成make TARGET=ARMV8 -j$(nproc)操作以后报错，具体报错信息见《其他补充信息 Additional Supplementary Information》

### 其他补充信息 Additional Supplementary Information

λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 -j$(nproc)
[  0%] Built target extern_eigen3
[  0%] Built target extern_utf8proc
[  0%] Built target extern_warpctc
[  0%] Built target extern_zlib
[  0%] Performing build step for 'extern_openblas'
[  0%] Performing configure step for 'extern_warprnnt'
make[3]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
[  0%] Built target extern_lapack
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log

make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
[  0%] Built target extern_pybind
make[1]: *** [CMakeFiles/Makefile2:4771：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/ops/compat/signatures.h
[  0%] Built target copy_signatures_command
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
In file included from ../common.h:543:0,
                 from gemm.c:41:
gemm.c: 在函数‘sgemm_’中:
../common_param.h:977:23: 错误：‘GEMM_DEFAULT_OFFSET_A’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
gemm.c:413:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (XFLOAT *)((BLASLONG)buffer +GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:977:23: 附注：每个未声明的标识符在其出现的函数内只报告一次
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
gemm.c:413:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (XFLOAT *)((BLASLONG)buffer +GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
In file included from ../common.h:543:0,
                 from symm.c:41:
symm.c: 在函数‘ssymm_’中:
../common_param.h:977:23: 错误：‘GEMM_DEFAULT_OFFSET_A’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
symm.c:373:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:977:23: 附注：每个未声明的标识符在其出现的函数内只报告一次
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
symm.c:373:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:987:18: 错误：‘SGEMM_DEFAULT_P’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_R’?
 #define SGEMM_P  SGEMM_DEFAULT_P
                  ^
../common_param.h:1123:18: 附注：in expansion of macro ‘SGEMM_P’
 #define GEMM_P   SGEMM_P
                  ^~~~~~~
gemm.c:414:37: 附注：in expansion of macro ‘GEMM_P’
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                     ^~~~~~
../common_param.h:988:18: 错误：‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_P’?
 #define SGEMM_Q  SGEMM_DEFAULT_Q
                  ^
../common_param.h:1124:18: 附注：in expansion of macro ‘SGEMM_Q’
 #define GEMM_Q   SGEMM_Q
                  ^~~~~~~
gemm.c:414:46: 附注：in expansion of macro ‘GEMM_Q’
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                              ^~~~~~
In file included from ../common.h:543:0,
                 from trsm.c:41:
trsm.c: 在函数‘strmm_’中:
../common_param.h:977:23: 错误：‘GEMM_DEFAULT_OFFSET_A’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
trsm.c:368:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:977:23: 附注：每个未声明的标识符在其出现的函数内只报告一次
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
trsm.c:368:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:987:18: 错误：‘SGEMM_DEFAULT_P’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_R’?
 #define SGEMM_P  SGEMM_DEFAULT_P
                  ^
../common_param.h:1123:18: 附注：in expansion of macro ‘SGEMM_P’
 #define GEMM_P   SGEMM_P
                  ^~~~~~~
symm.c:374:36: 附注：in expansion of macro ‘GEMM_P’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                    ^~~~~~
In file included from ../common.h:543:0,
                 from trsm.c:41:
trsm.c: 在函数‘strsm_’中:
../common_param.h:977:23: 错误：‘GEMM_DEFAULT_OFFSET_A’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_UNROLL_M’?
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
trsm.c:368:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:977:23: 附注：每个未声明的标识符在其出现的函数内只报告一次
 #define GEMM_OFFSET_A GEMM_DEFAULT_OFFSET_A
                       ^
trsm.c:368:37: 附注：in expansion of macro ‘GEMM_OFFSET_A’
   sa = (FLOAT *)((BLASLONG)buffer + GEMM_OFFSET_A);
                                     ^~~~~~~~~~~~~
../common_param.h:987:18: 错误：‘SGEMM_DEFAULT_P’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_R’?
 #define SGEMM_P  SGEMM_DEFAULT_P
                  ^
../common_param.h:1123:18: 附注：in expansion of macro ‘SGEMM_P’
 #define GEMM_P   SGEMM_P
                  ^~~~~~~
trsm.c:369:36: 附注：in expansion of macro ‘GEMM_P’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                    ^~~~~~
../common_param.h:979:20: 错误：‘GEMM_DEFAULT_ALIGN’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_P’?
 #define GEMM_ALIGN GEMM_DEFAULT_ALIGN
                    ^
gemm.c:414:73: 附注：in expansion of macro ‘GEMM_ALIGN’
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                         ^~~~~~~~~~
../common_param.h:988:18: 错误：‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_P’?
 #define SGEMM_Q  SGEMM_DEFAULT_Q
                  ^
../common_param.h:1124:18: 附注：in expansion of macro ‘SGEMM_Q’
 #define GEMM_Q   SGEMM_Q
                  ^~~~~~~
symm.c:374:45: 附注：in expansion of macro ‘GEMM_Q’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                             ^~~~~~
../common_param.h:978:23: 错误：‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_OFFSET_A’?
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
                       ^
gemm.c:414:103: 附注：in expansion of macro ‘GEMM_OFFSET_B’
   sb = (XFLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                                                       ^~~~~~~~~~~~~
../common_param.h:988:18: 错误：‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_P’?
 #define SGEMM_Q  SGEMM_DEFAULT_Q
                  ^
../common_param.h:1124:18: 附注：in expansion of macro ‘SGEMM_Q’
 #define GEMM_Q   SGEMM_Q
                  ^~~~~~~
trsm.c:369:45: 附注：in expansion of macro ‘GEMM_Q’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                             ^~~~~~
../common_param.h:987:18: 错误：‘SGEMM_DEFAULT_P’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_R’?
 #define SGEMM_P  SGEMM_DEFAULT_P
                  ^
../common_param.h:1123:18: 附注：in expansion of macro ‘SGEMM_P’
 #define GEMM_P   SGEMM_P
                  ^~~~~~~
trsm.c:369:36: 附注：in expansion of macro ‘GEMM_P’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                    ^~~~~~
../common_param.h:988:18: 错误：‘SGEMM_DEFAULT_Q’ undeclared (first use in this function); did you mean ‘SGEMM_DEFAULT_P’?
 #define SGEMM_Q  SGEMM_DEFAULT_Q
                  ^
../common_param.h:1124:18: 附注：in expansion of macro ‘SGEMM_Q’
 #define GEMM_Q   SGEMM_Q
                  ^~~~~~~
trsm.c:369:45: 附注：in expansion of macro ‘GEMM_Q’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                             ^~~~~~
../common_param.h:979:20: 错误：‘GEMM_DEFAULT_ALIGN’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_P’?
 #define GEMM_ALIGN GEMM_DEFAULT_ALIGN
                    ^
symm.c:374:72: 附注：in expansion of macro ‘GEMM_ALIGN’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                        ^~~~~~~~~~
../common_param.h:979:20: 错误：‘GEMM_DEFAULT_ALIGN’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_P’?
 #define GEMM_ALIGN GEMM_DEFAULT_ALIGN
                    ^
trsm.c:369:72: 附注：in expansion of macro ‘GEMM_ALIGN’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                        ^~~~~~~~~~
../common_param.h:978:23: 错误：‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_OFFSET_A’?
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
                       ^
symm.c:374:102: 附注：in expansion of macro ‘GEMM_OFFSET_B’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                                                      ^~~~~~~~~~~~~
../common_param.h:979:20: 错误：‘GEMM_DEFAULT_ALIGN’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_P’?
 #define GEMM_ALIGN GEMM_DEFAULT_ALIGN
                    ^
trsm.c:369:72: 附注：in expansion of macro ‘GEMM_ALIGN’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                        ^~~~~~~~~~
../common_param.h:978:23: 错误：‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_OFFSET_A’?
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
                       ^
trsm.c:369:102: 附注：in expansion of macro ‘GEMM_OFFSET_B’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                                                      ^~~~~~~~~~~~~
make[4]: *** [Makefile:1212：sgemm.o] 错误 1
../common_param.h:978:23: 错误：‘GEMM_DEFAULT_OFFSET_B’ undeclared (first use in this function); did you mean ‘GEMM_DEFAULT_OFFSET_A’?
 #define GEMM_OFFSET_B GEMM_DEFAULT_OFFSET_B
                       ^
trsm.c:369:102: 附注：in expansion of macro ‘GEMM_OFFSET_B’
   sb = (FLOAT *)(((BLASLONG)sa + ((GEMM_P * GEMM_Q * COMPSIZE * SIZE + GEMM_ALIGN) & ~GEMM_ALIGN)) + GEMM_OFFSET_B);
                                                                                                      ^~~~~~~~~~~~~
make[4]: *** 正在等待未完成的任务....
make[4]: *** [Makefile:1230：ssymm.o] 错误 1
make[4]: *** [Makefile:1266：strsm.o] 错误 1
make[4]: *** [Makefile:1248：strmm.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4511：CMakeFiles/extern_openblas.dir/all] 错误 2
make: *** [Makefile:133：all] 错误 2
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop}

**Comment by zhangting2020** [comment]
看上去和 #54774 提到的是一个编译问题？

**Comment by qili93** [comment]
您好，根据错误提示是您的环境下编译openblas库遇到的问题，可以尝试参考  https://github.com/xianyi/OpenBLAS/issues/994 这个ISSUE的回答修复试下。

可能是由于您使用的芯片架构不是公版的ARMV8导致的编译问题，由于我们内部目前没有 FT-2000/4 的环境，只有 S2500的环境，因此无法复现您的问题。如果方便我们登录您的机器环境定位具体问题的话，请留下您的邮箱，我们联系你这里登录您环境看下具体问题，谢谢！

**Comment by Phoenix2Legend** [comment]
> 

不是一个问题

**Comment by Phoenix2Legend** [comment]
> 您好，根据错误提示是您的环境下编译openblas库遇到的问题，可以尝试参考 [xianyi/OpenBLAS#994](https://github.com/xianyi/OpenBLAS/issues/994) 这个ISSUE的回答修复试下。
> 
> 可能是由于您使用的芯片架构不是公版的ARMV8导致的编译问题，由于我们内部目前没有 FT-2000/4 的环境，只有 S2500的环境，因此无法复现您的问题。如果方便我们登录您的机器环境定位具体问题的话，请留下您的邮箱，我们联系你这里登录您环境看下具体问题，谢谢！

我的邮箱是837649102@qq.com，关于以上我所表述的报错目前还没有进展，希望能得到您的帮助，谢谢！

**Comment by Phoenix2Legend** [comment]
> 您好，根据错误提示是您的环境下编译openblas库遇到的问题，可以尝试参考 [xianyi/OpenBLAS#994](https://github.com/xianyi/OpenBLAS/issues/994) 这个ISSUE的回答修复试下。
> 
> 可能是由于您使用的芯片架构不是公版的ARMV8导致的编译问题，由于我们内部目前没有 FT-2000/4 的环境，只有 S2500的环境，因此无法复现您的问题。如果方便我们登录您的机器环境定位具体问题的话，请留下您的邮箱，我们联系你这里登录您环境看下具体问题，谢谢！

您好，994未能解决该问题，如果能提供更有效的帮助，将不胜感激！

**Comment by martin-frbg** [comment]
> /bin/sh: ./getarch: 权限不够

This is very strange - getarch is needed to select all the missing GEMM parameters that it complains about later. It is a small C program that gets built first - somehow it does not have executable permission or it is not a valid executable
on your platform.
