### ISSUE TITLE
标注

### ISSUE THREAD

**Issue by cqray1990** [PaddlePaddle/Paddle#54954]
### 请提出你的问题 Please ask your question

如何我的实体名是生产日期：

文本是：生产日期：2022.12.01

标注的时候需要把生产日期标注进去？还是只标注后面的日期？

**Comment by zhangting2020** [comment]
请问这个是什么背景的问题呢？是在做某个模型的数据标注？如果是特定模型库的问题，建议在模型库的issue中提问
