### ISSUE TITLE
install Paddle on VM machine 

### ISSUE THREAD

**Issue by flamit** [PaddlePaddle/Paddle#54971]
### 问题描述 Issue Description

Im trying to run paddle in a VM. Paddle is installed 
pip install paddleocr, 

I get these errors 

rror: Can not import paddle core while this file exists: C:\Users\ai-appeal-ukpc-prod\myvenv\lib\site-packages\paddle\fluid\libpaddle.pyd
Traceback (most recent call last):

ImportError: DLL load failed while importing libpaddle: The specified module could not be found

### 版本&环境信息 Version & Environment Information

StatusCode        : 200
StatusDescription : OK
Content           : # Copyright (c) 2020 PaddlePaddle Authors. All Rights Reserved.
                    #
                    # Licensed under the Apache License, Version 2.0 (the "License");
                    # you may not use this file except in compliance with the License.
                    #...
RawContent        : HTTP/1.1 200 OK
                    Connection: keep-alive
                    Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox  
                    Strict-Transport-Security: max-age=31536000
                    X-Content-Type-Options: nosniff
                    ...
Forms             : {}
Headers           : {[Connection, keep-alive], [Content-Security-Policy, default-src 'none';
                    style-src 'unsafe-inline'; sandbox], [Strict-Transport-Security,
                    max-age=31536000], [X-Content-Type-Options, nosniff]...}
Images            : {}
InputFields       : {}
Links             : {}
ParsedHtml        : System.__ComObject
RawContentLength  : 5801

**Comment by zhangting2020** [comment]
use `import paddle` and `paddle.utils.run_check()` to verify if the installation was successful.

Additionally, you can refer to the installation steps: https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/develop/install/pip/linux-pip_en.html

**Comment by said46** [comment]
Hello! What was the solution? I faced the same issue and cannot find an answer anywhere.
