### ISSUE TITLE
test_sparse_norm_op failure

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#54986]
### bug描述 Describe the Bug

In [test_sparse_norm_op.py#L115](https://github.com/PaddlePaddle/Paddle/blob/1d8116a5178f456aeb11e6c6d2617c4882ad25ab/test/legacy_test/test_sparse_norm_op.py#L115), the gradients calculated by `sp_y.backward()` are zero, which is obviously incorrect.

Environment:
```
GPU: V100 or A100
Paddle version: 2.5
Paddle With CUDA: True
```

Error message:
```
2198: Traceback (most recent call last):
2198:   File "/opt/paddle/paddle/build/test/legacy_test/test_sparse_norm_op.py", line 120, in test_nd
2198:     self.check([2, 8, 8, 3])
2198:   File "/opt/paddle/paddle/build/test/legacy_test/test_sparse_norm_op.py", line 114, in check
2198:     np.testing.assert_allclose(
2198:   File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 1530, in assert_allclose
2198:     assert_array_compare(compare, actual, desired, err_msg=str(err_msg),
2198:   File "/usr/local/lib/python3.10/dist-packages/numpy/testing/_private/utils.py", line 844, in assert_array_compare
2198:     raise AssertionError(msg)
2198: AssertionError: 
2198: Not equal to tolerance rtol=1e-05, atol=0
2198: 
2198: Mismatched elements: 384 / 384 (100%)
2198: Max absolute difference: 3.4906066e-06
2198: Max relative difference: inf
2198:  x: array([[[[-5.049368e-07, -8.769730e-07,  3.315337e-07],
2198:          [-4.783593e-07,  3.065689e-07,  5.034986e-07],
2198:          [ 2.471942e-07, -1.593849e-06,  1.770462e-06],...
2198:  y: array([[[[0., 0., 0.],
2198:          [0., 0., 0.],
2198:          [0., 0., 0.],...
```

**Comment by Wong4j** [comment]
请问这个Bug有进展吗？

**Comment by umiswing** [comment]
@Wong4j 单测中涉及的算子调用cudnn进行计算。由于该单测在某些cudnn版本下可以通过，我做了如下这些验证：

1. 为排除框架影响，我将单测的数据dump下来并硬编码到一段使用cuda API调用cudnn的测试程序里，发现在cudnn 8.2和cudnn 8.4中，同一段测试程序计算结果不一致。
2. 在pytorch中计算相同的case，计算结果与paddle的一致（pytorch官方没有sparse batch norm的实现，paddle sparse batch norm会转换成batchnorm1d计算，因此paddle sparse batch norm对比的是pytorch在这个case下batchnorm1d的计算结果）。
3. 使用多个随机种子生成loss数据，单测都能通过assert。

根据这些测试结果，目前认为是某些版本的cudnn在单测的case下CUDNN_BATCHNORM_PER_ACTIVATION和CUDNN_BATCHNORM_SPATIAL两个mode计算结果diff比较大导致单测失败。修复方案还在讨论中。

**Comment by Wong4j** [comment]
感谢更新，Paddle的sparse batch norm跟cudnn有关系吗？如果排除了框架问题，确定是cudnn计算结果有问题，可以提供一个复现代码给我们。

**Comment by umiswing** [comment]
@Wong4j Paddle的sparse batch norm使用cudnn的CUDNN_BATCHNORM_PER_ACTIVATION mode计算。单测中用来与sparse做对比的dense bn使用cudnn的CUDNN_BATCHNORM_SPATIAL mode计算。我在cuda 11.7+cudnn 8.4下测试，这个case下这两个mode计算结果不一致。cudnn CUDNN_BATCHNORM_SPATIAL mode在cuda 11.2+cudnn 8.2与cuda 11.7+cudnn 8.4下测试，计算结果不一致。我这里可以提供一个测试CUDNN_BATCHNORM_SPATIAL mode的测试程序：https://github.com/umiswing/snippet/blob/master/cudnn_test/batchnorm.cu 输入数据硬编码了。我使用这个程序在不同cudnn环境下计算结果不同。应该还需要有一个CUDNN_BATCHNORM_PER_ACTIVATION mode的测试程序？如果需要的话我后续可以再提供，这样可以直接用cuda api对比同样的输入下cudnn这两个mode的计算结果。

**Comment by Wong4j** [comment]
我跑了一下这个代码，用最新的cuda 12.1 + cudnn 8.9 结果是非0的，用cuda 11.2+ cudnn8.2结果都是0。
看起来是cudnn 8.2结果不对？ 但是我们内部测试用的是最新的cudnn 8.9，测出来`sp_y.backward()`结果全为0。

这个问题确认是cudnn不同版本或mode计算的diff导致的吗？能否提供更详细的复现代码？

**Comment by umiswing** [comment]
@Wong4j 你测试的这个结果是符合预期的。因为我提供的这个代码不是paddle里sparse bn使用的mode，是用来检验sparse的计算结果的dense bn使用的mode，之前没有说清楚，不好意思。看起来是在这个case下，cudnn 8.2两个mode的计算结果都不对，cudnn升级后只修复了其中一个mode的计算结果，最后导致该单测失败。我后面会提供更详细的复现代码，感谢回复。

**Comment by Wong4j** [comment]
请问有复现代码吗？我可以反馈给cuDNN team

**Comment by umiswing** [comment]
我在单测里更换case暂时回避了这个问题：https://github.com/PaddlePaddle/Paddle/pull/55405
我当前有个高优任务，复现代码等我完成这个任务后提供吧。

**Comment by Wong4j** [comment]
请问是否有更新？能否提供大致的时间？

**Comment by umiswing** [comment]
https://github.com/umiswing/snippet/tree/master/cudnn_test
这个目录下，```batchnorm.cu```和```sp_batchnorm.cu```分别是dense bn和sparse bn反向在同一输入下的测试代码。
在cuda 11.7+cudnn 8.4下测试，```batchnorm.cu```输出非全0，```sp_batchnorm.cu```输出全0。
两份代码不同之处：
1. ```sp_batchnorm.cu```对输入```x```做了permute, shape从(n, c, h, w)变成(n\*h\*w, c, 1, 1)。
2. ```sp_batchnorm.cu```使用```CUDNN_BATCHNORM_PER_ACTIVATION```计算。

**Comment by Wong4j** [comment]
好的，我会测试一下然后反馈给cudnn team

**Comment by Wong4j** [comment]
repo链接没了，能再提供一下代码吗？

**Comment by umiswing** [comment]
@Wong4j 已更新到这个repo中。
https://github.com/umiswing/cudnn_test

**Comment by Wong4j** [comment]
已经反馈给cuDNN team，内部bug ID: 4273787

**Comment by Wong4j** [comment]
@umiswing 这是cuDNN team的回复：
```
I think we should ask the customer if they can use double precision or a SGBN engine to see if this resolves their issue.

A more detailed answer is that this batch normalization kernel uses floating point math roughly summed up as:
dxValue = dyMean - xDataDependentValue - dyValue

if the middle term is small relative to dyMean and dyMean and dyValue are close in value, then dxValue will end up evaluating to 0 because of floating point precision. If I reverse the order of operations to:
dyMean - dyValue - xDataDependentValue, then dxValue will correctly evaluate to xDataDependentValue, as dyMean and dyValue will cancel each other out.

This describes the customer's data set. dy is filed with 1s so its mean and values are equal. 1 is very large compared to the normalized xData, so it is being lost in FP32. FP64 retains the value.

I could reverse the order of operations as described, but then I worry about introducing new behavior where for small dyValues and large dyMeans and xDataValues it cancels to 0. I will discuss the pros and cons with the team.
```

看起来就是浮点加法中大数吃小数导致的精度损失，对这个问题你有什么看法吗？

**Comment by umiswing** [comment]
看起来第二种方式也会在某些case下出问题。是否要切换到第二种方式来计算，我觉得要看下模型训练时实际的数据范围了。不过，单测之前的case简单地输入全一的loss，这种case在模型训练时我估计不太常见。

**Comment by Wong4j** [comment]
这种case实际训练一般不会出现，那应该可以关掉这个issue了？

**Comment by umiswing** [comment]
我认为可以先关掉该issue。
