### ISSUE TITLE
win11下使用python3.11.4和CUDA12.2无法安装，无论带不带gpu都报错找不到版本

### ISSUE THREAD

**Issue by favouriter** [PaddlePaddle/Paddle#54995]
### 问题描述 win11下使用python3.11.4和CUDA12.2无法安装，无论带不带gpu都报错找不到版本

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.4.2 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2

### 版本&环境信息 Version & Environment Information

OS:win11
CPU:intel i7 12700H
GPU:nvidia GTX3060
CUDA:12.2

**Comment by zhwesky2010** [comment]
目前还没有发布3.11版本的whl包，可使用稍微3.10及以下的版本
