### ISSUE TITLE
paddle中沿对角线方向拼接矩阵，可以怎么实现？

### ISSUE THREAD

**Issue by jude2014** [PaddlePaddle/Paddle#54996]
### 请提出你的问题 Please ask your question

![2217fb8a954c8a689a80bb0032fae836](https://github.com/PaddlePaddle/Paddle/assets/11387828/41e0516d-0939-4b1d-bc6c-bcace048255c)
如图，输入是分别是子矩阵的维度，输出是二维矩阵，空白部分都是0

**Comment by jude2014** [comment]
https://blog.csdn.net/qq_37730871/article/details/120438255 类似这种功能

**Comment by danleifeng** [comment]
可以使用paddle.stack, paddle.zeros 和paddle切片等进行组合一下
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/stack_cn.html#stack
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/tensor_cn.html#suoyinheqiepian
