### ISSUE TITLE
安装出错：svn command failed怎么办

### ISSUE THREAD

**Issue by shouwangzhe** [PaddlePaddle/Paddle#550]
[WARNING]svn command failed, retrying ... 1
[NOTICE][Action:_GetTagAndRevisionByCommandInXML][cmd:svn info https://svn.baidu.com/sys/ip/trunk/rdma/thirdparty/ -r HEAD --xml][status:1][err:svn: access to 'https://svn.baidu.com/sys/ip/trunk/rdma/thirdparty' forbidden
]

**Comment by backyes** [comment]
需要找内部同学帮忙开svn权限，这里先close issue。
