### ISSUE TITLE
Error: Can not import paddle core while this file exists: /fluid/libpaddle.so (paddle develop)

### ISSUE THREAD

**Issue by Saransh-cpp** [PaddlePaddle/Paddle#55015]
### 问题描述 Issue Description

[DeepXDE](https://github.com/lululxvi/deepxde/)'s RTD build is failing with the error message -
```
Error: Can not import paddle core while this file exists: /home/docs/checkouts/readthedocs.org/user_builds/deepxde/envs/1311/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
```

<br>

- `paddle` is being [installed](https://github.com/lululxvi/deepxde/blob/master/docs/requirements.txt) from the following wheel file (develop version) - https://paddle-wheel.bj.bcebos.com/develop/linux/linux-cpu-mkl-avx/paddlepaddle-0.0.0-cp38-cp38-linux_x86_64.whl

- RTD logs - https://readthedocs.org/projects/deepxde/builds/21141828/

I saw a lot of similar issues in paddle's issue tracker but none of them were Installing the develop version of paddle; hence, I decided to report this.

### 版本&环境信息 Version & Environment Information

Environment is described here - https://github.com/lululxvi/deepxde/blob/master/.readthedocs.yaml

Paddle version: develop | linux-cpu-mkl-avx

**Comment by jasonsi1993** [comment]
Experiencing the same issue also, I used the cpu only version of paddlepaddle
