### ISSUE TITLE
window下docker编译 CMake Error at /paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):   Command failed: 1

### ISSUE THREAD

**Issue by Haozon** [PaddlePaddle/Paddle#55056]
@快乐开源活动
电脑环境：windows11
docker环境：docker-desktop
使用CPU编译
这个bug是在我用docker编译paddle框架时出现的，运行的命令为 time make -j$(nproc) ，我是严格按照官方文档[【Linux下从源码编译】文档的【使用Docker编译】](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile.html#span-id-compile-from-docker-docker-span)进行编译的。
下面是报错信息：
![image](https://github.com/PaddlePaddle/Paddle/assets/74298632/dea0bf85-2217-47c9-9f5b-7fe68d63cc6b)

[  0%] Performing configure step for 'extern_warprnnt'
[  0%] Built target extern_gflags
[  0%] copy_if_different /paddle/build/paddle/phi/kernels/declarations.h
[  0%] copy_if_different /paddle/build/paddle/phi/ops/compat/signatures.h
[  0%] Built target copy_declarations_command
CMake Error at /paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/home/cmake-3.16.0-Linux-x86_64/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/local/gcc-8.2/bin/c++' '-DCMAKE_C_COMPILER=/usr/local/gcc-8.2/bin/gcc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS= -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/paddle/third_party/warprnnt'

  See also /paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log

CMakeFiles/extern_warprnnt.dir/build.make:106: recipe for target 'third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure' failed
make[2]: *** [third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] Error 1
CMakeFiles/Makefile2:4960: recipe for target 'CMakeFiles/extern_warprnnt.dir/all' failed
make[1]: *** [CMakeFiles/extern_warprnnt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  0%] Built target copy_signatures_command

显然不是核心的问题。

**Comment by JZ-LIANG** [comment]
从报错log 看，是在编译paddle 的第三方依赖库（warprnnt）时失败了。 需要查看warprnnt 编译失败的原因，看一下 『 /paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log』文件里的log。
