### ISSUE TITLE
UT test_tuning_recompute failed on Paddle 2.5 with A100/A800/H100

### ISSUE THREAD

**Issue by zlsh80826** [PaddlePaddle/Paddle#55057]
### bug描述 Describe the Bug

复现步骤:

運行 `test_tuning_recompute` 在 A100/A800 上
```shell
ctest -R test_tuning_recompute
```

### 其他补充信息 Additional Supplementary Information

經過初步確認，此單測在 V100 能正常通過，但會在 A100/A800/H100 等 GPU 上面失敗

單測會有三個階段
1. trial-recompute-all-segments
2. trial-recompute-none-segments
3. trial-recompute-part-segments-*，只有當 non-segments 會 OOM 的時候才會運行 part-segments

在 V100 只有 16G 內存的時候，因為 none-segments 會 OOM，所以最後選擇的 trial 的 [no_recompute_segments](https://github.com/PaddlePaddle/Paddle/blob/f71e6a4186cadc94431bdef5b6778f959d984925/test/auto_parallel/test_tuning_recompute.py#L102) 一定會大於 0，但是在 A100/A800/H100 上因為顯存足夠，最佳的 trial 會是 none-segments，所以會遇到 [no_recompute_segments > 0](https://github.com/PaddlePaddle/Paddle/blob/f71e6a4186cadc94431bdef5b6778f959d984925/test/auto_parallel/test_tuning_recompute.py#L102) 的 assertion failed。所以此單測設計對於不同 GPU 架構的沒有適當的支援，需要修復

另外，在 `unittest.TestCase` 底下的單測應避免直接使用 assert，而是使用 unittest 模塊下的 [assert-methods](https://docs.python.org/3/library/unittest.html#assert-methods) 才能清楚的顯示錯誤訊息

例如這是把 [test_tuning_compute.py 中的 assert](https://github.com/PaddlePaddle/Paddle/blob/f71e6a4186cadc94431bdef5b6778f959d984925/test/auto_parallel/test_tuning_recompute.py#L98) 替換成 unittest 的 [assertGreater](https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertGreater) 的錯誤顯示差別，這在 CI 系統上才能清楚的看出問題
1. 使用 assert: 看不出來錯誤原因 (因為 python 只顯示 assert 那一行，而且也不會顯示錯誤的值跟期望的值)
```
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/auto_parallel/test_tuning_recompute.py", line 100, in test_recompute_pass
    assert (
AssertionError
```
2. 使用 assertGreater: 清楚顯示錯誤的值跟期望的值的行為
```
Traceback (most recent call last):
  File "/opt/paddle/paddle/build/test/auto_parallel/test_tuning_recompute.py", line 100, in test_recompute_pass
    self.assertGreater (
AssertionError: 0 not greater than 0
```

**Comment by JZ-LIANG** [comment]
非常感谢，很详细分析，我们将尽快修复

**Comment by zlsh80826** [comment]
Hi @JZ-LIANG,
PR-55165 能夠 cherry-pick 到 release/2.5 嗎?
