### ISSUE TITLE
test_uniform_random_inplace_op.py bug report

### ISSUE THREAD

**Issue by thaibabao2002** [PaddlePaddle/Paddle#55062]
### bug描述 Describe the Bug

in eagar_model.cc has this warning:
![image](https://github.com/PaddlePaddle/Paddle/assets/76588198/7b24be1a-88ab-4a69-9cd3-540d3d86f79f)
but, in Paddle/test/legacy_test/test_uniform_random_inplace_op.py
have this:
![image](https://github.com/PaddlePaddle/Paddle/assets/76588198/23c42966-f76a-4e34-a21f-9040551f56e8)
this will generate a warning even when using paddleOCR version 2.5. please fix this bug.

### 其他补充信息 Additional Supplementary Information

when fixed, please notify gmail thaibabaoa2@gmail.com to help me

**Comment by wanghuancoder** [comment]
感谢您的反馈我们将尽快修复。

**Comment by wanghuancoder** [comment]
请@zhwesky2010看一下这个问题。

**Comment by zhwesky2010** [comment]
@thaibabao2002 你好，这个只涉及0D Tensor，由于以前被当做shape为[1]的1D Tensor来使用，所以有不少历史代码可能对0D Tensor使用了 Tensor.numpy()[0]的错误用法，这里进行警告。

如果不是0D Tensor，则跟这里的警告没有任何关系，这里的shape是(1000, 784)，是2D Tensor与0D无关。
