### ISSUE TITLE
集群训练一段时间后无状态日志，且GPU/CPU util为0

### ISSUE THREAD

**Issue by xdsoul** [PaddlePaddle/Paddle#5506]
fc模型，2分类，800K fea，到2500batch后无任何状态日志输出，Job没有失败，且查看CPU/GPU利用率为0.

另外，某个阶段发生过这样的错误：
`
File "./gvpoints.py", line 26, in
JOB_ID = os.environ['PBS_JOBID'] 
File "/usr/lib64/python2.6/UserDict.py", line 22, in __getitem__ 
raise KeyError(key) 
KeyError: 'PBS_JOBID' 
`

**Comment by gongweibao** [comment]
请在HI上给我具体的链接，多谢。
