### ISSUE TITLE
Unset RUN_TYPE attribute for multi-GPU unittests

### ISSUE THREAD

**Issue by leo0519** [PaddlePaddle/Paddle#55079]
### 需求描述 Feature Description

For unit tests that use multiple GPUs, their property `RUN_TYPE` should be set `DIST` or `EXCLUSIVE`. This property is important for users and CI to tell an UT is single card or multiple card test. However, we found that there are still multi-GPU UTs without this attribute. We hope Paddle CI could detect this problem.

### 替代实现 Alternatives

- For single card tests (no `RUN_TYPE` attribute), make the visible GPU device of unit test application to be one.

**Comment by leo0519** [comment]
Example PR: https://github.com/PaddlePaddle/Paddle/pull/55125

**Comment by jeng1220** [comment]
After discussing with PaddlePaddle CI developer, it is difficult to identify how many GPUs are needed by an unittest before running the unittest. Thus, this issue will not be solved. Closing the issue.
