### ISSUE TITLE
Windows下利用QT编写的包含paddle_inference推理模型的软件发行到其他电脑中，没有确实dll的提示，但是执行模型推理会导致软件闪退。（推理模型能正常加载，只有推理会闪退，但发行版本的软件在开发电脑中正常运行

### ISSUE THREAD

**Issue by elkslanlanlan** [PaddlePaddle/Paddle#55082]
### 请提出你的问题 Please ask your question

Windows下利用QT编写的包含paddle_inference推理模型的软件发行到其他电脑中，没有确实dll的提示，但是执行模型推理会导致软件闪退。（推理模型能正常加载，只有推理会闪退，但发行版本的软件在开发电脑中正常运行
排除了海康SDK、opencv等的问题，要发行的电脑中配置了和开发电脑一致的cuda和cudnn，软件在新电脑中其他功能包括相机取图及显示，opencv处理等功能均正常，但加载模型后调用模型进行推理就会闪退。
发行软件的文件夹中包含的paddle动态库如下：
test_seg.dll、test_seg.lib、libiomp5md.dll、mkldnn.dll 、mklml.dll 、paddle_inference.dll
其中，test_seg.dll为使用VS生成的模型加载及推理接口动态库。
是否缺少了其他paddle推理模型必备的动态库导致发行的软件闪退呢？

**Comment by yuanlehome** [comment]
你好，一般来说gpu推理的话，只需要paddle_inference.dll就可以了。1. 使用的paddle版本是多少？ 2. export GLOG_v=5 打印下日志并贴上截图看一下。
