### ISSUE TITLE
download mkldnn/mklml failed

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#5508]
make[2]: *** [third_party/mklml/src/extern_mklml-stamp/extern_mklml-download] 错误 4
make[1]: *** [CMakeFiles/extern_mklml.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....

**Comment by luotao1** [comment]
可能是网速原因，导致mklml下载不成功。下面是手动下载的方法：
1. 进入对应的目录：
```
cd build/third_party/mklml/src/extern_mklml
```
2. 查看下包的大小， 正常情况下是75M，如果小于75M，即下载失败。
```
du -sh mklml_lnx_2018.0.1.20171007.tgz
```
3.  手动下载且解压缩，并手动生成download成功标签：
```
wget --no-check-certificate https://github.com/01org/mkl-dnn/releases/download/v0.11/mklml_lnx_2018.0.1.20171007.tgz -c -O mklml_lnx_2018.0.1.20171007.tgz 
tar zxf mklml_lnx_2018.0.1.20171007.tgz
touch ../extern_mklml-stamp/extern_mklml-download
```
4.  删掉已有的mkldnn目录，原因是https://github.com/PaddlePaddle/Paddle/pull/5492 更新了mkldnn的tag
```
rm -r build/third_party/mkldnn
rm -r build/third_party/install/mkldnn
```

接着编译即可。

**Comment by pkuyym** [comment]
Please make sure SSL connection supported by your network.

**Comment by jacquesqiao** [comment]
在服务器上下载速度及其慢，mklml为啥用这种方式发布源代码？

**Comment by luotao1** [comment]
@jacquesqiao 
> 在服务器上下载速度及其慢

公司内部服务器使用代理后（或者有外网权限），下载速度还是很快的。

> mklml为啥用这种方式发布源代码

mklml发布的不是源码，只是一个动态库。目前tensorflow和mxnet都采用了mklml库。
