### ISSUE TITLE
中东地区无法访问paddle文档（中/英）

### ISSUE THREAD

**Issue by eva2show** [PaddlePaddle/Paddle#55096]
### 文档链接&描述 Document Links & Description

如题：我刚出差到阿联酋做项目，但是在这边换了几个网络都打不开paddle官网。
![image](https://github.com/PaddlePaddle/Paddle/assets/137694327/c47f7d33-5d52-4e4f-99f2-27f79b876593)

### 请提出你的建议 Please give your suggestion

希望有个全球站点，国外也能正常访问使用。

**Comment by luotao1** [comment]
@eva2show 我们正在申请海外的CDN。

> 刚出差到阿联酋做项目

请问是做和Paddle相关的项目么？

**Comment by eva2show** [comment]
准备在项目中使用paddle来做ai相关的部分，现在可以访问了。 有机会也会向国外的公司推荐，加油paddle
