### ISSUE TITLE
源码编译win32的build错误

### ISSUE THREAD

**Issue by h4444433333** [PaddlePaddle/Paddle#55095]
### 请提出你的问题 Please ask your question

CMake Error at cmake/third_party.cmake:43 (message):
  Failed to get submodule, please check your network !
Call Stack (most recent call first):
  CMakeLists.txt:578 (include)
如上是错误信息，可以我已经安全上网，我的系统是win10 cmake是3.26.4，目前卡在这怎么也编译不过去。

**Comment by risemeup1** [comment]
这个是在下载第三方库，应该是无法访问外网github的问题
