### ISSUE TITLE
The way to solve the error complaint in MKLDNNLayer

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/Paddle#5510]
When building the latest paddle, one may meet the error in MKLDNNLayer:

 ```
error: no matching function for call to 'mkldnn::sum::primitive_desc::primitive_des(mkldnn::memory::desc, std::vector<float>&, std::vector<mkldnn::memory::primitive_desc>&)' 
```
 
 @luotao1 provides one solution that removes the related subdirectories in the ```build``` directory:
 
 ```
rm -r build/third_party/mkldnn
rm -r build/third_party/install/mkldnn
 ```
 
 If similar errors occur in this layer, please try the same solution first.

**Comment by tensor-tang** [comment]
That's is the common issue when third party update.
I have even encountered an similar issue when engine updated.

Just rm the older build and rebuild again.
