### ISSUE TITLE
我想做一个重复视频检测，有没有什么现成的模型？

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/Paddle#55106]
### 请提出你的问题 Please ask your question

具体的需求，希望能找出用户上传的视频是不是已经存在了，或者是不是由其他视频拼接、加工产生的。我初步的想法是将视频转换成一秒一张的图片序列，然后将图片用resnet、PP-LCNetv2这些模型提取特征，然后计算两个视频图片的相似度。但是在不训练的情况下，提取出来的特征区分度不高（预训练的1000维），难以判断哪些内容是重复的。自行标注训练成本又大
有没有什么专门处理这种情况的模型，或者其他一些思路？

**Comment by TingquanGao** [comment]
有尝试过PP-ShiTu的特征提取模型吗？

https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/PP-ShiTu/feature_extraction.md

**Comment by zouhan6806504** [comment]
> 有尝试过PP-ShiTu的特征提取模型吗？
> 
> https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/PP-ShiTu/feature_extraction.md

我用的模型是https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/inference/PPLCNetV2_base_infer.tar
就是这个里面的backbone吧，效果不是很好

**Comment by TingquanGao** [comment]
转到这边吧：
https://github.com/PaddlePaddle/PaddleClas/issues/2868
