### ISSUE TITLE
paddle.fluid.dataloader 接口换到哪里了呢

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#55108]
### 请提出你的问题 Please ask your question

`paddle.fluid.dataloader`这个接口没了？啥时候没的？

AttributeError: module 'paddle.fluid' has no attribute 'dataloader'

**Comment by will-jl944** [comment]
使用的Paddle版本是什么？你需要使用Paddle的动态图还是静态图模式？

**Comment by Ligoml** [comment]
<img width="805" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39876205/d57a7461-0957-48a4-ade3-262eb8a7f371">
