### ISSUE TITLE
How to save and load PaddleOCR model?

### ISSUE THREAD

**Issue by lukasugar** [PaddlePaddle/Paddle#55139]
### 请提出你的问题 Please ask your question

How to save PaddleOCR model? How to load it afterwards from the saved file?

I'd like to have something like this:
```
import PaddleOCR

model = PaddleOCR(use_angle_cls=True, lang='en')

save_path = '/some/custom/path'

# Save model - how?
model.save(save_path,...) # How to write this?

# Load model - how?
model = # load model from save_path
```

**Comment by will-jl944** [comment]
你需要保存训练过程中的checkpoint，用于恢复训练？还是已经完成训练，需要保存模型用于后续部署？

前者会在训练过程中自动保存。后者可以参考对应模型的模型导出与部署文档，以文字识别模型为例：https://github.com/PaddlePaddle/PaddleOCR/blob/b8888627a59985f361e419f6f624a77839c8ad14/doc/doc_ch/recognition.md#4-%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA%E4%B8%8E%E9%A2%84%E6%B5%8B
