### ISSUE TITLE
paddle的PTQ量化方法的开源案例哪里可以找到

### ISSUE THREAD

**Issue by wangqr2023** [PaddlePaddle/Paddle#55134]
### 请提出你的问题 Please ask your question

当前paddleSlim的开源案例，以及paddleNLP仓中的GPT-3的量化模型(https://paddlefleetx.bj.bcebos.com/model/nlp/gpt/GPT_345M_QAT_w_analysis.tar)都是基于QAT量化方法实现的，没有找打PTQ量化方法的开源案例，希望可以告知paddle哪里可以找到PTQ量化方法的开源案例

**Comment by will-jl944** [comment]
PTQ量化需要先将动态图模型导出为部署模型，具体可以参考此处的[教程](https://paddleslim.readthedocs.io/zh_CN/develop/quick_start/dygraph/dygraph_quant_post_tutorial.html)。

如果需要量化GPT-3模型，PTQ策略可能会对模型效果有较大影响，建议使用PaddleNLP提供的模型压缩示例。

**Comment by wangqr2023** [comment]
https://paddleslim.readthedocs.io/zh_CN/develop/quick_start/dygraph/dygraph_quant_post_tutorial.html，按照这个教程执行，生成的模型还是quant算子后面紧跟一个dequant算子，貌似还是QAT的量化方法。如下图所示：
![量化](https://github.com/PaddlePaddle/Paddle/assets/47288636/c1a50c2f-29ee-4fcd-9571-29f180451da4)


按照https://github.com/PaddlePaddle/Paddle/blob/develop/test/quantization/test_ptq.py的方法执行，生成的模型中也是quant算子后面紧跟一个dequant算子。我理解PTQ量化方法生成的模型应该是需要量化的算子（例如matmul）前面插入一个quat算子，后面插入一个dequat算子，而不是matmul算子前面插入quant+dequat算子，后面插入quat+dequant算子

**Comment by zzjjay** [comment]
‘quant 算子后紧跟着dequant 算子’ 这种形式都是为了方便在paddle上进行模拟量化，验证精度。
如果需要 [ quant + matmul + dequant ] 的结构，可以在调用paddleslim.quant.quant_post_static 时设置onnx_format = False 即可。
