### ISSUE TITLE
在arm平台编译出现”不支持的重定位”错误

### ISSUE THREAD

**Issue by Heraldic-Beast-Leo** [PaddlePaddle/Paddle#55140]
### 请提出你的问题 Please ask your question

在鲲鹏920处理器的UOS系统上编译2.4.0版本的Paddle，GCC版本8.3.0，python版本3.9.0，在编译任务总体进度进行到97%时出现如下错误。
[ 97%] Built target fluid_lib_dist
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_NotImplementedStruct' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): in function `_Py_DECREF':
/opt/Python-3.9.5/./Include/object.h:422:(.text+0x9c): dangerous relocation: 不支持的重定位
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `PyExc_TypeError' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): in function `binop_type_error':
/opt/Python-3.9.5/Objects/abstract.c:886:(.text+0xcc): dangerous relocation: 不支持的重定位
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `_Py_NotImplementedStruct' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): in function `_Py_DECREF':
/opt/Python-3.9.5/./Include/object.h:422:(.text+0x104): dangerous relocation: 不支持的重定位
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `PyExc_TypeError' which may bind externally can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): in function `binary_op':
/opt/Python-3.9.5/Objects/abstract.c:902:(.text+0x148): dangerous relocation: 不支持的重定位
/usr/bin/ld: /usr/local/python39/lib/libpython3.9.a(abstract.o): relocation R_AARCH64_ADR_PREL_PG_HI21 against symbol `PyCFunction_Type' which may bind externally can not be used when making a shared object; recompile with -fPIC

中间都是各种不支持的重定位
到最后是如下
'
/usr/bin/ld: 最后的链结失败: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/fluid/pybind/CMakeFiles/paddle.dir/build.make:2356：paddle/fluid/pybind/libpaddle.so] 错误 1
make[1]: *** [CMakeFiles/Makefile2:143317：paddle/fluid/pybind/CMakeFiles/paddle.dir/all] 错误 2
make: *** [Makefile:133：all] 错误 2

**Comment by FlyingQianMM** [comment]
您是使用我们提供的docker进行编译的吗？建议按照教程里面编译哈，https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/guides/hardware_support/rocm_docs/paddle_install_cn.html

**Comment by Heraldic-Beast-Leo** [comment]
> 您是使用我们提供的docker进行编译的吗？建议按照教程里面编译哈，https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/develop/guides/hardware_support/rocm_docs/paddle_install_cn.html

我一开始是按照文档使用develop分支进行编译，并且成功编译了的，但是实际调用时出现错误。在issues中查询到是paddlepaddle版本过高的原因，因此切换到2.4.0版本进行编译。才出现是上述错误。

**Comment by FlyingQianMM** [comment]
你是用我们提供的docker进行编译的吗？你试下不用使用这么高版本的python，换成python3.8试试。
![image](https://github.com/PaddlePaddle/Paddle/assets/22235422/0596b1c7-4691-4da2-88a0-3d55d1b0e4f5)
