### ISSUE TITLE
飞浆教程文档里面可以加上数据集的下载链接吗

### ISSUE THREAD

**Issue by LatinaDaisuki** [PaddlePaddle/Paddle#55146]
最近在学深度学习，看着飞浆教程文档写代码，但是在[手写数字识别](https://www.paddlepaddle.org.cn/tutorials/projectdetail/4906311) 里，文档直接就写了句“在本地./work/目录下读取文件名称为mnist.json.gz的MNIST数据”
`datafile = './work/mnist.json.gz'`
`print('loading mnist dataset from {} ......'.format(datafile))`
`data = json.load(gzip.open(datafile))`
`print('mnist dataset load done')`
因为教程没有提供数据集下载，我就在spyder上用
`import paddle.vision.datasets as datasets`
`train_dataset = datasets.MNIST(mode='train')`
`test_dataset = datasets.MNIST(mode='test')`
下载了数据集，后面也去Kaggle看了MNIST数据集，都没有后缀为.json.gz格式的文件，但是飞浆教程的代码又是需要解析json的，就卡在这了
![image](https://github.com/PaddlePaddle/Paddle/assets/85465394/11cd235e-c32b-4bd0-abec-4a6b3f8e9fec)

**Comment by FlyingQianMM** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/22235422/9800baaa-f772-4772-9ba8-812b351f58a7)

网页最上面有个『在线运行代码』，点击进入AIStudio的项目，里面有附文件名称为mnist.json.gz的MNIST数据
