### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.tensor.o2ps'

### ISSUE THREAD

**Issue by Ywenjun123** [PaddlePaddle/Paddle#55155]
### 问题描述 Please describe your issue

import paddle时候报错

ModuleNotFoundError: No module named 'paddle.tensor.o2ps'

**Comment by FlyingQianMM** [comment]
麻烦提供下paddle版本和机器环境

**Comment by Ywenjun123** [comment]
之前好用的突然就不好用了，我重新安装了下Paddle就好了

**Comment by Ywenjun123** [comment]
> 麻烦提供下paddle版本和机器环境


之前好用的突然就不好用了，我重新安装了下Paddle就好了
