### ISSUE TITLE
How to enable Timer in v2 API.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#5516]
I want to profile one of my models to get information about when doing forward-backward computation how much time each layer takes. There is a `Timer` in PaddlePaddle's codes, but I am not sure how to enable it in V2 API.

**Comment by ranqiu92** [comment]
To enable the timer, you should modify the NeuralNetwork.cpp and set-DWITH_TIMER=ON when configuring PaddlePaddle's compiling  options.
In the method `forward` of NeuralNetwork.cpp,  comment and add some codes as follows:
```c++
      //REGISTER_TIMER_INFO("ForwardTimer", layer->getName().c_str());
      auto name = "forward_test@" + layer->getName();
      auto stat = getStat(name);
      TimerOnce timer(stat.get(), name.c_str(), 1*1LU);
```
These codes indicate that a timer will calculate how long it takes for a layer or a network to forward each time and print the information if the time spent is over the threshold specified. Here 1*1LU means the threshold is 1us.  Some log is as follows:
```
I1115 00:42:28.517575 17348 Stat.h:204] Stat: [forward_test@__slope_intercept_layer_11__@__recurrent_group_2__] forward_test@__slope_intercept_layer_11__@__recurrent_group_2__ [Span:0ms38us]
I1115 00:42:28.517660 17348 Stat.h:204] Stat: [forward_test@__recurrent_group_2__] forward_test@__recurrent_group_2__ [Span:208ms320us]
I1115 00:42:28.518602 17348 Stat.h:204] Stat: [forward_test@__slope_intercept_layer_11__] forward_test@__slope_intercept_layer_11__ [Span:0ms926us]
I1115 00:42:28.518664 17348 Stat.h:204] Stat: [forward_test@__addto_8__] forward_test@__addto_8__ [Span:0ms45us]
I1115 00:42:28.518725 17348 Stat.h:204] Stat: [forward_test@__slope_intercept_layer_12__] forward_test@__slope_intercept_layer_12__ [Span:0ms47us]
```
The way to get time information about backward process is straightforward.

**Comment by luotao1** [comment]
Should we develop a profile tool like https://movidius.github.io/ncsdk/tools/profile.html?
