### ISSUE TITLE
深信服adesk云桌面vgpu安装paddle

### ISSUE THREAD

**Issue by smallsung1999** [PaddlePaddle/Paddle#55187]
### 问题描述 Issue Description

I0706 09:12:05.859525 3295570 execution_config.cc:106] place:Place(gpu:0), processor_count:8, device_count:8, serial_run:0, num_host_threads:4, num_device_threads:1
I0706 09:12:05.859545 3295570 execution_config.cc:151] ExecutionConfig:
create_local_scope = 0
used_for_cinn = 0
used_for_control_flow_op = 0
used_for_jit = 0
deivce_num_threads = 1
host_num_threads = 4
force_root_scope_vars = []
jit_input_vars = []
skip_gc_vars = []
I0706 09:12:05.859679 3295570 new_executor_defs.cc:49] Set local scope: 0
I0706 09:12:05.859714 3295570 standalone_executor.cc:112] Run job (0), type = default, micro_batch_id =0
I0706 09:12:05.859751 3295570 cuda_info.cc:252] SetDeviceId 0
I0706 09:12:05.859771 3295570 program_interpreter.cc:171] New Executor is Running.
I0706 09:12:05.859786 3295570 interpreter_util.cc:1026] Creating Variables
I0706 09:12:05.859807 3295570 scope.cc:199] Create variable create_parameter_0.w_0
I0706 09:12:05.859828 3295570 interpreter_util.cc:1058] Create Variable create_parameter_0.w_0 global, which pointer is 0x5589385b4800 type is 7
I0706 09:12:05.859850 3295570 scope.cc:199] Create variable create_parameter_1.w_0
I0706 09:12:05.859866 3295570 interpreter_util.cc:1058] Create Variable create_parameter_1.w_0 global, which pointer is 0x558938b65920 type is 7
I0706 09:12:05.859884 3295570 scope.cc:199] Create variable feed
I0706 09:12:05.859900 3295570 interpreter_util.cc:1058] Create Variable feed global, which pointer is 0x558937bfb2a0 type is 9
I0706 09:12:05.859916 3295570 scope.cc:199] Create variable fetch
I0706 09:12:05.859932 3295570 interpreter_util.cc:1058] Create Variable fetch global, which pointer is 0x558938b6c990 type is 10
I0706 09:12:05.859951 3295570 interpreter_util.cc:304] CreateOp from : fill_constant
I0706 09:12:05.859979 3295570 interpreter_util.cc:304] CreateOp from : uniform_random
I0706 09:12:05.860005 3295570 interpreter_util.cc:496] Static build: 0
I0706 09:12:05.860023 3295570 conditional_block_op_helper.cc:108] Found conditional_block op num: 0, conditional_block_grad op num: 0
I0706 09:12:05.860040 3295570 while_op_helper.cc:154] Found while op num: 0, while grad op num: 0
I0706 09:12:05.860057 3295570 recurrent_op_helper.cc:259] Found recurrent op num: 0, recurrent grad op num: 0
I0706 09:12:05.860080 3295570 interpreter_util.cc:262] gc map size:0
I0706 09:12:05.860095 3295570 interpreter_util.cc:524] Build OpFuncNode from : fill_constant
I0706 09:12:05.860128 3295570 interpreter_util.cc:596] fill_constant : [execution_stream, stream_priority, scheduling_priority] = [DefaultStream, 0, 0]
I0706 09:12:05.860147 3295570 interpreter_util.cc:604] Start run Place(gpu:0) Op(fill_constant), inputs:{}, outputs:{Out[create_parameter_0.w_0:[0]({})()]}.
I0706 09:12:05.860191 3295570 interpreter_util.cc:614] OP is not null
I0706 09:12:05.860208 3295570 interpreter_util.cc:617] get op_with_kernel
I0706 09:12:05.860224 3295570 interpreter_util.cc:622] get RuntimeContext
I0706 09:12:05.860241 3295570 context_pool.cc:62] DeviceContextPool Get: Place(gpu:0)
W0706 09:12:05.860392 3295570 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
I0706 09:12:05.860535 3295570 dynamic_loader.cc:220] Try to find library: libcudnn.so from default system path.
W0706 09:12:05.862012 3295570 gpu_resources.cc:149] device: 0, cuDNN Version: 8.2.

执行run_check后卡在这里一直不动，请问是哪里的问题呢？

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 0.0.0
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: 10.0.0-4ubuntu1 
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.10.12

CUDA version: 11.2.152
Build cuda_11.2.r11.2/compiler.29618528_0
cuDNN version: 8.2.1
Nvidia driver version: 470.103.01
Nvidia driver List: 
GPU 0: NVIDIA A16-4Q
CPU:AMD EPYC 73F3 16-Core Processor

****************************************
<img width="566" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/23568937/49483dbd-cc69-4f44-8f65-8747d3d87597">

**Comment by zhengqiwen1997** [comment]
建议cuda版本也变成11.2，而不是11.4

**Comment by smallsung1999** [comment]
> 建议cuda版本也变成11.2，而不是11.4


W0706 09:12:05.860392 3295570 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 11.4, Runtime API Version: 11.2
nvcc -V可以看到CUDA已经是11.2了 按照官网上的版本来的

**Comment by zhengqiwen1997** [comment]
可以试试将nvdia-smi的版本降级成11.2，或者升级到11.6。
或者试试将gcc版本升级到12.2
