### ISSUE TITLE
seq2seq 模型训练

### ISSUE THREAD

**Issue by 13488862011** [PaddlePaddle/Paddle#552]
我用训练数据是100w，训练了4轮，大概对了下对训练集的拟合还较好，准确率为90%以上，但在测试集合上的效果较差，准确率仅为10%-20%左右，这个有什么办法解决吗，多谢

**Comment by lcy-seso** [comment]
（1）准确率 90% 以上是指每个时间步，每个词分类的准确率吗？（2）训练数据和测试数据是同源数据吗？测试数据和训练数据分布有差别吗？（3）能否提供配置，以及训练日志（或者截图）呢？

**Comment by 13488862011** [comment]
目前目标是根据一个时序序列预测可能的序列，模型训练好后，对已有的样本进行预测，得到预测的准确率；
训练数据和测试数据是同源数据，但可能分布会有一些差异；

**Comment by lcy-seso** [comment]
意思是不是说，训练了一个squence generation model （encoder/decoder结构），测试：给定当前词，预测下一个词的准确率，在训练集合和测试集合上预测下一个词准确率有较大的差异，对吗？

（1）seq2seq 模型，在训练集上给定当前词预测下一个词，拟合精度到 0.93 是非常罕见的。能够具体描述一下这是一个什么样的任务吗？比如：翻译， 改写？还是其他呢？
（2）可以提供训练配置和完整训练日志吗？
