### ISSUE TITLE
cannot import name 'deprecated' from 'typing_extensions' 

### ISSUE THREAD

**Issue by uesrs** [PaddlePaddle/Paddle#55206]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/118713813/2de312cc-6253-439c-b45c-34a1f0d46b6a)

**Comment by winter-wang** [comment]
我们会在 https://github.com/PaddlePaddle/Paddle/issues/55202 中持续跟进。同一个问题不需要重复提issue。
