### ISSUE TITLE
 cannot import name 'deprecated' from 'typing_extensions' 

### ISSUE THREAD

**Issue by uesrs** [PaddlePaddle/Paddle#55202]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/118713813/5304415d-a707-4bec-b730-14f8333bf034)

**Comment by winter-wang** [comment]
请问你这个的python和paddle分别用的哪个版本？

**Comment by uesrs** [comment]
> 请问你这个python和paddle分别用哪个版本？

python                    3.7.16 
paddlepaddle-gpu          2.4.2.post117

**Comment by winter-wang** [comment]
需要你帮忙提供可以可复现样例，我们这边复现一下。
