### ISSUE TITLE
Location of `mean` method implementation

### ISSUE THREAD

**Issue by tomaszgrygiel-identt** [PaddlePaddle/Paddle#55218]
### 请提出你的问题 Please ask your question

Hello,

I'm trying to pinpoint where exactly in paddle C++ code can I find the implementation of `mean` function. I noticed that `paddle.mean` returns slightly different results than `torch.mean` for the same inputs and I was wondering why. If I try calculating mean using `paddle.sum()` and `paddle.divide()`, I get the same result as `pytorch.mean()`, but I can't obtain exact result of `paddle.mean()` using other basic `paddle` operations.

**Comment by csy0225** [comment]
Can you provide a detailed description of your use case？
1. For python api: 
You can find the operator mapped by thIS API is reduce_mean.  In this file: python/paddle/tensor/stat.py
2. Find corresponding implementations based on different devices，for cpu，you can find it in Paddle/paddle/phi/kernels/cpu/reduce_mean_kernel.cc
