### ISSUE TITLE
Implement Affine Grid Function

### ISSUE THREAD

**Issue by kiran-shahid** [PaddlePaddle/Paddle#55258]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

**Comment by Bobholamovic** [comment]
Please give a detailed description on the feature request, e.g. what the feature is and why this feature is required. It is difficult for us to speculate a full picture of the feature only from the title.

**Comment by Bobholamovic** [comment]
Please check if [this API](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/nn/functional/affine_grid_en.html) is what you want.
