### ISSUE TITLE
DOC issue in paddle math.py logit

### ISSUE THREAD

**Issue by MuhammadNizamani** [PaddlePaddle/Paddle#55252]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/logit_en.html#logit

the documentation says that logit take data type float32 and float 64
![doc](https://github.com/PaddlePaddle/Paddle/assets/49721249/840e01e8-c91d-4e49-a49d-5a8a6d436a06)

but when I take a look at source of the logit in paddle I saw it is allowed  float16, float32 and float64

![sorepaddle](https://github.com/PaddlePaddle/Paddle/assets/49721249/341e71ac-4af8-46f9-9846-61130b3ac0dc)

I thinks it is a issue and I want to contribute

### 请提出你的建议 Please give your suggestion

I will submit the PR if this issue is correct.

**Comment by MuhammadNizamani** [comment]
@LiYuRio can I create PR for that?

**Comment by LiYuRio** [comment]
Sure, we are glad to see your contribution. But I suggest you to check whether the the dygragh support float16 datatype
