### ISSUE TITLE
import paddle报错提示未定义的符号，ImportError: /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: deflate

### ISSUE THREAD

**Issue by sxl1993** [PaddlePaddle/Paddle#55257]
### 问题描述 Issue Description

x86_64环境，python版本3.8.1，
源码编译paddle-xpu后，import paddle，报错提示未定义的符号
ImportError: /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/libpaddle.so: undefined symbol: deflate
编译命令如下：
cmake .. -DPY_VERSION=3.8\
         -DPADDLE_VERSION=0.0.0 \
         -DWITH_MKL=OFF\
         -DWITH_TESTING=OFF\
         -DCMAKE_BUILD_TYPE=Release\
         -DWITH_DISTRIBUTE=ON \
         -DPY_PIP="/usr/local/lib/python3.8/dist-packages/pip" \
         -DON_INFER=ON\
         -DWITH_PYTHON=ON\
         -DWITH_CRYPTO=ON\
         -DWITH_XBYAK=OFF\
         -DCMAKE_CXX_FLAGS="-Wno-error -w"\
         -DWITH_GPU=OFF\
         -DWITH_XPU=ON\
         -DWITH_XPU_BKCL=ON\
         -DWITH_PSCORE=OFF

### 版本&环境信息 Version & Environment Information

Error: Can not import paddle core while this file exists: /usr/local/python3/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: N/A
CMake version: version 3.22.2
Libc version: glibc 2.27
Python version: 3.8.1

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by zhengqiwen1997** [comment]
将cmake版本降级到3.18再试试

**Comment by seansxl** [comment]
gcc的版本有要求么

**Comment by sxl1993** [comment]
> 将cmake版本降级到3.18再试试

gcc的版本有要求么

**Comment by zhengqiwen1997** [comment]
gcc 需要8.2
