### ISSUE TITLE
支持4090显卡吗

### ISSUE THREAD

**Issue by ww09057118** [PaddlePaddle/Paddle#55262]
### 请提出你的问题 Please ask your question

支持4090显卡吗

**Comment by Bobholamovic** [comment]
你好，PaddlePaddle框架支持4090显卡。请安装合适的版本的CUDA与cuDNN。

**Comment by ww09057118** [comment]
4090显卡，安装那个版本的CUDA与cuDNN比较和时，驱动安装那个版本比较合适？

**Comment by Bobholamovic** [comment]
> 4090显卡，安装那个版本的CUDA与cuDNN比较和时，驱动安装那个版本比较合适？

你好，这不属于Paddle相关问题。你可以在[NVIDIA官网](https://www.nvidia.com/download/index.aspx)搜索相关信息。

**Comment by vamoslc** [comment]
请问？最后安装了那个版本的cuda与cudnn显卡？

**Comment by CheungZeeCn** [comment]
端水推锅
