### ISSUE TITLE
编译paddle_inference的win32平台时cmake报错：Unknown CMake command "cc_library".

### ISSUE THREAD

**Issue by AckerlyLau** [PaddlePaddle/Paddle#55267]
### 问题描述 Issue Description

![image](https://github.com/PaddlePaddle/Paddle/assets/32513057/7e5e88bb-9719-4807-9869-20248b9b8710)
环境：
Windows 11 Pro 22H2
Visual Studio 17 2022
cmake version 3.26.4

问题描述：
需要使用能够在32位win平台上运行的预测库，但是官网提供的版本只有64位的，于是按照文档提示进行编译。在paddle/build目录下执行
cmake .. -G "Visual Studio 17 2022" -A x86 -T host=x86 -DCMAKE_BUILD_TYPE=Release -DWITH_MKL=ON -DWITH_GPU=OFF -DON_INFER=ON -DWITH_PYTHON=OFF
命令，报错“Unknown CMake command "cc_library".”
似乎是paddle/utils/string/CMakeLists.txt的错误
但是搞不清楚cc_library命令，似乎不是CMakeLists的正常语法，但是网上也没有找到cc_library的详细说明。 

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 32bc8b88d945022b054aa75e700cb5fe044edfc0 （commit ID）
Paddle With CUDA: N/A

OS: Windows 10
GCC version: (MinGW.org GCC-6.3.0-1) 6.3.0
Clang version: N/A
CMake version: version 3.26.4
Libc version: N/A
Python version: 3.7.16
GPU : AMD Ryzen 680M
CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by AckerlyLau** [comment]
使用和文档相同的环境也是同样的报错
![image](https://github.com/PaddlePaddle/Paddle/assets/32513057/ddb2508d-2d04-4008-96fd-1a296fd02d65)

**Comment by zhoutianzi666** [comment]
暂不支持32位程序了。因为里面Paddle涉及好多第三方依赖，这些依赖有一些只能是64位的

**Comment by AckerlyLau** [comment]
> 暂不支持32位程序了。因为里面Paddle涉及好多第三方依赖，这些依赖有一些只能是64位的

但是严格按照文档编译64位的程序也是报这个错误。这个issue似乎和32位没多大关系
