### ISSUE TITLE
[OSError] could not get source code，pyinstaller 保存静态图模型时报错

### ISSUE THREAD

**Issue by Husky1999** [PaddlePaddle/Paddle#55260]
### bug描述 Describe the Bug

工具包版本如下：
paddlepaddle-gpu：2.4.2.post112
pyqt5：5.15.9
python：3.8.17
pyinstaller：5.13.0

报错代码如下：
`net_static = to_static(self.net, input_spec=[InputSpec(shape=[None,
                                                                      self.channel,
                                                                      self.image_size,
                                                                      self.image_size],
                                                               name='x')])
        paddle.jit.save(net_static, self.save_static_path + '/' + self.model_sel)`
使用to_static不报错，paddle.jit.save后报错

报错内容如下：
![fcfd789396c187f725b8a3b57769eab](https://github.com/PaddlePaddle/Paddle/assets/65430413/2fe89f3b-6d58-4046-a5bc-534b704de827)

参考链接：
https://github.com/PaddlePaddle/Paddle/issues/43092
https://github.com/pyinstaller/pyinstaller/issues/6865

**Comment by Bobholamovic** [comment]
你好，实际上这并不是Paddle的问题，在你贴出的[这个回答](https://github.com/pyinstaller/pyinstaller/issues/6865)里已经有详尽的解释。由于Paddle采用解析源码的方式（类似PyTorch的scripting方式）实现动转静，在执行`paddle.jit.save`时，.py格式的源代码文件必须存在，而在不采用特殊配置的情况下，PyInstaller无法满足这一要求。

事实上，我建议你重新考虑当前的需求，即『将模型动转静代码打包进软件中』，是否合理，因为这个需求有些不太符合直觉——一般来说，需要将静态图模型等资源提前准备好，然后再执行最后的打包工序。

**Comment by Husky1999** [comment]
> 你好，实际上这并不是Paddle的问题，在你贴出的[这个回答](https://github.com/pyinstaller/pyinstaller/issues/6865)里已经有详尽的解释。由于Paddle采用解析源码的方式（类似PyTorch的scripting方式）实现动转静，在执行时，.py格式的源代码文件必须存在，而在不采用特殊配置的情况下，PyInstaller无法满足这一要求。`paddle.jit.save`
> 
> 事实上，我建议你重新考虑当前的需求，即『将模型动转静代码打包进软件中』，是否合理，因为这个需求有些不太符合直觉——一般来说，需要将静态图模型等资源提前准备好，然后再执行最后的打包工序。


请问没有解决方法吗，需要将训练、迁移和推理集成在一起，于是动态图和静态图分别进行迁移与推理，本人目前没有其他解决思路

**Comment by Bobholamovic** [comment]
如果确实有『使用打包后的程序进行模型的动转静』的需求，建议将模型定义部分代码以及执行动转静的代码以.py的源代码形式保留，和打包后的程序一起发布，并在程序中通过子进程调用等方式实现模型动转静功能。

**Comment by Husky1999** [comment]
> 

小白了，对这些不了解，请问我将训练及模型保存的代码与inspect.py文件以.py形式放入打包后的文件依然报错，但报错有区别，是还需要将什么包放入吗

最后都是要提交源码的，所以打包形式并不重要，能用就行

报错如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/65430413/bb750e70-0a39-43ce-8d91-6e75087b5f52)


inspect.py代码如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/65430413/135a6b04-0551-4249-8b49-0cc6107cf6e9)

**Comment by Bobholamovic** [comment]
『执行动转静的代码』指的是`paddle.jit.save`调用语句所在的那个.py文件，而不是Python标准库的`inspect.py`。另外，如果只是希望以源码形式发布、不需要编译成二进制文件的话，无需使用pyinstaller，可以直接通过[Python标准方式](https://packaging.python.org/en/latest/tutorials/packaging-projects)将源码打包为wheel、zip、tar等形式。

**Comment by Husky1999** [comment]
> 『执行动转静的代码』指的是`paddle.jit.save`调用语句所在的那个.py文件，而不是Python标准库的`inspect.py`。另外，如果只是希望以源码形式发布、不需要编译成二进制文件的话，无需使用pyinstaller，可以直接通过[Python标准方式](https://packaging.python.org/en/latest/tutorials/packaging-projects)将源码打包为wheel、zip、tar等形式。

非常感谢您的回复，paddle.jit.save那个.py文件拿出后进行打包，在打包后放入依然如上报错，过程如下：

1.在拿出文件后运行打包后程序：
报错没有找到所移出的.py文件
![捕获](https://github.com/PaddlePaddle/Paddle/assets/65430413/2244d956-3e88-4a74-ba2c-394363c69d09)

2.在将.py文件放入后，依然如之前报错
![image](https://github.com/PaddlePaddle/Paddle/assets/65430413/8d0eedba-7bc1-45b2-8a10-1725af64e3c4)

请问具体需要如何操作

或者有什么方法可以将主文件打包为exe，以启动软件，库以源码打包，以解决当前问题

非常感谢您的耐心解答

**Comment by Bobholamovic** [comment]
如果必须将代码打包为exe，同时又希望使用模型动转静功能，建议做如下处理：
1. 将模型定义.py文件以及调用了动转静的.py文件在exe程序以外以『资源』的方式进行管理。你可以查阅[pyinstaller的文档](https://pyinstaller.org/en/stable/spec-files.html#adding-data-files)以了解如何添加和管理这些资源。
2. 编写脚本实现模型动转静功能，具体逻辑为利用[`subprocess.Popen`](https://docs.python.org/zh-cn/3/library/subprocess.html)或者[`os.system`](https://docs.python.org/3/library/os.html#os.system)等手段，通过子进程调用执行动转静的.py脚本。这个新写的脚本也需要打包到exe中。例如：`subprocess.run([sys.executable, 'scripts/export.py', '--model_path', 'model.pdparams'])`将执行`scripts/export.py`脚本，并向其传递一些参数。当然，你可能需要考虑使用的Python解释器版本，因为`sys.executable`对应的解释器并不一定合适。据我所知pyinstaller程序一般会在exe中打包一个python解释器，你可以查阅pyinstaller相关文档以了解如何使用合适的解释器版本以及找到需要的依赖库，这不在本issue的讨论范围。

上述做法的打包产出是一个exe文件+一些外部资源。

**Comment by Bobholamovic** [comment]
除了子进程调用以外，Python的内建函数`exec`也是一个可选项，甚至通过`import`也可以实现类似的功能，但我觉得在这种情况下使用子进程调用更加显式、更符合直觉。不过，无论使用上述哪种方式，都请注意可能为你的软件带来的风险：当用户了解到上述原理后，可以通过修改软件附带的源代码的方式，轻松地更改软件的行为。如果这是你预期的行为（例如你希望通过这种方式为软件提供一定的可扩展性），那么一切都好；如果你不希望用户能够『自定义网络结构』或者『自定义导出方式』，我建议在打包进exe的脚本中添加一次安全检查，例如通过校验md5码防止文件被篡改。

**Comment by Husky1999** [comment]
> 除了子进程调用以外，Python的内建函数`exec`也是一个可选项，甚至通过`import`也可以实现类似的功能，但我觉得在这种情况下使用子进程调用更加显式、更符合直觉。不过，无论使用上述哪种方式，都请注意可能为你的软件带来的风险：当用户了解到上述原理后，可以通过修改软件附带的源代码的方式，轻松地更改软件的行为。如果这是你预期的行为（例如你希望通过这种方式为软件提供一定的可扩展性），那么一切都好；如果你不希望用户能够『自定义网络结构』或者『自定义导出方式』，我建议在打包进exe的脚本中添加一次安全检查，例如通过校验md5码防止文件被篡改。

感谢您的回复

目前方案暂时改以动态图直接进行预测，不进行静态图保存，待后续进行优化时对您所提及的方案进行尝试

**Comment by wangyexiang** [comment]
其实没这么复杂，对吗

**Comment by zhenhuamo** [comment]
请问能解决吗？我也遇到这个问题
