### ISSUE TITLE
GPU版本相关编译问题

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#55276]
### 编译选项CUDA_ARCH_NAME指定为All编译报错

在官方提供的nvidia docker（`docker pull paddlepaddle/paddle:2.5.0-gpu-cuda11.7-cudnn8.4-trt8.4`）上，编译v2.5.0，按照下面编译指令会报错：
```
cmake .. \
-DCMAKE_BUILD_TYPE=Release \
-DPYTHON_EXECUTABLE:FILEPATH=/root/miniconda3/envs/paddle_build/bin/python3.8 \
-DPYTHON_INCLUDE_DIR:PATH=/root/miniconda3/envs/paddle_build/include/python3.8 \
-DPYTHON_LIBRARIES:FILEPATH=/root/miniconda3/envs/paddle_build/lib/libpython3.8.so \
-DWITH_GPU=ON \
-DWITH_TENSORRT=OFF \
-DWITH_ROCM=OFF \
-DWITH_CINN=OFF \
-DWITH_DISTRIBUTE=ON \
-DWITH_MKL=ON \
-DWITH_AVX=ON \
-DCUDA_ARCH_NAME=All \
-DNEW_RELEASE_PYPI=ON \
-DNEW_RELEASE_ALL=OFF \
-DNEW_RELEASE_JIT=OFF \
-DWITH_PYTHON=ON \
-DWITH_TESTING=ON \
-DWITH_COVERAGE=OFF \
-DWITH_INCREMENTAL_COVERAGE=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DWITH_CONTRIB=ON \
-DWITH_INFERENCE_API_TEST=ON \
-DWITH_INFRT=OFF \
-DPY_VERSION=3.8 \
-DWITH_PSCORE=ON \
-DWITH_PSLIB=OFF \
-DWITH_GLOO=ON \
-DLITE_GIT_TAG=release/v2.10 \
-DWITH_XPU=OFF \
-DWITH_MLU=OFF \
-DWITH_IPU=OFF \
-DWITH_CNCL=OFF \
-DXPU_SDK_ROOT= \
-DWITH_LITE=OFF \
-DWITH_XPU_BKCL=OFF \
-DWITH_ARM=OFF \
-DWITH_ASCEND=OFF \
-DWITH_ASCEND_CL=OFF \
-DWITH_ASCEND_INT64=OFF \
-DWITH_STRIP=ON \
-DON_INFER=ON \
-DWITH_HETERPS=OFF \
-DWITH_FLUID_ONLY=OFF \
-DCUDA_ARCH_BIN= \
-DWITH_RECORD_BUILDTIME=OFF \
-DWITH_UNITY_BUILD=OFF \
-DWITH_ONNXRUNTIME=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON

make -j$(nproc)
```

相关错误信息：
```
/usr/lib/x86_64-linux-gnu/crti.o: in function `_init':
(.init+0x7): relocation truncated to fit: R_X86_64_REX_GOTPCRELX against undefined symbol `__gmon_start__'
CMakeFiles/phi.dir/common/place.cc.o: in function `phi::CustomRegisteredDeviceMap::Instance()':
place.cc:(.text+0x3): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0xe): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x1c): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x2f): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x43): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x4a): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x51): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x5c): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x68): relocation truncated to fit: R_X86_64_PC32 against `.bss'
place.cc:(.text+0x6f): additional relocation overflows omitted from the output
/usr/local/bin/ld: failed to convert GOTPCREL relocation; relink with --no-relax
collect2: error: ld returned 1 exit status
paddle/phi/CMakeFiles/phi.dir/build.make:20170: recipe for target 'paddle/phi/libphi.so' failed
make[2]: *** [paddle/phi/libphi.so] Error 1
CMakeFiles/Makefile2:7798: recipe for target 'paddle/phi/CMakeFiles/phi.dir/all' failed
make[1]: *** [paddle/phi/CMakeFiles/phi.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2
Start executing python setup.py bdist_wheel
```

后来在多个issue中也提到相关报错，很多没有解决，在这个[issue](https://github.com/PaddlePaddle/Paddle/issues/46966)中找到解决方法，将`CUDA_ARCH_NAME`指定为`Ampere`，但是这个报错在之前版本中未遇到。
1. 请问一下如果需要编译一个通用的whl包怎么解决呢？
2. 官方的build CI中也是指定`CUDA_ARCH_NAME`，请问release发版的编译是怎么解决这个问题的，官方发版的CD有链接可以看到吗？

**Comment by risemeup1** [comment]
问题1？ 理论上是用all的架构，但现在编译不过，已知问题，phi独立编译在解决这个问题，但是2.5分支没有打进phi独立编译

**Comment by risemeup1** [comment]
问题2:建议用我们官方的编译架构吧，cuda_arch_name=manual, 然后指定了4个架构

**Comment by risemeup1** [comment]
CUDA_ARCH_NAME=Manual
CUDA_ARCH_BIN='61 70 80 86'

**Comment by tiandou-tangdou** [comment]
> 问题1？ 理论上是用all的架构，但现在编译不过，已知问题，phi独立编译在解决这个问题，但是2.5分支没有打进phi独立编译

@risemeup1 请问paddlepaddle2.5发布的官方wheel包怎么编译的？我们想follow官方wheel包的方式，谢谢

**Comment by zepingWww** [comment]
> 



> CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'

@risemeup1 

用这个会报下面这个错误：
```
Traceback (most recent call last):
  File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
    args = parse_args()
  File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
    args = parser.parse_args()
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
    args, argv = self.parse_known_args(args, namespace)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
    take_action(action, args, option_string)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
    value = self._get_value(action, arg_string)
  File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
    result = type_func(arg_string)
  File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
    return find_arch_range(arch[0], arch[-1])
IndexError: list index out of range
CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
  The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
```

**Comment by risemeup1** [comment]
> > 
> 
> > CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'
> 
> @risemeup1
> 
> 用这个会报下面这个错误：
> 
> ```
> Traceback (most recent call last):
>   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
>     args = parse_args()
>   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
>     args = parser.parse_args()
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
>     args, argv = self.parse_known_args(args, namespace)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
>     namespace, args = self._parse_known_args(args, namespace)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
>     start_index = consume_optional(start_index)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
>     take_action(action, args, option_string)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
>     argument_values = self._get_values(action, argument_strings)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
>     value = self._get_value(action, arg_string)
>   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
>     result = type_func(arg_string)
>   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
>     return find_arch_range(arch[0], arch[-1])
> IndexError: list index out of range
> CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
>   The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
> ```

cmake命令是不是写错了

**Comment by zepingWww** [comment]
> > > 
> > 
> > 
> > > CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'
> > 
> > 
> > @risemeup1
> > 用这个会报下面这个错误：
> > ```
> > Traceback (most recent call last):
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
> >     args = parse_args()
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
> >     args = parser.parse_args()
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
> >     args, argv = self.parse_known_args(args, namespace)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
> >     namespace, args = self._parse_known_args(args, namespace)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
> >     start_index = consume_optional(start_index)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
> >     take_action(action, args, option_string)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
> >     argument_values = self._get_values(action, argument_strings)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
> >     value = self._get_value(action, arg_string)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
> >     result = type_func(arg_string)
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
> >     return find_arch_range(arch[0], arch[-1])
> > IndexError: list index out of range
> > CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
> >   The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
> > ```
> 
> cmake命令是不是写错了

就加了两句话，也没什么问题吧，请问有release发版的cmake命令可以参考吗

```
cmake .. \
-DCMAKE_BUILD_TYPE=Release \
-DPYTHON_EXECUTABLE:FILEPATH=/root/miniconda3/envs/paddle_build/bin/python3.8 \
-DPYTHON_INCLUDE_DIR:PATH=/root/miniconda3/envs/paddle_build/include/python3.8 \
-DPYTHON_LIBRARIES:FILEPATH=/root/miniconda3/envs/paddle_build/lib/libpython3.8.so \
-DWITH_GPU=ON \
-DWITH_TENSORRT=OFF \
-DWITH_ROCM=OFF \
-DWITH_CINN=OFF \
-DWITH_DISTRIBUTE=ON \
-DWITH_MKL=ON \
-DWITH_AVX=ON \
-DCUDA_ARCH_NAME=Manual \
-DCUDA_ARCH_BIN='61 70 80 86' \
-DNEW_RELEASE_PYPI=ON \
-DNEW_RELEASE_ALL=OFF \
-DNEW_RELEASE_JIT=OFF \
-DWITH_PYTHON=ON \
-DWITH_TESTING=ON \
-DWITH_COVERAGE=OFF \
-DWITH_INCREMENTAL_COVERAGE=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
-DWITH_CONTRIB=ON \
-DWITH_INFERENCE_API_TEST=ON \
-DWITH_INFRT=OFF \
-DPY_VERSION=3.8 \
-DWITH_PSCORE=ON \
-DWITH_PSLIB=OFF \
-DWITH_GLOO=ON \
-DLITE_GIT_TAG=release/v2.10 \
-DWITH_XPU=OFF \
-DWITH_MLU=OFF \
-DWITH_IPU=OFF \
-DWITH_CNCL=OFF \
-DXPU_SDK_ROOT= \
-DWITH_LITE=OFF \
-DWITH_XPU_BKCL=OFF \
-DWITH_ARM=OFF \
-DWITH_ASCEND=OFF \
-DWITH_ASCEND_CL=OFF \
-DWITH_ASCEND_INT64=OFF \
-DWITH_STRIP=ON \
-DON_INFER=ON \
-DWITH_HETERPS=OFF \
-DWITH_FLUID_ONLY=OFF \
-DCUDA_ARCH_BIN= \
-DWITH_RECORD_BUILDTIME=OFF \
-DWITH_UNITY_BUILD=OFF \
-DWITH_ONNXRUNTIME=OFF \
-DCMAKE_EXPORT_COMPILE_COMMANDS=ON

make -j$(nproc)
```

**Comment by zepingWww** [comment]
> > > 
> > 
> > 
> > > CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'
> > 
> > 
> > @risemeup1
> > 用这个会报下面这个错误：
> > ```
> > Traceback (most recent call last):
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
> >     args = parse_args()
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
> >     args = parser.parse_args()
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
> >     args, argv = self.parse_known_args(args, namespace)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
> >     namespace, args = self._parse_known_args(args, namespace)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
> >     start_index = consume_optional(start_index)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
> >     take_action(action, args, option_string)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
> >     argument_values = self._get_values(action, argument_strings)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
> >     value = self._get_value(action, arg_string)
> >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
> >     result = type_func(arg_string)
> >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
> >     return find_arch_range(arch[0], arch[-1])
> > IndexError: list index out of range
> > CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
> >   The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
> > ```
> 
> cmake命令是不是写错了

不好意思，cmake命令确实写错了，现在可以了。
请问一下官方release发版的CD可以给一下吗，想follow一下

**Comment by Aiga-Andrijanova** [comment]
> > > > 
> > > 
> > > 
> > > > CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'
> > > 
> > > 
> > > @risemeup1
> > > Using this will report the following error: 
> > > ```
> > > Traceback (most recent call last):
> > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
> > >     args = parse_args()
> > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
> > >     args = parser.parse_args()
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
> > >     args, argv = self.parse_known_args(args, namespace)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
> > >     namespace, args = self._parse_known_args(args, namespace)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
> > >     start_index = consume_optional(start_index)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
> > >     take_action(action, args, option_string)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
> > >     argument_values = self._get_values(action, argument_strings)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
> > >     value = self._get_value(action, arg_string)
> > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
> > >     result = type_func(arg_string)
> > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
> > >     return find_arch_range(arch[0], arch[-1])
> > > IndexError: list index out of range
> > > CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
> > >   The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
> > > ```
> > 
> > 
> > Is the cmake command wrong?
> 
> Sorry, the cmake command was indeed written wrong, and now it works. May I ask if you can give me the CD of the official release version, I want to follow

What was wrong in your cmake command?

**Comment by zepingWww** [comment]
> > > > > 
> > > > 
> > > > 
> > > > > CUDA_ARCH_NAME=Manual CUDA_ARCH_BIN='61 70 80 86'
> > > > 
> > > > 
> > > > @risemeup1
> > > > Using this will report the following error:
> > > > ```
> > > > Traceback (most recent call last):
> > > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 102, in <module>
> > > >     args = parse_args()
> > > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 97, in parse_args
> > > >     args = parser.parse_args()
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1768, in parse_args
> > > >     args, argv = self.parse_known_args(args, namespace)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1800, in parse_known_args
> > > >     namespace, args = self._parse_known_args(args, namespace)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2006, in _parse_known_args
> > > >     start_index = consume_optional(start_index)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1946, in consume_optional
> > > >     take_action(action, args, option_string)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 1858, in take_action
> > > >     argument_values = self._get_values(action, argument_strings)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2388, in _get_values
> > > >     value = self._get_value(action, arg_string)
> > > >   File "/root/miniconda3/envs/paddle_build/lib/python3.8/argparse.py", line 2421, in _get_value
> > > >     result = type_func(arg_string)
> > > >   File "/home/Paddle/paddle/phi/kernels/fusion/cutlass/memory_efficient_attention/generate_kernels.py", line 78, in convert_to_arch_list
> > > >     return find_arch_range(arch[0], arch[-1])
> > > > IndexError: list index out of range
> > > > CMake Error at paddle/phi/kernels/CMakeLists.txt:69 (message):
> > > >   The memory efficient attention kernel generation errors with NVCC_ARCH_BIN=
> > > > ```
> > > 
> > > 
> > > Is the cmake command wrong?
> > 
> > 
> > Sorry, the cmake command was indeed written wrong, and now it works. May I ask if you can give me the CD of the official release version, I want to follow
> 
> What was wrong in your cmake command?

I write the `CUDA_ARCH_BIN` twice, the later is 'CUDA_ARCH_BIN=' which covers `CUDA_ARCH_BIN='61 70 80 86'`.

**Comment by zepingWww** [comment]
@risemeup1 请问一下能提供官方wheel包编译的流程吗，这个issue还在忘记关闭了
