### ISSUE TITLE
paddlex客户端，在4090显卡上无法训练数据，3090和3080上都是正常的？

### ISSUE THREAD

**Issue by ww09057118** [PaddlePaddle/Paddle#55288]
### 请提出你的问题 Please ask your question

paddlex客户端，在4090显卡上无法训练数据，3090和3080上都是正常的，怎么解决？

**Comment by Birdylx** [comment]
@ww09057118 请确认下paddle、CUDA版本等，执行`paddle.utils.run_check()`确保paddle在4090能上能跑通。

**Comment by CheungZeeCn** [comment]
应该是不支持 4090 吧， 对应的cuda 12 不支持？
