### ISSUE TITLE
升级到Paddle推理库2.5版本后，PaddleOCR使用Mkldnn识别模型准确率严重下降

### ISSUE THREAD

**Issue by sdcb** [PaddlePaddle/Paddle#55290]
### bug描述 Describe the Bug

基于Windows，PaddleOCR PPOCR-v3模型
这是PaddleInference 2.5版本的PaddleOCR 识别模型返回的结果：
![image](https://github.com/PaddlePaddle/Paddle/assets/1317141/6763ef75-85e4-4eb2-9240-a9d392780b90)

这是PaddleInference 2.4.1版本的PaddleOCR 识别模型返回的结果：
![image](https://github.com/PaddlePaddle/Paddle/assets/1317141/40244229-82d2-4122-87e8-de4da8488426)

完整可复现代码如下：
[ppocr-v4-online-debug.linq.txt](https://github.com/PaddlePaddle/Paddle/files/11999718/ppocr-v4-online-debug.linq.txt)
（请切换为.linq后缀我，用LINQPad打开运行，使用PaddleInference 2.5时可以切换为安装Sdcb.PaddleInference.runtime.win64.mkl.2.5.0-preview.3 nuget包

### 其他补充信息 Additional Supplementary Information

经调查，发现只有Paddle Inference 2.5的Mkldnn有关，使用Openblas、Onnx、GPU都正常。

另外我再附加一个关联问题（PaddleOCR v4模型使用Mkldnn在非AVX512 CPU上变得非常慢 #10337）：
https://github.com/PaddlePaddle/PaddleOCR/issues/10337

**Comment by Birdylx** [comment]
@sdcb 
2.4的推理库性能也很差吗？可以在PaddleOCR的issue中同步下该问题

**Comment by sdcb** [comment]
@Birdylx PaddleOCR v4模型识别阶段性能差和推理库版本号无关，v3性能也差。

**Comment by sdcb** [comment]
经调查，PaddleInference 2.5使用PaddleOCR识别模型时准确率低，是因为未删除mkldnn的几个pass造成的，加上下面的代码准确率瞬间恢复、问题解决：
```csharp
PaddleDevice.Mkldnn().And(c =>
	{
		// 重点
		c.DeletePass("fc_mkldnn_pass");
		c.DeletePass("fc_act_mkldnn_fuse_pass");
	})
```

**Comment by raoyutian** [comment]
解决方案：
第一种，
paddle_inference代码中的paddle\fluid\inference\api\paddle_pass_builder.cc文件void CpuPassStrategy::EnableMKLDNN()
代码中，注释两个pass,fc_mkldnn_pass,fc_act_mkldnn_fuse_pass,这两个在之前版本就是注释的，2.5被取消注释。影响OCR识别精度降低，
第二种，
PaddleOCR代码删除这两个pass
pass_builder->DeletePass("fc_mkldnn_pass");
pass_builder->DeletePass("fc_act_mkldnn_fuse_pass");
推荐第二种，第一种更改了不知道会不会影响模块。

**Comment by xlg-go** [comment]
> ```cs
> fc_mkldnn_pass
> ```

大佬，用你的paddleSharp，2.5版本的gpu，rec识别不对，很奇怪
