### ISSUE TITLE
模型加载预测问题

### ISSUE THREAD

**Issue by zzwtop1** [PaddlePaddle/Paddle#55303]
### 请提出你的问题 Please ask your question

自然语言处理的预测问题，目前找到的文档，train_loader和test_loader都是使用DataLoader函数加载数据，并用drop_last参数将最后一个mini-batch不足一个batch_size的数据丢弃，训练的时候多跑几轮，使用drop_last没问题，但是预测的时候也使用drop_last，给了你一个测试集，结果丢掉一部分数据不预测了？？！如果给了你255条测试数据，batch_size设置成128，相当于只预测了128条数据，这时候计算的准确率真的准确吗？我有点想不明白，特别是要用于推理时，如果给你一条数据让你分类，难道要复制成128份才能进行分类？

**Comment by kangguangli** [comment]
你好，请问你的意思是说：
文档中的示例代码应该使用drop_last = False吗？我理解这里其实只是一个示例，演示下API用法，作为用户可以根据自己的需要设置True或False。
不过你说的问题确实是存在的，如果真的设置了drop_last = True，准确率比起drop_last = False很可能不一样。可以发下具体的代码位置，我们评估下要不要修改。如果你有兴趣的话，也欢迎提一个PR，流程可以参考 [代码贡献指南](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/code_contributing_path_cn.html)。
