### ISSUE TITLE
麒麟系统编译paddle时cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON \          -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF \          -DCMAKE_CXX_FLAGS="-Wno-error -w"后报错Do not have AVX2 intrinsics and disabled MKL-DNN.

### ISSUE THREAD

**Issue by Phoenix2Legend** [PaddlePaddle/Paddle#55319]
### bug描述 Describe the Bug

在麒麟v10系统上编译paddle，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。参考文档链接为：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html。在完成cmake操作以后报错，具体报错信息见《其他补充信息 Additional Supplementary Information》。configure done以后自动跳转了两行内容并且终止，不知道什么原因什么意思，求帮助，感谢！

### 其他补充信息 Additional Supplementary Information

-- Do not have AVX2 intrinsics and disabled MKL-DNN.
generate /workspace/Paddle/paddle/fluid/operators/ops_extra_info.cc
Performing Eager Dygraph Auto Code Generation
Final State Eager CodeGen
Generate dygraph file structure at path: /workspace/Paddle/paddle/fluid/eager/generated
Eager prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Static prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Prim tensor operants code generator
copy prim xxx_tensor_operants.tmp to xxx_tensor_operants
WITH_DLNNE:
-- Configuring done
-- Generating done
-- Build files have been written to: /workspace/Paddle/build
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop}          -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF \
> 
bash: -DWITH_TESTING=OFF：未找到命令
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop}          -DCMAKE_CXX_FLAGS="-Wno-error -w"

**Comment by Phoenix2Legend** [comment]
随后执行make TARGET=ARMV8 -j$(nproc)以后报错：
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:94：third_party/openblas/src/extern_openblas-stamp/extern_openblas-download] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make: *** [Makefile:133：all] 错误 2
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 -j$(nproc)
[  1%] Built target extern_gflags
[  1%] Performing download step (git clone) for 'extern_openblas'
[  1%] Built target extern_eigen3
[  1%] Built target extern_pybind
[  1%] Performing configure step for 'extern_warprnnt'
正克隆到 'extern_openblas'...
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log


make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4801：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  1%] Built target extern_threadpool
[  1%] Built target extern_dlpack
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：Failed to connect to github.com port 443: 连接超时
正克隆到 'extern_openblas'...
-- Had to git clone more than once:
          2 times.
注意：正在切换到 'v0.3.7'。

您正处于分离头指针状态。您可以查看、做试验性的修改及提交，并且您可以在切换
回一个分支时，丢弃在此状态下所做的提交而不对分支造成影响。

如果您想要通过创建分支来保留在此状态下所做的提交，您可以通过在 switch 命令
中添加参数 -c 来实现（现在或稍后）。例如：

  git switch -c <新分支名>

或者撤销此操作：

  git switch -

通过将配置变量 advice.detachedHead 设置为 false 来关闭此建议

HEAD 目前位于 5f36f1814 Update with 0.3.7 changes
[  1%] No update step for 'extern_openblas'
[  1%] No patch step for 'extern_openblas'
[  1%] No configure step for 'extern_openblas'
[  1%] Performing build step for 'extern_openblas'
make[3]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
ger.c: 在函数‘sger_’中:
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:836：sger.o] 错误 1
make[4]: *** 正在等待未完成的任务....
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:864：sgemv.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make: *** [Makefile:133：all] 错误 2
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop}

**Comment by kangguangli** [comment]
第一个问题：
> configure done以后自动跳转了两行内容并且终止，不知道什么原因什么意思，求帮助，感谢！
应该是往shell中粘贴多行的命令被截断了

第二个问题：
> fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时

有些第三方库下载需要开启代理，这里可能`openblas`只下了一部分文件，导致编译错误

**Comment by Phoenix2Legend** [comment]
> 第一个问题：
> 
> > configure done以后自动跳转了两行内容并且终止，不知道什么原因什么意思，求帮助，感谢！
> > 应该是往shell中粘贴多行的命令被截断了
> 
> 第二个问题：
> 
> > fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时
> 
> 有些第三方库下载需要开启代理，这里可能`openblas`只下了一部分文件，导致编译错误

谢谢，请问第二个问题中函数有变量未声明应该这么修改呢？

**Comment by Phoenix2Legend** [comment]
其中还有一条报错：
/bin/sh：./getarch：权限不够
有影响吗？要怎么解决呢？

**Comment by Phoenix2Legend** [comment]
make后完整报错内容如下：

λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 -j$(nproc)
[  0%] Performing build step for 'extern_openblas'
make[3]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
[  1%] Built target extern_lapack
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
[  1%] Built target extern_eigen3
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/ops/compat/signatures.h
[  1%] Built target copy_signatures_command
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/funcs/jit/kernels.h
[  1%] copy_if_different /workspace/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  1%] Built target copy_kernels_command
[  1%] Built target copy_paddle_inference_pass_command
[  1%] copy_if_different /workspace/Paddle/buλ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 -j$(nproc)
[  0%] Performing build step for 'extern_openblas'
make[3]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
[  1%] Built target extern_lapack
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
[  1%] Built target extern_eigen3
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/ops/compat/signatures.h
[  1%] Built target copy_signatures_command
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/funcs/jit/kernels.h
[  1%] copy_if_different /workspace/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  1%] Built target copy_kernels_command
[  1%] Built target copy_paddle_inference_pass_command
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/declarations.h
[  1%] Built target copy_declarations_command
[  2%] Built target extern_gflags
[  2%] copy_if_different /workspace/Paddle/build/paddle/fluid/pybind/pybind.h
[  2%] Built target extern_zlib
[  2%] Built target copy_pybind_command
Scanning dependencies of target extern_warpctc
[  3%] Built target extern_cryptopp
[  3%] Creating directories for 'extern_warprnnt'
[  3%] Creating directories for 'extern_warpctc'
[  3%] Creating directories for 'extern_threadpool'
[  3%] No download step for 'extern_warpctc'
[  3%] No download step for 'extern_warprnnt'
[  3%] No download step for 'extern_threadpool'
[  3%] No patch step for 'extern_warprnnt'
[  3%] No patch step for 'extern_warpctc'
[  3%] No patch step for 'extern_threadpool'
[  3%] No update step for 'extern_warprnnt'
[  3%] No update step for 'extern_warpctc'
[  3%] No update step for 'extern_threadpool'
[  3%] Performing configure step for 'extern_warpctc'
[  3%] Performing configure step for 'extern_warprnnt'
[  3%] No configure step for 'extern_threadpool'
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log


make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4801：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  3%] No build step for 'extern_threadpool'
[  3%] No install step for 'extern_threadpool'
[  3%] No test step for 'extern_threadpool'
[  3%] Completed 'extern_threadpool'
[  3%] Built target extern_threadpool
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
ger.c: 在函数‘sger_’中:
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:864：sgemv.o] 错误 1
make[4]: *** 正在等待未完成的任务....
make[4]: *** [Makefile:836：sger.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
-- extern_warpctc configure command succeeded.  See also /workspace/Paddle/build/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-configure-*.log
[  3%] Performing build step for 'extern_warpctc'
Scanning dependencies of target warpctc
[ 50%] Building CXX object CMakeFiles/warpctc.dir/src/ctc_entrypoint.cpp.o
[100%] Linking CXX shared library libwarpctc.so
[100%] Built target warpctc
[  3%] Performing install step for 'extern_warpctc'
[100%] Built target warpctc
Install the project...
-- Install configuration: "Release"
-- Installing: /workspace/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Installing: /workspace/Paddle/build/third_party/install/warpctc/include/ctc.h
[  3%] Completed 'extern_warpctc'
[  3%] Built target extern_warpctc
make: *** [Makefile:133：all] 错误 2
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} ild/paddle/phi/kernels/declarations.h
[  1%] Built target copy_declarations_command
[  2%] Built target extern_gflags
[  2%] copy_if_different /workspace/Paddle/build/paddle/fluid/pybind/pybind.h
[  2%] Built target extern_zlib
[  2%] Built target copy_pybind_command
Scanning dependencies of target extern_warpctc
[  3%] Built target extern_cryptopp
[  3%] Creating directories for 'extern_warprnnt'
[  3%] Creating directories for 'extern_warpctc'
[  3%] Creating directories for 'extern_threadpool'
[  3%] No download step for 'extern_warpctc'
[  3%] No download step for 'extern_warprnnt'
[  3%] No download step for 'extern_threadpool'
[  3%] No patch step for 'extern_warprnnt'
[  3%] No patch step for 'extern_warpctc'
[  3%] No patch step for 'extern_threadpool'
[  3%] No update step for 'extern_warprnnt'
[  3%] No update step for 'extern_warpctc'
[  3%] No update step for 'extern_threadpool'
[  3%] Performing configure step for 'extern_warpctc'
[  3%] Performing configure step for 'extern_warprnnt'
[  3%] No configure step for 'extern_threadpool'
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log


make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4801：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  3%] No build step for 'extern_threadpool'
[  3%] No install step for 'extern_threadpool'
[  3%] No test step for 'extern_threadpool'
[  3%] Completed 'extern_threadpool'
[  3%] Built target extern_threadpool
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
ger.c: 在函数‘sger_’中:
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:864：sgemv.o] 错误 1
make[4]: *** 正在等待未完成的任务....
make[4]: *** [Makefile:836：sger.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
-- extern_warpctc configure command succeeded.  See also /workspace/Paddle/build/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-configure-*.log
[  3%] Performing build step for 'extern_warpctc'
Scanning dependencies of target warpctc
[ 50%] Building CXX object CMakeFiles/warpctc.dir/src/ctc_entrypoint.cpp.o
[100%] Linking CXX shared library libwarpctc.so
[100%] Built target warpctc
[  3%] Performing install step for 'extern_warpctc'
[100%] Built target warpctc
Install the project...
-- Install configuration: "Release"
-- Installing: /workspace/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Installing: /workspace/Paddle/build/third_party/install/warpctc/include/ctc.h
[  3%] Completed 'extern_warpctc'
[  3%] Built target extern_warpctc
make: *** [Makefile:133：all] 错误 2
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} 

怎么解决呢，大佬救我!

**Comment by kangguangli** [comment]
> > 第一个问题：
> > > configure done以后自动跳转了两行内容并且终止，不知道什么原因什么意思，求帮助，感谢！
> > > 应该是往shell中粘贴多行的命令被截断了
> > 
> > 
> > 第二个问题：
> > > fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时
> > 
> > 
> > 有些第三方库下载需要开启代理，这里可能`openblas`只下了一部分文件，导致编译错误
> 
> 谢谢，请问第二个问题中函数有变量未声明应该这么修改呢？

我猜这个应该是没下完导致的

**Comment by kangguangli** [comment]
> 其中还有一条报错： /bin/sh：./getarch：权限不够 有影响吗？要怎么解决呢？

看起来getarch是openblas编译的产物

目前看应该就是网络问题导致依赖文件没下完吧，可以把build目录删掉重编试试

**Comment by Phoenix2Legend** [comment]
您好，删掉重试还是一样的问题，请问是帮助文档中给的cmake命令有误嘛？

**Comment by kangguangli** [comment]
> 您好，删掉重试还是一样的问题，请问是帮助文档中给的cmake命令有误嘛？

如果还是一样的问题，可以确认下你的网络问题解决了吗？有没有成功下载好第三方库呢？
比如说针对上面的openblas，可以确认下 `third_party/openblas`里面的文件是否完整

**Comment by Phoenix2Legend** [comment]
> > 您好，删掉重试还是一样的问题，请问是帮助文档中给的cmake命令有误嘛？
> 
> 如果还是一样的问题，可以确认下你的网络问题解决了吗？有没有成功下载好第三方库呢？ 比如说针对上面的openblas，可以确认下 `third_party/openblas`里面的文件是否完整

您好，这个文件完整性需要和什么对比呢？您上面说的有些第三方库需要开启代理是指什么呢？静候回应。

**Comment by kangguangli** [comment]
> fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时

完整性可以对比 这里的 `https://github.com/xianyi/OpenBLAS.git/`
关于开启代理，可以全程开启代理，特别是针对github链接。如果你的网络情况稳定，也可以不开启。

**Comment by Phoenix2Legend** [comment]
> 



> > fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时
> 
> 完整性可以对比 这里的 `https://github.com/xianyi/OpenBLAS.git/` 关于开启代理，可以全程开启代理，特别是针对github链接。如果你的网络情况稳定，也可以不开启。

您说的需要开启代理的部分是cmake部分吧？

**Comment by kangguangli** [comment]
> > 
> 
> > > fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时
> > 
> > 
> > 完整性可以对比 这里的 `https://github.com/xianyi/OpenBLAS.git/` 关于开启代理，可以全程开启代理，特别是针对github链接。如果你的网络情况稳定，也可以不开启。
> 
> 您说的需要开启代理的部分是cmake部分吧？

是的。不过make的时候可能也有下载文件的需求，可以先不开启，如果遇到问题再开启也可以。

**Comment by Phoenix2Legend** [comment]
> > > > fatal: 无法访问 '[https://github.com/xianyi/OpenBLAS.git/'：Failed](https://github.com/xianyi/OpenBLAS.git/'%EF%BC%9AFailed) to connect to github.com port 443: 连接超时
> > > 
> > > 
> > > 完整性可以对比 这里的 `https://github.com/xianyi/OpenBLAS.git/` 关于开启代理，可以全程开启代理，特别是针对github链接。如果你的网络情况稳定，也可以不开启。
> > 
> > 
> > 您说的需要开启代理的部分是cmake部分吧？
> 
> 是的。不过make的时候可能也有下载文件的需求，可以先不开启，如果遇到问题再开启也可以。

如果cmake结束以后显示configure done，算不算成功呢？既然这样为什么make以后还是报错呢？

**Comment by kangguangli** [comment]
算成功。make阶段如果报上面的错，可以开启代理再试试。

**Comment by Phoenix2Legend** [comment]
> 算成功。make阶段如果报上面的错，可以开启代理再试试。

总之您的意思是我上面的报错是网络问题导致的第三方库文件下载不全是吗

**Comment by kangguangli** [comment]
应该是的

**Comment by Phoenix2Legend** [comment]
> 应该是的

谢谢，我再试试！
