### ISSUE TITLE
paddleOCR的DBnet模型在昇腾训练服务器上训练，出现性能下降问题

### ISSUE THREAD

**Issue by old-steel** [PaddlePaddle/Paddle#55324]
### 问题描述 Please describe your issue

环境： kunpeng920  昇腾910训练八卡
操作系统：open Eular，
镜像：基于飞桨提供的ubuntu镜像
执行代码：
https://github.com/PaddlePaddle/PaddleOCR
训练模型：paddleOCR DBnet  
训练命令：python3 -m paddle.distributed.launch --gpus '0,1,2,3,4,5,6,7'  tools/train.py -c  configs/det/det_r50_vd_db.yml
问题描述：
训练性能在300epoch后逐步下降，定位发现在dataload上耗时逐步增加，可通过查看日志中打印的“avg_reader_cost“，可发现，在前300epoch的平均耗时为1.4s，在端到端的“avg_reader_cost“平均耗时在2.6s，说明dataload的耗时在逐步增加。

诉求：修复该问题

**Comment by kangguangli** [comment]
已在内部反馈，感谢反馈，我们会尽快跟进下这个问题。

**Comment by qili93** [comment]
hi，您好，

由于飞桨框架和昇腾CANN适配正在进行中，目前Paddle+昇腾组合支持模型有限，PaddleOCR 目前暂不在支持范围内。

我们会记录您的需求，待后续规划对OCR模型在昇腾上的适配和性能优化进行定位，谢谢！
