### ISSUE TITLE
单测报错信息优化（二期）

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#55348]
## 任务描述

任务需求来自 #44641，细节可以看一下 [框架易用性提升——单测报错信息优化](https://github.com/PaddlePaddle/community/blob/master/rfcs/CodeStyle/20220805_code_style_improvement_for_unittest.md)

简单来说就是我们当时处理了 `self.assertTrue(np.allclose(...))` 这种情况，而没有处理 `assert np.allclose(...)` 这种情况，这次准备处理下后者啦～

## 任务拆分

| 序号 | 任务描述 | 认领人 | 提交 PR |
|-|-|-|-|
| 1 | 替换 `assert np.allclose` | @zrr1999 | #55385 |
| 2 | 替换 `assert np.array_equal` | @zrr1999 | #55385 |
| 3 | CI 流水线中上线 `assert np.allclose/np.array_equal` 的监控（可参考 #45126） | @gouzil | #55355 |

**Comment by zrr1999** [comment]
认领 1 2

**Comment by gouzil** [comment]
认领3
