### ISSUE TITLE
[CustomDevice] 框架传入set和调用传入的 device id 不统一造成错误

### ISSUE THREAD

**Issue by tiandou-tangdou** [PaddlePaddle/Paddle#55340]
### bug描述 Describe the Bug

测试代码：使用paddlepaddle2.5.0 CPU + 插件
```
import paddle
paddle.set_device('npu:2') #此处不设置为0
x = paddle.to_tensor([1])
x
```

Paddle/paddle/fluid/pybind/tensor_py.h 中 SetTensorFromPyArrayT customdevice使用了DeviceGuard
```
    platform::Place tmp_place = place;
    LOG(WARNING) << "before gurad: place " << place;
    phi::DeviceGuard guard(tmp_place);
    auto dst = self->mutable_data<T>(place);

    phi::DeviceManager::GetDeviceWithPlace(tmp_place)->MemoryCopyH2D(
        reinterpret_cast<void *>(dst),
        const_cast<void *>(reinterpret_cast<const void *>(array.data())),
        array.nbytes());
    platform::DeviceContextPool &pool = platform::DeviceContextPool::Instance();
    auto &ctx = *pool.Get(place);
    ctx.Wait();
    LOG(WARNING) << "after ctx.Wait ";
```

在paddle2.5中，目前customdevice会默认设置比如npu:0, https://github.com/PaddlePaddle/Paddle/pull/53842/files
如果设置npu:2则此处 DeviceGuard 会保留 prev_id为0，并setdevice为2，在出DeviceGuard 时，会由guard析构函数恢复设置为0

但x做输出的时要D2H，没有使用DeviceGuard，做之前会Wait一下，调用SyncStream时，由于框架此时传进来的deviceid为2，但在guard析构时已经setdevice为0，则会报错，过程信息为：
![image](https://github.com/PaddlePaddle/Paddle/assets/5997715/07129301-5f44-4e00-be79-3f614edb0c93)

这里我理解可以在对应 tensor_method_numpy 同样使用DeviceGuard解决，但是想要框架侧明确的是：

其它地方是否会存在类似这个问题？
需要插件中针对每个接口都需要检查device和device->id吗？

**Comment by ronny1996** [comment]
你好，如果担心其他地方存在这类问题，可以在插件中检查 device->id，这个问题问题我会在develop上修复

**Comment by tiandou-tangdou** [comment]
> 你好，如果担心其他地方存在这类问题，可以在插件中检查 device->id，这个问题问题我会在develop上修复

@ronny1996 你好，这个PR这样改DeviceGuard功能本身好像不太对了是吗

**Comment by ronny1996** [comment]
@tiandou-tangdou 后面会考虑移除或者修改，DeviceGuard 会导致频繁调用 SetDevice

**Comment by tiandou-tangdou** [comment]
> @tiandou-tangdou 后面会考虑移除或者修改，DeviceGuard 会导致频繁调用 SetDevice

@ronny1996 好的
