### ISSUE TITLE
Paddle Op Reg and Dispatch/ flat hash map

### ISSUE THREAD

**Issue by KimBioInfoStudio** [PaddlePaddle/Paddle#55349]
### 请提出你的问题 Please ask your question

请问有详细的资料 是 关于 Paddle Op Reg / Dispatch 吗

- flat hash map 中的 存贮结构 和 数据类型是什么
- torch 和 paddle 在 op reg / dispatch 中 design  有何不同
- capi 和 c++ api 的中 Op reg 和 Dispatch 有何不同

PaddleCustomDevice intel_gpu 在使用 c++ api 注册算子时，发现 custom device op reg 时， flat hash map rehash中使用的 deallocate 与 llvm base 的 compiler 不兼容 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/utils/flat_hash_map.h#L753

**Comment by KimYannn** [comment]
cc @YanhuiDua @ronny1996 @qili93  @kevinyuk @yangulei @BaihuiJin @ChengleiTian @tangleintel @chaofanl

**Comment by KimYannn** [comment]
@USTCKAY 可以高优先级看下这个问题吗，这对我们实现 PaddleCustomDevice 非常重要

**Comment by ronny1996** [comment]
@KimBioInfoStudio 你好，c++ api是abi不兼容的，如果要使用c++ api适配intel gpu，需要用与plugin相同的编译器编译paddle，甚至有些编译选项也会导致不兼容。
capi 只是将 c++ api 用 c 函数包了一下再暴露接口，实现被隐藏，使用 capi 适配时应该只使用 paddle 中 header-only的 c++ 头文件。
具体你碰到的问题，还需要进一步分析错误信息，推荐是只使用 capi 和 paddle 中 header-only 的 c++ 头文件避免 c++ 的问题。

**Comment by KimYannn** [comment]
> @KimBioInfoStudio 你好，c++ api是abi不兼容的，如果要使用c++ api适配intel gpu，需要用与plugin相同的编译器编译paddle，甚至有些编译选项也会导致不兼容。 capi 只是将 c++ api 用 c 函数包了一下再暴露接口，实现被隐藏，使用 capi 适配时应该只使用 paddle 中 header-only的 c++ 头文件。 具体你碰到的问题，还需要进一步分析错误信息，推荐是只使用 capi 和 paddle 中 header-only 的 c++ 头文件避免 c++ 的问题。

现在情况是这样的

1. 使用 flat hash map + cxx api,  intel_gpu 在初始化的时候就会挂掉
2. 使用 std::unordered_map + cxx api,  intel_gpu 的全部 op search的时候 全部被 fallback cpu, 这个可能是 ABI 问题还在排查

**Comment by ronny1996** [comment]
@KimBioInfoStudio 你好，一定要使用 cxx api + llvm 的话，建议插件对需要 llvm 编译的部分进行封装，导出 c api，插件主体调用 c api 并使用 gcc 编译

**Comment by KimYannn** [comment]
> @KimBioInfoStudio 你好，一定要使用 cxx api + llvm 的话，建议插件对需要 llvm 编译的部分进行封装，导出 c api，插件主体调用 c api 并使用 gcc 编译

我们目前还是在使用capi 进行开发，但是像 fused ops这些接口只提供了c++ api, 所以我们一边在进行 capi 的前进，另一方面探索改用 cxxapi

目前基于 cxx api 的探索包括
1.  替换 hash_map （WIP， LLVM 编译）
2.  将注册宏剥离，使用 gcc 编译 （WIP， Mix 编译）
3.  使用 cxx api 写 kernel 主体， 使用 c api 宏 注册 （Okay， LLVM编译）

**Comment by ronny1996** [comment]
请问 fused ops 具体使用了哪些 c++ api，可以在 PaddleCustomDevice 提需求，我们会评估支持 capi

**Comment by KimYannn** [comment]
现在主要看到的是下面两个
```c++
PD_BUILD_OP
PD_BUILD_GRAD_OP
```

**Comment by ronny1996** [comment]
好的，我反馈一下，关于这两个接口支持capi
