### ISSUE TITLE
Compile chunk eval op failed

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#5535]
chunk_eval_op.cc:48:23: 错误：‘paddle::framework::DataType paddle::operators::ChunkEvalOp::IndicateDataType(const paddle::framework::ExecutionContext&) const’ marked override, but does not override
   framework::DataType IndicateDataType(
                       ^
make[2]: *** [paddle/operators/CMakeFiles/chunk_eval_op.dir/chunk_eval_op.cc.o] 错误 1
make[1]: *** [paddle/operators/CMakeFiles/chunk_eval_op.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....

**Comment by luotao1** [comment]
The same error to me

**Comment by pkuyym** [comment]
I'm working on it.
