### ISSUE TITLE
LayerNorm forward perf regression

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#55352]
### bug描述 Describe the Bug

We observe ~1.5% perf regression in BERT pretraining and squad finetuing since paddle2.4. In paddle v2.4 and v2.5, LayerNormForward becomes much slower than v2.3 because fast kernel is disabled. 

- In Paddle2.3, `ln_fwd_1024_kernel` is called when hidden size=1024, which is very fast.
- Since Paddle 2.4,  @limin2021 set `can_call_fast_kernel = false` to disable the fast kernel. So, the slower kernel `LayerNormForward` will be called. Refer to [layer_norm_kernel.cu#L608](https://github.com/PaddlePaddle/Paddle/blob/be3a6fa7e494df3871685c13cfc0c19a87c86083/paddle/phi/kernels/gpu/layer_norm_kernel.cu#L608) in [PR#43118](https://github.com/PaddlePaddle/Paddle/pull/43118).
- In Paddle 2.5, after change above line to `can_call_fast_kernel = true`, the fast kernel `fast_ln_fwd_kernel` will be used. (The `fast_ln_fwd_kernel` is an extention of `ln_fwd_1024_kernel` and performs almost as well as paddle 2.3.)
- We also noticed that @JamesLim-sy add `LayerNormFwdWithWelford` recently to optimize layer norm forward in [PR#50362](https://github.com/PaddlePaddle/Paddle/pull/50362)

**Why is [`can_call_fast_kernel`](https://github.com/PaddlePaddle/Paddle/blob/be3a6fa7e494df3871685c13cfc0c19a87c86083/paddle/phi/kernels/gpu/layer_norm_kernel.cu#L608) is hard-coded to `false` in all cases? Any concern on precision?**

benchmark case (from SQuAD finetuning): [batch_size, seqlen, hidden_size] = [16, 384, 1024]
A100 80GB
| kernel name | kernel overhead (micro second) |
|--|--------------------------------|
| ln_fwd_1024_kernel (2.3) | 28 |
| LayerNormForward (2.4 & 2.5) | 84 |
| LayerNormFwdWithWelford (2.5+FLAGS_use_fast_math) | 56 |
| fast_ln_fwd_kernel (2.5+can_call_fast_kernel = true) | 30 |

**Comment by Wong4j** [comment]
Hi @sneaxiy , you are the reviewer of [PR#43118](https://github.com/PaddlePaddle/Paddle/pull/43118). Could you please take a look?

**Comment by sneaxiy** [comment]
This PR https://github.com/PaddlePaddle/Paddle/pull/43118 may be a mistake. Thanks for pointing out!

**Comment by jeng1220** [comment]
@sneaxiy ,
We saw many UT failed if `can_call_fast_kernel` = True, such as:
* test_fused_feedforward_pass (Failed)
* test_fused_attention_pass (Failed)
* test_sparse_fused_attention_op (Failed)
* test_trt_convert_layer_norm (Failed)
* test_trt_convert_preln_residual_bias (Failed)
* test_trt_subgraph_pass.TensorRTSubgraphPassLayerNormBeginNormAxis2Test (Failed)
```python
AssertionError: 
Not equal to tolerance rtol=1e-05, atol=1e-05
Output has diff between inference and training forward at GPU 
Mismatched elements: 9215 / 12288 (75%)
Max absolute difference: 2.1435788
Max relative difference: 1.
 x: array([[[[ 1.605187,  0.084684, -0.048107, ..., -0.694687, -0.064943,
           0.552144],
         [ 1.007104, -1.665734,  0.811047, ...,  0.322182, -1.461859,...
 y: array([[[[ 1.605187,  0.084684, -0.048107, ..., -0.694687, -0.064943,
           0.552144],
         [ 1.007104, -1.665734,  0.811047, ...,  0.322182, -1.461859,...
```

**Comment by Wong4j** [comment]
[PR#43118](https://github.com/PaddlePaddle/Paddle/pull/43118)  claimed to extend the fast kernel from only supporting 1024 cols to supporting more cols, such as 768, 2048, 4096.
But I found that it still only works properly in the case of 1024.  When the cols in [768, 2048, 3072, 4096], the error will be very large.

```
AssertionError:
Not equal to tolerance rtol=0.0001, atol=0.0001

Mismatched elements: 2094192 / 2097152 (99.9%)
Max absolute difference: 2.6936824
Max relative difference: 91685.56
 x: array([[ 0.765701,  0.236014,  0.093661, ...,  0.551912,  0.344408,
        -0.081736],
       [-0.872823,  1.397171, -0.38428 , ...,  0.922817,  1.698386,...
 y: array([[ 0.776374,  0.22161 ,  0.079338, ...,  0.328588,  0.858359,
        -0.629368],
       [-0.855279,  1.404663, -0.368853, ...,  1.707707,  1.150643,...
```

To reproduce, 

1. set `can_call_fast_kernel = true` ([layer_norm_kernel.cu#L608](https://github.com/PaddlePaddle/Paddle/blob/be3a6fa7e494df3871685c13cfc0c19a87c86083/paddle/phi/kernels/gpu/layer_norm_kernel.cu#L608)) and recompile Paddle.
2. set the shape from 1024 to 768 in this line - [test_layer_norm_op.py#L716](https://github.com/PaddlePaddle/Paddle/blob/bc153701da60fd042335177c6bf2f145f38fc90b/test/legacy_test/test_layer_norm_op.py#L716)
3. run the UT.  `python test_layer_norm_op.py`

**Comment by jeng1220** [comment]
> [PR#43118](https://github.com/PaddlePaddle/Paddle/pull/43118) claimed to extend the fast kernel from only supporting
> ...
> To reproduce,
> 
> 1. set `can_call_fast_kernel = true` ([layer_norm_kernel.cu#L608](https://github.com/PaddlePaddle/Paddle/blob/be3a6fa7e494df3871685c13cfc0c19a87c86083/paddle/phi/kernels/gpu/layer_norm_kernel.cu#L608)) and recompile Paddle.
> 2. set the shape from 1024 to 768 in this line - [test_layer_norm_op.py#L716](https://github.com/PaddlePaddle/Paddle/blob/bc153701da60fd042335177c6bf2f145f38fc90b/test/legacy_test/test_layer_norm_op.py#L716)
> 3. run the UT.  `python test_layer_norm_op.py`

@sneaxiy ,

It is OOB access bug.

```sh
$ compute-sanitizer python -m pytest -v -k test_check_forward_backward_with_scale_and_bias ./test_layer_norm_op.py

========= Invalid __global__ read of size 16 bytes
=========     at 0x2b0 in /opt/paddle/paddle/paddle/phi/kernels/funcs/aligned_vector.h:38:void phi::Load<float, (int)4>(const T1 *, phi::AlignedVector<T1, T2> *)
=========     by thread (97,0,0) in block (121,0,0)
=========     Address 0x7f6273de7010 is out of bounds
=========     and is 102384 bytes before the nearest allocation at 0x7f6273e00000 of size 1572864 bytes
=========     Device Frame:/opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:230:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)4, (int)1, (int)16, (int)1024, (int)32, (int)32, (int)128, (int)4, (int)128, (int)8>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *) [0x2b0]
```

**Comment by jeng1220** [comment]
If the shape is changed from 1024 to 2048/4096 at [test_layer_norm_op.py#L716](https://github.com/PaddlePaddle/Paddle/blob/bc153701da60fd042335177c6bf2f145f38fc90b/test/legacy_test/test_layer_norm_op.py#L716), it shows data race bug.

```sh
$ compute-sanitizer  --tool racecheck python -m pytest -v -k test_check_forward_backward_with_scale_and_bias ./test_layer_norm_op.py

test_layer_norm_op.py::TestLayerNormOp::test_check_forward_backward_with_scale_and_bias ========= Error: Race reported between Read access at 0x660 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:264:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *)
=========     and Write access at 0x9b0 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:289:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *) [2048 hazards]
=========
========= Error: Race reported between Read access at 0x600 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:259:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *)
=========     and Write access at 0x630 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:261:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *) [1024 hazards]
=========
========= Error: Race reported between Read access at 0x9f0 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:296:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *)
=========     and Write access at 0xa20 in /opt/paddle/paddle/paddle/phi/kernels/funcs/layer_norm_impl.cu.h:298:void phi::funcs::fast_ln_fwd_kernel<float, float, float, (int)4, (int)2, (int)2, (int)16, (int)1024, (int)32, (int)64, (int)128, (int)2, (int)256, (int)4>(int, int, float, const T1 *, const T3 *, const T3 *, T2 *, T2 *, T1 *) [1024 hazards]
=========
FAILED                                                                                                            [100%]
```

**Comment by sneaxiy** [comment]
@jeng1220 OK, I will check it.

**Comment by jeng1220** [comment]
@sneaxiy ,
I updated the debugging message with lineinfo ^^^

**Comment by sneaxiy** [comment]
Thanks a lot @jeng1220

**Comment by jeng1220** [comment]
Addition, the branch I used is release/2.5

**Comment by Wong4j** [comment]
Fixed. Close bug.
