### ISSUE TITLE
_DataLoaderIterMultiProcess encounter error in static graph in Paddle 2.5

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#55362]
### bug描述 Describe the Bug

In paddle v2.5, I got the following error when training BERT using [DeepLearningExamples/PaddlePaddle/LanguageModeling/BERT/run_pretraining.py#L71](https://github.com/NVIDIA/DeepLearningExamples/blob/2693c632d8c29ed75f939b8217b435dca97c3b8f/PaddlePaddle/LanguageModeling/BERT/run_pretraining.py#L71).

Our code works well in paddle v2.3&v2.4. But since v2.5, this line no longer support static graph - [python/paddle/io/dataloader/worker.py#L387](https://github.com/PaddlePaddle/Paddle/blob/006bd959c70eed6f52ff16a290a2cbb6dd9102ee/python/paddle/io/dataloader/worker.py#L387). 

I don't know how to reproduce this bug with simple code yet. **Anyone has any idea?**

Error message:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/io/dataloader/worker.py", line 384, in _worker_loop
    tensor_list = [
  File "/usr/local/lib/python3.10/dist-packages/paddle/io/dataloader/worker.py", line 387, in <listcomp>
    else b.value().get_tensor()
  File "/usr/local/lib/python3.10/dist-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/paddle/fluid/framework.py", line 445, in __impl__
    assert in_dygraph_mode(), (
AssertionError: We only support 'value()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.
```

**Comment by Wong4j** [comment]
Hi @wanghuancoder , could you please take a look?

**Comment by USTCKAY** [comment]
Hi, I tried to reproduce the error but failed to construct the environment. The reason of the error is that method `value()` is only supported in dynamic mode in Paddle 2.5. 
https://github.com/PaddlePaddle/Paddle/blob/6a2db618c6d188e185ecd902f014c0c72fd010b3/python/paddle/fluid/dygraph/tensor_patch_methods.py#L801
This method just returns the input as output, so maybe you could try to change the code from 
`tensor_list = [
                        numpy2lodtensor(b)
                        if isinstance(b, np.ndarray)
                        else b.value().get_tensor()
                        for b in batch
  ]`
to 
`tensor_list = [
                        numpy2lodtensor(b)
                        if isinstance(b, np.ndarray)
                        else b.get_tensor()
                        for b in batch
 ]` to work around the error.

**Comment by Wong4j** [comment]
> Hi, I tried to reproduce the error but failed to construct the environment. The reason of the error is that method `value()` is only supported in dynamic mode in Paddle 2.5.
> 
> https://github.com/PaddlePaddle/Paddle/blob/6a2db618c6d188e185ecd902f014c0c72fd010b3/python/paddle/fluid/dygraph/tensor_patch_methods.py#L801
> 
> 
> This method just return the input as output, so maybe you could try to chage the code from
> `tensor_list = [ numpy2lodtensor(b) if isinstance(b, np.ndarray) else b.value().get_tensor() for b in batch ]`
> to
> `tensor_list = [ numpy2lodtensor(b) if isinstance(b, np.ndarray) else b.get_tensor() for b in batch ]` to work around the error.

Thank you @USTCKAY , I have tried this workaround and it works. 
But this method should support both static and dynamic graph. 
Could you please help to fix this bug? We expected it to be cherry-picked into paddle 2.5.

**Comment by USTCKAY** [comment]
> 

I have committed the fix in https://github.com/PaddlePaddle/Paddle/pull/55541 and https://github.com/PaddlePaddle/Paddle/pull/55545

**Comment by USTCKAY** [comment]
Hi, https://github.com/PaddlePaddle/Paddle/pull/55541 and https://github.com/PaddlePaddle/Paddle/pull/55545 have been mergerd, you can pull the code and try agian. @Wong4j

**Comment by Wong4j** [comment]
Thank you @USTCKAY . Bug fixed, close this issue
