### ISSUE TITLE
使用pphenet-base多卡训练时卡住，占用资源但并不开始训练

### ISSUE THREAD

**Issue by ariessweety07** [PaddlePaddle/Paddle#55370]
### bug描述 Describe the Bug

bug描述 Describe the Bug
![image](https://github.com/PaddlePaddle/Paddle/assets/62364611/dd6a1f56-6dab-4407-9dee-cf1f898467ac)

# model architecture
Arch:
  name: PPHGNet_base_Human
  pretrained: "PPHGNet_base_ssld_pretrained"
  use_ssld: False

任意结构使用这个pphgnet训练时，训练完全卡住，log中未打印报错信息，占用资源但并不进行训练，预训练权重url用在线的会无法download，用本地的绝对路径权重时会卡住

**Comment by USTCKAY** [comment]
Hi，CV模型相关的问题欢迎到PaddleClas repo处提issue哈，地址：https://github.com/PaddlePaddle/PaddleClas/issues

**Comment by TingquanGao** [comment]
转到https://github.com/PaddlePaddle/PaddleClas/issues/2869
