### ISSUE TITLE
【社区治理】zrr1999 发起 Committer 身份申请

### ISSUE THREAD

**Issue by zrr1999** [PaddlePaddle/Paddle#55384]
#### 基本信息

| 申请人 GitHub ID | **Paddle Repo 整体 merge PR 数** | **Paddle Repo 整体 review PR 数** | **Paddle Repo 整体报告 Issue 数** |
| ---------------- | -------------------------------- | --------------------------------- | --------------------------------- |
|   @zrr1999       |      [9(Paddle)](https://github.com/PaddlePaddle/Paddle/pulls/zrr1999)+[11(CINN)](https://github.com/PaddlePaddle/CINN/pulls/zrr1999)+[7(PaddleSOT)](https://github.com/PaddlePaddle/PaddleSOT/pulls/zrr1999) =27     |              0                   |                  [3(CINN)](https://github.com/PaddlePaddle/CINN/issues?q=is%3Aissue+author%3Azrr1999)+[2(PaddleSOT)](https://github.com/PaddlePaddle/PaddleSOT/issues?q=is%3Aissue+author%3Azrr1999+)=5               |

#### 社区贡献概况

以下是此前在本 repo 里做过的贡献：

实现若干 Paddle 算子和 onehot 的 tensorrt 的转换器。
实现若干 CINN 算子、ReverseComputeInline 调度原语、CSE Pass。
参与 CINN 代码风格改进计划。
参与 PaddleSOT 快乐喵喵开源任务和源码阅读 CRC 快乐喵喵之路。

##### 高质量 merge PR 展示

| PR 号          | PR 标题                               | Reviewer                      |
| -------------- | ------------------------------  | ----------------------------- |
|        https://github.com/PaddlePaddle/Paddle/pull/45849        |                【Hackathon No.21】为 Paddle 新增 paddle.incubate.sparse.transpose 稀疏 API                |     |zkh2016,OccupyMars2025,jeff41404,chenwhql,Ligoml,XiaoguangHu01,zhwesky2010     |                               
|       https://github.com/PaddlePaddle/Paddle/pull/51406         |                 【Hackathon 4th No.30】为 Paddle 新增 paddle.sparse.sum 稀疏 API                |         luotao1,jeff41404,zkh2016,umiswing,sunzhongkai588                                         |
|       https://github.com/PaddlePaddle/CINN/pull/897         |                 【PaddlePaddle Hackathon No.78】add gather, gather_nd, scatter and scatter_nd op         |        haozech,zhhsplendid           |                               
| https://github.com/PaddlePaddle/CINN/pull/1331 | [Hackathon NO.84] 为神经网络编译器 CINN 增加 ReverseComputeInline 原语 | BiynXu,CtfGo | 
| https://github.com/PaddlePaddle/PaddleSOT/pull/170 | support property process in TensorVariable | 2742195759,SigureMo,Aurelius84 | 

#### 担保人意见
@Ligoml @luotao1 @SigureMo

**Comment by SigureMo** [comment]
同意～

@zrr1999 在 Paddle、CINN（已合入 Paddle repo）、PaddleSOT（未来合入 Paddle repo）贡献了很多高质量的 PR，每个任务都能够很好地独立完成，对问题有着较为深刻的见解，为 Paddle 做出了突出的贡献，相信以后也会继续为 Paddle 做出更多有价值的贡献～

PS: 一点小小的建议，以后有时间可以尝试 review 一些代码了（可以先从 PaddleSOT 开始），review 往往能更好地证明对整个项目的熟悉程度～

**Comment by Ligoml** [comment]
同意~ @zrr1999 同学技术扎实，积极参与社区活动，后续建议多参与一些PR review的工作！@SigureMo 看到合适的 PR 就 assign 一下练练手

**Comment by raindrops2sea** [comment]
+1 同意！

**Comment by XiaoguangHu01** [comment]
+1 同意

**Comment by raindrops2sea** [comment]
感谢[zrr1999](https://github.com/zrr1999)对飞桨社区的贡献！已添加对应权限，请注意查收:-)
祝贺！
