### ISSUE TITLE
PGL模块知识图谱嵌入模型使用说明

### ISSUE THREAD

**Issue by zhaojun007** [PaddlePaddle/Paddle#55390]
### 请提出你的问题 Please ask your question

您好，请问PGL模块中TranE,TransR等知识图谱嵌入预训练模型如何预测及使用呢，看源码里只有训练如何调用，有文档的话麻烦给一下哈，谢谢！

**Comment by DesmonDay** [comment]
没有具体文档。具体怎么用来预测的可以看 https://github.com/PaddlePaddle/PGL/blob/main/apps/Graph4KG/utils.py 中的 evaluate_xxx 函数。

**Comment by zhaojun007** [comment]
> 没有具体文档。具体怎么用来预测的可以看 https://github.com/PaddlePaddle/PGL/blob/main/apps/Graph4KG/utils.py 中的 evaluate_xxx 函数。

好的，谢谢
