### ISSUE TITLE
请问怎样切换GPU版本和CPU版本的paddle？

### ISSUE THREAD

**Issue by SilasTHU** [PaddlePaddle/Paddle#55409]
### 请提出你的问题 Please ask your question

服务器上安装了CPU和GPU两个版本，但似乎是默认使用CPU版本，无法检测到CPU。
报错信息：
print(paddle.device.get_device())
--> cpu

**Comment by westfish** [comment]
是在一个环境下装了两个版本吗，如果是的话，请使用环境管理工具如conda分别开启两个python环境分别安装两个版本
