### ISSUE TITLE
要如何將轉化過存為pdmodel的檔案轉為 __mode__ 

### ISSUE THREAD

**Issue by Ciao-Wen-Chen** [PaddlePaddle/Paddle#55424]
### 请提出你的问题 Please ask your question

要如何將轉化過存為pdmodel的檔案轉為 __mode__ ，已嘗試直接修改檔案名稱但會造成缺少operator檔案

**Comment by westfish** [comment]
没有特别get到你的意思，可以用英语重新表述一下吗
