### ISSUE TITLE
请问ai studio的项目里面是不能下载文件超过40M吗？

### ISSUE THREAD

**Issue by THCNF** [PaddlePaddle/Paddle#55438]
### 问题描述 Please describe your issue

![图片](https://github.com/PaddlePaddle/Paddle/assets/47071679/9301cf0b-272d-4009-b9c5-46ff22bb40f5)
![图片](https://github.com/PaddlePaddle/Paddle/assets/47071679/2cda098d-8c8e-44ef-8f1c-e5f16533a42c)
我想要下载文件出来，但是每次好像下载到40M就会停止，请问是什么原因呢？

**Comment by YixinKristy** [comment]
AI Studio项目下载大小是没有这样的限制的，目前复现不出来，还希望您提供项目ID方便我们查询原因~

**Comment by fedocx** [comment]
我用firefox有40M的限制，每次都是。换chrome后好了
