### ISSUE TITLE
在jetson nano上使用ppvehicle的plus_tiny模型时显存溢出，提示需要分配16g左右的显存

### ISSUE THREAD

**Issue by nibnahzuh** [PaddlePaddle/Paddle#55437]
在jetson nano上使用ppvehicle的plus_tiny模型时显存分配异常。

在jetson nano上使用ppvehicle的plus_tiny模型时显存溢出，提示需要分配16g左右的显存，但在3090上运行实时监控显存消耗最多只有8g不到。jetson nano上换成其他大一些的模型报其他错误，同时这些模型在3090上都可以正常运行。请问这是什么问题呢？

![dfaf](https://github.com/PaddlePaddle/Paddle/assets/35127671/41980019-d19d-415b-898a-8d1c6f210a91)

**Comment by nemonameless** [comment]
您好，请补充下更多信息(环境/运行命令/代码改动)以便我们排查，并按模板提问谢谢 https://github.com/PaddlePaddle/Paddle/issues/new?assignees=&labels=type%2Fbug-report%2Cstatus%2Fnew-issue&projects=&template=1_bug-report.yml
首先确认下是否使用了正确的权重模型，其次是不是多任务？配置是否正确？
可在此重提 issue  https://github.com/PaddlePaddle/PaddleDetection/issues
