### ISSUE TITLE
PGL模块中训练模型通过参数指定日志输出方式均不生效

### ISSUE THREAD

**Issue by zhaojun007** [PaddlePaddle/Paddle#55440]
### 请提出你的问题 Please ask your question

您好，PGL模块中，我在训练TransE模型时，预测及验证的结果均不通过日志输出，日志级别是info，https://github.com/PaddlePaddle/PGL/blob/main/apps/Graph4KG/utils.py。我的训练命令是：python -u train.py --model_name TransE --data_name FB15k-237 --data_path ./data/FB15K  --save_path ./data/transe_fb237_sgpu --batch_size 512 --test_batch_size 16 --reg_coef 1e-9  --neg_sample_size 256 --neg_sample_type 'chunk' --embed_dim 200 --gamma 5.0 --lr 0.1 --optimizer adagrad -adv  --num_workers 4 --num_epoch 50 --test --print_on_screen --filter_eval

**Comment by DesmonDay** [comment]
是不是重定向到了别的日志？你试试把 logger.info 改成 print，直接运行，看看有没有打印出来？
