### ISSUE TITLE
关于一键 rerun 所有 CI 的需求

### ISSUE THREAD

**Issue by RedContritio** [PaddlePaddle/Paddle#55443]
### 请提出你的问题 Please ask your question

现有 CI 常因随机因素而失败，因而开发贡献过程中客观存在这样的需求：便利地 rerun 所有 CI 。

现有情况下，如果一个 CI 挂掉，导致其依赖的 CI 被中止，即使流水线重新执行，根据观察，似乎只重新执行了直接关联的 CI。

如 A 依赖 B，B 依赖 C。当 C 失败时，B、A 会级联失败。但是重新执行 C 并重运行流水线时，仅 B 会被重启。

目前通常的解决方法有以下两种，但合理性都略显不足：

1. 提交空 commit 来强制 rerun，该方法不甚优雅与合理

```bash
git commit -m "force rerun all CI" --no-verify --allow-empty
```

2. rebase 或 merge origin/develop 来达成实质上的改变，该方法相对实用，但仍然需要重新 rebase，造成非必要的提交

鉴于此，我认为现有 CI 机制或许可以做以下改善：
1. rerun 流水线时，完善级联 rerun 的功能；
2. 添加一个空 CI 作为所有 CI 的共同依赖，rerun 时通过 rerun 该 CI 来达成对所有 CI 的 rerun。

**Comment by tianshuo78520a** [comment]
如果需要rerun依赖流水线，在rerun时候有选择，可以一键rerun关联流水线，如果你想rerun全部流水线，可以rerun PR-CI-clone任务，他会帮你重跑大部分任务，可以参考文档：[Paddle CI详解](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/paddle_ci_manual_cn.html)
后续我也会考虑在文档中添加rerun任务说明。

**Comment by AndSonder** [comment]
感觉最近CI随机挂的概率已经高到了几乎每次commit都会有随机挂的情况，不知道内部有没有解决方案呢 @tianshuo78520a  一键 rerun 的功能感觉还是很实用的，不知道能不能添加  (*❦ω❦)

**Comment by tianshuo78520a** [comment]
Hi [AndSonder](https://github.com/AndSonder)

随机挂情况还在想办法解决，这是一件比较困难的事情，目前还没有特别好的方法去解决。
一键rerun所有任务（包括成功的），我上面有写：如果你想rerun全部流水线，可以rerun PR-CI-clone任务，他会帮你重跑大部分任务

希望可以帮助到你

祝好!
tian

**Comment by AndSonder** [comment]
> Hi [AndSonder](https://github.com/AndSonder)
> 
> 随机挂情况还在想办法解决，这是一件比较困难的事情，目前还没有特别好的方法去解决。 一键rerun所有任务（包括成功的），我上面有写：如果你想rerun全部流水线，可以rerun PR-CI-clone任务，他会帮你重跑大部分任务
> 
> 希望可以帮助到你
> 
> 祝好! tian

结合最近挂掉的情况来看，Paddle-Windows 的相关CI是随机挂的重灾区，每次都需要挨个点开去rerun，不知道百度智能云能不能添加类似rerun某个pr挂掉的ci的功能

**Comment by tianshuo78520a** [comment]
我会去和windows负责人沟通。
rerun某个PR失败CI的功能，这个我们需要再考虑下，我们是希望进到日志中，查看日志后，再进行判断，是否要进行rerun，而不是直接看到失败，就rerun所有失败的任务，这个需求我们会进行评估下。

**Comment by AndSonder** [comment]
> rerun某个PR失败CI的功能，这个我们需要再考虑下，我们是希望进到日志中，查看日志后，再进行判断，是否要进行rerun，而不是直接看到失败，就rerun所有失败的任务，这个需求我们会进行评估下。

好的非常感谢
