### ISSUE TITLE
【jetson paddle编译】【python3.10】在nano上编译时，报错。。。较难编译。。请帮看下，谢谢

### ISSUE THREAD

**Issue by bianyiJetsonnano** [PaddlePaddle/Paddle#55444]
### 问题描述 Issue Description

**编译命令：**
nvidia@nvidia-desktop:/usr/local/bin/Paddle/build$
 sudo -H cmake ..  -DCUDA_ARCH_NAME=All -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_ TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DPYTHON_INCLUDE_DIR="/home/nvidia/mambaforge/include/python3.10" -DPYTHON_LIBRARY="/home/nvidia/mambaforge/li b" -DON_INFER=ON -DWITH_PYTHON=ON -DWITH_XBYAK=OFF -DWITH_NV_JETSON=ON -DCMAKE_CUDA_COMPILER="/usr/local/cuda/bin/nvcc" -DPYTHON_EXECUTABLE:FILEPATH= "/home/nvidia/mambaforge/bin/python" -DPY_VERSION=3.10 -DCUDA_ARCH_NAME=Auto

**错误信息：**
 
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Paddle host system: ubuntu, version: 18.04.6
-- Found Paddle host system's CPU: 4 cores
for cuda before 11.7, libcudart.so must be used for the lazy module loading trick to work, instead of libcudart_static.a
-- CUDA compiler: /usr/local/bin/Paddle/tools/nvcc_lazy, version: NVIDIA 10.2.300
-- CXX compiler: /usr/local/bin/c++, version: GNU 8.2.0
-- C compiler: /usr/local/bin/gcc, version: GNU 8.2.0
-- AR tools: /usr/bin/ar
CMake Error at cmake/nccl.cmake:20 (file):
  file failed to open for reading (No such file or directory):

    /usr/local/bin/Paddle/NCCL_INCLUDE_DIR-NOTFOUND/nccl.h
Call Stack (most recent call first):
  CMakeLists.txt:425 (include)-**--------------1. 不涉及多gpu，应该是不影响吧？**

-- Current NCCL header is NCCL_INCLUDE_DIR-NOTFOUND/nccl.h. Current NCCL version is         v..
-- CUDA detected: 10.2.300

-- WARNING: This is just a warning for publishing release.
      _### You are building GPU version without supporting different architectures.
      So the wheel package may fail on other GPU architectures.
      You can add -DCUDA_ARCH_NAME=All in cmake command
      to get a full wheel package to resolve this warning.
      While, this version will still work on local GPU architecture.
-- Automatic GPU detection failed. Building for all known architectures._
   -------------------------------------------------**2.不知道是不是这里的问题？怎么处理呢?**

-- NVCC_FLAGS_EXTRA:  -gencode arch=compute_53,code=sm_53 -gencode arch=compute_62,code=sm_62 -gencode arch=compute_72,code=sm_72
-- Add thrust patches: /usr/local/bin/Paddle/patches/thrust
-- Current cuDNN header is /usr/include/cudnn_version.h Current cuDNN version is v8.2.1.
-- Current TensorRT header is /usr/include/aarch64-linux-gnu/NvInfer.h. Current TensorRT version is v8.2.1.8
-- warp-ctc library: /usr/local/bin/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
CMake Warning (dev) at /home/nvidia/cmake/cmake-3.26.4-linux-aarch64/share/cmake-3.26/Modules/ExternalProject.cmake:3091 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  /home/nvidia/cmake/cmake-3.26.4-linux-aarch64/share/cmake-3.26/Modules/ExternalProject.cmake:4208 (_ep_add_download_command)
  cmake/external/lapack.cmake:65 (ExternalProject_Add)
  cmake/third_party.cmake:269 (include)
  CMakeLists.txt:522 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build OpenBLAS by External Project (include: /usr/local/bin/Paddle/build/third_party/install/openblas/include, library: /usr/local/bin/Paddle/buil d/third_party/install/openblas/lib/libopenblas.a)
-- CBLAS_PROVIDER: EXTERN_OPENBLAS
-- Protobuf protoc executable: /usr/local/bin/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /usr/local/bin/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /usr/local/bin/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /usr/local/bin/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
CMake Deprecation Warning at cmake/FindNumPy.cmake:6 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  cmake/external/python.cmake:73 (find_package)
  cmake/third_party.cmake:302 (include)
  CMakeLists.txt:522 (include)

CUB_INCLUDE_DIR is /usr/local/bin/Paddle/build/third_party/cub/src/extern_cub
-- Download dependence[externalError] from https://paddlepaddledeps.bj.bcebos.com/externalErrorMsg_20210928.tar.gz, MD5: a712a49384e77ca216ad866712f7 cafa
CMake Warning (dev) at /home/nvidia/cmake/cmake-3.26.4-linux-aarch64/share/cmake-3.26/Modules/ExternalProject.cmake:3091 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  /home/nvidia/cmake/cmake-3.26.4-linux-aarch64/share/cmake-3.26/Modules/ExternalProject.cmake:4208 (_ep_add_download_command)
  cmake/third_party.cmake:138 (ExternalProject_Add)
  cmake/third_party.cmake:327 (file_download_and_uncompress)
  CMakeLists.txt:522 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

POCKETFFT_INCLUDE_DIR is /usr/local/bin/Paddle/build/third_party/pocketfft/src
-- Paddle version is 0.0.0
-- On inference mode, will take place some specific optimization.
PYTHON_VERSION_STRING---3.10.10
Requirement already satisfied: pyyaml in /home/nvidia/mambaforge/lib/python3.10/site-packages (6.0)
Requirement already satisfied: jinja2 in /home/nvidia/mambaforge/lib/python3.10/site-packages (3.1.2)
Requirement already satisfied: typing-extensions in /home/nvidia/mambaforge/lib/python3.10/site-packages (4.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/nvidia/mambaforge/lib/python3.10/site-packages (from jinja2) (2.1.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended  to use a virtual environment instead: https://pip.pypa.io/warnings/venv
parse api yamls:
- /usr/local/bin/Paddle/paddle/phi/api/yaml/ops.yaml
- /usr/local/bin/Paddle/paddle/phi/api/yaml/legacy_ops.yaml
- /usr/local/bin/Paddle/paddle/phi/api/yaml/backward.yaml
- /usr/local/bin/Paddle/paddle/phi/api/yaml/legacy_backward.yaml
validate api yaml:
- /usr/local/bin/Paddle/paddle/phi/api/yaml/parsed_apis/ops.parsed.yaml
- /usr/local/bin/Paddle/paddle/phi/api/yaml/parsed_apis/backward_ops.parsed.yaml
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
create or remove auto-geneated operators: /usr/local/bin/Paddle/paddle/fluid/operators/generated_op.cc.tmp
create or remove auto-geneated argument mappings: /usr/local/bin/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp
copy if different /usr/local/bin/Paddle/paddle/fluid/operators/generated_op.cc.tmp /usr/local/bin/Paddle/paddle/fluid/operators/generated_op.cc
copy if different /usr/local/bin/Paddle/paddle/fluid/operators/generated_sparse_op.cc.tmp /usr/local/bin/Paddle/paddle/fluid/operators/generated_spar se_op.cc
copy if different /usr/local/bin/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp /usr/local/bin/Paddle/paddle/phi/ops/compat/generated_sig.cc
copy if different /usr/local/bin/Paddle/paddle/phi/ops/compat/generated_sparse_sig.cc.tmp /usr/local/bin/Paddle/paddle/phi/ops/compat/generated_spars e_sig.cc
generate /usr/local/bin/Paddle/paddle/fluid/operators/ops_extra_info.cc
Merge and generate static library: phi_static_1
-- commit: f0422a28d7
-- branch: release/2.4
Performing Eager Dygraph Auto Code Generation
Final State Eager CodeGen
Generate dygraph file structure at path: /usr/local/bin/Paddle/paddle/fluid/eager/generated
WITH_DLNNE:
-- Configuring incomplete, errors occurred!
这里报错结束。。

**或者 能否提供一个jetson 的 基于python高版本的 如3.10的 paddle 编译包，**
目前只有3.7 的infernce，比如paddlespeech 都是需要paddle3.8以上的，几乎无法配合使用。

### 版本&环境信息 Version & Environment Information

****编译PaddlePaddle版本：**2.4**
**系统信息：**
 nvidia@nvidia-desktop:/usr/local/bin/Paddle/build$ jetson_release -v
Software part of jetson-stats 4.2.1 - (c) 2023, Raffaello Bonghi
Model: NVIDIA Jetson Nano Developer Kit - Jetpack 4.6.1 [L4T 32.7.1]
NV Power Mode[0]: MAXN
Serial Number: [XXX Show with: jetson_release -s XXX]
Hardware:
 - 699-level Part Number: 699-13448-0002-401 G.0
 - P-Number: p3448-0002
 - BoardIDs: p3448
 - Module: NVIDIA Jetson Nano module (16Gb eMMC)
 - SoC: tegra210
 - CUDA Arch BIN: 5.3
 - Codename: Porg
Platform:
 - Machine: aarch64
 - System: Linux
 - Distribution: Ubuntu 18.04 Bionic Beaver
 - Release: 4.9.253-tegra
 - 
 **- Python: 3.10.10**
 - 
jtop:
 - Version: 4.2.1
 - Service: Active
Libraries:
 - CUDA: 10.2.300
 - cuDNN: 8.2.1.32
 - TensorRT: 8.2.1.8
 - VPI: 1.2.3
 - Vulkan: 1.2.70
 - OpenCV: 4.1.1 - with CUDA: NO

**Comment by ZhangYulongg** [comment]
您可以尝试增加和修改一些cmake选项：
-DCMAKE_CXX_FLAGS='-Wno-error -w'
-DWITH_NCCL=OFF (解决nccl的报错)
-DCUDA_ARCH_NAME=Maxwell (只编译nano使用的架构)
若需要使用TensorRT推理，还可以加上TRT编译：
-DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr

**Comment by bianyiJetsonnano** [comment]
有用，谢谢。

> 您可以尝试增加和修改一些cmake选项： -DCMAKE_CXX_FLAGS='-Wno-error -w' -DWITH_NCCL=OFF (解决nccl的报错) -DCUDA_ARCH_NAME=Maxwell (只编译nano使用的架构) 若需要使用TensorRT推理，还可以加上TRT编译： -DWITH_TENSORRT=ON -DTENSORRT_ROOT=/usr

**Comment by bianyiJetsonnano** [comment]
有用，谢谢。
