### ISSUE TITLE
Mac安装paddlepaddle后运行提示 Process finished with exit code 132 (interrupted by signal 4: SIGILL)，仅仅将torch替换为paddlepaddle了

### ISSUE THREAD

**Issue by wuzhenxu** [PaddlePaddle/Paddle#55451]
### bug描述 Describe the Bug

控制台运行python后，import paddle也报错，报错信息如下：
zsh: illegal hardware instruction  python

**Comment by zengshao0622** [comment]
请问可以发一下安装时候的指令吗？同时建议可以参考一下PaddlePaddle安装指南：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/macos-pip.html
