### ISSUE TITLE
third_party/eigen3依赖出现问题

### ISSUE THREAD

**Issue by BeatSeat** [PaddlePaddle/Paddle#55456]
### 问题描述 Issue Description

在编译 PaddlePaddle 最新 develop 分支时(编译 cpu 版本)出现以下错误：

```
-- Check submodules of paddle, and run 'git submodule update --init --recursive'
fatal: Unable to find current revision in submodule path 'third_party/eigen3'
```

查看Github项目发现对应Github上eigen3项目被移除，目前应该在GitLab上，希望能更新对应依赖

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: Windows 10
GCC version: (GCC) 11.2.0
Clang version: N/A
CMake version: version 3.26.4
Libc version: N/A
Python version: 3.11.4

CUDA version: 12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0
cuDNN version: N/A
Nvidia driver version: 536.40
Nvidia driver List:
GPU 0: NVIDIA GeForce RTX 4060 Laptop GPU

****************************************

**Comment by risemeup1** [comment]
你查看.gitmodules文件，我们的eiigen3就是用的gitlab上的啊

**Comment by risemeup1** [comment]
cd Paddle; rm -rf third_party ; git submodue update --init

**Comment by time-heart** [comment]
> 你查看.gitmodules文件，我们的eiigen3就是用的gitlab上的啊

你好，我想问下我make时eigen3这个模块的源码报错
/ppd_data/source/Paddle/third_party/eigen3/unsupported/Eigen/CXX11/../../../Eigen/src/Core/arch/NEON/PacketMath.h:1675:9: error: ‘void* memcpy(void*, const void*, size_t)’ copying an object of non-trivial type ‘Eigen::internal::Packet4c’ {aka ‘struct Eigen::internal::eigen_packet_wrapper<int, 2>’} from an array of ‘const int8_t’ {aka ‘const signed char’} [-Werror=class-memaccess]
系统是ubuntu22.04 nvidia jetson arm64架构,gcc-11 g++-11 cmake3.27.5
