### ISSUE TITLE
麒麟系统源码编译paddle，make命令后报错

### ISSUE THREAD

**Issue by Phoenix2Legend** [PaddlePaddle/Paddle#55464]
### bug描述 Describe the Bug

在麒麟v10系统上编译paddle，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。参考文档链接为：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html。在完成make TARGET=ARMV8 -j$(nproc)操作以后报错，具体报错信息见《其他补充信息 Additional Supplementary Information》

### 其他补充信息 Additional Supplementary Information

根据参考文档指示，一直到cmake命令结束都没有报错，但是在build目录中执行make TARGET=ARMV8 -j$(nproc)操作以后出现如下报错：
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/ops/compat/signatures.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/funcs/jit/kernels.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/declarations.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  0%] Built target copy_signatures_command
[  0%] Built target copy_kernels_command
[  0%] Built target copy_declarations_command
[  0%] Built target copy_paddle_inference_pass_command
[  1%] Built target extern_zlib
[  1%] Built target extern_gflags
[  1%] copy_if_different /workspace/Paddle/build/paddle/fluid/pybind/pybind.h
[  1%] Built target extern_pocketfft
[  1%] Built target copy_pybind_command
[  1%] Built target extern_pybind
[  2%] Built target extern_utf8proc
[  2%] Built target extern_eigen3
[  2%] Performing configure step for 'extern_warprnnt'
[  2%] Built target extern_dlpack
[  2%] Creating directories for 'extern_cryptopp'
[  2%] Creating directories for 'extern_gloo'
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log

make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4801：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  2%] Creating directories for 'extern_lapack'
[  3%] Performing download step (git clone) for 'extern_cryptopp'
-- Avoiding repeated git clone, stamp file is up to date: '/workspace/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-gitclone-lastrun.txt'
[  3%] No download step for 'extern_gloo'
[  3%] Performing patch step for 'extern_cryptopp'
[  3%] Performing download step (verify and extract) for 'extern_lapack'
[  3%] No update step for 'extern_cryptopp'
-- verifying file...
     file='/workspace/Paddle/third_party/lapack/Linux/lapack_lnx_v3.10.0.20210628.tar.gz'
正克隆到 '/workspace/Paddle/build/third_party/cryptopp/src/extern_cryptopp/cmake'...
[  3%] No patch step for 'extern_gloo'
-- verifying file... done
[  3%] No update step for 'extern_gloo'
-- extracting...
     src='/workspace/Paddle/third_party/lapack/Linux/lapack_lnx_v3.10.0.20210628.tar.gz'
     dst='/workspace/Paddle/build/third_party/install/lapack/lib'
-- extracting... [tar xfz]
[  3%] No configure step for 'extern_gloo'
[  3%] Performing build step for 'extern_gloo'
-- Build type not set -- defaulting to Release
-- extracting... [analysis]
-- extracting... [rename]
-- extracting... [clean up]
-- extracting... done
-- Configuring done
[  4%] No update step for 'extern_lapack'
[  4%] No patch step for 'extern_lapack'
[  4%] No configure step for 'extern_lapack'
[  4%] No build step for 'extern_lapack'
[  4%] No install step for 'extern_lapack'
-- Generating done
[  4%] Completed 'extern_lapack'
-- Build files have been written to: /workspace/Paddle/build/third_party/gloo/src/extern_gloo/build
gmake[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
[  4%] Built target extern_lapack
[100%] Built target gloo
[  4%] Performing install step for 'extern_gloo'
[  4%] Completed 'extern_gloo'
[  4%] Built target extern_gloo
remote: Enumerating objects: 835, done.
remote: Counting objects: 100% (279/279), done.
remote: Compressing objects: 100% (37/37), done.
remote: Total 835 (delta 271), reused 244 (delta 242), pack-reused 556
接收对象中: 100% (835/835), 339.65 KiB | 834.00 KiB/s, 完成.
处理 delta 中: 100% (505/505), 完成.
切换到一个新分支 'CRYPTOPP_8_2_0'
[  4%] Performing configure step for 'extern_cryptopp'
-- extern_cryptopp configure command succeeded.  See also /workspace/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-configure-*.log
[  4%] Performing build step for 'extern_cryptopp'
[ 98%] Built target cryptopp-object
[ 99%] Built target cryptopp-shared
[100%] Built target cryptopp-static
[  4%] Performing install step for 'extern_cryptopp'
-- extern_cryptopp install command succeeded.  See also /workspace/Paddle/build/third_party/cryptopp/src/extern_cryptopp-stamp/extern_cryptopp-install-*.log
[  4%] Completed 'extern_cryptopp'
[  4%] Built target extern_cryptopp
make: *** [Makefile:133：all] 错误 2

请问如何解决，谢谢！

**Comment by jiahy0825** [comment]
您好，可能是编译第三方库时报错，建议删除 /workspace/Paddle/build/third_party/warprnnt/ 目录后，再重新 make 试试

**Comment by Phoenix2Legend** [comment]
删除warprnnt重新make以后又有如下报错：

CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/usr/local/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS=-Wno-error -w -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log


make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:110：third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] 错误 1
make[1]: *** [CMakeFiles/Makefile2:4801：CMakeFiles/extern_warprnnt.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:864：sgemv.o] 错误 1
make[4]: *** 正在等待未完成的任务....
ger.c: 在函数‘sger_’中:
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:836：sger.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
[  4%] Built target eager_python_c_codegen
[  4%] Built target eager_codegen
make: *** [Makefile:133：all] 错误 2

**Comment by jiahy0825** [comment]
我看您之前提过类似的 issue ：https://github.com/PaddlePaddle/Paddle/issues/55319
按照先前 issue 的方案，删除 third_party 目录后（Paddle/build/third_party 和 Paddle/third_party 都删除），换用稳定代理重新编译第三方库，可以解决问题吗

**Comment by Phoenix2Legend** [comment]
> 我看您之前提过类似的 issue ：#55319
> 按照先前 issue 的方案，删除 third_party 目录后（Paddle/build/third_party 和 Paddle/third_party 都删除），换用稳定代理重新编译第三方库，可以解决问题吗

麒麟系统用什么代理比较稳定啊

**Comment by Phoenix2Legend** [comment]
> > 我看您之前提过类似的 issue ：#55319
> > 按照先前 issue 的方案，删除 third_party 目录后（Paddle/build/third_party 和 Paddle/third_party 都删除），换用稳定代理重新编译第三方库，可以解决问题吗
> 
> 麒麟系统用什么代理比较稳定啊

您说的办法我试过了，还是会报错

**Comment by kangguangli** [comment]
可以先确认下 third_party目录下各个第三方库的完整性。关于上面的问题，可以看看下面两个目录
1. `third_party/warprnnt` 跟https://github.com/PaddlePaddle/warp-transducer.git对比下
2. `third_party/openblas` 跟https://github.com/xianyi/OpenBLAS/目录对比，具体跟哪个分支比得看你的环境，相关代码可以看看`cmake/external/openblas.cmake`

不过我觉得现在看可能不是网络问题，可以：
1. 把你使用的CMake选项贴出来看看
2. 把`/workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log`贴出来

**Comment by Phoenix2Legend** [comment]
关于cmake命令全部：
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF -DCMAKE_CXX_FLAGS="-Wno-error -w"
以下是最新报错：
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/ops/compat/signatures.h
[  1%] Built target extern_gflags
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/declarations.h
[  1%] copy_if_different /workspace/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  1%] Built target copy_signatures_command
[  1%] Built target copy_paddle_inference_pass_command
[  1%] Built target copy_declarations_command
[  1%] copy_if_different /workspace/Paddle/build/paddle/fluid/pybind/pybind.h
[  1%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/funcs/jit/kernels.h
[  1%] Built target copy_pybind_command
[  1%] Built target extern_warpctc
[  1%] Built target copy_kernels_command
[  2%] Built target extern_cryptopp
[  2%] Built target extern_eigen3
[  2%] Performing build step for 'extern_openblas'
[  3%] Built target extern_lapack
[  3%] Built target extern_gloo
make[3]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
make[3]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
[  3%] Built target extern_warprnnt
[  3%] Built target extern_dlpack
[  3%] Built target extern_zlib
[  3%] Built target extern_threadpool
[  3%] Built target extern_pocketfft
[  3%] Built target extern_pybind
[  4%] Built target extern_utf8proc
[  4%] Built target ps_py_proto_init
[  4%] Built target fleet_proto_init
/bin/sh: ./getarch: 权限不够
make[3]: *** [Makefile.prebuild:47：config.h] 错误 126
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:864：sgemv.o] 错误 1
make[4]: *** 正在等待未完成的任务....
ger.c: 在函数‘sger_’中:
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[4]: *** [Makefile:836：sger.o] 错误 1
make[3]: *** [Makefile:150：libs] 错误 1
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
[  4%] Built target eager_python_c_codegen
[  4%] Built target op_map_codegen
[  4%] Built target eager_codegen
make: *** [Makefile:133：all] 错误 2

**Comment by qili93** [comment]
您好，根据报错信息还是由于第三方库的编译错误导致的，你可以尝试先运行如下命令

```
# 单独运行，保证 warprnnt 第三方库编译成功
make TARGET=ARMV8 extern_warprnnt -j8

# 单独运行，保证 openblas 第三方库编译成功
make TARGET=ARMV8 extern_openblas -j8

# 以上两个命令运行成功之后，再运行全部的make命令
make TARGET=ARMV8 -j8
```

这样可以排除因为以上两个第三方库导致的编译错误。

**Comment by Phoenix2Legend** [comment]
您好，看样子就是openblas库下载异常？
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_warprnnt -j8
Scanning dependencies of target extern_warprnnt
Creating directories for 'extern_warprnnt'
No download step for 'extern_warprnnt'
No update step for 'extern_warprnnt'
No patch step for 'extern_warprnnt'
Performing configure step for 'extern_warprnnt'
-- extern_warprnnt configure command succeeded.  See also /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log
Performing build step for 'extern_warprnnt'
Scanning dependencies of target warprnnt
[ 50%] Building CXX object CMakeFiles/warprnnt.dir/src/rnnt_entrypoint.cpp.o
[100%] Linking CXX shared library libwarprnnt.so
[100%] Built target warprnnt
Performing install step for 'extern_warprnnt'
[100%] Built target warprnnt
Install the project...
-- Install configuration: "Release"
-- Installing: /workspace/Paddle/build/third_party/install/warprnnt/lib/libwarprnnt.so
-- Installing: /workspace/Paddle/build/third_party/install/warprnnt/include/rnnt.h
Completed 'extern_warprnnt'
Built target extern_warprnnt
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_openblas -j8
Scanning dependencies of target extern_openblas
Creating directories for 'extern_openblas'
Performing download step (git clone) for 'extern_openblas'
正克隆到 'extern_openblas'...
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：Empty reply from server
正克隆到 'extern_openblas'...
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：Empty reply from server
正克隆到 'extern_openblas'...
fatal: 无法访问 'https://github.com/xianyi/OpenBLAS.git/'：Failed to connect to github.com port 443: 连接超时
-- Had to git clone more than once:
          3 times.
CMake Error at /workspace/Paddle/build/third_party/openblas/tmp/extern_openblas-gitclone.cmake:31 (message):
  Failed to clone repository: 'https://github.com/xianyi/OpenBLAS.git'


make[3]: *** [CMakeFiles/extern_openblas.dir/build.make:94：third_party/openblas/src/extern_openblas-stamp/extern_openblas-download] 错误 1
make[2]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4548：CMakeFiles/extern_openblas.dir/rule] 错误 2
make: *** [Makefile:297：extern_openblas] 错误 2

**Comment by Phoenix2Legend** [comment]
将build/third_party下的openblas删除然后返回build目录重新执行make TARGET=ARMV8 extern_openblas -j8还是会报错：
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_openblas -j8
Performing build step for 'extern_openblas'
make[4]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
make[4]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
/bin/sh: ./getarch: 权限不够
make[4]: *** [Makefile.prebuild:47：config.h] 错误 126
gemv.c: 在函数‘sgemv_’中:
gemv.c:223:29: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if ( 1L * m * n < 2304L * GEMM_MULTITHREAD_THRESHOLD )
                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
                             GEMM_THREAD_TR
gemv.c:223:29: 附注：每个未声明的标识符在其出现的函数内只报告一次
ger.c: 在函数‘sger_’中:
ger.c:178:27: 错误：‘GEMM_MULTITHREAD_THRESHOLD’ undeclared (first use in this function); did you mean ‘GEMM_THREAD_TR’?
   if(1L * m * n > 2048L * GEMM_MULTITHREAD_THRESHOLD)
                           ^~~~~~~~~~~~~~~~~~~~~~~~~~
                           GEMM_THREAD_TR
ger.c:178:27: 附注：每个未声明的标识符在其出现的函数内只报告一次
make[5]: *** [Makefile:864：sgemv.o] 错误 1
make[5]: *** 正在等待未完成的任务....
make[5]: *** [Makefile:836：sger.o] 错误 1
make[4]: *** [Makefile:150：libs] 错误 1
make[3]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[2]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4548：CMakeFiles/extern_openblas.dir/rule] 错误 2
make: *** [Makefile:297：extern_openblas] 错误 2

**Comment by Phoenix2Legend** [comment]
> 您好，根据报错信息还是由于第三方库的编译错误导致的，你可以尝试先运行如下命令
> 
> ```
> # 单独运行，保证 warprnnt 第三方库编译成功
> make TARGET=ARMV8 extern_warprnnt -j8
> 
> # 单独运行，保证 openblas 第三方库编译成功
> make TARGET=ARMV8 extern_openblas -j8
> 
> # 以上两个命令运行成功之后，再运行全部的make命令
> make TARGET=ARMV8 -j8
> ```
> 
> 这样可以排除因为以上两个第三方库导致的编译错误。

第一个命令应该是没什么问题，但是第二个命令执行以后总是卡在“正克隆到‘extern_openblas’…”，最后自动切换分支然后出现语法报错，请问是什么问题呢？

**Comment by qili93** [comment]
根据错误提示，怀疑可能是您环境的权限不足导致的这个错误 “/bin/sh: ./getarch: 权限不够”

这个 getarch 命令输出会用于openblas里面判断平台架构类型，从而选择编译的代码平台，怀疑可能是由于您环境中权限不足导致 getarch 没有执行正确输出导致无法选择到对应 armv8 平台下的正确代码进行编译，从而导致的代码定义找不到等问题。

请先尝试解决 “getarch: 权限不够”的问题后，再运行“make TARGET=ARMV8 extern_openblas -j8”的命令。

如果还存在错误，也请尝试到 openblas 的 github 社区提问，谢谢！

**Comment by Phoenix2Legend** [comment]
> 根据错误提示，怀疑可能是您环境的权限不足导致的这个错误 “/bin/sh: ./getarch: 权限不够”
> 
> 这个 getarch 命令输出会用于openblas里面判断平台架构类型，从而选择编译的代码平台，怀疑可能是由于您环境中权限不足导致 getarch 没有执行正确输出导致无法选择到对应 armv8 平台下的正确代码进行编译，从而导致的代码定义找不到等问题。
> 
> 请先尝试解决 “getarch: 权限不够”的问题后，再运行“make TARGET=ARMV8 extern_openblas -j8”的命令。
> 
> 如果还存在错误，也请尝试到 openblas 的 github 社区提问，谢谢！

您好，我的所有操作都是先sudo到root下完成的，权限应该是足够的吧？网上也没有找到这个权限报错相关的解决办法，无从下手求帮助。

**Comment by Phoenix2Legend** [comment]
> > 您好，根据报错信息还是由于第三方库的编译错误导致的，你可以尝试先运行如下命令
> > ```
> > # 单独运行，保证 warprnnt 第三方库编译成功
> > make TARGET=ARMV8 extern_warprnnt -j8
> > 
> > # 单独运行，保证 openblas 第三方库编译成功
> > make TARGET=ARMV8 extern_openblas -j8
> > 
> > # 以上两个命令运行成功之后，再运行全部的make命令
> > make TARGET=ARMV8 -j8
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这样可以排除因为以上两个第三方库导致的编译错误。
> 
> 第一个命令应该是没什么问题，但是第二个命令执行以后总是卡在“正克隆到‘extern_openblas’…”，最后自动切换分支然后出现语法报错，请问是什么问题呢？

是网络问题么？我可以访问到GitHub啊。为什么克隆到extern_openblas目录的这一步就是没反应呢？

**Comment by Phoenix2Legend** [comment]
我可以在GitHub上下载好openblas的代码然后放到指定位置并且改名以后正常编译吗？

**Comment by Phoenix2Legend** [comment]
我直接将https://github.com/xianyi/OpenBLAS.git的代码下载下来以后，把OpenBLAS-develop文件夹放到Paddle/build/third_party/openblas/src下面，删除该文件夹下原有的的extern_openblas并把OpenBLAS-develop重命名为extern_openblas，然后返回build目录下执行make TARGET=ARMV8 extern_openblas -j$(nproc)后报错：
λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_openblas -j$(nproc)
Performing build step for 'extern_openblas'
make[4]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。
make[4]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。
/bin/sh: ./c_check: 权限不够
/bin/sh:行1: ./c_check: 权限不够
/bin/sh: ./c_check: 权限不够
make[4]: *** [Makefile.prebuild:63：config.h] 错误 126
Makefile.system:1504: Makefile.: 没有那个文件或目录
make[4]: *** 没有规则可制作目标“Makefile.”。 停止。
make[3]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2
make[2]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4548：CMakeFiles/extern_openblas.dir/rule] 错误 2
make: *** [Makefile:297：extern_openblas] 错误 2
有什么办法吗？

**Comment by wjddd** [comment]
> 我直接将[https://github.com/xianyi/OpenBLAS.git的代码下载下来以后，把OpenBLAS-develop文件夹放到Paddle/build/third_party/openblas/src下面，删除该文件夹下原有的的extern_openblas并把OpenBLAS-develop重命名为extern_openblas，然后返回build目录下执行make](https://github.com/xianyi/OpenBLAS.git%E7%9A%84%E4%BB%A3%E7%A0%81%E4%B8%8B%E8%BD%BD%E4%B8%8B%E6%9D%A5%E4%BB%A5%E5%90%8E%EF%BC%8C%E6%8A%8AOpenBLAS-develop%E6%96%87%E4%BB%B6%E5%A4%B9%E6%94%BE%E5%88%B0Paddle/build/third_party/openblas/src%E4%B8%8B%E9%9D%A2%EF%BC%8C%E5%88%A0%E9%99%A4%E8%AF%A5%E6%96%87%E4%BB%B6%E5%A4%B9%E4%B8%8B%E5%8E%9F%E6%9C%89%E7%9A%84%E7%9A%84extern_openblas%E5%B9%B6%E6%8A%8AOpenBLAS-develop%E9%87%8D%E5%91%BD%E5%90%8D%E4%B8%BAextern_openblas%EF%BC%8C%E7%84%B6%E5%90%8E%E8%BF%94%E5%9B%9Ebuild%E7%9B%AE%E5%BD%95%E4%B8%8B%E6%89%A7%E8%A1%8Cmake) TARGET=ARMV8 extern_openblas -j$(nproc)后报错： λ wangan-GW-001M1A-FTF /workspace/Paddle/build {develop} make TARGET=ARMV8 extern_openblas -j$(nproc) Performing build step for 'extern_openblas' make[4]: 警告: 子 make 中强制 -jN: 关闭 jobserver 模式。 make[4]: 警告: jobserver 不可用: 正使用 -j1。添加 “+” 到父 make 的规则。 /bin/sh: ./c_check: 权限不够 /bin/sh:行1: ./c_check: 权限不够 /bin/sh: ./c_check: 权限不够 make[4]: *** [Makefile.prebuild:63：config.h] 错误 126 Makefile.system:1504: Makefile.: 没有那个文件或目录 make[4]: *** 没有规则可制作目标“Makefile.”。 停止。 make[3]: *** [CMakeFiles/extern_openblas.dir/build.make:116：third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] 错误 2 make[2]: *** [CMakeFiles/Makefile2:4541：CMakeFiles/extern_openblas.dir/all] 错误 2 make[1]: *** [CMakeFiles/Makefile2:4548：CMakeFiles/extern_openblas.dir/rule] 错误 2 make: *** [Makefile:297：extern_openblas] 错误 2 有什么办法吗？

我也碰到了同样的问题，请问您找到解决办法了吗？
