### ISSUE TITLE
Should we change the epsilon in batch_norm_layer to a variable instead of a fixed value 1e-5.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#5548]
In other DL platform(such as tensorflow, mxnet.), the default value of epsilon is 0.001

**Comment by jacquesqiao** [comment]
what do you mean by variable?

**Comment by jacquesqiao** [comment]
now the `epsilon` in batch_norm_layer is also an attribute that can be configured.

**Comment by peterzhang2029** [comment]
I mean the previous v2 version, the implementation is:
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L3030

**Comment by jacquesqiao** [comment]
Got it! ~
