### ISSUE TITLE
无法创建卷积算子或者使用GPU运算？

### ISSUE THREAD

**Issue by LatinaDaisuki** [PaddlePaddle/Paddle#55492]
### 请提出你的问题 Please ask your question

首先我Cuda Driver版本是12.2，但根据paddle安装教程装了cuda11.7、cudn8.4.1和paddle2.4.2
然后在深度学习教程[卷积神经网络基础](https://www.paddlepaddle.org.cn/tutorials/projectdetail/4282406)里有一段用卷积神经网络检测黑白边界的代码，前半段代码没问题，创建了一个50*50的二维数组代表图片并把前20列数值全部设为1表示黑色区域，后30列数值为0代表白色区域。
```python
w = np.array([1, 0, -1], dtype='float32')
w = w.reshape([1, 1, 1, 3])
img = np.ones([50,50], dtype='float32')
img[:, 30:] = 0.
x = img.reshape([1,1,50,50])
x = paddle.to_tensor(x)
```
![image](https://github.com/PaddlePaddle/Paddle/assets/85465394/903b7189-a4b7-4be9-9632-4d8ce10a1e82)
但是使用卷积算子之后就报错并且导致后半段没有输出结果，而报错结果也只是一段版本信息让人摸不着头脑
```python
# 创建卷积算子，设置输入和输出通道数，卷积核大小，通过参数属性weight_attr用w初始化参数权重
conv = Conv2D(in_channels=1, out_channels=1, kernel_size=[1, 3],
       weight_attr=paddle.ParamAttr(
          initializer=Assign(value=w)))
y = conv(x)
out = y.numpy()
f = plt.subplot(121)
f.set_title('input image', fontsize=15)
plt.imshow(img, cmap='gray')
f = plt.subplot(122)
f.set_title('output featuremap', fontsize=15)plt.imshow(out.squeeze(), cmap='gray')
plt.show()
print(conv.weight)
print(conv.bias)
```
![image](https://github.com/PaddlePaddle/Paddle/assets/85465394/1f051af7-efd3-465d-9e99-9aab60e33085)

**Comment by wangzhen38** [comment]
<img width="1440" alt="截屏2023-07-18 10 17 16" src="https://github.com/PaddlePaddle/Paddle/assets/41941775/b12adbdb-041f-4bf1-9376-44daf93eb705">
我这边执行你这段代码是没问题的，你试下别的算子是否也存在这种问题

**Comment by LatinaDaisuki** [comment]
黑白边界检测出了一次问题，后面的[AI识虫](https://www.paddlepaddle.org.cn/tutorials/projectdetail/3643401)启动train的时候也有同样的问题

**Comment by wangzhen38** [comment]
可能是你gpu环境没配置好，建议你cudnn版本换成8.2试试
