### ISSUE TITLE
seqToseq demo train.conf 问题导致出core

### ISSUE THREAD

**Issue by seraphimhj** [PaddlePaddle/Paddle#555]
通过一键安装的paddle成功，使用seqToseq demo，preprocess.py 执行成功，在train.sh的时候，core了，运行日志如下，定位应该是train.conf 配置问题，同样附上：

**train.conf**

import sys
sys.path.append("..")

from seqToseq_net import *

is_generating = False

data_dir  = "./data/pre-query2title"
train_conf = seq_to_seq_data(data_dir = data_dir,
                             is_generating = is_generating)

settings(
    learning_method = AdamOptimizer(),
    batch_size = 50,
    learning_rate = 5e-4)

gru_encoder_decoder(train_conf, is_generating)   //**这行报错**

**train.log**：

I1121 20:00:58.179965 22000 Util.cpp:155] commandline: /home/disk1/paddle_internal_release_tools/idl/paddle/output/bin/../opt/paddle/bin/paddle_trainer --config=translation/train.conf --save_dir=translation/model --use_gpu=false --num_passes=16 --show_parameter_stats_period=100 --trainer_count=4 --log_period=10 --dot_period=5
I1121 20:00:58.185039 22000 Util.cpp:130] Calling runInitFunctions
I1121 20:00:58.185331 22000 Util.cpp:143] Call runInitFunctions done.
Traceback (most recent call last):
  File "/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer/config_parser.py", line 3406, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer/config_parser.py", line 3382, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "translation/train.conf", line 36, in <module>
    gru_encoder_decoder(train_conf, is_generating)
  File "/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/demo/seqToseq/seqToseq_net.py", line 159, in gru_encoder_decoder
    input=group_inputs)
  File "/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer_config_helpers/layers.py", line 2930, in recurrent_group
    assert (is_generating != has_LayerOutput)
AssertionError
F1121 20:02:35.661034 22000 PythonUtil.cpp:134] Check failed: (ret) != nullptr Current PYTHONPATH: ['/home/disk1/paddle_internal_release_tools/idl/paddle/output/opt/paddle/bin', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/demo/seqToseq', '/home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python27.zip', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/plat-linux2', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-tk', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-old', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-dynload', '/home/disk1/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages', '..']
Python Error: <type 'exceptions.AssertionError'> :
Python Callstack:
            /home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer/config_parser.py : 3406
            /home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer/config_parser.py : 3382
            translation/train.conf : 36
            /home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/demo/seqToseq/seqToseq_net.py : 159
            /home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer_config_helpers/default_decorators.py : 53
            /home/disk1/paddle_internal_release_tools/idl/paddle/Paddle/python/paddle/trainer_config_helpers/layers.py : 2930
Call Object failed.
*** Check failure stack trace: ***
    @          0x13b5c38  google::LogMessage::Fail()
    @          0x13b5b90  google::LogMessage::SendToLog()
    @          0x13b5625  google::LogMessage::Flush()
    @          0x13b83e6  google::LogMessageFatal::~LogMessageFatal()
    @           0x81223d  paddle::callPythonFuncRetPyObj()
    @           0x812441  paddle::callPythonFunc()
    @           0x7103c6  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x710a3d  paddle::TrainerConfigHelper::createFromFlags()
    @           0x591e34  main    
    @     0x7f79c7938bd5  __libc_start_main
    @           0x59dbf5  (unknown)
/home/disk1/paddle_internal_release_tools/idl/paddle/output/bin/paddle: line 81: 22000 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by luotao1** [comment]
请问您是用源码编译，还是其他什么方式安装的呢。用的是最新develop分支上的代码么

**Comment by seraphimhj** [comment]
公司内部 使用paddle_internal_release_tools 安装，Paddle下载的是dev分支

**Comment by luotao1** [comment]
@backyes 是不是安装和demo不一致的问题？

**Comment by seraphimhj** [comment]
稳定的版本是哪个？我先去下载试试

**Comment by backyes** [comment]
@seraphimhj 一键编译里面有demo源码，使用那个源码肯定会和一键编译出来的一致的。

**Comment by luotao1** [comment]
@seraphimhj bug已经修复了 #583
