### ISSUE TITLE
多卡环境下只能输出0卡paddle显存，不能输出其他卡的paddle显存

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/Paddle#55534]
### bug描述 Describe the Bug

在aistudio的V100四卡notebook环境下，在网络运行过程中，使用pynvml可以观察到4个卡的显存随着训练过程变化，但是使用paddle.device.cuda.memory_reserved(paddle.CUDAPlace(0))可以输出正确paddle显存值，而paddle.device.cuda.memory_reserved(paddle.CUDAPlace(1))输出结果为0

另外，希望出一个类似于torch.cuda.memory_summary的api，更详细地显示显存信息

**Comment by huilin16** [comment]
项目地址https://aistudio.baidu.com/aistudio/projectdetail/6545652

**Comment by JunnYu** [comment]
你好，关于第一个问题，我这里进行了测试，你需要查看log文件夹这里的对应卡号的log文件才可以看到对应卡的显存信息。
- 卡0
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/813a4dac-8348-4d7e-b747-d7a5578503de)
- 卡1
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/d3eac08e-85d7-4acd-903b-87330658fd62)

关于第二个问题，新增torch.cuda.memory_summary的api，这里已经记录你的需求，等待后续评估。当然也欢迎你贡献新的api到paddlepaddle。

**Comment by huilin16** [comment]
好的，多谢
