### ISSUE TITLE
CodeLab中work目录下数据消失

### ISSUE THREAD

**Issue by erichgy** [PaddlePaddle/Paddle#55564]
### 请提出你的问题 Please ask your question

**### 数据丢失！我在codelab中work目录下的数据突然消失了一大半。**
这上面显示的体积还是35G。
上次应该是算力卡归零之后，自动结束的。
很重要的数据，恳求各位工作人员一定帮忙啊。谢谢，谢谢，谢谢。
![微信图片_20230720090010](https://github.com/PaddlePaddle/Paddle/assets/95597907/1a991840-acb7-4f97-9d1b-39f400759e5a)

**Comment by risemeup1** [comment]
提供一下用户的uid和项目ID

**Comment by erichgy** [comment]
好的。uid：2159720，项目ID：5747963。谢谢。

**Comment by risemeup1** [comment]
看日志用户20号9:04有一次回传，可能是文件还没下载完用户就关闭了。17号有一个版本应该是他反馈的丢失版本。我们可以给你提供文件的下载链接，你留个微信，我让对应的RD加你

**Comment by erichgy** [comment]
非常感谢，vx：f2373b。再次感谢。
