### ISSUE TITLE
咨询fused_softmax_mask_grad_kernel的相关问题

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#55577]
### 背景

这个算子：`paddle/phi/kernels/fusion/gpu/fused_softmax_mask_grad_kernel.cu`它的函数原型是：

```
template <typename T, typename Context>
void FusedSoftmaxMaskGradKernel(const Context& dev_ctx,
                                const DenseTensor& out,
                                const DenseTensor& out_grad,
                                DenseTensor* x_grad)
```

它的前向，也就是`FusedSoftmaxMaskKernel`，原型是这样的，见`paddle/phi/kernels/fusion/gpu/fused_softmax_mask_kernel.cu`：

```
template <typename T, typename Context>
void FusedSoftmaxMaskKernel(const Context& dev_ctx,
                            const DenseTensor& x,
                            const DenseTensor& mask,
                            DenseTensor* out)
```

### 问题

1、前向计算的时候用到了`mask`，为什么反向计算的时候，不需要`mask`了呢？（这可能是个数学问题）

2、反向计算的函数定义，和“普通”的`SoftmaxGradKernel`很接近，少了一个`axis`参数。为啥不直接调用这个函数呢，而是重写了一个。我猜固定`axis`为最后一维就好了？见：`paddle/phi/kernels/impl/softmax_grad_kernel_impl.h`

```
void SoftmaxGradKernel(const Context& dev_ctx,
                       const DenseTensor& out,
                       const DenseTensor& out_grad,
                       int axis,
                       DenseTensor* x_grad)
```

所以是不是这两个kernel本质仍然是不同的？（这可能是个算法问题）

**Comment by LiYuRio** [comment]
1. 前向计算的mask是为了让softmax算出来的结果变得接近0，softmax的反向与前向计算出来的y相关，这个y是已经包含mask后计算出来的结果，从公式推导上看不需要再加一个mask。
2. 理论上，我理解是可以合并的，SoftmaxMask开发时，paddle的整个算子体系还在fluid下，或许当时不支持这种直接调用共享反向的方式
