### ISSUE TITLE
请问paddle是否能提供语音识别的模型，能把输入音频输出每句话及其在音频中的时间戳

### ISSUE THREAD

**Issue by superFilicos** [PaddlePaddle/Paddle#55578]
### 请提出你的问题 Please ask your question

请问paddle是否能提供语音识别的模型，能把输入音频输出每句话及其在音频中的时间戳

**Comment by risemeup1** [comment]
可以去paddlespeech仓库提issue问问呢，我对这个不了解

**Comment by zxcd** [comment]
可以尝试使用paddlespeech仓库的whisper模型。
使用方法参考：https://github.com/PaddlePaddle/PaddleSpeech/tree/develop/demos/whisper
