### ISSUE TITLE
从相同的checkpoint导出的infer不同

### ISSUE THREAD

**Issue by 0x0C001** [PaddlePaddle/Paddle#55579]
从相同的checkpoint导出的infer不同

**Comment by risemeup1** [comment]
不同指的是啥不同啊

**Comment by risemeup1** [comment]
方不方便提供下数据

**Comment by risemeup1** [comment]
> > 不同指的是啥不同啊
> 
> infer的结果不同

从你的代码中，你save了一个并没有执行的模型，这段代码也没有看到那段代码去执行推理，能否提供详细复现步骤
