### ISSUE TITLE
官网文档 Bug 确认 🔍

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/Paddle#55585]
## 一、 为什么做这件事？
研发同学总会说 ”这不是个 bug ，它只是一个 feature ”。但是对于官网的文档来说，如果发现了一个 bug，那大概率就是个 bug。
基于这个前提下，官网在年初上线了` 「文档反馈」 `的功能按钮，能够比较便捷的反馈官网文档 bug。用户只需要选取有问题的文档片段，并填写相应信息，便能直接向后台反馈文档存在的问题。

<div align="center">
<img width="400" alt="image" src="https://github.com/PaddlePaddle/docs/assets/70642955/144146ea-436a-4385-97ac-989c3e7e6108" >
</div>

然而，由于一些内部原因，这些用户反馈的 bug 一直迟迟未得到确认，更无从谈起修复 😢。因此，我们希望借助各位社区开发者的力量，来帮助我们确认用户反馈的 bug。

## 二、 用户反馈的 Bug 在哪？
我们提供了[用户反馈清单](https://shimo.im/sheets/NJkbnW0800T9BykR/K256U/ )，包含了从功能上线到现在的用户反馈的bug。其中，清单有如下字段：

文档链接 | 文档版本 | 错误的文本片段 | 错误类型 | 错误描述  | createTime
-- | -- | -- | -- | --  | --

- **【文档链接】** 用户反馈有问题的文档，其相应的网址链接；
- **【文档版本】** 用户反馈有问题的文档，其所处的版本（在界面左上角）；
<img width="300" alt="image" src="https://github.com/PaddlePaddle/docs/assets/70642955/ef067630-851a-4553-85fa-4cdb03eece9e" >

- **【错误的文本片段】** 用户反馈有问题的文档下，具体某处存在错误的文本片段；
- **【错误类型】** 有4种错误类型：描述不清楚、内容错误、代码/图片/链接缺失、其他。按字面意思理解即可；
- **【错误描述】** 用户关于文档错误的补充说明；
- **【createTime】** 用户反馈文档问题的时间点。

## 三、 你需要做什么？
在上述的[用户反馈清单](https://shimo.im/sheets/NJkbnW0800T9BykR/K256U/ )中，你可以随意选取任意数量的用户反馈，并填如下字段：

develop分支是否存在该问题 | reviewer
-- | --

- **【develop分支是否存在该问题】** 由于官网文档每天都在更新优化，你需要确认在最新的版本（develop / master）中是否还存在用户所反馈的问题，这涉及到以下2点：
    
```
     1. 用户反馈的问题是否 在 develop/master 分支已被修复？
     2. 用户反馈的问题是否 真实存在，且确实是个bug？

    ❗️如果有不确定的情况，可以不填。
```
     

- **【reviewer】** 确认后填写你的 Github ID，方便我们后续统计。

## 四、 谁适合做这个任务？

- 刚接触 paddle，想以此为契机参与飞桨社区活动的开发者们。
- 啥也不会，但仍想为飞桨社区做贡献的新人小白们。
- 对bug充满热情（误

## 五、 Leaderboard
截止8月9日榜单

GitHub ID | review问题数量
-- | --
@enkilee | 125
@Liyulingyue  | 118
@ooooo-create | 80
@yuchen202 | 45
@gouzil | 17
@whisky-12 | 14
@Kaedeharai | 8
@GoH | 4

后续，我们计划逐步开放文档的一系列开源活动，敬请期待～如果对文档感兴趣，可以扫码加群。

<div align="center">
<img width="300" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/70642955/b1025b56-592e-4820-bb0f-4227559f9698">
</div>

**Comment by yuchen202** [comment]
收到了，谢谢

**Comment by A1exan10er** [comment]
您好，加群二维码过期了，是否可更新一下呢？

**Comment by sunzhongkai588** [comment]
> 您好，加群二维码过期了，是否可更新一下呢？

已更新～

**Comment by sunzhongkai588** [comment]
感谢 @enkilee @Liyulingyue @ooooo-create @yuchen202 @gouzil @whisky-12 @Kaedeharai @goh 的开源贡献～ 🎉本活动已正式结项

这些确认过的bug，我再次review后会以任务形式发布～再次感谢以上同学的付出
