### ISSUE TITLE
Custom Device的算子融合实现/int8推理

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#55581]
### 需求描述 Feature Description

任务目标 Custom Device的算子融合; <br /> 
需求场景 OpenCL推理;  <br /> 
功能描述 OpenCL实现conv2d_fusion / int8推理

我看见 这个 https://github.com/PaddlePaddle/Paddle/commit/6216beb30dc0d2f6bf1600d6f216c42ecfe24b5b
能够自定义pass

**Q1** 现在Custom Device有没有办法实现算子融合，例如conv2d_fusion
conv2d和batch_norm和relu融合

**Q2** 另外如果是带有量化伪层的模型，int8的pass该如何编写

是否有例子？

**Comment by engineer1109** [comment]
@ronny1996

**Comment by ronny1996** [comment]
你好，CustomDevice 支持算子融合，可以参考 
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/tests/unittests/test_custom_pass_npu.py
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/custom_op/my_add_n_op.cc

CustomDevice应该还不支持量化，目前没有专门适配以及实验过

**Comment by engineer1109** [comment]
@ronny1996 怎么在C++上注册自己的融合算子Pass呢？

**Comment by engineer1109** [comment]
@ronny1996 别急着关问题啊

**Comment by ronny1996** [comment]
点错了，不好意思，@engineer1109 c++上还没有引出接口，目前只有python方式

**Comment by engineer1109** [comment]
@ronny1996 我如果想用fluid或phi接口来完成融合pass，我应该怎么做。有没有代码教程 或 说明？

**Comment by ronny1996** [comment]
@engineer1109 是指在框架内部实现吗？只能参考已有的pass进行实现 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/ir

**Comment by ccsuzzh** [comment]
> 点错了，不好意思，@engineer1109 c++上还没有引出接口，目前只有python方式

C++上什么时候能支持自定义Pass呢？目前有计划吗？

**Comment by ronny1996** [comment]
@ccsuzzh 目前没有计划支持，paddle ir在做升级，可能需要等升级完毕后

**Comment by ccsuzzh** [comment]
> @ccsuzzh 目前没有计划支持，paddle ir在做升级，可能需要等升级完毕后

好的，感谢回复。
