### ISSUE TITLE
Fatal Python error: Floating point exception; Erroneous arithmetic operation is detected by the operating system 

### ISSUE THREAD

**Issue by iababio** [PaddlePaddle/Paddle#55596]
### bug描述 Describe the Bug

Crash Report:  Fatal Python error: Floating point exception.
During Conv1d with the below parameters, Paddle or the system Crashes.

## Error message:
Fatal Python error: Floating point exception: 

Warning: FatalError: `Erroneous arithmetic operation` is detected by the operating system.
--

<br class="Apple-interchange-newline">

```python
!pip install paddleocr --upgrade
!pip install paddlepaddle

import paddle

x = paddle.to_tensor([[[0.50000000, 0.50000000]]], dtype="float32", stop_gradient=True,)
w = paddle.to_tensor([[[0.50000000, 0.50000000]]], dtype="float32", stop_gradient=True)
stride= 1
padding= "VALID"
dilation= 1
groups = 1
data_format = 'NLC' # changing data_format to NCL runs but returns an empty array

x = paddle.transpose(x, (2, 1, 0)) # shape of (0, 2, 1) runs if data_format == "NLC"
#x = paddle.transpose(x, (0, 2, 1)) # shape of (0, 2, 1) runs if data_format == "NLC" but ValueError: (InvalidArgument) 

res = paddle.nn.functional.conv1d(
        x=x,
        weight=w,
        stride=stride,
        padding=padding,
        dilation=dilation,
        data_format=data_format,
    )
```
### link to NoteBook
[Link to sample code in colab notebook](https://colab.research.google.com/drive/13Dv8CVxsNNqEZS7O80EbRW6iHEpfyAbw?usp=sharing)

### 其他补充信息 Additional Supplementary Information

# Colab Error log
<img width="879" alt="Screenshot 2023-07-20 at 2 22 18 PM" src="https://github.com/PaddlePaddle/Paddle/assets/9405739/c8d24a99-e325-473a-91c7-3d8b9b82b099">

# local Error log
<img width="614" alt="Screenshot 2023-07-20 at 3 55 44 PM" src="https://github.com/PaddlePaddle/Paddle/assets/9405739/6c483297-8503-4b00-8062-fc84fd174636">

**Comment by LokeZhou** [comment]
data_format='NCL' ,and del x = paddle.transpose(x, (2, 1, 0)） 。

**Comment by iababio** [comment]
Hi @LokeZhou, I know NCL works, but that's not what I am reporting; I am reporting the crash.

Thanks for the feedback ~

**Comment by LokeZhou** [comment]
Thank you for the report. We will resolve it as soon as possible
