### ISSUE TITLE
fix op in debug mode

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#5559]
Currently, our CI system only tests our code in Cmake `Release` mode, it will remove some asserts which may be failed in `debug` mode.  E.g. eigen tensor shape asserts will be removed in Release mode, so we need to test the project in debug mode locally.
```c++
cmake .. -DCMAKE_BUILD_TYPE=Debug 
```
- [x] seq_pool
- [x] matmul_op
- [x] l1_norm_op https://github.com/PaddlePaddle/Paddle/pull/5560
- [x] cos_sim_op
- [x] gru_op
- [x] elementwise_mul_op
- [x] squared_l2_norm_op https://github.com/PaddlePaddle/Paddle/pull/5560
- [x] reduce_op https://github.com/PaddlePaddle/Paddle/pull/5565

```text
The following tests FAILED:
	149 - test_seq_pool (OTHER_FAULT)
	151 - test_matmul_op (OTHER_FAULT)
	153 - test_l1_norm_op (OTHER_FAULT)
	158 - test_cos_sim_op (OTHER_FAULT)
	173 - test_gru_op (OTHER_FAULT)
	192 - test_elementwise_mul_op (OTHER_FAULT)
	220 - test_recognize_digits_conv (Failed)
	255 - test_reduce_op (OTHER_FAULT)
	262 - test_squared_l2_norm_op (OTHER_FAULT)
```

**Comment by qingqing01** [comment]
@dzhwinter  Thanks, I'll help to fix these operators.
