### ISSUE TITLE
libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by stack-dhruv** [PaddlePaddle/Paddle#55597]
### bug描述 Describe the Bug

I am trying to import the paddleocr in my google colab notebook. It leads me to the following error.

```shell
!git clone https://github.com/PaddlePaddle/PaddleOCR.git
!pip install paddleocr
!pip install paddlepaddle
```

```ipynb
import paddleocr
```

# The error

```shell
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-5-015a1fe02f03>](https://localhost:8080/#) in <cell line: 1>()
----> 1 import paddleocr
[/usr/local/lib/python3.10/dist-packages/paddle/fluid/core.py](https://localhost:8080/#) in <module>
    267 
    268 try:
--> 269     from . import libpaddle
    270 
    271     if avx_supported() and not libpaddle.is_compiled_with_avx():

ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```

### 其他补充信息 Additional Supplementary Information

This same code ran perfectly before few days, now I am trying to run this and it is showing me this error message.

**Comment by iababio** [comment]
Hi @stack-dhruv, run the below commands before you import

```bash
!wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
!sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```


### Just do step 2 before you import paddleocr
1. install packages
!git clone https://github.com/PaddlePaddle/PaddleOCR.git
!pip install paddleocr
!pip install paddlepaddle

2. run. below commands
!wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
!sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
3. import paddleocr


Let me know if it helps~.

**Comment by yuvrajsingh2** [comment]
@melch-inno You are a legend

**Comment by stack-dhruv** [comment]
> Hi @stack-dhruv, run the below commands before you import
> 
> ```shell
> !wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> !sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> ```
> 
> ### Just do step 2 before you import paddleocr
> 1. install packages
>    !git clone https://github.com/PaddlePaddle/PaddleOCR.git
>    !pip install paddleocr
>    !pip install paddlepaddle
> 2. run. below commands
>    !wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
>    !sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> 3. import paddleocr
> 
> Let me know if it helps~.

It worked for me, thanks

**Comment by pedroogaab** [comment]
**@melch-inno** it worked! thankss

**Comment by yonglee7015** [comment]
Why this happened in these days. About one week ago, I don't need to run the command you provide. @melch-inno

**Comment by hieunguyencs** [comment]
> Hi @stack-dhruv, run the below commands before you import
> 
> ```shell
> !wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> !sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> ```
> 
> ### Just do step 2 before you import paddleocr
> 1. install packages
>    !git clone https://github.com/PaddlePaddle/PaddleOCR.git
>    !pip install paddleocr
>    !pip install paddlepaddle
> 2. run. below commands
>    !wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
>    !sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
> 3. import paddleocr
> 
> Let me know if it helps~.

It worked for me, thank you so much. I have the same question as @yonglee7015. Can you explain it to us? @melch-inno

**Comment by iababio** [comment]
Hi @yonglee7015, @hieunguyencs 

It's a platform/system-related issue.
 
Paddle relies on libssl.so.1.1, which may be missing or outdated on the system/platform you are using. You can use the wget to download the required libssl1.1 version from the Ubuntu archive and then install it using sudo dpkg -i command. This ensures the correct OpenSSL library version is available.

Thanks~

**Comment by lagefreitas** [comment]
hi! Would there be another way of installing it through a package manager like `apt-get` for example to avoid using `dpkg`?

**Comment by BMukhtar** [comment]
thanks it worked!

**Comment by vincentluan** [comment]
Hi @melch-inno

I also stumbled this issue today. As libssl.so.1.1 is obsoleted and shouldn't be used, is there any plan to update Paddle to use a newer libssl in the near future?

**Comment by iababio** [comment]
> hi! Would there be another way of installing it through a package manager like `apt-get` for example to avoid using `dpkg`?


Hello @lagefreitas, my apologies for the delayed response. You might have already resolved your issue, but if not, here's an alternative approach to avoid using `dpkg` and utilize `apt-get`:

1. Use the following command to download the necessary `.deb` package:
   ```
   wget http://nz2.archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
   ```

2. After downloading, you can install the package using `apt-get` as shown below:
   ```
   sudo apt-get install ./libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
   ```

Feel free to execute these commands if you haven't already found a solution to your problem.

Thanks~

**Comment by iababio** [comment]
> Hi @melch-inno
> 
> I also stumbled this issue today. As libssl.so.1.1 is obsoleted and shouldn't be used, is there any plan to update Paddle to use a newer libssl in the near future?


Hi @vincentluan, Sorry, but I don't have intel on that. Thanks~

**Comment by Shreejan-git** [comment]
Another query: 
Is the above solution (commands) for paddlepaddle cpu version only? Because I ran both of the commands and it solved for the CPU but for the paddlepaddle-gpu cuda12 compatible ( mentioned here: https://www.paddlepaddle.org.cn/documentation/docs/en/install/pip/linux-pip_en.html#cpu ) did not work with the same commands. I am using two different conda environments one for cpu version and one for gpu version. Switching to CPU did not throw any error but GPU still has the same.

**Comment by wudashuo** [comment]
If anyone still not solve this problem, the download link above is 404 not found now, use http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb instead.

**Comment by WenpiaoSU** [comment]
> If anyone still not solve this problem, the download link above is 404 not found now, use http://archive.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.23_amd64.deb instead.

I have completed the first step. May I ask if there are any methods for the second step "sudo dpkg - i libssl1.1_1.1.1f-1 ubuntu2.19_amd64. deb" that do not require sudo permission?
