### ISSUE TITLE
请问美国的服务器可以安装paddle嘛，本地显存不够，感谢解答~ 

### ISSUE THREAD

**Issue by superFilicos** [PaddlePaddle/Paddle#55609]
### 请提出你的问题 Please ask your question

请问美国的服务器可以安装paddle嘛，本地显存不够，感谢解答~

**Comment by LokeZhou** [comment]
可以的

**Comment by superFilicos** [comment]
为啥我在他那个服务器上安装就提示什么找不到channel啥的呢






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月21日(星期五) 下午4:22
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 请问美国的服务器可以安装paddle嘛，本地显存不够，感谢解答~  (Issue #55609)





 
可以的
