### ISSUE TITLE
在美国的linux服务器上进行试验 python -v结果 ：3.7.3 64位python  pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple pip install paddlepaddle 等结果 报错为 ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none) ERROR: No matching

### ISSUE THREAD

**Issue by superFilicos** [PaddlePaddle/Paddle#55614]
### 问题描述 Issue Description

在美国的linux服务器上进行试验
python -v结果 ：3.7.3
64位python 
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install paddlepaddle 等结果
报错为
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching distribution found for paddlepaddle
感谢工作人员~

### 版本&环境信息 Version & Environment Information

在美国的linux服务器上进行试验
python -v结果 ：3.7.3
64位python 
pip install paddlepaddle -i https://mirror.baidu.com/pypi/simple
pip install paddlepaddle 等结果
报错为
ERROR: Could not find a version that satisfies the requirement paddlepaddle (from versions: none)
ERROR: No matching

**Comment by LokeZhou** [comment]
安装命令可以参考https://www.paddlepaddle.org.cn/ ，需要指出paddle版本

**Comment by LokeZhou** [comment]
已超72小时未回复，暂停跟进，后续有问题可以再提issue
