### ISSUE TITLE
corrupted double-linked list

### ISSUE THREAD

**Issue by Aixining** [PaddlePaddle/Paddle#55622]
(Unavailable) Currently, model parallelism is only supported between CPU and CUDA.\n  [Hint: Expected in.place().GetType() != dst_place.GetType(), but received in.place().GetType() == dst_place.GetType().] (at /paddle/paddle/fluid/framework/data_device_transform.cc:27)\n  [operator < split > error]

运行过程中偶尔出现此问题，请赐教

**Comment by Aixining** [comment]
报错 unavailable，然后报错corrupted double-linked list，程序也不中断，很奇怪。

**Comment by GGBond8488** [comment]
可能是op的输入数据在不同设备上吧，op选择kernel的时候只能选择某一个输入的设备kernel，那另一个输入就需要transform到对应的设备上，这里看起来是错误的判断为需要transfrom，但是实际上kernel设备合输入数据在的是同一个设备，具体的kernel选择逻辑可以看 [kernel_select](https://github.com/PaddlePaddle/community/blob/5cacc14861aceeef4a9c0d29703607223a0a54d1/pfcc/paddle-code-reading/kernel_selection/20221130_kernel_selection.md)。
同时可以提供一下复现的代码吗，我们可以知道具体是哪个case触发了这种问题
