### ISSUE TITLE
phi::enforce::EnforceNotMe

### ISSUE THREAD

**Issue by soyons** [PaddlePaddle/Paddle#55635]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.
训练中途报错
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
Mon Jul 24 04:06:46 2023[1,0]<stdout>:  what():  (Fatal) 900 seconds elapsed after the first worker stopped, so we think there may be something wrong and will stop the master worker. You can use 'export FLAGS_stop_check_timeout=3600' to change the timeout value in seconds. The default one is 900
Mon Jul 24 04:06:46 2023[1,0]<stdout>:  [Hint: Expected elapsed_seconds < _timeout, but received elapsed_seconds:900 >= _timeout:900.] (at /paddle/paddle/fluid/distributed/store/tcp_store.cc:235)
Mon Jul 24 04:06:46 2023[1,0]<stdout>:
Mon Jul 24 04:06:46 2023[1,0]<stdout>:
Mon Jul 24 04:06:46 2023[1,0]<stdout>:
Mon Jul 24 04:06:46 2023[1,0]<stdout>:--------------------------------------
Mon Jul 24 04:06:46 2023[1,0]<stdout>:C++ Traceback (most recent call last):
Mon Jul 24 04:06:46 2023[1,0]<stdout>:--------------------------------------
Mon Jul 24 04:06:46 2023[1,0]<stdout>:No stack trace in paddle, may be caused by external reasons.
Mon Jul 24 04:06:46 2023[1,0]<stdout>:
Mon Jul 24 04:06:46 2023[1,0]<stdout>:----------------------
Mon Jul 24 04:06:46 2023[1,0]<stdout>:Error Message Summary:
Mon Jul 24 04:06:46 2023[1,0]<stdout>:----------------------
Mon Jul 24 04:06:46 2023[1,0]<stdout>:FatalError: `Process abort signal` is detected by the operating system.
Mon Jul 24 04:06:46 2023[1,0]<stdout>:  [TimeInfo: *** Aborted at 1690142805 (unix time) try "date -d @1690142805" if you are using GNU date ***]
Mon Jul 24 04:06:46 2023[1,0]<stdout>:  [SignalInfo: *** SIGABRT (@0xd5a) received by PID 3418 (TID 0x7f74eca30700) from PID 3418 ***]

**Comment by warrentdrew** [comment]
您好，请问是单机多卡训练时遇到的问题吗？workerlog中是否有其他报错信息

**Comment by soyons** [comment]
单机多卡的问题，下面是worker里面的报错
2023-07-24 04:06:11  kf_top1_lane_accuracy:nan,kf_top3_lane_accuracy:nan
2023-07-24 04:06:11 	decision_num: 118, veh_decision_loss: 0.07923924922943115, veh_long_decision_num: 38
terminate called after throwing an instance of 'phi::enforce::EnforceNotMet'
  what():  (Fatal) 900 seconds elapsed after the first worker stopped, so we think there may be something wrong and will stop the master worker. You can use 'export FLAGS_stop_check_timeout=3600' to change the timeout value in seconds. The default one is 900
  [Hint: Expected elapsed_seconds < _timeout, but received elapsed_seconds:900 >= _timeout:900.] (at /paddle/paddle/fluid/distributed/store/tcp_store.cc:235)



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1690142805 (unix time) try "date -d @1690142805" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0xd5a) received by PID 3418 (TID 0x7f74eca30700) from PID 3418 ***]

**Comment by warrentdrew** [comment]
看上去accuracy出现了nan的情况，可以export FLAGS_check_nan_inf=1后运行定位具体的出现nan的位置
参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/flags/check_nan_inf_cn.html#check-nan-inf
也可以看下单卡是否能正常运行
