### ISSUE TITLE
基于 rocm4.5/hip 编译的 paddle bfloat16 数据类型问题

### ISSUE THREAD

**Issue by Rane2021** [PaddlePaddle/Paddle#55632]
### bug描述 Describe the Bug

基于 rocm4.5/hip 编译的 paddle bfloat16 数据类型在转换 -1 和 -512.0f 时会报错，问题可以通过 bfloat16_test 单元测试复现

**Comment by warrentdrew** [comment]
您好问题已收到，能否提供下具体的报错信息，我们相关的同学看下
