### ISSUE TITLE
黑客松第五期预热活动：黑客松小助手

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#55654]
### 任务简介
为了更便捷快速的展示黑客松赛题的进度：包括认领、提交RFC/PR和合入RFC/PR三个环节，方便黑客松选手们查看进度、也降低飞桨运营人员的人工维护成本。在黑客松第5期（预计9月初）上线前，开发黑客松小助手功能。
### 功能需求
* 设计合理的黑客松表单，可参考 [第四期](https://github.com/PaddlePaddle/Paddle/issues/51281#issuecomment-1457581337)。注：第5期将不再有队名，表单里需显示GithudID；需考虑一题有多个PR的情况
* 设计合理的规则引导选手，包括不限于：issue评论认领情况、PR内@小助手、PR标题规范化
* 完成自动化更新表单的功能：包括认领情况、提交PR（包括提案）情况和PR merge情况
* 完成自动化统计整体进展的看板，类似：
![image](https://github.com/PaddlePaddle/Paddle/assets/6836917/211aa034-9686-4a4b-b890-415e09a4493a)
### 产出要求
1. 流程：产品设计文档+技术实现路径（RFC） --> 代码
2. 设计文档、代码提交至： https://github.com/PFCCLab/PaddleAutoProject
3. 需要维护至黑客松5期结束（可能有临时需求）
4. 验收人员：飞桨花花、 @Ligoml  @luotao1  @社区有兴趣的开发者
### 奖励
1. 黑客松5期上线前完成产品设计文档和开发：500京东卡
2. 维护至黑客松5期结束后：500京东卡

**Comment by ZS-YANG** [comment]
前排🙋‍

**Comment by Fancy-hjyp** [comment]
提交了一个初级版本，分为五种状态，整体状态的变更顺序为：`报名状态` -> `提交RFC` -> `完成设计文档` -> `提交PR` -> `完成任务`。

目前可以自动根据评论进行报名、根据PR进行状态变更。

https://github.com/PFCCLab/PaddleAutoProject/pull/37

**Comment by Ligoml** [comment]
HackathonBot已上线，欢迎参与第五期飞桨黑客松~
