### ISSUE TITLE
国内docker安装paddle

### ISSUE THREAD

**Issue by Tracy6465** [PaddlePaddle/Paddle#5566]
通过命令：docker pull docker.paddlepaddle.org/paddle:0.10.0-gpu
总是返回
Error response from daemon: Get https://docker.paddlepaddle.org/v2/: net/http: TLS handshake timeout
你们 有遇到这个问题吗

**Comment by wsjlvlx** [comment]
docker run -it paddlepaddle/paddle:0.10.0 /bin/bash试试这个
