### ISSUE TITLE
windows 10， CUDA 11.7， cuDNN 8.4.1 官方安装指令报错

### ISSUE THREAD

**Issue by ZeLiu369** [PaddlePaddle/Paddle#55671]
### 问题描述 Issue Description

用的官网上的指令：
https://www.paddlepaddle.org.cn/en/install/quick?docurl=/documentation/docs/en/install/pip/windows-pip_en.html
上面对于 windows 10， CUDA 11.7， cuDNN 8.4.1 版pip 指令
python -m pip install paddlepaddle-gpu==2.5.0.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

会报错：
Defaulting to user installation because normal site-packages is not writeable
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html

ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.5.0.post117 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==2.5.0.post117

请问怎么解决？

### 版本&环境信息 Version & Environment Information

Python: 3.8
GPU: Nvidia G1660

**Comment by warrentdrew** [comment]
直接从这里下载.whl试下呢
https://paddle-wheel.bj.bcebos.com/2.5.0/windows/windows-gpu-cuda11.7-cudnn8.4.1-mkl-avx-vs2019/paddlepaddle_gpu-2.5.0.post117-cp38-cp38-win_amd64.whl
