### ISSUE TITLE
djl使用paddlepaddle提示2.0.2-cpu-win-x86_64\0.23.0-djl_paddle.dll: 找不到指定的程序。

### ISSUE THREAD

**Issue by 12341234-yangboran** [PaddlePaddle/Paddle#55689]
### 请提出你的问题 Please ask your question

djl使用paddlepaddle提示C:\Users\Administrator\.djl.ai\paddle\2.0.2-cpu-win-x86_64\0.23.0-djl_paddle.dll: 找不到指定的程序。
但是本地有目标文件

![image](https://github.com/PaddlePaddle/Paddle/assets/74187378/af4442e0-9f4d-4378-a7ec-f63dcb292503)

**Comment by GhostScreaming** [comment]
您好，先检查一下0.23.0-djl_paddle.dll是否正确链接，或者动态库文件是否损坏？

**Comment by mitoly** [comment]
可以看一下这个DJL的官网http://docs.djl.ai/engines/paddlepaddle/paddlepaddle-native/index.html
需要先安装Visual Studio 2017/2019 with C++ development toolkit is required to compile.
然后配一下gradle的环境变量

**Comment by showaker** [comment]
您好 问一下这个dll动态库在哪里下的 我需要个适合arm架构的动态库不知道在哪找

**Comment by mitoly** [comment]
> 您好 问一下这个dll动态库在哪里下的 我需要个适合arm架构的动态库不知道在哪找

> 您好 问一下这个dll动态库在哪里下的 我需要个适合arm架构的动态库不知道在哪找

http://docs.djl.ai/engines/paddlepaddle/paddlepaddle-engine/index.html
中通过maven获取依赖
<dependency>
    <groupId>ai.djl.paddlepaddle</groupId>
    <artifactId>paddlepaddle-engine</artifactId>
    <version>0.23.0</version>
    <scope>runtime</scope>
</dependency>

可以找个maven仓库把对应的jar包下下来，解压缩后里面有，但是我不确定这是否是你想要的
