### ISSUE TITLE
【New IR】《艾尔登 API 体系升级》赛题热身讨论 🐶🐶🐶 🐱🐱🐱

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle#55696]
### 一、Motavition 🚀

已经预征集了赛题的队友们：勇敢的🐶汪汪队🐶，🐱喵喵队🐱队。

赛题描述：https://github.com/PaddlePaddle/Paddle/issues/55737

为了更快乐、自由、高效地冲击「最高的5W💰」奖金，这里发起一个讨论，征集下大家之前协作时遇到的「问题」、更好的协作「方式」，比如：

+ 是否需要定期组织《赛题技术分享》
+ 是否需要定期组织《攻略圆桌会议》
+ .....等等

👏🏻欢迎队友们在此 Issue 下面抛出问题和想法！

> 圆桌会议，源于[《十二圆桌骑士》](https://baike.sogou.com/v2119629.htm)以及[《记录的地平线》](https://zh.wikipedia.org/zh-hans/%E8%A8%98%E9%8C%84%E7%9A%84%E5%9C%B0%E5%B9%B3%E7%B7%9A)，表示战争攻略或副本攻略。

**Comment by zrr1999** [comment]
加入🐱喵喵队🐱

**Comment by Liyulingyue** [comment]
加入🐶汪汪队🐶

**Comment by GreatV** [comment]
需要 赛题技术分享

**Comment by Aurelius84** [comment]
> 需要 赛题技术分享

@GreatV 好的，已经在在筹备安排了

**Comment by Aurelius84** [comment]
> 

@GreatV 技术设计文档先上线了，后续会组织串讲：https://github.com/PaddlePaddle/community/tree/master/pfcc/paddle-code-reading/IR_Dialect
