### ISSUE TITLE
麒麟系统编译paddle报错

### ISSUE THREAD

**Issue by Phoenix2Legend** [PaddlePaddle/Paddle#55708]
### bug描述 Describe the Bug

在麒麟v10系统上编译paddle，系统内核为Linux-4.4.131-20200710.kylin.desktop-generic-aarch64-with-Kylin-V10-juniper;CPU为Phytium,FT-2000/4(64位，4核)。参考文档链接为：https://www.paddlepaddle.org.cn/inference/v2.4/guides/hardware_support/cpu_phytium_cn.html。在完成make TARGET=ARMV8 -j$(nproc)操作以后报错：
/bin/sh: ./getarch: 权限不够
从而导致下面一些不必要的语法错误出现，请问如何解决，谢谢。

**Comment by YanhuiDua** [comment]
https://github.com/PaddlePaddle/Paddle/issues/55319，https://github.com/PaddlePaddle/Paddle/issues/54941 可以参考下
