### ISSUE TITLE
arm架构服务器上的debian容器内编译报错

### ISSUE THREAD

**Issue by ga1008** [PaddlePaddle/Paddle#55712]
### 问题描述 Issue Description

**截取的部分报错：**
-- Installing: /code/deploy_raw/Paddle/build/third_party/install/brpc/bin/rpc_replay
-- Installing: /code/deploy_raw/Paddle/build/third_party/install/brpc/bin/rpc_view
-- Installing: /code/deploy_raw/Paddle/build/third_party/install/brpc/bin/trackme_server
[  6%] Completed 'extern_brpc'
[  6%] Built target extern_brpc
Scanning dependencies of target extern_gloo
[  6%] Creating directories for 'extern_gloo'
[  6%] No download step for 'extern_gloo'
[  6%] Performing patch step for 'extern_gloo'
HEAD is now at 8b6b61d fix deprecated-copy warning
patching file device.cc
patching file types.h
[  6%] No update step for 'extern_gloo'
[  6%] No configure step for 'extern_gloo'
[  6%] Performing build step for 'extern_gloo'
-- The CXX compiler identification is GNU 12.2.0
-- The C compiler identification is GNU 12.2.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Build type not set -- defaulting to Release
-- Configuring done
-- Generating done
-- Build files have been written to: /code/deploy_raw/Paddle/build/third_party/gloo/src/extern_gloo/build
Scanning dependencies of target gloo
[  2%] Building CXX object gloo/CMakeFiles/gloo.dir/algorithm.cc.o
[  5%] Building CXX object gloo/CMakeFiles/gloo.dir/allgather.cc.o
[  8%] Building CXX object gloo/CMakeFiles/gloo.dir/allgatherv.cc.o
[ 11%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce.cc.o
[ 14%] Building CXX object gloo/CMakeFiles/gloo.dir/allreduce_local.cc.o
[ 17%] Building CXX object gloo/CMakeFiles/gloo.dir/barrier.cc.o
[ 20%] Building CXX object gloo/CMakeFiles/gloo.dir/broadcast.cc.o
[ 22%] Building CXX object gloo/CMakeFiles/gloo.dir/context.cc.o
[ 25%] Building CXX object gloo/CMakeFiles/gloo.dir/gather.cc.o
[ 28%] Building CXX object gloo/CMakeFiles/gloo.dir/reduce.cc.o
[ 31%] Building CXX object gloo/CMakeFiles/gloo.dir/scatter.cc.o
[ 34%] Building CXX object gloo/CMakeFiles/gloo.dir/types.cc.o
[ 37%] Building CXX object gloo/CMakeFiles/gloo.dir/common/logging.cc.o
[ 40%] Building CXX object gloo/CMakeFiles/gloo.dir/common/print_logging.cc.o
[ 42%] Building CXX object gloo/CMakeFiles/gloo.dir/common/linux.cc.o
In file included from /code/deploy_raw/Paddle/third_party/gloo/gloo/common/linux.cc:15:
/usr/include/linux/ethtool.h: In function ‘int gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)’:
/usr/include/linux/ethtool.h:2147:17: error: flexible array member ‘ethtool_link_settings::link_mode_masks’ not at end of ‘struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>’
 2147 |         __u32   link_mode_masks[];
      |                 ^~~~~~~~~~~~~~~
/code/deploy_raw/Paddle/third_party/gloo/gloo/common/linux.cc:192:11: note: next member ‘__u32 gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed struct>::link_mode_data [381]’ declared here
  192 |     __u32 link_mode_data[link_mode_data_nwords];
      |           ^~~~~~~~~~~~~~
/code/deploy_raw/Paddle/third_party/gloo/gloo/common/linux.cc:190:10: note: in the definition of ‘struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>’
  190 |   struct {
      |          ^
gmake[5]: *** [gloo/CMakeFiles/gloo.dir/build.make:248: gloo/CMakeFiles/gloo.dir/common/linux.cc.o] Error 1
gmake[4]: *** [CMakeFiles/Makefile2:198: gloo/CMakeFiles/gloo.dir/all] Error 2
gmake[3]: *** [Makefile:133: all] Error 2
make[2]: *** [CMakeFiles/extern_gloo.dir/build.make:116: third_party/gloo/src/extern_gloo-stamp/extern_gloo-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:7073: CMakeFiles/extern_gloo.dir/all] Error 2
make: *** [Makefile:144: all] Error 2

### 版本&环境信息 Version & Environment Information

**服务器主机cpu信息：**
架构：                           aarch64
CPU 运行模式：                   64-bit
字节序：                         Little Endian
CPU:                             8
在线 CPU 列表：                  0-7
每个核的线程数：                 1
每个座的核数：                   8
座：                             1
NUMA 节点：                      1
厂商 ID：                        HiSilicon
型号：                           0
型号名称：                       Kunpeng-920
步进：                           0x1
CPU 最大 MHz：                   2600.0000
CPU 最小 MHz：                   2600.0000
BogoMIPS：                       200.00
L1d 缓存：                       512 KiB
L1i 缓存：                       512 KiB
L2 缓存：                        4 MiB
L3 缓存：                        32 MiB
NUMA 节点0 CPU：                 0-7
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Vulnerable
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

**在主机上部署了docker，使用的镜像是debian12**
$ cat /etc/issue
Debian GNU/Linux 12 \n \l

$ cat /proc/version
Linux version 4.19.90-52.22.v2207.ky10.aarch64 (KYLINSOFT@localhost.localdomain) (gcc version 7.3.0 (GCC)) #1 SMP Tue Mar 14 11:52:45 CST 2023

**编译命令：**
ulimit -n 8192
cmake .. -DPY_VERSION=3.9 -DPYTHON_INCLUDE_DIR="${PYTHON_INCLUDE_DIRS}" -DPYTHON_LIBRARY="${PYTHON_LIBRARY}" -DWITH_ARM=ON -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=OFF -DWITH_TESTING=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release
make TARGET=ARMV8 -j1

**Comment by YanhuiDua** [comment]
你好，看上去是编译第三方依赖gloo的问题，请参考https://qengineering.eu/install-paddlepaddle-on-raspberry-pi-4.html安装dependencies再重新编译下

**Comment by ga1008** [comment]
> 

感谢！直接使用这个包安装上去了 https://github.com/Qengineering/Paddle-Raspberry-Pi/raw/main/paddlepaddle-2.4.2-cp39-cp39-linux_aarch64.whl

**Comment by peiwenYe** [comment]
您好 请问您使用的是哪个编译docker呢？
