### ISSUE TITLE
[Fluid] Migrate Fluid Distributed Kernels to PHI

### ISSUE THREAD

**Issue by GhostScreaming** [PaddlePaddle/Paddle#55716]
### 问题描述 Please describe your issue

大家好，当前Fluid下分布式算子由于未完全迁移到新的PHI算子体系，无法具备PHI下函数式算子注册时"记录自身输入输出属性“的能力，在分布式场景也就无法使用框架新的通信模块和调度系统，给分布式训练调试、优化等工作带来较大的负担。我们一共收集了17个需要迁移的算子，欢迎大家提交PR一起对这些算子做迁移改造。

更多详细介绍见 [Call-for-Contributions: Fluid算子函数式迁移专项](https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/functionalization_for_fluid_kernel.md)， 本issue用于跟踪记录该项目下各个算子的迁移改造进度。

注：

- 同一个算子的 cpu/gpu/xpu kernel 以及 InferShape 尽量由同一个同学进行迁移改造，在issue下方认领。
- 可参考前两期算子迁移工作：
   - https://github.com/PaddlePaddle/Paddle/issues/52395
   - https://github.com/PaddlePaddle/Paddle/issues/51292 
- 该任务时间：PR 截止提交时间是9月15日，截止合入时间是9月25日。
- PR 通过 CI 后，在Review Request @hitywt @GhostScreaming 进行审核。

### 待迁移算子列表（整体进度 15/16）
> 按 merge 的时间顺序，排名不分先后： @AndSonder (4) @GreatV (2) @BeingGod (3) @huangjiyi (2) @gouzil (2) @yangguohao (1) @zeroRains (1)

|  序号   | 算子名称  |  认领人  |  PR(cpu/gpu kernel )  |  PR(xpu kernel)  | PR(InferShape)|
|  ----  | ----  | ----  | ----  | ----  | ----  |
| 1  | c_embedding✅(2023/8/16) | @BeingGod  | #56129 | #56129 |  无需|
| 2  | dgc✅(2023/8/10)  | @huangjiyi  | #56003  | 无需 | 无需 |
| 3  | dgc_momentum✅(2023/8/18) | @huangjiyi  |#56158  | 无需 | #56358  |
| 4  | c_split✅(2023/8/22) | @BeingGod | #56327  | #56327 | 无需 |
| 5  | lars_momentum✅(2023/9/5) | @gouzil | #55798 | #56751 | #56749 |
| 6  | nop✅(2023/8/3) | @gouzil  | #55816 | 无需 | 无需 |
| 7  | ftrl | @enkilee  | #56270  |  |  |
| 8  | decayed_adagrad✅(2023/8/5) | @GreatV  | #55995   | 无需 | #55995 |
| 9  | c_identity✅(2023/8/23) |  @GreatV | #56215  | #56215 | #56215 |
| 10  | distributed_fused_lamb_init✅(2023/8/31)   | @zeroRains  | #55993  |无需  | 无需 |
| 11  | limit_by_capacity✅(2023/8/18) | @yangguohao  | #55948  | 无需 | 无需 |
| 12  | number_count✅(2023/8/15) | @BeingGod  | #56128 |无需  |  无需|
| 13  | ~~distributed_fused_lamb~~ | 上期迁移过  |  |  |  |
| 14  | random_routing✅(2023/8/1) | @AndSonder | #55773 | 无需 | 无需 |
| 15 | prune_gate_by_capacity✅(2023/8/1)  | @AndSonder | #55780 | 无需 | 无需 |
| 16  | assign_pos✅(2023/8/16)  | @AndSonder | #55794 | 无需 | 无需 |
| 17  | fused_softmax_mask_upper_triangle✅(2023/8/1) | @AndSonder | #55769 | 无需 | 无需 |

**Comment by GreatV** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
8 | decayed_adagrad |  @GreatV
9 | c_identity | @GreatV

**Comment by BeingGod** [comment]
<!DOCTYPE html>

序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel ) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
1 | c_embedding | @BeingGod |  https://github.com/PaddlePaddle/Paddle/pull/56129
4 | c_split| @BeingGod | https://github.com/PaddlePaddle/Paddle/pull/56327
12 | number_count | @BeingGod | https://github.com/PaddlePaddle/Paddle/pull/56128


<br class="Apple-interchange-newline">

**Comment by AndSonder** [comment]
| 序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel) | PR(xpu kernel) | PR(InferShape) |
| :--- | :---: | :---: | :---: | :---: | :---: |
| 14 | random_routing | @AndSonder  | #55773 | - | - |
| 15 | prune_gate_by_capacity | @AndSonder  | #55780 | - | - |
| 16 |assign_pos | @AndSonder  | #55794 | - | - |
| 17 | fused_softmax_mask_upper_triangle | @AndSonder  | #55769 | - | - |

**Comment by gouzil** [comment]
序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
5 | lars_momentum | @gouzil  | #55798  |   |  
6 | nop | @gouzil  |  #55816  |  -  | -

**Comment by enkilee** [comment]
<html>
<body>


序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
7 | ftrl | @enkilee |   |   |  


</body>
</html>

**Comment by huangjiyi** [comment]
|序号|算子名称|认领人|PR(cpu/gpu kernel)|PR(xpu kernel)|PR(InferShape)|
|---|---|---|---|---|---|
| 2 | dgc | @huangjiyi |
| 3 | dgc_momentum | @huangjiyi |

**Comment by yangguohao** [comment]
<html>
<body>


序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel) | PR(xpu kernel) | PR(InferShape)
-- | -- | -- | -- | -- | --
11 | limit_by_capacity | @yangguohao  |  



<br class="Apple-interchange-newline">
</body>
</html>

**Comment by AndSonder** [comment]
@GhostScreaming  fused_softmax_mask_upper_triangle 的任务， fused_softmax_mask_upper_triangle_grad 需要一并迁移吗？

**Comment by GhostScreaming** [comment]
> @GhostScreaming fused_softmax_mask_upper_triangle 的任务， fused_softmax_mask_upper_triangle_grad 需要一并迁移吗？

嗯嗯，对应的反向算子也默认是需要迁移的。

**Comment by zeroRains** [comment]
| 序号 | 算子名称 | 认领人 | PR(cpu/gpu kernel) | PR(xpu kernel) | PR(InferShape) |
| :--- | :---: | :---: | :---: | :---: | :---: |
| 10 | distributed_fused_lamb_init | @zeroRains   | - | - | - |

**Comment by AndSonder** [comment]
random_routing、prune_gate_by_capacity、assign_pos、fused_softmax_mask_upper_triangle 无需迁移 XPU，因为这些算子原本就没有 XPU 的Kernel。也无需迁移 InferShape，因为不涉及到undefined的注册数据类型，无需用InferMeta推导出 dtype 信息

**Comment by GreatV** [comment]
- `c_identity` gpu kernel xpu kernel InferShape 都在PR #56215
- `decayed_adagrad` gpu kernel InferShape 都在PR #55995 ,  xpu kernel 无需迁移

**Comment by AndSonder** [comment]
distributed_fused_lamb 这个算子在上一期中已经迁移过了可以划掉了 @luotao1

**Comment by BeingGod** [comment]
* `c_split` InferShape无需迁移，xpu kernel在https://github.com/PaddlePaddle/Paddle/pull/56327 中
* `c_embedding` InferShape无需迁移，xpu kernel在https://github.com/PaddlePaddle/Paddle/pull/56129 中
* `number_count` xpu kernel，InferShape无需迁移

**Comment by huangjiyi** [comment]
- `dgc` 和 `dgc_momentum` 都没有 xpu kernel，无需迁移
- `dgc` 的 InferShape 只有检查输入输出是否存在，无需迁移
- `dgc_momentum` InferShape 的迁移 PR：#56358

**Comment by zeroRains** [comment]
distributed_fused_lamb_init算子原本就没有 XPU 的Kernel，无须迁移xpu。不涉及到undefined的注册数据类型，无需用InferMeta推导出 dtype 信息，无须迁移InferShape

**Comment by gouzil** [comment]
* `nop`无需迁移 xpu, 也无需迁移 InferShape
 * `lars_momentum` 需要迁移 xpu, 也需要迁移 InferShape. 需要等待 #55798 合入

**Comment by yangguohao** [comment]
limit_by_capacity 无需迁移 XPU 和 InferShape

**Comment by yangguohao** [comment]
limit_by_capacity 无需迁移 XPU 和 InferShape

**Comment by luotao1** [comment]
Fluid下分布式算子迁移已完成，感谢参与的小伙伴们！

> 按 merge 的时间顺序，排名不分先后： @AndSonder (4) @GreatV (2) @BeingGod (3) @huangjiyi (2) @gouzil (2) @yangguohao (1) @zeroRains (1)

欢迎继续参与[快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/56689)！
