### ISSUE TITLE
报错：    forward_gru = fluid.layers.dynamic_gru(input=input_proj_bn_forward, AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_gru'

### ISSUE THREAD

**Issue by liangshu-code** [PaddlePaddle/Paddle#55721]
### 问题描述 Issue Description

fluid.layers模块中没有dynamic_gru这个属性。导致报错：

    forward_gru = fluid.layers.dynamic_gru(input=input_proj_bn_forward,
**AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_gru'**

### 版本&环境信息 Version & Environment Information

Paddle version: 2.5.0
Paddle With CUDA: True

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.8.0

CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: N/A
Nvidia driver version: 535.54.03
Nvidia driver List: 
GPU 0: Quadro P5000

**Comment by YanhuiDua** [comment]
你好，paddle 2.0后 这个api被替换成 paddle.nn.GRU，请参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/convert_from_older_versions/paddle_api_mapping_cn.html#paddle-1-8-paddle-2-0-api

**Comment by liangshu-code** [comment]
好的谢谢

**Comment by tonyliu088** [comment]
AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_lstm' ，请问如何用api 2.0 修改

**Comment by YanhuiDua** [comment]
> AttributeError: module 'paddle.fluid.layers' has no attribute 'dynamic_lstm' ，请问如何用api 2.0 修改

你好，API的映射关系可以参考官网文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/convert_from_older_versions/paddle_api_mapping_cn.html#paddle-1-8-paddle-2-0-api

dynamic_lstm对应paddle2.0的paddle.nn.LSTM，具体使用参考https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/LSTM_cn.html

**Comment by tonyliu088** [comment]
dynamic_lstm对应paddle2.0的paddle.nn.LSTM，语法上完全变了，请问有api2.0 demo 可以参考下么
