### ISSUE TITLE
paddle2.5安装报错

### ISSUE THREAD

**Issue by DLlearn** [PaddlePaddle/Paddle#55725]
### 问题描述 Issue Description

系统:ubuntu18.04
cuda:12.0
安装使用conda:
```bash
conda create -n pd python=3.9
conda install paddlepaddle-gpu==2.5.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/
```
报错：
```bash
>>> import paddle
Error: Can not import paddle core while this file exists: /home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/ai/anaconda3/envs/pd/lib/python3.9/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory
```

### 版本&环境信息 Version & Environment Information

原系统cuda:12.0
conda环境：10.2

**Comment by YanhuiDua** [comment]
python -m pip install paddlepaddle-gpu==2.5.0.post102 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

**Comment by DLlearn** [comment]
> python -m pip install paddlepaddle-gpu==2.5.0.post102 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

不行，这个不就是官网pip的安装方法么，我是想用cuda10.2的，conda装一套都搞定

**Comment by YanhuiDua** [comment]
你的版本装错了，你这个命令装的是11.2的

**Comment by DLlearn** [comment]
> 你的版本装错了，你这个命令装的是11.2的

conda install paddlepaddle-gpu==2.5.0 cudatoolkit=10.2 --channel https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/，你是说这个命令吗，我可是从官网哪里拷贝过来的啊？

**Comment by DLlearn** [comment]
> 你的版本装错了，你这个命令装的是11.2的

我试试

**Comment by YanhuiDua** [comment]
抱歉，是我看错了安装方式，你的安装命令是对的哈，在根目录下搜下是否存在libcudart.so.10.2,如果有的话，把对应的路径加到LD_LIBRARY_PATH，没有的话请检查安装的CUDA版本是否正确

**Comment by DLlearn** [comment]
> 抱歉，是我看错了安装方式，你的安装命令是对的哈，在根目录下搜下是否存在libcudart.so.10.2,如果有的话，把对应的路径加到LD_LIBRARY_PATH，没有的话请检查安装的CUDA版本是否正确
老哥，说实际的，人们用conda安装用户应该不会比pip少，咱用心点，像其它框架一样，一个命令执行完搞定不可以么？框架难度大都做好了，安装却做不好也不是百度的实力啊

**Comment by YanhuiDua** [comment]
如果你想使用一个命令安装好所有的东西，建议可以使用docker镜像；https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html；

你这里报错是CUDA版本与安装的Paddle不匹配，跟一个命令执行完似乎没什么关系

**Comment by DLlearn** [comment]
> 如果你想使用一个命令安装好所有的东西，建议可以使用docker镜像；[https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html；](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html%EF%BC%9B)
> 
> 你这里报错是CUDA版本与安装的Paddle不匹配，跟一个命令执行完似乎没什么关系

你错了，我这里不是不匹配，是找不到，conda已经把所有都下载好了，但是找不到，https://blog.csdn.net/qq_41982466/article/details/129202110       这是网上的答案，可以解决，你看看，如你之前回答，加到LD_LIBRARY_PATH。再说其它框架也有conda命令，照着做了不会有问题啊。还有一键安装好并非docker这种重量级的，conda是一个很好的选择。
