### ISSUE TITLE
【艾尔登】任务线二：「癫火之王 👑」之 「 `ProgramTranslator` 专项」

### ISSUE THREAD

**Issue by Aurelius84** [PaddlePaddle/Paddle#55735]
## 一、Background 🎃
详见：https://github.com/PaddlePaddle/Paddle/issues/55205

### 2.1 赛题介绍
WIP
### 2.2 参考链接
WIP
## 三、任务总览
序号 | 模块 | 任务描述 | PR | 贡献者
| - | - | - | - | - |
2.1 | 机制 ✅| 动静Op定义的参数名映射修复  |#55334 | 见issue
2.2 | OP ✅| ProgramTranslator支持fill_constant有可变属性的情形 |#55378 | @wanghuancoder 
2.3 | OP ✅| elementwise支持带axis的情形 |#55485 | @kangguangli
2.4 | 机制 | Op属性默认值处理，完善OpYamlInterface，让其中的OpAttributeInfo提供默认的ir::Attribute而非字符串 (WIP) |   | 
2.5 | Printer | 增加PrinterOption，允许控制打印粒度和级别(WIP) |   | 
2.6 | Printer | 优化 Value 打印，打印Value时不通过数字编号，而是针对Program的每个Value有一个固定的更可读的名字(WIP) |   | 
2.7 | OP ✅| 解决废弃算子mul op 在新 IR 下的translator问题 ，见 #56521 | #56550| @DrRyanHuang  |
2.8 | Printer | 为IR Printer实现算子级别的hook(#57234) | | @xingmingyyj

**Comment by Difers** [comment]
认领2.2
