### ISSUE TITLE
Paddle是否支持非图像数据进行训练？

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/Paddle#55743]
### 请提出你的问题 Please ask your question

发现飞桨的套件训练数据大都是3通道的图像数据，是否支持多通道的非图像数据进行训练呢？例如：256*256*20，这样的数据会不会对飞桨整体套件适应性有所挑战？谢谢。

**Comment by 1220985305** [comment]
例如：数据shape是256 * 256 * 20

**Comment by zhwesky2010** [comment]
@1220985305 你好，请问具体是哪个套件repo呢

**Comment by 1220985305** [comment]
PaddleSeg
