### ISSUE TITLE
paddle.jit.save报错问题，已解决

### ISSUE THREAD

**Issue by lidongJMX** [PaddlePaddle/Paddle#55748]
### 问题描述 Please describe your issue

https://github.com/PaddlePaddle/VisualDL/blob/develop/docs/components/README_CN.md#Graph--%E7%BD%91%E7%BB%9C%E7%BB%93%E6%9E%84%E7%BB%84%E4%BB%B6
使用add_graph这个接口
`net = MyNet()
with LogWriter(logdir="./log/graph_test/") as writer:
    writer.add_graph(
        model=net,
        input_spec=[paddle.static.InputSpec([-1, 1, 28, 28], 'float32')],
        verbose=True)`
然后再aistudio里面启动可视化服务就可以看到了

**Comment by zhwesky2010** [comment]
@lidongJMX 你好，请问现在还有问题吗
