### ISSUE TITLE
Change gflag.cmake to use default repo

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5576]
Currently, our gflags.cmake file refers to my personal fork of gflags:

https://github.com/PaddlePaddle/Paddle/blob/1c31bb94596266136ea9a77c32b6380cbe990a2b/cmake/external/gflags.cmake#L31-L39

This is because of a bug in the official gflags repo as mentioned in https://github.com/PaddlePaddle/Paddle/issues/3277.  I filed a PR https://github.com/gflags/gflags/pull/230 to fix the bug, and it seems that gflags maintainers have merged it.  So it is the time for us to switch back using the official gflags repo.

**Comment by Xreki** [comment]
Now the official gflags repo is used in Paddle, see 

https://github.com/PaddlePaddle/Paddle/blob/5c500c6f85943f82d3e6b06f0fd87bff08db01e2/cmake/external/gflags.cmake#L28-L47
