### ISSUE TITLE
paddlepaddle-gpu2.4.2能在cuda11.8上运行么？

### ISSUE THREAD

**Issue by zengtao1978** [PaddlePaddle/Paddle#55775]
### 请提出你的问题 Please ask your question

paddlepaddle-gpu2.4.2能在cuda11.8上运行么？

**Comment by qili93** [comment]
@zengtao1978 Paddle 2.4.2 支持的最高CUDA 版本为 11.7，可参考 https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 中的whl安装包，这里红框中显示的就是对应的CUDA版本号

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/a6fcff5c-fc22-4fcc-8670-ab27a62e9115)

**Comment by zengtao1978** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/4972224/2b481c8e-d19d-4a29-9627-f91745738152)
![image](https://github.com/PaddlePaddle/Paddle/assets/4972224/b71aa58d-e40d-44c2-bdcb-b4f1122ace0b)
拿为何报这个错误，需要配置什么参数么？

**Comment by zengtao1978** [comment]
或者需要重新编译paddlepaddle-gpu么？

**Comment by zengtao1978** [comment]
pip install ***.whl即可
