### ISSUE TITLE
关于训练数据的读取问题

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#5577]
我从这里下载了数据：
https://archive.ics.uci.edu/ml/machine-learning-databases/housing/housing.data
把数据存放在当前目录的housedata.train文件中。

然后我把线性回归中这一行做了修改：
paddle.batch(
            paddle.reader.shuffle(uci_housing.train(), buf_size=500),
            batch_size=2)
改为：
paddle.batch(
            paddle.reader.shuffle(paddle.reader.creator.text_file("housedata.train"), buf_size=500),
            batch_size=2)

目的是想自己替换下数据试试
可是报错：ValueError: The input should be a vector, please check your input data.

貌似对数据不认识。我应该如何组织数据呢？求教

**Comment by luotao1** [comment]
请参考 http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/concepts/use_concepts_cn.html#id4

**Comment by sandycs** [comment]
@luotao1 文档里对于如何构建reader语焉不详
我猜测我的主要原因是对PYTHON这个语言不熟悉
是否有c++版本的paddlepaddle

**Comment by luotao1** [comment]
paddle有c-API，用于inference，但不能用来训练: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/README.md
