### ISSUE TITLE
Paddle 2.5.1 关闭不必要debug日志

### ISSUE THREAD

**Issue by JiehangXie** [PaddlePaddle/Paddle#55771]
### 请提出你的问题 Please ask your question

Paddle版本：2.5.1

使用Paddle的时候，每次加载模型推理都会触发stats.h输出debug信息，请问有方法全局关掉这个信息显示吗？

![image](https://github.com/PaddlePaddle/Paddle/assets/51190264/9693c0ad-fcfa-467e-99a2-ea0e569c0834)

**Comment by qili93** [comment]
@JiehangXie 

根据这里的代码 https://github.com/PaddlePaddle/Paddle/blob/v2.5.1/paddle/fluid/memory/stats.h#L78

这个信息应该只有在开启GLOG_v>=8的时候才会显示，请检查一下您环境中设置的 GLOG_v的变量，默认设置为0的话，就不会显示debug信息。关闭具体命令为 `export GLOG_v=0`。

**Comment by GreatV** [comment]
也可以试试 GLOG_minloglevel=100
