### ISSUE TITLE
Plugin无法使用 DenseTensor.clear() method

### ISSUE THREAD

**Issue by wuwuwuxxx** [PaddlePaddle/Paddle#55795]
### bug描述 Describe the Bug

```shell
error: ‘class phi::DenseTensor’ has no member named ‘clear’
         dx->clear();
             ^~~~~
ninja: build stopped: subcommand failed.
```

### 其他补充信息 Additional Supplementary Information

paddle gpu在解决inplace tensor的计算的时候使用了一个[clear api](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/elementwise_grad.h#L166)，
但是这个api在plugin没法使用，编译会报错

**Comment by qili93** [comment]
这个接口定义在 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/dense_tensor.inl#L60 中。

这个头文件中定义的接口会不对外暴露，且在将来会被移除，见以下头文件中的说明。建议您在算子实现中避免对这个clear接口的调用，谢谢！

<img width="677" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1707764b-e536-457b-90c4-b9399a95d370">

**Comment by wuwuwuxxx** [comment]
我如果想实现类似的功能应该怎么做呢  @qili93

**Comment by wuwuwuxxx** [comment]
或者有没有一个更好的解决方案？

**Comment by qili93** [comment]
@wuwuwuxxx 根据算子实现中的注释，只有 “inplace strategy” 下才需要对dx进行特殊处理，请问您这里算子组网调用的是 inplace api 接口 add_ 吗？https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/add__cn.html

如果算子组网调用的是正常的 add 接口而不是 add_，可以在您的算子实现暂时忽略对 inplace 的处理，即代码 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/elementwise_grad.h#L165 这里返回 false，不会返回true。

**Comment by wuwuwuxxx** [comment]
我测试的就是resnet50，官方的实现，他的反向就是inplace的

**Comment by YuanRisheng** [comment]
这个后续提交PR将clear接口暴露

**Comment by wuwuwuxxx** [comment]
@YuanRisheng 这个预计啥时候能提交到develop里面，如果快的话，我们有些代码想基于这个api做开发。

**Comment by YuanRisheng** [comment]
已提交PR：https://github.com/PaddlePaddle/Paddle/pull/55844

**Comment by qili93** [comment]
PR 已合入，请尝试最新Paddle develop分支编译的代码，issue关闭。
