### ISSUE TITLE
develop分支最新代码编译安装后报错hard_sigmoid is not ready for custom kernel registering错误

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/Paddle#55791]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/8075567/8da682ed-ee2e-4e44-8cbd-e7d41a566f1a)

**Comment by qili93** [comment]
此问题是由于Paddle框架侧的kernel名称变化导致的。请参考 https://github.com/PaddlePaddle/PaddleCustomDevice/pull/702 的修改，更改修改您在custom device中注册的kernel的名称即可。
