### ISSUE TITLE
能否对外开放format.py

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle#55819]
### 需求描述 Feature Description

任务目标： 让TVM成功编译PaddlePaddle量化模型
需求场景： 搭建TM单测时需要开放量化算子节点
场景描述：TVM单测需要搭建动态图模型，Paddle量化模型的`dequantize_linear `和`quantize_linear `算子的动态图算子似乎没有对外开放

### 替代实现 Alternatives

查了下量化算子的节点应该在[format.py](https://github.com/PaddlePaddle/Paddle/blob/345de9a5992198f6577f8a12e5f1dc2a414c13ef/python/paddle/nn/quant/format.py)有考虑在正式版本开放这个算子吗？

**Comment by minghaoBD** [comment]
paddle动态图量化模型的逻辑是：构造了LinearQuanter和LinearDequanter两个layer，底层通过_C_ops.quantize_linear调用到了kernel： QuantizeLinearKernel。针对你的使用场景，有如下两个建议

1. 直接使用paddle-inference/PaddleLite 推理库：https://www.paddlepaddle.org.cn/inference/v2.5/guides/introduction/index_intro.html / https://www.paddlepaddle.org.cn/lite
2. 写脚本把quantize_linear封装的scale拿出来传给tvm

**Comment by Zheng-Bicheng** [comment]
> paddle动态图量化模型的逻辑是：构造了LinearQuanter和LinearDequanter两个layer，底层通过_C_ops.quantize_linear调用到了kernel： QuantizeLinearKernel。针对你的使用场景，有如下两个建议
> 
> 1. 直接使用paddle-inference/PaddleLite 推理库：https://www.paddlepaddle.org.cn/inference/v2.5/guides/introduction/index_intro.html / https://www.paddlepaddle.org.cn/lite
> 2. 写脚本把quantize_linear封装的scale拿出来传给tvm

您好，Paddle在TVM下的单测文件保存在[test_forward.py](https://github.com/apache/tvm/blob/main/tests/python/frontend/paddlepaddle/test_forward.py)中，您可以看到基本上都是使用构建动态图的形式进行单测。使用PaddleLite读取模型可能不兼容tvm读取模型的格式，我其实比较疑惑的点是为什么不对外暴露`LinearQuanter `和`LinearDequanter `两个类，平时是不需要接触到这两个类吗？

**Comment by RachelXu7** [comment]
量化时会对这两个类调用，但这比较偏低层，直接暴露出来用户不一定理解其含义，调用也需要自行写太多代码，所以我们选择封装起来。当然，有需求的话，我们会考虑放到nn.layer下对外开放。

**Comment by Zheng-Bicheng** [comment]
@minghaoBD @RachelXu7 感谢两位大佬，问题已经解决了，在tvm中建议使用`paddle.static.load_inference_model`接口读取模型
