### ISSUE TITLE
Unitest framework can`t check LOD of tensor

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#5581]
`check_output` in [op_test.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/op_test.py#L315) does`t support for checking LOD of tensor. 
We just get and check data in [check_output_with_place]( https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/op_test.py#L305)

**Comment by qingqing01** [comment]
@wanghaoshuang 

Do you want to check the output LoD for the operator?  The `op_test.py` supports it. You can refer to `test_lstm_op.py`: 

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/framework/tests/test_lstm_op.py#L158

make the output is a tuple: (output_numpy_array, output_LoD)

```python
 self.outputs = { 'Output': (out, lod)}
```
