### ISSUE TITLE
跑mpi任务出现'Params over flow error'

### ISSUE THREAD

**Issue by Bella-Zhao** [PaddlePaddle/Paddle#5584]
跑Mpi任务时，训练完第一个Pass后出现以下error：

> Sat Nov 11 00:15:39 2017[1,12]<stderr>:*********************Shell Script Stack Trace********************
Sat Nov 11 00:15:39 2017[1,12]<stderr>: @: [./log.sh: 41] log_fatal
Sat Nov 11 00:15:39 2017[1,12]<stderr>: @: [./common.sh: 399] kill_pserver2_exit
Sat Nov 11 00:15:39 2017[1,12]<stderr>: @: [./train.sh: 242] main
Sat Nov 11 00:15:39 2017[1,12]<stderr>:
Sat Nov 11 00:15:39 2017[1,12]<stderr>:+ exit 1
Sat Nov 11 00:26:13 2017[1,13]<stderr>:[INFO 2017-11-11 00:26:13,260 trainer_config.conf:126] Test at Pass 0, {'__auc_evaluator_0__': 0.7254259586334229, 'classification_error_evaluator': 0.04435134679079056}
Sat Nov 11 00:26:41 2017[1,13]<stderr>:Traceback (most recent call last):
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "conf/trainer_config.conf", line 182, in <module>
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    use_gpu=False)
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "conf/trainer_config.conf", line 139, in train
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    num_passes=num_passes)
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "/home/disk1/normandy/maybach/333156/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 175, in train
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    event_handler(v2_event.EndPass(pass_id, evaluator=pass_evaluator))
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "conf/trainer_config.conf", line 133, in _event_handler
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    trainer.save_parameter_to_tar(f)
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "/home/disk1/normandy/maybach/333156/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 107, in save_parameter_to_tar
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    self.__parameters__.to_tar(f)
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "/home/disk1/normandy/maybach/333156/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 271, in to_tar
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    self.serialize(nm, buf)
Sat Nov 11 00:26:41 2017[1,13]<stderr>:  File "/home/disk1/normandy/maybach/333156/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/parameters.py", line 253, in serialize
Sat Nov 11 00:26:41 2017[1,13]<stderr>:    f.write(param.tostring())
Sat Nov 11 00:26:41 2017[1,13]<stderr>:OverflowError: length too large
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ '[' 1 -ne 0 ']'
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ kill_pserver2_exit
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ ps aux
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ grep paddle_pserver2
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ grep paddle_cluster_job
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ grep -v grep
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ cut -c10-14
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ xargs kill -9
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit'
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ echo '[./common.sh : 399] [kill_pserver2_exit]'
Sat Nov 11 00:26:54 2017[1,13]<stderr>:[./common.sh : 399] [kill_pserver2_exit]
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit'
Sat Nov 11 00:26:54 2017[1,13]<stderr>:[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ get_stack
Sat Nov 11 00:26:54 2017[1,13]<stderr>:+ set +x
Sat Nov 11 00:26:54 2017[1,13]<stderr>:

我的mpi版本是参考http://wiki.baidu.com/pages/viewpage.action?pageId=327596461 安装的
看到类似issue，https://github.com/PaddlePaddle/Paddle/issues/2895 ，里面据说已经fixed，目前更新到mpi的版本里了吗？如果没有，请问我应该如何修改代码，以保证在mpi上不出错呢？

**Comment by pkuyym** [comment]
可以用最新源码编译后提交

**Comment by Bella-Zhao** [comment]
@pkuyym 请问是否可以指导一下如何编译最新源码，提交mpi任务，谢谢！

**Comment by pkuyym** [comment]
@Yancey1989 麻烦看一下是否需要更新receiver里面的paddle环境？

**Comment by Yancey1989** [comment]
Hi @pkuyym @Bella-Zhao 
可以使用http://wiki.baidu.com/pages/viewpage.action?pageId=327596461 中本地提交的方式来提交paddle任务。

**Comment by Bella-Zhao** [comment]
@Yancey1989 我就是按照wiki里的提交方式提交的，出现了param OverflowError: length too large的错误

**Comment by pkuyym** [comment]
@Bella-Zhao 你参照本地提交方式看看？

> 本地提交集群训练任务(package提交)

**Comment by Bella-Zhao** [comment]
好的，谢谢，我先试一下

**Comment by Bella-Zhao** [comment]
问题解决了，感谢@pkuyym @Yancey1989 

另外，
http://wiki.baidu.com/pages/viewpage.action?pageId=327596461 这个里面的
![image](https://user-images.githubusercontent.com/29970079/32875371-3e1232b2-ca5d-11e7-84ba-af515dda61a9.png)
似乎应该是before_train_hook.sh，参考
![image](https://user-images.githubusercontent.com/29970079/32875379-502e65ec-ca5d-11e7-97bb-293b47b66315.png)
before_hook.sh无效，before_train_hook.sh有效。
