### ISSUE TITLE
请问docker paddle-gpu的cuda版本必须和主机对应吗

### ISSUE THREAD

**Issue by TerryBryant** [PaddlePaddle/Paddle#55845]
比如我的主机装的cuda版本是11.4，然后docker paddle-gpu拉取的是cuda12版本的镜像，启动镜像之后，import paddle就会出现“You are using GPU version Paddle, but your CUDA device is not set properly”

**Comment by TerryBryant** [comment]
我的主机安装的cuda版本和驱动版本分别是11.4，470.199.02，然后参考[https://docs.nvidia.com/deploy/cuda-compatibility/](nvidia官网)的cuda版本和驱动版本对应关系，cuda11.6或者cuda12.0都是能兼容470.199.02驱动的。然而我尝试安装了这两个版本的docker paddle，进入容器之后均出现了“You are using GPU version Paddle, but your CUDA device is not set properly”

**Comment by AndSonder** [comment]
> your CUDA device is not set properly”

可以试试使用 nvidia-docker 去启动你的docker容器

**Comment by minghaoBD** [comment]
建议：
1. 可以试试使用 nvidia-docker 去启动你的docker容器
2. 使用11.2 or 11.4的镜像
3. 在docker里面尝试安装11.6的cuda-compat：apt install cuda-compat-11-6

**Comment by TerryBryant** [comment]
> > your CUDA device is not set properly”
> 
> 可以试试使用 nvidia-docker 去启动你的docker容器

尝试过了，不行，最后在docker run后面添加--gpus all解决了
