### ISSUE TITLE
编译paddlepaddle源码后，安装的时候出现错误

### ISSUE THREAD

**Issue by zhanghuihuichen** [PaddlePaddle/Paddle#55853]
### 问题描述 Issue Description

在飞腾主机+昆仑芯R2000的环境下，编译PaddlePaddle的源码，在安装生成的安装包的时候出现错误

ModuleNotFoundError: No module named 'paddle.incubate.autograd.phi_ops_map'
![微信图片_20230801105242](https://github.com/PaddlePaddle/Paddle/assets/56913460/5773a48f-a9a1-4e38-b072-b2b4ca8d0bda)

### 版本&环境信息 Version & Environment Information

cmake  
cmake .. -DPY_VERSION=3.8\
             -DPYTHON_EXECUTABLE=$python_exe\
             -DPADDLE_VERSION=2.4.2\
             -DWITH_ARM=ON\
             -DWITH_AARCH64=ON\
             -DWITH_MKL=OFF\
             -DWITH_TESTING=OFF\
             -DCMAKE_BUILD_TYPE=Release\
             -DON_INFER=ON\
             -DWITH_PYTHON=ON\
             -DWITH_CRYPTO=ON\
             -DWITH_XBYAK=OFF\
             -DCMAKE_CXX_FLAGS="-Wno-error -w"\
             -DWITH_GPU=OFF\
             -DWITH_XPU=ON\
             -DWITH_XPU_BKCL=ON\
             -DWITH_DISTRIBUTE=ON\
             -DWITH_PSCORE=OFF

操作系统：麒麟V10
加速芯片：昆仑R200
主机：飞腾T2000

**Comment by lyuwenyu** [comment]
https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
这里有和你匹配的预编译版本嘛，如果是源代码参考这里的按照流程
