### ISSUE TITLE
昇腾910编译paddle，是否cann版本只支持5.0.2，还是更高版本也可以支持

### ISSUE THREAD

**Issue by AIMBY** [PaddlePaddle/Paddle#55875]
### 问题描述 Issue Description

参考官网文档编译paddle，昇腾910编译paddle，是否cann版本只支持5.0.2，还是更高版本也可以支持

### 版本&环境信息 Version & Environment Information

昇腾910编译paddle，是否cann版本只支持5.0.2，还是更高版本也可以支持

**Comment by lyuwenyu** [comment]
支持的版本请参考这里 https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html

![Uploading image.png…]()
