### ISSUE TITLE
新网站中文版本中的英文页面

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5588]
http://www.paddlepaddle.org/docs/develop/models/README.cn.html
12 目标检测 中，点击 Single Shot MultiBox Detector，进去是一个全英文的页面，其中很往下有一行中文

**Comment by sweetsky0901** [comment]
9 阅读理解，存在相同的问题

**Comment by sweetsky0901** [comment]
8 序列到序列的学习，
8.4点进去什么都没有

**Comment by sweetsky0901** [comment]
8.1点进去，也是全英文的，并且下面还带着被划掉的很多文字

**Comment by sweetsky0901** [comment]
6.1也是全英文的

**Comment by sweetsky0901** [comment]
3.1点进去，也几乎全是英文，只有一行中文

**Comment by lcy-seso** [comment]
这个是因为网站指向的原始内容来自models。
1. SSD 之前的中文内容被删掉，最近已经加回来。这个预览的页面应该还没有同步最新的dev。
2. 8.4 的README还没有merge，所以没有什么内容。
3. 点进去全是英文的是因为这些例子在merge的时候都只有英文的README。

这些问题我们是否需要排一个计划，按部就班的处理一下呢？

**Comment by shanyi15** [comment]
非常感谢您的建议，以上模型文档现在的状态是：

12. 已翻译 http://www.paddlepaddle.org/docs/develop/models/ssd/README.cn.html
8.4 已翻译 http://www.paddlepaddle.org/docs/develop/models/generate_chinese_poetry/README.html
8.1 已翻译，删除线已没有http://www.paddlepaddle.org/docs/develop/models/nmt_without_attention/README.cn.html
6.1 已翻译 http://www.paddlepaddle.org/docs/develop/models/dssm/README.cn.html
3.1 已翻译 http://www.paddlepaddle.org/docs/develop/models/ctr/README.cn.html

**待翻译：**
9. 阅读理解
http://www.paddlepaddle.org/docs/develop/models/globally_normalized_reader/README.html 

我们的工作中有梳理文档的项目，中英文翻译的完善也是该项目的一部分。故此isseu关闭，后续我们将加快翻译进度。

非常感谢！
