### ISSUE TITLE
单机多卡Collective 模式下训练集加载多次

### ISSUE THREAD

**Issue by Nero1996** [PaddlePaddle/Paddle#55898]
### 请提出你的问题 Please ask your question

在单机多卡数据并行场景下使用spwan启动
无论是直接加载DataLoader还是使用DistributedBatchSampler都会把整个数据集加载多遍导致每个子进程都占用大量内存
有没有办法只加载一遍训练集让多卡共享呢？
单机多卡下它们并行的时候是各自完成整个训练集的训练还是共同完成一次epcho？

**Comment by zhiboniu** [comment]
使用DistributedBatchSampler的时候虽然每张卡都会加载数据集，但是不同卡会分配不同位置的数据。如果想减少这部分消耗可以把num_worker数量降一些
