### ISSUE TITLE
新网站某些目录点击无效果

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5589]
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/cluster/cluster_train_cn.html#启动计算节点

当我点击 启动计算节点的时候，并没有跳到预期的地方

**Comment by sweetsky0901** [comment]
几乎
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/cluster/cluster_train_cn.html
上的目录，点击都没有效果
我的是chrome的浏览器

**Comment by jetfuel** [comment]
Thank you for reporting. We are looking into this.

**Comment by shanyi15** [comment]
您好，这篇文档结构已做修改，同时，issue中提到的问题也已消除，请参考http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/cluster/index_cn.html
