### ISSUE TITLE
新网站的存在部分死链

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5590]
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/k8s/k8s_cn.html
比如这个页面上的Quick Start Tutorial 
http://www.paddlepaddle.org/doc/demo/quick_start/index_en.html，打不开
Docker installation guide
http://www.paddlepaddle.org/doc/build/docker_install.html，也打不开

**Comment by sweetsky0901** [comment]
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/k8s/k8s_distributed_cn.html页面里的 Cluster Training
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/cluster/opensource/cluster_train.md
打开是404页面

**Comment by luotao1** [comment]
solved by #6748
