### ISSUE TITLE
[UT] nearest interp v2 某些case dtype=float32时计算结果超过误差限

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/Paddle#55913]
### bug描述 Describe the Bug

复现代码：
```python
class TestNearestNeighborInterpCase2FP32(TestNearestInterpOp):
    def init_test_case(self):
        create_test_case2(self)
        self.dtype = np.float32
```

报错截图：
![image](https://github.com/PaddlePaddle/Paddle/assets/31957460/4335a08f-e91b-4d52-99a5-2619b75fbe08)

### 其他补充信息 Additional Supplementary Information

commitid: feff99f5e164afd0b9c4dd27264db37de75ce0cb

**Comment by zhiboniu** [comment]
请问这是哪一个API，同时辛苦提供一下环境信息，包括python版本、cuda、cudnn、系统版本等。

**Comment by BeingGod** [comment]
API: nearest_interp_v2
单测文件: `legacy_test/test_nearest_interp_v2_op.py`

环境信息（官方GPU Docker镜像）
* Python版本：3.8
* cuda：11.7
* cudnn：8.4.1
* 系统版本：ubuntu18.04

**Comment by luotao1** [comment]
@BeingGod 现在还有这个问题么

**Comment by BeingGod** [comment]
6f93f9c718213ea2f619f1f56cc3b07b21b8f34c 上已无该问题
