### ISSUE TITLE
pdparams 动态图模型转静态图后 出现一些无用算子，如何解决？

### ISSUE THREAD

**Issue by gooddog22** [PaddlePaddle/Paddle#55916]
### 请提出你的问题 Please ask your question

pdparams 动态图模型转静态图后 出现一些无用算子，如何解决？

![image](https://github.com/PaddlePaddle/Paddle/assets/754114/bb3f6387-588e-476e-b856-39f2648d04cc)

**Comment by zhiboniu** [comment]
请问这里面无用的算子指的是哪些？
