### ISSUE TITLE
新网站页面跳转体验问题

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5592]
当我点击左侧菜单中的某一项的时候，比如API中的模型配置，右侧显示了菜单内容，但是左侧主菜单又变到最上面

**Comment by luotao1** [comment]
请问左侧菜单栏能不能在点击后，固定在这个位置呢 @jetfuel

**Comment by jetfuel** [comment]
Thank you for the feedback. We will evaluate the work first. @varunarora any thought?

**Comment by shanyi15** [comment]
Close due to https://github.com/PaddlePaddle/PaddlePaddle.org/issues/387
