### ISSUE TITLE
可不可以把非avx的包也编译到PaddlePaddle里？

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#55939]
### 需求描述 Feature Description

自然语言处理、图像检测等项目训练和项目部署操作，在做项目的时候，经常会遇到非avx的服务器，自行编译太痛苦了，可不可以想pytorch一样，同时支持avx和非avx的cpu？
强烈希望官方加一下，经常需要考虑不同的python版本和paddlepaddle版本。

**Comment by cuicheng01** [comment]
感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～

**Comment by yangy996** [comment]
> 感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～

好的，如果仅只编译CPU版的还好，但涉及到编译GPU版的个人就无法编译了，版本太多了，还望尽量加一下，感谢！

**Comment by MooTong123** [comment]
> 感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～
你好，请问下，no-avx的paddlepaddle该如何下载啊？？我的操作系统是麒麟v10 sp3，根据文档中的安装目录是：

```
python3 -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

但这是avx版本的，结果我安装完，运行后报错：
```
 Your machine doesn't support AVX, but the installed paddlepaddle is avx core, you should reinstall paddlepaddle with no-avx core.
```

所以安装paddlepaddle-gpu no-avx版本的安装命令是啥啊？

**Comment by yangy996** [comment]
> > 感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～
> > 你好，请问下，no-avx的paddlepaddle该如何下载啊？？我的操作系统是麒麟v10 sp3，根据文档中的安装目录是：
> 
> ```
> python3 -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> ```
> 
> 但这是avx版本的，结果我安装完，运行后报错：
> 
> ```
>  Your machine doesn't support AVX, but the installed paddlepaddle is avx core, you should reinstall paddlepaddle with no-avx core.
> ```
> 
> 所以安装paddlepaddle-gpu no-avx版本的安装命令是啥啊？

官网下面有说明，但python版本限制在3.8

**Comment by MooTong123** [comment]
> > > 感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～
> > > 你好，请问下，no-avx的paddlepaddle该如何下载啊？？我的操作系统是麒麟v10 sp3，根据文档中的安装目录是：
> > 
> > 
> > ```
> > python3 -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 但这是avx版本的，结果我安装完，运行后报错：
> > ```
> >  Your machine doesn't support AVX, but the installed paddlepaddle is avx core, you should reinstall paddlepaddle with no-avx core.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 所以安装paddlepaddle-gpu no-avx版本的安装命令是啥啊？
> 
> 官网下面有说明，但python版本限制在3.8

你好，在哪里有写，我没找到noavx的安装命令？

**Comment by MooTong123** [comment]
> 感谢提问，这个问题我们会内部评估一下，如果可行，会考虑支持～

请问下，现在有支持paddlepaddle-gpu 支持cuda11.7的no_avx的安装吗？？

现在我使用命令安装：

```
pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
Looking in links: https://www.paddlepaddle.org.cn/whl/linux/mkl/noavx/stable.html
```

报错如下：
```
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.4.2.post117 (from versions: 1.8.5.post97, 1.8.5.post107, 2.0.0rc0, 2.0.0rc1, 2.0.0, 2.0.1, 2.0.2, 2.1.0, 2.1.1, 2.1.2, 2.1.2.post101, 2.1.3, 2.1.3.post101, 2.2.0rc0, 2.2.0rc0.post101, 2.2.0, 2.2.0.post101, 2.2.1, 2.2.1.post101, 2.2.2, 2.2.2.post101, 2.3.0rc0, 2.3.0rc0.post101, 2.3.0rc0.post102, 2.3.0, 2.3.0.post101, 2.3.1, 2.3.1.post101, 2.3.2, 2.3.2.post101, 2.4.0rc0, 2.4.0rc0.post101, 2.4.0, 2.4.1, 2.4.2, 2.5.0rc0, 2.5.0rc1, 2.5.0, 2.5.1)
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2.post117
```

所以现在最新的支持10.1的CUDA吗，没有更新的版本的了吗？
