### ISSUE TITLE
[优化性建议] profiler结果中slice title的时间信息能否去除

### ISSUE THREAD

**Issue by XiaociZhang** [PaddlePaddle/Paddle#55951]
### 问题描述 
如题，例如这么一个slice：AllReduce[5.962 ms]，imo后面的时间信息完全是无效/冗余信息，无论是通过UI去观察还是脚本分析都起不到实际作用，反而会ruin掉这个用法：选中一段trace，里面有多个AllReduce函数，获取AllReduce函数的统计信息，这在Nsight/Android systrace都是很有用的，而Paddle因为多了这个尾巴使用体验会很糟糕。

**Comment by cuicheng01** [comment]
感谢宝贵的建议，我们会认真评估下这个需求～
