### ISSUE TITLE
新网站导航栏名称不一致

### ISSUE THREAD

**Issue by wanghaox** [PaddlePaddle/Paddle#5596]
导航栏的"文档" 在切换到 0.10.0后显示为"文件"

**Comment by jetfuel** [comment]
已修復

**Comment by wanghaox** [comment]
http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/getstarted/index_cn.html
我这里还是显示"文件"

**Comment by luotao1** [comment]
刷新下，或者去除缓存重新加载。我这里是正常显示的：
![image](https://user-images.githubusercontent.com/6836917/32780044-dfed0e1a-c97a-11e7-8038-229b01cdd5c4.png)
