### ISSUE TITLE
申威处理器Paddle安装

### ISSUE THREAD

**Issue by zhuxy-USTC** [PaddlePaddle/Paddle#55971]
### 请提出你的问题 Please ask your question

可以给一下申威处理器下的安装文件吗

**Comment by engineer1109** [comment]
你直接说x86/arm/mips的哪一种，不行吗

**Comment by zhuxy-USTC** [comment]
申威架构啊，SW64

**Comment by engineer1109** [comment]
这个应该不在CI保护里，也没人实验过。纯CPU后端的话，应该都是eigen或openblas。自己试了才知道
