### ISSUE TITLE
paddleinference导出模型问题

### ISSUE THREAD

**Issue by GuoQuanhao** [PaddlePaddle/Paddle#55985]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/49911294/8b7452d7-b9b3-4b9c-ba52-1ca5251087d5)
请问只要是同一种模型，使用不同的方式训练，导出模型中的pdmodel 文件始终是相同的吗，变化的只是 pdiparams吗

**Comment by wangna11BD** [comment]
同一个模型，使用不同的方式训练，导出模型中的pdmodel 文件是相同的～
