### ISSUE TITLE
error: ‘initializeDeviceProp’ is not a member of ‘Eigen’

### ISSUE THREAD

**Issue by Klaoye** [PaddlePaddle/Paddle#55990]
### 问题描述 Issue Description
使用 release/2.5 版本
cmake ../Paddle -DPYTHON_EXECUTABLE:FILEPATH=/home/klaoye/venv/bin/python3.8 -DPYTHON_INCLUDE_DIR:PATH=/opt/python3.8/include/python3.8 -DPYTHON_LIBRARY:FILEPATH=/home/klaoye/venv/lib/ -DWITH_CONTRIB=OFF -DWITH_MKL=OFF -DWITH_MKLDNN=OFF -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DON_INFER=ON -DWITH_PYTHON=OFF -DWITH_XBYAK=OFF -DWITH_NV_JETSON=ON -DCUDA_ARCH_NAME=Auto -DTARGET=ARMV8 -G "Unix Makefiles" -DWITH_NCCL=OFF

###在编译时遇见如下报错，排查eigen版本，确认无误。
/home/klaoye/Paddle/paddle/phi/backends/gpu/gpu_context.cc: In constructor ‘phi::internal::EigenGpuStreamDevice::EigenGpuStreamDevice()’:
/home/klaoye/Paddle/paddle/phi/backends/gpu/gpu_context.cc:67:12: error: ‘initializeDeviceProp’ is not a member of ‘Eigen’
     Eigen::initializeDeviceProp();
            ^~~~~~~~~~~~~~~~~~~~
/home/klaoye/Paddle/paddle/phi/backends/gpu/gpu_context.cc: In member function ‘void phi::internal::EigenGpuStreamDevice::Reinitialize(phi::gpuStream_t, phi::Allocator*, phi::GPUPlace)’:
/home/klaoye/Paddle/paddle/phi/backends/gpu/gpu_context.cc:77:28: error: ‘m_deviceProperties’ is not a member of ‘Eigen’
     device_prop_ = &Eigen::m_deviceProperties[place.device];

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (Ubuntu/Linaro 7.5.0-3ubuntu1~18.04) 7.5.0
Clang version: N/A
CMake version: version 3.27.1
Libc version: glibc 2.27
Python version: 3.8.15

CUDA version: 10.2.300
Build cuda_10.2_r440.TC440_70.29663091_0
cuDNN version: 8.2.1
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************
编译机器为jetson nano a02 4g

**Comment by zhengqiwen1997** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/linux-compile-by-make.html
首先请使用gcc8.2重新试一下，若不行，再试着把cudnn版本降到cudnn7 >=7.6.5

**Comment by idontkonwher** [comment]
@Klaoye Have you solve this problem? I am faced the same issue now.
