### ISSUE TITLE
Segment Parallel 怎么使用？

### ISSUE THREAD

**Issue by windynight** [PaddlePaddle/Paddle#55994]
### 请提出你的问题 Please ask your question

请问Segment Parallel  怎么使用？ 能否给下对应的文档？

**Comment by windynight** [comment]
针对32k 100k长序列的训练配置

**Comment by haohongxiang** [comment]
@windynight 您好，我理解您指的是序列并行（Sequence Parallel）；目前还没有发布相关的使用文档，代码可以参考 [PaddleNLP SP使用](https://github.com/PaddlePaddle/PaddleNLP/blob/develop/model_zoo/gpt-3/ppfleetx/models/language_model/gpt/dygraph/hybrid_model.py#L50-L56)

**Comment by windynight** [comment]
> 

您好，非常感谢您的回复， 我指的是
![image](https://github.com/PaddlePaddle/Paddle/assets/2614472/dd8b4fb2-45de-474c-a5c5-00c1a9a444b5)

这个里面的Segment Parallel

**Comment by haohongxiang** [comment]
> > 
> 
> 您好，非常感谢您的回复， 我指的是 ![image](https://user-images.githubusercontent.com/2614472/258746489-dd8b4fb2-45de-474c-a5c5-00c1a9a444b5.png)
> 
> 这个里面的Segment Parallel

@windynight 抱歉，刚刚理解错了您的意思。Segment Parallel还未开源，目前没有使用文档或代码提供给您。
