### ISSUE TITLE
【demo】【Sentiment Analysis】可能存在内存泄漏

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#560]
运行环境：ubuntu 14.04 docker实例
paddle版本 v0.9.0 cpu版本
trainer.sh运行参数
![image](https://cloud.githubusercontent.com/assets/6229206/20513998/6dd75170-b0c4-11e6-9850-0645fd8c801d.png)
运行1:30秒后采集数据2.5G
第一列为PID 第二列为内存占用百分比   第三列为内存实际这那用大小  第四列开始时间  第五列运行时间
![image](https://cloud.githubusercontent.com/assets/6229206/20514003/79695a6a-b0c4-11e6-949b-ed3d3cec3748.png)
运行结束后4.4G
![image](https://cloud.githubusercontent.com/assets/6229206/20514011/8802d326-b0c4-11e6-9bba-9e83f68ff0b8.png)

**Comment by qingqing01** [comment]
1个pass之内的增长是正常现象，随着句子长度的变化，1个pass之内存是会增长的。通过实验，发现1个pass之后内存会稳定在 4405216 KB 左右。

所以麻烦QA同学 @wen-bo-yang 再测试下。

**Comment by wen-bo-yang** [comment]
@qingqing01 
刚刚从新跑了下，发现在跑到第三轮结束后，内存稳定在1.9%,3870164KB左右，第二次跑的时候没有发现内存问题
