### ISSUE TITLE
Paddle安装问题

### ISSUE THREAD

**Issue by ZeroLelouch1205** [PaddlePaddle/Paddle#56000]
### 问题描述 Issue Description

运行paddleSeg任务时Cuda11.2+Cudnn8.2、Cuda12.2+Cudnn8.9版本下都无法进行训练，paddle版本2.5.1
报错代码如下：
OSError: (External) CUDNN error(9), CUDNN_STATUS_NOT_SUPPORTED.
[Hint: 'CUDNN_STATUS_NOT_SUPPORTED'. The functionality requested is not presently supported by cuDNN. ] (at ../paddle/phi/backends/gpu/cuda/cudnn_desc.h:167)

环境如下：
platform: Windows-10-10.0.22621-SP0
Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
Paddle compiled with cuda: True
NVCC: Build cuda_12.2.r12.2/compiler.33053471_0
cudnn: 8.9
GPUs used: 1
CUDA_VISIBLE_DEVICES: None
GPU: ['GPU 0: NVIDIA GeForce']
PaddleSeg: 2.8.0
PaddlePaddle: 2.5.1
OpenCV: 4.5.5

W0803 17:19:36.956816 12184 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.2, Runtime API Version: 11.2
W0803 17:19:36.956816 12184 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.

### 版本&环境信息 Version & Environment Information

Paddle version: 2.5.1
Paddle With CUDA: True

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: version 3.26.4
Libc version: N/A
Python version: 3.9.13

CUDA version: 12.2.128
Build cuda_12.2.r12.2/compiler.33053471_0
cuDNN version: */.*/.*/
Nvidia driver version: 536.67
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3090 Ti

<img width="551" alt="显卡环境" src="https://github.com/PaddlePaddle/Paddle/assets/93037403/bf154195-326c-425a-959a-f893ea2c4ac7">

**Comment by shiyutang** [comment]
你好，目前我们尝试paddle2.5可以在cuda10.2和cudnn7.6.5下正确训练paddleseg。建议搭配上述版本进行尝试。

**Comment by cole-dda** [comment]
cuda10.2 不支持3090显卡。 3090显卡已经快3年了，paddle2.3.2系列还不支持，在这些显卡上非常非常慢。这些基本问题不解决，让我们怎么用paddle？无奈之下还是pytorch了

**Comment by shiyutang** [comment]
这个问题的发生包括下列原因： bs太大、cudnn版本不适配、代码中存在index、网络层输出错误等。建议使用cpu看看能不能有更多报错信息，查看是否是代码的问题。

**Comment by Droliven** [comment]
> cuda10.2 不支持3090显卡。 3090显卡已经快3年了，paddle2.3.2系列还不支持，在这些显卡上非常非常慢。这些基本问题不解决，让我们怎么用paddle？无奈之下还是pytorch了

你可以用cuda 11.7, cudnn <= 8.5, paddle == 2.4.2.post117, paddleocr==2.7.0.2我试下来可以

**Comment by Droliven** [comment]
> > cuda10.2 不支持3090显卡。 3090显卡已经快3年了，paddle2.3.2系列还不支持，在这些显卡上非常非常慢。这些基本问题不解决，让我们怎么用paddle？无奈之下还是pytorch了
> 
> 你可以用cuda 11.7, cudnn <= 8.5, paddle == 2.4.2.post117, paddleocr==2.7.0.2我试下来可以

注意是 paddlepaddle_gpu==2.4.2.post117

**Comment by Droliven** [comment]
你的 cudnn 版本太高了，别的 issue 里有提到过
