### ISSUE TITLE
同样使用CPU推理，官方的paddle-2.5.0和paddle-gpu-2.5.0训练模型精度不一致

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#56026]
### 请提出你的问题 Please ask your question

在同样使用CPU推理的情况下，官方发包的paddle-2.5.0和paddle-gpu-2.5.0训练同样的模型，发现第六次迭代后精度不一致。
paddle-2.5.0：
![image](https://github.com/PaddlePaddle/Paddle/assets/87294783/ed9fb547-5283-4adf-a8ec-78599bbcc7c9)
![image](https://github.com/PaddlePaddle/Paddle/assets/87294783/cfbdfc03-004e-4c4a-9ac7-d3d050b0417c)
paddle-gpu-2.5.0:
![image](https://github.com/PaddlePaddle/Paddle/assets/87294783/2b23443d-d7b5-470d-ade1-dc0e0ce8eb25)
![image](https://github.com/PaddlePaddle/Paddle/assets/87294783/edd4b02d-f451-46d8-9201-39ba32fdffbf)
如上图，第六次迭代开始精度不对齐，已经确定了随机数种子，保证了每次训练loss相同。

**Comment by 2742195759** [comment]
可以描述清除一点吗，我看你发的图是训练不是推理。请问是训练精度不对是吗？然后分别是CPU还是GPU训练的？

**Comment by zepingWww** [comment]
> 可以描述清除一点吗，我看你发的图是训练不是推理。请问是训练精度不对是吗？然后分别是CPU还是GPU训练的？

对的，是训练精度不同，就是分别用官方发布的paddle-2.5.0和paddle-gpu-2.5.0，都是`paddle.set_device('cpu')`使用CPU训练，训练相同的模型，第六次迭代后精度不对。

**Comment by 2742195759** [comment]
那应该是有某个Op在CPU版本下和GPU版本下存在diff了。我这边可以提供思路，您如果可以定位到Op，可以联系我然后我推动修复。主要的思路就是定位到第一个出现diff的位置：
1. 使用 set_printoptions 设置比较大的打印精度
2. 二分模型代码，看下第一个出现diff的位置在哪里
3. 如果是反向出现了精度diff，那么可以打印所有的weight梯度，查看他们的diff。

**Comment by zepingWww** [comment]
> 那应该是有某个Op在CPU版本下和GPU版本下存在diff了。我这边可以提供思路，您如果可以定位到Op，可以联系我然后我推动修复。主要的思路就是定位到第一个出现diff的位置：
> 
> 1. 使用 set_printoptions 设置比较大的打印精度
> 2. 二分模型代码，看下第一个出现diff的位置在哪里
> 3. 如果是反向出现了精度diff，那么可以打印所有的weight梯度，查看他们的diff。

好的，等我有空了按照上面方法定位一下。但是有一个问题，如果有算子有问题，为什么前五次的迭代是一致的，到第六次才出现diff？

**Comment by 2742195759** [comment]
他们不一定是一致的，这就是我为什么说要设置 set_printoptions 。可能小数点后很多位本来就有问题。随着迭代的次数，差别逐渐放大了。

**Comment by 2742195759** [comment]
那我先关闭这个卡片了哈，如果定位了Op可以随时在打开~
