### ISSUE TITLE
编译PaddlePaddle源码报错

### ISSUE THREAD

**Issue by zhanghuihuichen** [PaddlePaddle/Paddle#56027]
### 问题描述 Issue Description

在麒麟v10下安装python3.7（默认的pyhton3.8未卸载），编译paddlePaddle源码，在cmake的时候出现以下错误
![ec187829589fec044f60dec2c8aec2f](https://github.com/PaddlePaddle/Paddle/assets/56913460/84cc437e-ccb9-477e-a5d1-27eea68b21fc)
尝试在cmake中显示配置pyhton的路径，不能解决这个问题。

### 版本&环境信息 Version & Environment Information

paddle Version:2.4.1
Python3.7.5
麒麟V10
昆仑XPU R200
飞腾 D2000/8

**Comment by 2742195759** [comment]
是不是因为没有安装 wheel ：
可以尝试下：
```
pip install wheel
```

**Comment by 2742195759** [comment]
同学有问题可以继续打开，我这边先关闭issue了哈。
