### ISSUE TITLE
图像分类使用vgg模型如何优化参数，降低测试集上分类错误率。

### ISSUE THREAD

**Issue by Ihuzb** [PaddlePaddle/Paddle#5604]
按照官网提供的图像分类代码，使用其中的vgg模型进行训练，训练步骤200pass，训练数据10类共7000张，测试数据10类共2000张。
Pass 136, Batch 0, Cost 0.024843, {'classification_error_evaluator': 0.015625}
......................................................................
Test with Pass 136, {'classification_error_evaluator': 0.1459999978542328}
Pass 137, Batch 0, Cost 0.015981, {'classification_error_evaluator': 0.0078125}
......................................................................
Test with Pass 137, {'classification_error_evaluator': 0.13449999690055847}
从第75pass开始测试集上分类错误率一直保持在0.12~0.14，请问如何优化参数才能降低测试集上分类错误率。
修改过的参数：
momentum_optimizer = paddle.optimizer.Momentum(
momentum=0.9,
regularization=paddle.optimizer.L2Regularization(rate=0.0002 * 128),
learning_rate=0.1 / 128.0,
learning_rate_decay_a=0.1,
learning_rate_decay_b=7000 * 100, #这个7000按照我的训练集的总数设置过，其他的没有再设置过
learning_rate_schedule='discexp')

**Comment by yeyupiaoling** [comment]
已经达到瓶颈了吧,为啥不考虑使用resnet

**Comment by chengduoZH** [comment]
Close due to low activity, please feel free to reopen it.
