### ISSUE TITLE
CustomDevice在累计梯度时语义与cuda没有对齐，导致sharding功能精度错误

### ISSUE THREAD

**Issue by zhurou603** [PaddlePaddle/Paddle#56049]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/32234672/25dac39f-41fb-4038-968e-01b27ad86e99)
![image](https://github.com/PaddlePaddle/Paddle/assets/32234672/e75c470d-8b9b-4109-b224-e9089dc24b54)
目前在accumulation_node.cc的语义下，custom_device的梯度累加结果并非inplace的，而是在add_ad_func中分配了一块新的显存，并将*tensor做了一次赋值语义，而else分支内cuda的语义则是inplace语义【t + tensor -> tensor】。
造成的结果是在sharding功能中对于grad地址的绑定失效，造成grad全为0，模型无法正常梯度下降。

**Comment by ronny1996** [comment]
感谢反馈，该pr可能修复这个问题，https://github.com/PaddlePaddle/Paddle/pull/56052
