### ISSUE TITLE
use_global_stats 和 track_running_stats

### ISSUE THREAD

**Issue by Wang0203** [PaddlePaddle/Paddle#56046]
### 请提出你的问题 Please ask your question

在Batch Norm中，torch是默认开启track_running_stats的，而paddle中默认是None，我需要开启吗？

**Comment by Wang0203** [comment]
[False 是无效的？](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/BatchNorm2D_cn.html#batchnorm2d:~:text=%E7%9B%AE%E5%89%8D%E8%AE%AD%E7%BB%83%E6%97%B6%E8%AE%BE%E7%BD%AE%20track_running_stats%20%E4%B8%BA%20False%20%E6%98%AF%E6%97%A0%E6%95%88%E7%9A%84%EF%BC%8C%E5%AE%9E%E9%99%85%E8%BF%98%E6%98%AF%E4%BC%9A%E6%8C%89%E7%85%A7%20True%20%E7%9A%84%E6%96%B9%E6%A1%88%E4%BF%9D%E5%AD%98%E5%85%A8%E5%B1%80%E5%9D%87%E5%80%BC%E5%92%8C%E6%96%B9%E5%B7%AE%E3%80%82%E4%B9%8B%E5%90%8E%E7%9A%84%E7%89%88%E6%9C%AC%E4%BC%9A%E4%BF%AE%E5%A4%8D%E6%AD%A4%E9%97%AE%E9%A2%98%E3%80%82)

**Comment by 2742195759** [comment]
是的，目前在训练时开启是无效的，后续会修复这个问题：
![image](https://github.com/PaddlePaddle/Paddle/assets/16025309/8fe96279-eb78-4abf-9166-a10a726c5c55)

**Comment by Wang0203** [comment]
在训练时：None-->minibatch;  False/True-->全局？
在测试时：None/True--> 全局; False-->minibatch?
是这个意思吗，有点迷了，麻烦您确认一下

**Comment by Wang0203** [comment]
还有上面的问题，torch是默认开启track_running_stats的，而paddle中默认是None，我需要设置为True吗？

**Comment by 2742195759** [comment]
使用默认值即可。
训练时，因为有问题，永远都是全局的
预测时，None -> 全局、True -> 全局、 False -> MiniBatch

**Comment by 2742195759** [comment]
那我关闭这个issue了哈~
