### ISSUE TITLE
访问内部http服务

### ISSUE THREAD

**Issue by 950601** [PaddlePaddle/Paddle#56060]
### 请提出你的问题 Please ask your question

我部署了sd-webui， 在本地启动了一个http服务，地址为127.0.0.1:3000这样的形式，请问我怎么打开它？

**Comment by 950601** [comment]
使用的是 ai studio 平台

**Comment by zyfncg** [comment]
我理解像这样的http服务一般是用浏览器访问ip地址+端口吧，ai studio 支持ip和端口的暴露吗？

**Comment by 950601** [comment]
就是这个意思，我在ai studio启动的http服务应该如何访问？你要不问一下相关同学 支不支持 公有链接 或者 内嵌浏览器？

**Comment by zyfncg** [comment]
这个问题已反馈到ai studio的相关同学，那边应该在跟进了

**Comment by 950601** [comment]
好的，希望能尽快反馈

**Comment by lilith-zy** [comment]
> 好的，希望能尽快反馈

您好，AI Studio notebook暂不支持启动新本地端口服务供外面访问。
