### ISSUE TITLE
how to use multi_binary_label_cross_entropy_cost?

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#5607]
multi_binary_label_cross_entropy_cost是否有使用示例？
我遇到了和paddle v2 api, how to use multi_binary_label_cross_entropy_cost? #2323类似的问题，但是没有人解答那个答案。当label为多个Id的时候，用
 lbl = paddle.layer.data("label", paddle.data_type.integer_value_sequence(class_num)) 
的形式输入，结果报错。
错误如下：
F1113 20:42:26.065004 46806 Vector.cpp:96] Check failed: id < width (22415 vs. 590) F1113 20:42:26.073673 46798 Vector.cpp:96] Check failed: id < width (2096 vs. 590) F1113 20:42:26.075407 46802 Vector.cpp:96] Check failed: id < width (9976 vs. 590) 
*** Check failure stack trace: ***
    @     0x7f24178fe5ed  google::LogMessage::Fail()
    @     0x7f241790209c  google::LogMessage::SendToLog()
    @     0x7f2417721f65  paddle::VectorT<>::toOneHotSparseMatrix()
    @     0x7f24175e94f8  paddle::MultiBinaryLabelCrossEntropy::forwardImp()
    @     0x7f24179035ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2417721f65  paddle::VectorT<>::toOneHotSparseMatrix()
    @     0x7f24178fe5ed  google::LogMessage::Fail()
    @     0x7f241790209c  google::LogMessage::SendToLog()
    @     0x7f24178fe0e3  google::LogMessage::Flush()
    @     0x7f24178fe0e3  google::LogMessage::Flush()
    @     0x7f24179035ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2417721f65  paddle::VectorT<>::toOneHotSparseMatrix()
    @     0x7f24175e8df5  paddle::CostLayer::forward()
    @     0x7f24179035ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f24175e94f8  paddle::MultiBinaryLabelCrossEntropy::forwardImp()
    @     0x7f24175e8df5  paddle::CostLayer::forward()
    @     0x7f24175e94f8  paddle::MultiBinaryLabelCrossEntropy::forwardImp()
    @     0x7f24175e8df5  paddle::CostLayer::forward()
    @     0x7f2417623269  paddle::NeuralNetwork::forward()
    @     0x7f241762cee4  paddle::TrainerThread::forward()
    @     0x7f2417721f65  paddle::VectorT<>::toOneHotSparseMatrix()
    @     0x7f24175e94f8  paddle::MultiBinaryLabelCrossEntropy::forwardImp()
    @     0x7f24175e8df5  paddle::CostLayer::forward()
    @     0x7f2417623269  paddle::NeuralNetwork::forward()
    @     0x7f2417623269  paddle::NeuralNetwork::forward()
    @     0x7f241762cee4  paddle::TrainerThread::forward()
    @     0x7f241762e165  paddle::TrainerThread::computeThread()
    @     0x7f241762e165  paddle::TrainerThread::computeThread()
    @     0x7f248c6698a0  execute_native_thread_routine
    @     0x7f241762cee4  paddle::TrainerThread::forward()
    @     0x7f241762e165  paddle::TrainerThread::computeThread()
    @     0x7f248c6698a0  execute_native_thread_routine
    @     0x7f2417623269  paddle::NeuralNetwork::forward()
    @     0x7f241762cee4  paddle::TrainerThread::forward()

**Comment by pkuyym** [comment]
从错误上面看，应该是最后一层的参数shape没办法对应上，需要确定类别数以及输入到multi_binary_label_cross_entropy_cost的预测的数据纬度

**Comment by Yancey1989** [comment]
由于这个issue很长时间没有更新，先关闭这个issue了，如果依然有问题还请随时打开它。
