### ISSUE TITLE
tensor推理报错：Parameter check failed

### ISSUE THREAD

**Issue by kamiLight** [PaddlePaddle/Paddle#56091]
### bug描述 Describe the Bug

paddle: 2.4
cuda: 11.1
cudnn: 8.1
tensorrt: 7.2.1

使用paddle + c++部署 + tensorrt推理时报错：
Parameter check failed at: engine.cpp::setOptimizationProfileInternal::1075, condition: profileIndex >= 0 && profileIndex < mEngine.getNbOptimizationProfiles()

**Comment by zyfncg** [comment]
有可复现的代码和运行脚本吗？
