### ISSUE TITLE
paddle报这个错误： save gpu log failed，但是paddle.utils.run_check()在多gpu测试无问题

### ISSUE THREAD

**Issue by tuobay** [PaddlePaddle/Paddle#56095]
请问一下这个exception是啥吗，可以对应的去修改我的代码吗

https://github.com/PaddlePaddle/Paddle/blob/0d920178d318d8bcb6349e6e6a82e91397b3b647/python/paddle/distributed/launch/controllers/watcher.py#L95

**Comment by tuobay** [comment]
第一次多卡训练成功运行，但是第二次报这个错误，是否是package不兼容导致？部分log如下，其中cuDNN的警告第一次训练就有，并没有问题

[2023/08/08 20:33:26] ppocr INFO: train dataloader has 92 iters
[2023/08/08 20:33:26] ppocr INFO: valid dataloader has 42 iters
[2023/08/08 20:33:27] ppocr INFO: load pretrain successful from ./pretrain_models/ch_PP-OCRv3_rec_train/best_accuracy
[2023/08/08 20:33:27] ppocr INFO: During the training process, after the 0th iteration, an evaluation is run every 2000 iterations


LAUNCH WARNING 2023-08-08 20:34:19,551 save gpu log failed
LAUNCH WARNING 2023-08-08 20:34:52,981 save gpu log failed
LAUNCH WARNING 2023-08-08 20:35:26,398 save gpu log failed
LAUNCH WARNING 2023-08-08 20:35:59,897 save gpu log failed
W0808 20:36:32.951223 14459 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.0, which may cause serious incompatible bug. Please recompile or rein
stall Paddle with compatible CUDNN version.

**Comment by zoooo0820** [comment]
你好，看起来这是一个warning，会导致训练中断吗

**Comment by tuobay** [comment]
是的，出现这个警告接下来就会报错

<img width="728" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16618221/614f2e25-9312-44c6-be8d-949b4a6932e6">

**Comment by tuobay** [comment]
在paddle的代码增加了一些print：

<img width="434" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16618221/3626467b-8cb0-4558-af80-6e0fc8b6d6d5">

看起来错误是调nvidia-smi超时

<img width="727" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16618221/21fe9c9a-f3ec-4a46-97b2-dbf9b9d08cde">

底层原因ppocr并没有爆出来

**Comment by tuobay** [comment]
找到原因了，还是batchsize设置太大，但是ppocr并没有爆出这个原因

**Comment by zoooo0820** [comment]
嗯嗯好的
