### ISSUE TITLE
算子GPU性能优化

### ISSUE THREAD

**Issue by zhangting2020** [PaddlePaddle/Paddle#56119]
## 问题描述

本任务为飞桨框架优化一系列算子的GPU计算性能，以提升模型训练效率。任务要求如下：
- 理解并分析现有算子的计算流程和性能瓶颈
- 设计优化方案并实现
- 使用[op-benchmark](https://github.com/PaddlePaddle/benchmark/tree/master/api)工具进行算子性能的测试评估，比较优化前后的算子性能

## 注意事项
- 提交流程：请参考[算子性能优化&提交流程](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/op_optimization/op_optimization_contributing_guides_cn.html)，开发请参考
- [RFC](https://github.com/PaddlePaddle/community)要求：可以不提交﻿。但仍然建议参考链接中的算子优化文档去设计方案，在开发完成后自愿选择提交。
- 使用[op-benchmark](https://github.com/PaddlePaddle/benchmark)测试算子前、反向算子性能，前、反向算子的优化PR可以分开提交
- 认领规则：直接在 issue 下回复认领的任务 ID
- 提交PR前请参照[官网](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/code_contributing_path_cn.html)安装pre-commit，检查代码格式。否则CI可能无法通过。
- PR 通过 CI 后，可以评论里或者 review request @zhangting2020 ，研发会进行审核
- 欢迎联系花花加入社区，和我们一起快乐开源！
<img width="200" alt="image" src="https://user-images.githubusercontent.com/39876205/213131273-361d2bb8-ea48-4f62-9603-0b0401f50337.png">

任务序号 | 算子 | 认领人 | 提交PR
-- | -- | -- | --
1 | argmax和argmin | @AndSonder   |  
2 | argsort |  @GreatV  |  
3 | cumsum |  @enkilee  |  
4 | interp_trilinear |  @GreatV  |  
5 | max_pool2d | @sanbuphy   |  
6 | normalize | @Difers   |  
7 | pad2d |  @TanWei  |  
8 | pad3d |  @jinyouzhi  |  
9 | affine_grid | @yangguohao   |  
10 | avg_pool2d | @chenhao-stick-to  |

**Comment by sanbuphy** [comment]
认领max_pool2d

**Comment by AndSonder** [comment]
| 序号 | 算子名称 | 认领人 | PR |
| :--- | :---: | :---: | :---: |
| 1 | argmax和argmin | @AndSonder  |  |

**Comment by GreatV** [comment]
任务序号 | 算子 | 认领人 | 提交PR
-- | -- | -- | --
2  |  argsort | @GreatV |
4 | interp_trilinear | @GreatV |

**Comment by Difers** [comment]
<html>
<body>


序号 | 算子名称 | 认领人 | PR
-- | -- | -- | --
6 | normalize | @Difers  | 
</body>
</html>

**Comment by longranger2** [comment]
@enkilee 认领任务3

**Comment by TanWei** [comment]
认领任务7: pad2d

**Comment by luotao1** [comment]
@AndSonder 任务1可参考：
- https://github.com/PaddlePaddle/Paddle/pull/46655

**Comment by chenhao-stick-to** [comment]
认领任务10:avg_pool2d

**Comment by yangguohao** [comment]
认领任务9：affine_grid

**Comment by jinyouzhi** [comment]
认领8
