### ISSUE TITLE
Row Convolution Operator.

### ISSUE THREAD

**Issue by sidgoyal78** [PaddlePaddle/Paddle#5612]
- [RowConvLayer.cpp]( https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/RowConvLayer.cpp)
- Introduced in DeepSpeech2 : http://www.cs.cmu.edu/~dyogatam/papers/wang+etal.iclrworkshop2016.pdf

**Comment by qingqing01** [comment]
@sidgoyal78 The raw implementation of the layers is here:

CPU: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/function/RowConvOp.cpp
GPU: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/function/RowConvOpGpu.cu

Thank you! :)
