### ISSUE TITLE
有朋友编过mac arm m1 或者m2 的库吗 求分享

### ISSUE THREAD

**Issue by kwdchol** [PaddlePaddle/Paddle#56177]
### 问题描述 Please describe your issue

我编译了paddle和 paddleocr/deploy/cpp_infer
在paddleocr/deploy/cpp_infer/src/this->predictor_->Run(); 函数中报错 
我大致看了一下
predictor_ 在 paddleocr/deploy/cpp_infer//include/ocr_rec.h 定义  std::shared_ptr<paddle_infer::Predictor> predictor_; 共享指针
paddle_infer::Predictor 是 Paddle/fluid/paddle_inference_install_dir/paddle/include/paddle_inference_api.h:class PD_INFER_DECL Predictor 类
analysis_predictor.cc 中 bool Predictor::Run() { return predictor_->ZeroCopyRun(); }
paddle_api.h中 virtual bool ZeroCopyRun() { return false; } 最后返回是false 不太理解

**Comment by kwdchol** [comment]
用了 https://www.paddlepaddle.org.cn/inference/master/guides/install/download_lib.html#mac 里面提供的mac m1的 [paddle_inference]  发现也是同样的问题 那么这样到底是paddle _inference 不兼容 还是cpp_infer里的代码不兼容mac呢

**Comment by linjson** [comment]
m2上跑不动,推理的时候卡住了

**Comment by kwdchol** [comment]
> m2上跑不动，推理的时候卡住了

可以跑 但是速度不够快

**Comment by linjson** [comment]
@kwdchol 你是如何做到的?我直接用paddleocr也跑不了啊

**Comment by kwdchol** [comment]
@linjson  https://github.com/PaddlePaddle/Paddle/issues/56381 看这个
