### ISSUE TITLE
昇腾910，Python3.9,Cann6.3.rc1编译paddle

### ISSUE THREAD

**Issue by Sam-papa** [PaddlePaddle/Paddle#56197]
### 问题描述 Issue Description

想在昇腾910，Python3.9,Cann6.3.rc1（如果不适配也可以是支持的版本）编译paddle

### 版本&环境信息 Version & Environment Information

    PaddlePaddle版本：develop
    CPU（可选）：920
    GPU：昇腾910
    系统环境：ubuntu18.04
    Python版本: 3.9
    编译出错。

**Comment by KimYannn** [comment]
现在昇腾的代码已经迁移到了 https://github.com/PaddlePaddle/PaddleCustomDevice, 请参照文档进行尝试 后续沟通可将 issue 迁移到 对应得 repo
