### ISSUE TITLE
对不起我是初学者。线性回归这一章恳请各位帮忙

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#5619]
学习目标：尝试通过训练获取Y=AX+BX+CX这样的式子中的参数

首先我先定义了两个np_array
import os
import paddle.v2 as paddle
import numpy as np
with_gpu = os.getenv('WITH_GPU', '0') != '0'
def main():
    # init
    paddle.init(use_gpu=with_gpu, trainer_count=1)
    X = np.random.rand(1000,3)  
    //这里的Y是我给定的一个公式，其实就是为了生成一套训练的目标数据。未来用于对比。
    Y = 5* X[:,0]+7*X[:,1]+9*X[:,2]+11+0.01*np.random.rand(1000,1)
    
    readerx = paddle.reader.creator.np_array(X)
    readery = paddle.reader.creator.np_array(Y)

然后我就不太会写了。怎么应用paddlepaddle中的线性回归读取、训练呢？
我按例子里的写：
 y_predict = paddle.layer.fc(input=X, size=1, act=paddle.activation.Linear())
报错了。

错误信息：AssertionError

**Comment by kuke** [comment]
这里你其实只需要写一个data reader就可以了，你可以参考线性回归这个例子写[data reader](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/uci_housing.py#L89)，余下的就可以套用代码。

**Comment by sandycs** [comment]
感谢。折腾了一下午。搞出来了reader
我的数据是这样的：3维的输入（浮点型），1维输出（浮点型）

> （对比房价13维输入，1维输出）

train执行的时候出现这样的错误：

> 
> F1114 09:54:55.857656   684 Matrix.cpp:2770] Check failed: a_col == b_row (3996 vs. 3)
> *** Check failure stack trace: ***
>     @     0x7fb6f723d0ed  google::LogMessage::Fail()
>     @     0x7fb6f723f438  google::LogMessage::SendToLog()
>     @     0x7fb6f723cbfb  google::LogMessage::Flush()
>     @     0x7fb6f724030e  google::LogMessageFatal::~LogMessageFatal()
>     @     0x7fb6f7159f1f  paddle::CpuMatrix::mul()
>     @     0x7fb6f7166ea9  paddle::CpuMatrix::mul()
>     @     0x7fb6f6efb1ac  paddle::FullyConnectedLayer::forward()
>     @     0x7fb6f6fab7a9  paddle::NeuralNetwork::forward()
>     @     0x7fb6f720d2c0  GradientMachine::forwardBackward()
>     @     0x7fb6f6dbb424  _wrap_GradientMachine_forwardBackward
>     @           0x4cb45e  PyEval_EvalFrameEx
>     @           0x4c2765  PyEval_EvalCodeEx
>     @           0x4ca8d1  PyEval_EvalFrameEx
>     @           0x4c2765  PyEval_EvalCodeEx
>     @           0x4ca099  PyEval_EvalFrameEx
>     @           0x4c2765  PyEval_EvalCodeEx
>     @           0x4ca099  PyEval_EvalFrameEx
>     @           0x4c2765  PyEval_EvalCodeEx
>     @           0x4ca8d1  PyEval_EvalFrameEx
>     @           0x4c2765  PyEval_EvalCodeEx
>     @           0x4c2509  PyEval_EvalCode
>     @           0x4f1def  (unknown)
>     @           0x4ec652  PyRun_FileExFlags
>     @           0x4eae31  PyRun_SimpleFileExFlags
>     @           0x49e14a  Py_Main
>     @     0x7fb710f38830  __libc_start_main
>     @           0x49d9d9  _start
>     @              (nil)  (unknown)

**Comment by sandycs** [comment]
@kuke 帮忙再看看，谢谢了

**Comment by kuke** [comment]
@sandycs 根据报错应该是fc layer的参数或输入的维度不对，请检查一下。如果不能找到问题，可以在这里把相关代码贴出来

**Comment by sandycs** [comment]
@kuke 谢谢，代码如下：
我先初始化了一个nparray ：X，以及一个根据x计算出来的Y
然后把X和Y做了一个合并（因为我不太会写reader，只能合并成类似于HousingData的数据）

> global dataX 
> dataX = np.random.rand(1000,3) //生成1000组数据，每组3个数字。随机，float型
> global dataY 
> dataY = 5*dataX[:,0] + 7*dataX[:,1] + 9*dataX[:,2] + 11//一个固定公式，最后希望能通过训练反推该公式
> global dataFinal
> dataFinal = np.c_[dataX,dataY]

reader的语句是这么写的：

> def testdata():
>     def reader():
>         for i in xrange(len(dataX)):
>                 yield dataFinal[:-1],dataFinal[-1:]
>                 
>     return reader

接下来的语句和教程基本一样，除了把13改为3
>     x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(3))
>     y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())
>     y = paddle.layer.data(name='y', type=paddle.data_type.dense_vector(1))
>     cost = paddle.layer.square_error_cost(input=y_predict, label=y)
>     
>     parameters = paddle.parameters.create(cost)    
>     # create optimizer
>     optimizer = paddle.optimizer.Momentum(momentum=0)
>     trainer = paddle.trainer.SGD(
>         cost=cost, parameters=parameters, update_equation=optimizer)
>     feeding = {'x': 0, 'y': 1}

**这里提个小问题，feeding是什么意思，有点看不懂，为什么x是0，y是1**

然后是train语句，把reader.shuffle里的housingdata改为testdata()方法。
> # training
>     trainer.train(
>         reader=paddle.batch(
>             paddle.reader.shuffle(testdata(), buf_size=500),
>             batch_size=2),
>         feeding=feeding,
>         event_handler=event_handler,
>         num_passes=30)

**Comment by sandycs** [comment]
我发现自己少了一个“属性归一化”的步骤
不过由于生成的数据本身都是0-1之间的。所以是否这个步骤不一定要做？
我刚才测试了下加入属性归一的步骤
错误依旧

**Comment by sandycs** [comment]
@kuke 
对不起，我自己仔细研究了一下。已经搞定了
我有个问题请教一下：
这部分代码能否稍微详细的解释一下。我实在有点看不懂

> if isinstance(event, paddle.event.EndIteration):
>             if event.batch_id % 100 == 0:
>                 print "Pass %d, Batch %d, Cost %f" % (
>                     event.pass_id, event.batch_id, event.cost)
> 
>         if isinstance(event, paddle.event.EndPass):
>             if event.pass_id % 10 == 0:
>                 with open('params_pass_%d.tar' % event.pass_id, 'w') as f:
>                     trainer.save_parameter_to_tar(f)
>             result = trainer.test(
>                 reader=paddle.batch(uci_housing.test(), batch_size=2),
>                 feeding=feeding)
>             print "Test %d, Cost %f" % (event.pass_id, result.cost)

**Comment by kuke** [comment]
@sandycs 上面这段代码是为了输出训练日志。第一个```if``` 条件段落使得每经过100个batch的输出training cost；第二个```if```条件段落使得每个pass结束的时候进行test并输出test cost，同时每10个pass保存一次模型。

**Comment by sandycs** [comment]
@kuke 
其实就是这些东西让我疑惑
什么是batch，什么是pass
我从哪里可以学习到这些知识？

**Comment by 447zyg** [comment]
@sandycs （我也是初学的  我说下我的理解）pass有点一轮一轮的意思。  就比如你的
trainer.train(
    reader=paddle.batch(
        paddle.reader.shuffle(testdata(), buf_size=500),
        batch_size=2),
    feeding=feeding,
    event_handler=event_handler,
    num_passes=30)
里面  最后一个num_passes=30就是大概跑30个pass。

专业一点的解释就是


Pass 完成讲所有训练数据训练一次称作一个pass，一般会通过shuffle并多次训练防止拟合到局部最优解

batch   多个样本数据组成一个batch (或mini-batch)

也是提问别人告诉我的

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
