### ISSUE TITLE
海光dcu平台搭建部署paddle时make -j编译失败

### ISSUE THREAD

**Issue by hongtaossr** [PaddlePaddle/Paddle#56198]
### 请提出你的问题 Please ask your question

在海光dcu平台上部署paddle推理框架进行编译时，在40%左右卡住了，报错信息:error generating:/Paddle/build/paddlephi/kernels/CMakeFiles/phi gpu.dir/gpu/./phi_gpu_generated_edit_distance_kernel.cu.o

**Comment by hongtaossr** [comment]
[ 43%] Building CXX object paddle/phi/kernels/CMakeFiles/phi_cpu.dir/strings/unicode.cc.o
[ 43%] Building CXX object paddle/phi/kernels/CMakeFiles/phi_cpu.dir/transfer_layout_kernel.cc.o
[ 43%] Building CXX object paddle/phi/kernels/CMakeFiles/phi_cpu.dir/uniform_random_kernel.cc.o
[ 43%] Building CXX object paddle/phi/kernels/CMakeFiles/phi_cpu.dir/unsqueeze_grad_kernel.cc.o
[ 43%] Building CXX object paddle/phi/kernels/CMakeFiles/phi_cpu.dir/unsqueeze_kernel.cc.o
[ 43%] Linking CXX static library libphi_cpu.a
[ 43%] Built target phi_cpu

**Comment by KimYannn** [comment]
如果没有Nvidia 可以尝试 cmake 时候尝试 disable cuda
```bash
cd repo/
cmake -B build -GNinja -DWITH_GPU=OFF
cmake --build build -j $(nproc)
```

**Comment by hongtaossr** [comment]
你好，我的执行命令如下：
cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ROCM=ON \
         -DON_INFER=ON -DWITH_TESTING=OFF -DWITH_XBYAK=OFF
make -j$(nproc)
由于我的目的主要是进行在dcu上的C++推理，所以将CMakeList.txt中tensorrt相关的命令已经注释。请问应该如何修改

**Comment by yuguo-Jack** [comment]
可以参考：cmake .. -DPY_VERSION=${PYTHON_MAJOR_VER} -DPYTHON_INCLUDE_DIR=/usr/local/Python${PYTHON_MAJOR_VER}d/include/python${PYTHON_MAJOR_VER}/ -DPYTHON_LIBRARY=/usr/local/Python${PYTHON_MAJOR_VER}d/lib/libpython${PYTHON_MAJOR_VER}.so  -DPYTHON_EXECUTABLE=/usr/bin/python3 -DWITH_GPU=OFF -DWITH_ROCM=ON -DWITH_RCCL=ON -DWITH_NCCL=OFF -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -DWITH_TP_CACHE=ON -DROCM_PATH=${ROCM_PATH} -DWITH_MKLDNN=OFF -DON_INFER=ON

**Comment by yuguo-Jack** [comment]
可以参考：cmake .. -DPY_VERSION=${PYTHON_MAJOR_VER} -DPYTHON_INCLUDE_DIR=/usr/local/Python${PYTHON_MAJOR_VER}d/include/python${PYTHON_MAJOR_VER}/ -DPYTHON_LIBRARY=/usr/local/Python${PYTHON_MAJOR_VER}d/lib/libpython${PYTHON_MAJOR_VER}.so  -DPYTHON_EXECUTABLE=/usr/bin/python3 -DWITH_GPU=OFF -DWITH_ROCM=ON -DWITH_RCCL=ON -DWITH_NCCL=OFF -DWITH_TESTING=ON -DWITH_DISTRIBUTE=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_VERBOSE_MAKEFILE=OFF -DWITH_TP_CACHE=ON -DROCM_PATH=${ROCM_PATH} -DWITH_MKLDNN=OFF -DON_INFER=ON

**Comment by yuguo-Jack** [comment]
编译环境参考https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html
