### ISSUE TITLE
Recommendation Demo能否加上error rate评价指标

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#562]
<img width="1236" alt="2016-11-22 1 24 34" src="https://cloud.githubusercontent.com/assets/6861004/20518086/d453cb72-b0d8-11e6-9b7d-8497b9cf7c47.png">
如上图，demo在训练的时候只能看到train和test的cost，但是没有给出分类的error rate或者auc，这样感觉看起来不太直观，只知道cost的大小不太清楚具体的分类效果怎么样。

运行 evaluate.sh脚本，结果如下
Best pass is 00006,  error is 2.98329, which means predict get error as 0.863610155105
evaluating from pass output/pass-00006
这里的error 2.98329是指cost么？那math.sqrt(float(raw_input()))/2计算得到的0.863610155105的意义代表什么呢？

**Comment by reyoung** [comment]
因为本身这个问题就不是分类问题，所以没有error rate
