### ISSUE TITLE
GPU随机算子PRNG实现是否会统一？

### ISSUE THREAD

**Issue by Xiadalei** [PaddlePaddle/Paddle#56221]
### 请提出你的问题 Please ask your question

目前GPU上随机算子的prng存在一定的分歧，多数算子prng使用curand/hiprand，但是仍有一部分算子使用thrust::minstd_rand。如：
[truncated_gaussian_random](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/truncated_gaussian_random_kernel.cu#L105)无论使用全局种子与否，都使用thrust::minstd_rand，只不过全局种子时generator的increment用1占位。
[uniform](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/uniform_kernel.cu#L74)和[gaussian](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/gaussian_kernel.cu#L74)则是全局种子时使用curand/hiprand，而非全局种子时使用thrust::minstd_rand。
[dropout](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/dropout_impl_util.h#L35)则是无论全局种子与否，都使用curand/hiprand

那么问题是：
1. truncated_gaussian_random是否会和uniform/gaussian/dropout一样在使用全局种子时，使用curand/hiprand？
2. uniform/gaussian/truncated_gaussian_random会考虑在不使用全局种子时也使用curand/hiprand么（和dropout对齐）？

**Comment by haohongxiang** [comment]
@Xiadalei 已收到您的问题，我们的同学稍后会进行回复。
