### ISSUE TITLE
paddle  version 2.5.1   not support os maxos bigsur and linux centos 7

### ISSUE THREAD

**Issue by zxy1123** [PaddlePaddle/Paddle#56248]
### bug描述 Describe the Bug

when i use paddle on max os big sur, the version is 11 ，libpaddle.so dlopen can not find symbol
install paddle on centos 7 , libpaddle can not find libssl.1.1.os  ,there is only openssl 1.0.2 in centos 7. 
so can you help to  make paddle  compatible to old version os ，thanks

**Comment by zhengqiwen1997** [comment]
需要 openssl 升级到1.1.1，可以按照如下步骤：
1 wget -q https://cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.tar.gz
2 tar -zxvf cmake-3.18.0-Linux-x86_64.tar.gz
3 rm cmake-3.18.0-Linux-x86_64.tar.gz
4 export PATH=/cmake-3.18.0-Linux-x86_64/bin:$PATH（注意cmake路径）
