### ISSUE TITLE
PaddleServing模型转换生成配置字段异常

### ISSUE THREAD

**Issue by lycfight** [PaddlePaddle/Paddle#56288]
### bug描述 Describe the Bug

我正在参考PaddleDetection的[服务化样例](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/serving/python/README.md#python-serving%E9%A2%84%E6%B5%8B%E9%83%A8%E7%BD%B2)，
尝试服务化部署[版面分析模型](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/docs/models_list.md#1-%E7%89%88%E9%9D%A2%E5%88%86%E6%9E%90%E6%A8%A1%E5%9E%8B)，
这里使用的是[中文版面分析模型的推理模型](https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar)
由于按照[文档导入示例](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/serving/python/README.md#23-%E6%9C%8D%E5%8A%A1%E5%8C%96%E9%83%A8%E7%BD%B2%E6%A8%A1%E5%9E%8B%E5%AF%BC%E5%87%BA)，
没有找到该模型picodet_lcnet_x1_0_fgd_layout_cdla对应的.yml配置文件，
故参考[PaddleOCR服务化文档](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/deploy/pdserving/README_CN.md#%E6%A8%A1%E5%9E%8B%E8%BD%AC%E6%8D%A2)，
将中文版面分析模型的推理模型转化，
所用命令如下：
首先，下载CDLA数据集训练的中文版面分析模型的[推理模型](https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar)，
```
# 下载并解压中文版面分析模型
wget https://paddleocr.bj.bcebos.com/ppstructure/models/layout/picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar -O picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar && tar -xf picodet_lcnet_x1_0_fgd_layout_cdla_infer.tar
```
接下来，用安装的paddle_serving_client把下载的inference模型转换成易于server部署的模型格式，
```
# 转换中文版面分析模型
python3 -m paddle_serving_client.convert --dirname ./picodet_lcnet_x1_0_fgd_layout_cdla_infer/ \
                                         --model_filename ./picodet_lcnet_x1_0_fgd_layout_cdla_infer/model.pdmodel \
                                         --params_filename ./picodet_lcnet_x1_0_fgd_layout_cdla_infer/model.pdiparams \
                                         --serving_server ./picodet_lcnet_x1_0_fgd_layout_cdla_infer/serving_server \
                                         --serving_client ./picodet_lcnet_x1_0_fgd_layout_cdla_infer/serving_client 
```
模型转换完成后，会在模型文件夹picodet_lcnet_x1_0_fgd_layout_cdla_infer下多出serving_server 和serving_client 的文件夹，具备如下格式：
```
picodet_lcnet_x1_0_fgd_layout_cdla_infer
├── infer_cfg.yml
├── model.pdiparams
├── model.pdiparams.info
├── model.pdmodel
├── serving_client
│   ├── serving_client_conf.prototxt
│   └── serving_client_conf.stream.prototxt
└── serving_server
    ├── model.pdiparams
    ├── model.pdmodel
    ├── serving_server_conf.prototxt
    └── serving_server_conf.stream.prototxt
```
生成的serving_server_conf.prototxt规定了Paddle Serving服务模型的输入和输出，这里的内容如下：serving_server_conf.prototxt
```
feed_var {
  name: "image"
  alias_name: "image"
  is_lod_tensor: false
  feed_type: 1
  shape: 1
  shape: 3
  shape: 800
  shape: 608
}
fetch_var {
  name: "transpose_0.tmp_0"
  alias_name: "transpose_0.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 7600
  shape: 10
}
fetch_var {
  name: "transpose_1.tmp_0"
  alias_name: "transpose_1.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 7600
  shape: 32
}
fetch_var {
  name: "transpose_2.tmp_0"
  alias_name: "transpose_2.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 1900
  shape: 10
}
fetch_var {
  name: "transpose_3.tmp_0"
  alias_name: "transpose_3.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 1900
  shape: 32
}
fetch_var {
  name: "transpose_4.tmp_0"
  alias_name: "transpose_4.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 475
  shape: 10
}
fetch_var {
  name: "transpose_5.tmp_0"
  alias_name: "transpose_5.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 475
  shape: 32
}
fetch_var {
  name: "transpose_6.tmp_0"
  alias_name: "transpose_6.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 130
  shape: 10
}
fetch_var {
  name: "transpose_7.tmp_0"
  alias_name: "transpose_7.tmp_0"
  is_lod_tensor: false
  fetch_type: 1
  shape: 1
  shape: 130
  shape: 32
}
```
这里的输入输出和PaddleDetection这里说的
[目标检测模型的输入输出](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/EXPORT_MODEL.md#1%E5%AF%BC%E5%87%BA%E6%A8%A1%E8%BE%93%E5%85%A5%E8%BE%93%E5%87%BA%E8%AF%B4%E6%98%8E)
差别很大，
参考
[样例](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/deploy/serving/python/README.md#24-%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1%E7%AB%AF%E6%A8%A1%E5%9E%8B%E9%A2%84%E6%B5%8B%E6%9C%8D%E5%8A%A1)
替换模型路径为picodet_lcnet_x1_0_fgd_layout_cdla_infer，启动服务，服务报错跑不通，参考
[issue](https://github.com/PaddlePaddle/PaddleDetection/issues/8532)
对比推理代码和serving_server_conf.prototxt的模型输入输出字段，测试发现这里服务化模型输入feed_var是原图片经过resize()后的中间结果，而服务化模型输入fetch_var却是八个数组，这里服务的数据流和推理代码中的存在显著差别，似乎是将resize()后的几个预处理操作算到了模型处理中，而模型处理又少了将fetch_var转换的流程

**Comment by Caozhou1995** [comment]
感谢您的反馈，可以去PaddleDetection提相应的issue，帮助我们不断提升: https://github.com/PaddlePaddle/PaddleDetection

**Comment by lycfight** [comment]
> 感谢您的反馈，可以去PaddleDetection提相应的issue，帮助我们不断提升: https://github.com/PaddlePaddle/PaddleDetection

几周前在PaddleDetection提了，一直没有反馈，我已花了2周的成本去排查和定位问题，已经非常详细了，请务必帮我@一下和Paddle Serving和PaddleDetection服务部署相关的接口人，关注这个[bug](https://github.com/PaddlePaddle/PaddleDetection/issues/8538)

**Comment by Caozhou1995** [comment]
已反馈

**Comment by jerrywgz** [comment]
建议使用FastDeploy来实现服务化部署的能力，可以参考这里的文档 https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README_CN.md
建议使用这个基础镜像 registry.baidubce.com/paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.4-trt8.5-21.10

**Comment by lycfight** [comment]
> 建议使用FastDeploy来实现服务化部署的能力，可以参考这里的文档 https://github.com/PaddlePaddle/FastDeploy/blob/develop/examples/vision/detection/paddledetection/serving/README_CN.md 建议使用这个基础镜像 registry.baidubce.com/paddlepaddle/fastdeploy:1.0.7-gpu-cuda11.4-trt8.5-21.10

之前试过，中文版面分析推理有[问题](https://github.com/PaddlePaddle/FastDeploy/issues/2109)，推理结果是错的，和PaddleDetection的样例推理的不一样
