### ISSUE TITLE
ValueError: (InvalidArgument) Custom operator's 0-th output is not initialized. Please check your implementation again. If you are using inplace optional output, then you must use `paddle::Optional` to decorate this output (at ../paddle/fluid/pybind/eager_functions.cc:662)

### ISSUE THREAD

**Issue by Wang0203** [PaddlePaddle/Paddle#56306]
### 请提出你的问题 Please ask your question

<img width="997" alt="936f95878dcd182da4e963104dc9bb45" src="https://github.com/PaddlePaddle/Paddle/assets/65695245/d54a69f5-c78e-4629-9e0a-72814143f03e">

请问这是什么问题，算子有问题吗？

**Comment by Caozhou1995** [comment]
看报错提示是outs没有初始化，麻烦提供一下具体的paddle版本信息，以及调用该算子的组网部分代码

**Comment by Wang0203** [comment]
[paddle 3d](https://github.com/PaddlePaddle/Paddle3D/blob/develop/paddle3d/ops/iou3d_nms/iou3d_cpu.cpp)
![image](https://github.com/PaddlePaddle/Paddle/assets/65695245/8d8eaee0-5396-4a93-a151-0360f2e14988)

**Comment by Caozhou1995** [comment]
这种OP问题可以去Paddle3D repo中提issue：https://github.com/PaddlePaddle/Paddle3D/issues，那边会有相关专业同学进行解答
