### ISSUE TITLE
missing bias for conv_op

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#5630]
This might be one of the reasons that the test_recognize_digits_conv.py can not train as well as book/02.recognize_digits/train.py

**Comment by emailweixu** [comment]
Sorry, misread the code. There is bias.

**Comment by dzhwinter** [comment]
Yes, we have the bias parameter in the layers, we split the `conv_op` and `add_bias`  as two operators for the op-reuse and future optimization.
