### ISSUE TITLE
improve the initializer interface for layers

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#5632]
The parameters in layers need a better flexible and user-friendly initializer interface. Currently, most of our layers have the fixed init method, such as `conv2d` use the `gaussian` initializer [conv2d](https://github.com/PaddlePaddle/Paddle/blob/c3a61349e4fd0dd98fe8fbe80d2553dffe5626a0/python/paddle/v2/fluid/layers.py#L672).  
We need to rewrite that part.

**Comment by jacquesqiao** [comment]
this initializer for conv2d is designed in purpose, and it's a good initialization method

**Comment by qingqing01** [comment]
For the convolution operators, maybe we need to define a `MSRAInit` and set it by default.  The `MSRAInit` in caffe2 : https://github.com/caffe2/caffe2/blob/master/caffe2/operators/filler_op.h#L462

**Comment by abhinavarora** [comment]
I agree with @qingqing01. I have opened an issue for this https://github.com/PaddlePaddle/Paddle/issues/5752.

**Comment by dzhwinter** [comment]
I think we need to make the initialized method configurable. Even though the `MSRAInit` is perfect, when a user wants to do some init trick, our design will block their use cases.

**Comment by dzhwinter** [comment]
For example, this paper and its variants. https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&ved=0ahUKEwjyxfznscbXAhVQ1mMKHdgDBdwQFggnMAA&url=https%3A%2F%2Farxiv.org%2Fabs%2F1706.02677&usg=AOvVaw2FEBNWmB_5ah6W-73eD2yA

In a word, we need to give the right to users.

**Comment by abhinavarora** [comment]
@dzhwinter, I am working on a PR to add that flexibility. Will send you all review soon.

**Comment by abhinavarora** [comment]
Tasks:
 - [ ] Design pattern for letting users pass initializers
 - [ ] Ensure that all parameters created through layer_helper have initializers, if not then create a default initializer based on dtype
 - [ ] Fix FC layer
 - [ ] Fix Sequence_conv layer
 - [ ] Fix conv2d layer
