### ISSUE TITLE
是否有提供支持gpu+jupyter+paddle的docker镜像

### ISSUE THREAD

**Issue by 983183947** [PaddlePaddle/Paddle#56331]
请问是否有提供支持gpu+jupyter+paddle的docker镜像

**Comment by andyjiang1116** [comment]
官方镜像选择gpu版本的即可，里面应该有jupyter ，安装文档参考 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/docker/linux-docker.html
