### ISSUE TITLE
paddle inference进行模型推理时，推理时间周期性波动，请问是怎么回事？

### ISSUE THREAD

**Issue by gitleej** [PaddlePaddle/Paddle#56343]
### 请提出你的问题 Please ask your question

paddle inference进行模型推理时，推理时间周期性波动，请问是怎么回事？
![image-20230816143034241](https://github.com/PaddlePaddle/Paddle/assets/31566147/47c0bacf-68f4-41a3-87cd-7ee4ba15bb9d)
推理代码：
```C++
ErrorCode PaddleInferenceEngine::Infer(const std::vector<DataBlob>& inputs,
                                       std::vector<DataBlob>* outputs) {
    LOG(INFO) << "Start Infer.";

    ErrorCode ret = ErrorCode::SUCCESS;
    if (inputs.size() == 0) {
        ret = ErrorCode::E_INFER_EMPTY_INPUT;
        LOG(ERROR) << Error::getErrorMsg(ret);
        return ret;
    }
    auto input_names = this->m_predictor->GetInputNames();
    for (int i = 0; i < inputs.size(); i++) {
        auto in_tensor = this->m_predictor->GetInputHandle(input_names[i]);
        in_tensor->Reshape(inputs[i].shape);
        if (inputs[i].dtype == FLOAT32) {
            float* im_tensor_data;
            im_tensor_data = (float*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT64) {
            int64_t* im_tensor_data;
            im_tensor_data = (int64_t*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT32) {
            int* im_tensor_data;
            im_tensor_data = (int*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT8) {
            uint8_t* im_tensor_data;
            im_tensor_data = (uint8_t*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else {
            ret = ErrorCode::E_INFER_UNEXPECTED_INPUT_DATA_TYPE;
            LOG(ERROR) << Error::getErrorMsg(ret, "Data type: %d",
                                             inputs[i].dtype);
            return ret;
        }
    }
    // predict
    this->m_predictor->Run();

    // get output
    auto output_names = this->m_predictor->GetOutputNames();
    for (const auto output_name : output_names) {
        auto output_tensor = this->m_predictor->GetOutputHandle(output_name);
        auto output_tensor_shape = output_tensor->shape();
        DataBlob output;
        output.name = output_name;
        output.shape.assign(output_tensor_shape.begin(),
                            output_tensor_shape.end());
        output.dtype = paddle_infer::DataType(output_tensor->type());
        output.lod = output_tensor->lod();
        int size = 1;
        for (const auto& i : output_tensor_shape) {
            size *= i;
        }
        if (output.dtype == 0) {
            output.data.resize(size * sizeof(float));
            output_tensor->CopyToCpu(
                reinterpret_cast<float*>(output.data.data()));
        } else if (output.dtype == 1) {
            output.data.resize(size * sizeof(int64_t));
            output_tensor->CopyToCpu(
                reinterpret_cast<int64_t*>(output.data.data()));
        } else if (output.dtype == 2) {
            output.data.resize(size * sizeof(int));
            output_tensor->CopyToCpu(
                reinterpret_cast<int*>(output.data.data()));
        } else if (output.dtype == 3) {
            output.data.resize(size * sizeof(uint8_t));
            output_tensor->CopyToCpu(
                reinterpret_cast<uint8_t*>(output.data.data()));
        }
        outputs->push_back(std::move(output));
    }
    
    return ret;
}
```

**Comment by andyjiang1116** [comment]
你好，是哪个模型呢？是测试的同一个数据吗？

**Comment by gitleej** [comment]
> 你好，是哪个模型呢？是测试的同一个数据吗？

模型是pp-liteseg，数据尺寸都是一样的，但不是同一个数据，我在Infer函数里继续监控了一下。
![image-20230816150259954](https://github.com/PaddlePaddle/Paddle/assets/31566147/3c67ac28-deda-4970-9c51-ebbb60a9f345)
```C++
ErrorCode PaddleInferenceEngine::Infer(const std::vector<DataBlob>& inputs,
                                       std::vector<DataBlob>* outputs) {
    LOG(INFO) << "Start Infer.";

    ErrorCode ret = ErrorCode::SUCCESS;
    if (inputs.size() == 0) {
        ret = ErrorCode::E_INFER_EMPTY_INPUT;
        LOG(ERROR) << Error::getErrorMsg(ret);
        return ret;
    }
    
    auto inputStart = std::chrono::steady_clock::now();

    auto input_names = this->m_predictor->GetInputNames();
    for (int i = 0; i < inputs.size(); i++) {
        auto in_tensor = this->m_predictor->GetInputHandle(input_names[i]);
        in_tensor->Reshape(inputs[i].shape);
        if (inputs[i].dtype == FLOAT32) {
            float* im_tensor_data;
            im_tensor_data = (float*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT64) {
            int64_t* im_tensor_data;
            im_tensor_data = (int64_t*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT32) {
            int* im_tensor_data;
            im_tensor_data = (int*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else if (inputs[i].dtype == INT8) {
            uint8_t* im_tensor_data;
            im_tensor_data = (uint8_t*)(inputs[i].data.data());  // NOLINT
            in_tensor->CopyFromCpu(im_tensor_data);
        } else {
            ret = ErrorCode::E_INFER_UNEXPECTED_INPUT_DATA_TYPE;
            LOG(ERROR) << Error::getErrorMsg(ret, "Data type: %d",
                                             inputs[i].dtype);
            return ret;
        }
    }

    auto inputEnd = std::chrono::steady_clock::now();

    // predict
    auto predictStart = std::chrono::steady_clock::now();
    this->m_predictor->Run();
    auto predictEnd = std::chrono::steady_clock::now();

    // get output
    auto outputStart = std::chrono::steady_clock::now();

    auto output_names = this->m_predictor->GetOutputNames();
    for (const auto output_name : output_names) {
        auto output_tensor = this->m_predictor->GetOutputHandle(output_name);
        auto output_tensor_shape = output_tensor->shape();
        DataBlob output;
        output.name = output_name;
        output.shape.assign(output_tensor_shape.begin(),
                            output_tensor_shape.end());
        output.dtype = paddle_infer::DataType(output_tensor->type());
        output.lod = output_tensor->lod();
        int size = 1;
        for (const auto& i : output_tensor_shape) {
            size *= i;
        }
        if (output.dtype == 0) {
            output.data.resize(size * sizeof(float));
            output_tensor->CopyToCpu(
                reinterpret_cast<float*>(output.data.data()));
        } else if (output.dtype == 1) {
            output.data.resize(size * sizeof(int64_t));
            output_tensor->CopyToCpu(
                reinterpret_cast<int64_t*>(output.data.data()));
        } else if (output.dtype == 2) {
            output.data.resize(size * sizeof(int));
            output_tensor->CopyToCpu(
                reinterpret_cast<int*>(output.data.data()));
        } else if (output.dtype == 3) {
            output.data.resize(size * sizeof(uint8_t));
            output_tensor->CopyToCpu(
                reinterpret_cast<uint8_t*>(output.data.data()));
        }
        outputs->push_back(std::move(output));
    }
    auto outputEnd = std::chrono::steady_clock::now();

    double inputTime =
        std::chrono::duration<double, std::milli>(inputEnd - inputStart)
            .count();
    double predictTime =
        std::chrono::duration<double, std::milli>(predictEnd - predictStart)
            .count();
    double outputTime =
        std::chrono::duration<double, std::milli>(outputEnd - outputStart)
            .count();

    LOG(WARNING) << " inputTime: " << inputTime
                 << " predictTime: " << predictTime
                 << " outputTime: " << outputTime;
    
    return ret;
}
```

**Comment by gitleej** [comment]
> > 你好，是哪个模型呢？是测试的同一个数据吗？
> 
> 模型是pp-liteseg，数据尺寸都是一样的，但不是同一个数据，我在Infer函数里继续监控了一下。 ![image-20230816150259954](https://user-images.githubusercontent.com/31566147/260927329-3c67ac28-deda-4970-9c51-ebbb60a9f345.png)
> 
> ```c++
> ErrorCode PaddleInferenceEngine::Infer(const std::vector<DataBlob>& inputs,
>                                        std::vector<DataBlob>* outputs) {
>     LOG(INFO) << "Start Infer.";
> 
>     ErrorCode ret = ErrorCode::SUCCESS;
>     if (inputs.size() == 0) {
>         ret = ErrorCode::E_INFER_EMPTY_INPUT;
>         LOG(ERROR) << Error::getErrorMsg(ret);
>         return ret;
>     }
>     
>     auto inputStart = std::chrono::steady_clock::now();
> 
>     auto input_names = this->m_predictor->GetInputNames();
>     for (int i = 0; i < inputs.size(); i++) {
>         auto in_tensor = this->m_predictor->GetInputHandle(input_names[i]);
>         in_tensor->Reshape(inputs[i].shape);
>         if (inputs[i].dtype == FLOAT32) {
>             float* im_tensor_data;
>             im_tensor_data = (float*)(inputs[i].data.data());  // NOLINT
>             in_tensor->CopyFromCpu(im_tensor_data);
>         } else if (inputs[i].dtype == INT64) {
>             int64_t* im_tensor_data;
>             im_tensor_data = (int64_t*)(inputs[i].data.data());  // NOLINT
>             in_tensor->CopyFromCpu(im_tensor_data);
>         } else if (inputs[i].dtype == INT32) {
>             int* im_tensor_data;
>             im_tensor_data = (int*)(inputs[i].data.data());  // NOLINT
>             in_tensor->CopyFromCpu(im_tensor_data);
>         } else if (inputs[i].dtype == INT8) {
>             uint8_t* im_tensor_data;
>             im_tensor_data = (uint8_t*)(inputs[i].data.data());  // NOLINT
>             in_tensor->CopyFromCpu(im_tensor_data);
>         } else {
>             ret = ErrorCode::E_INFER_UNEXPECTED_INPUT_DATA_TYPE;
>             LOG(ERROR) << Error::getErrorMsg(ret, "Data type: %d",
>                                              inputs[i].dtype);
>             return ret;
>         }
>     }
> 
>     auto inputEnd = std::chrono::steady_clock::now();
> 
>     // predict
>     auto predictStart = std::chrono::steady_clock::now();
>     this->m_predictor->Run();
>     auto predictEnd = std::chrono::steady_clock::now();
> 
>     // get output
>     auto outputStart = std::chrono::steady_clock::now();
> 
>     auto output_names = this->m_predictor->GetOutputNames();
>     for (const auto output_name : output_names) {
>         auto output_tensor = this->m_predictor->GetOutputHandle(output_name);
>         auto output_tensor_shape = output_tensor->shape();
>         DataBlob output;
>         output.name = output_name;
>         output.shape.assign(output_tensor_shape.begin(),
>                             output_tensor_shape.end());
>         output.dtype = paddle_infer::DataType(output_tensor->type());
>         output.lod = output_tensor->lod();
>         int size = 1;
>         for (const auto& i : output_tensor_shape) {
>             size *= i;
>         }
>         if (output.dtype == 0) {
>             output.data.resize(size * sizeof(float));
>             output_tensor->CopyToCpu(
>                 reinterpret_cast<float*>(output.data.data()));
>         } else if (output.dtype == 1) {
>             output.data.resize(size * sizeof(int64_t));
>             output_tensor->CopyToCpu(
>                 reinterpret_cast<int64_t*>(output.data.data()));
>         } else if (output.dtype == 2) {
>             output.data.resize(size * sizeof(int));
>             output_tensor->CopyToCpu(
>                 reinterpret_cast<int*>(output.data.data()));
>         } else if (output.dtype == 3) {
>             output.data.resize(size * sizeof(uint8_t));
>             output_tensor->CopyToCpu(
>                 reinterpret_cast<uint8_t*>(output.data.data()));
>         }
>         outputs->push_back(std::move(output));
>     }
>     auto outputEnd = std::chrono::steady_clock::now();
> 
>     double inputTime =
>         std::chrono::duration<double, std::milli>(inputEnd - inputStart)
>             .count();
>     double predictTime =
>         std::chrono::duration<double, std::milli>(predictEnd - predictStart)
>             .count();
>     double outputTime =
>         std::chrono::duration<double, std::milli>(outputEnd - outputStart)
>             .count();
> 
>     LOG(WARNING) << " inputTime: " << inputTime
>                  << " predictTime: " << predictTime
>                  << " outputTime: " << outputTime;
>     
>     return ret;
> }
> ```

我对同一个数据重复测试了2000多次，还是一样出现周期性波动。
![image-20230816151403360](https://github.com/PaddlePaddle/Paddle/assets/31566147/7a8ae050-3bdb-4c04-a8c6-0f2ec46e368e)

**Comment by andyjiang1116** [comment]
后台有其他进程占用吗？

**Comment by gitleej** [comment]
> 后台有其他进程占用吗？

指显卡还是CPU，后台没有其他程序了，只运行这个

**Comment by gitleej** [comment]
> > 后台有其他进程占用吗？
> 
> 指显卡还是CPU，后台没有其他程序了，只运行这个

paddle inference版本
GIT COMMIT ID: 0e92adceae06b6b7463f2dc7790ffb0601730009
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_ASCEND_CL: OFF
WITH_ASCEND_CXX11: OFF
WITH_IPU: OFF
CUDA version: 11.2
CUDNN version: v8.2
CXX compiler version: 19.29.30141.0
WITH_TENSORRT: ON
TensorRT version: v8.0.1.6

**Comment by andyjiang1116** [comment]
这个应该是机器问题

**Comment by gitleej** [comment]
> 这个应该是机器问题

换不同的机器测试也有这个问题

**Comment by gitleej** [comment]
有可能时Windows下TensorRT有问题，可以参考这几个链接
https://github.com/NVIDIA/TensorRT/issues/2107
https://github.com/NVIDIA/TensorRT/issues/2042
https://zhuanlan.zhihu.com/p/619947091

**Comment by laborer123** [comment]
> 有可能时Windows下TensorRT有问题，可以参考这几个链接 [NVIDIA/TensorRT#2107](https://github.com/NVIDIA/TensorRT/issues/2107) [NVIDIA/TensorRT#2042](https://github.com/NVIDIA/TensorRT/issues/2042) https://zhuanlan.zhihu.com/p/619947091

是不是没办法从代码上解决，我也查了好多都是改显卡设置之类的

**Comment by gitleej** [comment]
显卡驱动降到470版本可以稳定-------- 原始邮件 --------发件人： laborer-lab ***@***.***>日期： 2024年1月2日周二 15:49收件人： PaddlePaddle/Paddle ***@***.***>抄送： gitleej ***@***.***>, Author ***@***.***>主    题： Re: [PaddlePaddle/Paddle] paddle inference进行模型推理时，推理时间周期性波动，请问是怎么回事？ (Issue #56343)

有可能时Windows下TensorRT有问题，可以参考这几个链接 NVIDIA/TensorRT#2107 NVIDIA/TensorRT#2042 https://zhuanlan.zhihu.com/p/619947091

是不是没办法从代码上解决，我也查了好多都是改显卡设置之类的

**Comment by lix19937** [comment]
marked
