### ISSUE TITLE
Transformer 如何使用流水线并行

### ISSUE THREAD

**Issue by Nero1996** [PaddlePaddle/Paddle#56348]
### 请提出你的问题 Please ask your question

用paddle封装好的transoformer类组网如何使用流水行并行切分模型

**Comment by andyjiang1116** [comment]
可以参考文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/pipeline_parallel_cn.html

**Comment by Nero1996** [comment]
只有自己编写组网代码实现transoformer才能使用流水线并行吗？

**Comment by andyjiang1116** [comment]
也可以试试分组切分并行 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/group_sharded_parallel_cn.html

**Comment by Nero1996** [comment]
单卡放不下完整模型的情况下这种方式能降低多少显存？

**Comment by andyjiang1116** [comment]
具体可以按照文档试下
