### ISSUE TITLE
models 里面的代码在 PaddlePaddle BOOK 很多引入不了  例如：reader,resnet..

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5636]
import reader
import vgg
import resnet
import alexnet
import googlenet

PaddlePaddle BOOK  找不models的目录

**Comment by kuke** [comment]
@466821202 这是import的路径不对。你所import的几个module，都在models下面的image_classification目录下，在book中没有正确的路径指向，自然是无法import的。建议找找在python中如何import的资料

**Comment by 466821202** [comment]
好的 谢谢 这个我肯定是明白的  现在问题是models 目录在那里   搜索了book 里面的所有目录 没找见 好尴尬   望指导
