### ISSUE TITLE
paddle 2.4 动态图调用paddle.fluid.layers.sampling_id 有问题

### ISSUE THREAD

**Issue by fengchu2017** [PaddlePaddle/Paddle#56376]
### 请提出你的问题 Please ask your question

paddle 2.4 动态图调用paddle.fluid.layers.sampling_id 函数, gpu 利用率直接打满（显存未打满），卡着不动了。用paddle 2.3静态图调用正常，如果把这个操作调用numpy库，用cpu 计算也正常运行，但是速度很慢。

**Comment by shiyutang** [comment]
你好，请问能否给出代码示例

**Comment by shiyutang** [comment]
我们的fluid相关API在paddle2.0时已经标记退场，目前已经不再支持对fluid相关API的修改，建议使用非fluid的对应API。

**Comment by fengchu2017** [comment]
paddle.fluid.layers.sampling_id 这个函数有非fluid 版本的替代函数吗

**Comment by shiyutang** [comment]
目前这个API已经没有负责人，建议从API的功能和修改该API的代码用户着手，找到替代的API。

**Comment by shiyutang** [comment]
提问者计划尝试paddle.multinomial。
