### ISSUE TITLE
利用paddle.jit.save保存的模型还能继续训练吗？

### ISSUE THREAD

**Issue by wangyexiang** [PaddlePaddle/Paddle#56383]
### 请提出你的问题 Please ask your question

在查阅官网文档后，发现所有的恢复模型训练都是用：
```
#保存
params_dict = paddle.load('./checkpoint/mnist_epoch0.pdparams')
opt_dict = paddle.load('./checkpoint/mnist_epoch0.pdopt')

# 加载参数到模型
model.set_state_dict(params_dict)
opt.set_state_dict(opt_dict)
```
我的问题是，如果模型用的是`paddle.jit.save`保存的，然后我想继续训练，并且我不想用原来的优化器，而是新定义一个优化器来训练，这种能实现吗？

**Comment by shiyutang** [comment]
这个是基于静态图的训练，在QAT中会用到，可以参考下面的代码：https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/quant/quant_aware_with_infermodel.py

**Comment by wangyexiang** [comment]
没看懂您提供的答案，我在paddle.jit.load方法中([https://github.com/PaddlePaddle/Paddle/blob/1cea578edd29ba34b69ffe7fd18acfb2600a538b/python/paddle/jit/api.py#L1308C33-L1308C33](url))找到一个例子，代码如下：

```
import numpy as np
import paddle
import paddle.nn as nn
import paddle.optimizer as opt

BATCH_SIZE = 16
BATCH_NUM = 4
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10


# define a random dataset
class RandomDataset(paddle.io.Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype("float32")
        label = np.random.randint(0, CLASS_NUM - 1, (1,)).astype("int64")
        return image, label

    def __len__(self):
        return self.num_samples


class LinearNet(nn.Layer):
    def __init__(self):
        super().__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    @paddle.jit.to_static
    def forward(self, x):
        return self._linear(x)


def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        for batch_id, (image, label) in enumerate(loader()):
            out = layer(image)
            loss = loss_fn(out, label)
            loss.backward()
            opt.step()
            opt.clear_grad()
            print(
                "Epoch {} batch {}: loss = {}".format(
                    epoch_id, batch_id, np.mean(float(loss))
                )
            )


# 1. train & save model.

# create network
layer = LinearNet()
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())

# create data loader
dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
loader = paddle.io.DataLoader(
    dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True, num_workers=0
)

# train
train(layer, loader, loss_fn, adam)

# save
path = "example_model/linear"
paddle.jit.save(layer, path)

# 2. load model

# load
loaded_layer = paddle.jit.load(path)

# inference
loaded_layer.eval()
x = paddle.randn([1, IMAGE_SIZE], "float32")
pred = loaded_layer(x)
print(f"pred:{pred.numpy()}")

# fine-tune---------------->这里的方法是类似我所需要的，但是代码报错(见下面)
loaded_layer.train()
adam = opt.Adam(learning_rate=0.001, parameters=loaded_layer.parameters())
train(loaded_layer, loader, loss_fn, adam)
```
代码报错：
```
File "f:\*******\test.py", line 87, in <module>
    train(loaded_layer, loader, loss_fn, adam)
  File "f:\*******\test.py", line 43, in train
    loss.backward()
  File "D:\pyvenvs\py310\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
ValueError: (InvalidArgument) The x.size() and x_grad_names.size() should be equal. But received x.size() = 1, x_grad_names.size() = 0
  [Hint: Expected x.size() == x_grad_names.size(), but received x.size():1 != x_grad_names.size():0.] (at ..\paddle/fluid/eager/to_static/run_program_op_node.h:701)
```
请问应该怎么解决这个问题呢？多谢@shiyutang

**Comment by 0x45f** [comment]
> 没看懂您提供的答案，我在paddle.jit.load方法中([https://github.com/PaddlePaddle/Paddle/blob/1cea578edd29ba34b69ffe7fd18acfb2600a538b/python/paddle/jit/api.py#L1308C33-L1308C33](url))找到一个例子，代码如下：
> 
> ```
> import numpy as np
> import paddle
> import paddle.nn as nn
> import paddle.optimizer as opt
> 
> BATCH_SIZE = 16
> BATCH_NUM = 4
> EPOCH_NUM = 4
> 
> IMAGE_SIZE = 784
> CLASS_NUM = 10
> 
> 
> # define a random dataset
> class RandomDataset(paddle.io.Dataset):
>     def __init__(self, num_samples):
>         self.num_samples = num_samples
> 
>     def __getitem__(self, idx):
>         image = np.random.random([IMAGE_SIZE]).astype("float32")
>         label = np.random.randint(0, CLASS_NUM - 1, (1,)).astype("int64")
>         return image, label
> 
>     def __len__(self):
>         return self.num_samples
> 
> 
> class LinearNet(nn.Layer):
>     def __init__(self):
>         super().__init__()
>         self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)
> 
>     @paddle.jit.to_static
>     def forward(self, x):
>         return self._linear(x)
> 
> 
> def train(layer, loader, loss_fn, opt):
>     for epoch_id in range(EPOCH_NUM):
>         for batch_id, (image, label) in enumerate(loader()):
>             out = layer(image)
>             loss = loss_fn(out, label)
>             loss.backward()
>             opt.step()
>             opt.clear_grad()
>             print(
>                 "Epoch {} batch {}: loss = {}".format(
>                     epoch_id, batch_id, np.mean(float(loss))
>                 )
>             )
> 
> 
> # 1. train & save model.
> 
> # create network
> layer = LinearNet()
> loss_fn = nn.CrossEntropyLoss()
> adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())
> 
> # create data loader
> dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
> loader = paddle.io.DataLoader(
>     dataset, batch_size=BATCH_SIZE, shuffle=True, drop_last=True, num_workers=0
> )
> 
> # train
> train(layer, loader, loss_fn, adam)
> 
> # save
> path = "example_model/linear"
> paddle.jit.save(layer, path)
> 
> # 2. load model
> 
> # load
> loaded_layer = paddle.jit.load(path)
> 
> # inference
> loaded_layer.eval()
> x = paddle.randn([1, IMAGE_SIZE], "float32")
> pred = loaded_layer(x)
> print(f"pred:{pred.numpy()}")
> 
> # fine-tune---------------->这里的方法是类似我所需要的，但是代码报错(见下面)
> loaded_layer.train()
> adam = opt.Adam(learning_rate=0.001, parameters=loaded_layer.parameters())
> train(loaded_layer, loader, loss_fn, adam)
> ```
> 
> 代码报错：
> 
> ```
> File "f:\*******\test.py", line 87, in <module>
>     train(loaded_layer, loader, loss_fn, adam)
>   File "f:\*******\test.py", line 43, in train
>     loss.backward()
>   File "D:\pyvenvs\py310\lib\site-packages\decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\framework.py", line 449, in __impl__
>     return func(*args, **kwargs)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 298, in backward
>     core.eager.run_backward([self], grad_tensor, retain_graph)
> ValueError: (InvalidArgument) The x.size() and x_grad_names.size() should be equal. But received x.size() = 1, x_grad_names.size() = 0
>   [Hint: Expected x.size() == x_grad_names.size(), but received x.size():1 != x_grad_names.size():0.] (at ..\paddle/fluid/eager/to_static/run_program_op_node.h:701)
> ```
> 
> 请问应该怎么解决这个问题呢？多谢@shiyutang

我本地跑这个case没有问题，请安装下最新版本的paddle再尝试下呢

**Comment by wangyexiang** [comment]
您好，我升级到paddlepaddle 2.5.1版本还是报错：

```
File "f:\************\test.py", line 43, in train
    loss.backward()
  File "D:\pyvenvs\py310\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\framework.py", line 449, in __impl__
    return func(*args, **kwargs)
  File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 298, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
ValueError: (InvalidArgument) The x.size() and x_grad_names.size() should be equal. But received x.size() = 1, x_grad_names.size() = 0
  [Hint: Expected x.size() == x_grad_names.size(), but received x.size():1 != x_grad_names.size():0.] (at ..\paddle/fluid/eager/to_static/run_program_op_node.h:701)
```

我用的是cpu版本，操作系统是win11，python版本为3.10.10。

**update**:我把飞桨版本降低到2.4.2后，可以正常运行@0x45f

**Comment by 0x45f** [comment]
> 您好，我升级到paddlepaddle 2.5.1版本还是报错：
> 
> ```
> File "f:\************\test.py", line 43, in train
>     loss.backward()
>   File "D:\pyvenvs\py310\lib\site-packages\decorator.py", line 232, in fun
>     return caller(func, *(extras + args), **kw)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
>     return wrapped_func(*args, **kwargs)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\framework.py", line 449, in __impl__
>     return func(*args, **kwargs)
>   File "D:\pyvenvs\py310\lib\site-packages\paddle\fluid\dygraph\tensor_patch_methods.py", line 298, in backward
>     core.eager.run_backward([self], grad_tensor, retain_graph)
> ValueError: (InvalidArgument) The x.size() and x_grad_names.size() should be equal. But received x.size() = 1, x_grad_names.size() = 0
>   [Hint: Expected x.size() == x_grad_names.size(), but received x.size():1 != x_grad_names.size():0.] (at ..\paddle/fluid/eager/to_static/run_program_op_node.h:701)
> ```
> 
> 我用的是cpu版本，操作系统是win11，python版本为3.10.10。
> 
> **update**:我把飞桨版本降低到2.4.2后，可以正常运行@0x45f

可以试试nightly build版本：https://www.paddlepaddle.org.cn/

**Comment by wangyexiang** [comment]
这个nightly build版本可以运行
