### ISSUE TITLE
这种json是什么标注的，怎么转png

### ISSUE THREAD

**Issue by xu756** [PaddlePaddle/Paddle#56385]
### 请提出你的问题 Please ask your question

这种json是什么标注的，怎么转png

```
<img width="1247" alt="iShot_2023-08-17_15 45 05" src="https://github.com/PaddlePaddle/Paddle/assets/84982391/0655cb83-e0d6-4565-a647-fed2fc09c003">

aistudio@jupyter-2065331-6652458:~/PaddleSeg$ python tools/data/labelme2seg.py dataset/data
Traceback (most recent call last):
  File "tools/data/labelme2seg.py", line 124, in <module>
    main(args)
  File "tools/data/labelme2seg.py", line 50, in main
    for shape in data['shapes']:
KeyError: 'shapes'
```
{
    "labels":[
        {
            "name":"crack",
            "x1":0,
            "y1":438,
            "x2":1023,
            "y2":614,
            "mask":"_>g0Zo00O1O1O10O01O100O010.....",
            "shape":"brush",
            "meta":{
                "actions":""
            },
            "size":{
                "height":1024,
                "width":1024
            }
        },
        {
            "name":"crack",
            "x1":615,
            "y1":507,
            "x2":803,
            "y2":552,
            "mask":"``Xc07go04M2N2N2N10001N100......",
            "shape":"brush",
            "meta":{
                "actions":""
            },
            "size":{
                "height":1024,
                "width":1024
            }
        }
    ]
}
``

**Comment by shiyutang** [comment]
你好，这个json结果不是eiseg/labelme的，我们也不确定是什么标注工具产生，建议溯源。

**Comment by shiyutang** [comment]
比如如何得到的这个json？

**Comment by xu756** [comment]
> 比如如何得到的这个json？

https://aistudio.baidu.com/datasetdetail/104352 你看看这个

**Comment by shiyutang** [comment]
这个数据来源我们也不知道是谁放的，所以不好意思，我们也不知道这个格式是什么标注个是，但是看上去是一些检测框的标注，可以写脚本把对应文件的检测框提取出来。
