### ISSUE TITLE
Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by vasanthsai26** [PaddlePaddle/Paddle#56408]
### 问题描述 Issue Description

I'm trying to install paddlepaddle , below are the details of my colab setup

!nvidia-smi     
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   42C    P8     9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|

!which python 
!python --version 

/usr/local/bin/python
Python 3.10.12 

!python -c 'import platform;print(platform.architecture()[0]);print(platform.machine())' 
64bit
x86_64

![image](https://github.com/PaddlePaddle/Paddle/assets/69052203/e22b4c4f-7790-41f2-813e-93b476a190e6)

!python -m pip install paddlepaddle-gpu==2.5.1.post120 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html 

Installation is successful, but when i try to import paddle, i'm getting below error 

Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so

I tried to install conda env in colab and run these still I see the same error. i did not find any resolutions in the repotted issues that could fix this issue. could someone please let me know what i could try to fix this. 

Thanks
Kalluri

### 版本&环境信息 Version & Environment Information

Requirement already satisfied: distro in /usr/lib/python3/dist-packages (1.7.0)
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 22.04
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.2
Libc version: glibc 2.35
Python version: 3.10.12

CUDA version: 11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: 8.9.0
Nvidia driver version: 525.105.17
Nvidia driver List: 
GPU 0: Tesla T4

****************************************
--2023-08-17 14:38:47--  https://raw.githubusercontent.com/PaddlePaddle/Paddle/develop/tools/summary_env.py
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5801 (5.7K) [text/plain]
Saving to: ‘summary_env.py’

     0K .....                                                 100% 51.1M=0s

2023-08-17 14:38:48 (51.1 MB/s) - ‘summary_env.py’ saved [5801/5801]

Error: Can not import paddle core while this file exists: /usr/local/lib/python3.10/dist-packages/paddle/fluid/libpaddle.so

**Comment by shiyutang** [comment]
Hi，did you try this?: https://stackoverflow.com/questions/76388016/error-can-not-import-paddle-core-while-this-file-exists

**Comment by vasanthsai26** [comment]
Yes I tried, it did not worked.

**Comment by vasanthsai26** [comment]
This is working by updating openssl https://github.com/PaddlePaddle/Paddle/issues/54194
