### ISSUE TITLE
[CustomDevice] 为paddle.device添加获取设备显存相关接口

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/Paddle#56416]
### 需求描述 Feature Description

**任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br />** 
cuda支持通过`paddle.device.cuda.max_memory_allocated`等接口获取设备显存占用。其核心接口调用`core.device_memory_stat_peak_value("Allocated", device_id)`是设备无关的。
```python
def max_memory_allocated(device=None):
    ......
    name = "paddle.device.cuda.max_memory_allocated"
    if not core.is_compiled_with_cuda():
        raise ValueError(
            f"The API {name} is not supported in CPU-only PaddlePaddle. Please reinstall PaddlePaddle with GPU support to call this API."
        )
    device_id = extract_cuda_device_id(device, op_name=name)
    return core.device_memory_stat_peak_value("Allocated", device_id)
```
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/device/cuda/__init__.py#L215

**需求场景（请描述你的项目中为什么需要用此功能）;  <br />** 
对于custom device设备，也希望能够获取显存信息。

**功能描述（请简单描述或设计这个功能）;  <br />**
是否能够在`paddle.device`下添加相关接口，支持custom device设备获取显存相关信息。

**Comment by ronny1996** [comment]
你好，目前这个接口不支持，需要调用DeviceMemoryStatPeakValue接口，但这个接口目前不支持CustomDevice
