### ISSUE TITLE
ERROR: Could not find a version that satisfies the requirement Pillow>=10.0.0

### ISSUE THREAD

**Issue by wang-tf** [PaddlePaddle/Paddle#56417]
### bug描述 Describe the Bug

In [paddle docker](https://hub.docker.com/layers/paddlepaddle/paddle/2.5.1-gpu-cuda10.2-cudnn7.6-trt7.0/images/sha256-65da4d564626c34f71337a9cf43e3cbb3aee8ffac6ed3525fa634130a92750e7?context=explore), the python version is 3.7. If it was used to install PaddleOCR, the error will discover because of Pillow version 10.0.0 was required. There is no Pillow wheel file for version 10.0.0 in [pypi](https://pypi.org/project/Pillow/10.0.0/#files).

**Comment by 0x45f** [comment]
建议使用py3.8及以上的版本，py3.7已经逐渐不再支持了

**Comment by wang-tf** [comment]
> 建议使用py3.8及以上的版本，py3.7已经逐渐不再支持了

请问会推出官方的py3.8的镜像么？

**Comment by 0x45f** [comment]
> > 建议使用py3.8及以上的版本，py3.7已经逐渐不再支持了
> 
> 请问会推出官方的py3.8的镜像么？

镜像里应该有多个py环境吧。或者可以自己装个conda试试py3.8

**Comment by wang-tf** [comment]
ok
