### ISSUE TITLE
验证安装是否成功，单卡正常，多卡卡着不动，求解！！！

### ISSUE THREAD

**Issue by wfs420100** [PaddlePaddle/Paddle#56454]
### 请提出你的问题 Please ask your question

<img width="1411" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/64070362/8890f306-cc2e-4676-89c3-9ee596104f1e">

**Comment by wfs420100** [comment]
使用docker镜像，多卡也是卡住没反应，，，（paddlepaddle/paddle:2.5.1-gpu-cuda11.7-cudnn8.4-trt8.4）

<img width="1366" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/64070362/03491b8d-710c-46e7-b820-e5416e2281f3">

**Comment by 0x45f** [comment]
请参考下面的文档，使用launch启动多卡程序：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/launch_cn.html#launch
