### ISSUE TITLE
模型相同参数情况下，和torch存在误差，误差随网络加深不断累积

### ISSUE THREAD

**Issue by BADBADBADBOY** [PaddlePaddle/Paddle#56462]
### 模型输出误差累积，代码如下：

[paddlebackbone.zip](https://github.com/PaddlePaddle/Paddle/files/12385378/paddlebackbone.zip)

### 其他补充信息 Additional Supplementary Information

整体代码在上面，很奇怪的是，前几成层误差还比较小，到model.block3的时候误差还可以接受，到深层model.block6误差不可接受，输出误差均值>1000，但是网络组成就是简单的堆叠，为啥会出现这么大的误差，这个问题在任何版本都是一样

**Comment by BADBADBADBOY** [comment]
任何版本都是一样

**Comment by zmxdream** [comment]
可以细粒度定位下具体是哪层哪个op开始出现较大误差
