### ISSUE TITLE
使用ImageFolder读取数据

### ISSUE THREAD

**Issue by kewuyu** [PaddlePaddle/Paddle#56482]
### 请提出你的问题 Please ask your question

![93aec28f2a3cb0f756e166d12def372](https://github.com/PaddlePaddle/Paddle/assets/109637491/3248b1a6-3a48-4943-9f43-9c9344de4cf9)
![ac4ff42d1b1d7c7fbc1726c684227dc](https://github.com/PaddlePaddle/Paddle/assets/109637491/ddc8ab40-a9ec-416b-84e5-5a8077735040)
![4edb60eef8441562f77fe69e30b7577](https://github.com/PaddlePaddle/Paddle/assets/109637491/892261d4-c77c-41e8-b382-8769704855fc)
![34d847762afec3e0aea3020342e25cb](https://github.com/PaddlePaddle/Paddle/assets/109637491/34063056-0cdb-402a-bae1-7188d544878f)
帮忙看一下

**Comment by YuanRisheng** [comment]
这个加载的图片目录下是怎么样存放数据的

**Comment by kewuyu** [comment]
tarin目录/标签目录/数据

**Comment by kewuyu** [comment]
> 这个加载的图片目录下是怎么样存放数据的

![Snipaste_2023-08-21_11-29-46](https://github.com/PaddlePaddle/Paddle/assets/109637491/c9baa5c8-03ba-4796-adcf-db9202f4eb62)

**Comment by YuanRisheng** [comment]
可以确认一下代码是否是示例代码，如果是示例代码，可以看一下是哪块儿代码，我会反馈给研发同学进行修复，如果不是示例代码，应该是需要自定义数据集加载方式，可以参考一下这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/data_load_cn.html#zhijiejiazaineizhishujuji

**Comment by kewuyu** [comment]
> 可以确认一下代码是否是示例代码，如果是示例代码，可以看一下是哪块儿代码，我会反馈给研发同学进行修复，如果不是示例代码，应该是需要自定义数据集加载方式，可以参考一下这个：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/data_load_cn.html#zhijiejiazaineizhishujuji

谢谢
