### ISSUE TITLE
映射文档问题，use_softmax参数

### ISSUE THREAD

**Issue by ZS-YANG** [PaddlePaddle/Paddle#56495]
### bug描述 Describe the Bug

映射文档问题，use_softmax参数未分析
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/loss.py#L2454

### 其他补充信息 Additional Supplementary Information

映射文档问题，use_softmax参数未分析
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/functional/loss.py#L2454

**Comment by zhwesky2010** [comment]
@ZS-YANG 这个需要你进行分析下。
