### ISSUE TITLE
windows下安装飞桨报SSL错误，无法安装。。

### ISSUE THREAD

**Issue by dxisdx** [PaddlePaddle/Paddle#56498]
### 问题描述 Issue Description

用pip安装 windows下的CUDA11.8版本报错：Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/paddlepaddle-gpu/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tu
na.tsinghua.edu.cn', port=443): Max retries exceeded with url: /simple/paddlepaddle-gpu/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been close
d (EOF) (_ssl.c:1131)'))) - skipping
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.5.1 (from versions: none)
ERROR: No matching distribution found for paddlepaddle-gpu==2.5.1
Could not fetch URL https://pypi.tuna.tsinghua.edu.cn/simple/pip/: There was a problem confirming the ssl certificate: HTTPSConnectionPool(host='pypi.tuna.tsinghua.e
du.cn', port=443): Max retries exceeded with url: /simple/pip/ (Caused by SSLError(SSLZeroReturnError(6, 'TLS/SSL connection has been closed (EOF) (_ssl.c:1131)'))) 
- skipping
无法安装

### 版本&环境信息 Version & Environment Information

 PaddlePaddle版本：2.5
CPU（可选）：i7 11800h
GPU：RTX 3070m，CUDA11.8 
系统环境：请说明系统类型、版本windows 10 64位
Python版本如python 3.8
若安装过程遇到问题，请提供安装方式python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple

**Comment by xuxinyi389** [comment]
该错误的原因可能有多种原因。
1.检查pip版本是否符合最低要求,可以尝试升级pip版本，推荐命令：pip install --upgrade pip
2.是否创建了虚环境，如果有请检查python版本，确保支持相应的 SSL/TLS 协议。
3.可以尝试换用该命令，将清华源加入受信任的主机。换用该命令python -m pip install paddlepaddle-gpu==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple --trusted-host pypi.tuna.tsinghua.edu.cn
4.如果你的网络环境受限，可能还需要进一步设置pip命令的proxy参数，这需要你提供进一步的信息。
