### ISSUE TITLE
运行paddle.utils.run_check() 卡住不动

### ISSUE THREAD

**Issue by coolge** [PaddlePaddle/Paddle#56514]
### 问题描述 Issue Description

paddle=2.2.2
cuda 10.2
cudnn 7.6.5
NVIDIA A30
可以在Tesla P40调通，但是在A30上调不通。

<img width="1121" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/14039870/a9a54e29-87a3-4fcb-84fc-bf1b81ffd200">

### 版本&环境信息 Version & Environment Information

paddle=2.2.2
cuda 10.2
cudnn 7.6.5
NVIDIA A30

**Comment by zhengqiwen1997** [comment]
a30和cuda10.2不匹，此问题已解决
