### ISSUE TITLE
这个模型库中的代码  和  paddle book  完全是不对应的  好多引入不了  是需要更新paddle book吗？

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5653]
ImportErrorTraceback (most recent call last)
<ipython-input-7-da299c7c0f86> in <module>()
      2 import paddle.v2.dataset.flowers as flowers
      3 import paddle.v2 as paddle
----> 4 import reader
      5 import vgg
      6 import resnet

ImportError: No module named reader

AttributeErrorTraceback (most recent call last)
<ipython-input-6-9c680b093d98> in <module>()
----> 1 out = resnet.resnet_imagenet(image, class_dim=CLASS_DIM)

AttributeError: 'module' object has no attribute 'resnet_imagenet'

**Comment by jacquesqiao** [comment]
cd到models/image_classification这个目录下运行试试

**Comment by 466821202** [comment]
是在这个目录下运行的

**Comment by 466821202** [comment]
我是在paddle book  执行    根本没有 models 这个目录啊

**Comment by chengduoZH** [comment]
该issue长时间没有更新，可以先关闭了，如要继续讨论请再打开
