### ISSUE TITLE
端口作用

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#5654]
hi，使用v1过程中，由于频繁遇到port used问题。所以有以下问题
1. 在v1中的端口是起什么作用的呢。是用在参数更新过程中哪个环节呢。
2. 在cluster_config中设置了一个端口号。如果用到mpi多个结点，多个trainer，那么要用到多少个端口号呢。

**Comment by typhoonzero** [comment]
> 在v1中的端口是起什么作用的呢。是用在参数更新过程中哪个环节呢。

不论是v1还是v2还是后续的版本，端口都用于分布式训练中，参数更新时，trainer和parameter server通信。

> 在cluster_config中设置了一个端口号。如果用到mpi多个结点，多个trainer，那么要用到多少个端口号呢。

有两个参数port和ports_num。例如`port=7164`, `ports_num=2`，那么每个mpi节点会使用7164, 7165两个端口通信。依次类推。
