### ISSUE TITLE
这里需要支持custom_device的判断，否则会清理掉pass

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/Paddle#56540]
https://github.com/PaddlePaddle/Paddle/blob/29efbdb6b5d182b97bab404309298162093f7008/paddle/fluid/inference/api/analysis_predictor.cc#L1572

**Comment by ronny1996** [comment]
你好，这里应该不需要，trt和gpu也会清理pass

**Comment by ronny1996** [comment]
感谢反馈，这个pr修了这个问题 https://github.com/PaddlePaddle/Paddle/pull/56755
