### ISSUE TITLE
这个模型库中的代码  import reader  reader.train_reader('train.list')  这个reader到底在那里啊  求大神了  帮帮忙  我提了好多遍问题了 其实就想知道这个reader 怎么实现的？  

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5655]
这个模型库中的代码  import reader  reader.train_reader('train.list')  这个reader到底在那里啊  求大神了  帮帮忙  我提了好多遍问题了 其实就想知道这个啊？

**Comment by guoshengCS** [comment]
能否说明下是那个例子中的，我搜了下`import reader `好多都有

**Comment by 466821202** [comment]
http://paddlepaddle.org/docs/develop/models/image_classification/README.html#permalink-2--

**Comment by guoshengCS** [comment]
是这个文件 https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py

**Comment by 466821202** [comment]
太感谢了！！！！！！
