### ISSUE TITLE
paddle randn 返回都是0，并求和结果不正确

### ISSUE THREAD

**Issue by listen-wind** [PaddlePaddle/Paddle#56577]
#### paddle randn 返回都是0

```python
import paddle
out1 = paddle.randn(shape=[2, 3])
Tensor(shape=[2, 3], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       [[0., 0., 0.],
        [0., 0., 0.]])
```

#### 求和结果不正确
```python
out2 = paddle.to_tensor(1) + 0.2
Tensor(shape=[], dtype=float32, place=Place(gpu:0), stop_gradient=True,
       0.)
```

#### 使用环境
device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.8
device: 0, cuDNN Version: 8.9.

**Comment by FeixLiu** [comment]
您使用的是什么版本的paddle呢？我在paddle的develop上没有复现该问题。可以尝试使用最新的paddle（nightly）：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

<img width="761" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/25279174/7f66c393-4dc2-4a08-b1c1-c3ce2fd4cc24">

**Comment by listen-wind** [comment]
我使用的就是最新的2.5.1版本，后面我使用cuda11.7，使用paddle2.4.2，可以了

**Comment by listen-wind** [comment]
> 您使用的是什么版本的paddle呢？我在paddle的develop上没有复现该问题。可以尝试使用最新的paddle（nightly）：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
> 
> <img alt="image" width="761" src="https://user-images.githubusercontent.com/25279174/262643281-7f66c393-4dc2-4a08-b1c1-c3ce2fd4cc24.png">

我使用的就是最新的2.5.1版本，后面我使用cuda11.7，使用paddle2.4.2，可以了

**Comment by Ligoml** [comment]
<img width="588" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39876205/87a2e41a-5d0e-4486-a8e0-ae685456c991">

测试了2.5.1，好像也没有这个问题
