### ISSUE TITLE
`paddlepaddle/paddle:develop` docker 镜像中的 `python` 版本仍然是 3.5，PyCharm 不支持它。

### ISSUE THREAD

**Issue by ozogxyz** [PaddlePaddle/Paddle#56581]
### 问题描述 Issue Description

`paddlepaddle/paddle:develop` docker 镜像中的 `python` 版本仍然是 3.5，PyCharm 不支持它。

<img width="842" alt="Screenshot 2023-08-23 at 13 20 00" src="https://github.com/PaddlePaddle/Paddle/assets/50372354/c5fad368-95a0-4bbe-bdd8-789ad378bfb2">

### 版本&环境信息 Version & Environment Information

不适用，因为它与 docker 镜像有关.

**Comment by FeixLiu** [comment]
可能默认python的默认镜像是3.5，可以使用python3.7来启动python3.7。

**Comment by ozogxyz** [comment]
是的，但更新 `docker` 镜像不是更好吗？这样就能让更多人开箱即用了☺️。
