### ISSUE TITLE
使用trainer.test，第二个Pass后train使用的是test中reader读取的数据

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#5658]
models/ctr例子，第一个pass之后使用的数据集不再是train里读取的，而是test中的reader读取的，原因如下：取batch_size=1w，train数据量有400w多，test数据量1w，第一个pass输出了400多个batch_id，第二个pass以后读取一个batch就结束了，如果把test的数据量增加1，即10001，第二个pass以后的batch由1变成2，说明第二个pass后读取的是test中reader的数据而不是train中reader的数据
以前用这个test也遇到过问题，大概是：train用20170901的数据，test如果用的是20170902的数据，最后的评估的结果是20170902的效果明显好于其他天，现在看来原来是因为第二个pass后train的数据集使用的是20170902而不是20170901，所以相当于train使用的是20170902，评估20170902的效果自然好于其他天。
![image](https://user-images.githubusercontent.com/10849519/32818402-b3cb02f2-c988-11e7-996f-49c206d5ebbc.png)

**Comment by guoshengCS** [comment]
这个问了下其他跑过这个的同学是没问题的，我们下来再看下

**Comment by wanghaoshuang** [comment]
这个貌似是个bug，需要修改下。我先看看。

**Comment by wanghaoshuang** [comment]
@buptwds 这个commit应该修复了你的问题。https://github.com/PaddlePaddle/models/commit/2fffef933762fccd24f8fbf8d77f25cf8f2b5d6f#diff-b7ee1eca88c965913e22a8983eebea78

**Comment by Yancey1989** [comment]
这个issue由于长时间未更新先关闭了，如有依然有问题请重新打开它。
