### ISSUE TITLE
paddle2.5推理问题

### ISSUE THREAD

**Issue by marshall-dteach** [PaddlePaddle/Paddle#56619]
### bug描述 Describe the Bug

模型压缩推理时遇到报错paddle2.5不支持算子，但是paddle2.4.1不存在这个问题
![image](https://github.com/PaddlePaddle/Paddle/assets/63546191/e38638dd-0d52-4646-916d-d6a0f6f90634)

**Comment by wuhuachaocoding** [comment]
@RichardWooSJTU 辛苦帮忙看下

**Comment by RichardWooSJTU** [comment]
压缩产出的模型需要打开tensorrt进行推理，否则在paddle2.4版本使用的是fake量化推理，速度甚至是不如非量化模型的；paddle2.5这里的报错原因在于paddle在逐渐支持原生量化推理，但是目前仅支持transformer模型且限制较多，因此还是推荐打开tensorrt。

如果还是想执行fake 量化推理的话可以屏蔽掉这个pass和其他量化相关pass
```cpp
config.delete_pass("delete_quant_dequant_linear_op_pass")
config.delete_pass("delete_weight_dequant_linear_op_pass")
```

具体参见：https://www.paddlepaddle.org.cn/inference/v2.5/api_reference/python_api_doc/Config/OptimConfig.html#ir
https://www.paddlepaddle.org.cn/inference/v2.5/api_reference/python_api_doc/Config/GPUConfig.html#tensorrt
