### ISSUE TITLE
申威服务器 编译paddle2.1.3报错

### ISSUE THREAD

**Issue by moye111** [PaddlePaddle/Paddle#56610]
### 问题描述 Issue Description

按照  https://www.paddlepaddle.org.cn/documentation/docs/zh/2.1/install/compile/sw-compile.html  文档编译安装
make -j$(nproc)  命令报错：
root@838b914603c0:/home/pylib/Paddle/build# make -j$(nproc)
[  0%] Built target extern_zlib
[  0%] copy_if_different /home/pylib/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  0%] Performing update step for 'extern_gflags'
[  0%] copy_if_different /home/pylib/Paddle/build/paddle/fluid/operators/jit/kernels.h
[  0%] Built target copy_paddle_inference_pass_command
-- extern_gflags update command succeeded.  See also /home/pylib/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-update-*.log
[  0%] copy_if_different /home/pylib/Paddle/build/paddle/fluid/pybind/pybind.h
[  0%] Built target copy_kernels_command
[  0%] Performing configure step for 'extern_gflags'
[  1%] Built target extern_eigen3
[  1%] Built target copy_pybind_command
[  1%] Built target extern_boost
[  2%] Built target extern_threadpool
[  2%] Built target extern_dlpack
[  2%] Performing build step for 'extern_openblas'
-- extern_gflags configure command succeeded.  See also /home/pylib/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-configure-*.log
make[3]: warning: -j0 forced in submake: resetting jobserver mode.
[  2%] Performing update step for 'extern_warpctc'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
[  2%] Performing update step for 'extern_pybind'
[  2%] Performing build step for 'extern_gflags'
getarch.c:1193:2: error: #error "This arch/CPU is not supported by OpenBLAS."
 #error "This arch/CPU is not supported by OpenBLAS."
  ^~~~~
getarch.c: In function 'main':
getarch.c:1255:5: warning: implicit declaration of function 'get_libname'; did you mean 'gethostname'? [-Wimplicit-function-declaration]
     get_libname();
     ^~~~~~~~~~~
     gethostname
getarch.c:1346:5: warning: implicit declaration of function 'get_cpuconfig' [-Wimplicit-function-declaration]
     get_cpuconfig();
     ^~~~~~~~~~~~~
make[3]: *** [Makefile.prebuild:62: getarch] Error 1
Makefile.system:1103: Makefile.sw_64: No such file or directory
make[3]: *** No rule to make target 'Makefile.sw_64'.  Stop.
make[2]: *** [CMakeFiles/extern_openblas.dir/build.make:112: third_party/openblas/src/extern_openblas-stamp/extern_openblas-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:348: CMakeFiles/extern_openblas.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
-- extern_warpctc update command succeeded.  See also /home/pylib/Paddle/build/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-update-*.log
-- extern_pybind update command succeeded.  See also /home/pylib/Paddle/build/third_party/pybind/src/extern_pybind-stamp/extern_pybind-update-*.log
[  2%] Performing configure step for 'extern_warpctc'
[  2%] No configure step for 'extern_pybind'
[ 50%] Built target gflags_nothreads_static
[100%] Built target gflags_static
[  2%] No build step for 'extern_pybind'
[  2%] Performing install step for 'extern_gflags'
-- extern_warpctc configure command succeeded.  See also /home/pylib/Paddle/build/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-configure-*.log
[  2%] No install step for 'extern_pybind'
[  2%] Performing build step for 'extern_warpctc'
[  2%] No test step for 'extern_pybind'
[100%] Built target warpctc
[  2%] Completed 'extern_pybind'
[  2%] Performing install step for 'extern_warpctc'
-- extern_gflags install command succeeded.  See also /home/pylib/Paddle/build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-install-*.log
[  2%] Completed 'extern_gflags'
[  2%] Built target extern_pybind
[  2%] Built target extern_gflags
-- extern_warpctc install command succeeded.  See also /home/pylib/Paddle/build/third_party/warpctc/src/extern_warpctc-stamp/extern_warpctc-install-*.log
[  2%] Completed 'extern_warpctc'
[  2%] Built target extern_warpctc
make: *** [Makefile:130: all] Error 2
root@838b914603c0:/home/pylib/Paddle/build#  gcc --version
gcc (GCC) 8.3.0
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

### 版本&环境信息 Version & Environment Information

Error: Can not import noavx core while this file exists: /usr/local/lib/python3.7/dist-packages/paddle/fluid/core_noavx.so
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: uos 20
GCC version: (GCC) 8.3.0
Clang version: N/A
CMake version: version 3.13.4
Libc version: glibc 2.28
Python version: 3.7.3

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by ccsuzzh** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/65210872/3342e521-e9bd-406c-9474-e979096c097b)

**Comment by moye111** [comment]
您的邮件已收到，我会尽早查看，谢谢。
