### ISSUE TITLE
PaddlePaddle在源码编译过程中报错  Could NOT find Git (missing: GIT_EXECUTABLE)

### ISSUE THREAD

**Issue by leonardxie** [PaddlePaddle/Paddle#56624]
### bug描述 Describe the Bug

在ARM服务器上编译源码编译PaddlePaddle，报错。
服务器为鲲鹏920处理器 麒麟V10操作系统 SP1版本
我下载了PaddlePaddle的Paddle-release-2.5分支的zip包代码，并复制到了我的服务器上docker容器的物理机内。
GCC，G++均已正常安装。
编译指令为
cmake ..  G“Ninja” -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF >cmake.log 2>&1

我参考了paddlepaddle的这个教程进行的操作
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html

### 其他补充信息 Additional Supplementary Information

cmake的报错日志信息如下：
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Deprecation Warning at CMakeLists.txt:28 (cmake_policy):
  The OLD behavior for policy CMP0104 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Paddle host system: , version: 
-- Found Paddle host system's CPU: 96 cores
-- The CXX compiler identification is GNU 10.3.1
-- The C compiler identification is GNU 10.3.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
CMake Warning (dev) at CMakeLists.txt:50 (find_package):
  Policy CMP0146 is not set: The FindCUDA module is removed.  Run "cmake
  --help-policy CMP0146" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
EXP_CUDA_MODULE_LOADING_LAZY only works with GPU
-- CXX compiler: /usr/bin/c++, version: GNU 10.3.1
-- C compiler: /usr/bin/cc, version: GNU 10.3.1
-- AR tools: /usr/bin/ar
CMake Error at /home/anaconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find Git (missing: GIT_EXECUTABLE)
Call Stack (most recent call first):
  /home/anaconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  /home/anaconda3/lib/python3.8/site-packages/cmake/data/share/cmake-3.27/Modules/FindGit.cmake:128 (find_package_handle_standard_args)
  CMakeLists.txt:232 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by leonardxie** [comment]
@RichardWooSJTU 麻烦帮忙看一下

**Comment by qili93** [comment]
根据提示“Could NOT find Git (missing: GIT_EXECUTABLE)”，需要在环境中安装 git
