### ISSUE TITLE
官方文档搜索结果连接失效

### ISSUE THREAD

**Issue by zishuaiz** [PaddlePaddle/Paddle#5662]
http://www.paddlepaddle.org/docs/0.10.0/documentation/en/search.html?q=paddle.init&check_keywords=yes&area=default

搜索结果连接失效。

顺便问一句：
paddle.init这个函数的`详细详细详细详细详细`api在哪，找个api咋就这么难呢？！
要去源码找么，能不能行？！

都快路转黑了~

**Comment by guoshengCS** [comment]
`paddle.init` 支持的参数可以先参考http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/howto/usage/cmd_parameter/use_case_cn.html 和 http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/howto/usage/cmd_parameter/arguments_cn.html
这是C++ bin进行训练的命令行参数，`init`是使用swig封装C++得到的支持相同的参数，这个的文档有所欠缺，文档我们也在不断的完善中~

**Comment by chengduoZH** [comment]
Close due to low activity, please feel free to reopen it.
