### ISSUE TITLE
ipykernel_launcher.py: error: argument model: invalid choice

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5663]
usage: ipykernel_launcher.py [-h] {alexnet,vgg13,vgg16,vgg19,resnet,googlenet}
ipykernel_launcher.py: error: argument model: invalid choice: '/root/.local/share/jupyter/runtime/kernel-381e7fc4-daee-48ea-ab43-a85e86faf75e.json' (choose from 'alexnet', 'vgg13', 'vgg16', 'vgg19', 'resnet', 'googlenet')
An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

**Comment by guoshengCS** [comment]
可否按照报错中的说明打下full traceback

**Comment by Yancey1989** [comment]
I'll close this issue since no update for a long time, please feel free to reopen it if necessary.
