### ISSUE TITLE
clone后third_party下某些文件夹为空

### ISSUE THREAD

**Issue by yoyoIcy** [PaddlePaddle/Paddle#56646]
### 问题描述 Please describe your issue

在对照文档完成热身打卡编译过程中：
按照文档clone代码之后编译时发现/paddle/third_party下  warprnnt和threadpool文件夹下无内容
打卡版本如下：
<img width="208" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/142126786/4575fee7-feef-4360-a375-feb4a1c7b534">

解决方法：
1. warprnnt文件夹删掉重新拉取后可以继续编译
2. threadpool是手动下载了[ThreadPool.h](https://github.com/progschj/ThreadPool/blob/9a42ec1329f259a5f4881a291db1dcb8f2ad9040/ThreadPool.h)放到threadpool文件夹后可以继续编译

另：在编译过程中发现交换空间不足也会导致编译失败
<img width="1605" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/142126786/79872386-ce99-4629-863d-f45ba98a3391">
解决方案：调增swap空间

实际成功编译的docker resources配置值为cpu 5，memory 16G，swap 2G。供参考

**Comment by risemeup1** [comment]
third_party没成功，可以rm -rf Paddle/third_party，git submodule update --init

**Comment by risemeup1** [comment]
顺便问一下，增加swap空间实在docker里设置的吗，我也遇到了类似的问题，好像设置swap空间没生效，方便把你设置的方法分享一下吗

**Comment by yoyoIcy** [comment]
好的，多谢啦~

然后我是这样设置的，然后会重启容器
<img width="1239" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/142126786/99926d69-48b4-4068-a4e4-dc07f41e6c46">
