### ISSUE TITLE
Session or Program

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#5666]
In [this](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/refactor/session.md) design doc, we define session as:

> The session object encapsulates the environment in which the computation graph is executed.

But currently for local training this is what the `Program` do. The `IR` is represented as `ProgramDesc` in protobuf format. It seems that we don't need to create another concept of same meaning, just add a `RemoteProgram` or some attribute in `ProgramDesc` can do the job.

**Comment by helinwang** [comment]
From https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/program.md :
> A PaddlePaddle program consists of two parts -- the first generates a ProgramDesc protobuf message that describes the program, and the second runs this message using a C++ class Executor

Maybe we can rename `Session` to `Executor`?

**Comment by typhoonzero** [comment]
Can't agree more. Will update the design doc.

**Comment by helinwang** [comment]
thanks!
