### ISSUE TITLE
 parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by akira178452130** [PaddlePaddle/Paddle#56683]
### 请提出你的问题 Please ask your question

硬件信息:
ubuntu20.04
GTX1080
CUDA版本:
cuda driver:535.86.10 cuda versionj: 12.2(driver API version: 12.2)
cudatoolkit: 11.6(runtime API version: 11.6)
cudnn: 8.4.0
报错 parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
奇怪的是我进入python命令行输入paddle.utils.run_check()是没有问题的，提示PaddlePaddle is installed successfully!，只报了几个warning ，但是实际使用paddlenlp的Taskflow的时候就报错了
查了一下这个报错说是cuda和paddlnlp的版本有问题，但是按理说只要cudaruntime版本低于driver版本就不会有什么问题，paddlepaddle-gpu也是按照https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html这个安装的对应cuda11.6版本的 但就是跑不起来

作为参考这些是命令行检验安装时报的warning
W0826 15:37:30.498044  6709 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0826 15:37:30.498070  6709 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.6
W0826 15:37:30.503268  6709 gpu_resources.cc:149] device: 0, cuDNN Version: 8.4.

**Comment by zhangbo9674** [comment]
您好，除了上述 warning 外，麻烦提供一下详细的报错截图

**Comment by zhengqiwen1997** [comment]
请提供下安装命令，怀疑是使用了不合适的安装whl包
