### ISSUE TITLE
鲲鹏920ARM系统编译安装后报错

### ISSUE THREAD

**Issue by wickedsickk** [PaddlePaddle/Paddle#56694]
### 问题描述 Issue Description

在鲲鹏cpu环境源码编译安装PaddlePaddle，安装成功，使用时报错

### 版本&环境信息 Version & Environment Information

鲲鹏920
架构：ARMV8
麒麟 V10
python 3.7

**编译过程中的cmake命令**：
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON
-DWITH_TESTING=OFF -DON_INFER=ON -DWITH_XBYAK=OFF
-DCMAKE_CXX_FLAGS="-Wno-error -w"

**报错信息**

报错代码
paddle.distributed.init_parallel_env()

Traceback (most recent call last):
File "<train.py>", line 3, in
File "", line 320, in
File "", line 115, in train_dsp
File "/opt/py3.7/lib/python3.7/site-packages/paddle/distributed/parallel.py", line 1101, in init_parallel_env
pg_options=None,
File "/opt/py3.7/lib/python3.7/site-packages/paddle/distributed/collective.py", line 151, in _new_process_group_impl
pg = core.ProcessGroupGloo.create(store, rank, world_size, group_id)
AttributeError: module 'paddle.fluid.libpaddle' has no attribute 'ProcessGroupGloo'

**Comment by ronny1996** [comment]
你好，请使用这个编译命令 
```
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=ON
```

**Comment by wickedsickk** [comment]
> 

用这个命令进行编译，在执行 make TARGET=ARMV8 -j$(nproc) 时报错

[  1%] Built target copy_signatures_command
make  -f paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/build.make paddle/fluid/operators/CMakeFiles/copy_pybind_command.dir/build
[  1%] Built target copy_kernels_command
make  -f CMakeFiles/extern_zlib.dir/build.make CMakeFiles/extern_zlib.dir/build
make  -f CMakeFiles/extern_utf8proc.dir/build.make CMakeFiles/extern_utf8proc.dir/depend
CMake Error at /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-Release.cmake:49 (message):
  Command failed: 1

   '/opt/cmake-3.19/bin/cmake' '-DCMAKE_CXX_COMPILER=/usr/bin/c++' '-DCMAKE_C_COMPILER=/usr/bin/cc' '-DCMAKE_C_FLAGS=' '-DCMAKE_C_FLAGS_DEBUG=-g' '-DCMAKE_C_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS= -Wno-error=deprecated-declarations -Wno-deprecated-declarations' '-DCMAKE_CXX_FLAGS_RELEASE=-O3 -DNDEBUG' '-DCMAKE_CXX_FLAGS_DEBUG=-g' '-DCMAKE_INSTALL_PREFIX=/workspace/Paddle/build/third_party/install/warprnnt' '-DWITH_GPU=OFF' '-DWITH_ROCM=OFF' '-DWITH_OMP=ON' '-DBUILD_SHARED=ON' '-DBUILD_TESTS=OFF' '-DCMAKE_POSITION_INDEPENDENT_CODE=ON' '-DCMAKE_BUILD_TYPE=Release' '-GUnix Makefiles' '-C/workspace/Paddle/build/third_party/warprnnt/tmp/extern_warprnnt-cache-Release.cmake' '/workspace/Paddle/third_party/warprnnt'

  See also

    /workspace/Paddle/build/third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure-*.log


make  -f CMakeFiles/extern_lapack.dir/build.make CMakeFiles/extern_lapack.dir/depend
make[2]: Leaving directory '/workspace/Paddle/build'
make[2]: *** [CMakeFiles/extern_warprnnt.dir/build.make:129: third_party/warprnnt/src/extern_warprnnt-stamp/extern_warprnnt-configure] Error 1
make[2]: Leaving directory '/workspace/Paddle/build'
make  -f CMakeFiles/extern_dlpack.dir/build.make CMakeFiles/extern_dlpack.dir/build
[  1%] Built target copy_declarations_command
make[1]: *** [CMakeFiles/Makefile2:4929: CMakeFiles/extern_warprnnt.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by ronny1996** [comment]
请删除掉 Paddle/third_party，并执行 git submodule update --init
