### ISSUE TITLE
本地版训练出现“Check failed: PySequence_Check(seq_) ”问题

### ISSUE THREAD

**Issue by SniperZhao** [PaddlePaddle/Paddle#567]
dataprovider设置：
![image](https://cloud.githubusercontent.com/assets/11026164/20550564/ec2d59ea-b171-11e6-8c77-6ad50a2a2280.png)
![image](https://cloud.githubusercontent.com/assets/11026164/20550569/f7add36c-b171-11e6-91b0-ca42091daef5.png)

trainer.py设置：
![image](https://cloud.githubusercontent.com/assets/11026164/20550539/95c3727e-b171-11e6-97d5-a5e66a8cdd5b.png)

train.sh设置：
![image](https://cloud.githubusercontent.com/assets/11026164/20550524/7738fe14-b171-11e6-8821-fb19082b4746.png)

报错信息：
![image](https://cloud.githubusercontent.com/assets/11026164/20550514/5cbbb662-b171-11e6-8354-d313d5e11b36.png)

**Comment by SniperZhao** [comment]
只是单纯的想做一个回归，数据并不是序列的，为什么还会做序列检查呢？不是很理解。

**Comment by qingqing01** [comment]
版本更新之后 Check failed: PySequence_Check(seq_)问题已经没有了。
