### ISSUE TITLE
旧版本安装页面好像找不到2.4安装方式了，啥时候更新一波？

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/Paddle#56710]
### 文档链接&描述 Document Links & Description

![a80ca526170bdcfa5328bbe6136aff5](https://github.com/PaddlePaddle/Paddle/assets/45508593/e91379a1-4e69-46b3-afa9-1b5c3272dfe3)
旧版本安装页面好像找不到2.4安装方式了，啥时候更新一波？

### 请提出你的建议 Please give your suggestion

希望更新旧版本2.4安装方式

**Comment by ronny1996** [comment]
好的，我反馈一下

**Comment by zhengqiwen1997** [comment]
已更新完毕
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/guides/hardware_support/rocm_docs/paddle_install_cn.html
