### ISSUE TITLE
paddle.amp.GradScaler没有set_state_dict()

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#56737]
### 请提出你的问题 Please ask your question

 - PaddlePaddle 2.5.1

为啥paddle.nn.Layer和paddle.amp.GradScaler加载模型不是统一的set_state_dict()
目前是paddle.nn.Layer用的是set_state_dict()，而paddle.amp.GradScaler用的是load_state_dict()

**Comment by ZzSean** [comment]
你好，请问这个差异导致您遇到了什么问题吗？

**Comment by yeyupiaoling** [comment]
@ZzSean 也没什么大问题。就是习惯性model、optimizer、GradScaler全部使用set_state_dict()，导致报错，改了就好。
