### ISSUE TITLE
如何使用小内存的服务器训练大内存的数据

### ISSUE THREAD

**Issue by 1220985305** [PaddlePaddle/Paddle#56740]
### 请提出你的问题 Please ask your question

如何使用小内存的服务器训练大内存的数据
 具体地，假如服务器内存为128G，而训练数据为512G，10000个，有没有好的策略去训练，最好让所有数据都参与训练；
不限某个套件，detection，Seg都可

**Comment by ZzSean** [comment]
你好，内存不够的话，可以减小batch_size，或者采取常见的分布式训练中的数据并行和模型并行
