### ISSUE TITLE
Train ResNet50 with imagenet  report : OSError: [Errno 24] Too many open files

### ISSUE THREAD

**Issue by chaofanl** [PaddlePaddle/Paddle#56743]
### bug描述 Describe the Bug

用imagenet 训练 resnet50
在data_loader里面启用多线程num_workers=32，运行不久后就会出现这个问题。 : OSError: [Errno 24] Too many open files
说一下自己的环境：
intel_gpu
python3.10
paddlepaddle : f55b387df0f473574f82c83da0c4c821829f35a7(Tue Apr 25 21:02:37 2023)
model-scripts : PaddleClas develop master

**Comment by chaofanl** [comment]
<img width="1171" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/50936814/b23417b0-eb84-4b66-b9ef-050e59d8bcbe">

**Comment by ZzSean** [comment]
你好，这个报错应该是同时打开的文件数量过多，超出了限制，导致这样的原因可能是你开的线程数太多了，解决方法建议：
1. ulimit -a 看下最大允许打开文件数量
2. open files  (-n) 表示这个数量
3. ulimit -n xxxx 设置这个限制大一些，可以先用lsof | wc -l 看下当前一共打开了多少文件，根据这个值设定一个限制值
