### ISSUE TITLE
安装GPU版本后运行异常

### ISSUE THREAD

**Issue by nuoline** [PaddlePaddle/Paddle#5674]
安装的GPU版本
运行：paddle train \
       --config=postag_train.py \
       --parallel_nn=1 \
       --use_gpu=true \
       --dot_period=10 \
       --log_period=1000 \
       --test_period=0 \
       --num_passes=10 
错误提示如下：
python27-gcc482/bin/paddle: line 83: [: too many arguments
  File "<stdin>", line 3
    if LooseVersion("0.10.0
                          ^
SyntaxError: EOL while scanning string literal
I1115 15:42:03.529911  4739 Util.cpp:166] commandline: /home/ssd1/zhaizhouwei/python27-gcc482/bin/paddle_trainer --config=postag_train.py --parallel_nn=1 --use_gpu=true --dot_period=10 --log_period=1000 --test_period=0 --num_passes=10 
W1115 15:42:11.678481  4739 CpuId.h:112] PaddlePaddle wasn't compiled to use avx instructions, but these are available on your machine and could speed up CPU computations via CMAKE .. -DWITH_AVX=ON
I1115 15:42:11.881070  4739 Trainer.cpp:165] trainer mode: Normal
F1115 15:42:11.883350  4739 hl_gpu_matrix_kernel.cuh:181] Check failed: cudaSuccess == err (0 vs. 8) [hl_gpu_apply_unary_op failed] CUDA error: invalid device function
*** Check failure stack trace: ***
    @           0x66fb8d  google::LogMessage::Fail()
    @           0x67363c  google::LogMessage::SendToLog()
    @           0x66f683  google::LogMessage::Flush()
    @           0x674b4e  google::LogMessageFatal::~LogMessageFatal()
    @           0x940f04  hl_gpu_apply_unary_op<>()
    @           0x941245  paddle::BaseMatrixT<>::applyUnary<>()
    @           0x941473  paddle::BaseMatrixT<>::zero()
    @           0x7afd81  paddle::Parameter::enableType()
    @           0x7ab60c  paddle::parameterInitNN()
    @           0x7add5a  paddle::NeuralNetwork::init()
    @           0x7d402f  paddle::ParallelNeuralNetwork::init()
    @           0x7d6a11  paddle::GradientMachine::create()
    @           0x8a7a08  paddle::TrainerInternal::init()
    @           0x8a40b2  paddle::Trainer::init()
    @           0x652a84  main
    @     0x7f07e3992bd5  __libc_start_main
    @           0x66d425  (unknown)
    @              (nil)  (unknown)
/home/ssd1/zhaizhouwei/python27-gcc482/bin/paddle: line 96:  4739 Aborted                 ${DEBUGGER} $PADDLE_BIN_PATH/paddle_trainer ${@:2}

**Comment by guoshengCS** [comment]
有类似的issue可以参考下 https://github.com/PaddlePaddle/Paddle/issues/2931#issuecomment-316283163

**Comment by sweetsky0901** [comment]
可以查看一下你本地的cuda和cudnn的版本。
如果是通过pip install安装的，是需要要求cuda8和cudnn5的。
具体下载地址
cuda8的下载地址是：https://developer.nvidia.com/cuda-toolkit-archive
cudnn5的下载地址是：https://developer.nvidia.com/rdp/cudnn-archive

**Comment by Yancey1989** [comment]
这个issue由于长时间未更新先关闭了，如有依然有问题请重新打开它。
