### ISSUE TITLE
[Extensions]auto_parallel.pb.h会在extensions里被引用

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#56750]
### bug描述 Describe the Bug

在开发第三方插件的时候，
写入
```cpp
#include "paddle/phi/extension.h"

```

会触发
```
No such file or directory
#include "paddle/phi/core/distributed/auto_parallel/auto_parallel.pb.h"
```
原因来源于
```
paddle/phi/core/tensor_utils.h:19
paddle/phi/core/distributed/auto_parallel/dist_attr.h:25:10
```
pb头文件在tensor_utils里被引用了，这合理吗？

@ronny

**Comment by engineer1109** [comment]
实验了一下，
删除 paddle/phi/core/tensor_utils.h 中的
```
#include "paddle/phi/core/distributed/auto_parallel/dist_tensor.h"
```
可以让extension编译成功

**Comment by engineer1109** [comment]
@ronny1996

**Comment by ZzSean** [comment]
你好，根据这个PR [#56361](https://github.com/PaddlePaddle/Paddle/pull/56361)来看，当前是取消了代码中的宏`PADDLE_WITH_DISTRIBUTE`限制，因此引入了这个头文件，可以尝试打开编译选项`-DWITH_DISTRIBUTE=ON`，重新编译试试

**Comment by engineer1109** [comment]
@ZzSean -DWITH_DISTRIBUTE=ON 下这个头文件还是会被引用的吧。
引用的头文件范围还是会扩大到protobuf

**Comment by engineer1109** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56760 Fixing
