### ISSUE TITLE
google drive 的文件，下载不了. 1. 国内肯定没戏啊 2.  翻墙了的也有限制. 

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#568]
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/verbDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/targetDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/wordDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/emb --no-check-certificate

**Comment by backyes** [comment]
Check https://github.com/PaddlePaddle/Paddle/issues/509. 

Google search already index github repo, so you can try "no-check-certificate paddle download github"  keywords to search answers if necessary.

In addtion, we will try to fix help scripts to output readable download options immediately.

**Comment by backyes** [comment]
@VamWolf 

Can you update you code? These URLs above do not exist in demo/semantic_role_labeling in latest code.  

@reyoung @luotao1 @qingqing01

**Comment by VamWolf** [comment]
刚看了下代码，还是这个URL 啊.  https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/data/get_data.sh 。你看下？

**Comment by gangliao** [comment]
@zhangjcqq  Please take a look at this.

**Comment by backyes** [comment]
Currently we work on release branch for next release ，It seems it is ok in https://github.com/PaddlePaddle/Paddle/blob/release/v0.9.0/demo/semantic_role_labeling/data/get_data.sh



-------- 原始邮件 --------
发件人：VamWolf <notifications@github.com>
时间：周三 11月23日 12:53
收件人：PaddlePaddle/Paddle <Paddle@noreply.github.com>
抄送："Wang,Yanfei(IDL)" <wangyanfei01@baidu.com>,Comment <comment@noreply.github.com>
主题：Re: [PaddlePaddle/Paddle] google drive 的文件，下载不了. 1. 国内肯定没戏啊 2. 翻墙了的也有限制. (#568)


刚看了下代码，还是这个URL 啊. https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/data/get_data.sh 。你看下？

**Comment by luotao1** [comment]
在release分支已经全部更新了，还没merge到develop分支

**Comment by VamWolf** [comment]
求一个百度网盘的下载地址，主干上的semantic role labeling 的数据获取还是这个方式. 尝试改了一下，没搞定. 还得再看看


wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/verbDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/targetDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/wordDict.txt --no-check-certificate
wget https://www.googledrive.com/host/0B7Q8d52jqeI9ejh6Q1RpMTFQT1k/semantic_role_labeling/emb --no-check-certificate

**Comment by gangliao** [comment]
@luotao1  release 那个是老的。
@zhangjcqq  请尽快解决一下，目前有几个人再问了。

**Comment by luotao1** [comment]
其他demo都更新了，srl的demo还未更新

**Comment by reyoung** [comment]
Release分支下的SRL demo里面没有google drive的数据呀？要更新什么？

**Comment by reyoung** [comment]
我们测试release的时候，SRL demo的PR还没有merge，所以这个版本，SRL还是使用老版本的demo代码

**Comment by luotao1** [comment]
用户应该问的是develop分支，@zhangjcqq develop分支也请尽快更新下吧

**Comment by luotao1** [comment]
@VamWolf 路径已经全部更新
