### ISSUE TITLE
使用自训练模型推理报错：Microsoft C++ 异常: phi::enforce::EnforceNotMet

### ISSUE THREAD

**Issue by WilliamQf-AI** [PaddlePaddle/Paddle#56828]
### 请提出你的问题 Please ask your question

使用自训练模型推理报错：Microsoft C++ 异常: phi::enforce::EnforceNotMet，请问这是啥意思？怎样解决？

**Comment by FrostML** [comment]
`phi::enforce::EnforceNotMet` 表示执行算子的某个前置条件不满足，应该有具体的报错信息，可以贴一下具体的报错内容是什么。是用的 [Paddle Inference](https://www.paddlepaddle.org.cn/inference/v2.5/api_reference/cxx_api_doc/cxx_api_index.html) 么？

**Comment by mgq2space** [comment]
请问一下解决了？我也遇到相同的问题

**Comment by WilliamQf-AI** [comment]
> 请问一下解决了？我也遇到相同的问题

没有，但是他们关闭了
