### ISSUE TITLE
请在AnalysisPredictor::PrepareArgument中适配npu的pass分支，避免被清空

### ISSUE THREAD

**Issue by bmers** [PaddlePaddle/Paddle#56830]
### 需求描述 Feature Description

在analysis_predictor.cc中，AnalysisPredictor::PrepareArgument函数中，当前没有适配npu分支，在推理时混合精度开启下，会清空Pass，请适配。
![image](https://github.com/PaddlePaddle/Paddle/assets/29788896/ea4ec6f3-ea9c-4dd7-9fd6-7dc5ef616cb0)

### 替代实现 Alternatives

![image](https://github.com/PaddlePaddle/Paddle/assets/29788896/52453c0b-b9c3-4bc0-b77b-a60dd8ff35a5)

**Comment by ronny1996** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56755 fixed
