### ISSUE TITLE
Return back to allreduce

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#5683]
The biggest finding is that most of the frameworks have abandoned Parameter Server and switched to allreduce. 

1. Tensorflow: https://github.com/uber/horovod
￼
![30b58a1d-45be-437c-ac7b-eb7b8db01a42](https://user-images.githubusercontent.com/3071933/32870248-ee1640d8-cab5-11e7-8dac-5a18eba50927.png)

2. ChainerMN: 
![img_20171028_105843](https://user-images.githubusercontent.com/3071933/32870214-ce0880ee-cab5-11e7-8abb-56f6f9c5d3c2.jpg)

![img_20171028_105921](https://user-images.githubusercontent.com/3071933/32870306-42a57ba0-cab6-11e7-8122-4101b29d401a.jpg)

3. Caffe2:
Yangqing gives a talk about `return to MPI` at AISys, SOSP'17. Sorry, he did not share this slides.

https://github.com/facebookincubator/gloo

Their training ImageNet in one hour is actually used allreduce. https://arxiv.org/abs/1706.02677

Based on above facts, I think this algorithm is faster, at least, it should be considered inside Paddle. 

NCCL2: https://developer.nvidia.com/nccl
￼

**Comment by typhoonzero** [comment]
Indeed we need to have an implementation of AllReduce using MPI API to gain benefits of RDMA and HPC architecture. Then user can choose either to train using Elastic training or HPC training.
