### ISSUE TITLE
ngram模型，补全的节点向量问题

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#5684]
现在想做前面4个词，预测后面一个词这样一个模型。
对于不满5个词的训练数据也不想丢弃，进行补全
比如训练数据是a，b（b是label），补全成empty empty empty a b
最终是通过前面4个词embedding后累加成一个向量，预测后面一个词
这边有办法使得empty固定embedding成0向量，不参与学习吗？
或者这边可以使得输入词是不固定长的，比如上面的例子，我只要计算a的向量，放到累加层

**Comment by wanghaoshuang** [comment]
你直接在你的data_reader里补齐input就行了，可以补0向量。

**Comment by windy444** [comment]
@wanghaoshuang 
我在代码里面补了s，但是这边怎么指定embedding后是0向量呢？
<img width="557" alt="2017-11-16 1 58 18" src="https://user-images.githubusercontent.com/33304501/32876095-e4ec108c-ca60-11e7-99b8-e6291ed976ae.png">

**Comment by windy444** [comment]
使用integer_value_sequence就可以了
