### ISSUE TITLE
Macos安装paddle_cpu版本后import报错

### ISSUE THREAD

**Issue by overloadedHenry** [PaddlePaddle/Paddle#56860]
### bug描述 Describe the Bug

```python
import paddle
```

```
Process finished with exit code 132 (interrupted by signal 4: SIGILL)
```

### 其他补充信息 Additional Supplementary Information

CPU:Apple M2 Silicon

**Comment by zhengqiwen1997** [comment]
是不是用的x86的python呀？使用arm的python 再安装一下吧

**Comment by overloadedHenry** [comment]
> 是不是用的x86的python呀？使用arm的python 再安装一下吧

不是的,只有2.3版本的paddle没有问题,但是2.3以上的就会报错

**Comment by zhengqiwen1997** [comment]
请问 python 版本是什么呢？是否按照 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/pip/macos-pip.html 的步骤安装了？
