### ISSUE TITLE
模型库-图像分类  训练 一直内核重启  求指导  那里可以看到详细的日志

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5688]
I1116 05:06:47.209822 11126 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
I1116 05:06:47.735155 11126 GradientMachine.cpp:94] Initing parameters..
I1116 05:06:50.696238 11126 GradientMachine.cpp:101] Init parameters done.
[I 05:07:30.348 NotebookApp] KernelRestarter: restarting kernel (1/5)
WARNING:root:kernel c1098098-63f1-46af-9e37-3bfa0458bdcb restarted

http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html

    optimizer = paddle.optimizer.Momentum(
        momentum=0.9,
        regularization=paddle.optimizer.L2Regularization(rate=0.0005 *
                                                         BATCH_SIZE),
        learning_rate=learning_rate / BATCH_SIZE,
        learning_rate_decay_a=0.1,
        learning_rate_decay_b=128000 * 35,
        learning_rate_schedule="discexp", )        只拿了一百多张图片做测试

**Comment by wanghaoshuang** [comment]
这应该不是paddle的问题，你可以参考下[这里](https://github.com/jupyter/notebook/issues/990)

**Comment by yeyupiaoling** [comment]
我怀疑是你的配置问题，

**Comment by myimpress** [comment]
我是加大内存就能跑了
