### ISSUE TITLE
data_provider 加载字典错误

### ISSUE THREAD

**Issue by sjtuwy** [PaddlePaddle/Paddle#569]
> Log file created at: 2016/11/23 11:12:59
Running on machine: yq01-hpc-wutai01-w00054.yq01.baidu.com
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F1123 11:12:59.977150 10936 PyDataProvider2.cpp:222] Check failed: (module) != nullptr Python Error: <type 'exceptions.IOError'> : [Errno 2] No such file or directory: './sparse_fea_entropy.20161112.dict'
Python Callstack: 
            /home/disk1/normandy/maybach/17395/workspace/thirdparty/thirdparty/ei_fea_provider_gender_sparse.py : 26
Cannot imort module ei_fea_provider_gender_sparse

任务运行脚本：
`rm -rf thirdparty
mkdir thirdparty
cp ei_fea_provider_gender_sparse.py ./thirdparty/
cp ./weiyi01/sparse_fea_entropy.20161112.dict  ./thirdparty/

SCRIPT_PATH=$PWD
export PYTHONPATH=$PYTHONPATH:$PWD:../../python/

  #--where=yq01-ecom-triger-box_slurm_cluster \
paddle cluster_train \
  --config=$SCRIPT_PATH/trainer_config_gender_sparse.cluster.py \
  --use_gpu=cpu \
  --time_limit=100:00:00 \
  --submitter=weiyi01 \
  --num_nodes=1 \
  --job_priority=normal \
  --config_args=is_local=False \
  --trainer_count=4 \
  --num_passes=1 \
  --log_period=10 \
  --dot_period=100 \
  --saving_period=1 \
  --test_all_data_in_one_period=1 \
  --distribute_test=1 \
  --job_name=weiyi01_dt_gender_train_sparse \
  --where=yq01-hpc-wutai01-dmop-cpu-10G_cluster \
  --thirdparty=$SCRIPT_PATH/thirdparty`

通过--thirdparty上传，workspace/thirdparty/thirdparty目录下也有这个字典，请问是什么原因，如何正确加字典？

**Comment by backyes** [comment]
问题不适合这里解答，close issue。
