### ISSUE TITLE
The GPU architecture in your current machine is Ampere, which is not compatible with Paddle installation with arch: 52 60 61 70 75

### ISSUE THREAD

**Issue by codeyearn** [PaddlePaddle/Paddle#56908]
### 问题描述 Issue Description

![00f7b312f9c576dba92f469e6f437a5](https://github.com/PaddlePaddle/Paddle/assets/44339043/eebb86b5-d751-431d-9ac4-cd56033c7f3f)

### 版本&环境信息 Version & Environment Information

我的电脑环境：
os：win11
显卡：nvidia 2050
cuda：10.2
conda：23.7.2
python：3.11

显卡版本截图：
![image](https://github.com/PaddlePaddle/Paddle/assets/44339043/09153ff5-cd5b-4cda-a20b-8391e1c920bc)

准备使用paddleOcr

**Comment by danleifeng** [comment]
可以参考官网上安装paddle正确的版本：
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/windows-conda.html#anchor-0
https://www.paddlepaddle.org.cn/
![image](https://github.com/PaddlePaddle/Paddle/assets/52735331/ce45e2cf-0474-4c65-8b69-e09f2d3125af)
