### ISSUE TITLE
部分API使用GPU上的IncrementOffset时，offset不对齐4倍

### ISSUE THREAD

**Issue by Xiadalei** [PaddlePaddle/Paddle#56912]
`IncrementOffset`作为generator设置offset的接口其设置的offset会进行数据叠加，一般我们希望offset设置是4的倍数，这个可以从部分API的描述中看出，如[distribution helper](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/funcs/distribution_helper.h#L314)。
但是目前部分API 使用hard code的offset设置，但并不是4的倍数如：[truncated_gaussian_random_kernel](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/truncated_gaussian_random_kernel.cu#L102)，[dirichlet_kernel](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/dirichlet_kernel.cu#L81)，[gumbel_softmax_kernel](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/gumbel_softmax_kernel.cu#L152)。由于这里的数值都是硬编码且数值本身无意义，是否可以进行4倍对齐的修改？

**Comment by ForFishes** [comment]
您好，这里涉及到算子的改动，会造成之前旧算子精度对不齐。请问一下，这个功能的需求背景是什么呢？

**Comment by liao-tianju** [comment]
> 您好，这里涉及到算子的改动，会造成之前旧算子精度对不齐。请问一下，这个功能的需求背景是什么呢？

我们想在customdevice上对齐GPU的随机结果，而当offset非4倍数时，philox随机需要多做一轮，这样对于性能影响较大
