### ISSUE TITLE
NPU编译paddle出错

### ISSUE THREAD

**Issue by Wall-cn** [PaddlePaddle/Paddle#56911]
### bug描述 Describe the Bug

编译步骤及环境都是严格按照https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md下的，到bash tools/compile.sh时遇到如下错误：
Scanning dependencies of target paddle-custom-npu
[ 15%] Building CXX object CMakeFiles/paddle-custom-npu.dir/runtime/runtime.cc.o
[ 16%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/abs_kernel.cc.o
[ 17%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/accuracy_kernel.cc.o
[ 17%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/activation_kernel.cc.o
[ 18%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/adadelta_kernel.cc.o
[ 18%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/adagrad_kernel.cc.o
[ 19%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/adam_kernel.cc.o
[ 20%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/add_n_kernel.cc.o
[ 20%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/amp/check_finite_and_unscale_kernel.cc.o
[ 21%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/amp/update_loss_scaling_kernel.cc.o
[ 21%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/arange_kernel.cc.o
[ 22%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/arg_min_max_kernel.cc.o
[ 23%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/argsort_grad_kernel.cc.o
[ 23%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/argsort_kernel.cc.o
[ 24%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/assign_kernel.cc.o
[ 25%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/batch_norm_kernel.cc.o
[ 25%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/bce_loss_kernel.cc.o
[ 26%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/bitwise_kernel.cc.o
[ 26%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/bmm_kernel.cc.o
[ 27%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/box_coder_kernel.cc.o
[ 28%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/cast_kernel.cc.o
[ 28%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/clip_by_norm_kernel.cc.o
[ 29%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/clip_kernel.cc.o
[ 29%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/coalesce_tensor_kernel.cc.o
[ 30%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/compare_kernel.cc.o
[ 31%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/concat_kernel.cc.o
[ 31%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/conv2d_kernel.cc.o
[ 32%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/conv_kernel.cc.o
[ 32%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/conv_transpose_kernel.cc.o
[ 33%] Building CXX object CMakeFiles/paddle-custom-npu.dir/kernels/cross_entropy_kernel.cc.o
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:26:
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/flags.h:65:16: error: expected constructor, destructor, or type conversion before ‘(’ token
   DEFINE_string(name, EnvToString("FLAGS_" #name, value), meaning)
                ^
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:28:1: note: in expansion of macro ‘FLAGS_DEFINE_string’
 FLAGS_DEFINE_string(npu_profiling_dir,
 ^~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/flags.h:62:16: error: expected constructor, destructor, or type conversion before ‘(’ token
   DEFINE_uint64(name, EnvToUInt("FLAGS_" #name, value), meaning)
                ^
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:31:1: note: in expansion of macro ‘FLAGS_DEFINE_uint64’
 FLAGS_DEFINE_uint64(npu_profiling_dtypes,
 ^~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/flags.h:62:16: error: expected constructor, destructor, or type conversion before ‘(’ token
   DEFINE_uint64(name, EnvToUInt("FLAGS_" #name, value), meaning)
                ^
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:36:1: note: in expansion of macro ‘FLAGS_DEFINE_uint64’
 FLAGS_DEFINE_uint64(npu_profiling_metrics,
 ^~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc: In function ‘C_Status ProfilerInitialize(C_Profiler, void**)’:
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:645:14: error: ‘FLAGS_npu_profiling_dir’ was not declared in this scope
           << FLAGS_npu_profiling_dir
              ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:646:50: error: ‘FLAGS_npu_profiling_dtypes’ was not declared in this scope
           << ", FLAGS_npu_profiling_dtypes: " << FLAGS_npu_profiling_dtypes
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/runtime/runtime.cc:647:51: error: ‘FLAGS_npu_profiling_metrics’ was not declared in this scope
           << ", FLAGS_npu_profiling_metrics: " << FLAGS_npu_profiling_metrics;
                                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/amp/update_loss_scaling_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/conv_util.h:16,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/conv_util.h:16,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/compare_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/cross_entropy_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/conv_util.h:16,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv_transpose_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/argsort_grad_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/adadelta_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc: In function ‘void custom_kernel::Conv2dKernel(const Context&, const phi::DenseTensor&, const phi::DenseTensor&, const std::vector<int>&, const std::vector<int>&, const string&, const std::vector<int>&, int, const string&, phi::DenseTensor*)’:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:32:7: error: ‘FLAGS_npu_storage_format’ was not declared in this scope
   if (FLAGS_npu_storage_format) {
       ^~~~~~~~~~~~~~~~~~~~~~~~
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/adam_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_enforce.h:21,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/conv_util.h:16,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:37: error: ‘FLAGS_npu_storage_format’ was not declared in this scope
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
                                     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:442:20: note: in definition of macro ‘__PADDLE_BINARY_COMPARE’
     auto __val1 = (__VAL1);                                               \
                    ^~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/accuracy_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:447:37: error: ‘__TYPE1__’ was not declared in this scope
         ::phi::details::CommonType1<__TYPE1__, __TYPE2__>;                \
                                     ^~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/add_n_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/arg_min_max_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:447:37: note: suggested alternative: ‘__TYPE2__’
         ::phi::details::CommonType1<__TYPE1__, __TYPE2__>;                \
                                     ^~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:447:57: error: template argument 1 is invalid
         ::phi::details::CommonType1<__TYPE1__, __TYPE2__>;                \
                                                         ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:449:57: error: type/value mismatch at argument 1 in template parameter list for ‘template<class T1, class T2> using CommonType2 = typename std::add_lvalue_reference<typename std::add_const<typename phi::enforce::details::TypeConverter<T1, T2>::Type2>::type>::type’
         ::phi::details::CommonType2<__TYPE1__, __TYPE2__>;                \
                                                         ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:449:57: note:   expected a type, got ‘__TYPE1__’
         ::phi::details::CommonType2<__TYPE1__, __TYPE2__>;                \
                                                         ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
In file included from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_runner.h:19,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:20,
                 from /home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/activation_kernel.cc:15:
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/funcs/npu_op_prepare.h:27:13: error: expected constructor, destructor, or type conversion before ‘(’ token
 DECLARE_bool(npu_storage_format);
             ^
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:450:40: error: ‘__COMMON_TYPE1__’ does not name a type; did you mean ‘__COUNTER__’?
     bool __is_not_error = (static_cast<__COMMON_TYPE1__>(__val1))__CMP(   \
                                        ^~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:473:3: note: in expansion of macro ‘__PADDLE_BINARY_COMPARE’
   __PADDLE_BINARY_COMPARE(__VAL0, __VAL1, ==, !=, __VA_ARGS__)
   ^~~~~~~~~~~~~~~~~~~~~~~
/home/ma-user/work/PaddleCustomDevice/backends/npu/kernels/conv2d_kernel.cc:44:3: note: in expansion of macro ‘PADDLE_ENFORCE_EQ’
   PADDLE_ENFORCE_EQ(channel_last && FLAGS_npu_storage_format,
   ^~~~~~~~~~~~~~~~~
/home/ma-user/.conda/envs/huawei_npu/lib/python3.9/site-packages/paddle/include/paddle/phi/core/enforce.h:451:21: error: ‘__COMMON_TYPE2__’ does not name a type; did you mean ‘__TYPE2__’?
         static_cast<__COMMON_TYPE2__>(__val2));

**Comment by USTCKAY** [comment]
这个bug是https://github.com/PaddlePaddle/Paddle/pull/56256 引入的，目前正在修复中，请稍等

**Comment by Walllllllllllllll** [comment]
> 这个bug是#56256 引入的，目前正在修复中，请稍等

哦哦，好的

**Comment by USTCKAY** [comment]
Hi，这个bug已解决。请拉取最新cusotm device代码试试

**Comment by Walllllllllllllll** [comment]
编译成功了，没有问题！

**Comment by USTCKAY** [comment]
此bug已解决
