### ISSUE TITLE
custom_allocator 可能会导致内存泄露

### ISSUE THREAD

**Issue by EnflameGCU** [PaddlePaddle/Paddle#56933]
CustomAllocator::AllocateImpl 调用了 MemoryAllocate，CustomAllocator::FreeImpl 没有对应调用 MemoryDeallocate， 可能会导致内存泄露。

https://github.com/PaddlePaddle/Paddle/blob/be9cb946e507832f9c0fe5fc1d0f5343f1da08b9/paddle/fluid/memory/allocation/custom_allocator.cc#L33

**Comment by engineer1109** [comment]
内存一直在增长是吗？

**Comment by EnflameGCU** [comment]
我们是小网络测试的，本身内存占用比较少。看到调用到了CustomDevice的内存申请接口，一直到结束退出都没有调用到内存释放接口。

**Comment by engineer1109** [comment]
确实不会释放
```cpp
auto x = paddle::experimental::empty({1, 2, 3, 4}, paddle::DataType::FLOAT32);
```
只会分配内存
