### ISSUE TITLE
Paddle和PaddleNLP最新develop分支代码GPU导出动态batch模型出错

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/Paddle#56946]
### bug描述 Describe the Bug

Paddle和PaddleNLP最新develop分支代码，执行导出动态batch模型命令报错，导出命令如下：
```python
python export_model.py \
    --model_name_or_path facebook/llama-7b \
    --output_path ./inference \
    --dtype float16 \
    --inference_model \
    --max_batch_size 8
```

报错信息：keyError,  state_dict里面没有"llama.embed_tokens.weight" key值

**Comment by MARD1NO** [comment]
目前推理模型这边使用safetensor类型权重还有一定兼容问题，可以先

rm -rf /root/.paddlenlp/models/facebook/llama-65b （一般默认路径是这里）

然后另外写一个下载非safetensor类型的权重脚本运行：
```
from paddlenlp.transformers import *

llama = AutoModel.from_pretrained('facebook/llama-65b', use_safetensors=False)
llama = AutoTokenizer.from_pretrained('facebook/llama-65b', use_safetensors=False)
```

再进行转换。

65b权重转换要求内存容量较大，如果内存不够出现OOM，可以先用下面的脚本对权重进行预切分：
```
"""
Author(Zhengzekang):

If we use PaddleNLP to export distributed model by using dy2static directly, 
each device will read full model which easily cause OOM. 

This script only use single device to read full model and split model by assigned NRANKS

"""

import paddle 
import os 
import json 

# Define Weight Name List. 
LLAMA_COLUMN_SPLIT_WEIGHT_LIST = [
    "self_attn.q_proj.weight",
    "self_attn.k_proj.weight",
    "self_attn.v_proj.weight",
    "mlp.gate_proj.weight",
    "mlp.up_proj.weight",
]

LLAMA_ROW_SPLIT_WEIGHT_LIST = [
    "self_attn.o_proj.weight",
    "mlp.down_proj.weight"
]

LLAMA_NO_SPLIT_WEIGHT_LIST = [
    "input_layernorm.weight",
    "post_attention_layernorm.weight"
]

LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST = [
    "lm_head.weight"
]

EMBEDDING_ROW_SPLIT_WEIGHT_LIST = [
    "llama.embed_tokens.weight"
]

FINAL_NORM_WEIGHT_LSIT = [
    "llama.norm.weight"
]

def parse_arguments():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--model_dir", required=True, help="The directory of model.")
    parser.add_argument("--output_model_dir", required=True, help="The directory of model.")
    parser.add_argument("--nranks", type=int, default="1", help="The number of distributed model num. ")
    return parser.parse_args()

def col_split(weight, nranks): 
    return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=1, num_or_sections=nranks)

def row_split(weight, nranks): 
    return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=0, num_or_sections=nranks)

def split_model_weight(model_dir, nranks, output_model_path): 
    model_state_path = os.path.join(model_dir, "model_state.pdparams")
    origin_model = paddle.load(model_state_path, return_numpy=True)
    config = None 
    with open(os.path.join(model_dir, "config.json"), "r") as f: 
        config = json.load(f) 

    for rank_id in range(nranks): 
        print("Now process rank: ", rank_id)
        split_state_dict = dict()
        col_split_lm_head_weight = col_split(origin_model[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
        row_split_embed_token_weight = row_split(origin_model[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
        split_state_dict[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]] = col_split_lm_head_weight
        split_state_dict[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]] = row_split_embed_token_weight

        for layer_id in range(config["num_hidden_layers"]): 
            print("Now process LayerIdx: ", layer_id)
            for column_split_weight_name in LLAMA_COLUMN_SPLIT_WEIGHT_LIST: 
                full_column_split_weight_name = "llama.layers.{}.".format(layer_id) + column_split_weight_name
                column_split_weight = col_split(origin_model[full_column_split_weight_name], nranks)[rank_id]
                split_state_dict[full_column_split_weight_name] = column_split_weight

            for row_split_weight_name in LLAMA_ROW_SPLIT_WEIGHT_LIST: 
                full_row_split_weight_name = "llama.layers.{}.".format(layer_id) + row_split_weight_name
                row_split_weight = row_split(origin_model[full_row_split_weight_name], nranks)[rank_id]
                split_state_dict[full_row_split_weight_name] = row_split_weight

            for no_split_weight_name in LLAMA_NO_SPLIT_WEIGHT_LIST: 
                full_no_split_weight_name = "llama.layers.{}.".format(layer_id) + no_split_weight_name
                split_state_dict[full_no_split_weight_name] = paddle.to_tensor(origin_model[full_no_split_weight_name], place=paddle.CPUPlace())

        last_norm_weight_name = FINAL_NORM_WEIGHT_LSIT[0]
        split_state_dict[last_norm_weight_name] = paddle.to_tensor(origin_model[last_norm_weight_name], place=paddle.CPUPlace())
        paddle.save(split_state_dict, os.path.join(output_model_path, "model_state.tp0{}.pdparams".format(rank_id)))

if __name__ == "__main__": 
    args = parse_arguments()
    split_model_weight(args.model_dir, 
                       args.nranks, 
                       args.output_model_dir)


```

运行：
```
python3.8 split_weight.py \
            --model_dir=/root/.paddlenlp/models/facebook/llama-65b \
            --nranks=8 \
            --output_model_dir=xxxx/split_llama_65b
```

再将export模型的目录换成切分好模型权重的目录

**Comment by MARD1NO** [comment]
> ### bug描述 Describe the Bug
> Paddle和PaddleNLP最新develop分支代码，执行导出动态batch模型命令报错，导出命令如下：
> 
> ```python
> python export_model.py \
>     --model_name_or_path facebook/llama-7b \
>     --output_path ./inference \
>     --dtype float16 \
>     --inference_model \
>     --max_batch_size 8
> ```
> 
> 报错信息：keyError, state_dict里面没有"llama.embed_tokens.weight" key值
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

目前推理模型这边使用safetensor类型权重还有一定兼容问题，可以先

rm -rf /root/.paddlenlp/models/facebook/llama-65b （一般默认路径是这里）

然后另外写一个下载非safetensor类型的权重脚本运行：
```
from paddlenlp.transformers import *

llama = AutoModel.from_pretrained('facebook/llama-65b', use_safetensors=False)
llama = AutoTokenizer.from_pretrained('facebook/llama-65b', use_safetensors=False)
```

再进行转换。

65b权重转换要求内存容量较大，如果内存不够出现OOM，可以先用下面的脚本对权重进行预切分：
```
"""
Author(Zhengzekang):

If we use PaddleNLP to export distributed model by using dy2static directly, 
each device will read full model which easily cause OOM. 

This script only use single device to read full model and split model by assigned NRANKS

"""

import paddle 
import os 
import json 

# Define Weight Name List. 
LLAMA_COLUMN_SPLIT_WEIGHT_LIST = [
    "self_attn.q_proj.weight",
    "self_attn.k_proj.weight",
    "self_attn.v_proj.weight",
    "mlp.gate_proj.weight",
    "mlp.up_proj.weight",
]

LLAMA_ROW_SPLIT_WEIGHT_LIST = [
    "self_attn.o_proj.weight",
    "mlp.down_proj.weight"
]

LLAMA_NO_SPLIT_WEIGHT_LIST = [
    "input_layernorm.weight",
    "post_attention_layernorm.weight"
]

LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST = [
    "lm_head.weight"
]

EMBEDDING_ROW_SPLIT_WEIGHT_LIST = [
    "llama.embed_tokens.weight"
]

FINAL_NORM_WEIGHT_LSIT = [
    "llama.norm.weight"
]

def parse_arguments():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument("--model_dir", required=True, help="The directory of model.")
    parser.add_argument("--output_model_dir", required=True, help="The directory of model.")
    parser.add_argument("--nranks", type=int, default="1", help="The number of distributed model num. ")
    return parser.parse_args()

def col_split(weight, nranks): 
    return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=1, num_or_sections=nranks)

def row_split(weight, nranks): 
    return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=0, num_or_sections=nranks)

def split_model_weight(model_dir, nranks, output_model_path): 
    model_state_path = os.path.join(model_dir, "model_state.pdparams")
    origin_model = paddle.load(model_state_path, return_numpy=True)
    config = None 
    with open(os.path.join(model_dir, "config.json"), "r") as f: 
        config = json.load(f) 

    for rank_id in range(nranks): 
        print("Now process rank: ", rank_id)
        split_state_dict = dict()
        col_split_lm_head_weight = col_split(origin_model[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
        row_split_embed_token_weight = row_split(origin_model[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
        split_state_dict[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]] = col_split_lm_head_weight
        split_state_dict[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]] = row_split_embed_token_weight

        for layer_id in range(config["num_hidden_layers"]): 
            print("Now process LayerIdx: ", layer_id)
            for column_split_weight_name in LLAMA_COLUMN_SPLIT_WEIGHT_LIST: 
                full_column_split_weight_name = "llama.layers.{}.".format(layer_id) + column_split_weight_name
                column_split_weight = col_split(origin_model[full_column_split_weight_name], nranks)[rank_id]
                split_state_dict[full_column_split_weight_name] = column_split_weight

            for row_split_weight_name in LLAMA_ROW_SPLIT_WEIGHT_LIST: 
                full_row_split_weight_name = "llama.layers.{}.".format(layer_id) + row_split_weight_name
                row_split_weight = row_split(origin_model[full_row_split_weight_name], nranks)[rank_id]
                split_state_dict[full_row_split_weight_name] = row_split_weight

            for no_split_weight_name in LLAMA_NO_SPLIT_WEIGHT_LIST: 
                full_no_split_weight_name = "llama.layers.{}.".format(layer_id) + no_split_weight_name
                split_state_dict[full_no_split_weight_name] = paddle.to_tensor(origin_model[full_no_split_weight_name], place=paddle.CPUPlace())

        last_norm_weight_name = FINAL_NORM_WEIGHT_LSIT[0]
        split_state_dict[last_norm_weight_name] = paddle.to_tensor(origin_model[last_norm_weight_name], place=paddle.CPUPlace())
        paddle.save(split_state_dict, os.path.join(output_model_path, "model_state.tp0{}.pdparams".format(rank_id)))

if __name__ == "__main__": 
    args = parse_arguments()
    split_model_weight(args.model_dir, 
                       args.nranks, 
                       args.output_model_dir)


```

运行：
```
python3.8 split_weight.py \
            --model_dir=/root/.paddlenlp/models/facebook/llama-65b \
            --nranks=8 \
            --output_model_dir=xxxx/split_llama_65b
```

再将export模型的目录换成切分好模型权重的目录

**Comment by zhjc** [comment]
> > ### bug描述 Describe the Bug
> > Paddle和PaddleNLP最新develop分支代码，执行导出动态batch模型命令报错，导出命令如下：
> > ```python
> > python export_model.py \
> >     --model_name_or_path facebook/llama-7b \
> >     --output_path ./inference \
> >     --dtype float16 \
> >     --inference_model \
> >     --max_batch_size 8
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 报错信息：keyError, state_dict里面没有"llama.embed_tokens.weight" key值
> > ### 其他补充信息 Additional Supplementary Information
> > _No response_
> 
> 目前推理模型这边使用safetensor类型权重还有一定兼容问题，可以先
> 
> rm -rf /root/.paddlenlp/models/facebook/llama-65b （一般默认路径是这里）
> 
> 然后另外写一个下载非safetensor类型的权重脚本运行：
> 
> ```
> from paddlenlp.transformers import *
> 
> llama = AutoModel.from_pretrained('facebook/llama-65b', use_safetensors=False)
> llama = AutoTokenizer.from_pretrained('facebook/llama-65b', use_safetensors=False)
> ```
> 
> 再进行转换。
> 
> 65b权重转换要求内存容量较大，如果内存不够出现OOM，可以先用下面的脚本对权重进行预切分：
> 
> ```
> """
> Author(Zhengzekang):
> 
> If we use PaddleNLP to export distributed model by using dy2static directly, 
> each device will read full model which easily cause OOM. 
> 
> This script only use single device to read full model and split model by assigned NRANKS
> 
> """
> 
> import paddle 
> import os 
> import json 
> 
> # Define Weight Name List. 
> LLAMA_COLUMN_SPLIT_WEIGHT_LIST = [
>     "self_attn.q_proj.weight",
>     "self_attn.k_proj.weight",
>     "self_attn.v_proj.weight",
>     "mlp.gate_proj.weight",
>     "mlp.up_proj.weight",
> ]
> 
> LLAMA_ROW_SPLIT_WEIGHT_LIST = [
>     "self_attn.o_proj.weight",
>     "mlp.down_proj.weight"
> ]
> 
> LLAMA_NO_SPLIT_WEIGHT_LIST = [
>     "input_layernorm.weight",
>     "post_attention_layernorm.weight"
> ]
> 
> LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST = [
>     "lm_head.weight"
> ]
> 
> EMBEDDING_ROW_SPLIT_WEIGHT_LIST = [
>     "llama.embed_tokens.weight"
> ]
> 
> FINAL_NORM_WEIGHT_LSIT = [
>     "llama.norm.weight"
> ]
> 
> def parse_arguments():
>     import argparse
> 
>     parser = argparse.ArgumentParser()
>     parser.add_argument("--model_dir", required=True, help="The directory of model.")
>     parser.add_argument("--output_model_dir", required=True, help="The directory of model.")
>     parser.add_argument("--nranks", type=int, default="1", help="The number of distributed model num. ")
>     return parser.parse_args()
> 
> def col_split(weight, nranks): 
>     return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=1, num_or_sections=nranks)
> 
> def row_split(weight, nranks): 
>     return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=0, num_or_sections=nranks)
> 
> def split_model_weight(model_dir, nranks, output_model_path): 
>     model_state_path = os.path.join(model_dir, "model_state.pdparams")
>     origin_model = paddle.load(model_state_path, return_numpy=True)
>     config = None 
>     with open(os.path.join(model_dir, "config.json"), "r") as f: 
>         config = json.load(f) 
> 
>     for rank_id in range(nranks): 
>         print("Now process rank: ", rank_id)
>         split_state_dict = dict()
>         col_split_lm_head_weight = col_split(origin_model[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
>         row_split_embed_token_weight = row_split(origin_model[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
>         split_state_dict[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]] = col_split_lm_head_weight
>         split_state_dict[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]] = row_split_embed_token_weight
> 
>         for layer_id in range(config["num_hidden_layers"]): 
>             print("Now process LayerIdx: ", layer_id)
>             for column_split_weight_name in LLAMA_COLUMN_SPLIT_WEIGHT_LIST: 
>                 full_column_split_weight_name = "llama.layers.{}.".format(layer_id) + column_split_weight_name
>                 column_split_weight = col_split(origin_model[full_column_split_weight_name], nranks)[rank_id]
>                 split_state_dict[full_column_split_weight_name] = column_split_weight
> 
>             for row_split_weight_name in LLAMA_ROW_SPLIT_WEIGHT_LIST: 
>                 full_row_split_weight_name = "llama.layers.{}.".format(layer_id) + row_split_weight_name
>                 row_split_weight = row_split(origin_model[full_row_split_weight_name], nranks)[rank_id]
>                 split_state_dict[full_row_split_weight_name] = row_split_weight
> 
>             for no_split_weight_name in LLAMA_NO_SPLIT_WEIGHT_LIST: 
>                 full_no_split_weight_name = "llama.layers.{}.".format(layer_id) + no_split_weight_name
>                 split_state_dict[full_no_split_weight_name] = paddle.to_tensor(origin_model[full_no_split_weight_name], place=paddle.CPUPlace())
> 
>         last_norm_weight_name = FINAL_NORM_WEIGHT_LSIT[0]
>         split_state_dict[last_norm_weight_name] = paddle.to_tensor(origin_model[last_norm_weight_name], place=paddle.CPUPlace())
>         paddle.save(split_state_dict, os.path.join(output_model_path, "model_state.tp0{}.pdparams".format(rank_id)))
> 
> if __name__ == "__main__": 
>     args = parse_arguments()
>     split_model_weight(args.model_dir, 
>                        args.nranks, 
>                        args.output_model_dir)
> ```
> 
> 运行：
> 
> ```
> python3.8 split_weight.py \
>             --model_dir=/root/.paddlenlp/models/facebook/llama-65b \
>             --nranks=8 \
>             --output_model_dir=xxxx/split_llama_65b
> ```
> 
> 再将export模型的目录换成切分好模型权重的目录

删除了safetensors文件，重新走了一遍导出，出现如下错误：
ValueError：The feeded_var_names[2]: 'position_ids' doesn't exist in pruned inference program. Please check whether 'position_ids' is a valid feed_var name, or remove it form feeded_var_name if 'position_ids' is not involved in the target_vars calculation.

**Comment by MARD1NO** [comment]
> > > ### bug描述 Describe the Bug
> > > Paddle和PaddleNLP最新develop分支代码，执行导出动态batch模型命令报错，导出命令如下：
> > > ```python
> > > python export_model.py \
> > >     --model_name_or_path facebook/llama-7b \
> > >     --output_path ./inference \
> > >     --dtype float16 \
> > >     --inference_model \
> > >     --max_batch_size 8
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 报错信息：keyError, state_dict里面没有"llama.embed_tokens.weight" key值
> > > ### 其他补充信息 Additional Supplementary Information
> > > _No response_
> > 
> > 
> > 目前推理模型这边使用safetensor类型权重还有一定兼容问题，可以先
> > rm -rf /root/.paddlenlp/models/facebook/llama-65b （一般默认路径是这里）
> > 然后另外写一个下载非safetensor类型的权重脚本运行：
> > ```
> > from paddlenlp.transformers import *
> > 
> > llama = AutoModel.from_pretrained('facebook/llama-65b', use_safetensors=False)
> > llama = AutoTokenizer.from_pretrained('facebook/llama-65b', use_safetensors=False)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再进行转换。
> > 65b权重转换要求内存容量较大，如果内存不够出现OOM，可以先用下面的脚本对权重进行预切分：
> > ```
> > """
> > Author(Zhengzekang):
> > 
> > If we use PaddleNLP to export distributed model by using dy2static directly, 
> > each device will read full model which easily cause OOM. 
> > 
> > This script only use single device to read full model and split model by assigned NRANKS
> > 
> > """
> > 
> > import paddle 
> > import os 
> > import json 
> > 
> > # Define Weight Name List. 
> > LLAMA_COLUMN_SPLIT_WEIGHT_LIST = [
> >     "self_attn.q_proj.weight",
> >     "self_attn.k_proj.weight",
> >     "self_attn.v_proj.weight",
> >     "mlp.gate_proj.weight",
> >     "mlp.up_proj.weight",
> > ]
> > 
> > LLAMA_ROW_SPLIT_WEIGHT_LIST = [
> >     "self_attn.o_proj.weight",
> >     "mlp.down_proj.weight"
> > ]
> > 
> > LLAMA_NO_SPLIT_WEIGHT_LIST = [
> >     "input_layernorm.weight",
> >     "post_attention_layernorm.weight"
> > ]
> > 
> > LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST = [
> >     "lm_head.weight"
> > ]
> > 
> > EMBEDDING_ROW_SPLIT_WEIGHT_LIST = [
> >     "llama.embed_tokens.weight"
> > ]
> > 
> > FINAL_NORM_WEIGHT_LSIT = [
> >     "llama.norm.weight"
> > ]
> > 
> > def parse_arguments():
> >     import argparse
> > 
> >     parser = argparse.ArgumentParser()
> >     parser.add_argument("--model_dir", required=True, help="The directory of model.")
> >     parser.add_argument("--output_model_dir", required=True, help="The directory of model.")
> >     parser.add_argument("--nranks", type=int, default="1", help="The number of distributed model num. ")
> >     return parser.parse_args()
> > 
> > def col_split(weight, nranks): 
> >     return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=1, num_or_sections=nranks)
> > 
> > def row_split(weight, nranks): 
> >     return paddle.split(paddle.to_tensor(weight, place=paddle.CPUPlace()), axis=0, num_or_sections=nranks)
> > 
> > def split_model_weight(model_dir, nranks, output_model_path): 
> >     model_state_path = os.path.join(model_dir, "model_state.pdparams")
> >     origin_model = paddle.load(model_state_path, return_numpy=True)
> >     config = None 
> >     with open(os.path.join(model_dir, "config.json"), "r") as f: 
> >         config = json.load(f) 
> > 
> >     for rank_id in range(nranks): 
> >         print("Now process rank: ", rank_id)
> >         split_state_dict = dict()
> >         col_split_lm_head_weight = col_split(origin_model[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
> >         row_split_embed_token_weight = row_split(origin_model[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]], nranks)[rank_id]
> >         split_state_dict[LM_HEAD_COLUMN_SPLIT_WEIGHT_LIST[0]] = col_split_lm_head_weight
> >         split_state_dict[EMBEDDING_ROW_SPLIT_WEIGHT_LIST[0]] = row_split_embed_token_weight
> > 
> >         for layer_id in range(config["num_hidden_layers"]): 
> >             print("Now process LayerIdx: ", layer_id)
> >             for column_split_weight_name in LLAMA_COLUMN_SPLIT_WEIGHT_LIST: 
> >                 full_column_split_weight_name = "llama.layers.{}.".format(layer_id) + column_split_weight_name
> >                 column_split_weight = col_split(origin_model[full_column_split_weight_name], nranks)[rank_id]
> >                 split_state_dict[full_column_split_weight_name] = column_split_weight
> > 
> >             for row_split_weight_name in LLAMA_ROW_SPLIT_WEIGHT_LIST: 
> >                 full_row_split_weight_name = "llama.layers.{}.".format(layer_id) + row_split_weight_name
> >                 row_split_weight = row_split(origin_model[full_row_split_weight_name], nranks)[rank_id]
> >                 split_state_dict[full_row_split_weight_name] = row_split_weight
> > 
> >             for no_split_weight_name in LLAMA_NO_SPLIT_WEIGHT_LIST: 
> >                 full_no_split_weight_name = "llama.layers.{}.".format(layer_id) + no_split_weight_name
> >                 split_state_dict[full_no_split_weight_name] = paddle.to_tensor(origin_model[full_no_split_weight_name], place=paddle.CPUPlace())
> > 
> >         last_norm_weight_name = FINAL_NORM_WEIGHT_LSIT[0]
> >         split_state_dict[last_norm_weight_name] = paddle.to_tensor(origin_model[last_norm_weight_name], place=paddle.CPUPlace())
> >         paddle.save(split_state_dict, os.path.join(output_model_path, "model_state.tp0{}.pdparams".format(rank_id)))
> > 
> > if __name__ == "__main__": 
> >     args = parse_arguments()
> >     split_model_weight(args.model_dir, 
> >                        args.nranks, 
> >                        args.output_model_dir)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 运行：
> > ```
> > python3.8 split_weight.py \
> >             --model_dir=/root/.paddlenlp/models/facebook/llama-65b \
> >             --nranks=8 \
> >             --output_model_dir=xxxx/split_llama_65b
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 再将export模型的目录换成切分好模型权重的目录
> 
> 删除了safetensors文件，重新走了一遍导出，出现如下错误： ValueError：The feeded_var_names[2]: 'position_ids' doesn't exist in pruned inference program. Please check whether 'position_ids' is a valid feed_var name, or remove it form feeded_var_name if 'position_ids' is not involved in the target_vars calculation.

麻烦更新下PaddleNLP，上午有一个修复PR合入：https://github.com/PaddlePaddle/PaddleNLP/pull/6906/files#diff-54cf6f74a225a355c5f4d338183dccd32f49254f1980d788447cb4dd5c9e27fcR84-R86
