### ISSUE TITLE
Auto_parallel 现阶段是否只支持静态图？

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/Paddle#56948]
### 请提出你的问题 Please ask your question

https://github.com/PaddlePaddle/Paddle/blob/abf7af224903f75cfa6613e5efd9221789460333/python/paddle/distributed/auto_parallel/static/engine.py#L59-L60
根据注释auto_parallel engine应当能支持动态图和静态图，但现阶段看`python/paddle/distributed/auto_parallel/dygraph`下为空，请问是否可以支持动态图？

**Comment by JZ-LIANG** [comment]
auto parallel 目前只支持静态图；动态图的auto parallel 目前正在开发（预计 Paddle2.6 会发布 early release 版本）。

engine 是一个高阶的API，这里的 『 support the dynamic graph and static graph』原本的意思是：

- 支持纯静态图组网 + engine 运行 auto parallel
- 支持动静态图组网 + 动转静 + engine 运行 auto parallel

感谢你指出的问题，我们后面会完善文档。

**Comment by jinyouzhi** [comment]
> auto parallel 目前只支持静态图；动态图的auto parallel 目前正在开发（预计 Paddle2.6 会发布 early release 版本）。
> 
> engine 是一个高阶的API，这里的 『 support the dynamic graph and static graph』原本的意思是：
> 
> * 支持纯静态图组网 + engine 运行 auto parallel
> * 支持动静态图组网 + 动转静 + engine 运行 auto parallel
> 
> 感谢你指出的问题，我们后面会完善文档。

感谢解惑！
