### ISSUE TITLE
ExternalError: CUBLAS error(7).    cuda安装报错，pip 安装后没有显示cuda和cudnn版本，也报错

### ISSUE THREAD

**Issue by hanlaoshi** [PaddlePaddle/Paddle#56950]
### bug描述 Describe the Bug

ExternalError: CUBLAS error(7). 
      [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/backends/gpu/gpu_context.cc:599)
      [operator < matmul_v2 > error]
cuda安装报错，pip 安装后没有显示cuda和cudnn版本，也报错，请问该如何处理。
环境：
系统cuda==11.4;

conda虚拟环境：
 python=3.9.0; 

 conda命令安装paddle： conda install paddlepaddle-gpu==2.5.1 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

安装完成后测试：paddle.utils.run_check()

显示：ExternalError: CUBLAS error(7). 
      [Hint: 'CUBLAS_STATUS_INVALID_VALUE'.  An unsupported value or parameter was passed to the function (a negative vector size, for example). To correct: ensure that all the parameters being passed have valid values. ] (at ../paddle/phi/backends/gpu/gpu_context.cc:599)
      [operator < matmul_v2 > error]

重新新建一个conda虚拟环境，使用pip安装：
命令：python3 -m pip install paddlepaddle-gpu==2.5.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html

FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1693876677 (unix time) try "date -d @1693876677" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0x3f10025a141) received by PID 2466113 (TID 0x7fba2784d280) from PID 2466113 ***]

Aborted (core dumped)

请问到底该如何安装paddle的gpu版本？

**Comment by zhengqiwen1997** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html 
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/linux-conda.html
请按照文档要求步骤进行安装，可能是cuda和cudnn版本不符合，建议用cuda11.2进行安装

**Comment by hanlaoshi** [comment]
> 



> https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html https://www.paddlepaddle.org.cn/documentation/docs/zh/install/conda/linux-conda.html 请按照文档要求步骤进行安装，可能是cuda和cudnn版本不符合，建议用cuda11.2进行安装

你好，我就是按照文档要求操作的。在新的conda虚拟环境下，直接使用conda安装出现错误，详情请阅读我上述内容。系统cuda版本是11.4，驱动：470.74；显卡是3090；无论是pip还是conda安装均报错

**Comment by zhengqiwen1997** [comment]
可以尝试cuda版本更换为cuda11.2，配合 cuDNN v8.2.1
