### ISSUE TITLE
[Custom Device]内存Free回收问题

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#56969]
### bug描述 Describe the Bug

通过目前的capi或paddle_inference
没有发现device_memory_deallocate的触发机会。

查询源码
发现[paddle/fluid/memory/allocation/custom_allocator.cc](https://github.com/PaddlePaddle/Paddle/blob/be9cb946e507832f9c0fe5fc1d0f5343f1da08b9/paddle/fluid/memory/allocation/custom_allocator.cc)
```cpp
void CustomAllocator::FreeImpl(phi::Allocation* allocation) {
  PADDLE_ENFORCE_EQ(
      allocation->place(),
      place_,
      platform::errors::PermissionDenied("CustomDevice memory is "
                                         "freed in incorrect device. "
                                         "This may be a bug"));

  delete allocation;
}
```

只有一个delete allocation;
delete allocation; 不会触发任何事件，只有一个空的析构函数

所以如何能在custom device上回收内存？
@ronny1996

**Comment by engineer1109** [comment]
@ronny1996

**Comment by engineer1109** [comment]
```cpp
auto x = paddle::experimental::empty({1, 2, 3, 4}, paddle::DataType::FLOAT32);
```
只有分配没有释放

**Comment by ronny1996** [comment]
感谢反馈，这个pr将修复该问题 https://github.com/PaddlePaddle/Paddle/pull/56977

**Comment by ccsuzzh** [comment]
> 感谢反馈，这个pr将修复该问题 #56977

研发大哥有成功复现这个问题吗？我尝试在paddle_inference使用这个API复现这个问题，Custom Device中正常free的。

**Comment by engineer1109** [comment]
@ccsuzzh  他PR已经合入了。有效。
验证 删除Predictor 或  TryShrinkMemory

**Comment by engineer1109** [comment]
Fixed
