### ISSUE TITLE
paddle对应torch中torch.cfloat数据类型缺失

### ISSUE THREAD

**Issue by zlynna** [PaddlePaddle/Paddle#56988]
### 需求描述 Feature Description

在复现论文Physics-informed neural operator for learning part的过程中, Fourier Neural Operator 网络在原pytorch代码环境中涉及到fft的网络训练参数的数据类型为torch.cfloat，paddle.create_parameter不支持cfloat，即complex64数据类型，请问是否可以在paddle中实现对该数据类型的支持？

**Comment by wanghuancoder** [comment]
你好，你可以直接传入dtype="complex64"

**Comment by wangguan1995** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/39621324/e2e9e1ad-a01b-40e5-a35f-f94e250dff19)

**Comment by wangguan1995** [comment]
> ![image](https://user-images.githubusercontent.com/39621324/284169654-e2e9e1ad-a01b-40e5-a35f-f94e250dff19.png)

    weight = paddle.randn([32, 32, 8, 8]).astype("complex64")
    weight = paddle.create_parameter(weight.shape, weight.dtype, attr=paddle.nn.initializer.Assign(weight))
