### ISSUE TITLE
【quick start】中训练模型配置use_gpu=1时，训练出core

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#570]
【quick start】中训练模型配置use_gpu=1时，训练出core。
![image](https://cloud.githubusercontent.com/assets/12882811/20552345/f4f3c65a-b184-11e6-9021-241a0c334201.png)

**Comment by gangliao** [comment]
`trainer_count * num_devices_in_model (4*1)=4 exceeds number of GPU devices(1)`

It looks like you do not have 4 GPU devices. Maybe you can change `--trainer_count=4` to the correct number of devices. 

@hedaoyuan

**Comment by beckett1124** [comment]
我只选择一个GPU训练模型呢？
paddle train \
  --config=$cfg \
  --save_dir=./output \
  --trainer_count=4 \
  --log_period=100 \
  --num_passes=15 \
  --use_gpu=1\
  --show_parameter_stats_period=100 \
  --test_all_data_in_one_period=1 \
  2>&1 | tee 'train.log'

他为啥依然去计算4个GPU，我如何指定GPU的id或者GPU的数目呢？

**Comment by gangliao** [comment]
@beckett1124 
Please check the end of this doc: http://www.paddlepaddle.org/doc/ui/cmd_argument/use_case.html  

It includes all information you need.

**Comment by hedaoyuan** [comment]
> 为啥依然去计算4个GPU？

把--trainer_count=4 修改成--trainer_count=1

**Comment by beckett1124** [comment]
嗯，--trainer_count=1 是ok的。
