### ISSUE TITLE
多个GPU加速没有预期效果

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#5700]
问题：在单机上使用多个GPU加速任务，结果速度和单GPU速度差不多。
细节：  
```python
train_reader = paddle.batch(
            paddle.reader.shuffle(paddle.reader.buffered(
                reader.train_reader(train_data_dir, word_dict, l1_dict, lbl_dict),
                1000000),buf_size=10000),
            batch_size=1000)
paddle.init(use_gpu=True, trainer_count=5)
```
使用了1000000的buff和1000的batch_size，5个GPU，结果每个GPU使用率最高只有40%，大部分是20%-30%，而且每次刷新经常有几个是0%。如下图所示，其中6，7，9，10，11是我使用的GPU。内存也没有沾满。
![image](https://user-images.githubusercontent.com/4252318/32881760-db69aa12-ca77-11e7-952f-9b2be90393ce.png)

**Comment by wanghaoshuang** [comment]
可能瓶颈在你的data reader, 建议你用[python profile](https://docs.python.org/2/library/profile.html)分析下哪一步比较耗时。
