### ISSUE TITLE
paddle在线infer加载保存的模型出错

### ISSUE THREAD

**Issue by mojingcj** [PaddlePaddle/Paddle#57009]
### 请提出你的问题 Please ask your question

![0b8b43f6b9e0399fd1e1556b6](https://github.com/PaddlePaddle/Paddle/assets/48461688/399d20fc-9ef3-4dc4-abc3-73c7564aa672)
在线infer加载模型失败，报错Can't parse message ProgramDesc because it is missing required fields: blocks[0].ops[32].attrs[17].type...

**Comment by Wangzheee** [comment]
请问使用的是什么版本的paddle、使用什么方式保存的模型呢？
请问使用什么版本的paddle infer这个模型呢？

**Comment by mojingcj** [comment]
> 

paddle2.3训练模型，jit保存模型；paddle2.0 infer模型

**Comment by TingquanGao** [comment]
是静态图训练吗？看起来是保存的模型中找不到部分参数名。可以加载保存的模型文件，打印看一下有多少参数。

**Comment by Wangzheee** [comment]
> > 
> 
> paddle2.3训练模型，jit保存模型；paddle2.0 infer模型

建议都使用最新的版本试试呢 https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html
