### ISSUE TITLE
numpy类型转paddle tensor速度慢

### ISSUE THREAD

**Issue by ZTurboX** [PaddlePaddle/Paddle#57000]
### 请提出你的问题 Please ask your question

在cpu下，numpy类型用paddle.to_tensor转tensor耗时较长

**Comment by TingquanGao** [comment]
复现代码可以贴下吗？

**Comment by ZTurboX** [comment]
> 复现代码可以贴下吗？

加了参数，速度变快了。
之前是paddle.to_tensor(prediction_scores)
加上几个参数后paddle.to_tensor(prediction_scores, dtype="float32",  place=paddle.CPUPlace(), stop_gradient=True)变快了
prediction_scores是numpy类型

**Comment by TingquanGao** [comment]
收到，我们试下。

**Comment by zhwesky2010** [comment]
@ZTurboX 你执行这个时：`paddle.to_tensor(prediction_scores)` ，是不是拷贝到默认的设备GPU了？麻烦截下图看下

**Comment by ZTurboX** [comment]
> @ZTurboX 你执行这个时：`paddle.to_tensor(prediction_scores)` ，是不是拷贝到默认的设备GPU了？麻烦截下图看下

CPU下执行的，需要截图代码吗

**Comment by zhwesky2010** [comment]
@ZTurboX 加的这几个参数只有 `place=paddle.CPUPlace()` 和性能有点关系，但是你说本地就是CPU的，所以加了这几个参数对性能应无任何影响。你可以再排查下是不是有什么其他问题，或者将一些首次初始化的时间算到`paddle.to_tensor`这个API里了
