### ISSUE TITLE
pip installed failed

### ISSUE THREAD

**Issue by ckeys** [PaddlePaddle/Paddle#5701]
Hi All,

When I try to install paddlepaddle, the terminal always shows that Could not find a version that satisfies the requirement paddlepaddle <from versions>.
No matching distribution found for paddlepaddle.

I tried to install the paddlepaddle in different devices, and all of them are not successful. Is there anybody meet the similar problem? and how to solve the issue?

Thanks,

**Comment by wanghaoshuang** [comment]
Can you paste some detail error log?

**Comment by lqsheng** [comment]
![screenshot from 2017-11-19 18-30-50](https://user-images.githubusercontent.com/25112740/32990364-616938b0-cd63-11e7-8fc9-9a2c4e79f29b.png)
I get the same error

**Comment by lqsheng** [comment]
@wanghaoshuang

**Comment by typhoonzero** [comment]
Please refer to FAQ for encountering different platform installation issues: 

https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/build_and_install/index_cn.rst#paddlepaddle-whl-is-not-a-supported-wheel-on-this-platform

**Comment by pkuyym** [comment]
This problem is probably solved, however there is no feedback from the user,  please feel free to reopen it if necessary.

**Comment by PariksheetPinjari909** [comment]
Use sudo. It worked for me.

**Comment by belomeriem** [comment]
I have the same problem. I can't pip PaddlePaddle. Also, the link posted here by typhoonzero does not exist anymore. Thanks. 
<img width="841" alt="screen shot 2018-04-19 at 1 29 17 pm" src="https://user-images.githubusercontent.com/6345293/38989041-c8e7fef2-43d5-11e8-9460-db4c8d08bf20.png">
