### ISSUE TITLE
2.5.1 gpu版本配合paddleocr只有cuda10.2能识别数据

### ISSUE THREAD

**Issue by jackieZhouQQ** [PaddlePaddle/Paddle#57035]
### bug描述 Describe the Bug

gpu ：1070
paddle-gpu版本 2.5.1
paddleocr版本  2.7.0.2
操作系统  windows11

测试过各个版本的cuda和对应的paddle版本，只有cuda10.2 ocr才能正常识别，其他版本的cuda，gpu识别结果都为空。

更换paddle-gpu版本为2.4.2后，各个cuda版本ocr都识别正常，感觉是新版本的paddle跟老设备兼容性不好？

**Comment by tink2123** [comment]
测试了 paddle2.5.1 + cuda11.2 可以正式识别，可以提供一个您这边有问题的环境，除了结果为空之外有什么报错信息吗？

**Comment by jackieZhouQQ** [comment]
除了结果为空之外没有任何报错，ocr的det部分就是检测到0个文本框。详细环境 windows11 22621，显卡1070，显卡驱动537.13

**Comment by tink2123** [comment]
请问是参考官方命令安装不同 cuda 版本的paddle吗：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html

例如 cuda11.6:
```
python -m pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

**Comment by jackieZhouQQ** [comment]
> 请问是参考官方命令安装不同 cuda 版本的paddle吗：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/linux-pip.html
> 
> 例如 cuda11.6:
> 
> ```
> python -m pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
> ```

是的

**Comment by vivienfanghuagood** [comment]
https://www.paddlepaddle.org.cn/inference/master/api_reference/python_api_doc/Predictor.html 可以参考这个链接，使用debug工具打印下中间结果，看下哪个算子开始出现了不符合预期的输出
