### ISSUE TITLE
Paddle Inference 对于Custom Device如何同时应用IR优化和混精度推理？

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/Paddle#57049]
### 请提出你的问题 Please ask your question

目前，参考#52038，GPU和Custom Device都以设备接口参数控制精度（且以单独一条IR auto_mixed_precision_pass 方式实现？），请问如何两种优化是否可以同时使用？
* 如何为custom device加入自定义pass
* 通过向pass_builder注入自定义pass可以使ir生效，但与混精度互斥
  * 打开混精度时（c），无法应用ir优化（a无效）
  * 尝试在a处把混精度IRauto_mixed_precision_pass 与自定义的pass一并传入，能看到run IR的log信息却没有见到amp生效

```python
        config = paddle.inference.Config(self.model_file, self.param_file)

        config.enable_memory_optim()
        config.switch_ir_optim(True)
        # Append custom pases into pass_builder
        if self.custom_passes and isinstance(self.custom_passes, list):
            pass_builder = config.pass_builder()
            for custom_pass in self.custom_passes:
                pass_builder.append_pass(custom_pass)                                             # a引入自定义pass
            print(pass_builder.all_passes())
        if self.device:
            device_id = int(
                os.environ.get(f'FLAGS_selected_{self.device}s', 0))
            config.enable_custom_device(self.device, device_id)                                       # b关闭混精度
            config.enable_custom_device(self.device, device_id, paddle.inference.PrecisionType.Half)  # c打开混精度
```

**Comment by ronny1996** [comment]
把c提到a之前即可，这个问题应该已经修复了 https://github.com/PaddlePaddle/Paddle/pull/56755

**Comment by TingquanGao** [comment]
@jinyouzhi 可以参考上面的方法解决，该issue先close了，如仍有问题可以再继续回复~

**Comment by jinyouzhi** [comment]
> 把c提到a之前即可，这个问题应该已经修复了 https://github.com/PaddlePaddle/Paddle/pull/56755

我注意到先前issue和pr，cherrypick后放在前面后面其实都试过不行。
https://github.com/jinyouzhi/Paddle/commit/f157f2b3cce273fabd24a8c5cb5e41f90341928f
不知道这里是不是有问题，custom混精度仍然会reset
@TingquanGao @ronny1996 感谢回复
