### ISSUE TITLE
Need to cherry-pick FSDP-related PRs to paddle2.5

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#57059]
### 请提出你的问题 Please ask your question

When tesing DP+FSDP+TP+PP using PaddleNLP, we found that FSDP has poor compatibility with DP/TP/PP, refer to https://github.com/PaddlePaddle/PaddleNLP/issues/6938.

I noticed that some of the issues have been fixed in paddle develop branch. We need to find all the PRs for these fixes and cherry-pick them into NGC Paddle, which is based on paddle 2.5.

We got 3 issues currently, see full error log in https://github.com/PaddlePaddle/PaddleNLP/issues/6938:

1. `dygraph_sharding_optimizer has no attribute 'reduce_gradients'`
    - Fixed in [PR#54634](https://github.com/PaddlePaddle/Paddle/pull/54634), need to cherry-pick to 2.5
2. `pipeline parallel is not compatible for sharding stage2 or stage3, please using sharding stage1`
    - ~~Not sure if it has been fixed.~~ Low priority
3. `AssertionError: sharding stage1 can not coexist with dp for now`
    - ~~Not sure if it has been fixed.~~ Fixed in [PR#55601](https://github.com/PaddlePaddle/Paddle/pull/55601), need to cherry-pick to 2.5

**Comment by Wong4j** [comment]
@sneaxiy Could you please take a look?

**Comment by Wong4j** [comment]
第一个问题，麻烦帮我们提供需要cherry-pick的PR。
后面两个问题不知道框架侧是否有解决，我们做Transformer Engine跟PaddleNLP的集成，后期将会需要测试DP+FSDP+TP+PP的不同组合，但目前可测试的组合很少。

**Comment by Wong4j** [comment]
@sneaxiy 更新一下issue，麻烦帮忙将FSDP功能相关的PR cherry-pick到2.5，或者提供一份list我们自己来cherry-pick

**Comment by liuzhenhai93** [comment]
> @sneaxiy 更新一下issue，麻烦帮忙将FSDP功能相关的PR cherry-pick到2.5，或者提供一份list我们自己来cherry-pick

@Wong4j 我这边已经修了，麻烦您把你的测试脚本给一下；
或者是您测试一下？https://github.com/PaddlePaddle/Paddle/pull/57776/files;
if any problem, feel free to contact me.

**Comment by Wong4j** [comment]
@liuzhenhai93 感谢，我会做测试然后反馈给您

**Comment by Wong4j** [comment]
已经测试过，可以跑了。先关掉这个issue
