### ISSUE TITLE
paddle.to_tensor如何单机多卡上使用

### ISSUE THREAD

**Issue by 0x0C001** [PaddlePaddle/Paddle#57055]
paddle.to_tensor如何单机多卡上使用

**Comment by mlpod** [comment]
import paddle
paddle.device.set_device("gpu")
# 首先获取当前的GPU id
current_rank = paddle.distributed.get_rank()
# 根据当前的GPU id将张量放到相应的设备上
labels = paddle.to_tensor([[3], [2], [1], [0]], place=paddle.CUDAPlace(current_rank))
label_map = paddle.to_tensor([0.0, 0.85 , 0.95, 1.0], place=paddle.CUDAPlace(current_rank))
print(label_map[labels])
