### ISSUE TITLE
需要downgrade找2.4.2版本支持cudnn的Paddle

### ISSUE THREAD

**Issue by ZhengyuXia** [PaddlePaddle/Paddle#57050]
### 请提出你的问题 Please ask your question

Hi, 最近在尝试复现RTFormer，系统配置为

System: Ubuntu 18.04
Cuda: 11.8
Cudnn: 8.6.0.163
NCCL: 2.15.5

可是在成功安装完最新的PaddlePaddle-2.5.1的时候，训练讯息一直报出大量warning ”eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' .“ 经查证后，得知可以通过降低Paddle版本来解决该问题，可是目前Paddle-2.4.2支持Cudnn的版本似乎已被官方下架，只有纯支持cuda的2.4.2版本，请问哪里可以找到2.4.2版本的Paddle with Cudnn的下载方式？

当前Paddle with Cudnn，可以看到只有2.5.0和2.5.1版本。
https://www.paddlepaddle.org.cn/whl/linux/cudnnin/stable.html

感谢！

**Comment by will-jl944** [comment]
> 训练讯息一直报出大量warning ”eager_method.cc:140] Warning:: 0D Tensor cannot be used as 'Tensor.numpy()[0]' .“

该警告信息为Paddle支持0-D Tensor机制引入的，可以通过设置环境变量`export FLAGS_set_to_1d=0`关闭。

**Comment by ZhengyuXia** [comment]
@will-jl944 这个方法，在先前的帖子中已经被提及并且尝试过，但是训练是直接报错了，以下是错误代码

```python
  File "tools/train.py", line 195, in <module>
    main(args)
  File "tools/train.py", line 190, in main
    to_static_training=cfg.to_static_training)
  File "/home/mmcom/PaddleSeg/paddleseg/core/train.py", line 273, in train
    avg_loss_list = [l[0] / log_iters for l in avg_loss_list]
  File "/home/mmcom/PaddleSeg/paddleseg/core/train.py", line 273, in <listcomp>
    avg_loss_list = [l[0] / log_iters for l in avg_loss_list]
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed
```

**Comment by will-jl944** [comment]
可以选择如下方案之一：

**Comment by will-jl944** [comment]
可以选择如下方案之一：

1. 给PaddleSeg提issue确认是否已经适配PaddlePaddle 2.5。如果尚未适配是否有办法通过修改PaddleSeg源码快速适配。
2. 安装旧版本PaddlePaddle。旧版本安装见https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/compile/linux-compile-by-ninja.html 。由于2.4版本未提供CUDA11.8对应的包，可以选择自行编译（https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html）或者降级CUDA。

**Comment by ZhengyuXia** [comment]
感谢回复。

为了使用PaddlePaddle v2.4.2 多卡版本，先downgrade了CUDA版本至11.6，同时安装相应的CUDNN和NCCL，并将PaddleSeg从v2.8降低到了v2.7，方才使得RTFormer从training到validation都正常运作。

BTW，PaddlePaddle官网英文版本似乎没有旧版本安装的页面？起初在英文版页面找了许久也未找到。

**Comment by xlg-go** [comment]
> 可以选择如下方案之一：
> 
> 1. 给PaddleSeg提issue确认是否已经适配PaddlePaddle 2.5。如果尚未适配是否有办法通过修改PaddleSeg源码快速适配。
> 2. 安装旧版本PaddlePaddle。旧版本安装见https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/compile/linux-compile-by-ninja.html 。由于2.4版本未提供CUDA11.8对应的包，可以选择自行编译（[https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html）或者降级CUDA。](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/fromsource.html%EF%BC%89%E6%88%96%E8%80%85%E9%99%8D%E7%BA%A7CUDA%E3%80%82)

改改下载链接，就能下载对应的包了
