### ISSUE TITLE
CustomDevice配置时import paddle出现runtime error后是否需要终止程序运行

### ISSUE THREAD

**Issue by zhjc** [PaddlePaddle/Paddle#57071]
### 请提出你的问题 Please ask your question

1、Custom Device（NPU）配置下，也就是基于以下命令安装Paddle和PaddleCustomDevice
```
cmake .. -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_CUSTOM_DEVICE=ON -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=ON
make TARGET=ARMV8 -j

# paddlecustomdevice
cd backends/npu
bash tools/compile.sh
```
2、执行import paddle不开日志打印时运行正常，但是程序fallback到CPUPlace执行

3、打开日志`export GLOG_v=6`时发现以下报错，但是程序也是照常fallback到CPUPlace
runtime error：Invalid enum backend type ‘10’  （paddle/phi/common/common.h文件118行）

此处有个疑问，import阶段的runtime是不是需要直接终止程序？否则是非预期流程，增加定位困难

**Comment by engineer1109** [comment]
enum 10 应该是Paddle CustomDevice的backend值。
有些enforce声明的方式 有问题。 Paddle CustomDevice的BackEnd记得是>9的值，会根据custom的种类叠加上去。
Paddle的一些代码可能有问题。对Custom Device的值判断出现失误。

**Comment by YanhuiDua** [comment]
应该是paddle和paddlecustomdevice的版本没有对齐，可以提供下paddle和paddlecustomdevice的版本号和commit号
