### ISSUE TITLE
sparse_vector_sequence vs dense_vector_sequence

### ISSUE THREAD

**Issue by alvations** [PaddlePaddle/Paddle#571]
When adding the `settings.slots` in the `hook()` function of `dataprovider.py`, is it right that both the `dense_vector_sequence()` and `sparse_vector_sequence` input must be a matrix (i.e. list of lists of floats)?

Is it right that for `sparse_vector_sequence()`, I can have `None` in my inner list, e.g.:

```
[ [0.1, 0.2, 0.2], [0.4, None, None] ]
```

But for `dense_vector_sequence()`, I cannot have `None` in my inner list and I have to fill them up with zeros, i.e.:

```
[ [0.1, 0.2, 0.2], [0.4, 0.0, 0.0] ]
```

**Is that the difference in the sparse and dense vector sequence in Paddle?**

**Comment by backyes** [comment]
@reyoung 请帮忙给出comments

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#input-types
- dense_vector 表示稠密的浮点数向量。
- sparse_binary_vector 表示稀疏的零一向量，即大部分值为0，有值的位置只能取1
- sparse_float_vector 表示稀疏的向量，即大部分值为0，有值的部分可以是任何浮点数

所以dense不能有None，sparse可以有None

**Comment by alvations** [comment]
@luotao1 Thanks for the explanation and the link to the docs!

> 所以dense不能有None，sparse可以有None

如果方便的话，这段因该添补进http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#input-types =）

**Comment by luotao1** [comment]
待补充进pydataprovider2的文档中。

**Comment by luotao1** [comment]
@alvations 抱歉，上面的回答有错误，sparse和dense都不能有None，两者的区别在于他们的输入格式不一样。具体格式可以看 http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#input-types

**Comment by alvations** [comment]
@luotao1 了解了，无论是sparse或dense都不能有None. 那从numpy输入的vector都得添上分值0。

**Comment by luotao1** [comment]
> 那从numpy输入的vector如有None都得添上分值0。

您的理解有点偏差。sparse存的是不为0的那些index值。比如：

- 对NO_SEQUENCE的sparse_binary_vector	，其格式是 [i, i, ...]。假设长度为9，只有index=1、3、5、7时，值为1，那么我们存的是[1, 3, 5, 7]。
- 对NO_SEQUENCE的sparse_float_vector，其格式是[(i,f), (i,f), ...]。假设长度为9，只有index=1、3、5、7时，值为0.5，那么我们存的是[(1, 0.5),  (3, 0.5), (5, 0.5), (7, 0.5)]。

**Comment by alvations** [comment]
啊！我这下子应该了解了。如果是浮值`dense_vector[0.0, 0.5, 0.0, 0.5, 0.0, 0.7])`也能转成 `sparse_float_vector([(1,0.5), (3,0.5), (5, 0.7)]`对吗？但是我得按照数据的稀疏或稠密度适当的设定slot为dense_vector 或 sparse_float_vector对吗？

**Comment by luotao1** [comment]
@alvations 是的

**Comment by alvations** [comment]
@luotao1 多谢了！
