### ISSUE TITLE
模型库-图像分类的怎么20条数据的时候可以 八十多条数据的时候内核就重启了？求指教

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5710]
http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html
数据是自定义的

**Comment by qingqing01** [comment]
> 20条数据的时候可以; 80多条数据

这个是总共的训练集呢，还是batch size呢？ 请问是Docker运行吗？有可能是内存不够吗？有具体的错误信息吗？

**Comment by 466821202** [comment]
内存是32G的   是训练集数据就二三十张图片可以 再多就内核重启了！

**Comment by 466821202** [comment]
我刚看了是内存不够了,内存可以通过那些参数调整一下呢！
    optimizer = paddle.optimizer.Momentum(
        momentum=0.9,
        regularization=paddle.optimizer.L2Regularization(rate=0.0005 *
                                                         BATCH_SIZE),
        learning_rate=learning_rate / BATCH_SIZE,
        learning_rate_decay_a=0.1,
        learning_rate_decay_b=128000 * 35,
        learning_rate_schedule="discexp", )

**Comment by yeyupiaoling** [comment]
@466821202 BATCH_SIZE 是什么来的，`learning_rate_decay_b=128000 * 35`这有什么用的，
