### ISSUE TITLE
Arm架构 openeuleros-22.3系统下，paddle plugin无法正常编译使用

### ISSUE THREAD

**Issue by cqli0905** [PaddlePaddle/Paddle#57121]
### 请提出你的问题 Please ask your question

1. 系统信息：
   执行uname -a，得到结果为：5.10.0-153.12.0.92.oe2203sp2.aarch64 #1 SMP Wed Jun 28 23:18:48 CST 2023 aarch64 aarch64 aarch64 GNU/Linux ；操作系统版本为openeuleros-22.3
2. python版本为 3.9.9
3. 先编译paddle，编译命令为： cmake .. -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=ON -DCMAKE_CXX_FLAGS="-Wno-error -w" && make TARGET=ARMV8 -j64
   然后编译paddle plugin
   在custom device 上执行abs算子，报错

![image](https://github.com/PaddlePaddle/Paddle/assets/141985065/317bee50-e075-49fc-9bb4-51e1f07f927f)

进行gdb，得到如下信息
![image](https://github.com/PaddlePaddle/Paddle/assets/141985065/d2adecaa-085d-462a-b5c2-1996d7396562)

**Comment by USTCKAY** [comment]
编译paddle时加上`-DWITH_CUSTOM_DEVICE=ON `试试
