### ISSUE TITLE
支持AMD显卡在windows平台使用Rocm加速训练

### ISSUE THREAD

**Issue by ruixu2** [PaddlePaddle/Paddle#57152]
### 需求描述 Feature Description

AMD最近发布了支持windows10和11的HIP SDK，宣称支持部分7000和6000消费显卡。

在windows平台，paddle不知能否在A卡上实现类似N卡安装cuda，cudnn和paddle的cuda gpu版本，使用显卡训练加速的效果。

**Comment by LiYuRio** [comment]
是想用amd的显卡来支持训练吗，如果这个，paddle是支持的，

**Comment by ruixu2** [comment]
> 是想用amd的显卡来支持训练吗，如果这个，paddle是支持的，

举个例子，使用AMD 7900XTX在windows安装paddle gpu版本进行网络的训练。

目前是无法实现的，需要使用linux系统

**Comment by ronny1996** [comment]
你好，paddle不支持在windows下使用rocm，如果你需要该功能，可以尝试自己使用PaddleCustomDevice在window下接入rocm
