### ISSUE TITLE
Custom Device版本检测需求

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#57162]
### 需求描述 Feature Description

任务目标：
Custom Device像CUDA一样实现版本检测<br /> 
需求场景
加载Cumtom Device库时发现，因为paddle中对于`dlopen`函数用了[RTLD_NOW](https://github.com/PaddlePaddle/Paddle/blob/3c19d80ad6f4bf942a7e6f09e69f5fc7211f23b6/paddle/fluid/platform/init.cc#L149)，导致当库加载错时会直接报错，比如符号链接找不到这种。
但是加载CUDA库时，无论版本都能加载，这上面用了[RTLD_LAZY | RTLD_LOCAL](https://github.com/PaddlePaddle/Paddle/blob/3c19d80ad6f4bf942a7e6f09e69f5fc7211f23b6/paddle/phi/backends/dynload/dynamic_loader.cc#L260C23-L260C23)，方便后面做进一步检查。
<br /> 
功能描述
是否能仿照CUDA加载库的方法，提供自定义检查Custom Device的版本方法

**Comment by ronny1996** [comment]
您好，请问是对CustomDevice版本检查有什么需求吗？这个我们后面改一下， 您也可以自己提PR哈😊

**Comment by zepingWww** [comment]
> 您好，请问是对CustomDevice版本检查有什么需求吗？这个我们后面改一下， 您也可以自己提PR哈😊

其实我们只需要保证，加载时的custom device库和编译时的custom device库不一致能不报错就行了，就是能把RTLD_NOW改成RTLD_LAZY | RTLD_LOCAL

**Comment by zepingWww** [comment]
> 您好，请问是对CustomDevice版本检查有什么需求吗？这个我们后面改一下， 您也可以自己提PR哈😊

那我后面有空自己提PR哈，先关了，后面提了关联一下
