### ISSUE TITLE
Go语言生态完善

### ISSUE THREAD

**Issue by caitou2019** [PaddlePaddle/Paddle#57188]
### 需求描述 Feature Description

任务目标:
实现Go语言目标检测, 目标跟踪等例子
需求场景:
Go编译型语言, 运行速度快, 语法简洁, 增快项目部署上线, 结合了C++的速度优势与python的简洁度

**Comment by Bobholamovic** [comment]
你好，实际上Paddle支持Go语言部署，请参考这个文档：https://www.paddlepaddle.org.cn/inference/master/guides/quick_start/go_demo.html
