### ISSUE TITLE
The usage for CUDA_ARCH and NVCC

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/Paddle#572]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by gaoshan2006** [comment]
There is NVCC flag for conditional compilation, such as in hl_gpu_matrix_kernel.cuh.  I have checked the cmake files and CMakelists.txt,  It looks the NVCC would be enabled  only when the "With_GPU" option is used.  Meanwhile, I also see another conditional compilation   __CUDA_ARCH__  in hl_matrix_base.cuh, and __CUDA_ARCH__  is always set in flags.cmake.    I thought  NVCC as for GPU usages,   and CUDA_ARCH for CUDA functions. If so,  the SSE3 and AVX2 code logic would not really take effect if I build a version for GPU or CUDA , right ? Thanks

**Comment by hedaoyuan** [comment]
1. `__NVCC__` used to distinguish whether this file is compiled by nvcc.
2. `__CUDA_ARCH__` used to distinguish which are the GPU code. In a .cu file which can contain both CPU and GPU code. 
3. SSE and AVX  code logic in the GPU version  is also effective. `__NVCC__` and` __CUDA_ARCH__` macros do not affect the compilation of SSE or AVX code logic. And `WITH_GPU` and `WITH_AVX` are two independent options in the cmak.
