### ISSUE TITLE
[FleetX] PaddleFleetX 的导出阶段大量显存占用问题和如何保存低精度模型

### ISSUE THREAD

**Issue by jinyouzhi** [PaddlePaddle/Paddle#57214]
### 请提出你的问题 Please ask your question

在参考https://github.com/PaddlePaddle/PaddleFleetX/tree/develop/projects/ernie 使用PaddleFleetX推理Ernie模型，有如下两点疑问：
1. 使用PaddleFleetX推理Ernie模型分为export和inference两个步骤，export阶段能够观察到GPU显存分两次爬坡，以6.7B ernie mp1为例，首先爬坡到25G左右，当`New Executor is Running`（开始动转静？）信息出现后继续爬坡至50G，峰值占用过高限制大尺寸模型导出。
2. PaddleFleetX支持在export时应用AMP将部分算子转fp16，但一能够转成fp16不如Paddle Inference AMP多，二是影响在Paddle Inference进行fusion等优化，故不如以fp32导出在Paddle Inference AMP，如此一来势必要以fp32尺寸模型导出。请问低精度推理最佳的实践，如何压减保存模型的尺寸和显存占用。

**Comment by xiaoguoguo626807** [comment]
PaddleFleetX 近期不再维护，相关代码移动至nlp,可以在nlp 代码库中尝试一下
