### ISSUE TITLE
编译 X86CPU + 华为昇腾910  NPU 版 Paddle；报错

### ISSUE THREAD

**Issue by enjoyloveless** [PaddlePaddle/Paddle#57270]
使用 paddlepaddle/paddle:latest-dev-cann5.0.2.alpha005-gcc82-x86_64 镜像

# 下载源码
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle

# 创建编译目录
mkdir build && cd build

# 执行 cmake
cmake .. -DPY_VERSION=3.7 -DWITH_ASCEND=ON -DWITH_ARM=OFF -DWITH_ASCEND_CL=ON -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON

# 使用以下命令来编译
make -j$(nproc) 

cannot find -lnpu_hccl
collect2: error: ld returned 1 exit status
paddle/phi/kernels/funcs/jit/CMakeFiles/jit_kernel_benchmark.dir/build.make:98: recipe for target 'paddle/phi/kernels/funcs/jit/jit_kernel_benchmark' failed
make[2]: *** [paddle/phi/kernels/funcs/jit/jit_kernel_benchmark] Error 1
CMakeFiles/Makefile2:9273: recipe for target 'paddle/phi/kernels/funcs/jit/CMakeFiles/jit_kernel_benchmark.dir/all' failed
make[1]: *** [paddle/phi/kernels/funcs/jit/CMakeFiles/jit_kernel_benchmark.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qili93** [comment]
昇腾NPU的源码编译方式已经全部迁移至 PaddleCustomDevice，请参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 进行源码编译。
