### ISSUE TITLE
编译paddle2.5失败

### ISSUE THREAD

**Issue by lichangW** [PaddlePaddle/Paddle#57283]
### 问题描述 Issue Description

 问题(1): 官方没有paddle2.5.1+cuda12.0在python3.7下的whl包，能帮忙提供吗？感谢！

问题(2)如图，在python3.7中编译paddle release/2.5报错，取掉-DCUDA_ARCH_NAME=All则ok; 但是我需要编译出python37下通用版本的whl， 所以我理解CUDA_ARCH_NAME是必要的？麻烦帮忙看下，感谢！
cmake .. -DPY_VERSION=3.7 -DWITH_GPU=ON -DCUDA_ARCH_NAME=All

编译环境：docker pull paddlepaddle/paddle:2.5.1-gpu-cuda12.0-cudnn8.9-trt8.6

![image](https://github.com/PaddlePaddle/Paddle/assets/9452272/a64c936c-f7f3-4c90-9c20-c22005bfe46c)

### 版本&环境信息 Version & Environment Information

paddle relase/2.5 cuda12.0
用的官方环境：paddlepaddle/paddle:2.5.1-gpu-cuda12.0-cudnn8.9-trt8.6

**Comment by risemeup1** [comment]
cuda_arch_name对应的是你的gpu架构，一般不用制定，会自动检测，如果手动指定需要与显卡对应，你指定成all，就是编译全部架构

**Comment by lichangW** [comment]
> cuda_arch_name对应的是你的gpu架构，一般不用制定，会自动检测，如果手动指定需要与显卡对应，你指定成all，就是编译全部架构

感谢回复，这边就是需要编译全部构架的通用版本，因为需要py37版本对应的whl包(不可能在每个机器上都编译一次)，请问咱们官方发布的whl包可以提供x86 py37的版本吗

**Comment by risemeup1** [comment]
我们cuda12编译镜像里面没有3.7的环境，我们也是需要去手动编一下的，可以用这个 cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_CUDNN_DSO=OFF -DWITH_SHARED_PHI=OFF -DWITH_TENSORRT=ON -DWITH_ROCM=OFF -DWITH_CINN=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON -DWITH_AVX=ON -DCUDA_ARCH_NAME=Manual -DNEW_RELEASE_PYPI=ON -DNEW_RELEASE_ALL=OFF -DNEW_RELEASE_JIT=OFF -DWITH_PYTHON=ON -DCUDNN_ROOT=/usr/ -DWITH_TESTING=OFF -DWITH_COVERAGE=OFF -DWITH_INCREMENTAL_COVERAGE=OFF -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_INFERENCE_API_TEST=OFF -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo -DPY_VERSION=3.7 -DCMAKE_INSTALL_PREFIX=/paddle/build -DWITH_PSCORE=ON -DWITH_PSLIB=OFF -DWITH_GLOO=ON -DLITE_GIT_TAG=release/v2.10 -DWITH_XPU=OFF -DWITH_IPU=OFF -DXPU_SDK_ROOT= -DWITH_LITE=OFF -DWITH_XPU_BKCL=OFF -DWITH_ARM=OFF -DWITH_STRIP=ON -DON_INFER=ON -DWITH_HETERPS=OFF -DWITH_GPU_GRAPH=OFF -DCUDA_ARCH_BIN='70 75 80 86' -DWITH_RECORD_BUILDTIME=OFF -DWITH_UNITY_BUILD=OFF -DWITH_ONNXRUNTIME=OFF -DWITH_CUDNN_FRONTEND=OFF

**Comment by lichangW** [comment]
> 我们cuda12编译镜像里面没有3.7的环境，我们也是需要去手动编一下的，可以用这个 cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=ON -DWITH_CUDNN_DSO=OFF -DWITH_SHARED_PHI=OFF -DWITH_TENSORRT=ON -DWITH_ROCM=OFF -DWITH_CINN=OFF -DWITH_DISTRIBUTE=ON -DWITH_MKL=ON -DWITH_AVX=ON -DCUDA_ARCH_NAME=Manual -DNEW_RELEASE_PYPI=ON -DNEW_RELEASE_ALL=OFF -DNEW_RELEASE_JIT=OFF -DWITH_PYTHON=ON -DCUDNN_ROOT=/usr/ -DWITH_TESTING=OFF -DWITH_COVERAGE=OFF -DWITH_INCREMENTAL_COVERAGE=OFF -DCMAKE_MODULE_PATH=/opt/rocm/hip/cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_INFERENCE_API_TEST=OFF -DINFERENCE_DEMO_INSTALL_DIR=/root/.cache/inference_demo -DPY_VERSION=3.7 -DCMAKE_INSTALL_PREFIX=/paddle/build -DWITH_PSCORE=ON -DWITH_PSLIB=OFF -DWITH_GLOO=ON -DLITE_GIT_TAG=release/v2.10 -DWITH_XPU=OFF -DWITH_IPU=OFF -DXPU_SDK_ROOT= -DWITH_LITE=OFF -DWITH_XPU_BKCL=OFF -DWITH_ARM=OFF -DWITH_STRIP=ON -DON_INFER=ON -DWITH_HETERPS=OFF -DWITH_GPU_GRAPH=OFF -DCUDA_ARCH_BIN='70 75 80 86' -DWITH_RECORD_BUILDTIME=OFF -DWITH_UNITY_BUILD=OFF -DWITH_ONNXRUNTIME=OFF -DWITH_CUDNN_FRONTEND=OFF

感谢回复，gcc12编译OK了，但是换成gcc7.5就不行了，麻烦看下
![image](https://github.com/PaddlePaddle/Paddle/assets/9452272/94b89fd2-6084-44ba-896b-a5d933540ead)


![image](https://github.com/PaddlePaddle/Paddle/assets/9452272/b4b04439-4a3d-4137-a5b0-5dcd27952da2)

![image](https://github.com/PaddlePaddle/Paddle/assets/9452272/7a3a541a-421a-4fda-af86-c45947c200ed)

**Comment by kangguangli** [comment]
从报错来看，其实只是报了一些 warning，但是我们对于 warning默认也是不许出现的，可以修改下编译选项，关掉warning试试。
修改方法为，删除以下代码
https://github.com/PaddlePaddle/Paddle/blob/0424fb78b4aaf057170fbf97d9db743b5abf5856/cmake/flags.cmake#L149-L151

**Comment by lichangW** [comment]
> 从报错来看，其实只是报了一些 warning，但是我们对于 warning默认也是不许出现的，可以修改下编译选项，关掉warning试试。 修改方法为，删除以下代码
> 
> https://github.com/PaddlePaddle/Paddle/blob/0424fb78b4aaf057170fbf97d9db743b5abf5856/cmake/flags.cmake#L149-L151

删除之后ok了，感谢指导：）
