### ISSUE TITLE
同名变量多次调用 `Tensor.detach_` 能稳定引发段错误

### ISSUE THREAD

**Issue by RedContritio** [PaddlePaddle/Paddle#57303]
### bug描述 Describe the Bug

重新创建同名变量并调用 `detach_`，将导致段错误

最小可复现代码：

```python
import paddle
x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
x.detach_()
x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
x.detach_()
```

错误信息
```
Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
, 1.0]], stop_gradient=False)
x.detach_()
x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
x.detach_()
>>> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
>>> x.detach_()
Tensor(shape=[1, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
       [[1., 1., 1.]])
>>> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
>>> x.detach_()


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1694633134 (unix time) try "date -d @1694633134" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 738250 (TID 0x7f73b1e02740) from PID 0 ***]

Segmentation fault (core dumped)
```

**Comment by kangguangli** [comment]
感谢同学的反馈和给出的用例，已反馈给同事，后续我们会及时修复，进展会在issue中同步。

**Comment by wanghuancoder** [comment]
> ### bug描述 Describe the Bug
> 重新创建同名变量并调用 `detach_`，将导致段错误
> 
> 最小可复现代码：
> 
> ```python
> import paddle
> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
> x.detach_()
> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
> x.detach_()
> ```
> 
> 错误信息
> 
> ```
> Python 3.8.10 (default, Nov 14 2022, 12:59:47) 
> [GCC 9.4.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import paddle
> , 1.0]], stop_gradient=False)
> x.detach_()
> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
> x.detach_()
> >>> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
> >>> x.detach_()
> Tensor(shape=[1, 3], dtype=float32, place=Place(cpu), stop_gradient=True,
>        [[1., 1., 1.]])
> >>> x = paddle.to_tensor(data=[[1.0, 1.0, 1.0]], stop_gradient=False)
> >>> x.detach_()
> 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> No stack trace in paddle, may be caused by external reasons.
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Segmentation fault` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1694633134 (unix time) try "date -d @1694633134" if you are using GNU date ***]
>   [SignalInfo: *** SIGSEGV (@0x0) received by PID 738250 (TID 0x7f73b1e02740) from PID 0 ***]
> 
> Segmentation fault (core dumped)
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

反写反馈，这个PR可以修复这个问题。https://github.com/PaddlePaddle/Paddle/pull/57394
