### ISSUE TITLE
arm64架构编译paddle2.4.1的问题

### ISSUE THREAD

**Issue by wsxf** [PaddlePaddle/Paddle#57311]
### 请提出你的问题 Please ask your question

官网上所有版本的编译文档的步骤都是切换到develop分支去编译，这样编译出来的版本能符合我们的预期吗？
![e243ece8ff4c5400d3bbb12f3b0ab875](https://github.com/PaddlePaddle/Paddle/assets/40845723/19ba9e0a-853d-46bb-9c0e-f73b2e6b8e56)

**Comment by kangguangli** [comment]
如果想编译2.4.1版本，需要先切换到2.4.1对应分支编译
```shell
git checkout tags/v2.4.1
```

**Comment by wsxf** [comment]
好的明白了，还有个问题，paddlepaddle和paddleInference的版本对应关系在哪能找到呢？

**Comment by kangguangli** [comment]
paddlepaddle和paddleInference使用同一个代码仓库，版本号是一致的。如果你是指推理库的话，应该只是根据使用场景打了下包。

**Comment by wsxf** [comment]
好的 了解 感谢～～！
