### ISSUE TITLE
GPU上的OCR识别结果为乱码，使用docker进行验证也是一样结果，显卡驱动已经为535

### ISSUE THREAD

**Issue by scyangjunjie** [PaddlePaddle/Paddle#57323]
### bug描述 Describe the Bug

系统ubantu20.04
python3.8.10
显卡1050TI
cuda11.7
问题现象：只能在paddle2.4.1版本下才能进行paddleocr在GPU上的OCR识别,使用paddle2.5.x版本的OCR结果为乱码

测试流程：拉取paddle2.5.1下不同cuda版本的docker进行GPU加速OCR测试，只有cuda10.2不会出现乱码，随后尝试paddle2.4.1下的cuda11.7的docker镜像，发现使用GPU加速OCR能正常的出结果

**Comment by kangguangli** [comment]
你好，从这里的描述很难看出问题，能否给出一份复现的流程呢？如果可以帮助定位下，给出一份最小可复现样例，可以更快地解决此问题。感谢！
