### ISSUE TITLE
在arm64架构下编译paddlepaddle2.4.1

### ISSUE THREAD

**Issue by wsxf** [PaddlePaddle/Paddle#57336]
### 请提出你的问题 Please ask your question

操作系统L：ubuntu18
gcc 8.2.0
python3.8
编译指令：
cmake .. -DPY_VERSION=3.8 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_GPU=OFF

报错：

Requirement already satisfied: MarkupSafe>=2.0 in /paddle/install/bpython/lib/python3.8/site-packages (from jinja2) (2.1.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
parse api yamls:
- /paddle/source/Paddle/paddle/phi/api/yaml/ops.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/legacy_ops.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/backward.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/legacy_backward.yaml
validate api yaml:
- /paddle/source/Paddle/paddle/phi/api/yaml/parsed_apis/ops.parsed.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/parsed_apis/backward_ops.parsed.yaml
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe

全量cmake日志如下：
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Paddle host system: ubuntu, version: 18.04.6
-- Found Paddle host system's CPU: 64 cores
-- The CXX compiler identification is GNU 8.2.0
-- The C compiler identification is GNU 8.2.0
-- Check for working CXX compiler: /paddle/install/gcc-8.2/bin/c++
-- Check for working CXX compiler: /paddle/install/gcc-8.2/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /paddle/install/gcc-8.2/bin/gcc
-- Check for working C compiler: /paddle/install/gcc-8.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
EXP_CUDA_MODULE_LOADING_LAZY only works with GPU
-- CXX compiler: /paddle/install/gcc-8.2/bin/c++, version: GNU 8.2.0
-- C compiler: /paddle/install/gcc-8.2/bin/gcc, version: GNU 8.2.0
-- AR tools: /usr/bin/ar
-- Found Git: /usr/bin/git (found version "2.17.1")
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Failed
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Failed
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Failed
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Failed
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Failed
-- Performing Test AVX512F_FOUND
-- Performing Test AVX512F_FOUND - Failed
Enable Custom Device when compiling for Linux. Force WITH_CUSTOM_DEVICE=ON.
CMake Warning at CMakeLists.txt:380 (message):
  Disable NCCL when compiling without GPU.  Force WITH_NCCL=OFF.

CMake Warning at CMakeLists.txt:459 (message):
  Disable RCCL when compiling without ROCM.  Force WITH_RCCL=OFF.

-- Do not have AVX2 intrinsics and disabled MKL-DNN.
-- warp-ctc library: /paddle/source/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Build OpenBLAS by External Project (include: /paddle/source/Paddle/build/third_party/install/openblas/include, library: /paddle/source/Paddle/build/third_party/install/openblas/lib/libopenblas.a)
-- CBLAS_PROVIDER: EXTERN_OPENBLAS
-- Protobuf protoc executable: /paddle/source/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /paddle/source/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /paddle/source/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /paddle/source/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 3.1.0
-- Found PythonInterp: /paddle/install/bpython/bin/python3 (found suitable version "3.8.5", minimum required is "3.8")
-- Found PythonLibs: /paddle/install/bpython/lib/libpython3.8.so (found suitable version "3.8.5", minimum required is "3.8")
-- Found PY_pip: /paddle/install/bpython/lib/python3.8/site-packages/pip
-- Found PY_numpy: /paddle/install/bpython/lib/python3.8/site-packages/numpy
-- Found PY_wheel: /paddle/install/bpython/lib/python3.8/site-packages/wheel
-- Found PY_google.protobuf: /paddle/install/bpython/lib/python3.8/site-packages/google/protobuf
-- Found NumPy: /paddle/install/bpython/lib/python3.8/site-packages/numpy/core/include
POCKETFFT_INCLUDE_DIR is /paddle/source/Paddle/build/third_party/pocketfft/src
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - done
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - done
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_int_in_bool_context - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wimplicit_fallthrough_0 - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_maybe_uninitialized - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_format_truncation
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_format_truncation - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_format_truncation
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_format_truncation - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_catch_value
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_catch_value - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_catch_value
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_catch_value - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_nonnull_compare
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_nonnull_compare - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_nonnull_compare
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_nonnull_compare - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_address
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_address - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_address
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_address - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_ignored_qualifiers
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_ignored_qualifiers - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_ignored_qualifiers
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_ignored_qualifiers - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_parentheses
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_parentheses - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 2.4.1
-- On inference mode, will take place some specific optimization.
Requirement already satisfied: pyyaml in /paddle/install/bpython/lib/python3.8/site-packages (6.0.1)
Requirement already satisfied: jinja2 in /paddle/install/bpython/lib/python3.8/site-packages (3.1.2)
Requirement already satisfied: typing-extensions in /paddle/install/bpython/lib/python3.8/site-packages (4.7.1)
Requirement already satisfied: MarkupSafe>=2.0 in /paddle/install/bpython/lib/python3.8/site-packages (from jinja2) (2.1.3)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
parse api yamls:
- /paddle/source/Paddle/paddle/phi/api/yaml/ops.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/legacy_ops.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/backward.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/legacy_backward.yaml
validate api yaml:
- /paddle/source/Paddle/paddle/phi/api/yaml/parsed_apis/ops.parsed.yaml
- /paddle/source/Paddle/paddle/phi/api/yaml/parsed_apis/backward_ops.parsed.yaml
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
create or remove auto-geneated operators: /paddle/source/Paddle/paddle/fluid/operators/generated_op.cc.tmp
create or remove auto-geneated argument mappings: /paddle/source/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp
copy if different /paddle/source/Paddle/paddle/fluid/operators/generated_op.cc.tmp /paddle/source/Paddle/paddle/fluid/operators/generated_op.cc
copy if different /paddle/source/Paddle/paddle/fluid/operators/generated_sparse_op.cc.tmp /paddle/source/Paddle/paddle/fluid/operators/generated_sparse_op.cc
copy if different /paddle/source/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp /paddle/source/Paddle/paddle/phi/ops/compat/generated_sig.cc
copy if different /paddle/source/Paddle/paddle/phi/ops/compat/generated_sparse_sig.cc.tmp /paddle/source/Paddle/paddle/phi/ops/compat/generated_sparse_sig.cc
generate /paddle/source/Paddle/paddle/fluid/operators/ops_extra_info.cc
Merge and generate static library: phi_static_1
-- commit: 4743cc8b9a
-- branch: HEAD
Performing Eager Dygraph Auto Code Generation
Final State Eager CodeGen
Generate dygraph file structure at path: /paddle/source/Paddle/paddle/fluid/eager/generated
WITH_DLNNE:

请问这个
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
BrokenPipeError: [Errno 32] Broken pipe
是什么原因？

**Comment by kangguangli** [comment]
从报错看不出错误原因，搜了下可能是管道问题，可以删除build目录重新编译试试。
也有可能这个问题不影响编译？这里是全部报错日志吗，没有抛出其他报错吗？
