### ISSUE TITLE
windows下如何指定显卡运行代码，或者多卡运行

### ISSUE THREAD

**Issue by SolarKnight1** [PaddlePaddle/Paddle#57350]
### 请提出你的问题 Please ask your question

我在网上查的几种方法都不好用，
现在是加了paddle.device.set_device('gpu:1')
但是报错ppocr INFO: train with paddle 2.5.1 and device Place(gpu:0)
E0915 09:02:36.581751 10584 place.cc:337] Invalid CUDAPlace(1), must inside [0, 1), because GPU number on your machine is 1
但我确实有俩啊

 GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA A10                   TCC   | 00000000:00:07.0 Off |                    0 |
|  0%   56C    P0             102W / 150W |  15477MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+
|   1  NVIDIA A10                   TCC   | 00000000:00:08.0 Off |                    0 |
|  0%   29C    P8               9W / 150W |      1MiB / 23028MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

**Comment by USTCKAY** [comment]
Hi，因为NCCL尚不支持windows，所以目前paddle在windows平台不支持多卡，因此默认使用0号卡，不能指定使用其他卡。参考这篇文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/index_cn.html
