### ISSUE TITLE
 Paddle2ONNX 命令行工具

### ISSUE THREAD

**Issue by homelandP** [PaddlePaddle/Paddle#57356]
### 问题描述 Issue Description

使用paddle2onnx命令行工具时，报错，调用的不是我当前虚拟环境里python解释器的路径，是原始安装paddle环境的路径，这个路径该怎么改？
Fatal error in launcher: Unable to create process using '"I:\espaddle\espaddle\python.exe" "E:\anaconda\envs\espaddle\Scripts\paddle2onnx.exe" --model_dir ........................

### 版本&环境信息 Version & Environment Information

****************

**Comment by USTCKAY** [comment]
你把需要的python的路径加到系统环境变量`Path`里，把不需要的python路径移除出去试试
