### ISSUE TITLE
sparse update的原理是什么？开启sparse update虽然会加速，模型的效果会下降吗？

### ISSUE THREAD

**Issue by hikkinight** [PaddlePaddle/Paddle#5737]
PaddlePaddle实现的sparse update有没有参考的paper？

**Comment by typhoonzero** [comment]
sparse update是在每一个layer的参数（parameters）optimize时，只更新非0的参数，或者在分布式处理时，只把非0参数发送到parameter server参数更新。在参数足够稀疏时增加optimize速度而不影响效果。
