### ISSUE TITLE
[Custom Device] 如何实现int8模型

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#57390]
### 请提出你的问题 Please ask your question

对于int8模型，Custom Device如何实现在Paddle Inference实现？
我看见就算是CUDA 也不支持int8推理，都是在TensorRT实现的。

**Comment by engineer1109** [comment]
@ronny1996

**Comment by ronny1996** [comment]
int8的kernel可以注册吗？现在是报什么错误吗？

**Comment by engineer1109** [comment]
@ronny1996 不是kernel的问题。就比如ppyolo_mbv3_large_qat 这种是量化模型，默认都是用float的。
但是有fake伪层，在OneDNN下会变成int8模型。
如果是Custom Device怎么样变成Int8模型。
或者怎么得到int8直接权重存储的模型。

**Comment by ronny1996** [comment]
这个和CustomDevice无关了，导出时将模型kernel设成int8或者将权重修改成int8

**Comment by engineer1109** [comment]
@ronny1996 PaddleSlim就算设置成int8,导出的模型也只能是float
```
from paddleslim.quant import quant_post_dynamic

import paddle

paddle.enable_static()

model_dir = "/home/wjl/gitlab_xdx/paddlelite_infer_cxx_demo/data/model/pp_liteseg_stdc1_cityscapes_1024x512_scale0.5_160k"
save_model_dir = "./new"
quant_post_dynamic(model_dir=model_dir,
                   model_filename="model.pdmodel",
                   params_filename="model.pdiparams",
                   save_model_dir=save_model_dir,
                   weight_bits=8,
                   quantizable_op_type=['conv2d', 'mul'],
                   generate_test_model=False)
```

**Comment by engineer1109** [comment]
@ronny1996 如何得到一个纯粹的int8模型进行验证呢？

**Comment by ronny1996** [comment]
这个应该是paddleslim的问题，你使用paddle导出int8模型呢？只有权重是int8, 输入是fp32吗？

**Comment by engineer1109** [comment]
paddleslim导出的量化都是float，需要在mkldnn的pass处理成自己需要的int8参数，转变成OneDNN的conv2d_fusion

我目前没找到Paddle的int8模型，如果存在应该如何导出？我需要一个能验证int8的模型

**Comment by ronny1996** [comment]
可能是输入是fp32, 权重是int8，所以kernel key中的dtype是fp32，你用netron看一下模型是不是这样的。如果是，只需要在kernel里做相应的支持就可以
