### ISSUE TITLE
使用Qt 搭建界面c++库 release 能正常跑，打包后运行崩溃。无法定位程序输入点EnableMemoryOptim@AnalysisConfig@paddle@@QEAAX_N@Z于动态链接库

### ISSUE THREAD

**Issue by DustReliant** [PaddlePaddle/Paddle#57406]
### bug描述 Describe the Bug

使用Qt 搭建界面c++库 release 能正常跑，打包后运行崩溃。无法定位程序输入点EnableMemoryOptim@AnalysisConfig@paddle@@QEAAX_N@Z于动态链接库

### 其他补充信息 Additional Supplementary Information

使用Qt 搭建界面c++库 release 能正常跑，打包后运行崩溃。无法定位程序输入点EnableMemoryOptim@AnalysisConfig@paddle@@QEAAX_N@Z于动态链接库

**Comment by USTCKAY** [comment]
Hi，能否提供复现步骤以及你的环境中的软硬件信息？

**Comment by DustReliant** [comment]
已经解决了 谢谢大佬回复。
