### ISSUE TITLE
PaddleNLP 推理失败，parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by BrandonStudio** [PaddlePaddle/Paddle#57422]
### bug描述 Describe the Bug

最小代码：
```python
from paddlenlp import Taskflow
ie = Taskflow("information_extraction", schema={"a":"b"})
```

输出错误：
```
W0917 20:27:05.681756  1669 gpu_resources.cc:96] The GPU architecture in your current machine is Pascal, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
W0917 20:27:05.681811  1669 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.6
W0917 20:27:05.683454  1669 gpu_resources.cc:149] device: 0, cuDNN Version: 8.9.
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device
已放弃
```

显示适配器：NVIDIA GeForce GTX 1060（6GB）
显示适配器驱动程序：Studio 驱动程序 版本 535.98
CUDA版本：11.6
cuDNN版本：8.9.5 (CUDA 11.x)
操作系统：Windows 10 22H2 (19045.3448) 及其 WSL (Ubuntu 20.04)（均异常退出，Windows输出不包含最后三行的错误信息）

paddlepaddle 版本：最新稳定版（2.5）
paddlenlp版本：latest（2.6.1）

paddlepaddle安装方法：官网
```cmd
python -m pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
```
```bash
python -m pip install paddlepaddle-gpu==2.5.1.post116 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
```

### 其他补充信息 Additional Supplementary Information

https://www.paddlepaddle.org.cn/inference/master/faq/faq_runtime_error.html 中说是编译问题，是不是你们编译的时候CMAKE架构没有选全？

**Comment by zengshao0622** [comment]
PaddleNLP相关问题建议在对应repo咨询：https://github.com/PaddlePaddle/PaddleNLP/issues

**Comment by BrandonStudio** [comment]
正如补充信息所述，我认为这是一个Paddle问题，而不是paddlenlp的问题

**Comment by zengshao0622** [comment]
> 正如补充信息所述，我认为这是一个Paddle问题，而不是paddlenlp的问题

是的，应该是Paddle编译的包在GTX 1060（Pascal架构)的条件下会有问题，建议参考faq修改一下cmake文件重新编译一下，如果还有问题可以继续反馈。

**Comment by BrandonStudio** [comment]
“Paddle编译的包”是什么意思？

我是按照官网的指南通过pip安装的，我只是paddlepaddle的用户，不应该负责编译。如果你们编译出的某个版本的paddlepaddle不能在特定架构下正确运行，你们应该以正确的方式重新编译，或者在安装指南中注明。

**Comment by BrandonStudio** [comment]
这个问题为什么被关闭了？
