### ISSUE TITLE
[LLM] Sharding stage3和zero stage3行为不一致

### ISSUE THREAD

**Issue by BeingGod** [PaddlePaddle/Paddle#57439]
### 请提出你的问题 Please ask your question

Sharding stage3对参数的切分，需要先在rank0上完成的模型参数加载和初始化，再进行打平切分。

分析sharing stage3的源码，在第480行，`param.fw_storage`构造了一个切分后的param（对参数进行切分）。在第497行，调用`param._clear_data()`对原来参数占用的显存进行释放。
![image](https://github.com/PaddlePaddle/Paddle/assets/31957460/a1fbc494-a870-4ab3-8527-74e40a3f6219)

zero stage3通过类似于上下文的方式，可以在初始化的同时进行切分。代码见：https://github.com/microsoft/DeepSpeed/blob/master/deepspeed/runtime/zero/partition_parameters.py#L709

由于Sharding stage3对于本身参数存在显存瓶颈的模型无法起到一个降低显存的作用。想了解一下Sharding stage3如此设计的原因，以及后续这部分的行为上是否会与zero stage3对齐？

**Comment by Charles-hit** [comment]
同学您好，这边已经找相关负责人跟进了呢，预计今天或者明天晚点确认下问题给您回复。
