### ISSUE TITLE
Paddle requires libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb on Ubuntu which is not installed

### ISSUE THREAD

**Issue by moisestohias** [PaddlePaddle/Paddle#57472]
### 问题描述 Issue Description

`pip install paddlepaddle==2.5.1 -i https://mirror.baidu.com/pypi/simple`

This can be fixed easily with 
```sh
!wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
!sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```
Please resolve update the dependency
also 

`import paddlehub` raises 
```
AttributeError                            Traceback (most recent call last)
[<ipython-input-15-38820e59b4ad>](https://localhost:8080/#) in <cell line: 2>()
      1 # import paddle as pl
----> 2 pl.version

AttributeError: module 'paddle' has no attribute 'version'
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 22.04
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: 14.0.0-1ubuntu1.1
CMake version: version 3.27.4
Libc version: glibc 2.35
Python version: 3.10.12

CUDA version: 11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: 8.9.0
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by jiahy0825** [comment]
Thanks for your issue, I will contact the relevant co-worker to follow this issue.

**Comment by jiahy0825** [comment]
> `import paddlehub` raises
> 
> ```
> AttributeError                            Traceback (most recent call last)
> [<ipython-input-15-38820e59b4ad>](https://localhost:8080/#) in <cell line: 2>()
>       1 # import paddle as pl
> ----> 2 pl.version
> 
> AttributeError: module 'paddle' has no attribute 'version'
> ```

Can you please check paddle's version, is it consistent with paddle installed in your local environment?

P.S. We are very open if you can create a PR to fix the install dependency problem :)

**Comment by moisestohias** [comment]
Running on Colab, I've tried multiple versions, non of them worked
```python
# !pip install paddlepaddle==2.5.1 -i https://mirror.baidu.com/pypi/simple
# import paddle
# paddle.version
```
Also tried this:
```python
# !pip install paddle==1.0.2
# !pip install paddlehub==2.3.1
# !pip install paddlepaddle==2.5.1
# !pip install paddlepaddle-gpu
```

Also paddle requires `libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb` which is not installed by default on Ubuntu (Colab), so you
 may want to report this as well
```bash
wget http://security.ubuntu.com/ubuntu/pool/main/o/openssl/libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
sudo dpkg -i libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb
```

I think there should be clean install, so the end use doesn't need to delve into the dependencies details

**Comment by risemeup1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56452 等我这个pr合入就好了

**Comment by falloutboy111** [comment]
Do you know when this fix will be merged? 

> #56452 等我这个pr合入就好了

**Comment by risemeup1** [comment]
> Do you know when this fix will be merged?
> 
> > #56452 等我这个pr合入就好了

这个PR需要依赖很多其他的PRcherry-pick到2.5，现在develop分支没这个问题

**Comment by falloutboy111** [comment]
> > Do you know when this fix will be merged?
> > > #56452 等我这个pr合入就好了
> 
> 这个PR需要依赖很多其他的PRcherry-pick到2.5，现在develop分支没这个问题

Are you saying that the development branch does not have the libssl.so.1.1?

**Comment by risemeup1** [comment]
@falloutboy111 yes，develop branch does't have this problem. You can use develop branch

**Comment by falloutboy111** [comment]
> @falloutboy111 yes，develop branch does't have this problem. You can use develop branch
if i install from develop this will be the gpu version correct?

**Comment by moisestohias** [comment]
Thank you for your prompt response and answers, I would like to create a PR for this, but I unfortunately don't have time, I've never used paddle before.
