### ISSUE TITLE
[TTS] Aborted (core dumped) after determining tmp storage requirements for inclusive_scan: cudaErrorInvalidDeviceFunction: invalid device function

### ISSUE THREAD

**Issue by neuxys** [PaddlePaddle/Paddle#57470]
### 问题描述 Issue Description

报错：
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  after determining tmp storage requirements for inclusive_scan: cudaErrorInvalidDeviceFunction: invalid device function
Aborted (core dumped)

完整错误信息如下截图：

![image](https://github.com/PaddlePaddle/Paddle/assets/7507589/fb82029e-8c5b-4890-acb3-fdb3b7896fe5)

-----------更多详细的测试和错误，可以参考[这里](https://github.com/PaddlePaddle/PaddleSpeech/issues/3523)----------

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 2.5.0
Paddle With CUDA:2.5.0.post117
OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: N/A
CMake version: version 3.27.4
Libc version: glibc 2.31
Python version: 3.8.13

CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: 8.4.1
Nvidia driver version: 515.43.04
Nvidia driver List: 
GPU 0: NVIDIA GeForce GTX 1050 Ti
GPU 1: NVIDIA GeForce GTX 1050 Ti

**Comment by Charles-hit** [comment]
您好，感谢您的问题。目前Paddle Speech没有做paddle 2.5版本的适配呢，如果您要用的话建议使用2.4版本的paddle。

**Comment by neuxys** [comment]
感谢您的回复，我将要去试一试2.4的paddle。有个小问题，PaddleSpeech的git主页推荐paddle使用<=2.5.1的，好奇怪
![image](https://github.com/PaddlePaddle/Paddle/assets/7507589/f781cbbb-e711-4e65-b7f1-5365a645f6e5)

**Comment by neuxys** [comment]
> 您好，感谢您的问题。目前Paddle Speech没有做paddle 2.5版本的适配呢，如果您要用的话建议使用2.4版本的paddle。

您好，有一个问题：paddlepaddle-gpu-2.4.0与paddlespeech使用的protobuf版本互不兼容

![image](https://github.com/PaddlePaddle/Paddle/assets/7507589/06d1e053-535c-45ea-ab27-841193a7bfb8)
