### ISSUE TITLE
CMake Error:  "WITH_MKL" "AND"

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#5747]
```
CMake Error at CMakeLists.txt:112 (if):
   if given arguments:

     "WITH_MKL" "AND"

   Unknown arguments specified
```

**Comment by tensor-tang** [comment]
https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceRuns.html

>  variable to store the result
           (1 for success, empty for failure)

So can not use `${AVX2_FOUND}` when do not have AVX2.
