### ISSUE TITLE
如何通过pass改变一个算子的输出数量？

### ISSUE THREAD

**Issue by MyAngelAyase** [PaddlePaddle/Paddle#57481]
### bug描述 Describe the Bug

模型中的算子如图：
![image](https://github.com/PaddlePaddle/Paddle/assets/10040619/a59c9cf4-099f-4084-87e7-b67b02d98355)

pass代码如下：

    @ir.RegisterPass
    def llama_fused_get_rotary_embedding():
        def pattern(head_dim_shape_tensor, input_ids, position_ids):
            fused_get_rotary_embedding_op = ir.PassDesc.OP.fused_get_rotary_embedding(head_dim_shape_tensor=head_dim_shape_tensor, input_ids=input_ids, position_ids=position_ids)
            return fused_get_rotary_embedding_op
    
        def replace(head_dim_shape_tensor, input_ids, position_ids):
            fused_get_rotary_embedding_op = ir.PassDesc.OP.fused_get_rotary_embedding(head_dim_shape_tensor=head_dim_shape_tensor, input_ids=input_ids, position_ids=position_ids)
            return fused_get_rotary_embedding_op #, position_ids
        return pattern, replace

想要实现的效果:
是将入参的postion_ids同时作为输出，传递给下一个算子。

**Comment by jiahy0825** [comment]
改变算子的输出数量不太可能，建议直接将 position_ids 连到下一个算子作为输入

**Comment by MyAngelAyase** [comment]
有没有示例可以参考一下？

**Comment by jiahy0825** [comment]
麻烦看看官网、以及您当时参考的资料，有没有相应示例呢

**Comment by MyAngelAyase** [comment]
就是因为没有找到有效的方法所以才提问的呢。。

**Comment by jiahy0825** [comment]
这种写法，我们都没用过，没有实际应用示例，只有单测demo：test/ir/test_ir_generate_pass.py
