### ISSUE TITLE
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by falloutboy111** [PaddlePaddle/Paddle#57493]
### bug描述 Describe the Bug

Hi I've read multiple posts suggesting that to simply fix this issue download it with wget and install it however.... This becomes tricky to get working on a server less environment I've been trying to install this now and no luck i just keep getting this error(ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory). The only version that seems to work is 2.4.2 cpu but i would like to use GPU as it is faster i tried 2.5.1 get libssl same on 2.5.0 when moving to 2.4.2 I get libcudart.so.10.2, now i do not have any control over the cuda version its only set to 11.7 which if I'm not mistaken i can only use 2.5.1 and 2.5.0? any assistance on how i can get paddlepaddle-gpu to work on a server less instance will be much appreciated.

**Comment by risemeup1** [comment]
https://github.com/PaddlePaddle/Paddle/pull/56452 等我这个PR合入就好了，develop分支没问题，2.5分支忘记合入了

**Comment by risemeup1** [comment]
先用develop分支编译的包吧

**Comment by risemeup1** [comment]
2.5分支cherry-pick的话依赖其他的PR

**Comment by yangy996** [comment]
也遇到了，头疼了半天

**Comment by HuaC-Z** [comment]
什么时候修好了麻烦说一哈

**Comment by risemeup1** [comment]
修好了

**Comment by yangy996** [comment]
> 修好了

可以发布个2.5.2版本吗？自己编译太费时费力了

**Comment by XieYunshen** [comment]
> > 修好了
> 
> 可以发布个2.5.2版本吗？自己编译太费时费力了

可以发一下需要cuda版本和python版本，我们可以提供一个2.5分支的nightly的安装包

**Comment by river7816** [comment]
> > > 修好了
> > 
> > 
> > 可以发布个2.5.2版本吗？自己编译太费时费力了
> 
> 可以发一下需要cuda版本和python版本，我们可以提供一个2.5分支的nightly的安装包

```
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Fri_Sep__8_19:17:24_PDT_2023
Cuda compilation tools, release 12.3, V12.3.52
Build cuda_12.3.r12.3/compiler.33281558_0
```
python = 3.10

**Comment by risemeup1** [comment]
2.5.2这周就发布了
