### ISSUE TITLE
Paddle3D(SMOKE)如何使用自己的摄像头进行部署

### ISSUE THREAD

**Issue by LeungWaiHo** [PaddlePaddle/Paddle#57518]
### Paddle3D(SMOKE)如何使用自己的摄像头进行部署

1、我使用的是Realsense相机，内参已改成Realsense相机的，请问还需要更改哪些参数，以实现物体的3D目标框检测以及3D目标框在2D图像上的投影；
2、我目前仅更改了相机内参矩阵[K](https://github.com/PaddlePaddle/Paddle3D/blob/dc031ec509fa1f16c6259de2b0ef975d88929013/deploy/smoke/python/infer.py#L144)，但似乎3D目标框的投影不太准确，如问题1所示，我还要更改哪些地方？

**Comment by JunnYu** [comment]
你好，这是paddle3d相关的问题，你可以去 https://github.com/PaddlePaddle/Paddle3D 这里咨询一下这个问题

**Comment by LeungWaiHo** [comment]
> 你好，这是paddle3d相关的问题，你可以去 https://github.com/PaddlePaddle/Paddle3D 这里咨询一下这个问题

您好，我在Paddle3D的版块上提问了，但没有相关的答疑，我看该板块也好久没有相关开发人员在issue上答疑了，所以我才在这里提问。请问可以帮我找一下Paddle3D的开发人员吗？谢谢。

**Comment by Ligoml** [comment]
@juncaipeng

**Comment by FlyingQianMM** [comment]
已经在Paddle3D的issue上回复。
