### ISSUE TITLE
[BUG]PaddlePaddle-gpu latest version:2.5.1 installation bug in cent os operation system

### ISSUE THREAD

**Issue by PancakeAwesome** [PaddlePaddle/Paddle#57523]
### bug描述 Describe the Bug

- 系统环境/System Environment：centos7
版本号/Version：Paddle：paddlegpu 2.5.1
openssl: 
```
$openssl version
OpenSSL 1.1.1t  7 Feb 2023
```
运行指令/Command Code：follow the official document of ppstructer document analysis:

```
>>> import paddle
```
出错信息：
```
Error: Can not import paddle core while this file exists: /opt/conda/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.8/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/opt/conda/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/opt/conda/lib/python3.8/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/opt/conda/lib/python3.8/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
```

### 其他补充信息 Additional Supplementary Information

PaddlePaddle-gpu latest version:2.5.1 installation bug in cent os operation system

**Comment by JunnYu** [comment]
你好，请提供一下你的GPU信息，cuda版本信息等。上述问题是因为你装了与设备不一致的paddle（不同cuda版本）版本导致的
`nvcc -V`
请确保nvcc -V显示的cuda版本与你安装的paddle的cuda版本一致
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/e66bde13-7994-4879-b25c-95e69ffdc09a)
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/f02f2b89-0cb8-4a01-a58d-3d18470c55dd)

**Comment by PancakeAwesome** [comment]
> 你好，请提供一下你的GPU信息，cuda版本信息等。上述问题是因为你装了与设备不一致的paddle（不同cuda版本）版本导致的 `nvcc -V` 请确保nvcc -V显示的cuda版本与你安装的paddle的cuda版本一致 ![image](https://user-images.githubusercontent.com/50394665/269156947-e66bde13-7994-4879-b25c-95e69ffdc09a.png) ![image](https://user-images.githubusercontent.com/50394665/269156991-f02f2b89-0cb8-4a01-a58d-3d18470c55dd.png)

thank u for your reply.
my env as follow:
paddle: 2.5.1_post117_cp38
cuda: 11.7
cudnn: 8.9.1.23

**Comment by PancakeAwesome** [comment]
> 你好，请提供一下你的GPU信息，cuda版本信息等。上述问题是因为你装了与设备不一致的paddle（不同cuda版本）版本导致的 `nvcc -V` 请确保nvcc -V显示的cuda版本与你安装的paddle的cuda版本一致 ![image](https://user-images.githubusercontent.com/50394665/269156947-e66bde13-7994-4879-b25c-95e69ffdc09a.png) ![image](https://user-images.githubusercontent.com/50394665/269156991-f02f2b89-0cb8-4a01-a58d-3d18470c55dd.png)

besides, my envs can run properly with paddlepaddle-gpu 2.4.2 version well.

**Comment by JunnYu** [comment]
same issue: https://github.com/PaddlePaddle/Paddle/issues/54194
this is the pr https://github.com/PaddlePaddle/Paddle/pull/56366

I have searched some issues.
https://github.com/search?q=repo%3APaddlePaddle%2FPaddle+ImportError%3A+libssl.so.1.1%3A+cannot+open+shared+object+file%3A+No+such+file+or+directory&type=issues

**Comment by PancakeAwesome** [comment]
> 你好，请提供一下你的GPU信息，cuda版本信息等。上述问题是因为你装了与设备不一致的paddle（不同cuda版本）版本导致的 `nvcc -V` 请确保nvcc -V显示的cuda版本与你安装的paddle的cuda版本一致 ![image](https://user-images.githubusercontent.com/50394665/269156947-e66bde13-7994-4879-b25c-95e69ffdc09a.png) ![image](https://user-images.githubusercontent.com/50394665/269156991-f02f2b89-0cb8-4a01-a58d-3d18470c55dd.png)

how to fix that bug? is there anybody could help me?

**Comment by JunnYu** [comment]
@PancakeAwesome you may install develop paddle，

```sh
python -m pip install paddlepaddle-gpu==0.0.0.post117 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html
```

 Follow this issue https://github.com/PaddlePaddle/Paddle/issues/54194
