### ISSUE TITLE
Mean Squared Error

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#5754]

**Comment by qingqing01** [comment]
@kavyasrinet We have [`squared_l2_distance_op`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/squared_l2_distance_op.h), the formula of this operator is :  

  output = sum((x-y)^2)

where y is tensor with same shape as x, or y is a vector. The `squared_l2_distance_op` does not compute the mean value.  Just remind you to pay attention this operator when you write `MSE` operator.

**Comment by kavyasrinet** [comment]
Thanks so much! Will do.
