### ISSUE TITLE
Allow removing the broadcast of input data in TP training

### ISSUE THREAD

**Issue by Tom-Zheng** [PaddlePaddle/Paddle#57567]
### 需求描述 Feature Description

In TP training, Paddle will broadcast the model input data across TP ranks: 
https://github.com/PaddlePaddle/Paddle/blob/8edf88d33ba47dfcefc6b52363a9e82ccbab3f93/python/paddle/distributed/fleet/meta_parallel/tensor_parallel.py#L51

However it introduces synchronized D2H copy when creating a new buffer given gpu shape tensor: https://github.com/PaddlePaddle/Paddle/blob/8edf88d33ba47dfcefc6b52363a9e82ccbab3f93/python/paddle/distributed/fleet/utils/hybrid_parallel_util.py#L139

, which harms the GPU utilization.

Is it possible to remove this broadcast?

### 替代实现 Alternatives

Feed each TP rank with the same batch of data by dataloader.

**Comment by ForFishes** [comment]
您好，当前框架对于TP会强制同步输入数据，后续可以开发功能，做成选项，选择是否广播数据。

**Comment by risemeup1** [comment]
@shenliang03
