### ISSUE TITLE
paddle inference如何多卡推理？

### ISSUE THREAD

**Issue by truthsun22** [PaddlePaddle/Paddle#57577]
### 请提出你的问题 Please ask your question

如果一个计算机有多块显卡，那么运行推理功能时，多个GPU是如何分配的？
是只能指定某一个吗？还是能指定多个？还是可以自动分配？

**Comment by Wangzheee** [comment]
可以指定 n (n=1、2、3.....)个GPU推理，具体使用可以参照 https://github.com/PaddlePaddle/PaddleNLP 中的demo

**Comment by truthsun22** [comment]
> 可以指定 n (n=1、2、3.....)个GPU推理，具体使用可以参照 https://github.com/PaddlePaddle/PaddleNLP 中的demo

谢谢，我还有点疑问，就是我们是做项目吗。可能用户触发一个请求，就开启一个推理进程。每个进程都设置n (n=1、2、3.....)。还是说每个进程根据计算显卡显存剩余多少后，来动态指定某一个显卡？

**Comment by Wangzheee** [comment]
> > 可以指定 n (n=1、2、3.....)个GPU推理，具体使用可以参照 https://github.com/PaddlePaddle/PaddleNLP 中的demo
> 
> 谢谢，我还有点疑问，就是我们是做项目吗。可能用户触发一个请求，就开启一个推理进程。每个进程都设置n (n=1、2、3.....)。还是说每个进程根据计算显卡显存剩余多少后，来动态指定某一个显卡？

每个进程使用一个执行器，每个执行器有自己的配置，可以设置使用哪张卡之类的
