### ISSUE TITLE
[Bug] Slice Kernel Error

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#57570]
### bug描述 Describe the Bug

版本 develop 275ca6b0880bc8220a403fda2e2ece11ff5c7979
Slice算子 在以下场景下出错
```python
import paddle
a = paddle.to_tensor([1, 2])
print(a.shape)
b = a[0]
print(b.shape)
```
b的shape为空了，不含任何数据

对其他生态的影响
Paddle Detection
导出solov2 出错，
IndexError: tuple index out of range
把 https://paddledet.bj.bcebos.com/models/solov2_r50_fpn_3x_coco.pdparams
放在 PaddleDetection 的创建models文件夹里

```
git clone git@github.com:PaddlePaddle/PaddleDetection.git
 python3 tools/export_model.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml -o weights=./models/solov2_r50_fpn_3x_coco.pdparams
```

C++验证代码
```cpp

#include <memory>

#include "paddle/phi/core/flags.h"

#include "paddle/fluid/platform/init.h"
#include "paddle/phi/backends/device_manager.h"

#include "paddle/phi/api/include/api.h"
#include "paddle/phi/api/lib/utils/allocator.h"
#include "paddle/phi/core/dense_tensor.h"
#include "paddle/phi/core/kernel_registry.h"

int main() {

    auto map = phi::GetExportedFlagInfoMap();
    auto* use_stride_kernel_flag = (bool*)map["use_stride_kernel"].value_ptr;
    *use_stride_kernel_flag = false;

    paddle::framework::InitMemoryMethod();
    paddle::framework::InitDevices();

    auto x = paddle::experimental::empty({2}, paddle::DataType::FLOAT32, phi::CPUPlace());

    // 2. test API
    std::vector<int64_t> axes = {0};
    std::vector<int64_t> starts = {0};
    std::vector<int64_t> ends = {1};
    auto out = paddle::experimental::slice(x, axes, starts, ends, {1}, {0});

    auto shape = out.shape();

    std::cout << shape.size() << std::endl;
}
```

**Comment by engineer1109** [comment]
solov2 受影响的代码
[solov2_head.py](https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.6/ppdet/modeling/heads/solov2_head.py)
```python
    def get_seg_single(self, cate_preds, seg_preds, kernel_preds, featmap_size,
                       im_shape, scale_factor):
        """
        The code of this function is based on:
            https://github.com/WXinlong/SOLO/blob/master/mmdet/models/anchor_heads/solov2_head.py#L385
        """
        h = paddle.cast(im_shape[0], 'int32')[0]
        w = paddle.cast(im_shape[1], 'int32')[0]
```

**Comment by engineer1109** [comment]
@jzhang533

**Comment by zhwesky2010** [comment]
> ### bug描述 Describe the Bug
> 版本 develop [275ca6b](https://github.com/PaddlePaddle/Paddle/commit/275ca6b0880bc8220a403fda2e2ece11ff5c7979) Slice算子 在以下场景下出错
> 
> ```python
> import paddle
> a = paddle.to_tensor([1, 2])
> print(a.shape)
> b = a[0]
> print(b.shape)
> ```
> 
> b的shape为空了，不含任何数据
> 
> 对其他生态的影响 Paddle Detection 导出solov2 出错， IndexError: tuple index out of range 把 https://paddledet.bj.bcebos.com/models/solov2_r50_fpn_3x_coco.pdparams 放在 PaddleDetection 的创建models文件夹里
> 
> ```
> git clone git@github.com:PaddlePaddle/PaddleDetection.git
>  python3 tools/export_model.py -c configs/solov2/solov2_r50_fpn_3x_coco.yml -o weights=./models/solov2_r50_fpn_3x_coco.pdparams
> ```
> 
> C++验证代码
> 
> ```c++
> #include <memory>
> 
> #include "paddle/phi/core/flags.h"
> 
> #include "paddle/fluid/platform/init.h"
> #include "paddle/phi/backends/device_manager.h"
> 
> #include "paddle/phi/api/include/api.h"
> #include "paddle/phi/api/lib/utils/allocator.h"
> #include "paddle/phi/core/dense_tensor.h"
> #include "paddle/phi/core/kernel_registry.h"
> 
> int main() {
> 
>     auto map = phi::GetExportedFlagInfoMap();
>     auto* use_stride_kernel_flag = (bool*)map["use_stride_kernel"].value_ptr;
>     *use_stride_kernel_flag = false;
> 
>     paddle::framework::InitMemoryMethod();
>     paddle::framework::InitDevices();
> 
>     auto x = paddle::experimental::empty({2}, paddle::DataType::FLOAT32, phi::CPUPlace());
> 
>     // 2. test API
>     std::vector<int64_t> axes = {0};
>     std::vector<int64_t> starts = {0};
>     std::vector<int64_t> ends = {1};
>     auto out = paddle::experimental::slice(x, axes, starts, ends, {1}, {0});
> 
>     auto shape = out.shape();
> 
>     std::cout << shape.size() << std::endl;
> }
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

@engineer1109 你好，这个计算结果是符合预期的，因为a是1D Tensor，在被索引后会降低1维，返回0维Tensor（也就是一个标量Tensor），其shape是一个空list或空tuple
![infoflow 2023-09-21 14-16-41](https://github.com/PaddlePaddle/Paddle/assets/52485244/c5b202a7-83ec-4259-906b-8005da796bfa)

Paddle 2.5之前不支持0维，是通过shape为`[1]`的1维Tensor来替代0维Tensor，目前Paddle最新develop已可正确的表达出shape为`[]`的0维Tensor，需要将 相关Python代码、或C++代码更新成新版的写法。

**Comment by engineer1109** [comment]
@zhwesky2010 那么paddle detection怎么处理。下载的model或自己导出都是这样的。 怎么取出b[0]

**Comment by engineer1109** [comment]
零维的东西怎么转成[1]表示呢

**Comment by engineer1109** [comment]
https://github.com/PaddlePaddle/PaddleDetection/issues/8643 这个问题可能波及所有实例分割模型

**Comment by engineer1109** [comment]
@zhwesky2010 OneDNN的greater_than好像没处理0Dim的问题

**Comment by engineer1109** [comment]
https://github.com/PaddlePaddle/PaddleDetection/pull/8644  solov2生态修复

**Comment by engineer1109** [comment]
Finish
