### ISSUE TITLE
use_gpu设置为true时结果为空或者乱码

### ISSUE THREAD

**Issue by sevenwassermelone** [PaddlePaddle/Paddle#57592]
### bug描述 Describe the Bug

1. paddlepaddle-gpu==2.5.1，cuda10.2，cudnn7.6.5:
（1）paddle.utils.run_check()：The GPU architecture in your current machine is Maxwell, which is not compatible with Paddle installation with arch: 70 75 80 86 , it is recommended to install the corresponding wheel package according to the installation information on the official Paddle website.
（2）设置use_gpu=true识别结果为空，dt_boxes num : 0；use_gpu=false正常

2. paddlepaddle-gpu==2.5.1，cuda11.2，cudnn8.2.1: 问题同1

3. paddlepaddle-gpu==2.4.2，cuda11.2，cudnn8.2.1:
（1）paddle.utils.run_check(): 正常
（2）设置use_gpu=true识别结果乱码；use_gpu=false正常

### 其他补充信息 Additional Supplementary Information

paddlepaddle-gpu==2.4.2，cuda11.2，cudnn8.2.1的话，会有警告：
C:\Users\xx\anaconda3\envs\paddle\lib\site-packages\setuptools\sandbox.py:13: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  import pkg_resources
C:\Users\xx\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
C:\Users\xx\anaconda3\envs\paddle\lib\site-packages\pkg_resources\__init__.py:2871: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)

请教下是什么原因呢，谢谢！

**Comment by XieYunshen** [comment]
请问一下你的显卡型号是什么呢？
2.5.1 cuda10.2的安装包是支持下面这些架构的
<img width="916" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/32428676/562c78d5-8763-470f-b219-f89a1d01d656">

**Comment by cesaryuan** [comment]
有同样的问题，显卡是1080Ti，安装命令是`conda install paddlepaddle-gpu==2.5.1 cudatoolkit=11.7 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge`

**Comment by risemeup1** [comment]
可能机器显卡架构不支持了，之前删了不少架构

**Comment by jsjjdzg** [comment]
paddlepaddle-gpu==2.5.2.post112
paddleocr==2.7.0.3
cuda11.2
cudnn8.1.1

1070显卡同样为空

paddle.utils.run_check(): 正常
<img width="1448" alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" src="https://github.com/PaddlePaddle/Paddle/assets/15165652/aea6539b-0b14-4826-99f1-6458b79db575">

**Comment by XieYunshen** [comment]
> paddlepaddle-gpu==2.5.2.post112 paddleocr==2.7.0.3 cuda11.2 cudnn8.1.1
> 
> 1070显卡同样为空
> 
> paddle.utils.run_check(): 正常 <img alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" width="1448" src="https://user-images.githubusercontent.com/15165652/279661319-aea6539b-0b14-4826-99f1-6458b79db575.png">

是因为编译架构问题，develop分支已经解决了这个问题，可以先使用develop分支的安装包，安装命令如下：`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

**Comment by jsjjdzg** [comment]
> > paddlepaddle-gpu==2.5.2.post112 paddleocr==2.7.0.3 cuda11.2 cudnn8.1.1
> > 1070显卡同样为空
> > paddle.utils.run_check(): 正常 <img alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" width="1448" src="https://user-images.githubusercontent.com/15165652/279661319-aea6539b-0b14-4826-99f1-6458b79db575.png">
> 
> 是因为编译架构问题，develop分支已经解决了这个问题，可以先使用develop分支的安装包，安装命令如下：`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

十分感谢，确实develop分支是可用有效的，为团队的效率点赞~

**Comment by chiliuliu** [comment]
> > paddlepaddle-gpu==2.5.2.post112 paddleocr==2.7.0.3 cuda11.2 cudnn8.1.1
> > 1070显卡同样为空
> > paddle.utils.run_check(): 正常 <img alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" width="1448" src="https://user-images.githubusercontent.com/15165652/279661319-aea6539b-0b14-4826-99f1-6458b79db575.png">
> 
> 是因为编译架构问题，develop分支已经解决了这个问题，可以先使用develop分支的安装包，安装命令如下：`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`

你好，我使用的是P100显卡，单张。自己开始搭环境的时候，更新到了develop，输出无结果。后面换了11.7和11.2的docker，发现输出都没有结果。但是设置use_gpu=False就有结果。请问是显卡原因吗？

**Comment by XieYunshen** [comment]
> > > paddlepaddle-gpu==2.5.2.post112 paddleocr==2.7.0.3 cuda11.2 cudnn8.1.1
> > > 1070显卡同样为空
> > > paddle.utils.run_check(): 正常 <img alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" width="1448" src="https://user-images.githubusercontent.com/15165652/279661319-aea6539b-0b14-4826-99f1-6458b79db575.png">
> > 
> > 
> > 是因为编译架构问题，develop分支已经解决了这个问题，可以先使用develop分支的安装包，安装命令如下：`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`
> 
> 你好，我使用的是P100显卡，单张。自己开始搭环境的时候，更新到了develop，输出无结果。后面换了11.7和11.2的docker，发现输出都没有结果。但是设置use_gpu=False就有结果。请问是显卡原因吗？

是的，因为没有编译P100的架构，建议自己去编译一下paddle的安装包。或者安装一下附录里面的Pascal架构Cuda11.2的安装包
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release
<img width="1103" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/32428676/7f103b65-193c-43a5-92f5-7c062d5ef265">

**Comment by chiliuliu** [comment]
> > > > paddlepaddle-gpu==2.5.2.post112 paddleocr==2.7.0.3 cuda11.2 cudnn8.1.1
> > > > 1070显卡同样为空
> > > > paddle.utils.run_check(): 正常 <img alt="企业微信截图_8f3e5861-6b69-4df4-b9d7-859c3f307da8" width="1448" src="https://user-images.githubusercontent.com/15165652/279661319-aea6539b-0b14-4826-99f1-6458b79db575.png">
> > > 
> > > 
> > > 是因为编译架构问题，develop分支已经解决了这个问题，可以先使用develop分支的安装包，安装命令如下：`python -m pip install paddlepaddle-gpu==0.0.0.post112 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html`
> > 
> > 
> > 你好，我使用的是P100显卡，单张。自己开始搭环境的时候，更新到了develop，输出无结果。后面换了11.7和11.2的docker，发现输出都没有结果。但是设置use_gpu=False就有结果。请问是显卡原因吗？
> 
> 是的，因为没有编译P100的架构，建议自己去编译一下paddle的安装包。或者安装一下附录里面的Pascal架构Cuda11.2的安装包 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/Tables.html#whl-release <img alt="image" width="1103" src="https://user-images.githubusercontent.com/32428676/283730517-7f103b65-193c-43a5-92f5-7c062d5ef265.png">

谢谢回复，请问一下编译安装包有什么教程或者关键字吗？如果有，是否可以麻烦提供一下。不太熟悉这方面。再次感谢
