### ISSUE TITLE
Cosine Distance

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#5759]

**Comment by qingqing01** [comment]
@kavyasrinet We have [cos_sim_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/cos_sim_op.cc), please to confirm whether the `Cosine Distance` is the same with `cos_sim_op`.

**Comment by kavyasrinet** [comment]
Sure, will do! Thanks for the pointer.

**Comment by Yancey1989** [comment]
Will close this inactive issue.
