### ISSUE TITLE
使用厂内一件编译脚本出错

### ISSUE THREAD

**Issue by zhipengli0524** [PaddlePaddle/Paddle#5762]
使用厂内一键编译工具
cd paddle_internal_release_tools/idl/paddle/ && sh build.sh [cpu|gpu] [rdma|nonrdma]

错误信息：

-- Found PythonInterp: /home/lizhipeng/tools/paddle_new/paddle_internal_release_tools/idl/paddle/thirdparties/python27-gcc482/bin/python2.7 (found version "2.7.10") 
-- Found Gflags: /home/lizhipeng/tools/paddle_new/paddle_internal_release_tools/third-64/gflags/include  
CMake Error at cmake/check_packages.cmake:38 (message):
  SWIG is not found.  Please install swig or disable WITH_SWIG_PY
Call Stack (most recent call first):
  CMakeLists.txt:62 (include)

提示没有安装swig，实际上安装了。

**Comment by peterzhang2029** [comment]
你好，推荐使用pip和docker进行安装使用，可参考文档 http://www.paddlepaddle.org/ 中的快速入门。
