### ISSUE TITLE
pooling的方式

### ISSUE THREAD

**Issue by Angus07** [PaddlePaddle/Paddle#5765]
paddle是否支持带window和stride的Max-pooling以及k-max pooling？是否能增加这个功能？在tensorflow中是支持的，如下：
![4a690a2ee33daad0b1977e17f6e54a76](https://user-images.githubusercontent.com/4252318/33001208-004a29cc-cd72-11e7-93e8-54cde2e14819.png)

**Comment by chengduoZH** [comment]
@Angus07 
1、当前paddle支持二维和三维数据的avg-pooling、max-pooling。
2、k-max pooling是不支持的，不过在paddle重构完成后会有这个的。

**Comment by Yancey1989** [comment]
Will close the inactive issue, please feel free to reopen it if any problem.
