### ISSUE TITLE
鲲鹏920编译patchelf出错

### ISSUE THREAD

**Issue by kane-hu** [PaddlePaddle/Paddle#57660]
### 问题描述 Issue Description

环境：Linux localhost.localdomain 4.19.90-52.22.v2207.ky10.aarch64 #1 SMP  aarch64 aarch64 aarch64 GNU/Linux
cmake version 3.16.8
make patchelf时出现：
![image](https://github.com/PaddlePaddle/Paddle/assets/128699761/cf224a24-ab3c-478f-91e0-fc485204aba5)

### 版本&环境信息 Version & Environment Information

2.5
kunpeng 920
T4
麒麟v10 sp3
python3.7

**Comment by GGBond8488** [comment]
@risemeup1 帮忙看看这个编译问题吧

**Comment by kane-hu** [comment]
已解决，gcc从7.3升级至8.2版本
