### ISSUE TITLE
关于rtdetr的int8 tensorrt部署，分别基于tensorrt和paddle量化

### ISSUE THREAD

**Issue by miraiaroha** [PaddlePaddle/Paddle#57697]
### 请提出你的问题 Please ask your question

**环境：
Linux 5.10.104-tegra  aarch64
Tensorrt=8.5.2
cuda=11.4**
paddle=2.5

**问题：想基于官方提供的rtdetr模型进行int8 tensorrt部署**
已尝试：
方案一（成功）：pdmodel转onnx，tensorrt导入onnx进行fp32、fp16、int8转换。
结果输出正常，但是推理耗时fp32-fp16-int8 = 60ms-33ms-35ms，tensorrt自带的int8转换没有起到加速效果。

方案二（失败）：下载官方量化好的pdmodel([https://github.com/PaddlePaddle/PaddleDetection/tree/develop/configs/rtdetr](url))，转换成onnx，tensorrt导入onnx进行trt转换，报错如下：
`[09/25/2023-15:21:50] [W] [TRT] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
[09/25/2023-15:21:50] [E] [TRT] p2o.DequantizeLinear.1268: only activation types allowed as input to this layer.
[09/25/2023-15:21:50] [E] [TRT] ModelImporter.cpp:726: While parsing node number 2 [DequantizeLinear -> "p2o.DequantizeLinear.1269"]:
[09/25/2023-15:21:50] [E] [TRT] ModelImporter.cpp:727: --- Begin node ---
[09/25/2023-15:21:50] [E] [TRT] ModelImporter.cpp:728: input: "conv2d_0.w_0.merged.bias"
input: "p2o.helper.constant.5694"
input: "p2o.helper.constant.5699"
output: "p2o.DequantizeLinear.1269"
name: "p2o.DequantizeLinear.1268"
op_type: "DequantizeLinear"
attribute {
  name: "axis"
  i: 0
  type: INT
}
[09/25/2023-15:21:50] [E] [TRT] ModelImporter.cpp:729: --- End node ---
[09/25/2023-15:21:50] [E] [TRT] ModelImporter.cpp:731: ERROR: ModelImporter.cpp:185 In function parseGraph:
[6] Invalid Node - p2o.DequantizeLinear.1268
p2o.DequantizeLinear.1268: only activation types allowed as input to this layer.
 parse onnx file fail ...
detr: /home/inkfish/code/code/dev/detr_tensorrt/detr.cpp:1084: int main(int, char**): Assertion `modelStream != nullptr' failed.`
![图片](https://github.com/PaddlePaddle/Paddle/assets/26821597/dbc7b518-4e26-4cc4-8fa3-79171df16df8)
量化后的onnx中dequantizelinear输入确实不是activate types，是int32。不清楚tensorrt是不支持量化后的onnx还是需要修改什么配置？

另外想问paddle官方是否支持导出trt文件？

另外发现develop分支中还保留了paddle.fluid接口，基于develop分支安装，paddleslim无法导入，但是rtdetr是放在了develop分支中。

**Comment by warrentdrew** [comment]
您好，问题已收到，我联系相关同学跟进下

**Comment by Wangzheee** [comment]
可以使用paddle-slim 量化模型，paddle- inference推理
https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/23786e22790d7e2cf19f30d22e72fa9dcb954334/c%2B%2B/gpu/resnet50/resnet50_test.cc#L65C32-L65C32

https://github.com/PaddlePaddle/PaddleSlim/blob/bb02b103a89a09635941bc0bbbd38506d7412468/demo/quant/deploy/TensorRT/README.md?plain=1#L171

**Comment by miraiaroha** [comment]
> 可以使用paddle-slim 量化模型，paddle- inference推理 https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/23786e22790d7e2cf19f30d22e72fa9dcb954334/c%2B%2B/gpu/resnet50/resnet50_test.cc#L65C32-L65C32
> 
> https://github.com/PaddlePaddle/PaddleSlim/blob/bb02b103a89a09635941bc0bbbd38506d7412468/demo/quant/deploy/TensorRT/README.md?plain=1#L171

和#380这个问题类似，其实我是想在nvidia orin上跑rt-detr，只想用tensorrt作为后端，这个你们目前有测试过量化onnx对接到tensorrt吗？

**Comment by Wangzheee** [comment]
paddle to onnx的之前是支持量化模型的转换，但很久没维护了，不太确定有没有问题。
Paddle Inference 支持 nvidia orin 的量化推理

**Comment by miraiaroha** [comment]
> paddle to onnx的之前是支持量化模型的转换，但很久没维护了，不太确定有没有问题。 Paddle Inference 支持 nvidia orin 的量化推理

恩，我测了下量化rt-detr转成onnx后进行推理，结果不太对，应该是有点问题

**Comment by zhDai** [comment]
请问楼主后面怎么解决这个问题的

**Comment by miraiaroha** [comment]
> 请问楼主后面怎么解决这个问题的

方案一用tensorrt量化同时开启fp16和int8是最快的

方案二是不行的，paddle量化后提供的onnx一般只支持paddle自己的推理框架，tensorrt是跑不了的
