### ISSUE TITLE
单机多CPU训练的正确实现方式是?

### ISSUE THREAD

**Issue by xieshuaix** [PaddlePaddle/Paddle#57718]
Paddle 2.4.1, 使用IterableDataset + [分布式 CPU 训练优秀实践](https://www.paddlepaddle.org.cn/documentation/advanced_guide/performance_improving/multinode_training_improving/cpu_train_best_practice.html)中的ParallelExecutor配置(num_threads=4), 报以下错:

 File "/usr/local/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1236, in _run_parallel
    exe.feed_tensors_into_local_scopes(res)
NotImplementedError: (Unimplemented) The feed data number 1 does not match the device number 4. If you are using DataLoader to feed data, this may be because you set drop_last=False in training network. Currently, drop_last=False for DataLoader is not supported for training network. Please set drop_last=True when defining DataLoader.

似乎是数据维度对不上, 数据维度是[batch_size, 1], 请问应该如何处理? 在单机上应该如何正确使用多核? 下面哪一种方式是当前已经确认可行的?
1. 不使用分布式训练, 通过多核加速
2. 分布式训练, 使用DistributedDataSampler
3. 使用fleet API

**Comment by danleifeng** [comment]
分布式CPU下可以参考下PaddleRec下训练脚本：https://github.com/PaddlePaddle/PaddleRec/blob/master/tools/static_trainer.py
