### ISSUE TITLE
[NPU][AARCH64]only confirm the ascend 310 and aarch64 support or not at release 2.4.0 or later,or show me the  detail and env

### ISSUE THREAD

**Issue by yinpeng-cn** [PaddlePaddle/Paddle#57727]
### 请提出你的问题 Please ask your question

only confirm the ascend 310 and aarch64 support or not at release 2.4.0 or later,or show me the  detail and env
CPU : FT-S2500 / Kunpeng 910 / FT 200+
OS: openeuler 22.03 / kylin V10 SP1
GCC: 8.2.0
cmake : 3.16.0

others you can help me  to define the env  to finish the build processing

**Comment by warrentdrew** [comment]
Thanks for your quesion. It will be forwarded to corresponding co-worker.

**Comment by qili93** [comment]
Ascend310 is only supported by Paddle-Lite, please refer to https://www.paddlepaddle.org.cn/lite/v2.12/demo_guides/huawei_ascend_npu.html
