### ISSUE TITLE
通过编译paddlepaddle源码的方式在import paddle时遇到了name 'libpaddle' is not defined的错误

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#57725]
### 问题描述 Issue Description

Python 3.7.5 (default, Sep 14 2023, 04:20:48) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
Error: Can not import paddle core while this file exists: /usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/libpaddle.so
Traceback (most recent call last):
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/core.py", line 268, in <module>
    from . import libpaddle
ImportError: /usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/libpaddle.so: undefined symbol: pthread_atfork

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import base
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/framework.py", line 33, in <module>
    from . import core
  File "/usr/local/python3.7.5/lib/python3.7/site-packages/paddle/base/core.py", line 369, in <module>
    if not avx_supported() and libpaddle.is_compiled_with_avx():
NameError: name 'libpaddle' is not defined

### 版本&环境信息 Version & Environment Information

![269927744-bd2cfc4c-f1a6-4665-a972-a9c9dc59091f](https://github.com/PaddlePaddle/Paddle/assets/145744711/028c3b2e-caa1-4255-9348-138c58614379)
docker使用下面的方式创建的
下载 Dockerfile
$ wget https://paddlelite-demo.bj.bcebos.com/devices/huawei/ascend/kunpeng920_arm/Ascend_ubuntu18.04_aarch64.Dockerfile
通过 Dockerfile 生成镜像
$ docker build --network=host -f Ascend_ubuntu18.04_aarch64.Dockerfile -t paddlelite/ascend_aarch64:cann_3.3.0 .
创建容器
$ docker run -itd --name=ascend-aarch64 --net=host -v $PWD:/Work -w /Work --device=/dev/davinci0 --device=/dev/davinci_manager --device=/dev/hisi_hdc --device /dev/devmm_svm -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi -v /usr/local/Ascend/driver/:/usr/local/Ascend/driver/ paddlelite/ascend_aarch64:cann_3.3.0 /bin/bash
进入容器
$ docker exec -it ascend-aarch64 /bin/bash
paddle源码使用下面的代码编译的
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

**Comment by warrentdrew** [comment]
您好，问题已经收到，会联系相关同学跟进

**Comment by risemeup1** [comment]
看着是arm的机器，编译的时候应该设置avx=off吧

**Comment by lijialin1999** [comment]
> 看着是arm的机器，编译的时候应该设置avx=off吧

对，是arm的机器，avx=off是设置为-DWITH_AVX=OFF这样吗

**Comment by lijialin1999** [comment]
> 看着是arm的机器，编译的时候应该设置avx=off吧

使用cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_AVX=OFF编译之后import paddle还是报了和之前同样的错误

**Comment by risemeup1** [comment]
给个复现的步骤吧，我复现一下

**Comment by risemeup1** [comment]
把原来的paddle卸载了重新装呢

**Comment by lijialin1999** [comment]
> 给个复现的步骤吧，我复现一下

我是进入docker里之后git clone --recursive https://github.com/PaddlePaddle/Paddle.git
cd Paddle
git checkout develop
mkdir build && cd build
ulimit -n 4096
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DWITH_AVX=OFF
make TARGET=ARMV8 -j$(nproc)
然后再进入/build/python/dist，pip3 install 那个.whl包，安装成功之后import就错误

**Comment by lijialin1999** [comment]
> 把原来的paddle卸载了重新装呢

这个方法试了大概有6.7遍了，一直是报同一个错误，编译啥的都没有问题，就是最后导入的时候报错

**Comment by risemeup1** [comment]
为啥不用我们提供的docker镜像啊啊

**Comment by lijialin1999** [comment]
> 为啥不用我们提供的docker镜像啊啊

因为要部署NPU，所以就照着https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html这个文档进行操作的

**Comment by risemeup1** [comment]
好的，我们研究下

**Comment by lijialin1999** [comment]
> 好的，我们研究下

好的，麻烦您们了

**Comment by qili93** [comment]
您好，昇腾相关的支持都已经全部迁移到 PaddleCustomDevice，请参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档进行编译安装。

**Comment by lijialin1999** [comment]
> 好的，我们研究下

你好，请问现在有解决办法了吗？
