### ISSUE TITLE
报错ModuleNotFoundError: No module named 'paddle.nn.layer.layers'，且已经安装了底版本的paddlepaddle

### ISSUE THREAD

**Issue by ZXHe23** [PaddlePaddle/Paddle#57723]
### 请提出你的问题 Please ask your question

改了版本
!pip install pgl==1.2.1 # 安装PGL
!pip install paddlepaddle==2.0
但是依然会报错

**Comment by warrentdrew** [comment]
您好，确认下安装的是cpu版本的paddlepaddle吗，是否尝试过2.5.1等最新的版本
