### ISSUE TITLE
能否提供pip直装的aarch64环境的PaddlePaddle包？

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#57729]
### 需求描述 Feature Description

aarch64环境越来越多，隔壁pytorch和tensflow都已经有直接安装的包了，希望官方尽早提供下，感谢！

**Comment by GhostScreaming** [comment]
已经和负责编译的同学反馈这个问题，非常感谢您的建议~

**Comment by risemeup1** [comment]
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/windows/cpu-mkl-avx/develop.html

**Comment by risemeup1** [comment]
python -m pip install paddlepaddle==0.0.0 -f https://www.paddlepaddle.org.cn/whl/linux/cpu-mkl/develop.html
