### ISSUE TITLE
Running error using ai studio notebook

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/Paddle#57735]
### use wandb error

![无标题](https://github.com/PaddlePaddle/Paddle/assets/71805205/dd1e0629-b69c-4880-b1aa-07f0086482b4)

**Comment by GhostScreaming** [comment]
看着报错是权限的问题，无法创建文件夹，先排查下相关问题？

**Comment by Yang-Changhui** [comment]
但是在ai studio中，并没有root权限，而且之前运行是没问题的，就前两天报错了

**Comment by sunzhongkai588** [comment]
应该是AIStudio的问题，在 AI Studio 官网中的「问题反馈」处反馈
![image](https://github.com/PaddlePaddle/Paddle/assets/70642955/2005dd15-7e5b-43e6-a1f2-14f18e5b74fb)
