### ISSUE TITLE
Paddle gpu  Add support for AMD  ROCm

### ISSUE THREAD

**Issue by mrs01dev** [PaddlePaddle/Paddle#57758]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

### 替代实现 Alternatives

PaddlePaddle v2.5
(
https://www.paddlepaddle.org.cn/en
https://www.paddlepaddle.org.cn/documentation/docs/zh/install/pip/linux-pip.html
)
Does not support  AMD  ROCm V5
(
https://rocm.docs.amd.com/en/latest/release/gpu_os_support.html
https://rocm.docs.amd.com/en/latest/release/windows_support.html
)
![image](https://github.com/PaddlePaddle/Paddle/assets/64358630/a37fb7ec-2b20-40e2-9d5d-ee2f4785f248)

Please Add support for AMD  ROCm V5

**Comment by engineer1109** [comment]
Rocm在僵尸状态 无人维护
