### ISSUE TITLE
CPAI如何获取多个Loss中的output值

### ISSUE THREAD

**Issue by alanse7en** [PaddlePaddle/Paddle#5777]
请教一个问题，我们的网络结构中有类似于GoogLeNet那样的多个Loss，部分代码如下：
```
//其中net_conf为一些网络结构的参数配置，out1和out2分别为两个Softmax输出
out1, out2, label = XNNModel(net_conf)
loss1 = paddle.layer.classification_cost(input = out1, label = label, coeff = 0.3)
extra_layers = [loss1]
cost = paddle.layer.classification_cost(input = out2, label = label)
```
在CAPI中，通过paddle_gradient_machine_forward(machine, in_args, out_args, false)这个接口获取模型的输出值，貌似只能取到cost里的输出层out2，我通过paddle_arguments_get_size这个接口确认了out_args只有一个slot，有没有办法取到out1的值呢？

**Comment by Xreki** [comment]
- 理论上，如果你的config里面输出有3个layer，那么`paddle_arguments_get_size(out_args)`获取到的值会是3。你获取到的size为1，那多半是你的config不对。
- C-API现在只支持预测，既然你是预测，为何需要`loss`呢？

**Comment by alanse7en** [comment]
我感觉可能是我在生成trainer_config.bin的时候有问题，现在生成的代码是这样的：
```
out1, out2, label = snn.SNN(net_conf)
network = parse_network(out2)
sys.stdout.write(network.SerializeToString())
```
改成下面这样，可以吗？
```
out1, out2, label = snn.SNN(net_conf)
loss1 = paddle.layer.classification_cost(input = out1, label = label, coeff = 0.3)
extra_layers = [loss1]
cost = paddle.layer.classification_cost(input = out2, label = label)
network = parse_network(cost)
sys.stdout.write(network.SerializeToString())
```
但是有一个问题，在训练过程中extra_layer是在trainer里设置的，`parse_network`的输入只有`cost`，这样去dump出来的config文件，是包含了`out1, out2, label`三个变量的？

**Comment by alanse7en** [comment]
补充一下，在训练的代码中，extra_layer的使用参考的  http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html  里的：
```
extra_layers = [loss1]
trainer = paddle.trainer.SGD(
    cost=cost,
    parameters=parameters,
    update_equation=optimizer,
    extra_layers=extra_layers)
```

**Comment by will-am** [comment]
试试在网络的配置文件中最后写成outputs([out1, out2, loss1, cost])这样

**Comment by chengduoZH** [comment]
该issue长时间没有反馈，可以先关闭了，如要继续讨论请再打开
