### ISSUE TITLE
训练过程结束后动转静模型，报相关unbind op的错误

### ISSUE THREAD

**Issue by jluhuangj** [PaddlePaddle/Paddle#57771]
### 需求描述 Feature Description

<img width="1166" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/21163785/8e7dd092-3f69-4b9f-bb09-12502257469f">

请问这个paddle.unbind op是不支持动转静吗？如果不支持的话，有什么可替代方案呢？
背景：在tensor的第0个维度(batch维度）进行unbind，后续对分开的每个tensor进行for循环遍历

**Comment by Aurelius84** [comment]
@jluhuangj 请问你这里 input.shape[axis] 的值是多少？是大于0的么？

**Comment by jluhuangj** [comment]
实际值是batch_size，所以是大于0的

**Comment by Aurelius84** [comment]
> 实际值是batch_size，所以是大于0的

@jluhuangj 这个要看动转静组网时 input 的shape值，「实际值」指的是运行期吧。可以在你模型中用到 unbind API 的前一行插入`breakpoint()` 进入pdb调试页面，使用`p ${your_input}` 查看下此时具体的shape是多少（要确认是动转静时，而非动态图时）。pdb命令使用参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/jit/debugging_cn.html#ertiaoshifangfa

另外，你在模型导出时，是不是指定了batch_size 维度为-1？
