### ISSUE TITLE
forwardTest非常消耗内存

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#578]
执行序列数据分类任务，序列长度10以内，分类label约7w，测试样本条数大概8w条，内存消耗了35g，
打印日志发现内存消耗主要在`output = self.network.forwardTest(input)`这里。

**Comment by backyes** [comment]
模型本身的size 多大？ 另外如果是seqtoseq模型，内存消耗会和sample的序列长度也有关系。 

@pengli09 @lcy-seso  两位有空可以给出更加专业的临床经验。

**Comment by 333caowei** [comment]
@backyes     
hidden size 256的一层simple lstm，做分类用。
softmax层稍微大一些分类label 7w。
序列长度倒是很短，百分之90的序列长度都在5以内。test样本数8w左右。

**Comment by pengli09** [comment]
我猜你是把所有数据一下全都load到内存里当作一个batch来做预测了吧？建议分成多个batch来做预测，如每读入1000条数据做一次预测，内存自然就降下来了。
