### ISSUE TITLE
分布式API显存占用不符合预期

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#57804]
### bug描述 Describe the Bug

1.  `broadcast_dp_parameters` 函数没有检查dp数为1 的时候，单路dp依然执行广播策略。
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/fleet/meta_parallel/tensor_parallel.py#L45C9-L45C32

2. `sync_params_buffers` 默认 fuse_params，会产生一份参数拷贝，增大显存占用。
https://github.com/PaddlePaddle/Paddle/blob/363d8b0be5d302801045ec8561382da54e50c737/python/paddle/distributed/parallel.py#L179
https://github.com/PaddlePaddle/Paddle/blob/363d8b0be5d302801045ec8561382da54e50c737/python/paddle/distributed/parallel.py#L89

**Comment by haohongxiang** [comment]
1. 这里应该是个bug，没有加DP并行数的判断；
2. 之前提过一个优化fused_allreduce显存的[PR](https://github.com/PaddlePaddle/Paddle/pull/54610)，但暂时没有验证过；sync这里也可以用类似的优化方式。

后续会对这两处进行修复和优化。
