### ISSUE TITLE
Confusing APIs under paddle.device

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#57812]
### 问题描述 Please describe your issue

stream:`paddle.device.current_stream` `paddle.device.stream`  `paddle.device.set_device` `paddle.device.stream_guard` `paddle.device.event`
context:`paddle.device.get_cudnn_version`

are not suitable for all devices or contexts, for example, a CPU has no stream and a XPU has no cudnn.

**Comment by ronny1996** [comment]
paddle.device.current_stream/paddle.device.stream/paddle.device.set_device/paddle.device.stream_guard/paddle.device.event only support custom_device/xpu/gpu

paddle.device.get_cudnn_version only supports gpu
