### ISSUE TITLE
在NPU上编译Paddle失败

### ISSUE THREAD

**Issue by cloud2009** [PaddlePaddle/Paddle#57830]
### bug描述 Describe the Bug

按照官网给的编译教程，无法编译。

执行官网教程代码
![9031b72a5a0123390e88caba5c2741cc](https://github.com/PaddlePaddle/Paddle/assets/113963162/b4f5e52c-1aa6-4f90-b022-f1d5fb2ca7b7)

报错
![1c32951f015e89d32230771c8ede12a4](https://github.com/PaddlePaddle/Paddle/assets/113963162/f14b5584-26a6-4747-a5d9-9afb0675215b)

**Comment by YanhuiDua** [comment]
你好，目前NPU相关代码移动至PaddleCustomDevice，请参考：https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 进行编译，有问题欢迎再提问

**Comment by cloud2009** [comment]
好的 谢谢
