### ISSUE TITLE
Paddle导出模型时能否新增模型运行时的OP的数据类型

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle#57846]
### 需求描述 Feature Description

# 1 体验不友好场景介绍

## 1.1 Paddle和ONNX模型的算子差异

在Paddle静态图模型转ONNX模型时会发现一个棘手的问题，Paddle静态图模型和ONNX模型支持的数据类型不一致，例如Log算子在Paddle静态图下不支持FP16，因此在导出时会插入Cast节点，如下图:

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/e1d5227f-3738-4365-bc0b-b98c3c0da611)

但是ONNX其实是支持Log算子直接在FP16下运行的，如下图:

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/067d605d-5f3c-4ebf-9d10-5d9e1d01260f)

这就会多进行两次Cast操作造成性能浪费

## 1.2 ~~Paddle和ONNX参数类型差异~~

~~在Paddle静态图模型转ONNX模型时会发现一个棘手的问题，Paddle静态图模型和ONNX模型支持的数据类型不一致，例如BN算子在Paddle静态图下支持输入数据为FP16，参数为FP32，如下图:~~

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/975de605-3545-4746-8d6a-8f0962be82ab)

~~但是ONNX实际上仅支持输入参数与OP节点参数一致，目前和 @jiangjiajun 讨论的方法是在Paddle2ONNX导出时插入Cast节点并进行图优化来解决这个问题。但是实际上会发现，图优化无法优化掉Cast算子，如下图:~~

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/f14ab93d-6512-4ef5-9eba-84d63e10f96b)

~~这就会造成两个问题:~~

* ~~导出的ONNX模型在使用netron可视化相当丑陋，不至于令人作呕，但至少令人反感~~
* ~~ONNX模型性能会降低~~

# 2 设想的解决方案

Attr内插入当前算子最理想的运行状态，例如在BN/Log算子上插入"float16"的状态，Paddle2ONNX在读取到状态时删除前后Cast操作，在输入参数和OP自带参数产生冲突时自动将OP参数在weight层面转换为输入参数的类型。

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/e6e6895d-be59-4e3b-97ba-3d0cc29f5775)

**Comment by Zheng-Bicheng** [comment]
问题1.2 已经通过动态升级ONNX OP版本来解决

**Comment by zhwesky2010** [comment]
@Zheng-Bicheng 请问你是用paddle.jit.save导出的模型结构吗

**Comment by zhwesky2010** [comment]
关于用户提到的这个方案：
> Attr内插入当前算子最理想的运行状态，例如在BN/Log算子上插入"float16"的状态，Paddle2ONNX在读取到状态时删除前后Cast操作，在输入参数和OP自带参数产生冲突时自动将OP参数在weight层面转换为输入参数的类型。

@jiangjiajun 评估觉得有可行和必要吗

**Comment by zhwesky2010** [comment]
@Zheng-Bicheng 你好，有这个网络结构对应的源代码吗，有可能是本身API就插入了cast 来适配FP16的运行，正常情况下，网络结构不是只针对某种特定数据类型或设备类型的，这些都是根据输入的Tensor来决定的，所以网络结构里存储数据类型、设备类型可能不太合理。

![image](https://github.com/PaddlePaddle/Paddle/assets/52485244/134cb344-8036-42b4-8827-810fc6228ec2)

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 请问你是用paddle.jit.save导出的模型结构吗

```
from paddle.inference import PrecisionType, PlaceType
from paddle.inference import convert_to_mixed_precision
import argparse

if __name__ == "__main__":
    black_list = set()

    src_model = "./inference.pdmodel"
    src_params = "./inference.pdiparams"
    dst_model = "./inference_fp16.pdmodel"
    dst_params = "./inference_fp16.pdiparams"

    convert_to_mixed_precision(
        src_model,  # fp32模型文件路径
        src_params,  # fp32权重文件路径
        dst_model,  # 混合精度模型文件保存路径
        dst_params,  # 混合精度权重文件保存路径
        PrecisionType.Half,  # 转换精度，如 PrecisionType.Half
        PlaceType.GPU,  # 后端，如 PlaceType.GPU
        True,  # 保留输入输出精度信息，若为 True 则输入输出保留为 fp32 类型，否则转为 precision 类型
        black_list  # 黑名单列表，哪些 op 不需要进行精度类型转换
    )
```

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 你好，有这个网络结构对应的源代码吗，有可能是本身API就插入了cast 来适配FP16的运行，正常情况下，网络结构不是只针对某种特定数据类型或设备类型的，这些都是根据输入的Tensor来决定的，所以网络结构里存储数据类型、设备类型可能不太合理。
> 
> ![image](https://user-images.githubusercontent.com/52485244/273533198-134cb344-8036-42b4-8827-810fc6228ec2.png)

这个我用netron可视化过了，原模型的log算子就是FP32的，可能是PaddleInference暂不支持log算子的FP16计算？
