### ISSUE TITLE
paddle.device.cuda.empty_cache()

### ISSUE THREAD

**Issue by ray1a1** [PaddlePaddle/Paddle#57841]
### bug描述 Describe the Bug

我有三张显卡，其中一张上面推理语音结束后，想清空显卡的缓存，代码如下
        wav_all = self.voc_inference(mel)
        paddle.device.cuda.empty_cache()
然后就发现当前显卡的显存清出了大概600M的显存占用，但是另外两张GPU莫名各多出来600m占用。
我是用的多进程，让三张显卡都初始化并加载了tts_executor = TTSExecutor()

**Comment by zhwesky2010** [comment]
@ray1a1 你好，单进程也会有这个问题吗？

**Comment by zhwesky2010** [comment]
@From00 帮忙也看一下吧

**Comment by From00** [comment]
你好，请提供一份最小可运行脚本，方便我们复现问题。

**Comment by xbbkok** [comment]
@ray1a1 我也遇到了这个问题，两张卡，在0卡运行的模型，使用paddle.device.cuda.empty_cache()， 另一张原本不占gpu的卡就会显示占用100多MB的gpu
