### ISSUE TITLE
海光DCU安装2.4以后跑paddleocr报错

### ISSUE THREAD

**Issue by jingsongliujing** [PaddlePaddle/Paddle#57845]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/45508593/f804c315-0e9d-4931-ad4d-128c112bbbaf)
![image](https://github.com/PaddlePaddle/Paddle/assets/45508593/566bfa1f-7cbb-496f-a446-863d26c321cd)
![image](https://github.com/PaddlePaddle/Paddle/assets/45508593/bc74351b-ae8b-4399-8134-de075cede43b)
使用光合社区的正常：https://cancon.hpccube.com:65024/4/main/paddle

**Comment by zhwesky2010** [comment]
@ronny1996 麻烦看下这个问题

**Comment by ronny1996** [comment]
你好，请问你使用的镜像是什么？

**Comment by jingsongliujing** [comment]
&nbsp;docker pull image.sourcefind.cn:5000/dcu/admin/base/custom:tvm-0.11_fp32_cpp_dtk22.10_py38_centos-7.6-latest



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月8日(周日) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 海光DCU安装2.4以后跑paddleocr报错 (Issue #57845)




 
你好，请问你使用的镜像是什么？

**Comment by jingsongliujing** [comment]
是这个地址提供的: https://sourcefind.cn/#/model-zoo/1672505571511885826



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年10月8日(周日) 中午1:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 海光DCU安装2.4以后跑paddleocr报错 (Issue #57845)




 
你好，请问你使用的镜像是什么？

**Comment by ronny1996** [comment]
dtk镜像需要从源码编译paddle并安装

**Comment by jingsongliujing** [comment]
好的，感谢

**Comment by JiyaoWei** [comment]
您好，我docker pull光源镜像失败了，请问该怎么弄呢？

**Comment by JiyaoWei** [comment]
(base) [jy@622640 docker]$ docker pull image.sourcefind.cn:5000/dcu/admin/base/custom:tvm-0.11_fp32_cpp_dtk22.10_py38_centos-7.6-latest
Error response from daemon: Get "https://image.sourcefind.cn:5000/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
(base) [jy@622640 docker]$ cat daemon.json
{"insecure-registries":["sourcefind.cn:5000"] }
