### ISSUE TITLE
Unable to compile paddle on macos 14.0

### ISSUE THREAD

**Issue by GreatV** [PaddlePaddle/Paddle#57878]
### bug描述 Describe the Bug

```shell
cmake .. -DPY_VERSION=3.10 -DWITH_GPU=OFF -DWITH_AVX=OFF -DWITH_ARM=ON -DWITH_MKL=OFF -DWITH_TESTING=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
make -j$(nproc)
```

![](https://github.com/PaddlePaddle/Paddle/assets/17264618/868e87dc-58e1-41e4-ab74-a559f4761c1c)

### 其他补充信息 Additional Supplementary Information

I fixed the issue with the following command:

```shell
install_name_tool -add_rpath ./build/third_party/install/protobuf/bin/protoc-3.21.12.0
```

**Comment by risemeup1** [comment]
建议使用我们推荐的环境，我本地复现不了啊

**Comment by risemeup1** [comment]
你这个protobuf版本对吗？我们发版本用的编译的机器
<img width="294" alt="bea74f221d3953a72bc214fa1f6b618d" src="https://github.com/PaddlePaddle/Paddle/assets/62429225/1c6596a2-f5a2-469a-ba38-76db40535929">

**Comment by GreatV** [comment]
<img width="465" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/17264618/a43aa337-2bf0-4169-86c8-b2e27d8fd5a3">

这个是14.0新出现的问题，之前版本是ok的
