### ISSUE TITLE
本地build成功，PR-CI-Build失败

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#57870]
### 请提出你的问题 Please ask your question

- 描述
老师您好！
我目前在做第五期黑客松第50题。本地可以正常编译。
![image](https://github.com/PaddlePaddle/Paddle/assets/118546135/56fcca59-e1e3-478b-a565-df9f1bb030f9)
但是PR-CI-Build却失败了。
[build (11).log](https://github.com/PaddlePaddle/Paddle/files/12793883/build.11.log)
想请教您一下，这属于正常现象吗？能不能指导一下大概的解决方向？
非常感谢！
- 相关PR
https://github.com/PaddlePaddle/Paddle/pull/57866

**Comment by WintersMontagne10335** [comment]
会不会因为ai studio框架开发环境是单机单卡？那我该如何验证代码的对错呀？

**Comment by pangengzheng** [comment]
是修改后编译不过吗，还是本来就在PR-CI-Build编译不过？你这边对应的PR链接方便贴一下吗

**Comment by WintersMontagne10335** [comment]
> 是修改后编译不过吗，还是本来就在PR-CI-Build编译不过？你这边对应的PR链接方便贴一下吗

老师您好。
PR就是上面的那个。我的问题是，我修改了切分推导的代码，但是ai studio上编译的时候，却仿佛并没有编译那部分代码。代码是否有错误，得提交到CI上去看，感觉很不方便。不知道是不是因为单机单卡的原因。
