### ISSUE TITLE
mac上pip安装paddle初始化错误

### ISSUE THREAD

**Issue by huayong** [PaddlePaddle/Paddle#5789]
请教一个安装问题，
在mac上使用 pip install paddlepaddle 安装paddle，
import paddle.v2 as paddle运行成功，
但是在 paddle.init(use_gpu=False, trainer_count=1) 后错误，错误如下：
Fatal Python error: PyThreadState_Get: no current thread
[1]    2411 abort      python
查看可能是由于lib link原因：
otool -L core.so
结果：
core.so:
	@rpath/libpaddle_pybind.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/local/opt/python/Frameworks/Python.framework/Versions/2.7/Python (compatibility version 2.7.0, current version 2.7.0)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
全局扫描没有发现libpaddle_pybind.dylib，有没有人知道什么原因？

mac版本：10.12.6 
Anaconda版本python：2.7.14
系统python：2.7.10

**Comment by huayong** [comment]
python版本冲突，主要是以前使用brew安装过python，全部卸载掉，使用系统的没有问题

**Comment by typhoonzero** [comment]
赞👍
