### ISSUE TITLE
昇腾NPU版的Paddle是否有NPU加速效果呢？

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#57902]
### 请提出你的问题 Please ask your question

根据这个官方文档https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md配置好了Paddle，想问一下进入硬件后端cd backends/npu后运行代码会有NPU的加速效果吗？如果没有的话要怎样才能调用NPU进行加速呢？

**Comment by Sophia-stargithub** [comment]
根据这个官方文档https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md，配置失败了，可以开源一下paddle-npu包嘛

**Comment by qili93** [comment]
您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请

<img width="1304" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/484b9329-dc3c-4498-8f9b-6fb7dd82c6b1">

**Comment by lijialin1999** [comment]
> 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> 
> <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">

我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html  这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远
![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/fdcf62c8-122a-438e-b18d-f38349dc8a7c)

**Comment by Sophia-stargithub** [comment]
已经向官网申请编译好的包了，能直接提供吗？
昇腾910+arm64；
想问一下昇腾310不转模型，直接安装编号好的paddle包可以运行吗

**Comment by hong19860320** [comment]
> > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> 
> 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)

80ms 完全不符合预期，看起来是跑在了 CPU 上，建议按照文档修改下列步骤，执行完后把 log.txt 上传上来。
`
./run.sh mobilenet_v1_fp32_224 linux arm64 huawei_ascend_npu >log.txt 2>&1
`

**Comment by onecatcn** [comment]
> > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> 
> 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)

310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动）
如果按照910的安装说明，就没有paddlelite提供的推理加速特性了

**Comment by lijialin1999** [comment]
> > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > 
> > 
> > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> 
> 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了

我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md  这个文档了

**Comment by lijialin1999** [comment]
> > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > 
> > 
> > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> 
> 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了

https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 所以这个文档就是只能910使用吗？

**Comment by onecatcn** [comment]
> > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > 
> > 
> > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> 
> 80ms 完全不符合预期，看起来是跑在了 CPU 上，建议按照文档修改下列步骤，执行完后把 log.txt 上传上来。 `./run.sh mobilenet_v1_fp32_224 linux arm64 huawei_ascend_npu >log.txt 2>&1`

@lijialin1999 如果需要debug，可以按照我们同事的建议上传log哈

**Comment by onecatcn** [comment]
> > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > 
> > > 
> > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > 
> > 
> > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> 
> 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了

能发一下安装出错的issue吗？我们去看一下。
PaddleLite与custom device对ascend硬件的适配方式不一样，性能会有差异。

**Comment by hong19860320** [comment]
> > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > 
> > > 
> > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > 
> > 
> > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> 
> 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了

paddlelite+ascend npu 的文档里是 c++ demo ，没有import 这步骤哈~

**Comment by onecatcn** [comment]
> > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > 
> > > 
> > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > 
> > 
> > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> 
> https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 所以这个文档就是只能910使用吗？

这是训练安装说明，需要硬件安装训练的toolkit。我们的测试都基于训练硬件，没有在推理硬件测试过。
理论上310芯片要是可以安装训练的toolkit的话应该就可以，但因为310芯片是推理卡，可能装不了训练的toolkit，这个可能得问硬件厂商哈。

**Comment by lijialin1999** [comment]
> > > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > > 
> > > > 
> > > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > > 
> > > 
> > > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> > 
> > 
> > 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了
> 
> paddlelite+ascend npu 的文档里是 c++ demo ，没有import 这步骤哈~

我是根据https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档配置好了docker，然后又根据https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这个文档编译paddlepaddle，在最后import的时候报了错误

**Comment by lijialin1999** [comment]
> > > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > > 
> > > > 
> > > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > > 
> > > 
> > > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> > 
> > 
> > https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 所以这个文档就是只能910使用吗？
> 
> 这是训练安装说明，需要硬件安装训练的toolkit。我们的测试都基于训练硬件，没有在推理硬件测试过。 理论上310芯片要是可以安装训练的toolkit的话应该就可以，但因为310芯片是推理卡，可能装不了训练的toolkit，这个可能得问硬件厂商哈。

https://github.com/PaddlePaddle/Paddle/issues/57725 这个是我当时报错发的issues

**Comment by lijialin1999** [comment]
> > > > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > > > 
> > > > > 
> > > > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > > > 
> > > > 
> > > > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> > > 
> > > 
> > > 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了
> > 
> > 
> > paddlelite+ascend npu 的文档里是 c++ demo ，没有import 这步骤哈~
> 
> 我是根据https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档配置好了docker，然后又根据https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这个文档编译paddlepaddle，在最后import的时候报了错误

我之前按照这种方式在6月份配置成功了一台电脑，但是现在第二台电脑前面都没问题，就在最后import的时候报了错误

**Comment by onecatcn** [comment]
> > > > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > > > 
> > > > > 
> > > > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > > > 
> > > > 
> > > > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> > > 
> > > 
> > > 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了
> > 
> > 
> > paddlelite+ascend npu 的文档里是 c++ demo ，没有import 这步骤哈~
> 
> 我是根据https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档配置好了docker，然后又根据https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这个文档编译paddlepaddle，在最后import的时候报了错误

建议完全follow：https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html  进行安装哈～

**Comment by lijialin1999** [comment]
> > > > > > > 您说的加速效果如果是指算子内核运行在昇腾NPU上的话，是的，参考此文档进行编译安装运行之后，模型会运行在昇腾NPU上，运行示例请参考README中功能验证部分。 目前昇腾仅支持i远吗编译，paddle-custom-npu 的安装包请在飞桨官网首页的 https://www.paddlepaddle.org.cn/install 的如下链接中申请
> > > > > > > <img alt="image" width="1304" src="https://user-images.githubusercontent.com/16605440/273433253-484b9329-dc3c-4498-8f9b-6fb7dd82c6b1.png">
> > > > > > 
> > > > > > 
> > > > > > 我的设备是昇腾310，但是根据此文档编译成功了，可是我在NPU上运行https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档里的程序时发现预测时间高达80ms，和文档中展示的相差甚远 ![image](https://user-images.githubusercontent.com/145744711/273435084-fdcf62c8-122a-438e-b18d-f38349dc8a7c.png)
> > > > > 
> > > > > 
> > > > > 310应该按照https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档的介绍安装（包括驱动） 如果按照910的安装说明，就没有paddlelite提供的推理加速特性了
> > > > 
> > > > 
> > > > 我之前确实是安装这个文档安装的，但是到了最后一步import的时候报了错，我发了issues询问，然后给我的回复是昇腾相关的支持全部转移到https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档了
> > > 
> > > 
> > > paddlelite+ascend npu 的文档里是 c++ demo ，没有import 这步骤哈~
> > 
> > 
> > 我是根据https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档配置好了docker，然后又根据https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这个文档编译paddlepaddle，在最后import的时候报了错误
> 
> 建议完全follow：https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 进行安装哈～

但是这个文档里没有介绍如何安装paddlepaddle，但是我又会用到，所以就只能按照另一个文档编译了

**Comment by onecatcn** [comment]
custom device是训推一体的方案，paddlelite是纯推理方案
具体到模型推理性能上，取决于不同的模型，2个方案的性能有差异。
