### ISSUE TITLE
请问一下paddle-cpu的官方编译发布版本，编译环境依赖的底层glibc的版本是多少？

### ISSUE THREAD

**Issue by xiaoyewww** [PaddlePaddle/Paddle#57911]
### 请提出你的问题 Please ask your question

请问一下paddle-cpu的官方编译发布版本，编译环境依赖的底层glibc的版本是多少？

**Comment by songh11** [comment]
我本地是 libstdc++.so.6.0.21 会出错

**Comment by xiaoyewww** [comment]
> 我本地是 libstdc++.so.6.0.21 会出错

我自己本地环境编译也会出错，而且好像如果是编译好的版本，很难查出来依赖的gnu版本？
