### ISSUE TITLE
昇腾NPU版paddle源码编译

### ISSUE THREAD

**Issue by Sophia-stargithub** [PaddlePaddle/Paddle#57913]
### 问题描述 Issue Description

根据这个文档https://www.paddlepaddle.org.cn/documentation/docs/zh/2.2/guides/09_hardware_support/npu_docs/paddle_install_cn.html编译昇腾NPU版paddle包，在编译过程中Built target fluid_lib_dist时卡住不动了，请问该怎么解决呢

### 版本&环境信息 Version & Environment Information

Operating System: EulerOS 2.0 (SP10)
Architecture: arm64
gcc (GCC) 8.2.0
cmake version 3.19.8

git clone -b release/2.2 https://github.com/PaddlePaddle/Paddle.git

**Comment by qili93** [comment]
您好，昇腾相关代码已经迁移，请参考 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档进行源码编译和安装。

**Comment by Sophia-stargithub** [comment]
参考
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
这个文档源码编译时，在git更新时报错了，连接github不稳定

`+ set +e
+ cmake .. -DCMAKE_BUILD_TYPE=Release -DWITH_TESTING=ON -DWITH_MKLDNN=OFF -DWITH_ARM=ON -DWITH_ASCEND_TRANSFORMER_ACC=OFF -DON_INFER=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
I1008 19:26:06.233048    64 init.cc:233] ENV [CUSTOM_DEVICE_ROOT]=""
I1008 19:26:06.233099    64 init.cc:142] Try loading custom device libs from: [""]
I1008 19:26:06.233163    64 custom_kernel.cc:39] No custom kernel info found in loaded lib(s).
I1008 19:26:06.233170    64 init.cc:154] Finished in LoadCustomDevice with libs_path: [""]
-- PADDLE_CORE_LIB: /opt/py39/lib/python3.9/site-packages/paddle/base/libpaddle.so
-- Run 'git submodule update --init Paddle' in /usr/local/Ascend/PaddleCustomDevice-develop
fatal: not a git repository (or any of the parent directories): .git
CMake Error at cmake/paddle.cmake:72 (message):
  Failed to get submodule Paddle', please check your network !
Call Stack (most recent call first):
  CMakeLists.txt:22 (include)


-- Configuring incomplete, errors occurred!
See also "/usr/local/Ascend/PaddleCustomDevice-develop/backends/npu/build/CMakeFiles/CMakeOutput.log".
+ cmake_error=1
+ '[' 1 '!=' 0 ']'
+ echo 'CMake Error Found !!!'
CMake Error Found !!!
+ exit 7`

**Comment by qili93** [comment]
github网络问题，请先尝试解决网络后重试。

**Comment by yinpeng-cn** [comment]
能够详细说明一下 paddle2.5.1中环境和编译参数吗  根据指导https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md   根本无法完成编译 C++目标。
1. 引入simd时 出现链接错误，比如竟然有-lpthreads的链接要求，或者 对于C中引入c++的参数（      -Wnon-virtual-dtor
      -Wdelete-non-virtual-dtor  flags.cmake）
2. 强制关闭 GPU、XPU选项并不起作用，xpu_kp.cmake仍然生效；
3. 在手动关闭某些cmake参数后，无法生成对应的makefile文件。

怀疑：
1、docker pull registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82 环境不完整，无法支撑顺畅编译；
2、https://github.com/PaddlePaddle/Paddle 的develop分支 以及 v2.5.1 分支 在arm64+npu下不能使用镜像编译；
3、或编译参数不正确，目前使用的参数为 
cmake .. -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON \
         -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_AVX=OFF -DWITH_DISTRIBUTE=OFF -DWITH_DLNNE=OFF \
         -DWITH_ARM=ON -DWITH_LITE=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_XPU=OFF \
         -DCMAKE_CXX_FLAGS="-Wno-error -w" -DCMAKE_C_FLAGS="-w -pthread -z max-page-size=0x10000"

另：
CPU：ft2000+，NPU ：昇腾 310 ，CANN601。

遍寻所有资料，暂无法找到参考依据，请提供解决方法或确定编译通过的过程及参数，谢谢。

**Comment by qili93** [comment]
您好，https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md  目前只能支持昇腾910芯片，昇腾310的推理芯片请参考 https://www.paddlepaddle.org.cn/lite/v2.12/demo_guides/huawei_ascend_npu.html 这个文档进行推理部署。

**Comment by yinpeng-cn** [comment]
> 您好，https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 目前只能支持昇腾910芯片，昇腾310的推理芯片请参考 https://www.paddlepaddle.org.cn/lite/v2.12/demo_guides/huawei_ascend_npu.html 这个文档进行推理部署。

这是官方回答吗？
1我是需要从源码编译出paddle-inference的源代码；
2.根据文档部署好对应的CANN版本后，编译出NPU版本的lib_custom_npu.so；
上述两个目标和要不要推理并没有任何关系。

目标是根据指导文档能编译出对应环境的需要的版本，并且希望提供对应的cmake参数和准确的环境设置。

**Comment by Sophia-stargithub** [comment]
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

请问什么时候可以开源昇腾910+arm64的安装包呢，根据上述文档本地编译一直失败，向官方申请两天了目前没有响应

**Comment by qili93** [comment]
您好，您遇到的编译问题，主要是由于开发文档中的开发镜像 cann601-ubuntu18-aarch64-gcc82 以及其中安装的 Ascend. toolkit 等软件都是基于鲲鹏920CPU构建的，无法直接用于飞腾CPU FT2000+，因此导致的编译失败。

目前飞桨对昇腾NPU芯片支持的ARM CPU为鲲鹏920 CPU，飞桨开源社区暂未支持飞腾CPU和昇腾NPU的适配组合，如果您有这个组合的需求请联系飞桨商业团队寻求定制开发的支持。商业支持的联系入口：https://www.paddlepaddle.org.cn/install/customerinfo

昇腾设备型号对应关系，请参考
<img width="1257" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1b6044ef-2c22-4ff5-9e3c-f3472506d4c1">

以上截图的入口位于：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
