### ISSUE TITLE
paddle对国产化设备的适配情况

### ISSUE THREAD

**Issue by QAQTATQAQTAT** [PaddlePaddle/Paddle#57922]
### 请提出你的问题 Please ask your question

1. paddle2.5.1在FT2000+昆仑R200显卡下是否适配
2. ppyolo_e_r旋转框能否在FT2000+昆仑R200显卡下推理训练

**Comment by engineer1109** [comment]
如果是Arm架构，你应该问昆仑是否有Arm版的驱动包

**Comment by engineer1109** [comment]
一般国产化，都是围绕着自己公司喜欢的方式做

**Comment by QAQTATQAQTAT** [comment]
昆仑R200在FT-2000下已经具备了相关的xpu驱动，目前是想了解paddlepaddle能否在该配置下正常编译使用

**Comment by engineer1109** [comment]
既然有了驱动，昆仑难道会不对自己的产品做适配？
能不能编译自己动手

**Comment by qili93** [comment]
ppyolo_e_r 这个模型之前在昆仑上没有适配过，可能会有问题，暂不支持。

**Comment by QAQTATQAQTAT** [comment]
> ppyolo_e_r 这个模型之前在昆仑上没有适配过，可能会有问题，暂不支持。

感谢您的回答，初次接触相关领域，了解很少，还想请教下s2anet和fcosr有适配过吗

**Comment by QAQTATQAQTAT** [comment]
> 既然有了驱动，昆仑难道会不对自己的产品做适配？ 能不能编译自己动手
在安装文档中有提到相关的硬件编译内容，但是版本不太明确，我是想确定下适配设备的最新的paddl框架版本来开展编译工作

**Comment by qili93** [comment]
> > ppyolo_e_r 这个模型之前在昆仑上没有适配过，可能会有问题，暂不支持。
> 
> 感谢您的回答，初次接触相关领域，了解很少，还想请教下s2anet和fcosr有适配过吗

这两个模型也暂时没有适配。
