### ISSUE TITLE
pr_57160 引入 solov2 模型在 trt8.6 下推理报错：RuntimeError: (NotFound) Can not find unsqueeze2_13.tmp_0_subgraph_2027 presistale var in scope.

### ISSUE THREAD

**Issue by EmmonsCurse** [PaddlePaddle/Paddle#57935]
### 错误信息
错误引入 PR: https://github.com/PaddlePaddle/Paddle/pull/57160
case 地址：https://github.com/PaddlePaddle/PaddleTest/blob/develop/inference/python_api_test/test_det_model/test_solov2_trt_fp32.py

镜像：registry.baidubce.com/paddlepaddle/paddle_manylinux_devel:cuda12.0-cudnn8.9-trt8.6-gcc12.2

错误类型：solov2 模型在 trt8.6 下推理报错：RuntimeError: (NotFound) Can not find unsqueeze2_13.tmp_0_subgraph_2027 presistale var in scope.

### Bug 复现步骤
**1、 环境配置**

* PaddlePaddle版本：develop
* CPU/GPU（GPU驱动、CUDA、cuDNN版本）：cuda12.0-cudnn8.9.1-trt8.6.1.6
* 操作系统版本：CentOS
* Python版本：3.10

**2、执行步骤**
2.1 基于对应镜像构建容器并配置好环境
2.1.1 起容器后进入
2.1.2 配置依赖
```
export LD_LIBRARY_PATH=/opt/_internal/cpython-3.10.0/lib/:${LD_LIBRARY_PATH}
export PATH=/opt/_internal/cpython-3.10.0/bin/:${PATH}
export LD_LIBRARY_PATH=/usr/local/TensorRT-8.6.1.6/lib:$LD_LIBRARY_PATH
export CUDA_MODULE_LOADING=LAZY
export PYTHON_FLAGS="-DPYTHON_EXECUTABLE:FILEPATH=/opt/_internal/cpython-3.10.0/bin/python3.10 -DPYTHON_INCLUDE_DIR:PATH=/opt/_internal/cpython-3.10.0/include/python3.10 -DPYTHON_LIBRARIES:FILEPATH=/opt/_internal/cpython-3.10.0/lib/libpython3.so"
ldconfig; 
```
2.1.3 下载 case 并安装 case 依赖以及推荐镜像对应的 paddle whl
```
git clone https://github.com/PaddlePaddle/PaddleTest.git --depth=1

cd ./PaddleTest/inference/python_api_test

python -m pip install -r ./requirements.txt -i https://mirror.baidu.com/pypi/simple

wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-TagBuild-Training-Linux-Gpu-Cuda12.0-Cudnn8.9-Trt8.6-Mkl-Avx-Gcc12.2/latest/paddlepaddle_gpu-0.0.0.post120-cp310-cp310-linux_x86_64.whl

python -m pip install paddlepaddle_gpu-0.0.0.post120-cp310-cp310-linux_x86_64.whl
```

2.1.4 执行 case
```
cd test_det_model
python -m pytest -m server -k trt --disable-warnings -sv test_solov2_trt_fp32.py
```

### 其他补充信息 Additional Supplementary Information

@leo0519 @Wangzheee 辛苦两位看一下哈～

**Comment by leo0519** [comment]
[PR-58015](https://github.com/PaddlePaddle/Paddle/pull/58015) addresses this issue, and it's waiting for CI and review.

**Comment by leo0519** [comment]
Hi @EmmonsCurse , the PR that addresses this issue was merged. Could you try the latest develop branch for verification?

**Comment by EmmonsCurse** [comment]
> Hi @EmmonsCurse , the PR that addresses this issue was merged. Could you try the latest develop branch for verification?

@leo0519 Okay, I'm currently verifying and the results will be given later. Thanks~

**Comment by EmmonsCurse** [comment]
> > Hi @EmmonsCurse , the PR that addresses this issue was merged. Could you try the latest develop branch for verification?

@leo0519 Thank you, the problem has been fixed.
