### ISSUE TITLE
 paddle 中销毁实例只会释放部分显存资源 但只要不结束进程始终有一部分显存(691MiB)被占用.  

### ISSUE THREAD

**Issue by renoyuan** [PaddlePaddle/Paddle#57943]
### bug描述 Describe the Bug

 paddle 中销毁实例始终会释放部分显存资源 但只要不结束进程始终有一部分显存(691MiB)被占用.  
paddle 版本:
paddlepaddle-gpu==2.2.2.post101 
显卡信息:
Tesla T4  Driver  418.87.00  CUDA 10.1 

-----------------------
    def __del__(self):
        logger.info("销毁实例{}".format(self.__format__))
        device.cuda.empty_cache()
        self.predictor.clear_intermediate_tensor()
        self.predictor.try_shrink_memory()
        del self.predictor
        del self.input_tensor
        del self.output_tensors
        del self

**Comment by engineer1109** [comment]
模型内存不会被销毁

**Comment by guoshengCS** [comment]
del变量并使用`empty_cache`能够清空显存管理allocator控制的显存，可以如下check下，

```python
def check_memory_usage(msg=""):
    max_memory_allocated_size = paddle.device.cuda.max_memory_allocated()/(1024*1024*1024)
    max_memory_reserved_size = paddle.device.cuda.max_memory_reserved()/(1024*1024*1024)
    memory_allocated_size = paddle.device.cuda.memory_allocated()/(1024*1024*1024)
    memory_reserved_size = paddle.device.cuda.memory_reserved()/(1024*1024*1024)
    logger.warning(f"checking gpu memory usage {msg}:\nmax_memory_allocated_size: {max_memory_allocated_size}GB\nmax_memory_reserved_size: {max_memory_reserved_size}GB\nmemory_allocated_size: {memory_allocated_size}GB\nmemory_reserved_size: {memory_reserved_size}GB")
```

剩余部分显存是CUDA context持有的，还不是模型及显存管理allocator控制的显存，这个还没有接口能够释放，torch也是同样的情况
