### ISSUE TITLE
bfloat16 tensor can not be assigned with a number value

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#57950]
### bug描述 Describe the Bug

<img width="992" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/10242208/3b41d4fd-2cf3-42c7-b329-15adc38599f2">

### 其他补充信息 Additional Supplementary Information

 从以上报错信息可以看出，bfloat16 无法通过切片的方式赋值一个非 tensor 数值数据，可是 float16 是可以的。

**Comment by zoooo0820** [comment]
https://github.com/PaddlePaddle/Paddle/pull/58643 已支持

```python
>>> a = paddle.randn((3,4),dtype='bfloat16')
>>> a[1,2] = 10
>>> a
Tensor(shape=[3, 4], dtype=bfloat16, place=Place(gpu:0), stop_gradient=True,
       [[-1.04687500,  0.77734375,  0.08056641,  0.97656250],
        [-0.16113281,  0.67187500,  10.       , -1.60156250],
        [-0.54296875, -1.82812500, -0.44531250,  2.32812500]])
```
