### ISSUE TITLE
v100在fp32 recompute训练下报出bf16的warning

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#57974]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/24701efea0cbdf3439e24db331d313bb7f018824/python/paddle/amp/auto_cast.py#L379-L391
在v100设备上这里会莫名显示bf16的warning，怀疑是recompute的时候引入的bf16什么的，实际上跑的是fp32
应该判断enable=True的时候才显示这个warning？

### 其他补充信息 Additional Supplementary Information
![image](https://github.com/PaddlePaddle/Paddle/assets/50394665/fe1683fb-044d-42de-b153-2b06cc669999)

_No response_

**Comment by zhangting2020** [comment]
develop已经修复
