### ISSUE TITLE
AdamW是否支持稀疏参数优化

### ISSUE THREAD

**Issue by gracciechou** [PaddlePaddle/Paddle#57979]
### 请提出你的问题 Please ask your question

目前官网（https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/optimizer/AdamW_cn.html）
描述说：paddle的AdamW优化器不支持稀疏参数优化，请问这里指的是不支持稀疏卷积吗？我这边有2d稀疏卷积的情况下是能够使用AdamW进行优化的，并能训练出一个相对正常的结果，请问是否AdamW是否已经支持稀疏卷积了呢？是官网没有进行相应更新吗？
<img width="527" alt="f57a3fd0e0c463111d78e8ad2c0ad093" src="https://github.com/PaddlePaddle/Paddle/assets/37568145/2ad4537d-588a-49d9-9b14-29968ec190b4">

**Comment by tianshuo78520a** [comment]
和相关负责人确认，目前还没有支持。

**Comment by gracciechou** [comment]
那请问我使用AdamW 对含有稀疏卷积的模型进行训练，训练出来的结果是不置信的对吗？

**Comment by tianshuo78520a** [comment]
是的

**Comment by gracciechou** [comment]
想麻烦相关同学进一步确认一下，我们在训练时使用AdamW性能并不会劣化，想请问“不支持”具体指的是训练过程中部分参数不会被更新吗？还是说会有一些随机优化的操作，导致模型多次使用AdamW的性能会出现不稳定的情况呢？
