### ISSUE TITLE
关于paddle.device.get_available_device()返回值的问题

### ISSUE THREAD

**Issue by lmw0320** [PaddlePaddle/Paddle#57983]
### bug描述 Describe the Bug

安装有 GPU 的机器上调用 paddle.device.get_available_device() 返回空列表。
使用paddlepaddle-gpu:2.3.2.post112 版本，docker起的容器，透传了gpu参数。具体情况如下：
<img width="539" alt="273507414-c3691c10-04d9-4e50-953b-eb9721127944" src="https://github.com/PaddlePaddle/Paddle/assets/37755235/01c2bb96-a57f-4983-8ea4-94891756cd08">

如何正确调用paddle.device.get_available_device()或是get_available_custom_device()呢？？我就想获取实际可用的GPU，目的是希望能根据获取的信息，来自动切换GPU和CPU进行推理

**Comment by ronny1996** [comment]
paddle.device.get_available_device() 或是 get_available_custom_device() 目前都支持 custom device，并不支持GPU

**Comment by tianshuo78520a** [comment]
没有必要使用paddle获取gpu数量，可以使用lspci | grep -i nvidia，或者nvidia-smi进行获取？

如果你一定需要，可以使用paddle.device.cuda.device_count()进行获取。[参考文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/cuda/device_count_cn.html)

**Comment by lmw0320** [comment]
> 没有必要使用paddle获取gpu数量，可以使用lspci | grep -i nvidia，或者nvidia-smi进行获取？
> 
> 如果你一定需要，可以使用paddle.device.cuda.device_count()进行获取。[参考文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/device/cuda/device_count_cn.html)
我目前的确就是用的device.cuda.device_count()来解决的。 但是这种做法，我个人是感觉有点奇怪而已。
对于torch而言，其只要靠一个torch.cuda.is_available()可以很方便实现这个需求。。也就是说，对gpu和cpu的切换，是十分灵活的。而对paddle，我是个人感觉有些不够方便。 ---因为对于cpu和gpu的自动切换，我的需求是希望在代码中自动获取状态的布尔值，从而快速自适应环境。

**Comment by lmw0320** [comment]
> paddle.device.get_available_device() 或是 get_available_custom_device() 目前都支持 custom device，并不支持GPU

哦哦，只是这种名称，容易让人产生误解。。那就是只能使用cuda.device_count()来实现这个gpu和cpu的检测了。。

**Comment by tianshuo78520a** [comment]
> > paddle.device.get_available_device() 或是 get_available_custom_device() 目前都支持 custom device，并不支持GPU
> 
> 哦哦，只是这种名称，容易让人产生误解。。那就是只能使用cuda.device_count()来实现这个gpu和cpu的检测了。。

是的，目前只能自己写判断逻辑。
