### ISSUE TITLE
使用NPU版paddle进行功能验证的时候不成功

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#57995]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/873568a4-bf09-42ae-8da8-a6823d394966)
如图 所示，前面的一切步骤都正常，唯独在进行功能验证的时候报错了

**Comment by qili93** [comment]
您好，请提供您的运行的详细环境信息：

- 昇腾NPU的设备型号：310，910A，910B？
- 设备的CPU型号：Intel CPU 还是 鲲鹏920 CPU
- 容器内运行 npu-smi info 并提供输出结果

**Comment by lijialin1999** [comment]
> 您好，请提供您的运行的详细环境信息：
> 
> * 昇腾NPU的设备型号：310，910A，910B？
> * 设备的CPU型号：Intel CPU 还是 鲲鹏920 CPU
> * 容器内运行 npu-smi info 并提供输出结果

型号是310，CPU是飞腾D2000
![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/340d1a79-6b9c-4815-94ef-52cee14edffc)

**Comment by qili93** [comment]
目前飞桨对昇腾NPU芯片支持的ARM CPU为鲲鹏920 CPU，飞桨开源社区暂未支持飞腾CPU和昇腾NPU的适配组合，如果您有这个组合的需求请联系飞桨商业团队寻求定制开发的支持。商业支持的联系入口：https://www.paddlepaddle.org.cn/install/customerinfo

昇腾设备型号对应关系，请参考
<img width="1257" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1b6044ef-2c22-4ff5-9e3c-f3472506d4c1">

以上截图的入口位于：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
