### ISSUE TITLE
在使用NPU版paddle运行程序出现ModuleNotFoundError: No module named 'paddle.fluid '的错误

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#57992]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/0676d73c-353c-4565-922e-96a3925f9c72)

如图，我根据https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md  这个文档安装好paddle后运行程序报了ModuleNotFoundError: No module named 'paddle.fluid '的错误，该如何解决？

**Comment by lijialin1999** [comment]
> ### 请提出你的问题 Please ask your question
> ![image](https://user-images.githubusercontent.com/145744711/273837510-0676d73c-353c-4565-922e-96a3925f9c72.png)
> 
> 如图，我根据https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 这个文档安装好paddle后运行程序报了ModuleNotFoundError: No module named 'paddle.fluid '的错误，该如何解决？

![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/e4697e90-1e10-46ae-a028-e2ef84617ff4)

**Comment by engineer1109** [comment]
paddle.fluid寄了 删除了，用paddle.base替代
如果感觉不适，请习惯就好。

**Comment by lijialin1999** [comment]
> paddle.fluid寄了 删除了，用paddle.base替代 如果感觉不适，请习惯就好。

那我直接进入对应文件把paddle.fluid改成paddle.base就行了吗？

**Comment by engineer1109** [comment]
> > paddle.fluid寄了 删除了，用paddle.base替代 如果感觉不适，请习惯就好。
> 
> 那我直接进入对应文件把paddle.fluid改成paddle.base就行了吗？

理论上，大多数情况直接替换可以解决。
但是如果功能函数被彻底删除了（某些冷门函数），只能自认倒霉，想办法修改。

**Comment by lijialin1999** [comment]
> > > paddle.fluid寄了 删除了，用paddle.base替代 如果感觉不适，请习惯就好。
> > 
> > 
> > 那我直接进入对应文件把paddle.fluid改成paddle.base就行了吗？
> 
> 理论上，大多数情况直接替换可以解决。 但是如果功能函数被彻底删除了（某些冷门函数），只能自认倒霉，想办法修改。

好的，感谢您的回复！

**Comment by Sophia-stargithub** [comment]
博主能提供一下NPU版paddle包嘛，arm结构，根据官方文档编译一直失败

**Comment by engineer1109** [comment]
@Sophia-stargithub    NPU已经不在Paddle主仓库支持，只需要cmake .. -DWITH_GPU=OFF -DWITH_CUSTOM_DEVICE -DWITH_ARM=ON即可。
NPU代码在Paddle的已经删除，需要插件导入
去看 https://github.com/PaddlePaddle/PaddleCustomDevice

**Comment by lijialin1999** [comment]
> @Sophia-stargithub NPU已经不在Paddle主仓库支持，只需要cmake .. -DWITH_GPU=OFF -DWITH_CUSTOM_DEVICE -DWITH_ARM=ON即可。 NPU代码在Paddle的已经删除，需要插件导入 去看 https://github.com/PaddlePaddle/PaddleCustomDevice

想问一下现在这个文档里的方式是支持所有昇腾NPU吗？还是仅仅支持昇腾910？

**Comment by lijialin1999** [comment]
> 博主能提供一下NPU版paddle包嘛，arm结构，根据官方文档编译一直失败

我的只有针对python的编译成功了，但是运行不成功

**Comment by qili93** [comment]
默认飞桨社区只提供源码编译，NPU 鲲鹏920 CPU的安装包请联系飞桨商业团队获取 https://www.paddlepaddle.org.cn/install/customerinfo

昇腾设备型号对应关系，请参考
<img width="1257" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1b6044ef-2c22-4ff5-9e3c-f3472506d4c1">

以上截图的入口位于：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
