### ISSUE TITLE
Text generation在generation的model路径不太友好

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#580]
训练完成了16个pass
然后在generating的时候，执行 gen.sh脚本，报错如下
<img width="1277" alt="2016-11-23 7 44 16" src="https://cloud.githubusercontent.com/assets/6861004/20560690/add12034-b1b5-11e6-8148-ee135701126b.png">
后发现文档上写loading model parameters from test_pass to (num_passes - 1)，here only loads data/wmt14_model/pass-00012
也就是说在generating的时候默认路径为 --save_dir='data/wmt14_model'
而用户在训练的时候默认路径为  --save_dir='translation/model' 

如果用户选择了自己训练的方式，在训练完成之后需要在gen.sh里面该目录或者把训练模型移动到gen.sh的模型目录，这样感觉不太友好？

**Comment by luotao1** [comment]
这个我觉得没必要改，用户应该知道怎么修改，修改起来也很方便

**Comment by luotao1** [comment]
这个我觉得没必要改，用户应该知道怎么修改，修改起来也很方便

**Comment by luotao1** [comment]
这个我觉得没必要改，用户应该知道怎么修改，修改起来也很方便

**Comment by luotao1** [comment]
这个我觉得没必要改，用户应该知道怎么修改，修改起来也很方便

**Comment by luotao1** [comment]
这个我觉得没必要改，用户应该知道怎么修改，修改起来也很方便
