### ISSUE TITLE
Is there any support for converting `paddle::pir` to `mlir`?

### ISSUE THREAD

**Issue by gglin001** [PaddlePaddle/Paddle#58006]
### 请提出你的问题 Please ask your question

hi, 我想尝试下将一个 paddle::pir::Program demo 转换成标准的 mlir graph, paddle 中有支持这种转换的基础设施吗?

**Comment by Aurelius84** [comment]
感谢对飞桨pir项目的关注，非常遗憾目前我们还没有提供相关工具将 `pir` 转换为 `mlir`。不过这是一个非常有意义的工作，我们会尽快评估并提上日程。
