### ISSUE TITLE
昇腾NPU版本在飞腾2000+环境下使用镜像编译失败

### ISSUE THREAD

**Issue by yinpeng-cn** [PaddlePaddle/Paddle#58002]
### 问题描述 Issue Description

能够详细说明一下 paddle2.5.1中环境和编译参数吗 根据指导https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 根本无法完成编译 C++目标。

引入simd时 出现链接错误，比如竟然有-lpthreads的链接要求，或者 对于C中引入c++的参数（ -Wnon-virtual-dtor
-Wdelete-non-virtual-dtor flags.cmake）
强制关闭 GPU、XPU选项并不起作用，xpu_kp.cmake仍然生效；
在手动关闭某些cmake参数后，无法生成对应的makefile文件。
怀疑：
1、docker pull registry.baidubce.com/device/paddle-npu:cann601-ubuntu18-aarch64-gcc82 环境不完整，无法支撑顺畅编译；
2、https://github.com/PaddlePaddle/Paddle 的develop分支 以及 v2.5.1 分支 在arm64+npu下不能使用镜像编译；
3、或编译参数不正确，目前使用的参数为
cmake .. -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=which python3 -DWITH_CUSTOM_DEVICE=ON
-DWITH_TESTING=OFF -DON_INFER=ON -DWITH_AVX=OFF -DWITH_DISTRIBUTE=OFF -DWITH_DLNNE=OFF
-DWITH_ARM=ON -DWITH_LITE=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_GPU=OFF -DWITH_XPU=OFF
-DCMAKE_CXX_FLAGS="-Wno-error -w" -DCMAKE_C_FLAGS="-w -pthread -z max-page-size=0x10000"

另：
CPU：ft2000+，NPU ：昇腾 310 ，CANN601。

遍寻所有资料，暂无法找到参考依据，请提供解决方法或确定编译通过的过程及参数，谢谢。

### 版本&环境信息 Version & Environment Information

以下为镜像内信息
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: 8.0.1  (based on LLVM 8.0.1)
CMake version: version 3.19.8
Libc version: glibc 2.27
Python version: 3.9.17

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
***************************************

以下为hostOS信息
****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: kylin V10
GCC version: (GCC) 7.3.0
Clang version: 8.0.1  (based on LLVM 8.0.1)
CMake version: version 3.16.5
Libc version: glibc 2.17
Python version: 3.7.9

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by lijialin1999** [comment]
你运行python示例的时候成功了吗？

**Comment by yinpeng-cn** [comment]
为什么要运行python示例 文档中并没有说这一步是必须的呀 请注意我的问题是 对于 这种情况 paddle的cmake参数 具体是如何设定的
对于现在的进展，使用paddle的develop版本在宿主机的环境下，使用以下参数能够完成编译，
cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON \
         -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"

但是，在执行PaddleCustomService的编译时，出现 In file included from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:19:0,
                 from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/abs_kernel.cc:15:
/home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_enforce.h:21:10: 致命错误：paddle/phi/core/enforce.h：没有那个文件或目录
 #include "paddle/phi/core/enforce.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~

补充，已经按照https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 补充了对应的env变量，
export ON_INFER=ON # 是否打开推理库编译，默认为 OFF
export PADDLE_INFERENCE_LIB_DIR=/path/to/Paddle/build/paddle_inference_install_dir
export CUSTOM_DEVICE_ROOT=/path/to/PaddleCustomDevice/backends/npu/build

**Comment by lijialin1999** [comment]
> 为什么要运行python示例 文档中并没有说这一步是必须的呀 请注意我的问题是 对于 这种情况 paddle的cmake参数 具体是如何设定的 对于现在的进展，使用paddle的develop版本在宿主机的环境下，使用以下参数能够完成编译， cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"
> 
> 但是，在执行PaddleCustomService的编译时，出现 In file included from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:19:0, from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/abs_kernel.cc:15: /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_enforce.h:21:10: 致命错误：paddle/phi/core/enforce.h：没有那个文件或目录 #include "paddle/phi/core/enforce.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> 
> 补充，已经按照https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 补充了对应的env变量， export ON_INFER=ON # 是否打开推理库编译，默认为 OFF export PADDLE_INFERENCE_LIB_DIR=/path/to/Paddle/build/paddle_inference_install_dir export CUSTOM_DEVICE_ROOT=/path/to/PaddleCustomDevice/backends/npu/build

因为我是安装完成了但是运行示例程序的时候不成功，所以想看看你有没有同样的情况，而且我也是昇腾310，我之前发的issues有人告诉我说这个文档的是适配昇腾910的，所以310用不了...

**Comment by yinpeng-cn** [comment]
> > 为什么要运行python示例 文档中并没有说这一步是必须的呀 请注意我的问题是 对于 这种情况 paddle的cmake参数 具体是如何设定的 对于现在的进展，使用paddle的develop版本在宿主机的环境下，使用以下参数能够完成编译， cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=ON -DCMAKE_CXX_FLAGS="-Wno-error -w"
> > 但是，在执行PaddleCustomService的编译时，出现 In file included from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_funcs.h:19:0, from /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/abs_kernel.cc:15: /home/ppy/src/PaddleCustomDevice/backends/npu/kernels/funcs/npu_enforce.h:21:10: 致命错误：paddle/phi/core/enforce.h：没有那个文件或目录 #include "paddle/phi/core/enforce.h" ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> > 补充，已经按照https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md 补充了对应的env变量， export ON_INFER=ON # 是否打开推理库编译，默认为 OFF export PADDLE_INFERENCE_LIB_DIR=/path/to/Paddle/build/paddle_inference_install_dir export CUSTOM_DEVICE_ROOT=/path/to/PaddleCustomDevice/backends/npu/build
> 
> 因为我是安装完成了但是运行示例程序的时候不成功，所以想看看你有没有同样的情况，而且我也是昇腾310，我之前发的issues有人告诉我说这个文档的是适配昇腾910的，所以310用不了...

感觉开发团队说不清楚paddle、paddle_lite、Serving、Fastdeploy的关联关系，编译和构建关系也说不清楚，很是迷茫。

**Comment by qili93** [comment]
您好，310芯片支持的设备都是Atlas设备，支持的CPU为鲲鹏920 CPU，飞桨开源社区暂未支持飞腾CPU和昇腾310的适配组合，如果您有这个组合的需求请联系飞桨商业团队寻求定制开发的支持。商业支持的联系入口：https://www.paddlepaddle.org.cn/install/customerinfo

昇腾设备型号对应关系，请参考
<img width="1257" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1b6044ef-2c22-4ff5-9e3c-f3472506d4c1">

以上截图的入口位于：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
