### ISSUE TITLE
v2 init have some code that can not run on mac

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#5801]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/__init__.py#L88
```python
 ht = os.popen("lscpu |grep \"per core\"|awk -F':' '{print $2}'|xargs")
```
Mac中不支持lscpu这个指令

**Comment by jacquesqiao** [comment]
mac里边现在无法运行book，这个还是需要支持一下

**Comment by tensor-tang** [comment]
这几句话的目的是获取机器状态，用于绑核和设置环境变量。

https://github.com/PaddlePaddle/Paddle/pull/5671

Code可以在docker里面直接使用。

如果需要支持mac的话， @luotao1  我只能在Mac环境下注释掉这几句了。

**Comment by jacquesqiao** [comment]
@wangkuiyi  do we need to support running book chapters directly in MacOS or we just support running in Docker container?

**Comment by jacquesqiao** [comment]
@wangkuiyi  do we need to support running book chapters directly in MacOS or we just support running in Docker container?

**Comment by luotao1** [comment]
@jacquesqiao mac在docker环境下可以运行book的。mac本地环境下，这行代码确实运行不了，有其他替代这行功能的代码么？

**Comment by typhoonzero** [comment]
我理解还是需要支持下mac，原因是文档中说明支持了在mac中pip install。

可以按照 @tensor-tang 的方法，mac下不走这个分支。

**Comment by tensor-tang** [comment]
如果有更加上层的命令获取，可以直接从python获取系统超线程状态和系统可用的process个数，是可以完全替代的。这里的code写的却是不够抽象。

**Comment by wangkuiyi** [comment]
这里不支持mac的原因是什么呢？如果只是某些命令和Linux下用法不兼容，是不是稍微判断一下就可以支持mac和linux了？如果是这样，就加一个判断吧。

**Comment by tensor-tang** [comment]
原因是我直接采用了
`lscpu |grep \"per core\"|awk -F':' '{print $2}'|xargs`
和'grep \"processor\" /proc/cpuinfo|sort -u|wc -l'这样的hard code。

当时没有找到比较上层、通用的做法。

不知道大家有没有好的建议。

**Comment by wangkuiyi** [comment]
https://github.com/PaddlePaddle/Paddle/blob/9891667b794711a72e940f1f57971d7193d60173/python/paddle/v2/__init__.py#L88-L95

这里为什么如果开启了hyperthreading几应该设置 `OMP_DYNAMIC` 呢？

**Comment by wangkuiyi** [comment]
If it is really necessary to know if hyper-threading is enabled, we can use the following commands with Mac:

```bash
sysctl -n hw.ncpu
sysctl -n hw.physicalcpu
sysctl -n hw.logicalcpu
8
```

where `sysctl` is a BSD-native program.

Given above information, we can defined a Python function like the following:

```python
import platform

def is_hyperthreading_enabled() :
  if platform.system() == "Darwin":
    return ...
  elif platform.system() == "Linux":
    return ...
  else ...
```

**Comment by wangkuiyi** [comment]
之前廖刚和其他几个人花了很多时间确保 PaddlePaddle 可以在 Mac 上编译和运行。希望我们不要因为不重要的原因，损失了这个功能。

**Comment by tensor-tang** [comment]
因为当开启超线程之后，有的机器上可用的线程数会比较多(特别是server上)，让OMP自己根据实际需要的并行程度自动调整，一般会带来比较好的性能。当然这个也不是绝对的，也是需要跟着workload走的，只不过通常情况下这样的配置比较好。

所以，还留了个接口，让用户在外面也可以改掉这个值，
https://github.com/PaddlePaddle/Paddle/blob/9891667b794711a72e940f1f57971d7193d60173/python/paddle/v2/__init__.py#L84-L86

**Comment by tensor-tang** [comment]
好的thx，稍后我来加上。
