### ISSUE TITLE
如何使用已经训练好保存的模型

### ISSUE THREAD

**Issue by ZXHe23** [PaddlePaddle/Paddle#58030]
如何直接使用保存好的模型

使用model.save_pretrained('/home/aistudio/checkpoint')
tokenizer.save_pretrained('/home/aistudio/checkpoint')
保存的模型，如何加载这个模型直接使用

**Comment by gongel** [comment]
你好，可以使用
```python
from_pretrained
```
接口，可以参考https://github.com/PaddlePaddle/PaddleNLP#%E5%A4%A7%E6%A8%A1%E5%9E%8B%E6%96%87%E6%9C%AC%E7%94%9F%E6%88%90
