### ISSUE TITLE
使用pip安装的paddlepaddle有没有noavx版本的，我的电脑不支持avx指令集

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#5803]
在docker我知道使用`docker.paddlepaddle.org/paddle:latest-noavx`的，但是我有时觉得docker用起来比较麻烦，想用pip安装，但是官方给出的是`pip install paddlepaddle`，但是我要的是noavx的，电脑太老了

**Comment by sweetsky0901** [comment]
建议你可以源码编译试试

**Comment by yeyupiaoling** [comment]
@sweetsky0901 好，谢谢你的回答

**Comment by Rainbowkfc** [comment]
你好，请问你源码编译安装成功了吗，我也有同样的问题，但发现源码安装时，每次安装磁盘的空间都不够，在编译过程中越来越大，超过6G空间了，目前无解。

**Comment by luotao1** [comment]
@Rainbowkfc 请问您的编译选项是什么呢

**Comment by yeyupiaoling** [comment]
@Rainbowkfc 
你可以看看这篇文章。编译过程是会变大的，我编译完成会有17G的。

**Comment by luotao1** [comment]
请参考最新官网的编译文档：http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html#build-step 
将WITH_TESTING选项设成OFF，不编译单测，能节省非常大的空间。
```
cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF ..
```

**Comment by Rainbowkfc** [comment]
好的，我试试，感谢。

**Comment by yes-github** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/install/Tables.html#whl-release
[win-cpu-mkl-noavx/paddlepaddle-2.4.2-cp38-cp38-win_amd64.whl](https://paddle-wheel.bj.bcebos.com/2.4.2/windows/windows-cpu-noavx-mkl-vs2017/paddlepaddle-2.4.2-cp38-cp38-win_amd64.whl)
