### ISSUE TITLE
在FT-2000+昆仑R200+麒麟v10下编译PaddlePaddle-develop

### ISSUE THREAD

**Issue by QAQTATQAQTAT** [PaddlePaddle/Paddle#58080]
### 问题描述 Issue Description
正克隆到 '/home/somnus/Paddle/build/third_party/lite/src/extern_lite/third-party/protobuf-mobile'...
正克隆到 '/home/somnus/Paddle/build/third_party/lite/src/extern_lite/third-party/gflags'...
子模组 'doc'（https://github.com/gflags/gflags.git）已对路径 'third-party/gflags/doc' 注册
正克隆到 '/home/somnus/Paddle/build/third_party/lite/src/extern_lite/third-party/gflags/doc'...
子模组 'third_party/benchmark'（https://github.com/google/benchmark.git）已对路径 'third-party/protobuf-host/third_party/benchmark' 注册
正克隆到 '/home/somnus/Paddle/build/third_party/lite/src/extern_lite/third-party/protobuf-host/third_party/benchmark'...
子模组 'third_party/benchmark'（https://github.com/google/benchmark.git）已对路径 'third-party/protobuf-mobile/third_party/benchmark' 注册
正克隆到 '/home/somnus/Paddle/build/third_party/lite/src/extern_lite/third-party/protobuf-mobile/third_party/benchmark'...
sed：无法读取 /home/somnus/Paddle/build/third_party/lite/src/extern_lite/cmake/os/armlinux.cmake：没有那个文件或目录
make[2]: *** [CMakeFiles/extern_lite.dir/build.make:114：third_party/lite/src/extern_lite-stamp/extern_lite-patch] 错误 2
make[1]: *** [CMakeFiles/Makefile2:4703：CMakeFiles/extern_lite.dir/all] 错误 2
make[1]: *** 正在等待未完成的任务....
make[1]: *** [CMakeFiles/Makefile2:5406：paddle/phi/CMakeFiles/phi.dir/all] 错误 2
make: *** [Makefile:136：all] 错误 2

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: kylin V10
GCC version: (GCC) 7.3.0
Clang version: 7.0.0 (kylin 7.0.0-6.1.ky10)
CMake version: version 3.27.7
Libc version: glibc 2.28
Python version: 3.7.14

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by yangy996** [comment]
没有把第三方包克隆下来
https://blog.csdn.net/YY007H/article/details/125386851

**Comment by qili93** [comment]
您好，这个应该是网络问题导致的第三方库没有克隆导致的，可以尝试在Paddle目录下运行 `git submodule update --init --recursive` 然后检查 `Paddle/third-party` 目录下的一个个子目录，保证里面都有代码。如果存在某个  `Paddle/third-party` 子目录下的目录里面内容是空的，可以删掉之后，在Paddle目录下重新运行 `git submodule update --init --recursive`命令；

另外根据你这里提示的错误信息，您的编译选项中应该是开了 WITH_LITE 的选项，这个是支持Paddle Inference使用Paddle Lite后端的，如果您没有这个需求，可以不需要开启这个编译选项。为了更好的定位您的问题，请提供以下信息

1. Paddle的代码commit ID，可以git log --oneline看下当前Paddle目录下最新的commit
2. 编译的CMAKE和make命令
3. 环境下lscpu的输出
4. 环境下uname -m && uname -r && cat /etc/*release 的输出
5. 环境下 cat /proc/xpu/version 的输出

您如果是使用镜像环境编译的，也请您提供你在使用的docker image，另外描述下您需要的飞桨功能，是训练还是推理？

我们根据以上信息分析下可能的错误原因。
