### ISSUE TITLE
安装报错，Error: Can not import paddle core while this file exists: D:\Program\anaconda3\envs\paddle\lib\site-packages\paddle\fluid\libpaddle.pyd

### ISSUE THREAD

**Issue by hxi667** [PaddlePaddle/Paddle#58096]
### 问题描述 Issue Description

在 python3.10环境下安装完paddlepaddle==2.5.1之后，执行 import paddle 验证安装是否成功时报错：
![image](https://github.com/PaddlePaddle/Paddle/assets/48883474/72f11562-6926-460c-8583-41063f6dd525)

### 版本&环境信息 Version & Environment Information

PaddlePaddle：2.51
GPU：虚拟v100s
python：3.10
系统环境：windows10
cuda：10.2
cudnn：v7.6.5

**Comment by risemeup1** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/62429225/8f6db950-803d-4221-a8eb-a038095c6e56)
我这里an zha按照你的操作完全没问题啊

**Comment by risemeup1** [comment]
建议你按照官方文档操作，我复现不了你的问题
