### ISSUE TITLE
Cross-compling Paddle for ARMv7

### ISSUE THREAD

**Issue by fhowen** [PaddlePaddle/Paddle#58123]
### 问题描述 Issue Description

现有目标平台是ARM  A15芯片（ARMv7），需要源码编译CPU版本的Paddle  [comit ID: 802613cca7](https://github.com/PaddlePaddle/Paddle/commit/802613cca7)
遇到的问题主要有：

1. 交叉编译Eigen库时报错，报错信息如下：

![fd727a3595b70d971d8889dd4319d78](https://github.com/PaddlePaddle/Paddle/assets/14502132/91e51861-4b80-4362-917e-5f4a228436b1)

![c183a944866fe2c87c8af2e6aa475ee](https://github.com/PaddlePaddle/Paddle/assets/14502132/dc0bbe6a-dff2-4b25-91ec-62729f66cc48)

相关错误在编译Eigen库时多次出现。

2. 数据截断问题
https://github.com/PaddlePaddle/Paddle/blob/1c5b00642c6f01142df4fbce1938598eaf9906ce/paddle/utils/flat_hash_map.h#L1144

在这个prime list中，后面的数据由于过大，在A15上报-Wnarrowing错误。对Paddle框架中需要处理的该类型错误有多少不确定。

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: arago 2019.05
GCC version: (Linaro GCC 8.2-2018.08~dev) 8.3.0
Clang version: N/A
CMake version: version 3.15.7
Libc version: glibc 2.9
Python version: 3.7.0

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by zhoutianzi666** [comment]
> ### 问题描述 Issue Description
> 现有目标平台是ARM A15芯片（ARMv7），需要源码编译CPU版本的Paddle [comit ID: 802613cca7](https://github.com/PaddlePaddle/Paddle/commit/802613cca7) 遇到的问题主要有：
> 
> 1. 交叉编译Eigen库时报错，报错信息如下：
> 
> ![fd727a3595b70d971d8889dd4319d78](https://user-images.githubusercontent.com/14502132/275496185-91e51861-4b80-4362-917e-5f4a228436b1.jpg)
> 
> ![c183a944866fe2c87c8af2e6aa475ee](https://user-images.githubusercontent.com/14502132/275498633-dc0bbe6a-dff2-4b25-91ec-62729f66cc48.jpg)
> 
> 相关错误在编译Eigen库时多次出现。
> 
> 2. 数据截断问题
>    https://github.com/PaddlePaddle/Paddle/blob/1c5b00642c6f01142df4fbce1938598eaf9906ce/paddle/utils/flat_hash_map.h#L1144
> 
> 在这个prime list中，后面的数据由于过大，在A15上报-Wnarrowing错误。对Paddle框架中需要处理的该类型错误有多少不确定。
> 
> ### 版本&环境信息 Version & Environment Information
> Paddle version: N/A Paddle With CUDA: N/A
> 
> OS: arago 2019.05 GCC version: (Linaro GCC 8.2-2018.08~dev) 8.3.0 Clang version: N/A CMake version: version 3.15.7 Libc version: glibc 2.9 Python version: 3.7.0
> 
> CUDA version: N/A cuDNN version: N/A Nvidia driver version: N/A Nvidia driver List: N/A

paddle是没办法编译成32位的哦！
