### ISSUE TITLE
验证相关

### ISSUE THREAD

**Issue by showaker** [PaddlePaddle/Paddle#58131]
### 请提出你的问题 Please ask your question

在国产化机器上验证时报错缺少libdjl_paddle.so文件 还有一些其他的库 请问在哪里下载

**Comment by ming1753** [comment]
您好，这个看起来不是paddle推理的库，似乎是用户基于paddle库编译出的so文件

**Comment by showaker** [comment]
好的 那应该是和djl相关的文件生成的 谢谢您
