### ISSUE TITLE
D:\Anaconda3\envs\ppocr\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:1438: UserWarning: Failed to check compiler version for cl: [WinError 2] 系统找不到指定的文件。

### ISSUE THREAD

**Issue by zgsxwsdxg** [PaddlePaddle/Paddle#58199]
### 请提出你的问题 Please ask your question

我是在win10环境下训练ppocr时，paddle 报警告：D:\Anaconda3\envs\ppocr\lib\site-packages\paddle\utils\cpp_extension\extension_utils.py:1438: UserWarning: Failed to check compiler version for cl: [WinError 2] 系统找不到指定的文件。这个是什么问题？如何解决？期待同仁解决下，谢谢！！！！

**Comment by cyber-pioneer** [comment]
麻烦发一下完整的报错截图

**Comment by xuxinyi389** [comment]
https://github.com/PaddlePaddle/Paddle/issues/new?assignees=&labels=type%2Fbuild%2Cstatus%2Fnew-issue&projects=&template=3_build-installation-issue.yml 可以参考这个链接重新描述下你的问题。此外报错信息为cl链接器有问题，可以检查下你的vs。

**Comment by zgsxwsdxg** [comment]
> 麻烦发一下完整的报错截图

没有报错，是UserWarning，但是通过警告，代码定位可以看出应该是找不到win10  c/c++编译执行文件

**Comment by zgsxwsdxg** [comment]
> https://github.com/PaddlePaddle/Paddle/issues/new?assignees=&labels=type%2Fbuild%2Cstatus%2Fnew-issue&projects=&template=3_build-installation-issue.yml 可以参考这个链接重新描述下你的问题。此外报错信息为cl链接器有问题，可以检查下你的vs。

我刚刚解决了，问题是paddle找不到cl.exe, 所以把cl.exe设置环境变量解决了，谢谢！！！
