### ISSUE TITLE
paddlepaddle>=2.5.0 paddle.to_tensor() 为什么不支持输入np.int16了？

### ISSUE THREAD

**Issue by Alc-z** [PaddlePaddle/Paddle#58208]
### 请提出你的问题 Please ask your question

paddlepaddle >=2.5.0
当输入numpy ndarray dtype为int16，会报`When the type of 'input' in assign is numpy.ndarray, the data type of 'input' must be bool, float32, int32 or int64, but received int16`

这导致paddlespeech asr fbank [link](https://github.com/PaddlePaddle/PaddleSpeech/blob/15ca007ea48147963fdafd18eb0551801c9215e3/paddlespeech/audio/transform/spectrogram.py#L372C1-L372C1)异常。

**Comment by cyber-pioneer** [comment]
<img width="528" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/116002591/293e5f3b-655e-487a-82c4-9c21cc5aa77d">

问题未复现，麻烦提供类似的case？

**Comment by Alc-z** [comment]
env：
$ pip list|grep paddle
paddle-bfloat               0.1.7
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.6.1
paddlepaddle                2.5.1
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                1.4.1
paddlespeech-ctcdecoders    0.2.1
paddlespeech-feat           0.1.0

这是在paddlespeech中运行的结果：
 ![2970718181](https://github.com/PaddlePaddle/Paddle/assets/25759539/184432ac-c9c3-4a06-9381-e1349606b746)

但是我尝试在python console中复现，似乎没有问题：
![499126106](https://github.com/PaddlePaddle/Paddle/assets/25759539/3cf38d7e-5a9b-4762-857a-b09309579a46)
存储上述bug中的ndarray，在console中加载

当我把paddlepaddle降到2.4.x，paddlespeech则没有问题。
还需要我提供什么信息吗？

**Comment by cyber-pioneer** [comment]
问题已复现
```
import numpy as np
import paddle

data = np.array([1,2],dtype="int16")
paddle.enable_static()
x=paddle.to_tensor(data)
print(x)
```

**Comment by cyber-pioneer** [comment]
静态图出现这样的问题，运行动态图模式可以暂时绕开这个问题

**Comment by Alc-z** [comment]
好的

**Comment by sranqiu** [comment]
> 问题已复现
> 
> ```
> import numpy as np
> import paddle
> 
> data = np.array([1,2],dtype="int16")
> paddle.enable_static()
> x=paddle.to_tensor(data)
> print(x)
> ```

uint8 的 ndarray也有这个问题，当我用 paddle.to_tensor 从 opencv 的 numpy 中获取数据的时候出现了同样的情况。
