### ISSUE TITLE
如何构建自己的dictionary以及技巧

### ISSUE THREAD

**Issue by xiahan** [PaddlePaddle/Paddle#5820]
我跑了关于paddle/model下text classification，看例子是可以提供自己的词典也可以paddle根据训练数据自动构建词典（根据词频）。对于词典我有几个疑问。
1）根据词频构建词典，词频的高低是否本身会影响到分类的结果？例如我有些英文单词是the ，虽然词频很高，但是其实没啥分类的实际意义，反倒是一些词频没有the这么高的单词反而更具有意义。
2）例子中如果不使用自己的数据，你们会下载已经有的数据集，包括词典，测试数据以及训练数据。我翻看了下该数据集的词典，词典为一行一个词，并没有词频。如果我自己构建自己的词典，而非你们自动构建的，我是否需要列出词频信息呢？
3）是否需要针对不同的应用场景做不同的词库？虽然我的训练数据都是可以用英文单词来表示，对于我的不同应用场景，我是应该有针对该场景的专门的词典呢还是所有的应用场景其实可以用相同的词典？例如我是针对对于电影的正面反面的评价这个应用场景，我的词典里会包含film，good之类的词。如果我是做体育类某个评论的应用场景，我是否应该把film这个词添加到词典呢？film这个词其实对我这个应用场景没事么用。或许都可以，只是会影响到分类的结果的正确率？

**Comment by zhouxiao-coder** [comment]
分享一些看法供参考。

> 1）根据词频构建词典，词频的高低是否本身会影响到分类的结果？

这个问题表达的不太清楚。在当前的建模中，一种常见的构建词典的做法是根据词频降序排列，截取头部的词汇作为词典，非常长尾的部分视为一个特殊的word（“UNK”）。高频词在语料中信息丰富，其对应参数（例如embedding）一般能得到更好的建模；被抛弃的词一般是非常长尾的词，在语料中出现次数少，即使放到词典中也很少得到有意义的参数，所以很多时候被“战略性的放弃”。

如“the”这样的常见词汇的处理：在一些比较早的传统NLP任务中会总结一部分极高频的无实际意义词汇将其作为停用词，在进行后续任务（分类、检索建索引）的时候去掉。但在神经网络模型中很少会这样做。我认为其中一个很重要的原因是由于文本可以被建模为更丰富的序列信息，而不是简单的词袋模型（BOW），此时丢掉所谓的停用词会破坏序列信息。

> 2）... 如果我自己构建自己的词典，而非你们自动构建的，我是否需要列出词频信息呢？

这个看具体实现了。我自己没有跑你提到的demo，你可以查看下数据处理的python代码。对于神经网络模型，或者paddle的核心代码而言，词频信息一般没有用处。

> 3）是否需要针对不同的应用场景做不同的词库？

一个词典是否适合你的任务很大程度上取决于它是否能很好的表示你的训练数据的构成。一个简单的检测方法是统计一下你训练数据中 "UNK" 的比例有多少。“UNK”比率太高的话，比如超过了2%，那么可能就需要重新生成一份词典，或者切换到更细粒度（subword级别）的词典了。

**Comment by Canpio** [comment]
1. 词典的作用仅仅是将单词映射为数字，至于这个映射出来的数字是多少并不重要，我们可以将apple映射为1，the映射为2；也可以将the映射为1，apple映射为2，模型训练并不会用到编号之间的大小关系，因此这本身不会对训练效果有任何影响。根据词频来分配编号是一种常用的做法，但并不表示必须这么做。
2. 如上一问所答，词频信息仅仅用来构建词典。构建完词典后，词频就没用了。当然，如果你用其他方式构建字典，那完全可以不统计词频。
3. 词库最重要的是保证和训练预测语料之间较高的重合度。因此一个包罗万象的词库和专门的词库应该都可以，但包罗万象的词库可能会导致训练较慢。

如果还有其他问题，欢迎继续提问。

**Comment by chengduoZH** [comment]
该issue长期没有回复，暂时先关闭了，如果许继续讨论再打开
