### ISSUE TITLE
CustomDevice 私有格式支持场景

### ISSUE THREAD

**Issue by JiruWang** [PaddlePaddle/Paddle#58218]
### 任务目标
且用户可通过python api，指定相关op参数为自定义存储格式。
在所有用户使用场景中，私有格式都可支持。
### 需求场景
目前私有格式使用环境变量,控制NPU identity op, 为conv，bn等op添加私有格式转换。
此方法用户反馈不够灵活，且支持场景不完善（比如layer.to(cpu)，没有转回nchw格式）
请问后续是否有开发计划，使用户可以通过python api灵活的控制参数私有格式？

**Comment by ronny1996** [comment]
你好，我们后续会开发自定义的存储和计算格式，目前只有NPU支持

**Comment by JiruWang** [comment]
> 你好，我们后续会开发自定义的存储和计算格式，目前只有NPU支持

请问是通过CustomDevice支持的吗

**Comment by ronny1996** [comment]
是的，计划是CustomDevice插件式的接入

**Comment by JiruWang** [comment]
> 是的，计划是CustomDevice插件式的接入

请问本季度会支持吗

**Comment by ronny1996** [comment]
你好，我们目前在规划中，预计今年Q4或者明年Q1支持

**Comment by yuanlehome** [comment]
@JiruWang 你好，还有问题嘛？如果没有的话，这个issue稍后给关闭了哈

**Comment by JiruWang** [comment]
> @JiruWang 你好，还有问题嘛？如果没有的话，这个issue稍后给关闭了哈

好的，谢谢
