### ISSUE TITLE
Tensor.cuda() API 是用同步拷贝，导致模型性能下降

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#58227]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/PaddleNLP/blob/develop/paddlenlp/trainer/trainer.py#L1709-L1711
```python
        elif isinstance(data, paddle.Tensor):
            # kwargs = dict(device=self.args.current_device)
            # update data type for pure fp16
            if data.place.is_cuda_pinned_place():
                return data.cuda()
            return data
```
PaddleNLP 中使用了 tensor.cuda() 将tensor从pin memory 拷贝到 gpu。
经过NV的同学profile发现：

> 观察到的情况是.cuda底层调用的是cudaMemcpy ，而不是cudaMemcpyAsync

最终造成模型 end to end 整体性能损失1%

请问 tensor.cuda() 可以换用 cudaMemcpyAsync 实现否？

**Comment by zhwesky2010** [comment]
https://github.com/PaddlePaddle/Paddle/pull/58228 修复PR
