### ISSUE TITLE
[api] 想知道`paddle.remainder` / `paddle.mod`  / `paddle.floor_mod` 三者的区别

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#58225]
### 请提出你的问题 Please ask your question

从[源码](https://github.com/PaddlePaddle/Paddle/blob/4dbd3f7d8a3a54066939a2e1acc46fadadf65c11/python/paddle/tensor/math.py#L1023)中来看似乎就是改了个名字，底层都是调用`remainder`的逻辑

**Comment by yuanlehome** [comment]
是的，从源码上来看，它们除了名字，是没有区别的
