### ISSUE TITLE
【Bug】MemcpyOp

### ISSUE THREAD

**Issue by yangguohao** [PaddlePaddle/Paddle#58224]
### bug描述 Describe the Bug

```
import paddle
@paddle.jit.to_static
def tensor_copy_to_cuda(x):
    x = paddle.to_tensor(x)
    y = x.cuda()
    z = y * 2
    return z
x = [1, 2, 3]
paddle.set_device('cpu')
z = tensor_copy_to_cuda(x)
print(z.place)
```
代码期望得到的 place 应该是 GPU，但是实际运行过程中会报错
```
[Hint: Expected ctx_place.GetType() == AllocationType::GPU == true, but received ctx_place.GetType() == AllocationType::GPU:0 != true:1.] (at /home/aistudio/Paddle/paddle/phi/core/tensor_utils.cc:125)
      [operator < scale > error]  [operator < run_program > error]
```

**Comment by yuanlehome** [comment]
您好，我们已经复现了这个问题，稍后内部会看一下～

**Comment by 2742195759** [comment]
这里 paddle.set_device('cpu') 之后在静态图下所有的Op都会使用CPU的Kernel来计算，而 x 被拷贝到了 gpu 上，这个用法在静态图下不合理。可以将这个 paddle.set_device('cpu') 删了就好了。

**Comment by yangguohao** [comment]
> 这里 paddle.set_device('cpu') 之后在静态图下所有的Op都会使用CPU的Kernel来计算，而 x 被拷贝到了 gpu 上，这个用法在静态图下不合理。可以将这个 paddle.set_device('cpu') 删了就好了。

这个主要是动转静测试 test/dygraph_to_static/test_tensor_memcpy_on_cpu.py 里 test_tensor_cuda_on_default_cpu 这个测试下，测试中没有 `z = y * 2` 代码是能成功运行，得到的 y 的 place 也是正确，但是多加一行后就报错了。如果删除 paddle.set_device('cpu')的话就失去测试的意义了吧

**Comment by 2742195759** [comment]
如果没有后续Op确实是对的，但是有后续Op就是不支持的。单侧中也没有后续的z = y * 2。这个问题本质是老静态图和动态图的Kernel选择逻辑的差异。

**Comment by yangguohao** [comment]
> 如果没有后续Op确实是对的，但是有后续Op就是不支持的。单侧中也没有后续的z = y * 2。这个问题本质是老静态图和动态图的Kernel选择逻辑的差异。

好的，感谢回复，那我就关掉这个 issues 了
