### ISSUE TITLE
[Docathon] 英文文档格式修复（Fix 'System Message'）

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/Paddle#58237]
## 背景

由于检查英文文档的CI在一段时间内失效，导致部分不合规的 PR 合入，从而产生了一些文档显示的问题。其中，比较突出的问题是「**由格式问题导致文档内容解析错误**」，表现为文档内容中出现 「**System Message: Warning / Error**」。

### Example：
以 [batch_norm](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/batch_norm_en.html) 为例，在参数描述中出现 [**System Message：Warning**]， 如下图所示：
![image](https://github.com/PaddlePaddle/Paddle/assets/70642955/cfe0f863-73a3-424b-a3ff-52a67eb88d2a)

在源码中，对应描述为：

        param_attr(ParamAttr|None): The parameter attribute for Parameter `scale`
             of batch_norm. If it is set to None or one attribute of ParamAttr, batch_norm
         will create ParamAttr as param_attr, the name of scale can be set in ParamAttr.
         If the Initializer of the param_attr is not set, the parameter is initialized
         with Xavier. Default: None.
实际上，由于 RST 语法的要求，同一段落缩进必须相同，因此修改为

        param_attr(ParamAttr|None): The parameter attribute for Parameter `scale`
             of batch_norm. If it is set to None or one attribute of ParamAttr, batch_norm
             will create ParamAttr as param_attr, the name of scale can be set in ParamAttr.
             If the Initializer of the param_attr is not set, the parameter is initialized
             with Xavier. Default: None.

> [!IMPORTANT]  
> 1. 一般出现 **System Message:Warning/Error** 的问题，往往是由于 `同一段落缩进不一致`、`不同段落间没用空行相隔`、`code_block下没加空行` 等，英文文档格式务必参考 [英文模板](https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/api_docs_guidelines_cn.html#yingwenmuban)。
> 2. 同时，想了解更多 RST 语法，可参考 [reStructuredText Primer](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html)

## 任务描述
我们提供以下存在 **System Message:Warning/Error** 问题的文档，请在该 issue 回复序号进行认领，并在相应的源码中进行修改

| 序号  |              英文文档链接                | 认领人/状态/PR | 
| :---: | :-----------------------------: | :----: | 
| 1 | [static/nn/batch_norm_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/batch_norm_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58503](https://github.com/PaddlePaddle/Paddle/pull/58503)<br> | 
| 2 | [distributed/fleet/DistributedStrategy_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/distributed/fleet/DistributedStrategy_en.html) | @ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#59295](https://github.com/PaddlePaddle/Paddle/pull/59295)<br> | 
| 3 | [Model_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Model_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| 4 | [Tensor/to_dense_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Tensor/to_dense_en.html) | @Tomoko-hjf <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58626](https://github.com/PaddlePaddle/Paddle/pull/58626)<br> | 
| 5 | [Tensor/to_sparse_coo_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Tensor/to_sparse_coo_en.html) | @Tomoko-hjf <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58626](https://github.com/PaddlePaddle/Paddle/pull/58626)<br> | 
| 6 | [Tensor/values_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Tensor/values_en.html) | @Tomoko-hjf <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58626](https://github.com/PaddlePaddle/Paddle/pull/58626)<br> | 
| 7 | [device/Event_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/Event_en.html) | @Tomoko-hjf <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#58626](https://github.com/PaddlePaddle/Paddle/pull/58626)<br>@Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58508](https://github.com/PaddlePaddle/Paddle/pull/58508)<br> | 
| 8 | [distributed/fleet/Fleet_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/distributed/fleet/Fleet_en.html) | @Tomoko-hjf <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58626](https://github.com/PaddlePaddle/Paddle/pull/58626)<br> | 
| 9 | [get_rng_state_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/get_rng_state_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| ~~10~~ | ~~[distributed/fleet/MultiSlotStringDataGenerator_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/distributed/fleet/MultiSlotStringDataGenerator_en.html)~~ | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| 11 | [device/current_stream_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/current_stream_en.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58508](https://github.com/PaddlePaddle/Paddle/pull/58508)<br> @BernieHuang2008 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| 12 | [Tensor_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Tensor_en.html) | @liyongchao911 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#59361](https://github.com/PaddlePaddle/Paddle/pull/59361)<br>@ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#59445](https://github.com/PaddlePaddle/Paddle/pull/59445)<br> | 
| 13 | [static/Variable_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/Variable_en.html) | @liyongchao911 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#58864](https://github.com/PaddlePaddle/Paddle/pull/58864)<br>@ooooo-create <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#59725](https://github.com/PaddlePaddle/Paddle/pull/59725)<br> | 
| 14 | [nn/TripletMarginWithDistanceLoss_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/TripletMarginWithDistanceLoss_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> @liyongchao911 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 15 | [amp/debugging/enable_operator_stats_collection_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/amp/debugging/enable_operator_stats_collection_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| 16 | [nn/utils/clip_grad_value__en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/nn/utils/clip_grad_value__en.html) | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58741](https://github.com/PaddlePaddle/Paddle/pull/58741)<br> | 
| 17 | [incubate/optimizer/LBFGS_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/optimizer/LBFGS_en.html) | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58742](https://github.com/PaddlePaddle/Paddle/pull/58742)<br> | 
| 18 | [linalg/eigh_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/linalg/eigh_en.html) | @SigureMo       #58206 ✅ | 
| 19 | [incubate/distributed/utils/io/dist_save/save_for_auto_inference_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_for_auto_inference_en.html) | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58743](https://github.com/PaddlePaddle/Paddle/pull/58743)<br> | 
| 20 | [incubate/distributed/utils/io/dist_save/save_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/incubate/distributed/utils/io/dist_save/save_en.html) | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58744](https://github.com/PaddlePaddle/Paddle/pull/58744)<br> | 
| 21 | [jit/to_static_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/jit/to_static_en.html) | @SigureMo        #58257✅ | 
| 22 | [distributed/fleet/MultiSlotDataGenerator_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/distributed/fleet/MultiSlotDataGenerator_en.html) | @wenxiaohahaha <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58784](https://github.com/PaddlePaddle/Paddle/pull/58784)<br> | 
| 23 | [hub/help_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/hub/help_en.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58733](https://github.com/PaddlePaddle/Paddle/pull/58733)<br> | 
| ~~24~~ | ~~[Tensor/fill_diagonal__en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/Tensor/fill_diagonal__en.html)~~ | @Sekiro-x <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 25 | [device/synchronize_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/synchronize_en.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58508](https://github.com/PaddlePaddle/Paddle/pull/58508)<br> @BernieHuang2008 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#58664](https://github.com/PaddlePaddle/Paddle/pull/58664)<br> | 
| 26 | [static/nn/instance_norm_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/static/nn/instance_norm_en.html) | @BernieHuang2008 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58503](https://github.com/PaddlePaddle/Paddle/pull/58503)<br> | 
| 27 | [metric/Metric_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/metric/Metric_en.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58733](https://github.com/PaddlePaddle/Paddle/pull/58733)<br> | 
| 28 | [device/Stream_en](https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/device/Stream_en.html) | @Sekiro-x <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#58508](https://github.com/PaddlePaddle/Paddle/pull/58508)<br> | 

> [!NOTE]
> **1. Issue 回复格式**：
>为了自动填写报名信息，需要在issue下回复报名信息，如果报名格式不正确，则会在comment区提示报名不正确，格式如下：
> ```
> 【报名】: 2、3、6-10
> ```
> > 其中【报名】:  后直接是报名的赛题序号，多个赛题之间需要用中文顿号`、`分隔，多个连续赛题可以用`横线`表示

> [!NOTE] 
> **2. PR 标题格式**：
> ```
> [Docathon][Fix System Message No.2、3、6-10]
> ```
> PR的标题中以 ` [Docathon][Fix System Message No.xxxx]` 开头即可，程序会自动提取赛题编号并更新榜单。
> 一个PR也可以提交多个赛题，多个赛题间以`顿号`或`横线`分隔，比如 No.24、26-28、30 赛题。

## 看板信息 
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
| Docathon | 28 | 24 / 24 | 85.71% | 24 | 85.71% |
#####

## 统计信息 
> 排名不分先后 @BernieHuang2008 (6) @ooooo-create (3) @Tomoko-hjf (4) @Sekiro-x (6) @Liyulingyue (4) @wenxiaohahaha (1) 
#####

**Comment by ooooo-create** [comment]
【报名】: 2

**Comment by BernieHuang2008** [comment]
【报名】: 1、26

**Comment by Sekiro-x** [comment]
【报名】: 7、11、25、28

**Comment by Fancy-hjyp** [comment]
【报名】：4-8

**Comment by wenxiaohahaha** [comment]
【报名】: 2、3、6-10

**Comment by wenxiaohahaha** [comment]
【报名】: 2

**Comment by BernieHuang2008** [comment]
【报名】: 3、9-11、14-15、25

**Comment by a-non-y-mous-really** [comment]
【报名】: 22

**Comment by liyongchao911** [comment]
【报名】: 12-14

**Comment by Sekiro-x** [comment]
【报名】: 23、24、27

**Comment by rhmaaa** [comment]
【报名】：8

**Comment by luotao1** [comment]
[[Docathon] 英文文档格式修复（Fix 'System Message'）](https://github.com/PaddlePaddle/Paddle/issues/58237#top) 已全部完成，感谢参与的小伙伴们！

> 排名不分先后 @BernieHuang2008 (6) @ooooo-create (3) @Tomoko-hjf (4) @Sekiro-x (6) @Liyulingyue (4) @wenxiaohahaha (1)
