### ISSUE TITLE
Pip install issues, missing libssl.so and coredump, Ubuntu 22.04 related SANGFOR HYPERVISOR/MISSING CPU INSTRUCTION

### ISSUE THREAD

**Issue by lz-work** [PaddlePaddle/Paddle#58247]
## issue
THIS ISSUE IS PRESENT ON **BOTH** MY LOCAL VM Ubuntu 22.04 LTS and REMOTE Ubuntu server 22.04 LTS, both are freshly stalled system.

Followed the official one-liner CPU only installation guide `python -m pip install paddlepaddle==2.5.1 -i https://pypi.tuna.tsinghua.edu.cn/simple`

and tried to import the paddle module in python interpreter via `import paddle`, got issue with ** ImportError libssl.so.1.1**

and since Ubuntu 22.04 does not comes with libssl1.1 in its official apt source, installed **libssl1.1_1.1.1f-1ubuntu2.19_amd64.deb**
and **libssl1.1_1.1.1f-1ubuntu2_amd64.deb** on separate try anyways. 

then tried to `import paddle` got **Illegal instruction (core dumped)**

Tried to run my pytest anyways got bit more detailed error indicating error comes from numpy.

### 版本&环境信息 Version & Environment Information

OS: Ubuntu 22.04.3 LTS (build-essential installed)
Python: Python 3.10.12
CPU: Intel Xeon Gold 5320

**Comment by lz-work** [comment]
It seemed https://github.com/PaddlePaddle/Paddle/pull/56452 have already identified this issue and the fix have been pulled albeit not merged. Still the issue persists. 

I guess I would request a link to your nightly X86_64 generic linux build, if that is possible, thanks in advance.

**Comment by lz-work** [comment]
Successfully tried installing on my local machine using the nightly build of paddle, would recommend using this method, to circumvent this issue

**Comment by yuanlehome** [comment]
Hello, we have fixed this issue in the development version, so you will not encounter the same error when installing night build of paddle. The version 2.5.2 of Paddle is about to be released and has also been fixed. See https://github.com/PaddlePaddle/Paddle/pull/57147.

**Comment by lz-work** [comment]
@yuanlehome Erm, NO, despite my local machine got the fix the remote machine still got core dump error when I simply tried to `import paddle`
![image](https://github.com/PaddlePaddle/Paddle/assets/145107434/de4e71b1-4aca-4918-a7f8-824dbc9ecfcc)

**Comment by yuanlehome** [comment]
Can you try using the official docker？

**Comment by lz-work** [comment]
Ok, I think I've figure out the issue, dose the python numpy module require the cpu to have AVX instruction support?

I got this idea because the error prompted illegal instruction, and The remote system I am working on is using virtual CPU, emulating a very old model, which is missing AVX and many other instruction support, so maybe this is the issue.

![image](https://github.com/PaddlePaddle/Paddle/assets/145107434/195f793e-c62a-4905-ad4d-ad200755e1ce)

**Comment by yuanlehome** [comment]
No, the Python NumPy module itself does not require the CPU to have AVX instruction support. But, "missing many other instruction support" maybe a problem.

**Comment by lz-work** [comment]
Great, it's been confirmed that this is indeed caused by the default **CPU EMULATION** parameters/configs by the Sangfor/深信服 hypervisor system. In which system the CPU is emulated as a Core 2 T7700 CPU and frankly is just too old, and a lot of instruction is missing which caused the core dump.

SOLUTION: SIMPLY USE THE ENABLE HOST CPU OPTION IN THE HYPERVISOR SYSTEM

Thanks @yuanlehome for helping my troubleshooting process.

**Comment by lz-work** [comment]
added some keywords in the title, hopefully could help people with similar situation.
