### ISSUE TITLE
通过源码编译paddlepaddle的方式在import的时候name 'libpaddle' is not defined的错误

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#58258]
### 问题描述 Issue Description

![c9417c763b2779a5932d1b26b80009d8_274638430-b1556927-2988-43b2-81dd-f8bc5a777fd9](https://github.com/PaddlePaddle/Paddle/assets/145744711/676487aa-076d-4177-bccc-5f18a860159e)
通过https://www.paddlepaddle.org.cn/lite/v2.10/demo_guides/huawei_ascend_npu.html 这个文档创建了docker，然后再通过https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 这个文档编译了paddlepaddle，编译源码使用的cmake .. -DPY_VERSION=3.7 -DPYTHON_EXECUTABLE=which python3 -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF 最后在import paddle的时候出现了上图所示的错误

在这里卡了半个月了，真的很急！！！

### 版本&环境信息 Version & Environment Information

![cbe8b69e22be43021196a14dd00c46c5_274639977-a1175252-b1b1-4cca-aa08-f14e17a09805](https://github.com/PaddlePaddle/Paddle/assets/145744711/6cf3c62d-c982-4439-860c-a42a4b1a5150)

**Comment by USTCKAY** [comment]
参考这个issue https://github.com/PaddlePaddle/Paddle/issues/55309 的cmake命令试试？

**Comment by lijialin1999** [comment]
> 参考这个issue #55309 的cmake命令试试？

试过了不行

**Comment by USTCKAY** [comment]
用这个docker镜像 `registry.baidubce.com/device/paddle-cpu:ubuntu18-aarch64-gcc82` + 这个cmake指令试试呢？
cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
        -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` \
        -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_CUSTOM_DEVICE=ON \
        -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=OFF -DWITH_XBYAK=OFF \
        -DWITH_ARM=ON -DCMAKE_BUILD_TYPE=Release

**Comment by lijialin1999** [comment]
> 用这个docker镜像 `registry.baidubce.com/device/paddle-cpu:ubuntu18-aarch64-gcc82` + 这个cmake指令试试呢？ cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_CUSTOM_DEVICE=ON -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=OFF -DWITH_XBYAK=OFF -DWITH_ARM=ON -DCMAKE_BUILD_TYPE=Release

这个镜像必须得换掉吗？

**Comment by USTCKAY** [comment]
是的

**Comment by lijialin1999** [comment]
> 是的
![image](https://github.com/PaddlePaddle/Paddle/assets/145744711/03d95576-8cf0-49ba-b880-af3f7cff3ab5)
 cmake报了这个错误，但是我的cmake版本是3.16.8，应该是满足要求的

**Comment by USTCKAY** [comment]
这样吧，你给我个邮箱，我给你发一下我这边编的aarch64包你直接安装使用看行不行

**Comment by lijialin1999** [comment]
> 这样吧，你给我个邮箱，我给你发一下我这边编的aarch64包你直接安装使用看行不行

我在宿主机安装成功了，docker里始终不行

**Comment by USTCKAY** [comment]
> > 这样吧，你给我个邮箱，我给你发一下我这边编的aarch64包你直接安装使用看行不行
> 
> 我在宿主机安装成功了，docker里始终不行

那还挺奇怪的，我这边就是在这个docker里编译成功的。不过问题解决了就好，如果没有别的问题了可以关闭一下issue。

**Comment by lijialin1999** [comment]
> > > 这样吧，你给我个邮箱，我给你发一下我这边编的aarch64包你直接安装使用看行不行
> > 
> > 
> > 我在宿主机安装成功了，docker里始终不行
> 
> 那还挺奇怪的，我这边就是在这个docker里编译成功的。不过问题解决了就好，如果没有别的问题了可以关闭一下issue。

好的
