### ISSUE TITLE
Build error in gloo::getInterfaceSpeedGLinkSettings

### ISSUE THREAD

**Issue by meerfrau** [PaddlePaddle/Paddle#58286]
### 问题描述 Issue Description

I can't build Paddle due to gloo:
```
In file included from /Paddle/third_party/gloo/gloo/common/linux.cc:15:
/usr/include/linux/ethtool.h: In function 'int gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)':
/usr/include/linux/ethtool.h:2199:17: error: flexible array member 'ethtool_link_settings::link_mode_masks' not at end of 'struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>'
 2199 |         __u32   link_mode_masks[];
      |                 ^~~~~~~~~~~~~~~
/Paddle/third_party/gloo/gloo/common/linux.cc:192:11: note: next member '__u32 gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed struct>::link_mode_data [381]' declared here
  192 |     __u32 link_mode_data[link_mode_data_nwords];
      |           ^~~~~~~~~~~~~~
/Paddle/third_party/gloo/gloo/common/linux.cc:190:10: note: in the definition of 'struct gloo::getInterfaceSpeedGLinkSettings(int, ifreq*)::<unnamed>'
  190 |   struct {
      |          ^

```
Re-reported because https://github.com/PaddlePaddle/Paddle/issues/55730 only has a screenshot ;)

### 版本&环境信息 Version & Environment Information

Paddle version: N/A
Paddle With CUDA: N/A

OS: arch rolling
GCC version: (GCC) 12.3
Clang version: 15.0.7
CMake version: version 3.27.7
Libc version: glibc 2.38
Python version: 3.10.10

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A

→AMD Radeon GPU

**Comment by lugimzzz** [comment]
看这个issue是否能够解决这个问题 https://github.com/PaddlePaddle/Paddle/issues/55712

**Comment by meerfrau** [comment]
@lugimzzz I'm on a Linux desktop, can impossibly use the Raspberry wheel.

**Comment by risemeup1** [comment]
AMD的显卡我们不支持，编cpu吧
