### ISSUE TITLE
CPU 跑paddle inference predictor错误，使用同一个predictor第二次执行就会返回[Nan,Nan....]

### ISSUE THREAD

**Issue by abasi20** [PaddlePaddle/Paddle#58292]
paddlenlp执行多源数据召回操作。同样问题执行两次，预测数据时发生。（docker 镜像）
第一次结果
![image](https://github.com/PaddlePaddle/Paddle/assets/26450285/7028e37c-1c60-4503-8670-a9d76faf6da0)
第二次结果
![image](https://github.com/PaddlePaddle/Paddle/assets/26450285/d914b7e3-d7f2-4585-8ca4-fcacbd78c1e4)

**Comment by lugimzzz** [comment]
方便提供一下PaddleNLP和Paddle版本吗

**Comment by abasi20** [comment]
> 方便提供一下PaddleNLP和Paddle版本吗
PaddleNLP 2.6.1
Paddle 2.5.1

**Comment by abasi20** [comment]
> > 方便提供一下PaddleNLP和Paddle版本吗
> > PaddleNLP 2.6.1
> > Paddle 2.5.1

追踪代码是在在调用pybind  predictor的问题，我也看了一下predictor的代码，没看到问题。看看你们有没有解决。

**Comment by abasi20** [comment]
> > > 方便提供一下PaddleNLP和Paddle版本吗
> > > PaddleNLP 2.6.1
> > > Paddle 2.5.1
> 
> 追踪代码是在在调用pybind predictor的问题，我也看了一下predictor的代码，没看到问题。看看你们有没有解决。
多路召回配置
# 指定语义检索系统的Yaml配置文件
export PIPELINE_YAML_PATH=rest_api/pipeline/multi_recall_semantic_search.yaml
# 使用端口号 8891 启动模型服务
python rest_api/application.py 8891

**Comment by lugimzzz** [comment]
你可以使用paddle 2.4.x版本和paddlenlp2.5.x版本测试一下

**Comment by lugimzzz** [comment]
可以在paddlenlp套件提一个issue ，可以让套件的同学跟进，可能更合适

**Comment by abasi20** [comment]
> 你可以使用paddle 2.4.x版本和paddlenlp2.5.x版本测试一下

感谢
