### ISSUE TITLE
`create_parameter` is very slow

### ISSUE THREAD

**Issue by mattbarrett98** [PaddlePaddle/Paddle#58294]
### bug描述 Describe the Bug

I want to create a parameter from a paddle tensor, but it takes a very long time eg:
```python
# paddlepaddle == 2.5.1
import paddle
from time import perf_counter

t = paddle.randn((50000, 2000))

start = perf_counter()
param = paddle.create_parameter(t.shape, dtype=t.dtype, default_initializer=paddle.nn.initializer.Assign(t))
print(perf_counter() - start)
```
shows that it takes around 11 seconds (for me). It's fine for smaller tensors, but for larger tensors like here it's extremely slow, which could be problematic for larger networks with many large parameters.

I would have thought all that needs to happen here is just wrap the paddle tensor in a parameter object, but maybe I'm missing something or there's a better way of doing this.

Most of the overhead (~7s) seems to come from this line https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/initializer/assign.py#L80

**Comment by chenwhql** [comment]
> I want to create a parameter from a paddle tensor,

Is this tensor a special tensor? Can it be created by other initializers?

![image](https://github.com/PaddlePaddle/Paddle/assets/22561442/c27a4d51-2707-42cc-acb3-3f9708f6dab5)

If we can't use other initializers, we need to understand the impl of Assign. It is implemented by inheriting NumpyArrayInitializer. It will convert the input tensor into a numpy array first, and then convert it into a paddle.Tensor through the numpy array.

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/nn/initializer/assign.py

If `t = paddle.randn((50000, 2000))` is a GPU Tensor, it will undergo two copies, `gpu->cpu->gpu`, so it is very slow. Maybe we can try to initialize this tensor as a CPU tensor to reduce one copy.

Or we may need to optimize the implementation of Assign.

**Comment by mattbarrett98** [comment]
It's a special tensor whose values I want to retain, also I'm not using gpu here so I don't think copies are the problem. I've found a much quicker way:
```python
param = self.create_parameter(
     shape=x.shape,
     dtype=x.dtype,
     default_initializer=None,
 )
 param.set_value(x)
 ```
which takes under a second, but potentially optimising `Assign` might be useful.

**Comment by chenwhql** [comment]
set_value will directly copy the value into the target tensor, even if it is only using the CPU, theoretically it should be faster than using tensor->numpy array->tensor. Here, we will optimize the implementation of Assign initializer later. Thank you for your feedback.
