### ISSUE TITLE
华为昇腾310如何可以使用npu跑代码？

### ISSUE THREAD

**Issue by lijialin1999** [PaddlePaddle/Paddle#58320]
### 请提出你的问题 Please ask your question

华为昇腾Ascend310，FT2000cpu怎么才能使用NPU跑paddlepaddle代码呢？

**Comment by qili93** [comment]
您好，昇腾310芯片支持的设备都是Atlas设备，支持的CPU为鲲鹏920 CPU，飞桨开源社区暂未支持飞腾CPU和昇腾310的适配组合，如果您有这个组合的需求请联系飞桨商业团队寻求定制开发的支持。商业支持的联系入口：https://www.paddlepaddle.org.cn/install/customerinfo

昇腾设备型号对应关系，请参考
<img width="1257" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/1b6044ef-2c22-4ff5-9e3c-f3472506d4c1">

以上截图的入口位于：https://www.paddlepaddle.org.cn/install/other?docurl=/documentation/docs/zh/install/pip/linux-pip.html
