### ISSUE TITLE
[oneDNN] The scale and bias parameters of batchnorm need to support optional

### ISSUE THREAD

**Issue by xuxinyi389** [PaddlePaddle/Paddle#58326]
### Background
Previously, the scale and bias parameters of batchnorm did not support optional. But now https://github.com/PaddlePaddle/Paddle/pull/58226 has fixed this feature.
### Requirement
Now, could you please modify the oneDNN synchronization to fully support optional semantics

**Comment by xinyu-intel** [comment]
@zhanglirong1999 @LLee233 Please support the optional semantics from oneDNN side.

**Comment by LLee233** [comment]
Hi @xuxinyi389, during realizing implementation, we found BatchNorm seems not fully support optional Scale/Bias yet  [BatchNormInferMeta](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L568).

Is it intentional or accidentally ignored? Since we may use different implementation accordingly.

**Comment by LLee233** [comment]
Hi @xuxinyi389, PR [58488](https://github.com/PaddlePaddle/Paddle/pull/58488) is opened for supporting optional scale/bias.

**Comment by LLee233** [comment]
> Hi @xuxinyi389, during realizing implementation, we found BatchNorm seems not fully support optional Scale/Bias yet [BatchNormInferMeta](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L568).
> 
> Is it intentional or accidentally ignored? Since we may use different implementation accordingly.

And for added UT, I left a comment [here](https://github.com/PaddlePaddle/Paddle/pull/58358/files#r1375773108), would you mind taking a look? Thanks!

**Comment by xuxinyi389** [comment]
Hi,@LLee233, Can you tell me the situatios that BatchNormInferMeta does not support optional Scale/Bias?https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L620

**Comment by xuxinyi389** [comment]
> > Hi @xuxinyi389, during realizing implementation, we found BatchNorm seems not fully support optional Scale/Bias yet [BatchNormInferMeta](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L568).
> > Is it intentional or accidentally ignored? Since we may use different implementation accordingly.
> 
> And for added UT, I left a comment [here](https://github.com/PaddlePaddle/Paddle/pull/58358/files#r1375773108), would you mind taking a look? Thanks!
You're right, I'll fix the UT.

**Comment by LLee233** [comment]
> Hi,@LLee233, Can you tell me the situatios that BatchNormInferMeta does not support optional Scale/Bias?https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L620

Hi~ I was asking it because I saw you changed `DenseTensor` as `optional<DenseTensor>` elsewhere but seems not change `MetaTensor`. And about failure of creating BN op, I just tried creating cpp/py UT for case of no scale/bias input, and found they were all failed (all cases I tried were failed no matter activating mkldnn or not)... Even tried your UT by using `check_without_scale_and_bias()` , it also failed. Not sure if it's relative to `BatchNormInferMeta` or about other implementation.

**Comment by xuxinyi389** [comment]
> > Hi,@LLee233, Can you tell me the situatios that BatchNormInferMeta does not support optional Scale/Bias?https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L620
> 
> Hi~ I was asking it because I saw you changed `DenseTensor` as `optional<DenseTensor>` elsewhere but seems not change `MetaTensor`. And about failure of creating BN op, I just tried creating cpp/py UT for case of no scale/bias input, and found they were all failed (all cases I tried were failed no matter activating mkldnn or not)... Even tried your UT by using `check_without_scale_and_bias()` , it also failed. Not sure if it's relative to `BatchNormInferMeta` or about other implementation.

Hi,@LLee233, I understand. I will pull your code and fix the UT to see if there are any other issues. And referring to `LayerNormInferMeta`, `BatchNormInferMeta` is likely to be right.

**Comment by LLee233** [comment]
> > > Hi,@LLee233, Can you tell me the situatios that BatchNormInferMeta does not support optional Scale/Bias?https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/infermeta/multiary.cc#L620
> > 
> > 
> > Hi~ I was asking it because I saw you changed `DenseTensor` as `optional<DenseTensor>` elsewhere but seems not change `MetaTensor`. And about failure of creating BN op, I just tried creating cpp/py UT for case of no scale/bias input, and found they were all failed (all cases I tried were failed no matter activating mkldnn or not)... Even tried your UT by using `check_without_scale_and_bias()` , it also failed. Not sure if it's relative to `BatchNormInferMeta` or about other implementation.
> 
> Hi,@LLee233, I understand. I will pull your code and fix the UT to see if there are any other issues. And referring to `LayerNormInferMeta`, `BatchNormInferMeta` is likely to be right.

Okay, then I would be very thankful~
