### ISSUE TITLE
【CustomDevice Event】CustomEventManager中复用event导致ddp异步执行顺序乱序

### ISSUE THREAD

**Issue by zhurou603** [PaddlePaddle/Paddle#58347]
### bug描述 Describe the Bug

框架侧有两个stream，一个通信stream，一个计算stream，执行顺序是在计算流上下发concat kernel之后在通信流下发通信kernel之前，首先会在计算流上通过EventRecord在计算流上记录一个event，再使用StreamWaitEvent在通信流上等待event，目的是希望所有后续在通信流下发的kernel的执行必须等待至该event执行完成后再执行。但从profiler的数据来看，出错的位置说明在计算流上的concat_kernel还没有执行的时候，通信流上的allreduce就已经先执行了

本质原因是因为在执行EventRecord时有可能在第一个StreamWaitEvent还没有执行完的时候，host端就进行了同一个event的第二次EventRecord，此时前一次的EventRecord将会失效，因此前一次的concat和all reduce流同步失效，导致concat kernel后于all reduce执行。

![image](https://github.com/PaddlePaddle/Paddle/assets/32234672/d2f39768-2a96-4b5a-a303-2fad0e0e3311)

将复用event逻辑替换为每次record使用新的event之后loss能够稳定。

**Comment by ronny1996** [comment]
你好，能否更新一下 Paddle 到最新的 develop 分支
