### ISSUE TITLE
【Adam/AdamW】beta1_pow beta2_pow计算存在精度误差。

### ISSUE THREAD

**Issue by ZHUI** [PaddlePaddle/Paddle#58378]
### bug描述 Describe the Bug

AdamW 中paddle采用的是迭代乘法，存在精度损失，而torch是直接pow计算。

100个step后，beta1_pow 与 beta2_pow 的误差分别达到了`2.7e-6`,`1.25e-6`。这个精度误差会导致与torch的训练对不齐，长期困扰，paddle与torch训练效果对齐。
```python
>>> a["linear_34.w_0_fp32_master_0_beta1_pow_acc_0"]
array([2.3905195e-05], dtype=float32)
>>> np.power(0.9, 101) 
2.3905258998828788e-05
>>> (2.3905258998828788e-05 - 2.3905195e-05)/2.3905258998828788e-05
2.6771861702948805e-06
>>> 
>>> (a["linear_34.w_0_fp32_master_0_beta2_pow_acc_0"] - np.power(0.999, 101) ) /  np.power(0.999, 101)
array([1.2529086e-06], dtype=float32)
```

### Paddle实现
https://github.com/PaddlePaddle/Paddle/blob/ae1c6830c585b2ca67366a6be58dc6e6b8a36418/paddle/phi/kernels/gpu/adamw_kernel.cu#L133-L141

### Torch实现
https://github.com/pytorch/pytorch/blob/88244cd7a989d444d7bd4fe9cc9e336df0fb05ef/torch/csrc/api/src/optim/adamw.cpp#L120-L121

### 其他补充信息 Additional Supplementary Information

fused_adam 使用的是double类型beta1，`1 - at::native::pow_(beta1, *step_count)`

https://github.com/pytorch/pytorch/blob/88244cd7a989d444d7bd4fe9cc9e336df0fb05ef/aten/src/ATen/native/cuda/fused_adam_utils.cuh#L71C1-L72C1
<img width="803" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16911935/6b640895-b86e-40cf-8358-77be2e9f2fe7">

python 层计算，使用的是`float64`, `bias_correction1 = 1 - beta1 ** step`
https://github.com/pytorch/pytorch/blob/88244cd7a989d444d7bd4fe9cc9e336df0fb05ef/torch/optim/adamw.py#L418C1-L419

<img width="566" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16911935/39939cdb-a609-4c6c-b3ca-8f70910427d2">

#### 对比模拟测试
```python
import numpy as np

beta=np.array(0.9, dtype="float32")
beta_x = beta + 0
for x in range(100):
    beta_x = beta * beta_x
    
print("paddle: \t", beta_x)

res = 0.9 ** 101 
res2 = np.power(np.array(0.9, dtype="float64"), 101)
print("torch python:\t", res)
print("torch fuse:\t", res2)
print("abs diff paddle and torch python:\t", np.abs(res -beta_x) / res)
```

```bash
paddle:          2.3905195038330537e-05
torch python:    2.3905258998828788e-05
torch fuse:      2.3905258998828788e-05
abs diff paddle and torch python:        2.675582734916143e-06
```

**Comment by cqulilujia** [comment]
我的个人理解，不同平台or不同硬件上对不齐很正常，这个精度应该是不影响模型收敛的，对具体任务上的端到端性能应该是没有影响的。

**Comment by Ligoml** [comment]
是的，不同框架存在精度误差是正常的，之前在其他模型上验证过不影响模型训练~
