### ISSUE TITLE
请问有paddle框架下的CLIP_vit_base_patch16_224模型的源码吗

### ISSUE THREAD

**Issue by Laurazlj** [PaddlePaddle/Paddle#58417]
### 请提出你的问题 Please ask your question

你好，我最近需要用到模型的源码，发现paddle可以直接调用CLIP_vit_base_patch16_224模型，但是我没有找到这个模型在Paddle框架下的结构的源码，只找到了pytorch框架下的源码，请问能为我提供一下吗？非常感谢！

**Comment by yangjianfengo1** [comment]
您好，想请问一下您是怎么调用的

**Comment by Laurazlj** [comment]
> 您好，想请问一下您是怎么调用的
![image](https://github.com/PaddlePaddle/Paddle/assets/49232003/58ccd348-3601-4ed6-9212-61c813a93517)

**Comment by cuicheng01** [comment]
可以看[这里](https://github.com/PaddlePaddle/PaddleClas/blob/develop/ppcls/arch/backbone/model_zoo/foundation_vit.py)哈~
