### ISSUE TITLE
AttributeError: 'PaddleCloudRoleMaker' object has no attribute 'generate_role'

### ISSUE THREAD

**Issue by Hexiangkun** [PaddlePaddle/Paddle#58430]
### 请提出你的问题 Please ask your question

        role = role_maker.PaddleCloudRoleMaker(is_collective=True)
        fleet.init(role)
File "/usr/local/miniconda3/lib/python3.8/site-packages/paddle/fluid/incubate/fleet/base/fleet_base.py", line 210, in init
    self._role_maker.generate_role()
AttributeError: 'PaddleCloudRoleMaker' object has no attribute 'generate_role' in paddlepaddle==2.3.2

**Comment by yangjianfengo1** [comment]
Is it convenient to upgrade Paddle version to 2.5？
