### ISSUE TITLE
【HACKATHON 预备营】飞桨启航计划集训营

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/Paddle#58497]
# 飞桨启航计划集训营
<!DOCTYPE html>

💡 **Tip**：
  1. 想快速了解活动内容  ➡️ [简要活动说明](https://www.canva.cn/design/DAFzeTQ1pNg/_v_I0Wox03pyIsvTNsJ23w/edit?utm_content=DAFzeTQ1pNg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)  
  2. 启航计划已安排活动说明会 ➡️ [腾讯会议录播](https://meeting.tencent.com/v2/cloud-record/share?id=d1ec6c3e-3cd6-4321-842a-d52f939daba2&from=3&is-single=true)
  3. 「启航计划」周报管理repo ➡️https://github.com/PFCCLab/Starter 

## 飞桨启航计划简介

**「启航计划」** 是 **百度飞桨社区** 发起的远程项目，也是「护航计划」的前置活动（不了解护航计划请看这里 ➡️ [护航计划说明](https://github.com/PFCCLab/Camp)）。我们以开展**集训营**的形式，鼓励开发者积极参与开源项目，以此提升自己的代码实践能力，与社区共同成长 💪。

开发者提交申请材料并通过后，将会参与为期**2个月**密集的集训项目，具体集训内容主要分为 2 个方向：
- 基础方向：参与 **Paddle 核心框架**和 **Paddle CV套件**的 **【快乐开源】** 任务 💻（具体介绍看这里 ➡️ [飞桨快乐开源活动全新升级](https://github.com/PaddlePaddle/Paddle/issues/56689)），你将有机会参与社区里**最轻松愉快**的开源开发活动 😄。
- 大模型方向：参与 **PaddleMIX 跨模态大模型套件**的 【快乐开源】任务 🤖（具体介绍看这里 ➡️ [🏅️飞桨大模型套件快乐开源常规赛](https://github.com/PaddlePaddle/PaddleMIX/issues/272)），你将有机会接触社区里**最前沿**的大模型应用开发与工具建设 🤩。

集训期间，我们会提供精心设计的课程辅导 🧑🏻‍💻、相应的研发支持、随时随地都能使用的**线上 V100 开发环境** 🔧（申请方式看这里 ➡️ [飞桨线上开发环境——AI Studio](https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions#%E9%A3%9E%E6%A1%A8%E7%BA%BF%E4%B8%8A%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83ai-studio)）以帮助学员更好地融入项目，不断提升技术水平。我们鼓励学员积极互动和交流，希望每位学员都能够在集训期结束时取得优异的成绩并成功结营。

完成「启航计划」的学员将有机会获得丰厚的奖励 🎁 和荣誉证书 📃。此外，表现出色的开发者还有机会成为「护航计划」的潜在候选人，进一步参与到更具挑战性的任务中。我们期待与你一同踏上这个激动人心的学习和成长之旅 ！快来加入我们吧～～ 💓

> [!IMPORTANT]  
> 与「护航计划」的区别：
>   * 不限定开发者背景，企业和学生开发者均可参与。
>   * 不进行面试，直接进行简历筛选。
>   * 集训内容为完成 **【快乐开源项目】**，合入1个 PR 即满足结营条件，相对轻松愉快。
>   * 提供**高质量集训课程**，并以 PR review 交流的形式进行沟通，而非导师一对一带教的形式。
>   * 时间周期更短。能让没接触过飞桨的你，快速上手飞桨开源活动。

## 报名参与流程
1. 先选择**一个或两个方向**中感兴趣的、尚未完成的快乐开源项目任务（任务列表 ➡️ [基础方向](https://github.com/PaddlePaddle/Paddle/issues/56689#happy-tasks)、[大模型方向](https://github.com/PaddlePaddle/PaddleMIX/issues/272)），并在该 issue 区下回复，如：

```
【报名】 意向：
  1. 基础方向：Paddle Docathon、框架API易用性提升
  2. 大模型方向：新增人像美肤模型
```

2. 同时投递简历和参与意向至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)。
4. 通过筛选后，将会收到**确认邮件**。确认参与后将以远程的方式参与飞桨的【快乐开源活动】项目开发实践，成果以 PR（Pull Requests）的形式贡献到指定代码仓库，实训期 **2** 个月，集训人数上限 **30** 人，先到先得哦～

> [!NOTE]  
> 在实际集训过程中，你可选择 **报名意向以外** 的任务进行开发，但至少需要**合入 1 个意向内任务的 PR**。

### 一、整体流程

进入启航计划的学员可以自选感兴趣的快乐开源项目。为了更好地推进项目顺利进行，下面是我们为大家安排的一些日常任务：

* 按照要求提交双周周报 📄（两周一次）
* 根据自身兴趣参加集训课程 📖（一周一次）
* 至少合入 1 个快乐开源 PR 

### 二、集训内容

1. **集训任务**：
   完成【快乐开源】**热身任务**，并根据自己的意向认领相应的**命题任务**。
   * 必修：完成所有**热身打卡任务**
     1. [修改飞桨文档](https://github.com/PaddlePaddle/Paddle/issues/56689#warmup-tasks-1)
     2. [完成 Paddle 本地编译](https://github.com/PaddlePaddle/Paddle/issues/56689#warmup-tasks-2)
     3. [Stable-Diffusion 训练推理](https://github.com/PaddlePaddle/PaddleMIX/issues/273)
   * 自选：任意方向的**命题任务**。
5. **任务形式**：【占坑制认领任务】谁先认领谁做。
   * 最多保持 3 个任务在认领状态，做完可继续认领。
   * 认领后 1 个月内未完成，则自动释放。
6. **开发辅导**： PR review 交流、集训课程、提 issue 、助教回复。
7. **双周周报**： 每双周总结集训成果、技术成长或感悟，助教负责管理。

> [!WARNING]  
> **未提交双周周报** 则视为放弃集训计划‼️ 😐

### 三、结营考核

1. 结营要求：满足最低要求，方可顺利结营。
   1. 最低要求：至少合入一个**报名意向内任务 PR** ✅。（热身任务的 PR 不包括在内⚠️）
   2. 加分项：沉淀技术思考、提出可行性建议、甚至主导开展新任务等。
2. 结营成绩：
   1. 不通过：未满足最低要求。  
   2. 通过：满足最低要求。
   3. 优秀：满足最低要求，同时在活动过程中有加分项。
3. 结营奖励：
   1. 不通过：无。
   2. 通过：结营荣誉证书 📃 与 精美礼品 🎁。
   3. 优秀：
      * 结营荣誉证书 📃 与 精美礼品 🎁 ；
      * 进入【护航计划】候选；
      * 可申请一、二、三等奖的答辩（申请制）。

> [!NOTE]  
>  一、二、三等奖各 1 个，共 3 人。需表现优秀的开发者**主动申请并答辩**，并由评委小组进行综合评估。如无满足条件者则奖项空缺。
>  * 一等奖：PS5 🎮 
>  * 二等奖：Apple Watch SE ⌚️
>  * 三等奖：Airpods（第三代）🎧

## 启航计划时间安排

这是我们为训练营制定的详细日程和计划 ⬇️ 

|          **时间**          |          **日程**          |
| -------------------------- | -------------------------- |
| **2023.11.1 14:00**       | 发布集训项目，启动营员招募 |
| **2023.11.1 ~ 2023.11.17** | 持续公开接收简历，进行筛选     |
| **2023.11.13**        | 集训项目启动  |
| **2023.11.13 ～ 2024.1.15** | 参与集训项目             |
| **2024.1.15 ～ 2024.1.19** | 申请一、二、三等奖答辩     |
| **2024.1.19 23:59**        | 集训营结营，公布考核结果   |

> [!IMPORTANT]  
> 考虑到临近截止日，报名人数激增🔥，为了让更多的开发者有机会参与到启航计划项目，我们决定**简历接收截止日延后 1 周，至 11月17日**⚠️。

## 启航计划录取情况（已截止✅）

已通过 **29** 人，名单如下：
@NKNaN、@shiofjsaio、@YangWulve、@Hhankyangg、@sanbuphy、@Atlantisming、@GreatV、@Tsaiyue、 @Kaedeharai、@wyyang23、 @jiongjiongli、 @rhmaaa、 @cocoshe、 @zbt78 、 @YibinLiu666 、 @Turingg 、 @ooooo-create 、 @ccsuzzh、 @zade23、 @challengewly 、 @zoey333、 @unicornshell 、 @storm-ice 、 @YinKeYu 、 @Olive-2019 、 @fsczz 、@jiangziyan-693 、 @isLinXu 、 @jingsongliujing

⏰未通过的开发者，也可以认领快乐开源任务哦～合入PR仍会获得快乐开源的礼品～

**开营仪式**

我们会在训练营正式开始时为成员们举办的一个线上见面会，在这里可以认识班主任、助教、导师和其他学员，结交到志同道合的好友 👯

## 启航计划课程安排

| **时间**              | **课程**                            |
| --------------------- | :-----------------------------------: |
| **第一课 2023.11.15** | 走进飞桨社区 & 框架开源任务介绍     |
| **第二课 2023.11.22** | 热身打卡任务实践                    |
| **第三课 2023.11.29** | PaddleMIX & 视觉套件任务总览        |
| **第四课 2023.12.6**  | PaddleMIX 应用开发实践              |
| **第五课 2023.12.14** | 三个框架快乐开源任务讲解            |
| **第六课 2023.12.20** | PaddleMIX 代码结构讲解+剩余任务说明 |

## 启航计划结营考核情况

1. 根据结营要求，以下为通过考核的 15 位营员名单 📄：
@GreatV, @Hhankyangg, @Kaedeharai, @NKNaN, @Tsaiyue, @Turingg, @YibinLiu666, @ccsuzzh, @cocoshe, @fsczz, @ooooo-create, @jiangziyan-693, @sanbuphy, @zade23, @zbt78

2. 一、二、三等奖的获奖名单 📄：
    - 一等奖：@zbt78
    - 二等奖：@Tsaiyue
    - 三等奖：@ooooo-create

结营考核详细情况，请参考 https://github.com/PFCCLab/Starter/issues/123

**Comment by YibinLiu666** [comment]
【报名】 意向：
  1. 框架：框架API易用性提升 新增封装API paddle.nn.GLU

**Comment by YibinLiu666** [comment]
【报名】 意向：
基础方向：框架API易用性提升

**Comment by Turingg** [comment]
【报名】 意向：
   基础方向：新IR Python API适配升级、Paddle Docathon

**Comment by Turingg** [comment]
【报名】 意向：
  1. 基础方向：新IR Python API适配升级、Paddle Docathon

**Comment by Turingg** [comment]
【报名】 意向：
  基础方向：新IR Python API适配升级、Paddle Docathon

**Comment by cocoshe** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级

**Comment by Hhankyangg** [comment]
【报名】 意向： 
基础方向：
新IR Python API适配升级、Paddle Docathon、新增early stop功能
大模型方向：
新增人像美肤模型

**Comment by Liyulingyue** [comment]
【报名】 意向：
基础方向：Paddle Docathon

**Comment by sanbuphy** [comment]
【报名】 意向：
大模型方向：

新增音乐生成（Music Generation）gradio应用
新增音频生成图像（Audio-to-Image Generation）
fastdeploy版的sd15模型添加gradio界面

**Comment by GreatV** [comment]
【报名】 意向：
基础方向：

- 【Bug Fix】humanseg显存泄漏
- 增加训练图像、推理图像、标签图像可视化🆕

**Comment by ooooo-create** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级、增加类激活图🆕

**Comment by storm-ice** [comment]
【报名】 意向：
基础方向：框架API易用性提升

**Comment by youngdian1** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级

**Comment by ailijian** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级
大模型方向：新增 StableDiffusionXL Reference Control支持

**Comment by YinKeYu** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级

**Comment by ccsuzzh** [comment]
【报名】 意向：
  基础方向：新IR Python API适配升级、Paddle Docathon、框架API易用性提升

**Comment by zbt78** [comment]
【报名】 意向：
基础方向：复数数据类型扩展任务， 算子GPU性能优化

**Comment by jiangziyan-693** [comment]
【报名】 意向：
大模型方向：新增大模型的微调，美肤模型

**Comment by Tsaiyue** [comment]
【报名】 意向：
  1. 大模型方向：fastdeploy版的sd15模型添加gradio界面

**Comment by Kaedeharai** [comment]
【报名】 意向：
1、大模型方向：新增Mixture Canvas pipeline ，新增 StableDiffusionXL Reference Control支持
2、基础方向：Paddle Docathon

**Comment by rhmaaa** [comment]
【报名】 意向：
基础方向：算子GPU性能优化

**Comment by luotao1** [comment]
@YibinLiu666 @zbt78 @rhmaaa 请知悉：本次集训营没有【算子GPU性能优化】方向。

**Comment by zbt78** [comment]
已知悉，在报名中去掉这个方向。蟹蟹！



botaozhou
***@***.***







                       
Original Email
                       
                     

Sender:"Tao Luo"< ***@***.*** &gt;;

Sent Time:2023/11/10 11:13

To:"PaddlePaddle/Paddle"< ***@***.*** &gt;;

Cc recipient:"zbt78"< ***@***.*** &gt;;"Mention"< ***@***.*** &gt;;

Subject:Re: [PaddlePaddle/Paddle] 【HACKATHON 预备营】飞桨启航计划集训营 (Issue #58497)




 
@YibinLiu666 @zbt78 @rhmaaa 请知悉：本次集训营没有【算子GPU性能优化】方向。

**Comment by rhmaaa** [comment]
【报名】 意向：
1. 基础方向：新IR Python API适配升级 复数数据类型扩展任务 Paddle 之艾尔登（IR Dialect）快乐勇士挑战赛

2. 大模型方向：lora代码升级

**Comment by sunzhongkai588** [comment]
> 【报名】 意向： 基础方向：新IR Python API适配升级

@youngdian1 请提供简要的简历说明或开发经历说明，发送邮箱至 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)

**Comment by youngdian1** [comment]
【报名】 意向：
基础方向：科学计算

**Comment by zade23** [comment]
【报名】 意向：
  1. 基础方向：框架API易用性提升
  2. 大模型方向：Custom Diffusion 训练支持；Checkpoint Merger

**Comment by challengewly** [comment]
【报名】 意向：

基础方向：复数数据类型扩展任务
大模型方向：AudioLDM2支持文本到音频和文本到语音的生成

**Comment by White-93** [comment]
【报名】 意向：
  1. 基础方向：新IR Python API适配升级，Paddle Docathon。

**Comment by Olive-2019** [comment]
【报名】 意向：
  1. 基础方向：新IR Python API适配升级  Paddle 之艾尔登（IR Dialect）快乐勇士挑战赛

**Comment by fsczz** [comment]
【报名】 意向：
基础方向：新IR Python API适配升级、复数数据类型扩展任务

**Comment by unicornshell** [comment]
【报名】 意向：
  1. 基础方向：Paddle Docathon、框架API易用性提升
  2. 大模型方向：新增模型vits-svc模型，PaddleMIX ppdiffusers中升级attention相关代码

**Comment by sunzhongkai588** [comment]
已结营，结营详情请参考 https://github.com/PFCCLab/Starter/issues/123
