### ISSUE TITLE
使用paddle将模型参数加载到模型中报错

### ISSUE THREAD

**Issue by zhang0391** [PaddlePaddle/Paddle#58518]
### 请提出你的问题 Please ask your question

您好，我在使用我们这边的一个模型验证工具，将模型参数加载到模型中时，报了如下的错误：
<img width="1162" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/52494652/733a2f9b-e177-416c-a41b-7d7eb88229ef">

InvalidArgumentError: The number of variables to be loaded is 0, expect it to be greater than 0.
[Hint: Expected out_var_names.size() > 0UL, but received out_var_names.size():0 <= 0UL:0.] (at /paddle/paddle/fluid/operators/load_combine_op.h:46)
[operator < load_combine > error]

我们使用的paddle版本是paddle2.4，请问这是paddle版本不兼容吗，帮忙看看怎么解决呢

**Comment by SigureMo** [comment]
> 我们使用的paddle版本是paddle2.4，请问这是paddle版本不兼容吗

使用之前保存时候的 Paddle 版本试试呢？
