### ISSUE TITLE
gpu更改不了的问题

### ISSUE THREAD

**Issue by NJUsw** [PaddlePaddle/Paddle#58510]
### 请提出你的问题 Please ask your question

echo $CUDA_VISIBLE_DEVICES
7
但是任然报错
Out of memory error on GPU 0. Cannot allocate 128.000000MB memory on GPU 0, 39.334839GB memory has been allocated and available memory is only 111.187500MB.
还是在使用GPU 0

**Comment by SigureMo** [comment]
根据文档，使用 `FLAGS_selected_gpus` 试试呢？

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/cuda_places_cn.html

**Comment by NJUsw** [comment]
> 根据文档，使用 `FLAGS_selected_gpus` 试试呢？
> 
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/static/cuda_places_cn.html

您好，请问一下具体怎么做呢，我看文档说下个版本修复CUDA_VISIBLE_DEVICES无效的问题

**Comment by SigureMo** [comment]
> 您好，请问一下具体怎么做呢

```bash
FLAGS_selected_gpus=7 your_command
```

这样试试呢？
