### ISSUE TITLE
Wrong LaTeX format in operator documentation

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5852]
For an example, in `lrn_op.cc` we have

https://github.com/PaddlePaddle/Paddle/blob/32b10d3bc4f269ff0c253df163db72d10454d4d5/paddle/operators/lrn_op.cc#L91-L96

This violates the rule of LaTex in Markdown -- math equations must follow the starting $$, but not on the second line.  This violation leads to wrong rendering of the equation on paddlepaddle.org:

<img width="1329" alt="screen shot 2017-11-22 at 4 13 56 pm" src="https://user-images.githubusercontent.com/1548775/33154890-7a54f30c-cfa0-11e7-89cb-d645cc452ae4.png">

This issue is the same as https://github.com/PaddlePaddle/PaddlePaddle.org/issues/339

**Comment by shanyi15** [comment]
![image](https://user-images.githubusercontent.com/35982308/35913695-94c83c94-0c3b-11e8-8ea1-7d03757e3315.png)
This problem has been repaired, please see http://www.paddlepaddle.org/docs/develop/documentation/zh/operators.html#permalink-131-lrn
