### ISSUE TITLE
如何在paddle-gpu 2.5或更新的版本上，使用英伟达用于加密货币计算的卡，用于一般的推理任务

### ISSUE THREAD

**Issue by hai4john** [PaddlePaddle/Paddle#58526]
基本上 用于加密货币计算的卡 例如 CMP 30hx 和 P104、P106等卡 都会识别不到，有什么配置项可以设置吗？
PS：这些卡在pytorch和jax 框架下都能正常使用。

**Comment by engineer1109** [comment]
这种问题不应该自己排查吗，nvidia-smi有效的话，cuda应该可用

**Comment by hai4john** [comment]
> 这种问题不应该自己排查吗，nvidia-smi有效的话，cuda应该可用

Paddle下才遇到，其他框架都没问题。
另外，Paddle的cuda相关函数也是可以认到卡的
    paddle.device.cuda.device_count()
    paddle.device.get_device()

**Comment by engineer1109** [comment]
我估计多半是二进制兼容问题，自己编译一下试试
