### ISSUE TITLE
AI Studio的python（3.7）和paddle develop版本过老

### ISSUE THREAD

**Issue by zyz-rise** [PaddlePaddle/Paddle#58556]
### 需求描述 Feature Description

AI Studio的python（3.7）和paddle develop版本过老，python版本没办法升级导致一些基于paddle开发的科学计算库无法正常使用，比如deepxde最新的包也用不了。
可以将AI Studio的python升级至更高版本吗？

**Comment by HydrogenSulfate** [comment]
一个临时的解决办法是启动项目之后手动卸载已有的paddle，安装官网上最新的develop paddle。
