### ISSUE TITLE
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5855]
NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.
  Possible C/C++ prototypes are:
    IVector::create(std::vector< int,std::allocator< int > > const &,bool)
    IVector::create(std::vector< int,std::allocator< int > > const &)

**Comment by QiJune** [comment]
请详细描述使用过程

**Comment by 466821202** [comment]
NotImplementedErrorTraceback (most recent call last)
<ipython-input-1-7dcfae19ac59> in <module>()
     82         reader=train_reader, num_passes=10, event_handler=event_handler)
     83 if __name__ == '__main__':
---> 84     main()

<ipython-input-1-7dcfae19ac59> in main()
     80 
     81     trainer.train(
---> 82         reader=train_reader, num_passes=10, event_handler=event_handler)
     83 if __name__ == '__main__':
     84     main()

/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.pyc in train(self, reader, num_passes, event_handler, feeding)
    167                 pass_type = self.__parameter_updater__.startBatch(
    168                     len(data_batch))
--> 169                 in_args = feeder(data_batch)
    170                 self.__prepare_parameter__(in_args)
    171                 self.__gradient_machine__.forwardBackward(in_args, out_args,

/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.pyc in __call__(self, dat, argument)
    280 
    281     def __call__(self, dat, argument=None):
--> 282         return self.convert(dat, argument)
    283 
    284     @staticmethod

/usr/local/lib/python2.7/dist-packages/paddle/v2/data_feeder.pyc in convert(self, dat, argument)
    131             return retv
    132 
--> 133         return DataProviderConverter.convert(self, reorder_data(dat), argument)

/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.pyc in convert(self, dat, argument)
    275 
    276         for scanner in scanners:
--> 277             scanner.finish_scan(argument)
    278 
    279         return argument

/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.pyc in finish_scan(self, argument)
    209 
    210     def finish_scan(self, argument):
--> 211         ids = swig_paddle.IVector.create(self.__ids__, self.data_in_gpu)
    212         assert isinstance(argument, swig_paddle.Arguments)
    213         argument.setSlotIds(self.pos, ids)

/usr/local/lib/python2.7/dist-packages/py_paddle/swig_paddle.pyc in create(*args)
   1419         create(vector_int data) -> IVector
   1420         """
-> 1421         return _swig_paddle.IVector_create(*args)
   1422 
   1423     if _newclass:

NotImplementedError: Wrong number or type of arguments for overloaded function 'IVector_create'.
  Possible C/C++ prototypes are:
    IVector::create(std::vector< int,std::allocator< int > > const &,bool)
    IVector::create(std::vector< int,std::allocator< int > > const &)

**Comment by 466821202** [comment]
http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html
用的是这个  数据是自己的  开始训练就报这个错了 完全没有头绪

**Comment by 466821202** [comment]
@QiJune http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html
用的是这个 数据是自己的 开始训练就报这个错了 完全没有头绪

**Comment by QiJune** [comment]
看起来是输入数据有问题。请问是开始训练一段时间出问题，还是立即出问题？
可以把网络配置部分给贴一下

**Comment by Yancey1989** [comment]
由于很长时间没有更新，先关闭这个issue了，如依然有问题还请随时打开它。
