### ISSUE TITLE
图片文件路径中包含中文，读取文件失败

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5858]
百度出来的的方法都测试了 不好使
单独这样写unicode(img_path, 'utf-8').encode('utf-8') 好使 但是paddle这样写就报错了
import os
img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/中文中文中文中文中文中文.jpg"
os.access(unicode(img_path, 'utf-8').encode('utf-8'), os.F_OK)
Out[3]:
True
第一种
if os.access(img_path.decode('gbk'), os.F_OK):
UnicodeEncodeError: 'ascii' codec can't encode characters in position 34-42: ordinal not in range(128)
第二种
 File "reader.py", line 36, in reader
    if os.access(img_path.decode('utf-8'), os.F_OK):
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 34: invalid continuation byte
第三种
File "reader.py", line 36, in reader
    if os.access(unicode(img_path , "utf8"), os.F_OK):
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xce in position 34: invalid continuation byte
第四种
#!/usr/bin/env Python
# coding=utf-8
第五种  这样写代码直接不执行了
import sys
reload(sys)
sys.setdefaultencoding("utf-8")
str = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg".decode('utf-8')
print str
单独测试

"/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
#!/usr/bin/env Python
# coding=utf-8
import os
os.access("/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg", os.F_OK)
Out[1]:
True
In [4]:

img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
os.access(img_path.decode('utf-8'), os.F_OK)
img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
os.access(img_path.decode('utf-8'), os.F_OK)

UnicodeEncodeErrorTraceback (most recent call last)
<ipython-input-4-cf7b0ee9fd6f> in <module>()
      1 img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
----> 2 os.access(img_path.decode('utf-8'), os.F_OK)

UnicodeEncodeError: 'ascii' codec can't encode characters in position 34-54: ordinal not in range(128)

In [5]:

img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
os.access(img_path.decode('gbk'), os.F_OK)
img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
os.access(img_path.decode('gbk'), os.F_OK)

UnicodeDecodeErrorTraceback (most recent call last)
<ipython-input-5-2e9cd804c693> in <module>()
      1 img_path = "/nfs/DDS/file/SYSBOOKDOC/2017/1/1/七里河区秀川派出所兰州七里河蓝天幼儿园门口.jpg"
----> 2 os.access(img_path.decode('gbk'), os.F_OK)

UnicodeDecodeError: 'gbk' codec can't decode bytes in position 48-49: illegal multibyte sequence

**Comment by QiJune** [comment]
这里是读入图片数据吗？能贴一下你的示例代码吗

**Comment by 466821202** [comment]
@QiJune #!/usr/bin/env Python
# coding=utf-8
import random
from paddle.v2.image import load_and_transform
import paddle.v2 as paddle
from multiprocessing import cpu_count
import os
    
def train_mapper(sample):
    '''
    map image path to type needed by model input layer for the training set
    '''
    img, label = sample
    #if os.access(img, os.F_OK):
    imgpath1 = img
    img = paddle.image.load_image(img)
    try:
        img = paddle.image.simple_transform(img, 224, 224, True)
    except:
        print imgpath1
    
    return img.flatten().astype('float32'), label


def test_mapper(sample):
    '''
    map image path to type needed by model input layer for the test set
    '''
    img, label = sample
    img = paddle.image.load_image(img)
    img = paddle.image.simple_transform(img, 224, 224, True)
    return img.flatten().astype('float32'), label


def train_reader(train_list, buffered_size=1024):
    def reader():
        with open(train_list, 'r') as f:
            lines = [line.strip() for line in f]
            for line in lines:
                try:
                    img_path, lab = line.strip().split(',')
                except:
                    print line
                yield img_path, int(lab)
    return paddle.reader.xmap_readers(train_mapper, reader,
                                      cpu_count(), buffered_size)


def test_reader(test_list, buffered_size=1024):
    def reader():
        with open(test_list, 'r') as f:
            lines = [line.strip() for line in f]
            for line in lines:
                img_path, lab = line.strip().split(',')
                yield img_path, int(lab)

    return paddle.reader.xmap_readers(test_mapper, reader,
                                      cpu_count(), buffered_size)


if __name__ == '__main__':
    for im in train_reader('train.list'):
        print len(im[0])
    for im in train_reader('test.list'):
        print len(im[0])

**Comment by 466821202** [comment]
@QiJune    图片路径是中文的时候就会报错

**Comment by QiJune** [comment]
paddle读入图片使用的是opencv提供的接口，在python/paddle/v2/image.py文件中


```python
def load_image(file, is_color=True):
    flag = 1 if is_color else 0
    im = cv2.imread(file, flag)
    return im
```

可以尝试把文件路径改为gbk编码试试。

```
file.encode('gbk')
```

**Comment by Yancey1989** [comment]
这个issue由于长时间未更新先关闭了，如有依然有问题请随时重新打开它。
