### ISSUE TITLE
麒麟鲲鹏从源码编译paddle遇到生成的whl无法pip install

### ISSUE THREAD

**Issue by tammy-na** [PaddlePaddle/Paddle#58586]
### bug描述 Describe the Bug

cmake .. -DPY_VERSION=3.8 -DPYTHON_EXECUTABLE=/anaconda3/envs/python38/bin/python3.8  -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF -DPYTHON_INCLUDE_DIR=/anaconda3/envs/python38/include/python3.8 -DPYTHON_LIBRARY=/anaconda3/envs/python38/lib/libpython3.8.so
是否需要加
DCMAKE_CXX_FLAGS="-Wno-error -w"？编译之后生成的whl无法安装

**Comment by yangy996** [comment]
可以看这篇文章进行编译
https://blog.csdn.net/YY007H/article/details/125386851
