### ISSUE TITLE
【demo】【所有demo中的test.sh存在bug】

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#586]
1. 在使用demo中test.sh脚本时，代码中，function get_best_pass()方法的目的是找到cost最小的pass-xxx模型。但是在使用sort排序是没有加-n参数，所得到的结果并不一定是最小的。
例如，在semantic_role_labeling中，训练500个模型，按照test.sh中脚本执行方法是，最小的是cost=10.0364的模型 00376，但实际上有存在cost=7.xxx的模型存在。需要对sort命令进行添加按数字排序参数。
![image](https://cloud.githubusercontent.com/assets/6229206/20585011/bb49c46e-b232-11e6-9e66-daf9ff038b91.png)

![image](https://cloud.githubusercontent.com/assets/6229206/20585000/a536cd98-b232-11e6-8ec3-12e3e145e41e.png)

**Comment by wen-bo-yang** [comment]
predict.sh中也可能存在该问题

**Comment by zhangjcqq** [comment]
确实存在该问题，需要更新一下代码。

**Comment by luotao1** [comment]
#593 修复了srl demo中的问题

**Comment by backyes** [comment]
@luotao1 

说所有test有问题，都fix了么？解决了就close 此issue

**Comment by luotao1** [comment]
@wen-bo-yang 还有哪些有问题？ @qingqing01 说image demo那个没问题的

**Comment by wen-bo-yang** [comment]
@luotao1 情感分析的也没问题，我重新跑了边，和青青碰了下这块是正常的。烦请close这个issue吧
