### ISSUE TITLE
paddle.mod 算子结果与 torch.fmod 不同，而是与 torch.remainder 相同

### ISSUE THREAD

**Issue by songh11** [PaddlePaddle/Paddle#58600]
### bug描述 Describe the Bug

paddle 版本：2.5.1
pytorch版本：2.1.0

```
import paddle
import torch

paddle.mod(paddle.to_tensor([-3., -2, -1, 1, 2, 3]), paddle.to_tensor([2.])) # [1. , -0., 1. , 1. , 0. , 1. ]
torch.fmod(torch.tensor([-3., -2, -1, 1, 2, 3]), 2) # [-1., -0., -1.,  1.,  0.,  1.]
torch.remainder(torch.tensor([-3., -2, -1, 1, 2, 3]), 2) # [1. , -0., 1. , 1. , 0. , 1. ]

```

**Comment by Vvsmile** [comment]
目前paddle.mod和remainder结果相同，实现torch.fmod可以参考，下面的实现。
```
import numpy as np
import torch
import paddle

def trunc_div(a, b):
    ipt = paddle.divide(a, b)
    sign_ipt = paddle.sign(ipt)
    abs_ipt = paddle.abs(ipt)
    abs_ipt = paddle.floor(abs_ipt)
    out = paddle.multiply(sign_ipt, abs_ipt)
    return out

def fmod(a, b):
    return a - trunc_div(a, b) * b

def test():
    x = np.random.randn(1, 1, 4, 4) * np.pi
    x = x.astype(np.float32)
    thx = torch.from_numpy(x).cuda()
    thx.requires_grad = True
    half_pi = np.pi / 2
    thy = torch.fmod(thx, half_pi)
    loss1 = thy.pow(2).sum()
    loss1.backward()
    print(thy, thx.grad)

    pdx = paddle.to_tensor(x)
    pdx.stop_gradient = False
    pd_half_pi = paddle.to_tensor([half_pi], dtype=paddle.float32)
    # pdy = fmod(pdx, pd_half_pi)
    pdy = pdx.mod(pd_half_pi)
    loss2 = pdy.pow(2).sum()
    loss2.backward()
    print(pdy, pdx.grad)

if __name__ == '__main__':
    test()

```

**Comment by songh11** [comment]
> 目前paddle.mod和remainder结果相同，实现torch.fmod可以参考，下面的实现。
> 
> ```
> import numpy as np
> import torch
> import paddle
> 
> def trunc_div(a, b):
>     ipt = paddle.divide(a, b)
>     sign_ipt = paddle.sign(ipt)
>     abs_ipt = paddle.abs(ipt)
>     abs_ipt = paddle.floor(abs_ipt)
>     out = paddle.multiply(sign_ipt, abs_ipt)
>     return out
> 
> def fmod(a, b):
>     return a - trunc_div(a, b) * b
> 
> def test():
>     x = np.random.randn(1, 1, 4, 4) * np.pi
>     x = x.astype(np.float32)
>     thx = torch.from_numpy(x).cuda()
>     thx.requires_grad = True
>     half_pi = np.pi / 2
>     thy = torch.fmod(thx, half_pi)
>     loss1 = thy.pow(2).sum()
>     loss1.backward()
>     print(thy, thx.grad)
> 
>     pdx = paddle.to_tensor(x)
>     pdx.stop_gradient = False
>     pd_half_pi = paddle.to_tensor([half_pi], dtype=paddle.float32)
>     # pdy = fmod(pdx, pd_half_pi)
>     pdy = pdx.mod(pd_half_pi)
>     loss2 = pdy.pow(2).sum()
>     loss2.backward()
>     print(pdy, pdx.grad)
> 
> if __name__ == '__main__':
>     test()
> ```

感谢回复，那 paddle 文档这里是否也需要修一下，https://github.com/PaddlePaddle/Paddle/issues/58600#issuecomment-1790386571
![image](https://github.com/PaddlePaddle/Paddle/assets/75419275/fdac825c-e4f2-45ae-8376-48ecb62016f6)

**Comment by Vvsmile** [comment]
> > 目前paddle.mod和remainder结果相同，实现torch.fmod可以参考，下面的实现。
> > ```
> > import numpy as np
> > import torch
> > import paddle
> > 
> > def trunc_div(a, b):
> >     ipt = paddle.divide(a, b)
> >     sign_ipt = paddle.sign(ipt)
> >     abs_ipt = paddle.abs(ipt)
> >     abs_ipt = paddle.floor(abs_ipt)
> >     out = paddle.multiply(sign_ipt, abs_ipt)
> >     return out
> > 
> > def fmod(a, b):
> >     return a - trunc_div(a, b) * b
> > 
> > def test():
> >     x = np.random.randn(1, 1, 4, 4) * np.pi
> >     x = x.astype(np.float32)
> >     thx = torch.from_numpy(x).cuda()
> >     thx.requires_grad = True
> >     half_pi = np.pi / 2
> >     thy = torch.fmod(thx, half_pi)
> >     loss1 = thy.pow(2).sum()
> >     loss1.backward()
> >     print(thy, thx.grad)
> > 
> >     pdx = paddle.to_tensor(x)
> >     pdx.stop_gradient = False
> >     pd_half_pi = paddle.to_tensor([half_pi], dtype=paddle.float32)
> >     # pdy = fmod(pdx, pd_half_pi)
> >     pdy = pdx.mod(pd_half_pi)
> >     loss2 = pdy.pow(2).sum()
> >     loss2.backward()
> >     print(pdy, pdx.grad)
> > 
> > if __name__ == '__main__':
> >     test()
> > ```
> 
> 感谢回复，那 paddle 文档这里是否也需要修一下，[#58600 (comment)](https://github.com/PaddlePaddle/Paddle/issues/58600#issuecomment-1790386571) ![image](https://user-images.githubusercontent.com/75419275/279953896-fdac825c-e4f2-45ae-8376-48ecb62016f6.png)

可否附一下链接指路，感谢

**Comment by songh11** [comment]
> > > 目前paddle.mod和remainder结果相同，实现torch.fmod可以参考，下面的实现。
> > > ```
> > > import numpy as np
> > > import torch
> > > import paddle
> > > 
> > > def trunc_div(a, b):
> > >     ipt = paddle.divide(a, b)
> > >     sign_ipt = paddle.sign(ipt)
> > >     abs_ipt = paddle.abs(ipt)
> > >     abs_ipt = paddle.floor(abs_ipt)
> > >     out = paddle.multiply(sign_ipt, abs_ipt)
> > >     return out
> > > 
> > > def fmod(a, b):
> > >     return a - trunc_div(a, b) * b
> > > 
> > > def test():
> > >     x = np.random.randn(1, 1, 4, 4) * np.pi
> > >     x = x.astype(np.float32)
> > >     thx = torch.from_numpy(x).cuda()
> > >     thx.requires_grad = True
> > >     half_pi = np.pi / 2
> > >     thy = torch.fmod(thx, half_pi)
> > >     loss1 = thy.pow(2).sum()
> > >     loss1.backward()
> > >     print(thy, thx.grad)
> > > 
> > >     pdx = paddle.to_tensor(x)
> > >     pdx.stop_gradient = False
> > >     pd_half_pi = paddle.to_tensor([half_pi], dtype=paddle.float32)
> > >     # pdy = fmod(pdx, pd_half_pi)
> > >     pdy = pdx.mod(pd_half_pi)
> > >     loss2 = pdy.pow(2).sum()
> > >     loss2.backward()
> > >     print(pdy, pdx.grad)
> > > 
> > > if __name__ == '__main__':
> > >     test()
> > > ```
> > 
> > 
> > 感谢回复，那 paddle 文档这里是否也需要修一下，[#58600 (comment)](https://github.com/PaddlePaddle/Paddle/issues/58600#issuecomment-1790386571) ![image](https://user-images.githubusercontent.com/75419275/279953896-fdac825c-e4f2-45ae-8376-48ecb62016f6.png)
> 
> 可否附一下链接指路，感谢

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.4/guides/model_convert/pytorch_api_mapping_cn.html#pytorch-1-8-paddle-2-0-api
这里有一个，另外还有 floor_divide 的也不一样，但是 pytorch 后面弃用了

**Comment by Vvsmile** [comment]
> > 目前paddle.mod和remainder结果相同，实现torch.fmod可以参考，下面的实现。
> > ```
> > import numpy as np
> > import torch
> > import paddle
> > 
> > def trunc_div(a, b):
> >     ipt = paddle.divide(a, b)
> >     sign_ipt = paddle.sign(ipt)
> >     abs_ipt = paddle.abs(ipt)
> >     abs_ipt = paddle.floor(abs_ipt)
> >     out = paddle.multiply(sign_ipt, abs_ipt)
> >     return out
> > 
> > def fmod(a, b):
> >     return a - trunc_div(a, b) * b
> > 
> > def test():
> >     x = np.random.randn(1, 1, 4, 4) * np.pi
> >     x = x.astype(np.float32)
> >     thx = torch.from_numpy(x).cuda()
> >     thx.requires_grad = True
> >     half_pi = np.pi / 2
> >     thy = torch.fmod(thx, half_pi)
> >     loss1 = thy.pow(2).sum()
> >     loss1.backward()
> >     print(thy, thx.grad)
> > 
> >     pdx = paddle.to_tensor(x)
> >     pdx.stop_gradient = False
> >     pd_half_pi = paddle.to_tensor([half_pi], dtype=paddle.float32)
> >     # pdy = fmod(pdx, pd_half_pi)
> >     pdy = pdx.mod(pd_half_pi)
> >     loss2 = pdy.pow(2).sum()
> >     loss2.backward()
> >     print(pdy, pdx.grad)
> > 
> > if __name__ == '__main__':
> >     test()
> > ```
> 
> 感谢回复，那 paddle 文档这里是否也需要修一下，[#58600 (comment)](https://github.com/PaddlePaddle/Paddle/issues/58600#issuecomment-1790386571) ![image](https://user-images.githubusercontent.com/75419275/279953896-fdac825c-e4f2-45ae-8376-48ecb62016f6.png)

非常感谢，我会把问题反映给相关负责人，如在PaddlePaddle的使用过程及文档阅读中发现其他问题，欢迎继续反馈！

**Comment by luotao1** [comment]
@songh11 可以提一个PR直接修一下 https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/model_convert/pytorch_api_mapping_cn.md 在develop版本进行修改后，cherry-pick到release/2.4分支和release/2.5分支
