### ISSUE TITLE
The right way to link to nnpack

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5863]
In our root CMakeLists.txt file, we have

https://github.com/PaddlePaddle/Paddle/blob/d883547bf072f1edd05eb52854e56970b50e7203/CMakeLists.txt#L177-L180

It uses the special variable EXTERNAL_LIBS.  

@hedaoyuan I am wondering why glog and gflags and many other third-party libraries don't need to be added to EXTERNAL_LIBS, but nnpack has to be?

Could @gangliao have a look at this issue as well? Thanks!

**Comment by gangliao** [comment]
glog and gflags and many other third-party libraries are also included.

https://github.com/PaddlePaddle/Paddle/blob/d883547bf072f1edd05eb52854e56970b50e7203/CMakeLists.txt#L156-L163

@wangkuiyi

**Comment by wangkuiyi** [comment]
@gangliao Got it. Thanks. I am closing this issue.
