### ISSUE TITLE
请教一个问题

### ISSUE THREAD

**Issue by chaoaibeidanci** [PaddlePaddle/Paddle#58646]
### 请提出你的问题 Please ask your question

麻烦请教下各位，AttributeError: module 'paddle.fluid.dygraph' has no attribute 'load_dygraph'这个，我降低到2.0的版本，还是报错了，该如何解决呢

**Comment by 6clc** [comment]
麻烦问一下，您是必须使用和这个接口吗？如果是必须，我也得挨个版本回去看看，看历史记录这个接口得追溯的paddle1.x版本了https://github.com/PaddlePaddle/Paddle/issues/21252。
