### ISSUE TITLE
Wrong LaTeX syntax in the SGD operator comment

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#5866]
https://github.com/PaddlePaddle/Paddle/blob/d883547bf072f1edd05eb52854e56970b50e7203/paddle/operators/sgd_op.cc#L56-L58

displays as

<img width="834" alt="screen shot 2017-11-22 at 7 32 42 pm" src="https://user-images.githubusercontent.com/1548775/33158103-f7e99640-cfbb-11e7-8320-e45dc491663b.png">

**Comment by abhinavarora** [comment]
@wangkuiyi I think we will encounter the same problem in many other ops. Do you know where I can see the generated documents?

**Comment by luotao1** [comment]
@abhinavarora You can see the generated documents in http://www.paddlepaddle.org/docs/develop/documentation/zh/operators.html
