### ISSUE TITLE
安装适配华为昇腾910B芯片的Paddle-NPU版本失败

### ISSUE THREAD

**Issue by Jeremy-lf** [PaddlePaddle/Paddle#58728]
### bug描述 Describe the Bug

按照官网给的教程安装Paddle-NPU版本，
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/hardware_support/npu_docs/paddle_install_cn.html
拉取镜像后显示如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/45171399/7f12030b-33c4-4b88-8e8f-ffe7f79395aa)
然后执行docker，会报如下错误
![image](https://github.com/PaddlePaddle/Paddle/assets/45171399/d871205b-b7f9-4825-a926-ecb40cf8f8c3)
应该怎么解决？

**Comment by YanhuiDua** [comment]
你好，昇腾安装说明，请参考：https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
