### ISSUE TITLE
paddle有支持实时流训练的计划吗？

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#5879]
目前了解到只能离线训练了，拿到模型，再infer。模型无法做到根据实时流数据更新

**Comment by reyoung** [comment]
Paddle使用Python作为数据提供器。如果提供数据的时候是流式的提供，譬如一个用Python读消息队列，那么Paddle就可以根据实时流数据更新

**Comment by lcy-seso** [comment]
@reyoung 我觉得这个问题有两个层面，一个是功能层面，比如从功能层面整个训练是如何在线上进运作的；另一个是算法层面，有一些专门的online学习算法，是否有这方面的要求也需要用户来提供信息。

如果希望支持请具体的列出一些功能需求。比如：

1. 期待的训练过程是如何运作；
2. 如何接入实时数据流；
3. 有没有性能要求；
4. 有没有特定算法和模型要求；
……

Paddle即使支持，也请清晰地描述需求，无法只根据一句话去支持一类功能。
