### ISSUE TITLE
【demo】image_classification在train时，配置的num_passes为200，而在predict时，取的模型为model=cifar_vgg_model/pass-00299/。

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#588]
【demo】image_classification在train时，配置的num_passes为200，而在predict时，取的模型为model=cifar_vgg_model/pass-00299/。

![image](https://cloud.githubusercontent.com/assets/12882811/20585541/e16a92c8-b236-11e6-85b5-5f70191f9356.png)

![image](https://cloud.githubusercontent.com/assets/12882811/20585553/f376f10a-b236-11e6-862b-eb2111635015.png)

**Comment by qingqing01** [comment]
感谢提出，train.sh里应该改成300个pass， 这个demo和Torch的一个demo相同，torch也是采用300个epoc 。http://torch.ch/blog/2015/07/30/cifar.html

**Comment by luotao1** [comment]
#597 fix it
