### ISSUE TITLE
[bug]2.5.2版本多线程并发执行时程序崩溃，2.4版本测试正常

### ISSUE THREAD

**Issue by yjbdsky** [PaddlePaddle/Paddle#58810]
**一、当多个Predictor运行时会panic.**
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x7f33fe906520]

![image](https://github.com/PaddlePaddle/Paddle/assets/20083081/a286b1b3-4256-4774-87fb-1f3319ffb4e9)
![image](https://github.com/PaddlePaddle/Paddle/assets/20083081/8d393625-3653-4659-a19f-bb5967ac9515)

**二、错误：**
![image](https://github.com/PaddlePaddle/Paddle/assets/20083081/e1e0f779-f621-4a8b-aca4-f28e2e0de4ce)

**三、paddle_inference_c版本：**
Paddle version: 2.5.2.post120
GIT COMMIT ID: 3a1b1659a405a044ce806fbe027cc146f1193e6d
WITH_MKL: ON
WITH_MKLDNN: ON
WITH_GPU: ON
WITH_ROCM: OFF
WITH_IPU: OFF
CUDA version: 12.0
CUDNN version: v8.9
CXX compiler version: 12.2.0
WITH_TENSORRT: ON
TensorRT version: v8.6.1.6

**Comment by yjbdsky** [comment]
https://github.com/PaddlePaddle/Paddle-Inference-Demo
样例中的go示例是并发的，但启动gpu就和我报错一样的，不启用gpu可正常运行

**Comment by yjbdsky** [comment]
补充一下，使用cpu不报错，使用ＧＰＵ，单卡1600并发才会报错
https://github.com/PaddlePaddle/Paddle/issues/45437
看起来和这个问题类似

**Comment by yjbdsky** [comment]
增加环境变量　export FLAGS_allocator_strategy=naive_best_fit　后再运行问题未解决

**Comment by yjbdsky** [comment]
测试了2.4版本，gpu的可以并发

**Comment by raoyutian** [comment]
2.5.X版本问题很多的。我也遇到CPU模式下崩溃问题，
2.4.1不崩溃，
用其他推理底层也不崩溃。
就2.5.X崩溃，几个月了，也没有修复

**Comment by yjbdsky** [comment]
是啊，饶大佬修复一下啊，貌似飞浆好像有做任务给钱的活动，不知道还在搞没。

**Comment by vivienfanghuagood** [comment]
你好，麻烦下载最新的develop包测试一下是否会崩溃，我们在2.5之后修复了部分问题。
如果还能复现，麻烦上传一下运行的示例，我们复现一下，谢谢！

**Comment by raoyutian** [comment]
> 2.5.X版本问题很多的。我也遇到CPU模式下崩溃问题， 2.4.1不崩溃， 用其他推理底层也不崩溃。 就2.5.X崩溃，几个月了，也没有修复
2.6版本已经修复了。
