### ISSUE TITLE
generate  heatmap of attention weight when use simple_attention in seq2seq

### ISSUE THREAD

**Issue by gitforhf** [PaddlePaddle/Paddle#5885]
as  described in this issue  https://github.com/PaddlePaddle/Paddle/issues/1269
>attention weight的heap map如下图。该功能有现成的evaluator可以直接调用。
![image](https://user-images.githubusercontent.com/991417/33165709-6b7de4d0-cffd-11e7-9080-3558232df207.png)

This requirement has been supported, but no solution has been given。 
is there demo or tools to implement this feature。

**Comment by QiJune** [comment]
@luotao1 Could you please have a look at this?

**Comment by gitforhf** [comment]
有方案么？

**Comment by ranqiu92** [comment]
You can take the attention weight as the output layer, and use the inference interface to get the values. For this, you can refer to:
https://github.com/PaddlePaddle/models/blob/develop/conv_seq2seq/model.py#L420
https://github.com/PaddlePaddle/models/blob/develop/conv_seq2seq/infer.py#L173
Then some python package can be used to draw the heatmap.

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
