### ISSUE TITLE
cost 为0 是什么情况啊

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#5886]
Pass 0, Batch 0, Cost 2.849024, {'classification_error_evaluator': 1.0}

Pass 0, Batch 1, Cost 0.000000, {'classification_error_evaluator': 0.0}

Pass 0, Batch 2, Cost 0.000000, {'classification_error_evaluator': 0.0}

Pass 0, Batch 3, Cost 0.000000, {'classification_error_evaluator': 0.0}

Pass 0, Batch 4, Cost 0.000000, {'classification_error_evaluator': 0.0}

**Comment by yeyupiaoling** [comment]
你这是图片识别的问题吗
