### ISSUE TITLE
paddle训练模型时，A卡在使用GPU卡，而B卡没有使用GPU卡，但是前者的Memory-Usage的比后者要小

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#589]
paddle训练模型时，A卡在使用GPU卡，而B卡没有使用GPU卡，但是前者的Memory-Usage的比后者要小

![image](https://cloud.githubusercontent.com/assets/12882811/20585873/ab113f62-b239-11e6-83ad-318f10c02081.png)

**Comment by reyoung** [comment]
这台机器不一定是独占的，可能有别的进程在占用GPU。
