### ISSUE TITLE
使用AI Studio跑通 Stable-Diffusion 训练推理

### ISSUE THREAD

**Issue by shiofjsaio** [PaddlePaddle/Paddle#58922]
### 请提出你的问题 Please ask your question

<img width="1332" alt="截屏2023-11-11 11 11 47" src="https://github.com/PaddlePaddle/Paddle/assets/56310731/bccf59b9-5863-4252-bff0-24792f266e22">

**Comment by jerrywgz** [comment]
可以发下ppdiffusers的版本和训练启动方法吗

**Comment by zhangboSJTU** [comment]
@shiofjsaio 可以发下ppdiffusers的版本和训练启动方法吗
