### ISSUE TITLE
Current method for querying number of cpu sockets is not robust

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#5893]
Current implementation is:

https://github.com/PaddlePaddle/Paddle/blob/65c859db7aadfdaccb1a04afe788d66d0e4a8694/python/paddle/v2/__init__.py#L86

However, in some computers, output of above command is:
```Core(s) per socket:    6```
which will lead to exception
```ValueError: invalid literal for int() with base 10: ''```

**Comment by luotao1** [comment]
related with https://github.com/PaddlePaddle/Paddle/issues/5821#issuecomment-347164595
