### ISSUE TITLE
Error: Can not import paddle core while this file exists: ~/python3.8/site-packages/paddle/fluid/libpaddle.so

### ISSUE THREAD

**Issue by alittlenico** [PaddlePaddle/Paddle#58963]
### bug描述 Describe the Bug

paddlepaddle-gpu            2.5.1.post112 
使用官网提供的命令:python -m pip install paddlepaddle-gpu==2.5.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html。
环境:centos7 cuda11.4 python8 conda创建的虚拟环境 OpenSSL 3.0.9 30 May 2023 (Library: OpenSSL 3.0.9 30 May 2023
安装环境成功后
用下面代码验证报错:
import paddle
paddle.utils.run_check()。

### 其他补充信息 Additional Supplementary Information

虚拟环境下的所有包:
absl-py                     2.0.0
aiohttp                     3.8.6
aiosignal                   1.3.1
annotated-types             0.6.0
antlr4-python3-runtime      4.9.3
anyio                       3.7.1
astor                       0.8.1
asttokens                   2.4.1
async-timeout               4.0.3
attrs                       23.1.0
audioread                   3.0.1
Babel                       2.13.1
backcall                    0.2.0
bce-python-sdk              0.8.96
blinker                     1.7.0
bokeh                       3.1.1
boltons                     23.1.1
Bottleneck                  1.3.7
braceexpand                 0.1.7
certifi                     2023.7.22
cffi                        1.16.0
charset-normalizer          3.3.2
click                       8.1.7
colorama                    0.4.6
coloredlogs                 15.0.1
colorlog                    6.7.0
contourpy                   1.1.1
cycler                      0.12.1
Cython                      3.0.5
datasets                    2.14.6
decorator                   5.1.1
dill                        0.3.4
Distance                    0.1.3
editdistance                0.6.2
einops                      0.7.0
exceptiongroup              1.1.3
executing                   2.0.1
fastapi                     0.104.1
filelock                    3.13.1
Flask                       3.0.0
flask-babel                 4.0.0
flatbuffers                 23.5.26
fonttools                   4.44.0
frozenlist                  1.4.0
fsspec                      2023.10.0
ftfy                        6.1.1
future                      0.18.3
g2p-en                      2.1.0
g2pM                        0.1.2.5
h11                         0.14.0
h5py                        3.10.0
httpcore                    1.0.2
httpx                       0.25.1
huggingface-hub             0.19.0
humanfriendly               10.0
HyperPyYAML                 1.2.2
idna                        3.4
importlib-metadata          6.8.0
importlib-resources         6.1.1
inflect                     7.0.0
intervaltree                3.1.0
ipython                     8.12.3
itsdangerous                2.1.2
jedi                        0.19.1
jieba                       0.42.1
Jinja2                      3.1.2
joblib                      1.3.2
jsonlines                   4.0.0
kaldiio                     2.18.0
kiwisolver                  1.4.5
librosa                     0.8.1
llvmlite                    0.41.1
loguru                      0.7.2
lxml                        4.9.3
markdown-it-py              3.0.0
MarkupSafe                  2.1.3
matplotlib                  3.7.3
matplotlib-inline           0.1.6
mdurl                       0.1.2
mido                        1.3.0
mock                        5.1.0
mpmath                      1.3.0
multidict                   6.0.4
multiprocess                0.70.12.2
nara-wpe                    0.0.9
nltk                        3.8.1
note-seq                    0.0.3
numba                       0.58.1
numpy                       1.24.4
omegaconf                   2.3.0
onnx                        1.15.0
onnxruntime                 1.16.2
OpenCC                      1.1.7
opencc-python-reimplemented 0.1.7
opencv-python               4.8.1.78
opt-einsum                  3.3.0
packaging                   23.2
paddle-bfloat               0.1.7
paddle2onnx                 1.1.0
paddleaudio                 1.1.0
paddlefsl                   1.1.0
paddlenlp                   2.6.1
paddlepaddle-gpu            2.5.1.post112
paddlesde                   0.2.5
paddleslim                  2.4.1
paddlespeech                1.4.1
paddlespeech-feat           0.1.0
pandas                      2.0.3
parameterized               0.9.0
parso                       0.8.3
pathos                      0.2.8
pattern-singleton           1.2.0
pexpect                     4.8.0
pickleshare                 0.7.5
Pillow                      10.1.0
pip                         23.3.1
platformdirs                4.0.0
pooch                       1.8.0
portalocker                 2.8.2
pox                         0.3.3
ppdiffusers                 0.19.3
ppft                        1.7.6.7
praatio                     5.1.1
pretty-midi                 0.2.10
prettytable                 3.9.0
prompt-toolkit              3.0.40
protobuf                    3.20.2
psutil                      5.9.6
ptyprocess                  0.7.0
pure-eval                   0.2.2
pyarrow                     14.0.1
pybind11                    2.11.1
pycparser                   2.21
pycryptodome                3.19.0
pydantic                    2.4.2
pydantic_core               2.10.1
pydub                       0.25.1
Pygments                    2.16.1
pygtrie                     2.5.0
pyparsing                   3.1.1
pypinyin                    0.44.0
pypinyin-dict               0.6.0
pytest-runner               6.0.0
python-dateutil             2.8.2
pytz                        2023.3.post1
pyworld                     0.3.4
PyYAML                      6.0.1
pyzmq                       25.1.1
rarfile                     4.1
regex                       2023.10.3
requests                    2.31.0
requests-mock               1.11.0
resampy                     0.4.2
rich                        13.6.0
ruamel.yaml                 0.18.5
ruamel.yaml.clib            0.2.8
sacrebleu                   2.3.2
safetensors                 0.4.0
scikit-learn                1.3.2
scipy                       1.10.1
sentencepiece               0.1.99
seqeval                     1.2.2
setuptools                  68.2.2
six                         1.16.0
sniffio                     1.3.0
sortedcontainers            2.4.0
soundfile                   0.12.1
stack-data                  0.6.3
starlette                   0.27.0
swig                        4.1.1.post0
sympy                       1.12
tabulate                    0.9.0
TextGrid                    1.5
threadpoolctl               3.2.0
timer                       0.2.2
ToJyutping                  0.2.3
tornado                     6.3.3
tqdm                        4.66.1
traitlets                   5.13.0
trampoline                  0.1.2
typeguard                   2.13.3
typer                       0.9.0
typing_extensions           4.8.0
tzdata                      2023.3
urllib3                     1.26.18
uvicorn                     0.24.0.post1
visualdl                    2.5.3
wcwidth                     0.2.9
webrtcvad                   2.0.10
websockets                  12.0
Werkzeug                    3.0.1
wheel                       0.41.3
xxhash                      3.4.1
xyzservices                 2023.10.1
yacs                        0.1.8
yarl                        1.9.2
zhon                        2.0.2
zipp                        3.17.0

**Comment by lyuwenyu** [comment]
报错信息呢

**Comment by alittlenico** [comment]
> 报错信息呢

完整报错如下:

>>> import paddle
Error: Can not import paddle core while this file exists: /home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/home/inspur/ly416100210179/miniconda3/envs/paddlepaddle/lib/python3.8/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory

**Comment by lyuwenyu** [comment]
libssl.so.1.1 搜一下你机器里有没有 这个库。

**Comment by alittlenico** [comment]
> libssl.so.1.1 搜一下你机器里有没有 这个库。

用locate libssl.so.1.1
显示：
/home/software/inteloneapi/2022.2/intelpython/python3.9/envs/2022.1.0/lib/libssl.so.1.1
/home/software/inteloneapi/2022.2/intelpython/python3.9/lib/libssl.so.1.1
/home/software/inteloneapi/2022.2/intelpython/python3.9/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.so.1.1
/home/software/inteloneapi/2022.2/vtune/2022.2.0/lib64/libssl.so.1.1
 这应该代表我本地机器是有这个库的吧

**Comment by danny-zhu** [comment]
> > libssl.so.1.1 搜一下你机器里有没有 这个库。
> 
> 用locate libssl.so.1.1 显示： /home/software/inteloneapi/2022.2/intelpython/python3.9/envs/2022.1.0/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/intelpython/python3.9/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/intelpython/python3.9/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/vtune/2022.2.0/lib64/libssl.so.1.1 这应该代表我本地机器是有这个库的吧

libssl.so.1.1在python3.9目录下，但你的报错提示在python3.8目录下找不到这个动态链接库

**Comment by alittlenico** [comment]
> > > libssl.so.1.1 搜一下你机器里有没有 这个库。
> > 
> > 
> > 用locate libssl.so.1.1 显示： /home/software/inteloneapi/2022.2/intelpython/python3.9/envs/2022.1.0/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/intelpython/python3.9/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/intelpython/python3.9/pkgs/openssl-1.1.1n-h7f8727e_0/lib/libssl.so.1.1 /home/software/inteloneapi/2022.2/vtune/2022.2.0/lib64/libssl.so.1.1 这应该代表我本地机器是有这个库的吧
> 
> libssl.so.1.1在python3.9目录下，但你的报错提示在python3.8目录下找不到这个动态链接库

感谢，这个已经解决。原因是使用的服务器分配的个人账号，服务器安装的openssl 但我的个人环境找不到openssl所依赖的一些库。1.个人环境重新安装openssl 或者2.把所有相关依赖动态链接库 cp到自己的usr/lib目录下。
