### ISSUE TITLE
请问如何在ai studio上申请开发票？

### ISSUE THREAD

**Issue by ruanzupan** [PaddlePaddle/Paddle#58968]
### 请提出你的问题 Please ask your question

请问如何在ai studio上申请开发票？开通了会员，想充值A币

**Comment by zhiboniu** [comment]
可以按如下方式联系官方试试，这里主要解决技术问题
![image](https://github.com/PaddlePaddle/Paddle/assets/31800336/41b0fd76-4fd0-4802-b1c5-0f754d856631)

**Comment by ruanzupan** [comment]
亲  - -  我要么就是在晒月亮，要么就是在淋太阳，要么就是在抽人，你要来不？

**Comment by ruanzupan** [comment]
😂 我就是根据截图的方式联系不上官方，发邮件也没回复，加QQ群也没回应。




帅神
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月14日(星期二) 上午10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] 请问如何在ai studio上申请开发票？ (Issue #58968)





 
可以按如下方式联系官方试试，这里主要解决技术问题
