### ISSUE TITLE
The generated documents have more blank lines which maybe be loose and break the original sections

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#5896]
### original:
![image](https://user-images.githubusercontent.com/10721757/33202838-ea5d7da6-d138-11e7-8d37-f0c0341d1d79.png)
### generated:
![image](https://user-images.githubusercontent.com/10721757/33203047-b9ce999e-d139-11e7-8581-7269a9691736.png)

### In contrast with caffe2:
![image](https://user-images.githubusercontent.com/10721757/33202891-144a3e60-d139-11e7-90a3-4502d118633b.png)

### And tensorflow:
![image](https://user-images.githubusercontent.com/10721757/33202914-28d4972c-d139-11e7-9f75-d2b8122786d8.png)

**Comment by shanyi15** [comment]
@jetfuel may it be resulted from HTML rendering?

**Comment by jetfuel** [comment]
@shanyi15 The line space is controlled by the CSS. And we have control over it. 
But the page looks fine now. I don't see any extra space. 
![screen shot 2018-02-07 at 10 41 33 am](https://user-images.githubusercontent.com/1093725/35934934-c90e6dae-0bf3-11e8-8bf1-fdc0dc6a3b91.png)

**Comment by shanyi15** [comment]
@jetfuel I agree with you. Close due to the page looks fine now.
