### ISSUE TITLE
paddle集群训练出错

### ISSUE THREAD

**Issue by dsisds** [PaddlePaddle/Paddle#590]
![1d9b99b7c4c5b8d89db77bfcb320672d](https://cloud.githubusercontent.com/assets/5534548/20588378/837c073c-b24f-11e6-8dc4-f133a69985e9.JPG)

![image](https://cloud.githubusercontent.com/assets/5534548/20588416/e204b074-b24f-11e6-807c-c58bc37248da.png)

![image](https://cloud.githubusercontent.com/assets/5534548/20588430/06c4e73a-b250-11e6-9b9b-defa927cebca.png)

**Comment by luotao1** [comment]
建议贴文字，截图太小了

**Comment by dsisds** [comment]
paddle_trainer.INFO
I1123 20:10:58.082078 15425 TrainerInternal.cpp:162] Batch=69 samples=8832 AvgCost=7.9748 CurrentCost=7.35378 Eval: classification_error_evaluator=0.992867 CurrentEval: classification_error_evaluator=0.984375 
I1123 20:11:18.766109 15425 TrainerInternal.cpp:162] Batch=70 samples=8960 AvgCost=7.96583 CurrentCost=7.34721 Eval: classification_error_evaluator=0.992634 CurrentEval: classification_error_evaluator=0.976562 
I1123 20:11:33.331632 15425 TrainerInternal.cpp:162] Batch=71 samples=9088 AvgCost=7.95688 CurrentCost=7.3304 Eval: classification_error_evaluator=0.992628 CurrentEval: classification_error_evaluator=0.992188 
I1123 20:11:53.630290 15425 TrainerInternal.cpp:162] Batch=72 samples=9216 AvgCost=7.9482 CurrentCost=7.33159 Eval: classification_error_evaluator=0.992405 CurrentEval: classification_error_evaluator=0.976562 
I1123 20:12:10.635258 15425 TrainerInternal.cpp:162] Batch=73 samples=9344 AvgCost=7.94028 CurrentCost=7.37031 Eval: classification_error_evaluator=0.992295 CurrentEval: classification_error_evaluator=0.984375 
F1123 20:12:21.628942 16976 SocketChannel.cpp:90] 00011 failed: len > 0 peer=10.88.157.15 20:12:0 628940 4 iovs[curIov].base=Fx7f66758c8be016974 SocketChannel.cpp11:2390] 20:12:21.628943 Check failed: len > 0 SocketChannel.cpp:10.88.151.16] curIov=0 iovCnt=4 iovs[curIov].base=Check failed: len > 0 peer=10.88.157.17 curIov=0 iovCnt=0x7f6677ffebe00x5 iovs[curIov].base=160x7f664fffebe0 iovs[curIov].iov_len=16: Broken pipe [32]:F1123 20:12:21.628937 16972 SocketChannel.cpp:90] Check failed: len > 0 peer=10.88.157.21 curIov=0 iovCnt=4 iovs[curIov].base=0x7f667d8c8be0 iovs[curIov].iov_len=16: Broken pipe [32] 
F1123 20:12:21.628942 16976 SocketChannel.cpp:90] 00011 failed: len > 0 peer=10.88.157.15 20:12:0 628940 4 iovs[curIov].base=Fx7f66758c8be016974 SocketChannel.cpp11:2390] 20:12:21.628943 Check failed: len > 0 SocketChannel.cpp:10.88.151.16] curIov=0 iovCnt=4 iovs[curIov].base=Check failed: len > 0 peer=10.88.157.17 curIov=0 iovCnt=0x7f6677ffebe00x5 iovs[curIov].base=160x7f664fffebe0 iovs[curIov].iov_len=16: Broken pipe [32]: Broken pipe [3232] 

F1123 20:12:21.628942 16976 SocketChannel.cpp:90] 00011 failed: len > 0 peer=10.88.157.15 20:12:0 628940 4 iovs[curIov].base=Fx7f66758c8be016974 SocketChannel.cpp11:2390] 20:12:21.628943 Check failed: len > 0 SocketChannel.cpp:10.88.151.16] curIov=0 iovCnt=4 iovs[curIov].base=Check failed: len > 0 peer=10.88.157.17 curIov=0 iovCnt=0x7f6677ffebe00x5 iovs[curIov].base=160x7f664fffebe0 iovs[curIov].iov_len=16: Broken pipe [32]: Broken pipe [3232] 


paddle_pserver2.INFO 
Log file created at: 2016/11/23 19:43:16 
Running on machine: yq01-idl-gpu-offline71.yq01.baidu.com 
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg 
I1123 19:43:16.041484 13255 Util.cpp:144] commandline: ./paddle_pserver2 --num_gradient_servers=4 --nics=xgbe0 --port=7164 --ports_num=1 --rdma_tcp=tcp --comment=_ 
I1123 19:43:19.045251 13255 Util.cpp:113] Calling runInitFunctions 
I1123 19:43:19.045738 13255 Util.cpp:126] Call runInitFunctions done. 
I1123 19:43:19.045904 13255 ParameterServer2Main.cpp:66] pserver started : xgbe0:7164 
I1123 19:43:19.046013 13599 LightNetwork.cpp:260] tcp server start 
I1123 19:47:33.965085 16956 LightNetwork.cpp:313] worker started, peer = 10.88.157.21 
I1123 19:48:01.493947 18291 LightNetwork.cpp:313] worker started, peer = 10.88.157.17 
I1123 19:48:19.306054 18692 LightNetwork.cpp:313] worker started, peer = 10.88.157.15 
I1123 19:54:23.560678 30339 LightNetwork.cpp:313] worker started, peer = 10.88.151.16 
I1123 19:54:25.772490 30339 ParameterServer2.cpp:255] pserver: setParameter 
I1123 19:54:25.772617 30339 ParameterServer2.cpp:292] pserver: new cpuvector: size=18481152 
I1123 19:54:26.304822 30356 LightNetwork.cpp:313] worker started, peer = 10.88.151.16 
I1123 19:54:26.369545 18692 ParameterServer2.cpp:679] pserver: getParameter 
I1123 19:54:26.565417 18291 ParameterServer2.cpp:679] pserver: getParameter 
I1123 19:54:27.037071 16956 ParameterServer2.cpp:679] pserver: getParameter 
I1123 19:54:42.359331 30339 BarrierStat.cpp:63] create barrierEndStat: SLOW_NODES_denseUpdater endBarrier warning rate: 0.35 
F1123 20:12:19.122027 30356 SocketChannel.cpp:47] Check failed: len >= 0 peer=10.88.151.16: Connection reset by peer [104] 
F1123 20:12:19.121994 30339 SocketChannel.cpp:90] Check failed: len > 0 peer=10.88.151.16 curIov=4 iovCnt=5 iovs[curIov].base=0x2159d1f42 iovs[curIov].iov_len=188606: 


train.log
./train.sh: line 215: 26192 Killed PYTHONPATH=./paddle:$PYTHONPATH GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_trainer --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --trainer_id=${OMPI_COMM_WORLD_RANK} --pservers=$ipstring --rdma_tcp=${rdma_tcp} --nics=${nics} ${train_arg} --config=conf/trainer_config.conf --save_dir=./${save_dir} ${extern_arg} 
+ '[' 137 -ne 0 ']' 
+ kill_pserver2_exit 
+ ps aux 
+ grep paddle_pserver2 
+ grep _ 
+ grep -v grep 
+ cut -c10-14 
+ xargs kill -9 
+ log_fatal 'paddle_trainer failed kill paddle_pserver2 and exit' 
+ echo '[./common.sh : 399] [kill_pserver2_exit]' 
[./common.sh : 399] [kill_pserver2_exit] 
+ echo '[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit' 
[FATAL]: paddle_trainer failed kill paddle_pserver2 and exit 
+ get_stack 
+ set +x 

*********************Shell Script Stack Trace******************** 
@: [./log.sh: 41] log_fatal 
@: [./common.sh: 399] kill_pserver2_exit 
@: [./train.sh: 218] main 

+ exit 1 
------------------------------------------------------- 
Primary job terminated normally, but 1 process returned 
a non-zero exit code.. Per user-direction, the job has been aborted. 
------------------------------------------------------- 
Current Layer forward/backward stack is 
Current Layer forward/backward stack is 
*** Aborted at 1479903139 (unix time) try "date -d @1479903139" if you are using GNU date *** 
*** Aborted at 1479903139 (unix time) try "date -d @1479903139" if you are using GNU date *** 
Current Layer forward/backward stack is 
PC: @ 0x62e0d2 paddle::ProtoClient::recv() 
Current Layer forward/backward stack is

**Comment by backyes** [comment]
@dsisds 
方便用paddle原生代码跑一次么？

**Comment by dsisds** [comment]
@backyes 用的就是paddle原生代码，只是代码不是最新的。我用的svn上的paddle跑的。
我现在跑通了，把test去掉就没有问题了。
