### ISSUE TITLE
backgrad for rms_norm

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#59092]
### 需求描述 Feature Description

请问下`rms_norm`这个算子，是没有CPU的实现吗？并且也没有反向的实现？
我翻了代码，只找到了`paddle/phi/kernels/gpu/rms_norm_kernel.cu`这里有一个GPU的前向实现。

背景是：实现XPU下面的`rms_norm`及其反向`rms_norm_grad`，需要前向和反向的CPU算子。
前向的CPU算子我或许可以抄GPU的前向，写出来一个“能算对但是很慢”的版本。
反向的话我感觉是要“从头加新算子”？我之前只操作过“给现有算子增加不同device实现”，全新算子这个还真不会，如果有文档或者指导的话也行啊。

**Comment by cxxly** [comment]
rms_norm 目前确实比较特殊，不太规范。 
目前现状：1）Paddle主框架只有一个前向，签名也不太规范 2）上层套件通过自定义算子也单独实现了一套
<img width="1158" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/8372068/2983e631-0b65-43cf-8b4d-a5be28149bb0">

如果只是使用，可以参考paddlenlp的实现；如果自己想动手为paddle主框架新增rmsnorm，参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/dev_guides/api_contributing_guides/api_contributing_guides_cn.html
