### ISSUE TITLE
paddle的预测API 在遇到什么样的数据时会失败？

### ISSUE THREAD

**Issue by buptzzl** [PaddlePaddle/Paddle#591]
调用paddle 原来的预测API，对样本进行批量预测时，有约1+%的用户是没有分数的。
具体调用的代码：
_m_predictor = new paddle_platform::SparseFloatValuePredictor();
.....  【省略环境准备代码】
paddle_platform::SUCCESS != _m_predictor->eval(_my_ins, 1, _my_results)

预测API 在遇到什么样的数据时会导致失败？

**Comment by backyes** [comment]
@buptzzl 

paddle_platform 这个namespace是你们自己封装的么？ 另外， 你的问题包含的信息太少，而且有点混淆，比如什么是```原来的预测api```。

@reyoung 看看能不能帮到他。

**Comment by reyoung** [comment]
1、这个api已经被废弃了。代码也全公开，所以debug可以自己看看。
2、这个数据合法性检测，可以自己先讲没有分数的样本找出来，看看是不是数据就不合法？

**Comment by backyes** [comment]
> 1、这个api已经被废弃了。代码也全公开，所以debug可以自己看看。

替代方案中，除了py_paddle 还有其他可选么？ @buptzzl py_paddle 是否能满足你的需求？
