### ISSUE TITLE
paddlehub.module.manager.EnvironmentMismatchError: Pneumonia_CT_LKM_PP-1.0.0 cannot be installed because some 

### ISSUE THREAD

**Issue by showfilv** [PaddlePaddle/Paddle#59114]
### 请提出你的问题 Please ask your question

paddlehub.module.manager.EnvironmentMismatchError: Pneumonia_CT_LKM_PP-1.0.0 cannot be installed because some conditions are not met:
+-------------------+----------+-----------------------------------+-----------------------------------+
|       Name        | Version  |   PaddlePaddle Version Required   |    PaddleHub Version Required     |
+-------------------+----------+-----------------------------------+-----------------------------------+
|Pneumonia_CT_LKM_PP|  1.0.0   |         <=2.1.0(Mismatch)         |         <=2.2.0(Mismatch)         |
+-------------------+----------+-----------------------------------+-----------------------------------+
上面是报错信息 
下面是包版本
packaging                    23.1
paddle                       1.0.2
paddle2onnx                  0.8.1
paddlefsl                    1.1.0
paddlehub                    1.6.2
paddlenlp                    2.6.1
paddlepaddle                 2.5.2
pandas                       2.1.2

求解为什么会报这样的错误呢？

**Comment by cxxly** [comment]
看报错信息，应该是版本不匹配，Paddle版本需要小于2.1。另外PaddleHub已不再维护，建议使用PaddleX，支持的模型库列表参考 https://aistudio.baidu.com/intro/paddlex/models
