### ISSUE TITLE
【Hackathon 5 No.64】待支持动转静模型列表文档

### ISSUE THREAD

**Issue by Fancy-hjyp** [PaddlePaddle/Paddle#59113]
# 待支持动转静模型列表文档

## PaddleSeg

因为不同文件夹下的`model`共用一个`train`逻辑，所以按照文件夹进行了统计。

| 模型名  | 文件路径 | 状态 |
| :-----: | :--: | :--: |
| AutoNUE |  contrib/AutoNUE/   | 待支持  |
| CityscapesSOTA  |  contrib/CityscapesSOTA/   |  待支持  |
| CrossPseudoSupervision | contrib/CrossPseudoSupervision/ |  待支持 |
| DomainAdaptation | contrib/DomainAdaptation/ | 待支持  |
| LaneSeg | contrib/LaneSeg/ |  待支持  |
| PanopticDeepLab | contrib/PanopticDeepLab/ | 待支持 |
| Matting | Matting/ | 待支持  |
| medicalseg | contrib/MedicalSeg/medicalseg/ | ✅ |
| PanopticSeg | contrib/PanopticSeg/ |  ✅ |
| QualityInspector | contrib/QualityInspector/ | ✅ |
| RSSegBenchmark | contrib/RSSegBenchmark/ | ✅ |
| paddleseg | paddleseg/ | ✅ |
| PP-HumanSeg | contrib/PP-HumanSeg/ | 没有找到训练代码 |
| SegmentAnything | contrib/SegmentAnything/ | 没有找到训练代码 |

**Comment by Tomoko-hjf** [comment]
@shiyutang 您好，请问赛题64 PaddleSeg套件这样整理可以吗

**Comment by 2742195759** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/16025309/f7b3f43d-0571-43e9-b44d-a9d1b0d91151)
可以看下configs这个文件夹下面，是全量的所有模型，然后每个对应的模型都可以通过在官网中查找对应的执行命令来获取（大概就是 train.py  + --config config名）。如下图：
<img width="1066" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16025309/1db4534f-7a14-40b1-b0e2-9edc1f415500">
通过这个方式可以得到所有的可以执行的动转静配置（一个配置就是一个yaml）然后分别对他们尝试开启动转静测试一下就可以得到没有支持的列表了。其他的套件也是类似的。有问题可以随时在这里提问哈。
