### ISSUE TITLE
AttributeError: module 'paddle.fluid.layers' has no attribute 'l2_normalize'

### ISSUE THREAD

**Issue by repenbaa** [PaddlePaddle/Paddle#59128]
### bug描述 Describe the Bug

描述: 
paddle2.5.2不存在paddle.fluid.layers.l2_normalize與paddle.fluid.layers.nn.l2_normalize函數

程式區塊: 
norm_feature = paddle.fluid.layers.l2_normalize(total_feature, axis=1)
norm_weight = paddle.fluid.layers.l2_normalize(weight, axis=0)

'''
Traceback (most recent call last):
  File "tools/train.py", line 35, in <module>
    train(args)
  File "E:\project\insightface-master\recognition\arcface_paddle\static\train.py", line 107, in train
    train_model = StaticModel(
  File "E:\project\insightface-master\recognition\arcface_paddle\static\static_model.py", line 86, in __init__
    self.classifier = eval("classifiers.{}".format(
  File "E:\project\insightface-master\recognition\arcface_paddle\static\classifiers\lsc.py", line 110, in __init__
    norm_feature = paddle.fluid.layers.l2_normalize(total_feature, axis=1)
AttributeError: module 'paddle.fluid.layers' has no attribute 'l2_normalize'
'''

### 其他补充信息 Additional Supplementary Information

依照官方要求確定各版本對應並下載與完成的事項: 
cuda=11.7
cudnn=8.9.6 for cuda 11.x
v11.7/bin/cublas64_12.dll(copy)->cublas64_11.dll
v11.7/bin/cudnn_ops_infer64_8.dll(add)
v11.7/include/cudn.h(add)
v11.7/lib/x64/cudnn.lib(add)
查詢: 
cmd 'pip debug' -(show)-> cp38-cp38-win_amd64, cp38-abi3-win_amd64, cp38-none-win_amd64, ... 確定我使用的電腦所支援的版本為cp38-cp38-win_amd
BUG: 
下載了paddlepaddle_gpu-2.5.2.post120-cp38-cp38-win_amd64.whl 與 paddlepaddle_gpu-2.5.2.post117-cp38-cp38-win_amd64.whl。嘗試使用兩個新的版本都出現了相同問題, 如下: 'paddle.fluid.layers' has no attribute 'l2_normalize'。
後來決定下載符合我使用open sourse年代的版本: paddlepaddle_gpu-2.2.0rc0.post112-cp38-cp38-win_amd64.whl, 則會出現多數套件版本過新而無法使用的問題。如: numpy==1.24, paddle需要 <1.18等等。
除了新版paddle**不存在paddle.fluid.layers.l2_normalize外也不存在paddle.fluid.layers.nn.l2_normalize**
最後:
查詢類似問題主要是使用了新版paddle.fluid.layers所沒有的存在於舊版的函數導致, 請問除了降版本之外有沒有此函數對應的新版paddle函數 ［l2_normalize］或者在不改動源碼前提下的解決辦法。煩請幫忙，感謝各位!

**Comment by 2742195759** [comment]
在2.5.2之后进行了fluid api的退场工作，上面的python 借口已经废弃不用了，建议使用最新的接口：functional.normalize ： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/normalize_cn.html#normalize

**Comment by repenbaa** [comment]
> 在2.5.2之后进行了fluid api的退场工作，上面的python 借口已经废弃不用了，建议使用最新的接口：functional.normalize ： https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/normalize_cn.html#normalize

有用, 謝謝你。
