### ISSUE TITLE
Paddle.arange()结果报错

### ISSUE THREAD

**Issue by 54wb** [PaddlePaddle/Paddle#59131]
### bug描述 Describe the Bug

hi~,我使用paddlepaddle-gpu 2.3.2时，遇到paddle.arange()这个函数，总是输出为0，但是这个函数正常应该是序列数据

out = paddle.arange(3)
out变成为Tensor(shape=[3], dtype=int64, place=Place(gpu:0), stop_gradient=True, [0, 0, 0])

使用的paddle版本是paddlepaddle-gpu          2.3.2                    pypi_0    pypi

**Comment by 2742195759** [comment]
我在最新的Paddle版本是OK的，请问是否可以升级一下Paddle版本，这个问题估计已经被修复了。
![image](https://github.com/PaddlePaddle/Paddle/assets/16025309/78ed0a6f-0742-4147-b4af-77c852e1b33c)
