### ISSUE TITLE
accumulation_node.cc每次都用临时变量替换掉参数梯度的地址，导致optimizer.clear_grad()后每个迭代的梯度空间没有重用。

### ISSUE THREAD

**Issue by JiruWang** [PaddlePaddle/Paddle#59207]
下面的代码中，t是临时变量，param的梯度tensor浅拷贝这个变量，device上的grad地址也变成临时变量。
https://github.com/PaddlePaddle/Paddle/blob/164c63f517ad74d789f0a0aae6e3bc00764289aa/paddle/fluid/eager/accumulation/accumulation_node.cc#L36C9-L36C9
clear_grad(set_to_zero=true)的语义是，当前迭代，grad置0，下一次重用这块内存，与当前框架实现不符，请问是否有计划优化这部分实现？

**Comment by wanghuancoder** [comment]
> 下面的代码中，t是临时变量，param的梯度tensor浅拷贝这个变量，device上的grad地址也变成临时变量。 https://github.com/PaddlePaddle/Paddle/blob/164c63f517ad74d789f0a0aae6e3bc00764289aa/paddle/fluid/eager/accumulation/accumulation_node.cc#L36C9-L36C9 clear_grad(set_to_zero=true)的语义是，当前迭代，grad置0，下一次重用这块内存，与当前框架实现不符，请问是否有计划优化这部分实现？

感谢提问。这是个很有深度的问题！这个SetFakeEmpty是后期加的一个特殊优化。优化的思路是：如果目前Tensor里的数据是0，没必要做一次梯度累加，因为在参数很大的时候，一次加法也会消耗不少CPU，因此直接用反向梯度覆盖现有的0，从数学上是没有错的。当然，这个确实没有复用原有显存。如果你明确期望复用原有显存，在clear之后，可以调用Tensor._unset_fake_empty()，则不会做fake动作了。

**Comment by JiruWang** [comment]
感谢您的回答，还有一个问题，clear_grad默认参数是set_to_zero=true，在没有复用原有显存的基础上，这块显存仍然被set为0，这个操作似乎时多余的。
