### ISSUE TITLE
pr_58560 caused the inference time of swin_transformer model is about 15 times longer than that of setting disable_mkldnn()

### ISSUE THREAD

**Issue by EmmonsCurse** [PaddlePaddle/Paddle#59252]
### bug描述 Describe the Bug

Error Description： After the merge of https://github.com/PaddlePaddle/Paddle/pull/58560 which make OneDNN default on paddle, the inference time of swin_transformer model is about 15 times longer than that of setting disable_mkldnn().
- Inference time: 61.4823 s
- Inference time (**disable_mkldnn**): 3.9201 s

#### 1. Operating environment
- PaddlePaddle version: develop
- OS version: CentOS
- Python version: 3.8
- CPU info: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz

#### 2. The problem recurrence steps
- Install paddlepaddle_whl and Install dependency package
- run test_swin_transformer.py(compare whether to set config.disable_mkldnn() )

> test_swin_transformer.py
```python
import os
import sys
import tarfile
import time
import wget
import numpy as np
import paddle

from paddle.inference import Config
from paddle.inference import PrecisionType
from paddle.inference import create_predictor


def check_model_exist():
    """
    check model exist
    """
    swin_transformer_url = "https://paddle-qa.bj.bcebos.com/inference_model_clipped/latest/class/swin_transformer.tgz"
    if not os.path.exists("./swin_transformer/inference.pdiparams"):
        wget.download(swin_transformer_url, out="./")
        tar = tarfile.open("swin_transformer.tgz")
        tar.extractall()
        tar.close()


def enable_mkldnn_test(input_data_dict, model_file, params_file):
    """
    Args:
        input_data_dict (dict)
        model_file (str)
        params_file (str)

    Returns:
        time_cost(float)
    """
    config = Config()
    config.set_prog_file(model_file)
    config.set_params_file(params_file)
    # config.disable_mkldnn()

    predictor = create_predictor(config)

    start_time = time.time()

    input_names = predictor.get_input_names()
    for i, input_data_name in enumerate(input_names):
        input_handle = predictor.get_input_handle(input_data_name)
        input_handle.copy_from_cpu(input_data_dict[input_data_name])

    predictor.run()

    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu()
    end_time = time.time()
    time_cost = end_time - start_time
    return time_cost


if __name__ == "__main__":
    check_model_exist()

    model_file="./swin_transformer/inference.pdmodel"
    params_file="./swin_transformer/inference.pdiparams"

    fake_input = np.random.randn(1, 3, 384, 384).astype("float32")
    input_data_dict = {"x": fake_input}
    time_cost = enable_mkldnn_test(input_data_dict, model_file, params_file)
    print(f"Inference time: {time_cost:.4f} s")
```

### 其他补充信息 Additional Supplementary Information

@zhanglirong1999 @xinyu-intel Is this problem reasonable？If not, can you help me solve this?

**Comment by zhanglirong1999** [comment]
@EmmonsCurse Thank you for report the problem, we will check as soon as possible

**Comment by EmmonsCurse** [comment]
@zhanglirong1999 @LLee233 Thank you for your reply and problem-fixing PR, the following information needs to be synchronized. 

Firstly, after merging #59394, the average inference time of swin_transformer is as follows:
enable_mkldnn: 6.4666 seconds
disable_mkldnn: 3.7087 seconds

Secondly after merging #59421, the average inference time of swin_transformer is as follows:
enable_mkldnn: 3.8187 seconds
disable_mkldnn: 3.9630 seconds

As we can see, the inference time of the model is greatly reduced after the two problem-fixing PR merging when setting enable_mkldnn().

But a new problem is introduced, after merging #59421 the inference **'output_data'** of this model is all **nan** when setting enable_mkldnn_int8(). 

<img width="985" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/49938469/dc56b368-3052-47e7-ae49-4253ac1ed563">


@LLee233 You can recurrence the problem by setting enable_mkldnn_int8() like bellow:

```
def enable_mkldnn_test(input_data_dict, model_file, params_file):
    """
    Args:
        input_data_dict (dict)
        model_file (str)
        params_file (str)

    Returns:
        time_cost(float)
    """
    config = Config()
    config.set_prog_file(model_file)
    config.set_params_file(params_file)
    # config.disable_mkldnn()
    config.enable_mkldnn_int8()

    predictor = create_predictor(config)

    start_time = time.time()

    input_names = predictor.get_input_names()
    for i, input_data_name in enumerate(input_names):
        input_handle = predictor.get_input_handle(input_data_name)
        input_handle.copy_from_cpu(input_data_dict[input_data_name])

    predictor.run()

    output_names = predictor.get_output_names()
    output_handle = predictor.get_output_handle(output_names[0])
    output_data = output_handle.copy_to_cpu()
    print("output_data:", output_data)
    end_time = time.time()
    time_cost = end_time - start_time
    return time_cost
```

@xinyu-intel @vivienfanghuagood Is this problem reasonable？

**Comment by LLee233** [comment]
@EmmonsCurse Thanks for your report, I will investigate it as soon as possible.

**Comment by LLee233** [comment]
> @EmmonsCurse Thanks for your report, I will investigate it as soon as possible.

Hi @EmmonsCurse, new PR is created https://github.com/PaddlePaddle/Paddle/pull/59663, and you may check if it works, thanks~

**Comment by EmmonsCurse** [comment]
> Hi @EmmonsCurse, new PR is created #59663, and you may check if it works, thanks~
@LLee233 OK，thanks ~
