### ISSUE TITLE
win10 Build DEV版本遇到错误 HEAD is now at 9dcc26c5 Prepare for Crypto++ 8.2 release Make ConstBytePtr return non-NULL pointer

### ISSUE THREAD

**Issue by raoyutian** [PaddlePaddle/Paddle#59299]
### 问题描述 Issue Description

编译环境：
win10 ，vs2017，
 
HEAD is now at 9dcc26c5 Prepare for Crypto++ 8.2 release Make ConstBytePtr return non-NULL pointer
![1700727947354(1)](https://github.com/PaddlePaddle/Paddle/assets/72854228/e03ed36d-2175-46af-b82c-ba90acdad5ed)

### 版本&环境信息 Version & Environment Information

编译环境：
win10 ，vs2017，
 
HEAD is now at 9dcc26c5 Prepare for Crypto++ 8.2 release Make ConstBytePtr return non-NULL pointer

**Comment by xuxinyi389** [comment]
HEAD is now at 9dcc26c5 Prepare for Crypto++ 8.2 release Make ConstBytePtr return non-NULL pointer 是正常输出信息，ninja是一个高度集成的工具，可以看看log中有无failed或者error，然后使用ninja  <object（替换为失败得对象名）> -v展示更详细的执行命令和报错信息。

**Comment by raoyutian** [comment]
同样的方式编译2.4.1就没有问题。

**Comment by raoyutian** [comment]
自从2.5.1版本包括目前开发版，windows下再也没有编译成功过。

**Comment by xuxinyi389** [comment]
您好，内部相关版本在正常编译、测试、发版。您可以提供更详细的报错信息从而获得帮助

**Comment by raoyutian** [comment]
> 您好，内部相关版本在正常编译、测试、发版。您可以提供更详细的报错信息从而获得帮助
您好，能不能提供第三方的所有已经下载好的文件？发我一份给我raoyutian001@163.com
我发现编译失败根本原因是第三方无法下载。

**Comment by xuxinyi389** [comment]
> > 您好，内部相关版本在正常编译、测试、发版。您可以提供更详细的报错信息从而获得帮助
> > 您好，能不能提供第三方的所有已经下载好的文件？发我一份给我[raoyutian001@163.com](mailto:raoyutian001@163.com)
> > 我发现编译失败根本原因是第三方无法下载。

第三方库好像经常有变动，你可以通过设置代理的方式从而正确地获取代码

**Comment by raoyutian** [comment]
编译不过是网络问题，无法下载第三方库导致。
关闭吧。
