### ISSUE TITLE
Paddle cuda镜像运行后，运行时发现找不到gpu

### ISSUE THREAD

**Issue by atalia** [PaddlePaddle/Paddle#59324]
### 请提出你的问题 Please ask your question

运行镜像
<img width="1081" alt="企业微信截图_ba68a2c8-099d-41fb-8199-78f4c914dee3" src="https://github.com/PaddlePaddle/Paddle/assets/15249755/36ca2255-e94e-44eb-942c-dc12394bee28">
在容器内，执行这个nvcc -V是可以查到cuda版本信息的
λ fb7b21dca1e3 /paddle/examples/tiny/asr1 nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

且可以正常查询到gpu版本信息
<img width="905" alt="企业微信截图_372368d8-b9a5-4d93-af45-f9b87ff8fc45" src="https://github.com/PaddlePaddle/Paddle/assets/15249755/53641700-2f53-415b-ad4a-2897f4050876">

但是框架启动时，还是会报错
![Uploading 企业微信截图_cbc0a87c-67bc-4f4e-a7ca-b3453f18b6d7.png…]()

**Comment by atalia** [comment]
<img width="1358" alt="企业微信截图_cbc0a87c-67bc-4f4e-a7ca-b3453f18b6d7" src="https://github.com/PaddlePaddle/Paddle/assets/15249755/097ab5cc-7488-4b5b-88f9-2b3b8d1ba830">

**Comment by haohongxiang** [comment]
请先参考官网教程提供的解决方法 [paddlepaddle-error-no-cuda-capable-device-is-detected](https://www.paddlepaddle.org.cn/documentation/docs/zh/faq/install_cn.html#paddlepaddle-error-no-cuda-capable-device-is-detected)
