### ISSUE TITLE
第五期黑客松 NO. 101 fused_multi_transformer算子迁移问题

### ISSUE THREAD

**Issue by zeroRains** [PaddlePaddle/Paddle#59362]
### 请提出你的问题 Please ask your question

在迁移`fused_multi_transformer`算子时，`fused_multi_transformer_kernel.cu.h`中这个部分涉及的依赖太复杂了，想询问一下迁移建议

![image](https://github.com/PaddlePaddle/Paddle/assets/57100978/f489d0b3-f451-4e30-8268-0b8eb173c1c0)

**Comment by yuanlehome** [comment]
同学你好，这个算子的迁移之前在黑客松上发布出来，目前由于一些迁移难度、历史局限性以及内部一些原因哈，我们不建议对这个算子进行迁移了。感谢理解🙏

**Comment by zeroRains** [comment]
好的
