### ISSUE TITLE
问一个关于训练结果应用的问题

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#5938]
您好。如果我通过PADDLEPADDLE进行训练。训练出了一个很不错的参数表。
然后我想把这个参数表应用在我android平台的C++程序上。我该怎么做呢？
我是否需要在ANDROID上也搭建一个类似PADDLE的开发环境出来。感觉这么做有点太重了。

背景介绍：
我平时使用COCOS2DX开发C++游戏。cocos2dx是可以跨平台使用的（IOS/ANDROID）
通过几天的训练，我现在训练了个觉得不错的参数出来。

问题来了：我所有的动作都是在DOCKER下进行的。我现在手上拿了一份参数的TAR文件。却不知如何在具体的游戏开发中使用上。

**Comment by sandycs** [comment]
顶一下。有没有好心人？

**Comment by typhoonzero** [comment]
@hedaoyuan  mark

**Comment by hedaoyuan** [comment]
@sandycs 可以看一下这里的内容https://github.com/PaddlePaddle/Mobile
在Android上用，需要follow里面的文档，编译Android上的inference library，然后再follow开发预测程序（可以看一下那个C的demo）。

**Comment by Yancey1989** [comment]
这个issue由于长时间未更新先关闭了，如有依然有问题可以随时重新打开它。
