### ISSUE TITLE
预训练模型不可用

### ISSUE THREAD

**Issue by taazzj** [PaddlePaddle/Paddle#59450]
### bug描述 Describe the Bug

显卡 3090
镜像 registry.baidubce.com/paddlepaddle/paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6
预训练模型 hub install yolov3_darknet53_vehicles==1.1.0
命令 hub run yolov3_darknet53_vehicles --input_path "./R.jpg"
![捕获](https://github.com/PaddlePaddle/Paddle/assets/136426142/acb8f5da-65fe-4f68-9ddb-7c3b57adcfc9)

**Comment by 0x45f** [comment]
请问用的是什么版本paddle呢？

**Comment by taazzj** [comment]
> 请问用的是什么版本paddle呢？

镜像默认的2.5.2

**Comment by 0x45f** [comment]
paddlehub只适配到paddle2.1，试下2.1版本呢。另外PaddleHub已不再维护，建议使用PaddleX，支持的模型库列表参考 https://aistudio.baidu.com/intro/paddlex/models

**Comment by taazzj** [comment]
> paddlehub只适配到paddle2.1，试下2.1版本呢。另外PaddleHub已不再维护，建议使用PaddleX，支持的模型库列表参考 https://aistudio.baidu.com/intro/paddlex/models

https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_vehicles&en_category=ObjectDetection
那这个预训练模型该怎么使用，里面使用的hub

**Comment by taazzj** [comment]
> > paddlehub只适配到paddle2.1，试下2.1版本呢。另外PaddleHub已不再维护，建议使用PaddleX，支持的模型库列表参考 https://aistudio.baidu.com/intro/paddlex/models
> 
> https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_vehicles&en_category=ObjectDetection 那这个预训练模型该怎么使用，里面使用的hub

**Comment by 0x45f** [comment]
> > paddlehub只适配到paddle2.1，试下2.1版本呢。另外PaddleHub已不再维护，建议使用PaddleX，支持的模型库列表参考 https://aistudio.baidu.com/intro/paddlex/models
> 
> https://www.paddlepaddle.org.cn/hubdetail?name=yolov3_darknet53_vehicles&en_category=ObjectDetection 那这个预训练模型该怎么使用，里面使用的hub

试下安装2.1版本的paddle，或者尝试使用PaddleX
