### ISSUE TITLE
[Bug]top_p_sampling 算子精度问题

### ISSUE THREAD

**Issue by wj-Mcat** [PaddlePaddle/Paddle#59485]
### bug描述 Describe the Bug

* 安装最新版本的 paddle 

直接在官网上面安装就行了，尽量保证一周之内的 paddle 版本: https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html

* 复现代码

```python
import paddle
inputs = paddle.randn([3, 10000], dtype='float32')
tokens_res = []
for i in range(10):
    # 这里加不加 seed 作用都是一样的
    _, next_tokens = paddle.tensor.top_p_sampling(inputs, paddle.full([3,1], 0.9, dtype="float32"))
    tokens_res.append(next_tokens.reshape([-1]).numpy().tolist())

for i in range(1, len(tokens_res)):
    assert tokens_res[i] == tokens_res[i-1]
```

**Comment by carryyu** [comment]
修复PR见：[59494](https://github.com/PaddlePaddle/Paddle/pull/59494)，待合入。

需要注意，当前top_p_sampling中的seed在不指定random_seed时，会根据时间戳产生，因此验证多次调用的随机性时，请sleep(1)。
