### ISSUE TITLE
咨询一下AdamW的实现细节

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#59512]
### 请提出你的问题 Please ask your question

在看AdamW的实现的时候，遇到了几个问题，希望可以得到解答：

1、文档中（ https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/AdamW_cn.html#adamw ）的公式里面，在最后一步计算`param_out`的时候，其中有一项，是这个：拿`moment_1`当做分子，根号下`moment_2`加一个很小的`epsilon`当做分母，这两个除一下。

不过从论文中的描述看，这里的`moment_1`是不是应该改成`moment_1_out`？同时`moment_2`也应该是`moment_2_out`。即，用更新之后的`moment_1`和`moment_2`来进行最后的计算，输出是`param_out`。

不知道是不是文档写错了？

2、在CUDA的实现中（ https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/gpu/adamw_kernel.cu ），有这样一句代码：
```
MT denom = (sqrt(mom2) / sqrt(static_cast<MT>(1.0) - beta2_pow)) + epsilon;
```
上面的代码中，`mom2`存放的是更新之后的值，对应1中提到的文档的`moment_2_out`。它和尾巴上的`epsilon`的关系是，这个东西要先开个根号，然后乘以某个数，才去加`epsilon`。但是文档中，是开根号之后，直接就加`epsilon`去了，中间没有乘以系数的操作。

另，我注意到了这个`adamw_kernel.cu`的算法实现，是把`sqrt(static_cast<MT>(1.0) - beta2_pow))`和`(static_cast<MT>(1.0) - beta1_pow)`这两个东西写在了两行，拆分成了两块计算，而不是文档中的那个对`learning_rate`进行直接缩放，缩放系数是根号下`1-beta2_pow`除以`1-beta1_pow`。但是，这两个计算方法不是完全等价的啊，区别在于`epsilon`这个东西差了一个系数。

虽然说`epsilon`这个很小的常量本来就不大，但那也是计算方法和公式/论文不符。

不知道是我哪里没有理解对，还是这里就是计算有bug，还是有什么原因特意写成了这样，希望可以得到解答。

**Comment by GuoxiaWang** [comment]
@houj04 
问题（1）是的，文档写的公式不是很准确
问题（2）epsilon 是为了起到避免除0，所以关心的是加在除法的那项上。其实就是数学等价还是数值等价的问题。

**Comment by houj04** [comment]
问题（2），从数学上来说的确是给分母加了一个epsilon。但是对于我们这些做多硬件支持的来说，我们按照论文的标准方法来实现，就会和PaddlePaddle的GPU实现有diff啊。喂同样的数据进去，同样的epsilon，算出来的结果就会不同。

**Comment by GuoxiaWang** [comment]
（2）应该是和 torch 对齐的？我之前研究过。不确定现在还对齐不。

**Comment by Xiadalei** [comment]
> 问题（2），从数学上来说的确是给分母加了一个epsilon。但是对于我们这些做多硬件支持的来说，我们按照论文的标准方法来实现，就会和PaddlePaddle的GPU实现有diff啊。喂同样的数据进去，同样的epsilon，算出来的结果就会不同。

实现adam/adamw时，eplison不是用的原始论文中Algorithm 1里提供的公式，用的实际是eplison-hat，具体可以见原始论文的2.1前：
![图片](https://github.com/PaddlePaddle/Paddle/assets/16681099/1aa3fbd0-d2d9-46c4-81d2-b98e2cc8be81)
论文地址是：
https://arxiv.org/pdf/1412.6980.pdf

文档上tensorflow/keras做出了说明，可见：
https://keras.io/api/optimizers/adamw/
对应的文档修改的讨论是：
https://github.com/tensorflow/tensorflow/issues/9047
这两种实现不同在于epsilon会有一个`1. / sqrt(1 - beta2_pow)` 的缩放。
这个差别在cpu的实现里体现地更加明显一些，可见
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/cpu/adam_kernel.cc#L118

**Comment by houj04** [comment]
感谢回复，我也是觉得`epsilon`上面差了一个系数。虽然说`epsilon`本身绝对值不大，但是我们做对齐的时候总感觉哪里差一点儿……
我再仔细阅读一下其它框架的实现和讨论。
