### ISSUE TITLE
无法定位程序输入点

### ISSUE THREAD

**Issue by xiaozhou0311** [PaddlePaddle/Paddle#59559]
### 请提出你的问题 Please ask your question

![1E2EE6E7-11C2-4536-B1D1-0361533C7E9A](https://github.com/PaddlePaddle/Paddle/assets/144915223/b12c536a-77f6-464c-aca1-a7a425629d07)

**Comment by xiaozhou0311** [comment]
无法定位程序的输入点

**Comment by vivienfanghuagood** [comment]
请问paddle版本、运行环境的版本分别是什么呢

**Comment by xiaozhou0311** [comment]
> 请问paddle版本、运行环境的版本分别是什么呢

paddle 2.7 cuda11.8 tensorrt 8.5

**Comment by vivienfanghuagood** [comment]
Paddle版本不是2.7，最高只有2.5哈
