### ISSUE TITLE
Single GPU performance Improvement

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#5957]
## Profiler
Use either `nvprof` or `paddle.v2.fluid.profiler`

## Benchmark:
1. resnet_cifar10: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_image_classification_train.py
1. RNN

## Steps:
1. Update cuDNN, this includes:
    1. Update NVIDIA Container to CUDA 9 and cuDNN 7 (Current version is CUDA 8 and cuDNN 5)
    1. Link cuDNN into Paddle in [cudnn.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/platform/dynload/cudnn.h)
    1. Search over Paddle Operators, directly use CuDNN when possible
1. Reduce the number of kernel launch of the kernel is written through eigen

**Comment by wangkuiyi** [comment]
Thanks for creating this issue. We need at least an addition benchmark of RNN performance.

**Comment by wangkuiyi** [comment]
Also, we should include the upgrade of cuDNN/cuBLAS/CUDA version.

**Comment by tonyyang-svail** [comment]
Use NCCL 2 to get NvLink support

**Comment by dzhwinter** [comment]
Please reference this cuda one into https://github.com/PaddlePaddle/Paddle/issues/6024 @tonyyang-svail 
We have create some tools and benchmarks.

**Comment by tonyyang-svail** [comment]
Moved the issue to https://github.com/PaddlePaddle/Paddle/issues/6024.
