### ISSUE TITLE
“如何贡献/修改文档”更新

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#5959]
目前的文档已过时：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/write_docs_cn.rst
最新的贡献文档在：https://github.com/PaddlePaddle/paddlepaddle.org#paddlepaddleorg-document-generation-and-viewer-tool

需要更新`write_docs_cn.rst`，并补充对应的英文文档。
同时，最新的贡献文档中还缺以下内容：
- 只有docker的使用步骤，如果开发者没有docker，能否提供其他的使用步骤？
- 只能在本地 http://localhost:8000 查看，缺少在远程机器上开发的步骤。

**Comment by jetfuel** [comment]
Still need to figure a good way to compile the documentation on a remote machine.
