### ISSUE TITLE
为何两台4核CPU的QPS会明显高于一台8核CPU机器？

### ISSUE THREAD

**Issue by tigflanker** [PaddlePaddle/Paddle#59624]
### 请提出你的问题 Please ask your question

请教paddle大佬一个工程问题：
我在用paddleocr做项目部署的时候，两台N核机器总是比一台2N核机器要好，这是为啥呢？

环境：
Centos 7 + gunicorn多进程 + Paddleocr（模型采用onnxruntime）
内存一直都是够的，从没用到80%，每台机器run的时候CPU都是跑满100%

评测结果：
1. 单张25k照片ocr耗时200ms~300ms
2. **【重点】两台8核机器QPS为16.11，一台16核机器QPS为12.29（比值76.3%）**
3. 两台4核机器（用nginx分发）的QPS（每秒处理需求数）为9.68，一台8核机器QPS为8.37（比值86.5%）

观察到的另一个现象：
如果一台N核的机器，假如说我把服务用taskset绑定到最后一个核（偏下方无论哪几个核），“前N/2-1” 个CPU一定是同时跑满的
例如16核机器，我用taskset把gunicorn服务绑定在第14和15两个核上运行，那我在post查询的时候，CPU0至CPU6和CPU14至CPU15，这7+2个核会跑满
这个现象我无法解释，不知道和这个问题是否相关

结论：
假如说一台64核的机器和两台32核机器的“资源”一样，那想要达到最佳性能，一定要至少拆到4核或者2核。那么为什么一台多核机器反而会有性能损耗呢？

**Comment by tigflanker** [comment]
百度谷歌上都没有查到答案，GPT也问了一下没有答案

另外我还观察到一个线索不知道是否和这个问题相关：
因为服务效率不高，我尝试对高并发场景积攒需求，做一下“流转批”
但是我发现：onnxruntime，for循环100次，每次一个查询的总耗时，要小于[100, 3, w, h]直接大张量用onnx预测的耗时

**Comment by FeixLiu** [comment]
感谢您的问题，我联系下相关同学帮忙看一下～

**Comment by tigflanker** [comment]
@FeixLiu 感谢您的答复，这问题可能比较偏Linux的需求分发或者资源分配。
因为我之前做工程太少，部署paddleocr时发现了这个问题，所以来请教下工程的大佬。
以下是上周测试的记录图，和问题相关的就是上面CPU测试和两个结论
![微信图片_20231204103924](https://github.com/PaddlePaddle/Paddle/assets/22868157/ff4a37d6-ad24-4f3d-a407-01f74e84d33b)

**Comment by vivienfanghuagood** [comment]
这是个很有价值的问题，我们持续关注，有进展会在这里同步。
