### ISSUE TITLE
新增 API 静态图单测时 infer_shape 报错 bad_variant_access

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#59629]
### 新增 API 静态图单测时 infer_shape 报错 bad_variant_access

- 相关PR
https://github.com/PaddlePaddle/Paddle/pull/58433

- 存在的问题
目前，动态图单元测试可以正常运行，但是静态图单元测试存在问题，如下
![image](https://github.com/PaddlePaddle/Paddle/assets/118546135/07774220-9325-43b1-8573-c8530c1e0146)
这周尝试了各种各样的方法，还是解决不了，很难过。想请教一下，我该往哪个方向努力呀？

**Comment by WintersMontagne10335** [comment]
其中一次尝试是，改变实现思路，在 pool2d 的基础上，增加参数 norm_type，这时静态图单测报错如下
![6864b4d3cbe0ecbf977d17c47fecb19](https://github.com/PaddlePaddle/Paddle/assets/118546135/c0711bf6-ed2e-4abd-ad08-ef56a9b51d32)
这个用了两天左右时间，也是解决不了。

**Comment by cyber-pioneer** [comment]
建议写一个单独的.py文件，复现这个报错case，先排除单侧系统的问题，确认报错的场景，包括参数输入，place，可以帮助定位问题。最小的复现case可以贴上来看看。

**Comment by WintersMontagne10335** [comment]
> 建议写一个单独的.py文件，复现这个报错case，先排除单侧系统的问题，确认报错的场景，包括参数输入，place，可以帮助定位问题。最小的复现case可以贴上来看看。

- 单测系统：参照paddle已有的avg_pool2d、max_pool2d的单测写的lp_pool2静态图的单测，avg_pool2d、max_pool2d都能正常运行，不太可能是单测系统的问题
- 报错场景
  - 参数输入：数据格式为 `NCHW` ，类型为 `float32`
  - place：CPU 、GPU 报同样的错误
- 复现步骤（基于 PR 的最新代码）
  - cmake .. -DPY_VERSION=3.8 -DWITH_GPU=ON -DWITH_TESTING=ON -DWITH_DISTRIBUTE=OFF -DWITH_NCCL=OFF -DWITH_RCCL=OFF
  - make
  - ctest -R test_lp_pool2d_api_static -V
