### ISSUE TITLE
need to upgrade libtool 

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#5964]
PR #5520 introduce the third-party package `cares`, which is needed by the `grpc`, if you meet the same error below, please upgrade the `libtool`.
`yum install libtool` or `apt-get install libtool --upgrade`

```txt
buildconf: libtoolize not found.
    You need GNU libtoolize 1.4.2 or newer installed.
CMakeFiles/extern_cares.dir/build.make:106: recipe for target 'third_party/cares/src/extern_cares-stamp/extern_cares-configure' failed
make[3]: *** [third_party/cares/src/extern_cares-stamp/extern_cares-configure] Error 1
CMakeFiles/Makefile2:439: recipe for target 'CMakeFiles/extern_cares.dir/all' failed
make[2]: *** [CMakeFiles/extern_cares.dir/all] Error 2
```

**Comment by typhoonzero** [comment]
PR https://github.com/PaddlePaddle/Paddle/pull/5520 added `libtool` in the `Dockerfile`, you just need to re-pull it or install `libtool` in your build environment.

**Comment by gongweibao** [comment]
On mac
`brew install libtool ` or `brew upgrade libtool`

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/6034
