### ISSUE TITLE
[Build] api_gen.py can't build in the python3.7 env

### ISSUE THREAD

**Issue by AndSonder** [PaddlePaddle/Paddle#59676]
### 问题描述 Issue Description

Develop 分支的 paddle，在api_gen.py中使用了3.8才支持的海象表达式，3.7环境下编译报错：

![197291701692014_ pic](https://github.com/PaddlePaddle/Paddle/assets/55493212/d9ef87c1-7b2c-4e54-8f87-479fcac1d2e8)

### 版本&环境信息 Version & Environment Information

Paddle version: develop
cuda version: 11.2
Python 版本：3.7

**Comment by 0x45f** [comment]
请使用3.8版本以上的python，3.7版本已经不在支持了~

**Comment by AndSonder** [comment]
好的 谢谢
