### ISSUE TITLE
Windows11 CUDA12.1 cuDNN8.9.6.50 python3.11 编译GPU版本错误

### ISSUE THREAD

**Issue by samabl** [PaddlePaddle/Paddle#59678]
按照官网教程来的，到`cmake .. -GNinja -DWITH_GPU=ON -DWITH_UNITY_BUILD=ON`这步出现错误

[log.txt](https://github.com/PaddlePaddle/Paddle/files/13554032/log.txt)

**Comment by YuanRisheng** [comment]
看起来好像是网络原因，三方库没有下载下来，全部删除重新编译呢，另外今天最新develop分支有点问题，可以用前几天代码库的代码试试

**Comment by samabl** [comment]
> 看起来好像是网络原因，三方库没有下载下来，全部删除重新编译呢，另外今天最新develop分支有点问题，可以用前几天代码库的代码试试

可以编译了但是执行`ninja`又报了一堆错误，是protobuf的版本不对吗（日志文件编码是GB2312）
[log_ninja.txt](https://github.com/PaddlePaddle/Paddle/files/13556220/log_ninja.txt)

**Comment by YuanRisheng** [comment]
确认了一下，cuda12.1在windows上现在还不支持，最近我们在做这项工作，后续支持后才可以使用

**Comment by samabl** [comment]
> 确认了一下，cuda12.1在windows上现在还不支持，最近我们在做这项工作，后续支持后才可以使用

好的，谢谢
