### ISSUE TITLE
[Dy2St] `enable_to_static_guard` 推全

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#59684]
## 一. BackGround 📚
任务背景：#59670

## 二. Tutorial 💼

举例:

```python
    def test_error(self):
        if self.dyfunc:
            with self.assertRaisesRegex(Dygraph2StaticException, self.error):
                paddle.jit.enable_to_static(True)
                self.assertTrue(paddle.jit.to_static(self.dyfunc)(self.x))
        paddle.base.dygraph.base.global_var._in_to_static_mode_ = False
        paddle.jit.enable_to_static(False)
```

```python
    def test_error(self):
        if self.dyfunc:
            with self.assertRaisesRegex(Dygraph2StaticException, self.error):
                with enable_to_static_guard(True):
                    self.assertTrue(paddle.jit.to_static(self.dyfunc)(self.x))
        paddle.base.dygraph.base.global_var._in_to_static_mode_ = False
```

将原来的flag形式:
```python
paddle.jit.enable_to_static(True)
......
paddle.jit.enable_to_static(False)
```
修改为上下文管理器的形式:
```python
with enable_to_static_guard(True):
    .......
```
以免泄漏 enable_to_static 状态到单测外

## 三. Task 🙋🏻‍♀️

✅：已经完全修复，所有单测都OK！
🟢：待合入，合入之后完全修复！
🟡：当前阶段不需要人力继续跟进，下阶段推进（Save、控制流、AMP、编译器、PyFuncOp、TrainStep整体导出】
❌：单测没有通过，需要人力跟进。
🚧：待分析，单测还没有进行分析，可以进行分析或者是修复。

|ID|文件名字 | 数量 |   PR   |   Github ID   |
|:-:|:-: | :-: |   :-:   |   :-:   |
|✅1|test/dygraph_to_static/test_assert.py | 1 |   #59686    |   [Ryan](https://github.com/DrRyanHuang)   |
|✅2|test/dygraph_to_static/test_bert.py | 3 |   #59686   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅3|test/dygraph_to_static/test_bmn.py | 2 |   #59686   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅4|test/dygraph_to_static/test_break_continue.py | 1 | #59569     |  [gouzil](https://github.com/gouzil)   |
|✅5|test/dygraph_to_static/test_build_strategy.py | 1 |   #59686   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅6|test/dygraph_to_static/test_cache_program.py | 1 |   #59691   |   [Ryan](https://github.com/DrRyanHuang)  |
|✅7|test/dygraph_to_static/test_convert_call.py | 4 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅8|test/dygraph_to_static/test_cycle_gan.py | 1 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅9|test/dygraph_to_static/test_declarative.py | 4 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅10|test/dygraph_to_static/test_dict.py | 3 |   #59691   |   [Ryan](https://github.com/DrRyanHuang)  |
|✅11|test/dygraph_to_static/test_fetch_feed.py | 1 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅12|test/dygraph_to_static/test_for_enumerate.py | 2 |  #59691   |   [Ryan](https://github.com/DrRyanHuang)  |
|✅13|test/dygraph_to_static/test_grad.py | 1 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅14|test/dygraph_to_static/test_grid_generator.py | 1 |   #59691   |  [Ryan](https://github.com/DrRyanHuang)   |
|✅15|test/dygraph_to_static/test_isinstance.py | 1 |   #59691    |  [Ryan](https://github.com/DrRyanHuang)   |
|✅16|test/dygraph_to_static/test_lac.py| 2 |   #59730   | [gouzil](https://github.com/gouzil)    |
|✅17|test/dygraph_to_static/test_logical.py | 1 |  #59717    |  [gouzil](https://github.com/gouzil)    |
|✅18|test/dygraph_to_static/test_lstm.py | 3 |  #59717    |  [gouzil](https://github.com/gouzil)   |
|✅19|test/dygraph_to_static/test_mobile_net.py | 2 |  #59717    |  [gouzil](https://github.com/gouzil)   |
|✅20|test/dygraph_to_static/test_param_guard.py | 2 | #59717     | [gouzil](https://github.com/gouzil)    |
|✅21|test/dygraph_to_static/test_print.py | 1 |  #59717    |  [gouzil](https://github.com/gouzil)   |
|✅22|test/dygraph_to_static/test_program_translator.py | 3 |  #59717    |  [gouzil](https://github.com/gouzil)   |
|✅23|test/dygraph_to_static/test_ptb_lm_v2.py | 2 |   #59729   |   [gouzil](https://github.com/gouzil)  |
|✅24|test/dygraph_to_static/test_ptb_lm.py | 2 |  #59729    |  [gouzil](https://github.com/gouzil)   |
|✅25|test/dygraph_to_static/test_pylayer.py | 2 |  #59729    |  [gouzil](https://github.com/gouzil)   |
|✅26|test/dygraph_to_static/test_reinforcement_learning.py | 2 |  #59729    |  [gouzil](https://github.com/gouzil)   |
|✅27|test/dygraph_to_static/test_resnet_amp.py | 1 |    #59729  |  [gouzil](https://github.com/gouzil)   |
|✅28|test/dygraph_to_static/test_resnet_pure_fp16.py | 1 |  #59729    |  [gouzil](https://github.com/gouzil)   |
|~29~|~test/dygraph_to_static/test_resnet_v2.py~ | 2 |  #59729    |  [gouzil](https://github.com/gouzil)   |
|✅30|test/dygraph_to_static/test_resnet.py | 2 |   #59742   |  [SigureMo](https://github.com/SigureMo)   |
|✅31|test/dygraph_to_static/test_return.py | 1 |   #59703   |   [ooooo-create](https://github.com/ooooo-create)  |
|✅32|test/dygraph_to_static/test_save_inference_model.py | 2 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅33|test/dygraph_to_static/test_save_load.py | 2 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅34|test/dygraph_to_static/test_se_resnet.py | 2 |    #59703  |  [ooooo-create](https://github.com/ooooo-create)   |
|✅35|test/dygraph_to_static/test_sentiment.py | 1 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅36|test/dygraph_to_static/test_seq2seq.py | 2 |  #59703    |  [ooooo-create](https://github.com/ooooo-create)   |
|✅37|test/dygraph_to_static/test_simnet_v2.py | 1 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅38|test/dygraph_to_static/test_simnet.py | 1 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅39|test/dygraph_to_static/test_slice.py | 1 |   #59703   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅40|test/dygraph_to_static/test_tensor_memcpy_on_cpu.py | 3 |   #59694   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅41|test/dygraph_to_static/test_tensor_memcpy_on_gpu.py | 3 |  #59694   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅42|test/dygraph_to_static/test_tensor_methods.py | 5 |   #59694   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅43|test/dygraph_to_static/test_tsm.py | 1 |   #59694   |   [ooooo-create](https://github.com/ooooo-create)  |
|✅44|test/dygraph_to_static/test_word2vec.py | 1 |   #59694   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅45|test/dygraph_to_static/test_yolov3.py | 1 |   #59694   |  [ooooo-create](https://github.com/ooooo-create)   |
|✅46| test/legacy_test/test_base_layer.py | 1 |  #59730    |  [gouzil](https://github.com/gouzil)   |
|✅47| test/legacy_test/test_jit_layer.py | 2 |  #59730    |  [gouzil](https://github.com/gouzil)   |
|✅48| test/legacy_test/test_model.py | 1 |   #59730   |  [gouzil](https://github.com/gouzil)   |
|✅49| test/legacy_test/test_paddlescience.py | 1 |    #59730  |  [gouzil](https://github.com/gouzil)   |
|✅50 | 在CI上添加检查 |  |    #60037 |  [Ryan](https://github.com/DrRyanHuang)   |
|✅51 | test/dygraph_to_static/test_declarative.py | 1 |    #60079 |  [Ryan](https://github.com/DrRyanHuang)   |
|✅52 | test/dygraph_to_static/test_return.py | 3 |    #60079 |  [Ryan](https://github.com/DrRyanHuang)   |

## 四. 统计信息 🎇
@gouzil 18
@ooooo-create 15
@DrRyanHuang 16
@SigureMo 1
鸣谢 reviewer @SigureMo

**Comment by SigureMo** [comment]
@paddle-bot 干啥呢！打你哦！
