### ISSUE TITLE
fused_layer_norm API PIR 迁移任务报错修复

### ISSUE THREAD

**Issue by MarioLulab** [PaddlePaddle/Paddle#59721]
### bug描述 Describe the Bug

关联 PR：https://github.com/PaddlePaddle/Paddle/pull/59420
此 [PR](https://github.com/PaddlePaddle/Paddle/pull/59420) 在 pir 模式下挂在了单测的 [`check_residual_bias_add`](https://github.com/PaddlePaddle/Paddle/pull/59420/files#diff-1d5e30c5392f24fac13f56380eb29b8a9aff4bc41014c2f072259876a7abab42R497-R544) 函数中，但在旧 ir 模式下，并没有报错

### 其他补充信息 Additional Supplementary Information

本地可以复现，报错栈为

```bash
I1205 12:20:48.664741 45627 inplace_pass.cc:473] Apply inplace pass on lowering ::pir::Program to Kernel Dialect.
I1205 12:20:48.665340 45627 pir_interpreter.cc:1178] New Executor is Running ...
I1205 12:20:48.668500 45627 pir_interpreter.cc:1205] pir interpreter is running by multi-thread mode ...
W1205 12:20:48.692785 45735 pir_interpreter.cc:1591]  OP id:6 pd_op.memcpy_d2h raises an EnforceNotMet exception phi::enforce::EnforceNotMet, In user code:


    PreconditionNotMetError: Tensor holds no memory. Call Tensor::mutable_data firstly.
      [Hint: holder_ should not be null.] (at /home/aistudio/Paddle/paddle/phi/core/dense_tensor_impl.cc:44)
      [operator < pd_kernel.phi_kernel > error]
E
======================================================================
ERROR: test_residual_bias_add (test_fused_layernorm_op.TestlayernormStaticOp)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/aistudio/Paddle/build-gpu/python/paddle/pir_utils.py", line 115, in impl
    func(*args, **kwargs)
  File "/home/aistudio/Paddle/test/legacy_test/test_fused_layernorm_op.py", line 732, in test_residual_bias_add
    ) = self.check_residual_bias_add(
  File "/home/aistudio/Paddle/test/legacy_test/test_fused_layernorm_op.py", line 550, in check_residual_bias_add
    out_s = exe.run(
  File "/home/aistudio/Paddle/build-gpu/python/paddle/base/executor.py", line 1715, in run
    res = self._run_pir_impl(
  File "/home/aistudio/Paddle/build-gpu/python/paddle/base/executor.py", line 2062, in _run_pir_impl
    ret = new_exe.run(list(feed.keys()), return_numpy)
  File "/home/aistudio/Paddle/build-gpu/python/paddle/base/executor.py", line 822, in run
    tensors = self._new_exe.run(
RuntimeError: In user code:


    PreconditionNotMetError: Tensor holds no memory. Call Tensor::mutable_data firstly.
      [Hint: holder_ should not be null.] (at /home/aistudio/Paddle/paddle/phi/core/dense_tensor_impl.cc:44)
      [operator < pd_kernel.phi_kernel > error]

----------------------------------------------------------------------
Ran 1 test in 4.546s
```

我将 pir 模式下的 startup program 和 main program 打印出来如下：

```bash
startup_program:
{
}

main_program:
{
 (%0) = "pd_op.data" () {dtype:(pd_op.DataType)float16,name:"x_static",place:(pd_op.Place)Place(undefined:0),shape:(pd_op.IntArray)[16,256],stop_gradient:[true]} : () -> pd_op.tensor<16x256xf16>
 (%1) = "pd_op.data" () {dtype:(pd_op.DataType)float16,name:"residual_static",place:(pd_op.Place)Place(undefined:0),shape:(pd_op.IntArray)[16,256],stop_gradient:[true]} : () -> pd_op.tensor<16x256xf16>
 (%2) = "pd_op.data" () {dtype:(pd_op.DataType)float16,name:"bias_static",place:(pd_op.Place)Place(undefined:0),shape:(pd_op.IntArray)[256],stop_gradient:[true]} : () -> pd_op.tensor<256xf16>
 (%3, %4, %5, %6) = "pd_op.fused_bias_residual_layernorm" (%0, %2, %1, <<NULL VALUE>>, <<NULL VALUE>>) {begin_norm_axis:(Int32)1,epsilon:(Float)1e-05,quant_max_bound:(Float)127,quant_min_bound:(Float)-127,quant_round_type:(Int32)1,quant_scale:(Float)0.15,residual_alpha:(Float)0.692047,stop_gradient:[true,true,true,true]} : (pd_op.tensor<16x256xf16>, pd_op.tensor<256xf16>, pd_op.tensor<16x256xf16>, <<NULL TYPE>>, <<NULL TYPE>>) -> pd_op.tensor<16x256xf16>, pd_op.tensor<16x256xf16>, pd_op.tensor<16xf32>, pd_op.tensor<16xf32>
}
```

该单测函数 `check_residual_bias_add` 传给 fused_layer_norm api 的 norm_weight=None, norm_bias=None，即给 c++ api 的 fused_bias_residual_layernorm 的输入 norm_weight 和 norm_bias 均为 None。拿 norm_weight 举例，我好奇 pir 构图中对空的 value 如何处理，于是一步步定位：
1. paddle/fluid/pir/dialect/operator/ir/pd_api.cc::fused_bias_residual_layernorm 函数中：若 norm_weight 为 nullptr，则以 pir::Value 的方式初始化 norm_bias，并传递给 pir op builder 的 build 函数构图
![image](https://github.com/PaddlePaddle/Paddle/assets/61354321/6e78ae24-94ee-4256-9ceb-36d304db8673)

2. 我定位到在 fused_bias_residual_layernorm 对应的 [Kernel 函数](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/kernels/fusion/gpu/fused_layernorm_kernel.cu#L968-L980)
这里居然没有给输出的 residual_out, mean, variance 分配任何内存，这是不是导致报错的原因？如果是这个原因，那么旧 ir 的执行器为何没有报错？

**Comment by 0x45f** [comment]
关于这个问题还是fetch导致的，这里相当于fetch了一个kernel里没有初始化的var出来。因为PIR这里fetch的逻辑和老静态图有diff，所以在PIR下fetch未初始化的var会报错。这里倾向于改一下单测吧，单测里应该只会测试已经初始化有数据的结果，修改一下fetch list吧，只把想要测试的结果fetch出来~
![image](https://github.com/PaddlePaddle/Paddle/assets/23097963/b4fbf5f0-94eb-4479-9067-2e66b5ef0b0a)
比如上图的测试case，只想要测试[0]，那么是不是就可以只把[0] fetch出来呢？

**Comment by MarioLulab** [comment]
> 关于这个问题还是fetch导致的，这里相当于fetch了一个kernel里没有初始化的var出来。因为PIR这里fetch的逻辑和老静态图有diff，所以在PIR下fetch未初始化的var会报错。这里倾向于改一下单测吧，单测里应该只会测试已经初始化有数据的结果，修改一下fetch list吧，只把想要测试的结果fetch出来~ ![image](https://private-user-images.githubusercontent.com/23097963/288271338-b4fbf5f0-94eb-4479-9067-2e66b5ef0b0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE4NDY0MzgsIm5iZiI6MTcwMTg0NjEzOCwicGF0aCI6Ii8yMzA5Nzk2My8yODgyNzEzMzgtYjRmYmY1ZjAtOTRlYi00NDc5LTkwNjctMmU2NmI1ZWYwYjBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA2VDA3MDIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4OTA2ZjY5Y2ZiY2ExNjI4MDgzOTQ3M2Q1YzQ1YmRjOGI3ODUyOWZlNTc3M2QyMjVmOTk5Zjg1NWI3MzhkNTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8TeCwJ09ciXha2KI0nPmDIUns1H7p3DrDnnvYT_qefw) 比如上图的测试case，只想要测试[0]，那么是不是就可以只把[0] fetch出来呢？

确实是可以的。按照这个方法，运行本地单测已经跑通了~ 
还想请问以下 pir 的 fetch 逻辑未来会不会和老静态图对齐，即未来会修复 “在PIR下fetch未初始化的var会报错” 这个错误？

**Comment by MarioLulab** [comment]
问题已解决，采取方法是：在 pir 单测中，只 fetch 出需要使用的变量。这种方法暂时规避这类错误
https://github.com/PaddlePaddle/Paddle/pull/59420
