### ISSUE TITLE
Wrong LaTeX equation in adagrad_op.cc

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#5973]
https://github.com/PaddlePaddle/Paddle/blob/d7bf372d2682b4951308da47fcc444265ac80510/paddle/operators/adagrad_op.cc#L83-L85

It seems that a pair of $'s nests in the pair of double-$, which leads to wrong LaTeX equation displaying at http://www.paddlepaddle.org/docs/develop/documentation/en/operators.html#permalink-2-adagrad

**Comment by kavyasrinet** [comment]
Fixed this in the pull request here : https://github.com/PaddlePaddle/Paddle/pull/6009
Please review when you can @kexinzhao
