### ISSUE TITLE
unable to access 'https://boringssl.googlesource.com/boringssl/'

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#5974]
When I build the latest code, I get this:
fatal: unable to access 'https://boringssl.googlesource.com/boringssl/': Failed to connect to boringssl.googlesource.com port 443: Connection timed out
fatal: clone of 'https://boringssl.googlesource.com/boringssl' into submodule path '/home/work/qijun/paddle/build/third_party/grpc/src/extern_grpc/third_party/boringssl-with-bazel' failed
Failed to clone 'third_party/boringssl-with-bazel' a second time, aborting
CMake Error at /home/work/qijun/paddle/build/third_party/grpc/tmp/extern_grpc-gitclone.cmake:67 (message):
  Failed to update submodules in:
  '/home/work/qijun/paddle/build/third_party/grpc/src/extern_grpc'

**Comment by typhoonzero** [comment]
https://boringssl.googlesource.com/boringssl seems cannot be accessed in China, try using a proxy.

**Comment by Yancey1989** [comment]
Maybe we can use the mirror on Github: https://github.com/google/boringssl

**Comment by qingqing01** [comment]
I have the same error. @QiJune how do you fix it?

**Comment by luotao1** [comment]
I use a proxy, but failed:
```

Initialized empty Git repository in /home/luotao02/Paddle/build/third_party/grpc/src/extern_grpc/.git/
error: The requested URL returned error: 503 while accessing https://github.com/grpc/grpc.git/info/refs

fatal: HTTP request failed
Initialized empty Git repository in /home/luotao02/Paddle/build/third_party/grpc/src/extern_grpc/.git/
error: The requested URL returned error: 503 while accessing https://github.com/grpc/grpc.git/info/refs

fatal: HTTP request failed
Initialized empty Git repository in /home/luotao02/Paddle/build/third_party/grpc/src/extern_grpc/.git/
error: The requested URL returned error: 503 while accessing https://github.com/grpc/grpc.git/info/refs

fatal: HTTP request failed
-- Had to git clone more than once:
          3 times.
CMake Error at /home/luotao02/Paddle/build/third_party/grpc/tmp/extern_grpc-gitclone.cmake:40 (message):
  Failed to clone repository: 'https://github.com/grpc/grpc.git'
```

**Comment by QiJune** [comment]
@qingqing01 
```
outnet_exec make -j12
```
