### ISSUE TITLE
CUDA sync_batch_norm 中 stream 使用

### ISSUE THREAD

**Issue by Aganlengzi** [PaddlePaddle/Paddle#59760]
### 请提出你的问题 Please ask your question

在PaddlePaddle的代码中[应该很久没有变更过了]，观察到 sync_batch_norm 算子中的计算和 ncclAllReduce 均传入相同 stream（记为计算流），而DDP的allreduce使用另外的流（记为通信流）

疑问：在模型训练开启DDP时，哪里保证了DDP的allreduce执行与这里的allreduce执行不会因为同时调用产生问题？
注意到cuda的计算流和通信流都是阻塞流

![image](https://github.com/PaddlePaddle/Paddle/assets/5997715/d37da9ff-17ec-4f16-9e48-27f055760cbc)

**Comment by AnnaTrainingG** [comment]
你好，在模型训练开启 DDP 时，保证 DDP 的 allreduce 执行与 sync_batch_norm 的 allreduce 执行不会产生问题，通常是由 PaddlePaddle 框架内部的实现来保证的。PaddlePaddle 的分布式训练模块会管理不同操作的流，并确保它们之间的同步关系。

**Comment by Aganlengzi** [comment]
> 你好，在模型训练开启 DDP 时，保证 DDP 的 allreduce 执行与 sync_batch_norm 的 allreduce 执行不会产生问题，通常是由 PaddlePaddle 框架内部的实现来保证的。PaddlePaddle 的分布式训练模块会管理不同操作的流，并确保它们之间的同步关系。

@niuliling123 这里没有任何流同步代码，phi::dynload::nccAllReduce又仅是一层接口的封装，哪里能做到你说的流同步？可以具体说一下吗

**Comment by ForFishes** [comment]
您好，阻塞流怎么理解？通信流的通信和计算流的allreduce（syncbn中）可以同时调用，并不会阻塞。

**Comment by ForFishes** [comment]
您好，阻塞流怎么理解？通信流的通信和计算流的allreduce（syncbn中）可以同时调用，并不会阻塞。

**Comment by AnnaTrainingG** [comment]
请问是静态图吗？Paddle中的c_sync_comm_stream算子专门做通信流的同步，组网的时候添加的； 计算流有对应的c_sync_calc_stream
![d54e397a1fd445bb9498fc1912024f94](https://github.com/PaddlePaddle/Paddle/assets/51102941/c9ffc5f1-c957-4ab4-a8b8-9bac080b45e3)

**Comment by Aganlengzi** [comment]
> 您好，阻塞流怎么理解？通信流的通信和计算流的allreduce（syncbn中）可以同时调用，并不会阻塞。

@ForFishes 你好，疑惑的是为什么可以同时调用。Paddle cuda中[cudaStreamCreate](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g6a3c4b819e6a994c26d0c4824a4c80da)

这里表述的阻塞流指[cudaStreamDefault](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1ged347a89ec289c787faa116b851708fc) 类型的流，与[cudaStreamNonBlocking](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g5dbd11a1723d9f5938a133cedbc525e3)想区别

考虑在典型场景中，当compute stream 和 communication stream上同时allreduce会怎么样？

NULL stream: ------------------------------------------------------------------------------
compute stream: ---------------------------allreduce--------------------------------------
communication stream: --------------------allreduce--------------------------------------

其中compute stream中的allreduce来自sync_bn，此处没有stream间同步操作，直接提交任务
communication stream是DDP默认的通信流，也不会感知到sync_bn在计算流上提交allreduce通信
哪里保证了两个allreduce同时调用时是正确的。

**Comment by Aganlengzi** [comment]
> 请问是静态图吗？Paddle中的c_sync_comm_stream算子专门做通信流的同步，组网的时候添加的； 计算流有对应的c_sync_calc_stream ![d54e397a1fd445bb9498fc1912024f94](https://private-user-images.githubusercontent.com/51102941/289414341-c9ffc5f1-c957-4ab4-a8b8-9bac080b45e3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjk1MjksIm5iZiI6MTcwMjI2OTIyOSwicGF0aCI6Ii81MTEwMjk0MS8yODk0MTQzNDEtYzlmZmM1ZjEtYzk1Ny00YWI0LWE4YjgtOWJhYzA4MGI0NWUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDA0MzM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRhNzNjMDFjNzFiMTEwMGFiNDUxZTJkZjFlM2RhZjNhNzI1NDNiM2U3M2NhNzAxYzk2MWY2ODExOTQ5ZDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F76PtGdM4z_4QfGP7fSIuWQCG0Qhd6c64Zh0nFhPlFk)

@niuliling123 不是的，动态图下开启sync_bn的DDP

**Comment by AnnaTrainingG** [comment]
好的 已经有相关同学回复了您的疑问，请问您是否还有其他困惑呢？

**Comment by Aganlengzi** [comment]
> 好的 已经有相关同学回复了您的疑问，请问您是否还有其他困惑呢？

@niuliling123 你好，还没有，还有点疑问
> > 您好，阻塞流怎么理解？通信流的通信和计算流的allreduce（syncbn中）可以同时调用，并不会阻塞。
> 
> @ForFishes 你好，疑惑的是为什么可以同时调用。Paddle cuda中[cudaStreamCreate](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__STREAM.html#group__CUDART__STREAM_1g6a3c4b819e6a994c26d0c4824a4c80da)
> 
> 这里表述的阻塞流指[cudaStreamDefault](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1ged347a89ec289c787faa116b851708fc) 类型的流，与[cudaStreamNonBlocking](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g5dbd11a1723d9f5938a133cedbc525e3)想区别
> 
> 考虑在典型场景中，当compute stream 和 communication stream上同时allreduce会怎么样？
> 
> NULL stream: ------------------------------------------------------------------------------ compute stream: ---------------------------allreduce-------------------------------------- communication stream: --------------------allreduce--------------------------------------
> 
> 其中compute stream中的allreduce来自sync_bn，此处没有stream间同步操作，直接提交任务 communication stream是DDP默认的通信流，也不会感知到sync_bn在计算流上提交allreduce通信 哪里保证了两个allreduce同时调用时是正确的。

**Comment by AnnaTrainingG** [comment]
您好， 您只是引用了两位同学的回答，还是原来的问题？还是有新的问题呢？

**Comment by Aganlengzi** [comment]
> 您好， 您只是引用了两位同学的回答，还是原来的问题？还是有新的问题呢？

@niuliling123 原来的问题未解决

具体问题：小模型DDP训练中，cuda使用 [cudaStreamDefault](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1ged347a89ec289c787faa116b851708fc) 类型的流，与[cudaStreamNonBlocking](https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g5dbd11a1723d9f5938a133cedbc525e3)相区别



问题：考虑在典型场景中，当compute stream 和 communication stream上同时allreduce会怎么样？

NULL stream: ------------------------------------------------------------------------------
compute stream: ---------------------------allreduce--------------------------------------
communication stream: --------------------allreduce--------------------------------------

其中compute stream中的allreduce来自sync_bn，此处没有stream间同步操作，直接提交任务
communication stream是DDP默认的通信流，也不会感知到sync_bn在计算流上提交allreduce通信
哪里保证了两个allreduce同时调用时是正确的？

**Comment by ForFishes** [comment]
> communication stream是DDP默认的通信流，也不会感知到sync_bn在计算流上提交allreduce通信
> 哪里保证了两个allreduce同时调用时是正确

计算流和通信流都不是defaultstream，他们两个之间可以并行。

**Comment by Aganlengzi** [comment]
> > communication stream是DDP默认的通信流，也不会感知到sync_bn在计算流上提交allreduce通信
> > 哪里保证了两个allreduce同时调用时是正确
> 
> 计算流和通信流都不是defaultstream，他们两个之间可以并行。

@ForFishes 多谢，所以原因是CUDA支持两个流并行执行allreduce是吗？请问能麻烦再帮贴下具体文档说明吗？我没找到相关内容

**Comment by AnnaTrainingG** [comment]
你好 可以参考这个文档：https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_performance/overlap.html


补充回答：在PaddlePaddle中，使用DDP（Distributed Data Parallel）进行模型训练时，确保了DDP的allreduce执行与其他allreduce执行不会因为同时调用而产生问题的地方是在数据并行的划分和通信流程的设计上。

具体来说，PaddlePaddle中的DDP会将模型参数划分为多个分片，在每个分片上进行独立的计算和梯度更新。而在进行梯度更新之前，会进行allreduce操作，将各个分片上的梯度进行求和，然后再将求和后的梯度广播到各个分片上进行更新。

为了避免同时调用产生的问题，PaddlePaddle采用了异步的计算流和通信流。在计算流中，每个分片的计算和梯度更新是独立进行的，不会相互影响。而在通信流中，使用非阻塞的通信方式，即在进行allreduce操作时，不会阻塞计算流的进行，从而保证了计算和通信的并行执行。

需要注意的是，虽然cuda的计算流和通信流都是阻塞流，但PaddlePaddle通过异步的方式来组织计算流和通信流的执行顺序，从而避免了同时调用产生的问题。这样可以在保证模型训练的正确性的同时，充分利用计算资源，提高训练的效率。

**Comment by Aganlengzi** [comment]
> 你好 可以参考这个文档：https://fleet-x.readthedocs.io/en/latest/paddle_fleet_rst/collective/collective_performance/overlap.html 

补充回答：
在PaddlePaddle中，使用DDP（Distributed Data Parallel）进行模型训练时，确保了DDP的allreduce执行与其他allreduce执行不会因为同时调用而产生问题的地方是在数据并行的划分和通信流程的设计上。
> 
> 具体来说，PaddlePaddle中的DDP会将模型参数划分为多个分片，在每个分片上进行独立的计算和梯度更新。而在进行梯度更新之前，会进行allreduce操作，将各个分片上的梯度进行求和，然后再将求和后的梯度广播到各个分片上进行更新。
> 
> 为了避免同时调用产生的问题，PaddlePaddle采用了异步的计算流和通信流。在计算流中，每个分片的计算和梯度更新是独立进行的，不会相互影响。而在通信流中，使用非阻塞的通信方式，即在进行allreduce操作时，不会阻塞计算流的进行，从而保证了计算和通信的并行执行。
> 
> 需要注意的是，虽然cuda的计算流和通信流都是阻塞流，但PaddlePaddle通过异步的方式来组织计算流和通信流的执行顺序，从而避免了同时调用产生的问题。这样可以在保证模型训练的正确性的同时，充分利用计算资源，提高训练的效率。

@niuliling123 非常感谢，看上去像是GPT或文心一言的回复，但没有理解问题

**Comment by AnnaTrainingG** [comment]
您好， 相关文档链接已经补充，可以看一下是否能够解答，补充的内容为内部智能助手回答

**Comment by Aganlengzi** [comment]
> 您好， 相关文档链接已经补充，可以看一下是否能够解答，补充的内容为内部智能助手回答

@niuliling123 实际不能，不是一个问题。

@ForFishes 我理解给了结论：所以原因是CUDA支持两个流并行执行同一通信域的allreduce。请问能麻烦再帮贴下具体文档说明吗？我没找到相关内容

**Comment by ForFishes** [comment]
> > 您好， 相关文档链接已经补充，可以看一下是否能够解答，补充的内容为内部智能助手回答
> 
> @niuliling123 实际不能，不是一个问题。
> 
> @ForFishes 我理解给了结论：所以原因是CUDA支持两个流并行执行同一通信域的allreduce。请问能麻烦再帮贴下具体文档说明吗？我没找到相关内容

是这个原因。多个CudaStream可以使用同一个NCCL comm。
