### ISSUE TITLE
paddle.jit.save使用问题

### ISSUE THREAD

**Issue by anygoanygogo** [PaddlePaddle/Paddle#59776]
### 请提出你的问题 Please ask your question

paddle.jit.save 存储模型时报错
File "/tmp/tmpUnOQzR.py", line 214, in false_fn_0
	for_loop_body_3, [tokens, decoder_outputs,
    UnboundLocalError: local variable 'decoder_outputs' referenced before assignment

但是自查了下，decoder_outputs的定义和使用没有问题， 无法定位到出错的位置

**Comment by ronny1996** [comment]
你好，请问使用的paddle是什么版本？

**Comment by anygoanygogo** [comment]
> 你好，请问使用的paddle是什么版本？

paddle 2.0

**Comment by ronny1996** [comment]
你好，推荐使用最新的paddle尝试下，另外能否贴一下最小可复现的代码？

**Comment by anygoanygogo** [comment]
> 你好，推荐使用最新的paddle尝试下，另外能否贴一下最小可复现的代码？

现在线上有paddle版本要求哈, 

           [next_input, new_maxes, i, j, batch_data, encoder_outputs
                ] = paddle.jit.dy2static.convert_while_loop(
                for_loop_condition_1, for_loop_body_1, [next_input,
                new_maxes, i, j, batch_data, encoder_outputs])
            next_input = paddle.jit.dy2static.convert_call(paddle.stack(
                next_input, axis=0).unsqueeze)(1)
            decoder_input = paddle.concat([decoder_input, next_input], axis=1)
            _ += 1
            return (tokens, decoder_outputs, subset_pt_tensor_mask,
                pt_tensor_mask, batch_data, tgt_mask, generate_variable_1,
                memory_mask, encoder_outputs, decoder_input, _)
        [tokens, decoder_outputs, subset_pt_tensor_mask, pt_tensor_mask,
            batch_data, tgt_mask, decoder_input.shape, memory_mask,
            encoder_outputs, decoder_input, _
            ] = paddle.jit.dy2static.convert_while_loop(for_loop_condition_3,
            for_loop_body_3, [tokens, decoder_outputs,
            subset_pt_tensor_mask, pt_tensor_mask, batch_data, tgt_mask,
            decoder_input.shape, memory_mask, encoder_outputs,
            decoder_input, _])

找到临时文件了， 报错的地方在这里，报错问题是：
File "/tmp/tmpYqKpth.py", line 224, in false_fn_0
	for_loop_body_3, [tokens, decoder_outputs,
    UnboundLocalError: local variable 'decoder_outputs' referenced before assignment

报错的问题也自查了，都是正常的，  train和predict的时候都没问题 ， 就save的时候出了问题

**Comment by ronny1996** [comment]
你好，临时文件可以再贴详细一点吗？原始的代码最好也贴上，可以在临时文件中看下 decoder_outputs 这个变量使用前是否没有赋值，可能是动转静不支持你原始代码中关于 decoder_outputs 的使用
