### ISSUE TITLE
num_channels未定义报错信息

### ISSUE THREAD

**Issue by bit1002lst** [PaddlePaddle/Paddle#5977]
网络定义时，如果第一层**num_channels**不定义，默认为None，输出的报错信息为assert **num_filters** is not None failed

**Comment by huxiaoman7** [comment]
第一层必须要定义吧，后面的如果不定义的话可以自动设定为前一层的输出的feature_map数。

**Comment by bit1002lst** [comment]
嗯，我的意思是第一层不定义的话给的报错信息不对
