### ISSUE TITLE
提交

### ISSUE THREAD

**Issue by PaulX1029** [PaddlePaddle/Paddle#59795]
### 问题描述 Please describe your issue

【提交】：2
【AI Studio uid】：2258715
【作品链接】：影视人物对话器【摇摇乐】
项目链接：https://aistudio.baidu.com/projectdetail/7215279
应用连接：https://aistudio.baidu.com/application/detail/12051

**Comment by Ligoml** [comment]
在这个issue下回复哈：https://github.com/PaddlePaddle/Paddle/issues/57585
