### ISSUE TITLE
paddle.cumsum api在计算较大tensor时精度问题

### ISSUE THREAD

**Issue by shengkelongshulong** [PaddlePaddle/Paddle#59803]
bug描述 Describe the Bug

主要当使用gpu时，paddle.cumsum的计算误差非常大，cpu则没有这个问题，代码如下
```
import paddle
import numpy as np
paddle.device.set_device("gpu")
a = paddle.rand([10000,500,3])

b = paddle.cumsum(a, axis=1)[:,-1,:]
c = a.sum(1)
print(b-c)
```

![image](https://github.com/PaddlePaddle/Paddle/assets/42399199/ceea6d09-bcb6-4965-bc19-d8bd32ba9237)
![image](https://github.com/PaddlePaddle/Paddle/assets/42399199/a0c0711d-c79d-4e61-b0cd-b6b92cd71257)

**Comment by ronny1996** [comment]
你好，这个问题我反馈一下，也可以使用 np.testing.assert_allclose 看一下相对误差是多少
