### ISSUE TITLE
cmake编译报错 cannot import name 'attr_types_map' from 'op_gen' 

### ISSUE THREAD

**Issue by shirwy** [PaddlePaddle/Paddle#59818]
### bug描述 Describe the Bug

(py39) λ bms-98e4 /workspace/Paddle/build {develop} cmake .. -DPY_VERSION=3.9 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_DISTRIBUTE=ON -DWITH_PSCORE=OFF -DWITH_TESTING=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DWITH_CUSTOM_DEVICE=ON -DWITH_ASCEND_INT64=ON
CMake Deprecation Warning at CMakeLists.txt:25 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

-- Found Paddle host system: ubuntu, version: 18.04.6
-- Found Paddle host system's CPU: 192 cores
EXP_CUDA_MODULE_LOADING_LAZY only works with GPU
-- CXX compiler: /opt/compiler/gcc-8.2/bin/c++, version: GNU 8.2.0
-- C compiler: /opt/compiler/gcc-8.2/bin/gcc, version: GNU 8.2.0
-- AR tools: /usr/bin/ar
-- ccache is founded, use ccache to speed up compile on Unix.
ccache version                      3.7
cache directory                     /root/.ccache
primary config                      /root/.ccache/ccache.conf
secondary config      (readonly)    /usr/local/ccache-3.7.9/etc/ccache.conf
cache hit (direct)                     0
cache hit (preprocessed)               0
cache miss                             0
cache hit rate                      0.00 %
cleanups performed                     0
files in cache                         0
cache size                           0.0 kB
max cache size                       5.0 GB

-- Check submodules of paddle, and run 'git submodule update --init --recursive'
-- Do not have AVX2 intrinsics and disabled MKL-DNN.
-- warp-ctc library: /workspace/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- warp-rnnt library: /workspace/Paddle/build/third_party/install/warprnnt/lib/libwarprnnt.so
-- Build OpenBLAS by External Project (include: /workspace/Paddle/build/third_party/install/openblas/include, library: /workspace/Paddle/build/third_party/install/openblas/lib/libopenblas.a)
-- CBLAS_PROVIDER: EXTERN_OPENBLAS
CMake Warning at /opt/cmake-3.19/share/cmake-3.19/Modules/FindProtobuf.cmake:502 (message):
  Protobuf compiler version doesn't match library version 3.0.0
Call Stack (most recent call first):
  cmake/external/protobuf.cmake:18 (find_package)
  cmake/third_party.cmake:370 (include)
  CMakeLists.txt:583 (include)

-- Protobuf protoc executable: /workspace/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf-lite library: /workspace/Paddle/build/third_party/install/protobuf/lib/libprotobuf-lite.a
-- Protobuf library: /workspace/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protoc library: /workspace/Paddle/build/third_party/install/protobuf/lib/libprotoc.a
-- Protobuf version: 21.12
-- Found PythonInterp: /opt/py39/bin/python3 (found suitable version "3.9.17", minimum required is "3.9")
-- Found PythonLibs: /usr/local/lib/libpython3.9.so (found suitable version "3.9.17", minimum required is "3.9")
CMake Deprecation Warning at cmake/FindNumPy.cmake:6 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
  cmake/external/python.cmake:76 (find_package)
  cmake/third_party.cmake:376 (include)
  CMakeLists.txt:583 (include)

-- ssl:/usr/lib/aarch64-linux-gnu/libssl.so
-- crypto:/usr/lib/aarch64-linux-gnu/libcrypto.so
POCKETFFT_INCLUDE_DIR is /workspace/Paddle/build/third_party/pocketfft/src
-- Paddle version is 0.0.0
-- On inference mode, will take place some specific optimization.
Requirement already satisfied: pyyaml in /opt/py39/lib/python3.9/site-packages (6.0.1)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: pip install --upgrade pip
create or copy auto-geneated tensor files
copy if different /workspace/Paddle/paddle/phi/api/include/operants_base.h.tmp /workspace/Paddle/paddle/phi/api/include/operants_base.h
copy if different /workspace/Paddle/paddle/phi/api/lib/tensor_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/tensor_api.cc
copy if different /workspace/Paddle/paddle/phi/api/include/tensor_operants.h.tmp /workspace/Paddle/paddle/phi/api/include/tensor_operants.h
copy if different /workspace/Paddle/paddle/phi/api/lib/tensor_operants.cc.tmp /workspace/Paddle/paddle/phi/api/lib/tensor_operants.cc
copy if different /workspace/Paddle/paddle/phi/api/include/operants_manager.h.tmp /workspace/Paddle/paddle/phi/api/include/operants_manager.h
copy if different /workspace/Paddle/paddle/phi/api/lib/operants_manager.cc.tmp /workspace/Paddle/paddle/phi/api/lib/operants_manager.cc
copy if different /workspace/Paddle/paddle/phi/api/lib/api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/api.cc
copy if different /workspace/Paddle/paddle/phi/api/include/api.h.tmp /workspace/Paddle/paddle/phi/api/include/api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/backward_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/backward_api.cc
copy if different /workspace/Paddle/paddle/phi/api/backward/backward_api.h.tmp /workspace/Paddle/paddle/phi/api/backward/backward_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/fused_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/fused_api.cc
copy if different /workspace/Paddle/paddle/phi/api/include/fused_api.h.tmp /workspace/Paddle/paddle/phi/api/include/fused_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/fused_backward_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/fused_backward_api.cc
copy if different /workspace/Paddle/paddle/phi/api/backward/fused_backward_api.h.tmp /workspace/Paddle/paddle/phi/api/backward/fused_backward_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/sparse_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/sparse_api.cc
copy if different /workspace/Paddle/paddle/phi/api/include/sparse_api.h.tmp /workspace/Paddle/paddle/phi/api/include/sparse_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/sparse_bw_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/sparse_bw_api.cc
copy if different /workspace/Paddle/paddle/phi/api/backward/sparse_bw_api.h.tmp /workspace/Paddle/paddle/phi/api/backward/sparse_bw_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/dygraph_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/dygraph_api.cc
copy if different /workspace/Paddle/paddle/phi/api/lib/dygraph_api.h.tmp /workspace/Paddle/paddle/phi/api/lib/dygraph_api.h
copy if different /workspace/Paddle/paddle/phi/api/lib/strings_api.cc.tmp /workspace/Paddle/paddle/phi/api/lib/strings_api.cc
copy if different /workspace/Paddle/paddle/phi/api/include/strings_api.h.tmp /workspace/Paddle/paddle/phi/api/include/strings_api.h
-- Copy generated python ps_pb2.py into directory /workspace/Paddle/python/paddle/incubate/distributed/fleet/parameter_server/pslib/
-- commit: 93e627736d
-- branch: develop
/opt/py39/lib/python3.9/site-packages/yaml
/opt/py39/lib/python3.9/site-packages/jinja2
/opt/py39/lib/python3.9/site-packages/typing_extensions.py
parse op yamls:
- /workspace/Paddle/paddle/phi/api/yaml/ops.yaml
- /workspace/Paddle/paddle/phi/api/yaml/legacy_ops.yaml
- /workspace/Paddle/paddle/phi/api/yaml/backward.yaml
- /workspace/Paddle/paddle/phi/api/yaml/legacy_backward.yaml
- /workspace/Paddle/paddle/phi/api/yaml/fused_ops.yaml
- /workspace/Paddle/paddle/phi/api/yaml/static_ops.yaml
validate op yaml:
- /workspace/Paddle/paddle/fluid/operators/generator/parsed_ops/ops.parsed.yaml
- /workspace/Paddle/paddle/fluid/operators/generator/parsed_ops/backward_ops.parsed.yaml
create or remove auto-geneated operators: generated_op(1-4).cc.tmp
create or remove auto-geneated argument mappings: /workspace/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp
copy if different /workspace/Paddle/paddle/fluid/operators/generated_op1.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_op1.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_op2.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_op2.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_op3.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_op3.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_op4.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_op4.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_static_op.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_static_op.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_fused_op.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_fused_op.cc
copy if different /workspace/Paddle/paddle/fluid/operators/generated_sparse_op.cc.tmp /workspace/Paddle/paddle/fluid/operators/generated_sparse_op.cc
copy if different /workspace/Paddle/paddle/phi/ops/compat/generated_sig.cc.tmp /workspace/Paddle/paddle/phi/ops/compat/generated_sig.cc
copy if different /workspace/Paddle/paddle/phi/ops/compat/generated_static_sig.cc.tmp /workspace/Paddle/paddle/phi/ops/compat/generated_static_sig.cc
copy if different /workspace/Paddle/paddle/phi/ops/compat/generated_sparse_sig.cc.tmp /workspace/Paddle/paddle/phi/ops/compat/generated_sparse_sig.cc
copy if different /workspace/Paddle/paddle/phi/ops/compat/generated_fused_sig.cc.tmp /workspace/Paddle/paddle/phi/ops/compat/generated_fused_sig.cc
generate /workspace/Paddle/paddle/fluid/operators/ops_extra_info.cc
Performing Eager Dygraph Auto Code Generation
Final State Eager CodeGen
Generate dygraph file structure at path: /workspace/Paddle/paddle/fluid/eager/generated
Eager prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Static prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Prim tensor operants code generator
copy prim xxx_tensor_operants.tmp to xxx_tensor_operants
copy if different /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op.h.tmp /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op.h
copy if different /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op.cc.tmp /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op.cc
copy if different /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op_vjp.cc.tmp /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_op_vjp.cc
copy if different /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_api.h.tmp /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_api.h
copy if different /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_api.cc.tmp /workspace/Paddle/paddle/fluid/pir/dialect/operator/ir/pd_api.cc
copy if different /workspace/Paddle/paddle/fluid/pybind/static_op_function.h.tmp /workspace/Paddle/paddle/fluid/pybind/static_op_function.h
copy if different /workspace/Paddle/paddle/fluid/pybind/static_op_function.cc.tmp /workspace/Paddle/paddle/fluid/pybind/static_op_function.cc
copy if different /workspace/Paddle/paddle/fluid/pybind/ops_api.cc.tmp /workspace/Paddle/paddle/fluid/pybind/ops_api.cc
Automatic code generation for paddle/fluid/primitive
Automatic code generation for paddle/fluid/primitive succeed.
Traceback (most recent call last):
  File "/workspace/Paddle/paddle/fluid/primitive/codegen/decomp_gen.py", line 43, in <module>
    from op_gen import attr_types_map, to_pascal_case
ImportError: cannot import name 'attr_types_map' from 'op_gen' (/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/op_gen/__init__.py)
CMake Error at paddle/fluid/primitive/codegen/CMakeLists.txt:48 (message):
  Automatic code generation for
  build/paddle/fluid/pir/dialect/operator/ir/op_decomp.cc failed.

-- Configuring incomplete, errors occurred!
See also "/workspace/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/workspace/Paddle/build/CMakeFiles/CMakeError.log".

**Comment by ZzSean** [comment]
你好，请问是在编译昇腾的时候报的错么？可以参考下这里的编译选项https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html#anzhuangfangshi-tongguoyuanmabianyianzhuang，
```
cmake .. -DPY_VERSION=3.9 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON \
         -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
```

**Comment by shirwy** [comment]
> 你好，请问是在编译昇腾的时候报的错么？可以参考下这里的编译选项[https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html#anzhuangfangshi-tongguoyuanmabianyianzhuang，](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html#anzhuangfangshi-tongguoyuanmabianyianzhuang%EF%BC%8C)
> 
> ```
> cmake .. -DPY_VERSION=3.9 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON \
>          -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
>          -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
> ```
这个方法可以在cann6.0.1上执行吗，在6.0.1上还是有同样的报错
Traceback (most recent call last):
  File "/workspace/Paddle/paddle/fluid/primitive/codegen/decomp_gen.py", line 43, in <module>
    from op_gen import attr_types_map, to_pascal_case
ImportError: cannot import name 'attr_types_map' from 'op_gen' (/usr/local/Ascend/ascend-toolkit/latest/python/site-packages/op_gen/__init__.py)

**Comment by ZzSean** [comment]
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md，试试这里的安装方法？

**Comment by qili93** [comment]
您好，这个错误是由于 CANN 的 PYTHON PATH 下已经存在一个op_gen.py，和Paddle源码中的op_gen.py冲突导致的，建议您这里编译CPU安装包的时候使用纯CPU的基础镜像进行编译来避免 op_gen的冲突。

可以参考如下命令启动纯CPU的镜像来编译Paddle Paddle的CPU安装包

docker run -it --name paddle-dev-cpu -v `pwd`:/workspace \
     --network=host --shm-size=128G --workdir=/workspace \
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
     registry.baidubce.com/device/paddle-cpu:ubuntu18-$(uname -m)-gcc82 /bin/bash

cmake 命令参考

cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON \
  -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=ON

**Comment by shirwy** [comment]
> 您好，这个错误是由于 CANN 的 PYTHON PATH 下已经存在一个op_gen.py，和Paddle源码中的op_gen.py冲突导致的，建议您这里编译CPU安装包的时候使用纯CPU的基础镜像进行编译来避免 op_gen的冲突。
> 
> 可以参考如下命令启动纯CPU的镜像来编译Paddle Paddle的CPU安装包
> 
> docker run -it --name paddle-dev-cpu -v `pwd`:/workspace --network=host --shm-size=128G --workdir=/workspace --cap-add=SYS_PTRACE --security-opt seccomp=unconfined registry.baidubce.com/device/paddle-cpu:ubuntu18-$(uname -m)-gcc82 /bin/bash
> 
> cmake 命令参考
> 
> cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=ON -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=ON


==============================================================

感谢，cmake通过了，但是按照https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/npu_docs/paddle_install_cn.html
指导执行make TARGET=ARMV8 -j$(nproc)后报错：
(py39) λ bms-98e4 /workspace/Paddle/build {develop} make TARGET=ARMV8 -j$(nproc)                                      [  0%] Performing install step for 'extern_zlib'
[  0%] copy_if_different /workspace/Paddle/build/paddle/fluid/operators/ops_signature/signatures.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/fluid/inference/api/paddle_inference_pass.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/funcs/jit/kernels.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/phi/kernels/declarations.h
[  0%] copy_if_different /workspace/Paddle/build/paddle/fluid/pybind/pybind.h
[  0%] Built target extern_gflags
[  1%] Built target extern_eigen3
[  1%] Built target extern_threadpool
[  1%] Built target extern_warpctc
[  1%] Built target extern_dlpack
[  3%] Built target extern_utf8proc
[  3%] Built target extern_lapack
[  3%] Built target extern_warprnnt
[  3%] Built target extern_openblas
[  3%] Built target extern_xbyak
[  3%] Built target extern_gloo
[  3%] Built target extern_pocketfft
[  3%] Built target extern_cryptopp
[  3%] Built target extern_pybind
[  3%] Built target copy_kernels_command
[  3%] Built target copy_paddle_inference_pass_command
[  3%] Built target copy_declarations_command
[  3%] Built target copy_signatures_command
[  3%] Built target copy_pybind_command
[  3%] Built target ops_api_gen
[  3%] Built target ps_py_proto_init
[  3%] Creating directories for 'extern_glog'
[  3%] Built target fleet_proto_init
make[5]: Warning: File '/opt/compiler/gcc-8.2/lib/gcc/aarch64-unknown-linux-gnu/8.2.0/include-fixed/limits.h' has modification time 2342702 s in the future
make[5]: Warning: File '/opt/compiler/gcc-8.2/lib/gcc/aarch64-unknown-linux-gnu/8.2.0/include-fixed/limits.h' has modification time 2342702 s in the future
[  3%] No download step for 'extern_glog'
[ 10%] Building C object CMakeFiles/zlibstatic.dir/compress.o
[ 10%] Building C object CMakeFiles/zlib.dir/adler32.o
[ 10%] Building C object CMakeFiles/zlib.dir/compress.o
[ 10%] Building C object CMakeFiles/zlibstatic.dir/adler32.o
[ 15%] Building C object CMakeFiles/zlib.dir/crc32.o
[ 15%] Building C object CMakeFiles/zlibstatic.dir/crc32.o
[ 25%] Building C object CMakeFiles/zlib.dir/deflate.o
[ 25%] Building C object CMakeFiles/zlibstatic.dir/deflate.o
[ 25%] Building C object CMakeFiles/zlib.dir/gzclose.o
[ 25%] Building C object CMakeFiles/zlibstatic.dir/gzclose.o
[ 32%] Building C object CMakeFiles/zlib.dir/gzlib.o
[ 32%] Building C object CMakeFiles/zlib.dir/gzwrite.o
[ 32%] Building C object CMakeFiles/zlibstatic.dir/gzread.o
[ 35%] Building C object CMakeFiles/zlib.dir/gzread.o
[ 42%] Building C object CMakeFiles/zlibstatic.dir/inflate.o
[ 42%] Building C object CMakeFiles/zlibstatic.dir/gzwrite.o
[ 42%] Building C object CMakeFiles/zlibstatic.dir/gzlib.o
[ 50%] Building C object CMakeFiles/zlib.dir/inflate.o
[ 52%] Building C object CMakeFiles/zlibstatic.dir/infback.o
[ 52%] Building C object CMakeFiles/zlib.dir/infback.o
[ 52%] Building C object CMakeFiles/zlib.dir/inftrees.o
[ 57%] Building C object CMakeFiles/zlibstatic.dir/inftrees.o
[ 57%] Building C object CMakeFiles/zlibstatic.dir/inffast.o
[ 60%] Building C object CMakeFiles/zlib.dir/trees.o
[ 62%] Building C object CMakeFiles/zlibstatic.dir/zutil.o
[ 72%] Building C object CMakeFiles/zlibstatic.dir/trees.o
[ 72%] Building C object CMakeFiles/zlib.dir/zutil.o
[ 72%] Building C object CMakeFiles/zlib.dir/inffast.o
[ 72%] Building C object CMakeFiles/zlib.dir/uncompr.o
[ 75%] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
[  3%] No update step for 'extern_glog'
[  3%] No patch step for 'extern_glog'
[  3%] Performing configure step for 'extern_glog'
[ 77%] Linking C static library libz.a
[ 80%] Linking C shared library libz.so
/usr/bin/ranlib: error while loading shared libraries: libz.so.1: file too short
CMakeFiles/zlibstatic.dir/build.make:320: recipe for target 'libz.a' failed
make[5]: *** [libz.a] Error 127
make[5]: *** Deleting file 'libz.a'
CMakeFiles/Makefile2:118: recipe for target 'CMakeFiles/zlibstatic.dir/all' failed
make[4]: *** [CMakeFiles/zlibstatic.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
make[5]: warning:  Clock skew detected.  Your build may be incomplete.
[ 80%] Built target zlib
Makefile:145: recipe for target 'all' failed
make[3]: *** [all] Error 2
CMakeFiles/extern_zlib.dir/build.make:103: recipe for target 'third_party/zlib/src/extern_zlib-stamp/extern_zlib-install' failed
make[2]: *** [third_party/zlib/src/extern_zlib-stamp/extern_zlib-install] Error 2
CMakeFiles/Makefile2:3865: recipe for target 'CMakeFiles/extern_zlib.dir/all' failed
make[1]: *** [CMakeFiles/extern_zlib.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  3%] Built target eager_python_c_codegen
[  3%] Built target op_map_codegen
[  3%] Built target eager_codegen
-- extern_glog configure command succeeded.  See also /workspace/Paddle/build/third_party/glog/src/extern_glog-stamp/extern_glog-configure-*.log
[  3%] Performing build step for 'extern_glog'
[ 25%] Building CXX object CMakeFiles/glog.dir/src/logging.cc.o
[ 25%] Building CXX object CMakeFiles/glog.dir/src/demangle.cc.o
[ 37%] Building CXX object CMakeFiles/glog.dir/src/raw_logging.cc.o
[ 50%] Building CXX object CMakeFiles/glog.dir/src/symbolize.cc.o
[ 62%] Building CXX object CMakeFiles/glog.dir/src/utilities.cc.o
[ 75%] Building CXX object CMakeFiles/glog.dir/src/vlog_is_on.cc.o
[ 87%] Building CXX object CMakeFiles/glog.dir/src/signalhandler.cc.o
[100%] Linking CXX static library libglog.a
[100%] Built target glog
[  3%] Performing install step for 'extern_glog'
-- extern_glog install command succeeded.  See also /workspace/Paddle/build/third_party/glog/src/extern_glog-stamp/extern_glog-install-*.log
[  3%] Completed 'extern_glog'
[  3%] Built target extern_glog
Makefile:135: recipe for target 'all' failed
make: *** [all] Error 2
(py39) λ bms-98e4 /workspace/Paddle/build {develop}
