### ISSUE TITLE
hardsigmoid 文档中计算公式是否存在问题

### ISSUE THREAD

**Issue by songh11** [PaddlePaddle/Paddle#59824]
### 文档链接&描述 Document Links & Description

文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/functional/hardsigmoid_cn.html#hardsigmoid
问题描述：按照公式计算，如果传入 slope 和 offset 的话，结果存在小于 0 和大于 1 的情况，但结果在 0 和 1 中间，与公式不符

**Comment by ZzSean** [comment]
能否贴出具体的测试结果？hard_sigmoid是有不同的实现方式，所以传入的slope和offset应该严格和x的范围相关，即需要保证x在某个区间的边界处，在官方文档中就是-3和3处，能够得到0和1的计算结果。所以当你传入自定义的slope和offset时，官方文档中的[-3,3]就不再完全适用了。真正比较通用的公式应该是`y = max(0, min(1, slope * x + offset))`

**Comment by songh11** [comment]
> 能否贴出具体的测试结果？hard_sigmoid是有不同的实现方式，所以传入的slope和offset应该严格和x的范围相关，即需要保证x在某个区间的边界处，在官方文档中就是-3和3处，能够得到0和1的计算结果。所以当你传入自定义的slope和offset时，官方文档中的[-3,3]就不再完全适用了。真正比较通用的公式应该是`y = max(0, min(1, slope * x + offset))`

感谢回复，那文档确实不适用自定义 slope 和 offset 的情况
