### ISSUE TITLE
请问下`setup.py`和`setup.py.in`分别是做什么的呢

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#59845]
### 请提出你的问题 Please ask your question

在PaddlePaddle的repo里面，有一个根目录下的`setup.py`，此外还有一个`python/setup.py.in`。
这两个文件有若干内容和函数是一样的，或者说是极为接近的，例如，都有函数叫做`get_cuda_version`和`get_cudnn_version`，并且看起来功能也是一样的，实现也很接近。
所以想问一下，这两个都叫setup，功能和区别是什么？以及，我想增加新的函数，例如，`get_my_new_dependency_version`这种，是需要往两个文件里面都加吗？

**Comment by ZzSean** [comment]
你好，这两个文件都是用来负责安装paddle的，`setup.py`是用来`python setup.py install`的，另一个是用来cmake源码编译的，两者需要同步改动
