### ISSUE TITLE
是否支持使用自注册的HostAlloc以差异化申请host memory

### ISSUE THREAD

**Issue by EnflameGCU** [PaddlePaddle/Paddle#59846]
### 请提出你的问题 Please ask your question

对应于GPU版本可以使用cudaHostAlloc来申请host memory，我们注意到PaddleCustomDevice注册进来的host_memory_allocate接口在主框架中却并没有流程使用（包括dev_ctx.template HostAlloc<T> 方式），请问下是否支持使用自注册的HostAlloc，当前不支持是基于什么考虑或者后续是否有计划支持？

**Comment by ronny1996** [comment]
你好，目前没有支持host_memory_allocate，host_memory_allocate主要是为了某些硬件需要host侧的锁页内存才能进行h2d的拷贝而准备的，当前如果也有这种需求，可以参考npu在插件侧实现
