### ISSUE TITLE
Python3.7 退场的一些工作汇总

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#59874]
## paddle仓库:

前序工作: 
* #59680 
* #59871

### 代码退场: 
  - [x]  `dockerfile`文件以及对应生成脚本，可以顺带补充 py3.11 和 py3.12 (#59877)
  - [x]  `paddle/scripts/paddle_build.sh`以及一些编译类的脚本 (#59876)
  - [x]   一些注释以及readme (#59875)

### CodeStyle
- [x]  ruff 默认版本提升(#60001)
https://github.com/PaddlePaddle/Paddle/blob/5a3c593f38ed79662a91e0650e1b453f8b5a17d6/pyproject.toml#L18

- [x]  ~~black 升级，需要注意可以升级的 python 最低版本~~ 待 black 24 发布后一起升级
https://github.com/PaddlePaddle/Paddle/blob/5a3c593f38ed79662a91e0650e1b453f8b5a17d6/.pre-commit-config.yaml#L55

## docs仓库:

- [x] ~~CI 运行 shell 文件~~
- [x] docs 文档内容部分 (https://github.com/PaddlePaddle/docs/pull/6458)
- [x] ~~ipynb 文档部分~~

欢迎大家补充

**Comment by zrr1999** [comment]
在 `https://github.com/pre-commit/pre-commit-hooks` 里添加 `debug-statements` hook 可以拦截不支持的语法

**Comment by gouzil** [comment]
> 在 `https://github.com/pre-commit/pre-commit-hooks` 里添加 `debug-statements` hook 可以拦截不支持的语法

记录一下我们的讨论结果：
`debug-statements`主要的功能是拦截`pdb`, `breakpoint()`这类 Debugger 函数方法
* 这点增加了 ruff 的`T100` 规则进行拦截 #60243

关于拦截不支持的语法，通过查看源码发现是通过 python 原生的 ast 实现的

* 如果想要使用这个特性需要满足2个条件: 
* 1. 安装 `pre-commit` 的 python 版本为所支持的最低版本(也就是现在的 python3.8 )
* 2. 需要控制 ci 中的 python 版本（目前外部开发没有权限）

相关链接：
* `debug-statements`源码：https://github.com/pre-commit/pre-commit-hooks/blob/42bc79146f8b566f640ff773057d48a9416763a7/pre_commit_hooks/debug_statement_hook.py#L4

对拦截不支持的语法简单实现：#60279
