### ISSUE TITLE
官方win c++推理库运行0xC000007B

### ISSUE THREAD

**Issue by Synmul** [PaddlePaddle/Paddle#59870]
用LoadLibrary()   lasterror是193
![2](https://github.com/PaddlePaddle/Paddle/assets/50161120/04ecbbb1-54ba-46b0-bb58-dd15c1c01671)

用工具看了一下不知准不准   显示大约500个dll找不到
![3](https://github.com/PaddlePaddle/Paddle/assets/50161120/0ba8e77c-6347-4617-9bbf-bea5ac0e5970)

**Comment by MARD1NO** [comment]
> 用LoadLibrary() lasterror是193 ![2](https://private-user-images.githubusercontent.com/50161120/289289256-04ecbbb1-54ba-46b0-bb58-dd15c1c01671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjU4NjIsIm5iZiI6MTcwMjI2NTU2MiwicGF0aCI6Ii81MDE2MTEyMC8yODkyODkyNTYtMDRlY2JiYjEtNTRiYS00NmIwLWJiNTgtZGQxNWMxYzAxNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NGZkOTAyNjBmNmY5ODEyOWMyNmVlZDcyNGJjYzAwYThkYmU2NjJkMTM0NGU4YTNjOWFjMDY0NDU5MDk2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sYzP4YGAgfK7XrlIq6ZN4Vb7GMe5JYywhwB-nvx7CwE)
> 
> 用工具看了一下不知准不准 显示大约500个dll找不到 ![3](https://private-user-images.githubusercontent.com/50161120/289289376-0ba8e77c-6347-4617-9bbf-bea5ac0e5970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjU4NjIsIm5iZiI6MTcwMjI2NTU2MiwicGF0aCI6Ii81MDE2MTEyMC8yODkyODkzNzYtMGJhOGU3N2MtNjM0Ny00NjE3LTliYmYtYmVhNWFjMGU1OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNGM0NDA0MWNmOGY2YTdjOTAwZjFlYzZhOGVkMTYwNjdhYzg1ZGM5Y2ViNmMwNTYyNzA5NTBiNmVlNjI1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwihPaJfdY4V6pZnb3E9UGLREyAXNF_ZZR3YP4Xgzz4)

可以先尝试排查下自身环境的问题，或者尝试用更新版本如2.5的预测库

**Comment by Synmul** [comment]
> > 用LoadLibrary() lasterror是193 ![2](https://private-user-images.githubusercontent.com/50161120/289289256-04ecbbb1-54ba-46b0-bb58-dd15c1c01671.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjU4NjIsIm5iZiI6MTcwMjI2NTU2MiwicGF0aCI6Ii81MDE2MTEyMC8yODkyODkyNTYtMDRlY2JiYjEtNTRiYS00NmIwLWJiNTgtZGQxNWMxYzAxNjcxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM4NGZkOTAyNjBmNmY5ODEyOWMyNmVlZDcyNGJjYzAwYThkYmU2NjJkMTM0NGU4YTNjOWFjMDY0NDU5MDk2OTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sYzP4YGAgfK7XrlIq6ZN4Vb7GMe5JYywhwB-nvx7CwE)
> > 用工具看了一下不知准不准 显示大约500个dll找不到 ![3](https://private-user-images.githubusercontent.com/50161120/289289376-0ba8e77c-6347-4617-9bbf-bea5ac0e5970.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIyNjU4NjIsIm5iZiI6MTcwMjI2NTU2MiwicGF0aCI6Ii81MDE2MTEyMC8yODkyODkzNzYtMGJhOGU3N2MtNjM0Ny00NjE3LTliYmYtYmVhNWFjMGU1OTcwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDAzMzI0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjNGM0NDA0MWNmOGY2YTdjOTAwZjFlYzZhOGVkMTYwNjdhYzg1ZGM5Y2ViNmMwNTYyNzA5NTBiNmVlNjI1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HwihPaJfdY4V6pZnb3E9UGLREyAXNF_ZZR3YP4Xgzz4)
> 
> 可以先尝试排查下自身环境的问题，或者尝试用更新版本如2.5的预测库

我用了好几次官方编译的库，也按照页面上的要求配置好环境，每次都是一样的原因不能用，非得要自己编译才可以，太费时间了，从上午10点编译到现在15:30还没结束
