### ISSUE TITLE
Spp Operator.

### ISSUE THREAD

**Issue by sweetsky0901** [PaddlePaddle/Paddle#5988]
- [SpatialPyramidPoolLayer.cpp](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/SpatialPyramidPoolLayer.cpp)
- [spp api](http://doc.paddlepaddle.org/develop/doc/api/v2/config/layer.html#spp)

**Comment by wangkuiyi** [comment]
In the first comment of PR #6204 , you need to write "fix #5988" instead of just "#5988".  Due to the wrong note, this issue was not closed by Github automatically when the PR is merged.
