### ISSUE TITLE
集群是否可以进行predict

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#599]
集群版demo中只有任务提交的例子，单机版的demo提供了predict.sh的demo，但在数据量很大的情况下单机版执行predict.sh会很慢，不知道mpi版本是否可以执行类似demo中的predict.sh的操作呢

**Comment by backyes** [comment]
predict 过程是一个高度可并行的过程，因此你可以将predict封装为一个mpi任务、一个spark任务，甚至一个特殊的hadoop任务， 例如

一个mpi封装：
```
mpirun download.sh # download several data
mpirun predict.sh  #do predict 
```
原理上，就像实现一个多机word count 一样的逻辑。

目前，paddle官方未维护多机predict平台。

**Comment by 333caowei** [comment]
@backyes 集群训练时候需要将train文件分割，mpi文件粒度并行，请问predict的执行过程是否需要将test文件也进行分割呢

**Comment by backyes** [comment]
@333caowei 
理论上要的。简单理解， predict过程就是一个forward获取output 激活的过程，所以你想要的结果一定是不同样本对应的不同的输出，所以你并行跑的predict的时候，也应该是不同并发任务运行不同的样本数据part，否则就没有意义了。

**Comment by hphp** [comment]
@333caowei  hi, caowei~ 我提供一下我的方法哈，正如backyes所说，prediction的过程应该是可高度并行的，所以大数据量时，我直接在hadoop集群上进行prediction，只需要将相应的依赖（包括库和predict及相应conf）上传即可，非常方便~
