### ISSUE TITLE
Dataloader segmentation fault in static graph

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#59937]
### bug描述 Describe the Bug

在静态图中，当collate_fn返回的是tensor而不是np array的时候，dataloader会报错。而动态图中都不会出错。
比如把下面这个collate_fn加入到[test_multiprocess_dataloader_static.py](https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_multiprocess_dataloader_static.py)这个单测中，并且设置dataloader的use_shared_memory=False：
```python
def collate_batch(batch_list):
    batch_size = len(batch_list)
    image = np.stack([item[0] for item in batch_list], axis=0).astype('float32')
    image = paddle.to_tensor(image).reshape([batch_size, -1])
    label = np.stack([item[1] for item in batch_list], axis=0).astype('int64')
    label = paddle.to_tensor(label).reshape([batch_size, -1])
    return image, label
```
就会报下面的错误：
```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::TensorInit(_object*, _object*, _object*)

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1702371369 (unix time) try "date -d @1702371369" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x20) received by PID 42357 (TID 0x7f94a37f9640) from PID 32 ***]

Segmentation fault (core dumped)
```

**Comment by ForFishes** [comment]
您好，这个静态图不支持paddle.tensor的数据类型，作为静态图的输入。

**Comment by Wong4j** [comment]
> 您好，这个静态图不支持paddle.tensor的数据类型，作为静态图的输入。

感谢回复。我有几个问题
1. dataloader是框架设计上就不考虑paddle.tensor作为静态图输入吗？还是说暂未支持，或者说静态图的相关功能已经不再维护，因为我有类似的代码在paddle 2.4都是可以跑的，2.5和develop会出问题。
2. 我有一个基于paddle dataloader开发的 [LDDL](https://github.com/NVIDIA/LDDL/blob/main/lddl/paddle/bert.py#L137-L147)，collate_fn返回的都是tensor类型，这个代码会用于动态图和静态图，在paddle 2.4没问题，2.5之后会出问题，对此你们有什么建议吗？应该全部改写成numpy array吗？

**Comment by Wong4j** [comment]
I have found a workaround，close this issue
