### ISSUE TITLE
CPU下加速库MKLDNN计划遗弃吗？

### ISSUE THREAD

**Issue by raoyutian** [PaddlePaddle/Paddle#59964]
### 请提出你的问题 Please ask your question

最近的的版本看代码MKLDNN被修改成ONEDNN，但都被条件编译隔离了，也没有相关参数或者配置。
一堆的#ifdef PADDLE_WITH_DNNL，也没有编译开关。
自从2.4.2以后的预测库，OCR就就没有可以正常使用的版本。
想了解下，飞桨对MKLDNN的修改计划，是放弃该加速库，还是未来哪个版本完善可以用？

**Comment by JZ-LIANG** [comment]
并没有，内部正在设计 ONEDNN 的适配方案，后续会用统一的 ONEDNN 提供

**Comment by raoyutian** [comment]
> 并没有，内部正在设计 ONEDNN 的适配方案，后续会用统一的 ONEDNN 提供

预计哪个版本可以提供使用呢？2.6版本会不会提供？
