### ISSUE TITLE
No stack trace in paddle, may be caused by external reasons. 

### ISSUE THREAD

**Issue by ZS-YANG** [PaddlePaddle/Paddle#59983]
### Bug描述 Describe the Bug

复现步骤:

下载cityscapesScripts数据集，使用

```
python tools/data/convert_cityscapes.py
``` 

转换数据集，更改

```
configs/_base_/cityscapes.yml
```

开始训练

```
python tools/train.py        --config configs/deeplabv3/deeplabv3_resnet50_os8_cityscapes_1024x512_80k.yml        --save_interval 500        --do_eval         --save_dir output_pid
```

报错内容

```
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
No stack trace in paddle, may be caused by external reasons.

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1702453676 (unix time) try "date -d @1702453676" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x0) received by PID 35373 (TID 0x7f0a2f217700) from PID 0 ***]

Segmentation fault (core dumped)
```

### 复现环境 Environment

Linux
paddlepaddle-gpu    0.0.0.post102
paddleseg           0.0.0.dev0   
python 3.8
Cuda10.2

**Comment by ZS-YANG** [comment]
https://github.com/PaddlePaddle/PaddleSeg/issues/3596

**Comment by ZS-YANG** [comment]
@JZ-LIANG 
报错的有
configs/deeplabv3/deeplabv3_resnet50_os8_cityscapes_1024x512_80k.yml
configs/unet/unet_cityscapes_1024x512_160k.yml
configs/u2net/u2net_cityscapes_1024x512_160k.yml
configs/unet_plusplus/unet_plusplus_cityscapes_1024x512_160k.yml

不报错的有
configs/deeplabv3p/deeplabv3p_resnet50_os8_cityscapes_1024x512_80k.yml 
configs/pp_liteseg/pp_liteseg_stdc2_cityscapes_1024x512_scale0.5_160k.yml
configs/ocrnet/ocrnet_hrnetw18_cityscapes_1024x512_160k.yml
configs/fcn/fcn_hrnetw18_cityscapes_1024x512_80k.yml
configs/mobileseg/mobileseg_ghostnet_cityscapes_1024x512_80k.yml
configs/u2net/u2netp_cityscapes_1024x512_160k.yml

**Comment by JZ-LIANG** [comment]
deeplabv3 套件更换数据集问题，部分数据集预处理 segment fault 报错，预处理逻辑存在问题

请使用自带数据集
