### ISSUE TITLE
 【quick start】quick start中用cfg=trainer_config.bidi-lstm.py训练的lstm模型，无法用cfg=trainer_config.lstm.py来进行预测

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#600]
quick start中用cfg=trainer_config.bidi-lstm.py训练的lstm模型，无法用cfg=trainer_config.lstm.py来进行预测。

root@0a88acc80043:~/paddle/demo/quick_start# ./predict.sh 
Paddle release a new version v0.9.0, you can get the install package in http://www.paddlepaddle.org
I1124 08:46:21.937424 17543 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lstm.py --use_gpu=false --job=test --init_model_path=output/pass-00003 --config_args=is_predict=1 --predict_output_dir=. 
I1124 08:46:21.937628 17543 Util.cpp:130] Calling runInitFunctions
I1124 08:46:21.937924 17543 Util.cpp:143] Call runInitFunctions done.
[WARNING 2016-11-24 08:46:22,086 networks.py:1438] `outputs` routine try to calculate network's inputs and outputs order. It might not work well.Please see follow log carefully.
[INFO 2016-11-24 08:46:22,086 networks.py:1466] The input order is [word]
[INFO 2016-11-24 08:46:22,086 networks.py:1472] The output order is [__maxid_layer_0__, __fc_layer_0__]
I1124 08:46:22.094259 17543 Trainer.cpp:149] trainer: in testing mode
I1124 08:46:22.094307 17543 Trainer.cpp:156] trainer mode: Testing
I1124 08:46:22.196655 17543 PyDataProvider2.cpp:257] loading dataprovider dataprovider_emb::process_predict
I1124 08:46:22.197605 17543 GradientMachine.cpp:123] Loading parameters from output/pass-00003
I1124 08:46:22.205034 17543 Parameter.cpp:344] missing parameters [output/pass-00003/_lstm_transform___lstm_0__.w0] while loading model.
F1124 08:46:22.205085 17543 Parameter.cpp:350] _lstm_transform___lstm_0__.w0 missing, not allowed.
*** Check failure stack trace: ***
    @     0x7f82d3e18daa  (unknown)
    @     0x7f82d3e18ce4  (unknown)
    @     0x7f82d3e186e6  (unknown)
    @     0x7f82d3e1b687  (unknown)
    @           0x825ce2  paddle::Parameter::load()
    @           0x5633a6  paddle::GradientMachine::loadParameters()
    @           0x6b689c  paddle::ParameterUtil::loadParametersWithPath()
    @           0x6c0a6d  paddle::Tester::test()
    @           0x52b718  main
    @     0x7f82d3024f45  (unknown)
    @           0x540c05  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109: 17543 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by luotao1** [comment]
得用同一个模型来进行预测的。不然网络结构和存的网络参数都不一样。
