### ISSUE TITLE
[cmake治理]删除paddle_test多余无用依赖

### ISSUE THREAD

**Issue by risemeup1** [PaddlePaddle/Paddle#60013]
## 一、需求背景
飞桨正在优化cmake代码，来减少编译时候的开发成本，目前paddle编译c++单测有多种方式，如cc_test_old（link静态库），cc_test（windows下link静态库，linux下link paddle.so），paddle_test(windows和linux下都link动态库paddle.so)，现在推荐使用paddle_test，好处在于：
1.  link动态库无需手动加过多的依赖，大部分符号在paddle.so中已存在；
2.  link libpaddle.so可以大幅度减小C++单测的体积 ，从而减少build目录体积大小

## 二、存在的问题
paddle仓库中大概有50个使用paddle_test的代码，有一部分后面加了额外不需要的依赖，需要删除，如test/cpp/pir/shape_dialect/CMakeLists.txt中shape_struct_test单测依赖了gtest，实际上是额外的依赖，应该删掉。

## 三、建议步骤
1 在linux下，将paddle_test DEPS依赖全部删掉编译，如果遇到找不到一些符号，再加上必要的依赖
2 linux下报错解决后，windows下可能也会遇到一些编译问题

## 四、任务划分
| 序号 | 目录 | 认领人/状态/PR号 |
| :-: | :-: | :-: |
| 1 | ~~paddle/fluid/inference/utils/CMakeLists.txt~~ | @Liyulingyue <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 2 | test/cpp/auto_parallel/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60274](https://github.com/PaddlePaddle/Paddle/pull/60274) [#60348](https://github.com/PaddlePaddle/Paddle/pull/60348)<br> | 
| 3 | ~~test/cpp/eager/performance_tests/CMakeLists.txt~~ | @BeingGod <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 4 | test/cpp/fluid/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60160](https://github.com/PaddlePaddle/Paddle/pull/60160)<br> | 
| 5 | test/cpp/fluid/cinn/CMakeLists.txt | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60235](https://github.com/PaddlePaddle/Paddle/pull/60235)<br> | 
| 6 | ~~test/cpp/fluid/framework/CMakeLists.txt~~ | @RedContritio <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 7 | ~~test/cpp/fluid/framework/details/CMakeLists.txt~~ | @RedContritio <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 8 | ~~test/cpp/fluid/lite/CMakeLists.txt~~ | @ccsuzzh <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | 
| 9 | test/cpp/fluid/pscore/CMakeLists.txt | @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60240](https://github.com/PaddlePaddle/Paddle/pull/60240)<br> | 
| 10 | test/cpp/pir/cinn/CMakeLists.txt | @zrr1999 <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60239](https://github.com/PaddlePaddle/Paddle/pull/60239)<br> | 
| 11 | test/cpp/pir/cinn/adt/CMakeLists.txt | @zrr1999 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60154](https://github.com/PaddlePaddle/Paddle/pull/60154)<br> | 
| 12 | test/cpp/pir/core/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60161](https://github.com/PaddlePaddle/Paddle/pull/60161)<br> | 
| 13 | test/cpp/pir/shape_dialect/CMakeLists.txt | @sanbuphy <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" />  [#60517](https://github.com/PaddlePaddle/Paddle/pull/60517)<br>  | 
| 14 | test/cpp/pir/sub_graph/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60087](https://github.com/PaddlePaddle/Paddle/pull/60087)<br> | 
| 15 | test/cpp/prim/CMakeLists.txt | @enkilee <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60149](https://github.com/PaddlePaddle/Paddle/pull/60149)<br> | 

### 认领方式
请大家以 comment 的形式认领任务，如：
```
【报名】：1、3、12-13
```
多个任务之间需要使用**中文顿号**分隔，报名多个连续任务可用横线表示，如 2-5
PR 提交格式：在 PR 的标题中以 **【CMake opt】** 开头，注明任务编号

## 看板信息
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
| 快乐开源 | 15 | 10 / 15 | 66.67% | 10 | 66.67% |
#####

## 统计信息 
> 排名不分先后 @zade23 (1) @DrRyanHuang (2) @ccsuzzh (1) @xiaoyewww (2) @zrr1999 (1) @Liyulingyue (3) 
#####

**Comment by Liyulingyue** [comment]
【报名】：1

**Comment by DrRyanHuang** [comment]
【报名】：4、12、14

**Comment by zrr1999** [comment]
【报名】：10、11

**Comment by RedContritio** [comment]
【报名】：6、7

**Comment by zade23** [comment]
【报名】：2

**Comment by enkilee** [comment]
【报名】：15

**Comment by BeingGod** [comment]
【报名】：3

**Comment by sanbuphy** [comment]
【报名】：13

**Comment by ccsuzzh** [comment]
【报名】：5、8

**Comment by xiaoyewww** [comment]
【报名】：9、14

**Comment by Liyulingyue** [comment]
Task No. 1 Finished. Nothing needs to delete.

The error log when delete the only DEPS, benchmark:

```
[ 85%] Built target test_mkldnn_cpu_quantize_pass
/usr/local/bin/ld: CMakeFiles/test_benchmark.dir/benchmark_tester.cc.o: in function `Benchmark_basic_Test::TestBody()':
benchmark_tester.cc:(.text._ZN20Benchmark_basic_Test8TestBodyEv+0xc8): undefined reference to `paddle::inference::Benchmark::SerializeToString[abi:cxx11]() const'
/usr/local/bin/ld: CMakeFiles/test_benchmark.dir/benchmark_tester.cc.o: in function `Benchmark_PersistToFile_Test::TestBody()':
benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0xae): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/bin/ld: benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0xea): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
/usr/local/bin/ld: benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0x126): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
collect2: error: ld returned 1 exit status
paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/build.make:113: recipe for target 'paddle/fluid/inference/utils/test_benchmark' failed
make[2]: *** [paddle/fluid/inference/utils/test_benchmark] Error 1
CMakeFiles/Makefile2:95109: recipe for target 'paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/all' failed
make[1]: *** [paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

**Comment by risemeup1** [comment]
> Task No. 1 Finished. Nothing needs to delete.
> 
> The error log when delete the only DEPS, benchmark:
> 
> ```
> [ 85%] Built target test_mkldnn_cpu_quantize_pass
> /usr/local/bin/ld: CMakeFiles/test_benchmark.dir/benchmark_tester.cc.o: in function `Benchmark_basic_Test::TestBody()':
> benchmark_tester.cc:(.text._ZN20Benchmark_basic_Test8TestBodyEv+0xc8): undefined reference to `paddle::inference::Benchmark::SerializeToString[abi:cxx11]() const'
> /usr/local/bin/ld: CMakeFiles/test_benchmark.dir/benchmark_tester.cc.o: in function `Benchmark_PersistToFile_Test::TestBody()':
> benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0xae): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> /usr/local/bin/ld: benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0xea): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> /usr/local/bin/ld: benchmark_tester.cc:(.text._ZN28Benchmark_PersistToFile_Test8TestBodyEv+0x126): undefined reference to `paddle::inference::Benchmark::PersistToFile(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'
> collect2: error: ld returned 1 exit status
> paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/build.make:113: recipe for target 'paddle/fluid/inference/utils/test_benchmark' failed
> make[2]: *** [paddle/fluid/inference/utils/test_benchmark] Error 1
> CMakeFiles/Makefile2:95109: recipe for target 'paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/all' failed
> make[1]: *** [paddle/fluid/inference/utils/CMakeFiles/test_benchmark.dir/all] Error 2
> make[1]: *** Waiting for unfinished jobs....
> ```

好的，那就不删除

**Comment by BeingGod** [comment]
Task NO.3 在 261532e583356b13e1b6d41676d3bb9daef520ad 已完成了多余依赖的删除

**Comment by BeingGod** [comment]
Task NO.3 的common已经在 https://github.com/PaddlePaddle/Paddle/pull/60149  删除。

**Comment by ccsuzzh** [comment]
Task NO.8 的common已经在 https://github.com/PaddlePaddle/Paddle/pull/60149 删除。

**Comment by RedContritio** [comment]
Task 6 已在 #60149 解决
Task 7 已在 #59995 解决

**Comment by luotao1** [comment]
[[cmake治理]删除paddle_test多余无用依赖](https://github.com/PaddlePaddle/Paddle/issues/60013#top) 已全部完成，感谢参与的小伙伴们！

> @zade23 (1) @DrRyanHuang (2) @ccsuzzh (1) @xiaoyewww (2) @zrr1999 (1) @Liyulingyue (3) @BeingGod  @RedContritio 


欢迎继续参与[快乐开源的其他任务](https://github.com/PaddlePaddle/Paddle/issues/56689)！
