### ISSUE TITLE
cuda12.0官网镜像下编译报错

### ISSUE THREAD

**Issue by YibinLiu666** [PaddlePaddle/Paddle#60035]
### 问题描述 Issue Description

当我使用 paddlepaddle/paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6 镜像创建了docker容器后，在容器中拉取最新的代码编译时会报错
![image](https://github.com/PaddlePaddle/Paddle/assets/68105073/1db2ba2f-6488-4026-bf6f-1e504ed7c761)

我使用的显卡是3090，服务器cuda版本是12.0，由于CUDA_STANDARD为17时 `cmake .. -DPY_VERSION=3.10 -DWITH_GPU -DWITH_TESTING=ON` 时会报错
![image](https://github.com/PaddlePaddle/Paddle/assets/68105073/ca1ee4af-329e-45cc-8547-8333b1e464cf)

因此我将 `cmake/cuda.make` 中的 `set(CMAKE_CUDA_STANDARD 17)` 改成了`set(CMAKE_CUDA_STANDARD 14)`

### 版本&环境信息 Version & Environment Information

None

**Comment by YibinLiu666** [comment]
从这个测试代码的修改日志来看好像是昨天的PR https://github.com/PaddlePaddle/Paddle/pull/59978 把cc_test_old改成了cc_test导致的，现在把 `paddle/cast/Paddle/test/cpp/pir/pass/CMakeLists.txt` 里面的cc_test改回去能通过编译，具体原因不清楚
![image](https://github.com/PaddlePaddle/Paddle/assets/68105073/7e720a10-dba9-467d-a9ac-d8a52cc3c2fe)

**Comment by cocoshe** [comment]
> 当我使用 paddlepaddle/paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6 镜像创建了docker容器后，在容器中拉取最新的代码编译时会报错

bin哥再遇到类似问题可以试试[这个镜像](https://hub.docker.com/r/paddlepaddle/paddle/tags)
```
docker pull paddlepaddle/paddle:latest-dev-cuda12.0-cudnn8.9-trt8.6-gcc12.2
```
我在2080ti上试了下用docker，可以成功编译，**无痛**一遍过
```
cmake .. -DWITH_TESTING=ON -DWITH_GPU=ON
make -j16
```

**Comment by YibinLiu666** [comment]
> > 当我使用 paddlepaddle/paddle:2.5.2-gpu-cuda12.0-cudnn8.9-trt8.6 镜像创建了docker容器后，在容器中拉取最新的代码编译时会报错
> 
> bin哥再遇到类似问题可以试试[这个镜像](https://hub.docker.com/r/paddlepaddle/paddle/tags)
> 
> ```
> docker pull paddlepaddle/paddle:latest-dev-cuda12.0-cudnn8.9-trt8.6-gcc12.2
> ```
> 
> 我在2080ti上试了下用docker，可以成功编译，**无痛**一遍过
> 
> ```
> cmake .. -DWITH_TESTING=ON -DWITH_GPU=ON
> make -j16
> ```

感谢coco哥
