### ISSUE TITLE
paddle源码编译失败，infer_io_utils_tester编译错误，链接时找不到符号

### ISSUE THREAD

**Issue by cocoshe** [PaddlePaddle/Paddle#60077]
### 问题描述 Issue Description
最近做hackathon的时候，同步了一下paddle库，然后突然就编译不过了。。。
![99bcd70acd1a84543ac957cf0e5ca26](https://github.com/PaddlePaddle/Paddle/assets/69197635/35e26854-7e1a-4aae-9988-e53d8c566a01)

```
cmake .. -DWITH_TESTING=ON -DWITH_GPU=ON
make -j20
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
Clang version: N/A
CMake version: version 3.19.0
Libc version: glibc 2.31
Python version: 3.8.10

CUDA version: 11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
cuDNN version: 8.6.0
Nvidia driver version: 535.104.05
Nvidia driver List: 
GPU 0: NVIDIA GeForce RTX 3080 Ti

****************************************

编译命令：
```
cmake .. -DWITH_TESTING=ON -DWITH_GPU=ON
make -j20
```

**Comment by will-jl944** [comment]
如果没有特殊需求，可以先尝试`-DWITH_TESTING=OFF`进行编译
