### ISSUE TITLE
同一时间只能训练一个模型。

### ISSUE THREAD

**Issue by wj920291253** [PaddlePaddle/Paddle#60082]
### 请提出你的问题 Please ask your question

在单机多卡环境里，同一时间只能训练一个模型；就算处在不同容器内，使用不同显卡，跑第二个模型的时候，第一个模型的训练会卡住，第二个模型也会卡住。

**Comment by FlyingQianMM** [comment]
请问同时启动多个训练，是怎么启动的呢？一般情况下，每个模型训练是不会相互影响的
