### ISSUE TITLE
Failed to build Release/2.6 (8189a99)

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#60088]
### 问题描述 Issue Description

Build release/2.6 branch but triggers following error if `-DWITH_TESTING=ON`:

```sh
/workspace/paddle/paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/fpA_intB_gemm_template.h:48:10: fatal error: paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/autogen/arch_define.h: No such file or directory
   48 | #include "paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/autogen/arch_define.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
According the error message, it needs files automatically generated by something.
Manually running [phi/.../generic_mixed_gemm_kernelLauncher.py](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/generic_mixed_gemm_kernelLauncher.py) triggers another error - `FileNotFoundError` until I manually created the `autogen` folder:
```sh
$ cd /workspace/paddle/paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm
$ python ./generic_mixed_gemm_kernelLauncher.py

Traceback (most recent call last):
  File "/home/scratch.rjeng_sw/baidu/paddle/paddle/paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/./generic_mixed_gemm_kernelLauncher.py", line 212, in <module>
    with open(header_name, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'autogen/arch_define.h'

$ mkdir autogen
$ python ./generic_mixed_gemm_kernelLauncher.py # generating needed files
```

The CMakeLists should cover build process instead of asking users manually creating files and folder.

### 版本&环境信息 Version & Environment Information

```sh
CCACHE_DIR=/workspace/ccache_storage
ARCH_FLAGS="-march=sandybridge -mtune=broadwell"
CXX_FLAGS="$ARCH_FLAGS -Wno-error=range-loop-construct -Wno-error=maybe-uninitialized -Wno-error=switch -faligned-new=32"
CUDA_FLAGS="-t2 --forward-unknown-to-host-compiler -Xfatbin=-compress-all $ARCH_FLAGS -lineinfo"

SKIP_DOWNLOAD_INFERENCE_DATA=ON cmake -Bpaddle/build -Spaddle \
    -GNinja \
    -DINFERENCE_DEMO_INSTALL_DIR=/home/scratch.rjeng_sw/baidu/paddle/test_data \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="$CUDA_FLAGS" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="80" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DWITH_CUDNN_FRONTEND=ON \
    -DPY_VERSION=$PYVER \
    -Wno-dev

cmake --build paddle/build -j$((`nproc`))
```

**Comment by jeng1220** [comment]
cc @onecatcn for vis

**Comment by winter-wang** [comment]
You should first remove the two folders "paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/autogen" and "paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/autogen_tmp" , and then re-execute cmake to generate new and correct files。

**Comment by jeng1220** [comment]
@winter-wang ,
NO, as I mentioned, the folder `paddle/phi/kernels/fusion/cutlass/cutlass_kernels/fpA_intB_gemm/autogen` doesn't exist before I manaully create it.
The point is that CMake doesn't automatically generate the needed files.
Please clone a new PaddlePaddle, checkpout to 8189a99, and build it with `-DWITH_TESTING=ON`. You should see the error message.

**Comment by jeng1220** [comment]
~For unknown reason, I cannot reproduce this error now, so close this issue.~
@winter-wang ,
This bug only happens when people switches branch.
The step to reproduce:
1. clone the PaddlePaddle
2. checkout to release/2.6
3. run configuration (cmake ..) successfully
4. switch another branch. for example, another private branch based on release/2.6
5. run configuration again. NOW, the cmake will delete the `fpA_intB_gemm/autogen` because of [CMakeLists.txt#L149](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/paddle/phi/kernels/CMakeLists.txt#L149). However, for unknown reason, it doesn't create the `fpA_intB_gemm/autogen` later, so the next line, `generic_mixed_gemm_kernelLauncher.py` will trigger  `FileNotFoundError`

Log:
```sh
git clone PaddlePaddle
git checkout release/2.6 # now fpA_intB_gemm/autogen doesn't exist
mkdir build && cd build # create an empty build folder
cmake ..  # run configuration successfully and fpA_intB_gemm/autogen will be generated
cd .. && git branch my_branch && git checkout my_branch # switch another branch
cd build && cmake .. # run configuration again. 
                     # kernels/CMakeLists.txt#L149 deletes fpA_intB_gemm/autogen.
                     # fpA_intB_gemm/autogen doesn't exist
                     # generic_mixed_gemm_kernelLauncher.py triggers FileNotFoundError
```

**Comment by jeng1220** [comment]
not sure why paddle-bot closed this issue, so reopen again

**Comment by risemeup1** [comment]
> not sure why paddle-bot closed this issue, so reopen again

这个还么解决吗？

**Comment by wwbitejotunn** [comment]
> ~For unknown reason, I cannot reproduce this error now, so close this issue.~ @winter-wang , This bug only happens when people switches branch. The step to reproduce:
> 
> 1. clone the PaddlePaddle
> 2. checkout to release/2.6
> 3. run configuration (cmake ..) successfully
> 4. switch another branch. for example, another private branch based on release/2.6
> 5. run configuration again. NOW, the cmake will delete the `fpA_intB_gemm/autogen` because of [CMakeLists.txt#L149](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/paddle/phi/kernels/CMakeLists.txt#L149). However, for unknown reason, it doesn't create the `fpA_intB_gemm/autogen` later, so the next line, `generic_mixed_gemm_kernelLauncher.py` will trigger  `FileNotFoundError`
> 
> Log:
> 
> ```shell
> git clone PaddlePaddle
> git checkout release/2.6 # now fpA_intB_gemm/autogen doesn't exist
> mkdir build && cd build # create an empty build folder
> cmake ..  # run configuration successfully and fpA_intB_gemm/autogen will be generated
> cd .. && git branch my_branch && git checkout my_branch # switch another branch
> cd build && cmake .. # run configuration again. 
>                      # kernels/CMakeLists.txt#L149 deletes fpA_intB_gemm/autogen.
>                      # fpA_intB_gemm/autogen doesn't exist
>                      # generic_mixed_gemm_kernelLauncher.py triggers FileNotFoundError
> ```

Thanks for detailed reproduce process. We haven't considered such case before. We will check and fix it as soon as possible.

**Comment by wwbitejotunn** [comment]
> ~For unknown reason, I cannot reproduce this error now, so close this issue.~ @winter-wang , This bug only happens when people switches branch. The step to reproduce:
> 
> 1. clone the PaddlePaddle
> 2. checkout to release/2.6
> 3. run configuration (cmake ..) successfully
> 4. switch another branch. for example, another private branch based on release/2.6
> 5. run configuration again. NOW, the cmake will delete the `fpA_intB_gemm/autogen` because of [CMakeLists.txt#L149](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/paddle/phi/kernels/CMakeLists.txt#L149). However, for unknown reason, it doesn't create the `fpA_intB_gemm/autogen` later, so the next line, `generic_mixed_gemm_kernelLauncher.py` will trigger  `FileNotFoundError`
> 
> Log:
> 
> ```shell
> git clone PaddlePaddle
> git checkout release/2.6 # now fpA_intB_gemm/autogen doesn't exist
> mkdir build && cd build # create an empty build folder
> cmake ..  # run configuration successfully and fpA_intB_gemm/autogen will be generated
> cd .. && git branch my_branch && git checkout my_branch # switch another branch
> cd build && cmake .. # run configuration again. 
>                      # kernels/CMakeLists.txt#L149 deletes fpA_intB_gemm/autogen.
>                      # fpA_intB_gemm/autogen doesn't exist
>                      # generic_mixed_gemm_kernelLauncher.py triggers FileNotFoundError
> ```

Hi, I follow the step but fail to reproduce. 
Before first cmake, I make sure the fpA_intB_gemm/autogen doesn't exist. The first cmake will run in release/2.6 and it success
Then i checkout to another branch called tmp. This branch is just release/2.6 add some useless space in arbitrary source files to make it different from release/2.6. The second cmake configure process success in branch tmp and build process success as well.
I want to know is there sometings I miss in those steps. My release/2.6 is in commit 203754e47a.

**Comment by jeng1220** [comment]
@wwbitejotunn ,
Please try this one, this is full steps:
```sh
#!/bin/bash

set -xe

CURRENT_PATH=$(pwd)
CCACHE_DIR=$CURRENT_PATH/ccache_storage
mkdir -p $CCACHE_DIR

TEST_DATA_DIR=$CURRENT_PATH/test_data
mkdir -p $TEST_DATA_DIR

git clone --branch release/2.6 --depth=1 https://github.com/PaddlePaddle/Paddle.git paddle
cd $CURRENT_PATH/paddle
git submodule update --init --recursive

cd $CURRENT_PATH
ARCH_FLAGS="-march=sandybridge -mtune=broadwell"
CXX_FLAGS="$ARCH_FLAGS -Wno-error=range-loop-construct -Wno-error=maybe-uninitialized -Wno-error=switch -faligned-new=32"
CUDA_FLAGS="-t2 --forward-unknown-to-host-compiler -Xfatbin=-compress-all $ARCH_FLAGS -lineinfo"

cmake -Bpaddle/build -Spaddle \
    -GNinja \
    -DINFERENCE_DEMO_INSTALL_DIR=$TEST_DATA_DIR \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="$CUDA_FLAGS" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="70" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=ON \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=ON \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=ON \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DWITH_CUDNN_FRONTEND=ON \
    -DPY_VERSION=$PYVER \
    -Wno-dev

echo ""
echo "1st configuration is done"
echo ""

cmake -Bpaddle/build -Spaddle \
    -GNinja \
    -DINFERENCE_DEMO_INSTALL_DIR=$TEST_DATA_DIR \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="$CUDA_FLAGS" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="70" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=ON \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=ON \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=ON \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DWITH_CUDNN_FRONTEND=ON \
    -DPY_VERSION=$PYVER \
    -Wno-dev 2>&1 | tee config.log

grep FileNotFoundError config.log

```
* cmake version 3.25.1
* ninja 1.10.1

**Comment by jeng1220** [comment]
It only happens if the source code is placed at NAS (network-attached storage). Instead, place the code at ramdisk, then the issue is gone. Close this issue for now.

**Comment by tianshuo78520a** [comment]
我刚刚尝试重跑这个脚本也没有复现
