### ISSUE TITLE
Why are p2p communications on calc stream for pipeline parallel?

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#60095]
### 请提出你的问题 Please ask your question

When testing GPT-3 using pipeline parallel and comparing with Megatron, I found Paddle always call `cudaStreamSynchronize` before p2p communication with Paddle 2.5.2 ([p2p_communication.py#L502](https://github.com/PaddlePaddle/Paddle/blob/v2.5.2/python/paddle/distributed/fleet/meta_parallel/pp_utils/p2p_communication.py#L502)), which makes the perf not good enough.

I have also checked the latest develop branch, the p2p communication is put on the calc stream and sync is not needed. I wonder that if you don't overlap the calculation with p2p communication, the performance will not be worse? May I ask why p2p communication is designed this way?

**Comment by Wong4j** [comment]
2.5.2版本之后p2p的逻辑改过两次，
1. [PR#53559](https://github.com/PaddlePaddle/Paddle/pull/53559)中改成了batch_isend_irecv -> wait reqs -> cudaDeviceSynchronize，这和Megatron基本一致([p2p_communication.py#L329](https://github.com/NVIDIA/Megatron-LM/blob/fab0bd693ec5be55b32c4f12a1ea44766ec63448/megatron/core/pipeline_parallel/p2p_communication.py#L329))，不过Megatron不需要cudaDeviceSynchronize.
2. [PR#54747](https://github.com/PaddlePaddle/Paddle/pull/54747)中改成了batch_send_recv_on_calc_stream，这种写法就是不需要同步，但是也不能与计算overlap。

**Comment by ForFishes** [comment]
您好，这里改动原因：
1、Megatron也使用了cudaDeviceSynchronize，它的是torch.cuda.synchronize()，这导致一个额外的同步操作。如果使用通信流，就必须用类似cudaDeviceSynchronize的操作，主要是前面的wait无法确保真正的同步。https://github.com/NVIDIA/Megatron-LM/blob/fab0bd693ec5be55b32c4f12a1ea44766ec63448/megatron/core/pipeline_parallel/p2p_communication.py#L345
2、paddle的改动主要是为了pipeline和dp的梯度通信overlap，需要避免cpu的sync操作（cudaDeviceSynchronize），因此将原来的操作改成了计算流。

**Comment by Wong4j** [comment]
@ForFishes 感谢回复，我跑过Megatron，那个cudaDeviceSynchronize的if分支并没有进去，看注释意思是新版本的pytorch不需要这个同步，不知道是怎么做到确保同步的。

我刚才测试了一下PaddleNLP GPT175B，64卡，只开TP=8和PP=8的情况下，三种p2p版本的训练速度差不多，性能基本没有变化。Paddle的p2p应该还有优化的空间

> paddle的改动主要是为了pipeline和dp的梯度通信overlap

这个意思是开DP+PP的时候，会有多个通信的overlap吗？性能会比之前的更好吗？

**Comment by Wong4j** [comment]
这是Megatron的timeline，p2p可以跟其他的计算和通信overlap
![image](https://github.com/PaddlePaddle/Paddle/assets/21985950/2313aad5-303e-40b2-a028-3dd00634e563)
这是Paddle的的timeline，p2p没有overlap
![image](https://github.com/PaddlePaddle/Paddle/assets/21985950/a0bd2a1b-6219-40f2-b019-fcde108cab45)

**Comment by ForFishes** [comment]
确实，最初的版本，torch需要强制调用cudaDeviceSynchronize保证精度正确，不过后续torch修复了这个问题，因此megatron应该用的是最新的版本。
由于使用batch_isend_irecv后，紧接着就要wait，因此这个batch_isend_irecv的异步是没有意义的，反而增加了切流的代价（原因是torch的通信库不支持选流）。
paddle这里的优化是方便后续pp+dp的性能优化，尤其是调用了pp+vpp的时候。

**Comment by Wong4j** [comment]
目前p2p不是性能瓶颈，先关掉这个issue
