### ISSUE TITLE
Paddle预测API无法加载多个network

### ISSUE THREAD

**Issue by huajunzeng** [PaddlePaddle/Paddle#601]
想在同一程序里用预测API加载多个network，类似这样：
```
for idx in range(n):
    conf = parse_config(train_conf[idx], "is_predict=1")
    network[idx] = swig_paddle.GradientMachine.createFromConfigProto(conf.model_config)
    network[idx].loadParameters(model_dir)
```
只加载一个网络时程序没错。有多个网络时，loadParameters这里出错了，出错信息是，
`Parameter.cpp:350] _lstm_transform___bidirectional_lstm_2___fw.w0 missing, not allowed.`
程序里只有两个blstm，只有0和1两套参数。估计是用了全局变量来累计给layer命名。有没有什么解决办法？

**Comment by luotao1** [comment]
试试使用layer的时候，自定义name

**Comment by huajunzeng** [comment]
多谢回答。这样是可以解决，但是好麻烦，自己要管理一套命名，不同model之间还要考虑不能冲突。有没有计划改？

**Comment by luotao1** [comment]
回头我们看看，最近应该还没有计划要改。有计划的话会尽快通知您的。

**Comment by reyoung** [comment]
@huajunzeng 这个，推荐使用python的multiprocessing来做多个网络的预测，并不算复杂。
