### ISSUE TITLE
[24Q2] Build release/2.6 (8189a99) is low efficient

### ISSUE THREAD

**Issue by jeng1220** [PaddlePaddle/Paddle#60105]
### 问题描述 Issue Description

It seems all modules are waiting for flash attention (third_party/flashattn). This dependence doesn't make sense. What's worse is that it only forks 4 processes to build flash attention. 
![image](https://github.com/PaddlePaddle/Paddle/assets/5894445/96426c18-3e5b-44f4-a2ea-3777368dfcf1)

### 版本&环境信息 Version & Environment Information

```
CCACHE_DIR=/workspace/ccache_storage
ARCH_FLAGS="-march=sandybridge -mtune=broadwell"
CXX_FLAGS="$ARCH_FLAGS -Wno-error=range-loop-construct -Wno-error=maybe-uninitialized -Wno-error=switch -faligned-new=32"
CUDA_FLAGS="-t2 --forward-unknown-to-host-compiler -Xfatbin=-compress-all $ARCH_FLAGS -lineinfo"

SKIP_DOWNLOAD_INFERENCE_DATA=ON cmake -Bpaddle/build -Spaddle \
    -GNinja \
    -DINFERENCE_DEMO_INSTALL_DIR=/home/scratch.rjeng_sw/baidu/paddle/test_data \
    -DCMAKE_CXX_FLAGS="$CXX_FLAGS" \
    -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_CUDA_FLAGS="$CUDA_FLAGS" \
    -DCUDA_ARCH_NAME=Manual \
    -DCUDA_ARCH_BIN="80" \
    -DWITH_INCREMENTAL_COVERAGE=OFF \
    -DWITH_INFERENCE_API_TEST=OFF \
    -DWITH_DISTRIBUTE=ON \
    -DWITH_COVERAGE=OFF \
    -DWITH_TENSORRT=OFF \
    -DWITH_TESTING=ON \
    -DWITH_CONTRIB=ON \
    -DWITH_ROCM=OFF \
    -DWITH_RCCL=OFF \
    -DWITH_STRIP=ON \
    -DWITH_MKL=OFF \
    -DWITH_AVX=OFF \
    -DWITH_GPU=ON \
    -DWITH_PYTHON=ON \
    -DWITH_CUDNN_FRONTEND=ON \
    -DPY_VERSION=$PYVER \
    -Wno-dev

cmake --build paddle/build -j$((`nproc`))
```

**Comment by risemeup1** [comment]
We know about this problem, and we have reported it to relevant RD.

**Comment by jeng1220** [comment]
@risemeup1 ,
I suggest that using [CMake/ProcessorCount](https://cmake.org/cmake/help/latest/module/ProcessorCount.html) to detect the number of CPU cores, and then passing the number to [cmake/external/flashattn.cmake#L110](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/cmake/external/flashattn.cmake#L110).
Otherwise, it is easy to encounter build timeout of CI.

**Comment by tianshuo78520a** [comment]
[PRhttps://github.com/PaddlePaddle/Paddle/pull/65339](https://github.com/PaddlePaddle/Paddle/pull/65339) 正在修改，目前单测有些问题，需要等下测试结果。

**Comment by jeng1220** [comment]
Thanks! Close this issue.
