### ISSUE TITLE
源码编译paddle-xpu包，每次编完版本号都是0.0.0咋弄

### ISSUE THREAD

**Issue by Newcomer-CL** [PaddlePaddle/Paddle#60169]
### 请提出你的问题 Please ask your question

源码编译paddle-xpu包，每次编完版本号都是0.0.0咋弄
paddlepaddle_xpu-0.0.0-cp39-cp39-linux_x86_64.whl

**Comment by Bobholamovic** [comment]
你好，0.0.0是默认的版本号，表示本地编译的版本。如果你需要指定一个版本号，可以尝试在安装时设置环境变量`PADDLE_VERSION`。
