### ISSUE TITLE
NCE负采样问题

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#6017]
`NCE` 现在支持是按照频率去负采样，请问支持把一次请求中未点击的部分作为负样例，而不是从整体中找负样例，这样的方式吗？

**Comment by zhouxiao-coder** [comment]
NCE设计的出发点是用一系列小的分类问题（proxy problem）来近似的解决一个大规模的分类问题。采样的分布应该尽量符合整体数据的分布，而不只是重点采样其中部分数据。

> 请问支持把一次请求中未点击的部分作为负样例，而不是从整体中找负样例

如果认为这样更合理的话，建议可以把问题建模成 Learning To Rank 问题，使用pairwise的方式进行训练，此时可以更加精确地掌握负例的构造。

如果有兴趣的话我们可以再展开讨论：）

**Comment by windy444** [comment]
非常感谢
