### ISSUE TITLE
paddle2.0 当DataLoader 参数num_workers>0时报错

### ISSUE THREAD

**Issue by anygoanygogo** [PaddlePaddle/Paddle#60185]
### 请提出你的问题 Please ask your question

paddle2.0 当DataLoader 参数num_workers>0时报错 AttributeError: ‘_DataLoaderIterMultiProcess’ object has no attribute ‘_shutdown’

**Comment by Bobholamovic** [comment]
请提供具体的Paddle版本、运行环境以及最小可复现代码，以便我们排查问题～

**Comment by anygoanygogo** [comment]
> 请提供具体的Paddle版本、运行环境以及最小可复现代码，以便我们排查问题～

paddle 2.4.0
本地运行



import paddle
import paddle.nn as nn
import paddle.optimizer as optim

from paddle.nn import Transformer
from paddle.nn import TransformerEncoder, TransformerDecoder
from paddle.io import Dataset, BatchSampler, DataLoader

import random
import numpy as np
import json

from model import AdsSort

from datetime import datetime
import time

import configparser


class CpmSortDataSet(Dataset):
    """
    """

    def __init__(self, n_rows):
        """
        """
        self.points = paddle.randn((n_rows, 40, 42)) 
        self.targets = paddle.randn((n_rows, 39))
        self.nums = paddle.randn((n_rows, 1)) 

    def __getitem__(self, idx):
        """
        __getitem__
        """
        points, targets, length = self.points[idx], self.targets[idx], self.nums[idx]
        return points, targets, length

    def __len__(self):
        """
        __len__
        """
        return len(self.points)

train_dataset = CpmSortDataSet(10)
train_loader = DataLoader(train_dataset, batch_size=2, num_workers=2, shuffle=True)

for bat, (batch_data, batch_labels, batch_lengths) in enumerate(train_loader):
    print (batch_data)
    print (batch_labels)
    print (batch_lengths)

**Comment by Bobholamovic** [comment]
在`Dataset`类的`__init__`中创建GPU tensor可能会遇到一些问题，建议使用`np.random.randn`代替`paddle.randn`（注意传递的参数略有差别），Paddle将自动执行ndarray->tensor的转换。

**Comment by anygoanygogo** [comment]
> 在`Dataset`类的`__init__`中创建GPU tensor可能会遇到一些问题，建议使用`np.random.randn`代替`paddle.randn`（注意传递的参数略有差别），Paddle将自动执行ndarray->tensor的转换。

def __init__(self, n_rows):
    """
    """
    self.points = np.random.randn(n_rows, 40, 42)
    self.targets = np.random.randn(n_rows, 39)
    self.nums = np.random.randn(n_rows, 1)

def __getitem__(self, idx):
    """
    __getitem__
    """
    points, targets, length = self.points[idx], self.targets[idx], self.nums[idx]
    return points, targets, length

def __len__(self):
    """
    __len__
    """
    return len(self.points)


还是报同样的错误

**Comment by Bobholamovic** [comment]
我使用Paddle 2.5无法复现这个错误，在使用`np.random.randn`代替`paddle.randn`后代码执行符合预期。如果可能的话，请考虑升级Paddle到最新的稳定版。此外，如果你使用的是Windows机器，建议将`num_workers`设置为0，因为Windows机器的多进程机制与Unix机器不同，在Windows机器上使用大于0的`num_workers`可能并不能起到预期的加速效果。
