### ISSUE TITLE
单机场景下无法build

### ISSUE THREAD

**Issue by jw8023wh** [PaddlePaddle/Paddle#602]
在执行到
cd paddle_internal_release_tools/idl/paddle/ && sh build.sh
时报错，错误如下：
![qq 20161124165631](https://cloud.githubusercontent.com/assets/9283249/20592143/046b5e3a-b267-11e6-88dd-765328357a84.png)

**Comment by backyes** [comment]
@jw8023wh 确认下你的Paddle源码目录是否完整，或者也可以重新下载一份。

**Comment by reyoung** [comment]
这应该是代码没下载完。
