### ISSUE TITLE
Fluid performance tuning plan

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#6024]
We plan to tune fluid's performance with a loop with three steps:

1. Profile: To figure out which part of the fluid is slow.
2. Find problems & Give a fix: We will discuss and find the problems based on profile results.
3. Profile: To confirm the problems has been solved and the performance is improved.

There are several jobs for these three steps:

1. Find a machine with docker and GPU for profiling.  @jacquesqiao 
2. Neural network configurations for CNN, LSTM, etc. @qingqing01 @dzhwinter 
    - https://github.com/PaddlePaddle/Paddle/pull/6056
3. Setup an environment for profiling. @chengduoZH 
    * Use cProfile for Python, yap for Python/C++, nvprof for CUDA
4. Find problems: All members together.
5. Fix GPU problems: @jacquesqiao @qingqing01 
6. Fix CPU problems: @dzhwinter 
7. Fix Python problems: TODO

**Comment by dzhwinter** [comment]
1. Python code optimization
    We use `CProfile` profiling the python code. The tool usage can be checked out at [cpu_profiling](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/optimization/cpu_profiling.md). If we need to dig into the code. You can add this snippet to the script, then you will get an accurate function call count. This is useful to measure whether there is redundant  `Variable`, `Operator` is created.
```python
import cProfile
pr = cProfile.Profile()
pr.enable()
// here the test codes. 
pr.disable()
```
     
    [ ] fine-tune the `fit_a_line` tests, check the components time cost. e.g.`Program, Variable, Operator, Block`
    [ ] fine-tune one forward pass, check total time cost in Python side. 

2. C++ code optimization
    The `yep` + `gperftools` is excellent, but there is many `Py_Eval`, `Py_Object` function call disturb the focus point.  Here is the method only retain necessary c++ calls. 
```c++
#ifdef ENABLE_PROFILE
#include <gperftools/profiler.h>
#endif
   ProfilerStart("cs.prof");
// here the test codes.
ProfilerStop()
ProfilerFlush()
```
     [ ] fine-tune the training forward/backward process, find the bottle-neck.

3. Cuda code
    TBD

**Comment by dzhwinter** [comment]
Also, we had created benchmark docker image and benchmark repo for every one reproduce the result.  
https://github.com/dzhwinter/benchmark
The benchmark repo contains the tensorflow and paddle scripts.

https://hub.docker.com/r/dzhwinter/benchmark

The docker image contains all the profile tools.

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/optimization/gpu_profiling_cn.rst

**Comment by jacquesqiao** [comment]
profile steps:
1. make a work dir for your self
2. checkout paddle source code and benchmark source code
https://github.com/dzhwinter/benchmark

3. cd to your source code
4. start and enter then benchmark container
```text
nvidia-docker run -it --rm --network=host -v $PWD:/paddle -v /root/.cache:/root/.cache  dzhwinter/benchmark /bin/bash  
```
5. build your source code inside the container and installed it.
6. run benchmark code
```shell
python -m yep -v test_recognize_digits_conv.py
```
7. run pprof. (NOTE: please random choose a port between 8000:9000)
```shell
pprof -http=0.0.0.0:8123 `which python` test_recognize_digits_conv.py.prof
```

**Comment by reyoung** [comment]
Basical Performance tunning has been done. Please reference Project https://github.com/PaddlePaddle/Paddle/projects/29#card-5921207 for the following works
