### ISSUE TITLE
离线paddle下载第三方编译，执行make还是会clone

### ISSUE THREAD

**Issue by huayong** [PaddlePaddle/Paddle#6028]
目前编译机器不能上网，但是需要使用最新paddle。
所以把build/third_party需要的第三方库离线下载下来，按照cmake中的目录组织，但是每次make编译后还会重新clone，有没有方法可以不让其在线clone，使用离线现在的包。

**Comment by luotao1** [comment]
`-DTHIRD_PARTY_PATH`可以指定路径
