### ISSUE TITLE
torchsde分解器在paddle中的替换函数

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/Paddle#60286]
### 需求描述 Feature Description

请问一下，在paddle中有torchsde的替换函数吗，在复现video2video论文中，使用torchsde.BrownianTree函数进行噪音采样，请问有什么替代函数

**Comment by kangguangli** [comment]
应该不需要替换，可以参考https://github.com/PaddlePaddle/PaddleMIX/blob/89d4c657863efaa1143368ef119bf75ac99a64b2/ppdiffusers/ppdiffusers/schedulers/scheduling_dpmsolver_sde.py#L48

**Comment by Yang-Changhui** [comment]
> 应该不需要替换，可以参考https://github.com/PaddlePaddle/PaddleMIX/blob/89d4c657863efaa1143368ef119bf75ac99a64b2/ppdiffusers/ppdiffusers/schedulers/scheduling_dpmsolver_sde.py#L48

好的，谢谢
