### ISSUE TITLE
paddle.fluid.layers.dynamic_lstm

### ISSUE THREAD

**Issue by Wei-Wu233** [PaddlePaddle/Paddle#60297]
### bug描述 Describe the Bug

paddle.fluid.layers.dynamic_lstm(input=lsmt_backward_fc, size=self.lstm_size * 4, is_reverse=True, name='rgb_lstm_backward')
如何将paddle.fluid.layers.dynamic_lstm更换为paddle.nn.LSTM？？？

**Comment by Charles-hit** [comment]
> ### bug描述 Describe the Bug
> paddle.fluid.layers.dynamic_lstm(input=lsmt_backward_fc, size=self.lstm_size * 4, is_reverse=True, name='rgb_lstm_backward') 如何将paddle.fluid.layers.dynamic_lstm更换为paddle.nn.LSTM？？？
> 
> ### 其他补充信息 Additional Supplementary Information
> _No response_

您好，可以参考这个文档进行转换https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/api_cn/layers_cn/dynamic_lstmp_cn.html
这儿有标识input_size与hidden_size之间的关系
