### ISSUE TITLE
在custom device上，关于 class DenseTensor中的被宏（PADDLE_WITH_CUSTOM_KERNEL）限制的成员方法（如slice，split）是否可以放开，正常使用，这样custom device使用这些方法可以提高该类型算子的性能。

### ISSUE THREAD

**Issue by raining-dark** [PaddlePaddle/Paddle#60309]
### 需求描述 Feature Description

任务目标：custom device上的模型训练; <br /> 需求场景：训练时会使用到slice，split等算子，class DenseTensor中有相关功能算子方法（如slice，split），直接使用该成员方法可以节省开销和时间，提高性能;  <br /> 功能描述：是否可以放开 class DenseTensor中的被宏（PADDLE_WITH_CUSTOM_KERNEL）限制的成员方法（如slice，split等），让custom device 也可以使用起来

**Comment by Charles-hit** [comment]
您好，我这边已经向相关负责人反馈了，有结论后给您同步

**Comment by Charles-hit** [comment]
<img width="865" alt="f039b00b2844290d4079ae320b08b939" src="https://github.com/PaddlePaddle/Paddle/assets/56987902/7c6ccbc9-db05-4a57-b834-2fd4f3b4788a">
您好，沟通了一下，这两个接口不是规范的算子接口，既然已经有正式的slice和split算子，尽量还是用正式API里的
