### ISSUE TITLE
Add a compile option for grpc?

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#6034]
Can we add a compile option for grpc? If we build and run on local machine which don't need distributed computing, we can choose not to compile send_op/recv_op and some related codes.

**Comment by chengduoZH** [comment]
I want to ask this too.

**Comment by typhoonzero** [comment]
Yep, will add. Is the option name `WITH_DISTRB` OK?

**Comment by luotao1** [comment]
How about use the full name `WITH_DISTRIBUTE`?

**Comment by typhoonzero** [comment]
Sure, will use `WITH_DISTRIBUTE`.
