### ISSUE TITLE
Should we add device field in our framwork.proto

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6035]
Our neural network topology will be serialized to `ProgramDesc`. And we hope that this `ProgramDesc` can be transpose to different hardware environments, such as single CPU/GPU, multi-GPUs, or multi-nodes.

However, we should also expose device configuration to users. Following is an example:
```
with paddle.device("CPU"):
   a = layers.data()
   b = layers.data()
   c = layers.sum(a, b)

with paddle.device("GPU"):
   d = layer.tanh(c)

with paddle.device("FPGA"):
   e = layers.softmax(d)
```

I think that this feature is important, we should provides such interface for users to set device for specific layers.

Then, there comes a question, where to store these device information. At now, there is no device field in framework.proto.

In tensorflow, there is a device field in [node_def.proto](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/node_def.proto#L48). In Mxnet, there is a device attribute of [graph ](https://github.com/apache/incubator-mxnet/blob/master/src/executor/graph_executor.cc#L410)to store users's device configuration.

If we want to support such feature(user can set device for specific operator),  we have to handle these device configuration. 
Maybe we should add a device field in framework.proto, or we create another struct to store the device configuration.

**Comment by helinwang** [comment]
I agree, it's a very useful feature. Maybe we can work out a first version that the user can not do manual placement, but later add this feature?

**Comment by tonyyang-svail** [comment]
Quick question: since all operators know where to run, do we still need the `place` in `Executor`'s construction?

**Comment by QiJune** [comment]
I think that we will have a pool of DeviceContext. What Executor do is to take a DeviceContext from the pool to run the operator under the guide of device in operator.
