### ISSUE TITLE
uniform_问题

### ISSUE THREAD

**Issue by Ren-Xin** [PaddlePaddle/Paddle#60365]
导入paddle.uniform_报错module 'paddle' has no attribute 'uniform_'
请问是没有这个方法吗，我在帮助文档里看到的这个方法
![image](https://github.com/PaddlePaddle/Paddle/assets/48504366/6240d8ae-326e-429a-8af7-beb1e41ec103)

**Comment by jiahy0825** [comment]
您好，这个错误可能是因为你使用的Paddle版本不支持uniform_函数。在旧版本的Paddle中，uniform_函数是不存在的。

解决这个问题的方法是升级Paddle到最新版本，或者使用其他适合你的需求的随机数生成函数。

你可以通过以下命令升级Paddle：

```
pip install --upgrade paddlepaddle
```

**Comment by Ren-Xin** [comment]
已经是2.5了

**Comment by jiahy0825** [comment]
`uniform_` 是 inplace API，可以试试这样调用：`x.uniform_()`
