### ISSUE TITLE
新首页草稿，请大家来提意见。

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#604]
![19c7a6b5cd95ae263deab9352](https://cloud.githubusercontent.com/assets/1908992/20592423/52489fae-b268-11e6-8166-0e683d1e14ce.jpg)

首页展示的案例我选了三个，并配上一部分文案。但是感觉不够专业，希望大家踊跃贡献。

**Comment by llxxxll** [comment]
> 是不是标题短点儿？比如“易学易用的分布式深度学习平台”？
by @wangkuiyi 

> 兴趣偏好没有图，还有最下面的四点，解释的地方，有些不通顺，得改改
by @luotao1

**Comment by wangkuiyi** [comment]
1. 是不是标题短点儿？比如“易学易用的分布式深度学习平台”？
1. “图像识别”==>"机器视觉“
1. ”语言情绪“==>“自然语言理解”
1. “预测兴趣偏好”==>“搜索结果排序”

**Comment by gangliao** [comment]
丰富的算法服务看起来不丰富啊 可以  2 x 2列 四个场景吧

**Comment by llxxxll** [comment]
@gangliao 方便给一些候选项吗？

**Comment by gangliao** [comment]
demo那些主题，难道都不是候选么。。

**Comment by llxxxll** [comment]
这是目前的demo主题，选入首页的标准为有趣、易读、有意义。

图像
- 图像分类 这是第一个案例

自然语言处理
- 情感分析  这是第二个案例
- 文本生成  
- 词性标注

推荐
- MovieLens数据集  （数据集不是案例）
- MovieLens评分回归  这是第三个案例

常用模型
- ImageNet: ResNet
- Embedding: Chinese Word

**Comment by luotao1** [comment]
常用模型不用放吧

**Comment by llxxxll** [comment]
那就暂定三个？如果未来有更多，可以纵向拓展。
- 机器视觉
- 自然语言理解
- 搜索引擎排序

**Comment by luotao1** [comment]
易用性：为用户提供了直观、灵活的数据接口和模型配置接口
灵活性：支持CNN、RNN等多种神经网络结构和优化算法。简单书写配置文件即可实现复杂模型。
高效性：在计算、存储、通信、架构等方面都做了高效优化，充分发挥各种资源的性能。
扩展性：全面支持多核、多GPU、多机环境。轻松应对大规模数据训练需求。

将“可伸缩性”换成3个字的“扩展性”，因为其他几个都是3个字的。

**Comment by qingqing01** [comment]
1. 技术和服务优势图  -> 技术和服务优势 ?
2. 这项里面增加： 易部署： 广泛支持百度产品线，比如大规模图像分类、CTR预估、OCR识别、搜索排序、推荐系统、病毒检测等。

**Comment by drinktee** [comment]
logo作为项目的标志是不是可以大一些

**Comment by reyoung** [comment]
Closed due to not responded for long time. Reopen it if it is needed.
