### ISSUE TITLE
paddleocr Error after package exe

### ISSUE THREAD

**Issue by zzqgithu** [PaddlePaddle/Paddle#60400]
[Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI105922\\paddleocr\\ppocr\\utils\\ppocr_keys_v1.txt'
I can add ppocr_keys_v1.txt to this directory, the new directory after each software restart is in temp, but it must be added once after each restart. Is there any other way to avoid this problem.

**Comment by JunnYu** [comment]
This is a problem with PaddleOCR. You can ask questions here: https://github.com/PaddlePaddle/PaddleOCR/issues
