### ISSUE TITLE
Zipping an iterable of 1D tensors creates list of scalars rather than 1D tensors

### ISSUE THREAD

**Issue by Sam-Armstrong** [PaddlePaddle/Paddle#60459]
### bug描述 Describe the Bug

I've noticed that the behaviour of zipping tuples of one dimensional tensors has changing between Paddle 2.5.2 and Paddle 2.6.0. As of 2.6.0, zipping a tuple of one dimensional tensors causes the resulting tensors to be scalars (have no shape), whereas on 2.5.2 they would be 1D tensors with a single entry. Could you clarify if this was an intended change? 

Here is a minimal example of the change of behaviour:

```
import paddle

x = paddle.to_tensor([1, 2, 3])
args = (x,)
print([a for a in zip(*args)])
```

**Paddle 2.5.2**
[
    (Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True, [1]),),
    (Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True, [2]),),
    (Tensor(shape=[1], dtype=int64, place=Place(cpu), stop_gradient=True, [3]),)
]

**Paddle 2.6.0**
[
(Tensor(shape=[], dtype=int64, place=Place(cpu), stop_gradient=True, 1),),
(Tensor(shape=[], dtype=int64, place=Place(cpu), stop_gradient=True, 2),),
(Tensor(shape=[], dtype=int64, place=Place(cpu), stop_gradient=True, 3),)
]

**Comment by zhwesky2010** [comment]
@Sam-Armstrong Hello, this is reasonable. Paddle had some unreasonable designs before and now has been modified. The same 0-D result to other deep learning frameworks such as Pytorch: 

<img width="526" alt="infoflow 2024-01-03 10-45-36" src="https://github.com/PaddlePaddle/Paddle/assets/52485244/e52d6b6e-f0e6-47d7-838f-48650b28bde9">
