### ISSUE TITLE
How long can I see the updated document in website After merge the PR

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#6045]
How long can I see the updated document In [this web site](http://www.paddlepaddle.org/docs/develop/documentation/zh/operators.html#permalink-0-operators) when I modify code document and merge it.

**Comment by pkuyym** [comment]
I have updated the equation for huber loss op, but the html page doesn't display normally.

**Comment by luotao1** [comment]
@jetfuel Can you answer "How long can I see the updated document in website" in #6014?

**Comment by jetfuel** [comment]
@luotao1 Once the the #6014 is merged, you should be able to see updated content in about 10 minutes. Travis CI will update the contents.
