### ISSUE TITLE
[Bug Report] pr_59536 encountered an error of [operator < assign > error] while running inference on the mask_rcnn model.

### ISSUE THREAD

**Issue by EmmonsCurse** [PaddlePaddle/Paddle#60470]
### 0. Error Description
After the merge of https://github.com/PaddlePaddle/Paddle/pull/59536 which 'add complex support for assign value' on paddle, an error while running inference on the mask_rcnn model as shown below:

```
>       predictor.run()
E       RuntimeError: In user code:
E
E           File "tools/export_model.py", line 116, in <module>
E             main()
E           File "tools/export_model.py", line 112, in main
E             run(FLAGS, cfg)
E           File "tools/export_model.py", line 79, in run
E             trainer.export(FLAGS.output_dir)
E           File "/root/workspace/base/PaddleDetection/ppdet/engine/trainer.py", line 1178, in export
E             save_dir)
E           File "/root/workspace/base/PaddleDetection/ppdet/engine/trainer.py", line 1137, in _get_infer_cfg_and_input_spec
E             input_spec, static_model.forward.main_program,
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 563, in main_program
E             concrete_program = self.concrete_program
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 479, in concrete_program
E             return self.concrete_program_specify_input_spec(input_spec=None)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
E             *desired_input_spec)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
E             concrete_program, partial_program_layer = self._program_cache[cache_key]
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
E             self._caches[item] = self._build_once(item)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
E             **cache_key.kwargs)
E           File "<decorator-gen-99>", line 2, in from_func_spec
E
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
E             return wrapped_func(*args, **kwargs)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
E             return func(*args, **kwargs)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
E             outputs = static_func(*inputs)
E           File "/tmp/tmpjfo7jgl7.py", line 100, in forward
E             false_fn_5, (), (inputs, self), (out,))
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
E             return true_fn(*true_args) if pred else false_fn(*false_args)
E           File "/tmp/tmpjfo7jgl7.py", line 83, in false_fn_5
E             for_loop_body_0, [inputs_list, __for_loop_var_index_0])
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
E             loop_vars = _run_py_while(cond, body, loop_vars)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
E             loop_vars = body(*loop_vars)
E           File "/tmp/tmpjfo7jgl7.py", line 78, in for_loop_body_0
E             dy2static.convert_call(self.get_pred)())
E           File "/tmp/tmpauay3ecx.py", line 29, in get_pred
E             (bbox_num, bbox_pred, mask_pred, output)))
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
E             return true_fn(*true_args) if pred else false_fn(*false_args)
E           File "/root/workspace/base/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 150, in get_pred
E             bbox_pred, bbox_num, mask_pred = self._forward()
E           File "/tmp/tmpsrjl9_kk.py", line 103, in _forward
E             __return_value_0, body_feats, self), (__return_value_0, rois, rois_num)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
E             return true_fn(*true_args) if pred else false_fn(*false_args)
E           File "/root/workspace/base/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 114, in _forward
E             # rescale the prediction back to origin image
E           File "/tmp/tmptfuoxamx.py", line 213, in get_pred
E             __return_value_6, bbox_num, bboxes, scale_factor)))
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
E             return true_fn(*true_args) if pred else false_fn(*false_args)
E           File "/tmp/tmptfuoxamx.py", line 112, in true_fn_51
E             bboxes, i))
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
E             return true_fn(*true_args) if pred else false_fn(*false_args)
E           File "/tmp/tmptfuoxamx.py", line 102, in true_fn_49
E             bbox_num, bboxes])
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
E             loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
E             loop_vars = control_flow.while_loop(cond, body, loop_vars)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 1251, in while_loop
E             map_structure(assign_skip_lod_tensor_array, output_vars, loop_vars)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 204, in map_structure
E             return pack_sequence_as(structure[0], [func(*x) for x in entries])
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 204, in <listcomp>
E             return pack_sequence_as(structure[0], [func(*x) for x in entries])
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 1148, in assign_skip_lod_tensor_array
E             assign(input, output)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/tensor.py", line 617, in assign
E             type='assign', inputs={'X': [input]}, outputs={'Out': [output]})
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
E             return self.main_program.current_block().append_op(*args, **kwargs)
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3184, in append_op
E             attrs=kwargs.get("attrs", None))
E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2224, in __init__
E             for frame in traceback.extract_stack():
E
E           PreconditionNotMetError: Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 24, memory's size is 0.
E             [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):24 > memory_size():0.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:55)
E             [operator < assign > error]
```

### 1. Operating environment
PaddlePaddle version: develop
OS version: CentOS
Python version: 3.8
CPU info: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz

### The problem recurrence steps

1. Install paddlepaddle_whl and Install dependency package
```
git clone https://github.com/PaddlePaddle/PaddleTest.git --depth=1

cd ./PaddleTest/inference/python_api_test

# requirements
python -m pip install -r ./requirements.txt -i https://mirror.baidu.com/pypi/simple

# download paddlepaddle_whl
# this error_pr(failed)
wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc82-Cuda112-Trtoff-Py38-Compile/c1d78603ca6d818aec775733521e04db9c145716/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl

# the previous commit of error_pr(passed) [Optional]
# wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc82-Cuda112-Trtoff-Py38-Compile/76ce9bb2de84ee6ea052cfde6ce269be1e4d8baf/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl

# install and check paddlepaddle_whl
python -m pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl

python -c "import paddle.inference as paddle_infer;print(paddle_infer.get_version())"
```
2. run case 
```
# Taking MKL-DNN inference as an example.
cd ./test_det_model
python -m pytest -m server -k mkldnn --disable-warnings -sv test_mask_rcnn_mkldnn.py
```

### 其他补充信息 Additional Supplementary Information

@zyt1024 @luotao1 @GGBond8488 Is this problem reasonable？If not, can you help me solve this?

**Comment by GGBond8488** [comment]
@zyt1024 这个应该和之前那个CI问题是一个问题，帮忙解答一下吧

**Comment by zyt1024** [comment]
> ### bug描述 Describe the Bug
> ### 0. Error Description
> After the merge of #59536 which 'add complex support for assign value' on paddle, an error while running inference on the mask_rcnn model as shown below:
> 
> ```
> >       predictor.run()
> E       RuntimeError: In user code:
> E
> E           File "tools/export_model.py", line 116, in <module>
> E             main()
> E           File "tools/export_model.py", line 112, in main
> E             run(FLAGS, cfg)
> E           File "tools/export_model.py", line 79, in run
> E             trainer.export(FLAGS.output_dir)
> E           File "/root/workspace/base/PaddleDetection/ppdet/engine/trainer.py", line 1178, in export
> E             save_dir)
> E           File "/root/workspace/base/PaddleDetection/ppdet/engine/trainer.py", line 1137, in _get_infer_cfg_and_input_spec
> E             input_spec, static_model.forward.main_program,
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 563, in main_program
> E             concrete_program = self.concrete_program
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 479, in concrete_program
> E             return self.concrete_program_specify_input_spec(input_spec=None)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 517, in concrete_program_specify_input_spec
> E             *desired_input_spec)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 427, in get_concrete_program
> E             concrete_program, partial_program_layer = self._program_cache[cache_key]
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 723, in __getitem__
> E             self._caches[item] = self._build_once(item)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 714, in _build_once
> E             **cache_key.kwargs)
> E           File "<decorator-gen-99>", line 2, in from_func_spec
> E
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
> E             return wrapped_func(*args, **kwargs)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/base.py", line 51, in __impl__
> E             return func(*args, **kwargs)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 662, in from_func_spec
> E             outputs = static_func(*inputs)
> E           File "/tmp/tmpjfo7jgl7.py", line 100, in forward
> E             false_fn_5, (), (inputs, self), (out,))
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
> E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
> E             return true_fn(*true_args) if pred else false_fn(*false_args)
> E           File "/tmp/tmpjfo7jgl7.py", line 83, in false_fn_5
> E             for_loop_body_0, [inputs_list, __for_loop_var_index_0])
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 45, in convert_while_loop
> E             loop_vars = _run_py_while(cond, body, loop_vars)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 59, in _run_py_while
> E             loop_vars = body(*loop_vars)
> E           File "/tmp/tmpjfo7jgl7.py", line 78, in for_loop_body_0
> E             dy2static.convert_call(self.get_pred)())
> E           File "/tmp/tmpauay3ecx.py", line 29, in get_pred
> E             (bbox_num, bbox_pred, mask_pred, output)))
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
> E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
> E             return true_fn(*true_args) if pred else false_fn(*false_args)
> E           File "/root/workspace/base/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 150, in get_pred
> E             bbox_pred, bbox_num, mask_pred = self._forward()
> E           File "/tmp/tmpsrjl9_kk.py", line 103, in _forward
> E             __return_value_0, body_feats, self), (__return_value_0, rois, rois_num)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
> E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
> E             return true_fn(*true_args) if pred else false_fn(*false_args)
> E           File "/root/workspace/base/PaddleDetection/ppdet/modeling/architectures/mask_rcnn.py", line 114, in _forward
> E             # rescale the prediction back to origin image
> E           File "/tmp/tmptfuoxamx.py", line 213, in get_pred
> E             __return_value_6, bbox_num, bboxes, scale_factor)))
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
> E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
> E             return true_fn(*true_args) if pred else false_fn(*false_args)
> E           File "/tmp/tmptfuoxamx.py", line 112, in true_fn_51
> E             bboxes, i))
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 211, in convert_ifelse
> E             out = _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 257, in _run_py_ifelse
> E             return true_fn(*true_args) if pred else false_fn(*false_args)
> E           File "/tmp/tmptfuoxamx.py", line 102, in true_fn_49
> E             bbox_num, bboxes])
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 43, in convert_while_loop
> E             loop_vars = _run_paddle_while_loop(cond, body, loop_vars)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 53, in _run_paddle_while_loop
> E             loop_vars = control_flow.while_loop(cond, body, loop_vars)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 1251, in while_loop
> E             map_structure(assign_skip_lod_tensor_array, output_vars, loop_vars)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 204, in map_structure
> E             return pack_sequence_as(structure[0], [func(*x) for x in entries])
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/utils.py", line 204, in <listcomp>
> E             return pack_sequence_as(structure[0], [func(*x) for x in entries])
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/control_flow.py", line 1148, in assign_skip_lod_tensor_array
> E             assign(input, output)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layers/tensor.py", line 617, in assign
> E             type='assign', inputs={'X': [input]}, outputs={'Out': [output]})
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
> E             return self.main_program.current_block().append_op(*args, **kwargs)
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 3184, in append_op
> E             attrs=kwargs.get("attrs", None))
> E           File "/usr/local/lib/python3.7/dist-packages/paddle/fluid/framework.py", line 2224, in __init__
> E             for frame in traceback.extract_stack():
> E
> E           PreconditionNotMetError: Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 24, memory's size is 0.
> E             [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):24 > memory_size():0.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:55)
> E             [operator < assign > error]
> ```
> 
> ### 1. Operating environment
> PaddlePaddle version: develop OS version: CentOS Python version: 3.8 CPU info: Intel(R) Xeon(R) Gold 6271C CPU @ 2.60GHz
> 
> ### The problem recurrence steps
> 1. Install paddlepaddle_whl and Install dependency package
> 
> ```
> git clone https://github.com/PaddlePaddle/PaddleTest.git --depth=1
> 
> cd ./PaddleTest/inference/python_api_test
> 
> # requirements
> python -m pip install -r ./requirements.txt -i https://mirror.baidu.com/pypi/simple
> 
> # download paddlepaddle_whl
> # this error_pr(failed)
> wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc82-Cuda112-Trtoff-Py38-Compile/c1d78603ca6d818aec775733521e04db9c145716/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
> 
> # the previous commit of error_pr(passed) [Optional]
> # wget -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/paddle-pipeline/Develop-GpuAll-LinuxCentos-Gcc82-Cuda112-Trtoff-Py38-Compile/76ce9bb2de84ee6ea052cfde6ce269be1e4d8baf/paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
> 
> # install and check paddlepaddle_whl
> python -m pip install paddlepaddle_gpu-0.0.0-cp38-cp38-linux_x86_64.whl
> 
> python -c "import paddle.inference as paddle_infer;print(paddle_infer.get_version())"
> ```
> 
> 2. run case
> 
> ```
> # Taking MKL-DNN inference as an example.
> cd ./test_det_model
> python -m pytest -m server -k mkldnn --disable-warnings -sv test_mask_rcnn_mkldnn.py
> ```
> 
> ### 其他补充信息 Additional Supplementary Information
> @zyt1024 @luotao1 @GGBond8488 Is this problem reasonable？If not, can you help me solve this?

Hello, I have reproduced this error and will fix it in the next few days.

**Comment by zyt1024** [comment]
@EmmonsCurse  Hello, We have identified the cause of the issue, and we will discuss a solution next week .

**Comment by EmmonsCurse** [comment]
> @EmmonsCurse Hello, We have identified the cause of the issue, and we will discuss a solution next week .

@zyt1024 OK, thanks and please synchronize with me after providing the solution for fixing~

**Comment by yuanlehome** [comment]
> @EmmonsCurse Hello, We have identified the cause of the issue, and we will discuss a solution next week .

Please fix it as soon as possible. Our business model also reported an error due to this issue.

**Comment by zyt1024** [comment]
> Please fix it as soon as possible. Our business model also reported an error due to this issue.

Okay, this bug can be fixed soon. If you are in a hurry, another solution is to save the model with the latest paddle.
