### ISSUE TITLE
官网的paddleInference的推理库下载连接打开为空，是不支持下载了吗

### ISSUE THREAD

**Issue by shangshanruowo** [PaddlePaddle/Paddle#60486]
### 问题描述 Issue Description

官网的paddleInference的推理库下载连接打开为空，是不支持下载了吗

### 版本&环境信息 Version & Environment Information

官网的paddleInference的推理库下载连接打开为空，是不支持下载了吗

**Comment by zxcd** [comment]
是指paddleInference哪个地方的哪个链接呢？

**Comment by shangshanruowo** [comment]
我找到了，在总页面前面可以下载，但你们那种文档里面的连接转不过去，你们可以更新一下，例如https://www.paddlepaddle.org.cn/inference/v2.6/guides/nv_gpu_infer/gpu_trt_infer.html这里的文档里面有下载linux和windows的推理库，但这个连接打不开，你们可以可以更新一下，里面好多连接都是https://paddleinference.paddlepaddle.org.cn/install/download_lib.html#linux跳在这里为空

**Comment by zxcd** [comment]
好的，感谢您的反馈，我们预计本周内会对文档链接进行修复。
