### ISSUE TITLE
TypeError: object of type 'int' has no len()， 求指导

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#605]
/baidu/idl/onekey/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/dataprovider_converter.py", line 128, in get_size
    return len(dat)
TypeError: object of type 'int' has no len()

下面的converter有问题么？爆了上面的错误..

input_types = [integer_sequence(4174), integer_sequence(36),integer_sequence(5), sparse_binary_vector_sequence(28469) ]
    converter = DataProviderConverter(input_types)
    TEST_DATA = [[2172, 1962, 4294967295, 1185, 66, 3138], [7, 25, 25, 25, 25, 25], [4, 4, 0, 4, 4, 4], [[476, 3447, 8583, 11213, 17474, 22378, 22414, 22450, 22504, 22540, 22742, 23371, 23750, 23939
, 25233, 26575, 27400], [477, 4687, 8373, 14719, 22380, 22415, 22468, 22504, 22540, 22943, 23318, 23529, 23939, 25091, 25904, 27497], [1455, 5546, 11553, 14019, 22381, 22433, 22468, 22504, 22540, 22
894, 23103, 23529, 23939, 24464, 26010, 27497], [2122, 7596, 10638, 15907, 20639, 22397, 22433, 22468, 22504, 22540, 22689, 23103, 23529, 23939, 24582, 26010, 27497], [3833, 6477, 13145, 15772, 1767
0, 22176, 22397, 22433, 22468, 22504, 22525, 22689, 23103, 23529, 24002, 24582, 26010, 27932], [782, 2873, 9549, 12962, 15771, 19364, 21889, 22397, 22433, 22468, 22487, 22546, 22689, 23103, 23600, 2
4196, 24582, 26507, 27691]]]
    inArg = converter(TEST_DATA)

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html#input-types 根据这个检查下，把每个input_types打出来看一下，就知道符不符合格式了。

**Comment by VamWolf** [comment]
thx. 两个问题1.  应该再套一个[] 2. 超了dim 了.
