### ISSUE TITLE
segment fault of test_conv2d_op_depthwise_conv in DCU

### ISSUE THREAD

**Issue by yuguo-Jack** [PaddlePaddle/Paddle#60500]
**segment fault of test_conv2d_op_depthwise_conv in DCU**

**环境**：使用Paddle-develop分支，commit：3e36271e62ae2251d536d48bab7c028590aeb2bd，或者2.5及以后版本，要求编译成完成。
**ctest命令**：ctest -R test_conv2d_op_depthwise_conv -VV
**现象**：会在单测反向时报段错误，可稳定复现。经初步排查后，认为该段错误并不是DTK运行时导致，是由Paddle引入的该bug，在2.5之前的版本均测试通过。
**结论**：最终段错误发生在initailized()：https://github.com/PaddlePaddle/Paddle/blob/3e36271e62ae2251d536d48bab7c028590aeb2bd/paddle/phi/core/device_context.cc#L157.
**排查**：该段错误只影响卷积中的deptnwise_conv2d单测，虽然conv反向时也调用ConvCudnnGradKernel，但并未出现段错误（诡异）。段错误在op代码中出现在https://github.com/PaddlePaddle/Paddle/blob/3e36271e62ae2251d536d48bab7c028590aeb2bd/paddle/phi/kernels/gpudnn/conv_grad_kernel.cu#L418 进一步跟进会定位到结论中代码位置。
**期望**：该bug和miopen应该没有关系，应该由paddle框架引入，由于涉及paddle框架的核心逻辑，不好修改，希望官方可以修复。

**Comment by qili93** [comment]
收到，我们后续定位下这个问题
