### ISSUE TITLE
2.6.1版本在windows 上进行OCR，使用CPU版本存在内存泄漏

### ISSUE THREAD

**Issue by raoyutian** [PaddlePaddle/Paddle#60510]
### bug描述 Describe the Bug

在win10上使用CPU预测库，使用PaddleOCR开启MKLDNN,进行文本检测与识别，
同一张图和OCR参数，连续循环10次，
使用2.6.1版本预测库，内存使用比2.5.2版本的多一倍，
2.6.1版本，1.2G内存（10次之后最终）
2.5.2版本，0.6G内存（10次之后最终）再多次循环，基本稳定在0.6G内存左右。

之前2.5.2版本，连续24小时测试OCR循环100万次，没有出现内存溢出，
2.6.1版本，循环不久就内存溢出了。

**Comment by GhostScreaming** [comment]
方便提供一下具体的复现环境和代码吗？

**Comment by raoyutian** [comment]
> 方便提供一下具体的复现环境和代码吗？
2.6.1是我自行编译的，下载的2.6.0的CPU版本的预测库也是同样的问题。
编译命令：
cmake .. -GNinja -DWITH_GPU=OFF -DWITH_PYTHON=OFF -DCMAKE_BUILD_TYPE=Release -DWITH_UNITY_BUILD=ON -DWITH_TESTING=OFF -DON_INFER=ON 


就是PaddleOCR的项目，C++代码编译的。
2.6.1CPU版本测试很多次，都会出现内存不断增长，
2.6.1GPU版本，同样图片，同样循环多次，内存使用稳定，没有出现增长的情况。
2.5.2以前的CPU,GPU版本，内存使用稳定，没有出现增长的情况。
使用OpenVINO底层推理，也没有内存增长问题。

-------------------------------------------------------------------------------------------
环境：
Win10，CPU13代I9
PaddleOCR V2.7,Paddle 2.6.1 CPU,开启MKLDNN加速。
PaddleOCR代码编译成动态库，初始化一次模型加载，后续循环调用检测识别。

**Comment by vivienfanghuagood** [comment]
我们会跟进

**Comment by LLee233** [comment]
Hi @raoyutian，可以麻烦详细描述一下吗？比如用的图片，模型和命令行之类的，感谢~

**Comment by zhanglirong1999** [comment]
Hi, @raoyutian ,请问问题解决了吗。能否具体提供一下win下vs的版本，以及具体模型等信息？

**Comment by raoyutian** [comment]
> Hi, @raoyutian ,请问问题解决了吗。能否具体提供一下win下vs的版本，以及具体模型等信息？
> Hi @raoyutian，可以麻烦详细描述一下吗？比如用的图片，模型和命令行之类的，感谢~

环境：
Win10，CPU13代I9，VS2019社区版
PaddleOCR V2.7,Paddle 2.6.1 CPU,开启MKLDNN加速。
PaddleOCR代码编译成动态库，初始化一次模型加载，后续循环调用检测识别。

图片找一个文本行较多的，比如一张A4文档的图片，使用PPOCRV4-中英文版轻量模型，
使用C++推理，逻辑是，加载初始化模型，然后后续直接检测与识别，不销毁预测引擎，就这样循环调用检测识别，内存慢慢就升了。

初步估计是MKLDNN的问题。

**Comment by LLee233** [comment]
> > Hi, @raoyutian ,请问问题解决了吗。能否具体提供一下win下vs的版本，以及具体模型等信息？
> > Hi @raoyutian，可以麻烦详细描述一下吗？比如用的图片，模型和命令行之类的，感谢~
> 
> 环境： Win10，CPU13代I9，VS2019社区版 PaddleOCR V2.7,Paddle 2.6.1 CPU,开启MKLDNN加速。 PaddleOCR代码编译成动态库，初始化一次模型加载，后续循环调用检测识别。
> 
> 图片找一个文本行较多的，比如一张A4文档的图片，使用PPOCRV4-中英文版轻量模型， 使用C++推理，逻辑是，加载初始化模型，然后后续直接检测与识别，不销毁预测引擎，就这样循环调用检测识别，内存慢慢就升了。
> 
> 初步估计是MKLDNN的问题。

Hi @raoyutian ，请问可以提供一下复现代码吗？我们这边用exon和core cpu分别在linux和windows上尝试复现了，也尝试修改了ocr的代码进行重复检测与识别，但都没有观察到内存溢出的情况。

**Comment by raoyutian** [comment]
如果不能复现，就关了吧。

**Comment by cmathx** [comment]
paddleocr内存泄漏的问题，有啥解决方案吗？看了paddlepaddle和paddleocr相关的issue，paddle和paddleocr都更新到最新版本，也尝试了相关内存管理的参数，还没有解决paddleocr的内存泄漏问题。

**Comment by zhanglirong1999** [comment]
@cmathx , hi, 如果是使用paddleocr时，开启了MKLDNN, 有以下两个建议可以避免和减轻内存泄漏问题。 1. 把mkldnn_cache_capacity调大，默认为10，调大可以增大cache的命中率，减少内存的创建。 2. 手动对输入的图片数据集进行预处理，让输入的图片尽可能同size.(如统一为最大一张图片的宽高，其他的小的图片边缘padding为0，这样的作法不会影响准确性，并且能将图片size统一，大大减小内存的重复创建)

**Comment by raoyutian** [comment]
其实内存泄漏问题，我在提本issue之前就已经找到原因了。
看到大家到现在还没有找到原因在哪里。我就公布解决方案吧：
内存泄漏的根本原因是2.6.1版本引用的第三方组件MKLDNN.dll导致的内存泄漏。
需要更换MKLDNN的版本。找到一个没有内存泄漏的版本。例如2.5.2版本引用的mkldnn的版本。
需要自己编译MKLDNN源代码。

**Comment by cmathx** [comment]
> @cmathx , hi, 如果是使用paddleocr时，开启了MKLDNN, 有以下两个建议可以避免和减轻内存泄漏问题。 1. 把mkldnn_cache_capacity调大，默认为10，调大可以增大cache的命中率，减少内存的创建。 2. 手动对输入的图片数据集进行预处理，让输入的图片尽可能同size.(如统一为最大一张图片的宽高，其他的小的图片边缘padding为0，这样的作法不会影响准确性，并且能将图片size统一，大大减小内存的重复创建)

mkldnn_cache_capacity调整试过，泄漏问题依旧村子啊。第2个点，我试下看看

**Comment by zhanglirong1999** [comment]
@cmathx ,hi, 我们测试发现开启MKLDNN导致内存泄漏，确实是paddle中MLKDNN库的问题(具体出问题的版本为3.2, brgemm kernels不断创建导致的），我们已经将它更新为最新的3.4版本，测试下来内存泄漏问题已经得到解决。如果需要避免此问题，可以拉取最新paddle代码进行编译。

cc @raoyutian

**Comment by cmathx** [comment]
貌似没有解决。我拉取了git clone了最新的仓库，版本是2.8.0；依旧存在内存泄漏

Zhang,Lirong ***@***.***> 于2024年6月19日周三 14:42写道：

**Comment by cmathx** [comment]
是先拉取最新的paddle代码，然后再安装最新版本的paddleocr？
最新paddle版本是多少？

**Comment by zhanglirong1999** [comment]
@cmathx ，hi, 这个问题本质和paddleocr无关，是paddleocr调用了paddle导致的，所以要解决需要的是最新的paddle，拉取paddle最新代码并编译，此时会得到paddlepaddle-xxxxx.whl的包，通过python pip即可。因为你现在是直接pip官方的paddle，官方提供的paddle whl还是老的版本，所以无法解决此问题，需要手动使用最新paddle的whl包。当然重新编译paddle可能比较耗时，最快速和暂时解决的方法还是之前说的，可以尝试一下对数据集进行预处理，可能更快一些~

**Comment by cmathx** [comment]
多谢，我试下。采用paddle官方模型（不是openvino、onnx），基于gpu做inference，目前应该没有显存泄漏的问题？

Zhang,Lirong ***@***.***> 于2024年6月19日周三 15:03写道：

**Comment by zhanglirong1999** [comment]
@cmathx GPU应该暂时还没发现类似的问题，现在看起来应该是在CPU和CPU上开启MKLDNN的情况下会出现oom.

**Comment by cmathx** [comment]
ok

Zhang,Lirong ***@***.***> 于2024年6月19日周三 15:12写道：

**Comment by raoyutian** [comment]
@cmathx @zhanglirong1999 这里给出解决方案：下载onednn代码，切换版本到3.1.1，修改makelist文件，版本改为3.2.1，cmake编译，dnnl.dll改文件名为mkldnn.dll,即可。或者加QQ群：318860399，找我直接发编译好的文件。把mkldnn.dll覆盖到你的有关文件目录下即可。python版本覆盖到PythonXX\Lib\site-packages\paddle\libs目录下，其他语言看着覆盖即可。
