### ISSUE TITLE
打开WITH_GLOO之后，编译报错

### ISSUE THREAD

**Issue by tiancaitzp** [PaddlePaddle/Paddle#60520]
### bug描述 Describe the Bug

编译选项：
-DCMAKE_INSTALL_PREFIX=output
-DPY_VERSION=3.7 
-DCMAKE_BUILD_TYPE=Release 
-DWITH_GPU=OFF 
-DWIT H_XPU=ON 
-DON_INFER=ON 
-DWITH_PYTHON=ON 
-DWITH_AVX=ON 
-DWITH_MKL=ON 
-DWITH_MKLDNN=ON 
-DWITH_XPU_KP=ON 
-DWITH_XPU_BKCL=ON 
-DWITH_DISTRIBUTE=OFF 
-DWITH_NCCL=OFF -DPYTHON_INCLUDE_DIR=${PYTHON_ROOT}/include/python3.7m 
-DPYTHON_LIBRARY=${PYTHON_ROOT}/lib/libpython3.7m.so 
-DPYTHON_EXECUTABLE=${PYTHON_ROOT}/bin/python3 -DADD_INCLUDE_DIR=${PYTHON_ROOT}/include 
-DADD_LIBRARY=${PYTHON_ROOT}/lib 
-DWITH_BOX_PS=ON     
-DWITH_GLOO=ON

编译错误信息：
[ 24%] Built target eager_final_state_codegen
In file included from /Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/math.h:11,
                 from /Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/algorithm.h:14,
                 from /Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/barrier.h:11,
                 from /Paddle/PaddleBox/Paddlebox-github/Paddle/paddle/fluid/framework/fleet/gloo_wrapper.h:32,
                 from /Paddle/PaddleBox/Paddlebox-github/Paddle/paddle/fluid/framework/fleet/gloo_wrapper.cc:12:
/Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/types.h: In member function 'gloo::float16& gloo::float16::operator+=(const gloo::float16&)':
/Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/types.h:165:35: error: implicitly-declared 'constexpr gloo::float16::float16(const gloo::float16&)' is deprecated [-Werror=deprecated-copy]
  165 |     float r = cpu_half2float(*this) + cpu_half2float(rhs);
      |                                   ^
/Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/types.h:112:12: note: because 'gloo::float16' has user-provided 'gloo::float16& gloo::float16::operator=(const gloo::float16&)'
  112 |   float16& operator=(const float16& rhs) {
      |            ^~~~~~~~
/Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/types.h:84:30: note:   initializing argument 1 of 'float gloo::cpu_half2float(gloo::float16)'
   84 | float cpu_half2float(float16 h);
      |                      ~~~~~~~~^
/Paddle/PaddleBox/Paddlebox-github/Paddle/build/third_party/install/gloo/include/gloo/types.h:165:57: error: implicitly-declared 'constexpr gloo::float16::float16(const gloo::float16&)' is deprecated [-Werror=deprecated-copy]
  165 |     float r = cpu_half2float(*this) + cpu_half2float(rhs);

### 其他补充信息 Additional Supplementary Information
使用GCC10编译
_No response_

**Comment by YanhuiDua** [comment]
你好，可以参考 https://github.com/tsduck/tsduck/issues/205，添加-Wno-error=deprecated-copy至cmake文件，避免出现这个报错来进行编译；

可以尝试下使用这个编译命令：cmake .. -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
  -DPY_VERSION=3.9 -DPYTHON_EXECUTABLE=`which python3` -DWITH_CUSTOM_DEVICE=OFF \
  -DWITH_TESTING=OFF -DON_INFER=ON -DWITH_DISTRIBUTE=ON -DWITH_ARM=OFF \
  -DWITH_XPU=ON -DWITH_XPU_BKCL=ON -DWITH_UBUNTU=ON
