### ISSUE TITLE
[Document] The Set Command-line Parameters module of develop and 0.10.0 branch introduce the instruction of version 0.9.0.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#6053]
官网文档中的develop分支和0.10.0分支中的设置命令行参数部分介绍的是0.9.0版本中的用法，http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/howto/usage/cmd_parameter/index_cn.html
而0.9.0分支中对应的命令行参数的介绍链接都坏掉了：
http://www.paddlepaddle.org/docs/0.9.0/documentation/zh/ui/index.html#id3
是否应该将这部分内容放在0.9.0分支下呢？
![image](https://user-images.githubusercontent.com/11489242/33374452-e3bc382a-d4cb-11e7-9845-9ffddef239cd.png)

**Comment by luotao1** [comment]
solved by https://github.com/PaddlePaddle/PaddlePaddle.org/issues/347
