### ISSUE TITLE
编译问题：‘__m256’ was not declared in this scope 

### ISSUE THREAD

**Issue by mayang002** [PaddlePaddle/Paddle#60539]
### error: ‘__m256’ was not declared in this scope，这个编译错误可能是什么原因？
![image](https://github.com/PaddlePaddle/Paddle/assets/77949147/9c9994a2-9cd9-460b-b112-83eb15501316)

**Comment by YanhuiDua** [comment]
你好，使用的是什么硬件环境呢？像是指令集不支持，参考：https://github.com/PaddlePaddle/Paddle-Lite/issues/5869

**Comment by mayang002** [comment]
@YanhuiDua 是个虚拟化环境，看了下是因为当前环境不支持 avx 指令集导致的，感谢~
