### ISSUE TITLE
[Custom Device] Custom Device在FP16混合精度下不能使用融合算子Pass

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#60542]
### bug描述 Describe the Bug

[paddle/fluid/inference/api/analysis_predictor.cc](https://github.com/PaddlePaddle/Paddle/pull/60541/files#diff-f6feda974e038d722114830a39bea985fd814e28bd86bcd33248aece3c3181a4)

这段代码是我很久以前提交的，过去未考虑现在的情况。
现在Custom Device已经能支持融合算子，只需要完成对应的Kernel。
ClearPass会导致在FP16下，Custom Device的融合算子Pass失效

修复PR https://github.com/PaddlePaddle/Paddle/pull/60541

**Comment by YanhuiDua** [comment]
你好，感谢贡献，PR已经approve

**Comment by engineer1109** [comment]
merged close
