### ISSUE TITLE
Ubuntu编译源码问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6054]
我按照[官网的教程](http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html)在`cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF`提示`does not appear to contain CMakeList.txt`这个文件是哪里的，项目中有很多这个文件

**Comment by NHZlX** [comment]
这里有一个中文教程  http://www.jianshu.com/p/c6264cd5f5c7

**Comment by Xreki** [comment]
> 这里有一个中文教程 http://www.jianshu.com/p/c6264cd5f5c7

@NHZlX 私人教程啊，:+1:

> does not appear to contain CMakeList.txt

@yeyupiaoling 这个是看你的Paddle源码在哪个目录了，一般情况是：
```
$ cd Paddle
$ mkdir build
$ cd build
$ cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF ..
```

最后关键的 **..** ，是代码源码所在目录。

**Comment by yeyupiaoling** [comment]
@NHZlX 谢谢，这个教程非常好用，很详细，我之所以少了那个文件是因为没写..

**Comment by yeyupiaoling** [comment]
@Xreki 对，就是少了那两个..希望这种博客越来越多
