### ISSUE TITLE
paddlehub运行报错

### ISSUE THREAD

**Issue by 123newday** [PaddlePaddle/Paddle#60581]
### bug描述 Describe the Bug

按照文档中的步骤执行至hub install u2_conformer_aishell时，
报错：AttributeError: module 'paddle' has no attribute 'fluid'
![截屏2024-01-05 11 23 11](https://github.com/PaddlePaddle/Paddle/assets/25628347/fd975ee8-bdef-4d87-8418-d67e00ce56f8)

参考文档：
https://github.com/PaddlePaddle/PaddleHub/tree/develop/modules/audio/asr/u2_conformer_aishell
环境依赖：
paddlepaddle-gpu          2.6.0.post112
paddlehub                 2.1.0
python 3.8

**Comment by qili93** [comment]
Paddle 2.6之后fluid接口已经废弃，但是paddlehub中的套件代码应该还没有来得及更新，因为最近Paddle2.6版本刚发布，套件代码都还没来得及更新到2.6版本，所以会有这里不兼容升级导致的额问题。建议使用老版本的Paddle试一下这个模型。

由于此模型的合入PR https://github.com/PaddlePaddle/PaddleHub/pull/1678 时间较早 (Nov 1, 2021)，建议找这个时间点附近的Paddle版本进行尝试。

这个时间点附近的Paddle版本是 (Nov 2, 2021) https://paddle-wheel.bj.bcebos.com/2.2.0/linux/linux-cpu-mkl-avx/paddlepaddle-2.2.0-cp38-cp38-linux_x86_64.whl

也有可能当时同学是基于develop分支开发的，那Paddle版本可以再高一个版本，可以试试 https://paddle-wheel.bj.bcebos.com/2.3.0/linux/linux-cpu-mkl-avx/paddlepaddle-2.3.0-cp38-cp38-linux_x86_64.whl

所有Paddle的历史版本参考 https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html
