### ISSUE TITLE
2.6.0版本源码编译报错“YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'”

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#60580]
### bug描述 Describe the Bug

2.6.0版本源码编译报错
Generate dygraph file structure at path: /home/Paddle2.6.0/paddle/fluid/eager/generated
Eager prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Static prim api code generator
copy tmp_xxx_prim_api to xxx_prim_api
Prim tensor operants code generator
copy prim xxx_tensor_operants.tmp to xxx_tensor_operants
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.h.tmp /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.h
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.cc.tmp /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.cc
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op_vjp.cc.tmp /home/Paddle2.6.0
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (\.cu)$
                          ^~~~~~~
Error reading /home/Paddle2.6.0/.clang-format: Invalid argument
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.h.tmp /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.h
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.cc.tmp /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op.cc
copy if different /home/Paddle2.6.0/paddle/fluid/pir/dialect/operator/ir/pd_op_vjp.cc.tmp /home/Paddle2.6.0

**Comment by yangy996** [comment]
问题出在 add_subdirectory(pir) 里，添加pir模块后，报上面的错误，在2.5.2中可以通过WITH_IR控制可以关闭

**Comment by yangy996** [comment]
路径：/home/Paddle2.6.0/paddle/fluid/CMakeLists.txt中

**Comment by qili93** [comment]
您好，根据报错提示

```
Error reading /home/sunway-cloud-dam-py/Paddle2.6.0/.clang-format: Invalid argument
YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
IncludeIsMainSourceRegex: (.cu)$
```

错误是由于clang-format导致的，请确认下您环境中的clang-format的版本信息是否正确，可以通过如下命令查看版本信息
![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/84c81b1d-1760-4527-bbfb-65ffeea2223f)

可能是由于clang-format路径配置不正确或者版本过低导致无法识别Paddle代码中 https://github.com/PaddlePaddle/Paddle/blob/develop/.clang-format#L28 这个的配置导致的

<img width="491" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/16605440/d29d871d-3bb3-4d2a-ab42-ee441730f5f5">

您可以参考飞桨的官方文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html，查看clang-format的版本要求如下

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/a38fb58f-3f02-4ade-84de-aa186519ccd1)

**Comment by yangy996** [comment]
> 您好，根据报错提示
> 
> ```
> Error reading /home/sunway-cloud-dam-py/Paddle2.6.0/.clang-format: Invalid argument
> YAML:28:27: error: unknown key 'IncludeIsMainSourceRegex'
> IncludeIsMainSourceRegex: (.cu)$
> ```
> 
> 错误是由于clang-format导致的，请确认下您环境中的clang-format的版本信息是否正确，可以通过如下命令查看版本信息 ![image](https://private-user-images.githubusercontent.com/16605440/294395706-84c81b1d-1760-4527-bbfb-65ffeea2223f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Mzk5MTgsIm5iZiI6MTcwNDQzOTYxOCwicGF0aCI6Ii8xNjYwNTQ0MC8yOTQzOTU3MDYtODRjODFiMWQtMTc2MC00NTI3LWJiZmItNjVmZmVlYTIyMjNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJkNzlmNzIyMzAwMDViNmMwOThhYzgzMTc5Y2IzNTE1YmYwOGNhMDJkYzBjMGZkM2U3ZDExMzIxY2JmYmJlNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ADZP01WMt9mGMeDKj-LixOVWOj8X-eWb__h9jxQIVL0)
> 
> 可能是由于clang-format路径配置不正确或者版本过低导致无法识别Paddle代码中 https://github.com/PaddlePaddle/Paddle/blob/develop/.clang-format#L28 这个的配置导致的
> 
> <img alt="image" width="491" src="https://private-user-images.githubusercontent.com/16605440/294396003-d29d871d-3bb3-4d2a-ab42-ee441730f5f5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Mzk5MTgsIm5iZiI6MTcwNDQzOTYxOCwicGF0aCI6Ii8xNjYwNTQ0MC8yOTQzOTYwMDMtZDI5ZDg3MWQtM2JiMy00ZDJhLWFiNDItZWU0NDE3MzBmNWY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI4M2UzYWM2ZjFkOWIzNGRiMjU3YzFiMzBiZDUyYzEyZmZhYTQxZjRjNzE4MDU1ZWI2MGEzMWYzYWE1MmZmZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AAZI85OcnivJViPppgUgfj7uy6zavThl04fh6WjT1_E">
> 您可以参考飞桨的官方文档 [https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html，查看clang-format的版本要求如下](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/dev_guides/git_guides/codestyle_check_guide_cn.html%EF%BC%8C%E6%9F%A5%E7%9C%8Bclang-format%E7%9A%84%E7%89%88%E6%9C%AC%E8%A6%81%E6%B1%82%E5%A6%82%E4%B8%8B)
> 
> ![image](https://private-user-images.githubusercontent.com/16605440/294396117-a38fb58f-3f02-4ade-84de-aa186519ccd1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ0Mzk5MTgsIm5iZiI6MTcwNDQzOTYxOCwicGF0aCI6Ii8xNjYwNTQ0MC8yOTQzOTYxMTctYTM4ZmI1OGYtM2YwMi00YWRlLTg0ZGUtYWExODY1MTljY2QxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA1VDA3MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1Mzc3NDc4YWNjYzJiYjg1OTJkYjI0ODA1NWJhM2MzYTEzZmIzM2VlNzIwNzI0ZWVlMDYwYzcyOTkwNzRkZDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6MHV7KyyGqNd40hZ_4TvjLPeCnXh2dE8MtrBgUKThXE)

奇怪了，为啥同样的环境，编译2.5.2版本就是正常的

**Comment by qili93** [comment]
请问您2.6.0的编译是否在升级clang-format版之后解决了呢？谢谢

**Comment by yangy996** [comment]
> 请问您2.6.0的编译是否在升级clang-format版之后解决了呢？谢谢

嗯嗯，解决了

**Comment by qili93** [comment]
好的，那我就关闭卡片了，谢谢～
