### ISSUE TITLE
CUDA error(98), invalid device function.

### ISSUE THREAD

**Issue by zhang-jinqi** [PaddlePaddle/Paddle#60587]
通过官网介绍，安装paddlepaddle-gpu2.4.2版本后，无法进行模型的训练
Traceback (most recent call last):
  File "/data2/app/TRT/info_category/service/lod_pre_api.py", line 394, in train_model_thread
    trainer.train(train_dataset, epochs=config_data['TRAIN']['EPOCHS'], batch_size=config_data['TRAIN']['BATCH_SIZE']
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddlehub/finetune/trainer.py", line 212, in train
    loss, metrics = self.training_step(batch, batch_idx)
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddlehub/finetune/trainer.py", line 352, in training_step
    result = self.model.training_step(batch, batch_idx)
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddlehub/module/nlp_module.py", line 502, in training_step
    predictions, avg_loss, metric = self(input_ids=batch[0], token_type_ids=batch[1], labels=batch[2])
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 1012, in __call__
    return self.forward(*inputs, **kwargs)
  File "/root/.paddlehub/modules/bert_base_chinese/module.py", line 103, in forward
    correct = self.metric.compute(probs, labels)
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddle/metric/metrics.py", line 261, in compute
    pred = paddle.argsort(pred, descending=True)
  File "/data2/anaconda3/envs/seq_cls2/lib/python3.8/site-packages/paddle/tensor/search.py", line 96, in argsort
    _, ids = _C_ops.argsort(x, axis, descending)
OSError: (External) CUDA error(98), invalid device function. 
  [Hint: Please search for the error code(98) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/kernels/gpu/argsort_kernel.cu:166)

 系统配置如下：centos7
(base) [root@localhost bin]# nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:24:38_PDT_2019
Cuda compilation tools, release 10.2, V10.2.89

(base) [root@localhost bin]# nvidia-smi
Fri Jan  5 14:37:22 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 440.33.01    Driver Version: 460.106.00   CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |

希望能够得到解答，谢谢

**Comment by qili93** [comment]
您好根据这个错误提示

```
OSError: (External) CUDA error(98), invalid device function.
[Hint: Please search for the error code(98) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/kernels/gpu/argsort_kernel.cu:166)
```

应该是您的Paddle安装包和您环境的CUDA版本不一致导致的。

请保证您这里安装的是 https://paddle-wheel.bj.bcebos.com/2.4.2/linux/linux-gpu-cuda11.2-cudnn8-mkl-gcc8.2-avx/paddlepaddle_gpu-2.4.2.post112-cp38-cp38-linux_x86_64.whl 这个安装包的版本。

建议可以使用 `pip list | grep paddle` 命令检查您这里安装的Paddle版本是否显示为 `2.4.2.post112`。

**Comment by zhang-jinqi** [comment]
在执行python3 -m pip install paddlepaddle-gpu==2.4.2.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html命令进行版本更新后，重新启用训练成功，但是提示：W0105 16:08:00.191686 105353 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 7.6, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.这个会影响使用吗？

还有就是训练开始后，观察gpu使用效率，padlle调用gpu一开始会是一个很低的占用率，只有2、3g，过了一段时间后才会达到20g左右的占用率，这个是为什么？

**Comment by qili93** [comment]
以下这个warnning是由于Paddle的这个安装包是基于cudnn8编译的，您的环境安装的是cudnn7，如果您的模型里面跑到cudnn算子的话可能会报不兼容的错误，但是如果您可以跑起来没有报错的话，可能是您的模型没有调用到cudnn实现的算子。

```
16:08:00.191686 105353 gpu_resources.cc:217] WARNING: device: . The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 7.6, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
```

如果想要消除以上的warning，可以考虑将您环境中的cudnn升级到8.2，或者使用飞桨提供的开发镜像

`paddlepaddle/paddle:2.4.2-gpu-cuda11.2-cudnn8.2-trt8.0`

另外关于GPU的使用率，GPU一开始会需要等待一段时间模型权重的加载，就是等待模型和数据从CPU到GPU的拷贝，等都加载完成之后才会满负载运行，因此GPU的占用率和显存会有一段爬升的时间是正常的。

**Comment by qili93** [comment]
Close as no more comments :)
