### ISSUE TITLE
运行paddle-speech的python api报错

### ISSUE THREAD

**Issue by 123newday** [PaddlePaddle/Paddle#60586]
### bug描述 Describe the Bug

python环境中运行 from paddlespeech.cli.asr.infer import ASRExecutor 报错（看着像是版本不适配）：
![1704434408](https://github.com/PaddlePaddle/Paddle/assets/25628347/b0a5f68d-3f85-41a2-84b6-afc2a641e66d)

参考文档：
https://github.com/PaddlePaddle/PaddleSpeech--Automatic Speech Recognition

环境依赖：
paddlehub                 2.4.0
paddlepaddle-gpu          2.4.2
paddlepaddle              2.5.1
python 3.8
paddlespeech              1.4.1 
paddlespeech-feat         0.1.0

**Comment by qili93** [comment]
您好这个是numpy的报错，原因见 https://stackoverflow.com/questions/76330655/attributeerror-module-numpy-has-no-attribute-complex

2个可能的修复建议
1. 降低您的numpy版本到可以支持 numpy.complex的版本，根据 https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations 需要安装1.20之前的numpy版本
3. 修改您的代码从 `np.complex` 改为 `complex`
