### ISSUE TITLE
[Custom Device] 让silu_fuse_pass变为Custom Device的可用Pass

### ISSUE THREAD

**Issue by engineer1109** [PaddlePaddle/Paddle#60596]
### 需求描述 Feature Description

**任务目标：** 
 让silu_fuse_pass变为Custom Device的可用Pass
  paddle/fluid/framework/ir/silu_fuse_pass.cc
代码中存在
 ```cpp
bool cutlass_enable = Get<bool>("use_cutlass");
```
这样的判定条件导致silu_fuse_pass变为cutlass(CUDA)专用Pass
然而, custom device没有cutlass的说法，所以即使在Paddle Inference中append这个pass，也不会有任何效果。

**解决方案**

https://github.com/PaddlePaddle/Paddle/pull/60595 
这个PR使得silu_fuse_pass变为Custom Device可用的Pass
可以融合为swish算子

**Comment by qili93** [comment]
Thanks for your contribution :)

**Comment by qili93** [comment]
Close as PR merged.
