### ISSUE TITLE
No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by Tortoise17** [PaddlePaddle/Paddle#60628]
### 请提出你的问题 Please ask your question

```
    from . import ops
  File "/installation/Soccernet-features-develop/paddlevideo/modeling/heads/ops.py", line 21, in <module>
    from paddle.fluid.framework import Variable, in_dygraph_mode
ModuleNotFoundError: No module named 'paddle.fluid'
LAUNCH INFO 2024-01-08 16:46:16,710 Exit code 1
(lab) [user@machine0 Mon 2024-01-08 16:46 /installation/Soccernet-features-develop]# 
```

Dear fellows:
I have tried several versions, and I am still facing same issue. Is there any solution to make it fix?  Your kind help is highly appreciated.

**Comment by engineer1109** [comment]
paddle.fluid is deleted, and use paddle.base now

**Comment by Tortoise17** [comment]
@engineer1109 Thank you so much. Great help. This helped, but still there is one point left. 

I have changed this as below

```
from paddle.base.framework import Variable, in_dygraph_mode
from paddle.base import core
from paddle.base.layer_helper import LayerHelper
from paddle.base.dygraph import layers
from paddle.base.data_feeder import check_variable_and_dtype, check_type, check_dtype, convert_dtype
```


below is the error.
```

from paddle.base.dygraph import layers
ImportError: cannot import name layers from paddle.base.dygraph
```

Please if you can also guide about it as I have changed this complete import from fluid to base.

**Comment by heavyrain-lzy** [comment]
> layers

Maybe you want to `from paddle.nn import Layer`

**Comment by Tortoise17** [comment]
@engineer1109 @heavyrain-lzy Thank you so much. Atleast this has resolved current error. I still have to fix other stuff and I may need your help until I can start the wheel. Millions of thank you.

**Comment by tear07251** [comment]
AttributeError: module 'paddle.base' has no attribute 'data'
