### ISSUE TITLE
编译适配登临卡（dlnne）的paddle inference，推理不使用登临GPU还是使用CPU推理。

### ISSUE THREAD

**Issue by LiquorPerfect** [PaddlePaddle/Paddle#60641]
### bug描述 Describe the Bug

**版本环境信息：**
paddle版本：2.5.1
系统版本：欧拉 openEuler2203
登临sdk：是由官方提供的，驱动安装成功且测试用例正常。
gcc版本：8.2.0

**问题反馈：**
两处代码编译报错，
①https://github.com/PaddlePaddle/Paddle/blob/b80ece97131961b56bdb034d1ae42f65a5810dda/paddle/fluid/operators/dlnne/dlnne_engine_op.h#L212 此处变量未用到，编译时警告即报错。下面还有212一样问题。
②https://github.com/PaddlePaddle/Paddle/blob/41ba14f30600373df53839dbf763405cfacb5c92/paddle/fluid/inference/analysis/ir_passes/dlnne_subgraph_pass.cc#L563 这边实参类型和形参类型对应不上。
③对上述两个问题自己修改后，按照这个教程（https://www.paddlepaddle.org.cn/support/news?action=detail&id=2516）编译出paddle inference适配登临卡的推理库，按照教程的demo验证python 加载模型推理，模型都没有运行在登临GPU上。使用C++推理再次验证，还是模型还是没有运行在GPU上，运行在CPU上。

**Comment by LiquorPerfect** [comment]
问题①我发现在后续的版本中完善了。

**Comment by LiquorPerfect** [comment]
@heavyrain-lzy 麻烦验证一下，谢谢。

**Comment by keeeers** [comment]
@LiquorPerfect 您好，很抱歉打扰你，我也正开始使用登临板卡。我希望使用登临板卡进行大模型的推理工作，但目前仅有登临SDK的资料。想要询问您是如何使用登临板卡的？是否有更多登临板卡方面的资料？期待您的回复！感谢！
