### ISSUE TITLE
paddle.unfold 和 Tensor.unfold API 不支持对一个数据连续使用

### ISSUE THREAD

**Issue by Ainavo** [PaddlePaddle/Paddle#60672]
### bug描述 Describe the Bug

```
shape1 = paddle.randn((2, 8, 32, 34, 3)).unfold(3, 3, 1).shape
print(shape1)
shape2 = paddle.randn((2, 8, 32, 34, 3, 3)).unfold(3, 3, 1).shape
print(shape2)
shape3 = paddle.randn((2, 8, 32, 34, 3)).unfold(3, 3, 1).unfold(3, 3, 1).shape
```

报错如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/57820731/2306d6b8-7187-4448-8810-653128246cef)
![image](https://github.com/PaddlePaddle/Paddle/assets/57820731/68c8ead7-1776-4be7-b3f2-a44c8690fa98)

对比了一下pytorch中的`Tensor.unfold`，并没有不能连续处理的问题，如下图：
![image](https://github.com/PaddlePaddle/Paddle/assets/57820731/104dd496-160c-4cde-a29f-3de719bbedb9)

**Comment by heavyrain-lzy** [comment]
@wanghuancoder 麻烦欢哥给解答一下

**Comment by wanghuancoder** [comment]
感谢您的问题反馈，这是unfold在支持Stride上的一个bug。我刚刚提了修复PR：
https://github.com/PaddlePaddle/Paddle/pull/60684
