### ISSUE TITLE
LSTM op doc not displayed correctly on paddle.org 

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#6067]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/lstm_op.cc#L201-L222

I think all the `/f` can be removed from this code.

Currently `/f` leading to incorrect display on:
http://www.paddlepaddle.org/docs/develop/documentation/en/operators.html#permalink-12-lstm

**Comment by qingqing01** [comment]
@kexinzhao Thanks!  I'll fix it. :)
