### ISSUE TITLE
gru op doc does not display correctly on paddle.org

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#6068]
https://github.com/PaddlePaddle/Paddle/blob/35572355c2261c493aa782ba1255971f4dfa385e/paddle/operators/gru_op.cc#L135-L140

I think the `\f[` and `\f]` should be replaced by `$$`, respectively.

Currently, equation is not correctly shown here:
http://www.paddlepaddle.org/docs/develop/documentation/en/operators.html#permalink-15-gru

**Comment by guoshengCS** [comment]
Thanks. I will fix it.
