### ISSUE TITLE
adam, adamax and adadelta op doc does not display correctly on paddle.org

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#6069]
https://github.com/PaddlePaddle/Paddle/blob/35572355c2261c493aa782ba1255971f4dfa385e/paddle/operators/adam_op.cc#L115-L119

https://github.com/PaddlePaddle/Paddle/blob/35572355c2261c493aa782ba1255971f4dfa385e/paddle/operators/adadelta_op.cc#L95-L100

https://github.com/PaddlePaddle/Paddle/blob/35572355c2261c493aa782ba1255971f4dfa385e/paddle/operators/adamax_op.cc#L110-L113

These three has similar issue as in adagrad.

http://www.paddlepaddle.org/docs/develop/documentation/en/operators.html#permalink-76-adam

**Comment by kavyasrinet** [comment]
Yeah sure, I can fix these in the PR I already created.
