### ISSUE TITLE
get_data.py in srl demo does not work

### ISSUE THREAD

**Issue by enfry** [PaddlePaddle/Paddle#607]
Hi,
I tried to run the srl demo but I could not download the embeddings using https://github.com/PaddlePaddle/Paddle/blob/develop/demo/semantic_role_labeling/data/get_data.sh.
I got error 404 from googledrive. 
I saw this is a known issue and I also checked on pan at the address https://pan.baidu.com/s/1o8q577s, but it seems that the files I need to run the demo are not there.
Is there a way to get them?

Thanks

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/release/v0.9.0/demo/semantic_role_labeling/data/get_data.sh，我们会马上同步到develop分支的

**Comment by backyes** [comment]
@enfry 

问题已经有解决方案，这里close

**Comment by enfry** [comment]
Hi,
thanks for addressing the issue so quickly, but I still don't know how to obtain those files.

**Comment by luotao1** [comment]
@enfry 代码已经更新了，重新运行get_data.sh即可。
