### ISSUE TITLE
Rank loss op doc displayed incorrectly on paddle.org

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#6070]
https://github.com/PaddlePaddle/Paddle/blob/35572355c2261c493aa782ba1255971f4dfa385e/paddle/operators/rank_loss_op.cc#L71-L75

`\f` should be removed.

Correctly, it is incorrectly displayed here:
http://www.paddlepaddle.org/docs/develop/documentation/en/operators.html#permalink-82-rank_loss

**Comment by kuke** [comment]
Thanks. I will fix it
