### ISSUE TITLE
Documentation for RNN

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#6072]
No documentation about hierarchical RNN in 0.9.0.
No documentation about RNN at all in 0.10.0
No documentation about hierarchical RNN in develop

**Comment by luotao1** [comment]
> No documentation about hierarchical RNN in 0.9.0

http://www.paddlepaddle.org/docs/0.9.0/documentation/zh/algorithm/rnn/hierarchical-rnn.html

> No documentation about RNN at all in 0.10.0

http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/howto/deep_model/rnn/index_cn.html

> No documentation about hierarchical RNN in develop

http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/deep_model/rnn/hrnn_rnn_api_compare_cn.html

**Comment by emailweixu** [comment]
I see. I couldn't find the English document.

**Comment by luotao1** [comment]
related #1943

**Comment by luotao1** [comment]
close due to the new issues #9013 #9014 #9015
