### ISSUE TITLE
离线推理，如何设置多卡运行？

### ISSUE THREAD

**Issue by bxbac** [PaddlePaddle/Paddle#60745]
### 请提出你的问题 Please ask your question

希望加载一个离线模型后，对目标样本进行预测并提取特征，希望采用多卡提速。
运行机器目前有8卡，采用如下方式都不能生效：
（1）shell脚本中，export  CUDA_VISIBLE_DEVICES="0,1,2,3"
（2）paddle.set_device("gpu:5")
（3）paddle.device.cuda.device_count() 返回的数为1
请帮助给出代码配置解决的方案.

**Comment by hitywt** [comment]
> ### 请提出你的问题 Please ask your question
> 希望加载一个离线模型后，对目标样本进行预测并提取特征，希望采用多卡提速。 运行机器目前有8卡，采用如下方式都不能生效： （1）shell脚本中，export CUDA_VISIBLE_DEVICES="0,1,2,3" （2）paddle.set_device("gpu:5") （3）paddle.device.cuda.device_count() 返回的数为1 请帮助给出代码配置解决的方案.

您好，请提供下您当前操作的完整的启动命令和配置内容

**Comment by bxbac** [comment]
启动命令：shell脚本
export  CUDA_VISIBLE_DEVICES="0,1,2,3"

启动命令为 python predictor_emb.py \
    --model_name_or_path ./checkpoints/baichuan2_13b_rewoo_v3_sft_ckpts/ \
    --batch_size 1 \
    --data_file ./data/online_log/log_multi_round.json \
    --dtype "float16" \
    --mode "dynamic" \
    --output_file ./data/online_query_emb/date_emb

设置内容
paddle.set_device(predictor_args.device)

**Comment by bxbac** [comment]
模型初始化内容：model = AutoModelForCausalLM.from_pretrained(
                    predictor_args.model_name_or_path,
                    #config=config,

                    dtype=predictor_args.dtype,
                    low_cpu_mem_usage=True,
                    tensor_parallel_degree=tensor_parallel_degree,
                    tensor_parallel_rank=tensor_parallel_rank,
                )

**Comment by wwbitejotunn** [comment]
可以尝试使用

**Comment by wwbitejotunn** [comment]
可以尝试一下使用这样的方法呢:
```
python -m paddle.distributed.launch \
    --gpus "0,1,2,3" \
    predictor_emb.py
    --model_name_or_path ./checkpoints/baichuan2_13b_rewoo_v3_sft_ckpts/
    --batch_size 1
    --data_file ./data/online_log/log_multi_round.json
    --dtype "float16"
    --mode "dynamic"
    --output_file ./data/online_query_emb/date_emb
```
