### ISSUE TITLE
请问在paddlepaddle上如何进行迁移学习，我这有训练的参数，想作为另一个模型的初始参数！

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#6075]
请问在paddlepaddle上如何进行迁移学习，我这有训练的参数，想作为另一个模型的初始参数！
```python
parameters = paddle.parameters.create(cost)
    with gzip.open('params_pass_0.tar.gz', 'r') as f:
        parameters = paddle.parameters.Parameters.init_from_tar(f)
```
是不是这样就可以了？有人这人测试过吗？

**Comment by sweetsky0901** [comment]
models 下面的globally normalize reader 有例子~在train.py 里面

**Comment by sweetsky0901** [comment]
https://github.com/PaddlePaddle/models/blob/develop/globally_normalized_reader/train.py

您的写法，看起来是对的，也可以再对照一下这个例子
