### ISSUE TITLE
build error on develop branch

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#6077]
<img width="813" alt="machi 2017-11-30 10-22-52" src="https://user-images.githubusercontent.com/1027183/33409964-9eb87f5e-d543-11e7-99d0-830bf9adbf43.png">
sorry I lost text error message

**Comment by sweetsky0901** [comment]
请问您编译的环境和之前具体已经执行的步骤方便发一下吗？

**Comment by zhglzh** [comment]
我是为了编译capi，把WITH_PYTHON关掉后，就没有上面的异常了

**Comment by Xreki** [comment]
和https://github.com/PaddlePaddle/Paddle/issues/4302 重复了。
