### ISSUE TITLE
在A40上使用paddle-gpu计算速度非常慢

### ISSUE THREAD

**Issue by tink2123** [PaddlePaddle/Paddle#60778]
### 请提出你的问题 Please ask your question

paddle版本：2.5.2
显卡： A40
测试脚本：

```
import paddle
import time
import numpy as np
device = 'gpu'
paddle.set_device(device)  # 设置使用GPU
start_time = time.time()
# 创建Tensor并进行一些操作
x_np = np.ones([1000, 1000])
x = paddle.to_tensor(x_np)
y_np = np.zeros_like(x_np)
y = paddle.to_tensor(y_np)
for i in range(10000):
 # 执行计算
 z = paddle.add(x, y)
end_time = time.time()
execution_time = end_time - start_time
print(f"running in :{device}, Computing time: {execution_time} seconds")
```

gpu运算时间大概在27s， 同样的代码在V100上只需要2s

**Comment by pkuzyc** [comment]
可以看下 tensor 的类型，numpy 生成的array默认的是 float64 类型，直接 to_tensor 之后也是 float64 类型。V100 的双精度算力相比 A40 强很多。

**Comment by tink2123** [comment]
请问会有这么大的差异吗? 发现这个问题是因为在模型预测时速度也非常慢，那需要把网络中所有的双精度都转成单精度吗？

**Comment by pkuzyc** [comment]
可以在这个测试代码里试一下，用 numpy 生成 float32 的 array：`x_np=np.ones([1000,1000],dtype='float32')` 或者 `x_np=np.ones([1000,1000]).astype('float32')`。看看用 float32 之后 a40 上的速度。
