### ISSUE TITLE
[Cleanup] `random_seed` -> `paddle.seed` 问题汇总

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#60787]
## 背景

动转静小组在理想态单测推全验证中，`test_lstm.py`单测发现：调用`default_main_program().random_seed`方法会导致 PIR 模式下的 random_seed 未能被设置到。这会导致在 PIR 模式 seed 设置无效，详见：[#60343](https://github.com/PaddlePaddle/Paddle/pull/60343)。

具体例子
```python
with enable_to_static_guard(to_static):
    paddle.static.default_main_program().random_seed = 1001
    paddle.static.default_startup_program().random_seed = 1001

    net = paddle.jit.to_static(Net(12, 2))
    x = paddle.zeros((2, 10, 12))
    y = net(x)
    return y.numpy()
```

修改后：
```python
with enable_to_static_guard(to_static):
	paddle.seed(1001)

    net = paddle.jit.to_static(Net(12, 2))
    x = paddle.zeros((2, 10, 12))
    y = net(x)
    return y.numpy()
```

补充说明:

`paddle.static.default_main_program().random_seed`为动静统一方法，动态图和老静态图都会读取`random_seed`参数，而 PIR 不会，且`program.random_seed`三年前就计划废弃，使用`paddle.seed`代替

## 任务列表

✅：已经完全迁移，所有单测都OK！
🟢：审核完毕待合入，合入之后完全迁移！
🔵：可认领！
🟡：当前阶段不需要人力继续跟进，下阶段推进（大部分是精度问题）
🚧：迁移中，单测还没有过，还没有审核完。

大致正常流程为:
🔵 -> 🚧 -> 🟢 -> ✅

异常流程为:
🔵 -> 🚧 -> 🟡

<summary>

### 第一阶段:（整体进展：0/18）
> test 目录下文件清理

</summary>

|  序号  |  文件位置  |  认领人  |  PR  |
| :---: | :---: | :---: | :---: |
| 🔵1 | dist_allreduce_op.py</br>dist_ctr.py</br>dist_fleet_ctr.py</br>dist_fleet_ctr_ps_gpu.py</br>dist_fleet_heter_pipeline_ctr.py</br> |  |  |
| 🔵2 | dist_fleet_raw_program_optimizer.py</br>dist_fleet_simnet_bow.py</br>dist_fleet_sync_batch_norm.py</br>dist_mnist.py</br>dist_mnist_dgc.py</br> |  |  |
| 🔵3 | dist_mnist_fp16_allreduce.py</br>dist_mnist_lars.py</br>dist_se_resnext.py</br>dist_sharding_save.py</br>dist_word2vec.py</br> |  |  |
| 🔵4 | fused_attention_pass_with_mp.py</br>ir_memory_optimize_net_base.py</br>op_test_ipu.py</br>test_cond.py</br>test_custom_leaky_relu_ipu.py</br> |  |  |
| 🔵5 | test_desc_clone.py</br>test_detection.py</br>test_dist_base.py</br>test_dist_data_parallel_ipu.py</br>test_dist_pod128_sample.py</br> |  |  |
| 🔵6 | test_dist_sample.py</br>test_dist_transpiler.py</br>test_dropout_nd_op.py</br>test_eager_deletion_dynamic_rnn_base.py</br>test_eager_deletion_padding_rnn.py</br> |  |  |
| 🔵7 | test_eval_model_ipu.py</br>test_fused_attention_op.py</br>test_fused_attention_op_xpu.py</br>test_fused_attention_pass.py</br>test_fused_bias_dropout_residual_layer_norm_op.py</br> |  |  |
| 🔵8 | test_fused_ec_moe_op.py</br>test_fused_feedforward_op.py</br>test_fused_feedforward_op_xpu.py</br>test_fused_feedforward_pass.py</br>test_fused_multi_transformer_int8_op.py</br> |  |  |
| 🔵9 | test_fused_multi_transformer_op.py</br>test_fused_resnet_basic_block_op_xpu.py</br>test_fused_transformer_encoder_layer.py</br>test_identity_loss_ipu.py</br>test_imperative_deepcf.py</br> |  |  |
| 🔵10 | test_imperative_hook_for_layer.py</br>test_imperative_mnist.py</br>test_imperative_mnist_sorted_gradient.py</br>test_imperative_out_scale.py</br>test_imperative_ptq.py</br> |  |  |
| 🔵11 | test_imperative_qat.py</br>test_imperative_qat_amp.py</br>test_imperative_qat_lsq.py</br>test_imperative_qat_matmul.py</br>test_imperative_qat_user_defined.py</br> |  |  |
| 🔵12 | test_imperative_recurrent_usage.py</br>test_inference_model_io_ipu.py</br>test_initializer.py</br>test_initializer_nn.py</br>test_lambv2_op.py</br> |  |  |
| 🔵13 | test_layers.py</br>test_llm_int8_linear.py</br>test_metrics.py</br>test_model_parallel_ipu.py</br>test_modelruntime_ipu.py</br> |  |  |
| 🔵14 | test_multiprocess_dataloader_dataset.py</br>test_multiprocess_dataloader_dynamic.py</br>test_multiprocess_dataloader_iterable_dataset_dynamic.py</br>test_multiprocess_dataloader_iterable_dataset_static.py</br>test_multiprocess_dataloader_static.py</br> |  |  |
| 🔵15 | test_optimizer_in_control_flow.py</br>test_optimizer_ipu.py</br>test_program.py</br>test_quantization_mkldnn_pass.py</br>test_quantization_pass.py</br> |  |  |
| 🔵16 | test_quantization_scale_pass.py</br>test_rnn_decode_api.py</br>test_save_inference_model.py</br>test_seq2seq.py</br>test_static_save_load.py</br> |  |  |
| 🔵17 | test_static_save_load_bf16.py</br>test_sync_batch_norm_op.py</br>test_trt_conv_quant_dequant_pass.py</br>test_trt_fc_fuse_quant_dequant_pass.py</br>test_trt_matmul_quant_dequant.py</br> |  |  |
| 🔵18 | test_user_defined_quantization.py</br>test_weight_decay.py</br>test_weight_only_linear.py</br>test_word2vec.py</br>test_yolov3.py</br> |  |  |

## 认领方式
请大家以 comment 的形式认领任务，如：
```
【报名】：1、3、12-13
```
多个任务之间需要使用顿号分隔，报名多个连续任务可用横线表示，如 2-5
PR 提交格式：在 PR 的标题中以 **【Cleanup random_seed No.】** 开头，注明任务编号

## 看板信息

| 任务数量 | 🔵可认领 | 🚧迁移中 | 🟢待合入 | ✅完成 | 🟡下阶段推进 | 完成率  |
| ---- | ---- | ---- | ---- | --- | ------ | ---- |
| 18  | 18  | 0    | 0    | 0   | 0      | 0.0% |

## 问题记录

- [ ] `test/collective/fleet/fused_attention_pass_with_mp.py` - 精度不足
- [ ] `test/collective/fleet/test_fused_attention_op_xpu.py` - 精度不足

**Comment by SigureMo** [comment]
这个 issue 同时追踪所有 PR 吧，别只追踪问题

另外 issue 写一下具体进展，比如一共多少处，还剩余多少处没清理

**Comment by gouzil** [comment]
【报名】：1、3、12-13

**Comment by gouzil** [comment]
【报名】：1、3、12-13

**Comment by gouzil** [comment]
任务合并至 https://github.com/PaddlePaddle/Paddle/issues/61385
