### ISSUE TITLE
【编译优化】paddle_test 推全

### ISSUE THREAD

**Issue by Galaxy1458** [PaddlePaddle/Paddle#60793]
## 一、需求背景
飞桨正在做编译优化工作，此需求为 [[cmake治理]删除paddle_test多余无用依赖 ](https://github.com/PaddlePaddle/Paddle/issues/60013) 的升级版需求，背景原理类似，目前paddle编译c++单测有多种方式，如cc_test（windows下link静态库，linux下link paddle.so），paddle_test(windows和linux下都link动态库paddle.so)，现在推荐使用paddle_test，好处在于：
1.  link动态库无需手动加过多的依赖，大部分符号在paddle.so中已存在；
2.  link libpaddle.so可以大幅度减小C++单测的体积 ，从而减少build目录体积大小

## 二、存在的问题
paddle仓库中有43个使用cc_test的CMakeLists.txt文件，其对paddle的单测编译造成一定压力，现打算将其全部替换为paddle_test.

### 可能遇到的编译问题：
请参考：https://github.com/PaddlePaddle/community/blob/master/pfcc/call-for-contributions/code_style/change_cc_test_to_paddle_test.md

## 四、任务划分
| 序号 | 文件名 | 认领人/状态/PR号 |
| :-: | :-: | :-: |
| 1 | test/cpp/pir/pattern_rewrite/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60830](https://github.com/PaddlePaddle/Paddle/pull/60830)<br> | 
| 2 | test/cpp/pir/pass/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60831](https://github.com/PaddlePaddle/Paddle/pull/60831)<br> | 
| 3 | test/cpp/pir/kernel_dialect/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60832](https://github.com/PaddlePaddle/Paddle/pull/60832)<br> | 
| 4 | test/cpp/pir/core/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60833](https://github.com/PaddlePaddle/Paddle/pull/60833)<br> | 
| 5 | test/cpp/pir/control_flow_dialect/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60834](https://github.com/PaddlePaddle/Paddle/pull/60834)<br> | 
| 6 | test/cpp/phi/ops/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#60919](https://github.com/PaddlePaddle/Paddle/pull/60919)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61985](https://github.com/PaddlePaddle/Paddle/pull/61985)<br> | 
| 7 | test/cpp/phi/kernels/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#60917](https://github.com/PaddlePaddle/Paddle/pull/60917)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61984](https://github.com/PaddlePaddle/Paddle/pull/61984)<br> | 
| 8 | test/cpp/phi/core/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#60918](https://github.com/PaddlePaddle/Paddle/pull/60918)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61980](https://github.com/PaddlePaddle/Paddle/pull/61980)<br> | 
| 9 | test/cpp/phi/common/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#60916](https://github.com/PaddlePaddle/Paddle/pull/60916)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61981](https://github.com/PaddlePaddle/Paddle/pull/61981)<br> | 
| 10 | test/cpp/phi/api/CMakeLists.txt | @DrRyanHuang <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#60915](https://github.com/PaddlePaddle/Paddle/pull/60915)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61983](https://github.com/PaddlePaddle/Paddle/pull/61983)<br> | 
| 11 | test/cpp/new_executor/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61013](https://github.com/PaddlePaddle/Paddle/pull/61013)<br> | 
| 12 | test/cpp/jit/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61014](https://github.com/PaddlePaddle/Paddle/pull/61014)<br> | 
| 13 | test/cpp/inference/api/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61016](https://github.com/PaddlePaddle/Paddle/pull/61016)<br> | 
| 14 | test/cpp/imperative/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61017](https://github.com/PaddlePaddle/Paddle/pull/61017)<br> | 
| 15 | test/cpp/fluid/reader/CMakeLists.txt | @zade23 <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61018](https://github.com/PaddlePaddle/Paddle/pull/61018)<br> | 
| 16 | test/cpp/fluid/mkldnn/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61672](https://github.com/PaddlePaddle/Paddle/pull/61672)<br> | 
| 17 | test/cpp/fluid/memory/CMakeLists.txt | @gouzil <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61105](https://github.com/PaddlePaddle/Paddle/pull/61105)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#62031](https://github.com/PaddlePaddle/Paddle/pull/62031)<br> | 
| 18 | test/cpp/fluid/math/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61673](https://github.com/PaddlePaddle/Paddle/pull/61673)<br> | 
| 19 | test/cpp/fluid/fused/CMakeLists.txt | @ccsuzzh <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61238](https://github.com/PaddlePaddle/Paddle/pull/61238)<br> | 
| 20 | test/cpp/fluid/framework/details/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61463](https://github.com/PaddlePaddle/Paddle/pull/61463)<br> | 
| 21 | test/cpp/fluid/framework/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61674](https://github.com/PaddlePaddle/Paddle/pull/61674) [#62534](https://github.com/PaddlePaddle/Paddle/pull/62534)<br> | 
| 22 | test/cpp/fluid/elementwise/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61376](https://github.com/PaddlePaddle/Paddle/pull/61376)<br> | 
| 23 | test/cpp/fluid/dlnne/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61372](https://github.com/PaddlePaddle/Paddle/pull/61372)<br> | 
| 24 | test/cpp/fluid/detection/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61373](https://github.com/PaddlePaddle/Paddle/pull/61373)<br> | 
| 25 | test/cpp/fluid/controlflow/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61374](https://github.com/PaddlePaddle/Paddle/pull/61374)<br> | 
| 26 | test/cpp/fluid/benchmark/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61375](https://github.com/PaddlePaddle/Paddle/pull/61375)<br> | 
| 27 | test/cpp/fluid/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61675](https://github.com/PaddlePaddle/Paddle/pull/61675)<br> | 
| 28 | test/cpp/eager/task_tests/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61676](https://github.com/PaddlePaddle/Paddle/pull/61676)<br> | 
| 29 | test/cpp/eager/data_structure_tests/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61677](https://github.com/PaddlePaddle/Paddle/pull/61677)<br> | 
| 30 | test/cpp/auto_parallel/CMakeLists.txt | @Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61462](https://github.com/PaddlePaddle/Paddle/pull/61462)<br> | 
| 31 | paddle/utils/string/CMakeLists.txt | @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60958](https://github.com/PaddlePaddle/Paddle/pull/60958) [#60959](https://github.com/PaddlePaddle/Paddle/pull/60959)<br> | 
| 32 | paddle/utils/CMakeLists.txt | @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60959](https://github.com/PaddlePaddle/Paddle/pull/60959)<br> | 
| 33 | paddle/phi/core/distributed/store/CMakeLists.txt | @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60960](https://github.com/PaddlePaddle/Paddle/pull/60960)<br> | 
| 34 | paddle/phi/backends/CMakeLists.txt | @xiaoyewww <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#60961](https://github.com/PaddlePaddle/Paddle/pull/60961)<br> | 
| 35 | paddle/fluid/platform/profiler/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61093](https://github.com/PaddlePaddle/Paddle/pull/61093)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#62034](https://github.com/PaddlePaddle/Paddle/pull/62034) [#62033](https://github.com/PaddlePaddle/Paddle/pull/62033)<br> | 
| 36 | paddle/fluid/platform/device/custom/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61094](https://github.com/PaddlePaddle/Paddle/pull/61094)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#62036](https://github.com/PaddlePaddle/Paddle/pull/62036) [#62033](https://github.com/PaddlePaddle/Paddle/pull/62033)<br> | 
| 37 | paddle/fluid/platform/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61095](https://github.com/PaddlePaddle/Paddle/pull/61095)<br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#62035](https://github.com/PaddlePaddle/Paddle/pull/62035) [#62033](https://github.com/PaddlePaddle/Paddle/pull/62033)<br> | 
| 38 | paddle/fluid/inference/api/details/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61943](https://github.com/PaddlePaddle/Paddle/pull/61943)<br> | 
| 39 | paddle/fluid/inference/analysis/ir_passes/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61944](https://github.com/PaddlePaddle/Paddle/pull/61944)<br> | 
| 40 | paddle/fluid/framework/ir/memory_optimize_pass/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-完成任务-9B59B6" /> [#61945](https://github.com/PaddlePaddle/Paddle/pull/61945)<br> | 
| 41 | paddle/fluid/framework/ir/fusion_group/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61946](https://github.com/PaddlePaddle/Paddle/pull/61946)<br> | 
| 42 | paddle/fluid/framework/ir/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61947](https://github.com/PaddlePaddle/Paddle/pull/61947)<br> | 
| 43 | paddle/fluid/distributed/test/CMakeLists.txt | @ooooo-create <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Liyulingyue <img src="https://img.shields.io/badge/状态-提交PR-F39C12" /> [#61948](https://github.com/PaddlePaddle/Paddle/pull/61948)<br> | 

### 认领方式
请大家以 comment 的形式认领任务，如：
```
【报名】：1、3、12-13
```
多个任务之间需要使用**中文顿号**分隔，报名多个连续任务可用横线表示，如 2-5
PR 提交格式：在 PR 的标题中以 **【paddle_test No.】** 开头，注明任务编号

## 看板信息
| 任务方向 | 任务数量 | 提交作品 / 任务认领 | 提交率 | 完成 | 完成率 |
| :----: | :----: | :----:  | :----: | :----: | :----: |
| 快乐开源 | 43 | 43 / 43 | 100.0% | 25 | 58.14% |
#####

## 统计信息 
> 排名不分先后 @Liyulingyue (20) @ccsuzzh (1) @xiaoyewww (4)

**Comment by ooooo-create** [comment]
【报名】：35-43

**Comment by DrRyanHuang** [comment]
【报名】：6-10

**Comment by xiaoyewww** [comment]
【报名】：31-34

**Comment by zade23** [comment]
【报名】：11-15

**Comment by ccsuzzh** [comment]
【报名】：19

**Comment by luotao1** [comment]
[【编译优化】paddle_test 推全](https://github.com/PaddlePaddle/Paddle/issues/60793#top) 暂时结项，等后续 cmake 分目录治理工作结束后，再重新启动，感谢参与的小伙伴们！

> 排名不分先后 @Liyulingyue (20) @ccsuzzh (1) @xiaoyewww (4)
