### ISSUE TITLE
Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)

### ISSUE THREAD

**Issue by sidneyzhu** [PaddlePaddle/Paddle#608]
after i successfully build all the dependencies of paddle on redhat es4, i mkdir build && cd build && cmake .. -DWITH_GPU=OFF -DWITH_DOC=ON -DWITH_SWIG_PY=ON
then i ends with following errors:
CMake Error at /home/wq/bins/cmake-3.7.0-Linux-x86_64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:138 (message):
  Could NOT find Protobuf (missing: Protobuf_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/wq/bins/cmake-3.7.0-Linux-x86_64/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /home/wq/bins/cmake-3.7.0-Linux-x86_64/share/cmake-3.7/Modules/FindProtobuf.cmake:393 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:14 (find_package)

thanks in advance!

**Comment by backyes** [comment]
@sidneyzhu 
Maybe the Protobuf tools is missing.  Check following command's output
```shell
which protoc
```

more PaddlePaddle installation options: http://www.paddlepaddle.org/doc_cn/build_and_install/index.html

For compiling issues, I think, these background should be provided, such as OS version, paddle version and the doc links that you follow.

**Comment by sidneyzhu** [comment]
@backyes thank you ! resolved by rebuild protobuf

**Comment by DaemonZhao** [comment]
> @backyes thank you ! resolved by rebuild protobuf

So...how to rebuild this.
