### ISSUE TITLE
新手请教些问题

### ISSUE THREAD

**Issue by balabalalilili** [PaddlePaddle/Paddle#609]
![2016-11-24 21-53-20](https://cloud.githubusercontent.com/assets/23418049/20601730/08f7cb72-b295-11e6-9e2f-a23b88da389a.png)
![2016-11-24 21-57-09](https://cloud.githubusercontent.com/assets/23418049/20601731/08f9235a-b295-11e6-9607-5ceef5f9ed79.png)
 model training 之后的步骤怎么进行  刚接触python和paddle

**Comment by qingqing01** [comment]
`vgg_16_cifar.py` 不应该用python执行，执行[train.sh](https://github.com/PaddlePaddle/Paddle/blob/develop/demo/image_classification/train.sh)就可以了，回头提升下文档。

```
sh train.sh
```

**Comment by gangliao** [comment]
@qingqing01  我们可以先把 训练的train.sh写在前面，之后才是详细解释内部原理。不然用户很容易迷糊。
download data -> preprocess data -> training [train.sh] -> prediction  [predict.sh] -> how it works...
