### ISSUE TITLE
2.6.0版本，ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by yangy996** [PaddlePaddle/Paddle#60906]
### bug描述 Describe the Bug

cuda版本： 12.2

在 paddlepaddle-gpu==2.3.2的时候，可以正常运行，也没有报错libcudart.so.11.0缺失的问题

在 paddlepaddle-gpu==2.5.2、2.6.0的时候，就会报错ImportError: libcudart.so.11.0: cannot open shared object file: No such file or directory

但是现在装2.6.0的12.0版本，又需要gcc12.2，我的系统Ubuntu20.04都报错：ImportError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.30' not found 

从2.3.2之后，官方编译的依赖包各种出问题，这个不能跟2.3.2一样向下兼容么？

**Comment by yangy996** [comment]
目前最稳定的版本是2.3.2，整的项目上我都不敢随便升级paddle版本了

**Comment by zhanghengjiayou** [comment]
cudnn的问题应该是，这个很恶心，你升级一下cudnn试试

**Comment by yangy996** [comment]
> cudnn的问题应该是，这个很恶心，你升级一下cudnn试试

是这个问题，paddle新版不能向下兼容
