### ISSUE TITLE
编译最后print_operators_doc出错

### ISSUE THREAD

**Issue by huayong** [PaddlePaddle/Paddle#6092]
[ 98%] Built target paddle_pybind
Scanning dependencies of target print_operators_doc
[ 98%] Building CXX object paddle/pybind/CMakeFiles/print_operators_doc.dir/print_operators_doc.cc.o
Linking CXX executable print_operators_doc
../operators/libpool_op.a(pool_op.cu.cc.o): In function `Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>& Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>::operator=<Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer> const> >(Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer> const> const&)':
/home/vis/xuhuayong/dl/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorDevice.h:35: undefined reference to `Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer> const> const> const, Eigen::GpuDevice, false>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, Eigen::TensorMap<Eigen::Tensor<double, 1, 1, long>, 0, Eigen::MakePointer> const> const> const&, Eigen::GpuDevice const&)'
../operators/libpool_op.a(pool_op.cu.cc.o): In function `Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>& Eigen::TensorDevice<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::GpuDevice>::operator=<Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer> const> >(Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer> const> const&)':
/home/vis/xuhuayong/dl/Paddle/build/third_party/eigen3/src/extern_eigen3/unsupported/Eigen/CXX11/src/Tensor/TensorDevice.h:35: undefined reference to `Eigen::internal::TensorExecutor<Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer> const> const> const, Eigen::GpuDevice, false>::run(Eigen::TensorAssignOp<Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer>, Eigen::TensorCwiseNullaryOp<Eigen::internal::scalar_constant_op<float>, Eigen::TensorMap<Eigen::Tensor<float, 1, 1, long>, 0, Eigen::MakePointer> const> const> const&, Eigen::GpuDevice const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/pybind/print_operators_doc] Error 1
make[1]: *** [paddle/pybind/CMakeFiles/print_operators_doc.dir/all] Error 2
make: *** [all] Error 2

目前主机是centos6.3，不能用docker
gcc5.3
CUDA8.0
CUDNN5.0.5(看官网上说要大于5.1，但是不知道是不是这个影响)
其他的third_party都是安装官方提供的版本

**Comment by sweetsky0901** [comment]
建议先更新一下cudnn的版本

**Comment by huayong** [comment]
更新到cudnn6.0后还是出现同样的问题

**Comment by huayong** [comment]
感觉这个功能不是必须的，能不能把它屏蔽掉，关键最后还会影响install过程

**Comment by luotao1** [comment]
如果是源码编译，可以把https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pybind/CMakeLists.txt#L8 先注释了。我来加个`WITH_DOC`的开关。

**Comment by huayong** [comment]
好的，非常感谢，目前编译已经成功
