### ISSUE TITLE
使用dotmul_projection提示assert param_attr is None错误

### ISSUE THREAD

**Issue by SniperZhao** [PaddlePaddle/Paddle#610]
网络设置：
![image](https://cloud.githubusercontent.com/assets/11026164/20612483/65afbb26-b2f5-11e6-88aa-c4c04b5d7c7d.png)

报错信息：
![image](https://cloud.githubusercontent.com/assets/11026164/20612496/88f9b85c-b2f5-11e6-83cf-d7e01251cafc.png)

param_attr已经被设置为None了 为什么还会报这样的错误呢？

**Comment by backyes** [comment]
@qingqing01 
此bug已经fix ，请给出相关PR或者issues

**Comment by SniperZhao** [comment]
感谢paddle人员的悉心帮助，此问题的解决方案是dotmul_projection不能独立为一个layer，，必须在mixed_layer中使用，具体的写法为：
h2_2 = mixed_layer(size = 16, input = [dotmul_projection(input = h1_1), dotmul_projection(input = h1_4)])
h2_3 = mixed_layer(size = 16, input = [dotmul_projection(input = h1_2), dotmul_projection(input = h1_3)])
