### ISSUE TITLE
【HACKATHON 6th Code Camp】黑客松护航计划集训营

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/Paddle#61006]
大家好，非常高兴地告诉大家，第六期 PaddlePaddle Hackathon 即将开始。本次活动是面向全球开发者的深度学习领域编程活动，鼓励开发者了解与参与飞桨深度学习开源项目。本次飞桨黑客马拉松由深度学习技术及应用国家工程研究中心主办，百度飞桨承办，活动包含两大赛道：开源贡献个人挑战赛、飞桨护航计划集训营、Fundable Projects、优秀稿件征集与传播，等你来挑战！活动详细信息可参考 [PaddlePaddle Hackathon 说明](https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/10_contribution/hackathon_cn.md)。

此 issue 发布 **飞桨护航计划集训营（第一批）** 的任务，开发者提交简历&通过面试后，以远程的方式深度参与飞桨开源项目开发课题，成果以 PR（Pull Requests）的形式贡献到指定代码仓库，实训期 3 个月（每周开发时间至少 25h），奖金 3-5 🌟。

如果是第一次接触黑客松护航计划，可以通过以下材料了解活动详情和流程

- [第六期黑客松护航计划集训营活动说明](https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/10_contribution/hackathon_cn.md#2-飞桨护航计划集训营)
- [护航计划集训营公开资料](https://github.com/PFCCLab/Camp)

## 通过考核的营员名单公示
护航计划集训营已于 6 月 3 日 ～ 7 日、19日 举行结营答辩，以下为参与答辩并通过考核的学员名单。其中，`特别奖励`为奖励在集训期间展现出额外突出贡献的营员，在原有答辩成绩的基础上额外增加一颗 🌟。

| 项目标题&介绍                                                | 锁定营员（GitHub ID） | 成绩                      |
| ------------------------------------------------------------ | --------------------- | ------------------------- |
| [PIR 算子补全与兼容机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目一pir-算子补全与兼容机制建设) | @xingmingyyj          | 优秀                      |
| [PIR 控制流专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二pir-控制流专项) | @huangjiyi            | 优秀                      |
| [PIR Python API 升级及机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目三pir-python-api-升级及机制建设) | @zrr1999              | 优秀（特别奖励）          |
| [动转静 SOT 模块 Python 3.12 支持](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目四动转静-sot-模块-python-312-支持) | @gouzil               | 优秀（特别奖励）          |
| [算子支持复数计算专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目五算子支持复数计算专项) | @zbt78                | 优秀                      |
| [框架 API 易用性提升](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目七框架-api-易用性提升) | @NKNaN                | 优秀（特别奖励）          |
| [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | @zeroRains            | 优秀                      |
| [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | @Eddie-Wang1120       | 优秀                      |
| [高阶微分的性能分析和优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目九高阶微分的性能分析和优化) | @YibinLiu666          | 优秀（特别奖励）          |
| [静态图半自动并行训练性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十静态图半自动并行训练性能优化) | @AndSonder            | 优秀（特别奖励+助教奖励） |
| [全自动并行架构升级](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十一全自动并行架构升级) | @Corle-hyz            | 优秀                      |
| [科学计算领域拓展专项（DeePMD-kit、光学案例）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十二科学计算领域拓展专项deepmd-kit光学案例) | @xusuyong             | 优秀                      |
| [科学计算领域拓展专项（领域流体方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十四科学计算领域拓展专项领域流体方向) | @DUCH714              | 良好                      |
| [科学计算领域拓展专项（领域气象方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十五科学计算领域拓展专项领域气象方向) | @Yang-Changhui        | 优秀（特别奖励）          |
| [CINN 支持动态 Shape 专项（前端方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十六cinn-支持动态-shape-专项前端方向) | @lshpku               | 优秀（特别奖励）          |
| [CINN 支持动态 Shape 专项（前端方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十六cinn-支持动态-shape-专项前端方向) | @ZelinMa557           | 优秀                      |
| [CINN 支持动态 Shape 专项（PIR 部分）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十七cinn-支持动态-shape-专项pir-部分) | @Xinyu302             | 良好                      |
| [CINN 支持动态 Shape 专项（PIR 部分）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十七cinn-支持动态-shape-专项pir-部分) | @fty1777              | 良好                      |
| [CINN 静态 shape 下鲁棒性和性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十八cinn-静态-shape-下鲁棒性和性能优化) | @yulangz              | 良好                      |
| [CINN 静态 shape 下鲁棒性和性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十八cinn-静态-shape-下鲁棒性和性能优化) | @WintersMontagne10335 | 良好                      |
| [CINN 支持动态 Shape 专项 （后端规则升级）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十九cinn-支持动态-shape-专项后端规则升级) | @Austin-00            | 优秀                      |
| [CINN 支持动态 Shape 专项 （后端模型扩量）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十cinn-支持动态-shape-专项后端模型扩量) | @unseenme             | 及格                      |
| [Paddle CMake 治理和编译优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十一paddle-cmake-治理和编译优化) | @silverling           | 优秀                      |
| [PaddleMIX 套件能力建设（文图方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十二paddlemix-套件能力建设文图方向) | @Tsaiyue              | 优秀                      |
| [PaddleMIX 套件能力建设（图文方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十三paddlemix-套件能力建设图文方向) | @cocoshe              | 优秀                      |
| [大模型训练稳定性和高效低价小模型快速收敛](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十四大模型训练稳定性和高效低价小模型快速收敛) | @lishuai-97           | 良好                      |
| [推理 Pass & 融合算子优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十六推理-pass--融合算子优化) | @yinfan98             | 优秀                      |
| [模型迁移工具建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目六模型迁移工具建设) | @RedContritio | 优秀 |  

祝贺这些同学成功顺利结营 🥳，同时也由衷感谢所有营员的积极参与和卓越贡献！🎉🎉🎉希望各位在未来的开发之路更上一层楼～

## 入选营员名单公示

恭喜以下 28 位同学成功入选**第六期黑客松护航计划集训营**～🎉

| 开源贡献 repo | 项目标题&介绍 | 锁定营员（GitHub ID） | 导师 （GitHub ID）|
| ------------- | ------------------------------------------------- | -------------------------- | ---- |
| Paddle | [PIR 算子补全与兼容机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目一pir-算子补全与兼容机制建设) | @xingmingyyj | @kangguangli |
| Paddle | [PIR 控制流专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二pir-控制流专项) | @huangjiyi | @winter-wang |
| Paddle | [PIR Python API 升级及机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目三pir-python-api-升级及机制建设) | @zrr1999<br>- | @YuanRisheng<br>@0x45f  |
| Paddle | [动转静 SOT 模块 Python 3.12 支持](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目四动转静-sot-模块-python-312-支持) | @gouzil | @SigureMo |
| Paddle | [算子支持复数计算专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目五算子支持复数计算专项) | @zyt1024<br>@zbt78 | @GGBond8488 |
| PaConvert | [模型迁移工具建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目六模型迁移工具建设) | @RedContritio | @zhwesky2010 |
| Paddle | [框架 API 易用性提升](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目七框架-api-易用性提升) | @NKNaN | @zhwesky2010 |
| Paddle | [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | @zeroRains | @cyber-pioneer |
| Paddle | [高阶微分的性能分析和优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目九高阶微分的性能分析和优化) | @YibinLiu666 | @HydrogenSulfate |
| Paddle | [静态图半自动并行训练性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十静态图半自动并行训练性能优化) | @AndSonder | @From00 |
| Paddle | [全自动并行架构升级](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十一全自动并行架构升级) | @Corle-hyz | @Caozhohou1995 |
| PaddleScience | [科学计算领域拓展专项（DeePMD-kit、光学案例）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十二科学计算领域拓展专项deepmd-kit光学案例) | @xusuyong | @HydrogenSulfate |
| PaddleScience | [科学计算领域拓展专项（超分重构方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十三科学计算领域拓展专项超分重构方向) | @zhaojiameng | @lijialin03 |
| PaddleScience | [科学计算领域拓展专项（领域流体方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十四科学计算领域拓展专项领域流体方向) | @DUCH714 | @wangguan1995 |
| PaddleScience | [科学计算领域拓展专项（领域气象方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十五科学计算领域拓展专项领域气象方向) | @Yang-Changhui | @zhiminzhang0830 |
| Paddle | [CINN 支持动态 Shape 专项（前端方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十六cinn-支持动态-shape-专项前端方向) | @lshpku<br> @ZelinMa557 | @zyfncg<br> @jiahy0825 |
| Paddle | [CINN 支持动态 Shape 专项（PIR 部分）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十七cinn-支持动态-shape-专项pir-部分) | @Xinyu302</br>@fty1777 | @zhangbopd |
| Paddle | [CINN 静态 shape 下鲁棒性和性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十八cinn-静态-shape-下鲁棒性和性能优化) | @yulangz  <br>@WintersMontagne10335 | @feifei-111  <br>@2742195759 |
| Paddle | [CINN 支持动态 Shape 专项 （后端规则升级）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十九cinn-支持动态-shape-专项后端规则升级) | - | @BiynXu |
| Paddle | [CINN 支持动态 Shape 专项 （后端模型扩量）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十cinn-支持动态-shape-专项后端模型扩量) | @unseenme | @zhhsplendid |
| Paddle | [Paddle CMake 治理和编译优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十一paddle-cmake-治理和编译优化) | @silverling | @risemeup1 |
| PaddleMIX | [PaddleMIX 套件能力建设（文图方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十二paddlemix-套件能力建设文图方向) | @Tsaiyue | @westfish |
| PaddleMIX | [PaddleMIX 套件能力建设（图文方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十三paddlemix-套件能力建设图文方向) | @cocoshe | @LokeZhou |
| Paddle | [大模型训练稳定性和高效低价小模型快速收敛](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十四大模型训练稳定性和高效低价小模型快速收敛) | @lishuai-97 | @GuoxiaWang |
| Paddle | [推理 Pass & 融合算子优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十六推理-pass--融合算子优化) | @yinfan98 | @yuanlehome |

## 报名记录

**报名格式参考：**

```
【报名】：1
【其他意向】：2、4、6
不接受调剂
```

简历投递邮箱 📮：ext_paddle_oss@baidu.com

> [!IMPORTANT]
> 报名截止延长至 **2024 年 2 月 23 日**，报名后务必尽快提交简历参与面试哦～

> [!NOTE]
> 基于往期护航计划学员的表现以及项目的延续性，部分项目已提前锁定营员～

| 项目编号 | 开源贡献 repo | 项目标题&介绍                                     | 人数 | 报名情况 | 锁定营员                   |
| -------- | ------------- | ------------------------------------------------- | :----: | :--------: | -------------------------- |
| 1 | Paddle | [PIR 算子补全与兼容机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目一pir-算子补全与兼容机制建设) | 1 | - | @xingmingyyj | 
| 2 | Paddle | [PIR 控制流专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二pir-控制流专项) | 1 | - | @huangjiyi | 
| 3 | Paddle | [PIR Python API 升级及机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目三pir-python-api-升级及机制建设) | 2 |  | @zrr1999 | 
| 4 | Paddle | [动转静 SOT 模块 Python 3.12 支持](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目四动转静-sot-模块-python-312-支持) | 1 | - | @gouzil | 
| 5 | Paddle | [算子支持复数计算专项](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目五算子支持复数计算专项) | 2 | @NKNaN <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@zbt78 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @zyt1024<br>@zbt78 | 
| 6 | PaConvert | [模型迁移工具建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目六模型迁移工具建设) | 1 | - | @RedContritio | 
| 7 | Paddle | [框架 API 易用性提升](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目七框架-api-易用性提升) | 1 | @shiofjsaio <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @NKNaN | 
| 8 | Paddle | [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | 1 | @zeroRains <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @zeroRains | 
| 9 | Paddle | [高阶微分的性能分析和优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目九高阶微分的性能分析和优化) | 1 | @YibinLiu666 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @YibinLiu666 | 
| 10 | Paddle | [静态图半自动并行训练性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十静态图半自动并行训练性能优化) | 1 | - | @AndSonder | 
| 11 | Paddle | [全自动并行架构升级](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十一全自动并行架构升级) | 1 | - | @Corle-hyz | 
| 12 | PaddleScience | [科学计算领域拓展专项（DeePMD-kit、光学案例）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十二科学计算领域拓展专项deepmd-kit光学案例) | 1 | - | @xusuyong | 
| 13 | PaddleScience | [科学计算领域拓展专项（超分重构方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十三科学计算领域拓展专项超分重构方向) | 1 | @zhaojiameng <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@gdmec <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @zhaojiameng | 
| 14 | PaddleScience | [科学计算领域拓展专项（领域流体方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十四科学计算领域拓展专项领域流体方向) | 1 | @DUCH714 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @DUCH714 | 
| 15 | PaddleScience | [科学计算领域拓展专项（领域气象方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十五科学计算领域拓展专项领域气象方向) | 1 | @AIzealotwu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Yang-Changhui | 
| 16 | Paddle | [CINN 支持动态 Shape 专项（前端方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十六cinn-支持动态-shape-专项前端方向) | 2 | @lshpku <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @lshpku<br> @ZelinMa557 | 
| 17 | Paddle | [CINN 支持动态 Shape 专项（PIR 部分）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十七cinn-支持动态-shape-专项pir-部分) | 2 | @diadestiny <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Xinyu302 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@fty1777 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Xinyu302</br>@fty1777 | 
| 18 | Paddle | [CINN 静态 shape 下鲁棒性和性能优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十八cinn-静态-shape-下鲁棒性和性能优化) | 2 | @WintersMontagne10335 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@yulangz <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @yulangz  <br>@WintersMontagne10335 | 
| 19 | Paddle | [CINN 支持动态 Shape 专项 （后端规则升级）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十九cinn-支持动态-shape-专项后端规则升级) | 1 | @lknt <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@shiofjsaio <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |  | 
| 20 | Paddle | [CINN 支持动态 Shape 专项 （后端模型扩量）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十cinn-支持动态-shape-专项后端模型扩量) | 1 | @unseenme <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @unseenme | 
| 21 | Paddle | [Paddle CMake 治理和编译优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十一paddle-cmake-治理和编译优化) | 1 | @silverling <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @silverling | 
| 22 | PaddleMIX | [PaddleMIX 套件能力建设（文图方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十二paddlemix-套件能力建设文图方向) | 1 | @shiofjsaio <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Yang-Changhui <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@lixcli <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Tsaiyue <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Tsaiyue | 
| 23 | PaddleMIX | [PaddleMIX 套件能力建设（图文方向）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十三paddlemix-套件能力建设图文方向) | 1 | @cocoshe <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @cocoshe | 
| 24 | Paddle | [大模型训练稳定性和高效低价小模型快速收敛](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十四大模型训练稳定性和高效低价小模型快速收敛) | 1 | - | @lishuai-97 | 
| 25 | Paddle | [动转静 SOT 项目支持动态 Shape](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十五动转静-sot-项目支持动态-shape) | 1 |  | @diadestiny | 
| 26 | Paddle | [推理 Pass & 融合算子优化](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十六推理-pass--融合算子优化) | 1 | @yinfan98 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@xlcjz <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @yinfan98 | 

## 统计信息 
> 排名不分先后 
#####

**Comment by silverling** [comment]
【报名】：21
【其他意向】：22
接受调剂

**Comment by zeroRains** [comment]
【报名】：8
【其他意向】：9、7、17
接受调剂

**Comment by PommesPeter** [comment]
【报名】：23
【其他意向】：6，7，22
接受调剂

**Comment by WintersMontagne10335** [comment]
【报名】：18
【其他意向】：17，19， 20，2
接受调剂

**Comment by WintersMontagne10335** [comment]
【报名】：18
【其他意向】：17，19， 20
接受调剂

**Comment by WintersMontagne10335** [comment]
【报名】：18
【其他意向】：17、19、20
接受调剂

**Comment by NKNaN** [comment]
【报名】：5
【其他意向】：15、22、23
接受调剂

**Comment by diadestiny** [comment]
【报名】：17
【其他意向】：16、18、19
接受调剂

**Comment by shiofjsaio** [comment]
【报名】：22
【其他意向】：23，7
接受调剂

**Comment by cocoshe** [comment]
【报名】：23
【其他意向】：22，7，19，20
接受调剂

**Comment by yulangz** [comment]
【报名】：18
【其他意向】：16、17
接受调剂

**Comment by Xinyu302** [comment]
【报名】：17
【其他意向】：18
接受调剂

**Comment by unseenme** [comment]
【报名】：20
【其他意向】：19、16、17、18、21
不接受调剂

**Comment by Yang-Changhui** [comment]
【报名】：22
【其他意向】：21,19
接受调剂

**Comment by lixcli** [comment]
【报名】：22
【其他意向】：23,16
不接受调剂

**Comment by DUCH714** [comment]
【报名】：14
不接受调剂

**Comment by Tsaiyue** [comment]
【报名】：22
【其他意向】：23
接受调剂

**Comment by zbt78** [comment]
【报名】：5
【其他意向】：19，16
接受调剂

**Comment by shiofjsaio** [comment]
【报名】：7
【其他意向】：19
接受调剂

**Comment by fty1777** [comment]
【报名】：17
【其他意向】：18
接受调剂

**Comment by YibinLiu666** [comment]
【报名】：9
不接受调剂

**Comment by zhaojiameng** [comment]
【报名】：13
【其他意向】：15， 25
接受调剂

**Comment by AIzealotwu** [comment]
【报名】：15
【其他意向】：25，19，16
接受调剂

**Comment by gdmec** [comment]
【报名】：13
【其他意向】：6,12,22,23
接受调剂
【253198】

**Comment by cindy20241900** [comment]
【报名】：6
【其他意向】：3、6、11
接受调剂

**Comment by ZelinMa557** [comment]
【报名】：10
【其他意向】：16、19、11
不接受调剂

**Comment by lshpku** [comment]
【报名】：16
【其他意向】：19
接受调剂

**Comment by lknt** [comment]
【报名】：19
【其他意向】：16
接受调剂

**Comment by FlamingoPg** [comment]
【报名】：26
【其他意向】：无
不接受调剂

**Comment by xlcjz** [comment]
【报名】：26
【其他意向】：无
不接受调剂

**Comment by TimePrinciple** [comment]
【报名】：3
【其他意向】：19
不接受调剂

**Comment by shiofjsaio** [comment]
【报名】：19
【其他意向】：无
接受调剂

**Comment by fuxiaojie2024** [comment]
【报名】16
【其他意向】6
接受调剂
