### ISSUE TITLE
pp2.6 0D张量赋值掉python pp2.6 0D tensor assignment will cause Python to crash

### ISSUE THREAD

**Issue by PlumBlossomMaid** [PaddlePaddle/Paddle#61040]
### bug描述 Describe the Bug

当框架版本为2.6时，运行如下代码会导致python直接崩溃。
When the framework version is 2.6, running the following code will cause Python to crash directly.
```python
from paddle import *
import paddle
paddle.set_device("cpu")
print(paddle.__version__)
s = to_tensor(0)
s[s == 0.0] = 1
print("done")
```
![a_prob](https://github.com/PaddlePaddle/Paddle/assets/108660099/ebec0f46-af00-40d9-b49e-d03a1b180713)
经过测试，0D张量在通过相同的方式进行赋值时，如果框架的版本为2.5及以下，则会直接报错。
After testing, when a 0D tensor is assigned in the same way, if the framework version is 2.5 or below, it will directly raise an error.
![image](https://github.com/PaddlePaddle/Paddle/assets/108660099/36bb5b1c-57cc-4435-b9c7-1dda288155d0)
在同类框架Pytorch中，0D张量则可以正常赋值。
In similar framework Pytorch, 0D tensor can be assigned normally.
![image](https://github.com/PaddlePaddle/Paddle/assets/108660099/4646dc79-5a72-4d4f-9365-2e74c2e06673)

### 其他补充信息 Additional Supplementary Information

希望可以尽快修复此bug。
Hope this bug can be fixed as soon as possible.

**Comment by caizejun** [comment]
0DTensor 理论上就不应该支持下标操作，torch可能优化的好一些，你可以直接s=1这样对0DTensor赋值

**Comment by PlumBlossomMaid** [comment]
那可以把这个问题优化一下吗？
![input](https://github.com/PaddlePaddle/Paddle/assets/108660099/25e5ec5e-4c4f-4eff-835f-7b6b594241c4)

**Comment by caizejun** [comment]
不好意思 我没有看到你之前的回复 实在对不起 我们这边会做出优化的

**Comment by PlumBlossomMaid** [comment]
目前3.x框架已经修复此bug，确认问题解决。
