### ISSUE TITLE
提供Android平台编译有什么用，能简单说一下吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6105]
在这里[Android平台编译指南](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/mobile/cross_compiling_for_android_cn.md#android平台编译指南)我看到了Android平台的编译文档，这有什么用吗，paddlepaddle能用在Android上吗，用它能干什么？

**Comment by sweetsky0901** [comment]
预测的时候可以跑在android上面

**Comment by yeyupiaoling** [comment]
@sweetsky0901 在Android上训练吗？在服务器删训练不是更好吗？

**Comment by sweetsky0901** [comment]
不是在安卓上训练，而是训练出来的模型做预测的时候，跑在安卓上，比如训练出来一个人脸识别，要在手机端真正识别脸的应用需要预测用到

**Comment by yeyupiaoling** [comment]
@sweetsky0901 好像有点理解了，就是把训练好的模型放在APP上做预测，就不用访问服务器，识别会快很多，是这样吗？

**Comment by NHZlX** [comment]
可以这么理解。

**Comment by yeyupiaoling** [comment]
@NHZlX 你有没有这个相关的教程博客，官方的不是很详细

**Comment by NHZlX** [comment]
关于移动端 可以看这个repo https://github.com/PaddlePaddle/Mobile  有关于这个repo的问题， 欢迎提issue

**Comment by yeyupiaoling** [comment]
@NHZlX 通过这个[教程](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/mobile/cross_compiling_for_android_cn.md)，生成了三个文件夹，哪怎么用呢？

**Comment by NHZlX** [comment]
refer:  https://github.com/PaddlePaddle/Mobile/tree/develop/benchmark/tool/C

**Comment by yeyupiaoling** [comment]
这个命令是怎么用的`./inference --merged_model ./model/mobilenet.paddle --input_size 150528`，小白，不是很懂

**Comment by NHZlX** [comment]
https://github.com/NHZlX/Mobile/blob/649b7129fe041a6904f392d04bc0d96914ae13f5/benchmark/tool/C/README.md   看这个文档， 会详细一些

**Comment by yeyupiaoling** [comment]
@NHZlX 感谢你的回答，我好好研究研究

**Comment by yeyupiaoling** [comment]
@NHZlX 
`adb push inference mobilenet.paddle /sdcard/test_mobilenet
adb shell
cd /sdcard/test_mobilenet
./inference --merged_model ./mobilenet.paddle --input_size 150528
`
最后一个命令是什么意思？

**Comment by NHZlX** [comment]
你可以看一下inference.cc 的代码， 具体是：读入model， 然后做20次前向预测，然后计算平均时间。一般用来做测试用。

**Comment by yeyupiaoling** [comment]
![image](https://user-images.githubusercontent.com/26297768/33671171-e41f4b7e-dae1-11e7-993c-573232261506.png)
@NHZlX  这部分是不是分成两步，第一步编译`inference.cc`，第二步执行下面的命令

**Comment by yeyupiaoling** [comment]
@NHZlX 我执行了`make`之后，在build文件夹的的如下图，哪些文件是我们需要的
![image](https://user-images.githubusercontent.com/26297768/33698425-5970f0fc-db47-11e7-894a-f1d1c5467fa1.png)
