### ISSUE TITLE
fluid接口保存的静态图模型，能否以动态图模式加载？

### ISSUE THREAD

**Issue by SenitCo** [PaddlePaddle/Paddle#61135]
### 需求描述 Feature Description

求教下，paddle.fluid.io.save_inferece_model()接口保存的静态图模型文件，可以用类似于paddle.jit.load()这种接口的动态图模式加载吗？

**Comment by zhiminzhang0830** [comment]
这个应该是不支持，建议还是jit.save和jit.load配合使用
