### ISSUE TITLE
请问prior_box算子的参数variances的长度是固定为4吗，如果不是的话，是与什么相关

### ISSUE THREAD

**Issue by raining-dark** [PaddlePaddle/Paddle#61136]
### 请提出你的问题 Please ask your question

![image](https://github.com/PaddlePaddle/Paddle/assets/33216444/5344914e-62db-42e1-b405-cd932f631581)

**Comment by raining-dark** [comment]
而且当variances的长度小于4时，cpu的prior_box算子与gpu的实现以及结果不一致；请问这个是bug吗

**Comment by zhiminzhang0830** [comment]
这个参数必须是4哈

**Comment by raining-dark** [comment]
好的，谢谢，不过我看intel的caffe实现里面，variances长度他给限制的是1或者4
<img width="383" alt="03815c5d320de1d79d19dd774a80f623" src="https://github.com/PaddlePaddle/Paddle/assets/33216444/9f2031c6-ab33-45a7-89fb-e133bc09d23a">

https://github.com/intel/caffe/blob/44d536385dc41804a673c527b4c2df2675770dff/src/caffe/layers/prior_box_layer.cpp#L94

**Comment by zhiminzhang0830** [comment]
嗯嗯，不过还是建议长度直接设置为4哈

**Comment by raining-dark** [comment]
好的，谢谢
