### ISSUE TITLE
wav2lip 转onnx（部署）

### ISSUE THREAD

**Issue by drakitLiu** [PaddlePaddle/Paddle#61142]
### 请提出你的问题 Please ask your question

wav2lip 转onnx后，生成的onnx模型输出维度变为：[-1, 3, 96, 96]，而原来paddlepaddle的模型正常输出是[-1, 6, 96, 96]，请问这是什么问题？

**Comment by drakitLiu** [comment]
转换过程：
1、python -u tools/export_model.py -c configs/wav2lip_hq.yaml --load applications/tools/checkpoints/wav2lip_hq.pdparams --inputs_size="-1,1,-1,-1;-1,6,-1,-1"
2、paddle2onnx --model_dir ./ --model_filename wav2lipmodelhq_netG.pdmodel --params_filename wav2lipmodelhq_netG.pdiparams --save_file model.onnx --enable_dev_version True --opset_version 13 --enable_onnx_checker True
3、onnx_model = onnx.load("model.onnx")
# 使用 ONNX 库检查 ONNX 模型是否合理
check = onnx.checker.check_model(onnx_model)
# 打印检查结果
print('check: ', check)
None
4、ort_inputs = {ort_sess.get_inputs()[0].name: mel_batch, ort_sess.get_inputs()[1].name: img_batch}
pred = ort_sess.run(None, ort_inputs)
print('pred', np.asarray(pred).shape)
（1，49，3，96，96） # 那个1我不知道怎么出来的，49是batch，3好像是通道？奇了怪了 ，不应该是6吗？还有就是为什么wav2lip的输入通道是6？我看了onnx模型也没发现分组卷积啊？难道我搞错了？总之，

输出尺寸应该是（-1，6，96，96）对吧？可是我的onnx输出尺寸是（-1，3，96，96）

**Comment by zhiminzhang0830** [comment]
这边按照[文档](https://github.com/PaddlePaddle/PaddleGAN/blob/develop/docs/zh_CN/tutorials/wav2lip.md)运行的方式，paddlepaddle生成器的输出形状是（128,3,96,96），通道数是3。注意到，该模型生成器代码最后有个判断分支可能会影响输出数据的形状，可以在相应的套件issue问下该分支的作用。
```
        x = self.output_block(x)
        if input_dim_size > 4:
            x = paddle.split(x, int(x.shape[0] / B), axis=0)
            outputs = paddle.stack(x, axis=2)

        else:
            outputs = x
```

**Comment by drakitLiu** [comment]
感谢！但是您是想告诉我这个输出是正常的？还是不正常的？

还有就是，如果该模型的最后的那个判别生成器这部分代码它影响到了输出的尺寸，那为什么原模型它的输出它是正常的，它的通道是6呢？
您提交的代码段是在PaddleGAN下的，我两天前就已经提交相关的issue，并没有得到答复，

**Comment by zhiminzhang0830** [comment]
@LielinJiang 辛苦帮忙看下吧

**Comment by zhiminzhang0830** [comment]
辛苦@LielinJiang 帮忙看下吧

**Comment by LielinJiang** [comment]
在gan的issue中回复了

> 感谢！但是您是想告诉我这个输出是正常的？还是不正常的？
> 
> 还有就是，如果该模型的最后的那个判别生成器这部分代码它影响到了输出的尺寸，那为什么原模型它的输出它是正常的，它的通道是6呢？ 您提交的代码段是在PaddleGAN下的，我两天前就已经提交相关的issue，并没有得到答复，
