### ISSUE TITLE
一直安装失败paddlepaddle_npu

### ISSUE THREAD

**Issue by sunbopython** [PaddlePaddle/Paddle#61159]
### 问题描述 Issue Description

cc1plus: all warnings being treated as errors
make[2]: *** [paddle/phi/CMakeFiles/phi.dir/build.make:1577: paddle/phi/CMakeFiles/phi.dir/kernels/funcs/eigen/broadcast.cc.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:8110: paddle/phi/CMakeFiles/phi.dir/all] Error 2
make: *** [Makefile:160: all] Error 2
编译过程中同时也会出现
[  9%] Performing install step for 'extern_rocksdb'
[  9%] Completed 'extern_rocksdb'
[  9%] Built target extern_rocksdb
make: *** [Makefile:160: all] Error 2然后就中断了

### 版本&环境信息 Version & Environment Information

操作系统：Linux-4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64-aarch64-with-glibc2.28.
python版本：3.10.13 (main, Sep 11 2023, 13:18:45) [GCC 11.2.0]
根据官网 https://www.paddlepaddle.org.cn/documentation/docs/zh/2.2/guides/09_hardware_support/npu_docs/paddle_install_cn.html安装一直没成功

**Comment by xysheng-baidu** [comment]
错误信息显示为"cc1plus: all warnings being treated as errors"和"make: *** [Makefile:133: all] Error 2"。这种情况通常是由于编译过程中的警告被当作错误处理导致的。可能的原因是编译选项中设置了"-Werror"，将所有警告视为错误。解决方法是修改编译选项，将"-Werror"改为"-Wno-error"，以允许编译过程中的警告。另外，还需要确保编译环境和依赖项都正确安装。
参考文档：https://github.com/PaddlePaddle/Paddle/issues/53932

**Comment by sunbopython** [comment]
> 错误信息显示为"cc1plus: all warnings being treated as errors"和"make: *** [Makefile:133: all] Error 2"。这种情况通常是由于编译过程中的警告被当作错误处理导致的。可能的原因是编译选项中设置了"-Werror"，将所有警告视为错误。解决方法是修改编译选项，将"-Werror"改为"-Wno-error"，以允许编译过程中的警告。另外，还需要确保编译环境和依赖项都正确安装。 参考文档：#53932

好的 谢谢 现在编译没有上述错误  
[ 32%] Linking CXX shared library libphi.so
/usr/bin/ld: cannot find -lnpu_hccl
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/phi/CMakeFiles/phi.dir/build.make:12416: paddle/phi/libphi.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:8110: paddle/phi/CMakeFiles/phi.dir/all] Error 2
make: *** [Makefile:160: all] Error 2再次中断
