### ISSUE TITLE
编译安装Paddle2.6.0当-DWITH_GPU=ON时报错

### ISSUE THREAD

**Issue by TingquanGao** [PaddlePaddle/Paddle#61152]
### 问题描述 Issue Description

编译安装Paddle2.6.0预测库，当-DWITH_GPU=ON时报错，OFF则没有问题。同样的cmake命令在paddle2.5.1版本可以正常编译完成。

docker：registry.baidubce.com/paddlepaddle/paddle:2.5.2-gpu-cuda11.7-cudnn8.4-trt8.4

cmake命令：`cmake .. -DWITH_PYTHON=OFF -DWITH_TESTING=OFF -DWITH_MKL=ON -DWITH_GPU=ON -DON_INFER=ON -DENABLE_ONNXRUNTIME=OFF`

报错信息部分截图：
<img width="619" alt="截屏2024-01-25 11 10 41" src="https://github.com/PaddlePaddle/Paddle/assets/12560511/a817256c-45e4-41d6-b9c5-6a5e4b90f41a">

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: ubuntu 18.04
GCC version: (GCC) 8.2.0
Clang version: 3.8.0 (tags/RELEASE_380/final)
CMake version: version 3.16.0
Libc version: glibc 2.27
Python version: 3.10.13

CUDA version: 11.7.64
Build cuda_11.7.r11.7/compiler.31294372_0
cuDNN version: N/A
Nvidia driver version: 520.61.05
Nvidia driver List:
GPU 0: NVIDIA A100 80GB PCIe
GPU 1: NVIDIA A100 80GB PCIe
GPU 2: NVIDIA A100 80GB PCIe
GPU 3: NVIDIA A100 80GB PCIe

****************************************

**Comment by risemeup1** [comment]
你好，请升级你的cmake版本到cmake3.18，具体操作命令入下：
wget -q https://cmake.org/files/v3.18/cmake-3.18.0-Linux-x86_64.tar.gz && tar -zxvf cmake-3.18.0-Linux-x86_64.tar.gz && rm cmake-3.18.0-Linux-x86_64.tar.gz

export PATH=/home/cmake-3.18.0-Linux-x86_64/bin:$PATH
