### ISSUE TITLE
data_norm只支持静态图接口吗？paddle.fluid.layers.data_norm和paddle.static.nn.data_norm

### ISSUE THREAD

**Issue by SenitCo** [PaddlePaddle/Paddle#61168]
### 请提出你的问题 Please ask your question

data_norm只找到了这两个接口，paddle.fluid.layers.data_norm和paddle.static.nn.data_norm，看着都只支持静态图模式，有动态图的版本吗？

**Comment by xysheng-baidu** [comment]
是的，目前PaddlePaddle的data_norm接口只支持静态图模式，暂时没有动态图的版本。
