### ISSUE TITLE
cannot find -lnpu_hccl

### ISSUE THREAD

**Issue by sunbopython** [PaddlePaddle/Paddle#61172]
### 问题描述 Issue Description

[ 32%] Linking CXX shared library libphi.so
/usr/bin/ld: cannot find -lnpu_hccl
collect2: error: ld returned 1 exit status
make[2]: *** [paddle/phi/CMakeFiles/phi.dir/build.make:12416: paddle/phi/libphi.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:8110: paddle/phi/CMakeFiles/phi.dir/all] Error 2
make: *** [Makefile:160: all] Error 2

### 版本&环境信息 Version & Environment Information

操作系统：Linux-4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64-aarch64-with-glibc2.28.
python版本：3.10.13 (main, Sep 11 2023, 13:18:45) [GCC 11.2.0]
PaddlePaddle版本号（2.6.0）

**Comment by sunbopython** [comment]
编译过程中一直报这个错误 找不到如何安装npu_hccl

**Comment by qili93** [comment]
请发送下您详细的编译命令和步骤，方便定位具体问题，谢谢 :)

NPU编译请参考此文档 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

**Comment by sunbopython** [comment]
> 请发送下您详细的编译命令和步骤，方便定位具体问题，谢谢 :)
> 
> NPU编译请参考此文档 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

cmake .. -DPY_VERSION=3.10 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON \
         -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-Wno-error -w" 
make TARGET=ARMV8 -j$(nproc)

**Comment by qili93** [comment]
> > 请发送下您详细的编译命令和步骤，方便定位具体问题，谢谢 :)
> > NPU编译请参考此文档 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
> 
> cmake .. -DPY_VERSION=3.10 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-Wno-error -w" make TARGET=ARMV8 -j$(nproc)

请问您是在PaddlePaddle主框架代码下编译NPU吗？NPU的代码已经从主框架移动到 PaddleCustomDevice了，主框架的Paddle代码不再支持 WITH_ASCEND_CL 的编译方式了。

请您移步到 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/release/2.6/backends/npu/README_cn.md 这个文档进行NPU的编译，谢谢！

**Comment by sunbopython** [comment]
> > > 请发送下您详细的编译命令和步骤，方便定位具体问题，谢谢 :)
> > > NPU编译请参考此文档 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
> > 
> > 
> > cmake .. -DPY_VERSION=3.10 -DWITH_ASCEND=OFF -DWITH_ARM=ON -DWITH_ASCEND_CL=ON -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-Wno-error -w" make TARGET=ARMV8 -j$(nproc)
> 
> 请问您是在PaddlePaddle主框架代码下编译NPU吗？NPU的代码已经从主框架移动到 PaddleCustomDevice了，主框架的Paddle代码不再支持 WITH_ASCEND_CL 的编译方式了。
> 
> 请您移步到 https://github.com/PaddlePaddle/PaddleCustomDevice/blob/release/2.6/backends/npu/README_cn.md 这个文档进行NPU的编译，谢谢！

好的 谢谢 去掉WITH_ASCEND_CL 编译过去了

**Comment by yhz0120** [comment]
@qili93 你好，我已知存在PaddleCustomDevice仓库
问下 npu_hccl 这个库文件应该是昇腾cann生态提供的吧？
我看到paddle的develop分支 CMake文件中依然保留这个依赖选项，但是在cann 6.0 版本后似乎中不到，想问下

1. 最开始添加这个依赖时，这个库文件是cann哪个版本提供的? 
2. 是driver提供的，还是tool-kit提供的?
