### ISSUE TITLE
注释中链接为两行，是否能修改链接在一行

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#61196]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/static/quantization/post_training_quantization.py

![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/1745e59a-d528-4481-a616-b7d37b7f8a0a)
注释中链接为两行，是否能修改链接在一行，这样容易选择

**Comment by SigureMo** [comment]
可以，链接不应该折行
