### ISSUE TITLE
执行demo/quick_start/preprocess.sh报perl的错误

### ISSUE THREAD

**Issue by jw8023wh** [PaddlePaddle/Paddle#612]
如题：
在执行demo/quick_start/preprocess.sh时报如下错误：

![qq 20161125105335](https://cloud.githubusercontent.com/assets/9283249/20613287/73c7c1d8-b2fd-11e6-9bf4-f6c554206db6.png)

**Comment by qingqing01** [comment]
这个是Perl安装不对导致的。 这个[PR](https://github.com/PaddlePaddle/Paddle/pull/573 )里我们提供了预处理好的数据。下载地址：

wget http://paddlepaddle.bj.bcebos.com/demo/quick_start_preprocessed_data/preprocessed_data.tar.gz

**Comment by wangkuiyi** [comment]
@jw8023wh 目前[Quick Start文档](http://www.paddlepaddle.org/doc/demo/quick_start/index_en.html)里对数据下载和预处理的过程描述如下：

```
cd demo/quick_start
./data/get_data.sh
./preprocess.sh
```

如果用 @qingqing01 预处理好的数据，那么上述步骤可以替换为：

```
cd demo/quick_start/data
wget http://paddlepaddle.bj.bcebos.com/demo/quick_start_preprocessed_data/preprocessed_data.tar.gz
```
