### ISSUE TITLE
编译出来的生成的paddlepaddle_npu 不是npu

### ISSUE THREAD

**Issue by sunbopython** [PaddlePaddle/Paddle#61200]
### 问题描述 Issue Description

根据https://www.paddlepaddle.org.cn/documentation/docs/zh/2.2/guides/09_hardware_support/npu_docs/paddle_install_cn.html编译安装的
编译命令
cmake .. -DPY_VERSION=3.10 -DWITH_ASCEND=OFF -DWITH_ARM=ON \
         -DWITH_ASCEND_INT64=ON -DWITH_DISTRIBUTE=ON -DWITH_TESTING=ON -DON_INFER=ON \
         -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_CXX_FLAGS="-Wno-error -w" 
make TARGET=ARMV8 -j$(nproc)
中途编译过程中未出现中断，最后在Paddle/build/python/dist目录中是这个whl，没有npu
paddlepaddle-0.0.0-cp310-cp310-linux_aarch64.whl
安装之后  检测未能启动npu

### 版本&环境信息 Version & Environment Information

操作系统：Linux-4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64-aarch64-with-glibc2.28.
python版本：3.10.13 (main, Sep 11 2023, 13:18:45) [GCC 11.2.0]

**Comment by sunbopython** [comment]
编译完之后检测结果显示还是CPU
(langchain) [root@hmtq-test dist]# python -c "import paddle; paddle.utils.run_check()"
Running verify PaddlePaddle program ... 
I0126 11:59:30.542078 104720 program_interpreter.cc:220] New Executor is Running.
I0126 11:59:30.552757 104720 interpreter_util.cc:652] Standalone Executor is Used.
PaddlePaddle works well on 1 CPU.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.

**Comment by gongweibao** [comment]
你用这个试试?https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

**Comment by sunbopython** [comment]
> 你用这个试试?https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md
(base) [root@hmtq-test ~]# docker pull registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64
Error response from daemon: manifest for registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64 not found: manifest unknown: manifest unknown
貌似是没有这个镜像  
我是910B的 不是x86的选的是这个镜像
registry.baidubce.com/device/paddle-npu:cann700-910B-ubuntu18-aarch64

**Comment by bukejiyu** [comment]
你好，该镜像已修复，请再试试
