### ISSUE TITLE
【PaddleInference】NHWC模型推理错误

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle#61234]
### bug描述 Describe the Bug

使用PaddleClas训练并导出了一个NHWC的ResNet-18模型，在推理时发现模型在第一个卷积层推理出现错误，希望帮忙看一下，报错如下:

```
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [1, 224, 224, 3]; the filter's channels is 7, the filter's shape is [64, 3, 7, 7]; the groups is 1, the data_format is NHWC. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == (channel_last ? filter_dims[filter_dims.size() - 1] : filter_dims[1]) * groups, but received input_channels:3 != (channel_last ? filter_dims[filter_dims.size() - 1] : filter_dims[1]) * groups:7.] (at /paddle/paddle/phi/kernels/cpu/conv_util.h:198)
  [operator < fused_conv2d_add_act > error]
```

**Comment by Zheng-Bicheng** [comment]
模型超过25M，无法直接上传至Github，已经上传到了百度网盘

链接: https://pan.baidu.com/s/1tHI_L51eogN6Swuf3zL44g?pwd=0225 提取码: 0225

**Comment by Zheng-Bicheng** [comment]
我用Netron对模型进行了可视化，发现conv2d卷积的OP Shape是OIHW类型，这个是正常的吗？是不是应该是OHWI类型（也就是[64,7,7,3]）

<img width="1512" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/58363586/cc3f1385-993b-41bc-9001-fdf158a0113d">

如果是的话，是不是可以推断出是导出模型的时候出现了问题？

**Comment by yangjianfengo1** [comment]
你好，这个问题可能是导出模型的时候，没有导出nhwc的模型，方便告诉我你是怎么导出的吗？

**Comment by Zheng-Bicheng** [comment]
> 你好，这个问题可能是导出模型的时候，没有导出nhwc的模型，方便告诉我你是怎么导出的吗？

* 我用的是PaddleClas的export脚本直接导出的，我看了下PaddleClas源代码，问题应该是不大的。
* 上图OP的**data_format**状态是**NHWC**，应该是成功导出了NHWC模型的。

**Comment by Zheng-Bicheng** [comment]
@yangjianfengo1 请Fork该项目并运行 [【PaddleClas】使用AVH部署ResNet模型](https://aistudio.baidu.com/projectdetail/7439131?contributionType=1)

**Comment by cuicheng01** [comment]
@Zheng-Bicheng 请提供一下导出的配置和详细的推理命令

**Comment by Zheng-Bicheng** [comment]
配置文件

```
# model architecture
Arch:
  name: ResNet18
  class_num: 3
  data_format: "NHWC"
```


导出数据命令
```
# 导出输入数据为NHWC格式的模型
!python tools/export_model.py \
    -c ./ppcls/configs/ImageNet/ResNet/Lockzhiner_ResNet18_Train_NHWC.yaml \
    -o Global.pretrained_model=/home/aistudio/PaddleClas/output/ResNet18/best_model \
    -o Global.save_inference_dir=./deploy/models/Lockzhiner_ResNet18
```

**Comment by Zheng-Bicheng** [comment]
@cuicheng01 具体脚本可以去AIStudio Fork项目下载？

**Comment by Zheng-Bicheng** [comment]
@cuicheng01 @yangjianfengo1 能排查出问题吗？这个挺重要的，如果基本OP没有能够支持NHWC的话，在微控制器领域，Paddle模型几乎部署不了了。

**Comment by cuicheng01** [comment]
> @cuicheng01 @yangjianfengo1 能排查出问题吗？这个挺重要的，如果基本OP没有能够支持NHWC的话，在微控制器领域，Paddle模型几乎部署不了了。
您好，这个推理命令也给一下呢？

**Comment by Zheng-Bicheng** [comment]
> > 您好，这个推理命令也给一下呢？
```bash
!python python/predict_cls.py -c configs/Lockzhiner_ResNet18_Infer_NHWC.yaml
```

**Comment by Zheng-Bicheng** [comment]
@cuicheng01 @yangjianfengo1 有进展吗？

**Comment by vivienfanghuagood** [comment]
你好，麻烦尝试下 conv融合的pass，这个pass可能在你的模型下触发了bug，
`config.delete_pass("conv_elementwise_add_fuse_pass")`
相关API链接：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/api_reference/python_api_doc/Config/OptimConfig.md

**Comment by Zheng-Bicheng** [comment]
> 你好，麻烦尝试下 conv融合的pass，这个pass可能在你的模型下触发了bug， `config.delete_pass("conv_elementwise_add_fuse_pass")` 相关API链接：https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/master/docs/api_reference/python_api_doc/Config/OptimConfig.md

我尝试了在PaddleClas构建Paddle Inference模型时添加了`config.delete_pass("conv_elementwise_add_fuse_pass")`，见下图

<img width="1512" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/58363586/e2a0b16f-1672-4931-a301-d42d30965a30">

但是还是会出现一样的错误，报错如下：

```text
Config pass op Start
Config pass op End
Warning: If want to use your own label_dict, please input legal path!
Otherwise label_names will be empty!
Traceback (most recent call last):
  File "/home/aistudio/PaddleClas/deploy/python/predict_cls.py", line 161, in <module>
    main(config)
  File "/home/aistudio/PaddleClas/deploy/python/predict_cls.py", line 135, in main
    batch_results = cls_predictor.predict(batch_imgs)
  File "/home/aistudio/PaddleClas/deploy/python/predict_cls.py", line 95, in predict
    self.predictor.run()
ValueError: (InvalidArgument) The number of input's channels should be equal to filter's channels * groups for Op(Conv). But received: the input's channels is 3, the input's shape is [1, 224, 224, 3]; the filter's channels is 7, the filter's shape is [64, 3, 7, 7]; the groups is 1, the data_format is NHWC. The error may come from wrong data_format setting.
  [Hint: Expected input_channels == (channel_last ? filter_dims[filter_dims.size() - 1] : filter_dims[1]) * groups, but received input_channels:3 != (channel_last ? filter_dims[filter_dims.size() - 1] : filter_dims[1]) * groups:7.] (at ../paddle/fluid/operators/fused/conv_fusion_op.cc:297)
  [operator < conv2d_fusion > error]
```

由这个报错大概可以猜测出应该是由于导出模型时，卷积算子weight的权重信息出现错误导致的。举个例子，输入Tensor Shape为NCHW(例如1,3,224,224)，卷积weight的权重是OIHW[64, 3, 7, 7]，此时是可以正常运行的，因为卷积的weight Shape和输入Tensor一一对应了。

但是现在输入Tensor Shape变成了NHWC（例如1,224,224,3），卷积weight的权重还是OIHW[64, 3, 7, 7]，此时就会发现HW和通道三个位置就对应不上了，正常的卷积权重应该是OHWI [64,7,7,3]，我排查了相关的代码逻辑也应该是这个原因。

**Comment by Zheng-Bicheng** [comment]
问题出处在[PaddlePaddle phi/kernels/cpu/conv_util.h 186行](https://github.com/PaddlePaddle/Paddle/blob/755b7495c709cfc46957eb16ec3a55476180a7bf/paddle/phi/kernels/cpu/conv_util.h#L186)。根据函数名称可以看出，这应该是推理卷积的输出Shape时发现输入Tensor的channel和卷积weight的channel对不上导致的。请考虑往这方面排查 @vivienfanghuagood

**Comment by vivienfanghuagood** [comment]
原始导出的模型是没有问题的，这是推理pass优化之后的融合算子weight 没有处理对，绕开的方法是：
`config.delete_pass("conv_elementwise_add_fuse_pass")
config.delete_pass("conv_elementwise_add_act_fuse_pass")
config.delete_pass("conv_elementwise_add2_act_fuse_pass")
config.delete_pass("conv_bn_fuse_pass")` ，这样可以保证跑通。conv融合算子的问题我们在下一个版本会修正。

**Comment by Zheng-Bicheng** [comment]
> 原始导出的模型是没有问题的，这是推理pass优化之后的融合算子weight 没有处理对，绕开的方法是： `config.delete_pass("conv_elementwise_add_fuse_pass") config.delete_pass("conv_elementwise_add_act_fuse_pass") config.delete_pass("conv_elementwise_add2_act_fuse_pass") config.delete_pass("conv_bn_fuse_pass")` ，这样可以保证跑通。conv融合算子的问题我们在下一个版本会修正。

我会再尝试一下这个解决方案，顺便请教一下大佬。这个`config.delete_pass`是在什么时候生效呢？是在`create_predictor`的时候就已经把所有的pass生效了，还是在推理阶段才生效呢。我之所以会猜测是卷积weight的权重的问题，是因为最近在给TVM做Paddle Inference NHWC模型的移植，TVM在读取这个卷积算子的权重后，在OP融合阶段会发生崩溃。

**Comment by vivienfanghuagood** [comment]
delete_pass需要在创建predictor之前设置，也就是在读取模型的阶段禁止使用这几个pass做OP融合。

**Comment by Zheng-Bicheng** [comment]
这个方案确实可行，感谢 @cuicheng01 @yangjianfengo1 @vivienfanghuagood @jzhang533 大佬们的帮助。
