### ISSUE TITLE
dist.all_gather多卡训练hang住

### ISSUE THREAD

**Issue by bixiaopeng0** [PaddlePaddle/Paddle#61260]
### 请提出你的问题 Please ask your question

问题：dist.all_gather训练hang住，不用dist.all_gather正常训练
环境：pd230
请问可能是什么原因呀？

**Comment by wangguan1995** [comment]
paddle2.3目前已经停止更新，建议使用最新版本
建议检查下各个卡allgather的数据是否长度一致
具体问题可以参考：https://github.com/PaddlePaddle/Paddle/issues/50308
