### ISSUE TITLE
multiclass_nms3算子在xpu单测上为什么不提供NoOutput测例？

### ISSUE THREAD

**Issue by zepingWww** [PaddlePaddle/Paddle#61288]
如xpu上[单测实现](https://github.com/PaddlePaddle/Paddle/blob/develop/test/xpu/test_multiclass_nms3_op_xpu.py)，为什么不提供CPU上的[TestMulticlassNMS3OpNoOutput测例](https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_multiclass_nms_op.py#L792)？

提出这个问题的原因是因为接入custom device相关算子遇到了，参考该[issue](https://github.com/PaddlePaddle/PaddleCustomDevice/issues/923)，怀疑是不是主框架上相关适配是不是有点问题？

**Comment by leolishaohao** [comment]
当时没有提供是因为没有考虑到这种情况，可以测试看加上能不能通过。

**Comment by zepingWww** [comment]
> 以测试看加上能不能通过。

这边没有xpu相关的硬件，请问你们可以这边试一下吗？

**Comment by leolishaohao** [comment]
> > 以测试看加上能不能通过。
> 
> 这边没有xpu相关的硬件，请问你们可以这边试一下吗？

我这边试一下

**Comment by leolishaohao** [comment]
> > 以测试看加上能不能通过。
> 
> 这边没有xpu相关的硬件，请问你们可以这边试一下吗？

我测着没问题

**Comment by zepingWww** [comment]
> > > 以测试看加上能不能通过。
> > 
> > 
> > 这边没有xpu相关的硬件，请问你们可以这边试一下吗？
> 
> 我测着没问题

好的多谢，那我这边再看看是什么问题

**Comment by zepingWww** [comment]
> > > 以测试看加上能不能通过。
> > 
> > 
> > 这边没有xpu相关的硬件，请问你们可以这边试一下吗？
> 
> 我测着没问题

请问是在静态图上吗，看上去我这边只有在静态图上才出现

**Comment by leolishaohao** [comment]
> > > > 以测试看加上能不能通过。
> > > 
> > > 
> > > 这边没有xpu相关的硬件，请问你们可以这边试一下吗？
> > 
> > 
> > 我测着没问题
> 
> 请问是在静态图上吗，看上去我这边只有在静态图上才出现

应该是静态图

**Comment by zepingWww** [comment]
> > > > > 以测试看加上能不能通过。
> > > > 
> > > > 
> > > > 这边没有xpu相关的硬件，请问你们可以这边试一下吗？
> > > 
> > > 
> > > 我测着没问题
> > 
> > 
> > 请问是在静态图上吗，看上去我这边只有在静态图上才出现
> 
> 应该是静态图

好的多谢，我再看看底层实现是怎么回事。
