### ISSUE TITLE
【PR merge一些规则】在release分支 QA测试阶段，如何发起新功能pr和bugfix pr

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#613]
当一个开发milestone完成后，从develop分支拉取一个release分支，进行QA测试。由于QA测试可能花费几周时间，因此：

* 如何在QA测试阶段，提交新功能pr应该merge到哪个分支
* 如何在QA测试阶段，针对QA测试出的bug，发起的pr应该merge到哪个分支
* 如何在QA测试阶段，针对自己发现的一些bug，发起的pr应该merge哪个分之

解决上述问题的规则很重要，可以保证release分支功能的完备性，保证release分支的质量，同时满足多人开发新功能的merge需求。

**Comment by reyoung** [comment]
see http://nvie.com/posts/a-successful-git-branching-model/

**Comment by wangkuiyi** [comment]
> * 如何在QA测试阶段，提交新功能pr应该merge到哪个分支

新功能应该是从feature branch merge到 develop branch。

> * 如何在QA测试阶段，针对QA测试出的bug，发起的pr应该merge到哪个分支

应该从release branch开bugfix branch，通过PRmerge到release branch。QA阶段结束之后，release branch会被merge到master和develop两个branch。

> * 如何在QA测试阶段，针对自己发现的一些bug，发起的pr应该merge哪个分之

同上。应该merge到release branch。
