### ISSUE TITLE
在鲲鹏cpu上编译失败

### ISSUE THREAD

**Issue by 2314933036** [PaddlePaddle/Paddle#61326]
### 问题描述 Issue Description
编译的仓库分支为2.6
执行`cmake .. -DPY_VERSION=3 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF`出现
![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/5a729572-3843-4222-9d27-8918df9d423c)
![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/c3a7efde-3959-415e-8da7-ed3520c7bb20)

### 版本&环境信息 Version & Environment Information

![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/22c9258c-444f-41c1-8378-2b1919ed5e4c)

**Comment by lijialin03** [comment]
您好，错误可能是由于使用python3.7导致，Paddle2.6不再支持python3.7，可以尝试更换python3.8/3.9/3.10 (64 bit)后再次尝试编译，编译时可参考官网文档[飞腾/鲲鹏下从源码编译](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html#anchor-0)，如未能解决还请继续反馈，谢谢。

**Comment by 2314933036** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/075f8726-8354-44e3-827e-c9dc43117a79)
已经换成Python3.8了还是一样的错误

**Comment by qili93** [comment]
根据错误提示，您需要再您的cmake命令中指定具体的python版本为3.7或者3.8，`-DPY_VERSION=3` 这个需要改为 `-DPY_VERSION=3.8`

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/530420b2-cdd5-4244-8b3f-1e8c2ecb115a)

**Comment by 2314933036** [comment]
> 根据错误提示，您需要再您的cmake命令中指定具体的python版本为3.7或者3.8，`-DPY_VERSION=3` 这个需要改为 `-DPY_VERSION=3.8`
> 
> ![image](https://private-user-images.githubusercontent.com/16605440/300708055-530420b2-cdd5-4244-8b3f-1e8c2ecb115a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY2MDEyNjYsIm5iZiI6MTcwNjYwMDk2NiwicGF0aCI6Ii8xNjYwNTQ0MC8zMDA3MDgwNTUtNTMwNDIwYjItY2RkNS00MjQ0LThiM2YtMWU4YzJlY2IxMTVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMwVDA3NDkyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMzcwOWJkOWQzYmRiYWQyODEwNGRkMjliZDMzNjE4OTZiYmY3MTI1MDRmYWRjNDU5ZTNmYjVhMjJlZGQxOWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GhJw35Cx8tuJ58e5XlM4-06QubQExd_YSZOT1DZ04sU)

十分感谢您的支持,加了这个参数可以了,另外我测试了3.7可以正常编译2.6分支
目前正在编译中,如有问题再来提问
![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/b600e412-452f-465c-b73d-76da79caf32b)

**Comment by 2314933036** [comment]
![image](https://github.com/PaddlePaddle/Paddle/assets/38069007/b0058884-1e96-41db-ac4d-eb09c10e9fbb)
编译成功了,但是测试不通过,提示`ModuleNotFoundError: No module named 'paddle.fluid'`

**Comment by lijialin03** [comment]
看起来像路径问题，麻烦@qili93 再帮忙看一下吧

**Comment by gouzil** [comment]
> 编译成功了,但是测试不通过,提示`ModuleNotFoundError: No module named 'paddle.fluid'`

`paddle.fluid` 已经弃用了，可以尝试使用`paddle.base`替换

**Comment by 2314933036** [comment]
> > 编译成功了,但是测试不通过,提示`ModuleNotFoundError: No module named 'paddle.fluid'`
> 
> `paddle.fluid` 已经弃用了，可以尝试使用`paddle.base`替换

https://paddleinference.paddlepaddle.org.cn/user_guides/compile_ARM.html
那这个地址的教程需要更新了,
我现在已经换了2.0rc1使用了,目前一切正常
