### ISSUE TITLE
[paddlepaddle2.6.0] FatalError: Segmentation fault is detected by the operating system

### ISSUE THREAD

**Issue by TorRient** [PaddlePaddle/Paddle#61332]
### bug描述 Describe the Bug

I'm encountering an error as shown below when using Paddle.
System Environment：debian12.4
Version：Paddle：paddlepaddle2.6.0, paddleocr==2.7.0.3
Command Code：predict_det.py
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::AnalysisPredictor::ZeroCopyRun()
1   paddle::framework::NaiveExecutor::Run()
2   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, phi::Place const&) 
3   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&) const
4   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, phi::Place const&, paddle::framework::RuntimeContext*) const
5   paddle::framework::OperatorWithKernel::BuildPhiKernelContext(paddle::framework::RuntimeContext const&, phi::DeviceContext*, phi::KernelContext*) const

----------------------
Error Message Summary:
----------------------
FatalError: `Segmentation fault` is detected by the operating system.
  [TimeInfo: *** Aborted at 1706587367 (unix time) try "date -d @1706587367" if you are using GNU date ***]
  [SignalInfo: *** SIGSEGV (@0x7f10594317b2) received by PID 1 (TID 0x7f17d87ff6c0) from PID 
1497569202 ***]

**Comment by lijialin03** [comment]
Hello, We have received the issue. 
Could you please provide a screenshot of the complete printed information from command execution to the error, and whole reproduction environment including operating system/python version/cuda version, etc. 
We will reply to you as soon as possible after reappearance. Thank you.

**Comment by lijialin03** [comment]
Hi, this issue should be supportted under [PaddleOCR](https://github.com/PaddlePaddle/PaddleOCR). Thank you.
