### ISSUE TITLE
分布式训练的时候，paddle训练失败，MPI任务却不结束

### ISSUE THREAD

**Issue by cszhou** [PaddlePaddle/Paddle#6136]
任务训练失败，需要点进去看具体的log才能定位失败原因。但是失败了，却还是没有结束MPI任务。
比如，任务报错。
LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.87.101.33: Connection refused [111]

**Comment by wanghaox** [comment]
请给一下任务具体的情况，job链接。

**Comment by Yancey1989** [comment]
看起来训练进程已经异常退出，这种情况还是需要在内网JIRA上联系下集群管理员帮忙定位下问题。
我先关闭这个issue了，如依然有问题可以随时打开它。
