### ISSUE TITLE
老版本PaddlePaddle编译问题（1.7.2）

### ISSUE THREAD

**Issue by zdxzheng** [PaddlePaddle/Paddle#61403]
### 问题描述 Please describe your issue

安装官网的教程在window11下进行本地编译PaddlePaddle1.7.2分支。链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/windows-compile.html
执行最后的ninja编译命令报错:ninja: error: 'third_party/install/protobuf/lib/libprotobuf.lib', needed by 'paddle/fluid/platform/CMakeFiles/profiler_py_proto', missing and no known rule to make it
编译环境：python3.8.10+cmake3.19.0+visual studio2019
请问又什么解决方法吗？或者那里能够下载PaddlePaddle1.7.2版本？

**Comment by BiynXu** [comment]
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-58-Windows%20%E5%AE%89%E8%A3%85

**Comment by BiynXu** [comment]
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-58-Windows%20%E5%AE%89%E8%A3%85

**Comment by BiynXu** [comment]
https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/install/pip/linux-pip.html#old-version-anchor-58-Windows%20%E5%AE%89%E8%A3%85
这里有1.7版本的安装，可以选择下。

**Comment by zdxzheng** [comment]
> pip安装里面最低版本只有1.8.5，Anaconda安装方式也找不到对应的包了，window环境

**Comment by xuxinyi389** [comment]
可以尝试使用如下命令安装：cpu版本：python -m pip install paddlepaddle==1.7.2 -i https://mirror.baidu.com/pypi/simple
gpu版本：python -m pip install paddlepaddle-gpu==1.7.2 -i https://mirror.baidu.com/pypi/simple

**Comment by xuxinyi389** [comment]
如果需要自行编译的话，ninja的编译支持是在21年完成的（https://github.com/PaddlePaddle/Paddle/pull/31161 ），因此v1.7当时不支持使用ninja构建，此时需要使用MSBuild构建，可参考https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/install/compile/windows-compile.html https://github.com/PaddlePaddle/docs/blob/31015a1c36fe04ec7f9960e768fdb21ca750efc3/docs/install/compile/windows-compile.md   文档内容自行构建。
