### ISSUE TITLE
[PIR] Adaptation of `test_zero_dim_*.py`

### ISSUE THREAD

**Issue by DrRyanHuang** [PaddlePaddle/Paddle#61413]
### 问题描述 Please describe your issue

UPDATE 20240311: 为了方便单测执行，`test/legacy_test/test_zero_dim_tensor.py`文件**已拆分为前缀名是`test_zero_dim_*`的多个文件**，其他没有变化

------

UPDATE 20240219: `test/legacy_test/test_zero_dim_tensor.py`文件中, 大部分单测由 #61575, #61577, #61582 覆盖，本issue记录的单测需要单独适配

------

`test/legacy_test/test_zero_dim_tensor.py` 文件中, 共13个单测类, 284个单测函数
详细报错信息请查看:
- https://github.com/PaddlePaddle/Paddle/pull/61088

|序号|?|Test*|已覆盖|总数|备注|
|:-:|:-:|:-:|:-:|:-:|:-:|
|1|✅|TestUnaryAPI|2|2||
|2|✅|TestReduceAPI|2|2| #61846 因 mac CI hang 住而暂时 revert |
|3|✅|TestBinaryAPI|1|2||
|4|✅|TestSundryAPI|114|114||
|5|✅|TestSundryAPIStatic|84|96|见 `5. TestSundryAPIStatic` |
|6|✅|TestNoBackwardAPI|20|20||
|7|✅|TestNoBackwardAPIStatic|6|21|见`7. TestNoBackwardAPIStatic`|
|8|✅|TestUnaryElementwiseAPIWithComplexInput|2|2||
|9|✅|TestAsReal|2|2||
|10|✅|TestAsComplex|2|2||
|11|✅|TestDistribution|13|13||
|12|✅|TestLossAPI|4|4||
|12|✅|TestLossAPIStatic|4|4||

### 3. TestBinaryAPI

```
TestBinaryAPI.test_static_binary
AttributeError: 'paddle.base.libpaddle.pir.Program' object has no attribute 'current_block'
```

### 4. TestSundryAPI
全动态图无需适配

### 5. TestSundryAPIStatic

| 单测函数| ? |
| :-: |  :-: | 
| test_create_parameter_var | 段错误 |
| test_getitem | 段错误 |
| test_setitem | 将被删除, 未适配 |
| test_tensordot | 段错误 |
| test_with_pir_api | API未适配pir | 
| test_t | 未知, 一跑就卡死 | 
| test_sequence_pad | API未适配pir | 
| test_static_data | API未适配pir | 
| test_static_nn_prelu | API未适配pir | 
| test_dist | 段错误 |
| test_linalg_norm | 段错误 |
| test_trace | 段错误 |

### 6. TestNoBackwardAPI
全动态图无需适配

### 7. TestNoBackwardAPIStatic
| 单测函数| ? |
| :-: |  :-: | 
| test_slice | 未知, 一跑就卡死 |
| test_strided_slice | ✅ |
| test_linspace | 未知, 一跑就卡死 |
| test_arange | ✅ |
| test_normal | 未知, 一跑就卡死 |
| test_rand | TypeError |
| test_randn | TypeError |
| test_randint | ✅ |
| test_randint_like | ✅ |
| test_standard_normal | TypeError |
| test_uniform | TypeError |
| test_empty_and_empty_like | TypeError |
| test_full_and_full_like | TypeError |
| test_ones_and_ones_like | TypeError |
| test_zeros_and_zeros_like | TypeError |
| test_embedding | API未适配pir |
| test_static_embedding | 有大bug, 开启后会导致其他单测出问题 |
| test_one_hot_label | ✅ |
| test_unique_consecutive | InvalidArgumentError, 开启后会导致其他单测出问题 |
| test_unique | InvalidArgumentError, 开启后会导致其他单测出问题 |
| test_static_matrix_rank | ✅ |

### 11. TestDistribution
全动态图无需适配

**Comment by DrRyanHuang** [comment]
这里还有一个 新老 IR 无法对齐 的问题待修复 

在`test/legacy_test/test_zero_dim_tensor.py` 4106行的 `test_increment`

- https://github.com/PaddlePaddle/Paddle/pull/61577#discussion_r1479389982

![A0CC868C-729D-44A6-9469-CF125CE19E3F](https://github.com/PaddlePaddle/Paddle/assets/44900829/edfe0cc1-0377-42e2-9ed6-17c22e6e09ac)

![image](https://github.com/PaddlePaddle/Paddle/assets/44900829/3639f8e0-8a91-4175-a217-fa95be770b95)

**Comment by SigureMo** [comment]
TestReduceAPI 在 mac 流水线上会高频 hang 住，暂时在 #61846 disable 掉

**Comment by SigureMo** [comment]
新状态由 #62652 跟踪
