### ISSUE TITLE
如何提升dataloader加载速度

### ISSUE THREAD

**Issue by HanksYang** [PaddlePaddle/Paddle#61418]
### 请提出你的问题 Please ask your question

使用paddle离线任务训练模型发现耗时都在dataloader上，如何优化减少dataloader耗时，或者说提高CPU核数和内存是否会有帮助
![2a289855afaf647be95865ef91275fcb](https://github.com/PaddlePaddle/Paddle/assets/32157815/41a2db9d-d2f2-4b04-bfa1-8ecf4c7ecd2c)

**Comment by SigureMo** [comment]
如果主要耗时在 dataloader 上，可以先排查下瓶颈在什么地方

- 如果单核 CPU 已经打满，那么可以考虑尝试提高 num_workers 以提供并行度
- 如果 CPU 完全打满，提高 num_workers 也没有效果，那么增加更多核数是可以的有帮助的
- 如果是内存不足，那么提高内存应该是有效果的

个人理解，希望有所帮助

另外 https://discuss.pytorch.org/t/how-to-speed-up-the-data-loader/13740/28 也有一些有用的方法，比如使用 dali 来使用 GPU 来进行数据预处理～

**Comment by daijun-hub** [comment]
如何使用多核cpu进行模型训练呢
