### ISSUE TITLE
Paddle多卡训练读取数据问题

### ISSUE THREAD

**Issue by SenitCo** [PaddlePaddle/Paddle#61481]
### 请提出你的问题 Please ask your question

Paddle多卡训练，实现IterableDataset接口加载数据的时候，需要手动把数据切成n份，还是直接使用paddle.io.DistributedBatchSampler接口就能自动实现数据的切分？
下面是实现IterableDataset迭代器手动切分文件的示例：
```py
def __iter__(self):
      """__iter__"""
      iter_start = 0
      iter_end = self.file_num

      if paddle.distributed.get_world_size() > 1:
          rank_num = paddle.distributed.get_world_size()
          file_num_per_rank = int(math.ceil(float(self.file_num) / rank_num))
          iter_start = paddle.distributed.get_rank() * file_num_per_rank
          iter_end = min(iter_start + file_num_per_rank, self.file_num)

      worker_info = paddle.io.get_worker_info()
      if worker_info is not None and worker_info.num_workers > 1:
          file_num_per_worker = int(math.ceil(float(self.file_num) / worker_info.num_workers))
          worker_id = worker_info.id
          iter_start = worker_id * file_num_per_worker
          iter_end = min(iter_start + file_num_per_worker, iter_end)

      for iter in range(iter_start, iter_end):
          with open(self.file_list[iter], 'r') as f:
              for line in f:
                  process(line)
```

**Comment by Galaxy1458** [comment]
可以使用IterableDataset接口加载数据，并根据进程数量和工作线程数量手动切分数据，也可以使用paddle.io.DistributedBatchSampler接口自动实现数据的切分。

**Comment by SenitCo** [comment]
@Galaxy1458 再请教下，paddle.DataParallel(model)能实现数据的自动切分，以及参数梯度的汇总求和、在多机上的同步更新吗？接口文档好像没有详细提及这些

**Comment by xysheng-baidu** [comment]
> @Galaxy1458 再请教下，paddle.DataParallel(model)能实现数据的自动切分，以及参数梯度的汇总求和、在多机上的同步更新吗？接口文档好像没有详细提及这些

参数多机同步更新的话也需要使用分布式接口包一下，类似于：optimizer = fleet.distributed_optimizer(optimizer)
具体可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/cluster_quick_start_collective_cn.html

**Comment by SenitCo** [comment]
@xysheng-baidu 我上面的表述有点问题，应该是在单机多卡上的同步更新，这种也必须用到fleet专用包吗？我之前是参考这个文档【[链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/cv_experience_cn.html#shierdanjiduokaxunlian)】和相关代码写的多卡训练逻辑，看着只需要用到paddle.distributed.init_parallel_env()和model = paddle.DataParallel(model)这些基础的接口就可以。

另外，我在用多卡训练的时候遇到了部分卡资源无法释放的问题，能辛苦帮看下是什么原因吗？感谢~
https://github.com/PaddlePaddle/Paddle/issues/61663

**Comment by xysheng-baidu** [comment]
> @xysheng-baidu 我上面的表述有点问题，应该是在单机多卡上的同步更新，这种也必须用到fleet专用包吗？我之前是参考这个文档【[链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/cv_experience_cn.html#shierdanjiduokaxunlian)】和相关代码写的多卡训练逻辑，看着只需要用到paddle.distributed.init_parallel_env()和model = paddle.DataParallel(model)这些基础的接口就可以。
> 
> 另外，我在用多卡训练的时候遇到了部分卡资源无法释放的问题，能辛苦帮看下是什么原因吗？感谢~ #61663

fleet不是专用包，内置在paddle里的：from paddle.distributed import fleet
就用基础接口就可以。单机多卡和多机多卡一样都属于分布式训练，接口使用是一样的。
