### ISSUE TITLE
cmake找不到pythonlib

### ISSUE THREAD

**Issue by sidneyzhu** [PaddlePaddle/Paddle#615]
cmake源码编译paddle，提示说找不到python库，python2.7的库通过locate是可以找到的，也在ldconfig的路径里面

![image](https://cloud.githubusercontent.com/assets/5105369/20614435/66e874f6-b309-11e6-8edd-5c3bf68577ff.png)

**Comment by backyes** [comment]
系统里看似有两个python， 这块python cmake处理可能会有bug https://github.com/PaddlePaddle/Paddle/pull/328

建议清理下自己环境里的python，如果可以确保只有一个python解释器。

**Comment by sidneyzhu** [comment]
是的，有一个python2.6，yum用的，另外装了一个python2.7给paddle用的。
要是把python2.6删除，yum就用不了

**Comment by backyes** [comment]
@sidneyzhu 

一般我会选择，如下方法先解决问题： 

* 暂时隐藏2.6版本的python的影响，比如我重命名下老python目录名，欺骗cmake系统

* 然后，编译安装完成之后，再使能老python。

* 运行时，尽量提高2.7版本python的环境变量搜索优先级，主要就是LD_LIBRARY_PATH中优先搜索2.7的路径

* 用到yum等必须依赖低版本的python的时候，绝对路径指定低版本python 解释器。 这种情况一般不大，大部分都是兼容的。

**Comment by sidneyzhu** [comment]
谢谢大家！
