### ISSUE TITLE
Custom Device 如何支持量化

### ISSUE THREAD

**Issue by Rruown** [PaddlePaddle/Paddle#61516]
### 请提出你的问题 Please ask your question

Paddle2.6和最新的develop分支目前开放的关于量化的phi kernel有weight_quantize, weight_dequantize，dequantize, dequantize_linear。尤其疑惑是quantize_linear_kernel.h中只有一个dequantize_linear kernel。我使用PaddleSlim的静态图离线量化功能导出了一个量化模型，默认使用onnex的量化格式（dequantize_linear ,quantize_linear ），但是框架只开放了dequantize_linear kernel该如何支持对激活变量的量化？
![image](https://github.com/PaddlePaddle/Paddle/assets/34084211/17d16067-219c-49bf-a2b6-ab07043f553a)

**Comment by vivienfanghuagood** [comment]
你好，paddle目前支持了相关的int8的matmul / Linear计算，具体可以参考这个PR：
https://github.com/PaddlePaddle/Paddle/pull/57852
目前Paddle通过pass将散的q/dq op融合成quant_linear，具体可以参考这个PR：
https://github.com/PaddlePaddle/Paddle/pull/58637
