### ISSUE TITLE
MPI训练时，多节点时test auc明显低于单节点

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#6155]
每轮Pass后，用测试集计算auc，auc不一致。
单节点时：
Test at Pass 0, {'__auc_evaluator_0__': 0.7868553996086121, 'classification_error_evaluator': 0.2663058936595917}
http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-646520/

多节点时：(10节点）
Test at Pass 0, {'__auc_evaluator_0__': 0.7584338784217834, 'classification_error_evaluator': 0.2819223999977112}
Test at Pass 0, {'__auc_evaluator_0__': 0.7583796381950378, 'classification_error_evaluator': 0.28192976117134094}
Test at Pass 0, {'__auc_evaluator_0__': 0.7583440542221069, 'classification_error_evaluator': 0.2819364368915558}
。。。
http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-646689/

提交代码：
paddle cluster_train \
  --config mpi_train.py \
  --port 8788 \
  --use_gpu cpu \
  --use_remote_sparse 0 \
  --time_limit 100:00:00 \
  --submitter wangdong08 \
  --num_nodes 10 \
  --job_priority normal \
  --trainer_count 1 \
  --num_passes 10 \
  --fs_name hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310 \
  --fs_ugi fcr-ad,2f6b06d4ce \
  --train_data_path /app/ecom/fcr-ad/yitengfei/intent-q/paddle_dssm_intentid/1030.train \
  --test_data_path  /app/ecom/fcr-ad/yitengfei/intent-q/paddle_dssm_intentid/1030.test \
  --output_path /app/ecom/fcr-ad/yitengfei/intent-q/paddle_dssm_intentid/model_output.1030_left_right-64.n10 \
  --where nmg01-hpc-off-dmop-slow-cpu-10G_cluster \
  --thirdparty thirdparty \
  --job_name wangdong08_paddle_cluster_dssm

**Comment by wanghaox** [comment]
可能是多节点和单节点收敛速度不一样

你调整下batch_size看看有没有改善，
参考 https://github.com/PaddlePaddle/Paddle/issues/3555

**Comment by typhoonzero** [comment]
可以试试：
- learning_rate改成单机的learning_rate / batch_size / node_count
- batch_size改成单机batch_size / node_count

**Comment by fty8788** [comment]
@typhoonzero 
mpi单节点时设的参数和单机时是一样的呢
mpi多节点就改了--num_nodes
怎么改？

**Comment by wanghaox** [comment]
可以修改模型文件内的learning_rate和batch_size。
如：
```
optimizer = paddle.optimizer.Momentum(
    learning_rate=0.1 / 128.0,
    momentum=0.9,
    regularization=paddle.optimizer.L2Regularization(rate=0.0005 * 128))
```
```
trainer.train(
    reader=paddle.batch(
        paddle.reader.shuffle(
            paddle.dataset.mnist.train(), buf_size=8192),
        batch_size=128),
    event_handler=event_handler_plot,
    num_passes=5)
```
这两段代码内对应的learning_rate和batch_size参数

**Comment by fty8788** [comment]
原来的配置：
batch_size=40000
learning_rate=1e-3,
regularization=paddle.optimizer.L2Regularization(rate=1e-3),

修改后：
num_nodes = 10
batch_size = 40000/num_nodes
learning_rate=1e-3/float(num_nodes)
regularization=paddle.optimizer.L2Regularization(rate=1e-3*float(num_nodes))
测试AUC也还是挺低的：
Test at Pass 0, {'__auc_evaluator_0__': 0.7550091743469238
http://nmg01-hpc-off-mon.dmop.baidu.com:8090/job/i-639499/

**Comment by ChunweiYan** [comment]
1. 确认下单机和集群里每个 pass 跑的数据是一样多的
2. 但 batch_size 比较大理论上会降低单个 epoch 的效果，分布式时，由于参数服务器会统一更新参数，集群里的一个 batch 其实是 batch_size * node_num
3. batch_size 增大可能会降低效果，如果 batch_size * node_num(集群) > batch_size(单机) ，单个 epoch 效果有所下降是合理的

- 单个 pass/epoch 单机/集群评估精度没有太大必要，最好是评估整个训练完成后的精度
- 训练过程中会输出多个模型，遍历这些模型得到最好的跟单机最好的比

集群训练的确会有效果与速度的 tradeoff，包括 batch_size 之内的参数需要好好调下才可能降低集群的影响。

正常情况下，影响不会太显著，试试最终出来模型的效果吧

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时打开它。
