### ISSUE TITLE
paddle 怎么对两个layer取min

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6157]
rt，想获取 两个layer 对应元素的最小值，怎么用paddle实现？

**Comment by wanghaox** [comment]
现在还不支持类似操作。
请提供一下详细的模型应用场景。

**Comment by ranqiu92** [comment]
额，与模型中周围的计算没多大关系，只需要实现这个运算，是否可以通过其他的api搭出来呢

**Comment by ranqiu92** [comment]
是所复现的一篇论文中 它自定义的一个loss里需要用到，所以与周围计算没多大关联。

**Comment by chengduoZH** [comment]
Fluid里面已经有了 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/elementwise_max_op.h
