### ISSUE TITLE
各位大佬，我的pycharm 不能调试paddle，请问 pycharm 是怎么获取 conda evn 的 cudatoolkit 版本的 或者说 conda 的 env 能设置好虚拟环境让 pycharm 识别吗？

### ISSUE THREAD

**Issue by thehzzz** [PaddlePaddle/Paddle#61610]
### 问题描述 Issue Description

我本机安装的是 cuda 11.8

我通过官网命令
conda install paddlepaddle-gpu==2.4.2 cudatoolkit=11.2 -c https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/Paddle/ -c conda-forge

在conda 在虚拟环境 PADDLED 安装了 cudatoolkit 11.2 ，这个 PADDLED 也一直显示 cuda 版本信息是 11.8 ，也没办法跑通项目。我的理解是 conda 应该自动帮我把虚拟环境设置后，为什么会一直显示 11.8 这个错误的版本。后来我通过设置 conda env config vars set 把 cudatoolkit 版本设置好后，cuda 版本终于正确，可以跑通项目

但我在尝试使用 pycharm 调试 PADDLED 的时候，pycharm 没办法识别 PADDLED 的 cuda 版本，各位大佬是怎么设置的呢？ 或者 conda 在设置虚拟环境的时候正确的做法是那样呢。

感谢各位大佬阅读，祝各位大佬新春快乐。

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：2.4.2
GPU：3090，CUDA11.2 和CUDNN 8.2.1。
系统环境：ubuntu 18
Python 3.9
conda 安装cudatoolkit 11.2 cudnn8.2.1
Comment

**Comment by liaoxin2** [comment]
根据已知信息，可以尝试以下方法来设置PyCharm识别PADDLED的CUDA版本：

1. 确保已经在PyCharm中正确配置了conda环境。在PyCharm的设置中，选择"Project: [项目名称]"，然后选择"Python Interpreter"。确保选择了正确的conda环境。

2. 在PyCharm中打开终端，并激活PADDLED环境。使用以下命令激活conda环境：
   ```
   conda activate PADDLED
   ```

3. 在终端中运行以下命令，查看CUDA版本是否正确：
   ```
   nvcc --version
   ```

   如果CUDA版本显示正确，那么PyCharm应该能够正确识别PADDLED的CUDA版本。如果仍然无法识别，可以尝试重启PyCharm并重新配置conda环境。

如果以上方法仍然无法解决问题，建议检查PyCharm的版本是否与PADDLED的版本兼容，并确保正确安装了PyCharm的插件以支持PaddlePaddle。此外，还可以尝试更新PaddlePaddle和PyCharm的版本，或者在PyCharm中手动设置CUDA路径。

**Comment by thehzzz** [comment]
@liaoxin2 非常感谢，已经解决问题！
