### ISSUE TITLE
PaddlePaddle 是否支持按照范数对梯度进行截断？

### ISSUE THREAD

**Issue by lcy-hugepanda** [PaddlePaddle/Paddle#6162]
训练深层复杂RNN模型时容易出现梯度爆炸。Paddle是支持通过限制梯度的范数等于固定的值（按照 norm 对梯度进行软截断）？怎样实现呢？

**Comment by kuke** [comment]
@lcy-hugepanda Paddle目前支持的是一种按值对梯度进行截断的方式，请参考[#3968](https://github.com/PaddlePaddle/Paddle/issues/3968); 按范数截断的方式已有一个实现，但是还没有merge，可以参考[#4970](https://github.com/PaddlePaddle/Paddle/pull/4970)。

**Comment by lcy-hugepanda** [comment]
好的，非常感谢。
