### ISSUE TITLE
Paddle中怎样实现一个自定义的evaluator，在训练过程中输出呢？

### ISSUE THREAD

**Issue by lcy-hugepanda** [PaddlePaddle/Paddle#6163]
我想定义一个自己的 evaluator，随着训练输出每个mini-batch上的评估结果，请问该怎么做呢？是否有文档可供参考。

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/5883 

参考：https://github.com/PaddlePaddle/models/tree/develop/ltr#训练过程中输出自定义评估指标

**Comment by lcy-hugepanda** [comment]
好的，谢谢啦。
