### ISSUE TITLE
Paddle算子单元测试的输入规模为什么必须大于100？

### ISSUE THREAD

**Issue by runzhech** [PaddlePaddle/Paddle#61650]
### 请提出你的问题 Please ask your question

在编写算子的过程中发现，Paddle/test/legacy_test/op_test.py:529会对算子的输入规模进行检查，如果输入规模小于100则会报错，但是实际情况中经常会出现规模小于100的情况。请问规定“算子输入规模必须大于100”的目的是什么？

**Comment by chen2016013** [comment]
规定算子输入规模必须大于100的目的可能是为了确保算子的输入数据具有一定的规模和复杂性，以便更好地测试算子的正确性和稳定性。
较小的输入规模可能无法充分考虑算子在大规模数据上的表现，无法全面评估算子的正确性和效率。通过设置输入规模大于100的要求，可以更好地模拟实际应用场景中的情况，提高算子的鲁棒性和可靠性。

**Comment by runzhech** [comment]
> 规定算子输入规模必须大于100的目的可能是为了确保算子的输入数据具有一定的规模和复杂性，以便更好地测试算子的正确性和稳定性。 较小的输入规模可能无法充分考虑算子在大规模数据上的表现，无法全面评估算子的正确性和效率。通过设置输入规模大于100的要求，可以更好地模拟实际应用场景中的情况，提高算子的鲁棒性和可靠性。

@chen2016013 但是有两种情况：
1. 真实训练场景中存在某一较小规模，且想要在单测中进行测试。
2. 某类特定算子，例如Paddle/test/legacy_test/test_elementwise_add_op.py:277，想要测试y长度为1时的正确性。

这些情况都会引入较小的输入规模。观察到现有单测中一些测试小规模的例子，如Paddle/test/legacy_test/test_elementwise_add_op.py:277中是使用skip_check_grad_ci的装饰器，暂时使得测试能够通过。这里我有些不理解，因为即使是小规模，我觉得也是需要检查梯度的

**Comment by chen2016013** [comment]
这里小规模梯度检查的需求确实没有被优先考虑到，感谢反馈。我个人的想法是：
1. 大规模数据上梯度的正确性可以基本确保小规模数据的梯度正确性
2. 从校验角度来讲，防止大规模数据的叠加精度误差有较高优先级

**Comment by runzhech** [comment]
> 这里小规模梯度检查的需求确实没有被优先考虑到，感谢反馈。我个人的想法是：
> 
> 1. 大规模数据上梯度的正确性可以基本确保小规模数据的梯度正确性
> 2. 从校验角度来讲，防止大规模数据的叠加精度误差有较高优先级

@chen2016013 感谢回复，想确认一下
1. 之后是否有计划取消最小规模的限制？
2. 如果不打算取消，那么今后遇到必要情况（例如上面提到的两种情况），是否可以统一使用skip_check_grad_ci来跳过检查？（由于在单测中使用这个装饰器会踩到approval的CI，所以需要确认一下）

**Comment by chen2016013** [comment]
> > 这里小规模梯度检查的需求确实没有被优先考虑到，感谢反馈。我个人的想法是：
> > 
> > 1. 大规模数据上梯度的正确性可以基本确保小规模数据的梯度正确性
> > 2. 从校验角度来讲，防止大规模数据的叠加精度误差有较高优先级
> 
> @chen2016013 感谢回复，想确认一下
> 
> 1. 之后是否有计划取消最小规模的限制？
> 2. 如果不打算取消，那么今后遇到必要情况（例如上面提到的两种情况），是否可以统一使用skip_check_grad_ci来跳过检查？（由于在单测中使用这个装饰器会踩到approval的CI，所以需要确认一下）

1. 短期没有取消限制的规划
2. 如果开发过程中需要approval可以联系相关人员review
