### ISSUE TITLE
修改类型参数CI错误

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#61681]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/pull/61670/

![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/0341e25b-e79c-4428-9f36-153e8e0b93df)
修改类型参数CI错误

https://xly.bce.baidu.com/paddlepaddle/paddle/newipipe/detail/10084104/job/25303418
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/738fb310-3741-4e89-b9ee-4f029f2b7f97)

**Comment by SigureMo** [comment]
flaot32 在 `test/legacy_test/test_sum_op.py` 也有，应该 xpu 的单测是从 legacy_test copy 的，一起修复下吧

同一个 name 的 Variable 应该只有同一个 dtype，把所有 paddle.static.data 的 name 都改成不一样的吧

这部分本身是测报错的，目测还有些其他问题，可以思考下能不能改对

**Comment by co63oc** [comment]
查看代码是测试类型错误不用修改
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/8ad61129-f0c4-4477-9594-95cfa5986991)
