### ISSUE TITLE
Python Error: <type 'exceptions.NameError'> : name 'LogActivation' is not defined

### ISSUE THREAD

**Issue by zuowang** [PaddlePaddle/Paddle#617]
我在网络配置中使用LogActivation，出现如下错误：
Python Error: <type 'exceptions.NameError'> : name 'LogActivation' is not defined
Python Callstack:
/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3406
/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3382
vgg_16_mnist.py : 123

但是LogActivation有定义，其他如ReluActivation, ExpActivation等都没问题

**Comment by luotao1** [comment]
在`python/paddle/trainer_config_helpers/Activations.py`的
```
__all__ = [
    "TanhActivation", "SigmoidActivation", "SoftmaxActivation",
    "IdentityActivation", "LinearActivation", 'SequenceSoftmaxActivation',
    'ExpActivation', "ReluActivation", "BReluActivation", "SoftReluActivation",
    "STanhActivation", "AbsActivation", "SquareActivation", "BaseActivation"
]
```
中没有定义，马上fix一下。

**Comment by zuowang** [comment]
多谢！
