### ISSUE TITLE
Question about framework::OpRegistry::CreateOp in Executor::Run.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#6170]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/executor.cc#L122

From the code here, the executor will call `OpRegistry::CreateOp` each mini-batch to create the same operator? Even if the network graph does not change.

**Comment by jacquesqiao** [comment]
yes, it will call
https://github.com/PaddlePaddle/Paddle/blob/c9b57dcc8314720ad01aa0e9c2d3f0711657749a/paddle/framework/type_defs.h#L44

to create a new op

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/details/op_registry.h#L82
