### ISSUE TITLE
Questions about the group in img_conv_layer

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/Paddle#6173]
The doc [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2531) and the code [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L2115) indicate the total number of filters is `number_filters * group`, while code in some other places also indicates the total number of filters is `number_filters / group` like [here](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer/config_parser.py#L714). Which is right.

**Comment by qingqing01** [comment]
> the total number of filters is number_filters / group

This is right. Our doc is wrong. This issue is related to #https://github.com/PaddlePaddle/Paddle/issues/5907

**Comment by guoshengCS** [comment]
Close this issue since the fix.
