### ISSUE TITLE
DOS due to high usage of memory

### ISSUE THREAD

**Issue by rook1337** [PaddlePaddle/Paddle#61752]
### bug描述 Describe the Bug

Check here https://huntr.com/bounties/f0eed0b0-95ed-487a-9218-d1891adc8753/

### 其他补充信息 Additional Supplementary Information

Check here https://huntr.com/bounties/f0eed0b0-95ed-487a-9218-d1891adc8753/

**Comment by rook1337** [comment]
@zhangbopd 
Kind reminder to check the report

**Comment by rook1337** [comment]
Hello team,
Need clarification about why it is not considered as security risk?

Because this occurring due to user inputs and its going to consume too much memory which will leads to consume lots of energy as well.

**Comment by VigiZhang** [comment]
OOM indicating that the available memory is exhausted. We consider OOM is not a security risk.
