### ISSUE TITLE
Linux 下使用 ninja 从源码编译error

### ISSUE THREAD

**Issue by aturbofly** [PaddlePaddle/Paddle#61794]
### 问题描述 Issue Description

参考https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/compile/linux-compile-by-ninja.html#compile_from_host 编译安装。
执行：ninja -j$(nproc)
包如下error:

ninja: error: 'third_party/install/mkldnn/lib64/libdnnl.so', needed by 'paddle/phi/tools/print_pten_kernels', missing and no known rule to make it

### 版本&环境信息 Version & Environment Information

paddle: 2.3
python:3.8

**Comment by cxxly** [comment]
@risemeup1

**Comment by risemeup1** [comment]
2.3不支持Ninja，永make编把
