### ISSUE TITLE
pdiparams如何转成pdparams？

### ISSUE THREAD

**Issue by frotms** [PaddlePaddle/Paddle#61799]
### 请提出你的问题 Please ask your question

请问如何将静态图的pdiparams参数转成动态图的pdparams？

**Comment by cxxly** [comment]
参数和动/静态图没有关系。保证Paddle版本一致，静态图下保存，然后动态图下加载就行。如果还有疑问，可以把问题描述具体一下

**Comment by frotms** [comment]
动态图怎么加载pdiparams呢？用什么接口？

**Comment by cxxly** [comment]
> 动态图怎么加载pdiparams呢？用什么接口？

https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/load_cn.html#load,  https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/model_save_load_cn.html

**Comment by frotms** [comment]
使用paddle.jit.load读取ppocr_v4_det模型会报错，python3.8, paddle 2.6.0

模型地址：[https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar)

我理解这个模型也是用torch.jit.save保存的。我试着把它的[train模型](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_train.tar)序列化保存后也无法load

```
import paddle
params_dir = "./models_v2.7/ppocrv4/ch_PP-OCRv4_det_infer/"
load_layer_state_dict = paddle.jit.load(params_dir)
```

 报错信息：


![Snipaste_2024-02-19_20-33-47](https://github.com/PaddlePaddle/Paddle/assets/18061450/2ae10496-b285-4fd8-9b03-95ee442a4c47)

**Comment by cxxly** [comment]
> 使用paddle.jit.load读取ppocr_v4_det模型会报错，python3.8, paddle 2.6.0
> 
> 模型地址：https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_infer.tar
> 
> 我理解这个模型也是用torch.jit.save保存的。我试着把它的[train模型](https://paddleocr.bj.bcebos.com/PP-OCRv4/chinese/ch_PP-OCRv4_det_train.tar)序列化保存后也无法load
> 
> ```
> import paddle
> params_dir = "./models_v2.7/ppocrv4/ch_PP-OCRv4_det_infer/"
> load_layer_state_dict = paddle.jit.load(params_dir)
> ```
> 
> 报错信息：
> 
> ![Snipaste_2024-02-19_20-33-47](https://private-user-images.githubusercontent.com/18061450/305950016-2ae10496-b285-4fd8-9b03-95ee442a4c47.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MDA1NjEsIm5iZiI6MTcwODQwMDI2MSwicGF0aCI6Ii8xODA2MTQ1MC8zMDU5NTAwMTYtMmFlMTA0OTYtYjI4NS00ZmQ4LTliMDMtOTVlZTQ0MmE0YzQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDAzMzc0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFmZTljNTJkNzViOTczYjE3YzhkMjA2MWRlZGQ1OTVhYTFlMTNiM2Q5YmNiNTk0ODI1NTA0NmFjMDMzYjU3NjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.g8F4Z0F9TKfo9nn-PXD0z0xayAWW43k8HtejScqxGOI)

加上模型名称，params_dir = "./models_v2.7/ppocrv4/ch_PP-OCRv4_det_infer/inference"
