### ISSUE TITLE
频繁打印 Get BackendSet from tensor 怎么办？

### ISSUE THREAD

**Issue by GuoDapeng** [PaddlePaddle/Paddle#61837]
### 请提出你的问题 Please ask your question

```
/Users/felix/Documents/paddlepaddle/demo/venv/bin/python -X pycache_prefix=/Users/felix/Library/Caches/JetBrains/PyCharm2023.3/cpython-cache /Users/felix/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 61098 --file /Users/felix/Documents/paddlepaddle/demo/test.py 
已连接到 pydev 调试器(内部版本号 233.13763.11)WARNING: Logging before InitGoogleLogging() is written to STDERR
I0219 20:43:19.297171 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297619 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297631 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297672 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297681 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297714 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297724 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297744 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
I0219 20:43:19.297755 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
Inference result is [[19.301105]], the corresponding label is 19.700000762939453

进程已结束，退出代码为 0
```

我觉得我成功了，看着预测的结果很接近了。但是频繁打印 Get BackendSet from tensor 淹没了我的调试信息，训练的时候会出很多。有什么办法不打印这个吗？我明天找个台式机试试，实在不行我就用台式机学习了。

  型号名称：	MacBook Pro
  芯片：	Apple M3 Max

**Comment by cgerx** [comment]
同样的情况 Macbook m2 Max 。 paddle 2.6.0

**Comment by GuoDapeng** [comment]
> ### 请提出你的问题 Please ask your question
> ```
> /Users/felix/Documents/paddlepaddle/demo/venv/bin/python -X pycache_prefix=/Users/felix/Library/Caches/JetBrains/PyCharm2023.3/cpython-cache /Users/felix/Applications/PyCharm Professional Edition.app/Contents/plugins/python/helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client 127.0.0.1 --port 61098 --file /Users/felix/Documents/paddlepaddle/demo/test.py 
> 已连接到 pydev 调试器(内部版本号 233.13763.11)WARNING: Logging before InitGoogleLogging() is written to STDERR
> I0219 20:43:19.297171 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297619 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297631 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297672 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297681 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297714 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297724 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297744 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> I0219 20:43:19.297755 3682196544 kernel_dispatch.h:102] Get BackendSet from tensor
> Inference result is [[19.301105]], the corresponding label is 19.700000762939453
> 
> 进程已结束，退出代码为 0
> ```
> 
> 我觉得我成功了，看着预测的结果很接近了。但是频繁打印 Get BackendSet from tensor 淹没了我的调试信息，训练的时候会出很多。有什么办法不打印这个吗？我明天找个台式机试试，实在不行我就用台式机学习了。
> 
> 型号名称： MacBook Pro 芯片： Apple M3 Max

确实同样的代码，台式机没有问题，是苹果电脑拉垮了。

**Comment by DesmonDay** [comment]
<img width="651" alt="截屏2024-02-20 下午3 05 49" src="https://github.com/PaddlePaddle/Paddle/assets/20554008/eb854d3e-749e-4d72-816c-52674ed82312">
正常来讲这个 log 等级比较低，是不会打印出来的。试试看设置 export GLOG_v=0。

**Comment by cgerx** [comment]
> <img alt="截屏2024-02-20 下午3 05 49" width="651" src="https://private-user-images.githubusercontent.com/20554008/306164596-eb854d3e-749e-4d72-816c-52674ed82312.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg0MTM0NzIsIm5iZiI6MTcwODQxMzE3MiwicGF0aCI6Ii8yMDU1NDAwOC8zMDYxNjQ1OTYtZWI4NTRkM2UtNzQ5ZS00ZDcyLTgxNmMtNTI2NzRlZDgyMzEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIwVDA3MTI1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM4MDRjOWZiM2JiNWMwNTE2YzIyODI2MDU3MzE3ODViMjY3ZjYwOGM2NmU4NGUzNzkzYmU2YmJjZjU1MjViNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c-RXUbFVOpr7B2H6wEjWK0LZWNzuId7haj2epb1wFEk"> 正常来讲这个 log 等级比较低，是不会打印出来的。试试看设置 export GLOG_v=0。

<img width="287" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/30364539/efdc0ba2-ddaf-4932-9623-fc9599afd3c7">
<img width="702" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/30364539/f754c07a-3350-4306-a111-44805a5bca33">
设置后好像没用

**Comment by DesmonDay** [comment]
那我找相关同学看看。

**Comment by yuanlehome** [comment]
这个我也遇到了类似的情况，求值班同学看一下～ 机器A10
![image](https://github.com/PaddlePaddle/Paddle/assets/23653004/cbac6625-9fb9-43ed-b743-19789337cf21)

**Comment by DesmonDay** [comment]
@yuanlehome 你试试设置 export GLOG_v=0 可以吗？

**Comment by yuanlehome** [comment]
> @yuanlehome 你试试设置 export GLOG_v=0 可以吗？

试了，不可以

**Comment by DrownFish19** [comment]
@yuanlehome 
1. 设置这个`export GLOG_minloglevel=10000`可以，修改了输出日志的最小等级。
2. 此处10000为任意设置的数字，大于代码中的`VLOG(8)`或者`VLOG(10)`中的等级8或者等级10就可以。

**Comment by luozeyu1015** [comment]
还没解决吗，import os
os.environ['GLOG_minloglevel'] = '9'怎么设置都没用

**Comment by DrownFish19** [comment]
> 还没解决吗，import os os.environ['GLOG_minloglevel'] = '9'怎么设置都没用

如果在python文件中进行设置，应该添加在paddle被调用之前。
建议直接添加环境变量进行修改。

**Comment by GuoDapeng** [comment]
> @yuanlehome
> 
> 1. 设置这个`export GLOG_minloglevel=10000`可以，修改了输出日志的最小等级。
> 2. 此处10000为任意设置的数字，大于代码中的`VLOG(8)`或者`VLOG(10)`中的等级8或者等级10就可以。

在提出问题的机器上测试，这个解决方案有效。

这里就关闭问题啦。

**Comment by GuoDapeng** [comment]
虽然问题解决了，但是还是有一个小技巧想在这里分享。如果你和我一样，使用 PyCharm ，可以用图片里的步骤，解决鼠标点击调试，环境变量的问题。

![截屏2024-04-03 20 52 19](https://github.com/PaddlePaddle/Paddle/assets/7477750/87441533-cb39-4771-8cc1-f98340f99623)
