### ISSUE TITLE
使用paddle.static.create_parameter函数 中创建的参数 是否可持久化

### ISSUE THREAD

**Issue by lwgkzl** [PaddlePaddle/Paddle#61849]
### 请提出你的问题 Please ask your question

以这个模型为例：
```
class LinearModel(object):
    def __init__(self,hidden_size=64, label_num):
        self.hidden_size = hidden_size
        self.label_num = label_num

    def other_linear(self, input_tensor):
        weight = paddle.static.create_parameter(shape=[self.hidden_size, self.label_num])
        return layers.matmul(input_tensor,weight)

    def get_ouput_put(input_tensor, label):
        output = fluid.layers.fc(input=input_tensor, size=self.hidden_size)
        logits = self.other_linear(input_tensor)
        loss = fluid.layers.sigmoid_cross_entropy_with_logits(logits, label)
        return loss

```
函数other_linear 中的 weight参数， 是每一次运行这个函数就会被重复创建吗？ 也就是说weight这个参数在模型学完之后，最终也是一个接近于随机初始化的状态。 还是说 weight 参数只有第一次会被创建， 之后会一直复用第一次创建的这个变量呢？

**Comment by 2742195759** [comment]
每次都会创建，如果是希望创建一个Parameter，通常都是将这部分逻辑放到 __init__ 中。

**Comment by lwgkzl** [comment]
> 每次都会创建，如果是希望创建一个Parameter，通常都是将这部分逻辑放到 **init** 中。

这意味着， 这个变量每次forward的过程中， 都会被随机初始化一次吗

**Comment by 2742195759** [comment]
我理解得看你怎么使用这个Program了，如果是一次forward拿到Program，然后每次都直接executor run的话，那么其实只会创建一次。可以具体看下Paddle的静态图的使用。
多次forward那一定是创建了两份weight。

**Comment by lwgkzl** [comment]
> 我理解得看你怎么使用这个Program了，如果是一次forward拿到Program，然后每次都直接executor run的话，那么其实只会创建一次。可以具体看下Paddle的静态图的使用。 多次forward那一定是创建了两份weight。

明白了， 感谢
