### ISSUE TITLE
Make ConvTransProjection support for dilation.

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#6187]
We calculate output size of [ConvTransProjection](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ConvTransProjection.cpp) with origin [filterH_]((https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ConvTransProjection.cpp#L27)) and  [filterW_](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/ConvTransProjection.cpp#L33), but not take into consideration dilation.
It  should be wrote as:
```
imageH_ = imageSize(outputH_,
                        (filterH_ - 1) * dilationH_ + 1,
                        paddingH_,
                        strideH_,
                       /* caffeMode */ true);
```

And,  [outputSize](https://github.com/wanghaoshuang/Paddle/blob/develop/paddle/math/MathUtils.cpp#L71) and [imageSize](https://github.com/wanghaoshuang/Paddle/blob/develop/paddle/math/MathUtils.cpp#L84) are not always reciprocal, so we should't use  [origin IMAGE_SIZE](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/test_LayerGrad.cpp#L243) as ConvTransProjection output size while using [output_x](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/tests/test_LayerGrad.cpp#L242) as input size.

**Comment by tonyyang-svail** [comment]
Excellent!
