### ISSUE TITLE
作业执行GPU集群训练报错（集群是docker环境的）

### ISSUE THREAD

**Issue by dale1202** [PaddlePaddle/Paddle#6190]
报： Unknown class type: cudnn_conv，求指教。我cuda和cudnn环境都装好了

[INFO 2017-12-02 13:11:51,066 layers.py:1985] output size for __pool_4__ is 1*1
I1202 13:11:51.076820    59 Trainer.cpp:170] trainer mode: Normal
F1202 13:11:51.098398    59 ClassRegistrar.h:66] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: cudnn_conv
*** Check failure stack trace: ***
    @     0x7fa925f01daa  (unknown)
    @     0x7fa925f01ce4  (unknown)
    @     0x7fa925f016e6  (unknown)
    @     0x7fa925f04687  (unknown)
    @           0x600835  paddle::Layer::create()
    @           0x538940  _ZZN6paddle13NeuralNetwork4initERKNS_11ModelConfigESt8functionIFviPNS_9ParameterEEERKSt6vectorINS_19enumeration_wrapper13ParameterTypeESaISB_EEbENKUlRKNS_11LayerConfigEE_clESI_
    @           0x539d5b  paddle::NeuralNetwork::init()
    @           0x5479d2  paddle::MultiGradientMachine::MultiGradientMachine()
    @           0x53efde  paddle::GradientMachine::create()
    @           0x67bc98  paddle::TrainerInternal::init()
    @           0x6783ee  paddle::Trainer::init()
    @           0x5132a9  main
    @     0x7fa92510df45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    59 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by will-am** [comment]
这个应该是因为用的是非GPU版本的paddle，应该安装GPU版本的paddle: `pip install paddlepaddle-gpu`

**Comment by dale1202** [comment]
我给里面改了下，--use_gpu=1改好了做了新镜像。镜像里面其他东西还需要改么？

**Comment by will-am** [comment]
其他选项应该不用改
