### ISSUE TITLE
文件不存在 test_relu_expr.py

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#61907]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/cinn/adt/readme.md

![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/6de02851-4e28-46ea-8ca2-494a9248bbf9)

文件不存在 test_relu_expr.py
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/6ef3b5f5-2415-4f57-a48e-440007202f2e)

**Comment by jiahy0825** [comment]
- 修复 PR：https://github.com/PaddlePaddle/Paddle/pull/61941
