### ISSUE TITLE
文档中链接不存在 doc/design/program.md

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#61915]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/cinn/frontend/paddle/framework.proto

![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/2ba6c74e-bb09-41f1-9a8f-af6da72925fb)

文件不存在
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/program.md
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/701d2a52-0d47-44c1-ab4e-aec4be60390f)

**Comment by zyfncg** [comment]
修复[PR61965](https://github.com/PaddlePaddle/Paddle/pull/61965)已合入
