### ISSUE TITLE
Vmware--Ubuntu安装paddle docker失败

### ISSUE THREAD

**Issue by breaknormal1** [PaddlePaddle/Paddle#6196]
目前Ubuntu的是装在Windows VMware虚拟机上，但在装paddle docker时出现了很多奇怪的问题。
想确认一下：paddle docker是否可以安装在VMware的Ubuntu上？NVIDIA驱动是否可以安装在这样的Ubuntu上？现在的Windows上有NVIDIA驱动。
请大神指点。。。。。

**Comment by gongweibao** [comment]
docker可以直接装在windows上。

**Comment by breaknormal1** [comment]
我要使用GPU进行训练，在用GPU训练时，不支持Windows吧？

**Comment by breaknormal1** [comment]
在运行NVIDIA-docker时出现下面的错误
![image](https://user-images.githubusercontent.com/34222954/33535893-7b496bf4-d8eb-11e7-9e74-5e78536616bf.png)
这是啥原因啊？
