### ISSUE TITLE
Mac 编译Paddle报错*** target pattern contains no `%'.  Stop.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6197]
系统版本 ：macOS High Sierra version 10.13.1 (1yB1003)

cmake 编译选项：
```bash
cmake /Users/ying/Documents/codes/Paddle \
    -DPYTHON_EXECUTABLE=/usr/bin/python \
    -DWITH_PYTHON=ON \
    -DPYTHON_LIBRARY=/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib \
    -DCMAKE_BUILD_TYPE=Debug \
    -DWITH_TESTING=ON \
    -DWITH_DOC=OFF \
    -DWITH_C_API=OFF \
    -DWITH_GPU=OFF \
    -DPADDLE_WITH_GPU=OFF \
    -DWITH_STYLE_CHECK=ON \
    -DWITH_TIMER=OFF \
    -DWITH_SWIG_PY=ON \
    -DWITH_MKL=ON \
    -DWITH_MKLML=OFF \
    -DWITH_MKLDNN=OFF
```

make时会报错：
```text
[ 64%] Built target tensor_test
paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60: *** target pattern contains no `%'.  Stop.
make[1]: *** [paddle/framework/CMakeFiles/framework_py_proto.dir/all] Error 2
make: *** [all] Error 2
```
看了一下报错的文件`paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60`的第60行：
```text
paddle/framework/framework_pb2.py: ../paddle/framework/framework.proto
paddle/framework/framework_pb2.py: ../paddle/framework/protobuf::protoc
        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/Users/ying/Documents/codes/Paddle/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Running Python protocol buffer compiler on framework.proto"
        cd /Users/ying/Documents/codes/Paddle/build/paddle/framework && protobuf::protoc --python_out /Users/ying/Documents/codes/Paddle/build/paddle/framework -I /Users/ying/Documents/codes/Paddle/paddle/framework /Users/ying/Documents/codes/Paddle/paddle/framework/framework.proto
```

手工修改下 `paddle/framework/CMakeFiles/framework_py_proto.dir/build.make` 改成下面这样可以正常编译：
```text
paddle/framework/framework_pb2.py: ../paddle/framework/framework.proto
paddle/framework/framework_pb2.py: /Users/ying/Documents/codes/Paddle/build/third_party/install/protobuf/bin/protoc
        @$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --blue --bold --progress-dir=/Users/ying/Documents/codes/Paddle/build/CMakeFiles --progress-num=$(CMAKE_PROGRESS_1) "Running Python protocol buffer compiler on framework.proto"
        cd /Users/ying/Documents/codes/Paddle/build/paddle/framework && protoc --python_out /Users/ying/Documents/codes/Paddle/build/paddle/framework -I /Users/ying/Documents/codes/Paddle/paddle/framework /Users/ying/Documents/codes/Paddle/paddle/framework/framework.proto
```
diff  如下：
![image](https://user-images.githubusercontent.com/5842774/33533394-c9bc49d8-d8db-11e7-9551-ccad5e2089a0.png)

具体的出错原因我也不清楚，没有细看。

---
最后附上 cmake 的输出：

```text
-- Found Paddle host system: macosx, version: 10.13.1
-- Found Paddle host system's CPU: 4 cores
-- The CXX compiler identification is AppleClang 9.0.0.9000038
-- The C compiler identification is AppleClang 9.0.0.9000038
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.13.6 (Apple Git-96)") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Protobuf protoc executable: /Users/ying/Documents/codes/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf library: /Users/ying/Documents/codes/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protobuf version: 3.1
-- Found PythonInterp: /usr/bin/python (found suitable version "2.7.10", minimum required is "2.7") 
-- Found PythonLibs: /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/libpython2.7.dylib (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PY_pip: /Library/Python/2.7/site-packages/pip-9.0.1-py2.7.egg/pip  
-- Found PY_numpy: /Users/ying/Library/Python/2.7/lib/python/site-packages/numpy  
-- Found PY_wheel: /Users/ying/Library/Python/2.7/lib/python/site-packages/wheel  
-- Found PY_google.protobuf: /Users/ying/Library/Python/2.7/lib/python/site-packages/google/protobuf  
-- Found NumPy: /Users/ying/Library/Python/2.7/lib/python/site-packages/numpy/core/include  
-- Found reference-cblas (include: /System/Library/Frameworks/vecLib.framework/Headers, library: /usr/lib/libcblas.dylib)
-- BLAS library: /usr/lib/libcblas.dylib
-- Found SWIG: /usr/local/bin/swig (found version "3.0.12") 
-- warp-ctc library: /Users/ying/Documents/codes/Paddle/build/third_party/install/warpctc/lib/libwarpctc.dylib
-- Ccache is founded, use ccache to speed up compile.
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - failed
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 0.10.0
-- Skip compiling with MKLDNNMatrix
-- Skip compiling with MKLDNNLayers and MKLDNNActivations
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/ying/Documents/codes/Paddle/build
```

**Comment by putcn** [comment]
encountered the same issue here, and this issue is blocking our CI build for Mac

**Comment by putcn** [comment]
https://github.com/PaddlePaddle/Paddle/issues/6441
verifying the fix

**Comment by putcn** [comment]
found the root cause of this issue, if you are building in Mac, make sure your cmake is later than 3.4 or it will throw this error.

**Comment by lcy-seso** [comment]
@putcn  Thank you for figuring out the reason. So I will close this issue.

**Comment by velconia** [comment]
我在用 CMake 3.11.2 编译时遇到了同样的问题, cmake 输出如下:

` cmake .. -DCMAKE_PREFIX_PATH=/usr/local/Cellar/llvm/6.0.0 -DCMAKE_BUILD_TYPE=Release -DWITH_DOC=OFF -DWITH_GPU=OFF -DWITH_TESTING=OFF -DWITH_GOLANG=OFF -DWITH_MKL=OFF
-- Found Paddle host system: macosx, version: 10.12.5
-- Found Paddle host system's CPU: 4 cores
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- The C compiler identification is AppleClang 8.1.0.8020042
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++, version: AppleClang 8.1.0.8020042
-- C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc, version: AppleClang 8.1.0.8020042
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Found Git: /usr/bin/git (found version "2.11.0 (Apple Git-81)") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - found
-- Found Threads: TRUE  
-- Performing Test MMX_FOUND
-- Performing Test MMX_FOUND - Success
-- Performing Test SSE2_FOUND
-- Performing Test SSE2_FOUND - Success
-- Performing Test SSE3_FOUND
-- Performing Test SSE3_FOUND - Success
-- Performing Test AVX_FOUND
-- Performing Test AVX_FOUND - Success
-- Performing Test AVX2_FOUND
-- Performing Test AVX2_FOUND - Success
-- Do not have AVX2 intrinsics and disabled MKL-DNN
-- Protobuf protoc executable: /Users/baidu/workspace/paddle/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf library: /Users/baidu/workspace/paddle/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protobuf version: 3.1
-- Found PythonInterp: /Users/baidu/workspace/conda/miniconda2/bin/python2.7 (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PythonLibs: /Users/baidu/workspace/conda/miniconda2/lib/libpython2.7.dylib (found suitable version "2.7.14", minimum required is "2.7") 
-- Found PY_pip: /Users/baidu/workspace/conda/miniconda2/lib/python2.7/site-packages/pip  
-- Found PY_numpy: /Users/baidu/workspace/conda/miniconda2/lib/python2.7/site-packages/numpy-1.14.1-py2.7-macosx-10.6-x86_64.egg/numpy  
-- Found PY_wheel: /Users/baidu/workspace/conda/miniconda2/lib/python2.7/site-packages/wheel  
-- Found PY_google.protobuf: /Users/baidu/workspace/conda/miniconda2/lib/python2.7/site-packages/google/protobuf  
-- Found NumPy: /Users/baidu/workspace/conda/miniconda2/lib/python2.7/site-packages/numpy-1.14.1-py2.7-macosx-10.6-x86_64.egg/numpy/core/include  
-- Found OpenBLAS (include: /usr/local/opt/openblas/include, library: /usr/local/opt/openblas/lib/libopenblas.dylib)
-- Found lapack in OpenBLAS (include: /usr/local/opt/openblas/include)
-- BLAS library: /usr/local/opt/openblas/lib/libopenblas.dylib
-- Found SWIG: /usr/local/bin/swig (found version "3.0.12") 
-- warp-ctc library: /Users/baidu/workspace/paddle/Paddle/build/third_party/install/warpctc/lib/libwarpctc.dylib
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - failed
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 0.12.0
-- Skip compiling with MKLDNNMatrix
-- Skip compiling with MKLDNNLayers and MKLDNNActivations
-- Skip compiling with MKLPackedLayers
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__ftls_model_global_dynamic
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__ftls_model_global_dynamic - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses_equality - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_self_assign
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_self_assign - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_maybe_uninitialized
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_maybe_uninitialized - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_missing_field_initializers
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_missing_field_initializers - Success
CMake Deprecation Warning at /usr/local/Cellar/cmake/3.11.2/share/cmake/Modules/UseSWIG.cmake:272 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  paddle/api/CMakeLists.txt:66 (SWIG_ADD_MODULE)


-- Configuring done
-- Generating done
-- Build files have been written to: /Users/baidu/workspace/paddle/Paddle/build`

解决方案如 @lcy-seso 所述
