### ISSUE TITLE
svd_norm 调用 elementwise_div axis 问题

### ISSUE THREAD

**Issue by co63oc** [PaddlePaddle/Paddle#61989]
### bug描述 Describe the Bug

https://github.com/PaddlePaddle/Paddle/pull/61746

python/paddle/tensor/linalg.py 中 svd_norm 调用 elementwise_div axis参数传递值为数组[-1]，测试test_linalg_cond.API_TestStaticCond，返回不是整数值错误

![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/4f583dff-dbbc-4d87-96b2-f28bc4888577)
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/e91a0fe3-cd50-4b6c-9d45-f4f88d1eaa67)

**Comment by zoooo0820** [comment]
此处看起来axis不会有其他值输入，是否可以直接改成-1

**Comment by co63oc** [comment]
PR已修改 -1
![image](https://github.com/PaddlePaddle/Paddle/assets/4617245/6b74782e-13f8-44aa-9e47-6f2fc3b4beca)
