### ISSUE TITLE
MKLDNN inference result on Mac

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#6202]
Use [run_mkldnn_infer.sh](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/paddle/image/run_mkldnn_infer.sh) to test MKLDNN/MKLML inference of VGG19/ResNet50/GoogleNet on Mac machine.
- docker environment: paddlepaddle/paddle:latest
- machine: Mac Pro A1502, CPU: 2.7 GHz Intel Core i5, Memory: 8 GB 1867 MHz DDR3

**Comment by kuke** [comment]
GoogleNet

| BatchSize    | 1     | 2     | 4       | 8     |
|--------------|-------| ------| --------|-------| 
| MKLML        | 11.33 | 17.39 | 25.84   | 23.59 |
| MKL-DNN      | 37.43 | 39.42 | 38.50   | 29.10 |

ResNet-50

| BatchSize    | 1     | 2     | 4       | 8     |
|--------------|-------| ------| --------|-------| 
| MKLML        | 3.82  | 5.33  | 6.43    | 5.27  |
| MKL-DNN      | 13.70 | 13.91 | 14.61   | 14.10 |

VGG-19

| BatchSize    | 1     | 2     | 4       | 8     |
|--------------|-------| ------| --------|-------| 
| MKLML        | 1.75  | 2.37  | 2.62    | 2.37  |
| MKL-DNN      | 3.23  | 3.20  | 3.75    | 3.81  |

**Comment by luotao1** [comment]
It seems that MKLDNN has speedup on Mac:
- GoogleNet: 1.2x~3.3x
- ResNet-50: 2.3x~3.6x
- VGG-19:  1.3x~1.8x

**Comment by NHZlX** [comment]
Is there any speed test without `mklml` and `mklDNN`.

**Comment by luotao1** [comment]
Do you mean openblas? You can see https://github.com/PaddlePaddle/Paddle/pull/6267/files . It is tested on server.
