### ISSUE TITLE
orthogonal initialization in lstm

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/Paddle#6205]
How should orthogonal initialization be done for LSTM model? 
I have tried to setting parameters through this way, but failed. 
   
```python
 for i in range(num_lstm_layers):
         parameters.set('lstm_%d' % i, get_orthoganal_matrix(hidden_dim, hidden_dim))
```

num_lstm_layers is the number of lstm layers,
hidden_dim is the dimension of lstm layer
get_orthoganal_matrix is the function of getting orthoganal matrix

And this is the error message.

**ValueError: Value shape mismatch, expect (128, 128, 4), should (512, 512)**

How should I fix this problem??

**Comment by lcy-seso** [comment]
修改成这样试试
```
for i in range(num_lstm_layers):
         parameters.set('lstm_%d' % i, get_orthoganal_matrix(hidden_dim, hidden_dim * 4))
```

**Comment by ChunweiYan** [comment]
shape 有问题，你现在是 (128, 128, 4) ? 改成 (512, 512) 试试
numpy 的 shape

**Comment by lcy-seso** [comment]
LSTM参数说明可以看这个issue：https://github.com/PaddlePaddle/Paddle/issues/5414

**Comment by April0402** [comment]
@ChunweiYan 
我现在的shape 是(512, 512)，lstm层的参数，应该的shape是多少？
@lcy-seso 
我现在这个get_orthoganal_matrix函数返回的是hiddem_dim * hidden_dim的正交矩阵，如果按照上面说的修改，意思是说返回4个hiddem_dim * hidden_dim的正交矩阵吗？

**Comment by ChunweiYan** [comment]
reference https://github.com/PaddlePaddle/Paddle/issues/5414#issuecomment-342357950

**Comment by April0402** [comment]
@ChunweiYan paddle python中的代码是指哪里？方便说一下是文件名和函数名么？api里实在写的太简单了啊，这样用户根本就不可能自助解决问题啊

**Comment by lcy-seso** [comment]
例子：https://github.com/PaddlePaddle/models/compare/develop...lcy-seso:orthogonal_init_lstm

**Comment by April0402** [comment]
感谢，已解决

**Comment by zenghsh3** [comment]
@lcy-seso 您好，请问还能提供orthogonal init lstm的例子吗？原有的branch比较链接好像失效了，感谢！
