### ISSUE TITLE
Build failed on CI with C-API, openblas

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#6206]
The failed job: https://paddleci.ngrok.io/viewLog.html?buildId=20174&buildTypeId=Manylinux1_Cuda80cudnn5avxOpenblas&tab=buildResultsDiv

The error logs:
```bash
[13:11:46]	+ [[ ! -z OFF ]]
[13:11:46]	+ find ./third_party/install -name libmklml_gnu.so -exec cp '{}' output/usr/local/lib ';'
[13:11:46]	+ find ./third_party/install -name libmklml_intel.so -exec cp '{}' output/usr/local/lib ';'
[13:11:46]	+ cp -P './third_party/install/mkldnn/lib/*' output/usr/local/lib/
[13:11:46]	cp: cannot stat `./third_party/install/mkldnn/lib/*': No such file or directory
```

**Comment by gongweibao** [comment]
Fix it https://github.com/gongweibao/tests/blob/develop/build_capi/build_capi.sh#L29

**Comment by Yancey1989** [comment]
I think the error is caused by 
```bash
if [[ ! -z "${WITH_MKLML}" ]]; then
```

We pass the parameters `WITH_MKL=OFF`, we can fix the bug by default value:
```bash
if [[ "${WITH_MKL:-OFF}" == "ON" ]] 
```

For another, `WITH_MKLML` is older, just use `WITH_MKL`.

**Comment by gongweibao** [comment]
In CMakeList.txt:
```
111 set(WITH_MKLML ${WITH_MKL})
112 if (WITH_MKL AND AVX2_FOUND)
113     set(WITH_MKLDNN ON)
114 else()
115     message(STATUS "Do not have AVX2 intrinsics and disabled MKL-DNN")
116     set(WITH_MKLDNN OFF)
117 endif()
```

**Comment by gongweibao** [comment]
Thanks!https://github.com/gongweibao/tests/blob/develop/build_capi/build_capi.sh#L28
Do we move the content of this bash script from the private repo to the CI command lines?

**Comment by Yancey1989** [comment]
Since `WITH_MKLM` is from `WITH_MKL`, and we can specify `WITH_MKL` with `cmake -DWITH_MKL` rather than `-DWITH_MKLML` or `-DWITH_MKLDNN`

**Comment by gongweibao** [comment]
OK!
