### ISSUE TITLE
paddle剪枝工具是否支持基于pytorch的Transformer模型剪枝？

### ISSUE THREAD

**Issue by huanghmingyue** [PaddlePaddle/Paddle#62064]
### 请提出你的问题 Please ask your question

paddle剪枝工具是否支持基于pytorch的Transformer模型剪枝？

**Comment by Caozhou1995** [comment]
目前PaddlePaddle的剪枝工具并不直接支持基于PyTorch的Transformer模型的剪枝。PaddlePaddle提供了用于剪枝的API和工具，建议将模型迁移到paddle
