### ISSUE TITLE
paddle的微信无法添加 paddle的微信交流群也无法添加！！！急需加入社群提问！！

### ISSUE THREAD

**Issue by huluhulu595** [PaddlePaddle/Paddle#62077]
### 需求描述 Feature Description

现在运行（https://aistudio.baidu.com/projectdetail/7481697?forkThirdPart=1）遇到很多困难，教程上面很多步骤没有写得很详细，希望能加入微信群交流沟通。

**Comment by Ligoml** [comment]
开发者你好，你的个人项目未公开无法查看，辛苦先发一下 fork 源项目，我们确认下二维码信息

**Comment by huluhulu595** [comment]
> 开发者你好，你的个人项目未公开无法查看，辛苦先发一下 fork 源项目，我们确认下二维码信息

您好 我们没有放到github上，就单纯把“https://aistudio.baidu.com/projectdetail/7481697?forkThirdPart=1”连接中的教程放到我们服务器里面跑，然后报很多错，希望能加入群聊哏大家讨论一下

**Comment by Ligoml** [comment]
看这个 url 应该是在 aistudio 上 fork 了一个项目吧？
<img width="120" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39876205/77bb9901-ab4e-434f-bcf8-92245f07527e">
你的个人项目未公开，我访问不到，辛苦发一下源项目的链接
<img width="261" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/39876205/2d4efef7-b9c9-4d94-ab32-de4ccc862e69">

**Comment by huluhulu595** [comment]
> 看这个 url 应该是在 aistudio 上 fork 了一个项目吧？ <img alt="image" width="120" src="https://private-user-images.githubusercontent.com/39876205/307755630-77bb9901-ab4e-434f-bcf8-92245f07527e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTM2MDksIm5iZiI6MTcwODk5MzMwOSwicGF0aCI6Ii8zOTg3NjIwNS8zMDc3NTU2MzAtNzdiYjk5MDEtYWI0ZS00MzRmLWJjZjgtOTIyNDVmMDc1MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAwMjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQyZmFlZDg1NGZhZjhhY2JkNWQ5MWQ4MTRmNzg0YmUxOTdjYTdhMzIzYTEyNWVkYjA0ZmU2Nzc1YzI1MjlhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ivj9MYHJE7H6FpWCbaTHEHB_a4J-jjP1BKoC4_0rDwM"> 你的个人项目未公开，我访问不到，辛苦发一下源项目的链接 <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/39876205/307755756-2d4efef7-b9c9-4d94-ab32-de4ccc862e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTM2MDksIm5iZiI6MTcwODk5MzMwOSwicGF0aCI6Ii8zOTg3NjIwNS8zMDc3NTU3NTYtMmQ0ZWZlZjctYjljOS00ZDk0LWFiMzItZGU0Y2NjODYyZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAwMjE0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkZmFhMjFlNGNjNGYyMjMxNjI2MTQwOTkwYjYyMzI5M2VjMmI3ZTc2NWQwMTc0ZWY5OTZkNTQ2M2I0M2QyZjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CPWo2woMsva6ry6ZVwM9QasPm_5YfLPIYEn_R26AJws">
我们是复制了项目文件和项目代码放到本地服务器上面跑，然后报错
![image](https://github.com/PaddlePaddle/Paddle/assets/82817744/b8ce9409-4866-48de-bafc-9962f9531d5a)
![WechatIMG33](https://github.com/PaddlePaddle/Paddle/assets/82817744/fab6bff4-8e5a-4824-ba94-5c0035ce1d53)

**Comment by FymZj** [comment]
[Ernie_test.txt](https://github.com/PaddlePaddle/Paddle/files/14412916/Ernie_test.txt)
这是我们的运行代码，因为train.json的数据好像有点问题，我只用了20条数据进行训练，但是他报出这些错误
![image](https://github.com/PaddlePaddle/Paddle/assets/160563697/3f99e72a-f90e-4136-8004-43b5e6bee964)
运行环境是paddlepaddle2.3.2,paddlenlp2.4.2

**Comment by FymZj** [comment]
> 看这个 url 应该是在 aistudio 上 fork 了一个项目吧？ <img alt="image" width="120" src="https://private-user-images.githubusercontent.com/39876205/307755630-77bb9901-ab4e-434f-bcf8-92245f07527e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTQ5MDksIm5iZiI6MTcwODk5NDYwOSwicGF0aCI6Ii8zOTg3NjIwNS8zMDc3NTU2MzAtNzdiYjk5MDEtYWI0ZS00MzRmLWJjZjgtOTIyNDVmMDc1MjdlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU4ZTVkODUwODNhZjYxODgyMDI1NzAzZmYzOThiZjg2NzkxYzU2OTJkZjNlOWE3YTU0ZTg0NmZlYjJlZDIxMDkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.kIRJ-d6Zg4lEFNSvDLlVW8ELxxAGrAzwKUtMhAp9U9A"> 你的个人项目未公开，我访问不到，辛苦发一下源项目的链接 <img alt="image" width="261" src="https://private-user-images.githubusercontent.com/39876205/307755756-2d4efef7-b9c9-4d94-ab32-de4ccc862e69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg5OTQ5MDksIm5iZiI6MTcwODk5NDYwOSwicGF0aCI6Ii8zOTg3NjIwNS8zMDc3NTU3NTYtMmQ0ZWZlZjctYjljOS00ZDk0LWFiMzItZGU0Y2NjODYyZTY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjI3VDAwNDMyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE0ZWE3MDkxMGYxN2U4NmQ5NzU5YmVkNjQzOWM5MTYwNWU3MTgxYjBmYmJlNDVmN2RiN2Y2NGQ0OTQ0ZWI2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6AMNj2YN-WwIj_iTLzsHXoIzeTNa7JAB6p8r-vbN16w">

[Ernie_test.txt](https://github.com/PaddlePaddle/Paddle/files/14412916/Ernie_test.txt)
这是我们的运行代码，我使用的是aistudio上的数据，因为train.json的数据好像有点问题，我只用了20条数据进行训练，但是他报出这些错误
![image](https://github.com/PaddlePaddle/Paddle/assets/160563697/3f99e72a-f90e-4136-8004-43b5e6bee964)
运行环境是paddlepaddle2.3.2,paddlenlp2.4.2

**Comment by Ligoml** [comment]
对，我问的就是你 fork 的这个项目是啥，我得看看项目才知道你要进哪个群呀

**Comment by FymZj** [comment]
> 对，我问的就是你 fork 的这个项目是啥，我得看看项目才知道你要进哪个群呀
https://aistudio.baidu.com/aistudio/projectdetail/2017202这个是我们参考的项目链接，代码都是这上面的

**Comment by FymZj** [comment]
> 对，我问的就是你 fork 的这个项目是啥，我得看看项目才知道你要进哪个群呀

https://aistudio.baidu.com/aistudio/projectdetail/2017202
这是我们参考的项目链接，我们的代码都是这上面的，数据也是

**Comment by jzhang533** [comment]
cc: @michaelowenliu @wawltor

**Comment by Ligoml** [comment]
> > 对，我问的就是你 fork 的这个项目是啥，我得看看项目才知道你要进哪个群呀
> 
> https://aistudio.baidu.com/aistudio/projectdetail/2017202 这是我们参考的项目链接，我们的代码都是这上面的，数据也是

这是 PaddleNLP 的 issue，已经同步相关同学跟进处理了哈

**Comment by lugimzzz** [comment]
paddlenlp版本用2.3.4 paddle用2.3试一下

**Comment by FymZj** [comment]
> paddlenlp版本用2.3.4 paddle用2.3试一下
![1709003088442(1)](https://github.com/PaddlePaddle/Paddle/assets/160563697/6dc6dce6-d395-45e7-b16d-40c690a97cec)
![1709003104008(1)](https://github.com/PaddlePaddle/Paddle/assets/160563697/34fa2128-c624-49bb-bc56-6c0a1e7a2486)
尝试更换版本运行，依旧不行。
