### ISSUE TITLE
非法指令（核心已转储）

### ISSUE THREAD

**Issue by liuxc1** [PaddlePaddle/Paddle#62084]
![QQ图片20240226182613](https://github.com/PaddlePaddle/Paddle/assets/38060387/75759b86-5328-41aa-833a-3e3529dc8aba)
Python 3.8.18
conda 23.11.0
![QQ图片20240226182613](https://github.com/PaddlePaddle/Paddle/assets/38060387/7a1695e3-8998-4a26-9d20-71348d2e3841)
![QQ截图20240226182907](https://github.com/PaddlePaddle/Paddle/assets/38060387/03523c3d-6877-4b07-8cdd-9ecb1b72a017)

**Comment by liuxc1** [comment]
![Uploading QQ截图20240226182907.png…]()

**Comment by zxcd** [comment]
"paddlespeech_server.py" not found. Maybe you want to use "paddlespeech/server/bin/paddlespeech_server.py".
Also for "paddlespeech_server start --help", you need to make sure your spelling and paddlespeech installation correct.
