### ISSUE TITLE
[TVM] PaddleInference是否考虑在量化节点的attr上添加量化OP的data_format

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/Paddle#62106]
### 使用场景

目前TFLite模型可以通过TVM来实现将TFLite模型转换为TVM模型，然后使用CMSIS-NN后端在微控制器设备上实现部署，我希望为Paddle模型也添加类似的能力。

TVM在将模型转换为CMSIS-NN可以运行的模型时有三点要求(根据和Arm RD的沟通以及对TVM文档的阅读):

* 1 模型的OP输入数据格式为"NHWC"
* 2 模型为量化模型
* 3 模型的部分OP（如conv_2d）权重格式需要为"HWIO"，Paddle模型目前为"OIHW"

### 已完成场景

针对问题1和问题3，在模型为FP32的NHWC模型时，我已经在卷积算子上完成了测试，并且提交了一个被合入的PR：

* https://github.com/apache/tvm/pull/16616

具体方法大致为，在转换模型时，对特定OP的输入格式作判断，当输入格式为NHWC时，对常数量weight做transpose操作

### 需求场景

但是当输入模型为NHWC格式的Paddle**量化**模型时，这个解决方法就不适用了。通过netron解析PaddleInference结构，可以看到:

![image](https://github.com/PaddlePaddle/Paddle/assets/58363586/b4040297-e0cf-4bd3-977f-61869e3a3257)

conv2d算子的weight权重不再是一个常数，而是dequantize_linear算子的输出(虽然输出应该也是一个常数)，TVM无法直接对这种情况作transpose操作。那么最简单的方法就是把conv_2d算子weights的transpose操作放到解析dequantize_linear算子时来做。那么此时又会碰到一个问题，dequantize_linear算子是没有数据格式的，也就是说，可能是NHWC也可能是NCHW。在这种情况下，是没有办法判断当前的dequantize_linear算子是否要对conv2d的weights做transpose操作的。

### 需求

能够对dequantize_linear算子和quantize_linear添加data_format参数，或者有没有其他更好的实现？

**Comment by jiangjiajun** [comment]
@Zheng-Bicheng 在当前的情况下，可以在模型frontend解析阶段，做一次遍历。 例如在遇到dequantize_linear时，判断他的下一个输出是否是conv节点，如果是conv节点，则在当前dequantize_linear节点将conv节点的data format给保存过来。试下这样看能否解决。

**Comment by Zheng-Bicheng** [comment]
> @Zheng-Bicheng 在当前的情况下，可以在模型frontend解析阶段，做一次遍历。 例如在遇到dequantize_linear时，判断他的下一个输出是否是conv节点，如果是conv节点，则在当前dequantize_linear节点将conv节点的data format给保存过来。试下这样看能否解决。

我尝试一下这个方法
