### ISSUE TITLE
build.sh操作不成功

### ISSUE THREAD

**Issue by AntyRia** [PaddlePaddle/Paddle#62121]
### 问题描述 Issue Description

我在arm开发板，NPU设备，执行如下网址的2.1.1操作[https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.7/deploy/lite/README.md](url)
当执行到这一步
`# 启动编译
./lite/tools/build.sh build_optimize_tool`
出现报错：
`[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/write_back_kHost_kAny_kAny_write_back_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/write_to_array_kHost_kAny_kAny_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/write_to_array_kXPU_kAny_kAny_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kARM_kFP16_kNCHW_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kHost_kFloat_kNCHW_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kMetal_kFP16_kMetalTexture2DArray_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kMetal_kFloat_kMetalTexture2DArray_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kOpenCL_kAny_kNCHW_def_class.cc.o
[ 88%] Building CXX object lite/kernels/CMakeFiles/kernels.dir/__/__/all_kernel_faked_dir/yolo_box_kXPU_kFloat_kNCHW_def_class.cc.o
[ 89%] Linking CXX static library libkernels.a
[ 89%] Built target kernels
make[1]: *** [CMakeFiles/Makefile2:1653：lite/api/CMakeFiles/opt.dir/rule] 错误 2
make: *** [Makefile:404：opt] 错误 2
`
前面的过程没有看到报错，请问如何解决

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: debian 10
GCC version: (Debian 8.3.0-6) 8.3.0
Clang version: N/A
CMake version: version 3.10.3
Libc version: glibc 2.28
Python version: 3.8.18

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by hong19860320** [comment]
把问题迁移到 https://github.com/PaddlePaddle/Paddle-Lite/issues 吧

**Comment by AntyRia** [comment]
好的
