### ISSUE TITLE
cx_freeze

### ISSUE THREAD

**Issue by NikhilDahitule** [PaddlePaddle/Paddle#62128]
### bug描述 Describe the Bug

I have encountered the same issue during packaging with pyinstaller as well as cx_Freeze. I got the issue in paddle/base/core.py

![image](https://github.com/PaddlePaddle/Paddle/assets/91003069/2322cfdc-40c5-47b9-a764-ac322030bae2)

**Comment by NikhilDahitule** [comment]
@shiyutang  Could you take a quick look and share your insights?

**Comment by shiyutang** [comment]
It seems error occur in https://github.com/PaddlePaddle/Paddle/blob/1ca27f11f886293b7577e86f3e7a8985f396f747/python/paddle/base/core.py#L397
can you find out which line of code says this error, our code version may not be the same. You should try fix the error path from None to a string.

**Comment by NikhilDahitule** [comment]
@shiyutang As per your code version im getting error in line number 412.

![image](https://github.com/PaddlePaddle/Paddle/assets/91003069/9f0da12b-d6f4-460b-82d5-fff338709de0)

**Comment by shiyutang** [comment]
please try edit:
``` 
if hasattr(site, 'USER_SITE')
```
to
```
if hasattr(site, 'USER_SITE') and site.USER_SITE: 
```

**Comment by NikhilDahitule** [comment]
@shiyutang I'm happy to report that the problem has been successfully resolved!

Thank you for your code contribution! It was a pleasure working with you on this.

**Comment by shiyutang** [comment]
Great～

**Comment by Suvoo** [comment]
> please try edit:
> 
> ```
> if hasattr(site, 'USER_SITE')
> ```
> 
> to
> 
> ```
> if hasattr(site, 'USER_SITE') and site.USER_SITE: 
> ```

working solution Aug 24
