### ISSUE TITLE
使用npu版本的paddlepaddle在paddleocr上进行检测识别出现的问题

### ISSUE THREAD

**Issue by LegendRGC** [PaddlePaddle/Paddle#62133]
### 问题描述 Please describe your issue

安装完npu版本的paddlepaddle后，使用run_check进行测试能够顺利通过，但是在paddleocr中进行检测识别会出现一些问题。检测阶段耗费时间很长，一张图像需要五六分钟，正常在gpu上只需要几秒即可；识别阶段无法通过，会出现报错，报错结果如图所示。
![微信图片_20240227161619](https://github.com/PaddlePaddle/Paddle/assets/68408391/cbd3c8be-2709-4061-8b4f-daef19a2db0b)

**Comment by qili93** [comment]
您好，根据报错提示，是昇腾软件栈CANN的错误，请尝试在镜像的 `/root/ascend/log/debug/plog` 目录下的 plog-xxxx.log 日志中定位 错误信息，例如 `grep ERROR plog-*.log` 定位到上方截图中的错误信息

![image](https://github.com/PaddlePaddle/Paddle/assets/16605440/d1556afe-717c-437e-a56b-71f38d3b8df1)

您可以将定位到的错误信息回复到这个PR中我们这里先初步判断下可能的问题原因，也可以尝试将此错误信息反馈到华为昇腾社区 https://gitee.com/ascend/modelzoo/issues 进行进一步的咨询。

关于 “**测阶段耗费时间很长，一张图像需要五六分钟，正常在gpu上只需要几秒即可**” 这个可能是由于模型中的部分算子在NPU上没有对应的算子实现，从而部分算子是fallback到CPU上执行而导致的性能问题，可以尝试在运行之前输出 `export GLOG_v=10` 的环境变量，然后在运行相关的paddleocr的检测识别命令，在输出的debug日志中检查是否有类似 "fallbacking to CPU one" 类似的日志信息，具体可以参考这段代码 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/phi/core/kernel_factory.cc#L325

谢谢 :)
