### ISSUE TITLE
unknown command bc when benchmark inference mkldnn

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#6219]
The command `bc` was not installed in docker.

https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/paddle/image/run_mkldnn_infer.sh#L6

**Comment by luotao1** [comment]
Shell本身不具备处理浮点计算的能力，需要使用“bc”这个高精度的计算器工具，或者调用“awk”脚本来处理浮点运算。由于paddle的docker中未安装bc命令，因此改成使用awk命令。http://smilejay.com/2012/11/floating-point-with-bc-and-awk/
