### ISSUE TITLE
[Paddle Infernce]assign_value OP中的values值为空，导致模型推理出错

### ISSUE THREAD

**Issue by NeroLoh** [PaddlePaddle/Paddle#62194]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/15044135/48fe1d3c-717c-4e39-ae08-df3583c1d36c)
assign_value的attr已经是新的scalar格式，但仍然被转化
![image](https://github.com/PaddlePaddle/Paddle/assets/15044135/be264758-6f7d-4b75-a303-9d95066b118d)
导致得到的values值为空
![image](https://github.com/PaddlePaddle/Paddle/assets/15044135/244b02b4-8111-4959-9874-975dc2a3c0bf)
目前怀疑与转换的判断逻辑有关
相关MR：https://github.com/PaddlePaddle/Paddle/pull/59536/files

**Comment by GGBond8488** [comment]
@zyt1024 帮忙看看吧，提个pr修一下，在set之前先判断一下是不是"values" 已经有值，以及values 有没有被之前的fp32_values, int32_values赋值

**Comment by zyt1024** [comment]
好的，我解决一下
