### ISSUE TITLE
elapsed_time API直接返回的值是0，是否可以替代使用的方式？

### ISSUE THREAD

**Issue by nishirong** [PaddlePaddle/Paddle#62198]
### 请提出你的问题 Please ask your question

请问python/paddle/device/__init__.py文件中的elapsed_time API直接返回的值是0，请问目前有什么可以替代使用的方式吗？相关代码在https://github.com/PaddlePaddle/Paddle/blob/380c37ad6b6c4bead924f3ddd6ed75988747f643/python/paddle/device/__init__.py#L563

**Comment by HydrogenSulfate** [comment]
Same here

**Comment by 0x45f** [comment]
你好，咨询了相关同学，目前这个API没有替代的方式，后面我们会评估一下是否支持该功能~
