### ISSUE TITLE
paddle.norm 与 torch.norm 计算行为不一致

### ISSUE THREAD

**Issue by JunnYu** [PaddlePaddle/Paddle#62240]
### bug描述 Describe the Bug

这个PR的修改存在问题 https://github.com/PaddlePaddle/Paddle/pull/60070
torch在下面的例子中使用的是vector norm, 在paddle<=2.6.0 之前是一致的，但是到了develop的时候行为不一致。
torch 2.1.0
```python
import torch, paddle
torch.cuda.manual_seed(42)
a = torch.randn([2, 24, 24, 4], device='cuda:0')
# torch.norm求的是vector norm
vector_o1 = torch.norm(a, p=2, dim=(1, 2), keepdim=True)
b = paddle.to_tensor(a.cpu().numpy())
# paddle.norm求的是matrix norm
o2 = paddle.norm(b, p=2, axis=(1, 2), keepdim=True)
print(vector_o1, o2)
# tensor([[[[24.9556, 24.9024, 24.0531, 22.3612]]],


#         [[[22.2263, 22.8545, 23.2422, 24.4033]]]], device='cuda:0') 
# Tensor(shape=[2, 1, 1, 4], dtype=float32, place=Place(gpu:0), stop_gradient=True,
#        [[[[9.78923035 , 10.33647346, 9.06337070 , 8.42760468 ]]],


#         [[[9.00046349 , 9.06209278 , 8.59618092 , 9.77013969 ]]]])
```

**Comment by zhwesky2010** [comment]
@JunnYu 你好，`paddle.linalg.norm/paddle.norm`对标的是 `torch.linalg.norm`，不是`torch.norm`，`torch.linalg.norm`计算的也是矩阵范数，两者是一致的：
<img width="716" alt="infoflow 2024-03-01 15-03-28" src="https://github.com/PaddlePaddle/Paddle/assets/52485244/5e5a65fa-7b24-4b14-8383-a3d1afcd36d8">

而`torch.norm`是torch早期设计不规范的API，torch计划废弃，不建议使用，也不保证行为正确性：https://pytorch.org/docs/stable/generated/torch.norm.html#torch-norm
<img width="668" alt="infoflow 2024-03-01 15-07-20" src="https://github.com/PaddlePaddle/Paddle/assets/52485244/bb1f1bde-130a-4491-baaf-5edde2f44c9f">


这几个API之间对应关系为：（不建议使用最后一个）

`paddle.norm` == `paddle.linalg.norm` == `torch.linalg.norm` != `torch.norm`
