### ISSUE TITLE
An Question about the demo in capi example folder

### ISSUE THREAD

**Issue by ckeys** [PaddlePaddle/Paddle#6227]
Hi All,

I am just wondering if there are any parameter files, which is required by the code in the example folder.

Here I attach the code:

/* --------------------------------------------------------------------------------------

paddle_gradient_machine_load_parameter_from_disk(machine,"./some_where_to_params")

/* --------------------------------------------------------------------------------------

 I wanna to deploy the code on the Android platform. Without the parameter file, I can not get the prob output. :(

Thanks.

**Comment by Xreki** [comment]
`./some_where_to_params` is a directory which contains all the parameters. See the comments here:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/gradient_machine.h#L55
```
/**
 * @brief Load parameter from disk.
 * @param machine Gradient Machine.
 * @param path local directory path.
 * @return paddle_error
 */
PD_API paddle_error paddle_gradient_machine_load_parameter_from_disk(
    paddle_gradient_machine machine, const char* path);
```

Also, if your config is written in v2 api, you can use [merge_v2_model](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/utils/merge_model.py#L25) to merge the config and parameters into a single file, and use `paddle_gradient_machine_create_for_inference_with_parameters` to create a gradient_machine.
