### ISSUE TITLE
torch.utils.checkpoint.checkpoint替换方案

### ISSUE THREAD

**Issue by Yang-Changhui** [PaddlePaddle/Paddle#62298]
### 需求描述 Feature Description

paddlescience论文复现气象领域：Earthformer: Exploring Space-Time Transformers for
Earth System Forecasting
原pytorch中需要使用torch.utils.checkpoint.checkpoint，paddle中如何支持或者有替代方案

**Comment by zhangbo9674** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/callbacks/ModelCheckpoint_cn.html#modelcheckpoint
您好，可以看看这个API是否满足你的使用要求

**Comment by Yang-Changhui** [comment]
> https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/callbacks/ModelCheckpoint_cn.html#modelcheckpoint 您好，可以看看这个API是否满足你的使用要求

好的，谢谢。不过经过飞桨老师的指导，这个API的功能和paddle.distributed.fleet.utils.recompute功能类似，已经解决啦
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/distributed/fleet/utils/recompute_cn.html
