### ISSUE TITLE
Paddle在加载Torch生成的pickle文件时，当内容是一个Object的时候，会报错，无法载入，什么办法可以解决吗？

### ISSUE THREAD

**Issue by GloriaYY** [PaddlePaddle/Paddle#62322]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/18144987/9e03d936-ef24-48e0-b908-b5aad466f49b)

**Comment by FeixLiu** [comment]
看图中的报错是没安装torch？

**Comment by Ligoml** [comment]
你好，aistudio 是飞桨的实训社区，仅支持paddle框架
