### ISSUE TITLE
Latex syntax in the description of lstm op does not render correctly

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#6236]
<img width="557" alt="screen shot 2017-12-05 at 1 28 38 am" src="https://user-images.githubusercontent.com/549367/33573495-edcbd5b6-d95b-11e7-92f0-21219a2606a2.png">

**Comment by qingqing01** [comment]
I have fixed it in PR https://github.com/PaddlePaddle/Paddle/pull/6148 .

**Comment by abhinavarora** [comment]
Yes I confirm it is fixed. Sorry I was not checking the latest documentation earlier.
