### ISSUE TITLE
使用cpu流式输入预测，dropout为is_test且无bn，预测结果会有一定随机性，每次不一致，且和gpu原始预测代码结果不同。

### ISSUE THREAD

**Issue by Rayarrow94** [PaddlePaddle/Paddle#62378]
### 请提出你的问题 Please ask your question

基于erniedoc进行finetune。预测时：
pp = model_predict.ModelPredict()
pp.init(ernie_config_path)
...
reader = task_reader.ClassifyReader()
data = reader._convert_to_instance((arr[1], arr[1]))
data_input = reader._pad_batch_records(data)
user_vec_list, ad_vec_list = pp.predict([data_input]) 得到向量。

模型加载和预测部分：
paddle.enable_static()
model_dir='./xxx'

class ModelPredict(object):
    def __init__(self):
        pass

    def init(self, ernie_config_path):
        """int function"""
        self.ernie_config = ErnieConfig(ernie_config_path)
        self.place = fluid.CPUPlace()
        self.startup_prog = fluid.Program()
        self.test_prog = fluid.Program()
        self.memory_len = 128 
        with fluid.program_guard(self.test_prog, self.startup_prog):
            with fluid.unique_name.guard():
                data_list, fc_src3, fc_trg3 = create_model(ernie_config=self.ernie_config)
            test_prog = self.test_prog.clone(for_test=True)
        self.exe = fluid.Executor(self.place)
        self.exe.run(self.startup_prog)
        def existed_persitables(var):
            if not fluid.io.is_persistable(var):
                return False
            return os.path.exists(os.path.join(model_dir, var.name))
        fluid.io.load_vars(self.exe,model_dir,main_program=self.startup_prog, predicate=existed_persitables)
        self.fetch_targets = [fc_src3, fc_trg3]
        self.feeder = fluid.DataFeeder(feed_list=data_list, place=self.place)

    def predict(self, feed_data):
        feed_dict = self.feeder.feed(feed_data)
        fc_src3, fc_trg3 = self.exe.run(self.test_prog,feed=feed_dict,fetch_list=self.fetch_targets)
        return fc_src3, fc_trg3

网络：
def create_model(ernie_config):
    src_ids = fluid.layers.data(name='src_ids', shape=[128, 1], dtype='int64', append_batch_size=True)
    trg_ids = fluid.layers.data(name='trg_ids', shape=[128, 1], dtype='int64', append_batch_size=True)
    src_pos_ids = fluid.layers.data(name='src_pos_ids', shape=[2 * 128 + 128, 1], dtype='int64', append_batch_size=True)
    trg_pos_ids = fluid.layers.data(name='trg_pos_ids', shape=[2 * 128 + 128, 1], dtype='int64', append_batch_size=True)
    src_task_ids = fluid.layers.data(name='src_task_ids', shape=[128, 1], dtype='int64', append_batch_size=True)
    trg_task_ids = fluid.layers.data(name='trg_task_ids', shape=[128, 1], dtype='int64', append_batch_size=True)
    src_input_mask = fluid.layers.data(name='src_input_mask', shape=[128, 1], dtype='float32', append_batch_size=True)
    trg_input_mask = fluid.layers.data(name='trg_input_mask', shape=[128, 1], dtype='float32', append_batch_size=True)

    data_list = [src_ids, trg_ids, src_pos_ids, trg_pos_ids, src_task_ids, trg_task_ids, src_input_mask, trg_input_mask]

    ernie_doc_src = ErnieDocModel(
        src_ids=src_ids,
        position_ids=src_pos_ids,
        task_ids=src_task_ids,
        input_mask=src_input_mask,
        config=ernie_config,
        number_instance=1,
        rel_pos_params_sharing=rel_pos_params_sharing,
        use_vars=use_vars)
    ernie_doc_trg = ErnieDocModel(
        src_ids=trg_ids,
        position_ids=trg_pos_ids,
        task_ids=trg_task_ids,
        input_mask=trg_input_mask,
        config=ernie_config,
        number_instance=1,
        rel_pos_params_sharing=rel_pos_params_sharing,
        use_vars=use_vars)

    cls_feats_src = ernie_doc_src.get_pooled_output()
    cls_feats_trg = ernie_doc_trg.get_pooled_output()

    fc_src2 = fluid.layers.fc(input = cls_feats_src, size = 256, act = 'tanh')
    fc_trg2 = fluid.layers.fc(input = cls_feats_trg, size = 256, act = 'tanh')
    fc_src3 = fluid.layers.fc(input = fc_src2, size = 128, act = 'tanh')
    fc_trg3 = fluid.layers.fc(input = fc_trg2, size = 128, act = 'tanh')
    return data_list, fc_src3, fc_trg3

**Comment by GuoxiaWang** [comment]
属于 ernie-doc 问题，

用户查到 memory 有变化，可以通过  mem_len=0 来避免
<img width="782" alt="8b2b10f5e8e3770dae05fe534df8b922" src="https://github.com/PaddlePaddle/Paddle/assets/16953187/c1b056e9-44fb-4725-b008-6df014ff2afb">
