### ISSUE TITLE
Equation for conv3d_transpose op is not in latex equation format

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#6237]

**Comment by abhinavarora** [comment]
<img width="566" alt="screen shot 2017-12-05 at 1 36 53 am" src="https://user-images.githubusercontent.com/549367/33573790-f085d3aa-d95c-11e7-8781-9a6b2aa72305.png">

**Comment by chengduoZH** [comment]
Equation for [conv_transpose](https://github.com/PaddlePaddle/Paddle/blob/1b6804fb8df986b2e207b19d9f90ede583a6b398/paddle/operators/conv_op.cc#L127) are in latex equation format, but the website does not update.

**Comment by abhinavarora** [comment]
This issue is resolved in the latest code. It seems the documentation was not updated at the time the issue was created.
