### ISSUE TITLE
嘿，我在运行paddle官网的例子出现了这个情况无法解决，不知道是哪里有问题了

### ISSUE THREAD

**Issue by ewwll** [PaddlePaddle/Paddle#62380]
### 问题描述 Please describe your issue

Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 534: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!

**Comment by GuoxiaWang** [comment]
请问你运行的是什么例子？paddle版本是什么？

**Comment by ewwll** [comment]
重启了一下Linux然后就没有这个问题了，应该不是paddle的问题，而是我自己的机器有什么问题了，还是非常感谢。
