### ISSUE TITLE
Custom Device是否能够支持BFloat16

### ISSUE THREAD

**Issue by Rruown** [PaddlePaddle/Paddle#62397]
### 请提出你的问题 Please ask your question

目前paddle develop分支custom device不支持开启bfloat16，请问原因是什么？custom device对bfloat16的支持程度如何？
我尝试修改了amp逻辑，允许python层对custom device的bfloat16支持，从结果上来看kernel key能够正常选取到bfloat16的kernel。
![image](https://github.com/PaddlePaddle/Paddle/assets/34084211/e1b29217-64cf-4507-b3f3-cdc898f5994e)

**Comment by YuanRisheng** [comment]
因为打开后有bug，可参考这个PR：https://github.com/PaddlePaddle/Paddle/pull/55364

**Comment by Rruown** [comment]
请问具体的bug是什么？我看这个pr55364和相关的pr10119没有提及到开启amp选择BFloat16类型会存在什么错误。我想知道框架层有哪里不支持嘛？

**Comment by Ligoml** [comment]
@tianhaodongbd 辛苦解答下

**Comment by tianhaodongbd** [comment]
custom device开启amp选择bf16目前来看是没有bug的，可能会存在kernel未注册bf16的情况。近期将在框架层支持custom device使用bf16进行混合精度训练。

**Comment by Rruown** [comment]
> custom device开启amp选择bf16目前来看是没有bug的，可能会存在kernel未注册bf16的情况。近期将在框架层支持custom device使用bf16进行混合精度训练。

谢谢
