### ISSUE TITLE
Packaging documents into Docker images and auto deploy to paddlepaddle.org

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#625]
It is reasonable to serve documents, especially API documents, of each version of Paddle, like what's been doing with Tensorflow:

<img width="424" alt="screen shot 2016-11-25 at 5 26 09 pm" src="https://cloud.githubusercontent.com/assets/1548775/20637224/23d98c5a-b335-11e6-85bb-707b82a04c31.png">

My rough idea about the auto packaging and auto deployment of documents is as follows:

1. When we build documents, we generate a Docker image containing the document and an HTTP server, e.g., Nginx.
1. We publish this image to Dockerhub.com as other images.
1. On paddlepaddle.org, we run a Nginx instance and Docker containers of document images of all Paddle versions, and make this Nginx instance http_proxy to all these Docker containers.

**Comment by wangkuiyi** [comment]
A possibly better solution might be that there is only one document Docker image, which doesn't contain the document built from .rst source, but builts the .rst source of a given Git tag/branch at Docker container startup time. This way, we can have one document container running and serving documents in the `develop` branch.

**Comment by wangkuiyi** [comment]
OK. I noticed that the most convenient way to doing this might be to build documents into Docker images, and support to build Docker images from any Git commit.

**Comment by reyoung** [comment]
The current paddlepaddle.org is automatically built and pushed by Travis-CI, but only for the master branch. Because the documentation should be stable by each release.
