### ISSUE TITLE
cinn 编译失败

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#62546]
### bug描述 Describe the Bug

按照这个[教程](https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/cinn) ，ai studio 与 paddle:2.6.0-gpu-cuda11.7-cudnn8.4-trt8.4 环境中， cinn with paddle 和 cinn only 都不能正常编译，报同一个错误。
![{3BFN8@}CRWZCP1VB0496QB](https://github.com/PaddlePaddle/Paddle/assets/118546135/9ba6c2bb-3459-4908-aac5-70cb66c9da61)

复现步骤：
``` bash
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
mkdir build
cd build
cmake .. -DCINN_ONLY=OFF -DWITH_CINN=ON -DWITH_GPU=ON
make -j8
```

**Comment by zhangting2020** [comment]
可能是网络问题，导致第三库没有clone下来。你可以检查下对应的第三方库下面有没有内容

**Comment by WintersMontagne10335** [comment]
> 可能是网络问题，导致第三库没有clone下来。你可以检查下对应的第三方库下面有没有内容

没内容，我根据它 cmake 时的信息，手动 clone 到对应的 third_party 目录下，然后重新 cmake make，然后还是这个问题。婷姐，这里由比较好的解决办法嘛。

**Comment by zhangting2020** [comment]
之前有同学遇到这个报错，大概是网络问题，重新编译又好了。

你再试试把Paddle/third_party/warpctc   Paddle/third_party/warprnnt删了，重新cmake & make

**Comment by WintersMontagne10335** [comment]
可以了，谢谢婷姐~~
还有一个小坑，会报 .h 文件与 .c 文件函数参数列表不一致，这里保证CUDA_VERSION>11000（即 nvcc --version中显示的值 > 11.0 即可）。杰哥有提醒过。
