### ISSUE TITLE
“快速入门”不“快速”

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#626]
当前的quick_start
 [quick_start](http://www.paddlepaddle.org/doc_cn/demo/quick_start/index.html)
![](http://www.paddlepaddle.org/doc_cn/_images/Pipeline.jpg)
当用户已经理解这五个部分时，那么这是一篇非常好的快速入门示例（在忽略500M数据的前提下）。对于那些想学，却不理解深度学习任务流的用户学习起来就会很困难。

@zhouxiao-coder 贡献了[introduction](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/introduction)
相对quick_start要清晰简单许多。从学习“深度学习”的角度，仍有些“信息”会干扰.。我试图进行精简并向@luotao1 求助，但结果似乎是系统设定，没有更好的精简方案。具体干扰我列举如下:

### 训练过程中会生成一些文件
- **dataprovider.pyc** introduction里只需要的数据只是一个二维向量，可不可以用数组代替？
- **empty.list** 文件列表? 好像用不到，还是生成了一个空文件.
- **output/** 每次训练的结果，每个文件夹下都有许多文件,如果没办法在这章节里解读,是否可以选择一个不生成文件夹的方法?

### 用到的方法
- PyDataProvider2 我理解这是一个非常好用的工具.是否可以在后续章节单独展开讲解他的场景和使用方法?而在introduction里出现,会让理解变得更复杂.
- define_py_data_sources2 同上

### 日志
每次训练过程中,真正有价值的数据只是 `Pass=1 Batch=167 samples=2000 AvgCost=0.439972`
但是却要在理解了下面大量日志之后，才能明白。
`...................................................................................................
I1126 03:31:46.700059    65 TrainerInternal.cpp:165]  Batch=100 samples=1200 AvgCost=0.456569 CurrentCost=0.456569 Eval:  CurrentEval: 
...................................................................I1126 03:31:46.705346    65 TrainerInternal.cpp:182]  Pass=0 Batch=167 samples=2000 AvgCost=0.446531 Eval: 
I1126 03:31:46.705713    65 GradientMachine.cpp:112] Saving parameters to ./output/pass-00000
I1126 03:31:46.706161    65 Util.cpp:230] copy trainer_config.py to ./output/pass-00000
...................................................................................................
I1126 03:31:46.722744    65 TrainerInternal.cpp:165]  Batch=100 samples=1200 AvgCost=0.436188 CurrentCost=0.436188 Eval:  CurrentEval: 
...................................................................I1126 03:31:46.731585    65 TrainerInternal.cpp:182]  Pass=1 Batch=167 samples=2000 AvgCost=0.439972 Eval: 
I1126 03:31:46.731825    65 GradientMachine.cpp:112] Saving parameters to ./output/pass-00001
I1126 03:31:46.732254    65 Util.cpp:230] copy trainer_config.py to ./output/pass-00001
...................................................................................................
I1126 03:31:46.746304    65 TrainerInternal.cpp:165]  Batch=100 samples=1200 AvgCost=0.430935 CurrentCost=0.430935 Eval:  CurrentEval: 
...................................................................I1126 03:31:46.752221    65 TrainerInternal.cpp:182]  Pass=2 Batch=167 samples=2000 AvgCost=0.426152 Eval: 
I1126 03:31:46.752640    65 GradientMachine.cpp:112] Saving parameters to ./output/pass-00002
I1126 03:31:46.753191    65 Util.cpp:230] copy trainer_config.py to ./output/pass-00002
`

引用一个类似主题，相对清晰的例子, [TensorFlow-Examples-linear_regression ](https://github.com/aymericdamien/TensorFlow-Examples/blob/master/notebooks/2_BasicModels/linear_regression.ipynb)
当然这个例子也有缺陷,对一些方法的讲解并不到位.但是在其他方面都很不错.

### 教程适合任何零基础的人，但是手册不是所有人都能看懂的。
这里引申出我的另一个未解的困惑，也希望能跟大家一起讨论
> paddlepaddle的doc应该是教程？还是手册？

![50d965bb-d033-4c20-a2a5-5fc285ecea4f](https://cloud.githubusercontent.com/assets/1908992/20637791/31662246-b3cd-11e6-895c-f182025d4750.JPG)

**Comment by luotao1** [comment]
赞同@llxxxll 关于“训练过程中会生成一些文件，用到的方法，日志”这三方面提出的建议。
> paddlepaddle的doc应该是教程？还是手册？

doc应该分成教程和手册两部分。Introduction这部分属于教程。

**Comment by JustinhoCHN** [comment]
点击这个introduction链接页面已经找不到了，能再发一次吗？

**Comment by luotao1** [comment]
@JustinhoCHN 请访问[basic_usage](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/getstarted/basic_usage/index_cn.rst)
