### ISSUE TITLE
paddle2.6 paddle.save在开启私有格式的场景下出错

### ISSUE THREAD

**Issue by blacksheep-Aristotle** [PaddlePaddle/Paddle#62639]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/82134450/94ad61ea-50c6-4988-bbce-6b9253387394)
在tensor转numpy这里先做了一次copy to cpu，导致不会走到custom_device分支触发storage_properties的处理。
![image](https://github.com/PaddlePaddle/Paddle/assets/82134450/730850aa-5e3f-49b2-8b68-6a3600f2fe46)
![image](https://github.com/PaddlePaddle/Paddle/assets/82134450/138f018f-0ca2-44d9-a098-bf98b805d703)

**Comment by wanghuancoder** [comment]
请 @YuanRisheng 帮忙看一下这个问题~

**Comment by YuanRisheng** [comment]
请问一下这里说的『不会走到custom_device分支触发storage_properties的处理』具体是哪块儿代码没走到呢，另外这个custom_device是指的哪类设备，npu还是xpu，还是其他的？

**Comment by blacksheep-Aristotle** [comment]
其他的，理论上npu也会触发。关于私有格式storage_properties的内容，是在我们芯片上会在训练过成中将某些权重的layout转置，注意是只转置layout而shape不变。带有storage_properties的tensor可能shape是NCHW，但是实际的layout是NHWC。所以需要在保存权重的时候需要处理带有私有格式的tensor，将layout转回和shape对应。
原来是tensor通过numpy方法直接被拷贝，在拷贝中走npuidentity，现在tensor直接d2h拷贝过去，没有走npuidentity，就会出错

**Comment by wanghuancoder** [comment]
请看一下，https://github.com/PaddlePaddle/Paddle/pull/62532 后是否还存在这个问题。

**Comment by wanghuancoder** [comment]
这个问题可能是早期的NPU不支持stride导致的。近期在做支持。如果还有问题，请提新的issue提问。因为老的issue可能大家关注不到，不能及时处理。感谢
