### ISSUE TITLE
[PIR] Adaptation of `test_zero_dim_*.py` - step: 2

### ISSUE THREAD

**Issue by gouzil** [PaddlePaddle/Paddle#62652]
UPDATE 20240311: 为了方便单测执行，`test/legacy_test/test_zero_dim_tensor.py`文件**已拆分为前缀名是`test_zero_dim_*`的多个文件**，其他没有变化

------

UPDATE 20240219: `test/legacy_test/test_zero_dim_tensor.py`文件中, 大部分单测由 #61575, #61577, #61582 覆盖，本issue记录的单测需要单独适配

------

### 一、BackGround 📚

随着近期 PIR 底层 IR 的开发，为了能够同时跑两种 IR 模式，在 `python/paddle/pir_utils.py` 添加了相关的装饰器，用于追加运行 PIR 模式。
为了确保 PIR 的准确性，我们需要尽快将新机制推全～

更多任务背景、任务修改内容、提交样例可参考前期已发布过的任务：https://github.com/PaddlePaddle/Paddle/issues/61413

### 二、Task 📚

* 文件 `test/legacy_test/test_zero_dim_binary_api.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅1| TestBinaryAPI.test_static_binary | `AttributeError: 'paddle.base.libpaddle.pir.Program' object has no attribute 'current_block'` | @gouzil | #62709 |

* 文件`test/legacy_test/test_zero_dim_sundry_static_api_part1.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅2| TestSundryAPIStatic.test_create_parameter_var | `create_parameter` 已适配，`create_global_var` 不适配，未来如果框架内遇到可以考虑是否能直接换成 `paddle.full` | @SigureMo | #63253 |
|✅3| TestSundryAPIStatic.test_getitem | 段错误 | @gouzil | #62958 |
|~~✅4~~| ~TestSundryAPIStatic.test_setitem~ | 将被删除 |  @gouzil |  |
|✅5| TestSundryAPIStatic.test_tensordot | 段错误 | @gouzil | #62958 |

* 文件`test/legacy_test/test_zero_dim_sundry_static_api_part3.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅6| TestSundryAPIStatic.test_t | ~~`AttributeError: 'paddle.base.libpaddle.pir.Value' object has no attribute 'grad_name'` 反向 API 返回的是输入，等后续研发确认~~ 可以简化一下单测 |  | #62837 |
|~~✅7~~| ~~TestSundryAPIStatic.test_sequence_pad~~ | ~~`TypeError: Cannot interpret '<VarType.INT64: 3>' as a data type`~~ 静态图专用 API，已确认废弃 |  |  |
|✅8| TestSundryAPIStatic.test_static_data | `Exception: Found fetch_target[0] is type(str) and doesn't have fetch op.` | @gouzil | #62879 |
|~~✅9~~| ~~TestSundryAPIStatic.test_static_nn_prelu~~ | ~~`TypeError: Cannot interpret '<DataType.FLOAT32: 10>' as a data type`~~ 静态图专用 API，已确认废弃 |  |  |

* 文件`test/legacy_test/test_zero_dim_sundry_static_api_part4.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅10| TestSundryAPIStatic.test_dist | 段错误 | @gouzil | #62958 |
|✅11| TestSundryAPIStatic.test_linalg_norm | 段错误 | @gouzil | #62958 |
|✅12| TestSundryAPIStatic.test_trace | 段错误 | @gouzil | #62958 |

* 文件`test/legacy_test/test_zero_dim_no_backward_api.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅13| TestNoBackwardAPIStatic.test_normal | `TypeError: float(Value) is not supported in static graph mode. If you are using @to_static, you can try this:` | @gouzil | #62864 |
|✅14| TestNoBackwardAPIStatic.test_rand | `TypeError: (InvalidType) full(): argument (position 2) must be double, but got Variable` | @gouzil | #62808 |
|✅15| TestNoBackwardAPIStatic.test_randn | `TypeError: too many positional arguments` | @gouzil | #62808 |
|✅16| TestNoBackwardAPIStatic.test_standard_normal | `TypeError: too many positional arguments` | @gouzil | #62808 |
|✅17| TestNoBackwardAPIStatic.test_uniform | `TypeError: (InvalidType) full(): argument (position 2) must be double, but got Variable` | @gouzil | #62808 |
|✅18| TestNoBackwardAPIStatic.test_empty_and_empty_like | `TypeError: too many positional arguments` | @gouzil | #62808 |
|✅19| TestNoBackwardAPIStatic.test_full_and_full_like | `TypeError: (InvalidType) full(): argument (position 2) must be double, but got Variable` | @gouzil | #62808 |
|✅20| TestNoBackwardAPIStatic.test_ones_and_ones_like | `TypeError: (InvalidType) full(): argument (position 2) must be double, but got Variable` | @gouzil | #62808 |
|✅21| TestNoBackwardAPIStatic.test_zeros_and_zeros_like | `TypeError: (InvalidType) full(): argument (position 2) must be double, but got Variable` | @gouzil | #62808 |
|✅22| TestNoBackwardAPIStatic.test_embedding | `TypeError: Cannot interpret '<VarType.FP32: 5>' as a data type` | @gouzil | #62681 |
|~~✅23~~| ~~TestNoBackwardAPIStatic.test_static_embedding~~ | 计划动静统一废弃此API，不适配 | @gouzil |  |
|✅ 24| TestNoBackwardAPIStatic.test_unique_consecutive | `TypeError: bool(Value) is not supported in static graph mode. If you are using @to_static, you can try this` | @gouzil | #62794 |
|✅ 25| TestNoBackwardAPIStatic.test_unique | `TypeError: bool(Value) is not supported in static graph mode. If you are using @to_static, you can try this` | @gouzil | #62794 |
|✅26| TestNoBackwardAPIStatic.test_slice | 遗漏装饰器 | @gouzil | #62653 |
|✅27| TestNoBackwardAPIStatic.test_linspace | 遗漏装饰器 | @gouzil  | #62653 |

* 文件`test/legacy_test/test_zero_dim_reduce_api.py`

| 序号 | 单测名称| 问题 | 贡献者 | PR链接 |
|:----|:----|:----|:----:|:----:|
|✅28| TestReduceAPI.test_static_reduce |  mac 流水线上会高频 hang 住 | @gouzil | #63185 |

### 任务统计

| 任务数量 | 🔵 可认领 | 🚧 修复中 | 🟢 待合入 | ✅ 完成 | 🟡 下阶段推进 | 🏁完成率  |
| ---- | ----- | ----- | ----- | ---- | ------- | ----- |
| 28   | 0     | 0     | 0     | 27   | 0       | 100.0% |

**Comment by ooooo-create** [comment]
认领 6

**Comment by gouzil** [comment]
> 认领 6

可以换一题，这个反向有问题，已经找反向的研发看了

**Comment by ooooo-create** [comment]
> > 认领 6
> 
> 可以换一题，这个反向有问题，已经找研发大哥看了

好的，认领 2

**Comment by SigureMo** [comment]
`TestSundryAPIStatic.test_create_parameter_var` 的 `paddle.static.create_global_var` 已经确定不适配 PIR，本任务结项～
