### ISSUE TITLE
LSTM多维度回归梯度爆炸

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/Paddle#6269]
最近使用栈式LSTM模型做多维度的回归预测（输入、输出维度在30维左右，可以理解为对30条KPI曲线同时做回归预测）。下面是我的模型配置，网络深度是5层、time step是16。训练时大概在100个epoch开始出现梯度截断（error clipping 目前只设置在了mixed layer全连接层），然后梯度截断越来越多直到无法训练（一直在做截断）。

许多防止梯度爆炸的手段也都有使用（比如输入使用z-score做归一化，设置gradient clipping，error clipping，调小学习率等等），一直无法起到明显作用。

同样的网络配置对于1维的输入输出表现非常正常，加大维度后就出现梯度爆炸的问题。请问是paddle的LSTM不支持多维度的输出还是其他的什么问题？

**Comment by QiJune** [comment]
@lcy-seso Could you please give some advice?

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如果需继续讨论再打开
