### ISSUE TITLE
Paddle.profiler模型推理，得不到GPU统计信息

### ISSUE THREAD

**Issue by hf201429** [PaddlePaddle/Paddle#62705]
### bug描述 Describe the Bug

我在使用Paddle.profiler，分析自己模型推理的快慢的时候，始终拿不到GPU统计信息和算子信息。使用的VLLM，自己模型在3090上 进行推理服务。

**Comment by hf201429** [comment]
![Uploading 监控信息.jpeg…]()

**Comment by will-jl944** [comment]
是否方便提供下使用的代码？

**Comment by hf201429** [comment]
print("\n\n-----------------create profile---------------\n\n")
prof = profiler.Profiler(targets=[profiler.ProfilerTarget.CPU, profiler.ProfilerTarget.GPU,profiler.ProfilerTarget.CUSTOM_DEVICE],
                  scheduler = None,
                 on_trace_ready = profiler.export_chrome_tracing('./profiler_log'),
                timer_only = False)

prof.start()
print("\n\n-----------------run and profile---------------\n\n")
outputs = llm.generate(sampling_params=sampling_params, prompt_token_ids=prompts)
prof.stop()

# outputs = llm.generate(prompts, sampling_params)
prof.summary(sorted_by=SortedKeys.GPUMax,
             op_detail=True,
             thread_sep=False,
             time_unit='ms',
             views=[SummaryView.ModelView, SummaryView.OperatorView , SummaryView.MemoryManipulationView])

**Comment by hf201429** [comment]
黑体字那行是注释的

**Comment by hf201429** [comment]
print("\n\n-----------------create profile---------------\n\n")
prof = profiler.Profiler(targets=[profiler.ProfilerTarget.CPU, profiler.ProfilerTarget.GPU,profiler.ProfilerTarget.CUSTOM_DEVICE],
scheduler = None,
on_trace_ready = profiler.export_chrome_tracing('./profiler_log'),
timer_only = False)

prof.start()
print("\n\n-----------------run and profile---------------\n\n")
outputs = llm.generate(sampling_params=sampling_params, prompt_token_ids=prompts)
prof.stop()

prof.summary(sorted_by=SortedKeys.GPUMax,
op_detail=True,
thread_sep=False,
time_unit='ms',
views=[SummaryView.ModelView, SummaryView.OperatorView , SummaryView.MemoryManipulationView])

**Comment by hf201429** [comment]
> 是否方便提供下使用的代码？

print("\n\n-----------------create profile---------------\n\n")
prof = profiler.Profiler(targets=[profiler.ProfilerTarget.CPU, profiler.ProfilerTarget.GPU,profiler.ProfilerTarget.CUSTOM_DEVICE],
scheduler = None,
on_trace_ready = profiler.export_chrome_tracing('./profiler_log'),
timer_only = False)

prof.start()
print("\n\n-----------------run and profile---------------\n\n")
outputs = llm.generate(sampling_params=sampling_params, prompt_token_ids=prompts)
prof.stop()

prof.summary(sorted_by=SortedKeys.GPUMax,
op_detail=True,
thread_sep=False,
time_unit='ms',
views=[SummaryView.ModelView, SummaryView.OperatorView , SummaryView.MemoryManipulationView])

**Comment by hf201429** [comment]
统计不到信息，SummaryView.ModelView，SummaryView.OperatorView，只有GPU的耗时。

**Comment by will-jl944** [comment]
代码是没问题的。



> 始终拿不到GPU统计信息和算子信息

具体指的是什么信息？是否可以粘贴下执行上述代码后输出的信息，以及生成的`.paddle_trace.json`文件使用chrome tracing打开后展示的信息？

**Comment by hf201429** [comment]
我上传不了图片，.paddle_trace.json 是15G，用chrome打不开。
执行模型后最后输出只有，这三个summary：
-------------------Device Summary-------------------
------------------------------  --------------------  
Device                          Utilization (%)       
------------------------------  --------------------  
CPU(Process)                    100.44                
CPU(System)                     4.43                  
GPU0                            24.09                 
------------------------------  -------------------- 

---------------------------------------------Overview Summary---------------------------------------------
Time unit: ms
-------------------------  -------------------------  -------------------------  -------------------------  
Event Type                 Calls                      CPU Time                   Ratio (%)                  
-------------------------  -------------------------  -------------------------  -------------------------  
ProfileStep                1                          12337.31                   100.00                     
  CudaRuntime              3497422                    4780.56                    38.75                      
-------------------------  -------------------------  -------------------------  -------------------------  
                           Calls                      GPU Time                   Ratio (%)                  
-------------------------  -------------------------  -------------------------  -------------------------  
  Memcpy                   1134                       4.72                       0.04                       
  Kernel                   255262                     2972.37                    24.09                      
  Memset                   2                          0.01                       0.00                       
-------------------------  -------------------------  -------------------------  -------------------------


---------------------------------------------------------------Kernel Summary---------------------------------------------------------------
Time unit: ms
------------------------------------------------------------------------------------------  ------  ----------------------------------------  
Name                                                                                        Calls   GPU Total / Avg / Max / Min / Ratio(%)    
------------------------------------------------------------------------------------------  ------  ----------------------------------------  
void at::native::unrolled_elementwise_kernel<at::native::CUDAFunctor_add<float>, at::de...  27391   294.51 / 0.01 / 0.01 / 0.01 / 9.91        
void at::native::unrolled_elementwise_kernel<at::native::direct_copy_kernel_cuda(at::Te...  28082   273.54 / 0.01 / 0.11 / 0.01 / 9.20

**Comment by hf201429** [comment]
trace能制定层级吗？

**Comment by hf201429** [comment]
trace能指定层级吗？

**Comment by will-jl944** [comment]
> at::native::unrolled_elementwise_kernel

这是pytorch实现的模型吗？

**Comment by hf201429** [comment]
是的，Paddle.profiler有什么限制？和环境要求？

**Comment by will-jl944** [comment]
建议使用pytorch的profiler进行分析。

对于pytorch的模型，使用paddle的profiler只能获取到到cuda kernel层面的信息，这是正常现象。

**Comment by yang-cchen** [comment]
P800，paddlepaddle-xpu，使用paddle的profiler进行分析模型训练，为什么只有CPU的信息，GPU的全是0，选择XPU又不支持，是框架版本问题吗？ @will-jl944
