### ISSUE TITLE
sym_shape_str 现在是否支持 multi-output op

### ISSUE THREAD

**Issue by WintersMontagne10335** [PaddlePaddle/Paddle#62714]
### 请提出你的问题 Please ask your question

为完成护航计划的子图修复任务，需要给 split 添加 InferSymbolicShape。有了解到如下注释：
```
        # TODO(fty1777): Add builtin.split op infer symbolic shape test
        #                Not added because attribute `sym_shape_str` does not support multi-output op now.
        #                See also: paddle/fluid/pir/transforms/shape_optimization_pass.cc:144.
```
请问这个问题解决了嘛。

注释链接：
- https://github.com/PaddlePaddle/Paddle/blob/develop/test/ir/pir/cinn/symbolic/test_op_infer_sym_shape.py#L717

**Comment by 2742195759** [comment]
可以编译一下最新的develop分支，复测一下。这个功能应该已经合入了。
