### ISSUE TITLE
频繁打印 Get BackendSet from tensor，环境MacBook Apple M1 Pro

### ISSUE THREAD

**Issue by luozeyu1015** [PaddlePaddle/Paddle#62874]
### bug描述 Describe the Bug

WARNING: Logging before InitGoogleLogging() is written to STDERR
I0320 12:37:26.494565 78087552 kernel_dispatch.h:102] Get BackendSet from tensor

### 其他补充信息 Additional Supplementary Information

import os
os.environ['GLOG_minloglevel'] = '9'
os.environ['GLOG_v'] = '0'
加入这些参数都不管用

**Comment by luozeyu1015** [comment]
解决了
![Uploading 20240320124850.jpg…]()

**Comment by GuoDapeng** [comment]
#61837 这里有解决办法，这个问题的图貌似挂了。
