### ISSUE TITLE
paddlepaddle在k8s上分布式训练，是否支持master按需分发训练数据

### ISSUE THREAD

**Issue by flyhighzy** [PaddlePaddle/Paddle#6288]
请问目前是否支持由master将切分好的数据按存在的trainer进程数量分发？
如果可以，是需要自己部署一套paddle-cloud吗？
谢谢！

**Comment by typhoonzero** [comment]
1. master会通过etcd监听存活的trainer进程，trainer进程总数变化时也可以训练。
1. paddle分布式训练并不强依赖于paddle cloud，可以用一组yaml启动任务，参考：https://github.com/PaddlePaddle/cloud/tree/develop/k8s/controller/autoscale_job

**Comment by flyhighzy** [comment]
感谢答复~ 请问如何切分训练数据呢？是否有相关文档或者示例代码

**Comment by typhoonzero** [comment]
您好，可以参考：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/dataset/common.py#L194 使用这个函数把数据集拆分成多个recordio格式的文件。文档位置在：http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/data/dataset.html

**Comment by flyhighzy** [comment]
谢谢啦~demo跑成功了~
