### ISSUE TITLE
图像分类里没有alexnet和googlenet的网络结构

### ISSUE THREAD

**Issue by psever** [PaddlePaddle/Paddle#6289]
大神们好，我在[models/图像分类](http://paddlepaddle.org/docs/develop/models/image_classification/README.html)这个网址下看到了用alexnet进行图像分类，但是在[paddlepaddle/books](https://github.com/PaddlePaddle/book/tree/develop/03.image_classification)里没有看到alexnet和googlenet

**Comment by QiJune** [comment]
models和book的模型是通用的，在models下面alexnet 和googlenet都有的

**Comment by qingqing01** [comment]
@psever 请参考 https://github.com/PaddlePaddle/models/tree/develop/image_classification
