### ISSUE TITLE
【Hackathon 6th Code Camp】飞桨护航计划集训营（第二批）

### ISSUE THREAD

**Issue by sunzhongkai588** [PaddlePaddle/Paddle#62906]
大家好，非常高兴地告诉大家，第六期 PaddlePaddle Hackathon 正式开始。本次活动是面向全球开发者的深度学习领域编程活动，鼓励开发者了解与参与飞桨深度学习开源项目与文心大模型开发实践。本次飞桨黑客马拉松由深度学习技术及应用国家工程研究中心主办，百度飞桨承办，活动包含四大赛道：开源贡献个人挑战赛、飞桨护航计划集训营、Fundable Projects、优秀稿件征集与传播，等你来挑战！活动详细信息可参考  [PaddlePaddle Hackathon 说明](https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/10_contribution/hackathon_cn.md)。

此 issue 发布 **飞桨护航计划集训营（第二批）** 的任务，主要在第一批的基础上进行补招。第一批护航计划集训营活动信息可参考 #61006 

开发者提交简历&通过面试后，以远程的方式深度参与飞桨开源项目开发课题，成果以 PR（Pull Requests）的形式贡献到指定代码仓库，实训期 3 个月（每周开发时间至少 25h），奖金 3-5 🌟。

如果是第一次接触黑客松护航计划，可以通过以下材料了解活动详情和流程

- [第六期黑客松护航计划集训营活动说明](https://github.com/PaddlePaddle/docs/blob/develop/docs/guides/10_contribution/hackathon_cn.md#2-飞桨护航计划集训营)
- [护航计划集训营公开资料](https://github.com/PFCCLab/Camp)

## 入选营员名单公示

恭喜以下 4 位同学成功入选**第六期黑客松护航计划集训营**～🎉

| 开源贡献 repo | 项目标题&介绍                                                | 锁定营员                 | 导师           |
| ------------- | ------------------------------------------------------------ | ------------------------ | -------------- |
| Paddle        | [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | @Eddie-Wang1120          | @cyber-pioneer |
| Paddle        | [CINN 支持动态 Shape 专项 （后端规则升级）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十九cinn-支持动态-shape-专项后端规则升级) | @Austin-00               | @BiynXu        |
| Paddle Speech | [PaddleSpeech 套件能力建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十七paddlespeech-套件能力建设) | @kk-2000 <br> @mattheliu | @zxcd          |

## 报名记录

**报名格式参考：**

```
【报名】：1
【其他意向】：2、4、6
不接受调剂
```

简历投递邮箱 📮：ext_paddle_oss@baidu.com

> [!IMPORTANT]
> 报名延长至 **2024 年 4 月 12 日**，报名后务必尽快提交简历参与面试哦～

| 序号 | 开源贡献 repo | 项目标题&介绍                                                | 人数 | 报名情况 | 锁定营员 |
| ---- | ------------- | ------------------------------------------------------------ | :--: | :------: | -------- |
| 1 | Paddle | [组合机制算子专项和机制建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目八组合机制算子专项和机制建设) | 1 | @OrangeTT <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Eddie-Wang1120 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@xingE650 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Eddie-Wang1120 | 
| 2 | Paddle | [CINN 支持动态 Shape 专项 （后端规则升级）](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目十九cinn-支持动态-shape-专项后端规则升级) | 1 | @amazinGoing <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Austin-00 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Austin-00 | 
| 3 | Paddle | [动转静 SOT 项目支持动态 Shape](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十五动转静-sot-项目支持动态-shape) | 1 | @zoukeh <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@jshh0401 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> |  | 
| 4 | Paddle Speech | [PaddleSpeech 套件能力建设](https://github.com/PaddlePaddle/community/blob/master/hackathon/hackathon_6th/【Hackathon%206th】飞桨护航计划集训营项目合集.md#项目二十七paddlespeech-套件能力建设) | 2 | @5204AIO <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Chen-Lun-Hao <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@kk-2000 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@mattheliu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @kk-2000 <br> @mattheliu | 

## 统计信息 
> 排名不分先后

**Comment by 5204AIO** [comment]
【报名】：4
【其他意向】：1

**Comment by OrangeTT** [comment]
【报名】：1
【其他意向】：2

**Comment by ADream-ki** [comment]
【报名】：4
不接受调剂

**Comment by amazinGoing** [comment]
【报名】：2
【其他意向】：1，3

**Comment by kk-2000** [comment]
【报名】：4
不接受调剂

**Comment by zoukeh** [comment]
【报名】：3
【其他意向】：1
接受调剂

**Comment by Eddie-Wang1120** [comment]
【报名】：1
【其他意向】：2

**Comment by CJ77Qi** [comment]
【报名】：2
【其他意向】：1

**Comment by xingE650** [comment]
【报名】：1
【其他意向】：4

**Comment by luotao1** [comment]
请 @5204AIO @OrangeTT @zoukeh @xingE650 的 issue报名评论里写上：是否接受调剂

**Comment by mattheliu** [comment]
【报名】：4
【其他意向】：3、2、1
接受调剂

**Comment by OrangeTT** [comment]
接受调剂

**Comment by xingE650** [comment]
【报名】：1
【其他意向】：4
  接受调剂

**Comment by jshh0401** [comment]
【报名】：3
【其他意向】：4
接受调剂

**Comment by luotao1** [comment]
@jshh0401 简历投递邮箱 📮：[ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)
