### ISSUE TITLE
【resize图片+纯色填充】有没有类似tensorflow中resize_image_with_crop_or_pad图片的方法

### ISSUE THREAD

**Issue by xiangjinxin1019** [PaddlePaddle/Paddle#6290]
实际应用产生的图片不能保证统一的长宽，因此需要resize到一个固定的height和width，然后未包括的区域用纯黑色填充。
这在tensorflow中有resize_image_with_crop_or_pad这么个方法可以用，但发现linux上搭的tf环境有问题，不同tf版本报错还不一样，也挺依赖GLIBC版本的。
想问除了tf的这个方法，业内有没有类似的方法了？
现在能想到一个可选的方案，就是把图片paste到一个固定大小底色纯黑的图片上。

**Comment by QiJune** [comment]
这个可以自己用python+opencv实现吧

**Comment by qingqing01** [comment]
PaddlePaddle提供了一些图片操作
 - 文档在： http://doc.paddlepaddle.org/develop/doc/api/v2/data/image.html#module-paddle.v2.image
 - 代码： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py

>  因此需要resize到一个固定的height和widt

[resize_short](http://doc.paddlepaddle.org/develop/doc/api/v2/data/image.html#paddle.v2.image.resize_short) 是等比里resize，和你想要还不太一样。PaddlePaddle里是用python-opencv，只需要类似这个接口写个函数即可。

> 这在tensorflow中有resize_image_with_crop_or_pad这么个方法可以用

PaddlePaddle中resize和crop是分开的接口，resize如上面介绍，crop接口是[center_crop](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L201)和[random_crop](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L229) 。[simple_transform](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L277) 接口是降这些操作连起来的。
