### ISSUE TITLE
run vgg_16_cifar wrong.

### ISSUE THREAD

**Issue by zhuyong0000** [PaddlePaddle/Paddle#63]
运行./train.sh 出现下面错误：
I0910 08:11:05.670004  1881 GradientMachine.cpp:134] Initing parameters..
I0910 08:11:06.422868  1881 GradientMachine.cpp:141] Init parameters done.
**/usr/local/bin/paddle: line 46:  1881 Killed                  ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
No data to plot. Exiting!**

运行的环境是paddledev/paddle:cpu-demo-latest，paddle版本为:
PaddlePaddle 0.8.0b, compiled with
    with_avx: OFF
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning: 
    with_timer: OFF
    with_predict_sdk:

**Comment by songdaojun** [comment]
Maybe Out of Memory, See in /var/log/messages

**Comment by reyoung** [comment]
It says that `Killed`. So maybe just out of memory. Please
* set the batch_size smaller
* set dataprovider's pool size smaller.

We will give a documentation to guide how to use less memory to train the job.

**Comment by zhangscth** [comment]
遇到了相同的问题。。

**Comment by reyoung** [comment]
@zhangscth https://github.com/baidu/Paddle/pull/128/files#diff-d718076d937b4f0e340765bf95c122c3

如果是killed的话，看一下如何减少内存占用。这块文档还在写

**Comment by qingqing01** [comment]
@zhangscth @zhuyong0000 如何减少内存的文档:http://www.paddlepaddle.org/doc_cn/faq/index.html#id1

在这个demo中您可以尝试减少DataProvider缓存、或者减少batch size.
