### ISSUE TITLE
在aistudio上编译paddle-gpu版时，有些库需要获取root权限

### ISSUE THREAD

**Issue by DreamMaker777** [PaddlePaddle/Paddle#63041]
### 问题描述 Issue Description

在aistudio上编译paddle-gpu版时，有些库需要获取root权限，如patchelf
![Snipaste_2024-03-27_10-46-55](https://github.com/PaddlePaddle/Paddle/assets/31379701/b664958f-2493-4350-8447-a8b59736224f)
如何解决？

### 版本&环境信息 Version & Environment Information

aistudio环境

**Comment by GGBond8488** [comment]
可以sudo吗，如果不行可以试试conda
   ```
   conda create -n paddle_env
   ```
   然后，激活该环境：
   ```
   conda activate paddle_env
   ```
   最后，安装patchelf：
   ```
   conda install -c conda-forge patchelf
   ```

**Comment by DreamMaker777** [comment]
可以用conda安装，多谢大佬！ @GGBond8488
