### ISSUE TITLE
paddle.flatten_这个api无法使用，paddle提示没有这个api，但是官网给出了这个api，在位置的flatten_而不是flatten。

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/Paddle#63054]
### 文档链接&描述 Document Links & Description

有问题的文档链接：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/flatten__cn.html
该文档存在的问题：paddle.flatten_这个api无法使用，paddle提示没有这个api，但是官网给出了这个api，在位置的flatten_而不是flatten。
我还测试了对于多为tensor的flatten_发现可以用tensor.flatten_，不过这个可用的tensor.flatten_只是部分可以正确使用，比如我对一个三维张量tensor.shape=（2，3，2）执行tensor.flatten_（0，1）就会出现错误的结果，而tensor.flatten_（1，2）就是正确的结果，而且在tensor.flatten_（1，2）这个代码中，如果我改为tensor.flatten_（start_axis=1，stop_axis=2）就又会报错。
一名来自inner mongolia university 的学术垃圾研究生嘿嘿

**Comment by ZACP-DERMATOLOGY** [comment]
多为改为多维

**Comment by sunzhongkai588** [comment]
能否提供一下复现代码以及版本、环境信息

**Comment by ZACP-DERMATOLOGY** [comment]
相关截图，如下，上面每个情况我都截图了，上传的顺序可能
![报错2](https://github.com/PaddlePaddle/docs/assets/48373656/be0a9b0d-0bed-49de-822c-b5e853f17fb6)
![报错flatten_](https://github.com/PaddlePaddle/docs/assets/48373656/9454399b-2af8-44e4-93ed-6d4b48bc2c04)
![正确](https://github.com/PaddlePaddle/docs/assets/48373656/e725aa3e-6b60-455e-89f2-0d9701d23389)
![正确2](https://github.com/PaddlePaddle/docs/assets/48373656/850d4819-42ad-46a3-a5f0-85522be7b7d1)
是乱的，抱歉哈
![api](https://github.com/PaddlePaddle/docs/assets/48373656/18d5751a-87a0-4ac4-a959-377cca00e7d7)
![flatten正确](https://github.com/PaddlePaddle/docs/assets/48373656/efbf5cdb-1d45-4b66-8dba-5f863d94d4d0)
![报错1](https://github.com/PaddlePaddle/docs/assets/48373656/2873c53e-7c07-4dae-9b98-8dad0e015516)

**Comment by ooooo-create** [comment]
> 如果我改为tensor.flatten_（start_axis=1，stop_axis=2）就又会报错。
![image](https://github.com/PaddlePaddle/docs/assets/106524776/c85045f5-55da-4005-bc42-22f0b9f2929f)

这个应该是 a.flatten_() 里面不应该还包含 a

**Comment by ZACP-DERMATOLOGY** [comment]
对的，这个是敲错了，忽略这个图片，看别的图

**Comment by ZACP-DERMATOLOGY** [comment]
@sunzhongkai588

**Comment by GGBond8488** [comment]
@sealoongleft flatten_错误确定是相关的kernel有bug，我们会尽快修复

**Comment by ZACP-DERMATOLOGY** [comment]
嗯嗯，我会继续使用paddle的，你们回复很快
