### ISSUE TITLE
无法利用train完的model进行预测

### ISSUE THREAD

**Issue by Pinletrot** [PaddlePaddle/Paddle#631]
paddle使用的是docker。在demo目录下的mnist，train.sh完成之后，进行测试时出错。

"""
set -e
config=vgg_16_mnist.py
output=./mnist_vgg_model
log=pred.log

paddle train \
--config=$config \
--use_gpu=false \
--config_args=is_predict=1 \
--predict_output_dir=./pred_output \
--init_model_path=./mnist_vgg_model/pass-00000
2>&1 | tee $log
"""

报错
![image](https://cloud.githubusercontent.com/assets/20688585/20639178/70b3343c-b3f7-11e6-8d0c-72a18b732add.png)

**Comment by qingqing01** [comment]
请注意区分【测试】和【预测】， 使用上面脚本来预测不对。

-  测试： 可以建立下面 `test.sh`脚本：

```
set -e
config=vgg_16_mnist.py
output=./mnist_vgg_model
log=train.log

paddle train \
--job=test \
--config=$config \
--use_gpu=false \
--trainer_count=1 \
--init_model_path=./mnist_vgg_model/pass-00000 \
2>&1 | tee $log
```

注意，增加参数 `--job=test`,   这里不需要 `--config_args=is_predict=1 `。

- 预测：

    `vgg_16_mnist.py` 中的 `is_predict`分支是用来预测，可以使用Python API预测， 参考[快速入门demo](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/quick_start) 或 [图像分类demo](https://github.com/PaddlePaddle/Paddle/tree/develop/demo/image_classification) 。
