### ISSUE TITLE
The build-from-source doc has content duplicate with the build-using-docker one

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#6311]
http://www.paddlepaddle.org/docs/develop/documentation/en/getstarted/build_and_install/build_from_source_en.html

and 

http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html

**Comment by luotao1** [comment]
@typhoonzero and I discussed in https://github.com/PaddlePaddle/Paddle/issues/5941  (sorry, it is a Chinese issue), `build-using-docker` is a nice article for blog, and we decide to remain `build-from-source`, and put `build-using-docker` into our blog repo later. Thus, we do following things:
- `build-from-source` describes how to `build-using-docker` as well.
```
# run the following command to build a CPU-Only binaries if you are using docker
docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e "WITH_TESTING=OFF" paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5 bash -x paddle/scripts/docker/build.sh
# else run these commands
mkdir build
```
- We extract the unitest part from `build-using-docker` into `build-from-source`. http://www.paddlepaddle.org/docs/develop/documentation/en/getstarted/build_and_install/build_from_source_en.html#run-tests

So can we remove the link of `build-using-docker` again after #6306 ?

**Comment by typhoonzero** [comment]
I thought it will be great if we put `build-using-docker` to blog as a "best practice" post and extend the documents. Then we can make the document simple and clear.

**Comment by wangkuiyi** [comment]
I think PaddlePaddle contributors should use Docker to unique their development environments. Otherwise, it would be even difficult to report building problems in issues, and it would be hard for us to figure out the reasons.

I agree that Docker-based building process should generate wheel packages (or other pip-installable formats) so that DL researchers could do `pip install paddle` and don't have to rely on Docker.

**Comment by typhoonzero** [comment]
@luotao1 @wangkuiyi Can we merge `build from docker` document contents to `build from source` and make Docker build method our only official supported build method?  And make `build from docker` shorter?

**Comment by luotao1** [comment]
> Can we merge build from docker document contents to build from source and make Docker build method our only official supported build method? 

I agree it. But what's the new title? Still `build from source`?
- Install and Build
   - Install Using pip
   - Run in Docker Containers
   - Build from Sources

**Comment by luotao1** [comment]
close due to we have the new install document: http://www.paddlepaddle.org/docs/0.14.0/documentation/fluid/zh/new_docs/beginners_guide/install/install_doc.html
