### ISSUE TITLE
api文档中无此get_path_from_url，但我用的时候确实可以使用

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/Paddle#63135]
### 文档链接&描述 Document Links & Description

from paddle.utils.download import get_path_from_url这个api我运行了，确实存在，但是官方的api中没有查询到，如果不是我看的仔细这个api我可能永远不知道。
官方文档中只给出了paddle.utils.download.get_weights_path_from_url(url, md5sum=None)，这俩api肯定不一样，而且我发现好多隐藏api了，官方是刻意这样做的吗？

### 请提出你的建议 Please give your suggestion

增加对缺失的api进行补充
![image](https://github.com/PaddlePaddle/Paddle/assets/48373656/4375436e-b903-477e-9d1b-983e349a0a2b)

**Comment by YanhuiDua** [comment]
你好，get_path_from_url 这个url是存在的，与get_weights_path_from_url的关系如下：get_weight_form_url 给了默认的weight_home路径

https://github.com/PaddlePaddle/Paddle/blob/9f75b0960a35b4bc10738aad78a2a4aea2bfee03/python/paddle/utils/download.py#L70

如果需要下载给定的权重，我们更推荐使用get_weights_path_from_url

你说的其他的没有在doc显示的doc，我们内部会再检查，感谢建议！

**Comment by ZACP-DERMATOLOGY** [comment]
谢谢，写出来更好些我觉得

**Comment by sunzhongkai588** [comment]
> 而且我发现好多隐藏api了，官方是刻意这样做的吗？

是的。Paddle 的 API  分为**公开/非公开**的，公开API 才会暴露在官网文档中，提供给开发者。一般 Paddle 的习惯是把公开 API 放在  `__all__` 中

https://github.com/PaddlePaddle/Paddle/blob/9f75b0960a35b4bc10738aad78a2a4aea2bfee03/python/paddle/utils/download.py#L54

但 `get_path_from_url` 这个 API 我们内部还得确定一下，看起来似乎像是要公开的但忘记进 `__all__` 了

**Comment by ZACP-DERMATOLOGY** [comment]
谢谢技术大佬支持，祝paddle越来越好，我会继续使用的

**Comment by xuxinyi389** [comment]
get_weights_path_from_url 指定root_dir参数为WEIGHT_HOME，底层调用 get_path_from_url。get_weights_path_from_url 可以覆盖 get_path_from_url 的用法，无需再公开 get_path_from_url 这个API。
