### ISSUE TITLE
Compile time - Runtime separation violation: setting xxBind as Attribute

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6316]
To achieve Compile time - Runtime separation, everything passed from Python to cpp should be proper serialized (e.g., serialized using protobuf).

xxBind (e.g., BlockDescBind) is not the proper way to do serialization, thus we should not use it as attribute.

This following code will break when Paddle runs on multiple machines, because BlockDescBind can not be serialized:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/recurrent_op.cc#L237-L238 :
```c++
    auto *block = Attr<framework::BlockDescBind *>(kStepBlock);
    auto *program = block->Program();
```

**Comment by jacquesqiao** [comment]
every bind have a Proto interface thus they can be serialized. for example:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/block_desc.h#L91

**Comment by helinwang** [comment]
That is good! But Attribute should not be `framework::BlockDescBind *`, it should be a plain protubuf object. Otherwise probably protobuf does not serialize `BlockDescBind` correctly. I tested with `test_understand_sentiment_lstm.py`, the step_block is serialized as:
```proto
attrs {
      name: "step_block"
      type: BLOCK
      b: true
    }
```
It does not make sense to me.

**Comment by helinwang** [comment]
Block is serialized with block ID, the implementation is correct.
