### ISSUE TITLE
Compile time - Runtime separation violation: Executor should not take xxBind as argument

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6317]
To achieve Compile time - Runtime separation, everything passed from Python to cpp should be proper serialized (e.g., serialized using protobuf).

The executor may run on a remote machine, for it to work correctly in distributed training, the `Run` method (https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/executor.h#L38 )
```c++
void Run(const ProgramDescBind&, Scope*, int, bool create_local_scope = true);
```

should not take `ProgramDescBind` as the argument, because `ProgramDescBind` can not serialize.

**Comment by jacquesqiao** [comment]
Every bind can be serialized to a Proto, bind is used to speed up the construction of graph, when send the graph to worker node in dist train, I think take a proto message directly is Ok.

**Comment by helinwang** [comment]
That's good! Then it's easier to change. We need to change the `Run` method to take `ProgramDesc` as argument. @tonyyang-svail told me before it was taking `ProgramDesc` but later changed to `ProgramDescBind`, I thought it may because there is some issue about `ProgramDesc` so we changed to `ProgramDescBind` to walk around the problem.

**Comment by helinwang** [comment]
Thanks to @reyoung , this is fixed.
