### ISSUE TITLE
Support reduction Layer (or Operator).

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#632]
1. This operation is needed in variational autoencoder,  https://github.com/PaddlePaddle/Paddle/issues/579
2. Reduction op: sum, mean,...

**Comment by reyoung** [comment]
Could `reduce` operator be implemented by `img_pool_layer`, which pooling kernel be very large?

**Comment by qingqing01** [comment]
我感觉 `img_pool_layer` 做 `reduce` 还是不够灵活，可能还是需要实现独立的op。
