### ISSUE TITLE
We need compile time - runtime separation

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6322]
We need to separate compile time and runtime for:

1. [multiple node training support](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/refactor/distributed_architecture.md#distributed-training-architecture), the compile time step (Python) generates a `ProgramDesc` for single GPU execution, gets converted to another `ProgramDesc` for multiple node execution. And sent over-the-wire (needs serialization) to remote nodes for execution.

1. [single node multiple GPU training support](https://github.com/dzhwinter/Paddle/blob/ddc258734e7b5a4a88ab3dd8f009adec49257ec9/paddle/framework/multigpu.md), the compile time step (Python) generates a `ProgramDesc` for single GPU execution, gets converted to another `ProgramDesc` for multiple GPU execution.

1. Without a clear compile time and runtime separation, it's hard to implement multiple thread executor too: https://github.com/PaddlePaddle/Paddle/issues/6319

All three points above are **blocked** by having the compile time - runtime separation, here are the few places that I found that violates it:

https://github.com/PaddlePaddle/Paddle/issues/6317
https://github.com/PaddlePaddle/Paddle/issues/6316

**Comment by jacquesqiao** [comment]
>All three points above are blocked by having the compile time - runtime separation, here are the few places that I found that violates it:
Do you mean that we should have compile time - runtime separation, but it's not implemented well?

**Comment by helinwang** [comment]
> Do you mean that we should have compile time - runtime separation, but it's not implemented well?

Yes, the places I found that are not implemented well are described in the two issue links I wrote at the bottom.

**Comment by typhoonzero** [comment]
The main cause may be that we don't have a "compile" interface explicitly for users to call. Currently, "Optimizer" do both append backward OPs and optimization OPs, after that, the "default_main_program" is ready to run. There can be sevaral methods to achieve this without changing the current interface:

1. Modify the `default_main_program` when creating `Executor`, pass any argument to `Executor` ctor to configure whether the job is multi-threaded or distributed.
1. Call `Executor.optimize(threads, gpu, pservers, trainers, ...)` to modify the program.

**Comment by helinwang** [comment]
@typhoonzero thanks that's some good points! By `Executor` do you mean Python `Executor` or the C++ `Executor`? My view (could be wrong) is that only Python `Executor` knows if the user want to run distributed program or not. The C++ `Executor` does not care if the current program it runs is for distributed running or not.

**Comment by typhoonzero** [comment]
> By Executor do you mean Python Executor or the C++ Executor?

The Python Executor.

**Comment by typhoonzero** [comment]
Maybe duplicated to: https://github.com/PaddlePaddle/Paddle/issues/6285

**Comment by helinwang** [comment]
@typhoonzero Agree that we need more explicit API. I think we need to hide it from the user, but internally in Python we need more explicit API as you mentioned.

**Comment by helinwang** [comment]
This issue is out-of-date, closing.
