### ISSUE TITLE
win7 32位操作系统安装paddle

### ISSUE THREAD

**Issue by zhys513** [PaddlePaddle/Paddle#63263]
### 请提出你的问题 Please ask your question
应用场景：在win7下使用paddleocr
系统环境：win7 32位操作系统
py环境：miniconda独立的env，python3.8
操作：直接使用pip安装paddle爆出，找不到对应的版本
问题：有什么办法可以使得paddle在win7系统上适配，或者说官方已经不再适配win7操作系统？

**Comment by ZHUI** [comment]
你好，可以上是寻找更早的paddle版本试试

**Comment by ZHUI** [comment]
询问了内部同学，不支持 win7 32位的系统
