### ISSUE TITLE
请问下sep_degree是什么

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#63299]
### 请提出你的问题 Please ask your question

请问下，这个sep group是哪种并行方式呢？是否有可以参考学习的文档呢？
之前只知道有4D并行，现在看起来变成5D了，想学习一下。

相关PR：https://github.com/PaddlePaddle/Paddle/pull/56271
![图片](https://github.com/PaddlePaddle/Paddle/assets/35131887/63b8c635-11f7-41da-afec-7a10bc7ef18e)

**Comment by ForFishes** [comment]
这个是切分sequence，实现另一种并行方式。对于transfomrer 结构而言，中间变量tensor维度是[b,s,n,h]，切分b是数据并行，切分n是张量模型并行，切分s就是sep并行。
