### ISSUE TITLE
【文档】docker安装文档中在运行gpu docker image前并没有提示用户需要先安装nvidia驱动

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#633]
1. 是否应该先提示用户安装好nvidia驱动，或者直接build到paddle的gpu-image中。如果按照文档在没有安装nvidia驱动库的机器上进行安装docker时，是无法执行export的语句的。
例如假设，用户在公有云服务器上，可能所有软件需要用户自己安装，所以有必要在文档中提醒用户先进行安装nvidia驱动后在执行图中的命令。
![image](https://cloud.githubusercontent.com/assets/6229206/20639860/1f0a3b5e-b40a-11e6-8cf7-05e82ac4cc9f.png)

**Comment by gangliao** [comment]
很有道理
