### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle.fluid'

### ISSUE THREAD

**Issue by XsSHX** [PaddlePaddle/Paddle#63317]
### 问题描述 Issue Description

windows:11
python:3.8.19
conda虚拟环境
运行 python -u tools/first-order-demo.py   --driving_video 'C:/Users/Administrator/Desktop/HL/1313.mp4'  --source_image 'C:/Users/Administrator/Desktop/HL/1212.jpg' --relative --adapt_scale --output '/home/aistudio/result' --image_size 512 --face_enhancement
报错ModuleNotFoundError: No module named 'paddle.fluid' 已经下载过paddle该如何解决

### 版本&环境信息 Version & Environment Information

AMD paddlepaddle==2.6.1 CPU

**Comment by pkuzyc** [comment]
新版本废弃了 fluid api，有用到 fluid api 的请使用其他替代 API。见文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/fluid/Overview_cn.html
