### ISSUE TITLE
place.cc里面某些报错退出用的是std::exit

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#63310]
### 请提出你的问题 Please ask your question

PaddlePaddle框架里面有很多的内置检查，各种不符合预期的会报错，例如使用`PADDLE_ENFORCE_EQ`或者类似的宏定义。
注意到 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/place.cc 这个里面有一些报错，用的是`LOG(ERROR)`后面接`std::exit`的方式。
比如：
![图片](https://github.com/PaddlePaddle/Paddle/assets/35131887/04210a87-bc5f-440a-bf7b-09f9447ade8d)

想问一下是特意这么写的么？

我遇到的问题是，在跑某个模型的时候，踩上了place不匹配的报错，但是由于这里用的是直接退出，而不是通常的那种带报错的宏定义，导致无法打出来调用栈，就比较难定位到具体是哪里的place喂错了才导致的训练失败。
如果把这个`place.cc`文件里面的一堆`exit`都换成通常的`ENFORCE`写法，就方便多了。

**Comment by Galaxy1458** [comment]
https://github.com/PaddlePaddle/Paddle/issues/62748 已有开源任务在逐步解决这类问题。
