### ISSUE TITLE
ImportError: cannot import name 'in_cinn_mode' from 'paddle.base.framework'

### ISSUE THREAD

**Issue by SiqinLv** [PaddlePaddle/Paddle#63314]
### bug描述 Describe the Bug

paddle2onnx               1.1.0
paddlefsl                 1.1.0
paddlenlp                 2.7.2
paddlenlp_ops             0.0.0
paddleocr                 2.6.1.3
paddlepaddle-gpu          2.6.1

### 其他补充信息 Additional Supplementary Information

root@40395f5353e1:/data/PaddleNLP/llm# python3.10 predictor.py 
Traceback (most recent call last):
  File "/data/PaddleNLP/llm/predictor.py", line 29, in <module>
    from paddle.base.framework import in_cinn_mode, in_pir_executor_mode
ImportError: cannot import name 'in_cinn_mode' from 'paddle.base.framework' (/usr/local/lib/python3.10/site-packages/paddle/base/framework.py)

试过很多种方案，依然报ImportError: cannot import name 'in_cinn_mode' from 'paddle.base.framework' ，烦请帮忙解决下

![image](https://github.com/PaddlePaddle/Paddle/assets/70061450/e228a7e5-745d-45e2-88a2-b3ee309a9d9f)

**Comment by pkuzyc** [comment]
可以提供下更详细的代码，我没有复现出这个bug，可以正常 import:
![infoflow 2024-04-08 20-42-25](https://github.com/PaddlePaddle/Paddle/assets/32740647/38350d9f-a201-4a03-891a-c3fb53a28a2b)

**Comment by Sgzmust** [comment]
我也遇到这个问题了
>>> from predictor import BasePredictor, ModelArgument, PredictorArgument, create_predictor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/PaddleNLP/llm/predictor.py", line 29, in <module>
    from paddle.base.framework import in_cinn_mode, in_pir_executor_mode
ImportError: cannot import name 'in_cinn_mode' from 'paddle.base.framework' (/root/anaconda3/envs/paddle/lib/python3.11/site-packages/paddle/base/framework.py)

**Comment by weiweiwei010119** [comment]
cannot import name 'in_cinn_mode' from 'paddle.base.framework'

**Comment by sanbuphy** [comment]
> 可以提供下更详细的代码，我没有复现出这个bug，可以正常 import: ![infoflow 2024-04-08 20-42-25](https://private-user-images.githubusercontent.com/32740647/320485453-38350d9f-a201-4a03-891a-c3fb53a28a2b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5ODU3MDIsIm5iZiI6MTcxNzk4NTQwMiwicGF0aCI6Ii8zMjc0MDY0Ny8zMjA0ODU0NTMtMzgzNTBkOWYtYTIwMS00YTAzLTg5MWEtYzNmYjUzYTI4YTJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDAyMTAwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc2MjBkNmJjODViNDQyOWQ1N2ZlMGE5MDM0MjBjYzZmNzk0YTQ1ZWU2ZDAxNDJiMTMwOTk5YTI5ZWFmZTFhYjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7NGs79-DfZkL_fZO2u0zLZTRHAlun1tpApQIf0vlk0Q)

你好 @pkuzyc ，这个问题可以在 aistudio 上创建 2.6.1环境，即可复现；
paddlehub                  2.4.0
paddlenlp                  2.8.0.post0
paddlepaddle-gpu           2.6.1

**Comment by sanbuphy** [comment]
@Sgzmust @weiweiwei010119  
使用 `python -m pip install paddlepaddle-gpu==0.0.0.post118 -f https://www.paddlepaddle.org.cn/whl/linux/gpu/develop.html` 
安装最新版本后可解
