### ISSUE TITLE
paddle2.0 or paddle 1.8怎么加载pdiparams和pdmodel

### ISSUE THREAD

**Issue by hahlw** [PaddlePaddle/Paddle#63368]
### 请提出你的问题 Please ask your question

paddle2.0 or paddle 1.8怎么加载pdiparams和pdmodel

**Comment by tianshuo78520a** [comment]
> ### 请提出你的问题 Please ask your question
> paddle2.0 or paddle 1.8怎么加载pdiparams和pdmodel

可以参考这个文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/1.8/beginners_guide/coding_practice/save_load_variables.html
