### ISSUE TITLE
_softmax_backward_data

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#63387]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

请问Paddle的API有对应的_softmax_backward_data实现没？我想实现以下的softmax反向，需要用到这个API：

https://github.com/huggingface/transformers/blob/41579763ee47a68d0c15fd798db1a309723d94d2/src/transformers/pytorch_utils.py#L38

https://pytorch.org/cppdocs/api/function_namespaceat_1a96dd211fdadf0c2816d55fe0e577b6d3.html

**Comment by tianshuo78520a** [comment]
看上去_softmax_backward_data 方法在Pytorch中也不是推荐使用的，请问你的需求是什么？ 是想自定义反向么？
自定义反向可以看下[PyLaye方法](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/autograd/PyLayer_cn.html#pylayer)

**Comment by w5688414** [comment]
复现下面的模型：

https://github.com/huggingface/transformers/blob/41579763ee47a68d0c15fd798db1a309723d94d2/src/transformers/models/deberta_v2/modeling_deberta_v2.py#L115

**Comment by tianshuo78520a** [comment]
目前Paddle没有对应的API
