### ISSUE TITLE
regression_cost使用求助：如何使用百分误差

### ISSUE THREAD

**Issue by liuzongquan** [PaddlePaddle/Paddle#634]
我看了源码中regression_cost layer的默认实现是采用square_error（均方误差）作为回归测试的默认的方法，现在问题是如果我希望使用相对误差（也叫百分误差）MAPE，如何实现呢？非常感谢！

**Comment by qingqing01** [comment]
目前不支持MAPE，如果想实现，可以在 `Paddle/paddle/gserver/layers/CostLayer.*` 中增加实现。
