### ISSUE TITLE
如何提高paddlepaddle的GPU的并发的性能

### ISSUE THREAD

**Issue by xiefuwei390** [PaddlePaddle/Paddle#63413]
### 请提出你的问题 Please ask your question

我使用一张4090的gpu卡，https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/deploy/cpp，在进行目标检测时候，使用了GPU，因为我有三个相机需要做识别，单个相机的识别效率在4090上是800ms左右（因为图片太大，其实是做了切片的子图来送入做检测的，有4到6张1504x1504的子图），我目前是将https://github.com/PaddlePaddle/PaddleDetection/tree/release/2.7/deploy/cpp的predict的代码移植过来在一个线程上做识别，我能够开多个线程一起并发识别吗？但是我看GPU的使用率已经到97%了，是否是通过增加显卡的方式？感谢回复

**Comment by HydrogenSulfate** [comment]
麻烦 @lyuwenyu 看一下这个问题

**Comment by lyuwenyu** [comment]
可以多进程并发，利用率那么高 有条件的话话 建议还是加卡
