### ISSUE TITLE
compilation error on centos 7.2 (both with and without GPU support)

### ISSUE THREAD

**Issue by jimdowling** [PaddlePaddle/Paddle#635]
* How to reproduce:
export LD_LIBRARY_PATH=/usr/local/cuda/lib64:$LD_LIBRARY_PATH
export PATH=/usr/local/cuda/bin:$PATH
cmake .. -DWITH_GPU=ON -DWITH_DOC=OFF

The problem is this line on 32 of cmake/cudnn.make:
    get_filename_component(CUDNN_LIB_PATH ${CUDNN_LIBRARY} DIRECTORY)
The DIRECTORY variable is not defined.

I have installed cuda 8.0 in /usr/local/cuda. Cudnn version 5.1 is also installed there.

Here's my output. It's the same if i switch off GPU support.

* Output

-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.7")
-- Found PythonInterp: /bin/python2.7 (found suitable version "2.7.5", minimum required is "2.7")
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Found installed version of gflags: /lib64/cmake/gflags
-- Detected broken gflags install in: /lib64/cmake/gflags, version: 2.1.1 <= 2.1.2 which defines gflags_LIBRARIES = gflags which is not an imported CMake target, see: https://github.com/gflags/gflags/issues/110.  Attempting to fix by detecting correct gflags target.
-- Found valid gflags target: gflags-shared, updating gflags_LIBRARIES.
-- Detected gflags version: 2.1.1
-- Failed to find gflags - Could not find file: //include/gflags/gflags.h containing namespace information in gflags install located at: //include.
-- Failed to find gflags - Failed to determine gflags namespace using regex for gflags version: 2.1.1 exported here: /lib64/cmake/gflags using CMake.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY)
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE)
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE)
-- Found OpenBlas (include: /usr/include/openblas, library: /usr/lib64/libopenblas.so)
CMake Error at cmake/cudnn.cmake:32 (get_filename_component):
  get_filename_component unknown component DIRECTORY
Call Stack (most recent call first):
  CMakeLists.txt:60 (include)

-- Current cuDNN header is /usr/local/cuda/include/cudnn.h. Current cuDNN version is v5.
-- Found PythonLibs: /usr/lib64/libpython2.7.so (found suitable version "2.7.5", minimum required is "2.6")
-- Found PythonInterp: /bin/python2.7 (found version "2.7.5")
-- DROP LINT dataproviders/MultiDataProvider.cpp
-- DROP LINT dataproviders/MultiDataProvider.h
-- Configuring incomplete, errors occurred!

**Comment by jimdowling** [comment]
Sorry, just found a PR with this fixed #212.

**Comment by wangkuiyi** [comment]
Hi @jimdowling , Docker has been and will be in the near future the only officially supported way to running Paddle. Because our base image is Ubuntu 14.04, so its is also reasonable to build from source code on Ubuntu 14.04. More details can be found [here](http://www.paddlepaddle.org/doc/build/build_from_source.html#build-and-install). We used to try to support more platforms, but with more and more platforms supporting Docker, these trials become less valuable.
