### ISSUE TITLE
编译capi 时候遇到错误，找不到UINT64_MAX (新的错误)

### ISSUE THREAD

**Issue by zhipengli0524** [PaddlePaddle/Paddle#6354]
我是厂内员工，被这个问题困扰很久，值班同学可以到我机器上看看。
请联系lizhipeng02

cmake 选项：
cmake .. \
      -DWITH_GPU=OFF \
      -DCMAKE_INSTALL_PREFIX=/home/disk1/tools/paddlei.c_api \
      -DWITH_C_API=ON \
      -DWITH_PYTHON=OFF \
      -DWITH_SWIG_PY=OFF

错误信息：
[  1%] Built target extern_gflags
[  2%] Built target extern_glog
[  3%] Built target extern_mklml
[  4%] Built target extern_mkldnn
[  5%] Built target zlib
[  6%] Built target extern_protobuf
[  7%] Built target extern_eigen3
[  7%] Built target extern_gtest
[  8%] Built target extern_lib_any
[  8%] Built target cblas
[  9%] Built target extern_warpctc
[  9%] Generating ../../paddle/python/paddle/proto/TrainerConfig_pb2.py
[  9%] Generating ../../paddle/python/paddle/proto/ParameterService_pb2.py
[  9%] Generating ../../paddle/python/paddle/proto/ParameterServerConfig_pb2.py
[  9%] Generating ../../paddle/python/paddle/proto/ParameterConfig_pb2.py
[  9%] Generating ../../paddle/python/paddle/proto/OptimizerConfig_pb2.py
[  9%] Generating ../../paddle/python/paddle/proto/ModelConfig_pb2.py
[ 10%] Generating ../../paddle/python/paddle/proto/DataFormat_pb2.py
[ 10%] Generating ../../paddle/python/paddle/proto/DataConfig_pb2.py
[ 10%] Built target gen_proto_py
[ 11%] Built target paddle_proto
[ 11%] Built target enforce
[ 11%] Built target place
[ 11%] Built target memory
[ 12%] Built target memcpy
[ 12%] Built target cpu_info
[ 13%] Built target system_allocator
[ 13%] Built target meta_data
[ 13%] Built target buddy_allocator
[ 14%] Built target meta_cache
[ 14%] Built target memory_block
[ 16%] Built target paddle_memory
[ 16%] Built target paddle_gtest_main
[ 17%] Built target serialization_test
[ 18%] Built target paddle_optimizer
[ 19%] Built target parameter_optimizer_test
[ 20%] Built target paddle_cuda
[ 20%] Building CXX object paddle/trainer/CMakeFiles/paddle_trainer_lib.dir/ParamUtil.cpp.o
In file included from /home/disk1/tools/paddle.c_api/Paddle/paddle/trainer/ParamUtil.cpp:30:0:
/home/disk1/tools/paddle.c_api/Paddle/paddle/utils/Stat.h: In constructor 'paddle::StatInfo::StatInfo(paddle::Stat*)':
/home/disk1/tools/paddle.c_api/Paddle/paddle/utils/Stat.h:41:12: error: 'UINT64_MAX' was not declared in this scope
     min_ = UINT64_MAX;
            ^
/home/disk1/tools/paddle.c_api/Paddle/paddle/utils/Stat.h: In member function 'void paddle::StatInfo::reset()':
/home/disk1/tools/paddle.c_api/Paddle/paddle/utils/Stat.h:48:12: error: 'UINT64_MAX' was not declared in this scope
     min_ = UINT64_MAX;
            ^
make[2]: *** [paddle/trainer/CMakeFiles/paddle_trainer_lib.dir/ParamUtil.cpp.o] Error 1
make[1]: *** [paddle/trainer/CMakeFiles/paddle_trainer_lib.dir/all] Error 2
make: *** [all] Error 2

**Comment by jacquesqiao** [comment]
gcc什么版本的？

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如果需继续讨论再打开
