### ISSUE TITLE
Compile time - runtime separation / single node multiple GPU milestones

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6359]
1. Attributes use [Attr proto message](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/framework.proto#L35) only (any C++ trick to make changing to it easier?):
    **The current attribute items can't be serialized, we can't use ProgramDesc for executor unless we change this.**

    ```text
    $ cd paddle/paddle
    
    # brew install ack, or use ack-grep on linux
    $ ack 'Attr<' |sed 's/Attr</|/' |awk -F'|' '{print $2}'|sed 's/>(/|/' |awk -F'|' '{print $1}'|sort|uniq
    AttrType
    T
    bool
    float
    framework::BlockDescBind *
    int
    int32_t
    size_t
    std::string
    std::vector<int>
    std::vector<std::string>
    # not a single OpDesc::Attr
    ```

1. C++ Executor take ProgramDesc

    Eventually we will change to ExecutionPlan, ProgramDesc is similar to ExecutionPlan (both can be serialized), but ProgramDescBind is too different from ExecutionPlan. If we develop multiple thread executor based on ProgramDescBind, there are too much to change later.

1. ExecutionPlan design doc (https://github.com/PaddlePaddle/Paddle/pull/6078)

1. change C++ Executor to take ExecutionPlan

1. Multiple thread executor design doc

1. C++ multiple thread Executor

1. simple C++ planner

    Just place everything on CPU / GPU-0

1. Modular Python Executor

    [current code](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/executor.py#L92):
    ```Python
    # pseudo code
    # implement local Python executor first, remote Python executor later.
    def run(program):
      plan = planner.plan(program, local_devices)
      fetch_vars = cpp_executor.run(plan, g_scope)
      return fetch_vars
    ```

1. single node multiple GPU planner

#### Dependency

<img width="980" alt="screen shot 2017-12-06 at 5 00 24 pm" src="https://user-images.githubusercontent.com/1724178/33693294-fb5da780-daa6-11e7-9e45-8493e4d4ed8c.png">

**Comment by jacquesqiao** [comment]
Attr proto message: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/framework.proto#L75

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/framework.proto#L19

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/while_op.cc#L49
this line use attr to store a blockdescbind pointer and have serialize problem

**Comment by typhoonzero** [comment]
https://stackoverflow.com/questions/13603878/how-to-delete-arbitrary-objects-in-repeated-field-protobuf

We don't have method of removing objects from protobuf

**Comment by jacquesqiao** [comment]
so we need some helper function to help modify the execution plan proto message.

**Comment by reyoung** [comment]
> The current attribute items can't be serialized, we can't use ProgramDesc for executor unless we change this.


The current attribute can be serialized. https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_desc.cc#L296

**Comment by Yancey1989** [comment]
Need a Parallel Operator to execute the block with multi threads.

**Comment by helinwang** [comment]
This issue is out-of-date, closing.
