### ISSUE TITLE
paddle多卡训练，显卡之间通信时间过长，显卡使用率低

### ISSUE THREAD

**Issue by AvalonSama** [PaddlePaddle/Paddle#63612]
### 请提出你的问题 Please ask your question

如题，请问如何定位问题+优化

![image](https://github.com/PaddlePaddle/Paddle/assets/10769190/3708c86e-f682-40c7-aff9-608ffdb65fd5)

**Comment by lugimzzz** [comment]
方便提供一下paddle版本和可复现case

**Comment by q465414859** [comment]
为什么你的单机多卡 就可以用 我的就不行？
