### ISSUE TITLE
Auto generated docs for some ops are lack of necessary description 

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#6361]
1. Like ```elementwise_div``` op: http://paddlepaddle.org/docs/develop/documentation/en/api/v2/fluid/layers.html#elementwise-div
```paddle.v2.fluid.layers.elementwise_div(**kwargs)```
```**kwargs``` should be replaced by actual arguments with well explanation.

2. And some ops are lack of docs

**Comment by luotao1** [comment]
As we have [API doc standard](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md) and [a list of API doc jobs](https://github.com/PaddlePaddle/Paddle/issues?q=is:issue%20is:open%20label:documentation%20label:pythonapi) now, this issue could be closed.
