### ISSUE TITLE
[Paddle Inference] reuse cache不生效

### ISSUE THREAD

**Issue by NeroLoh** [PaddlePaddle/Paddle#63627]
### bug描述 Describe the Bug

问题引入MR：https://github.com/PaddlePaddle/Paddle/pull/53930/files
当cluster_buffer_记录的tensor，刚好是memory最大的tensor时，将不会进入条件内对tensor进行复用
![image](https://github.com/PaddlePaddle/Paddle/assets/15044135/a1cfa99a-f5c1-4e2e-aa42-31c6dc8582d5)

**Comment by zhoutianzi666** [comment]
这个是给旧的执行器使用的逻辑，这部分代码将要废弃了，请使用 config.enable_new_executor(True)来配置推理时候使用新执行器。
