### ISSUE TITLE
Add command `dmidecode ` in docker

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#6363]
As our docker image paddlepaddle/paddle:latest doesn't have `dmidecode ` command, so we can't check the cpu memory information in https://github.com/PaddlePaddle/Paddle/pull/6291 when we don't have root permission.

**Comment by luotao1** [comment]
In our server: 
```
dmidecode --version
2.11
```

**Comment by Yancey1989** [comment]
Will do that, and for another,  `dmidecode` need to mount the device `/dev/mem` in the container, and we need to run the Docker Container with privillege mode:
```bash
> docker run --privileged paddlepaddle/paddle /bin/bash
```
