### ISSUE TITLE
缺少torch.nn.utils.rnn.pad_sequence的API或者实现

### ISSUE THREAD

**Issue by w5688414** [PaddlePaddle/Paddle#63655]
### 需求描述 Feature Description

任务目标（请描述你正在做的项目是什么，如模型、论文、项目是什么？）; <br /> 需求场景（请描述你的项目中为什么需要用此功能）;  <br /> 功能描述（请简单描述或设计这个功能）

正在做论文复现，但缺少上述的API：

https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pad_sequence.html#torch.nn.utils.rnn.pad_sequence

https://github.com/huggingface/trl/blob/75c1c47fcc922136ca1de249d79d34742ab1783b/trl/core.py#L24

**Comment by caizejun** [comment]
你可以先用其他api组合实现该功能，后续我们会支持该api

**Comment by w5688414** [comment]
好的，谢谢
