### ISSUE TITLE
paddle是否支持在customdevice（比如mlu、npu）使用flashattention

### ISSUE THREAD

**Issue by zhaogf01** [PaddlePaddle/Paddle#63650]
### 请提出你的问题 Please ask your question

这是paddle关于flashattention的代码，我认为这里的逻辑是只支持在gpu上开启flashattention。请问是否是这样的？
如果是的话，请问paddle后续有没有在customdevice上支持flashattention的计划？
![20240418134445](https://github.com/PaddlePaddle/Paddle/assets/148510471/9cf310c8-2596-4091-8de2-8bd312b375c0)
![20240418134516](https://github.com/PaddlePaddle/Paddle/assets/148510471/532a28f6-3a06-4a19-a17b-722690d90502)

**Comment by caizejun** [comment]
目前你提到的两个硬件 paddle是支持了flashattention的 你可能需要下载对应硬件的paddle, 比如paddle-npu

**Comment by zhaogf01** [comment]
请问paddle-mlu的分支在哪里？如果想要自定义硬件后端，是否有相应的分支可以使用？

**Comment by caizejun** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/mlu_docs/paddle_install_cn.html
这里是paddle支持的多种custom-devices的使用文档，可以看一下
