### ISSUE TITLE
在瑞芯微3568上已经部署好Fastdeploy。请问example中Yolov5的自己的onnx模型怎么使用呢？

### ISSUE THREAD

**Issue by dxisdx** [PaddlePaddle/Paddle#63656]
### 请提出你的问题 Please ask your question

在瑞芯微3568上已经部署好Fastdeploy。请问example中Yolov5的自己的目标检测onnx模型怎么使用呢？
例程infer下载的现成的模型是model.pdiparams和model.pdmodel文件
现在我有自己的onnx模型不知道程序里面怎么引用。下面是例程可以跑的程序。检测人的。

import fastdeploy as fd
import cv2
import os

def parse_arguments():
    import argparse
    import ast
    parser = argparse.ArgumentParser()
    parser.add_argument("--model", default=None, help="Path of yolov5 model.")
    parser.add_argument(
        "--image", default=None, help="Path of test image file.")
    parser.add_argument(
        "--device",
        type=str,
        default='cpu',
        help="Type of inference device, support 'cpu' or 'gpu' or 'kunlunxin'.")
    parser.add_argument(
        "--use_trt",
        type=ast.literal_eval,
        default=False,
        help="Wether to use tensorrt.")
    return parser.parse_args()

def build_option(args):
    option = fd.RuntimeOption()
    if args.device.lower() == "kunlunxin":
        option.use_kunlunxin()

    if args.device.lower() == "gpu":
        option.use_gpu()

    if args.device.lower() == "ascend":
        option.use_ascend()

    if args.use_trt:
        option.use_trt_backend()
        option.set_trt_input_shape("images", [1, 3, 640, 640])
    return option

args = parse_arguments()

# 配置runtime，加载模型
runtime_option = build_option(args)
**model_file = os.path.join(args.model, "model.pdmodel")
params_file = os.path.join(args.model, "model.pdiparams")**
model = fd.vision.detection.YOLOv5(
    model_file,
    params_file,
    runtime_option=runtime_option,
    model_format=fd.ModelFormat.PADDLE)

# 预测图片检测结果
if args.image is None:
    image = fd.utils.get_detection_test_image()
else:
    image = args.image
im = cv2.imread(image)
result = model.predict(im)
print(result)

# 预测结果可视化
vis_im = fd.vision.vis_detection(im, result)
cv2.imwrite("visualized_result.jpg", vis_im)
print("Visualized result save in ./visualized_result.jpg")
![微信截图_20240418162953](https://github.com/PaddlePaddle/Paddle/assets/67620410/8174b356-9b48-4dfe-94c4-c78ba620ba16)
![微信截图_20240418163006](https://github.com/PaddlePaddle/Paddle/assets/67620410/c4a50fda-3c84-4a7d-9b5a-241b52db03d2)
![微信截图_20240418163014](https://github.com/PaddlePaddle/Paddle/assets/67620410/f4656772-1f5e-482a-b883-45f43db3859d)

**Comment by caizejun** [comment]
https://github.com/PaddlePaddle/FastDeploy/blob/develop/README_CN.md fastdeploy是支持直接部署onnx模型的 这边是fastdeploy仓库 ，你可以找找示例api 看看怎么用
