### ISSUE TITLE
paddlepaddle==2.6.0和2.6.1适配国产化与非国产化代码返回不一致问题

### ISSUE THREAD

**Issue by leyiwang** [PaddlePaddle/Paddle#63659]
### bug描述 Describe the Bug

发现arm的昆仑芯编译的paddle2.6.0在国产化arm机器上跑下面代码时返回的维度有问题，同样的代码得到了不同的结果，导致代码无法正确运行，
另外，也测试了paddle官网提供的paddlepaddle_xpu-2.6.1-cp310-cp310-linux_aarch64.whl, 也存在上述问题
附： https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/hardware_support/xpu/install_cn.html
国产化机器：飞腾arm、昆仑芯
<img width="554" alt="60280aa0b5867844268be77038a80c9e" src="https://github.com/PaddlePaddle/Paddle/assets/10727709/788cb9d7-3d65-40df-b0a1-e8247e081375">
非国产化机器：x86, 英伟达P40
<img width="582" alt="05e2f9d31c151f43cccfe4eaa512cd1e" src="https://github.com/PaddlePaddle/Paddle/assets/10727709/5fefebc8-ffac-4338-9ca6-dfc43b254007">

**Comment by caizejun** [comment]
你可以试一下reshape确保代码正确执行，这个问题我们会进行修复

**Comment by hong19860320** [comment]
可以先看下在 arm 环境下 cpu place 是否有同样问题，可以参考 https://www.paddlepaddle.org.cn/documentation/docs/zh/install/compile/arm-compile.html 编译纯 cpu 的 paddle whl 包。
