### ISSUE TITLE
SSD: Single Shot MultiBox Detector 此论文中的网络结论paddle是否已经使用或者将来有计划实现

### ISSUE THREAD

**Issue by westeast** [PaddlePaddle/Paddle#637]
SSD: Single Shot MultiBox Detector 此论文中的网络结论paddle是否已经使用或者将来有计划实现?

**Comment by qingqing01** [comment]
@westeast 目前已经计划实现，上周刚刚讨论过需要新增的模块

**Comment by reyoung** [comment]
@qingqing01 这个issue实现完了么？目前进展是什么？可以close了么？

**Comment by qingqing01** [comment]
Related to #871 , 这个可以关掉了，保留 #871  即可。 这个实现得一段时间，由 @Noplz 来实现，大致需要支持 4 - 5个模块。
