### ISSUE TITLE
单机多卡问题

### ISSUE THREAD

**Issue by crazyZSShuo** [PaddlePaddle/Paddle#63704]
#### 一个节点两张卡：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/3dfa650d-a813-46b9-89d3-942885e256b8)

#### 飞桨GPU版本以及CUDA版本：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/a4b64408-4155-4f4a-a656-ac423ce9a9e7)

#### 第一次运行检查脚本run_check, 输出正常：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/77816003-c2f6-4041-90f4-497340935b70)

#### 输出报错：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/8ccd5d1d-f47d-4fe1-a2e8-44e5afa9a403)

#### 再次运行run_check脚本时，出现报错：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/8e0a9089-fbc1-4390-b264-187cd28f3ff5)

查阅了好多资料，至今无法解决，请教一下如何解决这个问题，万分感谢！！！

**Comment by q465414859** [comment]
我也是 这个问题 一机多卡 出问题 一星期了 没解决  好难

**Comment by zhiminzhang0830** [comment]
看报错是磁盘满了，可以先清理一下磁盘空间，再试试

**Comment by crazyZSShuo** [comment]
> 看报错是磁盘满了，可以先清理一下磁盘空间，再试试

貌似不是磁盘问题...
磁盘与内存占用情况：
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/be9fb3f5-d6c5-4a04-847e-de49b05fbde9)
![image](https://github.com/PaddlePaddle/Paddle/assets/33218762/f0fcd349-f4e4-4dd1-81cf-29fc2fb1cb17)

**Comment by crazyZSShuo** [comment]
> 我也是 这个问题 一机多卡 出问题 一星期了 没解决 好难

确实好难~~ 单机单卡就正常，多卡就异常
