### ISSUE TITLE
Duplicated API: `DeviceContext::Wait` and `DeviceContext::Finish`

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#6370]
We should remove `DeviceContext::Finish` because

1. If CUDA or another device has errors when invoking `Wait` method, the error should be thrown by `Wait`.
2. These two APIs are confusing. How do developers pick whether should be invoked?
3. The meaning of `Finish` is not clear. `Finialize` always means `delete` or `destroy`, not `complete`. 

https://github.com/PaddlePaddle/Paddle/blob/584c9cfc82bedf7fd1e293b9e295d2fd5a196409/paddle/platform/device_context.cc#L127-L130

**Comment by chengduoZH** [comment]
How about replacing `Finish` with `GetLastError`?
