### ISSUE TITLE
使用--use_trt出错

### ISSUE THREAD

**Issue by Daniel-969** [PaddlePaddle/Paddle#63729]
### 请提出你的问题 Please ask your question

在执行deploy/python/infer.py时，使用--use_trt报错形状不匹配，但是在不使用--use_trt时并不会报错。在模型导出的时候执行tools/export.py并指定了input_shape。
![c13162dd8390db72ef5100bbd7b74c5a](https://github.com/PaddlePaddle/Paddle/assets/75155068/387ad6a8-5ba5-48e2-93a6-1e6f8f583cfa)

**Comment by Daniel-969** [comment]
我export指定了input_shape，不使用use_trt时不会报错，并且输出是这样的
![f2751a21ba66a824d052de679cc0edcc](https://github.com/PaddlePaddle/Paddle/assets/75155068/2bf26edc-534e-48fe-8950-071bc5aa5e92)

**Comment by Daniel-969** [comment]
这是deploy.yaml
![b477d9d37c97b55823bc64c5b5265d21](https://github.com/PaddlePaddle/Paddle/assets/75155068/cd8775a9-c784-4995-a57a-8c6ca0352ef7)

**Comment by yangjianfengo1** [comment]
模型导出时保存的shape和推理使用的shape一致吗

**Comment by Daniel-969** [comment]
是一致的，用的是cityscapes原图。我刚试了一下使用--enable_auto_tune，然后可以推理成功了
![121874301e4736b5eb3916ea8bbcf213](https://github.com/PaddlePaddle/Paddle/assets/75155068/90bb37a3-253b-4a8c-b9e3-f12845956816)
这是因为什么原因啊？

**Comment by yangjianfengo1** [comment]
应该是dynamic shape 推导出了问题，使用--enable_auto_tune吧，他会自动推导的，不用显式给shape的

**Comment by Daniel-969** [comment]
那它自动推导的shape和我导出的时候指定的shape一样吗，因为我要测试输入分辨率为1024*2048的时候的fps

**Comment by yangjianfengo1** [comment]
你导出的时候shape 指定为none，这样就可以输入任意形状，auto_tune是你推理的时候如果你输入的形状没有tune过，就会重新tune，也就是你输入1024*2048，他就会tune 1024*2048的最优性能

**Comment by Daniel-969** [comment]
我在导出的时候如果不指定inputshape会报错，因为它不指定输入的时候默认是-1，但是我改的代码里面为-1的时候会出错，所以我指定了输入大小为1024x2048。这个时候我使用了auto_tune，然后输入图片是cityscapes数据集的原图，它测试出来的性能也是1024x2048吗？因为我这个网络还要测试cityscapes输入大小为768x1536分辨率的图片。

**Comment by yangjianfengo1** [comment]
shape 指定为None 就是dynamic shape了
