### ISSUE TITLE
How to solve "license/cla Expected — Waiting for status to be reported"

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#63727]
### 请提出你的问题 Please ask your question

<img width="825" alt="image" src="https://github.com/PaddlePaddle/Paddle/assets/47998305/aa9e1d1a-6db4-42ab-8134-bb678a7adbea">
As title and above image.

**Comment by yangjianfengo1** [comment]
由于 [CLA](https://github.com/cla-assistant/cla-assistant) 是第三方开源库，有时候会不稳定。如果确定自己已签署CLA，但CLA没触发成功，可尝试：
* 关闭并重新开启本PR，来重新触发CLA。点击 Close pull request ，再点击 Reopen pull request ，并等待几分钟。
* 如果上述操作重复2次仍未生效，请重新提一个PR。
