### ISSUE TITLE
templatedoc 机制清理

### ISSUE THREAD

**Issue by SigureMo** [PaddlePaddle/Paddle#63734]
## 背景

框架现存部分 API 文档使用了 `@templatedoc` 装饰器来通过提取 OP 定义中的参数描述来自动生成 docstring，比如 `row_conv`：

https://github.com/PaddlePaddle/Paddle/blob/08c0424a595199d7bc25fb7b6c138e8e31a7f4b2/python/paddle/static/nn/common.py#L3337-L3383

很明显，它通过其模板部分（如 `${comment}`、`${x_type}`、`${x_comment}` 等）是通过 OpMaker 中的参数描述来填充的：

https://github.com/PaddlePaddle/Paddle/blob/08c0424a595199d7bc25fb7b6c138e8e31a7f4b2/paddle/fluid/operators/row_conv_op.cc#L77-L135

可以猜测，当初的设计是为了避免重复书写参数描述，但是这样一方面会导致文档编写不直观，另一方面 IDE 无法通过静态分析获取完整的 docstring，开发体验较差。而 OpMaker 在未来是会被清理的，因此我们需要将这部分文档迁移到 docstring 中。

另外，因为一些 fluid 等的历史原因，我们框架内也存在了两份 `layer_function_generator.py`（`templatedoc` 的定义文件），因此我们希望尽可能清理掉无用的函数 / 文件，保持框架代码的整洁

## 目标

-  清理无用 `templatedoc` 装饰器的使用，将 OP 定义中的参数描述添加到现有的 docstring 中（不必清理 OpMaker 中的，只需要 copy 到 docstirng 即可），清理后框架不再存在 `templatedoc` 装饰器的使用
-  清理掉 `templatedoc` 函数定义，清理 `layer_function_generator.py`（`python/paddle/base/layers/layer_function_generator.py` 和 `python/paddle/tensor/layer_function_generator.py`）无用函数
-  清理 `layer_function_generator.py` 其余函数（如 `add_sample_code`，看是否能完全清理掉，此为进取项）

> [!TIP]
>
> PR 应拆尽拆，尽可能每个 PR 只做一件事情～

## 收益

-  确保框架内代码整洁性，无冗余代码
-  确保 OpMaker 清理后不会导致 API 文档的破坏和丢失
-  提升开发体验，IDE 可以通过静态分析获取完整的 docstring

**Comment by yangjianfengo1** [comment]
感谢您的建议，我们会慎重考虑的。

**Comment by SigureMo** [comment]
@yangjianfengo1 开源任务 tracking issue 哈，值班同学可以跳过，卡片已删除
