### ISSUE TITLE
怎样使用paddle里面的 auc_evaluator等函数 就是如何导出测试的分类错误率 

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/Paddle#638]
想通过导出每次训练 的分类test错误率 这样在预测时就可以实现 自动选择最优参数了 可是只在文档里找到了求错误率的函数 但不知道如何进行调用 并将其赋值给变量

**Comment by qingqing01** [comment]
如果设置了 evaluator， 评估结果会打印到log文件里面，可以通过log文件正则匹配出需要的结果(比如分类错误率)。
