### ISSUE TITLE
noamdecay有点小问题

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/Paddle#63840]
### 文档链接&描述 Document Links & Description

出问题的文档网址：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/optimizer/lr/NoamDecay_cn.html
noamdecay给出的公式如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/48373656/d76e7f42-bb88-4ec2-a5b8-f82e6be02e8a)
而论文中给出的公式如下：
![image](https://github.com/PaddlePaddle/Paddle/assets/48373656/98d73304-f5d1-4036-bd1d-04257763b667)
出问题的地方：
论文中给出的是step_num，也就是batch，但paddle文档中给出的是epoch，这里是文档出错了，还是真的按文档所述，就是按照epoch来进行计算的呢？

**Comment by zhwesky2010** [comment]
@sealoongleft 这里只是描述变量的不同，实现是一样的。具体是step_num还是epoch_num，取决于你怎么用：
<img width="702" alt="infoflow 2024-04-28 16-47-31" src="https://github.com/PaddlePaddle/Paddle/assets/52485244/5f4b3203-f697-4fe5-abe9-d9a45f9806c9">

如果你每个step都更新一次，那么公式里就是`step_num`，如果你每个epoch更新一次，那么公式里就是`epoch_num`。

怎么使用上是很灵活的，公式中的`epoch_num`也不限定一定是指与epoch有关

**Comment by ZACP-DERMATOLOGY** [comment]
多谢大佬回复，那我就明白了，后面我自己也进行了实际测试，确实和大佬说的一样，取决于我怎么用
