### ISSUE TITLE
Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed.

### ISSUE THREAD

**Issue by pobi123** [PaddlePaddle/Paddle#63882]
### bug描述 Describe the Bug

I got an error while using paddleseg for semantic segmentation training.
Error: C:\home\workspace\Paddle\paddle\phi\kernels\gpu\one_hot_kernel.cu:37 
Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. 
Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [20], but received [20].

My dataset has 7910 images, using grayscale annotations, with a total of 20 labels (including background classes).

Here is my environment configuration:
cuda 11.6
cudnn 8.4.0
python 3.8.0
paddlapddle 2.5.2
paddleseg 2.9

Can someone help me?

**Comment by BiynXu** [comment]
Can you please provide reproduction scripts?

**Comment by pobi123** [comment]
> Can you please provide reproduction scripts?

thank you. I've solved the problem. It is caused by the change of pixel value of some pixel points caused by interpolation algorithm during image geometry transformation.

**Comment by ISROalka** [comment]
My model based on paddle seg is not able to give better mIOU and accuracy and classes are nt predicted in right wya here i have tried all the things but loss is sometimes incresing and decresing not systmatic and accracy is moving slowly and prediction is very poor ..please give some idea as my classes was negtive  varying from -11.5,-10,-10.5.....0...10.5,11, i mapped them to 1,2,3...47 and backgroung to 0 class but prediction is poor and losses i am using is sum of focalloss, dice loss and jaccard loss 
 unique Actual Wrapped_Grad Class in Range dir [-6.  -5.5 -4.  -1.  -0.5  0.   7.   8.5 10.  11. ] (1, 1, 512, 512)
38/38 [==============================] - 183s 5s/step - batch_cost: 4.7053 - reader cost: 6.2986e-04
2024-05-15 11:39:48 [INFO]      [EVAL] #Images=38 mIoU=0.0143 Acc=0.6740 Kappa=-0.0002
2024-05-15 11:39:48 [INFO]      [EVAL] Class IoU:
[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.0082 0.6777 0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.    ]
2024-05-15 11:39:48 [INFO]      [EVAL] Class Acc:
[0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.0097 0.9799 0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.     0.     0.
 0.     0.     0.     0.     0.     0.     0.     0.    ]
2024-05-15 11:39:50 [INFO]      [EVAL] The model with the best validation mIoU (0.0143) was saved at iter 1500.
 90%|█████████████████████████████████████████████████████████████████████████████████████████████████████████            | 97/108 [22:26<02:35, 14.10s/it]iter ,log_iters,avg_loss,avg_acc 1610 10 1400.1825492858886 0.7067124366760253
[TRAIN] epoch=15, iter=1610/10000, loss=1400.1825,acc=0.7067, lr=0.000427, batch_cost=11.9251, reader_cost=0.0032 | ETA 27:47:31
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████▉ | 107/108 [24:26<00:11, 11.93s/it]iter ,log_iters,avg_loss,avg_acc 1620 10 1721.4624839782714 0.7076393127441406
[TRAIN] epoch=15, iter=1620/10000, loss=1721.4625,acc=0.7076, lr=0.000427, batch_cost=11.9568, reader_cost=0.0018 | ETA 27:49:58
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 108/108 [24:38<00:00, 13.69s/it]
  8%|█████████▊                                                                                                            | 9/108 [01:47<19:51, 12.03s/it]iter ,log_iters,avg_loss,avg_acc 1630 10 1385.8811283111572 0.7077432632446289
[TRAIN] epoch=16, iter=1630/10000, loss=1385.8811,acc=0.7077, lr=0.000426, batch_cost=12.0030, reader_cost=0.0051 | ETA 27:54:25
 18%|████████████████████▌                                                                                                | 19/108 [03:48<18:13, 12.28s/it]iter ,log_iters,avg_loss,avg_acc 1640 10 2218.9738037109373 0.7083283424377441
[TRAIN] epoch=16, iter=1640/10000, loss=2218.9738,acc=0.7083, lr=0.000426, batch_cost=12.0786, reader_cost=0.0006 | ETA 28:02:57
 27%|███████████████████████████████▍                                                                                     | 29/108 [05:49<15:48, 12.00s/it]iter ,log_iters,avg_loss,avg_acc 1650 10 1506.3449691772462 0.7078171730041504
[TRAIN] epoch=16, iter=1650/10000, loss=1506.3450,acc=0.7078, lr=0.000425, batch_cost=12.0773, reader_cost=0.0011 | ETA 28:00:45
 36%|██████████████████████████████████████████▎                                                                          | 39/108 [07:49<13:47, 12.00s/it]iter ,log_iters,avg_loss,avg_acc 1660 10 3425.55717086792 0.7057007789611817
[TRAIN] epoch=16, iter=1660/10000, loss=3425.5572,acc=0.7057, lr=0.000425, batch_cost=12.0069, reader_cost=0.0011 | ETA 27:48:57
 45%|█████████████████████████████████████████████████████                                                                | 49/108 [09:51<12:06, 12.32s/it]iter ,log_iters,avg_loss,avg_acc 1670 10 1383.3897163391114 0.7080835342407227
[TRAIN] epoch=16, iter=1670/10000, loss=1383.3897,acc=0.7081, lr=0.000424, batch_cost=12.2504, reader_cost=0.0006 | ETA 28:20:45
 55%|███████████████████████████████████████████████████████████████▉                                                     | 59/108 [11:51<09:43, 11.90s/it]iter ,log_iters,avg_loss,avg_acc 1680 10 1447.272087097168 0.7078677177429199
[TRAIN] epoch=16, iter=1680/10000, loss=1447.2721,acc=0.7079, lr=0.000424, batch_cost=11.8960, reader_cost=0.0020 | ETA 27:29:34
 64%|██████████████████████████████████████████████████████████████████████████▊                                          | 69/108 [13:51<07:49, 12.04s/it]iter ,log_iters,avg_loss,avg_acc 1690 10 2010.936703491211 0.708225154876709
[TRAIN] epoch=16, iter=1690/10000, loss=2010.9367,acc=0.7082, lr=0.000423, batch_cost=12.0647, reader_cost=0.0015 | ETA 27:50:57
 73%|█████████████████████████████████████████████████████████████████████████████████████▌                               | 79/108 [15:50<05:45, 11.92s/it]iter ,log_iters,avg_loss,avg_acc 1700 10 1434.161421585083 0.7078392982482911
[TRAIN] epoch=16, iter=1700/10000, loss=1434.1614,acc=0.7078, lr=0.000423, batch_cost=11.8396, reader_cost=0.0015 | ETA 27:17:48
2024-05-15 11:59:51 [INFO]      Start evaluating (total_samples=38, total_iters=38)...
