### ISSUE TITLE
Miscellaneous issues on CUDA

### ISSUE THREAD

**Issue by lawrence910426** [PaddlePaddle/Paddle#63894]
### 问题描述 Please describe your issue

For your convenience, we have gathered several PRs into this issue. As soon as there are any new PR waiting for review, we would update this issue. Thank you for your reviewing ^^

1. Pull Request on `malloc_test` [link](https://github.com/PaddlePaddle/Paddle/pull/64145)
2. Pull Request on `test_sparse_sum_op` [link](https://github.com/PaddlePaddle/Paddle/pull/64147)

**Comment by BiynXu** [comment]
Is there any prior information or questions?
