### ISSUE TITLE
fluid 每个layer的 learning_rate 如何设置？

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6391]
fluid 每个layer的 learning_rate的设置 是否是在 ParamAttr 设置learning_rate参数？设置后 该layer的实际学习率 是不是 该参数值 与 全局学习率 的乘积 （即 是否与 PaddlePaddle V2 中的含义相同）？

**Comment by jacquesqiao** [comment]
是的
