### ISSUE TITLE
中文版CentOS7.2 中不能正常执行问题

### ISSUE THREAD

**Issue by Fanping** [PaddlePaddle/Paddle#6397]
在英文版中预测房价的代码可以很好的运行，中文版则报错如下：
 
 File "/usr/lib64/python2.7/site-packages/paddle/v2/__init__.py", line 86, in num_physica│
l_cores                                                                                   │
    os.popen("lscpu |grep \"Socket\" |awk -F':' '{print $2}'|xargs")                      │
ValueError: invalid literal for int() with base 10: ''

通过在中文系统中执行：export LANG="en_US.UTF-8"解决了上述问题，但是毕竟是改了系统语言，建议都能较好的支持~

加油，paddlepaddle~

**Comment by luotao1** [comment]
问题和 https://github.com/PaddlePaddle/Paddle/issues/5821#issuecomment-347164595 一样，已经在 https://github.com/PaddlePaddle/Paddle/pull/5952 解决了这个问题，可以使用最新代码重新试下，谢谢~
