### ISSUE TITLE
ubantu16.04 gcc4.9使用paddlepaddle运行deepspeech的一些问题

### ISSUE THREAD

**Issue by john81529** [PaddlePaddle/Paddle#6405]
1.我觉得，百度可以开源这么优秀的工具，是件让我非常感激的事情。
2.因为运行deepspeech，最开始我是在docker中运行的，很简单方便，然而，在deepspeech的deploy中，服务器程序是在docker中启动的，而客户端是在宿主机中启动，于是，出现socket的链接问题，错误111.
3.于是，我猜想是docker和宿主机的通信问题，就想不用docker了，安装了`pip install paddlepaddle-gpu`,安装的应该是0.10.5，然后出现这样的错误：
```
yyh@yyh-System-Product-Name:~/Chi-Rec$ python train.py
----------- Configuration Arguments -----------
augment_conf_path: conf/augmentation.config
batch_size: 256
dev_manifest: asset/preprocess/dev
init_model_path: None
is_local: True
learning_rate: 0.0005
max_duration: 27.0
mean_std_path: asset/preprocess/mean_std.npz
min_duration: 0.0
num_conv_layers: 2
num_iter_print: 100
num_passes: 200
num_proc_data: 16
num_rnn_layers: 3
output_model_dir: asset/train
rnn_layer_size: 2048
share_rnn_weights: True
shuffle_method: batch_shuffle_clipped
specgram_type: linear
test_off: False
train_manifest: asset/preprocess/train
trainer_count: 1
use_gpu: True
use_gru: False
use_sortagrad: True
vocab_path: asset/preprocess/vocab.txt
I1129 21:20:58.427788 3881 Util.cpp:166] commandline: --use_gpu=True --rnn_use_batch=True --log_clipping=True --trainer_count=1
[INFO 2017-11-29 21:20:58,805 layers.py:2539] output for conv_0: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-11-29 21:20:58,805 layers.py:3062] output for batch_norm_0: c = 32, h = 81, w = 54, size = 139968
Traceback (most recent call last):
File "train.py", line 131, in 
main()
File "train.py", line 127, in main
train()
File "train.py", line 107, in train
share_rnn_weights=args.share_rnn_weights)
File "/home/yyh/Chi-Rec/model_utils/model.py", line 46, in init
rnn_layer_size, use_gru, share_rnn_weights)
File "/home/yyh/Chi-Rec/model_utils/model.py", line 307, in _create_network
share_rnn_weights=share_rnn_weights)
File "/home/yyh/Chi-Rec/model_utils/network.py", line 263, in deep_speech_v2_network
index_range_datas=index_range_datas)
File "/home/yyh/Chi-Rec/model_utils/network.py", line 165, in conv_group
index_range_data=index_range_datas[0])
File "/home/yyh/Chi-Rec/model_utils/network.py", line 43, in conv_bn_layer
scale_sub_region = paddle.layer.scale_sub_region(
AttributeError: 'module' object has no attribute 'scale_sub_region'
```
据维护deepspeech的作者们说，是pip安装的版本较低，然后推荐我从这个url选一个合适的
https://paddleci.ngrok.io/viewLog.html?buildId=19611&buildTypeId=Manylinux1_Cuda80cudnn5cp27cp27mu&tab=artifacts，
姑且不说下载了几天都不成功的问题，主要的问题是根本安装不成功。错误和官网上描述的一样，然而依然无法解决。
4.于是，我只好尝试源码编译的模式，然后还是很多问题。
5.期待paddlepaddle的更方便的安装模式，的确docker的使用很方便，然而目前来说，那个通信的问题的确也是个很大的限制。

**Comment by Yancey1989** [comment]
Hi @john81529 , 感谢您对PaddlePaddle的关注

> 2.因为运行deepspeech，最开始我是在docker中运行的，很简单方便，然而，在deepspeech的deploy中，服务器程序是在docker中启动的，而客户端是在宿主机中启动，于是，出现socket的链接问题，错误111.

可以尝试在启动Docker容器时使用`--net=host`参数指定容器使用宿主机网络，这样应该可以解决通信问题。

> 是pip安装的版本较低

pip的版本可以通过`pip install --upgrade pip`来解决。
另外可以尝试使用下面命令来下载最新的whl包：
```bash
wget http://guest@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl
```

**Comment by john81529** [comment]
嗯。我尝试一下。关于pip的问题，我是pip9是最新的版本了。然后，whl的包，我的确不是使用wget方式下载的，也许这样下载的文件会有错误。谢谢你的回答。

**Comment by john81529** [comment]
我用pip安装paddle的gpu版本，是0.10.5的，然后运行deepspeech,出现错误：
I1211 11:02:23.221732 14016 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
[INFO 2017-12-11 11:02:23,301 layers.py:2539] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-11 11:02:23,301 layers.py:3062] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
Traceback (most recent call last):
  File "deploy/demo_server.py", line 224, in <module>
    main()
  File "deploy/demo_server.py", line 220, in main
    start_server()
  File "deploy/demo_server.py", line 165, in start_server
    share_rnn_weights=args.share_rnn_weights)
  File "/home/yyh/DeepSpeech/deploy/../model_utils/model.py", line 46, in __init__
    rnn_layer_size, use_gru, share_rnn_weights)
  File "/home/yyh/DeepSpeech/deploy/../model_utils/model.py", line 307, in _create_network
    share_rnn_weights=share_rnn_weights)
  File "/home/yyh/DeepSpeech/deploy/../model_utils/network.py", line 263, in deep_speech_v2_network
    index_range_datas=index_range_datas)
  File "/home/yyh/DeepSpeech/deploy/../model_utils/network.py", line 165, in conv_group
    index_range_data=index_range_datas[0])
  File "/home/yyh/DeepSpeech/deploy/../model_utils/network.py", line 43, in conv_bn_layer
    scale_sub_region = paddle.layer.scale_sub_region(
AttributeError: 'module' object has no attribute 'scale_sub_region'

**Comment by john81529** [comment]
而用wget模式下载，出现这样的错误：
wget http://guest@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl
--2017-12-11 10:56:31--  http://guest@paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/.lastSuccessful/paddlepaddle-0.10.0-cp27-cp27mu-linux_x86_64.whl
正在解析主机 paddleci.ngrok.io (paddleci.ngrok.io)... 52.15.62.13, 2600:1f16:59e:b200:cd2c:dd37:7e0c:bb3e
正在连接 paddleci.ngrok.io (paddleci.ngrok.io)|52.15.62.13|:80... 失败：连接超时。
正在连接 paddleci.ngrok.io (paddleci.ngrok.io)|2600:1f16:59e:b200:cd2c:dd37:7e0c:bb3e|:80... 失败：网络不可达。

**Comment by john81529** [comment]
我想说，你们工作环境是什么样的，可以说说吗？我想全面模仿你们的环境，应该可以成功吧。

**Comment by Xreki** [comment]
你是下载最新的whl失败吗，直接通过浏览器可以下载吗？

**Comment by john81529** [comment]
可以啊，然后就出现官网上描述的错误，然后按照官网上的方法依然无法解决。

**Comment by john81529** [comment]
那个错误，再次出现：
Install the project...
-- Install configuration: "Release"
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/share/doc/mkldnn/LICENSE
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/lib/libmkldnn.so.0.11.0
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/lib/libmkldnn.so.0
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/lib/libmkldnn.so
-- Set runtime path of "/home/yyh/paddle_gpu/build/third_party/install/mkldnn/lib/libmkldnn.so.0.11.0" to ""
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/include/mkldnn.h
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/include/mkldnn_types.h
-- Installing: /home/yyh/paddle_gpu/build/third_party/install/mkldnn/include/mkldnn.hpp
[ 28%] Completed 'extern_mkldnn'
[ 28%] Built target extern_mkldnn
[ 28%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_table_apply.cu.o
paddle/framework/CMakeFiles/proto_desc.dir/build.make:86: recipe for target 'paddle/framework/CMakeFiles/proto_desc.dir/op_desc.cc.o' failed
make[2]: *** [paddle/framework/CMakeFiles/proto_desc.dir/op_desc.cc.o] Error 1
make[2]: *** 正在等待未完成的任务....
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_perturbation_util.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_aggregate.cu.o
CMakeFiles/Makefile2:8852: recipe for target 'paddle/framework/CMakeFiles/proto_desc.dir/all' failed
make[1]: *** [paddle/framework/CMakeFiles/proto_desc.dir/all] Error 2
make[1]: *** 正在等待未完成的任务....
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_matrix.cu.o
[ 29%] Linking CXX executable selected_rows_functor_test
[ 29%] Built target selected_rows_functor_test
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_sparse.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_cnn.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_lstm.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_top_k.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_batch_transpose.cu.o
Scanning dependencies of target nccl_test
[ 29%] Linking CXX executable nccl_test
[ 29%] Built target nccl_test
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_batch_norm.cu.o
[ 29%] Building NVCC (Device) object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/paddle_cuda_generated_hl_cuda_sequence.cu.o
Scanning dependencies of target transform_test
[ 29%] Linking CXX executable transform_test
[ 29%] Built target transform_test
Scanning dependencies of target selected_rows_functor_gpu_test
[ 29%] Linking CXX executable selected_rows_functor_gpu_test
Scanning dependencies of target paddle_cuda
[ 29%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_time.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_math.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_cpu_functions.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_avx_functions.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_cuda_cublas.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_warpctc_wrap.cc.o
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_cuda_cudnn.cc.o
[ 30%] Built target selected_rows_functor_gpu_test
[ 30%] Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_cuda_device.cc.o
[ 30%] Linking CXX static library libpaddle_cuda.a
cpplint: Checking source code style
Done processing src/hl_time.cc
Done processing src/hl_cpu_functions.cc
Done processing src/hl_math.cc
Done processing src/hl_avx_functions.cc
Done processing include/hl_time.h
Done processing include/hl_warpctc_wrap.h
Done processing include/hl_sequence.h
Done processing include/hl_cuda_cublas.h
Done processing include/hl_batch_transpose.h
Done processing include/hl_avx_functions.h
Done processing include/hl_sparse.h
Done processing include/hl_functions.h
Done processing include/hl_cuda_cudnn.h
Done processing include/hl_activation_functions.h
Done processing include/hl_base.h
Done processing include/stub/hl_cuda_cudnn_stub.h
Done processing include/stub/hl_cuda_stub.h
Done processing include/stub/hl_cuda_cublas_stub.h
Done processing include/stub/hl_cnn_stub.h
Done processing include/stub/hl_lstm_stub.h
Done processing include/stub/hl_sequence_stub.h
Done processing include/stub/hl_aggregate_stub.h
Done processing include/stub/hl_sparse_stub.h
Done processing include/stub/hl_matrix_stub.h
Done processing include/hl_aggregate.h
Done processing include/hl_cuda.h
Done processing include/hl_lstm.h
Done processing include/hl_table_apply.h
Done processing include/hl_gpu.h
Done processing include/hl_top_k.h
Done processing include/hl_matrix.h
Done processing include/hl_cnn.h
Done processing src/hl_warpctc_wrap.cc
Done processing src/hl_cuda_cublas.cc
Done processing src/hl_cuda_cudnn.cc
Done processing src/hl_cuda_device.cc
Total errors found: 0
[ 30%] Built target paddle_cuda
Makefile:160: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by john81529** [comment]
请问，你们的安装中，有没有docker版本的paddlepaddle和源码编译的paddlepaddle在一台电脑上？我在网上发现类似的问题，他是因为有一个软件导致的。

**Comment by Yancey1989** [comment]
@john81529 
> 我用pip安装paddle的gpu版本，是0.10.5的，然后运行deepspeech,出现错误：

可以尝试重新运行`pip install paddlepaddle-gpu`，我们最近更新了pypi上的whl包。

> 请问，你们的安装中，有没有docker版本的paddlepaddle和源码编译的paddlepaddle在一台电脑上

不是很理解这个问题，cuda和cudnn都是封装在Docker镜像里，和本地环境无关。另外可以直接使用PaddlePaddle提供的Docker镜像，并使用nvidia-docker来运行：
```bash
> nvidia-docker run --rm -it -v$PWD:/work paddlepaddle/paddle:latest-gpu /bin/bash
```

**Comment by john81529** [comment]
恩。这些问题已经在另一个issue中解决了，麻烦了。
