### ISSUE TITLE
本地Mac下运行paddlepaddle程序出现各种'module' object has no attribute 

### ISSUE THREAD

**Issue by yzx1992** [PaddlePaddle/Paddle#6410]
通过brew install python , pip install paddlepaddle ,运行http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/index_cn.html  房屋预测的代码，会出现 如下错误：

I1208 11:33:54.735730 3076465600 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
Traceback (most recent call last):
  File "/Users/zhenxuye/paddle_project/housing.py", line 13, in <module>
    parameters=paddle.dataset.uci_housing.model(),
AttributeError: 'module' object has no attribute 'model'

问题1: 本地 /usr/local/lib/python2.7/site-packages/paddle/v2/dataset/uci_housing.py存在，但是并没有model()函数。

问题2: 第8行代码` y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear()) 
` 中，用pycharm IDE layer 函数同样能过进入，但是fc会出现，Cannot find reference 'fc' in layer.py

**Comment by ranqiu92** [comment]
可能是版本问题，建议试下最新的paddle

**Comment by yzx1992** [comment]
那问题2呢？新版的layer.py下，也是找不到fc()，求助。

**Comment by typhoonzero** [comment]
pypi上的whl包比较老了最近会更细下～
