### ISSUE TITLE
官网首页的例子，就没跑起来，初始化报错

### ISSUE THREAD

**Issue by yzy8788** [PaddlePaddle/Paddle#6424]
代码：`paddle.init(use_gpu=False, trainer_count=1)`
报错内容：ValueError: invalid literal for int() with base 10: ''
系统环境：centos7+Python 2.7.5

**Comment by luotao1** [comment]
duplicated with #6410

**Comment by ranqiu92** [comment]
可能是环境 或 版本问题，可以试下用最新的源码进行安装paddle，安装前先卸载原paddle。

**Comment by yzy8788** [comment]
@ranqiu92 
pip也升级到最新版了
paddlepaddle卸载后，重新 pip install paddlepaddle 安装了依然是上面的错误。
看报错信息，好像是空字符串不能转成int，是不是某个必要的int参数没传啊？

**Comment by ranqiu92** [comment]
可有用最新的源码编译安装
