### ISSUE TITLE
paddlepaddle预测可以提供置信度吗?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6425]
比如我在做手写数字识别时,在预测结果是,能否同时输出置信度?

**Comment by ranqiu92** [comment]
你是指 输出 softmax 的概率吗？ paddle可以将 网络的某个layer的值进行输出。

**Comment by yeyupiaoling** [comment]
@ranqiu92 比如
```
probs = paddle.infer(
    output_layer=predict, parameters=parameters, input=test_data)
```
我希望它获得预测值时，同时得到这个预测值的置信度

**Comment by ranqiu92** [comment]
这里只能得到概率，其他的量应该需要自己写计算过程。

**Comment by yeyupiaoling** [comment]
@ranqiu92 好的,我研究研究,因为识别出来的结果至少要告知用户这个结果的可信度是多少.或者说有没有识别到结果.
