### ISSUE TITLE
官网docker 运行报错 docker.paddlepaddle.org/book   例子运行 初始化 报错 The kernel appears to have died. It will restart automatically.

### ISSUE THREAD

**Issue by rongchuang** [PaddlePaddle/Paddle#6431]
官网docker 运行报错 to 官网docker 运行报错 docker.paddlepaddle.org/book 例子运行 初始化 报错 The kernel appears to have died. It will restart automatically              系统是ubantu 16.04    docker版本是17.11.0-ce 。 运行代码是 paddle.init(use_gpu=False, trainer_count=1)

**Comment by yeyupiaoling** [comment]
你的电脑是否支持AVX指令集,判断是否支持命令([地址](http://paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/docker_install_cn.html)):
`if cat /proc/cpuinfo | grep -i avx; then echo Yes; else echo No; fi`

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时打开它。
