### ISSUE TITLE
在运行例子时 报错  Illegal instruction (core dumped),

### ISSUE THREAD

**Issue by rongchuang** [PaddlePaddle/Paddle#6432]
python housing.py 

Illegal instruction (core dumped)

**Comment by dzhwinter** [comment]
请提供运行环境，报错堆栈信息。只提供core dumped无法帮你debug。

**Comment by rongchuang** [comment]
ubantu  16.04    ，  python2.7.12，      （pip install paddlepaddle   安装的）。
执行官网例子就报错（测试了下， 执行到paddle.init(use_gpu=False, trainer_count=1 这里就会报错）
谢谢

**Comment by rongchuang** [comment]
root@rong-HP-EliteBook-8440p:~/workspace# python housing.py 
非法指令 (核心已转储)
root@rong-HP-EliteBook-8440p:~/workspace# ls
fit_a_line.tar  housing.py
root@rong-HP-EliteBook-8440p:~/workspace#

**Comment by dzhwinter** [comment]
使用全新的ubuntu16.04，系统自带python2.7.12，可正常运行，不能复现该问题。

python interpreter有问题。建议使用docker，或使用conda安装python

**Comment by dzhwinter** [comment]
复现环境：
Linux e1aa480a6522 4.10.0-40-generic #44~16.04.1-Ubuntu
python 2.7.12

**Comment by rongchuang** [comment]
docker  also have the same : 
root@rong-HP-EliteBook-8440p:~/workspace# docker run -it -v ~/workspace:/workspace paddlepaddle/paddle:latest /bin/bash
root@f46deba50f5f:/# cd workspace/
root@f46deba50f5f:/workspace# python housing.py 
Illegal instruction (core dumped)
root@f46deba50f5f:/workspace#

**Comment by dzhwinter** [comment]
另外，ilegal instruction是因为python编译二进制时候选项没设置错误，ubuntu16.04自带的python不会有这个问题（CI机器是16.04环境）。

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.

**Comment by bluebird138** [comment]
我这边新安装的Ubuntu也遇到以上的问题。
sudo apt-get install python-pip
pip install paddlepaddle
python housing.py
提示：非法指令 (核心已转储)
Ubuntu 16.04.3 LTS, Python 2.7
