### ISSUE TITLE
There is no documentation for paddle.inference Tensor in the official documentation of PaddlePaddle.

### ISSUE THREAD

**Issue by chaitanya-srikanth** [PaddlePaddle/Paddle#64325]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/inference/Tensor_en.html

### 请提出你的建议 Please give your suggestion

It'll be helpful if the input structure and the output structure for this class is explained so it can be used.

**Comment by 2742195759** [comment]
好的，感谢反馈，这边会反馈这个问题给负责的同学。
