### ISSUE TITLE
补全rms_norm算子CPU实现

### ISSUE THREAD

**Issue by cqulilujia** [PaddlePaddle/Paddle#64353]
### 需求描述 Feature Description

注意到 #60848 PR中将rms_norm算子从纯推理版本增加到训练算子，补全了反向实现，但是未添加CPU实现。算子评审中也提到了这个问题，但是后续PR中并未有实现。llama等模型中rms_norm的使用频率很高，在使用CPU调试时会用到融合版本的实现，请帮忙补全。

**Comment by vivienfanghuagood** [comment]
我们会安排这个算子的CPU版本实现。

**Comment by vivienfanghuagood** [comment]
https://github.com/PaddlePaddle/Paddle/pull/63165 CPU的rms_norm之前已经合入。
