### ISSUE TITLE
shared layer

### ISSUE THREAD

**Issue by ZhongpuXia** [PaddlePaddle/Paddle#6436]
how to share a layer in paddle? for example:
x1 = paddle.layer.data(name='x1', type=dense_vector(2))
x2 = paddle.layer.data(name='x2', type=dense_vector(2))

how to define a shared_layer, to get results for different inputs?
y1 = shared_layer(x1)
y2 = shared_layer(x2)

**Comment by dzhwinter** [comment]
Just use the same name of parameter, then paddle will share the parameter between layers. 
We have examples in our repo of https://github.com/PaddlePaddle/models .

**Comment by dzhwinter** [comment]
And, the input is data, it does not have any concept of shared or not. You can define a shared layer(with same name).
