### ISSUE TITLE
DSSM模型，PairWise Rank任务的评估方式

### ISSUE THREAD

**Issue by fanfannothing** [PaddlePaddle/Paddle#6437]
【描述】目前在DSSM模型中，Pairwise Rank任务，缺少评价方式。
因为DSSM中的pairwise任务的precition=left-score-right-score，而对于这种操作，目前的auc不支持评估。
请问，是否有其它的合理的评价方式，以及如何修改，谢谢！
@lcy-seso 

【DSSM】中代码如何
319         #left_score = paddle.layer.dot_prod(input1=semantics[0], input2=semantics[1])
320         #right_score = paddle.layer.dot_prod(input1=semantics[0], input2=semantics[2])

326         if not self.is_infer:
327             # rank cost
328             cost = paddle.layer.rank_cost(left_score, right_score, label=label)
多谢

**Comment by dzhwinter** [comment]
>目前的auc不支持评估

没理解为什么不支持，prediction 和label构造二分类结果，需要手写转换label的部分，输入到auc。

另外pairwise也可以用ndcg等传统方法来做，拿到prediction后可以算到ndcg。这是否是你想要的评价方式？

**Comment by fanfannothing** [comment]
> 没理解为什么不支持，prediction 和label构造二分类结果，需要手写转换label的部分，输入到auc。
我的输出是leftscore-rightscore，然后再接一下rank_loss；
不太清楚你说的手写转换label是指啥？

**Comment by dzhwinter** [comment]
抱歉没说清楚，手写转换label是指 
label = left - right
score = leftscore  - rightscore
auc(input=score, label=label)

**Comment by fanfannothing** [comment]
好的。谢谢 @dzhwinter 我先试试，有进展再在上面贴

**Comment by fanfannothing** [comment]
@dzhwinter 好像现在auc不支持leftscore-rightscore的形式。
请问有其它方法可解决吗？

**Comment by typhoonzero** [comment]
Closing due to low activity.

**Comment by bbgasj** [comment]
排序的指标可以参考MRR、NDCG、ERR等
