### ISSUE TITLE
训练的时候慢可以理解但是预测的时候太慢了,工程具体应用的例子有没有大神给个教程？

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#6439]
训练的时候慢可以理解但是预测的时候太慢了,工程具体应用的例子有没有大神给个教程？

**Comment by chengduoZH** [comment]
@466821202  你是在用capi做预测吗？ 这里有使用capi的例子：https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference
