### ISSUE TITLE
统一MKL的宏定义命名

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#6452]
在看fluid相关code时发现，现在使用的宏定义是PADDLE_**WITH**_CUDA这样的。
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/memory/detail/buddy_allocator.cc#L179

但是以前MKL相关的使用的是`PADDLE_USE_MKLML`和`PADDLE_USE_MKLDNN`，与`WITH`的不一致，需要统一下命名。

**Comment by QiJune** [comment]
@tensor-tang A reminder: if you are looking on porting MKL to fluid, please refer to #6403 

We may need `MKLPlace` derived from `CPUPlace` and `MKLDeviceContext` derived from `CPUDeviceContext` to implement computing in MKL library.

`Computing Library` --  `Place`-- `DeviceContext` -- `Kernel`, these concepts are one-to-one correspondence

**Comment by tensor-tang** [comment]
Thanks @QiJune it's helpful.

Actually I am planning to add some kind of `MKLPlace` concept, glad to see it meets you point.
