### ISSUE TITLE
DeepFM demo运行问题

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#6453]
我运行demo，报以下的错误
`I1211 14:29:43.642339 31648 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1 
Traceback (most recent call last):
  File "train.py", line 107, in <module>
    train()
  File "train.py", line 62, in train
    model = DeepFM(args.factor_size)
  File "/XXX/models/deep_fm/network_conf.py", line 39, in DeepFM
    fm_param_attr=paddle.attr.Param(name="DenseFeatFactors"))
  File "/XXX/models/deep_fm/network_conf.py", line 10, in fm_layer
    second_order = paddle.layer.factorization_machine(
AttributeError: 'module' object has no attribute 'factorization_machine'
`
使用的是paddlepaddle-0.10.0-cp27-cp27m-linux_x86_64.whl，这个版本的包，是不是这个版本还不支持？

**Comment by will-am** [comment]
这个安装的是老版本，没有factorization_machine，可以用pip安装最新的版本，现在是0.11.0。

安装前应该把旧的删干净`pip uninstall paddlepaddle`, 要是还安过更老的paddle的话还要试试
`pip uninstall py_paddle` 和`pip uninstall paddle`

**Comment by windy444** [comment]
好的，我试试

**Comment by will-am** [comment]
现在pypi上0.11.0还只有mac的版本，linux的貌似还在生成中，我问下，要是在linux下运行得稍等下

**Comment by will-am** [comment]
我刚问了下，linux版本的正在生成中，预计会在后天之前上传完毕。

**Comment by windy444** [comment]
好的，那先等等

**Comment by will-am** [comment]
linux的最新版已经发布，可以安装了：
`
# CPU version
pip install paddlepaddle==0.11.0
# GPU version
pip install paddlepaddle_gpu==0.11.0
`

**Comment by windy444** [comment]
@will-am 出现如下问题

pip install paddlepaddle==0.11.0
Downloading/unpacking paddlepaddle==0.11.0
  http://pypi.douban.com/simple/paddlepaddle/0.11.0 uses an insecure transport scheme (http). Consider using https if pypi.douban.com has it available
  http://pypi.douban.com/simple/paddlepaddle/ uses an insecure transport scheme (http). Consider using https if pypi.douban.com has it available
  Could not find any downloads that satisfy the requirement paddlepaddle==0.11.0
Cleaning up...
No distributions at all found for paddlepaddle==0.11.0
Storing debug log for failure in /home/work/.pip/pip.log

**Comment by will-am** [comment]
这个是因为pip配置成了从pypi.douban.com内部镜像获取，没有从官网获取，可以手动从官网下载安装：
https://pypi.python.org/pypi?%3Aaction=search&term=paddlepaddle&submit=search
