### ISSUE TITLE
Need documentation about the release binaries

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#6457]
Currently, we only push a part of binary distributions to docker hub and pypi: 

docker hub: 

- `latest` tag for cpu
- `latest-gpu` for gpu

pypi:

- cpu
- gpu
- macos

In the documents, we need to inform users that if they want to use versions like below, they should build by themselves:

- build with higher CUDA versions like CUDA 8.0, CUDA 9.0
- build with higher cuDNN versions like cuDNN 7.0
- build without AVX support
- build with OpenBlas instead of MKL
- build with fault-tolerant distributed training support `WITH_GOLANG`

**Comment by luotao1** [comment]
Does [releasing_process.md](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/releasing_process.md)  solve this issue?

**Comment by typhoonzero** [comment]
Yes, I'll close this issue now.
