### ISSUE TITLE
mac os编译时一些子依赖库无法访问的问题

### ISSUE THREAD

**Issue by aooxin** [PaddlePaddle/Paddle#64589]
### 问题描述 Issue Description

在mac os使用cmake时，会遇到部分包无法访问的问题，其中有部分看起来要从gitlab访问的私有库，如https://gitlab.mpcdf.mpg.de/mtr/pocketfft.git/
fatal: unable to access 'https://github.com/Cyan4973/xxHash.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
fatal: clone of 'https://github.com/Cyan4973/xxHash.git' into submodule path '/paddle/third_party/xxhash' failed
Failed to clone 'third_party/xxhash'. Retry scheduled
Cloning into '/paddle/third_party/zlib'...
fatal: unable to access 'https://github.com/madler/zlib.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
fatal: clone of 'https://github.com/madler/zlib.git' into submodule path '/paddle/third_party/zlib' failed
Failed to clone 'third_party/zlib'. Retry scheduled
Cloning into '/paddle/third_party/pocketfft'...
fatal: unable to access 'https://gitlab.mpcdf.mpg.de/mtr/pocketfft.git/': gnutls_handshake() failed: The TLS connection was non-properly terminated.
fatal: clone of 'https://gitlab.mpcdf.mpg.de/mtr/pocketfft.git' into submodule path '/paddle/third_party/pocketfft' failed
Failed to clone 'third_party/pocketfft' a second time, aborting
CMake Error at cmake/third_party.cmake:58 (message):
  Failed to update submodule, please check your network !
Call Stack (most recent call first):
  CMakeLists.txt:607 (include)

-- Configuring incomplete, errors occurred!
See also "/paddle/build/CMakeFiles/CMakeOutput.log".
See also "/paddle/build/CMakeFiles/CMakeError.log".

### 版本&环境信息 Version & Environment Information

paddleversion：develop（cpu）

**Comment by aooxin** [comment]
补充一下我使用的命令：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/macos-compile-make.html
完全按照这个文档的macos docker编译流程
python==3.12

**Comment by aooxin** [comment]
我把所有的库补充上来，有gitlab的目前已经无法访问了

Library | Download Link
-- | --
third_party/absl | https://github.com/abseil/abseil-cpp.git
third_party/brpc | https://github.com/apache/brpc.git
third_party/cccl | https://github.com/NVIDIA/cccl.git
third_party/cryptopp | https://github.com/weidai11/cryptopp.git
third_party/cryptopp-cmake | https://github.com/noloader/cryptopp-cmake.git
third_party/cub | https://github.com/NVIDIA/cub.git
third_party/cutlass | https://github.com/NVIDIA/cutlass.git
third_party/dlpack | https://github.com/dmlc/dlpack.git
third_party/eigen3 | https://gitlab.com/libeigen/eigen.git
third_party/flashattn | https://github.com/PaddlePaddle/flash-attention.git
third_party/gflags | https://github.com/gflags/gflags.git
third_party/glog | https://github.com/google/glog.git
third_party/gloo | https://github.com/ziyoujiyi/gloo.git
third_party/gtest | https://github.com/google/googletest.git
third_party/jitify | https://github.com/NVIDIA/jitify.git
third_party/leveldb | https://github.com/google/leveldb.git
third_party/nlohmann_json | https://github.com/nlohmann/json.git
third_party/onednn | https://github.com/oneapi-src/oneDNN.git
third_party/openblas | https://github.com/xianyi/OpenBLAS.git
third_party/pocketfft | https://gitlab.mpcdf.mpg.de/mtr/pocketfft.git
third_party/protobuf | https://github.com/protocolbuffers/protobuf.git
third_party/pybind | https://github.com/pybind/pybind11.git
third_party/rocksdb | https://github.com/Thunderbrook/rocksdb
third_party/snappy | https://github.com/google/snappy.git
third_party/threadpool | https://github.com/progschj/ThreadPool.git
third_party/utf8proc | https://github.com/JuliaStrings/utf8proc.git
third_party/warpctc | https://github.com/baidu-research/warp-ctc.git
third_party/warprnnt | https://github.com/PaddlePaddle/warp-transducer.git
third_party/xbyak | https://github.com/herumi/xbyak.git
third_party/xxhash | https://github.com/Cyan4973/xxHash.git
third_party/zlib | https://github.com/madler/zlib.git

**Comment by GuoxiaWang** [comment]
请检查一下你网络是否畅通，我这边是可以直接访问你上面列出来的 third_party github的。

**Comment by risemeup1** [comment]
这个就是代理问题

**Comment by risemeup1** [comment]
export no_proxy=bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn,gitlab.com,gitlab.mpcdf.mpg.de
试试

**Comment by aooxin** [comment]
> export no_proxy=bcebos.com,apiin.im.baidu.com,gitee.com,aliyun.com,.baidu.com,.tuna.tsinghua.edu.cn,gitlab.com,gitlab.mpcdf.mpg.de 试试

明白了多谢！！！
