### ISSUE TITLE
paddlepaddle==2.6.1的版本无法正常安装编译paddlex

### ISSUE THREAD

**Issue by jiaqi100** [PaddlePaddle/Paddle#64616]
### 问题描述 Issue Description

paddlepaddle==2.6.1的版本无法正常安装编译paddlex
另外，paddlepaddle==2.4.0无法导入from paddle.base.framework import in_dygraph_mode，没有“paddle.base”

### 版本&环境信息 Version & Environment Information

NONE

**Comment by ronny1996** [comment]
你好，请问你使用的paddlex是什么版本，需要使用配套版本的paddle

**Comment by jiaqi100** [comment]
你好，我是直接在aistudio中下载的。当paddlepaddle==2.6.1，在使用“pip install paddlex”时，无法正确下载并编译。

**Comment by ronny1996** [comment]
你好，方便贴下报错的信息吗？另外可以尝试下载最新的 PaddleX 从源码安装下

**Comment by jiaqi100** [comment]
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)

**Comment by jiaqi100** [comment]
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--ServerApp.iopub_data_rate_limit`.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)
安装失败，是否可以提供新的源码安装和编译代码

**Comment by jiaqi100** [comment]
IOPub data rate exceeded.
The Jupyter server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
--ServerApp.iopub_data_rate_limit.

Current values:
ServerApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
ServerApp.rate_limit_window=3.0 (secs)
安装失败，是否可以提供新的源码安装和编译代码
、
