### ISSUE TITLE
非image的cnn数据预处理

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/Paddle#6463]
我的数据是每秒一个x,y,z方向的传感器数据，每条数据用0或1来表示是否静止还是运动，我用每90s的连续数据组合成 90*3的数组来作为每份数据输入，来进行二分类问题学习。我需要如何构建对应的cnn的input。 我参考教程主要是图像分类cnn处理 simple_img_conv_pool， 我这种非图像的二维数据应该怎样构建cnn网络？ 谢谢！

**Comment by Canpio** [comment]
没有特别理解您的意思。您的数据是否是每条样本只有[x, y, z]这三个值？也就是说，90s的数据其实是一个90*3的矩阵？

**Comment by realsnake** [comment]
每条样本是[x,y,z,label], input是90*3的矩阵，90s的xyz。

**Comment by Canpio** [comment]
这样的话您的需求其实是一个一维的卷积，可以使用我们的sequence_conv。
使用方法可以参考我们的文本分类任务，里面有两种模型的实现，其中一种就是用了sequence_conv：
https://github.com/PaddlePaddle/models/tree/develop/text_classification
应该说和你的需求是非常相似的，除了在两个地方可能存在区别：
1. 文本分类里需要先通过embedding将单词转化成向量，你直接就已经是向量了。
2. 文本分类中每一个序列（句子）是边长的，而你是定长的固定90s

**Comment by realsnake** [comment]
多谢！
