### ISSUE TITLE
官网页面有链接失效

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6468]
http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/k8s/k8s_cn.html  该页面中有几个链接失效。

![1](https://user-images.githubusercontent.com/31875089/33822913-2c259a30-de94-11e7-800d-44254dd5cbaa.jpg)

**Comment by luotao1** [comment]
@typhoonzero @Yancey1989 
k8s 网页的链接失效能帮忙看一下么？

**Comment by Yancey1989** [comment]
Sure, will do that.
