### ISSUE TITLE
Use a standard RPC library instead of manual implement it.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#647]
## background

In Paddle, we manually implement an RPC library for `PServer <=> PClient` communication. The  [ProtoServer](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/ProtoServer.h) is the base class for RPC server, the [BaseClient](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/BaseClient.h) is the base class for RPC client. The code [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/ParameterServer2.cpp#L71) is used for register method in PServer. 

The pros and cons are listed below:

### pros

* The performance is well because the implementation is very thin and fine-tuned. It was written from raw TCP stack and raw RDMA stack.

### cons

* It is not very stable, even in HPC cluster. The reasons are:
   * It use send receive IOVs, and this [API](http://man7.org/linux/man-pages/man2/readv.2.html) in Linux use a 32bit length. It may be overflow in a huge neural network with 1 or 2 PServers.
   * It did not write any fault tolerance job. Write any illegal data in buffer or network has some error will cause whole cluster process die.

* It doesn't provide `on_disconnect` API or discover the disconnect process. Currently, one disconnect event will make every process die.

* It doesn't provide `Authentication` API, which is necessary for cluster service.

### conclusion

To use a standard PROTO RPC library will **make cluster API easier to expose and easier to write new logic code, but it may harm current Paddle network performance**.

So, should we change the Paddle RPC by using some standard RPC library?

Please thumbs up/down this issue to vote!

**Comment by reyoung** [comment]
The possible RPC library will list below, and I will give my personal thoughts about them in several dimensions.

* Easy to use
* Support RDMA or not
* Performance Good/Bad/Average
* Support Authentication or not
* etc.

**Comment by wangkuiyi** [comment]
我想了一会儿。搜了不少 grpc, thrift 和 golang rpc 的原理介绍和比较。实际情况比我想想得复杂多了，比如grpc是基于http2的，有他独到的优势。但是[傻逼使用方式](https://groups.google.com/forum/#!topic/grpc-io/JeGybvbz8nc)下，性能比thrift慢一个数量级——我们不能傻逼模式使用。这些测试导致我怀疑这恐怕不是一个可以通过大家投票得出结论的事儿。

目前我看到的比较靠谱的也是最新的是[这篇文章](https://open.dgraph.io/post/rpc-vs-grpc)。其论点是：应该用Go语言来写服务（我之前在腾讯做的peacock系统确实是用C写Gibbs sampling，用Go写server），用grpc，但是不用google protobuf作为wire format，而是使用 flatbuffers。

这个路子看上去是可以保证稳定性的，但是修改很大呀。不知道对性能有多大影响。另外，不知道优化完备我们自己的rpc实现的工程开销有多大——不知道是否要要像grpc那样考虑各种极端情况，还是goalng rpc那样两百行代码得了。

**Comment by reyoung** [comment]
# [sofa-rpc](https://github.com/baidu/sofa-pbrpc)

## Easy to use

The [code](https://github.com/baidu/sofa-pbrpc/blob/master/sample/echo/client_async.cc) using SOFA-RPC is quite easy, and SOFA-RPC is using Protobuf 2 which fits Paddle well.

But the SOFA-RPC  [depends on boost](https://github.com/baidu/sofa-pbrpc/issues/140), and using boost::asio as the low-level network communication library. To use SOFA-RPC means we must introduce boost library as a dependency.

## Support RDMA or not

No.

## Performance Good/Bad/Average

I think the performance about SOFA-RPC should be good(because the boost::asio is good), but not so many experiments have been done.

The official performance test is [here](https://github.com/baidu/sofa-pbrpc/wiki/%E6%80%A7%E8%83%BD), but it lacks the performance report about sending/receiving a huge message. 

## Support Authentication or not

No.

**Comment by reyoung** [comment]
# gRPC

## Easy to use

### Pros
* gRPC has lots of language bindings. 
* gRPC is well-documented.

### Cons

* gRPC will force paddle using protobuf 3.


## Support RDMA or not

No.

## Performance Good/Bad/Average

Because gRPC use `http2` as protocol, the performance is not very well but performance in the neural network should be tested in large message communication after warming up.

There some experiments need to do.

## Support Authentication or not

Yes.

**Comment by reyoung** [comment]
Thrift or arvo may be a good choice, but Paddle is using protobuf, so they are not considered yet.
