### ISSUE TITLE
Survey of NCCL multi node

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#6471]
result of the Survey:
https://github.com/PaddlePaddle/Paddle/wiki/NCCL2-Survey

**Comment by jacquesqiao** [comment]
http://www.sohu.com/a/198655698_465975

**Comment by typhoonzero** [comment]
nccl2 API seems similar to MPI API, in that case speed may be the main concern.

**Comment by jacquesqiao** [comment]
@typhoonzero yes, nccl is mainly designed to speed up multi GPU training, it is Optimized to achieve high bandwidth over PCIe and NVLink high-speed interconnect and 
Support for RDMA over Converged Ethernet (RoCE) network protocol for multi-node scaling.
