### ISSUE TITLE
cuda是11.8，但自检程序报错说是10.2，导致cudnn不对，进而导致不能运行。找不到合适的paddle版本的离线下载方式。

### ISSUE THREAD

**Issue by shelly-angel** [PaddlePaddle/Paddle#64756]
### 问题描述 Issue Description

Running verify PaddlePaddle program ...
W0530 16:48:04.292114  6064 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.8, Runtime API Version: 10.2
W0530 16:48:04.292114  6064 dynamic_loader.cc:276] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\utils\install_check.py", line 266, in run_check
    _run_static_single(use_cuda, use_xpu, use_npu)
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\utils\install_check.py", line 170, in _run_static_single
    exe.run(startup_prog)
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\fluid\executor.py", line 1299, in run
    six.reraise(*sys.exc_info())
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\six.py", line 719, in reraise
    raise value
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\fluid\executor.py", line 1285, in run
    res = self._run_impl(
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\fluid\executor.py", line 1510, in _run_impl
    return self._run_program(
  File "C:\ProgramData\anaconda3\envs\paddle-gpu\lib\site-packages\paddle\fluid\executor.py", line 1607, in _run_program
    self._default_executor.run(program.desc, scope, 0, True, True,
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:303)

### 版本&环境信息 Version & Environment Information

paddle version: 2.3.2-gpu
OS: windows server 2016
cuda: 11.8
cudnn: 8.6.0
python: 3.10
paddle安装方式--离线安装：（机器没法联网 只能离线安装）
命令： python -m pip install D:\download\paddlepaddle_gpu-2.3.2-cp310-cp310-win_amd64.whl
下载链接：https://paddle-wheel.bj.bcebos.com/2.3.2/windows/windows-gpu-cuda10.2-cudnn7.6.5-mkl-avx-vs2017/paddlepaddle_gpu-2.3.2-cp310-cp310-win_amd64.whl

用1链接的三个方法检查cuda、cudnn版本，结果均显示11.8, 8.6.0; 虽然查询到了2链接的方法，替换cudnn8为cudnn7，但是我觉得这样不对，毕竟我确实是11.8，pytorch框架跑着没有问题。路径也已经检查过没有问题（因为只安装了1个11.8）。
1.  https://dataartist.blog.csdn.net/article/details/128604798
2. https://blog.csdn.net/kieven2008/article/details/120410650
当我把paddle下载链接复制下来那一刻，发现下载的paddle版本可能有问题，但是我找不到适合我的离线下载的版本. 同时uninstall了2.3.2, 下载了2.5.0来安装，但是仍然不行。（https://paddle-wheel.bj.bcebos.com/2.5.0/windows/windows-gpu-cuda11.8-cudnn8.6.0-mkl-avx-vs2019/paddlepaddle_gpu-2.5.0.post118-cp310-cp310-win_amd64.whl）
所以如果是我猜测的这个问题，我就想要一个3.10-11.8-2.3.2的离线下载地址。可以有吗？
![cuda信息](https://github.com/PaddlePaddle/Paddle/assets/58506391/5b54c627-04e6-4bbf-8db8-b9695c2eb258)
![e85cffa8280127ee3e1aa885b48e566d](https://github.com/PaddlePaddle/Paddle/assets/58506391/3424b144-69eb-41f3-9c97-6a9d1c0588cd)

**Comment by shelly-angel** [comment]
或者有什么其他方法也可以，不限于更换版本，只是不方便更换cuda版本。此外，cuda11.4paddle的只能自己编译吗？因为我编译不出来(报一推错)，所以可以用paddle11.2 或者 paddle11.6的兼容11.4吗？

**Comment by danleifeng** [comment]
您好，有试过直接安装cuda11.8版本的whl包吗
![image](https://github.com/PaddlePaddle/Paddle/assets/52735331/4860cc71-9107-4549-bc5e-e30cb5ba5b8c)
https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/install/pip/windows-pip.html

**Comment by shelly-angel** [comment]
首先，这个安装不算吗？python -m pip install D:\download\paddlepaddle_gpu-2.3.2-cp310-cp310-win_amd64.whl； 
或者，您的意思是安装2.6.1版本的？我安装了paddle cpu版本的2.6.1，但是paddle detection运行不兼容（paddle detection 我下载的最新版本 release 2.7.1），我就又改成2.3.2的了（因为paddle detection 给的指南里面的例子的命令是2.3.2的）。
最后，进https://pypi.tuna.tsinghua.edu.cn/simple 这个网址，我看不出来哪一个是对应哪一个版本的（图片里面有多‘/’是一回车自己就多出来的），我这边有GPU的机器只能离线安装，它没有网。
![84d63c79714192c48e6c306f453a1b1e](https://github.com/PaddlePaddle/Paddle/assets/58506391/9d5235f3-8456-4ba0-bde4-f26ebde8a9f6)

**Comment by shelly-angel** [comment]
关于我找到的11.8-3.10-2.6.1的包，安装结果如下，仍然不成功（我下载了whl， 但是为啥还是尝试http?）。
wheel下载链接：https://paddle-wheel.bj.bcebos.com/2.6.1/windows/windows-gpu-cuda11.8-cudnn8.6.0-mkl-avx-vs2019/paddlepaddle_gpu-2.6.1-cp310-cp310-win_amd64.whl
众多wheel的地址：(https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html)
![339e9af513739750f97b1657250974d4](https://github.com/PaddlePaddle/Paddle/assets/58506391/f8dc0702-91ac-407d-b38c-7c452cf0eccc)

**Comment by shelly-angel** [comment]
解决了！！！
在有网的机器(和目标机器硬件环境不一致也没有关系)下安装paddle-gpu-2.6.1(https://paddle-wheel.bj.bcebos.com/2.6.1/windows/windows-gpu-cuda11.8-cudnn8.6.0-mkl-avx-vs2019/paddlepaddle_gpu-2.6.1-cp310-cp310-win_amd64.whl), 然后将envs下面的虚拟环境复制到目标机器上，运行成功了。
所以：
1. 下载whl的时候，记得观察百度给的链接名字，像我第一次安装2.3.2的版本，他们给的链接名字就不对，cuda出现问题的时候不一定是自己的原因，可能是他们给的链接是错误的。
2. 新版本gpu2.6.1-py3.10-cuda11.8 和 paddle detection2.7.1 兼容没有问题，也不知道为什么cpu版本的兼容有问题。
但是对于我上面的问题，也可以解决一下，为后面的小伙伴留下答案。
（1）paddle-gpu-2.3.3-py3.10-cuda11.8的离线版本（我搜索到的官方给的链接里面是找不到这个东西的）
（2）为啥我下载了whl，离线安装时仍然报http的错误，它还要联网吗？

**Comment by XieYunshen** [comment]
> 解决了！！！ 在有网的机器(和目标机器硬件环境不一致也没有关系)下安装paddle-gpu-2.6.1(https://paddle-wheel.bj.bcebos.com/2.6.1/windows/windows-gpu-cuda11.8-cudnn8.6.0-mkl-avx-vs2019/paddlepaddle_gpu-2.6.1-cp310-cp310-win_amd64.whl), 然后将envs下面的虚拟环境复制到目标机器上，运行成功了。 所以：
> 
> 1. 下载whl的时候，记得观察百度给的链接名字，像我第一次安装2.3.2的版本，他们给的链接名字就不对，cuda出现问题的时候不一定是自己的原因，可能是他们给的链接是错误的。
> 2. 新版本gpu2.6.1-py3.10-cuda11.8 和 paddle detection2.7.1 兼容没有问题，也不知道为什么cpu版本的兼容有问题。
>    但是对于我上面的问题，也可以解决一下，为后面的小伙伴留下答案。
>    （1）paddle-gpu-2.3.3-py3.10-cuda11.8的离线版本（我搜索到的官方给的链接里面是找不到这个东西的）
>    （2）为啥我下载了whl，离线安装时仍然报http的错误，它还要联网吗？

针对于离线安装的问题，是因为还有相关依赖要安装，如果要下载whl包并进行离线安装的话，可以使用pip的download命令下载`python -m pip download urls`,这样同时会把需要的依赖包下载到本地；安装时可以通过`pip install --no-index --find-links=/path/to/packages package_name`使用本地的路径进行安装
