### ISSUE TITLE
CNN的model预测结果与日志不一致

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#648]
1.  用2层CNN训练出来的model，预测测试集的图片（24680张），RGB通道不进行swap时是42.18%，RGB通道进行swap时是37.29%。但是在GPU训练时的日志是Test samples=51200 cost=0.30189 Eval: classification_error_evaluator=0.115723 。训练的samples和分类错误率跟预测时的差别很大？？？ 训练时是用GPU，预测时用的是CPU，是由于CPU和GPU在某些层的实现不一致吗？

**Comment by qingqing01** [comment]
首先是否需要对RGB通道进行swap应该保持和训练一致。 其次，卷积层GPU默认使用cudnn， 确实和CPU在conv不一致， https://github.com/PaddlePaddle/Paddle/pull/636   这里已经进行了统一。

**Comment by reyoung** [comment]
目前的版本里，对于卷积神经网络，预测时和训练时必须同时使用CPU或者GPU。否则确实会有不一致。

**Comment by qubingxin** [comment]
#636 的统一没看懂，是现在已经提供CPU和GPU一致的层了么？如果没有，那请问什么时候能修复该bug？

**Comment by qingqing01** [comment]
@qubingxin #636  merge了之后就会统一，这两天会merge。

**Comment by luotao1** [comment]
@qubingxin 该bug已经修复了。

**Comment by qubingxin** [comment]
hi，请问修复后的卷积层的实现，和之前的版本的CPU的一致还是GPU的一致？

**Comment by qingqing01** [comment]
修复之后 exconv的CPU/GPU实现和cudnn_conv实现一致。  如果你在修复之前使用exconv训练的模型，现在无法再使用exconv测试。
