### ISSUE TITLE
Fluid中如何得到参数的initial信息？

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#6484]
类似V2中的proto接口，新版的API如何拿到参数的初始化信息呢？例如：initial_mean，initial_std，size，name等。

**Comment by Canpio** [comment]
不知您的意思是“如何设置参数的初始化信息”还是“如何拿到已经被初始化的参数的初始化信息”？
如果是前者，可以通过设置`param_attr`来实现，这方面的文档我们还在编写中。
如果是后者，目前没有专门设置这方面的接口。Fluid还在持续改进中，您可以在这里说一下您有这个需求的原因，我们了解一下。

**Comment by peterzhang2029** [comment]
@Canpio 多谢回复哈，这里说的是后者，我现在也在做模型对齐相关的工作，因为v2和Fluid的默认初始化策略不同，对不同版本的paddle参数严格对齐的话，想把各自的参数的初始化配置拿出来比对一下。

**Comment by Canpio** [comment]
参数的初始化最终还是通过一系列的op来实现的，这些op会被放在一个Python中叫做`startup_program`的`Program`对象中，调用`default_startup_program()`可以获得这个对象。然后可以直接在python中将它print出来，你会看到一些列的variable和op，观察这些op的属性就可以确定对应参数的初始化方式。

**Comment by peterzhang2029** [comment]
@Canpio 多谢回复，我先试试。
