### ISSUE TITLE
import paddle时候出core

### ISSUE THREAD

**Issue by PassStory** [PaddlePaddle/Paddle#64962]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/6964842/92850878-00c8-4906-ae46-3e1595f15a42)

**Comment by will-jl944** [comment]
Paddle是如何安装的？是否有选择与环境cuda版本对应的包？

**Comment by PassStory** [comment]
> Paddle是如何安装的？是否有选择与环境cuda版本对应的包？

python -m pip install paddlepaddle-gpu

**Comment by will-jl944** [comment]
使用的cuda版本是多少？

**Comment by PassStory** [comment]
> 使用的cuda版本是多少？

> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Thu_Jan_28_19:32:09_PST_2021
Cuda compilation tools, release 11.2, V11.2.142
Build cuda_11.2.r11.2/compiler.29558016_0

**Comment by will-jl944** [comment]
尝试卸载掉原有的paddlepaddle-gpu，通过`python -m pip install paddlepaddle-gpu==2.6.1.post112 -f https://www.paddlepaddle.org.cn/whl/linux/mkl/avx/stable.html`重新安装。

**Comment by PassStory** [comment]
python版本提高到3.12了，这个问题不再出现

**Comment by PassStory** [comment]
python版本提高到3.12了，这个问题不再出现
