### ISSUE TITLE
while_loop报错

### ISSUE THREAD

**Issue by nku428** [PaddlePaddle/Paddle#64984]
### bug描述 Describe the Bug

import paddle

nid_cls_label = paddle.to_tensor([49,18,54,28,38,26,8,23,42,56,50,52,52,18,56,18,27,40,49,31,52,42,60,21,56,11,17,8,56,56,54,18,49,18,56,54,33,54,18,18,18,12,12,56,42,20,42,18,33,3,56,8,28,56,21,18,18,3,40,25,10,52,50,18])
logits = paddle.rand((64,8))
label_list = paddle.reshape(nid_cls_label, [nid_cls_label.shape[0]])
label_freq = paddle.cast(paddle.bincount(label_list), 'int32')
max_label = paddle.argmax(label_freq)
ones = paddle.ones_like(label_list)
zeros = paddle.zeros_like(label_list)
where_index_major = paddle.where(label_list == max_label, ones, zeros)
where_index_major = paddle.unsqueeze(where_index_major, axis=1)
where_index_major = paddle.expand(where_index_major, logits.shape)
where_index_major = paddle.cast(where_index_major, 'bool')
vec_select_major = paddle.masked_select(logits, where_index_major)
vec_select_major = paddle.reshape(vec_select_major, shape=[-1, logits.shape[1]])
major_cov = paddle.linalg.cov(vec_select_major, rowvar=False)
unique_label = paddle.unique(label_list, dtype='int32')
cls_num = paddle.shape(unique_label)[0]
def cond(i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov):
            return i < ten

def body(i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov):
        i = i + 1
        label_id = unique_label[i]
        if label_freq.shape[0] > label_id:
            if label_freq[label_id] > 2:
                if label_id != max_label:
                    where_index_small = paddle.where(label_list==label_id, ones, zeros)
                    where_index_small = paddle.unsqueeze(where_index_small, axis=1)
                    where_index_small = paddle.expand(where_index_small, logits.shape)
                    where_index_small = paddle.cast(where_index_small, 'bool')
                    vec_select_small = paddle.masked_select(logits, where_index_small)
                    vec_select_small = paddle.reshape(vec_select_small, shape=[-1, logits.shape[1]])
                    samall_cov = paddle.linalg.cov(vec_select_small, rowvar=False)
                    loss += paddle.linalg.norm(major_cov - samall_cov)
                    num += 1
        return [i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov]
        
i = paddle.full(shape=[1], dtype='int32', fill_value=0)
ten = paddle.to_tensor(cls_num, dtype='int32')
loss = paddle.full(shape=[1], dtype='float32', fill_value=0.0)
num = paddle.full(shape=[1], dtype='int32', fill_value=0)
i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov = paddle.static.nn.while_loop(cond=cond, 
                                             body=body,
                                             loop_vars=[i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov])

报错如下：

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/yuanhao03/apps/python3_flux/lib/python3.9/site-packages/paddle/fluid/layers/control_flow.py", line 1437, in while_loop
    output_vars = body(*loop_vars)
  File "<stdin>", line 4, in body
  File "/home/yuanhao03/apps/python3_flux/lib/python3.9/site-packages/paddle/fluid/dygraph/math_op_patch.py", line 304, in __impl__
    return math_op(self, other_var, -1)
RuntimeError: (PreconditionNotMet) Tensor's dimension is out of bound.Tensor's dimension must be equal or less than the size of its memory.But received Tensor's dimension is 8, memory's size is 0.
  [Hint: Expected numel() * SizeOf(dtype()) <= memory_size(), but received numel() * SizeOf(dtype()):8 > memory_size():0.] (at /paddle/paddle/phi/core/dense_tensor_impl.cc:58)

**Comment by winter-wang** [comment]
抱歉，由于你贴的代码没有缩进，我这边无法复线，麻烦规范一下代码缩进。

**Comment by nku428** [comment]
`import paddle

nid_cls_label = paddle.to_tensor([49,18,54,28,38,26,8,23,42,56,50,52,52,18,56,18,27,40,49,31,52,42,60,21,56,11,17,8,56,56,54,18,49,18,56,54,33,54,18,18,18,12,12,56,42,20,42,18,33,3,56,8,28,56,21,18,18,3,40,25,10,52,50,18])
logits = paddle.rand((64,8))
label_list = paddle.reshape(nid_cls_label, [nid_cls_label.shape[0]])
label_freq = paddle.cast(paddle.bincount(label_list), 'int32')
_ = paddle.static.Print(label_freq, message='label_freq', summarize=200)
max_label = paddle.argmax(label_freq)
ones = paddle.ones_like(label_list)
zeros = paddle.zeros_like(label_list)
where_index_major = paddle.where(label_list == max_label, ones, zeros)
where_index_major = paddle.unsqueeze(where_index_major, axis=1)
where_index_major = paddle.expand(where_index_major, logits.shape)
where_index_major = paddle.cast(where_index_major, 'bool')
vec_select_major = paddle.masked_select(logits, where_index_major)
vec_select_major = paddle.reshape(vec_select_major, shape=[-1, logits.shape[1]])
major_cov = paddle.linalg.cov(vec_select_major, rowvar=False)
unique_label = paddle.unique(label_list, dtype='int32')
cls_num = paddle.shape(unique_label)[0]
def cond(i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov):
    return i < ten

def body(i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov):
    i = i + 1
    label_id = unique_label[i]
    if label_freq.shape[0] > label_id:
        if label_freq[label_id] > 2:
            if label_id != max_label:
                where_index_small = paddle.where(label_list == label_id, ones, zeros)
                where_index_small = paddle.unsqueeze(where_index_small, axis=1)
                where_index_small = paddle.expand(where_index_small, logits.shape)
                where_index_small = paddle.cast(where_index_small, 'bool')
                vec_select_small = paddle.masked_select(logits, where_index_small)
                vec_select_small = paddle.reshape(vec_select_small, shape=[-1, logits.shape[1]])
                samall_cov = paddle.linalg.cov(vec_select_small, rowvar=False)
                loss += paddle.linalg.norm(major_cov - samall_cov)
                num += 1
    return [i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov]

i = paddle.full(shape=[1], dtype='int32', fill_value=0)
ten = paddle.to_tensor(cls_num, dtype='int32')
loss = paddle.full(shape=[1], dtype='float32', fill_value=0.0)
num = paddle.full(shape=[1], dtype='int32', fill_value=0)
i, ten, num, loss, label_freq, unique_label, label_list, logits, major_cov = paddle.static.nn.while_loop(cond=cond,
                                                                                                             body=body,
                                                                                                             loop_vars=[
                                                                                                                 i, ten,
                                                                                                                 num,
                                                                                                                 loss,
                                                                                                                 label_freq,
                                                                                                                 unique_label,
                                                                                                                 label_list,
                                                                                                                 logits,
                                                                                                                 major_cov])`

**Comment by nku428** [comment]
[test.txt](https://github.com/user-attachments/files/15708444/test.txt)
@winter-wang 我上传了一个文件辛苦再看下呢？感谢感谢

**Comment by winter-wang** [comment]
你的组网逻辑有问题， while_loop的逻辑是 while(cond) { body}
在你的网络中，cond是 i < ten, ten的值是25， 所以最后一轮循环，i的值是24.
此时执行body时，通过 i = i+1， i变为了25，随后执行 label_id = unique_label[i]就会访问越界，因为unique_label的下标范围是0到24。 所以报了你所贴的错误。

**Comment by nku428** [comment]
哦哦哦！！！犯了个低级错误。。。。
多谢多谢！！！
