### ISSUE TITLE
集群训练使用sparseupdate，提交任务报错，Check failed: error >= 0 ERROR connecting to 10.74.177.49: Connection refused

### ISSUE THREAD

**Issue by 20092136** [PaddlePaddle/Paddle#6499]
Tue Dec 12 11:28:10 2017[1,8]<stderr>:+ ./paddle_trainer --num_gradient_servers=50 --trainer_id=8 --pservers=隐藏
 --rdma_tcp=tcp --nics=xgbe0 --port=7164 --ports_num=16 --dot_period=1000 --port=20444 --config_args=is_local=0 --log_period=999999999 --trainer_count=16 --ports_num_for_sparse=4 --num_passes=150 --saving_period=1 --local=0 --config=conf/trainer_config.conf --save_dir=./output --use_gpu=0
Tue Dec 12 11:28:11 2017[1,8]<stderr>:[INFO 2017-12-12 11:28:11,417 networks.py:1482] The input order is [query, pos_data, neg_data, label]
Tue Dec 12 11:28:11 2017[1,8]<stderr>:[INFO 2017-12-12 11:28:11,417 networks.py:1488] The output order is [__rank_cost_0__]
Tue Dec 12 11:28:16 2017[1,8]<stderr>:[INFO 2017-12-12 11:28:16,284 dataprovider.py:53] dict len : 1549030
Tue Dec 12 11:28:32 2017[1,8]<stderr>:F1212 11:28:32.289374 51417 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.74.177.49: Connection refused [111]
Tue Dec 12 11:28:32 2017[1,8]<stderr>:*** Check failure stack trace: ***
Tue Dec 12 11:28:32 2017[1,8]<stderr>:F1212 11:28:32.289414 50993 LightNetwork.cpp:397] Check failed: error >= 0 ERROR connecting to 10.74.177.49: Connection refused [111]
Tue Dec 12 11:28:32 2017[1,8]<stderr>:*** Check failure stack trace: ***
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x91316d  google::LogMessage::Fail()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x916c1c  google::LogMessage::SendToLog()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x912c93  google::LogMessage::Flush()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x912e99  google::LogMessage::~LogMessage()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x916147  google::ErrnoLogMessage::~ErrnoLogMessage()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x7691a1  paddle::SocketClient::SocketClient()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x768fa1  paddle::SocketClient::TcpClient()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0xf06e50  paddle::ParameterClient2::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x7691a1  paddle::SocketClient::SocketClient()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x76052d  paddle::RemoteParameterUpdater::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x74ebd6  paddle::SyncThreadPool::execPlusOwner()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0xf06e50  paddle::ParameterClient2::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x75ca3e  paddle::SparseRemoteParameterUpdaterComposite::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x75c619  paddle::SparseRemoteParameterUpdater::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x748a04  paddle::Trainer::init()
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x5a3cbc  main
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @           0x734534  _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @     0x7ff6070198a0  execute_native_thread_routine
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @     0x7ff6074781c3  start_thread
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @     0x7ff60678a12d  __clone
Tue Dec 12 11:28:32 2017[1,8]<stderr>:    @              (nil)  (unknown)

同样的配置在单机跑是没问题的，不使用sparse update在集群跑也没问题。
看过 #2955 @typhoonzero 的回复，但是没有找到有效的解决方案。

**Comment by sweetsky0901** [comment]
更多的server log有吗

**Comment by 20092136** [comment]
@sweetsky0901 http://10.74.177.49:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/164598/workspace/log/server.log

**Comment by sweetsky0901** [comment]
Got error in response to OP_READ_BLOCK for object /64-19234848044for file /user/ltr/huangwenzhi/data/201511/text/train/part-04901.gz for block 18014401286017612
在train.log里看到这个错误

**Comment by 20092136** [comment]
@sweetsky0901 这个错误是必现的，但您说的这个下载数据的问题不是出现在每次提交的日志中，比如这个

**Comment by 20092136** [comment]
> 群多节点训练，日志报错为网络通信类错误，比如 Connection reset by peer 等。 此类报错通常是由于某一个节点的错误导致这个节点的训练进程退出，从而引发其他节点无法连接导致，可以参考下面的步骤排查：
> 
> 从 train.log ， server.log 找到最早报错的地方，查看是否是其他错误引发的报错（比如FPE，内存不足，磁盘空间不足等）。
> 如果发现最早的报错就是网络通信的问题，很有可能是非独占方式执行导致的端口冲突，可以联系OP，看当前MPI集群是否支持resource=full参数提交，如果支持增加此参数提交，并更换job 端口。
> 如果当前MPI集群并不支持任务独占模式，可以联系OP是否可以更换集群或升级当前集群。

  @sweetsky0901  hi群里推荐看这个，麻烦看看有没有帮助？我不太理解什么叫增加resource=full参数提交，并且使用receiver提交集群任务，似乎没法更换job 端口

**Comment by sweetsky0901** [comment]
这个文档的意思是说，表面现象是说链接不上，其实要看log，找到导致错误的根源

**Comment by 20092136** [comment]
我也仔细看过我的log，似乎没有找到什么有价值的信息

**Comment by cszhou** [comment]
我在使用中也遇到同样问题。也报了issue。我复现发现这个跟结点个数有关。
结点数量为20，没有报错。
结点数量为100，试了多次都报 @20092136  一样的错误。
节点数量为50的时候，提交多次，偶尔会有成功的。
麻烦paddle同学重视进行排查。

**Comment by 20092136** [comment]
@cszhou 我也调整过节点数，但从来没有成功过

**Comment by 20092136** [comment]
十分感谢 @sweetsky0901 @typhoonzero 的耐心支持，问题解决了。

解决的key在于使用sparse_update=True的时候，需要在cluster_config处设置use_remote_sparse=1
