### ISSUE TITLE
npu下import paddlenlp报错：No module named 'paddle.nn.layer.layers'

### ISSUE THREAD

**Issue by skywalk163** [PaddlePaddle/Paddle#64996]
### bug描述 Describe the Bug

npu下import paddlenlp报错：No module named 'paddle.nn.layer.layers'

在openi启智平台：
$npu-smi info
+------------------------------------------------------------------------------------------------+
| npu-smi 23.0.rc2                 Version: 23.0.rc2                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 1     910ProA             | Warning       | 75.2        41                0    / 0             |
| 0                         | 0000:81:00.0  | 0           2221 / 15137      1    / 32768         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
飞桨版本：

Running verify PaddlePaddle program ... 
PaddlePaddle works well on 1 CPU.
PaddlePaddle works well on 2 CPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/executor.py:1752: UserWarning: Standalone executor is not used for data parallel
  UserWarning,
'0.0.0'

paddle.version.commit
'507af1c87f43485c06c5d71f56a11a62aa0bb418'

执行import paddlenlp的时候
```
import paddlenlp
/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
/home/ma-user/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-9f806b89ef0e> in <module>
----> 1 import paddlenlp

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/__init__.py in <module>
     33 import paddle
     34 
---> 35 from . import (
     36     data,
     37     dataaug,

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/data/__init__.py in <module>
     16 from .causal_dataset import *
     17 from .collate import *
---> 18 from .data_collator import *
     19 from .dist_dataloader import *
     20 from .sampler import *

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/data/data_collator.py in <module>
     24 import paddle
     25 
---> 26 from ..transformers import BertTokenizer
     27 from ..transformers.tokenizer_utils_base import (
     28     BatchEncoding,

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/transformers/__init__.py in <module>
     15 
     16 from .configuration_utils import PretrainedConfig
---> 17 from .model_utils import PretrainedModel, register_base_model
     18 from .tokenizer_utils import (
     19     PretrainedTokenizer,

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/transformers/model_utils.py in <module>
     60 from paddlenlp.utils.log import logger
     61 
---> 62 from ..generation import GenerationConfig, GenerationMixin
     63 from ..utils import device_guard
     64 from .configuration_utils import PretrainedConfig

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/generation/__init__.py in <module>
     13 # limitations under the License.
     14 from .configuration_utils import GenerationConfig
---> 15 from .logits_process import (
     16     ForcedBOSTokenLogitsProcessor,
     17     ForcedEOSTokenLogitsProcessor,

~/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddlenlp/generation/logits_process.py in <module>
     20 import numpy as np
     21 import paddle
---> 22 from paddle.nn.layer.layers import in_declarative_mode
     23 
     24 

ModuleNotFoundError: No module named 'paddle.nn.layer.layers'
```

### 其他补充信息 Additional Supplementary Information

飞桨是从这里安装的：https://www.paddlepaddle.org.cn/install/quick?docurl=undefined 

> 安装PaddlePaddle。
> 
> 该命令会自动安装飞桨主框架每日自动构建的nightly-build版本：
> 
> python -m pip install --pre paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/
> 安装CustomDevice。
> 
> 该命令会自动安装飞桨Custom Device每日自动构建的nightly-build版本：
> 
> python -m pip install --pre paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npu/

paddlenlp是pip install paddlenlp安装的，后来又尝试了git clone https://openi.pcl.ac.cn/PaddlePaddle/PaddleNLP之后setup安装的

**Comment by winter-wang** [comment]
看你的报错信息，你似乎是在使用python3.7，但是目前的Paddle仅支持python3.8及以上，你贴的安装链接中也并没有发布python3.7对应的whl包。 麻烦你确认一下，是否正确安装了paddle的whl包。

**Comment by skywalk163** [comment]
收到，果然是python版本低了。
后来发现启智社区提供的npu是aarch64架构，飞桨官网提供的是amd64架构，所以升级了python到3.9也不行。

希望今后能提供aarch64架构的安装包，毕竟启智等昇腾npu算力中心大部分都是在aarch64 linux（[paddle_custom_npu-3.0.0.dev20240607-cp39-cp39-linux_x86_64.whl](https://paddle-whl.bj.bcebos.com/nightly/npu/paddle-custom-npu/paddle_custom_npu-3.0.0.dev20240607-cp39-cp39-linux_x86_64.whl)）下使用的。
