### ISSUE TITLE
官网映射文档develop版本无法正常显示，挂了很长时间了

### ISSUE THREAD

**Issue by zhwesky2010** [PaddlePaddle/Paddle#65031]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.html 官网映射文档无法正常显示，全部显示为空
![379814d5af9953888530b8f7026a58ad](https://github.com/PaddlePaddle/Paddle/assets/52485244/8f4f1966-9ed7-4680-a288-f987fae7d7cf)

而预览是可以正常显示的
![a29183255de3c23aad73ed9e8dfc2c3e](https://github.com/PaddlePaddle/Paddle/assets/52485244/195b2dd2-1548-40c2-b719-1abfcaa0ec9f)

### 请提出你的建议 Please give your suggestion

挂了挺长时间了，麻烦修一下

**Comment by Birdylx** [comment]
@zhwesky2010 可以切回2.6的页面查看映射表：https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/model_convert/convert_from_pytorch/pytorch_api_mapping_cn.html

**Comment by sunzhongkai588** [comment]
已解决，查看最新 develop
