### ISSUE TITLE
GatedRecurrentLayer 优化计划

### ISSUE THREAD

**Issue by ZhaiFeiyue** [PaddlePaddle/Paddle#6506]
ALL-
我是Intel 这边负责GatedRecurrentLayer 优化的工程师，GatedRecurrentLayer代码优化的DEMO已经完成并且通过了单元测试。希望GatedRecurrentLayer 优化的代码能尽快merge 到paddle项目中，以提高GatedRecurrentLayer的性能，让更多使用paddle的用户受益。

由于Intel的优化涉及到以下文件：
  a. paddle/gserver/layers/GatedRecurrentLayer.cpp
  b. paddle/gserver/layers/GatedRecurrentLayer.h
  c. paddle/function/GruFunctor.h
因此在merge 代码方面我们这边提供了三个方法：
  1. 用条件编译的方式修改GatedRecurrentLayer 和GruFunctor的代码，增加Intel 优化的packedGemm。
  2. 在GatedRecurrentLayer中实现packedGemm 子类，并且修改GruCompute::forward接口，将Intel优化
      的packedGemm对象传给GruFunctor。
  3. 在GatedRecurrentLayer 类中添加一个新的成员函数例如：forwardBatchPacked，将Intel 修改和依赖
      的的代码全部放到这个函数中，在GatedRecurrentLayer::forwardBatch函数中添加新分支来调用Intel 
      优化的forwardBatchPacked函数。

   请问paddle team这边觉得那种方案比较合理，可以接受？或者是否有更好的方案？

**Comment by luotao1** [comment]
请问Intel优化的packedGemm对象，具体是什么呢？是在调用GEMM库后做的一些封装操作么？不涉及MKLDNN库？

**Comment by luotao1** [comment]
@hedaoyuan 建议：如果优化代码与原先代码相关性不大的话，可以单独实现一个Layer，类似卷积有ExpandConvLayer和CudnnConvLayer。

如果不涉及MKLDNN库的话，可以取名为MKLGatedRecurrentLayer

**Comment by ZhaiFeiyue** [comment]
@luotao1 
**请问Intel优化的packedGemm对象，具体是什么呢？**
    A. packedGemm对象主要封装了
        1. GRU weight 权重矩阵的gemm pack操作
        2. GRU weight 权重矩阵的cbals alloc 操作
        3. GRU weight 权重矩阵的cblas free操作
        4. GRU forward 过程中用cblas_compute 替换 cblas_sgemm对外统一暴露一个compute接口
    B. GRU packedGemm 对象不依赖任何MKLDNN， 只是对mkl的封装
    C. 特别需要注意一下，如果采用方案二，由于GruCompute::forward调用了GruFunctor::compute, 并且
        在GruFunctor::compute中需要使用到packedGemm对象的方法，所以要修改GruCompute::forward 
        和GruFunctor::compute 的接口。例如GruCompute.cpp的修改如下(见红色框)：
![grucompute](https://user-images.githubusercontent.com/34468585/33874394-91446ea8-df59-11e7-9be7-7a2b9cbd37b7.png)

**Comment by ZhaiFeiyue** [comment]
关于
 **建议：如果优化代码与原先代码相关性不大的话，可以单独实现一个Layer，类似卷积有ExpandConvLayer和CudnnConvLayer。**
讨论参考：https://github.com/PaddlePaddle/Paddle/issues/6512

**Comment by luotao1** [comment]
集成MKLDNN的设计文档在[这里](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/mkldnn)，RNN优化计划能否也写成一个设计文档呢？

**Comment by tensor-tang** [comment]
Since short of resources, I think we should close it so far.
