### ISSUE TITLE
Refine current codes to support multi-devices

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6507]
- [x] Refine cuDNN related operators:
  - [x] rename `GPUPlace` to `CUDAPlace` and introduce `CUDNNPlace` derived from `CUDAPlace` https://github.com/PaddlePaddle/Paddle/pull/6518
  - [x] introduce `CUDNNDeviceContext` derived from `CUDADeviceContext` https://github.com/PaddlePaddle/Paddle/pull/6585
  - [x] make current cuDNN related operators to be a OpKernel of corresponding operator. For example: conv_cudnn is actually a OpKernel of conv operator, it should not be a independent operator. https://github.com/PaddlePaddle/Paddle/pull/6660
- [x] Refine the interface of `OperatorBase::Run`, take `vector<Place>` as parameter instead of `DeviceContext` https://github.com/PaddlePaddle/Paddle/pull/6783
- [x] Implement a pool of `DeviceContext` in init stage https://github.com/PaddlePaddle/Paddle/pull/6537
- [x] refine operator run logic.  https://github.com/PaddlePaddle/Paddle/pull/6783

**Comment by wangkuiyi** [comment]
Let us use https://github.com/PaddlePaddle/Paddle/projects/35 to manage this list.  After we create related TODO items in the project, we can close this issue. @QiJune
