### ISSUE TITLE
Set env into C-API library.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#6520]
Reference: https://github.com/PaddlePaddle/Paddle/issues/4813#issuecomment-350963870 and https://github.com/PaddlePaddle/Paddle/issues/5280#issuecomment-344481397 

Now, we need to set env variables `MKL_NUM_THREADS` and `OMP_NUM_THREADS` before running `C-API` program to make the best performance of MKLML.

How to merge these into C-API library and so user don't concern about it?

**Comment by luotao1** [comment]
Can you update https://github.com/gongweibao/testcapi and tell us how to use `paddle_capi_shared` for `build.sh` at first?
```
/opt/compiler/gcc-4.8.2/sbin/../lib/gcc/x86_64-baidu-linux-gnu/4.8.2/../../../../x86_64-baidu-linux-gnu/bin/ld: cannot find -lpaddle_capi_shared
collect2: error: ld returned 1 exit status
make[2]: *** [exeModel] Error 1
make[1]: *** [CMakeFiles/exeModel.dir/all] Error 2
make: *** [all] Error 2
```
