### ISSUE TITLE
paddle静态模型在mac预测输出正确，转化为paddlelite模型输出为nan，数据类型均为fp32

### ISSUE THREAD

**Issue by Xu789** [PaddlePaddle/Paddle#65215]
### bug描述 Describe the Bug

paddle静态模型在mac预测输出正确，转化为paddlelite模型输出为nan，数据类型均为fp32，如何解决？？？？

### 其他补充信息 Additional Supplementary Information

paddle静态模型在mac预测输出正确，转化为paddlelite模型输出为nan，数据类型均为fp32，如何解决？？？？
<img width="735" alt="98b443e7b620bcf529fac67e0" src="https://github.com/PaddlePaddle/Paddle/assets/94166333/cbc0ec32-f47f-4a3f-a7e8-5d9e8860689f">

**Comment by Xu789** [comment]
将c++输入类型改为double，输入到paddlelite模型的输出也不对  
![image](https://github.com/PaddlePaddle/Paddle/assets/94166333/6f5d0860-c626-4803-8a12-295a03270aef)

**Comment by hong19860320** [comment]
内部沟通解决，解决办法：使用 Netron 查看模型确定输入、输出个数、尺寸和数据类型。
