### ISSUE TITLE
ppyoloe_r 按照官方案例训练脊柱数据集，但是分类loss不收敛

### ISSUE THREAD

**Issue by tjdster** [PaddlePaddle/Paddle#65220]
### 请提出你的问题 Please ask your question

![4f83b826a58396eb0829d74f4b0bc1b](https://github.com/PaddlePaddle/Paddle/assets/61610666/7e867526-9803-4d72-bc1d-2985be51bb35)

**Comment by tjdster** [comment]
![d9acb89749458f06ef4f883cb0ce977](https://github.com/PaddlePaddle/Paddle/assets/61610666/9448a82e-fd60-465d-8edf-688b1558d4c8)

**Comment by tjdster** [comment]
如果方便可以加本人微信：1285235820，这样沟通更高效

**Comment by risemeup1** [comment]
> 如果方便可以加本人微信：1285235820，这样沟通更高效

这个可以去这个仓库下边去提问吧，我们这边不了解这个

**Comment by tjdster** [comment]
> > 如果方便可以加本人微信：1285235820，这样沟通更高效
> 
> 这个可以去这个仓库下边去提问吧，我们这边不了解这个

那边没回回复，是不是不维护了
