### ISSUE TITLE
【HACKATHON 预备营】飞桨启航计划集训营（第三期）

### ISSUE THREAD

**Issue by Harryoung** [PaddlePaddle/Paddle#65279]
> [!IMPORTANT]
> 启航计划已于 9 月 29 日正式结营，结营公示： https://github.com/PFCCLab/Starter/issues/411

---
> [!NOTE]  
> 接收简历时间延长一周至**7月15日**，开营、结营时间依次顺延。炎炎暑期，少年不来**开源一夏**吗？🏖️

## 飞桨启航计划简介

**「启航计划」** 是 **飞桨开源社区** 发起的远程项目，也是「护航计划」的前置活动（护航计划详情请看这里 ➡️ [护航计划说明](https://github.com/PFCCLab/Camp)）。我们以开展**线上集训营**的形式，鼓励开发者积极参与开源项目，以此提升自己的代码实践能力，与社区共同成长 💪。

> 第一期「启航计划」看这里 ➡️ https://github.com/PaddlePaddle/Paddle/issues/58497
> 第二期「启航计划」看这里 ➡️ https://github.com/PaddlePaddle/Paddle/issues/62347

开发者提交申请材料并通过后，将会参与为期**2个月**密集的**线上集训项目**，目标是尽可能多且高质量地完成开源任务 。为给大家更多引导，提高参与感，本期「启航计划」将特别保留专项团制度，每一位参与的同学都可以得到**飞桨研发同学的指导**。🧑‍🏫🧑‍🏫🧑‍🏫

当前可供选择的专项团列表如下：

- 营员要求：熟悉 Python 和 C++，对深度学习技术有一定了解，有深度学习框架应用和研发经验

| 编号 | 团名               | tracking issue & 导师信息                                    | 报名情况 | 锁定营员 |
| ---- | ------------------ | ------------------------------------------------------------ | -------- | -------- |
| 1 | 专项团：文档 | [Paddle Docathon 文档系列活动](https://github.com/PaddlePaddle/docs/issues/6165)<br />导师：[sunzhongkai588](https://github.com/sunzhongkai588) 助教：待定 | @entired <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @123456-ICEN <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Wang-ZengWei <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @haoyu2022 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Wang-ZengWei @haoyu2022 @freejager @EgoistSA @yeteye @pleasegivemeastar @fufu0615  | 
| 2 | 专项团：复数 | [【complex op】paddlepaddle 支持复数](https://github.com/PaddlePaddle/Paddle/issues/61975)<br />导师：[zhiminzhang0830](https://github.com/zhiminzhang0830) 助教：待定 | @cuishitan <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@ssy-lbh <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Marcusryz <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@struim <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @yyBlone <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @cuishitan @struim  @yyBlone @Aoraki-Dream | 
| 3 | 专项团：基础框架 | [飞桨 IR 快乐开源活动表单](https://github.com/PaddlePaddle/Paddle/issues/62704)<br />[【快乐开源】报错日志体系优化](https://github.com/PaddlePaddle/Paddle/issues/62748)<br />导师：[Aurelius84](https://github.com/Aurelius84)  助教：[zbt78](https://github.com/zbt78)、[AndPuQing](https://github.com/AndPuQing)、[ooooo-create](https://github.com/ooooo-create) | @Felix-Zhenghao <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @Kaedeharai <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @Lubenwei-nb123 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@ykcai-daniel <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@smallpoxscattered <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Betelgeu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@MikhayEeer <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @Turingg <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@GoldenStain <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@inaomIIsfarell <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Sekiro-x <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Felix-Zhenghao @Lubenwei-nb123 @ykcai-daniel @smallpoxscattered @Betelgeu @MikhayEeer @Turingg @GoldenStain @inaomIIsFarell @Sekiro-x  @successfulbarrier @brcarry @Marcusryz  | 
| 4 | 专项团：科学计算 | [PaddleScience 快乐开源活动表单](https://github.com/PaddlePaddle/PaddleScience/issues/379)<br />导师：[HydrogenSulfate](https://github.com/HydrogenSulfate) 助教：待定 | @dongjinkun <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @Dale1314 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@fufu0615 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @Dale1314  | 
| 5 | 专项团：大模型套件 | [PaddleMIX快乐开源活动表单](https://github.com/PaddlePaddle/PaddleMIX/issues/410)<br />导师：[LokeZhou](https://github.com/LokeZhou) 助教：待定 | @freejager <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @pleasegivemeastar <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@AIzealotwu <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@EgoistSA <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@InsaneOnion <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> @Xingyyy01 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@yeteye <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@brcarry <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@bruce2233 <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@successfulbarrier <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@developWmark <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br>@Aoraki-Dream <img src="https://img.shields.io/badge/状态-报名-2ECC71" /> <br> | @AIzealotwu @Xingyyy01 @InsaneOnion  @bruce2233 @developWmark | 

集训期间，我们会提供研发支持🧑🏻‍💻、随时随地都能使用的**线上 V100 开发环境** 🔧（申请方式看这里 ➡️ [飞桨线上开发环境——AI Studio星河社区](https://github.com/PaddlePaddle/community/tree/master/pfcc/call-for-contributions#%E9%A3%9E%E6%A1%A8%E7%BA%BF%E4%B8%8A%E5%BC%80%E5%8F%91%E7%8E%AF%E5%A2%83ai-studio)）以帮助学员更好地融入项目，不断提升技术水平。我们鼓励学员积极互动和交流，希望每位学员都能够在集训期结束时取得优异的成绩并成功结营。

完成「启航计划」的学员将有机会获得**丰厚的奖励 🎁 和荣誉证书 📃**。此外，表现出色的开发者还有机会成为「**护航计划**」的潜在候选人，进一步参与到更具挑战性的任务中。我们期待与你一同踏上这个激动人心的学习和成长之旅 ！快来加入我们吧～～ 💓

> [!IMPORTANT]  
> 与「护航计划」的区别：
>
>   * 不限定开发者背景，企业和学生开发者均可参与。
>   * 不进行面试，直接进行简历筛选。
>   * 合入1个 专项团PR 即满足结营条件，相对轻松愉快。
>   * 时间周期更短。能让没接触过飞桨的你，快速上手飞桨开源活动。

## 报名方式

1. 在本issue下方**评论回复**，格式如下，注意编号1~5对应各个专项团。

```
【报名】：1
【其他意向】：2、4、5
不接受调剂
```

2. **同时发送邮件**至📮 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，邮件主题为【启航计划报名-姓名】，需说明**GitHub ID**和报名意向，并附上简历（必须）和技术能力证明材料（如有）。

> [!IMPORTANT]
> 报名截止至 **2024 年 7 月 8 日**，通过筛选后，将会收到**确认邮件，请正式回复是否参加**。

### 一、集训内容

1. **集训任务**：
   完成【快乐开源】**热身任务**，并完成专项团内感兴趣的**专题任务**。
   * 必修：完成所有**热身打卡任务**（为方便统计完成情况，请大家在「a. 修改飞桨文档」任务PR**合入后**发送邮件至📮 [ext_paddle_oss@baidu.com](mailto:ext_paddle_oss@baidu.com)，主题为【启航计划文档打卡-姓名】，并附上PR链接。其余两个打卡任务按要求发送邮件即可。）
     1. [修改飞桨文档](https://github.com/PaddlePaddle/Paddle/issues/56689#warmup-tasks-1)
     2. [完成 Paddle 本地编译](https://github.com/PaddlePaddle/Paddle/issues/56689#warmup-tasks-2)
     3. [Stable-Diffusion 训练推理](https://github.com/PaddlePaddle/PaddleMIX/issues/273)
2. **任务形式**：以**PR合入**为任务完成标志。针对相同任务的PR，以最先合入的为准。
3. **开发辅导**： 特设**如流群**与导师和助教进行日常沟通答疑，并设有**每周例会**（导师可视情况调整频次）同步进展、技术答疑、分享心得
4. **双周周报**： 每双周总结集训成果、技术成长或感悟，集训营总助教（非专项团助教）负责统一管理。https://github.com/PFCCLab/Starter/issues/3

> [!WARNING]  
> **未提交双周周报** 则视为放弃集训计划‼️ 😐

### 二、结营考核

1. 结营要求：满足最低要求，方可顺利结营。
   1. 最低要求：**至少合入一个专项团 PR** ✅
   2. 加分项：合入较多PR，或合入难度较大的PR；沉淀技术思考、提出可行性建议、甚至主导开展新任务等。
2. 结营成绩：
   1. 不通过：未满足最低要求。  
   2. 通过：满足最低要求，即可毕业。
   3. 优秀：满足最低要求，同时在活动过程中有加分项。
3. 结营奖励：
   1. 不通过：无。
   2. 通过：结营荣誉证书 📃 与 精美礼品 🎁。
   3. 优秀：
      * 结营荣誉证书 📃 与 精美礼品 🎁 ；
      * 进入【护航计划】候选；
      * 可申请一、二、三等奖的答辩（申请制）。

> [!NOTE]  
> 一、二、三等奖各 1 个，共 3 人。需表现优秀的开发者**主动申请并答辩**，并由评委小组进行综合评估。如无满足条件者则奖项空缺。
>
>  * 一等奖：iPad (第十代) 💻
>  * 二等奖：Apple Watch SE ⌚️
>  * 三等奖：Airpods（第三代）🎧

### 三、日程计划

这是我们为本期启航计划制定的详细日程和计划 ⬇️ 

| **时间**                 | **日程**                                        |
| ------------------------ | ----------------------------------------------- |
| **2024.6.24**            | 正式启动报名                                    |
| **2024.6.26 20:00**      | 线上说明会                                      |
| **2024.6.24 ~ 2024.7.15** | 持续公开接收简历，进行筛选，确定助教（2 weeks） |
| **2024.7.17 19:00**       | 集训项目启动，直播kickoff                       |
| **2024.7.17 ～ 2024.9.9** | 参与集训项目（8 weeks）                         |
| **2024.9.9 ～ 2024.9.16** | 申请并完成一、二、三等奖答辩（1 week）          |
| **2024.9.17 23:59**      | 集训营结营，公布考核结果                        |

**开营仪式**

我们会在集训营正式开始时为大家举办一个线上见面会，在这里可以认识班主任、助教、导师和其他学员，结交到志同道合的好友 👯

最后：
- 本次未筛选通过的开发者，也可以认领[快乐开源](https://github.com/PaddlePaddle/Paddle/issues/61482)任务哦～合入PR仍会获得快乐开源的礼品～
- 可以先加运营同学的企业微信，她会拉你进入快乐开源交流群
<img width="166" alt="image" src="https://user-images.githubusercontent.com/6836917/195274459-1a47c60b-c73e-4d0a-b38b-70d844799d05.png"> 

## 统计信息 
> 排名不分先后 
#####

**Comment by freejager** [comment]
【报名】：5
【其他意向】：1、2、3、4
接受调剂

**Comment by pleasegivemeastar** [comment]
【报名】：5
【其他意向】：4、1、2、3
  接受调剂

**Comment by freejager** [comment]
收到，我愿意参加



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月20日(周四) 下午4:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [PaddlePaddle/Paddle] 【HACKATHON 预备营】飞桨启航计划集训营（第三期） (Issue #65279)




 
【报名】：5
 【其他意向】：4、1、2、3
 接受调剂

**Comment by cuishitan** [comment]
【报名】：2
【其他意向】：1、3、4、5
接受调剂

**Comment by Felix-Zhenghao** [comment]
【报名】：3
【其他意向】：4、5
不接受调剂

**Comment by entired** [comment]
【报名】：1
【其他意向】：2、3、4、5
接受调剂

**Comment by Kaedeharai** [comment]
【报名】：3
【其他意向】：1、2
不接受调剂

**Comment by 123456-ICEN** [comment]
【报名】：1
【其他意向】：2、3、4、5
接受调剂

**Comment by Lubenwei-nb123** [comment]
【报名】：3
【其他意向】：2、4、5
接受调剂

**Comment by AIzealotwu** [comment]
【报名】：5
【其他意向】：
不接受调剂

**Comment by ssy-lbh** [comment]
【报名】：2
【其他意向】：3、4、5
不接受调剂

**Comment by ykdcai** [comment]
【报名】：3
【其他意向】：2、5、1
接受调剂

**Comment by Marcusryz** [comment]
【报名】：2
【其他意向】：3、4、1、5
接受调剂

**Comment by EgoistSA** [comment]
【报名】：5
【其他意向】：1，3
接受调剂

**Comment by dongjinkun** [comment]
【报名】：4
【其他意向】：5、2、1、3
接受调剂

**Comment by Dale1314** [comment]
【报名】：4
【其他意向】：3、5
不接受调剂

**Comment by smallpoxscattered** [comment]
【报名】：3
【其他意向】：2、4、5
接受调剂

**Comment by Betelgeu** [comment]
【报名】：3
【其他意向】：5、4、2
不接受调剂

**Comment by InsaneOnion** [comment]
【报名】：5
【其他意向】：3
不接受调剂

**Comment by MikhayEeer** [comment]
【报名】：3
【其他意向】：2、4、5
不接受调剂

**Comment by Xingyyy01** [comment]
【报名】：5
【其他意向】：3、4
不接受调剂
​

**Comment by Turingg** [comment]
【报名】：3
【其他意向】：1
不接受调剂

**Comment by Wang-ZengWei** [comment]
【报名】：1
【其他意向】：2、3
不接受调剂

**Comment by HuaSakuLoop** [comment]
【报名】：1
【其他意向】：2、3、5
接受调剂

**Comment by yeteye** [comment]
【报名】：5
【其他意向】：1，3
接受调剂

**Comment by brcarry** [comment]
【报名】：5
【其他意向】：2、3、4
接受调剂

**Comment by GoldenStain** [comment]
【报名】：3
【其他意向】：2、4、5、1
接受调剂

**Comment by bruce2233** [comment]
【报名】：5
【其他意向】：3
不接受调剂

**Comment by Fz-TvT** [comment]
【报名】：2
【其他意向】：5
不接受调剂

**Comment by yyBlone** [comment]
【报名】：2
【其他意向】：1、3、4、5
接受调剂

**Comment by successfulbarrier** [comment]
【报名】：5
【其他意向】：3、4
不接受调剂

**Comment by yyBlone** [comment]
杨研博确认参加




杨研博04201304
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月10日(星期三) 上午10:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[PaddlePaddle/Paddle] 【HACKATHON 预备营】飞桨启航计划集训营（第三期） (Issue #65279)





 
Note

接收简历时间延长一周至7月15日，开营、结营时间依次顺延。炎炎暑期，少年不来开源一夏吗？🏖️
 
 
飞桨启航计划简介
 
「启航计划」 是 飞桨开源社区 发起的远程项目，也是「护航计划」的前置活动（护航计划详情请看这里 ➡️ 护航计划说明）。我们以开展线上集训营的形式，鼓励开发者积极参与开源项目，以此提升自己的代码实践能力，与社区共同成长 💪。
  
第一期「启航计划」看这里 ➡️ #58497
 第二期「启航计划」看这里 ➡️ #62347
  
开发者提交申请材料并通过后，将会参与为期2个月密集的线上集训项目，目标是尽可能多且高质量地完成开源任务 。为给大家更多引导，提高参与感，本期「启航计划」将特别保留专项团制度，每一位参与的同学都可以得到飞桨研发同学的指导。🧑‍🏫🧑‍🏫🧑‍🏫
 
当前可供选择的专项团列表如下：
  
营员要求：熟悉 Python 和 C++，对深度学习技术有一定了解，有深度学习框架应用和研发经验
     编号 团名 tracking issue &amp; 导师信息 报名情况 锁定营员 
    1 专项团：文档 Paddle Docathon 文档系列活动
导师：sunzhongkai588 助教：ooooo-create @entired  
 @123456-ICEN  
@Wang-ZengWei  
 @haoyu2022  
  
  2 专项团：复数 【complex op】paddlepaddle 支持复数
导师：zhiminzhang0830 助教：zbt78 @cuishitan  
@ssy-lbh  
@Marcusryz  
@struim  
 @yyBlone  
  
  3 专项团：基础框架 飞桨 IR 快乐开源活动表单
【快乐开源】报错日志体系优化
导师：Aurelius84  助教：待定 @Felix-Zhenghao  
 @Kaedeharai  
 @Lubenwei-nb123  
@ykcai-daniel  
@smallpoxscattered  
@Betelgeu  
@MikhayEeer  
 @Turingg  
@GoldenStain  
  
  4 专项团：科学计算 PaddleScience 快乐开源活动表单
导师：HydrogenSulfate 助教：待定 @dongjinkun  
 @Dale1314  
  
  5 专项团：大模型套件 PaddleMIX快乐开源活动表单
导师：LokeZhou 助教：待定 @freejager  
 @pleasegivemeastar  
@AIzealotwu  
@EgoistSA  
@InsaneOnion  
 @Xingyyy01  
@yeteye  
@brcarry  
@bruce2233  
@successfulbarrier  
  
   
集训期间，我们会提供研发支持🧑🏻‍💻、随时随地都能使用的线上 V100 开发环境 🔧（申请方式看这里 ➡️ 飞桨线上开发环境——AI Studio星河社区）以帮助学员更好地融入项目，不断提升技术水平。我们鼓励学员积极互动和交流，希望每位学员都能够在集训期结束时取得优异的成绩并成功结营。
 
完成「启航计划」的学员将有机会获得丰厚的奖励 🎁 和荣誉证书 📃。此外，表现出色的开发者还有机会成为「护航计划」的潜在候选人，进一步参与到更具挑战性的任务中。我们期待与你一同踏上这个激动人心的学习和成长之旅 ！快来加入我们吧～～ 💓
 
Important

与「护航计划」的区别：
  
不限定开发者背景，企业和学生开发者均可参与。
 
不进行面试，直接进行简历筛选。
 
合入1个 专项团PR 即满足结营条件，相对轻松愉快。
 
时间周期更短。能让没接触过飞桨的你，快速上手飞桨开源活动。
  
 
报名方式
  
在本issue下方评论回复，格式如下，注意编号1~5对应各个专项团。
  【报名】：1 【其他意向】：2、4、5 不接受调剂   
同时发送邮件至📮 ***@***.***，邮件主题为【启航计划报名-姓名】，需说明GitHub ID和报名意向，并附上简历（必须）和技术能力证明材料（如有）。
  
Important

报名截止至 2024 年 7 月 8 日，通过筛选后，将会收到确认邮件，请正式回复是否参加。
 
 
活动安排
 
一、集训内容
  
集训任务：
 完成【快乐开源】热身任务，并完成专项团内感兴趣的专题任务。  
必修：完成所有热身打卡任务（为方便统计完成情况，请大家在「a. 修改飞桨文档」任务PR合入后发送邮件至📮 ***@***.***，主题为【启航计划文档打卡-姓名】，并附上PR链接。其余两个打卡任务按要求发送邮件即可。）  
修改飞桨文档
 
完成 Paddle 本地编译
 
Stable-Diffusion 训练推理
  
  
 
任务形式：以PR合入为任务完成标志。针对相同任务的PR，以最先合入的为准。
 
开发辅导： 特设如流群与导师和助教进行日常沟通答疑，并设有每周例会（导师可视情况调整频次）同步进展、技术答疑、分享心得
 
双周周报： 每双周总结集训成果、技术成长或感悟，集训营总助教（非专项团助教）负责统一管理。PFCCLab/Starter#3
  
Warning

未提交双周周报 则视为放弃集训计划‼️ 😐
 
 
二、结营考核
  
结营要求：满足最低要求，方可顺利结营。  
最低要求：至少合入一个专项团 PR ✅
 
加分项：合入较多PR，或合入难度较大的PR；沉淀技术思考、提出可行性建议、甚至主导开展新任务等。
  
 
结营成绩：  
不通过：未满足最低要求。
 
通过：满足最低要求，即可毕业。
 
优秀：满足最低要求，同时在活动过程中有加分项。
  
 
结营奖励：  
不通过：无。
 
通过：结营荣誉证书 📃 与 精美礼品 🎁。
 
优秀：  
结营荣誉证书 📃 与 精美礼品 🎁 ；
 
进入【护航计划】候选；
 
可申请一、二、三等奖的答辩（申请制）。
  
  
  
Note

一、二、三等奖各 1 个，共 3 人。需表现优秀的开发者主动申请并答辩，并由评委小组进行综合评估。如无满足条件者则奖项空缺。
  
一等奖：iPad (第十代) 💻
 
二等奖：Apple Watch SE ⌚️
 
三等奖：Airpods（第三代）🎧
  
 
三、日程计划
 
这是我们为本期启航计划制定的详细日程和计划 ⬇️
    时间 日程 
    2024.6.24 正式启动报名 
  2024.6.26 20:00 线上说明会 
  2024.6.24 ~ 2024.7.15 持续公开接收简历，进行筛选，确定助教（2 weeks） 
  2024.7.15 20:00 集训项目启动，直播kickoff 
  2024.7.15 ～ 2024.9.9 参与集训项目（8 weeks） 
  2024.9.9 ～ 2024.9.16 申请并完成一、二、三等奖答辩（1 week） 
  2024.9.17 23:59 集训营结营，公布考核结果 
   
开营仪式
 
我们会在集训营正式开始时为大家举办一个线上见面会，在这里可以认识班主任、助教、导师和其他学员，结交到志同道合的好友 👯
 
最后：
  
本次未筛选通过的开发者，也可以认领快乐开源任务哦～合入PR仍会获得快乐开源的礼品～
 
可以先加运营同学的企业微信，她会拉你进入快乐开源交流群
  

  
统计信息
  
排名不分先后

**Comment by inaomIIsfarell** [comment]
【报名】：3
【其他意向】：1、2、4、5
接受调剂

**Comment by developWmark** [comment]
【报名】：5
【其他意向】：
不接受调剂

**Comment by Sekiro-x** [comment]
【报名】：3
【其他意向】：2、4、5
不接受调剂

**Comment by fufu0615** [comment]
【报名】：4
【其他意向】：2、3
接受调剂

**Comment by Aoraki-Dream** [comment]
【报名】：5
【其他意向】：2、3、4、1
接受调剂

**Comment by sunzhongkai588** [comment]
启航计划已于 9 月 27 日正式结营
