### ISSUE TITLE
pipe_read()第二轮训练读不到数据

### ISSUE THREAD

**Issue by jeromeJT** [PaddlePaddle/Paddle#6529]
第一轮训练正常输出结果
第二轮开始直接报ZeroDivisionError: float division by zero
  File "/home/map/paddle_env/python27-gcc482/lib/python2.7/site-packages/paddle/v2/trainer.py", line 220, in test
    evaluator=evaluator, cost=total_cost / num_samples)
ZeroDivisionError: float division by zero

check发现是api代码中，只在开始的时候调用了一次process = subprocess.Popen(left_cmd.split(" "), bufsize=bufsize, stdout=subprocess.PIPE)
数据读完之后，没用重新打开，所以第二轮训练读不到数据

辛苦paddlepaddle的同学给出解决方法，谢谢

**Comment by sweetsky0901** [comment]
试试看看 https://github.com/PaddlePaddle/Paddle/issues/1329

**Comment by fiendark** [comment]
遇到了一模一样的问题。第二轮训练出错。没有用dataprovider，自定义了一个reader。似乎和#1329描述无关。 @sweetsky0901

**Comment by fiendark** [comment]
这个问题，你现在解决了吗 @jeromeJT
