### ISSUE TITLE
macOS arm64 版本 whl 安装包中 paddlepaddle-x.x.x.dist-info 文件夹中生成的 WHEEL 文件 Tag 为 universal2

### ISSUE THREAD

**Issue by leovan** [PaddlePaddle/Paddle#65338]
### bug描述 Describe the Bug

macOS arm64 版本 whl 版本 whl 安装包中 paddlepaddle-x.x.x.dist-info 文件夹中生成的 WHEEL 文件 Tag 为 cp310-cp310-macosx_11_0_universal2，但这并非是一个 universal2 版本。这导致一些软件 https://github.com/beeware/briefcase/blob/main/src/briefcase/platforms/macOS/utils.py#L59 错误的将其识别为 universal2 版本，从而在打包 universal2 版本应用时出现问题（paddle/base/libpaddle.so (fat file, but missing compatible architecture (have 'arm64', need 'x86_64h' or 'x86_64'))）。Tag 应修改为 cp310-cp310-macosx_11_0_arm64。

**Comment by risemeup1** [comment]
最新的包已经没这个问题了，https://www.paddlepaddle.org.cn/packages/nightly/cpu/paddlepaddle/，自己找下

**Comment by leovan** [comment]
感谢回答
