### ISSUE TITLE
按照官方文档的to_tensor示例, 输出结果与期待不符合

### ISSUE THREAD

**Issue by achieve-dream1221** [PaddlePaddle/Paddle#65345]
### bug描述 Describe the Bug

```python
import paddle
import numpy as np

print(paddle.__version__)
print(np.__version__)
a = paddle.to_tensor([[0.1, 0.2], [0.3, 0.4]], place=paddle.CPUPlace(), stop_gradient=False)
print(a)
```

```
2.6.1
2.0.0
Tensor(shape=[2, 2], dtype=float32, place=Place(cpu), stop_gradient=False,
       [[0.        , 0.        ],
        [0.        , 0.00000000]])
```
# 实际输出
![image](https://github.com/PaddlePaddle/Paddle/assets/57209087/828abad8-f5d5-4b84-b6f4-8bb424798ca5)
# 期待输出
![image](https://github.com/PaddlePaddle/Paddle/assets/57209087/18ba9d3e-078b-4d99-8012-f2832352dea8)
[参考链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/to_tensor_cn.html)

**Comment by YanhuiDua** [comment]
你好，可以切换到develop版本，develop版本中这个问题已经被修复~

**Comment by YanhuiDua** [comment]
我这里是Paddle 2.6.1 + numpy 1.24.4，结果也是没问题的；可以尝试下降低numpy的版本
![image](https://github.com/PaddlePaddle/Paddle/assets/45005871/a4236026-f03d-4761-9432-90db2ef51e7c)

**Comment by achieve-dream1221** [comment]
> 我这里是Paddle 2.6.1 + numpy 1.24.4，结果也是没问题的；可以尝试下降低numpy的版本 ![image](https://private-user-images.githubusercontent.com/45005871/341655761-a4236026-f03d-4761-9432-90db2ef51e7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5NjA3MjIsIm5iZiI6MTcxODk2MDQyMiwicGF0aCI6Ii80NTAwNTg3MS8zNDE2NTU3NjEtYTQyMzYwMjYtZjAzZC00NzYxLTk0MzItOTBkYjJlZjUxZTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIxVDA5MDAyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUwZDU2NThkZGI1MTVmOGNhZmQ1NjM3NGE0OTY3Y2ZkZjE4YmIyYzI3YzQ3ZjgwZWYwMDc1YTJhNjI5ZGJkMTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VXNsX_FXBNrKWhUOzo1ZvKrhzCvNgtwkojNcKEjDvPM)

我将numpy降到1.26.4, 也能成功运行
![image](https://github.com/PaddlePaddle/Paddle/assets/57209087/471a9ff2-82aa-44fa-8eb8-652ebc021239)
