### ISSUE TITLE
fluid 训练模型，其他条件相同时，多次运行结果为何不一致？

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6535]
训练模型时，其他条件相同，(代码等也不做任何修改)，先后运行两次，输出的训练误差信息不同，这是为何？

**Comment by jacquesqiao** [comment]
数据会shuffer，去掉shuffer试试

**Comment by ranqiu92** [comment]
去掉shuffle后也不一致。代码中会人为设置 initializer，但并未设置seed，两次运行时，网络初始化参数 应该一样的吧？这样的话，结果不一致有些奇怪。

**Comment by ranqiu92** [comment]
默认状态下，fluid参数初始化使用的随机种子随机，所以每次运行时网络参数的初始值不同，导致运行结果不同。
