### ISSUE TITLE
PaddlePaddle新年大礼！周边产品送不停！

### ISSUE THREAD

**Issue by shangguanyifeng** [PaddlePaddle/Paddle#6542]
感受到了小伙伴们的爱和期待，新年礼物紧锣密鼓准备中。受到双十二及物流调整问题影响
预计**礼物会在12月22日-12月26日发出**~~**争取在元旦前到达全部小伙伴手中！**
此期间持续接收邮件哦！

——————————————我是可爱的分隔线——————————————————
各位亲爱的PaddlePaddle用户：
2017年已进入尾声，感谢你们一直陪伴PaddlePaddle在深度学习领域共同成长，无论是应用、贡献、还是review、纠错；每一个人的付出对于PaddlePaddle都是至关重要的。**值此新年，PaddlePaddle准备了一批周边小礼物赠送给各位，与各位一同迎接更好的2018！PaddlePaddle，一起加油！**

**周边礼物领取方式如下：**
请各位使用者、贡献者将**如下信息**发到**PaddlePaddle-TechWriter@baidu.com**
【**“姓名“+“github账号名” +“周边礼物快递邮寄地址”+”快递联系电话“+”定制卫衣号码（S：160，M：165：L：170，XL：175，xxL：180）“**】→发到PaddlePaddle-TechWriter@baidu.com
我们会根据邮件中的地址为您送上PaddlePaddle周边礼物一份。
您也可以同时回复此issue-”你对PaddlePaddle的祝福和嘱咐“或“PaddlePaddle，一起加油！”来提醒我们查收您的邮件。

# **礼物内容如下：**
每位发送邮件的用户都能获得**PaddlePaddle礼袋一个，内置“LOGO卫衣+贴纸+纪念小徽章“**
![12131](https://user-images.githubusercontent.com/32129961/33899942-f07ad210-dfa7-11e7-9c96-ec45539ad0af.png)

# 重要贡献用户随机加发下列周边产品之一：
## **PaddlePaddle定制款-膳魔师保温水杯**
![12132](https://user-images.githubusercontent.com/32129961/33899987-0edde01c-dfa8-11e7-95a7-b8304a58b078.png)

## **PaddlePaddle定制款-机械键盘**
![12133](https://user-images.githubusercontent.com/32129961/33900027-2e74ff6e-dfa8-11e7-9ec0-0d5396107593.png)

## **PaddlePaddle定制款-树莓派**
![12134](https://user-images.githubusercontent.com/32129961/33900121-6ec1b0ee-dfa8-11e7-8ecf-8885e984e36d.png)

**# 如有其他疑问，可以直接回复本issue~~感谢大家的支持！**

**Comment by xiangjinxin1019** [comment]
PaddlePaddle，一起加油！

**Comment by BlankRain** [comment]
默默潜水暗中观察还没有能力为社区做贡献的同学能不能有礼物?

**Comment by leochen86** [comment]
PaddlePaddle，一起加油！

**Comment by solomance** [comment]
PaddlePaddle，一起加油！

**Comment by cszhou** [comment]
PaddlePaddle，一起加油！

**Comment by SmallZa** [comment]
PaddlePaddle，一起加油

**Comment by autowang** [comment]
PaddlePaddle，一起加油！

**Comment by wangtao169447** [comment]
PaddlePaddle，一起加油！

**Comment by BlankRain** [comment]
PaddlePaddle，一起加油！

**Comment by aiwujie** [comment]
PaddlePaddle，一起加油！

**Comment by s-xq** [comment]
PaddlePaddle，一起加油！

**Comment by lazxer** [comment]
PaddlePaddle，一起加油！

**Comment by ViviLin** [comment]
PaddlePaddle，一起加油！

**Comment by buptwds** [comment]
PaddlePaddle，一起加油

**Comment by zhaopu7** [comment]
PaddlePaddle，加油干！

**Comment by rolytimez** [comment]
PaddlePaddle，一起加油！

**Comment by wangsouc** [comment]
PaddlePaddle，一起加油！

**Comment by zhaopu7** [comment]
PaddlePaddle，一起加油！

**Comment by zhuyinglinfeng** [comment]
PaddlePaddle，一起加油！

**Comment by whazmy** [comment]
PaddlePaddle，一起加油！

**Comment by chao-er** [comment]
PaddlePaddle，一起加油！

**Comment by Angela-shi** [comment]
PaddlePaddle，一起加油！

**Comment by huangjiaxin** [comment]
PaddlePaddle，一起加油！

**Comment by wjl84945979** [comment]
PaddlePaddle，一起加油！

**Comment by Anthonyweng** [comment]
PaddlePaddle，一起加油！

**Comment by Bella-Zhao** [comment]
PaddlePaddle，一起加油！

**Comment by daichengchao** [comment]
PaddlePaddle，一起加油！

**Comment by karryTata** [comment]
PaddlePaddle，一起加油！

**Comment by ckeys** [comment]
PaddlePaddle，一起加油！

**Comment by wangkuiyi** [comment]
PaddlePaddle，一起加油！

**Comment by taoziliu** [comment]
PaddlePaddle，一起加油！

**Comment by Yukizzz** [comment]
PaddlePaddle，一起加油！

**Comment by winterfell30** [comment]
PaddlePaddle，一起加油！

**Comment by tigerneil** [comment]
PaddlePaddle，一起加油！

**Comment by adniws** [comment]
PaddlePaddle，一起加油！

**Comment by tongjt** [comment]
PaddlePaddle，一起加油！

**Comment by gangliao** [comment]
PaddlePaddle，一起加油！

**Comment by yyRifle** [comment]
一起加油！

**Comment by pakchoi** [comment]
PaddlePaddle，一起加油！

**Comment by skyjia** [comment]
PaddlePaddle，一起加油！

**Comment by yyRifle** [comment]
PaddlePaddle，一起加油！

**Comment by huxiaoman7** [comment]
PaddlePaddle，一起加油！

**Comment by NHZlX** [comment]
PaddlePaddle，一起加油！

**Comment by tanzhongyibidu** [comment]
PaddlePaddle，一起加油！

**Comment by ceciliacai001** [comment]
PaddlePaddle，一起加油！

**Comment by zhangzhenyue1** [comment]
PaddlePaddle，一起加油

**Comment by livc** [comment]
PaddlePaddle，一起加油！

**Comment by tensor-tang** [comment]
PaddlePaddle，一起加油！

**Comment by yeyupiaoling** [comment]
我们一起努力，让paddlepaddle成为最流行的深度学习框架

**Comment by yukang2017** [comment]
由于项目需要近一个月以来一直在用paddle，因为各种问题不断地线上线下骚扰paddle组的师兄们。真的能感受到paddle组的师兄师姐们很负责很耐心地帮我解决各种问题，经常停下手头的事替我解决。能感受到Paddle在不断完善。希望能有更多的人使用PaddlePaddle。

**Comment by memorycancel** [comment]
PaddlePaddle，一起加油！

**Comment by dqcao** [comment]
PaddlePaddle，一起加油！

**Comment by jayhenry** [comment]
PaddlePaddle，一起加油！

**Comment by spencerlisp** [comment]
PaddlePaddle，一起加油！

**Comment by devindo** [comment]
PaddlePaddle，一起加油！

**Comment by zlinker** [comment]
PaddlePaddle，一起加油！

**Comment by 333caowei** [comment]
PaddlePaddle，一起加油！

**Comment by justbelieveyourself** [comment]
PaddlePaddle，一起加油！

**Comment by manifoldQAQ** [comment]
PaddlePaddle，一起加油！

**Comment by JessieMeng** [comment]
PaddlePaddle,一起加油！送个水杯！❤

**Comment by superdanta** [comment]
PaddlePaddle,一起加油！

**Comment by crazyofapple** [comment]
PaddlePaddle,一起加油！

**Comment by wybinos** [comment]
PaddlePaddle，一起加油！

**Comment by maxiao001** [comment]
PaddlePaddle，一起加油！

**Comment by xiaoziyao** [comment]
PaddlePaddle，一起加油！

**Comment by pardy218** [comment]
PaddlePaddle，一起加油！

**Comment by Yo641-10** [comment]
PaddlePaddle，一起加油！

**Comment by aviva159** [comment]
PaddlePaddle，一起加油！

**Comment by xiazhicheng** [comment]
PaddlePaddle，一起加油！

**Comment by Accool** [comment]
PaddlePaddle，一起加油！

**Comment by yaochenkun** [comment]
PaddlePaddle，一起加油！

**Comment by zlren** [comment]
PaddlePaddle，一起加油！

**Comment by liuyaqiu** [comment]
PaddlePaddle，一起加油！

**Comment by breaknormal1** [comment]
PaddlePaddle，撸起袖子加油干！

**Comment by breaknormal1** [comment]
PaddlePaddle，一起加油！

**Comment by yyydido** [comment]
PaddlePaddle，一起加油！
（树莓派！树莓派！）

**Comment by wanghaoshuang** [comment]
PaddlePaddle，一起加油！

**Comment by jacquesqiao** [comment]
PaddlePaddle，一起加油！

**Comment by jinfagang** [comment]
怎么申请礼物啊，我的博客已经写满了paddlepaddle的教程

**Comment by leywing** [comment]
PaddlePaddle，一起加油！

**Comment by BlankRain** [comment]
感谢感谢,麻袋已经收到了..

**Comment by shangguanyifeng** [comment]
@ jinfagang  详情看上方说明

**Comment by wangpeiing** [comment]
PaddlePaddle，一起加油！

**Comment by fantasycheung** [comment]
PaddlePaddle，一起加油！

**Comment by LightGal** [comment]
PaddlePaddle，一起加油！

**Comment by jshower** [comment]
PaddlePaddle，一起加油！
