### ISSUE TITLE
Should we rename ProgramDescBind to ProgramDesc?

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#6544]
When looking at the `ProgramDescBind`, my first impression is it's only an auxiliary class for `ProgramDesc`. But actually it's the real "ProgramDesc" that gets passed between modules (e.g., gets passed into Executor), the current `ProgramDesc` is just a proto c++ class for the wire format.

I think to avoid confusion, we should rename `ProgramDescBind` (already lives in `program_desc.cc`) to `ProgramDesc`, and put the current `ProgramDesc` under proto namespace (or rename to `ProgramDescProto`).

How do you guys think?

**Comment by reyoung** [comment]
If we decide to do this, I can help to rename this class, since `rename` is easier by IDE.

**Comment by reyoung** [comment]
I will complete this issue by following steps:

1. Move `framework.proto` to proto namespace
  * issue #6739
2. Rename `XXXBind` to `XXX`
