### ISSUE TITLE
L1/ L2 regularization

### ISSUE THREAD

**Issue by ziyenano** [PaddlePaddle/Paddle#6548]
I need to regularize the dropout(or fc) laryer with L1/ L2 norm, and how to implement  it in paddle?
Thanks in advance!

**Comment by lcy-seso** [comment]
Could you please give more details about the computation you need.
1. Here, what do you mean by "regularize". Does it mean a regularizer added to the cost of the entire network?
1. If you have a paper that proposes this work, could you please add it as the reference.

**Comment by ziyenano** [comment]
Right, add a regularizer to the loss function in order to avoid the networks weights growing very large. 
http://www.jmlr.org/papers/volume15/srivastava14a/srivastava14a.pdf?utm_content=buffer79b43&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer
See the Appendix A.3 in this paper.
https://pgaleone.eu/deep-learning/regularization/2017/01/10/anaysis-of-dropout/
This blog also points out putting regularization together with dropout.

**Comment by lcy-seso** [comment]
Thanks for your reference.

What you want is quite simple and straightforward. Just set the `l2_decay_rate` and `droprate` at the same time.

**Comment by ziyenano** [comment]
I will try it, and thanks again!

**Comment by typhoonzero** [comment]
Closing this for now, we shall open another issue to describe the documentation issues with "documentation" tag.
