### ISSUE TITLE
auto data sync between different devices

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#6549]
project: https://github.com/PaddlePaddle/Paddle/issues/6403
In a sequence of operators, when some of them run on GPU, some can only run on CPU,  we need to auto add some operators to copy host memory and device memory, so the whole graph can run in a multi devices environment.

## some problem 
1.  now we use name to get var in scope, and data on different devices should have different names, if we add some operator to sync data between different devices, we should change the input name of corresponding operators.

**Comment by jacquesqiao** [comment]
after discussion, there are several ways to implement this:

1.  auto copy data in OperatorWithKernel::Run() according to device.
2. auto copy data in Tensor::data(const Device& device);
3. add some op to copy data(not a good way).
4. use CUDA Unified Memory.(https://devblogs.nvidia.com/parallelforall/unified-memory-in-cuda-6/)

so I will do a survey on CUDA Unified Memory first.

**Comment by tensor-tang** [comment]
I think it's important and it should not only be `copy` itself.

This `sync` mechanism should contain many kinds of conversions through devices, like `CPUPlace`, `GPUPlace`, and maybe `MKLDNN`, `FPGA` later.

I hope it can reserve a interface to let developers implement this sync between different `Place`.

**Comment by jacquesqiao** [comment]
@tensor-tang cool, that is a good suggestion!

**Comment by luotao1** [comment]
The memory of MKLDNN is different from Paddle, and you can refer to https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/mkldnn#layers
