### ISSUE TITLE
design doc of packed MKL for RNN

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#6553]
We need add design doc for the RNN layers optimizations, which we used packed MKL.

contents like below?

- What's is Packed MKL
- Impelements
  - Recurrent Layers
  - GRU
  - LSTM
- Python API

**Comment by luotao1** [comment]
1. Packed MKL->Packed MKLML? Recurrent Layers->Vanilla RNN?
2. Implements->Implements and Key Points?
3. What's the title of this design doc, and where to put it?
4. The design doc can be Chinese first.

**Comment by tensor-tang** [comment]
> 1. Packed MKL->Packed MKLML? Recurrent Layers->Vanilla RNN?

还是用Packed MKL 比较好，MKLML主要是指那个library，这里指代的不应该是针对Library本身的。

> 2. Implements->Implements and Key Points?

这个我觉得没什么问题，或者把Key Points什么的放到最后，单独一项，如果需要的话。

> 3. What's the title of this design doc, and where to put it?

`doc/design/mkldnn/README.md` ==> `doc/design/mkl/mkldnn.md`
add `doc/design/mkl/packed_mkl.md` ?

> 4.The design doc can be Chinese first.

No problem.
