### ISSUE TITLE
paddle.create_parameter 的参数名

### ISSUE THREAD

**Issue by zhangxiaokai111** [PaddlePaddle/Paddle#65535]
### 请提出你的问题 Please ask your question

代码里会多次使用这个函数。它是否需要给layers的name?如果没有给定name，每次调用的参数会不会共享的吗？

**Comment by pkuzyc** [comment]
create_parameter 创建的不同变量不共享内存，paddle也会为不同参数自动创建不同的名称

**Comment by heavyrain-lzy** [comment]
进一步可以参考官方文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/create_parameter_cn.html
