### ISSUE TITLE
如何将动态图的模型参数转存为静态图

### ISSUE THREAD

**Issue by YzM1a0** [PaddlePaddle/Paddle#65556]
### 请提出你的问题 Please ask your question

有一个模型的预训练参数：OPEN_ERNIE_VIL2_BASE_ViT.pdparams。但是项目里的代码是用下图这样的热启方式，所以需要按参数将模型拆开存储。但是当我加载预训练参数以后，按照这样的方式，用 paddle.save()按参数存储后，用上图的热启方式会报错，报错如下。但是当我用 paddle.load() 时，可以正常加载参数，请问一下如何才能正确将模型按参数存下来呢。
![image](https://github.com/PaddlePaddle/Paddle/assets/52202139/ae191e45-f1ab-4a63-8f80-bd4bc54c5487)
![image](https://github.com/PaddlePaddle/Paddle/assets/52202139/65ab9498-fdd5-41e8-a886-b39f7c067379)
![image](https://github.com/PaddlePaddle/Paddle/assets/52202139/b21d6c77-d687-405d-8548-076f34a2d24d)

**Comment by pkuzyc** [comment]
动态图参数保存为静态图的话可以看下 paddle.jit.save 这个方法是否满足需求，模型保存加载可以看这个文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/model_save_load_cn.html

**Comment by pkuzyc** [comment]
动态图参数保存为静态图的话可以看下 paddle.jit.save 这个方法是否满足需求，模型保存加载可以看这个文档 https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/beginner/model_save_load_cn.html
