### ISSUE TITLE
example文件里面的dense demo， 无法通过交叉编译

### ISSUE THREAD

**Issue by zhuyinglinfeng** [PaddlePaddle/Paddle#6556]
Scanning dependencies of target dense
[ 50%] Building C object CMakeFiles/dense.dir/main.c.o
[100%] Linking C executable dense
Undefined symbols for architecture x86_64:
  "_paddle_arguments_create_none", referenced from:
      _main in main.c.o
  "_paddle_arguments_destroy", referenced from:
      _main in main.c.o
  "_paddle_arguments_get_value", referenced from:
      _main in main.c.o
  "_paddle_arguments_resize", referenced from:
      _main in main.c.o
  "_paddle_arguments_set_ids", referenced from:
      _main in main.c.o
  "_paddle_arguments_set_dense_start_pos", referenced from:
      _main in main.c.o
  "_paddle_gradient_machine_create_for_inference", referenced from:
      _main in main.c.o
  "_paddle_gradient_machine_destroy", referenced from:
      _main in main.c.o
  "_paddle_gradient_machine_forward", referenced from:
      _main in main.c.o
  "_paddle_gradient_machine_randomize_param", referenced from:
      _main in main.c.o
  "_paddle_init", referenced from:
      _main in main.c.o
  "_paddle_ivector_create", referenced from:
      _main in main.c.o
  "_paddle_ivector_destroy", referenced from:
      _main in main.c.o
  "_paddle_matrix_create_none", referenced from:
      _main in main.c.o
  "_paddle_matrix_destroy", referenced from:
      _main in main.c.o
  "_paddle_matrix_get_row", referenced from:
      _main in main.c.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [dense] Error 1
make[1]: *** [CMakeFiles/dense.dir/all] Error 2
make: *** [all] Error 2

**Comment by Xreki** [comment]
您好，您是在交叉编译iOS版本吧。这个错误和https://github.com/PaddlePaddle/Paddle/issues/5795 一样。我在#5795 里面解释过了https://github.com/PaddlePaddle/Paddle/issues/5795#issuecomment-345973142 ： `capi/example`里面的`CMakelist.txt`里面设定的是链接Paddle的动态库。但是iOS版Paddle只生成了静态库。

我们提供了iOS demo，请参考https://github.com/PaddlePaddle/Mobile/tree/develop/Demo/iOS/AICamera
