### ISSUE TITLE
 paddle.to_tensor(sample)生成的张量全是0

### ISSUE THREAD

**Issue by 394988736** [PaddlePaddle/Paddle#65579]
### bug描述 Describe the Bug

![image](https://github.com/PaddlePaddle/Paddle/assets/81234257/916f1dcd-bedc-4d06-a65a-279dc7a3a688)
sample = X_train[:1]  # 取前5个样本作为测试
tensor_sample = paddle.to_tensor(sample)生成的张量全是0

**Comment by 394988736** [comment]
dev版本正常

**Comment by HydrogenSulfate** [comment]
请问出现问题的paddle版本或者对应的commit号是什么呢？以及CUDA版本能提供一下吗？

**Comment by 394988736** [comment]
python -m pip install paddlepaddle-gpu==2.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple
Cuda compilation tools, release 11.8, V11.8.89

**Comment by HydrogenSulfate** [comment]
> python -m pip install paddlepaddle-gpu==2.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple Cuda compilation tools, release 11.8, V11.8.89

可以尝试安装3.0beta版：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

**Comment by 394988736** [comment]
> > python -m pip install paddlepaddle-gpu==2.6.1 -i https://pypi.tuna.tsinghua.edu.cn/simple Cuda compilation tools, release 11.8, V11.8.89
> 
> 可以尝试安装3.0beta版：https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/windows-pip.html

这个正常

**Comment by shizhh** [comment]
24.07.18，发现paddle.to_tensor生成的张量全部是0
这个问题的复现逻辑，用conda create -n test python=3.10 新建个python环境，然后pip install paddlepaddle==2.4.2 或者 2.6.1等 ，都有问题，安装3.0.0b1，正常

使用如下尝试，报错
paddle.Tensor(value=[1],persistable=False,zero_copy=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: (InvalidArgument) Could not parse the first keyword argument successfully, the first keyword argument is value, but it should be PyArray or Tensor or phi::DenseTensor. Please check your input first and make sure you are on the right way. (at /Users/paddle/xly/workspace/77aceb8e-2a5b-4fe4-a675-547f3aad14a4/Paddle/paddle/fluid/pybind/eager.cc:1117)

猜测是编译成whl包的过程中出现了某种问题，导致新安装的环境大部分都有问题
