### ISSUE TITLE
h_start 有一个除2的操作，可能会是小数， 直接用这个数字作为索引去取图像 会出错吧。

### ISSUE THREAD

**Issue by mengquann** [PaddlePaddle/Paddle#6558]
https://github.com/PaddlePaddle/Paddle/blob/79f0ab55dec5ee641c57b746dfb647ef28422a05/python/paddle/v2/image.py#L223

h_start 有一个除2的操作，可能会是小数， 直接用这个数字作为索引去取图像 会出现 TypeError: slice indices must be integers or None or have an __index__ method
错误。

**Comment by typhoonzero** [comment]
Close due to low activity, feel free to reopen it.
