### ISSUE TITLE
docker环境下paddledev/paddle:gpu-demo-v0.9.0a0 ，执行quickstart，Cuda Error: CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#656]
概述：
        docker环境下paddledev/paddle:gpu-demo-v0.9.0a0 ，执行quickstart，Cuda Error: CUDA driver version is insufficient for CUDA runtime version。

I1129 11:18:51.543231   335 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lr.py --save_dir=./output --trainer_count=4 --log_period=100 --num_passes=15 --use_gpu=True 
F1129 11:18:51.543578   335 hl_cuda_device.cc:526] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
    @     0x7f6d59f61daa  (unknown)
    @     0x7f6d59f61ce4  (unknown)
    @     0x7f6d59f616e6  (unknown)
    @     0x7f6d59f64687  (unknown)
    @           0x895bf0  hl_specify_devices_start()
    @           0x895dfd  hl_start()
    @           0x813362  paddle::initMain()
    @           0x52ac5b  main
    @     0x7f6d5916df45  (unknown)
    @           0x540c05  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:   335 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}
I1129 11:18:52.197794   356 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.lr.py --use_gpu=false --job=test --init_model_path=output/pass-00003 --config_args=is_predict=1 --predict_output_dir=. 
I1129 11:18:52.197998   356 Util.cpp:130] Calling runInitFunctions
I1129 11:18:52.198359   356 Util.cpp:143] Call runInitFunctions done.
[WARNING 2016-11-29 11:18:52,343 networks.py:1438] `outputs` routine try to calculate network's inputs and outputs order. It might not work well.Please see follow log carefully.
[INFO 2016-11-29 11:18:52,343 networks.py:1466] The input order is [word]
[INFO 2016-11-29 11:18:52,343 networks.py:1472] The output order is [__maxid_layer_0__, __fc_layer_0__]
I1129 11:18:52.350263   356 Trainer.cpp:149] trainer: in testing mode
I1129 11:18:52.350291   356 Trainer.cpp:156] trainer mode: Testing
I1129 11:18:52.451740   356 PyDataProvider2.cpp:257] loading dataprovider dataprovider_bow::process_predict
I1129 11:18:52.453099   356 GradientMachine.cpp:123] Loading parameters from output/pass-00003
I1129 11:18:52.453135   356 Parameter.cpp:344] missing parameters [output/pass-00003/___fc_layer_0__.w0] while loading model.
F1129 11:18:52.453147   356 Parameter.cpp:350] ___fc_layer_0__.w0 missing, not allowed.
*** Check failure stack trace: ***
    @     0x7efc8abdedaa  (unknown)
    @     0x7efc8abdece4  (unknown)
    @     0x7efc8abde6e6  (unknown)
    @     0x7efc8abe1687  (unknown)
    @           0x825ce2  paddle::Parameter::load()
    @           0x5633a6  paddle::GradientMachine::loadParameters()
    @           0x6b689c  paddle::ParameterUtil::loadParametersWithPath()
    @           0x6c0a6d  paddle::Tester::test()
    @           0x52b718  main
    @     0x7efc89deaf45  (unknown)
    @           0x540c05  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:   356 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
@gangliao Should we add this situation to FAQ?

**Comment by gangliao** [comment]
@reyoung  @beckett1124    Yes, We should. But, it's duplicate #598
