### ISSUE TITLE
Paddle的infer方法报错：invalid index to scalar variable

### ISSUE THREAD

**Issue by KaelChen** [PaddlePaddle/Paddle#6566]
我的测试代码如下所示：
```python
import paddle.v2 as paddle
import numpy as np

x = np.array([1,2,3,4,5])
paddle.init()
input = paddle.layer.data(name='input', type=paddle.data_type.integer_value(5))
layer = paddle.layer.fc(input=input, size=10, act=paddle.activation.Linear())
parameters = paddle.parameters.create(layer)
result = paddle.infer(output_layer=layer, parameters=parameters, input=x)
print result
```
我的本意是想测试一下单层网络在随机初始化下的默认输出，然而这段代码报错信息为:**IndexError: invalid index to scalar variable.**，请各位大神帮忙看下哪里理解的不对。谢谢

**Comment by KaelChen** [comment]
把input修改为
```python
input = paddle.layer.data(name='input', type=paddle.data_type.dense_vector(5))
```
还是报同样的错误，按理说这个时候placeholder定义的是5维的vector，输入的nparray也是5维的vector，为什么还会出同样的错误呢？

**Comment by memorycancel** [comment]
刚刚也遇到了这个问题，应该这么写：

**Comment by KaelChen** [comment]
![image](https://user-images.githubusercontent.com/6700795/34243170-8c9a421c-e65a-11e7-8714-69ad312919c9.png)
我查看了一下源代码`batch_size=len(input)`这里似乎默认了input应当是一个batch的数据。包括后面从input中迭代并取样本再构造一个minibatch，感觉这里应当是有bug。
并且这个实现与文档中所描述的也有冲突。

**Comment by typhoonzero** [comment]
Close for now, feel free to reopen it.
