### ISSUE TITLE
The data layout in MKLDNN

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6567]
@tensor-tang Could you please have a detailed introduction about the data layout in MKLDNN.

Since NCHW is slow in MKLDNN, we have to transform the data layout. Which data layout will be transformed into?

**Comment by tensor-tang** [comment]
用中文回答下，防止哪里没解释清楚。

> Since NCHW is slow in MKLDNN

首先这里的slow是相对的。
`NCHW`在MKLDNN里面的速度应该基本上是类似于Paddle用sgemm实现的CPU版本，不是说`NCHW`本身在MKLDNN里面的速度就是很慢的。 

其次， MKLDNN 里面可以支持比较多的格式，具体可以参考[这里](https://github.com/01org/mkl-dnn/blob/master/include/mkldnn_types.h#L107)。

总结一句话就是，同一个layout，针对不同的平台，速度是不一样的。

但是**用户**并不需要去理解MKLDNN内部的格式，到底哪个速度最好，以及选择哪一个run这种问题。MKLDNN自己会根据平台去选择最优的。所以，（对于MKLDNN来说）用户甚至都不需要touch到任何跟格式有关的事情或者API 参数。

但是对于**开发者**来讲，需要知道可能存在一种情况，比如`mkldnn_conv_op`得出的结论是当前平台上最好的格式是`nChw8c`的， 与默认的`NCHW`不一样。
那么`mkldnn_conv_op`在拿到input和output的tensor时，可能就希望格式已经准备好了，或者至少已经生成了一个转换格式的handle（用于push到最后执行的stream）。如果不是这样，那么就需要在code加转换的部分，这样code看上去会显得比较臃肿。

这个也就是#6549 讨论的问题，需要一个`sync`的接口。 或许这个问题体现的层面不应该局限在不同device上，或者具体上来讲应该是（像我们讨论的）计算库层面的，都需要考虑`sync`机制。

另外需要注意的一点是，MKLDNN里面数据流（也就是Tensor）和参数（也就是parameter），他们的格式不一定是一样的。#6549 里面我们考虑的sync问题，可能还需要范化到参数层面。

**Comment by luotao1** [comment]
@tensor-tang 这段解释能不能加入[MKLDNN的设计文档](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/design/mkldnn)中。

**Comment by tensor-tang** [comment]
可以的，不过这个跟fluid关系大一点，应该会一起把相关概念加入到以后fluid的设计文档里面。

**Comment by jacquesqiao** [comment]
> 可能就希望格式已经准备好了

这个应该由谁来准备呢，现在看之前的Paddle中是MKL-DNN layer内部自己来转的

**Comment by tensor-tang** [comment]
是不是可以让sync机制准备好？因为凡是遇到跨计算库的，读取数据时都应该有这个机制吧。
只不过，实现上是让每个写新的计算库的开发者，来根据实际需求来实现。

以前是`MKLDNNLayer`是把这些转换的事情，都实现在这个class中，比如[resetInValue](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MKLDNNLayer.cpp#L156) 和[resetInGrad](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MKLDNNLayer.cpp#L185)这样的函数中，所有的子类，比如[MKLDNNConvLayer](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MKLDNNConvLayer.cpp#L201) 都只是调用这些函数。当然这些code都是基于重构前的，管理多设备不是那么方便。

现在这些多设备，应该会变得更加清晰了，跨设备的访问可以粗略的理解为：
如果已经有了一个计算库A（或者是设备A），现在要添加计算库B。

- 从计算库A => 计算库B，当前op所在的计算库是 B， 那么我的理解是，这个sync应该由计算库B，来负责`调用`并`实现`吧。

- 从计算库B => 计算库A，当前op所在的计算库是 A， 那么我的理解是，这个sync应该由计算库A，来负责`调用`， 但是`实现`由添加计算库B的开发者实现吧。

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
