### ISSUE TITLE
Verify MKLDNN benchmark using 0.11.0 image

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#6568]
[IntelOptimizedPaddle.md](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/IntelOptimizedPaddle.md) use `paddle:latest` and `paddle:latest-openblas`, we should verify it using `paddle:0.11.0` and `paddle:0.11.0-openblas`.

**Comment by luotao1** [comment]
Training: before->0.11.0
- MKLML and MKL-DNN, the benchmark is almost the same.
- OpenBlas: Not finished yet.

Compared Result:
- VGG-19

| BatchSize    | 64    | 128  | 256     |
|--------------|-------| -----| --------|
| OpenBLAS     | 7.80  | 9.00  | 10.80  | 
| MKLML        | 12.12->12.59 | 13.70->14.36 | 16.18->17.11  |
| MKL-DNN      | 28.46->28.54 | 29.83->29.85 | 30.44->30.62  |

- ResNet-50

| BatchSize    | 64    | 128   | 256    |
|--------------|-------| ------| -------|
| OpenBLAS     | 25.22 | 25.68 | 27.12  | 
| MKLML        | 32.52->32.27 | 31.89->32.14 | 33.12->33.28  |
| MKL-DNN      | 81.69->81.16 | 82.35->83.84 | 84.08->85.28  |

- GoogLeNet

| BatchSize    | 64    | 128   | 256    |
|--------------|-------| ------| -------|
| OpenBLAS     | 89.52 | 96.97 | 108.25 | 
| MKLML        | 128.46->129.37| 137.89->136.49| 158.63->157.50 |
| MKL-DNN      | 250.46->253.73| 264.83->254.01| 269.50->270.79 |

**Comment by luotao1** [comment]
Training: before->0.11.0
- MKLML and MKL-DNN: the benchmark is almost the same except GoogleNet-MKLDNN.
- OpenBlas: Not finished yet.

Compared Result:
- VGG-19

| BatchSize | 1     | 2     | 4     | 8     | 16    |
|-----------|-------|-------|-------|-------|-------|
| OpenBLAS  | 1.07  | 1.08  | 1.06  | 0.88  | 0.65  |
| MKLML     | 5.58->5.51  | 9.80->9.52  | 15.15->15.81 | 21.21->21.38 | 28.67->32.56 |
| MKL-DNN   | 75.07->71.23 | 88.64->88.52 | 82.58->89.76 | 92.29-> 92.15 | 96.75->97.04 |

- ResNet-50

| BatchSize | 1     | 2      | 4      | 8      | 16     |
|-----------|-------|--------|--------|--------|--------|
| OpenBLAS  | 3.35  | 3.19   | 3.09   | 2.55   | 1.96   |
| MKLML     | 6.33->6.28  | 12.02->11.85  | 22.88->21.67  | 40.53->40.23  | 63.09->62.47  |
| MKL-DNN   | 107.83->108.94 | 148.84->151.12 | 177.78->188.24 | 189.35->181.82 | 217.69->224.56 |


- GoogLeNet

| BatchSize | 1      | 2      | 4      | 8      | 16     |
|-----------|--------|--------|--------|--------|--------|
| OpenBLAS  | 12.04  | 11.31  | 10.00  | 9.07   | 4.34   |
| MKLML     | 22.74->22.04  | 41.56->40.82  | 81.22->81.89  | 133.47->133.75 | 210.53->190.48 |
| MKL-DNN   | 175.10->238.81 | 272.92->309.93 | 450.70->269.47 | 512.00->341.33 | 600.94->355.56 |

**Comment by tensor-tang** [comment]
I've test on 0.11.0 and I think below data need double check:

- Training GoogLeNet

| BatchSize  | 128      | 
|-----------|-------|-
| MKL-DNN   | 264.83->254.01 |

- Inference GoogLeNet

| BatchSize  | 8      | 16     |
|-----------|-------|--------|
| MKL-DNN   | 512.00->341.33 | 600.94->355.56 |


My data did not change that much.

**Comment by luotao1** [comment]
> My data did not reduce that much.

Yes, The double check is ok.

- Training GoogLeNet

| BatchSize  | 128      | 
|-----------|-------|
| MKL-DNN   | 264.83->265.41 |

- Inference GoogLeNet

| BatchSize  | 4   | 8      | 16     |
|-----------|-------|--------|-----|
| MKL-DNN   | 450.70->415.58  | 512.00->524.59 | 600.94->603.77 |

| BatchSize  | 16   |
|-----------|-------|
| MKL-DNN   | 210.53->204.47  |

**Comment by luotao1** [comment]
openblas results are all error due to not set env

| BatchSize  | 64     | 
|-----------|-------|
| VGG-19   | 1.07->0.23 |
| ResNet-50   | 3.35->0.69 |
| GoogleNet-v1   | 12.04->1.53 |

**Comment by luotao1** [comment]
openblas (Training) results are almost same after #7105 

- AlexNet (Training) : need double check

| BatchSize    | 64    | 128   | 256    |
|--------------|-------| ------| -------|
| OpenBLAS     | 45.62 | 72.79 | 107.22 |

**Comment by tensor-tang** [comment]
I checked these data, LGTM.
