### ISSUE TITLE
[2024.Q4] Wrong parameter order in `all_to_all`

### ISSUE THREAD

**Issue by eee4017** [PaddlePaddle/Paddle#65732]
### bug描述 Describe the Bug

这边传进去 [all_to_all_tensor_on_calc_stream](https://github.com/eee4017/Paddle/blob/develop/python/paddle/distributed/communication/stream/all_to_all.py#L30
) 第一个参数是 in_tensor，但是到 [pybind](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/pybind/distributed_py.cc#L932) 第一个参数是 out_tensor。

之前有提过一个修正[PR#65093](https://github.com/PaddlePaddle/Paddle/pull/65093)，但有引发其他问题，[PR#65701](https://github.com/PaddlePaddle/Paddle/pull/65701)撤銷了修正PR#65093。

**Comment by LiYuRio** [comment]
您好，这个API确实是写反了，但涉及到一些模型写法的修改，我们已有一个整体修改方案，后续会重提pr，感谢。

**Comment by tianshuo78520a** [comment]
预计会在Q3修复

**Comment by AdamzNV** [comment]
@GuoxiaWang

**Comment by GuoxiaWang** [comment]
fix by https://github.com/PaddlePaddle/Paddle/pull/69014
