### ISSUE TITLE
The Centos6u3-CAPI library should be updated.

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#6574]
The latest successful build was in 04 Dec, I think the lib should be updated since the related source code has been modified.

**Comment by luotao1** [comment]
Known from @Yancey1989 
The latest build is in https://paddleci.ngrok.io/project.html?projectId=Manylinux1&tab=projectOverview
![image](https://user-images.githubusercontent.com/6836917/34348755-cae1a2e0-ea47-11e7-9e78-6fd86ae38f34.png)
The dev docker images is in https://hub.docker.com/r/paddlepaddle/centos6u3-capi/tags/

**Comment by Yancey1989** [comment]
Please follow up the C-API download links in https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/pip_install_en.rst#install-using-pip-1 , the corresponding  CI project has realdy been moved to https://paddleci.ngrok.io/project.html?projectId=Manylinux1&tab=projectOverview .
