### ISSUE TITLE
upsample layer need cpu&gpu forward&backward compare test.

### ISSUE THREAD

**Issue by NHZlX** [PaddlePaddle/Paddle#6579]
upsample layer need cpu&gpu forward&backward compare test.

**Comment by shengyuzhang** [comment]
Is upsampling layer added to PaddlePaddle? I didn't find it in paddle.fluid.layers

**Comment by NHZlX** [comment]
This issue & pr are for paddle v2.

**Comment by shengyuzhang** [comment]
emmm, sorry I'm new to paddlepaddle. 

Is paddle v2 the new active api of paddlepaddle? is it stable for research use?

 ( BTW, I just install paddlepaddle according the instructions on paddlepaddle.org and I am using fluid.

**Comment by NHZlX** [comment]
We have stopped developing V2. I suggest use fluid.

**Comment by shengyuzhang** [comment]
thanks
