### ISSUE TITLE
npu版本，aarch64+python 3.9 paddle-custom-npu安装失败

### ISSUE THREAD

**Issue by saysbye** [PaddlePaddle/Paddle#65854]
### 问题描述 Issue Description

pip install paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npu/
安装失败
```
:~# pip install paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npu
Looking in indexes: https://www.paddlepaddle.org.cn/packages/nightly/npu
ERROR: Could not find a version that satisfies the requirement paddle-custom-npu (from versions: none)
ERROR: No matching distribution found for paddle-custom-npu
```

看了里面没有对应版本的包，是不知道aarch64+python 3.9吗

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: 3.0.0
Paddle With CUDA: False

OS: ubuntu 20.04
GCC version: (Ubuntu 9.4.0-1ubuntu1~20.04.2) 9.4.0
Clang version: N/A
CMake version: N/A
Libc version: glibc 2.31
Python version: 3.9.19

CUDA version: N/A
cuDNN version: N/A
Nvidia driver version: N/A
Nvidia driver List: N/A
****************************************

**Comment by YanhuiDua** [comment]
你好，我们只提供了aarch64+py3.10的whl安装包，地址在这里：https://paddle-whl.bj.bcebos.com/nightly/npu/paddle-custom-npu/paddle_custom_npu-3.0.0.dev20240705-cp310-cp310-linux_aarch64.whl
