### ISSUE TITLE
strided_slice(): argument 'x' (position 0) must be Tensor, but got Tensor

### ISSUE THREAD

**Issue by lovychen** [PaddlePaddle/Paddle#65896]
### bug描述 Describe the Bug

  File "paddle/nn/layer/layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "load_paddle.py", line 254, in forward
    x23 = paddle.strided_slice(x=x2, axes=x20_list, starts=x20_list, ends=x19_list, strides=x18_list)
  File "lib/python3.11/site-packages/paddle/tensor/manipulation.py", line 3899, in strided_slice
    return _C_ops.strided_slice(x, axes, starts, ends, strides)
ValueError: (InvalidArgument) strided_slice(): argument 'x' (position 0) must be Tensor, but got Tensor (at ../paddle/fluid/pybind/eager_utils.cc:1005)

### 其他补充信息 Additional Supplementary Information

paddlepaddle-gpu        2.5.1

**Comment by 350078238** [comment]
执行  什么 报错的？  pip install paddleocr
 安装时？

**Comment by lovychen** [comment]
已解决
