### ISSUE TITLE
使用非GPU训练，报CUDA driver version错误

### ISSUE THREAD

**Issue by fingthinking** [PaddlePaddle/Paddle#6589]
```C++
I1213 19:41:38.391443 11006 Util.cpp:166] commandline:  --use_gpu=False
size: 2555
I1213 19:41:38.744371 11006 GradientMachine.cpp:83] Loading parameters from ../config/param
F1213 19:41:41.842129 11068 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 35) Cuda Error: CUDA driver version is insufficient for CUDA runtime version
```
请教一下，使用了--use_gpu参数，为什么还会出现CUDA不匹配的错误呢？这不应该是使用了gpu训练才会出现的吗？

**Comment by wanghaox** [comment]
参考 https://github.com/PaddlePaddle/Paddle/issues/6211

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如果需继续讨论再打开

**Comment by Yukizzz** [comment]
遇到了同样的问题，请问这个结论是啥呀？ 6211那个issue里的链接打不开…

**Comment by iyishengyoun** [comment]
@Yukizzz 这个问题你解决了吗

**Comment by GuoLiuFang** [comment]
遇到同样问题。use_gpu=False。然后报
![image](https://user-images.githubusercontent.com/10841581/39921874-219fac5e-554f-11e8-8c15-8f21ed123589.png)。。。only-cpu 的时候是不是应该跳过 CUDA check？在哪里可以进行这个操作？

**Comment by ggaaooppeenngg** [comment]
@chengduoZH 能再看一下这个 issue 吗，我也碰到这种情况，装的 gpu paddlepaddle 但是 gpu=False 还是进到了 CUDA 检查。

**Comment by chengduoZH** [comment]
@GuoLiuFang @ggaaooppeenngg 可以参考一下这个issue里描述的 https://github.com/PaddlePaddle/Paddle/issues/10416

**Comment by ggaaooppeenngg** [comment]
@chengduoZH  我在 cpu 机器上装了 gpu 版本，能跳过检查么。

**Comment by chengduoZH** [comment]
如果机器上没有GPU，可以装非GPU版本
这里有连接：http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/build_and_install/pip_install_cn.html

**Comment by luameows** [comment]
@chengduoZH 请问该问题如何处理，同样是安装的cpu版本，但是在训练时报GPU错误
