### ISSUE TITLE
need MKLDNNPlace

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#6591]
When I am trying to implement `conv_mkldnn_op.cc`, like `conv_cudnn_op.cu.cc`.

The first thing need to do is to check `platform::is_mkldnn_place`, just like [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/conv_cudnn_op.cu.cc#L38).

Then we need add `MKLDNNPlace` definition and some relevant functions at least.

**Comment by wangkuiyi** [comment]
Should this be MKLDNNPlace or MKLPlace?

**Comment by tensor-tang** [comment]
Yeah, that's a tangled question for me.

From `MKLPlace` perspective,  `CPUPlace` itself it has already considerate MKL part when `WITH_MKL=ON`, like gemm. etc. It seems that we do not need extra `MKLPlace` for this.

From `MKLDNNPlace` perspective, MKLDNN has some memory layout and some engine design, so we need a Place concept. But about the name, I have some hesitation as well.
For further use, I think `MKLPlace` should be better, in case we need any optimization about MKL(like MKL Packed gemm). But I am not sure if we actually need it. But from coding perspective, `MKLDNNPlace` is just for MKLDNN, not for MKL.

So, from my view, this time we can use `MKLDNNPlace`. If we have some further optimization requirements and if it's really necessary, we can change it to `MKLPlace` and handle some more complex situations.

Anyway, it' s open, any suggestion is absolutely acceptable.

What's do you think? @wangkuiyi
