### ISSUE TITLE
English translation of Recurrent group guide

### ISSUE THREAD

**Issue by varunarora** [PaddlePaddle/Paddle#6595]
It seems like the book chapter on [Machine translation](http://paddlepaddle.org/docs/develop/book/08.machine_translation/index.html) depends on an article on a StaticInput document. The English version of this chapter links to this: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/deep_model/rnn/recurrent_group_cn.md. But this is in Chinese.

Is there an English version of this article? And if so, it would be nice to replace the link in the chapter.

**Comment by luotao1** [comment]
related #6072

**Comment by luotao1** [comment]
Sorry, there is not an English version of this article now. Discussed with @lcy-seso, we will translate https://github.com/PaddlePaddle/Paddle/tree/develop/doc/howto/deep_model/rnn ASAP.

**Comment by varunarora** [comment]
🙏

**Comment by luotao1** [comment]
close due to the new issues #9013
