### ISSUE TITLE
sparse training cluster时在pass0后失败

### ISSUE THREAD

**Issue by CDDB** [PaddlePaddle/Paddle#660]
集群配置问题，转到内网

**Comment by backyes** [comment]
@tianbingsz 也知晓下。sparse相关模型重构后，用户反馈若干问题，需要深入分析问题。

**Comment by CDDB** [comment]
我现在用的是icode的版本，最近一次ci是10月8日。 不知道是否已经被重构了。

另外。我们尝试过sparse-binary-vec的cluster版本的sparse-train，遇到同样p-server启动失败的问题。

**Comment by backyes** [comment]
icode版本不再维护，且后续github 主干有若干关于sparse训练的bugfix，故请更新到新代码，内部有新版本receiver（通过内部渠道沟通），您只要更换下receiver配置即可使能最新版本。

**Comment by backyes** [comment]
@CDDB  请关注deeplearning.baidu.com，面向百度同学的使用文档介绍，获取有关集群信息。

**Comment by CDDB** [comment]
收到， 能确认我遇到的问题是已知问题，并且已经fix了么？

**Comment by backyes** [comment]
暂时不能确定

**Comment by CDDB** [comment]
好的， 我转到内网询问。 这个issue我删掉

**Comment by CDDB** [comment]
成功跑了一轮Pass，但是在Eval结果还没有出现前挂了。 似乎有几个关联问题？ 
采用公司最新receiver
I1201 14:22:15.860833 24546 ThreadLocal.cpp:37] thread use undeterministic rand seed:24547
I1201 14:43:17.116703 21909 TrainerInternal.cpp:182]  Pass=0 Batch=711 samples=35526 AvgCost=0.245079 Eval: 
F1201 14:43:17.771586 21981 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
F1201 14:43:17.771664 21983 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) F1201  14:43::1717..771920 21980 SparseRowMatrix.hSparseRowMatrix.h::63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295)
'''
更多错误日志
'''
u Dec  1 14:43:17 2016[1,3]<stderr>:F1201 14:43:17.139876 11101 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:*** Check failure stack trace: ***
Thu Dec  1 14:43:17 2016[1,3]<stderr>:F1201 14:43:17.139876 11103 S0:63] 12Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:1 14:43:17.139876 11104 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) F1201 14:43:17.140319 11102 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:*** Check failure stack trace: ***
Thu Dec  1 14:43:17 2016[1,3]<stderr>:F1201 14:43:17.139876 11103 S0:63] 12Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:1 14:43:17.139876 11104 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) F1201 14:43:17.140319 11102 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:*** Check failure stack trace: ***
Thu Dec  1 14:43:17 2016[1,3]<stderr>:F1201 14:43:17.139876 11103 S0:63] 12Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:1 14:43:17.139876 11104 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) F1201 14:43:17.140319 11102 SparseRowMatrix.h:63] Check failed: globalIndices_[row] != kUnusedId_ (4294967295 vs. 4294967295) 
Thu Dec  1 14:43:17 2016[1,3]<stderr>:*** Check failure stack trace: ***
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aeb38  google::LogMessage::Fail()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aeb38  google::LogMessage::Fail()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aeb38  google::LogMessage::Fail()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aeb38  google::LogMessage::Fail()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aea90  google::LogMessage::SendToLog()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aea90  google::LogMessage::SendToLog()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aea90  google::LogMessage::SendToLog()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13aea90  google::LogMessage::SendToLog()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13ae525  google::LogMessage::Flush()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13ae525  google::LogMessage::Flush()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13ae525  google::LogMessage::Flush()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13ae525  google::LogMessage::Flush()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13b12e6  google::LogMessageFatal::~LogMessageFatal()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13b12e6  google::LogMessageFatal::~LogMessageFatal()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13b12e6  google::LogMessageFatal::~LogMessageFatal()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @          0x13b12e6  google::LogMessageFatal::~LogMessageFatal()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7e5bec  paddle::CpuMatrix::mul<>()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7e5bec  paddle::CpuMatrix::mul<>()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7e5bec  paddle::CpuMatrix::mul<>()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7e5bec  paddle::CpuMatrix::mul<>()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7d5b77  paddle::CpuMatrix::mul()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7d5b77  paddle::CpuMatrix::mul()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7d5b77  paddle::CpuMatrix::mul()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x7d5b77  paddle::CpuMatrix::mul()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x675f1e  paddle::FullyConnectedLayer::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x675f1e  paddle::FullyConnectedLayer::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x675f1e  paddle::FullyConnectedLayer::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x675f1e  paddle::FullyConnectedLayer::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6d36a4  paddle::NeuralNetwork::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6d36a4  paddle::NeuralNetwork::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6d36a4  paddle::NeuralNetwork::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6d36a4  paddle::NeuralNetwork::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6c9ae6  paddle::TrainerThread::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6c9ae6  paddle::TrainerThread::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6c9ae6  paddle::TrainerThread::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6c9ae6  paddle::TrainerThread::forward()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6cac28  paddle::TrainerThread::computeThread()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6cac28  paddle::TrainerThread::computeThread()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6cac28  paddle::TrainerThread::computeThread()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @           0x6cac28  paddle::TrainerThread::computeThread()
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b565f8a0  execute_native_thread_routine
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b565f8a0  execute_native_thread_routine
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b565f8a0  execute_native_thread_routine
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b565f8a0  execute_native_thread_routine
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b5edd1c3  start_thread
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b5edd1c3  start_thread
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b5edd1c3  start_thread
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b5edd1c3  start_thread
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b4dd012d  __clone
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b4dd012d  __clone
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b4dd012d  __clone
Thu Dec  1 14:43:17 2016[1,3]<stderr>:    @     0x7f36b4dd012d  __clone
'''

**Comment by CDDB** [comment]
@backyes

**Comment by CDDB** [comment]
确认如果取消Test就可以跑通
