### ISSUE TITLE
时间序列输入lstm问题

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#6607]
输入为：长360的list，想以6的time_step分60次输入lstm
```python
data_layer_dict = {}
	for iter in ['rnn_state_input']:
		data_stream = paddle.layer.data(
				name=iter,
				type=paddle.data_type.dense_vector_sequence(6))
		data_layer_dict[iter] = data_stream
```
网络结构：3层lstm
```
	stacked_num = 3
	hid_dim = 64

	lstm1 = paddle.layer.lstmemory(
		input=data_layer_dict['rnn_state_input'], act=paddle.activation.Relu(), bias_attr=False)

	inputs = lstm1
	for i in range(2, stacked_num + 1):
		lstm = paddle.layer.lstmemory(
			input=inputs,
			act=paddle.activation.Relu(),
			bias_attr=False)
		inputs = lstm
	lstm_last = paddle.layer.pooling(input=inputs, pooling_type=paddle.pooling.Max())
```
报错：
```
I1214 03:18:11.936250   982 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
Traceback (most recent call last):
  File "traffic_predict_rnn.py", line 388, in <module>
    train_traffic_rnn_model(num_pass_val, is_local_val, learning_rate, batch_size)
  File "traffic_predict_rnn.py", line 262, in train_traffic_rnn_model
    cost_output_label_map = traffic_rnn_net()
  File "traffic_predict_rnn.py", line 208, in traffic_rnn_net
    input=data_layer_dict['rnn_state_input'], act=paddle.activation.Relu(), bias_attr=False)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/config_base.py", line 52, in wrapped
    out = f(*args, **xargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 415, in wrapper
    return method(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/layers.py", line 1558, in lstmemory
    assert input.size is not None and input.size % 4 == 0
AssertionError
```

**Comment by will-am** [comment]
输入lstmemory的input是要先经过fc的，这个fc输出的size应该是原来input size的4倍，具体见文档中关于lstmemroy的说明：

`text
NOTE: In PaddlePaddle’s implementation, the multiplications Wxixt, Wxfxt, Wxcxt, Wxoxt
 are not done in the lstmemory layer, so an additional mixed with full_matrix_projection or a fc must be included in the configuration file to complete the input-to-hidden mappings before lstmemory is called.
`

使用示例：
![2017-12-14 12 20 23](https://user-images.githubusercontent.com/32189592/33975449-97f42e3e-e0c9-11e7-84f9-8dc9d4b19915.png)

这个fc中的hid_dim是input size * 4

**Comment by hyo009** [comment]
data_layer_dict = {}
	for iter in ['rnn_state_input']:
		data_stream = paddle.layer.data(
				name=iter,
				type=paddle.data_type.dense_vector_sequence(360))
		data_layer_dict[iter] = data_stream

	# define rnn layers
	stacked_num = 3
	hid_dim = 6*4

	fc1 = paddle.layer.fc(input=data_layer_dict['rnn_state_input'],
							size=hid_dim,
							act=paddle.activation.Linear(),
							bias_attr=False)

	lstm1 = paddle.layer.lstmemory(
		input=fc1, act=paddle.activation.Relu(), bias_attr=False)

	inputs = [fc1, lstm1]
	for i in range(2, stacked_num + 1):
		fc = paddle.layer.fc(input=inputs,
                             size=hid_dim,
                             act=paddle.activation.Linear(),
                             bias_attr=False)
		lstm = paddle.layer.lstmemory(
							input=fc,
							act=paddle.activation.Relu(),
							bias_attr=False)
		inputs = [fc, lstm]
	lstm_last = paddle.layer.pooling(input=inputs[1], pooling_type=paddle.pooling.Max())

结构改成这样，还是报错，看不出是什么原因；
*** Aborted at 1513228463 (unix time) try "date -d @1513228463" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x50) received by PID 1314 (TID 0x7f1e4c854700) from PID 80; stack trace: ***
    @     0x7f1e4c42e390 (unknown)
    @     0x7f1e31646c70 paddle::LstmLayer::init()
    @     0x7f1e316e1c5f paddle::NeuralNetwork::init()
    @     0x7f1e3170b73f paddle::GradientMachine::create()
    @     0x7f1e319b9715 GradientMachine::createFromPaddleModelPtr()
    @     0x7f1e319b98ff GradientMachine::createByConfigProtoStr()
    @     0x7f1e31569377 _wrap_GradientMachine_createByConfigProtoStr
    @           0x4cb45e PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4ca8d1 PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4ca099 PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4de8b8 (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4f492e (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4f46a7 (unknown)
    @           0x4b670c (unknown)
    @           0x4b0cb3 PyObject_Call
    @           0x4c9faf PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4ca099 PyEval_EvalFrameEx
    @           0x4c2765 PyEval_EvalCodeEx
    @           0x4c2509 PyEval_EvalCode
    @           0x4f1def (unknown)
    @           0x4ec652 PyRun_FileExFlags
    @           0x4eae31 PyRun_SimpleFileExFlags
    @           0x49e14a Py_Main
    @     0x7f1e4c073830 __libc_start_main
    @           0x49d9d9 _start
    @                0x0 (unknown)
Segmentation fault (core dumped)

**Comment by will-am** [comment]
这个可能是参数设置的问题，可以设置error_clipping_threshold

参考这个例子：
https://github.com/PaddlePaddle/book/blob/03fe7b32feb52e64f910d00af32972d149fba4a8/08.machine_translation/train.py#L66

**Comment by hyo009** [comment]
fc中加了layer_attr=paddle.attr.ExtraLayerAttribute(error_clipping_threshold=10.0)
paddle.optimizer.Adam里也加了gradient_clipping_threshold=10.0，
还是同样的报错

**Comment by will-am** [comment]
可能是数据的问题，再检查下数据或网络结构
