### ISSUE TITLE
build_docs.sh中docker build参数顺序可能导致出错

### ISSUE THREAD

**Issue by yebie** [PaddlePaddle/Paddle#661]
在尝试运行 **paddle/scripts/tools/build_docs/build_docs.sh** 脚本来构建最新版本文档时，部分机器出现错误：

> docker: "build" requires 1 argument.
See 'docker build --help'.
Usage:	docker build [OPTIONS] PATH | URL | -
Build an image from a Dockerfile

但是部分机器能正常进行。

查看代码后，发现是这行：
`docker build . -t paddle_build_doc`
如果改成下面这样就不会出现问题：
`docker build -t paddle_build_doc .`

部分环境下，只支持options放在path前面，所以导致了这样的问题。
所以，为了兼容性，建议修改上述脚本。

PS：另有两个文档，即**doc/getstarted/build_and_install/docker_install.rst** 和 **doc_cn/build_and_install/install/docker_install.rst**中，在最后部分也有类似的命令介绍：
`docker build . -t paddle_ssh`
建议一并改掉~

**Comment by reyoung** [comment]
ok，有道理
