### ISSUE TITLE
cross compile ios  appear CHECK_TYPE_SIZE found different results, consider setting CMAKE_OSX_ARCHITECTURES or  CMAKE_TRY_COMPILE_OSX_ARCHITECTURES to one or no architecture !

### ISSUE THREAD

**Issue by ballackscholl** [PaddlePaddle/Paddle#6610]
My paddle version is Paddle-0.11.0

```
cmake -DCMAKE_SYSTEM_NAME=iOS       -DIOS_PLATFORM=OS       -DIOS_ARCH="armv7;arm64"       -DIOS_ENABLE_BITCODE=ON       -DIOS_USE_VECLIB_FOR_BLAS=ON       -DCMAKE_INSTALL_PREFIX=/Users/zhouyu/Documents       -DWITH_C_API=ON       -DWITH_TESTING=OFF       -DWITH_SWIG_PY=OFF       ..
```

error  happen !!!! 
in build/third_party/gflags/src/extern_gflags-stamp/extern_gflags-configure-*.log

Make Error at /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/CheckTypeSize.cmake:165 (message):
  2   CHECK_TYPE_SIZE found different results, consider setting
  3   CMAKE_OSX_ARCHITECTURES or CMAKE_TRY_COMPILE_OSX_ARCHITECTURES to one or no
  4   architecture !
  5 Call Stack (most recent call first):
  6   /usr/local/Cellar/cmake/3.9.1/share/cmake/Modules/CheckTypeSize.cmake:239 (__check_type_size_impl)
  7   CMakeLists.txt:315 (check_type_size)

**Comment by Xreki** [comment]
您好，这个错误有点偶然性的，再尝试`make`一次可能就没有这个错误了，所以我暂时还没有查清楚原因。如果还有这个问题，请尝试一次编译一个`IOS_ARCH`试下吧。

**Comment by Xreki** [comment]
另外，https://github.com/PaddlePaddle/Mobile/wiki 这里提供了一些预编译好的库，可下载试用。
https://github.com/PaddlePaddle/Mobile/blob/develop/Demo/iOS/AICamera/README_cn.md 有一个iOS demo。

**Comment by ballackscholl** [comment]
非常感谢 您的及时回复 出现错误后 再make 就可以pass了。  另外 paddle 比 tensorflow 好用太多了。就是开源模型比较少。作为ex-baiduer 在此向您和您的同事表示致敬。希望paddlepaddle 社区越来越大

**Comment by Xreki** [comment]
多谢您的支持。PaddlePaddle开源的模型请参考：https://github.com/PaddlePaddle/models 和https://github.com/PaddlePaddle/book 。更多的模型正在筹备中。如果请有特殊需求，可以在https://github.com/PaddlePaddle/models 下面提issue。
