### ISSUE TITLE
refine the MKL script in MKLDNN benchmark

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#6613]
- rename the script: from `run_mkldnn_*.sh` to `run_mkl_*.sh`, since the script contains both MKLDNN and MKLML
- auto computes the FPS by avg elapsed time.
  - Now, the script only compute the avg elapsed time
     ```
     I1214 05:18:01.186905  5426 Stat.cpp:102] ======= StatSet: [GlobalStatInfo] status ======
     I1214 05:18:01.186929  5426 Stat.cpp:105] Stat=FwdBwd                         TID=5426   total=508279     avg=5082.79    max=7292.66    min=4731.89    count=100
     ```
  - Then, we should manully computes images/second = batchsize/avg time
- refine the log name: 
   - for mkldnn log, the name is `train-vgg-19-mkldnn-256.log`
   - for mklml log, it typo likes `train-vgg-19-40mklml-256.log`, where `40` is extra
- auto organize the result like a table:

| BatchSize    | 64    | 128   | 256    |
|--------------|-------| ------| -------|
| MKLML        | 128.46| 137.89| 158.63 |
| MKL-DNN      | 250.46| 264.83| 269.50 |

**Comment by tensor-tang** [comment]
> rename the script: from run_mkldnn_*.sh to run_mkl_*.sh, since the script contains both MKLDNN and MKLML

OK, no problem, but only if we need an another script for openblas benchmark.

> Then, we should manully computes images/second = batchsize/avg time

Yes, this can be refined.

> for mklml log, it typo likes train-vgg-19-40mklml-256.log, where 40 is extra

This `40` is not extra, I added it on purpose. It means used 40 MKLML threads on this machine, which represent as `40mklml`. Then we can know how many threads used in this log name.


> auto organize the result like a table:

No problem. But need one more python script to implement.

**Comment by luotao1** [comment]
Ok, I will refine the first two.

**Comment by tensor-tang** [comment]
Thanks, I think you can use the same way as [run_mkldnn_infer.sh](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/paddle/image/run_mkldnn_infer.sh#L61), and keep the last line format like: `FPS: 300.10 images/sec`
