### ISSUE TITLE
训练model从GPU集群移到CPU集群报错

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#662]
之前用GPU训练CNNmodel，移到CPU集群训练报错。local_config和receiver已改，--where参数已改。
具体错误如下，未找到libpython2.6.so.1.0：
I1130 10:44:17.482218  3086 PyDataProvider.cpp:43] module:pyDataProviderImage class:GeneralJpegDataProvider
I1130 10:44:17.868773  3086 PythonUtil.cpp:149] createPythonClass moduleName.c_str:pyDataProviderImage
I1130 10:44:17.868809  3086 PythonUtil.cpp:154] createPythonClass className.c_str():GeneralJpegDataProvider
I1130 10:44:17.888891  3086 PythonUtil.cpp:83] Python Error: <type 'exceptions.ImportError'> : libpython2.6.so.1.0: cannot open shared object file: No such file or directory
I1130 10:44:17.888914  3086 PythonUtil.cpp:87] Python Callstack: 
I1130 10:44:17.888922  3086 PythonUtil.cpp:92]             /home/normandy/maybach/204635/workspace/thirdparty/thirdparty/pyDataProviderImage.py : 127
F1130 10:44:17.889091  3086 PythonUtil.cpp:108] Create class GeneralJpegDataProvider failed.

pyDataProviderImage.py的第126-127行是：
self.lib_name = "decodeJPEG._DeJPEG"
self.libmodel = __import__(self.lib_name,fromlist=['_DeJPEG'])

**Comment by backyes** [comment]
集群环境的python运行时环境为2.7版本，错误提示没有2.6版本。请更新到2.7版本依赖。

**Comment by qubingxin** [comment]
请问这个更新依赖是更新哪里的依赖？是指的receiver？

**Comment by backyes** [comment]
可能是你的thirdparty部分应该有依赖python2.6动态库模块，确保它们依赖python2.7，而不是2.6（集群环境没有2.6环境）。

**Comment by reyoung** [comment]
Closed due not response for long time. Reopen it if necessary.

**Comment by Skyeyue** [comment]
请问问题解决了吗？我遇到的问题是sqlite依赖于py2.6，但是我折腾了很久一直无法升级到2.7
