### ISSUE TITLE
如何将 模型参数 和模型 序列化成 *.paddle 文件

### ISSUE THREAD

**Issue by ballackscholl** [PaddlePaddle/Paddle#6625]
不好意思  在 Mobile/Demo/iOS/AICamera/  中用到的 模型参数 和模型 merge 好的 .paddle 是怎么做出来的。 我只看到 train.save_parameter_to_tar  保存模型参数的protobuf 文件

**Comment by Xreki** [comment]
https://github.com/PaddlePaddle/Mobile/tree/develop/deployment/model/merge_config_parameters 描述了merge model的方法，并且提供了一个例子。
