### ISSUE TITLE
centos编译paddle develop (cpu)报错。

### ISSUE THREAD

**Issue by blacksheep-Aristotle** [PaddlePaddle/Paddle#66283]
### 请提出你的问题 Please ask your question

执行命令：
按照文档步骤拉取进入docker。
安装conda环境。
cmake .. -DPY_VERSION=3.10 -DWITH_GPU=OFF
make -j32
![image](https://github.com/user-attachments/assets/9d381146-0740-4cfe-b209-c27c1ad1017a)
看报错信息是没有安装networkx，但是已经pip install -r python/requirements.txt 过了。
![image](https://github.com/user-attachments/assets/8b3aa267-65d5-4c60-aef5-fe7cba72e623)

**Comment by SigureMo** [comment]
```python
def check_build_dependency():
    missing_modules = '''Missing build dependency: {dependency}
Please run 'pip install -r python/requirements.txt' to make sure you have all the dependencies installed.
'''.strip()

    with open('${PADDLE_SOURCE_DIR}' + '/python/requirements.txt') as f:
        build_dependencies = (
            f.read().splitlines()
        )  # Specify the dependencies to install

    python_dependencies_module = []
    installed_packages = []

    for dependency in build_dependencies:
        python_dependencies_module.append(
            re.sub("_|-", '', re.sub(r"==.*|>=.*|<=.*", '', dependency))
        )
    reqs = subprocess.check_output([sys.executable, '-m', 'pip', 'freeze'])

    for r in reqs.split():
        installed_packages.append(
            re.sub("_|-", '', r.decode().split('==')[0]).lower()
        )

    for dependency in python_dependencies_module:
        if dependency.lower() not in installed_packages:
            raise RuntimeError(missing_modules.format(dependency=dependency))
```

按理说如果环境一致是没有问题的（特别是用 conda 这种独立虚拟环境），麻烦帮忙通过 `print` 来确认几件事情：

- `sys.executable` 是否是你所安装依赖的 python？如果不是，手动使用该绝对路径 + `-m pip install -r python/requirements.txt` 试试呢？
- `reqs` 结果是什么？是否符合预期？是否是后面匹配算法出问题？

**Comment by blacksheep-Aristotle** [comment]
还真是，为啥python环境不是conda 环境里的？而且我打which python，输出的路径是虚拟环境里的路径？
![image](https://github.com/user-attachments/assets/606aef47-3e3c-4982-bdaf-d43c1746ab80)

**Comment by blacksheep-Aristotle** [comment]
> ```python
> def check_build_dependency():
>     missing_modules = '''Missing build dependency: {dependency}
> Please run 'pip install -r python/requirements.txt' to make sure you have all the dependencies installed.
> '''.strip()
> 
>     with open('${PADDLE_SOURCE_DIR}' + '/python/requirements.txt') as f:
>         build_dependencies = (
>             f.read().splitlines()
>         )  # Specify the dependencies to install
> 
>     python_dependencies_module = []
>     installed_packages = []
> 
>     for dependency in build_dependencies:
>         python_dependencies_module.append(
>             re.sub("_|-", '', re.sub(r"==.*|>=.*|<=.*", '', dependency))
>         )
>     reqs = subprocess.check_output([sys.executable, '-m', 'pip', 'freeze'])
> 
>     for r in reqs.split():
>         installed_packages.append(
>             re.sub("_|-", '', r.decode().split('==')[0]).lower()
>         )
> 
>     for dependency in python_dependencies_module:
>         if dependency.lower() not in installed_packages:
>             raise RuntimeError(missing_modules.format(dependency=dependency))
> ```
> 
> 按理说如果环境一致是没有问题的（特别是用 conda 这种独立虚拟环境），麻烦帮忙通过 `print` 来确认几件事情：
> 
> * `sys.executable` 是否是你所安装依赖的 python？如果不是，手动使用该绝对路径 + `-m pip install -r python/requirements.txt` 试试呢？
> * `reqs` 结果是什么？是否符合预期？是否是后面匹配算法出问题？

还真是，为啥python环境不是conda 环境里的？而且我打which python，输出的路径是虚拟环境里的路径？
![image](https://github.com/user-attachments/assets/606aef47-3e3c-4982-bdaf-d43c1746ab80)
实际使用的是 /usr/bin/python3.10

**Comment by blacksheep-Aristotle** [comment]
为啥cmake时链接的不是conda里的python呀
![image](https://github.com/user-attachments/assets/71b79f19-43cf-4bed-9f05-bf8455369fd3)

**Comment by SigureMo** [comment]
> 为啥cmake时链接的不是conda里的python呀

创建的 conda 环境的 python 版本是 3.10 么？

**Comment by blacksheep-Aristotle** [comment]
> > 为啥cmake时链接的不是conda里的python呀
> 
> 创建的 conda 环境的 python 版本是 3.10 么？
conda里的是python 3.8
![image](https://github.com/user-attachments/assets/a726eefa-99f7-4fd8-b2c9-e274d1e202a5)

**Comment by SigureMo** [comment]
emmm，可是你 cmake 用的是 `-DPY_VERSION=3.10`，应该是在当前环境找不到 `python3.10`，只能找 `/usr/bin/python3.10` 了

你是想用 python3.10 还是 python3.8？如果想用 3.10 创建 3.10 的环境（比如 `conda create -n paddle_dev python=3.10`），如果想用 3.8，cmake 选项用 `-DPY_VERSION=3.8`

**Comment by blacksheep-Aristotle** [comment]
阿里嘎多
