### ISSUE TITLE
一些自定义数据集的读取问题

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6628]
在[官网教程](http://paddlepaddle.org/docs/develop/models/image_classification/README.html)中,讲到自定义数据集的读取,如下图:
![image](https://user-images.githubusercontent.com/26297768/33991322-2e661a96-e109-11e7-86ae-329e11e6e28b.png)
* 数据的顺序一定要打散吗,不打散会不会影响训练效果?
* 它读取图像列表文件用到`reader.py`这个文件,但是我在paddlepaddle源码中找不到这个文件,倒是在`paddle/benchmark/tensorflow/rnn`中有一个`reader.py`,但是不是需要的那个,这个文件到底在那啊?
* 哪些标签一定要整数吗?我直接用图片的文字吗?
* 下面的那些包我好像都没有,用`pip install `都安装不了,这些包哪里来的
```
import vgg
import resnet
import alexnet
import googlenet
```

**Comment by will-am** [comment]
1. 尽量打散，不打散会对训练效果有影响
2. 在paddle model bank里有完整的image classification模型，这里有reader.py：https://github.com/PaddlePaddle/models/tree/develop/image_classification
3. 文字要先转换成数字类别
4. 这些文件都在image classification模型下：https://github.com/PaddlePaddle/models/tree/develop/image_classification

**Comment by yeyupiaoling** [comment]
@will-am 每个问题都回答到要点,问题一下子全解决了,谢谢

**Comment by yeyupiaoling** [comment]
@will-am 这个是不是在读取的时候就已经打撒的的,使用到这个[关键字yield](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L33)
```
def train_reader(train_list, buffered_size=1024):
    def reader():
        with open(train_list, 'r') as f:
            lines = [line.strip() for line in f]
            for line in lines:
                img_path, lab = line.strip().split('\t')
                yield img_path, int(lab)

    return paddle.reader.xmap_readers(train_mapper, reader,
                                      cpu_count(), buffered_size)
```

**Comment by will-am** [comment]
是的

**Comment by yeyupiaoling** [comment]
@will-am 好的，我在做文件列表的时候就不用自己打撒了，谢谢
