### ISSUE TITLE
【paddlepaddle-gpu-2.6.1】执行paddle.to_tensor得到全为0

### ISSUE THREAD

**Issue by nicken** [PaddlePaddle/Paddle#66371]
### bug描述 Describe the Bug

* bug描述

执行下面脚本，得到返回张量全是0，且对两个不同的张量获得判断为true的情况
```python
import paddle
# 情况1：全为0
print(paddle.to_tensor([222,333,444]))
# 输出结果：Tensor(shape=[3], dtype=int64, place=Place(gpu:0), stop_gradient=True,[0, 0, 0])

# 情况2：判断为true
print(paddle.to_tensor([222,333,444]) == paddle.to_tensor([223,334,544]))
# W0723 10:21:05.496966 79441 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 12.2, Runtime API Version: 11.8
# W0723 10:21:05.497838 79441 gpu_resources.cc:164] device: 0, cuDNN Version: 8.8.
# 输出结果：Tensor(shape=[3], dtype=bool, place=Place(gpu:0), stop_gradient=True, [True, True, True])
```
* 环境情况
  * GPU: GTX 1060
  * CPU：Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  * system： Ubuntu 22.04.4 LTS
  * 驱动：535.146.02
  * python：3.9.16
  * cuda：cuda_11.8.r11.8/compiler.31833905_0
  * cudnn： 8.8
  * paddle相关包：
    paddle2onnx         1.2.5
    paddlefsl           1.1.0
    paddlenlp           2.8.1
    paddlepaddle-gpu    2.6.1

### 其他补充信息 Additional Supplementary Information

* 另外测试情况
  同一台设备，采用容器`paddlepaddle/paddle:2.6.1-gpu-cuda11.7-cudnn8.4-trt8.4`
执行命令`docker run -it --rm --gpus all paddlepaddle/paddle:2.6.1-gpu-cuda11.7-cudnn8.4-trt8.4 /bin/bash`，进入容器内，测试是没问题，可通过。可初步推断GPU、CPU、驱动正常。

相关问题：
#47797 
#56577 

PS：上述问题提供的方法都是，换paddle版本，但目前都是安装官方指引安装的，如无法找到问题，在后续安装新版本的时候问题仍有可能出现

**Comment by liaoxin2** [comment]
感谢您提出该问题，我们会对该问题进行排查。当然可以尝试最新版本的paddle，也可以参考一下https://github.com/PaddlePaddle/Paddle/issues/66181

**Comment by nicken** [comment]
> 感谢您提出该问题，我们会对该问题进行排查。当然可以尝试最新版本的paddle，也可以参考一下#66181

感谢你的回复，经排查，当前环境确实是numpy=2.0.0,当我执行`pip install numpy==1.26.4`进行回退，问题确实得到了解决；
另，请考虑是否有必要，提醒后续安装者，paddle与numpy的依赖的问题 @liaoxin2
（既然已有相关问题，本issue就关闭了）
