### ISSUE TITLE
JD: Deep Learning Platform Engineer

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#664]
Paddle is Baidu's open source deep learning platform. For the recent 3 more years, it has been supporting large-scale deep learning applications ranging from search engine, online advertising, image recognition, face recognition, natural language processing, etc. We are looking forward to having more experienced engineers and researchers with good engineering skills to join us to make Paddle better and to allow more users benefit from Paddle.

We hope that you can be one of the good hosts of the open source community of Paddle.  Paddle belongs to the community, not Baidu alone. We need to establish a good working environment in the community so to help more engineers outside of Baidu to contribute.

We are opening Paddle completely -- that is 100%. This means that we need to port some Baidu internal computing features to be compatible with open source infrastructures ranging from laptop to public clouds. 

We are encouraged to help everyone in every company benefit from Paddle. To do so, we are making sure that Paddle can train and serve on both mobile devices and the cloud.  Also, we are converting cutting-edge research results into Paddle toolkits and are building model banks.

We believe that if you possess any or some of the following skills, you will be able to work happily on Paddle:

1. Experience with C++ programming. Paddle was coding with C++11.
1. Experience with Python programming. Paddle's primary application development language is Python.
1. Distributed system engineering -- MPI, YARN, Mesos, Kubernetes.
1. Experience with GPU and CPU's SIMD instruction set and their applications.
1. Network programming skills, including TCP/IP and RDMA.
1. Knowing machine learning, or even better, having related work experience.
1. Image processing, computer vision and related work experience.
1. Natural language processing (NLP) and related work experience.
1. Experience with engineering process with Github -- design doc review, code review, Issues and Milestones, releasing and hotfix.

**Comment by emailweixu** [comment]
Made some minor changes directly. Overall looks good to me. But I feel the order of the skills can be optimized so that the important and hard-to-learn skills are at the top.

**Comment by wangkuiyi** [comment]
Got it. Re-ordered skills list. Please review. @emailweixu

**Comment by wangkuiyi** [comment]
@emailweixu approved it offline. I am posting this out. Anyone interested are welcome to join us! :-)
