### ISSUE TITLE
roi_pool文档描述中有笔误

### ISSUE THREAD

**Issue by gongshaotian** [PaddlePaddle/Paddle#66440]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/documentation/docs/zh/2.6/api/paddle/vision/ops/roi_pool_cn.html#roi-pool

”实现 roi_cooling 层“ 应该为 ”实现 roi_pooling 层“

**Comment by sunzhongkai588** [comment]
感谢～马上修复

**Comment by luotao1** [comment]
fixed by 
- https://github.com/PaddlePaddle/docs/pull/6790
