### ISSUE TITLE
fluid 如何获取网络参数

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6645]
想观察训练过程中网络参数的统计信息，fluid如何获取网络参数呢？

**Comment by jacquesqiao** [comment]
放到fetch_list里面

**Comment by lcy-seso** [comment]
能否更详细解释一下呢？我也想知道这个问题应该如何操作。

**Comment by jacquesqiao** [comment]
1，给parameter取一个名字，放在param_attr里面
2，从block中用名字取出对应的param的variable
3，把var放到fetch_list里面https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_image_classification_train.py#L124

**Comment by shjwudp** [comment]
请问现在支持在inference过程中获取子block的中间结果吗？
