### ISSUE TITLE
有使用 kubeflow 跑 paddle 分布式训练的示例？

### ISSUE THREAD

**Issue by tanjunchen** [PaddlePaddle/Paddle#66514]
### 请提出你的问题 Please ask your question

有使用 kubeflow 跑 paddle 分布式训练的示例（k8s 容器调度平台）？

**Comment by JZ-LIANG** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/06_distributed_training/deployment_cn.html#kubernetes
