### ISSUE TITLE
Add a new layer

### ISSUE THREAD

**Issue by lipeng-unisound** [PaddlePaddle/Paddle#666]
请问，我想增加一个新的 layer，是否必须在 Paddle 的代码树里增加文件？有没有可能我在一个独立的 git repo 里实现，然后以某种形式（比如将 paddle.git 作为我的 repo 的 submodule）build 出一个包含这个新 layer 的 paddle executable？

换句话说，layer 的实现能否是一个和 Paddle 源码分开的独立模块？不知道我说清楚没有。

谢谢！

**Comment by reyoung** [comment]
OK，这块美研的一些同事会有经验，等美国时间上班后，美研的一些同事会有一些解答。。

目前这块拆分应该比较trick，我在想我们也许需要做一个纯粹的插件系统，把一个个layer都变成.so运行时载入。@wangkuiyi

@wangkuiyi 麻烦联系下美研的同事回一下这个issue

**Comment by wangkuiyi** [comment]
我了解了一下，有两个方法：

1. main函数用Python写。一个例子是 https://github.com/PaddlePaddle/Paddle/pull/516 。在这个例子里的[main函数](https://github.com/PaddlePaddle/Paddle/pull/516/files#diff-a824391b64f13a3e341d314f25ff3dcfR193)调用了[`api.initPaddle`](https://github.com/PaddlePaddle/Paddle/pull/516/files#diff-a824391b64f13a3e341d314f25ff3dcfR212)函数以及其他一系列`api.` package里的函数。而`api`实际上是 [`py_paddle.swig_paddle`](https://github.com/PaddlePaddle/Paddle/pull/516/files#diff-a824391b64f13a3e341d314f25ff3dcfR24) 这个 package。通过调用这个package里的函数，甚至不需要写 Python data provider，而是可以
