### ISSUE TITLE
Why is there no paddlepaddle==2.0.0 on pypi?

### ISSUE THREAD

**Issue by CheneyYin** [PaddlePaddle/Paddle#66640]
### 请提出你的问题 Please ask your question

Why is there no `paddlepaddle==2.0.0` on pypi?
![Screenshot_2024-07-26-22-58-02-06_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/user-attachments/assets/9033e85f-62c6-43d9-980b-05cea7364d77)

**Comment by xuxinyi389** [comment]
pip本身是有存储空间限制的，所以上传新的包需要删除一些旧包，如需旧包可以参考如下链接 https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#old-version-anchor-46-V2.0

**Comment by CheneyYin** [comment]
> pip本身是有存储空间限制的，所以上传新的包需要删除一些旧包，如需旧包可以参考如下链接 https://www.paddlepaddle.org.cn/install/old?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html#old-version-anchor-46-V2.0

Thanks. I have extract these package links from docker [image](https://hub.docker.com/layers/paddlepaddle/paddle/2.0.0/images/sha256-e8e9868fde113a97733c4e0204ebf6edb63645bf44ff76e9183dff7364ee122f?context=explore).
