### ISSUE TITLE
有ARM架构，英伟达GPU版本paddlepaddle的docker或者whl吗？

### ISSUE THREAD

**Issue by SongJasper** [PaddlePaddle/Paddle#66685]
### 请提出你的问题 Please ask your question

目前官网的教程都是x86的，请问是否有arm+nvidia版本的适配
![image](https://github.com/user-attachments/assets/6c6a093f-97b1-41ef-a27a-64762de5a120)

**Comment by changeyoung98** [comment]
目前暂时没有arm+nvidia的版本，官网硬件支持部分https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/hardware_support/index_cn.html 列出了目前支持的版本类型～

**Comment by SongJasper** [comment]
> 目前暂时没有arm+nvidia的版本，官网硬件支持部分https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/hardware_support/index_cn.html 列出了目前支持的版本类型～

![image](https://github.com/user-attachments/assets/1798d01a-5902-44af-b788-1f7c0ca6ed9f)
你好，目前准备部署到T4+ARM的Linux系统上，这图片没有明确标明架构，请问一下，paddlepaddle2.5的源码支持编译运行到ARM+nvidia上吗 @changeyoung98    如果支持的话那我们想办法去编译 如果代码不支持的话那我们再去找其他办法

**Comment by changeyoung98** [comment]
> > 目前暂时没有arm+nvidia的版本，官网硬件支持部分https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/hardware_support/index_cn.html 列出了目前支持的版本类型～
> 
> ![image](https://private-user-images.githubusercontent.com/18087591/352954862-1798d01a-5902-44af-b788-1f7c0ca6ed9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIzMjEyMzEsIm5iZiI6MTcyMjMyMDkzMSwicGF0aCI6Ii8xODA4NzU5MS8zNTI5NTQ4NjItMTc5OGQwMWEtNTkwMi00NGFmLWI3ODgtMWY3YzBjYTZlZDlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMwVDA2Mjg1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmNzE4YWYyZTExNTg2MjdiNGFmOThlMDY5MjY0NjU5M2Y5NmVmYmZjNGQyMDQ4MDdlZGVmZWI0MzMyY2U3YzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.djuCknGqdf-qoaIECmXmoUG6DGy77orasd_wrMYf0Kw) 你好，目前准备部署到T4+ARM的Linux系统上，这图片没有明确标明架构，请问一下，paddlepaddle2.5的源码支持编译运行到ARM+nvidia上吗 @changeyoung98 如果支持的话那我们想办法去编译 如果代码不支持的话那我们再去找其他办法

是的，历史版本也未支持ARM+nvidia

**Comment by time-heart** [comment]
请问你们解决了吗，我在arm的linux上自己编译gpu版本的paddle一直编译不上，总是在make的时候报错
