### ISSUE TITLE
How to communicate among inter-node?

### ISSUE THREAD

**Issue by gaoshan2006** [PaddlePaddle/Paddle#667]
Among inter-node, how does Paddle communicate? By using GPU Direct RDMA, or MPI ? or other methods? Thanks

**Comment by gaoshan2006** [comment]
Among inter-node, how does Paddle communicate?  By using GPU Direct RDMA, or MPI ? or other methods?  Thanks

**Comment by backyes** [comment]
@gaoshan2006 

Paddle can harness TCP, RDMA, and it also can run without MPI. Paddle owns separate TCP/RDMA socket based parameter server implementation(https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/pserver). 

Paddle can run on k8s cluster, mpi cluster, ssh-based naive cluster.

**Comment by Yancey1989** [comment]
Close this issue, please feel free to reopen it.
