### ISSUE TITLE
linux运行paddleocr出现多个GPU同时运行

### ISSUE THREAD

**Issue by 77bw** [PaddlePaddle/Paddle#66720]
### 请提出你的问题 Please ask your question

wsl ubuntu20.04.GPU两张

from paddleocr import PaddleOCR

ocr = PaddleOCR(gpu_id=1)

运行以上命令在查看驱动运行程序的时候出现两个程序
|    0   N/A  N/A     10588      C   /python3.10                               N/A      |
|    1   N/A  N/A     10588      C   /python3.10                               N/A      |
如何使其运行在一个显卡之上呢？

**Comment by changeyoung98** [comment]
同学可以试一下用 paddle.set_device('gpu:1') 来指定

**Comment by 77bw** [comment]
你好我尝试了一下，结果是一样的

**Comment by changeyoung98** [comment]
export CUDA_VISIBLE_DEVICES=1，terminal执行这个指令试试呢？

**Comment by changeyoung98** [comment]
https://github.com/PaddlePaddle/Paddle/issues/6725 之前有一个类似的issue，可以参考一下～
