### ISSUE TITLE
Some question about the inheritance relationship of `DeviceContext`.

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#6676]
We assume each computational library is a place and has its own `DeviceContext`. So the inheritance relationship of `CUDADevCtx`, `CUDNNDevCtx`, and `NCCLDevCtx` is:

```
                 /- CUDNNDeviceContext
CUDADeviceContext
                 `- NCCLDeviceContext
```

Question 1: How about an operator will need both `NCCL` context and `CUDNN` context? Should we provide an `NCCLAndCUDNNDeviceContext`? Or we just let this operator get two `DeviceContext` instances?

Question 2: Should we implement a decoration pattern for `CUDNNDevCtx` and `NCCLDevCtx`? i.e.
The sample code is as below:

```cpp
class CUDADevCtx;
class CUDNNDevCtx : public CUDADevCtx {
public:
  CUDNNDevCtx(CUDADevCtx* cuda_dev_ctx): cuda_dev_ctx_(cuda_dev_ctx) {}
private:
  CUDADevCtx* cuda_dev_ctx_;
};
```

Question 3: If we make DeviceContext as global variables, how do we use different streams for copying data and computation in the same GPU?

Question 4: If we make DeviceContext as global variables, why we need `DeviceContext` class? Why not just some global functions?

**Comment by QiJune** [comment]
> Question 1: How about an operator will need both `NCCL` context and `CUDNN` context? Should we provide an `NCCLAndCUDNNDeviceContext`? Or we just let this operator get two `DeviceContext` instances?

CUDNN is used to do computation, NCCL is used to do communication. I could not find an operator that both need these two temporarily. If so, we may split this operator into two operators.

> Question 2: Should we implement a decoration pattern for `CUDNNDevCtx` and `NCCLDevCtx`? 

It's great If we can reduce codes without losing readability.

> Question 3: If we make DeviceContext as global variables, how do we use different streams for copying data and computation in the same GPU?

There will be at least two streams in a GPU, one for copying, one for computing. So, there will be at least two corresponding DeviecContext.

> Question 4: If we make DeviceContext as global variables, why we need `DeviceContext` class? Why not just some global functions?

I think the code lines between `DeviceContext` class and `global functions` are almost the same. If we remove `DeviceConext` class, we will have some global CUDA streams/cublas handles/cudnn handles/mkl handles created first. And we will have some global functions to manipulate these global variables. That's the way which former version paddle does.

**Comment by reyoung** [comment]
> There will be at least two streams in a GPU, one for copying, one for computing. So, there will be at least two corresponding DeviceContext.

So how do we design this two global DeviceContext?

Should the global device context be

```cpp
enum Role {
  kComputation,
  kCommunication
};
std::map<Place, 
   std::map<enum Role, DeviceContext>> g_dev_ctx;
```

**Comment by QiJune** [comment]
> Should the global device context be

```cpp
enum Role {
  kComputation,
  kCommunication
};
std::map<Place, std::map<enum Role, DeviceContext>> g_dev_ctx;
```

In CUDA, we need at least two CUDADeviceContext, one is io, one is computation. I am not sure what will other device/library do, we may be we can focus on CUDA first and consider to make an abstraction later.
