### ISSUE TITLE
有什么方式可以查看paddle的api源代码

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#6677]
最近，我有一些想法。虽然已经有了api，然而那些api不是很吻合我的需求，所以，我想看看api的源码，进而写一些我自己的代码，然而我找不到源码。请问，有人可以告诉我在哪里查看吗？

**Comment by lcy-seso** [comment]
建议您描述清楚您想写的功能是什么，代码涵盖的内容很多。很难直接回答您的这个问题。

**Comment by yyhlvdl** [comment]
以机器翻译来说，注意力机制解码ui+1的时候，它的输入应该是目标语言的ui，可是，我并不想输入目标语言ui，我想的是将前一个状态解码的结果(ui)作为输入，来解码ui+1.这样的功能。

**Comment by lcy-seso** [comment]
我没有明白您是说的这个和目前最常用的encoder-decoder结构有什么区别。PaddlePaddle下有大量seq2seq的例子：https://github.com/PaddlePaddle/models/blob/develop/README.cn.md 。

**Comment by yyhlvdl** [comment]
好的，谢谢，知道怎么解决我的问题了。
