### ISSUE TITLE
有什么方式可以查看数据经过每一层后的格式？

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#6679]
我想看看，我的数据在神经网络中，具体经过每一层之后变成什么样子了，请问，我可以做到这点吗？

**Comment by lcy-seso** [comment]
请参考这个例子 https://github.com/PaddlePaddle/models/tree/develop/ltr#%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B%E4%B8%AD%E8%BE%93%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%84%E4%BC%B0%E6%8C%87%E6%A0%87

**Comment by yyhlvdl** [comment]
好的

**Comment by yyhlvdl** [comment]
I1217 19:35:05.484254 12746 Util.cpp:166] commandline:  --use_gpu=True --rnn_use_batch=True --trainer_count=1 
[INFO 2017-12-17 19:35:07,691 layers.py:2689] output for __conv_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-17 19:35:07,692 layers.py:3251] output for __batch_norm_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-17 19:35:07,692 layers.py:7411] output for __scale_sub_region_0__: c = 32, h = 81, w = 54, size = 139968
[INFO 2017-12-17 19:35:07,693 layers.py:2689] output for __conv_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-17 19:35:07,693 layers.py:3251] output for __batch_norm_1__: c = 32, h = 41, w = 54, size = 70848
[INFO 2017-12-17 19:35:07,693 layers.py:7411] output for __scale_sub_region_1__: c = 32, h = 41, w = 54, size = 70848
然而，我有的是
/home/yyh/图片/2017-12-17 20-01-33屏幕截图.png
我想把gru也像卷积层那样打印，可以做到吗

**Comment by yyhlvdl** [comment]
或者说，我只想知道数据经过每一步后的size，怎么做呢？
