### ISSUE TITLE
Do we need to expose Transpiler to users?

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6692]
In our fluid deign, we use ProgramDesc proto message to describe our neural network. In my mind, users are more likely to write formulas when configuring a network. For example, users write a network for single GPU, the transpiler will transpile it to multi-GPUs. The procedure should be:

```
Write network  ---->  Transpile on certain hardware  -----> Execute the ProgramDesc
```

So, we may should expose `Transpile` to users. Just like uses can set many compiler flags when using gcc. 
There comes a question, which details users should write, and which details should be done by `Transpiler` with some flags setting by users?

**Comment by jacquesqiao** [comment]
I think for end user, it's too hard to understand and use Transpiler, for developers, this may be useful if they want to implement some custom cluster program.

**Comment by reyoung** [comment]
I think it is no matter what `end users` will do.

We will provide a low-level program description of the multi-GPUs training process. It is no matter whether this low program description is generated by a transpiler or by Python program directly. We should at least make this low-level program description runnable.

It is easy to give a high-level Python wrapper or a multi-GPUs transpiler. We can even give both of them if necessary. There is no conflict to use any of `Python Wrapper`/`Transpiler`/`Compiler flag` to generate this low-level program description.

I think our first priority to

1. Determine what is this low-level program description.
2. Make this low-level program description runnable/trainable.
