### ISSUE TITLE
caffe2paddle.py脚本出错

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#6693]
![image](https://user-images.githubusercontent.com/3048612/34090413-b8f08c4c-e3f1-11e7-920c-21f66369b5b5.png)

**Comment by jacquesqiao** [comment]
上图的问题是因为protobuf版本不对，import caffe失败

**Comment by fangyanghua** [comment]
TypeError: __init__() got an unexptected keyword argument 'file'

caffe找不到原来编译时使用的protobuf，以致找不到原有的接口。使用python -c "import caffe"就可以看到明确的错误提示。

这个问题是这样引起的，为了转换caffe model到paddle格式，需要在一台机器上搭建caffe和paddle两种环境，中间遇到过很多问题，protobuf使用brew, pip, port等install和uninstall过多次，导致有多个版本的protobuf有不同的时期存在于系统中，当运行caffe时，原来编译时使用的protobuf已经不是配置的那个路径了。解决的办法就是确定使用一种protobuf，重新编译caffe就好了。

**Comment by jacquesqiao** [comment]
新问题：
![image](https://user-images.githubusercontent.com/3048612/34091296-b5ae9ff0-e3f7-11e7-93c7-1994789711f0.png)
但是convert_Scale_layer的时候出错了。
assert self.pre_layer_type == "BatchNorm"
在这一句。

**Comment by guoshengCS** [comment]
针对提出的Scale layer可以描述说明下么，因为我有转换过vgg、resnet、inception-resnet-v2等常用的一些网络结构，没有遇到这个问题

**Comment by guoshengCS** [comment]
Related to #6696 ，先行close，如有需要请reopen。
