### ISSUE TITLE
caffe2paddle.py无法处理Scale layer

### ISSUE THREAD

**Issue by fangyanghua** [PaddlePaddle/Paddle#6696]
好不容易在macOS上同时搭建了caffe和paddle的环境，用caffe2paddle.py转换的时候，出现了以下问题：
Traceback (most recent call last):
  File "caffe2paddle.py", line 188, in <module>
    converter.convert()
  File "caffe2paddle.py", line 34, in convert
    if name_map == None else name_map.get(layer_name))
  File "caffe2paddle.py", line 122, in convert_Scale_layer
    assert self.pre_layer_type == "BatchNorm"
AssertionError

是在转换Scale layer的时候assert被触发了。
layer {
  name: "scale"
  type: "Scale"
  bottom: "inception_5b/output"
  top: "inception_5b/output"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  scale_param {
    filler {
      type: "constant"
      value: 0.1
    }
    bias_term: true
    bias_filler {
      type: "constant"
      value: 0.0
    }
  }
}

问了Paddle的开发人员，现在Paddle只把Scale当做BatchNorm内部的一种实现，不能处理独立的Scale layer。
现在提出这一问题，希望Paddle能尽快实现对单独Scale layer的支持。

**Comment by guoshengCS** [comment]
请问一下这个scale是训练出来的么，还是只是常量

**Comment by guoshengCS** [comment]
方便的话把模型配置贴一下吧，因为我这边转过常用的VGG、Resnet、Inception-Resnet-V2的模型都没有这个问题，所以不太能确定就是你这里提的问题。

**Comment by fangyanghua** [comment]
layer {
  name: "scale"
  type: "Scale"
  bottom: "inception_5b/output"
  top: "inception_5b/output"
  param {
    lr_mult: 1
    decay_mult: 1
  }
  param {
    lr_mult: 2
    decay_mult: 0
  }
  scale_param {
    filler {
      type: "constant"
      value: 0.1
    }
    bias_term: true
    bias_filler {
      type: "constant"
      value: 0.0
    }
  }
}
上面贴过Scale layer的定义，再贴一下。
weight和bias的type都是constant.

**Comment by fangyanghua** [comment]
调查的结论：
1.Paddle现在就是不直接单独的且不跟在BN后面的Scale layer(转换出问题的网络，Scale layer之间是Concat layer)，如果要支持的话，convert script(caffe2paddle.py)和paddle framework都要动。
2.暂时搁置，后续训练采用不同的网络结构，或移除这个层来解决。
3.Paddle转换要求只有Conv, BN, FC这三种layer可以有参数，其它layer不能有训练出来的参数，且Scale layer必须跟在BN layer之后（原本经典BN的定义y=alpha*Xnorm+beta就包含了BN和Scale两种layer，四种参数alpha, beta, mean, variance, 而Caffe把经典BN拆成了BN + Scale两种layer, 其中alpha, beta就相当于Scale layer中的w, bias）。
4.caffe2paddle.py只能转换caffemodel，而prototxt转换到paddle格式的网络定义需要用户手写。希望Paddle以后做的自动化高些，使用protobuf读取prototxt，一并处理prototxt+caffemodel原本就关联的所有问题。

**Comment by guoshengCS** [comment]
先行close，如有需要请reopen。
