### ISSUE TITLE
Error on PaddlePaddle document

### ISSUE THREAD

**Issue by zhouxiao-coder** [PaddlePaddle/Paddle#670]
This document seems broken:
http://www.paddlepaddle.org/doc_cn/ui/predict/swig_py_paddle.html

![2016-11-30 3 55 10](https://cloud.githubusercontent.com/assets/22702369/20744190/6c2e8080-b715-11e6-99ab-5cdc913228bf.png)

I tested it on both chrome and safari on Mac.

**Comment by reyoung** [comment]
Closed due not to reproduce this problem.
