### ISSUE TITLE
paddlepaddle的common.dll被McAfee的Trellix Endpoint Security 标记为“Most Likely Malicious”

### ISSUE THREAD

**Issue by LaurenceLong** [PaddlePaddle/Paddle#67011]
### bug描述 Describe the Bug

paddlepaddle的common.dll被McAfee的Trellix Endpoint Security 标记为“Most Likely Malicious”
Composite Reputation: Most Likely Malicious (ATD)
File Name: common.dll
File Path: C:\Users\...\paddle_ocr.venv\Lib\site-packages\paddle\libs\common.dll
File Version: Not available
MD5: 5079A216594FB92C494640FE0425AE29
Product Name: Not available

**Comment by 2742195759** [comment]
你好，这个问题应该是杀毒软件的误判导致的吧。因为Paddle中存在一些端口和网络的访问（分布式训练），可能被错误识别为了病毒？

**Comment by LaurenceLong** [comment]
> 你好，这个问题应该是杀毒软件的误判导致的吧。因为Paddle中存在一些端口和网络的访问（分布式训练），可能被错误识别为了病毒？

可能是误报，我已经提交文件给杀软他们分析了，有后续我再更新

**Comment by 2742195759** [comment]
那我先关闭这个issue了，后续有更新在open吧。
