### ISSUE TITLE
paddleocr使用两个控制台训练，输出内容相同

### ISSUE THREAD

**Issue by TyrionChou** [PaddlePaddle/Paddle#67043]
### 请提出你的问题 Please ask your question

paddleocr使用两个控制台分别paddle.distributed.launch指令训练crnn和svtr，但是先运行的控制台也会输出后运行的控制台的输出，很奇怪，搜索了issue有一个相同的问题并没有解答

**Comment by tink2123** [comment]
控制台会同时输出多个同时训练的log，无法区分。但是训练log会保存在对应目录下，可以直接查看log来确认训练进度。

**Comment by TyrionChou** [comment]
> 控制台会同时输出多个同时训练的log，无法区分。但是训练log会保存在对应目录下，可以直接查看log来确认训练进度。

原来是这样，谢谢
