### ISSUE TITLE
Confusing debug string when testing layers.

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#6705]
Is it essential [printing debug string](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/test_layers.py#L22)  for testing layers?
```python
def test_fit_a_line(self):
        program = Program()
        with program_guard(program, startup_program=Program()):
            x = layers.data(name='x', shape=[13], dtype='float32')
            y_predict = layers.fc(input=x, size=1, act=None)
            y = layers.data(name='y', shape=[1], dtype='float32')
            cost = layers.square_error_cost(input=y_predict, label=y)
            avg_cost = layers.mean(x=cost)
            self.assertIsNotNone(avg_cost)
            program.append_backward(avg_cost)

        print(str(program))
```

If checking [proto.IsInitialized](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/framework.py#L87) is necessary, maybe we can call  [Program.to_string](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/framework.py#L208) instead of printing debug strings to stdout.

**Comment by JiayiFeng** [comment]
That is because we have no other convenient methods to check whether the layer is correct except printing and checking them manually.
