### ISSUE TITLE
请教：paddlepaddle的源码能编译支持国产银河麒麟ARM架构+英伟达显卡的硬件环境吗？哪一个版本的代码开始支持？

### ISSUE THREAD

**Issue by zhangjunhst** [PaddlePaddle/Paddle#67064]
paddlepaddle版本众多，2.5，2.6，3.0，请问目前哪一个版本的源码支持编译成支持国产ARM银河麒麟系统的 paddlepaddle-gpu，目前显卡T4

**Comment by zyfncg** [comment]
你好，目前我们还没有对ARM+NV_GPU的架构做过针对性的适配，可以尝试使用最新版本的paddlepaddle进行编译，有遇到问题的话发到issue里我们可以协助排查

**Comment by zhangjunhst** [comment]
你好，我们现在使用的版本是2.5版本的docker编译，cmake的编译参数为
cmake .. -DWITH_ARM=ON -DWITH_TESTING=OFF -DCUDA_ARCH_NAME=All -DWITH_NCCL=OFF -DCMAKE_CXX_FLAGS="-march=armv8-a -mtune=cortex-a53 -O2 -ffunction-sections -fdata-sections" -DCMAKE_C_FLAGS=" -ffunction-sections -fdata-sections" -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCMAKE_EXE_LINKER_FLAGS=" -Wl,--gc-sections" -DCMAKE_SHARED_LINKER_FLAGS="-Wl,--gc-sections"
在使用make编译，进行文件链接的时候，报错如下：
![WechatIMG2831](https://github.com/user-attachments/assets/76008bb5-ea87-485c-8e81-af00e7730665)
请问有什么解决方法吗？

**Comment by zyfncg** [comment]
`-DCUDA_ARCH_NAME=All` 这个配置项会编译GPU全架构代码，导致编译的文件体积过大而出现上述问题，可以尝试去掉该配置项重新编译。

**Comment by zhangjunhst** [comment]
目前，我们编译的服务器和运行的服务器不是同一个，使用的nvidia显卡型号也不同，如果不使用-DCUDA_ARCH NAME=ALL 这个选项的话，会不会导致在这边编译的可以用，但是换了显卡就不能用了？

**Comment by zyfncg** [comment]
那可以不用ALL，直接指定运行显卡的型号
<img width="866" alt="image" src="https://github.com/user-attachments/assets/d9141bde-411d-4133-985d-244dd23d913d">

**Comment by zhangjunhst** [comment]
您好，我们现在在使用Ampere编译，太慢了，在寻找的过程中我发现了[inference](https://www.paddlepaddle.org.cn/inference/v2.6/guides/install/download_lib.html)中存在arm+gpu的whl包请问这个是否可以直接使用
<img width="896" alt="image" src="https://github.com/user-attachments/assets/ce9744ec-5d5e-418a-be03-8e9cbc09a431">

**Comment by zyfncg** [comment]
推理的安装包和训练安装包的在编译选项上会有一定差异，不一定能直接用，可以试试

**Comment by zhangjunhst** [comment]
cmake的编译选项中有只对推理的编译选项吗？interference代码也是paddle的没有区分，无法只对推理进行编译

**Comment by zyfncg** [comment]
interference编包会关闭一些推理不使用的编译选项，有一部分代码就不会编到interference的包里

**Comment by zhangjunhst** [comment]
> 推理的安装包和训练安装包的在编译选项上会有一定差异，不一定能直接用，可以试试

我们在3050上尝试了可以了，但是在T4 显卡上报错了。
<img width="1181" alt="image" src="https://github.com/user-attachments/assets/ff111379-3456-498f-807a-c8dfb8bc433a">
这个是因为推理库不支持Turing架构吗？

**Comment by zhangjunhst** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/933e2644-2618-4f62-9d68-3aca2d505b23">
编译选项中的ON_INFER是只编译推理库，不编译训练库吗？

**Comment by zyfncg** [comment]
理论上应该没有编训练的部分，但实际中有些逻辑可能没有区分的很到位

**Comment by zyfncg** [comment]
<img width="797" alt="image" src="https://github.com/user-attachments/assets/b6223f61-683f-4727-b42e-a435d287c6dc">

T4是不是不在这几个架构范围内？

**Comment by zhangjunhst** [comment]
> 那可以不用ALL，直接指定运行显卡的型号 <img alt="image" width="866" src="https://private-user-images.githubusercontent.com/13048366/355310880-d9141bde-411d-4133-985d-244dd23d913d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMTAzNTQsIm5iZiI6MTcyMzExMDA1NCwicGF0aCI6Ii8xMzA0ODM2Ni8zNTUzMTA4ODAtZDkxNDFiZGUtNDExZC00MTMzLTk4NWQtMjQ0ZGQyM2Q5MTNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDA5NDA1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlNzNiZmZkMjdmMjJjZTVlNjUxZmNjZmMxYWUxNTE4MjJjMzRkM2UxMTc2OTc4NTM4OGRlM2JiMzE0ZDkyYWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9YaKaDRjtGa58AIpTIoLPOfIU72l8MGdytHBRPakuZE">


是的 T4代表的是75，理论上我使用Turing编译出来的是支持T4的版本吗？

**Comment by zyfncg** [comment]
<img width="595" alt="image" src="https://github.com/user-attachments/assets/0244994c-852f-4909-949e-0fafd21e7e61">

Turing编出来的是75，T4应该可以匹配

**Comment by zhangjunhst** [comment]
已解决🎆🎆，感谢大佬

**Comment by gadLei** [comment]
大佬，请教一下，能使用windows本机编译编译arm的paddlepaddle-gpu吗
