### ISSUE TITLE
寒武纪飞桨基础健康检查报错libmluops.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xiaolongking** [PaddlePaddle/Paddle#67084]
### 问题描述 Issue Description

飞桨基础健康检查报错：
λ localhost /work python -c "import paddle; paddle.utils.run_check()"
I0806 14:00:20.592200    67 init.cc:236] ENV [CUSTOM_DEVICE_ROOT]=/usr/local/lib/python3.10/dist-packages/paddle_custom_device
I0806 14:00:20.592232    67 init.cc:145] Try loading custom device libs from: [/usr/local/lib/python3.10/dist-packages/paddle_custom_device]
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/paddle/__init__.py", line 37, in <module>
    from .base import core  # noqa: F401
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/__init__.py", line 204, in <module>
    __bootstrap__()
  File "/usr/local/lib/python3.10/dist-packages/paddle/base/__init__.py", line 196, in __bootstrap__
    core.init_devices()
ValueError: (InvalidArgument) Fail to open library: /usr/local/lib/python3.10/dist-packages/paddle_custom_device/libpaddle-custom-mlu.so with error: libmluops.so.1: cannot open shared object file: No such file or directory
  [Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/init.cc:152)

### 版本&环境信息 Version & Environment Information

PaddlePaddle版本：3.0.0.dev20240805
系统：银河麒麟ky10.x86_64
docker:paddle-mlu:ubuntu20-x86_64-gcc84-py310
寒武纪MLU370-S4
version: 3.0.0
commit: bb09ae7faabae6a75e3dba44c85b70fd2d38173a
cntoolkit: 3.10.1
cnnl: 1.25.1
cnnl_extra: 1.8.1
cncl: 1.16.0
mluops: 1.1.1
![image](https://github.com/user-attachments/assets/ad688b11-dedd-42cd-b84f-894a38f45052)

**Comment by zyfncg** [comment]
根据报错信息看是没有找到动态链接库`libmluops.so.1`，可以在根目录下检索是否有该文件，如果有的话手动加到链接PATH中试试

**Comment by xiaolongking** [comment]
> 根据报错信息看是没有找到动态链接库`libmluops.so.1`，可以在根目录下检索是否有该文件，如果有的话手动加到链接PATH中试试
没有动态链接库libmluops.so.1，只有
/usr/local/neuware/lib64/libmluops.so
/usr/local/neuware/lib64/libmluops.so.0
/usr/local/neuware/lib64/libmluops.so.0.11.0

**Comment by zyfncg** [comment]
会不会是版本不匹配的问题？

**Comment by xiaolongking** [comment]
> 会不会是版本不匹配的问题？

跑起来了，感谢，降级就可以了

**Comment by fei9157** [comment]
@xiaolongking

**Comment by fei9157** [comment]
> > 会不会是版本不匹配的问题？
> 
> 跑起来了，感谢，降级就可以了

麻烦问下，用的哪个版本，3.0吗，2.6好像不支持寒武纪

**Comment by fei9157** [comment]
> > 会不会是版本不匹配的问题？
> 
> 跑起来了，感谢，降级就可以了

麻烦问下，用的哪个版本，3.0吗，2.6好像不支持寒武纪 @xiaolongking
