### ISSUE TITLE
请问有用paddle实现二分类问题的模型吗？

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#6722]
请问有用paddle实现二分类问题的模型吗？

**Comment by JiayiFeng** [comment]
paddle book中的情感分类就是二分类。
https://github.com/PaddlePaddle/book/tree/develop/06.understand_sentiment

**Comment by 466821202** [comment]
恩恩，这个是文本二分类，我现在需要图像的，我有大量的一张有垃圾，一张垃圾清理后的图片，我想训练一个可以自动审核有没有处理的！

**Comment by peterzhang2029** [comment]
duplicated with https://github.com/PaddlePaddle/Paddle/issues/6740
