### ISSUE TITLE
官网文档中的Latex符号没有正确渲染

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6723]
PaddlePaddle 官网文档中存在 Latex 符号没有正确渲染的问题： http://www.paddlepaddle.org/docs/develop/models/nce_cost/README.html

上面文章中希腊字母omega没有正确渲染：
![image](https://user-images.githubusercontent.com/5842774/34137608-dc82e4a6-e4a6-11e7-9d36-8f6185c6a3fa.png)

同样问题也存在于 operator 文档中：
http://www.paddlepaddle.org/docs/develop/documentation/zh/operators.html#permalink-160-linear_chain_crf

在上面的文档中，希腊字母 alpha 也没有被正确的渲染。
![image](https://user-images.githubusercontent.com/5842774/34137647-11dc1956-e4a7-11e7-9f71-4446920a521f.png)

**Comment by luotao1** [comment]
@lcy-seso 可以提到paddlepaddle.org repo下，很快就会回复和修复的。

**Comment by jetfuel** [comment]
@lcy-seso When converting `md` files to `html` files, the `md` files go through `pymdownx.escapeall` so every char after a `\` gets escaped. This process, however, removes all the `\` from latex code. For example, `\omega` becomes `omega`. We will have some discussion within the team to figure out what's the best approach to resolve this issue. Thanks.

**Comment by jetfuel** [comment]
@lcy-seso We just released a new www.paddlepaddle.org that will fix this issue for Models. Once Models repo updates its code, the content will get re-generated and you should see the Latex symbols in Models. Thanks

**Comment by lcy-seso** [comment]
Thank you for fixing this.
