### ISSUE TITLE
我有大量的一张有垃圾，一张垃圾清理后的图片，我想训练一个可以自动审核垃圾有没有清理的模型！希望可以推荐一个！

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#6740]
我有大量的一张有垃圾，一张垃圾清理后的图片，我想训练一个可以自动审核垃圾有没有清理的模型！希望可以推荐一个！

**Comment by peterzhang2029** [comment]
是否可以将有垃圾的图片标记为1，垃圾清理之后的图片标记为0，用图片分类模型来进行建模？ 我们的models repo下有图片分类的示例: https://github.com/PaddlePaddle/models/tree/develop/image_classification

**Comment by 466821202** [comment]
这个不可以，有垃圾和没有垃圾的图片必须是一一对应的！

**Comment by 466821202** [comment]
只有确定是同一个地方垃圾被清理了，才算清理了！

**Comment by peterzhang2029** [comment]
同一个地方的垃圾在图片里如何体现？ 可否再详细描述一下 你的输入是什么 标记数据是什么  想要建立的模型的目的是什么？想要输出什么？

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
