### ISSUE TITLE
dockerhub.com paddle repo need a descriptive document

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#6752]
dockerhub.com paddle repo need a descriptive document.
https://hub.docker.com/r/paddlepaddle/paddle/

Refer to this https://hub.docker.com/r/paddledev/paddle/ 'Full Description'

**Comment by luotao1** [comment]
Can we refine the 'Full Description' of https://hub.docker.com/r/paddledev/paddle/  to tell the users that the latest docker images are in https://hub.docker.com/r/paddlepaddle/paddle/ ?

**Comment by llxxxll** [comment]
Or refer to the readme of the https://github.com/PaddlePaddle/Paddle/blob/develop/README.md
Because I see this 「https://hub.docker.com/r/paddledev/paddle/ Full Description」 version of information very old :(

**Comment by Yancey1989** [comment]
The `paddledev` repo in DockerHub was set to an `Automated build ` repo, this means that it would sync the READM.md from the GitHub Repo `PaddlePaddle/Paddle`. But the `paddlepaddle` repo in DockerHub was set to a normal one, and maybe we couldn't change this to `automated build`. So how about just sync the [README.md]( https://github.com/PaddlePaddle/Paddle/blob/develop/README.md) to the DockerHub?

**Comment by luotao1** [comment]
@Yancey1989 and I have already updated the Full Description of two docker repos.
