### ISSUE TITLE
损失函数为huber_classification_cost报错

### ISSUE THREAD

**Issue by buptwds** [PaddlePaddle/Paddle#6753]
数据和代码（除了损失函数）都一样，损失函数为huber_regression_cost和multi_binary_label_cross_entropy 时可以正常运行，但改为huber_classification_cost时报错如下：
![image](https://user-images.githubusercontent.com/10849519/34156167-0506d360-e4f7-11e7-80ea-e18ba843663d.png)

**Comment by peterzhang2029** [comment]
报错信息来自 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L675  可以贴一下你的训练配置么？

**Comment by lcy-seso** [comment]
请不要在issue中贴图。

**Comment by buptwds** [comment]
配置参考models/ctr的配置，label用的是dense_vector，样本中的值为1和-1，请问CHECK(label.ids)这行代码check的是什么呢，label的类型？

**Comment by peterzhang2029** [comment]
@buptwds huber_classification_cost中label的输入类型应该是paddle.data_type.integer_value(2)类型的，如果输入是dense_vector类型，CHECK(label.ids)会检测为空而报错。
