### ISSUE TITLE
Documentation 翻译错误

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#6762]
<img width="316" alt="c754438e1727ea311be493a542b2984a" src="https://user-images.githubusercontent.com/1908992/34189636-6f5b65d4-e577-11e7-88a5-1c534c4bfe13.png">
http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/getstarted/index_cn.html

文件>文档

**Comment by daming-lu** [comment]
http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/getstarted/index_cn.html
