### ISSUE TITLE
PaddlePaddle源码离线编译

### ISSUE THREAD

**Issue by MemoryAnt** [PaddlePaddle/Paddle#67649]
### 需求描述 Feature Description

需要在离线的FT S2500 + 昆仑R200 环境中安装paddle框架进行深度学习模型的推理；
源码编译过程中汇报网络连接失败，是否有编译好的文件或者离线环境编译的方式

**Comment by wanghuancoder** [comment]
我先尝试回答一下，然后我再请更了解的同学帮忙确认一下：
1. Paddle编译需要下载很多第三方源码，因此你编译时会报网络连接失败。
2. 你可以先在有网的环境下执行cmake，cmake会触发所有第三方源码的下载。之后将这个Paddle目录复制到离线环境编译
3. 你可以找一个等同的有线环境编译，然后将whl包放到离线环境使用

**Comment by wanghuancoder** [comment]
请 @XieYunshen 帮忙看看是否还有其他的好办法~感谢！

**Comment by XieYunshen** [comment]
> 请 @XieYunshen 帮忙看看是否还有其他的好办法~感谢！
可以使用这个链接
https://paddle-qa.bj.bcebos.com/CE-BuildTask-Clone/develop/linux/latest/Paddle.tar.gz

**Comment by MemoryAnt** [comment]
> 我先尝试回答一下，然后我再请更了解的同学帮忙确认一下：
> 
> 1. Paddle编译需要下载很多第三方源码，因此你编译时会报网络连接失败。
> 2. 你可以先在有网的环境下执行cmake，cmake会触发所有第三方源码的下载。之后将这个Paddle目录复制到离线环境编译
> 3. 你可以找一个等同的有线环境编译，然后将whl包放到离线环境使用

感谢，2、3两种方法也有考虑，现在情况是机器禁止联网，外网环境中找不到相同配置的机器，所以也只能求助一下官方有没有类似环境中编译好的whl文件，或者有没有安装好依赖的离线版本

**Comment by MemoryAnt** [comment]
> > 请 @XieYunshen 帮忙看看是否还有其他的好办法~感谢！
> > 可以使用这个链接
> > https://paddle-qa.bj.bcebos.com/CE-BuildTask-Clone/develop/linux/latest/Paddle.tar.gz

感谢，我试一下
