### ISSUE TITLE
need to add a data member to represent the Layout of a Tensor

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#6765]
Actually, a Tensor is a view of a block of memory. Besides a pointer to the memory, we also have to get some other descriptions of this block of memory, such as shape(ddim), stride, and layout.

Different layout leads to different implementation of operator kernel. There are mainly 4 principles we have to follow to support layout in our fluid framework.

- We take layout as a data member of Tensor. Layout is actually a enum variable. If fluid is built with MKLDNN, then, the memory format in MKLDNN will be added into this enum variable too.

- Users have to set layout for input data. And some operators like fill_constant/random, also have to set layout of generating data. Of course, we can have some default layout, like NCHW.

- The inference of Layout is at run-time, not compile-time.

- Every operator have to implement different kernels for different layouts. Let's take MKLDNN as an example, if we want to implement a MKLDNN convolution operator, we have to realize all the kernels for different layout, list at [here](http://01org.github.io/mkl-dnn/structmkldnn_1_1memory.html). And we will have a special macro to do registering kernels for MKLDNN operators.

**Comment by tensor-tang** [comment]
> could we let the operation itself to decide the output tensor layout in the function InferShape.

please forget about this point. `InferShape` should only focus on reshaping size, and put the layout things into `compute` would be more appropriate.

**Comment by QiJune** [comment]
> The layout after the first conv should always keep as nChw8c then we do not need to convert layout back and forth. And we do not need users to set the layout as nChw8c of those operations manually.
Yes, the default layout I say in principle 2 is only for input data and fill_constant/random operator. And we only expose setting layout in these interface. For other operators, users do need to set layout. The layout is decided at run-time and can be passed to next operator.

> One more question: the registering includes input layout, not output layout right?
Yes, only includes input layout. Because different input layout will lead to different implementation. Does this assumption have shortcoming?

> And a little more explanations about the formats in mkldnn. You can see many format in the link, but some of them are for weights, so we can only focus on the data flow format, such as nchw, nChw8c.

That's a good news!
