### ISSUE TITLE
GPU版本的PaddlePaddle内存问题

### ISSUE THREAD

**Issue by ApocalypticDoctor** [PaddlePaddle/Paddle#67702]
### 请提出你的问题 Please ask your question

安装GPU版本的paddlepaddle后使用PaddleOCR会占据大量内存(内存占用会越来越大)最后导致识别不到图片，即使手动清理内存后，仍然会出现识别不到图片的情况，请问这个该怎么解决啊

**Comment by LiYuRio** [comment]
你好，请问是占用大量内存（CPU）还是显存（GPU）？

**Comment by ApocalypticDoctor** [comment]
是CPU 他占用会越来越高



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年8月26日(星期一) 上午10:07
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] GPU版本的PaddlePaddle内存问题 (Issue #67702)














 
你好，请问是占用大量内存（CPU）还是显存（GPU）？

**Comment by ApocalypticDoctor** [comment]
呃 是这个内存




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] GPU版本的PaddlePaddle内存问题 (Issue #67702)





 
你好，请问是占用大量内存（CPU）还是显存（GPU）？

**Comment by ApocalypticDoctor** [comment]
是这个内存 然后刚刚发现GPU显存也会吃满
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "PaddlePaddle/Paddle"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月26日(星期一) 上午10:07
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [PaddlePaddle/Paddle] GPU版本的PaddlePaddle内存问题 (Issue #67702)





 
你好，请问是占用大量内存（CPU）还是显存（GPU）？

**Comment by LiYuRio** [comment]
请问用的Paddle的版本是？能提供最小复现case吗

**Comment by ApocalypticDoctor** [comment]
> 请问用的Paddle的版本是？能提供最小复现case吗

paddle是2.6.1.post117 paddleocr是2.8.1  触发的条件暂未确定 所以无法提供

**Comment by LiYuRio** [comment]
猜测可能是数据流存在内存泄漏，可以review一下代码

**Comment by ApocalypticDoctor** [comment]
> 猜测可能是数据流存在内存泄漏，可以review一下代码

这个是代码 可以帮我看看嘛 🙏🙏🙏
![QQ截图20240826113937](https://github.com/user-attachments/assets/e6f69fb6-0db4-4dbf-bee8-102619434ffb)

**Comment by ApocalypticDoctor** [comment]
> 猜测可能是数据流存在内存泄漏，可以review一下代码

嗯....貌似解决了 paddle切换到3版本显存占用就趋于一个比较低的值了 感谢
