### ISSUE TITLE
Wrong documents of Fluid python layer helpers.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6773]
The documentation of many layers' helper is not consistent with their codes:

For example:
http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid/layers.html#fc
![image](https://user-images.githubusercontent.com/5842774/34193992-7a459932-e591-11e7-86b4-aaa523d499e9.png)

The parameter `main_program` and `startup_program` should be removed.

**Comment by luotao1** [comment]
The parameters `main_program` and `startup_program` have already been removed.
