### ISSUE TITLE
源码编译出错

### ISSUE THREAD

**Issue by gengzhaoyun** [PaddlePaddle/Paddle#6786]
[root@TX-master build]# cmake -DWITH_GPU=OFF -DWITH_TESTING=OFF ..
-- Found Paddle host system: centos, version:
-- Found Paddle host system's CPU: 1 cores
-- CXX compiler: /usr/bin/c++, version: 4.8.5
-- C compiler: /usr/bin/cc, version: 4.8.5
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
-- Protobuf protoc executable: /root/paddle/Paddle/build/third_party/install/protobuf/bin/protoc
-- Protobuf library: /root/paddle/Paddle/build/third_party/install/protobuf/lib/libprotobuf.a
-- Protobuf version: 3.1
-- Found cblas and lapack in MKLML (include: /root/paddle/Paddle/build/third_party/install/mklml/mklml_lnx_2018.0.1.20171007/include, library: /root/paddle/Paddle/build/third_party/install/mklml/mklml_lnx_2018.0.1.20171007/lib/libmklml_intel.so)
-- BLAS library: /root/paddle/Paddle/build/third_party/install/mklml/mklml_lnx_2018.0.1.20171007/lib/libmklml_intel.so
-- Set /root/paddle/Paddle/build/third_party/install/mkldnn/lib to runtime path
-- Build MKLDNN with MKLML /root/paddle/Paddle/build/third_party/install/mklml/mklml_lnx_2018.0.1.20171007
-- MKLDNN library: /root/paddle/Paddle/build/third_party/install/mkldnn/lib/libmkldnn.so
-- Found SWIG: /usr/bin/swig (found version "2.0.10")
-- warp-ctc library: /root/paddle/Paddle/build/third_party/install/warpctc/lib/libwarpctc.so
-- Enable Intel OpenMP with /root/paddle/Paddle/build/third_party/install/mklml/mklml_lnx_2018.0.1.20171007/lib/libiomp5.so
-- Looking for UINT64_MAX
-- Looking for UINT64_MAX - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of pthread_spinlock_t
-- Check size of pthread_spinlock_t - done
-- Check size of pthread_barrier_t
-- Check size of pthread_barrier_t - done
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test C_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fPIC - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test C_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__fno_omit_frame_pointer - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wall - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wextra - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test C_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Werror - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wnon_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wdelete_non_virtual_dtor - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_parameter - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_literal_suffix - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_sign_compare - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_unused_local_typedefs - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_parentheses_equality - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_ignored_attributes - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_error_terminate - Failed
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_unused_function - Success
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds
-- Performing Test C_COMPILER_SUPPORT_FLAG__Wno_error_array_bounds - Success
-- Paddle version is 0.11.0
-- Compile with MKLDNNMatrix
-- Compile with MKLDNNLayers and MKLDNNActivations
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__ftls_model_global_dynamic
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__ftls_model_global_dynamic - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses_equality
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_parentheses_equality - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_self_assign
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_self_assign - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_maybe_uninitialized
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_maybe_uninitialized - Success
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_missing_field_initializers
-- Performing Test CXX_COMPILER_SUPPORT_FLAG__Wno_missing_field_initializers - Success
CMake Deprecation Warning at /usr/local/share/cmake-3.10/Modules/UseSWIG.cmake:231 (message):
  SWIG_ADD_MODULE is deprecated.  Use SWIG_ADD_LIBRARY instead.
Call Stack (most recent call first):
  paddle/api/CMakeLists.txt:66 (SWIG_ADD_MODULE)

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
Boost_INCLUDE_DIR (ADVANCED)
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/proto
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle/optimizer
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/cuda
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/function
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/utils
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/math
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/gserver
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/parameter
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/testing
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/pserver
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/trainer
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/string
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/scripts
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/paddle/api
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python
   used as include directory in directory /root/paddle/Paddle/python

-- Configuring incomplete, errors occurred!
See also "/root/paddle/Paddle/build/CMakeFiles/CMakeOutput.log".
See also "/root/paddle/Paddle/build/CMakeFiles/CMakeError.log".

**Comment by yeyupiaoling** [comment]
多半是缺少依赖包,这是一个教程,我是跟着这个教程做的[http://www.jianshu.com/p/c6264cd5f5c7](http://www.jianshu.com/p/c6264cd5f5c7) #6054

**Comment by gengzhaoyun** [comment]
我也正想安利这篇文章，http://www.jianshu.com/p/c2c76893e306
我在ubuntu上编译成功了。

等下试试centOS

**Comment by yeyupiaoling** [comment]
嗯嗯，加油！

**Comment by gengzhaoyun** [comment]
在mac上编译，报错误
[ 59%] Built target framework_py_proto_init
paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60: *** target pattern contains no `%'.  Stop.
make[1]: *** [paddle/framework/CMakeFiles/framework_py_proto.dir/all] Error 2
make: *** [all] Error 2

**Comment by gengzhaoyun** [comment]
在centOS上编译，报错误
[ 63%] Built target executor
[ 63%] Built target framework_py_proto_init
paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60: *** 目标模式不含有“%”。 停止。
make[1]: *** [paddle/framework/CMakeFiles/framework_py_proto.dir/all] 错误 2
make: *** [all] 错误 2

我继续找找原因。

**Comment by gengzhaoyun** [comment]
在mac上编译错误的问题解决了。
在build下  rm -rf *
重新make
之前出现错误可能是因为make -j8多线程编译了，不要多线程编译。

**Comment by yeyupiaoling** [comment]
不是最多`-j4`吗？

**Comment by yeyupiaoling** [comment]
你的那些问题都处理好了吗？

**Comment by gengzhaoyun** [comment]
@yeyupiaoling 我在mac和ubuntu上成功编译了，在centOS7.3上还没有编译成功。
make -j4后面跟的这个数字跟编译环境的CPU线程数有关吧。
我今天上午再试试centOS环境的编译。

**Comment by gengzhaoyun** [comment]
CentOS6.8上编译 卡在
Scanning dependencies of target extern_mklml
[  0%] Creating directories for 'extern_mklml'
[  0%] Performing download step for 'extern_mklml'

我暂时用其它环境编译吧，centOS有时间了再搞，问题可以关闭，多谢。

**Comment by Xreki** [comment]
> Scanning dependencies of target extern_mklml
[ 0%] Creating directories for 'extern_mklml'
[ 0%] Performing download step for 'extern_mklml'

这个是下载或者是网速问题。可以使用`cmake -DWITH_MKL=OFF ..`

**Comment by yeyupiaoling** [comment]
大佬出现了，好久没见你身影了

**Comment by putcn** [comment]
@gengzhaoyun 我在mac上重新cmake, 然后单线程make, 还是同样的错误
```
Scanning dependencies of target framework_py_proto_init
[ 56%] Built target framework_py_proto_init
paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60: *** target pattern contains no `%'.  Stop.
make[1]: *** [paddle/framework/CMakeFiles/framework_py_proto.dir/all] Error 2
make: *** [all] Error 2
```
还有一个issue也是关于这个错误, 给出的解决方案是手动安装protobuf, 但是在我的环境里面也不解决问题...
https://github.com/PaddlePaddle/Paddle/issues/6441

**Comment by gengzhaoyun** [comment]
@putcn 
我是这么解决的
在mac上编译错误的问题解决了。
在build下 rm -rf *
重新make
之前出现错误可能是因为make -j8多线程编译了，不要多线程编译。

你cmake后注意看这个文件
paddle/framework/CMakeFiles/framework_py_proto.dir/build.make:60
的60行的路径有没有问题，如果有两个:: 那就是一个有问题的路径。
可能是环境配置的有问题。

**Comment by putcn** [comment]
@gengzhaoyun 哈, 谢谢. 找到我的问题根源了, 是cmake版本的问题, 在mac上3.4 的cmake就一切ok了, 我在8核的机器上用了8个线程build也是成功的
