### ISSUE TITLE
Sentiment单机demo中预测函数不支持流式预测（读一行样本预测一行样本）

### ISSUE THREAD

**Issue by DrakeNi** [PaddlePaddle/Paddle#679]
Hi， 参考sentiment demo中的predict.py的预测函数，发现是将所有的预测样本一次性加载完后再输出结果， 自己跑的预测样本量一大，单机内存就爆掉了

改进了一下，读进样本的每一行就进行预测
但想知道能否提供流失预测的接口，比如从sys.stdin读入一行样本，就sys.stdout输出一个结果（或者有batch）进行处理
由于工作环境是在linux下，如果支持文件流式预测，会方便许多~

**Comment by qingqing01** [comment]
@DrakeNi sentiment demo中的预测示例只预测了一条样本。 可以改进提供流式预测方式~

**Comment by HugoLian** [comment]
重新下载这里的predict.sh predict.py就可以，但是我没有把这个移植成功到其他网络结构中。。。：（ https://github.com/PaddlePaddle/Paddle/tree/develop/demo/sentiment
