### ISSUE TITLE
图像分类问题,使用reader.py读取的图片,图片要做预处理吗?

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6795]
* 使用这个读取文件[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L27](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L27)
* 要对图像先做预处理,比如统一大小

**Comment by ranqiu92** [comment]
数据层定义时有对数据类型和维数的设置，所输入的数据 和 该设置 需要一致。

**Comment by yeyupiaoling** [comment]
@ranqiu92 这行代码[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13)是不是自动处理大小问题

**Comment by ranqiu92** [comment]
它会把数据处理成  crop_size * crop_size

**Comment by yeyupiaoling** [comment]
> resize_size（int） - 调整大小的图像的较短边缘长度。
这个是什么意思,有了`crop_size`是不是就不用预处理图片了?

**Comment by ranqiu92** [comment]
根据代码，resize_size 是改变图片大小，但保持 图片宽度高度比不变，有crop_size 之后，大小上的预处理应该就不用了。

**Comment by yeyupiaoling** [comment]
@ranqiu92 哦哦,我明白了,谢谢您!
