### ISSUE TITLE
Merge `Tensor` and `LoDTensor` class

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#6798]
In protocol buffer, tensor and lodtensor are of the same type.

https://github.com/PaddlePaddle/Paddle/blob/e445b3ff20f0c568b7d01ed91cbd154c745e124c/paddle/framework/framework.proto#L118-L126

This consistency should stay true at the class level.

**Comment by jacquesqiao** [comment]
why do we need to merge these two classes or Why do we need to keep these two classes?

**Comment by tonyyang-svail** [comment]
@jacquesqiao In the current implementation:

https://github.com/PaddlePaddle/Paddle/blob/61ec0b951656fb402e61c4dc519e80ba3fbc61d0/paddle/operators/mul_op.h#L30

Calls

https://github.com/PaddlePaddle/Paddle/blob/e445b3ff20f0c568b7d01ed91cbd154c745e124c/paddle/framework/operator.h#L314-L315

Calls

https://github.com/PaddlePaddle/Paddle/blob/e445b3ff20f0c568b7d01ed91cbd154c745e124c/paddle/framework/operator.cc#L202-L206

Calls

https://github.com/PaddlePaddle/Paddle/blob/e445b3ff20f0c568b7d01ed91cbd154c745e124c/paddle/framework/operator.cc#L178-L188

Meaning, even though `context.Input<Tensor>("X");` is called on the surface, deep down the code the type returned is `LoDTensor`. This is fundamentally wrong.

We have to remove `Tensor` class so that the code is less error-prone. For example, let's say someone calls `var->Mutable<Tensor>`, but the underlying type is `LoDTensor`, the call would return a brand new tensor.
