### ISSUE TITLE
如何将python环境打包，实现在hadoop集群上批量预测

### ISSUE THREAD

**Issue by DrakeNi** [PaddlePaddle/Paddle#680]
RT, 需要对大批量的数据进行预测，并且需要对预测代码进行修改（比如选择概率最大的top N, softmax)
如何将本地的python预测接口和环境打包到hadoop集群上，批量读入流式样本，然后进行预测？

**Comment by backyes** [comment]
类似在spark上跑预测，https://github.com/PaddlePaddle/Paddle/issues/692

**Comment by backyes** [comment]
@DrakeNi  

我们会归总下用户这种需求，希望能推出一个工具，帮助大家将预测跑到Spark、hadoop、mpi等集群上。 另外，你能否给出一点典型case，通过case描述清楚需求，我们好有针对性的解决问题。也欢迎这里讨论。
#692 也有类似讨论

**Comment by jacquesqiao** [comment]
@DrakeNi "批量读入流式样本"  流式是什么含义

**Comment by backyes** [comment]
@DrakeNi 

 我们写了一个在spark上跑py_paddle预测的demo，http://gitlab.baidu.com/idl-dl/predict_on_clusters 。

针对问题本身，我理解的解决方法： 

> 需要对大批量的数据进行预测，并且需要对预测代码进行修改（比如选择概率最大的top N, softmax)
 这个可以考虑对预测的输出进行进一步处理，或者直接hack 预测代码py_paddle，重新编译生成预测库，比如new_py_paddle。 

> 如何将本地的python预测接口和环境打包到hadoop集群上
在hadoop上做预测的话，不需要遵循hadoop 的map reduce架构，可以写一个shell的map脚本，hadoop框架会传递hdfs上的分块数据给map脚本，之后的逻辑完全可以自己控制。比如，此处在shell里调用py_paddle即可 。 
py_paddle是一个带so动态运行时库的py库，因此理论上你只需要将这个py_paddle的python库通过在map脚本设置PYTHONPATH=指向这个python库，就可以了。 实际上，paddle由于最低需要gcc48编译运行时环境，所以py_paddle里面的so库也需要gcc48运行时环境，那么需要编译一个支持gcc48的python解释器。对于百度用户，所有这些都可以通过一键脚本自动打包，您只需要将打包完的python27-gcc48解释器打包到hadoop集群即可（具体文档可以参看构建私有paddle的文档）。

> 批量读入流式样本
这个问题能否再详细描述下， 你是需要实时预测么？

**Comment by backyes** [comment]
@DrakeNi 

```
http://gitlab.baidu.com/idl-dl/predict_on_clusters 
```
请关注这个repo中demo（针对百度内部环境专门构建的demo），此处关闭此issue。

对于外部用户， 同理也可以将py_paddle python包打包到hadoop、spark、mpi集群上进行预测，将py_paddle视为一个普通的接入输入产出一个输出的模块，无需特殊处理。
