### ISSUE TITLE
fluid 是否支持一些数学操作

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6800]
fluid 目前是否支持一些数学操作，比如min  max  等数学运算？

**Comment by chengduoZH** [comment]
> fluid 目前是否支持一些数学操作，比如min max 等数学运算？

当前Fluid是有min, max数学操作的：  https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/elementwise_max_op.h
同时也支持对每一个layer的输出进行简单的数学计算，如加减乘除：
https://github.com/PaddlePaddle/Paddle/blob/3646be7bfca135fc20eb291dcbe14e13c93d8429/python/paddle/v2/fluid/tests/test_math_op_patch.py#L23-L177
