### ISSUE TITLE
Questions about CMake

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#681]
我感觉cmake的设计里有一些对维护大项目不利的地方。但是我也不知道有什么更好的办法。所以先把我碰到的一些问题记录在这里。

**Comment by wangkuiyi** [comment]
我在看Paddle的Python API的代码。当我在看[`paddle/api/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/CMakeLists.txt#L18)的时候，看到 

```
add_dependencies(paddle_api gen_proto_cpp)
```

为了找到 `gen_proto_cpp`定义在哪里，我搜搜了代码库里所有的 CMakeLists.txt 文件。

由此感触：希望一个build system（比如cmake）能有更好的 top-level target 管理方式，帮助我们跟容易地找到定义在不同目录里的targets。

**Comment by wangkuiyi** [comment]
我在看cmake [tutorial](https://cmake.org/cmake-tutorial/)的时候，意识到cmake维护者不少global information。比如：

```
# add the binary tree to the search path for include files
# so that we will find TutorialConfig.h
include_directories("${PROJECT_BINARY_DIR}")
```

`include_directories`会把参数中的目录**添加**到**当前search paths里**。这个**当前search paths**就是一个global information。它不仅影响本 CMakeLists.txt 文件里定义的targets，而且很难顾名思义的推测这会不会影响同一个项目里其他CMakeLists.txt里定义的targets。

**Comment by wangkuiyi** [comment]
以下这段和gflags相关的[代码](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/CMakeLists.txt#L21)

```
if(WITH_GFLAGS)
  list(LENGTH "${GFLAGS_LIBRARIES}" GFLAGS_LIBRARIES_LENGTH)

  if(${GFLAGS_LIBRARIES_LENGTH} EQUAL 0 AND TARGET "${GFLAGS_LIBRARIES}")
    # Because gflags compiled by cmake, so it is imported by cmake target,
    # not a real library path. Get the real library path here.
    message(STATUS "GFLAGS Libraries is ${GFLAGS_LIBRARIES}")
    get_target_property(GFLAGS_LOCATION ${GFLAGS_LIBRARIES} LOCATION)
    message(STATUS "GFLAGS Target location is ${GFLAGS_LOCATION}")
  else()
    set(GFLAGS_LOCATION ${GFLAGS_LIBRARIES})
  endif()
endif()
```

应该是不需要的。因为“强制”使用gflags并不难——只需要在paddle的repo里用git submodule建一个external dependency，指向 https://github.com/gflags/gflags/tree/v2.2.0

**Comment by wangkuiyi** [comment]
在 [`/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/CMakeLists.txt)里，很多地方用了 `include_directories`。有的引用Paddle项目里的header files，有的是external dependencies，都混在一起：

```
include_directories("${CBLAS_INC_DIR}")
include_directories("${PROJ_ROOT}")
include_directories("${PROJ_ROOT}/paddle/cuda/include")
include_directories(${PROTOBUF_INCLUDE_DIRS})
include_directories("${CMAKE_CURRENT_BINARY_DIR}/proto")
include_directories(${CUDNN_INCLUDE_DIR})
include_directories(${CUDA_TOOLKIT_INCLUDE})
```

这样很难拆解开Paddle的哪些模块依赖哪些include search paths。如果将来删改某些Paddle模块，很难对应更新 include search paths。

-------

反过来，Bazel定义了很清晰的模块之间的 include file dependencies。以下例子来自[Bazel C++ guide](https://bazel.build/versions/master/docs/tutorial/cpp.html#transitive-includes):

```
If a file includes a header, then the file's rule should depend on that header's library.

cc_library(
    name = "sandwich",
    srcs = ["sandwich.cc"],
    hdrs = ["sandwich.h"],
    deps = [":bread"],
)

cc_library(
    name = "bread",
    srcs = ["bread.cc"],
    hdrs = ["bread.h"],
    deps = [":flour"],
)

cc_library(
    name = "flour",
    srcs = ["flour.cc"],
    hdrs = ["flour.h"],
)
```

**Comment by reyoung** [comment]
这是C++项目本身的一个大问题。

C++ **事实上** 没有一个很好的编译工具链，这很大程度上也和C++语言的性质本身有关系。实际上Paddle开始使用的工具链也不是cmake，而是百度内部的编译工具链。

## 一个好的C++的编译工具链应该有什么

* C++源码级模块依赖
   * 客观的说，C++基本上只支持源码级的库依赖。如果是依赖pre-compiled的库，会有很多ABI的问题。
   * 自动下载依赖模块的源码，编译依赖模块。然后在自动加载依赖到某一个target
* Per-Target的设置
   * 每一个Target都可能依赖不同的东西，有不同的Header include dir和不同的predefine
* 自由的可定制化
   * 每一个C++项目可能的编译流程都不同。或者有些自定义的代码检查等等。

## 目前C++编译工具链的现状

### CMake

除了最简单的编译，基本上啥都不支持，还是一个特别恶心的语法。但也基本上是目前C++项目的事实标准。

### Scons

和CMake类似级别的东西，但是胜在是标准的python脚本。所以，我们可以自定义这个东西。

### Bazel

非常优秀的编译框架。支持上面的大部分功能，但是自定义性上不太舒服。有强烈的google风格。如果代码组织和google style完全一样的话，还是很好用的。否则，自定义一些编译流程会比较麻烦。

### Typhoon-blade

腾讯的https://github.com/chen3feng/typhoon-blade ，应该是bazel开源之前的山寨版。看起来是最符合我们想要的框架，定制性也比较强。可是就是太小众了，所以没有采用。


## 为什么当时选CMake

其实技术上比cmake好用的东西有很多，也做过调研。而且我也倾向于最好的技术解决当前问题。不过，太小众的技术可能对推广不力，所以当时就没有采用其他技术。

**Comment by wangkuiyi** [comment]
After modifying some C++ code, I got the following error when I re-compile:

```
In file included from ../paddle/utils/ThreadLocal.h:24:0,
                 from ../paddle/math/Matrix.h:22,
                 from ../paddle/api/Matrix.h:20,
                 from api/PaddleAPI.h:24,
                 from Paddle_wrap.cxx:3573:
../paddle/utils/Util.h:31:30: fatal error: TrainerConfig.pb.h: No such file or directory
 #include "TrainerConfig.pb.h"
                              ^
compilation terminated.
```

It seems like some targets should depend on the target that builds protobufs. But I cannot find the source target by `grep`-ing for `Paddle_wrap.cxx` in all CMakeLists.txt files.

How does CMakeLists.txt specify targets and dependent source files?

**Comment by wangkuiyi** [comment]
@reyoung @hedaoyuan 接着上次我们的讨论，我感觉我们需要一个能把targets之间依赖关系描述清晰的工具。别的考虑都在其次。

**Comment by reyoung** [comment]
> It seems like some targets should depend on the target that builds protobufs. But I cannot find the source target by grep-ing for Paddle_wrap.cxx in all CMakeLists.txt files.

这个是python的setup.py编译的。

**Comment by wangkuiyi** [comment]
@hedaoyuan 提醒需要验证一下，bazel可否确保生成的binary是**最小的**——只链接了依赖的libraries。

**Comment by wangkuiyi** [comment]
@reyoung 提醒bazel好像是可以在一个机群上编译的。intermediate files缓存在那个机群上。有望极大加速build。

**Comment by reyoung** [comment]
@wangkuiyi @hedaoyuan @gangliao 

尝试了一下bazel。 https://github.com/reyoung/bazel_playground

* 对于google官方的依赖，google一般会提供一个bazel的包，这样的第三方库很容易引入。例如protobuf
* 对于不是google的依赖，bazel需要手写一个编译这个依赖的bazel文件。例如 [glog](https://github.com/reyoung/bazel_playground/blob/master/third_party/glog.BUILD)

## 对于Paddle使用Bazel的一些问题

Paddle有一些非常重的依赖，例如python解释器本身，或者numpy，cblas等等。如果我们要切换到bazel编译paddle的话，需要使用bazel的语法，给各个编译依赖写一个编译脚本。而这个编译脚本应该还要处理这些第三方库的性质。。比如python解释器，应该有非常多的编译选项。

**Comment by wangkuiyi** [comment]
@reyoung 因为Tensorflow用的是Python，我估计这些问题应该可以在Tensorflow的BUILD和.bzl文件里找到现成的答案吧。

**Comment by wangkuiyi** [comment]
# 试验：Bazel 可以生成 fully statically linked binaries

基于这个[C++ tutorial](https://www.bazel.io/versions/master/docs/tutorial/cpp.html)，我在其中的`cc_binary` rule里增加了一行 `linkopts =...`，如下：

```
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = [
        ":hello-time",
        "//lib:hello-greet",
    ],
    linkopts = ["-static", "-static-libgcc", "-static-libstdc++"],
)
```

则 `bazel build main:hello-world` 产生的 binary 就是 fully statically linked binary 了：

```
[root@065fb78bd2d2 /learn-bazel]$ ldd bazel-bin/main/hello-world
	not a dynamic executable
```

这个实现是在 Bazel Docker container 做的。用的image是 https://hub.docker.com/r/chin33z/bazel/ 。其中编译器是 4.9.2：

```
[root@fa67127db7a4 ~]$ gcc --version
gcc (Debian 4.9.2-10) 4.9.2
```

**Comment by wangkuiyi** [comment]
According to this [issue](https://github.com/woboq/woboq_codebrowser/issues/48), Bazel doesn't work well with woboq code browser,  which we used to generated browsable C++ source code in our [Dockerfile](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L40).

**Comment by reyoung** [comment]
> 因为Tensorflow用的是Python，我估计这些问题应该可以在Tensorflow的BUILD和.bzl文件里找到现成的答案吧。

Tensorflow是一个python的library(Python Call tensorflow)，而Paddle内嵌了一个Python的解释器(Paddle Call Python)。这两个是不同的。

不过，似乎如果我们将paddle变成一个python的库的话，这问题就可以不解决了。

> Bazel 可以生成 fully statically linked binaries

另外补充一点。默认，bazel对于除去libgcc和libstdc++之外的其他库是纯静态的。

**Comment by reyoung** [comment]
Closed with a new issue #792
