### ISSUE TITLE
Improve distributed training with LARS

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#6811]
From latest meeting with Intel team:

https://arxiv.org/abs/1708.03888

**Comment by helinwang** [comment]
Should this be part of https://github.com/PaddlePaddle/Paddle/projects/30 ?, it seems a improvement rather than core feature.

**Comment by Yancey1989** [comment]
Sure, it's just an improvement, and we can defer this improvement for later(after 201802).
