### ISSUE TITLE
能不能出一个WIN10 或者WIN7 64位下的编译教程

### ISSUE THREAD

**Issue by sandycs** [PaddlePaddle/Paddle#6812]
CMAKE以后用VS2015编译
错误一大堆，改都改不完

如果可以的话，分享一个编译好的DLL或者LIB文件也可以

**Comment by Xreki** [comment]
您好，感谢您给Paddle的关注。
如文档http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/index_cn.html 上面所述，Paddle目前支持的系统是**CentOS 6以上, Ubuntu 14.04以及MacOS 10.12**，还不支持Windows上面的编译。
