### ISSUE TITLE
Exception thrown when running image-classificaiton demo with no modification

### ISSUE THREAD

**Issue by prognew** [PaddlePaddle/Paddle#682]
$ sh train.sh  # cpu=1, nordma=1, trainer=100

Stack trace as follows:

I1130 18:11:30.913192 20859 GradientMachine.cpp:112] Saving parameters to ./cifar_vgg_model/pass-00001
I1130 18:11:30.942971 20859 Util.cpp:230] copy vgg_16_cifar.py to ./cifar_vgg_model/pass-00001
.........
I1130 18:15:06.323289 20859 TrainerInternal.cpp:165]  Batch=100 samples=12800 AvgCost=2.3082 CurrentCost=2.3082 Eval: classification_error_evaluator=0.895781  CurrentEval: classification_error_evaluator=0.895781
.........
I1130 18:18:04.653513 20859 TrainerInternal.cpp:165]  Batch=200 samples=25600 AvgCost=2.30641 CurrentCost=2.30461 Eval: classification_error_evaluator=0.897266  CurrentEval: classification_error_evaluator=0.89875
.........
I1130 18:21:02.300884 20859 TrainerInternal.cpp:165]  Batch=300 samples=38400 AvgCost=2.2999 CurrentCost=2.28689 Eval: classification_error_evaluator=0.890938  CurrentEval: classification_error_evaluator=0.878281
.........I1130 18:23:43.368007 20859 TrainerInternal.cpp:182]  Pass=2 Batch=391 samples=50000 AvgCost=2.29892 Eval: classification_error_evaluator=0.890213
I1130 18:24:21.205286 20859 Tester.cpp:127]  Test samples=10000 cost=16.9838 Eval: classification_error_evaluator=0.856549
I1130 18:24:21.205492 20859 GradientMachine.cpp:112] Saving parameters to ./cifar_vgg_model/pass-00002
I1130 18:24:21.238078 20859 Util.cpp:230] copy vgg_16_cifar.py to ./cifar_vgg_model/pass-00002
.........
I1130 18:27:56.790280 20859 TrainerInternal.cpp:165]  Batch=100 samples=12800 AvgCost=2.30803 CurrentCost=2.30803 Eval: classification_error_evaluator=0.900547  CurrentEval: classification_error_evaluator=0.900547
.........
I1130 18:30:54.439805 20859 TrainerInternal.cpp:165]  Batch=200 samples=25600 AvgCost=2.30457 CurrentCost=2.30111 Eval: classification_error_evaluator=0.897305  CurrentEval: classification_error_evaluator=0.894062
.........
I1130 18:33:53.913244 20859 TrainerInternal.cpp:165]  Batch=300 samples=38400 AvgCost=2.30102 CurrentCost=2.2939 Eval: classification_error_evaluator=0.894401  CurrentEval: classification_error_evaluator=0.888594
.Thread [140352166532864] Forwarding __batch_norm_1__, __conv_1__, __batch_norm_0__, __conv_0__, image,
*** Aborted at 1480502060 (unix time) try "date -d @1480502060" if you are using GNU date ***

PC: @           0x74bd7c paddle::BaseMatrixT<>::applyUnary<>()

*** SIGFPE (@0x74bd7c) received by PID 20859 (TID 0x7fa649079700) from PID 7650684; stack trace: ***

    @     0x7fa710fdb160 (unknown)

    @           0x74bd7c paddle::BaseMatrixT<>::applyUnary<>()

    @           0x74c193 paddle::BaseMatrixT<>::square()

    @           0x5f0ec2 paddle::BatchNormalizationLayer::calMeanAndStd()

    @           0x5f25f3 paddle::BatchNormalizationLayer::forward()

    @           0x6d5884 paddle::NeuralNetwork::forward()

    @           0x6cbcc6 paddle::TrainerThread::forward()

    @           0x6ccdec paddle::TrainerThread::computeThread()

    @     0x7fa7107558a0 execute_native_thread_routine

    @     0x7fa710fd31c3 start_thread

    @     0x7fa70fec612d __clone

../bin/paddle_local: line 109: 20859 Floating point exception(core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by reyoung** [comment]
@qingqing01 Should we add this to [FAQ](https://github.com/PaddlePaddle/Paddle/blob/develop/doc_cn/faq/index.rst) documentation?

**Comment by prognew** [comment]
@reyoung what's the fix?

**Comment by Yancey1989** [comment]
I'll close this issue, if it has not been fixed, please reopen it.
