### ISSUE TITLE
Neural Machine Translation Models on Fluid.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6821]
In NLP field, Neural Machine Translation (NMT for short) is one of the most important tasks to evaluate how near our models and techniques approach the ultimate goal: understanding natural language. Besides, NMT models are always among the most complicated models in the NLP field. They require a deep learning framework should be both highly flexibile and computation efficient. 

Making popular NMT models being well supported help us to speed up the process that our framework is capable of solving practical problems.

Here, I first list some candidate models advised by our partners. At the very beginning, we should make sure our design has a native support for these models. (Later, I will create a project to manage all the functional requirements.)

1. [The RNN search model](https://arxiv.org/abs/1409.0473). This is a baseline model that MUST be well supported.
1. [ConvS2S](https://arxiv.org/abs/1705.03122) . This is also a very popular and basic model that is expected to be well supported. The key point of this model is through highly parallel computing to speed up the training process.
    - https://github.com/facebookresearch/fairseq 
1. [Transformer](https://arxiv.org/abs/1706.03762)
    - Our design should support the Transformer model naturally and easily.
    - https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/models/transformer.py

Other models, we should think about:
1. [Minimum Risk Training for Neural Machine Translation](http://www.aclweb.org/anthology/P16-1159)
    - Decoding during training helps to improve the performance of NMT. We should think about this.
1. [Dual learning for NMT](https://papers.nips.cc/paper/6469-dual-learning-for-machine-translation.pdf)
    - This model is time-consuming, but we'd better think about its training process.

About decoding:
- Think about [Lexically Constrained Decoding for Sequence Generation Using Grid Beam Search](https://arxiv.org/abs/1704.07138) besides the standard beam search.

---
Finally, I hope to summarize up:
- The top priority gives to RNN search model and ConvS2S.
- Guarantee our design can support the Transformer.

**Comment by lcy-seso** [comment]
Hi, @kavyasrinet @abhinavarora suggested by our partners, we can give our top priority to the Transformer model, because the Transformer model requires the framework much more than RNN search and ConvS2S. The RNN search is already a widely used model if we just implement this one, it is not good enough due to that there will be no "delta".

P.S： This does not mean we do not need to support RNN search and ConvS2S. Just a suggestion we can begin from this. I will give a clear TODO list later. Thank you all.

**Comment by kavyasrinet** [comment]
Thanks so much for the update. That sounds good. Let's wait for the TODO list then.

**Comment by lcy-seso** [comment]
I close this PR first. We can find it in the project. If there is any problem, we can reop this issue or create a new one.
