### ISSUE TITLE
外部引用paddleocr的logger打印两次

### ISSUE THREAD

**Issue by cwmore** [PaddlePaddle/Paddle#68250]
### bug描述 Describe the Bug

如下代码，按理说只是打印一次，但引入后会打印两次，
```
import paddleocr.ppocr.utils.logging as utilLogging
logger = utilLogging.get_logger()
logger.info("test!")
```
![image](https://github.com/user-attachments/assets/8875bdfd-bc49-48e2-91f7-ed5549edf310)
因为我想拿到paddleocr的logger做动态设置。使用 from paddleocr.ppocr.utils.logging import get_logger 去引入的方式也不对，看了代码，最后发现 logger_initialized 这个全局变量在import后不一致。按逻辑，应该是初始化后有了就直接返回。import时会被ppocr/utils/predict_rec.py等文件初始化默认的'ppocr'这个logger,但是当第三方一引入后，logger_initialized又变为空了。 
（之前其它人有说使用logreset方案绕过，但感觉就是bug。当然在get_logger的时候传不同的名字可以规避这个问题，但还是获取不到默认初始化的那个logger）

本人真不确定该怎么改，希望社区给点建议。

### 其他补充信息 Additional Supplementary Information

搜了相关类似问题都没有好的处理方案：
https://github.com/PaddlePaddle/PaddleOCR/pull/5743
https://github.com/PaddlePaddle/Paddle/issues/57165
https://gitee.com/paddlepaddle/PaddleOCR/issues/IAQDZC

**Comment by cwmore** [comment]
提交问题错误，应该提到PaddleOCR那边，故关闭
https://github.com/PaddlePaddle/PaddleOCR/issues/13876

**Comment by liym27** [comment]
您好，感谢反馈，这边复现下问题，具体稍后回复您。
