### ISSUE TITLE
paddle.multinomial()函数严重的cpu内存泄漏

### ISSUE THREAD

**Issue by chenghaoDong666** [PaddlePaddle/Paddle#68282]
### bug描述 Describe the Bug

![image](https://github.com/user-attachments/assets/c3376c24-da67-4bdc-88c2-b3eab8d5a0e3)
上图是一段blip2实现的itm构建负样本的代码，训练过程过程中存在严重的cpu内存泄漏问题，自己已经debug完毕，已确定是将挑选出来的负样本添加到列表时出现内存泄漏（保真可复现），但是我理解的是这个列表最后应该自动释放掉，不应该内存泄漏，怀疑paddle框架有问题

### 其他补充信息 Additional Supplementary Information

python 3.7 paddlepaddle版本paddlepaddle_gpu-2.4.0.post112-cp37-cp37m-linux_x86_64

**Comment by chenghaoDong666** [comment]
![image](https://github.com/user-attachments/assets/b1639bb5-c422-46a8-bf22-f2096e91d882)
看错了 应该是paddle.multinomial的问题
![image](https://github.com/user-attachments/assets/4f9bcdb5-2178-4c6e-9ac8-6beb604dbdee)

**Comment by chenghaoDong666** [comment]
![image](https://github.com/user-attachments/assets/60505603-c875-4574-8af2-e54b4b0b0001)
模型cpu内存溢出后报错

**Comment by yuanlehome** [comment]
2.4版本能复现，2.6版本无此问题，升级2.6版本后再次验证下～

**Comment by chenghaoDong666** [comment]
确认为paddle版本问题，更新到2.6.1版本问题解决
