### ISSUE TITLE
CPU 分布式训练 支持CountFilterEntry吗？

### ISSUE THREAD

**Issue by welsonzhang** [PaddlePaddle/Paddle#68324]
### 请提出你的问题 Please ask your question

一般来说sparse准入会有基于出现频次做特征准入的，但是看SparseAccessor的C++代码，没看到相关逻辑，这个CountFilterEntry具体是怎么使用的？

**Comment by danleifeng** [comment]
一般在save load和shrink阶段会有过滤

**Comment by welsonzhang** [comment]
ok, 所以这里只能依赖示例给出的show和click，进行特征准入了。
