### ISSUE TITLE
Refine CopyFrom interface

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#6833]
The current `CopyFrom` interface looks like this

https://github.com/PaddlePaddle/Paddle/blob/b28b2f172b2763dd8917833c2708309f98299a0a/paddle/framework/tensor_util.h#L31-L32

Since all device_context are globally accessible after https://github.com/PaddlePaddle/Paddle/pull/6537, we are able to refine the API to
```
inline void CopyFrom(const Tensor& src, Tensor* dst, const platform::Place& dst_place)
```

**Comment by gongweibao** [comment]
Maybe there will be multiple `devicecontext` on a `place` later

**Comment by dzhwinter** [comment]
This already done in https://github.com/PaddlePaddle/Paddle/pull/6954

**Comment by tonyyang-svail** [comment]
@dzhwinter `CopyFrom` in https://github.com/PaddlePaddle/Paddle/pull/6954 only supports CPU <-> CPU.

**Comment by tonyyang-svail** [comment]
A wrapper has been added at https://github.com/PaddlePaddle/Paddle/pull/7293/files#diff-790932c13606faa477566f3bb1d3cfe8.
