### ISSUE TITLE
Many warnings when compiling doc.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6835]
Many warnings when generating documentation like this:
```text
/home/caoying/paddle_codes/paddle_github/doc/api/v2/fluid/layers.rst:108: WARNING: Title underline too short.

linear_chain_crf
---------
/home/caoying/paddle_codes/paddle_github/doc/api/v2/fluid/layers.rst:108: WARNING: Title underline too short.

linear_chain_crf
```

**Comment by luotao1** [comment]
Can we ignore these warnings by setting sphinx?

**Comment by luotao1** [comment]
I survey the warning related option in Sphinx. There are some methods:
- use `-Q`:  Do not output anything on standard output, also suppress warnings. 安静模式，不再输出任何warning. http://www.sphinx-doc.org/en/stable/invocation.html
- use `-W`: Turn warnings into errors. This means that the build stops at the first warning and sphinx-build exits with exit status 1. 出现warning即报错 http://www.sphinx-doc.org/en/stable/invocation.html
- use `keep_warnings = True`: keep warnings as “system message” paragraphs in the built documents.
编译时会输出warning，且所有warning会在网上反应. http://www.sphinx-doc.org/en/stable/config.html
  - False，(our develop branch)
![image](https://user-images.githubusercontent.com/6836917/34295306-963df3a2-e747-11e7-8680-b4ea336a3360.png)
   - True (my branch)
![image](https://user-images.githubusercontent.com/6836917/34295323-af9b8c60-e747-11e7-8f20-169cea17c9d4.png)

- advantages：it is convenient for us to quickly optimize the document
- disadvantages: as there are a lot of formatting problems,  it will affect the reading for a period of time.

@lcy-seso @pkuyym @kavyasrinet @abhinavarora How do you think about it ?

**Comment by lcy-seso** [comment]
I prefer to fixing the error ourselves and ignore the warnings. I am afraid if the warnings are exposed to users, it hurts the user experience.
