### ISSUE TITLE
Example for paddle.v2.fluid.layers.embedding maybe not right.

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#6837]
It seems that `size` should be the shape of `w`, but not be the size of output. @abhinavarora 

https://github.com/PaddlePaddle/Paddle/blob/1a3d4b0d3d037aed9cd2999bbedfcbcd7a98c58c/python/paddle/v2/fluid/layers/nn.py#L118-L139

**Comment by abhinavarora** [comment]
You are right. Thank you for pointing that out.

**Comment by chengduoZH** [comment]
@abhinavarora 
The example also need be changed.
https://github.com/PaddlePaddle/Paddle/blob/1a3d4b0d3d037aed9cd2999bbedfcbcd7a98c58c/python/paddle/v2/fluid/layers/nn.py#L130-L133
