### ISSUE TITLE
新数据接口训练问题

### ISSUE THREAD

**Issue by shouwangzhe** [PaddlePaddle/Paddle#684]
做mnist训练时，使用新的数据接口：
from paddle.trainer_config_helpers import *define_py_data_sources2(
    train_list='train.list',
    test_list=None,
    module='mnist_provider',
    obj='process')img = data_layer(name='pixel', size=784)label = data_layer(name='label', size=10)
出现mnist_provider模块存在，请问怎样使用新数据接口做mnist训练

**Comment by luotao1** [comment]
见https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/mnist_provider.py

**Comment by shouwangzhe** [comment]
通过下载https://github.com/PaddlePaddle/Paddle/blob/develop/demo/mnist/mnist_provider.py里面的mnist_provider.py放到thirdparty里面，并在提交任务时加载thirdparty解决了这个问题，但是提交任务后遇到了新问题：
Python Error: <type 'exceptions.KeyError'> : 'input'
Python Callstack: 
            /home/disk1/normandy/maybach/13428/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/PyDataProvider2.py : 349
Cannot Create instance

**Comment by backyes** [comment]
@shouwangzhe 

请确保你集群后端的版本与demo版本兼容。 最新的内部集群workspace目录提供了Paddle_version文件记录了后端paddle的git log SHA1，请比对确保你使用了一致的版本，否则会出一些模型配置api不兼容的问题。 详细参见内部平台文档。

**Comment by shouwangzhe** [comment]
@backyes 我看到workspace的version了，demo的version怎么看？

**Comment by backyes** [comment]
@shouwangzhe 

直接根据集群workspace版本的SHA1， checkout响应的版本，即可。

**Comment by backyes** [comment]
无响应很长时间，close
