### ISSUE TITLE
paddlepaddle是否可以做场景内容预测，有没有这种相关的数据集

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6848]
* 有这样的问题，就是把一张图片里的大体含义预测出来
* 比如一张图片有个女生在吃饭，可以把这个预测出来

**Comment by lcy-seso** [comment]
这个是Image Caption，可以做。没有现成的例子。

**Comment by yeyupiaoling** [comment]
原来叫`Image Caption`,我百度了一下,感觉这个东西好难啊!

**Comment by lcy-seso** [comment]
是一个模型会相对复杂的任务。

**Comment by yeyupiaoling** [comment]
最近要弄毕设的题目,都不知道弄什么好,刚想到`Image Caption`,结果他太难了.你有什么好的建议吗,基于paddlepaddle的
