### ISSUE TITLE
Build from source with error

### ISSUE THREAD

**Issue by prognew** [PaddlePaddle/Paddle#685]
Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_math.cc.o
Building CXX object paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_avx_functions.cc.o
[  3%] [  4%] Scanning dependencies of target gen_proto_cpp
Scanning dependencies of target gen_proto_py
Generating DataConfig.pb.h, DataConfig.pb.cc
Generating TrainerConfig.pb.h, TrainerConfig.pb.cc
[  4%] [  4%] ParameterConfig.proto:59:20: Expected field name.
ModelConfig.proto: Import "ParameterConfig.proto" was not found or had errors.
ModelConfig.proto:515:12: "ParameterConfig" is not defined.
TrainerConfig.proto: Import "ModelConfig.proto" was not found or had errors.
TrainerConfig.proto:134:12: "ModelConfig" is not defined.
Generating DataConfig.pb.h, DataConfig.pb.cc
Generating .../idl/paddle/Paddle/paddle/python/paddle/proto/TrainerConfig_pb2.py
make[2]: *** [proto/TrainerConfig.pb.h] Error 1
make[1]: *** [proto/CMakeFiles/paddle_proto.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  4%] [  4%] ParameterConfig.proto:59:20: Expected field name.

`[  4%] [  4%] ParameterConfig.proto:59:20: Expected field name.`

**Comment by luotao1** [comment]
ParameterConfig.proto:59这行对应的代码贴出来看看

**Comment by prognew** [comment]
optional string format = 15 [default = ""];
?? this one?

**Comment by prognew** [comment]
optional string format = 15 [default = ""];

**Comment by backyes** [comment]
@prognew 

请排查是否你cmake的目录未知不对。 一般， 
```
cd Paddle && mkdir build && cd build && cmake ../ 
 ````

**Comment by backyes** [comment]
@prognew What's the progress?  If resloved, close this issue. Thanks a lot.
