### ISSUE TITLE
Cannot install paddlepaddle-gpu 2.4.2 on GPU: Quadro P2000

### ISSUE THREAD

**Issue by NguyenDucQuan12** [PaddlePaddle/Paddle#68570]
### 问题描述 Issue Description

when i run:
```
 python -m pip install paddlepaddle-gpu==2.4.2.post117 -f https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.html
```
it return:
```
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Looking in links: https://www.paddlepaddle.org.cn/whl/windows/mkl/avx/stable.htm
ERROR: Could not find a version that satisfies the requirement paddlepaddle-gpu==2.4.2.post117 (from versions: 2.6.0, 2.6.1, 2.6.2)
ERROR: No matching distribution found for paddlepaddle-gpu==2.4.2.post117
```
i use: GPU: P2000  
CUDA: 11.7  
cudnn: 8.9.7  
![image](https://github.com/user-attachments/assets/dbe184ab-9041-4854-a44c-552837cf83a7)
![image](https://github.com/user-attachments/assets/577aa768-1e12-4b48-8195-ae7fa98ca4c8)

### 版本&环境信息 Version & Environment Information

Python: 3.12.4

**Comment by NguyenDucQuan12** [comment]
I want to use paddlepaddle-gpu2.4.2 because I use paddleocr gpu and ultralytics gpu, it's make error:
```
ImportError: generic_type: type "_gpuDeviceProperties" is already registered!
```

**Comment by htcd-subham** [comment]
Hey @NguyenDucQuan12 how was the issue solved?

**Comment by NguyenDucQuan12** [comment]
@htcd-subham it's for python 3.10, not for 3.12
