### ISSUE TITLE
Paddle OP别名注册的文件是不是换位置了，现在在哪？

### ISSUE THREAD

**Issue by HarperCy** [PaddlePaddle/Paddle#68592]
### 请提出你的问题 Please ask your question

如题。一般情况下算子都是按照自己注册时候的名字注册的，但是也有的算子注册了别名，我记得以前有个cpp文件专门用来注册，现在这个文件找不着了，请教一下现在的别名注册是怎么弄的？

**Comment by gongshaotian** [comment]
paddle/fluid/ir_adaptor/translator/op_compat_info.cc 这个是您想找的吗

**Comment by HarperCy** [comment]
是的，我这边已经找到了，是op_compat.yaml
