### ISSUE TITLE
paddle3.0b安装好后单机无法多GPU

### ISSUE THREAD

**Issue by ccl-private** [PaddlePaddle/Paddle#68638]
### 问题描述 Issue Description

 通过这个命令安装的python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
安装好后发现虚拟环境里面已经自动安装了cuda、cudnn、nccl等动态链接库
执行检验GPU，我有两张A800,发现只能使用一张
import paddle
paddle.is_compiled_with_cuda()
paddle.utils.run_check()

报错信息：
PaddlePaddle is installed successfully ONLY for single GPU! Let's start deep learning with PaddlePaddle now.

### 版本&环境信息 Version & Environment Information

paddle版本3.0b

**Comment by mayun123** [comment]
我也是这样，请问哥们你这边解决了吗

**Comment by DesmonDay** [comment]
如果是2.x的Paddle版本，可以正常安装吗？如果2.x的版本也不可以正常安装，说明本身环境存在问题。

**Comment by risemeup1** [comment]
稍等，这边已经收到这个问题，我们本地复现下

**Comment by risemeup1** [comment]
![dceb5cbc6cd24a779025f4779fb59c07](https://github.com/user-attachments/assets/b561180b-7712-4666-afd8-64a80c73e49f)
我们这里可以啊，应该是你环境的问题

**Comment by ccl-private** [comment]
我的python是3.11的，环境我是新创建的虚拟环境，用python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/安装的，我看paddle3.0b会自动安装cuda的whl包，所以我本地没有安装任何cuda,只安装了显卡驱动。

**Comment by ccl-private** [comment]
@DesmonDay 2.x的版本需要手动安装cuda,我以前用过2.5的，那时候python、cuda、cudnn都严格按照官网说明是可以的

**Comment by ccl-private** [comment]
@risemeup1 你好，python3.11可以吗，你的python是什么版本

**Comment by tianshuo78520a** [comment]
![image](https://github.com/user-attachments/assets/3f75c8c3-5914-4ae3-baff-5dd5f0c7dab5)
我在python3.10上测试，没有问题

**Comment by ccl-private** [comment]
@tianshuo78520a 你host机有没有安装过nccl

**Comment by tianshuo78520a** [comment]
没有安装过，只有在安装paddle时候，自动安装nccl

**Comment by ccl-private** [comment]
@tianshuo78520a 我是ubuntu20，源码编译了个python3.10之后 ，新建虚拟环境，python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/
依旧只能单卡。

**Comment by tianshuo78520a** [comment]
可以发下nvidia-smi截图么，再echo $CUDA_VISIBLE_DEVICES 和env看下环境变量

我觉得可以尝试下：
1. 查看机器是否有装nccl，可能和pip 安装的冲突了?
2. 可以跑个 https://github.com/NVIDIA/cuda-samples 测试下，多卡是否正常（排除paddle问题）。

**Comment by ccl-private** [comment]
我本地只安装过显卡驱动，没有cuda、nccl，环境都是虚拟环境python -m pip install paddlepaddle-gpu==3.0.0b1 -i https://www.paddlepaddle.org.cn/packages/stable/cu123/安装的，刚刚试了cu11.8也一样的问题
![Screenshot from 2024-11-01 16-30-52](https://github.com/user-attachments/assets/f6cd2006-bc20-4b89-828e-c8904b43f777)

**Comment by ccl-private** [comment]
![Screenshot from 2024-11-01 16-36-28](https://github.com/user-attachments/assets/f93e60d5-902d-43db-96bd-1c798d55efe7)
echo $CUDA_VISIBLE_DEVICES 为空

**Comment by ccl-private** [comment]
刚刚export 了CUDA_VISIBLE_DEVICES也一样
![Screenshot from 2024-11-01 16-42-50](https://github.com/user-attachments/assets/227eea1a-147f-4f1d-ae65-8bb0eff0da21)

**Comment by ccl-private** [comment]
机器的卡本身是没有问题的，pytorch的多卡是正常的，也是用的虚拟环境venv

**Comment by tianshuo78520a** [comment]
不要写到main.py，直接python起动，import paddle 再run_check()呢

**Comment by ccl-private** [comment]
果然，直接python启动两张卡都成功了
![Screenshot from 2024-11-01 16-57-49](https://github.com/user-attachments/assets/a3185985-55ec-4b05-aef8-e7636b89548d)
写main.py里面不行，这是什么原理

**Comment by tianshuo78520a** [comment]
可能是我们这块写的不太好，可以把run_check()写到if __name__ == '__main__':
可以看下这个文档：https://juejin.cn/post/7053808358695895071

**Comment by ccl-private** [comment]
ok，感谢回答～多卡问题总算是搞定了
Let's start deep learning with PaddlePaddle now.
