### ISSUE TITLE
Balance the parameter shards of on multiple parameter server

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#6864]
Refer:
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/refactor/parameter_server.md#challenges

**Comment by helinwang** [comment]
Is this a core feature that need to be done by 2018/02/01? If not maybe we can add a column of "future" in the project https://github.com/PaddlePaddle/Paddle/projects/30 and put it there.

**Comment by typhoonzero** [comment]
Can we close this, I think it's already implemented.

**Comment by Yancey1989** [comment]
I'll close it since we have already implemented this feature.
