### ISSUE TITLE
paddle V1 集群运行sparse_float_vector失败

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#6865]
V1版本地版本支持sparse_float_vector
但是集群报Python Error: <type 'exceptions.NameError'> : global name 'sparse_float_vector' is not defined错误....
任务提交的receiver:connect to receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:9392
失败的任务job:1293056.nmg01-model-training-smart-001.nmg01.baidu.com

如果去掉数据中的sparse_float_vector，提交的任务虽然因为数据问题coredump但是没有参数定义错误
642096.nmg01-hpc-off.dmop.baidu.com

**Comment by ChunweiYan** [comment]
那就是集群版本比本地版本旧，不支持 sparse_float_vector
