### ISSUE TITLE
paddle test预测结果正确，paddle predictor单测结果错误

### ISSUE THREAD

**Issue by Yipeng-Sun** [PaddlePaddle/Paddle#6866]

**Comment by Yipeng-Sun** [comment]
paddle-v1训练spatial attention模型, paddle test结果正确，基于paddle predictor的单测结果有误，与paddle test结果不一致。

**Comment by Yipeng-Sun** [comment]
过程描述：从paddle test到使用paddle predictor进行预测开发，需要基于trainer_conf.py生成binary_conf文件，然后使用paddle predictor单测程序进行预测。

**Comment by luotao1** [comment]
请详细描述如何复现问题。

**Comment by Yipeng-Sun** [comment]
相关流程及过程涉及icode代码，方便线下沟通，可提供源码进行check。

**Comment by Yipeng-Sun** [comment]
目前问题做了进一步定位排查，采用现有的conv-bi gru-1d attention的英文模型进行转换，预测结果是对的，但是conv + spatial attention-RNN decode的模型转换，预测结果有误。

**Comment by ChunweiYan** [comment]
这个问题你能看出来么 @Xreki  或者我拉别人

**Comment by Xreki** [comment]
我看不出来，issue中提供的信息太少了。

**Comment by ChunweiYan** [comment]
补充一些信息进来吧 @Yipeng-Sun

**Comment by Yipeng-Sun** [comment]
目前该模型涉及内部线上系统，train_conf等信息已经同步给你们了

**Comment by Yipeng-Sun** [comment]
paddle-predict预测代码forward部分有bug, 未考虑到兼容性问题，通过修改paddle-predict版本layer代码，实现预测库结果与paddle-test输出结果完全一致。
