### ISSUE TITLE
单机执行情感分析的demo出错，之前用mpi跑ok

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#6868]
$ python query_dnn_single.py 
I1222 11:32:54.626684 23753 Util.cpp:166] commandline:  --use_gpu=False 
load dictionary...
I1222 11:32:54.637953 23753 GradientMachine.cpp:94] Initing parameters..
I1222 11:32:54.647127 23753 GradientMachine.cpp:101] Init parameters done.
I1222 11:32:54.647704 23753 ParameterClient2.cpp:113] pserver 0 127.0.0.1:20134
W1222 11:32:54.648000 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:32:55.648346 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:32:56.648589 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:32:57.648828 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:32:58.649035 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:32:59.649250 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:33:00.649497 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
W1222 11:33:01.649745 23753 LightNetwork.cpp:397] connection refused by pserver, try again!
F1222 11:33:01.649802 23753 LightNetwork.cpp:399] connection refused by pserver, maybe pserver failed!
*** Check failure stack trace: ***
    @     0x7ff3756c1d2d  google::LogMessage::Fail()
    @     0x7ff3756c57dc  google::LogMessage::SendToLog()
    @     0x7ff3756c1853  google::LogMessage::Flush()
    @     0x7ff3756c6cee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7ff37552d37f  paddle::SocketClient::TcpClient()
    @     0x7ff37552d521  paddle::SocketClient::SocketClient()
    @     0x7ff3772492e7  paddle::ParameterClient2::init()
    @     0x7ff376da8c4d  paddle::RemoteParameterUpdater::init()
    @     0x7ff3756a1cba  ParameterUpdater::init()
    @     0x7ff37531ca3b  _wrap_ParameterUpdater_init
    @     0x7ff39b73cbad  PyEval_EvalFrameEx
    @     0x7ff39b73dc3e  PyEval_EvalCodeEx
    @     0x7ff39b73d1f7  PyEval_EvalFrameEx
    @     0x7ff39b73dc3e  PyEval_EvalCodeEx
    @     0x7ff39b73d1f7  PyEval_EvalFrameEx
    @     0x7ff39b73dc3e  PyEval_EvalCodeEx
    @     0x7ff39b73d1f7  PyEval_EvalFrameEx
    @     0x7ff39b73dc3e  PyEval_EvalCodeEx
    @     0x7ff39b73dd52  PyEval_EvalCode
    @     0x7ff39b75e450  PyRun_FileExFlags
    @     0x7ff39b75e62f  PyRun_SimpleFileExFlags
    @     0x7ff39b773fd4  Py_Main
    @       0x318ae1ecdd  (unknown)
    @           0x400729  (unknown)
Aborted

**Comment by ChunweiYan** [comment]
模型配置里有集群的设置吗？ 写在文件开头的，可以贴出来，把具体集群的信息删掉

**Comment by ChunweiYan** [comment]
这个是单机启动了集群环境，没有启动pserver.
