### ISSUE TITLE
sequence_tagging demo:  layer 写法问题

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#687]
inputs(word, pos, chunk, features)
outputs(crf)
其中datalayer ： features，没有和任何layer 相连，相当于直接连接到 output layer ？

**Comment by luotao1** [comment]
features是crf_input的输入，crf_input是crf的输入

**Comment by VamWolf** [comment]
crf_input = mixed_layer(
    size=num_label_types,
    bias_attr=False,
    input=[ 
        full_matrix_projection(hidden2),
    ] + ([  
        full_matrix_projection(rnn2, param_attr=ParamAttr(initial_std=0))
    ] if with_rnn else []),
)
没有啊？

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/demo/sequence_tagging/linear_crf.py 请更新版本

**Comment by luotao1** [comment]
由于rnn_crf.py和linear_crf.py共用一个dataprovider.py，因此两者的data_layer是一样的。在rnn_crf.py中，虽然features没有用，但如果不加上，就要重新写一个dataprovider了。
