### ISSUE TITLE
paddle_inference V3.0Beta GPU版本预编译库无法下载

### ISSUE THREAD

**Issue by Shawn-Tao** [PaddlePaddle/Paddle#68703]
### bug描述 Describe the Bug

![image](https://github.com/user-attachments/assets/3cc8696f-4cd3-43ed-a9fa-403179416080)
3.0beta版本页面，c++推理库 GPU版本无法下载，点击后显示
NoSuchKey

**Comment by yuanlehome** [comment]
您好，可以先从这里下载 https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release/v3.0/docs-official/guides/install/download_lib.md ，官网url修复预计明天生效～

**Comment by Shawn-Tao** [comment]
感谢&nbsp;


桃
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Yuanle ***@***.***&gt;; 
发送时间: 2024年10月15日(星期二) 下午3:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] paddle_inference V3.0Beta GPU版本预编译库无法下载 (Issue #68703)














 
您好，可以先从这里下载 https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/release/v3.0/docs-official/guides/install/download_lib.md ，官网url修复预计明天生效～
