### ISSUE TITLE
test_randperm_op在部分GPU上会fail

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/Paddle#68700]
### bug描述 Describe the Bug

[test_randperm_op.py](https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_randperm_op.py#L230-L243)中的测试方法有问题，在固定随机种子的条件下，它assert在任何GPU上都会得到完全固定的随机序列。
curand在不同GPU上生成完全相同的随机数的一个前提是block/thread的config要完全相同，但实际randperm kernel中是通过phi::backends::gpu::GetGpuLaunchConfig1D来获取config，实测在A100, H100等GPU上config都是一致的，但在部分GPU，比如A16上并不一致。因为A16的sm数量特别小，phi::backends::gpu::GetGpuLaunchConfig1D会给它分配更大的threads_per_block，也就导致生成的随机数不一致。

建议是修改UT的逻辑，或者在randperm kernel中将block/thread config写死，保持一致，不要用phi::backends::gpu::GetGpuLaunchConfig1D来获取。

**Comment by zhwesky2010** [comment]
这个去修改kernel的逻辑去写死GpuLaunch配置可能也并不合理，这个可以固定GPU的类型来做这个**固定数值测试**，像 `paddle.rand`、`paddle.randn` 都是这么测试的：

https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_uniform_random_op.py#L672-L673

https://github.com/PaddlePaddle/Paddle/blob/develop/test/legacy_test/test_gaussian_random_op.py#L457-L459

加这几行就好
