### ISSUE TITLE
算子属性问题

### ISSUE THREAD

**Issue by jhxiang** [PaddlePaddle/Paddle#68711]
### 请提出你的问题 Please ask your question

paddlepaddle版本：3.0.0-beta1
目前我在做paddle到tvm的适配工作，我想请问下，在3.0版本中算子属性名是被替换了吗，我没有找到相关的文档
```
type_list = ["int32", "int64", "fp32", "fp64", "bool"]
for i in type_list:
    value = op.attr("%s_values" % i)
    if value:
        source = value
        break
```
报错如下：
```
RuntimeError: (NotFound) Attribute int32_values is not found.
```
如果被替换了，相应的变量名是什么呢？

**Comment by zyfncg** [comment]
这里的替换流程是什么样的呢？

**Comment by jhxiang** [comment]
大概逻辑是这样的：
这个错误发生在paddle框架到tvm框架的set_value函数中，这里应该是需要取value值，这里的op是自定义的一个类，最后的报错信息是在类方法的这句代码：
![4f8a8d83c62d8aadd77eb9add5801d5b](https://github.com/user-attachments/assets/0966ddac-c9b7-4457-87d8-30388871aad2)
按提示信息的关联文件是Paddle/paddle/fluid/framework/op_desc.cc
![cc11b6753506d95973d43ee6deed6750](https://github.com/user-attachments/assets/b52e362f-370e-44e0-8d29-738f08e807b0)

**Comment by zyfncg** [comment]
paddle从3.0开始静态图IR将切换到pir(参考：[PIR 基本概念和开发](https://www.paddlepaddle.org.cn/documentation/docs/zh/guides/paddle_v3_features/paddle_ir_cn.html))，op_desc的这套IR表示后续会逐步废弃掉，适配TVM的话还要继续用op_decs吗？

**Comment by zyfncg** [comment]
https://github.com/PaddlePaddle/Paddle/commit/dd2a749ae94acbb934b5851dfb081363dbbc3b80#diff-c9e26189ea21e415b94cfd6caacc1d112dcf7b10f1605962db16831703a47552R136
`int32_values`在这个PR中替换为了`values `

**Comment by jhxiang** [comment]
明白了，感谢，现阶段应该还是采用op_decs。如果要更换为pir，有什么适配建议吗？

**Comment by zyfncg** [comment]
1. op参数以及属性的获取接口估计需要统一更换
2. pir和op_decs的大部分算子定义还是一致的，少量会有调整，更换到pir的话主要是这些op的映射实现可能需要变一下

**Comment by jhxiang** [comment]
非常感谢！
