### ISSUE TITLE
Cluster train on GPU at Baidu , paddle_pserver2 exited with SIGSEGV when starting.

### ISSUE THREAD

**Issue by xdsoul** [PaddlePaddle/Paddle#6872]
GPU集群模式，采用单机2卡进行测试。显示pserver启动时core，未进入真正的training，因为没有调用
dataprovider的init hook function。
部分日志如下，详细请帮忙加hi联系。

=============================================

+ ./paddle_pserver2 --num_gradient_servers=1 --nics=eth2 --port=7164 --ports_num=8 --rdma_tcp=tcp --comment=paddle_cluster_job 
*** Aborted at 1513913615 (unix time) try "date -d @1513913615" if you are using GNU date *** 
PC: @ 0x0 (unknown) 
*** SIGSEGV (@0x1170) received by PID 13236 (TID 0x7f973a6f4700) from PID 4464; stack trace: *** 
@ 0x7f97443ea160 (unknown) 
@ 0x7f974209f74f (unknown) 
@ 0x7f97421f8ee4 (unknown) 
@ 0x7f9742192588 (unknown) 
@ 0x7f97443e21c3 start_thread 
@ 0x7f97430cd12d __clone 
@ 0x0 (unknown) 
./start_server.sh: line 33: 13236 Segmentation fault GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_pserver2 --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --nics=${nics} ${server_arg} --rdma_tcp=${rdma_tcp} --comment=$comment 
+ check_return 'paddle_pserver2 failed' 
+ '[' 139 -ne 0 ']' 
+ echo '[./start_server.sh : 34] [main]' 
[./start_server.sh : 34] [main] 
+ echo '[FATAL]: paddle_pserver2 failed' 
[FATAL]: paddle_pserver2 failed 
+ get_stack 
+ set +x 

*********************Shell Script Stack Trace******************** 
@: [./log.sh: 61] check_return 
@: [./start_server.sh: 34] main 

+ exit 1 

Primary job terminated normally, but 1 process returned 
a non-zero exit code.. Per user-direction, the job has been aborted. 

mpirun detected that one or more processes exited with non-zero status, thus causing 
the job to be terminated. The first process to do so was: 

Process name: [[58121,1],0] 
Exit code: 1

**Comment by ChunweiYan** [comment]
看不出啥问题，可以帮看看么 @typhoonzero 


paddle 命令：

```
commandline: ./paddle_trainer --num_gradient_servers=1 --trainer_id=0 --pservers=xxx --rdma_tcp=tcp --nics=eth2 --port=7164 --ports_num=8 --dot_period=50 --show_parameter_stats_period=50 --log_period=50 --trainer_count=4 --num_passes=8 --saving_period=4 --local=1 --config=conf/trainer_config.conf --save_dir=./output --use_gpu=1 
```

pserver命令：

```
commandline: ./paddle_pserver2 --num_gradient_servers=1 --nics=eth2 --port=7164 --ports_num=8 --rdma_tcp=tcp --comment=paddle_cluster_job 
```

**Comment by typhoonzero** [comment]
@xdsoul 请hi发我下job链接，或在issue中补充关键报错信息(workspace/log/train.log等)。需要更多信息判断出错原因。

**Comment by xdsoul** [comment]
没有其它明显的报错信息，jo链接已Hi你。

**Comment by typhoonzero** [comment]
看日志，可能是二进制和节点对应运行环境存在不匹配的问题。最好能有相同的环境测试运行成功后再提交集群。

另外，这个job启动时指定了`--local=1`所以其实是单机在跑，`--trainer_count=4`是4个卡。

**Comment by xdsoul** [comment]
看日志，可能是二进制和节点对应运行环境存在不匹配的问题。最好能有相同的环境测试运行成功后再提交集群。
------------------------------------
comment

**Comment by xdsoul** [comment]
1，看日志，可能是二进制和节点对应运行环境存在不匹配的问题。最好能有相同的环境测试运行成功后再提交集群。
二进制和环境都是有idl同学提供（接口人yanxu05），维护一个和集群一致的测试环境是不是有些成本
2，另外，这个job启动时指定了--local=1所以其实是单机在跑，--trainer_count=4是4个卡。
这个也不太清楚为何会指定Local=1，但预期是一个节点跑。可能是在idl同学提供的提交脚本中设置num_nodes=1，然后自动设置local模式？

**Comment by xdsoul** [comment]
初步结论：相同配置在其它节点上可正常启动并训练，在同一节点会复现出core，应该是节点问题。
更深入结论待更新。
