### ISSUE TITLE
编译paddle源码报错python版本不匹配

### ISSUE THREAD

**Issue by Serenagirl** [PaddlePaddle/Paddle#68822]
### 问题描述 Issue Description

执行官方文档第8个步骤时报错：
![image](https://github.com/user-attachments/assets/a285f396-0df6-4105-ae3a-b1fced8a7e7a)

### 版本&环境信息 Version & Environment Information

https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/arm-compile.html#beizhu

**Comment by Serenagirl** [comment]
arm鲲鹏服务器麒麟v10操作系统

**Comment by Serenagirl** [comment]
命令中要指定python版本，如cmake .. -DPY_VERSION=3.8.12 -DPYTHON_EXECUTABLE=`which python3` -DWITH_ARM=ON -DWITH_TESTING=OFF -DCMAKE_BUILD_TYPE=Release -DON_INFER=ON -DWITH_XBYAK=OFF

**Comment by Serenagirl** [comment]
还是报错，是不是路径哪里有问题：
![image](https://github.com/user-attachments/assets/bf19f603-8bc7-44ae-b92b-d358d70c6174)

**Comment by FeixLiu** [comment]
我联系下负责编译的同学帮忙看下。稍等

**Comment by tianshuo78520a** [comment]
报错显示你的python环境找不到，你看下你的python路径

**Comment by Serenagirl** [comment]
已解决
