### ISSUE TITLE
OCR版面识别

### ISSUE THREAD

**Issue by whwususu** [PaddlePaddle/Paddle#68886]
### 请提出你的问题 Please ask your question

请问下，版面分析模型的训练方法我看了半天不得其解，都是提供了各种数据集进行训练，而不是自定义训练集。那么有不有例如通过打标的方式，生成自己的训练集，然后进行训练的。
这个是我看的教程。https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/ppstructure/layout/README_ch.md
谢谢！

**Comment by ronny1996** [comment]
你好，如果是自定义数据集，可以使用dataloader，dataset相关api https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/DataLoader_cn.html
https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/io/Dataset_cn.html

可以参考模型提供的数据集格式，自己构建

**Comment by whwususu** [comment]
MemoryError:

C++ Traceback (most recent call last):
0 paddle::pybind::eager_api_conv2d(_object*, _object*, _object*)
1 conv2d_ad_func(paddle::Tensor const&, paddle::Tensor const&, std::vector<int, std::allocator >, std::vector<int, std::allocator >, std::string, std::vector<int, std::allocator >, int, std::string)
2 paddle::experimental::conv2d(paddle::Tensor const&, paddle::Tensor const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::string const&, std::vector<int, std::allocator > const&, int, std::string const&)
3 void phi::ConvCudnnKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::string const&, std::vector<int, std::allocator > const&, int, std::string const&, phi::DenseTensor*)
4 void phi::ConvCudnnKernelImplV7<float, phi::GPUContext>(phi::DenseTensor const*, phi::DenseTensor const*, phi::GPUContext const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, std::vector<int, std::allocator > const&, phi::backends::gpu::DataLayout, phi::backends::gpu::DataLayout, bool, bool, int, phi::DenseTensor*)
5 phi::DnnWorkspaceHandle::ReallocWorkspace(unsigned long)
6 paddle::memory::allocation::Allocator::Allocate(unsigned long)
7 paddle::memory::allocation::StatAllocator::AllocateImpl(unsigned long)
8 paddle::memory::allocation::Allocator::Allocate(unsigned long)
9 paddle::memory::allocation::Allocator::Allocate(unsigned long)
10 paddle::memory::allocation::Allocator::Allocate(unsigned long)
11 paddle::memory::allocation::Allocator::Allocate(unsigned long)
12 paddle::memory::allocation::CUDAAllocator::AllocateImpl(unsigned long)
13 std::string phi::enforce::GetCompleteTraceBackString<std::string >(std::string&&, char const*, int)
14 common::enforce::GetCurrentTraceBackString[abi:cxx11](https://github.com/PaddlePaddle/PaddleX/issues/bool)

Error Message Summary:

麻烦您看下，我换成了3090显卡，还是不行，有不有参数调下参数，让他训练下去。谢谢！

**Comment by ronny1996** [comment]
有错误日志吗？是不是显存不够了，可以调小batchsize试试

**Comment by whwususu** [comment]
![mmexport1729840894078](https://github.com/user-attachments/assets/2bea5377-bcf0-4676-b18f-d5f7e2674d87)
> 有错误日志吗？是不是显存不够了，可以调小batchsize试试

调整batchsize到1了，还是不行，然后调整了epochs_iters参数到10，可以了。我拿样例数据在原有的模型基础上训练，完成以后，发现训练前还没训练后的识别类型多，难道没有继承前模型的能力？
![mmexport1729840901230](https://github.com/user-attachments/assets/708b0911-c48d-4243-a82f-f19be51aa527)
第一个是训练前的，第二个是训练后的。是不是有什么参数需要设置？

**Comment by ronny1996** [comment]
是finetune吗？是不是没有加载好pertained权重

**Comment by whwususu** [comment]
![image](https://github.com/user-attachments/assets/05fe6c2e-08ea-47ce-9662-600dd453427e)
我用的是这个命令，参数只把批量提交和迭代次数调整了一下，这会是什么原因导致的，训练完成后，标签只有我自己新增的。
