### ISSUE TITLE
利用Jetson部署时报错module 'paddlex' has no attribute 'deploy'

### ISSUE THREAD

**Issue by Xiaorong-Zh** [PaddlePaddle/Paddle#68891]
用Jetson AGX orin做部署时报错module 'paddlex' has no attribute 'deploy'，是不是paddlex3.0中去除了deploy函数，应该怎么解决呢？

**Comment by FrostML** [comment]
可以在 [PaddleX](https://github.com/PaddlePaddle/PaddleX) 咨询下
