### ISSUE TITLE
稀疏更新方式，训练出错

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#689]
paddle1103版本，使用sparse_update加速，train.log报错

16[1,29]<stderr>:TypeError: __init__() got an unexpected keyword argument 'sparse_remote_update'
Thu Dec  1 11:54:24 2016[1,29]<stderr>:Traceback (most recent call last):
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "<string>", line 2, in <module>
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "trainer/config_parser.py", line 3036, in parse_config_and_serialize
Thu Dec  1 11:54:24 2016[1,29]<stderr>:    
Thu Dec  1 11:54:24 2016[1,29]<stderr>:config = parse_config(config_file, config_arg_str)
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "trainer/config_parser.py", line 3012, in parse_config
Thu Dec  1 11:54:24 2016[1,29]<stderr>:    
Thu Dec  1 11:54:24 2016[1,29]<stderr>:execfile(config_file, make_config_environment(config_file, config_args))
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "conf/trainer_config.conf", line 51, in <module>
Thu Dec  1 11:54:24 2016[1,29]<stderr>:    
Thu Dec  1 11:54:24 2016[1,29]<stderr>:Layer(inputs = [Input("input1", parameter_name = "_layer1_1.w")], name = "layer1_1", bias = Bias(parameter_name = "_layer1_1.bias"), active_type = "tanh", type = "fc", size = 40, drop_rate = 0.5, sparse_remote_update = True)
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "trainer/config_parser.py", line 2736, in Layer
Thu Dec  1 11:54:24 2016[1,29]<stderr>:    
Thu Dec  1 11:54:24 2016[1,29]<stderr>:layer_func(name, **xargs)
Thu Dec  1 11:54:24 2016[1,29]<stderr>:  File "trainer/config_parser.py", line 1430, in __init__
Thu Dec  1 11:54:24 2016[1,29]<stderr>:    
Thu Dec  1 11:54:24 2016[1,29]<stderr>:super(FCLayer, self).__init__(name, 'fc', size, inputs=inputs, **xargs)
Thu Dec  1 11:54:24 2016[1,29]<stderr>:TypeError
Thu Dec  1 11:54:24 2016[1,29]<stderr>:: 
Thu Dec  1 11:54:24 2016[1,29]<stderr>:__init__() got an unexpected keyword argument 'sparse_remote_update'
Thu Dec  1 11:54:24 2016[1,29]<stderr>:

**Comment by backyes** [comment]
@PseudoProgrammer 
请重新提问，注意体温方法。

**Comment by backyes** [comment]
@PseudoProgrammer 
请重新提问，确保问题能被精确理解。

**Comment by PseudoProgrammer** [comment]
@backyes 已更新

**Comment by reyoung** [comment]
版本太老了。之前Sparse设置机制和现在的不一样。请更新版本。

**Comment by backyes** [comment]
@PseudoProgrammer 是不是使用了新版本的模型api，跑在老的二进制程序上？

**Comment by PseudoProgrammer** [comment]
@backyes 没用新版本的api哈，全套都是用的paddle1103，bash submit.sh cpu提交方式
