### ISSUE TITLE
FatalError: `Erroneous arithmetic operation` is detected by the operating system.

### ISSUE THREAD

**Issue by zzk2021** [PaddlePaddle/Paddle#68908]
### bug描述 Describe the Bug

在一个代码里同时load两个模型报错，在第二个模型出错，具体问题不明
--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::pybind::eager_api_warpctc(_object*, _object*, _object*)
1   warpctc_ad_func(paddle::Tensor const&, paddle::Tensor const&, paddle::optional<paddle::Tensor> const&, paddle::optional<paddle::Tensor> const&, int, bool)
2   paddle::experimental::warpctc_intermediate(paddle::Tensor const&, paddle::Tensor const&, paddle::optional<paddle::Tensor> const&, paddle::optional<paddle::Tensor> const&, int, bool)
3   void phi::WarpctcKernel<float, phi::GPUContext>(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor const&, paddle::optional<phi::DenseTensor> const&, paddle::optional<phi::DenseTensor> const&,int, bool, phi::DenseTensor*, phi::DenseTensor*)
4   phi::funcs::UnpaddingLoDTensorFunctor<phi::GPUContext, int>::operator()(phi::GPUContext const&, phi::DenseTensor const&, phi::DenseTensor*, int, int, bool, phi::funcs::PadLayout)

----------------------
Error Message Summary:
----------------------
FatalError: `Erroneous arithmetic operation` is detected by the operating system.
  [TimeInfo: *** Aborted at 1729683441 (unix time) try "date -d @1729683441" if you are using GNU date ***]
  [SignalInfo: *** SIGFPE (@0x7f4ff2f20d64) received by PID 53505 (TID 0x7f508a559740) from PID 18446744073490533732 ***]

**Comment by FrostML** [comment]
看着是Warpctc报错，@nemonameless @zxcd 辛苦看看CTC问题

**Comment by zzk2021** [comment]
ctc相关报错吗？我检查了一下，是输入格式不对
