### ISSUE TITLE
Convert configuration file to protobuf binary error

### ISSUE THREAD

**Issue by flame12334** [PaddlePaddle/Paddle#6890]
We want to use C-API for Model Inference. Firstly, convert configuration file to protobuf binary, then use the C-API in my program, but the size of the NeuralNetwork's dataLayers is always 0.

**Comment by flame12334** [comment]
版本用的是当前develop分支, 重现方式可以用capi/multi_thread下面的demo，将binary文件换成我的conf文件对应的binary文件即可，不是很清楚conf文件的写法是不是哪里不符合规范

**Comment by lcy-seso** [comment]
请先参考这个文档再检查一下吧，应该是序列化配置的步骤出错。https://github.com/PaddlePaddle/Paddle/pull/6596

**Comment by flame12334** [comment]
文档看过了，过程也是这样用的，感觉是序列化的问题，就是不知道问题在哪

**Comment by flame12334** [comment]
随便发一个文档让参考的就请不要回复了

**Comment by lcy-seso** [comment]
好的。不再回复了。

**Comment by luotao1** [comment]
> 将binary文件换成我的conf文件对应的binary文件即可，不是很清楚conf文件的写法是不是哪里不符合规范。感觉是序列化的问题，就是不知道问题在哪

不贴conf文件的，除了发文档请参考，我们也不知道问题在哪。
