### ISSUE TITLE
book.05 recommendation systems use gpu happen Matrix.cpp:653] Not supported

### ISSUE THREAD

**Issue by mical892524** [PaddlePaddle/Paddle#6894]
CentOS Linux release 7.3.1611 (Core)
cuda-9.0

exec https://github.com/PaddlePaddle/book/blob/develop/05.recommender_system/train.py with gpu

```text
paddle.init(use_gpu=True, gpu_id=0)

output

I1222 10:26:48.378365   221 Util.cpp:166] commandline:  --use_gpu=True --gpu_id=0 
I1222 10:26:53.883152   221 GradientMachine.cpp:94] Initing parameters..
I1222 10:26:53.919482   221 GradientMachine.cpp:101] Init parameters done.
F1222 10:26:54.034803   221 Matrix.cpp:653] Not supported
*** Check failure stack trace: ***
    @     0x7f7c2a52f81d  google::LogMessage::Fail()
    @     0x7f7c2a531b68  google::LogMessage::SendToLog()
    @     0x7f7c2a52f32b  google::LogMessage::Flush()
    @     0x7f7c2a532a3e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f7c2a2f1eb8  paddle::GpuMatrix::mul()
    @     0x7f7c2a110dec  paddle::FullyConnectedLayer::forward()
    @     0x7f7c2a1ce04f  paddle::NeuralNetwork::forward()
    @     0x7f7c2a4ff370  GradientMachine::forwardBackward()
    @     0x7f7c29fb5d04  _wrap_GradientMachine_forwardBackward
    @           0x4cb755  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca7df  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4ca088  PyEval_EvalFrameEx
    @           0x4c9d7f  PyEval_EvalFrameEx
    @           0x4c2705  PyEval_EvalCodeEx
    @           0x4c24a9  PyEval_EvalCode
    @           0x4f19ef  (unknown)
    @           0x4ec372  PyRun_FileExFlags
    @           0x4eaaf1  PyRun_SimpleFileExFlags
    @           0x49e208  Py_Main
    @     0x7f7c93558830  __libc_start_main
    @           0x49da59  _start
    @              (nil)  (unknown)
Aborted (core dumped)


paddle version: 
root@c256ce8c415f:/work/05.recommender_system# paddle version
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: ON
    with_mkl: ON
    with_mkldnn: ON
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```

**Comment by lcy-seso** [comment]
v2 API中，目前矩阵乘法两个输入矩阵必须是都是dense的。这个例子中有稀疏矩阵乘以稠密矩阵的运算，这一步目前只能在CPU下面做，如果一定要使用GPU可以将输入变为稠密矩阵。

**Comment by mical892524** [comment]
安装上面的变为稠密矩阵，出现下面 的错误：

I1225 06:39:27.096025  1446 Util.cpp:166] commandline:  --use_gpu=True 
I1225 06:39:32.159993  1446 GradientMachine.cpp:94] Initing parameters..
I1225 06:39:32.197667  1446 GradientMachine.cpp:101] Init parameters done.
Traceback (most recent call last):
  File "train_gpu.py", line 135, in <module>
    main()
  File "train_gpu.py", line 113, in main
    num_passes=1)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/trainer.py", line 169, in train
    in_args = feeder(data_batch)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 282, in __call__
    return self.convert(dat, argument)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/data_feeder.py", line 133, in convert
    return DataProviderConverter.convert(self, reorder_data(dat), argument)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 267, in convert
    scanner.pre_scan(each_step)
  File "/usr/local/lib/python2.7/dist-packages/py_paddle/dataprovider_converter.py", line 119, in pre_scan
    "The data size must be equal to it in data layer.")
ValueError: The data size must be equal to it in data layer.

**Comment by typhoonzero** [comment]
Close due to low activity, feel free to reopen.

**Comment by xiaolv3366** [comment]
这个问题怎么解决？
ValueError: The data size must be equal to it in data layer.

**Comment by xiaolv3366** [comment]
@typhoonzero 问题还没解决呢！
出现以下错误：
ValueError: The data size must be equal to it in data layer.

**Comment by typhoonzero** [comment]
@xiaolv3366 建议检查下输入数据是否和data layer配置是保持一致的，可以在reader里print数据检查下。
