### ISSUE TITLE
Implement and test encoder-decoder without attention.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#6899]
Before we move to a more complicated mode for NMT task, we can implement the most basic RNN encoder-decoder without attention model and verify its convergence.

**Comment by pkuyym** [comment]
Related to https://github.com/dzhwinter/benchmark/issues/22

**Comment by lcy-seso** [comment]
This has been merged into the code base: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_rnn_encoder_decoder.py
