### ISSUE TITLE
About Paddle document theme

### ISSUE THREAD

**Issue by Shi-Liang** [PaddlePaddle/Paddle#690]
Hi all,
I am coding a new paddle document theme. So I wonder whether to create a new repository or just add a new folder which contains the theme files on paddle's main repository.
@reyoung @luotao1

**Comment by luotao1** [comment]
直接在develop分支上加一个新的文件夹吧。

**Comment by backyes** [comment]
@Shi-Liang Any more Questions？ Otherwise close this issue if necessary， :-)
