### ISSUE TITLE
The documentation of kubernetes distributed training is out of date

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#6909]
Documentations under http://www.paddlepaddle.org/docs/develop/documentation/en/howto/usage/cluster/k8s_en.html is out of date, we have more simple methods to submit using some sample yaml files.

**Comment by yyydido** [comment]
@typhoonzero where are these simple methods?

**Comment by Yancey1989** [comment]
Related issue #7032
