### ISSUE TITLE
PreconditionNotMetError found in paddle.utils.run_check()

### ISSUE THREAD

**Issue by Ao-Lee** [PaddlePaddle/Paddle#69102]
### 问题描述 Issue Description

the paddle.utils.run_check() returns with the following error:
```
PreconditionNotMetError: The third-party dynamic library (cublas64_118.dll;cublas64_11.dll) that Paddle depends on is not configured correctly. (error code is 126)
      Suggestions:
      1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
      2. Configure third-party dynamic library environment variables as follows:
      - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
      - Windows: set PATH by `set PATH=XXX; (at ..\paddle\phi\backends\dynload\dynamic_loader.cc:312)
      [operator < matmul_v2 > error]
```

when I copied all the dll files from  C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin to C:\Windows\System32, the paddle.utils.run_check() returns successfully, which implies I got the right cuda & cudnn version but paddle didn't find those dll files.

I would like to ask only one question: is there any way to make the paddle work without moving all the dll files to C:\Windows\System32? Thanks in advance.

Here is my system environment setting (some values in 'Path' is ommited):
```
CUDA_PATH: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
CUDA_PATH_V11_8: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8
Path: C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA; C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0\bin; C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.0
```

### 版本&环境信息 Version & Environment Information

here is my environment setting:
OS: windows10
driver version: 565.9
cuda version: 11.8
cudnn bin files are copied to C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin, cudnn 'include' and 'lib' folder were also copied to the corresponding folder.
paddle-gpu package was installed with the folloing command:
`python -m pip install paddlepaddle-gpu==2.6.2 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/`

**Comment by xuxinyi389** [comment]
windows 版本Paddle，自从2.6会自动安装cuda、cudnn等依赖的库，从而避免对本地cuda环境的依赖。从你当前的情况看，应是下载依赖包的时候出现了问题，导致继续在本地加载dll。你可以选择将，C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin 添加到你的 PATH 环境变量，即可解决问题。

**Comment by Ao-Lee** [comment]
将C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin 添加到PATH 环境变量后，问题已经解决，非常感谢

**Comment by Ao-Lee** [comment]
将C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\bin 添加到PATH 环境变量后，问题已经解决，非常感谢
