### ISSUE TITLE
Paddle3.0beta2 导出 onnx 模型出错

### ISSUE THREAD

**Issue by DarkenStar** [PaddlePaddle/Paddle#69128]
### bug描述 Describe the Bug

Paddle3.0beta2 导出 onnx 出错，mylinear.onnx是一个空文件什么也没有
```bash
2024-11-02 02:18:15 [INFO]      Static PaddlePaddle model saved in paddle_model_temp_dir.
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: paddle_model_temp_dir/model.pdmodel
[Paddle2ONNX] Parameters file path: paddle_model_temp_dir/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Failed to read model file: paddle_model_temp_dir/model.pdmodel, please make sure your model file or file path is valid.
[Paddle2ONNX] Failed to load program of PaddlePaddle model.
[Paddle2ONNX] Paddle model parsing failed.
[Paddle2ONNX] Paddle model convert failed.
2024-11-02 02:18:15 [INFO]      ONNX model saved in mylinear.onnx.
```
代码如下，paddle版本为3.0beta2，paddle2onnx版本为1.2.11，代码来源于[export的API文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/onnx/export_cn.html)
```python
from typing import Any
import paddle

class LinearNet(paddle.nn.Layer):
    def __init__(self) -> None:
        super().__init__()    
        self.linear = paddle.nn.Linear(128, 10)
        
    def forward(self, x) -> Any:
        return self.linear(x)
    
# Export model with 'InputSpec' to support dynamic input shape.
def export_linear_net():
    model = LinearNet()
    x_spec = paddle.static.InputSpec(shape=[None, 128], dtype='float32')
    paddle.onnx.export(model, "mylinear", input_spec=[x_spec])
    
export_linear_net()
```

**Comment by luguoyixiazi** [comment]
这个版本模型训练生成pdmodel文件的部分有问题，但是如果你有pdiparams的话可以先下载对应official_models的pdmodel，反正模型架构不变，指定pdiparams和pdmodel就能正常导出，但是有些设置改不了，可能会有影响

**Comment by DarkenStar** [comment]
> 这个版本模型训练生成pdmodel文件的部分有问题，但是如果你有pd

明白了，我再试试，感谢回复

**Comment by luguoyixiazi** [comment]
我看了一下，paddle.jit的api里面save就没有保存pdmodel这块，导入了INFER_MODEL_SUFFIX = ".pdmodel"，但是构建完model_filename就结束了……写漏了？

**Comment by DarkenStar** [comment]
我看[export](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/onnx/export.py#L35)最后是调用了ygraph2onnx这个函数
```python
# python/paddle/onnx/export.py
    file_prefix = os.path.basename(path)
    if file_prefix == "":
        raise ValueError(
            "The input path MUST be format of dirname/file_prefix "
            "[dirname\\file_prefix in Windows system], but "
            f"the file_prefix is empty in received path: {path}"
        )
    save_file = path + '.onnx'

    p2o.dygraph2onnx(
        layer,
        save_file,
        input_spec=input_spec,
        opset_version=opset_version,
        **configs,
    )
```

**Comment by luguoyixiazi** [comment]
不是转换onnx的问题，而且模型本身在训练保存时没有保存pdmodel文件，而这个文件在转换和一般推理时是要用的，所以你可以指定转onnx的参数，捣鼓出pdmodel文件后自己设定model filename，如
```paddle2onnx --model_dir mobilenetv3 --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file model.onnx --enable_dev_version True --opset_version 13 --enable_onnx_checker True```

**Comment by DarkenStar** [comment]
懂了，我先尝试下在旧版本上训练导出.pdmodel，谢谢

**Comment by luguoyixiazi** [comment]
简单的方法就是直接从paddle下载你那个模型的推理模型，里面就有pdmodel，指定那个pdmodel能导出，但是不能自己修改对应参数

**Comment by DarkenStar** [comment]
哦哦 好的 我找一下

**Comment by SigureMo** [comment]
> paddle版本为3.0beta2

PaddlePaddle 3.0.0b2 默认为 PIR，因此 `jit.save` 导出后的文件为 `.json` 格式的 PIR 模型文件，不再是 `.pdmodel` 格式的老 IR 模型文件

如果需要继续使用老 IR 导出，可以尝试使用环境变量 `FLAGS_enable_pir_api=0` 来临时切回老 IR

目前 Paddle2ONNX 的 PIR 导出尚在开发中 https://github.com/PaddlePaddle/Paddle2ONNX/tree/test_pir

@risemeup1 看下，从 Paddle2ONNX 的用户角度来看，我们是否应该让用户无感，在任何版本下都能无缝导出，在 PIR 尚未完善的情况下，当前的老 IR 分支（develop）应该先在 `DygraphOldIrGuard` 下进行 `jit.save`，以免影响 3.0.0b2 的用户

解决完问题后最好尽快发个新版本

cc @Zheng-Bicheng

**Comment by SigureMo** [comment]
PaddlePaddle/Paddle2ONNX#1421 应可修复

**Comment by Zheng-Bicheng** [comment]
@SigureMo 同意观点，建议默认按旧IR导出，等PIR合入P2O以后再说
