### ISSUE TITLE
昇腾 NPU 报错：libatb.so: cannot open shared object file: No such file or directory 

### ISSUE THREAD

**Issue by flow3rdown** [PaddlePaddle/Paddle#69146]
### 问题描述 Issue Description

按照官网安装指南安装：
```bash
pip install paddlepaddle -i https://www.paddlepaddle.org.cn/packages/nightly/cpu/
pip install paddle-custom-npu -i https://www.paddlepaddle.org.cn/packages/nightly/npu/
```
安装后进行基础功能检查：
```bash
python -c "import paddle_custom_device; paddle_custom_device.npu.version()"
```
之后报错：
```
ValueError: (InvalidArgument) Fail to open library: /data/miniconda3/envs/env-3.9.16/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so with error: libatb.so: cannot open shared object file: No such file or directory
  [Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/init.cc:149)
```

### 版本&环境信息 Version & Environment Information

npu-smi info:

<img width="695" alt="image" src="https://github.com/user-attachments/assets/8122ce11-a45f-4aec-955b-7480fdc04b95">

**Comment by Bobholamovic** [comment]
你好，可以尝试参考这个issue中提到的方式：https://github.com/PaddlePaddle/Paddle/issues/65797

**Comment by flow3rdown** [comment]
> 你好，可以尝试参考这个issue中提到的方式：#65797

按照这个试过了，没有找到atb/set_env.sh

**Comment by xuanyuanminzheng** [comment]
用的是官方提供的docker吗？首先可以找一下/usr/local/Ascend 这个默认路径下是否有atb目录，或者是软链接到某个路径。如果有的话可以source目录下的set_env.sh；没有的话应该是这个环境缺少atb相关的包

**Comment by flow3rdown** [comment]
> 用的是官方提供的docker吗？首先可以找一下/usr/local/Ascend 这个默认路径下是否有atb目录，或者是软链接到某个路径。如果有的话可以source目录下的set_env.sh；没有的话应该是这个环境缺少atb相关的包

找了一下没有atb目录，请问要如何安装呀

**Comment by xuanyuanminzheng** [comment]
> > 用的是官方提供的docker吗？首先可以找一下/usr/local/Ascend 这个默认路径下是否有atb目录，或者是软链接到某个路径。如果有的话可以source目录下的set_env.sh；没有的话应该是这个环境缺少atb相关的包
> 
> 找了一下没有atb目录，请问要如何安装呀

百度提供的docker里理论上应该是有的，如果你用的是的话可以发一下具体的链接给我看看，我这边确认下，这个不应该是让用户再另外加装的，那样太麻烦了。
