### ISSUE TITLE
win10按照官网文档编译失败

### ISSUE THREAD

**Issue by bluesky4485** [PaddlePaddle/Paddle#69179]
### 问题描述 Issue Description

按照官方文档安装工具 cmake, git, python, Visual studio 2019，在cmake的时候报错，不管是编译cpu版本还是gpu版本，报错都一样的。

develop分支和2.6分支 均是同样的问题。

编译命令：cmake .. -GNinja -DWITH_GPU=OFF -DWITH_UNITY_BUILD=ON
编译的时候还遇到过`Paddle needs cudnn to compile`的错误，再将cudnn相关文件拷贝到cuda对应目录下后，问题解决了。但是最后的还遇到另外一个报错信息，找了好久的解决方案，均无法解决，报错内容如下：
```
Automatic code generation for paddle/fluid/primitive
Automatic code generation for paddle/fluid/primitive succeed.
Automatic code generation for decomp interface succeed.
-- Configuring done
CMake Error at cmake/generic.cmake:394 (add_dependencies):
  The dependency target "python" of target "py_func_op" does not exist.
Call Stack (most recent call first):
  paddle/fluid/operators/CMakeLists.txt:128 (cc_library)


CMake Error at cmake/generic.cmake:394 (add_dependencies):
  The dependency target "python" of target "libpaddle" does not exist.
Call Stack (most recent call first):
  paddle/fluid/pybind/CMakeLists.txt:681 (cc_library)


-- Generating done
CMake Generate step failed.  Build files cannot be regenerated correctly.
```

### 版本&环境信息 Version & Environment Information

****************************************
Paddle version: N/A
Paddle With CUDA: N/A

OS: Windows 10
GCC version: N/A
Clang version: N/A
CMake version: version 3.17.0
Libc version: N/A
Python version: 3.12.7

CUDA version: 12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0
cuDNN version: N/A
Nvidia driver version: 546.12
Nvidia driver List:
GPU 0: Tesla P100-PCIE-16GB

****************************************

 nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Wed_Nov_22_10:30:42_Pacific_Standard_Time_2023
Cuda compilation tools, release 12.3, V12.3.107
Build cuda_12.3.r12.3/compiler.33567101_0

nvidia-smi
Tue Nov  5 16:14:38 2024
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.12                 Driver Version: 546.12       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla P100-PCIE-16GB         TCC   | 00000000:0B:00.0 Off |                    0 |
| N/A   38C    P0              26W / 250W |      8MiB / 16384MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|  No running processes found                                                           |
+---------------------------------------------------------------------------------------+

**Comment by risemeup1** [comment]
源码编译的时候建议用我们的docker否则编译会遇到很多问题

**Comment by risemeup1** [comment]
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/compile/linux-compile-by-make.html 参考这个文档来吧

**Comment by bluesky4485** [comment]
> 源码编译的时候建议用我们的docker否则编译会遇到很多问题

就是说基本上不建议用windows去编译运行，不用docker最起码也用linux去编译比较合适是么？

**Comment by risemeup1** [comment]
> > 源码编译的时候建议用我们的docker否则编译会遇到很多问题
> 
> 就是说基本上不建议用windows去编译运行，不用docker最起码也用linux去编译比较合适是么？

看错了，这个是windows下的，我让windows负责人帮你看看

**Comment by xuxinyi389** [comment]
首先说明下报错原因：编译目标 “py_func_op” 找不到依赖 “python”，请检查下python是否成功安装，可以在cmd中输入 where python 或 python 进行检查；此外cuda12.3 的编译应该是存在一些问题的（nvidia官方cudafe++的bug导致的），建议下降到12.0。此外你说的cudnn的问题，本地安装的时候请确保PATH环境变量配置的正确性，cuda 和 cudnn 的环境协同配置可参考网上教程。

**Comment by Layer-norm** [comment]
因为编译创建了一个python的虚拟环境，这一行命令里的python其实指的是cache下的python_venv目录里的python，而在windows中这个目录里并不会包含python3.dll, libs等编译所需的文件，从全局的python目录下把缺的东西复制过来就好了

**Comment by Catchusha** [comment]
> 因为编译创建了一个python的虚拟环境，这一行命令里的python其实指的是cache下的python_venv目录里的python，而在windows中这个目录里并不会包含python3.dll, libs等编译所需的文件，从全局的python目录下把缺的东西复制过来就好了

请问你说的cache是指cmake构建时的吗，我这边没看到有python_venv这个目录呢

**Comment by Layer-norm** [comment]
> 请问你说的cache是指cmake构建时的吗，我这边没看到有python_venv这个目录呢

题主是因为当时参考的是ci/windows下的批处理文件，自己新建了一个虚拟环境才导致的问题。从而导致cmake/generic.cmake的Line391处`add_dependencies(${TARGET_NAME} python)`出错，因为此处的python指的是虚拟环境目录下的python。

其实如果想保证环境隔离，用conda这类的python环境就会避免这类问题。另外因为飞浆这个项目还涉及到一些算子的安装，conda环境也比原生的python好处理得多。

如果不是特别急着在Windows下用cuda13或者其他必须要自己编译的原因的话，还是建议用官方的安装包，这比自己编译要可靠得多。
