### ISSUE TITLE
paddle predict on spark

### ISSUE THREAD

**Issue by 5idaidai** [PaddlePaddle/Paddle#692]
在这里分享一下之前利用spark对大量数据进行paddle模型预测的经验，个人感觉实现方式比较粗暴，欢迎大家讨论，当然如果开发了新的paddle SDK可能就不用这种方式了，balabala……

1. 利用paddle c++ SDK编写一个预测类PaddleRecommended

![14791953490870](https://cloud.githubusercontent.com/assets/1777746/20790104/e8d70d0a-b7f1-11e6-898a-ba8db7ac14a1.jpg)

- init: 模型预测初始化
- predict: 模型预测

2. 利用swig编写paddle的python预测接口
```c++
%module paddle_recommended
%{
#include <sstream>
#include <map>
#include "paddle_recommended.h"
%}
%include "std_string.i"
%include "std_vector.i"
%include "std_map.i"

namespace recommended {

class PaddleRecommended {
public:
    bool init(const std::string& vocab_path, const std::string& model_path);
    float predict(const std::string& text);
};

}
```

3. 利用swig编译生成相应的动态链接库和py文件，将py文件打包成egg包，将so文件放到spark根路径，上传相关模型、词典即可在spark上调用相关接口进行预测。

4. demo地址：待写。。。

**Comment by backyes** [comment]
赞👍

**Comment by backyes** [comment]
@5idaidai  

欢迎分享自己一些经验。 目前paddle已经提供了基于swig构造的python 预测接口， http://www.paddlepaddle.org/doc/ui/predict/swig_py_paddle_en.html， 所以用户将这个预测功能挪到spark上也是非常容易的吧

**Comment by backyes** [comment]
有类似需求， https://github.com/PaddlePaddle/Paddle/issues/680

**Comment by 5idaidai** [comment]
@backyes 确实目前paddle已经提供了基于swig构造的python 预测接口，但是我使用时遇到的问题在于该接口太过臃肿，不够轻量级，首先来说就是依赖于numpy库，这就使得需要在spark集群上的python安装numpy包，这个当时没找到解决办法，不知道大家有什么好的解决方案？

**Comment by 5idaidai** [comment]
我的理解，用于生产的Predict越简洁越轻便越好，最后能0依赖，这样会使得各种环境下方便不少使用，我最开始是想直接将原始版本的SDK C++接口封装成swig 接口的，后来于老师说近期在开发新版SDK所以没做直接偷懒基于预测库写了个预测类在封装成swig接口，这样封装很简单但是不普适，换个模型就要重新开发c++的预测类然后再封装，所以感觉实现的很ugly.

**Comment by backyes** [comment]
https://github.com/PaddlePaddle/Paddle/issues/680

**Comment by backyes** [comment]
> 确实目前paddle已经提供了基于swig构造的python 预测接口，但是我使用时遇到的问题在于该接口太过臃肿，不够轻量级，首先来说就是依赖于numpy库，这就使得需要在spark集群上的python安装numpy包，这个当时没找到解决办法，不知道大家有什么好的解决方案？ 

可以试试 PYSPARK_PYTHON 这个环境变量。 控制一个进程默认使用的python解释器，主要途径一般都是： 
* 设置修改PYTHONHOME、PYTHONPATH、LD_LIBRARY_PATH 三个环境变量，即可。 

从pySpark的文档来看，也是可以修改默认python解释器的。 

关联issue：
https://github.com/PaddlePaddle/Paddle/issues/988 

我们也根据百度生产环境提供了一套predict on cluster的demos，其中包含pySpark的demo。  

由于间隔时间较长，此处暂时关闭issue
