### ISSUE TITLE
为什么一条视频训练会报错？

### ISSUE THREAD

**Issue by fanplanet** [PaddlePaddle/Paddle#69225]
### 文档链接&描述 Document Links & Description

https://www.paddlepaddle.org.cn/tutorials/projectdetail/3560260#anchor-8

### 请提出你的建议 Please give your suggestion

5.3.2 LSTM训练
通过如下命令训练AttentionLSTM网络。

cd /home/aistudio/PaddleVideo/applications/FootballAction/train_lstm/
python -u scenario_lib/train.py  \
    --model_name=ActionNet \
    --config=conf/conf.txt \
    --save_dir=../football_lstm

这里因为训练数据只提供了一条视频，直接进行LSTM训练会存在问题，如有需要可根据自己的数据集使用上述命令进行训练，并通过修改 conf/conf.txt 文件，更改模型参数。

报错：
WARNING: OMP_NUM_THREADS set to 6, not 1. The computation speed will not be optimized if you use data parallel. It will fail if this PaddlePaddle binary is compiled with OpenBlas since OpenBlas does not support multi-threads.
PLEASE USE OMP_NUM_THREADS WISELY.
lstm_img.shape (-1, 4096)
/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /root/autodl-tmp/PaddleVideo/applications/FootballAction/train_lstm/scenario_lib/action_net.py:217
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/math_op_patch.py:336: UserWarning: /root/autodl-tmp/PaddleVideo/applications/FootballAction/train_lstm/scenario_lib/action_net.py:232
The behavior of expression A + B has been unified with elementwise_add(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_add(X, Y, axis=0) instead of A + B. This transitional warning will be dropped in the future.
  warnings.warn(
/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py:744: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  elif dtype == np.bool:
lstm_img.shape (-1, 4096)
W1107 14:42:23.162943 43588 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 12.0, Runtime API Version: 11.2
W1107 14:42:23.168251 43588 device_context.cc:465] device: 0, cuDNN Version: 8.1.
config setting
train reader
INFO:LSTM:Resetting train metrics...
INFO:LSTM:Resetting valid metrics...
epoch is  20
INFO:LSTM:Resetting train metrics...
INFO:LSTM:[TRAIN] Epoch 0, iter 0 average:      Loss: 35.165428,        top1_acc: 62.50,        top5_acc: 87.50,   iou: 0.477900
INFO:LSTM:[TRAIN] Epoch 0, iter 2 data training failed: In user code:

    File "scenario_lib/train.py", line 300, in <module>
      train(args)
    File "scenario_lib/train.py", line 181, in train
      train_model.build_model()
    File "/root/autodl-tmp/PaddleVideo/applications/FootballAction/train_lstm/scenario_lib/action_net.py", line 200, in build_model
      lstm_pool_audio = fluid.layers.sequence_pool(input=scaled_audio, pool_type='sum')
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/sequence_lod.py", line 360, in sequence_pool
      helper.append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The first dimension of Input(X) must be large than batch size.But received first dimension of Input(X) is 5, while batchsize is 8.
      [Hint: Expected dims[0] >= static_cast<int64_t>(lod[lod_level - 1].size() - 1), but received dims[0]:5 < static_cast<int64_t>(lod[lod_level - 1].size() - 1):8.] (at /paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:56)
      [operator < sequence_pool > error]
INFO:LSTM:[TRAIN] Epoch 0, iter 3 data training failed: In user code:

    File "scenario_lib/train.py", line 300, in <module>
      train(args)
    File "scenario_lib/train.py", line 181, in train
      train_model.build_model()
    File "/root/autodl-tmp/PaddleVideo/applications/FootballAction/train_lstm/scenario_lib/action_net.py", line 200, in build_model
      lstm_pool_audio = fluid.layers.sequence_pool(input=scaled_audio, pool_type='sum')
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layers/sequence_lod.py", line 360, in sequence_pool
      helper.append_op(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: The first dimension of Input(X) must be large than batch size.But received first dimension of Input(X) is 3, while batchsize is 8.
      [Hint: Expected dims[0] >= static_cast<int64_t>(lod[lod_level - 1].size() - 1), but received dims[0]:3 < static_cast<int64_t>(lod[lod_level - 1].size() - 1):8.] (at /paddle/paddle/fluid/operators/sequence_ops/sequence_pool_op.h:56)
      [operator < sequence_pool > error]

**Comment by westfish** [comment]
报错显示，批量大小（batch size）大于输入数据的第一维度（样本数量），因为您的训练数据只有一个视频，导致在进行序列池化操作时，输入数据的大小不足以满足批量处理的要求。如果可能的话，确保数据集的样本数量大于或等于批量大小。
