### ISSUE TITLE
windows11安装paddlepaddle后报错ImportError: DLL load failed while importing libpaddle: 找不到指定的模块。

### ISSUE THREAD

**Issue by wydahai-afk** [PaddlePaddle/Paddle#69236]
### 问题描述 Issue Description

windows11安装paddlepaddle后报错ImportError: DLL load failed while importing libpaddle: 找不到指定的模块。
![image](https://github.com/user-attachments/assets/9a07189a-7ed2-4f20-a28b-013ca4072974)

### 版本&环境信息 Version & Environment Information

1、paddlepaddle版本2.6.1
python版本3.10.11
2、设备规格、系统规格
![image](https://github.com/user-attachments/assets/abf623e6-ce82-40b7-aa7f-0d525aecdc88)
![image](https://github.com/user-attachments/assets/3e62d8d1-6d9e-44d1-a3b6-39bb639995fd)

**Comment by JunnYu** [comment]
你好，可以先尝试使用一下3.0.0b2版本的paddle，https://www.paddlepaddle.org.cn/
```sh
 python -m pip install paddlepaddle-gpu==3.0.0b2 -i https://www.paddlepaddle.org.cn/packages/stable/cu118/
```
麻烦再提供一下你系统的显卡型号，nvidia-smi的driver版本信息？
此外，在windows环境下，推荐你可以使用anaconda安装paddlepaddle（可以解决大部分环境问题）
```sh
conda install paddlepaddle-gpu==3.0.0b2 paddlepaddle-cuda=11.8 -c paddle -c nvidia
```

**Comment by wydahai-afk** [comment]
1、用上述方式无法解决
![image](https://github.com/user-attachments/assets/bdc5894b-eeb3-458e-82da-dff01633518b)

**Comment by JunnYu** [comment]
@wydahai-afk 你可以先看一下系统有没有装CUDA，从上面的截图看，感觉你系统没有装CUDA，https://blog.csdn.net/YYDS_WV/article/details/137825313，
安装完成后，请使用下面的命令，检查是否安装成功
```python
import paddle
paddle.utils.run_check()
```
![image](https://github.com/user-attachments/assets/709a4b7c-7520-40e6-914a-c3c7701ee66d)

**Comment by JunnYu** [comment]
长时间没有回复，关闭issue

**Comment by wqw547243068** [comment]
遇到同样的问题，操作系统旧了，解法: 安装[vc_redist.x64](https://blog.csdn.net/fuck_hang/article/details/114578986)

**Comment by wqw547243068** [comment]
遇到同样的问题，操作系统旧了，解法: 安装[vc_redist.x64](https://blog.csdn.net/fuck_hang/article/details/114578986)

**Comment by 188080501** [comment]
同样的问题，Windows 10 LTSC 2021系统
安装VS运行库后问题解决

**Comment by Zdmai** [comment]
> 遇到同样的问题，操作系统旧了，解法: 安装[vc_redist.x64](https://blog.csdn.net/fuck_hang/article/details/114578986)

安装之后还是报错，import paddle都import不进去，win10
