### ISSUE TITLE
SOT Python3.13 单测支持情况

### ISSUE THREAD

**Issue by GoldenStain** [PaddlePaddle/Paddle#69246]
### 任务列表

|  序号  |  文件位置  |  认领人  |  PR  | 报错信息 | 初步分析 |
| :---: | :---: | :---: | :---: | :---: | :---: |
| ✅1 | test_01_basic.py | | | | |
| ✅2 | test_02_store_inplace.py | | | | |
| ✅3 | test_03_tuple.py | @SigureMo | #69431 | `Not support builtin function: __gt__ with args: Args(TupleVariable, TupleVariable)` | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅4 | test_04_list.py | @SigureMo | #69432 | `Not support builtin function: __gt__ with args: Args(ListVariable, ListVariable)` | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅5 | test_05_dict.py | | | | |
| ✅6 | test_06_call_function.py | @SigureMo | #69431 | | `CALL_KW` 不支持 |
| ✅7 | test_07_unpack.py | | | | |
| ✅8 | test_08_rot.py | | | | |
| ✅9 | test_09_f_string.py | @GoldenStain | #69346 | | `FORMAT_SIMPLE` 不支持 |
| ✅10 | test_10_build_unpack.py | | | | |
| ✅11 | test_11_jumps.py | @GoldenStain | #69700 | `op = dis.cmp_op[cmp_op_index] IndexError: tuple index out of range` | `COMPARE_OP` 可能需要适配 |
| ✅12 | test_12_for_loop.py | @GoldenStain | #69700 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅13 | test_13_make_function.py | @GoldenStain | #69567 | | `MAKE_FUNCTION` 字节码有变动，需要适配 |
| ✅14 | test_14_operators.py | @GoldenStain | #69567 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅15 | test_15_slice.py | @SigureMo | #69557 | | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅16 | test_16_paddle_api.py | @SigureMo | #69432 | | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅17 | test_17_paddle_layer.py | @SigureMo | #69557 | | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅18 | test_18_tensor_method.py | @SigureMo | #69432 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅19 | test_19_closure.py | @gouzil | #69753 | | 段错误 |
| ✅20 | test_20_string.py | @GoldenStain | #69346 | | `FORMAT_SIMPLE` 不支持 |
| ✅21 | test_21_global.py | @SigureMo | #69436 | | `END_FOR` 检查挂掉 |
| ✅22 | test_analysis_inputs.py | @SigureMo | #69707 | | 疑似 Instruction offset 相关需要适配 |
| ✅23 | test_binary_operator_tracker.py | @SigureMo | #69431 | `op = dis.cmp_op[cmp_op_index] IndexError: tuple index out of range` | `COMPARE_OP` 可能需要适配 |
| ✅24 | test_break_graph.py | @SigureMo | #69744 | `TypeError: Can't constructs a 'paddle.Tensor' with data type <class 'paddle.jit.sot.opcode_translator.executor.variables.basic.NullVariable'>, data type must be scalar\|list\|tuple\|np.ndarray\|paddle.Tensor` | 传参错位 |
| ✅25 | test_builtin_bool.py | @GoldenStain | #69567 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅26 | test_builtin_dispatch.py | @GoldenStain | #69567 | | 大量传参错位 |
| ✅27 | test_builtin_map.py | @SigureMo | #69436 | | `END_FOR` 检查挂掉 |
| ✅28 | test_builtin_range.py | @SigureMo | #69557 | | `END_FOR` 检查挂掉 |
| ✅29 | test_builtin_zip.py | @SigureMo | #69557 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅30 | test_call_ast.py | | | | |
| ✅31 | test_call_object.py | @SigureMo | #69432 | | `too many positional arguments` |
| ✅32 | test_case_base.py | | | | |
| ✅33 | test_constant_graph.py | @SigureMo | #69431 | | 段错误 |
| ✅34 | test_dataclass.py | @gouzil | #69267 | | 段错误 |
| ✅35 | test_delete_fast.py | @gouzil | #69267 | | 段错误 |
| ✅36 | test_dtype.py | @SigureMo | #69432 | | 段错误 |
| ✅37 | test_dup_top.py | @GoldenStain | #69567 | | `TO_BOOL` 不支持 |
| ✅38 | test_enumerate.py | @SigureMo | #69557 | | `NotImplementedError`，需进一步查明 |
| ✅39 | test_envs.py | | | | |
| ✅40 | test_error_handling.py | | | | |
| ✅41 | test_execution_base.py | | | | |
| ✅42 | test_guard_outputs.py | | | | |
| ✅43 | test_guard_user_defined_fn.py | @SigureMo | #69432 | | `NotImplementedError`，需进一步查明 |
| ✅44 | test_inplace_api.py | @GoldenStain | #69567 | | |
| ✅45 | test_instruction_translator_cache.py | | | | |
| ✅46 | test_min_graph_size.py | @SigureMo | #69735 | | 段错误 |
| ✅47 | test_model_switch_training.py | @GoldenStain | #69567 | | cache 计数出错 |
| ✅48 | test_multiple_args.py | | | | |
| ✅49 | test_mutable_data.py | | | | |
| ✅50 | test_numpy.py | @SigureMo | #69735 | | `MAKE_FUNCTION` 字节码有变动，需要适配 |
| ✅51 | test_numpy_var_if.py | @SigureMo | #69431 | `Not support builtin function: __ge__ with args: Args(NumpyVariable, ConstantVariable)` | 疑似传参错位 |
| ✅52 | test_output_restoration.py | | | | |
| ✅53 | test_segment_linear.py | | | | |
| ✅54 | test_side_effects.py | @SigureMo | #69557 | | `END_FOR` 检查挂掉 |
| ✅55 | test_simulate_initialize.py | @gouzil | #69738 | `x.get_py_value() NotImplemented` | 需要定位 |
| ✅56 | test_sir_rollback.py | @gouzil | #69267 | | 段错误 |
| ✅57 | test_sot_call.py | | | | |
| ✅58 | test_sot_cost_model.py | @GoldenStain | #69567 | | `TO_BOOL` 不支持 |
| ✅59 | test_sot_dynamic_shape.py | @SigureMo | #69557 | | 输出类型检查失败 |
| ✅60 | test_sot_exception.py | @SigureMo | #69431 | | 行号检查失败等 |
| ✅61 | test_sot_export.py | @GoldenStain | #69567 | | export 失败，文件不存在 |
| ✅62 | test_sot_resnet.py | @GoldenStain | #69567 | | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅63 | test_sot_resnet50_backward.py | @SigureMo | #69557 | | 参数错位，疑似需要 `CALL_KW` 适配 |
| ✅64 | test_sot_stop_gradient.py | | | | |
| ✅65 | test_specialization.py | | | | |
| ✅66 | test_stack.py | | | | |
| ✅67 | test_step_profiler.py | | | | |
| ✅68 | test_str_format.py | @GoldenStain | #69567 | | `MAKE_FUNCTION` 适配 |
| ✅69 | test_tensor_dtype_in_guard.py | @SigureMo | #69431 | | `TypeError: '>=' not supported between instances of 'paddle.base.libpaddle.DataType' and 'paddle.base.libpaddle.DataType'` 疑似模拟参数错位 |
| ✅70 | test_tensor_slice.py | | | | |
| ✅71 | test_trace_list_arg.py | | | | |
| ✅72 | test_unsupport_function.py | | | | |
| ✅73 | test_resume_cache.py | @GoldenStain | #69700 | | `TO_BOOL` 不支持|

**Comment by SigureMo** [comment]
SOT Python 3.13 单测修复工作在上周已经基本推进完成，SOT Python 3.13 支持暂不在 Paddle 3.0 发布，发版后会继续进行模型验证和修复的推进～
