### ISSUE TITLE
paddlepaddle能不能做Image Caption，有没有相关的数据集吗？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#6924]
* 所谓Image Caption，就是从图片中自动生成一段描述性文字，有点类似于我们小时候做过的“看图说话”。知乎地址：[https://www.zhihu.com/collection/172414758](https://www.zhihu.com/collection/172414758)
* 讲道理，paddlepaddle能不能做这一个呢？有没有相关的数据集可以使用呢？

**Comment by lcy-seso** [comment]
https://arxiv.org/abs/1504.00325
