### ISSUE TITLE
dataloader对于GPU Tensor是否支持

### ISSUE THREAD

**Issue by banjiuyufen** [PaddlePaddle/Paddle#69291]
### bug描述 Describe the Bug

在Paddle Science中的ppsci/data/dataset/cgcnn_dataset.py文件中，如果在函数collate_pool中将数据设置为Tensor会报错
![image](https://github.com/user-attachments/assets/0375231e-6949-42ae-a54c-cc1cf9917010)
报错代码如下：

    """

    def collate_pool(dataset_list):
    """
    Collate a list of data and return a batch for predicting crystal properties.

    Args:
        dataset_list (list): A list of tuples for each data point containing:
            - atom_fea (paddle.Tensor): Shape (n_i, atom_fea_len).
            - nbr_fea (paddle.Tensor): Shape (n_i, M, nbr_fea_len).
            - nbr_fea_idx (paddle.Tensor): Shape (n_i, M).
            - target (paddle.Tensor): Shape (1,).
            - cif_id (str or int).

    Returns:
        tuple: Contains the following:
            - batch_atom_fea (paddle.Tensor): Shape (N, orig_atom_fea_len). Atom features from atom type.
            - batch_nbr_fea (paddle.Tensor): Shape (N, M, nbr_fea_len). Bond features of each atom's M neighbors.
            - batch_nbr_fea_idx (paddle.Tensor): Shape (N, M). Indices of M neighbors of each atom.
            - crystal_atom_idx (list): List of paddle.Tensor of length N0. Mapping from the crystal idx to atom idx.
            - target (paddle.Tensor): Shape (N, 1). Target value for prediction.
            - batch_cif_ids (list): List of CIF IDs.

    Notes:
        - N = sum(n_i); N0 = sum(i)
    """
    batch_atom_fea, batch_nbr_fea, batch_nbr_fea_idx = [], [], []
    crystal_atom_idx, batch_target = [], []
    batch_cif_ids = []
    base_idx = 0
    for i, item in enumerate(dataset_list):
        input = item[0]["i"]
        label = item[1]["l"]
        id = item[2]["c"]
        atom_fea, nbr_fea, nbr_fea_idx = input
        target = label
        cif_id = id
        n_i = atom_fea.shape[0]  # number of atoms for this crystal
        batch_atom_fea.append(atom_fea)
        batch_nbr_fea.append(nbr_fea)
        batch_nbr_fea_idx.append(nbr_fea_idx + base_idx)
        new_idx = paddle.to_tensor(np.arange(n_i) + int(base_idx), dtype="int64")
        crystal_atom_idx.append(new_idx)
        batch_target.append(target)
        batch_cif_ids.append(cif_id)
        base_idx += n_i

    # Debugging: print shapes of the tensors to ensure they are consistent
    # print("Shapes of batch_atom_fea:", [x.shape for x in batch_atom_fea])
    # print("Shapes of batch_nbr_fea:", [x.shape for x in batch_nbr_fea])
    # print("Shapes of batch_nbr_fea_idx:", [x.shape for x in batch_nbr_fea_idx])

    # Ensure all tensors in the lists have consistent shapes before concatenation
    batch_atom_fea = paddle.concat(batch_atom_fea, axis=0)
    batch_nbr_fea = paddle.concat(batch_nbr_fea, axis=0)
    batch_nbr_fea_idx = paddle.concat(batch_nbr_fea_idx, axis=0)

    return (
        {
            "i": (
                paddle.to_tensor(batch_atom_fea, dtype="float32"),
                paddle.to_tensor(batch_nbr_fea, dtype="float32"),
                paddle.to_tensor(batch_nbr_fea_idx),
                [paddle.to_tensor(crys_idx) for crys_idx in crystal_atom_idx],
            )
        },
        {"l": paddle.to_tensor(paddle.stack(batch_target, axis=0))},
        {"c": batch_cif_ids},
    )
在提交PR的版本中，将函数中 paddle.concat 改为 np.concatenate；将 paddle.to_tensor 改为 np.array 即可解决报错。

**Comment by zxcd** [comment]
如果整个网络都在gpu上的话，dataloader肯定也是支持gpu输入的。建议查看一下网络是否有一部分在cpu上

**Comment by banjiuyufen** [comment]
> 如果整个网络都在gpu上的话，dataloader肯定也是支持gpu输入的。建议查看一下网络是否有一部分在cpu上

官方文档不是显示dataloader中不支持GPU Tensor子进程吗，
![image](https://github.com/user-attachments/assets/9bf284de-6ba2-4d5e-a9d5-c9b78108ef5b)

**Comment by zxcd** [comment]
抱歉没理解你的意思，你是说希望在子进程中新增GPU tensor的操作的支持吗？
