### ISSUE TITLE
unexpected keyword argument 'average_window'

### ISSUE THREAD

**Issue by 333caowei** [PaddlePaddle/Paddle#693]
ubuntu 14.04 LTS，使用[paddle-cpu-0.8.0b1-Linux.deb](https://github.com/PaddlePaddle/Paddle/releases)安装，安装完成后运行demo，报错unexpected keyword argument 'average_window'，具体显示如下：

> caowei@caowei-OptiPlex-390:~/software/paddle/demo/sentiment$ sh train.sh 
> I1201 21:23:39.580473  5609 Util.cpp:151] commandline: /usr/bin/../opt/paddle/bin/paddle_trainer --config=trainer_config.py --save_dir=./model_output --job=train --use_gpu=false --trainer_count=4 --num_passes=5 --log_period=10 --dot_period=20 --show_parameter_stats_period=100 --test_all_data_in_one_period=1 
> I1201 21:23:39.580605  5609 Util.cpp:126] Calling runInitFunctions
> I1201 21:23:39.580756  5609 Util.cpp:139] Call runInitFunctions done.
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3185, in parse_config_and_serialize
>     config = parse_config(config_file, config_arg_str)
>   File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3161, in parse_config
>     execfile(config_file, make_config_environment(config_file, config_args))
>   File "trainer_config.py", line 34, in <module>
>     gradient_clipping_threshold=25
>   File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
>     return func(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 45, in __wrapper__
>     return func(*args, **kwargs)
> TypeError: settings() got an unexpected keyword argument 'average_window'
> F1201 21:23:39.942836  5609 PythonUtil.cpp:130] Check failed: (ret) != nullptr Python Error: <type 'exceptions.TypeError'> : settings() got an unexpected keyword argument 'average_window'
> Python Callstack: 
>             /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3185
>             /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3161
>             trainer_config.py : 34
>             /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 45
>             /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 45
> Call Object failed.
> *** Check failure stack trace: ***
>     @     0x7f9628e67daa  (unknown)
>     @     0x7f9628e67ce4  (unknown)
>     @     0x7f9628e676e6  (unknown)
>     @     0x7f9628e6a687  (unknown)
>     @           0x7447a7  paddle::callPythonFuncRetPyObj()
>     @           0x744b0c  paddle::callPythonFunc()
>     @           0x670a53  paddle::TrainerConfigHelper::TrainerConfigHelper()
>     @           0x671094  paddle::TrainerConfigHelper::createFromFlags()
>     @           0x50a0b3  main
>     @     0x7f9628073f45  (unknown)
>     @           0x515455  (unknown)
>     @              (nil)  (unknown)
> /usr/bin/paddle: 行 81:  5609 已放弃               (核心已转储) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by luotao1** [comment]
这个已经在release-9.0分支中fix了，可以更新代码，或者直接去掉average_window就行

**Comment by WoNiuHu** [comment]
@luotao1  Traceback (most recent call last):
  File "/home/blanc/local/tasks/sentiment_classify/predict_input.py", line 153, in <module>
    main()
  File "/home/blanc/local/tasks/sentiment_classify/predict_input.py", line 135, in main
    predict = SentimentPrediction(train_conf, dict_file, model_path, label)
  File "/home/blanc/local/tasks/sentiment_classify/predict_input.py", line 46, in __init__
    conf = parse_config(train_conf, "is_predict=1")
  File "/home/blanc/paddle/paddle/python27/lib/python2.7/site-packages/paddle/trainer/config_parser.py", line 3566, in parse_config
    make_config_environment(trainer_config, config_args))
  File "/home/blanc/local/tasks/sentiment_classify/trainer_config.py", line 37, in <module>
    gradient_clipping_threshold=25)
  File "/home/blanc/paddle/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/home/blanc/paddle/paddle/python27/lib/python2.7/site-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
TypeError: settings() got an unexpected keyword argument 'average_window'
麻烦帮忙看下啊，我在另一个版本的0.9.0的paddle上跑是正常的，请问这个这么改？

**Comment by luotao1** [comment]
请问什么是另一个版本的0.9.0的paddle？paddle只有一个0.9.0版本。你可以看看这个版本和你能跑的版本之间有什么差别？用`paddle version`看一下。
