### ISSUE TITLE
[Paddle3.0.0Beta2] 安装之后训练无法调起GPU

### ISSUE THREAD

**Issue by FlamingoPg** [PaddlePaddle/Paddle#69340]
### bug描述 Describe the Bug

run check能找到GPU，
![C14960A2A5EBD6FE494CB268CB2E989A](https://github.com/user-attachments/assets/b1034f76-a09f-445a-bd48-ee187c75ce70)

当beta2启动训练时，找不到GPU
![0D3E9BC91201EED568A5B38A3D458E1F](https://github.com/user-attachments/assets/b947002b-6cfb-4364-8cb1-ff671fbaae40)

![AF15557ADF8DC1E0D61E7C974ACEC10B](https://github.com/user-attachments/assets/3873ee66-ceef-4a71-bb88-7830954e725f)
版本是cu118，paddle3.0.0.beta2

**Comment by warrentdrew** [comment]
您好，可以查看下CUDA_VISIBLE_DEVICES有没有正确设置，这里运行命令看CUDA_VISIBLE_DEVICES= 可能是直接设置为空了

**Comment by Liyulingyue** [comment]
经测试 CUDA_VISIBLE_DEVICES=0,1 可以顺利调用GPU
