### ISSUE TITLE
Paddle 0.10.0 官网网页api文档显示有问题

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#6938]
官网网页 api文档显示有问题，如
http://www.paddlepaddle.org/docs/0.10.0/documentation/zh/api/v2/config/layer.html
![image](https://user-images.githubusercontent.com/31875089/34326592-eb25450a-e8eb-11e7-926c-a6872a4f1d0a.png)
这个已经修正过了，在develop页面下是没有问题的。

**Comment by luotao1** [comment]
如果要在0.10.0版本中修复，需要将对应的PR或者commit提交到0.10.0分支。但由于文档的格式问题比较多，在新版本发布后，如果老版本没有严重的问题，暂时不进行修复了。
