### ISSUE TITLE
编译Paddle需要的最低GCC版本

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#694]
当前Paddle可以用gcc4.6版本来编译，这个ISSUE讨论是否将Paddle最低gcc版本提高gcc4.8。

gcc4.6的一些问题：
1. gcc4.6支持部分c++11语法，比如不支持[Type alias, alias template ](https://github.com/PaddlePaddle/Paddle/issues/new)等；
2. gcc4.6不支持`-std=c++11`编译选项，只支持`-std=c++0x`编译选项，但是nvcc不支持`-std=c++0x`编译选项；所以nvcc + gcc4.6环境下cuda部分是用不了c++11特性的。
3.  issue #415 问题的根本原因是，nvcc不支持`-std=c++0x`，为了避免`-std=c++0x`参数透传到nvcc，cmake中设置了set(CUDA_PROPAGATE_HOST_FLAGS OFF)，但也导致了Debug或Release的参数也不能自动透传给nvcc。

**Comment by backyes** [comment]
百度生产环境除了预测场景下，可能依赖特定环境外，训练场景均具备gcc4.8的条件。

**Comment by wangkuiyi** [comment]
发一个PR更新一下文档？ @hedaoyuan

**Comment by hedaoyuan** [comment]
嗯，大家有疑问在这里讨论吧，我会提一个修改成最低支持gcc4.8的PR，主要涉及cmake里的改动。
