### ISSUE TITLE
undefined symbol问题

### ISSUE THREAD

**Issue by yuluzhong** [PaddlePaddle/Paddle#69403]
### 问题描述 Issue Description

ValueError: (InvalidArgument) Fail to open library: /home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so with error: /home/ma-user/anaconda3/envs/PyTorch-2.1.0/lib/python3.9/site-packages/paddle_custom_device/libpaddle-custom-npu.so: undefined symbol: ZN13custom_kernel14GatherNdKernelIbN3phi13CustomContextEEEvRKT0_RKNS1_11DenseTensorES8_PS6
[Hint: dso_handle should not be null.] (at /paddle/paddle/fluid/platform/init.cc:152)
各位老师们，请问这个问题怎么解决呢

### 版本&环境信息 Version & Environment Information

芯片型号  昇腾 910B
我的gcc版本是8.4.0
架构为arm
CANN-8.0.RC1.alpha002
系统为Linux notebook-558dd96e-c505-43fa-a4a1-376b14b047ff 4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64 #1 SMP Tue Jun 6 07:58:07 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux

**Comment by xiaoguoguo626807** [comment]
是按照这个文档编译安装的吗，看起来是没有设置"CUSTOM_DEVICE_ROOT"路径为npu 的路径
https://github.com/PaddlePaddle/PaddleCustomDevice/blob/develop/backends/npu/README_cn.md

**Comment by xiaoguoguo626807** [comment]
编译的时候加一下
![image](https://github.com/user-attachments/assets/31e41f36-fa5a-4c81-8b5f-35137bdb26ab)
试试， 或者检查一下这个路径下是不是有libpaddle-custom-npu.so
