### ISSUE TITLE
日志打印问题

### ISSUE THREAD

**Issue by juncyan** [PaddlePaddle/Paddle#69433]
### bug描述 Describe the Bug

![微信截图_20241115165314](https://github.com/user-attachments/assets/49b9f389-61ed-4e5d-87ca-ffef79890230)
使用paddle3.0在训练模型时，会自动打印日志，在这个截图上[TRAIN]和[EVAL]是我设置的logging的输出。但是[INFO]复制了一份我设置的内容并输出。同样的代码，我是用paddle2.5就没有这个问题。

### 其他补充信息 Additional Supplementary Information

paddle2.5之后的版本加载图片也会模型奇妙打印许多警报日志。但可以通过pil_logger = logging.getLogger('PIL')
pil_logger.setLevel(logging.INFO)屏蔽掉。

**Comment by ZHUI** [comment]
你试试paddle最新develop呢？
这个问题一般是，代码中加了`logging.basicConfig`类似代码，我在最新dev中没有发现。
https://github.com/search?q=repo%3APaddlePaddle%2FPaddle++logging.basicConfig&type=code

**Comment by juncyan** [comment]
> 你试试paddle最新develop呢？ 这个问题一般是，代码中加了`logging.basicConfig`类似代码，我在最新dev中没有发现。 https://github.com/search?q=repo%3APaddlePaddle%2FPaddle++logging.basicConfig&type=code

这个是paddle和python3.10的冲突，用python3.8就不会出现问题

**Comment by ZHUI** [comment]
没问题就好
