### ISSUE TITLE
set_default_dtype文档中的参数描述有误

### ISSUE THREAD

**Issue by rookieLiu2018** [PaddlePaddle/Paddle#69458]
### 文档链接&描述 Document Links & Description

文档对参数的描述为
> d (string|np.dtype) - 设为默认值的 dtype。它仅支持 float16、float32 和 float64。

但在该[PR](https://github.com/PaddlePaddle/Paddle/pull/53567)中已经至少添加了对BF16的支持

### 请提出你的建议 Please give your suggestion

修改文档的介绍

**Comment by zhwesky2010** [comment]
@rookieLiu2018 我们后续会修复该文档Bug
