### ISSUE TITLE
目前Paddle在aarch64环境下的 nightly build 都是运行正常的，您这里如果想要一个能够在aarch64上跑的docker镜像，可以使用 `registry.baidubce.com/device/paddle-cpu:kylinv10-aarch64-gcc82` 这个镜像，这个是公开镜像直接使用docker pull拉取即可。

### ISSUE THREAD

**Issue by huameinan219** [PaddlePaddle/Paddle#69489]
目前Paddle在aarch64环境下的 nightly build 都是运行正常的，您这里如果想要一个能够在aarch64上跑的docker镜像，可以使用 `registry.baidubce.com/device/paddle-cpu:kylinv10-aarch64-gcc82` 这个镜像，这个是公开镜像直接使用docker pull拉取即可。

_Originally posted by @qili93 in https://github.com/PaddlePaddle/Paddle/issues/54755#issuecomment-1598037800_

**Comment by huameinan219** [comment]
您好，该镜像pull不下来，请问在飞腾/鲲鹏下编译paddle，现在有能pull下来的镜像吗，教程里的也pull不下来

**Comment by HydrogenSulfate** [comment]
感谢提交issue，看起来可能原来的镜像失效了，我们内部找一下，有结论的话第一时间回复你。

**Comment by DSFDSFSer2** [comment]
您好，还有吗‘

**Comment by HydrogenSulfate** [comment]
> 您好，还有吗‘

已经找到了硬件相关的同事，正在处理

**Comment by HydrogenSulfate** [comment]
> 您好，还有吗‘

你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？
![image](https://github.com/user-attachments/assets/595d2d2c-7969-4b22-a588-7e9cbc74608e)

**Comment by huameinan219** [comment]
> > 您好，还有吗‘
> 
> 你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？ ![image](https://private-user-images.githubusercontent.com/23737287/389405553-595d2d2c-7969-4b22-a588-7e9cbc74608e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjM4NjksIm5iZiI6MTczMjUyMzU2OSwicGF0aCI6Ii8yMzczNzI4Ny8zODk0MDU1NTMtNTk1ZDJkMmMtNzk2OS00YjIyLWE1ODgtN2U5Y2JjNzQ2MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA4MzI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMmYxNmI2YmY3NGJjZDk0NTRmZjNlNzExYzU5N2YwMDRjOTRkNDNmZTk1NzdmMjJlMGY2ODFkYjcxY2IyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v99sE--TOFD-zjBD5tqDKzu4JMwEhQmCvEtsW7-aLsY)
我这边需要在FT-2000+与Kunpeng-920两款CPU上使用paddleOCR，且为离线环境，故需要离线编译相关源码与依赖

**Comment by DSFDSFSer2** [comment]
> > > 您好，还有吗‘
> > 
> > 
> > 你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？ ![image](https://private-user-images.githubusercontent.com/23737287/389405553-595d2d2c-7969-4b22-a588-7e9cbc74608e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1MjM4NjksIm5iZiI6MTczMjUyMzU2OSwicGF0aCI6Ii8yMzczNzI4Ny8zODk0MDU1NTMtNTk1ZDJkMmMtNzk2OS00YjIyLWE1ODgtN2U5Y2JjNzQ2MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA4MzI0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkMmYxNmI2YmY3NGJjZDk0NTRmZjNlNzExYzU5N2YwMDRjOTRkNDNmZTk1NzdmMjJlMGY2ODFkYjcxY2IyNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.v99sE--TOFD-zjBD5tqDKzu4JMwEhQmCvEtsW7-aLsY)
> > 我这边需要在FT-2000+与Kunpeng-920两款CPU上使用paddleOCR，且为离线环境，故需要离线编译相关源码与依赖

您好，我这边的硬件环境是Phytium，D2000/8，aarch64架构

**Comment by DSFDSFSer2** [comment]
> > 您好，还有吗‘
> 
> 你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？ ![image](https://private-user-images.githubusercontent.com/23737287/389405553-595d2d2c-7969-4b22-a588-7e9cbc74608e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjc3NTgsIm5iZiI6MTczMjUyNzQ1OCwicGF0aCI6Ii8yMzczNzI4Ny8zODk0MDU1NTMtNTk1ZDJkMmMtNzk2OS00YjIyLWE1ODgtN2U5Y2JjNzQ2MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZmJhMDRlNGU1NzI0ZDRhNDg2MDBmNzQ0ODdjYjkxMjRmZWE1ZjZkOGIwYzMyMjdmNGI3NDMxODU0OTEwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hTleXATBhlkMksaFo202NFURwnuaVqNxe1x74f_tNk)

您好，我这边的硬件环境是Phytium，D2000/8，aarch64架构，请问我是麒麟v10的操作系统，应该如何编译

**Comment by DSFDSFSer2** [comment]
> > > 您好，还有吗‘
> > 
> > 
> > 你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？ ![image](https://private-user-images.githubusercontent.com/23737287/389405553-595d2d2c-7969-4b22-a588-7e9cbc74608e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjc3NTgsIm5iZiI6MTczMjUyNzQ1OCwicGF0aCI6Ii8yMzczNzI4Ny8zODk0MDU1NTMtNTk1ZDJkMmMtNzk2OS00YjIyLWE1ODgtN2U5Y2JjNzQ2MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZmJhMDRlNGU1NzI0ZDRhNDg2MDBmNzQ0ODdjYjkxMjRmZWE1ZjZkOGIwYzMyMjdmNGI3NDMxODU0OTEwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hTleXATBhlkMksaFo202NFURwnuaVqNxe1x74f_tNk)
> 
> 您好，我这边的硬件环境是Phytium，D2000/8，aarch64架构，请问我是麒麟v10的操作系统，应该如何编译

您好，由于电脑为离线，需要使用镜像

**Comment by HydrogenSulfate** [comment]
> > > 您好，还有吗‘
> > 
> > 
> > 你好，方便提供一下具体的硬件型号吗？以及使用镜像的目的？除了镜像我们应该也能提供已经编译好的pip包，可以看下官网上这个armV8的包是否能使用？ ![image](https://private-user-images.githubusercontent.com/23737287/389405553-595d2d2c-7969-4b22-a588-7e9cbc74608e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1Mjc3NTgsIm5iZiI6MTczMjUyNzQ1OCwicGF0aCI6Ii8yMzczNzI4Ny8zODk0MDU1NTMtNTk1ZDJkMmMtNzk2OS00YjIyLWE1ODgtN2U5Y2JjNzQ2MDhlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTI1VDA5MzczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZmJhMDRlNGU1NzI0ZDRhNDg2MDBmNzQ0ODdjYjkxMjRmZWE1ZjZkOGIwYzMyMjdmNGI3NDMxODU0OTEwNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.0hTleXATBhlkMksaFo202NFURwnuaVqNxe1x74f_tNk)
> 
> 您好，我这边的硬件环境是Phytium，D2000/8，aarch64架构，请问我是麒麟v10的操作系统，应该如何编译

编译的时候可能需要联网安装一些第三方库，你的离线环境可能即便有了镜像也无法编译，感觉你可以先尝试官网上把whl包手动下载好，然后拷贝到机器上进行pip安装？

**Comment by DSFDSFSer2** [comment]
> 编译的时候可能需要联网安装一些第三方库，你的离线环境可能即便有了镜像也无法编译，感觉你可以先尝试官网上把whl包手动下载好，然后拷贝到机器上进行pip安装？

好的，感谢您的指导

**Comment by HydrogenSulfate** [comment]
@DSFDSFSer2 本issue先暂时关闭了，如果还有安装上的问题的话，仍然可以在这个issue中继续回复或者新提交一个issue

**Comment by sduqlsc** [comment]
> [@DSFDSFSer2](https://github.com/DSFDSFSer2) 本issue先暂时关闭了，如果还有安装上的问题的话，仍然可以在这个issue中继续回复或者新提交一个issue


@HydrogenSulfate 
你好，如果想编译鲲鹏CPU上的paddle-inference是否有镜像可用，原来的镜像已经失效了。

另，我在鲲鹏服务器上用ubuntu22.04的docker镜像gcc-11+python3.10参考https://www.paddlepaddle.org.cn/inference/master/guides/hardware_support/cpu_phytium_cn.html 进行编译成功后，`C++ 安装部署`部分，提示CUDA tookit 找不到。

在CMKE中加入  `-DCUDAToolkit_ROOT="" \  # 显式清空 CUDA 路径
  -DCMAKE_CUDA_COMPILER=""  # 禁用 CUDA 编译器` 后，又提示build目录找不到

**Comment by sduqlsc** [comment]
[/data/Paddle-Inference-Demo/c++/cpu/resnet50# ./compile.sh 
+ work_path=/data/Paddle-Inference-Demo/c++/cpu/resnet50
+ '[' '!' -d /data/Paddle-Inference-Demo/c++/cpu/resnet50/../../lib/paddle_inference ']'
+ '[' '!' -f /data/Paddle-Inference-Demo/c++/cpu/resnet50/CMakeLists.txt ']'
+ mkdir -p build
+ cd build
+ rm -rf CMakeCache.txt CMakeFiles
+ DEMO_NAME=resnet50_test
+ WITH_MKL=OFF
+ WITH_ONNXRUNTIME=OFF
+ WITH_OPENVINO=OFF
+ WITH_ARM=ON
+ WITH_MIPS=OFF
+ WITH_LOONGARCH=OFF
+ WITH_SW=OFF
+ WITH_SHARED_PHI=ON
+ WITH_ONEDNN=OFF
+ WITH_ROCM=OFF
+ WITH_IPU=OFF
+ WITH_GPU=OFF
+ LIB_DIR=/data/Paddle-Inference-Demo/c++/cpu/resnet50/../../lib/paddle_inference
+ cmake .. -DPADDLE_LIB=/data/Paddle-Inference-Demo/c++/cpu/resnet50/../../lib/paddle_inference -DDEMO_NAME=resnet50_test -DWITH_MKL=OFF -DWITH_ONNXRUNTIME=OFF -DWITH_OPENVINO=OFF -DWITH_ARM=ON -DWITH_MIPS=OFF -DWITH_LOONGARCH=OFF -DWITH_SW=OFF -DWITH_STATIC_LIB=OFF -DWITH_SHARED_PHI=ON -DWITH_GPU=OFF
-- The CXX compiler identification is GNU 11.4.0
-- The C compiler identification is GNU 11.4.0
CMake Error at /usr/share/cmake-3.22/Modules/CMakeDetermineCUDACompiler.cmake:179 (message):
  Failed to find nvcc.

  Compiler requires the CUDA toolkit.  Please set the CUDAToolkit_ROOT
  variable.
Call Stack (most recent call first):
  CMakeLists.txt:2 (project)
