### ISSUE TITLE
昇腾910B上taskflow调用UIE模型推理占用显存特别大

### ISSUE THREAD

**Issue by silence-pan84** [PaddlePaddle/Paddle#69486]
### 请提出你的问题 Please ask your question

昇腾910B上taskflow调用UIE模型推理占用显存特别大
![c0b62cd10f2f0b976688d6fccdc6c6a](https://github.com/user-attachments/assets/42f0aa10-80ab-4cf2-b7bb-500d3eafe432)

**Comment by HydrogenSulfate** [comment]
想问一下是用的paddle什么套件跑的UIE吗？比如paddlenlp或者是paddleocr？

**Comment by silence-pan84** [comment]
> 想问一下是用的paddle什么套件跑的UIE吗？比如paddlenlp或者是paddleocr？

paddlenlp

**Comment by HydrogenSulfate** [comment]
这个可能需要麻烦 @DrownFish19 或者PaddleNLP的同学帮忙看看~

**Comment by Irisnotiris** [comment]
@silence-pan84 根据我个人经验，paddle的环境变量里有个显存分配策略，默认是naive_best_fit，设置`paddle.set_flags({'FLAGS_allocator_strategy': 'auto_growth'})`试试，希望能帮到你~
参考：https://www.paddlepaddle.org.cn/documentation/docs/zh/2.6/guides/flags/memory_cn.html

**Comment by silence-pan84** [comment]
@Irisnotiris 感谢，这种方法的确可行。

**Comment by HydrogenSulfate** [comment]
@silence-pan84 看起来问题已经解决，如果还有使用上的问题可以提交新issue。
