### ISSUE TITLE
api中的name参数不起作用

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/Paddle#69497]
### 描述：

> 我注意到很多api有name这个参数，但一直没用到这个参数，今天尝试了一下，发现这个参数没发挥出任何文档中描述的作用，而且有问题的[文档链接](https://www.paddlepaddle.org.cn/documentation/docs/zh/api_guides/low_level/program.html#api-guide-name)中给的例子是fluid的，已经被你们官方弃用。但从这个有问题的文档描述中能提取到name参数起以下三个作用：

> 1. 更改层名。
> 2. 更改权重或偏置名。
> 3. 实现权重共享。

> 紧接着我在当前的3.0-beta的api中进行了测试，比如[nn.Linear](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/nn/Linear_cn.html)这个api就有name这个参数。测试结果如下图。在该图中，Linear层的name被设置为‘rrrr’，但是输出层名时，仍然是默认的输出名字，并未起到更改层名作用，此外我还尝试了，for g in model.named_parameters()等一些列的可以输出带层名的api，仍没看到效果。至于共享权重我也测试了，也没看到效果，就不放图了。

![image](https://github.com/user-attachments/assets/31f2c303-28d6-4d56-b186-05fe1c098018)

> 也可能是我自己理解有误，如果我理解有误请多多包涵，给大佬添麻烦了。

### 请提出你的建议 Please give your suggestion

更新有问题的文档描述和相关被弃用的例子。
也有可能是我技术不行，没理解透，希望大佬能解答一下多谢。

**Comment by HydrogenSulfate** [comment]
感谢提交issue，针对你的几个问题，回答如下：
1. name这个参数应该是早期静态图里使用的，但是后面paddle已经切换到默认的动态图，因此为了兼容而保留（否则接口参数数量就不同了）了这个参数，并且所有的动态图API里关于name的描述都是推荐不要设置，实际我看nn.Linear的实现也其实已经没有用name这个参数了，属于是被废弃的参数，但是因为兼容性而没有退场
> name (str，可选) - 具体用法请参见 [Name](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_guides/low_level/program.html#api-guide-name)，一般无需设置，默认值为 None。

2. 如果你想在动态图中更改层名，那么可以直接修改`self.linear`的名字，将其改成`self.rrrr = nn.Linear(...)`即可，因为动态图的层名是按照nn.Layer下的成员名字命名的；如果想更改权重，那么可以直接通过`model.linear.weight/bias`获取到权重/偏置，然后对其修改即可；如果想实现权重共享，动态图中的权重共享一般是通过使用同一个模型进行多次计算完成，举个例子，假如你想让 `self.linear`作为一个共享权重的子模块，那么就让他参与“共享权重”的计算过程，如下所示

``` py
class Model:
    self.linear = nn.Linear(...)
    self.out_linear1 = nn.Linear(...)
    self.out_linear2 = nn.Linear(...)
    
    def forward(self, x):
        head = self.linear(x)
        out1 = self.out_linear1(head)
        out2 = self.out_linear2(head)
        return out1, out2
```

上述代码就让`self.head`这个线性层成为了共享权重层（共享权重的典型论文是SimSiamNet，可以看下他的pytorch代码实现理解一下：）。我不知道我给的这个例子你好不好理解，如果不好理解，可以提供更详细的场景和代码，我帮你看下

**Comment by ZACP-DERMATOLOGY** [comment]
这是我用paddle以来提issue回复最快一次，感谢大佬回复，有一种很爽的喝可乐感觉哈哈哈哈，明白了，name参数既然是废参数我以后不碰了哈哈哈哈，感谢大佬。
然后这个共享权重我想共享layer1和layer4的权重，如下图，假如这四个层都是nn.Linear。这时候只需在forward的layer1和layer4处都调用同一个在__init__初始化中定义的线性层就好了嘛？
![image](https://github.com/user-attachments/assets/66f27557-02e8-445e-99ac-874975677384)

**Comment by HydrogenSulfate** [comment]
根据你的图，应该是可以确定的是layer1和layer4输入、输出通道数是相同的，所以我跟你的图简单写了个代码，可以参考看下：
``` py
import paddle


class Model(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
        self.layer1 = paddle.nn.Linear(1, 3)
        self.layer2 = paddle.nn.Linear(3, 4)
        self.layer3 = paddle.nn.Linear(4, 1)

    def forward(self, x):
        x1 = self.layer1(x)
        x2 = self.layer2(x1)
        x3 = self.layer3(x2)
        x4 = self.layer1(x3) # <-- 共享权重，因此仍然使用 layer1

        return x4

x = paddle.randn([16, 1])
model = Model()

y = model(x)
print(y.shape)
```

在动态图中，所谓共享权重，其实是指权重所在的层重复使用，这样反向计算的时候共享层的权重会多次出现在计算图中，梯度也会被累加多次，达到共享的目的

**Comment by ZACP-DERMATOLOGY** [comment]
嗯嗯明白了大佬，和我预想的一样十分感谢。
问题：
再问最后一个问题😂，因为有时候我看到一些论文中共享参数，他们还会共享不同层的权重（权重数量一样，不考虑偏置），比如nn.Embedding和nn.Linear，我可以让他们的weight_attr具有相同的数量，一个在网络的开始使用，另一个在网络的终点使用，但是这俩层共享参数，该怎么搞呢。（或者将Embedding中的一半权重与Linear中的一半权重进行共享）。
自己的构想：
我自己初步是想定义一个张量，给他开启梯度计算（stop_gradient=False），然后把这个tensor输送到两个层中的weight_attr.set_value上，其余则正常训练更新梯度计算什么的，不知这样能否实现我这个不同层的共享权重吗大佬？我很快就会实施到这里了😊

**Comment by HydrogenSulfate** [comment]
> 嗯嗯明白了大佬，和我预想的一样十分感谢。 问题： 再问最后一个问题😂，因为有时候我看到一些论文中共享参数，他们还会共享不同层的权重（权重数量一样，不考虑偏置），比如nn.Embedding和nn.Linear，我可以让他们的weight_attr具有相同的数量，一个在网络的开始使用，另一个在网络的终点使用，但是这俩层共享参数，该怎么搞呢。（或者将Embedding中的一半权重与Linear中的一半权重进行共享）。 自己的构想： 我自己初步是想定义一个张量，给他开启梯度计算（stop_gradient=False），然后把这个tensor输送到两个层中的weight_attr.set_value上，其余则正常训练更新梯度计算什么的，不知这样能否实现我这个不同层的共享权重吗大佬？我很快就会实施到这里了😊

你说的这种共享确实稍微复杂一些，需要手动操作，不再是简单地重复使用权重所在层了。然后你说的把weight进行传递是正确的做法，也就是说不再依赖nn.Linear这种封装好的API，而是手动构造可学习参数Tensor作为权重（假设这个权重变量叫做`weight`，另外建议用这个接口创建可学习参数：<https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/create_parameter_cn.html#create-parameter>），将`weight`进行传递时，linear部分手动调用[`out = F.linear(x, weight)`](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/linear_cn.html#linear)，embedding部分手动调用[`F.embedding(x, weight)`](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/nn/functional/embedding_cn.html#embedding)进行计算。
另外也不一定要传递，你可以自定义一个可以接收外来weight的Linear和embedding，这样仍然是在`__init__`中初始化这两种自定义层，计算仍然跟原来类似，不需要让weight显式地在代码中返回、传递

``` py
import paddle


class CustomLinear(paddle.nn.Layer):
    def __init__(self, weight: paddle.Tensor):
        super().__init__()
        self.weight = weight

    def forward(self, x: paddle.Tensor) -> paddle.Tensor:
        return paddle.nn.functional.linear(x, self.weight)


class CustomEmbedding...同理
```

**Comment by ZACP-DERMATOLOGY** [comment]
感谢技术大佬耐心解答，😘
祝paddle越来越好

**Comment by HydrogenSulfate** [comment]
> 感谢技术大佬耐心解答，😘 祝paddle越来越好

> 我自己初步是想定义一个张量，给他开启梯度计算（stop_gradient=False），然后把这个tensor输送到两个层中的weight_attr.set_value上

你说的这个操作是不对的，`set_value`只是简单地拷贝值，过程并不可微，linear和embedding的参数仍然是两份独立参数，而参数共享需要让这两个参数指向同一个张量。所以建议按照我上面给的代码操作。

**Comment by ZACP-DERMATOLOGY** [comment]
感谢大佬指导，嗯嗯，小弟跪谢了技术大佬。
要不然我得走不少弯路正要实施这个步骤呢
提issue体验最好的一次，很少遇到你这么顶的技术支持了







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月20日(星期三) 中午12:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] api中的name参数不起作用 (Issue #69497)














  
感谢技术大佬耐心解答，😘 祝paddle越来越好
   
我自己初步是想定义一个张量，给他开启梯度计算（stop_gradient=False），然后把这个tensor输送到两个层中的weight_attr.set_value上
  
你说的这个操作是不对的，set_value只是简单地拷贝值，linear和embedding的参数仍然是两份独立参数，而参数共享需要让这两个参数指向同一个张量。所以建议按照我上面给的代码操作。
