### ISSUE TITLE
FlashMask 的使用问题

### ISSUE THREAD

**Issue by complexfilter** [PaddlePaddle/Paddle#69523]
1. 在 H100 GPU上相对A100有额外的加速吗？
2. FlashMask的sliding window是否支持文生图任务中的frame-based granularity level？比如文生图任务只在临近的frames中算attention，此时的attention需要的颗粒度是单个frame，而不是单个token。
3. FlashMask的sliding window是否支持frame-based granularity level + key frames的mask? 就是既在临近的frames中算attention，且对每个frame对关键帧算attention。就是所有column 中，有若干个column要做full attention。

**Comment by GuoxiaWang** [comment]
1、目前还没针对 Hopper 做优化
2、FlashMask 是支持 token 粒度的，逐列 mask，因此可以表达如下的 mask 场景，但是需要自己构造 `startend_row_indices` 传入
3、可以的，可以参考论文 https://arxiv.org/abs/2410.01359 中的 Figure 1(a)12

<img width="810" alt="949e392626f8a0532ea16c60f4bca566" src="https://github.com/user-attachments/assets/714ad540-a479-4c06-92f4-2e95de7089e6">

<img width="478" alt="image" src="https://github.com/user-attachments/assets/1f139c7f-b2b5-412b-beb1-71c5c7b8dcce">
