### ISSUE TITLE
[XPU] add xpu backend

### ISSUE THREAD

**Issue by linkk08** [PaddlePaddle/Paddle#69535]
### 需求描述 Feature Description

create_predictor函数添加xpu后端支持; <br /> kunlun芯片落地算法需要用到xpu;  <br /> 添加xpu后端支持, 启用kunlun芯片功能

**Comment by hong19860320** [comment]
Paddle 已经支持 paddleinference，可以参考 https://github.com/PaddlePaddle/Paddle-Inference-Demo/blob/67cfdc3553937b5fbda61cffa0862af3f845c651/python/xpu/resnet50/infer_resnet.py#L20
