### ISSUE TITLE
AI Studio编译Paddle框架报错

### ISSUE THREAD

**Issue by aquagull** [PaddlePaddle/Paddle#69657]
### bug描述 Describe the Bug

CMake命令：`cmake .. -DPY_VERSION=3.8 -DWITH_GPU=ON -DWITH_TESTING=ON -DCMAKE_BUILD_TYPE=Release`
Make命令：`make -j22`
错误描述：在完整编译好源码后正常关闭ai studio，隔天再次开启后重新编译会出现如下错误（并不唯一但都是链接错误）。
此时只能删除所有之前编译的内容，重新编译整个项目才能成功。
![image](https://github.com/user-attachments/assets/b830df7e-a4c8-49fb-9792-bec99671075b)

**Comment by yangguohao** [comment]
你这个是重新cmake 后 make 的吗，因为 aistudio 关闭后所有缓存都没了，要重新cmake

**Comment by aquagull** [comment]
> 你这个是重新cmake 后 make 的吗，因为 aistudio 关闭后所有缓存都没了，要重新cmake

其中我也尝试过重新cmake后再make，但结果都一样。我在四期的开源活动里问过，似乎只有我有这种情况？

**Comment by FlamingoPg** [comment]
> > 你这个是重新cmake 后 make 的吗，因为 aistudio 关闭后所有缓存都没了，要重新cmake
> 
> 其中我也尝试过重新cmake后再make，但结果都一样。我在四期的开源活动里问过，似乎只有我有这种情况？

只能删掉build重新 make

**Comment by aquagull** [comment]
> > > 你这个是重新cmake 后 make 的吗，因为 aistudio 关闭后所有缓存都没了，要重新cmake
> > 
> > 
> > 其中我也尝试过重新cmake后再make，但结果都一样。我在四期的开源活动里问过，似乎只有我有这种情况？
> 
> 只能删掉build重新 make

了解，谢谢
