### ISSUE TITLE
请问下有distributed.stream.gather的文档吗？

### ISSUE THREAD

**Issue by houj04** [PaddlePaddle/Paddle#69686]
### 文档链接&描述 Document Links & Description

在文档中只看到了有`all_gather`的文档：https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api/paddle/distributed/stream/all_gather_cn.html
想问下有没有`gather`的文档，谢谢！

**Comment by yuanlehome** [comment]
gather 目前官网没有，可以暂时先看这个 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/distributed/communication/gather.py

稍后我找相关同事添加下这个api文档。

**Comment by yuanlehome** [comment]
当前有英文文档，参见 https://www.paddlepaddle.org.cn/documentation/docs/en/develop/api/paddle/distributed/gather_en.html

**Comment by yuanlehome** [comment]
@deepllz 同事后面会负责添加下中文文档，Thanks～
