### ISSUE TITLE
docker image url error

### ISSUE THREAD

**Issue by wang-tf** [PaddlePaddle/Paddle#69717]
### 文档链接&描述 Document Links & Description

I got the error when followed by https://www.paddlepaddle.org.cn/.
![image](https://github.com/user-attachments/assets/f1eebb1f-f541-44ad-86e3-85ac8abd9343)

My code: docker pull ccr-2vdh3abv-pub.cnc.bj.baidubce.com/paddlepaddle/paddle:3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5
Error: Error response from daemon: unknown: artifact paddlepaddle/paddle:3.0.0b2-gpu-cuda11.8-cudnn8.6-trt8.5 not found

Finally the url in this [page](https://www.paddlepaddle.org.cn/documentation/docs/zh/install/docker/linux-docker.html) work fine.

### 请提出你的建议 Please give your suggestion

Please check the docker image URL status.

**Comment by tianshuo78520a** [comment]
Discovered that this image was missed during the image synchronization process. It has been uploaded and will be attempted again?

**Comment by wang-tf** [comment]
Yes, it can work now. Thanks.
