### ISSUE TITLE
The comments in sequence_pool_op.cc is not right.

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#6974]
In following code, the `pooltype` is the string type, but it is int in the comments.

https://github.com/PaddlePaddle/Paddle/blob/d3c42f7d374eeaa1c76dd67d682219077a5c2a01/paddle/operators/sequence_pool_op.cc#L50-L54

**Comment by luotao1** [comment]
The reason is that  https://github.com/PaddlePaddle/Paddle/pull/5264/commits/43ee2d0c8cfa94b754a467fdaac0b7752e40301d replace enum with string, but forget to update the comment.
