### ISSUE TITLE
多条时序性数据预测

### ISSUE THREAD

**Issue by JillJenny** [PaddlePaddle/Paddle#6979]
假设有10个页面，标记ID为A ~ J

用户示例数据

A B C B D E F D G H
A B C B G H
A D E F G H
A D B J
A B C B D E F D G H
A B C B D E F D G H
A B C B D E F D G H
A B C B D E F D G H
A D B J
A B D E J
A E J
A D E J
A D B C B J
A D B C B D E J
A E J B D E F D G
A G H
A G A
A B C B D B C B D E J

预测的输入
A 预测 下一步结果 X
A+X 预测 下一步结果 XX
A+X+XX 预测 下一步结果 XXX

现在有多条时序列的话  如何整体给出一条最大概率的预测结果呢？
有同学有好的方法  欢迎讨论

**Comment by will-am** [comment]
这个像是用马尔科夫模型

**Comment by JillJenny** [comment]
好的  你觉得RNN适合解决这种问题么

**Comment by will-am** [comment]
感觉也可以用RNN试一下，先A预测X得到一个概率，然后A+X作为输入预测XX得到一个概率..... 最后把这些概率乘起来作为得到整条序列的概率
