### ISSUE TITLE
early training termination when cost starts increasing?

### ISSUE THREAD

**Issue by proteushf** [PaddlePaddle/Paddle#698]
I am running with training config num_passes=30, e.g.: https://github.com/PaddlePaddle/Paddle/blob/develop/demo/quick_start/train.sh

Is it possible that the training can stop when the cost starts increasing consistently so that unnecessary time can be saved? Thanks.

**Comment by backyes** [comment]
Currently，the process can not automatically stop if cost starts increasing. You can write help python scripts to monitor the output log and kill process if some requirements are satisfied. 

@qingqing01 @pengli09 Can you give some better suggestions?

**Comment by pengli09** [comment]
@backyes Currently we can only do it as you suggested.

**Comment by proteushf** [comment]
Thanks for the reply!
