### ISSUE TITLE
关于解码器初始化的想法

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#6980]
在我的使用中，我注意到，一般初始化解码器的时候，用的是first_seq,last-seq这两个函数。取的是序列的两端的数据进行初始化，然而，我觉得，如果能够添加一个层就更好了：它可以实现随机从序列中挑选一个时间步的数据，或者指定序列中间某个时间步的数据进行初始化。当然，这样的话，也许它也许没有什么特殊的物理意义，然而我觉得可以尝试一下。

**Comment by lcy-seso** [comment]
这个做法是Bengio在论文里面提出的。我之前的实验，这个因素并不是非常重要。可以直接初始化为0。使用解码反向第一个词，是因为反向第一个词恰好是<s>，而解码从<s>开始。

**Comment by yyhlvdl** [comment]
的确是这样。其实，我的思路是这样的。在教程中，是把输入文字ont-hot编码，然后embedding；只是，在我看来，一次做一句或者几句话太慢了，所以，我就想把大量语句(段落)放在一起，整个段落one-hot编码，再经过一系列的提取特征之类的。最终，进入数据层的不是文字，而是段落的向量，然后在初始化的时候，显示找不到序列的开始位置。我猜测的是，教程中的方法，那样做，保留了文字之间的顺序信息，是个时间步序列，然而我这样做之后，得到的其实只是矩阵，向量之间没有了顺序信息。所以，才会有上面的想法，直接自己指定时间步，将矩阵有序化。

**Comment by yyhlvdl** [comment]
其实是这样的，我觉得一句话一句话的翻译实在麻烦。所以，就想着能不能段落式翻译，当然，我看到有双层序列这样的东西。不过，我还是想用教程的方法。于是，我就将整个段落都one-hot编码，然后embedding，再经过一些处理。这样，进入网络数据层的已经不是教程那样的句子了，而是段落多次变换后的矩阵了。然后，初始化的时候，显示的是序列开始位置找不到(我没有把那个错误保留下来)。我猜测的是，这样的矩阵，其实每行之间已经没有什么顺序关系了，所谓的时间步也没有意义了。不像教程那样，还保留着文字间的顺序关系。那么，如果我们可以指定矩阵的时间步就好了，就是说人为加入顺序信息。我觉得，只要整个段落是对应的话，应该也可以，所以，才有上面的想法。

**Comment by lcy-seso** [comment]
目前绝大多数（90%）以上基于神经网络的文本生成都是一个字一个字生成。文本本身含有词法和句法信息，这些都附着在序列信息之上。解码时，后面的词语依赖于这个词之前的信息，有时需依赖关系。只在极其少数前沿的论文中会考虑打破这种逐词生成方式。不建议用在通用任务上。

**Comment by yyhlvdl** [comment]
是的。多谢。
