### ISSUE TITLE
demo quick_start中train.sh时报错

### ISSUE THREAD

**Issue by donote** [PaddlePaddle/Paddle#699]
直接执行train.sh时报出以下错误，paddle自带python的sys.maxunicode 为65535，jumbo自带python的maxunicode为1114111，报错信息如下：
F1202 10:24:18.795364  5465 PythonUtil.cpp:191] Check failed: (module) != nullptr Current PYTHONPATH: ['/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/opt/paddle/bin', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/setuptools-18.2-py2.7.egg', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/Paddle/demo/quick_start', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python27.zip', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/plat-linux2', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-tk', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-old', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-dynload', '/home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages']
Python Error: <type 'exceptions.ImportError'> : /home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/lib-dynload/operator.so: undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString
Python Callstack:
            /home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/paddle/trainer/config_parser.py : 78
            /home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/logging/__init__.py : 26
            /home/liuhui05/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/collections.py : 9
Import paddle.trainer.config_parserError

**Comment by donote** [comment]
UCS2对应的maxunicode为65535，UCS4为1114111，使用了系统自带的python应该支持UCS2的（报错信息undefined symbol: _PyUnicodeUCS2_AsDefaultEncodedString）

**Comment by backyes** [comment]
```
wangyanfei@** quick_start]$ ls
api_train.py  data                  predict.sh                   trainer_config.emb.py          train.log
api_train.sh  dataprovider_bow.py   trainer_config.bidi-lstm.py  trainer_config.lr.py           train.sh
core.21783    dataprovider_bow.pyc  trainer_config.cnn.py        trainer_config.lstm.py
core.6571     dataprovider_emb.py   trainer_config.db-lstm.py    trainer_config.resnet-lstm.py
[wangyanfei@** quick_start]$ pwd
/home/wangyanfei/paddle_internal_release_tools/idl/paddle/Paddle/demo/quick_start
[wangyanfei@** quick_start]$ which python
~/binaries/o/python27-gcc482/bin/python
[wangyanfei@** quick_start]$ which paddle
~/binaries/o/bin/paddle
[wangyanfei@** quick_start]$
```
@donote  尝试未能最终复现上述问题。也是采用的一键编译的产出，其中是自带的python解释器。

具体至于为什么你会出现这个问题，我会尝试后续给出。

**Comment by backyes** [comment]
@reyoung @wangkuiyi @gangliao @qingqing01 也帮忙看看

**Comment by donote** [comment]
系统环境gcc4.8.2版本问题，链接到系统自带的gcc4.8.2版本后问题解决，/opt/compiler/gcc-4.8.2 -> /home/opt/gcc-4.8.2.bpkg-r2/gcc-4.8.2.bpkg-r2
