### ISSUE TITLE
paddlepaddle的数据流的问题

### ISSUE THREAD

**Issue by yyhlvdl** [PaddlePaddle/Paddle#6997]
我想知道 output.sequenceStartPositions和 input.sequenceStartPositions这个东西指的是什么？可以在哪里查看吗？

**Comment by Xreki** [comment]
在Paddle里面，数据都是存成`Matrix`结构的，但是因为一个`batch`里面序列的长度可能是不一样的，所以需要`sequenceStartPositions`这样一个结构来保存`sequence`的信息。那么：
- 序列的个数：`sequenceStartPositions.size() - 1`
- 序列的长度： `sequenceStartPosition[i + 1] - sequenceStartPositions[1]`
- 第`i`个`sequence`对应的数据：`Matrix`中的第`sequenceStartPositons[i]`（包含）到`sequenceStartPositions[i + 1]`（不包含）行。

**Comment by yyhlvdl** [comment]
是这个问题，最近我想写一些代码，然而各种报错。比如这样的，
I1225 18:14:38.359241 12053 GradientMachine.cpp:94] Initing parameters..
I1225 18:14:40.559262 12053 GradientMachine.cpp:101] Init parameters done.
F1225 18:14:41.805058 12053 Matrix.cpp:513] Check failed: a.width_ == b.height_ (174 vs. 1312) 
我想问问，像GradientMachine.cpp这样的文件在哪里可以查看。
我感觉，根据官网的文档，自己写paddle的代码实在是困难，感觉各种layer，数据结构的属性都无处知道。有错误不知道怎么解决，想写新的代码，然而基本的数据在网络中的存储和格式变化都不清楚。

**Comment by Xreki** [comment]
> F1225 18:14:41.805058 12053 Matrix.cpp:513] Check failed: a.width_ == b.height_ (174 vs. 1312)

这个错误，应该是配置或者数据问题。出错的地方源码在这里：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/Matrix.cpp#L514 是矩阵乘里面两个矩阵的规模对不上。

> 像GradientMachine.cpp这样的文件在哪里可以查看。

在这里： https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/gradientmachines/GradientMachine.cpp 
如果你想找某个文件，将Paddle源码`git clone`到本地后，使用`find -name GradientMachine.cpp`即可找到。

> 感觉各种layer，数据结构的属性都无处知道。

由于历史原因，确实缺乏文档。有问题请尽管在github上发issue提出，我们将尽力解决，:smile:

**Comment by yyhlvdl** [comment]
多谢多谢。

**Comment by yyhlvdl** [comment]
根据我的理解，在paddle中的数据是这样的：
1.数据的质：就是官方入门教程所说的几种数据格式；数据的量：我们可以查看的矩阵。
2.量的查看： event.gm.getLayerOutputs这个工具，不过，我觉得其实没有什么特别的意义，因为每一层查看的结果都是字典：{ids:,矩阵：array[[]]，probs:}这样的格式。
3.质的查看：
（1）在每一层：真正的数据格式的信息，是在哪里存储的(sequenceStartPositions)？可以查看吗？怎么查看？用户可以自行修改吗？怎么修改？
（2）层与层之间：这些真正的数据信息，在层与层之间是如何传递的(对用户而言应该不是很重要)?每个新层应该是可以重塑数据的质的，那么，是如何重塑的，用户在挑选层的时候有什么办法可以预知自己的数据经过此新层后的质？
4.我觉得这些问题如果把paddle的源代码全部看一遍，应该是可以解决的，不过，如果官方api可以给出解答，那么，使用paddle起来会更加方便，这样无论是搭建网络，还是自己写新的函数，甚至新层都要简单许多。

**Comment by yyhlvdl** [comment]
我试验了一下，比如说deepspeech中的network.py文件，blockexpand文件将卷积结果转化为序列。序列信息存储在output_.sequenceStartPositions，我想看看它的具体样子，就将此层输出进入新层first_seq,然后报错：F1226 12:07:32.272393  6192 GatedRecurrentLayer.cpp:78] Check failed: input.sequenceStartPositions ，
在其文件中是这样描述的，void GatedRecurrentLayer::forward(PassType passType) {
  REGISTER_TIMER_INFO("GruFwTimer", getName().c_str());
  Layer::forward(passType);

  const Argument& input = getInput(0);
  CHECK(input.sequenceStartPositions);
也就是说，blockexpand赋予的序列信息output_.sequenceStartPositions，应该在 const Argument& input = getInput(0);这一步传给了input,那么下一步的CHECK应该是没有问题的，不知道问题出在哪里。不过，如果用户想要修改这些c++文件，是不是还要重新编译？

**Comment by luotao1** [comment]
> 如果用户想要修改这些c++文件，是不是还要重新编译安装paddle

是的，用户如果改了C++文件，需要重新编译paddle。

> 就将此层输出进入新层first_seq, 然后报错：F1226 12:07:32.272393 6192 GatedRecurrentLayer.cpp:78] Check failed: 

报的错是在GatedRecurrentLayer里面，您应该是first_seq后面接了gru_layer吧。first_seq是取了每个序列的第一个时间步，所以sequenceStartPositions就为null了，因为已经不是序列了。

**Comment by yyhlvdl** [comment]
嗯。
1.第一个问题是的，我在尝试修改，重新编译paddle(但愿不要这样)；
2.全貌是这样的，我将blockexpand的结果，既然它已经序列化了，我就想试试将它进行这样的操作：
def seq_to_seq_layer(input,encoder_size,decoder_size):
    #(3.1)编码，因为输入的是语音数据的特征向量，所以直接双层gru实现hi，与向量H
    src_forward = paddle.networks.simple_gru(
        input=input, size=encoder_size)
    src_backward = paddle.networks.simple_gru(
        input=input, size=encoder_size, reverse=True)
    encoded_vector = paddle.layer.concat(name='enc_vec',input=[src_forward, src_backward])

    #(3.2)解码器：根据ci(源语言生成的上下文向量)，解码器状态zi,，预测下个状态zi+1
    #(3.2.1)将编码向量进行映射
    encoded_proj = paddle.layer.fc(
        name='enc_proj',
        act=paddle.activation.Linear(),
        size=decoder_size,
        bias_attr=False,
        input=encoded_vector)
    #(3.2.2)解码器初始状态，c0=hT
    backward_first = paddle.layer.first_seq(input=src_backward)
    decoder_boot = paddle.layer.fc(
        size=decoder_size,
        act=paddle.activation.Tanh(),
        bias_attr=False,
        input=backward_first)
    def gru_decoder_with_attention(enc_vec,enc_proj):
    #(3.1.1)记录zi,初始化为decoder_boot
        decoder_mem = paddle.layer.memory(
            name='gru_decoder', size=decoder_size)
    #(3.1.2)enc_vec就是hj,enc_porj是hj的映射，得到ci
        context = paddle.networks.simple_attention(
            encoded_sequence=enc_vec,
            encoded_proj=enc_proj,
            decoder_state=decoder_mem)
    #(3.1.3)融合ci,si
        decoder_inputs = paddle.layer.fc(
            act=paddle.activation.Linear(),
            size=decoder_size * 3,
            bias_attr=False,
            input=context)
    #(3.1.4)实现zi+1：ci、si、zi
        gru_step = paddle.layer.gru_step(
            name='gru_decoder',
            input=decoder_inputs,
            output_mem=decoder_mem,
            size=decoder_size)
        return gru_step
    #(3.3.4)实现输出
    decoder_group_name = "decoder_group"
    group_input1 = paddle.layer.StaticInput(input=encoded_vector)
    group_input2 = paddle.layer.StaticInput(input=encoded_proj)
    group_inputs = [group_input1, group_input2]
    decoder = paddle.layer.recurrent_group(
        name=decoder_group_name,
        step=gru_decoder_with_attention,
        input=group_inputs)
    return decoder
思想就是试试是否可以用序列来提取一些序列的特征(注意力思想)，然后报错：F1226 14:11:29.925763  5895 RecurrentGradientMachine.cpp:417] Check failed: !commonSeqInfo_.empty() At least one input needs to be sequence or subsequence。我个人认为，这样的代码只是简单的把机器翻译教程的代码掐头去尾，即输入输出由文字序列变为向量序列(因为我前几个问题尝试过段落翻译)，实在是不明白这个错误的来源，简直没有道理。

**Comment by luotao1** [comment]
您的group_inputs只有两个StaticInput的输入，没有数据输入，因此报错。
具体可参考：http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/deep_model/rnn/recurrent_group_cn.html 【输入】部分
而我们的示例在https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/train.py#L93 有数据输入。

**Comment by yyhlvdl** [comment]
我明白您的意思，您的意思是，这个group_inputs它需要数据输入，可是，在我看来  group_inputs = [group_input1, group_input2,input]这样的模式，其中，input就是我原始的输入，就是blockexpand后需要我去提取信息的向量序列，然而同样的报错。难道说，group_inputs只能选择教程中那样的输入模式吗？
就我现在的想法，即实现向量序列通过编码解码模式生成新的向量序列这个思想，可以用这个教程框架实现吗？

**Comment by luotao1** [comment]
> 在我看来 group_inputs = [group_input1, group_input2,input]这样的模式，其中，input就是我原始的输入，就是blockexpand后需要我去提取信息的向量序列

上面的配置应该发生了变化吧，请把修改后的配置贴出来看看。

**Comment by yyhlvdl** [comment]
def seq_to_seq_layer(input,encoder_size,decoder_size):
    #(3.1)编码，因为输入的是语音数据的特征向量，所以直接双层gru实现hi，与向量H
    src_forward = paddle.networks.simple_gru(
        input=input, size=encoder_size)
    src_backward = paddle.networks.simple_gru(
        input=input, size=encoder_size, reverse=True)
    encoded_vector = paddle.layer.concat(input=[src_forward, src_backward])

    #(3.2)解码器：根据ci(源语言生成的上下文向量)，解码器状态zi,，预测下个状态zi+1
    #(3.2.1)将编码向量进行映射
    encoded_proj = paddle.layer.fc(
        act=paddle.activation.Linear(),
        size=decoder_size,
        bias_attr=False,
        input=encoded_vector)
    #(3.2.2)解码器初始状态，c0=hT
    backward_first = paddle.layer.first_seq(input=src_backward)
    decoder_boot = paddle.layer.fc(
        size=decoder_size,
        act=paddle.activation.Tanh(),
        bias_attr=False,
        input=backward_first)
    def gru_decoder_with_attention(enc_vec,enc_proj,inputs):
    #(3.1.1)记录zi,初始化为decoder_boot
        decoder_mem = paddle.layer.memory(
            name='gru_decoder', size=decoder_size)
    #(3.1.2)enc_vec就是hj,enc_porj是hj的映射，得到ci
        context = paddle.networks.simple_attention(
            encoded_sequence=enc_vec,
            encoded_proj=enc_proj,
            decoder_state=decoder_mem)
    #(3.1.3)融合ci,si
        decoder_inputs = paddle.layer.fc(
            act=paddle.activation.Linear(),
            size=decoder_size * 3,
            bias_attr=False,
            input=[context,inputs])
    #(3.1.4)实现zi+1：ci、si、zi
        gru_step = paddle.layer.gru_step(
            name='gru_decoder',
            input=decoder_inputs,
            output_mem=decoder_mem,
            size=decoder_size)
        return gru_step
    #(3.3.4)实现输出
    decoder_group_name = "decoder_group"
    group_input1 = paddle.layer.StaticInput(input=encoded_vector)
    group_input2 = paddle.layer.StaticInput(input=encoded_proj)
    inputs = input
    group_inputs = [group_input1, group_input2,inputs]
    decoder = paddle.layer.recurrent_group(
        name=decoder_group_name,
        step=gru_decoder_with_attention,
        input=group_inputs)
    return decoder

**Comment by luotao1** [comment]
> 然而同样的报错

错误也贴一下吧

**Comment by yyhlvdl** [comment]
不好意思，跑通了。
