### ISSUE TITLE
如何对教程中的草稿重置或者删除

### ISSUE THREAD

**Issue by ZACP-DERMATOLOGY** [PaddlePaddle/Paddle#69993]
### 需求描述 Feature Description

我在进行paddle[官方教程](https://aistudio.baidu.com/projectdetail/8604450)学习的时候，草稿中的代码被我改的和[教师版本](https://aistudio.baidu.com/projectdetail/3731547?pV=836194)差距太大导致运行错误了，然后我想重置这个草稿版本或者删除它，再重新开一个新的草稿版本。然后我没找到重置或者删除草稿的地方如下图所示。
![image](https://github.com/user-attachments/assets/be8d36df-9774-477a-a2b5-d8e2daff713d)

### 替代实现 Alternatives

如果有重置的话希望大牛告诉下在哪，要是没有添加这个功能即可多谢。

### 替代实现 Alternatives

各位技术大佬辛苦告诉下我，多谢多谢

**Comment by ZACP-DERMATOLOGY** [comment]
> [!TIP]
> #69810  和我提的这个问题一样，大佬在吗？看来好多人有我这个需求呢😂

**Comment by qjyyy77** [comment]
需要看一下是在封闭课的课节里还是作业里？
1. 如果是课节里，可以点“重新学习”
![e6a45d25f2e11cf040f5758ccd825884](https://github.com/user-attachments/assets/c7b9d7fe-32bd-4a97-9114-d449048bebb7)

2. 如果在作业里，可以点“重新答题”
<img width="1512" alt="dc5e237544338b34f27cc92767ffb79c" src="https://github.com/user-attachments/assets/ec01d85d-a4aa-4b77-9e40-f339240a075f">

**Comment by ZACP-DERMATOLOGY** [comment]
感谢大佬，我居然没注意那个重新学习按钮，多谢多谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年12月10日(星期二) 上午9:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [PaddlePaddle/Paddle] 如何对教程中的草稿重置或者删除 (Issue #69993)














 
需要看一下是在封闭课的课节里还是作业里？
  
 
如果是课节里，可以点“重新学习”
 e6a45d25f2e11cf040f5758ccd825884.jpg (view on web)
 
 
 
如果在作业里，可以点“重新答题”
 
  dc5e237544338b34f27cc92767ffb79c.png (view on web)
