### ISSUE TITLE
运行demo/model_zoo/embedding/pre_DictAndModel.sh ，报错

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#701]
网络环境：阿里云主机-香港
系统：Ubuntu -Docker

--2016-12-02 04:39:35--  (try:13)  http://paddlepaddle.bj.bcebos.com/model_zoo/embedding/baidu.dict
Connecting to paddlepaddle.bj.bcebos.com (paddlepaddle.bj.bcebos.com)|111.206.38.19|:80... connected.
HTTP request sent, awaiting response... Read error (Connection reset by peer) in headers.
Retrying.

<img width="747" alt="daa3220a7342fa197895324d5" src="https://cloud.githubusercontent.com/assets/1908992/20823125/6315634c-b88c-11e6-9bbc-d6c07072aae9.png">

**Comment by llxxxll** [comment]
发现一个规律，大多数下载报错出现在36%这个长度，限速300K/S达到36%也会报错

> 36% [=====================>                                       ] 17,128,189   300KB/s   in 56s

**Comment by backyes** [comment]
@llxxxll 

这个是CDN节点么？ 由于CDN节点性能更地域关系挺大，所以这个问题根本原因还是CDN问题，我们这里解决不了。 另外，我在上海测试http://paddlepaddle.bj.bcebos.com/model_zoo/embedding/baidu.dict没有问题。

可否帮忙将此问题反馈到相关负责同事。

@reyoung  也知晓。

**Comment by llxxxll** [comment]
注册了一个阿里云国内华北节点，问题就解决了。
是否需要提供一个全球的CDN解决方案？

**Comment by reyoung** [comment]
Won't Fix now, 这应该是阿里云香港节点网络的问题。
