### ISSUE TITLE
paddle.nn.Layer没有参数keep_vars

### ISSUE THREAD

**Issue by zydshizhu** [PaddlePaddle/Paddle#70129]
### bug描述 Describe the Bug

# paddlepaddle版本：2.6.2
# python：3.10.10
# 运行于aistudio
import paddle

class test(paddle.nn.Layer):
    def __init__(self):
        super().__init__()
    
    def forward(self, x: paddle.Tensor) -> paddle.Tensor:
        x = x * 2
        return x

a = test()
a.train()
b = a(paddle.to_tensor([1, 2]))
a.state_dict(destination=None, include_sublayers=True, structured_name_prefix='', use_hook=True, keep_vars=True)

“”“
以下是报错：
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In[8], line 13
     11 a.train()
     12 b = a(paddle.to_tensor([1, 2]))
---> 13 a.state_dict(destination=None, include_sublayers=True, structured_name_prefix='', use_hook=True, keep_vars=True)

TypeError: Layer.state_dict() got an unexpected keyword argument 'keep_vars'
”“”

**Comment by lyuwenyu** [comment]
这参数应该是`paddle 3.0`之后才引入的；使用`paddle 2.6`时候不需要加`keep_vars `参数；比如

```python
a.state_dict(destination=None, include_sublayers=True, structured_name_prefix='', use_hook=True,)
```

**Comment by zydshizhu** [comment]
原来如此，感谢~
