### ISSUE TITLE
重构class Matrix里面的一些计算API

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#703]
class Matrix里面的一些计算API的参数是通过shared_ptr来传递，这个看起并没什么必要。MatrixPtr应该是Matrix的一个wrapper，但Matrix自身并不需要用这个wrapper。
可以将这些API的参数修改成传递引用的方式，并且将test_matrixCompare.cpp里面的测试挪到test_Matrix.cpp里面（参考issue #695 和pr #643 ）。
大致看了一下这些API是可以修改的，
contextProjectionForward
contextProjectionBackward
contextProjectionBackwardData
contextProjectionBackwardWeight
classificationError
mul

**Comment by backyes** [comment]
warp -> wrapper? 这里是包装的意思么？

**Comment by hedaoyuan** [comment]
是的，已经fix

**Comment by hedaoyuan** [comment]
通过Function #892 的形式，重构这些API。

**Comment by tianbingsz** [comment]
Please refer to https://github.com/PaddlePaddle/Paddle/pull/934

**Comment by hedaoyuan** [comment]
Close this issue by #977
