### ISSUE TITLE
k8s单机训练

### ISSUE THREAD

**Issue by yyydido** [PaddlePaddle/Paddle#7032]
按照[http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/cluster/k8s_cn.html](url)给的例子进行k8s单机训练：
1.从docker hub拉下基础镜像：`docker pull paddledev/paddle:cpu-demo-latest`
2.运行这个基础镜像`docker run --name quick_start_data -it paddledev/paddle:cpu-demo-latest`
3.在镜像里下载数据：`cd root/paddle/demo/quick_start/data`
                                     `./get_data.sh`
至此，在这个含有数据的镜像里进行测试：
`cd root/paddle/demo/quick_start/`
`./train.sh`
报错：  `No such file or directory: './data/dict.txt'`
请问 这个dict.txt是哪里来的？在基础镜像本身没有包含，下载数据之后也没有产生，但是demo的运行需要这个文件，需要自己写吗？有没有参考的例子？这个dict.txt是干什么用的？

**Comment by typhoonzero** [comment]
这个文档里的例子比较老了，即将更新，更新进度参考 [这里](https://github.com/PaddlePaddle/Paddle/issues/6909)，推荐使用 [paddlecloud](https://github.com/PaddlePaddle/cloud/blob/develop/doc/tutorial_cn.md) ，或者根据 https://github.com/PaddlePaddle/cloud/tree/develop/k8s/controller/autoscale_job 这里的yaml文件配置一个job。

**Comment by typhoonzero** [comment]
补充，这个例子的数据是由 https://github.com/PaddlePaddle/Paddle/tree/release/0.10.0/demo/quick_start/data/proc_from_raw_data 的程序生成的，供参考。

**Comment by yyydido** [comment]
@typhoonzero 谢谢，问题已解决。

**Comment by yyydido** [comment]
@typhoonzero 看到k8s分布式训练还没有更新，不知道这里是否也有问题，我按照[http://staging.paddlepaddle.org/docs/develop/documentation/zh/howto/usage/cluster/k8s_distributed_cn.html](url)这个操作，在准备数据集时出现了问题，paddledev/paddle-tutorial:k8s_data这个镜像直接启动容器运行出错: `mkdir:missing operand`
这个镜像可不可以直接运行，bash进入到容器内？或者说这个镜像如何实现的数据下载和切割，有没有其他方式实现？
使用Job运行这个镜像下载并切割数据也跑不通。
能不能帮忙排查定位一下问题？（像上个问题您给的补充回答一样，对解决问题很有帮助。）谢谢

**Comment by typhoonzero** [comment]
这个镜像进入的方法是：`docker run -it --rm --entrypoint /bin/sh paddledev/paddle-tutorial:k8s_data`

**Comment by yyydido** [comment]
@typhoonzero 好的，谢谢，我再试一下。

**Comment by yyydido** [comment]
@typhoonzero 使用这个镜像下载数据并切割数据的代码在镜像中哪个位置？

**Comment by typhoonzero** [comment]
Close due to low activity, feel free to reopen.
