### ISSUE TITLE
How use a custom layer? 

### ISSUE THREAD

**Issue by bu540402** [PaddlePaddle/Paddle#7039]
Can i write a custom layer in paddlepaddle? eg.  like keras https://keras.io/layers/writing-your-own-keras-layers/

**Comment by luotao1** [comment]
Yes, you can write a custom layer.
- if you want to write a v2-api layer, you can refer to [this](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_layer_en.rst) and its [Chinese version](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_layer_cn.rst).
- if you want to write a fluid op, you can refer to [this](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_op_en.md) and its [Chinese version](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_op_cn.md).

Hope you can write a custom layer and contribute to us.
