### ISSUE TITLE
对paddle book中的房价线性回归infer数据问题

### ISSUE THREAD

**Issue by buaapoet** [PaddlePaddle/Paddle#7049]
教程中，无论是train数据集，还是test数据集，都是归一化的。 那么，在进行某一个新房的房价预测时，新房的各个属性如何进行归一化呢？

**Comment by jacquesqiao** [comment]
测试数据需要按照训练数据同样的方法进行归一化，可以认为训练数据和测试数据应该是同分布的，否则训练本身也有问题。
