### ISSUE TITLE
no execution permission in demo/semantic_role_labeling by default

### ISSUE THREAD

**Issue by leonardgithub** [PaddlePaddle/Paddle#705]
I use the paddledev/paddle:cpu-devel-latest image, but I found the sh and py files are without x permission in the folder /root/paddle/demo/semantic_role_labeling, It is recommended you add the x permission like other demo such as quick_start/*.sh

commands:
chmod +x *.sh
chmod +x *.py

**Comment by backyes** [comment]
@leonardgithub 

Thanks for your report. :-) 

I remember that he shell script will call python script indirectly. Generally, we will prefer to call shell script with ``` sh some.sh```. For source distribution, I think current solution would be better. :-)

**Comment by leonardgithub** [comment]
@backyes I agree with you, but why in other demo such as quick_start, the sh files have x permission. It is not consistent.

**Comment by backyes** [comment]
@leonardgithub 

We will try to fix it, thanks.

**Comment by backyes** [comment]
@leonardgithub 

Would like to contribute it to help us to make it perfect. :-)
