### ISSUE TITLE
How to use weight in cost function?

### ISSUE THREAD

**Issue by nick6918** [PaddlePaddle/Paddle#7056]
```python
@wrap_name_default("cost")
@layer_support()
def classification_cost(input,
                        label,
                        weight=None,
                        name=None,
                        evaluator=classification_error_evaluator,
                        layer_attr=None,
                        coeff=1.):
    """
    classification cost Layer.

    :param name: The name of this layer. It is optional.
    :type name: basestring
    :param input: The first input layer.
    :type input: LayerOutput
    :param label: The input label.
    :type label: LayerOutput
    :param weight: The weight layer defines a weight for each sample in the
                   mini-batch. It is optional.
    :type weight: LayerOutput
    :param evaluator: Evaluator method. classification_error_evaluator is the default.
    :type evaluator: Evaluator method
    :param layer_attr: The extra layer attribute. See ExtraLayerAttribute for
                       details.
    :type layer_attr: ExtraLayerAttribute
    :param coeff: The weight of the gradient in the back propagation.
                  1.0 is the default value.
    :type coeff: float
    :return: LayerOutput object.
    :rtype: LayerOutput
    """
```

In cost function like classification cost, our goal is to implement the mechanics that samples who has one specific label has larger weight when calculating cost, 

We noticed that there is a param called weight in all these cost function, due to lack of document, I'm not sure if it is what I want? If so, how can i set this parameter correctly? If not, how to implement the goal I mentioned before(samples who has one specific label has larger weight when calculating cost,)?

Thanks a lot!

**Comment by JiayiFeng** [comment]
Yes. I believe that's what you need.
`weight` should be a matrix of size `batch_size * 1`. You can prepare it in advance and then read it by `data_reader`, just like how you get data and label.

**Comment by nick6918** [comment]
Thanks for answering!!! I'm still confused on detail implementation, I think my case should be a common one, so I hope you can help on the implementation with more detail, thanks!!!

![image](https://user-images.githubusercontent.com/5869574/34369540-61dcf82a-eaf7-11e7-91da-1ab611925159.png)
￼
![image](https://user-images.githubusercontent.com/5869574/34369544-7a002698-eaf7-11e7-84b6-9d1d24f35bfd.png)

As you can see, I want to add weight in the cost function I used in the net(figure 1), and my data is reading through reader in figure 2, since it includes a shuffle method(which should be very common), how can I generate the weight matrix properly, is there any helper mechanics?

Thanks again for your time.

**Comment by JiayiFeng** [comment]
1. Generate weights of each instance by yourself and store them together with train data and labels.

2. Add a new data layer in the `.py` file, like:
```python
weight = paddle.layer.data(
        name="weight", type=paddle.data_type.dense_vector(1))
```

3. Modify your data reader. In most normal cases, the read result of each instance is a list of two elements:
```
[data, label]
```
You need to change the code of data reader, making it return a list of three:
```
[weight, data, label]
```
Making sure that the order of elements is consistent with data layers' definition order.

**Comment by nick6918** [comment]
It works, thanks a lot!!!

**Comment by nick6918** [comment]
Thanks a lot. It works!!!

BTW, I think we also have to change feeding dict to control the order to read data for different data layers.

```python
feeding = {'weight': 0, 'word': 1, 'label': 2}
```
