### ISSUE TITLE
need to refine CMakeLists.txt of paddle/operators

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7059]
Can we auto pybind following ops?
https://github.com/PaddlePaddle/Paddle/blob/95862a547c76bcea46a2439f96ae5788e6764c63/paddle/operators/CMakeLists.txt#L59-L154

**Comment by luotao1** [comment]
Can we omit following step when we add op need deps?
https://github.com/PaddlePaddle/Paddle/blob/95862a547c76bcea46a2439f96ae5788e6764c63/paddle/operators/CMakeLists.txt#L184-L213

**Comment by typhoonzero** [comment]
Is there a way to reduce codes like:

```
if ("${TARGET}" STREQUAL "net_op") 
     set(pybind_flag 1) 
 endif() 
```

**Comment by luotao1** [comment]
I will try to refine it.
