### ISSUE TITLE
在自定义图片数据集的时候，要怎么处理这些图片呢

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7062]
* 最近在做验证码识别，但是在数据集这个问题上一直弄了很久，比如这个问题：#6754
* 数据集到底要怎么做才正确，目前做的半成品：[https://github.com/yeyupiaoling/TestVerificationCode](https://github.com/yeyupiaoling/TestVerificationCode)

**Comment by JiayiFeng** [comment]
能否明确详细地描述一下目前遇到的困难呢？看了你提到的那个issue，并没有找到明确的遗留的问题。

**Comment by yeyupiaoling** [comment]
最后给的答案是数据集的问题，那么这个图片数据集要怎么处理

**Comment by yeyupiaoling** [comment]
@JiayiFeng 你有图片识别的例子吗?自定义数据集的

**Comment by yeyupiaoling** [comment]
* 要使用足够大的数据集,
* 可以不用专门处理,因为有`reader.py`帮我们处理
