### ISSUE TITLE
新首页v0.2，请大家提意见

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#707]
![paddle 1202-0](https://cloud.githubusercontent.com/assets/1908992/20830179/4aaf691e-b8ba-11e6-8316-7a76fd7ba92b.jpg)

**Comment by Haichao-Zhang** [comment]
(1) 发现有缺失的文字，比如 
    1) 图像识别部分： “卷积神经(网)络”  
    2) 预测兴趣偏好部分： “(用)户特征”，“新(用)户”，“对(不)同电影”
    3) 易用性部分 ：”核心设计目标之(一)“
(2) 高校性 -> 高效性

**Comment by backyes** [comment]
个人比较喜欢纯白色或者类似暖色的感觉，首页上下都偏黑，感觉略压抑。 个人意见。

**Comment by llxxxll** [comment]
@Haichao-Zhang 文字部分在视觉定稿后,做静态页的时候随时可以改

**Comment by dayhaha** [comment]
图片是不是能弄一些彩色的？感觉下面的颜色有点单调，比如说猫狗的那几张图能不能找实际的图片会更好些？
