### ISSUE TITLE
The document of reshape_op is reduplicated

### ISSUE THREAD

**Issue by kuke** [PaddlePaddle/Paddle#7071]
http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid/layers.html#permalink-10-reshape
http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid/layers.html#permalink-13-reshape

What's going on here?

**Comment by luotao1** [comment]
Because there are two reshape in https://github.com/PaddlePaddle/Paddle/blob/develop/doc/api/v2/fluid/layers.rst
