### ISSUE TITLE
CPU version speed  comparison with V2 of book.04 word2vec

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#7087]
Train with CPU:

Time cost (second):

| Pass |  V2(CPU) | Fluid(CPU) |
|---------------  | ---------------  | ------------------- |
|0 | 1112.000000  | 1359.000000 |
|1 | 1089.000000 | 1381.000000 |
|2 | 1098.000000 | 1360.000000 |
|3 | 1110.000000 | 1343.000000 |
|4 | 1083.000000 | 1355.000000 |
|avg: | 1098.4 | 1359.6 |

**Comment by chengduoZH** [comment]
This issue's mission has accomplished.
