### ISSUE TITLE
GPU version speed comparison with V2 of book.04 word2vec

### ISSUE THREAD

**Issue by peterzhang2029** [PaddlePaddle/Paddle#7088]
Time cost (second) :

| Pass |  V2(GPU) | Fluid(GPU) |
|---------------  | ---------------  | ------------------- |
|0 | 62.000000  | 171.000000 |
|1 | 62.000000 | 172.000000 |
|2 | 62.000000 | 170.000000 |
|3 | 62.000000 | 169.000000 |
|4 | 62.000000 | 167.000000 |
|avg: | 62.000000 | 169.8 |

GPU-Util:
V2: around 45%
Fluid: 37-39%

**Comment by chengduoZH** [comment]
This issue's mission has accomplished.
