### ISSUE TITLE
预测程序出错Check failed: newNnz <= newHeight * newWidth (2 vs. 0)

### ISSUE THREAD

**Issue by OleNet** [PaddlePaddle/Paddle#709]
这个issue是在 #708 之后，预测时遇到的
I1202 19:15:21.218796  4109 Util.cpp:144] commandline:  --use_gpu=0
I1202 19:15:21.218876  4109 Util.cpp:113] Calling runInitFunctions
I1202 19:15:21.219243  4109 Util.cpp:126] Call runInitFunctions done.
[INFO 2016-12-02 19:15:21,231 networks.py:1122] The input order is [word]
[INFO 2016-12-02 19:15:21,231 networks.py:1129] The output order is [__fc_layer_0__]
I1202 19:15:21.232671  4109 GradientMachine.cpp:123] Loading parameters from output_20161202183004/pass-00019/
############ round test case###############
>>word 0:a
>>word 1:v
[1928, 8428] a v
F1202 19:15:24.420614  4109 CpuSparseMatrix.cpp:59] Check failed: newNnz <= newHeight * newWidth (2 vs. 0)
*** Check failure stack trace: ***
    @     0x7f76f9c666fd  google::LogMessage::Fail()
    @     0x7f76f9c6ae60  google::LogMessage::SendToLog()
    @     0x7f76f9c67227  google::LogMessage::Flush()
    @     0x7f76f9c67486  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f76fa3b912a  paddle::CpuSparseMatrix::resize()
    @     0x7f76fa3b93aa  paddle::CpuSparseMatrix::CpuSparseMatrix()
    @     0x7f76fa3c581b  paddle::Matrix::createSparseMatrix()
    @     0x7f76fa45e86d  Matrix::createSparse()
    @     0x7f76fa1749be  _wrap_Matrix_createSparse
    @     0x7f76fe48146b  PyEval_EvalFrameEx
    @     0x7f76fe483634  PyEval_EvalCodeEx
    @     0x7f76fe481efe  PyEval_EvalFrameEx
    @     0x7f76fe482cf6  PyEval_EvalFrameEx
    @     0x7f76fe483634  PyEval_EvalCodeEx
    @     0x7f76fe481efe  PyEval_EvalFrameEx
    @     0x7f76fe482cf6  PyEval_EvalFrameEx
    @     0x7f76fe482cf6  PyEval_EvalFrameEx
    @     0x7f76fe483634  PyEval_EvalCodeEx
    @     0x7f76fe483832  PyEval_EvalCode
    @     0x7f76fe49c4ac  run_mod
    @     0x7f76fe49cb0c  PyRun_FileExFlags
    @     0x7f76fe49da21  PyRun_SimpleFileExFlags
    @     0x7f76fe4add36  Py_Main
    @       0x3f0b01c4bb  (unknown)
    @           0x4006da  (unknown)
已放弃 (core dumped)

**Comment by backyes** [comment]
I can not directly identify the root cause from this log. 

@reyoung @hedaoyuan make sense ?

**Comment by reyoung** [comment]
The configuration of the neural network is wrong.

Please follow the quick start demo first.
