### ISSUE TITLE
compile error-------CBlas must be set

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#710]
what's wrong？I have installed blas and cblas

paddle]$ cmake . -DWITH_SWIG_PY=ON -DWITH_DOC=ON
-- Could NOT find LIBGLOG (missing:  LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR) 
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Failed to find gflags - Could not find gflags include directory, set GFLAGS_INCLUDE_DIR to directory containing gflags/gflags.h
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Error at cmake/cblas.cmake:137 (message):
  CBlas must be set.  Paddle support MKL, ATLAS, OpenBlas, reference-cblas.
  Try set MKL_ROOT, ATLAS_ROOT, OPENBLAS_ROOT or REFERENCE_CBLAS_ROOT.
Call Stack (most recent call first):
  CMakeLists.txt:33 (include)

-- Configuring incomplete, errors occurred!
See also "/home/renbing/tool/paddle/CMakeFiles/CMakeOutput.log".
See also "/home/renbing/tool/paddle/CMakeFiles/CMakeError.log".

**Comment by PseudoProgrammer** [comment]
Anyone else can solve this problem？

**Comment by backyes** [comment]
@PseudoProgrammer 

Firstly, for user not familiar with CMake, the docker installation could be the best option. We release docker images and some binary releases. Check http://www.paddlepaddle.org/doc/build/docker_install.html

Then, for these user preferring source installation, please install necessary dependencies before calling **cmake** command. 
http://www.paddlepaddle.org/doc/build/build_from_source.html

> -- Could NOT find LIBGLOG (missing: LIBGLOG_LIBRARY LIBGLOG_INCLUDE_DIR)

means the glog dependency is not installed.

> CBlas must be set. Paddle support MKL, ATLAS, OpenBlas, reference-cblas.
> Try set MKL_ROOT, ATLAS_ROOT, OPENBLAS_ROOT or REFERENCE_CBLAS_ROOT.
By default Paddle will search some default path to find BLAS libraries. 

Atlas default search path:
``` 
47 set(ATLAS_ROOT $ENV{ATLAS_ROOT} CACHE PATH "Folder contains Atlas")
   48 set(ATLAS_INCLUDE_SEARCH_PATHS
   49         ${ATLAS_ROOT}/include
   50         /usr/include
   51         /usr/include/atlas)
   52 set(ATLAS_LIB_SEARCH_PATHS
   53         ${ATLAS_ROOT}/lib
   54         /usr/lib
   55         /usr/lib/blas/atlas
   56         /usr/lib/atlas
   57         /usr/lib/atlas-base   # special for ubuntu 14.04.
   58     )
````

openblas default search path:
```
   79 set(OPENBLAS_INCLUDE_SEARCH_PATHS
   80         ${OPENBLAS_ROOT}/include
   81         /usr/include
   82         /usr/include/openblas
   83         /usr/local/opt/openblas/include)
   84 set(OPENBLAS_LIB_SEARCH_PATHS
   85         ${OPENBLAS_ROOT}/lib
   86         /usr/lib
   87         /usr/lib/blas/openblas
   88         /usr/lib/openblas
   89         /usr/local/opt/openblas/lib)
```
cblas default search path:
```
 112 set(REFERENCE_CBLAS_INCLUDE_SEARCH_PATHS
  113   ${REFERENCE_CBLAS_ROOT}/include
  114   /usr/include
  115   /usr/include/cblas
  116 )
  117
  118 set(REFERENCE_CBLAS_LIB_SEARCH_PATHS
  119   ${REFERENCE_CBLAS_ROOT}/lib
  120   /usr/lib
  121   /usr/lib/blas/reference/
  122   /usr/lib/reference/
  123 )
```

If you BLAS libraries are not installed in default path, please use *_ROOT path to specify it mannually. 

All above code can be found in Paddle/cmake/cblas.cmake. 

Enjoy it.

**Comment by PseudoProgrammer** [comment]
@backyes I have install gblogs,gflags and so on.But it still has somethings wrong with gtest and atlas.I have installed gtest and atlas.How to solve the two problem?
1     error log:
[renbing@yq01-dev-up-bdg22 paddle]$ cmake . -DWITH_SWIG_PY=ON   
-- No preference for use of exported gflags CMake configuration set, and no hints for include/library directories provided. Defaulting to preferring an installed/exported gflags CMake configuration if available.
-- Failed to find installed gflags CMake configuration, searching for gflags build directories exported with CMake.
-- Failed to find an installed/exported CMake configuration for gflags, will perform search for installed gflags components.
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
CMake Error at cmake/cblas.cmake:137 (message):
  CBlas must be set.  Paddle support MKL, ATLAS, OpenBlas, reference-cblas.
  Try set MKL_ROOT, ATLAS_ROOT, OPENBLAS_ROOT or REFERENCE_CBLAS_ROOT.
Call Stack (most recent call first):
  CMakeLists.txt:33 (include)


-- Configuring incomplete, errors occurred!
See also "/home/renbing/tool/paddle/CMakeFiles/CMakeOutput.log".
See also "/home/renbing/tool/paddle/CMakeFiles/CMakeError.log".

2    googltest:
[renbing@yq01-dev-up-bdg22 make]$ ./sample1_unittest 
Running main() from gtest_main.cc
[==========] Running 6 tests from 2 test cases.
[----------] Global test environment set-up.
[----------] 3 tests from FactorialTest
[ RUN      ] FactorialTest.Negative
[       OK ] FactorialTest.Negative (0 ms)
[ RUN      ] FactorialTest.Zero
[       OK ] FactorialTest.Zero (0 ms)
[ RUN      ] FactorialTest.Positive
[       OK ] FactorialTest.Positive (0 ms)
[----------] 3 tests from FactorialTest (1 ms total)

[----------] 3 tests from IsPrimeTest
[ RUN      ] IsPrimeTest.Negative
[       OK ] IsPrimeTest.Negative (0 ms)
[ RUN      ] IsPrimeTest.Trivial
[       OK ] IsPrimeTest.Trivial (0 ms)
[ RUN      ] IsPrimeTest.Positive
[       OK ] IsPrimeTest.Positive (0 ms)
[----------] 3 tests from IsPrimeTest (0 ms total)

[----------] Global test environment tear-down
[==========] 6 tests from 2 test cases ran. (1 ms total)
[  PASSED  ] 6 tests.
[renbing@yq01-dev-up-bdg22 make]$ pwd 
/home/renbing/tool/googletest-master/googletest/make

3     atlas
[renbing@yq01-dev-up-bdg22 atlas]$ ll
total 4848
-rw-r--r-- 1 renbing renbing 4963681 Dec  2 12:17 Atlas-2.2.1.el6.x86_64.rpm
[renbing@yq01-dev-up-bdg22 atlas]$ rpm -qpl Atlas-2.2.1.el6.x86_64.rpm  
/usr/local/mysql-proxy/bin/VERSION
/usr/local/mysql-proxy/bin/encrypt
/usr/local/mysql-proxy/bin/mysql-proxy
/usr/local/mysql-proxy/bin/mysql-proxyd
/usr/local/mysql-proxy/conf/test.cnf
/usr/local/mysql-proxy/lib/libevent-2.0.so.5
/usr/local/mysql-proxy/lib/libglib-2.0.so.0
/usr/local/mysql-proxy/lib/libgmodule-2.0.so.0
/usr/local/mysql-proxy/lib/libgthread-2.0.so.0
/usr/local/mysql-proxy/lib/libjemalloc.so.1
/usr/local/mysql-proxy/lib/liblua-5.1.so
/usr/local/mysql-proxy/lib/libmysql-chassis-glibext.so.0
/usr/local/mysql-proxy/lib/libmysql-chassis-timing.so.0
/usr/local/mysql-proxy/lib/libmysql-chassis.so.0
/usr/local/mysql-proxy/lib/libmysql-proxy.so.0
/usr/local/mysql-proxy/lib/libsql-tokenizer.so.0
/usr/local/mysql-proxy/lib/mysql-proxy/lua/admin.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/chassis.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/crc32.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/glib2.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/lfs.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/lpeg.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/mysql.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/posix.so
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/auth.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/auto-config.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/balance.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/charset.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/commands.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/crc32.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/filter.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/log.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/parser.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/split.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/test.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/ticker.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/proxy/tokenizer.lua
/usr/local/mysql-proxy/lib/mysql-proxy/lua/time.so
/usr/local/mysql-proxy/lib/mysql-proxy/plugins/libadmin.so
/usr/local/mysql-proxy/lib/mysql-proxy/plugins/libproxy.so
/usr/local/mysql-proxy/log

**Comment by backyes** [comment]
专门为百度同学准备的一键编译工具，能否满足你的需求？

**Comment by PseudoProgrammer** [comment]
docker?I'll try to use it,Thank you
