### ISSUE TITLE
运行逻辑回归模型出core

### ISSUE THREAD

**Issue by thomas010** [PaddlePaddle/Paddle#7103]
*** Aborted at 1514469772 (unix time) try "date -d @1514469772" if you are using GNU date ***

**Comment by thomas010** [comment]
异常信息：
I1228 22:02:52.636976 30786 Util.cpp:166] commandline:  --use_gpu=False 
I1228 22:02:52.654975 30786 GradientMachine.cpp:94] Initing parameters..
I1228 22:02:52.654975 30786 GradientMachine.cpp:101] Init parameters done.
*** Aborted at 1514469772 (unix time) try "date -d @1514469772" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f4c7dbad4d8) received by PID 30786 (TID 0x7f4c775fe700) from PID 2109396184; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7f4c7dbad4d8 __kmp_initialize_system_tick
    @     0x7f4c7db78dcd __kmp_register_library_startup()
    @     0x7f4c7db7a3a1 _INTERNAL_25_______src_kmp_runtime_cpp_7e558fa4::__kmp_do_serial_initialize()
    @     0x7f4c7db6f515 __kmp_get_global_thread_id_reg
    @     0x7f4c7db65e77 __kmp_api_GOMP_parallel_start_10_alias
    @     0x7f4c8763b817 paddle::sgdUpdateCpu()
    @     0x7f4c8763b8e1 paddle::sgdUpdate()
    @     0x7f4c87624cbf paddle::SgdThreadUpdater::threadUpdateDense()
    @     0x7f4c87625e6f _ZNSt17_Function_handlerIFvimEZN6paddle16SgdThreadUpdater11finishBatchEfEUlimE_E9_M_invokeERKSt9_Any_dataim
    @     0x7f4c874c0ecc _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
    @       0x318eab6470 (unknown)
    @       0x318b207851 (unknown)
    @       0x318aee767d (unknown)
    @                0x0 (unknown)
浮点数例外

**Comment by QiJune** [comment]
请详细描述任务类型，模型配置等相关信息

**Comment by thomas010** [comment]
配置：我用pip安装的paddle：cpu_avx_openblas版本 paddlepaddle-0.11.0-cp27-cp27mu-linux_x86_64.whl；我的机器是centos6.3，GCC4.8
问题：运行教程中的fit_a_line/trainer.py程序，报上述异常

**Comment by QiJune** [comment]
在厂内环境测试上述安装包是没有问题的。

fit_a_line是在book中得到验证的，可以使用docker环境来运行
```
docker run -d -p 8888:8888 paddlepaddle/book
```

**Comment by jacquesqiao** [comment]
FPT是浮点数异常报错，trainer_count是多少？

**Comment by terrysha** [comment]
我在mac上运行这个例子也报错 ，macos 10.13.1 ,python 2.7.14  

  File "/usr/local/lib/python2.7/site-packages/paddle/v2/plot/plot.py", line 44, in __init__
    import matplotlib.pyplot as plt
  File "/usr/local/lib/python2.7/site-packages/matplotlib/pyplot.py", line 72, in <module>
    from matplotlib.backends import pylab_setup
  File "/usr/local/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 14, in <module>
    line for line in traceback.format_stack()


  matplotlib.use('Agg')
*** Aborted at 1514875064 (unix time) try "date -d @1514875064" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fff3684d2db) received by PID 34700 (TID 0x7fff974fa340) stack trace: ***
    @     0x7fff5e127f5a _sigtramp
    @     0x7fff3684d2dc CFNumberCreate
    @     0x7fff38964ee8 -[NSPlaceholderNumber initWithDouble:]
    @     0x7fff419948ea +[CALayer defaultValueForKey:]
    @     0x7fff41993b0f classDescription_locked()
    @     0x7fff41992f98 classDescription_locked()
    @     0x7fff41992f98 classDescription_locked()
    @     0x7fff419928c5 classDescription()
    @     0x7fff419924e6 CA::Layer::class_state()
    @     0x7fff419923ad -[CALayer init]
    @     0x7fff34a6564f -[_NSBackingLayer init]
    @     0x7fff33eead5b -[NSView makeBackingLayer]
    @     0x7fff33eeabc3 -[NSView(NSInternal) _createLayerAndInitialize]
    @     0x7fff34789a1b -[NSView _updateLayerBackedness]
    @     0x7fff34788453 -[NSView didChangeValueForKey:]
    @     0x7fff33ef6bfa __49-[NSThemeFrame _floatTitlebarAndToolbarFromInit:]_block_invoke
    @     0x7fff3486a619 +[NSAnimationContext runAnimationGroup:]
    @     0x7fff33ef684c -[NSThemeFrame _floatTitlebarAndToolbarFromInit:]
    @     0x7fff33ef4435 -[NSThemeFrame initWithFrame:styleMask:owner:]
    @     0x7fff33ef2ed2 -[NSWindow _commonInitFrame:styleMask:backing:defer:]
    @     0x7fff33ef1703 -[NSWindow _initContent:styleMask:backing:defer:contentView:]
    @     0x7fff33ef11ba -[NSWindow initWithContentRect:styleMask:backing:defer:]
    @        0x1171792a0 -[Window initWithContentRect:styleMask:backing:defer:withManager:]
    @        0x11717c787 FigureManager_init
    @        0x10a94d6b3 wrap_init
    @        0x10a9073cd PyObject_Call
    @        0x10a98662e PyEval_CallObjectWithKeywords
    @        0x10a917672 wrapperdescr_call
    @        0x10a9073cd PyObject_Call
    @        0x10a980f17 PyEval_EvalFrameEx
    @        0x10a97e5b6 PyEval_EvalCodeEx
    @        0x10a924d36 function_call

**Comment by typhoonzero** [comment]
This is more likely to be a python and matplot installation problem.
Close due to low activity, feel free to reopen.
