### ISSUE TITLE
咨询：能否使用paddle完成语音合成任务

### ISSUE THREAD

**Issue by captainwoon** [PaddlePaddle/Paddle#7106]
我们希望使用Paddle来根据某个电台主播的声音（不涉及版权）来训练语音合成模型，从而实现自动新闻播报，不知通过Paddle是否可以实现，如果可以我需要关注社区中哪些资源？

**Comment by jacquesqiao** [comment]
你好，目前Paddle还没有提供语音合成的功能，目前有语音识别，请参考https://github.com/PaddlePaddle/models/tree/develop/deep_speech_2
有相关更新的话，我们会在社区发布，请关注PaddlePaddle社区。

**Comment by luotao1** [comment]
deepspeech2项目已经转移到 https://github.com/PaddlePaddle/DeepSpeech/

**Comment by captainwoon** [comment]
好的，谢谢

**Comment by taoziliu** [comment]
声纹识别的模型有吗
