### ISSUE TITLE
paddle v2 分布式训练配置方法

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#7108]
refs: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/cluster_train_cn.md#%E5%90%AF%E5%8A%A8%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E

trainer_count 单机多线程数量
num_gradient_servers trainer数量
pservers 决定pserver数量

**Comment by typhoonzero** [comment]
PS:

- v1: 指定分布式训练必须的参数包括：`paddle_trainer --is_local=0 --pservers=ip,ip,... --num_gradient_servers=n`
- v2: 用户的python程序中创建`trainer`对象时会传参数`is_local`，参考[trainer.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/trainer.py#L82)

这个文档部分描述的确不是很准确，我更新下～

**Comment by jayhenry** [comment]
启动两个PS，设置num_gradient_servers=2，然后启动三个trainer，trainer_id分别为0,1,2。观察到3个trainer都能正常运行。
请问，这样的情况（trainer个数大于num_gradient_servers）是正常的吗？

**Comment by typhoonzero** [comment]
`num_gradient_servers`参数决定了在同步SGD中，parameter server在每个batch更新参数时，会等待多少个trainer完成了发送。trainer其实没必要区分顺序，有`trainer_id`时因为0号trainer会用做特殊用途（控制[BSP](https://en.wikipedia.org/wiki/Bulk_synchronous_parallel)的barrier），Fluid中会去掉trainer_id的概念。所以在v1中，有比`num_gradient_servers`更多trainer运行，多出来的trainer并不会参与parameter的gradient merging和optimization，实际没起到作用。能运行应该是正常的。

**Comment by jayhenry** [comment]
@typhoonzero 谢谢回答，所以paddle默认的PS是采用BSP的方式同步更新梯度的。那么：
1. 如何设置异步更新呢？
2. 控制不同机器之间差距不大于几轮的SSP，如何设置呢？

**Comment by typhoonzero** [comment]
这两个问题可以参考：http://www.paddlepaddle.org/docs/develop/documentation/en/howto/usage/cmd_parameter/detail_introduction_en.html#async-sgd

**Comment by jayhenry** [comment]
只在pserver启动设置就好吧？像下面这样
```
paddle pserver --async_count=100
```
参数`async_lagged_ratio_min` 含义是什么？ 那些大于`async_count`的梯度以这个概率被丢弃？

**Comment by jayhenry** [comment]
@typhoonzero 尝试在`paddle pserver --async_count=100 `和trainer初始化时`paddle.init(async_count=100, ...)` 加这个参数都报错。应该怎么使用呢？

**Comment by typhoonzero** [comment]
这块文档的确过时了。的确缺少如何配置使用async-SGD的方法，需要补充这里的文档。

先简单说下用法，v1/v2均使用`proto/TrainerConfig.proto`中的配置决定是否是同步还是异步，相关配置包括：

- algorithm：默认就是async_sgd，可以不改
- num_batches_per_send_parameter: 默认是1，即同步sgd
- num_batches_per_get_parameter: 默认是1，即同步sgd

可以看到主要改`num_batches_per_send_parameter`和`num_batches_per_get_parameter `这两个参数来实现。

对于v1，这两个配置可以通过`settings()`调用中直接传入。
对于v2，需要在创建optimizer的时候传，比如：`optimizer = paddle.optimizer.Momentum(momentum=0, num_batches_per_send_parameter=10, num_batches_per_get_parameter=10)`

**Comment by jayhenry** [comment]
@typhoonzero 感谢回答，解释得非常清楚！
另外，我查了下v2的api，默认的是同步的SGD。 FYI
```python
# paddle/trainer_config_helpers/optimizers.py
def settings(batch_size,
             learning_rate=1e-3,
             learning_rate_decay_a=0.,
             learning_rate_decay_b=0.,
             learning_rate_schedule='poly',
             learning_rate_args='',
             learning_method=None,
             regularization=None,
             is_async=False,
             model_average=None,
             gradient_clipping_threshold=None):
```
