### ISSUE TITLE
中英文目录合并

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#712]
As our goal is to make the English and Chinese documentations have the same structure, it seems that we should keep a single directory structure, other than two separated directories `doc` and `doc_cn`?

How about the idea that we have only one directory structure and keep two versions of each file in there, e.g., `doc/demos/ds2/ds2_en.rst` and `doc/demos/ds2/ds2_cn.rst` ?

**Comment by luotao1** [comment]
如果合并成一个目录的话，每个子路径下的index.rst也得分成index_en.rst和index_cn.rst。原先用户http://www.paddlepaddle.org/doc/ui/ 可以自动跳转到 http://www.paddlepaddle.org/doc/ui/index.html ，但合并成一个目录后，不能自动跳转了。

**Comment by wangkuiyi** [comment]
@luotao1 这个是不是让`index_en.rst`就叫`index.rst`就可以了？

如果不行的话，可否用 symbolic link 或者 HTML redirect ？

我在想很多demo虽然文字描述分为中英文两种，但是代码是一份，很多配图也是一份。再考虑未来说不定还会得有日语文档，每种语言一个目录树怕不合适呀。

**Comment by luotao1** [comment]
如果合并到一个目录的话，是不是等所有中文文档修改完后，再进行呢 @gangliao @wangkuiyi

**Comment by wangkuiyi** [comment]
@luotao1 我想应该是的。

另外，我在https://github.com/PaddlePaddle/Paddle/pull/716 这个 issue里更新了 docker_build.rst  。我发现没有对应的中文文档可以update。我写一个，现就放在 doc/.../docker_build_cn.rst 如何？

**Comment by luotao1** [comment]
@wangkuiyi 对应的中文文档在 doc_cn/howto/build_docker_image.rst

**Comment by luotao1** [comment]
已经合并了
