### ISSUE TITLE
Paddle 内进行 point wise product 和 element wise product 运算语法怎么写

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#7129]
RT，在文档内没有找到point wise（点积）和 element wise product的参考语法，请问这两种语法该怎么来写

**Comment by ChunweiYan** [comment]
http://doc.paddlepaddle.org/doc_cn/api/v2/config/layer.html#dotmul-projection

http://doc.paddlepaddle.org/doc_cn/api/v2/config/layer.html#dotmul-operator
