### ISSUE TITLE
本地训练cnn直接core无log排查

### ISSUE THREAD

**Issue by wangyao05** [PaddlePaddle/Paddle#7138]
![2](https://user-images.githubusercontent.com/35025991/34478760-a895939a-efdd-11e7-9212-f7563108876b.JPG)

train数据：
文本，图片tag（为40000+2000+100维度的0/1）, label

构建word_dict和lable_dict都是对的

后面就直接core了
![train](https://user-images.githubusercontent.com/35025991/34478752-97baf100-efdd-11e7-8c2c-131b53821f18.JPG)

**Comment by ChunweiYan** [comment]
will be fixed in https://github.com/PaddlePaddle/Paddle/issues/7142
