### ISSUE TITLE
Semantic Role Labeling demo 中把lstmemory 换成grumemory后model reload出现准确度问题

### ISSUE THREAD

**Issue by hohaxu** [PaddlePaddle/Paddle#714]
这里只训练2个pass，训练时test accuracy 是0.552631. 但是model reload进来以后test accuracy是0.552867. 具体log信息如下：

==training log==
......I1202 14:09:10.074734 20597 TrainerInternal.cpp:182]  Pass=1 Batch=36 samples=5267 AvgCost=105.924 Eval: classification_error_evaluator=0.880542
I1202 14:09:10.419319 20597 Tester.cpp:127]  Test samples=5267 cost=102.758 Eval: classification_error_evaluator=0.552631
I1202 14:09:10.419360 20597 GradientMachine.cpp:116] Saving parameters to ./output/pass-00001
I1202 14:09:10.442358 20597 Util.cpp:230] copy ./db_lstm1.py to ./output/pass-00001

==test log==
[INFO 2016-12-02 14:09:13,940 networks.py:1282] The input order is [word_data, verb_data, ctx_n1_data, ctx_0_data, ctx_p1_data, mark_data, target]
[INFO 2016-12-02 14:09:13,940 networks.py:1289] The output order is [__cost_0__]
I1202 14:09:13.945139 20686 Trainer.cpp:149] trainer: in testing mode
I1202 14:09:13.945157 20686 Trainer.cpp:156] trainer mode: Testing
I1202 14:09:14.009706 20686 PyDataProvider2.cpp:257] loading dataprovider dataprovider::process
I1202 14:09:14.010260 20686 GradientMachine.cpp:127] Loading parameters from ./output/pass-00001
I1202 14:09:15.250123 20686 Tester.cpp:257]  Pass=0 samples=5267 AvgCost=102.774 Eval: classification_error_evaluator=0.552867

试了下其他的RNN model，目前看来只有grumemory会有这个问题。 lstmemory，simple_lstm， simple_gru看起来没有这个问题。这是known issue吗？

training script:    https://github.com/hohaxu/Paddle/blob/develop/demo/semantic_role_labeling/train_1.sh
test script:   https://github.com/hohaxu/Paddle/blob/develop/demo/semantic_role_labeling/test_1.sh

**Comment by luotao1** [comment]
@hohaxu 请问是用CPU跑的，还是GPU跑的？

**Comment by zhangjcqq** [comment]
我看了一下，train 脚本是gpu，test脚本是cpu。有可能是这个导致的。

**Comment by luotao1** [comment]
@hohaxu 你可以试下gpu训练，gpu测试，还有同样的问题么

**Comment by hohaxu** [comment]
谢谢回复！

现在classification error一样了， average cost还有点差别  (4.25896 vs. 4.25968)

＝train log=
I1207 17:40:19.101894 32254 ThreadLocal.cpp:38] thread use undeterministic rand seed:32255
I1207 17:40:19.566210 32219 Tester.cpp:115]  Test samples=148647 cost=4.25896 Eval: classification_error_evaluator=0.573722
I1207 17:40:19.566277 32219 GradientMachine.cpp:113] Saving parameters to ./output/pass-00000
I1207 17:40:19.591164 32219 Util.cpp:233] copy ./db_lstm1.py to ./output/pass-00000

=test log=
I1207 17:40:27.017122 32341 Tester.cpp:245]  Pass=0 samples=148647 AvgCost=4.25968 Eval: classification_error_evaluator=0.573722

**Comment by hedaoyuan** [comment]
cost=4.25896 实际是这些`Test samples=148647` 的一个求和，train和test的时候对这些samples的计算顺序不一定一样。如果想比较的话，可以设置`Test samples=1`来看。

**Comment by hohaxu** [comment]
Thanks！

现在既然classification error一样，先close这个issue了。以后有时间再继续测试 ：）
