### ISSUE TITLE
paddlepaddle 使用mpi训练batch模型报错Connection timed out

### ISSUE THREAD

**Issue by bigshipbig** [PaddlePaddle/Paddle#7146]
![image](https://user-images.githubusercontent.com/15210529/34483419-40f98eaa-eff9-11e7-9e4c1008c9dd6884.png)
![image](https://user-images.githubusercontent.com/15210529/34483421-42564d42-eff9-11e7-8fff-9a3b4c4ff7fd.png)

**Comment by ChunweiYan** [comment]
怀疑是集群问题，不知道你能否看出问题 @typhoonzero

**Comment by bigshipbig** [comment]
@ChunweiYan 在两个集群上都尝试过，在nmg上尝试过很多次大概跑几个batch就会挂掉，在lvliang上跑了200个batch左右挂掉的

**Comment by typhoonzero** [comment]
请参考：http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/cluster/index_cn.html 找到最早的报错日志，供排查参考。

**Comment by bigshipbig** [comment]
@typhoonzero 在server.log找到的最早的报错
![image](https://user-images.githubusercontent.com/15210529/34508291-994440bc-f078-11e7-953e-4301e121ade0.png)
参考文档说
![image](https://user-images.githubusercontent.com/15210529/34508312-d2b30572-f078-11e7-82b2-7e6b292e1705.png)
可以确定是网络通信的问题吗？
似乎目前提交的时候已经添加了这个参数
![image](https://user-images.githubusercontent.com/15210529/34508384-9c24f7f8-f079-11e7-8418-bed3fdbbdeaa.png)

**Comment by typhoonzero** [comment]
如果是端口占用，一般会在`server.log`找到类似`Address already in use`之类的报错。建议检查下`train.log`最早的报错，是否存在python配置问题或者FPE之类的问题。

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如果需继续讨论再打开
