### ISSUE TITLE
Questions regarding structure of Paddle

### ISSUE THREAD

**Issue by KareemSalah** [PaddlePaddle/Paddle#715]
Hello,
I was having some questions regarding the structure of Paddle core and it's Python API, I'm working on a project and I may contribute, the problem is .. I don't know where/who to ask those questions.
Suggestions? #

**Comment by wangkuiyi** [comment]
Thank you for your interest with Paddle.

The API documents covering both C++ and Python source code can be found here: http://www.paddlepaddle.org/doc/source/index.html

I am building a browsable (HTML) version of the Paddle core (C++ source code) into Docker images:

- https://github.com/PaddlePaddle/Paddle/pull/716
- https://github.com/wangkuiyi/Paddle/pull/2

I usually find the one who might help me by looking up the Git blame, e.g., https://github.com/PaddlePaddle/Paddle/blame/develop/paddle/gserver/layers/CTCLayer.h

**Comment by wangkuiyi** [comment]
@reyoung Can we enable the build of documents about Python APIs in the Dockerfile?

**Comment by reyoung** [comment]
Paddle is not a Python Library currently. A python interpreter was embedded into Paddle process just for parsing [neural network configuration](http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/index.html) and [providing data](http://www.paddlepaddle.org/doc/ui/data_provider/pydataprovider2.html).

Making Paddle as a standard python library is under developing. It currently just used for [model inference](http://www.paddlepaddle.org/doc/ui/predict/swig_py_paddle_en.html). This API is under developing now and in flux. It lacks documentation now. But you can reference the [header](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/PaddleAPI.h), and it is well commented. You can also invoke `help` method after importing `py_paddle` API, like

```python
from py_paddle import swig_paddle as api

help(api)
help(api.BlahBlah)
```

**Comment by KareemSalah** [comment]
Thank you all for your help.
@reyoung We're build an API for paddle in another language other than Python, the only problem we had is that we didn't understand the process (we did after a long time) due to lack of documentation, it would be very helpful if you provide us with some thoughts and suggestions and maybe advice on our project, currently we're studying swig_paddle and we're up to developing another API similar to that in swig_paddle, apparently we're kinda shocked after realizing that the API is not complete, What do you think we should do?
May we can help completing the API? :)

**Comment by reyoung** [comment]
So which language binding you want to develop?  Could we just expose a `C-API` for you, then just use other language invoke C-API? We notice that `swig` is not a standard way for every language and may be only provide C-API is better.

Also, could you provide which level of API you want to use mostly? We could adjust our priority.

In Paddle, maybe contain several levels here:

```text
+-----------------------------------+
|    Trainer                        |
+-----------------------------------+
|    ParameterServer/Client         |
+-----------------------------------+
|    NeuralNetwork/GradientMachine  |
+-----------------------------------+
|    Layer                          |
+-----------------------------------+
|    Matrix&Vector                  |
+-----------------------------------+
```

* Matrix & Vector: Can do operations for the matrix.
* Layer:  Can do forward/backward for each layer in same CPU/GPU
* NeuralNetwork: Can forward/backward for one neural network, with multiple CPU/GPU enabled.
* ParameterServer/Client: Communication about multiple nodes.
* Trainer:  API about Train one mini-batch, train one pass.

**Comment by KareemSalah** [comment]
Well .. We're building an API for Julia language, Julia has a very promising performance and many data scientists are saying that it's highly probable to be the next favorite language for deep learning and data science.

The cool thing about Julia is that you can call C/C++ code almost directly without glue code, and it's performance is quit interesting, have a little research on that and you'll better understand it.

Tensor flow (I'm sure you know it) is also in C++/Python, people have started implementing an interface for it in Julia, meanwhile we understand how powerful and important Paddle is, so we decided to build the same interface for Paddle.

 Exposing a C-API would be very helpful for us and it would make it very easy for us to directly start implementing the Julia API using that C-API.

We haven't decided yet what level of API we would like to build, our first goal was to study Paddle's C++ core and afterwards decide up on that, but of course we would like to know professional's thought, opinions and ideas on what API level and on all that process.

**Comment by reyoung** [comment]
Thank you for your response. We will discuss them in next week, and hope will give you a roadmap or plan for it, and then we will give another issue to tracking this progress.

BTW, @wangkuiyi It seems that the C-API is the best way we expose our API.

**Comment by wangkuiyi** [comment]
@reyoung @KareemSalah Yes. We do have a plan to expose C-API of Paddle. That would be the core of our work of improving Paddle API.

@KareemSalah Thank you for your interest with Paddle. We would be glad to see a Paddle API for Julia. Please let us know if there is anything we should do to support your work.

**Comment by reyoung** [comment]
@KareemSalah you can use #849 to track the latest progress about it. And if there are any comments/questions, please do not hesitate to ask.
