### ISSUE TITLE
Paddle Support Focal Loss?

### ISSUE THREAD

**Issue by fantasycheung** [PaddlePaddle/Paddle#7154]
Cannot find content or API about [Focal Loss](https://arxiv.org/abs/1708.02002) in Paddle‘s official web and github,  does paddle support it?
If not, how could I implement it? Thanks

**Comment by sweetsky0901** [comment]
是的，现在还没有支持。

**Comment by fantasycheung** [comment]
好的，期待后续新版本能支持。
