### ISSUE TITLE
unify REGISTER_OP and REGISTER_OPERATOR

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#7158]
## background
currently, we have two macro REGISTER_OP and REGISTER_OPERATOR to register an operator to our framework, it's confusing, we should unify these two interfaces.

## history
firstly, we have REGISTER_OP, the interface is
```cpp
#define REGISTER_OP(op_type, op_class, op_maker_class, grad_op_type, grad_op_class) 
```
There are several reasons why this interface cannot meet our requirement now.
- This interface directly registers a grad_op_class for one op_type, it cannot support to use multiple ops to construct the backward ops for one forward op. So we have [grad_op_desc_maker](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/grad_op_desc_maker.h#L33) and need to register this instead of one grad_op_class)
- We split Infershape from op_with_kernel and add [InferShapeBase](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_info.h#L28), it also needs to be registered to the framework.

`REGISTER_OPERATOR` is used to do this:
```cpp
/*
  The variadic arguments should be class types derived from one of the
  following classes:
    OpProtoAndCheckerMaker
    GradOpDescMakerBase
    VarTypeInference
    InferShapeBase
*/
#define REGISTER_OPERATOR(op_type, op_class, ...)
```
the new REGISTER_OPERATOR support to register GradOpDescMakerBase and InferShapeBase.

the REGISTER_OP now is just a proxy interface that will call REGISTER_OPERATOR at last, it does two things to call REGISTER_OPERATOR
- register grad_op_type use REGISTER_OPERATOR.
- generate one DefaultGradOpDescMaker for this op_type.

## things need to do to unify the interface
1. implement all InferShape in op_with_kernel with InferShapeBase.
2. change `virtual void InferShape(InferShapeContext* ctx)` to a `final` interface.
3. implement a macro to easily define a default GradOpDescMaker for the ops that use REGISTER_OP to register.
4. remove REGISTER_OP in op_registry.h.

**Comment by luotao1** [comment]
Can you give an op example with the correct usage of `REGISTER_OPERATOR `?

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/mul_op.cc#L159 is a good example.

**Comment by tonyyang-svail** [comment]
@luotao1 @jacquesqiao Is there any follow up on this issue? If not, I will take a look at it.

**Comment by luotao1** [comment]
@tonyyang-svail There is no any follow up on this issue. Thanks very much if you could take a look at it.

**Comment by tonyyang-svail** [comment]
hi @luotao1, I don't think there is any technical difficulty on removing `REGISTER_OP`.
```
REGISTER_OP(crop, ops::CropOp, ops::CropOpMaker, crop_grad, ops::CropOpGrad);
```
Becomes
```
REGISTER_OPERATOR(crop, ops::CropOp, ops::CropOpMaker,
                  paddle::framework::DefaultGradOpDescMaker<true>);
REGISTER_OPERATOR(crop_grad, ops::CropOpGrad);
```
