### ISSUE TITLE
来人指导一下

### ISSUE THREAD

**Issue by balabalalilili** [PaddlePaddle/Paddle#717]
![2016-12-04 19-20-37](https://cloud.githubusercontent.com/assets/23418049/20866056/e2bcc676-ba5d-11e6-98b7-7bd045dde686.png)
 这个错误该怎么解决？
新人不太会 最好清楚一点 谢谢！！

**Comment by qingqing01** [comment]
你能贴一下你的机器(GPU)版本信息、以及你使用的Paddle版本吗？

**Comment by balabalalilili** [comment]
![2016-12-05 11-38-11](https://cloud.githubusercontent.com/assets/23418049/20873207/2ce6eb32-bae0-11e6-8bf5-b277a7cc09c5.png)
![2016-12-05 11-42-29](https://cloud.githubusercontent.com/assets/23418049/20873208/2ce77f0c-bae0-11e6-8909-e111286b0f12.png)
@qingqing01 谢谢你了

**Comment by luotao1** [comment]
paddle version下面显示with_gpu=off，说明没有gpu。然而你的demo是跑在gpu上，所以会出错。

**Comment by qingqing01** [comment]
@balabalalilili 如果你的机器不支持GPU， 可以切换使用CPU训练，将 `train.sh`中的 `--use_gpu=1`改为`--use_gpu=0`即可。
