### ISSUE TITLE
全连接层参数复用问题

### ISSUE THREAD

**Issue by wzmsltw** [PaddlePaddle/Paddle#7177]
你好，我在网络中对于多个vector希望使用共享的全连接层，如下所示：

`x1 = paddle.layer.data(name='x1', type=paddle.data_type.dense_vector(13))`
`x2 = paddle.layer.data(name='x2', type=paddle.data_type.dense_vector(13))`
`y1 = paddle.layer.fc(name="fc",input=x1, size=64,act=paddle.activation.Linear())`
`y2 = paddle.layer.fc(name="fc",input=x2, size=128,act=paddle.activation.Linear())`

但我不确定这样设置，两个全连接操作在训练中是否是共享参数的？如果不是，那应该如何共享参数呢？

**Comment by huiyingl** [comment]
这个是layer的名字相同，参数不是复用的。要参数属性（paddle.attr.Param）里的名字相同，例如
```
emb_para = paddle.attr.Param(name='emb', initial_std=0, is_static=True)
emb1 = paddle.layer.embedding(size=emb_dim, input=s1, param_attr=emb_para)
emb2 = paddle.layer.embedding(size=emb_dim, input=s2, param_attr=emb_para)
```

**Comment by wzmsltw** [comment]
明白了，感谢回答
