### ISSUE TITLE
使用自定义图片数据集时,报错 "date -d @1515036867" if you are using GNU date

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7185]
* 在使用自定义图片数据集训练时,在训练到一半是突然报错,错误信息如下:
```
Pass 0, Batch 0, Cost 14.597490, {'classification_error_evaluator': 0.7265625}

Pass 0, Batch 1, Cost 39.000000, {'classification_error_evaluator': 0.609375}

Pass 0, Batch 2, Cost 36.000000, {'classification_error_evaluator': 0.5625}
Thread [140661301901056] Forwarding __conv_1__, 
*** Aborted at 1515036867 (unix time) try "date -d @1515036867" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGFPE (@0x7fee67489187) received by PID 18909 (TID 0x7fee42eef700) from PID 1732809095; stack trace: ***

    @     0x7fee82e4d390 (unknown)

    @     0x7fee67489187 sgemm_kernel_NEHALEM
```
* 这是什么原因,我图片的命名是用uuid的没有用到时间毫秒,部分数据如下:
```
../data/image/fee16631-f096-11e7-aff8-2cd05afbe631.png	1
../data/image/fee16632-f096-11e7-aff8-2cd05afbe631.png	1
../data/image/fee16633-f096-11e7-aff8-2cd05afbe631.png	1
../data/image/fee16634-f096-11e7-aff8-2cd05afbe631.png	1
```
* 读取方式如下:
```
    train_reader = paddle.batch(
        paddle.reader.shuffle(
            reader.train_reader('../data/trainer.list'),
            buf_size=1000),
        batch_size=BATCH_SIZE)
```
  * 该项目的GitHub地址：[https://github.com/yeyupiaoling/TestCustomData](https://github.com/yeyupiaoling/TestCustomData)

**Comment by yeyupiaoling** [comment]
加了BN层和Dropout层好像就没有出现问题了

**Comment by qingqing01** [comment]
> *** SIGFPE (@0x7fee67489187) received by PID 18909 (TID 0x7fee42eef700) from PID 1732809095; stack trace: ***

[SIGFPE](https://zh.wikipedia.org/wiki/SIGFPE)是浮点异常，出现浮点异常一般会通过调节超参数，例如调小学习率，加正则等；对数据或特征归一化；加gradient clipping等来抑制。 所以你上面加BN尝试是合理吧。

**Comment by yeyupiaoling** [comment]
@qingqing01 
明白，谢谢青青姐姐

**Comment by liyutg** [comment]
*** Aborted at 1555033639 (unix time) try "date -d @1555033639" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x0) received by PID 22659 (TID 0x7f0f01560740) from PID 0; stack trace: ***
    @     0x7f0f00a55330 (unknown)
    @                0x0 (unknown)
bash: 行 1: 22659 段错误               (核心已转储) env "PYCHARM_MATPLOTLIB_PORT"="59714" "PYT


代码段
![image](https://user-images.githubusercontent.com/23010064/56006825-0ca8f900-5d09-11e9-9297-eb28aec86fad.png)

使用CPU没报异常，GPU报异常
