### ISSUE TITLE
There exists redundant output in sequence_pool operator 

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7211]
`max_index` is invisible for outside, so need set `max_index.stop_gradient = True` to avoid core dump.
https://github.com/PaddlePaddle/Paddle/blob/6f347faafeeaebe237c012f8d4233bda0112c80b/python/paddle/v2/fluid/layers/nn.py#L781

**Comment by luotao1** [comment]
Can you paste the detail information of core dump?
