### ISSUE TITLE
Should output of sequence_pool be LoDTensor with LoD?

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7212]
Currently, output of sequence_pool is a LoDTensor without LoD. However, the input is LoDTensor with LoD. Should we add LoD to output of sequence_pool.

**Comment by luotao1** [comment]
I think the output of sequence_pool (where input's LoDLevel=1) is Tensor, since the output is not a sequence .

**Comment by pkuyym** [comment]
Since the output is a LoDTensor object, I think add LoD info has no side effects. In some situation like decoder_boot in seq2seq, adding LoaD info makes things easier.

**Comment by lcy-seso** [comment]
I agree conceptually, a Tensor (here specifically means a non-sequence) equals to a LoDTensor (here specifically means a sequence)  with the LoDTensor fixed to be 1 for each sequence in the batch. But my concern is this is not a default setting for Fluid operators. Will this potentially affect the logic of other operators? But why not to enhance the `ReorderLoDTensorByRankTableOp` Is there any problem?

`sequece_pool` degrade a sequence into a non-sequence is frequently used in NLP task in previous PaddlePaddle. This is because, in many NLP task, there always requires encoding the variable-length sequences with fixed length vectors. Conceptually, in this situation, after pooling (the stride is length of the sequence) the sequence becomes a non-sequence.

**Comment by pkuyym** [comment]
In my opinion, `ReorderLoDTensorByRankTableOp` requires sequence input, so the input LoDTensor should contains LoD. If make the operator accepts common Tensor without LoD, it may confuse users.

**Comment by pkuyym** [comment]
@luotao1 @lcy-seso For `sequence_pool`, I think we can expose a attribute to users to decide whether inherit LoD info for output.

**Comment by guoshengCS** [comment]
I edit `ReorderLoDTensorByRankTableOp` in this way:
```
  std::vector<AbsoluteRankTableItem> GetAbsoluteOffsetAndLengthByLoDRankTable(
      const framework::LoDTensor &x) const {
    std::vector<AbsoluteRankTableItem> absolute_table;

    if (x.lod().empty()) {
      // For Tensor without lod, such as the output of sequence_pool_op
      size_t size = x.dims()[0];
      absolute_table.reserve(size);
      for (size_t i = 0; i < size; ++i) {
        absolute_table.emplace_back();
        absolute_table.back().length = 1;
        absolute_table.back().offset = i;
      }
    } else {
      size_t level = 0;
      size_t size = x.lod()[level].size();

      for (size_t i = 0; i < size - 1; ++i) {
        auto lod_offset =
            framework::GetSubLoDAndAbsoluteOffset(x.lod(), i, i + 1, level);

        auto &offset = lod_offset.second;

        absolute_table.emplace_back();
        absolute_table.back().length = offset.second - offset.first;
        absolute_table.back().offset = offset.first;
        absolute_table.back().lod = lod_offset.first;
      }
    }

    return absolute_table;
  }
```

**Comment by luotao1** [comment]
> I think we can expose an attribute to users to decide whether inherit LoD info for output

@pkuyym This will lead users more confused, and I agree with @guoshengCS to enhance the `ReorderLoDTensorByRankTableOp`, but not to modify the `sequence_pool`.

**Comment by reyoung** [comment]
I also agree with @luotao1 and @guoshengCS . `ReorderLoDTensorByRankTable` should be enhanced.

**Comment by reyoung** [comment]
BTW. There is a related question, 

Is A LoDTensor without LoD information as same as A LoDTensor with LoD information, the length of sequences are all one.

For example, is LoDTensor
```
[[0, 0, 0],
[1, 1, 1],
[2, 2, 2]]
```
as same as 
```
[[0, 0, 0],
[1, 1, 1],
[2, 2, 2]]

LoD=[[0, 1, 2, 3]]
```
?

**Comment by pkuyym** [comment]
@guoshengCS Please add corresponding test cases.

**Comment by pkuyym** [comment]
@reyoung If we only keep LoDTensor, I think LoD being empty equals all length of sequences being ones makes sense.

**Comment by lcy-seso** [comment]
I do not prefer to modify the `sequence_pool` operator to let the user decide whether to inherit the LoD information.  Enhance ReorderLoDTensorByRankTableOp is reasonable. I think this is not confusing.

**Comment by pkuyym** [comment]
Already fixed by https://github.com/PaddlePaddle/Paddle/pull/7251
