### ISSUE TITLE
有没有使用自定义图片数据集做图片分类的demo,在这个问题一直错误百出

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7215]
* 我想使用paddlepaddle做一个验证码识别和蔬菜分类的程序,但是在自定义数据集上一直出问题,程序要不跑不了,或者训练的model不能正常预测
## 为此提很多的问题,都没有彻底解决问题
1. 使用自定义图片数据集时,报错 "date -d @1515036867" if you are using GNU date #7185
2. paddle.v2.image.load_and_transform方法的参数问题 #7175
3. 在自定义图片数据集的时候，要怎么处理这些图片呢 #7062

**Comment by zishuaiz** [comment]
pytorch和tf有答案[手动微笑]
在pd文档还没有写完整前，最好还是别跳坑

**Comment by yeyupiaoling** [comment]
@zishuaiz 坑我跳了不少了，但是最近一直在搞paddlepaddle，我不想那么轻易放弃了

**Comment by yeyupiaoling** [comment]
根据我这几天的折腾,大概发现了问题说在
1. 我一开始是使用book的第三章的vgg模型,那个模型多了一个BN层,加上这个层之后,trainer_cost是收敛的,但是Test_cost是上升的,具体问题在: #7512
2. 图片可以不用预处理,因为使用`reader.py`这个可以帮我们处理图片,但是它不是使用整个图片,而是随机裁剪,如: #7510
3. 还有因为之前的数据太少了,没办法正常训练
4.最后剩下的问题是,我使用[https://github.com/PaddlePaddle/models/tree/develop/image_classification](https://github.com/PaddlePaddle/models/tree/develop/image_classification)这里的代码,vgg是一样有的,就还是错误 #7185
