### ISSUE TITLE
Bug in backward.py

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7216]
Y --> Out
https://github.com/PaddlePaddle/Paddle/blob/6f347faafeeaebe237c012f8d4233bda0112c80b/python/paddle/v2/fluid/backward.py#L165

**Comment by lcy-seso** [comment]
I do not look into details of this bug. Does this mean there are some constraints on the name of output tensor of an operator?

**Comment by pkuyym** [comment]
The backward logic is refactored by jiayi, and some var doesn't need grad, however we need add a `fill_zeros_like` operator to pass zeros, the name should be `Out` here.

**Comment by lcy-seso** [comment]
I see, thank you.
