### ISSUE TITLE
【demo】semantic_role_labeling中的脚本，缺少可执行权限

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#722]
【demo】semantic_role_labeling中的脚本，缺少可执行权限。
 
drwxr-xr-x  7 baidu  staff   238B 12  5 13:29 data
-rw-r--r--  1 baidu  staff   2.1K 12  5 13:29 dataprovider.py
-rw-r--r--  1 baidu  staff   4.2K 12  5 13:29 db_lstm.py
-rw-r--r--  1 baidu  staff   5.3K 12  5 13:29 predict.py
-rw-r--r--  1 baidu  staff   1.1K 12  5 13:29 predict.sh
-rw-r--r--  1 baidu  staff   1.5K 11 25 16:13 run.sh
-rw-r--r--  1 baidu  staff   1.1K 12  5 13:29 test.sh
-rw-r--r--  1 baidu  staff   863B 12  5 13:29 train.sh

**Comment by qingqing01** [comment]
这个问题我记得 @zhangjcqq fix过，麻烦 @zhangjcqq  再看下吧~

**Comment by backyes** [comment]
https://github.com/PaddlePaddle/Paddle/issues/705

**Comment by beckett1124** [comment]
在semantic_role_labeling的data目录下的脚本，依然存在没有权限的脚本

root@bc7d3bf462bc:~/paddle/demo/semantic_role_labeling/data# ll
total 32
drwxr-xr-x  2 root root 4096 Dec  6 08:00 ./
drwxr-xr-x 11 root root 4096 Dec  6 14:17 ../
-rw-r--r--  1 root root 2741 Dec  6 08:00 extract_dict_feature.py
-rw-r--r--  1 root root 4460 Dec  6 08:00 extract_pairs.py
-rw-r--r--  1 root root 1368 Dec  6 08:00 get_data.sh
-rw-r--r--  1 root root   15 Dec  6 08:00 test.list
-rw-r--r--  1 root root   15 Dec  6 08:00 train.list

**Comment by luotao1** [comment]
@beckett1124 在develop分支上，你们现在测试的是哪个分支呢？

**Comment by beckett1124** [comment]
developer分支

**Comment by backyes** [comment]
这个问题已经fix #725

**Comment by beckett1124** [comment]
是data目录下的下载数据的脚本。
![image](https://cloud.githubusercontent.com/assets/12882811/20952801/ea5693e0-bc69-11e6-8cfd-381845e52466.png)

drwxr-xr-x 2 root root 4096 Dec 6 08:00 ./
drwxr-xr-x 11 root root 4096 Dec 6 14:17 ../
-rw-r--r-- 1 root root 2741 Dec 6 08:00 extract_dict_feature.py
-rw-r--r-- 1 root root 4460 Dec 6 08:00 extract_pairs.py
-rw-r--r-- 1 root root 1368 Dec 6 08:00 get_data.sh
-rw-r--r-- 1 root root 15 Dec 6 08:00 test.list
-rw-r--r-- 1 root root 15 Dec 6 08:00 train.list
