### ISSUE TITLE
Get rid of pickle for Storing format of inference

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#7221]
Currently Pickle is used in fluid.io.save_inference_model to save inference protobuf string and feed and fetch var names.

However it is not well supported for the c++ side to parse the serializing format provided by pickle. 

To make the inference API concise, we need to get rid of pickle.

**Comment by abhinavarora** [comment]
One strategy that I am exploring right now is to create a new ProtoBuf called InferenceDesc that can incorporate the ProgramDesc and Model Params. This is a related issue for that https://github.com/PaddlePaddle/Paddle/issues/7328

**Comment by kavyasrinet** [comment]
I added a proposal in the same issue to avoid duplication, since I started working on the same issue (#7328) as well. @abhinavarora and I can work together on this I guess.
