### ISSUE TITLE
Survey Pytorch for Storing format

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#7224]
Pytorch does not have a special format for storing trained models. Instead, most Pytorch developers rely on the in-built [Serialization tools](http://pytorch.org/docs/master/torch.html#serialization) of Torch for storing and loading models.

### PyTorch Serialization Approaches

There are two main approaches for serializing and restoring models in PyTorch. These are as follows:

1. **Save and load only the Model Parameters**: This approach only saves and restores the parameters of the deep learning model/ This is the recommended way to store and load deep learning models in PyTorch. 
Saving the model looks like the follows:
`torch.save(the_model.state_dict(), PATH)`
Reloading can be done as follows:
```
the_model = TheModelClass(*args, **kwargs)
the_model.load_state_dict(torch.load(PATH))
```

2. **Save and Load entire model**:  This approach saves and then loads the entire machine learning model **with** the model parameters. This is not a recommended way of storing in PyTorch because the serialized data is bound to the specific classes and the exact directory structure used. Hence, it can break in various ways when used in other projects, or after some serious refactoring. 
Saving the model looks like the follows:
`torch.save(the_model, PATH)`
Reloading the model looks like the follows:
`the_model = torch.load(PATH)`

### PyTorch Serialization Semantics

The PyTorch serialization module provides a wrapper on top f Python Pickle to store and load PyTorch objects. It exposes two simple methods for serializing and deserializing objects in PyTorch:

1. `torch.save(obj, f, pickle_module=<module 'pickle' from '/opt/conda/lib/python3.6/pickle.py'>, pickle_protocol=2)`:  This method simply saves an object to a disk file and does nothing fancy. 

2. `torch.load(f, map_location=None, pickle_module=<module 'pickle' from '/opt/conda/lib/python3.6/pickle.py'>)`:  This method loads an object stored with the `torch.save` method.  This uses Python's unpickling facilities but also treats storages, which underlie tensors specifically. Tensors are first deserialized on the CPU and are then moved to the device they were saved from. If the runtime cannot find the specified device, then an exception is raised. The API also supports dynamic re-mapping of devices to an alternative set of devices.

**Comment by Xreki** [comment]
Just list some details of Fluid here.
There also are some serialization methods for LoDTensor, [SerializeToStream](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.cc#L160) and [DeserializeFromStream](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.cc#L187). In Fluid, `Parameter`s are load and saved by `load_op` and `save_op`. The two operators call the two serialization methods and save/load Parameters to/from separate files. The filename is specified as an attribute of `save_op` and `load_op`.
