### ISSUE TITLE
Is there a matching function for vectors inside LSTM sequence in paddle? 比较LSTM seq里面的向量

### ISSUE THREAD

**Issue by huiyingl** [PaddlePaddle/Paddle#7226]
Got LSTM full sequence representation for a pair of input, and want to compare the vector in each time step of one LSTM sequence against each vector of each time step of the other Lstm sequence. Is it possible in Paddle?
想要把一个lstm sequence中的每一个向量和另一个lstm seq中的每一个向量比较(e.g.算cosine)，请问paddle里有没有例子/可以实现？ 和tf.map_fn类似。
谢谢！

**Comment by will-am** [comment]
paddle目前貌似还不支持这个操作

**Comment by huiyingl** [comment]
@will-am 用cos_sim可能吗？ 如果我把第一个lstm的最后一步和第二个lstm的所有步vector比较
```
v1 = last_seq(simple_lstm(inp, size))
v2s = simple_lstm(inp1,size))
cos_sim(v1, v2s)
```
如果这样没问题的话...
还有就是按照cos_sim的文档，是第一个参数和第二个参数的所有列进行比较。是不是还得把v2s转过来？
谢谢！

**Comment by will-am** [comment]
cos_sim应该不支持输入是个sequence，所以只能实现第一个lstm的最后一步和第二个lstm的最后一步比较，应该不能算第一个lstm的最后一步和第二个lstm的所有步比较。

**Comment by huiyingl** [comment]
@will-am 了解，谢谢～
我的确是需要把第一个lstm的最后一步（或者每步）vec和另一个lstm的所有步都比一下……

**Comment by huiyingl** [comment]
@will-am 试了下cos_sim应该是支持sequence。把 last_seq(lstm_1) expand 到lstm_2的形状：
lstm1_exp = layer.expand(last_seq(lstm_1), expand_as=lstm2)
然后
cos_sim(lstm1_exp, lstm2)
是可以得到输出的～～

**Comment by huiyingl** [comment]
@will-am 以及另外一个想法不知道可行不：
把第二个lstm的output放进recurrent_group, 然后把第一个lstm的last_seq作为StaticInput也放进去，在step function得到拆解后的第二个lstm单步向量后和第一个lstm的last_seq比较。

**Comment by will-am** [comment]
原来cos_sim还支持sequence~

后面的这个想法应该可以~
