### ISSUE TITLE
mpi训练数据输入方式

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#7230]
我们这边的日志存储于HDFS，都是按照日期，小时分割好的，多级目录结构。但是现在paddle只能支持单一目录下，文件以part-XXX方式分割好。所以每次都要做一个目录和文件的重新组织，才能输入到paddle进行训练，这一步耗费了多余的空间和时间，希望paddle能支持多级目录作为输入，文件名最好也不要强制某种格式。

**Comment by typhoonzero** [comment]
可以参考 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/reader/decorator.py#L337 直接读取，就可以用python代码控制，而且不会下载数据也不会浪费空间。
