### ISSUE TITLE
Compiling fluid inference library

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7231]
For compiling fluid inference static and shared library, there are two questions:
1. Do we need an option like `WITH_C_API`?
2. Can we build a single static and shared library at first, and then spill them?

**Comment by Xreki** [comment]
> Do we need an option like WITH_C_API?

I think we don't need. It should be always built.

> Can we build a single static and shared library at first, and then spill them?

It's OK. Please note that the static library should not contain any binary code of third-party libraries.

**Comment by luotao1** [comment]
TODO List
- [ ] Compile one static library, which should not contain any binary code of third-party libraries.
- [ ] Compile one shared library.
- [ ] Dismantle one library into several.
- [ ] Make Install.

**Comment by wangkuiyi** [comment]
I have a question: do we have to *install* header files and libraries into a special directory structure? What would be the problem for our users to include/link to them if we leave them where they were (in the source directory and the build directory)?
