### ISSUE TITLE
获取 paramters 随机出错

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7235]
代码
https://github.com/liuhuiCNN/paddle_issues/blob/master/paddle_issue_0.py
运行的话随机出错，求原因。

问题：
1 paddle的网络像tensorflow那样，构建网络后需要feed吗？
2 上面代码中获取paddle的参数为什么随机出错？跟随机的权重大小有关吗？

**Comment by will-am** [comment]
还需要定义trainer，paddle中的参数是在trainer中初始化的。可以参考[paddle book](http://www.paddlepaddle.org/docs/develop/book/02.recognize_digits/index.html)中的例子。

**Comment by liuhuiCNN** [comment]
请问 addle中的参数是在trainer中初始化的 的相关代码位置在哪？我目前还没找到。谢谢！

**Comment by will-am** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/parameter/Parameter.cpp

**Comment by liuhuiCNN** [comment]
@will-am 谢谢！
