### ISSUE TITLE
API文档小问题

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7238]
> 不知道提在这里好不好，看paddlepaddle.org 里面是说提到这里

问题：

http://paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/attr.html 下的 paddle.v2.attr.ParameterAttribute ， `initiliazer`的定义重复了，此外少了`update_hooks`的解释

**Comment by will-am** [comment]
非常感谢，我修复下这个文档

**Comment by memeda** [comment]
我理解咱们的文档应该是根据代码自动生成的吧？但是看起来又有些不像... 如果不是，这个维护成本太大了....

**Comment by will-am** [comment]
paddle的文档都是根据代码中的注释自动生成的~

**Comment by memeda** [comment]
哦哦哦，好的，幸苦啦~
