### ISSUE TITLE
nvcc fatal: unknown option '-expt-relaxed-constexpr'?

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/Paddle#7243]
CUDA IS 7.0 gcc is 4.8

**Comment by will-am** [comment]
To compile paddle from source, you can refer to http://www.paddlepaddle.org/docs/develop/documentation/en/getstarted/build_and_install/build_from_source_en.html.

If you do not want to use docker, you can download compile as follows:

```bash
cd Paddle
mkdir build
cd build

cmake .. -DWITH_GPU=true -DWITH_AVX=true -DWITH_MKLDNN=true -DWITH_MKLML=true -DWITH_DSO=true -DWITH_TESTING=true -DWITH_SWIG_PY=true  -DCUDNN_ROOT=/someplace/cudnn_v5/cuda -DCMAKE_INSTALL_PREFIX=/someplace

make

make install

```

**Comment by qingqing01** [comment]
The `expt-relaxed-constexpr` is used to suppress Eigen warnings.  It is used here : https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/cuda.cmake#L175 .  It works on the environment of CentOS 6.3, CUDA 7.0 and GCC 4.8.  What's your system?
