### ISSUE TITLE
variant_caster_visitor is redefined!

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/Paddle#7245]
pybind/protobuf.cc
extern_pybind/.../stl.h:291

**Comment by will-am** [comment]
To compile paddle from source, you can refer to http://www.paddlepaddle.org/docs/develop/documentation/en/getstarted/build_and_install/build_from_source_en.html.

If you do not want to use docker, you can download compile as follows:

```bash
cd Paddle
mkdir build
cd build

cmake .. -DWITH_GPU=true -DWITH_AVX=true -DWITH_MKLDNN=true -DWITH_MKLML=true -DWITH_DSO=true -DWITH_TESTING=true -DWITH_SWIG_PY=true  -DCUDNN_ROOT=/someplace/cudnn_v5/cuda -DCMAKE_INSTALL_PREFIX=/someplace

make

make install

```
