### ISSUE TITLE
WHY new version of paddle is so hard-to-use!!! compared with the v1.

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/Paddle#7248]
like title said.

**Comment by will-am** [comment]
For the usage of v2, you can refer to http://www.paddlepaddle.org/docs/develop/book/01.fit_a_line/index.html and https://github.com/PaddlePaddle/models.

To install the new paddlepaddle, you can simply using `pip install paddlepaddle`.

**Comment by huiyingl** [comment]
I think you just get used to v1...
