### ISSUE TITLE
mkdir: can not create dir '~/.config/paddle': permission denied. HOW to set this with user directory??

### ISSUE THREAD

**Issue by lqniunjunlper** [PaddlePaddle/Paddle#7252]
mkdir: can not create dir '~/.config/paddle': permission denied. 

HOW and WHERE to set this with user-defined directory??

**Comment by lqniunjunlper** [comment]
@will-am

**Comment by luotao1** [comment]
Can you add more information about all your issue? We are hard to know what's problem you meet. Current information is too little.

**Comment by lqniunjunlper** [comment]
After installed paddle, when i was running the  executable paddle program on command line, this error occurred. 
Maybe i need to set $HOME environment parameter?
How to modify this?

**Comment by will-am** [comment]
Did you install paddle by `pip` or compile from source? Could you provide more info on your paddle program? How did you invoke the paddle program?

You can run this [example](https://github.com/PaddlePaddle/book/tree/develop/01.fit_a_line) first to test your installation of paddle. If this runs without error, your installation is all right.

**Comment by lqniunjunlper** [comment]
I installed paddle from source. 
I manually modify this script: paddle\scripts\submit_local.sh.in with PADDLE_CONF_PATH variable, and paddle worked!

**Comment by will-am** [comment]
I suggest to run paddle directly with python like `python train.py`, like this [example](https://github.com/PaddlePaddle/book/tree/develop/01.fit_a_line).
