### ISSUE TITLE
Documentation about wheel package releasing process

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7257]
http://paddlepaddle.org/ explained pip install. Who is in charge of the wheel releasing process and do we have a document about it?

**Comment by Yancey1989** [comment]
[Build using Docker](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/build_en.md) introduce how to build PaddlePaddle use Docker image, and we can build different versions of the wheel packages for multiple platforms by different Docker image which comes from [buildtools](https://github.com/PaddlePaddle/buildtools).

**Comment by luotao1** [comment]
We already have the release document on wheel package: https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/releasing_process_cn.md#%E5%8F%91%E5%B8%83wheel%E5%8C%85%E5%88%B0pypi
