### ISSUE TITLE
pip quick start doesn't work

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7258]
I was following the Pip Quick Start on paddlepaddle.org, but I got the following errors:

```
yi@Yis-Mac-mini hello $ nano housing.py
yi@Yis-Mac-mini hello $ python housing.py 
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
yi@Yis-Mac-mini hello $ 
```

**Comment by typhoonzero** [comment]
Try using `brew install python` instead of Mac OS system python. This error was because PaddlePaddle requires `libpython.dylib` to run and this error is the python interpreter is not compatible with `libpython.dylib`.

**Comment by wangkuiyi** [comment]
Thanks!
