### ISSUE TITLE
Remove the ambiguous Dockerhub account 

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7259]
Let us remove https://hub.docker.com/r/paddledev

**Comment by luotao1** [comment]
Discussed with @Yancey1989 in #6752 . We have already modify the [full description of `paddledev/paddle`](https://hub.docker.com/r/paddledev/paddle/)
![image](https://user-images.githubusercontent.com/6836917/34635695-36fc228c-f2ce-11e7-9a0f-665fffef53c2.png)

**Comment by luotao1** [comment]
@Yancey1989 As we don't find the way to delete this repo, how about setting its Visibility from Public to Private in https://hub.docker.com/u/paddledev/dashboard/settings/ ?

**Comment by reyoung** [comment]
They have been deleted.
