### ISSUE TITLE
Add next step link after Quick Start

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7261]
Our current Quick Start section in the paddlepaddle.org Web site presents an inference program. We need a link guiding the readers to the next step.  I am not sure what would be a good target, but it seems that PaddlePaddle book is a good candidate.

**Comment by luotao1** [comment]
I think PaddlePaddle book is a good candidate too. Can @cs2be help to add such a link at homepage of paddlepaddle.org?

**Comment by cs2be** [comment]
Yes, will add a link to book on the homepage

**Comment by cs2be** [comment]
https://github.com/PaddlePaddle/PaddlePaddle.org/pull/370
