### ISSUE TITLE
克隆了paddle的develop分支，进行docker编译image时报错

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#727]
在执行docker进行源码build镜像时，报错。
docker build -t regression/paddle:gpu-avx -f paddle/scripts/docker/Dockerfile.gpu .  
Sending build context to Docker daemon 31.55 MB
Step 1 : FROM nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04
7.5-cudnn5-devel-ubuntu14.04: Pulling from nvidia/cuda
04cf3f0e25b6: Pull complete 
d5b45e963ba0: Pull complete 
a5c78fda4e14: Pull complete 
193d4969ca79: Pull complete 
d709551f9630: Pull complete 
cdb3355c9d8c: Pull complete 
76bab5457ba1: Pull complete 
0c86c4b14c90: Pull complete 
31460c59fe99: Pull complete 
5c54b056009f: Pull complete 
7d61ec67daa6: Pull complete 
d91920c51f3e: Pull complete 
35c667451117: Pull complete 
Digest: sha256:0e0f152756bee7bcbf19137a83468e7feea3eb614a83c30138377a31d86e8489
Status: Downloaded newer image for nvidia/cuda:7.5-cudnn5-devel-ubuntu14.04
 ---> 7d5d89337da6
Step 2 : MAINTAINER PaddlePaddle Authors <paddle-dev@baidu.com>
 ---> Running in c20e66d58584
 ---> 5a949c353345
Removing intermediate container c20e66d58584
Step 3 : RUN apt-get update &&     apt-get install -y cmake libprotobuf-dev protobuf-compiler git     libgoogle-glog-dev libgflags-dev libatlas-dev libatlas3-base g++ m4 python-pip     python-protobuf python-numpy python-dev swig openssh-server     wget unzip python-matplotlib tar xz-utils bzip2 gzip coreutils     sed grep graphviz libjpeg-dev zlib1g-dev doxygen &&     apt-get clean -y
 ---> Running in 624d8899fc83
Err http://developer.download.nvidia.com  InRelease
  
Err http://developer.download.nvidia.com  InRelease
  
Err http://developer.download.nvidia.com  Release.gpg
  Could not resolve 'developer.download.nvidia.com'
Err http://developer.download.nvidia.com  Release.gpg
  Could not resolve 'developer.download.nvidia.com'
Err http://archive.ubuntu.com trusty InRelease
  
Err http://archive.ubuntu.com trusty-updates InRelease
  
Err http://archive.ubuntu.com trusty-security InRelease
  
Err http://archive.ubuntu.com trusty Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-updates Release.gpg
  Could not resolve 'archive.ubuntu.com'
Err http://archive.ubuntu.com trusty-security Release.gpg
  Could not resolve 'archive.ubuntu.com'
Reading package lists...
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/InRelease  

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/InRelease  

W: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/InRelease  

W: Failed to fetch http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/InRelease  

W: Failed to fetch http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1404/x86_64/Release.gpg  Could not resolve 'developer.download.nvidia.com'

W: Failed to fetch http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1404/x86_64/Release.gpg  Could not resolve 'developer.download.nvidia.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-security/Release.gpg  Could not resolve 'archive.ubuntu.com'

W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...E: Package 'cmake' has no installation candidate
E: Unable to locate package libprotobuf-dev
E: Unable to locate package protobuf-compiler
E: Unable to locate package git
E: Unable to locate package libgoogle-glog-dev
E: Unable to locate package libgflags-dev
E: Unable to locate package libatlas-dev
E: Unable to locate package libatlas3-base
E: Unable to locate package m4
E: Unable to locate package python-pip
E: Unable to locate package python-protobuf
E: Unable to locate package python-numpy
E: Unable to locate package python-dev
E: Unable to locate package swig
E: Unable to locate package openssh-server
E: Unable to locate package wget
E: Unable to locate package unzip
E: Unable to locate package python-matplotlib
E: Package 'graphviz' has no installation candidate
E: Unable to locate package libjpeg-dev
E: Unable to locate package zlib1g-dev
E: Unable to locate package doxygen

Package cmake is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package graphviz is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

The command '/bin/sh -c apt-get update &&     apt-get install -y cmake libprotobuf-dev protobuf-compiler git     libgoogle-glog-dev libgflags-dev libatlas-dev libatlas3-base g++ m4 python-pip     python-protobuf python-numpy python-dev swig openssh-server     wget unzip python-matplotlib tar xz-utils bzip2 gzip coreutils     sed grep graphviz libjpeg-dev zlib1g-dev doxygen &&     apt-get clean -y' returned a non-zero code: 100

**Comment by reyoung** [comment]
You need to have a VPN when compile this docker image, because the China GFW will
