### ISSUE TITLE
如何自定义带加权的2类交叉熵损失

### ISSUE THREAD

**Issue by wzmsltw** [PaddlePaddle/Paddle#7271]
请教一个问题。现在我的时序模型输出的vector 长度为 100 （y_predict), 2类标签的长度也是100 (y_label)。我想要计算如下的损失。

coeff1 * y_label * log(y_predict) + coeff2 * (1- y_label) * log(1-y_predict)

发现提供的cost层里面没有可以实现的方式，想请教一下应该如何自定义这个损失函数？非常感谢

**Comment by coeasy** [comment]
也在关注这个问题，希望帮忙看看的

**Comment by Superjomn** [comment]
哪个版本？ fluid 还是 v2?

**Comment by coeasy** [comment]
是 v2 版本的·

**Comment by Superjomn** [comment]
@guoshengCS 你模型写的多，可以帮解答下吗。

@shanyi15 我们有这样的介绍吗，有好几个人问过，可能文档确实或者不明显。

**Comment by guoshengCS** [comment]
是希望多种loss加权求和么，V2版本多目标loss设置方法可以参考这里 https://github.com/PaddlePaddle/models/blob/develop/image_classification/train.py#L53

**Comment by guoshengCS** [comment]
这个相当于为正负样本设置不同的权重吧，V2版本为样本设置权重的话可以增加一个data_layer，`paddle.layer.data(name='weight', type=paddle.data_type.dense_vector(1))`，然后把这个weight传给cross_entropy https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L6156 ，生成数据时每条样本加一个weight的field（正样本是[coeff1]，负样本是[coeff2]）
