### ISSUE TITLE
我使用paddlepaddle写了一个项目，代码完全照搬的，还是出错

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7277]
* 我的项目GitHub地址：[https://github.com/yeyupiaoling/TestCustomData](https://github.com/yeyupiaoling/TestCustomData)
* 之前提的问题 #7185
* 各位大神能帮我看看吗？

**Comment by liuhuiCNN** [comment]
你用的什么机器训练的？如果机器内存或者计算能力不强的话，试试小一点的模型。如果小模型可以跑，说明是机器内存或者计算能力不够。

**Comment by QiJune** [comment]
我看到错误是浮点异常，请问你的训练配置是什么样的

**Comment by yeyupiaoling** [comment]
@QiJune VGG16 [https://github.com/yeyupiaoling/TestCustomData/blob/master/code/vgg.py#L47](https://github.com/yeyupiaoling/TestCustomData/blob/master/code/vgg.py#L47)

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 
* 机器配置是Ubuntu，2核8G
* 数据是只有3千张图片，很小的
* cifar10都可以跑起来，内存是没问题的

**Comment by QiJune** [comment]
请问paddle是怎么安装的呢？
浮点异常具体发生在哪个层呢？

**Comment by yeyupiaoling** [comment]
@QiJune 
* paddlepaddle是我自己有源码编译的,因为我的电脑不支持AVX,没有现成的paddlepaddle安装
* 怎么查是安装了哪个的blas库,我好像是没有专门安装这个东西
* 同样的程序,我在另一个项目中是正常的
    * 正常的项目:[https://github.com/yeyupiaoling/TestImagesClassify/blob/master/code/PaddleUtil.py](https://github.com/yeyupiaoling/TestImagesClassify/blob/master/code/PaddleUtil.py)
     * 报错的项目:[https://github.com/yeyupiaoling/TestCustomData/blob/master/code/train.py](https://github.com/yeyupiaoling/TestCustomData/blob/master/code/train.py)
* 怎么查是哪一层发生的异常,我所有的异常信息都放出来了

**Comment by QiJune** [comment]
@yeyupiaoling 

如果是自己源码编译的，那么应该使用的是openblas。
这两个项目的区别就是训练数据不一样？
我看reader是你自己写的，你能先确认reader产生的数据是正确的吗？就像下面这样示例程序一样，检验一下输入数据是否正常
```
train_reader = paddle.batch(
    paddle.reader.shuffle(
        paddle.dataset.mnist.train(), buf_size=8192),
    batch_size=BATCH_SIZE)
for data in train_reader():
    print data
```

**Comment by yeyupiaoling** [comment]
@QiJune 
* 两项目是同样的训练数据,都是我自定义的数据,一样的
* 我按照你给的程序,测试了,两个项目输出的格式是一样的,我也对比了cifar10输出的,也是一样的
>我看reader是你自己写的，你能先确认reader产生的数据是正确的吗？就像下面这样示例程序一样，检验一下输入数据是否正常
* 那个`reader`不是我写的,是按照官网的,地址:[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py)

**Comment by QiJune** [comment]
能构造出一个复现问题的代码，以及一部分数据吗？需要验证一下

**Comment by yeyupiaoling** [comment]
@QiJune 
* 这项目就是又问题的，你运行一下就可以看到问题了 [https://github.com/yeyupiaoling/TestCustomData](https://github.com/yeyupiaoling/TestCustomData)

**Comment by QiJune** [comment]
好的，我线下跑跑看

**Comment by yeyupiaoling** [comment]
@QiJune 跑得怎么样，有没有找到问题

**Comment by QiJune** [comment]
能复现问题，有待进一步排查

**Comment by QiJune** [comment]
可以尝试这里的vgg配置，book中的vgg网络是针对32*32图片的，有bn层
https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/vgg.py

而model目录下的vgg网络是针对224*224大小的。

**Comment by yeyupiaoling** [comment]
@QiJune 
加了BN层和Dropout层好像就没有出现问题了,这是为什么?

**Comment by yeyupiaoling** [comment]
@QiJune 
加了BN层和Dropout层好像没办法收敛了,只有去掉BN层和Dropout层错误了才会下降,
