### ISSUE TITLE
img_conv中的groups参数和num_channels参数有什么区别？

### ISSUE THREAD

**Issue by KaelChen** [PaddlePaddle/Paddle#7289]
在使用paddle的img_conv层时发现有三个参数影响层与层之间传递的channel，分别是num_channels，num_filters和groups。
因为之前使用tensorflow和mxnet的经验，都是指定input_channels和output_channels之后，自动生成*input_channels * output_channels*个filter，比如输入channel是16个，输出channel是32个，那么会生成16 * 32个卷积核，对应每个输出通道有16个卷积核，和16个输入通道的图像做卷积操作之后合成一幅图像，那么本层的输出就是32个图像。
在paddle中似乎是通过**groups**来确定上一层输入多少个通道，通过*groups * num_filters*来确定本层产生多少个卷积核，输出通道数被设定为**num_filters**。但是这样一来，**groups**和**num_channels**的区别是什么呢？
总感觉这里用三个参数来实现有点怪，不知道我理解的对不对，希望大神解答一下。

**Comment by qingqing01** [comment]
[`img_conv_layer `](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L2508) 中的参数和MxNet的参数一致。

具体参数解释如下：

- num_channels: 表示输入层的通道数，假如叫Ci = 16
- num_filters:  表示该conv的输出通道数，假如叫Co = 32 
- groups: 分组的conv分的组数，假如叫 G

当`G = 1`时候，就是你理解的：

> 因为之前使用tensorflow和mxnet的经验，都是指定input_channels和output_channels之后，自动生成input_channels * output_channels个filter，比如输入channel是16个，输出channel是32个，那么会生成16 * 32个卷积核，对应每个输出通道有16个卷积核，和16个输入通道的图像做卷积操作之后合成一幅图像，那么本层的输出就是32个图像。

当`G>1`，比如G=2，和MxNet文档一致： https://mxnet.apache.org/api/python/gluon/nn.html?highlight=conv#mxnet.gluon.nn.Conv2D ，表示：

分成了2组独立的conv： 输出的前16个通道连接输入的前8个通道， 输出的后16个通道连接输入的后8个通道。 


> groups和num_channels的区别是什么呢？

这两其实没啥关系， 我们目前的文档有错误，给你带来的不便，我们尽快会修改。谢谢了~

**Comment by KaelChen** [comment]
明白了，谢谢解答
