### ISSUE TITLE
如何定义长方形的filter

### ISSUE THREAD

**Issue by ZouJG** [PaddlePaddle/Paddle#7296]
目前遇到这么一个问题:输入数据为8维400行，现在想做一个8x50的卷积核，对数据进行纵向的卷积，也就是输入为·[8,400]二维矩阵，filter_height=8, filter_width=50，stride与pooling中的x_axises=0，y>=1。
尝试过row_conv，但是没有找到相关步长与卷积核数量的设置；
尝试过img_conv，但是img_conv对于开平方不为整数的数据也会报错；
conv_operator与conv_projection看文档说明，是能支持这种自定义卷积的，但是木有gpu，未做尝试。

**Comment by qingqing01** [comment]
>  目前遇到这么一个问题:输入数据为8维400行，现在想做一个8x50的卷积核，对数据进行纵向的卷积，也就是stride与pooling中的x_axises=0。

能否详细的描述下数据组织方式？ 8维400行，是输入数据是[8, 400]的二维矩阵？8x50的卷积核是filter_height=8, filter_width=50?  是怎么做卷积的？

>  尝试过img_conv，但是img_conv对于开平方不为整数的数据也会报错；

img_conv支持长方形的filter。注意，如果输入数据是长方形，需要配置`data_layer`的height,width。
