### ISSUE TITLE
新版fluid分布式版本pserver问题咨询

### ISSUE THREAD

**Issue by alexqdh** [PaddlePaddle/Paddle#7297]
有问题麻烦看下，谢谢。
1. fluid分布式运行时候的pserver是否还支持之前的nics, rdma_tcp等参数
2. 针对sparse是否还有单独的实现优化

**Comment by Yancey1989** [comment]
> fluid分布式运行时候的pserver是否还支持之前的nics, rdma_tcp等参数

1. fluid的pserver启动时可以指定IP:PORT, 可以指定监听的IP为对应网卡的IP段。
1. 目前fluid分布式通信使用gRPC，RDMA的支持还需要调研，但在二月底的daedline还没有计划支持。

> 针对sparse是否还有单独的实现优化

spare目前采用[SelectedRows](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/selected_rows.md)结构来实现。

**Comment by chengduoZH** [comment]
该咨询已得到解答，这个issue可以关掉了，如有更深入咨询，可以再打开
