### ISSUE TITLE
demo数据下载失败

### ISSUE THREAD

**Issue by wzh420** [PaddlePaddle/Paddle#7298]
1、http://models.paddlepaddle.org/2017/04/21/sequence-tagging-for-ner-README.html
中的 http://models.paddlepaddle.org/2017/04/21/reader.py 等链接 404
2、https://github.com/PaddlePaddle/Paddle/tree/master/demo/sequence_tagging 中
cd demo/sequence_tagging
./data/get_data.sh
返回 ERROR 500: Internal Server Error.

**Comment by QiJune** [comment]
请问您是如何点到上述链接的呢？看起来这些链接已经是deprecated状态的
