### ISSUE TITLE
有paddle.v2.data_type.integer_value_sub_sequence类似功能，但是不限定dim的函数吗？

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7305]
我感觉这个设计的时候就是为了做Embedding映射的吗？但是有时我的输入不一定是Embedding的索引：
比如，我现在做抽取式摘要，需要有标签输入，预期是

```
(label1, left_sent_id1, right_sent_id1),
(label2, left_sent_id2, right_sent_id2),
...
```

然而这个该怎么读入呢？或者有什么更加标准的方法呢

**Comment by QiJune** [comment]
这个dim其实没有做检查，如果是embedding的话，会在embedding里面检查。
所以，在明确知道自己想做什么的情况下，可以直接使用而不需要关心设置的dim

**Comment by memeda** [comment]
哦哦，好的，缺乏经验 = =
求花力气更新文档，没有文档，paddle难以走远啊
