### ISSUE TITLE
'module' object has no attribute 'square_error_cost

### ISSUE THREAD

**Issue by wushaomei** [PaddlePaddle/Paddle#7310]
cost = paddle.layer.square_error_cost(input=y_predict, label=y)

**Comment by pardy218** [comment]
paddle.layer.square_error_cost(input=y_predict, label=y)
paddle 版本是 0.10.0 升级到那个版本？

**Comment by luotao1** [comment]
可以升级到0.11.0版本

**Comment by pardy218** [comment]
升级以后确定是会有这个.square_error_cost()方法 ？

**Comment by pardy218** [comment]
升级以后确定是会有.square_error_cost()这个方法？

**Comment by luotao1** [comment]
确定
