### ISSUE TITLE
使用最新的docker build 方式，使用默认的build.sh，编译报错

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#732]
在执行docker进行源码build镜像时，报错。
docker build -t regression/paddle:gpu-avx -f paddle/scripts/docker/Dockerfile.gpu .  
在dockerfile中开启，文档编译后，在docker进行image编译时报错。
![image](https://cloud.githubusercontent.com/assets/6229206/20882876/115b49e2-bb1e-11e6-959f-0709ed809cb9.png)

![image](https://cloud.githubusercontent.com/assets/6229206/20882898/341e98da-bb1e-11e6-8b9e-6e4b340c90f4.png)

**Comment by wen-bo-yang** [comment]
这块是不是需要在dockerfile中apt-get的时候安装urllib3的python扩展?

**Comment by reyoung** [comment]
Will be fixed in #723. I already found this bug and comment in this PR. Please watch #723 for update.
