### ISSUE TITLE
I want to know sparse_float_vector_sequence different

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/Paddle#7324]
I read [this page](https://github.com/PaddlePaddle/Paddle/blob/8a24915d39e06745af99cb50a4cb9c36149b948c/doc/getstarted/concepts/use_concepts_cn.rst) 
but i want to know the different of 
[[(1,2),(3,4),(5,6)]]
and
[[(1,2)],[(3,4)],[(5,6)]]
in sparse_float_vector_sequence 

in the example [this page](https://github.com/PaddlePaddle/models/blob/c952c3de1986204dced2d25a7351f72aa3ebab44/ctr/network_conf.py)
`self.lr_merged_input = layer.data(
            name='lr_input',
            type=paddle.data_type.sparse_float_vector(self.lr_input_dim))`
this can be used in 
`fc = layer.fc(
            input=self.lr_merged_input, size=1, act=paddle.activation.Relu())`
but i use in `paddle.networks.sequence_conv_pool` will cause core
is there any other networks the `sparse_float_vector` can be used, or give a example
thanks

**Comment by QiJune** [comment]
[(1,2),(3,4),(5,6)]是一个sparse float vector
[[(1,2),(3,4),(5,6)]]是一个sparse float vector sequence，这条数据中只有一个sequence
[[(1,2)],[(3,4)],[(5,6)]] 如果是指一个样本的话，没有这种表示方式

请把报错的详细信息贴一下

**Comment by veridone** [comment]
如果embeding操作会出现这个core
I0109 16:31:11.229604 21299 GradientMachine.cpp:94] Initing parameters..
I0109 16:31:12.471943 21299 GradientMachine.cpp:101] Init parameters done.
F0109 16:31:31.294528 21299 TableProjection.cpp:39] Check failed: in_->ids 
*** Check failure stack trace: ***
    @     0x7f061d2969ad  google::LogMessage::Fail()
    @     0x7f061d29a45c  google::LogMessage::SendToLog()
    @     0x7f061d2964d3  google::LogMessage::Flush()
    @     0x7f061d29b96e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f061cf447b5  paddle::TableProjection::forward()
    @     0x7f061cfa2469  paddle::MixedLayer::forward()
    @     0x7f061d04be6d  paddle::NeuralNetwork::forward()
    @     0x7f061d04cb83  paddle::GradientMachine::forwardBackward()
    @     0x7f061d272994  GradientMachine::forwardBackward()
    @     0x7f061cef0c99  _wrap_GradientMachine_forwardBackward
    @     0x7f068251c3d3  PyEval_EvalFrameEx
    @     0x7f068251e160  PyEval_EvalCodeEx
    @     0x7f068251c4d1  PyEval_EvalFrameEx
    @     0x7f068251e160  PyEval_EvalCodeEx
    @     0x7f068251c4d1  PyEval_EvalFrameEx
    @     0x7f068251e160  PyEval_EvalCodeEx
    @     0x7f068251c4d1  PyEval_EvalFrameEx
    @     0x7f068251e160  PyEval_EvalCodeEx
    @     0x7f068251c4d1  PyEval_EvalFrameEx
    @     0x7f068251e160  PyEval_EvalCodeEx
    @     0x7f068251e272  PyEval_EvalCode
    @     0x7f068253865c  run_mod
    @     0x7f0682538730  PyRun_FileExFlags
    @     0x7f0682539c3c  PyRun_SimpleFileExFlags
    @     0x7f068254b4fc  Py_Main
    @     0x7f0681777b45  __libc_start_main
Thread [139665938065216] Forwarding __embedding_4__, 
*** Aborted at 1515486691 (unix time) try "date -d @1515486691" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGABRT (@0x1f600005333) received by PID 21299 (TID 0x7f0682a02740) from PID 21299; stack trace: ***
    @     0x7f068222f130 (unknown)
    @     0x7f068178b9d9 __GI_raise
    @     0x7f068178d0e8 __GI_abort
    @     0x7f061d2a0eeb google::FindSymbol()
    @     0x7f061d2a18aa google::GetSymbolFromObjectFile()
    @     0x7f061d2a1f72 google::SymbolizeAndDemangle()
    @     0x7f061d29f778 google::DumpStackTrace()
    @     0x7f061d29f836 google::DumpStackTraceAndExit()
    @     0x7f061d2969ad google::LogMessage::Fail()
    @     0x7f061d29a45c google::LogMessage::SendToLog()
    @     0x7f061d2964d3 google::LogMessage::Flush()
    @     0x7f061d29b96e google::LogMessageFatal::~LogMessageFatal()
    @     0x7f061cf447b5 paddle::TableProjection::forward()
    @     0x7f061cfa2469 paddle::MixedLayer::forward()
    @     0x7f061d04be6d paddle::NeuralNetwork::forward()
    @     0x7f061d04cb83 paddle::GradientMachine::forwardBackward()
    @     0x7f061d272994 GradientMachine::forwardBackward()
    @     0x7f061cef0c99 _wrap_GradientMachine_forwardBackward
    @     0x7f068251c3d3 PyEval_EvalFrameEx
    @     0x7f068251e160 PyEval_EvalCodeEx
    @     0x7f068251c4d1 PyEval_EvalFrameEx
    @     0x7f068251e160 PyEval_EvalCodeEx
    @     0x7f068251c4d1 PyEval_EvalFrameEx
    @     0x7f068251e160 PyEval_EvalCodeEx
    @     0x7f068251c4d1 PyEval_EvalFrameEx
    @     0x7f068251e160 PyEval_EvalCodeEx
    @     0x7f068251c4d1 PyEval_EvalFrameEx
    @     0x7f068251e160 PyEval_EvalCodeEx
    @     0x7f068251e272 PyEval_EvalCode
    @     0x7f068253865c run_mod
    @     0x7f0682538730 PyRun_FileExFlags
    @     0x7f0682539c3c PyRun_SimpleFileExFlags

**Comment by veridone** [comment]
如果 sequence_conv_pool 会出现

Pass 0, Batch 0, Cost 0.250276, {}
................................Thread [140246747780928] Forwarding __sequence_conv_pooling_3___conv_fc, 
*** Aborted at 1515486924 (unix time) try "date -d @1515486924" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f8d5811b427) received by PID 11540 (TID 0x7f8dbd951740) from PID 1477555239; stack trace: ***
    @     0x7f8dbd17e130 (unknown)
    @     0x7f8d5811b427 paddle::vTanh<>()
    @     0x7f8d5812d413 paddle::CpuMatrix::tanh()
    @     0x7f8d57fff6dc paddle::tanhActivation::forward()
    @     0x7f8d57f0e4b9 paddle::Layer::forwardActivation()
    @     0x7f8d57f24c86 paddle::FullyConnectedLayer::forward()
    @     0x7f8d57f9ae6d paddle::NeuralNetwork::forward()
    @     0x7f8d57f9bb83 paddle::GradientMachine::forwardBackward()
    @     0x7f8d581c1994 GradientMachine::forwardBackward()
    @     0x7f8d57e3fc99 _wrap_GradientMachine_forwardBackward
    @     0x7f8dbd46b3d3 PyEval_EvalFrameEx
    @     0x7f8dbd46d160 PyEval_EvalCodeEx
    @     0x7f8dbd46b4d1 PyEval_EvalFrameEx
    @     0x7f8dbd46d160 PyEval_EvalCodeEx
    @     0x7f8dbd46b4d1 PyEval_EvalFrameEx
    @     0x7f8dbd46d160 PyEval_EvalCodeEx
    @     0x7f8dbd46b4d1 PyEval_EvalFrameEx
    @     0x7f8dbd46d160 PyEval_EvalCodeEx
    @     0x7f8dbd46b4d1 PyEval_EvalFrameEx
    @     0x7f8dbd46d160 PyEval_EvalCodeEx
    @     0x7f8dbd46d272 PyEval_EvalCode
    @     0x7f8dbd48765c run_mod
    @     0x7f8dbd487730 PyRun_FileExFlags
    @     0x7f8dbd488c3c PyRun_SimpleFileExFlags
    @     0x7f8dbd49a4fc Py_Main
    @     0x7f8dbc6c6b45 __libc_start_main
Aborted (core dumped)

**Comment by QiJune** [comment]
请问输入数据的格式是什么，可以附上一个输入数据的样例

**Comment by veridone** [comment]
用的sequence 输入如
[2330, [(0, 2), ..., (9, 1)], [5, 2225, ..., 301], [60, 69, 31, ..., 30], [[(59, 88), (14, 269), (14, 640),... (60, 24383)]], [1]]

**Comment by QiJune** [comment]
sequence pool目前不支持sparse数据

**Comment by veridone** [comment]
embeding也不支持吧

**Comment by QiJune** [comment]
embedding接收的输入是index数据
