### ISSUE TITLE
Model format proposal.

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#7329]
As of now, we store different files (one for each parameter) when we save the model in fluid, I want to look further into how we can structure this better.

**Comment by kavyasrinet** [comment]
The current approach in Fluid is as follows:
```python
save_program = Program()
save_block = save_program.global_block()

for each_var in vars: 
     new_var = _clone_var_in_block_(save_block, each_var)
     save_block.append_op(
               type='save',
                inputs={'X': [new_var]},
                outputs={},
                attrs={'file_path': os.path.join(dirname, new_var.name)})
```

This is an excerpt taken from the [`save_vars`](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/io.py#L32) function. 

Here, we iterate over all the variables/parameters one by one and create a separate file one for each variable in the parent directory.

I am looking at  different ways of efficiently achieving this, without having to create a new file for each variable.

**Comment by kexinzhao** [comment]
@kavyasrinet In your Proposal 1, would there be two files (one for model and one for parameters) or one file (for both model and parameters)?

**Comment by Xreki** [comment]
I think the design in @kavyasrinet 's Proposal 1, is to save the protobuf message and parameters into one file, a single binary file. In this design, the attribute `file_path` of `save_op` will be set to the same file, and we need another attribute `offset` to record the start offset in the saving file.

**Comment by abhinavarora** [comment]
I prefer storing the Parameters and the Protobuf message separately because it is possible that users might like to explore different Parameters for the same Inference Model. For easy distribution of the model, we can always write a small wrapper that can zip the model and the parameter files together.

**Comment by kavyasrinet** [comment]
@Xreki Thanks for clarifying , yes that's the approach I was proposing.
@abhinavarora I have thought about that approach but the design for that will need to be well thought out before proposing it, since there will be a bunch of additional components that will need to be written to make that design work with PaddlePaddle. The first approach I have proposed above is the fastest to implement. I will write more about other approaches today/tomorrow.

**Comment by kavyasrinet** [comment]
Hi @Xreki and @kexinzhao , I have added another proposal in the discussion above. Working on few more.

**Comment by sidgoyal78** [comment]
Even in proposal 1, it is a bit more involved. Since we need to retrieve the merged files into separate parameter files.
