### ISSUE TITLE
死链检测--持续集成工作

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#733]
文档死链，通过windows下xenu工具获得
截屏
![image](https://cloud.githubusercontent.com/assets/1908992/20883104/4d2545f8-bb1f-11e6-9113-b56f60d58f26.png)

URL list
- http://www.paddlepaddle.org/doc/genindex.html
- http://www.paddlepaddle.org/doc/ui/trainer_config_helpers_api.html
- http://www.paddlepaddle.org/doc/ui/api/trainer_config_helpers/layers_index.html
- http://www.paddlepaddle.org/doc_cn/ui/cmd_argument/detail_introduction.html
- http://www.paddlepaddle.org/doc/source/gserver/layers/layer.html
- http://www.paddlepaddle.org/doc/source/cuda/matrix/matrix.html
- http://www.paddlepaddle.org/doc/source/math/matrix/matrix.html
- http://www.paddlepaddle.org/doc_cn/faq/TBD
- http://www.paddlepaddle.org/doc/source/pserver/network/network.html

**Comment by luotao1** [comment]
应该对develop分支上的文档进行检测，另外https://arxiv.org/abs 这些都能打开。

**Comment by llxxxll** [comment]
首页里好像还有一个google css的经常超时链接。
http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic

**Comment by llxxxll** [comment]
@luotao1 能发布一个内网版本么，我可以用这个工具试试。

**Comment by llxxxll** [comment]
删除了https://arxiv.org/*链接

**Comment by luotao1** [comment]
http://m1-idl-gpu2-bak31.m1:8088/doc_luotao/note/doc/ 和 http://m1-idl-gpu2-bak31.m1:8088/doc_luotao/note/doc_cn 你可以试下。
不过应该在 #712 完成后再进行，因为英文目录的rst会改成*_en.rst，导致又出现死链接。

**Comment by luotao1** [comment]
有linux下的检测工具么，这样可以写进单测

**Comment by llxxxll** [comment]
@luotao1 https://github.com/andyidea/dead-links-crawler
试试这个

**Comment by luotao1** [comment]
有一个开源的检查死链的工具linkchecker https://wummel.github.io/linkchecker/ 。
- windows上测过很好用，速度也很快，没有误报。
- linux上，pip install的版本太老了(2014年的有bug)，得从源码编译安装。

**Comment by luotao1** [comment]
#946
