### ISSUE TITLE
Refactor the `load` and `save` methods.

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#7330]
I want to explore ways we can refactor the `save_inference_model` and `load_inference_model` methods to generalize for both training and inference. There are a lot of unnecessary parameters in the model that are probably not needed at the moment for inference.

**Comment by Xreki** [comment]
Yes, there are so many persistable variables that should be saved for training, but no need for inference. It is necessary to find a way to unify this.
