### ISSUE TITLE
Chinese version website doesn't have mobile section on top-right

### ISSUE THREAD

**Issue by kexinzhao** [PaddlePaddle/Paddle#7332]
There is a 'mobile' tab on the top-right side of the english version of paddlepaddle.org website.

However, when switched to Chinese version, only "文档"
"教程"  "模型库" are there. No tab corresponding to 'mobile'.

**Comment by Xreki** [comment]
Because there is no Chinese version README. In fact, there is a PR: https://github.com/PaddlePaddle/Mobile/pull/65

**Comment by Xreki** [comment]
https://github.com/PaddlePaddle/Mobile/pull/65 is merged now, and we can see a update of the English website http://www.paddlepaddle.org/docs/develop/mobile/README.html . However, the Chinese version still cannot be shown. How to fix this? @kexinzhao @jetfuel

**Comment by jetfuel** [comment]
@Xreki @kexinzhao I found out that the site didn't generate the sitemap properly for the Chinese version. I updated the paddlepaddle.org code to properly consume the Chinese version of Mobile documentation. The Chinese documentation is up now. Please take a look at it and let me know if you find any issue. Thank you for providing the documentation.

**Comment by kexinzhao** [comment]
Thanks @Xreki and @jetfuel for fixing this issue.

**Comment by Xreki** [comment]
@jetfuel @kexinzhao How about change `移动` to `移动端`?
