### ISSUE TITLE
fluid.io don't show in the website

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7335]
In http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid.html, there is no `fluid.io` for https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/io.py. Thus, we can't find the explanation of `load_inference_model` and `save_inference_model`.

**Comment by kavyasrinet** [comment]
I can look into this.

**Comment by kavyasrinet** [comment]
Still working on this, as of now, the docker build fails (this issue is being worked on: #7459
