### ISSUE TITLE
给 paramters 参数赋值 问题

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7336]
问题1：如何获取paramter参数的shape
我发现 Paddle/python/paddle/v2/parameters.py 中
paddle_names_lst = parameters.names()
paddle_keys_lst = parameters.keys()
（1）names和keys区别是什么？两者作用区别是什么？
paddle_np = parameters.get(paddle_names_lst[i])
（2）paddle_np.shape 和 parameters.get_shape(paddle_keys_lst[i]) 获取的shape不同，两个 numpy 有什么区别吗？
问题2：如何给paramter参数赋值？赋值之后可以infer
问题3：trainer和load weights的顺序对参数有影响
https://github.com/liuhuiCNN/paddle_issues/blob/master/paddle_issue_1.py

总结一下结果：
问题1：
（1）names 和 keys是一样的
  (2) 在参数只有1维的时候 paddle_np.shape 和 parameters.get_shape(paddle_keys_lst[i]) 获取的shape不同。不知道有什么意义？？？
代码在
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/parameters.py 202行
        dims = conf.dims if conf.dims else (1, conf.size)

问题2：可以使用paramters的set函数赋值
paramters["param_name"]方位到的也是权重
  
问题3 ：已解决

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/book/blob/develop/04.word2vec/README.cn.md#%E4%BF%AE%E6%94%B9%E8%AF%8D%E5%90%91%E9%87%8F 可以参考词向量这一章给参数赋值

**Comment by liuhuiCNN** [comment]
好的，谢谢！
请问 paddle 中 filter 参数的保存的二进制文件顺序是怎么样的？ 比如 3x3x1 filters=12 这样一个kernel怎么保存？

**Comment by jacquesqiao** [comment]
@liuhuiCNN 按照 Co Ci Kh Kw 的顺序存储的，Co是输出channle数， Ci数输入channel数

**Comment by liuhuiCNN** [comment]
@jacquesqiao 假设从___conv_pool_0___conv.w0 读出的权重是  3x3x1 filters=12，通过deserialize之后，得到的参数是 [12 1 3 3]，这样理解对吗？

f = open('model/___conv_0__.w0', 'r')
w0=deserialize(f)

def deserialize(f):
    """
    :param name:
    :param f:
    :type f: file
    :return:
    """
    f.read(16)  # header
    arr = np.frombuffer(f.read(), dtype=np.float32)
    return arr
