### ISSUE TITLE
Make optimizer program as a block instead of the attribute of Recv op

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#7343]
For the latest implement about Fluid distributed training, the optimizer program will be passed into Recv op as an attribute:
```bash
AddAttr<std::string>("OptimizeProgram", "type string",
                         "Serialized ProgramDesc string for recv to run.");
```

Maybe we could append the optimizer program into the block list and pass the block id into RecvOp, I think there is two advantage:
- All the variables will be infershaped before running.
- It's easy to debug, we can not print the whole pserver program after optimizer program be serialized to string.

**Comment by helinwang** [comment]
Yes! I faced the second issue today: https://github.com/PaddlePaddle/Paddle/issues/7419

**Comment by helinwang** [comment]
> All the variables will be infershaped before running.

Curious about this part of the code, if you are familiar with the infershape code, can you point me the code that explains why "All the variables will be infershaped before running."? Thanks!

**Comment by helinwang** [comment]
@Yancey1989 @typhoonzero if you guys agree this is a good idea, and are not working on this, I can take this item.

I think we need to be able to serialize OptimizeProgram for debugging and unit test purposes.

**Comment by helinwang** [comment]
Just took a look, seems OP does not know about the current running ProgramDesc though.

**Comment by Yancey1989** [comment]
> All the variables will be infershaped before running

I think `exe.run(default_startup_program())` will do that.

**Comment by typhoonzero** [comment]
Totally agree, this change can also distributed transpiler do not create variables twice both in pserver program and recv op subprogram.

**Comment by typhoonzero** [comment]
> @Yancey1989 @typhoonzero if you guys agree this is a good idea, and are not working on this, I can take this item.

@helinwang I'm not working on this currently.

**Comment by Yancey1989** [comment]
Thanks @typhoonzero @helinwang .

**Comment by helinwang** [comment]
Blocking issue: https://github.com/PaddlePaddle/Paddle/issues/7468
