### ISSUE TITLE
init device should use all avaliable device by default

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#7344]
Currently, we use InitDevices(devices) to configure devices, but we should use all available device by default.

**Comment by wangkuiyi** [comment]
Could you justify why should we make PaddlePaddle job use all devices? In my mind, a physical node could be allocated (by Kubernetes and etc) to run more than one PaddlePaddle jobs. So each job shouldn’t use up to all devices on a node, right?

**Comment by dzhwinter** [comment]
> a physical node could be allocated (by Kubernetes and etc) to run more than one PaddlePaddle jobs.
definitely agreed. 

The reason for changing InitDevices(devices)` to  use all visible devices by default 
1. Init device will create the device pool, if one user start paddle with default configuration, say write fluid in jupyter notebook, he will find that **parallel.for** didn't work unless he restarts paddle with multiple GPU init-configuration.

2. In the previous implementation, we use a vector of string represent configurated devices.
https://github.com/PaddlePaddle/Paddle/pull/7345/files#diff-bbc9307b109956ee51d740492608fd28L43-L47
Both c++ side and python side need to understand the format, and our operator test framework needs to switch between multiple-GPU(say nccl op test, parallel.for op test) and single-GPU.

I thought people can use [CUDA_VISIBLE_DEVICES](https://devblogs.nvidia.com/parallelforall/cuda-pro-tip-control-gpu-visibility-cuda_visible_devices/) to control visible device, it is more convenient than our previous one.
