### ISSUE TITLE
Specifies Paddle dependencies using git submodule

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#735]
Currently, we use CMakeLists.txt to check if dependencies, like gflags, glog, and protobuf, have been installed. For example: https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/FindGflags.cmake#L147.

An alternative is to use `git add submodule` to create dependencies in Paddle's repo pointing to https://github.com/gflags/gflags, https://github.com/google/glog, and https://github.com/google/protobuf.

There is no much difference between these two solutions as we build and run Paddle using Docker. A minor advantage of the latter one might be *exposing dependencies of Paddle explicitly*.

**Comment by Yancey1989** [comment]
I will close this issue,if there is an update, please reopen it.
