### ISSUE TITLE
ParameterAttribute中name命名问题

### ISSUE THREAD

**Issue by thomas010** [PaddlePaddle/Paddle#7351]
最近在阅读paddle教程代码，看到很多layer中可以定义param_attr和bias_attr，有点困惑：
1. 这两个参数分别表示什么，作用是什么，有什么差异
2. 这两个参数都可以用ParamAttr对象赋值，而且在ParamAttr对象中定义name参数，那么name命名有什么规范或要求吗？name是怎么表示layer中参数的？

 75 q_rnn = paddle.layer.lstmemory(
 76         input=wx,
 77         bias_attr=paddle.attr.ParamAttr(
 78             name="_q_rnn1.wbias", initial_std=0, l2_rate=default_l2_rate),
 79         param_attr=paddle.attr.ParamAttr(
 80             name="_q_rnn1.w0",
 81             initial_std=default_init_std,
 82             l2_rate=default_l2_rate))

**Comment by jacquesqiao** [comment]
1，一个leyer中可能包含两种参数，一种是parameter，一种是bias，param_attr和bias_attr是对这两种参数进行配置的方式。
2，name可以对parameter进行命名，可以实现跨layer的parameter复用。不使用特殊字符，方便查看就行了。。

**Comment by thomas010** [comment]
还有点困惑，比如下面例子（from 示例教程）
75 q_rnn = paddle.layer.lstmemory(
76 input=wx,
77 bias_attr=paddle.attr.ParamAttr(
78 name="_q_rnn1.wbias", initial_std=0, l2_rate=default_l2_rate),
79 param_attr=paddle.attr.ParamAttr(
80 name="_q_rnn1.w0",
81 initial_std=default_init_std,
82 l2_rate=default_l2_rate))

问题：lstm里面的bias_attr和param_attr表示什么信息？

**Comment by thomas010** [comment]
还有layer有多个参数（比如lstm包含Wo Wf Wc bo bf bc），这时候param_attr是怎么对应到某个具体参数的
