### ISSUE TITLE
如何做两个向量的拼接操作

### ISSUE THREAD

**Issue by ZouJG** [PaddlePaddle/Paddle#7358]
现在有一个A 为24维的行向量，B为16维的行向量，想请教下如何将A与B拼接成一个40维的行向量。

**Comment by memeda** [comment]
paddle.v2.layer.concat ?  sample里有吧

**Comment by ZouJG** [comment]
找到了，哪里有个比较全的文档呀

**Comment by memeda** [comment]
= =, 我也是每次在issue 里搜... 
比较全的文档就是[官网的doc](http://paddlepaddle.org/docs/0.11.0/documentation/en/getstarted/index_en.html)了吧，虽然感觉也不太清楚 
我觉得先把自己目标相关的示例模型看一下，应该能看到必要的api。

**Comment by ZouJG** [comment]
越来越懒了……

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
