### ISSUE TITLE
how to create MKLDNNDeviceContext from CPUPlace

### ISSUE THREAD

**Issue by tensor-tang** [PaddlePaddle/Paddle#7366]
During the mkldnn op work #7365, we need get `dev_ctx` from pool see [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.cc#L485).

Then firstly the `MKLDNNDeviceContext` should has been created in the pool when init.

However, about the init function, the way paddle `InitDevices` is
```
paddle::framework::InitDevices({"CPU"});
```

I suppose with mkldnn should be like this:
```
paddle::framework::InitDevices({"MKLDNN"});
```

And then stack should be like:
`paddle::framework::InitDevices(const std::vector<std::string>)`
`platform::DeviceContextPool::Init(places)`
`pool = new DeviceContextPool(places);`
`DeviceContextPool(const std::vector<platform::Place>& places)` [here](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/platform/device_context.cc#L32).

Since the concept has been changed that `MKLDNNPlace` is removed, we could only create `MKLDNNDeviceContext` from `CPUPlace`.

But it is not possible in the `DeviceContextPool`, unless the `LibraryType` was given.

So, is that OK we change the interface adding `LibraryType` when init `DeviceContextPool`
```
static DeviceContextPool& Init(const std::vector<std::pair<platform::Place, framework::LibraryType>>&)
explicit DeviceContextPool(const std::vector<std::pair<platform::Place, framework::LibraryType>>& )
```

@QiJune  could u help check is that fine, or is that really necessary, or you have better suggestion?

Thanks.

**Comment by QiJune** [comment]
We mainly have two ways to solve this problem:

1. Introduce LibraryType
Since we have removed MKLDNNPlace, we must add another LibraryType field to get MKLDNNDeviceContext.
For CPUDeviceContext and CUDADeviceContext, the LibraryType is kPlain by default.
And the DeviceContextPool can provide a method like this:
```
const platform::DeviceContext* DeviceContextPool::Get(const platform::Place& place, LibraryType lt=kPlain);
```
2. Make MKLDNNDeviceContext as a member of CPUDeviceContext
And CPUDeviceContext will be like this:

```
bool HasMKLDNN() {
#ifdef PADDLE_WITH_MKL
    return true;
#else
    return false;
}

class CPUDeviceContext : public DeviceContext {
 public:
  CPUDeviceContext() {
      eigen_device_.reset(new Eigen::DefaultDevice());
      if (HasMKLDNN()) {
          mkl_dnn_dtx_.reset(new MKLDNNDeviceContext());
      }
  };
  explicit CPUDeviceContext(CPUPlace place);

  Eigen::DefaultDevice* eigen_device() const;

  MKLDNNDeviceContext* mkl_dnn_dtx() const;

  Place GetPlace() const override;

 private:
  CPUPlace place_;
  std::unique_ptr<Eigen::DefaultDevice> eigen_device_;
  std::unique_ptr<MKLDeviceContext> mkl_dnn_dtx_;
};
```


@tensor-tang @dzhwinter What's your opinion?

**Comment by tensor-tang** [comment]
1. This is the same way as I mentioned before, right?
2. I do not think this is a appropriate method that `CPUDeviceContext` handle `MKLDNNDeviceContext`. And this method should also have a bug:  when WITH_MKL=ON, creating `CPUDeviceContext` will always create `MKLDNNDeviceContext`.

**Comment by tensor-tang** [comment]
About `pool::Get(place)`, I do not think it's necessary to add library yet, since the LibraryDeviceContext is already inherit from `CPUDeviceContext`.

**Comment by QiJune** [comment]
> This is the same way as I mentioned before, right?

Yes, the first way is as you method before.

> And this method should also have a bug: when WITH_MKL=ON, creating CPUDeviceContext will always create MKLDNNDeviceContext.

Yes, there is a same bug for cudnn_handle. Each time we create a CUDADeviceContext, a cudnn_handle will be created also.


In original version design of DeviceContext, cudnn handle is initialized lazily. Please refer to https://github.com/PaddlePaddle/Paddle/blob/1038bc461a76a30f0bda32ff04b47920157b3bfe/paddle/platform/device_context.h#L85

As for MKLDNNDeviceContext:

class CPUDeviceContext : public DeviceContext {
 public:
  CPUDeviceContext() {
      eigen_device_.reset(new Eigen::DefaultDevice());
   };
  explicit CPUDeviceContext(CPUPlace place);

  Eigen::DefaultDevice* eigen_device() const;

  MKLDNNDeviceContext* mkl_dnn_dtx() const {
   if (!mkl_dnn_ctx_ && HasMKLDNN()) {
      mkl_dnn_ctx_ = new MKLDNNDeviceContext();
    }
    return mkl_dnn_ctx_;
  };

  Place GetPlace() const override;

 private:
  CPUPlace place_;
  std::unique_ptr<Eigen::DefaultDevice> eigen_device_{nullptr};
  mutate MKLDeviceContext* mkl_dnn_ctx_{nullptr};
};
```
