### ISSUE TITLE
tf2paddle 出错

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7386]
https://github.com/liuhuiCNN/tf_2_paddle_mnist
tf2paddle出错，按照文档转换的，到了paddle中结果不对，不知道问题在哪？

（1）请check我的代码是否有问题？
（2）问题在那？

**Comment by peterzhang2029** [comment]
把出的问题也贴在issue里吧 包括用了哪些文件 转化什么模型等信息。

**Comment by liuhuiCNN** [comment]
@peterzhang2029 代码太多，我放到 github上了，https://github.com/liuhuiCNN/tf_2_paddle_mnist

**Comment by peterzhang2029** [comment]
那你转的是什么模型呢？ 是哪一层的结果没有对上呢？

**Comment by liuhuiCNN** [comment]
已经解决，稍后我回总结后写成文档。
