### ISSUE TITLE
CAPI预测时如何指定gpu_id?

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#7388]
![image](https://user-images.githubusercontent.com/1027183/34760971-e087155e-f61c-11e7-8d8c-e5c35e0f2f51.png)

nvidia-smi显示占用了两块卡，如上图
但是在代码中指定了0号卡
I0110 15:38:39.331306 59200 Util.cpp:166] commandline:  **--use_gpu=True --gpu_id=0**

想只使用0号卡，请问应该如何传参？

**Comment by peterzhang2029** [comment]
可以通过CUDA_VISIBLE_DEVICE环境变量来指定使用具体的GPU
