### ISSUE TITLE
How to NOT load all data into memory during training

### ISSUE THREAD

**Issue by maxxfan** [PaddlePaddle/Paddle#739]
Hi, our CPU memory is running out when the training data set is big and Paddle stopped. Will Paddle load all the data from train_list into memory at once even when dataprovider is set to process only one data file?

We tried to set in provider cache=CacheType.NO_CACHE and it had no difference comparing to cache=CacheType.CACHE_PASS_IN_MEM

Since batch training does not need all data to be loaded during training. Is there a way to only load part of the data, i.e. load one file in train_list at one time? (The batch size is much smaller than each training data.) Or is there a way to set the CPU memory limit?

Thanks a lot!

**Comment by luotao1** [comment]
You can use `pool size`, see http://www.paddlepaddle.org/doc_cn/ui/data_provider/pydataprovider2.html#reference

And a demo in https://github.com/PaddlePaddle/Paddle/blob/develop/demo/seqToseq/dataprovider.py#L69

**Comment by lcy-seso** [comment]
I guess, the problem is probably caused by that you put all the training files in train.list.
Maybe, you can try method in the last part of this document.
https://github.com/PaddlePaddle/Paddle/blob/develop/doc_cn/ui/data_provider/pydataprovider2.rst

**Comment by maxxfan** [comment]
Thanks a lot guys! Problem is resolved by setting pool_size.
