### ISSUE TITLE
capi输入数据参数构造问题

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/Paddle#7401]
请问我在python里预测使用的输入数据是这样的， 对应在capi需要怎么构造这种输入数据作为 in_args

   testdata = [
            [[[-0.11242925, -0.1776307 ,  0.24714306],
             [-0.32270447 ,-0.1776307 ,  0.35258154],
             [-0.11242925, -0.07556718,  0.56345851]], [1]],
            [[[ 0.09784597 ,-0.38175775 , 0.45802003],
             [-0.00729164 ,-0.07556718,  0.35258154],
             [ 0.09784597, -0.27969423,  0.45802003]], [0]],
            [[[-3.5819704 ,  3.08840203, -0.49092632],
             [-4.21279606  ,1.25125862 , 0.66889699],
             [-3.68710801 , 2.78221146, -4.70846563]], [0]]
                ]

**Comment by lcy-seso** [comment]
你看看这个PR里面的文档 https://github.com/PaddlePaddle/Paddle/pull/6596/files 有没有帮助。
