### ISSUE TITLE
调用paddle.trainer.SGD出现错误

### ISSUE THREAD

**Issue by pardy218** [PaddlePaddle/Paddle#7403]
x = paddle.layer.data(name='x',type=paddle.data_type.dense_vector(3))
    predict = paddle.layer.fc(input = x,size=1,act=paddle.activation.Linear())
    y = paddle.layer.data(name='y',type=paddle.data_type.dense_vector(1))
    cost = paddle.layer.square_error_cost(input=predict, label=y)
    param = paddle.parameters.create(cost)
    optimizer = paddle.optimizer.Momentum(momentum=0)
    **trainer = paddle.trainer.SGD(cost = cost,parameters = param,update_equation = optimizer)**
在自己开发机上执行类似线性回归代码，执行到trainer = paddle.trainer.SGD(cost = cost,parameters = param,update_equation = optimizer)这一句时候报错，报错信息如下：
WARNING: Logging before InitGoogleLogging() is written to STDERR
F0110 17:47:11.161947 31590 ClassRegistrar.h:65] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: poly
*** Check failure stack trace: ***
Aborted

**Comment by peterzhang2029** [comment]
在构造模型之前加上`paddle.init(use_gpu=False)`试试

**Comment by pardy218** [comment]
加上以后解决了，谢谢
