### ISSUE TITLE
通过源码编译安装的paddlepaddle,想更新要不要先卸载之前的旧版本

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7407]
我的paddlepaddle的版本显示的还是0.9,但是paddlepaddle目前已经是0.11了.
我想升级paddlepaddle,我是使用源码编译再安装的,安装新的paddlepaddle要不要先卸载之前的版本,还是paddlepaddle会更新之前的版本

**Comment by luotao1** [comment]
[从源码编译](http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html)文档中的`pip install build/python/dist/*.whl`可以改成`pip install build/python/dist/*.whl -U` 。即需要卸载再安装。

**Comment by yeyupiaoling** [comment]
好的，谢谢
