### ISSUE TITLE
sparse predict problem

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#741]
涉及隐私，已删。

**Comment by llxxxll** [comment]
@shenshuijing 联系一下 @backyes 吧。

**Comment by backyes** [comment]
@shenshuijing 

请重新梳理下问题，然后提问。

**Comment by backyes** [comment]
@shenshuijing 

参考下：https://github.com/PaddlePaddle/Paddle/issues/364

**Comment by backyes** [comment]
@shenshuijing 
问题解决了么？
