### ISSUE TITLE
Missing head file dependency in cmake

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#7415]
When some header files are changed, the corresponding obj file is not rebuilt. Several examples:
1. In operator/ directory, the change of the header file of an operator will not cause rebuilding for that operator. This is caused by op_library() not adding the header file dependency
2. In platform/ directory, change of profiler.h does not cause rebuilding of profiler_test.cc. This is caused by cc_test()  not adding related header file dependency

**Comment by qingqing01** [comment]
As discussed with @hedaoyuan, and I make some experiments for `profiler_test.cc` and `mul_op.cc`. We found if the header file is changed and the timestamp is updated,  the source file will be rebuilt. But when the timestamp of the file is older, the source file will not be rebuilt. For example:

```cpp
cd build 
make -j12
# `ll paddle/platform/profiler_test`  to see the timestamp
cd Paddle
cp paddle/platform/profiler_test.cc .
vim paddle/platform/profiler_test.cc # and change this file
cd build 
make -j12
# `ll paddle/platform/profiler_test`  to see the timestamp, the timestamp is changed.
cd Paddle
mv profiler_test.cc paddle/platform/profiler_test.cc
cd build 
make -j12
# `ll paddle/platform/profiler_test`  to see the timestamp, the timestamp is not changed, but the file has been changed.
```

**Comment by luotao1** [comment]
make通过比较对应文件（规则的目标和依赖）的**最后修改时间**，来决定哪些文件需要更新、那些文件不需要更新。（可以参考[文章](http://blog.csdn.net/guotianqing/article/details/77802350)）

因此，上述代码中，`mv profiler_test.cc paddle/platform/profiler_test.cc`后，需要`touch paddle/platform/profiler_test.cc`才会触发编译。

**Comment by emailweixu** [comment]
It's very weird. I tried this several times on my machine before I report this issue.
But somehow this problem disappeared now.
