### ISSUE TITLE
Update documents about Docker images

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#742]
I forgot to update Chinese documents in the following PRs

- https://github.com/PaddlePaddle/Paddle/pull/736
- https://github.com/PaddlePaddle/Paddle/pull/723
- https://github.com/PaddlePaddle/Paddle/pull/716
- https://github.com/PaddlePaddle/Paddle/pull/629
- https://github.com/PaddlePaddle/Paddle/pull/697

I will update in the near future.

**Comment by luotao1** [comment]
close this issue due to above Chinese documents all have been updated.
