### ISSUE TITLE
关于分布式训练时，如何判断pserver正常启动？

### ISSUE THREAD

**Issue by drinktee** [PaddlePaddle/Paddle#745]
在分布式训练部署的时候，要先正常启动所有节点的pserver，才能进行paddle train 否则paddle train进程就会报错退出。我在部署的时候采取了简单的等待几秒钟，在进行训练。是否有一个更保险的方法来判断呢？我想到的是 

1.启动时通过脚本去检查一下pserver的日志，来判断是否已经正常启动，如果这样做的话，又需要一个方法通知所有trainer，这个pserver已经正常启动了。比如判断正常启动后开个webserver返回200

2.paddle启动完pserver后开个端口用来健康检查

**Comment by backyes** [comment]
@drinktee 

看起来，上述两种方法其实可以结合起来： 
* 在pserver外围启动脚本中增加一个**keepalive server**， 同时该s**erver间隔check 日志**，直到pserver输出指定日志，确认启动成功, 期间trainer的外围脚本要支持多次的连接尝试，不能因为一次**keepalive server** 的拒绝就fail。

这个应该能快速解决问题， 也比较符合最快的解决问题的思路。 

另外，我能想到的方法：
* 从仅仅保证trainer不被connection refused拒绝而宕机的话， 仅需提交trainer的connect的鲁棒性，比如多尝试几次，最长尝试5分钟之类的等等，这样能解决大部分问题，而且看起来也比较合理。
* 另外结合keepalive功能，也能实现此issue需要解决的问题。

从完美的需求角度，需要做到：
* trainer 能支持多次尝试的连接pserver，而不是目前遇到refused就挂机。 （这是即便仅仅使能pserver的健康检查，也是不能做到。因为健康检查服务本身也可能因为某些原因，启动被推迟，从而出现connection refused）
* pserver要支持健康检查。（这是另一个问题，支持pserver不仅仅在刚刚启动开始阶段的连接问题，这个需求根本上跟当前issue要解决的问题无关）
* 如果trainer的外围脚本也要支持多次尝试的连接pserver，否则问题就回归到trainer进程本身连接pserver类似的问题。

**Comment by backyes** [comment]
@drinktee @wangkuiyi 

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/pserver/LightNetwork.cpp#L412

```
  /// connect to server with socket daemon
  sock = rdma::connect(socketDaemon_, rdmaUri.c_str());
  PCHECK(sock) << "ERROR connect to server" << rdmaUri;

```
这里可以考虑增加鲁棒性，对````ECONNREFUSED``` error  进行处理， 即可解决眼前的问题， 即：
> trainer 能支持多次尝试的连接pserver，而不是目前遇到refused就挂机。 （这是即便仅仅使能pserver的健康检查，也是不能做到。因为健康检查服务本身也可能因为某些原因，启动被推迟，从而出现connection refused）

**Comment by drinktee** [comment]
恩，这个比较适合我的场景，也能解决大部分问题了
>在pserver外围启动脚本中增加一个keepalive server， 同时该server间隔check 日志，直到pserver输出指定日志，确认启动成功, 期间trainer的外围脚本要支持多次的连接尝试，不能因为一次keepalive server 的拒绝就fail。
