### ISSUE TITLE
Building the docker for rendering paddlepaddle.org fails.

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#7459]
The steps followed were:
1.  Pull the latest docker image: `docker pull paddlepaddle/PaddlePaddle.org:latest`
2.  Run the docker image to render the website: `docker run -it -v `pwd`:/var/content -p 8000:8000 paddlepaddle/paddlepaddle.org:latest`

The following error shows up every time and prevents it from rendering the `operators`, `executor` and `fluid`:

```
[100%] Building CXX object paddle/pybind/CMakeFiles/print_operators_doc.dir/print_operators_doc.cc.o
[100%] Linking CXX executable print_operators_doc
../../third_party/install/openblas/lib/libopenblas.a(setparam_OPTERON.o):(.data.rel+0x6a8): undefined reference to `ctrsm_ilnncopy_OPTERON'
collect2: error: ld returned 1 exit status
paddle/pybind/CMakeFiles/print_operators_doc.dir/build.make:283: recipe for target 'paddle/pybind/print_operators_doc' failed
make[3]: *** [paddle/pybind/print_operators_doc] Error 1
CMakeFiles/Makefile2:21096: recipe for target 'paddle/pybind/CMakeFiles/print_operators_doc.dir/all' failed
make[2]: *** [paddle/pybind/CMakeFiles/print_operators_doc.dir/all] Error 2
CMakeFiles/Makefile2:21108: recipe for target 'paddle/pybind/CMakeFiles/print_operators_doc.dir/rule' failed
make[1]: *** [paddle/pybind/CMakeFiles/print_operators_doc.dir/rule] Error 2
Makefile:4329: recipe for target 'print_operators_doc' failed
make: *** [print_operators_doc] Error 2
```
The above error shows up at the step : `make -j 8 paddle_docs print_operators_doc`

**Comment by luotao1** [comment]
You can try the command: https://github.com/PaddlePaddle/Paddle/blob/29b2693afb26dec21d4a031e5f85b9e8999f76f2/paddle/scripts/docker/build.sh#L109-L118

**Comment by luotao1** [comment]
Maybe we should update [write_docs_en.rst](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/write_docs_en.rst) and  [write_docs_cn.rst](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/write_docs_cn.rst).
