### ISSUE TITLE
Add ProgramDesc as an argument to Operator::Run

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#7468]
### Problem

We have OPs (recurrent op, while op, parallel do op, conditional block op, recv op) that needs BlockDesc or ProgramDesc inside Operator::Run. Because currently Operator::Run does not take ProgramDesc as an argument, we serialize them into attributes, and deserialize during run. It has several issues:

1. Hard to debug the ProgramDesc: the attribute is a binary string, we do not understand it when printing it out. Also Python `print(program.to_string(True))` will raise exception when parsing the message, because currently serialized ProgramDesc and BlockDesc is saved as `proto::string`, and Python `proto::string` parsing only support utf8 strings. Related issue: https://github.com/PaddlePaddle/Paddle/issues/7343 https://github.com/PaddlePaddle/Paddle/issues/7419 

1. The following code shows up in many places in our codebase:
    ```
    auto *block = Attr<framework::BlockDesc *>(kStepBlock);
    auto *program = block->Program();
    ```
    From my understanding its a workaround to the fact that Operator::Run does not take ProgramDesc as an argument. Otherwise we could use the index of the BlockDesc in the ProgramDesc as an attribute.

### Solution

Given some of our OP need ProgramDesc in run, one solution is to pass it as an argument of Operator::Run. I would oppose to this solution if OP does not use executor to run ProgramDesc. Currently OP can run program, I think it's reasonable to let OP know the ProgramDesc that it runs in.

**Comment by reyoung** [comment]
Only the program can be deserialized. We can use `paddle::framework::ProgramDesc(const proto::ProgramDesc &desc)`  to deserialize a program. There is no binary string is serialized for `BlockDesc`.

If we want to send just a `Block`, we should make that block belong to a program. Since we can run a program, not a block, it should not just send a `Block`.

**Comment by helinwang** [comment]
@reyoung thanks for reply! I have removed the part about BlockDesc -- since we can't serialize them.

Are there currently anyway to get the current running ProgramDesc in OperatorBase::Run? If not, point 1 still holds. There is need for getting ProgramDesc in OperatorBase::Run, serealizing them into Attribute is very awkward.

Btw, for another topic, since BlockDesc can not be serialized, we should stop using them as a Attribute (the code in point 2 will not work for distributed training when ProgramDesc is sent to another machine)

**Comment by typhoonzero** [comment]
I remember talking to @reyoung and he said that currently for `while_op`, the `attr` is using a pointer of `BlockDesc` and when serializing the `while_op`, this attr field will be serialized to the block id.

If this is true, then we don't need to serialize the `sub-program`, just adding more block and remember the block id. We may not need to use a pointer in attr, for it seems hacky.

**Comment by JiayiFeng** [comment]
The `BlockDesc` in an op's attribute can indeed be serialized and deserialized properly. Although we use a `BlockDesc *` in C++, what actually be serialized into Protobuf is the block's id. And during the deserialization, we rebuild the `BlockDesc *` via the block's id. Following code show details:
Serialization:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_desc.cc#L258-L286

Deserialization:
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/op_desc.cc#L100-L134

**Comment by helinwang** [comment]
Thank you @JiayiFeng @typhoonzero  @reyoung !
