### ISSUE TITLE
如何实现 切片 操作

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7487]
（1）v2接口和fulid接口是否可以混用？
答：除了数据的feed，其他接口不可以，各自是一套接口。（描述或许不够准确，但可以确定不能混用）

（2）如何实现 切片 操作
（3）比如一个数据是 [N,2]的softmax，我要针对[:,0] 和 [:,1]分别softmax，如何实现呢？也就是说softmax是否支持指定维度计算？

**Comment by JiayiFeng** [comment]
在你的需求中，softmax输入数据的两个维度，也就是`N`和`2`这两个维度，分别表示什么意义呢？

**Comment by chengduoZH** [comment]
该issue长时间没有反馈，可以先关闭了，如要继续讨论请再打开
