### ISSUE TITLE
在v2 fulid 框架下 如何 自定义 operation

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7489]
有些操作不满足要求的话，在v2 fulid 框架下 如何 自定义 operation？
比如切片操作
类似这个issue的要求
https://github.com/PaddlePaddle/Paddle/issues/7487

**Comment by Yancey1989** [comment]
> 有些操作不满足要求的话，在v2 fulid 框架下 如何 自定义 operation？

可以参考Op的开发文档：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_op_cn.md

> 比如切片操作

不知道[SplitOp](http://paddlepaddle.org/docs/develop/documentation/zh/operators.html#permalink-165-split)是否满足需求，可以将一个Variable切成多个Variable.

**Comment by liuhuiCNN** [comment]
@Yancey1989 
#7487 
这个问题有比较好的解决方法吗？

**Comment by chengduoZH** [comment]
@liuhuiCNN 您的问题@Yancey1989已给出回答，这个issue可以关掉了，如果有其他问题，请在其他issue中讨论，谢谢！
