### ISSUE TITLE
CPU运行classification 出现的问题。

### ISSUE THREAD

**Issue by balabalalilili** [PaddlePaddle/Paddle#749]
![2016-12-07 00-50-11](https://cloud.githubusercontent.com/assets/23418049/20936275/ffb437bc-bc1c-11e6-9952-c5557eb34ee6.png)
 matplotlib已经安装。。这里到底还有多少问题？看得有点懵。

**Comment by gangliao** [comment]
http://www.paddlepaddle.org/doc/demo/image_classification/image_classification.html


We have prepared a script to download and process CIFAR-10 dataset. The script will download CIFAR-10 dataset from the official dataset. It will convert it to jpeg images and organize them into a directory with the required structure for the tutorial. Make sure that you have installed pillow and its dependents. Consider the following commands:
```
# install pillow dependents
sudo apt-get install libjpeg-dev
pip install pillow
```

**Comment by balabalalilili** [comment]
@gangliao   已经装好了的。

**Comment by balabalalilili** [comment]
PIL也已经装好了的

**Comment by gangliao** [comment]
还有出错吗？
看你出错的意思，确实是说PIL module没有找到。
一般来说，`pip install pillow`， 装上pillow就行了

**Comment by balabalalilili** [comment]
@gangliao   还没好。。装好了为什么提示没有这个模块？还需要安装什么吗

**Comment by gangliao** [comment]
你可以尝试：
```bash
export PYTHONPATH=/usr/lib/python2.7/site-packages/:$PYTHONPATH
```

实在不行的话，我们官方推荐使用docker安装paddle.
http://www.paddlepaddle.org/doc_cn/build_and_install/install/docker_install.html

**Comment by balabalalilili** [comment]
@gangliao  
![2016-12-07 18-12-16](https://cloud.githubusercontent.com/assets/23418049/20963564/d7e71f4c-bca8-11e6-9c4e-484481f93043.png)
我这个应该是docker版本的吧。

**Comment by gangliao** [comment]
@reyoung  docker 之前没出现这个问题吧 ？？

**Comment by balabalalilili** [comment]
@gangliao  我解决了。我在docke里面 输入这个 pip install pillow  貌似就好像可以了。 不知道对不对，没出现那个了

**Comment by gangliao** [comment]
明白了 谢谢

**Comment by balabalalilili** [comment]
@gangliao 谢谢    非常感谢
