### ISSUE TITLE
paddle支持多任务吗

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#7500]
multi-task任务，比如同时预估点击率和阅读时长，我这边没找到相关的

**Comment by windy444** [comment]
@liuhuiCNN 我看上面的issue，是指的infer输出的多个。训练的时候，可以支持多个损失函数吗？

**Comment by JiayiFeng** [comment]
多个损失函数的问题可以参考这个issue：https://github.com/PaddlePaddle/Paddle/issues/4191
