### ISSUE TITLE
paddlepaddle在进行图像训练的时候出现内存不足进程被杀死的问题。。。

### ISSUE THREAD

**Issue by JadyXuan** [PaddlePaddle/Paddle#7501]
使用的train.py的源码基本和官方示例一致，网络是官方教程中图像分类的vgg网络，但是使用了自己的图像数据集，每张大约200k大小，batch_size=50，learning_rate大约比官方使用的cifar数据集时设定的低一个数量级，为什么还是会把内存跑完？占用内存是跟哪些参数有关系的呢？
（刚刚接触神经网络的萌新提问：3）

**Comment by rulai-huiyingl** [comment]
同……
数据跑在GPU上跑了一天多以后，跑个几十个pass了，模型都训练得差不多了，进程说out of memory停止了。

**Comment by yeyupiaoling** [comment]
* 可以试试设置缓存大小buf_size,这个改小一点应该可以的.
* 你的batch_size怎么不是指数倍
* 想问一下,你电脑的配置是多大,内存小于4G就别跑了

**Comment by yeyupiaoling** [comment]
@rulai-huiyingl 
好像不断训练,它的内存占用率会一直增加的,它训练的权重参数一直报存在内存中

**Comment by JadyXuan** [comment]
@yeyupiaoling 
    buf_size 可以比batch_size 要小的吗？我这两个都是设置为50的。。。
    嗯，指数倍是什么意思啊。。？指数方法表示还是什么？
    电脑内存的话在虚拟机里配置了5000MB的。。跑cifar-10数据集都可以的。。buf_size好几千都没有问题。

> 这次buf_size只有5，batch_size只有2 。。但是还是炸了内存。。。T_T

![default](https://user-images.githubusercontent.com/35390572/34927579-1c8f7342-f9f2-11e7-8e26-64474e8afaa7.PNG)

**Comment by JadyXuan** [comment]
@yeyupiaoling  
![default](https://user-images.githubusercontent.com/35390572/34927747-77c880b8-f9f3-11e7-8657-2dc5be0d2151.PNG)
是不是这里的速率参数设定有问题呢？我猜learning_rate是越小训练速率越慢的吧。。。

**Comment by yeyupiaoling** [comment]
@JadyXuan 
* 跟速率参数是没有太大的关系的，`learning_rate`这个是训练速度
* 你要知道cifar的图片只有32\*32，只有几K
* 在`reader.py`中，你设置的大小是多少
* 你的报错信息是什么，

**Comment by zengjialuo** [comment]
遇到同样的问题，我是使用ResNet50-imageNet模型进行预测，batch_size=128，大约预测20w样本后就会报cuda out of memory. 当我改成batch_size=64之后，问题同样复现，也是大约20w样本后报错。

**Comment by JadyXuan** [comment]
@yeyupiaoling  
嗯。。reader.py里面忘记设置了。。。QwQ
![default](https://user-images.githubusercontent.com/35390572/34934512-b45570e6-fa15-11e7-8ced-3a4fb4fe70b8.PNG)
这次改成buf_size=64，batch_size=16，再跑了一次，报错从“已杀死”变成了“已放弃”。。
![1](https://user-images.githubusercontent.com/35390572/34934616-129edf8e-fa16-11e7-8ca5-e0b75077d091.PNG)
@zengjialuo 
噫，我都是跑都没开始跑就挂掉了。。

**Comment by yeyupiaoling** [comment]
这个厉害了，你的图片设置大小是多少

**Comment by JadyXuan** [comment]
@yeyupiaoling 
![default](https://user-images.githubusercontent.com/35390572/34935271-4c5a814a-fa18-11e7-8280-754f2b90f9b9.PNG)
是这个吗？

**Comment by yeyupiaoling** [comment]
是的，设置小一点看看，其他地方也对应设置小一些

**Comment by JadyXuan** [comment]
@yeyupiaoling 
谢谢啦，设置为3*64*64以后能够开始第一个pass。。但是后面这个报错是什么鬼？
![default](https://user-images.githubusercontent.com/35390572/34970252-4046b752-faae-11e7-9ebb-5f62c0cf87da.PNG)
我的数据集图片都是png格式的，shape应该是支持png格式的吧。。。而且第一个pass能够读了，为什么后面的怎么就报错了T_T

会不会是list路径错误或者什么的呢？

**Comment by JadyXuan** [comment]
@yeyupiaoling 
谢谢啦，问题解决啦
不过我的图片像素只有64*64，如果要做人脸识别的话是不是太小了一点？

**Comment by yeyupiaoling** [comment]
@JadyXuan 
我觉得不小了

**Comment by JadyXuan** [comment]
@yeyupiaoling 
诶。。64*64像素也能分辨不同的人的脸的细节的吗。。。？
