### ISSUE TITLE
Simplifying dynamic rnn

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#7509]
The design should be such that the user does not need to worry about batch at all. The code in test_dyn_rnn.py is too complex. User should not need to write code such as:
https://github.com/PaddlePaddle/Paddle/blob/df9c13a816dfdba77d1fb84101ec51a47fc2ef24/python/paddle/v2/fluid/tests/test_dyn_rnn.py#L27-L30
https://github.com/PaddlePaddle/Paddle/blob/df9c13a816dfdba77d1fb84101ec51a47fc2ef24/python/paddle/v2/fluid/tests/test_dyn_rnn.py#L55
https://github.com/PaddlePaddle/Paddle/blob/df9c13a816dfdba77d1fb84101ec51a47fc2ef24/python/paddle/v2/fluid/tests/test_dyn_rnn.py#L60
https://github.com/PaddlePaddle/Paddle/blob/df9c13a816dfdba77d1fb84101ec51a47fc2ef24/python/paddle/v2/fluid/tests/test_dyn_rnn.py#L62
Why can't we make it as easy as v2 recurrent_group or fluid StaticRNN?

**Comment by emailweixu** [comment]
For while_op, we should make it behave like if_else_op, meaning that the condition is a vector with size=batch_size. Each dimension of cond is responsible for one instance in the batch.

**Comment by emailweixu** [comment]
We should have a DynamicRNN with same usage as StaticRNN.

**Comment by reyoung** [comment]
@emailweixu 
We have the Python syntax sugar, `DynamicRNN`, to wrap them all. It just like `recurrent_group` before and uses the same API from https://github.com/PaddlePaddle/talks/blob/develop/paddle-gtc-china.pdf

The usage is shown in the below unit test.
https://github.com/PaddlePaddle/Paddle/blob/9deb1756a2caac29eb91c2d21888267cea50eade/python/paddle/v2/fluid/tests/test_dyn_rnn.py#L94-L101

The complex unit test is just a  low-level test for the syntax sugar `DynamicRNN`. It because we develop the low-level APIs first, and make the low-level APIs correctly. And we develop the syntax sugar and write the complete test by using this syntax sugar.

**Comment by emailweixu** [comment]
I see. But I think we still need a simpler while_op which can handle each sample in a batch independently.

**Comment by jacquesqiao** [comment]
@emailweixu do you mean the syntax like below, each candition can have an independent branch to handle?
```python
cond = less_then(...)
ie = pd.if_else(cond)
with ie.true_block():
    d = pd.layer.add(x, y)
    ie.output(d, pd.layer.softmax(d))
with ie.false_block():
    d = pd.layer.fc(z)
    ie.output(d, d+1)
o1, o2 = ie(cond)
```

like:
```python
cond = less_then(sequence, condition)
rnn = pd.DynamicRNN(cond)
with rnn.true_block():
     in_ = rnn.step_input(sent_emb) 
     mem = rnn.memory(shape=[100], dtype='float32') 
     out_ = fluid.layers.fc(input=[in_, mem], size=100, act='tanh') 
     rnn.update_memory(mem, out_) 
     rnn.output(out_) 
with rnn.false_block():
     in_ = rnn.step_input(sent_emb) 
     mem = rnn.memory(shape=[100], dtype='float32') 
     out_ = fluid.layers.fc(input=[in_, mem], size=200, act='relu') 
     rnn.update_memory(mem, out_) 
     rnn.output(out_) 
o = rnn()
```

**Comment by jacquesqiao** [comment]
I have a design of scalar switch case op, maybe the interface for this can be like:
<https://github.com/PaddlePaddle/Paddle/pull/8031>

```python
rnn = pd.DynamicRNN()
with rnn.block():
     in_ = rnn.step_input(sent_emb)
     cond1 = logic_op(in_, condition1)
     cond2 = logic_op(in_, condition2)
     switch = SwitchOp()
     with switch.case(cond1)
	     mem = rnn.memory(shape=[100], dtype='float32') 
	     out_ = fluid.layers.fc(input=[in_, mem], size=100, act='tanh') 
	     rnn.update_memory(mem, out_) 
	     rnn.output(out_)
     with switch.case(cond2)
	     mem = rnn.memory(shape=[100], dtype='float32') 
	     out_ = fluid.layers.fc(input=[in_, mem], size=200, act='relu') 
	     rnn.update_memory(mem, out_) 
	     rnn.output(out_) 
o = rnn()
```

**Comment by emailweixu** [comment]
What I am thinking is something like the following:

```python
cond = calc_initial_condition()
loop = fluid.layers.While(cond=cond)
with loop.block():
      mem = memory(boot=x)
      out = layers.fc(input=mem, size=100)
      p = layers.fc(input=out, size=1, act='sigmoid')
      layers.less_than(y, 0.5, cond=cond)
      loop.update_memory(mem, out)
      loop.output(out)
o = loop()
```

**Comment by jacquesqiao** [comment]
Sorry I am a little confused about the above code, I write my questions in the comment below.
```python
cond = calc_initial_condition()
loop = fluid.layers.While(cond=cond)
with loop.block():
      mem = memory(boot=x)
      out = layers.fc(input=mem, size=100)
      p = layers.fc(input=out, size=1, act='sigmoid')
      # 1. p is not used in the following code, is y ==> p ?
      # 2. what is the less_than used for?
      layers.less_than(y, 0.5, cond=cond)
      loop.update_memory(mem, out)
      loop.output(out)
o = loop()
```

**Comment by emailweixu** [comment]
Sorry, y should be p. less_than is for calculating termination condition
