### ISSUE TITLE
Questions about /paddle/math

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#751]
1. Why class `Allocator` needs method [getName](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/Allocator.h#L34)?

**Comment by gangliao** [comment]
Yeah, it looks like an unnecessary function which could be removed.

**Comment by hedaoyuan** [comment]
PoolAllocator里面有一个allocator_成员，allocator_不带名字，那么PoolAllocator需要自己记录当前的allocator_是一个什么类型的。

**Comment by reyoung** [comment]
We currently using `paddle::memory` to manage allocation.  Closed because of #2979.
