### ISSUE TITLE
如果我使用的图片的长方形的,那数据应该怎么设置

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7510]
在做图片分类时,使用[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13)读取自定义的图片,下面的是224 \* 224的,如果我的图片是长方形的的200 \* 300 的,该怎么办
```python
def train_mapper(sample):
    '''
    map image path to type needed by model input layer for the training set
    '''
    img, label = sample
    img = paddle.image.load_image(img)
    img = paddle.image.simple_transform(img, 256, 224, True)
    return img.flatten().astype('float32'), label
```

**Comment by liuhuiCNN** [comment]
你全用 paddle 的函数的话，没有问题的。
你注意好网络中间的 padding 的问题就OK。

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 那我的`crop_size`是设置成200,还是300

**Comment by liuhuiCNN** [comment]
@yeyupiaoling crop_size就是随机裁剪，数据增强的一种方式。crop_size应该跟你的网络输入一样大小。

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 我好像懂了,对下面这几行代码处理就行了吧
```python
h_start = np.random.randint(0, h - size + 1)
w_start = np.random.randint(0, w - size + 1)
h_end, w_end = h_start + size, w_start + size
```

**Comment by liuhuiCNN** [comment]
@yeyupiaoling 你先试试，其他地方你得确认也没有问题。因为paddle默认都是按照正方形处理的，你得改成保持一致。

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 好谢谢

**Comment by luotao1** [comment]
@yeyupiaoling 如果使用长方形输入，可以设置`height`和`width`，不用修改源码。
https://github.com/PaddlePaddle/Paddle/blob/496d64ebdb3f0c81f4684b9f48fdef90f9d94547/python/paddle/trainer_config_helpers/tests/configs/test_maxout.py#L5

**Comment by yeyupiaoling** [comment]
@luotao1 哇塞!有涨知识了.但是我看了一下代码,你这个是输入数据的设置.这个解决了,但是怎么读取数据呢?就是要训练的reader数据,下面用到的trainer_reader是在[这里的](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L27)
```python
trainer_reader = myReader.train_reader(train_list="../data/%s/trainer.list" % all_class_name)
reader = paddle.batch(reader=paddle.reader.shuffle(reader=trainer_reader,
                                                           buf_size=50000),
                              batch_size=128)
```

**Comment by yeyupiaoling** [comment]
既然说到这个问题,那顺便问一下,[https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L13)
```python
img = paddle.image.simple_transform(img, 256, 224, True)
```
其中有一个参数是
```
resize_size（int） - 调整大小的图像的较短边缘长度。
```
我一直搞不懂这个参数有什么用?

**Comment by luotao1** [comment]
https://github.com/PaddlePaddle/Paddle/issues/7510#issuecomment-357567715 说的是v1的接口。在v2中，请使用：`paddle.data_type.dense_array`。
参考示例：https://github.com/PaddlePaddle/DeepSpeech/blob/develop/tools/tune.py#L96 
reader返回数据是np.array

**Comment by yeyupiaoling** [comment]
@luotao1 嗯嗯了解，在[book的第三章也是这个](https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/train.py#L33)
```python
    image = paddle.layer.data(
        name="image", type=paddle.data_type.dense_vector(datadim))
```
顺便问一下，你这样引用代码是怎么做到的
![image](https://user-images.githubusercontent.com/26297768/34926385-050da782-f9ea-11e7-87e6-641ce2a83c9e.png)

**Comment by yeyupiaoling** [comment]
在下班前，能回答我上一个问题吗？[#7510 (comment)](https://github.com/PaddlePaddle/Paddle/issues/7510#issuecomment-357573347)

**Comment by luotao1** [comment]
引用代码时，需要commit，不能在develop分支里直接贴过来。下面是那张图的代码。
```
https://github.com/PaddlePaddle/Paddle/blob/496d64ebdb3f0c81f4684b9f48fdef90f9d94547/python/paddle/trainer_config_helpers/tests/configs/test_maxout.py#L5
```

**Comment by yeyupiaoling** [comment]
@luotao1 GET到了
https://github.com/PaddlePaddle/Paddle/blob/496d64ebdb3f0c81f4684b9f48fdef90f9d94547/python/paddle/trainer_config_helpers/tests/configs/test_maxout.py#L5

**Comment by yeyupiaoling** [comment]
[#7510 (comment)](https://github.com/PaddlePaddle/Paddle/issues/7510#issuecomment-357573347)这个问题已在 #7175 得到解决，谢谢
