### ISSUE TITLE
paddle 支持网络中有多个输出吗？

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7511]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/inference.py

infer 函数针对一个输入，是否支持输出多个变量？

类似问题  #7500

**Comment by yeyupiaoling** [comment]
你说的多个输出变量,是指多个预测值吗?

**Comment by liuhuiCNN** [comment]
@yeyupiaoling 是的比如多任务，例如人脸性别年龄回归，年龄是一个输出，性别是一个输出。

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 这个就高级了,小弟不懂了

**Comment by luotao1** [comment]
支持多个预测值，可以参考如下用法：
https://github.com/PaddlePaddle/Paddle/blob/46641c6361ebcf4c9fab79a70c4251ce4329a0f7/python/paddle/v2/inference.py#L116-L133

**Comment by yeyupiaoling** [comment]
@luotao1 这个好像只能是一个parameters吧，这种情况下要使用到多个parameters吗？

**Comment by luotao1** [comment]
用同一个网络来预测多个输出的话，网络参数都是一样的，所以是一个parameters。

**Comment by yeyupiaoling** [comment]
多个prediction可以训练出一个parameters，这个还真没试过，这个issue要收藏一下，到时候遇到实际需求好好看看

**Comment by luotao1** [comment]
> 多个prediction可以训练出一个parameters

这个parameters是训练好的网络参数，是用它来做预测的。不是prediction训练出来的。

**Comment by yeyupiaoling** [comment]
prediction这个不是有神经网络通过Softmax归一化的到的分类器吗？之后不是会用到这分类器训练网络参数吗？

**Comment by liuhuiCNN** [comment]
已经搞定，谢谢！ @luotao1
