### ISSUE TITLE
在图片分类中,使用自定义数据在vgg模型训练,如果加上了BN层,反而没办法收敛

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7512]
* 在自定义数据图片中,如果使用安装book中的[第三章图片分类](https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/README.cn.md#vgg-1),如果按照这里网络,使用后果BN层,错误率一直不变的
* trainer_cost是在收敛的,但是test_cost不但没降,反而上升了,如图:
### 下面这张图是trainer_cost和test_cost的图,因为test_cost是每一个pass才打印的,所以数量比较少
![t1](https://user-images.githubusercontent.com/26297768/34917230-8c36d3d0-f97e-11e7-9062-f2692fe74eaa.png)
### 这个是单独trainer_cost的,可以看到是一直在收敛的
![t2](https://user-images.githubusercontent.com/26297768/34917234-94dc9e20-f97e-11e7-9a76-e64f02f9b037.png)
### 这个是单独test_cost的,它反而一直在上升
![t3](https://user-images.githubusercontent.com/26297768/34917236-9a3e35fe-f97e-11e7-8422-ec5e1b484a57.png)
* 而Test的'classification_error_evaluator'一直都是0.6666666865348816,没有变过,具体的日志在最后

使用的网络vgg模型是下面这个:
```python
def vgg_bn_drop(input):
    def conv_block(ipt, num_filter, groups, dropouts, num_channels=None):
        return paddle.networks.img_conv_group(
            input=ipt,
            num_channels=num_channels,
            pool_size=2,
            pool_stride=2,
            conv_num_filter=[num_filter] * groups,
            conv_filter_size=3,
            conv_act=paddle.activation.Relu(),
            conv_with_batchnorm=True,
            conv_batchnorm_drop_rate=dropouts,
            pool_type=paddle.pooling.Max())

    conv1 = conv_block(input, 64, 2, [0.3, 0], 3)
    conv2 = conv_block(conv1, 128, 2, [0.4, 0])
    conv3 = conv_block(conv2, 256, 3, [0.4, 0.4, 0])
    conv4 = conv_block(conv3, 512, 3, [0.4, 0.4, 0])
    conv5 = conv_block(conv4, 512, 3, [0.4, 0.4, 0])

    drop = paddle.layer.dropout(input=conv5, dropout_rate=0.5)
    fc1 = paddle.layer.fc(input=drop, size=512, act=paddle.activation.Linear())
    bn = paddle.layer.batch_norm(
        input=fc1,
        act=paddle.activation.Relu(),
        layer_attr=paddle.attr.Extra(drop_rate=0.5))
    fc2 = paddle.layer.fc(input=bn, size=512, act=paddle.activation.Linear())
    return fc2
```
如果使用的是没加上BN层，使用这个错误率是会一直下降的

### 具体输出日志
```
Pass 0, Batch 0, Cost 1.206446, {'classification_error_evaluator': 0.6796875}
.......................
Test with Pass 0, {'classification_error_evaluator': 0.6666666865348816}

Pass 1, Batch 0, Cost 1.167446, {'classification_error_evaluator': 0.6484375}
.......................
Test with Pass 1, {'classification_error_evaluator': 0.6666666865348816}

Pass 2, Batch 0, Cost 1.123364, {'classification_error_evaluator': 0.65625}
.......................
Test with Pass 2, {'classification_error_evaluator': 0.6666666865348816}

Pass 3, Batch 0, Cost 1.150555, {'classification_error_evaluator': 0.6796875}
.......................
Test with Pass 3, {'classification_error_evaluator': 0.6666666865348816}

Pass 4, Batch 0, Cost 1.150093, {'classification_error_evaluator': 0.65625}
.......................
Test with Pass 4, {'classification_error_evaluator': 0.6666666865348816}

Pass 5, Batch 0, Cost 1.142492, {'classification_error_evaluator': 0.6484375}
.......................
Test with Pass 5, {'classification_error_evaluator': 0.6666666865348816}

Pass 6, Batch 0, Cost 1.160523, {'classification_error_evaluator': 0.625}
.......................
Test with Pass 6, {'classification_error_evaluator': 0.6666666865348816}

Pass 7, Batch 0, Cost 1.092726, {'classification_error_evaluator': 0.65625}
.......................
Test with Pass 7, {'classification_error_evaluator': 0.6666666865348816}

Pass 8, Batch 0, Cost 1.111178, {'classification_error_evaluator': 0.5859375}
.......................
Test with Pass 8, {'classification_error_evaluator': 0.6666666865348816}

Pass 9, Batch 0, Cost 1.139677, {'classification_error_evaluator': 0.6640625}
.......................
Test with Pass 9, {'classification_error_evaluator': 0.6666666865348816}

Pass 10, Batch 0, Cost 1.139612, {'classification_error_evaluator': 0.671875}
.......................
Test with Pass 10, {'classification_error_evaluator': 0.6666666865348816}

Pass 11, Batch 0, Cost 1.116644, {'classification_error_evaluator': 0.71875}
.......................
Test with Pass 11, {'classification_error_evaluator': 0.6666666865348816}

Pass 12, Batch 0, Cost 1.120817, {'classification_error_evaluator': 0.5703125}
.......................
Test with Pass 12, {'classification_error_evaluator': 0.6666666865348816}

Pass 13, Batch 0, Cost 1.078313, {'classification_error_evaluator': 0.578125}
.......................
Test with Pass 13, {'classification_error_evaluator': 0.6666666865348816}

Pass 14, Batch 0, Cost 1.080923, {'classification_error_evaluator': 0.5625}
.......................
Test with Pass 14, {'classification_error_evaluator': 0.6666666865348816}

Pass 15, Batch 0, Cost 1.049495, {'classification_error_evaluator': 0.546875}
.......................
Test with Pass 15, {'classification_error_evaluator': 0.6666666865348816}

Pass 16, Batch 0, Cost 1.084606, {'classification_error_evaluator': 0.5625}
.......................
Test with Pass 16, {'classification_error_evaluator': 0.6666666865348816}

Pass 17, Batch 0, Cost 1.046121, {'classification_error_evaluator': 0.578125}
.......................
Test with Pass 17, {'classification_error_evaluator': 0.6666666865348816}

Pass 18, Batch 0, Cost 0.957317, {'classification_error_evaluator': 0.4375}
.......................
Test with Pass 18, {'classification_error_evaluator': 0.6666666865348816}

Pass 19, Batch 0, Cost 0.998624, {'classification_error_evaluator': 0.4453125}
.......................
Test with Pass 19, {'classification_error_evaluator': 0.6666666865348816}

Pass 20, Batch 0, Cost 0.929192, {'classification_error_evaluator': 0.4375}
.......................
Test with Pass 20, {'classification_error_evaluator': 0.6666666865348816}

Pass 21, Batch 0, Cost 0.836099, {'classification_error_evaluator': 0.3671875}
.......................
Test with Pass 21, {'classification_error_evaluator': 0.6666666865348816}

Pass 22, Batch 0, Cost 0.748739, {'classification_error_evaluator': 0.3515625}
.......................
Test with Pass 22, {'classification_error_evaluator': 0.6666666865348816}

Pass 23, Batch 0, Cost 0.746704, {'classification_error_evaluator': 0.3515625}
.......................
Test with Pass 23, {'classification_error_evaluator': 0.6666666865348816}
```

**Comment by qingqing01** [comment]
上述加BN的配置是Book的例子，在CIFAR-10上可以收敛，这个可以确认吧。


> 如果使用的是没加上BN层,使用这个https://github.com/PaddlePaddle/models/blob/develop/image_classification/vgg.py,错误率是会一直下降的

 不要使用这个配置，直接在你上述包含BN的配置中，设置`conv_with_batchnorm=False`，不使用BN，看看可否收敛？
> Test with Pass 23, {'classification_error_evaluator': 0.6666666865348816}

看着`classification_error_evaluator`保持不变，一直是同一个数字，你的数据是多少类别呢？看看是不是每次test输出的分类概率都一模一样？
验证下在其他标注数据集(例如flowers-102)的收敛情况？
你是用的Batch Size多大呢？
使用的是CPU还是GPU训练呢？

**Comment by yeyupiaoling** [comment]
@qingqing01 
1. 有BN的配置的，在cifar-10是可以正常收敛的，这个可以确认，只是在使用我自定义数据是不能够收敛
2. 如果使用[https://github.com/PaddlePaddle/models/blob/develop/image_classification/vgg.py](https://github.com/PaddlePaddle/models/blob/develop/image_classification/vgg.py)，自定义数据可以收敛的
3. 对的，如果用有BN配置训练出的model，它的预测结果对的概率都是一样的，我有两个数据集，这个有3个类别
4. 关于test_cost和trainer_cost，这跟book中的例子不是很一样，我是保存了cost在TXT中，到训练完了再执行代码显示它的
5. flowers-102这个数据集我一直没办法下载，说以没测试
6. 我的batch_size是128
7. 我使用的是CPU

**Comment by yeyupiaoling** [comment]
@qingqing01 
* 我代码的地址是：[https://github.com/yeyupiaoling/TestImagesClassify](https://github.com/yeyupiaoling/TestImagesClassify)
* https://github.com/yeyupiaoling/TestImagesClassify/blob/a0b9b31331c26255a7318ef96aedefa6e8cd0cd5/code/PaddleUtil.py#L55-L59 是调用不同的vgg，第一个是有BN层的，第二个没有
* 在这里可以开始训练https://github.com/yeyupiaoling/TestImagesClassify/blob/299bcd3704e48e6413cb5375674ccb2ca82ef9a4/code/Test.py#L14-L31

**Comment by qingqing01** [comment]
[vgg_bn_drop ](https://github.com/yeyupiaoling/TestImagesClassify/blob/a0b9b31331c26255a7318ef96aedefa6e8cd0cd5/code/PaddleUtil.py#L56)和 [vgg.vgg16](https://github.com/yeyupiaoling/TestImagesClassify/blob/a0b9b31331c26255a7318ef96aedefa6e8cd0cd5/code/PaddleUtil.py#L58)的配置还是有所不同，两个配置dropout、fc层size都不一样。能不能在[`vgg_bn_drop`](https://github.com/yeyupiaoling/TestImagesClassify/blob/a0b9b31331c26255a7318ef96aedefa6e8cd0cd5/code/PaddleUtil.py#L56)，但将[`conv_with_batchnorm `](https://github.com/yeyupiaoling/TestImagesClassify/blob/a0b9b31331c26255a7318ef96aedefa6e8cd0cd5/code/PaddleUtil.py#L26)参数设置为False， 看`vgg_bn_drop`这个配置在不设置BN时，test是否收敛？ 如果收敛，再来分析是否为BN的问题？是否为train集的moving mean/var和test集分布相差较大？ 另外，看你的配置只有3类，`classification_error_evaluator=0.6666666865348816`看着是完全随机的。

**Comment by yeyupiaoling** [comment]
@qingqing01 
* 我现在把conv_with_batchnorm参数设置为False,在训练,到明天才看到效果,到明天我再把cost显示看看,但我现在已经看到了Test的错误率是有在变化了
* 青青姐能帮我看看问题 #7185 吗?这个也是vgg神经网络模型的问题

**Comment by yeyupiaoling** [comment]
@qingqing01 
数据已经出来了,可以收敛的,也能正常预测了,您说的
> 是否为train集的moving mean/var和test集分布相差较大？

这个是什么问题

## trainer_cost图片
![s1](https://user-images.githubusercontent.com/26297768/34967513-5ceae10e-fa9e-11e7-8f22-19c454db7d61.png)
## Test_cost图片
![s2](https://user-images.githubusercontent.com/26297768/34967548-9ffa25f4-fa9e-11e7-96c2-42a493c8dfcb.png)

**Comment by qingqing01** [comment]
辛苦反馈。我暂时没想到为啥在你的数据集上加BN test集不收敛。仔细看了下你代码，发现：

1.  你的[image_size=32](https://github.com/yeyupiaoling/TestImagesClassify/blob/master/code/PaddleUtil.py#L215)，在你的配置里也就是crop_size=32，但[resize_size=256](https://github.com/yeyupiaoling/TestImagesClassify/blob/master/code/MyReader.py#L15)。这两个大小相差太大。crop出来太小了。 你的原始图片多大呢? 如果较大的话，crop_size设置为224；如果较小的话，resize_size=34或36试试。

2. test集处理，[`img = paddle.image.simple_transform(img, 256, self.imageSize, True)`](https://github.com/yeyupiaoling/TestImagesClassify/blob/master/code/MyReader.py#L24) 这里最后需要设置False，这个参数表示`is_train`， test集一般只取中间的部分测试，不随机取。

关于BN的问题，我们也在flowers上验证看看。

**Comment by yeyupiaoling** [comment]
@qingqing01 
1. 我的原始图片都图片很大，图片都在[这里](https://github.com/yeyupiaoling/TestImagesClassify/tree/master/images/vegetables)，您可以看看
2. 如果改成224的话，可能好几天都没有结果，我电脑配置比较低，crop_size为32时，一个晚上也是只有50个pass，设置成其他大小的话，可以试试
3. 我是看到[这里](https://github.com/PaddlePaddle/models/blob/develop/image_classification/reader.py#L23)也是使用把is_train设置成True

**Comment by yeyupiaoling** [comment]
@qingqing01 
当把resize_size设为36时,Test cost是可以收敛的,Test的错误率也在下降,能够正常预测

**Comment by qingqing01** [comment]
> 当把resize_size设为36时,Test cost是可以收敛的,Test的错误率也在下降,能够正常预测

是说加了BN之后Test集上也可以收敛是吗？

> 当把resize_size设为224时,程序就崩掉了

具体错误是啥？

**Comment by yeyupiaoling** [comment]
> 是说加了BN之后Test集上也可以收敛是吗？

没错，加了BN 层也可以收敛了
> 具体错误是啥？

没有报什么错，直接停止了，应该是我电脑配置低的问题吧，我使用的是CPU，8G内存而已

**Comment by yeyupiaoling** [comment]
@qingqing01 青青姐
>之前的问题是在图像分类中，使用VGG16模型来训练自定义的数据集，当启用BN层模型无法收敛，如果关闭了BN就正常收敛

我好像发现问题所在了，我使用我自己的数据集是比较小的，当开启了BN，这样同时也会使用dropout层。因为数据集比较小，启用了dropout会使得特征丢失更多，从而无法收敛，关闭了BN层，也就关闭了dropout层。

验证：我同样把启用BN层，然后把全部的drop率设置为0，这模型也是可以收敛的。

我的设想是否准确？谢谢

**Comment by JiayiFeng** [comment]
我觉得你说的是一个原因。另外当训练数据集非常小时，网络中可能只有部分神经元在起作用，这时候再加上随机的dropout可能会使每次起作用的神经元更少，导致不收敛。

**Comment by yeyupiaoling** [comment]
好的，谢谢回答~
