### ISSUE TITLE
模型训练约20个小时后failed

### ISSUE THREAD

**Issue by stephenchan0693** [PaddlePaddle/Paddle#7515]
模型训练约20个小时后failed，但是查看train.log中没有报错，upload_model.log中有“upload_model.sh: line 51:  2226 Killed                  sleep 30” 报错，请paddle值班人员帮忙看看，谢谢~
附上任务链接：

**Comment by typhoonzero** [comment]
可能是集群系统把job kill了吧。

**Comment by gongweibao** [comment]
Feel free to reopen it!
