### ISSUE TITLE
Need python wrapper for GLU(gated linear unit)

### ISSUE THREAD

**Issue by guoshengCS** [PaddlePaddle/Paddle#7523]
Need python wrapper for GLU(gated linear unit) to implement ConvS2S.

**Comment by danFromTelAviv** [comment]
below is a keras ( python ) gated linear unit. 
The use is : 
net = glu_block(net, filter_len, dilation_rate)

def glu_block(input, filter_len, dilation_rate):
    num_filters_in = K.int_shape(input)[-1]
    conv_filter = Conv1D(num_filters_in, filter_len, dilation_rate=dilation_rate,
                         kernel_initializer='he_normal', padding="same")(input)
    gate_filter = Conv1D(num_filters_in, filter_len, dilation_rate=dilation_rate,
                         activation="sigmoid", kernel_initializer='he_normal', padding="same")(input)
    block = Multiply()([conv_filter, gate_filter])
    return block
