### ISSUE TITLE
develop分支下的sentiment预测时，提示语法错误。

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#753]
develop分支下的sentiment预测时，提示语法错误。

I1207 02:52:29.259552 24680 TrainerInternal.cpp:165]  Batch=190 samples=24320 AvgCost=0.000106342 CurrentCost=8.35871e-05 Eval: classification_error_evaluator=0  CurrentEval: classification_error_evaluator=0 
I1207 02:52:32.427665 24680 TrainerInternal.cpp:181]  Pass=9 Batch=196 samples=25000 AvgCost=0.000113647 Eval: classification_error_evaluator=0 
I1207 02:53:19.009176 24680 Tester.cpp:109]  Test samples=25000 cost=nan Eval: classification_error_evaluator=0.17408 
I1207 02:53:19.027931 24680 GradientMachine.cpp:113] Saving parameters to ./model_output/pass-00009
I1207 02:53:19.150913 24680 Util.cpp:233] copy trainer_config.py to ./model_output/pass-00009
I1207 02:53:22.093690 26643 Util.cpp:158] commandline:  --use_gpu=0 
I1207 02:53:22.093875 26643 Util.cpp:132] Calling runInitFunctions
I1207 02:53:22.094306 26643 Util.cpp:146] Call runInitFunctions done.
  File "<string>", line 13
    paddle version: 
                 ^
SyntaxError: invalid syntax
[INFO 2016-12-07 02:53:22,212 networks.py:1466] The input order is [word]
[INFO 2016-12-07 02:53:22,212 networks.py:1472] The output order is [__fc_layer_3__]
I1207 02:53:22.350169 26643 GradientMachine.cpp:124] Loading parameters from model_output/pass-00002/

**Comment by qingqing01** [comment]
@beckett1124  我没有复现这个问题，本地测试都正常。

> File "", line 13
> paddle version:
> ^
> SyntaxError: invalid syntax

很奇怪怎么会有  `paddle version: ` ？

**Comment by nosqldev** [comment]
In [1]: from py_paddle import swig_paddle

In [2]: swig_paddle.initPaddle("--use_gpu=false")
I0209 16:16:13.293015  7006 Util.cpp:155] commandline:  --use_gpu=false
I0209 16:16:13.293550  7006 Util.cpp:130] Calling runInitFunctions
I0209 16:16:13.294040  7006 Util.cpp:143] Call runInitFunctions done.
  File "<string>", line 13
    paddle version:
                 ^
SyntaxError: invalid syntax

----------------------------------------------

环境：
cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=14.04
DISTRIB_CODENAME=trusty
DISTRIB_DESCRIPTION="Ubuntu 14.04.3 LTS"

使用 deb 安装

**Comment by Yancey1989** [comment]
我先close这个issue了，如果最新代码依然有问题再reopen。
