### ISSUE TITLE
单机训练模型阶段发现auc打印都是0

### ISSUE THREAD

**Issue by zhayefei** [PaddlePaddle/Paddle#7532]
输入的特征是稠密向量（9维）+ 1.8W维度的one-hot 向量，预测的标签是0，1，如下：
[  6.40000000e+01   1.00000000e+00  -6.02653000e-02   2.66371000e-01
   1.20000000e-01   4.00000000e+00   2.35000000e-01   1.23000000e-01
   1.20000000e+01] [0 0 0 ..., 0 0 0] ['0']

最后训练阶段：其中auc均为0
Pass 0, Batch 0, Cost 0.070000, {'__auc_evaluator_0__': 0.0, 'classification_error': 0.07000000029802322}
Pass 0, Batch 50, Cost 0.080000, {'__auc_evaluator_0__': 0.0, 'classification_error': 0.07999999821186066}
Pass 0, Batch 100, Cost 0.040000, {'__auc_evaluator_0__': 0.0, 'classification_error': 0.03999999910593033}
.....

**Comment by wanghaox** [comment]
请补充下相关的网络部分代码

**Comment by zhayefei** [comment]
补充下：1）训练数据已经过shuffle； 2）样本相对较均衡。

**Comment by zhayefei** [comment]
dense_x = paddle.layer.data(name='dense_x', type=paddle.data_type.dense_vector(dense_input_dim))
    sparse_x = paddle.layer.data(name='sparse_x', type=paddle.data_type.sparse_binary_vector(sparse_input_dim))

    label_y = paddle.layer.data(name='label_y', type=paddle.data_type.dense_vector(1))
    output = lr_model([dense_x, sparse_x])
    print "lr_model is ok"
    cost = paddle.layer.square_error_cost(input=output, label=label_y)

    print "cost is ok"
    parameters = paddle.parameters.create(cost)
    optimizer = paddle.optimizer.Momentum(momentum=0)

    print "opt is ok"
    paddle.evaluator.classification_error(name="classification_error", input=output, label=label_y)
    paddle.evaluator.auc(input=output, label=label_y)

    trainer = paddle.trainer.SGD(
            cost=cost,
            parameters=parameters,
            update_equation=optimizer)

    print "trainer is ok"
    feeding = {'dense_x': 0, 'sparse_x': 1, 'label_y': 2}

    test_reader = paddle.batch(
        paddle.reader.shuffle(
            cluster_data_reader(cluster_test_dir), buf_size = 300),
        batch_size=100)

    train_reader = paddle.batch(
        paddle.reader.shuffle(
            cluster_data_reader(cluster_train_dir), buf_size=300),
        batch_size=100)
    print eval,"eval"

**Comment by zhayefei** [comment]
def lr_model(input_x):
    output = paddle.layer.fc(
            input=input_x,
            size=1,
            act=paddle.activation.Sigmoid())
        #   param_attr=paddle.attr.Param(initial_std=0.01, name="output"))
    return output

**Comment by wanghaox** [comment]
参考https://github.com/PaddlePaddle/Paddle/issues/2921
label_y请使用intege_value类型
