### ISSUE TITLE
本地编译报这种错nvcc fatal   : Unsupported gpu architecture 'compute_50'

### ISSUE THREAD

**Issue by keain** [PaddlePaddle/Paddle#754]

**Comment by hedaoyuan** [comment]
估计是你本地CUDA的版本比较低，还不支持compute_50这种架构。
`nvcc --version`可以看一下nvcc的版本，编译paddle需要nvcc 7.0以上。

**Comment by keain** [comment]
CMAKE的编译选项加入自己安装的高版本的cuda可以解决这个问题
-DCUDA_TOOLKIT_INCLUDE=/home/work/cuda-7.5/include -DCUDA_TOOLKIT_ROOT_DIR=/home/work/cuda-7.5
