### ISSUE TITLE
better directory structure

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7542]
1. We need a `/examples` directory or `python/examples`.
1. Move `/adversarial` into `/examples/fluid/advbox`.
1. Move `/v1_api_demo` into `/examples/v1`

**Comment by luotao1** [comment]
@wangkuiyi @lcy-seso How about move `/adversarial` into `models` repo?

**Comment by lcy-seso** [comment]
I agree models repo need examples of Fluid so that users can learn by examples, and the examples are in one place so that users can easily find them.

**Comment by JiayiFeng** [comment]
In my opinion, `advbox` is a tool instead of a model. It doesn't train and produce a model. It takes a completed model and generates some modified images via the model.

**Comment by luotao1** [comment]
> It takes a completed model and generates some modified images via the model

So it works like inference?

**Comment by JiayiFeng** [comment]
@luotao1 
Indeed. However, during normal inference, we just get the value of the predicted label, while in the `advbox` we get the gradient of the input image and then modify the image itself until the model cannot infer it correctly.

**Comment by luotao1** [comment]
`models repo` doesn't contain model only. For example, in https://github.com/PaddlePaddle/models#9-image-classification, following two chapters are all tools like `advbox`. 
- 9.1 convert Caffe model file to PaddlePaddle model file
- 9.2 convert TensorFlow model file to PaddlePaddle model file

Thus, `advbox` can move to `models repo` as well.

**Comment by wangkuiyi** [comment]
Let us create a directory `fluid` in the models repo, and move advbox into `models:/fluid/advbox`.

**Comment by gx-wind** [comment]
OK. It's a good and reasonable proposal.I will move later.
Thank you all.

**Comment by luotao1** [comment]
@gx-wind You can move into https://github.com/PaddlePaddle/models/tree/develop/fluid.
