### ISSUE TITLE
TypeError: reduce() of empty sequence with no initial value

### ISSUE THREAD

**Issue by JessieMeng** [PaddlePaddle/Paddle#7545]
while(i<video_feature.shape[0]):
                    yield [video_feature[i][:-1]]+[int(video_feature[i][2048])]
                   #print [video_feature[i][:-1]]+[int(video_feature[i][2048])]
                   i+=1

data = paddle.layer.data("word",paddle.data_type.dense_vector_sequence(input_dim))
 lbl = paddle.layer.data("label", paddle.data_type.integer_value(2))

**Comment by will-am** [comment]
I am not sure what the problem is. Could  you provide more information?
