### ISSUE TITLE
Examples of model in parallel

### ISSUE THREAD

**Issue by zzqiang04053080** [PaddlePaddle/Paddle#755]
well,  I am a novice for paddle,  and I have learned that  paddle  supports model parallelism  on single machine. But I didn't find the demo or some useful information.  This issue is superficial, anyone can give guidance?

**Comment by luotao1** [comment]
Parall_nn Introduction: http://www.paddlepaddle.org/doc/ui/cmd_argument/use_case.html#parallel-nn 
And an unitest: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/tests/sample_trainer_config_parallel.conf

**Comment by zzqiang04053080** [comment]
@luotao1   Thank you for your quick reply!
