### ISSUE TITLE
提个问题. 深度学习能学会书本上的知识么？

### ISSUE THREAD

**Issue by yuer01** [PaddlePaddle/Paddle#7552]
提个问题. 深度学习能学会书本上的知识么？
比如能看懂历史课上的故事么？
如果可以，把图书馆的所有书本知识都输入。不知道会有什么效果。
我们十年寒窗苦的努力，会不会在人工智能的面前变的轻而易举。

**Comment by will-am** [comment]
哈哈，这个是强的通用人工智能了，应该是人工智能的终极目标了吧

**Comment by yuer01** [comment]
如果局限于医学领域，是不是会加快攻克某些疾病。 
普通人学医学要多年的学习，然后是医院的实践。这个过程能不能加快医学研究的过程。
或者说哪些传统很慢的事情，可以通过机器学习快速掌握，我们来掌握机器。

**Comment by will-am** [comment]
这个想法不错~
