### ISSUE TITLE
Failed to install Java as bazel's dependency

### ISSUE THREAD

**Issue by lipeng-unisound** [PaddlePaddle/Paddle#756]
我在尝试在 Paddle 的 Dockerfile 里增加 bazel。按照 bazel 的[安装文档](https://www.bazel.io/versions/master/docs/install.html#ubuntu) ，要先安装 Java。我在一台 Ubuntu 14.04 的虚拟机里照着文档做了一遍，在安装 Java 时，会弹出一个 dialog，同意协议、选择配置等等。而当我在 Dockerfile 里加入这些安装步骤后再运行 docker build 时，由于没有 TERM，无法弹出 dialog，导致 Java 不能被安装。错误信息如下：

![image](https://cloud.githubusercontent.com/assets/17057205/20957571/982f8ffa-bc8b-11e6-8dfd-3e80c89f33f8.png)

  我的问题是： 
1. Java 是否 bazel 的 prerequisite?
1. 有没有办法在 Dockerfile 里指定 TERM？
1. 我想到可以将 FROM ubuntu:14.04 改为 FROM  openjdk:8，但是我发现 openjdk 是 基于 debian 而非 ubuntu:14.04 的。

**Comment by gangliao** [comment]
Can you paste your dockerfile in here?

**Comment by gangliao** [comment]
```dockerfile
RUN \
  echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
  add-apt-repository -y ppa:webupd8team/java && \
  apt-get update && \
  apt-get install -y oracle-java8-installer && \
  rm -rf /var/lib/apt/lists/* && \
  rm -rf /var/cache/oracle-jdk8-installer
ENV JAVA_HOME /usr/lib/jvm/java-8-oracle
RUN cd / && git clone https://github.com/google/bazel.git
RUN cd /bazel && ./compile.sh
ENV PATH "$PATH:/bazel/output"
```

**Comment by lipeng-unisound** [comment]
Thanks!
``` echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections``` solves this problem.
