### ISSUE TITLE
AttributeError: 'Parameters' object has no attribute 'init_from_tar'

### ISSUE THREAD

**Issue by dockiHan** [PaddlePaddle/Paddle#7564]
paddlepaddle v0.10.0
想使用增量学习的方法训练网络，得到RT的错误。
```
in lstm_train(self, train_set_num, train_x, train_y, save_path, init_model, increment, log_every_n, train_pass_num, pass_cost)
    189         if increment and os.path.isfile(self.__init_model):
    190             with open(self.__init_model, "r") as file:
--> 191                 self.__parameters.init_from_tar(file)
    192         feeding = {"lstm_X": 0, "label_Y": 1}
    193         self.__trainer.train(reader=paddle.minibatch.batch(paddle.reader.shuffle(

AttributeError: 'Parameters' object has no attribute 'init_from_tar'
```

**Comment by will-am** [comment]
可以使用`self.__parameters.from_tar(file)`

**Comment by dockiHan** [comment]
@will-am  你好，今天又试了下发现from_tar加载现有模型参数后训练的cost与先前第一轮训练的cost差不多大小，感觉并没有起到增量学习的效果。 我的优化算法使用的Adam

**Comment by will-am** [comment]
应该要再多训练几轮吧，或者是learning rate设置的大了

**Comment by dockiHan** [comment]
@will-am 额~~增量学习的话不应该是在现有模型的基础上做进一步的训练吗？对于同类型的训练数据，cost的规模应该与之前最后一轮的训练结果相近而不应该与第一轮训练结果相近呀。。第一轮与最后一轮的cost差了100倍呢

**Comment by will-am** [comment]
那是有问题，检查下新增的数据吧，可能分布与之前差异较大

**Comment by will-am** [comment]
可以试试先不用新的数据，加载上次的参数后，还用原来的数据再训练一轮，看cost变化，如果正常，那应该就是新的数据分布变化比较大了

**Comment by dockiHan** [comment]
@will-am 嗯，谢谢， 我问了一下paddle群里的其他人，说是优化算法的问题， 使用Adam等动态学习率的优化算法在恢复模型的时候是有损的，无法恢复Adam优化的最新学习率。所以从cost看起来训练好像是从新开始的，而不是做的增量学习。
