### ISSUE TITLE
Make elementwise_op supporting scalar input `Y`

### ISSUE THREAD

**Issue by JiayiFeng** [PaddlePaddle/Paddle#7568]
Our binary `elemetwise_op` takes two inputs: `X` and `Y`. The dimension of `X` should be greater than the one of `Y`. Currently the `Y`'s dimension must be a exactly slice of `X`'s. It doesn't work when `Y` is a scalar:

```
X shape: [2, 3 , 4, 5]  Y shape: [4, 5] ====> OK
X shape: [2, 3 , 4, 5]  Y shape: [5] ====> OK
X shape: [2, 3 , 4, 5]  Y shape: [1] ====> Error
```

However, the calculation between a tensor and a scalar is quite a basic math operation. We shall support it.

**Comment by pkuyym** [comment]
It seems this issue https://github.com/PaddlePaddle/Paddle/issues/6757 is related to current issue.

**Comment by gongweibao** [comment]
There is  [scaleop](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/scale_op.h) yet.

**Comment by JiayiFeng** [comment]
@gongweibao 
1. The `scale` of `scale_op` is an attribute, not a variable, which means it can not be the output of some other `op`.

2. `scale_op` can only handle `mul` operation. `Add`. `sub`, `div` and even `max` between a tensor and a scalar is also needed.
