### ISSUE TITLE
Rename WITH_C_API into PADDLE_BUILD_INFERENCE_LIB

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#7578]
The term *C_API* has been pretty confusing.  By reading our source code, I think it means the C-API for inference only, but not those for training.  Let us use an accurate name for it.

**Comment by luotao1** [comment]
As `WITH_C_API` is used for a long time in old PaddlePaddle, users are familiar with it, we may remain it. And for fluid, we will add `WITH_FLUID` option for both training and inference.
