### ISSUE TITLE
`use_cudnn` should expose to python interface.

### ISSUE THREAD

**Issue by chengduoZH** [PaddlePaddle/Paddle#7582]
Currently, `conv_op`, `conv_transpose_op` and `pool_op` take `use_cudnn` as an attribute, and the default value is false.
https://github.com/PaddlePaddle/Paddle/blob/38c61053ff7b7d87b31a08548a846bc05c3bae3b/paddle/operators/conv_op.cc#L221-L224
But the python interface of those `op` do not have an option to chose using `cudnn` or not.
https://github.com/PaddlePaddle/Paddle/blob/38c61053ff7b7d87b31a08548a846bc05c3bae3b/python/paddle/v2/fluid/layers/nn.py#L669-L677

**Comment by jacquesqiao** [comment]
we still need a priority mechanism to resolve such kind of problem in the future.

**Comment by chengduoZH** [comment]
related issue https://github.com/PaddlePaddle/Paddle/issues/7589
