### ISSUE TITLE
Optimize distributed training performance

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7607]

**Comment by wangkuiyi** [comment]
It is difficult to understand the title of this issue.

**Comment by typhoonzero** [comment]
Sorry, the original issue is trying to leave a TODO in the project. I'm writing a transpiler which can split one variable and send to multiple parameter servers to do the partial, elementwise optimization, but the current implementation of `split_op` have to copy the splited data to newly allocated memory, which can be optimized.

Then we noticed that all the allocation is managed by "buddy allocator" under `paddle/memory`, if we use several pointers pointing to sections of the original tensor, and then use these pointers in new tensor objects will probably cause memory errors.

I changed this issue to be more general, and we can do some other performance enhancements for now.
