### ISSUE TITLE
How about implement another Run() in framework::Executor

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#7610]
Suggested by @qingqing01 , we may implement another `Run()` in [paddle/framework/executor.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/executor.h) which do the same things as the `Run()` of Python `Executor`.

https://github.com/PaddlePaddle/Paddle/blob/144854d2e86efce8858b34518c1ee5f4b48d9407/python/paddle/v2/fluid/executor.py#L125-L132

The interface maybe like and will do following things:
```cpp
void Run(const ProgramDesc& program,
         Scope* scope,
         std::map<std::string, Tensor>& feeds,
         std::map<std::string, Tensor>& fetchs,
         std::string& feed_var_name="feed",
         std::string& fetch_var_name="fetch") {
  1. clone the program
  2. prepend feed_op
  3. set feed variables
  4. append fetch_op
  5. call Run(const ProgramDesc&, Scope*, int, bool create_local_scope = true, bool create_vars = true)
  6. get fetch variables 
}
```

So that we can directly `Run` both in Python API and C++ API.

**Comment by sidgoyal78** [comment]
@Xreki: This idea seems like a reasonable approach to avoid the Resolver class. So I think I would prefer this approach.

(Another comment, just comparing against the Resolver class design: I think steps 1 - 4  which are extra in this design should be relatively cheap in terms of computation. So calling run again and again, in case of inference in a streaming fashion, should be also fine. )

**Comment by Xreki** [comment]
Do you have some detail about running steps 1-4 a streaming fashion?

**Comment by sidgoyal78** [comment]
I just was saying that if we call the `Run()` function again and again:
- in the previous design with ProgramResolver and the current design, the only repetitive part that i see is steps 1 to 4 in the above function. 
So I think this should be fine since these steps are not costly..

**Comment by Xreki** [comment]
OKay. It seems an optimization method. I add it to the TODO list in inference framework project to remark it.
