### ISSUE TITLE
roi_pool 如何 infer 时 输入2个input

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#7614]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/tests/configs/test_roi_pool_layer.py
像这个网络，如何 infer 的时候输入2input（data和rois）？

**Comment by guoshengCS** [comment]
data_layer需要像这样：

``` python
   img = paddle.layer.data(name="image", type=paddle.data_type.dense_array(3 * 224 * 224))
   roi = paddle.layer.data(name="roi", type=paddle.data_type.dense_vector_sequence(5))
```

infer的话feed的数据类似这样：
```python
def data_provider(file_name='data/data_1.bin'):
    with open(file_name, 'rb') as f:
        img_rois = []
        img_num = img_num = struct.unpack('i', f.read(4))[0] / 2
        for i in range(img_num):
            for j in range(roi_num):
                batch_idx = struct.unpack('I', f.read(4))[0]
                left = struct.unpack('f', f.read(4))[0]
                top = struct.unpack('f', f.read(4))[0]
                width = struct.unpack('f', f.read(4))[0]
                height = struct.unpack('f', f.read(4))[0]
                x_start = left
                y_start = top
                x_end = left + width
                y_end = top + height
                rois.append([batch_idx, x_start, y_start, x_end, y_end])
            input_rois.append((fmt_img, rois))
    return img_rois
```

**Comment by liuhuiCNN** [comment]
@guoshengCS 解决了， 非常感谢！

**Comment by guoshengCS** [comment]
```
roi_pool = roi_pool_layer( input=conv, rois=rois, ...)
```
中conv是一个conv_layer，rois是一个data_layer

**Comment by liuhuiCNN** [comment]
@guoshengCS 
1、 请问这个例子是 paddle v1接口还是 v2 接口还是 fluid接口。
2、import paddle
    input_roi_pooling = paddle.trainer_config_helpers.data_layer(name='data', size=3*14*14,  height=14, width=14)
    input_rois = paddle.trainer_config_helpers.data_layer(name='rois', size=20)

   ROI_pool = paddle.layer.roi_pool(name="ROI_pool", input=input_roi_pooling, rois=input_rois, pooled_width=7, pooled_height=7, \
                               spatial_scale=1.0/16, num_channels=3)
    parameters = paddlev2.parameters.create(ROI_pool)

这样一个网络，如何feed一个numpy进行infer？

**Comment by guoshengCS** [comment]
那这里就先close这个issue了，如果后续还有疑问的话可以reopen
