### ISSUE TITLE
should this line return a string?

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#7627]
I just found following line is blocking my build, since it's supposed to return a string.
```cpp
virtual std::string GetReqName() { assert(false); }
```
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/detail/grpc_server.cc#L39

**Comment by helinwang** [comment]
Yes, thanks! This PR fixes it: https://github.com/PaddlePaddle/Paddle/pull/7626

I think we should turn on distributed flag on TeamCity, is there any concern (such as longer build speed) for turning it on?

**Comment by putcn** [comment]
I don't see why we shouldn't.

**Comment by Yancey1989** [comment]
Yes, it tasks longer time with `DWITH_DISTRIBUTE=ON`, I add a scheduled job on CI https://paddleci.ngrok.io/viewType.html?buildTypeId=Paddle_DistributedUnitTestNightly , maybe we can concern this job.

**Comment by putcn** [comment]
I see this job is triggered by schedule, should we make it triggered by change so that build can be verified before it's merged to main branch?
I think it would be more reasonable to add `DWITH_DISTRIBUTE=ON` to PR_CI, since that's kinda gateway for repo code quality.

**Comment by typhoonzero** [comment]
This https://github.com/PaddlePaddle/Paddle/pull/7605 also fix this.

**Comment by typhoonzero** [comment]
@putcn @Yancey1989 I think we can turn it on once we have the CI machines upgraded to have more computing power.
