### ISSUE TITLE
fail to run trainer in mpi with multi node, but success with num_nodes=1

### ISSUE THREAD

**Issue by lcstore** [PaddlePaddle/Paddle#7638]
1.env:
paddle.v2

2.cause  error log:
1).train.log
Thu Jan 18 03:05:54 2018[1,2]<stderr>:*** Aborted at 1516215954 (unix time) try "date -d @1516215954" if you are using GNU date ***
Thu Jan 18 03:05:54 2018[1,2]<stderr>:PC: @                0x0 (unknown)
Thu Jan 18 03:05:54 2018[1,2]<stderr>:*** SIGSEGV (@0x8) received by PID 36257 (TID 0x7fc1776dd700) from PID 8; stack trace: ***
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc3b570f160 (unknown)
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc354755162 paddle::ProtoClient::recv()
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc3564786e4 paddle::ParameterClient2::sendParallel()
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc35485d57c _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc3a74628a0 execute_native_thread_routine
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc3b57071c3 start_thread
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @     0x7fc3b4d2f12d __clone
Thu Jan 18 03:05:54 2018[1,2]<stderr>:    @                0x0 (unknown)

2).server.log
Thu Jan 18 03:05:54 2018[1,9]<stderr>:F0118 03:05:54.103477 21025 ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=0 block id=71
Thu Jan 18 03:05:54 2018[1,2]<stderr>:F0118 03:05:54.109586 38765 ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=0 block id=78
Thu Jan 18 03:05:54 2018[1,3]<stderr>:F0118 03:05:54.122237  2490 ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=0 block id=77
3).paddle_pserver2.FATAL
ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=0 block id=80

在mpi上运行，num_nodes=1时正常运行，num_nodes>1时，总数报上面的异常

**Comment by JiayiFeng** [comment]
排查得到原因是端口冲突，更换端口或者使用独占模式运行。

**Comment by lcstore** [comment]
更换不同的端口，总是碰上端口冲突。可否加个功能解决这类问题，人工改端口要试很多次还不一定能成功，效率比较低

**Comment by lcstore** [comment]
报端口冲突（ERROR on binding 10.86.90.26: Address already in use），但让OP查看pserver和trainer的端口，却没有被占用。（同一配置和代码，之前有跑通过50个节点的）

**Comment by Yancey1989** [comment]
可以参考这个comment：https://github.com/PaddlePaddle/Paddle/issues/9426#issuecomment-376760175。 我先关闭这个issue了，如依然有问题请重新再打开它。
