### ISSUE TITLE
from datapoint import DataPoint, Evidence, EecommFeatures  这个datapoint 我通过pip安装了，但是就是没有DataPoint, Evidence, EecommFeatures

### ISSUE THREAD

**Issue by 466821202** [PaddlePaddle/Paddle#7647]
from datapoint import DataPoint, Evidence, EecommFeatures  这个datapoint 我通过pip安装了，但是就是没有DataPoint, Evidence, EecommFeatures

**Comment by JiayiFeng** [comment]
这个datapoint不是pip上的datapoint，而是我们自己开发的一个模块，会在下载数据的同时下载。请严格按照https://github.com/PaddlePaddle/models/tree/develop/neural_qa下README.md所写的内容，先执行
```bash
cd data && ./download.sh && cd ..
```
在进行训练：
```bash
PYTHONPATH=data/evaluation:$PYTHONPATH python train.py 2>&1 | tee train.log
```
