### ISSUE TITLE
请问PaddlePaddle Fluid是否有更详细更多的demo可供学习，是否能实现以下网络？

### ISSUE THREAD

**Issue by 20092136** [PaddlePaddle/Paddle#7651]
希望用Paddle来实现一个model，称为MatchPyramid，paper在这：[Text Matching as Image Recognition](https://arxiv.org/pdf/1602.06359.pdf)

![image](https://user-images.githubusercontent.com/1858392/35086143-68a2ec48-fc66-11e7-9193-82a41a951e8d.png)

这个model用于提取文本matching特征（或者说对match度打分），简单描述如下：
1. 输入query、doc两段文本；
2. 分别过embedding，得到emb_q，emb_d；
3. 将2个emb矩阵相乘得到matching matrix；
4. 将matching matrix看作一张图片，做conv和pooling；
5. +若干全连接到输出；

已经对Paddle进行过的调研和理解（都是基于非fluid版本的paddle v2）：
1. 上述第三步中的矩阵相乘，Paddle没有相应的layer可以实现；
2. 第四步中，可以预期matching matrix的size在每一对样本下都不一样，我们希望pooling的输出feature-map的size是固定的，于是希望Pooling kernel的size是动态计算的，Paddle目前没有支持动态的Pooling操作；

于是想尝试Fluid，但关于fluid的例子比较少，没有配合例子的相关注释说明，已经看过的资料有：
1. Design Doc: PaddlePaddle Fluid；
2. 官网上的Fluid的接口文档；
3. 代码中那个Gan的demo；

还是未能搞懂Fluid的使用方式，于是请问：
1.  Fluid是不是能实现上述网络？
2. 是否还有其他fluid的资料或例子推荐？

**Comment by JiayiFeng** [comment]
你好，感谢关注Paddle Fluid。
我没有非常理解你所说第3步的操作。要取出的东西，是整张词表，还是只是句子中出现过的词的词向量的集合？
如果是整张词表，那么大小应该是固定的，应该不会出现第四步中size变化的情况；如果是出现过的词的词向量，那么其实就是句子经过embedding层的输出，在目前的paddle中也可以拿到。

**Comment by 20092136** [comment]
![image](https://user-images.githubusercontent.com/1858392/35086903-39dccdae-fc69-11e7-9627-30b2ce331b2d.png)


我想这个图能更好的表达我的需求，我希望对2个文本的embedding层的输出做点乘，也就是假设2个文本分别有3和4个term，我希望得到一个3x4的矩阵（图中这个例子是10x10）；

**Comment by JiayiFeng** [comment]
那么其实就是两个embedding层的输出之间的点积。这应该是可以实现的。
但是即使在Fluid中，依然不支持变大小的kernel，所以第4步可能不大好实现。

在 https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/v2/fluid/tests/book 里可以看到用Fluid实现的Paddle Book中的各个例子，可以作为学习的demo。

**Comment by 20092136** [comment]
好的，感谢关于Fluid的解答！！

另外关于

> 那么其实就是两个embedding层的输出之间的点积。这应该是可以实现的。

能否举个例子呢？是用哪个layer呢，我看过dotmul_projection、dotmul_operator、dot_prod_layer、linear_comb_layer似乎都不是这个操作？

**Comment by JiayiFeng** [comment]
我的理解，这其实就是一个矩阵转置然后再点积的操作。
矩阵转置可以用 trans layer，http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#trans
点积直接写c = a * b即可

**Comment by 20092136** [comment]
@JiayiFeng 
直接 * 是调用layer_math.py里重载的__mul__吧，但我看mul()这个方法似乎要求其中一个乘数是浮点数，或者size=1？

**Comment by JiayiFeng** [comment]
看了一圈发现好像还真没有可以直接实现两个矩阵简单相乘的layer，不过可以用Fluid，Fluid可以很容易地实现这个。

**Comment by 20092136** [comment]
好的，明白了，多谢解答~
