### ISSUE TITLE
CAPI GPU预测时出现异常

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#7664]
同样的模型CPU下正常，GPU下出现异常：
I0118 22:17:51.851774 60632 mlp_base.cpp:229] paddle_init --use_gpu=True --gpu_id=0
I0118 22:17:51.852061 60632 Util.cpp:166] commandline:  --use_gpu=True --gpu_id=0
...
F0118 22:17:53.868855 60632 BaseMatrix.cu:92] Check failed: useGpu_ == b.useGpu_ Matrix type mismatch
*** Check failure stack trace: ***
    @     0x7fa72b4131bd  google::LogMessage::Fail()
    @     0x7fa72b416d05  google::LogMessage::SendToLog()
    @     0x7fa72b412ce3  google::LogMessage::Flush()
    @     0x7fa72b41821e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fa72b6cc40c  paddle::BaseMatrixT<>::applyBinary<>()
    @     0x7fa72b6cc591  paddle::BaseMatrixT<>::applyBinary<>()
    @     0x7fa72b6cc619  paddle::BaseMatrixT<>::assign()
    @     0x7fa72b48820a  paddle::BatchNormalizationLayer::expandMat()
    @     0x7fa72b48929d  paddle::BatchNormalizationLayer::forward()
    @     0x7fa72b5a81dd  paddle::NeuralNetwork::forward()
    @     0x7fa72b40e816  paddle_gradient_machine_forward

**Comment by JiayiFeng** [comment]
先升级一下paddle版本重新尝试，如果还是有问题，可以在这里贴一下batchnorm层相关的配置
