### ISSUE TITLE
return 404 when click  hyperlink in "quickstart" docment

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#767]
return 404 when click hyperlink in "quickstart" docment------“ Layer documentation”
 
http://www.paddlepaddle.org/doc/demo/quick_start/index_en.html ，
Later, you will also get chance to build other more powerful network architectures. For more detailed documentation, you could refer to: Layer documentation。

**Comment by backyes** [comment]
@reyoung @wangkuiyi 

外网layer文档页面404了，麻烦确认下为啥没有了。

**Comment by reyoung** [comment]
@qingqing01 `Quick Start` documentation contains a dead link. Please fix this bug in the master branch. And merge the fix in both develop and master.
