### ISSUE TITLE
Check SSE/AVX/AVX2 at runtime  to decline in number of release binaries

### ISSUE THREAD

**Issue by gangliao** [PaddlePaddle/Paddle#768]
Currently, we have four release binaries, `no-avx CPU, avx-CPU, no-avx-GPU, avx-GPU.`, which looks quite miscellaneous. Actually, we can check CPU capabilities at runtime via

1. query `cpuid`
```c
#ifdef _WIN32
/// MSVC CPUID
#define cpuid(info, x)    __cpuidex(info, x, 0)
#else
//  GCC Intrinsics
#include <cpuid.h>
/// gcc / clang CPUID
#define cpuid(info, x) __cpuid_count(x, 0, info[0], info[1], info[2], info[3])
#endif
```
2.  Then, do some bit manipulation to check whether AVX is supported or not.

**That can help us decline in number of release binaries from four to two.**

- [x] Add SIMD flags source code in `paddle/utils` #800 
- [ ] change macro `#if` in current PaddlePaddle to support AVX and SSE at runtime

**Comment by gangliao** [comment]
Reference

SIMD Extensions http://paginapessoal.utfpr.edu.br/gortan/aoc/transparencias/t09_mmx-simd/literatura/Wiki_SIMD_Extensions.pdf

**Comment by reyoung** [comment]
@gangliao To query CPUID will detect whether CPU supports AVX instincts or not during runtime. But Paddle code needs to be refactored to switch calculation between AVX and SSE. 

The code in `SIMDFunction.h` and `CUDA` package only export one symbol for both AVX and SSE. Has this been done? Is there any plan?

**Comment by hedaoyuan** [comment]
这个可以搞定这个issue后在来做，不只是`SIMDFunction.h`和`CUDA`的问题。
1. `SIMDFunction.h`里面很多不用的函数可以删掉了
2. `hl_cpu_lstm.cuh`这种文件，把avx和非avx代码拆成两个文件分别编译，avx的加`-mavx`，符号名本来就是不同的两个。
3. `BaseMatrix.cu`需要考虑一下怎么同时编译avx和非avx两个版本。

**Comment by reyoung** [comment]
Maybe the first step is add a `cpuid.h/cpp` in util package.

**Comment by gangliao** [comment]
@reyoung  @hedaoyuan  Yeah, `util/simd.h` almost done.
It will detect all CPUID flags related to SIMD for general-purpose utilities (`SSE2, SSE3, SSSE3, AVX, AVX2, AVX512`) to support switch calculation.

**Comment by typhoonzero** [comment]
I think this was already done.

Closing this issue, feel free to reopen it.
