### ISSUE TITLE
run hsigmoid model fail in mpi

### ISSUE THREAD

**Issue by lcstore** [PaddlePaddle/Paddle#7682]
env: paddle
注：单节点可以正常执行，多节点跑总是失败

总是提示端口已被占用，或者提示连接失败.
1.尝试resource=full模式，失败
2.尝试receiver提交任务，失败
3.使用旧版paddle，失败

1和2，拒绝连接的日志：
Thu Jan 18 17:21:31 2018[1,6]<stderr>:F0118 17:21:31.361541 62092 LightNetwork.cpp:399] connection refused by pserver, maybe pserver failed!
Thu Jan 18 17:21:31 2018[1,6]<stderr>:*** Check failure stack trace: ***
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
F0118 17:21:43.570335 31721 LightNetwork.cpp:399] connection refused by pserver, maybe pserver failed!

3.1.使用旧版paddle，server.log日志
Fri Jan 19 12:00:36 2018[1,3]<stderr>:+ ./paddle_pserver2 --num_gradient_servers=5 --nics=xgbe0 --port=12864 --ports_num=1 --ports_num_for_sparse=1 --rdma_tcp=tcp --comment=paddle_cluster_job
Fri Jan 19 12:02:47 2018[1,3]<stderr>:F0119 12:02:47.159351  5046 ParameterServer2.cpp:751] Check failed: offset >= 0 (-1 vs. 0) Only existing parameter block is allowed:  id=3 block id=391
Fri Jan 19 12:02:47 2018[1,3]<stderr>:*** Check failure stack trace: ***
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x8d19fd  google::LogMessage::Fail()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x8d54ac  google::LogMessage::SendToLog()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x8d1523  google::LogMessage::Flush()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x8d69be  google::LogMessageFatal::~LogMessageFatal()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x70d6b7  paddle::ParameterServer2::sendBackParameter()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x70d857  paddle::ParameterServer2::getParameter()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x7137bc  paddle::ParameterServer2::sendParameter()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x71bf8e  std::_Function_handler<>::_M_invoke()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x71d89c  std::function<>::operator()()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @           0x7228af

3.2.使用旧版paddle，train.log日志
Fri Jan 19 12:02:34 2018[1,0]<stdout>:end to build dict:399549,time:81.744120121
Fri Jan 19 12:02:47 2018[1,3]<stderr>:*** Aborted at 1516334567 (unix time) try "date -d @1516334567" if you are using GNU date ***
Fri Jan 19 12:02:47 2018[1,3]<stderr>:PC: @                0x0 (unknown)
Fri Jan 19 12:02:47 2018[1,3]<stderr>:*** SIGSEGV (@0x8) received by PID 65327 (TID 0x7fe05f6fd700) from PID 8; stack trace: ***
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe0aa354160 (unknown)
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe04c9e8012 paddle::ProtoClient::recv()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe04d67317a paddle::ParameterClient2::sendParallel()
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe04caef0ec _ZNSt6thread5_ImplISt12_Bind_simpleIFZN6paddle14SyncThreadPool5startEvEUliE_mEEE6_M_runEv
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe04bb458a0 execute_native_thread_routine
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe0aa34c1c3 start_thread
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @     0x7fe0a997412d __clone
Fri Jan 19 12:02:47 2018[1,3]<stderr>:    @                0x0 (unknown)
Fri Jan 19 12:02:47 2018[1,3]<stderr>:./train.sh: line 239: 65327 Segmentation fault      python27-gcc482/bin/python 

另外：同样的配置，执行word2vec的ngram模型(最后一层是Softmax)是能正常执行的

**Comment by Yancey1989** [comment]
还请根据 http://paddlepaddle.org/docs/develop/documentation/zh/faq/cluster/index_cn.html， 找到第一个报错位置的日志。

**Comment by lcstore** [comment]
上面贴的就是第一个报错位置的日志。其他情况的异常信息已经hi跟yanxu05反馈过。麻烦你跟他一起看看这个问题

**Comment by Yancey1989** [comment]
Hi, @lcstore ， PServer日志(server.log)第一次报错的位置应该不是这个吧，麻烦更新下issue，尽量贴全一些，这样也方便后续的排查。

**Comment by lcstore** [comment]
@Yancey1989 已在原问题更新详细的日志，麻烦跟进，谢谢

**Comment by QiJune** [comment]
一般连接失败可能是端口server的端口被占用了。可以检查server.log中的日志确认下
