### ISSUE TITLE
Hard to Understand to_lodtensor function in Fluid/tests/Book/*.py

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Paddle#7684]
When I look into the details of python scripts in python/paddle/v2/fluid/tests/book, it seems that to_lodtensor function has to be defined beforehand, although there is no explicit function call in the python scripts. This may cause users hard to figure out how to define the to_lodtensor function. A possible way is to read the fluid API in details, but it is not friendly to new users or new developers. Could someone add a more detailed example to explain the basic rules in writing the to_lodtensor function? 

```python
def to_lodtensor(data, place):
    seq_lens = [len(seq) for seq in data]
    cur_len = 0
    lod = [cur_len]
    for l in seq_lens:
        cur_len += l
        lod.append(cur_len)
    flattened_data = np.concatenate(data, axis=0).astype("int64")
    flattened_data = flattened_data.reshape([len(flattened_data), 1])
    res = fluid.LoDTensor()
    res.set(flattened_data, place)
    res.set_lod([lod])
    return res
```

**Comment by QiJune** [comment]
You can refer to the design doc of LoDTensor https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.md.
LoD is very useful in sequence data. Fluid handles variant length data in dynamic RNN.

Following is an example:

```
a b c
d e f g
h i
```
We have three sequences, and the input data will be like this:
```
a b c d e f g h i
```
And we must set another lod information to record the length of each sequence. The lod of this example will be 

```
0 3 7 9
```

The equation is:
```
length[i] = LoD[i + 1] - LoD[i]
```

**Comment by guru4elephant** [comment]
I can understand the design of LodTensor. The problem is the to_lodtensor is weird in many examples. Users actually do not need to know this.

**Comment by cheradam** [comment]
@shanyi15 please follow this documentation requirement

**Comment by shanyi15** [comment]
@cheradam @QiJune 
discuss with @Superjomn 
这里不缺文档，而缺一个好的封装隐藏lodtensor,此问题较复杂。在设计之初，没有考虑对用户隐藏lodtensor。而且目前lodtensor开发方面做得不太好，建议加to do到某个projects里。
另，需要API做一套统一的操作/隐藏lodtensor细节的事情，需要讨论后执行。
