### ISSUE TITLE
【问题】请问，如何在建图时获取一个向量（或者说layer）的shape呢？

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7696]
> 更新. 发现paddle的[parameters是有get_shape方法](http://paddlepaddle.org/docs/develop/documentation/zh/api/v2/run_logic.html)的，但似乎是建好图之后——即创建parameters之后。问题更新为创建图的过程中。

其实我的直接问题是如何实现 luong attention ?

背景是，我有一个title的embedding向量，然后有一个 sentence 向量构成的sequence，然后我想用这个title embedding 去attentend到setence embedding sequence, 然后求setence embedding sequence的加权求和，由此得到一个doc的表示。

目前我是这样做的：paddle 的 networks 里已经有 `doc_product_attention`, 我只需要给title embedding 乘上一个 Matrix, 然后作为 `doc_product_attention` 的 `transformed_state`. 
问题出现了，如何乘上一个Matrix呢？我用的paddle.layer.fc, 但是fc的size如何指定？它应该是跟sentence的embedding一样大——我能否自动获取sentence embedding 的维度呢？也就是把 sentence_embedding 的shape，赋值给 fc 的size？ 

因为我的sentence embedding是做了很多操作后concat的结果，没有预设的值。当然也是可以预先算出来的，不过每次改动模型都要手动改一下，感觉不太灵活。所以想问问有没有这样自动获取维度的操作。

不知道对不对，或者清不清楚，贴一下代码...

```Python
    def _create_doc_repr(self, sentence_repr_list, title_repr):
        """

        sentence_repr_list: list of sentence embedding!!
                           
        title_repr: title embedding. 
                    
        """

        ## do Luong attention, see http://aclweb.org/anthology/D15-1166

        # we first make W x title => tansformed_vec
        # then call paddle's dot_product_attention
        # about dot_product_attention, see http://paddlepaddle.org/docs/develop/documentation/\
        # zh/api/v2/config/networks.html#dot-product-attention
        transformed_vec = paddle.layer.fc(
            name="transform_vec",
            input=title_repr,
            size= ????,
            act=paddle.activation.Linear(),
            bias_attr=False
        )

        doc_emb = paddle.networks.dot_product_attention(
            name="local_attention",
            encoded_sequence=sentence_repr_list,
            attended_sequence=sentence_repr_list,
            transformed_state=transformed_vec
        )

        return doc_emb
```

**Comment by QiJune** [comment]
embedding的大小是需要先设置的吧

> 因为我的sentence embedding是做了很多操作后concat的结果，没有预设的值

这里能详细说说吗？是怎么配置的呢

**Comment by memeda** [comment]
就像这样：

```Python
        sentence_local_feature_aggregate = paddle.layer.concat(
            name="{}_concat_all_feature".format(title_or_sentence),
            input=[
                cn_char_unigram_repr, cn_char_bigram_repr,
                basic_word_repr, word_pos_repr,
                ner_token_tag_repr
            ]
        )
```
拼接了很多层，当然是可以先预先算的，只是如果我后面修改一下，那么又得重新算一下，比较麻烦。

当然，我现在也不直接就用拼接后的结果作为句子表示了，而是再过了一个全连接层，这样做attention之前维度也就固定了，这个问题算是规避过去了。

**Comment by QiJune** [comment]
> 拼接了很多层，当然是可以先预先算的，只是如果我后面修改一下，那么又得重新算一下，比较麻烦

这个可以预先算的，用一个变量存下来就好
```
concat_dim = embed_dim1 + embed_dim2 + embed_dim3 
```

然后在后面的fc，填写上concat_dim就行了

**Comment by memeda** [comment]
嗯嗯，的确是哈，不过需要自己维护一下每个层的layer 大小，会稍微不太方便~ 不过没什么哈，只要能用就行  = =
