### ISSUE TITLE
在做图片分类训练是，错误率居然是上升的？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7699]
我在训练10类别的分类训练，下面是训练过程中图片分类错误率，可以看到是错误率是上升的，这是为什么？
![e1](https://user-images.githubusercontent.com/26297768/35160046-05a01dfc-fd77-11e7-9048-52551c0bfd3a.png)
![e2](https://user-images.githubusercontent.com/26297768/35160049-07cb9458-fd77-11e7-9158-7ac9ae8f9626.png)

**Comment by helinwang** [comment]
可能是不巧模型走到了一个不好的点，尝试把learning rate调低？

**Comment by yeyupiaoling** [comment]
@helinwang 你会遇到这种不好的点吗？好的我修改一下。

**Comment by helinwang** [comment]
以前learning rate大的时候会碰见。

**Comment by yeyupiaoling** [comment]
@helinwang 好的，谢谢您。
