### ISSUE TITLE
单机二进制版安装后无法使用py_paddle

### ISSUE THREAD

**Issue by tianwei-bnu** [PaddlePaddle/Paddle#770]
RT。安装单机二进制版本后无法使用py_paddle调用python swig进行预测。

**Comment by backyes** [comment]
@tianwei-bnu 

请问是否直接安装完，立即执行了 ``` import py_paddle ``` ?  如果是，请执行一次paddle train --help，然后在import py_paddle.

如果不是，请提供详细信息。

**Comment by tianwei-bnu** [comment]
@backyes 

刚刚试了执行paddle train --help，然后出错了：

/home/work/weitian/paddle/output/bin/paddle_local: /home/work/weitian/paddle/output/python27-gcc482/bin/pip: /home/wangyanfei/paddle_internal_release_tools/idl/paddle/output/python27-gcc4: bad interpreter: No such file or directory
pip should be installed to run paddle.

/home/wangyanfei/paddle_internal_release_tools/idl/paddle/output/python27-gcc4这个路径并不存在，是不是写死在代码里了？

**Comment by backyes** [comment]
```
cat /home/work/weitian/paddle/output/python27-gcc482/bin/pip
```
如果输出的最上一行#！不是 ```#!/home/work/weitian/paddle/output/XXXXXX``` , 那么应该是你安装过程出错，或者没有使用指定的安装命令，导致未完全安装所致。 


如果有必要，请附上详细的安装过程和日志

**Comment by backyes** [comment]
太长无响应，关闭issue
