### ISSUE TITLE
Check GPU at runtime

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#771]

**Comment by wangkuiyi** [comment]
As pointed out by @gangliao and @hedaoyuan , this is impossible because CUDA related shared libraries are loaded before the execution of the `main` function.

**Comment by lamhoangtung** [comment]
If this is impossible. How can Pytorch have something like: `torch.cuda.is_available()` @wangkuiyi ? cc @gangliao  @hedaoyuan

**Comment by gangliao** [comment]
I don't recall the details since it has been 5 years, but I think the context mentioned here is different. 

Of course, Pytorch can explicitly approach the GPU driver to detect whether a GPU is present in the environment.

https://pytorch.org/docs/stable/_modules/torch/cuda.html#is_available

**Comment by lamhoangtung** [comment]
Hi @gangliao. Thanks for the response. I forget to look at the time of this issue. BTW, I'm looking for the equivalent of `torch.cuda.is_available()` in PaddlePaddle. I've been searching the web but yet to find it. Can you help me out here ?

**Comment by mineshmathew** [comment]
@lamhoangtung You can verify whether paddle is using GPU using the `get_device` function - See [this](https://www.paddlepaddle.org.cn/documentation/docs/en/api/paddle/device/get_device_en.html)
