### ISSUE TITLE
请问在训练过程如何在开发集上做自定义的评价

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7716]
背景
------
目前在做句子打分（排序）模型，希望在开发集上算一个NDCG分数。

当前paddle在训练过程中做评价的方法
-------------------------------------

我查看了一些示例代码，感觉基本是这么做的：

```Python
trainer = paddle.trainer.SGD(
        cost=model.cost,
        parameters=params,
        update_equation=optimizer,
        **extra_layers=model.eval** # define extra_layers
 )

# devel
result = trainer.test(
                reader=paddle.batch(
                data_generator.train_reader(test_file_list),
                batch_size=conf.batch_size),
                feeding=feeding)

print("Test %d, Cost %f, Eval %s" %
                  (event.pass_id, result.cost, 
                   **result.metrics** # 评价值
                  ))
```

其中 extra_layers 定义里是paddle.v2.evaluators 预先定义的值

问题
-----------
NDCG的评价不在evaluators中，也就是需要做自定义的评价，该如何做呢？
此外，trainner.test 是否能够给出更加详细的API解释呢

**Comment by qingqing01** [comment]
1.  如何在训练中test

    请参考文档示例： https://github.com/PaddlePaddle/models/blob/develop/ltr/train.py#L94

2. trainer.test接口文档

    请参考http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/run_logic.html#trainer 中国年test()接口

3. NDCG计算

    我看LambdaCost里计算的就是NDCG，并且作为了输出，是否可以直接使用这个？至于如何事情，请参考1中给出的示例。 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L384

4. 如何自定义评价方法

    请参考[示例文档](https://github.com/PaddlePaddle/models/blob/2e13e0602c34c5421b80d5c20121c64dc4480fb3/ltr/README.md#%E8%AE%AD%E7%BB%83%E8%BF%87%E7%A8%8B%E4%B8%AD%E8%BE%93%E5%87%BA%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AF%84%E4%BC%B0%E6%8C%87%E6%A0%87)将需要的层输出，在Python里定义评价函数，调用、计算、输出即可。

**Comment by memeda** [comment]
哇，我试了“如何自定义评价方法”，还是不行啊...

**Comment by qingqing01** [comment]
`calc_sent_doc_sim` 是[`paddle.layer.recurrent_group`](http://www.paddlepaddle.org/docs/develop/documentation/en/api/v2/config/layer.html?highlight=recurrent_group#recurrent-group)层，不支持获取该层里面的内容。

**Comment by memeda** [comment]
哇， 我找到方法啦
1. 把infer的layer也create出来，
2. 然后把它作为 trainner 的  extra_layers
3. 把trainner.test 的reader的batch size设为整个devel数据集大小，使得整个devel数据集只跑一次前向
4. 利用 event.gm.getLayerOutputs 得到跑完前向后的infer layer的输出结果

哈哈，非常感谢，暂时来看还可以用...

**Comment by qingqing01** [comment]
>  利用 event.gm.getLayerOutputs 得到跑完前向后的infer layer

在你上面列子中`infer layer`是哪个呢？

**Comment by memeda** [comment]
哦，是额外的一个layer哈，就是在得到sim_val_vec 之后，做了一下kmax

```
        kmax_indices = paddle.layer.kmax_seq_score(
            input=sim_value_vec,
            beam_size=top_k,
            name="kmax_score_indices"
        )
```

**Comment by qingqing01** [comment]
问题已解决，关闭次Issue.
