### ISSUE TITLE
自定义layer

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#7734]
keras的Lambda层支持自定义layer，比较方便，类似：
// add a x -> x^2 layer
model.add(Lambda(lambda x: x ** 2))

paddlepaddle有没有类似的实现也能支持layer的自定义？

**Comment by qingqing01** [comment]
@zhglzh PaddlePaddle目前不支持~

**Comment by qingqing01** [comment]
@zhglzh 是当前Layer不能满足你的要求吗？ 也可以详细说明背景~

**Comment by chengduoZH** [comment]
当前fluid支持对每个layer的输出做简单的运算，如加减乘除 https://github.com/PaddlePaddle/Paddle/blob/3646be7bfca135fc20eb291dcbe14e13c93d8429/python/paddle/v2/fluid/tests/test_math_op_patch.py#L23-L177
非常复杂的还没有，请问您的应用场景是怎样的呢？ @zhglzh
