### ISSUE TITLE
想在一个流程的脚本里初始化多个模型来做预测，但是paddle.init()方法只能初始化一次，怎么破

### ISSUE THREAD

**Issue by xiangjinxin1019** [PaddlePaddle/Paddle#7738]
有个需求场景，需要在一个完整的流程中调用多个模型执行预测，每个模型都需要初始化，但是paddle.init()方法只能被初始化一次，该怎么解决呢？

**Comment by qingqing01** [comment]
`paddle.init()` 正常只需要初始化一次。 多个模型使用的同一个配置呢？还是不同的配置呢？建议多次预测，肯定是没问题的。

**Comment by yeyupiaoling** [comment]
@qingqing01 
我猜他的需求类似这样的:例如一个桌面应用,进入不同的界面实现识别不同类别的物体.但是这样问题就来了,PaddlePaddle只能init一次,同时创建分类器只能执行一次,这样就有问题了.

**Comment by yeyupiaoling** [comment]
@xiangjinxin1019 
兄弟,怎么没下文了,我还想看你是怎么解决这个问题的呢

**Comment by liuhuiCNN** [comment]
同问

**Comment by yeyupiaoling** [comment]
@liuhuiCNN 怎么来了，你也要解决这个问题吗？

**Comment by will-am** [comment]
可以参考这个issue中的办法：https://github.com/PaddlePaddle/Paddle/issues/7897
