### ISSUE TITLE
用docker搭建paddle集群的话，需要开放哪些端口？

### ISSUE THREAD

**Issue by qianxiaoyun** [PaddlePaddle/Paddle#774]
不同物理机之间docker通信需要哪些端口？

**Comment by qianxiaoyun** [comment]
不同物理机之间docker通信需要哪些端口？

**Comment by reyoung** [comment]
http://www.paddlepaddle.org/doc_cn/concepts/use_concepts.html#id6

**Comment by wangkuiyi** [comment]
@reyoung 我看到文档里有一行

```
paddle pserver --port=5000 --num_gradient_servers=4 --nics='eth0'
```

是不是只需要开放 5000 就可以了？

**Comment by backyes** [comment]
@qianxiaoyun 

Paddle does not depend on any concret port, while it just needs some port range resources. Like Nginx, Paddle can listen on any ports in theory. 

In docker, if setting: 
``` 
paddle pserver --port=5000 --port_num=2
```
which means port 5000, 5001 ports should be allowed for **docker VM**, 

```
paddle pserver --port=5000 --port_num=2 --ports_num_for_sparse=3
```
which means port 5000, 5001, and 5002,5003 should be allowed for **docker VM**. These ports 5002,5003 are reserved by sparse cluster training. Paddle will create one pserver threads for each dense port or sparse port to harness high-bandwidth(fat communication channel) channel. 

> 不同物理机之间docker通信需要哪些端口？

Each dockers' port will be mapped to physical's port , so these ports needed to be open in physical machine depends on the map setting. That's not Paddle's consideration.
