### ISSUE TITLE
Need add one_hot operator

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#7740]
Given an index variable and a depth, the operator will return the one-hot representation.

**Comment by abhinavarora** [comment]
Hi @pkuyym Could you please give an example. I understand one-hot representation, but the meaning of `index` and `depth` is not clear. It would be great if you can give an example. 

What I understood from the post : 
If we have index = 2 and depth = 5, we return `00100`.

Is this correct?

**Comment by pkuyym** [comment]
@abhinavarora Yeah, you are right, that's what `depth` means. This operator mainly refers to https://www.tensorflow.org/api_docs/python/tf/one_hot

**Comment by abhinavarora** [comment]
@pkuyym Thank you for confirming. I can implement this op if you are not already implementing it?

**Comment by pkuyym** [comment]
@abhinavarora You are welcomed to implement this op, thanks.

**Comment by pkuyym** [comment]
@abhinavarora Hi, I wonder have you started the implementation ? If yet, I can submit a PR ASAP.
