### ISSUE TITLE
Implement Book Chapter 06 Understanding Sentiment (LSTM) in distributed framework

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#7749]

**Comment by typhoonzero** [comment]
@abhinavarora  @Yancey1989 I think this is done?

**Comment by Yancey1989** [comment]
Yes, the demo code is [here]( https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_understand_sentiment.py).
