### ISSUE TITLE
Migrate private registry server to bcc

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#7758]
Migrate the private registry server to bcc:
1. Deploy the private registry server on bcc.
1. Change the domain from `docker.paddlepaddle.org` to `docker.paddlepaddlehub.com` and also the document, TeamCity.

**Comment by typhoonzero** [comment]
Need to add the reason why should we do this.

**Comment by Yancey1989** [comment]
Thanks for @typhoonzero 's remind and the reason is as following:
1. For currently, the registry server was deployed on an ECS instance on AliYun (HK region), the connection is not stabilization just because of the GFW, and on the other hand, we have an official account on `cloud.baidu.com`, so migrate the registry server to `cloud.baidu.com` is a better way.
1. The domain `docker.paddlepaddlehub.com` has already been **beian** by @llxxxll , we can use this  domain in China.
