### ISSUE TITLE
做验证码和车牌的“端到端”识别有没有例子，或者说一下它的思想也好

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#7767]
做验证码和车牌的“端到端”识别有没有例子，或者说一下它的思想也好
说说用paddlepaddle来实现的思想，给个思路，我一点头绪多没有。

**Comment by Xreki** [comment]
你好，可以参考下[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)的例子。

**Comment by yeyupiaoling** [comment]
@Xreki 
好的,我先研究研究这个例子,如果再不懂,再来问,能否?

**Comment by Xreki** [comment]
欢迎提问题，我们尽力解答~

**Comment by chengduoZH** [comment]
这个issue已经得到非常好的解答，我先关了，如果有技术上疑问，请另建issue讨论，谢谢！

**Comment by yeyupiaoling** [comment]
@chengduoZH 好的，我今晚就打算关的，我也不喜欢issue一直开着。
