### ISSUE TITLE
汉化工作--image classification

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#778]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/image_classification/index_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/image_classification/)

文件命名为 index_cn.md

**Comment by llxxxll** [comment]
baidu_hi: hu_yi_qing 认领，还未注册github.

**Comment by maurise-yq-hu** [comment]
确认认领
