### ISSUE TITLE
MulOp实现问题咨询

### ISSUE THREAD

**Issue by alexqdh** [PaddlePaddle/Paddle#7783]
1. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_op_cn.md
这篇文档中关于MulOp实现跟代码里对不上，用的REGISTER_OP，最新代码mul_op.cc里调用REGISTER_OPERATOR，且把mul与mul_grad分为两次注册，不知道哪种方式是最新的? 在dropout_op.cc中是用的REGISTER_OP。
2. MulOp中目前前向后向推导output维度的时候，我看分别用了ops::MulOpShapeInference与InferShape两种方式，后面推荐是用哪种?

**Comment by reyoung** [comment]
1. `REGISTER_OP`调用了`REGISTER_OPERATOR`，二者目前都支持。 `REGISTER_OP`的接口相对简单。
2. 推导维度可以继承framework::InferShapeBase 写一个functor，也可以override InferShape函数。二者最后都会生成一个functor注册给OpInfo结构体。

**Comment by Xreki** [comment]
你好，补充关于`REGISTER_OP`和`REGISTER_OPERATOR`讨论的两个issue，以供参考：https://github.com/PaddlePaddle/Paddle/issues/7147 https://github.com/PaddlePaddle/Paddle/issues/7158

**Comment by alexqdh** [comment]
谢谢回答，另外提个小建议，MulOp中REGISTER_OPERATOR注册的时候既然已经把mul与mul_grad分开，感觉把DefaultGradOpDescMaker放到mul_grad注册那里更清晰点。

REGISTER_OPERATOR(mul, paddle::framework::OperatorWithKernel, ops::MulOpMaker,
                  ops::MulOpShapeInference,
                  paddle::framework::DefaultGradOpDescMaker<true>);
REGISTER_OPERATOR(mul_grad, ops::MulOpGrad);

**Comment by chengduoZH** [comment]
现在mul已经换成了REGISTER_OPERATOR

https://github.com/PaddlePaddle/Paddle/blob/3646be7bfca135fc20eb291dcbe14e13c93d8429/paddle/operators/mul_op.cc#L158-L161
