### ISSUE TITLE
汉化工作--sentiment_analysis

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#779]
将https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/sentiment_analysis/sentiment_analysis.md 翻译成中文

**Comment by wangkuiyi** [comment]
请将中文版本提交到上述目录里，并且命名为 sentiment_analysis_cn.md 就好。或者email给 yi.wang.2005@gmail.com，代为提交。

**Comment by luotao1** [comment]
该文档已经有中文版本了，close了。
