### ISSUE TITLE
PaddlePaddle Fluid 中的 layers.data中的shape属性可以使用None 表示不确定大小吗

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#7795]
我正在做一个CNN的转移工作。 输入的数据大小是不确定的，所以问一下是否可以像tensorflow那样使用None表示可变大小

**Comment by Yancey1989** [comment]
还不可以，现在[fluid.layers.data](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/layers/io.py#L21) 需要一个指定的shape。 另外能麻烦描述一下具体的场景吗，我们看下是否有其他方法解决或者开发新的feature支持这种特性。

**Comment by zzhzz** [comment]
是这样的，输入层需要输入的是一颗多叉树，具体的输入方式是按照邻接表的方式输入的。这样一来输入的大小就是一个不确定的矩阵。目前来看，fluid.layers.data需要指定一个shape并且实际训练中输入的shape必须是这个shape。由于训练数据大小不一，我必须将数据统一成同一个大小的矩阵，增加了训练的时间。

**Comment by zzhzz** [comment]
是这样的，输入层需要输入的是一颗多叉树，具体的输入方式是按照邻接表的方式输入的。这样一来输入的就是一个大小不确定的矩阵，并且不同树的大小也不是统一的。目前来看，fluid.layers.data需要指定一个shape并且实际训练中输入的shape必须是这个shape。由于训练数据大小不一，我必须将数据统一成同一个大小的矩阵，增加了训练的时间。

**Comment by guoshengCS** [comment]
fluid.layers.data中的指定的shape可以认为是placeholder只是为了生成配置使用的，实际feed的数据的大小是可以变化的，OP在执行时会获取运行时数据的实际大小，但不排除部分OP会受静态配置shape的影响。
