### ISSUE TITLE
期望本机安装paddlepaddle 0.10.0以上 noavx版，源码安装不成功，求大神指导。

### ISSUE THREAD

**Issue by Rainbowkfc** [PaddlePaddle/Paddle#7798]
初入门，因docker内调试不太方便，想本机安装paddlepaddle，便于pycharm本地调试，pip内默认的是需支持avx版的0.11.0，网站上的deb包有0.9.0的noavx版本，安装正常但不支持paddle.v2，多次尝试源码安装，每次到cmake..的后一步“make -j `nproc`”时，时间非常长，而且build文件夹越来越大，留了8G空间都被占满导致最后不成功，参考安装方式是：http://geek.csdn.net/news/detail/242639，请问有安装成功的大神吗，求指导～～～

**Comment by luotao1** [comment]
请参考 https://github.com/PaddlePaddle/Paddle/issues/5803#issuecomment-359812057 来节省空间。

**Comment by Rainbowkfc** [comment]
好的，我先试试，谢谢。

**Comment by yeyupiaoling** [comment]
@Rainbowkfc 是否已正常编译?

**Comment by luotao1** [comment]
可以在 https://paddleci.ngrok.io/viewType.html?buildTypeId=Manylinux1_CpuNoavxOpenblas 下载noavx的whl包。稍后我们会更新文档。

**Comment by Rainbowkfc** [comment]
按照 @luotao1 的方法去掉了单测正在进行编译
cmake .. -DWITH_GPU=OFF -DWITH_TESTING=OFF -DWITH_AVX=OFF

**Comment by Rainbowkfc** [comment]
好的，编译还不行我就直接下载。 @luotao1

**Comment by yeyupiaoling** [comment]
@Rainbowkfc 
我觉得还是自己编译的比较好，这样才能保证你的paddlepaddle才是最新的

**Comment by Rainbowkfc** [comment]
@luotao1 @yeyupiaoling @Yancey1989  已编译成功，同时也试了下载的资源，都可正常安装，非常感谢各位帮助～谢谢～
