### ISSUE TITLE
汉化工作--text generation

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#781]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/text_generation/index_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/tutorials/text_generation)

文件命名为 index_cn.md

**Comment by llxxxll** [comment]
已认领,@StrangerG

**Comment by StrangerG** [comment]
确认认领
