### ISSUE TITLE
又一个 CosSimOp：  Check failed: square_sum_x > 0 && square_sum_y > 0 ，以及可能的DEBUG方法

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7815]
问题
-------------
![image](https://user-images.githubusercontent.com/5585818/35315529-d2790b20-0107-11e8-91b7-ac5d7a579e4b.png)

相似issues
------------

#7299 [Check failed: square_sum_x > 0 && square_sum_y > 0](https://github.com/PaddlePaddle/Paddle/issues/7299) 

回答检查数据是否为0,无后续跟进

#3586 [CosSimOp.cpp:54\] Check failed: square_sum_x > 0 && square_sum_y > 0](https://github.com/PaddlePaddle/Paddle/issues/3586)

回答检查数据是否为0，无后续

措施
---------------
第一遍，我先检查输入是否有空的情况，的确是有的！过滤掉了150+条；
再跑，比上次多跑了200多个batch，但是最后还是报这个错误core掉。
再次检查数据，确认不包含空输入，那么按照这个core信息，只可能是`cos_sim`中的`a, b`可能是0向量了。 这个两个向量是输入做卷积、全连接的结果，感觉为0的可能太低了。

经过提醒，**可能是用了`Relu`的原因**， 我再测试一下

疑问
-------------
1. 是否有可能其他原因，导致这个core？
2. 是否有debug机制，比如这个dump出来的30G+的core，能不能用上？有没有一种合适的debug方法，能够拿到core之前的输入，以及此刻的paddle内部状态？

模型信息
-------------
模型代码太长，就不直接粘出来了，也没有做可视化，只能大概说下连接情况：

目标问题：抽取式摘要

参考模型：DSSM

思路：获取title的表示、每个句子的标题，拿title去attend到每个句子表示，然后得到句子的权重，将句子加权平均得到doc的表示；算doc表示与每个句子表示的cos-sim；训练过程根据预先生成的 (left-sent-id, right-sent-id, label) 来算rank-loss；预测过程取cos-sim topk的句子。

输入：title与句子同等表示，都有7种离散特征，句子以列表形式组合到一起成为doc；也就是输入有14个元素，前7个是title的特征列表，后7个是doc的特征列表。对于训练实例，还有3个列表，分别是left-sent-id-list, right-sent-id-list, label-list. 保证输入都不空。

内部连接：title或句子，每种特征都是先做CNN，把7中特征CNN的结果concat，再过一个全连接，得到句子表示；算 title 到句子的attention，得到doc表示；doc表示与每个句子算`cos_sim`，得到`cos_sim`列表；训练过程，取left-sent-id、right-sent-id对应的`cos_sim`值，算rank-loss; 预测就是取`cos_sim`列表topk的sent-id-list

**Comment by Yancey1989** [comment]
根据issue中的comment，能否找到造成core dump的数据呢？

**Comment by memeda** [comment]
没有找到... 目前是batch跑的，只知道core掉的batch id，具体哪一条不太清楚的

**Comment by Yancey1989** [comment]
可以根据二分法和在reader记录日志的方式，找到引起core dump的数据吧，能复现问题才好进一步排查。

**Comment by memeda** [comment]
嗯嗯，好的
现在paddle遇到错误只能core掉吗，能不能抛出异常交给上层处理呢，或者core掉的时候把数据信息，内部矩阵信息以文本的方式dump一下呢，只dump 一个core，给debug带来的很大的麻烦

**Comment by jinyongbo128** [comment]
@memeda  请问这问题后来解决了吗？ 我这边也遇到同样问题，
数据确定不为空，激活全部改成tanh，依然core

**Comment by memeda** [comment]
@jinyongbo128 抱歉，才看到…… 解决了哈，我这边换成Tanh就不core了
感觉这里core掉应该是全0的问题，可以再检查一下哈，会不会存在0的向量作为原始输入呢？
