### ISSUE TITLE
汉化工作--semantic_role_labeling

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#782]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/semantic_role_labeling/index_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/semantic_role_labeling/)

文件命名为 index_cn.md

**Comment by llxxxll** [comment]
已认领，@livc
