### ISSUE TITLE
Threadpool needs to have two instances, one for calculations the other one for doing IO (e.g. RPC calls).

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#7828]

**Comment by gongweibao** [comment]
How many threads should each contain?

**Comment by helinwang** [comment]
Please consider this comment: https://github.com/PaddlePaddle/Paddle/pull/7705#issuecomment-360219569

**Comment by typhoonzero** [comment]
@helinwang right, I'll close this for now.
