### ISSUE TITLE
汉化工作--imagenet_model

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#783]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/imagenet_model/resnet_model_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/imagenet_model/)

文件命名为 resnet_model_cn.md

**Comment by llxxxll** [comment]
已认领，@CrossLee1
