### ISSUE TITLE
汉化工作--embedding_model

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#784]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/embedding_model/index_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/embedding_model/)

文件命名为 index_cn.md

**Comment by llxxxll** [comment]
@water1981 已认领
