### ISSUE TITLE
小白求助..新手上路

### ISSUE THREAD

**Issue by BlankRain** [PaddlePaddle/Paddle#7840]
我有已经分类好的图像数据.
举个例子:
- 老王(文件夹) 
      -  00.png (图像文件)
      -  01.png 
      ...
      -   ${n}.png 
- 老李(文件夹)
     -  00.png (图像文件)
      -  01.png 
      ...
- 老张
     - ...
-  老....

总之,这么一个树形结构.
文件夹名就是它的类别,每个文件夹下放的是他们的图片(不是他们的照片,不用考虑人脸识别.)

现在我想基于此数据,训练个模型, 拿一张新图片, 让它识别出是老张还是老王.

http://www.paddlepaddle.org/docs/develop/book/03.image_classification/index.cn.html
这个教程数据集已经做好了..

小白求助
1. 这种个该怎么训练.
2. 个人自定义的训练数据集,该怎么处理加载进来.

**Comment by yeyupiaoling** [comment]
@BlankRain 您好,可以参考这个例子:http://blog.csdn.net/qq_33200967/article/details/79095265
