### ISSUE TITLE
增加trainer數量

### ISSUE THREAD

**Issue by redfish-lee** [PaddlePaddle/Paddle#7848]
在  [Paddle/doc/design/cluster_train/checkpointing.md](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/checkpointing.md)
  中提到“目前只考慮動態擴容trainer數量，可以減小系統複雜性。”

這裡指的複雜性是指 ps 動態調整帶來的複雜性？

**Comment by Yancey1989** [comment]
是的，因为在每个PServer节点上会存储整个模型中的一部分参数信息，如果要实现PServer的动态调整主要大概有以下几个方便需要考虑：
- 每个PServer节点上的数据需要重分布
- 保证PServer节点调整时数据不丢失，例如如何处理在扩容期间节点失败如何回滚等操作。
- 在PServer节点扩容时，如何协调trainer节点的参数更新。

考虑到动态调整PServer节点数量带来的收益并没有很高，所以暂时没有列为主要的feature。

**Comment by redfish-lee** [comment]
ok thanks

**Comment by redfish-lee** [comment]
ok thanks
