### ISSUE TITLE
JD：PaddlePaddleTechWriter

### ISSUE THREAD

**Issue by llxxxll** [PaddlePaddle/Paddle#787]
# PaddlePaddle Tech Writer 招募志愿者

## 【职责】PaddlePaddleTechWriter — 教程撰写方向（Tutorial）
【要求】
- 对DeepLearning某一块知识（如优化、通信、调参、某一个网络结构、某一项具体实践任务等）非常了解
- 内容组织条理清晰
- 具备一定的文字组织能力
- 能准确把握读者阅读过程中的心理变化

【入组流程】
- 提交原创教程一篇至 paddle-dev@baidu.com; 邮件标题为『应聘TechWriter-Tutorial』

## 【职责】PaddlePaddleTechWriter — 设计有趣的深度学习示例（Interesting examples）
【要求】
- 对DeepLeanring非常了解
- 有很强的编程能力
- 具备跨平台开发经验（端、硬件等）优先
- 愿意与PaddlePaddle的极客们创造有趣的应用场景

【入组流程】
- 提交自我介绍或作品至 paddle-dev@baidu.com ，邮件标题为『应聘TechWriter-Interesting examples』

***

关于：PaddlePaddle Tech Writer

是由热爱深度学习、并愿为中国深度学习开源平台贡献自己力量的伙伴们组成。
『PaddlePaddle Tech Writer Group』主要负责文档的多语言化（Translated）、教程撰写（Tutorial）、设计有趣的深度学习示例（Interesting examples）。
如果您擅长上述任何一项，非常期待您加入我们

**Comment by llxxxll** [comment]
![7587e20e1319cbf32493f6b3c](https://cloud.githubusercontent.com/assets/1908992/21219276/194fc97e-c2ef-11e6-8e5d-4eba107aa483.png)

**Comment by helinwang** [comment]
Closed due to inactivity, please reopen if necessary.
