### ISSUE TITLE
集群模式参数设置

### ISSUE THREAD

**Issue by sarawon** [PaddlePaddle/Paddle#788]
按照cluster_train的步骤跑的集群demo
关于参数设置方面有几个问题：
1.下面命令里的trainer_count是跟所有机器上的pserver总数一样吗？还有每台机器上的pserver个数跟机器配置有关系吧？
python paddle.py \
  --job_dispatch_package="${PATH_TO_LOCAL_WORKSPACE}" \
  --dot_period=10 \
  --ports_num_for_sparse=2 \
  --log_period=50 \
  --num_passes=10 \
  --trainer_count=4 \
  --saving_period=1 \
  --local=0 \
  --config=./trainer_config.py \
  --save_dir=./output \
  --use_gpu=0
2.感觉单机和集群模式训练模型使用的时间是一样的，是参数哪里设置的不对吗？
3.训练完了程序好久没有退出？

**Comment by backyes** [comment]
@sarawon 

> 1.下面命令里的trainer_count是跟所有机器上的pserver总数一样吗？还有每台机器上的pserver个数跟机器配置有关系吧？

 trainer_count指示一个trainer会起trainer_count个并行线程，共同完成一个mini-batch数据的forward和backward过程，所以这个参数跟pserver数目没有关系。我们提供的简易脚本里，提供N个trainer（可能包含trainer_count个trainer thread）和N个pserver，且一个物理节点对应一个trainer和一个pserver，所有的trainer将利用所有的pserver进行通信，同步参数。

> 感觉单机和集群模式训练模型使用的时间是一样的，是参数哪里设置的不对吗？

根据guide，如果你没有对训练数据进行手动划分，那么所有的节点将分别对所有全量的数据进行处理，所以时间上和单机没有区别，因为你相当于每个节点都对完整数据做了训练（这其实是不对的）。 从你使用的```--job_dispatch_package```来看，你应该是将本地所有样本直接推送到了所有节点，因此每个节点都重复做了一次完整的训练。 文档中提到这个```--job_dispatch_package```主要辅助用户完成调试。 实际训练中，需要用户手动**划分**数据，并配置train.list和test.list，然后利用```--job_workspace``` 完成实际训练。
关于集群训练，很快我们将推出更加完备的的集群训练方法。

> 训练完了程序好久没有退出？

我们提供的简易脚本，是一个阻塞式的脚本，训练完成后，用户直接ctrl + c就能停止训练，并清除所有节点上训练进程。

**Comment by backyes** [comment]
建议结合我上面的回答，再仔细阅读并理解简易多机脚本的逻辑, :-) 。

**Comment by sarawon** [comment]
@backyes 多谢回复的这么详细哈。
那pserver的端口数设置主要作用是什么呢？

**Comment by backyes** [comment]
优化连接并发度，对于短肥通信管道可以起到提高带宽利用率和pserver计算并发度的作用
