### ISSUE TITLE
请问 fluid.layers.data 可以直接进行数乘运算吗

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#7896]
就是这样：
>
layer = fluid.layers.data(name='x', shape=[10, 10])
layer_ = layer * 0.5

**Comment by chengduoZH** [comment]
是支持的，请参看这里： https://github.com/reyoung/Paddle/blob/87b424e866b742b0173389ace4abfd6e66caa1ad/python/paddle/v2/fluid/tests/test_math_op_patch.py#L82-L92
