### ISSUE TITLE
官方例子image_classification提交MPI任务出错

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle#790]
日志信息如下：

> Thu Dec  8 19:55:24 2016[1,0]<stderr>:Python Error: <type 'exceptions.IOError'> : [Errno 2] No such file or directory: '\xff\xc4'
Thu Dec  8 19:55:24 2016[1,0]<stderr>:Python Callstack: 
Thu Dec  8 19:55:24 2016[1,0]<stderr>:            /home/disk1/normandy/maybach/237307/workspace/thirdparty/thirdparty/image_provider.py : 72
Thu Dec  8 19:55:24 2016[1,0]<stderr>:Calling iterator next error

**Comment by backyes** [comment]
@pkuyym 

paddle_platform自带的test样例是测试case，可能不兼容最新paddle。请依照http://deeplearning.baidu.com/doc/deprecated_doc/doc_cn/demo/index.html 中demo的示例，完成多机训练。 或者根据文档思路，自己基于开源的单机demo，自行修改成多机demo，从单机到多机迁移成本也非常低。

以后百度内部将不再针对每一个单机版本的demo，构建多机版本demo，历史demo集群版本参看 历史文档http://deeplearning.baidu.com/doc/deprecated_doc/doc_cn/demo/index.html

**Comment by pkuyym** [comment]
@backyes 
demo就是依据http://deeplearning.baidu.com/doc/deprecated_doc/doc_cn/demo/index.html的步骤提交的，现在新的问题是多机版提交任务thirdpary的before_hook.sh执行出错，日志如下：

> Fri Dec  9 12:02:29 2016[1,0]<stderr>:Could not execute the executable "./thirdparty/thirdparty/before_hook.sh": Exec format error
Fri Dec  9 12:02:29 2016[1,0]<stderr>:
Fri Dec  9 12:02:29 2016[1,0]<stderr>:This could mean that your PATH or executable name is wrong, or that you do not
Fri Dec  9 12:02:29 2016[1,0]<stderr>:have the necessary permissions.  Please ensure that the executable is able to be
Fri Dec  9 12:02:29 2016[1,0]<stderr>:found and executed.

**Comment by backyes** [comment]
这个问题的确奇怪，方便私下提供job地址吧

**Comment by pkuyym** [comment]
@backyes 
已解决，before_bash.sh第一行的注视应该是#!/bin/bash，而不能使其它注视
