### ISSUE TITLE
conv_2d cuDNN operator slow

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#7902]
During the benchmarking of https://github.com/dzhwinter/benchmark/blob/master/fluid/mnist.py, I found [conv_2d](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/layers/nn.py#L250) with cuDNN is slow. It turns out the ~~`element_wise_add`~~ `element_wise_add_grad` bias takes about 80% of the time while the actual cudnn_conv only takes 10%.

![image](https://user-images.githubusercontent.com/29932814/35462153-a707fed0-029f-11e8-9a95-f28f667aaee4.png)

@dzhwinter This looks pretty bad to me. Please confirm if you've seen the similar results during your benchmarking? I am using `nvprof` and NVIDIA Visual Profiler.

I am wondering if we can do one of the following.

1. See if can improve the `elementwise_add`, but I am not sure how hard it is in Eigen. @reyoung 
1. Combine conv and add bias into one operator, like [CudnnConvBaseLayer.cpp](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CudnnConvBaseLayer.cpp#L105) in v2.

We need to improve this due to the importance of this operator in vision task.

Issue related: https://github.com/PaddlePaddle/Paddle/issues/7862.

**Comment by chengduoZH** [comment]
The result of this issue #7862 shows that `elementwise_add_grad` is very time-consuming, but `element_wise_add` looks nomal. @tonyyang-svail

**Comment by tonyyang-svail** [comment]
@chengduoZH you are right. I have edited the issue.

**Comment by chengduoZH** [comment]
>  element_wise_add_grad bias takes about 80% of the time while the actual cudnn_conv only takes 10%.

How do you get these two proportions (80% and 10%) from `nvprof`?  conv_2d and element_wise_add_grad are two independent operations.
