### ISSUE TITLE
Make paddle_util not to reference cuda

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#793]
During developing bazel build, we discover paddle_util package reference some CUDA headers(basically in `Utils.h`).

To reproduce this issue, just check out branch `feature/bazel_build`, then run `bazel build paddle/utils:paddle_utils` in MacOS, (currently only MacOS is supported).

The screen record is [here](https://asciinema.org/a/8ts4rkd45s5ecyz757o36ld75).

NOTE: We should fix this issue in `develop` branch because it is not just a bazel building problem.

**Comment by reyoung** [comment]
@gangliao Please help to fix this issue in develop branch.

**Comment by gangliao** [comment]
We did not adopt bazel as our building tool. So I closed this issue
