### ISSUE TITLE
More user-friendly Save/Load API of Fluid

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#7931]
We now have three save interface in [fluid](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/io.py):

- save_vars for saving a list of variables
- save_params for saving all parameters 
- save_persistables for saving checkpoint

And save_vars interface is not exposed to users directly since users can not access a variable created inside a layer. We can use save_persistables to do checkpoint when training. And we expect save_params can work in saving model for inference. 

But save_params and save_persistables are not enough to cover all cases. For example, if we want to save a model for inference network with BN layer, global mean variable is needed, whereas momentum variable is not needed. Both save_params and save_persistables are not satisfied.

We need to design a more user-friendly save/load API.

**Comment by reyoung** [comment]
Just adding a reference.

Tensorflow uses global sets of tensors, which are named `collections`, to identify the kind of a tensor. The collections could be [these](https://www.tensorflow.org/api_docs/python/tf/GraphKeys).
Users can save any parameters in any collection.
