### ISSUE TITLE
sequence convolutional neural network not fast enough

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Paddle#7935]
I built a text classification model with CNN under fluid framework and found that the training speed is not fast enough compared with my implementation. Since this model is pretty simple, I think we should make sure of the runtime bottleneck of this model.
https://github.com/PaddlePaddle/Paddle/wiki/Text-Classification-With-CNN-model

**Comment by peterzhang2029** [comment]
请问是用的哪个版本的PaddlePaddle运行的？我这边用最新的PaddlePaddle跑链接提供的脚本 test_acc始终是0.50000，字典是用的是 http://ai.stanford.edu/%7Eamaas/data/sentiment/aclImdb_v1.tar.gz 里面的 imdb.vocab 加上UNK字典大小为：89528.

**Comment by guru4elephant** [comment]
词典没问题，是在某一个时间点的develop branch上的版本，可能后续有人做了更新。

**Comment by peterzhang2029** [comment]
那请问您那边的环境使用最近版本的PaddlePaddle运行 https://github.com/PaddlePaddle/Paddle/wiki/Text-Classification-With-CNN-model  配置得到的精度和时间是多少呢？

**Comment by guru4elephant** [comment]
@peterzhang2029 实验结果在公司内部wiki，不方便贴在这里，我单hi给你。

**Comment by cheradam** [comment]
At the issue-triage meeting，marked this issue as low priority。
