### ISSUE TITLE
getNonStaticParameter()函数不是线程安全的，导致使用 MultiGradientMachine时可能出 core

### ISSUE THREAD

**Issue by LiuJiaqiang89** [PaddlePaddle/Paddle#7936]
在基于 Paddle 进行开发时，发现将 trainer_count 设置为大于 1 的数后，训练过程会在调用TrainerThread::mergeCpuGradients() (MultiGradientMachine.cpp) 时出 Core. 
追踪发现 mergeCpuGradients() 中调用了 getNonStaticParameters() 函数，该函数会修改 
nonStaticParameters_ 的数据，但并没看到做加锁等相关处理。
因为似乎其他同学在使用多线程训练时并没发现类似的问题，不知道是不是 Paddle 使用了
其他机制保证了多线程调用 getNonStaticParameters() 的安全性，求解答。

**Comment by kuke** [comment]
@LiuJiaqiang89 应该和``` trainer_count > 1```没关系，会有加锁保证参数更新是线程安全的。可以完整的贴下你的报错吗？

**Comment by LiuJiaqiang89** [comment]
报错 LOG 如下：
*** Aborted at 1516971977 (unix time) try "date -d @1516971977" if you are using GNU date ***
PC: @           0x951d9e paddle::VectorT<>::subVecFrom()
*** SIGSEGV (@0x29) received by PID 7802 (TID 0x7ff1cf38d700) from PID 41; stack trace: ***
    @     0x7ff26f52e160 (unknown)
    @           0x951d9e paddle::VectorT<>::subVecFrom()
    @           0x949199 paddle::TrainerThread::mergeGradDense()
    @           0x94e58e paddle::TrainerThread::mergeCpuGradients()
    @           0x94ec92 paddle::TrainerThread::backward()
    @           0x94ef70 paddle::TrainerThread::computeThread()
    @     0x7ff26da4a8a0 execute_native_thread_routine
    @     0x7ff26f5261c3 start_thread
    @     0x7ff26d1bb12d __clone

通过加新的 LOG 定位到是在 TrainerThread::mergeCpuGradients() 中调用时 para->useGpu()出的错。
补充代码：
```
void TrainerThread::mergeCpuGradients() {
  CHECK_EQ(mergeTypes_.size(), 1UL);
  CHECK_EQ(mergeTypes_[0], PARAMETER_GRADIENT);

  {
    REGISTER_TIMER("waitbeforeMerge");
    multiMachine_->waitBeforeMerge();
  }
  std::vector<const std::vector<ParameterPtr>*> slaveParameters =
      multiMachine_->getSlaveParameters();

  CHECK(slaveParameters.size());
  // Each thread will call getNonStaticParameters() here. 
  for (auto& para : multiMachine_->getNonStaticParameters()) {
    if (para->useGpu()) continue;
    if (para->isSparseRemoteUpdate()) {
      REGISTER_TIMER("mergeRemoteGradSparse");
      mergeGradSparseRemote(para.get(), slaveParameters);
    } else if (para->isGradSparseUpdate()) {
      REGISTER_TIMER("mergeGradSparse");
      mergeGradSparse(para.get(), slaveParameters);
    } else {
      REGISTER_TIMER("mergeGradDense");
      mergeGradDense(para.get(), slaveParameters);
    }
  }
  {
    REGISTER_TIMER("waitbeforeMerge");
    multiMachine_->waitAfterMerge();
  }
}
```
```
  std::vector<ParameterPtr>& getNonStaticParameters() {
    if (nonStaticParameters_.empty()) {
      for (auto para : parameters_) {
        if (!para->isStatic()) {
          nonStaticParameters_.push_back(para);
        }
      }
    }
    return nonStaticParameters_;
  }
```
从上面的代码看，在第一个线程调用 getNonStaticParameters() 时 nonStaticParameters_ 为空，因此会修改 nonStaticParameters_ 的内容，如果这个时候有其他线程调用 getNonStaticParameters() 可能会出问题。
通过修改 MultiGradientMachine.cpp 的构造函数，在构造函数里直接填充 nonStaticParameters() 的内容后，上面出 core 的问题没有再出现。
因为我是把 Paddle 集成到了我们内部的一个框架里，所以不排除是内部框架导致的问题。

**Comment by kuke** [comment]
@LiuJiaqiang89 ```getNonStaticParameters()```这里的逻辑应该没有问题，在cpu模式中多个线程之间的参数是共享的，所以只要一个线程获取参数并返回就没有问题了。这一块在平时用的时候没有出问题，建议你看下内部框架是否有问题。
