### ISSUE TITLE
求问如何求两个向量的平均值？

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#7951]
啊，翻了API几遍也没有找到

**Comment by kuke** [comment]
这个是可以做的，先用```addto``` layer将两个向量求和，再用```scaling``` layer 将求和结果乘以0.5就可以实现求平均值，这两个layer在文档中都能找到：http://paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html

**Comment by memeda** [comment]
但是 `scaling`的api是这样的呀

```Python
scaling(input=layer1, weight=layer2)
```
需要引入一个输入吗？

**Comment by kuke** [comment]
```weight```是scaling的因子，这里设置成0.5就可以了，但是要注意输入是layer类型的，可能需要转化下

**Comment by memeda** [comment]
嗯，除了FEEDING的方式，还有转化方法吗

**Comment by kuke** [comment]
@memeda 应该是没有其它的转化方法了

**Comment by memeda** [comment]
好的，非常感谢

**Comment by EchoCX** [comment]
> 嗯，除了FEEDING的方式，还有转化方法吗

请教一下，如何feeding做转化。

**Comment by fseasy** [comment]
就是把 0.5 作为一个输入
————
你在用v2吗？ 赶紧换到fluid吧，大幅节省时间
