### ISSUE TITLE
How cmake links libpython*.so to paddle_trainer

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#796]
I see that the executable `paddle_trainer` is built by [`paddle/trainer/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/trainer/CMakeLists.txt#L43) using

```
add_paddle_exe(paddle_trainer TrainerMain.cpp)
```

where `add_paddle_exe` calls `link_paddle_exe` defined in [`cmake/util.cmake`](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/util.cmake#L69) and [specifies Python as a dependency](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/util.cmake#L124):

```
    if(WITH_PYTHON)
        target_link_libraries(${TARGET_NAME}
            ${PYTHON_LIBRARIES})
    endif()
```

I am wondering how `cmake` knows the value of `PYTHON_LIBRARIES`.  After `grep`-ing the whole source code repo, I noticed that it is defined in [`paddle/api/paddle_api_config.py.in`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/paddle_api_config.py.in), and `paddle_api_config.py` is imported by other Python modules. The importing sequence is as follows:

1. in [`paddle/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/CMakeLists.txt#L10), cmake converts `setup.py.in` into `setup.py` and then `add_subdirectory(api)`. Note that `paddle/setup.py` is listed in `paddle/.gitignore`.

1. `paddle/setup.py.in` calls `import api.paddle_ld_flags`, where [`paddle/api/paddle_ld_flags.py`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/paddle_ld_flags.py) runs `from paddle_api_config import *`

1. where `paddle/api/paddle_api_config.py` is generated by [`paddle/api/CMakeLists.txt`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/CMakeLists.txt#L36) from [`paddle/api/paddle_api_config.py.in`](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/api/paddle_api_config.py.in).

1. In `paddle/api/paddle_api_config.py.in`, there is `PYTHON_LIBRARIES="@PYTHON_LIBRARIES@"`. This implies that `cmake` should have known the value of `PYTHON_LIBRARIES` before it can execute the `.in` template.  

But how does `cmake` knows the value of `PYTHON_LIBRARIES`?!

I'd thought that it was set by `cmake` standard macro [`FindPythonInterp`](https://cmake.org/cmake/help/v3.0/module/FindPythonInterp.html), but the document doesn't say so.

**Comment by reyoung** [comment]
> how does cmake knows the value of PYTHON_LIBRARIES?!

Use [FindPythonLibs](https://cmake.org/cmake/help/v3.0/module/FindPythonLibs.html) module to find `PYTHON_LIBRARIES`.

**Comment by backyes** [comment]
@wangkuiyi 

These find_package functions in top CMakeFile.txt will generate several specific CMake's variables, such as PYTHON_LIBRARIES for find._package(PythonLibs ...).  

Internally, each find_package(Somelib, ..) call will indirectly call FindSomelib.cmake module searched within  ```CMAKE_MODULE_PATH``` defined directory(such as ```Paddle/cmake/FindAVX.cmake```) and cmake's default Modules directory( such as ```/usr/local/share/cmake/Modules/FindJPEG.cmake```).

```

ind_package(PythonLibs 2.7 REQUIRED)
find_package(PythonInterp 2.7 REQUIRED)
find_package(ZLIB REQUIRED)
find_package(NumPy REQUIRED)
find_package(Threads REQUIRED)
find_package(AVX QUIET)
find_package(Glog)
find_package(Gflags QUIET)
find_package(GTest)
find_package(Sphinx)
find_package(Doxygen)
include(cblas)
```
