### ISSUE TITLE
[Discussion]Some FAQ maybe asked by new users.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#7963]
A new user of PaddlePaddle cluster maybe want to know:
1. How many resources are available for me in Cluster?
    - How many `trainers` and `pservers` can I create?
1. What's the best ratio of `pservers` and `trainers` to get the best performance? 
    - How to give useful advice?
    - Can we give the formula to estimated it according to parameter size and numbers？  
1. How to find what the job is doing?
    -I start 60 trainers and 10 pservers and it seems hangs after several hours. All of them doesn't print anything more.

**Comment by helinwang** [comment]
Thanks! Maybe our current vgg test can generate some data points that helps this issue.
