### ISSUE TITLE
Change the default option of `WITH_TESTING` to OFF

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#7969]
Now, as the default option of `WITH_TESTING` is ON, users always need a lot of space (more than 17GB) to build PaddlePaddle. (see #5803) 

Though, we have [document](http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/build_and_install/build_from_source_cn.html#build-step) to tell users to use `-DIWTH_TESTING=OFF`, the effect is not very good. 

Thus, can we change the default option of `WITH_TESTING` to OFF? @lcy-seso @typhoonzero How do you think about it ?

**Comment by typhoonzero** [comment]
I think we can. Also, `WITH_GOLANG` can be turned off by default. Let the CI build with these options turned on is enough.

**Comment by luotao1** [comment]
>  Also, WITH_GOLANG can be turned off by default

`WITH_GOLANG` already defaults OFF now.

**Comment by typhoonzero** [comment]
Okay.

**Comment by lcy-seso** [comment]
我在自己机器上大致比较简单的测试了一下。
- MAC下面原生的，不用docker编译（无GPU）：
    1. `DCMAKE_BUILD_TYPE=RelWithDebInfo` 且 `-DWITH_TESTING=ON`，build 目录 5.0G。
    1. `DCMAKE_BUILD_TYPE=Debug` 且 `-DWITH_TESTING=ON`，build 目录 7.2G。
    1. `DCMAKE_BUILD_TYPE=Debug` 且 `-DWITH_TESTING=OFF`，build 目录 7.0G。
- MAC下用docker 编译， `DCMAKE_BUILD_TYPE=Debug` ， `-DWITH_TESTING=ON`，build 目录 17G。
- Linux开发机上 ，GPU = ON，`DCMAKE_BUILD_TYPE=Debug` 且 `-DWITH_TESTING=ON`，build 目录 24.0G。

看上去`DWITH_TESTING`指定为ON或者OFF差别不是特别大。

**Comment by luotao1** [comment]
第二项和第三项，设置`DWITH_TESTING=OFF`后，build目录有多大呢？

**Comment by typhoonzero** [comment]
刚才用Linux + Docker，先删除build下所有文件，用
```
WITH_GOLANG=OFF
WITH_TESTING=OFF
WITH_DISTRIBUTE=OFF
WITH_GPU=OFF
```
编译，build目录为11G
