### ISSUE TITLE
The whl pacakge became so huge

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/Paddle#7971]
The whl package size became 400+MB from 80MB, who knows what's happened?
<img width="1537" alt="2" src="https://user-images.githubusercontent.com/1426912/35552502-07e54b04-05cf-11e8-9dba-38e8ceef8578.png">
<img width="1588" alt="1" src="https://user-images.githubusercontent.com/1426912/35552503-0818cac4-05cf-11e8-9fd1-5966423d60b6.png">

**Comment by Yancey1989** [comment]
After unizp the whl file, find that `core.so` increased to 400MB+, 

```bash
[root@k8s-node3 fluid]# ls -lhat
total 432M
drwxr-xr-x 7 root root 4.0K Jan 30 15:16 ..
drwxr-xr-x 4 root root 4.0K Jan 30 15:16 .
drwxr-xr-x 2 root root  181 Jan 30 15:16 layers
drwxr-xr-x 2 root root   49 Jan 30 15:16 proto
-rwxr-xr-x 1 root root 431M Jan 29 18:27 core.so
-rw-r--r-- 1 root root 7.5K Jan 29 18:00 clip.py
-rw-r--r-- 1 root root  23K Jan 29 18:00 distribute_transpiler.py
```

**Comment by luotao1** [comment]
In my server, the core.so compiled with develop branch (onlycpu+openblas) is still 40M.

**Comment by Yancey1989** [comment]
The cmake flag `BUILD_TYPE ` would be set to `RelWithDebInfo` if we don't specify any `BUILD_TYPE` argument, and I think there is a bug in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/scripts/docker/build.sh#L35 , the scripts doen't set `BUILD_TYPE` correctly.
