### ISSUE TITLE
NameError: name'define_py_data_source2' is not defined

### ISSUE THREAD

**Issue by PseudoProgrammer** [PaddlePaddle/Paddle#798]
NameError: name'define_py_data_source2' is not defined

when i try training in cluster with using default receivers, i has been told this error! what's wrong?wait for answer online!

**Comment by backyes** [comment]
@PseudoProgrammer 

请使用 http://deeplearning.baidu.com/doc/install.html 指定的最新receiver。

**Comment by PseudoProgrammer** [comment]
@backyes 
it says
"如何自定义Receiver
如须自定义Receiver，请修改local_config.py中的receivers变量，用自定义receiver替换原有receiver列表。"

i can't find local_config.py!can you tell me how to define Receiver?

**Comment by backyes** [comment]
@PseudoProgrammer  

应该文档更新有问题，我们fix下文档内容。

``` shell

PATH=```which   cluster_train.sh```
```
替换$PATH/local_config.py中列表，即可。

**Comment by backyes** [comment]
@PseudoProgrammer 

```
PATH=$(dirname `which cluster_train.sh`)/../opt/paddle_platform/$VERSION
```
替换$PATH/local_config.py 中receiver列表

**Comment by backyes** [comment]
@PseudoProgrammer 

文档已经更新

**Comment by PseudoProgrammer** [comment]
@backyes thank you! It's done.
But anther error happened,
"cluster.sh: line 20: --thirdparty=/home/renbing/.jumbo/opt/paddle_platform/1a014a0b8fe68964124d0da0fdb802f176f12eed/thirdparty: No such file or directory"

but the thirdparty is still here, why can't paddle find it

[renbing@yq01-dev-up-bdg22 1a014a0b8fe68964124d0da0fdb802f176f12eed]$ ll /home/renbing/.jumbo/opt/paddle_platform/1a014a0b8fe68964124d0da0fdb802f176f12eed/thirdparty
total 8
-rw-rw-r-- 1 renbing renbing  109 Dec  9 05:49 before_hook.sh
drwxrwxr-x 2 renbing renbing 4096 Dec  9 05:49 thirdparty

**Comment by backyes** [comment]
@PseudoProgrammer 

请参看： http://deeplearning.baidu.com/doc/deprecated_doc/doc_cn/index.html  中demo的集群示例。 如果遇到接口不兼容，请更新到最新版本。  

/home/renbing/.jumbo/opt/paddle_platform/1a014a0b8fe68964124d0da0fdb802f176f12eed/ 下的test 后续将不再更新。
