### ISSUE TITLE
使用paddlepaddle进行机器翻译如何调取本地训练集？

### ISSUE THREAD

**Issue by yanmengqi** [PaddlePaddle/Paddle#8003]
目前在使用paddlepaddle进行机器翻译的相关学习，目前我的中英文语料的训练集是本地文件的形式存储的，如果使用paddlepaddle进行训练的话，该如何调用本地训练集呢？

**Comment by yanmengqi** [comment]
Already solved,thank you!

**Comment by xingyushu** [comment]
怎么解决的呢，小白求大佬回答，改下接口吗

**Comment by yanmengqi** [comment]
没有想到更好的方法，用了个笨方法。把默认训练集的文件替换掉了，把MD5值重新计算后也替换掉，Paddle就会用你替换过的训练集训练了。

**Comment by xingyushu** [comment]
好的，谢谢！就是按照他们的格式替换下数据，文件名wmt14不改是吧，因为已经封装了那个接口

**Comment by yanmengqi** [comment]
是的，但是还需要修改MD5值，重新计算一下替换后文件的MD5值，然后在配置文件里修改掉。

**Comment by xingyushu** [comment]
配置文件在哪，好像模型里只有train.py和训练/测试的数据

**Comment by yanmengqi** [comment]
不太清楚你的安装目录。MD5验证值是在wmt14.py的文件里存着。也就是在你的Paddlepaddle安装目录里存着。

**Comment by xingyushu** [comment]
大佬，能否发下你改过后的数据集和wmt14.py到邮箱1402598162@qq.com,或者加下qq也行 @yanmengqi
