### ISSUE TITLE
如何仿照book的第三章的代码格式，写一个验证码端到端的识别

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8012]
在这个问题之前，我提了一个 #7767 建议我参考场景文字识别的例子，我看了好久，都一头雾水，里面的代码比较复杂。
我想是按照[book的第三章](http://paddlepaddle.org/docs/develop/book/03.image_classification/index.cn.html)这个种格式做一个可以端到端的验证码识别和车牌识别
我想过把验证码的结果放在label上，但是这个好像不行，label只接受int类型

**Comment by guoshengCS** [comment]
验证码端到端识别不能算是图像分类问题，它需要的label和book中第七、八章类似要是一个标识字符的id的序列可以参考下。

**Comment by yeyupiaoling** [comment]
@guoshengCS 
好的，谢谢。我看看

**Comment by yeyupiaoling** [comment]
@guoshengCS 
我看了一下book中第七、八章，他们跟图像识别差别太大了。完全看不懂，讲到底应该还是[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)比较符合，你知道如何修改成验证码识别么？顺便问个问题：https://github.com/PaddlePaddle/models/issues/619
