### ISSUE TITLE
v2接口 转 fliud接口

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#8025]
v2接口 转 fliud接口：
1.两个接口最大的区别在哪？
2.v2接口的**模型** 转 fliud接口**模型**，有什么注意点？可否提供相关文档地址或者代码地址？
3.v2接口的**模型权重** 转 fliud接口**模型权重**，有什么注意点？可否提供相关文档地址或者代码地址？

**Comment by guoshengCS** [comment]
区别主要是在底层，接口的区别不是特别大，参照v2版本book各个模型的示例https://github.com/PaddlePaddle/book和fluid版本book中各个模型的示例https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/v2/fluid/tests/book 应该就可以了，可以conver多数场景，可以在转换的时候遇到问题的话结合具体问题分析。
