### ISSUE TITLE
关于batch_norm层进行权值绑定的问题

### ISSUE THREAD

**Issue by KaelChen** [PaddlePaddle/Paddle#8034]
我在构造了两个形状相同的网络并对它们进行权值绑定，但是在实际测试的时候发现bn层没有进行绑定。
源代码如下：
```python
layer = paddle.layer.batch_norm(input=layer, batch_norm_type="cudnn_batch_norm", act=paddle.activation.Relu(), use_global_stats=True, param_attr=paddle.attr.Param(name='fc_bn_%d') %i)
```
我总共有两个bn层，理论上进行权值绑定后应该只有两个bn参数
而实际打印出来的参数是这样的：
>fc_bn_0 (1, 1024)
>___batch_norm_0__.w1 (1, 1024)
>___batch_norm_0__.w2 (1, 1024)
>___batch_norm_0__.wbias (1, 1024)
>fc_layer_1 (1024, 1)
>fc_bn_1 (1, 1)
>___batch_norm_1__.w1 (1, 1)
>___batch_norm_1__.w2 (1, 1)
>___batch_norm_1__.wbias (1, 1)
>___batch_norm_2__.w1 (1, 1024)
>___batch_norm_2__.w2 (1, 1024)
>___batch_norm_2__.wbias (1, 1024)
>___batch_norm_3__.w1 (1, 1)
>___batch_norm_3__.w2 (1, 1)
>___batch_norm_3__.wbias (1, 1)

这里貌似bn2和bn3是另一个网络里面的两个bn层，所以两个网络的bn并没有进行权值绑定。是我使用的地方哪里不对吗？我是使用param_attr里面的参数名字来进行参数共享的。

**Comment by guoshengCS** [comment]
目前Paddle中batchnorm包含mean、variance、scale、offset四个参数，分别对应w1、w2、w0、wbias。 另外权值共享需要param name一样。
