### ISSUE TITLE
Reclassify and change of V2 API documentation structure

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8035]
**Task**
Please re-classify the V2 API documentations and make it more clear for reading.
For example:
Image OPs be classified together

p.s. 
分类级别请最多设置到4级,选择这个数目是为了和官网树形展开方式相对应。
如当前：Model Configuration（1）-Evaluator（2）-Classificaition（3）-classification_error（4）

**Project Background**
Polish documentation of PaddlePaddle, enhancing user experience
-----Enhancement Plan: 
Stage 1: https://note.youdao.com/share/?token=83F0AB634A7749E6B4676F823D6EC343&gid=69922175#/
-----Enhancement Schedule: 
https://shimo.im/sheet/VnyT2IKRHjoU1a6i/6HGyl// 

Thank you very much!

**Comment by luotao1** [comment]
Discussed with @qingqing01 @lcy-seso, following v2 APIs should be updated:
- [Dataset](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/data/dataset.html): add wmt16
- [Layers](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html):
  - [factorization-machine](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#factorization-machine): move into [Math Layers](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#permalink-11-math-layers), and remove header "Factorization Machine Layer"
  -  [pad](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#pad): move into [Image Pooling Layer](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#permalink-4-image-pooling-layer), and remove header "Slicing and Joining Layers"
  - [dropout](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#dropout): move into [Math Layers](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#permalink-11-math-layers), and remove header "Miscs"
  - [Activation with learnable parameter](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#activation-with-learnable-parameter): rename to "Activation"
  - [gated_unit](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#gated-unit): move into [Recurrent Layers](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#permalink-6-recurrent-layers)
  - [detection_output](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#detection-output): move into [Cost Layers](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/config/layer.html#permalink-15-cost-layers), and remove header "Detection output Layer"
