### ISSUE TITLE
fluid api的batch_norm

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#8036]
fluid api的batch_norm只能用到图像输入上？有么有类似norm1d的实现？
![image](https://user-images.githubusercontent.com/1027183/35668823-ff019862-076d-11e8-8cb8-a432a8b5ac75.png)

**Comment by guoshengCS** [comment]
这个目前应该是只支持图像的，输出的大小都是channel的数目，目前还没有1d的实现
