### ISSUE TITLE
使用fetch_list输出中间层结果出错

### ISSUE THREAD

**Issue by shiwenguo** [PaddlePaddle/Paddle#8038]
<img width="793" alt="b3359927d1d6e4bd49b218c45" src="https://user-images.githubusercontent.com/34640983/35670860-a9201f34-0774-11e8-8ec0-742ab8d3726d.png">
<img width="686" alt="2d281c2464d4646df895e8849" src="https://user-images.githubusercontent.com/34640983/35670861-a951705c-0774-11e8-9372-9c898e0e825a.png">

如上图所示，在executor的run里面使用fetch_list获取中间层的输出结果出错，fc_out为一个 LoDTensor

**Comment by pkuyym** [comment]
Related to https://github.com/PaddlePaddle/Paddle/issues/8038
