### ISSUE TITLE
关于demo-lstm教程中，pooling层输出元素个数的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#8043]
参考地址：http://www.paddlepaddle.org/docs/develop/book/06.understand_sentiment/index.html

我用的是V1版本，不过看模型结构和V2（即上面的DEMO）配置完全相同。

我的疑问是，（max）pooling层的输出，一共是多少元素呢？
![image](https://user-images.githubusercontent.com/22980558/35674774-bf52676a-0780-11e8-94eb-5ea264607c58.png)

在网络配置中，没有这部分说明：
![image](https://user-images.githubusercontent.com/22980558/35674861-fa9105fc-0780-11e8-9f53-b0defb73169f.png)

从模型结果看，大概512字节可以表达一个参数的数值，那么模型每一层的输出，用总大小/512几乎都等于这一层输出的元素个数，其他所有层用上述方法文件大小和参数个数都对得上：
![image](https://user-images.githubusercontent.com/22980558/35674992-6cac8e72-0781-11e8-9076-29e3414b449d.png)

因为这是个2分类问题，最后一层输出两个元素，而最后一层___fc_layer_3__.w1的文件大小是1040， 除以512正好是2个参数。而上一层pooling的参数大小是4112，也正好是8个输出的大小。

但是通过一个fc和一个lstm pooling出来的输出为什么是8个元素呢？请大侠指教一下，或者哪里错了呢？

**Comment by guoshengCS** [comment]
以___fc_layer_3__.w0为例，减去16个字节的head是4096个字节，每个float四个字节，所以___fc_layer_3__.w0中参数的数目为1024，等于hidden_size(512)*class_dim(2)。fc_last里的pooling就是沿着一个sequence里所有时间步进行pooling，每一个sequence都会变成一个hidden_size的向量，传到fc_layer_3所以___fc_layer_3__.w0参数大小是hidden_size(512)*class_dim(2)。

**Comment by HugoLian** [comment]
@guoshengCS  我测了不同的batch_size，发现确实最后一层矩阵的参数数量，和最后一个fc_layer，即下图中红框与绿框是相关的
![image](https://user-images.githubusercontent.com/22980558/35846045-ef5aac56-0b4f-11e8-83e0-bdff419f16d9.png)
另外，我感觉参数的数量，其实和直接连softmax，即没有下图中黑框的部分是相同的：
![image](https://user-images.githubusercontent.com/22980558/35846092-2668919a-0b50-11e8-8d7b-93232fc9aa13.png)
能不能理解成，如果没有黑框部分，从一个fc_layer一个lstm到最后的softmax输出，公式是这样的：
a1(w1x1 + w2x2 + w3x3 ..) + b1 => class1
a2(w1x1 + w2x2 + w3x3 ..) + b2 => class2
如果加上一个pooling层，这个计算公式变成：
a1( max(w1x1,w2x2,w3x3 ..) ) + b1 => class1
a2( max(w1x1,w2x2,w3x3 ..) ) + b2 => class2

请问这么理解对么？

**Comment by guoshengCS** [comment]
我没有特别抓住想问的点，是否理解pooling层在做什么就可以了，而不需要从现象来推断pooling层在做什么，pooling就是沿着一个sequence（其表示为sequence_length * hidden_size）里所有时间步（sequence_length）进行pooling（对hidden_size中的每一个维度都从sequence_length个值中求出最大的），然后每一个sequence都会变成一个hidden_size的向量。
