### ISSUE TITLE
本地CPU训练，trainner_count与内存、速度的关系 

### ISSUE THREAD

**Issue by memeda** [PaddlePaddle/Paddle#8046]
文档对于`trainer_count`的介绍不多，只在
 [本地训练与预测](http://paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#id2) 里说这个是本地多线程的参数，可以理解这个就是训练线程数吗？

能否估算这个参数对内存（CPU训练下）的影响吗，我现在用4个count，占14G；1个count，用10G；

另外，我并没有发现count=4的速度相比count=1的有什么提升……

**Comment by luotao1** [comment]
请问您是用哪个版本（0.11.0/develop），v1/v2，openblas/mkl?

**Comment by memeda** [comment]
sorry, 用的是 v2；
 至于openblas 还是 mkl，这个没有注意；应该是openblas, MKL应该是需要额外装一些东西的吧，我直接用pip装的（CentOs4.3 ）

**Comment by luotao1** [comment]
MKL也不需要额外装。`paddle version`看下版本把。

**Comment by memeda** [comment]
```xml
PaddlePaddle 0.10.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: OFF
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF
```
哇，原来有这个功能……

**Comment by luotao1** [comment]
可以升级到最新develop版本，会自动设置最优的openblas环境变量。
如果不升级的话，可参考https://github.com/PaddlePaddle/Paddle/issues/7218#issuecomment-355572079

**Comment by memeda** [comment]
好的，非常感谢~
