### ISSUE TITLE
使用PaddlePaddle怎么去做OCR

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8050]
如何使用PaddlePaddle做OCR，[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)算不算是 OCR，使用场景文字识别能否做平常的文字识别。
在场景文字识别这个例子，我有几个问题：https://github.com/PaddlePaddle/models/issues/619 能否答一下

**Comment by wanghaoshuang** [comment]
关于OCR的一个例子：https://github.com/wanghaoshuang/models/tree/ocr_ctc/fluid/ocr

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 
感谢分享，能顺便帮我回答这个问题吗：https://github.com/PaddlePaddle/models/issues/619

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 
这个例子用到了Fluid，这个我还没学，有点难看懂。

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 
你这个OCR的例子什么时候pull request到PaddlePaddle/model上，还有文档什么时候能够完成，没有文档，真看不懂

**Comment by yeyupiaoling** [comment]
@wanghaoshuang 
期待你的例子在https://github.com/PaddlePaddle/models/tree/develop/fluid 出现，还有文档。
