### ISSUE TITLE
文本分类任务，利用已经学习好的embedding进行热启动，是否有Fluid下的示例？

### ISSUE THREAD

**Issue by guru4elephant** [PaddlePaddle/Paddle#8052]
假设想做下面链接里的文本分类问题，word embedding是提前训练好的，如何热启动Fluid中的embedding参数。
https://github.com/PaddlePaddle/Paddle/wiki/Text-Classification-With-CNN-model

**Comment by jaegerstar** [comment]
@guru4elephant 请问是否解决了这个问题
