### ISSUE TITLE
Add Unit Tests for Buffered and Unbuffered Channels

### ISSUE THREAD

**Issue by abhinavarora** [PaddlePaddle/Paddle#8066]
Adding Unit tests

- [x] Simple Test for Buffered Channel
- [x] Simple Test for Unbuffered Channel
- [x] Unbuffered Channel with num_Writers > num_Readers  @kavyasrinet https://github.com/PaddlePaddle/Paddle/pull/8060
- [x] Unbuffered Channel with num_Writers < num_Readers https://github.com/PaddlePaddle/Paddle/pull/8061 @kavyasrinet 
- [x] Test that closing unbuffered channel closes blocked reader and writer threads @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/8067
- [x] Test that closing buffered channel closes blocked reader and writer threads @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/8109
- [x] Add block when channel empty, successfully transfer when there is a send  @kavyasrinet 
 https://github.com/PaddlePaddle/Paddle/pull/8063
- [x] Calling destructor any channel should unblock any threads waiting to write or read from the channel @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/8197
- [x] Check if receive gets a value of zero when channel is closed @kavyasrinet https://github.com/PaddlePaddle/Paddle/pull/8167
- [x] Add Panic unit test for Buffered Channel @kavyasrinet @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/8171 https://github.com/PaddlePaddle/Paddle/pull/8197
- [x] Add Panic unit test for unbuffered channel @abhinavarora https://github.com/PaddlePaddle/Paddle/pull/8197

**Comment by wangkuiyi** [comment]
Thanks to @abhinavarora, @kavyasrinet, and @chengduoZH for completing this lit of unit tests!
