### ISSUE TITLE
dynamic RNN的原理

### ISSUE THREAD

**Issue by zhlxys** [PaddlePaddle/Paddle#8073]
1.图中灰色的RNN节点是真实存在的RNN网络还是不同时刻下的同一RNN？
2.因为RNN在反向传播时，是用的BPTT，如果不用padding，batch的长度不同，反向传播的次数不同的。tensorflow通过bucket的机制让每个batch的长度是一致的。paddle如何处理的？

![image](https://user-images.githubusercontent.com/12048003/35718170-2ec32efc-081e-11e8-8b5c-f99871e75e50.png)

**Comment by luotao1** [comment]
可以参考下[RNN单元实现细节](https://github.com/PaddlePaddle/Paddle/wiki/Paddle%E7%9B%AE%E5%89%8D%E7%9A%84%E5%AE%9E%E7%8E%B0%E7%9A%84%E5%90%84%E4%B8%AA%E6%A8%A1%E5%9D%97%E7%BB%86%E8%8A%82#rnn%E5%8D%95%E5%85%83)。

**Comment by zhlxys** [comment]
多谢。我刚看了文档，还是有点不明白
inputSeq是变长的，而FC Layer是同一个，为何FC Layer可以接受变长的输入了
![image](https://user-images.githubusercontent.com/12048003/35720508-f18d0700-0828-11e8-8a35-d9d8c380b6ea.png)

**Comment by luotao1** [comment]
序列信息对FCLayer的计算是不起作用的，因此无论变长还是定长的输入，FCLayer的前向和反向的计算都是一样的。但需要注意的是，Paddle的FCLayer会把输入的序列信息完整地传给输出。

**Comment by luotao1** [comment]
[RNN 变长输入设计](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/op_documentation/rnn_design.md)也可以参考下。
