### ISSUE TITLE
机器翻译demo是否可以支持定向翻译

### ISSUE THREAD

**Issue by MiraiJ** [PaddlePaddle/Paddle#8074]
https://github.com/PaddlePaddle/book/tree/develop/08.machine_translation
使用机器翻译demo训练，目前是自由翻译，target在len(word_dict)^size的空间内，我这里需要的target是一个有限的结果集，例如只有1000w个句子，如何实现这种定向的翻译呢？

**Comment by wanghaoshuang** [comment]
需要在机器翻译demo的基础上修改下decoder，改变一下beam search的策略，只是简单的建议。
更多方法需要您参阅相关论文。
