### ISSUE TITLE
安装完paddlepaddle运行出错

### ISSUE THREAD

**Issue by liangsj** [PaddlePaddle/Paddle#8077]
我刚刚安装完paddlepaddle 照着教程写了一个demo
      import paddle.v2 as paddle
import sys

paddle.init(use_gpu=False, trainer_count=1)

x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(13))
y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())

probs = paddle.infer(
    output_layer=y_predict,
    parameters=paddle.dataset.uci_housing.model(),
    input=[item for item in paddle.dataset.uci_housing.test()()])

for i in xrange(len(probs)):
    print 'Predicted price: ${:,.2f}'.format(probs[i][0] * 1000)

出现了如下错误，希望能得到解答：

python housing.py
I0202 13:44:01.580305 2602550208 Util.cpp:166] commandline:  --use_gpu=False --trainer_count=1
*** Aborted at 1517550241 (unix time) try "date -d @1517550241" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fff7cadcc81) received by PID 2573 (TID 0x7fff9b1fc3c0) stack trace: ***
    @     0x7fff924eeb3a _sigtramp
    @     0x7fff7cadcc82 CFNumberCreate
    @     0x7fff7e559495 -[NSPlaceholderNumber initWithDouble:]
    @     0x7fff82797554 +[CALayer defaultValueForKey:]
    @     0x7fff82819461 classDescription_locked()
    @     0x7fff828189d6 classDescription_locked()
    @     0x7fff828189d6 classDescription_locked()
    @     0x7fff8281426a classDescription()
    @     0x7fff8281446d CAObject_classInfo
    @     0x7fff82797db4 CA::Layer::class_state()
    @     0x7fff8279a041 -[CALayer init]
    @     0x7fff7a65a484 -[NSView makeBackingLayer]
    @     0x7fff7a65a30b -[NSView(NSInternal) _createLayerAndInitialize]
    @     0x7fff7a65997d -[NSView _doSetWantsLayerYES]
    @     0x7fff7a65960a -[NSView setWantsLayer:]
    @     0x7fff7a666ee6 __49-[NSThemeFrame _floatTitlebarAndToolbarFromInit:]_block_invoke
    @     0x7fff7af9e846 +[NSAnimationContext runAnimationGroup:]
    @     0x7fff7a666b53 -[NSThemeFrame _floatTitlebarAndToolbarFromInit:]
    @     0x7fff7a6646cc -[NSThemeFrame initWithFrame:styleMask:owner:]
    @     0x7fff7a663152 -[NSWindow _commonInitFrame:styleMask:backing:defer:]
    @     0x7fff7a661833 -[NSWindow _initContent:styleMask:backing:defer:contentView:]
    @     0x7fff7a66128f -[NSWindow initWithContentRect:styleMask:backing:defer:]
    @        0x10d69e2a0 -[Window initWithContentRect:styleMask:backing:defer:withManager:]
    @        0x10d6a1787 FigureManager_init
    @        0x10987429f _PyObject_SlotCompare
    @        0x10982d6fb PyObject_Call
    @        0x1098abdbb PyEval_CallObjectWithKeywords
    @        0x10983db9f PyComplex_AsCComplex
    @        0x10982d6fb PyObject_Call
    @        0x1098a878b PyEval_EvalFrameEx
    @        0x1098a59be PyEval_EvalCodeEx
    @        0x10984b4d1 PyFunction_SetClosure
Floating point exception: 8

**Comment by wanghaoshuang** [comment]
麻烦您补充下：
1. matplotlib version
2. matplotlib backend

**Comment by liangsj** [comment]
@wanghaoshuang 
十分感谢您关注我的问题，最近业务需要引入机器学习相关能力，故对paddlepaddle进行调研，如下是补充的信息：
1、matplotlib version： 2.1.2
2、matplotlib backend： u'MacOs'
3、paddle安装方式：pip install paddlepaddle
4、macos
5、Python 2.7.10

**Comment by wanghaoshuang** [comment]
你看你能不能把你matplotlib backend改成 `Agg` ?
```
Python 2.7.10 (default, Jul 14 2015, 19:46:27)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib
>>> matplotlib.use('Agg')
>>> matplotlib.get_backend()
'agg'
```

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
