### ISSUE TITLE
srl示例中字典的使用可能存在问题

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#8079]
在使用srl任务给出的例子的时候（代码的路径为~/Paddle-0.11.0/python/paddle/v2/fluid/tests/book/test_label_semantic_roles.py），发现了一个问题。
就是其使用了chunk_eval层，在看该层相关的实现代码chunk_eval_op时，可以看到其对原始标签字典是有要求的，原始标签字典应组织为如下形式，也就是如下形式：
   B-ORG  0
    I-ORG  1
    B-PER  2
    I-PER  3
    B-LOC  4
    I-LOC  5
    O      6
但是在这个实验中选择的conll05数据集中，下载到本地的target.dict.txt本身并不满足上述格式。
所以这个地方是不是存在一个bug，辛苦确认一下。

**Comment by guoshengCS** [comment]
貌似这里确实是有些问题，因为之前book中的实现没有使用chunk_evaluator所以数据集就没有考虑这个标签字典的组织，如果这里要使用chunk_evaluator可否先自行修改下下载下来的target.dict.txt中的内容。

**Comment by jshower** [comment]
好的，我就是确认一下这个问题。
