### ISSUE TITLE
srl任务的demo脚本如何进行测试

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#8082]
在使用~/Paddle-0.11.0/python/paddle/v2/fluid/tests/book/test_label_semantic_roles.py中，我发现其本身不包含测试评估部分。使用python的api接口，如果我想在测试集上进行评估，该怎么做呢，能否提供示例代码。

**Comment by wanghaoshuang** [comment]
这里有个比较完整的例子：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_recognize_digits.py#L132
