### ISSUE TITLE
Base on 900w samples to train seqToseq on cluster, but run failed as "data part files is less than the mpi nodes you set! "

### ISSUE THREAD

**Issue by zhouyuan0828** [PaddlePaddle/Paddle#809]
job url as below: http://10.73.219.55:8920/fileview.html?path=/home/normandy/maybach/209432/
I have 900w samples , the file size is about 500M. 
In case that running seqToseq will cost so much time, so i want to use more inodes e.g. inode is set as 10 to train model, but the job will run error as "data part files is less than the mpi nodes you set! " 
thanks ~~

**Comment by backyes** [comment]
@zhouyuan0828 

将样本数据划分多份文件，即可。
