### ISSUE TITLE
v2 接口 和 v2.fluid 接口区别

### ISSUE THREAD

**Issue by liuhuiCNN** [PaddlePaddle/Paddle#8090]
ref #8025

1. v2.fluid接口是否可以同时预测2个不同网络？
类似 fc_gan.py

2. v2.fluid 输入数据是否可以不指定尺寸，或者实际输入图像跟所指定尺寸不一样？

3. v2.fluid接口中 roi_pooling 层 跟 v2 接口变化大吗？使用是否一致？

4. v2.fluid save_params 的参数 如何读/写？
    v2.fluid中如何根据权重参数名字得到对应的参数，并给这个参数赋值？（对参数的 读 写 操作）
    v2.fluid中是否可以通过python读写参数？
    v2中参数转成v2.fluid接口中参数，是否需要其他特殊转换？
    请贴出v2.fluid中读写参数的代码地址。

5. tensorflow的权重转成v2.fluid接口的话，对应的tensor是否可以直接转换？
在代码中，v2.fliud如何给指定的tensor赋值？

6. v2.fluid接口中 数据格式和 v2 接口区别？
（1）v2中数据格式是 N C H W         kernel参数格式是 Cout Cin H W
tensorflow中数据格式是 N H W C    kernel参数格式是 H W Cin Cout
v2.fluid中跟v2区别？

**Comment by wanghaoshuang** [comment]
>1. v2.fluid接口是否可以同时预测2个不同网络？
类似 fc_gan.py

可以

>2. v2.fluid 输入数据是否可以不指定尺寸，或者实际输入图像跟所指定尺寸不一样？

data layer必须指定shape, 实际输入图像跟所指定尺寸可以不一样

3. v2.fluid接口中 roi_pooling 层 跟 v2 接口变化大吗？使用是否一致？

> 4. v2.fluid save_params 的参数格式跟 v2 具体有什么区别？
若将v2接口的权重转成fliud，需要哪些操作？

对于每个parameter(权重？), v2.fluid 会将其保存为一个文件，文件名是parameter的名称。

> 5. tensorflow的权重转成v2.fluid接口的话，对应的tensor是否可以直接转换？
在代码中，v2.fliud如何给指定的tensor赋值？

v2.fliud如何给指定的tensor赋值方法如下：
```
import numpy as np
import paddle.v2.fluid.core as core
place = core.CPUPlace()
my_tensor = core.tensor()
np_data = np.random.uniform(0.1, 1, [3, 512, 512])
my_tensor.set(np_data, place)
```
所以，理论上是可以手动把tensorflow的tensor转过来的。

> 6. v2.fluid接口中 数据格式和 v2 接口区别？
（1）v2中数据格式是 N C H W         kernel参数格式是 Cout Cin H W
tensorflow中数据格式是 N H W C    kernel参数格式是 H W Cin Cout
v2.fluid中跟v2区别？

v2.fluid 用[data_layout](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/data_layout.h#L25)来表示图像纬度次序，你可以指定tensor的data_layout。

**Comment by liuhuiCNN** [comment]
@wanghaoshuang 
3. fluid接口中 python wrapper roi_pooling接口是否很简单？
4. 把V2接口的tar解压，名字改成fluid对应的名字，权重参数是不是就相等于转换好了？
5.fluid中如何制定参数名字（找了一会没找到特别的参数？）？如果在网络中根据参数名字找到对应参数并赋值？
