### ISSUE TITLE
使用fluid api将keras模型转为paddle模型时碰到的问题

### ISSUE THREAD

**Issue by zhglzh** [PaddlePaddle/Paddle#8092]
1 序列的Masking，能否支持？
2 batch_norm 1d，用于对序列做norm，能否支持？
3 dynamic_lstm act不支持hard_sigmoid，能否支持？
4 dynamic_lstm 不支持dropout，该如何实现？
5 fc layer如何支持l1或l2正则？
6 计算cost时，如何实现类似 y_true = tf.where(tf.equal(y_true, self._default_behavior), y_pred, y_true)的操作？
7 fluid api train出的模型，是否可以使用CAPI加载使用？

**Comment by zhglzh** [comment]
4 fluid.layers.dropout
5 paddle.fluid.param_attr.ParamAttr regularizer= regularizer .L2Decay

**Comment by zhglzh** [comment]
7 https://github.com/luotao1/fluid_inference_example/blob/master/example.cc

**Comment by pkuyym** [comment]
@zhglzh 
1 序列的Masking，能否支持？
不是很清楚需求，序列做Masking是mask掉整个序列？可以从data layer构造mask矩阵，然后用点乘的方式进行mask

2.batch_norm 1d，用于对序列做norm，能否支持？
有例子对序列做batch norm，可参考https://github.com/PaddlePaddle/DeepSpeech/blob/develop/model_utils/network.py#L133，看是否符合需求

3. dynamic_lstm act不支持hard_sigmoid，能否支持？
这个是新feature需求，目前暂没有计划支持

6. 计算cost时，如何实现类似 y_true = tf.where(tf.equal(y_true, self._default_behavior), y_pred, y_true)的操作？
这个看起来是schedule sampling？v2版有complex layer，具体使用参照 https://github.com/PaddlePaddle/models/tree/develop/scheduled_sampling，如果不是这个意思，那v2版应该没有直接的实现
