### ISSUE TITLE
fluid 可以在网络（或者说模型）间共享参数吗？

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#8096]
我做的模型的输入大小是不确定的，而 fluid要求data layer的尺寸固定。比如说我定义一个[30, 50]的data layer，但测试数据有可能有[3, 5]。所以我需要将测试数据按大小分类输入不同输入层来进行计算。所以请问fluid可以在不同网络间共享参数吗？如果可以的话希望可以给我一个例子作为参考

**Comment by ranqiu92** [comment]
可以试下把要进行参数共享的相应layer的参数名设置成相同的
```python
fc1 = fluid.layers.fc(
    input=input1,
    param_attr=ParamAttr(name='fc.w'),
    bias_attr=ParamAttr(name='fc.b'))

fc2 = fluid.layers.fc(
    input=input2,
    param_attr=ParamAttr(name='fc.w'),
    bias_attr=ParamAttr(name='fc.b'))
```

**Comment by zzhzz** [comment]
@ranqiu92 那在训练的时候的怎么设置呢？这样一来我相当于有3个cost layer，是同时需要构建3个optimizer吗

**Comment by ranqiu92** [comment]
你的模型是要实现什么？输入具体是什么？

**Comment by zzhzz** [comment]
@ranqiu92 我要实现的是一个多叉树分类识别的功能。输入的是不同的树的邻接表。使用类似CNN的方式进行识别。由于树的大小不一致，所以需要桉树大小分类输入。

**Comment by ranqiu92** [comment]
额，没有完全理解你所说的。  如果是 变长序列输入的话，可以参考 https://github.com/dzhwinter/benchmark/blob/master/fluid/machine_translation.py#L219

**Comment by zzhzz** [comment]
@ranqiu92 说的简单些就是识别图像，但图像的大小尺寸不固定。

**Comment by ranqiu92** [comment]
一般情况下，图像识别会在数据预处理的时候 将数据处理成相同维数。图像识别可以参考 https://github.com/dzhwinter/benchmark/blob/master/fluid/resnet50.py

Paddle V2的话，对于变长输入处理可以参考  https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/model/index_cn.rst#6-paddlepaddle%E6%98%AF%E5%90%A6%E6%94%AF%E6%8C%81%E7%BB%B4%E6%95%B0%E5%8F%AF%E5%8F%98%E7%9A%84%E6%95%B0%E6%8D%AE%E8%BE%93%E5%85%A5
