### ISSUE TITLE
场景文字识别例子中的一些问题和错误日志

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8099]
在[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)这个例子中，更book中的例子有里很大的不同，我看了很久也看不懂所以然，路过的大神能否解答以下一些问题：
1. 例子中很多都用到了`click`这个东西，这个有什么用，我猜是命令行里的参数，不知道是不是。
2. 这个例子用用到的神经网络模型是什么，跟传统的图像分类不一样了。
3. 如何修改这个例子才可以使用CPU运行
4. 下面的训练输出日志正常吗？Eval后面没东西的
```
Pass 73, batch 0, Samples 0, Cost 10.854516, Eval {}
Pass 73, batch 50, Samples 500, Cost 0.071530, Eval {}
Test 73, Cost 12.956735, Eval {}
Pass 74, batch 0, Samples 0, Cost 15.511139, Eval {}
Pass 74, batch 50, Samples 500, Cost 0.054424, Eval {}
Test 74, Cost 12.839751, Eval {}
```

谢谢各位

**Comment by ranqiu92** [comment]
click是一个python包，你可以自己查一下了解详细用途。
然后因为这个用到了warp_ctc，所以只能在GPU下运行。

**Comment by yeyupiaoling** [comment]
@ranqiu92 
那它用到的神经模型有名字吗？
输出的日子是否正常的？
我训练的700多pass，预测结果还是不是很理想

**Comment by ranqiu92** [comment]
你可以使用nohup，这个是断开服务器，服务器也可以继续运行程序。

**Comment by yeyupiaoling** [comment]
@ranqiu92  
好的，谢谢
>在训练2000多个pass之后，预测的结果没有一个是对的，这个正常吗？完全是原来的例子，没有改任何的代码

这个问题呢

**Comment by ranqiu92** [comment]
你是在GPU下运行的吗？

**Comment by yeyupiaoling** [comment]
@ranqiu92 
对的，CPU用不了。使用的是百度的GPU集群

**Comment by yeyupiaoling** [comment]
* 使用的神经网络是先使用CNN提取特征，然后将RNN的输出映射到字符分布。
* 用于预测因为使用不到`CTC`，所以可以使用CPU预测
```python
# 使用扭曲CTC来计算CTC任务的成本。
        if not self.is_infer:
            self.cost = paddle.layer.warp_ctc(
                input=self.output,
                label=self.label,
                size=self.num_classes + 1,
                norm_by_times=True,
                blank=self.num_classes)

            self.eval = paddle.evaluator.ctc_error(input=self.output, label=self.label)
```
