### ISSUE TITLE
除了场景文字识别，还有其他的方法实现验证码端到端的识别码

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8106]
* 在[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)这个例子中，它只能使用GPU来训练，我的电脑没有GPU，运行不了
* 有什么办法可以使用CPU来实现验证码端到端的识别

**Comment by ranqiu92** [comment]
不知道 这个是否对你有用
https://github.com/PaddlePaddle/book/tree/develop/02.recognize_digits

**Comment by yeyupiaoling** [comment]
@ranqiu92 
这个方法我在验证码切割识别的时候用了，现在想做端到端识别的。

**Comment by yeyupiaoling** [comment]
可以使用https://github.com/wanghaoshuang/models/tree/ocr_ctc/fluid/ocr 来做端到端的预测
