### ISSUE TITLE
paddle卷积问题：比如图片，paddle定义数据输入的时候是长与宽的乘积，一维的向量，可是图片是二维卷积，这个一维向量不知道怎么弄，paddle后面是怎么处理的呢？。而在tensorflow中是直接定义二维的输入的

### ISSUE THREAD

**Issue by MEYOUTH** [PaddlePaddle/Paddle#8108]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by zzhzz** [comment]
你使用的是fluid还是paddle v2

**Comment by MEYOUTH** [comment]
使用的是paddle v2

**Comment by MEYOUTH** [comment]
@zzhzz ，我之前用tensorflow做的CNN现在不知道如何转成paddle，正卡在这个地方

**Comment by yeyupiaoling** [comment]
@MEYOUTH 
我不太明白你的问题描述，如果是三通道的彩色图，就是通道数 \* 宽 \* 高
如：https://github.com/PaddlePaddle/models/blob/develop/image_classification/train.py#L15

**Comment by MEYOUTH** [comment]
应该是这样吧，卷积paddle对图片是正方形处理，长方形后面要加height=xx，width=xx

**Comment by yeyupiaoling** [comment]
@MEYOUTH 
可以参考这个https://github.com/PaddlePaddle/models/blob/develop/scene_text_recognition/network_conf.py#L33-L37

**Comment by MEYOUTH** [comment]
是的！，就是这一句，长方形要指定高和宽
       # Image input as a float vector.
        self.image = layer.data(
            name='image',
            type=paddle.data_type.dense_vector(self.image_vector_size),
            height=self.shape[0],
width=self.shape[1])
