### ISSUE TITLE
Make it easier to share parameters

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#811]
Currently, the mechanism for sharing parameters across different parts of a model is to set the parameter name in ParamAttr. However, for some compound layers defined in trainer_config_helpers/network.py, there are too many parameters and it's very inconvenient to explicitly indicating the name for each of them. For example, simple_lstm has 3 parameters and bidirectional_lstm has 6 parameters.

One possible way to do this is adding an argument para_name_prefix to these functions, so that the user only need to set para_name_prefix and do not set the name for each parameters.

**Comment by gongweibao** [comment]
Close it because it's not a problem in fluid.
