### ISSUE TITLE
怎样在训练过程中获取 layer.data 的output，或者直接获取layer.data

### ISSUE THREAD

**Issue by wuliangradi** [PaddlePaddle/Paddle#8110]
https://github.com/PaddlePaddle/Paddle/blob/29603cf39a8d61475dee013b23b6aa589d75887f/doc/faq/local/index_cn.rst#layeroutput
文档讲了获取 如何在训练过程中获得某一个layer的output
但是当获取 data类型的layer总是出错

**Comment by peterzhang2029** [comment]
你的输入类型是什么呢？ 如果是integer_value_sequence类型的话，应该从event.gm.getLayerOutputs("name")["name"]["id"]这个key取到

**Comment by wuliangradi** [comment]
@peterzhang2029 恰好是sparse_float_vector和sparse_binary_vector这两个类型，可以取吗

**Comment by peterzhang2029** [comment]
打印一下 event.gm.getLayerOutputs("name")["name"] 看下是否有对应的值。
