### ISSUE TITLE
Implement ArgMax and ArgMin operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8121]
See ONNX [ArgMax](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ArgMax) and [ArgMin](https://github.com/onnx/onnx/blob/master/docs/Operators.md#ArgMin) for more detail.

**Comment by m3ngyang** [comment]
please assign the issue to me. (mengyang02)

**Comment by lcy-seso** [comment]
Thank you for taking this.

**Comment by m3ngyang** [comment]
Can we implement Argmax/Argmin as subclasses of `ReduceOp`, just like `class ReduceMaxOpMaker : public ReduceOpMaker`

**Comment by guoshengCS** [comment]
@m3ngyang Good idea. Unified interface and code style is preferred. Some points should be paid attentions and I am not sure yet. The data type of the output tensor of `Argmax/Argmin` should be integer while the other `ReduceOp` uses float type, thus the `ReduceKernel` may need be changed to support different data types for input and output. Additionally,  I am not sure how Eigen Tensor (which the `ReduceKernel` depends on currently )  supports `Argmax/Argmin` and the [interface](https://github.com/RLovelett/eigen/blob/d608d9f3f577118981acbdd40da9dcf6b514668a/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h#L646) seems different with the other reduce functions like [`sum/mean/maximum`](https://github.com/RLovelett/eigen/blob/d608d9f3f577118981acbdd40da9dcf6b514668a/unsupported/Eigen/CXX11/src/Tensor/TensorBase.h#L532)  and maybe you can [search the test case](https://github.com/RLovelett/eigen/search?utf8=✓&q=argmax&type=) for the usage and check if `Argmax/Argmin` can use the same `ReduceKernel` as the other `ReduceOp`.

**Comment by m3ngyang** [comment]
I think the most implementation of `ArgMax/ArgMin` and `ReduceOp` is repeated, excepts the points you mentioned above.
First, the types of input and output. For `ReduceOp`, output has the same data type with input. But for `ArgMax/ArgMin`, the type of output is always an interger. We add a typename for output in the template of `ReduceKernel` to adapt to different conditions.
Second, the inferfaces are different. Maybe we need an abstract ReduceKernel for the share component of `ReduceOp` and `ArgMax/ArgMin`.
And [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/argmax_op.h#L52) is an example of using argmin in eigen.

**Comment by luotao1** [comment]
We have already [arg_min_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/arg_min_op.cc) and [arg_max_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/arg_max_op.cc)
