### ISSUE TITLE
Implement ceil and floor operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8122]
See ONNX [ceil](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Ceil) and [floor](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Floor) for more detail.

**Comment by liuzhiwei** [comment]
认领。百度 ID：liuzhiwei03@baidu.com

**Comment by lcy-seso** [comment]
Thank you for taking this.

**Comment by lcy-seso** [comment]
I close this issue first because @liuzhiwei pointed out that these two operators have already implemented and merged into Fluid.
