### ISSUE TITLE
Implement InstanceNormalization operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8126]
See ONNX [InstanceNormalization](https://github.com/onnx/onnx/blob/master/docs/Operators.md#InstanceNormalization) for more detail.

**Comment by lgone2000** [comment]
我做这个， liuguoyi

**Comment by lcy-seso** [comment]
Thank you for taking this.

**Comment by lgone2000** [comment]
@lcy-seso  看了一下[pytorch的实现](http://pytorch.org/docs/0.3.1/_modules/torch/nn/modules/instancenorm.html)，它把InstanceNormalization 看做batchnorm的一个特殊情况，在python层次实现了。我们是不是也可以不用单独实现op，直接在python层次封装一下？

**Comment by lcy-seso** [comment]
是这样的。可以在Python端直接拼接或者对已有的一些operator进行封装，对用户展现行为不同的接口。例如 `layers.l2_normalize`  https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L2265 没有对应的C++实现，而是在Python端拼接封装基础Operator来实现。

**Comment by lcy-seso** [comment]
针对在python端wrap出来的layers，单测可以选择两种方式：
1.  针对简单情况，一个layers对应一个或者几个 op，计算逻辑简单，主要用户测试添加的wrapper是否能够被正确调用 ： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_layers.py
1. 计算逻辑相对复杂，可以为组合op单独编写op，测试前向和反向（需要手算反向的梯度，假设每一个基础op都已经通关了反向梯度检测，是否为反向组合Op添加反向现在没有强制） : https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/unittests/test_normalization_wrapper.py
