### ISSUE TITLE
Impelement RandomNormalLike, RandomUniform and RandomUniformLike op.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8127]
See ONNX [RandomNormalLike](https://github.com/onnx/onnx/blob/master/docs/Operators.md#RandomNormalLike), [RandomUniform](https://github.com/onnx/onnx/blob/master/docs/Operators.md#randomuniform) and [RandomUniformLike](https://github.com/onnx/onnx/blob/master/docs/Operators.md#randomuniformlike) for more detail.

**Comment by xymyeah** [comment]
please assign the issue to me

**Comment by lcy-seso** [comment]
Thank you for taking this.

**Comment by xymyeah** [comment]
这几个好像已经被别的同学完成了，
对应的代码为
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/

gaussian_random_op.cc
gaussian_random_op.cu
gaussian_random_batch_size_like_op.cc


uniform_random_batch_size_like_op.cc
uniform_random_op.cc
uniform_random_op.cu

**Comment by lcy-seso** [comment]
I close this issue for these two operators have already merged into Fluid. Thank you for pointing this out.
