### ISSUE TITLE
Implement ReduceProd operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8129]
See ONNX [ReduceProd](https://github.com/onnx/onnx/blob/master/docs/Operators.md#reduceprod) for more detail.

**Comment by zhouhanqing** [comment]
please assign the issue to me（zhouhanqing）

**Comment by lcy-seso** [comment]
Thank you for taking this work!

Some of the reduce op is already implemented. You can this the merged reduced_op for reference. https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/reduce_op.h

Please try to add ReduceProd into the reduce_op.
