### ISSUE TITLE
Impelment squeeze and unsqueeze operator.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8131]
See ONNX [squeeze](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Squeeze) and [unsqueeze](https://github.com/onnx/onnx/blob/master/docs/Operators.md#Unsqueeze) operator for more detail.

**Comment by shiwenguo** [comment]
Apply for this issue.

**Comment by lcy-seso** [comment]
Thank you for taking this task.
