### ISSUE TITLE
paddle.init(use_gpu=False, trainer_count=1)时kernel崩溃

### ISSUE THREAD

**Issue by gamingjoy** [PaddlePaddle/Paddle#8133]
我是mac用anaconda新建了一个python2.7的paddlepadddle环境。
按照教程入门教程，在jupyter notebook上面执行第二步paddle.init时
```
import paddle.v2 as paddle
# Initialize PaddlePaddle.
paddle.init(use_gpu=False, trainer_count=1)
```
jupyter提示kernel崩溃，请问是什么情况，如何解决？

**Comment by QiJune** [comment]
kernel崩溃可能的原因是python依赖库的问题，请问你是怎么安装的？
另外，推荐使用docker环境来使用paddle

**Comment by gamingjoy** [comment]
@QiJune 我是pip install
自动安装了一些依赖。请问怎么能查找是什么依赖出错了呢？
另外，只能在python2.7环境下吗？（这次我是conda python 2.7的）

**Comment by liuhuiCNN** [comment]
建议先命令行运行，如果出现问题会报错。没有问题在使用jupyter notebook

**Comment by cdliheng** [comment]
我也遇到同样的问题，安装镜像都正常，没问题。
用命令运行快速快速入门的代码
docker run --rm -v ~/workspace:/workspace paddlepaddle/paddle:latest python /workspace/housing.py
不报错，也没任何输出，回车后就直接到下一个提示符了。。。。 @liuhuiCNN

**Comment by yeyupiaoling** [comment]
@cdliheng 
请确认您的电脑是否支持AVX指令集，查看命令如下：
```
if cat /proc/cpuinfo | grep -i avx; then echo Yes; else echo No; fi
```
