### ISSUE TITLE
我们想跑paddlepaddle官网上的图片分类案例，用到VGG或者Resnet模型，需要什么配置的电脑呢？

### ISSUE THREAD

**Issue by zpyzlsd** [PaddlePaddle/Paddle#8143]
我的笔记本装了虚拟机分了1GB内存，是不是跑不起来，推荐用什么样的配置比较好，需要GPU吗？我们主要是想跑下paddle paddle官网的图像分类的案例。谢谢

**Comment by QiJune** [comment]
1GB的内存是比较小的，建议8G以上。
CPU训练会比较慢，有GPU会快很多。
