### ISSUE TITLE
自行build centos paddle的image，在执行paddle version时出现错误，请帮忙看看，谢谢

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#8154]
基于http://paddleci.ngrok.io/viewLog.html?buildId=27156&tab=artifacts&buildTypeId=Manylinux1_CpuAvxCp27cp27mu安装的paddle
在执行paddle version时出现错误

/usr/local/bin/paddle: line 158: [: 0.10.0: binary operator expected
  File "<stdin>", line 3
    if LooseVersion("0.10.0
                          ^
SyntaxError: EOL while scanning string literal

**Comment by luotao1** [comment]
和 #7476 同样的问题，不过不影响打印`paddle version`的内容

**Comment by xymyeah** [comment]
那意思是说这种情况不影响使用是吧？

**Comment by luotao1** [comment]
对的，不影响使用。但我们也会尽快修复这个问题的。

**Comment by guoshengCS** [comment]
先行close，如有需要请reopen。
