### ISSUE TITLE
activation.Relu6() is not supported, but mobilenetV2 need, how can i do?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#8156]

**Comment by QiJune** [comment]
Now, we do not support relu6 activation. 
I have add a feature request label on it. We will add it soon.

**Comment by yeyupiaoling** [comment]
@youngstu hi,The Fluid version has been supported.
http://www.paddlepaddle.org/documentation/api/en/0.14.0/layers.html#relu6
