### ISSUE TITLE
Incorporate gtest and protobuf

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#816]
This is a subtask of https://github.com/PaddlePaddle/Paddle/issues/792

**Comment by reyoung** [comment]
@wangkuiyi https://github.com/reyoung/bazel_playground/blob/master/WORKSPACE 

glog, gflags, protobuf are incorporated in this repo.

**Comment by wangkuiyi** [comment]
@reyoung Cool. Given your demo for glog/gflags/protobuf and mine at  https://github.com/wangkuiyi/learn-bazel, I created this PR https://github.com/PaddlePaddle/Paddle/pull/818.   It is not yet finished, but we can discuss there.
