### ISSUE TITLE
Add test cases to test for as per the PR: #8164

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#8173]
As per the Axioms and facts mentioned in #8164 
We should explicitly check for the following:
- [ ] Receiver should block on an empty channel. : https://github.com/PaddlePaddle/Paddle/pull/8166
- [ ] Send to a nil channel should block -- As of now, one proposal is to implement a special kind of Unbuffered channel that is a nil channel and check for that.
- [ ] Receive from a nil channel blocks
- [ ] Closing a nil channel also causes a run-time panic.
- [ ] Send to a closed channel panics . (The panic behavior could be : throw an exception or return the `false` boolean) :  https://github.com/PaddlePaddle/Paddle/pull/8171
- [ ] Receive from closed channel returns zero value after channel is emptied and otherwise the values in the buffer :  https://github.com/PaddlePaddle/Paddle/pull/8167

**Comment by chengduoZH** [comment]
@kavyasrinet  I am curious about, in Fluid, what's the case with a nil channel?
