### ISSUE TITLE
Please delete "Operators" in API tree

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8177]
![image](https://user-images.githubusercontent.com/35982308/35839246-5a6bd2a2-0b2a-11e8-9606-8635adfbfcf0.png)
![image](https://user-images.githubusercontent.com/35982308/35839750-1ed153fe-0b2d-11e8-9786-c30439dc933c.png)

Plz delete "Operators" in the API tree because we've already had "Fluid".

“Operators” was put here because at first there was not a "Fluid" menu. After "Fluid" menu was added, "Operators" could be deleted.

Thank you so much!

**Comment by jetfuel** [comment]
@shanyi15 @luotao1 Will "Fluid" section cover "Operator" completely? We are about to delete "Operator", but we find there are technical details in "Operator" not yet in "Fluid".

**Comment by luotao1** [comment]
> Will "Fluid" section cover "Operator" completely

The "Fluild" section will not have "Operator" too. Thus, you can delete "Operator".

**Comment by jetfuel** [comment]
@luotao1 Since "Fluid" section will not have "Operator", shouldn't we keep "Operator" for reference?

**Comment by luotao1** [comment]
Yes, we will not keep "Operator" for reference later, it's duplicated with "fluid".
