### ISSUE TITLE
在模型库每个模型文档的Readme.md中告知用户该模型适用的版本

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8183]
当前，PaddlePaddle官网的模型库中没有定版本，只有dev版，其中有些模型适用于v2，有些适用于Fluid，给用户的阅读和使用带来了一定的困难。
经讨论，我们制定了解决方案：在每篇模型文档的Readme中告诉用户该模型适用于哪个版本，即使将来模型库代码从v2转为Fluid，我们也可以通过修改Readme的方式及时告知用户代码版本的变化。

谢谢！

**Comment by lcy-seso** [comment]
收到。下周之内统一修改完毕。

**Comment by yeyupiaoling** [comment]
下载都过年了，年后吧。[嘻嘻]
