### ISSUE TITLE
Both code and doc of Fluid API are located in V2 API's menu

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8188]
注：需要征集大家的意见，请用“向上手势”表示赞成，用“向下手势”表示反对。
Please note that: use "GestureUp" to show agreement and "GestureDown" to show disagreement.

______________________________________________________________________________________________________

Now Fluid API doc is located in[ V2 API doc menu](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/api/v2)

![image](https://user-images.githubusercontent.com/35982308/35852806-cc3a8e28-0b66-11e8-92ea-4d8e4dd5137b.png)

and Fluid API code is located in  [V2 API code menu ](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/v2) (According to @luotao1 's comment below)

![111](https://user-images.githubusercontent.com/35982308/35856217-49347a84-0b70-11e8-8489-84d4d27d92c9.PNG)

Also, Fluid API name contains "V2", making users confused
[For example](http://www.paddlepaddle.org/docs/develop/documentation/zh/api/v2/fluid/layers.html), paddle.v2.fluid.layers.xxxx

![image](https://user-images.githubusercontent.com/35982308/35853034-7114e024-0b67-11e8-8050-74f7aaba4e8e.png)

**Suggestion:**

We could move Fluid API doc/code out of V2 API doc/code, in github/PaddlePaddle/Paddle/tree/develop/doc/api/, paddle/python/paddle/v2 **or** paddlepaddle.org/api.

**Advantages and necessity:**

1. Improving users' experience
2. Being suitable for the enhanced paddlepaddle.org in the future: in the new version of paddlepaddle.org, Fluid API docs will be separated from V2 API docs.

**Comment by luotao1** [comment]
Should we move Fluid API code out of V2 API code?
![default](https://user-images.githubusercontent.com/6836917/35854532-899342e0-0b6b-11e8-83d9-670bbbff23dd.PNG)

**Comment by shanyi15** [comment]
I think @luotao1 's suggestion makes sense.

**Comment by wangkuiyi** [comment]
Also, we want to move `/paddle/{framework,memory,operators}` into `/paddle/fluid//{framework,memory,operators}`.

**Comment by luotao1** [comment]
@wangkuiyi  should we move `/paddle/{framework, memory, operator, inference, platform, string, optimizer, pybind}` all into `/paddle/fluid/{}`?
