### ISSUE TITLE
python api接口设置线程数

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#8194]
你好，我在使用python/paddle/v2/fluid/tests/book下的例子时，没有在脚本中看到关于线程数的选项，但是用top命令看，其cpu占用率超过100%，是默认是多线程的吗，如何设置运行时的线程数？能给个例子吗？

**Comment by reyoung** [comment]
> 你好，我在使用python/paddle/v2/fluid/tests/book下的例子时，没有在脚本中看到关于线程数的选项，但是用top命令看，其cpu占用率超过100%，是默认是多线程的吗，如何设置运行时的线程数？能给个例子吗？

默认不是多线程的。多线程需要使用Parallel.Do。文档正在完善。
