### ISSUE TITLE
NCCL compilation and linking version not match

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#8195]
Currently, paddle is compiled with nccl1.3 by pulling its source code from https://github.com/NVIDIA/nccl. During the runtime, it is linked to nccl2. This would result in failure such as `unhandled cuda error`.

The CI doesn't fail because some CI machine only have one GPU so the nccl test is skipped.

**Comment by dzhwinter** [comment]
Now our base docker image is CUDA8. And we use dso to load cudnn, NCCL. 
NCCL1.3 is ok but NCCL2 will failed.  It seems that we need to upgrade our CUDA Driver to 9.1 if we want to use NCCL2.1.4. 

Here is the debug info
```txt
91: I0207 07:09:26.591536 47744 dynamic_loader.cc:67] Try to find library: libnccl.so from default system path.
91: NCCL version 2.1.4+cuda9.1
91:
91: idgsim-gpu-001:47744:47744 [0] init.cu:674 WARN Cuda failure 'CUDA driver version is insufficient for CUDA runtime version'
91: unknown file: Failure
91: C++ exception with description "unhandled cuda error at [/paddle/Paddle/paddle/platform/nccl_test.cu:34]
91: PaddlePaddle Call Stacks:
91: 0             0x436a89p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 761
91: 1             0x42f4ebp paddle::platform::NCCL_init_Test::TestBody() + 635
91: 2             0x4ed023p void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) + 67
91: 3             0x4e2e0ap testing::Test::Run() + 186
91: 4             0x4e2f58p testing::TestInfo::Run() + 280
91: 5             0x4e3065p testing::TestCase::Run() + 229
91: 6             0x4e5507p testing::internal::UnitTestImpl::RunAllTests() + 583
91: 7             0x4e5839p testing::UnitTest::Run() + 89
91: 8             0x42c2abp main + 75
```

**Comment by tonyyang-svail** [comment]
@dzhwinter CUDA driver version and CUDA version are different things. If you type `nvidia-smi`, on the upper right you can see the driver version on your machine.

The current driver version on CI is 390.25, and it passed all the NCCL test (though failed on some other tests)
https://paddleci.ngrok.io/viewLog.html?buildId=27474&buildTypeId=Paddle_PrCi&tab=buildLog
