### ISSUE TITLE
Support all the padding mode in conv_op and pool_op.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8203]
Pad mode should be made an attribute for conv_op and pool_op so that user can configure these two ops to support SAME_UPPER, SAME_LOWER or VALID padding mode. The user interface can follow ONNX's standard.

The computation logic of convolution and pooling does not need to change, but how to compute the output size should be carefully modified and enhanced.

**Comment by liuzhiwei** [comment]
认领。百度ID：liuzhiwei03

**Comment by lcy-seso** [comment]
Thank you for taking this work!
