### ISSUE TITLE
Fluid 如何实现分布式训练？

### ISSUE THREAD

**Issue by QingshuChen** [PaddlePaddle/Paddle#8223]
Fluid已经把分布式训练的功能实现了，请问Fluid如何跑一个分布式训练？有什么参考文档？另外，如果想用MPI集群去跑，需要改哪些配置？

**Comment by JiayiFeng** [comment]
Fluid的分布式训练目前仍在开发中。预计2月底会发布第一个版本。

**Comment by typhoonzero** [comment]
您好，Fluid目前分布式执行方式可以参考：

- [英文文档](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/fluid_cluster_train_en.md)
- [book分布式demo](https://github.com/PaddlePaddle/Paddle/tree/develop/python/paddle/v2/fluid/tests/book_distribute)
- [benchmark](https://github.com/PaddlePaddle/Paddle/tree/develop/benchmark/cluster/vgg16)

中文文档会逐步补充并添加从 www.paddlepaddle.org 的访问入口。

如果是希望用内部的MPI集群执行，可以Hi沟通，寻求解决方法。

PaddlePaddle希望可以支持OpenMPI更新的版本已获得使用Message Passing Framework在通用计算集群和支持GPU direct集群获得更好的性能，此项功能的支持目前处在前期调研阶段。

**Comment by chengduoZH** [comment]
Close this inactive issue, please feel free to reopen it.
