### ISSUE TITLE
What is the format of Fluid's saved models

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#8234]
We need to load parameters trained by another platform. So we hope to know the format of Fluid's saved model.

Can anyone help to give us some guidance? Is there any doc or example? or which part of code I can read? Thanks for the help.

Chinese translation:

我们希望加载其它平台训练的参数作为热启动，然后继续训练。请问目前Fluid模型的存储格式是什么样呢？是否有示例或者应该直接参考哪一段代码呢？

**Comment by lcy-seso** [comment]
Answer from @Xreki 

简单来说，每个权重其实就是一个LoDTensor，那么重点就是LoDTensor是怎么保存的，以什么顺序保存什么信息，主要调用https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.cc#L234 这个函数。但不同框架之间的模型转换，重点不是保存格式，而是大家怎么使用的。比如tf有可能用的是nhwc，而我们用的是hchw。这些细节需要进一步确认。

**Comment by qingqing01** [comment]
parameter的存储也可以参考文档： https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/model_format.md#implementation
