### ISSUE TITLE
when trainning model, i use gpu and when test model, i don't use gpu, the cost jump very high. Why?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#8235]

**Comment by JiayiFeng** [comment]
Would you please add more detail? For example your network config and how you save and load model.

**Comment by youngstu** [comment]
**similar to network config**: https://github.com/PaddlePaddle/Mobile/blob/develop/models/mobilenet_ssd_pascal/mobilenet_ssd_pascal.py

save and load model by command line. (eg. --init_model_path)

**Comment by youngstu** [comment]
trainning model using gpu come to a good level and test model using gpu is also better, but when i modiy use_gpu=0, it results in a worst result. Why? 

when i turn to my friends, they all say that it is a bug of paddle.

**Comment by JiayiFeng** [comment]
The issue you describe did exist in an old version of Paddle, but it should have been fixed. So please update Paddle to the newest version and try again. If the problem persists, would you please show us how to reproduce it? It will be quite beneficial if you can offer the following information:
1. The python scripts you are using to train and test. You can paste them here or push them to your own GitHub repo.
2. The steps how we can reproduce the problem with given python scripts.
