### ISSUE TITLE
[semantic_role_labeling]的train时，使用GPU时，提示不支持GPU

### ISSUE THREAD

**Issue by beckett1124** [PaddlePaddle/Paddle#824]
[semantic_role_labeling]的train时，使用GPU时，提示不支持GPU。

root@aaef91eb6282:~/paddle/demo/semantic_role_labeling# ./train.sh 
I1212 05:39:14.360787 13452 Util.cpp:158] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=./db_lstm.py --use_gpu=True --log_period=10 --trainer_count=1 --show_parameter_stats_period=10 --save_dir=./output --num_passes=50 --average_test_period=1000 --init_model_path=./data --load_missing_parameter_strategy=rand --test_all_data_in_one_period=1 
I1212 05:39:16.981266 13452 Util.cpp:132] Calling runInitFunctions
I1212 05:39:16.981845 13452 Util.cpp:146] Call runInitFunctions done.
Traceback (most recent call last):
  File "<string>", line 13, in <module>
NameError: name 'GLOG_logtostderr' is not defined
[INFO 2016-12-12 05:39:17,271 networks.py:1466] The input order is [word_data, ctx_n2_data, ctx_n1_data, ctx_0_data, ctx_p1_data, ctx_p2_data, verb_data, mark_data, target]
[INFO 2016-12-12 05:39:17,271 networks.py:1472] The output order is [crf]
I1212 05:39:17.300215 13452 Trainer.cpp:180] trainer mode: Normal
I1212 05:39:17.621610 13452 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
I1212 05:39:17.654880 13452 PyDataProvider2.cpp:243] loading dataprovider dataprovider::process
W1212 05:39:17.655321 13452 Trainer.cpp:637] --test_all_data_in_one_period was deprecated, since we will always do test on all test set 
I1212 05:39:17.655371 13452 GradientMachine.cpp:124] Loading parameters from ./data
I1212 05:39:17.655391 13452 Parameter.cpp:377] missing parameters [./data/vemb] while loading model.
I1212 05:39:17.655400 13452 Parameter.cpp:387] vemb missing, set to random.
I1212 05:39:17.664822 13452 Parameter.cpp:377] missing parameters [./data/_word_ctx-in_embedding.w0] while loading model.
I1212 05:39:17.664839 13452 Parameter.cpp:387] _word_ctx-in_embedding.w0 missing, set to random.
I1212 05:39:17.671900 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w0] while loading model.
I1212 05:39:17.671927 13452 Parameter.cpp:387] _hidden0.w0 missing, set to random.
I1212 05:39:17.673307 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w1] while loading model.
I1212 05:39:17.673322 13452 Parameter.cpp:387] _hidden0.w1 missing, set to random.
I1212 05:39:17.674618 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w2] while loading model.
I1212 05:39:17.674631 13452 Parameter.cpp:387] _hidden0.w2 missing, set to random.
I1212 05:39:17.675930 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w3] while loading model.
I1212 05:39:17.675945 13452 Parameter.cpp:387] _hidden0.w3 missing, set to random.
I1212 05:39:17.677237 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w4] while loading model.
I1212 05:39:17.677249 13452 Parameter.cpp:387] _hidden0.w4 missing, set to random.
I1212 05:39:17.678539 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w5] while loading model.
I1212 05:39:17.678552 13452 Parameter.cpp:387] _hidden0.w5 missing, set to random.
I1212 05:39:17.679847 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w6] while loading model.
I1212 05:39:17.679859 13452 Parameter.cpp:387] _hidden0.w6 missing, set to random.
I1212 05:39:17.681155 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.w7] while loading model.
I1212 05:39:17.681169 13452 Parameter.cpp:387] _hidden0.w7 missing, set to random.
I1212 05:39:17.682849 13452 Parameter.cpp:377] missing parameters [./data/_hidden0.wbias] while loading model.
I1212 05:39:17.682865 13452 Parameter.cpp:387] _hidden0.wbias missing, set to random.
I1212 05:39:17.684195 13452 Parameter.cpp:377] missing parameters [./data/_lstm0.w0] while loading model.
I1212 05:39:17.684211 13452 Parameter.cpp:387] _lstm0.w0 missing, set to random.
I1212 05:39:17.690449 13452 Parameter.cpp:377] missing parameters [./data/_lstm0.wbias] while loading model.
I1212 05:39:17.690465 13452 Parameter.cpp:387] _lstm0.wbias missing, set to random.
I1212 05:39:17.690670 13452 Parameter.cpp:377] missing parameters [./data/_hidden1.w0] while loading model.
I1212 05:39:17.690685 13452 Parameter.cpp:387] _hidden1.w0 missing, set to random.
I1212 05:39:17.711928 13452 Parameter.cpp:377] missing parameters [./data/_hidden1.w1] while loading model.
I1212 05:39:17.711944 13452 Parameter.cpp:387] _hidden1.w1 missing, set to random.
I1212 05:39:17.717007 13452 Parameter.cpp:377] missing parameters [./data/_hidden1.wbias] while loading model.
I1212 05:39:17.717020 13452 Parameter.cpp:387] _hidden1.wbias missing, set to random.
I1212 05:39:17.717145 13452 Parameter.cpp:377] missing parameters [./data/_lstm1.w0] while loading model.
I1212 05:39:17.717156 13452 Parameter.cpp:387] _lstm1.w0 missing, set to random.
I1212 05:39:17.722203 13452 Parameter.cpp:377] missing parameters [./data/_lstm1.wbias] while loading model.
I1212 05:39:17.722215 13452 Parameter.cpp:387] _lstm1.wbias missing, set to random.
I1212 05:39:17.722817 13452 Parameter.cpp:377] missing parameters [./data/_hidden2.w0] while loading model.
I1212 05:39:17.722829 13452 Parameter.cpp:387] _hidden2.w0 missing, set to random.
I1212 05:39:17.742910 13452 Parameter.cpp:377] missing parameters [./data/_hidden2.w1] while loading model.
I1212 05:39:17.742923 13452 Parameter.cpp:387] _hidden2.w1 missing, set to random.
I1212 05:39:17.747975 13452 Parameter.cpp:377] missing parameters [./data/_hidden2.wbias] while loading model.
I1212 05:39:17.747988 13452 Parameter.cpp:387] _hidden2.wbias missing, set to random.
I1212 05:39:17.748111 13452 Parameter.cpp:377] missing parameters [./data/_lstm2.w0] while loading model.
I1212 05:39:17.748122 13452 Parameter.cpp:387] _lstm2.w0 missing, set to random.
I1212 05:39:17.753178 13452 Parameter.cpp:377] missing parameters [./data/_lstm2.wbias] while loading model.
I1212 05:39:17.753191 13452 Parameter.cpp:387] _lstm2.wbias missing, set to random.
I1212 05:39:17.753602 13452 Parameter.cpp:377] missing parameters [./data/_hidden3.w0] while loading model.
I1212 05:39:17.753614 13452 Parameter.cpp:387] _hidden3.w0 missing, set to random.
I1212 05:39:17.773663 13452 Parameter.cpp:377] missing parameters [./data/_hidden3.w1] while loading model.
I1212 05:39:17.773677 13452 Parameter.cpp:387] _hidden3.w1 missing, set to random.
I1212 05:39:17.778733 13452 Parameter.cpp:377] missing parameters [./data/_hidden3.wbias] while loading model.
I1212 05:39:17.778745 13452 Parameter.cpp:387] _hidden3.wbias missing, set to random.
I1212 05:39:17.779038 13452 Parameter.cpp:377] missing parameters [./data/_lstm3.w0] while loading model.
I1212 05:39:17.779050 13452 Parameter.cpp:387] _lstm3.w0 missing, set to random.
I1212 05:39:17.784099 13452 Parameter.cpp:377] missing parameters [./data/_lstm3.wbias] while loading model.
I1212 05:39:17.784112 13452 Parameter.cpp:387] _lstm3.wbias missing, set to random.
I1212 05:39:17.784404 13452 Parameter.cpp:377] missing parameters [./data/_hidden4.w0] while loading model.
I1212 05:39:17.784415 13452 Parameter.cpp:387] _hidden4.w0 missing, set to random.
I1212 05:39:17.804471 13452 Parameter.cpp:377] missing parameters [./data/_hidden4.w1] while loading model.
I1212 05:39:17.804486 13452 Parameter.cpp:387] _hidden4.w1 missing, set to random.
I1212 05:39:17.809542 13452 Parameter.cpp:377] missing parameters [./data/_hidden4.wbias] while loading model.
I1212 05:39:17.809556 13452 Parameter.cpp:387] _hidden4.wbias missing, set to random.
I1212 05:39:17.809769 13452 Parameter.cpp:377] missing parameters [./data/_lstm4.w0] while loading model.
I1212 05:39:17.809782 13452 Parameter.cpp:387] _lstm4.w0 missing, set to random.
I1212 05:39:17.814838 13452 Parameter.cpp:377] missing parameters [./data/_lstm4.wbias] while loading model.
I1212 05:39:17.814851 13452 Parameter.cpp:387] _lstm4.wbias missing, set to random.
I1212 05:39:17.815124 13452 Parameter.cpp:377] missing parameters [./data/_hidden5.w0] while loading model.
I1212 05:39:17.815135 13452 Parameter.cpp:387] _hidden5.w0 missing, set to random.
I1212 05:39:17.835216 13452 Parameter.cpp:377] missing parameters [./data/_hidden5.w1] while loading model.
I1212 05:39:17.835229 13452 Parameter.cpp:387] _hidden5.w1 missing, set to random.
I1212 05:39:17.840277 13452 Parameter.cpp:377] missing parameters [./data/_hidden5.wbias] while loading model.
I1212 05:39:17.840291 13452 Parameter.cpp:387] _hidden5.wbias missing, set to random.
I1212 05:39:17.840550 13452 Parameter.cpp:377] missing parameters [./data/_lstm5.w0] while loading model.
I1212 05:39:17.840562 13452 Parameter.cpp:387] _lstm5.w0 missing, set to random.
I1212 05:39:17.845614 13452 Parameter.cpp:377] missing parameters [./data/_lstm5.wbias] while loading model.
I1212 05:39:17.845628 13452 Parameter.cpp:387] _lstm5.wbias missing, set to random.
I1212 05:39:17.847009 13452 Parameter.cpp:377] missing parameters [./data/_hidden6.w0] while loading model.
I1212 05:39:17.847021 13452 Parameter.cpp:387] _hidden6.w0 missing, set to random.
I1212 05:39:17.867884 13452 Parameter.cpp:377] missing parameters [./data/_hidden6.w1] while loading model.
I1212 05:39:17.867907 13452 Parameter.cpp:387] _hidden6.w1 missing, set to random.
I1212 05:39:17.872958 13452 Parameter.cpp:377] missing parameters [./data/_hidden6.wbias] while loading model.
I1212 05:39:17.872972 13452 Parameter.cpp:387] _hidden6.wbias missing, set to random.
I1212 05:39:17.873556 13452 Parameter.cpp:377] missing parameters [./data/_lstm6.w0] while loading model.
I1212 05:39:17.873569 13452 Parameter.cpp:387] _lstm6.w0 missing, set to random.
I1212 05:39:17.878623 13452 Parameter.cpp:377] missing parameters [./data/_lstm6.wbias] while loading model.
I1212 05:39:17.878635 13452 Parameter.cpp:387] _lstm6.wbias missing, set to random.
I1212 05:39:17.878989 13452 Parameter.cpp:377] missing parameters [./data/_hidden7.w0] while loading model.
I1212 05:39:17.879001 13452 Parameter.cpp:387] _hidden7.w0 missing, set to random.
I1212 05:39:17.899056 13452 Parameter.cpp:377] missing parameters [./data/_hidden7.w1] while loading model.
I1212 05:39:17.899070 13452 Parameter.cpp:387] _hidden7.w1 missing, set to random.
I1212 05:39:17.904109 13452 Parameter.cpp:377] missing parameters [./data/_hidden7.wbias] while loading model.
I1212 05:39:17.904122 13452 Parameter.cpp:387] _hidden7.wbias missing, set to random.
I1212 05:39:17.905550 13452 Parameter.cpp:377] missing parameters [./data/_lstm7.w0] while loading model.
I1212 05:39:17.905562 13452 Parameter.cpp:387] _lstm7.w0 missing, set to random.
I1212 05:39:17.910604 13452 Parameter.cpp:377] missing parameters [./data/_lstm7.wbias] while loading model.
I1212 05:39:17.910619 13452 Parameter.cpp:387] _lstm7.wbias missing, set to random.
I1212 05:39:17.912001 13452 Parameter.cpp:377] missing parameters [./data/_output.w0] while loading model.
I1212 05:39:17.912014 13452 Parameter.cpp:387] _output.w0 missing, set to random.
I1212 05:39:17.916373 13452 Parameter.cpp:377] missing parameters [./data/_output.w1] while loading model.
I1212 05:39:17.916388 13452 Parameter.cpp:387] _output.w1 missing, set to random.
I1212 05:39:17.917551 13452 Parameter.cpp:377] missing parameters [./data/_output.wbias] while loading model.
I1212 05:39:17.917564 13452 Parameter.cpp:387] _output.wbias missing, set to random.
I1212 05:39:17.918787 13452 Parameter.cpp:377] missing parameters [./data/crfw] while loading model.
I1212 05:39:17.918799 13452 Parameter.cpp:387] crfw missing, set to random.
I1212 05:39:18.249344 13486 ThreadLocal.cpp:38] thread use undeterministic rand seed:13487
F1212 05:39:18.282557 13452 CRFLayer.cpp:56] Check failed: !useGpu_ GPU is not supported
*** Check failure stack trace: ***
    @     0x7fcc5fe42daa  (unknown)
    @     0x7fcc5fe42ce4  (unknown)
    @     0x7fcc5fe426e6  (unknown)
    @     0x7fcc5fe45687  (unknown)
    @           0x58d297  paddle::CRFLayer::forward()
    @           0x58938e  paddle::NeuralNetwork::forward()
    @           0x56d153  paddle::GradientMachine::forwardBackward()
    @           0x6b11bc  paddle::TrainerInternal::forwardBackwardBatch()
    @           0x6b15d4  paddle::TrainerInternal::trainOneBatch()
    @           0x6ac540  paddle::Trainer::trainOneDataBatch()
    @           0x6aef2f  paddle::Trainer::trainOnePass()
    @           0x6b02b0  paddle::Trainer::train()
    @           0x534987  main
    @     0x7fcc5f04ef45  (unknown)
    @           0x54a762  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 111: 13452 Aborted                 ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
develop版本已经标明 `crf_layer ` 不支持GPU： https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/semantic_role_labeling/index_en.md

```
--use_gpu=false: use CPU to train, set true, if you install GPU version of PaddlePaddle and want to use GPU to train, until now crf_layer do not support GPU
```

故该问题暂且不需要fix。
