### ISSUE TITLE
git wiki 中的链接无法访问

### ISSUE THREAD

**Issue by water1981** [PaddlePaddle/Paddle#825]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/text_generation/text_generation.md

这个链接无法正常的访问。

**Comment by water1981** [comment]
引用的链接是：https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/embedding_model/index_en.md

**Comment by luotao1** [comment]
#806 已经fix这个问题了，待review和merge中
