### ISSUE TITLE
multibox_loss_layer() appears not to support the position(x,y) num setting of the 'input_loc' default 2. I want to add some feature points except for the box positions in input_loc.

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#8255]

**Comment by youngstu** [comment]
And it also don't support loss setting. **For example, for one class, i don't want to compute the loss of box possition(e.g. multi-task).**

How can I modify the C++ code to support it Temporarily.

**Comment by will-am** [comment]
The C++ code for multibox_loss_layer is here: https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MultiBoxLossLayer.cpp

**Comment by guoshengCS** [comment]
Close this issue temporarily, and please feel free to reopen it.
