### ISSUE TITLE
SGD参数is_local的真实含义？

### ISSUE THREAD

**Issue by jinyongbo128** [PaddlePaddle/Paddle#8256]
问题：
同样的数据集，唯一区别在于SGD参数，is_local=False/True
在分布式训练时候，auc（is_local=True） = 0.6， auc（is_local=False） = 0.52这个结果和参数共享效果更好相背了。请问下SGD参数is_local的作用是什么？是仅仅实现不同node的参数共享吗？

假设分布式训练的时候，设置成is_local=True，有几个问题请教？
1. 这样是不是意味着就是每个node单独训练自己的parameter？
2. 如果每个node都有自己的独占parameter，那最终output哪个模型作为最终的模型？
3. 每个node的train_data数量其实就是total_train_data/node_num，如果是这样，那是不是等同于我用total_train_data/node_num这样的数据量进行单机训练？
4. 模型输入定义了sparse_binary_interge,  layer也使用了sparse_update。。这种情况下use_remote_sparse一定要用吗？ use_remote_sparse说是使用稀疏参数服务器，这个什么场景使用？是否和其他参数有联动？

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/8144  https://github.com/PaddlePaddle/Paddle/issues/8138

**Comment by typhoonzero** [comment]
分布式训练，是为了用更多的机器的计算能力，在更短的时间能训练更多的数据。这几个类似的issue，看起来像是v2的一个bug，需要深入debug下。

**Comment by jinyongbo128** [comment]
目前还不清楚分布式使用同步更新方式，为何auc还不如is_local开启方式，
折中的方案，我是否可以使用异步更新机制，--async_lagged_ratio_min 文档上有这个参数，可以控制异步机制，我看默认是1.0，如果设置0.8，就是等同于80%的node算完后，更新参数吗？

**Comment by typhoonzero** [comment]
Async-SGD的文档是需要更新下，V1/V2使用 Async-SGD的方法如下：

https://github.com/PaddlePaddle/Paddle/issues/7108#issuecomment-354717422

这个问题我感觉是个bug，得排查下，可以麻烦贴下复现的方法和步骤么。

**Comment by wuliangradi** [comment]
@typhoonzero 为什么在 https://github.com/PaddlePaddle/Paddle/issues/7923 里你说应该设置成is_local=False呢。我尝试设置成false会报fetal。

**Comment by typhoonzero** [comment]
@wuliangradi 可以贴下详细的报错信息。
