### ISSUE TITLE
capi如何用paddle加载多个模型进行预测

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#8260]
capi的使用问题：
我的程序需要在同一个进程里加载两个模型，这两个模型分别对不同类型的文件进行预测。举例：一个图片识别模型，一个声音识别模型。
现在遇到的问题是，首先paddle不能初始化两次，如果初始化一次倒是可以跑，但是最后free的时候会报错。
我看到多线程的例子，但是多线程的例子里模型加载是在主线程里完成的，还是一个模型用多个线程预测。
多个模型的正确使用姿势是怎么样的？
谢谢

**Comment by will-am** [comment]
试试每个模型的参数都指定名字，然后名字不要重复

**Comment by thomaslwang** [comment]
就是用不同的名字做的，最后destroy gradient machine的时候会hang住。

**Comment by thomaslwang** [comment]
0.11.0

**Comment by will-am** [comment]
那应该是只能加载一个模型了

**Comment by will-am** [comment]
可以参考这个issue中的解决办法：https://github.com/PaddlePaddle/Paddle/issues/7950

**Comment by thomaslwang** [comment]
是呀，我是capi。工程里使用多个模型是强需求。tf不知道支不支持

**Comment by Xreki** [comment]
> 就是用不同的名字做的，最后destroy gradient machine的时候会hang住。

capi应该可以同时支持多个模型的预测。不看destroy gradient machine，你能得到正确的预测结果吗？

**Comment by thomaslwang** [comment]
基本正确，但是不知道会不会和单独模型有差别。不是说有不可见的全局变量么？

**Comment by wangkuiyi** [comment]
按照 micro-service 的原则，如果要加载两个模型，是不是应该启动两个进程，每个进程加载一个模型呢？

**Comment by thomaslwang** [comment]
实际应用的场景，多个模型非常常见，比如同时预测语音和图片，或者预测多个语音模型。多个进程需要进程间通信，开销大。micro-service适用的场景是什么？

**Comment by thomaslwang** [comment]
咱们不应该僵化在某个原则，从使用者角度看这是强需求。
