### ISSUE TITLE
Can paddle support a new demand that it is a multi-task includding classification, bounding boxs, feature points.

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#8264]

**Comment by youngstu** [comment]
Maybe it extend the multibox_loss_layer() and detection_output_layer() to support feature points prediction. ( It is best to set the loss ratio of different tasks  and can choose other task loss is computed according by classification)

**Mtcnn network  and modified ssd have the demand.**

**Comment by qingqing01** [comment]
@youngstu Thanks for your proposal. We are doing detection on our new framework Fluid now. We will take your demand into consideration.  It is fine if you give the paper link.

**Comment by youngstu** [comment]
【MTCNN】
CSDN: http://blog.csdn.net/shuzfan/article/details/52668935
https://arxiv.org/abs/1604.02878v1

**Comment by youngstu** [comment]
【MTCN】 for reference
http://blog.csdn.net/shuzfan/article/details/52668935
http://blog.csdn.net/amds123/article/details/69568495
https://kpzhang93.github.io/MTCNN_face_detection_alignment/

Additionaly, we want to extend ssd algorithm and add key points task in it.

**Comment by jacquesqiao** [comment]
support in https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/detection
