### ISSUE TITLE
Format problem of documentation

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8274]
![image](https://user-images.githubusercontent.com/35982308/35966316-74723248-0cf8-11e8-9904-cd55a2571393.png)

There exists space beside the main body @进阶使用-分布式训练-[环境准备](http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/cluster/preparations_cn.html)

Please polish it, thank you!

**Comment by luotao1** [comment]
English article has the same format problem @HOWTO-Distributed Training-[Preparations](http://www.paddlepaddle.org/docs/develop/documentation/en/howto/cluster/preparations_en.html).

**Comment by shanyi15** [comment]
P.s. 这篇文档中文的paddle version是0.10.0，英文的是0.10.0rc，应该都改成0.11.0

**Comment by shanyi15** [comment]
您好，此issue在近一个月内暂无更新，我们将于今天内关闭。若在关闭后您仍需跟进提问，可重新开启此问题，我们将在24小时内回复您。因关闭带来的不便我们深表歉意，请您谅解~感谢您对PaddlePaddle的支持! 
 Hello, this issue has not been updated in the past month. We will close it today for the sake of other user‘s experience. If you still need to follow up on this question after closing, please feel free to reopen it. In that case, we will get back to you within 24 hours. We apologize for the inconvenience caused by the closure and thank you so much for your support of PaddlePaddle Group!
