### ISSUE TITLE
paddle使用docker编译报找不到PYTHON_LIBRARY 的错误

### ISSUE THREAD

**Issue by jshower** [PaddlePaddle/Paddle#8281]
你好，我在使用以下步骤：
docker pull paddlepaddle/paddle:latest-dev
git clone https://github.com/PaddlePaddle/Paddle.git
cd Paddle
docker run -it -v $PWD:/paddle -e "WITH_GPU=OFF" -e "WITH_TESTING=OFF" paddlepaddle/paddle_manylinux_devel:cuda8.0_cudnn5 bash -x /paddle/paddle/scripts/docker/build.sh
出错，出错结果如下，我应该如何解决？
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "paddle_pserver_main" in directory /paddle/paddle/pserver
    linked by target "paddle_trainer" in directory /paddle/paddle/trainer
    linked by target "paddle_merge_model" in directory /paddle/paddle/trainer
    linked by target "_swig_paddle" in directory /paddle/paddle/api
```

**Comment by will-am** [comment]
docker编译paddle请参考这个步骤：http://www.paddlepaddle.org/docs/develop/documentation/en/build_and_install/build_en.html

**Comment by jshower** [comment]
使用http://www.paddlepaddle.org/docs/develop/documentation/en/build_and_install/build_en.html
这个教程编译时，会出现一些库不能下载的问题，应该是国内不能访问的原因，所以获取了编好的docker
镜像后，按照下面的教程操作，
http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/build_from_source_cn.html
就会出现上面的问题，有能解决的方案吗？

**Comment by will-am** [comment]
下面的文档比较老了，建议还是根据上面的文档编译，我这里目前可以下载，你再想想办法下载

**Comment by pzelazko** [comment]
I have the same issue

**Comment by gongweibao** [comment]
I have the same issue.
