### ISSUE TITLE
Is it necessary checking the input 'numel' in compare op?

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/Paddle#8296]
`compare op` should support for inputs with different dims. `Input(Y)` can be broadcasted to the shape as `Input(X)`. So it is not necessary to checking `numel` of  `Input(X)` and `Input(Y)`.
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/operators/compare_op.cc#L61

**Comment by jacquesqiao** [comment]
the current compare wise op is elementwise
