### ISSUE TITLE
What should do to add MKLDNN kernel

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#8305]
### Base class that need to implement:

- `MKLDNNLoDTensor` derived from [LoDTensor](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/lod_tensor.h#L123). in formal PaddlePaddle.
Like [MKLDNNMatrix.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/math/MKLDNNMatrix.h) for v2
 

- `MKLDNNKernelBase` derived from [KernelBase](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/operator.h#L336). Like [MKLDNNLayer.h](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/MKLDNNLayer.h#L35) in formal PaddlePaddle for v2
- Tensor transform functions used to tranform between LodTensor and MKLDNNKernel

### Steps to add new kernel

Take `pool_cudnn_op` as example:

1. add `pool_cudnn_op.cu.cc`
2. implement `PoolCUDNNOpKernel`
3. register kernel with library type `CUDNN`

```
REGISTER_OP_KERNEL(pool2d, CUDNN, ::paddle::platform::CUDAPlace,
                   ops::PoolCUDNNOpKernel<float>,
                   ops::PoolCUDNNOpKernel<double>);
```

If we want to add `pool_mkldnn` kernel, the step should be:

1. add new file `pool_mkldnn_op.cc`
2. implement PoolMKLDNNOpKernel
3. register PoolMKLDNNOpKernel with library `MKLDNN `

```
REGISTER_OP_KERNEL(pool2d, MKLDNN, ::paddle::platform::MKLDNNPlace,
                   ops::PoolMKLDNNOpKernel<float>,
                   ops::PoolMKLDNNOpKernel<double>);
```

**Comment by mrysztow** [comment]
Can we move the instruction to some wiki page, link it here and close the issue?

**Comment by luotao1** [comment]
Your suggestion sounds nice. The related documentation is [new_op_kernel_en.md](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/new_op_kernel_en.md). Can you move the instruction to it?

**Comment by mrysztow** [comment]
@pzelazko-intel can you validate the instruction above and if it is actual, insert it into the file pointed by @luotao1 ?

**Comment by pzelazko-intel** [comment]
@jacquesqiao For MKLDNN kernels we actually derive from `framework::OpKernel` directly. Please take a look at #8879.

Does class representing MKLDNN matrix have to derive from `LoDTensor`? Couldn't it derive from `Tensor`?

**Comment by luotao1** [comment]
> Does class representing MKLDNN matrix have to derive from LoDTensor? Couldn't it derive from Tensor?

It should derive from LoDTensor. The reason is that （sorry, we don't have a documentation about it）:

All the input and output of ops are LoDTensor in fact. Ops should deliver the LoD information one by one, if one of them is not LoDTensor, the delivery is broken.  For examples, A->B->C, if B doesn't use LoDTensor, C would not get the LoD information. (https://github.com/PaddlePaddle/Paddle/issues/3717)
