### ISSUE TITLE
仿照场景文字识别做车牌识别，训练的cost已经很小了，为什么测试的cost还是很大

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8308]
我仿照[场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition)这个例子写了一个车牌识别的，数据集有250多张，经过差不多500个pass，训练的cost已经很小了，为什么Test的cost还是很大

```text
Pass 478, batch 0, Samples 0, Cost 0.009310, Eval {}
Test 478, Cost 31.028336, Eval {}
Pass 479, batch 0, Samples 0, Cost 0.240099, Eval {}
Test 479, Cost 30.694710, Eval {}
Pass 480, batch 0, Samples 0, Cost 0.013670, Eval {}
Test 480, Cost 30.789079, Eval {}
```

**Comment by jacquesqiao** [comment]
从 train的data set中取出一些做test看一下cost呢？

**Comment by yeyupiaoling** [comment]
@jacquesqiao 
我试试，有结果再跟你反馈

**Comment by yeyupiaoling** [comment]
@jacquesqiao 
Test的cost跟train的cost很接近了，都比较低了。这是为什么呢？难道只有训练过才能识别吗？

**Comment by JiayiFeng** [comment]
训练集cost小而测试集cost大，说明过拟合了。
解决方案是增加训练数据，增加正则项，或者干脆降低网络的复杂度。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
官方给出的优化方法是没有其他参数的，加上正则可以吗？
```
optimizer = paddle.optimizer.Momentum(momentum=0)
```
修改网络那更加复杂，数据集也有点小

**Comment by jacquesqiao** [comment]
看起来确实是过拟合了，在 @JiayiFeng 给出的方案之外，还可以想办法通过已有的数据增加数据集，比如把图片随机截取一部分，或者旋转，作为新的训练数据

**Comment by yeyupiaoling** [comment]
>把图片随机截取一部分，或者旋转，作为新的训练数据

这是个好办法，好的，谢谢您们
