### ISSUE TITLE
汉化工作--cluster_train

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#831]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/cluster_train_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/usage/cluster/)

文件命名为 cluster_train_cn.md

**Comment by livc** [comment]
认领。

**Comment by luotao1** [comment]
@livc 请注意该文档地址已更新，内容不变。
