### ISSUE TITLE
用docker源码编译paddle失败

### ISSUE THREAD

**Issue by alexqdh** [PaddlePaddle/Paddle#8318]
执行步骤"安装开发工具到 Docker image 里"的时候遇到报错，看着也不像是被墙了，请帮忙看下，谢谢
```
cd paddle; docker build -t paddle:dev .
```
[教程链接](http://paddlepaddle.org/docs/develop/documentation/zh/build_and_install/build_cn.html)

报错信息:
```
Successfully built docopt PyYAML MarkupSafe
Installing collected packages: docopt, PyYAML, alabaster, MarkupSafe, Jinja2, snowballstemmer, pytz, babel, imagesize, setuptools, Pygments, typing, docutils, certifi, chardet, idna, urllib3, requests, six, sphinxcontrib-websupport, sphinx
  Found existing installation: pytz 2014.10
    Uninstalling pytz-2014.10:
      Successfully uninstalled pytz-2014.10
  Found existing installation: setuptools 20.7.0
    Uninstalling setuptools-20.7.0:
      Successfully uninstalled setuptools-20.7.0
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_set.py", line 795, in install
    requirement.commit_uninstall()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_install.py", line 767, in commit_uninstall
    self.uninstalled.commit()
  File "/usr/local/lib/python2.7/dist-packages/pip/req/req_uninstall.py", line 142, in commit
    rmtree(self.save_dir)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 49, in wrapped_f
    return Retrying(*dargs, **dkw).call(f, *args, **kw)
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 212, in call
    raise attempt.get()
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 247, in get
    six.reraise(self.value[0], self.value[1], self.value[2])
  File "/usr/local/lib/python2.7/dist-packages/pip/_vendor/retrying.py", line 200, in call
    attempt = Attempt(fn(*args, **kwargs), attempt_number, False)
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 102, in rmtree
    onerror=rmtree_errorhandler)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "/usr/lib/python2.7/shutil.py", line 252, in rmtree
    onerror(os.remove, fullname, sys.exc_info())
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 110, in rmtree_errorhandler
    if os.stat(path).st_mode & stat.S_IREAD:
OSError: [Errno 2] No such file or directory: '/tmp/pip-HxcE09-uninstall/usr/bin/easy_install'
The command '/bin/sh -c pip install --upgrade pip &&     pip install -U wheel &&     pip install -U docopt PyYAML sphinx &&     pip install -U sphinx-rtd-theme==0.1.9 recommonmark' returned a non-zero code: 2
```

**Comment by jacquesqiao** [comment]
看起来是 pip install的时候失败了，感觉和网络关系比较大，可以重试一下

**Comment by alexqdh** [comment]
Dockerfile文件中的改动点
(1)Dockerfile中下载go的时候防止被墙把googleapis域名替换成了国内的链接
(2)pip使用的时候源换成了阿里的

具体改动内容如下:
 # Install Go and glide
-RUN wget -qO- https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz | \
+RUN wget -qO- https://dl.gocn.io/golang/1.8.1/go1.8.1.linux-amd64.tar.gz | \
-RUN pip install --upgrade pip && \
-    pip install -U wheel && \
-    pip install -U docopt PyYAML sphinx && \
-    pip install -U sphinx-rtd-theme==0.1.9 recommonmark
+RUN pip install --upgrade --force-reinstall pip -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
+    pip install -U wheel -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
+    pip install -U docopt PyYAML sphinx -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
+    pip install -U sphinx-rtd-theme==0.1.9 recommonmark -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

-RUN pip install pre-commit 'ipython==5.3.0' && \
-    pip install 'ipykernel==4.6.0' 'jupyter==1.0.0' && \
-    pip install opencv-python
+RUN pip install pre-commit 'ipython==5.3.0' -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
+    pip install 'ipykernel==4.6.0' 'jupyter==1.0.0' -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com && \
+    pip install opencv-python -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

 COPY ./python/requirements.txt /root/
-RUN pip install -r /root/requirements.txt
+RUN pip install -r /root/requirements.txt -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

 # To fix https://github.com/PaddlePaddle/Paddle/issues/1954, we use
 # the solution in https://urllib3.readthedocs.io/en/latest/user-guide.html#ssl-py2
 RUN apt-get install -y libssl-dev libffi-dev
-RUN pip install certifi urllib3[secure]
+RUN pip install certifi urllib3[secure] -i http://mirrors.aliyun.com/pypi/simple/ --trusted-host mirrors.aliyun.com

**Comment by jacquesqiao** [comment]
The reason and fix method is in this issue https://github.com/PaddlePaddle/Paddle/issues/8331
