### ISSUE TITLE
汉化工作--RNN Configuration

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#832]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/deep_model/rnn/rnn_en.rst)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/deep_model/rnn/)

文件命名为 rnn_cn.md

**Comment by livc** [comment]
认领。
