### ISSUE TITLE
paddle有没有自动调参的功能

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#8322]
对于很多应用，训练样本和测试样本都固定了，需要调的参数挺多，目前业界也有不少自动调参方法了，这样可以节省很多时间。
请问，目前有这种功能吗，如果没有有计划加上吗？

**Comment by luotao1** [comment]
目前没有这个功能，fluid以后会加上，但不在近期计划中。

**Comment by guoshengCS** [comment]
已提供答复且较久未更新，这里先行close，如有需要还请reopen。
