### ISSUE TITLE
汉化工作--new_layer

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#833]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/new_layer_en.rst)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/)

文件命名为 new_layer_cn.rst

**Comment by zzsu** [comment]
认领

**Comment by luotao1** [comment]
@zzsu 请注意下该文档地址已更新，内容未变。
