### ISSUE TITLE
[Intel] CLA (Contributor License Agreement)

### ISSUE THREAD

**Issue by mrysztow** [PaddlePaddle/Paddle#8335]
Does PaddlePaddle require signing of any Contributor License Agreement, like other companies working on OS code do (Tensor flow example is first paragraph of [https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md))?
I'm looking trhough the PaddlePaddle repo (especially at [https://github.com/PaddlePaddle/Paddle/blob/develop/CONTRIBUTING.md](https://github.com/PaddlePaddle/Paddle/blob/develop/CONTRIBUTING.md)) and cannot find any information about CLA

**Comment by wangkuiyi** [comment]
Hello @mrysztow , Yes, you are right. PaddlePaddle requires contributors to sign a CLA.  We used to do this offline. Let me set up Github to allow contributors to do it online. 

Thanks for the reminder!

**Comment by luotao1** [comment]
Hello @mrysztow, we have already set up CLA online, see [CONTRIBUTING.md](https://github.com/PaddlePaddle/Paddle/blob/develop/CONTRIBUTING.md) and https://github.com/PaddlePaddle/Paddle/pull/8353#issuecomment-364627842 for example.

**Comment by mrysztow** [comment]
Great. How can we sign the CLA online (contributing.md mentions only agreeing with the CLA, but CLA itself explicite requires a signature)?

**Comment by luotao1** [comment]
When you create a PR, it will remind that signing your cla on cla-assistant. (see https://github.com/PaddlePaddle/Paddle/pull/8353#issuecomment-364627842)
![image](https://user-images.githubusercontent.com/6836917/36093768-a3acd6ae-1026-11e8-9120-acb684ff6272.png)

**Comment by mrysztow** [comment]
Thank you very much for this detailed description. I think we can close the issue as resolved one
