### ISSUE TITLE
汉化工作--gpu_profiling

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#834]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/optimization/gpu_profiling_en.rst)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/optimization/)

文件命名为 gpu_profiling_cn.rst

**Comment by yebie** [comment]
认领~
