### ISSUE TITLE
Rename core.so into fluid.so

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#8347]
https://github.com/PaddlePaddle/Paddle/blob/e0fcaa518f4d15b895777e233c56acc4298a9c65/python/CMakeLists.txt#L46-L49

We need a more specific name `fluid.so` instead of `core.so`, which is a rather general name.

**Comment by abhinavarora** [comment]
Since Beijing folks are on leave, I can do this issue as this will help me learn more about Pybind.

**Comment by abhinavarora** [comment]
On investigation, I found that this core refers to Fluid C++ core and renaming it to fluid will create a conflict in the naming convention at some places. We have a lot of imports like this:
```python
import paddle.v2.fluid.core as core
import paddle.v2.fluid as fluid
```

Renaming the `core` in the first line to `fluid` can lead to an erroneous naming convention. Hence closing this issue.
