### ISSUE TITLE
汉化工作--contribute_to_paddle

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#835]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/contribute_to_paddle_en.md)

中文版本提交[目录](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/)

文件命名为 contribute_to_paddle_cn.md

**Comment by livc** [comment]
认领
