### ISSUE TITLE
汉化工作--cmd_parameter

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#836]
[ 需汉化文档英文地址](https://github.com/PaddlePaddle/Paddle/tree/develop/doc/howto/usage/cmd_parameter)

包括：arguments_en.md，detail_introduction_en.md，use_case_en.md 共三个文件

中文版本提交在同目录下。

文件命名为 arguments_cn.md，detail_introduction_cn.md，use_case_cn.md

**Comment by CrossLee1** [comment]
认领该任务

**Comment by luotao1** [comment]
@CrossLee1 请注意下该文档目录地址已更新，内容未变。
