### ISSUE TITLE
`forward_block_id` should be record in `proto::BlockDesc`

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#8367]
During the backward stage, an operator can access variables from two blocks, its current block, and its forward block. There are two paths to resolve variables. 

For example, the forwarding block could be

```text
{
   name: 'block0'
   
   {
      name: 'block1'
      parent: 'block0'
      {
         name: 'block2'
         parent: 'block1'
      }
   }
}
```

Its backward blocks are

```text

{
  name: 'block0_grad'
  parent: 'block0'
  fwd_block: 'block0'

  {
     name: 'block1_grad'
     parent: 'block0_grad'
     fwd_block: 'block1'

     {
        name: 'block2_grad'
        parent: 'block1_grad'
        fwd_block: 'block2'
     }
  }
}
```

Operators in `block2_grad` can access variables by `block::parent`(`block2_grad->block1_grad->block0_grad->block0`) and by `block::fwd_block` (`block2_grad->block2->block1->block0`).

The order of resolving variables should be breadth-first. i.e. `variables in block2` can hide `variables in block0_grad`.

**Comment by tonyyang-svail** [comment]
> The order of resolving variables should be breadth-first. i.e. variables in block2 can hide variables in block0_grad.

In the implementation, it is DFS. please confirm.

**Comment by JiayiFeng** [comment]
@tonyyang-svail I think it's just a simple linear backtracking. The variable searching order is:
```
current_grad_block ---> corresponding_fwd_block ---> parent_grad_block ---> parent_of_parent_grad_block ......
```
