### ISSUE TITLE
What is layer's interface standard in Python API ?

### ISSUE THREAD

**Issue by qingqing01** [PaddlePaddle/Paddle#8370]
1. About the name:

Some interfaces have the name, some not.

https://github.com/PaddlePaddle/Paddle/blob/279aa626ab25385093dcfc7e1a932a37535dc5a4/python/paddle/v2/fluid/layers/nn.py#L1432-L1439

https://github.com/PaddlePaddle/Paddle/blob/279aa626ab25385093dcfc7e1a932a37535dc5a4/python/paddle/v2/fluid/layers/nn.py#L1136-L1145

2. About `kwargs`

Some interfaces have the `**kwargs`, some not.

https://github.com/PaddlePaddle/Paddle/blob/279aa626ab25385093dcfc7e1a932a37535dc5a4/python/paddle/v2/fluid/layers/nn.py#L832-L836

https://github.com/PaddlePaddle/Paddle/blob/274f4e94af0051679e38b615a21a42fe363fbc5e/python/paddle/v2/fluid/layers/nn.py#L818-L819

**Comment by JiayiFeng** [comment]
I think we shall avoid using `**kwargs` in user interfaces. It makes users confused about what arguments are required exactly. Can anyone show me any examples the `**kwargs` is necessary?

**Comment by qingqing01** [comment]
> I think we shall avoid using **kwargs in user interfaces. It makes users confused about what arguments are required exactly.

I agree with you.

**Comment by reyoung** [comment]
## name
I was wishing the layer with the same name shared the same parameters. However, it seems that we have not implemented this feature.

We can give an easier way for two layers share the same parameters, and remove the `name` parameter.

## **kwargs
> I think we shall avoid using **kwargs in user interfaces. It makes users confused about what arguments are required exactly.
Can anyone show me any examples the **kwargs is necessary?

It because we pass the program to each layer function before. Now we change program to global variables. It is no need to use `**kwargs`.

**Comment by JiayiFeng** [comment]
Please notice that `**kwargs`s in layer interfaces has been removed by #8405 .

**Comment by abhinavarora** [comment]
@reyoung I was thinking that we should keep the name everywhere. What I see in the `layer_helper.py` that we prefix the names of the parameters with the `name` that is provided. I think this is very useful for debugging deep learning algorithms. For example, your model might have lots of fc layers. By giving name to layer, it is very easy to only concentrate on the parameter that you want to debug. Similarly, this will also be very useful once PaddleBoard for visualization is ready. You can visualize params from any particular layer easily if you know the name. What do you think?
