### ISSUE TITLE
Need to change the attribute is_test of batch_norm op to true in test_program and inference_program

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#8372]
There is a kind of operators which behaves differently in training and testing phase. They holds a attribute `is_test` to distinguish the type of task, such as [batch_norm_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/batch_norm_op.cc#L89) and [dropout_op](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/dropout_op.cc#L53). We need to set `is_test` to `true` in [test_program](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_image_classification.py#L117) and [inference_program](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/tests/book/test_image_classification.py#L181).

**Comment by kexinzhao** [comment]
@Xreki  The `inference_optimize` [function](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/prune.cc#L189-L204) can perform exactly this operation (no other optimization is performed).

Currently inference program will be inference optimized after pruning.
Will change test program to be inference optimized as well.

Another issue is that `inference_optimize` can only handle non-RNN case (i.e., no multiple blocks).
Will create a issue to make it compatible with RNN.

Please let me know if you have other suggestions.

**Comment by Xreki** [comment]
> The inference_optimize function can perform exactly this operation (no other optimization is performed).
> 
> Currently inference program will be inference optimized after pruning.
Will change test program to be inference optimized as well.

I think it is OK.

> Another issue is that inference_optimize can only handle non-RNN case (i.e., no multiple blocks).
Will create a issue to make it compatible with RNN.

I am not sure about this. The `save/load` may be rewritten in the near future. #8521 Let's how it will be first.
