### ISSUE TITLE
模型从cpu迁移到gpu后无法运行，提示错误和cuda相关

### ISSUE THREAD

**Issue by m123oooo** [PaddlePaddle/Paddle#8373]
系统信息：

<img width="273" alt="machi 2018-02-11 13-55-42" src="https://user-images.githubusercontent.com/8164606/36070337-5120f7f6-0f33-11e8-9558-53e25c1991a0.png">

CUDA Version 8.0.61

报错：
<img width="1132" alt="machi 2018-02-11 13-55-30" src="https://user-images.githubusercontent.com/8164606/36070342-68f479de-0f33-11e8-90ff-8cbcd089b5c5.png">

**Comment by chengduoZH** [comment]
请贴一下您用的GPU卡型是什么？

**Comment by m123oooo** [comment]
pip install paddlepaddle_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl
直接使用whl安装，报错：
![image](https://user-images.githubusercontent.com/8164606/36072160-ba82e444-0f55-11e8-8f81-a20ebc86fbeb.png)

**Comment by Superjomn** [comment]
pip install paddlepaddle_gpu 有试过吗

**Comment by m123oooo** [comment]
嗯嗯，试过了，最开始贴的那个图就是当时的提示的错误，pip install paddlepaddle_gpu这个安装没有问题，但是训练有问题

**Comment by m123oooo** [comment]
>>> print os.getenv('WITH_GPU')
None
直接获取GPU信息是空的，和机器配置有关系嘛？

**Comment by Superjomn** [comment]
这个应该不是问题。  WITH_GPU 不是系统的环境变量，只是paddle的cmake里的编译选项

**Comment by m123oooo** [comment]
![image](https://user-images.githubusercontent.com/8164606/36081617-27d75a3a-0fdc-11e8-9d26-ff98b03987a8.png)

**Comment by m123oooo** [comment]
会不会是环境变量没有设置呀？

**Comment by Superjomn** [comment]
.so 那就对应设下环境变量吧

如果可以用docker的话建议用docker，内网环境比较乱，也不容易装依赖

**Comment by m123oooo** [comment]
https://stackoverflow.com/questions/39850309/how-to-resolve-cudasuccess-err-0-vs-8-error-on-paddle-v0-8-0b
找到一个解决相关问题的链接，辛苦看一下

**Comment by m123oooo** [comment]
我是借用的其他组的机器，用docker安装方便吗？

**Comment by m123oooo** [comment]
问题已经解决，使用cuda8.0版本的whl安装包就没有问题了
