### ISSUE TITLE
paddle mpi运行了18个passes后失败，receiver提交的任务 http://10.73.168.17:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/655446/workspace/log/train.log

### ISSUE THREAD

**Issue by wfeagle** [PaddlePaddle/Paddle#8398]
Thank you for contributing to PaddlePaddle. Submitting an issue is a great help for us.
Both Chinese and English issues are welcome.

It's hard to solve a problem when important details are missing.
Before submitting the issue, look over the following criteria before handing your request in.

- [ ] Was there a similar issue submitted or resolved before ? You could search issue in the github.
- [ ] Did you retrieve your issue from widespread search engines ?
- [ ] Is my description of the issue clear enough to reproduce this problem?
   * If some errors occurred, we need details about `how do you run your code?`, `what system do you use?`, `Are you using GPU or not?`, etc.
   * If you use an recording [asciinema](https://asciinema.org/) to show what you are doing to make it happen, that's awesome! We could help you solve the problem more quickly.
- [ ] Is my description of the issue use the github markdown correctly?
   * Please use the proper markdown syntaxes for styling all forms of writing, e.g, source code, error information, etc.
   * Check out [this page](https://guides.github.com/features/mastering-markdown/) to find out much more about markdown.

**Comment by wanghaox** [comment]
参考这个issue https://github.com/PaddlePaddle/Paddle/issues/4419
请先排除机器节点问题，端口是否被占用。

**Comment by wfeagle** [comment]
请问如何排查机器几点？端口如果被占用，应该有相应的错误提示吧？一般说来，哪些端口可以用呢？

**Comment by wanghaox** [comment]
可以参考
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/faq/cluster/index_cn.rst

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
