### ISSUE TITLE
Register new Activation Operator using MKLDNN library

### ISSUE THREAD

**Issue by kbinias** [PaddlePaddle/Paddle#8433]
I want to register new Activation Operators (relu, tanh, sqrt) using MKLDNN library.
What steps I need to take to get my new Activation Operator working ?

**Comment by luotao1** [comment]
You can new a file named activation_mkldnn_op.cc, write kernels in it and register kernels.

**Comment by kbinias** [comment]
Solved, new activation operators will be delivered as soon as possible.
