### ISSUE TITLE
Need a `mutex` op in Fluid

### ISSUE THREAD

**Issue by kavyasrinet** [PaddlePaddle/Paddle#8435]
During the discussion of designing Go op in Fluid, we discovered that we might need a `synchronized` op in fluid that acquires a mutex on shared variables, if the Go op is used with other operators in Fluid. For example, to execute the following:
```go
import fluid

W = fluid.tensor(...)
X = fluid.tensor(...)

with fluid.go():
    mul_op(W, X)

# main thread
mul_op(W, X)
```
We need to acquire a mutex on the variables `W` and `X` in case other `Go` routines are trying to access them. This is how `Go` performs it as well (reference: https://golang.org/ref/mem#tmp_5). So one proposal is:
```go
import fluid

W = fluid.tensor(...)
X = fluid.tensor(...)

mutex = fluid.mutex(...)

with fluid.go():
    with fluid.synchronize(mutex):
        mul_op(W, X)

# main thread
with fluid.synchronize(mutex):
        mul_op(W, X)
```
We need to figure out how to share the lock between threads.
This work would require us to create a new variable that holds a mutex and a new operator `synchronize` that takes in the mutex and the block to protect.

**Comment by wangkuiyi** [comment]
I agree that in some use cases, mutex would be easier than CSP, like the above example.

A few suggestions on naming:

```python
with fluid.mutex_lock(mutex):
  mul_op(W, X)
```
