### ISSUE TITLE
How to print LoDTensor to debug for my input

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#8440]
I want to check my input in debugging my Model, but when I used fetch_list to get a LoDtensor and print it, I got [<paddle.v2.fluid.core.LoDTensor object at 0x7fcf26cacde0>], how to print its data in Python?

**Comment by kexinzhao** [comment]
You can use something like `np_data = np.array(your_lod_tensor)` to convert it to a numpy array and then print it.

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
