### ISSUE TITLE
Broken document rendering -- the Evolution of Deep Learning Systems

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#8448]
@hedaoyuan just reported this issue:

![14204f06fd40499f359bd883989ecb43](https://user-images.githubusercontent.com/1548775/36236915-b2622e96-11ad-11e8-991f-fe5f43db0d9a.jpg)

The table in this document doesn't display correctly.

**Comment by cs2be** [comment]
Fixed in https://github.com/PaddlePaddle/PaddlePaddle.org/pull/406
