### ISSUE TITLE
FLUID models roadmap

### ISSUE THREAD

**Issue by mrysztow** [PaddlePaddle/Paddle#8450]
Do you have a roadmap of introducing models to FLUID? We would like to align our plan of providing MKL-DNN OP kernels with model roadmap.

**Comment by luotao1** [comment]
In #7561, we have discussed PaddlePaddle's 10 aspects in 2018. For models of FLUID, there are NLP,Speech and Image support:
- NLP support: Enhance the CPU power of some NLP ops (mainly RNN/LSTM/GRU) based on specific workload.
- Speech support: Enhance the CPU power of some Speech ops (mainly RNN/CNN) based on specific workload.
- Image support: Enhance the CPU power of some Image ops (mainly CNN and Detection) based on specific workload.

**Comment by lcy-seso** [comment]
I give some brief information on NLP support. We have a plan to first focus on some state-of-art models in neural machine translation task in NLP field.
- Generally, for most many NLP tasks, RNN modules (including but not limited to) LSTM ([LSTM operator](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lstm_op.h) , [LSTM unit operator](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lstm_unit_op.h)), GRU ([GRU operator](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/gru_op.h)，[GRU unit operator](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/gru_unit_op.h)), and Simple RNN, are among the most important compuatation units. These operators are expected to be highly optimized.

---

-  For NMT task, three models are expected to be highly optimized:
    - RNN search (RNN encoder-decoder with attention): [Fluid's implementation](https://github.com/dzhwinter/benchmark/blob/master/fluid/machine_translation.py)
    - ConvS2S: Fluid's implementation is WIP.
    - Transformer: [Fluid's implementation](https://github.com/PaddlePaddle/models/tree/develop/fluid/transformer) 

- The time schedule: 
    - The first milestone for the NMT task is at the end of March, at then, the implementation of the three models are finished, their learning performances are verified and a basic profiling report is given. You can check this project: https://github.com/PaddlePaddle/Paddle/projects/37

- Important operators expected to be highly optimized:
    - [matmul operator](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/matmul_op.h)
    - [layer normalization](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/layer_norm_op.h)

**Comment by mrysztow** [comment]
Thank you for pointing particular NMT models.
What topologies are the most important for image recognition and speech? Are they Resnet-50 and DS2?

**Comment by luotao1** [comment]
@qingqing01 @kuke Can you help to answer it? Thanks very much!

**Comment by mrysztow** [comment]
@qingqing01 thank you for the list
Does SE-ResNeXt is going to replace classic Resnet50, already implemented for Fluid (https://github.com/dzhwinter/benchmark/blob/master/fluid/resnet50.py) ?

**Comment by qingqing01** [comment]
@mrysztow Both two networks are classic. Both are all needed.  They have the same basic operators.

**Comment by kuke** [comment]
For the application in speech,  we are now developing a recognition system [DeepASR](https://github.com/PaddlePaddle/models/tree/develop/fluid/DeepASR). The two important operators used are [Conv1D](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/sequence_conv_op.cc) and [LSTMP](https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lstmp_op.cc). 

In Q2, we plan to implement a wake-up system, the main structure is also CNNs+RNNs.

**Comment by mrysztow** [comment]
@luotao1 is https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/machine_translation.py implementation of Conv seq2seq, mentioned earlier in this thread (https://github.com/PaddlePaddle/Paddle/issues/8450#issuecomment-368200533)? Or it is another seq2seq model?

**Comment by luotao1** [comment]
@mrysztow https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/machine_translation.py is [seq2seq model](http://www.paddlepaddle.org/docs/develop/book/08.machine_translation/index.html). And conv seq2seq is in https://github.com/PaddlePaddle/models/pull/686.

**Comment by mrysztow** [comment]
Thank you

**Comment by luotao1** [comment]
| Tier 1| Tier 2| Tier 3|
|-------|-------|-------|
|ResNet50|[MobileNet-SSD](https://github.com/PaddlePaddle/models/blob/develop/fluid/object_detection/mobilenet_ssd.py)|[Conv seq2seq](https://github.com/PaddlePaddle/models/pull/686)(PR)|
|[RNN Search](https://github.com/dzhwinter/benchmark/blob/master/fluid/machine_translation.py)|[Transformer](https://github.com/PaddlePaddle/models/tree/develop/fluid/neural_machine_translation/transformer)|[CRNN CTC](https://github.com/PaddlePaddle/models/blob/develop/fluid/ocr_recognition/crnn_ctc_model.py)|
|[SE-ResNeXt](https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/se_resnext.py)|[DeepASR](https://github.com/PaddlePaddle/models/tree/develop/fluid/DeepASR)||

**Comment by luotao1** [comment]
Feeds support :
- [text_classification](https://github.com/PaddlePaddle/models/tree/develop/fluid/text_classification)
- [Transformer](https://github.com/PaddlePaddle/models/tree/develop/fluid/neural_machine_translation/transformer)
- [language_model](https://github.com/PaddlePaddle/models/tree/develop/fluid/language_model)
- [chinese_ner](https://github.com/PaddlePaddle/models/tree/develop/fluid/chinese_ner)

The mainly related operators are:
- FC, GRU, LSTM, Self-Attention

**Comment by mrysztow** [comment]
@luotao1 
I would like to confirm, that the current priority list is, considering current CPU deployments and feeds model, would be the following:

Tier 1 | Tier 2 | Tier 3| Tier 4 |
-- | -- | -- | --  |
ResNet50 | text_classification | MobileNet-SSD | Conv seq2seq(PR) |
CRNN-CTC | transformer | SE-ResNeXt | |
| | language_model |DeepASR| |
| | chinese_ner | RNN Search|  |

**Comment by luotao1** [comment]
@mrysztow The priority list is OK now.
