### ISSUE TITLE
Boost package location

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#8461]
Instead of using a private host http://paddlepaddledeps.s3-website-us-west-1.amazonaws.com for storing boost package, why don't we use the version from the official github repo https://github.com/boostorg/boost/tree/boost-1.41.0 ?

https://github.com/PaddlePaddle/Paddle/blob/c7ad26d6a4a37c6a2f0a59408e93fda23315cf94/cmake/external/boost.cmake#L27

**Comment by wangkuiyi** [comment]
For some reason, the CMakeLists.txt file in https://github.com/boostorg/boost is empty, except for a message:

https://github.com/boostorg/boost/blob/3f7b9488ec7214aaa73402117ad9b7564be239c1/CMakeLists.txt#L6-L16
