### ISSUE TITLE
删除废弃的PyDataProvider

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#847]
理由： 

* PyDataProvider2.py 已经取代PyDataProviderWrapper.py模块，且已经没有代码在沿用这个模块了。
* 有些用户因为**懒**, 在模型配置和数据处理上未全部采用新接口，而是混用新老接口，可能导致潜在的bug风险（ 因为PyDataProviderWrapper.py实际上可用）

故建议删除PyDataProviderWrapper.py模块

请 @reyoung  review

**Comment by reyoung** [comment]
同时应该删除PyDataProvider.cpp/h 和 config_parser.py， protobuf pyDataProviderBase.py等几个文件。

**Comment by reyoung** [comment]
@backyes 如果有时间可以交一下这个PR。

**Comment by backyes** [comment]
> 同时应该删除PyDataProvider.cpp/h 和 config_parser.py， protobuf pyDataProviderBase.py等几个文件。

麻烦也给下理由，方便其他人围观。 

这个issue，我来follow 没有问题。

**Comment by reyoung** [comment]
因为这个废弃的PyDataProvider不只有PyDataProviderWrapper.py这一个文件。

**Comment by backyes** [comment]
说个自己的体会： 
很多时候不是代码想解决的问题复杂，而是代码变迁的历史无从知晓，因此也给后来人理解或者改善代码带来困难，徒增学习成本。 因此，建议issue和pr首先能说清楚解决的问题是是什么。 另外，我相信绝对部分人都具备解决问题的能力，但是不一定具备理解历史的机会， 所以解释历史非常重要， 是合作的前提  ;-)

**Comment by zzsu** [comment]
目前因为OCR训练数据的特殊性（batch之间的图像尺寸不同），我们仍在沿用PyDataProvider。在PyDataProvider2支持用户形成并传入一个batch而非一个样本之前，删除PyDataProvider会造成我们没法继续目前的训练。

**Comment by reyoung** [comment]
> 目前因为OCR训练数据的特殊性（batch之间的图像尺寸不同），我们仍在沿用PyDataProvider。在PyDataProvider2支持用户形成并传入一个batch而非一个样本之前，删除PyDataProvider会造成我们没法继续目前的训练。

用PyDataProvider2，然后设置`should_shuffle=False`，应该可以满足需求吧？

**Comment by zzsu** [comment]
我理解是这样：设置一个batch_size，在python端，连续yield batch_size数量个样本，并且这些样本尺寸一致，然后PyDataProvider2会将传入的batch_size个连续样本组织成一个batch。这样的话是可以的。这里有两个问题，PyDataProvider2需要将样本的尺寸信息赋值到argument的frame height和width中；另一个是需要保证当PyDataProvider2形成一个batch时，需要确定这些样本是一样大小的，防止python端的处理弄错顺序（一个样本的错位就就造成所有batch都有问题）

**Comment by backyes** [comment]
@zzsu 

> 目前因为OCR训练数据的特殊性（batch之间的图像尺寸不同），我们仍在沿用PyDataProvider。在PyDataProvider2支持用户形成并传入一个batch而非一个样本之前，删除PyDataProvider会造成我们没法继续目前的训练。

由于PyDataProviderWrapper.py里对数据data_layer的类型的定义与PyDataProvider2是两条线，不是包含继承关系，且整个paddle 单测和demo已经没有任何关于PyDataProviderWrapper的引用，因此理论上说，PyDataProviderWrapper就没有存在的必要。针对 @zzsu 你的需求，你要么继续使用当前版本paddle，要么使用扩展PyDataProvider2，支持对不同图像尺寸的支持，因为即便保留PyDataProviderWrapper这种接口，由于主干代码并没有任何覆盖对PyDataProviderWrapper的测试支持，所以是会存在潜在的bug风险。 

因此， 主干开发分支，去掉PyDataProviderWrapper的支持，是合理的。

**Comment by reyoung** [comment]
> 我理解是这样：设置一个batch_size，在python端，连续yield batch_size数量个样本，并且这些样本尺寸一致，然后PyDataProvider2会将传入的batch_size个连续样本组织成一个batch。这样的话是可以的。这里有两个问题，PyDataProvider2需要将样本的尺寸信息赋值到argument的frame height和width中；另一个是需要保证当PyDataProvider2形成一个batch时，需要确定这些样本是一样大小的，防止python端的处理弄错顺序（一个样本的错位就就造成所有batch都有问题）


似乎这个需求可以在现有框架中实现，如果设置should_shuffle=False,那么训练数据的顺序和python yield的顺序exactly same。

**Comment by zzsu** [comment]
那麻烦请支持一下这个需求吧，只要其可以设置frame height和width，那数据的其他问题可以在python层解决。不过需要注意frame height和width有可能和ImageConf冲突，例如在batch norm层中，是通过frame height及width是否为0来判断需要考虑ImageConf还是frame height, width。换句话说，需要判断何时设置frame height和width，何时不设置。 @backyes 请暂时先不要删除，待我们完成切换或过渡后再删除。

**Comment by backyes** [comment]
@zzsu 

从整个pydataprovider的架构上看， 如下 ：

* paddle config_parse.py 读取配置文件（包含数据定义部分），并根据数据定义部分获取出用户自定义dataprovider的模块和函数（比如叫，image_pydataprovider.py for you）, 完成整个数据mini-batch的读取准备。

这其中， PyDataProviderWrapper.py是作为image_pydataprovider.py的一个依赖存在，且PyDataProviderWrapper.py并不跟paddle本身有任何关系。 

因此， 对于您的需求，最好的方法，是自己维护PyDataProviderWrapper.py作为自己image_pydataprovider.py的依赖模块即可。即， 你可以将该模块放到自己的project中，成为你的配置的一个部分。


@reyoung  请review这个做法是否有隐患。 @zzsu 你也可以试一试。 

我们clean代码也是优化用户体验，避免用户踩坑， 甚至让用户阅读代码也相对容易。

**Comment by zzsu** [comment]
@backyes 这个我是明白的，我们不介意PyDataProviderWrapper.py的存在与否，只介意PyDataProvider.cpp等文件是否存在。

**Comment by zzsu** [comment]
所以是否可以考虑支持一下在PyDataProvider2中支持一下frame height和width @reyoung @qingqing01

**Comment by backyes** [comment]
综合考虑 暂时不删除老dataprovider， 相关pr已经关闭，此issue也关闭
