### ISSUE TITLE
实现Torch7中图像常用的Data Augmentation处理逻辑，复现Identity-ResNet在Torch7上的结果

### ISSUE THREAD

**Issue by EnderLiuxiao** [PaddlePaddle/Paddle#850]
复现该repo下(https://github.com/facebook/fb.resnet.torch/tree/master/datasets) transforms.lua和imagenet.lua的图像预处理流程。使得在Paddle上预处理可以与Torch7严格一致。对同一数据集、用同样的结构，训练速度和最终分类精度都能基本相同。

**Comment by qingqing01** [comment]
data argumentaion实现以及在Identity-ResNet上的实验已经验证，结果 @EnderLiuxiao 已经验证，速度和准确度与Torch7接近。 后续data argumentaion的代码集成在  https://github.com/PaddlePaddle/Image  这个repo里，因此该issue暂时关掉了。
