### ISSUE TITLE
Distributed training VGG16 benchmark questions

### ISSUE THREAD

**Issue by helinwang** [PaddlePaddle/Paddle#8500]
In [Distributed training VGG16 benchmark](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/cluster/vgg16/README.md)

- Does `Single Node Single Thread` mean single node, if so, the `PServer Count: 10, Trainer Count: 20` below better be removed, since it's confusing.
- In `Different Batch Size`, there is `Per trainer CPU Core: 1`, why only 1 core is used, we probably should be utilizing all the computing resource of one node.
- Does `78.64%` in `Accelerate Rate` means the performance compared to ideal scenario?
- In `Accelerate Rate`, `PaddlePaddle v2` is much better than `Fluid` in the `trainer count = 20` case, do you know why is it so? Same question for the metric in `Different Pserver Count`, V2 is much better than Fluid.

**Comment by typhoonzero** [comment]
> In Different Batch Size, there is Per trainer CPU Core: 1, why only 1 core is used, we probably should be utilizing all the computing resource of one node.

Currently multicore uses MKL threading which is much like OMP, I'd prefer to test with parallel_do support. By the way, if we want to see whether the network communication performance will become a bottleneck, GPU tests may be easier to hit the point.

> Does 78.64% in Accelerate Rate means the performance compared to ideal scenario?

Yes. Which means actual performance / num_nodes * single thread result.

> In Accelerate Rate, PaddlePaddle v2 is much better than Fluid in the trainer count = 20 case, do you know why is it so? Same question for the metric in Different Pserver Count, V2 is much better than Fluid.

No, need to figure it out.

**Comment by helinwang** [comment]
Thanks @typhoonzero !
"Currently multicore uses MKL threading which is much like OMP, I'd prefer to test with parallel_do support" -- do you mean "1 core" is just the setting for intel MKL, in terms of the available CPU resource for each trainer process is still the number of core of "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz"?

Btw, can you look at the first point? (Does Single Node Single Thread mean single node, if so, the PServer Count: 10, Trainer Count: 20 below better be removed, since it's confusing.)

Thanks!

**Comment by typhoonzero** [comment]
> "1 core" is just the setting for intel MKL, in terms of the available CPU resource for each trainer process is still the number of core of "Intel(R) Xeon(R) CPU E5-2620 v4 @ 2.10GHz"?

Yes and No. The number of cores is determined by Kubernetes resource limits, and since I didn't use parallel_do in the test case, and gRPC uses async mode, this case does not utilize multi-core power at all.

I'll update the `README.md` today, thanks for pointing that out.
