### ISSUE TITLE
nccl.h not found when compiling from source

### ISSUE THREAD

**Issue by yu239** [PaddlePaddle/Paddle#8504]
See the reopened #5035.

**Comment by helinwang** [comment]
CC: @tonyyang-svail @dzhwinter could you guys take a look, we probably should support compiling without docker.

**Comment by helinwang** [comment]
Hi @yu239 , we switched to nccl2, please install the dependency using `sudo apt-get install libnccl2 libnccl-dev` (more info is here: http://docs.nvidia.com/deeplearning/sdk/nccl-install-guide/index.html).

nccl2 is closed source comparing to nccl1, so we can use cmake to download the source and compile. Maybe manually install it using apt-get is the best solution.

**Comment by typhoonzero** [comment]
@helinwang Is it necessary to add a build option to switch off nccl dependency?

**Comment by dzhwinter** [comment]
The nccl2 is not open sourced anymore, NVIDIA provide the cuda docker image with ppa include inside, so we can make a `apt install` command. @helinwang 
For build paddle of docker, you need to install nccl2 like cudnn manually.  Here is the nccl2 download link https://developer.nvidia.com/nccl

**Comment by luotao1** [comment]
Can we remove [cmake/external/nccl.cmake](https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/external/nccl.cmake), which will make users  confused?

**Comment by wangkuiyi** [comment]
Is our codebase (develop branch) still depend on NCCL 1? If not, let us remove mccl.cmake. @luotao1

**Comment by luotao1** [comment]
Our codebase still works well with NCCL 1, and @dzhwinter will update the nccl.cmake later to get the compatibility of the NCCL 1 and 2.

**Comment by dzhwinter** [comment]
In our codebase, we provide NCCL as a [DSO](https://gcc.gnu.org/wiki/Visibility)(Dynamic Shared Library) library. It means that we only use a nccl.h to compile, no more static library is depended.

According to the NCCL installl guide https://docs.nvidia.com/deeplearning/sdk/pdf/NCCL-Installation-Guide.pdf , we have the dependency relation below.
![image](https://user-images.githubusercontent.com/6687176/36639208-97358fee-1a42-11e8-85ed-5935a59b562e.png)

nccl2.1.4(latest) -> cuda9.0 or higher
nccl2.1.2 -> cuda8.0
nccl1.x -> cuda7.0 or higher

To make our Multi-GPU supported in more platform, we still need the nccl1 to compatible with older CUDA version.
