### ISSUE TITLE
长方形图片（non-square input）做卷积怎么处理

### ISSUE THREAD

**Issue by shboy** [PaddlePaddle/Paddle#8506]
我的输入图片是长方形的
看paddle.v2.layer.img_conv的描述是支持长方形的 可是没有找到可以设置长宽的形参
http://paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#permalink-6-conv-layers

**Comment by typhoonzero** [comment]
Related: https://github.com/PaddlePaddle/Paddle/issues/8108
