### ISSUE TITLE
paddle 图片模型内网无法下载，使用浏览器直接下载也失败

### ISSUE THREAD

**Issue by youan1** [PaddlePaddle/Paddle#8507]
如题，使用paddle 提供的model_download.sh无法下载vgg16的模型，直接使用浏览器从url ： http://cloud.dlnel.org/filepub/?uuid=aa0e397e-474a-4cc1-bd8f-65a214039c2e下载后，无法正常解压，请问从哪里能取到可用的vgg16的模型

**Comment by typhoonzero** [comment]
mac 测试可以正常下载并解压：`tar xzf test_vgg16.tar`

**Comment by yeyupiaoling** [comment]
@youan1 
您这个脚本在哪里的，我也试试

**Comment by guoshengCS** [comment]
已提供答复且较久未更新，这里先行close，如有需要还请reopen
