### ISSUE TITLE
想实现三个CNN模型输出权值相加

### ISSUE THREAD

**Issue by shboy** [PaddlePaddle/Paddle#8509]
![default](https://user-images.githubusercontent.com/24290262/36578779-624666e0-189a-11e8-87d8-176dfe9b02f5.jpg)
上图中等号右边 三个X 全是 2×32×35的图片（三个独立CNN输出），现在想为他们分别附一个可被训练的权重（learnable parameters），相加得到一个2×32×35的输出，想问一下这个paddle中如何实现呢？

**Comment by qingqing01** [comment]
可被训练的权重可以采用[`scale_shift`](http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#scale-shift)，不设置bias即可。

**Comment by shboy** [comment]
scale_shift 和 dotmul_projection（http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#permalink-41-dotmul_projection）有什么区别呢

**Comment by shboy** [comment]
scale_shift 和 dotmul_projection（http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#permalink-41-dotmul_projection ） 有什么区别呢 @qingqing01

**Comment by qingqing01** [comment]
- [scale_shift](http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#scale-shift): y=a*x+b, a,b可学习的参数，都是标量，大小为1。
- [dotmul_projection](http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#permalink-41-dotmul_projection): y = w * x，w是可学习的参数，是向量，w大小和feature size (x的大小)相等。
- [scaling_projection](http://www.paddlepaddle.org/docs/develop/api/en/v2/config/layer.html#scaling-projection): y=ax, a是可学习的参数，是标量，大小为1。

**Comment by chengduoZH** [comment]
问题已有解答，issue可以关掉了，如果仍有疑问，请重新打开！
