### ISSUE TITLE
 采用逻辑回归模型拟合text classification的demo中，input data不应该是sparse_binary_vector类型

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#851]
lr(bow) 模型用户文本分类： 

* 数据类型定义
```
    settings.input_types = [
        # The first input is a sparse_binary_vector,
        # which means each dimension of the vector is either 0 or 1. It is the
        # bag-of-words (BOW) representation of the texts.
        sparse_binary_vector(len(dictionary)),
        # The second input is an integer. It represents the category id of the
        # sample. 2 means there are two labels in the dataset.
        # (1 for positive and 0 for negative)
        integer_value(2)
    ]
```

* 数据处理过程：

```
def process(settings, file_name):
    # Open the input data file.
    with open(file_name, 'r') as f:
        # Read each line.
        for line in f:
            # Each line contains the label and text of the comment, separated by \t.
            label, comment = line.strip().split('\t')

            # Split the words into a list.
            words = comment.split()

            # convert the words into a list of ids by looking them up in word_dict.
            word_vector = [settings.word_dict.get(w, UNK_IDX) for w in words]

            # Return the features for the current comment. The first is a list
            # of ids representing a 0-1 binary sparse vector of the text,
            # the second is the integer id of the label.
            yield word_vector, int(label)
```
从上述dataprovider的片段来看， bow（lr）模型的输入数据类型应该为dense_vector, 而不是sparse_binary_vector， 因为返回的word_vector的每个id是word在字典中的序列，因此word_vector中每项均是非零值，因此使用dense_vector更加合理，否则容易误导用户对sparse的理解。 

Note: 此疑问来自追踪一个sparse bug的问题。（用户对sparse的用法比较晦涩，我们的guide）

related ： 
https://github.com/PaddlePaddle/Paddle/issues/841 
https://github.com/PaddlePaddle/Paddle/issues/847

@pengli09 @lcy-seso 请帮忙review下， 上述建议是否正确。

**Comment by backyes** [comment]
另外， 

模型定义的数据input size = len(总字典数量), 但是实际输入数据是len(一个句子的长度) ？ 

dataprovider中定义：
```
             # Split the words into a list.
            words = comment.split()
            # convert the words into a list of ids by looking them up in word_dict.
            word_vector = [settings.word_dict.get(w, UNK_IDX) for w in words]

            # Return the features for the current comment. The first is a list
            # of ids representing a 0-1 binary sparse vector of the text,
            # the second is the integer id of the label.
            yield word_vector, int(label)
```

模型配置：

```
# Define the data for text features. The size of the data layer is the number
# of words in the dictionary.
data = data_layer(name="word", size=len(word_dict))

```

@pengli09  帮忙review下

**Comment by reyoung** [comment]
@pengli09 我来吧。

这个原始配置是没有错的。

> 从上述dataprovider的片段来看， bow（lr）模型的输入数据类型应该为dense_vector, 而不是sparse_binary_vector， 因为返回的word_vector的每个id是word在字典中的序列，因此word_vector中每项均是非零值，因此使用dense_vector更加合理，否则容易误导用户对sparse的理解。

> 模型定义的数据input size = len(总字典数量), 但是实际输入数据是len(一个句子的长度) ？

这些都是正确的配置。

BOW是指，将一句话的所有词(word)，对应字典(dict)中的偏移值或者ID，组成一个稀疏向量(sparse_binary_vector)。

例如，字典为 { A:0, B:1, C:2, D:3, E:4, F:5}，句子为 "A C F"。组合出的向量即为 [1 0 1 0 1]。


所谓的Embedding，是将这个稀疏向量，乘以一个embedding矩阵，取出对应的embedding过程。

比如embedding的dim是4， 那么对应之前词典的embedding矩阵可能为:

```text
  | 0 1 2 3
--------------
A | a a a a
B | b b b b
C | c c c c
D | d d d d
E | e e e e
F | f f f f
```

所谓的embedding就是 那个bow的向量 [1 0 1 0 1] 乘以这个矩阵的过程，算出来的结果就是 [a+c+f] * 4, 也就是4维的dense向量。


所以，原始配置说的是直接使用BOW进行分类。就应该是返回一个字典大小的二值稀疏向量。

更具体更详细的事情，请参考论文  https://arxiv.org/abs/1103.0398

**Comment by backyes** [comment]
刚刚跟 @qingqing01 讨论了下， 的确我理解错了。 

另外，@qingqing01表示这个sparse_binary_vector表示中还会出现同一个index多次出现，index之间乱序的情况，也都是正常的。
