### ISSUE TITLE
Parallel Do operator occupies too much memory in GPU0.

### ISSUE THREAD

**Issue by QiJune** [PaddlePaddle/Paddle#8517]
Currently, the parallel do operator accumulate gradient in GPU 0, please refer to following code:
https://github.com/PaddlePaddle/Paddle/blob/8c0434c318edcc129e3ca9861aab05e717fda098/paddle/fluid/operators/parallel_do_op.cc#L281-L293

This will bring too much pressure on GPU 0. In large batch size training, it breaks down easily.

**Comment by QiJune** [comment]
Currently, maybe NCCL is the most convenient choice to do multi-GPU training.

**Comment by tonyyang-svail** [comment]
@QiJune Just FYI, NCCL also needs param_grad_buf for every param_grad.
