### ISSUE TITLE
paddle v2中，CNN的输入可以是可变尺寸的吗

### ISSUE THREAD

**Issue by SidHard** [PaddlePaddle/Paddle#8518]
image = paddle.layer.data(name="image", type=pd.data_type.dense_vector(3×224×224))
请问一下，paddle中，上面语句中的图像尺寸：224，是否可以设置为一个变量，根据输入图像的尺寸进行调节

**Comment by JiayiFeng** [comment]
不可以。输入图片必须有相同的尺寸。
建议先将所有输入图片都resize到同一大小再送入训练

**Comment by qingqing01** [comment]
@SidHard 支持mini-batch之内不可变，之间图片height, width可变。 参考： http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/model/index_cn.html#paddlepaddle
