### ISSUE TITLE
Fluid conv2d中存在bug

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#8546]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/fluid/layers/nn.py
的conv2d函数的此处filter_shape = [num_filters, num_filter_channels] + filter_size

如果filter_size为tuple，例如：[5,8]+(2,5,8)，则会出现以下异常
TypeError: can only concatenate list (not "tuple") to list

filter_size为None也会出现异常

**Comment by qingqing01** [comment]
感谢反馈，我们尽快修复下～
