### ISSUE TITLE
Remove LOG(FATAL) and CHECK in Paddle

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#855]
This issue is used to remove all LOG(FATAL) and CHECK in paddle. Related issue #849 .
Paddle was used as a command line tool in the past, so it should crash if any problems ware found. But if we want to use Paddle as lib in notebook, error should been thrown as exception but not crash.

**Comment by reyoung** [comment]
Now we are refactoring Paddle and using `PADDLE_ENFORCE` to fix this.
