### ISSUE TITLE
cmake WITH_GPU=ON && make, then cmake _WITH=GPU=OFF && make fails.

### ISSUE THREAD

**Issue by panyx0718** [PaddlePaddle/Paddle#8553]
If first make with gpu, then make without gpu, the second make fails with the following error messages.

My guess is, the WITH_GPU generates some other variables that needs CUDA, when WITH_GPU is false, those variables are not reset, hence it still asks for CUDA, which no longer exits.

../../libpaddle_fluid.a(gaussian_random_op_generated_gaussian_random_op.cu.o): In function `__cudaUnregisterBinaryUtil()':
/usr/local/cuda/include/crt/host_runtime.h:238: undefined reference to `__cudaUnregisterFatBinary'
../../libpaddle_fluid.a(gaussian_random_op_generated_gaussian_random_op.cu.o): In function `__device_stub__ZN6thrust6system4cuda6detail5bulk_6detail15launch_by_valueILj0ENS4_9cuda_taskINS3_14parallel_groupINS3_16concurrent_groupINS3_5agentILm1EEELm0EEELm0EEENS4_7closureINS2_17for_each_n_detail15for_each_kernelENS_5tupleINS4_6cursorILj0EEENS_12zip_iteratorINSG_INS_17counting_iteratorIjNS_11use_defaultESL_SL_EENS_10device_ptrIfEENS_9null_typeESP_SP_SP_SP_SP_SP_SP_EEEENS_6detail16wrapped_functionINSS_23unary_transform_functorIN6paddle9operators17GaussianGeneratorIfEEEEvEEjSP_SP_SP_SP_SP_SP_EEEEEEEEvT0_':
/tmp/tmpxft_00006eaa_00000000-4_gaussian_random_op.compute_61.cudafe1.stub.c:17: undefined reference to `cudaSetupArgument'
../../libpaddle_fluid.a(gaussian_random_op_generated_gaussian_random_op.cu.o): In function `cudaLaunch<char>':
/usr/local/cuda/include/cuda_runtime.h:1819: undefined reference to `cudaLaunch'

**Comment by luotao1** [comment]
> If first make with gpu, then make without gpu

You can `make clean` between these two `make` step. Or `rm -r build/paddle/fluid/inference` directly.
