### ISSUE TITLE
使用Docker编译Android的PaddlePaddle库，在build开发镜像时下载Go依赖环境失败

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8555]
使用这些命名创建Docker容器，在最后一条命令时
```
$ git clone https://github.com/PaddlePaddle/Paddle.git
$ cd Paddle
$ docker build -t username/paddle-android:dev . -f Dockerfile.android
```
卡在
```
Step 11/18 : RUN wget -qO- go.tgz https://www.golangtc.com/static/go/1.8.4/go1.8.4.linux-amd64.tar.gz |     tar -xz -C /usr/local &&     mkdir /root/gopath &&     mkdir /root/gopath/bin &&     mkdir /root/gopath/src
```
之前的下载路径是下面这个，但是因为被墙了，所以才改成上面那个，但是还是卡在这里动不了，然后就死掉了。
```
https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
```

有什么办法处理吗？

**Comment by yeyupiaoling** [comment]
自己配置go环境是否可行？

下载源码
```
wget https://storage.googleapis.com/golang/go1.8.1.linux-amd64.tar.gz
```
解压源码
```
tar -xzf go1.8.1.linux-xxx.tar.gz -C /usr/local 
```
在`~/.bashrc`的最后加上
```
export GOPATH=/usr/local/go  
export PATH=$GOPATH/bin:$PATH  
```
使其生效
```
source ~/.bashr 
```
再在命令行中输入
```‘
export GOROOT=/usr/local/go  
export GOPATH=$PATH:$GOROOT/bin  
```
检查安装结果
```
go version
```

**Comment by yeyupiaoling** [comment]
好像自行安装不行，在执行
```
docker run -it --rm -v $PWD:/paddle -e "ANDROID_ABI=armeabi-v7a" -e "ANDROID_API=21" mypaddle/paddle-android:dev
```
报错
```
CMake Error at CMakeLists.txt:22 (project):
  No CMAKE_Go_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "GO_COMPILER" or the CMake cache entry CMAKE_Go_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/paddle/build_android/CMakeFiles/CMakeOutput.log".
```

**Comment by Xreki** [comment]
可尝试使用Paddle官方提供的[Android开发镜像](http://www.paddlepaddle.org/docs/develop/documentation/zh/mobile/cross_compiling_for_android_cn.html)，通过运行以下命令：

```
docker pull paddlepaddle/paddle:latest-dev-android
```

> 之前的下载路径是下面这个，但是因为被墙了，所以才改成上面那个，但是还是卡在这里动不了，然后就死掉了。

编译Android版本其实不需要依赖Go，后续我们会Fix这个问题，去掉Go的依赖。

**Comment by yeyupiaoling** [comment]
@Xreki 
我有使用过官方提供的，也卡住了如下，网络非常好的，我用的是**百度深度学习集群**
```
latest-dev-android: Pulling from paddlepaddle/paddle
8f7c85c2269a: Downloading 40.91 MB/40.91 MB
9e72e494a6dd: Download complete 
3009ec50c887: Download complete 
9d5ffccbec91: Download complete 
e872a2642ce1: Download complete 
570082195a8a: Downloading 13.49 MB/145.3 MB
0cdf10645261: Downloading 47.62 MB/47.62 MB
64027af0c9f9: Download complete 
4fbf912cad9c: Download complete 
885800e8dda3: Downloading 8.378 MB/8.378 MB
00b3792683ff: Downloading 820.6 MB/820.6 MB
```

有没有像编译源码http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/build_from_source_cn.html#build-options 这样选择不用GO语言的吗？

**Comment by yeyupiaoling** [comment]
@Xreki 
我用其他链接解决的下载GO语言的问题，但是又出现
```
/paddle/paddle/scripts/docker/build_android.sh: line 2: $'\r': command not found
: invalid optioncripts/docker/build_android.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/paddle/paddle/scripts/docker/build_android.sh: line 4: $'\r': command not found
/paddle/paddle/scripts/docker/build_android.sh: line 11: syntax error near unexpected token `else'
'paddle/paddle/scripts/docker/build_android.sh: line 11: `else # armeabi, armeabi-v7a
```

**Comment by Xreki** [comment]
可暂时通过手动改源码的方式来解决这个问题，将

https://github.com/PaddlePaddle/Paddle/blob/c02f773a537b1693a3fad941980d052aa36cc766/CMakeLists.txt#L22

改成`project(paddle C CXX)`，然后`Dockerfile.android`中去掉

https://github.com/PaddlePaddle/Paddle/blob/c02f773a537b1693a3fad941980d052aa36cc766/Dockerfile.android#L24-L32

Android实际并不依赖Go代码，我正在想办法去掉这个依赖，:smile:

**Comment by Xreki** [comment]
> 我用其他链接解决的下载GO语言的问题，但是又出现
>
> ```
> /paddle/paddle/scripts/docker/build_android.sh: line 2: $'\r': command not found
> : invalid optioncripts/docker/build_android.sh: line 3: set: -
> set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
> /paddle/paddle/scripts/docker/build_android.sh: line 4: $'\r': command not found
> /paddle/paddle/scripts/docker/build_android.sh: line 11: syntax error near unexpected token `else'
> 'paddle/paddle/scripts/docker/build_android.sh: line 11: `else # armeabi, armeabi-v7a

这个错不是构建Docker镜像的错误了啊。你Docker镜像已经成功构建了？
`paddle/scripts/docker/build_android.sh`你是不是在windows上打开编辑过？

**Comment by yeyupiaoling** [comment]
@Xreki 
应该是没有的，我一直都是在百度深度学习的集群上处理的，我重新试试
话说这个服务器clone 的PaddlePaddle速度超慢的
还有官方有没有提供国内的paddlepaddle/paddle:latest-dev-android镜像，我一直都pull不成功

**Comment by Xreki** [comment]
> 还有官方有没有提供国内的paddlepaddle/paddle:latest-dev-android镜像，我一直都pull不成功

目前没有国内的镜像源。 @Yancey1989 我们可以将android开发镜像tag推送到国内镜像源`docker.paddlepaddlehub.com/paddle`吗？

**Comment by yeyupiaoling** [comment]
>我用其他链接解决的下载GO语言的问题，但是又出现
```
/paddle/paddle/scripts/docker/build_android.sh: line 2: $'\r': command not found
: invalid optioncripts/docker/build_android.sh: line 3: set: -
set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
/paddle/paddle/scripts/docker/build_android.sh: line 4: $'\r': command not found
/paddle/paddle/scripts/docker/build_android.sh: line 11: syntax error near unexpected token `else'
'paddle/paddle/scripts/docker/build_android.sh: line 11: `else # armeabi, armeabi-v7a
```
这个问题我解决的，果然是Windows的问题，我用git强制覆盖本地就行了

**Comment by yeyupiaoling** [comment]
@Xreki 
>手动改源码的方式来解决这个问题

这个去掉Go语言的问题我也解决了，如果没有问题我就close issue了

@Yancey1989 
如果可以，在这里回答一下可以吗？

**Comment by Yancey1989** [comment]
> 目前没有国内的镜像源。 @Yancey1989 我们可以将android开发镜像tag推送到国内镜像源docker.paddlepaddlehub.com/paddle吗？

Done, 可通过 `docker pull docker.paddlepaddlehub.com/paddle:latest-dev-android` 来从国内镜像源拉取镜像。

**Comment by Xreki** [comment]
@Yancey1989 多谢了~

**Comment by yeyupiaoling** [comment]
@Yancey1989 多谢了
