### ISSUE TITLE
The default option of WITH_FAST_BUNDLE_TEST should be OFF 

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#8558]
This issue comes from users. When they add new unitests, they couldn't run these unitests independently. They should manually set `-DWITH_FAST_BUNDLE_TEST=OFF`.

Thus, we could set the default option of `WITH_FAST_BUNDLE_TEST` be OFF, and turn it ON in teamcity.

**Comment by panyx0718** [comment]
Sounds Good
