### ISSUE TITLE
capi, 多sequence输入如何编写

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#8578]
capi v2的例子中只有单个sequence输入的例子 https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/capi/examples/model_inference ，有没有多个sequence输入的例子？还有对应python中的feeding如何设置？

**Comment by Yancey1989** [comment]
可以参考下models中的seq2seq: https://github.com/PaddlePaddle/models/blob/develop/conv_seq2seq/model.py#L370

**Comment by peterzhang2029** [comment]
https://github.com/PaddlePaddle/Paddle/issues/8618
