### ISSUE TITLE
The problem of improving the performance of Parallel_Do

### ISSUE THREAD

**Issue by tonyyang-svail** [PaddlePaddle/Paddle#8592]
The current design uses parallel_do to describe the multi-GPU training.

In order to achieve [good performance](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/parallel_do.md#forward-copy-parameter-to-onto-different-devices), we need to maintain a copy of the parameters on each GPU. This includes the parameter itself, the aggregation of the gradient across all devices, and momentum/velocity if needed by the optimizer.

This requires compatibility support of initializer, backward and optimizer.

LayerHelper(@reyoung) needs to be aware which parameter is created inside of a parallel_do, then put their initializers in a new parallel_do block.

Backward(@JiayiFeng) needs to support inserting AllReduce into the programDesc when the parameter is created inside of a parallel_do.

Optimizer(@jacquesqiao) needs to create a new parallel_do whose block contains the `sgd` if the parameter is created inside of a parallel_do.

Moreover, the support of memory optimization(@QiJune) is also needed.

This large amount of dependencies doesn't look right to me.

**Comment by tonyyang-svail** [comment]
```c++
ParallelExecutor(vector<Place>);

ParallelExecutor::Run() {
  for (sub_place in places) {
    sub_scope = scope.Get(sub_place)
    Executor sub_exe(sub_place);
    thread([](Executor(program_desc, sub_scope, sub_place))
  }
}
```

```python
net_def()
backward.append_backward(..., allreduce=True)

ParallelExecutor([CUDAPlace(0), CUDAPlace(1)])

ParallelExecutor.Run(fluid.default_startup_program())

while True:
    ParallelExecutor.Run(fluid.default_main_program())
```

**Comment by helinwang** [comment]
```python
import executor
from . import core

class ParallelExecutor(object):
    def __init__(self, places):
        self.scopes = {}
        self.executors = []
        for place in places:
            self.executors.append(executor.Executor(place))

    def run(self,
            program=None,
            feed=None,
            fetch_list=None,
            feed_var_name='feed',
            fetch_var_name='fetch',
            scope=None,
            return_numpy=True):
        # TODO(helin): support data feeder
        # TODO(helin): split input
        # TODO(helin): run in parallel
        for idx, exe in enumerate(self.executors):
            if scope is None:
                if idx == 0:
                    scope = executor.global_scope()
                else:
                    if idx in self.scopes:
                        scope = self.scopes[idx]
                    else:
                        scope = core.Scope()
                        self.scopes[idx] = scope

            tmp_out = exe.run(program, feed, fetch_list, feed_var_name, fetch_var_name, scope, return_numpy)
            if idx == 0:
                # TODO(helin): concat output
                outs = tmp_out
        return outs
```

**Comment by dzhwinter** [comment]
I encounter the low efficiency of cuda memcpy problem. I will work on separate the copy and compute engine. It will also improve the performance of parallel.do.  https://devblogs.nvidia.com/how-overlap-data-transfers-cuda-cc/

related issue https://github.com/PaddlePaddle/Paddle/issues/8567

**Comment by QiJune** [comment]
We mainly have two problem:
- IO and computation do not have overlap
- GPUs resource are not fully used, there is much IO and computation burden on GPU0

**Comment by jacquesqiao** [comment]
The main problem is that Program does not know actual device information.

**Comment by helinwang** [comment]
> A better implementation should be:
> each card does part of parameter optimization.

Agree, but I think that's not a option for parallel do, since it requires all threads running the same block. It's possible after the go operator comes out.

**Comment by helinwang** [comment]
How do you guys think about this approach:

1. parallel do: copy the parameter in the sub scope starting from the second place. (first place uses the parameter in the global scope, other places uses the parameter in their own local scope).
1. parallel do grad: NCCL all reduce will be called, each place will have its own param visible.
1. parallel do: each block will have optimizer that update its own param. No NCCL all reduce necessary.

**Comment by QiJune** [comment]
> parallel do: copy the parameter in the sub scope starting from the second place. (first place uses the parameter in the global scope, other places uses the parameter in their own local scope). Need to modify parallel_do_op.cc.

Agreed. Each GPU card will has its own local parameter. 


> parallel do for optimization pass: each block will have optimizer that update its own param. Need to modify create_optimization_pass in optimizer.py.

Agreed. Each GPU card will update its own parameter.

@helinwang  I have another question. The logic of parallel_do in CPU is a little different from parallel_do GPU. Since we only have one copy of parameter in CPU memory, but we have to four copy of parameter if we have four GPU card.

**Comment by helinwang** [comment]
@QiJune thanks for the reminder! I think I need to change to logic, only make copy parameter if it's GPU memory (https://github.com/PaddlePaddle/Paddle/pull/8620/files#diff-9cc30f7ca2054240d8daf3a8c0e3b70eR147).

**Comment by tonyyang-svail** [comment]
Conclusion: In multi-GPU training, ParallelDo won't maintain a copy of the parameters on each GPU.
