### ISSUE TITLE
文本语义化召回

### ISSUE THREAD

**Issue by wangbin11** [PaddlePaddle/Paddle#8597]
最近在尝试用paddlepaddle提供的[dssm模型](https://github.com/PaddlePaddle/models/tree/develop/dssm)对query和doc做向量语义化，但是发现通过query向量语义化召回的很多doc结果毫无关联。比如query是”广洲新塘新围工业区“，召回了”新叶汤圆“ 还有”兴 宁 路 / 钓 台 路 ( 路 口 )“这种结果，cos相似度倒是挺高的，0.96。求教， 为什么会出现这样的无关语义召回结果呀。
模型和paddlepaddle提供的dssm模型库基本一样，用的是cnn+回归，正负样本各2000w，单字切分（切词也试了，效果没太大区别）。word embeding是256维度，模型输出（短文本）的是128维，训练了25个pass。

**Comment by lcy-seso** [comment]
下面这条样本是训练集合还是测试集合？

>“比如query是”广洲新塘新围工业区“，召回”新叶汤圆“ 还有”兴 宁 路 / 钓 台 路 ( 路 口 )“这种结果，cos相似度倒是挺高的，0.96。”

这个问题难以直接回答。机器学习任务通过拟合训练样本，且同时避免过拟合，来实现对未知样本的预测。请考虑训练样本如何构造，如何进行的评估。同时，细节缺失，问题太大，无法直接回答你的问题。

**Comment by wangbin11** [comment]
@lcy-seso 这条0.96的结果是测试集，
依然非常感谢帮助解答，我从构造数据集的角度再迭代一下

**Comment by pkuyym** [comment]
@wangbin11 Close it due to inactivity.
