### ISSUE TITLE
SSD神经网络使用PaddlePaddle如何做预训练

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8599]
我使用仿照这个例子http://paddlepaddle.org/docs/develop/models/ssd/README.cn.html 使用自己的数据集训练，如果没有预训练就报浮点异常，那么怎么做预训练？#8530

**Comment by lcy-seso** [comment]
通常图像类任务会使用大规模图像分类任务（比如ImageNet数据集上的分类任务等）作为预训练任务。

**Comment by yeyupiaoling** [comment]
@lcy-seso 
如何理解您这句话？有没有具体的操作，又或者code

**Comment by pkuyym** [comment]
@yeyupiaoling hi，之前的issue应该已经解决了您遇到的问题。目前版本的SSD比较容易出异常，比较大的可能是参数初始化不太好，导致梯度爆炸或loss overflow。预训练可以一定程度上缓解这种情况，这是因为针对图像任务，初始几层的卷积层通常提取的是low level的特征，这些filter具有很大的可迁移性，在其他任务里面训练的模型（例如图像分类），使得这些filter的参数得到了较好的训练，用这些参数来初始化新的模型，有助于提升模型的收敛速度及效果。

**Comment by yeyupiaoling** [comment]
@pkuyym 
好，那最后问一下，官方的预训练模型是如何训练得到的？谢谢

**Comment by pkuyym** [comment]
@yeyupiaoling 这个是从caffe的模型转换过来的

**Comment by yeyupiaoling** [comment]
@pkuyym 
了解，谢谢~

**Comment by yeyupiaoling** [comment]
@pkuyym 
>这个是从caffe的模型转换过来的

是训练什么数据的呢？ImageNet吗？

**Comment by yeyupiaoling** [comment]
我在这里找到一个类似的预训练模型，应该是数据集应该是ilsvrc
