### ISSUE TITLE
Ubuntu 16.04.3 pip安装的paddlepaddle运行housing.py，提示：非法指令（核心已转储）

### ISSUE THREAD

**Issue by bluebird138** [PaddlePaddle/Paddle#8606]
我这边新安装的Ubuntu也遇到以上的问题。
sudo apt-get install python-pip
pip install paddlepaddle
python housing.py
提示：非法指令 (核心已转储)
lenovoG460笔记本，Ubuntu 16.04.3 LTS, Python 2.7

**Comment by bluebird138** [comment]
使用docker来运行housing程序，模型也已放在workspace目录，输入以下命令，没有任何输出。
bluebird@bluebird-Lenovo-G460:~/workspace$ sudo docker run --rm -v ~/workspace:/workspace python /workspace/housing.py

查看docker版本，输入
sudo docker version
输出以下信息
Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:11:19 2017
 OS/Arch:	linux/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:09:53 2017
  OS/Arch:	linux/amd64
  Experimental:	false

**Comment by yeyupiaoling** [comment]
@bluebird138 
请确认您的电脑是否支持AVX指令集，查看命令如下：
```
if cat /proc/cpuinfo | grep -i avx; then echo Yes; else echo No; fi
```

**Comment by bluebird138** [comment]
已检查过cpu不支持avx指令集。我用docker在https://hub.docker.com/r/paddlepaddle/paddle/tags/下载了paddlepaddle/paddle:0.10.0rc3-noavx使用，同样没跑通基本的housing.py例子，原因缺少许多python依赖库，需要使用docker另外安装依赖包，这表明目前PaddlePaddle官网没有提供可以完全跑通housing.py基本例子的paddle镜像，这给PaddlePaddle初学者带来许多不便。

**Comment by luotao1** [comment]
related https://github.com/PaddlePaddle/Paddle/issues/8721#issuecomment-370317929 我们正在push noavx的docker版本，更新后会第一时间通知您

**Comment by yeyupiaoling** [comment]
@bluebird138 
建议在ubuntu上搭建PaddlePaddle环境，这样却什么环境就不什么。但要安装navx版本的PaddlePaddle

**Comment by bluebird138** [comment]
最好的办法是换台电脑，使用支持avx的cpu的计算机做实验，否则因为新版paddlepaddle不支持noavx指令集，会遇到各种问题。
