### ISSUE TITLE
编译paddle_internal_release_tools报错

### ISSUE THREAD

**Issue by imzcy1987** [PaddlePaddle/Paddle#861]
编译的时候报错：
paddle_internal_release_tools/idl/paddle/Paddle/paddle/cuda/include/hl_warpctc_wrap.h:19:34: fatal error: warp-ctc/include/ctc.h: No such file or directory
 #include "warp-ctc/include/ctc.h"
找不到ctc.h文件

**Comment by backyes** [comment]
@imzcy1987  请重新update paddle_internal_release_tools repo，确认当前是stable分支， 然后再编译。

**Comment by backyes** [comment]
@imzcy1987 

上树问题是由于一键编译工具refer了 最新的代码（集成了warp-ctc）。 

建议解决方法： 

* 从稳定性角度，且不着急尝试新特性，可以考虑git pull 更新一键工具。 一键工具默认已经使能refer github paddle稳定master分支。

* 如果非要尝试最新的版本，请执行编译前，执行git submodule init && git submoudel update ，使能warp-ctc sumodule local repo， 即可。
