### ISSUE TITLE
通过什么接口获取seq2seq模型的输出结果

### ISSUE THREAD

**Issue by nuoline** [PaddlePaddle/Paddle#8618]
设计了一个seq2seq模型，前面几层是RNN，最后一层是CRF解码来做序列标注，C++接口里面通过什么接口可以获取预测后标注的结果呢？
//输入
        paddle_arguments in_args = paddle_arguments_create_none();
        CHECK(paddle_arguments_resize(in_args, 1));
        paddle_ivector sentence = paddle_ivector_create(
                sentence_ids, sizeof(sentence_ids) / sizeof(int), false, false);
        CHECK(paddle_arguments_set_ids(in_args, 0, sentence));
        int seq_pos_array[] = {0, sizeof(sentence_ids) / sizeof(int)};
        paddle_ivector seq_pos = paddle_ivector_create(
                seq_pos_array, sizeof(seq_pos_array) / sizeof(int), false, false);
        CHECK(paddle_arguments_set_sequence_start_pos(in_args, 0, 0, seq_pos));
//预测
       paddle_arguments out_args = paddle_arguments_create_none();
        CHECK(paddle_gradient_machine_forward(_machine, in_args, out_args, /*isTrain*/false));
然后通过什么C-API接口获取标注的结果？ 是否有接口使用DEMO？

**Comment by luotao1** [comment]
可以参考：https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/capi/examples/model_inference/sequence/main.c

**Comment by nuoline** [comment]
看文档说是序列输出应该使用paddle_ivector，CRF模型输出应该使用paddle_ivector吧，为什么这个demo使用的paddle_matrix ？ 
我就是使用这个demo里面的获取方法，代码一样，但是执行最后提示：
Invoke paddle error 1 in paddle_matrix_get_row(prob, 0, &array)

**Comment by nuoline** [comment]
paddle_matrix prob = paddle_matrix_create_none();
        CHECK(paddle_arguments_value(out_args, 0, prob));
        paddle_real* array;
        CHECK(paddle_matrix_get_row(prob, 0, &array));

        for (int i = 0; i < 2; ++i) {
            std::cout << array[i] << "\t";
        }
我的C-API里面没有paddle_arguments_get_value这个函数，编译会报错，我改为了paddle_arguments_value，编译通过后，最终执行就提升上面的erro

**Comment by luotao1** [comment]
> CRF模型输出应该使用paddle_ivector吧，为什么这个demo使用的paddle_matrix

demo的输出是fc_layer，是二维矩阵。而CRF模型的输出是一维整型数组，需要使用paddle_arguments_ids来获得。

**Comment by peterzhang2029** [comment]
Closing due to low activity. Feel free to reopen it.
