### ISSUE TITLE
在mpi环境下运行fluid分布式训练时transpile出core

### ISSUE THREAD

**Issue by Cwndmiao** [PaddlePaddle/Paddle#8625]
在厂内mpi集群上尝试运行fluid分布式训练，使用的测试程序是[test_fit_a_line.py](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_fit_a_line.py)。

使用`mpirun train.sh`在每个mpi节点上运行`train.sh`，主要内容如下。
![image](https://user-images.githubusercontent.com/2132839/36768737-8ce07a0a-1c7b-11e8-9628-dc71734b7a68.png)

程序崩溃时看到的log如下。
![image](https://user-images.githubusercontent.com/2132839/36768789-bb5b82d0-1c7b-11e8-9cf0-9c631c224230.png)

**Comment by typhoonzero** [comment]
貌似是个bug，我现在在develop分支也遇到这个问题。正在看。

**Comment by Yancey1989** [comment]
Trainer启动时的环境变量是什么呢？

**Comment by Cwndmiao** [comment]
![image](https://user-images.githubusercontent.com/2132839/36769289-63732764-1c7e-11e8-83a8-8faf50fcc51e.png)

**Comment by Cwndmiao** [comment]
![image](https://user-images.githubusercontent.com/2132839/36769373-d8f88934-1c7e-11e8-82dc-7079c5c13ebe.png)
trainer的环境变量和pserver就相差了一个training_role。
