### ISSUE TITLE
一键编译后的paddle_internal_release_tools，在预测时出现ImportError

### ISSUE THREAD

**Issue by qubingxin** [PaddlePaddle/Paddle#865]
一键编译paddle_internal_release_tools成功后，用output文件夹下的/output/python27-gcc482/bin/python运行预测代码（之前是可以运行成功的），报错：
Traceback (most recent call last):
  File "predict_img1.py", line 15, in <module>
    from py_paddle import swig_paddle, DataProviderConverter
  File "/home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/__init__.py", line 15, in <module>
    from util import DataProviderWrapperConverter
  File "/home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/util.py", line 18, in <module>
    import swig_paddle
  File "/home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 28, in <module>
    _swig_paddle = swig_import_helper()
  File "/home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/swig_paddle.py", line 24, in swig_import_helper
    _mod = imp.load_module('_swig_paddle', fp, pathname, description)
ImportError: /home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm

请问是什么原因？

**Comment by backyes** [comment]
@qubingxin  

有复现的方法么？

**Comment by qubingxin** [comment]
http://deeplearning.baidu.com/doc/local_compile.html 按照这个一键安装的。然后运行/output/python27-gcc482/bin/python   之后输入from py_paddle import swig_paddle, DataProviderConverter  就会报上述错误

**Comment by qubingxin** [comment]
刚刚测试了下，输入from py_paddle import swig_paddle会报Segmentation fault；输入from py_paddle import DataProviderConverter会报ImportError: /home/qubingxin/qbx/model/paddle_predict/libpaddle/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm

**Comment by backyes** [comment]
@qubingxin 

确认下几个步骤： 

*  有没有source ~/.bashrc。 第一次执行的时候，如果没有执行paddle train --help, 是不能直接导入py_paddle, 但是貌似你没有执行这个步骤，所以我怀疑你也没有执行 source ~/.bashrc

**Comment by backyes** [comment]
@qubingxin 

另外，如果上述方法都操作过，还是有bug， 请给出相对能step by step的复现方法。

**Comment by qubingxin** [comment]
再次试了一遍仍有bug，复现方法：
1. 进入paddle_internal_release_tools/idl/paddle，执行sh build.sh
2. source ~/.bashrc
3. paddle train –help  
之后进入paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7，执行python，输入from py_paddle import DataProviderConverter，仍会报ImportError: /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: undefined symbol: _ZNKSt8__detail20_Prime_rehash_policy11_M_next_bktEm

该过程稳定复现

**Comment by backyes** [comment]
```
[qubingxin@cp01-bri00 python27-gcc482]$ ldd /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so
/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/python2.7/site-packages/py_paddle/_swig_paddle.so: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/libpython2.7.so.1.0)
	linux-vdso.so.1 =>  (0x00007fffb65ff000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f2dec79b000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f2dec596000)
	libpython2.7.so.1.0 => /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/output/python27-gcc482/lib/libpython2.7.so.1.0 (0x00007f2dec177000)
	libstdc++.so.6 => /home/qubingxin/.jumbo/opt/gcc46/lib64/libstdc++.so.6 (0x00007f2debe7a000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f2debbf5000)
	libgcc_s.so.1 => /home/qubingxin/.jumbo/opt/gcc46/lib64/libgcc_s.so.1 (0x00007f2deb9e0000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f2deb64e000)
	/lib64/ld-linux-x86-64.so.2 (0x000000318a600000)
	libutil.so.1 => /opt/compiler/gcc-4.8.2/lib/libutil.so.1 (0x00007f2deb44a000)
```

swig 链接到jumbo 库（非gcc48库）， 故障原因应该跟这个应该有关系。 我追一下。

**Comment by backyes** [comment]
@qubingxin 

确认应该是Paddle make系统有缺陷，对swig paddle的构造过程使用了系统默认的gcc，而非指定的gcc48，
```
c++ -pthread -shared build/temp.linux-x86_64-2.7/Paddle_wrap.o -o build/lib.linux-x86_64-2.7/py_paddle/_swig_paddle.so -Xlinker -start-group -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/math -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/utils -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/parameter -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/gserver -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/api -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/cuda -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/pserver -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/trainer -L/home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/build/paddle/../proto -Wl,--whole-archive -lpaddle_gserver -Wl,--no-whole-archive -lpaddle_pserver -lpaddle_trainer_lib -lpaddle_network -lpaddle_parameter -lpaddle_math -lpaddle_utils -lpaddle_proto -lpaddle_cuda -lpaddle_api /home/qubingxin/qbx/source_code/paddle_internal_release_tools/third-64/protobuf/lib/libprotobuf.a /home/qubingxin/qbx/source_code/paddle_internal_release_tools/third-64/zlib/lib/libz.a -lpthread -ldl /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/thirdparties/mkl/lib/libmkl_intel_lp64.a /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/thirdparties/mkl/lib/libmkl_sequential.a /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/thirdparties/mkl/lib/libmkl_core.a /home/qubingxin/qbx/source_code/paddle_internal_release_tools/idl/paddle/thirdparties/python27-gcc482/lib/libpython2.7.so /home/qubingxin/qbx/source_code/paddle_internal_release_tools/third-64/glog/lib/libglog.a /home/qubingxin/qbx/source_code/paddle_internal_release_tools/third-64/gflags/lib/libgflags.a -lpthread -Xlinker -end-group
```

临时解决方法 ：

* 在执行sh build.sh cpu nonrdma命令前,  export PATH=/opt/compiler/gcc-4.8.2/bin/:$PATH到shell环境变量。

如果有问题请继续反馈，  :-)

**Comment by backyes** [comment]
这里先close
