### ISSUE TITLE
se_resnet_152 multi-gpu profile

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#8661]
## profile model
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/se_resnext.py

### single card
![image](https://user-images.githubusercontent.com/3048612/36786241-aac87316-1cc0-11e8-8f10-a074981d8862.png)
￼

### two cards with nccl
![image](https://user-images.githubusercontent.com/3048612/36786080-09c4adcc-1cc0-11e8-8414-3a9c90785cf8.png)

### two cards without nccl
![image](https://user-images.githubusercontent.com/3048612/36786910-1477a35c-1cc3-11e8-88de-ca7429eac625.png)

some simple conclusion:
1, there is a huge gap between forward and backward when nccl is used
2, there is a huge gap between each step.

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/issues/8624
earlier profile result:
>paddle-P40-1-card(无内存优化), max batch size=10, speed(fp+bp): 1.00sec
paddle-P40-1-card(有内存优化), max batch size=25, speed(fp+bp): 1.90sec
paddle-P40-8-card(无内存优化), max batch size=80, speed(fp+bp): 2.35sec
pytorch-P40-1-card, max batch size=48, speed(fp+bp): 2.06sec
pytorch-P40-8-card, max batch size=384, speed(fp+bp): 2.77sec

**Comment by tonyyang-svail** [comment]
@jacquesqiao could you post the link to the profiling script?

**Comment by jacquesqiao** [comment]
@tonyyang-svail  https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/se_resnext.py I use this model.
