### ISSUE TITLE
server.log报错

### ISSUE THREAD

**Issue by hijkzzz** [PaddlePaddle/Paddle#8670]
Thu Mar  1 11:05:13 2018[1,44]<stderr>:*********************Shell Script Stack Trace********************
Thu Mar  1 11:05:13 2018[1,44]<stderr>: @: [./log.sh: 61] check_return
Thu Mar  1 11:05:13 2018[1,44]<stderr>: @: [./start_server.sh: 34] main
Thu Mar  1 11:05:13 2018[1,44]<stderr>:
Thu Mar  1 11:05:13 2018[1,44]<stderr>:+ exit 1
Thu Mar  1 11:05:13 2018[1,38]<stderr>:WARNING: Logging before InitGoogleLogging() is written to STDERR
Thu Mar  1 11:05:13 2018[1,38]<stderr>:F0301 11:05:13.781890 50448 hl_dso_loader.cc:97] Check failed: nullptr != *dso_handle Failed to find cuda library: libcudart.so
Thu Mar  1 11:05:13 2018[1,38]<stderr>:Please specify its path correctly using one of the following ideas: 
Thu Mar  1 11:05:13 2018[1,38]<stderr>:Idea 1. set cuda and cudnn lib path at runtime. http://www.paddlepaddle.org/doc/ui/cmd_argument/argument_outline.html 
Thu Mar  1 11:05:13 2018[1,38]<stderr>:For instance, issue command: paddle train --use_gpu=1 --cuda_dir=/usr/local/cudnn/lib --cudnn_dir=/usr/local/cudnn/lib ...
Thu Mar  1 11:05:13 2018[1,38]<stderr>:Idea 2. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
Thu Mar  1 11:05:13 2018[1,38]<stderr>:For instance, issue command: export LD_LIBRARY_PATH=... 
Thu Mar  1 11:05:13 2018[1,38]<stderr>:Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. However, @Idea 1always work well.
Thu Mar  1 11:05:13 2018[1,47]<stderr>:WARNING: Logging before InitGoogleLogging() is written to STDERR
Thu Mar  1 11:05:13 2018[1,47]<stderr>:F0301 11:05:13.787817 41376 hl_dso_loader.cc:97] Check failed: nullptr != *dso_handle Failed to find cuda library: libcudart.so
Thu Mar  1 11:05:13 2018[1,47]<stderr>:Please specify its path correctly using one of the following ideas: 
Thu Mar  1 11:05:13 2018[1,47]<stderr>:Idea 1. set cuda and cudnn lib path at runtime. http://www.paddlepaddle.org/doc/ui/cmd_argument/argument_outline.html 
Thu Mar  1 11:05:13 2018[1,47]<stderr>:For instance, issue command: paddle train --use_gpu=1 --cuda_dir=/usr/local/cudnn/lib --cudnn_dir=/usr/local/cudnn/lib ...
Thu Mar  1 11:05:13 2018[1,47]<stderr>:Idea 2. set environment variable LD_LIBRARY_PATH on Linux or DYLD_LIBRARY_PATH on Mac OS. 
Thu Mar  1 11:05:13 2018[1,47]<stderr>:For instance, issue command: export LD_LIBRARY_PATH=... 
Thu Mar  1 11:05:13 2018[1,47]<stderr>:Note: After Mac OS 10.11, using the DYLD_LIBRARY_PATH is impossible unless System Integrity Protection (SIP) is disabled. However, @Idea 1always work well.
Thu Mar  1 11:05:13 2018[1,47]<stderr>:*** Check failure stack trace: ***
Thu Mar  1 11:05:13 2018[1,47]<stderr>:./start_server.sh: line 33: 41376 Aborted                 GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_pserver2 --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --nics=${nics} ${server_arg} --rdma_tcp=${rdma_tcp} --comment=$comment
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ check_return 'paddle_pserver2 failed'
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ '[' 134 -ne 0 ']'
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ echo '[./start_server.sh : 34] [main]'
Thu Mar  1 11:05:13 2018[1,47]<stderr>:[./start_server.sh : 34] [main]
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ echo '[FATAL]: paddle_pserver2 failed'
Thu Mar  1 11:05:13 2018[1,47]<stderr>:[FATAL]: paddle_pserver2 failed
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ get_stack
Thu Mar  1 11:05:13 2018[1,47]<stderr>:+ set +x
Thu Mar  1 11:05:13 2018[1,47]<stderr>:

**Comment by hijkzzz** [comment]
目前猜测可能是非cpu集群pserver用gpu的方式启动了

**Comment by typhoonzero** [comment]
应该是receiver配置的问题

**Comment by wuliangradi** [comment]
@hijkzzz 最后是因为什么原因呢
