### ISSUE TITLE
paddle.v2.layer.addto 支持自动识别通道数么？ paddle layer 的 size = W×H 还是 C×W×H？

### ISSUE THREAD

**Issue by shboy** [PaddlePaddle/Paddle#8672]
![default](https://user-images.githubusercontent.com/24290262/36828091-867eb38e-1d52-11e8-9292-2b85ce4b9eaf.JPG)
见上图
目的： 将fc的结果 reshape 成 c=2 w=234 h=236的图片 和 main_output（ c=2 w=234 h=236）相加

**Comment by shboy** [comment]
疑惑之处：
我加了第3句 resize 程序才调通
删了第二句 会报assert layer_size ！= input_layer.size 的错 见下图最后两行
![2](https://user-images.githubusercontent.com/24290262/36828275-c52af8f8-1d53-11e8-84e5-81e96992484e.jpg)
问题：
1. main_output 的 size 是 2*234*236 还是 234*236？
2. paddle中层的size是 W*H 还是 C*W*H？
3. 我这样resize对么？
4. 若 3 是对的， 那么 main_output已知是 c=2 w=234 h=236 的图片 为啥我还需要resize？

**Comment by qingqing01** [comment]
1. Paddle layer的size是C*H*W。
2. 这里`addto`之前的`main_output` size是多少呢？ 

```
main_output = paddle.layer.addto([main_output, h1], ...)
```

addto需要保证相加的两个值的维度完全相同。在老Paddle里数据结构是Matrix，即Matrix的height、width都需要相同。

**Comment by shboy** [comment]
@qingqing01 main_output  c = 2, h = 236, w = 234, size = 110448

**Comment by typhoonzero** [comment]
老paddle指的是paddle.v2。
@qingqing01 提到的数据结构是只paddle内部的数据结构实现。

看描述，如果addto之前需要resize成234*246，那么main_output 应该也是234*246的。

**Comment by shboy** [comment]
ok了 我是代码写错了的问题 排查出来了 @qingqing01  @typhoonzero
