### ISSUE TITLE
fluid vs pytorch profile on se_resnext152

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#8677]
### Setup
[Script](https://github.com/jacquesqiao/benchmark/blob/c92cda7c68bdcd1bed46c4fe2731a9bd912f7198/image_resnet/fluid/se_resnext152_parallel.py)
batch_size: 25
card_num: 1

|               | Speed           | Memory   |
|---------------|-----------------|----------|
| Fluid         | 1.95 sec/iter  | 18341 MB |
| PyTorch       | 1.154 sec/iter | 13359 MB |
| Fluid/PyTorch | 1.68            | 1.3729   |

**Comment by tonyyang-svail** [comment]
@jacquesqiao could you please provide the script and the command of this profiling?

**Comment by jacquesqiao** [comment]
@tonyyang-svail the profile script for this issue is https://github.com/dzhwinter/benchmark/pull/83, the script can run in our dev docker container, but have something to do: https://github.com/dzhwinter/benchmark/pull/83#issue-172168024
