### ISSUE TITLE
Logging using glog

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#869]
We created `paddle/util/Logging.h` as a wrapper of glog a while ago with the mind that Paddle might need to support embedded systems without glog in the future.  Indeed, a more convenient way to logging on embedded systems might be to change glog other than wrapping glog within Paddle.

Let me turn to use glog directly and make it easier to go through building targets in Bazel BUILD files.

**Comment by reyoung** [comment]
@gangliao are removing `glog` and `gflags` in cmake now.
