### ISSUE TITLE
fluid分布式gpu版本出现异常cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: unknown error at [/paddle/paddle/fluid/platform/gpu_info.cc:32]

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#8700]
使用了1卡的情况下（共8卡，有两卡正在被其他进程使用），出现下面的异常

```bash
Traceback (most recent call last):
  File "trainer.py", line 287, in <module>
    train_main(use_cuda=True, is_sparse=True)
  File "trainer.py", line 280, in train_main
    exe.run(pserver_startup)
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 292, in run
    self.executor.run(program.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: unknown error at [/paddle/paddle/fluid/platform/gpu_info.cc:32]
PaddlePaddle Call Stacks: 
0       0x7f2a2bd12c56p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f2a2c928016p paddle::platform::GetCUDADeviceCount() + 246
2       0x7f2a2c92889fp paddle::platform::SetDeviceId(int) + 31
3       0x7f2a2c80a8a4p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 116
4       0x7f2a2bd9a32ep paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 1214
5       0x7f2a2bd27adbp _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEIRKNS4_11ProgramDescEPNS4_5ScopeEibbEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vISO_S8_SA_ibbEISB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 555
6       0x7f2a2bd21864p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
7       0x7f2a7fa42631p PyEval_EvalFrameEx + 24497
8       0x7f2a7fa43bcep PyEval_EvalCodeEx + 2190
9       0x7f2a7fa4220ap PyEval_EvalFrameEx + 23434
10      0x7f2a7fa43bcep PyEval_EvalCodeEx + 2190
11      0x7f2a7fa4220ap PyEval_EvalFrameEx + 23434
12      0x7f2a7fa43bcep PyEval_EvalCodeEx + 2190
13      0x7f2a7fa43ce2p PyEval_EvalCode + 50
14      0x7f2a7fa639e0p PyRun_FileExFlags + 176
15      0x7f2a7fa63bbfp PyRun_SimpleFileExFlags + 239
16      0x7f2a7fa79454p Py_Main + 3188
17      0x7f2a7ed2dcddp __libc_start_main + 253
18            0x400649p
```

**Comment by xymyeah** [comment]
gpu机器上只有当前job进程时也还是这样的错误

**Comment by chengduoZH** [comment]
您是用fluid分布式gpu版本在单机单卡上跑  是吗？

**Comment by xymyeah** [comment]
pserver和trainer是分开的，分别在不同的机器上

**Comment by typhoonzero** [comment]
@xymyeah 这个问题现在还存在么？

**Comment by xymyeah** [comment]
这个问题还存在

Traceback (most recent call last):
  File "trainer.py", line 287, in <module>
    train_main(use_cuda=True, is_sparse=True)
  File "trainer.py", line 283, in train_main
    train_loop(t.get_trainer_program())
  File "trainer.py", line 234, in train_loop
    exe.run(framework.default_startup_program())
  File "/usr/local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 349, in run
    self.executor.run(program_cache.desc, scope, 0, True, True)
paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:32]
PaddlePaddle Call Stacks:
0       0x7fc1dde62e36p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7fc1deac1a96p paddle::platform::GetCUDADeviceCount() + 246
2       0x7fc1deac2d9fp paddle::platform::SetDeviceId(int) + 31
3       0x7fc1de972454p paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, boost::variant<paddle::platform::CUDAPlace, paddle::platform::CPUPlace, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_, boost::detail::variant::void_> const&) + 164
4       0x7fc1ddef347ep paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool) + 1086
5       0x7fc1ddef44a0p paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool) + 64
6       0x7fc1dde7850bp _ZZN8pybind1112cpp_function10initializeIZNS0_C1IvN6paddle9framework8ExecutorEIRKNS4_11ProgramDescEPNS4_5ScopeEibbEINS_4nameENS_9is_methodENS_7siblingEEEEMT0_FT_DpT1_EDpRKT2_EUlPS5_S8_SA_ibbE_vISO_S8_SA_ibbEISB_SC_SD_EEEvOSF_PFSE_SH_ESN_ENUlRNS_6detail13function_callEE1_4_FUNESV_ + 555
7       0x7fc1dde71c34p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
8       0x7fc2313f6631p PyEval_EvalFrameEx + 24497
9       0x7fc2313f7bcep PyEval_EvalCodeEx + 2190
10      0x7fc2313f620ap PyEval_EvalFrameEx + 23434
11      0x7fc2313f7bcep PyEval_EvalCodeEx + 2190
12      0x7fc2313f620ap PyEval_EvalFrameEx + 23434
13      0x7fc2313f7bcep PyEval_EvalCodeEx + 2190
14      0x7fc2313f620ap PyEval_EvalFrameEx + 23434
15      0x7fc2313f7bcep PyEval_EvalCodeEx + 2190
16      0x7fc2313f7ce2p PyEval_EvalCode + 50
17      0x7fc2314179e0p PyRun_FileExFlags + 176
18      0x7fc231417bbfp PyRun_SimpleFileExFlags + 239
19      0x7fc23142d454p Py_Main + 3188
20      0x7fc2306e1cddp __libc_start_main + 253
21            0x400649p

**Comment by Yancey1989** [comment]
看报错像是环境问题引起的，可以Check下：
1. 单机是否可以运行
1. 编译用的CUDA版本和runtime的CUDA版本是否一致
1. 如果是在Docker中运行，是否正确设置了`docker run --privileged `以及在Container内GPU设备是否可以找到？

**Comment by dzhwinter** [comment]
>其中pserver在非gpu机器上，trainer在GPU机器上，
pserver（pserver在非gpu的机器上）和trainer都会出现这样的异常：

trainer上如果有GPU的话，抛这个异常请检查一下 driver version. 

> paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at [/paddle/paddle/fluid/platform/gpu_info.cc:32]

**Comment by xymyeah** [comment]
pserver在非gpu上，pserver会报这个错误：paddle.fluid.core.EnforceNotMet: cudaGetDeviceCount failed in paddle::platform::GetCUDADeviceCount: CUDA driver version is insufficient for CUDA runtime version at 
要求pserver也必须在gpu机器上运行吗？

**Comment by xymyeah** [comment]
trainer是有gpu的，是cuda8 cudnn5

**Comment by Yancey1989** [comment]
> 要求pserver也必须在gpu机器上运行吗？

没有要求PServer必须在GPU上运行，但需要设置为CPUPlace

**Comment by xymyeah** [comment]
如果pserver运行在gpu机器上就设置GPUPlace，如果pserver运行在cpu机器上就设置CPUPlace？
还是说只要是pserver就设置为CPUPlace？

**Comment by typhoonzero** [comment]
pserver执行的计算比较少，一般使用CPU足够，设置为GPU反而会增加数据从CPU拷贝到GPU的时间。

**Comment by xymyeah** [comment]
好的，thanks

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.

**Comment by tcwm1** [comment]
docker增加privileged相关参数问题得到解决
