### ISSUE TITLE
安装支持Python3吗

### ISSUE THREAD

**Issue by lshfong** [PaddlePaddle/Paddle#8701]
安装支持Python3吗，还是只支持在Python2.7环境下安装开发

**Comment by wangpeiing** [comment]
目前不支持Python3

**Comment by linbaicome** [comment]
3个月过去了 还是不支持python3吗？

**Comment by usafchn** [comment]
同问

**Comment by chengduoZH** [comment]
duplicate with https://github.com/PaddlePaddle/Paddle/issues/9174
