### ISSUE TITLE
怎么解析paddle的模型？

### ISSUE THREAD

**Issue by lxy890123** [PaddlePaddle/Paddle#8707]
paddle模型的权重存放在.tar.gz文件中，而模型的定义和参数目前看来是写在.py文件（例如vgg.py），请问如何获得layer的参数和权重，以及layer之间的连接关系？

**Comment by chengduoZH** [comment]
获取layer的参数和权重：
http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#layeroutput
layer之间的链接关系很你定义网络的顺序有关

**Comment by chengduoZH** [comment]
Close due to low activity, please feel free to reopen it.
