### ISSUE TITLE
使用image_classification示例程序里的alexnet报这种错

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#8714]
使用image_classification示例程序里的alexnet报这种错：
```
Pass 2, Batch 0, Cost 32.000000, {'classification_error_evaluator': 0.5}
Thread [140578746316544] Forwarding __crmnorm_0__, 
*** Aborted at 1519988183 (unix time) try "date -d @1519988183" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fdabba5df57) received by PID 37439 (TID 0x7fdb0a3cb700) from PID 18446744072562794327; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7fdabba5df57 paddle::TensorCpuApply<>()
    @     0x7fdabba5a345 paddle::CrossMapNormal<>()
    @     0x7fdabba5fc5c paddle::CrossMapNormalFunc<>::calc()
    @     0x7fdabb920628 paddle::CMRProjectionNormLayer::forward()
    @     0x7fdabb9d9e6d paddle::NeuralNetwork::forward()
    @     0x7fdabb9dab83 paddle::GradientMachine::forwardBackward()
    @     0x7fdabbc00994 GradientMachine::forwardBackward()
    @     0x7fdabb87ec99 _wrap_GradientMachine_forwardBackward
    @     0x7fdb0a4c03a3 PyEval_EvalFrameEx
    @     0x7fdb0a4c2130 PyEval_EvalCodeEx
    @     0x7fdb0a4c04a1 PyEval_EvalFrameEx
    @     0x7fdb0a4c2130 PyEval_EvalCodeEx
    @     0x7fdb0a4c04a1 PyEval_EvalFrameEx
    @     0x7fdb0a4c2130 PyEval_EvalCodeEx
    @     0x7fdb0a4c04a1 PyEval_EvalFrameEx
    @     0x7fdb0a4c2130 PyEval_EvalCodeEx
    @     0x7fdb0a4c04a1 PyEval_EvalFrameEx
    @     0x7fdb0a4c2130 PyEval_EvalCodeEx
    @     0x7fdb0a4c2242 PyEval_EvalCode
    @     0x7fdb0a4dc62c run_mod
    @     0x7fdb0a4dc700 PyRun_FileExFlags
    @     0x7fdb0a4ddc0c PyRun_SimpleFileExFlags
    @     0x7fdb0a4ef4cc Py_Main
    @       0x318ae1ecdd (unknown)
^C^C
Aborted (core dumped)
```

**Comment by Kayven** [comment]
上面是自己的图片样本，用flowers数据集，报错如下：
Pass 0, Batch 3, Cost 63.000000, {'classification_error_evaluator': 0.984375}

Pass 0, Batch 4, Cost 62.000000, {'classification_error_evaluator': 0.96875}

*** Aborted at 1519990737 (unix time) try "date -d @1519990737" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGFPE (@0x7f34bf26be70) received by PID 27645 (TID 0x7f338e1fc700) from PID 18446744072621571696; stack trace: ***

    @       0x318b20f500 (unknown)

    @     0x7f34bf26be70 sgemm_kernel_SANDYBRIDGE
Floating point exception (core dumped)

**Comment by chengduoZH** [comment]
您是在什么设备上跑的，以及您跑的模型或者模型连接发一下？

**Comment by yeyupiaoling** [comment]
@Kayven 
检查你的数据集是否有问题，看报错应该是浮点异常，修改超参数是否有效？你用的是CPU还是GPU

**Comment by chengduoZH** [comment]
可能是梯度有异常，建议将检查一下梯度信息

**Comment by chengduoZH** [comment]
@yeyupiaoling 梯度可能有Nan。

> *** Aborted at 1519988183 (unix time) try "date -d @1519988183" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7fdabba5df57) received by PID 37439 (TID 0x7fdb0a3cb700) from PID 18446744072562794327; stack trace: ***
    @       0x318b20f500 (unknown)

出现这种错误极大可能是数据（forward数据或者backward数据）有问题，导致计算过程中出错

**Comment by yeyupiaoling** [comment]
@chengduoZH 
所以加上`BN`层，可以拟制梯度弥散。

**Comment by chengduoZH** [comment]
@yeyupiaoling BN是有这种作用的
