### ISSUE TITLE
使用paddlepaddle进行机器翻译训练，训练集的dict文件如何生成？

### ISSUE THREAD

**Issue by yanmengqi** [PaddlePaddle/Paddle#8717]
目前想尝试使用paddlepaddle进行机器翻译训练，但是不知道自己准备的训练集的话，src.dict和trg.dict如何生成？paddle里有提供相关命令吗？还是需要自己在数据预处理的时候处理好？

**Comment by chengduoZH** [comment]
请参考：https://github.com/PaddlePaddle/book/blob/develop/08.machine_translation/README.cn.md
