### ISSUE TITLE
使用jupyter运行第一个样例01.fit_a_line 报错！请求帮助

### ISSUE THREAD

**Issue by cdliheng** [PaddlePaddle/Paddle#8721]
安装docker和paddlepaddle都正常，启动paddlepaddle/book 也正常
但是进入README.cn.ipynb后点击执行按钮，
到paddle.init(use_gpu=False, trainer_count=1) 这句话时弹出错误提示：
“The kernel appears to have died. It will restart automatically.”

后台报错信息
[I 05:42:34.183 NotebookApp] 302 GET / (172.17.0.1) 0.66ms
[I 05:42:43.970 NotebookApp] Writing notebook-signing key to /root/.local/share/jupyter/notebook_secret
[W 05:42:43.973 NotebookApp] Notebook 01.fit_a_line/README.cn.ipynb is not trusted
[I 05:42:45.933 NotebookApp] Kernel started: cd1df3d8-56ba-4acf-8c6b-bdd51915ce1e
[I 05:42:45.947 NotebookApp] 302 GET /notebooks/01.fit_a_line/image/train_and_test.png (172.17.0.1) 4.33ms
[I 05:42:45.954 NotebookApp] 302 GET /notebooks/01.fit_a_line/image/ranges.png (172.17.0.1) 6.63ms
[I 05:42:45.963 NotebookApp] 302 GET /notebooks/01.fit_a_line/image/predictions.png (172.17.0.1) 1.31ms
[I 05:42:47.446 NotebookApp] Adapting to protocol v5.1 for kernel cd1df3d8-56ba-4acf-8c6b-bdd51915ce1e
[I 05:43:27.926 NotebookApp] KernelRestarter: restarting kernel (1/5), keep random ports
WARNING:root:kernel cd1df3d8-56ba-4acf-8c6b-bdd51915ce1e restarted

**Comment by kuke** [comment]
你手动重启一下kernel (点击restart the kernel按钮)，然后再运行试一下

**Comment by cdliheng** [comment]
点击了，还是不行，一样报错。。。 @kuke

**Comment by kuke** [comment]
@cdliheng https://github.com/PaddlePaddle/Paddle/issues/8133 这里有个类似的issue，请参考

**Comment by cdliheng** [comment]
我是用docker安装的，完全按照教程来的。 @kuke

**Comment by cdliheng** [comment]
在命令行下运行“快速启动”的样例：
docker run --rm -v ~/workspace:/workspace paddlepaddle/paddle:latest python /workspace/housing.py
不会报错，也没有任何输出，回车后直接又到下一个提示符了。。。。

**Comment by kuke** [comment]
我刚测试了最新的book镜像，并没有问题。你检查一下docker是否正常安装？

**Comment by cdliheng** [comment]
@kuke 同样的安装方法和顺序，我在win7旗舰版上安装运行都没任何问题。但是到win10专业版上，安装也没问题，但是就是运行报错，我在想是不是操作系统的问题？

**Comment by kuke** [comment]
@cdliheng 请在mac或者linux下测试，win上并没有验证过

**Comment by cdliheng** [comment]
晕了，我只有WINDOWS系统啊，怎么办啊？郁闷

**Comment by kuke** [comment]
可以考虑装个ubuntu的双系统

**Comment by cdliheng** [comment]
@kuke 我操作不来linux啊，我不是开发人员，我是产品经理，技术基础比较薄弱的，唉，该怎么办啊

**Comment by kuke** [comment]
只能向身边的技术人员求助先解决系统的问题了，对于有安装系统经验的来说并不是个很难的事情

**Comment by cdliheng** [comment]
恩，只有这样了，对了，还想问个问题，mac下怎么安装paddlepaddle/book呢？教程里没有介绍 @kuke

**Comment by kuke** [comment]
mac与linux无区别，参照book的readme按步骤执行就行了

**Comment by cdliheng** [comment]
是不是mac与linux下，也先安装docker？然后执行docker run -d -p 8888:8888 paddlepaddle/book

**Comment by kuke** [comment]
对的，需要先安装docker

**Comment by cdliheng** [comment]
谢谢，我试试

**Comment by yeyupiaoling** [comment]
@cdliheng 

请确认您的电脑是否支持AVX指令集，查看命令如下：
```
if cat /proc/cpuinfo | grep -i avx; then echo Yes; else echo No; fi
```

**Comment by cdliheng** [comment]
@yeyupiaoling 您好，请问这个命令是在哪里运行啊？我在cmd里面运行不了呢。。。

**Comment by cdliheng** [comment]
@yeyupiaoling 我查了下电脑CPU是Intel Celeron 3855U 1.6Ghz ,是不是这处理器不支持AVX哦？

**Comment by luotao1** [comment]
直接cmd输入 `cat /proc/cpuinfo | grep -i avx`，如果有结果表示yes，即支持AVX；如果是空表示No，即不支持AVX

**Comment by kuke** [comment]
@cdliheng book镜像能否运行与cpu是否支持avx没有关系，上面给的命令也是linux系统下的命令。建议还是先解决系统的问题，要么用win7，要么装linux系统。

**Comment by yeyupiaoling** [comment]
@kuke 
看情况他的镜像是正常运行的，只是在初始化paddlepaddle的时候报错，所以我觉得应该考虑avx指令集问题

**Comment by cdliheng** [comment]
@kuke @yeyupiaoling 你好，镜像运行正常，确实是我CPU不支持AVX，现在该怎么办呢？

**Comment by yeyupiaoling** [comment]
@cdliheng 
两种方法，一种是下载官方的navx版本的docker，另一种是自行构建docker镜像

**Comment by luotao1** [comment]
@Yancey1989 请问paddlepaddle/book能否有一个noavx的镜像呢？谢谢

**Comment by Yancey1989** [comment]
noavx的镜像是可以在不支持AVX的CPU上运行，稍后编译结束后下载运行下试试吧。

**Comment by Yancey1989** [comment]
It's build failed on develop branch #8854  we need to fix it first.

**Comment by cdliheng** [comment]
@yeyupiaoling @Yancey1989 我已经在win10上安装好了docker，现在就等你们no-avx版本的paddlepaddle镜像，拉下来试试了，对吧？实在抱歉，这方面我比较菜鸟

**Comment by cdliheng** [comment]
@yeyupiaoling @Yancey1989 您好，请问noavx的镜像地址可以公布了吗？

**Comment by yeyupiaoling** [comment]
@cdliheng 
自己编译吧，[教程](http://blog.csdn.net/qq_33200967/article/details/79071926#%E5%9C%A8%E6%9C%AC%E5%9C%B0%E7%BC%96%E8%AF%91%E7%94%9F%E6%88%90%E5%AE%89%E8%A3%85%E5%8C%85)

**Comment by luotao1** [comment]
@cdliheng 地址见：http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/pip_install_cn.html#id18
已经有cpu_noavx_openblas的版本了。

**Comment by yeyupiaoling** [comment]
@luotao1 
这个是要下载的，如果再服务器上就不行了，使用wget命令下载不了

**Comment by cdliheng** [comment]
@luotao1 我是win10装的docker，您提供这个地址能安装吗？

**Comment by yeyupiaoling** [comment]
@cdliheng 
```
paddlepaddle/paddle:latest-noavx-openblas
```
国内应该是
```
docker.paddlepaddlehub.com/paddle:latest-noavx-openblas
```

**Comment by cdliheng** [comment]
@yeyupiaoling 太感谢了，我试试，万分感谢

**Comment by Yancey1989** [comment]
在book镜像库中增加了noavx版本
```bash
paddlepaddle/book:latest-noavx-openblas
```
国内镜像：
```bash
docker.paddlepaddlehub.com/book:latest-noavx-openblas
```
