### ISSUE TITLE
Limit the threads of thread pool

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#8724]
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/framework/threadpool.cc#L33
When the program runs in Docker, the number of threads is the number of CPU the host and not the number of CPU in the container.

**Comment by helinwang** [comment]
Maybe this will help? https://github.com/moby/moby/issues/31424#issuecomment-283133048

**Comment by Yancey1989** [comment]
Maybe another way is to use the env variable to determinate the thread numbers, looks like more general.

**Comment by gongweibao** [comment]
May we need an ENV variable to initial thread_num in a container.
