### ISSUE TITLE
Repair doc format problem

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#8733]
Please see here:
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/cmd_parameter/detail_introduction_en.md
![image](https://user-images.githubusercontent.com/35982308/36957764-b17c9174-2071-11e8-85ff-ae70d791a18a.png)
and the corresponding paddlepaddle.org page
![image](https://user-images.githubusercontent.com/35982308/36957809-0c13155e-2072-11e8-9af3-013b7887c45d.png)

Please repair it, thank you!

**Comment by cs2be** [comment]
is it possible to change this page to an RST?  Or manually fix the issue on the MD itself.  Since Sphinx has issues supporting MD tables, to fix that table bug we had to change the code to generate HTML from MD directly from PPO.  As a result, sphinx commands do not work anymore in MD files.

**Comment by luotao1** [comment]
I will try to fix the issue on the MD itself.
>  Since Sphinx has issues supporting MD tables

But this md doesn't has tables.
