### ISSUE TITLE
the master branch build from source error

### ISSUE THREAD

**Issue by jinfagang** [PaddlePaddle/Paddle#8741]
I have tried so many times but same error always happen:

```
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 10%] No update step for 'extern_eigen3'
[ 10%] No patch step for 'extern_eigen3'
[ 10%] No configure step for 'extern_eigen3'
[ 10%] No build step for 'extern_eigen3'
[ 10%] No install step for 'extern_eigen3'
[ 10%] No test step for 'extern_eigen3'
[ 10%] Completed 'extern_eigen3'
[ 10%] Built target extern_eigen3
make: *** [all] Error 2
```
Is this error about eigen3 or CMakeList file problem? I have already installed eigen environment why still build from source and always return a build error. I think this kind of error should throw a message rather than just build failed.

**Comment by pkuyym** [comment]
Please paste more logs.

**Comment by chengduoZH** [comment]
该issue长时间咩有回复，暂时先关闭了。
