### ISSUE TITLE
多个输出报错 it != layerMap_.end() Unknown layer

### ISSUE THREAD

**Issue by yjj19920505** [PaddlePaddle/Paddle#8749]
我们想做层次化分类，所以需要同时训练多个独立分类器，需要同时定义多个分类器，但是如下代码会报错F0305 18:10:10.509027 127905 NeuralNetwork.h:94] Check failed: it != layerMap_.end() Unknown layer output2
该怎么解决呢？

data = paddle.layer.data("word1",
    paddle.data_type.integer_value_sequence(dict_dim))
emb = paddle.layer.embedding(name = "emb_word", input=data, size=64)
conv3 = paddle.networks.sequence_conv_pool(input=emb, context_len=3, hidden_size=32, name = "conv31")
conv32 = paddle.networks.sequence_conv_pool(input=emb, context_len=3, hidden_size=32, name = "conv32")
output = paddle.layer.fc(name = "output", input=[conv3], size=class_dim, act=paddle.activation.Softmax())
lbl = paddle.layer.data("label1", paddle.data_type.integer_value(int(class_dim)))
cost = paddle.layer.classification_cost(name = "cost1", input=output, label=lbl)

output2 = paddle.layer.fc(name = "output2", input=[conv32], size=class_dim, act=paddle.activation.Softmax())
lbl2 = paddle.layer.data("label2", paddle.data_type.integer_value(int(class_dim)))
cost2 = paddle.layer.classification_cost(name = "cost2", input=output2, label=lbl2)

**Comment by yjj19920505** [comment]
我发现去掉cost2 = paddle.layer.classification_cost(name = "cost2", input=output2, label=lbl2)这句后就不会报错，是不能同时存在多个cost的定义吗？

**Comment by yjj19920505** [comment]
https://github.com/PaddlePaddle/Paddle/issues/4191

**Comment by sherlockjin** [comment]
解决了吗

**Comment by yjj19920505** [comment]
恩，解决了啊
