### ISSUE TITLE
DeepASR profile timeline

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#8750]
![image](https://user-images.githubusercontent.com/3048612/36969905-c13f963a-20a1-11e8-9a9e-67b878a4c159.png)

## conclution
for DeepASR model, the gap between steps is not so much, the most time consuming part is LSTMP operators.

**Comment by kuke** [comment]
This result is consistent with the profiling result in [#637](https://github.com/PaddlePaddle/models/issues/637)
