### ISSUE TITLE
how to make parameter(layer) untrainable in fluid? 

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [PaddlePaddle/Paddle#8751]
In tensorflow, we can set variable untrainable by setting parameter's attribute (trainable=False)
Do we have similar API In fluid?

**Comment by gongweibao** [comment]
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/nn.py#L80

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks a lot !
` 
param_attr = ParamAttr(trainable=target)
fc1 = fluid.layers.fc(input=state, size=128, act='relu', param_attr=param_attr)
fc2 = fluid.layers.fc(input=fc1, size=64, act='relu', param_attr=param_attr)
value = fluid.layers.fc(input=fc2, size=param.action_dim, param_attr=param_attr)`
