### ISSUE TITLE
[Speed] IO recordio format support

### ISSUE THREAD

**Issue by dzhwinter** [PaddlePaddle/Paddle#8763]
Currently, we use the python ndarray preprocess and read the content into LoDTensor, it is quite low efficient for training. When we head for the recordio format, we encounter a problem that the go version recordio implementation will introduce the go runtime, which will take over our threadpool with the goroutine. We thought it is too heavy since we only use the recordio for reading.

**Comment by helinwang** [comment]
Can you add some explanation about this issue?

**Comment by dzhwinter** [comment]
This issue is a proposal, which has been implemented in the latest develop branch.
