### ISSUE TITLE
Any documentation on adding a custom layer in v2 api?

### ISSUE THREAD

**Issue by lispc** [PaddlePaddle/Paddle#8769]
I want to add a custom layer in v2 api, including cuda code, cpp code, python wrapper and tests. Is there any recommended documentation to read to do this?
Thx.

**Comment by guoshengCS** [comment]
Please reference to https://github.com/PaddlePaddle/Paddle/blob/develop/doc/v2/dev/new_layer_cn.rst for new layers in V2.

**Comment by lispc** [comment]
that's what i am looking for. thanks
