### ISSUE TITLE
厂内测试机安装docker. 

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#8779]
厂内的测试机，linux 内核、centos 版本，都和当前paddle 发布的版本不一致.
有通用的解决办法吗？

**Comment by guoshengCS** [comment]
能够安装docker用docker的话应该就不需要考虑环境版本不一致了吧。

**Comment by VamWolf** [comment]
主要是docker 装不了. 系统版本低的...

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开。
