### ISSUE TITLE
image_classification不收敛

### ISSUE THREAD

**Issue by yuanghbdbj** [PaddlePaddle/Paddle#8789]
用的标准模型alexnet、googlenet进行分类，都不收敛，40%左右错误率。是不是这些问题：1）样本比较少，只有5000；2）都是长方形图片，375*2300（平均，大小不一）；3）加了bn层，设置dropout rate 0.5；4）其他参数不对
如果是第2、3、4或相关的问题，该怎么解决或调试呢？

**Comment by guoshengCS** [comment]
主要还是数据较少吧，另外对于长方形图片paddle包含图片处理的代码 https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/v2/image.py#L213 ，另外dropout rate貌似有点过大了

**Comment by yeyupiaoling** [comment]
@yuanghbdbj 
减少学习率有用吗？

**Comment by yeyupiaoling** [comment]
@yuanghbdbj 尝试去掉BN层试试。使用image.py来随机裁剪。

**Comment by chengduoZH** [comment]
改issue长时间没有得到反馈，可以先关闭了，如果疑问请再打开
