### ISSUE TITLE
  Could not find a version that satisfies the requirement recordio>=0.1.0 (from paddlepaddle==0.10.0) (from versions: ) No matching distribution found for recordio>=0.1.0 (from paddlepaddle==0.10.0)

### ISSUE THREAD

**Issue by VamWolf** [PaddlePaddle/Paddle#8799]
Could not find a version that satisfies the requirement recordio>=0.1.0 (from paddlepaddle==0.10.0) (from versions: )
No matching distribution found for recordio>=0.1.0 (from paddlepaddle==0.10.0)

改了whl  和系统支持的一致，缺这个文件，求处理

**Comment by guoshengCS** [comment]
请试着自行安装下recordio https://pypi.python.org/pypi/recordio

**Comment by VamWolf** [comment]
thx, 下载安装已解决. 继续安装，出现
    Invalid declaration of or reference to symbol `trim' at (^) [initially seen at (^)]
    error: Command "/usr/bin/g77 -g -Wall -fno-second-underscore -fPIC -O3 -funroll-loops -Ibuild/src.linux-x86_64-2.7 -I/home/work/.jumbo/lib/python2.7/site-packages/numpy/core/include -I/home/work/.jumbo/include/python2.7 -c -c scipy/io/_test_fortran.f -o build/temp.linux-x86_64-2.7/scipy/io/_test_fortran.o" failed with exit status 1
    
    ----------------------------------------
Command "/home/work/.jumbo/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ePg76q/scipy/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-klPzG7-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-ePg76q/scipy/

**Comment by guoshengCS** [comment]
貌似是其他一些python依赖包安装的问题，麻烦还请把这些依赖试着手动安装下吧。

**Comment by VamWolf** [comment]
终于安装成功了，总体来说，比paddle v1 的时候从源码安装还是简单了不少. 
期间遇到几个问题
1. Could not find any downloads that satisfy the requirement paddlepaddle. No distributions at all found for paddlepaddle
    这个看下python -c "import pip; print(pip.pep425tags.get_supported())" ，系统的版本之类的，改一下wheel 的名字，可以解决

2. Could not find a version that satisfies the requirement recordio>=0.1.0
    缺少python 的recordio 包，下载个whl 的包，recordio-0.1.5-cp27-none-linux_x86_64.whl ，如果安装过程中不支持的话，和1 一样，改个名字

3. 提示 fortran XXX 的编译错误
    这个一般是scipy 没有安装，下载安装一个

4.  Running setup.py install for subprocess32 ... error 
     下载个subprocess32-3.5.0rc1.tar.gz,  安装

5.  pip install paddlepaddle-XXX.whl
    成功了.

不容易...一些老系统没办法装docker 的. 只能一步一步来. 如果能用docker 还是用docker吧.

**Comment by wangkuiyi** [comment]
辛苦了 @VamWolf 

我一年多之前刚加入PaddlePaddle的时候，曾经试过在 Linux kernel 2.6 机器上做过一些编译工作。基本上一天之内就放弃了。正道应该是用现代 kernel 跑现代应用，因为不管升级kernel的阻力有多大，都比在古代kernel上跑现代应用省劲。
