### ISSUE TITLE
cost出奇的大，该怎么解决？

### ISSUE THREAD

**Issue by tanhaoyu** [PaddlePaddle/Paddle#8822]
有两个问题：
1.训练结果的cost出奇的大
2.推测的时候，我更改infer预测的特征值数据，换任何数字都对预测结果probs无影响，预测结果probs只与训练轮数有影响，而且并不是我的目标值。
请问，这两个问题该如何解决？眼看就要成功了，希望能帮助解答谢谢！

**Comment by wanghaoshuang** [comment]
>1.训练结果的cost出奇的大
可能是数据质量问题或训练超参数没调好。

**Comment by chengduoZH** [comment]
该issue长期没有更新，暂时先关闭了，如需继续讨论请再打开。
