### ISSUE TITLE
如何选择docker 进项编译paddle capi

### ISSUE THREAD

**Issue by utopiar** [PaddlePaddle/Paddle#8826]
由于当前paddle官方提供的预编译capi是基于protobuf3.1编译，与我厂大部分库（基于protobuf2.4）冲突，因此paddle同学建议自己编译，但是不知道应该选择哪个docker进行capi编译，请解答？
paddlepaddle/paddle_manylinux_devel 还是
paddlepaddle/centos6u3-capi？

另外是否能提供国内镜像，国外镜像拉取速度感人……

**Comment by wangkuiyi** [comment]
PaddlePaddle 提供一个开发环境的 Dockerfile，在 ： https://github.com/PaddlePaddle/Paddle/blob/develop/Dockerfile
