### ISSUE TITLE
How to merge non-sequential output with sequential output?

### ISSUE THREAD

**Issue by csx008** [PaddlePaddle/Paddle#8832]
Suppose I have two data types generated by data provider, one is sequential type and the other non-sequential. In the begining these two data will follow seperate network flows(for example sequence will go to lstm and non-sequence will go to FC), marked as flow_seq and flow_nonseq. Then I want to join these two flow together as sequential data and proceed to next level. How to perform such merge?

Belowing is simple descriptive code:
sequential flow:
`seq_data = layer.data(name="sequential_feature", type=dense_vector_sequence(M))`
`seq_fc=layer.fc(input=seq_data ,act=linear,size=hid_dim)`
`seq_lstm=layer.lstmemory(input=seq_fc,act=relu)`

non-sequential flow:
`non_seq_data = layer.data(name="non_sequential_feature",type=dense_vector(K))`
`non_seq_fc=layer.fc(input=seq_data ,act=tah,size=hid_dim)`

then merge as new sequential data where merged[i-th step] = seq_lstm[i-th step] + non_seq_fc:
`merged=somewhat_concat(seq_lstm, non_seq_fc)`
`merged_lstm = layer.lstmemory(input=merged,act=relu)`

How can i merge these two data?
BTW, seq_data  and non_seq_data  are provided by one data provider.

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
