### ISSUE TITLE
主流DL框架文档格式调研

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#8834]
以下为主流DL框架的文档格式:

### PyTorch

- Code Definition (definition and source link)
- Brief Introduction (necessary formula and symbols' description)
- Note
- Parameters description (including data type and default value)
- Inputs (shape, description)
- Outputs (shape, description)
- Variables (if have learnable network parameters, the description)
- Usage Example
![image](https://user-images.githubusercontent.com/31875089/37082282-1541fd32-2227-11e8-8e5b-33c8954fb326.png)

### TensorFlow
- Code Definition
- Code Source Link
- Guide
- Brief Introduction
- Note
- Usage Example
- Args description (optional attribute)
- Return Value Description
- Potential Exception

![image](https://user-images.githubusercontent.com/31875089/37082730-45fd86a2-2228-11e8-8f2d-ccb748dcc47a.png)

![image](https://user-images.githubusercontent.com/31875089/37082767-59449818-2228-11e8-842b-40d51de04800.png)

### CNTK

- Brief Introduction (one sentence)
- Code Definition
- Parameters (description, default value, optional attribute)
- Return Value Description
- Description (function， details)
- Usage Example

![image](https://user-images.githubusercontent.com/31875089/37082549-c9d587dc-2227-11e8-8ab0-b706c6e42aa6.png)

### MxNet

- Code Definition (source code link)
- Brief Introduction (necessary formula)
- Parameters (description, data type, default value)
- Inputs (shape, description)
- Outputs (shape, description)
- Usage Example

![image](https://user-images.githubusercontent.com/31875089/37082791-71206b6a-2228-11e8-8a0e-52edb392f4d8.png)

![image](https://user-images.githubusercontent.com/31875089/37082803-7bad8b1c-2228-11e8-8a38-de83db779e3b.png)

**Comment by luotao1** [comment]
related #6160
