### ISSUE TITLE
图片模型训练很慢

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#8835]
前面也做过paddle文本分类的模型，感觉图片慢太多了，也做了一些处理：
去掉了shuffle，减小batch_size甚至到16，学习率0.0001；但是使用比较大的长宽读取图片

结果Init parameters done.后几十分钟才开始迭代Batch，而且占用内存和cpu很高（感觉资源还不够的样子，有时等很久才开始下一批batch）
![6878466c-8652-4512-a8a8-70a7c7aa929d](https://user-images.githubusercontent.com/1950292/37083146-997e5a4e-2229-11e8-9782-133b3906b540.JPG)

**Comment by Kayven** [comment]
用的googlenet，image_classifission的例子，单机，cpu

**Comment by wanghaoshuang** [comment]
用CPU做图像处理本身就比较慢。

**Comment by yeyupiaoling** [comment]
@Kayven
这是自己机器资源问题，没有什么疑问吧。试试GPU

**Comment by chengduoZH** [comment]
该issue长时间没有更新，暂时先关闭了，如需继续讨论请再打开。
