### ISSUE TITLE
demo/mnist的Tutorial

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#884]
一直有一个问题，mnist作为一个比较简单的例子，为什么只是在代码里面有，而在文档里面不作为demo示例进行开放呢？
tensorflow  https://www.tensorflow.org/tutorials/mnist/beginners/
mxnet          http://mxnet.io/tutorials/python/mnist.html
tensorflow和mxnet都把mnist手写字识别作为第一个例子来让初学者入门，而且尽量详细的将一些机器学习相关的初步知识。两者都是先用MLP训练，然后再用CNN来提高效果，让初学者体验CNN对图像识别的一个显著提升作用，而paddle里面为什么只有比较高端的vgg_net呢？这一块是不是可以添加一下呢？

**Comment by luotao1** [comment]
mnist的tutorial正在考虑加，@dayhaha 你可以加一份么？

**Comment by dayhaha** [comment]
那我领这个任务，尝试丰富这个demo吧。

**Comment by luotao1** [comment]
可以先写中文文档。

**Comment by dayhaha** [comment]
那我能先写mnist的MLP和CNN的paddle实现，提交代码，review通过了再写文档么？

**Comment by dayhaha** [comment]
demo里面只有vgg_16_mnist.py，但是tensorflow和mxnet都把这个作为一个经典例子，先用基础的模型，分类准确率大概为92%，然后再用CNN，分类准确率就上升到了99%，我是觉得我们是不是可以像那样丰富一下？

**Comment by qingqing01** [comment]
@dayhaha  支持，我觉得这样挺好的， 使用简单一些网络，训练速度也快，适合用户学习。

**Comment by luotao1** [comment]
由于PaddlePaddle Book中更新了"识别数字"的中英文教程，因此该issue就close了。
