### ISSUE TITLE
IS CAPI multi-thread predict interface is actually exactly running sequence ? 

### ISSUE THREAD

**Issue by veridone** [PaddlePaddle/Paddle#8840]
AS the example in `paddle/capi/examples/model_inference/multi_thread`
I use all the default parameter make an executable program

`time ./multi_thread trainer_config.bin models/ 2>/dev/null` #it has 2 threads 
real    0m0.332s
user    0m0.420s
sys     0m0.271s

`time ./multi_thread trainer_config.bin models/ 4>/dev/null` #it has 4 threads 
real    0m0.684s
user    0m0.802s
sys     0m0.302s

0.684s/0.332s = 2
that means if I has four threads to run the program use just use the two times time of two threads 
it means is actually running sequence of the four threads ?

**Comment by luotao1** [comment]
what's version of your CAPI? cpu/gpu, mkl/openblas?

**Comment by veridone** [comment]
cpu version

**Comment by veridone** [comment]
use the model produce by `examples/model_inference/dense`

**Comment by veridone** [comment]
use github code and compile myself

**Comment by luotao1** [comment]
mkl/openblas? use `paddle version` to see it.

**Comment by veridone** [comment]
paddle version
PaddlePaddle 0.11.0, compiled with
    with_avx: ON
    with_gpu: OFF
    with_mkl: OFF
    with_mkldnn: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_timer: OFF

**Comment by veridone** [comment]
I installed it using `pip install paddlepaddle`

**Comment by veridone** [comment]
use command in [paddlepaddle.org](http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/capi/compile_paddle_lib_cn.html )
cmake -DCMAKE_INSTALL_PREFIX=$PADDLE_ROOT \
      -DCMAKE_BUILD_TYPE=Release \
      -DWITH_C_API=ON \
      -DWITH_SWIG_PY=OFF \
      -DWITH_GOLANG=OFF \
      -DWITH_PYTHON=OFF \
      -DWITH_MKL=OFF \
      -DWITH_GPU=OFF  \
      ..

**Comment by luotao1** [comment]
You can try env and run again:
```
export OPENBLAS_NUM_THREADS=1
```

**Comment by veridone** [comment]
it‘s OK，thanks

**Comment by luotao1** [comment]
Can you tell us how do you solve the problem?
