### ISSUE TITLE
Dead links in document.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#8846]
The picture links [around here](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/howto/optimization/cpu_profiling_cn.md#%E5%AF%BB%E6%89%BE%E6%80%A7%E8%83%BD%E7%93%B6%E9%A2%88-1) are dead.

**Comment by luotao1** [comment]
修复方法：将https://github.com/PaddlePaddle/Paddle/tree/develop/doc/v2/howto/optimization 目录下的pprof_1.png和pprof_2.png 移到 https://github.com/PaddlePaddle/Paddle/tree/develop/doc/fluid/howto/optimization

**Comment by Melobelle** [comment]
认领
