### ISSUE TITLE
MPI集群训练的模型本地infer的时候出错

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#8868]
Traceback (most recent call last):
  File "query_dnn_single_infer.py", line 180, in <module>
    dnn_infer(input_file_name, param_file_name)
  File "query_dnn_single_infer.py", line 156, in dnn_infer
    probs = paddle.infer(output_layer=out, parameters=parameters, input=input)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/inference.py", line 157, in infer
    inferer = Inference(output_layer=output_layer, parameters=parameters)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/inference.py", line 50, in __init__
    val.copyFromNumpyArray(parameters.get(name).flatten())
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 242, in get
    return self.__getitem__(key=parameter_name)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 186, in __getitem__
    return self.__getter_inner(key, api.PARAMETER_VALUE)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 153, in __getter_inner
    shape = self.get_shape(key)
  File "/home/users/zhouweiran/anaconda2/lib/python2.7/site-packages/paddle/v2/parameters.py", line 200, in get_shape
    raise ValueError("No such parameter %s" % key)
ValueError: No such parameter ___sequence_conv_pooling_0___conv_fc.w0

**Comment by wrchow** [comment]
119 
120 def dnn_infer(input_file_name, parma_file_name):                                                                                                                                    
121     """
122     predict instance labels by dnn network
123 
124     :params file_name: network parameter file
125     :type file_name: str
126     """
127     dict_dim = len(word_dict)
128     class_dim = 2
129     # Movie Reviews, from imdb test
130     reviews = []
131     for line in open(input_file_name):
132         line = line.strip("\n")
133         line_list = line.split("\t")
134         text = line_list[0]
135         reviews.append(text)
136     reviews = [c.split() for c in reviews]
137 
138     UNK = word_dict['<unk>']
139     input = []
140     for c in reviews:
141         input.append([[word_dict.get(words, UNK) for words in c]])
142 
143     # 0 stands for positive sample, 1 stands for negative sample
144     label = {0:'pos', 1:'neg'}
145     # Use the network used by trainer
146     out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
147     # out = stacked_lstm_net(dict_dim, class_dim=class_dim, stacked_num=3, is_predict=True)
148     parameters = paddle.parameters.Parameters.from_tar(gzip.open(param_file_name))
149     probs = paddle.infer(output_layer=out, parameters=parameters, input=input)
150 
151     labs = np.argsort(-probs)
152     for idx, lab in enumerate(labs):
153         #print idx, "predicting probability is", probs[idx], "label is", label[lab[0]]
154         print query_list.replace(" ", "") + "\t" + label[lab[0]] + "\t" + query_list  + "\t" + ",".join([str(i) for i in input[idx]])
155

**Comment by wrchow** [comment]
import sys
import math
import os
import shutil
import pickle
import paddle.v2 as paddle
import gzip
import numpy as np

train_file_dir = "./data/test1/train.imdb.v1.1"
test_file_dir = "./data/test1/test.imdb.v1.1"
dev_file_dir = "./data/test1/dev.imdb.v1.1"
#node_id = int(os.getenv("OMPI_COMM_WORLD_RANK"))

word_dict_file = open("./data/word_dict.pickle", "r")
word_dict = pickle.load(word_dict_file)

def encode_word(word):
    if word_dict.has_key(word):
        return word_dict[word]
    else:
        return word_dict['<unk>']


def single_data_reader(file_dir_name):
    def data_reader():
        for line in open(file_dir_name, "r"):
            elems = line.strip('\n').split('\t')
            ins = '\t'.join(elems[0:-1])
            label = elems[-1]
            ins_data = [int(encode_word(w)) for w in ins.split(' ')]
            yield ins_data, int(label)
    return data_reader


def convolution_net(input_dim,
                    class_dim=2,
                    emb_dim=128,
                    hid_dim=128,
                    is_predict=False):
    data = paddle.layer.data("word",
                             paddle.data_type.integer_value_sequence(input_dim))
    emb = paddle.layer.embedding(input=data, size=emb_dim)
    conv_3 = paddle.networks.sequence_conv_pool(
        input=emb, context_len=3, hidden_size=hid_dim)
    conv_4 = paddle.networks.sequence_conv_pool(
        input=emb, context_len=4, hidden_size=hid_dim)
    output = paddle.layer.fc(input=[conv_3, conv_4],
                             size=class_dim,
                             act=paddle.activation.Softmax())
    if not is_predict:
        lbl = paddle.layer.data("label", paddle.data_type.integer_value(2))
        cost = paddle.layer.classification_cost(input=output, label=lbl)
        return cost
    else:
        return output


def train_dnn_model(num_pass):
    print 'load dictionary...'
    #word_dict = paddle.dataset.imdb.word_dict()
    dict_dim = len(word_dict)
    class_dim = 2
    train_reader = paddle.batch(
        paddle.reader.shuffle(
            single_data_reader(train_file_dir), buf_size=1000),
        batch_size=100)
    test_reader = paddle.batch(
        single_data_reader(test_file_dir),
        batch_size=100)
    feeding={'word': 0, 'label': 1}
    # Please choose the way to build the network
    # by uncommenting the corresponding line.
    cost = convolution_net(dict_dim, class_dim=class_dim)
    # cost = stacked_lstm_net(dict_dim, class_dim=class_dim, stacked_num=3)
    # create parameters
    parameters = paddle.parameters.create(cost)
    # create optimizer
    adam_optimizer = paddle.optimizer.Adam(
        learning_rate=2e-3,
        regularization=paddle.optimizer.L2Regularization(rate=8e-4),
        model_average=paddle.optimizer.ModelAverage(average_window=0.5))
    # End batch and end pass event handler
    def event_handler(event):
        if isinstance(event, paddle.event.EndIteration):
            if event.batch_id % 100 == 0:
                print "\nPass %d, Batch %d, Cost %f, %s" % (
                event.pass_id, event.batch_id, event.cost, event.metrics)
            else:
                sys.stdout.write('.')
                sys.stdout.flush()
        if isinstance(event, paddle.event.EndPass):
            with open('./params_pass_%d.tar' % event.pass_id, 'w') as f:
                trainer.save_parameter_to_tar(f)

            result = trainer.test(reader=test_reader, feeding=feeding)
            print "\nTest with Pass %d, %s" % (event.pass_id, result.metrics)
            if not os.path.exists("model_params"):
                os.makedirs("model_params")
            with gzip.open("model_params/dnn_params_pass" + str(event.pass_id) + ".tar.gz", 'w') as f:
                parameters.to_tar(f)
    # create trainer
    trainer = paddle.trainer.SGD(cost=cost,
                            parameters=parameters,
                            update_equation=adam_optimizer)
    trainer.train(
        reader=train_reader,
        event_handler=event_handler,
        feeding=feeding,
        num_passes=num_pass)
    print("Training finished.")


def dnn_infer(input_file_name, parma_file_name):
    """
    predict instance labels by dnn network

    :params file_name: network parameter file
    :type file_name: str
    """
    dict_dim = len(word_dict)
    class_dim = 2
    # Movie Reviews, from imdb test
    reviews = []
    for line in open(input_file_name):
        line = line.strip("\n")
        line_list = line.split("\t")
        text = line_list[0]
        reviews.append(text)
    reviews = [c.split() for c in reviews]

    UNK = word_dict['<unk>']
    input = []
    for c in reviews:
        input.append([[word_dict.get(words, UNK) for words in c]])

    # 0 stands for positive sample, 1 stands for negative sample
    label = {0:'pos', 1:'neg'}
    # Use the network used by trainer
    out = convolution_net(dict_dim, class_dim=class_dim, is_predict=True)
    # out = stacked_lstm_net(dict_dim, class_dim=class_dim, stacked_num=3, is_predict=True)
    parameters = paddle.parameters.Parameters.from_tar(gzip.open(param_file_name))
    probs = paddle.infer(output_layer=out, parameters=parameters, input=input)

    labs = np.argsort(-probs)
    for idx, lab in enumerate(labs):
        #print idx, "predicting probability is", probs[idx], "label is", label[lab[0]]
        print query_list.replace(" ", "") + "\t" + label[lab[0]] + "\t" + query_list  + "\t" + ",".join([str(i) for i in input[idx]])


if __name__ == "__main__":
    """
    paddle.init(use_gpu=False,
            trainer_count=int(os.getenv("PADDLE_TRAINER_COUNT", "1")),
            port=int(os.getenv("PADDLE_PORT", "7164")),
            ports_num=int(os.getenv("PADDLE_PORTS_NUM", "1")),
            num_gradient_servers=int(os.getenv("PADDLE_NUM_GRADIENT_SERVERS", "1")),
            trainer_id=int(os.getenv("PADDLE_TRAINER_ID", "0")),
            pservers=os.getenv("PADDLE_PSERVERS", "127.0.0.1"))
    """
    # F1222 11:13:42.303535 22874 LightNetwork.cpp:399] connection refused by pserver, maybe pserver failed!
    paddle.init(use_gpu=False)
    num_pass = 5
    #train_dnn_model(num_pass=num_pass)
    param_file_name = "model_params/dnn_params_pass" + str(num_pass - 1) + ".tar.gz"
    dnn_infer(dev_file_dir, param_file_name)
    #shutil.move("model_params", "output/model_params")

**Comment by wrchow** [comment]
./paddle cluster_train \
    --config /home/users/zhouweiran/ml/paddle/demo/paddle_study/text_classify/text_classification_dnn.py \
    --use_gpu cpu \
    --use_remote_sparse 0 \
    --time_limit 01:20:00 \
    --submitter weiran \
    --num_nodes 4 \
    --job_priority high \
    --init_model_path \"\" \
    --fs_name afs://tianqi.afs.baidu.com:9902 \
    --fs_ugi rank-click-antispam,rca123456 \
    --train_meta_data_path \"\" \
    --test_meta_data_path \"\" \
    --train_data_path /app/ps/rank/rank-click-antispam/weiran/paddle_study/text_classify/train \
    --test_data_path  /app/ps/rank/rank-click-antispam/weiran/paddle_study/text_classify/test \
    --output_path /app/ps/rank/rank-click-antispam/weiran/paddle_study/text_classify/output_wise_all_output3 \
    --thirdparty /home/users/zhouweiran/ml/paddle/demo/paddle_study/text_classify/my_thdpty \
    --where yq01-hpc-heng-dpf-dmop-cpu-10G_cluster \
    --job_name paddle_cluster_text_classification_weiran_wise_all_output

**Comment by ranqiu92** [comment]
使用mpi训练生成的模型文件报错，而本地训练生成的正常，可以先解压下模型文件，对比两中模型文件的差异 看看。

**Comment by ranqiu92** [comment]
mpi训练时使用了不同的网络结构 导致的这个问题。
