### ISSUE TITLE
v2 集群任务是否运行正常【server.log报错，但train.log滚动正常，output输出tar.gz抓取下来提示格式错误】

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#8870]
【任务节点】
http://10.73.37.43:8900/fileview.html?path=/home/disk1/normandy/maybach/657903/
receiver:  yq01-idl-gpu-offline14.yq01.baidu.com:8091 #V2版本的receiver

【问题】
   1 、server.log和train.log日志显示不一致，不确定任务是否正常运行？
   2、V2版本中间输入参数是否如V1一样 wget ${main_node_ip}:8099/output/xxx 类似方式拉取?目前抓取失败
  
【server.log】
Thu Mar  8 14:34:22 2018[1,28]<stderr>:./start_server.sh: line 34: 28618 Killed                  GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_pserver2 --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --nics=${nics} ${server_arg} --rdma_tcp=${rdma_tcp} --use_gpu=0 --comment=$comment
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ check_return 'paddle_pserver2 failed'
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ '[' 137 -ne 0 ']'
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ echo '[./start_server.sh : 35] [main]'
Thu Mar  8 14:34:22 2018[1,28]<stderr>:[./start_server.sh : 35] [main]
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ echo '[FATAL]: paddle_pserver2 failed'
Thu Mar  8 14:34:22 2018[1,28]<stderr>:[FATAL]: paddle_pserver2 failed
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ get_stack
Thu Mar  8 14:34:22 2018[1,28]<stderr>:+ set +x
Thu Mar  8 14:34:22 2018[1,28]<stderr>:
Thu Mar  8 14:34:22 2018[1,28]<stderr>:*****

【train.log】
Thu Mar  8 15:15:49 2018[1,4]<stdout>:Pass 48 Batch 5 Cost 0.422954053
Thu Mar  8 15:15:59 2018[1,4]<stdout>:Pass 48 Batch 6 Cost 0.356798267
Thu Mar  8 15:15:59 2018[1,10]<stdout>:Pass 48 Batch 10 Cost 0.402026196
Thu Mar  8 15:16:00 2018[1,29]<stdout>:Pass 49 Batch 4 Cost 0.420187109
Thu Mar  8 15:16:01 2018[1,28]<stdout>:Pass 48 Batch 5 Cost 0.402949292
Thu Mar  8 15:16:08 2018[1,9]<stdout>:Pass 49 Batch 2 Cost 0.440044434
Thu Mar  8 15:16:14 2018[1,17]<stdout>:Pass 49 Batch 8 Cost 0.427096777
Thu Mar  8 15:16:16 2018[1,13]<stdout>:Pass 49 Batch 4 Cost 0.394396509

**Comment by Yancey1989** [comment]
`train.log` 和 `server.log` 中是收集了所有节点的日志，例如：
```bash
Thu Mar 8 15:15:49 2018[1,4]:Pass 48 Batch 5 Cost 0.422954053
```
表示`4`号节点。

这种情况一般要先找最先报错的trainer节点的日志，才好定位问题。

**Comment by lyp2github** [comment]
train.log中没找到FATAL日志，server.log里没有记录节点
我每个节点都点进去，日志正常，output正常产出
还能如何确定哪个节点报的错？

**Comment by Yancey1989** [comment]
在Hi上单发我下job链接吧：yanxu05

**Comment by Yancey1989** [comment]
根据在Hi上沟通情况，这个任务需要指定指定`is_local=False`, 否则每个节点都是跑的单机训练任务，例如：

https://github.com/PaddlePaddle/Paddle/blob/12fc76e1b575a474dd8637e754e7361a790aedc0/doc/v2/howto/cluster/src/word2vec/api_train_v2_cluster.py#L58
https://github.com/PaddlePaddle/Paddle/blob/12fc76e1b575a474dd8637e754e7361a790aedc0/doc/v2/howto/cluster/src/word2vec/api_train_v2_cluster.py#L126-L129
