### ISSUE TITLE
集群训练打开sparse update后报错 Check failed: numPorts > 0 (0 vs. 0)

### ISSUE THREAD

**Issue by SearchVera** [PaddlePaddle/Paddle#8875]
未打开sparse update可以跑通完成训练，打开sparse update修改了两个地方
1. 网络结构配置sparse_update=True

`

    hd1 = paddle.layer.fc(
        input=feature,
        size=hidden_layer_size,
        act=paddle.activation.Tanh(),
        layer_attr=paddle.attr.Extra(drop_rate=0.5),
        #param_attr=paddle.attr.Param(initial_std=1.0 / hidden_layer_size))
        param_attr=paddle.attr.Param(initial_std=1.0 / hidden_layer_size, sparse_update=True))`

2. 提交命令use_remote_sparse设为1

`
    paddle cluster_train \
      --config ${model_config_file} \
      --use_remote_sparse 1 \
`

打开后报错：
![image](https://user-images.githubusercontent.com/4626893/37140619-5324a296-22ed-11e8-8124-a520b119ec00.png)

更新算法使用的AdaGrad：

`
    adagrad_optimizer = paddle.optimizer.AdaGrad(
        learning_rate=1e-3,
        regularization=paddle.optimizer.L2Regularization(rate=1e-3))`

**Comment by wangkuiyi** [comment]
昨天我在PaddlePaddle团队周报里看到一个已知问题，貌似和这个问题是一样的。也看到相关同事们在解决。请 @typhoonzero 确认一下吧

**Comment by typhoonzero** [comment]
请确认下：

1. `paddle.init(ports_num_for_sparse=int(os.getenv("PADDLE_PORTS_NUM_FOR_SPARSE", "1")),...)`包含这个参数。
1. 查看pserver启动日志，是否包含`ports_num_for_sparse`参数

**Comment by SearchVera** [comment]
@typhoonzero 
确实是没有配置这个参数造成的，感谢哈~
ports_num_for_sparse=int(os.getenv("PADDLE_PORTS_NUM_FOR_SPARSE", "1")

另外想问有没有稀疏更新的教程？我就是没找到，只能照着别人的配置改

**Comment by typhoonzero** [comment]
内网的那个wiki的demo默认是开了sparse的。不过的确关于稀疏更新的文档需要一个单独的文档的section比较好。 @luotao1 你觉得呢。

**Comment by luotao1** [comment]
@typhoonzero 我觉得很好，可以单独提一个issue来解决这个问题。稀疏更新的文档建议新增一篇，而非放入已有文档的某个章节中，此外可以先增加中文文档。

**Comment by typhoonzero** [comment]
好，这个issue我先关闭了~
