### ISSUE TITLE
paddle 初始化报错

### ISSUE THREAD

**Issue by jinyuanqing** [PaddlePaddle/Paddle#8878]
安装完paddle后，环境Python2,7，paddle0.11.0
执行文档中纽约房价预测的代码报错。报错的代码是Initialize PaddlePaddle.也就是第2句代码，错误提示为提示非法指令。然后我单步跟踪初始化，发现初始化调用了以下2句
def init(**kwargs):
    import py_paddle.swig_paddle as api
而这里的第二句导入py_paddle.swig_paddle as api报错，提示非法指令

房价预测代码如下：
import paddle.v2 as paddle

# Initialize PaddlePaddle.
paddle.init(use_gpu=False, trainer_count=1)

# Configure the neural network.
x = paddle.layer.data(name='x', type=paddle.data_type.dense_vector(13))
y_predict = paddle.layer.fc(input=x, size=1, act=paddle.activation.Linear())

# Infer using provided test data.
probs = paddle.infer(
    output_layer=y_predict,
    parameters=paddle.dataset.uci_housing.model(),
    input=[item for item in paddle.dataset.uci_housing.test()()])

for i in xrange(len(probs)):
    print 'Predicted price: ${:,.2f}'.format(probs[i][0] * 1000)

**Comment by ranqiu92** [comment]
先用 pip  卸载 paddle 再 用pip 重新安装 试下

**Comment by jinyuanqing** [comment]
卸载后重新安装paddle，还是老样子。直接python wodewenjian。py执行的，报错：非法指令。问题依旧是py_paddle.swig_paddle as ap这句产生的

**Comment by wangkuiyi** [comment]
> 而这里的第二句导入py_paddle.swig_paddle as api报错，提示非法指令

我见过的非法指令错误可能是 AVX 指令集或者 CUDA 的问题。

@jinyuanqing 上述实验是用 Docker 做的吗？如果是用 https://hub.docker.com/r/paddlepaddle/paddle/tags/ 这里的 gpu 相关的 images，需要用  nvidia-docker 而不是 docker 来启动 Docker container。

**Comment by yeyupiaoling** [comment]
@jinyuanqing 问题是否已得到解决，请反馈一下。

**Comment by jinyuanqing** [comment]
大家好。这个问题暂时没有解决。我更换一个i7的cpu电脑就好了，原先的是amd245的cpu。另外可能是我的房价模型没有下载的缘故。
