### ISSUE TITLE
在docker中使用paddle，在python improt cv2时报错，但是本机的python import cv2是正常的

### ISSUE THREAD

**Issue by Yight001** [PaddlePaddle/Paddle#8880]
在docker中使用python时 import cv2时报错，但在本机却没问题

![qq 20180308174250](https://user-images.githubusercontent.com/37174503/37147653-a0cf83f2-2302-11e8-8a6c-e598f180bba4.png)

使用paddle时，也会报错

![qq 20180308185054](https://user-images.githubusercontent.com/37174503/37147359-a3f7fdda-2301-11e8-8b78-9bfd4b955345.png)

问题应该就是在docker的python库中找不到opencv，但是没有什么好的方法解决，求大神帮帮忙！

**Comment by yeyupiaoling** [comment]
@Yight001 
您好，docker容器跟本机的环境是完全分离的，所以您在本机安装cv2，对docker是不会影响的

**Comment by Yight001** [comment]
@yeyupiaoling 但是之前在本机安装的numpy在docker中就能正常使用

**Comment by yeyupiaoling** [comment]
@Yight001 
您先了解Docker容器，如果不熟悉，可以在电脑本机上使用PaddlePaddle
也可以参考这个文章：http://blog.csdn.net/tengxing007/article/details/54380732

**Comment by ranqiu92** [comment]
docker与本机是分离的，在docker里输入pip list 看下装了哪些python包

**Comment by wangkuiyi** [comment]
### 答疑

我估计 @Yight001 说的“host上安装的CV2在Docker里能用”其实是Docker image里也有CV2。

理论上有一种做法，可以让 Docker container 使用host上的Python package —— 在启动 container 的时候使用 `-v` 参数把host上的Python package directory map到container里。不过这不是一个好办法，因为host上和 container 里的的Python interpreter 可能不是同一个版本，所以他们的package不一定能通用。

### 解惑

如果要build一个Docker image，能用来跑依赖OpenCV和PaddlePaddle的Python程序，可以：

1. 写一个Dockerfile，从官方PaddlePaddle Docker image派生自己的image。
2. 这个Dockerfile里写明安装 python-opencv package。
3. Build这个新的image。
4. 运行这个image。

我在我的MacBook Pro上按照上述过程实践了一下，验证通过。

1. 我的`/tmp/cv2paddle/Dockerfile`的内容如下：

   ```dockerfile
   FROM paddlepaddle/paddle:latest
   MAINTAINER Yi Wang <yi.wang.2005@gmail.com>

   RUN apt-get update && apt-get install -y python-opencv
   ```

2. 我用如下命令build我的image：

   ```bash
   cd /tmp/cv2paddle
   docker build -t cv2paddle .
   ```

3. 用如下命令运行我的image，并且在其中启动一个Python 解释器，来验证可以import paddle和cv2：

   ```bash
   yi@Yis-Mac-mini cv2paddle $ docker run --rm -it cv2paddle /bin/bash
   root@c767b69c8ce5:/# python
   Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
   [GCC 5.4.0 20160609] on linux2
   Type "help", "copyright", "credits" or "license" for more information.
   >>> import paddle.v2 as paddle
   >>> import cv2
   >>> 
   ```

   我没有做进一步的验证，但是至少以上步骤确保import paddle和cv2都没问题。

**Comment by Yight001** [comment]
大神@wangkuiyi，我对Docker不是很熟悉，找了很多资料，我尝试您的做法，但是始终不能build这个镜像
docker build -t cv2paddle . 中的cv2paddle是 文件夹的名字吗？还有/tmp/cv2paddle/Dockerfile这个路径是本机的路径吗？

**Comment by typhoonzero** [comment]
`docker build -t cv2paddle .` 这个命令中`-t cv2paddle`是指定build生成的镜像的名字。后面的`.`是指在当前目录`.`下寻找`Dockerfile`文件并使用该文件build `cv2paddle `这个镜像。

**Comment by yeyupiaoling** [comment]
@Yight001 
如果你不了解使用Dockerfile构建一个镜像，可以在原来的镜像安装和更新你的库，使用命令
```
docker run -t -i 你的镜像 /bin/bash
```
然后使用`exit`退出，在退出之前要记住镜像的ID，然后提交生成一个新的镜像
```
docker commit -m="提交信息" -a="作者" 刚才记录的ID 镜像名称
```

要注意是ID是你进入镜像看到的ID，比如`root@1234566`，那么1234566就是ID
镜像名称的结构是：`REPOSITORY:TAG`

**Comment by Yight001** [comment]
@wangkuiyi   麻烦您了，在镜像中如何更新我的库呢，按照您的方法进入了指定的镜像

![qq 20180309135813](https://user-images.githubusercontent.com/37174503/37192861-94d96d60-23a2-11e8-8d86-91d9b7563196.png)

**Comment by Yight001** [comment]
我在镜像中安装了opencv但是还是报错

![qq 20180309153601](https://user-images.githubusercontent.com/37174503/37195918-b00cb85a-23af-11e8-94ac-1c96a8fe8f75.png)

**Comment by typhoonzero** [comment]
Try `apt-get install libglib2.0-0`, if this still does not work, try find whether `libgthread-2.0.so.0` exists and export `LD_LIBRARY_PATH` to it's directory.

**Comment by mrlinyj** [comment]
![image](https://user-images.githubusercontent.com/35088451/38560972-70e2ee88-3d09-11e8-8bd0-3e9884dd7f7a.png)
