### ISSUE TITLE
CAPI如何加载合并模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8883]
这里是介绍普通的加载模型的方法
https://github.com/PaddlePaddle/Paddle/blob/ffda2c414dcf520d2dea0ac9fccd0478dc8e081f/paddle/capi/examples/model_inference/dense/main.c#L35-L44

文档这也用说到下面一行代码是加载合并模型的，我看怎么跟上面的一样呢
https://github.com/PaddlePaddle/Mobile/blob/develop/Demo/linux/paddle_image_recognizer.cpp#L59

**Comment by wangkuiyi** [comment]
这个问题和 https://github.com/PaddlePaddle/Paddle/issues/8885 相关。也请 @Xreki @kexinzhao 看看吧。

**Comment by yeyupiaoling** [comment]
在Android上使用合并模型使用这个：
```
  // Step 1: Reading merged model.
  long size;
  void* buf = read_config(merged_model_path, &size);

  // Step 2:
  //    Create a gradient machine for inference.
  CHECK(paddle_gradient_machine_create_for_inference_with_parameters(
      &gradient_machine_, buf, size));

```
