### ISSUE TITLE
CAPI如何获取预测结果

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8885]
看到例子，下面代码就是最后的了，应该是预测的结果获取
https://github.com/PaddlePaddle/Paddle/blob/ffda2c414dcf520d2dea0ac9fccd0478dc8e081f/paddle/capi/examples/model_inference/dense/main.c#L97-L106

而使用Python的，预测的代码是下面这一条，所以cpp中的`array`是不是就是Python中的`probs`
```python
probs = paddle.infer(output_layer=predict, parameters=parameters, input=test_data)
```

**Comment by wangkuiyi** [comment]
@yeyupiaoling 是不是在用 Fluid 训练模型，同时寻求 inference 的做法？

我理解如果是Fluid训练的模型，可能就不能用这个被称为 C-API 的inference library来做inference了，而需要使用 Fluid 的inference 方法。请 @Xreki @kexinzhao 确认一下吧。我们也是有Fluid 的inference 的例子的。

**Comment by yeyupiaoling** [comment]
@wangkuiyi 
您好，我不是使用Fluid的，是使用Paddle 1的，然后编译放到Android上的，官方有个例子，我有几个问题不懂

**Comment by wangkuiyi** [comment]
哦。这个可能得 @Xreki 帮着看看呢。

**Comment by yeyupiaoling** [comment]
https://github.com/PaddlePaddle/Paddle/blob/ffda2c414dcf520d2dea0ac9fccd0478dc8e081f/paddle/capi/examples/model_inference/dense/main.c#L97
通过这一行就可以获得跟
```
    probs = paddle.infer(
        output_layer=out, parameters=parameters, input=test_data)
```
获得同样的结果。
