### ISSUE TITLE
paddle.v2.image怎么裁剪后拼接图片

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#8889]
仿照center_crop这种函数crop出两部分图片im1和im2，再怎么纵向拼成一张图片呢？

**Comment by yeyupiaoling** [comment]
@Kayven 
你这需求有点奇怪，通过中心裁剪后，使用中间的图像进行预测，你怎么还有拼在一起

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
