### ISSUE TITLE
paddle_pserver2 err 

### ISSUE THREAD

**Issue by adrianhust** [PaddlePaddle/Paddle#8892]
Hi, 
log:
```
Fri Mar  9 08:34:38 2018[1,4]<stderr>:./start_server.sh: line 33: 42473 Aborted                 GLOG_logtostderr=0 GLOG_log_dir="./log" ./paddle_pserver2 --num_gradient_servers=${OMPI_COMM_WORLD_SIZE} --nics=${nics} ${server_arg} --rdma_tcp=${rdma_tcp} --comment=$comment
Fri Mar  9 08:34:38 2018[1,8]<stderr>:F0309 08:34:38.208967 43912 ParameterServer2.cpp:158] Check failed: !configMap_.count(config.para_id()) Duplicated parameter name: ___fc_layer_1__.wbias
Fri Mar  9 08:34:38 2018[1,4]<stderr>:+ check_return 'paddle_pserver2 failed'
Fri Mar  9 08:34:38 2018[1,4]<stderr>:+ '[' 134 -ne 0 ']'
Fri Mar  9 08:34:38 2018[1,4]<stderr>:+ echo '[./start_server.sh : 34] [main]'
Fri Mar  9 08:34:38 2018[1,7]<stderr>:F0309 08:34:38.206758 20904 ParameterServer2.cpp:158] Check failed: !configMap_.count(config.para_id()) Duplicated parameter name: ___fc_layer_1__.wbias
Fri Mar  9 08:34:38 2018[1,4]<stderr>:[./start_server.sh : 34] [main]
Fri Mar  9 08:34:38 2018[1,4]<stderr>:+ echo '[FATAL]: paddle_pserver2 failed'
Fri Mar  9 08:34:38 2018[1,4]<stderr>:[FATAL]: paddle_pserver2 failed
Fri Mar  9 08:34:38 2018[1,4]<stderr>:+ get_stack
```
<img width="500" alt="mem2018-03-09 09-56-16" src="https://user-images.githubusercontent.com/1840577/37186391-3a533668-2380-11e8-9329-5035ca5c63f3.png">

**Comment by Yancey1989** [comment]
Could you submit the job by `receiver` service?  It's a stable version for PaddlePaddle on internal MPI cluster and it works well for most users.

**Comment by wangkuiyi** [comment]
@adrianhust and @Yancey1989 : is this question about the job submitter we used inside Baidu? I ask because I cannot find the `start_server.sh` script in the Paddle repo nor the cloud repo.

**Comment by Yancey1989** [comment]
Yes, this job was running on the internal MPI cluster, and I think this question has been fixed by submitting through `receiver`, which is a Python Service to make it easy to submit a job to MPI cluster for users.

@adrianhust , I will close this issue and feel free to reopen it.

**Comment by pkuyym** [comment]
Close it due to inactivity.
