### ISSUE TITLE
PaddlePaddle的国内的Docker镜像的网站是什么？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8904]
比如PaddlePaddle的国外存放的Docker镜像在：https://hub.docker.com/u/paddlepaddle/
但是国内的文档我找不到连接，我想如果镜像国内有的，我尽量使用国内的，国外的速度真的不好意思说出来
比如这是一个国外的镜像
```
docker pull paddlepaddle/paddle
```
这个是国内的镜像
```
docker pull docker.paddlepaddlehub.com/paddle
```
我之前测试过，并非所有的镜像都提供国内版

**Comment by peterzhang2029** [comment]
目前国内的镜像是没有这样的网页说明的。

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
那是否可以在提供国外镜像的时候，也提供国内镜像？

**Comment by peterzhang2029** [comment]
@yeyupiaoling  据同事反应，国外的镜像 国内镜像应该也是相应提供的，如果对应的你没有找到，可以提一下，这边修正一下。

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
嗯嗯，这是因为之前遇到过这个情况，已经补上了。现在想起这个问题，就提一下issue。谢谢
