### ISSUE TITLE
Paddle Function

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#892]
The main purpose of refactoring Paddle's computationally related code is to use a unified interface to represent each function. The function here can be understood as an operator in a neural network. Refactoring these computationally related codes mainly to solve the following three issues.
- Lack of unified function interface description
In Paddle, the definition of Layer has a unified interface, but a Layer often call a number of functions, these functions do not have a unified interface description.
If I just want to write an FFT-based convolution forward calculation for model inference, which interface should I refer to?
- Refactor the interfaces listed in ISSUE #977
Most of these functions are defined as a member function of the Matrix, but it does not specify how the member function interface of the Matrix should be defined. This has encountered some problems in interface readability and interface testing (#385).
- Import third-party library, such as cuDNN, NNPACK, to improve the computational performance of Paddle on different hardware platforms(such as #2177).
To import a third-party library requires a piece of code to wrap the interface provided by the third-party library to facilitate calls in Paddle. So, what needs to be considered is how to simplify the writing of this wrapper code.

## A unified function interface description
Paddle has many computationally related code(ISSUE #997), by analyzing these interfaces, we can understand that what issues needs to solve.
1. A calculation function that has one input and one output(https://github.com/PaddlePaddle/Paddle/issues/892#issuecomment-267358563).
2. A calculation function that has multiple inputs and multiple outputs(https://github.com/PaddlePaddle/Paddle/issues/892#issuecomment-267358563).
3. Some of the interfaces will assign the result to the output, while others will add the result to the output(https://github.com/PaddlePaddle/Paddle/issues/892#issuecomment-267358563).
4. The same function is implemented as multiple versions based on different devices. At present, for CPU and GPU two devices, the realization of the CpuMatrix::memberFunction and GpuMatrix::memberFunction two functions.
5. The same function is implemented as multiple versions based on different data type(like double, float). At present, it is done by switching the definition of `real` at compile time.
6. Using Matrix and Vector to represent one-dimensional and two-dimensional dense data types;
7. With a Matrix and a Vector two arguments to represent an argument of the sequence type;
8. SparseMatrix represents the sparse matrix type of `NO_VALUE` or `FLOAT_VALUE`;

If we have designed an interface to solve these problems, we can reorganize the code(https://github.com/PaddlePaddle/Paddle/issues/892#issuecomment-267288472) of the interface listed in #997.

**Comment by hedaoyuan** [comment]
PR #854  是Paddle增加一个cross map normalize Function的例子：
1. 定义CrossMapNormal/CrossMapNormalGrad 并实现算法API；
2. 将API以FunctionBase的形式，封装成CrossMapNormalFunc/CrossMapNormalGradFunc；
3. CMRProjectionNormLayer::init里面create forward/backward function；
4. CMRProjectionNormLayer::forward/backward里面调用相应的function；

**Comment by hedaoyuan** [comment]
**Paddle Function New Features**

1. Function Performance -- todo
每个Function可以单独计时，并根据其计算复杂度和访存复杂度计算Function的性能；而原先的Layer由于可能包含多个计算及内存相关操作，直接对Layer描述性能会比较困难；获得每个Function的性能后，就能比较简单的描述Layer和Neural Network的性能。

**Comment by hedaoyuan** [comment]
**FAQ**
与@tianbingsz 在基于Function开发上的一些问题：
1. FunctionBase::calc只有一个类型，在重构Matrix API时有些不是很好写，是否可以增加虚函数类型。
不用增加虚函数类型。FunctionBase设计的初衷就是一个calc接口类型，当前的`class Tensor`只能表示dense的数据类型，后续会扩展。
2. FunctionCompare::cmpWithArg也只有一个接口类型，有些test case参数是在cmpWithArg外面初始化的，调用cmpWithArg时参数会被覆盖
这里同样只需要一个接口，本意是test case只需要给出被测Function类型和参数类型（上面commit中的Function Arguments Type Checking实现后参数类型也不用给了），参数的分配初始化都在接口里面实现，简化test case的写法。

**Comment by hedaoyuan** [comment]
**Function Argument**
Function的calc接口包含inputs, outputs, inouts三个参数，参数的类型是`BufferArgs`结构，一个`BufferArgs`结构包含a list of `BufferArg`，`BufferArg`描述每个input/output/inout的类型。

Paddle中Function的参数类型主要有以下四种；
1. `TENSOR_NORMAL`用于描述参数是一个任意维度的稠密Buffer，对应BufferArg结构；
2. `TENSOR_SEQUENCE_ID`描述参数是一个一维的向量，不同于`TENSOR_NORMAL`的是Buffer中的值是一个递增的序列，用于描述sequenceStartPositions这种特殊的Buffer，另外隐含着number sequences信息，对应SequenceIdArg结构，一般和一个`TENSOR_NORMAL`一起描述一个`TENSOR_SEQUENCE_DATA`；
3. `TENSOR_SEQUENCE_DATA`是用于描述一个sequence数据的Buffer，paddle的sequence data支持一个mini-batch中包含多个不等长的序列，实现上用一个`TENSOR_NORMAL`和`TENSOR_SEQUENCE_ID`一起来描述一个sequence data，对应SequenceArg结构；
4. `TENSOR_SPARSE`用于描述一个SparseMatrix Buffer，当前Paddle的Sparse支持CSR/CSC两种Format及NO_VALUE和FLOAT_VALUE两种DataType；对应SparseMatrixArg结构。
```
enum BufferType {
  TENSOR_NORMAL = 0,
  TENSOR_SEQUENCE_ID = 1,
  TENSOR_SEQUENCE_DATA = 2,
  TENSOR_SPARSE = 3
};
```

**Comment by hedaoyuan** [comment]
**Function `outputs` and `inouts` Argument**
`Function::calc`接口原型中包含`inputs`，`outputs`，`inouts`三个参数。
```
  virtual void calc(const BufferArgs& inputs,
                    const BufferArgs& outputs,
                    const BufferArgs& inouts) {}
```
其中`outputs`和 `inouts` 的区别是，如果Function计算结果赋值到output buffer是**Assign模式**，则会通过outputs来传递output buffer；如果计算结果是**Add模式**，则会通过inouts来传递output buffer。相应的Function::calc在实现上要通过判断参数来区分。
其中**add模式**主要包括如下一些场景：
1. 使用MixedLayer连接多个input buffer及Function到同一个output buffer，需要用inouts来传递output buffer；
2. 一个inputLayer链接多个outputLayer，每个outputLayer在调用backward Function时需要用inouts来传递inputGrad参数；

**Comment by tianbingsz** [comment]
@hedaoyuan , 对于1 MixedLayer, 为什么要用inouts， 这里的output是Assign还是Add？能否给个小例子？

**Comment by hedaoyuan** [comment]
MixedLayer只链接一个inputLayer到output，则只需要output = Function(input)；
如果连接多个，并对应多个Function则需要：
output = Function1(input1);
output += Function2(input2);

**Comment by tianbingsz** [comment]
我大概明白了。

**Comment by hedaoyuan** [comment]
**Function::calc() prototype**

**Comment by hedaoyuan** [comment]
**Function comments**

Function是Paddle Computation的抽象，被其他模块（Layer，ParameterUpdate等）调用，所以每个Function需要有清晰的注释，包括具体的实现，输入输出参数类型，以及Function对于output参数（ASSIGN_TO/ADD_TO）的支持等；注释的目的是能够让使用者不必阅读具体代码也能明白Function的实现逻辑并正确的调用。

一些基本的Function注释方法：
1. 如果Funciton实现来自于某篇论文公式，可在注释中注明来源和公式，并将Function的参数和公式的参数之间的关系描述清楚；
2. 参数的类型在注释中要说明清楚，以便调用者能够正确的输入参数；
