### ISSUE TITLE
随机数是否可以预测？

### ISSUE THREAD

**Issue by breaknormal1** [PaddlePaddle/Paddle#8925]
paddle的同学们，请教一下：
有一万笔数据可供训练，一千笔数据可用来测试；
每一笔都是从1~100随机抽取十个整数；
目的：预测下一轮的十个整数
问题：1.因为是随机抽取的整数，没有其他特征值，是否可以预测呢？比较担心这一点
2.可以预测的话，paddle有没有可用参考的模型？

**Comment by peterzhang2029** [comment]
如果数据中没有一定的统计规律的话，类似图像或者文本，感觉使用深度学习方法还是很难进行预测的。

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
