### ISSUE TITLE
'module' object has no attribute 'sparse_float_vector'

### ISSUE THREAD

**Issue by adrianhust** [PaddlePaddle/Paddle#8926]
Hi, 
log:
Fri Mar  9 16:07:32 2018[1,0]<stderr>:  File "conf/trainer_config.conf", line 84, in main
Fri Mar  9 16:07:32 2018[1,0]<stderr>:    name="input", type=paddle.data_type.sparse_float_vector(dict_size))
Fri Mar  9 16:07:32 2018[1,0]<stderr>:AttributeError: 'module' object has no attribute 'sparse_float_vector'
code:
`    input = paddle.layer.data(
        name="input", type=paddle.data_type.sparse_float_vector(dict_size))`
  `  label = paddle.layer.data("label", paddle.data_type.integer_value(class_dim))`

paddle on mpi cluster not support this api, any api doc to refer?
input data is like, sparse float sequence:
<img width="1014" alt="data6137e82f66b869600b18ce677" src="https://user-images.githubusercontent.com/1840577/37198550-a8c8a61c-23b9-11e8-9c00-f1dfdc4b24bb.png">

help! thank you!

**Comment by Yancey1989** [comment]
It has been renamed by #4968, you can try `data_type.sparse_vector ` for the older version.
