### ISSUE TITLE
CAPI - Example on how to infer Caffe trained AlexNet with Paddle CAPI

### ISSUE THREAD

**Issue by jczaja** [PaddlePaddle/Paddle#8936]
Hi,

I made an example on how to use CAPI for alexnet inference to test CAPI. It is havily based on caffe's cpp_classification example. I made it for my own understanding of CAPI . So I'm sharing it here, hopefully it will be useful:

https://github.com/jczaja/test-paddle-c-api

Usage(rough instruction):
1) Get model(params) of BVLC_alexnet from caffe and convert to paddle with caffe2paddle
2) Run: convert_
3) Next to executable, make directory: Paddle_bvlc_alexnet and put converted model inside
./test-paddle <name of picture eg. cat.jpg>

Notes:
- Model(params) is taken from BVLC/caffe and its config was manually crafted to correspond to caffe one.
- dropout in caffe and paddle are implemented diffrently and to make paddle producing the same results in inference , model(config) was updated with slope_intercept_layer.
- On few images (taken from caffe/examples/images) I got the same top-1 prob of paddle match prob of caffe.

**Comment by peterzhang2029** [comment]
Thank you very much for your contribution !  It will be very helpful.
