### ISSUE TITLE
A experiment of fuse all optimize op to one

### ISSUE THREAD

**Issue by jacquesqiao** [PaddlePaddle/Paddle#8941]
## Background
In fluid's current design, the last part of a program is optimization related operators. For example, in [se_resnext](https://github.com/dzhwinter/benchmark/pull/84) example, the last operators are a list of SGD as timeline shows below:
![image](https://user-images.githubusercontent.com/3048612/37140670-89bd698c-22ed-11e8-8271-b88841e15a79.png)

After discuss with @chengduoZH @panyx0718, we think that currently, these little ops will waste a lot of time launching kernels, so maybe we can fuse these little ops into a big one. 

There is two part of things to do:
1. Add a fused SGD op that it takes a list of parameter, gradient and learning rate as the input. This is done by @chengduoZH in PR https://github.com/PaddlePaddle/Paddle/pull/8869. 
2. Add a fuse transpiler to fuse all SGD op into the big one. This is done in PR https://github.com/PaddlePaddle/Paddle/pull/8940.

## Experiment result
- Timeline after the fusing.
![image](https://user-images.githubusercontent.com/3048612/37213027-cfa42ea0-23eb-11e8-8d3c-be5b3f0e4a59.png)

- Running time for all SGD ops.  The running time has been reduced by half. There are still promotion space if we can merge all CUDA kernel into one in the sgd_group op.

![image](https://user-images.githubusercontent.com/3048612/37213017-c9e20d34-23eb-11e8-80aa-fc64bbd26b9d.png)

## Notice
This is just an experiment for one kind of solution, there are many other solutions, for example, multi-thread async execution that need to discuss.

**Comment by chengduoZH** [comment]
That is awesome!
 I will try to use only one CUDA kernel do all the SGD operations.
