### ISSUE TITLE
移除Accuracy之后，Fluid怎么使用了？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8942]
我使用了最新的PaddlePaddle，在使用Fluid的时候发现报错
```
accuracy = fluid.evaluator.Accuracy(input=out, label=label)
AttributeError: 'module' object has no attribute 'Accuracy'
```
一步步查看才知道在 #8643 已经去掉了Accuracy，那么https://github.com/PaddlePaddle/models/blob/df8060e7022fcac12fd33a8adf098c0663d8152d/fluid/image_classification/mobilenet.py 这个例子怎办?
比如这些怎么处理
```
accuracy = fluid.evaluator.Accuracy(input=out, label=label)

accuracy.reset(exe)

pass_acc = accuracy.eval(exe)
```

**Comment by peterzhang2029** [comment]
新的accuracy接口使用可见示例：https://github.com/PaddlePaddle/Paddle/blob/87568cfd96d8f5c886e2fff3d4d6090f190292f7/python/paddle/fluid/tests/book_memory_optimization/test_memopt_image_classification_train.py#L126 上述例子的模型有的还在完善当中，会陆续进行修改的。

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
怎么又多了这两行代码，其中`batch_size `是否可以手动指定为128，`batch_acc `有何用处的？
https://github.com/PaddlePaddle/Paddle/blob/87568cfd96d8f5c886e2fff3d4d6090f190292f7/python/paddle/fluid/tests/book_memory_optimization/test_memopt_image_classification_train.py#L125-L126

然后是应该使用
https://github.com/PaddlePaddle/Paddle/blob/87568cfd96d8f5c886e2fff3d4d6090f190292f7/python/paddle/fluid/tests/book_memory_optimization/test_memopt_image_classification_train.py#L149
代替
```python
 accuracy = fluid.layers.Accuracy(input=out, label=label)
```
吗？
测试的如果创建`test_accuracy`，之前版本为
```python
with fluid.program_guard(inference_program):
    test_accuracy = fluid.evaluator.Accuracy(input=out, label=label)
    test_target = [avg_cost] + test_accuracy.metrics + test_accuracy.states
    inference_program = fluid.io.get_inference_program(test_target)
```

**Comment by peterzhang2029** [comment]
batch_acc在对每个batch计算的时候能取到当前batch里面样本的个数，从而来求平均的准确率， 具体可以在迭代的时候输出结果看一下，如果需要test_accuracy可以参考 https://github.com/JiayiFeng/Paddle/blob/ea508c9ef276192e66ac93b8ea48af2e76385d2d/benchmark/cluster/vgg16/vgg16_fluid.py#L146

**Comment by yeyupiaoling** [comment]
@peterzhang2029 
batch_size是否可以手动指定为128，例子的是这样的
https://github.com/PaddlePaddle/Paddle/blob/87568cfd96d8f5c886e2fff3d4d6090f190292f7/python/paddle/fluid/tests/book_memory_optimization/test_memopt_image_classification_train.py#L125

还有优化方法好像没有使用到
https://github.com/PaddlePaddle/Paddle/blob/87568cfd96d8f5c886e2fff3d4d6090f190292f7/python/paddle/fluid/tests/book_memory_optimization/test_memopt_image_classification_train.py#L122-L123

**Comment by JiayiFeng** [comment]
@yeyupiaoling 你好，非常抱歉我们在去掉Fluid中的`Accuracy`之后，没有对models中的例子进行及时更新，对您的使用造成了困扰。

对models中例子的更新已经开始，估计这两天就可以发出pr。pr merge后，我会在这个issue下回复告知。

再次感谢您对Paddle Fluid的关注，谢谢！

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
哈哈，通过不断提issue，我已经跑通了训练部分，但是预测部分还是不懂，请赐教 #8938

**Comment by yeyupiaoling** [comment]
@peterzhang2029 @JiayiFeng 
能否也解答这个问题https://github.com/PaddlePaddle/models/issues/703#issuecomment-371832868

**Comment by wangkuiyi** [comment]
非常感谢 @yeyupiaoling 的这些 issue和这些讨论。不仅帮助paddlepaddle团队定位问题，督促我们完善系统，也让日后碰到类似的问题的朋友们可以通过搜索issues内容得到答案。
