### ISSUE TITLE
Check failed: cudaSuccess == cudaStat (0 vs. 2) Cuda Error: out of memory

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#8949]
![image](https://user-images.githubusercontent.com/15224527/37239583-5faa20a8-2479-11e8-9386-2c218ee05994.png)

**Comment by reyoung** [comment]
这个看起来是显存耗尽了。

**Comment by wangkuiyi** [comment]
显存耗尽有很多可能的原因。比如在一个GPU上同时跑多个进程，或者一个进程使用了超过这个GPU的显存的空间。
