### ISSUE TITLE
Fluid版本如何在训练之前加载之前训练好的模型

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8973]
For example，Paddle load model is：
```python
parameters = paddle.parameters.Parameters.from_tar(f)
```
And in the FIuid infer is:
```
[inference_program, feed_target_names, fetch_targets] = fluid.io.load_inference_model(model_path, exe)
```

**But I need train load model**

**Comment by JiayiFeng** [comment]
在Fluid中，模型由一个或多个program来表示，program包含了block，block中包含了op和variable。

在保存模型时，program--block--{op, variable}这一系列的拓扑结构会被保存成一个文件，variable具体的值会被保存在其他文件里。

所以，保存一个训练中的模型，你需要做两步：
1. 保存program：
```python
with open(filename, "wb") as f:
        f.write(program.desc.serialize_to_string())
```
2. 保存program中各个persistable的varibale的值：
```python
fluid.io.save_persistables(executor, dirname, main_program)
```
其中`main_program`就应该是刚刚被保存的那个program。

同样，从保存的文件中恢复，也需要两步：
1. 恢复program：
```python
with open(filename, "rb") as f:
        program_desc_str = f.read()
program = Program.parse_from_string(program_desc_str)
```
2. 恢复persistable的variable：
```python
load_persistables(executor, dirname, main_program)
```
同样，main_program应当是刚刚恢复出来的那个program。

然后，program就可以放到`exe.run()`里面去做正常的训练了。

如果还有问题，欢迎继续回复。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 

保存模型
-----
我在例子中看到的保存模型是这样的，没看到您说`main_program`
https://github.com/PaddlePaddle/models/blob/develop/fluid/image_classification/mobilenet.py#L214
```
fluid.io.save_inference_model(model_path, ['image'], [out], exe)
```

恢复模型
-----
是不是把下面代码替换之前的
```
with open(filename, "rb") as f:
        program_desc_str = f.read()
program = Program.parse_from_string(program_desc_str)

loss, acc, weight = exe.run(program,
                    feed=feeder.feed(data),
                    fetch_list=[avg_cost, batch_acc, batch_size])
```
之前的
```
loss, acc, weight = exe.run(fluid.default_main_program(),
                    feed=feeder.feed(data),
                    fetch_list=[avg_cost, batch_acc, batch_size])
```
但是感觉不太对，保存的我是按照例子的做的，所以只有保存一次，你的保存的是两次，所以我觉得我的恢复模型不对

**Comment by JiayiFeng** [comment]
@yeyupiaoling 
`save_inference_model`内部也是调用了我说的那两个接口。另外，在调用这两个接口之前，`save_inference_model`还会做一些模型裁剪的工作，裁减掉backward的部分。backward部分对于inference来说不需要，但对模型的继续训练是需要的。因此save_inference_model这个封装并不适用与你的需求。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
对模型的继续训练有什么好的封装的接口吗？我觉得那样太麻烦了
顺便问一下，`load_persistables(executor, dirname, main_program)`的`load_persistables`完整路径是什么？是不是`paddle.fluid.load_persistables`

**Comment by JiayiFeng** [comment]
目前还没有。但目前模型的io这块我们正在进行比较大的优化，所以未来应该会有。

最完整的路径是paddle.fluid.io.load_persistables。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
好的，Thank you so much. 这是我写的博客http://blog.csdn.net/qq_33200967/article/details/79126897 ，还没有完成，这个还没完成，特别是预测部分。

**Comment by JiayiFeng** [comment]
非常感谢你对Fluid的关注，我们会尽快完成这部分的优化开发

**Comment by JiayiFeng** [comment]
感谢你对Fluid的关注。目前的底层API使用上确实不方便，也不完整，是一种比较hacky的方法，可能确实不适宜放在博客上。我们会尽快完整这部分的优化开发，尽快向你提供成型的高层API。

**Comment by yeyupiaoling** [comment]
好，就不把这一部分写上去，等完善后再加，那我一直开着issue，等您回复！

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
是否提供了保存训练模型的接口？不是预测模型的接口。

**Comment by JiayiFeng** [comment]
没有很理解你说的“保存训练模型”指的是什么。模型保存下来的目的是什么？

**Comment by JiayiFeng** [comment]
没有太理解你的意思。模型保存下来不是为了预测，那么我的理解是为了继续训练？这不就是我们在这个issue里面一直在讨论的问题么？目前这部分的高层接口还不ready。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
好的，Fluid迭代更新那么快，过了那么多天，我就想问问完成没有而已。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 我又来问一下，这个接口完成了吗？

**Comment by yeyupiaoling** [comment]
@JiayiFeng 
## 保存训练参数
如果要保存训练使用的模型参数，是不是应该调用以下的保存方式：
https://github.com/PaddlePaddle/Paddle/blob/16b09d3c368cd6758bf77456da9fd45b1d31ff81/python/paddle/fluid/io.py#L129-L139

## 加载参数
在训练之前，如果想在这个模型参数基础之上在训练，应该调用以下的方法：
https://github.com/PaddlePaddle/Paddle/blob/16b09d3c368cd6758bf77456da9fd45b1d31ff81/python/paddle/fluid/io.py#L221-L230

那么我拿到了参数，如果加到主程序中呢？

**Comment by JiayiFeng** [comment]
最近我们正在对Fluid的API进行一个比较大的简化，模型的保存和加载是改动的重点。预计会在六月份完成。这之后应该对这个issue中的各种问题都会有个比较明确简单的解法。

相关的讨论和总体设计：https://github.com/PaddlePaddle/Paddle/issues/10248

**Comment by chengyuz** [comment]
你好，我将caffemodel转化为fluid做finetune，然后报错：
----------- vgg Configuration Arguments -----------
batch_size: 128
data_format: NCHW
data_set: cifar10
device: GPU
iterations: 80
learning_rate: 0.001
pass_num: 50
skip_batch_num: 5
with_test: False
------------------------------------------------
/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/average.py:42: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)
Traceback (most recent call last):
  File "vgg16.py", line 301, in <module>
    main()
  File "vgg16.py", line 263, in main
    fetch_list=[avg_cost])
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 333, in run
    fetch_var_name=fetch_var_name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 232, in _add_feed_fetch_ops
    out = global_block.var(name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 725, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var img not in this block
其中var img是数据输入层

**Comment by chengyuz** [comment]
@JiayiFeng ，你好，我将caffemodel转化为fluid的形式做finetune，然后报错：
----------- vgg Configuration Arguments -----------
batch_size: 128
data_format: NCHW
data_set: cifar10
device: GPU
iterations: 80
learning_rate: 0.001
pass_num: 50
skip_batch_num: 5
with_test: False
------------------------------------------------
/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/average.py:42: Warning: The WeightedAverage is deprecated, please use fluid.metrics.Accuracy instead.
  (self.__class__.__name__), Warning)
Traceback (most recent call last):
  File "vgg16.py", line 301, in <module>
    main()
  File "vgg16.py", line 263, in main
    fetch_list=[avg_cost])
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 333, in run
    fetch_var_name=fetch_var_name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 232, in _add_feed_fetch_ops
    out = global_block.var(name)
  File "/home/yczhao/anaconda2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 725, in var
    raise ValueError("var %s not in this block" % name)
ValueError: var img not in this block
其中var img是模型数据层名称

**Comment by JiayiFeng** [comment]
@chengyuz 你好。你的问题和这个issue的主题不完全一致。请发一个新的issue说明你的操作和遇到的问题。会有值班同学负责assign和进行处理。

**Comment by chengyuz** [comment]
@JiayiFeng 发了一个新issue，thx

**Comment by chengyuz** [comment]
@JiayiFeng 发了一个issue，麻烦看一下，thx（https://github.com/PaddlePaddle/Paddle/issues/10998）

**Comment by chengduoZH** [comment]
issue中的问题已转到#10998

**Comment by ahsdx** [comment]
> 在Fluid中，模型由一个或多个program来表示，program包含了block，block中包含了op和variable。
> 
> 在保存模型时，program--block--{op, variable}这一系列的拓扑结构会被保存成一个文件，variable具体的值会被保存在其他文件里。
> 
> ## 保存模型
> 保存一个训练中的模型，你需要做两步：
> 
> 1. 保存program：
> 
> ```python
> with open(filename, "wb") as f:
>         f.write(program.desc.serialize_to_string())
> ```
> 
> 1. 保存program中各个persistable的varibale的值：
> 
> ```python
> fluid.io.save_persistables(executor, dirname, main_program)
> ```
> 
> 其中`main_program`就应该是刚刚被保存的那个program。
> 
> ## 恢复模型
> 同样，从保存的文件中恢复，也需要两步：
> 
> 1. 恢复program：
> 
> ```python
> with open(filename, "rb") as f:
>         program_desc_str = f.read()
> program = Program.parse_from_string(program_desc_str)
> ```
> 
> 1. 恢复persistable的variable：
> 
> ```python
> load_persistables(executor, dirname, main_program)
> ```
> 
> 同样，main_program应当是刚刚恢复出来的那个program。
> 
> 然后，program就可以放到`exe.run()`里面去做正常的训练了。
> 
> 如果还有问题，欢迎继续回复。
请问下这个filename是已存在文件的路径吗？我填写'/home/aistudio/work/programs/program'报错了，我的programs文件夹是存在的，但program不存在。请问怎么解决啊

**Comment by ahsdx** [comment]
> 在Fluid中，模型由一个或多个program来表示，program包含了block，block中包含了op和variable。
> 
> 在保存模型时，program--block--{op, variable}这一系列的拓扑结构会被保存成一个文件，variable具体的值会被保存在其他文件里。
> 
> ## 保存模型
> 保存一个训练中的模型，你需要做两步：
> 
> 1. 保存program：
> 
> ```python
> with open(filename, "wb") as f:
>         f.write(program.desc.serialize_to_string())
> ```
> 
> 1. 保存program中各个persistable的varibale的值：
> 
> ```python
> fluid.io.save_persistables(executor, dirname, main_program)
> ```
> 
> 其中`main_program`就应该是刚刚被保存的那个program。
> 
> ## 恢复模型
> 同样，从保存的文件中恢复，也需要两步：
> 
> 1. 恢复program：
> 
> ```python
> with open(filename, "rb") as f:
>         program_desc_str = f.read()
> program = Program.parse_from_string(program_desc_str)
> ```
> 
> 1. 恢复persistable的variable：
> 
> ```python
> load_persistables(executor, dirname, main_program)
> ```
> 
> 同样，main_program应当是刚刚恢复出来的那个program。
> 
> 然后，program就可以放到`exe.run()`里面去做正常的训练了。
> 
> 如果还有问题，欢迎继续回复。



还有请问一些，恢复训练时，需要start_program = fluid.default_startup_program()操作吗？还是不需要
