### ISSUE TITLE
How paddlepaddle use CPU or GPU in the Fluid

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#8974]
In Paddle 1,we can do that:
```python
paddle.init(use_gpu=False, trainer_count=2)
```
In Fluid maybe is this line:
```python
place = fluid.CUDAPlace(0) if use_cuda else fluid.CPUPlace()
```
But where is `trainer_count`

**Comment by JiayiFeng** [comment]
The `trainer_count` is used to sets the number of training threads. In Fluid, we use `parallel_do` to represent multithread data parallel processing. 

Here are some examples about how to use it:

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_recognize_digits.py#L80

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_word2vec.py#L93

https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/book/test_understand_sentiment.py#L156

**Comment by yeyupiaoling** [comment]
I don't quite understand. But thank you for your answer. Let me think about it.
