### ISSUE TITLE
Record links of all .md files in the fluid directory

### ISSUE THREAD

**Issue by weixing02** [PaddlePaddle/Paddle#8976]
related #8587 
links of all .md files in the fluid directory:

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/memory/README.md

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/rnn_design.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/net_op_design.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/name_convention.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/batch_norm_op.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/op_markdown_format.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/variable.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/tensor.md

 

- https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/lod_tensor.md

**Comment by shanyi15** [comment]
我归纳的分类，欢迎大家提议

1.  https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/memory/README.md

基于区域的异构内存管理 是design doc
2. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/rnn_design.md
RNN 变长输入设计 是design doc
3. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/net_op_design.md
网络设计 是design doc
4. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/name_convention.md
operator参数命名规范 建议放在“开发标准”

5. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/batch_norm_op.md
批归一化 是不是放在“进阶使用”里？
6. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/operators/op_documentation/op_markdown_format.md
Operators标准md格式 是不是放在“开发标准”？

7. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/variable.md
变量 是设计文档还是基本使用概念？
8. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/tensor.md
张量 是设计文档还是基本使用概念？
9. https://github.com/PaddlePaddle/Paddle/tree/develop/paddle/fluid/framework/lod_tensor.md
LODz张量 这个也许更偏向于“设计文档”

**Comment by luotao1** [comment]
> Operators标准md格式 是不是放在“开发标准”？

请 @ranqiu92 和 API注释标准 #8927 一起考虑下。

> 变量 是设计文档还是基本使用概念？

variable, tensor, lod_tensor都属于设计文档里的核心概念。

**Comment by shanyi15** [comment]
doc/design目录下的文档整理 keep updating......
1. 
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/build_system/README.md
看起来是一篇和Cmake编译有关的设计文档 但较口语化 不建议放在官网
2.以下几篇在“集群训练”目录下 
Design Doc: Distributed Training
（1） https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/README.md
分布式训练 设计文档
（2）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/checkpointing.md
模型参数检查点
（3）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/data_dispatch.md
训练数据的存储和分发
（4）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/large_model_dist_train.md
用Paddle进行大模型分布式训练的分析 这篇应该是v1的文档
（5）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/master_server.md
Design Doc: Master Server 一篇设计文档 
（6）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/pserver_client.md
Design Doc: The Client Library of Parameter Server 一篇设计文档
（7）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/remote_parameter_updater.md
Design Doc: Remote Parameter Updater for Cluster Train 一篇设计文档
（8）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/save_model.md
Design Doc: Save Model 一篇设计文档
（9）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/cluster_train/submit-job.md
Submit a Distributed Training Job 提交分布式训练任务 进阶使用or设计文档？
3. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist_refactor/distributed_architecture.md
Design Doc: Distributed Training Architecture 
4. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist_refactor/multi_cpu.md
Design Doc: Execute the Program with Multi CPU
5. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/dist_refactor/parameter_server.md
Design Doc: Parameter Server
6. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/file_manager/pfs/pfsclient.md
PFSClient
7. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/file_manager/README.md
FileManager设计文档
8. 多语言接口
（1）https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/multi_language_interface/00.why_plain_c.md
Paddle多语言接口实现 
（2） https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/multi_language_interface/01.inference_implementation.md
C-API 模型推断实现文档
9. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/ops/rnn.md
RNNOp design
10. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/ops/sequence_decoder.md
Design: Sequence Decoder Generating LoDTensors
11. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/reader/README.md
Python Data Reader Design Doc
12. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/speech/deep_speech_2.md
DeepSpeech2 on PaddlePaddle: Design Doc
13. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/api.md
**PaddlePaddle Design Doc**
14. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/auto_gradient_check.md
Auto Gradient Check Design
15. https://github.com/PaddlePaddle/Paddle/blob/develop/doc/design/backward.md
Backward Building 后向构建，设计文档？
-----------------
the following contents keep updating

**Comment by shanyi15** [comment]
> 批归一化
jiayi说批归一化放设计文档，用户看这个太深了
