### ISSUE TITLE
use_eigen_cn.md 文档中的链接指向了错误的代码位置

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#8979]
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/use_eigen_cn.md
中 更多的转换方法请参考eigen_test.cc中的  “单元测试“
单元测试链接 https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/framework/eigen_test.cc 目前为404.
新的代码地址应该是 paddle/fluid/framework/eigen_test.cc

建议 做一个文档中链接的自动检查，可以通过自动方式检查 文档中链接代码出现的死链。

**Comment by lgone2000** [comment]
英文的文档 也有同样问题
https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev//use_eigen_en.md

**Comment by JiayiFeng** [comment]
已经在处理中。非常感谢您的反馈！

**Comment by luotao1** [comment]
非常感谢您的反馈，目前官网上的所有文档(http://www.paddlepaddle.org/docs/develop/documentation/zh/getstarted/index_cn.html )已经加了文档链接的自动检测。对没有放入官网的文档，暂时还没有做这部分工作，等fluid文档整体上线前，我们也会增加这部分检测的。不过这个issue我们会先修复的。
