### ISSUE TITLE
Pass 6, Batch 0, Cost 0.848673, {'classification_error_evaluator': 0.53125}  batchid为何一直是0

### ISSUE THREAD

**Issue by 930083287** [PaddlePaddle/Paddle#8982]
![image](https://user-images.githubusercontent.com/15224527/37262120-204b8d98-25dc-11e8-9aec-55b55cf0aed1.png)

**Comment by typhoonzero** [comment]
可能是你的训练数据的总量 <= batch_size

**Comment by 930083287** [comment]
在train函数中，for batch_id, data_batch in enumerate(reader()): reader()的长度是32，不知为何不能继续枚举？
