### ISSUE TITLE
What are TrainerConfig_pb2 and ModelConfig_pb2 in folder paddle.proto and where are they?

### ISSUE THREAD

**Issue by Meloneat** [PaddlePaddle/Paddle#9007]

**Comment by Meloneat** [comment]
l get the problem of 'No module named TrainerConfig_pb2' and l can't find them in the python files.

**Comment by luotao1** [comment]
After you `make gen_proto_py`, these files will be generated, and you will find them in `/python/paddle/proto` folder.
