### ISSUE TITLE
需要文档来介绍evaluators

### ISSUE THREAD

**Issue by iamadog3333** [PaddlePaddle/Paddle#9029]
need docs for kinds of evaluators
需要文档来介绍evaluators

比如在models里面的ner标注的例子，里面用了evaluators

import paddle.v2.evaluator as evaluator

evaluator.sum(name="error", input=crf_dec)
    evaluator.chunk(
        name="ner_chunk",
        input=crf_dec,
        label=target,
        chunk_scheme="IOB",
        num_chunk_types=(label_dict_len - 1) / 2)

但是这里面是如何计算的error，以及如何修改，还有哪些evaluators种类,   找不到文档。

**Comment by shanyi15** [comment]
Please refer to API documentation-Evaluators
http://www.paddlepaddle.org/docs/develop/api/en/config/evaluators.html
