### ISSUE TITLE
建议对python/paddle/trainer_config_helpers/math.py进行更名

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#903]
目前在写网络config时，都会使用from paddle.trainer_config_helpers import *，此时会将python/paddle/trainer_config_helpers/math.py导入命名空间，与python自带的math库发生名字冲突。一方面由此引发报错时很难追查，另一方面如果需要同时使用二者时，会比较麻烦。因此建议对该文件名进行修改，或在python/paddle/trainer_config_helpers/__init__.py将import math修改为import math as NEW_NAME

该问题已导致SRL demo无法运行：db_lstm.py中先导入系统库math，然后通过from paddle.trainer_config_helpers import * 意外导入paddle.trainer_config_helpers.math，将系统库math覆盖，引起db_lstm.py第116行找不到sqrt()定义。

**Comment by reyoung** [comment]
有道理。

**Comment by pengli09** [comment]
#922 的解法还是不能正确解决这个问题，#922 只是又额外引入了一个新名字layer_math，import *的时候还是会把math导入到当前命名空间中。
