### ISSUE TITLE
A deadlink in the distributed training design doc.

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#9032]
When I read this design doc https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/design/dist_train/distributed_architecture.md , I found there is a deadlink in it:

![image](https://user-images.githubusercontent.com/5842774/37350229-33d1b328-2713-11e8-8a5f-1b6594981f31.png)

**Comment by typhoonzero** [comment]
Thanks for reporting, I submitted a PR to fix this.
