### ISSUE TITLE
all supported ops for fluid

### ISSUE THREAD

**Issue by wangyang59** [PaddlePaddle/Paddle#9036]
Hi there,

I am trying to use the new Fluid api to implement a project. I was just wondering if there is a place I can find all of the ops available in Fluid?

For example it seems that Paddle/paddle/fluid/operators/scatter.h is not documented in http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html. Is it available to use?

Thank you very much for your help!

Best,
yang

**Comment by shanyi15** [comment]
hi, please refer to 
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#permalink-79-ops
and 
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#permalink-35-nn

**Comment by dzhwinter** [comment]
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html contains all of the current operators. 
Scatter op is not exported yet.
