### ISSUE TITLE
install nuisance of paddlepaddle on mac

### ISSUE THREAD

**Issue by buaawht** [PaddlePaddle/Paddle#9039]
mac OS: 10.11.6
python : 2.7.14
pip : 9.0.1

I want install the paddle on my mac so that to use my Pycharm.

when i use `pip install paddlepaddle ` it gives: `Could not find a version that satisfies the requirement paddlepaddle (from versions: ) No matching distribution found for paddlepaddle`. So I want build paddle from sources and I get the solution from [Build from Sources(http://www.paddlepaddle.org/docs/develop/documentation/en/build_and_install/build_from_source_en.html) but it hinted the protobuf version is < 3.0.0. But I use `pip show protobuf` and it gives `Version: 3.5.2`. 

So how can  i install paddle on my mac so that the IDE can auto-complete the code. please help me. Thanks.

**Comment by buaawht** [comment]
I use `pip install paddlepaddle` to install paddlepaddle, but it failed. And I download `paddlepaddle-0.11.0-cp27-cp27m-linux_x86_64.whl` and use `pip install paddlepaddle-0.11.0-cp27-cp27m-linux_x86_64.whl`. It failed too. I think maybe because of the version of mac OS(10.11.6). I am not sure.

**Comment by seiriosPlus** [comment]
I find `paddlepaddle-0.11.0-cp27-cp27m-macosx_10_12_x86_64.whl`  on `https://pypi.python.org/pypi/paddlepaddle/0.11.0`, you can have a try.
