### ISSUE TITLE
V1能跑的结构和数据，迁移到V2跑的时候，经常跑到中途出core

### ISSUE THREAD

**Issue by lyp2github** [PaddlePaddle/Paddle#9042]
Mar 13 20:36:57 2018[1,26]<stdout>:Test with Pass 32, Cost 0.4533, matrics {}
Tue Mar 13 20:37:04 2018[1,0]<stderr>:*** Aborted at 1520944624 (unix time) try "date -d @1520944624" if you are using GNU date ***
Tue Mar 13 20:37:04 2018[1,0]<stderr>:PC: @                0x0 (unknown)
...
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @           0x4b6c52 PyEval_EvalCode
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @           0x4e1c7d PyRun_FileExFlags
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @           0x4e3501 PyRun_SimpleFileExFlags
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @           0x4159dd Py_Main
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @     0x7f6183e2bbd5 __libc_start_main
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @           0x414b71 (unknown)
Tue Mar 13 20:37:04 2018[1,24]<stderr>:    @                0x0 (unknown)
Tue Mar 13 20:37:05 2018[1,13]<stderr>:./train.sh: line 239: 14794 Segmentation fault      python27-gcc482/bin/python conf/trainer_config.conf
Tue Mar 13 20:37:05 2018[1,13]<stderr>:+ '[' 139 -ne 0 ']'
Tue Mar 13 20:37:05 2018[1,13]<stderr>:+ kill_pserver2_exit

**Comment by yeyupiaoling** [comment]
@lyp2github 
是不是梯度中途出错了，调一下超参数试试
