### ISSUE TITLE
本地测试总是内存错误，有什么方法可以避免么？

### ISSUE THREAD

**Issue by wrchow** [PaddlePaddle/Paddle#9050]
F0314 12:03:39.361496 32630 Allocator.h:56] Check failed: posix_memalign(&ptr, 32ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7fab78790d2d  google::LogMessage::Fail()
    @     0x7fab787947dc  google::LogMessage::SendToLog()
    @     0x7fab78790853  google::LogMessage::Flush()
    @     0x7fab78795cee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fab786c7345  paddle::CpuAllocator::alloc()
    @     0x7fab786ae79f  paddle::PoolAllocator::alloc()
    @     0x7fab786ae266  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7fab786d5df7  paddle::CpuMatrix::CpuMatrix()
    @     0x7fab786d60a6  paddle::Matrix::create()
    @     0x7fab786e5d21  paddle::Matrix::resizeOrCreate()
    @     0x7fab784b7a77  paddle::Layer::resetSpecifyOutput()
    @     0x7fab784b7cf4  paddle::Layer::resetOutput()
    @     0x7fab7849c3a1  paddle::MixedLayer::forward()
    @     0x7fab7854612d  paddle::NeuralNetwork::forward()
    @     0x7fab783f06ad  _wrap_GradientMachine_forward
    @     0x7faba6c6cbad  PyEval_EvalFrameEx
    @     0x7faba6c6dc3e  PyEval_EvalCodeEx
    @     0x7faba6c6d1f7  PyEval_EvalFrameEx
    @     0x7faba6c6dc3e  PyEval_EvalCodeEx
    @     0x7faba6c6d1f7  PyEval_EvalFrameEx
    @     0x7faba6bdd39c  gen_send_ex
    @     0x7faba6c674f1  PyEval_EvalFrameEx
    @     0x7faba6bdd39c  gen_send_ex
    @     0x7faba6c674f1  PyEval_EvalFrameEx
    @     0x7faba6c6dc3e  PyEval_EvalCodeEx
    @     0x7faba6c6d1f7  PyEval_EvalFrameEx
    @     0x7faba6c6dc3e  PyEval_EvalCodeEx
    @     0x7faba6c6d1f7  PyEval_EvalFrameEx
    @     0x7faba6c6d345  PyEval_EvalFrameEx
    @     0x7faba6c6dc3e  PyEval_EvalCodeEx
    @     0x7faba6c6dd52  PyEval_EvalCode
    @     0x7faba6c8e450  PyRun_FileExFlags

**Comment by dzhwinter** [comment]
请您提供一下系统信息，环境信息，使用的版本等等

**Comment by wrchow** [comment]
Linux version 3.10.0_1-0-0-8 (whistler@www.local) (gcc version 4.9.2 20150212 (Red Hat 4.9.2-6) (GCC) ) #1 SMP Thu Mar 24 15:26:50 CST 2016

cpu: 4

MemTotal:       16435140 kB
MemFree:        11509660 kB
MemAvailable:   12689664 kB


canoe (0.1.1)              - Carve out log files and paddle
paddlepaddle-gpu (0.11.0)  - Parallel Distributed Deep Learning
paddle (1.0.2)             - A package for dictionary learning
paddlepaddle (0.11.0)      - Parallel Distributed Deep Learning
  INSTALLED: 0.10.7
  LATEST:    0.11.0

**Comment by dzhwinter** [comment]
posix_memalign 返回错误为12，"Out of Memory".  https://www.systutorials.com/docs/linux/man/3-posix_memalign/#lbAE
可能是安装有问题？

> paddlepaddle (0.11.0) - Parallel Distributed Deep Learning

把这个卸载了试试

**Comment by wrchow** [comment]
把样本从2w降低到2k 可以跑了

**Comment by dzhwinter** [comment]
An OOM error. fixed by reducing the model size.
