### ISSUE TITLE
调用paddlepaddle中的paddle.v2.image 出现问题

### ISSUE THREAD

**Issue by AkaShark** [PaddlePaddle/Paddle#9053]
环境是paddle提供的docker镜像 发生错误'NoneType' object has no attribute 'imread' 而且所用的OpenCV所有的API接口都出现了问题

**Comment by dzhwinter** [comment]
可否提供一下docker镜像版本呢？
> 所用的OpenCV所有的API接口都出现了问题 

可以提供一下你是怎么使用的吗？ 
参考一下导出的api
https://github.com/PaddlePaddle/Paddle/blob/24509f4af942bb250564756ad636691c7921e1df/python/paddle/v2/image.py

**Comment by AkaShark** [comment]
是的就是调用cv2.imread就出现了错误，错误信息是 'NoneType' object has no attribute 'imread'、
 我用的paddle是这个月刚拉去的的应该是最新的。 希望您可以给予帮助 谢谢~

**Comment by yeyupiaoling** [comment]
@AkaShark 
参考这个编译，试试是否可行：http://blog.csdn.net/tengxing007/article/details/54380732

**Comment by yeyupiaoling** [comment]
@AkaShark 问题是否已解决，请反馈一下

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开。
