### ISSUE TITLE
Parallel.Do performance issue

### ISSUE THREAD

**Issue by reyoung** [PaddlePaddle/Paddle#9054]
In the current implementation, the logic of multi-GPU using Parallel.Do is like below

```python
w1 = Variable()  # var in GPU 0
w2 = Variable()  # var in GPU 0

with Parallel.Do() as pd:
  hidden = fc(w1)  # fc will run on all devices
  hidden = fc(w2) # fc will run on all devices
  loss = ...
  pd.write_output(loss)

loss = mean(pd.output())  # loss in GPU 0
minimize(loss)  # minimize losss
```

Only forward and backward are running on multiple GPUs. The optimization stage, i.e. `SGD`, is running on the GPU0. It because `ProgramDesc` lacks device ID in variables. We cannot describe all GPUs will do the optimization. We can avoid broadcast parameters on the second mini-batch if we optimize parameter on every GPUs.

A straightforward solution is moving backward and optimization inside the `Parallel.Do`, like

```python
w1 = Variable()  # var in GPU 0
w2 = Variable()  # var in GPU 0

with Parallel.Do() as pd:
  hidden = fc(w1)  # fc will run on all devices
  hidden = fc(w2) # fc will run on all devices
  loss = ...
  pd.write_output(loss)
  loss = mean(pd.output())  # loss in GPU 0
  minimize(loss)  # minimize losss
```

There are several problems:

1. Fluid does not support backward inside a Block. It can be implemented in 2-3 days. However, it is hard to define how to backward in a child block. For example
     ```python
     hidden = fc()  # 1
     hidden = fc()  # 2
     with Parallel.Do as pd:
          hidden = fc()  # 3
          backward()
     ```
    Should this backward including the `#1` and `#2` fc? If the backward should include the `#1` and `#2` fc, should this backward include `Parallel.Do`? Is this backward of `Parallel.Do` as same as plain backward logic?

2. The `coeff` of backward in each devices is not `1`. It should be `1/N`, where `N` is the count of running devices. At the end of an epoch/pass, the mini-batch of data could be very tiny. It could be 4 GPUs and 3 samples. The count of running devices should be `std::min(NumDevices, NumSamples)`. It is hard to represent this logic in `ProgramDesc`.

3. We will use `reader` to feeding data on MultiGPUs. It will significantly speed up training process. However, get the count of running devices is harder if we are using readers. For example,
    ```python
    reader = ...
    if reader.eof():
       run[i] = False
    thread_barrier()  # CPU thread barrier
    count_of_running_devices = count(run, lambda x: x==True)
    ```
It is hard to represent `thead_barrier()` in `ProgramDesc`

So we propose to write a `ParallelExecutor`, which will take a `Program` and run it in multi-devices. It is hard to optimize speed and to think how to represent it in `ProgramDesc` at the same time.

**Comment by QiJune** [comment]
> It is hard to optimize speed and to think how to represent it in ProgramDesc at the same time.

Yes, so https://github.com/PaddlePaddle/Paddle/issues/8631 propose that we should separate expression and schedule. Because it's hard to make schedule differentiable, and keep high performance at the same time.

**Comment by panyx0718** [comment]
I kind of agree it from the implementation point of view that ParallelExecutor will be easier to implement some optimizations. But I have some questions:
1. Will the input preprocessing Ops and pipeline be part of the main program? If true, would ParallelExecutor run them in multiple GPUs? or will they be in different program?
2. Will the other logic (Save/Load/Distribution) have Ops in the main program? If true, would
they be treated specially?

I have one more concern that would like some comments from experts on the modeling side:

In the ParallelDo, users are allowed to configure part of the program to be parallel (multi-device)
while leave other part of the program to run on a single CPU or GPU.
In comparison, the new ParallelExecutor plans to run the whole main program in parallel on multi-device. Will there be some models that don't expect this? For example, will there be some more
dynamic models (GAN?) that wants fine-grained control on placement logic and scheduling logic?
@qingqing01 @lcy-seso @pkuyym

**Comment by tonyyang-svail** [comment]
Update: ParallelExecutor is implemented to support high-performance multi-GPU training.
