### ISSUE TITLE
parameters in API doc display wrong

### ISSUE THREAD

**Issue by shanyi15** [PaddlePaddle/Paddle#9055]
Here is the problem:
http://www.paddlepaddle.org/docs/develop/api/en/fluid/layers.html#ops
![image](https://user-images.githubusercontent.com/35982308/37387382-18e04492-2797-11e8-8d50-2b3f0dcf3c77.png)
It should be like this:
![image](https://user-images.githubusercontent.com/35982308/37387406-31905c66-2797-11e8-8016-9883a4caf7e3.png)

please repair it
thanks

**Comment by luotao1** [comment]
The documentation of ops are generated by `generate_layer_fn`
https://github.com/PaddlePaddle/Paddle/blob/95ea54fd7938b59483e81a57b69262e7efa410cd/python/paddle/fluid/layers/ops.py#L75-L76

**Comment by shanyi15** [comment]
This is a hard problem to solve, please lay it on the table.

**Comment by luotao1** [comment]
TensorFlow exists the same problem:
https://www.tensorflow.org/versions/r1.0/api_docs/python/tf/contrib/layers/separable_conv2d
![image](https://user-images.githubusercontent.com/6836917/37449836-bb0761f4-2866-11e8-8437-3db1c66958db.png)
