### ISSUE TITLE
CPU平台下编译paddlepaddle发生错误

### ISSUE THREAD

**Issue by zzhzz** [PaddlePaddle/Paddle#9057]
我在我的电脑上编译paddlepaddle develop分支时发生如下错误：

>Paddle/paddle/fluid/framework/attribute.h:23:49: fatal error: paddle/fluid/framework/framework.pb.h: No such file or directory
compilation terminated.
paddle/fluid/platform/CMakeFiles/device_tracer.dir/build.make:62: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o' failed
make[2]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/device_tracer.cc.o] Error 1
CMakeFiles/Makefile2:2711: recipe for target 'paddle/fluid/platform/CMakeFiles/device_tracer.dir/all' failed
make[1]: *** [paddle/fluid/platform/CMakeFiles/device_tracer.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

请问如何解决

**Comment by seiriosPlus** [comment]
能提供一下编译环境，以及编译指令么

**Comment by zzhzz** [comment]
cmake .. -DWITH_GPU=OFF
make

**Comment by zzhzz** [comment]
我在另一个issue找到了解决办法，似乎是protoc版本的问题，先close了

**Comment by JadeRay** [comment]
哪个issue提供了解决方案，辛苦link一下？
