### ISSUE TITLE
Need to limit the symbol in libpaddle_fluid.so

### ISSUE THREAD

**Issue by Xreki** [PaddlePaddle/Paddle#9071]
All the dependent third party libraries (protobuf, gflags, glog, etc) are linked to `libpaddle_fluid.so`, so that in inference codes users only need to link `libpaddle_fluid.so`. But if users need to link another `glog` library of different version, the compiling will fail because of conflict of symbols. We need to limit the symbol table of `libpaddle_fluid.so` as do in capi

https://github.com/PaddlePaddle/Paddle/blob/48f213e5a1f89035e35810b7d4445802d5f154a1/paddle/capi/CMakeLists.txt#L71-L73

**Comment by wangkuiyi** [comment]
May I know how doesn paddle_capi.map work, or how to learn more about *.map?

I am working on https://github.com/PaddlePaddle/Paddle/pull/9719 to refactorize paddle/fluid/memory. However, the CI always fails at linking tests in paddle/fluid/inference/tests/book/*, complaining symbols being defined multiple times.
