### ISSUE TITLE
different meaning in LRN's param 'n' in paddle?

### ISSUE THREAD

**Issue by dragonwarrior** [PaddlePaddle/Paddle#9094]
i found that the implementation of LRN(local response normalization) operator maybe not correct about param 'n'。
when i tried to compare the results produced by tensorflow and paddle using LRN function, i noticed that their difference is too large. Then i inspect the code in paddle, found 
for (int c = start; c <= end; c++) {
in https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/operators/lrn_op.cc:39. we can decuded that the channels it summed over is (n + 1), but not n, which can explain my experiment's result.

**Comment by qingqing01** [comment]
@dragonwarrior Thanks. Yeah, it is a bug. I will fix it later.

**Comment by dragonwarrior** [comment]
new info: i test this operator on GPU, and the result is the same with tensorflow. so this bug only exist in cpu version of LRN op.

**Comment by qingqing01** [comment]
@dragonwarrior Yeah, you are right. The https://github.com/PaddlePaddle/Paddle/pull/9124/files only fix the CPU version.
