### ISSUE TITLE
basic_usage中英文文档更新

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#911]
根据 #620 中提的意见，更新basic_usage中英文文档。文档地址：https://github.com/PaddlePaddle/Paddle/tree/develop/doc/getstarted/basic_usage

**Comment by zhouxiao-coder** [comment]
@luotao1 我提交了一个pull request #920 ，你看下吧。
 这个pull request只包含英文文档，中文部分我看 @tianbingsz  已经更新过了，我暂时没改，不过有个问题想跟 @tianbingsz 讨论一下，我写在 #920  的comment里了。

**Comment by luotao1** [comment]
由于PaddlePaddle Book中重写了新手入门的中英文版，该issue和对应的PR就close了。
