### ISSUE TITLE
模型预测出core : TableProjection Check failed: in_->ids

### ISSUE THREAD

**Issue by thomas010** [PaddlePaddle/Paddle#912]
模型训练ok，测试的时候check失败：
[INFO][PredictorInternal.cpp][init][429] input[1]: dim=[2], name=[label].
I1215 17:03:20.836092 27917 BatchPredictor.cpp:31] Finish initializing the model.
I1215 17:03:20.836122 27917 BatchPredictor.cpp:38] outputNum=1
I1215 17:03:20.836127 27917 BatchPredictor.cpp:42] outputDim[0]=2
I1215 17:03:20.836133 27917 BatchPredictor.cpp:46] slot num: 2
I1215 17:03:20.836139 27917 BatchPredictor.cpp:47] output dim: 2
I1215 17:03:20.836145 27917 BatchPredictor.cpp:52] input dim: [0] 187808
I1215 17:03:20.836151 27917 BatchPredictor.cpp:52] input dim: [1] 2
F1215 17:03:20.837668 27917 TableProjection.cpp:37] Check failed: in_->ids
Check failed: in_->ids

但测试和训练的数据格式都一致，能否帮我查看哈

**Comment by backyes** [comment]
@thomas010  

能否贴一下你的模型配置？ 另外，最好也能提供下dataprovider等相关配置，如果能可复现，那最好了。
