### ISSUE TITLE
docker build出错

### ISSUE THREAD

**Issue by dayhaha** [PaddlePaddle/Paddle#913]
按照https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst 在mac上面进行docker build，出错如下：
In file included from /paddle/paddle/cuda/src/hl_warpctc_wrap.cc:15:0:
/paddle/paddle/cuda/include/hl_warpctc_wrap.h:19:34: fatal error: warp-ctc/include/ctc.h: No such file or directory
 #include "warp-ctc/include/ctc.h"
                                  ^
compilation terminated.
make[2]: *** [paddle/cuda/CMakeFiles/paddle_cuda.dir/src/hl_warpctc_wrap.cc.o] Error 1
make[1]: *** [paddle/cuda/CMakeFiles/paddle_cuda.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

然后发现warp-ctc下的文件为空，重新git clone一遍paddle源代码该文件夹也是空的，是需要自己手动去clone warp-ctc的库么？

**Comment by reyoung** [comment]
@Xreki Please give an answer. And we should add this to FAQ, too.

**Comment by Xreki** [comment]
@dayhaha 请使用以下命令`git clone`：
```bash
git clone --recursive https://github.com/PaddlePaddle/paddle
```
或
```bash
git clone github.com/PaddlePaddle/Paddle
cd Paddle
git submodule update --init --recursive
```

其实这两条命令在`Non-AVX Images`和`Development Using Docker`都有写明，但在`CPU-only and GPU Images`省去了。

**Comment by dayhaha** [comment]
谢谢，不好意思没有看到下面。 但是我觉得作为一个用户，是不是一般习惯从上往下执行看呢？ 或者说需不需要把git clone --recursive这块强调一下呢？   感觉这块是不是可以改变一下顺序呢？ 文件的名字叫docker_install_en.rst，看到CPU-only and GPU Images的标题我以为是开始教build image了。

**Comment by Xreki** [comment]
@dayhaha 文档描述确实有不够严谨之处，谢谢你的建议，我们会尽快调整。

**Comment by reyoung** [comment]
@dayhaha 直接把docker_install那个文件，按照你的想法改了吧。@我review一下。
关于这个的FAQ，我加一下，@dayhaha 你再review一下。

**Comment by dayhaha** [comment]
好的，我提了个PR #917。  @reyoung 你review一下吧。
