### ISSUE TITLE
Why my mobilenet_v2_ssd model reappeared with paddle does not converge ? 

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#9159]
Neither do my other workmates.

**Comment by qingqing01** [comment]
Please give more details.

**Comment by qingqing01** [comment]
In order to solve the problem effectively, Could you give more details or the code and environment that can be reproduced this problem?

**Comment by youngstu** [comment]
I am a student of baidu， do you have baidu HI account ?  Can i add you as my friend in hi app?

**Comment by youngstu** [comment]
I can pass you the code through hi app.

**Comment by qingqing01** [comment]
@youngstu Of course. You can search my name Dang Qingqing.

**Comment by qingqing01** [comment]
@youngstu Have you solved this problem?

**Comment by youngstu** [comment]
Yes, i do. Thank you.

**Comment by chengduoZH** [comment]
What's the problem? how to solve? can you describe them in this issue?
