### ISSUE TITLE
用seq2seq模型做infer，beam_size=1的时候出错

### ISSUE THREAD

**Issue by wangbin11** [PaddlePaddle/Paddle#9160]
`#coding=gbk
import sys, os
import numpy as np
import paddle.v2 as paddle
import argparse
import reader
import logging
from paddle.trainer_config_helpers import layers

logger = logging.getLogger("paddle")
logger.setLevel(logging.INFO)

parser = argparse.ArgumentParser(description="NMT but only need encoder vector")

parser.add_argument(
    "--infer_model",
    type=str,
    required=False,
    help="The path of model for infer.")

parser.add_argument(
    "-i",
    "--train_data_path",
    type=str,
    required=False,
    help="The path of training data.")

parser.add_argument(
    "-e",
    "--test_data_path",
    type=str,
    required=False,
    help="The path of test data.")

parser.add_argument(
    "--is_generating",
    type=int,
    required=False,
    default=0,
    help="generating or train(default)")

parser.add_argument(
    "--gpu_id",
    type=int,
    default=0,
    required=False,
    help="gpu id")

parser.add_argument(
    "-m",
    "--init_from_tar_path",
    type=str,
    required=False,
    help="init param from models")

parser.add_argument(
    "-s",
    "--source_dic_path",
    type=str,
    required=False,
    help="The path of the source's word dictionary.")

parser.add_argument(
    "--target_dic_path",
    type=str,
    required=False,
    help=("The path of the target's word dictionary, "
          "if this parameter is not set, the `source_dic_path` will be used"))

parser.add_argument(
    "-b",
    "--batch_size",
    type=int,
    default=32,
    help="The size of mini-batch (default:64).")

parser.add_argument(
    "-p",
    "--num_passes",
    type=int,
    default=10,
    help="The number of passes to run(default:10).")

parser.add_argument(
    "--use_gpu",
    type=int,
    default=0,
    help="Whether to use GPU devices (default: False)")

parser.add_argument(
    "-g",
    "--num_batches_to_log",
    type=int,
    default=100,
    help=("The log period. Every num_batches_to_test batches, "
          "a training log will be printed. (default: 100)"))

parser.add_argument(
    "-d",
    "--dnn_size",
    type=str,
    default="128,128,128",
    help = "emb size, encode size, decode size")

parser.add_argument(
    "-z",
    "--num_batches_to_save_model",
    type=int,
    default=1000,
    help=("Every num_batches_to_save_model batches, "
          "a trained model will be saved (default: 400)."))

parser.add_argument(
    "--beam_size",
    type=int,
    default=3,
    help = ("decode num"))

args = parser.parse_args()

def save_model(trainer, save_path):
    with open(save_path, 'w') as f:
        trainer.save_parameter_to_tar(f)

def seq_to_seq_net(source_dict_dim,
                   target_dict_dim,
                   args,
                   max_length=32,
                   beam_size = 3):
    ### Network Architecture
    word_vector_dim, encoder_size, \
            decoder_size = map(int, args.dnn_size.split(","))
    is_generating = args.is_generating
    #### Encoder
    print "dddddd"
    src_word_id = paddle.layer.data(
        name='source_language_word',
        type=paddle.data_type.integer_value_sequence(source_dict_dim))
    src_embedding = paddle.layer.embedding(
        input=src_word_id, size=word_vector_dim)
    src_forward = paddle.networks.simple_gru(
        input=src_embedding, size=encoder_size)
    src_backward = paddle.networks.simple_gru(
        input=src_embedding, size=encoder_size, reverse=True)
    encoded_vector = paddle.layer.concat(input=[src_forward, src_backward])

    #### Decoder
    encoded_proj = paddle.layer.fc(
        act=paddle.activation.Linear(),
        size=decoder_size,
        bias_attr=False,
        input=encoded_vector)
    if is_generating:
        layers.print_layer(encoded_proj)
        pass

    backward_first = paddle.layer.first_seq(input=src_backward)
    decoder_boot = paddle.layer.fc(
        size=decoder_size,
        act=paddle.activation.Tanh(),
        bias_attr=False,
        input=backward_first)

    def gru_decoder_with_attention(enc_vec, enc_proj, current_word):

        decoder_mem = paddle.layer.memory(
            name='gru_decoder', size=decoder_size, boot_layer=decoder_boot)

        context = paddle.networks.simple_attention(
            encoded_sequence=enc_vec,
            encoded_proj=enc_proj,
            decoder_state=decoder_mem)

        decoder_inputs = paddle.layer.fc(
            act=paddle.activation.Linear(),
            size=decoder_size * 3,
            bias_attr=False,
            input=[context, current_word],
            layer_attr=paddle.attr.ExtraLayerAttribute(
                error_clipping_threshold=100.0))

        gru_step = paddle.layer.gru_step(
            name='gru_decoder',
            input=decoder_inputs,
            output_mem=decoder_mem,
            size=decoder_size)

        out = paddle.layer.fc(
            size=target_dict_dim,
            bias_attr=True,
            act=paddle.activation.Softmax(),
            input=gru_step)
        return out

    decoder_group_name = 'decoder_group'
    group_input1 = paddle.layer.StaticInput(input=encoded_vector)
    group_input2 = paddle.layer.StaticInput(input=encoded_proj)
    group_inputs = [group_input1, group_input2]

    if not is_generating:
        trg_embedding = paddle.layer.embedding(
            input=paddle.layer.data(
                name='target_language_word',
                type=paddle.data_type.integer_value_sequence(target_dict_dim)),
            size=word_vector_dim,
            param_attr=paddle.attr.ParamAttr(name='_target_language_embedding'))
        group_inputs.append(trg_embedding)

        # For decoder equipped with attention mechanism, in training,
        # target embeding (the groudtruth) is the data input,
        # while encoded source sequence is accessed to as an unbounded memory.
        # Here, the StaticInput defines a read-only memory
        # for the recurrent_group.
        decoder = paddle.layer.recurrent_group(
            name=decoder_group_name,
            step=gru_decoder_with_attention,
            input=group_inputs)

        lbl = paddle.layer.data(
            name='target_language_next_word',
            type=paddle.data_type.integer_value_sequence(target_dict_dim))
        cost = paddle.layer.classification_cost(input=decoder, label=lbl)

        return cost
    else:
        # In generation, the decoder predicts a next target word based on
        # the encoded source sequence and the previous generated target word.

        # The encoded source sequence (encoder's output) must be specified by
        # StaticInput, which is a read-only memory.
        # Embedding of the previous generated word is automatically retrieved
        # by GeneratedInputs initialized by a start mark <s>.

        trg_embedding = paddle.layer.GeneratedInput(
            size=target_dict_dim,
            embedding_name='_target_language_embedding',
            embedding_size=word_vector_dim)
        group_inputs.append(trg_embedding)

        beam_gen = paddle.layer.beam_search(
            name=decoder_group_name,
            step=gru_decoder_with_attention,
            input=group_inputs,
            bos_id=0,
            eos_id=1,
            beam_size=beam_size,
            max_length=max_length)

        return beam_gen

def main():
    paddle.init(use_gpu=args.use_gpu, trainer_count=1, gpu_id=args.gpu_id)
    is_generating = args.is_generating

    src_dict, source_dict_dim = reader.read_to_dict(
            args.source_dic_path)
    trg_dict, target_dict_dim = reader.read_to_dict(
            args.target_dic_path)

    if not is_generating:
        # define optimize method and trainer
        optimizer = paddle.optimizer.Adam(
            learning_rate=5e-5,
            regularization=paddle.optimizer.L2Regularization(rate=8e-4))

        cost = seq_to_seq_net(source_dict_dim, target_dict_dim, args)
        parameters = paddle.parameters.create(cost)
        if args.init_from_tar_path:
            parameters.init_from_tar(open(args.init_from_tar_path))

        trainer = paddle.trainer.SGD(
            cost=cost, parameters=parameters, update_equation=optimizer)
        # define data reader
        train_reader = paddle.batch(
            paddle.reader.shuffle(
                reader.train(args.train_data_path,
                    args.source_dic_path,
                    args.target_dic_path), buf_size=8192),
            batch_size=args.batch_size)

        # define event_handler callback
        def event_handler(event):
            if isinstance(event, paddle.event.EndIteration):
                if event.batch_id % args.num_batches_to_log == 0:
                    logger.info("Pass %d, Batch %d, Cost %f, %s" %
                          (event.pass_id, event.batch_id, event.cost,
                           event.metrics))
                if not event.batch_id % args.num_batches_to_save_model:
                    save_path = './output/params_pass_%05d.tar' % (
                        event.pass_id)
                    save_model(trainer, save_path)

            if isinstance(event, paddle.event.EndPass):
                # save parameters
                save_path = './output/params_pass_%05d.tar' % (event.pass_id)
                save_model(trainer, save_path)

        # start to train
        trainer.train(
            reader=train_reader, event_handler=event_handler,
            num_passes=args.num_passes)

    else:
        logger.info("start to infer")
        # use the first 3 samples for generation
        **//这里如果beam_size = 1,在paddle.infer的时候，会报错，2以上就没问题
        beam_size = 1**
        src_dict_reverse = {v: k for k, v in src_dict.items()}
        trg_dict_reverse = {v: k for k, v in trg_dict.items()}
        beam_gen = seq_to_seq_net(source_dict_dim, target_dict_dim,
                                args, beam_size = beam_size)
        # get the trained model, whose bleu = 26.92
        parameters = reader.model(args.infer_model)
        inferer = paddle.inference.Inference(
                output_layer=beam_gen, parameters=parameters)

        gen_data = []
        for item in reader.test(
                args.test_data_path,
                args.source_dic_path,
                args.target_dic_path)():
            logger.info("___begin___")
            gen_data = [[item[0]]]
            # prob is the prediction probabilities, and id is the prediction word.
            beam_result = inferer.infer(input=gen_data, field=["prob", "id"])
            gen_sen_idx = np.where(beam_result[1] == -1)[0]
            assert len(gen_sen_idx) == len(gen_data) * beam_size
            # -1 is the delimiter of generated sequences.
            # the first element of each generated sequence its length.
            start_pos, end_pos = 1, 0
            for i, sample in enumerate(gen_data):
                logger.info(
                    "".join([src_dict_reverse[w] for w in sample[0][1:-1]])
                )  # skip the start and ending mark when printing the source sentence
                for j in xrange(beam_size):
                    end_pos = gen_sen_idx[i * beam_size + j]
                    logger.info("%.4f\t%s" % (beam_result[0][i][j], "".join(
                        trg_dict_reverse[w] for w in beam_result[1][start_pos:end_pos])))
                    start_pos = end_pos + 2
            logger.info("___end___")

def display_args(args):
    logger.info("The arguments passed by command line is :")
    for k, v in sorted(v for v in vars(args).items()):
        logger.info("{}:\t{}".format(k, v))

if __name__ == '__main__':
    display_args(args)
    main()
`
如果beam_size=1,会报如下错误：
Traceback (most recent call last):
  File "train.py", line 351, in <module>
    main()
  File "train.py", line 326, in main
    beam_result = inferer.infer(input=gen_data, field=["prob", "id"])
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/inference.py", line 103, in infer
    retv = [numpy.concatenate(out) for out in retv]
ValueError: zero-dimensional arrays cannot be concatenated

而beam_size大于1没问题。
看了一下，beam_result返回list，有两个元素，一个是概率，一个是word id。当beam_size=1的时候，概率是None, 这个是什么原因呢

**Comment by luotao1** [comment]
beam_size=1的时候，生成的是一句话（one way search），所以是没有概率的。
可以试下：`result = inferer.infer(input=gen_data, field=["id"])`

**Comment by wangbin11** [comment]
@luotao1 非常感谢您的解答，不过还是有个疑问，prob概率是指生成一段文本的概率吗，那为什么生成一句话却没有概率呢。

**Comment by luotao1** [comment]
> prob概率是指生成一段文本的概率吗

是的，它是句子中每个词语的log概率只和。

> 为什么生成一句话却没有概率呢

- beam_size>1的时候，生成句子时，每一步选择概率最大的beam_size个词语进行下一步生成使用，下一步在生成出的beam_size*beam_size个词语中选择概率最大的beam_size个词语。可参考[柱搜索算法](http://www.paddlepaddle.org/docs/develop/book/08.machine_translation/index.cn.html#permalink-8--)，最后会打印出beam_size个生成句子，每个句子按照概率从大到小排列。
- 而beam_size=1的时候，生成句子时，每一步只选择概率最大的1个词语进行下一步生成使用，下一步也只会生成出1个词语，每个词语的概率一直都为1.

**Comment by wangbin11** [comment]
@luotao1 非常感谢解答，了解啦~
