### ISSUE TITLE
I hope the PASCAL VOC2012 dataset can be uploaded to the paddlepaddle cloud

### ISSUE THREAD

**Issue by LogicHolmes** [PaddlePaddle/Paddle#9162]
I will train fcn model with the paddlepaddle , and I use the VOC2012 dataset  as my data. I feel so happy When I find the VOC2012 dataset at the paddle.v2.dataset.VOC2012 . But the VOC2012 dataset couldn't be used in the server . We should download it on the server, but we have no rigth to do it . 
So I hope the PASCAL VOC2012 dataset can be uploaded to the paddlepaddle cloud.

**Comment by qingqing01** [comment]
Thanks for your suggestion.  You can put your own VOC2012 dataset in:

```
~/.cache/paddle/dataset/voc2012
```

Then the `paddle.v2.dataset.VOC2012` will use the local data and  not download from `http://host.robots.ox.ac.uk/pascal/VOC/voc2012/VOCtrainval_11-May-2012.tar `

**Comment by LogicHolmes** [comment]
Thank you very much @qingqing01 .I am trying to scp my own VOC2012 to my local server ~/.cache/paddle/dataset/voc2012. I think your suggestion is so helpful.

**Comment by Yancey1989** [comment]
Thanks for @qingqing01 and @LogicHolmes, For my understanding, @LogicHolmes want a pre-download dataset on PaddlePaddle Cloud cluster and don't need to upload the dataset before submitting the job, that's right?

**Comment by qingqing01** [comment]
@LogicHolmes  Do you train the FCN model on PaddlePaddle cloud or your local server?

**Comment by LogicHolmes** [comment]
@qingqing01 I will train the FCN model on paddlepaddle cloud,and i am wrting the Deconvlution layer.

**Comment by LogicHolmes** [comment]
@Yancey1989 I initially thought of the dataset on the paddlepaddle cloud cluster, so I needn't upload the dataset by myself. Now i could move my dataset on ~/.cache/paddle/dataset/voc2012. That's helpful!

**Comment by shanyi15** [comment]
Hi @LogicHolmes 
Thank you for your suggestion, we will collect it and fix it according to the priority.
Thank @qingqing01 and @Yancey1989 for providing solution.

**Comment by qingqing01** [comment]
@LogicHolmes I close this PR, please feel free to open this issue if you think we still need to upload  VOC2012 dataset to PaddlePaddle cloud.
