### ISSUE TITLE
在Mobile中使用到的mobilenet神经网络是哪个？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#9169]
我在这里https://github.com/PaddlePaddle/Mobile/blob/develop/models/standard_network/mobilenet.py 看到了mobilenet神经网络，这个是不是就是谷歌的那个MobileNets，
有没有论文？是不是这个：https://arxiv.org/abs/1704.04861

**Comment by qingqing01** [comment]
@yeyupiaoling  是这个网络~

**Comment by yeyupiaoling** [comment]
@qingqing01 好的，谢谢

**Comment by yeyupiaoling** [comment]
@qingqing01 
https://github.com/PaddlePaddle/Mobile/blob/develop/models/standard_network/mobilenet.py#L76
中的参数 `scale` 是不是指论文中的`width multiplier α`

**Comment by NHZlX** [comment]
1. 对的， scale 是指的width multiplier。
2. “mobilenet训练时间比VGG长那么多”，这个训练时间具体是指什么呢，是相同batch 下一个step下的时间，还是整个训练过程的时间？

**Comment by yeyupiaoling** [comment]
@NHZlX 
是指整个训练时间，同样的pass。我看论文，论文中说到mobilenet的计算量不是比VGG16要小吗？难道是不是这样理解的，训练时间长是因为mobilenet的网络深？

**Comment by NHZlX** [comment]
首先先确定你是否在gpu下，如果pc的cpu训练，是有可能比vgg16慢的，如果在gpu下，那测试一下在相同的数据输入大小，相同的batch大小一个step下的时间

**Comment by yeyupiaoling** [comment]
@NHZlX 
我使用的是百度的深度学习集群，4个GPU，训练CIFAR10数据集，同样是50个pass，使用mobilenets训的训练的时间是40个小时，使用VGG16使用的时间是3个小时，这是正常的吗？

**Comment by NHZlX** [comment]
这样看起来并不是太正常，方便把mobilenet 和 vgg16的配置文件以及训练脚本放到gist上发给我一份么，我测试一下

**Comment by yeyupiaoling** [comment]
@NHZlX 
嗯嗯，可以的呢，就是这个：https://github.com/yeyupiaoling/TestAndroid/blob/master/code/train.py
可以通过修改这一行：https://github.com/yeyupiaoling/TestAndroid/blob/master/code/train.py#L47
来修改使用MobileNets或者VGG16，VGG16的是这个样：
```python
out = vgg_bn_drop(datadim, 10)
```

**Comment by yeyupiaoling** [comment]
@NHZlX 
我今天又测试了一次，奇怪的是这次同样是50个pass，同样是CIFAR10数据集，使用的mobilenet的训练的时间跟前三次的都不一样，这次只要2个小时，比VGG16时间还少，这次正常吗？
我是重新创建了一个集群的，是不是跟集群有关系，但是集群的配置都是一样的，4个GPU。

**Comment by NHZlX** [comment]
在我的机器上进行的测试的结果如下

|model| time (one pass)|
|:---:|:---:|
|vgg16 with one card | 199.51s |
|vgg16 with three card| 197.9s|
|mobilenet with one card| 91.92s |
|mobilenet with three card|116.01s |

**Comment by yeyupiaoling** [comment]
@NHZlX 
这么说，mobilenet比VGG16快才是正常的？
可是mobilenet的卷积层要比VGG16要多好多，虽然mobilenet没有池化层

**Comment by NHZlX** [comment]
你可以简要写一个脚本测试一下模型的计算量(可以参考我之前写的一个https://gist.github.com/NHZlX/ca05f002072995307de9914a81b8b7b2)。 卷积层的个数多少还有参数的个数都不能代表一个网络计算量的多少

**Comment by yeyupiaoling** [comment]
@NHZlX 
好的，谢谢。
