### ISSUE TITLE
PaddlePaddle Fluid 有支持python3的计划么？

### ISSUE THREAD

**Issue by hohdiy** [PaddlePaddle/Paddle#9174]
Python语言作者Guido van Rossum宣布Python 2.7支持时间延长到2020年，python2.7是python2.x的最后一个版本。
目前PaddlePaddle Fluid 只支持python2，请问是否有计划支持python3？如果有大概是什么时候？

**Comment by Yancey1989** [comment]
感谢您的建议，PaddlePaddle team目前大部分精力都投入在Fliud的开发，优化中，等到一个相对比较稳定版本后会考虑对Python3的支持，暂时还没有具体时间。

**Comment by yeyupiaoling** [comment]
问题重复 #8981

**Comment by yangzhg** [comment]
我尝试了paddle 在python3 的编译，使用了paddle 编译镜像里的cp35-cp35m 版本python，主要编译问题集中在

- paddle/gserver/dataproviders/PyDataProvider.cpp
-  paddle/gserver/dataproviders/PyDataProvider2.cpp
- paddle/utils/PythonUtil.cpp
- paddle/utils/PythonUtil.h
 这四个文件中，主要的问题有 PyString_*  和 PyInt_*函数在python3中已经不存在了，具体可以[看这里](https://docs.python.org/3/howto/cporting.html) 和[这里](http://py3c.readthedocs.io/en/latest/guide-porting.html)， 对于版本的判断 可以使用`PY_MAJOR_VERSION` 这个宏，另外的问题 paddle 里使用的PyInstance_New 函数子啊Python3 中不存在了，而且没有直接对应的函数， python3 中使用了wchar_t 代替了char，我已经修改了一点，但是还有编译错误没用通过，也没有使用`PY_MAJOR_VERSION` 兼容python2 和python3，暂时没有精力继续改进下去，现在把我的改动diff 附在这里
[paddle.diff.txt](https://github.com/PaddlePaddle/Paddle/files/1832258/paddle.diff.txt) 仅供参考

**Comment by JC-S** [comment]
Looking forward to the support of python 3 as well.

**Comment by luotao1** [comment]
我们已经有Python3的排期 #12040 #12050 了，先关闭该issue，谢谢您的关注！

**Comment by velconia** [comment]
Paddle Fluid 会在 0.15.0 发布python3的试用版, 1.0 发布正式版. 

这个 [issue](https://github.com/PaddlePaddle/Paddle/issues/12040) 记录了我们的工作;
