### ISSUE TITLE
how to generate text faster by using seqToseq ?

### ISSUE THREAD

**Issue by zhouyuan0828** [PaddlePaddle/Paddle#918]
I have about 90w samples needed to generate text by seqToseq model.
when generate locally, and trainer_count set as 1, it is quite slow. On the other hand,  when i set trainner_count as 5, it will gen core as below. SO wonder to know  generate text  on cluster is ok? and how to do it , please help share a link?
thanks 
yuan
F1216 11:31:51.538795 18198 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytes
*** Check failure stack trace: ***
    @          0x13b2d38  google::LogMessage::Fail()
F1216 11:31:51.540397 18199 MemoryHandle.cpp:52] Check failed: size != 0  allocate 0 bytes
*** Check failure stack trace: ***
    @          0x13b2c90  google::LogMessage::SendToLog()

**Comment by hedaoyuan** [comment]
What is the batchSize?  I think you may have set batchSize = 1. 
If batchSize = 1 and trainner_count = 5, than some trainers may not have data, and will cause the above error.

**Comment by zhouyuan0828** [comment]
thanks when i set batchsize the same as trainer_count, it can work locally.
