### ISSUE TITLE
docker build 使用默认apt源时，在国内编译很慢，有时会导致出错

### ISSUE THREAD

**Issue by wen-bo-yang** [PaddlePaddle/Paddle#919]
按照https://github.com/PaddlePaddle/Paddle/blob/develop/doc/getstarted/build_and_install/docker_install_en.rst
进行使用源码中提供的dockersfile进行编译时，在apt-get更新软件包时会很慢，有时会出现build失败的情况。
这块是否需要增加对apt-get源进行用户自定义的支持？

**Comment by dayhaha** [comment]
我build的时候也是遇到了源的问题，build失败。
<img width="1280" alt="2016-12-16 1 08 45" src="https://cloud.githubusercontent.com/assets/6861004/21252333/ec6aea5e-c390-11e6-9cab-f168ff4c2628.png">
将源改成163的源才通过了build
RUN sed -i 's#http://archive.ubuntu.com#http://mirrors.163.com#g' /etc/apt/sources.list

**Comment by wen-bo-yang** [comment]
是否可以在build时传递--build-arg参数，并且在dockerfile中apt-get之前判断这个参数是否开启，来进行更改apt源的方式（针对国内apt源的修改）。
具体如下
build docker images:
docker build --build-arg CHINA_APT_SOURCE=ON -t p:test -f Dockerfile .
Dockerfile:
![image](https://cloud.githubusercontent.com/assets/6229206/21253357/f082e10c-c398-11e6-89d9-64f9d4330045.png)

即在RUN apt-get update && apt-get install xxx 之前进行参数判断并更改container的/etc/apt/sources.list

**Comment by reyoung** [comment]
交PR吧。。

不过感觉起来，参数叫做`APT_MIRROR`。
然后使用起来是
```bash
docker build --build-arg APT_MIRROR="http://mirrors.163.com"
```
这样。

**Comment by wen-bo-yang** [comment]
收到

**Comment by reyoung** [comment]
APT_MIRROR => UBUNTU_MIRROR 吧。

**Comment by wen-bo-yang** [comment]
已经提交PR https://github.com/PaddlePaddle/Paddle/pull/927
PR中修改了dockerfile和英文文档
