### ISSUE TITLE
Fluid版本图像训练报错

### ISSUE THREAD

**Issue by JadyXuan** [PaddlePaddle/Paddle#9196]
将fc_gan.py修改成自己的训练集的时候出现了这个错误，不知道是哪个方面出了错误。萌新请教一下各位大佬们~不胜感激
![aaa](https://user-images.githubusercontent.com/35390572/37586804-6a3ef4aa-2b98-11e8-8a7a-45158cde3fc5.PNG)
日志信息
bsakz@bsakz-VirtualBox:~/桌面/workspace/fc_gan$ python gan.py
Traceback (most recent call last):
  File "gan.py", line 162, in <module>
    main()
  File "gan.py", line 143, in main
    fetch_list={d_loss})[0]
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/executor.py", line 144, in run
    self.executor.run(program.desc, scope, 0, True)
paddle.v2.fluid.core.EnforceNotMet: enforce x_dims[0] == labels_dims[0] failed, 64 != 96
The 1st dimension of Input(X) and Input(Label) should be equal. at [/paddle/paddle/operators/sigmoid_cross_entropy_with_logits_op.cc:38]
PaddlePaddle Call Stacks: 
0       0x7f5d86d6d636p paddle::platform::EnforceNotMet::EnforceNotMet(std::__exception_ptr::exception_ptr, char const*, int) + 486
1       0x7f5d86ede9fbp paddle::operators::SigmoidCrossEntropyWithLogitsOp::InferShape(paddle::framework::InferShapeContext*) const + 1387
2       0x7f5d871f4426p paddle::framework::OperatorWithKernel::Run(paddle::framework::Scope const&, paddle::platform::DeviceContext const&) const + 70
3       0x7f5d86df8a8dp paddle::framework::Executor::Run(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool) + 1581
4       0x7f5d86d7f107p void pybind11::cpp_function::initialize<pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool)#1}, void, paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(pybind11::cpp_function::initialize<void, paddle::framework::Executor, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool, pybind11::name, pybind11::is_method, pybind11::sibling>(void (paddle::framework::Executor::*)(paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool)#1}&&, void (*)(paddle::framework::Executor*, paddle::framework::ProgramDescBind const&, paddle::framework::Scope*, int, bool), pybind11::name const&, pybind11::is_method const&, pybind11::sibling const&)::{lambda(pybind11::detail::function_call&)#3}::_FUN(pybind11::detail::function_call) + 471
5       0x7f5d86d7a864p pybind11::cpp_function::dispatcher(_object*, _object*, _object*) + 2596
6       0x5574b600b44ep PyEval_EvalFrameEx + 37566
7       0x5574b5fffb3ap PyEval_EvalCodeEx + 858
8       0x5574b600782ep PyEval_EvalFrameEx + 22174
9       0x5574b6007462p PyEval_EvalFrameEx + 21202
10      0x5574b5fffb3ap PyEval_EvalCodeEx + 858
11      0x5574b603050fp
12      0x5574b602b202p PyRun_FileExFlags + 130
13      0x5574b602acadp PyRun_SimpleFileExFlags + 397
14      0x5574b5fd9d7bp Py_Main + 1675
15      0x7f5da1b8e1c1p __libc_start_main + 241
16      0x5574b5fd95fap _start + 42

**Comment by yeyupiaoling** [comment]
@JadyXuan 
你这样提问题不好，不要截图，应该把日志复制出来，方便别人问题定位

**Comment by JiayiFeng** [comment]
看上去就是样本数量和label数量不一致的问题，送入的样本有64个，标签却有96个。

**Comment by JadyXuan** [comment]
那请问如果我只是做对抗训练的话，标签是不是可以不要呢？
