### ISSUE TITLE
paddle训练使用多cpu不如单cpu速度快

### ISSUE THREAD

**Issue by janelu9** [PaddlePaddle/Paddle#923]
在服务器上建立了1,2,4,8个cpu的镜像，当trainner_counter分别设置为1,2,4,8时发现速度逐渐变慢，全部设置为1时，速度相当。说明paddle并没有利用多cpu啊

**Comment by janelu9** [comment]
版本是0.9.0a0
with_avx: ON
    with_gpu: OFF
    with_double: OFF
    with_python: ON
    with_rdma: OFF
    with_glog: ON
    with_gflags: ON
    with_metric_learning:
    with_timer: OFF

**Comment by reyoung** [comment]
@janelu9 最可能的原因是batch_size设置的过小，导致计算线程大量空闲。

同时，读数据的DataProvider可能写的太慢，导致时间占用都在读数据上。

**Comment by backyes** [comment]
@janelu9 

* 比较快速做一些排除分析，比如可以加大batch size，排除是否是mini-batch很小的原因。 

* 另外如果有兴趣深入分析原因， 也可以从源码编译Paddle， 并使能WITH_TIMER， 可以获取更加量化的分析。

**Comment by backyes** [comment]
@janelu9 

> 在服务器上建立了1,2,4,8个cpu的镜像

另外，不知道这些是否都是物理核个数

**Comment by janelu9** [comment]
@backyes  物理核心有2个 逻辑48个 256G内存 suse12系统

**Comment by janelu9** [comment]
加大batch_size等于成倍减少训练次数 肯定训练的时间会缩短了 但是精度会下降

**Comment by reyoung** [comment]
duplicated #957  不过这里很多想法是错的。。比如加大batch_size不一定成比例增加训练次数。

**Comment by janelu9** [comment]
@reyoung 额 不是训练次数 那是迭代次数了 不过每次迭代的计算量不一样了
