### ISSUE TITLE
SIGSEGV  ERROR during training

### ISSUE THREAD

**Issue by April0402** [PaddlePaddle/Paddle#9238]
This error occurs when traing a LSTM model.  I added an attention layer to this model, which is calculated as weight of tokens in the sequence. I guess there is something wrong with this layer, but I don't know what's the problem. The related code is below.

**This is the error info:**
```
Thread [139810164651776] Forwarding __expand_layer_0__,
*** Aborted at 1521533628 (unix time) try "date -d @1521533628" if you are using GNU date ***

PC: @                0x0 (unknown)

*** SIGSEGV (@0x30) received by PID 16264 (TID 0x7f2817333700) from PID 48; stack trace: ***

    @     0x7f28594c3160 (unknown)

    @     0x7f27f63eac79 paddle::ExpandLayer::forward()

    @     0x7f27f645b19d paddle::NeuralNetwork::forward()

    @     0x7f27f647c984 paddle::TrainerThread::forward()

    @     0x7f27f647dbe5 paddle::TrainerThread::computeThread()

    @     0x7f284b6d68a0 execute_native_thread_routine

    @     0x7f28594bb1c3 start_thread

    @     0x7f2858ae312d __clone

    @                0x0 (unknown)
local.sh: line 5: 16264 段错误               (core dumped) python bin/train.py --conf_path=conf/slot_filling.local.conf
```
**This is the code of attention layer**
  
    attention_weight_layer = get_position_aware_attention(raw_lstm_layer, emb_dim_dict, \
            attention_dim, position_input_size)
    attention_weight_seq_layer = paddle.layer.repeat(input=attention_weight_layer, \
            num_repeats=raw_lstm_layer.size, as_row_vector=False)
    weighted_lstm_layer = paddle.layer.dot_prod(
            input1=raw_lstm_layer,
            input2=attention_weight_seq_layer)
    hidden_layer = paddle.layer.fc(
            size=hidden_dim,
            bias_attr=paddle.attr.Param(initial_std=default_std),
            input = weighted_lstm_layer,
            param_attr = fc_para_attr)
    
    #获取attention层
    def get_position_aware_attention(lstm_layer, emb_dim_dict, attention_dim, \
            position_input_size):
        position_data = paddle.layer.data(name='position_data', \
            type=paddle.data_type.dense_vector_sequence(position_input_size))
        position_emb_layer = get_embedding_layer(position_data, 'position', emb_dim_dict)`

        lstm_sum = paddle.layer.addto(
            input=paddle.layer.seq_slice(input=lstm_layer,
                starts=paddle.layer.first_seq(input=lstm_layer), ends=None),
            bias_attr=False)
        lstm_sum_expand = paddle.layer.expand(input=lstm_sum, expand_as=lstm_layer,
            expand_level=paddle.layer.ExpandLevel.FROM_SEQUENCE)`

        attention_input_seq = []
        attention_input_seq.append(
            paddle.layer.fc(
                input=lstm_sum_expand,
                size=attention_dim,
                act=paddle.activation.Linear(),
                bias_attr=False))
        attention_input_seq.append(
            paddle.layer.fc(
                input=lstm_layer,
                size=attention_dim,
                act=paddle.activation.Linear(),
                bias_attr=False))
        attention_input_seq.append(
            paddle.layer.fc(
                input=position_emb_layer,
                size=attention_dim,
                act=paddle.activation.Linear(),
                bias_attr=False))

        attention_input_sum = paddle.layer.addto(input=attention_input_seq)

        raw_weight = paddle.layer.fc(input=attention_input_sum, size=1)
        normalized_weight = paddle.layer.fc(input=raw_weight, size=1,
            act=paddle.activation.SequenceSoftmax())
        return normalized_weight`

**Comment by luotao1** [comment]
> lstm_sum_expand = paddle.layer.expand(input=lstm_sum, expand_as=lstm_layer, expand_level=paddle.layer.ExpandLevel.FROM_SEQUENCE)

ExpandLevel的用法参见：[here](http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#expandlevel)
这里没有使用双层序列，所以不用配置expand_level，使用默认值即可。

**Comment by April0402** [comment]
修改了之后仍然有错，这次的报错信息是：
F0320 17:07:32.670521  2620 ExpandLayer.cpp:66] Check failed: dataInput.getBatchSize() == shapeInput.getNumSequences()

> lstm_sum = paddle.layer.addto(
        input=paddle.layer.seq_slice(input=lstm_layer,
            starts=paddle.layer.first_seq(input=lstm_layer), ends=None),
        bias_attr=False)
    lstm_sum_expand = paddle.layer.expand(input=lstm_sum, expand_as=lstm_layer,
        expand_level=paddle.layer.ExpandLevel.FROM_SEQUENCE)

在这两句里，我希望做的就是把sequence中每个token的LSTM层的输出做加和，然后再把这个加和后的vector扩展成和原始sequence长度相同，然后再一起计算。我现在这样写是对的吗？

**Comment by luotao1** [comment]
> input=paddle.layer.seq_slice(input=lstm_layer,
starts=paddle.layer.first_seq(input=lstm_layer), ends=None)

根据[seq_slice](http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#seq-slice)的说明，ends=None时，slice出的是从starts到ends的，而这里的starts是first-seq，也就是说这个seq_slice没起作用。

> 我希望做的就是把sequence中每个token的LSTM层的输出做加和

可以使用`paddle.v2.layer.pooling`么，把`pooling_type=SumPooling()`，然后再用expand？

**Comment by April0402** [comment]
ok了，非常感谢！
