### ISSUE TITLE
paddle中train函数的参数feeding怎么理解

### ISSUE THREAD

**Issue by know133** [PaddlePaddle/Paddle#9244]
看了paddle的训练的参数定义如下：
def train(self, reader, num_passes=1, event_handler=None, feeding=None)
其中feeding这个怎么理解，看代码好像是为了兼容样本的输入格式，能不能举个具体的例子说下，看demo中有些没有加这些参数，有些加了。
譬如样本格式分别如下:
1.([1,2,3,],[4,5,],[4,5,6,7])来自nmt的样本，不加feeding
2.([1.0, 2.0, 3.0, ...], 5) 来自text-calassfication的样本，加feeding

**Comment by luotao1** [comment]
可以参考注释：https://github.com/PaddlePaddle/Paddle/blob/5008020d19ae6ae08d92855b01a7fedd70f765f7/python/paddle/v2/data_feeder.py#L28-L84

简单来说，feeding是一个字典，“If mini-batch data and data layers are not one to one mapping, we could pass a dictionary to feeding parameter to represent the mapping relationship.” 正常情况下，是按顺序排列的。
