### ISSUE TITLE
fluid分布式版本pserver出现SIGSEGV

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#9245]
*** Aborted at 1521532634 (unix time) try "date -d @1521532634" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x8) received by PID 298 (TID 0x7f0b2f5fe700) from PID 8; stack trace: ***
    @     0x7f0d99645500 (unknown)
    @     0x7f0d4cddb878 paddle::framework::Scope::FindVarLocally()
    @     0x7f0d4cddb924 paddle::framework::Scope::FindVar()
    @     0x7f0d4ce185ae paddle::operators::detail::RequestGet::Process()
    @     0x7f0d4ce12367 paddle::operators::detail::AsyncGRPCServer::HandleRequest()
    @     0x7f0d4ce15695 std::thread::_Impl<>::_M_run()
    @     0x7f0d8f7a3470 (unknown)
    @     0x7f0d9963d851 start_thread
    @     0x7f0d98d0090d clone
    @                0x0 (unknown)

**Comment by typhoonzero** [comment]
Please provide the following details of this issue:

1. how to reproduce this situation?
1. does it appears every time you run or randomly?
1. what version did you use?
1. what was your code snippet?

**Comment by Yancey1989** [comment]
The same error while turn on the glog as env `GLOG_v=3 GLOG_logtostderr=1 python xxx.py`

**Comment by typhoonzero** [comment]
Just turn off `GLOG_v=3 `

**Comment by xymyeah** [comment]
没有开启过GLOG_v=3这个参数

**Comment by typhoonzero** [comment]
> Please provide the following details of this issue:
> how to reproduce this situation?
> does it appears every time you run or randomly?
> what version did you use?
> what was your code snippet?

**Comment by Yancey1989** [comment]
Close this inactive issue, please feel free to reopen it.
