### ISSUE TITLE
should we remove/disable Centos6u3-CAPI from CI?

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#9263]
[Centos6u3-CAPI](https://paddleci.ngrok.io/project.html?projectId=Centos6u3capi&tab=projectOverview) is still actively building every day, but it fails all the time due to the out-of-date paddle dev docker image. 
from what I read (#6574 and #8376), this project should be deprecated and moved into manylinux project. 
is there any reason we still keep it or we can remove it from CI?

**Comment by Yancey1989** [comment]
This project is deprecated, and I will remove it, thanks for reminding!

**Comment by putcn** [comment]
thanks @Yancey1989
