### ISSUE TITLE
关于预训练模型的几个问题？

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#9274]
在推文中，我再次看到了[预训练模型](http://www.paddlepaddle.org/docs/develop/models/image_classification/README.html#permalink-12--)这个问题，我还是有几个不懂，请各位赐教：
1. [场景文字识别](https://github.com/PaddlePaddle/models/tree/develop/ssd#to-use-pre-trained-model) 这个预训练的模型是不是训练ImageNet数据集得到的模型？#8530
2. 预训练跟迁移有什么关系，感觉是一个东西？
3. 在PaddlePaddle上使用其他的数据集训练的模型，迁移到自己的数据集上训练，需要对模型修改什么吗？比如类别总数不一样了，这样的问题？下面是加载预训练的代码
```python
# 第一种
parameters = paddle.parameters.Parameters.from_tar(gzip.open('Paddle_ResNet50.tar.gz', 'r'))
# 第二种
parameters = paddle.parameters.create(cost)
parameters.init_from_tar(gzip.open('Paddle_ResNet50.tar.gz', 'r'))
```

**Comment by typhoonzero** [comment]
1. 你应该是指SSD，使用的数据集的描述就在你发的链接里：https://github.com/PaddlePaddle/models/tree/develop/ssd#pascal-voc-data-set
1. 迁移是指？
1. 使用其他的数据集训练的模型，迁移到自己的数据集上训练，可以复用用网络模型配置，但不可以复用预训练模型参数，由于“自己的数据集”和demo的数据集分布完全不一样，也可能需要不断的调整模型配置中的参数已达到预期的效果。

**Comment by yeyupiaoling** [comment]
@typhoonzero 
1. 我指的是SSD那个例子使用到的[预训练模型](https://github.com/PaddlePaddle/models/tree/develop/ssd#to-use-pre-trained-model)，我只知道这个模型是从caffe转换过来的，那它是训练哪些数据得到的呢？
2. 迁移学习，好像也叫微调，那它跟预训练有什么关系

>也可能需要不断的调整模型配置中的参数已达到预期的效果

这个是要我们手动去处理是吧？

**Comment by typhoonzero** [comment]
1. 数据集是：https://github.com/PaddlePaddle/models/tree/develop/ssd#pascal-voc-data-set
1. 可以参考下 https://www.zhihu.com/question/41979241 刚才搜到的
1. 对的。我理解即使使用迁移学习，是否能有效果提升也需要不断地验证。

**Comment by yeyupiaoling** [comment]
@typhoonzero 
好的，谢谢
