### ISSUE TITLE
百度DeepSeech官网提供的链接下载中文语言模型失败

### ISSUE THREAD

**Issue by bluebird138** [PaddlePaddle/Paddle#9278]
DeepSpeech网页下载 Mandarin LM Small 失败
网页：https://github.com/PaddlePaddle/DeepSpeech
下载连接：http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e

DeepSpeech的 DeepSpeech/models/lm/download_lm_ch.sh 里面下载 zh_giga.no_cna_cmn.prune01244.klm 失败
URL=http://cloud.dlnel.org/filepub/?uuid=d21861e4-4ed6-45bb-ad8e-ae417a43195e
MD5="29e02312deb2e59b3c8686c7966d4fe3"
TARGET=./zh_giga.no_cna_cmn.prune01244.klm

以上都提示文件不存在，可以使用火狐浏览器59.01测试。

**Comment by pkuyym** [comment]
@bluebird138 This is a hot fix, please using `http://cloud.dlnel.org/filepub/?uuid=5cd1688e-78d9-4b9e-9c2f-6f104bd5b518` to replace the old url.
