### ISSUE TITLE
fluid分布式版本不收敛

### ISSUE THREAD

**Issue by xymyeah** [PaddlePaddle/Paddle#9279]
fluid分布式版本不收敛，单机可以收敛，但是分布式（分开的一个pserver、一个trainer）却一直无法收敛，用的数据集是一样的，代码已经私下给了 @typhoonzero

**Comment by typhoonzero** [comment]
Due to the detailed information cannot be published here, I'll close this issue for now.

**Comment by xymyeah** [comment]
分别用如下两个版本，对fluid分布式进行的验证
commitid: ed2bc194c5f5a404e0f70edd29688f23482ca7f0 （2018-03-20中午从github获取的代码）
commitid: 48f213e5a1f89035e35810b7d4445802d5f154a1 （2018-03-14日从github获取的代码）
分布式（分开的一个pserver、一个trainer）都无法收敛，代码请参见线下发给你的

**Comment by typhoonzero** [comment]
目前是有这个问题，和GPU async有关系，正在解决

**Comment by xymyeah** [comment]
主要跑的还是cpu版本的
