### ISSUE TITLE
关于 sequence_conv_pool

### ISSUE THREAD

**Issue by wyq136** [PaddlePaddle/Paddle#9283]
如果输入的一个序列的长度为1， 而卷积核大小为3，这个会怎么计算？
比如输入为  [A]，那么是补0使用 [0, A, 0] 来计算吗？

**Comment by typhoonzero** [comment]
fluid中的确是会默认padding 0，如果设置`paddingTrainable`也可以配置padding可训练。

**Comment by hf136** [comment]
那如果设置了 paddingTrainable = True，那是相当于给卷积核训练了一个bias项吗？
