### ISSUE TITLE
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function

### ISSUE THREAD

**Issue by BigFishMaster** [PaddlePaddle/Paddle#9290]
when running se-resnext-50 networking to train imagenet-1000 dataset, I got an ERROR as below.
```python
Traceback (most recent call last):
  File "se_resnext50_parallel.py", line 237, in <module>
    train(learning_rate=0.1, batch_size=256, num_passes=120, init_model=None)
  File "se_resnext50_parallel.py", line 174, in train
    exe.run(fluid.default_startup_program())
  File "/ssd1/yancanxiang/se_resnext50_parallel_MSRA_imagenet1000/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/executor.py", line 373, in run
    self.executor.run(program.desc, scope, 0, True, True)
RuntimeError: function_attributes(): after cudaFuncGetAttributes: invalid device function
```
I use the paddle-wheel from folows:
paddle url：https://paddleci.ngrok.io/viewType.html?buildTypeId=Manylinux1_Cuda80cudnn5cp27cp27mu
wheel：https://paddleci.ngrok.io/repository/download/Manylinux1_Cuda80cudnn5cp27cp27mu/31050:id/paddlepaddle_gpu-0.11.0-cp27-cp27mu-linux_x86_64.whl

**Comment by typhoonzero** [comment]
cuda error "invalid device function" usually means your CUDA library does not fit your hardware and driver.

dup: https://github.com/PaddlePaddle/Paddle/issues/7820 https://github.com/PaddlePaddle/Paddle/issues/6524 https://github.com/PaddlePaddle/Paddle/issues/5674 https://github.com/PaddlePaddle/Paddle/issues/5629 https://github.com/PaddlePaddle/Paddle/issues/34

**Comment by BigFishMaster** [comment]
Ok, I will check this. @typhoonzero

**Comment by BigFishMaster** [comment]
@typhoonzero I tried (cuda8 + cudnn5/cudnn5.1 + driver384.81/384.66) 4 combination, but failed.

**Comment by BigFishMaster** [comment]
@qingqing01 I meet a gcc problem:
```
ImportError: /opt/compiler/gcc-4.8.2/lib/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /ssd1/yancanxiang/se_resnext50_parallel_MSRA_imagenet1000/python-gcc482-paddle/lib/python2.7/site-packages/paddle/fluid/core.so)
```

**Comment by BigFishMaster** [comment]
I tried jumbo with gcc5.3 and paddle is ok. Thanks @qingqing01
