### ISSUE TITLE
build_and_install URL failed.

### ISSUE THREAD

**Issue by livc** [PaddlePaddle/Paddle#931]
>安装
>
>请参考 安装教程 安装PaddlePaddle。

"[安装教程](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/build_and_install/index.html) " URL in https://github.com/PaddlePaddle/Paddle/blob/develop/doc/tutorials/quick_start/index_cn.rst failed.

**Comment by luotao1** [comment]
http://www.paddlepaddle.org/doc_cn/demo/quick_start/index.html，网页中是可以正常打开的。
