### ISSUE TITLE
Floating point exception

### ISSUE THREAD

**Issue by fty8788** [PaddlePaddle/Paddle#9317]
用DSSM，只是换了一份训练数据重训模型，就出现Floating point exception的core

I0322 14:36:48.685048 16304 MultiGradientMachine.cpp:99] numLogicalDevices=1 numThreads=4 numDevices=16
I0322 14:36:48.821815 16304 GradientMachine.cpp:85] Initing parameters..
I0322 14:37:08.328995 16304 GradientMachine.cpp:92] Init parameters done.
[INFO 2018-03-22 14:37:08,539 reader.py:33] [reader] load trainset from dssm_query_title
*** Aborted at 1521700631 (unix time) try "date -d @1521700631" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0x7f3bb1864e39) received by PID 16304 (TID 0x7f3bf4ae0700) from PID 18446744072392953401; stack trace: ***
    @     0x7f3bf46b7160 (unknown)
    @     0x7f3bb1864e39 paddle::AucEvaluator::evalImp()
    @     0x7f3bb1865805 paddle::Evaluator::eval()
    @     0x7f3bb1831048 paddle::CombinedEvaluator::eval()
    @     0x7f3bb18363f2 paddle::MultiGradientMachine::eval()
    @     0x7f3bb16e6daa _wrap_GradientMachine_eval
    @           0x4b4cb9 PyEval_EvalFrameEx
    @           0x4b6b28 PyEval_EvalCodeEx
    @           0x4b5d10 PyEval_EvalFrameEx
    @           0x4b6b28 PyEval_EvalCodeEx
    @           0x4b5d10 PyEval_EvalFrameEx
    @           0x4b6b28 PyEval_EvalCodeEx
    @           0x4b5d10 PyEval_EvalFrameEx
    @           0x4b6b28 PyEval_EvalCodeEx
    @           0x4b6c52 PyEval_EvalCode
    @           0x4e1c7d PyRun_FileExFlags
    @           0x4e3501 PyRun_SimpleFileExFlags
    @           0x4159dd Py_Main
    @     0x7f3bf3c11bd5 __libc_start_main
    @           0x414b71 (unknown)
    @                0x0 (unknown)
Floating point exception

**Comment by chengduoZH** [comment]
请检查一下您的数据是否有异常，比如是否有Nan数据等等

**Comment by fty8788** [comment]
肉眼看数据看不出啥异常来，通过调batch_size定位到数据行，再batch_size=1去训练，错误不复现。。

**Comment by jacquesqiao** [comment]
参考 https://github.com/jacquesqiao/Paddle/wiki/Paddle-Float-Point-exception%E7%9A%84%E9%97%AE%E9%A2%98%E5%8E%9F%E5%9B%A0

**Comment by fty8788** [comment]
有时候是这个错误
这个是梯度爆炸么？
F0327 13:47:16.693892  6463 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
*** Check failure stack trace: ***
F0327 13:47:16.693892  6454 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
*** Check failure stack trace: ***
*** Check failure stack trace: ***
F0327 13:47:16.693892  6454 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encounteredF0327 13:47:16.695104  6459 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encounteredF0327 13:47:16.695104  6455 hl_cuda_device.cc:565] Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered
*** Check failure stack trace: ***
    @     0x7fc5607365ed  google::LogMessage::Fail()
    @     0x7fc5607365ed  google::LogMessage::Fail()
    @     0x7fc5607365ed  google::LogMessage::Fail()
    @     0x7fc5607365ed  google::LogMessage::Fail()
    @     0x7fc56073a09c  google::LogMessage::SendToLog()
    @     0x7fc56073a09c  google::LogMessage::SendToLog()
    @     0x7fc56073a09c  google::LogMessage::SendToLog()
    @     0x7fc56073a09c  google::LogMessage::SendToLog()
    @     0x7fc5607360e3  google::LogMessage::Flush()
    @     0x7fc5607360e3  google::LogMessage::Flush()
    @     0x7fc5607360e3  google::LogMessage::Flush()
    @     0x7fc5607360e3  google::LogMessage::Flush()
    @     0x7fc56073b5ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc56073b5ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc56073b5ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc56073b5ae  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc5606f40d7  hl_stream_synchronize()
    @     0x7fc5606f40d7  hl_stream_synchronize()
    @     0x7fc5606f40d7  hl_stream_synchronize()
    @     0x7fc5606f40d7  hl_stream_synchronize()
    @     0x7fc560464a03  paddle::TrainerThread::copyGradToBufferThread()
    @     0x7fc56070d54f  hl_max_sequence_backward()
    @     0x7fc5605c0e17  hl_gpu_apply_unary_op<>()
    @     0x7fc5605c0e17  hl_gpu_apply_unary_op<>()
    @     0x7fc56057233e  paddle::GpuMatrix::maxSequenceBackward()
    @     0x7fc59eed78a0  execute_native_thread_routine
    @     0x7fc5605c1205  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7fc5605c1205  paddle::BaseMatrixT<>::applyUnary<>()
    @     0x7fc5603c1e2e  paddle::MaxLayer::backward()
    @     0x7fc5b02dc1c3  start_thread
    @     0x7fc5605c1433  paddle::BaseMatrixT<>::zero()
    @     0x7fc5605c1433  paddle::BaseMatrixT<>::zero()
    @     0x7fc56045b8d1  paddle::NeuralNetwork::backward()
    @     0x7fc5af90412d  __clone
    @     0x7fc560465fd2  paddle::TrainerThread::backward()
    @     0x7fc560566ee5  paddle::GpuMatrix::zeroMem()
    @     0x7fc560566ee5  paddle::GpuMatrix::zeroMem()
    @              (nil)  (unknown)
Aborted

**Comment by chengduoZH** [comment]
@fty8788 可能是的
>  Check failed: cudaSuccess == cudaStat (0 vs. 77) Cuda Error: an illegal memory access was encountered

这种错误一般是因为数据异常导致的，而数据之所以异常很可能是梯度异常（梯度太多或者太小）

**Comment by chengduoZH** [comment]
该issue长时间没有反馈，可以先关闭了，如要继续讨论请再打开
