### ISSUE TITLE
Fluid保存模型时报错‘NoneType’ object has no attribute 'block'

### ISSUE THREAD

**Issue by JadyXuan** [PaddlePaddle/Paddle#9322]
使用fluid.io.save_inference_model(model_path, ['image'], [img], exe)命令保存模型时报错：
Traceback (most recent call last):
  File "fc_gan.py", line 168, in <module>
    main()
  File "fc_gan.py", line 165, in main
    fluid.io.save_inference_model(model_path, ['image'], [img], exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/io.py", line 191, in save_inference_model
    pruned_program = main_program.prune(targets=target_vars)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/framework.py", line 747, in prune
    targets_idx.append([t.block.idx, t.idx])
AttributeError: 'NoneType' object has no attribute 'block'
请问一下是出了什么问题呢？

更正一下，之前的错误好像是参数出错，原fc_gan.py把img赋值到了g_img所以我弄错了参数。
但是纠正之后fluid.io.save_inference_model(model_path, ['image'], [g_img], exe)命令还是报错，indexerror：
Traceback (most recent call last):
  File "fc_gan.py", line 168, in <module>
    main()
  File "fc_gan.py", line 165, in main
    fluid.io.save_inference_model(model_path, ['img','label'], [g_img], exe)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/io.py", line 191, in save_inference_model
    pruned_program = main_program.prune(targets=target_vars)
  File "/usr/local/lib/python2.7/dist-packages/paddle/v2/fluid/framework.py", line 749, in prune
    res.desc = core.prune(self.desc, targets_idx)
IndexError: deque::_M_range_check
这里是出了什么错误呢？求大佬指点。

**Comment by chengduoZH** [comment]
你跑的模型是什么样子的？

**Comment by JadyXuan** [comment]
@chngduoZH 是一个fc_gan的例子在这里https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/tests/demo/fc_gan.py
我在main函数底下插了一个保存模型的命令。

**Comment by chengduoZH** [comment]
`fc_gan.py`里面的代码是很早之前写的，后面也没有更新
你可以看这个例子： https://github.com/PaddlePaddle/Paddle/blob/8f8728635a028e5ef69498cae109366302a048ee/python/paddle/fluid/tests/book/test_recommender_system.py#L240-L244

**Comment by JadyXuan** [comment]
@chengduoZH  @yeyupiaoling  请问这个命令里面的["user_id","gender_id", "age_id", "job_id", 
         "movie_id", "category_id", "movie_title" ]参数有什么含义呢？因为fc_gan.py这个文件里面没有保存模型的命令，所以我想自己添加一条，但是报错了，找不出原因在哪里。这两个例子都是fluid版本，保存模型的命令应该是通用的吧？

**Comment by chengduoZH** [comment]
@JadyXuan  请问问题解决了吗？

**Comment by JadyXuan** [comment]
@chengduoZH  还没有，最近在复习，没有时间。。。 不过因为报错信息是IndexError: deque::_M_range_check 不是python的报错，所以暂时不知道怎么办。用其他例子保存模型的时候并不会出错，可能是fc_gan.py这个例子本身没有考虑到保存模型所以生成的模型格式不一样？

**Comment by yeyupiaoling** [comment]
@JadyXuan 
好好复习吧，未来还是你的。百日誓师过了吧。好好努力。

**Comment by JadyXuan** [comment]
@yeyupiaoling  不存在什么百日誓师orz。。。我们从高二就开始高考。。。所以现在这个也不过是尘埃落定的一次。。。
