### ISSUE TITLE
训练时候embedding能否给0加速计算

### ISSUE THREAD

**Issue by windy444** [PaddlePaddle/Paddle#9323]
有一堆特征slot，每个都需要embedding，但是对于一个样本来说，其中大多数是缺失的，一般情况下，会给个unk之类的，有没有办法给0之类的，来加速计算

**Comment by chengduoZH** [comment]
请问您用的Fluid还是V2?

**Comment by windy444** [comment]
@chengduoZH 是V2

**Comment by chengduoZH** [comment]
@windy444  应该是可以的，不过如果要实现这个的话可能得对一段时间

**Comment by typhoonzero** [comment]
V2可以再配置optimizer是加参数`sparse=True`就可以

**Comment by windy444** [comment]
@typhoonzero 
主要是如何设计输入0向量，如果embedding都一样的，可以用个序列，不必所有的都输入。但是如果embedding都是单独的，这个如何处理呢？我目前只会对缺失的设置一个UNK，还是会参与到embedding训练中去
