### ISSUE TITLE
请问paddle有什么好工具或方法进行特征分析

### ISSUE THREAD

**Issue by Kayven** [PaddlePaddle/Paddle#9328]
想看看是哪些输入或卷积核使得输入被预测成了那一类，以便找到分错的原因，或者进行重要性分析，或者看输入特征样本分布的影响。

不知道有没有比较好的方法或工具，成本低些，请赐教。

**Comment by chengduoZH** [comment]
目前来说应该还没有太好的工具能够达到你要求。

在机器学习里面，比如LR，你可以根据学到权重分析出哪个特征是重要，进而帮助进一步的分析问题。但是目前来说对于深度学习还是一个黑盒子，还不能根据学习的权重得出哪个特征更重要。

这里一个一篇介绍特征可视化的文章你可以参考一下: [Deep Visualization:可视化并理解CNN](https://zhuanlan.zhihu.com/p/24833574)

**Comment by chengduoZH** [comment]
该issue已答复，可以close了，如需进一步讨论，请重新打开，
