### ISSUE TITLE
fail when batch_size < trainer_count

### ISSUE THREAD

**Issue by lzhao4ever** [PaddlePaddle/Paddle#933]
When I set trainer_count=4 and batch_size=1 in cpu mode, the second thread got batchSize=0.
Attached are train.sh and config file.

[train.zip](https://github.com/PaddlePaddle/Paddle/files/658412/train.zip)

**Comment by hedaoyuan** [comment]
Yes, the current implementation requires batch_size greater than trainer_count, otherwise there will be problems.
