### ISSUE TITLE
V2 API里应该用哪个方法来做一维卷积

### ISSUE THREAD

**Issue by realsnake** [PaddlePaddle/Paddle#9335]
尝试使用sequence_conv_pool，这个的输出好像无法再作为下一个sequence_conv_pool的输入。
我想实现如图所示的网络结构，应该怎么写？
![image](https://user-images.githubusercontent.com/1198818/37821928-07a53892-2ec0-11e8-990f-6f82d2191ac8.png)

**Comment by kuke** [comment]
V2中支持一维卷积的就是这个API
https://github.com/PaddlePaddle/Paddle/blob/76ae540f8ef3dc5463da6127556fc48a343698c9/python/paddle/trainer_config_helpers/networks.py#L40-L55

其输出作为下一个sequence_conv的输入应该也是没有问题的，请问你遇到的报错是什么？

**Comment by realsnake** [comment]
@kuke  我是参考情感分类的例子，我的net如下，其中input_dim是3：
![image](https://user-images.githubusercontent.com/1198818/37883187-8b48bcb0-30db-11e8-8a75-cc5a61605481.png)
当红框里为conv_3时正常，改为conv_4时，报错信息如下：
F0326 01:54:23.681402   319 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
    @     0x7f15da4f377d  google::LogMessage::Fail()
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686344   318 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686344   318 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686486   320 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686344   318 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686486   320 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686691   315 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15e8bd1c80  (unknown)
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15e8bd1c80  (unknown)
    @     0x7f15fa31e6ba  start_thread
F0326 01:54:23.683117   317 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 0101::5454::2323.684893684893   316  322  ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686344   318 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686486   320 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.686691   315 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions F0326 01:54:23.689934   321 ContextProjection.cpp:108] Check failed: in_->sequenceStartPositions 
*** Check failure stack trace: ***
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da4f377d  google::LogMessage::Fail()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da4f722c  google::LogMessage::SendToLog()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da4f32a3  google::LogMessage::Flush()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da4f873e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da27fcc3  paddle::ContextProjection::forward()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da1d8a49  paddle::MixedLayer::forward()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15e8bd1c80  (unknown)
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15fa0543dd  clone
    @     0x7f15fa31e6ba  start_thread
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15da2a46bd  paddle::NeuralNetwork::forward()
    @     0x7f15fa0543dd  clone
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @     0x7f15e8bd1c80  (unknown)
    @     0x7f15fa31e6ba  start_thread
    @     0x7f15da2c5ca4  paddle::TrainerThread::forward()
    @              (nil)  (unknown)
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15fa0543dd  clone
    @     0x7f15e8bd1c80  (unknown)
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
    @     0x7f15da2c6f05  paddle::TrainerThread::computeThread()
Aborted

**Comment by kuke** [comment]
@realsnake 抱歉才看到你的回复，这个问题是否解决了？

**Comment by MonkandMonkey** [comment]
我也有同样的问题，请问多层卷积网络应该怎么搭建呢？

**Comment by jiachengni** [comment]
我也有同样的问题，请问sequence_conv_pool构造多层卷积网络应该怎么搭建呢？
