### ISSUE TITLE
calculate  gradient w.r.t input in loss？

### ISSUE THREAD

**Issue by buaawht** [PaddlePaddle/Paddle#9371]
tensorflow和pytorch都支持对输入求梯度，不知道paddle可以求吗？特别地，对于含有BatchNormalization层的CNN网络能这样对输入求梯度吗？

**Comment by guoshengCS** [comment]
Paddle Fluid中是可以的，在设置data layer时指定`stop_gradient=False`即可，示例如下：
```python
layers.data(
        name="data",
        shape=[32, 3, 224, 224],
        dtype="int64",
        append_batch_size=False,
        stop_gradient=False)
```
然后可以通过`data@GRAD`取出梯度的值。

**Comment by guoshengCS** [comment]
已经提供答复且较久未更新，这里先行close，如有需要还请reopen。
