### ISSUE TITLE
API doc problems of ones, zeros

### ISSUE THREAD

**Issue by ranqiu92** [PaddlePaddle/Paddle#9379]
#### 单词拼写、遗漏和语法等问题未列出，修改时请注意
*请参考[API注释标准](https://github.com/PaddlePaddle/Paddle/blob/develop/doc/fluid/dev/api_doc_std_cn.md)！*
------
源文件：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/tensor.py

- ones
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#ones
  - 参数介绍与参数列表不符
  - 介绍须改善
  - 数据类型问题（None不作为数据类型）
  - 格式问题（returns等）

- zeros
http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html#zeros
  - 同上

**Comment by typhoonzero** [comment]
These pages seem not exist anymore, @shanyi15 can you please take a look at this? It seems that there's quite a lot of this kind issues there.
