### ISSUE TITLE
Does paddle work on a Nvidia Jetson TX1

### ISSUE THREAD

**Issue by sunils27** [PaddlePaddle/Paddle#939]
Has anyone built paddle on a Jetson TX1?
Didn't find anything so figured I'd post it here. 

Thanks for the info. 
Sunil

**Comment by hedaoyuan** [comment]
At present may not work. 
The ARM environment is not yet supported.

**Comment by hedaoyuan** [comment]
The present Paddle already supports Jetson TX1, and also supports DRIVE PX. And support Android, raspberry and other embedded environments.

**Comment by yxnal** [comment]
I would like to ask you a question：
how to source compile on jetson TX1？
