### ISSUE TITLE
paddle production docker image default command error

### ISSUE THREAD

**Issue by putcn** [PaddlePaddle/Paddle#9391]
I built my own production image with dockerfile from build directory. When I try to run this image, the default command throws error as follows:
``` bash
[root@k8s-node1 ~]# docker run --rm -it putcn/paddle:pro
/usr/local/bin/paddle: line 158: [: 0.10.0: binary operator expected
  File "<stdin>", line 3
    if LooseVersion("0.10.0
                          ^
SyntaxError: EOL while scanning string literal
```

looks like the there are some syntax issues, as well as version detecting issue. 
and turnd out this line:
``` bash
INSTALLED_VERSION=`pip freeze 2>/dev/null | grep "^paddle" | sed 's/.*==//g'`
```
is hitting both `paddlepaddle` and `paddlepaddle-gpu`, which broke the rest of execution.

**Comment by wangkuiyi** [comment]
Were you following http://www.paddlepaddle.org/docs/0.10.0/documentation/en/getstarted/build_and_install/docker_install_en.html#develop-paddlepaddle-or-train-model-using-c-api ? Thanks!

**Comment by putcn** [comment]
I was. In production image there is a paddle cmd script added to PATH, and it's executed by default as "paddle version" to print paddle version if no training script is provided.
the issue is due to the cmd script's syntax issue and one version detecting logic issue, which are fixed within above PR.
