### ISSUE TITLE
如何将dense_vector_sequence平铺成dense_vector数据？

### ISSUE THREAD

**Issue by hyo009** [PaddlePaddle/Paddle#9394]
如题，经过RNN处理后的dense_vector_sequence数据层想平铺成dense_vector类型。

**Comment by wanghaoshuang** [comment]
如果你的sequence是定长的，可以考虑用[resize_layer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L7340).

**Comment by wanghaoshuang** [comment]
使用resize_layer的原理如下所示：
![image](https://user-images.githubusercontent.com/7534971/37943674-0f66f19a-31ab-11e8-812d-53b7c6602b97.png)

**Comment by wanghaoshuang** [comment]
Please feel free to reopen it.
