### ISSUE TITLE
模型本地预测可以，mpi预测模型时出错

### ISSUE THREAD

**Issue by shenchong721** [PaddlePaddle/Paddle#9397]
infer函数中使用的是paddle.data_type.sparse_float_vector，使用paddle api提交后显示 'module' object has no attribute 'sparse_float_vector'。

按照#8926 说明，用sparse_vector代替sparse_float_vector，之后再运行时，显示如下错误，感觉是数据类型出了问题，因为在代码本地预测是正常运行的

Mon Mar 26 22:47:19 2018[1,0]<stderr>:Traceback (most recent call last):
Mon Mar 26 22:47:19 2018[1,0]<stderr>:  File "conf/trainer_config.conf", line 200, in <module>
Mon Mar 26 22:47:19 2018[1,0]<stderr>:    infer(model_path=model_path, batch_size=30000)
Mon Mar 26 22:47:19 2018[1,0]<stderr>:  File "conf/trainer_config.conf", line 182, in infer
Mon Mar 26 22:47:19 2018[1,0]<stderr>:    output = inferer.infer(input=test_batch,flatten_result=False,field=['value'],feeding=feeding)
Mon Mar 26 22:47:19 2018[1,0]<stderr>:  File "/home/disk1/normandy/maybach/662947/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 74, in infer
Mon Mar 26 22:47:19 2018[1,0]<stderr>:    for result in self.iter_infer_field(field=field, **kwargs):
Mon Mar 26 22:47:19 2018[1,0]<stderr>:  File "/home/disk1/normandy/maybach/662947/workspace/python27-gcc482/lib/python2.7/site-packages/paddle/v2/inference.py", line 61, in iter_infer_field
Mon Mar 26 22:47:19 2018[1,0]<stderr>:    for result in self.iter_infer(**kwargs):
Mon Mar 26 22:47:19 2018[1,0]<stderr>:TypeError: iter_infer() got an unexpected keyword argument 'flatten_result'

**Comment by wanghaoshuang** [comment]
第一个问题：'module' object has no attribute 'sparse_float_vector'。
应该是MPI使用的paddle版本落后于您的本地版本，所以MPI上找不到sparse_float_vector。

第二个问题：iter_infer() got an unexpected keyword argument 
应该也是版本问题，MPI上paddle版本没有flatten_result这个参数

你是通过什么方式提交MPI的？如果是receiver的话,可以通过这个[教程](http://wiki.baidu.com/pages/viewpage.action?pageId=327596461#%E8%87%AA%E5%AE%9A%E4%B9%89%E4%BB%BB%E5%8A%A1%E9%A2%84%E5%A4%84%E7%90%86%E8%84%9A%E6%9C%AC)使上传本地的paddle binary到MPI.

**Comment by shenchong721** [comment]
嗯嗯，按照[教程](http://www.paddlepaddle.org/docs/develop/documentation/zh/faq/local/index_cn.html#infer-layer) 解决这个问题了，由于我的infer只是输出倒数第二层一个vector，把flatten_result=False这个参数去掉，就可以正常运行了。谢谢！
