### ISSUE TITLE
Run fluid models and update current dist train performance result

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#9401]
We need to update performance results under `benchmark/cluster` to add different models:

codes:

https://github.com/PaddlePaddle/models/tree/develop/fluid

- NLP model:
  - text_classification  -- @typhoonzero
  - sequence_tagging_for_ner -- @putcn @helinwang 
  - neural_machine_translation --@gongweibao
- image model:
  - image_classification -- @seiriosPlus 
  - ResNet 50

Result metrics:

- speed of local mode
- dist mode speed up percentage (CPU/GPU)

**Comment by seiriosPlus** [comment]
I will add performance about image_classification.

**Comment by putcn** [comment]
Me and @helinwang will take sequence_tagging_for_ner

**Comment by wangkuiyi** [comment]
Please make sure that we maintain the performance testing/evaluation results on Google Docs, and please share the link here.

**Comment by wangkuiyi** [comment]
Could we do these performance evaluation via the continuous evaluation system developed by @Superjomn ?  If so,  it seems that the results will be continuously updated and could be shared publicly.

**Comment by typhoonzero** [comment]
@wangkuiyi sure! I will move perf tests to CI system once we have the baseline updated.

**Comment by Superjomn** [comment]
yes, the CE is already online for testing.  http://yq01-sys-hic-v100-box-a223-0007.yq01.baidu.com:8111/

**Comment by gongweibao** [comment]
@wangkuiyi We plan to add later https://github.com/PaddlePaddle/Paddle/issues/9046#issuecomment-375168986

**Comment by typhoonzero** [comment]
Result google doc link: https://docs.google.com/spreadsheets/d/1D5Xc_TfGfMV5aKh4ZJS_b4js3Mnn06H1Po0iuECZLr4/edit?usp=sharing

**Comment by typhoonzero** [comment]
@putcn I'm currently working on sequence_tagging_for_ner perf data now

**Comment by putcn** [comment]
@typhoonzero sorry I was working on aws tool, and thanks for taking this over. I made some progress on ner test, please refer to https://github.com/putcn/Paddle/tree/benchmark_cluster_ner if you need anything.

**Comment by typhoonzero** [comment]
Thanks! @putcn

**Comment by typhoonzero** [comment]
Done.
