### ISSUE TITLE
MPI集群提交任务一直失败

### ISSUE THREAD

**Issue by yuanzfy** [PaddlePaddle/Paddle#9407]
![image](https://user-images.githubusercontent.com/4515954/37958330-d0f5fd06-31e2-11e8-899d-55cb973b88e0.png)
提交任务命令：
function train() {
    local port=$1
    PATH=./mpi_env:${PATH}

    # 训练中需要用到的数据及程序都可以放在thirdparty中，通过--thirdparty上传至集群
    # 可以在thirdparty中添加before_hook.sh，在每个节点开始执行前会先执行该脚本

    cp ./paddle/common.py ./thirdparty
    cp ./paddle/config.py ./thirdparty
    cp ./paddle/trainer_config_v2.py ./thirdparty
    cp ./paddle/network.py ./thirdparty
    mkdir -p thirdparty/data
    cp ./data/word_2_id.tsv thirdparty/data
    cp ./data/psid_2_id.tsv thirdparty/data

    paddle cluster_train \
      --config ./paddle/train_v2_mpi.py \
      --port ${port} \
      --use_gpu cpu \
      --time_limit 0 \
      --submitter zoufangyuan01 \
      --num_nodes 10 \
      --job_priority high \
      --fs_name hdfs://nmg01-mulan-hdfs.dmop.baidu.com:54310 \
      --fs_ugi pa,J82K0JKl \
      --train_data_path ${HDFS_BASE}/train \
      --test_data_path ${HDFS_BASE}/test \
      --output_path ${HDFS_BASE}/mpi_output \
      --where nmg01-idl-dl-high-cpu-10G_cluster \
      --thirdparty ./thirdparty \
      --job_name train_v2_mpi \
      --init_model_path \"\" \
      2>&1 | tee log/mpi.log
}

**Comment by wanghaoshuang** [comment]
你先更新下paddle cloud clien试试？https://github.com/PaddlePaddle/cloud/blob/develop/doc/usage_cn.md

**Comment by typhoonzero** [comment]
报错可能是python程序中有exception导致，建议检查python程序并先在本地测试过再提交

**Comment by yuanzfy** [comment]
是概率性的，本地测试通过过，集群也成功过

**Comment by typhoonzero** [comment]
这种情况重试就行，或者用8091端口，同时提交的多也会这样

**Comment by yuanzfy** [comment]
我重试了一下午了~~~
