### ISSUE TITLE
Need to run make install inside Docker container before we can run examples

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9418]
Users must run make install as follows:

```bash
git clone https://github.com/paddlepaddle/paddle
cd paddle
docker build -t paddle:dev .
mkdir build
nvidia-docker run --rm -it -v $PWD:/paddle paddle:dev /bin/bash
$ cd /paddle/build
$ cmake ..
$ make -j56
```

After doing the above steps, we should have a built binary version of PaddlePaddle in `./paddle/build`, or `/paddle/build` in the container. I suppose that in the container, we should be able to run

```bash
$ python python/tests/book/test_fit_a_line.py
```

However, if I do so, Python would complain that it cannot import `paddle`.

It seems that we must run `make install` after `make` so could we run examples.  This doesn't make sense.

**Comment by wanglei828** [comment]
Before run the test, we need install the generated "whl" package using " pip install", the package is located in the "build/python/dist" directory.

**Comment by wangkuiyi** [comment]
Got it. Thanks.

Is it possible that we don't run `pip install` (nor `make install`), but can import paddle from Python?
