### ISSUE TITLE
请问以下报错是什么原因？

### ISSUE THREAD

**Issue by issca** [PaddlePaddle/Paddle#943]
I1218 14:29:30.308993    79 Util.cpp:155] commandline: /usr/local/bin/../opt/paddle/bin/paddle_trainer --config=./db_lstm.py --use_gpu=0 --log_period=5000 --trainer_count=1 --show_parameter_stats_period=5000 --save_dir=./output --num_passes=10000 --average_test_period=10000000 --init_model_path=./data --load_missing_parameter_strategy=rand --test_all_data_in_one_period=1 
I1218 14:29:30.309124    79 Util.cpp:130] Calling runInitFunctions
I1218 14:29:30.309283    79 Util.cpp:143] Call runInitFunctions done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3406, in parse_config_and_serialize
    config = parse_config(config_file, config_arg_str)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py", line 3382, in parse_config
    execfile(config_file, make_config_environment(config_file, config_args))
  File "./db_lstm.py", line 90, in <module>
    average_window=0.5, max_average_window=10000), )
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py", line 53, in __wrapper__
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py", line 441, in settings
    kwargs = __extends__(kwargs, each.to_setting_kwargs())
  File "/usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py", line 349, in __extends__
    assert key not in dict1
AssertionError
F1218 14:29:30.475177    79 PythonUtil.cpp:134] Check failed: (ret) != nullptr Current PYTHONPATH: ['/usr/local/opt/paddle/bin', '/home/code/demo/semantic_role_labeling', '/usr/lib/python2.7', '/usr/lib/python2.7/plat-x86_64-linux-gnu', '/usr/lib/python2.7/lib-tk', '/usr/lib/python2.7/lib-old', '/usr/lib/python2.7/lib-dynload', '/usr/local/lib/python2.7/dist-packages', '/usr/lib/python2.7/dist-packages']
Python Error: <type 'exceptions.AssertionError'> : 
Python Callstack: 
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3406
            /usr/local/lib/python2.7/dist-packages/paddle/trainer/config_parser.py : 3382
            ./db_lstm.py : 90
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/default_decorators.py : 53
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py : 441
            /usr/local/lib/python2.7/dist-packages/paddle/trainer_config_helpers/optimizers.py : 349
Call Object failed.
*** Check failure stack trace: ***
    @     0x7fcac2904daa  (unknown)
    @     0x7fcac2904ce4  (unknown)
    @     0x7fcac29046e6  (unknown)
    @     0x7fcac2907687  (unknown)
    @           0x76814a  paddle::callPythonFuncRetPyObj()
    @           0x76832c  paddle::callPythonFunc()
    @           0x684ef3  paddle::TrainerConfigHelper::TrainerConfigHelper()
    @           0x685534  paddle::TrainerConfigHelper::createFromFlags()
    @           0x513207  main
    @     0x7fcac1b10f45  (unknown)
    @           0x51f2a5  (unknown)
    @              (nil)  (unknown)
/usr/local/bin/paddle: line 109:    79 Aborted                 (core dumped) ${DEBUGGER} $MYDIR/../opt/paddle/bin/paddle_trainer ${@:2}

**Comment by qingqing01** [comment]
Please refer to #820

**Comment by issca** [comment]
您好，根据#820修改后还是有同样的问题，我将代码更新到 7b74a6d也不行。






At 2016-12-19 09:37:03, "qingqing01" <notifications@github.com> wrote:


Please refer to #820

**Comment by issca** [comment]
resolved

**Comment by shejay2017** [comment]
你好，请问你这个问题是怎么解决的啊，望告知，万分感谢！！！
