### ISSUE TITLE
使用libpaddle_capi_shared.so动态链接库，偶发core

### ISSUE THREAD

**Issue by likeqinqin** [PaddlePaddle/Paddle#9436]
只用一个卡，没有发现显存不足

#0  0x00007fab6f88a3f7 in raise () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#1  0x00007fab6f88b7d8 in abort () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#2  0x00007fab88dde115 in google::DumpStackTraceAndExit() () from ./extend/lib/libpaddle_capi_shared.so
#3  0x00007fab88dd4d3d in google::LogMessage::Fail() () from ./extend/lib/libpaddle_capi_shared.so
#4  0x00007fab88dd87ec in google::LogMessage::SendToLog() () from ./extend/lib/libpaddle_capi_shared.so
#5  0x00007fab88dd4863 in google::LogMessage::Flush() () from ./extend/lib/libpaddle_capi_shared.so
#6  0x00007fab88dd9cfe in google::LogMessageFatal::~LogMessageFatal() () from ./extend/lib/libpaddle_capi_shared.so
#7  0x00007fab891f0c34 in hl_malloc_device(unsigned long) () from ./extend/lib/libpaddle_capi_shared.so
#8  0x00007fab8903b5a6 in paddle::GpuAllocator::alloc(unsigned long) () from ./extend/lib/libpaddle_capi_shared.so
#9  0x00007fab8901ee4f in paddle::PoolAllocator::alloc(unsigned long) () from ./extend/lib/libpaddle_capi_shared.so
#10 0x00007fab8901e854 in paddle::GpuMemoryHandle::GpuMemoryHandle(unsigned long) () from ./extend/lib/libpaddle_capi_shared.so
#11 0x00007fab8904ae97 in paddle::GpuMatrix::GpuMatrix(unsigned long, unsigned long, bool) () from ./extend/lib/libpaddle_capi_shared.so
#12 0x00007fab8904b830 in paddle::Matrix::create(unsigned long, unsigned long, bool, bool) () from ./extend/lib/libpaddle_capi_shared.so
#13 0x00007fab8905c311 in paddle::Matrix::resizeOrCreate(std::shared_ptr<paddle::Matrix>&, unsigned long, unsigned long, bool, bool) ()
   from ./extend/lib/libpaddle_capi_shared.so
#14 0x00007fab88ebdfd2 in paddle::Layer::resetSpecifyOutput(paddle::Argument&, unsigned long, unsigned long, bool, bool) ()
   from ./extend/lib/libpaddle_capi_shared.so
#15 0x00007fab88ebe284 in paddle::Layer::resetOutput(unsigned long, unsigned long) () from ./extend/lib/libpaddle_capi_shared.so
#16 0x00007fab88f45031 in paddle::BatchNormalizationLayer::forward(paddle::enumeration_wrapper::PassType) ()
   from ./extend/lib/libpaddle_capi_shared.so
#17 0x00007fab88f53d0d in paddle::NeuralNetwork::forward(std::vector<paddle::Argument, std::allocator<paddle::Argument> > const&, std::vector<paddle::Argument, std::allocator<paddle::Argument> >*, paddle::enumeration_wrapper::PassType) () from ./extend/lib/libpaddle_capi_shared.so
#18 0x00007fab88dcfd76 in paddle_gradient_machine_forward () from ./extend/lib/libpaddle_capi_shared.so

**Comment by agxcul** [comment]
显存只用了1/4，gpu利用率也只有50-70%

**Comment by ranqiu92** [comment]
能提供详细的信息吗，用的什么模型，是怎么调用的，是每次运行都出相同的问题吗
