### ISSUE TITLE
Is it possible to somehow apply CNN layer to non-square (spectrogram) inputs?

### ISSUE THREAD

**Issue by F0REacH** [PaddlePaddle/Paddle#944]
I am trying to replicate model similar to [DeepSpeech2](https://arxiv.org/abs/1512.02595) and [neon example](https://github.com/NervanaSystems/deepspeech/blob/master/speech/train.py) ( [spectrogram ~4000 timesteps each of size 512] -> [1D or 2D invariant convolutions] -> [bidirectional GRU] -> [fully connected layer] -> [warp-ctc] )

No problem with:
> [bidirectional GRU] -> [fully connected layer] -> [warp-ctc]

But I have no idea how to add CNN layer.

Docs says:
> img_conv_layer - Convolution layer for image. Paddle only support square input currently and thus input image’s width equals height.

I am providing data as:
> settings.input_types = [dense_vector_sequence(512)]

Non-square CNN inputs are really not supported or there is some way to load data?

**Comment by qingqing01** [comment]
The develop branch support Non-square input image now.

**Comment by F0REacH** [comment]
@qingqing01 Thanks for the tip. Somehow I've missed pull #409
