### ISSUE TITLE
paddle提供支持python可直接调用的so用于infer流程么？

### ISSUE THREAD

**Issue by g7925836** [PaddlePaddle/Paddle#9440]
背景：
利用paddlepaddle已经离线训练好了model文件，需要在线上用于预测。
线上的集群机器很难安装paddlepaddle的包，请问paddle有没有提供可以直接用于python的so文件用于线上预测呢？

**Comment by ranqiu92** [comment]
如果是 c/c++的话，可以参考 http://www.paddlepaddle.org/docs/develop/documentation/zh/howto/capi/index_cn.html

python 可以直接pip安装，http://www.paddlepaddle.org/docs/develop/documentation/zh/build_and_install/pip_install_cn.html

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开。
