### ISSUE TITLE
paddlepaddle使用dropout层报错

### ISSUE THREAD

**Issue by KaelChen** [PaddlePaddle/Paddle#9441]
```
layer = paddle.layer.dropout(input=layer, dropout_rate=0.5)
```
代码中新增加一行dropout layer，运行时报错，错误信息如下：
F0328 14:41:18.216569 14590 hl_cuda_device.cc:542] Check failed: dynload::curandGenerateUniform(t_resource.gen, dest_d, num) == CURAND_STATUS_SUCCESS (201 vs. 0) 
请问是跟cuda版本有关系么？

**Comment by ranqiu92** [comment]
能贴下完整的代码吗

**Comment by chengduoZH** [comment]
该issue长时间没有更新，暂时先关闭了，如需继续讨论请再打开。
