### ISSUE TITLE
Is there any available parameters initializer in paddle?

### ISSUE THREAD

**Issue by bipedalBit** [PaddlePaddle/Paddle#9451]
I've try code like this:
~~~~{.python}
    def get_param_attr(local_lr, regularization):
        is_static = False
        if local_lr == 0.0:
            is_static = True
        return paddle.attr.ParamAttr(initializer=fluid.initializer.Xavier(),
            learning_rate=local_lr, l2_rate=regularization, is_static=is_static)
    conv = paddle.layer.img_conv(
        param_attr=get_param_attr(1, default_l2regularization),
        ...
        )
~~~~
It comes to the error that a __call__() ask for 3 arguments, 2 given.
I checked the __call__() of Xavier() in the paddle source code and found ```__call__(self, variable, block)```. So I wonder how can I initial parameters correctly?

**Comment by ranqiu92** [comment]
目前  v2版本和fluid 不能混用，对于V2 的话，可以设置对应layer的 param_attr 参数。可以参考 https://github.com/PaddlePaddle/models/blob/develop/conv_seq2seq/model.py#L51 ，如果是设置  initial_mean  和 initial_std 则是高斯分布，如果是设置 initial_min和initial_max 则是对应区间的均匀分布。

**Comment by guoshengCS** [comment]
已经提供答复且较久未更新，这里先行close，如有需要还请reopen。
