### ISSUE TITLE
连续学习/增量学习如何实现

### ISSUE THREAD

**Issue by galgaxygit** [PaddlePaddle/Paddle#9529]
具体定义可见链接。
https://www.jiqizhixin.com/articles/2017-08-11-11

即不断获得了新样本，如何在原有训练模型基础上继续训练？
期望是能够从新样本中获取新知识以及改正以往样本中学到的错误知识。
搜索issue了解到可以from_tar方式初始化模型，但是会损失以往训练结果？

**Comment by JiayiFeng** [comment]
可以把训练完成的模型保存下来，有新的数据来了，载入模型，用新的数据在原基础上继续训练。

**Comment by galgaxygit** [comment]
1.和infer的方式一样吗？即在模型参数初始化时用Parameters.from_tar替换parameters.create(cost)？
2.optimizer类型对效果是否有影响，比如adam_optimizer？

**Comment by JiayiFeng** [comment]
1. 应该是一样的。但如果遇到了错误，可以尝试先parameters.create(cost)一下，再Parameters.from_tar。
2. 因为保存模型并不会保存Adam的高阶优化信息，因此重新载入模型后这些高阶信息就丢失了，可能在开始几个batch中对收敛有影响。

**Comment by Yancey1989** [comment]
由于长时间没有更新的信息，先关闭这个issue了，如有进一步反馈请随时重新打开。
