### ISSUE TITLE
Can't build with CUDA on mac os 10.12.1 -- "nvcc fatal   : Stray '"' character"

### ISSUE THREAD

**Issue by yingliangzh** [PaddlePaddle/Paddle#953]
nvcc fatal   : Stray '"' character
nvcc fatal   : Stray '"' character
nvcc fatal   : Stray '"' character
nvcc fatal   : Stray '"' character
CMake Error at sift_gpu_generated_ProgramCU.cu.o.RelWithDebInfo.cmake:222 (message):
  Error generating
  /Users/yingliang/Projects/MVS/colmap_modified/build_unix/src/ext/SiftGPU/CMakeFiles/sift_gpu.dir//./sift_gpu_generated_ProgramCU.cu.o

CMake Error at pba_generated_ProgramCU.cu.o.RelWithDebInfo.cmake:222 (message):
  Error generating
  /Users/yingliang/Projects/MVS/colmap_modified/build_unix/src/ext/PBA/CMakeFiles/pba.dir//./pba_generated_ProgramCU.cu.o

CMake Error at mvs_cuda_generated_gpu_mat_prng.cu.o.RelWithDebInfo.cmake:218 (message):
  Error generating
  /Users/yingliang/Projects/MVS/colmap_modified/build_unix/src/mvs/CMakeFiles/mvs_cuda.dir//./mvs_cuda_generated_gpu_mat_prng.cu.o

CMake Error at mvs_cuda_generated_patch_match_cuda.cu.o.RelWithDebInfo.cmake:218 (message):
  Error generating
  /Users/yingliang/Projects/MVS/colmap_modified/build_unix/src/mvs/CMakeFiles/mvs_cuda.dir//./mvs_cuda_generated_patch_match_cuda.cu.o

make[2]: *** [src/ext/PBA/CMakeFiles/pba.dir/pba_generated_ProgramCU.cu.o] Error 1
make[2]: *** [src/ext/SiftGPU/CMakeFiles/sift_gpu.dir/sift_gpu_generated_ProgramCU.cu.o] Error 1
make[2]: *** [src/mvs/CMakeFiles/mvs_cuda.dir/mvs_cuda_generated_gpu_mat_prng.cu.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [src/mvs/CMakeFiles/mvs_cuda.dir/mvs_cuda_generated_patch_match_cuda.cu.o] Error 1
[  3%] Built target poisson_recon
make[1]: *** [src/ext/PBA/CMakeFiles/pba.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
make[1]: *** [src/ext/SiftGPU/CMakeFiles/sift_gpu.dir/all] Error 2
nvcc fatal   : Stray '"' character
CMake Error at mvs_cuda_generated_gpu_mat_ref_image.cu.o.RelWithDebInfo.cmake:218 (message):
  Error generating
  /Users/yingliang/Projects/MVS/colmap_modified/build_unix/src/mvs/CMakeFiles/mvs_cuda.dir//./mvs_cuda_generated_gpu_mat_ref_image.cu.o

make[2]: *** [src/mvs/CMakeFiles/mvs_cuda.dir/mvs_cuda_generated_gpu_mat_ref_image.cu.o] Error 1
make[1]: *** [src/mvs/CMakeFiles/mvs_cuda.dir/all] Error 2

**Comment by reyoung** [comment]
It seems that `sift_gpu_generated_ProgramCU.cu` is not part of Paddle.
