### ISSUE TITLE
添加paddle在cudnn v6环境下cudnn convolution对double类型的支持

### ISSUE THREAD

**Issue by ccx0912** [PaddlePaddle/Paddle#954]
在测试paddle的在nvidia tesla P4上运行时，为了尽可能的发挥Pascal架构的优势，需要使用到cudnn v6和cuda 8.0。检查cudnn v5与v6的区别，发现在`paddle/cuda/src/hl_cuda_cudnn.cc`文件中使用的cudnn函数，只有函数`cudnnSetConvolution2dDescriptor`有所修改，cudnn v6后cudnn convolution可以支持double类型，所以函数的输入需要添加一个变量`cudnnDataType_t`变量来指定计算的数据类型，当前的PR #949 中也仅修改了这个函数，而对于cudnn v6中的其他特征并未考虑，如
- 对更多的数据类型的支持（如`CUDNN_DATA_INT8`等）；
- 新添加的函数（如`cudnnReduceTensor`等）；
- 原来enum中添加的新成员；
- 原来结构体中添加的新变量等。

**Comment by reyoung** [comment]
@hedaoyuan Is this issue already fixed?

**Comment by hedaoyuan** [comment]
从PR内容看起来主要是，修改`cudnnSetConvolution2dDescriptor`增加一个`data_type`参数，所以原来cudnn convolution是不支持double类型，cudnn v6后可以支持double类型了，PR主要是在cudnn v6环境下增加double的能力这样是吗？

如果只是修改convolution支持double的话，修改一下ISSUE的描述，当前标题跟内容不是特别相符，我昨天看到PR的标题的时候一开始也没看明白准备写什么。对cudnn v6的其他特性支持可以另外新建一个ISSUE来描述。

**Comment by hedaoyuan** [comment]
另外，我看你的ISSUE描述应该是测试了Tesla P4，CUDNN V6等，如果有一些测试对比的性能数据的话也可以新建ISSUE贴上来。
可以是自己的Benchmark，也可以是基于paddle/benchmark的。

**Comment by fayeshine** [comment]
@ccx0912 cudnn v6是在哪出现的？
