### ISSUE TITLE
paddle training hold

### ISSUE THREAD

**Issue by chengxiaohua1105** [PaddlePaddle/Paddle#9554]
This is my job:
http://10.89.142.11:8900/fileview.html?path=/home/disk1/normandy/maybach/app-user-20180401223440-24958/

But it holds for 3hours,  I want to know the reason.

**Comment by chengxiaohua1105** [comment]
已经在机器学习用户服务台提交issue，请INF的同学看过了，他们认为是paddle那里处理有问题。所以请教paddle的同学，这是个什么问题？

**Comment by chengxiaohua1105** [comment]
smart链接地址：

http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20180401223440-24958&submitTime=2018-04-01%2022:34:40

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/38183471-2d8f5406-3673-11e8-8f2c-59c4725a0662.png)

感觉这个是mpi执行的hang吧
http://10.89.142.11:8900/filetree?action=cat&path=/home/disk1/normandy/maybach/app-user-20180401223440-24958/log/task_main.log

最经济的方式是，重新起个任务试试，也可以起个小的任务看看能不能执行。

**Comment by chengxiaohua1105** [comment]
我重新起了一个小任务，可以训练出结果。基本上可以定位问题是单个节点处理的数据量太大，训练不过来。
我的训练数据一共是一个T的数据，目前使用了25个MPI节点来训练。推荐使用多少MPI节点比较合适？

**Comment by Superjomn** [comment]
感觉CPU集群的话60~80左右就可以了，再大收益不明显而且碰到慢节点概率很大；数据太大可能没跑完就收敛了。

**Comment by chengxiaohua1105** [comment]
"碰到慢节点"引起的原因是什么？

**Comment by Superjomn** [comment]
MPI集群总有一定量的慢节点。 现在paddle的batch是全局同步，因此速度决定于最慢的节点。

你那个问题可能因为hdfs的hang。

**Comment by chengxiaohua1105** [comment]
如果是因为hdfs的hang，那是不是说我使用再多的mpi节点都没有办法训练呢？

**Comment by chengxiaohua1105** [comment]
我现在开了80个节点，在如下代码加上了log：
114     def event_handler(event):
115         print "enter event handler"
116         if isinstance(event, paddle.event.EndIteration):
117             print "enter event handler first stage"
118             if event.batch_id == 0 and event.pass_id != 0:
120                 print "begin to print pass cost auc"
121                 result = trainer.test(
122                     paddle.batch(
123                         cluster_reader_cluster("./test_data_dir/", node_id), batch_size))
124                 print "Pass %d, Batch %d, Batch size %d, Cost %f, %s, Testing metrics %s" % (
125                     event.pass_id, event.batch_id, batch_size, event.cost, event.metrics,
126                     result.metrics)

发现一直在刷"enter event handler"    以及" enter event handler first stage" 这两个日志信息就是没有看见cost 和auc的信息

**Comment by chengxiaohua1105** [comment]
我现在开了80个节点，在如下代码加上了log：
114     def event_handler(event):
115         print "enter event handler"
116         if isinstance(event, paddle.event.EndIteration):
117             print "enter event handler first stage"
118             if event.batch_id == 0 and event.pass_id != 0:
120                 print "begin to print pass cost auc"
121                 result = trainer.test(
122                     paddle.batch(
123                         cluster_reader_cluster("./test_data_dir/", node_id), batch_size))
124                 print "Pass %d, Batch %d, Batch size %d, Cost %f, %s, Testing metrics %s" % (
125                     event.pass_id, event.batch_id, batch_size, event.cost, event.metrics,
126                     result.metrics)

发现一直在刷"enter event handler"    以及" enter event handler first stage" 这两个日志信息就是没有看见cost 和auc的信息
这个是smart链接地址：
http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20180402135040-25449

**Comment by chengxiaohua1105** [comment]
这个是smart 的链接：
http://yq01-hpc-lvliang-mon.dmop.baidu.com:8919/taskinfo.html?appId=app-user-20180402135040-25449

**Comment by Superjomn** [comment]
![image](https://user-images.githubusercontent.com/328693/38189638-a9400300-3693-11e8-8131-359b0a977604.png)

这个会频繁调用，print影响性能 。 

没有进去说明一个batch还没好， 这个逻辑不需要集群测试，单机就可以测试了。

**Comment by chengxiaohua1105** [comment]
--test_data_path "/app/ecom/fcr-model/liugang06/chengxiaohua/relevance_model/train_data/20180327/whole_network_test"

**Comment by chengxiaohua1105** [comment]
测试样本放在这个目录，比如我开启了10个节点训练。是所有测试数据都要下载到每一个节点，还是测试数据平分到每一个节点？

**Comment by Superjomn** [comment]
Done.
