### ISSUE TITLE
Which pass should I select?

### ISSUE THREAD

**Issue by thomaslwang** [PaddlePaddle/Paddle#9557]
Hello Paddle guys,
I trained 100 passes, got following precision recall eval results.
At around pass 40, precision has a peak, and then keep growing to pass 99.
Do you think this is a normal result? which one should I select, pass 40 or pass 99, considering overfitting?
Pass=0 Batch=713 samples=91139 AvgCost=0.263164 Eval: positive_label=1 precision=0.837905 recall=0.886698 F1-score=0.861611 
Pass=1 Batch=713 samples=91139 AvgCost=0.137665 Eval: positive_label=1 precision=0.91924 recall=0.945237 F1-score=0.932057 
Pass=2 Batch=713 samples=91139 AvgCost=0.11886 Eval: positive_label=1 precision=0.931736 recall=0.953054 F1-score=0.942275 
Pass=3 Batch=713 samples=91139 AvgCost=0.105056 Eval: positive_label=1 precision=0.940107 recall=0.960213 F1-score=0.950053 
Pass=4 Batch=713 samples=91139 AvgCost=0.0960731 Eval: positive_label=1 precision=0.946862 recall=0.963287 F1-score=0.955004 
Pass=5 Batch=713 samples=91139 AvgCost=0.0917989 Eval: positive_label=1 precision=0.949862 recall=0.965922 F1-score=0.957824 
Pass=6 Batch=713 samples=91139 AvgCost=0.0852514 Eval: positive_label=1 precision=0.953199 recall=0.967766 F1-score=0.960427 
Pass=7 Batch=713 samples=91139 AvgCost=0.0800915 Eval: positive_label=1 precision=0.956128 recall=0.969523 F1-score=0.962779 
Pass=8 Batch=713 samples=91139 AvgCost=0.0784995 Eval: positive_label=1 precision=0.955581 recall=0.971191 F1-score=0.963323 
Pass=9 Batch=713 samples=91139 AvgCost=0.0757114 Eval: positive_label=1 precision=0.958357 recall=0.971235 F1-score=0.964753 
Pass=10 Batch=713 samples=91139 AvgCost=0.0711739 Eval: positive_label=1 precision=0.96047 recall=0.973124 F1-score=0.966755 
Pass=11 Batch=713 samples=91139 AvgCost=0.0692104 Eval: positive_label=1 precision=0.961812 recall=0.974441 F1-score=0.968085 
Pass=12 Batch=713 samples=91139 AvgCost=0.0661699 Eval: positive_label=1 precision=0.963955 recall=0.974792 F1-score=0.969344 
Pass=13 Batch=713 samples=91139 AvgCost=0.063795 Eval: positive_label=1 precision=0.965394 recall=0.976417 F1-score=0.970875 
Pass=14 Batch=713 samples=91139 AvgCost=0.0667709 Eval: positive_label=1 precision=0.963738 recall=0.973387 F1-score=0.968538 
Pass=15 Batch=713 samples=91139 AvgCost=0.060641 Eval: positive_label=1 precision=0.968018 recall=0.976988 F1-score=0.972483 
Pass=16 Batch=713 samples=91139 AvgCost=0.0585774 Eval: positive_label=1 precision=0.969166 recall=0.977296 F1-score=0.973214 
Pass=17 Batch=713 samples=91139 AvgCost=0.0570084 Eval: positive_label=1 precision=0.971036 recall=0.977603 F1-score=0.974308 
Pass=18 Batch=713 samples=91139 AvgCost=0.0569759 Eval: positive_label=1 precision=0.970762 recall=0.9769 F1-score=0.973821 
Pass=19 Batch=713 samples=91139 AvgCost=0.0531924 Eval: positive_label=1 precision=0.972369 recall=0.979799 F1-score=0.97607 
Pass=20 Batch=713 samples=91139 AvgCost=0.0538682 Eval: positive_label=1 precision=0.972282 recall=0.979711 F1-score=0.975982 
Pass=21 Batch=713 samples=91139 AvgCost=0.0537124 Eval: positive_label=1 precision=0.970261 recall=0.980018 F1-score=0.975115 
Pass=22 Batch=713 samples=91139 AvgCost=0.0511401 Eval: positive_label=1 precision=0.97422 recall=0.980809 F1-score=0.977504 
Pass=23 Batch=713 samples=91139 AvgCost=0.0516373 Eval: positive_label=1 precision=0.972869 recall=0.981072 F1-score=0.976954 
Pass=24 Batch=713 samples=91139 AvgCost=0.050488 Eval: positive_label=1 precision=0.974014 recall=0.981029 F1-score=0.977508 
Pass=25 Batch=713 samples=91139 AvgCost=0.0512133 Eval: positive_label=1 precision=0.974737 recall=0.981072 F1-score=0.977895 
Pass=26 Batch=713 samples=91139 AvgCost=0.0481349 Eval: positive_label=1 precision=0.976153 recall=0.981512 F1-score=0.978825 
Pass=27 Batch=713 samples=91139 AvgCost=0.0534168 Eval: positive_label=1 precision=0.972549 recall=0.980194 F1-score=0.976357 
Pass=28 Batch=713 samples=91139 AvgCost=0.0455856 Eval: positive_label=1 precision=0.976643 recall=0.98239 F1-score=0.979508 
Pass=29 Batch=713 samples=91139 AvgCost=0.0454446 Eval: positive_label=1 precision=0.977053 recall=0.983532 F1-score=0.980281 
Pass=30 Batch=713 samples=91139 AvgCost=0.0461332 Eval: positive_label=1 precision=0.976731 recall=0.982522 F1-score=0.979618 
Pass=31 Batch=713 samples=91139 AvgCost=0.0435544 Eval: positive_label=1 precision=0.978507 recall=0.983663 F1-score=0.981078 
Pass=32 Batch=713 samples=91139 AvgCost=0.04415 Eval: positive_label=1 precision=0.977768 recall=0.983093 F1-score=0.980423 
Pass=33 Batch=713 samples=91139 AvgCost=0.0432586 Eval: positive_label=1 precision=0.97779 recall=0.984103 F1-score=0.980936 
Pass=34 Batch=713 samples=91139 AvgCost=0.0428702 Eval: positive_label=1 precision=0.977877 recall=0.984147 F1-score=0.981002 
Pass=35 Batch=713 samples=91139 AvgCost=0.0412653 Eval: positive_label=1 precision=0.979071 recall=0.984059 F1-score=0.981559 
Pass=36 Batch=713 samples=91139 AvgCost=0.0408749 Eval: positive_label=1 precision=0.97989 recall=0.984322 F1-score=0.982101 
Pass=37 Batch=713 samples=91139 AvgCost=0.0500506 Eval: positive_label=1 precision=0.974869 recall=0.981248 F1-score=0.978048 
Pass=38 Batch=713 samples=91139 AvgCost=0.0400834 Eval: positive_label=1 precision=0.980231 recall=0.984234 F1-score=0.982229 
Pass=39 Batch=713 samples=91139 AvgCost=0.0395061 Eval: positive_label=1 precision=0.980782 recall=0.986123 F1-score=0.983445 
Pass=40 Batch=713 samples=91139 AvgCost=0.0391227 Eval: positive_label=1 precision=0.981579 recall=0.985157 F1-score=0.983364 
Pass=41 Batch=713 samples=91139 AvgCost=0.0383267 Eval: positive_label=1 precision=0.981564 recall=0.986694 F1-score=0.984122 
Pass=42 Batch=713 samples=91139 AvgCost=0.0378651 Eval: positive_label=1 precision=0.980583 recall=0.986913 F1-score=0.983738 
Pass=43 Batch=713 samples=91139 AvgCost=0.0419349 Eval: positive_label=1 precision=0.979835 recall=0.983707 F1-score=0.981767 
Pass=44 Batch=713 samples=91139 AvgCost=0.0549565 Eval: positive_label=1 precision=0.975264 recall=0.980018 F1-score=0.977636 
Pass=45 Batch=713 samples=91139 AvgCost=0.0366582 Eval: positive_label=1 precision=0.982667 recall=0.985947 F1-score=0.984304 
Pass=46 Batch=713 samples=91139 AvgCost=0.0369084 Eval: positive_label=1 precision=0.981986 recall=0.986298 F1-score=0.984137 
Pass=47 Batch=713 samples=91139 AvgCost=0.0358985 Eval: positive_label=1 precision=0.982983 recall=0.986781 F1-score=0.984878 
Pass=48 Batch=713 samples=91139 AvgCost=0.0344006 Eval: positive_label=1 precision=0.98425 recall=0.987967 F1-score=0.986105 
Pass=49 Batch=713 samples=91139 AvgCost=0.0349393 Eval: positive_label=1 precision=0.98342 recall=0.987221 F1-score=0.985317 
Pass=50 Batch=713 samples=91139 AvgCost=0.0337242 Eval: positive_label=1 precision=0.984791 recall=0.986694 F1-score=0.985741 
Pass=51 Batch=713 samples=91139 AvgCost=0.0344647 Eval: positive_label=1 precision=0.983718 recall=0.987045 F1-score=0.985379 
Pass=52 Batch=713 samples=91139 AvgCost=0.0347597 Eval: positive_label=1 precision=0.983295 recall=0.98744 F1-score=0.985363 
Pass=53 Batch=713 samples=91139 AvgCost=0.034347 Eval: positive_label=1 precision=0.983206 recall=0.987265 F1-score=0.985231 
Pass=54 Batch=713 samples=91139 AvgCost=0.0357834 Eval: positive_label=1 precision=0.982597 recall=0.986869 F1-score=0.984729 
Pass=55 Batch=713 samples=91139 AvgCost=0.0346443 Eval: positive_label=1 precision=0.98286 recall=0.987177 F1-score=0.985014 
Pass=56 Batch=713 samples=91139 AvgCost=0.0358372 Eval: positive_label=1 precision=0.983507 recall=0.987265 F1-score=0.985382 
Pass=57 Batch=713 samples=91139 AvgCost=0.0347743 Eval: positive_label=1 precision=0.983454 recall=0.98665 F1-score=0.985049 
Pass=58 Batch=713 samples=91139 AvgCost=0.0330111 Eval: positive_label=1 precision=0.984363 recall=0.986957 F1-score=0.985659 
Pass=59 Batch=713 samples=91139 AvgCost=0.0333704 Eval: positive_label=1 precision=0.984239 recall=0.987265 F1-score=0.985749 
Pass=60 Batch=713 samples=91139 AvgCost=0.0315848 Eval: positive_label=1 precision=0.985207 recall=0.988582 F1-score=0.986892 
Pass=61 Batch=713 samples=91139 AvgCost=0.0309416 Eval: positive_label=1 precision=0.98478 recall=0.988802 F1-score=0.986786 
Pass=62 Batch=713 samples=91139 AvgCost=0.0456973 Eval: positive_label=1 precision=0.980159 recall=0.984937 F1-score=0.982542 
Pass=63 Batch=713 samples=91139 AvgCost=0.0308444 Eval: positive_label=1 precision=0.985475 recall=0.989197 F1-score=0.987332 
Pass=64 Batch=713 samples=91139 AvgCost=0.030668 Eval: positive_label=1 precision=0.98522 recall=0.98946 F1-score=0.987336 
Pass=65 Batch=713 samples=91139 AvgCost=0.0354116 Eval: positive_label=1 precision=0.983334 recall=0.987221 F1-score=0.985273 
Pass=66 Batch=713 samples=91139 AvgCost=0.0307266 Eval: positive_label=1 precision=0.985819 recall=0.989153 F1-score=0.987483 
Pass=67 Batch=713 samples=91139 AvgCost=0.0295276 Eval: positive_label=1 precision=0.986469 recall=0.989285 F1-score=0.987875 
Pass=68 Batch=713 samples=91139 AvgCost=0.0298612 Eval: positive_label=1 precision=0.986469 recall=0.989329 F1-score=0.987897 
Pass=69 Batch=713 samples=91139 AvgCost=0.0304649 Eval: positive_label=1 precision=0.986112 recall=0.988494 F1-score=0.987302 
Pass=70 Batch=713 samples=91139 AvgCost=0.02883 Eval: positive_label=1 precision=0.986951 recall=0.989812 F1-score=0.988379 
Pass=71 Batch=713 samples=91139 AvgCost=0.0287142 Eval: positive_label=1 precision=0.987072 recall=0.989153 F1-score=0.988111 
Pass=72 Batch=713 samples=91139 AvgCost=0.0290804 Eval: positive_label=1 precision=0.987198 recall=0.988845 F1-score=0.988021 
Pass=73 Batch=713 samples=91139 AvgCost=0.0293104 Eval: positive_label=1 precision=0.98607 recall=0.988538 F1-score=0.987302 
Pass=74 Batch=713 samples=91139 AvgCost=0.0282465 Eval: positive_label=1 precision=0.986863 recall=0.989724 F1-score=0.988292 
Pass=75 Batch=713 samples=91139 AvgCost=0.0286141 Eval: positive_label=1 precision=0.986566 recall=0.990075 F1-score=0.988317 
Pass=76 Batch=713 samples=91139 AvgCost=0.0277184 Eval: positive_label=1 precision=0.988251 recall=0.989943 F1-score=0.989096 
Pass=77 Batch=713 samples=91139 AvgCost=0.0278449 Eval: positive_label=1 precision=0.987422 recall=0.98946 F1-score=0.98844 
Pass=78 Batch=713 samples=91139 AvgCost=0.0274254 Eval: positive_label=1 precision=0.988119 recall=0.989768 F1-score=0.988943 
Pass=79 Batch=713 samples=91139 AvgCost=0.0272782 Eval: positive_label=1 precision=0.988469 recall=0.990075 F1-score=0.989271 
Pass=80 Batch=713 samples=91139 AvgCost=0.0297284 Eval: positive_label=1 precision=0.987029 recall=0.989153 F1-score=0.98809 
Pass=81 Batch=713 samples=91139 AvgCost=0.0270535 Eval: positive_label=1 precision=0.988298 recall=0.990251 F1-score=0.989273 
Pass=82 Batch=713 samples=91139 AvgCost=0.0283747 Eval: positive_label=1 precision=0.986956 recall=0.990207 F1-score=0.988579 
Pass=83 Batch=713 samples=91139 AvgCost=0.0267555 Eval: positive_label=1 precision=0.988862 recall=0.990295 F1-score=0.989578 
Pass=84 Batch=713 samples=91139 AvgCost=0.0264321 Eval: positive_label=1 precision=0.987387 recall=0.990119 F1-score=0.988751 
Pass=85 Batch=713 samples=91139 AvgCost=0.025699 Eval: positive_label=1 precision=0.988788 recall=0.99148 F1-score=0.990132 
Pass=86 Batch=713 samples=91139 AvgCost=0.0262653 Eval: positive_label=1 precision=0.988865 recall=0.990558 F1-score=0.989711 
Pass=87 Batch=713 samples=91139 AvgCost=0.0253771 Eval: positive_label=1 precision=0.989039 recall=0.990646 F1-score=0.989842 
Pass=88 Batch=713 samples=91139 AvgCost=0.0272678 Eval: positive_label=1 precision=0.988512 recall=0.990075 F1-score=0.989293 
Pass=89 Batch=713 samples=91139 AvgCost=0.0250211 Eval: positive_label=1 precision=0.989695 recall=0.991173 F1-score=0.990434 
Pass=90 Batch=713 samples=91139 AvgCost=0.0259562 Eval: positive_label=1 precision=0.989558 recall=0.990514 F1-score=0.990036 
Pass=91 Batch=713 samples=91139 AvgCost=0.0253452 Eval: positive_label=1 precision=0.989038 recall=0.990558 F1-score=0.989797 
Pass=92 Batch=713 samples=91139 AvgCost=0.0255414 Eval: positive_label=1 precision=0.988659 recall=0.991568 F1-score=0.990112 
Pass=93 Batch=713 samples=91139 AvgCost=0.0253555 Eval: positive_label=1 precision=0.989049 recall=0.991612 F1-score=0.990329 
Pass=94 Batch=713 samples=91139 AvgCost=0.0252529 Eval: positive_label=1 precision=0.989222 recall=0.991524 F1-score=0.990372 
Pass=95 Batch=713 samples=91139 AvgCost=0.0248823 Eval: positive_label=1 precision=0.988962 recall=0.991568 F1-score=0.990264 
Pass=96 Batch=713 samples=91139 AvgCost=0.0242352 Eval: positive_label=1 precision=0.98988 recall=0.992271 F1-score=0.991074 
Pass=97 Batch=713 samples=91139 AvgCost=0.024469 Eval: positive_label=1 precision=0.989444 recall=0.992051 F1-score=0.990746 
Pass=98 Batch=713 samples=91139 AvgCost=0.0248666 Eval: positive_label=1 precision=0.98896 recall=0.991393 F1-score=0.990175

**Comment by Superjomn** [comment]
It seems normal, jumped out of local maximum.
