### ISSUE TITLE
Evaluate the perfermace of fluid inference

### ISSUE THREAD

**Issue by mzchtx** [PaddlePaddle/Paddle#9562]
### 1. Description

This issue evaluates the perfermance of fluid inference. For evaluation, I pick 3 models, ResNet50, SE-ResNeXt50 and MobileNet-SSD, which can be found [here](https://github.com/PaddlePaddle/models/tree/develop/fluid). I also randomly select 50000 images from imagenet dataset for testing. Besides, all of the evaluations are runing on a single P4 GPU.

Some other details are as follows：
+ System: Centos 6.3
+ Paddle: 5271c32d2476a51bc6be906862c7cf6ec9597e76
+ CUDA: 8.0
+ CUDNN: v7

### 2. Average Latency(ms)

The latency does not contain the time costed by images preprocessing.

#### paddle

| batch-size    | 1       | 2       | 4       | 8      | 16     | 32     |
|---------------|---------|---------|---------|--------|--------|--------|
| resnet50      | 10.8819 | 7.3180  | 5.7559  | 5.0179 | 4.6569 | 4.7132 |
| se-resnext50  | 26.6772 | 16.5596 | 11.3949 | 9.2108 | 7.7693 |        |
| mobilenet-ssd | 10.9310 | 7.9588  | 6.5468  | 5.4529 | 4.9165 | 5.5263 |

#### tensorrt

| batch-size    | 1       | 2       | 4       | 8      | 16     | 32     |64     |
|---------------|---------|---------|---------|--------|--------|--------|--------|
| resnet50      | 4.91313 | 3.51293  | 3.43974  | 3.09247 | 2.67418 | 2.39979 |2.28533 |

### 3. Latency Profiling

The latency profiling report shows as follow: the most time-consuming part within paddle is conv2d.

#### paddle

```
------------------------->     Profiling Report     <-------------------------

Place: CUDA
Time unit: ms
Sorted by event first end time in descending order in the same thread

Event                        Calls       Total       Min.        Max.        Ave.
thread18::init_program       1           0.006208    0.006208    0.006208    0.006208
thread18::feed               1           0.142464    0.142464    0.142464    0.142464
thread18::conv2d             53          8.01661     0.041984    0.38912     0.151257
thread18::elementwise_add    70          1.4817      0.00512     0.075776    0.0211671
thread18::batch_norm         53          1.12963     0.011264    0.060416    0.0213138
thread18::relu               49          0.624544    0.004096    0.050176    0.0127458
thread18::pool2d             2           0.074752    0.019456    0.055296    0.037376
thread18::mul                1           0.077824    0.077824    0.077824    0.077824
thread18::softmax            1           0.033792    0.033792    0.033792    0.033792
thread18::fetch              1           0.023072    0.023072    0.023072    0.023072
```

#### tensorrt

```
I0320 15:35:37.995844  9865 tensorrt_util.cpp:83] layer_name: conv1 + conv1_relu                          total_used:     0.140 ms  avg_used:   0.140 ms  run_times:   1
I0320 15:35:37.995860  9865 tensorrt_util.cpp:83] layer_name: pool1                                       total_used:     0.041 ms  avg_used:   0.041 ms  run_times:   1
I0320 15:35:37.995868  9865 tensorrt_util.cpp:83] layer_name: res2a_branch1                               total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.995877  9865 tensorrt_util.cpp:83] layer_name: res2a_branch2a + res2a_branch2a_relu        total_used:     0.036 ms  avg_used:   0.036 ms  run_times:   1
I0320 15:35:37.995883  9865 tensorrt_util.cpp:83] layer_name: res2a_branch2b + res2a_branch2b_relu        total_used:     0.068 ms  avg_used:   0.068 ms  run_times:   1
I0320 15:35:37.995890  9865 tensorrt_util.cpp:83] layer_name: res2a_branch2c + res2a + res2a_relu         total_used:     0.093 ms  avg_used:   0.093 ms  run_times:   1
I0320 15:35:37.995898  9865 tensorrt_util.cpp:83] layer_name: res2b_branch2a + res2b_branch2a_relu        total_used:     0.071 ms  avg_used:   0.071 ms  run_times:   1
I0320 15:35:37.995905  9865 tensorrt_util.cpp:83] layer_name: res2b_branch2b + res2b_branch2b_relu        total_used:     0.068 ms  avg_used:   0.068 ms  run_times:   1
I0320 15:35:37.995913  9865 tensorrt_util.cpp:83] layer_name: res2b_branch2c + res2b + res2b_relu         total_used:     0.094 ms  avg_used:   0.094 ms  run_times:   1
I0320 15:35:37.995920  9865 tensorrt_util.cpp:83] layer_name: res2c_branch2a + res2c_branch2a_relu        total_used:     0.072 ms  avg_used:   0.072 ms  run_times:   1
I0320 15:35:37.995928  9865 tensorrt_util.cpp:83] layer_name: res2c_branch2b + res2c_branch2b_relu        total_used:     0.067 ms  avg_used:   0.067 ms  run_times:   1
I0320 15:35:37.995934  9865 tensorrt_util.cpp:83] layer_name: res2c_branch2c + res2c + res2c_relu         total_used:     0.094 ms  avg_used:   0.094 ms  run_times:   1
I0320 15:35:37.995942  9865 tensorrt_util.cpp:83] layer_name: res3a_branch1                               total_used:     0.093 ms  avg_used:   0.093 ms  run_times:   1
I0320 15:35:37.995950  9865 tensorrt_util.cpp:83] layer_name: res3a_branch2a + res3a_branch2a_relu        total_used:     0.069 ms  avg_used:   0.069 ms  run_times:   1
I0320 15:35:37.995957  9865 tensorrt_util.cpp:83] layer_name: res3a_branch2b + res3a_branch2b_relu        total_used:     0.072 ms  avg_used:   0.072 ms  run_times:   1
I0320 15:35:37.995965  9865 tensorrt_util.cpp:83] layer_name: res3a_branch2c + res3a + res3a_relu         total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.995972  9865 tensorrt_util.cpp:83] layer_name: res3b_branch2a + res3b_branch2a_relu        total_used:     0.079 ms  avg_used:   0.079 ms  run_times:   1
I0320 15:35:37.995980  9865 tensorrt_util.cpp:83] layer_name: res3b_branch2b + res3b_branch2b_relu        total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.995987  9865 tensorrt_util.cpp:83] layer_name: res3b_branch2c + res3b + res3b_relu         total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.995995  9865 tensorrt_util.cpp:83] layer_name: res3c_branch2a + res3c_branch2a_relu        total_used:     0.075 ms  avg_used:   0.075 ms  run_times:   1
I0320 15:35:37.996001  9865 tensorrt_util.cpp:83] layer_name: res3c_branch2b + res3c_branch2b_relu        total_used:     0.072 ms  avg_used:   0.072 ms  run_times:   1
I0320 15:35:37.996008  9865 tensorrt_util.cpp:83] layer_name: res3c_branch2c + res3c + res3c_relu         total_used:     0.072 ms  avg_used:   0.072 ms  run_times:   1
I0320 15:35:37.996016  9865 tensorrt_util.cpp:83] layer_name: res3d_branch2a + res3d_branch2a_relu        total_used:     0.076 ms  avg_used:   0.076 ms  run_times:   1
I0320 15:35:37.996022  9865 tensorrt_util.cpp:83] layer_name: res3d_branch2b + res3d_branch2b_relu        total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.996029  9865 tensorrt_util.cpp:83] layer_name: res3d_branch2c + res3d + res3d_relu         total_used:     0.073 ms  avg_used:   0.073 ms  run_times:   1
I0320 15:35:37.996037  9865 tensorrt_util.cpp:83] layer_name: res4a_branch1                               total_used:     0.125 ms  avg_used:   0.125 ms  run_times:   1
I0320 15:35:37.996044  9865 tensorrt_util.cpp:83] layer_name: res4a_branch2a + res4a_branch2a_relu        total_used:     0.099 ms  avg_used:   0.099 ms  run_times:   1
I0320 15:35:37.996052  9865 tensorrt_util.cpp:83] layer_name: res4a_branch2b + res4a_branch2b_relu        total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.996058  9865 tensorrt_util.cpp:83] layer_name: res4a_branch2c + res4a + res4a_relu         total_used:     0.079 ms  avg_used:   0.079 ms  run_times:   1
I0320 15:35:37.996067  9865 tensorrt_util.cpp:83] layer_name: res4b_branch2a + res4b_branch2a_relu        total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.996073  9865 tensorrt_util.cpp:83] layer_name: res4b_branch2b + res4b_branch2b_relu        total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997318  9865 tensorrt_util.cpp:83] layer_name: res4b_branch2c + res4b + res4b_relu         total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997324  9865 tensorrt_util.cpp:83] layer_name: res4c_branch2a + res4c_branch2a_relu        total_used:     0.078 ms  avg_used:   0.078 ms  run_times:   1
I0320 15:35:37.997331  9865 tensorrt_util.cpp:83] layer_name: res4c_branch2b + res4c_branch2b_relu        total_used:     0.081 ms  avg_used:   0.081 ms  run_times:   1
I0320 15:35:37.997339  9865 tensorrt_util.cpp:83] layer_name: res4c_branch2c + res4c + res4c_relu         total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997344  9865 tensorrt_util.cpp:83] layer_name: res4d_branch2a + res4d_branch2a_relu        total_used:     0.077 ms  avg_used:   0.077 ms  run_times:   1
I0320 15:35:37.997351  9865 tensorrt_util.cpp:83] layer_name: res4d_branch2b + res4d_branch2b_relu        total_used:     0.081 ms  avg_used:   0.081 ms  run_times:   1
I0320 15:35:37.997360  9865 tensorrt_util.cpp:83] layer_name: res4d_branch2c + res4d + res4d_relu         total_used:     0.082 ms  avg_used:   0.082 ms  run_times:   1
I0320 15:35:37.997367  9865 tensorrt_util.cpp:83] layer_name: res4e_branch2a + res4e_branch2a_relu        total_used:     0.075 ms  avg_used:   0.075 ms  run_times:   1
I0320 15:35:37.997375  9865 tensorrt_util.cpp:83] layer_name: res4e_branch2b + res4e_branch2b_relu        total_used:     0.081 ms  avg_used:   0.081 ms  run_times:   1
I0320 15:35:37.997381  9865 tensorrt_util.cpp:83] layer_name: res4e_branch2c + res4e + res4e_relu         total_used:     0.083 ms  avg_used:   0.083 ms  run_times:   1
I0320 15:35:37.997388  9865 tensorrt_util.cpp:83] layer_name: res4f_branch2a + res4f_branch2a_relu        total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997395  9865 tensorrt_util.cpp:83] layer_name: res4f_branch2b + res4f_branch2b_relu        total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997401  9865 tensorrt_util.cpp:83] layer_name: res4f_branch2c + res4f + res4f_relu         total_used:     0.080 ms  avg_used:   0.080 ms  run_times:   1
I0320 15:35:37.997408  9865 tensorrt_util.cpp:83] layer_name: res5a_branch1                               total_used:     0.250 ms  avg_used:   0.250 ms  run_times:   1
I0320 15:35:37.997416  9865 tensorrt_util.cpp:83] layer_name: res5a_branch2a + res5a_branch2a_relu        total_used:     0.158 ms  avg_used:   0.158 ms  run_times:   1
I0320 15:35:37.997423  9865 tensorrt_util.cpp:83] layer_name: res5a_branch2b + res5a_branch2b_relu        total_used:     0.132 ms  avg_used:   0.132 ms  run_times:   1
I0320 15:35:37.997431  9865 tensorrt_util.cpp:83] layer_name: res5a_branch2c + res5a + res5a_relu         total_used:     0.137 ms  avg_used:   0.137 ms  run_times:   1
I0320 15:35:37.997437  9865 tensorrt_util.cpp:83] layer_name: res5b_branch2a + res5b_branch2a_relu        total_used:     0.103 ms  avg_used:   0.103 ms  run_times:   1
I0320 15:35:37.997443  9865 tensorrt_util.cpp:83] layer_name: res5b_branch2b + res5b_branch2b_relu        total_used:     0.143 ms  avg_used:   0.143 ms  run_times:   1
I0320 15:35:37.997452  9865 tensorrt_util.cpp:83] layer_name: res5b_branch2c + res5b + res5b_relu         total_used:     0.135 ms  avg_used:   0.135 ms  run_times:   1
I0320 15:35:37.997459  9865 tensorrt_util.cpp:83] layer_name: res5c_branch2a + res5c_branch2a_relu        total_used:     0.100 ms  avg_used:   0.100 ms  run_times:   1
I0320 15:35:37.997467  9865 tensorrt_util.cpp:83] layer_name: res5c_branch2b + res5c_branch2b_relu        total_used:     0.144 ms  avg_used:   0.144 ms  run_times:   1
I0320 15:35:37.997473  9865 tensorrt_util.cpp:83] layer_name: res5c_branch2c + res5c + res5c_relu         total_used:     0.137 ms  avg_used:   0.137 ms  run_times:   1
I0320 15:35:37.997479  9865 tensorrt_util.cpp:83] layer_name: pool5                                       total_used:     0.015 ms  avg_used:   0.015 ms  run_times:   1
I0320 15:35:37.997488  9865 tensorrt_util.cpp:83] layer_name: fc1000                                      total_used:     0.081 ms  avg_used:   0.081 ms  run_times:   1
I0320 15:35:37.997495  9865 tensorrt_util.cpp:83] layer_name: prob                                        total_used:     0.017 ms  avg_used:   0.017 ms  run_times:   1
I0320 15:35:37.997499  9865 tensorrt_util.cpp:87] Time over all layers: 5.01862 ms
```

### 4. QPS

We integrate the fluid inference api into our services, and limit the max batch size. The latency contains the time costed by images preprocessing.

#### ResNet50 batch-size = 1

| QPS                 | 10  | 20   | 30   | 35  |
|---------------------|-----|------|------|-----|
| average latency(ms) | 35  | 35.8 | 56.8 | 110 |
| GPU utilization     | 18% | 31%  | 56%  | 62% |

#### ResNet50 batch-size = 4

| QPS                 | 10 | 20 | 40   | 80   | 100  |
|---------------------|----|----|------|------|------|
| average latency(ms) |    |    | 16.1 | 30.1 | 81.5 |
| GPU utilization     |    |    | 36%  | 54%  | 55%  |

#### ResNet50 batch-size = 8

| QPS                 | 10 | 20 | 40 | 80   | 100  |
|---------------------|----|----|----|------|------|
| average latency(ms) |    |    |    | 29.6 | 37.5 |
| GPU utilization     |    |    |    | 60%  | 60%  |

#### SE-ResNeXt50 batch-size = 1

| QPS                 | 10   | 20  | 30   | 32   |
|---------------------|------|-----|------|------|
| average latency(ms) | 31.3 | 32  | 40.5 | 49.7 |
| GPU utilization     | 25%  | 47% | 72%  | 77%  |

#### SE-ResNeXt50 batch-size = 4

| QPS                 | 10   | 20  | 30   | 40   | 50   | 60   | 65  |
|---------------------|------|-----|------|------|------|------|-----|
| average latency(ms) | 35.1 | 31  | 31.4 | 48.5 | 51.7 | 55.9 | 62  |
| GPU utilization     | 27%  | 48% | 71%  | 83%  | 84%  | 86%  | 86% |

#### SE-ResNeXt50 batch-size = 8

| QPS                 | 10 | 20 | 40   | 70   |
|---------------------|----|----|------|------|
| average latency(ms) |    |    | 48.6 | 67.7 |
| GPU utilization     |    |    | 83%  | 85%  |

#### MobileNet-SSD batch-size = 1

| QPS                 | 10   | 20   | 30  | 40   | 50  |
|---------------------|------|------|-----|------|-----|
| average latency(ms) | 19.2 | 19.5 | 20  | 21.5 | 40  |
| GPU utilization     | 7%   | 14%  | 22% | 29%  | 35% |

#### MobileNet-SSD batch-size = 4

| QPS                 | 10 | 20 | 40  | 60 | 70  | 75  |
|---------------------|----|----|-----|----|-----|-----|
| average latency(ms) |    |    | 19  |    | 40  | 42  |
| GPU utilization     | %  | %  | 29% | %  | 34% | 35% |

#### MobileNet-SSD batch-size = 8

| QPS                 | 10 | 20 | 40  | 60  | 70  | 80  |
|---------------------|----|----|-----|-----|-----|-----|
| average latency(ms) |    |    | 19  | 31  | 39  | 51  |
| GPU utilization     | %  | %  | 29% | 36% | 36% | 35% |

### 5. caffe, mxnet, paddle and tensorrt

We compare the perfermance of ResNet50 with other frameworks, such as caffe, mxnet and tensorrt. The caffe(tensorrt) model can be found [here](https://onedrive.live.com/?authkey=%21AAFW2-FVoxeVRck&id=4006CBB8476FF777%2117887&cid=4006CBB8476FF777), the mxnet model [here](https://mxnet.incubator.apache.org/versions/master/api/python/gluon/model_zoo.html), and the paddle model is converted from caffe model.

Other details as follows:
+ max batch size: 1
+ mxnet version: 1.1.0
+ tensorrt version: 3.0.4

#### caffe

| QPS                 | 10  | 20   | 30   | 35  |
|---------------------|-----|------|------|-----|
| average latency(ms) | 35  | 35.8 | 56.8 | 110 |
| GPU utilization     | 18% | 31%  | 56%  | 62% |

#### mxnet

| QPS                 | 10  | 20  | 40  | 80  | 95  |
|---------------------|-----|-----|-----|-----|-----|
| average latency(ms) | 27  | 28  | 30  | 62  | 103 |
| GPU utilization     | 11% | 21% | 32% | 72% | 81% |

#### Paddle

| QPS                 | 10 | 20   | 30   | 40   | 50   | 58  |
|---------------------|----|------|------|------|------|-----|
| average latency(ms) | 17 | 17.2 | 17.4 | 17.3 | 20.5 | 80  |
| GPU utilization     | 8% | 19%  | 30%  | 38%  | 46%  | 54% |

#### tensorrt

| QPS                 | 10 | 20   | 40   | 80  | 160 | 200 | 220 |
|---------------------|----|------|------|-----|-----|-----|-----|
| average latency(ms) | 20 | 20.7 | 21.3 | 21  | 28  | 50  | 86  |
| GPU utilization     | 6% | 11%  | 21%  | 35% | 69% | 82% | 85% |

### 6. Summary

+ TensorRT improves inference throughput and latency compared to the other frameworks.
 
+ There seems to be a restricted execution that leads to a lower gpu utilization in paddle. I haven't investigated in depth what causes this phenomenon.

**Comment by pangge** [comment]
We integrate the fluid inference api into our **services**, and limit the max batch size. The latency contains the time costed by images preprocessing.

do you mean that the services is  rpc services?

**Comment by mzchtx** [comment]
@pangge Yeah.

**Comment by xwwell** [comment]
@mzchtx Are the reported latency time divided by batch size? Why larger batch size have lower latency, which does not make sense...
