### ISSUE TITLE
场景文字识别使用GPU训练后，怎么在预测的时候不可以用CPU

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#9586]
在场景文字识别的例子中：https://github.com/PaddlePaddle/models/tree/develop/scene_text_recognition
训练是一定要GPU，但是预测是可以不用的，如这个代码：https://github.com/PaddlePaddle/models/blob/9264e8cebb0219a9cd765511b8a7c9236f0b1da8/scene_text_recognition/network_conf.py#L81-L89
但是在真正的实际上，在预测使用CPU是报错：
```
F0403 08:36:29.233067  3738 Allocator.h:54] Check failed: posix_memalign(&ptr, 4096ul, size) == 0 (12 vs. 0) 
*** Check failure stack trace: ***
    @     0x7f2cf5f3e2cd  google::LogMessage::Fail()
    @     0x7f2cf5f40618  google::LogMessage::SendToLog()
    @     0x7f2cf5f3dddb  google::LogMessage::Flush()
    @     0x7f2cf5f414ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f2cf5e9ca91  paddle::PoolAllocator::alloc()
    @     0x7f2cf5e95d25  paddle::CpuMemoryHandle::CpuMemoryHandle()
    @     0x7f2cf5e50c93  paddle::CpuMatrix::CpuMatrix()
    @     0x7f2cf5e50e1e  paddle::Matrix::create()
    @     0x7f2cf5e61518  paddle::Matrix::resizeOrCreate()
    @     0x7f2cf5c49fa7  paddle::Layer::resetSpecifyOutput()
    @     0x7f2cf5c4a212  paddle::Layer::resetOutput()
    @     0x7f2cf5d1b331  paddle::BatchNormalizationLayer::forward()
    @     0x7f2cf5b3fe3f  paddle::NeuralNetwork::forward()
    @     0x7f2cf5ac0d86  _wrap_GradientMachine_forward
    @           0x4bc3fa  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4d4c9d  (unknown)
    @           0x4bc9b6  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4c136f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7f2d1325b830  __libc_start_main
```

**Comment by pkuyym** [comment]
> 但是在真正的实际上，在预测使用CPU是报错：
使用GPU预测是没问题的吗？

**Comment by yeyupiaoling** [comment]
@pkuyym 
没问题的，能正常预测。

**Comment by pkuyym** [comment]
@yeyupiaoling 从log看似乎是内存分配问题，这个问题是稳定复现的吗？能否确认一下内存是否足够？

> F0403 08:36:29.233067  3738 Allocator.h:54] Check failed: posix_memalign(&ptr, 4096ul, size) == 0 (12 vs. 0)

**Comment by yeyupiaoling** [comment]
@pkuyym 
8G的内存，应该足够吧？

**Comment by pkuyym** [comment]
@yeyupiaoling 看log是BN层挂掉了，想问下这个exception是稳定复现的吗？比如当infer的样本数为1时，所有的样本的都infer失败还是？

**Comment by yeyupiaoling** [comment]
@pkuyym 
我把预测的样本设置为一个时，报错如下：
```
F0409 22:03:12.072908 32274 BlockExpandOp.cpp:73] Check failed: seqLength == outputHeight * outputWidth (11 vs. 18446744073709551539) 
*** Check failure stack trace: ***
    @     0x7fe39bc0a2cd  google::LogMessage::Fail()
    @     0x7fe39bc0c618  google::LogMessage::SendToLog()
    @     0x7fe39bc09ddb  google::LogMessage::Flush()
    @     0x7fe39bc0d4ee  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fe39ba111f8  paddle::BlockExpandForward<>::calc()
    @     0x7fe39b8e0200  paddle::BlockExpandLayer::forward()
    @     0x7fe39b80be3f  paddle::NeuralNetwork::forward()
    @     0x7fe39b7fd76c  paddle::TrainerThread::forward()
    @     0x7fe39b8013f8  paddle::TrainerThread::computeThread()
    @     0x7fe3b6c7fc80  (unknown)
    @     0x7fe3b92d86ba  start_thread
    @     0x7fe3b900e41d  clone
    @              (nil)  (unknown)
```

**Comment by yeyupiaoling** [comment]
自我回答，首先出现以下报错：
```
Check failed: seqLength == outputHeight * outputWidth (11 vs. 18446744073709551539)
```
是因为PaddlePaddle版本的问题，在0.10.0是没有问题的，在0.11.0就报这个错误

**Comment by pkuyym** [comment]
看起来是遇到了corner case，导致内存访问出错，```18446744073709551539```这个值明显异常，看log，是BlockExpand Op出错了，能否share一份BlockExpand的input？当然不排除BlockExpand Input本身就有问题，能否协助确认一下？
```
seqLength == outputHeight * outputWidth (11 vs. 18446744073709551539) 
```

**Comment by yeyupiaoling** [comment]
@pkuyym 请问我如何获取这个BlockExpand呢？

**Comment by pkuyym** [comment]
可以在这个函数里面获取到BlockExpand的input，尝试一下把input信息保存到文件里面，然后试着load这个input，看能否稳定复现，这样可以提高debug效率

**Comment by yeyupiaoling** [comment]
@pkuyym 
这个场景文字识别在0.10.0版本正常，在0.11.0就不行了，不知道更新了什么。如果这个模型只能在0.10.0版本下使用，而其他的又是在0.11.0版本，那我要在两条电脑上转两个版本。这样是不是很费劲。
您说在BlockExpand的获取input，这个在python如何操作呢？

**Comment by nemo9903** [comment]
顶一下，因为我是新手，直接用的0.14，一直都报错这个错误。
nemo@1080Ti:~/carplate/downloadimages/project$ python train.py
[INFO 2018-09-07 17:34:53,488 layers.py:2716] output for __conv_0__: c = 16, h = 80, w = 180, size = 230400
[INFO 2018-09-07 17:34:53,488 layers.py:3361] output for __batch_norm_0__: c = 16, h = 80, w = 180, size = 230400
[INFO 2018-09-07 17:34:53,489 layers.py:2716] output for __conv_1__: c = 16, h = 80, w = 180, size = 230400
[INFO 2018-09-07 17:34:53,489 layers.py:3361] output for __batch_norm_1__: c = 16, h = 80, w = 180, size = 230400
[INFO 2018-09-07 17:34:53,490 layers.py:2858] output for __pool_0__: c = 16, h = 40, w = 90, size = 57600
[INFO 2018-09-07 17:34:53,490 layers.py:2716] output for __conv_2__: c = 32, h = 40, w = 90, size = 115200
[INFO 2018-09-07 17:34:53,490 layers.py:3361] output for __batch_norm_2__: c = 32, h = 40, w = 90, size = 115200
[INFO 2018-09-07 17:34:53,491 layers.py:2716] output for __conv_3__: c = 32, h = 40, w = 90, size = 115200
[INFO 2018-09-07 17:34:53,491 layers.py:3361] output for __batch_norm_3__: c = 32, h = 40, w = 90, size = 115200
[INFO 2018-09-07 17:34:53,492 layers.py:2858] output for __pool_1__: c = 32, h = 20, w = 45, size = 28800
[INFO 2018-09-07 17:34:53,492 layers.py:2716] output for __conv_4__: c = 64, h = 20, w = 45, size = 57600
[INFO 2018-09-07 17:34:53,493 layers.py:3361] output for __batch_norm_4__: c = 64, h = 20, w = 45, size = 57600
[INFO 2018-09-07 17:34:53,493 layers.py:2716] output for __conv_5__: c = 64, h = 20, w = 45, size = 57600
[INFO 2018-09-07 17:34:53,493 layers.py:3361] output for __batch_norm_5__: c = 64, h = 20, w = 45, size = 57600
[INFO 2018-09-07 17:34:53,494 layers.py:2858] output for __pool_2__: c = 64, h = 10, w = 23, size = 14720
[INFO 2018-09-07 17:34:53,494 layers.py:2716] output for __conv_6__: c = 128, h = 10, w = 23, size = 29440
[INFO 2018-09-07 17:34:53,495 layers.py:3361] output for __batch_norm_6__: c = 128, h = 10, w = 23, size = 29440
[INFO 2018-09-07 17:34:53,495 layers.py:2716] output for __conv_7__: c = 128, h = 10, w = 23, size = 29440
[INFO 2018-09-07 17:34:53,496 layers.py:3361] output for __batch_norm_7__: c = 128, h = 10, w = 23, size = 29440
[INFO 2018-09-07 17:34:53,496 layers.py:2858] output for __pool_3__: c = 128, h = 5, w = 12, size = 7680
I0907 17:34:53.553309 17721 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1
I0907 17:34:55.091177 17721 GradientMachine.cpp:94] Initing parameters..
I0907 17:34:55.164140 17721 GradientMachine.cpp:101] Init parameters done.
F0907 17:34:55.255237 17721 BlockExpandOp.cpp:73] Check failed: seqLength == outputHeight * outputWidth (12 vs. 18446744073709551556)
*** Check failure stack trace: ***
    @     0x7f44d9a6913d  google::LogMessage::Fail()
    @     0x7f44d9a6cbec  google::LogMessage::SendToLog()
    @     0x7f44d9a68c63  google::LogMessage::Flush()
    @     0x7f44d9a6e0fe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f44d97de0a6  paddle::BlockExpandFunction::getColShape()
    @     0x7f44d97e01a8  paddle::BlockExpandForward<>::calc()
    @     0x7f44d975976f  paddle::BlockExpandLayer::forward()
    @     0x7f44d978405d  paddle::NeuralNetwork::forward()
    @     0x7f44d9776763  paddle::GradientMachine::forwardBackward()
    @     0x7f44d9a44f94  GradientMachine::forwardBackward()
    @     0x7f44d95dabd9  _wrap_GradientMachine_forwardBackward
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7f450d276830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)
已放弃

**Comment by yeyupiaoling** [comment]
@nemo9903 你是修改了什么吧，输入大小好像有问题。

**Comment by nemo9903** [comment]
我是使用车牌识别的例子。我把图片文件名都改成拼音了。先执行CutPlateNumber.py，再执行createDataList.py，再执行image2GRAY.py，再执行train.py。使用paddle 0.14，就是这样。你遇到的问题解决了吗？

**Comment by nemo9903** [comment]
链接：https://pan.baidu.com/s/1J5J433_eqX9T6SccAaCFPA 密码：i1gy
这是代码和已经下载的图片。

**Comment by yeyupiaoling** [comment]
@nemo9903 我项目中有说明是使用那边版本吧，先使用对应版本看看

**Comment by yeyupiaoling** [comment]
@nemo9903 你看看大小有没有设置对，还有图片的裁剪得如何

**Comment by nemo9903** [comment]
你是说用0.10.0版本的paddlepaddle-gpu吗？现在pip已经不能安装了，怎么获得这个版本？
我的图片都是从这个地方获得的，里面有个别图片不能用，我给删除了。因为这里面图片都是你处理过的，我就没有再处理。
https://github.com/yeyupiaoling/LearnPaddle/tree/master/note7/images/src_temp

**Comment by nemo9903** [comment]
@yeyupiaoling  我是新手，at还要学习使用一下。

**Comment by nemo9903** [comment]
@yeyupiaoling  后来你把input参数打印出来了吗？

**Comment by yeyupiaoling** [comment]
@nemo9903 没有呢，不知道如何打印。

**Comment by nemo9903** [comment]
@pkuyym 
是不是需要自己编译paddle,在代码里面增加打印？

**Comment by yeyupiaoling** [comment]
@nemo9903 应该不用。

**Comment by YitianSusan** [comment]
@yeyupiaoling 楼主知道在GPU上跑你git分享的code，train的时候出现如下error的问题是什么吗？paddle是0.10.0 版本。

[INFO 2019-01-04 11:54:22,578 layers.py:2430] output for __conv_0__: c = 16, h = 80, w = 180, size = 230400
[INFO 2019-01-04 11:54:22,580 layers.py:2430] output for __conv_1__: c = 16, h = 80, w = 180, size = 230400
[INFO 2019-01-04 11:54:22,581 layers.py:2555] output for __pool_0__: c = 16, h = 40, w = 90, size = 57600
[INFO 2019-01-04 11:54:22,582 layers.py:2430] output for __conv_2__: c = 32, h = 40, w = 90, size = 115200
[INFO 2019-01-04 11:54:22,584 layers.py:2430] output for __conv_3__: c = 32, h = 40, w = 90, size = 115200
[INFO 2019-01-04 11:54:22,585 layers.py:2555] output for __pool_1__: c = 32, h = 20, w = 45, size = 28800
[INFO 2019-01-04 11:54:22,586 layers.py:2430] output for __conv_4__: c = 64, h = 20, w = 45, size = 57600
[INFO 2019-01-04 11:54:22,588 layers.py:2430] output for __conv_5__: c = 64, h = 20, w = 45, size = 57600
[INFO 2019-01-04 11:54:22,589 layers.py:2555] output for __pool_2__: c = 64, h = 10, w = 23, size = 14720
[INFO 2019-01-04 11:54:22,590 layers.py:2430] output for __conv_6__: c = 128, h = 10, w = 23, size = 29440
[INFO 2019-01-04 11:54:22,592 layers.py:2430] output for __conv_7__: c = 128, h = 10, w = 23, size = 29440
[INFO 2019-01-04 11:54:22,593 layers.py:2555] output for __pool_3__: c = 128, h = 5, w = 12, size = 7680
I0104 11:54:22.620714 24560 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=1 
I0104 11:54:25.615885 24560 GradientMachine.cpp:85] Initing parameters..
I0104 11:54:25.753832 24560 GradientMachine.cpp:92] Init parameters done.
F0104 11:54:26.135999 24560 BlockExpandOp.cpp:73] Check failed: seqLength == outputHeight * outputWidth (12 vs. 18446744073709551556) 
*** Check failure stack trace: ***
    @     0x7f9b4bf718dd  google::LogMessage::Fail()
    @     0x7f9b4bf73c28  google::LogMessage::SendToLog()
    @     0x7f9b4bf713cb  google::LogMessage::Flush()
    @     0x7f9b4bf74afe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f9b4bccecf8  paddle::BlockExpandForward<>::calc()
    @     0x7f9b4bc036c0  paddle::BlockExpandLayer::forward()
    @     0x7f9b4bc204b1  paddle::NeuralNetwork::forward()
    @     0x7f9b4bf415a0  GradientMachine::forwardBackward()
    @     0x7f9b4ba840c4  _wrap_GradientMachine_forwardBackward
    @           0x4c30ce  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c16e7  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4c1e6f  PyEval_EvalFrameEx
    @           0x4b9ab6  PyEval_EvalCodeEx
    @           0x4eb30f  (unknown)
    @           0x4e5422  PyRun_FileExFlags
    @           0x4e3cd6  PyRun_SimpleFileExFlags
    @           0x493ae2  Py_Main
    @     0x7f9b73497830  __libc_start_main
    @           0x4933e9  _start
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by YitianSusan** [comment]
@nemo9903 你是不是没用GPU跑？

**Comment by yeyupiaoling** [comment]
@YitianSusan 之前有出现过，我是使用了PaddlePaddle 0.11.0出现的，换成0.10.0就没问题了

**Comment by YitianSusan** [comment]
@yeyupiaoling 楼主知道如果安装了多个版本的paddle（0.10.0, 0.11.0），怎么在电脑上切换两个版本呢？

**Comment by yeyupiaoling** [comment]
@YitianSusan 可以用Python的虚拟环境：virtualenv
