### ISSUE TITLE
关于mixed layer中的weight参数

### ISSUE THREAD

**Issue by Pinletrot** [PaddlePaddle/Paddle#962]
例如，dotmul_projection的文档中提到了
![image](https://cloud.githubusercontent.com/assets/20688585/21345172/062f38b8-c6da-11e6-9240-931a995c7d02.png)

我有两个问题：
1)这个weight是一个类似于fc_layer中的weights和bias的可以学习的参数吗？
2)这个参数可以读取出来吗？

我想用mixed layer在做一个类似于highway layer的layer，比如
input是 layer1, layer02
output是 activation_func(weight * layer1 + (1 - weight) * layer2)
weight是mixed layer中的可学习的参数，并且在[0, 1]之间。

**Comment by luotao1** [comment]
[interpolation_layer](https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L1401)是否满足你的需求？
