### ISSUE TITLE
paddle latest code failed on CentOS docker.

### ISSUE THREAD

**Issue by Superjomn** [PaddlePaddle/Paddle#9642]
Hi, I compiled the Paddle code on a CentOS docker, but it failed with 

![image](https://user-images.githubusercontent.com/328693/38292532-b0688510-3816-11e8-8180-59fb3f08044c.png)

This docker can compile yesterday‘s code.

The source code's commit is c14305f0f62335c51174b5eafb534b0c5f9dbc33, the docker image is https://hub.docker.com/r/chunweiyan/gpu_agent .

Thank u.

**Comment by luotao1** [comment]
@mozga-intel Can you help fix this issue?

**Comment by Superjomn** [comment]
I set WITH_MKLDNN=OFF, still the same error.

**Comment by mozga-intel** [comment]
Sure I will help. Now I am checking this code on the local machine.

**Comment by luotao1** [comment]
If `WITH_MKLDNN=OFF`, the `fc_mkldnn_op` should not be compiled.

**Comment by mozga-intel** [comment]
@Superjomn How can I reproduce this error ?, because this code works on the local machine also when I ran the unit tests
