### ISSUE TITLE
paddle book里vgg_bn_drop关于BN层参数的问题

### ISSUE THREAD

**Issue by seanxh** [PaddlePaddle/Paddle#9643]
![machi 2018-04-04 14-40-39](https://user-images.githubusercontent.com/5815297/38292391-2d0b7718-3816-11e8-8f34-c4789149d249.png)

对于这个网络https://github.com/PaddlePaddle/book/blob/develop/03.image_classification/vgg.py

img_conv_group这个函数没有找到详细的解释，我理解应该是conv_num_filter个带bn的卷积层，然后接一个MAXPOOL。但我不理解的是，每个bn层，为什么有___batch_norm_0__.w0,w1,w2三个参数呢？

一个32\*32\*3的图像，经过一个有64个3\*3\*3大小的卷积核后，应该输出30\*30\*64大小。其bn层不应该只有两个参数w_0是64的，b_0也是64的吗？

**Comment by qingqing01** [comment]
BN层有4个参数：
- ___batch_norm_0__.w0: 是scale系数。
- ___batch_norm_0__.w1: 是moving mean
- ___batch_norm_0__.w2: 是moving variance
- ___batch_norm_0__.wbias: 是偏移量。
