### ISSUE TITLE
How can i use the data_layer for label whose length is not fixed such mulibox detection label

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#9645]
`label = data_layer(name='label', size=24, height=4, width=6)`

**Comment by qingqing01** [comment]
If in SSD detection,   for the variable-length labels,  you need to use `dense_vector_sequence` as the data type. You can refer https://github.com/PaddlePaddle/models/blob/develop/ssd/vgg_ssd_net.py#L274 .
