### ISSUE TITLE
Can i get slice of the data_layer?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#9646]
data format:
img_path  class_label, x1, y1, x2, y2, class_label2, x3, y3, x4, y4

Can i use the seq_slice_layer to solve it ?

**Comment by qingqing01** [comment]
If this data is generated by Python reader. You can change the data reader to do it. There is no need to use `slice_layer` in config.

**Comment by youngstu** [comment]
Yeah, I know that i can modify the reader.  But i want to change the code less and by the way, i want to know the seq_slice_layer() method whether is ok ?

**Comment by qingqing01** [comment]
You can not used `seq_slice_layer`, you can see the doc: https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L7125

This layer is used to slice the sub-sequences. Can not slice `class_label, x1, y1, x2, y2` to `x1, y1, x2, y2` in this dimension.
