### ISSUE TITLE
detection label format for detection_map_evaluator ?

### ISSUE THREAD

**Issue by youngstu** [PaddlePaddle/Paddle#9647]
what it looks like ?  Is it a fixed format with 6 dims ?

**Comment by qingqing01** [comment]
Yeah, you can refer: https://github.com/PaddlePaddle/models/blob/develop/ssd/data_provider.py#L76

the label layout is: [label_id, xmin, ymin, xmax, ymax, difficult] , `difficult` means whether this bbox is difficult or not.
