### ISSUE TITLE
predict.py找不到py_paddle模块

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#968]
hi,

我运行demo/sentiment中的 predict.sh, 报错找不到py_paddle:
![image](https://cloud.githubusercontent.com/assets/22980558/21352621/4d75dcae-c6fd-11e6-9fe8-ac53df5bc391.png)
请问这个问题应该怎么解决啊？

**Comment by HugoLian** [comment]
补充说明：我的paddle是内部一键编译版本。

**Comment by backyes** [comment]
@HugoLian 

一键编译工具默认会编译py_paddle，所以你的问题也很奇怪， 能否提供一下编译日志中的关键部分，比如cmake 命令参数？ 或者自己查一下./output/python27-gcc48/目录下是否有py_paddle包？  

另外，也确认下， 你是否能用一键编译脚本进行训练呢？

**Comment by HugoLian** [comment]
@backyes 
可以进行训练，相关的目录结构是：
![image](https://cloud.githubusercontent.com/assets/22980558/21376593/242fca48-c771-11e6-81cd-9d4f72db13f6.png)
这里面有你说的py_paddle包么？

cmake命令参数我没动过，就是一键编译的默认参数，或者应该具体查看一下哪些？

**Comment by HugoLian** [comment]
尝试了很多方法，最后通过彻底删除本机上的工程，删除bashrc上paddle相关变量，从新拉取最新git代码，一键编译，然后问题就不再出现了。

**Comment by HugoLian** [comment]
感谢大家的帮助！@王燕飞
