### ISSUE TITLE
Unused argument max_block_size in split_dense_variable()

### ISSUE THREAD

**Issue by emailweixu** [PaddlePaddle/Paddle#9682]
max_block_size is not used in this function:
https://github.com/PaddlePaddle/Paddle/blob/f53beedd13747e9925a523d1a2ffff36e3bb7893/python/paddle/fluid/distribute_transpiler.py#L91-L95

**Comment by typhoonzero** [comment]
This may be related to https://github.com/PaddlePaddle/Paddle/issues/9675. We can reduce the copy of split op and limit the max size of each parameter/gradient block, and send those blocks using an "IOthreadpool" ( which should contain much more threads than machine CPU cores).

And, in earlier tests result https://github.com/PaddlePaddle/Paddle/issues/7944, we see that split copying is not the major time-consuming operator, so we delayed this improvement.
