### ISSUE TITLE
尝试保存变量到文件报错

### ISSUE THREAD

**Issue by lgone2000** [PaddlePaddle/Paddle#9712]
在fluid.layers.tensor 里面找到save函数，不知道下面用法对不对
```
def testsave():
    x = fluid.layers.create_parameter(dtype="float32", shape=[5, 10], name="x")
    exe = fluid.Executor(fluid.CPUPlace())
    exe.run(fluid.default_startup_program())
    fluid.layers.tensor.save(x, 'x.data')
```

**Comment by luotao1** [comment]
请问有什么错误？
可以试试`fluid.io.save_vars(executor=exe, dirname='dir_name', vars=[x])`

**Comment by lgone2000** [comment]
使用 fluid.layers.tensor.save  报错
"/home/vis/liuguoyi01/work/paddlelearn/paddle_easybuild/buildcpu/python/paddle/fluid/framework.py", line 816, in append_op
    op = Operator(block=self, desc=op_desc, *args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'args'

fluid.io.save_vars 测试可以使用
