### ISSUE TITLE
need to install the whl package On CI server

### ISSUE THREAD

**Issue by luotao1** [PaddlePaddle/Paddle#9728]
Today @jacquesqiao  find that the whl package compiled by the latest code  does not contain `core.so`, but the CI can pass because it run test under the build dir. #9721 

Thus, we need to install the whl package On CI server and run some tests for the installed package to ensure the whl package is correct.

**Comment by jshower** [comment]
I meet the same question. use the latest code.  
>> python -c "import paddle.fluid"
```
Warning with import paddle: you should not 
     import paddle from the source directory; please install paddlepaddle*.whl firstly.Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: cannot import name core
```
When this bug is fixed， please tell me here.

**Comment by luotao1** [comment]
@jshower This bug is fixed now, you can use the latest code again.
