### ISSUE TITLE
python import fluid error

### ISSUE THREAD

**Issue by lxy890123** [PaddlePaddle/Paddle#9731]
mac pip安装paddle，import paddle.v2 没有问题，调用init也没有问题，
但是import paddle.v2.fluid 就会出现下面的错误：

>>> import paddle.v2.fluid as fluid
Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6

**Comment by typhoonzero** [comment]
需要使用`brew install python`作为python环境。Paddle发布的mac版本的包是基于brew python编译的。

**Comment by typhoonzero** [comment]
问题解决了么？ @lxy890123
