### ISSUE TITLE
Why use ARCHIVE_START and ARCHIVE_END in Fluid

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9736]
In paddle/fluid/inference/*, there are two uses of `ARCHIVE_START` and `ARCHIVE_END`:

1. https://github.com/PaddlePaddle/Paddle/blob/0821ee78c5c553ff5ffe1fde40a73c01cf325b5e/paddle/fluid/inference/CMakeLists.txt#L14

1. https://github.com/PaddlePaddle/Paddle/blob/09b4a1a361003840e3690e61003a37db4f65564d/paddle/fluid/inference/tests/book/CMakeLists.txt#L20

`ARCHIVE_START` and `ARCHIVE_END` are not part of `cmake/generic.cmake`, thus is not supposed to be used in Fluid. Why do we need them in `paddle/fluid/inference`?

**Comment by wangkuiyi** [comment]
https://github.com/PaddlePaddle/Paddle/issues/9071#issuecomment-379525101

**Comment by Xreki** [comment]
`ARCHIVE_START` and `ARCHIVE_END` is defined in https://github.com/PaddlePaddle/Paddle/blob/develop/cmake/util.cmake#L8. It is a couple of flags needed by the linker `ld`. The usage is different for `gcc` and `clang`.
- For `gcc`, you should use `gcc -shared -o libab.so -Wl,--whole-archive liba.a -Wl,--no-whole-archive libb.a`

For the effect of `-Wl,--whole-archive`, you can refer to https://blog.csdn.net/Aquester/article/details/49800237. Without this linking flags, user codes for inference will fail by the error: `operators xxx is not registered`.

It is also used in caffe2:

https://github.com/caffe2/caffe2/blob/0dd3284525079f3870df92f61bed3b94eb45ff53/cmake/public/utils.cmake#L12-L24

**Comment by wangkuiyi** [comment]
I know the purpose of `-Wl,--whole-archive`. I am afraid that it would prevent us from building a binary (maybe a shared object file) which contains only the operators in use?

Anyway, I see that we have the `USE_OP` mechanism with Fluid:

https://github.com/PaddlePaddle/Paddle/blob/767f453ab89c48f827bbc7612e8a59b842297fdc/paddle/fluid/operators/dropout_op_test.cc#L33

I suppose that `USE_OP` would make us no longer need `-Wl,--whole-archive`, would it?

**Comment by Xreki** [comment]
I think you are right, I'll try.
