### ISSUE TITLE
wiki 连接失效

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#9739]
https://github.com/PaddlePaddle/Paddle/wiki/fluid-design-doc-summary

我们自己编辑的学习材料中，很多地方链接到了 github 的 wiki，但是现在都变成了 404；github 自己的 wiki 目录页面链接也都是 404。麻烦解决一下吧～多谢

**Comment by typhoonzero** [comment]
您好，上面的链接我使用safari和chrome打开都是正常的，没有出现404。github的wiki页面都是由github本身存储，正常是不会删除或者丢失的。麻烦再确认下，谢谢

**Comment by BryceLuminary** [comment]
@typhoonzero 您好，我是说的上面链接页面中的子链接

**Comment by typhoonzero** [comment]
您好以上wiki页面我更新了，最新的文档可以到http://www.paddlepaddle.org/docs/develop/documentation/fluid/zh/design/index_cn.html 查看，更加完整。
