### ISSUE TITLE
Remove the main function inside the test file

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#975]
Most of the main functions in the test file are the same.
Move function/TestMain.cpp to utils, and remove the main function in the test files.

**Comment by reyoung** [comment]
It will lead the paddle modules(gserver, trainer, etc.) to depend on `gtest` library, which could be unnecessary. 

Maybe extract to a module only used for unit tests is better.

**Comment by hedaoyuan** [comment]
There is no dependency problem. Only the executable of the test case is linked to TestMain.cpp.
> It will lead the paddle modules(gserver, trainer, etc.) to depend on gtest library
