### ISSUE TITLE
paddle book中栈式双向LSTM参数的问题

### ISSUE THREAD

**Issue by seanxh** [PaddlePaddle/Paddle#9757]
在paddle book的情感分析例子里。[http://www.paddlepaddle.org/docs/develop/book/06.understand_sentiment/index.cn.html](url)

1、lstm memory的输入是fc层的512维output。lstm的输出应该有c_t和h_t两个output，每个128维，为啥网络中lstm_memory的输出只有128维。输出的是哪个呢？
2、这个例子中对于不同长度的句子，是如何进行padding的，貌似没有体现？data = paddle.layer.data("word",paddle.data_type.integer_value_sequence(input_dim)) ，它的输入可以理解为是一个int sequence？网络直接对这个变长的int 序列进行embedding?而不是One-hot向量
3、fc_last = paddle.layer.pooling(input=inputs[0], pooling_type=paddle.pooling.Max())
这句的代码，inputs[0]应该是512维的，输出还是512维的？他做了一个什么维度的MaxPOOLING?

**Comment by chengduoZH** [comment]
> 1、lstm memory的输入是fc层的512维output。lstm的输出应该有c_t和h_t两个output，每个128维，为啥网络中lstm_memory的输出只有128维。输出的是哪个呢？

这里有关于lstmeory的介绍，你可以参考一下：http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#lstmemory

**Comment by chengduoZH** [comment]
> 1、lstm memory的输入是fc层的512维output。lstm的输出应该有c_t和h_t两个output，每个128维，为啥网络中lstm_memory的输出只有128维。输出的是哪个呢？

这里有关于lstmeory的介绍，你可以参考一下：http://www.paddlepaddle.org/docs/develop/api/en/config/layer.html#lstmemory 最后输出的是h_t

> 2、这个例子中对于不同长度的句子，是如何进行padding的，貌似没有体现？data = paddle.layer.data("word",paddle.data_type.integer_value_sequence(input_dim)) ，它的输入可以理解为是一个int sequence？网络直接对这个变长的int 序列进行embedding?而不是One-hot向量

是的

>3、fc_last = paddle.layer.pooling(input=inputs[0], pooling_type=paddle.pooling.Max())
这句的代码，inputs[0]应该是512维的，输出还是512维的？他做了一个什么维度的MaxPOOLING?

它做的相当于词之间的MaxPooling，这里有描述： https://github.com/PaddlePaddle/book/blob/develop/06.understand_sentiment/README.cn.md

**Comment by futureer** [comment]
1. lstmemory文档写着，四个与x有关的矩阵变换没包含在lstmemory内部，需要额外加一个fc层。那么在这篇教程里面的stackedLSTM实现，fc+lstmemory只能算是一个lstm网络，那么模型图中全连接的部分不就没体现出来吗？

2. fc接收了一个list的参数该如何理解？这个样例中，fc1的输出是t×512（n是句子中词的个数），lstm1是128维的h_t。这两个rank不一样的tensor在同一个fc中是如何计算的？
`inputs = [fc1, lstm1]
for i in range(2, stacked_num + 1):
fc = paddle.layer.fc(input=inputs,
                         size=hid_dim,
                         act=linear,
                         param_attr=para_attr,
                         bias_attr=bias_attr)
`
