### ISSUE TITLE
Make send recv serialization more readable by writting the ByteBuffer using a protobuf message.

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/Paddle#9766]
We can rewrite the serialization and deserialization for send/recv using the following sample code, thanks Xu laoshi for reminding.

```c++
sendrecv::VariableMessage request;
request.set_name(var_name);
...
std::string header;
request.AppendToString(&header);
ProtoEncodeHelper e(static_cast<char*>(buf), 1024);
e.WriteRaw(header.data(), header.size())
```

**Comment by typhoonzero** [comment]
@gongweibao is there a way to simplify `variable_response.cc` code?

**Comment by gongweibao** [comment]
Deserialization is implemented in variable_reponse.cc.
Do you mean to merge them into `ProtoEncodeHelper` class?

**Comment by gongweibao** [comment]
It's a good idea.

**Comment by gongweibao** [comment]
We can't deserialize part of proto.
So I close this issue.
