### ISSUE TITLE
Refactoring the Computation API in Paddle Based on Function

### ISSUE THREAD

**Issue by hedaoyuan** [PaddlePaddle/Paddle#977]
基于Function #892 重构Paddle中的 Computation API。

重构Computation API的几个目的：
1. 用统一的抽象来表示Computation，所以在重构Matrix API的时候需要同时完善FunctionBase;
2. 补充Computation的说明，原先实现在Matrix.cpp里面的很多API没有完善的注释解释API的功能和使用方法，重构的时候需要把Function的实现和用法描述清楚。
3. 更进一步可以对Computation API进行性能测试，优化实现的逻辑。

**Comment by hedaoyuan** [comment]
**Matrix API -> Function**

* [x] crossMapNormalFwd / crossMapNormalBwd -> CrossMapNormalFunc / CrossMapNormalGradFunc
* [ ] sequenceAvgForward
* [ ] maxoutForward / maxoutBackward
* [ ] oneHotCrossEntropy / oneHotCrossEntropyBp
* [ ] oneHotCrossEntropyWithSelfNorm / oneHotCrossEntropyWithSelfNormBp
* [ ] sequenceSoftmax
* [ ] softmax / softmaxDerivative / softmaxBackward
* [ ] sumOfSquares / sumOfSquaresBp
* [ ] tanh / tanhDerivative
* [ ] softrelu / softreluDerivative
* [ ] cosSim / cosSimDerivative
* [ ] convExpand / convShrink
* [ ] maxPoolForward / maxPoolBackward
* [ ] avgPoolForward / avgPoolBackward
* [ ] maxSequenceForward / maxSequenceBackward
* [ ] contextProjectionForward / contextProjectionBackwardData / contextProjectionBackwardWeight / contextProjectionBackward
* [ ] paramReluForward / paramReluBackwardW / paramReluBackwardDiff
* [ ] bilinearForward / bilinearBackward
* [ ] multiBinaryLabelCrossEntropy / multiBinaryLabelCrossEntropyBp
* [ ] circularConv / circularConvDerivative

------------------------
* [ ] addColumnVector
* [ ] randomizeUniform
* [ ] scaledTanh
* [ ] classificationError
* [ ] colMax
* [ ] rowMax
* [ ] rowSum
* [ ] colMerge
* [ ] addToRows
* [ ] selectRows
* [ ] mul / leftMul / rightMul
* [ ] collectSharedBias
* [ ] collectBias
* [ ] addBias
* [ ] addSharedBias
* [ ] inverse / getInverse
* [ ] transpose
* [ ] copyByRowIndex
* [ ] getAbsSum
* [ ] accumulateColSum
* [ ] getSum
* [ ] resetOne
* [ ] zeroMem
* [ ] setDiag
* [ ] rowNormalizeL1
* [ ] classificationErrorMulti
* [ ] copyFrom
----------------------------

**Comment by hedaoyuan** [comment]
**TrainingAlgorithmOp**

* [ ] sparseMomentumApply
* [ ] adadeltaApply
* [ ] adagradApply
* [ ] rmspropApply
* [ ] decayedAdagradApply
* [ ] adamApply
* [ ] adamaxApply

**Comment by hedaoyuan** [comment]
**RNN Computation API**

* [ ] LstmCompute::forwardBatch
* [ ] LstmCompute::backwardBatch
* [ ] LstmCompute::forwardOneSequence
* [ ] LstmCompute::backwardOneSequence
* [ ] GruCompute::forward
* [ ] GruCompute::backward

**Comment by hedaoyuan** [comment]
**CNN Computation API**

**Comment by hedaoyuan** [comment]
**Sparse Matrix Computation API**

**Comment by jacquesqiao** [comment]
refs: https://github.com/PaddlePaddle/Paddle/issues/892

**Comment by hedaoyuan** [comment]
Closed due to reconstruction.
