### ISSUE TITLE
希望发布新版C/C++预测SDK

### ISSUE THREAD

**Issue by shenshuijing** [PaddlePaddle/Paddle#978]
已经发布的sdk无法支持新的如batch norm等策略， 目前某产品线通过依赖sdk来进行在线预测， 线下产出的模型无法及时在线上使用， **希望能尽快发布最新版本的sdk**， 错误信息提示：
F1221 11:08:06.806284 32040 ClassRegistrar.h:63] Check failed: mapGet(type, creatorMap_, &creator) Unknown class type: batch_norm

**Comment by reyoung** [comment]
Duplicated with #849. And our current roadmap of this feature, please tracking #959 for update.
