### ISSUE TITLE
跑了下ltr model的例子， ranknet的网络收敛，可是lambda rank的网络从loss看根本不收敛

### ISSUE THREAD

**Issue by everal** [PaddlePaddle/Paddle#9793]
最近在考虑ltr model的使用，尤其是listwise的方式。
试了下paddle提供ranknet和lambda_rank两个模型(没做任何修改)，发现lambda_rank方式下cost并没有表现出减小的趋势，完全是无规律震荡的(如下图)。 于是又跑了下ranknet的模型，发现结果是收敛的。
请教下，pairwise和listwise的方式，理论上效果上是几乎相等的，但为何在训练结果上的差别如此大？是因为部分超参并没有选好么？
辛苦相关同学解答下。
![image](https://user-images.githubusercontent.com/7055728/38491300-186b40e8-3c1e-11e8-819c-2ea256f5f08d.png)

**Comment by chengduoZH** [comment]
你把`pairwise`的learning rate 调小点试试。

**Comment by everal** [comment]
![image](https://user-images.githubusercontent.com/7055728/38601384-eb1543c8-3d99-11e8-96d7-cb41fc821d0b.png)
@chengduoZH @pkuyym 翻看了lambda cost的实现，发现在计算delta NDCG的时候，似乎还考虑了截断后的部分，请问这么做是否合理呢？

**Comment by everal** [comment]
看了下paddle在lambdacost的实现，cost和ndcg是正相关的啊，感觉lambdarank的 优化目标应该是cost 最大化吧。
按照这个思路做了一些简单的实验：
选了一条样本，样本对应有10个doc， 迭代了100次，观察了这100个模型的cost变化。
发现cost会不断的升高直到cost = 10，我理解这个10其实就是优化到了ndcg值等于1的理想状态了。

既然如此，那是不是也验证了，listwise的训练目标其实是cost最大化，而非最小化。
辛苦paddlepaddle的同学确认下，这是符合预期的设计么？

@chengduoZH @gongweibao @pkuyym
