### ISSUE TITLE
delete_ops call should also delete variables of the op, but do not delete vars that all other ops use.

### ISSUE THREAD

**Issue by gongweibao** [PaddlePaddle/Paddle#9794]

**Comment by gongweibao** [comment]
related https://github.com/gongweibao/tests/issues/2

**Comment by luotao1** [comment]
Dose #9384 solve this issue?

**Comment by gongweibao** [comment]
A potential bugs of current implementation:
1. A user creates a global variable `LearningRate` without `operator` to use it.
2. Assign this variable to Adam optimizer.
    Adam optimizer can accept `float`  or variable argument.
3. When we use `delete_ops` to delete optimizers, it deletes all variable not used by other operators and so `LearningRate` variable is deleted.
4. When the user uses this variable, information prompted is incomprehensible

I met this last Saturday, how do you think to avoid this?
https://github.com/gongweibao/tests/issues/2

**Comment by luotao1** [comment]
Since `LearningRate` is assigned to `Adam_op` in stage2, why it be deleted in stage3? Does`Adam_op` not added to the program_desc?

**Comment by gongweibao** [comment]
The `adam` op doesn't create a new one if you assign a variable to it.
https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/optimizer.py#L427

**Comment by luotao1** [comment]
Does `LearningRate` and `Adam_op` in the same block? When we use `delete_ops` to delete optimizers, it deletes all variable not used by other operators in the same block.

**Comment by gongweibao** [comment]
It's not a perfect idea because it demands users to very careful with variables.
