### ISSUE TITLE
dssm-提交MPI集群训练模型，tar保存的模型不完整，在本地解压失败

### ISSUE THREAD

**Issue by sgcsky** [PaddlePaddle/Paddle#9806]
通过Receiver提交MPI集群训练任务，在每个pass训练完后会保存参数，并使用put的方式放到集群上，在本地解压失败，
tar: 归档文件中异常的 EOF
tar: 归档文件中异常的 EOF
tar: Error is not recoverable: exiting now，
在本地训练的时候，保存的参数不会出现该问题

**Comment by kuke** [comment]
@sgcsky 可否把你如何保存模型的代码也贴上

**Comment by sgcsky** [comment]
# save model
            if event.batch_id > 0 and \
                    isinstance(event, paddle.event.EndPass):
                model_desc = "{type}_{arch}".format(
                    type=str(model_type), arch=str(model_arch))
		filename = "%s/dssm_%s_pass-%05d.tar" % (model_output_prefix, model_desc, event.pass_id)
                with open(filename, "w") as f:
                    trainer.save_parameter_to_tar(f)
		    cmd  = "/home/normandy/nma/tools/hadoop-client/hadoop/bin/hadoop fs -D fs.default.name=XXXX -D hadoop.job.ugi=XXXX -put %s XXXX " % filename
		    os.system(cmd)

**Comment by gongweibao** [comment]
把这个cmd打印出来然后贴上来吧？

**Comment by sgcsky** [comment]
所有的机器会执行，这种冲突应该是导致提交不了，上传成功的感觉不该有问题

**Comment by sgcsky** [comment]
所有的机器会执行，这种冲突应该是导致提交不了，上传成功的感觉不该有问题

**Comment by kuke** [comment]
@sgcsky 可以试下只让某台机器保存模型

**Comment by sgcsky** [comment]
好的

**Comment by yeyupiaoling** [comment]
@sgcsky 
我之前也出现这样的错误，我当时怀疑的是每次保存模型的时间太快了，我然后几个pass在保存，就没有问题了。

**Comment by sgcsky** [comment]
@yeyupiaoling 我试下看看
