### ISSUE TITLE
DeepSpeech工程的 example/aishell/run_infer_golden.sh 运行报错，貌似模型文件不匹配。

### ISSUE THREAD

**Issue by bluebird138** [PaddlePaddle/Paddle#9810]
运行～/DeepSpeech/example/aishell/run_infer_golden.sh 报错。貌似以下两个参数的文件不匹配。
--model_path='models/aishell/params.tar.gz' \
--lang_model_path='models/lm/zh_giga.no_cna_cmn.prune01244.klm' \

报错信息如下。
[INFO 2018-04-10 10:57:46,684 model.py:243] begin to initialize the external scorer for decoding
terminate called after throwing an instance of 'lm::FormatLoadException'
  what():  kenlm/lm/binary_format.cc:160 in void* lm::ngram::BinaryFormat::LoadBinary(std::size_t) threw FormatLoadException because `file_size != util::kBadSize && file_size < total_map'.
Binary file has size 1088258466 but the headers say it should be at least 2953349384

本次是在Ubuntu16.04 不使用docker下测试 DeepSpeech，且不使用GPU,运行参数如下。
CUDA_VISIBLE_DEVICES=0 \
python -u infer.py \
--num_samples=10 \
--trainer_count=1 \
--beam_size=300 \
--num_proc_bsearch=8 \
--num_conv_layers=2 \
--num_rnn_layers=3 \
--rnn_layer_size=1024 \
--alpha=2.6 \
--beta=5.0 \
--cutoff_prob=0.99 \
--cutoff_top_n=40 \
--use_gru=True \
--use_gpu=False \
--share_rnn_weights=False \
--infer_manifest='data/aishell/manifest.test' \
--mean_std_path='models/aishell/mean_std.npz' \
--vocab_path='models/aishell/vocab.txt' \
--model_path='models/aishell/params.tar.gz' \
--lang_model_path='models/lm/zh_giga.no_cna_cmn.prune01244.klm' \
--decoding_method='ctc_beam_search' \
--error_rate_type='cer' \
--specgram_type='linear'

**Comment by kuke** [comment]
@bluebird138 应该是模型没有成功下载造成的，请尝试重新下载模型， 并确保下载成功。

**Comment by bluebird138** [comment]
我通过以下链接下载语言模型 zh_giga.no_cna_cmn.prune01244.klm 文件，发现无法完整下载。
http://cloud.dlnel.org/filepub/?uuid=5cd1688e-78d9-4b9e-9c2f-6f104bd5b518
例如我使用火狐浏览器下载到的文件大小是1,716,728KB，与官网提示的2.8GB相差很大，无法正常下载。已多次尝试下载失败。

另外也尝试过使用DeepSpeech/models/lm/download_lm_ch.sh修改URL后的shell脚本下载，同样下载失败。
URL=http://cloud.dlnel.org/filepub/?uuid=5cd1688e-78d9-4b9e-9c2f-6f104bd5b518
MD5="29e02312deb2e59b3c8686c7966d4fe3"
TARGET=./zh_giga.no_cna_cmn.prune01244.klm

求完整下载zh_giga.no_cna_cmn.prune01244.klm的方法。

**Comment by bluebird138** [comment]
vi /etc/hosts
填写 
180.76.189.142   cloud.dlnel.org 
问题解决
