### ISSUE TITLE
average layer 及其他一些layer 不能在配置中设置drop_rate

### ISSUE THREAD

**Issue by lcy-seso** [PaddlePaddle/Paddle#983]
下图是 config_parse.py 中的average layer，红色圈出来的是新加入目前代码里面缺少的。一些参数没有办法传给 LayerBase。

最常用的比如 drop_rate，导致average layer 无法直接设置 dropout，类似的 layer 还有一些，未完全统计。

![image](https://cloud.githubusercontent.com/assets/5842774/21384488/bc402236-c7a5-11e6-94cc-8b61285992f3.png)

**Comment by reyoung** [comment]
Thx，直接提PR应该可以吧。

**Comment by lcy-seso** [comment]
嗯。好的。
