### ISSUE TITLE
是否可以提供noavx的pip安装方式

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/Paddle#9834]
这一段时间里，我看的有很多同学的因为电脑不支持AVX指令集，要编译源码安装，非常麻烦。使用可以提供pip安装方法。如这样：
```
pip install paddlepaddle-noavx
```

**Comment by pkuyym** [comment]
这个里面编译了很多不同版本的whl包
![image](https://user-images.githubusercontent.com/5782283/38597672-9c038528-3d8b-11e8-8430-026dfe006141.png)

**Comment by yeyupiaoling** [comment]
@pkuyym 
感谢回答，如果再本地，这个是挺好的，但是在服务器就不太友好了，因为有个验证过程。

顺便问一下，从https://paddleci.ngrok.io/ 这里下载的，是不是最新的，
我刚才看了其中一个安装包：paddlepaddle-0.11.0-cp27-cp27mu-linux_x86_64.whl 
而我在上个月用源码编译的是：paddlepaddle-0.11.1a1-cp27-cp27mu-linux_x86_64.whl
可以看到CI系统中的版本更低，但我看的编译时间是10小时之前的，理论上版本更高才对。

还有，我编译的有300多M，而CI系统中的已有不到100M，CI系统中的安装包是不是少了很多依赖库？

**Comment by pkuyym** [comment]
> 感谢回答，如果再本地，这个是挺好的，但是在服务器就不太友好了，因为有个验证过程。

理论上可以直接download下来，然后传到服务器，会略麻烦一些。

> 还有，我编译的有300多M，而CI系统中的已有不到100M，CI系统中的安装包是不是少了很多依赖库？

需要选取通过CI的编译版本，至于哪个版本更新，可以通过对比commit id 

```python
import paddle
print paddle.version.commit
```

**Comment by yeyupiaoling** [comment]
@pkuyym 感谢回答，谢谢。
