### ISSUE TITLE
机器翻译的例子，运行速度很慢，麻烦问一下这块瓶颈在哪

### ISSUE THREAD

**Issue by iyishengyoun** [PaddlePaddle/Paddle#9836]
直接用的例子的train.py 感觉执行速度很慢

**Comment by pkuyym** [comment]
建议做一下profiling，这样才能知道为什么慢

**Comment by pkuyym** [comment]
@iyishengyoun 这个函数是个很大的函数，测的整个ForwardBackward，CPU本来就很慢，优化没有GPU的多

**Comment by xingyushu** [comment]
时间单位是分钟吗？用gpu环境试一下吧

**Comment by lcy-seso** [comment]
issue中提供的信息太笼统了。机器翻译本身就是一个计算量很大的模型，运行速度慢到底是不正常的慢，还是正常？如果认为是不正常的慢，又是如何判断为不正常的呢？模型规模是多少（使用多少个LSTM/GRU单元，隐层大小，词表大小）？想要达到的预期计算速度是多少呢？这些信息缺失无法回答issue中的问题。

**Comment by iyishengyoun** [comment]
gpu环境运行
