### ISSUE TITLE
pre-commit clang-format 3.6和clang-format 4.0结果不同

### ISSUE THREAD

**Issue by pengli09** [PaddlePaddle/Paddle#984]
pre-commit中clang-format似乎默认用的是4.0版或更高，当使用clang-format 3.6时，格式化出来的结果会与4.0有差别。参见[此处](https://github.com/PaddlePaddle/Paddle/pull/678/commits/5c3b8f6bd18bfadfa23e2a4eb4821bf383a3fd77)，左侧为3.6格式化结果，右侧为4.0格式化结果。

**Comment by backyes** [comment]
大家clang-format 3.8用的比较多， 可以看看3.8的有没有diff 。 内网gitlab idl-dl group下有一个编译好的3.8版本

**Comment by reyoung** [comment]
因为clang-format 3.8有一个新功能我们要用。

https://github.com/PaddlePaddle/Paddle/blob/develop/doc/howto/dev/contribute_to_paddle_en.md#using-pre-commit-hook
