### ISSUE TITLE
c++使用动态链接库、多线程，加载多个模型，会概率性假死

### ISSUE THREAD

**Issue by likeqinqin** [PaddlePaddle/Paddle#9845]
#0  0x00007fff765289a5 in clock_gettime ()
#1  0x00007f4922e87cbd in clock_gettime () from /opt/compiler/gcc-4.8.2/lib/libc.so.6
#2  0x00007f490c5d3f1e in ?? () from /usr/lib64/libcuda.so.1
#3  0x00007f490c661325 in ?? () from /usr/lib64/libcuda.so.1
#4  0x00007f490c5c00e3 in ?? () from /usr/lib64/libcuda.so.1
#5  0x00007f490c5c0239 in ?? () from /usr/lib64/libcuda.so.1
#6  0x00007f490c4e7ce7 in ?? () from /usr/lib64/libcuda.so.1
#7  0x00007f490c61a9d2 in cuStreamSynchronize () from /usr/lib64/libcuda.so.1
#8  0x00007f493c807684 in cudart::cudaApiStreamSynchronize(CUstream_st*) () from ./extend/lib/libpaddle_capi_shared.so
#9  0x00007f493c83dc2d in cudaStreamSynchronize () from ./extend/lib/libpaddle_capi_shared.so
#10 0x00007f493c73149c in hl_stream_synchronize(hl_stream_t) () from ./extend/lib/libpaddle_capi_shared.so
#11 0x00007f493c728827 in hl_matrix_mul(float*, hl_trans_op_t, float*, hl_trans_op_t, float*, int, int, int, float, float, int, int, int) () from ./extend/lib/libpaddle_capi_shared.so
#12 0x00007f493c537cfb in paddle::GemmConvFunction<(paddle::DeviceType)2>::calc(paddle::BufferArgs const&, paddle::BufferArgs const&) () from ./extend/lib/libpaddle_capi_shared.so
#13 0x00007f493c41e89f in paddle::ExpandConvLayer::forward(paddle::enumeration_wrapper::PassType) () from ./extend/lib/libpaddle_capi_shared.so
#14 0x00007f493c492d0d in paddle::NeuralNetwork::forward(std::vector<paddle::Argument, std::allocator<paddle::Argument> > const&, std::vector<paddle::Argument, std::allocator<paddle::Argument> >*
, paddle::enumeration_wrapper::PassType) () from ./extend/lib/libpaddle_capi_shared.so
#15 0x00007f493c30ed76 in paddle_gradient_machine_forward () from ./extend/lib/libpaddle_capi_shared.so
#16 0x0000000000816a1b in xp::PaddlePredict::_predict(cv::Mat&, std::vector<float, std::allocator<float> >&, int, int) ()

**Comment by pkuyym** [comment]
请问能不能提供一个可稳定复现的环境，这样会帮助我们定位问题所在

**Comment by likeqinqin** [comment]
可以提供，方便 hi 上聊吗

**Comment by likeqinqin** [comment]
已解决，赞paddle同学的高效支持，非常感谢。cuda Stream是进程的全局变量，需要进程级别锁保证线程安全。后续更新后烦请同步。

**Comment by pymumu** [comment]
@likeqinqin 问一下，我们当前遇到一个类似的cuda卡住问题。
你说的这个Stream是进程全局变量，要进程级别的锁，这个能具体说明一下吗？
