### ISSUE TITLE
Unable to import paddle.fluid using the "paddle:latest" docker image. 

### ISSUE THREAD

**Issue by sidgoyal78** [PaddlePaddle/Paddle#9856]
Hi, I wanted to test a script using the docker image which has the latest paddle installed. So I did this:
`docker pull paddlepaddle/paddle:latest` , followed by:
`docker run -it -v `pwd`:/paddle paddlepaddle/paddle:latest /bin/bash`

Then, i tried importing paddle.fluid from inside the container. But I get this error:
```
root@406dbf58b9d3:/paddle# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
>>> import paddle.fluid as fl
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/__init__.py", line 17, in <module>
    import framework
  File "/usr/local/lib/python2.7/dist-packages/paddle/fluid/framework.py", line 22, in <module>
    from . import core
ImportError: /usr/local/lib/python2.7/dist-packages/paddle/fluid/core.so: undefined symbol: PyUnicodeUCS2_FromString
```

Has anyone encountered this?

**Comment by Yancey1989** [comment]
FROM @typhoonzero 
> I've changed the CI build command template today, then it errors when pushing the built image to docker.paddlepaddlehub.com/paddle

Thanks for recovering the building, and I check the registry server just now, `push failed` may be caused by the full disk on the registry server, I'll fix this problem and feed back here.
