### ISSUE TITLE
请问scale_shift层参数如何使用？

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#9882]
我有一个cos_sim的输出，原始范围是【-1,1】
想通过0.5x + 0.5 把这层输出变化到 【0， 1】之间，
利用paddle.v2.layer.scale_shift（），这个0.5x + 0.5的参数para和bias应该怎么写呢？

**Comment by HugoLian** [comment]
原始需求就是变化下区间，不一定非使用scale_shift，别的可以实现的方法也可以。

**Comment by pkuyym** [comment]
请试一下这个layer https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/trainer_config_helpers/layers.py#L5323，scale_shift可能会要求scale和shift是可训练的参数

**Comment by HugoLian** [comment]
@pkuyym 请问这个应该如何使用呢？我直接定义：
auc_layer = paddle.layer.slope_intercept_layer(name='scale_layer', slope=0.5, intercept=0.5)
报错：
‘’‘
Traceback (most recent call last):
  File "train_recommend_test.py", line 139, in <module>
    main()
  File "train_recommend_test.py", line 47, in main
    auc_layer = paddle.layer.slope_intercept_layer(name='scale_layer', slope=0.5, intercept=0.5)
AttributeError: 'module' object has no attribute 'slope_intercept_layer'
’‘’

**Comment by yuanxiangxie** [comment]
@HugoLian Hi 你好，我现在也有这个需求，但是我采用slope之后遇到训练信息无输出的情况(https://github.com/PaddlePaddle/Paddle/issues/12850#issuecomment-414933643)，请问你遇到了吗？ paddle v2版本
