### ISSUE TITLE
paddle v0.11.0 GPU版本向下兼容CPU版本吗

### ISSUE THREAD

**Issue by babybear1992** [PaddlePaddle/Paddle#9890]
问题就是，paddlepaddle v0.11.0 GPU版是否向下兼容CPU版，这样我只需要安装GPU版本即可。

**Comment by guoshengCS** [comment]
GPU版是兼容CPU的版本的

**Comment by defineconst** [comment]
有NVIDIA显卡是表示可以支持GPU吗？CUDA、CUDNN选择什么版本了？
