### ISSUE TITLE
Fluid with distribution can not run rightly when batch_size is too small

### ISSUE THREAD

**Issue by seiriosPlus** [PaddlePaddle/Paddle#9893]
I think there are questions about our trainer start-up mechanisms @Yancey1989 @typhoonzero.

At present, trainer starts to run only base on judge whether the pserver process exists, when the batch_size is too small, It will send gradient to pserver before pserver is ready to receive, that may throw the exception.
```
E0413 05:42:53.977813  2453 grpc_client.cc:234] proc param error:name:[fc_26.b_0@GRAD] ep:[127.0.0.1:36001] grpc error:Connect Failed
```

**Comment by typhoonzero** [comment]
See https://github.com/PaddlePaddle/cloud/blob/develop/docker/paddle_k8s for how we do the process syncing.

**Comment by seiriosPlus** [comment]
OK,  I will have a try.

**Comment by seiriosPlus** [comment]
I have fixed it in Paddle/cloud, the pull request is: https://github.com/PaddlePaddle/cloud/pull/654
