### ISSUE TITLE
关于推荐双塔模型输出的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#9900]
我用的双塔推荐模型参考下图：
![image](https://user-images.githubusercontent.com/22980558/38727502-c3bcb9bc-3f3f-11e8-886a-043339587d97.png)

实际使用的时候，希望输出用户向量，即L2  物品向量，R2
因为模型训练的时候是先读入的用户数据，再读入的物品数据。
所以如果想获得L2输出时，模型仅仅加载L1数据即可：
![image](https://user-images.githubusercontent.com/22980558/38727666-3f2d0462-3f40-11e8-91e0-60b718ab5ca8.png)

但是如果要获得R2的输出，只加载物品的网络结构就报错了，必须先加载L1的网络结构（可以没有数据输入），再加在R1才能成功：
![image](https://user-images.githubusercontent.com/22980558/38727724-6d5e7e60-3f40-11e8-9ab1-c603ad7e87df.png)

请问必须要这样么？或者通过怎么配置可以只加载右半部分网络就可以输出结果呢？

**Comment by guoshengCS** [comment]
请问报错是怎样的，还请贴下报错信息

**Comment by HugoLian** [comment]
@guoshengCS 接主题中第三图，如果把get_user_feature() 那个左塔设置注销：
![image](https://user-images.githubusercontent.com/22980558/38788576-2425e93a-4167-11e8-85d1-56e164fa93ec.png)

运行报错：
![image](https://user-images.githubusercontent.com/22980558/38788624-631639c4-4167-11e8-869e-d92326aacdad.png)

如果是计算左边的用户特征，不读取get_feed_feature() 没有问题。

**Comment by guoshengCS** [comment]
这个报错应该是load的模型结构和保存的模型参数不一致，参数没对上。

**Comment by HugoLian** [comment]
@guoshengCS 是的，因为没有先读入user的网络结构，所以数据对不上。。我先执行
user_features = get_user_feature()
但是在feeding中并没设置任何用户数据的输入就可以执行，但是不先读入这个不用的左半边网络就一直对不上，所以我就想请教一下，有不读入左半边网络可以直接输出R2的方法么？

其中两边网络结构的代码和feeding的输入如下：
‘’‘
def get_user_features():
    user_main = paddle.layer.data(name='user_main', type=paddle.data_type.sparse_float_vector(568999))
    user_main_fc = paddle.layer.fc(input=user_main, size=64, act=paddle.activation.Relu())
    
    user_minor = paddle.layer.data(name='user_minor', type=paddle.data_type.sparse_float_vector(568999))
    user_minor_fc = paddle.layer.fc(input=user_minor, size=16, act=paddle.activation.Relu())
    
    user_part = paddle.layer.fc(input=[user_main_fc, user_minor_fc], size=32, act=paddle.activation.Tanh())

    return user_part

def get_feed_features():
    feed_plsa = paddle.layer.data(name='feed_plsa', type=paddle.data_type.sparse_binary_vector(1001))
    feed_plsa_fc = paddle.layer.fc(input=feed_plsa, size=32, act=paddle.activation.Relu())
    
    feed_tag = paddle.layer.data(name='feed_tag', type=paddle.data_type.sparse_binary_vector(568999))
    feed_tag_fc = paddle.layer.fc(input=feed_tag, size=32, act=paddle.activation.Relu())
    
    feed_entity = paddle.layer.data(name='feed_entity', type=paddle.data_type.sparse_binary_vector(44163))
    feed_entity_fc = paddle.layer.fc(input=feed_entity, size=32, act=paddle.activation.Relu())
    
    feed_attention = paddle.layer.data(name='feed_attention', type=paddle.data_type.sparse_binary_vector(92325))
    feed_attention_fc = paddle.layer.fc(input=feed_attention, size=32, act=paddle.activation.Relu())
    
    feed_cid= paddle.layer.data(name='feed_cid', type=paddle.data_type.sparse_binary_vector(16))
    
    feed_pid= paddle.layer.data(name='feed_pid', type=paddle.data_type.sparse_binary_vector(21))
    
    feed_part = paddle.layer.fc(input=[feed_plsa_fc, feed_tag_fc, feed_entity_fc, feed_attention_fc, feed_cid, feed_pid], size=32, act=paddle.activation.Tanh())

    return feed_part

def main():
    paddle.init(use_gpu=True, trainer_count=4)
    user_features = get_user_features()
    feed_features = get_feed_features()
    
    with gzip.open('../model/pass-9-test-0.0623276769836.tar.gz', 'r') as f: 
        parameters = paddle.parameters.Parameters.from_tar(f)
    
    feeding = {
        'feed_plsa': 0,
        'feed_tag': 1,
        'feed_entity': 2,
        'feed_attention': 3,
        'feed_cid': 4,
        'feed_pid': 5
    }
    ..........以下省略，可参考上面切图
’‘’

**Comment by guoshengCS** [comment]
可以试下从保存的模型里把两部分各自的参数拿出来手工的保存两个模型分别load，如果无法确定这两部分各自所使用的参数时可以在定义网络结构时为每一层设置layer name来进行判断

**Comment by HugoLian** [comment]
那请问应该如何手动保存呢？比如我第一步先读取一个参数到parameter:
parameters = paddle.parameters.Parameters.from_tar(gzip.open('./model.tar.gz'))

例如里面就两个slot，分两个fc输出：
user = paddle.layer.data(name='user', type=paddle.data_type.sparse_float_vector(20000))
user_fc = paddle.layer.fc(name='user_fc', input=user, size=64, act=paddle.activation.Relu())

feed= paddle.layer.data(name='feed', type=paddle.data_type.sparse_float_vector(10000))
feed_fc = paddle.layer.fc(name='feed_fc', input=user, size=64, act=paddle.activation.Relu())

我看保存模型用的是：
parameters.to_tar(f)

那么如何把user 和feed的参数手动保存到两个文件呢？可以给个demo么？
@guoshengCS

**Comment by guoshengCS** [comment]
直接解压tar文件，然后把各自相关的参数文件拿出来就可以

**Comment by guoshengCS** [comment]
较久未更新，先行关闭此issue，如有需要还请重新打开。
