### ISSUE TITLE
C++ 预测接口临时解决方案

### ISSUE THREAD

**Issue by backyes** [PaddlePaddle/Paddle#991]
考虑到基于Paddle重构的C-API接口进行封装C++预测接口短期内不能ready，本着尽快解决问题的原则，计划先提供一个 *支持Paddle最新接口的C++预测接口* 临时解决方案。 

关联issue： 
https://github.com/PaddlePaddle/Paddle/issues/849 

@reyoung  将follow相关进度。

**Comment by reyoung** [comment]
Closed because it has been discussed offline.

**Comment by backyes** [comment]
以后遇到 C++ 预测接口问题，先连接 @reyoung  协调内部同学，临时帮忙解决。
