### ISSUE TITLE
Can we remove paddle/scripts/check_env.sh

### ISSUE THREAD

**Issue by wangkuiyi** [PaddlePaddle/Paddle#9916]
@wanglei828 is cleaning up our build and test scripts. He has a question -- it seems that Github code search reveals that `paddle/scripts/check_env.sh` is not used anywhere in our codebase. Could we remove it? @tensor-tang

**Comment by luotao1** [comment]
Yes, we can move `check_env.sh` to https://github.com/PaddlePaddle/Paddle/tree/develop/benchmark. It's used to check the environment of benchmark machine.

**Comment by tensor-tang** [comment]
Sure, we can put it anywhere appropriate or just keep it offline. I am OK with any case.
