### ISSUE TITLE
Error in cross compilation for raspberry pi on ubuntu 16.04  -  undefined reference to `paddle::DataProvider::getNextBatch

### ISSUE THREAD

**Issue by cogmeta** [PaddlePaddle/Paddle#9936]
[ 80%] Built target paddle_parameter
[ 80%] Built target paddle_network
[ 82%] Built target paddle_pserver
[ 85%] Built target paddle_trainer_lib
[ 85%] Built target paddle_pserver_main
Linking CXX executable paddle_merge_model
libpaddle_trainer_lib.a(Trainer.cpp.o): In function `paddle::Trainer::checkGradient()':
/home/ubuntu/deepspeech-rpi/Paddle/paddle/trainer/Trainer.cpp:310: undefined reference to `paddle::DataProvider::getNextBatch(l\
ong long, paddle::DataBatch*)'
libpaddle_trainer_lib.a(Trainer.cpp.o): In function `paddle::Trainer::trainOnePass()':
/home/ubuntu/deepspeech-rpi/Paddle/paddle/trainer/Trainer.cpp:505: undefined reference to `paddle::DataProvider::getNextBatch(l\
ong long, paddle::DataBatch*)'
libpaddle_trainer_lib.a(Trainer.cpp.o): In function `paddle::Trainer::init(std::shared_ptr<paddle::TrainerConfigHelper> const&,\
 bool, std::shared_ptr<paddle::GradientMachine> const&, std::shared_ptr<paddle::DataProvider> const&, std::shared_ptr<paddle::D\
ataProvider> const&)':
/home/ubuntu/deepspeech-rpi/Paddle/paddle/trainer/Trainer.cpp:231: undefined reference to `paddle::GradientMachine::randParamet\
ers()'
/home/ubuntu/deepspeech-rpi/Paddle/paddle/trainer/Trainer.cpp:215: undefined reference to `paddle::DataProvider::create(paddle:\
:DataConfig const&, paddle::ModelConfig const&, bool)'
/home/ubuntu/deepspeech-rpi/Paddle/paddle/trainer/Trainer.cpp:196: undefined ref

**Comment by JiayiFeng** [comment]
能贴一下你的`CMakeLists.txt`中的配置吗，可以试下设置WITH_PYTHON=OFF编译
