### ISSUE TITLE
如果每个特征的维度不同，怎么输入给模型？

### ISSUE THREAD

**Issue by peiss** [PaddlePaddle/Paddle#9945]
比如我有如下的特征列表：

特征1 - 用户搜索QUERY进行分词后的One-hot：类型为定长数组，比如[0,0,0,1,0,0]
特征2 - 用户的性别：类型为单个元素整形，比如1
特征3 - 用户的兴趣列表：类型为不定长数组，比如[游泳、跑步]、[游戏、看书、音乐]

这三个特征，类型分别是定长数组、单个元素、不定长数组
请问这样的特征集合，怎么输入给模型呢》？

**Comment by peiss** [comment]
最好帮忙给个例子，初学Paddle，谢谢

**Comment by chaoswork** [comment]
特征3也搞个大词典后one-hot，最后就是三个定长list concat成一个定长list。再输入给模型。

**Comment by chengduoZH** [comment]
该issue长时间没有回复，暂且关闭了。
