### ISSUE TITLE
Aborted at 1523880810 (unix time) try "date -d @1523880810" if you are using GNU date

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#9955]
*** Aborted at 1523880810 (unix time) try "date -d @1523880810" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGSEGV (@0x18) received by PID 5090 (TID 0x7f9f684b7800) from PID 24; stack trace: ***
    @       0x318b20f500 (unknown)
    @     0x7f9f68ec0392 list_repr
    @     0x7f9f68ed1055 PyObject_Repr
    @           0xfa3c4f paddle::py::repr()
    @           0xc1021f paddle::IndexScanner::fill()
    @           0xc10bd4 paddle::SequenceScanner::fill()
    @           0xc0f8ab paddle::PyDataProvider2::getNextBatchInternal()
    @           0xbdeadf paddle::DataProvider::getNextBatch()
    @           0xda5e75 paddle::Trainer::trainOnePass()
    @           0xda4652 paddle::Trainer::train()
    @           0xafa224 main
    @       0x318ae1ecdd (unknown)
    @           0xaf9e5d (unknown)

**Comment by JiayiFeng** [comment]
SIGSEGV一般是段错误，内存访问越界引起的。

**Comment by yeyupiaoling** [comment]
@JiayiFeng 一般从什么办法入手解决这问题呢？

**Comment by cbstyle** [comment]
目前这个问题是输入的label格式造成的

**Comment by cbstyle** [comment]
这个错误确实是训练数据异常导致的。
