### ISSUE TITLE
关于infer随机报错的问题

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#9972]
同样的预测数据，同样的程序和运行环境，中间没有任何shuffle等随机过程，为什么有的时候能直接成功，有的时候会报下述错误呢？这个错误和什么有关？
![image](https://user-images.githubusercontent.com/22980558/38846797-dd8ccf64-4230-11e8-8cd8-ddad2b15669c.png)

**Comment by jacquesqiao** [comment]
这是用c_api进行预测的么？

**Comment by HugoLian** [comment]
@jacquesqiao 不是的，就是用python paddle.infer()的方法预测。

**Comment by jacquesqiao** [comment]
把thread设置成1试试呢？

**Comment by HugoLian** [comment]
@jacquesqiao 你是说把trainer_count设置成1么？

**Comment by jacquesqiao** [comment]
@HugoLian 对，只用一个线程，一张卡，https://github.com/PaddlePaddle/Paddle/issues/7598 类似这个

**Comment by chengduoZH** [comment]
Close this inactive issue, please feel free to reopen it.
