### ISSUE TITLE
Aborted at 1523938666 (unix time) try "date -d @1523938666" if you are using GNU date

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#9976]
/home/***/m000_000200_0.pkl
Thread [140324547237888] Forwarding __fc_layer_1__, 
*** Aborted at 1523938666 (unix time) try "date -d @1523938666" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0xdfc80f) received by PID 21833 (TID 0x7f9fdaca9800) from PID 14665743; stack trace: ***
    @       0x318b20f500 (unknown)
    @           0xdfc80f paddle::CpuMatrix::softmax()
    @           0xdfccab paddle::CpuMatrix::sequenceSoftmax()
    @           0xbc8088 paddle::sequence_softmaxActivation::forward()
    @           0xc245c9 paddle::Layer::forwardActivation()
    @           0xca8948 paddle::FullyConnectedLayer::forward()
    @           0xb26896 paddle::NeuralNetwork::forward()
    @           0xb2a726 paddle::GradientMachine::forwardBackward()
    @           0xdabdba paddle::TrainerInternal::forwardBackwardBatch()
    @           0xdaa411 paddle::TrainerInternal::trainOneBatch()
    @           0xda5a26 paddle::Trainer::trainOneDataBatch()
    @           0xda5f2f paddle::Trainer::trainOnePass()
    @           0xda4652 paddle::Trainer::train()
    @           0xafa224 main
    @       0x318ae1ecdd (unknown)

    @           0xaf9e5d (unknown)

**Comment by jacquesqiao** [comment]
看错误信息是 ‘SIGFPE' float point exception. 计算出现数值问题，请尝试降低batcisize、降低学习速率或者优化算法等方法。

**Comment by cbstyle** [comment]
/home/***/attempt_20171215200623_1687558_m000_000027_0.pkl
/home/***/attempt_20171215200623_1687558_m000_000028_0.pkl
/home/***/attempt_20171215200623_1687558_m000_000029_0.pkl
/home/***/attempt_20171215200623_1687558_m000_000030_1.pkl
.........
I0417 14:59:26.435760  3243 TrainerInternal.cpp:165]  Batch=10 samples=80 AvgCost=9.30827 CurrentCost=9.30827 Eval: classification_error=0.00739437  CurrentEval: classification_error=0.00739437 
.........
I0417 15:00:11.914364  3243 TrainerInternal.cpp:165]  Batch=20 samples=160 AvgCost=8.99264 CurrentCost=8.677 Eval: classification_error=0.00724765  CurrentEval: classification_error=0.00710094 
.........
I0417 15:00:59.582525  3243 TrainerInternal.cpp:165]  Batch=30 samples=240 AvgCost=8.95793 CurrentCost=8.88851 Eval: classification_error=0.007277  CurrentEval: classification_error=0.00733568 
.....Thread [139909066135552] Forwarding __fc_layer_1__, 
*** Aborted at 1523948485 (unix time) try "date -d @1523948485" if you are using GNU date ***
PC: @                0x0 (unknown)
*** SIGFPE (@0xdfc80f) received by PID 3243 (TID 0x7f3f1e301800) from PID 14665743; stack trace: ***
    @       0x318b20f500 (unknown)
    @           0xdfc80f paddle::CpuMatrix::softmax()
    @           0xdfccab paddle::CpuMatrix::sequenceSoftmax()
    @           0xbc8088 paddle::sequence_softmaxActivation::forward()
    @           0xc245c9 paddle::Layer::forwardActivation()
    @           0xca8948 paddle::FullyConnectedLayer::forward()
    @           0xb26896 paddle::NeuralNetwork::forward()
    @           0xb2a726 paddle::GradientMachine::forwardBackward()
    @           0xdabdba paddle::TrainerInternal::forwardBackwardBatch()
    @           0xdaa411 paddle::TrainerInternal::trainOneBatch()
    @           0xda5a26 paddle::Trainer::trainOneDataBatch()
    @           0xda5f2f paddle::Trainer::trainOnePass()
    @           0xda4652 paddle::Trainer::train()
    @           0xafa224 main
    @       0x318ae1ecdd (unknown)
    @           0xaf9e5d (unknown)

**Comment by jacquesqiao** [comment]
修改之后还是有问题，建议对训练数据进行检查

**Comment by cbstyle** [comment]
发现确实是训练数据异常导致的bug；对数据读取部分加上异常检查逻辑；
