### ISSUE TITLE
官网 API 说明文档的疑问

### ISSUE THREAD

**Issue by BryceLuminary** [PaddlePaddle/Paddle#9979]
请问 prior_box 和 box_coder 两个 OP 是对外可见的 Layer 吗？
如果是的话，我在 Paddle 的 API 说明页 http://www.paddlepaddle.org/docs/develop/api/fluid/en/layers.html 中没有找到它们。
麻烦补上说明吧，多谢！

**Comment by qingqing01** [comment]
- prior_box: 没有单独对外，集成在multi_box_head之中，参考文档：https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/detection.py#L567

- box_coder： 对外可见，用法类似： https://github.com/PaddlePaddle/Paddle/blob/develop/python/paddle/fluid/layers/detection.py#L126

"Paddle 的 API 说明页" 还没加上，后续加下。
