### ISSUE TITLE
paddle中怎样实现channel shuffle的功能

### ISSUE THREAD

**Issue by huayong** [PaddlePaddle/Paddle#9986]
目前在caffe中实现了shufflenet网络，里面用到了channel shuffle的功能，具体caffe的实现连接如下：https://github.com/farmingyard/ShuffleNet ，
基本思路如下图（从https://github.com/camel007/Caffe-ShuffleNet 截的图）：
![image](https://user-images.githubusercontent.com/7414341/38856175-4c363154-4258-11e8-9f0d-cc15d75b0aff.png)

后面需要把网络转换到paddle上使用，其他的layer目前paddle中都已经转换完成，该操作查阅了一些资料，目前没有头绪，如何在paddle端怎样去复现该操作，希望给些建议，多谢！

**Comment by jacquesqiao** [comment]
v2不支持这种操作，Fluid支持这种操作

**Comment by jacquesqiao** [comment]
可以考虑用fluid实现相应的功能。
