### ISSUE TITLE
关于预测阶段出out of memory的问题求助：

### ISSUE THREAD

**Issue by HugoLian** [PaddlePaddle/Paddle#9990]
用的paddle.infer() 方法，每输入2000条元素执行一次这个方法，主要部分代码如下：
```
input_data = []
        res = []
        ids = []
        count = 0
        out_file = open("./data.infer.user", "w");
        with open("./data.user") as file:
            for line in file:
                data = line.strip().split("\t")
                if len(data) == 2:
                    input_data.append([get_sparse_index_data(data[1]), get_sparse_index_data([])])
                    ids.append(data[0])
                elif len(data) == 3:
                    input_data.append([get_sparse_index_data(data[1]), get_sparse_index_data(data[2])])
                    ids.append(data[0])
                else:
                    continue
                count += 1
                if count == 2000:
                    res = paddle.infer(output_layer=user_features, parameters=parameters, input=input_data, feeding=feeding)
                    for index in range(0, count):
                        list = res[index]
                        output = ''
                        for i in range(0, 32) :
                            output += str(round(list[i], 4)) + " "
                        out_file.write(ids[index] + "\t" + output.strip() + "\n")
                    input_data = []
                    ids = []
                    count = 0
```
每次运行一段时间就会报出 Cuda Error: out of memory 
![image](https://user-images.githubusercontent.com/22980558/38859825-6cd08618-4261-11e8-8dbd-269cb40a2049.png)

请问这个是paddle的问题，还是python的问题?

**Comment by reyoung** [comment]
这个是显存超了。

**Comment by HugoLian** [comment]
那这个是什么地方内存没释放出来呢？每次大概都是读到差不多大小的数据就抛出错误。上面的代码中除了paddle.infer() 方法对我不透明，其他只是会重复给数组赋初值：ids = [] 应该不会导致内存溢出。 @reyoung

**Comment by HugoLian** [comment]
我现在不确定这个out of memory，是paddle的错误，还是python的错误。。。

**Comment by jacquesqiao** [comment]
这个问题和 https://github.com/PaddlePaddle/Paddle/issues/9972 是两个独立的问题么？@HugoLian

**Comment by HugoLian** [comment]
@jacquesqiao 这是两个独立问题，那个问题有办法解决，只是觉得需要加载不需要输出的网络比较别扭。 这个问题是每次预测了几百万数据后就会抛出out of memory，还没有定位原因。。

**Comment by jacquesqiao** [comment]
https://github.com/PaddlePaddle/Paddle/issues/7598 按照这个方法试一下

**Comment by HugoLian** [comment]
之前GPU trainer_count设置是4，和GPU数相同没有问题，设置成1之后直接报错：
![image](https://user-images.githubusercontent.com/22980558/38877262-e0310c5c-4290-11e8-8d58-61a0747f5702.png)
这是为什么呢？

另外一个线程在用cpu跑，trainer_count=7，目前还没有出错，计算数据量已经是GPU报错的2倍了。

**Comment by jacquesqiao** [comment]
单卡不应该报错，这个肯定有哪里不对

**Comment by HugoLian** [comment]
@jacquesqiao 
我发现设置trainer_counter=2， gpu=True的时候，看GPU状态TYPE都显示是C不是G
![image](https://user-images.githubusercontent.com/22980558/38882612-3261b74a-429d-11e8-92cc-0a9a0a54b775.png)

其中9153是infer得GPU程序，我设置得是2，但是还是显示占用了4个GPU
而且看GPU的memory，一直是上升的过程，没有释放
而26443这个用CPU预测的任务，memory就不变
这样正常么？

包括trainer_counter=1为什么不能跑，我也不知道是为什么。。。

**Comment by wangbin11** [comment]
以前我也遇到过这样的问题，
要不别用paddle.infer这个接口，它会每次创建一个Inference对象，这个非常耗费内存，而且不会自动释放；可以在你循环的外层，inferer = Inference(output_layer=output_layer, parameters=parameters)。
然后在循环里面，inferer.infer(field=field, input=input, feeding=feeding)
这样就不会内存爆掉了，

**Comment by HugoLian** [comment]
@wangbin11 非常感谢，后来我也尝试过你说的方法，观察了GPU的内存使用情况，也是一个一直增长的过程，不过初始占用内存没有直接使用paddle.infer多，所以三千万的数据可以一次性跑完，不知道用inferer.infer这个方法在数据量极大的时候，GPU内存是直接打满，还是到了一定大小会释放一部分。

**Comment by iyishengyoun** [comment]
@HugoLian 麻烦问一下你上面的问题解决了吗 我现在也是遇到这种问题out of memory 情景类似

**Comment by wanghaoshuang** [comment]
建议更新下paddle，后来有一些内存泄露相关的fix。比如：
https://github.com/PaddlePaddle/Paddle/pull/10358

**Comment by gongweibao** [comment]
Feel free to reopen it!

**Comment by daming-lu** [comment]
我在跑 CIFAR10 图像分类的时候也遇到过这个情况`python train.py resnet`。把 BATCH_SIZE 从 128 降到 32 就可以解决这个问题。

**Comment by HugoLian** [comment]
@daming-lu GPU的预测显存就是一直增长，不知道新版本修复这个问题没有，楼上有个方法可以比较有效缓解这个问题，不过也只是缓解，这样能涨得慢很多，基本够用。
