### ISSUE TITLE
Missing paddle.init function in benchmark Resnet script decrease CPU performance

### ISSUE THREAD

**Issue by kbinias** [PaddlePaddle/Paddle#9995]
[Resnet benchmark script](https://github.com/PaddlePaddle/Paddle/blob/develop/benchmark/fluid/resnet.py) doesn't contain paddle.init() function.
Missing this function decrease CPU performance. It runs many threads but only one is actually working.
When I add e.g. paddle.init(use_gpu=False) function, it works well - it uses all cores correctly.

**Comment by luotao1** [comment]
The reason it that `paddle.init` auto set CPU environment if have not set before.
https://github.com/PaddlePaddle/Paddle/blob/f837eee724824a7f06025152400e70a1b9a2be53/python/paddle/v2/__init__.py#L65-L72

We are manually set CPU environment in fluid now. We will add `auto set` function later.
