### ISSUE TITLE
multil-label LSTM：1、gpu loss；2、evaluate

### ISSUE THREAD

**Issue by cbstyle** [PaddlePaddle/Paddle#9996]
1、multi-label有gpu版的loss吗？
      目前用multi_binary_label_cross_entropy，则不能设置gpu_use=true;
2、multi-label评估的classification_error是怎么算的？

**Comment by jacquesqiao** [comment]
从代码上看是支持GPU的，你可能要看下具体是哪一层不支持GPU
https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/gserver/layers/CostLayer.cpp#L543
