### ISSUE TITLE
集群训练只跑了一个pass 0, batch 0，就停止不动了，也没有报错。

### ISSUE THREAD

**Issue by bianchuanxin** [PaddlePaddle/Paddle#9998]
版本是paddle.v2，在集群上提交任务做二分类，数据量较大，在train.log里监控，只跑了一个初值（Pass 0, Batch 0）就停止不动了。

请问这是什么原因？

**Comment by yeyupiaoling** [comment]
@bianchuanxin 
升级一下应该就可以了。
```
pip install paddlepaddle-gpu
```
